### PR TITLE
xtensa: support multiple toolchain versions

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Any given Xtensa CPU build will be against a specific version of the Xtensa SDK, which may not be the most recent. Since the Xtensa SDK allows multiple versions of the toolchain to be installed, let the SOC configuration define what the intended version of the toolchain is to use.

The end user just needs to set some base paths and the build system will locate the correct toolchain and CPU build.

Some additional sanitycheck targets have been added now that we can build against multiple toolchain versions.

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
Is it possible to make this generic and remove the XCC dependency, so it can be used for other compilers, in fact we already have an option that is similar in many ways that can be generalised, see TOOLCHAIN_VARIANT.

**Comment by andrewboie** [comment]
@nashif I'm not seeing how this is reusable. This Makefile is extremely XCC specific.
Can you expand your request and requirements in considerably more detail, with examples? I don't really understand where you are coming from..
Also please consider whether what you are asking for falls under the scope of this patch or ought to be just put in an enhancement JIRA..

**Comment by nashif** [comment]
> I'm not seeing how this is reusable. This Makefile is extremely specific to the Cadence SDK / XCC compiler. Can you expand your request and requirements in considerably more detail, with examples? I don't really understand where you are coming from..
Also please consider whether what you are asking for falls under the scope of this patch or ought to be just put in an enhancement JIRA..

My request for change falls under this change, it is not an enhancement request that would require a new JIRA.  We already have a Kconfig option for dealing with different versions/variant of the toolchain for the same architecture and SDK/toolchain configuration. Lets reuse that instead of introducing a new option that is specific to an architecture/compiler.

The options in question is TOOLCHAIN_VARIANT, even if this option might not sound a best match, the option you are introducing needs to be made global and generic so the next guy can use it for their toolchain/arch instead of dealing with multiple options doing the same thing defined per architecture.

**Comment by andrewboie** [comment]
@nashif  Sorry for being thick but I still don't know what you are looking for here.
Please look at Makefile.toolchain.xcc again. It's incredibly specific to the directory layout of the XCC toolchain.

> the option you are introducing

What option are you talking about?
Are you saying that you want CONFIG_XCC_TOOLCHAIN_VERSION to be replaced with CONFIG_TOOLCHAIN_VARIANT?
I can easily do that, but it does not make any of this Makefile reusable!

Maybe it would help if you did your review inline instead of a toplevel comment, I don't know what of the 4 patches here you are talking about..

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
> Maybe it would help if you did your review inline instead of a toplevel comment, I don't know what of the 4 patches here you are talking about..

Yeah, sorry about that.

**Pull request merged**
