### PR TITLE
Reduce flash wear in flash map tests

### PR DESCRIPTION
**Pull request by de-nordic**
Two commits:
 - changing flash_area_get_sectors test to just verify layout against device layout, without doing read/write to device
 - move SHA calculation to separate main file, so that only SHA is tested in SHA test scenarios and there are not basic tests doing writes/erases

### CODE REVIEW

**Review by aescolar — DISMISSED** [review]

**Comment by de-nordic** [comment]
Found one more erase to remove.

**Review by butok — APPROVED** [review]

**Review by tomi-font — APPROVED** [review]
Commit nit: `needles` => `needless`

**Review by aescolar — APPROVED** [review]

**Comment by de-nordic** [comment]
> Commit nit: `needles` => `needless`

Fixed. I am so happy that this has not removed acks.

**Comment by tomi-font** [comment]
> Fixed. I am so happy that this has not removed acks.

:+1: As long as the diff remains the same or it's just a rebase without conflict the acks are not discarded.

**Comment by butok** [comment]
Hi @de-nordic 

Just tried it on real HW.
After this PR, the test by default runs only 1 test, instead of 6. Is it intentional behavior? 

It is cause by:
```
if(NOT CONFIG_FLASH_AREA_CHECK_INTEGRITY_PSA AND NOT CONFIG_FLASH_AREA_CHECK_INTEGRITY_MBEDTLS)
  FILE(GLOB app_sources src/main.c)
else()
  FILE(GLOB app_sources src/main_sha.c)
endif()
```
As CONFIG_FLASH_AREA_CHECK_INTEGRITY_PSA  or  CONFIG_FLASH_AREA_CHECK_INTEGRITY_MBEDTLS are set to Y, the cmake always takes main_sha.c which only runs one "test test_flash_area_check_int_sha256" test.

Log for `west build -p always -b frdm_mcxn947/mcxn947/cpu0 tests/subsys/storage/flash_map`. 
After PR:
```
*** Booting Zephyr OS build v4.0.0-405-g2efc8598e39f ***
Running TESTSUITE flash_map_sha
===================================================================
START - test_flash_area_check_int_sha256
 PASS - test_flash_area_check_int_sha256 in 0.132 seconds
===================================================================
TESTSUITE flash_map_sha succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [flash_map_sha]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.132 seconds
 - PASS - [flash_map_sha.test_flash_area_check_int_sha256] duration = 0.132 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

Before:
```
*** Booting Zephyr OS build v3.7.0-190-gf09ea4753feb ***
Running TESTSUITE flash_map
===================================================================
START - test_fixed_partition_node_macros
 PASS - test_fixed_partition_node_macros in 0.001 seconds
===================================================================
START - test_flash_area_check_int_sha256
 PASS - test_flash_area_check_int_sha256 in 0.127 seconds
===================================================================
START - test_flash_area_disabled_device
 PASS - test_flash_area_disabled_device in 0.001 seconds
===================================================================
START - test_flash_area_erase_and_flatten
Flash area info:
        pointer:         0x30002ea4
        offset:  1081344
        size:    1015808
 PASS - test_flash_area_erase_and_flatten in 7.912 seconds
===================================================================
START - test_flash_area_erased_val
 PASS - test_flash_area_erased_val in 0.001 seconds
===================================================================
START - test_flash_area_get_sectors
 PASS - test_flash_area_get_sectors in 0.886 seconds
===================================================================
TESTSUITE flash_map succeeded
 
------ TESTSUITE SUMMARY START ------
 
SUITE PASS - 100.00% [flash_map]: pass = 6, fail = 0, skip = 0, total = 6 duration = 8.928 seconds
 - PASS - [flash_map.test_fixed_partition_node_macros] duration = 0.001 seconds
 - PASS - [flash_map.test_flash_area_check_int_sha256] duration = 0.127 seconds
 - PASS - [flash_map.test_flash_area_disabled_device] duration = 0.001 seconds
 - PASS - [flash_map.test_flash_area_erase_and_flatten] duration = 7.912 seconds
 - PASS - [flash_map.test_flash_area_erased_val] duration = 0.001 seconds
 - PASS - [flash_map.test_flash_area_get_sectors] duration = 0.886 seconds
 
------ TESTSUITE SUMMARY END ------
 
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Comment by de-nordic** [comment]
Hello @butok 

I have intended to separately run SHA from other test to not wear down devices, where only sha is supposed to be tested, with unneeded write/erase operations.
The SHA tests is supposed to run once for mbedTLS and once for PSA, separately from other tests scenarios.

If that is somehow broken please report.

**Comment by butok** [comment]
> Hello @butok
> 
> I have intended to separately run SHA from other test to not wear down devices, where only sha is supposed to be tested, with unneeded write/erase operations. The SHA tests is supposed to run once for mbedTLS and once for PSA, separately from other tests scenarios.
> 
> If that is somehow broken please report.

OK. But there is no a test configuration in testcase.yaml to run the main.c tests.

**Comment by de-nordic** [comment]
> 
> OK. But there is no a test configuration in testcase.yaml to run the main.c tests.

The default one does not run anymore?

**Comment by butok** [comment]
> > OK. But there is no a test configuration in testcase.yaml to run the main.c tests.
> 
> The default one does not run anymore?

The default behavior has been described. Otherwise I wouldn't have added the comment ;)
 https://github.com/zephyrproject-rtos/zephyr/pull/81091#issuecomment-2485437652

**Comment by de-nordic** [comment]
> > > OK. But there is no a test configuration in testcase.yaml to run the main.c tests.
> > 
> > 
> > The default one does not run anymore?
> 
> The default behavior has been described. Otherwise I wouldn't have added the comment ;) [#81091 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/81091#issuecomment-2485437652)

I will take a look, but I am quite sure that I have 3 scenarios running each time a test the dir, which includes the base one and two separate sha tests.

**Comment by butok** [comment]
> > > > OK. But there is no a test configuration in testcase.yaml to run the main.c tests.
> > > 
> > > 
> > > The default one does not run anymore?
> > 
> > 
> > The default behavior has been described. Otherwise I wouldn't have added the comment ;) [#81091 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/81091#issuecomment-2485437652)
> 
> I will take a look, but I am quite sure that I have 3 scenarios running each time a test the dir, which includes the base one and two separate sha tests.

CONFIG_FLASH_AREA_CHECK_INTEGRITY_MBEDTLS is Y for the default case, for me.

**Comment by de-nordic** [comment]
> 
> The default behavior has been described. Otherwise I wouldn't have added the comment ;) [#81091 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/81091#issuecomment-2485437652)

You are right, the fix is here: https://github.com/zephyrproject-rtos/zephyr/pull/81642

**Pull request merged**
