### PR TITLE
audio: intel dmic: get dma properties from devicetree

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
@dcpleung & @sathishkuttan this is starts of cleaning up dma usage in dmic driver to use devicetree properly.

What I'm not clear on is use of dma-channel & dma-slot for dmic.  Also would appreciate comments on the `dma-names` property.

**Comment by dcpleung** [comment]
> What I'm not clear on is use of dma-channel & dma-slot for dmic. Also would appreciate comments on the `dma-names` property.

Maybe just leave them as-is for now? The DMA controller, IIRC, is wired for specific function for each channel, so there is no need to make them configurable.

**Comment by galak** [comment]
> > 
> 
> Maybe just leave them as-is for now? The DMA controller, IIRC, is wired for specific function for each channel, so there is no need to make them configurable.

Works for me, any comments on the dma-names?

**Comment by dcpleung** [comment]
> Works for me, any comments on the dma-names?

`rxa` and `rxb`? This corresponds to which is used in `soc/xtensa/intel_s1000/soc.h` as `DMA_CHANNEL_DMIC_RXA` and `DMA_CHANNEL_DMIC_RXB`.

**Comment by galak** [comment]
> `rxa` and `rxb`? This corresponds to which is used in `soc/xtensa/intel_s1000/soc.h` as `DMA_CHANNEL_DMIC_RXA` and `DMA_CHANNEL_DMIC_RXB`.

Right, I made up the names `rx-a` and `rx-b` so asking if those names made sense or should I change them to `rxa` and `rxb`

**Comment by dcpleung** [comment]
> Right, I made up the names `rx-a` and `rx-b` so asking if those names made sense or should I change them to `rxa` and `rxb`

`rx-a` and `rx-b` look good to me.

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
