### PR TITLE
Remove case ranges

### PR DESCRIPTION
**Pull request by pfl**
Remove five case ranges/GNUisms, four in a led driver and one in printk as reported in #11594

### CODE REVIEW

**Review by ceolin — APPROVED** [review]

**Comment by ceolin** [comment]
#9893

**Comment by nashif** [comment]
> #9893

does this fix the issue above?

Need Fixes #9893 in the body or a commit to associate and close automatically once this is merged.

**Comment by pfl** [comment]
> does this fix the issue above?

This one fixes 2) in #11594

**Comment by ceolin** [comment]
@nashif it does not fix all issues. But fix some violations

**Review by tyrantlizard77 — APPROVED** [review]

**Pull request merged**
