### PR TITLE
drivers: i2c: Support for devices with 16 bit internal addressing

### PR DESCRIPTION
**Pull request by aasinclair**
New functions added to support I2C devices with 16 bit internal addresses.  Implements enhancement #40553.

### CODE REVIEW

**Comment by aasinclair** [comment]
I have just noticed that this functionality existed previously but was removed:
   https://github.com/zephyrproject-rtos/zephyr/pull/12588

Is the consensus still to keep this in the drivers?  If so I will close this PR.

**Comment by carlescufi** [comment]
> I have just noticed that this functionality existed previously but was removed: #12588
> 
> Is the consensus still to keep this in the drivers? If so I will close this PR.

That was a long time ago so I believe it makes sense to bring this up again.
To start with it'd be great to get @teburd's opinion as a maintainer. Based on his feedback we can decide whether to take this to the Architecture WG meeting.

**Comment by carlescufi** [comment]
Architecture WG:

- @gmarull mentions that there's a new Nordic PMIC that uses 16-bit addressing
- @henrikbrixandersen states that both little and big endian addresses are used
- @henrikbrixandersen also states that many of our drivers might not support `I2C_MSG_RESTART`, which would mean not being able to implement those APIs, but also means that they are also limited in many other ways
-

**Comment by aasinclair** [comment]
Based on the feedback from the architecture WG and previous commentary in #12588 I am going to close this pull request.

Of particular concern is the issue highlighted by @teburd, which means that there is no easy way to create a helper function for a write of arbitrary length that will work on all devices.  The only way to do it portably is for the driver to combine the address and data in a contiguous buffer.

I'll keep the message packing in the driver and add these details to the associated improvement ticket.

**Comment by teburd** [comment]
I have some commentary #41889 that is relevant as well, and while this is closed now its useful to link these things.

**Pull request closed without merging**
