### PR TITLE
Add functions regarding CoAP block options

### PR DESCRIPTION
**Pull request by LukasWoodtli**
Some utility functions regarding CoAP options:

- Possibility to remove a CoAP option from a message
- Check if a block option is avalable in a message
- Documentation improvements
- Tests

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
LGTM, only some style-related nitpicks.

**Comment by manuargue** [comment]
@LukasWoodtli fyi not sure why I (and so many others?) got pulled into this review. I removed myself and looks like it also unintentionally removed more people as well 🤷

**Comment by LukasWoodtli** [comment]
> @LukasWoodtli fyi not sure why I (and so many others?) got pulled into this review. I removed myself and looks like it also unintentionally removed more people as well 🤷

Thanks for the information. I’m not sure why this happened.

**Review by rlubos — APPROVED** [review]
LGTM

**Review by rerickson1 — APPROVED** [review]

**Pull request merged**
