### PR TITLE
doc: getting_started: Modernize macOS instructions

### PR DESCRIPTION
**Pull request by carlescufi**
Modernize macOS instructions to fit the latest packages offered by
Homebrew and macOS High Sierra.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by nashif** [comment]
hmm #6934?

**Comment by carlescufi** [comment]
@nashif oh sorry, I didn't realize. Can you take my changes, or do you want me to take yours?

**Comment by nashif** [comment]
> @nashif oh sorry, I didn't realize. Can you take my changes, or do you want me to take yours?

i was first :)

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by carlescufi** [comment]
@nashif ok! let's merge your PR and  then I will rebase mine :)

**Comment by nashif** [comment]
no i am fine with this...

**Pull request merged**
