### PR TITLE
tests: kernel: fifo_timeout: Do not print status messages during tests

### LINKED ISSUE #52009: tests: kernel: fifo: fifo_timeout: kernel.fifo.timeout fails on nrf5340dk_nrf5340_cpuapp
**Describe the bug**
The tests/kernel/fifo/fifo_timeout/kernel.fifo.timeout fails

Observed for
- nrf5340dk_nrf5340_cpuapp

Occurrence: 1/14

**To Reproduce**
1. have nrf5340dk_nrf5340 connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/kernel/fifo/fifo_timeout -p nrf5340dk_nrf5340--device-testing --device-serial /dev/ttyACM2 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.2.0-1275-g8db84cfa6a95 ***
Running TESTSUITE fifo_timeout
===================================================================
START - test_timeout_non_empty_fifo
PASS - test_timeout_non_empty_fifo in 0.001 seconds
===================================================================
TESTSUITE fifo_timeout succeeded
Running TESTSUITE fifo_timeout_1cpu
===================================================================
START - test_timeout_empty_fifo
PASS - test_timeout_empty_fifo in 0.012 seconds
===================================================================
START - test_timeout_fifo_thread
PASS - test_timeout_fifo_thread in 0.012 seconds
===================================================================
START - test_timeout_threads_pend_fail_on_fifo
thread (q order: 0, t/o: 20, fifo 0x20000980)
thread (q order: 1, t/o: 40, fifo 0x20000980)
thread (q order: 2, t/o: 0, fifo 0x20000980)
thread (q order: 3, t/o: 10, fifo 0x20000980)
thread (q order: 4, t/o: 30, fifo 0x20000980)
PASS - test_timeout_threads_pend_fail_on_fifo in 0.073 seconds
===================================================================
START - test_timeout_threads_pend_on_dual_fifos
thread (q order: 0, t/o: 0, fifo 0x20000994)
thread (q order: 5, t/o: 10, fifo 0x20000980)
FAIL - test_multiple_threads_pending@186.  *** thread 3 woke up, expected 2
Assertion failed at ../../../../../../../../../zephyr/zephyr/tests/kernel/fifo/fifo_timeout/src/main.c:467: fifo_timeout_1cpu_test_timeout_threads_pend_on_dual_fifos: rv not equal to TC_PASS
FAIL - test_timeout_threads_pend_on_dual_fifos in 0.090 seconds
===================================================================
START - test_timeout_threads_pend_on_fifo
FAIL - test_multiple_threads_pending@186.  *** thread 2 woke up, expected 0
Assertion failed at ../../../../../../../../../zephyr/zephyr/tests/kernel/fifo/fifo_timeout/src/main.c:447: fifo_timeout_1cpu_test_timeout_threads_pend_on_fifo: rv not equal to TC_PASS
FAIL - test_timeout_threads_pend_on_fifo in 0.052 seconds
===================================================================
TESTSUITE fifo_timeout_1cpu failed.
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [fifo_timeout]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.001 seconds
- PASS - [fifo_timeout.test_timeout_non_empty_fifo] duration = 0.001 seconds
SUITE FAIL -  60.00% [fifo_timeout_1cpu]: pass = 3, fail = 2, skip = 0, total = 5 duration = 0.239 seconds
- PASS - [fifo_timeout_1cpu.test_timeout_empty_fifo] duration = 0.012 seconds
- PASS - [fifo_timeout_1cpu.test_timeout_fifo_thread] duration = 0.012 seconds
- PASS - [fifo_timeout_1cpu.test_timeout_threads_pend_fail_on_fifo] duration = 0.073 seconds
- FAIL - [fifo_timeout_1cpu.test_timeout_threads_pend_on_dual_fifos] duration = 0.090 seconds
- FAIL - [fifo_timeout_1cpu.test_timeout_threads_pend_on_fifo] duration = 0.052 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 12c13573907da6eb2683456106d8c776
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.14.1
 - Commit SHA or Version used: v3.2.0-1275-g8db84cfa6a95

The same test works well for:
nrf52840dk_nrf52840, nrf52dk_nrf52832, nrf9160dk_nrf9160, nrf5340dk_nrf5340_cpunet

### PR DESCRIPTION
**Pull request by anangl**
... to avoid undesirable delays in waking up of the threads on
scheduled timeouts. In specific configurations such additional load
of the CPU can be even harmful to the test. This was observed for
nRF platforms where the UART_NRF_DK_SERIAL_WORKAROUND Kconfig option
was enabled.
All calls to TC_PRINT() in this test suite are replaced with calls to
LOG_DBG(), so the status messages are not printed by default, but they
can be enabled if needed by changing CONFIG_LOG_DEFAULT_LEVEL.

On the occasion, correct also one misleading error message.

Fixes #52009.

### CODE REVIEW

**Review by andyross — DISMISSED** [review]
On the whole there's nothing wrong with adjusting timeouts to accomodate slow hardware.  But those numbers (10-40ms) were frankly very padded already.

Are we really unable to get a context switch working in 10ms on these boards?  That points to a performance regression somewhere, are there details on that?  If it's well-understood and not something that can be fixed, then it would be good to see it documented (here in the PR would be OK if it doesn't belong anywhere else).  If not, maybe we can open a bug?

But my intuition says that the analysis is actually wrong here and what we have is not a performance glitch but an aliasing issue converting between (decimal!) ms and the 32768 Hz clock that can't represent them exactly.  And if that's the case the fix is absolutely not to pad the timeouts but to adjust them to work in ticks instead.

**Comment by peter-mitsis** [comment]
Why are we even introducing a dependency on the UART in a success path for a fifo test? That seems odd.

Perhaps the test should be tweaked such that the print statements only occur on the failure paths and between tests? I'm not seeing anything special that the test runner is looking for in those descriptive updates. Their primary purpose appears to be for human convenience. However, if the test is primarily used by the automated infrastructure, that kind of output seems to be superfluous. If we really want to keep them, perhaps have a verbose option that can be selected, but by default have them off.

**Comment by andyross** [comment]
Ah, OK.  So it's the output uart seeing overruns, and our workaround is putting a k_busy_wait() into the logging output path, which is slowing everything down.   Regarding the original workaround: can't you spin for space in the FIFO in the driver instead of doing an unconditional multi-millisecond wait?  That would minimize the impact, and I bet anything would fix this.  DOS/PC utilities spent decades spinning on their serial ports, it's a well-tested technique. :)

As for this test: yeah, I guess my sense is we don't want to be increasing timeouts (especially ones this long) just to work around one platform's performance problems.  If you really need a pass and can't do anything at the driver level, maybe you could make it settable and predicate the change on that one nRF uart flag?

**Comment by nordic-krch** [comment]
So maybe those `TC_PRINT`s could be converted to `LOG_DBG`s?

**Comment by anangl** [comment]
> So maybe those `TC_PRINT`s could be converted to `LOG_DBG`s?

Yes. done.

**Review by dcpleung — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
