### PR TITLE
sntp_client for cc3220sf_launchxl

### PR DESCRIPTION
**Pull request by vanti**
This PR adds support for cc3220sf_launchxl to the sntp_client sample.

Some modifications are made to the example to make IPv6 and NET_CONFIG_SETTINGS optional, since these are not currently working in the cc3220sf wifi driver implementation.

### CODE REVIEW

**Comment by pfalcon** [comment]
> NET_CONFIG_SETTINGS optional, since these are not currently working in the cc3220sf wifi driver implementation.

NET_CONFIG_SETTINGS isn't supported on cc3220? But that's one of the most basic networking sub-subsystems in general, and for samples in particular. Almost every sample uses it, do you intend to patch them all? Why the choice is on making such patches instead of implementing NET_CONFIG_SETTINGS support?

The specific commit message:

> In this commit, a config.h header file is added to support the case
when the NET_CONFIG_SETTINGS is not used

should mention that this is being done to allow cc3220 support. Actually, I'm a bit proponent of detailed, well-separated changes, but here I'd say it might be better to squash the two commits together.

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by jukkar** [comment]
>  but here I'd say it might be better to squash the two commits together.

Please do not squash the patches, there is now two different changes which is ok in this case.

**Comment by vanti** [comment]
> NET_CONFIG_SETTINGS isn't supported on cc3220? But that's one of the most basic networking sub-subsystems in general, and for samples in particular. Almost every sample uses it, do you intend to patch them all? Why the choice is on making such patches instead of implementing NET_CONFIG_SETTINGS support?

@pfalcon Implementing NET_CONFIG_SETTINGS fully is non-trivial, as far as I understand. As @GAnthony mentioned in #11889, NET_CONFIG_SETTINGS forces hardcoded values for IP address, which is not desired for an offload driver which already handles DHCP, and brings in other unnecessary functions. It is a current limitation in the SimpleLink driver where we do not support static IP addresses that are set via NET_CONFIG_SETTINGS. So you are right, I'd have to patch the samples that are supported on cc3220xl_launchxl. Fortunately some of them were already following this model where NET_CONFIG_SETTINGS may or may not be defined (e.g. mqtt_publisher), so I am simply following suit.

**Comment by vanti** [comment]
Updated commit message per comment from @pfalcon, and fixed a build issue in config.h.

**Pull request merged**
