### PR TITLE
Remove legacy MQTT library

### PR DESCRIPTION
**Pull request by jukkar**

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]

**Review by dbkinder — CHANGES_REQUESTED** [review]
doc/subsystems/networking/overview.rst (lines 70-72) reference the coap client and server samples that were deleted.  Should overview.rst be edited to delete references to these samples, or are there replacement samples?

**Review by rlubos — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]

**Comment by jukkar** [comment]
Postponing the removal until end of January to let all the users to migrate.

**Review by dbkinder — APPROVED** [review]
It would appear the previously deleted samples are back now, so the doc build is no longer failing.

**Comment by dbkinder** [comment]
Note though that the current doxygen defgroup ``mqtt_socket`` is not referenced by a Sphinx doxygengroup directive so the API documentation is missing.

**Comment by jukkar** [comment]
> Note though that the current doxygen defgroup `mqtt_socket` is not referenced by a Sphinx doxygengroup directive so the API documentation is missing.

@rlubos Can you send a PR that fixes the mqtt_socket API documentation issue?

**Comment by jukkar** [comment]
> Or shall I remove the reference to the old API straightaway?

That sounds like a good plan, so remove the old API from documentation and replace it with the new one.

**Pull request merged**
