### PR TITLE
kernel: add closing comments to config endifs

### PR DESCRIPTION
**Pull request by simhein**
No functional changes.
Just adding closing comments to the endifs with the configuration information to make it easier to navigate the code.

### CODE REVIEW

**Review by nashif — DISMISSED** [review]

**Comment by simhein** [comment]
last changes fix CI compliance check

**Comment by simhein** [comment]
changes fix CI compliance checks

**Review by nashif — DISMISSED** [review]

**Review by cfriedt — DISMISSED** [review]

**Review by TaiJuWu — APPROVED** [review]
This work is very useful, thanks.

**Review by TaiJuWu — APPROVED** [review]

**Comment by simhein** [comment]
rebased to resolve conflicts

**Comment by simhein** [comment]
@andyross ping to have a look at this PR 😃

**Review by kartben — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
