### PR TITLE
CI: Reschedule codecov workflow

### PR DESCRIPTION
**Pull request by gbarkadiusz**
Propose of reschedule the codecov workflow from '6:25 and 18:25, Monday-Friday' to 'everyday at 06:25'.

### CODE REVIEW

**Comment by nashif** [comment]
I am missing the "Why" in the commit message.

**Comment by fabiobaltieri** [comment]
> That's a good question. I'm trying to understand why the coverage data are generated twice a day, instead of once a day. That's why, this "asking" pr.

Isn't that what the cron spec says now?

**Comment by gbarkadiusz** [comment]
> > That's a good question. I'm trying to understand why the coverage data are generated twice a day, instead of once a day. That's why, this "asking" pr.
> 
> Isn't that what the cron spec says now? Or are you asking why it was done like that?

Yes, I'm asking why it was done like that. Is there any reason that it runs two times a day instead of once a day?

**Comment by fabiobaltieri** [comment]
> Yes, I'm asking why it was done like that. Is there any reason that it runs two times a day instead of once a day?

Got it, looks like it used to be three per day and got scaled down in https://github.com/zephyrproject-rtos/zephyr/pull/66654/commits/244ae1f28784ed72a5092d49126c212f314715e6, guess to save resources? @nashif

**Comment by gbarkadiusz** [comment]
> > Yes, I'm asking why it was done like that. Is there any reason that it runs two times a day instead of once a day?
> 
> Got it, looks like it used to be three per day and got scaled down in [244ae1f](https://github.com/zephyrproject-rtos/zephyr/commit/244ae1f28784ed72a5092d49126c212f314715e6), guess to save resources? @nashif

Thank you for your investigation. I've noticed that there was a difference between the values of coverage in data comes from 6 AM and 6 PM on 15.05 and 16.05. It can be related with [#72807](https://github.com/zephyrproject-rtos/zephyr/issues/72807)
I didn't find the direct reason for that difference.
I'm trying to automate the process of gathering coverage data and presenting it.
That's why my proposal is to reschedule this workflow to once a day.

There's that mentioned difference.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/acholewx/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/acholewx/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>


Component | Coverage at 16.05 6:25 PM | Coverage at 16.05 6:25 AM | Diff
-- | -- | -- | --
acpi | 19.09 | 9.54 | -9.54
bluetooth | 40.36 | 11.87 | -28.49
lib | 84.41 | 79.69 | -4.73
libraries | 84.41 | 79.69 | -4.73
printk | 92.14 | 83.29 | -8.85
testing | 81.10 | 72.20 | -8.90
utilities | 92.03 | 79.19 | -12.83
  |   |   |  
Component | Coverage at 15.05 6:25 PM | Coverage at 15.05 6:25 AM | Diff
acpi | 19.09 | 9.87 | -9.22
bluetooth | 40.35 | 8.39 | -31.96
lib | 84.41 | 80.14 | -4.28
libraries | 84.41 | 80.14 | -4.28
printk | 92.14 | 83.89 | -8.25
testing | 81.10 | 72.20 | -8.90
utilities | 92.03 | 80.48 | -11.55



</body>

</html>


Maybe this issue should be solved, but so far I've proposed to reschedule this workflow once a day. It will be easier to deal with the coverage data per day.

**Review by nashif — CHANGES_REQUESTED** [review]
I do not see how this helps with anything, you can get the data daily if you wish. Running multiple times gives us another checkpoint during the day if something goes wrong.

**Comment by gbarkadiusz** [comment]
I get it, so, I'm closing this pr.

**Comment by gbarkadiusz** [comment]
I'd like to reconsider this thing again.
Ok, if we want to like double check if something goes wrong.
So, why we run this workflow only on workdays instead of twice a day but every day.
Assuming that the development is going on weekends as well.

**Comment by fabiobaltieri** [comment]
> So, why we run this workflow only on workdays instead of twice a day but every day.
> Assuming that the development is going on weekends as well.

May not be a bad idea considering developer may be in any possible timezone.

**Review by fabiobaltieri — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by simhein — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
> I imagine cost is less of a factor with the new infrastructure setup (@stephanosio can you comment on that?)

Running the codecov workflow on the weekends will have a negligible effect on the overall CI operating cost.

**Pull request merged**
