### PR TITLE
tests: can: api: Add MCP2515 DT label to the device name list

### PR DESCRIPTION
**Pull request by alexanderwachter**
Add DT_INST_0_MICROCHIP_MCP2515_LABEL to the list of possible
device labels.

### CODE REVIEW

**Review by karstenkoenig — APPROVED** [review]
I definitely ran these tests at some point, I guess that #ifdef tree was introduced at some point with CAN_0 and CAN_1 names? Anyways, thanks for adding the mcp2515 into the drivers tests :-)

**Comment by alexanderwachter** [comment]
@karstenkoenig it was introduced for the flexcan drivers. I tried to test the optimizations for the mcp2515 and was surprised that the test didn‘t work.

**Comment by henrikbrixandersen** [comment]
I would prefer adding a `dts_fixup.h` file to the MCP2515 equipped shields instead.

**Comment by karstenkoenig** [comment]
Like this?
https://github.com/karstenkoenig/zephyr/commit/33dd91dabb61c5fe68f302f4931ea0e6b400bdd1

I wasn't even aware it works for shields, but yeah seems to be pulled in and compiles with 'DT_CAN_1_NAME' being set for the test. But is this really a nice way to do this? Not saying hooking up a MCP2515 to an SOC with onboard CAN controller would make sense, but this would definitely be broken now.

The code in the test is trying to 'grab any CAN controller there is'. The dts_fixup is just improving this by keeping the number of DT defines to look through smaller, but only when using a shield. Not a fan and I'd prefer the original solution. Or a more generic DT based approach for 'get me the first instance for X possible', but not sure that is a common usecase except for samples or testcaes.

**Comment by henrikbrixandersen** [comment]
@galak What is your opinion on this? (dts fixup in shields vs. hardcoded labels)?

**Review by ioannisg — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
> @galak What is your opinion on this? (dts fixup in shields vs. hardcoded labels)?

I'm fine with this for now until we clean things up across the board.

**Pull request merged**
