### PR TITLE
modules: mbedtls: Update with PSA dependencies

### PR DESCRIPTION
**Pull request by mfischer**
mbedtls wants matching PSA configuration options for some of the elliptic curve algoritmhs nowadays.

Thse checks are encoded in mbedTLS' check_config.h header.

### CODE REVIEW

**Comment by mfischer** [comment]
Updated the commit message to remove the typos.

@d3zd3z this seems like a pretty non controversial change

**Comment by mfischer** [comment]
@cfriedt @d3zd3z ping

**Comment by MaureenHelm** [comment]
@ceolin @d3zd3z @ithinuel can you take a look?

**Comment by MaureenHelm** [comment]
> @ceolin @d3zd3z @ithinuel can you take a look?

ping

**Comment by ithinuel** [comment]
@valeriosetti how does this interact with https://github.com/zephyrproject-rtos/zephyr/pull/72243 ?

**Comment by valeriosetti** [comment]
> @valeriosetti how does this interact with #72243 ?

The scope of #72243 is exactly to introduce support for all the `PSA_WANT` symbols used in MbedTLS and, more in general, by any crypto client, so I think that PR can help here.

**Pull request closed without merging**
