### PR TITLE
hwmv2: cmake: Use only one defconfig

### PR DESCRIPTION
**Pull request by 57300**
Commit 84a7f75a4e86a10470ef9d273be72e5a3e4931ef enabled sourcing several defconfig files for a single board, ordered from least to most specific to the selected board variant. The assumption was: given two targets of the form `<board>/<soc>` and `<board>/<soc>/<variant>`, the latter would naturally inherit configuration from the former.

However, having multiple defconfigs doesn't make sense, and in practice, they tend to clash with each other, which complicates porting.

Another motivation for doing that was to make `<board>_<soc>_defconfig` optional, so that `<board>_defconfig` could be used instead, if present. This can still be achieved by constraining the `_defconfig` lookup to only use the most specific file available, just like `.dts` lookup.

Relevant changes to `zephyr_file()` have been reverted.

This means that `<board>_<revision>.conf` overlays, which were meant to be deprecated, are no longer replaced by revision-specific defconfigs, so they need to be un-deprecated. None of the currently ported **(merged)** boards are affected by this change.

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
> However, having multiple defconfigs doesn't make sense, and in practice, they tend to clash with each other, which complicates porting.

In which way does two `_defconfig`s clash more than a `_defconfig` + `.conf` ?
Both are identical in terms of format, that is, both uses:
```
CONFIG_<setting>=<value>
```
and both are applied as arguments to Kconfiglib, for example:
```
kconfig.py --zephyr-base=<path>/zephyr --handwritten-input-configs <path>/Kconfig <build>/zephyr/.config <build>/zephyr/include/generated/autoconf.h <build>/zephyr/kconfig/sources.txt
<boards>/renesas/rzt2m_starterkit/rzt2m_starter_kit_defconfig
<boards>/renesas/rzt2m_starterkit/rzt2m_starter_kit_renesas_rzt2m_defconfig
<zephyr_base>/samples/hello_world/prj.conf
<zephyr_base>/samples/hello_world/boards/rzt2m_starter_kit.conf
<zephyr_base>/samples/hello_world/boards/rzt2m_starter_kit_renesas_rzt2m.conf
```

So please explain why substituting a `_defconfig` with `.conf` file in above will make kconfig less conflicting ?

> Another motivation for doing that was to make <board>_<soc>_defconfig optional, so that <board>_defconfig could be used instead, if present. 

True, but also to simplify naming, so that users won't need to think about whether to use `.conf` or `_defconfig`.
With the #68724 users will have to consider whether to use `_defonconfig` or `.conf`.

As well as when using `plank_foo_defconfig` users must include the settings they require from `plank_defconfig`, whereas if they use `plank_foo.conf`, the file is used together with `plank_defconfig`.
Not something making it easier to understand the basic configuration of a board.

Similar, if a plank board contains socA and socB, and variant `foo` and `bar` with following files:
```
|-- plank_defconfig
|-- plank_socA.conf
```
then when building for `socA/foo`, then `plank_defconfig` + `plank_socA.conf`, are used together.

If someone then adds `plank_socA_foo_defconfig`, then suddenly `plank_socA.conf` is no longer used.
Now: 
```
|-- plank_defconfig
|-- plank_socA_foo_defconfig
|-- plank_socA.conf
```

Not convinced the proposed complexity in this PR is justified, and to me it seems the content of the `_defconfig`s from https://github.com/zephyrproject-rtos/zephyr/pull/68792#discussion_r1484041804 should instead be properly adjusted:
> qemu_cortex_a53/qemu_cortex_a53/smp produces Kconfig warnings, because qemu_cortex_a53_defconfig conflicts with qemu_cortex_a53_qemu_cortex_a53_smp_defconfig.

**Comment by tejlmand** [comment]
> to me it seems the content of the `_defconfig`s from [#68792 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/68792#discussion_r1484041804) should instead be properly adjusted:
> 
> > qemu_cortex_a53/qemu_cortex_a53/smp produces Kconfig warnings, because qemu_cortex_a53_defconfig conflicts with qemu_cortex_a53_qemu_cortex_a53_smp_defconfig.

I see the problem.
```
warning: QEMU_ICOUNT_SHIFT (defined at boards/Kconfig:62) was assigned the value '4' but got the
value ''. Check these unsatisfied dependencies: QEMU_ICOUNT (=n).
```

we are disabling a dependency setting, so that `QEMU_ICOUNT_SHIFT` is no longer valid to set.
Will do some thinking.

**Comment by tejlmand** [comment]
actually, this is not a new issue.
Same issue exists with board Kconfig fragment, for example on `zephyr/main`, try creating:
```
# samples/hello_world/boards/qemu_cortex_a53.conf
CONFIG_QEMU_ICOUNT=n
CONFIG_QEMU_ICOUNT_SLEEP=n
```
and build hello_world as:
```
$ cmake -DBOARD=qemu_cortex_a53 -Bbuild samples/hello_world/
...
Parsing <path>/zephyr/Kconfig
Loaded configuration '<path>/zephyr/boards/arm64/qemu_cortex_a53/qemu_cortex_a53_defconfig'
Merged configuration '<path>/zephyr/samples/hello_world/prj.conf'
Merged configuration '<path>/zephyr/samples/hello_world/boards/qemu_cortex_a53.conf'
Configuration saved to '<path>/zephyr/build/zephyr/.config'
...
warning: QEMU_ICOUNT_SHIFT (defined at boards/Kconfig:67) was assigned the value '4' but got the
value ''. Check these unsatisfied dependencies: QEMU_ICOUNT (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_QEMU_ICOUNT_SHIFT and/or look up
QEMU_ICOUNT_SHIFT in the menuconfig/guiconfig interface. The Application Development Primer, Setting
Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be helpful
too.
```

so it's a more fundamental problem, and i'm not sure the right way to solve this is by increasing the complexity of board conf files.

**Comment by 57300** [comment]
> So please explain why substituting a `_defconfig` with `.conf` file in above will make kconfig less conflicting ?

Outside of revisions, I didn't suggest anything about `_defconfig` vs. `.conf`. Obviously that wouldn't make a difference.

The real issue is "false inheritance". `qemu_cortex_a53` must have its own defconfig, and `qemu_cortex_a53//smp` has a different defconfig, but the two aren't composable, as you've noticed in your second comment.

A similar problem occurs for `mps3` and `mps3//ns`.

Therefore, it's wrong to assume that a board variant can always inherit configuration from its base.

> when building for `socA/foo`, then `plank_defconfig` + `plank_socA.conf`, are used together.
> (...)
> If someone then adds `plank_socA_foo_defconfig`, then suddenly `plank_socA.conf` is no longer used.

I don't know what branch you're on, because none of that is applicable to `collab-hwm` today.

**Comment by tejlmand** [comment]
> Therefore, it's wrong to assume that a board variant can always inherit configuration from its base.

just as wrong as to assume a `boards/<board>.conf` in a sample can always adjust a configuration for a board.
That is the root of the problem, and what we should be looking into.

> I don't know what branch you're on, because none of that is applicable to collab-hwm today.

correct, but that would have to be the outcome if we want to support same behavior as for `.dts` + `.overlay` and ensure that it's possible to only make adjustments.

Just like a board revision conf would not support "removal" of `QEMU_ICOUNT_SHIFT` in the case above.

**Comment by 57300** [comment]
> just as wrong as to assume a `boards/<board>.conf` in a sample can always adjust a configuration for a board.
> That is the root of the problem, and what we should be looking into.

Firstly, that's not a problem specific to HWMv2; you can always create sample overlays that clash with board defconfigs. Secondly, no matter what the sample configuration is, the board configuration should be consistent within itself.

From another perspective, the root issue is: you can't unset an int in Kconfig. But that's not an issue I'm interested in solving.

**Comment by tejlmand** [comment]
> > Therefore, it's wrong to assume that a board variant can always inherit configuration from its base.
> 
> just as wrong as to assume a `boards/<board>.conf` in a sample can always adjust a configuration for a board. That is the root of the problem, and what we should be looking into.

seems to be an unintended side-effect of: https://github.com/zephyrproject-rtos/zephyr/pull/20742
One thing is to ensure we don't assign values to disabled fields in `.conf` files, another is to still allow users / samples to disable otherwise enabled settings.

The warning even occurs if someone tries to set `CONFIG_QEMU_ICOUNT=n` in prj.conf.

**Comment by tejlmand** [comment]
>  you can always create sample overlays that clash with board defconfigs.

or you can put it another way, a board defconfig should not prevent a sample from disabling a feature if that feature is not crucial to the board.

If looking at this specific case, the `boards/qemu/qemu_cortex_a53/Kconfig.defconfig` could instead be used to set a different default int value, like:
```
config QEMU_ICOUNT_SHIFT
        default 4
        depends on QEMU_ICOUNT
```

No reason to do this in `_defconfig` if it break inheritance or samples ability to adjust a value.
In fact, this pattern is exactly what is used by other `Kconfig.defconfig`s, such as: qemu_cortex_a9 and qemu_x86.

**Comment by 57300** [comment]
> ```
> config QEMU_ICOUNT_SHIFT
>         default 4
>         depends on QEMU_ICOUNT
> ```

That works, although it would be nice if the migration script could make these kind of adjustments as well.
Applied in https://github.com/zephyrproject-rtos/zephyr/pull/68805 for now.

**Pull request closed without merging**
