### PR TITLE
Add USB support for MCX N947

### PR DESCRIPTION
**Pull request by mmahadevan108**
This uses the old USB framework. We would need to transition to USB Next once the USB driver is merged.

### CODE REVIEW

**Review by decsny — CHANGES_REQUESTED** [review]
need to update doc page

**Comment by danieldegrasse** [comment]
> need to update doc page

Adding to this, should add `- usb_device` to the board's supported YAML definitions

**Comment by mmahadevan108** [comment]
> need to update doc page

Thanks, updated doc page.

**Review by danieldegrasse — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Review by decsny — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
@jfischer-no I'm assigning this to me since it is a change to an existing intree USB driver to add support for this SOC.

**Pull request merged**
