### PR TITLE
Enable tristate Kconfig options

### PR DESCRIPTION
**Pull request by lyakh**
kconfiglib.py has a hard dependency on CONFIG_MODULES to support 'm' values for tristate Kconfig options. It's a logical companion for but can also be used with other configurations.

### CODE REVIEW

**Review by pillo79 — DISMISSED** [review]
I see the potential of having tristate options in Zephyr, and it's OK to keep the `CONFIG_MODULES` / `=m` names as they are widely used in Kconfig-based projects. 
Minor tip: I would add a `depends on LLEXT` so that it is hidden unless dynamic code loading is actually used in the build.

**Review by tejlmand — DISMISSED** [review]
lgtm.

As this setting is currently intended for llext then current location is  acceptable, 
but has been considered if `subsys/Kconfig` is the right location for this setting? 
Another option could be under `Build and Link features` where other settings related to build and configuration is controlled, ref: https://github.com/zephyrproject-rtos/zephyr/blob/c25ac487af84e71498788577af4ee2e62291e34f/Kconfig.zephyr#L825

Approved for now, as we can always move the setting later if desired.

**Comment by lyakh** [comment]
Thanks for the reviews so far! In principle I'm not against any of the proposals - neither against adding a `CONFIG_LLEXT` dependency, nor against moving to a different location, but I would feel more confident making those changes if I had more than one vote in favour of either of them :-) Otherwise of course, as has been mentioned, those changes can be added later

**Comment by lyakh** [comment]
The Compliance Check is complaining about:
> Boolean option 'MODULES' prompt must not start with 'Enable...'

Indeed, the `CONFIG_MODULES` prompt in this commit begins with "enable" but I don't find a better description. Any ideas or can we keep it?

**Comment by nashif** [comment]
would be great and very helpful to have a usecase and a sample of this kconfig being used. Just throwing in a kconfig in a PR is usually not enough....

**Comment by lyakh** [comment]
> would be great and very helpful to have a usecase and a sample of this kconfig being used. Just throwing in a kconfig in a PR is usually not enough....

@nashif the use-case is LLEXT and a sample is SOF https://github.com/thesofproject/sof/pull/8180/commits/614ec42020db1aced42af9324702f8ff6bb60d05#diff-44c49245e3507ea76cafeca22e652e4f30a24495a147d0beb5681a7bad5b0b71

**Comment by marc-hb** [comment]
> would be great and very helpful to have a usecase and a sample of this kconfig being used. Just throwing in a kconfig in a PR is usually not enough....

Same problem in related:
- #66573

I think the biggest `llext` gap right now is around CMake.

I understand brand new features are made of many different parts and that they can't all be merged at the same time. On the other hand, there also seems to be a common misconception that the main branch is the only way to share incomplete bits still in progress.

**Comment by lyakh** [comment]
> Same problem in related:
> 
>     * https://github.com/zephyrproject-rtos/zephyr/pull/66573

@marc-hb I don't think it's the same "problem" - @nashif commented on "Just throwing in a kconfig in a PR" and that other PR doesn't add any Kconfig options.

> I think the biggest llext gap right now is around CMake.

I agree that CMake for llext is a bit difficult now, but I wouldn't relate it to this PR. Again: this is purely to trigger scripts/kconfig/kconfiglib.py to accept tristate Kconfig options, nothing else. As is it's not directly related to llext or to any other subsystem.

**Comment by lyakh** [comment]
twister seems to have experienced a melt down on this PR, should I re-push to have a clean CI run?

**Review by nashif — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
Switch to assignee just to confirm about the option in the top level subsys Kconfig. @tejlmand can you reconfirm please?

**Review by tejlmand — APPROVED** [review]

**Pull request merged**
