### PR TITLE
[RFC] Add support for running LwM2M test in native_posix

### PR DESCRIPTION
**Pull request by SeppoTakalo**
I would like to propose a different approach of running test for LwM2M stack. For this approach I'm completely dropping the Twister and using Pytest directly for various reasons explained below.

I would like to receive comments and suggestions for improvements regarding this approach. If this is acceptable for Zephyr community, I could start developing for more testcases. I have only now submitted two testcases defined by OMA LwM2M specification.

## Approach

Uses Pytest to build and run tests on native_posix environment against locally running Leshan demo server.

Leshan is downloaded and started as part of test fixture. This test fixture is defined as a `scope="module"` which means that it is started only once, and stopped when all of the testcases defined in this module are executed.

Device under test is defined also as a test fixture which contains `west build` and `west build -t run` commands. This fixture is also defined in module scope, so each test case executes against the same test target. Output of the running application is stored in the log file for further study.

For the networking, I'm relying on existing `net-tools` repository that is cloned under `scripts/net-tools`.

## Diagram of test setup
pytest

## Resons for not to use Twister

Currently the implementation of Twister does seem to run the native_posix or QEMU target until it is stopped. Only after this, it launches the Pytest test cases. This does not allow any interaction between the test target and test case which is Pytest

Also, Twister does not have well defined support for extending the test fixtures to support for example setting up the environment, like I have done here.

When Pytest is in use, the log output of the running binary is lost. Only the Pytest log will enter `handler.log`

## Running the tests

1. Set up the local networking by running the `sudo ./net-setup.sh start` from the `scripts/net-tools`
2. Go to `zephyr/test/net/lib/lwm2m/pytest`
3. Call `pytest`

Pytest will automatically download the Leshan demo server and launch it.
Pytest will also automatically build and launch the test binary.

### CODE REVIEW

**Comment by carlescufi** [comment]
We have an upcoming Twister v2, based on Pytest. Maybe that would be the right way to approach this? Cc @gopiotr

**Comment by gopiotr** [comment]
@SeppoTakalo Thank you for your proposition. The problem with lack of test runner for more complicated tests it is not only your problem. Similar situation is with tests dedicated for BabbleSim simulator, where Twister cannot be used, due to the fact of more complicated test workflow. I also tried to manage this problem on my own, used for it Pytest: https://github.com/zephyrproject-rtos/zephyr/pull/46259
And my intention is that, when Twister v2 will be released, I will try to merge my "plugin" into Twister v2. That is why I used there tests defined in yaml files instead of tests written in Python to be easier to merge them in the future.

At this moment I'm not able to said anything else - I'm also waiting for community feedback with my similar proposition. 
Personally, I think that until we do not have Twister v2 there is no option to introduce such tests in other way. The question is: should we wait with our propositions until Twister v2 will be released or it is acceptable that such tests (for lwm2m or BabbleSim) will be handled in this specific way.

**Comment by jheiskan81** [comment]
How long process Twister v2 is? I see the great value run lwm2m test by using native_posix environment. It is much faster to evaluate LwM2M stack implementation without any HW requirements.
It is not requirement any docker environment. I think we can run also same test also with with real HW. This test network also add possibility to use valgrind, gdb and code coverage. Those give outstanding value.

**Comment by jukkar** [comment]
Note that there is a way to run network samples against servers that are running in docker. This can be done in an automated way. It looks like this Dockerized testing could be useful here.
See more information at https://github.com/zephyrproject-rtos/zephyr/tree/main/scripts/net

**Comment by PerMac** [comment]
I clearly find such a test very useful. However, I am not so keen on seeing such "unique" testing approaches in the main tree. I believe it would be beneficial if such tests wouldn't require "hard fixed" configuration implemented within them. In particular stuff like building and using a hex (even though it is just calling west). If we agree on such approach we need to realize that it will take more maintenance effort, since each test of this kind will introduce it's own solutions and reviewing/maintaining will be getting harder with each such test. It would also require additional calls in CI and so on. 

I see the benefit of running this on native_posix. However, I think the problem with the proposed approach is that it is not really scalable. If a more general test runner is used such test would be able to be configured and executed e.g. on a real hardware. I understand that in this case native_posix should be enough, but I am trying to show some broader context for this kind of approach.  

Just keep in mind, that I clearly have a "conflict of interest" since I am driving twister v2 development, and I will advocating for it. However, I think what I've mentioned is not so burdened by it. I can offer to combine our effort and try bringing such test to twister v2 early on. I believe there can be a benefit of exporting some fixtures to a more abstract way (adding to the test runner side), which will enhance scalability if the configuration and also provide tools for other developers to reuse in their tests.

**Pull request closed without merging**
