### PR TITLE
sample: sensor: veml7700: Added sample for veml7700

### PR DESCRIPTION
**Pull request by golmanoj**
This sample application reads the ALS value at specified period

### CODE REVIEW

**Comment by kartben** [comment]
Thanks for the PR! 
We don't recommend having code samples for "generic" sensors, as people can simply use e.g. the `sensor_shell` sample to test the sensor.
I would recommend to either drop this PR, or update it so that it effectively uses some of the stuff that's specific to the veml7700, ex. display white raw counts, or show how to configure the gain.

**Comment by kartben** [comment]
@golmanoj are you planning to revisit this PR as per the feedback in my previous comment? Please let me know if you have questions!

**Comment by kartben** [comment]
@golmanoj ping :)

**Review by MaureenHelm — COMMENTED** [review]
> Thanks for the PR!
We don't recommend having code samples for "generic" sensors, as people can simply use e.g. the sensor_shell sample to test the sensor.
I would recommend to either drop this PR, or update it so that it effectively uses some of the stuff that's specific to the veml7700, ex. display white raw counts, or show how to configure the gain.

I'm ok with new generic sensors in the same vein as `samples/sensor/accel_polling` and `magn_polling`, but want to avoid driver-specific samples.

**Pull request closed without merging**
