### PR TITLE
Fix small api usage problems

### PR DESCRIPTION
**Pull request by ceolin**
There are some small fixes for api usage to be more compliant with C standards and remove possible (unlikely) problems. Some of them like irq_lock() api usage I've created an coccinelle script to automate and identify erroneous problems, but I've manually checked to guarantee that the result was right.

Other important fix is regarding bitwise operations. According with C standard bitwise operations using signed int are UB. It was also created a coccinelle script to change these operations to use BIT() macro.

### CODE REVIEW

**Comment by carlescufi** [comment]
@ceolin this commit is lacking a prefix and will probably make CI fail:

https://github.com/zephyrproject-rtos/zephyr/pull/9454/commits/41dacbf8a84e7b9b03649a2d20e7c76962b11ef1

I suggest using `irq:` as the prefix here.

**Comment by ceolin** [comment]
that is weird. It's failing on test when float point is enabled, the problem is in swap.S, the macro is not expanding correct. The failure happens in:
```
	testb	$_FP_USER_MASK, _thread_offset_to_user_options(%eax)
```
`_FP_USER_MASK` is `#define _FP_USER_MASK (K_FP_REGS | K_SSE_REGS)`

```
#define K_FP_REGS (BIT(1))
#define K_SSE_REGS BIT(7)
```

even when I manually expand this macro the build complains about L character ...
testb	$(((1UL << (1))) | (1UL << (7))), _thread_offset_to_user_options(%eax)

The file has .S suffix and I've checked that gcc was invoked with `-xassembler-with-cpp` but this is not working. Does someone knows why ?

**Comment by ceolin** [comment]
@andyross do you have any clue about this ?

**Comment by andyross** [comment]
This looks like a binutils feature mismatch.  The assembler in our toolchain (binutils 2.27 for an i586 target) doesn't seem to support the "UL" suffix on the literal.  I do note that the 2.29 x86_64 assembler on my host system works just fine, though, so presumably they fixed this at some point.

You may need to put that "1" constant inside a _ASMLANGUAGE test to select the proper syntax.

**Comment by ceolin** [comment]
@andyross thanks ! This was one problem the other one was spotted by @nashif - a missing include.

**Review by nashif — APPROVED** [review]

**Pull request merged**
