### PR TITLE
kernel/mm: shuffle header files

### PR DESCRIPTION
**Pull request by dcpleung**
* Moved kernel MM APIs (`k_mem_*`) under `include/zephyr/kernel/`.
* Separated out `z_*` ones into internal header directory.
* Separated demand paging APIs into its own header file.
* Some doxygen work so MM APIs are actually included in the API doc.

### CODE REVIEW

**Review by peter-mitsis — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]

**Comment by carlescufi** [comment]
@jhedberg can you take a look?

**Review by kartben — CHANGES_REQUESTED** [review]
Unless I'm missing something, the fact that users of the API would need to update their includes calls for an entry in the migration guide.
Looks 👍🏼 otherwise, thank you!

**Comment by dcpleung** [comment]
> Unless I'm missing something, the fact that users of the API would need to update their includes calls for an entry in the migration guide. Looks 👍🏼 otherwise, thank you!

Not writing this in the migration guide is intentional. Out of tree repo users and app developers should continue using `sys/mem_manage.h` as it always include the kernel memory management headers. On the other hand, IMHO, in tree users should be a little more discipline on what to include.

Note that the main intention of this PR is to move `k_*` symbols under kernel/. The concept of `sys -> memory management` has not changed.

If you insist, I can add this to the migration guide (though I think it creates unnecessary work for others). Or I can remove the #include changes in this PR.

**Review by andyross — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by kartben** [comment]
> > Unless I'm missing something, the fact that users of the API would need to update their includes calls for an entry in the migration guide. Looks 👍🏼 otherwise, thank you!
> 
> Not writing this in the migration guide is intentional. Out of tree repo users and app developers should continue using `sys/mem_manage.h` as it always include the kernel memory management headers. On the other hand, IMHO, in tree users should be a little more discipline on what to include.
> 
> Note that the main intention of this PR is to move `k_*` symbols under kernel/. The concept of `sys -> memory management` has not changed.
> 
> If you insist, I can add this to the migration guide (though I think it creates unnecessary work for others). Or I can remove the #include changes in this PR.

So I was missing something, thanks!

**Review by kartben — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
This broke CI on `main`: https://github.com/zephyrproject-rtos/zephyr/issues/65506

**Pull request merged**
