### PR TITLE
doc: west manifest examples, convert 'installation' to 'workspace'

### PR DESCRIPTION
**Pull request by mbolivar**
A couple of last-minute docs changes for west that should go into 2.2 if at all possible.

### CODE REVIEW

**Comment by mbolivar** [comment]
> ************* Module extensions
> doc/guides/west/extensions.rst:1:1: E0001: invalid syntax (<unknown>, line 1) (syntax-error)

Why in the world is pylint looking at a .rst file?

**Review by carlescufi — APPROVED** [review]
Very nice improvement. The fact that we give example manifest files for T2 and T3, along with a dual-example for T2 based on import vs copying manually is going to be extremely useful for users. Thanks for this!

**Review by MaureenHelm — APPROVED** [review]

**Comment by mbolivar** [comment]
kicking CI

**Comment by mbolivar** [comment]
@jhedberg I think pylint is wrong and this is mergeable

**Comment by jhedberg** [comment]
> @jhedberg I think pylint is wrong and this is mergeable

ok, I'll merge

**Pull request merged**
