### PR TITLE
boards: arm: add ruuvi_ruuvitag

### PR DESCRIPTION
**Pull request by ghost**
Fix board name on https://docs.zephyrproject.org/. Currently it is ruuvi_ruuvitag,
new change is to Ruuvi RuuviTag.

Signed-off-by: the BASTION <thebasti0ncode@gmail.com>

### CODE REVIEW

**Comment by theBASTI0N** [comment]
Not sure why buildkite failed:
image

**Comment by stephanosio** [comment]
> Not sure why buildkite failed:
> image

cc @galak @nashif

**Review by ioannisg — APPROVED** [review]

**Comment by theBASTI0N** [comment]
@nashif Is there something I should do to get buildkite to be successful?

Or can this be apporved without that passing?

**Comment by MaureenHelm** [comment]
Please rebase

**Pull request closed without merging**
