### PR TITLE
drivers: i2c_ll_stm32_v1: Wait until not busy before disabling i2c

### PR DESCRIPTION
**Pull request by ghost**
There are a number of bug reports and PRs about I2C bus hangs. The problem I had looked a lot like bug #22751 on the oscilloscope, but neither STOP nor BUSY flags are set before sending START as described in that bug report and in PR #23663. This might be because the problem I had is different, or because the I2C driver is different nowadays compared to 1.14 (it now disables/enables the I2C peripheral for each transaction, for example).

Waiting until the busy flag is cleared before disabling the I2C peripheral helps with an I2C bus hang that has been observed on STM32F429. The I2C bus would stop working after a while when reading from a particular I2C device. After that, the STM32 would only send a start condition immediately followed by a stop condition, until it was reset.

Tested on v2.2.0 on STM32F429, I2C master mode, with and without CONFIG_I2C_STM32_INTERRUPT.

### CODE REVIEW

**Comment by lowlander** [comment]
Hey @jonasn-ge  could you check if PR #27291 works for you ? Because when I made that patch just waiting for BUSY to go away did not work, it might be that the master branch version reacts different, I will try your patch in the weekend.  

Can your setup deal with disruption of the SDA signal, the 1.14 (and master) driver would hang when disrupting the SDA signal for example by shortly connecting it to GND.  That is the other commit in #27291 that deals with that, giving up after a timeout and reseting the hardware.

**Comment by jonasn-ge** [comment]
Hi @lowlander, yes PR #27291 works. Details:

On vanilla 2.2.0:
I2C sometimes spontaneously stops working.
If I tie SDA to ground for a bit, it causes I2C to stop working either with SCL stuck low or generating clock pulses forever.

With my PR:
I2C doesn't spontaneously stop working.
Tying SDA to ground still is a problem, and it gets stuck forever.

PR #27291:
The problem of I2C spontaneously locking up seems to be gone (run for 15 minutes so far). I can see the STOP flag detection log from time to time, and clearing STOP does the trick.
If I tie SDA to ground, the write timeout kicks in and recovers the situation. Nice!

It is a bit curious to me that it works, because I had been looking a lot for that stuck STOP flag before finding out that waiting for BUSY to clear helps (at least for me). What caught me was that LL_I2C_IsActiveFlag_STOP() isn't for _that_ STOP flag, so I was looking at the wrong bit.

**Comment by lowlander** [comment]
@jonasn-ge On my system I poll a I2C sensor only every 100 ms or so, and on the old driver it was still "busy" on the start of the next I2C transfer, that's how I found out I could not "just wait" for it to go away.  Somehow the STM I2C hardware is a bit weird :-/

**Comment by jonasn-ge** [comment]
Looks like PR #27291 solves the problem and is close to getting merged. Closing.

**Pull request closed without merging**
