### PR TITLE
drivers: usb_dc_sam: get the maximum speed from DT as enum

### PR DESCRIPTION
**Pull request by aurel32**
For historical reasons, the maximum speed of the Atmel SAM USB
controller is done by comparing the maximum-speed property string from
the DT using strncmp at runtime.

Now that the DT_ENUM_IDX macro exists, we can use it to get the
maximum-speed property at build time and without string comparison.
Unsupported speed can also be reported at build time.

Note that the default speed in case the optional maximum-speed property
isn't present in the DT is changed from full-speed to high-speed to
match the property description. This is a no-op in practice as this
properties is defined at the soc level.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

### CODE REVIEW

**Comment by aurel32** [comment]
Note that there is the same issue on the STM32 driver. I'll do the same change if/when I get positive feedback about that PR.

**Review by stephanosio — COMMENTED** [review]
In the generated device tree header, we have:
```
#define DT_N_S_soc_S_usbd_40038000_P_maximum_speed "full-speed"
#define DT_N_S_soc_S_usbd_40038000_P_maximum_speed_ENUM_IDX 1
#define DT_N_S_soc_S_usbd_40038000_P_maximum_speed_EXISTS 1
```

While some might consider using enum index a "cleaner" approach, we risk introducing serious bugs that can easily go unnoticed if we ever make changes to the enum orders in the future.

IMHO, the compile-time string comparison approach using `DT_N_S_soc_S_usbd_40038000_P_maximum_speed` is preferable to the index comparison approach using `DT_N_S_soc_S_usbd_40038000_P_maximum_speed_ENUM_IDX` (cc @galak).

**Comment by aurel32** [comment]
> In the generated device tree header, we have:
> 
> ```
> #define DT_N_S_soc_S_usbd_40038000_P_maximum_speed "full-speed"
> #define DT_N_S_soc_S_usbd_40038000_P_maximum_speed_ENUM_IDX 1
> #define DT_N_S_soc_S_usbd_40038000_P_maximum_speed_EXISTS 1
> ```
> 
> While some might consider using enum index a "cleaner" approach, we risk introducing serious bugs that can easily go unnoticed if we ever make changes to the enum orders in the future.

I doubt they will be changed without double checking their usage, but I get your point. Note that there are other locations where DT_ENUM_IDX is used that way, for example in the Atmel SAM GMAC driver to get the PHY connection type.

> IMHO, the compile-time string comparison approach using `DT_N_S_soc_S_usbd_40038000_P_maximum_speed` is preferable to the index comparison approach using `DT_N_S_soc_S_usbd_40038000_P_maximum_speed_ENUM_IDX` (cc @galak).

`DT_N_S_soc_S_usbd_40038000_P_maximum_speed` is what is used in the existing code through `DT_INST_PROP(0, maximum_speed)`. However you suggest to use compile-time string comparison approach, do you have an idea how to do that? There are many tricks existing using preprocessor macros, but they look hackish and I am not sure they are portable.

**Review by jfischer-no — APPROVED** [review]

**Comment by nzmichaelh** [comment]
Hi @aurel32 re: compile time string comparison, @galak might be talking about how GCC will optimize out a strcmp of two constants.  For example, `strcmp("foo", "foo")` will be converted to constant 0.

I gave it a quick test and it doesn't work for strcmp() on Zephyr but does for __builtin_strcmp.  I wonder why?

**Comment by aurel32** [comment]
Removing the stale tag that has just been added, I still believe this is an improvement over comparing strings.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Might be nice to have some `#define` s somewhere for the magic numbers.

**Comment by mbolivar-nordic** [comment]
> While some might consider using enum index a "cleaner" approach, we risk introducing serious bugs that can easily go unnoticed if we ever make changes to the enum orders in the future.

Seems like this could be avoided in the short term by using macros for the enum indexes that get updated if necessary. There is an enhancement open to make this better (https://github.com/zephyrproject-rtos/zephyr/issues/21273) which we could look at if that's no good.

**Pull request merged**
