### PR TITLE
boards: arm: Add mcuboot flash partitions to mimxrt1020_evk

### PR DESCRIPTION
**Pull request by ainguraXmarquiegui**
Adds flash partitions and chosen nodes to the mimxrt1020_evk device tree
to support mcuboot on the internal QSPI flash.

Also enables FlexSPI flash driver XIP mode support on this board to
support mcuboot.

Signed-off-by: Xabier Marquiegui <xmarquiegui@ainguraiiot.com>

### CODE REVIEW

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Thanks for the patch, it looks good. Will you please also update the board documentation page (`boards/arm/mimxrt1020_evk/doc/index.rst`) to reflect that a flash driver is now supported?

**Comment by ainguraXmarquiegui** [comment]
> Thanks for the patch, it looks good. Will you please also update the board documentation page (`boards/arm/mimxrt1020_evk/doc/index.rst`) to reflect that a flash driver is now supported?

No problem. I have already pushed the documentation change. I have taken the liberty of including the mimxrt1024_evk documentation file too. Flash support for this board was added on this commit:

commit e12e126f3262ffcac90572a6be4dffe12f17a30f
Author: Mikkel Jakobsen <mikkel.aunsbjerg@prevas.dk>

**Review by MaureenHelm — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by ainguraXmarquiegui** [comment]
@nashif , thoughts on this PR?

**Comment by ainguraXmarquiegui** [comment]
Commit a50a16e7104924f126b668953fdfc804ee99006d says that @MaureenHelm is no longer working in NXP, and @nashif seems to be unresponsive.

Maybe Assignees and Reviewers need to be updated?

**Pull request merged**
