### PR TITLE
drivers: modem: add support for nrf9160

### PR DESCRIPTION
**Pull request by AlessioLei94**
Added support for nRF9160 modem according to the Zephyr device driver model.
The implementation assumes Serial LTE Modem application by Nordic is running on the nRF9160.

### CODE REVIEW

**Comment by bjarki-trackunit** [comment]
Hi, new modem drivers should be implemented using the new modem subsystem, which you can find here https://github.com/zephyrproject-rtos/zephyr/tree/main/subsys%2Fmodem, you can draw inspiration from here https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/modem/modem_cellular.c and here  https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/gnss/gnss_quectel_lcx6g.c

**Comment by AlessioLei94** [comment]
Hi @bjarki-trackunit,

I had a look at the modem subsystem when i started implementing this driver and i noticed that it wasn't compatible with the nRF9160 as Nordic offers two separate applications to interface to it either using AT commands or PPP and the two are not meant to be used together. Besides that also CMUX is not supported by it.

I used as reference the other modem drivers available in zephyr that only use AT commands as that architecture was suitable for the nRF9160, but apparently is outdated. 

Thanks for your reply,
i will be happy to update the driver if and when Nordic will updated the nRF9160 (or newer models) to be compatible with Zephyr's modem subsystem

**Comment by bjarki-trackunit** [comment]
@AlessioLei94 The new modem subsystem provides the modem backends, which abstract the ISR and Async UART APIs, and a command handling module, `modem_chat`. You would be using an instance of  `modem_chat connected to an instance of `modem_backend_uart` which interacts with the UART.

The GNSS subsystem is also based on the new modem subsystem, and does not use PPP or CMUX either :)

**Comment by AlessioLei94** [comment]
Hi @rerickson1, @bjarki-trackunit ,
thanks for the explanations!
I clearly misunderstood what i saw in the modem_cellular.c file, thinking PPP and CMUX were the only ways to go. 

I found a couple of videos explaining the modem subsystem, I'll try to get a better understanding of how it should work and rework what i did to follow the modem subsystem architecture

**Comment by rerickson1** [comment]
> Hi @rerickson1, @bjarki-trackunit , thanks for the explanations! I clearly misunderstood what i saw in the modem_cellular.c file, thinking PPP and CMUX were the only ways to go.
> 
> I found a couple of videos explaining the modem subsystem, I'll try to get a better understanding of how it should work and rework what i did to follow the modem subsystem architecture

Fantastic, reach out if you have any questions!

**Comment by AlessioLei94** [comment]
@bjarki-trackunit after having a better look i understand now how the modem_backend and chat works and how i am supposed to be using them.

I think i am just missing one last thing, for what concerns offloaded APIs (sockets, DNS etc..), is everything the same is in the drivers implemented using the old method? 

Thanks again for helping me figure this out.

**Comment by bjarki-trackunit** [comment]
> @bjarki-trackunit @rerickson1 after having a better look i understand now how the modem_backend and chat works and how i am supposed to be using them.
> 
> I think i am just missing one last thing, for what concerns offloaded APIs (sockets, DNS etc..), is everything the same is in the drivers implemented using the old method?
> 
> Thanks again for helping me figure this out.

The socket offloading is not part of the modem subsystem, that is part of the network subsystem, so it will be the same :)

**Comment by bjarki-trackunit** [comment]
@tomi-font Hi, very nice! I don't know if you are allowed to answer my question, but are you guys planning to implement PPP in the modem firmware? or will the application be offloading the PPP requests to the modems IP stack?

I have a dream that we could use IPC to set up channels instead of CMUX for the nrf91, and send PPP directly to the modem :)

Again, feel free to not answer :D

**Comment by AlessioLei94** [comment]
@tomi-font Do you have any indication about the timeline?

**Comment by merethan** [comment]
Are there any complications using this, or the upcoming thing @tomi-font hinted at, with silicon revision B0?

For nRF9160 revision B0 the latest modem firmware is v1.2.8, as v1.3.0 and later are targeted at revision B1 and newer. Now, it is not _impossible_ to use modem firmwares v1.3.0 and later with B0 silicon, but it is explicitly recommended to do so for _development purposes only_.

So, does this and the upcoming work hinted at by @tomi-font work with modem firmware is v1.2.8?

**Comment by tomi-font** [comment]
The [compatibility table](https://docs.nordicsemi.com/bundle/comp_matrix_nrf9160/page/COMP/nrf9160/nrf9160_modem_fw.html) between modem firmware and nRF Connect SDK versions shows that officially, the latest SDK version supported on modem firmware 1.2.8 is 1.5.2. Which is old. And because we are making changes to the application, they will only be available with NCS 2.6.0 or later. Which is definitely not (officially) compatible with modem firmware 1.2.8.
Now as to whether they (MFW 1.2.8 + NCS 2.6.0) could work in practice, well I think clearly not.
Backporting the Serial LTE Modem changes to an older NCS version is also not an option in my opinion because of the amount of work it would require.
So for being able to use the upcoming functionality that I talked about, you will need a recent enough modem firmware. Whether that's on an older HW revision (at your own risk) or a newer one.

Regarding what @AlessioLei94 did, I didn't look into it and don't know what the Serial LTE Modem application was like in older releases, though I'm tempted to say that it has a slightly higher chance to work if the application supports what the driver expects from it.
At best you may have to make changes to the driver and/or application to make up for things that are not supported. The risk is that it's too much work.

All in all I just don't recommend using such old versions.

**Comment by bjarki-trackunit** [comment]
@AlessioLei94 The `modem_context` is a hard no :) It has been replaced by the modem modules, `modem_socket` is not dependent on the `modem_context`, so you should be able to use it :)

**Comment by AlessioLei94** [comment]
Hi @bjarki-trackunit thanks for your reply. From what i see in the `Kconfig` file in drivers/modem the config to enable `modem_socket`  has a dependency on `modem_context`.

I don't really need `modem_context` for the driver implementation, but it seems like i have to enable the related config to be able to use the APIs available in `modem_socket`. Maybe my first question was a bit confusing, i hope this is a better explanation

**Comment by bjarki-trackunit** [comment]
@AlessioLei94 I believe that is a Kconfig bug, looking through the code, the modem_socket is not dependent. try just pushing MODEM_SOCKET Kconfigs down below `endif # MODEM_CONTEXT` and build it, should work fine. Then create a PR if it works ;)

**Comment by AlessioLei94** [comment]
@bjarki-trackunit you are right, it seem to be just a bug in the Kconfig file. I fixed it and created the PR

**Comment by AlessioLei94** [comment]
I updated the modem driver to use modem_chat and the uart_backend as @bjarki-trackunit suggested. Not sure if it's still of interest to merge this changes as Nordic is working on updating their application to add PPP and CMUX and add the nrf9160 support to Zephyr. But since i did the work and we are using this code i updated also the branch on which i created the PR

**Comment by kartben** [comment]
my understanding is that this would be superseded by #68981, correct @bjarki-trackunit ?

**Comment by bjarki-trackunit** [comment]
> my understanding is that this would be superseded by #68981, correct @bjarki-trackunit ?

Yep :)

**Comment by AlessioLei94** [comment]
@bjarki-trackunit @tomi-font Is it known if the driver for nRF9160 will allow to use GNSS functionalities as well? It's very nice the driver that uses CMUX and PPP made by Nordic will be included in Zephyr 3.7.0 but for what i see at the moment it's only for modem functionalities and in our use-case we also need GNSS

**Comment by tomi-font** [comment]
We haven't talked about it much yet as the focus has been first on the IP side of things. But this is something should definitely be added rather sooner than later. Unfortunately I can't promise when this will be done, but I hope to be able to look into this relatively soon. (Please let me know if you have any plans on doing anything in this regard in case you need it really quickly so that we are on the same page.)

By the way, regarding what has been done already. Indeed in Zephyr the first version with the changes will be 3.7.0, but we have already cherry-picked them in nRF Connect SDK for the upcoming release (v2.6.0) that is planned for mid-March.
This means that NCS v2.6.0 will already have the modem driver with support for the nRF91 (minus the GNSS functionality, of course).

**Comment by AlessioLei94** [comment]
@tomi-font Thanks for your reply.

At the moment we are using the driver implementation that i made as it seems to be working fine and it also includes the GNSS functionalities. We would prefer to use the implementation included in Zephyr of course but we decided to transition to it once all the functionalities are in place, as it would be more work for us to add (again) GNSS driver to it.

**Pull request closed without merging**
