### PR TITLE
net: l2: ieee8021564: shell/mgmt: fix resource leaks, beacon filtering, length calculation; introduce test coverage for fixes

### PR DESCRIPTION
**Pull request by ghost**
1. While introducing integration test coverage for the existing IEEE 802.15.4 scanning procedure, several resource and functional bugs were discovered.
This PR contributes fixes and introduces full integration test coverage for the scanning procedure via shell and net management.
An additional test suite is being introduced for shell/net mgmt testing as shell/mgmt testing happenes on a deeper integration level than the existing API tests plus the existing test suite had already grown rather large. It is also to be expected that further tests covering shell/mgmt commands will be introduced in the future.

2. Parsing of IEEE 802.15.4. information elements requires distinction of frame payload and MAC payload (payload IEs are part of the L2 MAC payload but not part of the L3+ frame payload to be delivered to userland). Therefore access to MAC and frame payload length should be easy and obvious to maintain. This PR fixes a bug related to L2 payload length calculation for beacon and command frames in preparation for the MAC/upper layer frame payload length distinction introduced later on (including additional test coverage).

This PR is part of a larger PR series contributing to #50336 .

### CODE REVIEW

**Comment by fgrandel** [comment]
@nandojve @jukkar @rlubos Thanks for reviewing/merging my last PR so quickly. I agreed with Robert that I'm going to have exactly one digestible PR from the TSCH branch active at each time. So this is the next one in the series. There's more to come so please take your time.

**Comment by fgrandel** [comment]
Just added two more commits for another minor fix + corresponding test coverage. The PR is now stable to be reviewed.

**Review by rlubos — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]
LGTM

**Pull request merged**
