### PR TITLE
boards: seeed: doc: fix links to the device tree files

### PR DESCRIPTION
**Pull request by CharlesDias**
Fix links to the device tree file in the documentation.

### CODE REVIEW

**Comment by kartben** [comment]
should be addressed with https://github.com/zephyrproject-rtos/zephyr/pull/70152 but it looks like I might have missed a file on my side?

**Comment by CharlesDias** [comment]
Sorry, my bad. This was fixed in the https://github.com/zephyrproject-rtos/zephyr/pull/70152.

**Review by nordicjm — CHANGES_REQUESTED** [review]
Duplicate of https://github.com/zephyrproject-rtos/zephyr/pull/69901/files

**Comment by CharlesDias** [comment]
Dear, @kartben and @nordicjm, as that issue is already addressed with https://github.com/zephyrproject-rtos/zephyr/pull/70152, should I close this PR?

**Comment by nordicjm** [comment]
> Dear, @kartben and @nordicjm, as that issue is already addressed with #70152, should I close this PR?

Yes

**Comment by CharlesDias** [comment]
Close because this issue is already addressed by https://github.com/zephyrproject-rtos/zephyr/pull/70152.

**Pull request closed without merging**
