### PR TITLE
ci: compliance: Exclude ClangFormat

### PR DESCRIPTION
**Pull request by pdgendt**
Stop running ClangFormat in CI as it confuses (first time) contributors more than it helps.

### CODE REVIEW

**Review by tomi-font — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Comment by aescolar** [comment]
@pdgendt I'm wondering if it would not be better to exclude it by default in the script itself https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/ci/check_compliance.py#L1853 ?
(otherwise those who run this script locally, which we encourage developers to do, will get a different result than what CI produces, which will confuse them)

**Comment by pdgendt** [comment]
> @pdgendt I'm wondering if it would not be better to exclude it by default in the script itself [`main`/scripts/ci/check_compliance.py#L1853](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/ci/check_compliance.py?rgh-link-date=2024-11-26T08%3A19%3A32Z#L1853) ? (otherwise those who run this script locally, which we encourage developers to do, will get a different result than what CI produces, which will confuse them)

I think the check itself can still be useful, @carlescufi pointed out that the main confusion were the GH annotations in combination with other compliance checks that could fail?

**Comment by aescolar** [comment]
> I think the check itself can still be useful

Yes, but we could let it be disabled by default(?). If a user wants it they would explicitly enable it(?), and/or we could add a new option to enable all checks including the currently disabled ones.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Thanks @pdgendt, this makes sense.

**Review by fabiobaltieri — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Pull request merged**
