### PR TITLE
samples: mesh: nrf52: revised implementation

### PR DESCRIPTION
**Pull request by vikrant8052**
Removed redundancy from App & revised overall implementation.
Fixed Bugs. Upgraded coding style. Added & replaced comments to
improve code readability.

Upgrade State Binding algorithm by adding ceiling() & constrain
functions.

If particular Server model receive Prohibited values as per
Mesh Model Specification then that message will not get entertained.

Now proper status code will get send if user upgrade
light_lightness_range_state & light_ctl_temperature_range_state.

Added time stamp based message filtering as per Bluetooth Mesh
Developer study guide for each Server. Now even if message
source address & TID is same even after 6 seconds then
that will get proceed otherwise will get ignored.

Added transition time support. With this it was possible to
implement gen_move_set/gen_move_set_unack message handlers.

Signed-off-by: Vikrant More <vikrant8051@gmail.com>

### CODE REVIEW

**Comment by vikrant8051** [comment]
@MariuszSkamra
Kindly note that due to some Github related conflict issue I've closed
 https://github.com/zephyrproject-rtos/zephyr/pull/8926.

If you gonna execute PTS then please run it against this latest PR.

@jhedberg I've not yet deleted PR:8926. Please excuse me :(

**Comment by vikrant8051** [comment]
@nashif Please review & help to merge this PR.

**Comment by vikrant8051** [comment]
@jhedberg @nashif 
It was https://github.com/zephyrproject-rtos/zephyr/pull/9302 because of it conflict arises.

As per our email communication, I had already informed you that I've take care of that Bug in PR:8926.

Playing with rebase & git commands is already nightmare & on that if something like this happen then what to do I don't know.

**Comment by vikrant8051** [comment]
@jhedberg @nashif 
Please as of now merge this commit since it is very large. Surely it is better than what is currently present in master branch.

I will take care of upcoming PTS results in next PR.

**Review by jhedberg — APPROVED** [review]
Approving & merging, but you need to start splitting up your changes into independent commits which do one logical change. E.g. coding style fixes do not belong together in the same commit with functional changes. Also, you need to stop closing your PRs and recreating them as new PRs. You can always force push to the existing PR branch (like I've told you several times in the past).

**Comment by vikrant8051** [comment]
@jhedberg Many many thanks.

**Pull request merged**
