### PR TITLE
drivers: dma: stm32: fix build for STM32F0 MCUs

### LINKED ISSUE #35474: The dma-stm32 driver don't build for STM32F0 MCUs
Here is the error message when building the dma-stm32 driver for a STM32F0 MCU:

```
drivers/dma/dma_stm32.c: In function 'dma_stm32_configure':
drivers/dma/dma_stm32.c:470:16: error: 'LL_DMA_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'PeriphRequest'
  DMA_InitStruct.PeriphRequest = config->dma_slot;
                ^
```

I encountered this issue when building a Zephyr application for a nucleo_f070rb board with SPI_STM32_DMA enabled.

### PR DESCRIPTION
**Pull request by simonguinot**
The STM32F0 MCUs (except STM32F030XC) don't have a DMA channel selection
register (DMA_CSELR). This patch fixes the build of the dma_stm32 driver
for them.

Signed-off-by: Simon Guinot <simon.guinot@seagate.com>

Fixes #35474

### CODE REVIEW

**Comment by erwango** [comment]
Thanks for this patch.
 
Do you confirm this is the only missing bit to get DMA working in your case (non F030XC)?
If yes, we can get this into V2.6.0, but it will require a matching issue(bug) to get it merged. So you'll need to create it.

Also, we're trying to address cross series DMA discrepancies as a whole in https://github.com/zephyrproject-rtos/zephyr/pull/34666. This is targeting v2.7.0. Can you review and provide feedback so your case is also taken into account ?

**Comment by simonguinot** [comment]
> Thanks for this patch.
> 
> Do you confirm this is the only missing bit to get DMA working in your case (non F030XC)?
> If yes, we can get this into V2.6.0, but it will require a matching issue(bug) to get it merged. So you'll need to create it.
> 
> Also, we're trying to address cross series DMA discrepancies as a whole in #34666. This is targeting v2.7.0. Can you review and provide feedback so your case is also taken into account ?

Hi @erwango,

Here is a bug report associated to this PR: #35474.

I can confirm that with this patch I can get SPI+DMA working on a nucleo_f070rb board with a STM32F070RB MCU and on another board with a STM32F070RB MCU. That's all I can confirm :)

I'll look at #34666 and at #34972 (as suggested by @FRASTM in the bug report).

**Comment by erwango** [comment]
> I can confirm that with this patch I can get SPI+DMA working on a nucleo_f070rb board with a STM32F070RB MCU and on another board with a STM32F070RB MCU. That's all I can confirm :)

Ok, great!
Would you mind adding a commit to get this tested (at least compiled) on nucleo_f070rb using `tests/drivers/dma/chan_blen_transfer` ?

**Comment by simonguinot** [comment]
> Would you mind adding a commit to get this tested (at least compiled) on nucleo_f070rb using `tests/drivers/dma/chan_blen_transfer` ?

Sure. This test is building and running correctly on a nucleo_f070rb board.

But for some reason the  loop_transfer test is not. This triggers a hard fault in `dma_request_channel()`. It looks like it is related with the `dev->data` pointer...

Do you want me to add the loop_transfer test as well, even if it is failing or just the chan_blen_transfer test which is succeeding ?

**Comment by erwango** [comment]
> Do you want me to add the loop_transfer test as well, even if it is failing or just the chan_blen_transfer test which is succeeding ?

If there's a bug, it likely means it's valuable to test it.
Let's add both and we'll investigate the failure after then.

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
