### PR TITLE
soc/intel_adsp: use correct uuid for bringup & base module

### PR DESCRIPTION
**Pull request by RanderWang**
Currently sof ipc4 driver and windows driver can't work with
sof fw built for zephyr. The reason is bringup and base module
can't be found. The manifest data is for sof fw to build image
data and the uuid should be the same as the uuid used in sof
components, or these components can't be found.

Signed-off-by: Rander Wang <rander.wang@intel.com>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Review by andyross — CHANGES_REQUESTED** [review]
So... the obvious question is "what required the old UUIDs and what will break if we change it here?"  If the ipc4 host drivers care about this value, surely some other software cares about the current defaults?  Dropping a quick -1 just to get the answer confirmed; feel free to override if this is safe.

But longer term, this is an area where the zephyr/rimage/sof overlap is sort of messy.  Really Zephyr shouldn't be in the business of deciding on how to identify itself to the host kernel firmware loader.  We should just get that UUID as application input (probably via kconfig).

Consider something like `CONFIG_INTEL_ADSP_BOOT_UUID=f3e4792b-7546-49f6-89df3bc194a91aeb`

Then we could have a tiny python script generate the module C file (along with whatever other fields should be app-configured), allowing the same source tree to build for multiple host driver versions, etc...

In fact, ideally this should probably be an rimage feature rather than something it's trying to suck out of custom sections of a foreign binary image.

**Comment by marc-hb** [comment]
> So... the obvious question is "what required the old UUIDs and what will break if we change it here?" If the ipc4 host drivers care about this value, surely some other software cares about the current defaults?

Yes please. The commit message should at least explain why losing the old values does not break anything: were they entirely ignored absolutely everywhere?

I traced the old values to the giant, initial import commit 3686ad1ac923 and the corresponding PR has no discussion about that very specific point.

**Comment by marc-hb** [comment]
I just ran `sof/tools/sof_ri_info/sof_ri_info.py` on all the XTOS images found in https://github.com/thesofproject/sof-bin/tree/main/v1.9.x/sof-v1.9

Only the APL (and GLK symlink) images have these:
```
    BRNGUP    0d7b48cc-1ea9-470a-a8c1-533424528a17
    BASEFW    fc869e2e-45f8-4045-a416-89880ae320a9
```

All other products have these:
```        
    BRNGUP    2b79e4f3-4675-f649-89df-3bc194a91aeb
    BASEFW    0e398c32-5ade-ba4b-93b1-c50432280ee4
```


(to defeat the crazy GUID endianness look at the end of it first)


Longer example:
```    
  cavs0015 (ADSP Manifest) file offset 0x2300 name ADSPFW build ver 2.0.0.1 feature mask 0xffff image flags 0x0
    HW buffers base address 0x0 length 0x0
    Load offset 0x30000

    BRNGUP    2b79e4f3-4675-f649-89df-3bc194a91aeb
      entry point 0xb0038000 type 0x21 ( loadable LL )
      cfg offset 0 count 0 affinity 0x3 instance max count 1 stack size 0x1
      .text   0xb0038000 file offset 0x8000 flags 0x1001f ( contents alloc load readonly code type=0 pages=1 )
      .rodata 0xb0039000 file offset 0x9000 flags 0x1012f ( contents alloc load readonly data type=1 pages=1 )
      .bss    0x0 file offset 0x0 flags 0xf00 ( type=15 pages=0 )

    BASEFW    0e398c32-5ade-ba4b-93b1-c50432280ee4
      entry point 0xbe02c400 type 0x21 ( loadable LL )
      cfg offset 0 count 0 affinity 0x3 instance max count 1 stack size 0x1
      .text   0xbe02c000 file offset 0xa000 flags 0x2b001f ( contents alloc load readonly code type=0 pages=43 )
      .rodata 0xbe057000 file offset 0x35000 flags 0x23012f ( contents alloc load readonly data type=1 pages=35 )
      .bss    0xbe07a000 file offset 0x0 flags 0x1660202 ( alloc type=2 pages=358 )
```

**Comment by marc-hb** [comment]
@RanderWang where do these come from in XTOS? Maybe you can fix these in the SOF repo first, I think the SOF repo is a better place to discuss this first. Then the Zephyr commit message becomes just "fix Zephyr copy/paste/diverge, see SOF commit abcdef for details" without bothering Zephyr people about GUID typos.

> But longer term, this is an area where the zephyr/rimage/sof overlap is sort of messy

That is of course a very valid Zephyr discussion. GUID typos not so much.

**Comment by RanderWang** [comment]
> @RanderWang where do these come from in XTOS? Maybe you can fix these in the SOF repo first, I think the SOF repo is a better place to discuss this first. Then the Zephyr commit message becomes just "fix Zephyr copy/paste/diverge, see SOF commit abcdef for details" without bothering Zephyr people about GUID typos.
> 
> > But longer term, this is an area where the zephyr/rimage/sof overlap is sort of messy
> 
> That is of course a very valid Zephyr discussion. GUID typos not so much.

please check base_fw.c.  (https://github.com/thesofproject/sof/blob/main/src/audio/base_fw.c#L11-L14).  This is the implementation of basefw. And also they are in https://github.com/thesofproject/rimage/blob/ee5c3e1deb1436a6e52b653bb523b594511cf330/config/tgl-cavs.toml#L58, 
https://github.com/thesofproject/rimage/blob/ee5c3e1deb1436a6e52b653bb523b594511cf330/config/tgl-cavs.toml#L68.
https://github.com/thesofproject/sof/blob/main/src/platform/tigerlake/base_module.c#L19
https://github.com/thesofproject/sof/blob/main/src/platform/tigerlake/boot_module.c#L19
https://github.com/thesofproject/sof/blob/main/src/platform/icelake/base_module.c#L18
https://github.com/thesofproject/sof/blob/main/src/platform/icelake/boot_module.c#L18
https://github.com/thesofproject/sof/blob/main/src/platform/cannonlake/base_module.c#L18
https://github.com/thesofproject/sof/blob/main/src/platform/cannonlake/boot_module.c#L18.

The problem is to change which ? The UUID exists in SOF for a long time and we should keep it.

**Comment by marc-hb** [comment]
> The problem is to change which ?

Exactly: if https://github.com/thesofproject/sof/blob/980a5b25b3d/src/platform/apollolake/boot_module.c is correct in XTOS, then how can it be wrong in Zephyr and why change it in Zephyr?

> The UUID exists in SOF for a long time and we should keep it.

If we have different, tested and working UUIDs in XTOS for different platforms, then how can we have a single one for all platforms in Zephyr? If they must be different in XTOS then then cannot be the same in Zephyr, this will not work.

There is no point trying to fix a copy/paste in Zephyr before the situation is clarified in the original.

**Comment by RanderWang** [comment]
> > The problem is to change which ?
> 
> Exactly: if https://github.com/thesofproject/sof/blob/980a5b25b3d/src/platform/apollolake/boot_module.c is correct in XTOS, then how can it be wrong in Zephyr and why change it in Zephyr?
> 
> > The UUID exists in SOF for a long time and we should keep it.
> 
> If we have different, tested and working UUIDs in XTOS for different platforms, then how can we have a single one for all platforms in Zephyr? If they must be different in XTOS then then cannot be the same in Zephyr, this will not work.
> 
> There is no point trying to fix a copy/paste in Zephyr before the situation is clarified in the original.

Sure, we can't have one single config for all platforms.

**Comment by marc-hb** [comment]
Resubmitted by @aiChaoSong in #43571

**Pull request closed without merging**
