### PR TITLE
[Backport v1.14-branch] Bluetooth: controller: Increased thread context operation queue count

### LINKED ISSUE #32430: [v1.14] Bluetooth: thread crashes when configuring a non 0 Slave Latency
**Describe the bug**
Our nRF52 peripheral device running Zephyr v1.14 accepts up to 4 connections from central devices (CONFIG_BT_MAX_CONN = 4), all go well with the default BT_PERIPHERAL_PREF_SLAVE_LATENCY = 0 config.
If we change BT_PERIPHERAL_PREF_SLAVE_LATENCY to non 0, and make 3 or above connections, the bluetooth thread crashes within minutes.

**To Reproduce**
1. build and run the peripheral system with the following,
CONFIG_BT_MAX_CONN = 4
BT_PERIPHERAL_PREF_SLAVE_LATENCY = 2
2. Connect 3 or more mobile devices to the peripheral.

**Expected behavior**
No crash of threads.

**Impact**
Major

**Logs and console output**
[00:05:33.008,941] <err> bt_ctlr_ctrl: assert: '(ticker_status == 0) || (ticker_status == 2)' failed
***** Kernel OOPS! *****
Current thread ID = 0x200028f4
Faulting instruction address = 0x266e6
Fatal fault in thread 0x200028f4! Aborting.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain :GNU Arm Embedded Toolchain
 - v1.14-branch, SHA-1: ffd8a91f558ece947726e6df86f418d18b2caee7

**Additional context**
Reported to @cvinayak on Slack.

### PR DESCRIPTION
**Pull request by cvinayak**
When ticker job is disabled inside radio events then all
advertising, scanning, and slave latency cancel ticker
operations will be deferred, requiring increased ticker
thread context operation queue count.

Fixes #32430.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@nashif how to proceed with the CI failures in this PR?

**Review by nashif — APPROVED** [review]

**Comment by galak** [comment]
@cvinayak can you rebase this on the top of upstream v1.14-branch so we can pull in the buildkite ci env support.

**Comment by galak** [comment]
Can you rebase now that the doc building is fixed.

**Comment by cvinayak** [comment]
@galak I get unrelated kernel test failure: https://buildkite.com/zephyr/zephyr/builds/26782

I will try a forced push again.

**Comment by cvinayak** [comment]
@galak @nashif unrelated CI failures recently in v1.14-branch is an overhead following up/force pushing. Maybe the kernel/driver test failure are genuine failures in the LTS v1.14-branch ?

**Pull request merged**
