### PR TITLE
samples: bindesc: doc: Describe sample using zephyr:code-sample

### PR DESCRIPTION
**Pull request by kartben**
Missed the chance to review the sample doc in time for this one, sorry @yonsch . 
@nashif would it make sense to add a generic entry for samples to MAINTAINERS file? (implicitly volunteering myself as a maintainer for it).

Describe the code sample using zephyr:code-sample directive to help with making it easier to find from API reference.
Also cross-referenced main bindesc page from the sample.

### CODE REVIEW

**Comment by nashif** [comment]
> @nashif would it make sense to add a generic sample entry to MAINTAINERS file? (implicitly volunteering myself as a maintainer for it)

yeah, go for it.

**Review by nashif — APPROVED** [review]

**Comment by yonsch** [comment]
See #63225

**Comment by kartben** [comment]
> See #63225

ooh nice, thx. do you want me to add my commit on top of your PR?

**Comment by kartben** [comment]
> > See #63225
> 
> ooh nice, thx. do you want me to add my commit on top of your PR?

went ahead and added my commit to the PR branch for #63225. Closing this one.

**Comment by kartben** [comment]
> > @nashif would it make sense to add a generic sample entry to MAINTAINERS file? (implicitly volunteering myself as a maintainer for it)
> 
> yeah, go for it.

#64192

**Pull request closed without merging**
