### PR TITLE
samples: net: sockets: Add smoke testing support

### LINKED ISSUE #13300: NET: USB Ethernet tests were removed allowing to submit not compiling code
We had special overlays and configuration for USB Ethernet networking and now they are removed. Please restore.

### PR DESCRIPTION
**Pull request by jukkar**
The net-app based echo-server/client applications were used for
various smoke testing purposes. As those two apps are now removed
we need to introduce the same support into sockets based echo-client
and echo-server applications.

Fixes #13300 #13481

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]
definitely needed

**Review by pfalcon — APPROVED** [review]
Thanks

**Comment by jukkar** [comment]
The file `samples/net/sockets/echo_server/frdm_kw41z.conf` should have been in boards directory.

**Comment by pfalcon** [comment]
I'd say something wrong is here, because e.g. smsc91xx eth driver is known to be broken in master, while CI here passed. In my queue to look into that.

**Pull request merged**
