### PR TITLE
bluetooth: hci: refactored bluetooth hci packet type indicators

### PR DESCRIPTION
**Pull request by ndrs-pst**
Introduced a unified definition for HCI packet type indicators in `bluetooth/hci_types.h`.
This change streamlines the code in `drivers/bluetooth/hci/`, reducing redundancy.
Enhances maintainability and consistency across all HCI drivers.

### CODE REVIEW

**Review by hermabe — DISMISSED** [review]

**Review by jhedberg — CHANGES_REQUESTED** [review]
Isn't it by chance the values are like they are? AFAIK each HCI transport (at least those you can find in the Bluetooth core spec) independently define their own way of indicating packet types. Many have inherited the values used by the UART transport (with HW flow control), also known as H:4, but I think it's important to acknowledge that these values are not standard in any general sense, rather they're always specific to each transport specification (even if some transports happen to use the same values). Curiously, the `h4.c` driver is the one which you're *not* touching in this PR, even though that's where these values first showed up (both in the core spec as well as in the driver, in Zephyr's case). Why is that?

Because of this, I don't think we should present the values as if they come from some universal standard, at least not through the `hci_types.h` header file, since that's supposed to strictly adhere to the HCI transport specifications as they exist in the Bluetooth core specification.

**Review by erwango — DISMISSED** [review]
~~Approved for STM32~~ Cf maintainer's comment.

**Comment by jori-nordic** [comment]
> at least not through the hci_types.h header file

Could we have an H4 section in that file? And namespace the defines with `_H4` with a comment above stating that other transports might also decide to use this by convention.

**Comment by ndrs-pst** [comment]
@jhedberg, I haven't made changes to `h4.c` because it uniquely defines `#define H4_NONE 0x00`, which isn't a standard value, as you pointed out. Similarly, `h5.c` uses `0x00 for HCI_3WIRE_ACK_PKT`. Therefore, I've decided not to modify either file at this stage. Once we finalize a solution, I'll be ready to update and push a new commit to this PR.

The rationale behind this PR is that I observed each driver defining their own similar values due to the absence of a common definition in the header file.

**Comment by jhedberg** [comment]
> > at least not through the hci_types.h header file
> 
> Could we have an H4 section in that file? And namespace the defines with `_H4` with a comment above stating that other transports might also decide to use this by convention.
> 
> edit: and `hci_h4.h` would also be fine for me.

Both of these options sound reasonable to me. I'd also include a good code comment as part of the definitions, explaining where they come from and why they have wider reusability.

> @jhedberg, I haven't made changes to `h4.c` because it uniquely defines `#define H4_NONE 0x00`, which isn't a standard value, as you pointed out. Similarly, `h5.c` uses `0x00 for HCI_3WIRE_ACK_PKT`.

Those two defines for the value `0x00` are indeed a special. For the H:4 case it's purely for the driver's internal state keeping, i.e. this is not even part of the HCI transport specification. For the H:5 driver it's something specific to the H:5 transport that isn't really applicable elsewhere.

The transport specifications don't (AFAIK) make any references to each other, so I really haven't seen any problem with having each driver provide their own defines for packet types. The non-standard drivers (of which there seem to be quite many) have gone with the original H:4 values, so for them I'd be fine with putting the H:4 values in a shared header and have the non-standard drivers use those. For standard drivers, however, like H:5, I'd keep separate (driver-internal) defines, since those come from the spec and the spec makes no references to other transports wrt to these values.

**Comment by msmttchr** [comment]
@ndrs-pst, could you please apply this improvement, when finalised, to the recently added `hci_spi_st.c` file ?

**Comment by ndrs-pst** [comment]
> @ndrs-pst, could you please apply this improvement, when finalised, to the recently added `hci_spi_st.c` file ?
OK, got it. I'll rebase and apply to `hci_spi_st.c` too.

**Comment by erwango** [comment]
@msmttchr, @HoZHel  ^^

**Comment by jhedberg** [comment]
> > @ndrs-pst, could you please apply this improvement, when finalised, to the recently added `hci_spi_st.c` file ?
> 
> OK, got it. I'll rebase and apply to `hci_spi_st.c` too.

@ndrs-pst are you still planning to do this change? After that I'd be happy to approve the PR.

**Comment by ndrs-pst** [comment]
@jhedberg I've already implemented the change. Please take a look and let me know if everything looks good for approval. Thanks!

**Review by jhedberg — APPROVED** [review]

**Review by msmttchr — APPROVED** [review]
OK for me. @HoZHel, could you please have a look as well ?

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by HoZHel — APPROVED** [review]

**Pull request merged**
