### PR TITLE
drivers: spi_esp32_spim: Support more CS pins per SPI instance 

### PR DESCRIPTION
**Pull request by ydamigos**
Convert SPI csel_pin device tree property to array in order to support more CS pins per SPI instance.

boards/odroid_go: Add support for microSD card

### CODE REVIEW

**Comment by sylvioalves** [comment]
@ydamigos This PR is really welcome, however, @glaubermaroto has another pinctrl PR that will overwrite all of this. @glaubermaroto PTAL.

**Comment by ydamigos** [comment]
> @ydamigos This PR is really welcome, however, @glaubermaroto has another pinctrl PR that will overwrite all of this. @glaubermaroto PTAL.

@sylvioalves Does it support multiple CS on the same SPI instance?

**Comment by glaubermaroto** [comment]
> > @ydamigos This PR is really welcome, however, @glaubermaroto has another pinctrl PR that will overwrite all of this. @glaubermaroto PTAL.
> 
> @sylvioalves Does it support multiple CS on the same SPI instance?

It is better to hold this PR for a while and wait for the pinctrl subsystem support to be merged before.

**Comment by ydamigos** [comment]
OK, I will rebase it when PR #43589 is merged.

**Comment by ydamigos** [comment]
Now that PR #43589 was merged, I have updated this PR.

**Comment by ydamigos** [comment]
@glaubermaroto @sylvioalves Could you take a look?

**Comment by sylvioalves** [comment]
@ydamigos Please, rebase so we can approve.

**Comment by ydamigos** [comment]
@sylvioalves Rebased to latest main.

**Review by sylvioalves — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Pull request merged**
