### PR TITLE
scripts: Remove unnecessary () around if/while conditions in Python

### PR DESCRIPTION
**Pull request by ulfalizer**
Not needed in Python. Detected by check C0325 in pylint3.

Also replace an

    if len(tag):

with just

    if tag:

Empty strings, byte strings, lists, etc., are falsy in Python.

### CODE REVIEW

**Comment by ulfalizer** [comment]
(I know these are habits from C, so no worries. Just seeing what stuff I can batch-fix to then flag automatically in CI. :P)

**Comment by aescolar** [comment]
@ulfalizer (I prefer not involving myself in this kind of issues but just a general question)
This seems to be going in the direction of imposing a coding style for python scripts, but, do we actually have such a guideline for python? (otherwise somebody else may start to override your corrections tomorrow with equal validity)

**Comment by ulfalizer** [comment]
@aescolar 
I'm guessing `if (foo):` is almost always a habit from other another language creeping in rather than something people consciously prefer over `if foo:`. When I started out with Python, I also wrote a bunch of `if (foo == bar):` and the like, due to habits from C. Didn't even see the parens, because I was so used to filtering them out. :)

I could be wrong though.

**Review by dbkinder — APPROVED** [review]
OK. If CI is going to start flagging python "issues", we should indeed document our expectations as we are/will be doing for C coding, doxygen comments, and reST/Sphinx conventions...

**Review by tyrantlizard77 — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
