### PR TITLE
boards: Move default pinmux enable to <board>_defconfig

### PR DESCRIPTION
**Pull request by MaureenHelm**
Most boards enable the pinmux by default by setting CONFIG_PINMUX=y in
<board>_defconfig, but several boards did it in Kconfig.defconfig
instead. Several code reviews, such as #5043, have suggested using a
select in Kconfig.board to enable the pinmux, however this caused
warnings:

warning: (BOARD_LPCXPRESSO54114) selects PINMUX which has unmet direct
dependencies (BOARD_FRDM_K64F || BOARD_FRDM_KL25Z || BOARD_FRDM_KW41Z ||
BOARD_HEXIWEAR_K64 || BOARD_USB_KW24D512 || BOARD_GALILEO)

Fix how these boards enable the pinmux so they are more consistent with
other boards.

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

### CODE REVIEW

**Review by galak — DISMISSED** [review]
Why don't we clean this up the other way - by using select everywhere.

So in boards/*/*/Kconfig.board we'd add:

```
select PINMUX
```

and remove it from ```boards/*/*/Kconfig.defconfig``` & ```boards/*/*/<BOARD>_defconfig```

**Comment by MaureenHelm** [comment]
> Why don't we clean this up the other way - by using select everywhere.

That's a bigger change that impacts a lot more boards. Then the question becomes, should we do the same for gpio, serial, console, ...? How do we decide what gets set to 'y' in <board>_defconfig vs. selected in Kconfig.board?

**Comment by nashif** [comment]
we should not use select for this, if you use select, you will not be able turn it of and this will most likely cause lots of dependency problems

**Review by nashif — APPROVED** [review]

**Comment by erwango** [comment]
> Then the question becomes, should we do the same for gpio, serial, console, ...? How do we decide what gets set to 'y' in _defconfig vs. selected in Kconfig.board?

FYI, We've recently had a similar discussion for STM32 based boards in #3483
Clean up happened in #5515. We end up having this 'use case' configuration flags in _defconfig

**Review by galak — APPROVED** [review]

**Pull request merged**
