### PR TITLE
include: usb: fix hid feature item typo

### PR DESCRIPTION
**Pull request by stenhardvara**
Fix typo setting HID feature item to output item.

Signed-off-by: Sven Åkersten <sven.akersten@gmail.com>

### CODE REVIEW

**Review by jfischer-no — APPROVED** [review]
thanks

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@stenhardvara thanks for the PR! The email in the `Signed-off-by` and the email on your commit must match. You can change the email on your commit with `git commit --amend --author="Author Name <email@address.com>"`

**Comment by carlescufi** [comment]
@stenhardvara you now have a merge commit. You need to use force-push `git push -f` to clean up and have a single commit in this PR.

**Comment by stenhardvara** [comment]
@carlescufi I think it is correct now. I am quite new to git, so might still be incorrect.

**Comment by carlescufi** [comment]
> @carlescufi I think it is correct now. I am quite new to git, so might still be incorrect.

Thanks! Congrats on your first Zephyr PR merged.

**Pull request merged**
