### PR TITLE
cpp: Check functions in init_array section

### PR DESCRIPTION
**Pull request by finikorg**
Add __ASSERT() to catch broken init_array section.

### CODE REVIEW

**Review by vanwinkeljan — APPROVED** [review]

**Review by pabigot — COMMENTED** [review]
Why are there null pointers in this array?  I would expect that to be the root cause of the failure.

**Comment by pabigot** [comment]
Which "cpp tagged tests" fail because of this problem?  `tests/application_development/cpp` passes on my ESP32 hardware with 0.11.1 toolchain.

**Comment by vanwinkeljan** [comment]
> Why are there null pointers in this array? I would expect that to be the root cause of the failure.

I was wondering the same but a quick google learned me that some compilers put null pointers in the array for padding.

**Comment by andyross** [comment]
The linker might add padding, but if that's reflected in our array start/end symbols then we have a bug in our own linker script.

**Review by andyross — CHANGES_REQUESTED** [review]
Yeah, I gotta -1 this one.  We should figure out why the `__init_array_start/end` symbols are wrong.

**Comment by finikorg** [comment]
The proper fix is here: https://github.com/thesofproject/rimage/pull/8
So this workaround is not needed anymore. However i am thinking to add some ASSERT to indicate the problem. Otherwise Zephyr crashes in the beginning in some cases without logs.

**Review by pabigot — COMMENTED** [review]
I don't object to it, but I don't think this is worth doing so I won't approve it either.  This isn't something that can be broken by user error; it's something broken in a tool (in this case, an out-of-tree tool for a specific external framework).

Extending the rationale we should add checks in device initization and anywhere else the linker places objects into an array.

**Comment by andyross** [comment]
OK, so not a bug in the toolchain per se but in the image conversion utility, which is sort of the same thing.  I wouldn't -1 an __ASSERT, but this is an awfully special case here; it would just be tracking for regressions in the image packer.  I think it's not unreasonable for Zephyr to assume that its tooling is generating correct binaries without defensive coding.

**Comment by finikorg** [comment]
Closing since issue is fixed in the 3rd party tool rimage (https://github.com/thesofproject/rimage/pull/8) which copies ".init_array" section for up_squared_adsp board.

**Pull request closed without merging**
