### PR TITLE
drivers: slip: Rework logging to follow conventions

### PR DESCRIPTION
**Pull request by pfalcon**
Previously, there was boolean CONFIG_SLIP_DEBUG, which effectively
switched between "logging off" and "debug-level logging". Instead,
switch to CONFIG_SYS_LOG_SLIP_LEVEL (the naming of the option follows
existing conventions) which allows to select any of the standard 5
logging levels.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
This contains a detailed commit message which can be considered an update on my RFC re: improving net logging. So, by now I figured there's no easy way to achieve what my RFC talked about (being able to show just all errors/warnings), simply because different parts of Zephyr do logging in different ways. While some do exactly "logging", and with different, clearly defined levels, some (like this drivers), have it's just binary: log too much, or log nothing. They consequently even call that "debugging", not "logging". This patch makes a first step towards teaching them non-flat logging structure, but leaves the existing terminology (and config names) as is. Ultimately, that needs to be addressed too.

This comes as part of #4022 investigation.

**Review by nashif — CHANGES_REQUESTED** [review]
I would simplify this and remove CONFIG_SLIP_DEBUG altogether and introduce SYS_LOG_SLIP_LEVEL instead

**Review by jukkar — APPROVED** [review]

**Comment by jukkar** [comment]
> I would simplify this and remove CONFIG_SLIP_DEBUG altogether and introduce SYS_LOG_SLIP_LEVEL instead

I am ok with current proposal. Do you mean that we should introduce a Kconfig variable for SLIP log level? The name in that case would probably need to be CONFIG_SLIP_LOG_LEVEL or similar.

**Comment by pfalcon** [comment]
> Do you mean that we should introduce a Kconfig variable for SLIP log level? The name in that case would probably need to be CONFIG_SLIP_LOG_LEVEL or similar.

Exactly the direction of my thinking, but instead should be done consistently throughout Zephyr, not just for SLIP. I'm thinking of not just adding another Kconfig option, but switching to consistent model where if a component controlled by CONFIG_FOO, there's CONFIG_FOO_LOG_LEVEL (or maybe CONFIG_FOO_LOGLVL or something), and it's the only option to control logging level for the component (perhaps with logging gated somewhere, and perhaps the option inheriting from another more global logging level). That requires more thinking and RFC, on TODO.

**Comment by pfalcon** [comment]
> I would simplify this and remove CONFIG_SLIP_DEBUG altogether and introduce SYS_LOG_SLIP_LEVEL instead

@nashif : Let's don't haste ahead of doing it well. As I mentioned, this requires a consistent change across the codebase, which involved incompatible change (Kconfig options gone), which requires planning and discussion. In the meantime, current change allows to debug issues like #4022.

**Comment by nashif** [comment]
> The name in that case would probably need to be CONFIG_SLIP_LOG_LEVEL or similar.

CONFIG_SYS_LOG_<COMPONENT> is the right naming convention

**Comment by pfalcon** [comment]
> CONFIG_SYS_LOG_[COMPONENT] is the right naming convention

What's so right about it? Let's discuss separately.

**Comment by nashif** [comment]
> What's so right about it? Let's discuss separately.

It is how we have been setting the log level for every component, there are some anomalies, here and there, but this is the convention for setting the logging level for sys log components.

**Comment by pfalcon** [comment]
Indeed

~~~
dfu/img_util/flash_img.c:#define SYS_LOG_LEVEL CONFIG_SYS_LOG_IMG_MANAGER_LEVEL
net/buf.c:#define SYS_LOG_LEVEL CONFIG_SYS_LOG_NET_BUF_LEVEL
usb/usb_descriptor.c:#define SYS_LOG_LEVEL CONFIG_SYS_LOG_USB_LEVEL
usb/class/cdc_acm.c:#define SYS_LOG_LEVEL CONFIG_SYS_LOG_USB_CDC_ACM_LEVEL
usb/class/mass_storage.c:#define SYS_LOG_LEVEL CONFIG_SYS_LOG_USB_MASS_STORAGE_LEVEL
~~~

Eerie (long). Will rework the patch.

**Comment by pfalcon** [comment]
Reworked per @nashif's suggestions.

**Review by nashif — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
samples/net/dhcpv4_client/prj.conf has CONFIG_SLIP_DEBUG=n, please remove

**Comment by pfalcon** [comment]
> samples/net/dhcpv4_client/prj.conf has CONFIG_SLIP_DEBUG=n, please remove

Done.

**Review by nashif — APPROVED** [review]

**Pull request merged**
