### PR TITLE
flash_map: Merge subsys/storage/flash_map into subsys/storage

### PR DESCRIPTION
**Pull request by ulfalizer**
subsys/storage/CMakeLists.txt and subsys/storage/Kconfig just pass
everything through to subsys/storage/flash_map/. Simplify things by
removing subsus/storage/flash_map/ and putting the files directly in
subsys/storage/ instead.

Also remove the "Storage" Kconfig menu, which was in the old
"pass-through" subsys/storage/Kconfig. It showed up even with FLASH_MAP
disabled.

This puts FLASH_MAP in the top-level menu and gets rid of one menu level
(without making the top-level menu longer, because FLASH_MAP is a
'menuconfig' symbol).

### CODE REVIEW

**Review by mbolivar — COMMENTED** [review]
Code changes look sane and I agree it would be nice to flatten this hierarchy a bit; @nvlsianpu, what do you think?

**Review by nashif — CHANGES_REQUESTED** [review]
We should leave the top-level storage alone as we might have other items below it, flash_map is only one possible item.

**Comment by ulfalizer** [comment]
Maybe we could add a menu later, once we have more items.

**Review by nvlsianpu — COMMENTED** [review]
Actually I thinks that flash_map is the same kinds as disk_access abstraction is (for instance).
So an abstraction for access raw area NVM combined with all knowledge required to access these certain memory area.
Not sure what exact name is the best for such kind. On of available is storage, volume_access_layer.

> We should leave the top-level storage alone as we might have other items below it, flash_map is only one possible item.

I'm in line with sentence above.

**Pull request closed without merging**
