### PR TITLE
Introduce the native_sim board - minimal PR

### PR DESCRIPTION
**Pull request by aescolar**
This is the minimum subset (the first 13 commits) of https://github.com/zephyrproject-rtos/zephyr/pull/59302 which can introduce the new native_sim board, and keep the tree in a correct and fully coherent state.
(main should be kept bisectable between commits, but inbetween this PR's commits there would be dead code, or code not covered by MAINTAINERS).

It is split out of the other PR to ease reviewing , but I accept reviews in either PR.
It:
* Introduces the native simulator (runner) in tree
* Introduces a new board (native_sim & native_sim_64), which uses this runner.
* Introduces 2 new kconfig options: NATIVE_BUILD and NATIVE_LIBRARY apart from NATIVE_APPLICATION (application is kept for those that build monolitically, i.e. native_posix & nrf52_bsim), NATIVE_BUILD is common to both NATIVE_LIBRARY and APPLICATION
* Adds the minimum set of overlays for tests and samples so CI keeps passing

With this subset, you **cannot yet** run the POSIX API shim or libC tests in this new target. If you want to try things out, #59302 would be better.

### CODE REVIEW

**Review by rodrigopex — COMMENTED** [review]
@aescolar, the changes that affect ZBus are ok.

**Comment by cfriedt** [comment]
Looks good in terms of C/C++ library changes.

One question I had was whether it might help to kind of re-use some of the "device" machinery here for the interface in order to overload the C global namespace a bit less.

So this would fall into the category of a "pseudo device". 

Specifically, if we consider the native simulator a device, then we could consider that it also has a device API, a `const` config, and mutable data.

The native sim _interface_ in this case would be very cleanly encapsulated using all of the existing device driver API machinery.

Technically, there is also nothing stopping us from using Devicetree at that point to describe / configure it either.

Just a thought.

**Comment by aescolar** [comment]
> Specifically, if we consider the native simulator "interface" 

Unfortunately that is not possible, as the native simulator lives before and after Zephyr. That is, it is not Zephyr starting the native simulator but viceversa. Also note that the native simulator runner lives without Zephyr, and is meant to be used also with other embedded OSes and with baremetal SW.

**Comment by aescolar** [comment]
Closing as the main PR is getting traction

**Pull request closed without merging**
