### PR TITLE
Use crypto drivers for Bluetooth - v2

### PR DESCRIPTION
**Pull request by ceolin**
Initial info about this pr in (#8351)
--- 
In addition to making the Bluetooth subsystem work with crypto drivers, this PR makes a few changes to accommodate it:

    This adds all the primitives needed to support the Bluetooth subsystem, including new algorithms (PRNG, CMAC, and ECC-DH).
    Implements the new algorithms and their associated modes in both the TinyCrypt and mbedTLS shims
    Changes the Bluetooth subsystem to not require TinyCrypt, but rather declare its need for particular algorithms; the crypto backend can then be selected. Declaring the need for a particular algorithm will enable/disable the features in either mbedTLS or TinyCrypt. In the case of mbedTLS, however, only the default configuration file is aware of these declarations.

This has only been build-tested; I don't know enough of Bluetooth to carry on the necessary testing to ensure that this is working correctly, and I would appreciate help in getting this tested.

This is a step in closing #8081.
--

This new version address some problems spotted during review and add what was missing to make mbedTLS crypto driver feature compatible with TinyCrypt driver. In resume:

 - Fix mempool usage
 - Fix entropy device dependency (mbedTLS)
 - Fix additional data usage in `cipher_prng_op()`
 - Fix samples/drivers/crypto and ensured that this sample works in both implementations
 - Fix old problem in CBC mode (TinyCrypt), output length was being reported wrongly.
 - Added CBC mode for mbedTLS
 - Added CTR mode for mbedTLS

notes:
1 - This pr is on top of #9127
2 - This pr is a replacement to #8351

### CODE REVIEW

**Comment by pizi-nordic** [comment]
FYI: @cvinayak

**Comment by ceolin** [comment]
some tests are failing due mbetls's size. Should I disable them ?
Other failures are related to memory alignment in memory pool, cooking a V2 fixing it.

**Comment by dleach02** [comment]
If tests are failing on some platforms because of size issues then would that not imply that those platforms can not support mbedtls as an option? If so, then couldn't we set up things so mbedtls is not tested on those platforms?

**Comment by ceolin** [comment]
@dleach02  sort of ... The tests failing is using several algorithms (CBC, CTR and CCM). Applications using less options can fit even in the platforms that are failing.

A conservative approach could be skip this test in failing platforms while we check whether or not is possible tuning mbedTLS to requires less resources.

**Comment by dleach02** [comment]
I agree. Those platforms where it is failing due to size constraints can be further looked at by folks who find it important enough for them to get mbedtls working over tinycrypt.

**Comment by ceolin** [comment]
Hi @jhedberg, can you take a look in this pr. The main use of this will be on Bluetooth.

**Comment by ceolin** [comment]
@andrewboie @andyross can you guys help me reviewing it ?

**Comment by jhedberg** [comment]
@MariuszSkamra @kolodgrz We'd need to have all LE pairing and mesh provisioning PTS tests run for this PR

**Comment by kolodgrz** [comment]
I've testet it against PTS test cases with MESH for now and this PR introduces a regression in comparison with master (HEAD d66e8077cef9c22f5dc09628ae1436a529a35472).

With master (100% PASS rate 18/18)
 1/18   MESH   MESH/NODE/MPS/BV-07-C        PASS            25.927
 2/18   MESH   MESH/NODE/MPS/BV-04-C        PASS            23.055                  
 3/18   MESH   MESH/NODE/MPS/BV-08-C        PASS            23.225                  
 4/18   MESH   MESH/NODE/MPS/BI-01-C        PASS            24.734                  
 5/18   MESH   MESH/NODE/MPS/BV-10-C        PASS            29.008                  
 6/18   MESH   MESH/NODE/MPS/BV-01-C        PASS            15.806                  
 7/18   MESH   MESH/NODE/MPS/BV-06-C        PASS            19.749                  
 8/18   MESH   MESH/NODE/MPS/BV-09-C        PASS            25.807                  
 9/18   MESH   MESH/NODE/MPS/BV-02-C        PASS            23.298                  
10/18   MESH   MESH/NODE/MPS/BV-05-C        PASS            22.574                  
11/18   MESH   MESH/NODE/MPS/BV-03-C        PASS            20.728                  
12/18   MESH   MESH/NODE/PROV/UPD/BV-11-C   PASS            45.448                  
13/18   MESH   MESH/NODE/PROV/BI-01-C       PASS            24.945                  
14/18   MESH   MESH/NODE/PROV/BI-02-C       PASS            85.097                  
15/18   MESH   MESH/NODE/PROV/UPD/BV-07-C   PASS            72.638                  
16/18   MESH   MESH/NODE/PROV/UPD/BV-01-C   PASS            63.207                  
17/18   MESH   MESH/NODE/PROV/UPD/BV-09-C   PASS            213.496                  
18/18   MESH   MESH/NODE/PROV/UPD/BV-10-C   PASS            28.721 

With PR9227 (78% PASS rate 14/18):               
 1/18   MESH   MESH/NODE/MPS/BV-07-C        PASS            20.986             
 2/18   MESH   MESH/NODE/MPS/BV-04-C        PASS            21.057                  
 3/18   MESH   MESH/NODE/MPS/BV-08-C        PASS            17.301                  
 4/18   MESH   MESH/NODE/MPS/BI-01-C        PASS            16.259                  
 5/18   MESH   MESH/NODE/MPS/BV-10-C        PTS TIMEOUT     162.699                  
 6/18   MESH   MESH/NODE/MPS/BV-01-C        PASS            14.345                  
 7/18   MESH   MESH/NODE/MPS/BV-06-C        PASS            22.779                  
 8/18   MESH   MESH/NODE/MPS/BV-09-C        PASS            15.775                  
 9/18   MESH   MESH/NODE/MPS/BV-02-C        PASS            15.948                  
10/18   MESH   MESH/NODE/MPS/BV-05-C        PASS            17.7                  
11/18   MESH   MESH/NODE/MPS/BV-03-C        PASS            15.046                  
12/18   MESH   MESH/NODE/PROV/UPD/BV-11-C   FAIL            80.245                  
13/18   MESH   MESH/NODE/PROV/BI-01-C       PASS            18.494                  
14/18   MESH   MESH/NODE/PROV/BI-02-C       PASS            58.053                  
15/18   MESH   MESH/NODE/PROV/UPD/BV-07-C   FAIL            79.263                  
16/18   MESH   MESH/NODE/PROV/UPD/BV-01-C   FAIL            79.861                  
17/18   MESH   MESH/NODE/PROV/UPD/BV-09-C   PASS            195.963                  
18/18   MESH   MESH/NODE/PROV/UPD/BV-10-C   PASS            24.076

I wasn't able to get land compare ogs with qemu because of error:
"***** Booting Zephyr OS v1.12.0-1280-ge2a1feeb68 *****
ASSERTION FAIL [flags != 0] @ ../../../../include/crypto/cipher.h:115:
	Keytype missing: RAW Key or OPAQUE handleqemu-system-arm: terminating on signal 15 from pid 16618 (python)"

Briefly, PTS is timing out or failing on provisioning step.

**Comment by kolodgrz** [comment]
Secure Manager tests:
SM/MAS/SIGN/BV-01-C [IUT transfers signed data – Success], SM/SLA/KDU/BV-02-C [LE Legacy Pairing, IUT Responder – Lower Tester sets IdKey bit – Success], SM/MAS/KDU/BV-05-C [LE Legacy Pairing, IUT Initiator – Lower Tester sets Idkey bit – Success] are failing.

Cannot get logs because of ASSERTION about which mentioned above

**Comment by ceolin** [comment]
Hi @kolodgrz thanks for testing it. I'll try to check this problem in qemu and submit a new pr.

**Comment by ceolin** [comment]
@kolodgrz the crash on qemu_cortex_m3 was due main stack's size.

Can you test again doing like in https://github.com/zephyrproject-rtos/zephyr/pull/9227/commits/80c8b149d40868d7e2ebb5fa636296a962e3702c#diff-0a2ce469f862d39fa55bab31a5577048R7 ?

**Review by nashif — APPROVED** [review]

**Review by jhedberg — CHANGES_REQUESTED** [review]
I don't immediately see anything wrong with the PR, however we need to sort out the PTS failures before this gets merged, so marking it with "Request changes" until that (also added the DNM label)

**Comment by nashif** [comment]
blocking change with a -1 is enough, lets not put DNM on it which keeps reviewers away.

**Comment by jhedberg** [comment]
I did some testing using samples/bluetooth/peripheral_sc_only and tried connecting from my iPhone (LightBlue app). The pairing fails at the stage of validating the public key received from the iPhone:

```
[bt] [ERR] emulate_le_generate_dhkey: public key is not valid (ret -22)
```

Note that to get the log you need to enable `CONFIG_BT_DEBUG_LOG=y` for that app.

I tried replacing `sys_memcpy_swap()` with `memcpy()` in case this is just a byte-order issue, but that's not the case. I also tried removing the public key validation, but then the pairing just fails at a later stage.

**Comment by jhedberg** [comment]
Another thing I noticed: mbedtls it taking more stack space and busting the hci_ecc thread's stack when debug logs are disabled:

```
ecc stack (real size 1024):     unused 0        usage 1024 / 1024 (100 %)
***** HARD FAULT *****
***** Hardware exception *****
***** Booting Zephyr OS v1.12.0-1602-g18a74cefda *****
```

**Comment by jhedberg** [comment]
Increasing the ecc thread stack size fixes the hard fault, but the public key validation still fails, so this was not the cause of it.

**Comment by jhedberg** [comment]
Hold on, the above was with `TINYCRYPT_SHIM=y` based on `<build_dir>/zephyr/.config`. I'm unable to build with `CONFIG_CRYPTO_MBEDTLS_SHIM=y`. It seems it has broken dependencies. The Kconfig entry for it has various select statements, but seems it's not sufficient since I get the following when building the app:

```
drivers/crypto/libdrivers__crypto.a(crypto_mtls_shim.c.obj): In function `mtls_ecc_gen_shared_key':
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:692: undefined reference to `mbedtls_ecp_keypair_init'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:693: undefined reference to `mbedtls_ecp_group_free'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:694: undefined reference to `mbedtls_ecp_group_load'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:699: undefined reference to `mbedtls_ecp_point_init'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:700: undefined reference to `mbedtls_ecp_point_read_binary'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:715: undefined reference to `mbedtls_ecdh_compute_shared'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:730: undefined reference to `mbedtls_ecp_point_free'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:732: undefined reference to `mbedtls_ecp_keypair_free'
drivers/crypto/libdrivers__crypto.a(crypto_mtls_shim.c.obj): In function `mtls_ecc_validate_pubkey':
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:656: undefined reference to `mbedtls_ecp_group_load'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:662: undefined reference to `mbedtls_ecp_point_init'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:663: undefined reference to `mbedtls_ecp_point_read_binary'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:668: undefined reference to `mbedtls_ecp_check_pubkey'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:671: undefined reference to `mbedtls_ecp_point_free'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:672: undefined reference to `mbedtls_ecp_group_free'
drivers/crypto/libdrivers__crypto.a(crypto_mtls_shim.c.obj): In function `mtls_ecc_gen_key':
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:615: undefined reference to `mbedtls_ecp_keypair_init'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:616: undefined reference to `mbedtls_ecp_gen_key'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:629: undefined reference to `mbedtls_ecp_point_write_binary'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:636: undefined reference to `mbedtls_ecp_keypair_free'
drivers/crypto/libdrivers__crypto.a(crypto_mtls_shim.c.obj): In function `mtls_mac_op':
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:518: undefined reference to `mbedtls_cipher_cmac_finish'
/home/jh/src/zephyr/drivers/crypto/crypto_mtls_shim.c:521: undefined reference to `mbedtls_cipher_cmac_update'
```

**Comment by ceolin** [comment]
@jhedberg 
```
+CONFIG_MBEDTLS_CFG_FILE="config-tls-generic.h"
+CONFIG_CRYPTO_ENABLE_AES_CCM=y
+CONFIG_CRYPTO_ENABLE_AES_CBC=y
+CONFIG_CRYPTO_ENABLE_AES_CTR=y
+CONFIG_TLS_CIPHER_AES_ENABLED=y
+CONFIG_TLS_CIPHER_DES_ENABLED=y
+CONFIG_TLS_CIPHER_CCM_ENABLED=y
```

it fixes these dependencies, but indeed, these dependencies are not clear, I'll fix it and send a new version.

**Comment by ceolin** [comment]
@jhedberg found (and fixed) the key's problem that you mentioned, undefined references was also fixed (relating some dependencies in kconfig.

I've tested peripheral_sc_only with my phone using nRF connect and it's working now.
(tested native_posix port with both mbedTLS and tinycrypt implementations)

Can you give a second look in this pr please ?

**Comment by jhedberg** [comment]
@ceolin thanks for the updates, however I still see the same issues with the TinyCrypt shim. The remote public key gives:
```
[bt] [ERR] emulate_le_generate_dhkey: public key is not valid (ret -22)
```

And I need to increase the ECC thread stack size to not cause an overflow:
```
--- a/subsys/bluetooth/host/hci_ecc.c
+++ b/subsys/bluetooth/host/hci_ecc.c
@@ -35,7 +35,7 @@
 #endif
 
 static struct k_thread ecc_thread_data;
-static BT_STACK_NOINIT(ecc_thread_stack, 1024);
+static BT_STACK_NOINIT(ecc_thread_stack, 1152);
 
 /* based on Core Specification 4.2 Vol 3. Part H 2.3.5.6.1 */
 static const u32_t debug_private_key[8] = {
```

Next I'll try to enable the mbedtls shim to see how the behavior is with that (e.g. whether the stack size increase is sufficient for it as well)

**Comment by jhedberg** [comment]
@ceolin btw in your own testing make sure you don't fall back to legacy LE pairing but use LE SC instead, since only with that do you exercise the ECC usage. I've used `samples/bluetooth/peripheral_sc_only` as a starting point, but you can force any other Bluetooth app use SC (or fail if the peer doesn't support SC) by enabling `CONFIG_BT_SMP_SC_ONLY=y`

**Comment by jhedberg** [comment]
Well, I was finally able to switch to mbedtls, however didn't get off to a good start:
```
Advertising successfully started
***** HARD FAULT *****
***** Hardware exception *****
Current thread ID = 0x200038f4
Faulting instruction address = 0x1abd
Fatal fault in ISR! Spinning...
```

The reason turns out to be that mbedtls consumes *way* more call stack than TinyCrypt does, so the modest increase I had to do for TinyCrypt is not sufficient. Increasing to 2k works, and shows this:
```
ecc stack (real size 2348):     unused 688      usage 1660 / 2348 (70 %)
```

So mbedtls is not increasing the code size but also RAM consumption by a substantial amount. I'm now worried that we wont be able to fit our micro:bit applications into 16k anymore.

Even after the stack increase mbedtls fails at an even earlier stage than TinyCrypt. I don't even need to connect since it's not able to generate the initial key pair:
```
[bt] [ERR] generate_keys: Could not generate key
[bt] [WRN] bt_smp_pkey_ready: Public key not available
```

**Comment by jhedberg** [comment]
@ceolin I just tried peripheral_sc_only on native_posix using the mbedtls shim, and things don't work there either. The same thing as I obvserved on nrf51_pca10028 happens, i.e. local public-private key pair generation fails:
```
[bt] [ERR] generate_keys: Could not generate key
[bt] [WRN] bt_smp_pkey_ready: Public key not available
```

Note (again) that you need to enable `CONFIG_BT_DEBUG_LOG=y` to see these errors and warnings. I bet you didn't have those enabled, and in that case it may *look* like things work, since you get connected without errors (however pairing doesn't happen).

**Comment by kolodgrz** [comment]
@ceolin I did some testings agains PTS (still **failing**). Mostly failing after pairing initiation. Attached logs from one of failing test cases ZephyrOS logs: https://privatebin.net/?b9352dd7b5cefacf#5+PqW4GLKQ1Vz4H/906UwCgc4dubnQga6YwWGMTo5DM= .
btmon logs: https://privatebin.net/?a9457a9423c50f13#h8QY+z4/s5M3V+A08fzVhMqh2IO3SD4crOMGgyz8g54=

**Comment by ceolin** [comment]
@kolodgrz thanks for looking it. Can you give me the instructions to reproduce your tests ? At this moment I've tested peripheral_sc_only + sanitychecks (to ensure that crypto drivers are working).

**Comment by jhedberg** [comment]
> Both cases worked, see the output:

@ceolin see my earlier comments. Your output does *not* mean that it worked. If you don't see the message "Security changed: <addr> level 4" then you haven't exercised any of the crypto code. It's unfortunate that the peripheral_sc_only app doesn't print a clear error when pairing gets aborted, but you should at least see the error if you enable `CONFIG_BT_DEBUG_LOG=y` as I earlier suggested.

**Comment by jhedberg** [comment]
@ceolin @kolodgrz btw, PTS is probably an unnecessarily slow way to proceed with fixing this at the moment, since the issue can be trivially & quicker triggered by initiating Secure Connections-based pairing or Mesh provisioning manually (i.e. the two use cases that use ECC). Once such manual tests start passing we can get back to running all the PTS tests.

**Comment by ceolin** [comment]
@jhedberg I've enabled `CONFIG_BT_DEBUG_LOG`, that is why I received
`[bt] [WRN] hci_vs_init: Controller doesn't seem to support Zephyr vendor HCI` right ?

Other thing, I've successfully connected my phone to peripheral_sc_only app, and as fair as I understood, this app will always ensure that it's not using legacy pairing. Though, I've never received this "Security changed: level 4" message, I'll search for it and debug from that. But, just to be clean, I've enabled debug logs since the very beginning. If this app is connecting to my phone using a legacy pairing we probably have other bug as well.

**Comment by jhedberg** [comment]
@ceolin I'm not sure why you don't get an error then, however in my own testing the connection stayed up even when pairing was never completed. It's not really a stack bug since it's an application policy for what it wants to do, and the peripheral_sc_only does not have any special code to disconnect upon pairing failure.

**Comment by jhedberg** [comment]
Just one other note: the "level 4" log should come from a printk() in the app's own security_changed() function in main.c, i.e. it doesn't require BT_DEBUG_LOG.

**Comment by ceolin** [comment]
that's weird indeed. I'm building with/without this pr and results are looking the same, I've enabled basically all debug options to trace execution and they look similar. But definitely will debug this security_changed() function. I'll try run this test using qemu as well (instead of only using native_posix).

**Comment by jhedberg** [comment]
Found the reason why TinyCrypt public key validation is faling: you're misinterpreting the return value of `uECC_valid_public_key()`. It's documented to return 0 on success and a negative value on failure. TC_CRYPTO_SUCCESS is defined to be 1, so that'll never match. The following change makes the validation work for me:
```
--- a/drivers/crypto/crypto_tc_shim.c
+++ b/drivers/crypto/crypto_tc_shim.c
@@ -318,7 +318,7 @@ static int do_ecc_op_validate_pubkey(struct cipher_ctx *ctx,
        r = uECC_valid_public_key(pkt->public_key,
                                  &curve_secp256r1);
 
-       return r == TC_CRYPTO_SUCCESS ? 0 : -EINVAL;
+       return r == 0 ? 0 : -EINVAL;
 }
 
 
```

**Comment by jhedberg** [comment]
Now that the ECC part seems to be working with TC, I'm getting failures with AES CMAC - looking at that now.

**Comment by jhedberg** [comment]
Enabling crypto logs reveals this:
```
[general] [ERR] tc_session_setup_mac: Only AES-ECB, with 128-bit keys are supported
```

**Comment by ceolin** [comment]
@jhedberg I'm checking it. Thanks for review

**Comment by ceolin** [comment]
@jhedberg Finally I could see the problem you are mentioning, I was tricked by the connected() message in Zephyr and the application that I'm using on android. Understood how it works now.

About `tc_session_setup_mac()`, it seems to be a bug, I've tested without it and has worked, but I'll ensure that this was a bug before sending a new version. I'll test with mbedtls as well.

My tests are in qemu_x86 and native_posix ports only.

Thanks a lot again !

**Comment by jhedberg** [comment]
@ceolin I've opened #10162 to improve the logging of peripheral_sc_only so it doesn't give this false impression of "everything is fine" when it in fact isn't.

**Comment by jhedberg** [comment]
Thanks for the updates @ceolin 

The TinyCrypt shim works now, however I've needed to increase the HCI ECC stack size for both shims as follows:

```
--- a/subsys/bluetooth/host/hci_ecc.c
+++ b/subsys/bluetooth/host/hci_ecc.c
@@ -34,8 +34,14 @@
 #include "hci_core.h"
 #endif
 
+#if IS_ENABLED(CONFIG_CRYPTO_TINYCRYPT_SHIM)
+#define ECC_STACK_SIZE 1152
+#else
+#define ECC_STACK_SIZE 1792
+#endif
+
 static struct k_thread ecc_thread_data;
-static BT_STACK_NOINIT(ecc_thread_stack, 1024);
+static BT_STACK_NOINIT(ecc_thread_stack, ECC_STACK_SIZE);
 
 /* based on Core Specification 4.2 Vol 3. Part H 2.3.5.6.1 */
 static const u32_t debug_private_key[8] = {
```

It'd be good to incorporate a patch like that to this PR.

Now, moving onto mbedTLS, I enabled `CONFIG_CRYPTO_MBEDTLS_SHIM=y`, however I'm not even able to generate a keypair. It turns out that `mbedtls_ecp_gen_key()` fails with `MBEDTLS_ERR_ECP_ALLOC_FAILED`.

**Comment by jhedberg** [comment]
Increasing `CONFIG_MBEDTLS_HEAP_SIZE` from its default 512 to 1024 changes the `mbedtls_ecp_gen_key()` error to `MBEDTLS_ERR_MPI_ALLOC_FAILED`, and it seems to stay like that even if I increase the heap to 2k or even 4k.

**Comment by ceolin** [comment]
@jhedberg I've increase the heap to 8k here, but this is kinda of ridiculous, also I've to increase the main stack size.

I'll incorporate your suggestion and dig a little bit more in mbedtls resource usage.

**Comment by jhedberg** [comment]
> @jhedberg I've increase the heap to 8k here, but this is kinda of ridiculous, also I've to increase the main stack size.

Agreed. There's no way we'll be able to replace TinyCrypt with mbedTLS if the overhead is that big. This is simply a showstopper for any 16k nRF51 board or the new low-cost 24k nRF52 board.

**Comment by carlescufi** [comment]
@ceolin @jhedberg have we considered using upstream [micro-ecc](https://github.com/kmackay/micro-ecc) directly?

**Comment by ceolin** [comment]
@carlescufi nope, I'd never seen. I'm just afraid we fall in the same tinycrypt problems, looking the repository it does not seem to be under development. The lack of bug fixes and possible security flaws are a problem. That's been said, I know nothing about this implementation.

**Comment by jhedberg** [comment]
@ceolin micro-ecc is what TC used for its ECC implementation.

**Comment by ceolin** [comment]
I see, well, tinycrypt support in crypto drivers is working and fitting in supported platforms, other backends can be implemented using this interface.
I've found other problems in mbedtls implementation that I've fixed. native_posix is working well for both backends now, though it still consume a lot of resources.

@jhedberg my suggestion is (if there is no bug) integrate it, since it is not breaking anything and continue using tinycrypt as default for smaller platforms while we try to reduce resources usage on mbedtls. Another advantage with this pr is that make easier change the crypto library used in bluetooth, basically it does not require change any line in bluetooth's code. What you think ?

**Comment by jhedberg** [comment]
@ceolin that would be ok, except I don't see the hci_ecc.c stack size increase incorporated yet to this PR. It's needed even for TinyCrypt since the new layers of abstraction increase the call stack usage. It'd be good if you could do at least some tests on real HW since you'd see this issue immediately then. I also think that we should do one more PTS test run for both Bluetooth pairing and Mesh Provisioning before this gets merged (ping @MariuszSkamra @sjanc), to be completely sure we're not breaking anything critical. I've only done manual pairing testing so far.

Another note: I'll be offline for the next two weeks (vacation), so I wont be able to give any more feedback on this PR if it's to be merged during that time.

**Comment by ceolin** [comment]
@jhedberg about the usage, following the results for bcc_microbit

with crypto driver and using tinycrypt
```
Memory region         Used Size  Region Size  %age Used
           FLASH:        101 KB       256 KB     39.45%
            SRAM:       16148 B        16 KB     98.56%
        IDT_LIST:         120 B         2 KB      5.86%
```
without crypto driver (current master):
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      102500 B       256 KB     39.10%
            SRAM:       15792 B        16 KB     96.39%
        IDT_LIST:         120 B         2 KB      5.86%
```

Thanks for helping and enjoy your vacation.

**Comment by aescolar** [comment]
It has been now more than 9 months since there has been any activity in this PR. Assuming there is no interest in pursuing it further I close it. If you would like to continue with it, please reopen it.

**Pull request closed without merging**
