### PR TITLE
kernel/work_q: Fix block-in-spinlock bug

### LINKED ISSUE #13411: kernel: ASSERTION FAIL [z_spin_lock_valid(l)]
This is similar to #13289 but 100% reproducible with a simple `main.c`

Run the following on `qemu_x86` or any `nrf` board:
 
https://github.com/lemrey/zephyr/tree/bug-workq

```
prj.conf:
CONFIG_ASSERT=y
---
main.c:
#include <zephyr.h>
#include <misc/printk.h>

struct k_delayed_work dw;

void work_handler(struct k_work *w)
{
	k_delayed_work_submit(&dw, 10);
}

void main(void)
{
	printk("Hello World! %s\n", CONFIG_BOARD);

	k_delayed_work_init(&dw, work_handler);
	k_delayed_work_submit(&dw, K_NO_WAIT);

	while (1) {
		k_sleep(K_SECONDS(1));
	}
}
```

results in:
`ASSERTION FAIL [z_spin_lock_valid(l)] @ zephyr.git/include/spinlock.h:66`

### PR DESCRIPTION
**Pull request by andyross**
Work queues are implemented in terms of k_queue objects which provide
their own synchronization.  In particular insertion is potentially
blocking and always acts as a reschedule point, which means that it
must not be called with spinlocks held.

Release the lock first, and do a little cleanup of the resulting
k_delayed_work_submit_to_queue() logic.

Fixes #13411

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by carlescufi** [comment]
Thanks @andyross. I will test it as soon as I can today

**Review by ioannisg — APPROVED** [review]
Worked for me
Tested on
- nrf52_pca10040
- nrf52840_pca10056
- nrf9160_pca10090
- frdm_k64f

**Review by carlescufi — APPROVED** [review]
This fixes the issue on qemu and nrf boards.
Thank you!

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by lemrey** [comment]
This fixed it, thank you @andyross.

**Pull request merged**
