### PR TITLE
Revert "doc: move 'getting help' to contrib guidelines"

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This reverts commit 05ccdd7c4086d940d2cfd311ae8102f2d905b6e7.

I put it in a standalone place so that it would be easy for beginners
to find.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
I wasn't asked for review on the original PR that did this (https://github.com/zephyrproject-rtos/zephyr/pull/34364) and I would have -1ed.

**Comment by mbolivar-nordic** [comment]
Also, in no way is "I need help with using zephyr" content that belongs in a page about "here is how to contribute to zephyr".

**Review by henrikbrixandersen — APPROVED** [review]
Moving this to a more prominent spot certainly won't hurt. Thanks.

**Comment by mbolivar-nordic** [comment]
> Moving this to a more prominent spot certainly won't hurt. Thanks.

Just to be clear, this PR is putting it back to where it originally was and had been since I added the page. Thanks for review.

**Review by nashif — CHANGES_REQUESTED** [review]
The page was moved to another location at the SAME level, not following how the previous location was more prominent. It is is still linked the same way and currently is actually more prominent as it is higher in the overall TOC. We can argue where it should go and maybe "Contribution Guidelines" is not the right fit, but it does not belong into a separate "Guide".

The main reason for the move is an ongoing cleanup and reduction of what we currently have under "User and Developer Guides" and "API Reference" with the final goal of introducing a new structure and layout that is modular (#33725).

**Review by carlescufi — APPROVED** [review]
I'm with @mbolivar-nordic on this one. The content is not related at all with contribution, so it either belongs in its own page or in the Getting Started Guide in my opinion. I see @nashif points about the restructuring, but this can be done later once we have a proper place for it.

**Comment by mbolivar-nordic** [comment]
> The page was moved to another location at the SAME level, not following how the previous location was more prominent.

Before:

2021-05-06T10:05:10,694820585-07:00


After:

2021-05-06T10:04:41,414469450-07:00

**Comment by mbolivar-nordic** [comment]
@nashif yes, it's moved to here:

2021-05-06T10:08:21,630854255-07:00

But that makes no sense.

This is not information for contributors; it's for users.

**Review by nashif — CHANGES_REQUESTED** [review]
> This is not information for contributors; it's for users.

then put it in 'Getting Started Guide'

**Comment by mbolivar-nordic** [comment]
> then put it in 'Getting Started Guide'

done

**Review by nashif — APPROVED** [review]

**Pull request merged**
