### PR TITLE
dts: bindings: Have 'required: true/false' instead of 'category: ...'

### PR DESCRIPTION
**Pull request by ulfalizer**
The `category: required/optional` setting for properties is just a
yes/no thing. Using a boolean makes it clearer, so have
`required: true/false` instead.

The scripts in `scripts/dts/` ignore this setting, and only print a
warning if `category: required` in an inherited binding is changed
to `category: optional`. Update the code for that warning.

Print a warning if `category: ...` appears in the settings for a
property, along with a hint to replace it with `required: true/false`.
The new device tree parser will turn it into an error, and will keep the
hint.

The replacement was done with

    git ls-files 'dts/bindings/*.yaml' | xargs sed -i \
        -e 's/category:\s*required/required: true/' \
        -e 's/category:\s*optional/required: false/'

`dts/bindings/device_node.yaml.template` was updated as well.

### CODE REVIEW

**Comment by ulfalizer** [comment]
There's one more binding format change I want to make after this one, but I'll probably wait until the new parser is in.

The way it's currently used, `!include` isn't really needed. We could just have

```
inherits:
    - foo.yaml
    - bar.yaml
```

That'd get rid of some hairy PyYAML stuff too.

**Review by erwango — APPROVED** [review]
Clearer indeed

**Comment by b0661** [comment]
> There's one more binding format change I want to make after this one, but I'll probably wait until the old parser is gone.

If you are changing the binding format you should also think about the '#cells' information in the binding. This might become ambiguous if you have several cell based properties in the same binding. It might be better to make it more specific; aka. '#interrupt-cells', '#clock-cells', .... "#cells" may just be the fallback if no specific info is found.

**Comment by ulfalizer** [comment]
@b0661 
Hadn't thought of that. Could look into later.

Wonder if it's caused any workarounds yet.

**Review by carlescufi — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
I'd rather we not change the binding description, or if we are going to, that we move towards making the bindings in-sync with dtschema (https://github.com/devicetree-org/dt-schema/)

So for 'category' it would become 'required:' with a list of required props.

**Comment by ulfalizer** [comment]
@galak 
Don't think it'll be that bad as long as the error clearly says what needs to change for outdated bindings. Probably doesn't take more than a minute to fix.

If we lock down the format, then we're stuck and can't improve on it.

Not against moving towards some other schema format later. For now, this feels like a small immediate improvement though. Maybe it's already a bit closer too.

**Pull request closed without merging**
