### PR TITLE
scripts: runners: fix blackmagicprobe SIGINT behavior

### LINKED ISSUE #21139: west: runners: blackmagicprobe: Keyboard Interrupt shouldn't kill the process
**Describe the bug**
Currently, when using `west {debug,attach}` (at least with blackmagicprobe runner), pressing Ctrl-C will kill the runner process and child process. However, this is not be desirable when using GDB or other utilities that catch and use interrupt as a part of debugging process. 

**To Reproduce**
```
west attach -r blackmagicprobe 
(gdb) run
[press Ctrl-C to pause the execution]
Starting program: /.../build/zephyr/zephyr.elf
^C
Program received signal SIGINT, Interrupt.
arch_cpu_idle () at /.../zephyrproject/zephyr/arch/arm/core/cpu_idle.S:78
78              bx lr
user@linux:~$ # gdb was killed
```

**Expected behavior**
Keyboard Interrupt should be passed to the child process instead of stopping runner and killing child process as a result. i.e. GDB  should normally break execution of the running program.

**Impact**
It's impossible to properly debug hardware using runner that uses, for example, GDB, thus one is forced to run and configure it manually to be able to use interrupts to break execution.

**Screenshots or console output**
see To Reproduce

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: west & blackmagicprobe runner
 West version: v0.6.1
zephyr commit  0a925bdf9c574bf57940ff41354806f851b6ccfe

**Additional context**

### PR DESCRIPTION
**Pull request by mbolivar**
Fixes: #21139

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
please write a more descriptive commit message

**Comment by dleach02** [comment]
@mbolivar

**Comment by mbolivar** [comment]
> please write a more descriptive commit message

I copy/pasted the root cause comment from the issue description

**Review by MaureenHelm — APPROVED** [review]
Thanks!

**Pull request merged**
