### PR TITLE
net: shell: Fix relative include paths

### PR DESCRIPTION
**Pull request by ycsin**
Fix include paths that should be relative to the file to avoid editor/IDE warnings.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
We have the include paths set in CMakefile already, why this is needed?

**Comment by ycsin** [comment]
> We have the include paths set in CMakefile already, why this is needed?

VSCode was complaining that it couldn't find these files, maybe it didn't factor in the CMake file..

**Comment by rlubos** [comment]
@ycsin I'm using VS code as well and don't have this problem (AFAIR I didn't change anything in the configuration with regards to include path), perhaps you've changed something in the config that confuses VS code?

I any case, I don't think we should modify the sources to resolve specific editor issues, from the build system perspective current setting is perfectly fine.

**Comment by ycsin** [comment]
> @ycsin I'm using VS code as well and don't have this problem (AFAIR I didn't change anything in the configuration with regards to include path), perhaps you've changed something in the config that confuses VS code?

Do you mind sharing your vscode configurations (intellisense? plugin? include path / using `compile_commands.json`?)

> I any case, I don't think we should modify the sources to resolve specific editor issues, from the build system perspective current setting is perfectly fine.

Agree, closed

**Pull request closed without merging**
