### PR TITLE
runners: harmonize misc-flasher template with the other runners

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Make the misc-flasher template work like all the other runners:

- use board_set_flasher_ifnset so that it's used automatically if specified first
- rename the file to match the runner name so one could use something like:

board_runner_args(misc-flasher "...")
include(${ZEPHYR_BASE}/boards/common/misc-flasher.board.cmake)

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]

**Review by mbolivar-ampere — CHANGES_REQUESTED** [review]
Do we really need this?

It's going to break out of tree boards that load this file. Yes, it's a wart, but I don't think it's **that** bad...

**Comment by fabiobaltieri** [comment]
> Do we really need this?
> 
> It's going to break out of tree boards that load this file. Yes, it's a wart, but I don't think it's **that** bad...

Yeah I think it's worth doing it, right now if you want to set some default parameters for this one you have to use the argument `misc-flasher` but include the `misc` template, which is unlike any other runner and fairly confusing. It's a simple change, I'll add a line in the release notes.

**Comment by fabiobaltieri** [comment]
Well, I guess I may as well use it on other boards while I'm at it.

**Comment by dcpleung** [comment]
Maybe keep the current `misc.board` and use the deprecation process on it? It will avoid breaking any out-of-tree boards.

**Comment by fabiobaltieri** [comment]
> Maybe keep the current `misc.board` and use the deprecation process on it? It will avoid breaking any out-of-tree boards.

Sure, kept the old file added a cmake warning in there. Can't help but think that it'll just get ignored and break down the road anyway but hey I guess at least we tried.

**Comment by dcpleung** [comment]
> Sure, kept the old file added a cmake warning in there. Can't help but think that it'll just get ignored and break down the road anyway but hey I guess at least we tried.

That's why I usually add "You've been warned!" in the warnings. Sometimes even in the line of ... "don't even think about filing bugs". :P

**Comment by fabiobaltieri** [comment]
> That's why I usually add "You've been warned!" in the warnings. Sometimes even in the line of ... "don't even think about filing bugs". :P

Yeah I think I saw some. :-) Anyway, if I can figure why CI is mad at me now...

**Comment by fabiobaltieri** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/61131 for CI sadness

**Comment by mbolivar-ampere** [comment]
I'd rather see a deprecation framework put in for runner names. C'mon, y'all, we're heading into LTS2, let's please try to avoid gratuitous compatibility breakage.

I have a half-done framework locally but I might be a bit slow to finish it up. Feel free to take a crack at it yourself if you get impatient; you need to modify core.py and run_common.py under scripts/west_commands to add the framework

**Comment by fabiobaltieri** [comment]
> I'd rather see a deprecation framework put in for runner names. C'mon, y'all, we're heading into LTS2, let's please try to avoid gratuitous compatibility breakage.

That seems like a disproportionate amount of work for the change.

How about this: I kept the old template, just added the new one.

**Comment by mbolivar-ampere** [comment]
> That seems like a disproportionate amount of work for the change.

I don't agree. We should be prioritizing the developer experience, not our own convenience. All the individual breaking changes are papercuts that add up.
 
> How about this: I kept the old template, just added the new one. All the compatibility!

In my opinion this is even worse than a breaking change: now there are two things that do the same thing, or do they?

**Comment by mbolivar-ampere** [comment]
> I have a half-done framework locally but I might be a bit slow to finish it up.

https://github.com/zephyrproject-rtos/zephyr/pull/61243

PTAL

**Comment by mbolivar-ampere** [comment]
I'm going to say "no" to this one. Let's move the discussion to the other PR

**Pull request closed without merging**
