### PR TITLE
ext: mbedtls: Allow base64 compilation only

### PR DESCRIPTION
**Pull request by carlescufi**
In order to reuse the base64 library that comes with mbedTLS we use that
as the only implementation in Zephyr. That however forces any app that
requires only the base64 library to compile the whole mbedTLS set of
files, which is rather large.

Introduce CONFIG_MBEDTLS_BASE64 and CONFIG_MBEDTLS_CRYPTO in order to
refine the parts of the mbedTLS library that get built when enabling it.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by mike-scott** [comment]
LGTM, but I'll defer to @tbursztyka or @jukkar to approve

**Comment by nashif** [comment]
oh wow, all of this just to reuse something as simple as base64! Not really comfortable with how this is being done. If base64 is going to be used on its own we maybe should implement it natively in zephyr and stop pulling all of mbedTLS just for one file. Now we are creating some pseudo classification and adding more config options making this difficult to understand and configure.

**Comment by carlescufi** [comment]
@nashif Yes, there was a point when @nvlsianpu wanted to introduce native base64 but he was told that mbedTLS already implements it so better use that one instead. Given  all this what I'm gonna do is to pull that single file from mbedtls, rename it and place it in `zephyr/lib/base64` and end of the story. This will duplicate base64 though, when required both by mbedTLS and by other libraries.

**Comment by carlescufi** [comment]
@nvlsianpu no need for a special config file when compiling only that `base64.c` because it basically uses nothing from the config file.

**Comment by carlescufi** [comment]
Closing this in favor of https://github.com/zephyrproject-rtos/zephyr/pull/6753

**Pull request closed without merging**
