### PR TITLE
NXP: mimxrt1024_evk: Ethernet issue: Fixes #57808

### LINKED ISSUE #57808: RT1024 EVK - Fix Ethernet PHY pins
**Describe the bug**

Ethernet issue on RT1024 EVK: 

Issue was confirmed using the **samples/net/sockets/dumb_http_server** with Zephyr release **v3.3.0**. 
The sample ran with no errors displayed in the console, but a computer connected on the same Ethernet network could not connect to the web server or ping the static IP address 192.0.2.1. 
The LEDs on the Ethernet jack were dim, not full brightness. Probing the signals to these LEDs, they were at 1.6V instead of 0V.
Probing the ENET RST signal to the PHY reset, it was not toggling when the ENET driver toggles the reset pin.

**Expected behavior**
ENET RST signal should toggle 

**Impact**
Ethernet connection is impacted

**Environment:**
 - OS: Windows
 - Toolchain: Zephyr SDK v0.16.0
 - Commit SHA: https://github.com/zephyrproject-rtos/zephyr/commit/fb779e0b1b8fed17341d1327babdc98bc3bfd6db

**Additional context**
PHY reset and interrupt GPIO pins were reversed

### PR DESCRIPTION
**Pull request by DishaNXP**
PHY reset and GPIO interrupt pins were reversed. Fixes #57808

### CODE REVIEW

**Review by DerekSnell — CHANGES_REQUESTED** [review]
Hi @DishaNXP ,
Thank you for contributing this.  But your commit message has a typo.  Can you please correct the board name to mimxrt1024_evk?  Otherwise, I am ready to approve this.  Thank you

**Review by DerekSnell — CHANGES_REQUESTED** [review]
Hi @DishaNXP ,
Now this PR is 3 commits for a simple change.  Please squash these into a single commit.  Thanks

**Comment by decsny** [comment]
> Now this PR is 3 commits for a simple change. Please squash these into a single commit. Thanks

I think this is caused because of using a merge commit,  so make sure to just rebase and fast forward onto the latest zephyr main.  Zephyr git strategy does not use merging, only rebasing.

**Comment by danieldegrasse** [comment]
Hi @DishaNXP, thank you for the contribution. Is the intention to merge this fix as a backport to the frozen v3.3 branch? Typically we would merge a fix like this into the latest `main` branch.

**Comment by dleach02** [comment]
@DishaNXP, it looks like your branch is messed up. Please rebase your changes on a fresh branch from main.

**Comment by DishaNXP** [comment]
I have created a new PR #58117 for this issue. Please refer:
https://github.com/zephyrproject-rtos/zephyr/pull/58117

**Pull request closed without merging**
