### PR TITLE
[RFC] fs: Convert FCB to use sectors (not areas)

### PR DESCRIPTION
**Pull request by ccollins476ad**
Prior to this commit: `struct fcb` contained a pointer to an array of `struct flash_area`.  Each entry in the array represented a flash sector that the fcb comprised.

After commit: `struct fcb` contains a pointer to an array of `struct flash_sector`, not `struct flash_area`.

Rationale: The FCB needs to know which sectors it occupies for its rotate operation.  However, the `flash_area` type is meant to represent a collection of sectors, not a single sector.  `struct flash_area` contains information that the fcb does not need (e.g., area ID and
device ID).  Furthermore, the flash_map API provides a means of converting a flash area ID to an array of sectors (`flash_area_get_sectors()`), but no way to convert to an array of areas.

I also squeezed a few flash_map nitpicks into this PR.

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@ccollins476ad Is Redy for using. All fcb tests passed. Shippable should pass as well.

**Comment by nashif** [comment]
need to fix checkpatch issues

**Comment by nvlsianpu** [comment]
<b>flash power management future:</b>

@ccollins476ad wrote:
> The changes look good to me.  I just have one possible concern.  I noticed the flash area gets opened once in `fcb_init()` (via a call to `flash_area_open()`), and never gets closed.  For internal flash, this is not a problem, but I believe the expectation was that flash areas would be opened when accessed, and closed when the access is complete.
I guess there was a thought that keeping an external flash device open is problematic (perhaps for power usage reasons).
So I'm not sure if this is something that should be changed or not.  Like I said, it should work fine with internal flash.
Maybe it is best to keep your changes as is.  This seems like an issue that is best addressed when needed (if ever).

my answer to this:
so far calling `flash_area_open` each time only increasing the latency. `flash_area_close` dose nothing. Maybe it was an idea of power management basing on this, but so fare this add only unwanted latency. My proposition is to modify flash_map API instead: Add f. `flash_area_get(int flash_area_id, flash_area **fap)` - it will do what current `flash_area_open' does so it will return proper flash_area pointer basing on flash_area_id.  Change 'int flash_area_open(int flash_area_id, flash_area **fap)' to 'int flash_area_open(flash_area *fap)' and limit its functionality to "flash power activation features" - so it will be empty for now. We will keep `flash_area_close` as is - but we coment that it is dedicated to functionality of "flash power deactivation future".

@mbolivar - I need your opinion on this, I'm not sure what idea was behind flash_area_open/close API i mynewt.

**Review by carlescufi — APPROVED** [review]
LGTM, pending the issue mentioned by @nvlsianpu

**Comment by nvlsianpu** [comment]
^^ Will open an issue for this - this can be threaten as improvement.

**Comment by carlescufi** [comment]
@nvlisanpu thanks!

**Comment by nvlsianpu** [comment]
done

**Comment by mbolivar** [comment]
> @mbolivar - I need your opinion on this, I'm not sure what idea was behind flash_area_open/close API i mynewt.

I've responded in the issue itself.

**Pull request merged**
