### PR TITLE
RFC: usb: drivers: Enable USB on stm32f429i_disc1 board

### PR DESCRIPTION
**Pull request by finikorg**
Enable USB controller for 32F429IDISCOVERY board:
https://www.st.com/en/evaluation-tools/32f429idiscovery.html

Signed-off-by: Andrei Emeltchenko <andrei.emeltchenko@intel.com>

### CODE REVIEW

**Review by ydamigos — CHANGES_REQUESTED** [review]
Could you also update board's doc files regarding usb support?

**Comment by finikorg** [comment]
@ydamigos At the moment this is RFC since USB is not working, do you know am I missing some configuration?

**Comment by ydamigos** [comment]
@finikorg Sorry, I thought the USB was working so I didn't check it thoroughly.
Yes, the USB OTG full speed on this board (CN6) is connected to OTG HS controller of the SoC, PB14 (OTG_HS_DM) PB15 (OTG_HS_DP).

There is already a discussion about it on the mainling list https://lists.zephyrproject.org/g/devel/message/4843

I also started working on it. Could you try it with the following branch:
https://github.com/ydamigos/zephyr/commits/stm32_otg_hs

I don't have the hw to test it, so any feedback is welcome.

**Comment by finikorg** [comment]
@ydamigos This PR is about OTG_FS, I checked https://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-discovery-kits/32f429idiscovery.html#design-scroll 
They seems to mention only FS.
And your tree is only about OTG_HS, right? (https://github.com/ydamigos/zephyr/commits/stm32_otg_hs)

**Comment by ydamigos** [comment]
@finikorg My tree is about OTG_HS controller. The controller on STM32F429 SoCs supports supports 3 PHY interfaces:
– An on-chip full-speed PHY
– An I2C Interface for external full-speed I2C PHY
– An ULPI interface for external high-speed PHY

So, the OTG_HS controller works in FS mode. @jli157 already tested my tree on his stm32f429 based board. He also raised issue #8791 about it.

**Comment by finikorg** [comment]
Closing old request

**Pull request closed without merging**
