### PR TITLE
kernel: timer: Enabling k_timer_stop from high priority context

### PR DESCRIPTION
**Pull request by nordic-krch**
Changes needed to prevent asserts when timer is stopped/restarted
from higher (than timeout) priority context. Without this change,
if expiration handler was interrupted and timer was stopped or
stopped and started timeout asserted due to attempt to link
already linked timeout object.

Failing use cases:
1. Stopping timer from higher priority interrupt
Periodic timer is running.
Timeout expiration is executed. It is interrupted before calling  `z_timer_expiration_handler` by higher priority interrupt which calls `k_timer_stop()`. Timer is stopped. We go back to `z_timer_expiration_handler` and call `z_add_timeout` since `timer->period` is set to periodic as a result timer keeps running even though it was stopped. Solution is to reset `period` field in `k_timer_stop`.

2. Restarting timer from higher priority interrupt.
Timeout expiration is executed. It is interrupted before calling  `z_timer_expiration_handler` by higher priority interrupt which calls `k_timer_start()` with period. Timer is started and timeout object is added to the list. We go back to `z_timer_expiration_handler` and call `z_add_timeout` which asserts because timeout object is already added to the list.
Solution: check is timeout is not already in the list.

Note that in both cases user function will still be executed even though it is after stop but that shall be expected and can be handled by the user who is aware that stopping from higher priority context may lead to that.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
Modifying the currently-executing timeout was always supposed to work from within the timeout handler.  That is, it was supposed to work already to call those functions "while the handler was running".  So I'm a little suspicious that this is addressing the wrong side of the issue, and that what we really have is a synchronization bug.

Stated differently: if this code works, then we must have had a pre-existing bug where k_timer_start/stop() from inside the handler would have triggered the same condition.  Did we?  (We might have!  If so you could simply the commit message and comment here, and we might want to write a test case to catch future regressions.)

If not, and this is a situation where it's racing against the timer internals and not just the handler, then this fix is almost certainly insufficient and we need to be looking for a missing lock somewhere.

**Review by andyross — CHANGES_REQUESTED** [review]
Giving this a -1 for now just so it doesn't merge too quickly.  If this really is just a pure logic bug then I'm fine with it; I just want to be sure this isn't papering over a synchronization failure instead.

**Comment by nordic-krch** [comment]
> we must have had a pre-existing bug where k_timer_start/stop() from inside the handler would have triggered the same condition

Bug is not visible when timer is reconfigured from within the handler. Only happens when it is preempted before expiry function is called. Periodic timeout is added to the list before calling expiry function.
Path is following:
- sys clock announces new ticks (`sys_clock_announce`)
- under lock, list of timeouts is checked, timeout function is called with lock released
- timer timeout handler is called, lock is set, if timer is periodic timeout is added to the list
- lock is released and expiry function is called

Issue occurs when context is preempted before timer handler (`z_timer_expiration_handler`) sets the lock.

**Comment by nordic-krch** [comment]
Sequence:
-lock is released in `timeout.c` before calling `t->fn(t)` https://github.com/zephyrproject-rtos/zephyr/blob/525fa76f4dd13d42549261c9fc846a150ee291bc/kernel/timeout.c#L252
- higher interrupt preempts and calls `k_timer_stop()`
- Lock is again taken in the timer handler https://github.com/zephyrproject-rtos/zephyr/blob/525fa76f4dd13d42549261c9fc846a150ee291bc/kernel/timer.c#L29
- timeout is scheduled again (for just stopped timer)  because `timer->period` was untouched during stop https://github.com/zephyrproject-rtos/zephyr/blob/525fa76f4dd13d42549261c9fc846a150ee291bc/kernel/timer.c#L37

**Comment by nordic-krch** [comment]
Second sequence is the same except for the fact that timer is restarted to periodic timer instead of being stopped. In that case, timeout is already added to the list by `k_timer_start` and `z_add_timeout` hits assert https://github.com/zephyrproject-rtos/zephyr/blob/525fa76f4dd13d42549261c9fc846a150ee291bc/kernel/timeout.c#L93

**Comment by nordic-krch** [comment]
@andyross any thoughts on that? We have test that fails because of that.

**Comment by carlescufi** [comment]
@andyross could you please take another look?

**Review by peter-mitsis — APPROVED** [review]
I think the proposed changes make sense.

**Comment by nordic-krch** [comment]
@andyross ping

**Pull request closed without merging**
