### PR TITLE
doc: update jquery version to 3.1.2

### PR DESCRIPTION
**Pull request by dbkinder**
The jquery provided by Sphinx 1.5.5 has a bug dealing with the
coordinates returned for offset().top for empty <span> tags, generated
by Sphinx for intra-document labels used to create hyperlink anchor
targets.  As reported in PR #5591, some browsers (chrome for example)
don't scroll to the right spot in the document when we link to these
intra-document label points.  jquery v3.2.1 fixes this.  (When Sphinx
updates the jquery included in its release, we can remove our copy that
is overriding the copy installed in the generated output by Sphinx.)

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
cant this be part of the theme?

**Comment by dbkinder** [comment]
Alas No, I tried that first.  It didn't override the jquery.js that Sphinx wanted to use,  This patch did.  We can remove this override when jquery is updated in a future version of Sphinx.

**Comment by nashif** [comment]
> Alas No, I tried that first. It didn't override the jquery.js that Sphinx wanted to use, This patch did. We can remove this override when jquery is updated in a future version of Sphinx.

which version?

**Comment by nashif** [comment]
CI now building with sphinx 1.6.5, is this still needed?

**Comment by dbkinder** [comment]
Yes, sphinx 1.6.5 uses jquery 3.1.0 and this issue was fixed in jquery 3.1.1 (current version of jquery is 3.1.2)

**Comment by dbkinder** [comment]
I've submitted a [Sphinx issue](https://github.com/sphinx-doc/sphinx/issues/4412) asking them to upgrade jquery, but until then, this PR is a workaround.

**Comment by nashif** [comment]
> I've submitted a Sphinx issue asking them to upgrade jquery, but until then, this PR is a workaround.

I am just not a big fan of pulling stuff like this into the tree, even as a workaround

**Comment by dbkinder** [comment]
Understandable.  But I'm at a loss for another solution for now. I can submit an issue to track this so when Sphinx is updated to include a newer jquery, we'll remove our local copy...

**Review by nashif — APPROVED** [review]

**Comment by dbkinder** [comment]
@nashif Sphinx 1.6.7 now ships with a working version of jquery (3.1.2) so we can update our CI systems (and remove the copy of jquery we imported once the CI systems are updated).

**Pull request merged**
