### PR TITLE
boards: qemu_x86_64: enable icount for CONFIG_MP_NUM_CPUS=1

### PR DESCRIPTION
**Pull request by dcpleung**
QEMU icount does not work correctly when more than 1 CPU is used,
but works fine with only 1 CPU enabled. So we can enable icount
on qemu_x86_64 when CONFIG_MP_NUM_CPUS=1. Sanitycheck goes from
~158 seconds to ~113 seconds on my dev machine.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]
ultimately, I'd like to learn why the round-robin CPU scheduling in icount-enabled QEMU (all on a single host emulator thread) breaks stuff.

**Review by wentongwu — APPROVED** [review]

**Comment by wentongwu** [comment]
> ultimately, I'd like to learn why the round-robin CPU scheduling in icount-enabled QEMU (all on a single host emulator thread) breaks stuff.

@andrewboie look at this case, qemu(with icount enabled) just has one vCPU thread working just like one core system, but the main thread just busy loop to wait other core's thread to run and never gives up CPU before checking test result, so qemu most likely doesn't run the spawned threads. From qemu TCG perspective, when translate target code to intermediate code, there is possibility that the checking result code is located at different TB with previous code so that other CPU thread can have chance to run and there may be a success result but there is no mechanism to make sure that. I think this can explain why it doesn't work with icount enabled on qemu for smp.

```
void test_coop_resched_threads(void)
{
        /* Spawn threads equal to number of cores,
         * since we don't give up current CPU, last thread
         * will not get scheduled
         */
        spawn_threads(K_PRIO_COOP(10), THREADS_NUM, !EQUAL_PRIORITY,
                      &thread_entry, THREAD_DELAY);

        /* Wait for some time to let other core's thread run */
        k_busy_wait(DELAY_US);


        /* Reassure that cooperative thread's are not preempted
         * by checking last thread's execution
         * status. We know that all threads got rescheduled on
         * other cores except the last one
         */
        for (int i = 0; i < THREADS_NUM - 1; i++) {
                zassert_true(tinfo[i].executed == 1,
                             "cooperative thread %d didn't run", i);
        }
        zassert_true(tinfo[THREADS_NUM - 1].executed == 0,
                     "cooperative thread is preempted");

        /* Abort threads created */
        abort_threads(THREADS_NUM);
        cleanup_resources();
}
```

**Comment by andrewboie** [comment]
> but the main thread just busy loop to wait other core's thread to run and never gives up CPU before checking test result,

@wentongwu but isn't "giving up the CPU" fundamentally an OS abstraction? I would expect the CPU emulator to emulate instructions on each CPU round-robin, regardless of what the OS is doing.

In other words, it doesn't make sense to me that if we call `k_busy_wait()` on CPU 0, that nothing happens on CPU 1 the entire time. That seems like broken behavior. Is that really what's happening? We might want to talk to the QEMU devs, Peter has been very responsive and helpful in the past.

**Comment by andrewboie** [comment]
I didn't see a bug open on this so I opened https://github.com/zephyrproject-rtos/zephyr/issues/26868
This is a merged PR, let's conduct further discussion there.

**Pull request merged**
