### PR TITLE
fb: cfb: Fix CFB_FONT_MSB_FIRST font rendering

### PR DESCRIPTION
**Pull request by soburi**
I broke the rendering of the `CFB_FONT_MSB_FIRST` font in
the previously committed https://github.com/zephyrproject-rtos/zephyr/pull/53796.

Use this option together with font data that has reversed bit order.
Font data with the bit order reversed can be created with `scripts/build/gen_cfb_font_header.py`.
By using this, you can reduce the amount of calculation when drawing to displays with different bit orders.

The default font does not specify this option, so it is actualized not usual.

I will correct the entire font rendering process to make it
easier to remove the restriction that the vertical size of
the font must be a multiple of 8.

I added tests for the CFB to ensure the fix.
However, since there is no display in the CI environment, I set it to build_only.

This time, I introduced a test that uses the native simulator's SDL to check the display contents on the screen. I am creating comparison data by converting image data into C language binary. I would be happy to receive your opinion on this matter.

### CODE REVIEW

**Review by danieldegrasse — APPROVED** [review]
Not an expert on CFB, but seems to restore the behavior of `samples/subsys/display/cfb` observed in Zephyr 3.4.0 (before the merge of #53796) on the reel board I have

**Comment by soburi** [comment]
@danieldegrasse 
Thank you for reproducing check!

**Comment by danieldegrasse** [comment]
@jfischer-no ping to take a look when you get a chance :-)

**Comment by danieldegrasse** [comment]
@jfischer-no ping to take a look at this, so we can merge during 3.7 window

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
