### PR TITLE
Improve the memory utilization on ESP32-S3

### PR DESCRIPTION
**Pull request by marekmatej**
This fixes the MCUboot linkage issues and improves the memory utilization of the ESP32-S3 for multiple build scenarios.

### CODE REVIEW

**Comment by marekmatej** [comment]
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/73400

**Comment by marekmatej** [comment]
Depends on https://github.com/zephyrproject-rtos/zephyr/pull/73429

**Comment by sylvioalves** [comment]
Please rebase.

**Review by sylvioalves — APPROVED** [review]

**Comment by sylvioalves** [comment]
@LucasTambor PTAL.

**Review by LucasTambor — APPROVED** [review]

**Pull request merged**
