### PR TITLE
ethernet: stm32h7: Move DMA buffers from sram3 to sram2

### LINKED ISSUE #29915: eth: stm32h747i_disco: sem timeout and hang on debug build
**Describe the bug**
When building the dumb http server with `CONFIG_DEBUG` enabled, for the stm32h747i_disco_m7 board, we very fast get a semaphore timeout on waiting for transmission complete callback from ST HAL layer. We can see
```
[00:00:02.719,000] <err> eth_stm32_hal: HAL_ETH_TransmitIT tx_int_sem take timeout
[00:00:02.719,000] <err> eth_stm32_hal: eth packet timeout
98 fa 9b 39 67 d7 02 80  e1 67 51 79 08 00 45 00 |...9g... .gQy..E.
00 28 00 00 00 00 40 06  64 a8 a9 fe 61 15 a9 fe |.(....@. d...a...
61 16 1f 90 ed 02 04 81  fc b9 99 ef e4 5e 50 10 |a....... .....^P.
05 00 08 90 00 00                                |......           
```
Often it hangs and doesn't recover. Build without `CONFIG_DEBUG` and it works flawless. Increasing semaphore timeout time doesn't do any difference.
**What have you tried to diagnose or workaround this issue?**
With instruction cache disabled, it works flawlessly with `CONFIG_DEBUG` enabled. I managed to track it down to 
`modules/hal/stm32/stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_eth.c: 2979`. If we enable instruction cache before this line, timeout. If we enable it after, it works. If we insert a data barrier after, it works:
```
/* Mark it as LAST descriptor */
SET_BIT(dmatxdesc->DESC3, ETH_DMATXNDESCRF_LD);
__DSB();
```
I guess this is a fix, but really not that nice to be messing around in ST's HAL, and I'm also wondering if this fix actually fixes a problem we are causing in the driver. We might be doing something wrong in our stm32h7 driver? Comparing with ST samples for STM32H743 it looks correct.  I didn't find anybody else having this issue with ST's HAL on stm32h747i MCU.
I've seen some people from ST contributing here, maybe somebody can take a look at this?
Messing with buffer alignments doesn't have any effect either; I tried alignment 256 bytes, with confirmation it was aligned.
Please note that this issue was seen when making this driver as well (https://github.com/zephyrproject-rtos/zephyr/pull/27188#discussion_r475380472)

**To Reproduce**
1. add to `/boards/arm/stm32h747i_disco/stm32h747i_disco.dtsi`
```
&mac {
	status="okay";
	pinctrl-0 = <&eth_tx_en_pg11 &eth_txd1_pg12
				 &eth_txd0_pg13 &eth_mdc_pc1
				 &eth_mdio_pa2 &eth_ref_clk_pa1
				 &eth_crs_dv_pa7 &eth_rxd0_pc4
				 &eth_rxd1_pc5>;
};
```
2. add to `samples/net/sockets/dumb_http_server/prj.conf`
```
CONFIG_NET_L2_ETHERNET=y
CONFIG_ETH_STM32_HAL=y
CONFIG_DEBUG=y
```
3. `west build -b stm32h747i_disco_m7 zephyr/samples/net/sockets/dumb_http_server/`
4. west flash
5. Open COM port and do repeated http requests to devkit over ethernet, for example `ab -n 100 -c 1 http://192.0.2.1:8080/`
6. The error will be printed in the terminal instantly, and it will hang subsequent transmissions

**Expected behavior**
Ethernet tx complete semaphore should not timeout. Temporary fix proves this is possible.

**Impact**
Showstopper if it hangs, which it appears to do. We realize it only happens when building for debug, but it's not sustainable to not be able to debug properly. *Something's wrong* 

**Logs and console output**
Please note I am using different IP's than example.
```
*** Booting Zephyr OS build zephyr-v2.4.0-1314-gc3ac3027a17a  ***
[00:00:00.006,000] <inf> net_config: Initializing network
[00:00:00.006,000] <inf> net_config: Waiting interface 1 (0x24004ae4) to be up...
Single-threaded dumb HTTP server waits for a connection on port 8080...
[00:00:02.000,000] <inf> net_config: Interface 1 (0x24004ae4) coming up
[00:00:02.000,000] <inf> net_config: IPv4 address: 169.254.97.21
[00:00:02.991,000] <err> eth_stm32_hal: HAL_ETH_TransmitIT tx_int_sem take timeout
[00:00:02.991,000] <err> eth_stm32_hal: eth packet timeout
98 fa 9b 39 67 d7 02 80  e1 97 e2 22 08 06 00 01 |...9g... ..."....
08 00 06 04 00 02 02 80  e1 97 e2 22 a9 fe 61 15 |........ ..."..a.
98 fa 9b 39 67 d7 a9 fe  61 16                   |...9g... a.      
Connection #0 from 169.254.97.22
Connection from 169.254.97.22 closed
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: c3ac3027a17a89fd30863db818ab320e5bf8b14e (v2.4.99)

**Additional context**
Ethernet cable connected straight to computer

### PR DESCRIPTION
**Pull request by zagor**
PR #30403 implemented nocache regions for ethernet DMA buffers in sram3 to fix issue #29915. Unfortunately, chip variants STM32H742xx do not have any sram3, so they still suffer from #29915.

All H7 variants have sram2 though, so lets use that instead.

(Additionally, I removed the ifdef `DT_NODE_HAS_STATUS(DT_NODELABEL(sramX), okay)` because it hid the problem. The H7 ethernet driver requires nocache dma buffers, we should not let the build succeed without them.)

Fixes #29915

### CODE REVIEW

**Comment by rlezuo1** [comment]
Have tried to cherry-pick this one on top of 4256cd41df6c60f1832fd2deb14edc30ac7debab (v3.2.0), resulted in crash and reboot during early zephyr init. 
Cherry-picking this one: https://github.com/zephyrproject-rtos/zephyr/pull/29944/commits/8ed12aecb9a2311e183b833e563601f527a1590c though made my Ethernet very stable (3.838.506 flood pings, 1 lost).

This is on a H735ig (has no sram3).

**Comment by zagor** [comment]
@rlezuo1 That's odd. I'd like to know more about what goes wrong. Is your build using sram2 for anything else?

As I understand the issue, the https://github.com/zephyrproject-rtos/zephyr/commit/8ed12aecb9a2311e183b833e563601f527a1590c patch works by force-flushing the AXI SRAM (D1 domain), where your dma buffers are currently positioned. Moving the buffers to an AHB SRAM area (D2 domain) removes the need for flushing. This is the solution ST recommends, and it is already merged into Zephyr. Now we just need to make it work for targets that lack sram3.

**Comment by rlezuo1** [comment]
@zagor sram2 is not in use, the bootloader leaves some bytes in sram4 though. dma_tx_buffer_ends up @ 0x24000000. Perhaps this change depends on some other commits which have been merged after v3.2.0 ? It applied cleanly and looked plausible though.

**Comment by zagor** [comment]
> dma_tx_buffer_ends up @ 0x24000000.

Wait a minute. 0x24000000 is the AXI SRAM, SRAM2 is located at 0x30004000.
Your map file should have a section looking like this:

```
eth_stm32       0x0000000030020000     0x4000
                0x0000000030020000                . = ABSOLUTE (0x30020000)
 *(SORT_BY_ALIGNMENT(.eth_stm32_desc))
 .eth_stm32_desc
                0x0000000030020000       0xc0 zephyr/drivers/ethernet/libdrivers__ethernet.a(eth_stm32_hal.c.obj)
                0x0000000030020100                . = (ABSOLUTE (0x30020000) + 0x100)
 *fill*         0x00000000300200c0       0x40 
 *(SORT_BY_ALIGNMENT(.eth_stm32_buf))
 .eth_stm32_buf
                0x0000000030020100     0x2fc0 zephyr/drivers/ethernet/libdrivers__ethernet.a(eth_stm32_hal.c.obj)
                0x0000000030024000                . = (ABSOLUTE (0x30020000) + 0x4000)
 *fill*         0x00000000300230c0      0xf40 
```

**Comment by rlezuo1** [comment]
You've pushed me the right direction with that address comment, I've found the reason it does not work, you'll like that one, there is a very subtle difference in sram2 addresses across h7 product lines it seems, screenshot from h723/733, h725/735, h730 RM:

image


```
---
 dts/arm/st/h7/stm32h723.dtsi | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/dts/arm/st/h7/stm32h723.dtsi b/dts/arm/st/h7/stm32h723.dtsi
index 0291c66163..6f56053c63 100644
--- a/dts/arm/st/h7/stm32h723.dtsi
+++ b/dts/arm/st/h7/stm32h723.dtsi
@@ -93,8 +93,8 @@
 	};
 
 	/* D2 domain, AHB SRAM */
-	sram2: memory@30040000 {
-		reg = <0x30040000 DT_SIZE_K(16)>;
+	sram2: memory@30004000 {
+		reg = <0x30004000 DT_SIZE_K(16)>;
 		compatible = "zephyr,memory-region", "mmio-sram";
 		zephyr,memory-region = "SRAM2";
 	};
-- 
```
with above patch applied sram2 DMA buffers work as expected

**Comment by zagor** [comment]
> -	sram2: memory@30040000 {
> -		reg = <0x30040000 DT_SIZE_K(16)>;
> +	sram2: memory@30004000 {
> +		reg = <0x30004000 DT_SIZE_K(16)>;

Ouch, that's pretty severe and needs a separate PR. Do you want to do it @rlezuo1 or shall I?

**Comment by rlezuo1** [comment]
@zagor: have done: https://github.com/zephyrproject-rtos/zephyr/pull/54593

**Comment by zagor** [comment]
@erwango Do we really want to delay this fix to 3.4.0?

Ethernet is broken (i.e exhibits #29915) for at least STM32H723, 725, 733, 735 and 742.

I know 3.3 is frozen, but this feels pretty serious to me.

**Comment by erwango** [comment]
> lemented nocache regions for ethernet DMA buffers in sram3 to fix issue #29915. Unfortunately, chip variants STM32H742xx do not have any sram3, so they still suffer from #29915.
> 
> All H7 variants have sram2 though, so lets use that instead.
> 
> (Additionally, I removed the ifdef `DT_NODE_HAS_STATUS(DT_NODELABEL(sramX), okay)` because it hid the problem. The H7 ethernet driver requires nocache dma buffers, we should not let the build succeed without them.)

Actually we've done rather intensive testing on STM32 ethernet recently. We didn't notified specific issue, at least the one you mention. 
Do I understand correctly that issues requires `CONFIG_DEBUG=y` ?

**Comment by rlezuo1** [comment]
@erwango No it does not require DEBUG_CONFIG=y,

bug triggers when:

CONFIG_ETH_STM32_HAL_USE_DTCM_FOR_DMA_BUFFER=n
CONFIG_SOC_SERIES_STM32H7X=y

results in crash before main starts

**Comment by zagor** [comment]
To clarify, the bug that this PR is about is #29915. It manifests as `eth_stm32_hal: HAL_ETH_TransmitIT tx_int_sem take timeout` and `eth_stm32_hal: eth packet timeout`. This bug was fixed for the larger STM32H7 variants in PR #30403.

Unfortunately, the #30403 fix assumes the existence of sram3. If sram3 does not exist, it silently reverts to putting ethernet DMA buffers in AXI SRAM, which is what causes bug #29915.

**Review by erwango — CHANGES_REQUESTED** [review]
I had a look to sram2 definition on other H7 devices and I'm not 100% confident they are correctly done (for instance stm32h7a3 defines AXI SRAM Address, some sram2 regions declare 384K) and that change is 100% harmless on existing configurations: what is the impact on users already using sram2 in cacheable configuration?

I agree this is a required change but given we're a bit late in the party to merge risky change, can you re-arrange this PR in order not to impact SoC that currently use SRAM3 ?

In next DV we'll take time to revisit this, review existing SRAM descriptions, ensure this is harmless on existing configuration or notify users otherwise.

**Review by erwango — DISMISSED** [review]
Thanks for the quick change.
This is fine for me.

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
