### PR TITLE
doc: Add INFINEON Prefix to ifx supported boards

### PR DESCRIPTION
**Pull request by praveenCY**
Add INFINEON Prefix to boards supported by IFX so that documentation shows "INFINEON" properly

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Any reason this is all caps?

**Comment by praveenCY** [comment]
> Any reason this is all caps?
@galak  : Just following how other vendors (like ESP, NXP) are defining in https://docs.zephyrproject.org/latest/boards/index.html

**Comment by ifyall** [comment]
> > Any reason this is all caps?
> > @galak  : Just following how other vendors (like ESP, NXP) are defining in https://docs.zephyrproject.org/latest/boards/index.html

And this capitalization is aligned with our Marketing team's desires.

**Review by ifyall — APPROVED** [review]

**Comment by galak** [comment]
> And this capitalization is aligned with our Marketing team's desires.

Just be aware there are some places that all caps is not accepted (main one I can think of is devicetree).

**Review by galak — APPROVED** [review]

**Pull request merged**
