### PR TITLE
treewide: Replace all uses of CONCAT with _CONCAT

### PR DESCRIPTION
**Pull request by aescolar**
One of the ARM architure files, defined since long ago CONCAT having the exact same purpose as Zephyr's _CONCAT. Unfortunately this header is included almost always and the macro defined in all ARM based platforms,
which seems to have lead to many uses of this macro instead of _CONCAT.

Fix it by using _CONCAT instead, so that code works also with other architectures.

-----

Related to:
- https://github.com/zephyrproject-rtos/zephyr/issues/64841

### CODE REVIEW

**Review by manuargue — APPROVED** [review]

**Review by gmarull — CHANGES_REQUESTED** [review]
sounds like a workaround, fixing the problem in the wrong place. fix should go to whoever is polluting the namespace

**Comment by aescolar** [comment]
> sounds like a workaround, fixing the problem in the wrong place. fix should go to whoever is polluting the namespace

@gmarull This is the fix of the users who should not use that macro. The next step would be to remove the line which provides the CONCAT macro. But that needs to be done after, and probably more carefully as there is going to be off-tree users.

**Review by nordicjm — APPROVED** [review]

**Review by gmarull — APPROVED** [review]
+1, provided a new PR will be sent to remove `CONCAT` from arch header files (they should not define such macros but use Zephyr ones)

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> +1, provided a new PR will be sent to remove `CONCAT` from arch header files (they should not define such macros but use Zephyr ones)

@aescolar will you post this PR?

**Comment by aescolar** [comment]
> > +1, provided a new PR will be sent to remove `CONCAT` from arch header files (they should not define such macros but use Zephyr ones)
> 
> @aescolar will you post this PR?

yep

**Pull request merged**
