### PR TITLE
Silicon Labs BRD4161A board support added

### PR DESCRIPTION
**Pull request by spatil2447**
Added support for a new silicon labs board ( BRD4161A).

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi, thanks for the PR!

Please split your changes into meaningful chunks (e.g. let's keep SoC changes in a separate commit from board changes). Additionally, some CI checks are reported as failed, you can see more details here: https://github.com/zephyrproject-rtos/zephyr/actions/runs/7637616954/job/20812617950?pr=68041.

**Comment by spatil2447** [comment]
@fkokosinski @tgorochowik 

Please review and approve PR .
All the test cases are passing.

**Comment by fkokosinski** [comment]
@spatil2447 thanks! Looks much better now. One last nit would be to reorder those commit, so that SoC changes are before board changes. In our case in this PR, we could do the following:
1. SoC commit
2. Devicetree commit
3. Board commit

**Review by fkokosinski — APPROVED** [review]
LGTM

**Comment by spatil2447** [comment]
@tgorochowik 

Waiting for your approval, Please review!

**Review by tgorochowik — APPROVED** [review]

**Comment by tgorochowik** [comment]
Looks good, thanks

**Pull request merged**
