### PR TITLE
boards: stm32l5: add usb_fs definition to devicetree

### PR DESCRIPTION
**Pull request by f3dora19**
Add USB_FS device definition to devicetree of all STM32L5 SoC family

Signed-off-by: Luc Viala <luc.viala19@gmail.com>

### CODE REVIEW

**Review by FRASTM — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for this change. 
Though, I haven't been able to run USB sample on L5 DK board with this.
Am I missing something (related to Type-C connector maybe ) ?

If there's any additional tweak to be done to the board to use it ?
If yes, some additional comments would be nice

**Comment by lucviala** [comment]
> Thanks for this change.
> Though, I haven't been able to run USB sample on L5 DK board with this.
> Am I missing something (related to Type-C connector maybe ) ?
> 
> If there's any additional tweak to be done to the board to use it ?
> If yes, some additional comments would be nice

Hi @erwango ,

Yes you've right, the sample seems not running with only the commit I made.

I was too confident, I enabled the USB CDC within my own project without anything else USB related configured than in the sample `prj.conf`, except that I got a callback handler on `usb_enable` function which makes nothing else than print the USB event, and this is running on my stm32l562e_dk board.

I have to check what is wrong with my work.

**Comment by lucviala** [comment]
Hi @erwango, 
I tried adding and removing some configurations on the project I work on and I finally found what is different, simply add this in `prj.conf` and it will work:

> CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y

I get the sample code working and get `/dev/ttyACM1` device on my PC:

```
[ 2825.077931] usb 3-1: new full-speed USB device number 53 using xhci_hcd
[ 2825.227136] usb 3-1: New USB device found, idVendor=2fe3, idProduct=0001, bcdDevice= 2.06
[ 2825.227144] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2825.227149] usb 3-1: Product: Zephyr CDC ACM sample
[ 2825.227152] usb 3-1: Manufacturer: ZEPHYR
[ 2825.227155] usb 3-1: SerialNumber: xxxxxxxxxxxxx
[ 2825.228053] cdc_acm 3-1:1.0: ttyACM1: USB ACM device
```

If you find an explanation, I'll be happy to hear it.

**Comment by erwango** [comment]
> If you find an explanation, I'll be happy to hear it.

I'll be happy as well :-) @jfischer-no maybe ?
So, I got this working on cdc_acm sample, but other samples such as console doesn't.
Does it work on your end ?

**Comment by lucviala** [comment]
> Does it work on your end ?

The console sample is working for me ONLY if I add this unrelated configuration on `prj.conf`

```
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
```

I tried on an stm32f746g_disco, it works correctly if I remove above confguration which seems normal behavior.

**Comment by erwango** [comment]
> ENTROPY_GENERATOR

This is likely due to the fact STM32 entropy driver is enabling HSI48 clock.
Can you do the same for L5 in USB driver ? (already done for some series)

**Comment by lucviala** [comment]
> This is likely due to the fact STM32 entropy driver is enabling HSI48 clock.
> Can you do the same for L5 in USB driver ? (already done for some series)

Hi @erwango, seems you've right, I made the changes.
Thanks for your help

**Review by MaureenHelm — APPROVED** [review]
@erwango please revisit

**Review by erwango — APPROVED** [review]

**Pull request merged**
