### PR TITLE
WIP usb: stm32: implement usb_detach

### PR DESCRIPTION
**Pull request by jli157**
disable STM32's usb irq and clock.

Trying to fix the issue #16023 
Signed-off-by: Jun Li <jun.r.li@intel.com>

### CODE REVIEW

**Comment by jli157** [comment]
@ydamigos I'm trying to use this PR to fix a blocking issue #16023. My original implementation was also calling the function `HAL_PCD_DeInit()` to de-initialize USB device. However, that function gets stuck somewhere.

**Comment by jli157** [comment]
Tried just adding `HAL_PCD_DevDisconnect(&usb_dc_stm32_state.pcd)`, still got stuck. :-(

**Comment by ydamigos** [comment]
@jli157 I'll try to have a look this weekend.

**Comment by jli157** [comment]
@ydamigos any further comments?

**Comment by ydamigos** [comment]
@jli157 I took a look at it during last weekend. It is clear that we should call `HAL_PCD_DeInit()` in `usb_dc_detach()`, but I failed to get it work. Moreover, I tried to run `tests/subsys/usb/device/` on my stm32f3_disco and it crashes. I'll try to find sometime and debug it.

**Comment by erwango** [comment]
@jli157 , any plan for this work?

**Comment by jli157** [comment]
> @jli157 , any plan for this work?

I've made some workaround to make sure my project can go ahead without being blocked by this one but you know it is still a workaround. I'm hoping to have @ydamigos 's help. Hopefully he can find some time to take a look at this one again.

**Comment by erwango** [comment]
@jli157, @ydamigos is this PR still valid?

**Comment by erwango** [comment]
@jli157 do you plan to continue this PR ?

**Comment by jli157** [comment]
It is just workaround:) I’m not sure if the current code base has already done this one.   I’m expecting some USB experts like you to take care of the issue. 

This can be closed.

**Comment by jli157** [comment]
@erwango Feel free to close this PR if #22827 addresses the same goal.

**Comment by erwango** [comment]
> @erwango Feel free to close this PR if #22827 addresses the same goal.

Txs, closing, let's focus on #22827

**Pull request closed without merging**
