### PR TITLE
drivers: wdt: esp32: code refactor to use hal calls

### PR DESCRIPTION
**Pull request by sylvioalves**
Update WDT driver to use hal calls, which
brings proper unification among socs.

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>

### CODE REVIEW

**Comment by sylvioalves** [comment]
Somehow this PR was left behind. @glaubermaroto @uLipe PTAL.

**Review by glaubermaroto — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Comment by sylvioalves** [comment]
Rebased again.

**Comment by sylvioalves** [comment]
@cfriedt @nashif Can we merge this already?

**Comment by sylvioalves** [comment]
> > @cfriedt @nashif Can we merge this already?
> 
> We are still here in feature freeze for v3.0.0. Shouldn't take long now.

@henrikbrixandersen sure, thanks!

**Pull request merged**
