### PR TITLE
tests/drivers pwm_clock: Build fix sam_v71_xult

### PR DESCRIPTION
**Pull request by aescolar**
Fix build error due to cmake requiring a separate
overlay for each of this target's SOCs.

Error being fixed:
```
-- Board: sam_v71_xult, qualifiers: samv71q21
CMake Error at cmake/modules/extensions.cmake:2742 (message):
  Board sam_v71_xult defines multiple SoCs.

  Shortened file name (sam_v71_xult.overlay) not allowed, use
  '<board>_<soc>.overlay' naming
```

The error was detected by CI

### CODE REVIEW

**Comment by pdgendt** [comment]
Should the same be applied to `samples/drivers/adc/adc_sequence/boards/sam_v71_xult.overlay`?

**Review by nordicjm — DISMISSED** [review]

**Comment by aescolar** [comment]
> Should the same be applied to samples/drivers/adc/adc_sequence/boards/sam_v71_xult.overlay? 

I guess :)  I will update this PR
(that target is not enabled for that test)

**Review by nordicjm — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Review by nordic-segl — APPROVED** [review]

**Comment by nandojve** [comment]
Hi @aescolar ,

Two questions:

1- Why only now this is showing up on CI?
2- Why this is assign to @nordic-krch and not to a contributor or maintainer from the specific platform?

**Comment by aescolar** [comment]
> 1- Why only now this is showing up on CI?

With all likelihood it has been failing since the transition to hwmv2. But the issues was likely lost in between many others. During the last few weeks we have been fixing issues detected by the weekly CI job, but had started from the worse cases, and now we are down to just a few failures.

>  Why this is assign to @nordic-krch and not to a contributor or maintainer from the specific platform?

The bot/script assigns based on the maintainers file. As here we are changing tests/samples, the script picked based on the area the tests are. For this case indeed assigning to the platform maintainer would be better. I just did not take the time to check for a better assignee as the fix seemed quite simple.
You are very welcome to add a new pattern to the maintainers file so overlays for this boards in samples and tests will also be detected as being part of that area.

**Review by nandojve — APPROVED** [review]

**Pull request merged**
