### PR TITLE
cmake: kconfig: Allow user to add custom menuconfig impl.

### PR DESCRIPTION
**Pull request by SebastianBoe**
Out-of-tree Kconfig frontends need to know which environment variables
are exported by Zephyr to Kconfig.

To support this we allow additional Kconfig python frontend targets to
be specified from out-of-tree.

This support was added on request by a third-party with a custom
Kconfig frontend.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by ulfalizer** [comment]
Did someone request this?

**Comment by SebastianBoe** [comment]
Yes.

**Comment by SebastianBoe** [comment]
recheck

**Comment by SebastianBoe** [comment]
There are some issues with this approach that I need to rework.

**Comment by SebastianBoe** [comment]
This is now ready for review.

**Comment by SebastianBoe** [comment]
@ulfalizer : Would appreciate a review here.

The use-case is integration of third-party Kconfig frontends.

**Comment by SebastianBoe** [comment]
@nashif : Review is needed.

**Review by ulfalizer — APPROVED** [review]
Sorry, forgot about this one.

**Review by carlescufi — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Pull request merged**
