### PR TITLE
stm32 QSPI flash driver enables XiP on external NOR flash

### PR DESCRIPTION
**Pull request by FRASTM**
With this PR the stm32l496 and stm32h750 target board with quad-NOR flash can configure this external flash to eXecute In Place a sample code application stored on this external memory.
The qspi flash driver is configuring the external NOR in MemoryMapped mode at init so that code is XiP at the external NOR flash address.
This is demonstrated by the samples/application_development/code_relocation_nocopy/ running on the stm32h750b or stm32l496 disco kits.

This PR completes the https://github.com/zephyrproject-rtos/zephyr/pull/68597

### CODE REVIEW

**Comment by FRASTM** [comment]
Running the sample to relocate code on the external NOR flash of the stm32h750b_dk disco kit (also valid with stm32l496g_disco) :
`west build -p always -b stm32h750b_dk samples/application_development/code_relocation_nocopy/`
gives
```
*** Booting Zephyr OS build zephyr-v3.5.0-5287-g8635e7efae61 ***
Address of main function 0x800066d
Address of function_in_ext_flash 0x90000001
Address of var_ext_sram_data 0x240000e0 (10)
Address of function_in_sram 0x24000001
Address of var_sram_data 0x240000e4 (10)
Hello World! stm32h750b_dk
```

TODO : fix ***** USAGE FAULT *****  after cold reset on the stm32h750b_dk disco kit

**Comment by FRASTM** [comment]
adding the support of the stm32l496 disco kit with single quad-flash : 
```
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash@90000000: SFDP v 1.6 AP ff with 3 PH
[00:00:00.000,000] <inf> flash_stm32_qspi: PH0: ff00 rev 1.6: 16 DW @ 30
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash@90000000: 8 MiBy flash
[00:00:00.000,000] <inf> flash_stm32_qspi: Quad read mode 4 instr [0x6b] supported
[00:00:00.000,000] <inf> flash_stm32_qspi: Quad read mode 7 instr [0xeb] supported
[00:00:00.000,000] <inf> flash_stm32_qspi: Quad read mode 7 instr [0xeb] will be used
[00:00:00.000,000] <inf> flash_stm32_qspi: QE requirement mode: 2
[00:00:00.000,000] <inf> flash_stm32_qspi: Quad mode enabled
[00:00:00.000,000] <inf> flash_stm32_qspi: PH1: ffc2 rev 1.0: 4 DW @ 110
*** Booting Zephyr OS build zephyr-v3.5.0-5288-g918bf5d05858 ***
Address of main function 0x8000589
Address of function_in_ext_flash 0x90000001
Address of var_ext_sram_data 0x200000e0 (10)
Address of function_in_sram 0x20000001
Address of var_sram_data 0x200000e4 (10)
Hello World! stm32l496g_disco
```

**Comment by luispimo** [comment]
I would like to use it on a stm32f7508_dk since the internal flash is very small, but I get a MPU_FAULT at boot:

```
*** Booting Zephyr OS build v3.6.0-1933-gdf51b82cc598 ***
Address of main function 0x800059d
[00:00:00.000,000] <err> os: ***** MPU FAULT *****
[00:00:00.000,000] <err> os:   Instruction Access Violation
[00:00:00.000,000] <err> os: r0/a1:  0x00000007  r1/a2:  0x00000000  r2/a3:  0x00000008
[00:00:00.000,000] <err> os: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x080005b1
[00:00:00.000,000] <err> os:  xpsr:  0x61000000
[00:00:00.000,000] <err> os: Faulting instruction address (r15/pc): 0x90000000                                                         
[00:00:00.000,000] <err> os: >>> ZEPHYR FATAL ERROR 20: Unknown error on CPU 0                                                         
[00:00:00.000,000] <err> os: Current thread: 0x200107e8 (unknown)                                                                      
[00:00:00.107,000] <err> os: Halting system    
```

Is it possible? Am I doing something wrong?

**Comment by FRASTM** [comment]
flash_stm32_qspi driver  supporting the dual flash mode with 2 identical quad-NOR mounted 
testing on the stm32h750b_dk  disco kit: `west build  -p auto -b stm32h750b_dk samples/application_development/code_relocation_nocopy/`
When the quad flash are in MEMMAP mode, 
```
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP                                                                            
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash-1@90000000: 64 MiBy flash                                                                                                      
...                                                                                                                  
[00:00:00.000,000] <inf> flash_stm32_qspi: Quad mode enabled  
...                                                                                         
[00:00:00.000,000] <dbg> flash_stm32_qspi: flash_stm32_qspi_init: Dual Flash Mode                                                  
[00:00:00.000,000] <dbg> flash_stm32_qspi: flash_stm32_qspi_init: NOR quad-flash in MemoryMapped mode at 0x90000000 (0x4000000 byt)
*** Booting Zephyr OS build v3.6.0-1946-g66d42c0c889f ***                                                                          
Address of main function 0x800066d                                                                                                 
Address of function_in_ext_flash 0x90000001                                                                                        
Address of var_ext_sram_data 0x240000e0 (10)                                                                                       
Address of function_in_sram 0x24000001                                                                                             
Address of var_sram_data 0x240000e4 (10)                                                                                           
Hello World! stm32h750b_dk 
```

**Comment by FRASTM** [comment]
with the stm32h747 disco, the samples/application_development/code_relocation_nocopy is correctly flashed and executed until an ARM bl instruction to a address in a blank page !?
Screenshot from 2024-04-19 14-38-37

**Comment by FRASTM** [comment]
> I would like to use it on a stm32f7508_dk since the internal flash is very small, but I get a MPU_FAULT at boot:
> 
> ```
> *** Booting Zephyr OS build v3.6.0-1933-gdf51b82cc598 ***
> Address of main function 0x800059d
> [00:00:00.000,000] <err> os: ***** MPU FAULT *****
> [00:00:00.000,000] <err> os:   Instruction Access Violation
> [00:00:00.000,000] <err> os: r0/a1:  0x00000007  r1/a2:  0x00000000  r2/a3:  0x00000008
> [00:00:00.000,000] <err> os: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x080005b1
> [00:00:00.000,000] <err> os:  xpsr:  0x61000000
> [00:00:00.000,000] <err> os: Faulting instruction address (r15/pc): 0x90000000                                                         
> [00:00:00.000,000] <err> os: >>> ZEPHYR FATAL ERROR 20: Unknown error on CPU 0                                                         
> [00:00:00.000,000] <err> os: Current thread: 0x200107e8 (unknown)                                                                      
> [00:00:00.107,000] <err> os: Halting system    
> ```
> 
> Is it possible? Am I doing something wrong?

Well, I have checked with a **stm32f746g_disco**, the flash_stm32_qspi  driver and the qspi_set_memorymap function requires 10 dummy cylce for the this quad-NOR 
Then this board has a single-quad flash, -->  I set the `flash-id = <1>;` in the board DTS  &quadspi  NODE
Plus I set the `ATTR_MPU_IO`  to the quadspi_memory region to have code executed in XiP

**Comment by FRASTM** [comment]
new quad-spi driver supporting dual  or single quad-flash
Tested on stm32l496g_disco --> single quad-flash
Tested on stm32f746g_disco --> single quad-flash
Tested on stm32h750i_disco --> dual quad-flash

**Comment by FRASTM** [comment]
This PR is similar to https://github.com/zephyrproject-rtos/zephyr/pull/72339

**Pull request closed without merging**
