### PR TITLE
drivers: i2c_dw: Remove CMake-based templating

### PR DESCRIPTION
**Pull request by jhedberg**
With the help of some additional macro-magic it's possible to remove the CMake-based per-instance templating, and instead take advantage of the usual `DT_INST_FOREACH_STATUS_OKAY()` macro.

### CODE REVIEW

**Comment by jhedberg** [comment]
FWIW, the ns16550 UART driver should also be possible to convert using the same mechanism. It's a bit more demanding though with lots of build-time conditional configuration struct members. I'll start looking at that next.

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]
Fancy :)

**Comment by galak** [comment]
@jhedberg rebase on master now that https://github.com/zephyrproject-rtos/zephyr/commit/9693fc8fee68ea66de470f5fe7f70adbe56e6000 is merged

**Comment by jhedberg** [comment]
> @jhedberg rebase on master now that 9693fc8 is merged

@galak done, thanks for the heads-up

**Pull request merged**
