### PR TITLE
Using `ZBUS_CHAN_DEFINE` with enabled `CONFIG_CPP` cause compilation error

### PR DESCRIPTION
**Pull request by mi-mdziebowski**
There appear error: `zephyr/zbus/zbus.h:352:9: error: designator order for field 'zbus_channel_data::highest_observer_priority' does not match declaration order in `zbus_channel_data`.

Solution: change order in `ZBUS_CHAN_DEFINE` macro according to zbus_channel_data structure.

### CODE REVIEW

**Review by rodrigopex — APPROVED** [review]
Thanks for your contribution. I need to be more vigilant about CPP compatibility. I usually focus on testing that just for C. Maybe Adding some CPP test variant will prevent this kind of issue in the future.

**Comment by anedergaard** [comment]
I have had the same issue, and proposal for a fix including an addition to `tests/lib/cpp/cxx/src/main.cpp` for validation with twister.
What is the recommended procedure, should I create a PR with these changes and link to this PR?

**Comment by rodrigopex** [comment]
@anedergaard 

> I have had the same issue, and a proposal for a fix including an addition to `tests/lib/cpp/cxx/src/main.cpp` for validation with twister. What is the recommended procedure, should I create a PR with these changes and link to this PR?

I am on the way to add a CPP sample to ZBus. I will try to exercise all the zbus features on the same sample to make that a good CPP compatibility test. If you'd like to contribute, we can talk about it.

**Comment by anedergaard** [comment]
> @anedergaard 
> 
> 
> 
> > I have had the same issue, and a proposal for a fix including an addition to `tests/lib/cpp/cxx/src/main.cpp` for validation with twister. What is the recommended procedure, should I create a PR with these changes and link to this PR?
> 
> 
> 
> I am on the way to add a CPP sample to ZBus. I will try to exercise all the zbus features on the same sample to make that a good CPP compatibility test. If you'd like to contribute, we can talk about it. 

Hi @rodrigopex,
Yes I would like to contribute with compatibility test of `ZBUS` in CPP.

**Review by pdgendt — APPROVED** [review]

**Pull request merged**
