### PR TITLE
samples: tfm_integration: Set TF-M profile type to none.

### PR DESCRIPTION
**Pull request by joerchan**
Set the TF-M profile type to none for TF-M integration samples.
If the default profile has been set to something else these samples may
fail.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]

**Comment by microbuilder** [comment]
@theotherjimmy Mind having a look at this to test on the usual slew of boards, and looks like there is an issue with the new FWU sample in CI? Thanks!

**Comment by theotherjimmy** [comment]
Yeah, that compile error is strange. Off the cuff, I don't know what's causing it.

**Review by oyvindronningstad — DISMISSED** [review]

**Comment by joerchan** [comment]
Hmm, my guess would be it is related to this:

`zephyr/boards/arm/lpcxpresso55s69/Kconfig.defconfig`:
```
choice TFM_PROFILE_TYPE
	depends on BUILD_WITH_TFM
	default TFM_PROFILE_TYPE_MEDIUM
endchoice
```

**Comment by microbuilder** [comment]
The CI failures seen here should be addressed in https://github.com/zephyrproject-rtos/zephyr/pull/45858 until a more permanent solution can be found (requiring changes uptream to TF-M first), which will certainly be after the 3.1.0 release.

**Comment by joerchan** [comment]
Rebased now that fix for compilation issue has been merged.

**Review by microbuilder — APPROVED** [review]

**Review by theotherjimmy — APPROVED** [review]

**Pull request merged**
