### PR TITLE
arm64: Add stack guard for v8r

### PR DESCRIPTION
**Pull request by povergoing**
Add stack guard as an implementation of HW_STACK_PROTECTION, needs find a better way to handle

- Depends on the `safe exception stack` (https://github.com/zephyrproject-rtos/zephyr/pull/48297).
- Enable MPU based stack guard
- Tested on `fvp_baser_aemv8r` board with `HW_STACK_PROTECTION` enabled.
```
$ ./zephyr/scripts/twister -p fvp_baser_aemv8r
Renaming output directory to /src/zephyrproject/twister-out.1
INFO    - Using Ninja..
INFO    - Zephyr version: zephyr-v3.3.0-494-ge460f91a379d
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /src/zephyrproject/twister-out/testplan.json
INFO    - JOBS: 8
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete: 2018/2018  178%  skipped: 1663, failed:    0, error:    0
INFO    - 2209 test scenarios (2018 test instances) selected, 1663 configurations skipped (1582 by static filter, 81 at runtime).
INFO    - 355 of 2018 test configurations passed (100.00%), 0 failed, 0 errored, 1663 skipped with 0 warnings in 1318.53 seconds
INFO    - In total 2674 test cases were executed, 6498 skipped on 1 out of total 543 platforms (0.18%)
INFO    - 296 test configurations executed on platforms, 59 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing JSON report /src/zephyrproject/twister-out/twister.json
INFO    - Writing xunit report /src/zephyrproject/twister-out/twister.xml...
INFO    - Writing xunit report /src/zephyrproject/twister-out/twister_report.xml...
INFO    - Run completed

```
- Fix some testcases by increasing the stack guard which the stack guard detects

Limitation:
- SMP **NOT** fully supported for now
- MMU based stack guard does **NOT** support, and might open another PR in the future.

### CODE REVIEW

**Comment by npitre** [comment]
You have:

```
        /* load primary stack and entry point */
-       ldr     x24, =(z_interrupt_stacks + CONFIG_ISR_STACK_SIZE)
+       ldr     x24, =(z_interrupt_stacks + ARCH_KERNEL_STACK_RESERVED + CONFIG_ISR_STACK_SIZE)
```

You could use `__z_interrupt_stack_SIZEOF` here instead. It was
created for that purpose. See commit 1f362a81f172.

**Comment by carlocaione** [comment]
> @carlocaione do you have any clue on this `unexpected eof`? `INFO - 656/656 qemu_cortex_a53_smp samples/subsys/portability/cmsis_rtos_v1/philosophers/sample.portability.cmsis_rtos_v1.philosopher.semaphores FAILED unexpected eof (qemu 0.027s)` https://github.com/zephyrproject-rtos/zephyr/actions/runs/4551908320/jobs/8044448572?pr=55207

Uhm, IIRC this problem could be due to some binary / non-ascii data that is being mis-interpreted by the test framework. Do you have anything like that when running locally?

**Comment by povergoing** [comment]
> Uhm, IIRC this problem could be due to some binary / non-ascii data that is being mis-interpreted by the test framework. Do you have anything like that when running locally?

Yes, I tested on my local. The weird thing is:
When I run `west twister -p qemu_cortex_a53_smp -s samples/subsys/portability/cmsis_rtos_v1/philosophers/sample.portability.cmsis_rtos_v1.philosopher`, it PASS without `unexpected eof`
But if I run `west twister -p qemu_cortex_a53_smp`, this testcase fails with `unexpected eof`

**Comment by povergoing** [comment]
> @povergoing this is failing locally as well for me:
> 
> `west build -b qemu_cortex_a53_smp samples/subsys/portability/cmsis_rtos_v1/philosophers -T sample.portability.cmsis_rtos_v1.philosopher.semaphore`
> 
> and then:
> 
> `west build -t run`

May I see your output? Cause after I run `west build -t run`, I got the following infinite output which is expected I think? I didn't see any of EOF things?
image

**Comment by carlocaione** [comment]
Weird, for me the output is stuck. Are you sure you are trying with `sample.portability.cmsis_rtos_v1.philosopher.semaphore` and not with `sample.portability.cmsis_rtos_v1.philosopher` (note the `semaphore` part).

**Comment by povergoing** [comment]
> Weird, for me the output is stuck. Are you sure you are trying with `sample.portability.cmsis_rtos_v1.philosopher.semaphore` and not with `sample.portability.cmsis_rtos_v1.philosopher` (note the `semaphore` part).

Yes, my cmd: `west build -b qemu_cortex_a53_smp zephyr/samples/subsys/portability/cmsis_rtos_v1/philosophers -T sample.portability.cmsis_rtos_v1.philosopher.semaphores`

**Comment by carlocaione** [comment]
Yeah, there is something strange going on. Sometimes it works, sometimes it doesn't.

Can you try with:
`west build -b qemu_cortex_a53_smp samples/subsys/portability/cmsis_rtos_v1/philosophers -T sample.portability.cmsis_rtos_v1.philosopher.semaphores --pristine` ?

**Comment by povergoing** [comment]
> 

I have the normal output even using `--pristine`. I need to try to upgrade the SDK

**Comment by carlocaione** [comment]
@povergoing any news?

**Comment by povergoing** [comment]
> @povergoing any news?

While I am still looking into the CI issue, bu I found the `main` branch is already broken. When we run `twister`, some of the time-sensitive test cases fail with qemu_cortex_a53_smp (this is already known right?), and further, the assert will be false and call `thread_abort`, but some test cases need some clean up, for example:
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/kernel/sched/schedule_api/src/test_sched_timeslice_and_lock.c#L262
However, the assert happens, then the current thread is aborted, thus the `teardown_thread()` will not run, and the "zombie" thread still lives in `runq`. 
What's more, because of "zombie" thread will be reused many times, the same thread will be re-added into `runq` which will cause an unexpected exception during the next tests and then cause a `psci_down`. At this time, the Qemu will exit, and the twister thinks it's an `unexpected eof`.

Any suggestions? But I am now on vacation and will keep on fixing it when I am back.

**Pull request closed without merging**
