### PR TITLE
drivers: mfd: npm6001: Add timeout to allow for startup delay

### PR DESCRIPTION
**Pull request by bjda**
Adds a timeout to the first operation in the initialization function, to allow for the startup delay of nPM6001 after it is powered and enabled.

### CODE REVIEW

**Review by gmarull — COMMENTED** [review]
looks hackish, I've never found this problem myself, @aasinclair any comments?

**Comment by aasinclair** [comment]
@bjda Could you give some more details of the specific issue you are facing?

**Comment by bjda** [comment]
When using nPM6001 as a secondary PMIC, it will not immediately respond to I2C commands after being powered and enabled by the main PMIC (nPM1300 in our case), so initialization fails.

This PR retries the first operation for a certain time, so that nPM6001 can boot and get the I2C interface ready. Retrying the first operation rather than introducing a fixed delay ensures that we do not delay the rest of the boot process unnecessarily.

**Comment by aasinclair** [comment]
You can add a delay after LDO1 switches like this:
```

**Comment by bjda** [comment]
We will go with that instead, thanks.

**Pull request closed without merging**
