### PR TITLE
Bluetooth: Read static address from FICR on nRF5 if no VS enabled

### PR DESCRIPTION
**Pull request by sjanc**
When running combined build on nRF5 with disabled VS command it is
possible to simply read static random address from FICR in host.

Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]
Not really happy about starting to populate hci_core.c with vendor specific code, but I can't think of a good alternative right now. If it ever looks like we need to extend this to more platforms we should start looking at refactoring this out from hci_core.c to some common libraries or something like that.

**Comment by carlescufi** [comment]
>Not really happy about starting to populate hci_core.c with vendor specific code, but I can't think of a good alternative right now. If it ever looks like we need to extend this to more platforms we should start looking at refactoring this out from hci_core.c to some common libraries or something like that.

Same. I was really happy to get rid of vendor-specific code and move it to commands. But I think practicality must always prevail over aesthetical considerations, and shipping in small devices with limited flash is critical to the project.

**Review by carlescufi — APPROVED** [review]

**Comment by sjanc** [comment]
implemented another approach to this in https://github.com/zephyrproject-rtos/zephyr/pull/9909

**Comment by sjanc** [comment]
I'll close this PR for now to avoid confusion

**Pull request closed without merging**
