### PR TITLE
samples: use K_MSEC with k_sleep()

### PR DESCRIPTION
**Pull request by nashif**
Couple of samples missing the conversion.

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Comment by jhedberg** [comment]
I know this is a hotfix and we want it merged ASAP, but you could have converted these to use `K_SECONDS()` in the same go and thereby make them slightly more intuitive to read.

**Review by galak — COMMENTED** [review]
Should we be using k_msleep here instead?

Also seems like there are more cases:

```
samples/bluetooth/peripheral/src/main.c:		k_sleep(MSEC_PER_SEC);
samples/bluetooth/peripheral_csc/src/main.c:		k_sleep(MSEC_PER_SEC);
samples/bluetooth/peripheral_esp/src/main.c:		k_sleep(MSEC_PER_SEC);
samples/bluetooth/peripheral_hr/src/main.c:		k_sleep(MSEC_PER_SEC);
samples/bluetooth/peripheral_ht/src/main.c:		k_sleep(MSEC_PER_SEC);
subsys/net/lib/openthread/platform/uart.c:	k_sleep(MSEC_PER_SEC * 1);
tests/bluetooth/bsim_bt/bsim_test_app/src/test_connect2.c:		k_sleep(MSEC_PER_SEC);
tests/bluetooth/shell/src/main.c:		k_sleep(MSEC_PER_SEC);
tests/net/ipv6/src/main.c:	k_sleep((lifetime * 2U) * MSEC_PER_SEC);
```

**Comment by jhedberg** [comment]
> Should we be using k_msleep here instead?

@galak those should be fixed, but all of them sleep for a multiple of seconds, so using a millisecond-based API seems a bit odd. I'd use `k_sleep(K_SECONDS(n));` for them.

**Comment by galak** [comment]
not sure if running `scripts/coccinelle/int_literal_to_timeout.cocci` against the tree would find any other cases and fix them (@pabigot ?)

**Comment by jhedberg** [comment]
For the record, I can submit a PR to fix the Bluetooth ones (even the net one as long as @jukkar approves), unless @nashif wants to combine everything into this PR.

**Comment by nashif** [comment]
> Also seems like there are more cases:
> 


are those failing anywhere?

**Comment by nashif** [comment]
> unless @nashif wants to combine everything into this PR.

no, take your time, this PR fixes build issues, I do not see BT samples failing anywhere. (still using legacy)

**Comment by galak** [comment]
> no, take your time, this PR fixes build issues, I do not see BT samples failing anywhere. (still using legacy)

Why aren't the BT samples failing, confused by what's the difference between them and the simple ones?

**Review by galak — APPROVED** [review]

**Comment by pabigot** [comment]
@galak 

    spatch -D patch --sp-file scripts/coccinelle/int_literal_to_timeout.cocci --dir . --very-quiet 

proposes changes to a few things but other than a `k_sem_take` in drivers/wifi/esp/esp_offload.c I don't know that they're necessary.  Wouldn't have changed the calls where the parameter is a macro.

**Comment by ioannisg** [comment]
> > no, take your time, this PR fixes build issues, I do not see BT samples failing anywhere. (still using legacy)
> 
> Why aren't the BT samples failing, confused by what's the difference between them and the simple ones?

BT samples use legacy API, as far as I understood

**Comment by jhedberg** [comment]
> BT samples use legacy API, as far as I understood

@ioannisg @galak looking at `subsys/net/Kconfig` the `NET_BUF` option (which both Networking and Bluetooth use) has a `select LEGACY_TIMEOUT_API`, which explains this. I wasn't aware that such an exception had been made in the Timeout API PR.

**Review by carlescufi — APPROVED** [review]

**Comment by pabigot** [comment]
> @pabigot thanks. Wondering if a new cocci script or updates to the existing scripts could be made as I'm guessing as we transition this API we'll have more cases that need conversion.

Probably.  I'll take a look.

**Pull request merged**
