### PR TITLE
[Backport v3.1-branch] lib: posix: make sleep() and usleep() standards-compliant

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 027b79ecc4f71d36dbd89b9e0fb1dab7d096f0f7~4..027b79ecc4f71d36dbd89b9e0fb1dab7d096f0f7 from #52519

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/51776
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/52517
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/52518

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@cfriedt bug number?

**Comment by cfriedt** [comment]
Yeesh - was this right around when we switched test APIs?

Likely the change from `v2.7-branch` would work in that case.

**Comment by cfriedt** [comment]
* added trailing `, NULL` bit to `zassert_equal` and `zassert_ok`

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by cfriedt** [comment]
Since this is not an LTS release, dropping this PR.

**Pull request closed without merging**
