### PR TITLE
boards: arm: stm32h750b_dk: add support for display

### PR DESCRIPTION
**Pull request by toonst**
Add support for display on stm32h750b_dk. `samples/drivers/display` is compiling and flashing correctly now. Still getting a white screen however, will investigate when I have some free time.
This is git based on https://github.com/zephyrproject-rtos/zephyr/pull/67120 and https://github.com/zephyrproject-rtos/zephyr/pull/67221

### CODE REVIEW

**Comment by kartben** [comment]
@toonst you need to enable the memory controller for sdram to actually be available :) Something like:

https://github.com/zephyrproject-rtos/zephyr/blob/e49d174be910760031fb2e8ea1df79ad25c8da7d/boards/arm/stm32f746g_disco/Kconfig.defconfig#L21-L28

BTW, looking at https://github.com/STMicroelectronics/stm32h750b-dk-bsp/blob/main/stm32h750b_discovery_sdram.h#L22, the SDRAM might rather be SDRAM2, available at 0xd0000000?

Similarly, memory config might need some updating? https://github.com/STMicroelectronics/stm32h750b-dk-bsp/blob/main/stm32h750b_discovery_sdram.c#L191-L208

**Comment by toonst** [comment]
> @toonst you need to enable the memory controller for sdram to actually be available :) Something like:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/e49d174be910760031fb2e8ea1df79ad25c8da7d/boards/arm/stm32f746g_disco/Kconfig.defconfig#L21-L28
> 
> BTW, looking at https://github.com/STMicroelectronics/stm32h750b-dk-bsp/blob/main/stm32h750b_discovery_sdram.h#L22, the SDRAM might rather be SDRAM2, available at 0xd0000000?
> 
> Similarly, memory config might need some updating? https://github.com/STMicroelectronics/stm32h750b-dk-bsp/blob/main/stm32h750b_discovery_sdram.c#L191-L208

Fixed the Kconfig and the SDRAM configuration. `samples/drivers/display` is compiling and flashing correctly. Still getting a white screen however, will investigate when I have some free time.

**Comment by erwango** [comment]
> @kartben Fixed the Kconfig and the SDRAM configuration. `samples/drivers/display` is compiling and flashing correctly now. Still getting a white screen however, will investigate when I have some free time.

Adding "Block HW Test" tag to notify this work is not yet ready to review.

@toonst Please update PR description if not accurate anymore. In general PR description should contain description of the change (what you're adding) and a note on status if not ready, which can be updated, with more details on the follow up messages. Alternatively, if submitting a work which is not complete yet, please use "Draft" PR.

**Comment by toonst** [comment]
@erwango Thanks. The title still accurately describes what this PR is about. Maybe this is not clear because the changed files also contain changes of two other PRs that this PR is based on.

**Comment by ajarmouni-st** [comment]
> @erwango Thanks. The title still accurately describes what this PR is about. Maybe this is not clear because the changed files also contain changes of two other PRs that this PR is based on.

@toonst since the PR's title says "add support for display", but we are still getting a white screen when running the display sample, that means the PR is still a work in progress & not ready for review.

**Comment by pcornu** [comment]
Hi :-)
I manage to make the display example running based on @toonst display patch + few changes: disp-on-gpios (D7), pll3, ltdc pixel clock, and sdram2 as external-sdram.
https://gist.github.com/pcornu/45809dff1ae4121da2a6f7384f10d2d6
I will try to find more time next week to fully check ltdc node: pinctrl, blanking values, backlight gpio...
Have fun & many thanks,
Philippe :-)

**Comment by erwango** [comment]
> Hi :-)

I've seen this face somewhere ;)
Great, we'll welcome your contribution!

**Comment by toonst** [comment]
Hi @pcornu, thanks for your improvements. I've added them in a commit and updated the branch here https://github.com/zephyrproject-rtos/zephyr/compare/main...toonst:zephyr:stm32h750b_dk_display. For some reason this PR doesn't reflect these changes (probably becaus it is closed).

**Comment by toonst** [comment]
Btw, I again get some linking errors with that version when building `west build -b stm32h750b_dk zephyr/samples/drivers/display`:

```
[138/143] Linking C executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map zephyrproject/build/zephyr/zephyr_pre0.map
: && ccache zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc  -gdwarf-4 zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr_pre0.elf  zephyr/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -fuse-ld=bfd  -T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map=zephyrproject/build/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/arm/core/libarch__arm__core.a  zephyr/arch/arch/arm/core/cortex_m/libarch__arm__core__cortex_m.a  zephyr/arch/arch/arm/core/mpu/libarch__arm__core__mpu.a  zephyr/lib/libc/picolibc/liblib__libc__picolibc.a  zephyr/lib/libc/common/liblib__libc__common.a  zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a  zephyr/drivers/clock_control/libdrivers__clock_control.a  zephyr/drivers/console/libdrivers__console.a  zephyr/drivers/display/libdrivers__display.a  zephyr/drivers/gpio/libdrivers__gpio.a  zephyr/drivers/pinctrl/libdrivers__pinctrl.a  zephyr/drivers/reset/libdrivers__reset.a  zephyr/drivers/serial/libdrivers__serial.a  zephyr/drivers/timer/libdrivers__timer.a  modules/stm32/stm32cube/lib..__modules__hal__stm32__stm32cube.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  -L"zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/thumb/v7e-m/nofp"  -Lcode/zephyrproject/build/zephyr  -lgcc  zephyr/arch/common/libisr_tables.a  -mcpu=cortex-m7  -mthumb  -mabi=aapcs  -mfp16-format=ieee  -mtp=soft  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn  -Wl,-no-pie  -DPICOLIBC_LONG_LONG_PRINTF_SCANF  --specs=picolibc.specs  -lc  -lgcc && cd zephyrproject/build/zephyr && /opt/homebrew/Cellar/cmake/3.29.1/bin/cmake -E true
zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: warning: orphan section `.stm32_sdram2' from `zephyr/drivers/display/libdrivers__display.a(display_stm32_ltdc.c.obj)' being placed in section `.stm32_sdram2'
ephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/zephyr_pre0.elf section `.stm32_sdram2' will not fit in region `IDT_LIST'
zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: section .stm32_sdram2 VMA wraps around address space
zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: region `IDT_LIST' overflowed by 228513 bytes
collect2: error: ld returned 1 exit status
```
I remember having this issue before, but forgot how it was resolved

**Comment by ajarmouni-st** [comment]
> Btw, I again get some linking errors with that version when building `west build -b stm32h750b_dk zephyr/samples/drivers/display`:
> 
> I remember having this issue before, but forgot how it was resolved

@toonst `west build -p always -b... ` could solve the issue.

**Comment by ajarmouni-st** [comment]
@toonst @pcornu just tested it on my board, `samples/drivers/display` is working like a charm

Here is the branch rebased on https://github.com/zephyrproject-rtos/zephyr/commit/b21b50b02b653925248af072f5f50588a10a99b4
https://github.com/ajarmouni-st/zephyr_dev/tree/dev_stm32h750b_dk_display

**Comment by ajarmouni-st** [comment]
> For some reason this PR doesn't reflect these changes (probably becaus it is closed).

@toonst yes you need to reopen the PR to see the updates to the branch.

**Comment by toonst** [comment]
I didn't cherry-pick the complete patch before, it is working now. New PR with patch by @pcornu available here: https://github.com/zephyrproject-rtos/zephyr/pull/73107 (I can't seem to re-open this one).

**Comment by pcornu** [comment]
My check results: pinctrl are fine, timings are fine **excepted "de-active" that should be 1 instead of 0**, fixing the screen artifact on the right hand side of the panel, pll3 values looks fine, pixel clocks is around ((25/5)*192)/99=9.7Mhz that is fine.
```
-		de-active = <0>;
+		de-active = <1>;
```
Hope it helps :-)
Philippe

**Pull request closed without merging**
