### PR TITLE
Added simple implementation of NuMaker PFM-M2351

### PR DESCRIPTION
**Pull request by travisby**
Howdy folks,

I own a NuMaker PFM-M2351 that I wanted to use with Zephyr.  I've tried to follow the previous NuMaker-PFM-M487 as an example for adding both a board and soc.

I'm very new to embedded/rtos' so I'd really appreciate a fine-tooth'd review.  Known-Unknowns I've called out with `XXX` to hopefully draw extra eyes to those lines.

I can say that both `zephyr/samples/synchronization` and `zephyr/samples/hello_world` both work, so at a minimum I have UART working ^.^. [edit -- I should say I have it working only with extra args to the `west flash` command, I wasn't sure how to specify special openocd settings as part of the config files]

I have added the numicro hal as part of my `select`s here, to use the already existing numicro_uart driver.  This does require a modification to the hal which is in a separate PR: zephyrproject-rtos/hal_nuvoton#3

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
There are some white space issues in Kconfig & dts files.  Please clean those up.

**Comment by travisby** [comment]
Sorry it took me so long to get back to this, @galak.  I believe I've made the suggested changes!

**Comment by wschang0** [comment]
We try to build but it seems to lack "NuMicro.h" file which causes build error.

**Comment by travisby** [comment]
Howdy @wschang0,

That was added to the separate repo hal_nuvoton -- https://github.com/zephyrproject-rtos/hal_nuvoton/pull/3

**Comment by wschang0** [comment]
Hi Travis,

We suggest to enable the configuration in "nuvoton_pfm_m2351_defconfig" for download and debug message.
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_UART_NUMICRO=y

Adding openocd support by edit "openocd.cfg" file content by "target/numicroM23.cfg"

For m2351\soc.c, you may need to add "CLK_SetCoreClock(FREQ_64MHZ);" in z_arm_platform_init()
To enable PLL of M2351 for CPU speed.

Regards,
WS

**Pull request closed without merging**
