### PR TITLE
Revert #23437

### PR DESCRIPTION
**Pull request by carlescufi**
Revert PR #23437, was merged by mistake

### CODE REVIEW

**Comment by nashif** [comment]
needs signed-off-by...

**Comment by carlescufi** [comment]
> needs signed-off-by...

Done, sorry.

**Review by galak — DISMISSED** [review]
Its annoying, but can you add in the commit message why we are reverting.  Its more for history if someone looks one day.

**Comment by carlescufi** [comment]
> Its annoying, but can you add in the commit message why we are reverting. Its more for history if someone looks one day.

Done, thanks.

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
