### PR TITLE
drivers: peci: microchip: Add MEC172x peci support

### PR DESCRIPTION
**Pull request by jvasanth1**
Add support for MEC172x peci and pin control changes.

### CODE REVIEW

**Review by albertofloyd — CHANGES_REQUESTED** [review]
@jvasanth1 understand this is not supposed to be enabled in minimum config. But this driver doesn't get compiled by enable CONFIG_PECI=y in samples/drivers/peci

**Comment by jvasanth1** [comment]
> @jvasanth1 understand this is not supposed to be enabled in minimum config. But this driver doesn't get compiled by enable CONFIG_PECI=y in samples/drivers/peci

Need to enable CONFIG_PECI_XEC=y as well.

**Comment by albertofloyd** [comment]
> > @jvasanth1 understand this is not supposed to be enabled in minimum config. But this driver doesn't get compiled by enable CONFIG_PECI=y in samples/drivers/peci
> 
> Need to enable CONFIG_PECI_XEC=y as well.

See MEC152x or other drivers for reference, that should not be needed.

**Comment by jvasanth1** [comment]
> > > @jvasanth1 understand this is not supposed to be enabled in minimum config. But this driver doesn't get compiled by enable CONFIG_PECI=y in samples/drivers/peci
> > 
> > 
> > Need to enable CONFIG_PECI_XEC=y as well.
> 
> See MEC152x or other drivers for reference, that should not be needed to be explicit. CONFIG_PECI_XEC=y should be enabled automatically when CONFIG_PECI and MEC172x boards/soc are enabled.

Updated accordingly in MEC172x Kconfig.

**Review by albertofloyd — DISMISSED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
> Update Microchip XEC PECI driver to support MEC172x.
> Standardize device structure usage.

Please split these changes into two commits

**Comment by jvasanth1** [comment]
> > Update Microchip XEC PECI driver to support MEC172x.
> > Standardize device structure usage.
> 
> Please split these changes into two commits

split into 2 commits.

**Review by MaureenHelm — APPROVED** [review]

**Review by albertofloyd — APPROVED** [review]

**Pull request merged**
