### PR TITLE
Fix timer defaults for Intel Apollo Lake based boards

### PR DESCRIPTION
**Pull request by jhedberg**
Three patches to fix the default timer selection and related Kconfig options for gpmrb and up_squared boards.

### CODE REVIEW

**Comment by jhedberg** [comment]
@dcpleung you might want to incorporate these into your PR since there'll be conflicts otherwise with `up_squared/Kconfig.defconfig`

**Review by andyross — APPROVED** [review]
Looks great.  We should still make APIC work with SMP though.

**Comment by jhedberg** [comment]
@andyross CI is failing to build `tests/benchmarks/boot_time` for the `gpmrb` board because of this:
```
warning: BOOT_TIME_MEASUREMENT (defined at subsys/debug/Kconfig:9) was assigned the value 'y' but
got the value 'n'. Check these unsatisfied dependencies: (ARCH_POSIX || ARM || (X86 && APIC_TIMER &&
APIC_TIMER_TSC)) (=n)
```

which eventually results in this:

```
tests/benchmarks/boot_time/src/main.c: In function 'main':
tests/benchmarks/boot_time/src/main.c:37:15: error: 'z_timestamp_main' undeclared (first use in this function)
   37 |        (u64_t)z_timestamp_main,
      |           
```

Is it there something missing in the HPET driver implementation why it doesn't satisfy the dependencies for `BOOT_TIME_MEASUREMENT` or those dependencies are not correct?

**Comment by nashif** [comment]
```diff
--- a/subsys/debug/Kconfig
+++ b/subsys/debug/Kconfig
@@ -8,7 +8,7 @@ menu "System Monitoring Options"

 config BOOT_TIME_MEASUREMENT
        bool "Boot time measurements"
-       depends on ARCH_POSIX || ARM || (X86 && APIC_TIMER && APIC_TIMER_TSC)
+       depends on ARCH_POSIX || ARM || X86
        help
          This option enables the recording of timestamps during system boot.
```

solves it or me, and the test runs on the up_squared board.

**Comment by jhedberg** [comment]
@nashif thanks, I've now included a patch which simplifies the X86 dependency as suggested

**Comment by dcpleung** [comment]
Does HPET start early enough for the boot timing measurement to be meaningful?

**Comment by jhedberg** [comment]
> Does HPET start early enough for the boot timing measurement to be meaningful?

All timers seem to be initialised through the same `z_clock_driver_init()` call in the `PRE_KERNEL_2` phase. That said, I'm not familiar with the details of these drivers, in case there's some extra start-up latency in HPET, or something like that.

**Comment by andrewboie** [comment]
I would think any boot-time measurement would absolutely have to be TSC-based in order to produce useful numbers, since neither the HPET or LOAPIC are available until much later in the boot process.

**Comment by andyross** [comment]
I don't know why CONFIG_BOOT_TIME_MEASUREMENT is hardcoded to those particular drivers.  There is nothing special about the apic timer vs. hpet in this context (but @andrewboie is correct that neither timer can be used before PRE_KERNEL_2 and that we should probably support some kind of framework for early timestamps via raw counters like the TSC).  My guess is that @wentongwu just listed what was validated?  I agree with @nashif that just removing the false dependency seems like the obvious fix.

**Review by carlescufi — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
