### PR TITLE
drivers: watchdog: Pass timeout in ms if iwdg is started at boot

### PR DESCRIPTION
**Pull request by aakkds**
iwdg_stm32_install_timeout expects a timeout passed in
	milli seconds. As the timeout is defined in micro
	seconds in Kconfig.stm32, we need to divide by
	USEC_PER_MSEC when CONFIG_IWDG_START_AT_BOOT is
	activated because iwdg_stm32_install_timeout makes
	the multiplication by USEC_PER_MSEC.

Signed-off-by: Philémon Jaermann <p.jaermann@gmail.com>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
@aakkds, LGTM.
In order to get this in 2.0, we need to add a reference to a matching issue (https://github.com/zephyrproject-rtos/zephyr/issues/18695 I just created).
Can you add the following in commit message?
```
Fixes #18965
```

**Comment by aakkds** [comment]
@erwango Sure! It's done

**Comment by erwango** [comment]
@aakkds, txs. btw, can you fix indentation in commit message? It's not required actually

**Comment by aakkds** [comment]
@erwango yep, done

**Review by erwango — APPROVED** [review]

**Pull request merged**
