### PR TITLE
net: dns: Fix formatting

### PR DESCRIPTION
**Pull request by Ayush1325**
- Format using clang-format with zephyr config
- I was working on this subsys and did not want to pollute the PRs with formatting changes
- Fix `.clang-format` to not indent goto labels. Gives CI error.

### CODE REVIEW

**Review by jukkar — CHANGES_REQUESTED** [review]
Sorry but I do not like what the DNS code now looks like. There is really no need to change the formatting in those files.

**Comment by Ayush1325** [comment]
> Sorry but I do not like what the DNS code now looks like. There is really no need to change the formatting in those files.

Well, in the current code, I have to manually fix any kind of formatting changes that arise while moving stuff or adding new stuff. This can be a bit cumbersome when trying to add support for new stuff (working on support for PTR query defined in DNS_SD) since I sometimes have to change formatting of like 100 lines manually.

I don't particularly care about manually formatting header files, but I would really like not to have to do stuff by hand in the c files.

**Comment by jukkar** [comment]
> Well, in the current code, I have to manually fix any formatting changes that arise while moving stuff or adding new stuff. This can be a bit cumbersome when trying to add support for new stuff (working on support for PTR query defined in DNS_SD [RFC6763](https://datatracker.ietf.org/doc/html/rfc6763)) since I sometimes have to change the formatting of like 100 lines manually.
> 
> I don't particularly care about manually formatting header files, but I would really like not to have to do stuff by hand in the c files. Of course, I don't mind if you want me to use a config other than zephyr default or even a different formatter, but I would like it to be somehow automated.

The problem with these formatting patches is that it is annoying to backport patches to older release because the patches do no longer apply cleanly. So they do not bring any real benefits, but just more work when maintaining the code.
The original code is formatted using the 80 column rule which is shorter that what is currently allowed, but it is still very readable.

Not sure why you would need to fix formatting when moving or adding new stuff, why would you need to do that? Just follow the coding style of the original file.

**Comment by Ayush1325** [comment]
> The problem with these formatting patches is that it is annoying to backport patches to older release because the patches do no longer apply cleanly. So they do not bring any real benefits, but just more work when maintaining the code. The original code is formatted using the 80 column rule which is shorter that what is currently allowed, but it is still very readable.

I see. I did not realize the problem in backporting.

> Not sure why you would need to fix formatting when moving or adding new stuff, why would you need to do that? Just follow the coding style of the original file.

Well, sure, it is fine when working with a small number of changes or just adding a new self-contained function. But well, when modifying a large portion of the file functionality, it becomes a problem since I am not completely sure what coding style is being followed here. I tried checking and it seems like there are differences other than just the 80-column rule. While I can manually fix most of the stuff the compliance script might complain about, everything opinionated will need to be pointed out by whoever is reviewing the PR.

I won't press too hard if everyone is in agreement to not use formatter for this subsystem, but well I would prefer being able to automate it.

**Comment by Ayush1325** [comment]
> I agree with Jukka here, large patches like this are cumbersome with backporting and blur the blame history. Plus it seems that the majority of changes here are just a result of an increased char/line limit that took place some time ago in Zephyr. Please note, that if you need to format your changes, you can use `git-clang-format` to apply the formatting on diff (commit) only.

Alright. Going to close this.

**Pull request closed without merging**
