### PR TITLE
net: websockets: do not close tcp socket in websocket

### PR DESCRIPTION
**Pull request by ssekar15**
The websocket_connect api expects connected tcp socket. Closing tcp socket at websocket layer is incorrect

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Original rationale for closing the user supplied socket was that it was not usable after closing the websocket. But indeed it might make sense to not close the original socket here so that it can be re-used. Also the user supplied socket is not really "owned" by websocket library so closing it here is not good.

I would like to see better commit message, it is not clear from the text why we do not want to close the socket here.
So perhaps something like
`Do not close the user supplied socket so that the caller can re-use it if needed.`

Please also fix the `samples/net/sockets/websocket_client` sample app so that it will close the socket so that we do not leak it.

**Comment by rlubos** [comment]
There's also `mqtt_client_websocket_disconnect()` in `subsys/net/lib/mqtt/mqtt_transport_websocket.c` that should be aligned (i. e. underlying sock should be closed).

**Comment by jukkar** [comment]
This could also be considere an API change so probably needs to be mentioned in the release notes.
Also could be mentioned in the websocket API documentation that user needs to close the socket itself.

**Comment by ssekar15** [comment]
@jukkar @rlubos thanks for your time. Fixed the review comments, please have a look.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by rlubos — APPROVED** [review]

**Pull request merged**
