### PR TITLE
doc: porting: boards: Update the terminology diagram

### PR DESCRIPTION
**Pull request by carlescufi**
The current diagram uses a custom font that does not render correctly on some browsers. Replace it with a common font (Courier New) instead so that there are no rendering issues.

### CODE REVIEW

**Comment by carlescufi** [comment]
@nordicjm @tejlmand can you check if this works fine now?

https://builds.zephyrproject.io/zephyr/pr/71579/docs/hardware/porting/board_porting.html#board-terminology
https://builds.zephyrproject.io/zephyr/pr/71579/docs/_images/board-terminology.svg

**Comment by nordicjm** [comment]
> @nordicjm @tejlmand can you check if this works fine now?
> 
> https://builds.zephyrproject.io/zephyr/pr/71579/docs/hardware/porting/board_porting.html#board-terminology https://builds.zephyrproject.io/zephyr/pr/71579/docs/_images/board-terminology.svg

Is broken, the texts wraps around to a second line after the `nrf5340/`. Maybe make the svg and text box slightly bigger

**Comment by carlescufi** [comment]
> > @nordicjm @tejlmand can you check if this works fine now?
> > https://builds.zephyrproject.io/zephyr/pr/71579/docs/hardware/porting/board_porting.html#board-terminology https://builds.zephyrproject.io/zephyr/pr/71579/docs/_images/board-terminology.svg
> 
> Is broken, the texts wraps around to a second line after the `nrf5340/`. Maybe make the svg and text box slightly bigger

Can you check again @nordicjm?

**Review by tejlmand — APPROVED** [review]
Verified with:
Linux: firefox, chrome
Windows: firefox, chrome, edge

Looks good on all.

Only browser which doesn't seem to render the svg is Lynx 😆

**Review by nordicjm — APPROVED** [review]
Works here

**Comment by tejlmand** [comment]
I noticed shadows has been removed in the updated picture.
Is that intentional ?

**Review by aescolar — APPROVED** [review]

**Comment by carlescufi** [comment]
> I noticed shadows has been removed in the updated picture. Is that intentional ?

No, oversight. But no big deal

**Comment by tejlmand** [comment]
> No, oversight. But no big deal

I agree, if it was a big deal I would have requested changes 😉 
Just wanted to pass on my observation, to give the chance of update the picture in case you prefer the shadows.

**Pull request merged**
