### PR TITLE
xtensa: mmu: Enhacements and fixes

### PR DESCRIPTION
**Pull request by ceolin**
- Save memory using the kernel page table for the default memory domain.
  -   Uses the SW (area dedicated to sw implementation) to save the original map that is used when duplicating this table  for new memory domains
 - Fix the macro `XTENSA_MMU_PTE_RING_GET`
 - Remove duplicated `XTENSA_MMU_PTE` macro
 -  Remove unnecessary parameter in internal function
 - Simplify the logic around shared ASID in the memory map

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Review by nashif — DISMISSED** [review]

**Comment by aescolar** [comment]
@ceolin rebase needed

**Comment by ceolin** [comment]
> @ceolin rebase needed

done :)

**Comment by ceolin** [comment]
@nashif @dcpleung can you refresh the review after the rebase ?

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Never gave this a +1, but looks clean

**Pull request merged**
