### PR TITLE
drivers: ieee802154: gracefully handle invalid Ack timestamp

### PR DESCRIPTION
**Pull request by jciupis**
The nRF IEEE 802.15.4 driver might report a received Ack frame with invalid timestamp, if the timestamp could not have been taken. The upper layers are not prepared to handle such a case as they expect that for a received frame, the timestamp is always present and valid.

This commit detects this situation and handles it gracefully by reporting the transmission as failed as if no Ack was received.

### CODE REVIEW

**Comment by jciupis** [comment]
FYI @ankuns @LuDuda

**Review by Damian-Nordic — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
LGTM :+1:

**Review by rlubos — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by jciupis** [comment]
Is there anything in the way of merging this PR?

**Comment by fgrandel** [comment]
@jciupis Sorry, that I didn't comment on this PR. I was ill quite a long time and wasn't aware of it. Just got the merge message.

Question: Would it make sense to document this solution as general expected behavior in the radio driver API? No need to do it now of course but could be added next time you make a change to the driver maybe? Our API description is quite specific and detailed by now so I think it could fit there.

**Comment by jciupis** [comment]
@fgrandel it's great to hear that you are back and well! Sure, it makes sense to document it if we agree that it should be the expected behavior in general. I'll open a separate PR because I'd probably forget to add it when making other, unrelated changes. Is adding a relevant section in [this doc](https://github.com/zephyrproject-rtos/zephyr/blob/9f0cd47c784e4d2099f59899d17a6ba5f3d4be55/include/zephyr/net/ieee802154_radio.h#L1606-L1680) sufficient?

**Comment by fgrandel** [comment]
> @fgrandel it's great to hear that you are back and well!

:-) thx!! I'm also very happy that I can continue to contribute. Found a job that allows me to do that.

> Is adding a relevant section in [this doc](https://github.com/zephyrproject-rtos/zephyr/blob/9f0cd47c784e4d2099f59899d17a6ba5f3d4be55/include/zephyr/net/ieee802154_radio.h#L1606-L1680) sufficient?

Absolutely, probably it can be as simple as:

>  @retval -ENOMSG The frame was not confirmed by an ACK packet (TX ACK offloading feature only) **or the received ACK packet was invalid**.

Does something like this designate the essence of your change? If not feel free to do it differently of course.

**Pull request merged**
