### PR TITLE
I2C: Add common I2C context and refactor nRF TWI and TWIM to use it

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
## Overview
Adds common I2C context for I2C controller device drivers which provides an event driven framework compatible with both the synchronous `i2c_transfer()` API and the asynchronous `i2c_transfer_cb()` and `i2c_transfer_signal()` APIs. This greatly simplifies device drivers by moving the transfer flow to a common module, making every driver capable of implementing the transfer_cb API.

## The I2C context
The I2C context provides callbacks which are executed in a safe context which device drivers shall implement, along with an API for the device drivers to start a transfer, and signal the result of a partial transfer (sending a single i2c_msg).

The I2C context runs in the calling context of `i2c_transfer()` if `CONFIG_I2C_CALLBACK=n`, like most drivers do now. If `CONFIG_I2C_CALLBACK=y`, the I2C context delegates all work to the system workqueue, allowing the entire transfer to be performed asynchronously, without any alteration to the device drivers.

## RTIO
RTIO (in the context of I2C) provides a queue to perform async I2C operations. Each of these operations can be directly fulfilled by an I2C API call:

- RTIO_OP_NOP -> Do nothing
- RTIO_OP_RX  -> call `i2c_read_cb()` (helper needs to be added)
- RTIO_OP_TX  -> call `i2c_write_cb()` (helper needs to be added)
- RTIO_OP_CALLBACK -> Call back
- RTIO_OP_TXRX -> call `i2c_write_read_cb()`
- RTIO_OP_I2C_RECOVER() -> i2c_recover() (may need async variant)
- RTIO_OP_I2C_CONFIGURE() -> i2c_configure() (may need async variant)

I2C controller device drivers can implement the I2C device driver API, and a higher level RTIO context can wrap the RTIO messages into `struct i2c_msg` and call i2c_transfer_cb(), using the callback to pass the transfer result to `i2c_rtio_complete`, like what is done for the `i2c_transfer_signal()` wrapper.

## Layers
The device driver implements the I2C APIs, `transfer`, `recover_bus` and `configure`. It uses the `i2c_context` to manage the transfer flow.

If `CONFIG_RTIO=n` and `CONFIG_I2C_CALLBACK=n`, the device driver uses no work queues or other async delegation, it simply runs from the context of the caller to any of its three APIs.

If `CONFIG_I2C_CALLBACK=y`, the device driver implements the `transfer_cb` API (which is free using the i2c_context). Calls to `transfer` and `transfer_cb` run in the context of the system workqueue.

If `CONFIG_RTIO=y`, `CONFIG_I2C_CALLBACK=y` is selected. The device driver implements the `i2c_rtio` context and `iodev_submit` API. Calls to `iodev_submit` are converted to calls to the `transfer_cb`, `recover_bus` and `configure` APIs.

This provides a clear layer separation from lowest complexity/size to highest complexity/size, while essentially requiring only that device drivers implement the `transfer_cb` to be compatible with RTIO.

### CODE REVIEW

**Comment by teburd** [comment]
Why not use the i2c_rtio context and build on that instead? This is the future of where I'd like to see i2c go, its definitely the future of where sensors is going.

**Comment by bjarki-andreasen** [comment]
@teburd The call to i2c_tranfer_cb will indeed fail with -EWOULDBLOCK if transfer is already ongoing (see line 182 of i2c_context.c)

Regarding RTIO, it is quite a bit more complex than `i2c_transfer_cb`. At this time, we (Nordic) want to support it, and using this context makes this trivial (while also cleaning up the implementation of the blocking `i2c_transfer()`) I see no downside to using it at this time :)

**Comment by teburd** [comment]
> @teburd The call to i2c_tranfer_cb will indeed fail with -EWOULDBLOCK if transfer is already ongoing (see line 182 of i2c_context.c)
> 
> Regarding RTIO, it is quite a bit more complex than `i2c_transfer_cb`

It's already supported for twi, for twim it could easily be supported similarly with I'd guess ~300-500 lines of C code. I don't consider ~300-500 lines of C code complex myself but perhaps I'm missing something, and if so please do help me understand.

Adding work queues with cancellation and timeouts and such to transfers is... exactly what I'm trying to solve in a general way with RTIO. We already have cancellation. Timeouts is a matter of replicating what io_uring does, which would work for all drivers (spi, i2c, sensors, etc) in a common manner. I think this is duplicating efforts that could be better spent improving a common asynchronous I/O framework, one that works with the future of sensors.

**Comment by bjarki-andreasen** [comment]
@teburd I will look into extending the context to cover RTIO, or the other way around, whichever is simpler, As long as we end up with one simple framework that supports every usecase :) RTIO should map exactly to the I2C API I would imagine

**Comment by teburd** [comment]
> @teburd I will look into extending the context to cover RTIO, or the other way around, whichever is simpler, As long as we end up with one simple framework that supports every usecase :) RTIO should map exactly to the I2C API I would imagine

It does, and provides a common driver context (i2c_rtio) which the twi driver takes advantage of

**Comment by bjarki-andreasen** [comment]
I will look into it :)

**Comment by bjarki-andreasen** [comment]
@teburd Do you have any references, like samples or documentation, I can use to learn more about RTIO? I'm especially interested in how an I2C attached sensor driver would use it, would it replace calls to the I2C API `i2c_write()` for example?

**Comment by teburd** [comment]
> @teburd Do you have any references, like samples or documentation, I can use to learn more about RTIO? I'm especially interested in how an I2C attached sensor driver would use it, would it replace calls to the I2C API `i2c_write()` for example?

You don't have to replace the blocking calls, those are converted for you by the i2c_rtio context. The most useful addition is the ability to do asynchronous bus requests directly from an ISR, avoiding the need of a dedicated thread or terrible latency k_work just to start an i2c transaction to read a sensor.

icm42688 is the only driver that really does this today that I can currently recall. @ubieda or @yperess might recall others. I believe @MaureenHelm was interested in porting some ADI drivers as well and was a supporter of the work on all of this.

**Comment by teburd** [comment]
I didn't mean to close this, apologies

**Comment by JordanYates** [comment]
Speaking of TWIM, PR for RTIO support is up #76904

**Pull request closed without merging**
