### PR TITLE
samples: net: mqtt_publisher: Add the relevant prj files

### PR DESCRIPTION
**Pull request by jiequanx**
Added the prj_arduino_101.conf and prj_bt.conf files

Signed-off-by: Wu Jiequan <jiequanx.wu@intel.com>

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

**Comment by pfalcon** [comment]
This patch needs rebase.

**Review by jukkar — CHANGES_REQUESTED** [review]
Please rebase this patch so we can merge it.

**Review by jukkar — CHANGES_REQUESTED** [review]
Please do not have any merge commits in your PR. What this means that you need to rebase your own tree from latest master, then re-submit this PR again.

**Comment by jiequanx** [comment]
Verify the mqtt sample on FRDM and Qemu.

**Pull request closed without merging**
