### PR TITLE
ext: hal: atmel: sam: update to version 2.3.98

### PR DESCRIPTION
**Pull request by aurel32**
This is an import of Atmel SAM E70 HAL version 2.3.98, and only for the
revision A of the chip. The files have been passed through dos2unix to
minimize the differences with the previous version which seems to also
have been imported that way.

On top of that the following commit has been reapplied:
* 133306152 ("Add missing header files symbols for Atmel SAM E70)"
  => except the DACC alternate pin functions which has been fixed in the
     same way in the new version.

The following commits have not been reapplied, and the README file has
been updated accordingly:
* 9670dc582 (Remove unused and broken preprocesor macros)
  => The macros have been changed from the _U to _U_ style and thus are
     less likely to break compilation with some toolchains.
* 4dcfc8706 (Add missing interrupt number definitions)
  => This has been fixed with a slightly different way in the new
     version. This commit also adjusts the names in the ethernet driver.
* 3369a9639 ("ext: same70: Add missing PMC_SR_PCKRDY3 define")
  => This has been fixed the same way in the new version.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

### CODE REVIEW

**Comment by aurel32** [comment]
> > On top of that the following commit has been reapplied:
> > 
> > * [1333061](https://github.com/zephyrproject-rtos/zephyr/commit/13330615267b41c18ac63201e8c09611f3926467) ("Add missing header files symbols for Atmel SAM E70)"
> >   => except the DACC alternate pin functions which has been fixed in the
> >   same way in the new version.
> 
> can this be an actual commit?

I can indeed split that into a separate commit, however that means the intermediate commits won't build. Is it acceptable?

**Comment by aurel32** [comment]
@galak I have just pushed a new version that split out the HAL update from the other patches. Note that these commits are not bisectable anymore, ie the ethernet driver won't compile with intermediate commits.

**Review by mnkp — APPROVED** [review]
This looks good with a minor remark regarding commit title. "ext: hal: atmel: sam: re-add missing header files following HAL import" should be better changed to "ext: hal: atmel: sam: re-add missing header symbols" since we are adding symbols not files.

**Review by nashif — APPROVED** [review]

**Comment by aurel32** [comment]
> This looks good with a minor remark regarding commit title. "ext: hal: atmel: sam: re-add missing header files following HAL import" should be better changed to "ext: hal: atmel: sam: re-add missing header symbols" since we are adding symbols not files.

@mnkp Thanks for the review. That is a good point, I have just fixed that.

**Review by galak — APPROVED** [review]

**Pull request merged**
