### PR TITLE
boards: stm32f4_disco: Add CONFIG_GPIO_STM32_PORTD

### PR DESCRIPTION
**Pull request by psidhu**
blinky example crashes otherwise.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
For coherency, enabling PORT D should be done in 
arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.series
such as it is done for port A, B, C.
Though, comment should be updated for all stm32f4 based SoCs.

**Comment by psidhu** [comment]
@erwango Ok. I pushed code that does what I believe you were talking about.

**Review by erwango — DISMISSED** [review]
Miss a commit message in your clean up commit.
Otherwise LGTM

**Comment by psidhu** [comment]
@erwango Thanks for catching that. I pushed a new commit.

@galak Looks like this may be ready to merge.

**Review by nashif — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
