### PR TITLE
Removing unused 15.4 drivers

### PR DESCRIPTION
**Pull request by tbursztyka**

### CODE REVIEW

**Review by rlubos — APPROVED** [review]
LGTM, provided there are indeed no users of these drivers.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
No, we can not do that. I can understand if you no longer want to maintain (especially) these devices. But [CC2520](http://www.ti.com/product/CC2520) and [CC1200](http://www.ti.com/product/CC1200) are still active. Last time we did not even want to remove support for discontinued TMP007.

**Comment by pfalcon** [comment]
@jfischer-phytec-iot: Thanks for speaking up. (Though unless a maintainer for these is found, they still would have a hard fate.)

**Comment by tbursztyka** [comment]
@jfischer-phytec-iot ok, you do use these drivers then? I am not against maintaining those, but currently no boards supports it in Zephyr, it would help if there was.

**Comment by jfischer-phytec-iot** [comment]
> @jfischer-phytec-iot ok, you do use these drivers then? I am not against maintaining those, but currently no boards supports it in Zephyr, it would help if there was.

I do not use any, I had my lesson with CC2520. But someone could use it out-of-tree or could decide to use it because the drivers are included in release and the next time they are just gone. Even if there is no need for this transceivers and everyone agree, I suggest to have some kind of "[deprecation phase](https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html?#deprecated)" for this type of complex devices.

**Comment by tbursztyka** [comment]
> I suggest to have some kind of "deprecation phase" for this type of complex devices.

We'll need to come with a deprecation procedure for drivers then.

**Review by vanti — APPROVED** [review]

**Comment by jukkar** [comment]
> We'll need to come with a deprecation procedure for drivers then.

Perhaps similar way like APIs are deprecated. So marking drivers as deprecated and then removing them after two release cycles. 
https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html?highlight=deprecate

**Comment by nashif** [comment]
> currently no boards supports it in Zephyr,

that is not a factor, those devices can be used with any board. If we do not build them or test them, this is another issue and it would apply to many other devices that are peripheral in nature and can be added to any board

**Comment by tbursztyka** [comment]
@nashif True. It would be really great to have a board supporting those anyway.

Closing this PR then.

**Pull request closed without merging**
