### PR TITLE
workflows: Add a workflow to add items to projects

### PR DESCRIPTION
**Pull request by keith-zephyr**
Create a workflow using the actions/add-to-project to automatically add issues with the "Process" label to the Process project.

### CODE REVIEW

**Comment by nashif** [comment]
This is a built-in feature of projects, not sure why you need an action for that.

**Comment by nashif** [comment]
@keith-zephyr  I think you want to use to move away from classic projects and use the new project type, this is built-in.

**Comment by keith-zephyr** [comment]
> @keith-zephyr I think you want to use to move away from classic projects and use the new project type, this is built-in.

The [Process](https://github.com/zephyrproject-rtos/zephyr/projects/33) has already been moved from the classics project area.

I'm not seeing seeing issues with the "Process" label automatically get added to the Process project.

For example: on issue https://github.com/zephyrproject-rtos/zephyr/issues/61374, I manually added it to the Process project about 7 hours after you added the label.

**Comment by keith-zephyr** [comment]
> > @keith-zephyr I think you want to use to move away from classic projects and use the new project type, this is built-in.
> 
> The [Process](https://github.com/zephyrproject-rtos/zephyr/projects/33) has already been moved from the classics project area.
> 
> I'm not seeing seeing issues with the "Process" label automatically get added to the Process project.
> 
> For example: on issue #61374, I manually added it to the Process project about 7 hours after you added the label.

My mistake, I see the Process project is still under the "classic" tab.

**Comment by keith-zephyr** [comment]
Opened https://github.com/zephyrproject-rtos/zephyr/issues/61400 to migrate "Process" from the classic to new style github project.

**Pull request closed without merging**
