### PR TITLE
samples: sensor: Enable bme280 sensor using I2C driver

### PR DESCRIPTION
**Pull request by srinivas-aerlync**
Added overlay to enable bme280 sensor
using i2c on esp32_devkitc_wroom board.

### CODE REVIEW

**Review by MaureenHelm — COMMENTED** [review]
Is this sensor on the board or did you manually attach it somehow (with a shield or hand wiring)?

**Comment by srinivas-aerlync** [comment]
It is connected manually,

**Comment by srinivas-aerlync** [comment]
@MaureenHelm  any comment on this changes please.

**Comment by kartben** [comment]
> It is connected manually

Then the value of adding this overlay to the source tree is probably very limited. We certainly don't want / can't have upstream all the overlays possible for any combination of sensors people may attach to their dev kits :)
I will close this PR if that's ok with you. Let me know if you have questions or concerns

**Pull request closed without merging**
