### PR TITLE
Add support for setting function properties using Doxygen

### LINKED ISSUE #21061: Document where APIs can be called from using doxygen
## Introduction

Right now we have no standard way for documenting what APIs can be called from where and if they for example are allowed to be called from thread context or ISR context or if they can be used during initialization of the system for example.

### Problem description

Documentation of the above is spread around the project either in the implementation itself or in the API docs or in the guides, but there is no 1 single place where we reliably and consistently document this.

### Proposed change

Use a custom tag in doxygen to document the context from which an API can be called from

## Detailed RFC

Add a new alias to doxygen (\@allowed_from) and use it consistently to document from what contexts APIs are allowed to be called.

### Proposed change (Detailed)

for example:
```diff
diff --git a/doc/zephyr.doxyfile.in b/doc/zephyr.doxyfile.in
index 147f94f629..087fc17892 100644
--- a/doc/zephyr.doxyfile.in
+++ b/doc/zephyr.doxyfile.in
@@ -224,6 +224,7 @@ ALIASES                = "rst=\verbatim embed:rst:leading-asterisk" \
                          "endrst=\endverbatim"

 ALIASES               += "req=\xrefitem req \"Requirement\" \"Requirements\" "
+ALIASES            += "allowed_from=\xrefitem context \"Allowed from\" \"Allowed from\" "

 # This tag can be used to specify a number of word-keyword mappings (TCL only).
 # A mapping has the form "name=value". For example adding "class=itcl::class"
```
will allow us to do this:

```diff
diff --git a/include/kernel.h b/include/kernel.h
index 23c0fd17f0..2ab916bcd4 100644
--- a/include/kernel.h
+++ b/include/kernel.h
@@ -1890,7 +1890,7 @@ __syscall void k_queue_init(struct k_queue *queue);
  * -EINTR and K_POLL_STATE_CANCELLED state (and per above, subsequent
  * k_queue_get() will return NULL).
  *
- * @note Can be called by ISRs.
+ * @allowed_from Threads, ISRs
  *
  * @param queue Address of the queue.
  *
```

which will result in:

image

instead of what we have now:

image

The above will also generate 1 single page with all the information:

image

### Dependencies

Doxygen changes

### Concerns and Unresolved Questions

How do we enforce this for example?

## Alternatives

Alternative is to create some table or adhoc documentation that will always be out of sync. If we make this a requirement for any new API, then we can always rely on the autogenerated doxygen documentation.

### PR DESCRIPTION
**Pull request by gmarull**
# Current approach
This PR is an attempt to resolve #21061 by using Doxygen aliases. Developer can add a list of function properties by using `@funcprops \prop1, ..., \propN`. They will be rendered as plain text in the Doxygen build and a with a link to terminology on the Sphinx side. Note that this solution does not allow to obtain a list of, e.g. "all functions that are async".

Doxygen output:
image

Sphinx output:
image

**Pros**: Minimal changes, standardized keywords, renders links on the Sphinx side
**Cons**: Plain-text on the Doxygen side, not possible to list functions with a certain property

# Other options

## Links to terminology in both Doxygen and Sphinx
In order to achieve this functionality the `terminology.rst` content needs to be moved to a Doxygen page. Then, the `ALIAS` can contain, e.g. `@ref async`. The content of the Doxygen page can be rendered back in Sphinx using the recently added `..doxygenpage` directive in `breathe`, together with https://github.com/michaeljones/breathe/pull/645.

Doxygen output:
image

image

Sphinx output:

image

image

**Pros**: Function properties contain link to terminology in both, Doxygen and Sphinx.
**Cons**: Terminology has to be moved to Doxygen

# List of functions with a certain property

In order to obtain a list of functions that have a certain property, e.g. `async` I have tried the options listed below. Note that I haven't had success in obtaining a fully functional solution.

## `\xrefitem`
Using `\xrefitem <key> "(heading)" "(list title)" { text }` a new page is created in the Doxygen side with a list of all functions that have the property set. One of the problems is that the generated page is added to the root of the Doxygen tree. Furthermore, I haven't been able to make this option work reliably when multiple properties are used.

Doxygen:

image

Sphinx:

image

image

**Pros**: Pages with a list of all functions with a certain property are generated
**Cons**: **Not working properly on the Sphinx side** (renders empty), page location can't be controlled in the Doxygen side

## `\ingroup`
The advantage of using groups is that pages location can be controlled (e.g. creating a parent group somewhere in the hierarchy). However, the function will be listed in only one group, so it is not an option.

From Doxygen documentation:
> Note that compound entities (like classes, files and namespaces) can be put into multiple groups, but members (like variable, functions, typedefs and enums) can only be a member of one group (this restriction is in place to avoid ambiguous linking targets in case a member is not documented in the context of its class, namespace or file, but only visible as part of a group).

**Pros**: None
**Cons**: Does not work when multiple properties are used.

# Table of properties

In order to generate something like:

function           | syscall | reschedule | sleep | no-wait | isr-ok | pre-kernel-ok | async | supervisor
------------------ | ------- | ---------- | ----- | ------- | ------ | ------------- | ----- | ----------
k_mutex_init       | YES     | no         | no    | yes     | yes    |               |       |
k_mutex_lock       | YES     | yes        | YES   | YES     | NO*    |               |       |

I haven't found a solution using existing Doxygen/Sphinx/Breathe facilities. On the Doxygen side we should have conditionals to evaluate certain properties of a function. As fas as I know, this is not possible. Onthe Sphinx side we need to implement  a new custom plugin that parses Doxygen XML files and generates such table. It may be possible to re-use `breathe` parser, but I'm not sure it it is worth for this purpose due to its "complexity".

### CODE REVIEW

**Review by pabigot — COMMENTED** [review]
I don't have an opinion on whether this is adequate for Zephyr's needs, but it's a reasonable first step.

https://github.com/pabigot/zephyr/commits/pr/32972 has two fixup commits that complete the terminology set and the proposed effect on the api in https://github.com/zephyrproject-rtos/zephyr/issues/18970#issuecomment-651445304

**Comment by galak** [comment]
dev-review (Apr 1):
* Add a comma or some visual separator for the list
* Add something about function properties being a WIP
* plan to merge this to enable being able to update a subsystem with function properties

**Comment by gmarull** [comment]
Updated PR:
- `Function properties` title moved to `Function properties (list may not be complete)`. Breathe doesn't seem to render `\n`, so it is not easy/possible to render this information afterwards. In my opinion adding this information is misleading. Current docs may also suffer this problem.
- Regarding comma, it is actually possible to write `@funcprops \prop0, \prop1, ..., \propN`, so I haven't changed anything.

**Comment by gmarull** [comment]
@nashif @carlescufi ping

**Review by dcpleung — APPROVED** [review]
I wonder if it is possible to have a brief "pop-up" description when you hover over the properties.

**Comment by gmarull** [comment]
> I wonder if it is possible to have a brief "pop-up" description when you hover over the properties.

Afaik this is not trivial to do, would require a Sphinx plugin at least.

**Review by carlescufi — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
