### PR TITLE
west.yml: Update zcbor from 0.8.0 to 0.8.1

### PR DESCRIPTION
**Pull request by oyvindronningstad**
Brings a few improvements and bugfixes, most notably:
- Adds a forward declaration of strnlen()
- Adds a ZCBOR_VERSION macro

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
cc @aescolar

**Comment by aescolar** [comment]
Thanks @oyvindronningstad 
I just retriggered CI as a PR which affects this has just been merged.

**Review by aescolar — APPROVED** [review]
LGTM

**Review by SeppoTakalo — APPROVED** [review]
OK from LwM2M point of view.

**Review by nordicjm — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
