### PR TITLE
net: dhcpv4: Add locking

### LINKED ISSUE #33348: ip/dhcpv4 is not thread-safe in SMP/preemptive thread configurations
The DHCPv4 implementation maintains a list of interfaces that support DHCPv4, and tracks the state of the DHCP FSM in `net_if_dhcpv4` instances in that list.

Neither the list nor the `net_if_dhcpv4` structures appear to have a defined locking regimen.  As these structures are manipulated by library code triggered by network events and application operations, and by the system work queue thread triggered by timeouts, locks are probably required.

Other interface structures from `<net/net_if.h>` may similarly require some sort of protection.

### PR DESCRIPTION
**Pull request by jukkar**
Add locking when accessing interface list and the DHCPv4 config
struct that is found in net_if.

Fixes #33348

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Review by pabigot — CHANGES_REQUESTED** [review]
This protects the list, but doesn't protect all code paths that manipulate the state in individual interface objects.  See #33389 for one trace that appears to require an additional lock placement.

If that's the only one it can be fixed by that PR.

**Comment by jukkar** [comment]
> doesn't protect all code paths that manipulate the state in individual interface objects

Could you elaborate more what you meant here? Did you meant the lock in `net_dhcpv4_input()` that you added in #33389, or was there still more issues. I am asking because I did not spot any in this PR (not to say there isn't any).

**Comment by pabigot** [comment]
> Could you elaborate more what you meant here? Did you meant the lock in `net_dhcpv4_input()` that you added in #33389, or was there still more issues. I am asking because I did not spot any in this PR (not to say there isn't any).

I only found that one, which as you pointed out actually was protected.  Without documentation on where locks need to be taken or are already held it's hard to tell what's supposed to be safe to call in what context.  But I didn't see any other failure points (but I didn't look closely).

**Review by pabigot — APPROVED** [review]
Seems OK.

**Comment by jukkar** [comment]
After re-reviewing the PR, I spotted one place which could have locks (in `net_dhcpv4_input()` between lines 1043-1059). I will revisit this PR for a new version).

**Pull request merged**
