### PR TITLE
drivers: ethernet: add PTP_clock for SOC_SERIES_STM32F4X

### PR DESCRIPTION
**Pull request by Desvauxm-st**
add PTP_clock for SOC_SERIES_STM32F4X

### CODE REVIEW

**Comment by Desvauxm-st** [comment]
@mariopaja
could you check this PR please.

**Comment by mariopaja** [comment]
> @mariopaja could you check this PR please.

@Desvauxm-st I noticed that I dont have the board with me :/ . I will be able to test it by the end of next week

**Comment by Desvauxm-st** [comment]
OK thanks you

**Comment by mariopaja** [comment]
@Desvauxm-st I just tested the change and it is not working for me.

**Test case:**
Sample: gPTP
Peer-to-Peer connection between **Nucleo F429ZI** and **MIMXRT1064 EVK**. 

Problem: 
I get the following warning:
`<wrn> net_gptp: Not AS capable: 4294967295 ns > 100000 ns`

[nucleo_f429zi_net_tap.zip](https://github.com/zephyrproject-rtos/zephyr/files/13949887/nucleo_f429zi_net_tap.zip)


**Nucleo F429ZI**:
```
net gptp 1
Port id    : 1 (DISABLED)
Interface  : 0x200013a8 [1]
Clock id   : 00:80:e1:ff:fe:55:38:4c
Version    : 2
AS capable : no

Configuration:
Time synchronization and Best Master Selection enabled        : yes
The port is measuring the path delay                          : yes
One way propagation time on the link attached to this port    : 4294967295 ns
Propagation time threshold for the link attached to this port : 100000 ns
Estimate of the ratio of the frequency with the peer          : 0
Asymmetry on the link relative to the grand master time base  : 0
Maximum interval between sync messages                        : 10000000
Maximum number of Path Delay Requests without a response      : 3
Current Sync sequence id for this port                        : 62821
Current Path Delay Request sequence id for this port          : 32610
Current Announce sequence id for this port                    : 10678
Current Signaling sequence id for this port                   : 72
Whether neighborRateRatio needs to be computed for this port  : yes
Whether neighborPropDelay needs to be computed for this port  : yes
Initial Announce Interval as a Logarithm to base 2            : 0
Current Announce Interval as a Logarithm to base 2            : 0
Initial Sync Interval as a Logarithm to base 2                : -4
Current Sync Interval as a Logarithm to base 2                : -4
Initial Path Delay Request Interval as a Logarithm to base 2  : 0
Current Path Delay Request Interval as a Logarithm to base 2  : 0
Time without receiving announce messages before running BMCA  : 1 ms (3)
Time without receiving sync messages before running BMCA      : 0 ms (3)
Sync event transmission interval for the port                 : 62 ms
Path Delay Request transmission interval for the port         : 1000 ms
BMCA default priority1                                        : 248
BMCA default priority2                                        : 248

Runtime status:
Current global port state                                : DISABLED
Path Delay Request state machine variables:
        Current state                                    : WAIT_ITV_TIMER
        Initial Path Delay Response Peer Timestamp       : 52068997600
        Initial Path Delay Response Ingress Timestamp    : 117820320000000052
        Path Delay Response messages received            : 1
        Path Delay Follow Up messages received           : 1
        Number of lost Path Delay Responses              : 0
        Timer expired send a new Path Delay Request      : 0
        NeighborRateRatio has been computed successfully : 1
        Path Delay has already been computed after init  : 0
        Count consecutive reqs with multiple responses   : 0
Path Delay Response state machine variables:
        Current state                                    : INITIAL_WAIT_REQ
SyncReceive state machine variables:
        Current state                                    : DISCARD
        A Sync Message has been received                 : no
        A Follow Up Message has been received            : no
        A Follow Up Message timeout                      : no
        Time at which a Sync Message without Follow Up
                                     will be discarded   : 0
SyncSend state machine variables:
        Current state                                    : INITIALIZING
        A MDSyncSend structure has been received         : no
        The timestamp for the sync msg has been received : no
PortSyncSyncReceive state machine variables:
        Current state                                    : DISCARD
        Grand Master / Local Clock frequency ratio       : 0.000000
        A MDSyncReceive struct is ready to be processed  : no
        Expiry of SyncReceiptTimeoutTimer                : no
PortSyncSyncSend state machine variables:
        Current state                                    : TRANSMIT_INIT
        Follow Up Correction Field of last recv PSS      : 0
        Upstream Tx Time of the last recv PortSyncSync   : 0
        Rate Ratio of the last received PortSyncSync     : 0.000000
        GM Freq Change of the last received PortSyncSync : 0.000000
        GM Time Base Indicator of last recv PortSyncSync : 0
        Received Port Number of last recv PortSyncSync   : 0
        PortSyncSync structure is ready to be processed  : no
        Flag when the half_sync_itv_timer has expired    : no
        Has half_sync_itv_timer expired twice            : no
        Has syncReceiptTimeoutTime expired               : no
PortAnnounceReceive state machine variables:
        Current state                                    : RECEIVE
        An announce message is ready to be processed     : no
PortAnnounceInformation state machine variables:
        Current state                                    : POST_DISABLED
        Expired announce information                     : yes
PortAnnounceTransmit state machine variables:
        Current state                                    : POST_IDLE
        Trigger announce information                     : no

Statistics:
Sync messages received                 : 405
Follow Up messages received            : 50
Path Delay Request messages received   : 400
Path Delay Response messages received  : 50
Path Delay messages threshold exceeded : 49
Path Delay Follow Up messages received : 50
Announce messages received             : 51
ptp messages discarded                 : 0
Sync reception timeout                 : 0
Announce reception timeout             : 0
Path Delay Requests without a response : 3
Sync messages sent                     : 0
Follow Up messages sent                : 0
Path Delay Request messages sent       : 53
Path Delay Response messages sent      : 401
Path Delay Response FUP messages sent  : 401
Announce messages sent                 : 0
```
**MIMXRT1064 EVK**:
```
net gptp 1
Port id    : 1 (MASTER)
Interface  : 0x800012e0 [1]
Clock id   : 02:04:9f:ff:fe:a1:25:26
Version    : 2
AS capable : yes

Configuration:
Time synchronization and Best Master Selection enabled        : yes
The port is measuring the path delay                          : yes
One way propagation time on the link attached to this port    : 0 ns
Propagation time threshold for the link attached to this port : 1000000 ns
Estimate of the ratio of the frequency with the peer          : 1
Asymmetry on the link relative to the grand master time base  : 0
Maximum interval between sync messages                        : 10000000
Maximum number of Path Delay Requests without a response      : 3
Current Sync sequence id for this port                        : 23843
Current Path Delay Request sequence id for this port          : 19820
Current Announce sequence id for this port                    : 15190
Current Signaling sequence id for this port                   : 22317
Whether neighborRateRatio needs to be computed for this port  : yes
Whether neighborPropDelay needs to be computed for this port  : yes
Initial Announce Interval as a Logarithm to base 2            : 0
Current Announce Interval as a Logarithm to base 2            : 0
Initial Sync Interval as a Logarithm to base 2                : -4
Current Sync Interval as a Logarithm to base 2                : -4
Initial Path Delay Request Interval as a Logarithm to base 2  : -3
Current Path Delay Request Interval as a Logarithm to base 2  : -3
Time without receiving announce messages before running BMCA  : 1 ms (3)
Time without receiving sync messages before running BMCA      : 0 ms (3)
Sync event transmission interval for the port                 : 62 ms
Path Delay Request transmission interval for the port         : 125 ms
BMCA default priority1                                        : 100
BMCA default priority2                                        : 248

Runtime status:
Current global port state                                : MASTER
Path Delay Request state machine variables:
        Current state                                    : WAIT_ITV_TIMER
        Initial Path Delay Response Peer Timestamp       : 35905868440
        Initial Path Delay Response Ingress Timestamp    : 35857122480
        Path Delay Response messages received            : 1
        Path Delay Follow Up messages received           : 1
        Number of lost Path Delay Responses              : 0
        Timer expired send a new Path Delay Request      : 0
        NeighborRateRatio has been computed successfully : 1
        Path Delay has already been computed after init  : 0
        Count consecutive reqs with multiple responses   : 0
Path Delay Response state machine variables:
        Current state                                    : INITIAL_WAIT_REQ
SyncReceive state machine variables:
        Current state                                    : DISCARD
        A Sync Message has been received                 : no
        A Follow Up Message has been received            : no
        A Follow Up Message timeout                      : no
        Time at which a Sync Message without Follow Up
                                     will be discarded   : 0
SyncSend state machine variables:
        Current state                                    : SEND_SYNC
        A MDSyncSend structure has been received         : no
        The timestamp for the sync msg has been received : no
PortSyncSyncReceive state machine variables:
        Current state                                    : DISCARD
        Grand Master / Local Clock frequency ratio       : 0.000000
        A MDSyncReceive struct is ready to be processed  : no
        Expiry of SyncReceiptTimeoutTimer                : no
PortSyncSyncSend state machine variables:
        Current state                                    : SYNC_RECEIPT_TIMEOUT
        Follow Up Correction Field of last recv PSS      : 0
        Upstream Tx Time of the last recv PortSyncSync   : 35999245400
        Rate Ratio of the last received PortSyncSync     : 0.000000
        GM Freq Change of the last received PortSyncSync : 0.000000
        GM Time Base Indicator of last recv PortSyncSync : 0
        Received Port Number of last recv PortSyncSync   : 0
        PortSyncSync structure is ready to be processed  : no
        Flag when the half_sync_itv_timer has expired    : yes
        Has half_sync_itv_timer expired twice            : no
        Has syncReceiptTimeoutTime expired               : yes
PortAnnounceReceive state machine variables:
        Current state                                    : RECEIVE
        An announce message is ready to be processed     : no
PortAnnounceInformation state machine variables:
        Current state                                    : CURRENT
        Expired announce information                     : yes
PortAnnounceTransmit state machine variables:
        Current state                                    : POST_IDLE
        Trigger announce information                     : no

Statistics:
Sync messages received                 : 0
Follow Up messages received            : 270
Path Delay Request messages received   : 35
Path Delay Response messages received  : 270
Path Delay messages threshold exceeded : 0
Path Delay Follow Up messages received : 270
Announce messages received             : 0
ptp messages discarded                 : 0
Sync reception timeout                 : 272
Announce reception timeout             : 0
Path Delay Requests without a response : 16
Sync messages sent                     : 273
Follow Up messages sent                : 273
Path Delay Request messages sent       : 286
Path Delay Response messages sent      : 35
Path Delay Response FUP messages sent  : 34
Announce messages sent                 : 34
```


PS: I can also later the week test it with a Nucleo H745ZI-Q board and compare the results.

**Comment by Desvauxm-st** [comment]
@mariopaja
in fact we faced last year with the STMH7xx serie with the same issue you found.
we add changed the code like that:
into stm32cube/stm32h5xx/drivers/src/stm32h5xx_hal_eth.c
fix to the HAL_API_V2 to get PTP to work in STM32H5 #62800
to resume it is these modifications:

image

image

I try to do the same for STM32F4xx  serie but i m not sure at all.
could you check with these modifications in 
modules\hal\stm32\stm32cube\stm32f4xx\drivers\src\stm32f4xx_hal_eth.c
see the file after:
[stm32f4xx_hal_eth.zip](https://github.com/zephyrproject-rtos/zephyr/files/13977373/stm32f4xx_hal_eth.zip)

the modifications is like that:


image

and:
image


can you try that or try to change the line 1140 with the previous on 
in fact I don't known if we must use to check timestamp available even the bit 
TSSTU or TSARU bit in  PTPTSCR register .

**Comment by mariopaja** [comment]
@Desvauxm-st 
Are you using the same prj.conf for both boards but just changing the IP address?

**Comment by Desvauxm-st** [comment]
@mariopaja
I use the last prj.conf only for nucleo_f429zi ( with the ip inverted )
for the nucleo_h753zi i use the previous prj.conf

**Comment by mariopaja** [comment]
@Desvauxm-st 

I was not able to replicate your results just by changing the **prj.conf**.

However I replaced the following [lines](https://github.com/zephyrproject-rtos/zephyr/blob/129b73ce266e1eabc518333b38d2971c207685fa/subsys/net/l2/ethernet/gptp/gptp_md.c#L381C1-L392C3 ):

```
	if ((port_ds->neighbor_prop_delay <=
	     port_ds->neighbor_prop_delay_thresh)) {
		port_ds->as_capable = true;
	} else {
		port_ds->as_capable = false;

		NET_WARN("Not AS capable: %u ns > %u ns",
			 (uint32_t)port_ds->neighbor_prop_delay,
			 (uint32_t)port_ds->neighbor_prop_delay_thresh);

		GPTP_STATS_INC(port, neighbor_prop_delay_exceeded);
	}
```

with

`port_ds->as_capable = true;`

And the board was immediatelly recognised as master.
I did the change because I noticed that **CONFIG_NET_GPTP_NEIGHBOR_PROP_DELAY_THR** was not setting the  value that was defined in pro.conf. 

Additionally, it was fulfilling the **<=** criteria but it was always assigned false and then assigned as **Not AS capable**

```
[00:08:40.713,000] <inf> net_gptp: neighbor_prop_delay: 4294967295 n
[00:08:40.713,000] <inf> net_gptp: neighbor_prop_delay_thresh: 4294967295 n
```


**STM32H745ZI-Q**
```
uart:~$ net gptp 1
Port id    : 1 (SLAVE)
Interface  : 0x240013c8 [1]
Clock id   : 00:80:e1:ff:fe:75:ca:99
Version    : 2
AS capable : yes

Configuration:
Time synchronization and Best Master Selection enabled        : yes
The port is measuring the path delay                          : yes
One way propagation time on the link attached to this port    : 0 ns
Propagation time threshold for the link attached to this port : 100000 ns
Estimate of the ratio of the frequency with the peer          : 1
Asymmetry on the link relative to the grand master time base  : 0
Maximum interval between sync messages                        : 375000000
Maximum number of Path Delay Requests without a response      : 3
Current Sync sequence id for this port                        : 32945
Current Path Delay Request sequence id for this port          : 49891
Current Announce sequence id for this port                    : 31848
Current Signaling sequence id for this port                   : 17679
Whether neighborRateRatio needs to be computed for this port  : yes
Whether neighborPropDelay needs to be computed for this port  : yes
Initial Announce Interval as a Logarithm to base 2            : 0
Current Announce Interval as a Logarithm to base 2            : 0
Initial Sync Interval as a Logarithm to base 2                : -4
Current Sync Interval as a Logarithm to base 2                : -4
Initial Path Delay Request Interval as a Logarithm to base 2  : 0
Current Path Delay Request Interval as a Logarithm to base 2  : 0
Time without receiving announce messages before running BMCA  : 3000 ms (3)
Time without receiving sync messages before running BMCA      : 0 ms (3)
Sync event transmission interval for the port                 : 62 ms
Path Delay Request transmission interval for the port         : 1000 ms
BMCA default priority1                                        : 248
BMCA default priority2                                        : 248

Runtime status:
Current global port state                                : SLAVE
Path Delay Request state machine variables:
        Current state                                    : WAIT_ITV_TIMER
        Initial Path Delay Response Peer Timestamp       : 414435216
        Initial Path Delay Response Ingress Timestamp    : 2855063935

```

**STM32F429ZI**
```
net gptp 1
Port id    : 1 (MASTER)
Interface  : 0x200013d0 [1]
Clock id   : 00:80:e1:ff:fe:55:38:4c
Version    : 2
AS capable : yes

Configuration:
Time synchronization and Best Master Selection enabled        : yes
The port is measuring the path delay                          : yes
One way propagation time on the link attached to this port    : 4294967295 ns
Propagation time threshold for the link attached to this port : 4294967295 ns
Estimate of the ratio of the frequency with the peer          : 4294967295
Asymmetry on the link relative to the grand master time base  : 0
Maximum interval between sync messages                        : 1250000000
Maximum number of Path Delay Requests without a response      : 3
Current Sync sequence id for this port                        : 39729
Current Path Delay Request sequence id for this port          : 9263
Current Announce sequence id for this port                    : 3052
Current Signaling sequence id for this port                   : 18228
Whether neighborRateRatio needs to be computed for this port  : yes
Whether neighborPropDelay needs to be computed for this port  : yes
Initial Announce Interval as a Logarithm to base 2            : 0
Current Announce Interval as a Logarithm to base 2            : 0
Initial Sync Interval as a Logarithm to base 2                : -4
Current Sync Interval as a Logarithm to base 2                : -4
Initial Path Delay Request Interval as a Logarithm to base 2  : 0
Current Path Delay Request Interval as a Logarithm to base 2  : 0
Time without receiving announce messages before running BMCA  : 1 ms (10)
Time without receiving sync messages before running BMCA      : 0 ms (10)
Sync event transmission interval for the port                 : 62 ms
Path Delay Request transmission interval for the port         : 1000 ms
BMCA default priority1                                        : 248
BMCA default priority2                                        : 248

```

**Pull request closed without merging**
