### PR TITLE
tests: kernel: workq: update for removal of deprecated API

### LINKED ISSUE #34105: Convert tests/kernel/workq to new kwork API
Convert tests/kernel/workq/critical/src/main.c & tests/kernel/workq/work_queue/src/main.c to use new kwork API.

See the following issue for details:

#33104

### PR DESCRIPTION
**Pull request by pabigot**
Remove a test that's dedicated to using the legacy API, and remove from the replacement test all verification specific to the deprecated API.

Fixes #34105 but really those tests ought to remain in tree until the deprecated API has been removed.  An alternative solution is present in #32888.

### CODE REVIEW

**Comment by galak** [comment]
@pabigot will you update this to get merged or should I take over this PR?  Happy to handle it either way, as we are getting close to having all in-tree users converted over.

**Comment by pabigot** [comment]
@galak IIRC this is not necessary until the old k_work API is actually removed.  The intent in #32888 is to allows it to remain in place and tested until then, while not causing CI failures due to the deprecations.

**Comment by carlescufi** [comment]
@pabigot should we close this now?

**Comment by pabigot** [comment]
No, it should go out of draft and be merged when the deprecated API is removed.  Presumably that will be for 2.9.

**Pull request closed without merging**
