### PR TITLE
can: cast value 1U to type ULL in function can_stm32_set_filter

### PR DESCRIPTION
**Pull request by maxxlife**
Potentially overflowing expression 1U << register_demand
changed to the 1ULL << register_demand to avoid overflow.

Coverity-CID: 190996
Fixes: #13829

Signed-off-by: Maksim Masalski <maxxliferobot@gmail.com>

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by alexanderwachter** [comment]
Thanks for fixing! Alternatively 1ULL would do the same.

**Comment by maxxlife** [comment]
Do you think that it is better to use 1ULL?
Maybe performance will be better.

**Comment by alexanderwachter** [comment]
1ULL is definitely shorter and used for constants :-)

**Comment by maxxlife** [comment]
Ok. Will change it. I checked another codes right now, it seems ULL is
better for that case.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by alexanderwachter — APPROVED** [review]

**Pull request merged**
