### PR TITLE
RISC-V: Add NEORV32 SoC support

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
This PR adds basic Zephyr support for the NEORV32 RISC-V SoC.

More information about the NEORV32 can be obtained here:
* GitHub: https://github.com/stnolting/neorv32
* Datasheet: https://stnolting.github.io/neorv32/
* User Guide: https://stnolting.github.io/neorv32/ug/

The implementation passes the full suite of applicable test cases and samples as selected by `twister`.

### CODE REVIEW

**Review by fkokosinski — COMMENTED** [review]
Hi, I've been trying to use the Tcl script located in `setups/vivado/arty-a7-test-setup` in the repository you've linked above to test this port on HW, but it seems to be referencing non-declared variables (such as `$fileset_neorv32`), and non-existing board part (at least on my Vivado 2020.2). Could you point me to a script that would allow me to build this setup? This would be also beneficial to add to the board documentation in Zephyr.

**Comment by henrikbrixandersen** [comment]
> Hi, I've been trying to use the Tcl script located in `setups/vivado/arty-a7-test-setup` in the repository you've linked above to test this port on HW, but it seems to be referencing non-declared variables (such as `$fileset_neorv32`), and non-existing board part (at least on my Vivado 2020.2). Could you point me to a script that would allow me to build this setup? This would be also beneficial to add to the board documentation in Zephyr.

I have just submitted a PR against the NEORV32 project for fixing the `setups/vivado/arty-a7-test-setup` example: https://github.com/stnolting/neorv32/pull/175

With this PR in, I was able to synthesise and implement the upstream example design using Xilinx Vivado 2020.02.

I have also submitted a PR for hinting at installing board support files:
https://github.com/stnolting/neorv32/pull/174

The Zephyr board documentation refers to the excellent upstream documentation for instructions on how to synthesise, implement, and load the NEORV32 FPGA designs. Any questions or generic NEORV32 documentation fixes are better addressed there.

**Review by nandojve — CHANGES_REQUESTED** [review]
Hi @henrikbrixandersen ,
Very interesting. Just couple questions.

**Review by katsuster — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@nandojve Was your request for changes addressed?

**Review by nandojve — APPROVED** [review]
Yes, thank you for your contribution.

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
