### PR TITLE
scripts/Kconfig: Add dt_node_has_prop Kconfig function

### PR DESCRIPTION
**Pull request by erwango**
Add dt_node_has_prop function to query the presence of 'prop'
for given node label.

Cf use in https://github.com/zephyrproject-rtos/zephyr/pull/30864

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Can you implement both this and dt_node_has_bool_prop using a single function instead of copy/pasting? Similar to how dt_node_reg_size_int and dt_node_reg_size_hex are both implemented using dt_node_reg.

**Comment by erwango** [comment]
> Can you implement both this and dt_node_has_bool_prop using a single function instead of copy/pasting? Similar to how dt_node_reg_size_int and dt_node_reg_size_hex are both implemented using dt_node_reg.

@mbolivar dt_node_has_bool_prop takes a 'path', while this function takes a 'label'. Do you want me to change this as well ?

**Comment by erwango** [comment]
@mbolivar-nordic This patch has been merged as is as part of https://github.com/zephyrproject-rtos/zephyr/pull/30864 (I probably didn't advertised enough this late dependency)
Though, it is not too late to fix as per your request, if you could answer previous comment (I guess with the correct @nickname will work better)

**Comment by mbolivar-nordic** [comment]
> `dt_node_has_bool_prop` takes a 'path', while this function takes a 'label'. Do you want me to change this as well ?

Heh, yes, I didn't notice that on my first review, but it's a good reason to do it in terms of existing code.

The name `dt_node_has_prop` is not a good one then, IMO. It should be `dt_nodelabel_has_prop`; notice other functions like `dt_nodelabel_has_compat`.

Can you please send a follow-up making `dt_node_has_prop` and if necessary `dt_nodelabel_has_prop`?

**Pull request closed without merging**
