### PR TITLE
doc: net: Hide UDP API documentation

### PR DESCRIPTION
**Pull request by jukkar**
The UDP API functions are for Zephyr internal use only so do
not generate documentation for them.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by jukkar** [comment]
How this "hiding" should be done, sanity complains if I remove the file from toctree
`/var/lib/shippable/build/IN/main_repo/zephyr/doc/_build/rst/doc/reference/networking/udp.rst: WARNING: document isn't included in any toctree`

**Comment by nashif** [comment]
> How this "hiding" should be done, sanity complains if I remove the file from toctree
> `/var/lib/shippable/build/IN/main_repo/zephyr/doc/_build/rst/doc/reference/networking/udp.rst: WARNING: document isn't included in any toctree`

you need to remove the file or orphan it

**Review by pfalcon — APPROVED** [review]
By reading a title of "hiding UDP API" I was alerted, but turns out, merely a coulpe of UDP header helper functions are being hidden.

Well, I don't ask to title here to be rewritten, but please let me use exact, precise titles (that's re: https://github.com/zephyrproject-rtos/zephyr/pull/13528).

**Review by dbkinder — CHANGES_REQUESTED** [review]
Since you've removed the doxygen comments (via @cond), you'll need to delete ``udp.rst`` as well since it's trying to reference the udp doxygen group you just removed. (That will make the doc gen errors go away.)  Adding an :orphan: tag will make the toctree complaint go away but not the doxygen reference error.)

**Comment by jukkar** [comment]
Removed udp.rst file.

**Review by dbkinder — APPROVED** [review]

**Pull request merged**
