### PR TITLE
drivers: gpio: nrfx: fix lost level interrupts

### LINKED ISSUE #11806: gpio_nrf mishandles level interrupts
For in-work enhancements to sensors I have a Thingy:52 (nrf52_pca20020) application that uses triggers to capture data from three environmental sensors at a fairly high rate.  At random points the sensor callbacks will stop being invoked, even though the data-ready signals are properly asserted.

Through previous experience I knew that this occurs when clearing the PORT event is not properly synchronized with a reliable deassert of the DETECT signal.  This is the case for the Zephyr implementation of the GPIOTE interrupt handler.

If an external device causes a level change at [this point in the code](https://github.com/zephyrproject-rtos/zephyr/blob/e9364d52fea305bad3a87c4864c223858be1bf36/drivers/gpio/gpio_nrfx.c#L406) the computed value of `active_level_triggers` will be stale, and if it is zero the ISR will clear the PORT event even when DETECT has just been asserted.  Since event generation requires a rising edge the presence of unhandled SENSE signals will not be signaled and processing will stop.

The requirement to ensure DETECT is deasserted before clearing PORT is described in a comment in [this devzone thread](https://devzone.nordicsemi.com/f/nordic-q-a/7246/missing-interrupts-on-gpioe-port-events).  The only mechanism sufficient to confirm a deasserted DETECT is disabling all GPIO SENSE configurations across all GPIO peripheral instances.  SENSE configurations should be re-enabled after all callbacks have completed; this will generate a new PORT event if level criteria are still met.

### PR DESCRIPTION
**Pull request by pabigot**
Nordic devices detect edge interrupts through the PORT event which is
generated on a rising edge of DETECT, which itself is asserted when any
GPIO is configured for sense level detection and the GPIO's input signal
matches the configuration.

The previous code in Zephyr attempts to detect when at least one GPIO
SENSE signal is still asserted, and intentionally leaves the PORT event
uncleared to ensure the interrupt is re-entered.

This approach fails when no pin satisfies its SENSE condition during the
check but at least one input changes level between the completion of the
check and the clear of the PORT event.  Such a failure can be observed
on the pca20020 hardware when multiple sensors configured for level
triggers are active.  In this situation the corresponding sensor trigger
signals remain asserted but the PORT event required to drive their
processing has already been cleared.

The fix is to ensure that the SENSE configuration for all GPIOs across
all port instances is disabled prior to unconditionally clearing the
PORT event, then re-enabling the SENSE configuration for all GPIOs once
callbacks associated with detected SENSE triggers have been performed.
The act of re-enabling will ensure any relevant SENSE condition causes a
new rising edge on DETECT and so a new PORT event.

Fixes #11806

See: https://devzone.nordicsemi.com/f/nordic-q-a/7246/missing-interrupts-on-gpioe-port-events

Signed-off-by: Peter A. Bigot <pab@pabigot.com>

### CODE REVIEW

**Comment by carlescufi** [comment]
@pabigot thanks for the PR!
Note: if you write `Fixes #11806` instead of `Closes issues #11806` (I reworded it now) then the issue will automatically get closed when this PR is merged

**Comment by pabigot** [comment]
@carlescufi thanks; I never remember the exact syntax github wants.  I'll correct the commit message if the PR is approved with modifications.

**Comment by JoeHut** [comment]
The issue description looks very much like it would fix #10034 as well. I will try it out.

**Review by Mierunski — APPROVED** [review]
LGTM

**Review by anangl — APPROVED** [review]
Great job!

**Pull request merged**
