### PR TITLE
doc: drop usage of numfig/numref

### PR DESCRIPTION
**Pull request by gmarull**
Usage of numfig=True option in conf.py significantly increases doc build time. While it is a nice feature, it's not extensively used in Zephyr documentation, so let's remove its usage in favor of faster doc builds.

TODO: compare build times (cold/incremental)

### CODE REVIEW

**Review by marc-hb — APPROVED** [review]
Thanks for doing this! This must have been quite tedious but will be very useful.

> TODO: compare build times (cold/incremental)

Some numbers posted in #55708

**Comment by marc-hb** [comment]
https://github.com/zephyrproject-rtos/zephyr/actions/runs/4631147648/jobs/8193645328?pr=56631 still takes 11.5 min which is disappointing; no major speed up. Compared to #55708 it is still running `breathe` though - and of course it is from scratch which is not the most important use case from a performance perspective.

Or maybe `numfig` fixed its performance issues?

**Comment by gmarull** [comment]
> https://github.com/zephyrproject-rtos/zephyr/actions/runs/4631147648/jobs/8193645328?pr=56631 still takes 11.5 min which is disappointing; no major speed up. Compared to #55708 it is still running `breathe` though - and of course it is from scratch which is not the most important use case from a performance perspective.
> 
> Or maybe `numfig` fixed its performance issues?

With the numbers we have, there's not enough evidence that removing numfig has a positive performance impact. I'll close this for now.

**Comment by marc-hb** [comment]
What (new?) numbers do you have? The only number I've seen for **incremental build** (the only build that matters in this case) is the one I posted in #55708 and the difference was huge.

**Comment by marc-hb** [comment]
Resubmitted in
- #57624

**Pull request closed without merging**
