### PR TITLE
west.yml: update hal_atmel to include qdec SAME70b fix

### LINKED ISSUE #65432: qdec in same70q21b not compiling, however in same70q21 works
It looks like there is an issue with using the QDEC in **same70q21b** vs **same70q21**.

When compiling with enabled `sam-qdec` I get an issue in that file:
[drivers/sensor/qdec_sam/qdec_sam.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/qdec_sam/qdec_sam.c)

missing definition of `TC_CMR_ETRGEDG_NONE`

```
.../zephyr/drivers/sensor/qdec_sam/qdec_sam.c: In function 'qdec_sam_configure':
.../zephyr/drivers/sensor/qdec_sam/qdec_sam.c:90:27: error: 'TC_CMR_ETRGEDG_NONE' undeclared (first use in this function); did you mean 'TC_CMR_ETRGEDG_Pos'?
   90 |                         | TC_CMR_ETRGEDG_NONE

```

this definition is present in:

[asf/sam/include/same70/component/tc.h](https://github.com/zephyrproject-rtos/hal_atmel/blob/master/asf/sam/include/same70/same70q21.h)

but **not** present in:
[asf/sam/include/same70b/component/tc.h](https://github.com/zephyrproject-rtos/hal_atmel/blob/master/asf/sam/include/same70b/same70q21b.h)

steps to reproduce
cmake
`-DBOARD=sam_e70b_xplained` (**fails**)  vs `-DBOARD=sam_e70_xplained` (**works**)

dt
```
&tc0 {
	status = "okay";
	compatible = "atmel,sam-tc-qdec";

	pinctrl-0 = <&tc0_qdec_default>;
	pinctrl-names = "default";
	label = "QDEC_0";
};
```
conf
```
# quadrature decoder
CONFIG_SENSOR=y
CONFIG_QDEC_SAM=y

```
from the datasheet, I dont see any difference between both revision regarding qdec:
image

I suggest to copy paste from 
`same70/same70q21.h`
to
`same70b/same70q21b.h`

### PR DESCRIPTION
**Pull request by tswaehn**
This update fixes the qdec in SAME70b, which could not be compiled prior to this fix, due to missing TC_CMR definitions. Moreover it fixes #65432.

### CODE REVIEW

**Comment by tswaehn** [comment]
I am wondering if that should go to 3.5 branch as it is a fix.

**Comment by tswaehn** [comment]
@nandojve I don't see my changes as reason for the tests to fail. Can we restart the tests?

**Comment by tswaehn** [comment]
ok. actually it looks like that warnings will be turned into errors. which is ok. it also looks like that due to copy paste I did copy a little too much, as there come definitions from the deprecated module. so changed it to only add exclusively the missing defines.

**Comment by nandojve** [comment]
Update the PR with newest hash from hal_atmel.

**Comment by tswaehn** [comment]
updated west.yml with the merged [hal_atmel commit hash](https://github.com/zephyrproject-rtos/hal_atmel/commit/aad79bf530b69b72712d18873df4120ad052d921)

and also cherry-picked from PR #65611 to this PR with the commit msg mentioning the corresponding issue.

**Review by nandojve — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Pull request merged**
