### PR TITLE
Dma stm32 fix

### PR DESCRIPTION
**Pull request by avisconti**
(FIX for STM32 DMA)
I noticed that the STM32 DMA is not used much inside zephyr, expecially the memory-to-peripheral and peripherl-to-memory part. I'm currently implementing the stm32-i2s driver and I'm using the DMA for that purpose. My intention is to use it also inside SPI driver and maybe others.

### CODE REVIEW

**Comment by SebastianBoe** [comment]
recheck

**Comment by avisconti** [comment]
@SebastianBoe 
same (or similar) error

**Comment by avisconti** [comment]
Ok, sanitycheck is passed and bug has been closed. If it happens again I will re-open it.

**Comment by avisconti** [comment]
@erwango 
Pls add who else is needed for the review of this part. I noticed that Lee Jones (Linaro) has done some work in the past on stm32 DMA.

**Review by erwango — COMMENTED** [review]
LGTM, Can you confirm that tests/drivers/dma is still 'passed' with this change?
(requires to change DMA_DEVICE_NAME to "DMA_2")

**Comment by erwango** [comment]
@avisconti :
Test is not in CI, You have to run the test manually
Go in tests/drivers/dma/loop_transfer
Make the change to "DMA_2"
Build vs a target supporting dma, then flash and run the test, and you will have the verdict.

Then (if you're interested), maybe would be worth to get some STM32 targets running this test in CI, btw...

**Comment by avisconti** [comment]
@erwango 
> Test is not in CI, You have to run the test manually

OK, got it.

> Go in tests/drivers/dma/loop_transfer
> Make the change to "DMA_2"
> Build vs a target supporting dma, then flash and run the test, and you will have the verdict.

I had also to add in prj.conf the following
  CONFIG_DMA_STM32F4X=y

After that I launched the test on my ArgonKey and it worked:

***** Booting Zephyr OS v1.12.0-453-g286bd85 *****
DMA memory to memory transfer started on DMA_2
Preparing DMA Controller
Starting the transfer and waiting for 1 second
Each RX buffer should contain the full TX buffer string.
TX data: The quick brown fox jumps over the lazy dog
RX data Loop 0: The quick brown fox jumps over the lazy dog
RX data Loop 1: The quick brown fox jumps over the lazy dog
RX data Loop 2: The quick brown fox jumps over the lazy dog
RX data Loop 3: The quick brown fox jumps over the lazy dog
RX data Loop 4: The quick brown fox jumps over the lazy dog
Finished: DMA

**Comment by avisconti** [comment]
@erwango 
Pls note that the DMA loop transfer test does only memory to memory transfers, while my modifications are more concerned with mem-to-periph and periph-to-mem. But it is good to see that my coomts didn't break the functionality.

To test the changes I use the I2S driver I'm writing and tested it on ArgonKey. I tested it in both directions using I2S RX (from Microphone) and I2S TX on 96 board connector watching the transactions with a scope.

**Comment by avisconti** [comment]
@erwango 
Is this patch fine for you then? As you see above the dma test pass as expected.

**Review by erwango — APPROVED** [review]

**Pull request merged**
