### PR TITLE
LwM2M: fix float32/64 handling + timer obj

### PR DESCRIPTION
**Pull request by mike-scott**
- Since adding to Zephyr, float32 has only sent whole value (dropping decimal) and float64 was completely broken.  Let's fix that.
- Let's add support for the IPSO Timer object which uses float values extensively
- Add Timer object to sample
- Adjust dummy temp sensor in sample to display a decimal value

### CODE REVIEW

**Comment by mike-scott** [comment]
Fixed checkpatch complaint

**Comment by mike-scott** [comment]
Fixed up dates to correct patch ordering

**Comment by mike-scott** [comment]
Adding due to interest in LwM2M client in the past:
@arn-soft @therealprof rbtchc

**Comment by mike-scott** [comment]
Hm.. DO NOT MERGE.  Found a bug with very small numbers.

**Comment by mike-scott** [comment]
Ok, negative exponent handling for the binary32/binary64 formats is fixed.

Please review.

**Comment by mike-scott** [comment]
Woops fixing checkpatch / style issues.

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by mike-scott** [comment]
1 small bug fix for float32 -> binary32 conversion

```
diff --git a/subsys/net/lib/lwm2m/lwm2m_util.c b/subsys/net/lib/lwm2m/lwm2m_util.c
index 99b7244d84..4562a7ad5b 100644
--- a/subsys/net/lib/lwm2m/lwm2m_util.c
+++ b/subsys/net/lib/lwm2m/lwm2m_util.c
@@ -13,7 +13,7 @@
 /* convert from float32 to binary32 */
 int lwm2m_f32_to_b32(float32_value_t *f32, u8_t *b32, size_t len)
 {
-	s32_t e = 0, v, f = 0;
+	s32_t e = -1, v, f = 0;
 	int i;
 
 	if (len != 4) {
```

Basically the whole number was being doubled by accident.

**Pull request merged**
