### PR TITLE
samples: basic: Add overlay to support nRF54L15 PDK

### PR DESCRIPTION
**Pull request by kl-cruz**
Simple overlay configuration to support fade_led sample on nRF54L15 DK.

### CODE REVIEW

**Review by nika-nordic — APPROVED** [review]

**Review by kartben — COMMENTED** [review]
does this really need to be an overlay? No other Nordic board seems to be doing it that way, and instead has PWM leds configured in the main dts

**Comment by gmarull** [comment]
> does this really need to be an overlay? No other Nordic board seems to be doing it that way, and instead has PWM leds configured in the main dts

agreed

**Review by anangl — CHANGES_REQUESTED** [review]
> > does this really need to be an overlay? No other Nordic board seems to be doing it that way, and instead has PWM leds configured in the main dts
> 
> agreed

I also agree. Let's stay consistent with other Nordic boards and add this stuff in the board definition.

**Comment by kl-cruz** [comment]
Adressed in https://github.com/zephyrproject-rtos/zephyr/pull/72010

**Pull request closed without merging**
