### PR TITLE
drivers: pinmux: stm32: complete stm32f2 header

### PR DESCRIPTION
**Pull request by ibisz**
Complete and modify some USART/UART pin configurations.

Signed-off-by: Istvan Bisz <istvan.bisz@t-online.hu>

### CODE REVIEW

**Review by erwango — COMMENTED** [review]
Pins muxing part looks correct.

Can you elaborate on the change of configuration
RX/NOPULL TX/PULLUP?

**Comment by ibisz** [comment]
recheck

**Comment by erwango** [comment]
Ok, indeed this is a behavior we'll have to change one day by having the pin configuration called by IP drivers themselves, so they can do it at the right time. This will be easier to deploy once pinctrl configuration by dts is available.

I think this point is valid for other series as well. Could you extend it to whole STM32 family?

**Comment by erwango** [comment]
> OK, I will do it step by step, but not in this PR, I am now in a short vacation, sorry.

No problem, enjoy!

**Review by erwango — APPROVED** [review]

**Review by ydamigos — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
