### PR TITLE
tracing: add user event trace

### PR DESCRIPTION
**Pull request by danieldegrasse**
Add support for a "user event" trace. This trace is intentionally not
used by the system. The purpose of this trace is to allow driver or
application developers to quickly add tracing for events for debug
purposes, and to provide an example of how tracing subsystems can be
extended with additional trace identifiers.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@nashif please take a look

**Comment by nashif** [comment]
> @nashif please take a look

yep, looking at this.

**Comment by danieldegrasse** [comment]
Rebased to clear conflicts

**Comment by teburd** [comment]
I can see this being useful for quickly looking at some tracing points, but the reality is the string name here will limit how many points can be sent over a wire quickly I'd think, perhaps renaming this to NAMED_EVENT or so would be more apt, as users are welcome to add tracing points of their own with their own TIDs ideally.

**Comment by danieldegrasse** [comment]
> I can see this being useful for quickly looking at some tracing points, but the reality is the string name here will limit how many points can be sent over a wire quickly I'd think, perhaps renaming this to NAMED_EVENT or so would be more apt, as users are welcome to add tracing points of their own with their own TIDs ideally.

IE names like:
- `sys_trace_named_event`
- `CTF_EVENT_NAMED_EVENT`

I have no issue with this change- the primary goals here are to provide an example for users of how to extend tracing support, and to add a simple function to quickly extend tracing while debugging an issue

**Comment by danieldegrasse** [comment]
> > I can see this being useful for quickly looking at some tracing points, but the reality is the string name here will limit how many points can be sent over a wire quickly I'd think, perhaps renaming this to NAMED_EVENT or so would be more apt, as users are welcome to add tracing points of their own with their own TIDs ideally.
> 
> IE names like:
> 
>     * `sys_trace_named_event`
> 
>     * `CTF_EVENT_NAMED_EVENT`
> 
> 
> I have no issue with this change- the primary goals here are to provide an example for users of how to extend tracing support, and to add a simple function to quickly extend tracing while debugging an issue

@teburd wanted to clarify here, were you asking me to make this name change?

**Comment by teburd** [comment]
> > > I can see this being useful for quickly looking at some tracing points, but the reality is the string name here will limit how many points can be sent over a wire quickly I'd think, perhaps renaming this to NAMED_EVENT or so would be more apt, as users are welcome to add tracing points of their own with their own TIDs ideally.
> > 
> > 
> > IE names like:
> > ```
> > * `sys_trace_named_event`
> > 
> > * `CTF_EVENT_NAMED_EVENT`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have no issue with this change- the primary goals here are to provide an example for users of how to extend tracing support, and to add a simple function to quickly extend tracing while debugging an issue
> 
> @teburd wanted to clarify here, were you asking me to make this name change? Happy to do so if you are

It's not a blocker, but I do think the name would, at least for me, signal the right things better than the current user event naming.

**Comment by danieldegrasse** [comment]
> I leave it up to you @danieldegrasse as you are the author.

No problem with the name change- I've update the PR

**Review by teburd — APPROVED** [review]

**Comment by danieldegrasse** [comment]
@nashif could you take a look at this?

**Comment by nashif** [comment]
@danieldegrasse  sorry about the delay, will do asap and in time for 4.0.0

**Review by nashif — APPROVED** [review]

**Pull request merged**
