### PR TITLE
net: app: allow IPv6 interface init to work with late IP assigment

### PR DESCRIPTION
**Pull request by mike-scott**
Some network interfaces such as bluetooth 6lowpan can start without
an assigned IP address and then later once the connection is up a
router advertisement broadcast will assign the IP address.

The net_app framework will timeout out during network init if a value
cannot be parsed from CONFIG_NET_APP_MY_IPV6_ADDR.  Let's adjust
the framework to handle a missing value there and fill it in later
when the IPv6 address is added to the interface.

Signed-off-by: Michael Scott <michael.scott@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
Does  this blend well with https://github.com/zephyrproject-rtos/zephyr/pull/979 ?

**Comment by mike-scott** [comment]
@pfalcon This shouldn't conflict w/ https://github.com/zephyrproject-rtos/zephyr/pull/979

**Review by Vudentz — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
Makes sense, +1

**Comment by pfalcon** [comment]
This patch broke static IPv6 assignment: https://jira.zephyrproject.org/browse/ZEP-2464

**Pull request merged**
