### PR TITLE
dts: stm32: convert SPI & USB DT_COMPAT usage to new macros

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by avisconti** [comment]
Is this one superseeded by #24593?

**Comment by galak** [comment]
> Is this one superseeded by #24593?

how ?  touching 2 different things.

**Comment by avisconti** [comment]
> > Is this one superseeded by #24593?
> 
> how ? touching 2 different things.

Sorry, I misread it

**Review by avisconti — APPROVED** [review]
LGTM

**Review by loicpoulain — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
