### PR TITLE
modules: Bump to mbedTLS to  3.3.0

### PR DESCRIPTION
**Pull request by ceolin**
Bump mbedTLS to the latest release.

### CODE REVIEW

**Comment by ceolin** [comment]
@microbuilder Kevin, can you check if tfm supports mbedtls 3.3.0 ? The version that we have contains old psa headers.
`psa/crypto_types.h` for example does not contain new types used in mbedTLS. 
There are probably other things I've missed :)

**Comment by joerchan** [comment]
@ceolin Current version of TF-M (1.6) is aligned with MBedTLS 3.1. The next version, (1.7) is aligned against MBedTLS 3.2.

Updating to 3.3 is likely to fail at this point, we have been following the TF-M specified version lately.
Is there a specific reason for going to the 3.3 version?

**Comment by microbuilder** [comment]
> @microbuilder Kevin, can you check if tfm supports mbedtls 3.3.0 ? The version that we have contains old psa headers. `psa/crypto_types.h` for example does not contain new types used in mbedTLS. There are probably other things I've missed :)

I'll have to test and see if this fails against TF-M 1.6 (MbedTLS 3.1) or TF-M 1.7 (MbedTLS 3.2). Nordic also has a lot of samples that depends on TF-M, but I see @joerchan already noticed this PR.

**Comment by microbuilder** [comment]
I did a quick test with a more complex app we have in house, pointing to the MbedTLS PR in my Zephyr manifest, and adding the following to my config file:

```yaml
CONFIG_MBEDTLS_ENTROPY_ENABLED=y
CONFIG_MBEDTLS_CTR_DRBG_ENABLED=y
CONFIG_MBEDTLS_PSA_CRYPTO_C=y
```

I had to install `jsonschema` via `pip`, but then builiding the sample, linking fails against the PSA APIs in the secure environment and MbedTLS: 

```
...
/Users/kevintownsend/zephyr-sdk-0.15.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../../../../arm-zephyr-eabi/bin/ld.bfd: modules/trusted-firmware-m/libtfm_api.a(tfm_crypto_ipc_api.c.obj): in function `psa_key_derivation_setup':
/Users/kevintownsend/Linaro/zephyr/applications/zephyr_confidential_ai/build/tfm/install/interface/src/tfm_crypto_ipc_api.c:1720: multiple definition of `psa_key_derivation_setup'; modules/mbedtls/libmodules__mbedtls.a(psa_crypto.c.obj):/Users/kevintownsend/Linaro/zephyr/modules/crypto/mbedtls/library/psa_crypto.c:5183: first defined here
...
```

I disabled the `CONFIG_MBEDTLS_PSA_CRYPTO_C=y` config flag, and the sample compiles, but I see some warnings in the log during a TLS connection which I'll need to explore:

```
Generating X.509 CSR for 'Device Client TLS' key:
Subject: O=Linaro,CN=45b51869-8132-4e15-b780-288d521a5078,OU=Device Client TLS
cert starts at 0x2e2 into buffer
[00:00:16.876,000] <inf> app: Got DNS for linaroca
[00:00:16.891,000] <err> mbedtls: ssl_client.c:0261: got supported group(001d)
[00:00:16.891,000] <err> mbedtls: ssl_client.c:0261: got supported group(0017)
[00:00:16.891,000] <err> mbedtls: ssl_client.c:0261: got supported group(0018)
[00:00:16.891,000] <err> mbedtls: ssl_client.c:0261: got supported group(001e)
[00:00:16.891,000] <err> mbedtls: ssl_client.c:0261: got supported group(0019)
[00:00:16.891,000] <err> mbedtls: ssl_client.c:0261: got supported group(001a)
--- 1 messages dropped ---
[00:00:17.284,000] <inf> app: Response to req
[00:00:17.284,000] <inf> app: Status OK
```

TLS does still work, though, and the PSA Crypto API seems OK on the S side when I run a secure service:

```
uart:~$ infer get utvm_sine SIGN1 1.5
Start: 1.50 End: 1.50 stride: 1.00
[UTVM SERVICE] Starting secure inferencing
[UTVM SERVICE] Starting CBOR/COSE encoding
SIGN1 encoded inference value:
00000000: d2 84 43 a1 01 26 a0 58  1f a3 3a 00 01 38 7f 44 |..C..&.X ..:..8.D|
00000010: 80 a9 62 3d 3a 00 01 38  84 44 00 00 00 00 3a 00 |..b=:..8 .D....:.|
00000020: 01 38 85 44 01 00 00 00  58 40 59 23 3e 80 5e e0 |.8.D.... X@Y#>.^.|
00000030: 9f fa e3 f4 14 62 d3 15  a5 b0 95 b5 e5 cb 79 92 |.....b.. ......y.|
00000040: f8 f1 a0 fe 14 0c 6c 84  2a 41 41 2e bf 7f ed 27 |......l. *AA....'|
00000050: 02 0d eb 5a 2a 05 fd 70  33 8b 16 ad 69 e2 5d bf |...Z*..p 3...i.].|
00000060: 4a b0 3f 05 cd b9 f1 93  9c 7c                   |J.?..... .|      |
Model: Sine of 1.50 deg is: 0.055337
C Mathlib: Sine of 1.50 deg is: 0.026177
Deviation: 0.942158
```

This /might/ still be OK to update to MbedTLS 3.3 on the NS side, but until TF-M also uses 3.3 and do some PSA cleanup we won't be able to enable `CONFIG_MBEDTLS_PSA_CRYPTO_C`, but I really need to do some more digging here as well.

@joerchan Flavio, David and myself have a call at 17:00 CET (I think same as Norway) to discuss this. I'll add you to the invite, but if that's too late on a Friday, no worries.

**Comment by microbuilder** [comment]
Just as another datapoint, TF-M 1.7.0, which is what we'll update to soon-ish, uses MbedTLS 3.2.1: https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/config/config_base.cmake?h=TF-Mv1.7.0#n124

**Comment by ceolin** [comment]
@microbuilder As we have discussed. I've created a pr using mbedTLS 3.2.1 https://github.com/zephyrproject-rtos/zephyr/pull/53685

**Comment by ceolin** [comment]
I'm closing it to avoid confusion with the 3.2.1 pr.  Feel free to re-open if if you want.

**Pull request closed without merging**
