### PR TITLE
aarch64: mmu: don't touch the lock before the MMU is on

### PR DESCRIPTION
**Pull request by npitre**
We can't do atomic memory operations before the MMU is on. Let's create
a code path to set up MMU page tables without any lock. There is
obviously no concurrency issues at this stage.

Signed-off-by: Nicolas Pitre <npitre@baylibre.com>

### CODE REVIEW

**Comment by npitre** [comment]
This should solve #33515 reported by @luisgerhorst

**Review by carlocaione — APPROVED** [review]

**Comment by npitre** [comment]
Ping. This needs reviews.

Without this, Zephyr won't boot on real hardware.

**Comment by carlocaione** [comment]
@nashif @ioannisg can you ACK and merge this? This is pretty high priority. Having two reviewers for the AArch64 stuff seems an impossible task.

**Comment by carlocaione** [comment]
@npitre can you rebase this?

**Review by nashif — APPROVED** [review]

**Pull request merged**
