### PR TITLE
boards: beagle_bcf: Fix undefined references to pinctrl and gpio device

### LINKED ISSUE #56181: drivers.flash.default unit test doesn't build for beagleconnect_freedom
**Describe the bug**
In #52980, `drivers.flash.common.default` unit test [fails](https://github.com/zephyrproject-rtos/zephyr/pull/52980/checks?check_run_id=12225244478) to build for `beagleconnect_freedom` with following message:
```
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map 
: && ccache /opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc  -gdwarf-4 zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr_pre0.elf  -fuse-ld=bfd  -Wl,-T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map=/__w/zephyr/zephyr/twister-out/beagleconnect_freedom/tests/drivers/flash/common/drivers.flash.common.default/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/arm/core/aarch32/libarch__arm__core__aarch32.a  zephyr/arch/arch/arm/core/aarch32/cortex_m/libarch__arm__core__aarch32__cortex_m.a  zephyr/arch/arch/arm/core/aarch32/mpu/libarch__arm__core__aarch32__mpu.a  zephyr/lib/libc/minimal/liblib__libc__minimal.a  zephyr/soc/arm/common/cortex_m/libsoc__arm__common__cortex_m.a  zephyr/boards/arm/beagle_bcf/libboards__arm__beagle_bcf.a  zephyr/subsys/testsuite/ztest/libsubsys__testsuite__ztest.a  zephyr/drivers/flash/libdrivers__flash.a  zephyr/drivers/spi/libdrivers__spi.a  zephyr/drivers/timer/libdrivers__timer.a  modules/ti/simplelink/source/ti/devices/cc13x2x7_cc26x2x7/lib..__modules__hal__ti__simplelink__source__ti__devices__cc13x2x7_cc26x2x7.a  modules/ti/simplelink/lib..__modules__hal__ti__simplelink.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  zephyr/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -L"/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/thumb/v7e-m/nofp"  -L/__w/zephyr/zephyr/twister-out/beagleconnect_freedom/tests/drivers/flash/common/drivers.flash.common.default/zephyr  -lgcc  zephyr/arch/common/libisr_tables.a  -Wl,--fatal-warnings  -no-pie  -mcpu=cortex-m4  -mthumb  -mabi=aapcs  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn && cd /__w/zephyr/zephyr/twister-out/beagleconnect_freedom/tests/drivers/flash/common/drivers.flash.common.default/zephyr && /usr/local/bin/cmake -E echo
/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/flash/libdrivers__flash.a(spi_nor.c.obj):(.data.__compound_literal.0+0x0): undefined reference to `__device_dts_ord_13'
/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/spi/libdrivers__spi.a(spi_cc13xx_cc26xx.c.obj): in function `pinctrl_apply_state':
/__w/zephyr/zephyr/twister-out/beagleconnect_freedom/tests/drivers/flash/common/drivers.flash.common.default/../../../../../../../include/zephyr/drivers/pinctrl.h:348: undefined reference to `pinctrl_lookup_state'
/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/spi/libdrivers__spi.a(spi_cc13xx_cc26xx.c.obj): in function `pinctrl_apply_state_direct':
/__w/zephyr/zephyr/twister-out/beagleconnect_freedom/tests/drivers/flash/common/drivers.flash.common.default/../../../../../../../include/zephyr/drivers/pinctrl.h:329: undefined reference to `pinctrl_configure_pins'
/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/spi/libdrivers__spi.a(spi_cc13xx_cc26xx.c.obj):(.rodata.__compound_literal.0+0x0): undefined reference to `__device_dts_ord_13'
/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/spi/libdrivers__spi.a(spi_cc13xx_cc26xx.c.obj):(.rodata.__compound_literal.0+0x8): undefined reference to `__device_dts_ord_13'
/opt/toolchains/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/spi/libdrivers__spi.a(spi_cc13xx_cc26xx.c.obj):(.rodata.__compound_literal.0+0x10): undefined reference to `__device_dts_ord_13'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
The problem seems to be unrelated to the PR.

**To Reproduce**
Build `driver.flash.common.default` for `beagleconnect_freedom`

**Expected behavior**
Test builds successfully.

**Impact**
No one wants to merge PR when unit test doesn't build.

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Zephyr CI
 - #52980 PR

**Additional context**
Test `drivers.flash.default` was moved and renamed to `drivers.flash.common.default` in the PR.

### PR DESCRIPTION
**Pull request by duda-patryk**
This patch fixes undefined references when compiling tests/drivers/flash for beagleconnect_freedom board using following command:

west build -b beagleconnect_freedom tests/drivers/flash

Adding CONFIG_PINCTRL fixes undefined references to 'pinctrl_lookup_state' and 'pinctrl_configure_pins'.

Adding CONFIG_GPIO fixes undefined reference to '__device_dts_ord_13' from spi_nor and spi_cc13xx_cc26xx drivers.

Fixes #56181

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
CC: @jadonk

**Comment by jadonk** [comment]
I tried to minimize the configs, but wasn't sure what should be included. What is the norm?

**Comment by jadonk** [comment]
So, right way is *not* with a boards config file? How much *should* I turn on?

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
> I tried to minimize the configs, but wasn't sure what should be included. What is the norm?

@jadonk https://docs.zephyrproject.org/latest/hardware/porting/board_porting.html#general-recommendations

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
