### PR TITLE
samples: modules: nanopb: Showcase configuring options

### PR DESCRIPTION
**Pull request by pdgendt**
The latest version of nanopb allows for using kconfig symbols in files with an `options.in` extension.

See https://github.com/nanopb/nanopb/pull/936

### CODE REVIEW

**Review by kartben — CHANGES_REQUESTED** [review]
I think it would make sense to add some blurb to the README to briefly explain this new options.in mechanism?

**Comment by pdgendt** [comment]
> I think it would make sense to add some blurb to the README to briefly explain this new options.in mechanism?

@kartben I've restructured the documentation a bit, I hope this makes it clearer.

**Review by kartben — COMMENTED** [review]
Brilliant! 
Please check my comment re: paragraph formatting -- looks very good otherwise!

**Review by cfriedt — DISMISSED** [review]
LGTM - would it be OK if I made an entry for Thrift under serialization too?

**Comment by kartben** [comment]
> LGTM - would it be OK if I made an entry for Thrift under serialization too?

Please!

**Review by kartben — DISMISSED** [review]

**Comment by pdgendt** [comment]
Updated module SHA @kartben @cfriedt 

> > LGTM - would it be OK if I made an entry for Thrift under serialization too?
> 
> Please!

That's the idea, the same would apply for `zcbor` for example.

**Review by kartben — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
