### PR TITLE
drivers: counter: nrfx: Add option to call handlers in ZLI interrupts

### PR DESCRIPTION
**Pull request by nordic-krch**
Add device tree option to enforce that counter (TIMER, RTC) uses ZLI interrupt.

Updated test to validate that configuration. Since test was using semaphores in the counter event handler it had to be updated to use uint variables instead when ZLI is enabled. Added configuration for nrf52840dk to run the test with ZLI feature enabled.

DNM since it is based on #32568.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
The devicetree bits feel like software configuration and thus seem like they should be in Kconfig and not devicetree.

**Comment by mbolivar-nordic** [comment]
> The devicetree bits feel like software configuration and thus seem like they should be in Kconfig and not devicetree.

Agreed.

**Comment by nordic-krch** [comment]
sure, can move it there. On the other hand, zli is kind of interrupt priority level and that one is in device tree.

**Comment by nordic-krch** [comment]
moved configuration to Kconfig. Keep it in separate commits for now, will squeeze later.

**Comment by mbolivar-nordic** [comment]
> zli is kind of interrupt priority level and that one is in device tree.

Are the ZLI interrupt priorities different than the priorities specified in the DT? That would seem to cover 'boot time configuration' then and be an argument for putting it into DT, but I wonder if the existing interrupts property isn't enough then.

**Comment by nordic-krch** [comment]
> Are the ZLI interrupt priorities different than the priorities specified in the DT?

Yes. When interrupt is configured as ZLI then priority is overridden to 0 (the highest) and priority property is not used.

**Comment by nordic-krch** [comment]
@galak @mbolivar-nordic so is there a consensus? can this option stay in device tree as it sets interrupt priority level for the driver?

**Comment by mbolivar-nordic** [comment]
I defer to @galak -- since he already said it belongs in Kconfig I have no objections.

**Comment by nordic-krch** [comment]
ZLI option in Kconfig.

**Comment by nordic-krch** [comment]
@galak @anangl can you review?

**Comment by nordic-krch** [comment]
@galak @anangl  ping

**Review by anangl — APPROVED** [review]
LGTM

**Comment by nordic-krch** [comment]
@mbolivar-nordic @galak  I have second thoughts regarding zli configuration in Kconfig. I'm working on adding busy simulator (random cpu load used for tests) on top of a counter instance. It will be changing priority of counter interrupt to the highest but some tests will require busy simulator running in zli. It will be a bit messy with zli configuration in kconfig and interrupt level configuration in overlay. It seems cleaner to have something like:

```
&timer0 {
    interrupts = <13 0>;
    /* use-zli; */
    busy_sim: zephyr-busy-sim {
        ...
    };
};
```

Then additionally adding `CONFIG_COUNTER_TIMER0_ZLI=y` to kconfig and have to update both when changing counter instance.

**Comment by nordic-krch** [comment]
@mbolivar-nordic @galak any thoughts?

**Comment by nordic-krch** [comment]
@galak can you finish review?

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic @galak any thoughts?

Maybe `zephyr,use-zli` instead?

**Comment by nordic-krch** [comment]
> Maybe zephyr,use-zli instead?

@galak ?

**Comment by nordic-krch** [comment]
@galak you've been blocking this PR for very long time without any response. Can you comment or withdraw?

**Comment by mbolivar-nordic** [comment]
> @galak you've been blocking this PR for very long time without any response. Can you comment or withdraw?

Added to dev-review. @nordic-krch -- this is always available as an option to get things prioritized

**Review by galak — APPROVED** [review]

**Review by galak — COMMENTED** [review]
I didn't mean to approve, but was trying to clear my dis-approval since the current code doesn't introduce any devicetree properties.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
