### PR TITLE
drivers: ieee802154: nrf5: fix handling multiple CCA

### PR DESCRIPTION
**Pull request by edmont**
Fix a couple of bugs introduced with last commits related to multiple CCA support.

### CODE REVIEW

**Comment by edmont** [comment]
CC: @ankuns

**Review by rlubos — DISMISSED** [review]
A pity that went unnoticed through review/CI. This made me wonder, perhaps we should have another build variant in https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/build_all/ieee802154/testcase.yaml#L15, which enables all of the driver features?

**Comment by edmont** [comment]
> A pity that went unnoticed through review/CI. This made me wonder, perhaps we should have another build variant in https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/build_all/ieee802154/testcase.yaml#L15, which enables all of the driver features?

That wouldn't have helped in this case since the code within `#if defined(IEEE...` would be simply been ignored by the compiler.

**Review by LuDuda — APPROVED** [review]
Good catch!

**Comment by fgrandel** [comment]
> A pity that went unnoticed through review/CI.

It goes a bit in the direction that @ssharks also mentioned: The nRF5 Zephyr driver wrapper does not have unit/integration tests right now. A unit test strategy would also have helped me quite a bit wrt the timing refactorings. Probably some kind of mocking strategy for the underlying driver would be required to catch things like these as you can then observe the missing effect similarly to how we mock the IEEE 802.15.4 driver API for L2 unit/integration tests.

**Review by ghost — DISMISSED** [review]

**Review by jciupis — DISMISSED** [review]

**Comment by edmont** [comment]
Sorry, there was still some build warning in `nrf5_attr_get`.

**Review by rlubos — DISMISSED** [review]

**Review by ghost — APPROVED** [review]

**Review by jciupis — APPROVED** [review]

**Pull request merged**
