### PR TITLE
usb_device: Fix typo in comment

### LINKED ISSUE #16223: stm32: Unable to send 64 byte packet over control endpoint
**Describe the bug**
cdc_acm_composite does not work on olimexino_stm32. Reverting commit e5cbe6a9e7 (usb: cdc: Add unique PIDs for each sample) fixes the problem.

 
**To Reproduce**

1. compile ```subsys/usb/cdc_acm_composite``` sample
```
cd samples/subsys/usb/cdc_acm_composite
rm -rf build && mkdir build && cd build
cmake -DBOARD=olimexino_stm32  ..
make
```
2. burn zephyr image into olimexino_stm32;
3. connect olimexino_stm32 to linux host via USB;
4. reset olimexino_stm32;
5. No ```/dev/ttyACMx``` device registered on linux host.
See ```dmesg``` output on linux host (some details may vary):
```
usb 2-1.1: new full-speed USB device number 102 using ehci-pci
usb 2-1.1: New USB device found, idVendor=2fe3, idProduct=0002, bcdDevice= 0.11
usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 2-1.1: can't set config #1, error -32
```

**Expected behavior**
Registering two new ```/dev/ttyACMx``` devices is expected on linux host.
Expected ```dmesg``` output on linux host (some details may vary):
```
usb 2-1.1: new full-speed USB device number 101 using ehci-pci
usb 2-1.1: New USB device found, idVendor=2fe3, idProduct=0100, bcdDevice= 0.11
usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 2-1.1: Product: Zephyr CDC ACM sample
usb 2-1.1: Manufacturer: ZEPHYR
usb 2-1.1: SerialNumber: 0.01
cdc_acm 2-1.1:1.0: ttyACM0: USB ACM device
cdc_acm 2-1.1:1.2: ttyACM1: USB ACM device
```

**Environment (please complete the following information):**

USB Host OS: Debian Linux x86_64, kernel version 4.18.6-1
Toolchain: Zephyr SDK 0.10.0
Zephyr git describe: zephyr-v1.14.0-836-gfc3270d09c

### PR DESCRIPTION
**Pull request by ydamigos**
Fix typo in comment

Signed-off-by: Yannis Damigos <giannis.damigos@gmail.com>

### CODE REVIEW

**Comment by ydamigos** [comment]
Marked it as DNM until it is tested with more samples and other platforms.

**Comment by ydamigos** [comment]
@frantony Could you have a look?

**Comment by jfischer-phytec-iot** [comment]
DNM scares reviewers

**Review by jfischer-no — CHANGES_REQUESTED** [review]
It does not look wrong, block it until it has been extensively tested.

**Review by masz-nordic — DISMISSED** [review]
This introduces regression for `nrf52840_pca10056` - the issue with 64B descriptor not being handled properly.

To reproduce, modify `prj.conf` from hid example to:
```
CONFIG_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_COMPOSITE_DEVICE=y
CONFIG_USB_DEVICE_HID=y
CONFIG_ENABLE_HID_INT_OUT_EP=y
CONFIG_USB_DEVICE_PRODUCT="Zephyr HID sample"
CONFIG_USB_HID_BOOT_PROTOCOL=y

CONFIG_USB_MASS_STORAGE=y
CONFIG_USB_MASS_STORAGE_LOG_LEVEL_ERR=y
CONFIG_DISK_ACCESS_RAM=y
CONFIG_MASS_STORAGE_DISK_NAME="RAM"

CONFIG_LOG=y
CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
```

**Comment by ydamigos** [comment]
> This introduces regression for nrf52840_pca10056 - the issue with 64B descriptor not being handled properly.

@masz-nordic  Are we talking about patching `usb_dc_nrfx` driver to handle correctly a 64B descriptor? If yes, I don't have the hardware to do it and test it.

**Comment by jfischer-phytec-iot** [comment]
@masz-nordic Do you refer to commit 3c3e267d72d9f0329d17ecdc4c2277b3b4f44ada? But there is no special treatment for `usb_dc_nrfx` in IN endpoint processing. This patch should not cause any new problems on nRF platform. I tested it quickly with testusb and hid sample, works fine.

**Comment by masz-nordic** [comment]
@jfischer-phytec-iot On Windows 10?

**Comment by jfischer-phytec-iot** [comment]
>On Windows 10?

@masz-nordic Why should it depend on OS?  3c3e267 fixed a bug in the stack and is not specific to usb_dc_nrfx.

**Comment by frantony** [comment]
@ydamigos

> @frantony Could you have a look?

I have tested  your usb-device-zlp branch (c26e8c4e92c7f6a9081) on olimexino-stm32 board. The subsys/usb/cdc_acm_composite sample works perfectly.

**Comment by jfischer-phytec-iot** [comment]
@ydamigos rebase, please

**Comment by ydamigos** [comment]
Rebased to include only the typo fix as #18646 handles ZLP.

**Review by jfischer-no — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
