### PR TITLE
Bluetooth: CAP: Commander discovery support

### PR DESCRIPTION
**Pull request by Thalley**
Implement the CAP Commander discovery function.
    
Adds support for it in the shell.
    
This includes initial babblesim and unit testing as well.

### CODE REVIEW

**Review by kruithofa — DISMISSED** [review]

**Review by MariuszSkamra — DISMISSED** [review]
LGTM

**Comment by fabiobaltieri** [comment]
@Thalley this also needs a rebase :-)

**Comment by carlescufi** [comment]
@Thalley please rebase

**Comment by carlescufi** [comment]
@Thalley please rebase

**Review by MariuszSkamra — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]

**Pull request merged**
