### PR TITLE
Improve ROUND_UP and ROUND_DOWN macros

### PR DESCRIPTION
**Pull request by besmarsh**
This PR improves the utility macros `ROUND_UP` and `ROUND_DOWN` to work with alignments that are not a power of 2.

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Looks harmless, though I'm a little worried this will turn up in some oddball toolchain context where it's not correctly optimizing the divide to a mask operation.  Certainly the overwhelming majority of users (and all the current ones, of course) only care about power of two behavior; these are macros for alignment and padding as they exist today.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Failure is unrelated, old CI.

**Comment by besmarsh** [comment]
> Looks harmless, though I'm a little worried this will turn up in some oddball toolchain context where it's not correctly optimizing the divide to a mask operation. Certainly the overwhelming majority of users (and all the current ones, of course) only care about power of two behavior; these are macros for alignment and padding as they exist today.

There was an extensive discussion a little while ago about common utility macros like these and it was decided that Zephyr's definition should be *the* definition - they shouldn't be conditionally defined, redefined, namespaced etc. I believe part of the reasoning there was that in projects using Zephyr, Zephyr is the OS and should provide the definition of these common macros. I think a part of that should be making them useful and clear for application code - maybe they're only used within Zephyr for alignment and padding today, but with such common names and being accessible to application code, providing functionality that is more useful and may be expected is probably a good thing.

Anyway, thanks for the approvals and merge :)

**Comment by xyzzy42** [comment]
> Looks harmless, though I'm a little worried this will turn up in some oddball toolchain context where it's not correctly optimizing the divide to a mask operation. Certainly the overwhelming majority of users (and all the current ones, of course) only care about power of two behavior; these are macros for alignment and padding as they exist today.

This does indeed happen.  It's not so much a toolchain issue and more of a usage one.  Consider where `align` is not constant, but will be a power of 2.

```
lib/libc/common/source/stdlib/malloc.c:         heap_base = UINT_TO_POINTER(ROUND_UP(HEAP_BASE, heap_size));
lib/os/json.c:                  total += ROUND_UP(s, 1 << descr->align_shift);
subsys/bluetooth/mesh/shell/blob.c:     total_blocks = DIV_ROUND_UP(info->size, 1U << info->block_size_log);
subsys/bluetooth/mesh/blob_cli.c:               cli->block_count = DIV_ROUND_UP(cli->xfer->size, (1U << cli->xfer->block_size_log));
subsys/bluetooth/mesh/blob_cli.c:               DIV_ROUND_UP(cli->block.size, chunk_size);
lib/os/cbprintf_packaged.c:                     buf = (void *)ROUND_UP(buf, align);
kernel/mmu.c:                   *aligned_addr = ROUND_DOWN(addr, align);
```

Clang is able to optimize the calls of the `1U << align` form while gcc (AFAICT, all versions) can not.  Those like the calls in mmu.c where the argument is entirely unknown are of course impossible to optimize.

**Pull request merged**
