### PR TITLE
Adding more net_pkt write helpers

### PR DESCRIPTION
**Pull request by jukkar**
Noticed that we are missing some helpers while implementing ppp support.

### CODE REVIEW

**Comment by tbursztyka** [comment]
Is there any place where this could be useful?
I had these at first, and I removed it when posting the new API because there were no place that needed it.

**Comment by jukkar** [comment]
I needed these for ppp, but can live without them too. Actually it seems that currently my ppp patches are not using these right now. Anyway, these helpers do not make any harm so we could just have them even if no one is not currently using them. Currently very low priority.

**Comment by pfalcon** [comment]
Why this didn't get auto-reviewers assigned?

**Comment by pfalcon** [comment]
> Why this didn't get auto-reviewers assigned?

@nashif

**Comment by jukkar** [comment]
> Why this didn't get auto-reviewers assigned?

I am wondering this too, lately there have been several networking PRs where the review list has not been assigned at all.

**Comment by jukkar** [comment]
These functions are already merged as part of other PRs.

**Pull request closed without merging**
