### PR TITLE
IPv6 privacy extension support

### PR DESCRIPTION
**Pull request by jukkar**
This PR implements [RFC 4941](https://tools.ietf.org/html/rfc4941)

### CODE REVIEW

**Comment by nashif** [comment]
status of this one? is it going to be updated and be ready for review? should it be closed?

**Comment by jukkar** [comment]
This feature needs some pondering what to do when the IP address, that the application is using, changes.

**Comment by jukkar** [comment]
Fixed merge conflicts.

**Comment by jukkar** [comment]
Storing this to https://github.com/jukkar/zephyr/pull/20 as this is probably not going to be merged any time soon.

**Pull request closed without merging**
