### PR TITLE
tests: kernel: fpu_sharing: fix double-promotions

### PR DESCRIPTION
**Pull request by XenuIsWatching**
Double promotion warnings are generated with the flag -Wdouble-promotion

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
No reason not to -1, but this looks like a broken warning to me.

The idea behind -Wdouble-promotion is to warn you when math on your float value is going to be done in double precision (e.g. software-emulated).  Here, it's being passed in the varargs list to a declared function with a printf format attribute (it's literally printf()!) and matched against a "%f" specifier, which **requires** that its argument be passed as a double at the ABI level.

The automatic promotion is correct; the warning is wrong.  Basically: this looks like a toolchain bug to me.  AFAICT, this warning isn't being enabled anywhere internal to the Zephyr tree.  Not personally a fan of taking code, no matter how trivial, to work around toolchain bugs elsewhere.

**Comment by XenuIsWatching** [comment]
> No reason not to -1, but this looks like a broken warning to me.
> 
> The idea behind -Wdouble-promotion is to warn you when math on your float value is going to be done in double precision (e.g. software-emulated). Here, it's being passed in the varargs list to a declared function with a printf format attribute (it's literally printf()!) and matched against a "%f" specifier, which **requires** that its argument be passed as a double at the ABI level.
> 
> The automatic promotion is correct; the warning is wrong. Basically: this looks like a toolchain bug to me. AFAICT, this warning isn't being enabled anywhere internal to the Zephyr tree. Not personally a fan of taking code, no matter how trivial, to work around toolchain bugs elsewhere.

This is trying to go within Zephyr see: https://github.com/zephyrproject-rtos/zephyr/pull/57154 . Just too many times people have pushed up and merged in issues where floats magically become doubles and nobody knows about it... but in order for this to go in, we've gotta get the warnings fixed throughout the CI builds including this one.

That is not a toolchain bug nor a broken warning there.... that float is being promoted to a double there and IIRC will even start to compile in the compiler libraries for double precision if there is no DPFPU

**Comment by XenuIsWatching** [comment]
I'm thinking something like this may be cleaner...
```
#ifdef CONFIG_CPU_HAS_FPU_DOUBLE_PRECISION
#define FP_CONSTANT(x)   x##f
#else
#define FP_CONSTANT(x)   x
#endif
```

**Comment by cfriedt** [comment]
> No reason not to -1, but this looks like a broken warning to me.
> 
> The idea behind -Wdouble-promotion is to warn you when math on your float value is going to be done in double precision (e.g. software-emulated). 

Some platforms only have 32-bit HW floating point capabilities. In some cases using SW emulation and linking the vast kB associated with emulation code (I'm being facetious) can be prohibitively expensive.. (I'm sure there is a use case for that, maybe). Really though, real-time motor control or something like that might be an actual use case.

Anyway... inside of this test file, in particular, I think we could get away with far fewer `#ifdef`s by typedefing either `double` or `float` in file scope and using the `FP_CONSTANT(x)` Ryan mentioned above. The only scenario where that may be tricky are specific NaNs or values that are out of range / precision for `float`.

**Review by cfriedt — APPROVED** [review]

**Comment by andyross** [comment]
> That is not a toolchain bug nor a broken warning there.... that float is being promoted to a double there

Meh.  It's being promoted to a double in a context where it **must** be promoted to a double though.  There are no (standard) ways to printf() a 32 bit float.  Float values in varargs context must be passed as doubles per the langauge standard.  Warning about it is just wrong, and the cast adds nothing but source code bytes.

As stated though, not a -1.  Surely the warning has value in other contexts, it just cheeses me off that the toolchain didn't get the edge cases right, and makes me worry that there are other such slip-ups we'll be dealing with.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
