### PR TITLE
scripts: set_assignee: add options to assign module PRs and issues

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Add a -m option to set_assignees to have the script find all unassigned module PRs for areas that have an assignee and set the assignee on those PRs.

This should help avoiding forgotten PRs on modules. It's implemented as a search and meant to run periodically, so we don't have to add a workflow for this on every individual module.

### CODE REVIEW

**Comment by nashif** [comment]
nice, let me play with this a bit...

**Comment by fabiobaltieri** [comment]
> nice, let me play with this a bit...

Sure thing, been testing with `./scripts/set_assignees.py -v --dry-run -m`

**Comment by fabiobaltieri** [comment]
@henrikbrixandersen https://github.com/zephyrproject-rtos/zephyr/pull/61513/commits/faa59883456c1b6415836990c92162c103360816

```
$ ./scripts/set_assignees.py -v --dry-run -I 61751
Working on https://api.github.com/repos/zephyrproject-rtos/zephyr/issues/61751: test issue
Found labels: [Label(name="Enhancement"), Label(name="area: Input")]
Found Label(name="area: Input") maintainers: {'fabiobaltieri'}
Adding fabiobaltieri to https://github.com/zephyrproject-rtos/zephyr/issues/61751
```

**Comment by fabiobaltieri** [comment]
Updates:
- added an issue assigner mode
-  change the CI patch to handle both modules and issues, but only enable issue for now, the scheduler/module part is commented out

**Comment by nashif** [comment]
what about issues with an excessive amount of labels set? will this be assigned to all maintainers of the areas that are labeled?

**Comment by nashif** [comment]
well, we have too many labels and until we clean those up we will be dealing with excpetions more than rules.
IMO assigning multiple people is a no-go, we probably want to just assign to the first match and wish for the best.

**Comment by fabiobaltieri** [comment]
> well, we have too many labels and until we clean those up we will be dealing with excpetions more than rules. IMO assigning multiple people is a no-go, we probably want to just assign to the first match and wish for the best.

Ah it's not too bad, so I did some change and I'm now doing a scond pass when building the `label_to_maintainer` map so that areas with multiple labels where one of the label is unique are also mapped so I can match for an individual label or for the whole set, for bluetooth it looks something like this:

```
             ('area: bluetooth',): {'jhedberg'},
             ('area: bluetooth', 'area: bluetooth controller'): {'cvinayak'},
             ('area: bluetooth', 'area: bluetooth host'): {'jhedberg'},
             ('area: bluetooth controller',): {'cvinayak'}, <- from the second pass
             ('area: bluetooth host',): {'jhedberg'}, <- from the second pass
```

Then I'm discarding all labels not mentioned in maintainer and doing the matching for all labels in the issue, this some sample run:

- only input:
```
$ ./scripts/set_assignees.py -v --dry-run -I 61751
Working on https://api.github.com/repos/zephyrproject-rtos/zephyr/issues/61751: test issue
Ignoring label: Label(name="Enhancement")
Using labels: ('area: input',)
Adding fabiobaltieri to https://github.com/zephyrproject-rtos/zephyr/issues/61751
```

- only bluetooth:
```
$ ./scripts/set_assignees.py -v --dry-run -I 61751
Working on https://api.github.com/repos/zephyrproject-rtos/zephyr/issues/61751: test issue
Ignoring label: Label(name="Enhancement")
Using labels: ('area: bluetooth',)
Adding jhedberg to https://github.com/zephyrproject-rtos/zephyr/issues/61751
```

- bluetooth and controller (maps directly to an area)
```
$ ./scripts/set_assignees.py -v --dry-run -I 61751
Working on https://api.github.com/repos/zephyrproject-rtos/zephyr/issues/61751: test issue
Ignoring label: Label(name="Enhancement")
Using labels: ('area: bluetooth', 'area: bluetooth controller')
Adding cvinayak to https://github.com/zephyrproject-rtos/zephyr/issues/61751
```

- just controller (does not map directly to an area but only an area has it)
```
$ ./scripts/set_assignees.py -v --dry-run -I 61751
Working on https://api.github.com/repos/zephyrproject-rtos/zephyr/issues/61751: test issue
Ignoring label: Label(name="Enhancement")
Using labels: ('area: bluetooth controller',)
Adding cvinayak to https://github.com/zephyrproject-rtos/zephyr/issues/61751
```

- input and bluetooth
```
$ ./scripts/set_assignees.py -v --dry-run -I 61751
Working on https://api.github.com/repos/zephyrproject-rtos/zephyr/issues/61751: test issue
Ignoring label: Label(name="Enhancement")
Using labels: ('area: bluetooth', 'area: input')
no match for the label set, not assigning
```

So now if the issue has multiple labels (that are mentioned in areas) they have to be an exact match or no one gets assigned, but if you only have one label it's going to find something even if the area has multiple labels. To state the obvious if we start having more complex label overlap cases in the maintainer file this would start picking just one somewhat randomly, but for the current setup of <broad label> <specific label> it should work fine.

**Review by nashif — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
LGTM, thanks!

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
