### PR TITLE
subsys/bluetooth/controller/ll_sw: Refactored llcp_rec test to helper function

### PR DESCRIPTION
**Pull request by alexsven**
@cvinayak @carlescufi 
Here is the refactoring of the req/ack into helper functions. Don't know who to copy in this PR

### CODE REVIEW

**Comment by carlescufi** [comment]
@alexsven Thanks! please use `Bluetooth: controller: <>` as the commit summary line and fix the identity issues.

**Comment by carlescufi** [comment]
@alexsven for the next time: you don't need to close the PR. You amend the commit and then `git push -f` to your branch.

**Comment by alexsven** [comment]
Noted, I also see that in the new PR some other persons work has snuck in. If I delete the files in the PR, via GITHub, are they removed from my PR?

**Comment by aescolar** [comment]
The PR reflects the content of the branch you have used to create the PR (in your clone of Zephyr = https://github.com/alexsven/zephyr )
That branch being https://github.com/alexsven/zephyr/commits/BLE-SPLIT_move_reck_ack_to_helper_functions
If you "fix" that branch locally and push the changes to the server, the PR will be automatically updated.

**Pull request closed without merging**
