### PR TITLE
make find_package(Zephyr...) REQUIRED

### PR DESCRIPTION
**Pull request by marc-hb**
... because it is (required).

This makes a difference when building with CMake and forgetting
ZEPHYR_BASE or not registering Zephyr in the CMake package registry.

In this particular case, REQUIRED turns this harmless looking log
statement:
```
-- Could NOT find Zephyr (missing: Zephyr_DIR)
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- ...
-- ...
-- ...
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:8 (target_sources):
  Cannot specify sources for target "app" which is not built by
  this project.
```
... into this louder, clearer, faster and (last but not least) final
error:
```
CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a package configuration file provided by "Zephyr" with
  any of the following names:

    ZephyrConfig.cmake
    zephyr-config.cmake

  Add the installation prefix of "Zephyr" to CMAKE_PREFIX_PATH or set
  "Zephyr_DIR" to a directory containing one of the above files.  If
  "Zephyr" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
```

### CODE REVIEW

**Review by tejlmand — APPROVED** [review]
Thanks for this.
That should of course have been part of the introduction of this feature.

**Review by vanwinkeljan — APPROVED** [review]

**Comment by tejlmand** [comment]
Note: The CI will fail due to timeout because of amount of projects touched.
@nashif @carlescufi This is safe to merged, even if CI times out.

**Review by carlescufi — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by carlescufi** [comment]
This is timing out on CI. I am merging this since the changes are extremely well localized (i.e. same line changed over and over) and thus I see no potential for interaction with anything else.

**Comment by nashif** [comment]
wow, that was a very quick turnaround for a PR changing over 500 files 1 week before a release...

**Comment by pfalcon** [comment]
> wow, that was a very quick turnaround for a PR changing over 500 files 1 week before a release...

+1. I wonder how those 500 lines were verified for containing "extremely well localized" changes. I may imagine following process: independent party (from the original submitter) wrote a script which performed verification. Then another independent party verified that the script is correct.

But don't listen to me - just merge one of my next patches (of my choosing) in the same way :-D.

**Comment by marc-hb** [comment]
For the record I didn't realize it was only 1 week before release when I submitted this. I also didn't care at all whether it would be merged before or after release. Sorry for not paying attention to the release cycle.

I obviously didn't type these changes, they were performed by a one-line script[*] _and_ the result was carefully  reviewed line by line by me and I'm pretty sure by other reviewers. Doing such a throrough review is actually very easy and very quick if you try because it's 500 times the exact same, **one-word** and obviously very low risk change. The human vision is very good at detecting irregularities. Just try it: open the "Changes" tab and scroll down, you'll see how little time it takes. Even faster with the `git show HEAD~x` commands that I used.

By now I probably spent almost as much time writing and proof-reading this comment as very carefully reviewing this PR, so I'm going to stop, sorry for any typos left in the comment :-)

[*] I considered adding a new "layer of indirection" to have all `find_package` options in one place and avoid the duplication but AFAIU `find_package` is the "bootstrap" command so I don't think it is possible.

>  just merge one of my next patches (of my choosing) in the same way :-D.

I'm afraid one line of C code can have much wider ranging and subtle or even "undefined" consequences than one extra keyword in a plain CMake command. The number of lines matters but it's not everything.

**Comment by tejlmand** [comment]
> > wow, that was a very quick turnaround for a PR changing over 500 files 1 week before a release...
> 
> +1. I wonder how those 500 lines were verified for containing "extremely well localized" changes. I may imagine following process: independent party (from the original submitter) wrote a script which performed verification. Then another independent party verified that the script is correct.

@pfalcon Doing a:
```
git fetch zephyr pull/25808/head; git checkout FETCH_HEAD; git diff HEAD~3
```
and then verify this PR doesn't take long.

Especially when knowing what the `REQUIRED` flag does, and why it is important.

**Pull request merged**
