### PR TITLE
CPU mask affinity/pinning API

### PR DESCRIPTION
**Pull request by andyross**
This is the affinity API that was promised during the initial SMP work on esp32.

It's clean and simple, if not super featureful, and has a simple API that should shouldn't need fussing in the future.  It can also be tested on a uniprocessor system without SMP at all, which is helpful as SMP is... actually kind of broken right now...

### CODE REVIEW

**Comment by andyross** [comment]
Good point, will fix the verb convention.

I didn't add the "enable all" as that's the default state of a new thread so it didn't seem to be particularly useful at runtime and I was too lazy to type the extra lines of code, honestly.  Will add it, probably unifying the implementation a bit to remove the existing duplication.

Note that one other missing bit is that these aren't defined as system calls.  They certainly could be, but it similarly didn't seem like an API used at the very top level of an app really cared about running in a userspace context (or was worth the extra typing).

**Comment by andyross** [comment]
Fix naming.  Add the _enable_all() function @dcpleung requested (and unified the implementations to reduce the boilerplate).  Fixed the RAM overflow failures on the smaller boards by reusing an existing stack for the new test.

**Review by dcpleung — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@andyross one more conflict :)

**Comment by andyross** [comment]
Heh, yeah, same conflict really.  Popular spot in _Cstart() today

**Pull request merged**
