### PR TITLE
nucleo_f070rb: Enable USART1 ports on nucleo_f070rb

### PR DESCRIPTION
**Pull request by qianfan-Zhao**
default pinmaps for usart1 is PA9(tx) and PA10(rx)

Signed-off-by: qianfan Zhao <qianfanguijin@163.com>

### CODE REVIEW

**Review by ydamigos — APPROVED** [review]
LGTM

**Comment by zhaozhongchen** [comment]
@ydamigos I had forget add 'usart1' in dts file, and added that now. please recheck.

**Review by ydamigos — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Please update doc.

We'll have to decide if this is compatible with default boards configuration guidelines. Anyway, for now this is in line with other nucleos that present the same configuration, so I won't block, but it might be reviewed later on.

**Comment by zhaozhongchen** [comment]
@erwango some nucleo board configured PB6/PB7 as USART1 and others using PA9/PA10. What's is the best choise?

**Review by dbkinder — APPROVED** [review]
+1 for docs

**Comment by zhaozhongchen** [comment]
ping @erwango

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
