### PR TITLE
z_get_next_switch_handle() is not enough

### PR DESCRIPTION
**Pull request by npitre**
This is an attempt at formally distinguishing and supporting the case
described in 40795 where an architecture doesn't preserve/restore the
complete thread state upon entering/exiting interrupt exception state.

The corresponding ARM64 changes are also included. RISC-V is concerned
too, but pending patches have to be merged first.

### CODE REVIEW

**Comment by andyross** [comment]
This seems reasonable.  I think if we're going to respecify the API, we might go a little farther though:

* The name isn't great, it's really not just a predicate returning the next swtich handle, the scheduler uses this as the EOI hook where it knows it needs to set things up for the next context.

* It seems like the z_ prefix for internal names is in less favor now, and this is clearly an architecture API.

* We really don't want a third scheme in the API.  Let's fix all the architectures in one PR.

So maybe `arch_isr_complete()`, with the existing semantics but no switch handle argument, and `arch_isr_context()` which must be called at some point after that with a complete/valid switch handle?

**Comment by andyross** [comment]
Though thinking on it, the operation of `arch_isr_context()` is just to set the switch_handle field on the thread.  That's trivially inlined in C but the relevant code is almost certainly going to be in assembly on most architectures.  So really we'd just be specifying it as a field assignment anyway, maybe with a callable symbol just for clarity/documentation.

**Comment by npitre** [comment]
> I think if we're going to respecify the API, we might go a little
> farther though

Hmmm OK. I was under the impression that I had gone too far already.
More on that below.

> The name isn't great

I totally agree.

> It seems like the z_ prefix for internal names is in less favor now,
> and this is clearly an architecture API.

Well, I thought arch_* is used for kernel common to architecture calls
whereas architecture to kernel common calls always uses z_*. Here we have
the later case.

> We really don't want a third scheme in the API.  Let's fix all the
> architectures in one PR.

Not sure I understand. What third scheme?

> So maybe `arch_isr_complete()`, with the existing semantics but no
> switch handle argument, and `arch_isr_context()` which must be called
> at some point after that with a complete/valid switch handle?

Hmmpfff. I'd need an example to understand how this could work.

> Though thinking on it, the operation of `arch_isr_context()` is just
> to set the switch_handle field on the thread.  That's trivially inlined
> in C but the relevant code is almost certainly going to be in assembly
> on most architectures.  So really we'd just be specifying it as a field
> assignment anyway, maybe with a callable symbol just for
> clarity/documentation.

Well, when I said I might have gone too far above... It is about
the fact that we could simply formalize the definition of
`z_get_next_switch_handle()` where the passed handle value could
have 2 values. Either:

- The interrupted thread's handle, in which case this function returns
  the handle for the next thread to execute, which might be the same
  handle as the one passed in. The thread context must be completely parked
  when this is called.

- A NULL indicating that we want to know what the next thread to run is
  without parking the whole thread state just yet. If there is no other
  thread to run then NULL is returned. It is the responsibility of the
  caller to assign the k_thread_t.switch_handle of the interrupted thread
  with its handle value once the thread context is fully parked.

The beauty of it all is that the above already just works without any change to
the code, even with !SMP. Suffice to formalize it.

And with the explicit field assignment we won't need that tripple-pointer
argument.

And yes, the assignment is most likely done in assembly. And I would avoid
a callable symbol as this forces you to preserve active registers across
the call when a straight forward offsetable store (one instruction) can
do the job.

**Comment by npitre** [comment]
I pushed the simpler version. Unless you convinced me otherwise,
I don't see why we need to make it more complicated.

**Review by andyross — APPROVED** [review]
Right, I have no complaints with the doc changes to fully specify the semantics.  I'm thinking more along the lines of futureproofing this for other architectures.  The stages of "ISR has returned" and "context has been saved" are not the same thing and we should have two entry points which clarify that this is what they mean.

**Review by carlocaione — APPROVED** [review]
LGTM

**Pull request merged**
