### PR TITLE
Introduce GD32F4xx serial SoCs with GD32F450i_EVAL board

### PR DESCRIPTION
**Pull request by cameled**
Initial version for GD32F4xx serial SoCs support. There also have a more functional serial driver https://github.com/zephyrproject-rtos/zephyr/pull/39897 in progress.

[EDIT]: About GD32 support on zephyr, more info can be found in https://github.com/zephyrproject-rtos/zephyr/issues/38657

### CODE REVIEW

**Comment by cameled** [comment]
Hi @gmarull 

I found you are also work on GD32F450i_EVAL board at https://github.com/teslabs/zephyr/tree/gd32f450

Since this PR not have the GD32F450i_EVAL board description, I think we can work together to finish it. 

I have done the board basic init with the hello_world sample.

This PR use J-Link to Flash and Debug the board.

Best,
Cameled

**Comment by gmarull** [comment]
Since I already had the support ready for this board I've opened https://github.com/zephyrproject-rtos/zephyr/pull/39958 which has some more things, e.g. GD-Link support, docs and some HAL/DTS re-organization (use series/soc more in line with manufacturer practices, since GD32 is not following STM32 conventions).

Let's try to find a way to merge both, since this PR also has interesting stuff like J-Link support and F405/407 initial support.

**Comment by nandojve** [comment]
> Let's try to find a way to merge both, since this PR also has interesting stuff like J-Link support and F405/407 initial support.

There is a task list at #38657 and everyone is invited to add their name at tasks that want to do and avoid duplicated work. I saw that @gmarull already assumed some tasks. This is very important to avoid this kind of conflicts.

@cameled, do you mind rebase on top of #39958 in this particular case?

**Comment by cameled** [comment]
> > Let's try to find a way to merge both, since this PR also has interesting stuff like J-Link support and F405/407 initial support.
> 
> There is a task list at #38657 and everyone is invited to add their name at tasks that want to do and avoid duplicated work. I saw that @gmarull already assumed some tasks. This is very important to avoid this kind of conflicts.
> 
> @cameled, do you mind rebase on top of #39958 in this particular case?

Rebase is good. I don't have much more time to improve this recently.

**Pull request closed without merging**
