### PR TITLE
driver: usb: change function parameter name from class to base_class.

### PR DESCRIPTION
**Pull request by ssnover**
Change function parameter name in function usbd_device_set_code_triple from `class` to `base_class` as `class` is a keyword in C++.

Signed-off-by: Shane Snover <ssnover95@gmail.com>

### CODE REVIEW

**Comment by plushambush** [comment]
@ssnover I suppose there must be a matching change in definition of  `usbd_device_set_code_triple()`  in `subsys/usb/device_next/usbd_device.c` . Isnt' it?

**Review by tmon-nordic — CHANGES_REQUESTED** [review]
Please keep the same name between function declaration and definition.

**Review by tmon-nordic — DISMISSED** [review]

**Review by jfischer-no — CHANGES_REQUESTED** [review]
In that case it should be renamed to `base_class`.

**Review by jfischer-no — COMMENTED** [review]
Thanks

**Review by jfischer-no — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]

**Pull request merged**
