### PR TITLE
boards: rakwireless: Use proper vendor prefix as board folder

### PR DESCRIPTION
**Pull request by kartben**
hwmv2 established a convention that boards live in a folder named after the vendor prefix.
RAK Wireless boards apparently missed the memo.

### CODE REVIEW

**Review by pdgendt — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by kartben** [comment]
@aaronyegx @aaronyegx @RichardSWheatley could you help with the (unrelated) CI issue? AFAICT this warning in the HAL has always been there but I think it's only recently that c++ warnings have been promoted to errors

```
ccache /opt/toolchains/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ -DKERNEL -DK_HEAP_MEM_POOL_SIZE=0 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DTC_RUNID=7ab3f77f86036300d310c38a3c1cb87d -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/twister-out/rak11720/tests/lib/cpp/cxx/cpp.main.cpp98/zephyr/include/generated/zephyr -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/rak11720/tests/lib/cpp/cxx/cpp.main.cpp98/zephyr/include/generated -I/__w/zephyr/zephyr/soc/ambiq -I/__w/zephyr/zephyr/soc/ambiq/apollo3x/. -I/__w/zephyr/zephyr/soc/ambiq/. -I/__w/zephyr/zephyr/subsys/rtio -I/__w/zephyr/zephyr/subsys/testsuite/include -I/__w/zephyr/zephyr/subsys/testsuite/coverage -I/__w/zephyr/zephyr/subsys/testsuite/ztest/include -I/__w/zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/__w/zephyr/zephyr/modules/cmsis/. -I/__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include -I/__w/zephyr/modules/hal/ambiq/utils -I/__w/zephyr/modules/hal/ambiq/mcu/apollo3 -I/__w/zephyr/modules/hal/ambiq/components/bluetooth -isystem /__w/zephyr/zephyr/lib/libc/common/include -isystem /__w/zephyr/zephyr/lib/cpp/minimal/include -fno-strict-aliasing -Werror -Os -fcheck-new -std=c++98 -fno-exceptions -fno-rtti -imacros /__w/zephyr/zephyr/twister-out/rak11720/tests/lib/cpp/cxx/cpp.main.cpp98/zephyr/include/generated/zephyr/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft --sysroot=/opt/toolchains/zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/tests/lib/cpp/cxx=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -specs=picolibc.specs -nostdinc++ -MD -MT CMakeFiles/app.dir/src/main.cpp.obj -MF CMakeFiles/app.dir/src/main.cpp.obj.d -o CMakeFiles/app.dir/src/main.cpp.obj -c /__w/zephyr/zephyr/tests/lib/cpp/cxx/src/main.cpp
In file included from /__w/zephyr/zephyr/soc/ambiq/apollo3x/./soc.h:13,
                 from /__w/zephyr/zephyr/modules/cmsis/./cmsis_core_m.h:24,
                 from /__w/zephyr/zephyr/modules/cmsis/./cmsis_core.h:10,
                 from /__w/zephyr/zephyr/include/zephyr/arch/arm/asm_inline_gcc.h:24,
                 from /__w/zephyr/zephyr/include/zephyr/arch/arm/asm_inline.h:18,
                 from /__w/zephyr/zephyr/include/zephyr/arch/arm/arch.h:30,
                 from /__w/zephyr/zephyr/include/zephyr/arch/cpu.h:19,
                 from /__w/zephyr/zephyr/include/zephyr/kernel_includes.h:36,
                 from /__w/zephyr/zephyr/include/zephyr/kernel.h:17,
                 from /__w/zephyr/zephyr/include/zephyr/pm/device.h:11,
                 from /__w/zephyr/zephyr/tests/lib/cpp/cxx/src/main.cpp:18:
/__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include/apollo3.h:16343:3: error: this decimal constant is unsigned only in ISO C90 [-Werror]
16343 |   CLKGEN_CLOCKENSTAT_CLOCKENSTAT_IOMSTRIFC0_CLKEN = -2147483648,/*!< IOMSTRIFC0_CLKEN : Clock enable for the IOMSTRIFC0        */
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include/apollo3.h:16367:3: error: this decimal constant is unsigned only in ISO C90 [-Werror]
16367 |   CLKGEN_CLOCKEN2STAT_CLOCKEN2STAT_FORCEHFRC = -2147483648,/*!< FORCEHFRC : HFRC is forced on Status.                          */
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include/apollo3.h:16[382](https://github.com/zephyrproject-rtos/zephyr/actions/runs/11442906213/job/31841780930?pr=80160#step:12:384):3: error: this decimal constant is unsigned only in ISO C90 [-Werror]
16382 |   CLKGEN_CLOCKEN3STAT_CLOCKEN3STAT_flashclk_en = -2147483648,/*!< flashclk_en : Flash clk is enabled [31]                      */
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

**Comment by RichardSWheatley** [comment]
> @AlessandroLuo @aaronyegx @RichardSWheatley could you help with the (unrelated) CI issue? AFAICT this warning in the HAL has always been there but I think it's only recently that c++ warnings have been promoted to errors
> 
> 
> 
> ```
> 
> ccache /opt/toolchains/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ -DKERNEL -DK_HEAP_MEM_POOL_SIZE=0 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DTC_RUNID=7ab3f77f86036300d310c38a3c1cb87d -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/twister-out/rak11720/tests/lib/cpp/cxx/cpp.main.cpp98/zephyr/include/generated/zephyr -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/rak11720/tests/lib/cpp/cxx/cpp.main.cpp98/zephyr/include/generated -I/__w/zephyr/zephyr/soc/ambiq -I/__w/zephyr/zephyr/soc/ambiq/apollo3x/. -I/__w/zephyr/zephyr/soc/ambiq/. -I/__w/zephyr/zephyr/subsys/rtio -I/__w/zephyr/zephyr/subsys/testsuite/include -I/__w/zephyr/zephyr/subsys/testsuite/coverage -I/__w/zephyr/zephyr/subsys/testsuite/ztest/include -I/__w/zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/__w/zephyr/zephyr/modules/cmsis/. -I/__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include -I/__w/zephyr/modules/hal/ambiq/utils -I/__w/zephyr/modules/hal/ambiq/mcu/apollo3 -I/__w/zephyr/modules/hal/ambiq/components/bluetooth -isystem /__w/zephyr/zephyr/lib/libc/common/include -isystem /__w/zephyr/zephyr/lib/cpp/minimal/include -fno-strict-aliasing -Werror -Os -fcheck-new -std=c++98 -fno-exceptions -fno-rtti -imacros /__w/zephyr/zephyr/twister-out/rak11720/tests/lib/cpp/cxx/cpp.main.cpp98/zephyr/include/generated/zephyr/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft --sysroot=/opt/toolchains/zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/tests/lib/cpp/cxx=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -specs=picolibc.specs -nostdinc++ -MD -MT CMakeFiles/app.dir/src/main.cpp.obj -MF CMakeFiles/app.dir/src/main.cpp.obj.d -o CMakeFiles/app.dir/src/main.cpp.obj -c /__w/zephyr/zephyr/tests/lib/cpp/cxx/src/main.cpp
> 
> In file included from /__w/zephyr/zephyr/soc/ambiq/apollo3x/./soc.h:13,
> 
>                  from /__w/zephyr/zephyr/modules/cmsis/./cmsis_core_m.h:24,
> 
>                  from /__w/zephyr/zephyr/modules/cmsis/./cmsis_core.h:10,
> 
>                  from /__w/zephyr/zephyr/include/zephyr/arch/arm/asm_inline_gcc.h:24,
> 
>                  from /__w/zephyr/zephyr/include/zephyr/arch/arm/asm_inline.h:18,
> 
>                  from /__w/zephyr/zephyr/include/zephyr/arch/arm/arch.h:30,
> 
>                  from /__w/zephyr/zephyr/include/zephyr/arch/cpu.h:19,
> 
>                  from /__w/zephyr/zephyr/include/zephyr/kernel_includes.h:36,
> 
>                  from /__w/zephyr/zephyr/include/zephyr/kernel.h:17,
> 
>                  from /__w/zephyr/zephyr/include/zephyr/pm/device.h:11,
> 
>                  from /__w/zephyr/zephyr/tests/lib/cpp/cxx/src/main.cpp:18:
> 
> /__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include/apollo3.h:16343:3: error: this decimal constant is unsigned only in ISO C90 [-Werror]
> 
> 16343 |   CLKGEN_CLOCKENSTAT_CLOCKENSTAT_IOMSTRIFC0_CLKEN = -2147483648,/*!< IOMSTRIFC0_CLKEN : Clock enable for the IOMSTRIFC0        */
> 
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> /__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include/apollo3.h:16367:3: error: this decimal constant is unsigned only in ISO C90 [-Werror]
> 
> 16367 |   CLKGEN_CLOCKEN2STAT_CLOCKEN2STAT_FORCEHFRC = -2147483648,/*!< FORCEHFRC : HFRC is forced on Status.                          */
> 
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> /__w/zephyr/modules/hal/ambiq/CMSIS/AmbiqMicro/Include/apollo3.h:16[382](https://github.com/zephyrproject-rtos/zephyr/actions/runs/11442906213/job/31841780930?pr=80160#step:12:384):3: error: this decimal constant is unsigned only in ISO C90 [-Werror]
> 
> 16382 |   CLKGEN_CLOCKEN3STAT_CLOCKEN3STAT_flashclk_en = -2147483648,/*!< flashclk_en : Flash clk is enabled [31]                      */
> 
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> cc1plus: all warnings being treated as errors
> 
> ninja: build stopped: subcommand failed.
> 
> ```
> 
> 

I was always under the assumption that our HAL would not have to conform to Zephyr standards.

**Comment by kartben** [comment]
Maybe @fabiobaltieri can chime in as he is the author #78419 (which I *think* is why this PR now fails, but not actually sure)

**Comment by fabiobaltieri** [comment]
> Maybe @fabiobaltieri can chime in as he is the author of #78419 (which I _think_ is why this PR now fails, but not actually sure)

https://github.com/zephyrproject-rtos/hal_ambiq/pull/34 it's fixed on the module but the manifest is out of date

**Comment by fabiobaltieri** [comment]
Ok, the fix is pending on https://github.com/zephyrproject-rtos/zephyr/pull/79547

**Comment by kartben** [comment]
> Ok, the fix is pending on https://github.com/zephyrproject-rtos/zephyr/pull/79547

Thanks much for digging this up! Guess I didn't search thoroughly enough for open issues/PRs

**Comment by fabiobaltieri** [comment]
> Thanks much for digging this up! Guess I didn't search thoroughly enough for open issues/PRs

Well I only found out after doing a PR to fix it myself and trying to figure why it was not mergeable :-)

**Comment by zeonchew** [comment]
> Ok, the fix is pending on #79547

I believe the manifest has been updated and merged in #80032

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
