### PR TITLE
drivers: entropy: pseudo entropy from device id

### PR DESCRIPTION
**Pull request by alexanderwachter**
This driver enables to seed xoroshiro128 with a pseudo entropy.
It is useful for devices with no entopy source but is unsuitable
to use for crypto (e.g. nonce generation)!

Signed-off-by: Alexander Wachter <alexander.wachter@student.tugraz.at>

### CODE REVIEW

**Comment by erwango** [comment]
Hi @lpereira, would you help reviewing this?

**Review by erwango — COMMENTED** [review]
I'm fine with the change, but would like review from people more aware about security.

**Comment by alexanderwachter** [comment]
@erwango this solution has no security relation. This is not a real entropy source an has therefore no security benefit. Nonces or keys generated from this RND are not secure and can easily be predicted.
The aim of this PR is to to have some random number i.e. for random address generation or retransmit timers or similar.
The problem I had was that I'm running a network of equal boards with equal software. If the boards are powered from the same source they will boot exactly at the same time and produce the same sys_rand numbers when timer is used as random source. In my case, this leads to collisions in my application.

**Comment by lpereira** [comment]
While I understand the need for something like this, especially in test environments (since  TEST_RANDOM_GENERATOR has to be defined for this to be active), I'm not really happy with an entropy driver that produces no entropy.  Also, there's no way to ensure that any user other than the xoroshiro sys_rand implementation will use this.

What I'd do instead is modify one of those test-only RNGs, such as rand32_timer.c: instead of adding a hardcoded constant to the cycle counter, add the device unique ID instead. This lessens the possibility of people enabling an entropy driver that provides no entropy whatsoever, and fixes your issues.

**Comment by alexanderwachter** [comment]
As i understand the problem is that an entropy driver does not provide any entropy. Even worse it always provides the same value for every call.
Using rand32_timer.c will not solve the problem because there is no hardware independent (driver api) way to get the unique hardware id. It is not possible to get the device id within the rand subsys.
Writing an API for reading the device unique id and seed the LFSR (with TEST_RANDOM_GENERATOR enabled) would be acceptable @lpereira ?

**Comment by lpereira** [comment]
That would work, @alexanderwachter.  As a bonus, such API to obtain a unique hardware ID could be used to add some personalization data for a crypto-safe PRNG; Zephyr currently lacks such feature.

**Comment by alexanderwachter** [comment]
Replaced by  #13023

**Pull request closed without merging**
