### PR TITLE
doc: Add upgrade flag to the install requirements command

### PR DESCRIPTION
**Pull request by butok**
- Adds -U upgrade flag to the install requirements command.
- Fixes a possible documentation generation issue, reported in https://github.com/zephyrproject-rtos/zephyr/issues/73082

### CODE REVIEW

**Comment by butok** [comment]
There are CI internal errors (module updates):
```
=== updating zcbor (modules/lib/zcbor):
Cloning into '/__w/zephyr/modules/lib/zcbor'...
--- zcbor: cloning from /repo-cache/zephyrproject/modules/lib/zcbor
done.
HEAD is now at 75d0880 tests: Update mps2 board name
ERROR: update failed for projects: sof, tflite-micro, thrift
Error: Error: failed to run script step: command terminated with non-zero exit code: Error executing in Docker Container: 1
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

**Comment by butok** [comment]
UP

> There are CI internal errors (module updates):
> 
> ```
> === updating zcbor (modules/lib/zcbor):
> Cloning into '/__w/zephyr/modules/lib/zcbor'...
> --- zcbor: cloning from /repo-cache/zephyrproject/modules/lib/zcbor
> done.
> HEAD is now at 75d0880 tests: Update mps2 board name
> ERROR: update failed for projects: sof, tflite-micro, thrift
> Error: Error: failed to run script step: command terminated with non-zero exit code: Error executing in Docker Container: 1
> Error: Process completed with exit code 1.
> Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
> ```

The CI issue was solved. 
Please continue the PR review.

**Review by kartben — CHANGES_REQUESTED** [review]
line 101 requires updating too

**Comment by butok** [comment]
> line 101 requires updating too

Updated.

**Review by kartben — APPROVED** [review]

**Comment by butok** [comment]
FYI: The CI is broken
`"-- Could NOT find LATEX (missing: LATEX_COMPILER PDFLATEX) "`

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
