### PR TITLE
net: lwm2m: add support for building with POSIX API

### PR DESCRIPTION
**Pull request by tokangas**
If POSIX_API option is enabled, use the relevant POSIX headers and do not select NET_SOCKETS_POSIX_NAMES.

### CODE REVIEW

**Review by SeppoTakalo — DISMISSED** [review]

**Review by rlubos — COMMENTED** [review]
That's one way to address the matter, but maybe a cleaner solution would be to do something like we did for MQTT, i.e. drop POSIX dependency and use `zsock_` API directly? There's the change for reference https://github.com/zephyrproject-rtos/zephyr/commit/fff28ad8ae573d5d48ef9ff90fbced28d9509c1f

**Comment by tokangas** [comment]
> That's one way to address the matter, but maybe a cleaner solution would be to do something like we did for MQTT, i.e. drop POSIX dependency and use `zsock_` API directly? There's the change for reference [fff28ad](https://github.com/zephyrproject-rtos/zephyr/commit/fff28ad8ae573d5d48ef9ff90fbced28d9509c1f)

Similar flagging has been done at least in websocket, so I though this was the way to. I agree that it's not very nice, though. If using `zsock_` directly is preferable, I can modify the PR.

**Comment by tokangas** [comment]
@rlubos Pushed a new commit which uses the `zsock_` functions instead. Ping @SeppoTakalo.

**Review by rlubos — DISMISSED** [review]

**Review by SeppoTakalo — DISMISSED** [review]

**Comment by tokangas** [comment]
Needed to rebase.

**Review by SeppoTakalo — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Review by rlubos — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Pull request merged**
