### PR TITLE
tests: bsim: CIS: Increase timeouts

### PR DESCRIPTION
**Pull request by aescolar**
These tests take relatively long to run.
The runtime timeout (CI safety timeout) is too short.
Increase it so it does not fail at random in CI.

The only penalty of increasing this timeout, is that
if one of these tests actually hangs, we will not detect it
until the timeout expires, wasting a bit of CI time.

---

One failure due to this timeout in CI here:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/4896346415/jobs/8743045813?pr=57346#step:12:26015

### CODE REVIEW

**Review by Thalley — CHANGES_REQUESTED** [review]
Code change is good, but please fix the typo with `increse` in the commit message and PR title :)

**Comment by aescolar** [comment]
> ..Code change is good, but please fix the typo ..

@stephanosio  Seems gitlint /  scripts/ci/check_compliance.py  is not catching typos in commits messages anymore (this is not the first typo in a message not flagged in the compliance check)
Was this disabled purposefully, or something got miss-configured?

**Comment by Thalley** [comment]
> > I think couple more CIS tests that have the same 30 second timeout will need increase.
> 
> If you tell me which, I can fix them in this PR directly

A quick search yielded this: 

image

I assume that any tests that contains > 5 devices may want a higher timeout.

**Comment by aescolar** [comment]
@cvinayak @Thalley all CIS' timeouts increased :)

**Review by cvinayak — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Pull request merged**
