### PR TITLE
drivers: can: m_can: fix alignmed issues

### PR DESCRIPTION
**Pull request by alexanderwachter**
Make sure that all access to the msg_sram is 32 bit aligned.

Fix for #41255 and #41074

### CODE REVIEW

**Comment by alexanderwachter** [comment]
@pdietl Have made this hotfix. We can switch to your memcpy when it ti through.

**Review by henrikbrixandersen — APPROVED** [review]
Thanks.

**Review by martinjaeger — APPROVED** [review]
Thanks. Agreed as a hotfix, though I would prefer to finally put the generic `memcpy32` functions into `lib/` as suggested in #41273 by @pdietl.

**Comment by alexanderwachter** [comment]
The generic memcpy32 is not generic enough. I prefer a version with volatile qualifier so that the compiler is forced to copy 32bit in the order specified.

**Comment by erwango** [comment]
> The generic memcpy32 is not generic enough. I prefer a version with volatile qualifier so that the compiler is forced to copy 32bit in the order specified.

I'm also puzzled to have such function implemented in a driver. If `memcpy32` is not enough, maybe `volatile_memcpy32` could also be added to the lib ?

**Comment by alexanderwachter** [comment]
@erwango this is a hotfix. As soon as we have something generic, we will switch to that instead.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
I merged this to get the hotfix in, but I completely agree we need to move those functions out of the driver.

**Pull request merged**
