### PR TITLE
drivers: flash: stm32 quad/octo-spi driver reads sfdp table

### PR DESCRIPTION
**Pull request by FRASTM**
Fix the SFDP command to be sent by the qspi driver to get the SFDP table from the NOR quad flash.
Configuration file is updated for quad-spi or octo-spi boards to get the jedec info when running the 
samples/drivers/jesd216/

This PR is creating a new  testcase for stm32 devices with sample.drivers.stm32.jesd216:

- Another way could be to ored the filter: dt_compat_enabled("jedec,spi-nor") or add a `compatible = ""jedec,spi-nor"` for the target boards

Note that CONFIG_FLASH_STM32_QSPI=y and CONFIG_SPI_NOR=n

### CODE REVIEW

**Comment by FRASTM** [comment]
running the   samples/drivers/jesd216/  on the stm32h747i_disco_m7

```
*** Booting Zephyr OS build zephyr-v3.4.0-3583-g999b20809752 ***
qspi-nor-flash-1@0: SFDP v 1.6 AP ff with 2 PH
PH0: ff00 rev 1.6: 16 DW @ 30
Summary of BFP content:
DTR Clocking supported
Addressing: 3- or 4-Byte
4-KiBy erase: uniform
Support QSPI XIP
Support 1-1-1
Support 1-1-2: instr 3Bh, 1 mode clocks, 7 waits
Support 1-1-4: instr 6Bh, 1 mode clocks, 7 waits
Support 1-2-2: instr BBh, 1 mode clocks, 7 waits
Support 1-4-4: instr EBh, 1 mode clocks, 9 waits
Support 2-2-2: instr BBh, 1 mode clocks, 7 waits
Support 4-4-4: instr EBh, 1 mode clocks, 9 waits
Flash density: 67108864 bytes
ET1: instr 20h for 4096 By; typ 48 ms, max 480 ms
ET2: instr D8h for 65536 By; typ 160 ms, max 1600 ms
ET3: instr 52h for 32768 By; typ 112 ms, max 1120 ms
Chip erase: typ 62464 ms, max 1499136 ms
Byte program: type 15 + 1 * B us, max 360 + 24 * B us
Page program: typ 120 us, max 2880 us
Page size: 256 By
Suspend: 75h ; Resume: 7Ah
DPD: Enter B9h, exit ABh ; delay 30000 ns ; poll 0x3e
HOLD or RESET Disable: supported
QER: 0
0-4-4 Mode methods: entry 0x2 ; exit 0x03
4-4-4 Mode sequences: enable 0x14 ; disable 0xa
4-byte addressing support: enter 0x36, exit 0x0f6
Soft Reset and Rescue Sequence support: 0x3d
Status Register 1 support: 0x01
size = <536870912>;
sfdp-bfp = [
        e5 20 fb ff  ff ff ff 1f  29 eb 27 6b  27 3b 27 bb
        ff ff ff ff  ff ff 27 bb  ff ff 29 eb  0c 20 10 d8
        0f 52 00 00  24 4a 99 00  8b 8e 03 e1  ac 01 27 38
        7a 75 7a 75  fb bd d5 5c  4a 0f 82 ff  81 bd 3d 36
        ];
PH1: ff84 rev 1.0: 2 DW @ 80
sfdp-ff84 = [
        ff e7 ff ff  21 dc ff ff
        ];
jedec-id = [32 31 20];
```

**Review by erwango — COMMENTED** [review]
> Note that CONFIG_FLASH_STM32_QSPI=y and CONFIG_SPI_NOR=n

This is unclear. Does it mean that it only works in this configuration?
What about other configurations ? Are they supported ? Non legit ?

**Comment by FRASTM** [comment]
> > Note that CONFIG_FLASH_STM32_QSPI=y and CONFIG_SPI_NOR=n
> 
> This is unclear. Does it mean that it only works in this configuration? What about other configurations ? Are they supported ? Non legit ?

The autoconf.h is generated with #define CONFIG_FLASH_STM32_QSPI 1 and no CONFIG_SPI_NOR

**Comment by FRASTM** [comment]
tested with ospi driver on stm32l562e_dk, b_u585i_iot02a, stm32h573i_dk, stm32h735g_disco, b_l4s5i_iot01a
tested with qspi driver on stm32l496g_disco,  stm32h747i_disco_m7, , disco_l475i_iot1

**Comment by FRASTM** [comment]
Rebase on 68365d5b67057c8e960a5168c2cf99f4b8c457c1

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Pull request merged**
