### PR TITLE
Bluetooth: BAP: Remove SNK and SRC count asserts

### PR DESCRIPTION
**Pull request by mkasenberg**
This removes asserts introduced in 5a4c9a2112a06fab89c6fb99a7621bdb1ebe2bdd.

An application does not need to support all configurations, hence CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT and
CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT should be configurable to value 1.

Table 4.2 in BAP v1.0.1 just shows us what we need to support a configuration.

### CODE REVIEW

**Comment by Thalley** [comment]
> An application does not need to support all configurations, hence CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT and
CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT should be configurable to value 1.
> 
> Table 4.2 in BAP v1.0.1 just shows us what we need to support a configuration.

Hmm, can you elaborate? If we only support e.g. 1 sink ASE, then we do not support the mandatory Audio Configuration 6(i).

Is is not valid to have a Unicast Client that only supports 1 sink ASE. Either we support the Audio Source role (indicated by supporting > 0 sink ASEs) and we must support at least 2 sink ASEs, or we do not support the Audio Source role.

This is indeed something that caused an interoperability issue during UPF

**Comment by mkasenberg** [comment]
Oh, I see. My interpretation was as follow:

If only a client is empowered to select an audio configuration it needs and set up a CIG, it means that in a client implementation, all configurations are optional. If a client application does not meet or like a configuration requirement, it will simply not use it in the CIG setup. With that assumption, the only work that needs to be done here is to determine if the server supports any configuration according to the client's preferences. This is also the client's responsibility.
Based on table 4.2, I can see that a server's AC capabilities can be determined by the presence of Sink and Source ASE characteristics, supported Audio Locations and Audio Channels count. So if the client is not satisfied with the server's AC capabilities, it can choose not to set up a CIG and disconnect.

I have only considered the BAP, ASCS, and PACS specifications. I can imagine that some profiles of the upper layers of the LE Audio framework depend on these mandatory requirements. Have there been any interoperability issues during UPF with these upper layer profiles? In my opinion, in that case, assertions in Zephyr's implementation could check if those are being used, and only then ensure that the number of Sinks is >1 or ==0.

**Comment by mkasenberg** [comment]
Moreover I think the 4.2. table can be read as fallow:

For AC 1: If both Client and Server support 1 CIS, the Client supports 1 server and 1 Audio Source and the Server supports 1 Audio Sink, then the AC1 is expected to be supported.

For AC 6(i): If both Client and Server support 2 CISes, the Client supports 1 server and 2 Audio Sources and the Server supports 2 Audio Sinks and supports more than one Audio Location in Sink Audio Locations, then the AC 6(i) is expected to be supported.

**Comment by Thalley** [comment]
@mkasenberg You have some good points, and I am indeed unsure if the BUILD_ASSERTS is the right way to go. 

Your comments with `If both Client and Server support 2 CISes,` is a bit moot though, as it is a mandatory configuration that will be tested in BAP for qualification. In other words, you cannot be a BAP Unicast Client without supporting 2 CISes, so the "if" cannot be applied. 

> Have there been any interoperability issues during UPF with these upper layer profiles?

No, the interoperability issue was found during a simple BAP test

> assertions in Zephyr's implementation could check if those are being used

Since a device can use BAP in any role (BAP, CAP, TMAP, HAP, etc.) at any time, it is impossible for the stack to know which role a BAP operation is done in. E.g. just because you support TMAP in your device, does not mean that the stream operations is done in respect to that profile. 

> I can see that a server's AC capabilities can be determined by the presence of Sink and Source ASE characteristics, supported Audio Locations and Audio Channels count.

Indeed, the combination of # of ASEs and the channel count does indicate which audio configurations are supported by the server. 



In the end, the fact of the matter is that the table enforces some requirements on the Client (and on the server), and to qualify as a BAP device you must support those requirements as they will be tested with PTS

**Comment by mkasenberg** [comment]
I've checked in Launch Studio and you have right, this is marked as mandatory

image

**Comment by mkasenberg** [comment]
Though I think we should differentiate between the capabilities of the stack and the features actually used by the application, to allow to keep the app binary as small as possible.

**Comment by Thalley** [comment]
> Though I think we should differentiate between the capabilities of the stack and the features actually used by the application, to allow to keep the app binary as small as possible.

Agree, to the extent that is possible :)

**Pull request closed without merging**
