### PR TITLE
net: sockets: tls: Implement TLS socket internals using WolfSSL

### PR DESCRIPTION
**Pull request by ColtonWilley**
Modify the TLS socket implementation to allow wolfSSL instead of mbedTLS for underlying TLS implementation.

### CODE REVIEW

**Comment by ColtonWilley** [comment]
Maintainers, I believe this PR will be impossible to pass the checks until a new wolfssl repo is added similar to the mbedtls one here https://github.com/zephyrproject-rtos/mbedtls, as this will be adding a new default module. 

I do not believe I have permissions to add such a repo myself, so please let me know if there is anything I need to do on my end to facilitate this process.

**Comment by jukkar** [comment]
The module would first need to exists in for example https://github.com/zephyrproject-rtos/wolfssl before this PR could be merged to upstream. The process to create the module repo is described in https://docs.zephyrproject.org/latest/contribute/external.html

The license of the wolfssl seems to be GPLv2 which is not compatible with Apache-2, which would probably prevent the module to be created as an normal module. The module could be an external module, so being outside of zephyrproject-rtos repo, but in that case this PR could not be merged to upstream.

**Review by tomi-font — CHANGES_REQUESTED** [review]
The first step in this would be to introduce wolfSSL into Zephyr.

As @jukkar pointed out, a challenge with this is wolfSSL's license and its compatibility with Zephyr. This is probably the first thing that needs to be figured out.
FYI there's already been some discussion around this topic in the past, though without resolution: https://github.com/zephyrproject-rtos/zephyr/issues/55861

Regarding the implementation, I don't think we want any more of those `#ifdef`s for choosing the crypto provider. Even though Zephyr currently uses different APIs (PSA/Mbed TLS/TinyCrypt/crypto driver), the goal is to stop doing that and instead only use the PSA Crypto API. (https://github.com/zephyrproject-rtos/zephyr/issues/43712)

wolfSSL could be made to replace the PSA Crypto API implementation of Mbed TLS when configured to be used. This greatly simplifies things and avoids having usage of wolfSSL symbols baked into the Zephyr codebase, possibly helping with the licensing issue.

**Comment by ColtonWilley** [comment]
@tomi-font While the PSA crypto idea is a great one, and I think something we could look into in the future for other more pure crypto use cases in zephyr, I dont think it solves the issues faced at this moment. Even if all PSA crypto is implemented properly, it doesnt change the fact that the TLS implementation itself wont fall under PSA, and callers may want the wolfssl TLS stack instead of the mbedTLS TLS stack. Ultimately though this may all be moot as I think all of this rests on the module question. 

@jukkar I have read the documentation on external modules and am still a bit confused. Will you allow calling code in the zephyr sockets_tls.c to an external wolfssl module? If not, what is the alternative? I apologize for having so many questions, I am just a bit confused here on what my options are given licensing restrictions.

**Comment by jukkar** [comment]
> I have read the documentation on external modules and am still a bit confused. Will you allow calling code in the zephyr sockets_tls.c to an external wolfssl module? If not, what is the alternative?

That is a good question, I think we do not allow that so having ifdef code that cannot be compiled properly as the module cannot be enabled without manually editing west manifest file. Best option would be of course to have an API that zephyr would use and then the wolfssl (or any other ssl implementation) could implement. I believe this is what @tomi-font is describing above.

**Comment by ColtonWilley** [comment]
@jukkar OK that is about what I expected, direct calls like that would be disallowed. Per "Best option would be of course to have an API that zephyr would use and then the wolfssl (or any other ssl implementation) could implement." I guess I am not fully understanding this suggestion. I dont see how it would be different than say how ztls_accept_ctx() is already an implementation agnostic call. We could make that function go to some generic TLS accept function, but I would think any implementation of the new interface would also go in the kernel, and would also need to then split into calls for mbedtls/wolfssl, leading us back to the same issue of default module code. Unless I am missing something?

**Comment by tomi-font** [comment]
> While the PSA crypto idea is a great one, and I think something we could look into in the future for other more pure crypto use cases in zephyr, I dont think it solves the issues faced at this moment. Even if all PSA crypto is implemented properly, it doesnt change the fact that the TLS implementation itself wont fall under PSA, and callers may want the wolfssl TLS stack instead of the mbedTLS TLS stack. Ultimately though this may all be moot as I think all of this rests on the module question.

Right, I had forgotten that TLS is at a higher layer than PSA Crypto and that (at least as of now) there's no unified API that Mbed TLS and wolfSSL both implement.
Even if wolfSSL code cannot be called from mainline Zephyr, maybe wolfSSL could have its own `sockets_tls.c` that would live in an external repository and would replace the one in Zephyr when wolfSSL would be configured to be used in Zephyr.
The exact limitations brought by the licensing need to be figured out to know what needs to be worked around and if/how this is doable/acceptable.
One potential alternative could be if wolfSSL provided a license different than GPLv2 so that the integration in Zephyr would become acceptable. I don't know.

**Comment by ColtonWilley** [comment]
I agree if these issues cannot be resolved it would likely be maintained as a separate sockets_tls.c. Overall though I was still hoping to get it in as I believe wolfssl can provide value to zephyr users. The next step was going to be to add TLS 1.3 support, giving zephyr users a "out of the box" option for TLS 1.3 and post quantum crypto. 

Under the submission process detailed here https://docs.zephyrproject.org/latest/contribute/external.html, under "submission and review process" it states "If, however, the external source code uses a license other than Apache-2.0, then these additional steps must be followed:" then a process involving petitioning the TSC for an exemption. I have also done some digging and it does seem there are already multiple modules like openocd, libpicoc, and qemu that have been approved as default modules with a GPLv2 license. I was wondering if this would fall under that case, and I would be allowed to petition the TSC for an exemption.

**Comment by str4t0m** [comment]
I am no licensing expert, but to my knowledge GPLv2 is incompatible with apache2.
Arduino is also facing the same issue at the moment. And [GNU](https://directory.fsf.org/wiki/License:Apache2.0.) explicitly warns about it.

 Also, note that the openocd and qemu have been forked to be able to build the SDK and Picolibc is mostly BSD licensed:
> While much of the code comes from Newlib, none of the GPL-related bits used to build the library are left in the repository, so all of the source code uses BSD-like licenses, a mixture of 2- and 3- clause BSD itself and a variety of other (mostly older) licenses with similar terms.

**Comment by ColtonWilley** [comment]
I agree that the licensing is currently incompatible to bring this in as is. I guess at this point I am wondering specifically if I am allowed to file for an exemption to the TSC.

**Comment by ColtonWilley** [comment]
Thank you all for your time on this issue. I see now that the licensing issues cannot be overcome.

I will be closing this PR. My work did extend the existing TLS test suite for mbedTLS as well, so I will look at committing that separately.

**Comment by dleach02** [comment]
The other option to consider is for wolssl to host their own downstream that does this integration. Not as convenient but doable. If the value proposition is great enough to use wolfssl over the modules that Zephyr Project as integrated then some users of Zephyr that need that may consider leveraging your downstream.

**Comment by tomi-font** [comment]
Or host all the wolfSSL-calling code in an external (wolfSSL-owned) repository (e.g. `sockets_tls.c`, so not a complete fork of Zephyr because this would have a higher maintenance cost) and upstream configuration changes to facilitate switching from Mbed TLS to wolfSSL for users wanting it (and having the appropriate license)?
This is basically what @nashif was saying is possible [here](https://github.com/zephyrproject-rtos/zephyr/issues/76002#issuecomment-2234480867).

With the recent changes related to PSA Crypto we've already been moving towards a more crypto provider-agnostic approach (although it's still heavily Mbed TLS-based), e.g. see [Kconfig.psa](https://github.com/zephyrproject-rtos/zephyr/blob/v3.7.0-rc3/modules/mbedtls/Kconfig.psa), and more progress in that direction is welcome.

**Pull request closed without merging**
