### PR TITLE
Just a typo fix.

### LINKED ISSUE #14292: Typo "QPSI" in QSPI macros in some stm32 drivers
```
$ git grep QPSI
drivers/flash/soc_flash_nios2_qspi.c:           /* read QPSI status register */
ext/hal/st/stm32cube/stm32f4xx/drivers/include/stm32f4xx_hal_qspi.h:#define HAL_QPSI_TIMEOUT_DEFAULT_VALUE 5000U /* 5 s */
ext/hal/st/stm32cube/stm32f4xx/drivers/src/stm32f4xx_hal_qspi.c:    HAL_QSPI_SetTimeout(hqspi, HAL_QPSI_TIMEOUT_DEFAULT_VALUE);
ext/hal/st/stm32cube/stm32f7xx/drivers/include/stm32f7xx_hal_qspi.h:#define HAL_QPSI_TIMEOUT_DEFAULT_VALUE ((uint32_t)5000)/* 5 s */
ext/hal/st/stm32cube/stm32f7xx/drivers/src/stm32f7xx_hal_qspi.c:    HAL_QSPI_SetTimeout(hqspi, HAL_QPSI_TIMEOUT_DEFAULT_VALUE);
ext/hal/st/stm32cube/stm32l4xx/drivers/include/stm32l4xx_hal_qspi.h:#define HAL_QPSI_TIMEOUT_DEFAULT_VALUE 5000U /* 5 s */
ext/hal/st/stm32cube/stm32l4xx/drivers/src/stm32l4xx_hal_qspi.c:    HAL_QSPI_SetTimeout(hqspi, HAL_QPSI_TIMEOUT_DEFAULT_VALUE);
```

### PR DESCRIPTION
**Pull request by yannroth**
Fixes #14292

signed-off-by: Yann Roth <yannrth@gmail.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Please update packages README files (patch list section).
I'll provide an internal  bug tracker ID, so please wait for that.

**Comment by ioannisg** [comment]
You should probably write a commit message body, as well. (not just the "Fixes #14296")

**Review by erwango — CHANGES_REQUESTED** [review]
Please split your PR as follows:
-driver/flash commit:
-stm32f4 commit (code + readme, add bug tracker 63625)
-stm32f7 commit (code + readme, add bug tracker 63626)
-stm32l4 commit (code + readme, add bug tracker 63627)

Txs

**Comment by erwango** [comment]
This issue has been fixed and devlivered for at least L4 package. Others packages should be fixed in upcoming releases. Closing this issue

**Pull request closed without merging**
