### PR TITLE
Board cleanup

### PR DESCRIPTION
**Pull request by galak**
Remove or reduce use of board.h outside of the board directory.

### CODE REVIEW

**Review by aescolar — DISMISSED** [review]
board.h is included from subsys/usb/usb_device.c:64
Those will break with this PR
I don't have any other issue otherwise regarding the effect on native_posix or the nrf52_bsim.

**Review by GAnthony — APPROVED** [review]
LGTM. 
Passes sanity on cc3220sf_launchxl.

**Comment by galak** [comment]
Opened up PR #11290 to address the usb issue.

**Review by erwango — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
LGTM

**Review by ydamigos — APPROVED** [review]

**Comment by galak** [comment]
@aescolar can you re-review now that the USB stuff has changed and been merged.

**Review by nategraff-sifive — APPROVED** [review]
LGTM

**Review by aescolar — APPROVED** [review]
No further complaints from my side

**Pull request merged**
