### PR TITLE
boards: efm32pg_stk3402a: Add minimal pwm support

### PR DESCRIPTION
**Pull request by chrta**
With this additions samples/basic/blinky_pwm works. LED0 is used as pwm output.

This is tested on hardware using both board variants:
```
west build -b efm32pg_stk3402a --pristine auto samples/basic/blinky_pwm
west build -b efm32pg_stk3402a_jg --pristine auto samples/basic/blinky_pwm
```

### CODE REVIEW

**Comment by chrta** [comment]
@catch-twenty-two I wanted to test your change on the dev board, so i added the missing pieces. I left your commit untouched here in this pr. It this is ok for you, i will remove the draft here.

**Comment by catch-twenty-two** [comment]
hi @chrta I'm not sure what you want to do, did you want to move the pr to this branch? or merge your changes into mine?

**Comment by chrta** [comment]
> hi @chrta I'm not sure what you want to do, did you want to move the pr to this branch? or merge your changes into mine?

If you approve, we can close #42064 and i can remove the draft status here, so this pr can be reviewed and merged.

**Comment by catch-twenty-two** [comment]
> > hi @chrta I'm not sure what you want to do, did you want to move the pr to this branch? or merge your changes into mine?
> 
> @catch-twenty-two If you approve, we can close #42064 and i can remove the draft status here, so this pr can be reviewed and merged.

Hi @chrta sounds good to me, thanks for helping out

**Review by MaureenHelm — DISMISSED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
