### PR TITLE
[backport v1.14] Bluetooth: controller: legacy: Backport v2.2 to v1.14-branch

### LINKED ISSUE #25314: Bluetooth: controller: legacy: Backport conformance test related changes
**Describe the bug**
During conformance testing of v2.2-branch, numerous implementation fixes related to conformance test changes and failures were undertaken. These fixes are missing in legacy controller in v1.14-branch.

**To Reproduce**
Re-run conformance testing using hci_uart application in v1.14-branch

**Expected behavior**
Bluetooth Controller in v1.14-branch shall meet the same level of quality as v2.2-branch for a said Bluetooth v5.1 qualified design listing.

**Impact**
showstopper

**Screenshots or console output**
NA

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: v1.14.2

**Additional context**
backport PR #23091

### PR DESCRIPTION
**Pull request by cvinayak**
Commits in this PR are manual cherry-pick of commits based on differences in ctrl.c file.

Fixes #25314

### CODE REVIEW

**Comment by carlescufi** [comment]
@cvinayak please move this out of draft in order to get it in a 1.14 dot release

**Comment by cvinayak** [comment]
@kruithofa  CC

**Comment by cvinayak** [comment]
Please remove the stale label, the changes in this PR is need to be in a 1.14 release branch.

**Comment by carlescufi** [comment]
This covers all security issues up to the removal of the legacy controller.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@thoh-ot @kruithofa could you review and approve please?

**Comment by MaureenHelm** [comment]
> @thoh-ot @kruithofa could you review and approve please?

ping

**Comment by MaureenHelm** [comment]
@cvinayak will you please rebase?

**Comment by cvinayak** [comment]
Closing to re-open, so as to retrigger CI.

**Comment by cvinayak** [comment]
@MaureenHelm I get unrelated build failure, maybe the v1.14-branch is borken? need help from maintainers/implementors of the following:
```
qemu_x86_64               tests/crypto/rand32/crypto.rand32
qemu_x86_64               tests/drivers/ipm/peripheral.mailbox
qemu_x86_64               tests/kernel/sched/schedule_api/kernel.sched
qemu_x86_64               tests/kernel/timer/timer_api/kernel.timer
qemu_x86_64               tests/lib/crc/misc.crc
```

**Comment by MaureenHelm** [comment]
> @MaureenHelm I get unrelated build failure, maybe the v1.14-branch is broken? need help from maintainers/implementors of the following:

@nashif can you take a look?

**Pull request merged**
