### PR TITLE
kernel: syscalls: no need to include all syscalls in binary

### LINKED ISSUE #58936: Userspace: Disabled APIs have impact on binary size
**Describe the bug**
Seen when investigating https://github.com/zephyrproject-rtos/zephyr/issues/58416

When building an application with `CONFIG_USERSPACE=y`, non used APIs have impact on final binary size.

**To Reproduce**
1. west build -p always -b nucleo_l073rz samples/hello_world -- -DCONFIG_USERSPACE=y
```
[181/181] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       29592 B       192 KB     15.05%
             RAM:        7544 B        20 KB     36.84%
        IDT_LIST:          0 GB         2 KB      0.00%
```
2. Make some modification in an API disabled. Eg, in `include/zephyr/drivers/counter.h`
```
- __syscall int counter_start(const struct device *dev);
```
Note: COUNTER API is disabled:
```
$ grep -r CONFIG_COUNTER build/nucleo_l073rz/
build/nucleo_l073rz/zephyr/.config:# CONFIG_COUNTER is not set
```
Note: Line should be removed: commenting or `#if 0` have no effect

3. Build again: `west build -p always -b nucleo_l073rz samples/hello_world -- -DCONFIG_USERSPACE=y`
4. Compare Flash footprint:
```
[181/181] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       29588 B       192 KB     15.05%
             RAM:        7544 B        20 KB     36.84%
        IDT_LIST:          0 GB         2 KB      0.00%
```

Final ROM size decreased by 4 bytes.

**Expected behavior**
Disabled APIs should not have impact on final binary size.

**Impact**
In USERSPACE config, binaries are bloated with disabled/non supported APIs.
In long term, some small devices might not support USERSPACE anymore because too much APIs are available in Zephyr.

### PR DESCRIPTION
**Pull request by dcpleung**
The syscall generation phase parses all header files to look for potential syscalls, and emits all the relevant files to enable syscalls. However, this results in all the syscall marshalling functions being included in the final binary. This is due to these functions being referred to inside the dispatch list, resulting in ineffective garbage collection during linking. Previous commits allows each drivers and subsystems to specify which header files containing syscalls are relevant. So this commit changes the syscall generation to only include the syscalls needed for the build in the syscall dispatch list and removing various bits related to that. This allows the linker to garbage collect unused syscall related function, and thus reducing final binary size.

Fixes #58936

### CODE REVIEW

**Comment by cfriedt** [comment]
Oooo - fancy! How many bytes are we talking about here?

**Comment by dcpleung** [comment]
> Oooo - fancy! How many bytes are we talking about here?

It depends on how many drivers and subsystems are enabled. Some pointers in the dispatch tables and a bunch of `z_mrsh_*` would no longer be there. So I am guessing... on average, a couple hundred bytes in `.text` and `.rodata`? We currently have a total of 465 syscalls. On `qemu_x86` and `tests/kernel/mem_protect/userspace`, the number drops to 149. So raw saving is more than 1k. However, with forced page alignment on `.text` and `.rodata`, there may not be that much savings in the final binaries.

**Review by cfriedt — DISMISSED** [review]

**Review by nashif — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by thedjnK — CHANGES_REQUESTED** [review]
Needs auxdisplay update

**Review by andyross — DISMISSED** [review]
This looks great.  Note that it would be possible to go one step farther and let an early linker pass do the real collection.  Maybe put weak aliases into the dispatch table, such that you can see the ones that are unused by the real code?

**Comment by dcpleung** [comment]
> This looks great. Note that it would be possible to go one step farther and let an early linker pass do the real collection. Maybe put weak aliases into the dispatch table, such that you can see the ones that are unused by the real code?

It will probably interfere with the kobject generation which can't tolerate things being moved around. I will look into it as a future enhancement.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
Flash drivers look OK.

**Review by nashif — APPROVED** [review]

**Pull request merged**
