### PR TITLE
manifest: update LVGL to v8.3.3

### PR DESCRIPTION
**Pull request by diegoherranz**
Related to https://github.com/zephyrproject-rtos/lvgl/pull/33

Thanks!

### CODE REVIEW

**Comment by diegoherranz** [comment]
As far as I can tell, the fail on the "twister-build (4)" tests is due to some warnings about certain LVGL code itself (from upstream), which are treated as error.

**Comment by pdgendt** [comment]
> As far as I can tell, the fail on the "twister-build (4)" tests is due to some warnings about certain LVGL code itself (from upstream), which are treated as error.

It's not only warnings treated as errors, but the warnings should be looked at as well. Can you investigate and/or report upstream if the `lvgl` samples have the same issues.
It might be caused by some (default) configuration?

**Comment by carlescufi** [comment]
@pdgendt @brgl @jfischer-no would be great if you could take a look at this

**Comment by carlescufi** [comment]
@diegoherranz could you please fix the CI test issues? These do seem related to your change.

**Comment by MaureenHelm** [comment]
@kisvegabor we're looking for someone to maintain the lvgl integration in zephyr. would you be interested or know someone?

**Comment by kisvegabor** [comment]
Hi Maureen,

We are working on some updates in LVGL. Due to these LVGL will contain built-in display drivers and interfaces to exiting systems. It will be possible to attache SPI, parallel port, etc driver to the built-in display and touch pad drivers. So all we need is a wrapper around Zephyr's SPI, parallel, etc driver API to allow using all the built-in display driver of LVGL. I think it will make maintaining LVGL in Zephyr much easier. 

Other than that, could you tell in more detail what are the complications with maintaining LVGL in Zephyr? 
Ideally LVGL should be just a drop-in library in Zephyr and we'd be happy to improve LVGL in a way to really make the integration that simple.

**Comment by jfischer-no** [comment]
> We are working on some updates in LVGL. Due to these LVGL will contain built-in display drivers and interfaces to exiting systems. It will be possible to attache SPI, parallel port, etc driver to the built-in display and touch pad drivers. So all we need is a wrapper around Zephyr's SPI, parallel, etc driver API to allow using all the built-in display driver of LVGL. I think it will make maintaining LVGL in Zephyr much easier.

Good news. We already have a display controller API and support multiple controllers. The best thing for your plans would be to remove the LVGL module from Zephyr completely. How you manage the Zephyr port is up to you, SPI/I2C driver API is publicly available.

**Comment by kisvegabor** [comment]
I'm glad that you like the idea. However, I think it still would be convenient for the user if LVGL were part of Zephyr in some form and  could be simply enabled in Kconfig or so. 

How complicated would it be if we ship a ready to use Kconfig file?

**Comment by jfischer-no** [comment]
> I'm glad that you like the idea. However, I think it still would be convenient for the user if LVGL were part of Zephyr in some form and could be simply enabled in Kconfig or so.

I do not think so, there is no benefit to the project. Rather the opposite, suppression of own development, maintenance overhead. The user could add LVGL to his downstream project as a module if needed, there is no need to keep anything upstream.

> 
> How complicated would it be if we ship a ready to use Kconfig file?

Please check the docs https://docs.zephyrproject.org/latest/develop/west/manifest.html

**Comment by pdgendt** [comment]
It feels like we're running in circles again like the discussions for `thrift` or `pigweed` (see https://github.com/zephyrproject-rtos/zephyr/pull/54013#discussion_r1084286269).
Please don't shoot me, the following is my humble opinion.

Having a GUI library inside `zephyr` feels like an addition instead of something that we have to drag along. We could probably benefit from having optional (lazy) modules, but that is entire other ongoing discussion.
It's a one-stop-getting-started with a sample instead of going to a project which may or may not support some version zephyr.

Regarding the question how to integrate LVGL in zephyr, I know there were suggestions in the past to have a `GPU` API in zephyr, which could in turn be used by something like LVGL as an abstraction layer.

**Comment by dleach02** [comment]
Will the twister errors be addressed soon?

**Comment by pdgendt** [comment]
@diegoherranz Do you think we could bring this PR (and the LVGL one) up-to-date? We can pick this up after the 3.4 feature freeze.

**Comment by pdgendt** [comment]
> @pdgendt I am very interested in moving this PR forward, from the discussion I gather that some twister issues need to be addressed, is that correct? And the preferred way of doing it would be to upstream those fixes into LVGL itsself and wait for another release thereafter?

zephyr has an LVLG fork where we accept patches: https://github.com/zephyrproject-rtos/lvgl
The twister logs from this PR are no longer available, so I'm not sure what is missing.

@diegoherranz are you still working on this? Could you rebase the changes, so we can verify what is needed to fix the build issues?

**Comment by faxe1008** [comment]
@pdgendt I took some time and fixed the twister issues that I found. I created my own fork based on @diegoherranz work right here: [https://github.com/faxe1008/zephyr-lvgl/tree/update_8.3.7](https://github.com/faxe1008/zephyr-lvgl/tree/update_8.3.7). While I was at it, I also merged the version 8.3.7. 

The tests run fine locally, tomorrow I will do some tests with actual hardware.

**Comment by kisvegabor** [comment]
> I have found some issues regarding allocation on my rebased version. I bisected the issue down to this commit:

How can I reproduce this issue? Do you see it with the latest commit in the `release/v8.3` branch?

**Comment by faxe1008** [comment]
@pdgendt I got the tests running locally and did a test with the lvgl sample, seems to run fine. 

PR in zephyr project: [https://github.com/zephyrproject-rtos/zephyr/pull/59656](https://github.com/zephyrproject-rtos/zephyr/pull/59656)
PR in lvgl project: [https://github.com/zephyrproject-rtos/lvgl/pull/41](https://github.com/zephyrproject-rtos/lvgl/pull/41)

Any feedback/help verifying the fixes added would be appreciated :^)

**Comment by kisvegabor** [comment]
This test deletes the active screen:
```c
  lv_obj_t *default_screen = lv_scr_act();
  lv_obj_t *new_screen = lv_obj_create(NULL);
  lv_scr_load(new_screen);
  lv_task_handler();

  lv_obj_t *act_screen = lv_scr_act(); //act_screen == new_screen
  lv_obj_del(new_screen);              //Deletes the active screen
  lv_scr_load(default_screen);         //This should be called before deleting the active screen
  lv_task_handler();

  act_screen = lv_scr_act();
```

**Comment by faxe1008** [comment]
@kisvegabor when checking the issue I also noticed that and indeed reordering the statements works. However I was not sure if you are supposed to be able to do this. Since the test already existed and ran fine in 8.2.0 I figured it was expected that this works.

**Comment by kisvegabor** [comment]
>  Since the test already existed and ran fine in 8.2.0 I figured it was expected that this works.

In v8.2 it was working only by accident and not by design :slightly_smiling_face:

**Comment by faxe1008** [comment]
@kisvegabor Ah ok, good to know. Anyways I reverted the "revert" :^), and changed the tests over at: 
[https://github.com/zephyrproject-rtos/zephyr/pull/59656](https://github.com/zephyrproject-rtos/zephyr/pull/59656)
Thanks 👍

**Comment by faxe1008** [comment]
This PR can be closed as 8.3.7 was merged to the module. Thanks @diegoherranz for the initial impulse and work on this 👍

**Pull request closed without merging**
