### PR TITLE
samples: boards: stm32 Rename README.md to README.rst

### PR DESCRIPTION
**Pull request by micropk**
Updated the README file extension from .md to the **expected** extension .rst

Signed-off-by: Peeyush Kumar <peeyush.ei@gmail.com>

### CODE REVIEW

**Comment by kpyush** [comment]
@henrikbrixandersen The earlier PR was not signed off by me properly.

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen The earlier PR was not signed off by me properly.

In the future just do a force push updating the commit instead of closing the PR and opening a new.

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by kpyush** [comment]
@henrikbrixandersen Sure, I was not aware of that option, will keep it in mind next time.

Thanks.

**Comment by kpyush** [comment]
@henrikbrixandersen Can you please add appropriate labels and reviewers?

Let me know if anything from my end is needed.

**Review by FRASTM — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Comment by kpyush** [comment]
> @kpyush please fix compliance issues reported

Hi @erwango,

I have updated the commit and the compliance check went through.

**Review by martinjaeger — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
