### PR TITLE
Add new Raytac MDBT53-DB-40 and MDBT53V-DB-40 board

### PR DESCRIPTION
**Pull request by RaytacStanley**
Adds support for Raytac MDBT53-DB-40 and MDBT53V-DB-40 demo board. These two boards pull out all the GPIOs of the module and connect them with pins without additional peripherals. It is very convenient for the development of various project programs.

### CODE REVIEW

**Comment by nordicjm** [comment]
@joerchan @anangl could you review please?

**Review by joerchan — APPROVED** [review]

**Comment by RaytacStanley** [comment]
Is there anything else that needs to be modified?

**Comment by RaytacStanley** [comment]
@anangl, Could you review, please?

**Comment by jukkar** [comment]
ping @anangl

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
