### PR TITLE
drivers: i2c_ll_stm32_v1: Reset i2c device on read/write error

### PR DESCRIPTION
**Pull request by lowlander**
Reset the i2c device when read or write return with an error code. This is to bring the i2c hardware back into a known
state after a hardware error (like EMC spikes) caused the device to lock up.

This tries to fix the same device lock up that happened when using IRQ's . After an error the i2c driver will never work anymore, the reset fixes that.

### CODE REVIEW

**Comment by lowlander** [comment]
@pabigot @ydamigos @MaureenHelm could one of you review this PR, it deals with the same I2C problems as #27291 did but for the non-IRQ case.

**Comment by pabigot** [comment]
I've got a v1-capable board arriving Monday, so will check it next week.  It should be able to make 2.4.

**Comment by lowlander** [comment]
> I've got a v1-capable board arriving Monday, so will check it next week.  It should be able to make 2.4.

That would be great, thanks

**Review by pabigot — APPROVED** [review]
I really need to get a test jig set up for this sort of thing, since I can't force a fault to verify the desired behavior, but I've at least been able to verify that it works normally.

**Comment by lowlander** [comment]
> I really need to get a test jig set up for this sort of thing, since I can't force a fault to verify the desired behavior, but I've at least been able to verify that it works normally.

@pabigot the easiest way to trigger i2c errors that trips the driver was to short SDA to GND, I got things to break with that rather easily.  

BTW thanks for testing

**Comment by lowlander** [comment]
@ydamigos @ldts @erwango @pabigot is this PR OK, or is there anything I have to change?

**Review by erwango — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
