### PR TITLE
samples: Bluetooth: Reduce heap for hci_ipc

### PR DESCRIPTION
**Pull request by Thalley**
Reducing the heap requirement for the hci_ipc sample from 8KiB to 4KiB. It has been tested in various configurations to work with 2300, but 4KiB was used to provide some leeway for future updates.

The heap requirement is not documented, and it is unclear why values lower than 2300 (not exact number) won't boot, and should be investigated further.

Memory has become a very scarce resource for especially the ISO builds for the nRF5340, which is why this is getting reduced.

### CODE REVIEW

**Review by cvinayak — DISMISSED** [review]

**Comment by Thalley** [comment]
#AutoPTS run zephyr nrf53 BAP/UCL/STR/BV-523-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests (1)</summary>BAP     BAP/UCL/STR/BV-523-C            PASS</details>

**Comment by jhedberg** [comment]
> it would be nice if it could instead rely on the `HEAP_MEM_POOL_ADD_SIZE_` (but that might not be possible?) https://docs.zephyrproject.org/latest/kernel/memory_management/heap.html#defining-the-heap-memory-pool

Agreed. There's actually a related issue that's been open for the other side of the IPC HCI transport for quite some time: #66698

**Comment by Thalley** [comment]
I can also mentioned that due to this bug https://github.com/zephyrproject-rtos/zephyr/issues/81044, the sample may build and flash, but without the necessary memory available, which breaks it silently.

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by cvinayak — APPROVED** [review]

**Comment by jhedberg** [comment]
@Thalley you seemed to agree with using `HEAP_MEM_POOL_ADD_SIZE_` in https://github.com/zephyrproject-rtos/zephyr/pull/81728#issuecomment-2492376813. Should I assume you're planning to do that in a follow-up PR since this one still just adjusts the absolute value?

**Comment by Thalley** [comment]
> Should I assume you're planning to do that in a follow-up PR since this one still just adjusts the absolute value?

No :) I don't know the requirements and investigating the memory uses of all the users of the heap will take time I don't have right now

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
> No :) I don't know the requirements and investigating the memory uses of all the users of the heap will take time I don't have right now

Fair enough. However, one of the challenges the ADD_SIZE tries to solve is precisely this need to know the needs of "everyone". Instead, you focus on each user individually and specify its particular need, without having to be concerned of other users.

**Review by kruithofa — APPROVED** [review]

**Pull request merged**
