### PR TITLE
tests: Add a test for fast console output

### PR DESCRIPTION
**Pull request by smrtos**
tests: Add a test for fast console output

Currently, the Intel CAVS platforms use a ring buffer
design for log output. And use a dedicated tool called
cavstool.py to extract logs from Intel CAVS boards.

The cavstool may lose logs or even extract nothing at all
from the board if log output is frequent enough.

Incomplete log can cause  twister to consider a
test fail because log output is used as the criteria.

This test is designed to be a gate-keeper for such
scenario. It just output certain amount of logs frequently on
CAVS15/18/25 platforms. It assumes nothing about how logging
is implemented on these platforms. Should the implementation
be changed, this test should still pass.

This test is dedicated to Intel CAVS platforms.
Other platforms will skip this test.

Signed-off-by: Ming Shao <ming.shao@intel.com>

(If this PR is merged, I think it's appropriate to merge https://github.com/zephyrproject-rtos/zephyr/pull/49010 as well.)

### CODE REVIEW

**Review by enjiamai — DISMISSED** [review]

**Review by enjiamai — DISMISSED** [review]

**Comment by teburd** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/49546 shows in the test case how a fast log (can be used with TC_PRINT and printk using LOG_PRINTK=y) will not lose data with HDA logging.

Using this logger with this test, the test passes.

**Comment by andyross** [comment]
Indeed, not really seeing the purpose here.  If you have a two-way communication with some kind of flow control protocol, then that's always going to work better (though never without any kind of loss or misbehavior, computers are finite resources).  Winstream is designed to work without driver support in a regime where all you have is a one-way view of memory.  Data loss is inevitable and expected, it's even in the docs.  If you don't want to miss it, don't log so much, increase the buffer size, and/or increase the polling frequency.

**Review by andyross — CHANGES_REQUESTED** [review]
Gotta be honest: I'm seeing (from over the fence, heh) some IMHO pretty terrible misunderstandings of what winstream is supposed to accomplish.  We can't have logging from early boot environments with a DMA driver, or frankly even a two-way protocol like the mtrace stuff @kv2019i has been working on.  Something needs to fill that gap, and that's what this protocol does.  You can't demand features from it that it can't provide, and you can't add features to it without breaking its intended users.

(There's a real deja vu thing going on here for me.  I fought and lost the same fight for an x86 boot-time serial driver that didn't interact with the rest of the system and couldn't be broken by integration, and so repeatedly had to go in and unbreak early logging every time I touched the platforms.  I'm not losing the fight this time, heh.  No messing with winstream.)

**Comment by teburd** [comment]
> Gotta be honest: I'm seeing (from over the fence, heh) some IMHO pretty terrible misunderstandings of what winstream is supposed to accomplish. We can't have logging from early boot environments with a DMA driver, or frankly even a two-way protocol like the mtrace stuff @kv2019i has been working on. Something needs to fill that gap, and that's what this protocol does. You can't demand features from it that it can't provide, and you can't add features to it without breaking its intended users.
> 
> (There's a real deja vu thing going on here for me. I fought and lost the same fight for an x86 boot-time serial driver that didn't interact with the rest of the system and couldn't be broken by integration, and so repeatedly had to go in and unbreak early logging every time I touched the platforms. I'm not losing the fight this time, heh. No messing with winstream.)

winstream is absolutely not going away for exactly those reasons. What is needed however is a lossless logging mechanism once enough bootstrapping is done.

**Review by nashif — CHANGES_REQUESTED** [review]
This test tests nothing, called winstream test yet, nothing related to winstream is being tested. I do not see how this can be useful.

**Comment by nashif** [comment]
> Maybe simply renaming the test to fast lossless console testing might be more apt. As that's what its trying to validate, that the console isn't losing data and that twister will mark the test as a success. I've sort of replicated that in the HDA log test as its useful anyways to suss out problems (as it did just that).

if there is an issue with the output, we will catch through other tests.

**Comment by smrtos** [comment]
@teburd 
I have renamed it to fast console output test. And yes, I just want to verify the frequent output is intact.

**Comment by smrtos** [comment]
@teburd @nashif  @andyross 
I have renamed it to fast console output test. And yes, I just want to verify the frequent output is intact.

**Pull request closed without merging**
