### PR TITLE
Devicetree docs for 3.5

### PR DESCRIPTION
**Pull request by mbolivar-ampere**
Document changes for the release

### CODE REVIEW

**Comment by jhedberg** [comment]
Wouldn't the migration guide be a more suitable place for some of this info?

**Comment by mbolivar-ampere** [comment]
This sort of thing has only ever gone into the release notes. Sorry if I missed it, but has there been a policy change on where things go?

**Comment by jhedberg** [comment]
> This sort of thing has only ever gone into the release notes. Sorry if I missed it, but has there been a policy change on where things go?

The latest guidance (earlier today) from @carlescufi in the #release channel was that duplication should be avoided between the two files and the "the migration guide should only contain the changes that are required by users in order to be able to continue building their application with no change in behavior (the required ones). The recommended ones are less clear. I will send a PR documenting this"

**Comment by jhedberg** [comment]
@mbolivar-ampere the commit message of commit a7b0ce614a2de9f366bdb84b3741e0da5855dac8 which introduced the migration guide also tries to explain what should go there.

**Comment by mbolivar-ampere** [comment]
Thanks; I asked some clarifying questions in the channel and will wait for the PR

**Review by jhedberg — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
