### PR TITLE
scripts: runners: add misc-flash runner

### PR DESCRIPTION
**Pull request by mbolivar**
Some boards require specific sequences of commands to run which aren't
generally useful for other boards. Add a catch-all runner to handle
these cases.

### CODE REVIEW

**Comment by mbolivar** [comment]
@nashif @carlescufi : please don't merge until @chen-png agrees this will work for up_squared

**Comment by chen-png** [comment]
> @nashif @carlescufi : please don't merge until @chen-png agrees this will work for up_squared

yes, it worked well for up squared board, thanks.

**Review by chen-png — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]
LGTM, can you rebase?

**Comment by galak** [comment]
@mbolivar can you rebase this?

**Comment by mbolivar** [comment]
> @mbolivar can you rebase this?

done. tacked a commit on top to keep the lists sorted so git has a better chance to rebase in the future

**Comment by mbolivar** [comment]
> tacked a commit on top to keep the lists sorted

... and fixed it

**Comment by chen-png** [comment]
@mbolivar  I am sorry i missed a problem. using this runner for up squared, after 'west build' command, I can use 'west flash  path_script  path_image' to run the test case on board, because i already know the path of image.
but if i use sanitycheck to run all tests, how can I pass the image path? because each image path is different according to the test case name.
for other runner, they all use the zephyr.elf image in the 'cfg' argument.

**Comment by mbolivar** [comment]
> but if i use sanitycheck to run all tests, how can I pass the image path? because each image path is different according to the test case name.

Would it work for you if the misc-flasher set some environment variables pointing to the binary, hex, and ELF files in the build directory, as well as the build directory itself?

I can't think of another way offhand.

**Comment by chen-png** [comment]
I think we can add the build directory into the agrs list.
because if  we want run a test on some boards, after 'west build' command, all test case image file we may use are in the build directory.

**Pull request merged**
