### PR TITLE
Xmc4xxx i2c patches

### PR DESCRIPTION
**Pull request by talih0**
Several xmc4xxx i2c related patches.

### CODE REVIEW

**Comment by talih0** [comment]
@billwatersiii ping

**Comment by billwatersiii** [comment]
> @billwatersiii ping

@talih0 , are you looking for a review and approval for the pull request?  I don't have official approval permission.  I have reviewed the updates and don't see any issues.  @ifyall

**Review by ifyall — DISMISSED** [review]

**Comment by talih0** [comment]
@ifyall, could you re-ack pls

**Review by ifyall — APPROVED** [review]

**Comment by talih0** [comment]
@teburd, could you have a look when you have a moment pls

**Review by carlescufi — APPROVED** [review]

**Comment by billwatersiii** [comment]
@talih0 , is there a sample application that uses these updates?

**Pull request merged**
