### PR TITLE
Kconfig cleanup drivers/mm

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
@dcpleung have a commit in here that changes the compatible for the tlb device on mtl.  I think that looks good, but do take a look.

**Review by dcpleung — APPROVED** [review]

**Comment by dcpleung** [comment]
> @dcpleung have a commit in here that changes the compatible for the tlb device on mtl. I think that looks good, but do take a look.

This looks good. Though I wish @jxstelter to have a say since they need to know about the DTS change in case SOF is doing an overlay.

**Comment by galak** [comment]
@MaureenHelm @dcpleung any ability to get that additional review on this.

**Comment by jxstelter** [comment]
The MTL specific TLB support is in file mm_drv_intel_adsp_mtl_tlb.c
It is added to source code list in 
https://github.com/galak/zephyr/blob/kconfig-cleanup/mm/drivers/mm/CMakeLists.txt
zephyr_sources_ifdef(
	CONFIG_MM_DRV_INTEL_ADSP_MTL_TLB
	mm_drv_intel_adsp_mtl_tlb.c
	)
Don't we need this changed to to have this MTL TLB code compiled?

**Comment by galak** [comment]
> 

Not sure I follow the question.  All the references there are to 'MTLB'

**Comment by jxstelter** [comment]
> @jxstelter - Not sure I follow the question. All the references there are to 'MTLB'

Oh, ignore my previous comment. It looks ok, I think.

**Review by marcinszkudlinski — APPROVED** [review]

**Review by jxstelter — APPROVED** [review]

**Pull request merged**
