### PR TITLE
drivers: i2c_dw: Fixes #75463, interrupt routine for i2c target mode

### PR DESCRIPTION
**Pull request by Manu3l0us**
When using the eeprom_target in 16-bit mode on rp2040, some issues in the addressing have been observed where the read was executed before all writes where finished.

### CODE REVIEW

**Comment by Manu3l0us** [comment]
This fixes #75463.

**Review by teburd — APPROVED** [review]
Seems ok to me, though would be good to get a rp reviewer

**Review by yonsch — APPROVED** [review]
Thanks

**Comment by dcpleung** [comment]
In the commit message, the "Fixes..." part should be last in the commit message, and not in the commit summary. Bonus is that GitHub would link the issue together if you have `Fixes #75463` in the commit message. Look at git history to see how it is usually done.

**Comment by Manu3l0us** [comment]
@dcpleung Thank you for the feedback. I will look at the history and improve the message. Can probably do it on Friday Morning CEST.

**Pull request merged**
