### PR TITLE
[RFC] FS_SEEK_RET_POS flag added to allow fs_seek returning new position on success

### PR DESCRIPTION
**Pull request by de-nordic**
This is RFC to gather some input on the idea of adding `FS_SEEK_RET_POS` flag to `fs_seek`, that combined with other `FS_SEEK_* `identifier will make `fs_seek` return new position within file on success instead of 0.

The change unfortunately modifies API, because the return type of `fs_seek` needs to be changed from int to `off_t`.

### CODE REVIEW

**Review by nvlsianpu — COMMENTED** [review]
Can you describe rationale behind this patch? An user case or what other FS API in the world behaves.

Patch looks good to me, I would say that if it can go in then I prefer to get the seek values always instead of on-demand option.

**Comment by de-nordic** [comment]
> 
> 
> Can you describe rationale behind this patch? An user case or what other FS API in the world behaves.
> 
This is provided to make it easier to implement lseek in POSIX form.
Some of file system drivers return new file position on success and with use of this flag we could simply use that value with lseek instead of calling ftell.

**Comment by de-nordic** [comment]
> Patch looks good to me, I would say that if it can go in then I prefer to get the seek values always instead of on-demand option.

Actually I didn't do that because I wanted to keep compatibility with user code; I am afraid that users may be checking if the `fs_seek` has been successful by comparing result to 0 in which case, making returning the new position default behavior, would break their code. This is the only reason I am doing it per request rather than default.

**Comment by nvlsianpu** [comment]
^^ good point.

**Comment by nvlsianpu** [comment]
@de-nordic any update on this patch?

**Comment by de-nordic** [comment]
> 
> I still think that better to be coherent and change this API as change is small.
> I believe optional version of API might imposed badly on user experience.

Wouldn't that require some release notes or some other notifications to developers?
@carles, what is you opinion?

**Comment by nvlsianpu** [comment]
^^ Each API change need to by recorded in release note under API paragraph.

**Comment by carlescufi** [comment]
Even if the API change is small, this is impactful, so we need to apply the [stable API change procedure](https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html#introducing-incompatible-changes)

**Comment by de-nordic** [comment]
> 
> 
> Even if the API change is small, this is impactful, so we need to apply the [stable API change procedure](https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html#introducing-incompatible-changes)

Yeah sure but what do you think regarding that comment: https://github.com/zephyrproject-rtos/zephyr/pull/28878#issuecomment-716496677

What is your opinion: do you also think that it is better to change `fs_seek` to return a new file position on return, instead of only when the flag is given, as I did it here.
@nvlsianpu rationale is that making the returned offset optional may give bad user experience, be misleading (https://github.com/zephyrproject-rtos/zephyr/pull/28878#issuecomment-716496677)
My rationale is that I don't want to force developers to change the code to support changed default behavior of the function.

**Pull request closed without merging**
