### PR TITLE
input: convert kscan_mchp_xec.c driver to input and shared keyboard scan code

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Last keyboard scanning driver converted to input and the common keyboard matrix library. This one had few implementation specific bits in what became the common code, I think I managed to maintain the previous behavior, but I don't have any hardware to test it so keep in mind it's build tested only.

If anyone could give this a run it'd be much appreciated, should work fine with both the kscan and input_dump tests.

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
Merge conflict, rebased.

**Comment by fabiobaltieri** [comment]
CI sad, fix: https://github.com/zephyrproject-rtos/zephyr/pull/65633

**Comment by fabiobaltieri** [comment]
@jvasanth1 @VenkatKotakonda @albertofloyd anyone?

**Comment by fabiobaltieri** [comment]
@jvasanth1 @VenkatKotakonda @albertofloyd happy new year!

**Review by jvasanth1 — DISMISSED** [review]
The changes look good

**Review by jvasanth1 — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]

**Pull request merged**
