### PR TITLE
MAINTAINERS: add self as maintainer of Intel ISH platform

### PR DESCRIPTION
**Pull request by kwd-doodling**
Add maintainer and collaborators for Intel ISH platform and related drivers

### CODE REVIEW

**Comment by kwd-doodling** [comment]
@nashif I submit this draft patch per Fabio's suggestion in https://github.com/zephyrproject-rtos/zephyr/pull/61085.
not sure if it's alright. please help review first.
should I add al ISH team members working on ISH drivers into the collaborators list?

**Comment by kwd-doodling** [comment]
should be CODEOWNERS file changed also?

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
> should be CODEOWNERS file changed also?

no need

**Comment by nashif** [comment]
@kwd-doodling  you need to fix the compliance issues

**Comment by kwd-doodling** [comment]
this patch is generated with github webpage. I'm denied to change it's commit message.
re-submitted in a new PR https://github.com/zephyrproject-rtos/zephyr/pull/61120.

**Pull request closed without merging**
