### PR TITLE
scripts: compliance: Another round of cleanups

### PR DESCRIPTION
**Pull request by carlescufi**
... and a small bugfix.

### CODE REVIEW

**Review by nashif — DISMISSED** [review]

**Review by stephanosio — DISMISSED** [review]

**Review by gmarull — DISMISSED** [review]

**Comment by talih0** [comment]
there's  a typo in the first commit (Fix regex) message: s/wiht/with

**Comment by carlescufi** [comment]
> there's a typo in the first commit (Fix regex) message: s/wiht/with

Thanks! fixed

**Review by stephanosio — COMMENTED** [review]
While we're at it:

s/desctiptions/descriptions
s/docuemntation/documentation

**Comment by carlescufi** [comment]
> While we're at it:
> 
> s/desctiptions/descriptions s/docuemntation/documentation

Fixed, thanks!

**Review by stephanosio — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
