### PR TITLE
net: Add CONFIG_NET_NATIVE option for selecting native IP

### LINKED ISSUE #18105: BSD socket offload with IPv4 and IPv6 disabled breaks many client-based net samples
**Is your feature request related to a problem? Please describe.**
When using the socket offload API where IPv4 and IPv6 are disabled, all net samples are broken due to their dependence on `NET_CONFIG_*` settings.

**Describe the solution you'd like**
In a perfect world, samples would still work -- the main issue being where to get things like peer server address.

**Describe alternatives you've considered**
Just starting the discussion.  I haven't explored alternatives yet.

**Additional context**
Devices like TI's SimpleLink Wifi and the upcoming modem context changes allow for them to be used without the majority of the Zephyr IP stack -- instead offloading the IP stack onto the NCP via the `NET_SOCKETS_OFFLOAD` config.

This saves quite a lot of flash and processing when combined with `CONFIG_IPV4=n` and `CONFIG_IPV6=n`, but means the user has to customize each networking sample.

### PR DESCRIPTION
**Pull request by jukkar**
Allow user to disable native IP stack and use offloaded IP
stack instead. It is also possible to enable both at the same
time if needed.

Fixes #18105

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
Only build tested like this:
```
$ cd samples/net/sockets/echo_client
$ cmake -B build -DBOARD=cc3220sf_launchxl -DOVERLAY_CONFIG=overlay-offload.conf
$ make -C build
```
overlay-offload.conf file
```
CONFIG_NET_NATIVE=n
CONFIG_NET_OFFLOAD=y
CONFIG_NET_SOCKETS_OFFLOAD=y
```

**Review by rlubos — COMMENTED** [review]
This looks very promising. I've tested these changes with nRF91 offloading, and all seems functional. Tested one of the samples, the numbers dropped from this (with default networking settings):
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      124024 B       976 KB     12.41%
            SRAM:       34976 B       128 KB     26.68%
        IDT_LIST:         120 B         2 KB      5.86%
```
to this (with `CONFIG_NET_NATIVE` disabled):
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      104736 B       976 KB     10.48%
            SRAM:         32 KB       128 KB     25.00%
        IDT_LIST:         120 B         2 KB      5.86%
```

I've noticed though that there are two heavy RAM users - `net_tc` and `net_pkt`. While I guess we could safely disable `net_tc` from the build, would the same apply for the `net_pkt`? I've experimented with disabling both (which resulted in this [this](https://github.com/zephyrproject-rtos/zephyr/files/3486364/native_stack_tweaks.txt) patch), and ended up with the following numbers:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      104288 B       976 KB     10.43%
            SRAM:       24128 B       128 KB     18.41%
        IDT_LIST:         120 B         2 KB      5.86%
```

**Comment by jukkar** [comment]
> While I guess we could safely disable `net_tc` from the build, would the same apply for the `net_pkt`?

I did not do full optimization yet, those two are good candidates to be disabled if only offloading is used. Thanks for reporting the numbers!

**Comment by jukkar** [comment]
New more optimized version. If socket offloading is enabled, then most of the code is not compiled in. Network offloading adds a bit more stuff as it requires net_context.

**Comment by mike-scott** [comment]
Few errors when I tested this on top of the new modem changes (socket offload):
```
subsys/net/ip/net_shell.c: In function 'tcp_cb':
subsys/net/ip/net_shell.c:1069:19: warning: implicit declaration of function 'net_tcp_get_recv_mss'; did you mean 'net_tcp_seq_cmp'? [-Wimplicit-function-declaration]
  u16_t recv_mss = net_tcp_get_recv_mss(tcp);
                   ^~~~~~~~~~~~~~~~~~~~
                   net_tcp_seq_cmp
subsys/net/ip/net_shell.c:1072:13: error: dereferencing pointer to incomplete type 'struct net_tcp'
     tcp, tcp->context,
             ^~
subsys/net/ip/net_shell.c:69:44: note: in definition of macro 'PR'
  shell_fprintf(shell, SHELL_NORMAL, fmt, ##__VA_ARGS__)
                                            ^~~~~~~~~~~
subsys/net/ip/net_shell.c:1076:5: warning: implicit declaration of function 'net_tcp_state_str'; did you mean 'net_tcp_seq_cmp'? [-Wimplicit-function-declaration]
     net_tcp_state_str(net_tcp_get_state(tcp)));
     ^~~~~~~~~~~~~~~~~
subsys/net/ip/net_shell.c:69:44: note: in definition of macro 'PR'
  shell_fprintf(shell, SHELL_NORMAL, fmt, ##__VA_ARGS__)
                                            ^~~~~~~~~~~
subsys/net/ip/net_shell.c:1076:23: warning: implicit declaration of function 'net_tcp_get_state'; did you mean 'net_pkt_get_data'? [-Wimplicit-function-declaration]
     net_tcp_state_str(net_tcp_get_state(tcp)));
                       ^~~~~~~~~~~~~~~~~
subsys/net/ip/net_shell.c:69:44: note: in definition of macro 'PR'
  shell_fprintf(shell, SHELL_NORMAL, fmt, ##__VA_ARGS__)
                                            ^~~~~~~~~~~
At top level:
subsys/net/ip/net_shell.c:1064:13: warning: 'tcp_cb' defined but not used [-Wunused-function]
 static void tcp_cb(struct net_tcp *tcp, void *user_data)
             ^~~~~~
```

**Comment by mike-scott** [comment]
(Using `lwm2m_client` sample and the error above was with `CONFIG_NET_NATIVE=y`)

Still testing with the latest modem changes, `lwm2m_client` and `CONFIG_NET_SHELL=n`, it fixes the compiles, but hangs execution in `subsys/net/lib/config/init.c`.   If I set `CONFIG_NET_CONFIG_AUTO_INIT=n`, then the sample comes all the way up and runs normally(!).

These are my results for the exact same build only changing `CONFIG_NET_NATIVE`:
```
[CONFIG_NET_NATIVE=y]
Memory region         Used Size  Region Size  %age Used
           FLASH:      122088 B         1 MB     11.64%
            SRAM:       53536 B       192 KB     27.23%
        IDT_LIST:         152 B         2 KB      7.42%

[CONFIG_NET_NATIVE=n]
Memory region         Used Size  Region Size  %age Used
           FLASH:      116000 B         1 MB     11.06%
            SRAM:       53184 B       192 KB     27.05%
        IDT_LIST:         152 B         2 KB      7.42%
```

Fairly remarkable flash savings!

When I tested

**Comment by jukkar** [comment]
> Still testing with the latest modem changes, `lwm2m_client` and `CONFIG_NET_SHELL=n`, it fixes the compile,

Seems that you did not had TCP enabled. Will send new version shortly that fixes this.

**Comment by jukkar** [comment]
> hangs execution in `subsys/net/lib/config/init.c`. If I set `CONFIG_NET_CONFIG_AUTO_INIT=n`

@mike-scott What board are you using in your test?

**Comment by rlubos** [comment]
Looks pretty good.

One reflection that comes to my mind, not directly related to this PR - the socket offloaded solutions I've seen rely on both `NET_OFFLOAD` and `NET_SOCKETS_OFFLOAD` because currently it's only possible to create offloaded network interface when `NET_OFFLOAD` is enabled:
https://github.com/zephyrproject-rtos/zephyr/blob/4524035bc8d5e8eb892bccc1ce9547b09e9c7f52/drivers/wifi/simplelink/simplelink.c#L195
https://github.com/zephyrproject-rtos/zephyr/blob/b78bf8d6c16497f882d1264a21b2fcb8e8b0aa11/subsys/net/ip/net_if.c#L3342

So as a next step, we'd need to allow to create offloaded network interfaces with `NET_SOCKETS_OFFLOAD` only, to fully utilize these optimizations.

**Comment by jukkar** [comment]
> So as a next step, we'd need to allow to create offloaded network interfaces with `NET_SOCKETS_OFFLOAD` only, to fully utilize these optimizations.

Yep, very true. I will look into this next.

**Comment by jukkar** [comment]
> https://github.com/zephyrproject-rtos/zephyr/blob/b78bf8d6c16497f882d1264a21b2fcb8e8b0aa11/subsys/net/ip/net_if.c#L3342

There is related discussion at #18117 where we were thinking about introducing L2 offload driver that would have support for `enable()` API. If that works gets into something then the offload handling in `net_if.c:net_if_up()` can be removed.

**Comment by pfalcon** [comment]
Stuff like `defined(CONFIG_NET_IPV6) && defined(CONFIG_NET_NATIVE)` indeed does look repetitive. Maybe indeed replace it with something like `NATIVE_IPV6` (either as header-level macro or as Kconfig level macro).

**Comment by jukkar** [comment]
> Stuff like `defined(CONFIG_NET_IPV6) && defined(CONFIG_NET_NATIVE)` indeed does look repetitive. Maybe indeed replace it with something like `NATIVE_IPV6` (either as header-level macro or as Kconfig level macro).

Yep, I was thinking that too but this initial version of this PR was done like this. There is still time to tweak the code into better shape.

**Comment by mike-scott** [comment]
> > hangs execution in `subsys/net/lib/config/init.c`. If I set `CONFIG_NET_CONFIG_AUTO_INIT=n`
> 
> @mike-scott What board are you using in your test?

Board is frdm_k64f with SARA R4 modem using lwm2m_client.  So you are correct, TCP was not enabled.

**Comment by jukkar** [comment]
This looks like 2.1 stuff so I will update the commit later after 2.1 opens. Setting the milestone to 2.1.

**Comment by jukkar** [comment]
Updated according to comments.

Some statistics:
Board: frdm_k64f
Sample: samples/net/lwm2m_client

**Socket offloaded stack**
```
CONFIG_MODEM_UBLOX_SARA=y
CONFIG_NET_NATIVE=n
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_ETH_MCUX=n
CONFIG_NET_L2_ETHERNET=n

Memory region         Used Size  Region Size  %age Used
           FLASH:      109364 B         1 MB     10.43%
            SRAM:       33664 B       192 KB     17.12%
        IDT_LIST:         120 B         2 KB      5.86%
```

**Native stack**
```
CONFIG_MODEM_UBLOX_SARA=y
CONFIG_NET_NATIVE=y
CONFIG_NET_SOCKETS_OFFLOAD=n
CONFIG_ETH_MCUX=n
CONFIG_NET_L2_ETHERNET=n

Memory region         Used Size  Region Size  %age Used
           FLASH:      149532 B         1 MB     14.26%
            SRAM:       44768 B       192 KB     22.77%
        IDT_LIST:         120 B         2 KB      5.86%
```

**Comment by mike-scott** [comment]
> So in this example, RAM usage is 24% and flash 26% smaller in offloaded stack if native IP stack is disabled.
@jukkar This will be very exciting to followup on in v2.1.

**Comment by jukkar** [comment]
Ping @mike-scott, @rlubos et al. We could start to think about merging this so please +1 if this looks ok to you.

**Review by mike-scott — APPROVED** [review]
LGTM.  Better to merge this sooner and let it play out over the dev cycle IMHO.

**Comment by vanti** [comment]
@jukkar @mike-scott Very promising changes. I gave it a try and rebuilt the echo sample on cc3220sf_launchxl against these, and got some link errors:

```
/home/a0792201local/zephyrproject-work/zephyr/drivers/wifi/simplelink/simplelink.c:71: undefined reference to `net_if_ipv4_set_gw'
/home/a0792201local/bin/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: /home/a0792201local/zephyrproject-work/zephyr/drivers/wifi/simplelink/simplelink.c:72: undefined reference to `net_if_ipv4_addr_add'
```

Are calls to 'net_if_ipv4_addr_add' and 'net_if_ipv4_set_gw' no longer needed when CONFIG_NET_SOCKETS_OFFLOAD=y? The echo sample seems to work ok after commenting these calls out.

**Comment by mike-scott** [comment]
> @jukkar @mike-scott Very promising changes. I gave it a try and rebuilt the echo sample on cc3220sf_launchxl against these, and got some link errors:
> 
> ```
> /home/a0792201local/zephyrproject-work/zephyr/drivers/wifi/simplelink/simplelink.c:71: undefined reference to `net_if_ipv4_set_gw'
> /home/a0792201local/bin/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: /home/a0792201local/zephyrproject-work/zephyr/drivers/wifi/simplelink/simplelink.c:72: undefined reference to `net_if_ipv4_addr_add'
> ```
> 
> Are calls to 'net_if_ipv4_addr_add' and 'net_if_ipv4_set_gw' no longer needed when CONFIG_NET_SOCKETS_OFFLOAD=y? The echo sample seems to work ok after commenting these calls out.

Those calls shouldn't be needed if you're using an offloaded network stack.

**Comment by vanti** [comment]
> Those calls shouldn't be needed if you're using an offloaded network stack.

I put up #19032 to fix this. After resolving the link errors, I see the following results for the echo sample:

**With CONFIG_NET_NATIVE=y**
```
Memory region         Used Size  Region Size  %age Used
           FLASH:       81168 B         1 MB      7.74%
            SRAM:       25792 B       256 KB      9.84%
        IDT_LIST:         104 B         2 KB      5.08%
```

**With CONFIG_NET_NATIVE=n**
```
Memory region         Used Size  Region Size  %age Used
           FLASH:       73024 B         1 MB      6.96%
            SRAM:       25504 B       256 KB      9.73%
        IDT_LIST:         104 B         2 KB      5.08%
```

Some decent size improvements. I can make CONFIG_NET_NATIVE=n into the default for SimpleLink wifi once this PR is merged.

**Comment by jukkar** [comment]
Rebased against latest master. Also cherry-picked the commit from #19032 so this PR is working out of the box in SimpleLink.

**Comment by jukkar** [comment]
> **With CONFIG_NET_NATIVE=y**
> 
> ```
> Memory region         Used Size  Region Size  %age Used
>            FLASH:       81168 B         1 MB      7.74%
>             SRAM:       25792 B       256 KB      9.84%
>         IDT_LIST:         104 B         2 KB      5.08%
> ```
> 
> **With CONFIG_NET_NATIVE=n**
> 
> ```
> Memory region         Used Size  Region Size  %age Used
>            FLASH:       73024 B         1 MB      6.96%
>             SRAM:       25504 B       256 KB      9.73%
>         IDT_LIST:         104 B         2 KB      5.08%
> ```

I wonder why the RAM usage dropped so little here. In my earlier compilations with frdm_k64f, the RAM usage dropped 24%.

**Review by rlubos — APPROVED** [review]
Thank you for this PR. I've verified it with nRF91 and the numbers looked fine for it - I've checked `ram_report`/`rom_report` and did not find anything suspicious. So at least for offloaded sockets, the RAM/ROM usage drop is significant.

As https://github.com/zephyrproject-rtos/zephyr/commit/a4f4f6d6f3c580e9230ec0b3de567bb786b3319e seems to resolve my provious concerns, I have nothing else to complain. LGTM :+1:

**Pull request merged**
