### PR TITLE
drivers: adc: tla2021: seperate thread, only when needed

### PR DESCRIPTION
**Pull request by maass-hamburg**
only use the separate thread, when
CONFIG_ADC_ASYNC is enabled.

### CODE REVIEW

**Comment by maass-hamburg** [comment]
ping

**Review by anangl — APPROVED** [review]

**Comment by maass-hamburg** [comment]
ping @decsny

**Comment by casparfriedrich** [comment]
Hi, sorry for the delay. I'm a but busy at the moment but I'll see that I have a look this week.

**Comment by decsny** [comment]
> Hi, sorry for the delay. I'm a but busy at the moment but I'll see that I have a look this week.

ping reminder

**Comment by maass-hamburg** [comment]
ping @casparfriedrich @decsny

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
