### PR TITLE
power: policy: recover deep sleep states from residency policy

### PR DESCRIPTION
**Pull request by wentongwu**
Commit c248cdf17e388acb0ef9b4a3b32cc9b4cac6a02d remove deep sleep states
    from residency policy based on SoC loses context in deep sleep states to
    avoid a "forever timeout" power-off the whole system. It's right if deep
    sleep means power off whole system only.

    One of deep sleep states is that most power domains are shut off, but
    except a few that retain just enough logic to allow the CPU to resume
    from the same point of execution where it went to sleep. This is well
    documented and implementations also have same behavior.

    For another deep sleep state, system off, sys_pm_ctrl_disable_state can
    prevent system off unexpectedly from being entered on long timeout. And
    sys_pm_force_power_state can help power off whole system.

### CODE REVIEW

**Comment by vanti** [comment]
FWIW "standby mode" on TI CC1352R1 matches the definition of a state where "most power domains are shut off, but except a few that retain
just enough logic to allow the CPU to resume from the same point of
execution where it went to sleep". In my PR #21465, I had originally made it into a deep sleep state, and then modified it to be a sleep state after seeing work in commit c248cdf17e388acb0ef9b4a3b32cc9b4cac6a02d. I am ok with reverting back, but I'd like to see an agreement on deep sleep's definition in Zephyr, to avoid reworking the same code.

I see 3 possible definitions for deep sleep thus far:

1. Deep sleep is equivalent to shutting off the device, and should not be entered automatically by the residency policy
2. Deep sleep is a state in which we can resume from the same point of execution where it went to sleep
3. A combination of 1 and 2, which means there needs to be a way to tell the residency policy to not automatically enter a deep sleep state that shuts off the device if that is not desired. I think this can currently be accomplished with sys_pm_ctrl_disable_state().

#3 is the most compatible with the current state in Zephyr (assuming this current PR gets in), given it'd justify why there are multiple deep sleep states (after all one is all that is needed to implement shut off). It'd also be in agreement with how things are done in samples/boards/nrf/system_off.

#1 imho is the one that is easiest to understand (sleep means resume, deep sleep doesn't). This would point to eliminating DEEP_SLEEP_2 and DEEP_SLEEP_3 as they don't make a lot of sense.

#2 would require a new API to be defined to shut off the CPU, given we can no longer implement it as a deep sleep state.

Personally I don't have a strong preference for any of these, but would love to move forward after there is an agreement on the definition.

**Comment by wentongwu** [comment]
> I am ok with reverting back, but I'd like to see an agreement on deep sleep's definition in Zephyr, to avoid reworking the same code.

@vanti if agree the reverting, please +1, thanks.

> #3 is the most compatible with the current state in Zephyr (assuming this current PR gets in), given it'd justify why there are multiple deep sleep states (after all one is all that is needed to implement shut off). It'd also be in agreement with how things are done in samples/boards/nrf/system_off.
> 
> #1 imho is the one that is easiest to understand (sleep means resume, deep sleep doesn't). This would point to eliminating DEEP_SLEEP_2 and DEEP_SLEEP_3 as they don't make a lot of sense.
> 
> #2 would require a new API to be defined to shut off the CPU, given we can no longer implement it as a deep sleep state.
> 
right, method #1 would abandon DEEP_SLEEP_2 and DEEP_SLEEP_3. And in the implementation of _sys_syspend, we have code like blow to turn on devices after resume from deep sleep.
```
        if (deep_sleep || low_power) {
                /* Turn on peripherals and restore device states as necessary */
                sys_pm_resume_devices();
        }
```
This shows that deep sleep states contains the state in which we can resume from the same point of execution where it went to sleep.

For shut off(or power off) whole system which I didn't consider carefully, I agree that take it also as one state of deep sleep states because the required new API would be most similar with current _sys_suspend. And if everyone agrees(I think we will) the combination of #2(resume from the same point of execution) and power off state, the solution will be that sys_pm_ctrl_disable_state can prevent system off unexpectedly from being entered on long timeout and sys_pm_force_power_state will help power off whole system.

@pabigot could you please take a look this PR. thanks

**Review by tyrantlizard77 — APPROVED** [review]

**Review by pabigot — CHANGES_REQUESTED** [review]
AFAICT this does exactly what the commit message says: it reverts PR #20950.  However, it does not address any of the concerns that led to that commit being merged.

The [documentation for deep sleep states](https://docs.zephyrproject.org/latest/reference/power_management/index.html#deep-sleep-state) says:

> CPU is power gated and loses execution context. Execution will resume
at OS startup code or at a resume point determined by a bootloader
that supports deep sleep resume.

This does not seem consistent with the commit message statement:

> One of deep sleep states is that most power domains are shut off, but except a few that retain just enough logic to allow the CPU to resume from the same point of execution where it went to sleep. This is well documented and implementations also have same behavior.

Note that `k_sleep(K_FOREVER)` cannot be assumed to mean the application intends to shut down to a deep-sleep mode,or even for a long time.  Such a thread can be woken by an external or peripheral interrupt that invokes `k_wakeup()`.  I do not believe it is *ever* acceptable to have a policy that allows `k_sleep()` of any duration, including `K_FOREVER`, to shut down and wake in a way that essentially restarts the application. https://github.com/zephyrproject-rtos/zephyr/pull/20950#issuecomment-561344723 supports this position.

At a higher level I feel Zephyr's power management infrastructure is rather incoherent.  There's system and device power management, with centralized and distributed policies.  It would be good to collect requirements and use cases from a variety of stakeholders and hardware vendors and agree on what functionality is needed, the terminology necessary to describe it, and an architecture that would support it.

In any case, #20950 should not be reverted until the reasons it was merged have been clearly addressed, at a minimum by clearly documenting what "deep sleep" means.

**Review by nashif — APPROVED** [review]
@pabigot  #20950 is breaking us. 
If the issue is documentation then the documentation should be fixed after this is reverted or another solution is found that does not break existing applications.

**Comment by wentongwu** [comment]
> The [documentation for deep sleep states](https://docs.zephyrproject.org/latest/reference/power_management/index.html#deep-sleep-state) says:
> 
> > CPU is power gated and loses execution context. Execution will resume
> > at OS startup code or at a resume point determined by a bootloader
> > that supports deep sleep resume.

@pabigot Usually that startup code will help resume to the same point of execution where it went to sleep with the help of saved context before going to deep sleep.

> This does not seem consistent with the commit message statement:
> 
> > One of deep sleep states is that most power domains are shut off, but except a few that retain just enough logic to allow the CPU to resume from the same point of execution where it went to sleep. This is well documented and implementations also have same behavior.
> 
> Note that `k_sleep(K_FOREVER)` cannot be assumed to mean the application intends to shut down to a deep-sleep mode,or even for a long time. Such a thread can be woken by an external or peripheral interrupt that invokes `k_wakeup()`. I do not believe it is _ever_ acceptable to have a policy that allows `k_sleep()` of any duration, including `K_FOREVER`, to shut down and wake in a way that essentially restarts the application. [#20950 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/20950#issuecomment-561344723) supports this position.
> 
> At a higher level I feel Zephyr's power management infrastructure is rather incoherent. There's system and device power management, with centralized and distributed policies. It would be good to collect requirements and use cases from a variety of stakeholders and hardware vendors and agree on what functionality is needed, the terminology necessary to describe it, and an architecture that would support it.
> 
> In any case, #20950 should not be reverted until the reasons it was merged have been clearly addressed, at a minimum by clearly documenting what "deep sleep" means.

I think ```
For another deep sleep state, system off, sys_pm_ctrl_disable_state can
prevent system off unexpectedly from being entered on long timeout. And
sys_pm_force_power_state can help power off whole system.
``` can address #20950, and above comments(https://github.com/zephyrproject-rtos/zephyr/pull/22084#issuecomment-577958374 and https://github.com/zephyrproject-rtos/zephyr/pull/22084#issuecomment-577434115) are trying to align the deep sleep.

**Comment by pabigot** [comment]
#20950 fixes a bug: In no circumstance should the default behavior of `k_sleep()` result in selecting a sleep level that turns off the system timer that is used to terminate sleep delays.  The existing description of what constitutes a deep sleep state, along with default Kconfig values, clearly permits turning off the system clock if the delay is at least 60 s.  I can't understand how that can be viewed as acceptable default behavior.  Consequently deep sleep states must not be entered by default due to the sleep-duration-based residency policy.

Using the options from https://github.com/zephyrproject-rtos/zephyr/pull/22084#issuecomment-577434115, I believe:
* option 1 "sleep means resume, deep sleep doesn't" is the simplest, is most consistent with existing documentation, and after #20950 is the current behavior.
* Zephyr's power management is too immature in most platforms to try to move to option 2 by adding generic API to resume, and certainly this can't be done in the remainder of this release cycle.
* I'd accept option 3 "residency supports sleep and deep sleep" but only if deep sleep support in residency is opt-in rather than opt-out.

IMO you should solve the Intel application breakage by taking the last option, which is simple and should have the least impact on the system as it currently exists.  All you'll need to do to make the Intel apps work is default-enable deep sleep residency support in whatever applications can support it.

And I certainly agree with
>  yes, we should align the definition first.

I don't think fixing one bug by re-introducing another bug is justified without (a) a consensus on which behavior is more reasonable and (b) clear documentation recording that consensus so we don't have to revisit this same discussion every three months.

**Comment by wentongwu** [comment]
> #20950 fixes a bug: In no circumstance should the default behavior of `k_sleep()` result in selecting a sleep level that turns off the system timer that is used to terminate sleep delays. The existing description of what constitutes a deep sleep state, along with default Kconfig values, clearly permits turning off the system clock if the delay is at least 60 s. I can't understand how that can be viewed as acceptable default behavior. Consequently deep sleep states must not be entered by default due to the sleep-duration-based residency policy.
> 

It's bug only for system off deep sleep state, but it's not for other deep sleep states(like state which allows to resume from the same point of execution where it went to sleep, etc). I think #20950 is based on just your own platform which supports only system off deep sleep state, but the change in #20950 will cause other deep sleep states supported by other platforms not working as before. Also power management sub-system already provides opt-out solution like below words, so it's better to follow current solution to address the bug. 

```
For another deep sleep state, system off, sys_pm_ctrl_disable_state can
prevent system off unexpectedly from being entered on long timeout. And
sys_pm_force_power_state can help power off whole system.

```
> Using the options from [#22084 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/22084#issuecomment-577434115), I believe:
> 
> * option 1 "sleep means resume, deep sleep doesn't" is the simplest, is most consistent with existing documentation, and after #20950 is the current behavior.
> * Zephyr's power management is too immature in most platforms to try to move to option 2 by adding generic API to resume, and certainly this can't be done in the remainder of this release cycle.

no one sleep state is mandatory, but for platform that already support it, the change in #20950 will break them.

> * I'd accept option 3 "residency supports sleep and deep sleep" but only if deep sleep support in residency is opt-in rather than opt-out.
> 
> IMO you should solve the Intel application breakage by taking the last option, which is simple and should have the least impact on the system as it currently exists. All you'll need to do to make the Intel apps work is default-enable deep sleep residency support in whatever applications can support it.
> 
> And I certainly agree with
> 
> > yes, we should align the definition first.
> 
> I don't think fixing one bug by re-introducing another bug is justified without (a) a consensus on which behavior is more reasonable and (b) clear documentation recording that consensus so we don't have to revisit this same discussion every three months.

**Comment by pabigot** [comment]
My assessment is based solely on [the documentation of what a deep sleep state is](https://docs.zephyrproject.org/latest/reference/power_management/index.html?highlight=deep%20sleep#deep-sleep-state).  There is no "my platform" here, nor is the exception limited to system off.    All deep sleep states are allowed to turn off the system clock, and that is not something that `k_sleep()` should be allowed to do by default.

Looks like we need to discuss this in dev review.

**Comment by wentongwu** [comment]
> All deep sleep states are allowed to turn off the system clock

ok, I never see these words in your commit of PR #20950. Also I copy the documentation you mentioned above here to help anyone trying to find these words. If you are saying` "CPU is power gated and loses execution context."`, SysTick of Cortex M will be turned off if CPU is power gated, but not any platform will use SysTick as system timer; even SysTick as system timer, using a second frequency reduced and clock independent timer when in deep sleep state is also a normal SoC design; Also Zephyr supports other architectures not only Arm. I hope we can align the deep sleep states.  

```
Deep Sleep State
CPU is power gated and loses execution context. Execution will resume at OS startup code or at a resume point determined by a bootloader that supports deep sleep resume. Depending on the SOC’s implementation of the power saving feature, it may turn off power to most devices. RAM may be retained by some implementations, while others may remove power from RAM saving considerable power. Power states in this category save more power than Sleep states and would have higher wake latencies.
```

**Review by pabigot — APPROVED** [review]

**Comment by pabigot** [comment]
OK, I've had a chance to go back through this, and am withdrawing my objection.

My requirement is that `k_sleep()` must never, by default, cause the processor to go to a sleep state that loses execution context.  That rule should apply even when `CONFIG_SYS_POWER_MANAGEMENT=y`.

What I didn't see clearly is that for `k_sleep()` to  happen the application must also explicitly select one or both of `CONFIG_SYS_POWER_SLEEP_STATES` or `CONFIG_SYS_POWER_DEEP_SLEEP_STATES`.

So the unacceptable behavior is not enabled by default.  I'm not sure how I got confused about this, and apologize for wasting the time.

**Pull request merged**
