### PR TITLE
sensor: fxos8700: Convert to new DT_<COMPAT>_<INSTANCE> defines

### PR DESCRIPTION
**Pull request by cybertale**
The old defines make the Shippable tests fail. Convert the fixing
ups for fxos8700 to use new defines introduced in #12491.

Signed-off-by: Song Qiang <songqiang1304521@gmail.com>

### CODE REVIEW

**Comment by cybertale** [comment]
@galak

**Comment by galak** [comment]
> The old defines make the Shippable tests fail. Convert the fixing
> ups for fxos8700 to use new defines introduced in #12491.

which CI test is failing?

**Comment by cybertale** [comment]
@galak tests/drivers/build_all

**Comment by galak** [comment]
> @galak tests/drivers/build_all

how are you seeing the failure, when I build via sanitycheck I don't see any issue.

**Comment by cybertale** [comment]
Manually select this driver in menuconfig and build system will complain he can not find some defines, please have a look at the shippable build log of #13447 @galak




| |
宋强
|
|
邮箱：songqiang.1304521@163.com
|

签名由 网易邮箱大师 定制

On 03/11/2019 07:35, Kumar Gala wrote:

@galak tests/drivers/build_all

how are you seeing the failure, when I build via sanitycheck I don't see any issue.

**Review by galak — APPROVED** [review]

**Pull request merged**
