### PR TITLE
device-tree: binding support for spi-nor devices

### PR DESCRIPTION
**Pull request by pabigot**
This is a step towards supporting device tree for the SPI NOR driver.  It is not mergeable and probably doesn't pass tests; the purpose is to get feedback on whether this is the right path before I waste too much time.

This effort has revealed a lot of gaps:
* Linux device-tree does not specify flash size, because the driver should be able to figure it out with CFI commands.  That capability needs to be implemented; for now, there's a `size` property in the binding.
* The driver wants to know the page and sector size.  Linux doesn't need to ask.  Need to figure out why.  For now these remain Kconfig options.
* Zephyr SPI CS control wants a delay after asserting CS.  The device tree bindings have no provision for providing one.  What to do?  For now, it's a Kconfig option---added, because somehow the spi-nor driver was merged without any support to configure the option it requires.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Looks good, can we remove dts/bindings/slave/spi,flash.yaml?

**Comment by pabigot** [comment]
@galak done.  Also updated the intel_s1000_crb to use the new bindings.  I can't test that, though, since the xcc toolchain variant is required and doesn't appear to be recognized even with 0.10beta5.

* 2ae438d5de dts: flash: add bindings for jedec,spi-nor
* eb9389493e boards: particle: add bindings for on-board flash
* 6234a696ff boards: nrf52840_pca10056: add bindings for on-board serial flash
* 8680de87b6 drivers: flash: spi-nor: update towards device-tree support
* 04fe28f49a dts: intel_s1000: switch flash to jedec spi-nor
* 445bb3be08 dts: bindings: cleanup mtd descriptions

**Comment by pabigot** [comment]
Removed DNM as this got basic feedback suggesting the approach was acceptable.  Needs testing on intel_s1000_crb and @galak revisit review.

**Comment by pabigot** [comment]
Rebased to deal with conflict, removing `dts_fixup.h`

* cb49815071 dts: flash: add bindings for jedec,spi-nor
* 8823610f9d drivers: flash: spi-nor: update towards device-tree support
* 615bd9a76e boards: particle: add bindings for on-board flash
* 0adb020e2b boards: nrf52840_pca10056: add bindings for on-board serial flash
* b7b81f707e dts: intel_s1000_crb: switch flash to jedec spi-nor
* 4f85e86c3f dts: bindings: cleanup mtd descriptions

**Review by galak — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by nashif** [comment]
@pabigot @galak  getting this now:

```
home/nashif/Work/zephyrproject/zephyr/drivers/flash/spi_nor.c: In function ‘spi_nor_erase’:
/home/nashif/Work/zephyrproject/zephyr/drivers/flash/spi_nor.c:276: error: ‘FLASH_ERASE_BLOCK_SIZE’ undeclared (first use in this function)
/home/nashif/Work/zephyrproject/zephyr/drivers/flash/spi_nor.c:276: error: (Each undeclared identifier is reported only once
/home/nashif/Work/zephyrproject/zephyr/drivers/flash/spi_nor.c:276: error: for each function it appears in.)
/home/nashif/Work/zephyrproject/zephyr/drivers/flash/spi_nor.c: At top level:
/home/nashif/Work/zephyrproject/zephyr/drivers/flash/spi_nor.c:388: error: ‘FLASH_ERASE_BLOCK_SIZE’ undeclared here (not in a function)
/home/nashif/Work/zephyrproject/zephyr/drivers/flash/spi_nor.c:409: error: ‘FLASH_WRITE_BLOCK_SIZE’ undeclared here (not in a function)
```

**Pull request merged**
