### PR TITLE
board: mimxrt1010_evk: add linkserver support

### PR DESCRIPTION
**Pull request by hakehuang**
linkserver supports rt1010_evk from 1.5.30

### CODE REVIEW

**Review by DerekSnell — COMMENTED** [review]
Hi @hakehuang ,
Thank you for contributing LinkServer support for this board.  But we should also update the board doc page, and document this support in the Debug Probe section.

**Review by decsny — DISMISSED** [review]

**Comment by danieldegrasse** [comment]
Currently the documentation for the RT1010 EVK states the following:

> A debug probe is used for both flashing and debugging the board. This board is configured by default to use the [OpenSDA DAPLink Onboard Debug Probe](https://builds.zephyrproject.io/zephyr/pr/73019/docs/develop/flash_debug/probes.html#opensda-daplink-onboard-debug-probe), however the [pyOCD Debug Host Tools](https://builds.zephyrproject.io/zephyr/pr/73019/docs/develop/flash_debug/host-tools.html#pyocd-debug-host-tools) do not yet support programming the external flashes on this board so you must reconfigure the board for one of the following debug probes instead.

I think as part of this PR, we should update this blurb to clarify that the onboard debug firmware is supported out of the box by LinkServer (unless the firmware needs to be updated before it functions with LinkServer)

**Comment by hakehuang** [comment]
> I think as part of this PR, we should update this blurb to clarify that the onboard debug firmware is supported out of the box by LinkServer (unless the firmware needs to be updated before it functions with LinkServer)

let me update it

**Comment by teburd** [comment]
pyocd works fine on this board and all the imxrt boards I've tried it on, the docs are out of date

**Review by dleach02 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Comment by hakehuang** [comment]
> pyocd works fine on this board and all the imxrt boards I've tried it on, the docs are out of date

pyocd is working in this board, but the we are adding linkserver. And pyocd thing is complex, new boards need use `pyocd pack update` which is not document in any zephyr document. I will follow up with our pyocd maintainer for more clear view on pyocd

**Pull request merged**
