### PR TITLE
logging: Rafactor LOG_MODULE_REGISTER and LOG_MODULE_DECLARE macros

### LINKED ISSUE #11078: NET_L2_BT has the wrong dependencies
Sample: net/http_server for 96b_carbon board with overlay-netusb.conf.

Following warning during CMake:

```
warning: NET_6LO (defined at subsys/net/ip/Kconfig.ipv6:121) has direct dependencies NET_IPV6 && !NET_RAW_MODE && NETWORKING with value n, but is currently being y-selected by the following symbols:
 - NET_L2_BT (defined at /home/user/zephyr/boards/arm/96b_carbon/Kconfig.defconfig:70, subsys/net/l2/Kconfig:16), with value y, direct dependencies (NETWORKING && BOARD_96B_CARBON) || NETWORKING (value: y), and select condition NETWORKING (value: y)
```

As the outcome NET_6LO is set and 6lo.c file is compiled (CMakeLists.txt: `zephyr_library_sources_ifdef(CONFIG_NET_6LO          6lo.c)`) but Kconfig options are cut because in kconfig NET_6LO options depends on NET_IPV6 option which is disabled.

I'm not sure if this is framework error or board configuration error.
Note that this error is not visible on master but appeared on branch which is using one of the kconfig flag which is not present (https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/25994/1/tests).

### PR DESCRIPTION
**Pull request by nordic-krch**
Changed LOG_MODULE_REGISTER and LOG_MODULE_DECLARE macros to take log
level as optional parameter. LOG_MODULE_DECLARE can now also be used
in static inline functions in headers. Added LOG_LEVEL_SET macro
which is used when instance logging API is used to indicate maximal
log level compiled into the file.

This is based on #10215 but LOG_MODULE_REGISTER/LOG_MODULE_DECLARE have been made backward compatible to be able to use following:

```
#define LOG_LEVEL CONFIG_LEVEL
LOG_MODULE_REGISTER(name);
```

or
```
LOG_MODULE_REGISTER(name, CONFIG_LEVEL);
```

With this approach we will be able to merge that and gradually adapt modules. #10215 was huge and can even force other reworks (https://github.com/zephyrproject-rtos/zephyr/pull/10215#issuecomment-435368011)

Fixes #11078.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
doc changes look OK, but can't verify CI results because of other errors.

**Comment by nordic-krch** [comment]
@nashif, do you know who could help regarding nios2 compilation error. It fails with following error:
```
 warning: Unable to reach log_dynamic_sample_module (at 0x0040020c) from the global pointer (at 0x00408390) because the offset (-33156) is out of the allowed range, -32678 to 32767.
```
Googling reveals that issue exists but rarely solution is proposed. Here (https://www.intel.com/content/dam/www/programmable/us/en/pdfs/literature/hb/nios2/n2sw_nii52004.pdf) I've found that is related to  _global pointer register_ and it can be disabled using `-G n` compiler option (section 6-43). I've tried that with no success.

**Review by jukkar — COMMENTED** [review]
minor nit pick for commit msg, +1 to networking changes

**Comment by pfalcon** [comment]
@nordic-krch : Besides nios2 issue, there're other errors:

Sanitycheck / 96b_carbon:samples/net/http_server/test_usbnet_ecm / 96b_carbon/samples/net/http_server/test_usbnet_ecm 
~~~
FAILED: ccache /opt/sdk/zephyr-sdk-0.9.3/sysroots/x86_64-pokysdk-linux/usr/bin/arm-zephyr-eabi/arm-zephyr-eabi-gcc -DBUILD_VERSION=zephyr-v1.13.0-1583-g448e21c947 -DKERNEL -DSTM32F401xE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D_FORTIFY_SOURCE=2 -D__ZEPHYR__=1 -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/kernel/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/arch/arm/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/soc/arm/st_stm32/stm32f4 -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/soc/arm/st_stm32/stm32f4/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/soc/arm/st_stm32/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/boards/arm/96b_carbon -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include/drivers -Izephyr/include/generated -isystem /opt/sdk/zephyr-sdk-0.9.3/sysroots/x86_64-pokysdk-linux/usr/lib/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/include -isystem /opt/sdk/zephyr-sdk-0.9.3/sysroots/x86_64-pokysdk-linux/usr/lib/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/include-fixed -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/lib/libc/minimal/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/cmsis/Include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/st/stm32cube/stm32f4xx/soc -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/st/stm32cube/stm32f4xx/drivers/include -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/st/stm32cube/stm32f4xx/drivers/include/Legacy -I/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/net/lib/dns/. -Os -g -Wall -Wformat -Wformat-security -Wno-format-zero-length -imacros /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/out-2nd-pass/96b_carbon/samples/net/http_server/test_usbnet_ecm/zephyr/include/generated/autoconf.h -ffreestanding -Wno-main --sysroot /opt/sdk/zephyr-sdk-0.9.3/sysroots/armv5-zephyr-eabi/usr -mthumb -mcpu=cortex-m4 -Werror -Wno-deprecated-declarations -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -Wno-pointer-sign -Wno-unused-but-set-variable -fno-reorder-functions -fno-defer-pop -Werror=implicit-int -Wpointer-arith -ffunction-sections -fdata-sections -mabi=aapcs -march=armv7e-m -std=c99 -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj   -c /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/samples/net/http_server/src/main.c
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/samples/net/http_server/src/main.c:40:2: error: #error "TCP connections over Bluetooth need CONFIG_NET_CONTEXT_NET_PKT_POOL " "defined."
 #error "TCP connections over Bluetooth need CONFIG_NET_CONTEXT_NET_PKT_POOL "\
  ^~~~~
~~~


Please rebase or something.

**Comment by pfalcon** [comment]
@nordic-krch:

> help regarding nios2 compilation error

Well, it's in samples/subsys/logging/logger/samples.logger, so it's all yours to pluck "unneeded" stuff from it.

> can be disabled using -G n compiler option

That doesn't look like gcc option.

**Comment by pfalcon** [comment]
@nordic-krch :
~~~
-:357: ERROR:MULTISTATEMENT_MACRO_USE_DO_WHILE: Macros with multiple statements should be enclosed in a do - while loop
#357: FILE: include/logging/log.h:309:
+#define _LOG_MODULE_DATA_CREATE(_name, _level)			\
+	_LOG_MODULE_CONST_DATA_CREATE(_name, _level);		\
+	_LOG_MODULE_DYNAMIC_DATA_COND_CREATE(_name)

-:419: WARNING:COMPLEX_MACRO: Macros with complex values should be enclosed in parentheses
#419: FILE: include/logging/log.h:346:
+#define LOG_MODULE_REGISTER(...)					\
+	_LOG_EVAL(							\
+		_LOG_LEVEL_RESOLVE(__VA_ARGS__),			\
+		(_LOG_MODULE_DATA_CREATE(_LOG_ARG1(__VA_ARGS__),	\
+				      _LOG_LEVEL_RESOLVE(__VA_ARGS__))),\
+		()/*Empty*/						\
+	)								\
+	LOG_MODULE_DECLARE(__VA_ARGS__)

- total: 1 errors, 1 warnings, 907 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

Your patch has style problems, please review.

NOTE: Ignored message types: AVOID_EXTERNS BRACES CONFIG_EXPERIMENTAL CONST_STRUCT DATE_TIME FILE_PATH_CHANGES MINMAX NETWORKING_BLOCK_COMMENT_STYLE PRINTK_WITHOUT_KERN_LEVEL SPLIT_STRING VOLATILE
~~~

**Review by erwango — APPROVED** [review]

**Comment by carlescufi** [comment]
@nordic-krch can you fix CI?

**Comment by nordic-krch** [comment]
@pfalcon @carlescufi CI is fixed with macro thing exception. This type of macros are not accepted by checkpatch and cannot be fixed (e.g. macro is used outside function so cannot be wrapped into `do{}while(0)` loop.

**Comment by nordic-krch** [comment]
please note that there is one commit with actual change and rest is fixing. Fixing includes:
- adding `;` to LOG_MODULE_REGISTER call. Now it is obligatory, previously it was accepted without `;`
- adding missing `CONFIG_<MODULE>_LOG_LEVEL` - previously there was no compilation error when define was used in code but actually didn't exist. Now it is detected.
- #11078 thing
- nios2 global pointer register, @nashif, please take a look at https://github.com/zephyrproject-rtos/zephyr/pull/11035/commits/2da87c493ecd289c4fe97444e7f9d9933a137d43 which is current workaround for nios2. If better workaround exists please let me know.

**Comment by pfalcon** [comment]
More specifically:

~~~
-:373: ERROR:MULTISTATEMENT_MACRO_USE_DO_WHILE: Macros with multiple statements should be enclosed in a do - while loop
#373: FILE: include/logging/log.h:309:
+#define _LOG_MODULE_DATA_CREATE(_name, _level)			\
+	_LOG_MODULE_CONST_DATA_CREATE(_name, _level);		\
+	_LOG_MODULE_DYNAMIC_DATA_COND_CREATE(_name)

-:435: WARNING:COMPLEX_MACRO: Macros with complex values should be enclosed in parentheses
#435: FILE: include/logging/log.h:346:
+#define LOG_MODULE_REGISTER(...)					\
+	_LOG_EVAL(							\
+		_LOG_LEVEL_RESOLVE(__VA_ARGS__),			\
+		(_LOG_MODULE_DATA_CREATE(_LOG_ARG1(__VA_ARGS__),	\
+				      _LOG_LEVEL_RESOLVE(__VA_ARGS__))),\
+		()/*Empty*/						\
+	)								\
+	LOG_MODULE_DECLARE(__VA_ARGS__)

- total: 1 errors, 1 warnings, 943 lines checked
~~~


+1 from me override checkpatch here. (No comments on the patch itself, just trying to help with triaging PRs.)

**Review by nashif — APPROVED** [review]

**Pull request merged**
