### PR TITLE
mgmt: mcumgr: Move zephyr_grp to lib/cmd folder

### PR DESCRIPTION
**Pull request by nordicjm**
Moves the zephyr_grp commands to the same directory as the other
mgmt command handlers.

### CODE REVIEW

**Review by nvlsianpu — DISMISSED** [review]

**Comment by de-nordic** [comment]
Shouldn't we, with the move, rename the zephyr_grp directory to zephyr_basic?

**Comment by nordicjm** [comment]
> Shouldn't we, with the move, rename the zephyr_grp directory to zephyr_basic?

If we do this, it's breaking changes for existing usage of this module, can change it or leave it as-is

**Comment by de-nordic** [comment]
> > Shouldn't we, with the move, rename the zephyr_grp directory to zephyr_basic?
> 
> If we do this, it's breaking changes for existing usage of this module, can change it or leave it as-is

How change of directory name can break it? You have just move it, which is basically equivalent of renaming it when you look at the directory path. I am not talking about changing Kconfig option names.

**Comment by nordicjm** [comment]
@de-nordic Renamed

**Review by de-nordic — DISMISSED** [review]

**Review by nvlsianpu — DISMISSED** [review]

**Review by de-nordic — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
