### PR TITLE
logging: add arguments counting in log_generic

### LINKED ISSUE #10348: valgrind detected issue in logger, during msg free
`Valgrind` is detecting an issue, when the logger frees messages:

==18932== Conditional jump or move depends on uninitialised value(s)
==18932==    at 0x804AC96: log_is_strdup (log_core.c:539)
==18932==    by 0x804AEEF: msg_free (log_msg.c:51)
==18932==    by 0x804AFB8: log_msg_put (log_msg.c:86)
==18932==    by 0x804A971: msg_process (log_core.c:369)
==18932==    by 0x804A9D2: log_process (log_core.c:383)
==18932==    by 0x804A4A3: msg_finalize (log_core.c:65)
==18932==    by 0x804A549: log_n (log_core.c:137)
==18932==    by 0x804A6AB: log_generic (log_core.c:193)
==18932==    by 0x8048F83: log_handler (ext_log_system_adapter.c:36)
==18932==    by 0x8048E6F: ext_log_system_foo (ext_log_system.c:17)
==18932==    by 0x80494FA: external_log_system_showcase (main.c:218)
==18932==    by 0x80495D7: log_demo_thread (main.c:267)

Steps to reproduce:
```
cmake ../samples/subsys/logging/logger/  -GNinja -DBOARD=native_posix  -DCONFIG_NO_OPTIMIZATIONS=y
ninja
valgrind zephyr/zephyr.exe
```

The full log until that point:
```
***** Booting Zephyr OS zephyr-v1.13.0-600-gf7eb0c9 *****
Module logging showcase.
[00:00:00.130,000] <inf> sample_module: log in test_module 11
Disabling logging in the sample_module module
Function called again but with logging disabled.
Instance level logging showcase.
[00:00:00.130,000] <inf> sample_instance.inst1: counter_value: 0
[00:00:00.130,000] <wrn> sample_instance.inst1: Example of hexdump:
01 02 03 04             |....    
[00:00:00.130,000] <inf> sample_instance.inst2: counter_value: 0
[00:00:00.130,000] <wrn> sample_instance.inst2: Example of hexdump:
01 02 03 04             |....    
Changing filter to warning on sample_instance.inst1 instance.
[00:00:00.130,000] <wrn> sample_instance.inst1: Example of hexdump:
01 02 03 04             |....    
[00:00:00.130,000] <inf> sample_instance.inst2: counter_value: 1
[00:00:00.130,000] <wrn> sample_instance.inst2: Example of hexdump:
01 02 03 04             |....    
Disabling logging on both instances.
Function call on both instances with logging disabled.
Severity levels showcase.
[00:00:00.130,000] <err> main: Error message example.
[00:00:00.130,000] <wrn> main: Warning message example.
[00:00:00.130,000] <inf> main: Info message example.
String logging showcase.
[00:00:00.130,000] <inf> main: Logging transient string:transient_string
Severity levels showcase.
[00:00:00.130,000] <err> main: Error message example.
[00:00:00.130,000] <wrn> main: Warning message example.
[00:00:00.130,000] <inf> main: Info message example.
Logging performance showcase.
[00:00:00.130,100] <inf> main: performance test - log message 0
[00:00:00.130,200] <inf> main: performance test - log message 1
Estimated logging capabilities: 1000000 messages/second
Logs from external logging system showcase.
[00:00:00.130,300] <err> ext_log_system: critical level log
==18932== Thread 5:
==18932== Conditional jump or move depends on uninitialised value(s)
==18932==    at 0x804AC96: log_is_strdup (log_core.c:539)
==18932==    by 0x804AEEF: msg_free (log_msg.c:51)
==18932==    by 0x804AFB8: log_msg_put (log_msg.c:86)
==18932==    by 0x804A971: msg_process (log_core.c:369)
==18932==    by 0x804A9D2: log_process (log_core.c:383)
==18932==    by 0x804A4A3: msg_finalize (log_core.c:65)
==18932==    by 0x804A549: log_n (log_core.c:137)
==18932==    by 0x804A6AB: log_generic (log_core.c:193)
==18932==    by 0x8048F83: log_handler (ext_log_system_adapter.c:36)
==18932==    by 0x8048E6F: ext_log_system_foo (ext_log_system.c:17)
==18932==    by 0x80494FA: external_log_system_showcase (main.c:218)
==18932==    by 0x80495D7: log_demo_thread (main.c:267)
==18932== 
[00:00:00.130,300] <err> ext_log_system: error level log, 1 arguments: 1
[00:00:00.130,300] <wrn> ext_log_system: warning level log, 2 arguments: 1 2
...
```

### PR DESCRIPTION
**Pull request by nordic-krch**
Log_generic() can be used by external logger systems to map to zephyr
logger subsystem. Function has variable number of arguments. So far
logger assumed maximal number of arguments to avoid scanning
string to count number of arguments. In outcome, uninitialized memory
was treated as valid argument in a message (but discarded when actual
string formatting took place). Valgrind complained about that so
log_generic() has been extended to scan the string and count number
of arguments and build message with valid number of arguments.

Fixes #10348.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by aescolar** [comment]
@nordic-krch : The issue seems to be still there in this branch.
Are you able to compile for native_posix and run in valgrind on your side?

**Review by aescolar — DISMISSED** [review]
~The valgrind detected issue is still there..~

**Review by pizi-nordic — CHANGES_REQUESTED** [review]

**Review by pizi-nordic — CHANGES_REQUESTED** [review]
We were not decided to scan format string when we added `log_strdup()` in order to maximize logger performance even if not doing that introduced risk of log data corruption. Here we blindly introducing the same feature to satisfy valgrind....

IMHO we have to decide:
- Should we scan format string and make log_strdup() safe as well as valgrind happy

OR

- Should we focus on performance and solve this issue by simple comment, that logger is designed in certain way in order to achieve maximum possible speed.

**Comment by nordic-krch** [comment]
@pizi-nordic i feel your bitterness :) but note following:
- this is about a function which is added to the logger to allow pluging in external logger source which expects fn(fmt,...)-like function. So primary requirement is to have that function available and performance is set aside.
- scanning for % is less time consuming than scanining for any variants of %s
- here I've replaced 'assume max arguments always' with string scanning so i guess that in many, if not most, cases it will be faster and take less memory (<4 arguments 32bytes message vs always 64 bytes)

Have no worries, regarding `log_strdup` I'm got convinced to do the scanning there as the second step (first check address range, if match do the scan) and i even started working on that.

**Comment by aescolar** [comment]
@nordic-krch : Do you see them before your patch?

**Comment by nordic-krch** [comment]
@aescolar yes, when i move one commit up i get following:
```
[00:00:00.130,300] <err> ext_log_system: critical level log
==3021== Thread 2:
==3021== Conditional jump or move depends on uninitialised value(s)
==3021==    at 0x10D1A4: log_is_strdup (log_core.c:539)
==3021==    by 0x10D457: msg_free (log_msg.c:51)
==3021==    by 0x10D53C: log_msg_put (log_msg.c:86)
==3021==    by 0x10CE5D: msg_process (log_core.c:369)
==3021==    by 0x10CEBE: log_process (log_core.c:383)
==3021==    by 0x10C967: msg_finalize (log_core.c:65)
==3021==    by 0x10CA0D: log_n (log_core.c:137)
==3021==    by 0x10CB86: log_generic (log_core.c:193)
==3021==    by 0x10B3A6: log_handler (ext_log_system_adapter.c:36)
==3021==    by 0x10B281: ext_log_system_foo (ext_log_system.c:17)
==3021==    by 0x10B92E: external_log_system_showcase (main.c:218)
==3021==    by 0x10BA0B: log_demo_thread (main.c:267)
==3021== 
==3021== Conditional jump or move depends on uninitialised value(s)
==3021==    at 0x10D1AE: log_is_strdup (log_core.c:539)
==3021==    by 0x10D457: msg_free (log_msg.c:51)
==3021==    by 0x10D53C: log_msg_put (log_msg.c:86)
==3021==    by 0x10CE5D: msg_process (log_core.c:369)
==3021==    by 0x10CEBE: log_process (log_core.c:383)
==3021==    by 0x10C967: msg_finalize (log_core.c:65)
==3021==    by 0x10CA0D: log_n (log_core.c:137)
==3021==    by 0x10CB86: log_generic (log_core.c:193)
==3021==    by 0x10B3A6: log_handler (ext_log_system_adapter.c:36)
==3021==    by 0x10B281: ext_log_system_foo (ext_log_system.c:17)
==3021==    by 0x10B92E: external_log_system_showcase (main.c:218)
==3021==    by 0x10BA0B: log_demo_thread (main.c:267)
==3021== 
[00:00:00.130,300] <err> ext_log_system: error level log, 1 arguments: 1
```

**Comment by aescolar** [comment]
From the addresses in valgrind's report I'm guessing you have address space layout randomization enabled in your linux kernel, which is probably masking the issue. Could you disable it and retry?

**Comment by nordic-krch** [comment]
@aescolar I tried to disable (`echo 0 | sudo tee /proc/sys/kernel/randomize_va_space`), recompiled and still no issue. I'm not linux expert so im not sure if this is enough.

**Comment by aescolar** [comment]
@nordic-krch : Debugging memory issues (overflows, and other corruptions) can be pretty annoying as they tend to depend on many factors, and moving the data around in memory can hide or show them..
I would guess this ticket may be related to the other 3 open issues about logger memory issues.

Which gcc version, kernel and linux distro are you running trying this on?

**Comment by aescolar** [comment]
I have just reproduced your (lack of) issue in an clean Ubuntu 18.04

**Comment by nordic-krch** [comment]
i have:
- Linux Mint 19 Cinnamon
- gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
- valgrind-3.13.0

**Review by pizi-nordic — APPROVED** [review]

**Comment by nordic-krch** [comment]
@nashif @carlescufi, @aescolar confirms that it fixes the issue.

**Comment by carlescufi** [comment]
@nordic-krch needs rebase

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
