### PR TITLE
tests: Bluetooth: Add missing ICS for LE audio

### LINKED ISSUE #75825: Tests: Bluetooth: Missing ICS in Bluetooth Host qualification file
**Describe the bug**

The following ICS may be enabled:

- GAP: 17b/4: LE security mode 3 level 3
- GAP: 20A/6: Security Manager OOB
- GAP: 23/7: Connected Isochronous Stream Terminate procedure
- GAP: 27/7: Writable Appearance
- GATT: 3/25a: Enabling Robust Caching

**Impact**

People using the Zephyr qualification file to qualify their product may not qualify some feature even tho the feature is supported by the Zephyr Bluetooth Host.

### PR DESCRIPTION
**Pull request by Thalley**
Add missing LE audio and host features

fixes https://github.com/zephyrproject-rtos/zephyr/issues/75825

### CODE REVIEW

**Comment by Thalley** [comment]
Should consider fixing https://github.com/zephyrproject-rtos/zephyr/issues/75825 in this PR as well

**Comment by Thalley** [comment]
This will conflict with https://github.com/zephyrproject-rtos/zephyr/pull/75809 and if a rebase is needed then we need to make sure that both changes are properly added (can be difficult due to the size of the file)

**Comment by theob-pro** [comment]
> This will conflict with #75809 and if a rebase is needed then we need to make sure that both changes are properly added (can be difficult due to the size of the file)

IMO you should stack your PR on top of #75809, this will be easier like that. We then just have to add DNM on your PR until the other one is merged.

**Comment by theob-pro** [comment]
Also I just discovered that we have documentation pages that describe the ICS. (https://docs.zephyrproject.org/latest/connectivity/bluetooth/bluetooth-qual.html#ics-features)

I am not sure if this is really useful as it's already what we can see on the Bluetooth qualification website. Maybe we should remove those pages (in another PR) as they are outdated or we should update them in this PR if we want to keep them.

What do you think @Thalley @sjanc ?

**Comment by Thalley** [comment]
> Also I just discovered that we have documentation pages that describe the ICS. (https://docs.zephyrproject.org/latest/connectivity/bluetooth/bluetooth-qual.html#ics-features)
> 
> I am not sure if this is really useful as it's already what we can see on the Bluetooth qualification website. Maybe we should remove those pages (in another PR) as they are outdated or we should update them in this PR if we want to keep them.
> 
> What do you think @Thalley @sjanc ?

Good question. Maybe a topic for the BT WG. A nice way of doing it would be to autogenerate those pages based on the actual ICS file, but of course the ICS file does not contain the descriptions. 

I think assuming that we will remember to manually keep these pages up to date is going to be tricky

**Comment by Thalley** [comment]
> > This will conflict with #75809 and if a rebase is needed then we need to make sure that both changes are properly added (can be difficult due to the size of the file)
> 
> IMO you should stack your PR on top of #75809, this will be easier like that. We then just have to add DNM on your PR until the other one is merged.

Probably a good idea. Will do that and then mark this as draft

**Comment by theob-pro** [comment]
> > Also I just discovered that we have documentation pages that describe the ICS. (https://docs.zephyrproject.org/latest/connectivity/bluetooth/bluetooth-qual.html#ics-features)
> > I am not sure if this is really useful as it's already what we can see on the Bluetooth qualification website. Maybe we should remove those pages (in another PR) as they are outdated or we should update them in this PR if we want to keep them.
> > What do you think @Thalley @sjanc ?
> 
> Good question. Maybe a topic for the BT WG. A nice way of doing it would be to autogenerate those pages based on the actual ICS file, but of course the ICS file does not contain the descriptions.
> 
> I think assuming that we will remember to manually keep these pages up to date is going to be tricky

I agree, we will definitely forgot to update them. Honestly I don't think those page add a lot of value to the documentation. But yes, we can get others opinion during BT WG.

**Comment by Thalley** [comment]
Update: This PR is now on top of https://github.com/zephyrproject-rtos/zephyr/pull/75890

**Comment by jhedberg** [comment]
> The compliance check failure is to be expected as these files need to be CRLF

@nashif @carlescufi another case here, essentially the same as what we had with #75809

**Review by jhedberg — APPROVED** [review]

**Review by sjanc — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]

**Pull request merged**
