### PR TITLE
Add rgb565 font support

### PR DESCRIPTION
**Pull request by hakehuang**
This pull request is splited from pr #16331 based on review commnets

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
@pabigot Can you push your patch for gen_cfb_font_header.py?

**Comment by pabigot** [comment]
> Can you push your patch for gen_cfb_font_header.py?

@jfischer-phytec-iot Which patch are you referring to?  I found [one patch](https://github.com/pabigot/zephyr/commit/27ae7f11b05a1ad8b1f16015b729d34dfca5e847) that wasn't part of #17541 which seems to provide something similar to this and would definitely conflict if we're going this way.

```
commit 27ae7f11b05a1ad8b1f16015b729d34dfca5e847
Author: Peter A. Bigot <pab@pabigot.com>
Date:   Tue Jul 16 11:47:59 2019 -0500

    subsys/cfb: move MSB_FIRST down to font capabilities
    
    Font capabilities currently indicate whether font data is packed
    horizontally or vertically, and this is used to control frame buffer
    updates.  The font bit ordering should likewise be recorded in the font
    description, and any reversal to match the display applied when text is
    being set in the frame buffer.
```

**Comment by jfischer-phytec-iot** [comment]
> > Can you push your patch for gen_cfb_font_header.py?
> 
> @jfischer-phytec-iot Which patch are you referring to? I found [one patch](https://github.com/pabigot/zephyr/commit/27ae7f11b05a1ad8b1f16015b729d34dfca5e847) that wasn't part of #17541 which seems to provide something similar to this and would definitely conflict if we're going this way.

I mean "Adding horizontal and MSB" / hpack and msb-first patches.

**Comment by galak** [comment]
I'm closing this PR as it was made on a branch of master, rather than a PR from a forked repo.  Please re-submit with addressed changes and from a branch from a forked repo.

**Comment by pabigot** [comment]
I agree: contributions should not be made from branches created on the master repository as this creates clutter when people fetch upstream repo content.

The content from the deleted branch at  the time of deletion is archived at https://github.com/pabigot/zephyr/tree/hakehuang/add_rgb565_font which can be used as a basis for creating another PR for 2.3.  I'll keep it there until another PR is issued.

@jfischer-phytec-iot I will revisit my patches after 2.2 is released; IIRC they do not depend on this, and may in fact conflict.

**Comment by jfischer-phytec-iot** [comment]
BTW, I tested it and the problem with RGB565 support in CFB is that the memory consumption is far too high and this PR is not acceptable yet. Either CFB should be reworked and use partial write or be replaced by LVGL.

**Pull request closed without merging**
