### PR TITLE
tests: socket: tcp: Test handling of EOF condition on socket

### PR DESCRIPTION
**Pull request by pfalcon**
If peer socket closed, the other side should get 0 from recv(), and
should get in stable manner (no matter how much time went from the
closure and/or how many times recv() is called).

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Review by rveerama1 — APPROVED** [review]

**Comment by pfalcon** [comment]
Oops. Who'd knew this will be merged together with https://github.com/zephyrproject-rtos/zephyr/pull/14050. I thought one of them will be merged nicely spaced out with another (earlier, rather than later). 

@nashif: When CI breakage hits the master, the proper fix is not to revert this PR, but to merge https://github.com/zephyrproject-rtos/zephyr/pull/13667. This and #14050 was made by guys insisting on reproduction case for it ;-).

**Comment by nashif** [comment]
next time submit dependent commits in one PR please or add DNM explaining dependency. Now you are asking me to merge something that was not reviewed to fix master...

**Comment by pfalcon** [comment]
@nashif, Well, yeah, noted. Then https://github.com/zephyrproject-rtos/zephyr/pull/14050 is the immediate issue trigger and should be smaller to revert.

**Comment by nashif** [comment]
@pfalcon see https://github.com/zephyrproject-rtos/zephyr/pull/14126

**Pull request merged**
