### PR TITLE
boards: arm: Fix Partition Addressing for nrf52_pca10040

### PR DESCRIPTION
**Pull request by jsiloto**
Fix Issue #5107

Signed-off-by: Juliano Siloto Assine <jsiloto@cpqd.com.br>

### CODE REVIEW

**Comment by carlescufi** [comment]
@jsiloto can you amend the commit message describing the reason for the change?

**Comment by jsiloto** [comment]
I changed the commit message.
I don't know if there are better alternatives for partition sizes. So far 0x8000 is enough for the current build of mcuboot

**Comment by nvlsianpu** [comment]
Look at my comments in https://github.com/zephyrproject-rtos/zephyr/issues/5107. What you was observing was a mcuboot bug.

**Comment by nvlsianpu** [comment]
I disprove this patch as it try to fix non existing bug.

**Pull request closed without merging**
