### PR TITLE
[RFC] scripts/ci: Merge ci-tools back into main Zephyr repository

### PR DESCRIPTION
**Pull request by ulfalizer**
Put the scripts from the [ci-tools](https://github.com/zephyrproject-rtos/ci-tools) repository in `scripts/ci` in the main Zephyr
repository, where they used to be.

Here's why I think it's a good idea:

 1. A single PR can change both Zephyr code and CI code, e.g. to add a new test
    related to the PR, or modify the whitelist for a test

 2. It makes people more likely to notice CI changes

 3. It makes the CI scripts easier to discover

 4. It makes the CI scripts easier to run. No need to clone a separate
    repository.

 5. It means you automatically get the corresponding CI checks when you
    check out a particular Zephyr version, which are guaranteed to pass

Use a merge commit (with `--allow-unrelated-histories`) so that the `ci-tools`
history is preserved.

### CODE REVIEW

**Comment by ulfalizer** [comment]
This just moves the CI scripts back. If this goes in, then other CI plumbing will have to be changed as well to point to `scripts/ci` in the main repo.

**Review by carlescufi — CHANGES_REQUESTED** [review]
I am preemptively blocking this from getting merged until @thst-nordic has had a chance  to take a look. We asked to split this out for a couple of reasons, one of which was to be able to freeze the ci-tools version we use downstream to any revision we needed regardless of zephyr upmerges.

**Comment by ulfalizer** [comment]
> I am preemptively blocking this from getting merged until @thst-nordic has had a chance to take a look. We asked to split this out for a couple of reasons, one of which was to be able to freeze the ci-tools version we use downstream to any revision we needed regardless of zephyr upmerges.

Why do you need to freeze the version of the `ci-tools` repo? I wonder if there might be a simple purely downstream fix.

**Comment by mbolivar** [comment]
> Why do you need to freeze the version of the `ci-tools` repo?

Because incoming upstream changes were breaking downstream CI.

> I wonder if there might be a simple purely downstream fix.

Not without guaranteeing API stability for this code, which I'm guessing nobody will want to put the effort into doing (are you volunteering? :smile:).

**Comment by nashif** [comment]
Blocking such changes related to CI because some downstream CI might break IMO is a non-starter. This script is primarily designed and intended for Zephyr and how zephyr CI works, if someone downstream uses that, it is fine, but it should not block merging changes, etc.

I do not remember why we split this, I think it was mostly related to how zephyr CI works and not because of someone else using it downstream. Pulling this back into Zephyr has lots of advantages, most of which we have seen and identified over the last few months where we had to make changes to ci-tools to pass in the main tree. The other main reason which will soon hit us is if we start making changes that depend on master, CI in 1.14 branch will start failing (Both branches use the same version). Of course we could branch ci-tools, but this will get more complicated in how this script operates and it will be difficult to keep the script and the code base it is supposed to test in sync.

**Comment by ulfalizer** [comment]
@mbolivar 
There's a trade-off between people doing out-of-tree custom CI and everyone else here I think. Bending over backwards too much to accommodate exotic tweaks outside of Zephyr might hurt us. Probably best to just let people maintain their own patches.

**Comment by mbolivar** [comment]
> Probably best to just let people maintain their own patches.

That is *exactly* what keeping it in a separate repository permits.

**Comment by nashif** [comment]
already happened when moving to GH actions.

**Pull request closed without merging**
