### PR TITLE
manifest: update zephyr-lang-rust Zephyr module

### LINKED ISSUE #79295: ninja / cmake --build fails for Rust
**Describe the bug**
During investigation of CI failures I discovered that building of Rust hello_world fails when invoking `ninja` directly / for incremental builds.

This happens both when running `ninja` as well as `cmake --build`.

What works is a complete `west` build.

**To Reproduce**
Working scenario:
```
$ cd <west-workspace>/zephyr
$ west build -p -b qemu_riscv32 ../modules/lang/rust/samples/hello_world -T sample.rust.helloworld
-- west build: making build dir /projects/github/ncs/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
...
[104/104] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
             RAM:       38176 B       256 MB      0.01%
        IDT_LIST:          0 GB         2 KB      0.00%
Generating files from /projects/github/ncs/zephyr/build/zephyr/zephyr.elf for board: qemu_riscv32
```

Failing incremental build, for example cleaning the build folder and doing a rebuild, like:
```
$ ninja -C build clean
ninja: Entering directory `build'
[2/2] Cleaning all built files...
Cleaning... 334 files.
$ ninja -C build 
ninja: Entering directory `build'
[1/104] Preparing syscall dependency handling

[3/104] Generating include/generated/zephyr/version.h
-- Zephyr version: 3.7.99 (/projects/github/ncs/zephyr), build: v3.7.0-3720-g9c0f92db475f
[94/104] Building Rust application
FAILED: always-run-cargo.dummy rust/target/riscv32i-unknown-none-elf/debug/librustapp.a rust/wrapper.c /projects/github/ncs/zephyr/build/always-run-cargo.dummy /projects/github/ncs/zephyr/build/rust/target/riscv32i-unknown-none-elf/debug/librustapp.a /projects/github/ncs/zephyr/build/rust/wrapper.c 
cd /projects/github/ncs/modules/lang/rust/samples/hello_world && /opt/cmake-3.26.5-linux-x86_64/bin/cmake -E env BUILD_DIR=/projects/github/ncs/zephyr/build DOTCONFIG=/projects/github/ncs/zephyr/build/zephyr/.config ZEPHYR_DTS=/projects/github/ncs/zephyr/build/zephyr/zephyr.dts INCLUDE_DIRS="/projects/github/ncs/zephyr/build/zephyr/include/generated/zephyr /projects/github/ncs/zephyr/include /projects/github/ncs/zephyr/build/zephyr/include/generated /projects/github/ncs/zephyr/soc/qemu/virt_riscv /projects/github/ncs/zephyr/lib/libc/common/include /projects/github/ncs/zephyr/soc/common/riscv-privileged/. " INCLUDE_DEFINES="KERNEL __ZEPHYR__=1  __LINUX_ERRNO_EXTENSIONS__ PICOLIBC_LONG_LONG_PRINTF_SCANF K_HEAP_MEM_POOL_SIZE=0" WRAPPER_FILE="/projects/github/ncs/zephyr/build/rust/wrapper.c" cargo build --config patch.crates-io.zephyr.path=\"/projects/github/ncs/modules/lang/rust/zephyr\" --config patch.crates-io.zephyr-build.path=\"/projects/github/ncs/modules/lang/rust/zephyr-build\" --config patch.crates-io.zephyr-sys.path=\"/projects/github/ncs/modules/lang/rust/zephyr-sys\" --target riscv32i-unknown-none-elf --target-dir /projects/github/ncs/zephyr/build/rust/target
   Compiling zephyr-sys v0.1.0 (/projects/github/ncs/modules/lang/rust/zephyr-sys)
error: failed to run custom build command for `zephyr-sys v0.1.0 (/projects/github/ncs/modules/lang/rust/zephyr-sys)`

Caused by:
  process didn't exit successfully: `/projects/github/ncs/zephyr/build/rust/target/debug/build/zephyr-sys-45fc2e34b4407e58/build-script-build` (exit status: 1)
  --- stdout
  Clang version: ClangVersion { parsed: Some((14, 0)), full: "Ubuntu clang version 14.0.0-1ubuntu1.1" }

  --- stderr
  Error: environment variable not found
ninja: build stopped: subcommand failed.
```

Same error is seen if using `west build` to just run CMake and then invoke `ninja` / `cmake --build` afterwards:
```
$ west build -p -b qemu_riscv32 ../modules/lang/rust/samples/hello_world -T sample.rust.helloworld  --cmake-only
-- west build: making build dir /projects/github/ncs/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /projects/github/ncs/modules/lang/rust/samples/hello_world
...
-- Building Rust llvm target riscv32i-unknown-none-elf
-- Processing crates: 
-- module: zephyr
-- module: zephyr-build
-- module: zephyr-sys
-- Configuring done (2.6s)
-- Generating done (0.0s)
-- Build files have been written to: /projects/github/ncs/zephyr/build
$ ninja -C build
ninja: Entering directory `build'
[1/104] Preparing syscall dependency handling

[3/104] Generating include/generated/zephyr/version.h
-- Zephyr version: 3.7.99 (/projects/github/ncs/zephyr), build: v3.7.0-3720-g9c0f92db475f
[94/104] Building Rust application
FAILED: always-run-cargo.dummy rust/target/riscv32i-unknown-none-elf/debug/librustapp.a rust/wrapper.c /projects/github/ncs/zephyr/build/always-run-cargo.dummy /projects/github/ncs/zephyr/build/rust/target/riscv32i-unknown-none-elf/debug/librustapp.a /projects/github/ncs/zephyr/build/rust/wrapper.c 
cd /projects/github/ncs/modules/lang/rust/samples/hello_world && /opt/cmake-3.26.5-linux-x86_64/bin/cmake -E env BUILD_DIR=/projects/github/ncs/zephyr/build DOTCONFIG=/projects/github/ncs/zephyr/build/zephyr/.config ZEPHYR_DTS=/projects/github/ncs/zephyr/build/zephyr/zephyr.dts INCLUDE_DIRS="/projects/github/ncs/zephyr/build/zephyr/include/generated/zephyr /projects/github/ncs/zephyr/include /projects/github/ncs/zephyr/build/zephyr/include/generated /projects/github/ncs/zephyr/soc/qemu/virt_riscv /projects/github/ncs/zephyr/lib/libc/common/include /projects/github/ncs/zephyr/soc/common/riscv-privileged/. " INCLUDE_DEFINES="KERNEL __ZEPHYR__=1  __LINUX_ERRNO_EXTENSIONS__ PICOLIBC_LONG_LONG_PRINTF_SCANF K_HEAP_MEM_POOL_SIZE=0" WRAPPER_FILE="/projects/github/ncs/zephyr/build/rust/wrapper.c" cargo build --config patch.crates-io.zephyr.path=\"/projects/github/ncs/modules/lang/rust/zephyr\" --config patch.crates-io.zephyr-build.path=\"/projects/github/ncs/modules/lang/rust/zephyr-build\" --config patch.crates-io.zephyr-sys.path=\"/projects/github/ncs/modules/lang/rust/zephyr-sys\" --target riscv32i-unknown-none-elf --target-dir /projects/github/ncs/zephyr/build/rust/target
...
error: failed to run custom build command for `zephyr-sys v0.1.0 (/projects/github/ncs/modules/lang/rust/zephyr-sys)`

Caused by:
  process didn't exit successfully: `/projects/github/ncs/zephyr/build/rust/target/debug/build/zephyr-sys-45fc2e34b4407e58/build-script-build` (exit status: 1)
  --- stdout
  Clang version: ClangVersion { parsed: Some((14, 0)), full: "Ubuntu clang version 14.0.0-1ubuntu1.1" }

  --- stderr
  Error: environment variable not found
ninja: build stopped: subcommand failed.
```

Same happens when running CMake + ninja:
```
$ cmake -GNinja -DBOARD=qemu_riscv32 -Bbuild ../modules/lang/rust/samples/hello_world
Loading Zephyr default modules (Zephyr workspace).
-- Application: /projects/github/ncs/modules/lang/rust/samples/hello_world
...
-- Building Rust llvm target riscv32i-unknown-none-elf
-- Processing crates: 
-- module: zephyr
-- module: zephyr-build
-- module: zephyr-sys
-- Configuring done (2.6s)
-- Generating done (0.0s)
-- Build files have been written to: /projects/github/ncs/zephyr/build
$ ninja -C build
ninja: Entering directory `build'
[1/104] Preparing syscall dependency handling

[3/104] Generating include/generated/zephyr/version.h
-- Zephyr version: 3.7.99 (/projects/github/ncs/zephyr), build: v3.7.0-3720-g9c0f92db475f
[94/104] Building Rust application
FAILED: always-run-cargo.dummy rust/target/riscv32i-unknown-none-elf/debug/librustapp.a rust/wrapper.c /projects/github/ncs/zephyr/build/always-run-cargo.dummy /projects/github/ncs/zephyr/build/rust/target/riscv32i-unknown-none-elf/debug/librustapp.a /projects/github/ncs/zephyr/build/rust/wrapper.c 
cd /projects/github/ncs/modules/lang/rust/samples/hello_world && /opt/cmake-3.26.5-linux-x86_64/bin/cmake -E env BUILD_DIR=/projects/github/ncs/zephyr/build DOTCONFIG=/projects/github/ncs/zephyr/build/zephyr/.config ZEPHYR_DTS=/projects/github/ncs/zephyr/build/zephyr/zephyr.dts INCLUDE_DIRS="/projects/github/ncs/zephyr/build/zephyr/include/generated/zephyr /projects/github/ncs/zephyr/include /projects/github/ncs/zephyr/build/zephyr/include/generated /projects/github/ncs/zephyr/soc/qemu/virt_riscv /projects/github/ncs/zephyr/lib/libc/common/include /projects/github/ncs/zephyr/soc/common/riscv-privileged/. " INCLUDE_DEFINES="KERNEL __ZEPHYR__=1  __LINUX_ERRNO_EXTENSIONS__ PICOLIBC_LONG_LONG_PRINTF_SCANF K_HEAP_MEM_POOL_SIZE=0" WRAPPER_FILE="/projects/github/ncs/zephyr/build/rust/wrapper.c" cargo build --config patch.crates-io.zephyr.path=\"/projects/github/ncs/modules/lang/rust/zephyr\" --config patch.crates-io.zephyr-build.path=\"/projects/github/ncs/modules/lang/rust/zephyr-build\" --config patch.crates-io.zephyr-sys.path=\"/projects/github/ncs/modules/lang/rust/zephyr-sys\" --target riscv32i-unknown-none-elf --target-dir /projects/github/ncs/zephyr/build/rust/target
...
   Compiling zephyr-sys v0.1.0 (/projects/github/ncs/modules/lang/rust/zephyr-sys)
error: failed to run custom build command for `zephyr-sys v0.1.0 (/projects/github/ncs/modules/lang/rust/zephyr-sys)`

Caused by:
  process didn't exit successfully: `/projects/github/ncs/zephyr/build/rust/target/debug/build/zephyr-sys-45fc2e34b4407e58/build-script-build` (exit status: 1)
  --- stdout
  Clang version: ClangVersion { parsed: Some((14, 0)), full: "Ubuntu clang version 14.0.0-1ubuntu1.1" }

  --- stderr
  Error: environment variable not found
ninja: build stopped: subcommand failed.

```

**Expected behavior**
Incremental builds invoked directly with the build command (ninja / make / cmake --build) should work.
Running CMake + ninja should work.

**Impact**
Annoyance as it make investigating build failures much harder when tools cannot be run step by step.

Also this form or error indicates that the actual build process (ninja / make) is dependent on certain setting being present in environment. This is generally a bad thing as it makes tracing and debugging build failures unnecessary hard, and it's an indication that the build scripts are poorly written.

**Logs and console output**
See above.

**Environment (please complete the following information):**

 - OS: Linux, Ubuntu 22.04
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: 9c0f92db475f0e27673ac366276026eddf1a150c

**Additional context**

### PR DESCRIPTION
**Pull request by tejlmand**
Fixes: #79295

Update zephyr-lang-rust Zephyr module to include fix for incremental builds and CMake + ninja invocations.

### CODE REVIEW

**Comment by d3zd3z** [comment]
@tejlmand zephyr-lang-rust change has merged. This can be updated.

**Comment by tejlmand** [comment]
> @tejlmand zephyr-lang-rust change has merged. This can be updated.

Done.

**Review by d3zd3z — APPROVED** [review]

**Comment by d3zd3z** [comment]
Do we want to migrate to the additional change that has merged, or does that need to be included in your other changes?

**Review by teburd — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by tejlmand** [comment]
closing as the manifest update in this pr has been superseded by: #78320

**Pull request closed without merging**
