### PR TITLE
arch: arc: remove ARCH_HAS_STACK_PROTECTION for ARC_MPU_VER 2

### PR DESCRIPTION
**Pull request by IRISZZW**
Fix test `tests/kernel/fatal/exception/kernel.common.stack_protection` failure in `qemu_arc_hs` and `qemu_arc_em`, found by
CI in pull request: #32768 

As we have removed MPU_STACK_GUARD for ARC_MPU_VER 2, we also need to remove ARCH_HAS_STACK_PROTECTION for
boards with ARC_MPU_VER 2 and no hardware stack checking, relative commit: commit(arch: arc: remove MPU_STACK_GUARD
for ARC_MPU_VER 2) in pull request #24021.

### CODE REVIEW

**Review by abrodkin — CHANGES_REQUESTED** [review]
Please add a comment ob rationale for that change. Was it a fix for some seen issue, preventive fix, clean-up etc?

**Comment by ruuddw** [comment]
> Please add a comment ob rationale for that change. Was it a fix for some seen issue, preventive fix, clean-up etc?

Rationale for what? The original PR that removed MPU-based stack guards for MPUv2, or this PR? Doesn't make sense to me to explain the old PR here (fyi: rationale was that it wasted a lot of memory and if ARCs include MPU, users would typically also configure HW stack checking).

**Review by ruuddw — APPROVED** [review]

**Comment by abrodkin** [comment]
> > Please add a comment ob rationale for that change. Was it a fix for some seen issue, preventive fix, clean-up etc?
> 
> Rationale for what? The original PR that removed MPU-based stack guards for MPUv2, or this PR? Doesn't make sense to me to explain the old PR here (fyi: rationale was that it wasted a lot of memory and if ARCs include MPU, users would typically also configure HW stack checking).

I thought about referring to https://github.com/zephyrproject-rtos/zephyr/pull/32768 for which this fix was needed to get clean execution of QEMU boards with MPU :)

**Review by abrodkin — APPROVED** [review]

**Comment by abrodkin** [comment]
Maybe re-base and force push https://github.com/zephyrproject-rtos/zephyr/pull/32768 to trigger CI rerun once this fix gets accepted?

**Pull request merged**
