### PR TITLE
board: 96b_argonkey: Add on-board MP34DT05 microphone support in BSP

### PR DESCRIPTION
**Pull request by avisconti**
This commit is taking care of following stuff:

1. pinmux: STM32F4 micro is using I2S5_CK and I2S_SD to interface with
   on-board microphone.

2. default dts: make use of SPI5 because I2S is not currently supported
   in Zephyr dts bindings.

3. default configuration:
     - enable I2S5 and configure PLLI2S properly to generate
       I2SxCLK = 128MHz.
     - enable DMA

Note:
 As stated in issue #9028 we needed to take care of a known SPI/I2S bug
 implementing the following two actions:

 A. APB2 clock has been slowed down to 42MHz.
 B. The SPI/I2S clock gpio speed has been set to very_high_speed.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Comment by avisconti** [comment]
This PR depends from the PR #9034.
@erwango

**Review by dbkinder — APPROVED** [review]
+1 for doc changes

**Comment by erwango** [comment]
@avisconti , can you rebase it on top of #9034 so we have better view and clear status when #9034 gets merged

**Comment by avisconti** [comment]
@erwango.
Sure, I had plan to do it as well. Moreover things changed a bit also in this commit after I put I2S handling in DTS.

**Comment by avisconti** [comment]
Rebased this PR on top of #9034, as suggested by @erwango.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
recheck

**Comment by avisconti** [comment]
@erwango 
I think we need to merge #9034 first.
Then I'll rebase this PR on top of master.

**Comment by avisconti** [comment]
Now that #9034 has been merged I rebased this PR once more against master

**Pull request merged**
