### PR TITLE
usb: cdc_acm: use pipes instead of ringbuffers to ensure thread safety

### LINKED ISSUE #59611: Thread unsafety/race conditions in USB CDC-ACM class
**Describe the bug**
The CDC-ACM `tx_ringbuf` (among others, probably) is accessed by multiple threads (the usbworkq calling `tx_work_handler` as well as any callers of `cdc_acm_fifo_fill`/`cdc_acm_poll_out`), but is not protected in any way. This causes race conditions and associated data corruption/crashes, as `struct ring_buf` is not thread safe.

**To Reproduce**
No good reproduction, as it's racy, but I hope the cause is easy enough to understand.

**Expected behavior**
The CDC-ACM device does not contain race conditions.

**Impact**
In one specific configuration, the device crashes on an assert because the ringbuffer data is changed concurrently.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: Zephyr SDK 0.16.1
 - Commit SHA or Version used: 3.4.0

### PR DESCRIPTION
**Pull request by arbrauns**
`rx_ringbuf`/`tx_ringbuf` were entirely unprotected, which meant that the multiple threads accessing them (usbworkq as well as any threads calling the public read/write functions) would potentially corrupt each other's data.

Since mutexes are not allowed inside ISRs, simply switch everything to pipes. Since they don't support peeking/claiming, an additional buffer is necessary to store the data to be transmitted by the USB stack.

Fixes #59611
cc @tmon-nordic

### CODE REVIEW

**Comment by tmon-nordic** [comment]
> Since mutexes are not allowed inside ISRs, simply switch everything to pipes

Where is it called from ISR context? Note that the completion callback will be called from USB worqueue:
https://github.com/zephyrproject-rtos/zephyr/blob/e216dcfc3d430a42bf71d97a5f60d8756d67ec7a/subsys/usb/device/usb_transfer.c#L134-L143

**Comment by arbrauns** [comment]
I can't remember where I hit that issue, I'll have to look into it next week.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Not sure how this relates to the ISR context, there is no description in the commit message. There are no multiple writers/readers. And if you were using the UART API properly, there would be only one context used (e.g. workqueue thread used by CDC ACM implementation). This change is not acceptable, also because of ignorance of the style used in the file.

**Comment by tmon-nordic** [comment]
> @tmon-nordic:
> 
> > Where is it called from ISR context?
> 
> `cdc_acm_read_cb` is called through `cdc_acm_dev_status_cb` -> `cdc_acm_do_cb`.

But only if `dev_data->configured` is `false` to kick-start the transfers.

To observe the issue, `usb_transfer_work()` executing transfer `cb` (`cdc_acm_read_cb`) would have to be pre-empted first by `USB_DC_RESET`) and then by `USB_DC_CONFIGURED` status callback. On nrfx `USB_DC_CONFIGURED` chains back to `usbd_work_handler`. Both `usbd_thread` and `usbd_work_handler` have cooperative priorities and therefore I see no way for them to interrupt each other and thus manifest this issue.

On which target did you observe the issue?

**Comment by tmon-nordic** [comment]
> In that case, please correct my improper use of the UART API, which leads to multiple concurrent reads of the CDC-ACM TX buffer.
> 
>     1. From my application task, I am calling `uart_poll_out()`. This ends up in `cdc_acm_poll_out()`, which, in case the TX buffer is full, [frees a byte by reading it](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/device/class/cdc_acm.c#L1016).
> 
>     2. Concurrently, `tx_work_handler()` (invoked by the system work queue) [also reads the TX buffer](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/device/class/cdc_acm.c#L247) to send it to the USB stack.
> 
> 
> As is the nature of race conditions, this is an absolute pain to reproduce, so I'm not confident that this is the only issue.

Should we just remove the "free the byte to make space"? Choosing which byte to lose is an pandora box of its own, but without this there would be no issue - or would there?

**Comment by arbrauns** [comment]
> To observe the issue, `usb_transfer_work()` executing transfer `cb` (`cdc_acm_read_cb`) would have to be pre-empted first by `USB_DC_RESET` and then by `USB_DC_CONFIGURED` status callback. On nrfx `USB_DC_CONFIGURED` chains back to `usbd_work_handler`.

Sorry, I was just talking about why mutexes can't be used; as far as I know, there is no corruption on that path.

> Should we just remove the "free the byte to make space"? Choosing which byte to lose is a pandora box of its own, but without this there would be no issue - or would there?

That would certainly fix that specific issue, I haven't reviewed it thoroughly enough to claim it is the only one.

**Comment by kand198** [comment]
I've encountered this race condition as well, and I'd like to help out with the fix if possible.

> Should we just remove the "free the byte to make space"? Choosing which byte to lose is a pandora box of its own, but without this there would be no issue - or would there?

According to the [UART Polling API Documentation](https://docs.zephyrproject.org/latest/hardware/peripherals/uart.html#c.uart_poll_out):

> This routine checks if the transmitter is full. When the transmitter is not full, it writes a character to the data register. It waits and blocks the calling thread, otherwise. This function is a blocking call.

The `cdc_acm_poll_out` behavior does not match this description, as it will attempt to drop characters from the transmitter if it is full and will never block.

The [USB CDC ACM](https://docs.zephyrproject.org/latest/connectivity/usb/device/usb_device.html#cdc-acm) documentation currently describes two behavioral deviations from the standard UART API, but this is not one of them.

However, there is inline documentation (block comment) for the `cdc_acm_poll_out` function:

> This function does not block, if the USB subsystem is not ready, no data is transferred to the buffer, that is, c is dropped.\
If the USB subsystem is ready and the buffer is full, the first character from the tx_ringbuf is removed to make room for the new character.

This correctly describes the behavior of `cdc_acm_poll_out`. This is the only documentation of the deviation from the expected behavior of the UART Polling API and is only found on inspection of the source code (the deviation itself).

Modifying `cdc_acm_poll_out` to match the expected behavior of `uart_poll_out` would be my preferred solution, but I assume that the decision to deviate from this behavior was deliberate.\
In any case, the user documentation should be updated to reflect the behavior of the code.

**Comment by arbrauns** [comment]
That diverging behaviour of `cdc_acm_poll_out()` does have its reason, of course - for "real" hardware UARTs, no matter how much data you stuff in, eventually it'll be sent out. For CDC-ACM, if no host is connected, the data will sit there forever, potentially causing a complete lockup of the sending task. Maybe it would be possible to check whether a host is connected and capable of receiving data, and only block if that is the case (and throw away data otherwise)? Or slightly more dynamically, only block until X milliseconds after the last time the host read something?

**Comment by kand198** [comment]
@arbrauns thanks for your explanation 😄. It makes sense that the intention was to emulate the hardware behavior of a hardware UART.

I don't think that this goal is causing the problem. It's probably important to make `cdc_acm_poll_out` substitutable with other devices that implement the UART interface. Instead, we should try eliminating the side-effect of concurrent access on the FIFO, which you've done here by switching to pipes.

> Or slightly more dynamically, only block until X milliseconds after the last time the host read something?

I could see this working, but I think your solution in this MR is more elegant.

**Comment by arbrauns** [comment]
> I could see this working, but I think your solution in this MR is more elegant.

This PR doesn't really touch that issue at all, just as before it buffers a bit and then discards any extra input without blocking. Blocking unless the host is dead would be a different change.

**Pull request closed without merging**
