### PR TITLE
dt-bindings: sensor: ina237: adjust operating modes

### PR DESCRIPTION
**Pull request by bbilas**
Adjust operating modes to match with datasheet and `ina230` pattern.

Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>

### CODE REVIEW

**Review by MaureenHelm — COMMENTED** [review]
Are you just renaming macros or their values changing? It's hard to see in the diff

**Comment by bbilas** [comment]
> Are you just renaming macros or their values changing? It's hard to see in the diff

I've only renamed them and I added the missing `INA237_OPER_MODE_TEMP_TRIG` mode.

**Comment by MaureenHelm** [comment]
> > Are you just renaming macros or their values changing? It's hard to see in the diff
> 
> I've only renamed them and I added the missing `INA237_OPER_MODE_TEMP_TRIG` mode.

Can you mention this in the commit message please? Also, why aren't there any corresponding .c changes? Are these macros not used anywhere?

**Comment by bbilas** [comment]
> > > Are you just renaming macros or their values changing? It's hard to see in the diff
> > 
> > 
> > I've only renamed them and I added the missing `INA237_OPER_MODE_TEMP_TRIG` mode.
> 
> Can you mention this in the commit message please? Also, why aren't there any corresponding .c changes? Are these macros not used anywhere?

I will do that. Currently, they are used only in the device tree that's why there are no changes related to the .c files.

**Comment by bbilas** [comment]
@MaureenHelm I've updated the commit message.

**Review by MaureenHelm — DISMISSED** [review]

**Comment by bbilas** [comment]
@MaureenHelm force pushed to update the driver as well since the macros have been using there since https://github.com/zephyrproject-rtos/zephyr/commit/755c0d57e8c6e671938bfd5cb09f2dc7eb378a58 commit.

**Review by mzagrabski — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
