### PR TITLE
boards: lpcxpresso55s69: fix a few missed HWMv1 identifiers

### PR DESCRIPTION
**Pull request by danieldegrasse**
Fix some missed HWMv1 board identifiers (particularly for LPC55S69 CPU0 overlays)

### CODE REVIEW

**Review by decsny — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Review by iuliana-prodan — DISMISSED** [review]

**Review by EmilioCBen — DISMISSED** [review]

**Comment by dleach02** [comment]
@danieldegrasse there are CI failures.

**Comment by danieldegrasse** [comment]
> @danieldegrasse there are CI failures.

Those are expected until https://github.com/zephyrproject-rtos/zephyr/pull/69938 merges

**Comment by henrikbrixandersen** [comment]
@danieldegrasse Please rebase :)

**Review by decsny — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
rerunning CI

**Pull request merged**
