### PR TITLE
Rename up_squared_adsp to intel_adsp_cavs15

### PR DESCRIPTION
**Pull request by nashif**
The Audio DSP is not specific to up_squared, so make it more generic.

Also removes stray file.

### CODE REVIEW

**Comment by nashif** [comment]
@plbossart FYI

**Review by lyakh — CHANGES_REQUESTED** [review]
This PR (patch 2 specifically) breaks APL / cAVS1.5 builds in some not immediately obvious way. I'll try to figure it out, please, wait with merging

**Comment by nashif** [comment]
> This PR (patch 2 specifically) breaks APL / cAVS1.5 builds in some not immediately obvious way. I'll try to figure it out, please, wait with merging

this?

/home/nashif/zephyr-sdk/xtensa/intel_apl_adsp/xtensa-zephyr-elf/bin/xtensa-zephyr-elf-objcopy: /home/nashif/Work/zephyrproject/zephyr/build/zephyr/zephyr.elf.mod: warning: empty loadable segment detected at vaddr=0, is this intentional?
/home/nashif/zephyr-sdk/xtensa/intel_apl_adsp/xtensa-zephyr-elf/bin/xtensa-zephyr-elf-objcopy: /home/nashif/Work/zephyrproject/zephyr/build/zephyr/zephyr.elf.mod: warning: empty loadable segment detected at vaddr=0, is this intentional?
/home/nashif/zephyr-sdk/xtensa/intel_apl_adsp/xtensa-zephyr-elf/bin/xtensa-zephyr-elf-objcopy: BFD (crosstool-NG 1.24.0.37-3f461da-dirty) 2.32 internal error, aborting at /home/buildslave/src/github.com/zephyrproject-rtos/sdk-ng/build/build_xtensa_intel_apl_adsp/.build/xtensa-zephyr-elf/src/binutils/bfd/elf.c:7164 in rewrite_elf_program_header

/home/nashif/zephyr-sdk/xtensa/intel_apl_adsp/xtensa-zephyr-elf/bin/xtensa-zephyr-elf-objcopy: Please report this bug.

**Comment by lyakh** [comment]
@nashif I'm getting this:

```
/usr/local/src/project/51/src/zephyr-andyross/modules/audio/sof/src/schedule/timer_domain.c:33:2: error: #error "Zephyr uses 19.2MHz clock derived from SSP which must be enabled."
   33 | #error "Zephyr uses 19.2MHz clock derived from SSP which must be enabled."
      |  ^~~~~
[164/238] Building C object modules/sof/CMakeFiles/modules_sof.dir/usr/local/src/project/51/src/zephyr-andyross/modules/audio/sof/src/audio/pipeline.c.obj
ninja: build stopped: subcommand failed.
```

**Comment by nashif** [comment]
@lyakh can you check if you have the name of the board hardcoded somewhere in your tree?

**Review by dcpleung — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by andrewboie** [comment]
@lyakh are you reproducing this on the Zephyr master branch or some other tree?

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by lyakh** [comment]
> @lyakh are you reproducing this on the Zephyr master branch or some other tree?

@andrewboie to test SOF I need additional patches, so, I took the SOF-integration tree from @andyross, which works as is, and applied these patches on top

**Review by lyakh — APPROVED** [review]
I figured out what the problem in my build is. It isn't in this PR, it's now in https://github.com/zephyrproject-rtos/zephyr/commit/641d07cb35ac69ba40627f217bf803dd743ed2b8#r43471349 so, @andyross just has to modify that one line in that @lgirdwood 's commit

**Pull request merged**
