### PR TITLE
samples: net: zperf: Refactor udp_received

### PR DESCRIPTION
**Pull request by bublover**
Use the state machine states to determine if the session has ended.
This way zperf will properly reply stat packet to remote client even if
duration of the session is non zero.

Also we don't need to update counter (received packet number) at end of
the session.

Note: if id < 0, it means session end, otherwise it's session ongoing.
(id is the first feild of application data from remote client).

Signed-off-by: Bub Wei <bub.wei@unisoc.com>

### CODE REVIEW

**Review by jukkar — CHANGES_REQUESTED** [review]
While reading the diff, I am not sure what the PR is fixing. Could you explain more detail in the commit message what is being fixed and why?

**Comment by bublover** [comment]
> While reading the diff, I am not sure what the PR is fixing. Could you explain more detail in the commit message what is being fixed and why?

Dear Jukkar,  Current zperf does not reply the stat packet while I am doing UDP RX test. 
> /* If necessary send statistics */	
	if (session->state == STATE_LAST_PACKET_RECEIVED) {	
		u32_t rate_in_kbps;	
		u32_t duration = HW_CYCLES_TO_USEC(	
			time_delta(session->start_time, time));	

 		/* Update state machine */	
		session->state = STATE_COMPLETED;	

 		/* Compute baud rate */	
		if (duration != 0) {	
			rate_in_kbps = (u32_t)	
				(((u64_t)session->length * (u64_t)8 *	
				  (u64_t)USEC_PER_SEC) /	
				 ((u64_t)duration * 1024));	
		} else {	
			rate_in_kbps = 0U;	


 			/* Fill statistics */

There is invalid point at STATE_LAST_PACKET_RECEIVED, if duration is not zero, zperf won't reply stat pakcet to remote client.

And,
> /* Update counter */	
 	session->counter++;
	session->length += net_pkt_appdatalen(pkt);

If id is less than zero, it means the session end.  We don't need to update counter(received packet number).  That's, there is no state check while update counter.

**Comment by pfalcon** [comment]
@bublover: Thanks for your patch. As @jukkar mentions, all these points should be described in the commit message, so if you like at it in a year, you could yourself know why you made those changes. (And so someone looking at the patch now, how that idea too.)

**Comment by bublover** [comment]
Dear @pfalcon and @jukkar ,
I have updated commit message. Could you please review this patch accordingly?

**Comment by jukkar** [comment]
Thanks for the update. I still has difficulties to understand what the commit message is trying to say.
I tried to figure out a better commit message, would this still be correct:
```
Use the state machine states to determine if the session has ended.
This way zperf will properly reply stat packet to remote client even if
duration of the session is non zero.

Also we don't need to update counter (received packet number) at end of
the session.
```

**Comment by bublover** [comment]
> Thanks for the update. I still have difficulties to understand what the commit message is trying to say.
> I tried to figure out a better commit message, would this still be correct:
> 
> ```
> Use the state machine states to determine if the session has ended.
> This way zperf will properly reply stat packet to remote client even if
> duration of the session is non zero.
> 
> Also we don't need to update counter (received packet number) at end of
> the session.
> ```

Hi @jukkar ,
Your message is exactly what I am trying to say.
Updated with your message. Thanks.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by pfalcon — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
