### PR TITLE
Bluetooth: drivers: Remove unmaintained B91 HCI driver

### LINKED ISSUE #52111: Incompatible LTO version of liblt_9518_zephyr.a
Target: TLSR9518ADK80D
Zephyr versions:  v3.2.0, main.
Host OS: Ubuntu 22.04
```
lto1: fatal error: bytecode stream in file '/workdir/modules/hal/telink/tlsr9/ble/proj_lib/lib/liblt_9518_zephyr.a' generated with LTO version 9.3 instead of the expected 12.0
compilation terminated.
lto-wrapper: fatal error: /home/egor/.local/zephyr-sdk-0.15.1/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-gcc returned 1 exit status
compilation terminated.
/home/egor/.local/zephyr-sdk-0.15.1/riscv64-zephyr-elf/bin/../lib/gcc/riscv64-zephyr-elf/12.1.0/../../../../riscv64-zephyr-elf/bin/ld.bfd: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
Reproduce:
add `CONFIG_FPU=y` to zephyr/boards/riscv/tlsr9518adk80d/tlsr9518adk80d_defconfig
``` bash
west build -p -b tlsr9518adk80d ../zephyr/samples/bluetooth/peripheral
```

Expected: successful build

### PR DESCRIPTION
**Pull request by jhedberg**
The driver isn't currently buildable due to "west blobs" support never having been added for hal_telink. Furthermore, even if the blob dependency is manually made available it turns out the code has bitrotten to the point where it doesn't build anymore. This situation has continued for several years without anyone taking action, so I think it's safe to assume this is unmaintained and should be removed.

Fixes #52111

### CODE REVIEW

**Comment by jhedberg** [comment]
References:
https://github.com/zephyrproject-rtos/zephyr/issues/52113#issuecomment-2130954000

#52112

**Comment by jhedberg** [comment]
Sigh... seems like we can't just remove it, since hal_telink has references to the BT_B91 Kconfig option, i.e. those need to be removed first from the HAL tree.

**Review by alwa-nordic — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

**Comment by jori-nordic** [comment]
@jhedberg what do you think about this idea:
For every HCI driver in the tree, have a basic sample to build on a nightly basis. Shouldn't be very costly in CI IMO.

@carlescufi I still haven't gotten a clear answer on if Zephyr has a full nightly build that we can use for this kind of testing. Ie. stuff that doesn't need to be built for every PR, but still should be in order to prevent bitrot.

**Comment by jhedberg** [comment]
> @jhedberg what do you think about this idea: For every HCI driver in the tree, have a basic sample to build on a nightly basis. Shouldn't be very costly in CI IMO.

Wouldn't be even possible to have some simple Bluetooth app that lists as its integration platforms everything that's needed to cover all HCI drivers? I don't think that would case unreasonable overhead, maybe 10 more builds or so (compared to hundreds that CI currently does for Bluetooth PRs).

**Comment by jhedberg** [comment]
> > @jhedberg what do you think about this idea: For every HCI driver in the tree, have a basic sample to build on a nightly basis. Shouldn't be very costly in CI IMO.
> 
> Wouldn't be even possible to have some simple Bluetooth app that lists as its integration platforms everything that's needed to cover all HCI drivers? I don't think that would case unreasonable overhead, maybe 10 more builds or so (compared to hundreds that CI currently does for Bluetooth PRs).

It would also set a clear precedent for new HCI drivers (and even some existing ones) so that they don't go arbitrarily adding their respective boards to various Bluetooth sample/test apps.

Once we have the new HCI driver API in place, we could even have a dedicate HCI driver API test app (like we already do for many other driver APIs), which wouldn't enable the host or HCI_RAW at all, rather it just does some basic testing that the driver builds behaves as expected.

**Review by andriy-bilynskyy — APPROVED** [review]

**Comment by jhedberg** [comment]
@jori-nordic @alwa-nordic regarding CI coverage for all HCI drivers, @carlescufi just pointed out that we'll never be able to get that if some drivers depend on binary blobs. From https://docs.zephyrproject.org/latest/contribute/bin_blobs.html#support-and-maintenance:
> Regarding Continuous Integration, binary blobs will not be fetched in the project’s CI infrastructure that builds and optionally executes tests and samples to prevent regressions and issues from entering the codebase. This includes both CI ran when a new GitHub Pull Request is opened as well as any other regularly scheduled execution of the CI infrastructure.

I do think the Zephyr project could do a bit better than that. I think it'd make sense to have a blob-dependent build process separate from CI and a dashboard where we can see the build status of blob-dependent code in the main tree. That'd at least give a chance to make decisions prior to releases, i.e. to fix, remove or ignore the broken code.

**Comment by jori-nordic** [comment]
I agree, we should have a way to update these blobs. 

I'm unusure, but do we have a hashing function of some sort for individual blobs? In order to remove the risk of Zephyr CI being compromised by a compromised vendor server.

**Review by andriy-bilynskyy — APPROVED** [review]

**Comment by jhedberg** [comment]
@alwa-nordic @jori-nordic west.yml updated with my merged hal_telink PR - please re-approve if you're still fine with this

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Pull request merged**
