### PR TITLE
Tests: Minor change in descriptions and group name of SMP test cases

### PR DESCRIPTION
**Pull request by enjiamai**
Do minor change of the descriptions and doxygen group name. This is in order to pave the way for generation the integration/module test specification later. 

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

**Review by youhuazhu — APPROVED** [review]
seems good and double checked with doxygen.

**Review by LeiW000 — APPROVED** [review]
Simple change. Approve it.

**Comment by LeiW000** [comment]
@andrewboie , could you take look at it, them merge it if there is no comment from you?

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Merging since this is trivial.

**Pull request merged**
