### PR TITLE
devicetree: Remove special-casing for clocks, treating them like other phandle-array props

### PR DESCRIPTION
**Pull request by ulfalizer**
Remove almost all special-casing for `clocks = ...` properties and
handle them with the generic phandle-array code. The commits
below make the required changes to C and header files.

These output inconsistencies were fixed to able to reuse the
phandle-array code:

 - Properties like `pwms = ...` and `*-gpios = ...` generate identifiers
   with `PWMS` and `GPIOS` (note the -S), while `clocks` generated
   `CLOCK`.

 - A non-indexed `*_CLOCK_<clock-cells entry>` identifier (as opposed to
   `*_CLOCK_<clock-cells entry>_0`) was always generated, regardless of
   how many clocks there were. Properties like `pwms = ...` only
   generate a non-indexed identifier if there's a single entry in the
   phandle-array.

   (In practice, no `clocks = ...` has more than one entry in Zephyr.)

The only special-casing that remains is for `fixed-clock`:
`write_clocks()` is now `write_freq()`, which writes the `clock-frequency`
from any controller in `clocks` that's compatible with `fixed-clock`.

Besides reducing code duplication and making things less surprising and
easier to understand, this change has two nice side effects:

 - `description:` texts now show up for clocks now show up in the output

 - Static initializers like

       #define ..._CLOCKS {"SIM", 0, 4152, 20}

   now get generated.

Also add a check for `clocks` being a phandle-array in `write_freq()`.

Using the old macros now generates a warnings saying to use `*_CLOCKS_*' instead of `*_CLOCK_*`, via these commits:

```
scripts: gen_defines.py: Add out_dev() flag for deprecated macros

Add a 'deprecation_msg' string/flag to out_dev(). When 'deprecation_msg'
is passed, all generated macros include

    _Pragma("GCC warning \"<deprecation_msg>\"")

which prints a customizable warning if the macro is used.

Meant to be used when improving the output format.
```

```
scripts: dts: Generate deprecated clock #defines with warnings

Add back generation of the the non-phandle-array-consistent clock
defines, but generate deprecation warnings for them if they're used,
with a message saying to use *_CLOCKS_* instead of *_CLOCK_*.
```

Fixes in C code:

```
devicetree: dts_fixup.h: Remove unused *_CLOCK_{BITS,BUS}_0 macros

Copy-pasted around. Not used anywhere in the code. Equivalent to
*_CLOCK_{BITS,BUS} without an index.

I'm adapting all clock code to the preceding gen_defines.py change, and I'd
rather remove unused identifiers than fix them.
```

```
devicetree: dts_fixup.h: Use *_CLOCK_{BITS,BUS} without _0 suffix

Correct as long as there's a single clock in 'clocks = ...', which there
always is at the moment.

Makes the code compatible with write_phandle_val_list_entry().

Adapting all clock code to the preceding gen_defines.py change.
```

```
devicetree: s/CLOCK/CLOCKS/ in references to generated macros

gen_defines.py generated macros with 'PWMS' and 'GPIOS' in them for
'pwms = ...' and '*-gpios = ...', but 'clocks = ...' generates 'CLOCK',
with no -S. Replace 'CLOCK' with 'CLOCKS' to fix the inconsistency.

Adapting all clock code to the preceding gen_defines.py change.

I was careful to not change any macros defined in dts_fixup.h files
(which are currently also prefixed with 'DT_').
```

### CODE REVIEW

**Comment by ulfalizer** [comment]
The script change and the C code changes need to go in together. I just split it into multiple commits to make it easier to review.

Maybe this could go in as a merge commit. I could squash all of the commits together too, though it makes it a bit hard to understand.

**Comment by henrikbrixandersen** [comment]
While I generally think this is good simplification, I'm afraid it will break many out-of-tree drivers/bindings?

**Comment by ulfalizer** [comment]
@henrikbrixandersen 
Yeah, could cause some breakage, though it's a quick and simple fix at least.

I think the current devicetree output is in a bad enough shape that it's not worth preserving perfect backwards compatibility everywhere, or we'll never get anywhere. Once things have been streamlined a bit, we could be more careful.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by ulfalizer** [comment]
@henrikbrixandersen 
Added backwards compatibility now too, along with warnings that tell people what to do if they use the old macros (change `*_CLOCK_*` to `*_CLOCKS_*`). See these new commits:

 - `scripts: gen_defines.py: Add out_dev() flag for deprecated macros`

 - `scripts: dts: Generate deprecated clock #defines with warnings`

I also moved out the `deprecation_msg` functionality into [a separate PR](https://github.com/zephyrproject-rtos/zephyr/pull/21537), in case this PR gets stalled.

**Comment by pabigot** [comment]
> I think the current devicetree output is in a bad enough shape that it's not worth preserving perfect backwards compatibility everywhere, or we'll never get anywhere. Once things have been streamlined a bit, we could be more careful.

"could".

And this is exactly why I get so frustrated with zephyr (@carlescufi).  "The current solution is bad, so let's keep breaking it for everybody incrementally to fix the immediate problem until we finally figure out what we want to do."  No plan, just patching.

Even leaving the old one in as `deprecated` causes pain, since it produces build warnings that have to be fixed in pending PRs.  Which happened with the `parent/child-bus` rework.

No, I don't have a better solution.  But this is not consistent with Zephyr being "a quality code base with good engineering practices".

**Review by carlescufi — CHANGES_REQUESTED** [review]
> > I think the current devicetree output is in a bad enough shape that it's not worth preserving perfect backwards compatibility everywhere, or we'll never get anywhere. Once things have been streamlined a bit, we could be more careful.
> 
> "could".
> 
> And this is exactly why I get so frustrated with zephyr (@carlescufi). "The current solution is bad, so let's keep breaking it for everybody incrementally to fix the immediate problem until we finally figure out what we want to do." No plan, just patching.
> 
> Even leaving the old one in as `deprecated` causes pain, since it produces build warnings that have to be fixed in pending PRs. Which happened with the `parent/child-bus` rework.
> 
> No, I don't have a better solution. But this is not consistent with Zephyr being "a quality code base with good engineering practices".

In this case, I completely agree with @pabigot. Before we move forward with a change like this, we need to hear from the Device Tree maintainer, in this case @galak. Only after we know what the plan is mid and long term we should introduce breaking changes. That doesn't mean this PR is not going in the right direction, but we need to decide if this is the final direction before we merge it.

**Comment by ulfalizer** [comment]
> No, I don't have a better solution. But this is not consistent with Zephyr being "a quality code base with good engineering practices".

Because it isn't in this case. That's why I'm trying to fix it, through these slow and painstaking global fixups that realistically I don't think anyone but me would do.

Sure, could wait for some more feedback, but please work with me a bit when I'm putting in the legwork and doing stuff that no one else would do and that might save the devicetree stuff longterm.

**Comment by ulfalizer** [comment]
Here's an example warning-turned-error from CI by the way (new stuff, fixed now):

```
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/soc/arm/nxp_kinetis/ke1xf/soc.c:185:13:
error: Please use *_CLOCKS_* instead of *_CLOCK_*. The output for clock properties is now consistent with other phandle-array properties. [-Werror]
    CLOCK_SetIpSrc(kCLOCK_Lpspi0, DT_NXP_IMX_LPSPI_SPI_0_CLOCK_IP_SOURCE);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
```

Fixed with an `s/_CLOCK_/_CLOCKS_/`, as indicated.

**Comment by galak** [comment]
Can you rebase.

**Comment by ulfalizer** [comment]
> Can you rebase.

Rebased now.

Will do a check for newly-added stuff a bit later. Marking DNM for now.

**Comment by ulfalizer** [comment]
> Will do a check for newly-added stuff a bit later. Marking DNM for now.

Should be fine again now.

**Comment by galak** [comment]
@erwango can you take a look.

**Review by erwango — APPROVED** [review]

**Comment by galak** [comment]
Closing this as lot of this change will/is happening with the conversion to the new DT macros.

**Pull request closed without merging**
