### PR TITLE
sample: usb: shell: add keybord harness string

### PR DESCRIPTION
**Pull request by jfischer-no**
Add keybord harness string to sample.yaml file.

### CODE REVIEW

**Comment by desowin** [comment]
How do you run the test with this fix? When I run `./scripts/twister -T samples/subsys/usb/shell -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs` it simply skips the test.

**Comment by jfischer-no** [comment]
> How do you run the test with this fix? When I run `./scripts/twister -T samples/subsys/usb/shell -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs` it simply skips the test.

It is not a test, it is a sample, but yes, see also https://docs.zephyrproject.org/latest/develop/test/twister.html#test-runner-twister

**Comment by desowin** [comment]
> > How do you run the test with this fix? When I run `./scripts/twister -T samples/subsys/usb/shell -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs` it simply skips the test.
> 
> It is not a test, it is a sample, but yes, see also https://docs.zephyrproject.org/latest/develop/test/twister.html#test-runner-twister

Could you please be a bit more specific? The documentation mentions `The test configuration has defined a harness but you don’t have it or haven’t set it up.`, but I cannot see how to setup the `kyeboard` harness and https://github.com/zephyrproject-rtos/zephyr/discussions/46553 is unanswered.

**Review by desowin — CHANGES_REQUESTED** [review]
This simply skips the test instead of actually solving the issue. The problem seems to be in twister not in the shell sample.

If I add `ser.write(b'\n')` before https://github.com/zephyrproject-rtos/zephyr/blob/da2305081242b61067784a9f0c034f0105bc31a8/scripts/pylib/twister/twisterlib/handlers.py#L376 then twister still fails despite the log containing a lot of lines.

**Comment by jfischer-no** [comment]
> This simply skips the test instead of actually solving the issue. The problem seems to be in twister not in the shell sample.
> 
> If I add `ser.write(b'\n')` before
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/da2305081242b61067784a9f0c034f0105bc31a8/scripts/pylib/twister/twisterlib/handlers.py#L376
> then twister still fails despite the log containing a lot of lines.

Where did I claim it is solving an issue? Whatever you found out about twister, string harness keyboard belongs in the sample.yml just like in any other shell sample.

**Review by desowin — APPROVED** [review]
The harness essentially skips the test as keyboard harness was never implemented. SImply skipping shell tests seems to be twister status quo for the time being.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
