### PR TITLE
posix: sched: Implement sched_setparam() and sched_setscheduler()

### LINKED ISSUE #66962: posix: implement `sched_setparam()`
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`sched_setparam()` is required as part of `_POSIX_PRIORITY_SCHEDULING` Option Group.

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/sched_setparam.html

### LINKED ISSUE #66963: posix: implement `sched_setscheduler()`
This is part of the See [POSIX Roadmap for LTSv3](https://github.com/zephyrproject-rtos/zephyr/issues/51211) (RFC #51211).

`sched_setscheduler()` is required as part of `_POSIX_PRIORITY_SCHEDULING` Option Group.

For more information, please refer to https://pubs.opengroup.org/onlinepubs/9699919799/functions/sched_setscheduler.html

### PR DESCRIPTION
**Pull request by moonlight83340**
Implement sched_setparam() and sched_setscheduler() POSIX APIs
as a part of PSE53 _POSIX_PRIORITY_SCHEDULING option group.

I start my draft from the pull request : https://github.com/zephyrproject-rtos/zephyr/pull/67028

Resolves : https://github.com/zephyrproject-rtos/zephyr/issues/66963
resolves : https://github.com/zephyrproject-rtos/zephyr/issues/66962

### CODE REVIEW

**Comment by golowanow** [comment]
@moonlight83340 why you duplicate #67028 ?

**Comment by moonlight83340** [comment]
> @moonlight83340 why you duplicate #67028 ?

Sorry I wanted to continue with your work for base (That why it's a draft).

**Comment by golowanow** [comment]
> > @moonlight83340 why you duplicate #67028 ?
> 
> Sorry I wanted to continue with your work for base (That why it's a draft).

then could you rename it and give some description ? just to avoid confusion

**Comment by moonlight83340** [comment]
> > > @moonlight83340 why you duplicate #67028 ?
> > 
> > 
> > Sorry I wanted to continue with your work for base (That why it's a draft).
> 
> then could you rename it and give some description ? just to avoid confusion

Okay, I will do that, thank you

**Comment by moonlight83340** [comment]
> > > @moonlight83340 why you duplicate #67028 ?
> > 
> > 
> > Sorry I wanted to continue with your work for base (That why it's a draft).
> 
> then could you rename it and give some description ? just to avoid confusion

Seems okay for you ?
The title was already different, I had description and that I take my start from your PR.

**Pull request closed without merging**
