### PR TITLE
pm: Do not suspend during kernel initialization

### LINKED ISSUE #41839: BLE causes system sleep before main
**Describe the bug**
When the BLE subsystem is enabled (CONFIG_BT=y) then system enters idle thread (sleep) before main function is invoked.

Tested on blinky sample with CONFIG_BT=y and with small code changes as described below.
main.c
```C
...
volatile uint32_t idle_counter = 0;

void main(void)
{
        if (idle_counter > 0) {
                printk("idle_entry: %u", idle_counter);
        }
...
```
idle.c
```C
...
	while (true) {
	    extern volatile uint32_t idle_counter;
	    idle_counter++;
...
```

Target (board) is nucleo_wb55rg.

**To Reproduce**
1. Modify blinky sample and idle.c as described above.
2.  west build --board=nucleo_wb55rg
3. west flash
4. See output on console: `idle_entry: 2`

**Expected behavior**
System should not sleep before entering main or this behavior should be documented.

**Impact**
annoyance

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA: 44462723f59ddcc0786af0b5406122476c2addf9

### PR DESCRIPTION
**Pull request by ceolin**
Check if the kernel has fully initialized before take any action that
may suspend the system.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by erwango — COMMENTED** [review]
@ceolin This sounds reasonable, but I had a try and this doesn't fix https://github.com/zephyrproject-rtos/zephyr/issues/41839

**Review by peter-mitsis — APPROVED** [review]

**Comment by ceolin** [comment]
> @ceolin This sounds reasonable, but I had a try and this doesn't fix #41839

This does not prevent the system to goes idle but prevents it of suspending, so it is still  reasonable of having

**Comment by erwango** [comment]
> This does not prevent the system to goes idle but prevents it of suspending, so it is still reasonable of having

Sure, but I think we should remove the "Fixes #41839" indication.

**Comment by ceolin** [comment]
> > This does not prevent the system to goes idle but prevents it of suspending, so it is still reasonable of having
> 
> Sure, but I think we should remove the "Fixes #41839" indication.

absolutely !

**Pull request merged**
