### PR TITLE
kconfig: Deprecate BOOTLOADER_SRAM_SIZE

### LINKED ISSUE #65118: Non-XIP (ARM) images lock up when common malloc area Kconfig is set to -1
**Describe the bug**
Testing MCUboot's RAM LOAD mode seems to fail when trying to boot an image whereby the common malloc size is -1 (this means to use the rest of available RAM for heap). Upon setting this Kconfig to 0 or another value (e.g. 4096) then the image loads and functions fine.

**Expected behavior**
Image to boot and work

**Impact**
Showstopper

**Logs and console output**
There is no output at all, not even the boot banner outputs, trying to debug it (before knowing it was the malloc Kconfig) did not yield anything useful, the kernel seemed to start then get to a point whereby the stack trace made no sense and was corrupt.

**Environment (please complete the following information):**
 - Commit SHA or Version used: 3003cc1938f53074ad717af79d1ff1e7ff15b514

### LINKED ISSUE #65121: RFC: Remove CONFIG_BOOTLOADER_SRAM_SIZE
## Introduction

This is an RFC to discuss potentially removing of the Kconfig BOOTLOADER_SRAM_SIZE symbol, why you might ask, read on to find out why:

### Problem description

This symbol sounds like it's useful for non-XIP applications, so you can have your application set up then set this symbol to the amount of RAM that your bootloader uses and away you go, thinking it would offset the start of your image by the value given. This however, is not the case, this is the Cortex-M code for this Kconfig:
```
#if defined(CONFIG_XIP)  
#if defined(CONFIG_IS_BOOTLOADER)
#define RAM_SIZE (CONFIG_BOOTLOADER_SRAM_SIZE * 1K)
#define RAM_ADDR (CONFIG_SRAM_BASE_ADDRESS + \
        (CONFIG_SRAM_SIZE * 1K - RAM_SIZE))
#else
#define RAM_SIZE (CONFIG_SRAM_SIZE * 1K)
#define RAM_ADDR CONFIG_SRAM_BASE_ADDRESS
#endif
#else
#define RAM_SIZE (CONFIG_SRAM_SIZE * 1K - CONFIG_BOOTLOADER_SRAM_SIZE * 1K)
#define RAM_ADDR CONFIG_SRAM_BASE_ADDRESS
#endif
```

So from looking at it, I don't really see what the point of this symbol is, it adjusts the total RAM size of your application, but does nothing to the base SRAM address? If you assume that the bootloader uses 64KB of RAM (at the start address of RAM, as we do other partitions e.g. flash) then want to load your application after, you can't use this Kconfig, you have to play with the Kconfigs for the RAM base address and total RAM size.

### Proposed change

Remove this Kconfig. Alternatively, change it so it applies to the start of RAM and affects both the address and size, instead of just the end size address.

### Concerns and Unresolved Questions

Unknown is anyone using this Kconfig, whom that is I do not know. @GAnthony since you seem to use this symbol on cc3220sf, do you have any input on this? And why it adjusts the end address of RAM to the application, not the start address and total size?

### PR DESCRIPTION
**Pull request by nordicjm**
This Kconfig is seemingly unused with exception to a single board,
    whose maintainers have been unresponsive for a long time. It is
    not useful to any other board and can be set in dts, therefore
    deprecate it and schedule removal after the Zephyr 3.7 release

Fixes #65121

### CODE REVIEW

**Comment by Laczen** [comment]
@nordicjm it is to be expected that this Kconfig option is not used in the zephyr tree, this is mainly used by a bootloader to setup the ram usage at the end of ram. Bootloaders are not part of the zephyr tree and even mcuboot has no in tree zephyr configuration that shows how to setup ram loading.
The fact that even when this Kconfig option is set to 0 allows bootloaders to boot the ram image in 99.9 % of the cases does not mean it can be removed because a bootloader needs it to define its ram usage.
I agree that this can be done using the dts, but an example of this would also not be part of the zephyr tree (as it is a bootloader setup). At least it should be documented somewhere how to setup the ram for bootloader usage in the dts as an alternative to the present Kconfig option.

**Comment by nordicjm** [comment]
> At least it should be documented somewhere how to setup the ram for bootloader usage in the dts as an alternative to the present Kconfig option.

This would be down to users and their choice of bootloader, the in-tree supported bootloader does not need this with the default configuration of swap using move/scratch

**Comment by nordicjm** [comment]
@vaishnavachath @vanti @tejlmand @de-nordic @d3zd3z @microbuilder please review

**Review by henrikbrixandersen — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
LGTM, thanks for this cleanup.

Note, this issue also seems to have been discussed earlier: https://github.com/zephyrproject-rtos/zephyr/issues/49484

**Review by microbuilder — APPROVED** [review]

**Review by vaishnavachath — APPROVED** [review]

**Comment by Laczen** [comment]
> > At least it should be documented somewhere how to setup the ram for bootloader usage in the dts as an alternative to the present Kconfig option.
> 
> This would be down to users and their choice of bootloader, the in-tree supported bootloader does not need this with the default configuration of swap using move/scratch

The default configuration should not be determining this, it should be all configurations of the in-tree supported bootloader. The documentation is needed for mcuboot running images from ram. This documentation should also show that it is possible to reuse the bootloader ram.

**Review by Laczen — DISMISSED** [review]
Requires documentation for setting up a bootloader that starts images from ram.

**Comment by nordicjm** [comment]
> Requires documentation for setting up a bootloader that starts images from ram.

How is that of any relevance to this change? Point out exactly why that is necessary to deprecate a feature that is undocumented, unused, unsupported and didn't have anything to do with what you're talking about here since it never worked with it:

**Comment by Laczen** [comment]
> > Requires documentation for setting up a bootloader that starts images from ram.
> 
> How is that of any relevance to this change? Point out exactly why that is necessary to deprecate a feature that is undocumented, unused, unsupported and didn't have anything to do with what you're talking about here since it never worked with it:

`BOOTLOADER_SRAM_SIZE` is used for 2 things:
1. For a XIP bootloader define the used ram size **AND** move it to the end of the available ram,
2. For a non-XIP image determine what ram is not available by reducing the available ram,

So let's make mcuboot (XIP) for a system with ram loading of images: Set `CONFIG_BOOTLOADER_SRAM_SIZE` to e.g. 16kB, mcuboot will use this 16kB at the end of RAM,
Make a RAM image for this case, as long as the end of the heap is smaller than end of RAM - 16kB it is possible to generate a image that fully utilizes the RAM for the execution slot, so for the application we can set `CONFIG_BOOTLOADER_SRAM_SIZE` equal to 0. The 16kB is available for the stack.

How is this relevant to the change: The change removes this kind of setup completely while not providing a solution of how to make this setup.

**Comment by nordicjm** [comment]
> For a XIP bootloader define the used ram size AND move it to the end of the available ram,

Not supported by anything in-tree in zephyr, not relevant

> For a non-XIP image determine what ram is not available by reducing the available ram,

Not supported by anything in-tree in zephyr, not relevant

> So let's make mcuboot (XIP) for a system with ram loading of images:

You're talking about a new feature or sample, nothing to do with this PR

**Comment by Laczen** [comment]
@nordicjm,
since v3.6 nordic devices are using imply `CONFIG_XIP` to allow creating ram based images by setting `CONFIG_XIP=n` (although at the moment this doesn't seem to work).
Mcuboot has been supporting ram loading of images since ... (probably from the start), and this is supported by zephyr (illustrated by https://github.com/mcu-tools/mcuboot/blob/main/boot/zephyr/main.c#L152 and https://github.com/mcu-tools/mcuboot/blob/main/boot/zephyr/ram_load.conf).

**Comment by nordicjm** [comment]
Right and where do any of them set BOOTLOADER_SRAM_SIZE ?

**Comment by Laczen** [comment]
> Right and where do any of them set BOOTLOADER_SRAM_SIZE ?

They don't because the example for ram loading seems to have a lot of ram that doesn't need to reuse it. An example configuration shouldn't be used as a determining factor for removing a Kconfig option. Instead it is better to look at an example where the Kconfig option would be used and to determine if this can really be removed.

As said, mcuboot and zephyr clearly support ram loading of images on all boards. When removing this Kconfig option all of them would need a dts showing how to use this. The existing Kconfig options could also be documented, this would be a lot less work.

**Comment by nordicjm** [comment]
> They don't because the example for ram loading seems to have a lot of ram that doesn't need to reuse it. An example configuration shouldn't be used as a determining factor for removing a Kconfig option. Instead it is better to look at an example where the Kconfig option would be used and to determine if this can really be removed.

Quite right, an example would be great

> As said, mcuboot and zephyr clearly support ram loading of images on all boards. When removing this Kconfig option all of them would need a dts showing how to use this. The existing Kconfig options could also be documented, this would be a lot less work.

A great idea **for an enhancement**, not for deprecating something that **has no in-tree usage**.

To make things simple, as a MCUboot collaborator, build system collaborator and nordic employee, because your NACK comments are actually of no relevance to this change I will be dismissing your review 2 days from now at which point this PR can be merged. You are will within your rights to escalate this should you wish to do so by following the information presented on https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#pr-technical-escalation or alternatively can withdraw your NACK and (optionally) create a new enhancement bug describing the additions you would like to see for a RAM loading sample.

**Comment by Laczen** [comment]
@MaureenHelm, a quick summary of my view as a preparation of the dev-review meeting:

1. The PR proposes a removal of configuration value(s) that are valuable when building zephyr based bootloaders or zephyr based applications for ram execution that use an out-of-tree bootloader that is configured to use a region of ram at the end of the available ram,
2. With the values ram load images can be generated that are located at the start of ram and in specific conditions can utilize the complete available ram (although this is not implied by the configuration values),
3. The PR is justified by the ascertainment that the configuration value is not used in-tree. This justification is questionnable,

My proposal is:
1. Keep the configuration values, document the use in more detail (especially `CONFIG_IS_BOOTLOADER`) and inform the mcuboot developers on how to use these configuration values,
2. If it is really considered not an option to keep these configuration values the PR should include documentation on how the configuration can be created using an alternative method (dts ?) so that it is possible to evaluate if it is better to keep these configuration values or the alternative method.

**Comment by nordicjm** [comment]
> The PR proposes a removal of configuration value(s) that are valuable when building zephyr based bootloaders or zephyr based applications for ram execution that use an out-of-tree bootloader that is configured to use a region of ram at the end of the available ram,

It is not supported by the official zephyr bootloader: MCUboot

> The PR is justified by the ascertainment that the configuration value is not used in-tree. This justification is questionnable,

Yet in the whole thread you've be unable to point to a single project making use of this

> Keep the configuration values, document the use in more detail (especially CONFIG_IS_BOOTLOADER) and inform the mcuboot developers on how to use these configuration values,

As previously said as a collaborator for MCUboot: no

> If it is really considered not an option to keep these configuration values the PR should include documentation on how the configuration can be created using an alternative method (dts ?) so that it is possible to evaluate if it is better to keep these configuration values or the alternative method.

So where is the documentation for what this deprecates?

**Comment by carlescufi** [comment]
@Laczen @nordicjm I did not realize this had the dev-review label when I merged this. Let me bring this to the attention of others.

**Comment by Laczen** [comment]
@nordicjm, it is needed to deprecate `CONFIG_IS_BOOTLOADER` as well. When `CONFIG_BOOTLOADER_SRAM_SIZE` is not available it is not possible to generate a bootloader with the `CONFIG_IS_BOOTLOADER` option.

**Pull request merged**
