### PR TITLE
sanitycheck: Append 'sanity-out' directory to --outdir argument.

### PR DESCRIPTION
**Pull request by hakonfam**
Partial solution to #7146

This is done to reduce chances of users deleting data unintended.

Signed-off-by: Håkon Øye Amundsen haakon.amundsen@nordicsemi.no

### CODE REVIEW

**Comment by SebastianBoe** [comment]
CI is failing. I assume it needs to be updated to work with the new behaviour.

https://github.com/zephyrproject-rtos/zephyr/blob/master/.shippable.yml

**Comment by carlescufi** [comment]
CI is failing because the signed-off-line is not matching the email in the commit author:
```
author email (Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>) needs to match one of the signed-off-by entries.
``

**Comment by galak** [comment]
Can you clarify if sanity-out is appended to the dir name, or another directory is created?

I'm also not sure I see the value of this change.

**Comment by hakonfam** [comment]
@galak Do you mean to clarify it in code or here? Another directory called `sanity-out` will be created. 

The value is simply to avoid users deleting data unintended. 
Imagine a first time user (like me) running `scripts/sanitycheck` and wanting to have the test report put in their projects root folder, this will result in the entire project folder being deleted. All local branches and non-tracked files will be deleted.

**Comment by galak** [comment]
> @galak Do you mean to clarify it in code or here? Another directory called sanity-out will be created.

Both.  In the commit message, and code.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
why are we doing this??

**Review by nashif — CHANGES_REQUESTED** [review]
instead of change options and defaults, I propose to perform some checks on the directory before it gets deleted, i.e. if directory exists when we try to create it the first time, check if it has some data from a previous run before deleting, if it does not, bail out or something like that.

**Comment by andrewboie** [comment]
NACK

I don't think this is a problem that needs to be addressed.
Why are you pointing sanitycheck's out directory to a directory containing non-disposable information?

>  it is NOT CLEAR that it will delete my_important_folder

At most, update the --help documentation.
Not introduce a Rube Goldberg contraption with respect to test artifact output.

**Comment by hakonfam** [comment]
> instead of change options and defaults, I propose to perform some checks on the directory before it gets deleted, i.e. if directory exists when we try to create it the first time, check if it has some data from a previous run before deleting, if it does not, bail out or something like that.

To ensure that all generated files is deleted, one would have to store a list of generated files. This because the set of generated files might change across versions. So I don't see this as a feasible solution.

**Comment by hakonfam** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/7183

**Pull request closed without merging**
