### PR TITLE
watchdog: atmel_sam: enable build for all SAM family

### PR DESCRIPTION
**Pull request by mnkp**
atmel_sam watchdog driver was temporarily limited to SAME70
series only. Now that all SAM series are using ASF the
change can be reverted.

Signed-off-by: Piotr Mienkowski <piotr.mienkowski@gmail.com>

### CODE REVIEW

**Comment by galak** [comment]
Can I get use to rebase on latest arm branch, sorry I updated the branch after merge with master :)

**Review by fallrisk — COMMENTED** [review]
This change looks trivial so it's probably good. I was wondering if we could wait to merge it until tonight. I want to test the hello world sample on the Arduino Due and the SAM4S Xplained. If we wait we can include fixes for them in this PR? Or do you guys (@mnkp and @galak) just want to merge it and if there is a problem make a new PR to fix Watchdog on the SAM4S Xplained board and Arduino Due board.

**Comment by mnkp** [comment]
I have a bit of a problem with watchdog as - for whatever reason - it does not reset my board even when the watchdog unit is enabled, i.e. when the wdt_sam driver is disabled the board should start with watchdog unit enabled by default and reset every 16 s. That's not happening. Tested both on Arduino Due and SAM E70 Xplained.

I can confirm however that with wdt_sam driver enabled the WDT_MR.WDDIS bit is set upon startup. It means that the driver works and the watchdog unit was disabled. Tested both on Arduino Due and SAM E70 Xplained board.

It would be certainly nice to know how the driver behaves on SAM4S Xplained board.

**Comment by fallrisk** [comment]
Sure, I will let you know tonight when I am at the hardware how the SAM4S Xplained behaves. I wasn't aware you had an Arduino Due, that's why I offered to test against it.

**Review by fallrisk — APPROVED** [review]
I tested on the SAM4S and I see the same results as you did with the SAME70 and SAM3X. I think the fact that it doesn't reset might have to do with WDIDLEHLT being brought up set. I need to investigate it further.

Your PR looks good to me.

**Comment by mnkp** [comment]
It would be good if we merged this commit also on 1.8 branch. Before the move to ASF the SAM3X init routine disabled the watchdog, this is not the case any more and ultimately the watchdog starts in its default, enabled state.

Disabling the watchdog during SoC initialization was wrong. Watchdog can be programmed only once, and as such, the previous solution made the watchdog unit unusable. The current solution with an independent watchdog driver is the proper one. We have to make sure however that the watchdog driver is enabled by default otherwise the implementation can be considered buggy.

**Review by galak — APPROVED** [review]

**Comment by mnkp** [comment]
Should I resubmit this PR against v1.8-branch or will it make to the release anyway?

**Pull request merged**
