### PR TITLE
stm32L4s5 disco kit has ospi for quad Nor-flash access 

### LINKED ISSUE #52276: stm32: ST Kit B-L4S5I-IOT01A Octospi flash support
**Is your enhancement proposal related to a problem? Please describe.**

The B-L4S5I-IOT01A board has an onboard QSPI flash, but the flash memory is not exposed in the device tree. 

**Describe the solution you'd like**

I would like the ability to use the external flash memory with the B-L4S5I-IOT01A board. 

**Describe alternatives you've considered**

I tried adding support for ospi flash to the device tree from v3.2.0, but ran into driver compatibility issues with the stm32l4 ospi hal (see below).

The [Stm32CubeL4 HAL implementation](https://github.com/zephyrproject-rtos/hal_stm32/blob/main/stm32cube/stm32l4xx/drivers/include/stm32l4xx_hal_ospi.h) does not appear to be compatible with the [OSPI flash driver](https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v3.2.0/drivers/flash/flash_stm32_ospi.c). Curiously there does appear to be a compatible implementation of stm32L4xx_hal_ospi out there (for example the [implementation used by the LoRaMac-Node](https://github.com/zephyrproject-rtos/loramac-node/blob/zephyr/src/boards/mcu/stm32/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_ospi.h)).

### Errors from build: 

```bash
/home/brian/zephyrproject/zephyr/drivers/flash/flash_stm32_ospi.c: In function 'flash_stm32_ospi_init':
/home/brian/zephyrproject/zephyr/drivers/flash/flash_stm32_ospi.c:1766:29: error: 'OSPI_InitTypeDef' has no member named 'WrapSize'
 1766 |         dev_data->hospi.Init.WrapSize = HAL_OSPI_WRAP_NOT_SUPPORTED;
      |                             ^
/home/brian/zephyrproject/zephyr/drivers/flash/flash_stm32_ospi.c:1766:41: error: 'HAL_OSPI_WRAP_NOT_SUPPORTED' undeclared (first use in this function); did you mean 'HAL_DMA_ERROR_NOT_SUPPORTED'?
 1766 |         dev_data->hospi.Init.WrapSize = HAL_OSPI_WRAP_NOT_SUPPORTED;
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         HAL_DMA_ERROR_NOT_SUPPORTED
/home/brian/zephyrproject/zephyr/drivers/flash/flash_stm32_ospi.c:1766:41: note: each undeclared identifier is reported only once for each function it appears in
/home/brian/zephyrproject/zephyr/drivers/flash/flash_stm32_ospi.c:1778:29: error: 'OSPI_InitTypeDef' has no member named 'Refresh'
 1778 |         dev_data->hospi.Init.Refresh = 0;
      |                             ^
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/brian/firmware/build
```

### Changes to the device tree:

```
diff --git a/dts/arm/st/l4/stm32l4r5.dtsi b/dts/arm/st/l4/stm32l4r5.dtsi
index 6bd658232a..d85ac9b546 100644
--- a/dts/arm/st/l4/stm32l4r5.dtsi
+++ b/dts/arm/st/l4/stm32l4r5.dtsi
@@ -6,6 +6,7 @@
 
 #include <mem.h>
 #include <st/l4/stm32l4.dtsi>
+#include <zephyr/dt-bindings/flash_controller/ospi.h>
 
 / {
        sram0: memory@20000000 {
@@ -246,6 +247,17 @@
                        };
                };
 
+    // 0xA000 1400 - 0xA000 13FF
+               octospi2: octospi@a0001000 {
+                       compatible = "st,stm32-ospi";
+      reg = <0xA0001000 0x400>; 
+                       interrupts = <76 0>;  
+      clocks = <&rcc STM32_CLOCK_BUS_AHB3 0x00000100>; 
+                       #address-cells = <1>;
+                       #size-cells = <0>;
+                       status = "disabled";
+               };
+
                can1: can@40006400 {
                        compatible = "st,stm32-can";
                        reg = <0x40006400 0x400>;
```

```
diff --git a/boards/arm/b_l4s5i_iot01a/b_l4s5i_iot01a.dts b/boards/arm/b_l4s5i_iot01a/b_l4s5i_iot01a.dts
index ffe1b59029..e2aa37a02e 100644
--- a/boards/arm/b_l4s5i_iot01a/b_l4s5i_iot01a.dts
+++ b/boards/arm/b_l4s5i_iot01a/b_l4s5i_iot01a.dts
@@ -205,6 +205,43 @@
        };
 };
 
+&octospi2 {
+    pinctrl-0 = <&octospim_p1_clk_pe10 &octospim_p1_ncs_pe11
+                 &octospim_p1_io0_pe12 &octospim_p1_io1_pe13
+                 &octospim_p1_io2_pe14 &octospim_p1_io3_pe15
+                 &octospim_p1_io4_pd4 &octospim_p1_io5_pd5
+                 &octospim_p1_io6_pd6 &octospim_p1_io7_pd7>;
+
+
+    pinctrl-names = "default";
+
+    status = "okay";
+
+    mx25r6435f: ospi-nor-flash@0 {
+            compatible = "st,stm32-ospi-nor";
+            reg = <0>;
+            ospi-max-frequency = <DT_FREQ_M(50)>;
+            size = <DT_SIZE_M(64)>;
+            spi-bus-width = <OSPI_QUAD_MODE>; /* access on 4 data lines */
+            data-rate = <OSPI_STR_TRANSFER>; /* access in STR */
+            status = "okay";
+    };
+
+    partitions {
+                          compatible = "fixed-partitions";
+                          #address-cells = <1>;
+                          #size-cells = <1>;
+
+                          partition@0 {
+                              label = "nor";
+                              reg = <0x00000000 DT_SIZE_M(4)>;
+                          };
+               };
+
+};
+
 &rtc {
        status = "okay";
 };
```

**Additional context**

I modeled my changes after [this pull request](https://github.com/zephyrproject-rtos/zephyr/pull/39770) by @FRASTM  though the st,stm32-ospi-nor binding has been updated to allow for quadspi mode since.

### PR DESCRIPTION
**Pull request by FRASTM**
Add the support of the OCTOSPI peripheral to the stm32L4 plus serie
The stm32L4S5 serie has two octospi peripherals with in octospiM to multiplex IO pins.

See the stm32L4S5  refman [RM0432](https://www.st.com/content/ccc/resource/technical/document/reference_manual/group0/81/c8/d7/84/ba/20/48/5f/DM00310109/files/DM00310109.pdf/jcr:content/translations/en.DM00310109.pdf)  quad NOR-flash

The stm32l4s5r disco_kit b_l4s5i_iot01a  has a [MX25R6435F](https://www.mxic.com.tw/Lists/Datasheet/Attachments/8868/MX25R6435F,%20Wide%20Range,%2064Mb,%20v1.6.pdf) quad NOR-flash.
On the b_l4s5i_iot01a  board, the NOR flash is connected on 4 SPI IO lines and uses the QUAD-SPI mode to transfer data over the octospi1 peripheral.

The DMA (through DMAMUX) is enabled to operate transfer on the octoSPI bus.

Requires https://github.com/zephyrproject-rtos/zephyr/pull/47962  for jedec SDFP support

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/52276

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
Requires https://github.com/zephyrproject-rtos/zephyr/pull/47962  support to be merged

**Comment by FRASTM** [comment]
Rebase after merge of SFDP support
Adapt the flash ospi driver for the stm32l4plus (stm32l4Rx, stm32l4Sx, stm32l4Px, stm32l4Qx)
Tested on b_l4s5i_iot01a the disco  kit in the SPI, DUAL, QUAD (STR transfer rate) modes with or without DMA transfer.
The writeopcode is "writeoc="PP_1_4_4" or "PP" both are supported by the NOR octoflash.

The spi max freq must be limited to 26MHz to fit the octospi characteristics (see  [DS12024](https://www.st.com/content/ccc/resource/technical/document/datasheet/group3/f3/8d/da/d9/97/b8/4c/cc/DM00366449/files/DM00366449.pdf/jcr:content/translations/en.DM00366449.pdf))

**Comment by FRASTM** [comment]
running the west build -p auto -b b_l4s5i_iot01a samples/drivers/spi_flash
```
ospi-nor-flash@0 SPI flash testing
==========================

Test 1: Flash erase
Flash erase succeeded!

Test 2: Flash write
Attempting to write 4 bytes
Data read matches data written. Good!!
```

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Comment by bdunlay** [comment]
I think there may still be an issue related to the flash addressing. I am not able to successfully read from the external flash memory if the partition size is greater than 4 MB. I am hitting this issue using code very similar to the littlefs sample. I can open a new issue if you'd like. @FRASTM @GeorgeCGV 

```
[00:00:00.905,000] <err> flash_stm32_ospi: Error: address or size exceeds expected values: addr 0x3f2000, size 16
[00:00:00.905,000] <err> fs: failed to create directory (-22)
```

**Comment by bdunlay** [comment]
Created an issue to track this, linked above.

**Pull request merged**
