### PR TITLE
west.yml: Update zcbor to point to 0.7.0

### LINKED ISSUE #53375: net: lwm2m: write method when floating point
**Describe the bug**
When server send write operation (float) on 3340/0/5521, internal server error (500) is returned.

Please also mention any information which could help others to understand
the problem you're facing:
- SENML CBOR is used. cbor_decode_lwm2m_senml function doesn't return ZCBOR_SUCCESS and then return EBADMSG
```
dret = cbor_decode_lwm2m_senml(ICTX_BUF_R_PTR(&msg->in), ICTX_BUF_R_LEFT_SZ(&msg->in),
					   &fd->dcd, &decoded_sz);

if (dret != ZCBOR_SUCCESS) {
	ret = -EBADMSG;
	goto error;
}
```
- CBOR : it returns net_lwm2m_cbor: unable to decode a floating-point value and returns internal server error (500)

I am using leshan server with SENML CBOR (and CBOR for test).
Wireshark trace of write request 
```
0000   04 91 62 87 26 2f d4 54 8b 8c 1b a8 08 00 45 00   ..b.&/.T......E.
0010   00 4b ae 89 00 00 80 11 00 00 c0 a8 00 35 c0 a8   .K...........5..
0020   00 3c 16 35 a1 84 00 37 82 0a 48 03 ee 0b b0 2b   .<.5...7..H....+
0030   28 45 c6 6a bc c3 b4 33 33 34 30 01 30 04 35 35   (E.j...3340.0.55
0040   32 31 11 70 ff 81 a2 02 f9 4f 80 21 6c 2f 33 33   21.p.....O.!l/33
0050   34 30 2f 30 2f 35 35 32 31                                   40/0/5521
```

**To Reproduce**
1. lwm2m client sample
2. add res instance 5521 with post_write_callback
3. make
4. Launch write request on 3340/0/5521

**Expected behavior**
Write request deserialization of float success and then call post_write callback directly

### PR DESCRIPTION
**Pull request by oyvindronningstad**
Among other things, this update brings:

* C++ improvements
* float16 support
* Improved docs
* -Wall and -Wconversion compliance

Fixes #53375

### CODE REVIEW

**Comment by nordicjm** [comment]
This seems to have broken a test, can you investigate @oyvindronningstad ?

**Review by nordicjm — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Review by SeppoTakalo — DISMISSED** [review]

**Review by de-nordic — DISMISSED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by oyvindronningstad** [comment]
@SeppoTakalo @rlubos @de-nordic Please re-approve if you can. I just updated the sha in west.yml.

**Review by SeppoTakalo — APPROVED** [review]

**Comment by SeppoTakalo** [comment]
@oyvindronningstad Please add:
```
Fixes #53375
```

to your PR description so it automatically closes that issue.

Fixes #53375

**Comment by SeppoTakalo** [comment]
I did manual verification against Leshan with our LwM2M client using SenML-CBOR content format. This PR seem to fix the float16 problem.

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
