### PR TITLE
boards: m5stack: cores3: Add AW9523B configuration

### PR DESCRIPTION
**Pull request by soburi**
Adding AW9523B gpio expander configuration.

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]

**Comment by soburi** [comment]
@sylvioalves @marekmatej 

Could you please check this too?

**Comment by sylvioalves** [comment]
@soburi, I think the `compatible` you used isn't available in Zephyr. Perhaps you can add a new file at `zephyr/dts/bindings/gpio/awinic,aw9523b-gpio.yaml` with a similar content as in below:

```c
# Copyright (c) ....
# SPDX-License-Identifier: Apache-2.0

description: AWINIC AW9523B GPIO Controller

compatible: "awinic,aw9523b-gpio"

include: gpio-controller.yaml

gpio-cells:
  - pin
  - flags
```

@kartben Can you confirm?

**Comment by soburi** [comment]
@sylvioalves 

> @soburi, I think the `compatible` you used isn't available in Zephyr. Perhaps you can add a new file at `zephyr/dts/bindings/gpio/awinic,aw9523b-gpio.yaml` with a similar content as in below:

The file has already been available for just 6 hours before.

https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/gpio/awinic%2Caw9523b-gpio.yaml

**Comment by sylvioalves** [comment]
> @sylvioalves
> 
> > @soburi, I think the `compatible` you used isn't available in Zephyr. Perhaps you can add a new file at `zephyr/dts/bindings/gpio/awinic,aw9523b-gpio.yaml` with a similar content as in below:
> 
> The file has been added at just 6 hours before.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/gpio/awinic%2Caw9523b-gpio.yaml

Oh, really sorry. Thanks!

**Review by sylvioalves — DISMISSED** [review]

**Comment by soburi** [comment]
I rebased this to solve conflict.

**Review by nordicjm — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by soburi** [comment]
@sylvioalves 
Could you re-approve?

**Review by sylvioalves — APPROVED** [review]

**Pull request merged**
