### PR TITLE
Add missing properties for SPI node on Renesas RA8 devices

### PR DESCRIPTION
**Pull request by khoa-nguyen-18**
- Add missing `pinctrl-names` and `status` properties for the spi1 node in ek_ra8m1.dts to be able to test spi_loopback on ek_ra8m1
- Add condition in source driver to check for close before opening to prevent invalid pointer access

### CODE REVIEW

**Review by kartben — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Comment by khoa-nguyen-18** [comment]
@kartben @nordicjm Sorry for the inconvenience, we just added an improvement condition in the source code driver SPI to check whether it's closed or not. Can you guys please take a look?

**Review by nordicjm — COMMENTED** [review]
can you remove `bug: ` from the commit titles? We do not prefix bugs, they have the normal system prefix

**Comment by khoa-nguyen-18** [comment]
> can you remove `bug: ` from the commit titles? We do not prefix bugs, they have the normal system prefix

Thank you, I have removed it

**Review by nordicjm — APPROVED** [review]

**Review by soburi — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by khoa-nguyen-18** [comment]
Currently, CI is failing but not from our commits. We have rebased with the latest main and built the failed test locally, it seems the test is still not fixed.

**Review by duynguyenxa — APPROVED** [review]

**Review by thaoluonguw — APPROVED** [review]

**Pull request merged**
