### PR TITLE
tests: devicetree: device: fix multiple declarations

### LINKED ISSUE #32656: reel_board: tests/lib/devicetree/devices/ build failure
**Describe the bug**
tests/lib/devicetree/devices/ can't be built on reel board.

**To Reproduce**
1. west build -p auto -b reel_board tests/lib/devicetree/devices/
2. See error

**Expected behavior**
Testsuite should build successfully and pass.

**Logs and console output**
```
[0/1] Re-running CMake...
Including boilerplate (Zephyr base (cached)): /home/ztest/work/zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/ztest/work/zephyrproject/zephyr/tests/lib/devicetree/devices
-- Zephyr version: 2.5.99 (/home/ztest/work/zephyrproject/zephyr)
-- Found west (found suitable version "0.9.0", minimum required is "0.7.1")
-- Board: reel_board
-- Cache files will be written to: /home/ztest/.cache/zephyr
-- Using toolchain: zephyr 0.12.2 (/home/ztest/zephyr-sdk-0.12.2)
-- Found dtc: /home/ztest/zephyr-sdk-0.12.2/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/ztest/work/zephyrproject/zephyr/boards/arm/reel_board/reel_board.dts
-- Found devicetree overlay: /home/ztest/work/zephyrproject/zephyr/tests/lib/devicetree/devices/app.overlay
-- Generated zephyr.dts: /home/ztest/work/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/ztest/work/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: /home/ztest/work/zephyrproject/zephyr/build/zephyr/include/generated/device_extern.h
Parsing /home/ztest/work/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/ztest/work/zephyrproject/zephyr/build/zephyr/.config'
No change to configuration in '/home/ztest/work/zephyrproject/zephyr/build/zephyr/.config'
No change to Kconfig header in '/home/ztest/work/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ztest/work/zephyrproject/zephyr/build
[126/133] Linking C executable zephyr/zephyr_prebuilt.elf
FAILED: zephyr/zephyr_prebuilt.elf zephyr/zephyr_prebuilt.map
: && ccache /home/ztest/zephyr-sdk-0.12.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc   zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj -o zephyr/zephyr_prebuilt.elf  -Wl,-T  zephyr/linker.cmd  -Wl,-Map=/home/ztest/work/zephyrproject/zephyr/build/zephyr/zephyr_prebuilt.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/arm/core/aarch32/libarch__arm__core__aarch32.a  zephyr/arch/arch/arm/core/aarch32/cortex_m/libarch__arm__core__aarch32__cortex_m.a  zephyr/arch/arch/arm/core/aarch32/cortex_m/mpu/libarch__arm__core__aarch32__cortex_m__mpu.a  zephyr/lib/libc/minimal/liblib__libc__minimal.a  zephyr/lib/posix/liblib__posix.a  zephyr/soc/arm/common/cortex_m/libsoc__arm__common__cortex_m.a  zephyr/soc/arm/nordic_nrf/nrf52/libsoc__arm__nordic_nrf__nrf52.a  zephyr/boards/arm/reel_board/libboards__arm__reel_board.a  zephyr/subsys/testsuite/ztest/libsubsys__testsuite__ztest.a  zephyr/drivers/gpio/libdrivers__gpio.a  zephyr/drivers/i2c/libdrivers__i2c.a  zephyr/drivers/serial/libdrivers__serial.a  modules/hal_nordic/libmodules__hal_nordic.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  zephyr/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -L"/home/ztest/zephyr-sdk-0.12.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.2.0/thumb/v7e-m/nofp"  -L/home/ztest/work/zephyrproject/zephyr/build/zephyr  -lgcc  zephyr/arch/common/libisr_tables.a  -mcpu=cortex-m4  -mthumb  -mabi=aapcs  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -no-pie  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn && cd /home/ztest/work/zephyrproject/zephyr/build/zephyr && /usr/bin/cmake -E echo
/home/ztest/zephyr-sdk-0.12.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.2.0/../../../../arm-zephyr-eabi/bin/ld: zephyr/drivers/i2c/libdrivers__i2c.a(i2c_test.c.obj):/home/ztest/work/zephyrproject/zephyr/drivers/i2c/i2c_test.c:46: multiple definition of `__device_dts_ord_73'; app/libapp.a(main.c.obj):/home/ztest/work/zephyrproject/zephyr/tests/lib/devicetree/devices/src/main.c:35: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/ztest/work/zephyrproject/zephyr/build
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS
 - Toolchain zephyr-sdk-0.12.2
 - Zephyr 2.5 commit ID 5de3f850a752

### PR DESCRIPTION
**Pull request by pabigot**
The test defines driver instances for the devices in the tree, but there's now a dummy driver for `vnd,i2c` that would also attempt to define the same device on any platform that defaults `CONFIG_I2C=y`, resulting in multiply-defined symbol errors.

native_posix does not default `CONFIG_I2C=y` and because `CONFIG_I2C_TEST` is hidden there's no way to turn it on or off at the driver level, so disable the subsystem to mask the driver, leaving the test code as the only place the devices are defined.

Fixes  #32656

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by pabigot** [comment]
An alternative fix is to explicitly `CONFIG_I2C_TEST=n` in the test.

**Comment by galak** [comment]
> An alternative fix is to explicitly `CONFIG_I2C_TEST=n` in the test.

Hmm, maybe that makes more sense since as having the I2C controller device in the test seems to make sense.

**Comment by galak** [comment]
> Hmm, maybe that makes more sense since as having the I2C controller device in the test seems to make sense.

Oh, nevermind.. now as I understand what's going on either solution is fine.  Seems like removing `DEVICE_DT_DEFINE(TEST_I2C...` is a bit more interesting as it causes a little interplay with a driver doing that outside of the test itself.

**Comment by pabigot** [comment]
> Seems like removing `DEVICE_DT_DEFINE(TEST_I2C...` is a bit more interesting as it causes a little interplay with a driver doing that outside of the test itself.

Yes, that's why I slightly prefer this approach, but I'd like @mbolivar-nordic to chime in.

**Review by carlescufi — APPROVED** [review]

**Comment by nashif** [comment]
CI still failing, does this depend on something else?

**Comment by pabigot** [comment]
> CI still failing, does this depend on something else?

It's failing in a different way on a different target, so a third solution path had to be found.  Let's see if it's OK now.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
> Let's see if it's OK now.

CI is green; ready to merge

**Pull request merged**
