### PR TITLE
tests: subsys: fixed the samples/tracing code can not generate coverage

### LINKED ISSUE #38323: Can not generate code coverage report by running samples/subsys/tracing
I have a try to run test cases of samples/ directories, and I find that it works to run all test cases by the tool twister. But if I add the '-C' option, such as `twister -p qemu_x86 -T samples/subsys/tracing/  -C`, it will fail to run. And the error log is as below:

====================================================================

[ 90%] Built target drivers__timer
[ 91%] Building C object zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj
[ 92%] Linking C executable zephyr_prebuilt.elf
/home/zn/zephyr-sdk-0.13.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/10.3.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: kernel/libkernel.a(kheap.c.obj): in function `k_heap_init':
/home/zn/zephyrproject/zephyr/kernel/kheap.c:18: undefined reference to `sys_trace_k_heap_init'
/home/zn/zephyr-sdk-0.13.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/10.3.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: kernel/libkernel.a(kheap.c.obj): in function `k_heap_aligned_alloc':
/home/zn/zephyrproject/zephyr/kernel/kheap.c:71: undefined reference to `sys_trace_k_heap_aligned_alloc_enter'
/home/zn/zephyr-sdk-0.13.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/10.3.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: /home/zn/zephyrproject/zephyr/kernel/kheap.c:89: undefined reference to `sys_trace_k_heap_aligned_alloc_blocking'
/home/zn/zephyr-sdk-0.13.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/10.3.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: /home/zn/zephyrproject/zephyr/kernel/kheap.c:101: undefined reference to `sys_trace_k_heap_aligned_alloc_exit'
/home/zn/zephyr-sdk-0.13.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/10.3.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: kernel/libkernel.a(kheap.c.obj): in function `k_heap_alloc':
/home/zn/zephyrproject/zephyr/kernel/kheap.c:109: undefined reference to `sys_trace_k_heap_alloc_enter'
/home/zn/zephyr-sdk-0.13.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/10.3.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: /home/zn/zephyrproject/zephyr/kernel/kheap.c:113: undefined reference to `sys_trace_k_heap_alloc_exit'
/home/zn/zephyr-sdk-0.13.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/10.3.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: kernel/libkernel.a(kheap.c.obj): in function `k_heap_free':
/home/zn/zephyrproject/zephyr/kernel/kheap.c:124: undefined reference to `sys_trace_k_heap_free'
collect2: error: ld returned 1 exit status
zephyr/CMakeFiles/zephyr_prebuilt.dir/build.make:110: recipe for target 'zephyr/zephyr_prebuilt.elf' failed
make[2]: *** [zephyr/zephyr_prebuilt.elf] Error 1
CMakeFiles/Makefile2:2347: recipe for target 'zephyr/CMakeFiles/zephyr_prebuilt.dir/all' failed
make[1]: *** [zephyr/CMakeFiles/zephyr_prebuilt.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

=====================================================================

### PR DESCRIPTION
**Pull request by ghost**
Add some tracing functions to fix that the samples/tracing code 
cannot generate coverage by twister.

Fixed #38323

Signed-off-by: Lixin Guo <lixinx.guo@intel.com>

### CODE REVIEW

**Comment by LeiW000** [comment]
@LixinGuoX , please fix the coding compliance issue.

**Comment by LixinGuoX** [comment]
> @LixinGuoX , please fix the coding compliance issue.


> Add some APIs to fix the bug that can not generate
> code coverage.
> 
> Fixed #38323
> 
> Signed-off-by: Lixin Guo [lixinx.guo@intel.com](mailto:lixinx.guo@intel.com)



> @LixinGuoX , please fix the coding compliance issue.



> @LixinGuoX , please fix the coding compliance issue.

Coding compliance issue done , thanks.

**Comment by LixinGuoX** [comment]
> @LixinGuoX , please fix the coding compliance issue.



> @LixinGuoX , please fix the coding compliance issue.

Coding compliance issue fixed , thanks.

**Review by mengxianglinx — APPROVED** [review]

**Review by Zhaoningx — APPROVED** [review]
It works.

**Review by nashif — CHANGES_REQUESTED** [review]
bad commit title: "tests: subsys: Add some APIs to fix a bug"

please explain what you are fixing and do not be generic saying you are fixing a bug. This can be in the content of the commit

**Comment by LixinGuoX** [comment]
> bad commit title: "tests: subsys: Add some APIs to fix a bug"
> 
> please explain what you are fixing and do not be generic saying you are fixing a bug. This can be in the content of the commit

Hi , @nashif , I have modified the commit title and content , I will pay attention to such formatting issues in the future . Thanks .

**Review by nashif — APPROVED** [review]

**Pull request merged**
