### PR TITLE
syscall: Move arch specific syscall code into its own header

### PR DESCRIPTION
**Pull request by galak**
Split out the arch specific syscall code to reduce include pollution
from other arch related headers.  For example on ARM its possible to get
errno.h included via SoC specific headers.  Which created an interesting
compile issue because of the order of syscall & errno/errno syscall
inclusion.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@andrewboie can you take a look and see what you think.  Before I go fixup arc & x86, wanted to see that the direction was acceptable.

**Comment by MaureenHelm** [comment]
Thanks @galak. This fixes #9054

**Comment by galak** [comment]
> Thanks @galak. This fixes #9054

Ah, nice side effective, wasn't sure if it would help there or not.

**Comment by andrewboie** [comment]
Yeah this LGTM

**Review by tyrantlizard77 — APPROVED** [review]
Some ARC-related issues revealed by CI, probably just a missing include, otherwise LGTM

**Comment by galak** [comment]
> Some ARC-related issues revealed by CI, probably just a missing include, otherwise LGTM

Yeah, was being lazy and letting CI do a check for me.  Should hopefully now work on arc & x86.

**Pull request merged**
