### PR TITLE
CODEOWNERS: remove rsalveti

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This GitHub account has been disabled for over a year (it was replaced
by a `ricardosalveti` account). Remove from CODEOWNERS.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
I think maybe @idlethread could be removed also, but I am 100% sure about the stale rsalveti account. CC @mike-scott

**Review by nashif — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by idlethread** [comment]
> I think maybe @idlethread could be removed also, but I am 100% sure about the stale rsalveti account. CC @mike-scott

Hah :) I just pulled out my carbon for some hacking in the lock down. Can we postpone removal or is this affecting maintenance?

**Comment by galak** [comment]
> > I think maybe @idlethread could be removed also, but I am 100% sure about the stale rsalveti account. CC @mike-scott
> 
> Hah :) I just pulled out my carbon for some hacking in the lock down. Can we postpone removal or is this affecting maintenance?

I don't think the board support is being removed.  Just the fact that Ricardo isn't active in the Zephyr project.

**Comment by mbolivar-nordic** [comment]
> > I think maybe @idlethread could be removed also, but I am 100% sure about the stale rsalveti account. CC @mike-scott
> 
> Hah :) I just pulled out my carbon for some hacking in the lock down. Can we postpone removal or is this affecting maintenance?

Hey there! I was just trying to avoid unnecessary review requests getting sent your way to save you some spam. Never mind :)

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
> Hah :) I just pulled out my carbon for some hacking in the lock down. Can we postpone removal or is this affecting maintenance?

@idlethread I think that question is more about if you still feel as a codeowner for these files or not.

**Pull request merged**
