### PR TITLE
boards/xtensa/intel_s1000_crb: Add Intel assigned VID and PID for S1000 CRB

### PR DESCRIPTION
**Pull request by sathishkuttan**
Signed-off-by: Sathish Kuttan <sathish.k.kuttan@intel.com>

### CODE REVIEW

**Comment by sathishkuttan** [comment]
@nashif can you pl. review this?

**Comment by sathishkuttan** [comment]
@nashif 
Are the Title and Body referring to the commit message or the pull request?
What are UC3 and UC6 referring to?

**Comment by nashif** [comment]
> Are the Title and Body referring to the commit message or the pull request?

Commit message

> What are UC3 and UC6 referring to?

Those are just error codes

Your commit message should be:
```
boards: intel_s1000_crb: Assign Intel assigned VID for S1000 CRB

[Add more details here]

Signed-off-by: Sathish Kuttan <sathish.k.kuttan@intel.com>

```

**Comment by sathishkuttan** [comment]
@nashif
Thanks. Changed.

**Review by SavinayDharmappa — APPROVED** [review]
LGTM

**Comment by sathishkuttan** [comment]
@SavinayDharmappa 
Thanks

**Comment by nashif** [comment]
why did you close it? :)

**Comment by sathishkuttan** [comment]
@nashif 
newbie mistake? should I not be closing it?

**Pull request merged**
