### PR TITLE
arch: arm: cortex_r: Fix MPU_RASR_S_Msk

### PR DESCRIPTION
**Pull request by tolezk**
Fix typo to match specification.

### CODE REVIEW

**Review by stephanosio — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Comment by stephanosio** [comment]
@tolezk Please add `Signed-off-by: Anatol Ivanov <Anatoleech@mail.ru>` at the end of the commit message to fix the compliance check failure.

**Review by povergoing — DISMISSED** [review]

**Review by bbolen — DISMISSED** [review]

**Comment by tolezk** [comment]
> @tolezk Please add `Signed-off-by: Anatol Ivanov <Anatoleech@mail.ru>` at the end of the commit message to fix the compliance check failure.

Done.

**Review by microbuilder — DISMISSED** [review]

**Comment by tolezk** [comment]
Sorry for review dismiss, didn't expect that.

**Comment by stephanosio** [comment]
> Sorry for review dismiss, didn't expect that.

no worries, reviews are automatically dismissed when new changes are pushed.

**Review by stephanosio — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]

**Review by bbolen — APPROVED** [review]

**Review by povergoing — APPROVED** [review]

**Pull request merged**
