### PR TITLE
modules: tf-m: Disable initial attestation service

### LINKED ISSUE #54017: Modules: TF-M: Resolve QCBOR issues with TF-M 1.7.0
## Origin

TF-M requires access to https://github.com/laurencelundblade/QCBOR.git to build.

TF-M relies on [QCBOR](https://github.com/laurencelundblade/QCBOR.git) for CBOR and COSE functionality, and currently downloads QCBOR during builds, which is incompatible with Zephyr project policies. We require a local fork of this repo under `zephyrproject-rtos` to comply with these build requirements, or an alternate solution to solve this problem.

UPDATE: It has also been pointed out the QCBOR does not have an OSI-compliant license, requiring a license exception from the TSC and board, or the removal of any code that makes use of QCBOR in default Zephyr builds.

> Note that QCBOR is really a **COSE LIBRARY**, adding encryption and signing support on top of CBOR, and as such is functionally different than zcbor as it exists today.

> **NOTE**: This repo will NOT be used directly by Zephyr, and is only required by TF-M during the managed secure firmware build process, to prevent downloading the build requirement at compile time.

## Possible Solutions

To prevent downloads and comply with project policy, one of the following needs to happen:

1. Add QCBOR to `west.yml` under `zephyrproject-rtos` as a fork
2. Add QCBOR to `west.yml` pointing to the **upstream** module (outside `zephyrproject-rtos`) 
3. Setup QCBOR as a **submodule** (see [git-submodules-in-projects](https://docs.zephyrproject.org/latest/develop/west/manifest.html#git-submodules-in-projects))
  - NOTE: The submodule approach would require two instances of QCBOR as a sub-module, since the following repos make use of it:
    - [zephyrproject-rtos/trusted-firmware-m](https://github.com/zephyrproject-rtos/trusted-firmware-m)
    - [zephyrproject-rtos/tf-m-tests](https://github.com/zephyrproject-rtos/tf-m-tests)
4. Propose a change upstream to TF-M to include QCBOR source in `lib/ext/qcbor` (they already do this for `t_cose`), but this is unlikely to pass since they recently pulled it out: https://github.com/joerchan/sdk-trusted-firmware-m/commit/8836b2229a36fe6eb23d889bbf146d1fe6226c86
5. Re-commit QCBOR files in the Zephyr fork via `git subtree`, maintaining this on top of every update until an acceptable upstream solution is found
6. Other?

## Maintainership (assuming new repo)

@microbuilder, @joerchan

## Revision

Version or SHA you would like to integrate initially

`b0e7033268e88c9f27146fa9a1415ef4c19ebaff`

## License

`BSD-3-Clause`

### PR DESCRIPTION
**Pull request by microbuilder**
Includes changes to the TF-M integration in Zephyr to prevent TF-M from building the initial attestation secure service and related tests, which have a dependency on QCBOR, which is being downloaded at compile time, and also has a non-OSI license.

If either of these flags are enabled at build time:

- `CONFIG_TFM_PARTITION_INITIAL_ATTESTATION`
- `CONFIG_TFM_PSA_TEST_INITIAL_ATTESTATION`

A fatal error will be thrown, with a description of the reason.

`CONFIG_TFM_PARTITION_INITIAL_ATTESTATION` has been set to `n` by default (previously `y`), and relevant test suites have been disabled for the initial attestation secure service.

A new config flag, `CONFIG_TFM_QCBOR_PATH`, has been added where you can optionally indicate the location of the QCBOR library, or set the value to `DOWNLOAD` to download the library at compile time, which allows for the two attestation flags above to be set if the license terms of QCBOR are acceptable in your application.

fixes: https://github.com/zephyrproject-rtos/zephyr/issues/54017

### CODE REVIEW

**Comment by microbuilder** [comment]
@joerchan The fatal error check should likely have an exception added if `QCBOR_PATH` is set to a valid path, meaning that the end user has already downloaded QCBOR, and is OK with the non-OSI license, at which point they can use initial attestation service as is.

**Review by joerchan — DISMISSED** [review]

**Review by stephanosio — DISMISSED** [review]
On a surface level, looks ok to me.

**Comment by microbuilder** [comment]
Added a DNM label pending some further documentation reviews with @joerchan since this can still go in Monday as a release blocker.

**Comment by joerchan** [comment]
> Added a DNM label pending some further documentation reviews with @joerchan since this can still go in Monday as a release blocker.

Pushed the change. QCBOR can be be used by overriding a configuration and pointing to their own checkout of QCBOR or  allowing the TF-M download mechanism.

**Review by joerchan — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
Merging this into RC3 so we can get more testing on this before the release. Release notes can be added in a follow-up PR.

**Comment by microbuilder** [comment]
> Merging this into RC3 so we can get more testing on this before the release. Release notes can be added in a follow-up PR.

I was going to mention it in a general release note PR next week for all the changes in Aarch32 and TF-M.

**Pull request merged**
