### PR TITLE
tests: remove unused harness config

### LINKED ISSUE #45848: tests: console harness: inaccuracy testcases report
**Describe the bug**
Tests supporting console harness have some problem in testing reporting, even the test suite has passed, we can not collecting the status of single testcases, they are showing `null `or `unknown`. 
All of the failing testcases are written in ztest framwork, like `coredump.backends.logging` and `logging.log_syst.mipi_syst`

Also, we should not add the test_suite as testcase to report if it is written in ztest.

**To Reproduce**
1. twister -p qemu-x86 -T tests/subsys/logging/log_syst/
2. see twister.json or twister_report.xml

**Expected behavior**
We should have the same result in twister.log and twister.json(xml).

**Impact**
The number of failure testcases increase in the test report.

**Logs and console output**
```
        {
            "name":"tests/subsys/logging/log_syst/logging.log_syst.mipi_syst",
            "arch":"x86",
            "platform":"qemu_x86",
            "run_id":"82f5091e5a945b7553fc8b98ecddfecd",
            "runnable":true,
            "status":"passed",
            "execution_time":"2.09",
            "testcases":[
                {
                    "identifier":"logging.log_syst.mipi_syst.log_syst_data",
                    "execution_time":"0.00",
                    "status":null
                },
                {
                    "identifier":"logging.log_syst.mipi_syst.log_syst_float_data",
                    "execution_time":"0.00",
                    "status":null
                },
                {
                    "identifier":"logging.log_syst.mipi_syst.log_syst_data_multiple_args",
                    "execution_time":"0.00",
                    "status":null
                },
                {
                    "identifier":"logging.log_syst.mipi_syst.log_syst_format_table_selection",
                    "execution_time":"0.00",
                    "status":null
                },
                {
                    "identifier":"logging.log_syst.mipi_syst",
                    "execution_time":"0.00",
                    "status":"passed"
                }
            ]
        },
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain 0.14.1
 - Commit d781945

### PR DESCRIPTION
**Pull request by ghost**
logging.log_syst.mipi_syst is written in ztest framework, now it has
a good method to test automatically, no need to configure the harness
as console any more, so remove it.

Fixes #45848 
Signed-off-by: Guo Lixin <lixinx.guo@intel.com>

### CODE REVIEW

**Review by hakehuang — DISMISSED** [review]

**Comment by LixinGuoX** [comment]
> why not configure the harness to use test directly in yaml file if a test was written in ztest framework? i.e. for the test logging.log_syst.mipi_syst you mentioned in issue, this test was used to verify the sys-t format and now all things were done by log buffer memory comparison automatically, we don't need to configure the harness as console and judge the result manually any more, we did this before because we didn't find a good method to verify sys-t format automatically, but now it did, so we should configure the harness as test, rather than console.

Yes, thank you for the comment, I have pushed another version, trying to configure the harness as test if it has ztest_suite_names, because most tests do not configure the harness to use test directly in yaml file. Could you please re-review, thank you.

**Review by enjiamai — DISMISSED** [review]

**Review by chen-png — DISMISSED** [review]

**Review by dcpleung — CHANGES_REQUESTED** [review]
The console harness is there to make sure we are getting the output we want to see on the coredump_backends test. So do not remove it until you have some other ways of verifying those outputs.

**Comment by LixinGuoX** [comment]
> The console harness is there to make sure we are getting the output we want to see on the coredump_backends test. So do not remove it until you have some other ways of verifying those outputs.

Yes, you are right, this test needs console harness to verify the output, have added them back, also will figure out a better way to handle this ztest+console circumstance.

**Review by enjiamai — DISMISSED** [review]

**Review by dcpleung — DISMISSED** [review]

**Review by chen-png — DISMISSED** [review]

**Comment by enjiamai** [comment]
Hi @LixinGuoX , thanks for the fix. One of my personal suggestion is to split them into 2 PRs, one is for logging testcase and one is for twister harness.

**Comment by LixinGuoX** [comment]
Sure, will do it as suggested, thanks.

**Review by enjiamai — APPROVED** [review]

**Comment by hakehuang** [comment]
@LixinGuoX need fix the CI failure.

**Review by smrtos — APPROVED** [review]

**Review by chen-png — DISMISSED** [review]

**Review by smrtos — DISMISSED** [review]

**Review by enjiamai — DISMISSED** [review]

**Comment by LixinGuoX** [comment]
No code change, just rebase.

**Review by chen-png — APPROVED** [review]

**Review by enjiamai — APPROVED** [review]

**Review by gopiotr — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by yerabolu — APPROVED** [review]

**Pull request merged**
