### PR TITLE
Remove static analyzer warnings about binary bitwise operator used with signed integer in LOG_XYZ macros.

### PR DESCRIPTION
**Pull request by r2r0**
clang-tidy complains: "warning: use of a signed integer operand with a binary bitwise operator"
```
LOG_ERR("Index is out of bounds");
        ^
/path/zephyr/include/logging/log.h:40:25: note: expanded from macro 'LOG_ERR'
#define LOG_ERR(...)    Z_LOG(LOG_LEVEL_ERR, __VA_ARGS__)
                        ^
/path/zephyr/include/logging/log_core.h:287:2: note: expanded from macro 'Z_LOG'
        __LOG(_level,                                  \
        ^
/path/zephyr/include/logging/log_core.h:259:19: note: expanded from macro '__LOG'
                                   (_level <= LOG_RUNTIME_FILTER(_filter))) {  \
                                              ^
/path/zephyr/include/logging/log_core.h:397:2: note: expanded from macro 'LOG_RUNTIME_FILTER'
        LOG_FILTER_SLOT_GET(&(_filter)->filters, LOG_FILTER_AGGR_SLOT_IDX)
        ^
/path/zephyr/include/logging/log_core.h:378:4: note: expanded from macro 'LOG_FILTER_SLOT_GET'
        ((*(_filters) >> LOG_FILTER_SLOT_SHIFT(_id)) & LOG_FILTER_SLOT_MASK)
          ^
```

### CODE REVIEW

**Comment by nashif** [comment]
How did you run clang-tidy?

**Comment by r2r0** [comment]
@nashif 
CLANG_TIDY_PROGRAM set to clang-tidy-10
CMAKE_SOURCE_DIR is set to my application base folder.

```
add_custom_target(clang-tidy ${CLANG_TIDY_PROGRAM}
                  -checks=-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,hicpp-*,modernize-*,readability-*,-modernize-use-trailing-return-type,-hicpp-noexcept-move
                  -p ${CMAKE_CURRENT_BINARY_DIR}
                  -header-filter='${CMAKE_SOURCE_DIR}/src/.*'
                  --quiet
                  ${CLANG_TIDY_APP_SOURCES} 2>&1 > clang-tidy-analysis.txt
                  COMMENT "Run clang-tidy on the firmware")

```

**Review by nordic-krch — APPROVED** [review]

**Review by nordic-krch — CHANGES_REQUESTED** [review]
CI is failing because of `Z_LOG_RESOLVED_LEVEL` and `Z_LOG_EVAL` macros which are using concatenation trick to figure out if log level is set.

You need to add there U-version of log levels. Something like:
```
#define _LOG_ZZZZ1 _LOG_YYYY,
#define _LOG_ZZZZ1U _LOG_YYYY, <----
#define _LOG_ZZZZ2 _LOG_YYYY,
#define _LOG_ZZZZ2U _LOG_YYYY,  <----
#define _LOG_ZZZZ3 _LOG_YYYY,
#define _LOG_ZZZZ3U _LOG_YYYY, <----
#define _LOG_ZZZZ4 _LOG_YYYY,
#define _LOG_ZZZZ4U _LOG_YYYY, <----
```

Note that log level values coming from Kconfig will be without U thus both ways are needed.

**Comment by r2r0** [comment]
Problem with Z_LOG_RESOLVED_LEVEL and Z_LOG_EVAL should be fixed now.

**Review by nordic-krch — APPROVED** [review]

**Pull request merged**
