### PR TITLE
ext: hal: make openisa HAL a zephyr module

### PR DESCRIPTION
**Pull request by nashif**
Maintain this HAL in its own repo:
git@github.com:zephyrproject-rtos/hal_openisa.git

and manage using west.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by mbolivar — APPROVED** [review]
west.yml change is OK

**Review by ioannisg — APPROVED** [review]

**Comment by galak** [comment]
Looks like we need:

```
diff --git a/soc/riscv/openisa_rv32m1/soc.h b/soc/riscv/openisa_rv32m1/soc.h
index 50b9023add..f5a299acbc 100644
--- a/soc/riscv/openisa_rv32m1/soc.h
+++ b/soc/riscv/openisa_rv32m1/soc.h
@@ -9,7 +9,7 @@
 
 #ifndef _ASMLANGUAGE
 
-#include "fsl_device_registers.h"
+#include <fsl_device_registers.h>
 #include <zephyr/types.h>

```

**Comment by nashif** [comment]
@galak looking at this issue, I cant reproduce it locally for some reason. Will spend some time on it today.

**Comment by galak** [comment]
> @galak looking at this issue, I cant reproduce it locally for some reason. Will spend some time on it today.

I pushed a fix into the PR.

**Comment by nashif** [comment]
> I pushed a fix into the PR.

the real issue was in the module repo, I forgot to check-in one file, thats why it was working locally for me. :(

**Pull request merged**
