### PR TITLE
maintainers: set henrikbrixandersen as canbus maintainer

### PR DESCRIPTION
**Pull request by alexanderwachter**
Set henrikbrixandersen as the new maintainer of canbus

Signed-off-by: Alexander Wachter <alexander@wachter.cloud>

### CODE REVIEW

**Comment by carlescufi** [comment]
Thank you @alexanderwachter for all the hard work on CAN!

**Review by carlescufi — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]
No objections.

Thanks to both of you for your great work! @henrikbrixandersen for the many recent enhancements and @alexanderwachter for maintaining and driving the CAN bus part of Zephyr for several years.

**Comment by henrikbrixandersen** [comment]
Thank you for all your efforts so far, Alex :)

**Review by gmarull — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by alexanderwachter** [comment]
No worries. I'll still be active as much as possible.
Just handing over to someone who is more active now (and has more time).
The thing is that I'm not using CAN in my professional career (but Zephyr :-)) and all the time for maintaining was taken from my spare time. Brix noticed that and offered to take over.
When I introduced CAN in Zephyr, I did to promote 6LoCAN which was removed recently, I had plenty of time.
Now since I'm working full time I focus more on having some time without my computer in front.

**Review by dleach02 — DISMISSED** [review]
Thank you @alexanderwachter for your contributions and thankyou @henrikbrixandersen for stepping up!

**Comment by henrikbrixandersen** [comment]
@alexanderwachter You need to fix the CI compliance issue regarding the author email in order for this to be merged.

**Comment by alexanderwachter** [comment]
@henrikbrixandersen need to do that on my own pc tomorrow

**Comment by alexanderwachter** [comment]
Fixed compliance check.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
