### PR TITLE
Bluetooth: host: ifdef sc_reset on CONFIG_BT_GATT_SERVICE_CHANGED

### PR DESCRIPTION
**Pull request by SebastianBoe**
Only define sc_reset when CONFIG_BT_GATT_SERVICE_CHANGED is
defined. Otherwise we get an unused function warning.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
```
[134/226] Building C object zephyr/subsys/bluetooth/host/CMakeFiles/subsys__bluetooth__host.dir/gatt.c.obj
/home/sebo/ncs/zephyr/subsys/bluetooth/host/gatt.c:371:13: warning: 'sc_reset' defined but not used [-Wunused-function]
  371 | static void sc_reset(struct gatt_sc_cfg *cfg)
      |             ^~~~~~~~

```

I was surprised to see gcc be so strict.

**Comment by jhedberg** [comment]
Are you sure there isn’t a missing `if (IS_ENABLED(CONFIG_BT_GATT_SERVICE_CHANGED))` somewhere instead? That would be preferred over adding ifdefs like this (in fact, adding ifdefs effectively prevents calling code from using `IS_ENABLED()`).

**Comment by jhedberg** [comment]
Or to put it another way, sounds like some calling code is using ifdefs instead of IS_ENABLED(). I realize it’s not always feasible or practical to avoid ifdefs, but this should be first checked before such changes. Once you start using ifdefs it tends to spread everywhere and completely eliminate the possibility of IS_ENABLED().

**Comment by SebastianBoe** [comment]
I saw that there was a possibility to use IS_ENABLED, but I was not aware that was the best-practice. Will re-write to use IS_ENABLED.

**Comment by jhedberg** [comment]
> I saw that there was a possibility to use IS_ENABLED, but I was not aware that was the best-practice. Will re-write to use IS_ENABLED.

There's been talk of formulating these practices and their justifications to some document, but I don't think anyone got around to it. The main benefits of IS_ENABLED() (as I see them) are:
 
 - You (as a human) only need to parse one language (C, not the pre-processor), so reading it becomes easier
 - All branches are always exposed to the compiler, and so you get basic validation (e.g. of the syntax) by the compiler for all code regardless of what Kconfig options have been selected.

**Comment by SebastianBoe** [comment]
I agree with the policy, I guess I just assumed that the original ifdef was ifdef'ing for a good reason.

But I see that I don't get any undefined reference issues with IS_ENABLED so evidently no good reason to use ifdef there :)

The feedback has been addressed, please re-assess your review :)

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
