### PR TITLE
Merge build assert macros

### PR DESCRIPTION
**Pull request by ozhuraki**
In order to de-duplicate 2 macros with the same use,
one of which is discouraged/deprecated, merge
BUILD_ASSERT(), BUILD_ASSERT_MSG() into one macro
and drop BUILD_ASSERT_MSG().

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
LGTM, no objections

**Review by henrikbrixandersen — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
fine with this

**Review by jhedberg — APPROVED** [review]

**Comment by ozhuraki** [comment]
There's a dependency on hal_nordic. The PR against hal_nordic is here:

https://github.com/zephyrproject-rtos/hal_nordic/pull/29

**Comment by joerchan** [comment]
@ozhuraki You should update the west.yml to include this pr, use pull/29/head as the version so that CI can run properly with up to date changes.

**Comment by ozhuraki** [comment]
@joerchan 

OK, thanks a lot for the help! Done.

**Review by dcpleung — APPROVED** [review]

**Comment by andrewboie** [comment]
Patch LGTM.
It might be better to leave the BUILD_ASSERT_MSG() macros in-place for one release and tag them with DEPRECATED_MACRO, but I don't feel strongly about this.

**Comment by ozhuraki** [comment]
@andrewboie

> It might be better to leave the BUILD_ASSERT_MSG() macros in-place for one release and tag them with DEPRECATED_MACRO, but I don't feel strongly about this.

Thanks and sure, this is probably the best approach here. Done.

**Comment by ozhuraki** [comment]
@andrewboie @nashif @utzig 

There are changes in mcuboot since v1.5.0 (the compilation fails on mcuboot using newer tinycbor), so the approach with pointing west to the pull request doesn’t work.

This PR will need to wait until this could be resolved in some way.

The alternative is to temporary drop __DEPRECATED from the BUILD_ASSERT_MSG() and lift it when the changes from mcuboot propagate.

**Comment by utzig** [comment]
> There are changes in mcuboot since v1.5.0 (the compilation fails on mcuboot using newer tinycbor), so the approach with pointing west to the pull request doesn’t work.

I suppose you're referrring to https://github.com/JuulLabs-OSS/mcuboot/pull/633 and https://github.com/zephyrproject-rtos/mcuboot/commit/470e2f3d5bdcb1892d76a534a745186fd8ff5aab; `west` is currently using `v1.5.0` and it should be updated for a version after those `tinycbor` changes were merged, is that correct?

**Comment by nvlsianpu** [comment]
@utzig, all ^^ Required patch is the part of some bigger efforts, see
https://github.com/zephyrproject-rtos/zephyr/pull/21825

**Comment by ozhuraki** [comment]
@utzig 

> zephyrproject-rtos/mcuboot@470e2f3; west is currently using v1.5.0 and it should be updated for a version after those tinycbor changes were merged, is that correct?

I am not quite sure. When I pointed the CI to my patch on top of zephyrproject-rtos/mcuboot master, the compilation failed on tinycbor. Could you please take a look?

**Comment by nvlsianpu** [comment]
@ozhuraki Pleas follow below steps:

step 1. please point https://github.com/JuulLabs-OSS/mcuboot/pull/682 in manifest update here
step 2. one CI pass we can merge mcuboot PR (i will upgrade zephyr's mcuboot intermediately. 
step 3. update manifest patch here to the mcuboot head SHA 
step 4. merge the PR

@nashif Is DNM still relevant?

cc @carlescufi

**Comment by ozhuraki** [comment]
@nvlsianpu 

> step 1. please point JuulLabs-OSS/mcuboot#682 in manifest update here

Thanks and done. However, a few failures:

https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/65967/5/console

Could you please take a look if it's mcuboot related, or we should retry a bit later?

**Comment by utzig** [comment]
> https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/65967/5/console
> 
> Could you please take a look if it's mcuboot related, or we should retry a bit later?

```
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/ieee802154/ieee802154_nrf5.c: In function 'nrf5_rx_thread':
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/ieee802154/ieee802154_nrf5.c:125:4: error: implicit declaration of function 'log_stack_usage' [-Werror=implicit-function-declaration]
  125 |    log_stack_usage(&nrf5_radio->rx_thread);
      |    ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

This looks completely unrelated to mcuboot.

**Comment by nvlsianpu** [comment]
@ozhuraki ^^ looks like something inherited from the master  - can you rebase?

**Comment by ozhuraki** [comment]
@utzig @nvlsianpu 

>This looks completely unrelated to mcuboot.

Looks unrelated to me too.

> looks like something inherited from the master - can you rebase?

Doesn't look like a random failure, but sure let's retry.

**Comment by ozhuraki** [comment]
@utzig @nvlsianpu

I had a look into CI failures and don't see a clear reason.

To sort out that these problems are manifest related:

- Dropped commits with manifest changes of hal_nordic, mcuboot
- Dropped deprecated from BUILD_ASSERT_MSG()

**Comment by ozhuraki** [comment]
@utzig @nvlsianpu

OK, disregard the previous message.

I could reproduce that warning on implicit declaration of log_stack_usage() and added a patch to fix that.

**Comment by nvlsianpu** [comment]
@andrewboie ^^

**Comment by ozhuraki** [comment]
@utzig @nvlsianpu @anangl @nashif 

> step 1. please point JuulLabs-OSS/mcuboot#682 in manifest update here
step 2. one CI pass we can merge mcuboot PR (i will upgrade zephyr's mcuboot intermediately.
step 3. update manifest patch here to the mcuboot head SHA
step 4. merge the PR

OK, CI passes.

If there's still an interest, let's proceed:

1. Upgrade mcuboot https://github.com/JuulLabs-OSS/mcuboot/pull/682
2. Upgrade hal_nordic https://github.com/zephyrproject-rtos/hal_nordic/pull/29
3. I could then drop the manifest changes in this PR.

**Comment by carlescufi** [comment]
@ozhuraki my apologies, I merged this by mistake. I have reverted it in #23608. Would you mind opening a new PR?

**Comment by ozhuraki** [comment]
@carlescufi

OK, will make a new one.

**Pull request merged**
