### PR TITLE
boards: arm: update actinius_icarus board definitions

### PR DESCRIPTION
**Pull request by alextsam**
This PR updates the flash partitions of the actinius_icarus ~~as per  #25874 (but *not* taking into account #22228 since that's not merged yet)~~ for compatibility with the SPU, adds aliases for feather and arduino compatibility, adds a vbatt node for the voltage divider (similar to the nordic thingy), plus a number of minor modifications/improvements.

Signed-off-by: Alex Tsamakos <alex@actinius.com>

### CODE REVIEW

**Comment by alextsam** [comment]
@ioannisg I may be wrong, but wouldn't normally reviewer auto-assignment kick-in when creating the PR? Is there something I can do at this moment? Thank you!

**Comment by ioannisg** [comment]
You are right, see #28187

**Comment by alextsam** [comment]
> You are right, see #28187

Thanks!

**Comment by alextsam** [comment]
Would it be possible perhaps for this update to make it into v2.4.0 still?

**Comment by alextsam** [comment]
@MaureenHelm @galak would it be possible to have this reviewed please? Sorry for bumping this again, but there might still be a chance for this to make it into the next nRF Connect release I think. Thank you

**Review by MaureenHelm — COMMENTED** [review]
Could you please reduce the size of the file `Icarus_front.png`?

**Comment by alextsam** [comment]
> Could you please reduce the size of the file `Icarus_front.png`?

Sure thing; I just pushed the updated one.
Thank you.

**Review by MaureenHelm — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
