### PR TITLE
Bluetooth: Mesh: Fix re-initializing provisioning state upon reset

### LINKED ISSUE #14928: Bluetooth: Mesh: Provisioning state doesn't always get properly re-initialized when doing reset
If both PB-ADV and PB-GATT are supported and the node is reset after provisioning, there are several parts of the provisioning state that do not get correctly re-initialized and result in the following fault:
```
***** USAGE FAULT *****
  Illegal use of the EPSR
***** Hardware exception *****
Current thread ID = 0x20001f10
Faulting instruction address = 0x0
Fatal fault in thread 0x20001f10! Aborting.
```

### PR DESCRIPTION
**Pull request by jhedberg**
If both PB-ADV and PB-GATT are supported, we need to properly
re-initialize variables such as link.rx.prev_id and (particularly
importantly) link.rx.buf. If we don't do this it may lead to the
following fault when trying to reprovision again:

***** USAGE FAULT *****
  Illegal use of the EPSR
***** Hardware exception *****
Current thread ID = 0x20001f10
Faulting instruction address = 0x0
Fatal fault in thread 0x20001f10! Aborting.

Fixes #14928

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
@bgix FYI

**Review by carlescufi — APPROVED** [review]

**Comment by jhedberg** [comment]
Added DNM flag for a while - it seems there might be a cleaner/more proper way to fix the issue (even though this patch does also fix the issue)

**Comment by jhedberg** [comment]
Ok, so this morphed into something slightly more complex, with a few simple cleanups along the way. I've tested this against both ADV and GATT based provisioning in various different combinations now, so I'm still comfortable with this going in for 1.14.

**Review by carlescufi — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM

**Pull request merged**
