### PR TITLE
twister: add trace print in exception

### PR DESCRIPTION
**Pull request by hakehuang**
add trace print when exception happens

### CODE REVIEW

**Comment by hakehuang** [comment]
pre discussion in https://github.com/zephyrproject-rtos/zephyr/pull/80623

**Comment by hakehuang** [comment]
@nashif , @gchwier , @golowanow , @PerMac , @LukaszMrugala , @KamilxPaszkiet please review this.

**Review by golowanow — COMMENTED** [review]
I think this PR should clarify its commit description as it logs traces for `TwisterException` objects only.

.. and the stack trace output will be duplicated for ~all~ other Twister exceptions, but `StatusAttributeError` with their handlers.

**Review by golowanow — APPROVED** [review]

**Comment by hakehuang** [comment]
@nashif @gchwier @PerMac @LukaszMrugala  can you help to review. Thanks.

**Review by gchwier — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
