### PR TITLE
drivers: flash: nrf: Add warning about small writes

### PR DESCRIPTION
**Pull request by d3zd3z**
This driver has an option SOC_FLASH_NRF_EMULATE_ONE_BYTE_WRITE_ACCESS
that emulates small writes by erasing and rewriting data.  Add a note
to the Kconfig for this option to make is clear that this makes the
flash driver susceptible to significant data loss in the event of
untimely reset or power loss.

Signed-off-by: David Brown <david.brown@linaro.org>

### CODE REVIEW

**Comment by d3zd3z** [comment]
@adamkondraciuk, who added the feature.

**Comment by nvlsianpu** [comment]
@d3zd3z 
I think this might only disrupt bytes which have been written.
Or such operation might disrupt whole 32-bit word where a byte belongs?

**Comment by d3zd3z** [comment]
> I believe it can disrupt the entire 512-byte page the write is done in.

This feature cannot be used safely if you care about the contents of flash. I still argue this feature shouldn't even be present in our driver. If something needs to be able to handle sub writes (such as the shell), it should be implemented there. It is never useful to do this in a real application.

**Comment by d3zd3z** [comment]
I don't know why this needs to keep being said. Flash memory is fairly complex to use correctly. It is important that the driver be as transparent as possible so that an application using flash can be aware of this complexity, and manage it properly. Driver operations that try to hide this complexity will only result in catastrophic data loss by users of the flash.

**Comment by nvlsianpu** [comment]
> I don't know why this needs to keep being said. Flash memory is fairly complex to use correctly. It is important that the driver be as transparent as possible so that an application using flash can be aware of this complexity, and manage it properly. Driver operations that try to hide this complexity will only result in catastrophic data loss by users of the flash.

Option is disabled by default. It is here by reason of ensure backward compatibility - initially the driver supports one-byte-write without any change to disable it.
https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/releases/release-notes-2.2.rst 
 stands:
>nRF flash driver
The nRF Flash driver has changed its default write block size to 32-bit aligned. Previous emulation of 8-bit write block size can be selected using the CONFIG_SOC_FLASH_NRF_EMULATE_ONE_BYTE_WRITE_ACCESS Kconfig option. Usage of 8-bit write block size emulation is only recommended for compatibility with older storage contents.

So fare i encountered a few commercial zephyr user which need this option. So we can't remove it, but rather state that it is not recommended.

> I believe it can disrupt the entire 512-byte page the write is done in.

I will consult this with Nordic HW engineers. On register level writing a byte is realized by writing a 32-bit word. I don,t see any reason why issue mentioned above is not an issue for regular 32-bit write

**Comment by d3zd3z** [comment]
>  On register level writing a byte is realized by writing a 32-bit word. I don,t see any reason why issue mentioned above is not an issue for regular 32-bit write

Every flash device has an inherent write size, which is the minimum amount of data that can be written at a time, and a minimum erase size, which is the minimum amount of data that can be erased. The details of what it means if you try to do less depends a little bit on the device hardware. For example, most modern flash devices don't let you write again to a given 32-bit value. This means you would have to erase the data in a much larger region before being able to write to it. Other devices will just experience excessive wear.

I guess we need to find out what the case is here. I was assuming this feature worked around an inability to write smaller units by reading, erasing, and rewriting. This case is the one that can easily result in catastrophic data loss. If it is just doing multiple writes to the same 32-bit word, then there is less need for a strong warning.

**Comment by d3zd3z** [comment]
@nvlsianpu Did you hear anything back from the HW engineers on the consequences of this emulation?

**Comment by nvlsianpu** [comment]
@d3zd3z Confirmed that feature doesn't allow to touch any other bytes that it try to modify.
PR should be closed then.

**Pull request closed without merging**
