### PR TITLE
drivers: misc: ethos_u: fix irq connect

### PR DESCRIPTION
**Pull request by XenuIsWatching**
The Ethos-U driver was using IRQ_DIRECT_CONNECT. This is not what the
driver needs as this will not detect a context switch when coming out
of the isr if it was idle, and this is needed as the isr will release a semaphore.

A file just named `init.c` is not that descriptive inside of a project
that has a lot of files of already. Rename to `ethos_u.c`.

Signed-off-by: Ryan McClelland <ryanmcclelland@meta.com>

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@kristofer-jonsson-arm please take a look

**Comment by kristofer-jonsson-arm** [comment]
First of all thanks for finding this, and sorry for missing your first cc. I'll talk to Jonny and ask him to review both patches you have uploaded.

**Comment by XenuIsWatching** [comment]
> Thanks for finding and fixing this. I must admit I haven't had time to get into the nitty gritty details of Zephyr yet. The semaphore functions are marked as being "isr ok", if you could you give some more background on the specific problem that would be much appreciated (if so just for future reference).
> 
> File rename looks OK to me.
> 
> Otherwise the only thing missing would be a new Copyright line.
> 
> Thanks again!

The main thing that was missing was the cpu wasn't not checking for a context switch when coming out of idle to an isr. The reason why it was "sometimes" working, was because by chance another isr would wake it up again (such as a uart or systick) and then it would check the state of the context and see that the thread was pending the whole time.

You can see the assembly code that gets inserted around an isr here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/arm/core/cortex_m/isr_wrapper.S
Documentation on the direct and regular isr can be found here:
https://docs.zephyrproject.org/latest/kernel/services/interrupts.html#implementation

If all looks good, please approve....... but now looking at the reviewers, it looks like I can not add you the reviewers :( as you are not a member of the project. I'll see if I'm able to ping some people

**Review by dkalowsk — APPROVED** [review]
Looks okay to me.  I don't' have an ethos to test with though

**Comment by jonny-svaerd-arm** [comment]
> > Thanks for finding and fixing this. I must admit I haven't had time to get into the nitty gritty details of Zephyr yet. The semaphore functions are marked as being "isr ok", if you could you give some more background on the specific problem that would be much appreciated (if so just for future reference).
> > File rename looks OK to me.
> > Otherwise the only thing missing would be a new Copyright line.
> > Thanks again!
> 
> The main thing that was missing was the cpu wasn't not checking for a context switch when coming out of idle to an isr. The reason why it was "sometimes" working, was because by chance another isr would wake it up again (such as a uart or systick) and then it would check the state of the context and see that the thread was pending the whole time.
> 
> You can see the assembly code that gets inserted around an isr here: https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/arm/core/cortex_m/isr_wrapper.S Documentation on the direct and regular isr can be found here: https://docs.zephyrproject.org/latest/kernel/services/interrupts.html#implementation
> 
> If all looks good, please approve....... but now looking at the reviewers, it looks like I can not add you the reviewers :( as you are not a member of the project. I'll see if I'm able to ping some people

Thanks, that makes sense. Patches look good to me too.

**Review by aasinclair — APPROVED** [review]

**Pull request merged**
