### PR TITLE
BLE fixes for 1.13.1

### PR DESCRIPTION
**Pull request by sjanc**
Those are proposed patches to be included in 1.13.1.
This contains qualification required fixes, size reduction features, few crashes and IOP fixes.

### CODE REVIEW

**Comment by sjanc** [comment]
unfortunately yes, but some of them are due prerequisite for fixes (to avoid conflicts) or regressions introduced by original fixes (and I didn't squashed those)

**Comment by kolodgrz** [comment]
@sjanc This PR doesn't introduce any regression, comparing latest known Zephyr OS (master branch) tested results. Tested agains auto-pts with PTS 7.3.0 - HEAD: d5740e18dc522a7ce819d83ee79efd8be6af7aba

**Comment by jhedberg** [comment]
It would be good to get commit 3d0950e59a8cffc45157640455a549fd9a97cb6c included in this PR.

**Comment by sjanc** [comment]
@jhedberg OK, I'll add this in next version together with fix for last CI error,  after that we should be ready to go :-)

@kolodgrz thanks for testing!

**Review by jhedberg — APPROVED** [review]

**Review by cvinayak — DISMISSED** [review]
What about directed advertising API support backporting to 1.13?

**Comment by cvinayak** [comment]
@jhedberg you are right, I got confused with the broken directed adv implementation on master.

**Comment by cvinayak** [comment]
Sorry wrong button pressed, that closed the issue. Reopening.

**Comment by jhedberg** [comment]
@cvinayak your "changes requested" is still there though

**Comment by jhedberg** [comment]
Any chance to get the patch from #12450 still included into this PR?

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
