### PR TITLE
board/shields: x-nucleo-iks01a3: (FIX) use INT2 for LSM6DSO DRDY

### LINKED ISSUE #20933: x_nucleo_iks01a3 shield: STM LSM6DSO sensor does not work after h/w or s/w reset
LSM6DSO sensor on x_nucleo_iks01a3 shield does not work anymore after reset.

Plug the x_nucleo_iks01a3 shield on an arduino compatible board (e.g. nucleo_f401re).

Then:
1. cd .../zephyrproject/zephyr/samples/shields/x_nucleo_iks01a3/standard/
2. mkdir build && cd build
3. cmake -DBOARD=nucleo_f401re ..
4. make
5. see error on console output::

    ***** Booting Zephyr OS build v2.1.0-rc1-226-gdfe57ca9e118 *****
    Could not get LSM6DSO device
    [00:00:00.004,000] <dbg> LIS2DW12.lis2dw12_set_power_mode: Apply default Power Mode
    [00:00:00.008,000] <dbg> LSM6DSO.lsm6dso_init_interrupt: Could not set pulse mode
    [00:00:00.008,000] <err> LSM6DSO: Failed to initialize interrupt.

### PR DESCRIPTION
**Pull request by avisconti**
On LSM6DSO sensor the INT1 pin is used for both generating the drdy
interrupt and for switching to I3C hotjoin mode just after reset if
it is at logical '1' level. If you reset the x_nucleo_shield3 board
the LSM6DSO enter in hot join, as INT1 '1' level is preserved by
the level shifter.

This commit switch to INT2 to generate DRDY interrupt, so that INT1
always remain to logical '0' level.

Fixes: #20933 

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Comment by erwango** [comment]
@avisconti, is that fixing an already known issue ?

**Comment by avisconti** [comment]
> @avisconti, is that fixing an already known issue ?

@erwango 
Yes, it is a known issue on LSM6DSO and the fact that it is entering I3C hot join state by mistake. This is due to the fact that when INT1 is used as source for DRDY interrupt the '1' is preserved by the level shifter (if any, but on shield3 we have it) and if you press the reset button the INT1 pin is configured as input and the '1' is switching the sensor to hot join state.
Solution prposed by this commit: use INT2 as source of drdy interrrupts, so that int1 remains always to '0'.

**Comment by avisconti** [comment]
@pabigot 
Maybe you can test it on your solution (nrf52_pca10040) as well. Thanks!

**Review by pabigot — APPROVED** [review]
Works with nrf52_pca10040 and iks01a3 shield.  Soft reset and reflash both run without locking up.

**Comment by erwango** [comment]
@avisconti, can you create a matching issue so we can get this in v2.1 ?

**Comment by avisconti** [comment]
> @avisconti, can you create a matching issue so we can get this in v2.1 ?

Yes, sure.

**Comment by avisconti** [comment]
Just repushed including the reference to the #20933 bug in the commit message.

**Review by erwango — APPROVED** [review]

**Pull request merged**
