### PR TITLE
DNS check address family against hints

### LINKED ISSUE #18870: zsock_getaddrinfo() returns garbage values if IPv4 address is passed and hints->ai_family == AF_INET6
**Describe the bug**
When `zsock_getaddrinfo()` is passed a `node` value that is already a valid stringified IPv4 address, but `hints->ai_family` is configured to `AF_INET6`, the returned address is unusable.

**To Reproduce**
1. Build and run the following application:

**CMakeLists.txt**:
```cmake
cmake_minimum_required(VERSION 3.13.1)
include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
project(pollout_bug_demo)
target_sources(app PRIVATE main.c)
```

**prj.conf**:
```
CONFIG_NEWLIB_LIBC=y
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_SOCKETS=y
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_SERVER_IP_ADDRESSES=y
CONFIG_DNS_SERVER1="8.8.8.8"
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
```

**main.c**:
```c
#include <assert.h>
#include <stdio.h>
#include <net/socket.h>

void main(void) {
    struct zsock_addrinfo *result = NULL;
    int ret = zsock_getaddrinfo("192.168.1.1", NULL,
                                &(struct zsock_addrinfo) {
                                    .ai_family = AF_INET6
                                }, &result);
    assert(!ret);
    assert(result);
    assert(result->ai_addr->sa_family == AF_INET6);
    
    char buf[256];
    puts(zsock_inet_ntop(
            AF_INET6,
            &((const struct sockaddr_in6 *) result->ai_addr)->sin6_addr,
            buf, sizeof(buf)));
}
```
2. Observe a garbage address being printed out, for example `c0a8:101:196:8:5830:8:0:41`. Note that the first two segments, `c0a8:101`, is `192.168.1.1` printed in IPv6 notation. The rest are random bytes from uninitialized memory.

**Expected behavior**
`zsock_getaddrinfo()` in this usage shall fail.

If `AI_V4MAPPED` flag is passed through `hints->ai_flags`, and if Zephyr supported IPv4-mapped IPv6 addresses, then returning a proper IPv4-mapped IPv6 address would also be acceptable, but AFAIK, Zephyr does not support IPv4-mapped IPv6 addresses.

**Impact**
If both IPv4 and IPv6 are configured, `zsock_getaddrinfo()` prefers IPv4 addresses (i.e., returns them first). If an application wants to support IPv4/v6 dual stack, wants to support both domain names and numeric addresses, and wants to prefer IPv6 addresses, one possible approach is to call `getaddrinfo()` with `AF_INET6` hint first, and then fall back to `AF_INET` if that does not yield any results. This approach does not work on Zephyr because of this bug.

A different approach is necessary as a workaround, e.g. attempting to use `inet_pton()` first, or using `getaddrinfo()` without family hint and reordering the results. However, this can be an obstacle when attempting to use existing code that would otherwise be trivially portable to Zephyr.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.10.3
 - Commit SHA or Version used: `aa9b762d12`

### PR DESCRIPTION
**Pull request by jukkar**
Fixes #18870

### CODE REVIEW

**Review by pfalcon — DISMISSED** [review]
I'm not sure this fixes the right problem in the right place. Let's go thru quick questionnaire. 

Basic premise: getaddrinfo()'ing a numeric IP address should never hit a DNS server at all.

@jukkar, so you agree? (y/n)

If no, then oops, because we kinda already follow that way. E.g. numeric IPv4 addresses are resolved w/o querying DNS (of course! DNS is for domain names, how it can resolve numeric address??): https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/sockets/getaddrinfo.c#L176

If yes, then unfortunately we don't have full implementation yet. Only IPv4 numeric addresses are resolved as such. (Or more specifically only IPv4 numeric addresses are resolved by getaddrinfo() at all, because again, DNS is  supposed to resolve only domain names, and nothing else).

Consequently, the proper fix would be:

a) Implement handling of IPv6 numeric addresses in getaddrinfo().
b) In case there's a numeric address with mismatching hints family, handle "can't resolve" situation within getaddrinfo().

This leaves question open of what happens if someone resolve something like "300.0.0.0". Different opinions exist: https://serverfault.com/a/638270 .


Now my humble assessment of what happens with this patch. You, @jukkar, have a funny DNS server, which, being fed a non-domain name, tries to resolve it nonetheless. The authors of that DNS server thought it may be a convenience for users, but its actually a mis-convenience, hiding bugs, like we have here, and providing another attack vector (just wait and see until someone will resolve "1.1.1.1" into "2.2.2.2", leading you god knows where. P.S. I may happen that internets is ridden with such mis-convenience DNS servers. The issue is that we try to resolve a numeric address thru them is still on our side.

**Comment by jukkar** [comment]
> If yes, then unfortunately we don't have full implementation yet. Only IPv4 numeric addresses are resolved as such. (Or more specifically only IPv4 numeric addresses are resolved by getaddrinfo() at all, because again, DNS is supposed to resolve only domain names, and nothing else).

That is incorrect. We definitely check whether the address is numeric IPv6 address. The check is not in getaddrinfo() but it is still there. https://github.com/zephyrproject-rtos/zephyr/blob/4b3f89646d4f05c533c1495b5490e3b7a9b62a55/subsys/net/lib/dns/resolve.c#L784

**Review by rveerama1 — APPROVED** [review]

**Comment by pfalcon** [comment]
> That is incorrect. We definitely check whether the address is numeric IPv6 address. The check is not in getaddrinfo() but it is still there.

> zephyr/subsys/net/lib/dns/resolve.c 

Then only worse, because, as usual, we have various checks spread around, including in random places. This would be a good chance to clean it up, but nope, as usual, just more random patchings will be added.

**Comment by jukkar** [comment]
> Then only worse, because, as usual, we have various checks spread around, including in random places. This would be a good chance to clean it up, but nope, as usual, just more random patchings will be added.

Instead of this constant stream of complaints, why not do something about it and submit patches. I see that you submitted the IPv4 numeric resolving patch in 8b3db460aa5c1dc7acfde810a667b8b3b8d85504, so you should be able to send similar patch for IPv6.

**Comment by pfalcon** [comment]
> Instead of this constant stream of complaints, why not do something about it and submit patches.

This is called "review process", and I'm sorry that you submitted a bunch of hasted patches and it takes so much discussion to point you to better ways to implement them.

> do something about it and submit patches.

I submit patches all the time. Perhaps less frequently that I could, as it takes time to think them out and polish.

> I see that you submitted the IPv4 numeric resolving patch in 8b3db46, so you should be able to send similar patch for IPv6.

Sure, it was on TODO all the time. The question is why you, now that you look in this area, don't lend a hand and implement it, given that the check you want to apply is best to be applied there?

**Comment by jukkar** [comment]
> The question is why you, now that you look in this area, don't lend a hand and implement it, given that the check you want to apply is best to be applied there?

The system works just fine as it is right now. No urgency to implement the checks for IPv6 as the lower level APIs will do the checks anyway. My point was that you started to complain about something that currently works ok, perhaps you didn't check the code properly before hastily commenting things.

**Comment by pfalcon** [comment]
> No urgency to implement the checks for IPv6 as the lower level APIs will do the checks anyway.

But the whole talking about that these checks should be done on getaddrinfo() level, and as soon as they're done there, checks at the lower level are useless dead weight. So, instead of adding dead weight, it makes sense to implement the needed functionality on getaddrinfo() level, because nobody later will clean up dead weight.

But I figure it all falls on deaf ears. And it seems how people use networking in Zephyr is disabling it and using proprietary "offloaded" stacks, which seems to have less problem than some "reviewed" open source projects. So, anyway, let there be more mess, I'm withdrawing my -1.

**Comment by jukkar** [comment]
> But the whole talking about that these checks should be done on getaddrinfo() level, and as soon as they're done there, checks at the lower level are useless dead weight.

Your comment implies that getaddrinfo() is always used to resolve DNS names. This is not true as the DNS API can be used directly (at least currently).

**Comment by pfalcon** [comment]
> Your comment implies that getaddrinfo() is always used to resolve DNS names. This is not true as the DNS API can be used directly (at least currently).

Then it still would be used to resolve **DNS names** (quoting yourself). To resolve numeric IP addresses, we have net_addr_pton().

**Comment by jukkar** [comment]
> Then it still would be used to resolve **DNS names** (quoting yourself). To resolve numeric IP addresses, we have net_addr_pton().

Sure. But of course we need to support numeric IP address resolving, I wonder why we are even talking about obvious things here.

**Comment by pfalcon** [comment]
> Sure. But of course we need to support numeric IP address resolving, I wonder why we are even talking about obvious things here.

We need. And we do. In getaddrinfo(), as it requires that (modulo unimplemented cases, crying for help in being implemented). In inet_pton() (net_addr_pton()). End of list. Anywhere else it's just dead weight and potential source of bugs.

**Comment by jukkar** [comment]
Backporting 1.14 will fail as we are missing various patches needed for getaddrinfo tests.

**Pull request merged**
