### PR TITLE
Bluetooth: tests/shell: Rename Arduino 101 conf file for cmake

### PR DESCRIPTION
**Pull request by jhedberg**
The conf file name must be of the form prj_<board>.conf for it to be
automatically chosen for a given board.

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
Note that it's likely that the build will fail because of a bug in the FAT FS includes:

`In file included from /home/jh/src/zephyr/include/fs/fs_interface.h:45:0,
                 from /home/jh/src/zephyr/include/fs.h:11,
                 from /home/jh/src/zephyr/subsys/bluetooth/host/storage.c:13:
/home/jh/src/zephyr/include/fs/fat_fs.h:11:16: fatal error: ff.h: No such file or directory
`

**Comment by SebastianBoe** [comment]
Fixed the FAT FS include bug. https://github.com/jhedberg/zephyr/pull/1

**Review by SebastianBoe — APPROVED** [review]

**Comment by jhedberg** [comment]
Some cleaner solution will be needed, so let's not merge this yet

**Comment by jhedberg** [comment]
See https://github.com/zephyrproject-rtos/zephyr/issues/4910

**Comment by jhedberg** [comment]
The patches have been updated now, so this should be ready for merghing

**Pull request merged**
