### PR TITLE
tests: Remove posix exclude

### PR DESCRIPTION
**Pull request by finikorg**
Build also for posix.

### CODE REVIEW

**Review by pabigot — COMMENTED** [review]
I can't see any record of the motivation for excluding this originally.  It may have been a toolchain issue that's been fixed.

I don't see any problem with this, but would like @vanwinkeljan who's done cross-platform/toolchain testing more recently.

Also if there is no reason to exclude posix then the same change should be made to the libcxx test.

**Review by pabigot — CHANGES_REQUESTED** [review]
Never mind.  Looking at the shippable results posix is excluded because shippable won't pass due to a lack of libstdc++.

**Comment by vanwinkeljan** [comment]
> Never mind. Looking at the shippable results posix is excluded because shippable won't pass due to a lack of libstdc++.

Is this not actually due to a missing 32-bit version (multilib) of stdc++ in the ci docker container

See: https://github.com/zephyrproject-rtos/ci-dockerfiles/issues/19

**Comment by aescolar** [comment]
> I can't see any record of the motivation for excluding this originally

When native_posix was first added, C++ did not work on it at all. There has been many fixes over this ~2 years that should have made it possible now.

**Comment by pabigot** [comment]
@finikorg Could you rebase this so we can verify the merge of #19735 enables this to pass shippable?

**Comment by finikorg** [comment]
> @finikorg Could you rebase this so we can verify the merge of #19735 enables this to pass shippable?

Done

**Comment by vanwinkeljan** [comment]
Added label blocked as CI docker image is needed see https://github.com/zephyrproject-rtos/ci-dockerfiles/pull/59

**Review by vanwinkeljan — CHANGES_REQUESTED** [review]
Please also remove `arch_exclude: posix` from  `tests/application_development/libcxx/testcase.yaml`.

**Comment by finikorg** [comment]
> Please also remove `arch_exclude: posix` from `tests/application_development/libcxx/testcase.yaml`.

added second patch

**Review by vanwinkeljan — APPROVED** [review]
thx, now we only have to wait for a new CI docker image including multilib and C++ 17

**Comment by vanwinkeljan** [comment]
blocked by #20625

**Comment by vanwinkeljan** [comment]
@finikorg could you rebase with latest master?

**Comment by finikorg** [comment]
> @finikorg could you rebase with latest master?

Done.

**Comment by vanwinkeljan** [comment]
@pabigot can please revisit you review

**Review by pabigot — APPROVED** [review]

**Comment by vanwinkeljan** [comment]
@nashif can this be merged?

**Pull request merged**
