### PR TITLE
wifi: Add hostap OSS repo

### PR DESCRIPTION
**Pull request by krish2718**
This PR adds a downstream fork of [`hostap`](https://w1.fi/cgit/hostap/) to the Zephyr project. This was developed in a downstream fork of Zephyr (Nordic's nRF connect), so, all the history is also pulled with slight tweaks to remove Nordic related stuff.

### CODE REVIEW

**Comment by carlescufi** [comment]
@krish2718 @jukkar @rlubos this requires an issue as part of [the process](https://docs.zephyrproject.org/latest/contribute/external.html#submission-and-review-process)

**Comment by jukkar** [comment]
Hmm, I do not think we are ready yet for this. The commits needs cleanup etc. We could still leave this as a draft while preparation of proper release.

**Comment by krish2718** [comment]
Sure, I was preparing a local draft of the issue to be raised, so, just submitted this as part of the checklist, we can update before raising the issue.

**Comment by dleach02** [comment]
@krish2718, do you have any insight in how much additional changes are needed in hostap for the Zephyr integration? 

I'm asking because we might want to consider a process flow to manage these changes if we anticipate delays in providing the changes to the hostap upstream.

**Comment by krish2718** [comment]
> @krish2718, do you have any insight in how much additional changes are needed in hostap for the Zephyr integration?

Let me check and get back to you on this.

> 
> I'm asking because we might want to consider a process flow to manage these changes if we anticipate delays in providing the changes to the hostap upstream.

Can you please elaborate on what `process flow` means? Are you referring to picking unmerged changes in case there is a delay?

**Comment by dleach02** [comment]
Specifically, I think it would be beneficial to manage changes to this repository using a flow that your company uses on their fork of Zephyr. Particularly the special tags and such.

**Comment by dleach02** [comment]
can we close this PR?

**Comment by carlescufi** [comment]
> can we close this PR?

@jukkar ?

**Comment by krish2718** [comment]
Yes, @jukkar  's PR supersedes this PR.

**Pull request closed without merging**
