### PR TITLE
kconfig: experimental settings now uses `select EXPERIMENTAL`

### PR DESCRIPTION
**Pull request by tejlmand**
Continuation of: #33566

This PR is opened independently to allow proper review of all setting having experimental in their title, as requested at API-meeting:
See https://github.com/zephyrproject-rtos/zephyr/pull/33566#issuecomment-810396251
> Review all options that are currently marked as EXPERIMENTAL in their title

To reviewers, the important thing to review is not whether the `select EXPERIMENTAL` is correct but to consider whether or not the feature itself is still experimental or if `EXPERIMENTAL` should be removed.

**If approving the PR, then please make a comment regarding which area you have verified, for example:**
> EXPERIMENTAL on subsys/net verified

Also, if you have the knowledge, then as per: https://lwn.net/Articles/520867/
>  For items that really are experimental, maintainers should use "default
>  n", optionally include "(EXPERIMENTAL)" in the title, and add language to
>  the help text indicating why the item should be considered experimental.

feel free to add a comment under the setting stating why the feature is considered experimental and I will update the help text with the proposed text in this PR.

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]
- EXPERIMENTAL on drivers/can reviewed
- EXPERIMENTAL on subsys/canbus reviewed
- EXPERIMENTAL on subsys/net/l2/canbus reviewed

**Review by joerchan — CHANGES_REQUESTED** [review]
BT_AUDIO is missing. I'm guessing that is because it is with "[Experimental]" tag instead.
Could be more, so best to do a case-insensitive search.

**Review by joerchan — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Ack for Bluetooth

**Review by jukkar — APPROVED** [review]
+1 to networking changes

**Pull request merged**
