### PR TITLE
storage/flash_map: Add option to use MBEDTLS for img integrity check.

### LINKED ISSUE #38982: subsys: storage: flash_map: Add mbedtls option for `flash_area_check_int_sha256`
**Is your enhancement proposal related to a problem? Please describe.**
Provide an option for `flash_area_check_int_sha256` to use mbedtls for the SHA256 hash, so that an application doesn't have to compile tinycrypt if it already compiles the mbedtls, which should save some ROM space.

**Describe the solution you'd like**
Kconfig options to switch between tinycrypt and mbedtls.

### PR DESCRIPTION
**Pull request by ycsin**
Add option to use MBEDTLS library to perform the flash area integrity check, so that application with mbedtls already compiled doesn't have to compile another crypto library.

fixes #38982

### CODE REVIEW

**Review by nvlsianpu — APPROVED** [review]

**Comment by ycsin** [comment]
For some reason it fails the flash map test, I haven't run this on a real board to debug yet.

**Review by nvlsianpu — DISMISSED** [review]
Right, besides patch looks good to me

**Review by d3zd3z — APPROVED** [review]
At some point, we'd like to migrate to a single API (probably the PSA crypto API). It gets a bit messy having to have ifdefs at every use site. But, for now, this is fine, and just becomes yet another place we need to fix that.

Have you benchmarked the SHA256 between Mbed TLS and TC? I know at least some of the operations are quite a bit faster in Mbed TLS (other than EC, which is slower).

**Comment by ycsin** [comment]
@d3zd3z Thanks for the review and the suggestion, I will mark this draft for now and change it at another time.

**Comment by ycsin** [comment]
@nvlsianpu @d3zd3z could you review this again? Thanks!

**Review by d3zd3z — APPROVED** [review]

**Comment by d3zd3z** [comment]
@nvlsianpu can you check to see if your concerns are addressed?

**Review by ceolin — APPROVED** [review]

**Comment by ycsin** [comment]
ping @nvlsianpu
could you review again?

**Review by nandojve — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by ycsin** [comment]
@cfriedt thanks!

**Pull request merged**
