### PR TITLE
doc: cmake: Enable out-of-tree builds

### PR DESCRIPTION
**Pull request by carlescufi**
The following changes have been made to support out-of-tree builds:

* In order to avoid using relative hardcoded paths, use CMake's
  configure_file() to replace the paths in the doxygen input file
  so that the output directory is set correctly.
* All .rst and additional required files are now copied from the doc/
  folder into the build/rst folder using extract_content.py. The
  samples/ and boards/ folder are copied twice (once into build/rst
  and another into build/doc/rst) to manage relative paths.
* All paths are absolute where possible, including themes and static
  content.

This patch ensures that the Zephyr repo is not contaminated by the
build at all.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
@dbkinder 
Here's a diff between the HTML generated in master and in this branch:

```diff
diff -r master-html/.buildinfo oot-html/.buildinfo
3c3
< config: eef16d2b03d9721464cc1105dfd06154
---
> config: 140f916d9e4698bf01f385e60217a412
diff -r master-html/_sources/contribute/doc-guidelines.rst.txt oot-html/_sources/contribute/doc-guidelines.rst.txt
343c343
< .. include:: /extensions/zephyr/application.py
---
> .. include:: ../extensions/zephyr/application.py
diff -r master-html/west/flash-debug.html oot-html/west/flash-debug.html
413c413
< <em class="property">class </em><code class="descclassname">west.runner.core.</code><code class="descname">RunnerCaps</code><span class="sig-paren">(</span><em>commands={'debugserver'</em>, <em>'debug'</em>, <em>'flash'}</em>, <em>flash_addr=False</em><span class="sig-paren">)</span><a class="headerlink" href="#west.runner.core.RunnerCaps" title="Permalink to this definition">Â¶</a></dt>
---
> <em class="property">class </em><code class="descclassname">west.runner.core.</code><code class="descname">RunnerCaps</code><span class="sig-paren">(</span><em>commands={'debug'</em>, <em>'debugserver'</em>, <em>'flash'}</em>, <em>flash_addr=False</em><span class="sig-paren">)</span><a class="headerlink" href="#west.runner.core.RunnerCaps" title="Permalink to this definition">Â¶</a></dt>
```

**Comment by carlescufi** [comment]
@dbkinder could you please play around a bit with this, to make sure everything is fine and also to see if incremental builds still work as they should? thanks!

**Review by nashif — APPROVED** [review]

**Comment by dbkinder** [comment]
I tried doing a ``make htmldocs`` from my $ZEPHYR_BASE folder and it seems to work.  And when I ran it again it worked again (yea).  But then I followed the instructions in the http://docs.zephyrproject.org/README.html where it looks like I can do:

```
cd doc/_build
ninja htmldocs
```

But that failed with:

```
ninja: error: loading 'build.ninja': No such file or directory
```

So I tried:

```
cmake -GNinja ..
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```

Ah.  Looking at the zephyr/Makefile I see it used ``cmake -G"Unix Makefiles"`` while the document says to use ``cmake -GNinja`` so there's a mismatch. If you use the "convenience" Makefile ``make htmldocs`` you can't then use the documented doc build process, and vice versa.

Of course, when I tried to clean stuff up as documented:

```
ninja pristine
ninja: error: loading 'build.ninja': No such file or directory
```

So I just deleted the ``doc/_build`` folder manually and followed the documented steps:

```
mkdir _build; cd _build;
cmake -GNinja ..
ninja htmldocs
```

That ran fine and took 6m42s.  I immediately did another build ``ninja htmldocs`` and it took the same amount of time.  That would indicate the Sphinx optimizations reducing content regeneration time are thwarted by this PR  (including @ulfalizer change to genrest.py to not rewrite the config .rst files if the content didn't change).

**Comment by carlescufi** [comment]
@dbkinder thanks for testing.

Mixing the Makefile and `ninja` was never supported in the first place, because with the Makefile I use `make` as a generator since it makes sense not to require a new tool.

There is something I don't quite understand in your explanation. Can you please give me the exact sequence of commands that gives you incremental builds before this PR (i.e. in current master) and that no longer works with this PR?

I would recommend using either the Makefile or CMake + Ninja, but it's fine to mix them if you use make instead.

**Comment by dbkinder** [comment]
@carlescufi Maybe add the ``write_if_updated`` hack that's in genrest.py to extract_content.py to help?

**Comment by dbkinder** [comment]
Sphinx itself does the build-time optimization based on it's own caching.  We got a nice speed improvement when the genrest.py was tweaked to not rewrite .rst file for the config options if the content didn't change.  That doesn't seem to be working with your PR where I did two ``time ninja html`` commands in a row and the time was the same 6m42s, where on the current master branch, the second run is only 2m10s.

**Comment by dbkinder** [comment]
I guess we can ignore comments about the mismatched Cmake/Ninja stuff, though I wonder if the top level makefile could/should use ``-GNinja`` so it's the same?

**Comment by carlescufi** [comment]
>Sphinx itself does the build-time optimization based on it's own caching. We got a nice speed improvement when the genrest.py was tweaked to not rewrite .rst file for the config options if the content didn't change. That doesn't seem to be working with your PR where I did two time ninja html commands in a row and the time was the same 6m42s, where on the current master branch, the second run is only 2m10s.

Understood. I will play around and try to fix this after I've reproduced locally.

**Comment by carlescufi** [comment]
>I guess we can ignore comments about the mismatched Cmake/Ninja stuff, though I wonder if the top level makefile could/should use -GNinja so it's the same?

Yeah, I think we should actually. I will add a commit later.

**Comment by dbkinder** [comment]
BTW, the Sphinx "cache" is the ``doctree`` folder specified by the ``-d`` parameter to Sphinx:

-d path
  Since Sphinx has to read and parse all source files before it can write an output file, the parsed  source files are cached as “doctree pickles”. Normally, these files are put in a directory called .doctrees under the build directory; with this option you can select a different cache directory (the doctrees can be shared between all builders).

**Comment by pizi-nordic** [comment]
FYI: @pdunaj

**Comment by carlescufi** [comment]
>@carlescufi Maybe add the write_if_updated hack that's in genrest.py to extract_content.py to help?

Done, and it works beautifully. Even faster than before, thanks for the tip

**Comment by carlescufi** [comment]
>Sphinx itself does the build-time optimization based on it's own caching. We got a nice speed improvement when the genrest.py was tweaked to not rewrite .rst file for the config options if the content didn't change. That doesn't seem to be working with your PR where I did two time ninja html commands in a row and the time was the same 6m42s, where on the current master branch, the second run is only 2m10s.

This was a recursion bug I introduced in `extract_contents.py`. I've fixed it now and everything is in order.

**Comment by carlescufi** [comment]
>I guess we can ignore comments about the mismatched Cmake/Ninja stuff, though I wonder if the top level makefile could/should use -GNinja so it's the same?

Done

**Pull request merged**
