### PR TITLE
stm32 usb: fix disconnect-gpios configuration

### LINKED ISSUE #45791: drivers/usb: stm32: Superfluous/misleading Kconfig option
**Describe the bug**
For some reason, rather than testing for the presence of disconnect-gpios in the devicetree, the USB Device driver was relying on a hidden Kconfig flag to be set.

This has two problems:

Board developers need to realise that there's a Kconfig option too and override it in their board definition so their DT setting works.

You can't trivially enable it via overlay when you're developing on a generic board like the nucleo since you can't assert the hidden Kconfig flag via prj.conf.

When I was auditing this, I also found there are several boards (other than the OLIMEXINO) that have the disconnect-gpios enabled in their DTS, but not in their kconfig!

**Expected behavior**
DTS description should be sufficient for this specific configuration

**Impact**
Could easily lead to misconfiguration

### PR DESCRIPTION
**Pull request by kuroneko**
For some reason, rather than testing for the presence of disconnect-gpios in the devicetree, the USB Device driver was relying on a hidden Kconfig flag to be set.

This has two problems:

  1. Board developers need to realise that there's a Kconfig option too and override it in their board definition so their DT setting works.

  2. You can't trivially enable it via overlay when you're developing on a generic board like the nucleo since you can't assert the hidden Kconfig flag via prj.conf.

When I was auditing this, I also found there are several boards (other than the OLIMEXINO) that have the disconnect-gpios enabled in their DTS, but not in their kconfig!

This patch removes the Kconfig option completely and simply tests for the DT property "disconnect-gpios" - if it's set, you obviously know what you're doing and obviously need the pull-up GPIO behaviour.

EDIT (@erwango):
Fixes #45791

### CODE REVIEW

**Review by erwango — DISMISSED** [review]

**Comment by erwango** [comment]
Thanks @kuroneko for this change. This is indeed better that way.

Since we're in the code freeze period of the V3.2.0, an issue is requested in order to allow the merge of this fix. I've created it, so  you should be goo to go now.

One nitpick comment on the commit, please use a more formal subsystem specifier path:
`drivers: usb: stm32: my change`

**Review by loicpoulain — DISMISSED** [review]

**Review by jfischer-no — COMMENTED** [review]
Introduced by 38d2567e088fd49eaf7a1037eeb6df6aaf029000, most of the options are removed in f47b9c2fca00801ce8cb55b20937fca5d5c29c2a

>on a hidden Kconfig flag

This Kconfig option is not hidden, it just does not have a prompt and does not need it. Please update your commit message accordingly.

**Comment by erwango** [comment]
@kuroneko Would you mind fixing the compliance check:
```
Run if [[ ! -s "compliance.xml" ]]; then
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style for more details.

Missing newline at end of 'drivers/usb/device/usb_dc_stm32.c'. Check your text editor settings.
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style for more details.

-:37: ERROR:SPACING: space required after that ',' (ctx:VxV)
#37: FILE: drivers/usb/device/usb_dc_stm32.c:1102:
+#if (defined(USB) || defined(USB_DRD_FS)) && DT_INST_NODE_HAS_PROP(0,disconnect_gpios)
                                                                     ^

-:46: WARNING:MISSING_EOF_NEWLINE: adding a line without newline at end of file
#46: FILE: drivers/usb/device/usb_dc_stm32.c:1115:
+#endif /* USB && DT_INST_NODE_HAS_PROP(0,disconnect_gpios) */

- total: 1 errors, 1 warnings, [29](https://github.com/zephyrproject-rtos/zephyr/runs/6502777912?check_suite_focus=true#step:9:30) lines checked
```

**Review by erwango — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]
Thanks!

**Pull request merged**
