### PR TITLE
boards: arm: update pwm signals on all STM32 based boards

### PR DESCRIPTION
**Pull request by gmarull**
Update PWM pinctrl signal names of all non-F1 STM32 boards.

STM32 timers are multi-purpose peripherals ranging from PWM, Input
capture, encoder, HALL sensor... In all series except F1 the timer pins
will always be configured in the same mode, i.e. alternate. So using a
variant for each functionality is not necessary. When working with F1
series mode is still required because the pin may operate in either
alternate or input mode depending on the assigned functionality.

Companion PR: https://github.com/zephyrproject-rtos/hal_stm32/pull/80

### CODE REVIEW

**Review by martinjaeger — APPROVED** [review]
Looks good and makes sense.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@galak this is ready for merge. (DNM is for the BK patch)

**Comment by gmarull** [comment]
@galak This PR should be merged before any other PR updating hal_stm32 with later additions.

**Review by Navin-Sankar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
CI is green with the BK  patch, please remove the patch @gmarull

**Comment by gmarull** [comment]
@carlescufi done

**Pull request merged**
