### PR TITLE
zephyr-env.sh: reduce posixargzero side effects.

### LINKED ISSUE #20284: zephyr-env.sh  Is this supposed to be unsetopt posixargzero ?
```sh
if [ -n "${ZSH_VERSION:-}" ]; then
        DIR="${(%):-%N}"
        if [ $options[posixargzero] != "on" ]; then
                setopt posixargzero
                NAME=$(basename -- "$0")
                # setopt posixargzero
                unsetopt posixargzero
        else
                NAME=$(basename -- "$0")
        fi
else
        DIR="${BASH_SOURCE[0]}"
        NAME=$(basename -- "$0")
fi
```

**If we don't change this option back, it may affect other scripts in the current context.**

### PR DESCRIPTION
**Pull request by honsunrise**
Reduce zephyr-env.sh side effects. 
For example, when using zsh p9k theme will cause some problems that affect the experience.

Fixes #20284.

Signed-off-by: Hosun Zhu <hosun@linux.com>

### CODE REVIEW

**Comment by carlescufi** [comment]
@bandheight thanks for the PR. Can you  please format the commit message according to the project rules?

https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

**Comment by aescolar** [comment]
Thanks for your contribution @bandheight .
Note that the bot is going to complain about this commit not meeting this https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines 
(you will need to fix it)

With regards to the PR, please set a title that is descriptive of the change itself

**Comment by bandheight** [comment]
I have changed my github name to Hosun Zhu. 
Why can't pass CI checks?

**Comment by carlescufi** [comment]
@bandheight it's not the GitHub  name, but the name that git sees in your `~/.gitconfig`

**Pull request closed without merging**
