### PR TITLE
x86: early_printk: allow custom UART clock, baud rate, and SoC specific initialization

### PR DESCRIPTION
**Pull request by dcpleung**
The x86 early_printk is used as very early serial console to print out debug information. It is useful when doing platform bringup and debugging architecture and SoC initialization code.

This PR changes the initialization code to allow custom UART clock rate and serial baud rate defined in the UART device tree entry via `zephyr_console`. This is to accommodate SoC with UART clock other than the more usual 1.8432MHz rate.

This also adds two weak functions which are to be implemented in the SoC layer to allow SoC specific initialization of UART, e.g. power/clock gating, pinmux, etc.

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]
I wonder if the increasing number of #defines needed in early_serial.c could be placed in a header used by both the early serial driver, and the real ns16550 one. As we make early serial more feature-ful, I think investigation of areas for unification would remove duplication between the two drivers. Up to and including checking if we can somehow just get the regular 16550 driver to init this early in the boot process.

What's an example of a post step, that can't be done in the pre step?

**Comment by dcpleung** [comment]
The early_serial.c uses `zephyr-console` DT node which points to the actual UART DT node. It will probably need some macro magic.

If we initialize 16550 driver early, we can instead have a simple, universal output-only, non-interrupt driven console driver similar to UART console driver. We will then need another init level which will do SoC specific init, 16550 driver init and console driver init.

As for the post init part, some SoCs need baud rate set (e.g. to initialize the clock) before the UART block can be enabled for I/O.

**Review by sjg20 — APPROVED** [review]

**Comment by nashif** [comment]
@dcpleung  please rebase

**Comment by dcpleung** [comment]
Due to the early console no longer getting configuration from DTS, this PR is no longer usable. Closing...

**Pull request closed without merging**
