### PR TITLE
Add automated testing using Travis CI

### PR DESCRIPTION
**Pull request by cclauss**
41 undefined names (variables that are not defined or imported -- May raise NameError at runtime)

[flake8](http://flake8.pycqa.org) testing of https://github.com/zephyrproject-rtos/zephyr on Python 3.7.

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./doc/conf.py:71:4: F821 undefined name 'tags'
if tags.has("svgconvert"):
   ^
./doc/conf.py:194:4: F821 undefined name 'tags'
if tags.has('release'):
   ^
./scripts/dts/gen_defines.py:191:9: F821 undefined name '_err'
        _err("missing 'label' property on {!r}".format(dev.parent))
        ^
./scripts/dts/testdtlib.py:1215:46: F821 undefined name 'alias'
            fail("no node found for path " + alias)
                                             ^
./scripts/dts/dtlib.py:243:29: F821 undefined name '_T_LABEL'
            elif tok.id in (_T_LABEL, _T_REF):
                            ^
./scripts/dts/dtlib.py:243:39: F821 undefined name '_T_REF'
            elif tok.id in (_T_LABEL, _T_REF):
                                      ^
./scripts/dts/dtlib.py:247:30: F821 undefined name '_T_LABEL'
                if tok.id is _T_LABEL:
                             ^
./scripts/dts/dtlib.py:250:38: F821 undefined name '_T_REF'
                    if tok.id is not _T_REF:
                                     ^
./scripts/dts/dtlib.py:264:28: F821 undefined name '_T_DEL_NODE'
            elif tok.id is _T_DEL_NODE:
                           ^
./scripts/dts/dtlib.py:271:28: F821 undefined name '_T_OMIT_IF_NO_REF'
            elif tok.id is _T_OMIT_IF_NO_REF:
                           ^
./scripts/dts/dtlib.py:278:28: F821 undefined name '_T_EOF'
            elif tok.id is _T_EOF:
                           ^
./scripts/dts/dtlib.py:292:40: F821 undefined name '_T_DTS_V1'
        while self._peek_token().id is _T_DTS_V1:
                                       ^
./scripts/dts/dtlib.py:297:41: F821 undefined name '_T_PLUGIN'
            if self._peek_token().id is _T_PLUGIN:
                                        ^
./scripts/dts/dtlib.py:310:44: F821 undefined name '_T_LABEL'
            while self._peek_token().id is _T_LABEL:
                                           ^
./scripts/dts/dtlib.py:313:41: F821 undefined name '_T_MEMRESERVE'
            if self._peek_token().id is _T_MEMRESERVE:
                                        ^
./scripts/dts/dtlib.py:373:28: F821 undefined name '_T_DEL_NODE'
            elif tok.id is _T_DEL_NODE:
                           ^
./scripts/dts/dtlib.py:381:28: F821 undefined name '_T_DEL_PROP'
            elif tok.id is _T_DEL_PROP:
                           ^
./scripts/dts/dtlib.py:404:26: F821 undefined name '_T_LABEL'
            if tok.id is _T_LABEL:
                         ^
./scripts/dts/dtlib.py:406:28: F821 undefined name '_T_OMIT_IF_NO_REF'
            elif tok.id is _T_OMIT_IF_NO_REF:
                           ^
./scripts/dts/dtlib.py:436:28: F821 undefined name '_T_BITS'
            elif tok.id is _T_BITS:
                           ^
./scripts/dts/dtlib.py:446:28: F821 undefined name '_T_CHAR_LITERAL'
            elif tok.id is _T_CHAR_LITERAL:
                           ^
./scripts/dts/dtlib.py:452:28: F821 undefined name '_T_STRING'
            elif tok.id is _T_STRING:
                           ^
./scripts/dts/dtlib.py:455:28: F821 undefined name '_T_REF'
            elif tok.id is _T_REF:
                           ^
./scripts/dts/dtlib.py:458:28: F821 undefined name '_T_INCBIN'
            elif tok.id is _T_INCBIN:
                           ^
./scripts/dts/dtlib.py:479:26: F821 undefined name '_T_REF'
            if tok.id is _T_REF:
                         ^
./scripts/dts/dtlib.py:486:28: F821 undefined name '_T_LABEL'
            elif tok.id is _T_LABEL:
                           ^
./scripts/dts/dtlib.py:514:28: F821 undefined name '_T_LABEL'
            elif tok.id is _T_LABEL:
                           ^
./scripts/dts/dtlib.py:535:26: F821 undefined name '_T_STRING'
        if tok.id is not _T_STRING:
                         ^
./scripts/dts/dtlib.py:567:30: F821 undefined name '_T_LABEL'
            if tok.id is not _T_LABEL:
                             ^
./scripts/dts/dtlib.py:615:31: F821 undefined name '_T_CHAR_LITERAL'
        if tok.id in (_T_NUM, _T_CHAR_LITERAL):
                              ^
./scripts/dts/dtlib.py:806:26: F821 undefined name '_T_SKIP'
            if tok_id is _T_SKIP:
                         ^
./scripts/dts/dtlib.py:812:26: F821 undefined name '_T_INCLUDE'
            if tok_id is _T_INCLUDE:
                         ^
./scripts/dts/dtlib.py:821:26: F821 undefined name '_T_LINE'
            if tok_id is _T_LINE:
                         ^
./scripts/dts/dtlib.py:827:26: F821 undefined name '_T_EOF'
            if tok_id is _T_EOF:
                         ^
./scripts/dts/dtlib.py:831:31: F821 undefined name '_T_EOF'
                return _Token(_T_EOF, "<EOF>")
                              ^
./scripts/dts/dtlib.py:835:27: F821 undefined name '_T_DEL_PROP'
            if tok_id in (_T_DEL_PROP, _T_DEL_NODE, _T_OMIT_IF_NO_REF) or \
                          ^
./scripts/dts/dtlib.py:835:40: F821 undefined name '_T_DEL_NODE'
            if tok_id in (_T_DEL_PROP, _T_DEL_NODE, _T_OMIT_IF_NO_REF) or \
                                       ^
./scripts/dts/dtlib.py:835:53: F821 undefined name '_T_OMIT_IF_NO_REF'
            if tok_id in (_T_DEL_PROP, _T_DEL_NODE, _T_OMIT_IF_NO_REF) or \
                                                    ^
./scripts/dts/dtlib.py:843:29: F821 undefined name '_T_MEMRESERVE'
            elif tok_id in (_T_MEMRESERVE, _T_BITS) or tok_val == "]":
                            ^
./scripts/dts/dtlib.py:843:44: F821 undefined name '_T_BITS'
            elif tok_id in (_T_MEMRESERVE, _T_BITS) or tok_val == "]":
                                           ^
./scripts/dts/dtlib.py:918:28: F821 undefined name '_T_REF'
        if label.id is not _T_REF:
                           ^
41    F821 undefined name 'tags'
41
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by galak** [comment]
We've started to have pylint run as part of our CI flow.  Is this still relevant?

**Comment by cclauss** [comment]
https://lukeplant.me.uk/blog/posts/pylint-false-positives

**Comment by galak** [comment]
> [lukeplant.me.uk/blog/posts/pylint-false-positives](https://lukeplant.me.uk/blog/posts/pylint-false-positives)

Adding @ulfalizer one of our resident python experts.

**Comment by ulfalizer** [comment]
@cclauss 
Hello,

Those are all false positives, and are suppressed in our automatic `pylint` check that just got integrated. We've fixed all the warnings from `pylint` (and suppressed a few false positive ones).

There's a `# pylint: disable=undefined-variable` for `tags` in `doc/conf.py` for example.

Our `pylint` configuration is [here](https://github.com/zephyrproject-rtos/ci-tools/blob/master/scripts/pylintrc).

**Comment by ulfalizer** [comment]
For what it's worth, I agree that `pylint`'s default configuration is way too nitty. Useful warnings tend to get drowned out in a flood of complaints about short variable names and wrong hanging indents and stuff.

`pylint` can be tamed into a useful and non-annoying tool though. I summed up what warnings I left disabled [here](https://github.com/zephyrproject-rtos/ci-tools/pull/37#discussion_r322975156), along with motivations.

**Pull request closed without merging**
