### PR TITLE
drivers: i2c_shell: Add direct_read sub command

### PR DESCRIPTION
**Pull request by erang20**
Adds a direct_read subcommand to the I2C command.

Usage: I2C direct_read <device> <addr> [<nbytes>].
This command reads directly from the I2C device without first writing a register address.

### CODE REVIEW

**Review by teburd — APPROVED** [review]
looks ok to me, thanks!

**Comment by erang20** [comment]
@nashif Can you please review this change? Thanks!

**Comment by erang20** [comment]
@nashif Any chance you can get to this soon?

Thanks!

**Comment by erang20** [comment]
@teburd I think that @nashif is OOO. Can we assign another reviewer? Thanks!

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
