### PR TITLE
Nios2-i2c: Add i2c master driver for Nios-II i2c core

### PR DESCRIPTION
**Pull request by ramakrishnapallala**

### CODE REVIEW

**Comment by ramakrishnapallala** [comment]
@nashif @andrew How to handle warning messages which are coming from HAL drivers? The idea is we should not make changes to them right?

**Review by rgundi — APPROVED** [review]
Looks good to me

**Comment by nashif** [comment]
> @nashif @andrew How to handle warning messages which are coming from HAL drivers? The idea is we should not make changes to them right?

deal with that warning in the cmake file building the source. You can remove this warning for this particular file. see for example ext/hal/ti/simplelink/CMakeLists.txt

**Comment by ramakrishnapallala** [comment]
Thank you @anas

**Comment by ramakrishnapallala** [comment]
Shippable passed. Good for review @andrewboie @lpereira

**Review by tyrantlizard77 — APPROVED** [review]

**Pull request merged**
