### PR TITLE
doc: release-notes-2.6: CAN bus and Task Watchdog

### PR DESCRIPTION
**Pull request by martinjaeger**
See commit messages.

### CODE REVIEW

**Comment by str4t0m** [comment]
I'm not sure if we should mention STM32G0 CAN-FD support until #34963 is merged.

While all the tests pass on STM32G4, the assert checking the valid range of sjw failed due to the uninitialized timing.sjw and caused all tests to fail on STM32G0.
#34963 includes a commit that initializes timing.sjw in case CAN-FD is enabled.
Is there a chance this PR could still be merged in 2.6?

**Comment by martinjaeger** [comment]
@str4t0m Makes sense, I can take out the G0 remark again. For some reason I thought that the devicetree nodes for G0 also made it into the tree already.

I guess it can't be merged into 2.6 anymore. But your PR also contains a bugfix, which could still get merged if it's in a separate PR.

**Comment by alexanderwachter** [comment]
It has to be merged for 2.6 since it is a bug fix

**Comment by martinjaeger** [comment]
@str4t0m updated the notes to include the STM32G4 only.
@alexanderwachter let me know if I forgot any other important change for CAN.

**Review by MaureenHelm — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
