### PR TITLE
Revert "lib c/cpp: Move .ctor .init_array handling from C++ to kernel"

### PR DESCRIPTION
**Pull request by andyross**
Unfortunately this breaks native_sim fuzzing due (presumably) to interactions with the .ctors emitted by the libc/sanitizer layer.

See SOF discussion at https://github.com/thesofproject/sof/pull/9278

This reverts commit 6e977ae2d54c4f5443f752ce3a88f22043dcbf07.

### CODE REVIEW

**Comment by andyross** [comment]
cc @kv2019i @aescolar @marc-hb

Throwing this up as a revert since we're so close to the release just to have somewhere to discuss the regression.  I don't have a proper analysis yet.

**Comment by aescolar** [comment]
@andyross you are still running the fuzzer in native_posix and not native_sim?
(i can repro the issue in native_posix but things seem to work fine in native_sim)

**Review by aescolar — CHANGES_REQUESTED** [review]
I see the reason for the issue[^1]
It would seem this only happens when you run the fuzzer in native_posix but works fine in native_sim.
So I see as less dramatic options:
a) We just say that the fuzzer is not supported anymore in native_posix but only in native_sim. (native_posix will be deprecated right after we do the release). So we are just forcing you to switch the target in your CI by 3 weeks :)
b) We change the default so this option is not enabled for NATIVE_APPLICATION if ARCH_POSIX_LIBFUZZER

[^1]: native_posix does not have a separately linked runner where its own constructors will be run like native_sim, so indeed whatever the fuzzer wanted to run before the native_posix initialization is not run yet and it fails

**Comment by andyross** [comment]
OK, will investigate what needs to change to get the fuzzing support ported to native_sim.  For right now it's probably enough to add a kconfig setting to SOF to turn this off (which would preclude fuzzing C++ code or relying on non-C++ static initializers of course, but that's fine for the short term).

FWIW the deadline is actually now, though.  SOF tracks upstream pretty closely and the linked discussion is an uprev required to get an unrelated fix.

**Comment by aescolar** [comment]
> ARCH_POSIX_LIBFUZZER

fastest fix just do CONFIG_STATIC_INIT_GNU=n in your prj.conf

**Comment by andyross** [comment]
Yeah, I was bumping into the kconfig trap too. :)  Really the fastest way to solve this (absent SOF carrying around a private reversion) is to just do the board swap.

**Comment by aescolar** [comment]
@andyross https://github.com/zephyrproject-rtos/zephyr/pull/75404

**Comment by keith-packard** [comment]
Looks like there are a couple of fine options to pick from; not sure I can help you all decide which to run with.

**Comment by andyross** [comment]
Going to close this one.  native_sim port in SOF is up at https://github.com/thesofproject/sof/pull/9280 which resolves the regression for me, no need to do a full revert before LTS

**Pull request closed without merging**
