### PR TITLE
nvmp: a flash_map replacement

### PR DESCRIPTION
**Pull request by Laczen**
flash_map is used by several subsystems to allow access to flash devices in a unified way. Flash_map is by design directed and limited towards flash devices and does not provide support for other non volatile memories (e.g. eeprom).

nvmp (non volatile memory and partitioning) is proposed as an alternative for flash_map that provides a path to solve many problems that are caused by flash_map (e.g. https://github.com/zephyrproject-rtos/zephyr/issues/52395, the need to use flash_page interface for block-size, the ability to override the flash page size with a multiple, ...).

The proposal is easily extended to other types of memory that would use a dedicated driver solution (e.g. fram, mram, rram that could have a driver similar to eeprom). It can also be extended to disks and even files.

nvmp is an alternative for https://github.com/zephyrproject-rtos/zephyr/pull/67687 and https://github.com/zephyrproject-rtos/zephyr/pull/70828.

### CODE REVIEW

**Review by de-nordic — CHANGES_REQUESTED** [review]
Still misses the point of device capabilities.

**Comment by Laczen** [comment]
> Still misses the point of device capabilities.

Capabilities are indeed not a part of the proposal (they could be added if deemed required), the reasons for not including them are:
1. Adding a capability means that it is described and is put into use by the subsystem using it, at the moment I couldn't find any capability that is not described by the proposals lack of erase and write routines.
2. Adding a capability description is meant to be used by future expansion possibilities and this might influence how capabilities are added: a set of flags might not be sufficient to describe a capability like switching a operation mode that might have influence on the set of flags.
3. Adding capabilities will add to code size.

But as said, once it is known how to best add the capabilities, I see no problem in extending the proposal with capabilities support. It could be made specific to the backend (adding it to `eeprom_store` or `flash_store`), or more general by adding it to `nvmp_info`.

**Comment by Laczen** [comment]
@d3zd3z , nvmp solves the issues of https://github.com/mcu-tools/mcuboot/issues/1823. It also provides a solution for the problem when internal flash erase block size is smaller than external flash erase block size (reported for stm32 devices with 2kB erase blocks).

**Comment by de-nordic** [comment]
> @d3zd3z , nvmp solves the issues of [mcu-tools/mcuboot#1823](https://github.com/mcu-tools/mcuboot/issues/1823). It also provides a solution for the problem when internal flash erase block size is smaller than external flash erase block size (reported for stm32 devices with 2kB erase blocks).

Another thing that has been misunderstood: MCUboot wants non-system specific solution, so that it would not have to directly deal with system APIs. If this PR "solves" the MCUboot problem, it should be proposed in MCUboot, not in Zephyr.

**Comment by Laczen** [comment]
> > @d3zd3z , nvmp solves the issues of [mcu-tools/mcuboot#1823](https://github.com/mcu-tools/mcuboot/issues/1823). It also provides a solution for the problem when internal flash erase block size is smaller than external flash erase block size (reported for stm32 devices with 2kB erase blocks).
> 
> Another thing that has been misunderstood: MCUboot wants non-system specific solution, so that it would not have to directly deal with system APIs. If this PR "solves" the MCUboot problem, it should be proposed in MCUboot, not in Zephyr.

You are reading a lot of things that are not written. The PR proposes a replacement for flash_map that has advantages for zephyr and allows zephyr to utilize devices that do not require an erase. At the same time the PR also provides a solution to the issues that have been raised by @d3zd3z in mcuboot.

**Comment by de-nordic** [comment]
> You are reading a lot of things that are not written.

@Laczen I have proposed to be taken into consideration, described and discussed the feature on a meeting the issue has been created after. I quite understand what I have meant, you better tone down on telling publicly what I am doing or not doing.

**Comment by Laczen** [comment]
> > You are reading a lot of things that are not written.
> 
> @Laczen I have proposed the feature to be taken into consideration, described and discussed it on a meeting the issue has been created after. I quite understand what I have meant, you better tone down on telling publicly what I am doing or not doing.

Once again you are reading things that I have not written.
You make a remark "another thing that has been misunderstood...", this implies that I'm somehow influencing this, I am not. So you are reading things that I have not written.
Now you are implying that I'm stating that you don't understand what was written in the mcuboot issue, I am not,

Stick to facts, does the PR provide a solution to the issues or not. If it does accept it, if it doesn't comment that it doesn't.

**Comment by Laczen** [comment]
To allow maximum reuse of existing code (e.g. allow defining a rram/mram/fram device as a spi-nor) it is possible to define a compatible `zephyr,flash-no-erase-nvmp-fixed-partitions` that would call the flash drivers for read and write but omit the definition of `nvmp_flash_erase()` from `nvmp_info`.

**Pull request closed without merging**
