### PR TITLE
drivers: spi: nrfx: Add support for new instances

### PR DESCRIPTION
**Pull request by awojasinski**
Prepare nrfx SPIM driver for new instances. That includes:
- driver instances definition
- Konfig symbols for enabled SPIM nodes with SPIM compatible
- translation layer from Zephyr's Kconfig symbols to nrfx symbols

### CODE REVIEW

**Review by gmarull — APPROVED** [review]
we really need to stop doing this in nRF drivers. cc: @carlescufi

**Review by hubertmis — APPROVED** [review]
I wish instead of all these code repetitions we could instantiate drivers using existing device tree macros.

**Comment by awojasinski-nordicsemi** [comment]
@gmarull @hubertmis there was a discussion about that and I keep that in mind. I'll try to come up with some solution to that

**Review by anangl — APPROVED** [review]

**Review by anangl — COMMENTED** [review]
The order of commits is wrong. f4e2a2212f96d575b68cd4c2cf1b5c0e1c7be8a8 references Kconfig options that are not yet defined.

**Pull request merged**
