### PR TITLE
Various RISC-V FPU context switching fixes

### LINKED ISSUE #54208: Various RISC-V FPU context switching issues
Several issues are present in the current FPU switching code for RISC-V.
Fixes are provided in PR #54207 as well as a corresponding CI test.

### PR DESCRIPTION
**Pull request by npitre**
Fix various issues with the new FPU context switching code on RISC-V
and provide a comprehensive test for that code.

Fixed issues are:

- IRQ state for the interrupted context corresponds to the PIE bit not
  the IE bit.

- Restoring the saved FPU state should clear the entire field before
  or'ing wanted bits in.

- Properly trap access to the fcsr, frm and fflags registers.

- Work around platforms that don't capture faulting instructions in mtval.
  This is notably the case on QEMU with the previously mentioned registers.

Fixes #54208

### CODE REVIEW

**Review by fkokosinski — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]

**Review by edersondisouza — APPROVED** [review]

**Comment by pottendo** [comment]
Hi fellow hackers,
seeing some improvements merged, I gave those a try. My testcase still fails, so I tried the new test-case. There seems to be something seriously wrong with my port:
```
--=============== SoC ==================--
CPU:		VexRiscv SMP-LINUX @ 80MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		48KiB
SRAM:		16KiB
MAIN-RAM:	16384KiB 

--========== Initialization ============--
Memtest at 0x40000000 (2.0MiB)...
  Write: 0x40000000-0x40200000 2.0MiB
   Read: 0x40000000-0x40200000 2.0MiB
Memtest OK
Memspeed at 0x40000000 (Sequential, 2.0MiB)...
  Write speed: 21.8MiB/s
   Read speed: 13.0MiB/s

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
[LITEX-TERM] Received firmware download request from the device.
[LITEX-TERM] Uploading build/zephyr/zephyr.bin to 0x40000000 (100092 bytes)...
[LITEX-TERM] Upload calibration... (inter-frame: 10.00us, length: 64)
[LITEX-TERM] Upload complete (58.6KB/s).
[LITEX-TERM] Booting the device.
[LITEX-TERM] Done.
Executing booted program at 0x40000000

--============= Liftoff! ===============--
*** Booting Zephyr OS build v3.3.0-rc1-51-ga359d18a496f ***
Running TESTSUITE riscv_fpu_sharing
===================================================================
START - test_basics

    Assertion failed at WEST_TOPDIR-pottendo/tests/arch/riscv/fpu_sharing/src/main.c:52: riscv_fpu_sharing_test_basics: fpu_is_off() is false

 FAIL - test_basics in 0.005 seconds
===================================================================
START - test_fp_insn_trap

    Assertion failed at WEST_TOPDIR-pottendo/tests/arch/riscv/fpu_sharing/src/main.c:370: riscv_fpu_sharing_test_fp_insn_trap: fpu_is_off() is false

 FAIL - test_fp_insn_trap in 0.005 seconds
===================================================================
START - test_multi_thread_interaction

    Assertion failed at WEST_TOPDIR-pottendo/tests/arch/riscv/fpu_sharing/src/main.c:90: new_thread_check: (fpu_is_clean() is false)
FPU not clean after read
 FAIL - test_multi_thread_interaction in 0.006 seconds
===================================================================
START - test_thread_vs_exc_interaction

    Assertion failed at WEST_TOPDIR-pottendo/tests/arch/riscv/fpu_sharing/src/main.c:302: riscv_fpu_sharing_test_thread_vs_exc_interaction: fpu_is_dirty() is false

 FAIL - test_thread_vs_exc_interaction in 0.006 seconds
===================================================================
TESTSUITE riscv_fpu_sharing failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [riscv_fpu_sharing]: pass = 0, fail = 4, skip = 0, total = 4 duration = 0.022 seconds
 - FAIL - [riscv_fpu_sharing.test_basics] duration = 0.005 seconds
 - FAIL - [riscv_fpu_sharing.test_fp_insn_trap] duration = 0.005 seconds
 - FAIL - [riscv_fpu_sharing.test_multi_thread_interaction] duration = 0.006 seconds
 - FAIL - [riscv_fpu_sharing.test_thread_vs_exc_interaction] duration = 0.006 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED
```
It seems that the `mstatus` is not behaving as expected, or the respective bits are organized differently on this CPU (VexRiscV-smp). 
I did the Zephyr port to this [board](https://github.com/pottendo/zephyr-pottendo/tree/main/boards/riscv/orangecart), so maybe I missed some specifics for FPU: See [here](https://github.com/pottendo/zephyr-pottendo) for the dts + board configs. 
The board `orangecart_fpu' is the one which uses the FPU.
Let me know if I can support further.

bye, pottendo

**Comment by npitre** [comment]
Please let's move this conversation to issue #54205.

**Comment by carlocaione** [comment]
also it is really not nice to maintainers and project asking for support on downstream only boards and ports.

**Comment by pottendo** [comment]
> also it is really not nice to maintainers and project asking for support on downstream only boards and ports.

Hi,
I apologize if I violated some rules; not sure what I should have done differently though.
My intention was to report a potential regression maybe hitting others as well. For me it wasn't obvious that this is board and/or port specific.
regards, pottendo

**Pull request merged**
