### PR TITLE
boards: frdm_k22f: Fix SPI CS pinmux setting / remove bogus pin setting

### PR DESCRIPTION
**Pull request by galak**
The chipselect is wired to PTC4 and is SPI0_PCS0.  Fix pinmux.c and
board docs to correctly reflect this.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
I'm not sure why we are setting PTC11 as GPIO for SPI0??

**Comment by bfrog** [comment]
> I'm not sure why we are setting PTC11 as GPIO for SPI0??

I don't recall why this is there, probably a test application I created needed an enable pin and I forgot to remove it

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
No problem removing the spurious PTC11 setting, but the original chip select settings were correct. This is the Arduino header:
image

**Comment by galak** [comment]
> No problem removing the spurious PTC11 setting, but the original chip select settings were correct. This is the Arduino header:

So the Arduino header has SPI1 connected to it.  SPI0 is what is getting configured in the board/dts/pinmux code.

**Review by MaureenHelm — APPROVED** [review]
Ok, the SPI chip select change does make sense for the SD card. Sorry for the noise.

**Pull request merged**
