### PR TITLE
STM32 generic LL headers for further peripherals

### PR DESCRIPTION
**Pull request by martinjaeger**
Based on @gmarull's work in #28894, this PR adds support for the generic LL headers for a all other drivers.

I ran lots of sanitychecks for `tests/drivers`, `tests/subsys` and `samples/drivers` locally, so I hope I didn't forget to include the new LL headers anywhere.

The remaining content of `soc.h` is the MCU-specific register map file (e.g. `stm32l1xx.h`) and the generated devicetree including STM-specific macros.

### CODE REVIEW

**Review by gmarull — APPROVED** [review]
LGTM, great job!

**Review by erwango — CHANGES_REQUESTED** [review]
Great work but flash and i2s miss an update.
(i2s functions are to be found in within spi api)

**Review by loicpoulain — APPROVED** [review]

**Comment by martinjaeger** [comment]
> Great work but flash and i2s miss an update.
> (i2s functions are to be found in within spi api)

Good spot. Should be fixed now. Added I2S before SPI and the flash before clock control so that bi-secting does not break for the intermediate commits.

How did you actually find these issues? Is there any way to run sanitycheck only for STM32?
```
./scripts/sanitycheck -T tests/drivers --all --build-only
./scripts/sanitycheck -T samples/drivers --all --build-only
```
would take days on my machine, so I ran several tests manually, but must have missed flash and I2C.

On a related note: If a driver uses HAL instead of LL, how are the hal header files included? I know that the HAL can be activated with Kconfig `select USE_STM32_HAL_FOO`. But I can only see how this add the .c files to the build. The .h files don't seem to be included anywhere.

**Comment by erwango** [comment]
> How did you actually find these issues? Is there any way to run sanitycheck only for STM32?

I've a dedicated machine with specific scripts to run sanitycheck on STM32 based boards.
This is a powerful machine, but this is indeed pretty long to run (took 5 hours to build samples/ and tests/drivers all STM32 based boards).

> On a related note: If a driver uses HAL instead of LL, how are the hal header files included? I know that the HAL can be activated with Kconfig select USE_STM32_HAL_FOO. But I can only see how this add the .c files to the build. The .h files don't seem to be included anywhere.

On HAL side, there's the dedicated `stm32cube/stm32l4xx/drivers/include/stm32l4xx_hal_conf.h` file used to include HAL headers. The equivalent doesn't exist for LL API.

**Comment by gmarull** [comment]
> > On a related note: If a driver uses HAL instead of LL, how are the hal header files included? I know that the HAL can be activated with Kconfig select USE_STM32_HAL_FOO. But I can only see how this add the .c files to the build. The .h files don't seem to be included anywhere.
> 
> On HAL side, there's the dedicated `stm32cube/stm32l4xx/drivers/include/stm32l4xx_hal_conf.h` file used to include HAL headers. The equivalent doesn't exist for LL API.

If I'm not wrong the reason LL does not provide something similar is because it is mostly built upon static inline functions, so a global header would *paste* the whole LL API in each translation unit. On the other hand HAL headers contain mainly declarations.

**Comment by erwango** [comment]
@martinjaeger only one issue remaining: `subsys/disk/disk_access_stm32_sdmmc.c`.
(You can test it with `sanitycheck -T samples/subsys/fs/fat_fs -p stm32l496g_disco`)
Sorry for late finding, it was burried into the other issues at first execution.

**Comment by martinjaeger** [comment]
> @martinjaeger only one issue remaining: `subsys/disk/disk_access_stm32_sdmmc.c`.
> (You can test it with `sanitycheck -T samples/subsys/fs/fat_fs -p stm32l496g_disco`)
> Sorry for late finding, it was burried into the other issues at first execution.

No worries. Thanks for running these extensive build tests. I fixed it and again placed the commit before clock_control, which previously included several commonly used header files.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
> I fixed it and again placed the commit before clock_control, which previously included several commonly used header files.

Txs, it is all good now! Txs for the PR

**Pull request merged**
