### PR TITLE
boards: nxp: imx95_evk: add M7 DDR board variant

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Add DDR variant of the i.MX95 EVK board (M7 core). Using this variant, one can run Zephyr from DDR instead of ITCM/DTCM as it's the case for the M7 "base" board.

### CODE REVIEW

**Review by iuliana-prodan — DISMISSED** [review]
LGTM

**Comment by yangbolu1991** [comment]
@LaurentiuM1234 ,
The PR looks good to me:)

There is another PR specified board targets in doc.
https://github.com/zephyrproject-rtos/zephyr/pull/78276

Let's see which one is merged first. The the other will need rebase to update doc about board target.
Thanks.

**Comment by JiafeiPan** [comment]
Update board document to add this variant?

**Comment by LaurentiuM1234** [comment]
> Update board document to add this variant?

done

**Review by JiafeiPan — DISMISSED** [review]

**Review by dbaluta — DISMISSED** [review]

**Comment by kartben** [comment]
needs rebase

**Comment by LaurentiuM1234** [comment]
> needs rebase

done

**Review by dbaluta — APPROVED** [review]

**Review by JiafeiPan — APPROVED** [review]

**Review by yangbolu1991 — APPROVED** [review]

**Pull request merged**
