### PR TITLE
dsi_mcux_2l changes

### PR DESCRIPTION
**Pull request by mjchen0**
CL1: use pxfmt to select SMARTDMA slot instead of hardcoding it to RGB565/RGB565_SWAP. This allows support for displays that use pxfmt RGB888.

CL2: allow msg to select high speed mode transfers instead of hardcoding some messages to use high speed mode and some to use low power mode

### CODE REVIEW

**Comment by danieldegrasse** [comment]
Hi @mjchen0, thank you for the changes- can you also set the `MCUX_DSI_2L_USE_HIGH_SPEED` bit in the `rm67162_write_fb` function within `display_rm67162.c`? That way we preserve the existing behavior for that display controller when not using SMARTDMA for transfers.

**Comment by mjchen0** [comment]
> Hi @mjchen0, thank you for the changes- can you also set the `MCUX_DSI_2L_USE_HIGH_SPEED` bit in the `rm67162_write_fb` function within `display_rm67162.c`? That way we preserve the existing behavior for that display controller when not using SMARTDMA for transfers.

Okay, I updated the commit.

**Comment by mjchen0** [comment]
> Hi @mjchen0- Apologies for not noticing this earlier. Since low power mode is something defined by the MIPI spec, we already have a flag available in the MIPI driver header:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/fdaba20b2cef812d611d2d2f665d43c9f20c2833/include/zephyr/drivers/mipi_dsi.h#L204
> 
> We should configure the `dsi_mcux_2l` driver to use low power mode for transfers whenever this flag is set, like the STM32 DSI driver does, instead of using a hardware specific flag
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/fdaba20b2cef812d611d2d2f665d43c9f20c2833/drivers/mipi_dsi/dsi_stm32.c#L274

I had found that flag earlier, but the documentation wasn't clear how it was intended to be used.
I read the stm code and how it used that flag, but it's different than what I wanted. The flag seemed to be to allow transfers withing a DPI video transfer (which is HS) to send cmd in LPM. It's a very special case that seems specific to the stm MIPI controller.

We could overload the meaning for the nxp MIPI driver as you suggested, but it would also prevent a user to make full use of the NXP MIPI controller capability of doing high speed or low power on a transfer/by/transfer basis, since that flag is for the entire device. There could be cases where the user wants to do all init in low power, but then switch to high speed for subsequent transfers.

**Comment by mjchen0** [comment]
> > I had found that flag earlier, but the documentation wasn't clear how it was intended to be used.
> > I read the stm code and how it used that flag, but it's different than what I wanted. The flag seemed to be to allow transfers withing a DPI video transfer (which is HS) to send cmd in LPM. It's a very special case that seems specific to the stm MIPI controller.
> 
> Thanks for the clarification here- the primary reasoning I have for wanting to make this generic is that other MIPI IP seems to support low power mode transfers (such as the RT1170 MIPI DSI block). Perhaps we can make the message flag generic, since Linux seems to have one for sending a message in low power mode: https://elixir.bootlin.com/linux/latest/source/include/drm/drm_mipi_dsi.h#L21?

My initial implementation was to make it a general flag in Zephyr's mipi_dsi.h, but I thought it might be easier to get a more limited change approved. I can change my patch to make it a flag in the common mipi_dsi.h msg transfer struct instead of limited only to dsi_mcux_2l.

**Review by danieldegrasse — APPROVED** [review]
Thanks for these changes- I appreciate you making the flag generic

**Comment by danieldegrasse** [comment]
@gmarull, FYI, since this is touching the MIPI DSI driver headers you may want to take a look. I think this makes sense though, since sending a message in low power mode is a feature supported by multiple DSI controllers (and Linux already supports a flag like the one this PR adds)

**Review by gmarull — APPROVED** [review]
mipi dsi flag lgtm

**Pull request merged**
