### PR TITLE
[Backport v2.2] Bluetooth: controller: Added support for vendor ticker nodes

### PR DESCRIPTION
**Pull request by mtpr-ot**
Backport of #25066

### CODE REVIEW

**Comment by jhedberg** [comment]
Which PR is this a backport of? (please add the reference to the description) It also needs a corresponding issue to be accepted into v2.2-branch.

**Comment by jhedberg** [comment]
@mped-oticon I succeeded in finding the master branch PR and added the reference myself

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by mtpr-ot** [comment]
Closed and re-opened to trigger CI.

**Comment by carlescufi** [comment]
@cvinayak could you please review this?

**Review by thoh-ot — APPROVED** [review]

**Comment by jhedberg** [comment]
@cvinayak this is still waiting for your review

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
