### PR TITLE
Raspberry Pi Pico RTC Driver

### PR DESCRIPTION
**Pull request by andrei-edward-popa**
I have added driver support for RTC for Raspberry Pi Pico. Driver was tested using samples/drivers/counter/alarm sample and all tests from tests/drivers/counter/counter_basic_api passed.

### CODE REVIEW

**Comment by andrei-edward-popa** [comment]
I understand that the failing checks are related to stm32, so I cannot solve them.

**Comment by nordicjm** [comment]
This would be a good candidate for using https://github.com/zephyrproject-rtos/zephyr/pull/41287

**Comment by andrei-edward-popa** [comment]
> This would be a good candidate for using #41287

Yes, but for now I think that this implementation using the counter interface is good for users. I don't know when the RTC interface will be upstreamed and it seems that it is not merged with the main branch to start an implementation using it.

**Comment by andrei-edward-popa** [comment]
@yonsch Hi! Can you take a look at this driver?

**Comment by yonsch** [comment]
This looks good generally, but if there's an RTC API change coming soon I think we should wait. I'll see what I can do with that other PR.

**Comment by andrei-edward-popa** [comment]
> This looks good generally, but if there's an RTC API change coming soon I think we should wait. I'll see what I can do with that other PR.

Okay, thank you! :)

**Comment by yonsch** [comment]
Marking this as draft until Zephyr gets an RTC driver

**Comment by soburi** [comment]
@andrei-edward-popa 
Finally https://github.com/zephyrproject-rtos/zephyr/pull/52618 has been merged!

**Comment by nordicjm** [comment]
@andrei-edward-popa any plans to rework this using the RTC API?

**Comment by andrei-edward-popa** [comment]
> @andrei-edward-popa any plans to rework this using the RTC API?

**Comment by andrei-edward-popa** [comment]
> @andrei-edward-popa any plans to rework this using the RTC API?

Yes, I will start to work on it soon.

**Comment by andrei-edward-popa** [comment]
For now this is a draft, when it will be ready to be reviewed I will ping all the people that are responsible for RTC and Raspberry Pi Pico.

**Pull request closed without merging**
