### PR TITLE
Scripts: Support Application's Kconfig tree

### PR DESCRIPTION
**Pull request by jli157**
This PR is trying to address the issue #6623, implementing a hierarchy Kconfig tree for an application. And as an example, the test `tests/drivers/spi/spi_loopback/` was refactored to demonstrate enabling application's Kconfig tree.

### CODE REVIEW

**Comment by carlescufi** [comment]
I wonder why this is necessary if MCUboot is already doing this as a Zephyr application: 

https://github.com/runtimeco/mcuboot/blob/master/boot/zephyr/Kconfig

**Comment by jli157** [comment]
Similar to the test `tests/drivers/spi/spi_loopback/`, mcuboot has only one layer of Kconfig, which is fine. However, if an application has multiple layers of Kconfig files, its top `Kconfig` needs to load them, thus needs to know the source directory of next Kconfig. Without being fed with the environment `${APPLICATION_BASE}`, the command `make menuconfig` will fail.  You can take a look at my changes on the test application.

**Comment by carlescufi** [comment]
@jli157 understood, thanks for the explanation

**Review by carlescufi — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
I would prefer to have this demonstrated in a dedicated test with other Kconfig related features that can be tested. This here changes the structure of an unrelated test

**Comment by jli157** [comment]
Okay, will make a new test. What kind of other Kconfig features would be implemented in that test?

**Comment by SebastianBoe** [comment]
Another approach to solve the same problem would be to wait for the latest kconfiglib.py to be supported (https://github.com/zephyrproject-rtos/zephyr/pull/6569) and then do:

_rsource_ "src/Kconfig"

from the application root Kconfig. E.g. from tests/drivers/spi/spi_loopback/Kconfig

This works because 'rsource' is a new extention to the kconfiglib language that does uses relative paths. It will be supported when (if) #6569 is merged.

I like this approach over the current proposal because you don't have to document and introduce the new keyword/special name APPLICATION_BASE. (We can do more with fewer concepts)

**Comment by jli157** [comment]
@SebastianBoe The feature looks very nice to have. Looking forward to trying it!

**Comment by carlescufi** [comment]
CC @ulfalizer

**Comment by jli157** [comment]
@SebastianBoe has the feature provided by PR #6569 already been implemented and merged? I need this feature for one of my projects. Thank you!

**Comment by ulfalizer** [comment]
@jli157 
It will be safe to start using `rsource` once https://github.com/zephyrproject-rtos/zephyr/pull/7293 gets in. The blocker is that the C tools don't have it.

I'm finishing up the search feature mentioned at the end of that PR now, so should be in within a few days at most I think.

**Comment by SebastianBoe** [comment]
@jli157 : Please close this PR after verifying that using rsource supports this use-case as expected.

**Comment by jli157** [comment]
Is there an example that I can refer to? Thank you!

**Comment by SebastianBoe** [comment]
rsource "relative/path/Kconfig"

is expected to work out-of-the-box

**Comment by carlescufi** [comment]
@jli157 please let us know if `rsource` fixes the problem you had now that support for it has landed on master. This is important feedback for us.

**Comment by jli157** [comment]
Verified and it works as expected. I have my Kconfig in my project to combine both the config tree of my project and Zephyr's together by the following code:

```
config ZEPHYR_BASE
        string
        option env="ZEPHYR_BASE"

rsource "src/Kconfig"

rsource "$ZEPHYR_BASE/Kconfig.zephyr"
```

**Comment by carlescufi** [comment]
@jli157 thank you for confirming that this fixes your problem.

**Pull request closed without merging**
