### PR TITLE
Enabling DMA on stm32f3 series

### PR DESCRIPTION
**Pull request by ikmdani**
These commits enable DMA on STM32F3 series.
This has been tested with `tests/drivers/dma/chan_blen_transfer` and `tests/drivers/dma/loop_transfer` on stm32f3_disco platform and is working as expected.

`tests/drivers/dma/loop_transfer`

```
*** Booting Zephyr OS build zephyr-v2.6.0-1333-g66eae393d634  ***
Running test suite dma_m2m_loop_test
===================================================================
START - test_dma_m2m_loop
DMA memory to memory transfer started on DMA_1
Preparing DMA Controller
this platform do not support the dma channel
Starting the transfer on channel 4 and waiting for 1 second
Each RX buffer should contain the full TX buffer string.
RX data Loop 0: The quick brown fox jumps over the lazy dog
RX data Loop 1: The quick brown fox jumps over the lazy dog
RX data Loop 2: The quick brown fox jumps over the lazy dog
RX data Loop 3: The quick brown fox jumps over the lazy dog
RX data Loop 4: The quick brown fox jumps over the lazy dog
Finished: DMA
 PASS - test_dma_m2m_loop in 1.49 seconds
===================================================================
Test suite dma_m2m_loop_test succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

`tests/drivers/dma/chan_blen_transfer`

```
*** Booting Zephyr OS build zephyr-v2.6.0-1333-g66eae393d634  ***
Running test suite dma_m2m_test
===================================================================
START - test_dma_m2m_chan0_burst8
Preparing DMA Controller: Chan_ID=4, BURST_LEN=1
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan0_burst8 in 2.13 seconds
===================================================================
START - test_dma_m2m_chan1_burst8
Preparing DMA Controller: Chan_ID=2, BURST_LEN=1
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan1_burst8 in 2.13 seconds
===================================================================
START - test_dma_m2m_chan0_burst16
Preparing DMA Controller: Chan_ID=4, BURST_LEN=2
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan0_burst16 in 2.13 seconds
===================================================================
START - test_dma_m2m_chan1_burst16
Preparing DMA Controller: Chan_ID=2, BURST_LEN=2
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan1_burst16 in 2.13 seconds
===================================================================
Test suite dma_m2m_test succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

### CODE REVIEW

**Comment by ikmdani** [comment]
@erwango @FRASTM for your review.

**Review by FRASTM — COMMENTED** [review]
Commit 4ee9bc4433e7e0adf8243869afc3ad0907ea4761 : this part could be set in  a `tests/drivers/dma/chan_blen_transfer/boards/stm32f3_disco.overlay`  and `tests/drivers/dma/loop_transfer/boards/stm32f3_disco.overlay`

**Comment by FRASTM** [comment]
I have fixed the error on _buildkite/zephyr — Build  failed_ with the https://github.com/zephyrproject-rtos/zephyr/pull/37165

**Comment by ikmdani** [comment]
> I have fixed the error on _buildkite/zephyr — Build failed_ with the #37165

Looks like below failures are still present.

```
3 failures:

tests/drivers/dma/chan_blen_transfer/drivers.dma in nucleo_f070rb:tests/drivers/dma/chan_blen_transfer/drivers.dma
tests/drivers/dma/chan_blen_transfer/drivers.dma.interactive in nucleo_f070rb:tests/drivers/dma/chan_blen_transfer/drivers.dma
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer in nucleo_f070rb:tests/drivers/dma/loop_transfer/drivers.dma
```

**Comment by erwango** [comment]
> > I have fixed the error on _buildkite/zephyr — Build failed_ with the #37165
> 
> Looks like below failures are still present.

@ikmdani #37165 is not merged yet. You can help to fasten the merge by adding your review.

**Comment by ikmdani** [comment]
> It seems better now enable the dma with
> 
> ```
> &dma1 {
> 	status = "okay";
> };
> ```
> 
> directly in the
> `./boards/arm/stm32f0_disco/stm32f0_disco.dts`instead of adding a overlay in the testcase. Just keep the .conf with the channel configuration.

F0 DMA seem to be different from other series and has build issues. It is better to raise another PR for F0 DMA.

**Comment by FRASTM** [comment]
yes for the f0 refer to https://github.com/zephyrproject-rtos/zephyr/pull/37169
This PR is for F3 so expecting ./boards/arm/stm32f3_disco/**stm32f3_disco.dts** 
instead of adding a overlay in the testcase. Just keep the .conf with the

**Comment by FRASTM** [comment]
Please @ikmdani rebase since the https://github.com/zephyrproject-rtos/zephyr/pull/37165 is merged

**Review by FRASTM — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
