### PR TITLE
samples: chre: CI fixes

### PR DESCRIPTION
**Pull request by fabiobaltieri**
CHRE CI fixes:
- use minimal logging to stop depending on the deferred log buffer size
- exclude leon3 from the test
- missing linker section from intel_adsp cavs

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
The m0 run can be fixed by increasing the log buffer size to 256 bytes. I don't think it would add much anyway so I'd say let's just exclude it. Not too sure about the leon3, fails with `tt = 0x07, mem_address_not_aligned`, this is the location I got for PC:

```
$ addr2line -e build/zephyr/zephyr.elf  40007330
zephyrproject/modules/lib/chre/core/event_loop.cc:497
```

Not too sure where to go from there though but probably not worth keeping the CI broken for it.

**Review by stephanosio — COMMENTED** [review]
> failing on qemu_cortex_m0 because that specific platform reduces the log buffer to 128 bytes

should we address that by setting the `min_ram:` filter since the fundamental issue is that there is not enough RAM available on `qemu_cortex_m0`?

> on qemu_leon3 for some address alignment issue

this sounds like a real bug -- before filtering this platform out, a bug should be filed.

**Comment by fabiobaltieri** [comment]
> > failing on qemu_cortex_m0 because that specific platform reduces the log buffer to 128 bytes
> 
> should we address that by setting the `min_ram:` filter since the fundamental issue is that there is not enough RAM available on `qemu_cortex_m0`?

But it does have enough ram, it's just not using enough for the log. Actually how about this: we can set it to use CONFIG_LOG_MODE_MINIMAL so it does not depend on the log buffer size. Let me rework this PR.

> 
> > on qemu_leon3 for some address alignment issue
> 
> this sounds like a real bug -- before filtering this platform out, a bug should be filed.

Yeah will file one

**Comment by fabiobaltieri** [comment]
Filed https://github.com/zephyrproject-rtos/zephyr/issues/52513 for leon3.

**Comment by fabiobaltieri** [comment]
Now this fails for `intel_adsp_ace15_mtpm`, linker issue

```
/opt/zephyr-sdk-0.15.0/xtensa-intel_s1000_zephyr-elf/bin/../lib/gcc/xtensa-intel_s1000_zephyr-elf/12.1.0/../../../../xtensa-intel_s1000_zephyr-elf/bin/ld.bfd: warning: orphan section `.unstable_id' from `modules/chre/lib..__modules__lib__chre__platform__zephyr.a(version.cc.obj)' being placed in section `.unstable_id'
```

Something special about that platform linker setup?

**Review by nashif — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
