### PR TITLE
Revert "X86: MMU: PAE boot time page tables."

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Reverts zephyrproject-rtos/zephyr#1534

This PR is breaking the build for some users.

### CODE REVIEW

**Comment by inakypg** [comment]
I confirm disabling CONFIG_X86_PAE_MODE in boards/x86/qemu_x86_defconfig makes Hello World pass in QEMU/x86

**Comment by galak** [comment]
Curious how this ended up as a branch on the master tree.

**Comment by andrewboie** [comment]
@galak I pushed the "revert" button on the original PR when @inakypg notified me that some build machines were failing. This is what Github generated.

**Comment by andrewboie** [comment]
Closing this in favor of #4527

**Comment by galak** [comment]
> @galak I pushed the "revert" button on the original PR when @inakypg notified me that some build machines were failing. This is what Github generated.

thanks, was wondering if it was something like that.

**Comment by AdithyaBaglody** [comment]
A false positive.Thus recreating the required patch. #4548

**Pull request closed without merging**
