### PR TITLE
manifest: update hal_nordic revision

### PR DESCRIPTION
**Pull request by jciupis**
This commit updates hal_nordic revision to bring the latest changes in the nRF 802.15.4 radio driver.

### CODE REVIEW

**Comment by jciupis** [comment]
CC: @fgrandel. The [PR](https://github.com/zephyrproject-rtos/hal_nordic/pull/136) contains [API](https://github.com/zephyrproject-rtos/hal_nordic/pull/136/files?diff=unified&w=0#diff-a68f78a5a708228e4640963ab8cb36bbc3c173379471e9b11564bb2f050f0d29R426-R454) created to address suggestions from https://github.com/zephyrproject-rtos/zephyr/issues/59245

**Comment by fgrandel** [comment]
@jciupis I'm currently at ZDS and also caught up in some other TSCH stuff, so cannot work on PRs - expect my part of it to arrive in two or three weeks latest. Hope that's ok?

**Comment by jciupis** [comment]
> Hope that's ok?

Sure, I just wanted to unblock you and avoid the need to align [nRF5 ieee802154](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/ieee802154/ieee802154_nrf5.c) code twice.

**Comment by carlescufi** [comment]
@jciupis please rebase and add a SHA. CC @rlubos

**Comment by jciupis** [comment]
@carlescufi done.

**Review by rlubos — APPROVED** [review]

**Review by edmont — APPROVED** [review]

**Pull request closed without merging**
