### PR TITLE
picolibc: Use Zephyr native errno for non-TLS targets

### PR DESCRIPTION
**Pull request by keith-packard**
I added all of the necessary infra to picolibc to allow use of z_errno() a long time ago and somehow forgot to hook it up in zephyr. This moves the picolibc commit to bring in the cmake bits there for this; that's where the bulk of the changes live. This series mostly just enables tests that make sure it works.

### CODE REVIEW

**Comment by stephanosio** [comment]
@keith-packard It seems the picolibc commit currently referenced in the `west.yml` (https://github.com/zephyrproject-rtos/picolibc/commit/4f8076520240192be284843a114c92853e29bbbc) is not part of any branches in the `zephyrproject-rtos/picolibc` repository. Are you going to be using the `zephyr` branch as the "main" branch in that repository from now on? (one that will never be force-pushed to)

**Review by andyross — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by keith-packard** [comment]
> @keith-packard It seems the picolibc commit currently referenced in the `west.yml` ([zephyrproject-rtos/picolibc@4f80765](https://github.com/zephyrproject-rtos/picolibc/commit/4f8076520240192be284843a114c92853e29bbbc)) is not part of any branches in the `zephyrproject-rtos/picolibc` repository. Are you going to be using the `zephyr` branch as the "main" branch in that repository from now on? (one that will never be force-pushed to)

I can't appear to control the 'main' branch at all, so I've been putting changes on the zephyr branch instead. What I want to be able to do is move the 'main' branch in the zephyr repo to a particular 'main' branch point in the upstream repo as changes are merged and tested there, then I'd be able to use commits along that main branch for the west.yml file.

**Comment by stephanosio** [comment]
> I can't appear to control the 'main' branch at all, so I've been putting changes on the zephyr branch instead. What I want to be able to do is move the 'main' branch in the zephyr repo to a particular 'main' branch point in the upstream repo as changes are merged and tested there, then I'd be able to use commits along that main branch for the west.yml file.

@keith-packard the main branch had a branch protection rule preventing that. I have modified it to allow fast-forward pushes, so you should be able to fast-forward the main branch in the fork repo now. Please let me know if you encounter any other issues.

**Review by carlescufi — APPROVED** [review]

**Comment by keith-packard** [comment]
> @keith-packard the main branch had a branch protection rule preventing that. I have modified it to allow fast-forward pushes, so you should be able to fast-forward the main branch in the fork repo now. Please let me know if you encounter any other issues.

Thanks, I just gave this a try; the 'main' branch is now set to the current west.yml point.

**Pull request merged**
