### PR TITLE
drivers: can: deprecate the can_attach_workq() API call

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Deprecate the can_attach_workq() API call.
    
This API is limited in its functionality (it does not work with userspace, it uses one common buffer size for all work queue instances).
    
Similar functionality can easily be implemented using the can_attach_msgq() API along with the generic triggered work API (e.g. using k_work_poll_submit()).
    
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by alexanderwachter** [comment]
I would not deprecate it. It is foreseen to make it work with userspace.

**Review by alexanderwachter — CHANGES_REQUESTED** [review]
Do not agree to remove it

**Comment by henrikbrixandersen** [comment]
The CI failure is due to #41255.

**Comment by henrikbrixandersen** [comment]
> I would not deprecate it. It is foreseen to make it work with userspace.

The main reason for removing it is that it is a redundant API. The exact same functionality - with added flexibility - can be achieved by using a CAN message queue along with our triggered work APIs, which has the benefit of fitting in with the rest of the standard Zephyr APIs.

In addition, the triggered work approach does not suffer from the limitations of the CAN work queue API.

**Comment by carlescufi** [comment]
> I firmly believe that driver subsystems should not wrap functionality provided by other APIs (here, the k_work_q APIs) unless absolutely needed, as this breaks the modularity and interoperability of our APIs. Here, wrapping is not needed and does not provide any gain (rather the opposite considering the limitations of the can_attach_workq() API).

I very much agree with this statement. Is there a particular reason you want to keep this API @alexanderwachter? To me it sounds like the arguments brought forward by @henrikbrixandersen make a good case for its deprecation.

**Comment by alexanderwachter** [comment]
@henrikbrixandersen got your point now.
This API is from a time where the triggered work did not exist.
Agree to deprecate. Let's add a scenario with triggered work to the samples!

**Review by alexanderwachter — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
