### PR TITLE
modules/picolibc: Include clang+cmake and old GCC changes

### LINKED ISSUE #54336: picolibc is incompatible with xcc / xcc-clang toolchains
**Describe the bug**

Compilation of picolibc module for picolibc tests fails with XCC on ADSP platforms. Followup to https://github.com/zephyrproject-rtos/zephyr/issues/54224.

A few of the flags used by GCC to build the picolibc module are not compatible with XCC. Different flags are observed to be not working for different versions of XCC toolchain.

`RI-2021.7-linux (xcc-clang)` + MTL:
```
clang-10: error: unknown argument: '-fno-printf-return-value'
clang-10: warning: optimization flag '-fsignaling-nans' is not supported [-Wignored-optimization-argument]
```

`RG-2017.8-linux (xcc)` + CAVS15, 18, CAVS25:
```
xt-xcc ERROR parsing -frounding-math:  unknown flag
xt-xcc ERROR parsing -fsignaling-nans:  unknown flag
xt-xcc ERROR parsing -fno-stack-protector:  unknown flag
xt-xcc ERROR parsing -Warray-bounds:  unknown flag
xt-xcc ERROR parsing -ftls-model=local-exec:  unknown flag
xt-xcc ERROR parsing -fno-printf-return-value:  unknown flag
```

**To Reproduce**
```
export ZEPHYR_TOOLCHAIN_VARIANT=xcc
west build -p -b intel_adsp_cavs15 -T tests/kernel/common/kernel.common.picolibc
```

**Expected behavior**
Compilation

**Impact**
Annoyance

**Logs and console output**
See above.

**Environment**
 - OS: Ubuntu 20.04
 - Toolchain: XCC / XCC-clang (see above)
 - Recent main

### PR DESCRIPTION
**Pull request by keith-packard**
This updates west.yml to pull a version of picolibc that includes both the patches in #54391 as well as a proposed fix that provides some compatibility with GCC versions before 4.5, such as the GCC based XCC compiler.

Signed-off-by: Keith Packard <keithp@keithp.com>

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54336

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]

**Review by stephanosio — DISMISSED** [review]

**Comment by keith-packard** [comment]
This patch is still under discussion for merging to picolibc; when this feature is merged to picolibc main, I'll remove the DNM tag.

**Comment by keith-packard** [comment]
This now references the picolibc patch which was reviewed and merged upstream.

**Comment by stephanosio** [comment]
There are some failures.

**Comment by keith-packard** [comment]
> There are some failures.

Zephyr and picolibc were both trying to use a macro __deprecated, but picolibc had an argument for the optional message (which old GCC didn't support). Thanks for noticing, let's see if that's fixed now.

**Comment by keith-packard** [comment]
> > There are some failures.
> 
> Zephyr and picolibc were both trying to use a macro __deprecated, but picolibc had an argument for the optional message (which old GCC didn't support). Thanks for noticing, let's see if that's fixed now.

Yup, looks fixed now -- the one remaining failure I'm seeing also on main.

**Comment by keith-packard** [comment]
> Yup, looks fixed now -- the one remaining failure I'm seeing also on main, and that test isn't using picolibc.

And it's transient; re-running the test resolved the issue. Sigh.

**Review by galak — CHANGES_REQUESTED** [review]
Tried this with qemu_x86 w/llvm-14 or llvm-15 on ubuntu and get the following (or some form it):
```
<inline asm>:2:1: error: __getauxval changed binding to STB_GLOBAL
```
when trying:
```
./scripts/twister -p qemu_x86 -T tests/lib/c_lib/
```

branch: https://github.com/galak/zephyr/pull/new/llvm-x86-pico

**Comment by galak** [comment]
> Tried this with qemu_x86 w/llvm-14 or llvm-15 on ubuntu and get the following (or some form it):
> 
> ```
> <inline asm>:2:1: error: __getauxval changed binding to STB_GLOBAL
> ```
> 
> when trying:
> 
> ```
> ./scripts/twister -p qemu_x86 -T tests/lib/c_lib/
> ```
> 
> branch: https://github.com/galak/zephyr/pull/new/llvm-x86-pico

Seems to be related to `__weak_reference` is expanding to:
```
unsigned long getauxval(unsigned long type)
{
 (void) type;
 (*z_errno_wrap()) = 22;
 return 0;
}
__asm__(".weak_reference " "__getauxval");
__asm__(".globl " "__getauxval");
__asm__(".set " "__getauxval" ", " "getauxval");
```

**Comment by keith-packard** [comment]
> Seems to be related to `__weak_reference` is expanding to:
> 
> ```
> unsigned long getauxval(unsigned long type)
> {
>  (void) type;
>  (*z_errno_wrap()) = 22;
>  return 0;
> }
> __asm__(".weak_reference " "__getauxval");
> __asm__(".globl " "__getauxval");
> __asm__(".set " "__getauxval" ", " "getauxval");
> ```

Yeah, newlib (and picolibc by extension) use inline asm for weak references instead of using attributes. I'm working on a picolibc patch to make it use `__attribute__((__weak__, __alias__...))` instead. Seems to fix this, but needs testing.

**Comment by keith-packard** [comment]
> Yeah, newlib (and picolibc by extension) use inline asm for weak references instead of using attributes. I'm working on a picolibc patch to make it use `__attribute__((__weak__, __alias__...))` instead. Seems to fix this, but needs testing.

I've updated this series to pull in picolibc with this fix from upstream.

**Review by stephanosio — DISMISSED** [review]

**Comment by keith-packard** [comment]
Updated past other recent picolibc merge, does not change target manifest revision

**Review by galak — COMMENTED** [review]
Based on TSC conversation today (Mar 15, 2023), please also update the SDK to point at this version of picolibc.

Whenever we update west.yml picolibc, we should also update the SDK to match.

**Comment by keith-packard** [comment]
> Based on TSC conversation today (Mar 15, 2023), please also update the SDK to point at this version of picolibc.
> 
> Whenever we update west.yml picolibc, we should also update the SDK to match.

Yup, been running tests to make sure updating both will work as expected.

**Review by stephanosio — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
