### PR TITLE
Fix sample_basic_disco no LED blinking issue.

### PR DESCRIPTION
**Pull request by overheat**
This sample did not enable gpio driver, so nothing happens after flash it into a board. 
By enabling gpio driver to fix it.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by WilliamGFish** [comment]
This sample works as expected according to the the "Readme.rst" instructions. I have just compiled and run on nRF52 Devkit all was fine.

> This sample should work on board with multiple built-in LEDs without any
> changes, otherwise, the code may need some changes before running on various
> board: set PORT, LED0 and LED1 according to the board's GPIO configuration.

**Comment by overheat** [comment]
@WilliamGFish Thanks for reviewing. Do you mean this demo works fine without my patch? I am afraid that it is not for me, I just update my zephyr code and confirm that we need this patch even on the nRF52 Devkit.

**Comment by WilliamGFish** [comment]
By configuring the GPIO in the conf the disco works.

**Review by WilliamGFish — APPROVED** [review]
Has been tested against nRF52840-PCA10056

**Comment by erwango** [comment]
Affecting back to NRF guys.
Since I'm there: I think GPIO should be part is of default boards configuration (otherwise there is quite little things we can do when not activated). Then if really necessary it can't be disabled for optimization purpose.
So should not be needed to activate in samples.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@erwango agreed with you, `GPIO` should be enabled by default on boards.

**Comment by carlescufi** [comment]
@anangl can you please see why `GPIO` is not enabled by default?

**Comment by erwango** [comment]
Wasn't that merged a bit fast?
Maybe we should raise an issue to clean up samples from GPIO activation (and see quickly which boards do not enable GPIO). This could be done for 1.15

**Comment by anangl** [comment]
@carlescufi @erwango
> @anangl can you please see why `GPIO` is not enabled by default?

I don't see any particular reason for not enabling it, nor recall any direct change in this regard.
However, some time ago the nRF SERIAL driver had a false dependency on the GPIO driver and `select`ed it in Kconfig, effectively making the GPIO driver always enabled, without a possibility to disable it (unless the SERIAL driver itself was disabled). And this dependency was removed, see [this commit](https://github.com/zephyrproject-rtos/zephyr/commit/7c13ba9965338d2bb8ca0d13847e110a5e7fa67d#diff-cb43ddfba4a214d29f2732e7fa1a402c). Perhaps that's why the GPIO driver is now not enabled by default for Nordic boards - previously it was enabled implicitly together with the SERIAL driver.
And I agree, it seems reasonable to enable `GPIO` by default for all boards.

**Comment by carlescufi** [comment]
@anangl would you mind sending a PR?

**Comment by anangl** [comment]
> @anangl would you mind sending a PR?

Sure, I'll prepare one.

**Comment by anangl** [comment]
> @anangl would you mind sending a PR?

Done. #14931

**Pull request merged**
