### PR TITLE
ARC: NSIM: switch to ns16550 UART model 

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
Switch nSIM from custom legacy ARC UART model to ns16550 model which is available in nSIM for more than a year.
That will allow us to use zephyr images build for nSIM on other platforms like HAPS, QEMU, etc...

### CODE REVIEW

**Review by vonhust — APPROVED** [review]
LGTM, @Palmyr3 did you run the necessary example or test?

**Comment by Palmyr3** [comment]
@vonhust, yep, I've run our verification on this - no additional issues.
However I steel need to fix that issue with reference to CONFIG_UART_NSIM (which doesn't exist any more) in linker script. Nice catch by checker :)

**Review by nashif — APPROVED** [review]

**Review by abrodkin — CHANGES_REQUESTED** [review]
Documentation (https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arc/nsim/doc/index.rst) should be fixed-up accordingly too.

Also in the commit message a couple of typos:
 * Switch nSIM from custom ARC UART ~model~~using~ to ns16550 model.
 * images buil**T**

**Review by abrodkin — APPROVED** [review]
LGTM now!

**Pull request merged**
