### PR TITLE
drivers: sensor: bme280: use int math in decode q31 conv

### LINKED ISSUE #77295: bme280: Decoder should use integer math
**Is your enhancement proposal related to a problem? Please describe.**
Converting sensor readings from their native value (typically int16 with some range given by the device) to a q31_t with a different range should be a single integer multiply operation. the Bosch BME280 driver currently uses floating point math.

**Describe the solution you'd like**
Use integer math in the bme280_decoder.c to convert from sensor values to q31_t values.

**Additional context**
Most recently a few drivers ran into this and have been worked on to be single integer multiplies

bme280 code using float math https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/bosch/bme280/bme280_decoder.c#L78 which is not ideal

mmc56x3 doing this with integer multiplication is ideal https://github.com/zephyrproject-rtos/zephyr/pull/77253/files#diff-1675443b623b309c4351cbabdd621d61ec66664f7213f7c525e7409bf4f078ffR100

### PR DESCRIPTION
**Pull request by laurenmurphyx64**
Fix decoder to use integer math when converting readings to Q31. Clang format files.

Fixes #77295

### CODE REVIEW

**Review by teburd — COMMENTED** [review]
Can you split the clang format and int math changes into two commits? Thanks!

**Comment by laurenmurphyx64** [comment]
Finally getting reasonable numbers:

```
*** Booting Zephyr OS build v3.7.0-2432-g9992127cf326 ***                            
Found device "bme280@77", getting sensor data                                        
temp: 23.99975; press: 100.816406; humidity: 48.260742                               
temp: 23.99975; press: 100.816406; humidity: 48.238281                               
temp: 23.109985; press: 100.820312; humidity: 48.283203                              
temp: 23.109985; press: 100.820312; humidity: 48.405273                              
temp: 23.119995; press: 100.820312; humidity: 48.649414 
```

**Review by teburd — COMMENTED** [review]
Math and output looks good!

Ideally would be two commits though, one for the math change and another for the formatting changes.

**Review by yperess — CHANGES_REQUESTED** [review]
Please split clang-format run into separate commit.

**Comment by laurenmurphyx64** [comment]
> Please split clang-format run into separate commit.

@teburd @yperess Sorry, just did that. I could've sworn I did it with the first push, but somehow I squashed the commits... anyways it's done now.

**Review by teburd — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by yperess — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
