### PR TITLE
requirements: add west>=0.6.0

### PR DESCRIPTION
**Pull request by nashif**
west is yet another python package, so lets add it here. This will provide
us with one single file with all python requirements that can be used
during setup and for example for docker images.

### CODE REVIEW

**Review by mbolivar — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]

**Comment by dbkinder** [comment]
If I ask nicely, would you add ``sphinx-tabs`` to requirements.txt too  :)

**Comment by mbolivar** [comment]
@nashif will this make sure we get the latest west in the CI container used for shippable?

I'm about to do west 0.6.1 and I need to make sure it's available for the documentation build, so I can get python docstrings pulled into sphinx.

**Comment by dbkinder** [comment]
@nashif should you add cmake into requirements.txt as well?  The getting started guide mentions using ``pip3 install --user cmake`` to verify you've got the lastest cmake (3.13.1 or higher)

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> @nashif should you add cmake into requirements.txt as well? The getting started guide mentions using `pip3 install --user cmake` to verify you've got the lastest cmake (3.13.1 or higher)

I don´t think that´s a good idea, because installing CMake with pip is one of the several options to get CMake. If we put it here we risk users having multiple versions of it.

**Comment by nashif** [comment]
> @nashif should you add cmake into requirements.txt as well? The getting started guide mentions using `pip3 install --user cmake` to verify you've got the lastest cmake (3.13.1 or higher)

not a good idea, the preferred method for getting cmake should always be the distribution or OS being used.

> If I ask nicely, would you add `sphinx-tabs` to requirements.txt too :)

lets keep this PR to west.

**Comment by dbkinder** [comment]
ok.

**Pull request merged**
