### PR TITLE
Civetweb big file load crash

### PR DESCRIPTION
**Pull request by KozhinovAlexander**
Civetweb application `samples/net/sockets/civetweb` from current main repo crashes, when using jQuery v3.5.1 slim version (about ~24KiB in gzipped version).

My test board is `nucleo_h745zi_q_m7` from current master branch.

**I. Steps to reproduce (negative Test):**

1. Checkout this PR
2. Carefully go through changes in commits
3. Change board's and gatewy's IPv4 in sample's `pro.conf`
4. Compile it like this: 'west build -p auto -b <your_board_name_here> samples/net/sockets/civetweb'
5. Connect to your board's debug UART: 'minicom -D /dev/ttyACM0 -b 115200'
6. After ethernet the connection is established (use ping as indicator here) open in your browser (preferably Chrome) following link: `http://<your_bard_ip_here>:8080/jquery-3.5.1.slim.min.js`

My UART console shows following crash report:

>[00:00:14.751,000] <err> net_pkt: Data buffer (1500) allocation failed.                                                   
[00:00:14.751,000] <err> net_tcp: conn: 0x24037ee0 packet allocation failed, len=1452                                     
[00:00:14.751,000] <err> os: ***** BUS FAULT *****                                                                        
[00:00:14.751,000] <err> os:   Precise data bus error                                                                     
[00:00:14.751,000] <err> os:   BFAR Address: 0x7edfd9b3                                                                   
[00:00:14.751,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x24037820  r2/a3:  0x00000000                                   
[00:00:14.751,000] <err> os: r3/a4:  0x7edfd9ab r12/ip:  0xe0000000 r14/lr:  0x08008a09                                   
[00:00:14.751,000] <err> os:  xpsr:  0x61000000                                                                           
[00:00:14.751,000] <err> os: Faulting instruction address (r15/pc): 0x08012dce                                            
[00:00:14.751,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0                                             
[00:00:14.751,000] <err> os: Current thread: 0x240255a8 (unknown)                                                         
[00:00:14.812,000] <err> os: Halting system  

**II. Steps to reproduce (positive Test):**
1. Do the steps 1 - 3 from I.
2. Change the size of `samples/net/sockets/civetweb/web_page/jquery-3.5.1.slim.min.js` file by just leaving some few symbols (e.g. ~200 symbols). And save the file.
3. Clean the project by `rm -rf ./build` in your `/zephyr`path. 
4. Do steps 4 - 6 from I.

My UART console shows following staff:

> <boards_ipv4_here> - "GET /jquery-3.5.1.slim.min.js HTTP/1.1" 200
[00:00:10.451,000] <dbg> main.this_send_buffer_chunked: Transferring:
[00:00:10.451,000] <dbg> main.this_send_buffer_chunked: itr: 0x08017396 ret: 0 left_bytes: 4294975488 chunk_size: 1 B
[00:00:10.451,000] <dbg> main.this_send_buffer_chunked: itr: 0x08017462 ret: 210 left_bytes: 257698037761
[IMPLEMENTATION MISSING : strftime]

Even my browser shows changed `jquery-3.5.1.slim.min.js` file of smaller size.

### CODE REVIEW

**Comment by Nukersson** [comment]
*To all here:*
1. This PR is created only for @jukkar to test his net stack!
2. This PR does not intends to be merged ever since jQuery has MIT license!

Pleas all (except @jukkar) ignore this PR.

**Comment by Nukersson** [comment]
@jukkar Please let me know, if you observer same crashes at your dev-board.

I also add @erwango here, to ask him to test this PR on his `STM32F4` dev board, if possible. Thanks @erwango in advance!

**Comment by Nukersson** [comment]
Hello Jukka. I've just tested your new net/tcp improvements. This is, what I am getting within this PR after calling `http://<your_bard_ip_here>:8080/jquery-3.5.1.slim.min.js` now:

> 192.168.188.20 - "GET /jquery-3.5.1.slim.min.js HTTP/1.1" 404
[00:00:28.230,000] <dbg> main.this_send_buffer_chunked: Transferring:
[00:00:28.230,000] <dbg> main.this_send_buffer_chunked: itr: 0x0801764a ret:B
[00:00:28.335,000] <err> net_pkt: Data buffer (68) allocation failed.
[00:00:28.435,000] <err> net_pkt: Data buffer (150) allocation failed.
[00:00:28.435,000] <err> net_tcp: conn: 0x24037d88 packet allocation failed,2
[00:00:28.535,000] <err> net_pkt: Data buffer (150) allocation failed.
[00:00:28.535,000] <err> net_tcp: conn: 0x24037d88 packet allocation failed,2
[00:00:28.535,000] <dbg> main.this_send_buffer_chunked: itr: 0x0801964a ret:1
[00:00:28.535,000] <err> main: aborted! ret: -1

It looks much better now. Congrats! Obviously, the behavior is self explaining.
**But I still have one question:**
Is it possible with your tcp/net stack implementation to send the mentioned big file `jquery-3.5.1.slim.min.js` by just somehow chunked (multiple time reusing of same buffer) tcp transfer?

**Comment by jukkar** [comment]
> Is it possible with your tcp/net stack implementation to send the mentioned big file `jquery-3.5.1.slim.min.js` by just somehow chunked (multiple time reusing of same buffer) tcp transfer?

Hmm, I am not sure I understand what you mean here. The PR that I sent earlier tries to "fix" the issue if we have run out of memory, so it is certainly possible that the same buffer is used multiple times during TCP transfer. For the application, it is actually useful (is we have small amount of buffer), to send the data in smaller chunks, and optionally sleep a small amount of time between send chunks. This helps the memory pressure as the TCP stack is able to free the buffers when we have received ACK from the peer.

**Comment by Nukersson** [comment]
> > Is it possible with your tcp/net stack implementation to send the mentioned big file `jquery-3.5.1.slim.min.js` by just somehow chunked (multiple time reusing of same buffer) tcp transfer?
> 
> Hmm, I am not sure I understand what you mean here. The PR that I sent earlier tries to "fix" the issue if we have run out of memory, so it is certainly possible that the same buffer is used multiple times during TCP transfer. For the application, it is actually useful (is we have small amount of buffer), to send the data in smaller chunks, and optionally sleep a small amount of time between send chunks. This helps the memory pressure as the TCP stack is able to free the buffers when we have received ACK from the peer.
> 

Ok. Now I understand, what you mean.
I'll try to explain my question better now: Is it possible, that in case of *out of memory* your tcp stack tries to send the data chunked instead showing the error in the console?

Or should I better put sleep after chunked send command (see jQuery handler function in main.c of this PR), to avoid tcp stack error?

P.S.: With your fixes, providing *negative test* (see description of this PR) throws tcp stack error in the console. It is still much better, than hard fault without the mentioned fixes.

**Comment by jukkar** [comment]
> I'll try to explain my question better now: Is it possible, that in case of _out of memory_ your tcp stack tries to send the data chunked instead showing the error in the console?

Even if you try to send tens of kb of data, the TCP stack will usually only be able to send smaller piece of it. We need to queue the sent data in the TCP code until we have received the ACK from peer. So if you call `send()` in the application (with large amount of data), the `send()` usually returns much smaller value and you need to be prepared to handle that. This is normal socket programming anyway.

> 
> Or should I better put sleep after chunked send command (see jQuery handler function in main.c of this PR), to avoid tcp stack error?

The small sleep (like 50-100ms) in the application between `send()` calls could help if there is shortage of net_bufs. But if there is lot of buffers available, then the sleep is not needed. And beside it would slow down the data transfer. So it depends on the application needs / device in question.

**Comment by Nukersson** [comment]
> > I'll try to explain my question better now: Is it possible, that in case of _out of memory_ your tcp stack tries to send the data chunked instead showing the error in the console?
> 
> Even if you try to send tens of kb of data, the TCP stack will usually only be able to send smaller piece of it. We need to queue the sent data in the TCP code until we have received the ACK from peer. So if you call `send()` in the application (with large amount of data), the `send()` usually returns much smaller value and you need to be prepared to handle that. This is normal socket programming anyway.
> 
> > 
> > Or should I better put sleep after chunked send command (see jQuery handler function in main.c of this PR), to avoid tcp stack error?
> 
> The small sleep (like 50-100ms) in the application between `send()` calls could help if there is shortage of net_bufs. But if there is lot of buffers available, then the sleep is not needed. And beside it would slow down the data transfer. So it depends on the application needs / device in question.
> 

Thank you very much. Now will be able better use Zephyrs tcp stack

**Comment by Nukersson** [comment]
@jukkar Do you need this PR for your further net stack testings? Please let me know. Otherwise I would prefer to delete it. You are of course welcome to copy it to your branch anytime.

**Comment by jukkar** [comment]
> You are of course welcome to copy it to your branch anytime.

Thanks, I copied it. You can discard this draft PR.

**Comment by Nukersson** [comment]
closed since copied by jukkar

**Pull request closed without merging**
