### PR TITLE
net: lwm2m: Publicize firmware block context

### PR DESCRIPTION
**Pull request by yaomon**

### CODE REVIEW

**Review by tbursztyka — CHANGES_REQUESTED** [review]
You need a message and your signed-off-by in addition to the commit title

In such message could you explain the use case for this function?

**Comment by mike-scott** [comment]
I apologize for the delay.  My work schedule has been very busy and I was away on vacation for the last few weeks.  I'm reviewing this now.

**Comment by mike-scott** [comment]
I recommended squashing the 2nd patch back into the first, but overall, I wonder if this isn't a situation that the LwM2M subsys should just handle.  Why leave it up to the client at all?

**Comment by jukkar** [comment]
@mike-scott What should we do with this, merge or not to merge?

**Comment by mike-scott** [comment]
@jukkar don't merge.  There is still the open question concerning the 2nd patch.

**Comment by mike-scott** [comment]
@yaomon can you move the brace change back into the first patch (so there is only 1 patch)?

**Comment by sunkyl** [comment]
Yea, I'll try to get on it ASAP.

**Comment by yaomon** [comment]
Ok, the commits have been squashed. Let me know what else needs to be changed. Thanks for taking the time to respond :)

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by nashif** [comment]
stale, closing. Reopen when there are updates...

**Pull request closed without merging**
