### PR TITLE
tests/disk_access: Add flash-disk overlay for testing

### PR DESCRIPTION
**Pull request by de-nordic**
Adds native_posix overlay and modifies code to allow testing flash-disk access.

### CODE REVIEW

**Review by danieldegrasse — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]

**Review by aescolar — CHANGES_REQUESTED** [review]
May I ask for a native_sim overlay instead? (you can have a native_sim overlay, and the native_posix including the native_sim one)
native_posix will be deprecated soon, in favour of native_sim.

**Comment by de-nordic** [comment]
> May I ask for a native_sim overlay instead? (you can have a native_sim overlay, and the native_posix including the native_sim one)
> native_posix will be deprecated soon, in favour of native_sim.

Yes. I will do that.

**Comment by de-nordic** [comment]
> May I ask for a native_sim overlay instead? (you can have a native_sim overlay, and the native_posix including the native_sim one) native_posix will be deprecated soon, in favour of native_sim.

Ok, done. Since you have written that native_posix is going away, I have just did the native_sim then. The testcase.yaml has been altered to use native_sim instead of native_posix.

**Review by kartben — DISMISSED** [review]

**Review by aescolar — DISMISSED** [review]

**Comment by aescolar** [comment]
@de-nordic  note that due to the recent overlay-not-merging changes you need a extra overlay:
tests/drivers/disk/disk_access/boards/native_sim_native_64.overlay :
```
/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include "native_sim.overlay"
```

**Review by aescolar — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
