### PR TITLE
ieee802154: cc13xx_cc26xx: Driver updates for dual band support

### PR DESCRIPTION
**Pull request by vaishnavachath**
Add support for SubG and 2.4G band radios to co-exist in CC1352 and add minor fixes to the SubG and 2.4G RF drivers for CC1352. Changes were tested on CC1352P1 LaunchXL.

### CODE REVIEW

**Comment by vaishnavachath** [comment]
Dual network interface was tested with interface setup performed in application using net_if_* helpers as multiple interface configuration is not supported yet due to https://github.com/zephyrproject-rtos/zephyr/issues/29750

**Comment by cfriedt** [comment]
@vaishnavachath - LGTM - code changes will need to be postponed though until after the release stabilization period, unless there is an exception granted (which you could ask for).

Note: you could probably make a separate PR to simply add yourself as maintainer for TI platforms. That should be able to get in for this release, since it's not a code change.

To be honest, you should have been added as a collaborator long ago already.

**Comment by vaishnavachath** [comment]
Thanks @cfriedt , I will create a separate PR to add myself as maintainer for TI platforms and drop the commit from this PR.

**Comment by vaishnavachath** [comment]
> @vaishnavachath - LGTM - code changes will need to be postponed though until after the release stabilization period, unless there is an exception granted (which you could ask for).
> 
> Note: you could probably make a separate PR to simply add yourself as maintainer for TI platforms. That should be able to get in for this release, since it's not a code change.
> 
> To be honest, you should have been added as a collaborator long ago already.

@cfriedt created https://github.com/zephyrproject-rtos/zephyr/pull/54328

**Comment by teburd** [comment]
@cfriedt please take a look again

**Review by rlubos — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
Thanks @vaishnavachath!

**Pull request merged**
