### PR TITLE
kernel/sched: Fix SMP race on pend

### PR DESCRIPTION
**Pull request by andyross**
For historical reasons[1] suspending threads would release the scheduler lock between pend() (which places the current thread onto a wait queue) and z_swap() (which effects the context swtich).  This process happens with the caller's lock held, so local interrupts are masked.  But on SMP this opens a tiny race where another CPU could grab the pended thread and switch to it while we were still executing on its stack!

Fix this by elevating the "lock swap" code that already exists in the (portable/switch-based) z_swap() code one level so that it happens in z_pend_curr() also.  Now we hold the scheduler lock between pend and the final context switch.

Note that this technique can't work for the older z_swap_irqlock() implementation, which exists to vestigially support a few bits of arch code (mostly direct interrupts) that don't work on SMP anyway. Address with an assert to prevent future misuse.

[1] z_swap() is a historical API implemented in per-arch assembly for
    older architectures (like ARM32!).  It was designed to be called
    with what at the time was a global IRQ lock, so it doesn't
    understand the idea of a separate scheduler lock.  When we finally
    get all archictures on arch_switch() this design can be cleaned up
    quite a bit.

Signed-off-by: Andy Ross <andyross@google.com>

### CODE REVIEW

**Comment by andyross** [comment]
Stumbled on this while banging on the zync PR fixing the long tail of issues so it can merge.

This is a really small race window, happens only on SMP, and in CI is completely buried in the noise of spurious SMP timer failures.  But I found a spot where zync + userspace + qemu_riscv64_smp (only that one platform: spent two whole days thinking it was an arch bug!)  would hang one case in tests/kernel/semaphore/semaphore with a frequency of about 40%, which I guess was good enough.

Should probably consider a backport, but I'll leave that decision to others.

**Review by peter-mitsis — DISMISSED** [review]
Great find!

This definitely should be backported. It is the type of thing that will have both quality and certification impacts.

**Review by teburd — DISMISSED** [review]
Nice find indeed

**Review by yperess — DISMISSED** [review]

**Comment by andyross** [comment]
Heh, that failure turns out to be due to a late assertion I put in to protect vs. the case where we call z_pend_curr() (or its wrapper z_sched_wait()) with the scheduler lock directly, which would break the lock swap trick.  We don't do this anywhere.  It's fine.  But the story is interesting as to how it failed anyway on that one test on clang, so I'm going to tell it:

On uniprocessor setups, k_spinlock is degenerate.  You can't have multiple contexts spinning with only one cpu, so there's no need to store any actual lock data and the struct has zero size[1].  Essentially "k_spin_lock()" becomes equivalent to "irq_lock()", which was an important efficiency promise when this lock was introduced.

But having zero size, that means that the object placed in memory after a struct k_spinlock will have the same address as the lock.  And, getting back to this test, that assertion was testing to see if the lock being passed to z_pend_curr() was the scheduler
lock by doing a pointer equality comparison.

By now you know where this was going: **it just so happened** that when building that one test with clang, the sched_spinlock lock got placed adjacent to the global work_q spinlock.  So when the work queue tried to wait using its own lock, the kernel decided it was using the scheduler spinlock and aborted.

Trivial bug to fix.  Pretty nasty bug to find.  Anyway I thought someone would be amused.  Will have the update pushed as soon as my local twister run finishes.

[1] When building for C only, anyway.  It turns out that C++ doesn't allow empty structs, so there's a 1-byte dummy when C++ builds are enabled.  Ugh.

**Comment by andyross** [comment]
OK, rebased and passing.  Please re-review.

**Comment by npitre** [comment]
I'm not sure I fully understand the explanation.

You say: "Now we hold the scheduler lock between pend and the final 
context switch". But you do a k_spin_release() before calling z_swap(() 
which does drop the lock before the final context switch. The local IRQs 
remain masked out but on SMP that won't prevent another CPU from coming 
along and grabbing that thread like you describe.

What am I missing?

**Review by peter-mitsis — APPROVED** [review]

**Comment by npitre** [comment]
On Mon, 10 Oct 2022, Andy Ross wrote:

> Now it releases the caller's lock after acquiring the scheduler lock

Oh! OK. That's what I was missing: this is a different lock.

**Review by npitre — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
