### PR TITLE
Add: Support for pyocd runner for mr_canhubk3 board

### PR DESCRIPTION
**Pull request by mayankmahajan-nxp**
Modifying board.cmake file of mr_canhubk3 for pyocd support.

### CODE REVIEW

**Review by manuargue — CHANGES_REQUESTED** [review]
Please update the board's doc `Programming and Debugging` chapter to mention this runner support.

**Review by PetervdPerk-NXP — DISMISSED** [review]

**Review by manuargue — DISMISSED** [review]

**Review by bperseghetti — DISMISSED** [review]

**Comment by mayankmahajan-nxp** [comment]
> Adding `DNM` until hwmv2 collab branch is merged into main. After that, this PR should be rebased

Hi @manuargue, is the hwmv2 collab branch is merged into main?

**Comment by henrikbrixandersen** [comment]
> > Adding `DNM` until hwmv2 collab branch is merged into main. After that, this PR should be rebased
> 
> Hi @manuargue, is the hwmv2 collab branch is merged into main?

It is, yes. I have removed the DNM label.

**Comment by henrikbrixandersen** [comment]
@mayankmahajan-nxp You need to rebase this PR on current `main`.

**Comment by mayankmahajan-nxp** [comment]
> @mayankmahajan-nxp You need to rebase this PR on current `main`.

Done @henrikbrixandersen. Please check at your convenience.

**Comment by mayankmahajan-nxp** [comment]
Hi @bperseghetti, @PetervdPerk-NXP and @manuargue, your approvals have been dismissed due to rebase. Requesting review again.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by manuargue — APPROVED** [review]

**Review by bperseghetti — APPROVED** [review]

**Pull request merged**
