### PR TITLE
drivers/timer/hpet.c: migrate to devicetree

### LINKED ISSUE #18657: drivers/timer/hpet.c should use devicetree, not CONFIG_* for MMIO/IRQ data
The HPET timer driver currently uses `CONFIG_HPET_TIMER_BASE_ADDRESS` and the like for device configuration information, and the Zephyr standard mechanism for these is DeviceTree.  We need to add to devicetree and modify the driver accordingly.

### PR DESCRIPTION
**Pull request by ghost**
This driver was still using CONFIG_* values to determine its address,
IRQ, etc. Add a binding for an "intel,hpet" device and migrate this
driver to devicetree.

Fixes: #18657

Signed-off-by: Charles E. Youse <charles.youse@intel.com>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by gnuless** [comment]
Whoops.  I guess I need to make x86_64 work with devicetree.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
Uugh, I'd prefer we don't hack in `DT_` defines.  Can you just ifdef the driver or something?

**Review by wentongwu — APPROVED** [review]

**Comment by gnuless** [comment]
@galak Do you want to +1 this or should I shelve this until `x86_64` is retired?

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
> @galak Do you want to +1 this or should I shelve this until `x86_64` is retired?

when is `x86_64` going away?

**Comment by gnuless** [comment]
> when is `x86_64` going away?

I believe the plan is to pull it once SMP and memory protection are implemented in the Intel64 subarch stuff in x86, so I would think before the 2.1 release.

**Pull request merged**
