### PR TITLE
net: lib: lwm2m: fix coap proxy resource option

### PR DESCRIPTION
**Pull request by mike-scott**
commit 2a7546fb5ae9 ("net: lwm2m: add support for coap2coap proxy")
erroneously changed the COAP_OPTION_* used to specify the coap2coap
or coap2http proxy resource used from COAP_OPTION_URI_PATH to
COAP_OPTION_PROXY_SCHEME.

Changing it back to COAP_OPTION_URI_PATH requires us to re-order how
the coap options are appended to the packet as the coap options must
be added in the order specified by the numbers in:
https://tools.ietf.org/html/rfc7252#section-12.2

Signed-off-by: Michael Scott <michael@opensourcefoundries.com>

### CODE REVIEW

**Review by rveerama1 — APPROVED** [review]
LGTM

**Review by rbtchc — COMMENTED** [review]
This will set
1. COAP_OPTION_URI_PATH to either "coap2coap" or "coap2http"
1. COAP_OPTION_PROXY_URI to whatever URI (firmware_uri) set from lwm2m server

I check RFC 7252, it seems that you either use "PROXY_URI" without any URI_* options included or you composed the URI from URI_* options and replace the scheme by "PROXY_SCHEME" option to indicate it's a forward-proxy request

I also check [Californium example](https://github.com/eclipse/californium/tree/master/demo-apps/cf-proxy/src/main/java/org/eclipse/californium/examples). The example seems able to tell that the incoming request is a forward-proxy one by checking "PROXY_URI", or "URI_*" w/ "PROXY_SCHEME" w/o appending "coap2coap" or "coap2http" in "URI_PATH".

I may be wrong for I did not dig deep enough into Californium.

**Comment by mike-scott** [comment]
@rbtchc 
> This will set
> 
> COAP_OPTION_URI_PATH to either "coap2coap" or "coap2http"
> COAP_OPTION_PROXY_URI to whatever URI (firmware_uri) set from lwm2m server
I check RFC 7252, it seems that you either use "PROXY_URI" without any URI_* options included or you composed the URI from URI_* options and replace the scheme by "PROXY_SCHEME" option to indicate it's a forward-proxy request
> 
> I also check Californium example. The example seems able to tell that the incoming request is a forward-proxy one by checking "PROXY_URI", or "URI_*" w/ "PROXY_SCHEME" w/o appending "coap2coap" or "coap2http" in "URI_PATH".
> 
> I may be wrong for I did not dig deep enough into Californium.

The reason I posted this correction, was that RFC 7252 explains the use of proxy-uri and proxy-scheme as follows in Section 5.10.2: https://tools.ietf.org/html/rfc7252#section-5.10.2
> The Proxy-Uri Option MUST take precedence over any of the Uri-Host, Uri-Port, Uri-Path or Uri-Query options (each of which MUST NOT be included in a request containing the Proxy-Uri Option).  As a special case to simplify many proxy clients, the absolute-URI can be constructed from the Uri-* options.  When a Proxy-Scheme Option is present, the absolute-URI is constructed as follows: a CoAP URI is constructed from the Uri-* options as defined in Section 6.5. In the resulting URI, the initial scheme up to, but not including, the following colon is then replaced by the content of the Proxy-Scheme Option.  Note that this case is only applicable if the components of the desired URI other than the scheme component actually can be expressed using Uri-* options; for example, to represent a URI with a userinfo component in the authority, only Proxy-Uri can be used.

This doesn't mean you MUST NOT use the URI_* options in a request to a proxy server when PROXY_URI is present.  It means these options will not be used to generate the forward proxy request URI.  And, my use of the PROXY_SCHEME in the original patch seems incorrect.  It's used as an override for the schema when PROXY_URI is not included.  So a request including URI_* components for: coap://<server>:<port>/<uri_path with a PROXY_SCHEME set to "http" becomes: http://<server>:<port>/<uri_path> when sent to the forwarded resource.

I was also testing my original patch with a build of cf-proxy from the master branch and that's why it was working.   The behavior mentioned here: https://github.com/eclipse/californium/blob/master/demo-apps/cf-proxy/src/main/java/org/eclipse/californium/examples/ProxyMessageDeliverer.java#L55 was added with commit https://github.com/eclipse/californium/commit/edcb5fdded79de3a950f461d7c694a18573e8d23 as of August 17, 2017.   That commit is not present in either of the 1.0.x or 2.0.x branches.  So, when using many of the prebuilt branch-based .jar binaries, the current logic doesn't work.  I felt it was better to explicitly ask for the right resource on the proxy via URI_PATH.

If we're ok relying on the fact that proxy users *must* use the master branch of Californium project AND that PROXY_SCHEME seems to have a very specific use-case in the Californium proxy that we are taking advantage of, then I will close this patch and leave it as is.

**Comment by rbtchc** [comment]
Thanks for the clear explanations.
My understanding is that there are two ways to generate a proxy requests, one is using PROXY_URI another is using PROXY_SCHEME w/ URI_*. The first one is less restrictive. Therefore, I agree with you that we should support PROXY_URI. And you are right, the Californium example I found is in the master branch and not included in 1.0 nor 2.0. For the sake of backward compatible, we could include URI_PATH to send the request directly to the resource "coap2coap" or "coap2http" as well.

By the way, I realized that "coap2coap" and "coap2http" is implementation specific.
Implementation other than Californium might have other URI name defined.
But I think it should be fine if those implementation check the PROXY_URI first and ignore the URI_*.

**Comment by mike-scott** [comment]
@rbtchc were you ok approving the patch?

**Review by rbtchc — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
