### PR TITLE
drivers/sensor: lis2dh: add INT1/INT2 gpio interrupt config

### LINKED ISSUE #63736: Avoid lis2dh interrupt multiple triggers
### Problem description

I am using the accelerometer lis3dh in a project that requires very low power consumption and I am having to high power when implementing anymotion interrupt. I notice that the driver [drivers/sensor/lis2dh](url) configures the interrupt pin as GPIO_INT_LEVEL_ACTIVE and turn it OFF while processing to avoid multiple triggers. Although there is a situation that multiple triggers still happen.

Lis3dh (or lis2dh) does not clear the interrupt immediately after INTx_SRC is read, but only at the next sample read. So lets say we implement a 50Hz sampling rate, it means readings every 20ms. 
The callback `lis2dh_thread_cb` can be executed much faster than 20 ms and it creates a loop that runs for 20 ms every time that the interrupt is triggered by the accelerometer (When lis2dh_thread_cb is finished the pin will still be high and a new call will be generated). 

Since the register INTx_SRC is read in the first loop, it will be cleared and `handler_anymotion` will be called only once. But the loop will still be running and consuming power, as can be seen in the picture below.

Interrupt current

### Proposed change

I propose that the type of interrupt is changed from **GPIO_INT_LEVEL_ACTIVE** to **GPIO_INT_EDGE_RISING**, which will ensure that it is triggered only once. 

Since the interrupt is changed to EDGE type, the multiple calls for `setup_int1` and `setup_int2` can be removed and the interrupt can be initialized only once.

### PR DESCRIPTION
**Pull request by avisconti**
Add INT1/INT2 gpio interrupt configuration.
iPossible values:

      0 = GPIO_INT_EDGE_RISING
      1 = GPIO_INT_EDGE_FALLING
      2 = GPIO_INT_LEVEL_HIGH
      3 = GPIO_INT_LEVEL_LOW

Fixes #63736

EDIT:
Added also GPIO_INT_EDGE

### CODE REVIEW

**Review by fabiobaltieri — DISMISSED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by gwa-simon** [comment]
Hi @avisconti 

thank you for implementing the changes. I have tested the changes in my hardware and now the power consumption follows the specification from the datasheet and the multiple triggers problem is solved.

*I highlight the need for having GPIO_INT_EDGE as an option. It is required because the micro NRF52832 shows a constant current of 400uA if configured directly to GPIO_INT_EDGE_RISING or GPIO_INT_EDGE_FALLING. But with GPIO_INT_EDGE it works fine.

**Review by aasinclair — APPROVED** [review]

**Comment by bjarki-trackunit** [comment]
Hi, I'm looking into creating a generic way of implementing GPIO routed interrupts, and I hope someone here can enlighten me a bit :)

What is the benefit from the additions added here compared to following the `GPIO_ACTIVE_HIGH` / `GPIO_ACTIVE_LOW` like this:
```
gpio_pin_configure_dt(&config->int_gpio, GPIO_INPUT);

gpio_init_callback(&data->gpio_callback, config->int_gpio_callback,
	           BIT(config->int_gpio.pin));

gpio_add_callback(config->int_gpio.port, &data->gpio_callback);

gpio_pin_interrupt_configure_dt(&config->int_gpio, GPIO_INT_EDGE_TO_ACTIVE);
```
I'm very interested in the following:
* why can the user set `GPIO_INT_LEVEL_HIGH` and `GPIO_INT_LEVEL_LOW` in the devicetree, potentially negating the `GPIO_ACTIVE_HIGH` / `GPIO_ACTIVE_LOW` flags
* why can the user configure if the INT shall be edge or level triggered, would that not be up to the driver to configure internally?

Sorry to ask in a merged PR instead of a new issue but the PR is just so very relevant :)

**Comment by gwa-simon** [comment]
Hi @bjarki-trackunit,

`GPIO_INT_LEVEL_HIGH` and `GPIO_INT_LEVEL_LOW` are used for configuring at which status (LOW or HIGH) the interrupt will be triggered. 
`GPIO_ACTIVE_HIGH` and `GPIO_ACTIVE_LOW` are responsible for making the translation from physical value to logical value. What is really useful when we need to flip the logic (making 0V recognized as HIGH)

About making it configurable, I would say that in general it is really better to make it up to the driver to define the right configuration. But in this specific case we have implemented the sensor to a microcontroller with some bugs in the interrupt that cause extra power consumption in some INT configurations. So setting it according to the micro type became more convenient.

I hope it clarifies a little your question.

**Comment by bjarki-trackunit** [comment]
@gwa-simon

If we could specify the `GPIO_INT_*` flags in the devicetree, would this not make the `GPIO_ACTIVE_*` flags redundant?
Specifically, using `GPIO_INT_LEVEL_LOW` and `GPIO_ACTIVE_LOW` together is identical to just using `GPIO_INT_LEVEL_HIGH` right?

**Pull request merged**
