### PR TITLE
twister: add fixtures given by --fixture option to each devices.

### PR DESCRIPTION
**Pull request by chen-png**
fixtures could also be given by twister command with --fixture option
explicitly, not only hardware map file. In this case, we should
assign those fixtures to each devices too.

Signed-off-by: Chen Peng1 <peng1.chen@intel.com>

### CODE REVIEW

**Review by fuhaolei — APPROVED** [review]

**Comment by hakehuang** [comment]
so if the fixture is given, twister will assume that the target board has given fixture?

**Comment by chen-png** [comment]
> so if the fixture is given, twister will assume that the target board has given fixture?

yes, I think so, if we invoke twister with --fixture option, then the board should have them.

**Review by PerMac — CHANGES_REQUESTED** [review]
Being able to call tests requiring fixtures and telling twister that the fixture is available, without the need to modify a hardware map is a very useful option for developers IMO. However, this PR breaks the current "API". `--fixture` flag is used in an opposite way. When  it is used twister selects only boards which provide such fixture. I.e. it is a filtering option.

After our docs (https://docs.zephyrproject.org/latest/guides/test/twister.html) 
> fixture: <expression>
Specify a test case dependency on an external device(e.g., sensor), and identify setups that fulfill this dependency. It depends on specific test setup and board selection logic to pick the particular board(s) out of multiple boards that fulfill the dependency in an automation setup based on “fixture” keyword. Some sample fixture names are i2c_hts221, i2c_bme280, i2c_FRAM, ble_fw and gpio_loop. Only one fixture can be defined per testcase.

Therefore, either we decide to change the definition of the flag and update the docs accordingly, or you modify the approach, adding a new flag, e.g. `fixture-imply` (but this is just a loose idea for the name).

**Comment by chen-png** [comment]
>A testcase can specify the fixture it needs which can then be matched with hardware capability of a board and the fixtures it supports **via the command line or using the hardware map file.**

docs mentioned that fixtures could be added via command line or hardware map file, but it seems that it only introduce hardware map file, I will add some for command line.

**Review by PerMac — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]

**Review by gopiotr — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
