### PR TITLE
boards: arm: mchp: Enable additional drivers for MEC15xxEVB board

### PR DESCRIPTION
**Pull request by albertofloyd**
Enable pinmux for port F,  Enable ADC, PWM and WDT drivers by default, but keep SPI disabled for now.
Swap I2C instances since I2C0 is multiplexed with UART2
Select VTR3 as 1.8V

Signed-off-by: Jose Alberto Meza <jose.a.meza.arellano@intel.com>

### CODE REVIEW

**Comment by albertofloyd** [comment]
@scottwcpg  could you review this?

**Review by franciscomunoz — COMMENTED** [review]
LGTM

**Review by scottwcpg — APPROVED** [review]

**Review by franciscomunoz — APPROVED** [review]

**Comment by dcpleung** [comment]
Swapping I2C 0<->1 is going to cause confusion since it no longer corresponds to the schematics. Is there a particular reason you want I2C1 on hardware to appear as instance 0? Developers can always use instance 1 instead of 0.

**Comment by albertofloyd** [comment]
> Swapping I2C 0<->1 is going to cause confusion since it no longer corresponds to the schematics. Is there a particular reason you want I2C1 on hardware to appear as instance 0? Developers can always use instance 1 instead of 0.

This arise as original instance actually cannot be used at the same time than UART 2 port which is the console. The other option I considered was to remove it completely.

Also note that mapping is not 1 to 1 for all exposed instances. i.e. I2C 2 is actually SoC I2C controller 7

**Comment by dcpleung** [comment]
If that's the case, set `CONFIG_I2C_XEC_0=n` would probably be better. I still believe a one-to-one mapping is better in the long term.

**Review by dcpleung — APPROVED** [review]
Let's merge this and I will play with the naming.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
Need to fix doc issues before I can merge this.

**Comment by dbkinder** [comment]
> Need to fix doc issues before I can merge this.

@andrewboie I just pulled this PR and generated the docs locally without error.  Do we still have a way to tell CI to try again (and build the docs another time)?

**Comment by andrewboie** [comment]
@dbkinder think we need your help here

**Comment by andrewboie** [comment]
Looks like that fixed it thanks

**Pull request merged**
