### PR TITLE
boards: remove CONFIG_PINCTRL udoo boards.

### PR DESCRIPTION
**Pull request by ParthSanepara**
this pr fix  change file "boards/udoo/udoo_neo_full/udoo_neo_full_mcimx6x_m4_defconfig " removed CONFIG_PINCTRL=y
#78619

### CODE REVIEW

**Comment by ParthSanepara** [comment]
@nordicjm can you review this pr?

**Comment by mmahadevan108** [comment]
Please address the CI compliance check failures.

**Review by nordicjm — CHANGES_REQUESTED** [review]
You're just removing this but NXP has not moved the options to Kconfig, I would rather you did not submit a mass of PRs that are wrong if you do not understand what the actual required changes are

**Comment by ParthSanepara** [comment]
I am closing this PR as it may conflict with another PR Request.

**Pull request closed without merging**
