### PR TITLE
lib/picolibc: Rework malloc arena setup

### PR DESCRIPTION
**Pull request by keith-packard**
Picolibc inherited its malloc arena configuration from newlib instead of
from minimal libc. This ended up making it a bit too fragile to run the
full set of zephyr tests. In particular:

 * Z_MALLOC_PARTITION_EXISTS would get set when not used

 * Setting an arena size depended on a bunch of other values, including
   whether the system had an MMU or MPU, and whether the MPU required
   power-of-two alignment or not.

This patch cleans things up so that there is a single heap size specifier,
PICOLIBC_HEAP_SIZE.

 * If PICOLIBC_HEAP_SIZE is positive, this sets the size of the heap. On
   MMU systems, picolibc will only use the remaining memory if that's
   smaller.

 * If PICOLIBC_HEAP_SIZE is zero, then there is no heap available and
   malloc will always fail. This also disables Z_MALLOC_PARTITION_EXISTS.

 * If PICOLIBC_HEAP_SIZE is negative, then picolibc uses all remaining
   memory for the malloc heap.

The defaults are designed to allow tests to work without requiring
additional settings.

 * For MMU enabled systems, the default value is 1048576. It would be nice
   to have this use 'all available memory', but that's difficult to manage
   as the API which returns free memory (k_mem_free_get) doesn't take into
   account the amount of free virtual address space.

 * For MPU enabled systems which require power-of-two aligned MPU regions,
   the default value is 64kB.

 * For other systems, the default value is -1, indicating that all
   available memory be used for the malloc arena.

Signed-off-by: Keith Packard <keithp@keithp.com>

### CODE REVIEW

**Review by andyross — DISMISSED** [review]
This is another area where there's a brewing popcorn fight.  Zephyr has its own heap layer too (see sys_heap/k_heap), and it's provided as a toolkit API to allow apps to manage memory in multiple pools, etc... Now, most apps including a libc right now are likely going to be using a single global heap, because we don't really have good support for a userspace "process" model that would give threads their own heaps.  But we'll get there, and at some point the existence of two blobs of heap code is going to look like a wart.

**Comment by keith-packard** [comment]
> This is another area where there's a brewing popcorn fight. Zephyr has its own heap layer too (see sys_heap/k_heap), and it's provided as a toolkit API to allow apps to manage memory in multiple pools, etc... Now, most apps including a libc right now are likely going to be using a single global heap, because we don't really have good support for a userspace "process" model that would give threads their own heaps. But we'll get there, and at some point the existence of two blobs of heap code is going to look like a wart.

Yeah, I've seen that stuff. Picolibc malloc could use that by having the 'sbrk' function allocate chunks of that space instead of a separate pool. Getting it to *release* chunks of the heap which are no longer in use would be trickier as the sbrk API doesn't really accommodate that. It would be great to also let usermode threads do allocations in a private heap so they could be protected too. That might just require implementing malloc in zephyr instead of using the C library implementation.

**Comment by keith-packard** [comment]
Hrm. This doesn't seem to work as I expected:
```
config PICOLIBC_HEAP_SIZE
	int "Picolibc heap size (bytes)"
	default 1048576 if MMU
	default 65536 if MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT
	default -1
```
This config value is getting set to -1 even when MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT is set. I'm kludging around this by moving this conditional stuff to the code, but that doesn't seem ideal to me?

**Comment by cfriedt** [comment]
> Hrm. This doesn't seem to work as I expected:
> 
> ```
> config PICOLIBC_HEAP_SIZE
> 	int "Picolibc heap size (bytes)"
> 	default 1048576 if MMU
> 	default 65536 if MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT
> 	default -1
> ```
> 
> This config value is getting set to -1 even when MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT is set. I'm kludging around this by moving this conditional stuff to the code, but that doesn't seem ideal to me?

Kconfig might need some hand-holding (i.e. being very explicit about conditionals).

**Comment by keith-packard** [comment]
> Kconfig might need some hand-holding (i.e. being very explicit about conditionals).

Arg, just a typo -- used `USERMODE` instead of `USERSPACE`. All fine now. Local builds didn't catch this, but CI did.

**Review by cfriedt — APPROVED** [review]

**Comment by stephanosio** [comment]
> at some point the existence of two blobs of heap code is going to look like a wart.

One thing we can do is to provide an option to "map" the libc `malloc` and its friends to the Zephyr equivalent functions in the shim layer (i.e. `libc-hooks.c`). At least, for the newlib (and probably the picolibc too), you can completely override the default `malloc` implementation.

**Review by stephanosio — APPROVED** [review]

**Comment by keith-packard** [comment]
> > at some point the existence of two blobs of heap code is going to look like a wart.
> 
> One thing we can do is to provide an option to "map" the libc `malloc` and its friends to the Zephyr equivalent functions in the shim layer (i.e. `libc-hooks.c`). At least, for the newlib (and probably the picolibc too), you can completely override the default `malloc` implementation.

We don't need to do anything fancy at all, just provide the malloc() API inside zephy. That would replace *any* C library version.

**Pull request merged**
