### PR TITLE
arch: arm: aarch32: cortex_m: fault: Prevent BusFault from HardFault

### PR DESCRIPTION
**Pull request by chrisc11**
A Cortex-M BusFault often arises from the execution of a function
pointer that got corrupted.

The Zephyr Cortex-M fault handler de-references the `$pc` in
`z_arm_is_synchronous_svc()` to determine if the fault was due to a
kernel oops (ARCH_EXCEPT). This can cause a BusFault if the pc itself
was corrupt. A BusFault from a HardFault will trigger ARM Cortex-M
"Lockup" preventing the Zephyr fault handler from running to
completion. This in turn, results in no fault handling information
getting dumped by the Zephyr fault handler.

To fix the issue, we can simply set the `CCR.BFHFNMIGN` bit prior to
the instruction address dereference which will cause the processor to
ignore the BusFault and return a value of 0x0 instead of entering
lockup. After the operation is complete, we clear `CCR.BFHFNMIGN` as
it would be unexpected for any other code in the fault handler to
trigger a fault.

The issue can be reproduced programmatically with:

```
  void (*unaligned_func)(void) = (void (*)(void))0x50000001;
  unaligned_func();
```

I bumped into this problem while debugging an issue on the nRF9160DK
(`west build --board nrf9160dk_nrf9160ns`) and confirmed that after
making this change I now see the full fault handler print:

```
[00:00:45.582,214] <err> os: Exception occurred in Secure State
[00:00:45.582,244] <err> os: ***** HARD FAULT *****
[...]
[00:00:45.583,984] <err> os: Current thread: 0x2000d340 (shell_uart)
[00:00:45.829,498] <err> fatal_error: Resetting system
```

Signed-off-by: Chris Coleman <chris@memfault.com>

### CODE REVIEW

**Comment by microbuilder** [comment]
This seems sensible and I ran into this issue early this week, but let me do some testing before I approve. Thanks for the PR, though.

**Comment by chrisc11** [comment]
> This seems sensible and I ran into this issue early this week, but let me do some testing before I approve. Thanks for the PR, though.

@microbuilder Just wanted to see if you had a chance to try this out or had any feedback? I tried this out on a few Cortex-M's this week and it worked as expected -- note that ARMV6-M (i.e Cortex-M0's) do not support this bit so I opted to leave the existing behavior for that arch

**Review by microbuilder — APPROVED** [review]

**Comment by microbuilder** [comment]
> > This seems sensible and I ran into this issue early this week, but let me do some testing before I approve. Thanks for the PR, though.
> 
> @microbuilder Just wanted to see if you had a chance to try this out or had any feedback? I tried this out on a few Cortex-M's this week and it worked as expected -- note that ARMV6-M (i.e Cortex-M0's) do not support this bit so I opted to leave the existing behavior for that arch

Sorry, slipped off my radar, but looks good.

**Comment by MaureenHelm** [comment]
Need to rebase and remove the merge commit

**Review by microbuilder — CHANGES_REQUESTED** [review]
Need to remove merge commit message (thanks for catching that @MaureenHelm). 

To squash the last two commits on your PR branch, and remove the merge conflict message:

```bash
$ git reset --soft HEAD~1
$ git commit --no-edit --amend
$ git push -f origin <yourbranch>
```

**Comment by chrisc11** [comment]
> Need to remove merge commit message (thanks for catching that @MaureenHelm).
> 
> To squash the last two commits on your PR branch, and remove the merge conflict message:
> 
> ```shell
> $ git reset --soft HEAD~1
> $ git commit --no-edit --amend
> $ git push -f origin <yourbranch>
> ```

Fixed -- I had clicked the "Update branch" button on Github and had missed that it defaulted to merge commit, thanks!

**Review by microbuilder — DISMISSED** [review]

**Comment by chrisc11** [comment]
jfyi @microbuilder I rebased the branch to kick off tests again since CI hit an [unrelated test flake](https://github.com/zephyrproject-rtos/zephyr/runs/7728392149)

**Review by microbuilder — APPROVED** [review]
CI passing now (kicked it off again), thanks for the PR!

**Comment by chrisc11** [comment]
> CI passing now (kicked it off again), thanks for the PR!

Awesome, thank you!

**Review by povergoing — APPROVED** [review]

**Pull request merged**
