### PR TITLE
net: lwm2m: Restructure LwM2M Kconfig menu

### PR DESCRIPTION
**Pull request by SeppoTakalo**
* Create submenu for protocol versions. Like LwM2M 1.0 vs 1.1. Object versions.
* Create submenu for engine features. Containing all engine tweaks that are not directly from protocol specification.
* Create submenu for all memory tuning options. For example maximum number of certain objects, buffer sizes, etc.
* Order all objects by object ID and show the ID in title.
* When multiple options depend on same feature, group them under if <option> ... endif. Preferably directly after the selection itself.
* Move IPSO and uCIFI menuentries one sublevel up.
* Drop deprecated entries to bottom.

No functional changes, just clean up of Kconfig menu.

## Main LwM2M menu
Screenshot from 2023-08-04 12-15-58

## Protocol versions
Screenshot from 2023-08-04 12-16-13

## Engine features
Screenshot from 2023-08-04 12-16-29

### CODE REVIEW

**Comment by kartben** [comment]
It would probably be nice to have consistent capitalization of the term LwM2M, while you're at it?

**Comment by SeppoTakalo** [comment]
Sure.. I just did a quick search for " LWM2M " and replaced those with " LwM2M ".
Surprisingly many.

**Comment by SeppoTakalo** [comment]
Apparently my refactoring introduced some build failures... I'll continue on working on this.

**Review by rlubos — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Pull request merged**
