### PR TITLE
samples: drivers: soc_flash_nrf: enable 8-bit write block emulation

### PR DESCRIPTION
**Pull request by PerMac**
Updated sample config to allow emulation of 8-bit write block.
(because the nRF Flash driver has changed its default write block size
 to 32-bit aligned)

Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
@nvlsianpu can you take a look?

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@nashif This patches fixes on-board test. Please merge.

**Comment by mbolivar-nordic** [comment]
kicking CI

**Comment by nvlsianpu** [comment]
@carlescufi Can you merge this?

**Review by ioannisg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
