### PR TITLE
tools: net-tools: place net-tools inside tools

### PR DESCRIPTION
**Pull request by ghost**
Updates references to net-tools (e.g. referring to $ZEPHYR_BASE or to the net-tools project) to refer to the correct placement of net-tools under tools.

TODO:
* [x] As soon as https://github.com/zephyrproject-rtos/net-tools/pull/75 has been merged I'll update this PR to point to the proper commit in west.
* [x] Rebase after #77852 has been merged.

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Comment by fgrandel** [comment]
@kartben Any idea how I could debug that doc build failure? Guess it has something to do with the additional links I introduced? Maybe I overlooked some specific error message that points me to the source of the problem?

**Comment by kartben** [comment]
> @kartben Any idea how I could debug that doc build failure? Guess it has something to do with the additional links I introduced? Maybe I overlooked some specific error message that points me to the source of the problem?

You seem to be missing the declaration for your reference target

Something like:

https://github.com/zephyrproject-rtos/zephyr/blob/main/samples%2Fnet%2Fvirtual%2FREADME.rst#L50

**Comment by fgrandel** [comment]
> > @kartben Any idea how I could debug that doc build failure? Guess it has something to do with the additional links I introduced? Maybe I overlooked some specific error message that points me to the source of the problem?
> 
> You seem to be missing the declaration for your reference target

Doh! Fixed. Thanks for your help.

**Review by jukkar — DISMISSED** [review]

**Comment by fgrandel** [comment]
@kartben @pdgendt @jukkar @nordicjm Thanks for having approved earlier versions, would be nice if you could re-approve. No changes, just rebased.

**Review by pdgendt — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
