### PR TITLE
sensors: convert lis2mdl to use information coming from dts

### PR DESCRIPTION
**Pull request by avisconti**
Convert lis2mdl magnetometer driver to get the device name as well
as i2c slave information from device tree. Updates the build_all
test accordingly.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Review by galak — DISMISSED** [review]
Is this missing a dts binding file for lis2mdl?

**Comment by avisconti** [comment]
> Is this missing a dts binding file for lis2mdl?

Actually no. The dts binding file was already there for lis2mdl, but for some reason the
device name and I2C infos were taken from configuration.

**Comment by avisconti** [comment]
@MaureenHelm 
Any comment here?

**Review by MaureenHelm — APPROVED** [review]
Looks good, but please fix the merge conflict

**Pull request merged**
