### PR TITLE
pm: device: Get rid of core devices list

### LINKED ISSUE #34214: codes reference weak variable are optimized out
**Describe the bug**
In `subsys/power/device.c`, there is a variable defined as
```
__weak const char *const z_pm_core_devices[] = {...
```
When define a strong version of this variable in other file, the code in this file
```
153                 while (z_pm_core_devices[cdi]) {
154                         if (strcmp(dev->name, z_pm_core_devices[cdi]) == 0) {
155                                 pm_devices[cdi] = pmi;
156                                 break;
157                         }
158                         ++cdi;
159                 }
```
can't be compiled correctly, they are optimized out.

**To Reproduce**
1. cherry pick patch https://github.com/mengxianglinx/zephyr/commit/08864aabb1cc3570bb99cdca618e35576826af58
2. run `twister -s tests/subsys/power/power_mgmt/subsys.power.interface -p qemu_x86`, test case failed
3. run `twister -s tests/subsys/power/power_mgmt/subsys.power.interface -p qemu_x86 --coverage`, test case pass
4. compare `zephyr.lst` generated in step 2 and step 3, assembly codes for the codes above are different

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK 0.12.2, 0.12.3, 0.12.4)

### PR DESCRIPTION
**Pull request by ceolin**
Use device tree dependencies between devices to replace hardcoded core devices.

Fixes zephyrproject-rtos#34214

### CODE REVIEW

**Comment by nashif** [comment]
this fixes a bug AFAIK, please add a reference

**Review by gmarull — COMMENTED** [review]
I think that the solution here is too complex, and still doesn't get rid, e.g. of `CONFIG_PM_MAX_DEVICES`.

As mentioned earlier, using devices as they are sorted by the linker should be enough. Current priorities duplicate dependency information to some extent. A device `B` depending on `A` will never appear before on the device list, since it's wrong to have `prio(B) < prio(A)`.

If we want to have a list of devices with PM instead of checking for PM availability every time, we can:

- Duplicate device list for PM purposes and drop those with no PM at init time
- Use the proposal in #35257

I understood that using current priorities and checking for PM != NULL was the chosen solution to move forward.

**Comment by ceolin** [comment]
> I think that the solution here is too complex, and still doesn't get rid, e.g. of `CONFIG_PM_MAX_DEVICES`.
> 
> As mentioned earlier, using devices as they are sorted by the linker should be enough. Current priorities duplicate dependency information to some extent. A device `B` depending on `A` will never appear before on the device list, since it's wrong to have `prio(B) < prio(A)`.
> 
> If we want to have a list of devices with PM instead of checking for PM availability every time, we can:
> 
> * Duplicate device list for PM purposes and drop those with no PM at init time
> * Use the proposal in #35257
> 
> I understood that using current priorities and checking for PM != NULL was the chosen solution to move forward.

Yep, that was what we had talked. I just thought this solution was simple enough and was consuming the right API to this. The proposal in #352577 I really want o avoid, I think is complex because the logic is scattered across different areas, linker sections, preprocessor magic, ...

Anyway, lets keep it simple and go with what we have discussed for now. I'll keep `CONFIG_PM_MAX_DEVICES` to track which devices were suspended and need to be resumed though.

**Comment by ceolin** [comment]
> this fixes a bug AFAIK, please add a reference

Yep, I've added the `fixes` tag in the first commit. Don't know why it is not linking the pr with the issue though.

**Comment by nashif** [comment]
> I understood that using current priorities and checking for PM != NULL was the chosen solution to move forward.

I did not see a followup PR that addresses the feedback given last week. We agreed that #35257 was not enough and would require significant changes to devices

**Review by gmarull — APPROVED** [review]
will work on a solution to remove `CONFIG_PM_MAX_DEVICES` after this gets merged

**Review by nashif — APPROVED** [review]

**Pull request merged**
