### PR TITLE
arch: arc: implement stack pointer random

### LINKED ISSUE #8197: kernel.memory_protection.stack_random: Stack pointer randomization fails on em_starterkit_em7d_v22
**Test location:** tests/kernel/mem_protect/stack_random

**Issue:** stack pointer changed 0 times out of 64 tests

**Execution log:** 

```
Running test suite stack_pointer_randomness
===================================================================
starting test - test_stack_pt_randomization
Test Stack pointer randomization
stack pointer changed 0 times out of 64 tests

 Assertion failed at zephyr.git/tests/kernel/mem_protect/stack_random/src/main.c:60: test_stack_pt_randomization: (changed equal to 0)
Stack pointer is not randomized
FAIL - test_stack_pt_randomization
===================================================================
===================================================================
PROJECT EXECUTION FAILED
```

**Board on which the test fails:** em_starterkit_em7d_v22

**Latest commit on which failure observed:** 265f502b8e48ba3299bfbbef7814cbab196af0b3

### PR DESCRIPTION
**Pull request by vonhust**
implement the stack pointer random for CONFIG
_STACK_POINTER_RANDOM

Fixes #8197

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
Thanks for sending this. I think we can actually take a different approach which will solve #13465 on ARM as well, by passing an additional offset parameter to _new_thread. More to follow later.

**Review by tyrantlizard77 — APPROVED** [review]
I think this is OK for 1.14. @ioannisg and I have been talking about overhauling how the kernel invokes z_new_thread() but we're going to do that in the 1.15 cycle.

**Review by ruuddw — APPROVED** [review]
ok, if adding the 'offset' to the common new_thread code or other more generic solution doesn't make it in 1.14, this is good to go in now.

**Comment by andrewboie** [comment]
> ok, if adding the 'offset' to the common new_thread code or other more generic solution doesn't make it in 1.14, this is good to go in now.

Yeah at this point in the release cycle we're hesitant to take any big changes for 1.14 since we are already past feature freeze and total code freeze is imminent.

**Pull request merged**
