### PR TITLE
doc: build overview: Improve diagram, fix errors/stale info, misc.

### PR DESCRIPTION
**Pull request by ulfalizer**
Diagram and text improvements:

 - Redraw the configuration phase diagram to better reflect the actual
   logic. Remove some misleading arrows, like from devicetree.h to
   Kconfig. Kconfig uses the devicetree scripts directly.

 - After the old devicetree scripts were removed in commit c8c35f76ab
   ("scripts: dts: Remove deprecated extract_dts_includes.py script"),
   the dtc compiler is only run to catch any high-level warnings and
   errors from it. The output is unused.

   Update the diagram and descriptions to explain how dtc is used.

 - Mention kconfigfunctions.py and explain better how devicetree and
   Kconfig interact

 - Clarify that 'cpp' is the C preprocessor. People often confuse it
   with C++.

 - Fix a typo'd devicetree_fixups.h in the text

 - Use the :file: role for files instead of italic text

 - Add links to the devicetree and Kconfig sections of the manual, and
   use the :zephyr_file: role to turn more files into direct links

 - Make the text generic re. Make vs. Ninja

 - Lots of other minor tweaks and clarifications

### CODE REVIEW

**Comment by ulfalizer** [comment]
Configuration overview diagram before:

diagbefore

Some of the arrows seem a bit weird, and the `dtc` stuff is misleading now.

Configuration overview diagram after:

diag-after

**Comment by ulfalizer** [comment]
Used https://draw.io for modifying the diagram btw. Pretty handy.

Means Inkscape has trouble opening it though.

**Comment by ceolin** [comment]
Really good improvements, mainly addressing possible misunderstandings. Regarding new image, it is clear than the old one, but I think it is missing few things:

1) It is missing information that it is orchestrated by CMake, though it is described in text
2) Output of configuration phase is also Makefiles or Ninja scripts that will be consumed later.

**Comment by ulfalizer** [comment]
> * It is missing information that it is orchestrated by CMake, though it is described in text
> * Output of configuration phase is also Makefiles or Ninja scripts that will be consumed later.

Do you think it might be enough to add an extra box for it in the Outputs box? Wanted to avoid having a box-in-box for the entire diagram. Getting borderline big already.

**Comment by ulfalizer** [comment]
@ceolin 
Updated the title and added an output. Does this look okay?

build-config-phase-Page

**Review by ceolin — APPROVED** [review]

**Comment by ceolin** [comment]
yep

**Review by nashif — APPROVED** [review]

**Pull request merged**
