### PR TITLE
os: disable CRC by default and move to lib/crc

### PR DESCRIPTION
**Pull request by nashif**
Users of CRC shall enable the the kconfig and not rely on it being
enabled by default.

Also move CRC to lib/crc

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Comment by nashif** [comment]
@nordicjm  note I change kconfig in retention subsys...

**Review by nordicjm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]
typo *not

**Review by de-nordic — DISMISSED** [review]
It seems that MCUmgr did not get broken by this change.

**Review by str4t0m — CHANGES_REQUESTED** [review]
Looking for crc includes I stumbled over the following cases that I think should select/imply CRC as well:
- `ICP10125_CHECK_CRC` is enabled in drivers/sensor/icp10125/Kconfig (`btw. icp10125_check_crc()` should be guarded by that config as well to avoid unused function warnings).
- `ETH_STM32_HAL` is enabled in drivers/ethernet/Kconfig.stm32_hal
- `ETH_ADIN2111_SPI_CFG0` in drivers/ethernet/Kconfig.adin2111

EDIT: maybe also for the bluetooth ots service.  I'm not sure if it is already guaranteed to to be selected for that elsewhere.

**Review by cfriedt — DISMISSED** [review]

**Review by MaureenHelm — COMMENTED** [review]
There are more sensors that use crc:
```
$ git grep include.*crc -- drivers/sensor/
drivers/sensor/icp10125/icp10125.c:#include <zephyr/sys/crc.h>
drivers/sensor/sgp40/sgp40.c:#include <zephyr/sys/crc.h>
drivers/sensor/sht3xd/sht3xd.c:#include <zephyr/sys/crc.h>
drivers/sensor/sht4x/sht4x.c:#include <zephyr/sys/crc.h>
drivers/sensor/shtcx/shtcx.c:#include <zephyr/sys/crc.h>
drivers/sensor/si7055/si7055.c:#include <zephyr/sys/crc.h>
```

**Comment by nashif** [comment]
> There are more sensors that use crc:

all of which already select CRC.

**Review by str4t0m — CHANGES_REQUESTED** [review]
I now had a closer look at the bluetooth ots client in subsys/bluetooth/services/ots/ and it should also imply CRC, because when `BT_OTS_OACP_CHECKSUM_SUPPORT` is enabled it needs crc32_ieee() and tests fail to build.

**Comment by nashif** [comment]
@str4t0m  hopefully I got them all now :)

**Review by str4t0m — APPROVED** [review]
Yeah, I think this should now cover all.

**Review by MaureenHelm — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
