### PR TITLE
irq: multilevel: fixes and optimizations 

### LINKED ISSUE #79301: arch: irq: multilevel: the value return from `irq_parent_level_3()` is wrong
**Describe the bug**

When Zephyr encodes an IRQ to the second and the third level, the value of the IRQ is incremented by one, as zero means no IRQs present in that level.

So when we want to get the parent IRQ of level 3 with `irq_parent_level_3()`, the value in the level 2 should be restored by minus 1.

**To Reproduce**
1. Run the tests fixed/added in #78845 with v3.7-branch
2. The test should fail

**Expected behavior**
`irq_parent_level_3()` should return the correct IRQ and the test should pass

**Impact**
Applications/drivers that depend on `irq_parent_level_3()` will get the wrong IRQ value.

**Context**
This can be closed by backporting the first commit (https://github.com/zephyrproject-rtos/zephyr/pull/78845/commits/30aa3465d02b8348d472c856c19a8210a9bf8854) of #78845

### PR DESCRIPTION
**Pull request by ycsin**
- Fixed a bug in the calculation of parent IRQ (probably should be backported)
- Changed the multilevel IRQ APIs to always work with all levels of IRQ
- Convert the decoding of the multi-level IRQ from manual bit manipulation through bit mask and shifting, to a named union struct(`_z_irq_t`) that partitions the bits of a `uint32_t` into `l1`, `l2` & `l3`. `_z_irq_t` also allows us to get the interrupt controller IRQ of a IRQ easily.
- Add a new API to increment a multi-level IRQ

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]
LGTM - simplifies things, although I needed a second take on `_z_irq_t`

**Review by andyross — APPROVED** [review]
I'm still on record wanting a rewrite that generates all of this from a graph in devicetree with no manual code (especially for things like duplicated code for specific levels, etc...).    But this definitely looks like cleanup.

**Comment by ycsin** [comment]
@nashif probably can comment on the `_z_irq_t`?

**Comment by cfriedt** [comment]
> @nashif probably can comment on the `_z_irq_t`?

I just meant that it was a little confusing at first, so needed to look at it again.

**Pull request merged**
