### PR TITLE
manifest: update TF-M with latest upstream

### LINKED ISSUE #33423: tests: portability: tests/portability/cmsis_rtos_v2 fails on nrf5340dk_nrf5340_cpuappns
**Describe the bug**
The test `test_semaphor` from the test suite under tests/portability/cmsis_rtos_v2 fails on nrf5340dk_nrf5340_cpuappns causing the rest of tests in the test suite to fail. It causes ` >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU `. The suite is terminated then only by the timeout.

**To Reproduce**
1. have nrf5340dk connected
2. go you your zephyr dir
3. call `./scripts/twister -T /home/maciej/zephyrproject2/zephyr/tests/portability/cmsis_rtos_v2/ -p nrf5340dk_nrf5340_cpuappns --device-testing --device-serial /dev/ttyACM2 -v --inline-logs`

**Expected behavior**
The test passes

**Impact**
not clear

**Logs and console output**
```
===================================================================
START - test_semaphore
ASSERTION FAIL [thread->base.pended_on] @ WEST_TOPDIR/zephyr/kernel/sched.c:585
ASSERTION FAIL [z_spin_lock_valid(l)] @ WEST_TOPDIR/zephyr/include/spinlock.h:129
Recursive spinlock 0x20042230
E: r0/a1:  0x00000004  r1/a2:  0x00000081  r2/a3:  0x00000001
E: r3/a4:  0x000542c5 r12/ip:  0x80000000 r14/lr:  0x0005879d
E:  xpsr:  0x41000025
E: Faulting instruction address (r15/pc): 0x0005bb24
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Fault during interrupt handling
E: Current thread: 0x20040d54 (Mutex_check)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK 0.12.2
 - Commit SHA or Version used zephyr-v2.5.0-1069-g4fbd0cb0ca6b

### LINKED ISSUE #33667: tests: kernel: timer: Test timeout_abs from tests/kernel/timer/timer_api hangs causing test scenarios to fail
**Describe the bug**
The test timeout_abs from kernel.timer.tickless and kernel.timer scenarios at tests/kernel/timer/timer_api hangs on nrf5340dk_nrf5340_cpuappns causing this scenarios to fail (test sleep_abs is not executed)

**To Reproduce**
1. have nrf5340dk connected
2. go to your zephyr dir
3. run `./scripts/twister -T tests/kernel/timer/timer_api/ -p nrf5340dk_nrf5340_cpuappns --device-testing --device-serial /dev/ttyACM2 --jobs 1 -v -v --inline-logs`

**Expected behavior**
Test passes

**Impact**
Not clear

**Logs and console output**
```
...
START - test_timer_remaining
PASS - test_timer_remaining in 0.51 seconds
===================================================================
START - test_timeout_abs
```
and hangs. Then is terminated with a timeout

**Environment (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Toolchain zephyr sdk 0.12.2
 - Commit SHA or Version used zephyr-v2.5.0-1463-gc59cf

**Additional context**
This is a different issue than #32839. There the test fails due to an assertion error. Here it hangs.

### LINKED ISSUE #34962: tfm: cmake: Toolchain not being passed into psa-arch-tests
**Describe the bug**

When running unit tests for `psa_arch_tests` with TF-M, cmake falls back to the default C compiler, rather than forwarding the correct ARM cross-compiler, resulting in build failure.

The use of the host compiler is caused by this: https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/master/psa-arch-tests/api-tests/CMakeLists.txt#L415-L436

Where the compiler is not passed on, but a C compiler is being looked up here:
https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/51cdecd6f9e6b0aa66da45db22f4b478183d472f/psa-arch-tests/api-tests/tools/scripts/target_cfg/CMakeLists.txt#L29

```cmake
project(TargetConfigGen LANGUAGES C)
```

**To Reproduce**

```bash
$ ./scripts/twister -p mps2_an521_nonsecure -N --inline-logs \
  -s samples/tfm_integration/tfm_psa_test/sample.tfm.psa_internal_trusted_storage_test
```

This will result in trying to run the system C compiler (`/Library/Developer/CommandLineTools/usr/bin/cc` here, on OS X):

```
[2/5] Building C object CMakeFiles/TargetConfigGen.dir/Users/kevin/Linaro/zephyr/zephyr/twister-out/mps2_an521_nonsecure/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_internal_trusted_storage_test/tfm/app/psa_api_tests/targetConfigGen.c.o
FAILED: CMakeFiles/TargetConfigGen.dir/Users/kevin/Linaro/zephyr/zephyr/twister-out/mps2_an521_nonsecure/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_internal_trusted_storage_test/tfm/app/psa_api_tests/targetConfigGen.c.o 
/Library/Developer/CommandLineTools/usr/bin/cc  -I/Users/kevin/Linaro/zephyr/modules/tee/tfm/psa-arch-tests/api-tests/val/nspe -I/Users/kevin/Linaro/zephyr/modules/tee/tfm/psa-arch-tests/api-tests/val/common -I/Users/kevin/Linaro/zephyr/modules/tee/tfm/psa-arch-tests/api-tests/platform/targets/common/nspe -I/Users/kevin/Linaro/zephyr/modules/tee/tfm/psa-arch-tests/api-tests/platform/targets/common/nspe/crypto -I/Users/kevin/Linaro/zephyr/modules/tee/tfm/psa-arch-tests/api-tests/platform/targets/tgt_dev_apis_tfm_an521/nspe -arch arm64 -o CMakeFiles/TargetConfigGen.dir/Users/kevin/Linaro/zephyr/zephyr/twister-out/mps2_an521_nonsecure/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_internal_trusted_storage_test/tfm/app/psa_api_tests/targetConfigGen.c.o -c /Users/kevin/Linaro/zephyr/zephyr/twister-out/mps2_an521_nonsecure/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_internal_trusted_storage_test/tfm/app/psa_api_tests/targetConfigGen.c
/Users/kevin/Linaro/zephyr/zephyr/twister-out/mps2_an521_nonsecure/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_internal_trusted_storage_test/tfm/app/psa_api_tests/targetConfigGen.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
```

**Expected behavior**

The toolchain should be passed on in the cmake function when running the PSA tests.

**Additional context**

This fix should happen upstream in TF-M, but the issue is being filed here for tracking purposes until it is resolved either upstream and/or downstram in Zephyr's TF-M module.

### PR DESCRIPTION
**Pull request by ioannisg**
The TF-M update brings in the latest PSA crypto headers,
after TF-M switched formally to MBedTLS 2.26.0. It also
brings in some important fixes for cache enabling in nRF
platforms.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

Fixes #33423.
Fixes #33667.
Fixes #34962 

Supersedes #35455

### CODE REVIEW

**Review by anangl — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]
Tested on:

- lpcxpresso5s69_ns
- mps2_an521_nonsecure

**Comment by microbuilder** [comment]
Also tested for issue #34962 ... fixes problem:

```bash
./scripts/twister -p mps2_an521_nonsecure -N --inline-logs \
  -s samples/tfm_integration/tfm_psa_test/sample.tfm.psa_internal_trusted_storage_test
```

```
INFO    - Zephyr version: zephyr-v2.5.0-4118-ga7c1268ee622
INFO    - JOBS: 8
INFO    - Using 'gnuarmemb' toolchain.
INFO    - Building initial testcase list...
INFO    - 1 test scenarios (1 configurations) selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0
INFO    - 1 of 1 test configurations passed (100.00%), 0 failed, 0 skipped with 0 warnings in 45.03 seconds
INFO    - In total 1 test cases were executed, 0 skipped on 1 out of total 372 platforms (0.27%)
INFO    - 1 test configurations executed on platforms, 0 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing xunit report /Users/kevin/Linaro/zephyr/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /Users/kevin/Linaro/zephyr/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
```

**Review by MaureenHelm — APPROVED** [review]

**Comment by ioannisg** [comment]
Tested on all platforms that support TF-M
- mps2
- nrf
- laird
- stm
- nxp

**Comment by ioannisg** [comment]
@MaureenHelm @galak looks to me that the CI failure is relevant to the fact that the LPC build in TF-M is pulling HAL from external tries. What should we do about this?

**Comment by MaureenHelm** [comment]
> @MaureenHelm @galak looks to me that the CI failure is relevant to the fact that the LPC build in TF-M is pulling HAL from external tries. What should we do about this? I confirm that the failing test builds fine locally.

Do you mean this?
```
In file included from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/platform_base_address.h:26,
                 from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/platform_regs.h:27,
                 from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/cmsis.h:14,
                 from /workdir/modules/tee/tfm/trusted-firmware-m/platform/include/tfm_hal_device_header.h:14,
                 from /workdir/modules/tee/tfm/trusted-firmware-m/interface/src/psa/psa_client.c:12:
/workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Native_Driver/LPC55S69_cm33_core0.h:195:1: error: unterminated comment
  195 | /*!
      | ^
/workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Native_Driver/LPC55S69_cm33_core0.h:46: error: unterminated #ifndef
   46 | #ifndef _LPC55S69_CM33_CORE0_H_
      |
```

**Comment by ioannisg** [comment]
> > @MaureenHelm @galak looks to me that the CI failure is relevant to the fact that the LPC build in TF-M is pulling HAL from external tries. What should we do about this? I confirm that the failing test builds fine locally.
> 
> Do you mean this?
> 
> ```
> In file included from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/platform_base_address.h:26,
>                  from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/platform_regs.h:27,
>                  from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/cmsis.h:14,
>                  from /workdir/modules/tee/tfm/trusted-firmware-m/platform/include/tfm_hal_device_header.h:14,
>                  from /workdir/modules/tee/tfm/trusted-firmware-m/interface/src/psa/psa_client.c:12:
> /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Native_Driver/LPC55S69_cm33_core0.h:195:1: error: unterminated comment
>   195 | /*!
>       | ^
> /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Native_Driver/LPC55S69_cm33_core0.h:46: error: unterminated #ifndef
>    46 | #ifndef _LPC55S69_CM33_CORE0_H_
>       |
> ```

No, no this one. @MaureenHelm where did you get this log?

**Comment by MaureenHelm** [comment]
> > > @MaureenHelm @galak looks to me that the CI failure is relevant to the fact that the LPC build in TF-M is pulling HAL from external tries. What should we do about this? I confirm that the failing test builds fine locally.
> > 
> > 
> > Do you mean this?
> > ```
> > In file included from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/platform_base_address.h:26,
> >                  from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/platform_regs.h:27,
> >                  from /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Device/Include/cmsis.h:14,
> >                  from /workdir/modules/tee/tfm/trusted-firmware-m/platform/include/tfm_hal_device_header.h:14,
> >                  from /workdir/modules/tee/tfm/trusted-firmware-m/interface/src/psa/psa_client.c:12:
> > /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Native_Driver/LPC55S69_cm33_core0.h:195:1: error: unterminated comment
> >   195 | /*!
> >       | ^
> > /workdir/modules/tee/tfm/trusted-firmware-m/platform/ext/target/nxp/lpcxpresso55s69/Native_Driver/LPC55S69_cm33_core0.h:46: error: unterminated #ifndef
> >    46 | #ifndef _LPC55S69_CM33_CORE0_H_
> >       |
> > ```
> 
> No, not this one. @MaureenHelm where did you get this log?

https://buildkite.com/zephyr/zephyr/builds/31235#a79acfd7-ae18-4309-9dd8-5cd98d3d35ef, line 1639

**Comment by ioannisg** [comment]
I removed the HW test block label, since i actually tested this.

**Pull request merged**
