### PR TITLE
twister: fix skipped count issue in xml result with --only-failed.

### LINKED ISSUE #43348: twister:skipped case num issue when use --only-failed.
**Describe the bug**
If retry the failed test case with “twister --only-failed”, skip case num will be lost in twister_report.xml.

**To Reproduce**
    1.Run test case with twister, make it have skip and failed case.
    2.Run twister again with "--only-failed" option.
    3.See error.

**Logs and console output**
First run
>DEBUG   - running footprint_reports
INFO    - 135 of 136 test configurations passed (99.26%), 1 failed, 875 skipped with 0 warnings in 4022.07 seconds
**INFO    - In total 1161 test cases were executed, 18289 skipped on 1 out of total 432 platforms (0.23%)**
INFO    - 136 test configurations executed on platforms, 0 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing xunit report /home/ztest/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/ztest/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed

Second run
>DEBUG   - running footprint_reports
INFO    - 1 of 1 test configurations passed (100.00%), 0 failed, 0 skipped with 0 warnings in 14.80 seconds
**INFO    - In total 1 test cases were executed, 0 skipped on 0 out of total 432 platforms (0.00%)**
INFO    - 1 test configurations executed on platforms, 0 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing xunit report /home/ztest/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/ztest/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed

Results in XML
>time="712.053899" tests="18953" failures="0" errors="0" skipped="0">

**Environment**
OS: Ubuntu
Toolchain zephyr-sdk-0.13.2
Commit ba02864d4125

### PR DESCRIPTION
**Pull request by chen-png**
When running twister with --only-failed option, based on last xml
result, the new skipped count should be the last skipped count
plus current skipped count.

fix: #43348 

Signed-off-by: Chen Peng1 <peng1.chen@intel.com>

### CODE REVIEW

**Review by enjiamai — DISMISSED** [review]

**Review by PerMac — DISMISSED** [review]

**Review by hakehuang — DISMISSED** [review]

**Comment by chen-png** [comment]
>  how are you reproducing the issue and testing that this PR solves the problem described?

this issue occurred when we used --only-failed option to re-run those failures/errors based on last twister-out directory.

so I **changed any one test case in tests/kernel/threads/ as failed manually**, and run twister command:

```
 twister -p qemu_x86 -T tests/kernel/threads/
<testsuite errors="0" failures="1" name="qemu_x86" skipped="54" tests="109" time="13.220984">
```

and **restore the failed tests, ran twister with --only-failed again**
```
twister -p qemu_x86 -T tests/kernel/threads/ --only-failed
<testsuite errors="0" failures="0" name="qemu_x86" skipped="1" tests="109" time="13.177411">
```

and found that the skipped is 1 in the final twister_report.xml, this is not correct.

**Comment by chen-png** [comment]
when we run twister with --only-failed and update the results in twister_report.xml, it will overlay the skipped count using the skips from second results, it's not the total skipped count
```
if os.path.exists(filename) and append:
              ts = eleTestsuites.findall(f'testsuite/[@name="{p}"]')
              if ts:
                   eleTestsuite = ts[0]
                   eleTestsuite.attrib['skipped'] = "%d" % skips
```
for total skipped count, we should use the new skips plus the last skips.

**Review by hakehuang — APPROVED** [review]

**Review by PerMac — APPROVED** [review]

**Review by enjiamai — APPROVED** [review]

**Comment by chen-png** [comment]
@nashif Could you please help review this? thanks.

**Comment by nashif** [comment]
> @nashif Could you please help review this? thanks.

looking

**Pull request merged**
