### PR TITLE
maintainers: add TI platforms and initial set of collaborators

### PR DESCRIPTION
**Pull request by cfriedt**
So far, the majority of support has been through Linaro for these platforms, but we do expect to bring a maintainer on from TI in the near future.

cc @vaishnavachath

### CODE REVIEW

**Comment by cfriedt** [comment]
It looks like the `hal_ti` check might be a false positive (at least one existing platform in the file names a hal path as well).

**Review by nashif — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by MaureenHelm** [comment]
> It looks like the `hal_ti` check might be a false positive (at least one existing platform in the file names a hal path as well).

Not a false positive. `modules/hal_nordic/` and `modules/hal_nxp/` exist in the tree, but `modules/hal_ti/` does not.

**Comment by nashif** [comment]
@cfriedt please fix issue.

**Comment by cfriedt** [comment]
See #44572

**Pull request closed without merging**
