### PR TITLE
shell: Allow extension of shell APIs

### PR DESCRIPTION
**Pull request by asemjonovs**
Similar to logging module, allow application specific extension of shell fprintf APIs at a macro level.

### CODE REVIEW

**Review by yperess — DISMISSED** [review]

**Comment by jakub-uC** [comment]
@asemjonovs 
I am not against this change, but may you please share some use cases for this? I am just curious :)

**Comment by asemjonovs** [comment]
> @asemjonovs I am not against this change, but may you please share some use cases for this? I am just curious :)

Sure! I'm working on a project where I'm converting our text based logging over to tokenized logging.  I found that we can get additional space savings by also tokenizing the strings that are used in the shell API's as well, since its similar to logging for us.  Since the tokenizing occurs at build time, I need to intercept the macro to tokenize the string.

**Review by jakub-uC — DISMISSED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
not a big fan of this open-ended extension method, but if we want to go with this, we would like to see a sample using this in the tree, similar to how it is done for logging. please.

**Comment by asemjonovs** [comment]
> not a big fan of this open-ended extension method, but if we want to go with this, we would like to see a sample using this in the tree, similar to how it is done for logging. please.

Done.  Yeah, I'm not a huge fan of this as well, but I'm not sure if there's a better way?

**Review by yperess — APPROVED** [review]

**Review by jakub-uC — APPROVED** [review]

**Comment by asemjonovs** [comment]
@nashif - could you give this another pass?

**Review by nashif — APPROVED** [review]

**Pull request merged**
