### PR TITLE
doc: drivers: add diagram and clarify a note

### PR DESCRIPTION
**Pull request by dcpleung**
Add a simple diagram on the device driver model.

Instead of saying "this device driver", spell out that the note
is for the random number generator driver, as the visual
presentation does not have clear distinction.

Also update some formatting.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Review by aescolar — DISMISSED** [review]
Thanks for the PR.
Regarding the changes in the text I have no complaints.
About the figure: There seems to be too much detail/text for the size of the figure: https://builds.zephyrproject.org/zephyrproject-rtos/zephyr/18278/docs/reference/drivers/index.html
It is not really possible to read it when rendered inside the page itself. Some of the figure fonts seem to be ~1/4 to 1/2 of the size of the web font.
What would be the difference between a "device driver instance" and a "device driver implementation"?

**Comment by dcpleung** [comment]
An instance is one created by doing `DEVICE_AND_API_INIT()`, and implementation is the actual code. I tried to capture that one implementation can be utilized for multiple "devices".

As for the size, let me try re-arrange them. Maybe I should rotate them 90 degrees?

**Comment by aescolar** [comment]
> An instance is one created by doing 

Ah, I had missed the "instance N of dev driver M" text :)

**Comment by dbkinder** [comment]
@dcpleung if you used draw.io to create this diagram (as I hope you did), would you export it as an SVG with "Include a copy of my diagram".  That will allow someone to edit the SVG diagram saved in the repo using draw.io:
Screenshot from 2019-08-16 13-20-31

**Review by dbkinder — CHANGES_REQUESTED** [review]
agreed, the image text is too small to be readable...

**Comment by dcpleung** [comment]
I have rotated the diagram 90 degrees. Let me know if it looks okay to you.

**Review by dbkinder — APPROVED** [review]
Yes. Image looks better, thanks.

**Review by nashif — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
