### PR TITLE
west.yml: Update NXP HAL SDK to 2.14

### PR DESCRIPTION
**Pull request by mmahadevan108**
Update NXP HAL SDK to 2.14

### CODE REVIEW

**Comment by hakehuang** [comment]
@mmahadevan108 testing is scheduled, will feedback once ready

**Comment by hakehuang** [comment]
> @mmahadevan108 testing is scheduled, will feedback once ready

there are many format error in the source code.

**Comment by mmahadevan108** [comment]
@hakehuang , can you take a look at this PR and provide test results.

**Review by manuargue — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Comment by hakehuang** [comment]
Regression test done. no issues found.

**Review by hakehuang — APPROVED** [review]

**Pull request merged**
