### PR TITLE
MAINTAINERS: Update Renesas maintainers

### PR DESCRIPTION
**Pull request by andrzej-kaczmarek**
Update maintainers for Renesas code to Renesas employees.
Add @ioannis-karachalios as maintainer for Renesas SmartBond code.
Add @KhiemNguyenT as maintainer for Renesas HAL.

### CODE REVIEW

**Review by ezflash — APPROVED** [review]

**Review by blauret — APPROVED** [review]

**Review by renesasae — APPROVED** [review]
Renesas TSC team member (Onkar Raut) approving this change.

**Review by ydamigos — APPROVED** [review]

**Comment by KhiemNguyenT** [comment]
@MaureenHelm , may I get your support to review this ?

**Review by sjanc — APPROVED** [review]

**Comment by KhiemNguyenT** [comment]
@stephanosio and @nashif , may I get your support to review this ?

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by kartben** [comment]
@ioannis-karachalios @KhiemNguyenT thanks for stepping up as maintainers! Feel free to claim your Zephyr Maintainer badge here, if you haven't already! https://forms.gle/oCw9iAPLhUsHTapc8 :)

**Pull request merged**
