### PR TITLE
fs: implemented unmount function to fatfs

### PR DESCRIPTION
**Pull request by lucaspeixotot**
There isn't a function to handle the unmount, so I implemented based in
f_mount comments. In the comments of f_mount we actually have that f_mount is
used to mount/unmount logic, is just necessary use NULL pointer to fs
argument.

Signed-off-by: Lucas Peixoto <lucaspeixotoac@gmail.com>

### CODE REVIEW

**Comment by nashif** [comment]
need to open an issue against 1.14. Is there a PR for master?

**Comment by lucaspeixotot** [comment]
> need to open an issue against 1.14. Is there a PR for master?

I'm sorry, I created this pull request because I'm working in v1.14-branch, but I think that actually the right pull request is for master. I'm changing pull request for master.

**Comment by lucaspeixotot** [comment]
> need to open an issue against 1.14. Is there a PR for master?

I'm sorry, but what exactly I need to do to conclude this pull request? My team is working in v1.14-branch, do I need to create a issue explaining my changes for v1.14-branch? Do I need to do the same for master?

**Comment by nvlsianpu** [comment]
You can create one PR for master and just label it as backport-1.14 (if you can't ask someone with write access to  do that). Then a boot should make backport PR automatically.

What i see there is that only last commit in this PR is related to PR title, so pleas remove unrelated commits for there (let's open dedicated PRs for them if needed).

**Comment by lucaspeixotot** [comment]
> You can create one PR for master and just label it as backport-1.14 (if you can't ask someone with write access to do that). Then a boot should make backport PR automatically.
> 
> What i see there is that only the last commit in this PR is related to PR title, so pleas remove unrelated commits for there (let's open dedicated PRs for them if needed).

Thanks, I will create another PR to do that.

**Pull request closed without merging**
