### PR TITLE
Test: Add two scripts for testing tracing function

### PR DESCRIPTION
**Pull request by youhuazhu**
1. Add a script to capture tracing data for posix backend:
    trace_capture_posix.py
2. Add a script to verify the tracing function by tracing
output and dump the elf file:
    trace_function_check.py

Signed-off-by: YouhuaX Zhu <youhuax.zhu@intel.com>

### CODE REVIEW

**Comment by youhuazhu** [comment]
Hi @wentongwu ,  would you help to review this PR?  thanks.

**Comment by nashif** [comment]
how do you expect to use those scripts for testing exactly?

**Comment by youhuazhu** [comment]
> how do you expect to use those scripts for testing exactly?

thanks for quickly response,  for now,  I run those scripts by manual:
e.g.
python3 trace_function_check.py -b posix_port
python3 trace_function_check.py -b usb
python3 trace_function_check.py -b uart

and for usb/uart backends,  they depends on phiscal devices. 
(I verified the two backends on my reel board).

**Comment by youhuazhu** [comment]
Hi @nashif ,  
For tracing system part,  as my checking,  we can't get kernel tracing info(thread, ISR ...) in C code, also can't check the status with ZASSERT(...).  it just output the tracing data to backends,   So I use python script to verify the zephyr tracing system.

I would much appreciate if you give me some suggestions for this.    thanks.

**Comment by youhuazhu** [comment]
Hi @nashif, @LeiW000 , @wentongwu:
	for background of this pr:
	I want to verify below tracing functions for zephyr which output tracing data(text/ctf) to backend(usb/uart/posix),
	a. check tracing if support operation (thread, ISR, idle thread, etc.) based on the provided trace data.
	b. using babeltrace to transfer the CTF data.
	c. Check tracing if producing code when the tracing system is disabled.

	and we have 2 solutions to verify this:
	a. python solution:
		using script to handle tracing output and using objdump to check the symbols in zephyr image.
		Drawbacks:
		it's hard to intergrate into sanitycheck, and maybe also have issues for doxygen.
	b. C code solution:
		use execve() function and text handle fuction in C library to check tracing fuctions.
		Drawbacks: 
		it will take more time to implement this than using python script.

	so which is better as your opinion or other suggestions?

**Comment by youhuazhu** [comment]
I will re-design tracing module test with C code, so close this one.

**Pull request closed without merging**
