### PR TITLE
Fixed quantity of ESP32-C3 board interfaces

### PR DESCRIPTION
**Pull request by Nyarn-WTF**
Corrected the documentation due to the quantity of interfaces different from the datasheet.

[ESP32-C3 datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf)

### CODE REVIEW

**Comment by sylvioalves** [comment]
@Nyarn-WTF, thanks for updating that info. Can you re-work your commit title, description and sign-off?

**Comment by Nyarn-WTF** [comment]
@sylvioalves Thank you for pointing that out.
Commit message fix completed.

**Review by uLipe — DISMISSED** [review]

**Review by sylvioalves — DISMISSED** [review]

**Comment by fkokosinski** [comment]
Hi @Nyarn-WTF, thanks for your contribution. It looks like the CI is complaining about your commit's author and sign-off line not being the same:
```
From: Nyarn <dev@mail.nyarn.wtf>
Signed-off-by: Haruki Obuchi <dev@mail.nyarn.wtf>
```

**Comment by Nyarn-WTF** [comment]
Thank you @fkokosinski .
fix completed.

**Review by fkokosinski — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Pull request merged**
