### PR TITLE
doc/kernel: Remove incorrect kernel priority illustration

### PR DESCRIPTION
**Pull request by andyross**
Carles discovered that this graph is actually incorrect, it shows priority zero as a cooperative priority, when in fact only negative priorities are cooperative.

Fixing documentation graphics isn't something anyone should trust me to do, so just remove it for now pending rework.  It isn't otherwise referenced in the text.

There's some thought that the "Idle Thread (cooperative)" indicator is confusing also, as it might be taken to imply that the idle thread can have a higher priority than other threads, which is impossible by construction.  (The meaning seems to be more "This is where the idle thread priority would be if there were no preemptible priorities configured")

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
I can update the picture, better than removing it.

**Comment by nashif** [comment]
ok, this is weird, if I open the same svg file it is shown correctly in the editor, not in the docs though, hmmm:

image

**Comment by nashif** [comment]
think it was a bug in draw.io or something, I just saved it the same picture again and it seems to put the arrow in the right place.

**Comment by andyross** [comment]
Closing, obviated by diagram fix

**Pull request closed without merging**
