### PR TITLE
net: lib: http: split out URL parsing as a separate CONFIG

### PR DESCRIPTION
**Pull request by mike-scott**
With the introduction of CoAP and other protocols, URL parsing is
needed when HTTP_PARSER is not.  Let's split out the existing
functionality of URL parsing into it's own CONFIG and let
HTTP_PARSER use it by automatically selecting HTTP_PARSER_URL when
HTTP_PARSER is enabled.

Signed-off-by: Michael Scott <michael.scott@linaro.org>

### CODE REVIEW

**Comment by mike-scott** [comment]
This commit is will be the ancestor of https://github.com/zephyrproject-rtos/zephyr/pull/4208 which will drop the commit and be slightly reworked once this is merged.

**Comment by mike-scott** [comment]
@nashif In https://github.com/zephyrproject-rtos/zephyr/pull/4208 you requested a different approach to splitting out the URL parsing code.  Please let me know if this is also the wrong approach and we can discuss.

One concern to note: Future pulls from the upstream repo (https://github.com/nodejs/http-parser/releases/tag/v2.7.1) will be harder to apply this way.  Where the #ifdef approach might be easier.

**Review by rbtchc — APPROVED** [review]
LGTM

**Comment by jukkar** [comment]
> One concern to note: Future pulls from the upstream repo (https://github.com/nodejs/http-parser/releases/tag/v2.7.1) will be harder to apply this way. Where the #ifdef approach might be easier.

I agree, it will be much harder to take any upstream http parser code after this. But the code is in subsys/net/lib/http instead of ext/lib so it looks like this merging was never really expected anyway.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by nashif — APPROVED** [review]

**Pull request merged**
