### PR TITLE
Fixup nxp gpio names

### PR DESCRIPTION
**Pull request by galak**
This attempts to provide a different solution to #7172

### CODE REVIEW

**Comment by mike-scott** [comment]
TBH, these are really hacky patches going in the wrong direction.  Is there some pressure to "just make this work" for a while?  They also don't address the dead references to GPIO_MCUX_PORT*_NAME which are all over the docs.

I know you don't want to revert the original patchset moving the GPIO definitions to DTS, but it's probably the right thing to do in this case.  These drivers and the docs can all be fixed at the same time when the original patchset is reworked.

**Comment by mike-scott** [comment]
> I'm not sure I would say this is a hack. It's just changing how the Kconfig value gets set by default. I'm also not clear what the doc issue exactly is.
Doesn't this patch hard-code the names of GPIO ports as config items?  Seems like the correct approach would be to configure the driver to accept DTS defines where it was applicable.  Your PR: https://github.com/zephyrproject-rtos/zephyr/pull/7189 would allow for that.

**Comment by mbolivar** [comment]
@galak @mike-scott 
>> I'm not sure I would say this is a hack. It's just changing how the Kconfig value gets set by default.
> Doesn't this patch hard-code the names of GPIO ports as config items? Seems like the correct approach would be to configure the driver(s) to use DTS-based GPIO LABEL defines where applicable. Your PR: #7189 would allow for that.

There hasn't been any progress on #7189 in a week. Any chance that we can merge the revert (https://github.com/zephyrproject-rtos/zephyr/pull/7181) in the interests of closing the medium priority issue (#7172)?

Moving to DTS properly can be finished when there is time, but this seems like low hanging fruit to decrease the bug count as discussed at today's TSC meeting.

**Comment by galak** [comment]
This is now cleaned up by #7355

**Pull request closed without merging**
