### PR TITLE
drivers: ieee802154: rf2xx: Add config enhancements

### PR DESCRIPTION
**Pull request by nandojve**
Add following enhancements:
 - tx mode direct
 - tx mode CCA 
 - enable promiscuous mode
 - enable pan coordinator mode

Fix small backslash alignment.

CC: @markus-becker-tridonic-com

### CODE REVIEW

**Review by jukkar — APPROVED** [review]

**Comment by nandojve** [comment]
Hi @tbursztyka ,
I was wondering if there is anything pending from your side.

**Comment by markus-becker-tridonic-com** [comment]
@nandojve LGTM.

do you think it would be possible to support IEEE802154_TX_MODE_TXTIME with rf2xx? OpenThread requires this for Thread 1.2. I believe the chip does not immediately support it, but would it be possible to mimic it in software?

**Comment by nandojve** [comment]
> @nandojve LGTM.
> 
> do you think it would be possible to support IEEE802154_TX_MODE_TXTIME with rf2xx? OpenThread requires this for Thread 1.2. I believe the chip does not immediately support it, but would it be possible to mimic it in software?

I don't see why not. But we need add something that will help us with time functions. I'm not sure what is best path here.
If radio don't require listen, for instance, it is possible load payload and wait a "timer" to release package.

I'm not aware about all requirements related to OT 1.2 but, for sure, we can collaborate to achieve that.

**Comment by nandojve** [comment]
rebase

**Review by rlubos — APPROVED** [review]

**Pull request merged**
