### PR TITLE
arch: arm: mpu: Make XN bit conditional on CONFIG_XIP for RAM region

### LINKED ISSUE #50652: RAM Loading on i.MXRT1160_evk
**Describe the bug**
   
   --> Want to run zephyr application from SDRAM location using RAM Loading feature.

**Information**

- Build the code for SDRAM using CONFIG_CODE_SEMC=y. However, when I test with this, I see when z_bss_zero() is called in the startup code, it trashes the code memory in SDRAM. 

- So it seems the linker settings for this RT1160 are not configured for CONFIG_CODE_SEMC=y, and allow the BSS section to overlap code in SDRAM.

**Expected behavior**
  
   --> Copy the content from FLASH to given SDRAM location and execute from SDRAM.

Thanks,
Sathishkumar K

### PR DESCRIPTION
**Pull request by danieldegrasse**
Make the execute never (XN) bit conditonal on CONFIG_XIP for the RAM MPU region attribute. This is required because when CONFIG_XIP is not set, the entire image will be linked into SRAM. In this case, SRAM must be executable.

The alternative to this would be to configure two MPU regions within the SRAM region (one with the XN bit set, and the other with it clear). However, trying to use linker symbols in order to initialize the ARM MPU regions needed for this setup results in the build failing with the error: `initializer element is not computable at load time`.

I'm open to any ideas for a better approach for how to handle `CONFIG_XIP=n` on ARM Cortex M platforms, since currently the MPU must be disabled to run an image built with `CONFIG_XIP=n` on this architecture.

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@carlocaione Would be interested in any feedback you have here- the benefit I see to enabling `CONFIG_XIP=n` to function on Cortex M parts (versus defining two regions within the SRAM address space, and using one as "flash"), is that the linker can more efficiently utilize the SRAM space, since no padding is needed between the text and data sections

**Review by microbuilder — CHANGES_REQUESTED** [review]
This looks good to me, but can you maybe add a comment here noting why this is being added, as a future signpost? Something like:

```c
// On Cortex M, currently the MPU must be disabled when running an image from
// SRAM (CONFIG_XIP=n). This means that we can only set the XN flag
// when XIP=y (running from flash memory, etc.), otherwise the application code
// in the default SRAM memory region won't be executable.
```

I wasn't aware of the restriction that the MPU can't be used when running from SRAM, since I'm generally working with flash memory for code.

**Comment by povergoing** [comment]
> This looks totally reasonable to me. I'm kinda confused why cortex-R and NXP are instead using `CONFIG_MPU_ALLOW_FLASH_WRITE` to control the `X` bit of the SRAM MPU region.

This is reasonable. I am not clear with what NXP is doing, but in terms of FVP, unfortunately, there is no XIP support for R.

**Comment by danieldegrasse** [comment]
> This looks good to me, but can you maybe add a comment here noting why this is being added, as a future signpost? Something like:

Sure, I've added a comment explaining why we do not set the XN bit when `CONFIG_XIP=n`.

**Review by microbuilder — APPROVED** [review]

**Review by povergoing — APPROVED** [review]

**Pull request merged**
