### PR TITLE
arch: arc: fix the bug of irq_offload

### PR DESCRIPTION
**Pull request by vonhust**
* remove irq lock/unlock which is not needed because of
  the protection of offload_sem in irq_offload
* simplify the assembly codes related irq_offload, remove
  the thread switch logic

### CODE REVIEW

**Comment by ruuddw** [comment]
This looks like a good simplification of the code, but can you add some further explanation of what this fixes? irq lock would be stronger than a scheduler lock, unless the irq offload syscall triggers a reschedule.
Would the scheduler lock be something specific for ARC, or could it be moved to the generic irq_offload in thread.c?
I see different implementations for different architectures, some lock interrupts, some the scheduler.

**Comment by vonhust** [comment]
> This looks like a good simplification of the code, but can you add some further explanation of what this fixes? irq lock would be stronger than a scheduler lock, unless the irq offload syscall triggers a reschedule.
> Would the scheduler lock be something specific for ARC, or could it be moved to the generic irq_offload in thread.c?
> I see different implementations for different architectures, some lock interrupts, some the scheduler.

codes in irq_offload can raise the scheduling as it's used to simulate the behavior  of irq and irq routine can call  some sys API, e.g. give_semaphore, so here scheduler lock should be used to check whether it requires a scheduling.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
> irq routine can call some sys API, e.g. give_semaphore, so here scheduler lock should be used to check whether it requires a scheduling.

That doesn't seem right, and suggests to me that the ARC implementation of `arch_irq_offload()` isn't correct.

The test in tests/kernel/common/src/irq_offload.c verfies the result if k_is_in_isr() when inside the IRQ handler. Giving a semaphore inside an irq offload handler should not have the kernel try to swap out *inside the handler*.

If this is actually happening, what is the difference in execution context in an irq offload handler, and a real interrupt? by definition they should be the same!

Now if the kernel decides to swap out after the irq offload handler has completed, this is expected behavior, just like a normal interrupt which gives a semaphore.

**Comment by andrewboie** [comment]
and just another note: locking the scheduler does not solve concurrency problems *on another CPU*

**Comment by andrewboie** [comment]
to add more detail: if you look at z_reschedule(), it only swaps if resched() returns true...and that has a check for arch_is_in_isr().

**Comment by ruuddw** [comment]
Thanks Andrew for the hints. I found the schedule locking a bit suspicious, but ARM does it as well I believe. Guess the thing to check and maybe fix is the is_in_isr part, instead.

**Comment by andrewboie** [comment]
> I found the schedule locking a bit suspicious, but ARM does it as well I believe

Needs to be removed if that's the case

**Comment by vonhust** [comment]
@andrewboie  Thanks for you review. Here is my understanding

1. irq_offload is some kind of sw interrupt simulation. Because we don't know which interrupt to use and need a sync interrupt (real int may be not sync). So here we use trap exception to simulate int and get into interrupt context.  Architecture like ARM aslo uses exception to do that.

2. irq_offload_handler may rasie a potentital thread swich request, i.e. update the ready queue,  won't do a thread swith by z_swap. The job of thread switch will be done in the epilogue of interrupt or exception handling(see codes in regular_irq.s). 

3.  As exception is used for irq offload and to make codes simpler (see i removed lots of code in fault_s.S),   there is no thread switch codes in the epilogue code of irq_offload exception. But we need to have a scheduling point after arch_irq_load.  So k_sched_lock/unlock are used, where k_sched_unlock is such a scheduling point.  irq_lock/unlock don't make a scheduling point.

4. I already ran the sanitcheck test about irq_offload, no failures

5. It seems irq_load is used to get into local interrupt context, it seems no concurrency problem with cpu.

6. Considering offload_sem is used to sync irq_offload,   i think k_sched_lock/unlock can be removed as give offload_sem is a scheduling ponit.  I will take a try.

**Comment by vonhust** [comment]
offload_sem  is used to protect offload_routine and offload_parameter, i thinks k_sched_lock/unlock can be removed. Other arch like ARM, x86 should aslo do a fix.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by abrodkin — COMMENTED** [review]
Similarly to Ruud's comment I'd like to see more verbose explanation of which bug in particular we're fixing here. If the main point of this commit is code clean-up then probably we may want to change its title to mention it instead of bug fix.

**Comment by vonhust** [comment]
This PR can fix #22559 and #22624

**Comment by vonhust** [comment]
> Similarly to Ruud's comment I'd like to see more verbose explanation of which bug in particular we're fixing here. If the main point of this commit is code clean-up then probably we may want to change its title to mention it instead of bug fix.

I update the commit msg to describe why it's bug. It may cause irq_offload related codes crash

**Review by abrodkin — APPROVED** [review]
@vonhust ok now it makes more sense. Thanks for re-spinning.

**Pull request merged**
