### PR TITLE
tests: watchdog: Added support for esp32

### PR DESCRIPTION
**Pull request by vikramx2112**
Added support of esp32 for polling and interrupt mode in watchdog
testcases.
Signed-off-by: Vikram Singh Shekhawat <vikramx.shekhawat@intel.com>

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
We should be reworking the test to be more generic, not adding more specific details unique to a give platform.

**Comment by lpereira** [comment]
I have an [experimental branch](https://github.com/lpereira/zephyr/tree/esp32-watchdog) implementing two new APIs for the watchdog device: ability to get boot reason, and access to a retained value.  These should be sufficient to write these tests in a platform-agnostic way.

**Comment by vikramx2112** [comment]
Will update the changes once new api changes will merge in wdt driver.

**Comment by vikramx2112** [comment]
@lpereira , Are we going to merge the retention reg and reset reason entry point in WDT drivers. As this test case is still waiting for new driver changes.

**Comment by lpereira** [comment]
I completely forgot about this, @vikramx2112.  The new watchdog API (on #1260) do not contemplate adding the boot reason and access to a value retained by the watchdog.

**Comment by vikramx2112** [comment]
@lpereira , Any idea when we will include the changes of retention reg and reset reason entry point in WDT drivers.

**Comment by lpereira** [comment]
No idea, @vikramx2112. It's likely this won't be added, as it's not something supported by all platforms supported by Zephyr.

@m-kru, on your investigations while rethinking the watchdog API, have you encountered any other platform with this feature?

**Comment by m-kru** [comment]
@lpereira You mean retention register and reset reason?

Yes I have encountered both but I have never seen them as a part of watchdog peripheral.

**Comment by lpereira** [comment]
@m-kru Yeah, ESP32 is usually the odd one out.  It sort of makes sense in this case, though. These things can be implemented as another driver class.

In any case, I'm closing this issue, as it doesn't make sense to add this to the watchdog driver class as it's a peculiarity of this SoC.

**Comment by vikramx2112** [comment]
@lpereira , what about the esp32_wdt_test app changes. Are we going to merge this one or not. As latest wdt_test app is used to test quark devices only. How we are going to test esp32 wdt driver.

**Comment by lpereira** [comment]
We're not going to merge this one.  We can use the information frmo this patch to create a few driver classes so we can get the reset reason, and store/restore the retention register values.  The reason is, as stated by @m-kru, this is something present in other microcontrollers, but they're usually not in the watchdog peripheral as it is in the ESP32.

**Pull request closed without merging**
