### PR TITLE
fix USB pinmux for two stm32f103-based boards

### LINKED ISSUE #16191: boards/arm/{olimexino_stm32, stm32_min_dev}: USB pinmux setup is skipped
**Describe the bug**
USB-related pinmux setup is skipped for two stm32f103-based boards: olimexino_stm32 and stm32_min_dev.

**To Reproduce**

Compile ```samples/subsys/usb/cdc_acm``` for ```olimexino_stm32`` with ```#error 1``` inserted into USB-related block:

```shell
patch -p1 <<EOF;
--- a/boards/arm/olimexino_stm32/pinmux.c
+++ b/boards/arm/olimexino_stm32/pinmux.c
@@ -46,6 +46,7 @@ static const struct pin_config pinconf[] = {
        {STM32_PIN_PA8, STM32F1_PINMUX_FUNC_PA8_PWM1_CH1},
 #endif /* CONFIG_PWM_STM32_1 */
 #ifdef USB_DC_STM32
+#error 1
        {STM32_PIN_PA11, STM32F1_PINMUX_FUNC_PA11_USB_DM},
        {STM32_PIN_PA12, STM32F1_PINMUX_FUNC_PA12_USB_DP},
 #endif /* USB_DC_STM32 */

EOF

cd samples/subsys/usb/cdc_acm
rm -rf build && mkdir build && cd build
cmake -DBOARD=olimexino_stm32  ..
make
```

**Expected behavior**
After inserting ```#error 1``` I expect compilation abort, but compilation success.

The file boards/arm/stm32_min_dev/pinmux.c is affected by the same problem.

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.10.0
 - Zephyr git describe: zephyr-v1.14.0-817-g07d21bef0d

### PR DESCRIPTION
**Pull request by frantony**
Fixes #16191

### CODE REVIEW

**Review by ydamigos — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Can you open an issue for the usb pinmux fix?  Might be nice if this was split into 2 PRs, one for the bug fix and one for the "enhancement" to the olimexino_stm32

**Review by erwango — APPROVED** [review]

**Comment by frantony** [comment]
@galak 
> Can you open an issue for the usb pinmux fix? Might be nice if this was split into 2 PRs, one for the bug fix and one for the "enhancement" to the olimexino_stm32

I have just opened new issue https://github.com/zephyrproject-rtos/zephyr/issues/16191

**Comment by galak** [comment]
> I have just opened new issue #16191

thanks, I know its a bit of extra work, but you can split the commits into 2 PRs.  Helps us take just the bug fix commit/PR for LTS.

**Comment by frantony** [comment]
@galak @ydamigos 
I have just separated *the "enhancement" to the olimexino_stm32* into individual PR https://github.com/zephyrproject-rtos/zephyr/pull/16192.

**Comment by frantony** [comment]
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/16191

**Pull request merged**
