### PR TITLE
Bluetooth: Controller: Fix DLE HCI params parsing

### LINKED ISSUE #44164: Implement the equivalent of PR #44102 in LLCP
Implement the equivalent of PR #44102 in LLCP

PR #44102 fixes an issue in the legacy controller,  which we also need to handle in the refactored LLCP

### PR DESCRIPTION
**Pull request by sjanc**
LE Write Suggested Default Data Length and LE Set Data Length commands
are suggestions from host and should be validated only as per HCI
specification regarding internal setting of LLCP.

LLCP is allowed to use other values is needed.

fixes #44164

Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

### CODE REVIEW

**Comment by kruithofa** [comment]
fixes #44164

**Comment by carlescufi** [comment]
@cvinayak please review

**Review by cvinayak — COMMENTED** [review]
Changes look good and do not affect the conformance tests (HCI tests pass). The CI failure needs addressing though.

**Review by kruithofa — APPROVED** [review]

**Comment by cvinayak** [comment]
No objections from me. If this is passing latest TCRL based conformance tests, you have my approval.

@thoh-ot Please get a review at your side.

**Review by erbr-ot — APPROVED** [review]
LGTM - did an EBQ run (HCI and CON tests) with this commit on Oticon target with no added failures.

**Review by cvinayak — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
Should this go for 3.2.0? The matching issue is tagged as Enhancement... tagging for 3.3.0, feel free to move it as necessary.

**Pull request merged**
