### PR TITLE
Instant doc/ gratification: do not re-run doxygen when not needed

### PR DESCRIPTION
**Pull request by marc-hb**
Use file(GLOB_RECURSE ...) to generate a superset of doxygen input
files. Use this list as a dependency for a new empty file
doc/_build/last_doxy_run_tstamp.
    
The incremental build time to re-run "make htmldocs-fast" after a small
.rst doc change is brought down from from ~8s to ~4s on my Linux system
 and from ~30s to less than 10s on my MacBook.
    
Doxygen changes are still slow for a couple reasons isolated and
documented in doc/CMakeLists.txt)

### CODE REVIEW

**Review by dbkinder — COMMENTED** [review]
So I'm wondering... since we only document **public** APIs for Zephyr, do we need to have doxygen scanning ``.c`` and ``.S`` files?  Would only looking at ``.h`` file be sufficient?  Doing that would reduce the opportunity for doxygen comment changes (in implementations) affecting the doc build...

**Comment by marc-hb** [comment]
> So I'm wondering... since we only document **public** APIs for Zephyr, do we need to have doxygen scanning `.c` and `.S` files? Would only looking at `.h` file be sufficient?

Good question but... somewhat off-topic for now?

>  Doing that [only .h] would reduce the opportunity for doxygen comment changes (in implementations) affecting the doc build...

Yes, scanning only .h files could save some people time two ways:
1. even _without_ this optimization because doxygen could run a bit faster, cf. Doxyfile
2. even more _after_ this is optimization cause doxygen would be run less often, cf. CMakeLists.txt

About 1. I just did a quick test with INPUT=*.h only in Doxyfile and the number of generated doxygen/xml files dropped from 1700 to 1400 with a pretty minor build time improvement.

BTW Doxygen defaults are tuned for .h files. I've been maintaining a set of "alternate Doxygen defaults" for .c files (EXTRACT_everything = YES; SOURCE_BROWSER = YES, etc.) because Doxygen also makes a very good code browser. This is a different use of the same tool, I wonder why some .c files are being scanned by Zephyr now, maybe doxygen is currently configured somewhere in the middle?

Anyway I think someone said it was off-topic.

**Review by dbkinder — APPROVED** [review]

**Comment by marc-hb** [comment]
Fix for minor conflict with PR #13521, zero code change.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Tested on Windows and fixed the comment, thank you very much for this, it's blazing fast now!

**Pull request merged**
