### PR TITLE
drivers: adc: mcux_adc12: fix compilation

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Fix compilation of NXP MCUX ADC12 driver shim after commit
d4a0c3a2aa9b1b99949caa9f0ad34a0e8e3883db.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
@galak It appears this was broken by your `DT_INST_*` change.

**Comment by MaureenHelm** [comment]
are we missing coverage for this driver in CI?

**Comment by henrikbrixandersen** [comment]
> are we missing coverage for this driver in CI?

@MaureenHelm No, it is covered by `tests/drivers/adc/adc_api/`. The latest changes are causing CI failures in both #16867 and #16251. I do not how those changes made it through CI at all.

**Review by galak — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
> > are we missing coverage for this driver in CI?
> 
> @MaureenHelm No, it is covered by `tests/drivers/adc/adc_api/`. The latest changes are causing CI failures in both #16867 and #16251. I do not how those changes made it through CI at all.

For some reason, there are no CI results on #16815, where the change was introduced?

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
