### PR TITLE
Bluetooth: controller: use inclusive naming

### PR DESCRIPTION
**Pull request by cvinayak**
Use centrl/perip, denylist/allowlist, decorr/decorrelation
in implementation naming.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by George-Stefan — APPROVED** [review]

**Comment by George-Stefan** [comment]
Looks fine at a quick review, but the CI failures must be fixed

**Review by carlescufi — CHANGES_REQUESTED** [review]
We agreed in the TSC and board discussions that these changes would be made in the code only when the corresponding specification has changed as well. Otherwise this is going to be extremely confusing for other people to look at and try to match the spec.

**Review by alexandru-porosanu-nxp — APPROVED** [review]
LGTM

**Comment by cvinayak** [comment]
> 
> 
> We agreed in the TSC and board discussions that these changes would be made in the code only when the corresponding specification has changed as well. Otherwise this is going to be extremely confusing for other people to look at and try to match the spec.

Yes, the changes can wait.

There is very few that is specification related; filename, variable names etc. being at the discretion of the implementation can anytime be inclusive.

This PR is converted to draft, and gives an estimation of changes required when the names are decided.

**Comment by jettr** [comment]
I noticed you used `central` instead of something like `controller` as the replacement for master. Is there consensus on this replacement for I2C somewhere that you can reference or link to?

SPI for instances plans to use `controller` as the replacement for master: https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names

Also, linking this to the issue I just filed #27000

**Comment by cvinayak** [comment]
> I noticed you used central instead of something like controller as the replacement for master. 

In the Bluetooth Architecture, controller is defined as a logical entity below the Bluetooth Host Controller Interface (HCI). A collective term referring to all of the layers below HCI.

A Central and Peripheral are two of four roles in Bluetooth's Generic Access Profile (GAP).

In the original implementation of the now contributed Zephyr BLE controller, my ideas for the scheduling design (ticker.c/.h) was based on the concept of `Conductor of Orchestra`. I saw the peripherals as being directed to perform at a said interval etc.

I will go with what the Bluetooth Specification adopts (, this draft PR is an exercise to estimate effort/dependencies etc.).

**Comment by cvinayak** [comment]
Changes in Terminology in Bluetooth Specification: https://btprodspecificationrefs.blob.core.windows.net/language-mapping/Appropriate_Language_Mapping_Table.pdf

image

**Comment by erbr-ot** [comment]
I'm wondering if using 'perip' and 'centrl' in the code is so as to avoid code lines to become to long?
To me it is noisy to not use 'peripheral' and 'central', and I'd suggest to go all in on the name change.

**Comment by cvinayak** [comment]
Changes incorporated upstream.

**Pull request closed without merging**
