### PR TITLE
net: tcp: Cleanup context if connection is not established

### PR DESCRIPTION
**Pull request by jukkar**
If we are closing connection before the connection was established,
then unref the context so that the cleanup is done properly.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
This fixes the issue I was seeing but it introduces failures in tests. It requires a bit more work still.

**Comment by jukkar** [comment]
Fixed the sanity issue.

**Comment by jukkar** [comment]
Added test case for the issue.

**Review by rveerama1 — APPROVED** [review]

**Comment by jukkar** [comment]
Enhancing the unit test.

**Pull request merged**
