### PR TITLE
k_thread_abort(): fail assert if abort essential thread

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Previously, this was only done if an essential thread self-exited.
Now if any thread has k_thread_abort() called on it, and that thread
is essential to the system operation, this check is made.

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Review by agross-oss — APPROVED** [review]
Looks good to me.

**Review by andyross — DISMISSED** [review]
Can't this just be an assert?  What's the use case for wanting runtime checking on what is clearly buggy behavior?

It's not wrong, but extra code is extra code.  Who would ever do this?

(Actually looking more closely the action of the patch is just to move the check from one place to another, so no net code size change.   I withdraw the complaint, but leave the question about "why do we care?" in place because I'm curious)

**Comment by andrewboie** [comment]
I don't know the full history behind this, but I needed it moved because _new_thread may run in user mode, in which case things like _is_thread_essential() are not callable.
I could make this an __ASSERT(), will update.

**Comment by andrewboie** [comment]
update: now an assertion

**Review by andyross — APPROVED** [review]

**Pull request merged**
