### PR TITLE
include: scripts: linker: Create multi-image shared memory section

### PR DESCRIPTION
**Pull request by sigvartmh**
To be able to pass or retain information between multiple images such as a
boot loader and a zephyr application a shared RAM section needs to be available.
This commit adds a shared memory region called `SHARED_SRAM` which the linker
script then can use in anyway it wants. Like using the `custom-section.ld` file
to place a custom section in a shared region; of course this needs to be
configured for both the boot loader and application. Or use the available `zephyr_code_relocate` function in CMake and place data in a shared region.

### Rationale
This is an RFC because I'm really unsure if this is something Zephyr wants to support but it's useful in code sharing between a boot loader and application(if desired) 

### Use case
Keeping persistent debug info/buffer when developing with a boot loader.  When you do a jump from the boot loader to an application and you are doing deferred logging in the boot loader and application the log buffer could be lost because you are switching to another image before the logs are outputted through the back-end, those logs are lost and non-recoverable.

You could also use this space to store other useful information which you want to retain from the boot loader to the application.

### Point of discussions
People could just derive their own linker-script from `linker.ld` and add the memory regions they want themselves. So why is this needed?

> @sigvartmh: It could be nice to have a configurable region already available so that most use-cases are covered. This way a lot of use-cases don't have to derive a `custom linker-script.ld`then track any upstream changes done to this file.

Signed-off-by: Sigvart Hovland <sigvart.m@gmail.com>

### CODE REVIEW

**Comment by sigvartmh** [comment]
@SebastianBoe If you have time please have a look also :)

**Comment by sigvartmh** [comment]
@MaureenHelm @galak any feedback?

**Comment by erwango** [comment]
Hi @sigvartmh,

I think the proposal is indeed interesting but it would be even more useful to get it directly from device tree, with possibility to define more than one shared section (I'd need 2 actually :-)).

**Comment by sigvartmh** [comment]
> I think the proposal is indeed interesting but it would be even more useful to get it directly from device tree, with possibility to define more than one shared section (I'd need 2 actually :-)).

I haven't really considered the possibility of needing more than one but that's certainly another approach. If it should be placed in the device tree it would have to be in som sort of overlay that is included on selection. Since DTS is running before KConfig this would prove itself to be a bit difficult so I'm not really sure how one would go a head and solve this.

I guess since you are saying that you would need two declared RAM sections I guess they can't be placed with `__attributes__` rather than actually being separate sections in the linker script. I haven't had the use case of having n-separated ram regions but I'm sure there is a few so I wouldn't' really rule it out but I'm a bit unsure of a sustainable way of doing this.

**Comment by nashif** [comment]
stale for a long time already..

**Pull request closed without merging**
