### PR TITLE
manifest: update LVGL to v8.3.7

### PR DESCRIPTION
**Pull request by faxe1008**
Related to [zephyrproject-rtos/lvgl#41
](https://github.com/zephyrproject-rtos/lvgl/pull/41)

### CODE REVIEW

**Comment by pdgendt** [comment]
@faxe1008 thanks for putting the effort in this, can you update the sample as discussed in #53974 as well here?

**Review by pdgendt — APPROVED** [review]

**Comment by faxe1008** [comment]
@pdgendt I am not sure what sample you are refering to. According to the discussion with @kisvegabor in [pull/53974#issuecomment-1606850642](https://github.com/zephyrproject-rtos/zephyr/pull/53974#issuecomment-1606850642) I changed the order of operations in the twister tests in the zephyr repo (this PR), since the test should not have worked like this in the first place. The sample located at `samples/subsys/display/lvgl` builds just fine for me.

**Comment by pdgendt** [comment]
> @pdgendt I am not sure what sample you are refering to. 

I meant the test, it's fine now.

**Comment by faxe1008** [comment]
Fixed a typo in last commit message :^)

**Review by pdgendt — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]

**Comment by faxe1008** [comment]
@carlescufi I updated the src rev :^)

**Review by pdgendt — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
