### PR TITLE
dts: bindings: ethernet: Remove fixed link

### LINKED ISSUE #70323: dts: bindings: ethernet-fixed-link.yaml: Ethernet fixed link requires hardcoding node labels in drivers
**Problem**
Ethernet fixed link scheme causes node label to need to be hardcoded into drivers.

**Describe the solution you'd like**
Remove ethernet-fixed-link.yaml and describe all phys properly in DT.

**Describe alternatives you've considered**
- Have a compatible on the fixed link node and find the node from that.
- Make the fixed link parameters optional properties on the ethernet controller node instead of making a child node.

### PR DESCRIPTION
**Pull request by decsny**
Remove ethernet-fixed-link binding as it is redundant with the phy bindings. Clearly, ethernet does not work without the L1 layer, which is a phy device, or an integrated mac/phy device, and all of these things should be described properly in DT. The schema did not even come with a compatible, meaning nodelabels were hardcoded into the drivers, which is unacceptable.

- Remove the binding file for ethernet-fixed-link.yaml.
- Remove fixed link functionality from the nxp s32 gmac driver. Since this functionality is already covered by the phy support, it is redundant.
- Remove fixed link include from the s32 gmac binding.
- Remove fixed link include from the nuvoton numaker binding. As far as I can tell the corresonding driver does not even use it anyways, and I did not find any board with this device that describes a "fixed link".
- Move the definition into the nxp,kinetis-ethernet binding as the eth_mcux driver, which is already being deprecated, does use this, contain the debt to the legacy driver.

Fixes #70323

### CODE REVIEW

**Review by manuargue — DISMISSED** [review]
No objections

**Review by cyliangtw — DISMISSED** [review]
LGTM at the update of nuvoton,numaker-ethernet.yaml

**Review by manuargue — APPROVED** [review]

**Review by cyliangtw — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Comment by decsny** [comment]
@galak

**Comment by decsny** [comment]
@fabiobaltieri I don't think I can be assignee and author, then it would never get assignee approval...

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri I don't think I can be assignee and author, then it would never get assignee approval...

It's fine, the whole change is under Ethernet and you are the only name in the maintainer file there, author+assignee is also ok, there's no rule against that and the bot does it all the time, you still need to check all the other rules for this to get merged anyway.

**Pull request merged**
