### PR TITLE
DGRAM: Add a test to verify L2 header removal

### PR DESCRIPTION
**Pull request by krish2718**
As per [1] DGRAM packet sockets L2 header processing is handled by the
networking stack based on the "sll" structure, and only the payload is
handled by the application, but this is not working as expected, so,
extend the test to demonstrate this failure by checking for data
validity.

[1] - https://docs.zephyrproject.org/3.0.0/reference/kconfig/CONFIG_NET_SOCKETS_PACKET_DGRAM.html

Signed-off-by: Krishna T <krishna.t@nordicsemi.no>

### CODE REVIEW

**Comment by krish2718** [comment]
Opened a bug for the actual issue https://github.com/zephyrproject-rtos/zephyr/issues/45514

**Comment by krish2718** [comment]
FYI, tests failing is expected as this PR is mainly to demonstrate the bug.

**Comment by jukkar** [comment]
Are you planning to submit a fix that strips away L2 header? This commit could be part of that PR.

**Comment by krish2718** [comment]
Yes, looking at the effort required for the fix. But wanted to get a confirmation of the issue first.

**Comment by krish2718** [comment]
Test and fix covered as part of #45592

**Pull request closed without merging**
