### PR TITLE
Bluetooth: Host: Refactor legacy adv creation

### LINKED ISSUE #78721: Bluetooth: Starting an already started advertiser messes up state
**Describe the bug**
1. Call `bt_le_adv_start()`
2. Call `bt_le_adv_start()` again -> will return EALREADY. But internally the state is messed up.
3. Call `bt_le_adv_start()` again -> The host thinks the advertiser is not running 

Fix: Do not call `bt_le_adv_delete_legacy()` upon error. Is this safe?

Triggers here: https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/periodic_sync_rsp/src/main.c#L234 if a sync is not established within 10 seconds

### PR DESCRIPTION
**Pull request by ludvigsj**
This fixes #78721 which was introduced in PR #44686, which changed (and renamed) `adv_new_legacy`/`adv_get_legacy` to return an existing `bt_dev.adv` if it existed. This caused a problem, where the existing adv then would be used to start advertising, and if this fails (because the adv is already advertising, for instance), `bt_le_adv_start` would erroneously delete the adv, making the host lose the context for the adv which still is advertising.

Before PR #44686, this would not happen, because `bt_le_adv_start` would return early when `adv_new_legacy` returned `NULL` and never reach the delete call.

I have refactored this to make responsibilities a bit more clear: `adv_create_legacy` now does 1 thing: create an ext adv and assign as the legacy advertiser. This mirrors `bt_le_adv_delete_legacy` which does the opposite. I have implemented error codes to match the behavior that PR #44686 was made to implement.

### CODE REVIEW

**Comment by ludvigsj** [comment]
I suspect this question might show up during review, so I'll answer it right now: I _could_ have solved this by only calling `bt_le_adv_delete_legacy` in `bt_le_adv_start` if the error was `!= -EALREADY`. I decided against this, because that would put an invisible contract on both `bt_le_adv_start_ext` and `bt_le_adv_start_legacy` that they both return `-EALREADY` if (and only if!) the problem was that the `adv` passed in was already advertising, which could easilly be missed and broken again in the future.

**Comment by Thalley** [comment]
@ludvigsj took me a bit time to understand, but correct me if I'm wrong:

You have some case similar to 
1) App calls `bt_le_ext_adv_create` and creates a legacy advertiser
2) App calls `bt_le_adv_start`, but it fails to start for whatever and delete the legacy advertiser from 1) when calling `bt_le_adv_delete_legacy`

Where with your change you have
1) App calls `bt_le_ext_adv_create` and creates a legacy advertiser
2) App calls `bt_le_adv_start`, but this will now fail with -ENOMEM, and thus won't call `bt_le_adv_delete_legacy`

**Comment by ludvigsj** [comment]
> @ludvigsj took me a bit time to understand, but correct me if I'm wrong:
> 
> You have some case similar to
> 
> 1. App calls `bt_le_ext_adv_create` and creates a legacy advertiser
> 2. App calls `bt_le_adv_start`, but it fails to start for whatever and delete the legacy advertiser from 1) when calling `bt_le_adv_delete_legacy`
> 
> Where with your change you have
> 
> 1. App calls `bt_le_ext_adv_create` and creates a legacy advertiser
> 2. App calls `bt_le_adv_start`, but this will now fail with -ENOMEM, and thus won't call `bt_le_adv_delete_legacy`

No, this is the legacy API, the app will never call `bt_le_ext_adv_create` as far as I know? `bt_le_adv_start` is the single entrypoint when using legacy advertising (even with `CONFIG_BT_EXT_ADV` set), unless I have misunderstood.

The problem that I'm fixing would show up when the app calls `bt_le_adv_start` multiple times while the (legacy) advertising was alredy running from a previous call to `bt_le_adv_start`. Previously (before this bug was introduced), the `bt_le_ext_adv` would be created inside `bt_le_adv_start`, not by the app. If this failed, it would return early and skip trying to start advertising. I've gone back to this behavior, but with more informative error codes (which was the reason why the PR introducing this bug was made in the first place).

**Comment by ludvigsj** [comment]
Basically, the current behavior:

1. App calls `bt_le_adv_start`. This causes the creation of a `bt_le_ext_adv` with context. All calls succeed
2. App calls `bt_le_adv_start` again. This causes the host to try starting advertising again using the same `bt_le_ext_adv` created in step 1. Which fails, of course, and then that context is deleted(!).
3. The host has now lost the context for the advertising started in step 1, which is still advertising in the controller.

The new behavior is:

1. App calls `bt_le_adv_start`. This causes the creation of a `bt_le_ext_adv` with context. All calls succeed.
2. App calls `bt_le_adv_start` again. This causes the host to try to create a `bt_le_ext_adv`, but it will not be able to, and will return with error code.
3. The context created in step 1 is not touched.

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Pull request merged**
