### PR TITLE
Revert "samples/audio: Add Sound Open Firmware"

### PR DESCRIPTION
**Pull request by galak**
This reverts commit efa794dbc5fe2d0b406f953be5be09caeaac03ab.

Sample doesn't build currently and has issues when builds are done via
twister on platforms not supported by SoF.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
I suggest we revert the sample for now until its in a working state.

**Comment by nashif** [comment]
> I suggest we revert the sample for now until its in a working state.

Can't we fix this with filters instead? what issues are you seeing exactly? I know that qemu_xtensa for example will not work and I was about to submit a fix for that, what else?

**Comment by nashif** [comment]
oh, the other thing needed is a call to a west extension to update submodules while we wait for this feature to be merged in west.

**Comment by nashif** [comment]
alternative https://github.com/zephyrproject-rtos/zephyr/pull/31157

**Pull request closed without merging**
