### PR TITLE
manifest: TF-M: Update to include fix for fwu partition build error

### PR DESCRIPTION
**Pull request by theotherjimmy**
In particular, the update of mcuboot cause this issue, as mcuboot
changed the type of mcuboot_img_magic which tf-m has fixed upstream.

Signed-off-by: Jimmy Brisson <jimmy.brisson@linaro.org>

### CODE REVIEW

**Review by microbuilder — CHANGES_REQUESTED** [review]
Please add a commit to update https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/guides/tfm/requirements.rst to reference imgtool 1.9.0, and any other changes based on `trusted-firmware-m/bl2/ext/mcuboot/scripts/requirements.txt`.

**Comment by theotherjimmy** [comment]
@microbuilder Updated. Thanks.

**Comment by theotherjimmy** [comment]
Updated to include the now-merged upstream(?) hash.

**Review by microbuilder — APPROVED** [review]

**Review by joerchan — APPROVED** [review]
Checked SHA.

**Pull request merged**
