### PR TITLE
cmake: modules: boards: do not error on multiple board definitions

### PR DESCRIPTION
**Pull request by danieldegrasse**
Instead of throwing an error on multiple board definitions, select the first definition provided. This allows directories defined earlier in BOARD_ROOT to contain board definitions that override in tree board definitions. For example, this can be used by a module to replace an in tree board definition if desired.

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@tejlmand Interested in your thoughts on this change. The idea here is to allow a module to replace a board definition. With HWMv2, this is currently possible with SOCs (IE if a directory in SOC_ROOT defines an SOC with the same name as an in tree SOC, the out of tree definition will be used instead). I'm not sure if this was intentional, but the idea with this change is to make the same kind of override possible for boards

**Review by nordicjm — CHANGES_REQUESTED** [review]
> The idea here is to allow a module to replace a board definition

Hate the idea, you're the creating a mess of "if I have 17 board definitions of the exact same board in different repos, which one is going to be used?"

**Comment by dleach02** [comment]
> > The idea here is to allow a module to replace a board definition
> 
> Hate the idea, you're the creating a mess of "if I have 17 board definitions of the exact same board in different repos, which one is going to be used?"

It is in the intro to the PR: "select the first definition provided".

Here is the use case, you have your downstream and a manifest repository with a board/soc definition. This manifest repo also pulls in either a downstream of Zephyr or the actual upstream of Zephyr. As you start moving the board/soc definition to the upstream, it will be in various states of completeness until it is fully upstreamed. With this particular enhancement to the build system, your downstream will continue to function with the full features.

**Comment by nordicjm** [comment]
> It is in the intro to the PR: "select the first definition provided".

But it's not, because what you do here is allow multiple, if you have the same board defined in multiple repositories, all of which you pull, which one will be picked? It allows users to create an evil mess that they're unaware of because they think they're doing something with a board and actually their definitions are being completely ignores

**Comment by dleach02** [comment]
@nordicjm I think you missed the point. What this is supposed to do is select the first location where it is defined. Currently, the build system explicitly disallows multiple locations. On the surface that generally makes sense. But we realized a use case that we wanted to deal with. 

So let me describe our use case again and a little differently:

RepoA --> Downstream_Zephyr_Fork_Repo

We have a downstream Zephyr fork. Its general rule is to stay closely aligned with the upstream with some selective cherry picks to deal with issues/features we deem useful for our downstream. Our general rule is to upstream first all enablement where possible.

But there are situations where we can't start upstreaming an enablement so we do that enablement in RepoA. This development may occur for a year of more and it may be made available to certain users as part of some early access agreement. 

But at some point, we expect that we can start upstreaming. When we do though, we know that the Zephyr project doesn't necessarily allow one single large PR but instead multiple smaller PRs. Some of this may take some amount of time to do the upstreaming and during that time, we may find ourselves in a situation where we need to do an upmerge of the upstream into our Zephyr downstream. When we do the upmerge, it may include the partial state of the upstream we were doing on the SOC/Board/what-ever. Since we have a full enablement in our RepoA, we don't want this partial upstream to disrupt the early access state we have.

This change allows us to have a partial state of upstreaming with synchronization in our downstream Zephyr without disrupting the functionality in our downstream found in RepoA. We already have this change working in our downstream.

Admittedly, we don't need Zephyr project to accept this change because we can have it as a [noup/toup] tagged change in our downstream Zephyr repo. But we were hoping to get some constructive feedback on this PR and potentially some options on how to handle our use case.

**Comment by nordicjm** [comment]
Then what you want is board extensions: https://github.com/zephyrproject-rtos/zephyr/issues/69548

**Comment by danieldegrasse** [comment]
> Then what you want is board extensions: https://github.com/zephyrproject-rtos/zephyr/issues/69548

Sure, but the issue I am concerned about with board/soc extensions is that it is only additive (as far as I understand) IE features/init code cannot be *removed*. A specific use case I can think of here would be an SOC that only has TF-M support in a downstream repository. In the downstream repository, we need to add code to skip the SOC init if targeting a TF-M nonsecure variant, because the secure firmware will have already setup the SOC.

With an SOC extension, I'm not sure how we'd accomplish this. We'd effectively need to remove a `SYS_INIT` macro present in the upstream within the SOC port downstream.

If we replace the SOC port with a new downstream version, this is easy to solve. The need to replace the board port then exists because we want to keep the downstream board port in sync with this downstream SOC port- not with what exists upstream.

**Pull request closed without merging**
