### PR TITLE
kernel: Remove CONFIG_LEGACY_TIMEOUT_API

### LINKED ISSUE #30893: Remove LEGACY_TIMEOUT_API
Remove legacy timeout API support, this has been there for a few releases already and shall be removed for LTS, so ideally remove before 2.5 is released.

### PR DESCRIPTION
**Pull request by andyross**
This was a fallback for an API change several versions ago.  It's time
for it to go.

Fixes: #30893

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
Looks good technically thanks.

Please add an entry to the API Changes section in doc/releases/release-notes-2.5.rst noting the legacy API deprecated in release 2.3 has now been removed.

**Review by jukkar — APPROVED** [review]
+1 to networking changes

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by nashif** [comment]
@andyross  can you please fix the CI issue and a comment in the release notes?

**Review by nashif — APPROVED** [review]

**Review by katsuster — APPROVED** [review]

**Comment by andyross** [comment]
Added release notes.  Note that the CI failure is a false positive, it's complaining about a reference to the kconfig that has now been deleted, but the reference is in an old release notes file we obviously can't change.

**Comment by nashif** [comment]
> Added release notes. Note that the CI failure is a false positive, it's complaining about a reference to the kconfig that has now been deleted, but the reference is in an old release notes file we obviously can't change.

we should change that and remove the :option: thing from the release notes, so

:option:`CONFIG_LEGACY_TIMEOUT_API` becomes `CONFIG_LEGACY_TIMEOUT_API`

**Review by pabigot — APPROVED** [review]

**Pull request merged**
