### PR TITLE
kernel/sched: Fix preemption logic

### LINKED ISSUE #8049: kernel: scheduler tries to make polling threads active
Since commit https://github.com/zephyrproject-rtos/zephyr/commit/1856e2206d1286ede9c8b25a5702f8c40d8bccd6#diff-23bba5938c8ac686f219f01f58478b9a "kernel/sched: Don't preempt cooperative threads" the update_cache() function in kernel/sched.c has been placing threads which are polling back into the ready queue if they are high enough priority.

This occurs when CONFIG_POLL is enabled (could be auto-selected when CONFIG_NETWORKING is enabled) and a high priority workq such as net_tc's TX / RX workq becomes the only available high priority thread to be requeued.

In Zephyr, this manifests as a random deadlock in the kernel where the work_q_main function will return from k_queue_get() with a NULL work and then immediately call k_queue_get() again only to return and be re-called over and over.

This was never a problem before the above commit, because update_cache would preempt *any* thread  even high priority ones.

A long discussion of this behavior is outlined in https://github.com/zephyrproject-rtos/zephyr/issues/8005

### PR DESCRIPTION
**Pull request by andyross**
The should_preempt() code was catching some of the "unrunnable" cases
but not all of them, opening the possibility of failing to preempt a
just-pended thread and thus waking it up synchronously.  There are
reports of this causing spin loops over k_poll() in the network stack
work queues (see #8049).

Note that the previous _is_dummy() call is folded into (the somewhat
verbosely named) _is_thread_prevented_from_running(), and that the
order of tests has been changed/optimized to hopefully catch common
cases earlier.

Fixes #8049

Suggested-by: Michael Scott <michael@opensourcefoundries.com>
Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by mike-scott — APPROVED** [review]
Initial testing of this LGTM.  Letting it run for a while on HW to see if it stalls out anywhere.

**Comment by mike-scott** [comment]
Can we add this to the PR description?
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/8049

**Review by tyrantlizard77 — APPROVED** [review]

**Review by lpereira — APPROVED** [review]
LGTM

**Comment by ulfalizer** [comment]
> This code actually is performance-critical, though this close to release I'd prefer to keep this clearer rather than optimized. Scheduler performance is an item for 1.13 for sure (we've regressed a bit, though this patch turns out to repair most of the damage). In this case though I'd expect the compiler to have figured out the proper boolean path here. Note that both _is_idle() and is_preempt() are comparisons on the thread priority, so it might be able to fold them together.

Yeah, I just did a dumb local check. GCC always simplifies the non-SMP `return thread == _idle_thread` case, but the SMP case is a bit trickier. I don't know the context here though. Just something random I spotted.

**Pull request merged**
