### PR TITLE
drivers: serial: uart_ns16550: Convert to new DT_INST macros

### PR DESCRIPTION
**Pull request by galak**
Convert older DT_INST_ macro use the new include/devicetree.h
DT_INST macro APIs.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@fabled if you can take a look/review.

**Review by dcpleung — APPROVED** [review]

**Review by fabled — APPROVED** [review]
Looks good to me.

**Review by jenmwms — APPROVED** [review]
Looks good, thanks!

**Comment by jenmwms** [comment]
FWIW - There are a few failed tests. What is the impact?

**Comment by galak** [comment]
> FWIW - There are a few failed tests. What is the impact?

The issue is on NIOS2 because interrupts are represented in the device tree.  I've posted a PR to fix that:  #23870, so once that is reviewed in merged, will rebase this PR and it will resolve the CI failures.

**Comment by galak** [comment]
ci failure is intermittent mps2_an385 failure which has nothing to do with 16550 uart.  Going to merge rather than re-run ci.

**Pull request merged**
