### PR TITLE
[Backport v1.14-branch] Backport sched test fixes

### LINKED ISSUE #16011: Increase coverage of tests
**Describe the bug**

When evaluating coverage data we notice some features in the core kernel is not be covered with any tests. 

**To Reproduce**

Run with coverage enable and look at reports of kernel and core OS services.

**Expected behavior**
Line and function coverage is or close to 100%.

**Impact**

We do not test everything, we might introduce bugs without being able to catch them.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Backport to v1.14 branch of fixes to schedule_api tests.

partial fix #16011

### CODE REVIEW

**Review by andyross — APPROVED** [review]
No reason not to, but do we really need to backport test fixes for coverage work?  If someone had an important app on 1.14 and expected to get only important behavioral fixes, would they be surprised to see this land in their tree?  How furious would they be if we messed up and broke something?

Basically this is a soap box from me about us being way too promiscuous with what we suck into the 1.14 branch and we really want to be letting that be except for real fixes.  But that has nothing to do with this patch.

**Comment by andrewboie** [comment]
> No reason not to, but do we really need to backport test fixes for coverage work? 

These are the marching orders I have, unfortunately.

**Comment by ioannisg** [comment]
Please, create an issue for 1.14.1

**Comment by andrewboie** [comment]
@ioannisg #16011

**Review by nashif — APPROVED** [review]

**Pull request merged**
