### PR TITLE
Add BMP390 sensor using BMP388 driver

### PR DESCRIPTION
**Pull request by DaAwesomeP**
This is a draft because I am still testing this out. I am also not sure if this is the preferred way to do this. Please let me know!

As far as I was able to detect from the datasheets, the only difference between the i2c and SPI interfaces on the BMP388/BMP390 is the reported chip ID. As such, the existing driver for the BMP388 can be used for the BMP390.

### CODE REVIEW

**Comment by bjarki-trackunit** [comment]
Looking at the three datasheets for the active chips 390 and 384, and the deprecated 388, they all have a very similar register layout. I would prefer you rename the driver `bmp388.c` to `bmp3xx.c` to make it clear the driver covers multiple variants of the chip. Similarly for the `bmp388-base.yaml`, rename it to `bmp3xx-base.yaml`.

I think you are approaching the issue correctly in creating a generic driver :)

I would like you to split the changes you are making into separate commits to make it easier to review once you are ready, I know its just a draft for now :)

**Comment by DaAwesomeP** [comment]
> I think you are approaching the issue correctly in creating a generic driver :)

Thank you for the initial feedback!

> I would prefer you rename the driver `bmp388.c` to `bmp3xx.c` to make it clear the driver covers multiple variants of the chip. Similarly for the `bmp388-base.yaml`, rename it to `bmp3xx-base.yaml`.

Sounds good! I leaned toward backward compatibility to be safe before.

> I would like you to split the changes you are making into separate commits to make it easier to review once you are ready, I know its just a draft for now :)

Yes, definitely now that someone else is taking a look!

> Looking at the three datasheets for the active chips 390 and 384, and the deprecated 388, they all have a very similar register layout.

I will note that I only have the BMP390 on hand, so I cannot test with the BMP384 as well. I'm confident that I won't break anything with the BMP388 with this sort of change.

**Comment by bjarki-trackunit** [comment]
Regarding the BMP384, I don't expect you to ensure or even add support for the BMP384, that will be up to whoever wants to expand the driver to support it in the future :)

**Comment by kartben** [comment]
Hi @DaAwesomeP -- just making sure that you didn't leave this PR on draft unintentionally. Please move it out of draft state whenever you're ready, and also make sure to have a look at the compliance errors that are reported (commit titles being too long)
Thanks!

**Comment by DaAwesomeP** [comment]
@kartben Thanks for the nudge! Still working on it, but much delayed as I have not been able to make time for this recently. I hope to resume this in the next few weeks.

There is currently some issue preventing Zephyr from bootstrapping when I load this module with my changes, but I am tracking down the proper debugging tools for the microcontrollers I have on-hand at the moment.

**Pull request closed without merging**
