### PR TITLE
west: hal_rpi_pico: Update Pico-SDK to v1.5.0

### PR DESCRIPTION
**Pull request by soburi**
Update Pico-SDK to v1.5.0 release.

Signed-off-by: TOKITA Hiroshi <tokita.hiroshi@fujitsu.com>

### CODE REVIEW

**Comment by yonsch** [comment]
Was this tested in any way?

**Comment by soburi** [comment]
> Was this tested in any way?

Twister testing with `tests/drivers` and `sample/drivers` tests is mostly OK.

One exception:
`samples/drivers/led_pwm` raise an error, but it is the same behavior in the current version. I think it is no problem about it.

**Comment by soburi** [comment]
Pico-SDK 1.5.0 already available, skip 1.4.0.

**Comment by carlescufi** [comment]
https://github.com/zephyrproject-rtos/hal_rpi_pico/pull/4 is merged @soburi

**Comment by soburi** [comment]
@carlescufi , @yonsch 
Thank you for your response.
I applied HAL update to this PR.

**Review by yonsch — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
