### PR TITLE
nrf52_bsim: Use same sys tick period as the real SOCs

### PR DESCRIPTION
**Pull request by aescolar**
The real nRF SOCs set the tick period to a number that is nicely divisible by the HW frequency.
Let's do the same, or the systick accuracy will be too bad.

Note: This fixes tests/kernel/sleep/ which started failing for this board sometime in the last year (maybe after the rtc driver update https://github.com/zephyrproject-rtos/zephyr/commit/fcda8699cb8c26daaf1002508397f4b6321c78e3 )

Gated by: 
- https://github.com/zephyrproject-rtos/zephyr/pull/55397

### CODE REVIEW

**Comment by aescolar** [comment]
@Thalley  tests/bluetooth/bsim/audio/test_scripts/vcp.sh fails with this config. I'm guessing another real bug uncovered?

**Review by anangl — APPROVED** [review]

**Comment by Thalley** [comment]
> @Thalley tests/bluetooth/bsim/audio/test_scripts/vcp.sh fails with this config. I'm guessing another real bug uncovered? DNM until the test is fixed

I'll take a look :)

**Comment by Thalley** [comment]
> > @Thalley tests/bluetooth/bsim/audio/test_scripts/vcp.sh fails with this config. I'm guessing another real bug uncovered? DNM until the test is fixed
> 
> I'll take a look :)

Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/55397

**Comment by aescolar** [comment]
This PR can be merged now, as the fix for the BT test that failed is now in tree

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Pull request merged**
