### PR TITLE
ITE: drivers/flash: remove flash write protection API

### PR DESCRIPTION
**Pull request by GTLin08**
This API has be removed in Zephyr 2.8, and does not need to be used
as a static function. Because flash_it8xxx2_write_protection(false)
is not supported. If the IT83XX_GCTRL_EPLR register in the
flash_it8xxx2_write_protection(false) is written as 1, the flash
write region will not be protected later, only be cleared by
power-on reset.

Signed-off-by: Tim Lin <tim2.lin@ite.corp-partner.google.com>

### CODE REVIEW

**Comment by GTLin08** [comment]
Hi @keith-zephyr and @brockus-zephyr ,
This PR needs your review, thanks.

**Comment by jackrosenthal** [comment]
> Zephyr 2.8

Zephyr 3.0? 2.8 does not exist.

**Review by jackrosenthal — APPROVED** [review]

**Review by brockus-zephyr — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]
Should the EPLR register get set by the [ChromeEC flash driver](https://chromium.googlesource.com/chromiumos/platform/ec/+/bb733b03/zephyr/drivers/cros_flash/cros_flash_it8xxx2.c#266)?

**Comment by GTLin08** [comment]
> Should the EPLR register get set by the [ChromeEC flash driver](https://chromium.googlesource.com/chromiumos/platform/ec/+/bb733b03/zephyr/drivers/cros_flash/cros_flash_it8xxx2.c#266)?

A CL(Gerrit) has been created for this.

**Pull request merged**
