### PR TITLE
toolchain: common.h: Rename STRINGIFY to Z_STRINGIFY

### LINKED ISSUE #12935: Zephyr usurps "STRINGIFY" define
If you'd need to define a macro which stringifies a symbol, how'd you call it? Surprise: everyone else calls it just the same. When different projects are used together, this leads to each redefine the other's, which leads to warnings, and with ever-popular -Werror, to build errors. And not even talking about cases where `#define STRINGIFY(x) itoa(x)`.

As anything else in Zephyr, STRINGIFY should be namespaced with prefix.

### PR DESCRIPTION
**Pull request by pfalcon**
"STRINGIFY" is the default name for this macro for every other
project out there. Using such with Zephyr will lead to macro
redifinition warning, which can easily become errors with -Werror.

For reference, a specific case where this happened is with open62541
project.

Fixes: #12935

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
Patch in the same vein as https://github.com/zephyrproject-rtos/zephyr/pull/13277

**Comment by ulfalizer** [comment]
Could get rid of the warning by doing `#undef STRINGIFY` before the `#define` too. Makes the code less cluttered.

Should probably explain why the `Z_` prefix is there in a comment if it's kept.

**Comment by nashif** [comment]
so everyone in the world get to call it STRINGiFY but us?

**Review by nashif — CHANGES_REQUESTED** [review]
I do not think this is a bug and this should not go into 1.14. By that definition I can create a project that reuses all zephyr macro names and force zephyr to keep renaming left and right. Also, Z_ has been used for internal APIs, and was never intended to prefix every macro or function, albeit this is being done inconsistently now and is probably the bug.

**Comment by SebastianBoe** [comment]
Using undef or ifndef seems more sane.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
> I do not think this is a bug and this should not go into 1.14. By that definition I can create a project that reuses all zephyr macro names and force zephyr to keep renaming left and right.

I don't think Zephyr should be polluting the preprocessor (or C) namespace with whatever random names we have in toolchain.h, ideally everything in there has a z_ or k_ prefix

this is probably a better thing to tackle for 1.15 though, and rename everything not just STRINGIFY

**Comment by pfalcon** [comment]
@ulfalizer:

> Could get rid of the warning by doing `#undef STRINGIFY` before the `#define` too. Makes the code less cluttered.

@SebastianBoe:

> Using undef or ifndef seems more sane.

I'm not sure what you guys are talking about. There's millions projects out there. There's this new wannabe "Zephyr" OS, which claims support for various well-known standards like BSD Sockets or POSIX. Nowhere do they say that the header X.h described by the standard defines a macro named STRINGIFY. Thus, millions of projects rightfully just define it in use. Nobody will patch a million of projects with #indef and #ifndef. Either Zephyr frees the space, of it'll become infamous for its "compatibility" with the standards.

Perhaps that indeed was better explained by @andrewboie:

> I don't think Zephyr should be polluting the preprocessor (or C) namespace with whatever random names we have in toolchain.h, ideally everything in there has a z_ or k_ prefix

**Comment by pfalcon** [comment]
@nashif:

> so everyone in the world get to call it STRINGiFY but us?

Exactly, that captures the idea well, in a humble and polite wording. However can be made more explicit: everyone in the world can think they're smarter than everyone else and use a bareword like STRINGIFY. But Zephyr should be *actually* smarter, and prefix all its stuff, to play along with everyone else in the world, no matter how mad they are.

> I do not think this is a bug and this should not go into 1.14. 

This was submitted on the hot steps of https://github.com/zephyrproject-rtos/zephyr/pull/13277. If **that** gigantic, and at the same time, half-baked patch (again, it should have been Z_MIN/Z_MAX) was merged, that it should be a piece of cake to merge this one.

> By that definition I can create a project that reuses all zephyr macro names and force zephyr to keep renaming left and right.

Right, as was pointed out, "z_" is too short a prefix, likely used by many projects already. For example, guess what, Z_DATA_ERROR is an zlib symbol, and who knows which more. I personally don't think we'll be done with the matter until we consistently use distinguishable prefix like `zph_` for everything.

> Also, Z_ has been used for internal APIs

STRINGIFY is exactly an internal API.

**Comment by SebastianBoe** [comment]
> Nobody will patch a million of projects with #indef and #ifndef. Either Zephyr frees the space, of it'll become infamous for its "compatibility" with the standards.
-  @pfalcon 

I tried to say that Zephyr should use undef of ifndef, not the external projects.

**Comment by pfalcon** [comment]
> I tried to say that Zephyr should use undef of ifndef, not the external projects.

I see, I guessed it, but the situation is that an existing project has an include for ANSI C/POSIX header, then includes its local headers, which defines STRINGIFY. Perhaps, I need to reword commit message to make that clearer. As mentioned, this did happen with https://github.com/open62541/open62541 , which also had -Werror in its CFLAGS.

(For full disclosure, this STRINGIFY issue is not the only one leading to warning (as error) building open62541. That's the whole matter - we'll need to make a hundred of changes like this to achieve good POSIX, etc. portability to Zephyr. And we'd better be ready for that, whereas now it's quite erratic - #13277 was voted up unanimously and merged quickly, whereas here suddenly bikeshedding starts, while both are of the same nature, and this one is only simpler re: amount of changes.)

**Review by SebastianBoe — APPROVED** [review]
Ah, right, adding a guard to Zephyr's definition doesn't work if an external project defines it afterwards without a guard.

I guess Z_STRINGIFY makes sense then.

If Z_STRINGIFY is not approved we could undef STRINGIFY before including the external project's definition of STRINGIFY.

**Review by mped-oticon — APPROVED** [review]

**Comment by nashif** [comment]
stale for a long time already..

**Pull request closed without merging**
