### PR TITLE
new hardware support : nucleof412 can internal controller

### PR DESCRIPTION
**Pull request by pbonazzi**
Reponed after #46476 and #49409 closed without commits

### CODE REVIEW

**Comment by pbonazzi** [comment]
@FRASTM If you want the second CAN, can you tell me where to find it in the documentation for nucleo f412zg?
https://www.st.com/resource/en/user_manual/dm00244518-stm32-nucleo144-boards-mb1137-stmicroelectronics.pdf

**Comment by henrikbrixandersen** [comment]
@pbonazzi Please fix the failing CI checks.

**Review by str4t0m — CHANGES_REQUESTED** [review]
Could you please change the commit order:
- First, add the can1 node to the SOC (also change the commit message it does not have anything to do with the nucleo but only the stm32f412 soc.
- Then you can enable the can1 in the board.

Also , please rebase on the latest main branch. You are working off a 3 months old state.

> If you want the second CAN, can you tell me where to find it in the documentation for nucleo f412zg?

You could add the can2 node like:
Reference manual (10.2 Table 40;  6.3.13; 2.2.2 Table 1)   

```
	can2: can@40006800 {
			compatible = "st,stm32-can";
			reg = <0x40006800 0x400>;
			interrupts = <63 0>, <64 0>, <65 0>, <66 0>;
			interrupt-names = "TX", "RX0", "RX1", "SCE";
			clocks = <&rcc STM32_CLOCK_BUS_APB1 0x06000000>;
			master-can-reg = <0x40006400>;
			status = "disabled";
			sjw = <1>;
			sample-point = <875>;
		};
```

**Comment by henrikbrixandersen** [comment]
@pbonazzi You still need to pay attention to the failing CI if you want to get this merged. Also, please take a look at the existing commits in the tree for inspiration on how to format your commit logs.

**Comment by henrikbrixandersen** [comment]
From the compliance CI output:

```
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style for more details.

Please remove blank lines at end of 'boards/arm/nucleo_f412zg/nucleo_f412zg.dts'
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

0ff7e5e893b44db273f25ee1010f9dedc5b2d7d8: author email (Pietro Bonazzi <pietrobonazzi.jobs@gmail.com>) needs to match one of the signed-off-by entries.
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

1: UC2 Body does not contain a 'Signed-off-by:' line
Error: Process completed with exit code 1.
```

**Pull request closed without merging**
