### PR TITLE
drivers: uart: native_posix: convert to DT_INST defines

### PR DESCRIPTION
**Pull request by galak**
Convert driver to fully use DT_INST_ defines.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by vanwinkeljan — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Comment by aescolar** [comment]
@galak we are in freeze.. ;)

**Comment by vanwinkeljan** [comment]
@aescolar Looks like it is merged into a topic branch or did I miss something ;)

**Comment by aescolar** [comment]
true story, sorry for the noise :)

**Comment by galak** [comment]
:), since the DT_INST changes touch a lot of drivers decided a topic branch that we hopefully will merge right after the release is made.

**Pull request merged**
