### PR TITLE
boards/arm: Add MCUbootr's button and led aliases to Nordic's boards

### PR DESCRIPTION
**Pull request by nvlsianpu**
Added alias for the button's gpio pin which might be used by MCUboot.
So far pin assignments for MCUboot was configured by the Kconfig. New
alias will help to switch configuration to more native DTS based
description.

MCUboot will start to use the alias thanks to: https://github.com/mcu-tools/mcuboot/pull/1344

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]

**Review by anangl — COMMENTED** [review]
What about other Nordic boards, for example `nrf21540dk_nrf52840`? It seems that the alias should be defined for all boards that define `bootloader-led0`.

**Comment by nvlsianpu** [comment]
@anangl for many of them the bootloader pin assignment is unknow to me. I can assign a button0 for the all, but this might be wrong for some.

**Review by jfischer-no — DISMISSED** [review]

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
I think this needs more discussion on how we are going to represent this; see the upstream MCUboot PR for details: https://github.com/mcu-tools/mcuboot/pull/1344#discussion_r847383035

I know there is an existing `bootloader-led0`, but I don't remember reviewing that and I'm not convinced it's a good idea to put this in the `/aliases` node like this without 'mcuboot' in the name. Remember that mcuboot is not the only bootloader which uses DTS.

**Comment by nvlsianpu** [comment]
> I know there is an existing bootloader-led0, but I don't remember reviewing that and I'm not convinced it's a good idea to put this in the /aliases node like this without 'mcuboot' in the name. Remember that mcuboot is not the only bootloader which uses DTS.

@mbolivar-nordic I'm fine with your opinion. `mcuboot-button0` might be the better alias name.

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic I'm fine with your opinion. `mcuboot-button0` might be the better alias name.

OK, thanks @nvlsianpu. In the interest of making progress, let's go with that if we can, then.

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Did you leave `bootloader-led0` the way it is on purpose?

I think it would be cleaner to move all the in-tree users to `mcuboot-led0`, for consistency. This could go alongside a change in mcuboot's `boot/zephyr/main.c` file so that `LED0_NODE` is checked for both cases, like this:

```c
#if DT_NODE_EXISTS(DT_ALIAS(mcuboot_led0))
#define LED0_NODE DT_ALIAS(mcuboot_led0))
#elif DT_NODE_EXISTS(DT_ALIAS(bootloader_led0))
#warning "bootloader-led0 alias is deprecated; use mcuboot-led0 instead"
#define LED0_NODE DT_ALIAS(bootloader_led0)
#endif
```

**Comment by lairdjm** [comment]
This update should also be applied to: bt510, bt610, bl5340_dvk, bl652_dvk, bl653_dvk, bl654_dvk, bl654_sensor_board, pinnacle_100_dvk

**Review by nordicjm — DISMISSED** [review]

**Review by mbolivar-nordic — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

**Review by MaureenHelm — COMMENTED** [review]
The last commit message looks like a copy paste mistake?

`boards/arm: Add mcuboot's button alias to nRF boards` adds led aliases, not button aliases

**Review by d3zd3z — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Pull request merged**
