### PR TITLE
manifest: update hal_nordic revision to have nrfx 3.7.0 release

### PR DESCRIPTION
**Pull request by nika-nordic**
New nrfx 3.7.0 release contains nRF54H20 EngC support and multi-instanced PDM driver needed for nRF54L15 support.

### CODE REVIEW

**Comment by nika-nordic** [comment]
cc @mstasiaknordic @adamkondraciuk

**Review by aescolar — COMMENTED** [review]
Don't you need to update NRFX_CONFIG_API_VER_MINOR to 7? (Both in Zephyr side and in the templates)

**Comment by mstasiaknordic** [comment]
> Don't you need to update NRFX_CONFIG_API_VER_MINOR to 7? (Both in Zephyr side and in the templates)

The release includes changes to PDM API, which are used with nrfx version 3.7. The version will be updated once Zephyr PDM driver is adjusted, not to cause build errors.

See https://github.com/zephyrproject-rtos/zephyr/pull/79177/files#diff-4b852647b675001f0093ac047dbf6b85483c8eb6919d45d3f202e2dbde6b58a4

**Review by aescolar — COMMENTED** [review]
Another needed change:
```diff --git a/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h b/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h
index 770cb70d8cc..5ecb3e0f735 100644
--- a/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h
+++ b/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h
@@ -149,7 +149,7 @@ static inline void hal_trigger_crypt_ppi_config(void)
 {
        nrf_radio_publish_set(NRF_RADIO,
                              NRF_RADIO_EVENT_ADDRESS, HAL_RADIO_RECV_TIMEOUT_CANCEL_PPI);
-       nrf_ccm_subscribe_set(NRF_CCM, NRF_CCM_TASK_CRYPT, HAL_RADIO_RECV_TIMEOUT_CANCEL_PPI);
+       nrf_ccm_subscribe_set(NRF_CCM, NRF_CCM_TASK_START, HAL_RADIO_RECV_TIMEOUT_CANCEL_PPI);
 }
 
 /*******************************************************************************
@@ -157,7 +157,7 @@ static inline void hal_trigger_crypt_ppi_config(void)
  */
 static inline void hal_trigger_crypt_ppi_disable(void)
 {
-       nrf_ccm_subscribe_clear(NRF_CCM, NRF_CCM_TASK_CRYPT);
+       nrf_ccm_subscribe_clear(NRF_CCM, NRF_CCM_TASK_START);
 }
 
 /*******************************************************************************
```

**Review by aescolar — COMMENTED** [review]
And
```diff
diff --git a/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf54lx.h b/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf54lx.h
index b0d3948aefb..5230c9c354e 100644
--- a/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf54lx.h
+++ b/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf54lx.h
@@ -633,8 +633,8 @@ static inline uint32_t hal_radio_tx_power_value(int8_t tx_power_lvl)
                return RADIO_TXPOWER_TXPOWER_Neg20dBm;
        }
 
-       if (tx_power_lvl >= -26) {
-               return RADIO_TXPOWER_TXPOWER_Neg26dBm;
+       if (tx_power_lvl >= -28) {
+               return RADIO_TXPOWER_TXPOWER_Neg28dBm;
        }
 
        if (tx_power_lvl >= -40) {
```

**Review by gmarull — CHANGES_REQUESTED** [review]
let's centralize HAL update in: https://github.com/zephyrproject-rtos/zephyr/pull/78631

Since 54H20 has become EngB, the EngB relabel needs to happen with the HAL update, otherwise EngB will build as EngC.

There are now multiple PRs targeting the same HAL PR, and it is not clear which ones are mandatory or not.

**Comment by aescolar** [comment]
@nika-nordic You can cherry-pick this commit https://github.com/zephyrproject-rtos/zephyr/pull/79214

**Comment by nika-nordic** [comment]
closed in favor of: https://github.com/zephyrproject-rtos/zephyr/pull/78631

**Pull request closed without merging**
