### PR TITLE
Bluetooth: Revert "Disable host-based RPA resolution when !BT_PRIVACY"

### PR DESCRIPTION
**Pull request by alwa-nordic**
It is reasonable that `BT_SMP`, which enables bonding, allows properly bonding and reconnecting to devices that are in privacy mode. RPA resolution is pretty much required for interoperability. Most devices, both central and peripheral, are in privacy mode most of the time. So, any application supporting bonding must be able to resolve RPAs. This is true even if the application developer does not want the local device to be in privacy mode.

After discussion, the Zephyr Bluetooth maintainers now agree that `BT_PRIVACY` will affect only local identity privacy. This is a reversal of a prior decision. The commits of the prior decision are reverted in this PR.

Commit 59eef60665dc816510bd7a9cc43b6167a20d42a1 is reverted and replaced with 6c3fa2f98f0645575c81c64b8920e17bb89bd704. The controller resolve list is used by the host for receiving directed advertising with private addresses. Zephyr Bluetooth Host populates the resolve list with information from bonds. Bonding is supported if `BT_SMP`. So `BT_SMP` is used as a stand-in for "Host needs controller resolve list". `BT_CTLR_PRIVACY` enables the controller resolve list.

Commit 5824ac90ecd8dd06d9ea117d345dbc6b069e5840 is the main issue. It contains some unrelated changes. Those changes will be re-submitted in a separate PR.

### CODE REVIEW

**Comment by alwa-nordic** [comment]
@cvinayak The replacement commit you gave me fails CI. It's because of `CONFIG_BT_CTLR_PRIVACY=n` in `tests/bluetooth/bsim_bt/bsim_test_app/prj_split.conf`. Can I remove that commit and let this PR be a pure revert? You can post a PR with the improved config defaults.

**Comment by cvinayak** [comment]
> @cvinayak The replacement commit you gave me fails CI. It's because of `CONFIG_BT_CTLR_PRIVACY=n` in `tests/bluetooth/bsim_bt/bsim_test_app/prj_split.conf`. Can I remove that commit and let this PR be a pure revert? You can post a PR with the improved config defaults.

I do not think just keeping the revert commit would pass the test due to your changes. You can give a try, but I am assuming you will need to change the prj.conf files of the tests.

**Comment by alwa-nordic** [comment]
@cvinayak I spoke too soon. I don't know exactly what is happening, since your two commits without my revert commit works.

**Review by joerchan — APPROVED** [review]
Changes look good.

We should update the documentation for BT_PRIVACY.
```
config BT_PRIVACY
	bool "Enable Privacy"
	help
	  Enable Privacy for the local device. This makes the local device
	  use Resolvable Private Addresses (RPAs).
          Note: Without privacy support in the controller establishing connections
          as a directed advertiser, or to a directed advertiser is not possible.

**Review by jhedberg — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Comment by carlescufi** [comment]
> Changes look good.
> 
> We should update the documentation for BT_PRIVACY.
> 
> ```
> config BT_PRIVACY
> 	bool "Enable Privacy"
> 	help
> 	  Enable Privacy for the local device. This makes the local device
> 	  use Resolvable Private Addresses (RPAs).
>           Note: Without privacy support in the controller establishing connections
>           as a directed advertiser, or to a directed advertiser is not possible.
> ```

@alwa-nordic please send a follow-up PR with this change

**Review by carlescufi — APPROVED** [review]
Looks good, thank you @alwa-nordic!

**Comment by alwa-nordic** [comment]
> > Changes look good.
> > We should update the documentation for BT_PRIVACY.
> > ```
> > config BT_PRIVACY
> > 	bool "Enable Privacy"
> > 	help
> > 	  Enable Privacy for the local device. This makes the local device
> > 	  use Resolvable Private Addresses (RPAs).
> >           Note: Without privacy support in the controller establishing connections
> >           as a directed advertiser, or to a directed advertiser is not possible.
> > ```
> 
> @alwa-nordic please send a follow-up PR with this change

The proposed text looks a bit out of place in the help text of config BT_PRIVACY. Any suggestions for a better placement? Maybe it should go into config BT_CTRL_PRIVACY? @carlescufi

**Comment by joerchan** [comment]
The note can be moved to BT_CTLR_PRIVACY. But in addition, the zephyr host may be used with controllers that don' use the zephyr controller. So IMO it could be in both places.

Do we have some higher layer documentation that describes privacy?

**Pull request merged**
