### PR TITLE
soc: silabs: add Kconfig options to independently enable compilation of vendor HAL library modules

### PR DESCRIPTION
**Pull request by mnkp**
Zephyr gecko drivers depend on libraries provided by the vendor. The same libraries may also be used directly by the application code or RAIL library. To facilitate the latter use case scenario this commit adds Kconfig options to independently enable compilation of vendor HAL library modules.

### CODE REVIEW

**Comment by mnkp** [comment]
@ekarlso, @diegosueiro, @mtuxpe Another PR that modifies code common to all SiLabs SoCs. The main purpose of this PR is to support compilation of an external RAIL library as well as porting of native SiLabs code which doesn't use Zephyr drivers. Your comments are welcome.

**Comment by diegosueiro** [comment]
@mnkp,

LGTM.

**Comment by mtuxpe** [comment]
Cool ! Are you planning to add  support any radio on Silabs ?

Em sex, 14 de dez de 2018 às 07:35, Piotr Mienkowski <
notifications@github.com> escreveu:

**Comment by mnkp** [comment]
> Cool ! Are you planning to add support any radio on Silabs ?

I have a local copy of RAIL library in the application directory plus some cmake plumbing on top. It works very well. The only difficulty with adding RAIL to Zephyr would be figuring out the license issue. Unfortunately, I haven't done much in this regard so far.

**Review by chrta — APPROVED** [review]
:+1:

**Comment by ekarlso** [comment]
LGTM, tested on efr32mg12 project I have.

**Comment by galak** [comment]
Looks good, can you update to fix the merge conflict.

**Comment by mnkp** [comment]
PR updated.

**Review by galak — APPROVED** [review]

**Pull request merged**
