### PR TITLE
board: stm32f3_seco_d23:  update name and refs

### LINKED ISSUE #67169: boards: doc: Deadlink in SECO JUNO SBC-D23 documentation page ('boards/arm/stm32f3_seco_d23/doc/index')
**Describe the bug**

SECO JUNO SBC-D23 [documentation page](https://docs.zephyrproject.org/latest/boards/arm/stm32f3_seco_d23/doc/index.html) contains a deadlink to https://edge.seco.com/juno.html

Could it be that this board now goes by a new name, @ektor5? Looking at the board image, it feels like it's now https://edge.seco.com/fr/sbc-3-5-px30.html? 

**Environment**

* Page: `boards/arm/stm32f3_seco_d23/doc/index`
* Version: main
* SHA-1: 14c92da96d5613b48610fa9bfe284528a814a4e6

### PR DESCRIPTION
**Pull request by ektor5**
Due to board name change (JUNO -> SBC-3.5-PX30), it is necessary to update board names, links and references in files and documentation.

Closes https://github.com/zephyrproject-rtos/zephyr/issues/67169

### CODE REVIEW

**Comment by kartben** [comment]
Sorry, didn't see this one as this didn't get through the PR Assignee bot. Looks like there's now a merge conflict, that's bad luck!

**Review by kartben — DISMISSED** [review]
fwiw this look good apart from the unfortunate conflict

**Review by FRASTM — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@ektor5 can you rebase please?

**Comment by fabiobaltieri** [comment]
You need to actually `git rebase` and then force push again. :-)

**Comment by ektor5** [comment]
@fabiobaltieri I know, I know... just testing how intelligent was the GitHub webUI, nice but still not ideal. :sweat_smile:

**Review by erwango — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
