### PR TITLE
drivers: led: Add LED driver support for NXP PCA9633

### PR DESCRIPTION
**Pull request by sbourdelin**
Add support for NXP PCA9633 an I2C 4-bit LED driver.
Supported blinkink period: 41ms to 10667ms
Supported brightness value: 0 to 100%

This driver supports the following APIs:

1. led_blink
2. led_set_brightness
3. led_on
4. led_off

Signed-off-by: Sebastien Bourdelin <sebastien.bourdelin@savoirfairelinux.com>

### CODE REVIEW

**Review by MaureenHelm — COMMENTED** [review]
Really nice work, thanks for contributing. The only change I'd like to see is the addition of a sample or test in a second commit so we can make sure the driver gets built in CI.

**Comment by sbourdelin** [comment]
@MaureenHelm Thanks for the fast review, i'll send an other PR adding a sample this week!

**Comment by MaureenHelm** [comment]
> i'll send an other PR adding a sample this week!

You can just push another commit to your branch to update this PR. I'd like to hold off merging the driver until we have the sample too.

**Comment by sbourdelin** [comment]
> You can just push another commit to your branch to update this PR. I'd like to hold off merging the driver until we have the sample too.

Hi @MaureenHelm i just add a sample, let me know if it looks good for you.
Thanks

**Comment by MaureenHelm** [comment]
Thanks @sbourdelin . The sample code looks fine, but please add a README.rst

**Comment by sbourdelin** [comment]
> Thanks @sbourdelin . The sample code looks fine, but please add a README.rst
Done.

**Review by MaureenHelm — APPROVED** [review]

**Comment by sbourdelin** [comment]
Thanks for the fast review and merge @MaureenHelm

**Pull request merged**
