### PR TITLE
boards: snps: emsdp: remove CONFIG_PINCTRL from the defconfig

### PR DESCRIPTION
**Pull request by tagunil**
Add proper PINCTRL dependencies to the drivers involved and remove CONFIG_PINCTRL from the board defconfig.

This is a part of #78619.

### CODE REVIEW

**Comment by ruuddw** [comment]
Besides UART and SPI, shouldn't I2C and GPIO have CONFIG_PINCTRL enabled somewhere else now as well?

**Comment by tagunil** [comment]
> Besides UART and SPI, shouldn't I2C and GPIO have CONFIG_PINCTRL enabled somewhere else now as well?

That's a good question. The GPIO driver doesn't support PINCTRL at the moment, so that's a separate matter to investigate. The I2C driver does, but we don't have the I2C peripheral enabled for the EMSDP boards in Zephyr. I believe there is a lot of work ahead to clean up and verify our board configurations, but the scope of this PR is limited by #78619.

**Comment by ruuddw** [comment]
OK, then let's leave the other peripherals for a follow-up PR.

**Review by ruuddw — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by nordicjm** [comment]
> > Besides UART and SPI, shouldn't I2C and GPIO have CONFIG_PINCTRL enabled somewhere else now as well?
> 
> That's a good question. The GPIO driver doesn't support PINCTRL at the moment, so that's a separate matter to investigate. The I2C driver does, but we don't have the I2C peripheral enabled for the EMSDP boards in Zephyr. I believe there is a lot of work ahead to clean up and verify our board configurations, but the scope of this PR is limited by #78619.

I mean, if they are needed can you add them to this PR? The idea is to have PINCTRL automatically working and drivers that need it to select it, if someone can instantly break a board by enabling i2c, that's not a good user experience

**Comment by ruuddw** [comment]
I forgot that the I2C support was never merged, looks like the PR for that (#58409) got stale and closed after Siyuan left.

Let's indeed keep that for another PR, I think this is ok to merge now.

**Comment by nordicjm** [comment]
If it's not supported then fine to omit, was under the assumption it was supported already

**Review by gmarull — APPROVED** [review]

**Review by evgeniy-paltsev — APPROVED** [review]

**Comment by nordicjm** [comment]
@dcpleung please review

**Pull request merged**
