### PR TITLE
tests: kernel: semaphore: Added tests for semaphore.

### PR DESCRIPTION
**Pull request by AdithyaBaglody**
The following test cases have been added for semaphore.

1. Test simple semaphore give/take from an isr.
2. Test simple semaphore give/take from a task.
3. Test semaphore take with no wait.
4. Test semaphore take with no wait and fails.
5. Test semaphore take with timeout and fails.
6. Test semaphore take with timeout.
7. Test semaphore take with timeout as forever
8. Test semaphore take with timeout from an isr.
9. Test semaphore take on multiple threads.
10. Test semaphore give/take from an isr.
11. Test semaphore multiple threads wait on a semaphore.
12. Test semaphore measure timeouts.
13. Test semaphore measure timeout when give is from another thread.
14. Test semaphore multiple sem take and timeouts.
15. Test semaphore multiple sem take with diff timeout & semaphore.

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
why does main.c and the header file exist?

just put it all in one C file.

**Comment by AdithyaBaglody** [comment]
makes sense I will combine the header into the c file. 
But for main.c file I am bit concerned since some test cases have a dedicated main.c, others don't. So not sure what to follow here.

**Comment by nashif** [comment]
> But for main.c file I am bit concerned since some test cases have a dedicated main.c, others don't. So not sure what to follow here.

use main.c with all test code in the file, if the test does test multiple things in parallel that are not logically related, you can have multiple .c files for each tested component.

**Comment by AdithyaBaglody** [comment]
delta:
1.  Merged into a single file(i.e main.c)
2. Handled other review fixes.

**Review by nashif — APPROVED** [review]

**Pull request merged**
