### PR TITLE
net: l2: Add custom IEEE802154 L2

### PR DESCRIPTION
**Pull request by rlubos**
Define a custom IEEE802154 based L2. The user can then use those symbols
to implement their own 802.15.4 based L2, based on those symbols, w/o a
need to modify the Zephyr tree.

### CODE REVIEW

**Review by mniestroj — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Looks good, this approach was discussed offline and is sound.

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by pdgendt** [comment]
Would be nice to have a sample/test for the custom scenario.

**Review by jfischer-no — APPROVED** [review]

**Comment by rlubos** [comment]
> Would be nice to have a sample/test for the custom scenario.

I  can't think of any useful sample for the feature in Zephyr, since this would require some custom L2 implementation, which we don't have in Zephyr (since this configuration is intended for out-of-tree use cases). But I can add some test with some dummy implementation to verify that custom 15.4 L2 can be registered in the system properly.

**Pull request merged**
