### PR TITLE
boards: arm: 96b_argonkey.yaml: Add i2c/spi/gpio to the supported list

### PR DESCRIPTION
**Pull request by avisconti**
Add i2c/spi/gpio to the supported list to enable the CI to correctly
run the 96b_argonkey board sample.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Comment by avisconti** [comment]
@MaureenHelm 
OK, thanks for the hints.
I think this is what you were suggesting, correct?

**Comment by avisconti** [comment]
> Yup. But could you please rearrange the list in alpha order?

sounds reasonable

**Review by MaureenHelm — APPROVED** [review]

**Comment by MaureenHelm** [comment]
recheck

**Comment by avisconti** [comment]
rebased and repushed.
I think now the check is going to pass (maybe)

**Comment by avisconti** [comment]
recheck

**Comment by MaureenHelm** [comment]
Please see #10351. Once that gets merged, you should be able to pass CI.

**Comment by avisconti** [comment]
> Please see #10351. Once that gets merged, you should be able to pass CI.

OK, good.

**Pull request merged**
