### PR TITLE
samples: mgmt: smp_srv: add runtime tests with 'native_sim'

### PR DESCRIPTION
**Pull request by mniestroj**
Add pytest scripts for testing SMP server running on `native_sim`. Use UDP
transport for that and loopback (`127.0.0.1`) interface of Native Simulator
offloaded sockets.

Set `HAS_FLASH_LOAD_OFFSET` to `y` as a workaround to build SMP image group
implementation.

Depends on: #77512

### CODE REVIEW

**Comment by nordicjm** [comment]
Hmm I would rather that tests were done so that everything is tested inside of the test itself, generating commands, sending them, waiting for responses, checking results - without use of an external tool whose quality is unknown. See https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/subsys/mgmt/mcumgr for examples

**Comment by pdgendt** [comment]
> Hmm I would rather that tests were done so that everything is tested inside of the test itself, generating commands, sending them, waiting for responses, checking results - without use of an external tool whose quality is unknown. See https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/subsys/mgmt/mcumgr for examples

How would that work for a sample? I think it makes a lot of sense to have the sample functionality tested as well.

**Comment by nordicjm** [comment]
> > Hmm I would rather that tests were done so that everything is tested inside of the test itself, generating commands, sending them, waiting for responses, checking results - without use of an external tool whose quality is unknown. See https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/subsys/mgmt/mcumgr for examples
> 
> How would that work for a sample? I think it makes a lot of sense to have the sample functionality tested as well.

There is nothing in the sample, the sample is just enabling the Kconfigs

**Comment by pdgendt** [comment]
> There is nothing in the sample, the sample is just enabling the Kconfigs

IMO there is a lot in this sample, a user builds it, and can try it out manually. So why shouldn't that be verified in an automated way?

**Comment by nordicjm** [comment]
> > There is nothing in the sample, the sample is just enabling the Kconfigs
> 
> IMO there is a lot in this sample, a user builds it, and can try it out manually. So why shouldn't that be verified in an automated way?

MCUmgr is tested in CI and on real hardware using the tests, this sample just adds various configurations, a way of mounting a filesystem and advertising over bluetooth - none of which is even tested by this PR, all this PR does is test an external utility, it's not even testing the MCUmgr code in tree

**Comment by nordicjm** [comment]
Also note we already do test this sample in https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/boot/test_mcuboot and https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/boot/with_mcumgr

**Pull request closed without merging**
