### PR TITLE
Enable IPM on i.MX7 SoC and boards

### PR DESCRIPTION
**Pull request by diegosueiro**
The changes were tested by building and executing this demo:
[https://github.com/diegosueiro/rpmsg-lite/tree/zephyr-support/zephyr/samples/subsys/ipc/rpmsg_lite/remote_echo](https://github.com/diegosueiro/rpmsg-lite/tree/zephyr-support/zephyr/samples/subsys/ipc/rpmsg_lite/remote_echo)

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
Can you enable the sample on these boards?

**Comment by diegosueiro** [comment]
@galak ,

You mean by removing `platform_whitelist: udoo_neo_full_m4` on samples/subsys/ipc/ipm_imx/sample.yaml file?

**Comment by diegosueiro** [comment]
> > You mean by removing `platform_whitelist: udoo_neo_full_m4` on samples/subsys/ipc/ipm_imx/sample.yaml file?
> 
> Yep.

This broke the tests. I'm not sure how to solve this.

**Comment by galak** [comment]
> This broke the tests. I'm not sure how to solve this.
> It seems that the `filter: CONFIG_SOC_FAMILY_IMX` is not working as expected.

Yeah, guess you should just add the other boards to the platform_whitelist.

**Review by galak — APPROVED** [review]

**Pull request merged**
