### PR TITLE
Bluetooth: host: conn param update fixes

### PR DESCRIPTION
**Pull request by knutel-nordic**
Fixes bug where it was not possible to change the connection interval min/max if the current interval was within min/max already.
Fixes return code so that parameters identical to the current parameters are accepted without error.

### CODE REVIEW

**Review by hermabe — APPROVED** [review]

**Review by jori-nordic — CHANGES_REQUESTED** [review]
could you add a test?

**Comment by knutel-nordic** [comment]
> could you add a test?

Yes, I will do that.

**Comment by jhedberg** [comment]
And an update to the migration guide about the change in behavior, thanks.

**Comment by jori-nordic** [comment]
Discussed in Bluetooth WG meeting:
- `0` as a return value implies the operation was successful, and an `updated` event will come. This is not the case anymore after this patch
- the check should be removed altogether, and just return the err code from the controller

**Comment by jori-nordic** [comment]
Superseeded by https://github.com/zephyrproject-rtos/zephyr/pull/75323

**Pull request closed without merging**
