### PR TITLE
tests: syscalls: add torture test

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Hammer all CPUs with multiple threads all making system calls
that do memory allocations and buffer validation, in the hopes
that it will help smoke out concurrency issues.

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
Note: this crashes on mps2_an385 and mps2_an521 due to #22275 

I have also found that nsim_em and nsim_sem also fatally crash out, opening a bug on this.

**Review by ceolin — APPROVED** [review]

**Review by wentongwu — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Comment by ioannisg** [comment]
Thanks @andrewboie, I wonder if we can keep this DNM until we apply the relevant fixes

**Comment by andrewboie** [comment]
> Thanks @andrewboie, I wonder if we can keep this DNM until we apply the relevant fixes

I don't see the point of adding DNM, this won't be merged until CI is passing

**Comment by ioannisg** [comment]
Included in #22691

**Pull request closed without merging**
