### PR TITLE
tests: drivers: counter: counter_nrf_rtc: Add nRF54L15 to platform allow

### PR DESCRIPTION
**Pull request by nordic-segl**
Add nRF54L15 to platform_allow in the sample.yaml.

### CODE REVIEW

**Comment by nordic-segl** [comment]
@adamkondraciuk: Could You take a look?

**Comment by nordic-segl** [comment]
This test is passing on nrf54l15 in our CI.

**Review by nordic-piks — APPROVED** [review]

**Comment by nordic-krch** [comment]
@nordic-segl this test was passing because there were no instances enabled (and test was ok with that). I've opened #71415 with your commit and additional changes needed to run on instances (also added fail if there are no RTC instances).

**Comment by nordic-segl** [comment]
Included in https://github.com/zephyrproject-rtos/zephyr/pull/71415 which has additional fixes and improvements.

**Pull request closed without merging**
