### PR TITLE
libc: share time() between minimal libc and armclang libc

### PR DESCRIPTION
**Pull request by galak**
Introduce a place to share implementations of libc functions that are needed by different libc versions.  Place time() in this common location so it can be shared when building for either minimal libc or armclang libc.

### CODE REVIEW

**Review by keith-packard — APPROVED** [review]
This looks very nice. Are you thinking of doing this with malloc et al too? Would love to get rid of the separate libc heap for newlib and picolibc ...

**Review by cfriedt — APPROVED** [review]
LGTM

**Review by nashif — APPROVED** [review]

**Comment by galak** [comment]
> This looks very nice. Are you thinking of doing this with malloc et al too? Would love to get rid of the separate libc heap for newlib and picolibc ...

@keith-packard I'm currently looking at what's needed for the arm-clang libc.  So feel free to submit PRs to refactor what's needed for newlib/picolibc.

**Comment by nordicjm** [comment]
> @galak
> 
> This change introduce new cmake warning during build when using toolchain from Zephyr SDK:
> 
> ```
> CMake Warning at /home/user/zephyr/zephyr/CMakeLists.txt:828 (message):
>   No SOURCES given to Zephyr library: lib__lita/zephyr/zephyr-arc-64/zephyr/CMakeLists.txt:828 (message):
>   No SOURCES given to Zephyr library: lib__libc__common
> 
>   Excluding target from build.
> ```
> 
> How to reproduce:
> 
> ```
> west build -b qemu_arc_hs samples/hello_world
> ```
> 
> May I ask you to check?
> 
> Thanks!

Issue was opened here about it: https://github.com/zephyrproject-rtos/zephyr/issues/56243

**Pull request merged**
