### PR TITLE
doc: Fix double 'the'

### PR DESCRIPTION
**Pull request by butok**
Fix double 'the' in all .rst documentation.

### CODE REVIEW

**Review by kartben — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
Thanks! This greatly improves the the documentation.

**Comment by butok** [comment]
> Thanks! This greatly improves the the documentation.

I decided to read all the documentation. 
8 documentation fixes have already been merged. 
Other corrections will come later.

**Comment by henrikbrixandersen** [comment]
> I decided to read all the documentation. 
> 
> 8 documentation fixes have already been merged. 
> 
> Other corrections will come later.

Awesome, thank you so much. This is a huge effort.

**Review by nashif — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
wow

**Comment by fabiobaltieri** [comment]
Still after this one:

```console
$ git grep 'the the ' | wc -l
65
```

not in .rst files, how can this be so common

**Comment by kartben** [comment]
> not in .rst files, how can this be so common?

That's the the question

**Comment by kartben** [comment]
see #65237!

**Pull request merged**
