### PR TITLE
dts: arm: nxp_rt: Fix typo in DT_PWM_MCUX_3_INDEX definition

### PR DESCRIPTION
**Pull request by andy0808**
DT_NXP_IMX_4PWM_03DC000_PWM3_INDEX should be
    DT_NXP_IMX_PWM_403DC000_PWM3_INDEX.
    
    Signed-off-by: Andy Liu <andy@madmachine.io>

### CODE REVIEW

**Comment by ulfalizer** [comment]
Could make the commit message something like

```
dts: arm: nxp_rt: Fix typo in DT_PWM_MCUX_3_INDEX definition

DT_NXP_IMX_4PWM_03DC000_PWM3_INDEX should be
DT_NXP_IMX_PWM_403DC000_PWM3_INDEX.

Signed-off-by: madandyliu <andy@madmachine.io>
```

to get it past the automated tests.

Think there might be some real-name policy too.

(Don't know the code itself, though it looks right to me.)

**Comment by andy0808** [comment]
Got it, this is my first pull request at Github. Still trying to get familiar with the system.

**Comment by ulfalizer** [comment]
@andy0808 
After editing the commit (with e.g. `git commit --amend`), do a `git push --force` to replace the old commit.

**Comment by andy0808** [comment]
@ulfalizer Thank you so much for your detailed information : )

**Review by MaureenHelm — APPROVED** [review]
Good catch, thank you!

**Review by galak — APPROVED** [review]

**Pull request merged**
