### PR TITLE
Bluetooth: controller: Add data path config for ISO sync receiver

### PR DESCRIPTION
**Pull request by mtpr-ot**
- Assign sync_delay parameters for ISO-AL sink creation
- Store framing information from BIGinfo for use in sink creation
- Set max_octets for sink creation

### CODE REVIEW

**Comment by mtpr-ot** [comment]
@cvinayak, any idea why that simulation test fails?

**Comment by cvinayak** [comment]
@Thalley any clues as to why CAP bsim test is failing for the trivial fix in the controller?

**Comment by mtpr-ot** [comment]
We have discovered that the reason this commit makes the simulation test fail, is that the test uses framing, which does not work in the broadcaster. The test should be disabled to avoid false positives. @Tronil has a PR on the way to fix framing in the broadcaster.

**Comment by mtpr-ot** [comment]
Included in PR #74244

**Pull request closed without merging**
