### PR TITLE
Microchip: MEC172x: I2C driver

### PR DESCRIPTION
**Pull request by scottwcpg**
Microchip MEC172x series I2C driver implementing controller
and target modes. The driver implemenents its own I2C port
pin control functions and does not depended upon pinmux. Future
updates will make use of PINCTRL when that subystem is finalized.

Signed-off-by: Scott Worley <scott.worley@microchip.com>

### CODE REVIEW

**Review by jackrosenthal — APPROVED** [review]

**Review by albertofloyd — APPROVED** [review]

**Review by cfriedt — CHANGES_REQUESTED** [review]
Please rebase & fix merge conflicts

**Comment by scottwcpg** [comment]
@cfriedt Why is the PM device_runtime being built?  I don't have any PM implemented or enabled at this time.  Is this a new requirement?

**Comment by cfriedt** [comment]
> @cfriedt Why is the PM device_runtime being built? I don't have any PM implemented or enabled at this time. Is this a new requirement?

Not sure - latest docs indicate that it is n-selected.

**Comment by scottwcpg** [comment]
If I run twister locally for the mec172xevb_assy6906 platform is runs 37 tests and has 4 build failures.  Three are PM tests.
samples/modules/nanopb/sample.modules.nanopb       FAILED: Cmake build failure  This fails because it can't find external protoc tool
tests/subsys/pm/power_mgmt/subsys.pm.device_pm     FAILED: Build failure
tests/subsys/pm/device_runtime/subsys.pm.device_pm FAILED: Build failure
tests/kernel/device/kernel.device.pm               FAILED: Build failure
The mec15xxevb_assy6853 which I have not touched with this PR fails the same tests except kernel.device.pm. Not sure if it ran this test as I couldn't find it in the log.

**Comment by scottwcpg** [comment]
@cfriedt The PM tests started being run in commit 8eceeee798743d25ac882cf0374cb062a435cefe pm: device: Add wakeup source API.  The commit includes pm.yaml in base.yaml.  pm.yaml has a new property named wakeup-source. The build is failing because the PM tests are expecting wakeup-source to be present in the pinmux or gpio driver. 
The nanopb failure was caused by not having the protocol buffer compiler installed on my build machine.  Once I installed the protocol buffer compiler the nanopb test passed.

**Comment by scottwcpg** [comment]
@ceolin The pm: device: Add wakeup source API commit 8eceeee798743d25ac882cf0374cb062a435cefe is triggering new PM tests to be run against MCHP boards.  We don't have the new PM API implemented.  Is there a way to disable these tests until we have the new PM implemented in the future?

**Comment by cfriedt** [comment]
@mbolivar - I think @scottwcpg needs some DT sleuthing - can you help?

**Comment by mbolivar-nordic** [comment]
@cfriedt sure, I'll try. Please note that my work handle is @mbolivar-nordic.

**Comment by mbolivar-nordic** [comment]
@scottwcpg is this fixed by https://github.com/zephyrproject-rtos/zephyr/pull/37679?

**Comment by scottwcpg** [comment]
@mbolivar-nordic Hi. Yes #37679 fixes the test breakage.  No need to use board level ignore_tags.

**Comment by scottwcpg** [comment]
@cfriedt Rebased to pull in #37679 which should fix the failing PM tests.

**Comment by scottwcpg** [comment]
What needs to happen to get this PR merged?

**Comment by ravinprv** [comment]
> @cfriedt Rebased to pull in #37679 which should fix the failing PM tests.

@cfriedt may we know when this PR will be merged

**Pull request merged**
