### PR TITLE
RTC and CAN shell completion

### PR DESCRIPTION
**Pull request by yishai1999**
Trying to improve the shell commands completion

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Limiting the device selection/completion to in-tree compatibles is not an option, sorry. 

This needs to solved on a higher level, which is being worked on.

**Comment by yishai1999** [comment]
@henrikbrixandersen  I saw this is what's done in the ADC shell. How come it's not an option here? At least until a wider solution is found...

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen I saw this is what's done in the ADC shell. How come it's not an option here? At least until a wider solution is found...

Correct, but we are actively working on getting rid of that (see https://github.com/zephyrproject-rtos/zephyr/pull/67698 and https://github.com/zephyrproject-rtos/zephyr/pull/71773). There is no point in introducing more technical dept in this area.

**Comment by kartben** [comment]
as per earlier comments, will close this one given recommended approach is being discussed in other PRs. @yishai1999 please do feel free to chime in there if you haven't already as I hope you will find other way to contribute than this current PR! :)

**Pull request closed without merging**
