### PR TITLE
[v2.7-branch] actions: west/devicetree: exclude python 3.6 on windows

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This version of python is not available anymore. Excluding for now to
unblock CI.

Fixes: #49139

Signed-off-by: Anas Nashif <anas.nashif@intel.com>
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>
(cherry picked from commit 773242cbb705a887ca6b7445ec79636ce7b65069)

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
I'll need some time to figure out why mypy is complaining

**Comment by mbolivar-nordic** [comment]
> I'll need some time to figure out why mypy is complaining

We can get mypy to shut up if we merge https://github.com/zephyrproject-rtos/zephyr/pull/49976 and cherry-pick it onto this PR. I think that's the best way to go.

**Comment by cfriedt** [comment]
@mbolivar-nordic - is this basically ready? There are a couple of compliance warnings so I wasn't sure.

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic - is this basically ready? There are a couple of compliance warnings so I wasn't sure.

Yep, should be with the latest push.

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
