### PR TITLE
logging: support runtime packaging without format strings in mem

### PR DESCRIPTION
**Pull request by dcpleung**
This adds support for runtime packaging with tagged arguments so that cbprintf_package() can function without the format strings in memory. This allows the format strings to be removed from final binary to converse space.

### CODE REVIEW

**Comment by dcpleung** [comment]
@nordic-krch here is my attempt to do runtime packaging without format strings in memory. In current form, this is guarded behind kconfig so the old path is still the default (as not to disrupt anyone). `CONFIG_LOG_PRINTK` is not supported at the moment as it would require some more macro work. I will work on supporting `printk()` if this is an acceptable way to go forward.

**Comment by nordic-krch** [comment]
@dcpleung I started to think that it can actually be done much simpler as part of static packaging. What we need is to add runtime string length to package length when macro is called with NULL pointer and when macro is called with a buffer we can create an array with indexes where string arguments are located and then call a function that takes created package and array of those indexes and do the copying into the package.

Pieces of this is already done since there is an option to collect indexes of strings and attach it to the package (added by #37133): 
https://github.com/zephyrproject-rtos/zephyr/blob/22c0843485b5d03a8bf1de8499fe1d20d2ded3d3/include/sys/cbprintf_internal.h#L276

As the outcome we could use static method in all cases. That would speed up a lot. Runtime packaging would be used when features are not supported or to reduce stack usage in no optimization case.

**Comment by nordic-krch** [comment]
@dcpleung fyi, keep working on the proposal. Will publish something tomorrow.

**Comment by dcpleung** [comment]
> @dcpleung fyi, keep working on the proposal. Will publish something tomorrow.

That's great. Thank you. :)

**Comment by nordic-krch** [comment]
Took more time but draft PR is out: #43150

**Pull request closed without merging**
