### PR TITLE
 soc: x86: apollo_lake: Turn .rst doc into .txt

### PR DESCRIPTION
**Pull request by carlescufi**
In order to avoid a warning from Sphinx complaining that the
    supported_features.rst file is not included in any ToC, rename it to
    .txt so that Sphinx understands that this is only a snippet to be
    included in other files.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
Added 2.1 milestone since this has been triggering a warning on doc builds on Windows:

`C:\Users\Carles\src\zephyr\zephyr\doc\b\rst\doc\soc\x86\apollo_lake\doc\supported_features.rst: WARNING: document isn't included in any toctree`

**Comment by nashif** [comment]
That file should just be removed

**Comment by carlescufi** [comment]
> That file should just be removed

It's included in several boards' doc, including Up-Squared.

**Comment by nashif** [comment]
> It's included in several boards' doc, including Up-Squared.

Oh ok, I thought the file was empty, just looked at the diff. Good then

**Review by nashif — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Review by dbkinder — DISMISSED** [review]
While this will work, if this file is only included and not in a TOC, the preferred way is to rename this file to ``supported_features.txt`` and change the references to this txt file instead of a rst file.  (Sphinx looks for ALL .rst files to make sure they're in a TOC, but doesn't care about .txt files.)

There are two references to this (included) file:

- boards/x86/up_squared/doc/index.rst
- boards/x86/gpmrb/doc/index.rst

**Comment by carlescufi** [comment]
> While this will work, if this file is only included and not in a TOC, the preferred way is to rename this file to `supported_features.txt` and change the references to this txt file instead of a rst file. (Sphinx looks for ALL .rst files to make sure they're in a TOC, but doesn't care about .txt files.)
> 
> There are two references to this (included) file:
> 
> * boards/x86/up_squared/doc/index.rst
> * boards/x86/gpmrb/doc/index.rst

Interesting. Why is that the preferred way? I’d have thought that keeping the rst extension and adding a simple directive was cleaner.

**Comment by dbkinder** [comment]
Using ``:orphan:`` doesn't stop Sphinx from processing that .rst file and generating an HTML output for it, so you can still view it as https://docs.zephyrproject.org/latest/soc/x86/apollo_lake/doc/supported_features.html even though it's not in the toctree.  We don't want this file to exist as a generated HTML file, so renaming it as a .txt file keeps Sphinx from processing it.

**Comment by ru-fu** [comment]
Agree - there's a difference between snippets that can be included and actual rst files.

**Comment by carlescufi** [comment]
> Using `:orphan:` doesn't stop Sphinx from processing that .rst file and generating an HTML output for it, so you can still view it as https://docs.zephyrproject.org/latest/soc/x86/apollo_lake/doc/supported_features.html even though it's not in the toctree. We don't want this file to exist as a generated HTML file, so renaming it as a .txt file keeps Sphinx from processing it.

Understood, makes sense. Will fix with your approach.

**Comment by nashif** [comment]
maybe .rst.inc, to signify that this file is being included by someone else and is not a standalone .txt

**Comment by carlescufi** [comment]
> maybe .rst.inc, to signify that this file is being included by someone else and is not a standalone .txt

Not opposed to that, although we seem to use `.txt` in other places already (see for example `substitutions.txt` which is in fact an `.rst` file).

**Review by ru-fu — APPROVED** [review]
Any file extension will work for includes, but I vote for being consistent. So .txt is fine imo.

**Review by dbkinder — APPROVED** [review]
Thanks!

**Comment by dleach02** [comment]
Thanks

**Pull request merged**
