### PR TITLE
twister: fix the testcase-schema.yaml

### PR DESCRIPTION
**Pull request by smrtos**
Change the "yes/no" value to "true/false".
Otherwise pykwalify 1.8.0 will report below errors:
- Value: 'no' for required keyword must be a boolean:
  Path: '/mapping/common'>
- Value: 'yes' for required keyword must be a boolean:
  Path: '/mapping/sample/mapping/name'>

Signed-off-by: Shao Ming <ming.shao@intel.com>

### CODE REVIEW

**Review by chen-png — APPROVED** [review]

**Comment by nashif** [comment]
Why are you closing old PRs and opening new ones for the same code? You should be able to update existing PR with changes, no need to create new PRs.

**Review by nashif — APPROVED** [review]

**Comment by smrtos** [comment]
I saw there is a merging commit message after I amended the commit.
And its format cannot pass the CI check.
So I created new PR.
Maybe there's a better way to handle this.

**Review by enjiamai — APPROVED** [review]

**Comment by nashif** [comment]
> I saw there is a merging commit message after I amended the commit.
> And its format cannot pass the CI check.
> So I created new PR.
> Maybe there's a better way to handle this.

you should be able to fixup the branch or reset it and apply new commits and still push back to the same PR, no need to create new PRs for each fixup.

**Comment by smrtos** [comment]
> > I saw there is a merging commit message after I amended the commit.
> > And its format cannot pass the CI check.
> > So I created new PR.
> > Maybe there's a better way to handle this.
> 
> you should be able to fixup the branch or reset it and apply new commits and still push back to the same PR, no need to create new PRs for each fixup.

After some experiment I guess I figured it out. Thanks for the hints.

**Pull request merged**
