### PR TITLE
update bt host .bls to add new LE Audio profiles PBP and GMAP

### PR DESCRIPTION
**Pull request by JingsaiLu**
update bt host .bls and .pts to add new LE Audio profiles PBP and GMAP with mandatory ICS items

**some items (such as [GMAP] (1/1) and [GMAP] (1/3)) are disabled as they depends on [CAP] (1/3)**

image

All ICS inconsistencies are resolved.
Could review by importing .bls into https://launchstudio.bluetooth.com/ or importing .pts into local pts workspace.

### CODE REVIEW

**Comment by Thalley** [comment]
@jsplyy please rebase this

**Comment by MaureenHelm** [comment]
@Thalley please revisit

**Comment by Thalley** [comment]
Will check it out soon - Thanks for the reminder Maureen. 

Just FYI, this will possibly conflict with https://github.com/zephyrproject-rtos/zephyr/pull/71942

**Review by Thalley — CHANGES_REQUESTED** [review]
Comments:

GMAP:
1. This does not seem to enable the GMAUGG or BGS. How come? 
2. Why are we not enabling UGT multiplex, multisink and multisource? We should be able to support that
3. Why are we not enabling 33/1 (advertisements) for UGT? 
4. Why are we not enabling 34/5 (multiple ASEs) for UGT?
5. Why are we not enabling 40/27 - 40/72 for UGT? We should support all of them
6. Why are we not enaling 41/1 for authenticated pairing for UGT? 
7. Why are we not enabling 72/1 and 72/2 for BGR? 

Actually I don't think there is a single feature/option for GMAP that shouldn't/couldn't be enabled. 

PBP
1. We support sending metadata and Program_Info (6/1 and 6/2) for PBS
2. We support 24_2_1 and 24_2_2 (7/2 and 7/4) for PBS

Similar to GMAP, we should support all the things for PBP, except for the broadcast assistant that isn't implemented yet.

**Comment by jsplyy** [comment]
Thanks @Thalley , I will check and update asap, need some time to check the specs for your questions,

**Comment by jsplyy** [comment]
Hi @Thalley ,

Is CAP commander feature ready ?
you commented CAP commander is not ready when this PR is created before, and still is disabled in current bls file.
but GAMP UGG and BGS features depend on it.

image

image

**Comment by Thalley** [comment]
> Hi @Thalley ,
> 
> Is CAP commander feature ready now? you commented CAP commander is not ready when this PR is created before, and **is still disabled in current bls file**. but GAMP UGG and BGS features depend on it.
> 
> image
> 
> image

Most of it is available, yes. 

We do not have the broadcast reception and distribute broadcast code fully implemented yet, but they are being worked on.

**Comment by jsplyy** [comment]
Hi @Thalley, I have accepted all your suggestions and updated the ics files,
now, all the GMAP and PBP features are included, excepting BR/EDR items, also enabled the CAP dependency features.
expect to be merged before code freeze : )

for the CI checking, it has dos line and whitespace issues, 
I could fix it, but the launch studio will not import it if have that changes. 
Could we have force merge if no other issues ?

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
> for the CI checking, it has dos line and whitespace issues,
> I could fix it, but the launch studio will not import it if have that changes.

In this kind of cases we usually just override CI and merge anyway, e.g. with the help of @carlescufi

**Comment by Thalley** [comment]
I believe this PR now redundant due to the new qualification tools. I believe @sjanc has added the changes from this PR to another (future) PR that will work with the new tools.

**Comment by Thalley** [comment]
superseded by https://github.com/zephyrproject-rtos/zephyr/pull/75419

**Pull request closed without merging**
