### PR TITLE
Add script for partly automating devicetree bindings release notes

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This script generates .rst describing the devicetree bindings changes between two git revisions in the zephyr repository. I used it in https://github.com/zephyrproject-rtos/zephyr/pull/54869.

Its purpose is to avoid tedium while writing release notes, and to speed up that process. You can use its output directly, but it is better for the developer experience if you read over it to identify common patterns and clean up the output based on that.

For example, if every device of type X gets a new property Y, then you can delete the many repeated lines saying "new property Y" and replace them with a single bullet point saying "devices of type X now all have property Y; see <binding.yaml> for details".

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
cc @erwango

**Comment by mbolivar-nordic** [comment]
@galak ping

**Review by carlescufi — DISMISSED** [review]
LGTM! thanks!

**Comment by erwango** [comment]
Don't beat me, as I'm sure I'm doing something wrong, but I get following error (Python 3.8.10):
```
$ python3 scripts/release/list_devicetree_bindings_changes.py --start a04cbc3180d737c7d1771116966ee3cc34c1f361 --end 50c1f857e0743e7ed70a0a43ff2193e4f94a9f08 --file res.rst
Traceback (most recent call last):
  File "scripts/release/list_devicetree_bindings_changes.py", line 307, in <module>
    start_fn: Callable[str, Any],
  File "/usr/lib/python3.8/typing.py", line 813, in __getitem__
    raise TypeError(f"Callable[args, result]: args must be a list."
TypeError: Callable[args, result]: args must be a list. Got <class 'str'>
```

**Comment by mbolivar-nordic** [comment]
@erwango thanks! Botched rebase; I was testing with `from __future__ import annotations` on my machine before I pushed and fixed things up one by one on the earlier version of python we have here.

There are no `--start`, `--end`, or `--file` options, though; these are positional arguments. For example:

```
python3 scripts/release/list_devicetree_bindings_changes.py a04cbc3180d737c7d1771116966ee3cc34c1f361 50c1f857e0743e7ed70a0a43ff2193e4f94a9f08 res.rst
```

**Comment by erwango** [comment]
@mbolivar-nordic Really nit. Now I wonder what I'll do with all this suddenly freed time at each release :-D
One suggestion:
What do you think about grouping the results per vendor ?
I guess that release note readers focus on the platform(s) they care about. Grouping per vendor might help to have a quick view of the changes.

**Comment by mbolivar-nordic** [comment]
@erwango done

**Review by erwango — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
