### PR TITLE
Bluetooth: Rename `num_complete_pool` -> `sync_evt_pool`

### PR DESCRIPTION
**Pull request by alwa-nordic**
Refactor only. The surrounding ifdefs are intentionally not changed in this patch. They will be in the near future.

Rename the pool and generalize the documentation to allow using this pool for other events that fit the same criteria. This pool can be used for any buffer that is processed synchronously, without negatively affecting 'num complete' messages. E.g. 'cmd complete/status' can be put in this pool already.

We will be working towards making the host process all event buffers synchronously. This is because events have no dedicated flow control, and discarding events in the driver without informing the host creates problems. Discarding should instead happen in the host higher layers when unavoidable.

### CODE REVIEW

**Comment by Thalley** [comment]
> We will be working towards making the host process all event buffers synchronously. 

Can you elaborate on this?

**Comment by alwa-nordic** [comment]
> > We will be working towards making the host process all event buffers synchronously.
> 
> Can you elaborate on this?

The idea is that the 'generic event buffer' is processed synchronously. That way, it's illegal for any event handler to be special, delay the buffer de-allocation, and stall event handling. 

If a handler is special, then it needs to have special buffers. If the data for the special handler comes in a generic buffer, the special handler will need to `memcpy` it out to keep it. Ideally, handler don't need to memcopy into other net_bufs, but rather are able to summarize the data into fixed-size memory locations. E.g. The disconnect event handler can store the disconnect reason in `bt_conn.err` and schedule a work to invoke callbacks later.

If the driver puts special data in special buffers (for zero-copy reasons), and we are out of special buffers, the driver will take the generic buffer instead. When the special handler gets the generic buffer, it is obliged to act like a generic handler and free the buffer, e.g. by discarding the data.

E.g. advertising data can go in the discardable pool. But if that pool is full, the data goes in the generic pool. When the advertiser handler gets the generic buffer, it can note down in static memory that a discard has occurred, but it must free the buffer before returning.

A generic handler is not allowed to invoke any functions that block on HCI RX or TX, since this forms a potential deadlock. This means invoking arbitrary application callbacks is not allowed. Invoking the callbacks has to be offloaded off the `bt_recv` context. Isr-ok-marked callbacks may be invoked, but this is bad for other reasons like the stack size problem.

**Comment by Thalley** [comment]
> The idea is that the 'generic event buffer' is processed synchronously. That way, it's illegal for any event handler to be special, delay the buffer de-allocation, and stall event handling.

Does that involve getting rid of `bt_hci_cmd_send_sync` in the future, or what's the plan? Not sure I fully understand it yet

**Comment by alwa-nordic** [comment]
> > The idea is that the 'generic event buffer' is processed synchronously. That way, it's illegal for any event handler to be special, delay the buffer de-allocation, and stall event handling.
> 
> Does that involve getting rid of `bt_hci_cmd_send_sync` in the future, or what's the plan? Not sure I fully understand it yet

This plan shifts the problem away from `bt_hci_cmd_send_sync` existing to acknowledging that it's not isr-safe, so it shall not be called from a generic event handler.

It then becomes an orthogonal problem: So long as the special handler finds a way to offload the callbacks that end up in `bt_hci_cmd_send_sync` away from the `bt_recv` context to somewhere legal, you can keep on using `bt_hci_cmd_send_sync` if you want. But note that the system work queue is not an ok place to call blocking functions from. So the special handler will need to offload it to some other thread.

The 'plan' is to gradually 'formalize' the interfaces in the host with expectations around blocking. We do this by starting with the core hci and pushing the legacy cruft out to the edges of 'the nice garden'.

So I don't have a concrete design in UML to show you :P. But I have ideas about principles that should resolve our issues if we apply them repeatedly.

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by Thalley** [comment]
> > > The idea is that the 'generic event buffer' is processed synchronously. That way, it's illegal for any event handler to be special, delay the buffer de-allocation, and stall event handling.
> > 
> > 
> > Does that involve getting rid of `bt_hci_cmd_send_sync` in the future, or what's the plan? Not sure I fully understand it yet
> 
> This plan shifts the problem away from `bt_hci_cmd_send_sync` existing to acknowledging that it's not isr-safe, so it shall not be called from a generic event handler.
> 
> It then becomes an orthogonal problem: So long as the special handler finds a way to offload the callbacks that end up in `bt_hci_cmd_send_sync` away from the `bt_recv` context to somewhere legal, you can keep on using `bt_hci_cmd_send_sync` if you want. But note that the system work queue is not an ok place to call blocking functions from. So the special handler will need to offload it to some other thread.
> 
> The 'plan' is to gradually 'formalize' the interfaces in the host with expectations around blocking. We do this by starting with the core hci and pushing the legacy cruft out to the edges of 'the nice garden'.
> 
> So I don't have a concrete design in UML to show you :P. But I have ideas about principles that should resolve our issues if we apply them repeatedly.

Thanks for the explanation, then I understand the path and the goal :) And thanks for doing this in smaller steps than a huge PR

**Review by jori-nordic — APPROVED** [review]

**Pull request merged**
