### PR TITLE
Revert "samples: net: Fix sanitycheck for sam_e70_xplained board"

### PR DESCRIPTION
**Pull request by pfalcon**
This reverts commit a0df4f66984b3cc52c07da52e74fdadf7c79b728.

This commit has the following description:

"""
Some of the sanitycheck tests were having too small limit for
network buffers when compiling for sam_e70_xplained board.
Increase the buffer limits when testing this for this board.
"""

But the actual code changes do not correspond to this description:
instead of making changes just for the affected sam_e70_xplained,
actually the defaults for all Ethernet boards are changed.

This has negative impact on BOARD=frdm_k64f. Specifically, without
a0df4f6698, using samples/net/sockets/dumb_http_server and
ApacheBench's "ab -n1000 http://192.0.2.1:8080/" (i.e. load-test
the Zephyr IP stack with serving 1000 consecutive connections),
everything works as expected (excerpts from the ab report):

Time taken for tests:   8.171 seconds
Complete requests:      1000
Percentage of the requests served within a certain time (ms)
  50%      8
  66%      8
  75%      8
  80%      8
  90%      8
  95%      8
  98%      8
  99%      9
 100%     21 (longest request)

However, with a0df4f6698 in effect, running the same command serves
10-100 requests OK, but then the visible slowdown starts. After
breaking ab after 30s (otherwise, it could take hour(s) to finish),
the result is:

Time taken for tests:   35.449 seconds
Complete requests:      51
Percentage of the requests served within a certain time (ms)
  50%      8
  66%   1216
  75%   1312
  80%   1312
  90%   1472
  95%   1984
  98%   2560
  99%   3776
 100%   3776 (longest request)

Thus, revert a0df4f6698, as generally an Ethernet board works OK with
the settings as were before. Suggestions regarding sam_e70_xplained:
1. Try to anylize why its behavior is different from e.g. frdm_k64f.
(Perhaps, the matter is not just one board vs another board, but
one sample vs another. Different samples should be tested (including
samples/net/sockets/), and only affected should have config changed.)
2. If truly needed, sam_e70_xplained-specific settings should go in
its specific config(s).

### CODE REVIEW

**Comment by pfalcon** [comment]
As promised in https://github.com/zephyrproject-rtos/zephyr/pull/6789#issuecomment-386905227 , I submit a patch to revert back unduly increase in network buffers just for the Ethernet L2. The commit message goes into details as to why. 

Here I can just post complete ApacheBench reports (the commit message has them abbreviated).

With a0df4f6 (breaking after ~30s):

~~~
Concurrency Level:      1
Time taken for tests:   35.449 seconds
Complete requests:      51
Failed requests:        0
Total transferred:      111231 bytes
HTML transferred:       108222 bytes
Requests per second:    1.44 [#/sec] (mean)
Time per request:       695.080 [ms] (mean)
Time per request:       695.080 [ms] (mean, across all concurrent requests)
Transfer rate:          3.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  399 490.3      1    1030
Processing:     4  249 520.4      7    2753
Waiting:        4  249 520.4      7    2753
Total:          6  649 842.1      8    3776

Percentage of the requests served within a certain time (ms)
  50%      8
  66%   1216
  75%   1312
  80%   1312
  90%   1472
  95%   1984
  98%   2560
  99%   3776
 100%   3776 (longest request)
~~~

Without a0df4f6 (i.e. with this revert patch):
~~~
Concurrency Level:      1
Time taken for tests:   8.171 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      2181000 bytes
HTML transferred:       2122000 bytes
Requests per second:    122.38 [#/sec] (mean)
Time per request:       8.171 [ms] (mean)
Time per request:       8.171 [ms] (mean, across all concurrent requests)
Transfer rate:          260.65 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.5      1      14
Processing:     2    7   0.8      7      20
Waiting:        1    7   0.8      7      20
Total:          6    8   0.8      8      21

Percentage of the requests served within a certain time (ms)
  50%      8
  66%      8
  75%      8
  80%      8
  90%      8
  95%      8
  98%      8
  99%      9
 100%     21 (longest request)
~~~

**Comment by pfalcon** [comment]
I'd like to add that the behavior is in full accordance with the definition of https://en.wikipedia.org/wiki/Bufferbloat - throwing more buffers on the fire seems like solve one issue, but actually pops up different.

**Review by jukkar — CHANGES_REQUESTED** [review]
Instead of reverting this fully, I am hoping you provide then a patch that fixes the issue with sam_e70_xplained board which ran out of memory. I am ok if we revert this but then a solution for this atmel board needs to be provided.

**Comment by pfalcon** [comment]
> Instead of reverting this fully, I am hoping you provide then a patch that fixes the issue with sam_e70_xplained board which ran out of memory.

Unfortunately, I don't have sam_e70_xplained, so can prepare only a mechanical patch which you'd need to test still. In that case, my choice would be to put the overrides into boards/arm/sam_e70_xplained/ (perhaps, sam_e70_xplained_defconfig), with a clear note that there's no logical explanation why these overrides are needed for this board.

But the main point - this is posted for review and confirmation of the issue. Did you have a chance to try the tests which are described in the commit message on frdm_k64f? Because so far only I report that there's a problem, and unless reproduced independently it doesn't cost much. (And results of reproducing may vary, as e.g. https://github.com/zephyrproject-rtos/zephyr/issues/7818 show.) Thanks.

**Comment by pfalcon** [comment]
> Did you have a chance to try the tests which are described in the commit message on frdm_k64f?

Also please do that without https://github.com/zephyrproject-rtos/zephyr/pull/7849 , as it may change the behavior. (Not fix the issue, just change the behavior, e.g. make the issue masked for the specific test scenario.)

**Comment by jukkar** [comment]
I was not able to test with frdm_k64f as the dump_http_server application kept hanging when printing something. Dunno what was wrong with it.

Anyway, it worked a bit better with qemu_x86. I managed to get memory allocation report which says this:
```
shell> net allocs
Network memory allocations

memory		Status	Pool	Function alloc -> freed
0x00412b78/2	used	TX	zsock_sendto():250
0x0040a1b0/1	used	TDATA	net_pkt_append():1233
0x0040a1c8/1	used	TDATA	net_pkt_append_bytes():1209
0x0040a1e0/1	used	TDATA	net_pkt_append_bytes():1209
0x0040a1f8/1	used	TDATA	net_pkt_append_bytes():1209
0x0040a210/1	used	TDATA	net_pkt_append_bytes():1209
0x0040a228/1	used	TDATA	net_pkt_append_bytes():1209
0x0040a258/1	used	TDATA	net_ipv4_create_raw():38
```

It is a bit difficult to say whether this will affect the outcome but we need to fix the leak first.

After running apache bench for a while, the application crashed

```
***** CPU Page Fault (error code 0x00000000)
Supervisor thread read address 0x00000058
PDE: 0x025 Present, Read-only, User, Execute Enabled
PTE: 0x00 Non-present, Read-only, Supervisor, Execute Enabled
Current thread ID = 0x00403eb8
eax: 0x00000000, ebx: 0x004148dc, ecx: 0x00000246, edx: 0x00000000
esi: 0x0040ff90, edi: 0x00000006, ebp: 0x0041af84, esp: 0x0041af4c
eflags: 0x00000206 cs: 0x0008
call trace:
eip: 0x0000d450
     0x0000b946 (0x6)
     0x00008d4e (0x4148dc)
     0x00008d9e (0x41afd0)
     0x000131ae (0x4148e0)
     0x00003f4b (0x403ea0)
Fatal fault in thread 0x00403eb8! Aborting.
```

The net-shell was still responsive after the crash.

**Comment by jukkar** [comment]
> It is a bit difficult to say whether this will affect the outcome but we need to fix the leak first.

It might be that there is no "leak" here as the net_pkt might be just waiting for ACK that we did not receive yet. Thus this needs more testing.

**Comment by pfalcon** [comment]
> I was not able to test with frdm_k64f as the dump_http_server application kept hanging when printing something. Dunno what was wrong with it.

This is really weird. I mean, the kind of the outcome you get. The difference in our outcomes per se doesn't surprise me however, I myself may get differences testing few days ago and today (most are due to "false positives" though). Or you can compare investigation in https://github.com/zephyrproject-rtos/zephyr/issues/7818, where for @rlubos something 100% doesn't work, which has always worked 100% (or 99%) for me.

We'd need to sync on our testing and get to the bottom of that. For that, we'd need to be as exact as possible to allow for repeatability. Can you please confirm the exact git rev you tested, so I can retest it, and we can contrast the results for the same rev? Any further details on the test process are helpful too to pinpoint any differences in it. I try to describe mine in https://github.com/pfalcon/zephyr/wiki/NetworkingTestPlan

**Comment by pfalcon** [comment]
> Anyway, it worked a bit better with qemu_x86.

Well, qemu_x86 has been working OK for me for quite some time lately (IIRC), which I tribute to slowness of qemu and SLIP (so, contingency points aren't hit, as with fast Ethernet).

> I managed to get memory allocation report which says this:
> shell> net allocs

So, dumb_http_server sample doesn't enable net_shell, which means you already tested something different than I ;-). (And yes, any change in config may have a butterfly effect. I many times tried to debug these issues with logging - the problem behavior goes away or radically changes.)

> After running apache bench for a while, the application crashed

Didn't see anything like that for quite some time.

For reference, I just ran "ab -n1000 http://192.0.2.1:8080/" against qemu_x86 with master c4b0f1c5b451bc6a. No issues:

~~~
Time taken for tests:   19.995 seconds
Complete requests:      1000
 100%    109 (longest request)
~~~

**Comment by pfalcon** [comment]
@rlubos : Wanna join fun with testing dumb_http_server too? ;-)

**Comment by rlubos** [comment]
@pfalcon Heh, thanks for the invitation :)

Well I don't have sam_e70_xplained nor frdm_k64f so all I can do is to run it on qemu.

So I ran it on qemu_x86, and I was just going to report that it works fine for me, when the app froze when I was writing this comment. It just paused after handling ~5K connections, no crash or whatsoever. I was hoping to reproduce the issue to get some more detail, unfortunately wasn't able on qemu_x86...

But, then I ran it on qemu_cortex_m3 and it's fairly easy to reproduce, at least on my desk, the application freezes just after few connections are established. Yet it's still not a crash. Not sure why is it happening, perhaps I can mess a little bit with debugging.

I'm ran vanilla version of `dumb_http_server` on a branch from this PR.

**Comment by pfalcon** [comment]
@rlubos :

> So I ran it on qemu_x86, and I was just going to report that it works fine for me, when the app froze when I was writing this comment. It just paused after handling ~5K connections,

Great, thanks! And well, I'm talking about 1000 requests (`ab -n1000`) for a reason, to have a "reasonable" baseline (call it smoke test if you want). Because well, for me, with this current patch applied, on frdm_k64f, I can get 1K requests served well 100% reproducibly. But if I up that to 10K, I'll still get slowdown eventually. So, there're still issues lurking in the stack, and munging number of buffers back and forth like this patch, doesn't resolve issues, but simply works them around for a particular case ("mask" in my own terminology).

But anyway, I recommend standardizing on 1000 requests. The number chosen because it's, well, at least reasonable if not venerable, and because test with it completes quickly (under 1min), so can be run regularly (as a smoke test again).

When all IP stack developers will be able to see those 1K requests served, we have a good baseline to resolve "more rare" issues. As @jukkar's case shows, we aren't even there :-(.


> no crash or whatsoever. I was hoping to reproduce the issue to get some more detail, unfortunately wasn't able on qemu_x86...
> But, then I ran it on qemu_cortex_m3 and it's fairly easy to reproduce, at least on my desk, the application freezes just after few connections are established.

Thanks for the info, will try to play with that too.

**Comment by jukkar** [comment]
> Can you please confirm the exact git rev you tested, so I can retest it, and we can contrast the results for the same rev?

Friday testing was with c4b0f1c5b451bc6a0cc3c2d13950383b45e37469 + your "Revert "samples: net: Fix sanitycheck for sam_e70_xplained board" applied. I also enabled net-shell + some other relevant / not so relevant options

```
--- prj.conf	2018-05-25 13:44:25.936387479 +0300
+++ prj.conf.jukka	2018-05-25 15:33:02.348526687 +0300
@@ -8,6 +8,9 @@
 CONFIG_NET_TCP=y
 CONFIG_NET_SOCKETS=y
 CONFIG_NET_SOCKETS_POSIX_NAMES=y
+CONFIG_INIT_STACKS=y
+CONFIG_NET_TX_STACK_SIZE=2200
+CONFIG_NET_RX_STACK_SIZE=2500
 
 # Network driver config
 CONFIG_TEST_RANDOM_GENERATOR=y
@@ -25,4 +28,18 @@
 
 # Network debug config
 #CONFIG_NET_DEBUG_SOCKETS=y
-CONFIG_SYS_LOG_NET_LEVEL=2
+CONFIG_NET_LOG=y
+CONFIG_SYS_LOG_SHOW_COLOR=y
+CONFIG_SYS_LOG_NET_LEVEL=4
+CONFIG_NET_DEBUG_NET_PKT=y
+CONFIG_NET_BUF_POOL_USAGE=y
+
+CONFIG_NET_SHELL=y
+CONFIG_NET_STATISTICS=y
+
+CONFIG_NET_PKT_RX_COUNT=100
+CONFIG_NET_PKT_TX_COUNT=100
+CONFIG_NET_BUF_RX_COUNT=160
+CONFIG_NET_BUF_TX_COUNT=160
+
+CONFIG_PRINTK=y
```

**Comment by pfalcon** [comment]
@rlubos 

> But, then I ran it on qemu_cortex_m3 and it's fairly easy to reproduce, at least on my desk, the application freezes just after few connections are established.

Ok, I can reproduce this, if "freezes" is defined as "the sample is stuck when processing a particular request; after some time, ApacheBench times out". But restarting `ab` shows that the app didn't freeze completely, it can process new batch of requests (until it will get stuck again). For reference, it's a1492325c050f645f627af913e88121b3b81091c (that's relatively old rev by now) + revert patch from this PR applied.

**Comment by pfalcon** [comment]
Now fast forward to 4a693c3c388db6cea3f19e8171c4964dc562e91f which is HEAD as of now, testing without this PR.

qemu_x86: Now, unlike e.g. with a149232, the processing gets stuck on some request, just as described for qemu_cortex_m3. In 3 runs, this happened on ~400th, ~200th, 993th request.

qemu_cortex_m3: Similar to a149232, gets stuck on <100th request.

**Comment by pfalcon** [comment]
Now 4a693c3 + revert from this PR:

qemu_x86: Works without a hitch, run 5 times * 1000 requests, even without qemu restart.

qemu_cortex_m3: Stuck on <100th request, as before.

**Comment by pfalcon** [comment]
4a693c3 + revert from this PR, continued:

frdm_k64f: works well for 1000 req

pristine 4a693c3:

frdm_k64f: delays starting with req. no 16.

**Comment by pfalcon** [comment]
Debugging qemu_cortex_m3 being stuck with just net shell doesn't show obvious probs, e.g. there's no shortage of free pkts/bufs. Submitted few cosmetic improvements to net shell instead.

**Comment by pfalcon** [comment]
Not trying to enable debug logging, as I know it'll skew results. Instead posted https://github.com/zephyrproject-rtos/zephyr/issues/8168.

**Comment by pfalcon** [comment]
> But, then I ran it on qemu_cortex_m3 and it's fairly easy to reproduce, at least on my desk, the application freezes just after few connections are established. Yet it's still not a crash. Not sure why is it happening, perhaps I can mess a little bit with debugging.

Ok, good (enough) understanding what happens there: https://github.com/zephyrproject-rtos/zephyr/issues/8187 , https://github.com/zephyrproject-rtos/zephyr/issues/8188 .

**Comment by pfalcon** [comment]
As of today's master 58e40cb029d55306afd1fcb835e0572b1c561698, the situation described in this PR still holds for me: with pristine master, running ab -n1000 results in slowdown after ~50th request, while with this patch applied, ab -n1000 goes thru.

**Comment by pfalcon** [comment]
Retested with today's master d003d0e6a69f57540bb7df9b9651a87e8ddf3b66, the situation is the same as in previous comment and before.

**Comment by jukkar** [comment]
This PR has become very convoluted and difficult to read. What we are trying to achieve here with this one as I do not see much point reverting the original patch and cause various errors in sanitychecker so I suggest we close this one.

**Comment by pfalcon** [comment]
> This PR has become very convoluted and difficult to read.

What exactly is difficult to read? The patch is simple (it's no longer a literal revert, had to be updated for later changes; the commit message can be fixed of course).

Comments? But that's good there're comments, much worse when there're no comments (a typical situation with networking issue reports).

> What we are trying to achieve here

It's the same as before, as described in the rather detailed commit message (also description of this PR). Summary: a) fix regression introduce to at least frdm_k64f; b) generally, we should no solve issue but increasing number of buffers, we should have defaults which should work across all hardware we support. (Like the older ones, which this patch restores.)

> cause various errors in sanitychecker

The only reason why there're sanitycheck errors is because one single driver (sam_e70's etehrnet) doesn't fit well with the rest of Zephyr. We have https://github.com/zephyrproject-rtos/zephyr/issues/9015 on that, and until it's fixed properly, we can/should blacklist sam_e70.

**Review by nashif — CHANGES_REQUESTED** [review]
reverting a commit (as the PR title says) from 3 months ago is not the right thing to do now, the original commit fixed some issues and I guess you are reverting because it introduced other issues? Can you submit a PR that fixes those new issues instead of the revert which is starting to be confusing?

**Comment by pfalcon** [comment]
> the original commit fixed some issues

No, the claim is that it worked around some issues, and while doing so, introduced more.

> Can you submit a PR that fixes those new issues instead of the revert which is starting to be confusing?

*This* is such PR, containing wealth of the information on the matter. The "revert" title will be changed.

**Comment by nashif** [comment]
stale PR, you can open an issue if this is still relevant or submit a new PR. The information here is not not going to be lost.

**Comment by pfalcon** [comment]
The PR updated. The issue it fixes is as fresh as it was more than half-year ago. The current status is that there're slow negotiations with @mnkp in https://github.com/zephyrproject-rtos/zephyr/issues/9015 on how to fix it *in addition* to this patch. And I actually wait for weekly PR reviews promised by you, @nashif (or TSC), to argue that this patch should be merged.

**Comment by pfalcon** [comment]
Interesting, I reopened this PR yesterday... Well, nevermind, resubmitted as https://github.com/zephyrproject-rtos/zephyr/pull/11530

**Pull request closed without merging**
