### PR TITLE
Bluetooth: Host: Avoid adding the same device to resolving list

### LINKED ISSUE #45827: bluetooth: bluetooth host: Adding the same device to resolving list
**Describe the bug**
Core v5.3, Vol 4, Part E, 7.8.38 specifies:
If an entry already exists in the resolving list with the same four parameter
values, the Controller shall either reject the command or not add the device to
the resolving list again and return success. If the command is rejected then the
error code Invalid HCI Command Parameters (0x12) should be used.

Core 5.2 however doesn't mention the option.

This means the Bluetooth host should be able to handle both outcomes from the controller.

If a remote device has been added to RL before, then the local device changes its advertising address, and the remote device tries to pair with the new address, we could end up trying to add the same data to RL.

**Expected behavior**
The host should not issue HCI_LE_Add_Device_To_Resolving_List for devices already on the list. Or it should ignore the error in that case.

**Impact**
Low/negligible. Only the log indicates an error. Everything seems to work fine from user perspective.

**Logs and console output**
[00530287] <wrn> bt_hci_core: opcode 0x2027 status 0x12
[00530288] <err> bt_id: Failed to add IRK to controller -5

### PR DESCRIPTION
**Pull request by ibaz-nordic**
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/45827
If a remote device's public/static address is known, this patch deletes the old entry from RL before adding it.  

Signed-off-by: Azizah Ibrahim <azizah.ibrahim@nordicsemi.no>

### CODE REVIEW

**Review by jori-nordic — APPROVED** [review]
Seems fine to me, if I understand we are changing the behavior from:
- delete the key only if a key already exists for the current conn addr and the req address is different
to 
- delete the key if a key already exists for the current conn addr.

I'd still like to get feedback from you @joerchan (if you have the time) since you were the one introducing these lines and I worry I might be missing something.

**Comment by joerchan** [comment]
@jori-nordic So the comment and commit message is only talking about the RL, but calling `bt_keys_clear` also deletes it from flash.

Other than that you should make sure that `update_keys_check` still works as expected. It's purpose is to make sure that security level is not make weaker.

**Comment by ibaz-nordic** [comment]
> @jori-nordic So the comment and commit message is only talking about the RL, but calling `bt_keys_clear` also deletes it from flash.
> 
> Other than that you should make sure that `update_keys_check` still works as expected. It's purpose is to make sure that security level is not made weaker.

Testing with nrf_desktop looks fine.  Do I need to test this PTS?

**Comment by joerchan** [comment]
> Testing with nrf_desktop looks fine. Do I need to test this with PTS?

Probably those would not take you down the specific code path for this.
You'd want to test pairing with overwrite. I.e do a pairing, and then trigger another pairing that replaces the bond.
A use-case for that would be to elevate the security requirement, in order to go from sec-level 2 to sec-level 3.
Also you'd want to verify that it is not possible to this in order to go from sec-level 3 to sec-level 2, or replace a sec-level 2 with a sec-level 2 (BT_SMP_ALLOW_UNAUTH_OVERWRITE).

You can test this with the shell by setting different types of authentication available. `bt auth` command.

**Review by jhedberg — APPROVED** [review]

**Comment by sjanc** [comment]
FYI:  This breaks re-pairing if legacy pairing is used (in legacy pairing LTK is distributed before IRK and thus LTK gets deleted)

I'll create issue for this once get list of tests that is affected.

**Comment by ibaz-nordic** [comment]
I'll have another look at the patch.  Could you please provide some info on how to run the failing tests?

**Comment by sjanc** [comment]
You can test this with PTS eg GAP/SEC/SEM/BV-58-C

**Comment by ibaz-nordic** [comment]
Reverted with https://github.com/zephyrproject-rtos/zephyr/pull/46505

**Pull request merged**
