### PR TITLE
power: policy: remove deep sleep states from residency policy

### PR DESCRIPTION
**Pull request by pabigot**
Deep sleep states are documented to include SoC-level power gating, i.e. the SoC loses context.  In practice entering a deep sleep state requires an external wakeup mechanism that may need to restart the application.

Such states are too dangerous to enter automatically based on an expected duration of sleep, especially since a "forever" sleep that would normally be woken as a result of a peripheral event would select the deepest sleep state available.  Limit the sleep levels selected by a residency policy to ones in which the CPU may be stopped, but will not lose execution context.

This does not completely resolve concerns identified in #20792, but would allow that issue to be converted to a low priority enhancement.

### CODE REVIEW

**Review by mnkp — DISMISSED** [review]

**Review by erwango — APPROVED** [review]

**Comment by vanti** [comment]
I like this helps to clarify what "deep sleep" means. I have some WIP that implements deep sleep state 1 with a standby mode where most power domains are shut off, except a few that retain just enough logic to allow the CPU to resume from the same point of execution where it went to sleep. I had thought it was acceptable. Given the change in this PR, I would need to rework it as just another sleep state.

One observation is that this change effectively makes it impossible today to suspend devices via the central method in device PM for sleep states that have the ability to resume without a restart, since _sys_suspend() only calls sys_pm_suspend_devices() when the state is deemed a "deep sleep" state:

```
        deep_sleep = IS_ENABLED(CONFIG_SYS_POWER_DEEP_SLEEP_STATES) ?
                     sys_pm_is_deep_sleep_state(pm_state) : 0;

       ...

        if (deep_sleep) {
#if CONFIG_DEVICE_POWER_MANAGEMENT
                /* Suspend peripherals. */
                if (sys_pm_suspend_devices()) {
```

This is where some of the changes in PR #18007 would help, since it introduces sys_pm_clock_gate_devices() to invoke sys_pm_set_devices_power_state() for sleep states. 

Note Zephyr's definition of deep sleep -- where the context is lost to the point where a restart is necessary -- doesn't quite match the one I have seen used in ARM documentation (see [here](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0552a/CHDJJHJI.html) for one such instance). But then again ARM is not the only platform Zephyr supports, so not sure if there is an incentive to match up.

**Comment by dleach02** [comment]
Do we need any additional reviewers to approve this for merge?

**Comment by mnkp** [comment]
> I have some WIP that implements deep sleep state 1 with a standby mode where most power domains are shut off, except a few that retain just enough logic to allow the CPU to resume from the same point of execution where it went to sleep.

Such behavior is currently not taken into account by Zephyr power management subsystem. We have sleep state where neither CPU context nor device configuration is lost or deep sleep state where both CPU context and device configuration are lost. That's according to the documentation. Implementation suggests something else. It looks like we need to clarify SoC/Device power levels.

The one distinctive aspect of power management is CPU losing or not its execution context as this requires very different handling of resume from the power state. Since we have two classes of sleep states it would probably make sense to define deep sleep as a state where CPU is losing context, just as it is the case now, but allow devices to lose their configuration in sleep state.

I'm not sure anymore if the solution proposed in this PR is the proper one. First of all if the device power management is turned off, which is akin to distributed method, only an application is able to make an informed decision which power state the SoC can enter. Having it done automatically, e.g. based on the duration of the idle state, doesn't really makes sense.

So rather than turning off residency policy for deep sleep states I would rather enable by default `SYS_PM_STATE_LOCK` option (or remove this configuration option altogether leaving the code in place) and have all power states upon boot disabled by default (in a sense that calling `sys_pm_ctrl_is_state_enabled` should return false for all defined power states). In this case a power state could be entered only if application explicitly enables it.

Since residency policy doesn't take into account the device power management subsystem the above holds true even if the device power management is enabled. Residency policy is unable to reliably determine which power state to enter since its decision is based exclusively on the duration of the CPU idle state.

**Comment by pabigot** [comment]
@mnkp I don't understand what you're proposing, so please prepare a PR that prevents `k_poll(args, K_FOREVER)` from allowing the residency algorithm to power-off the CPU in the way you wish that done, and we can discuss whether that solution or this one is the best approach.

**Comment by mnkp** [comment]
@pabigot I've created a draft proposal #21118.

**Comment by pabigot** [comment]
@mnkp I've commented on #21118.

I had hoped to get this into 2.1, because the existing behavior for system power management is simply wrong.  I don't see how discussions of device power management, or assessments that an existing policy is not useful, would ever change that, and #21118 is a long way from being a solution.

It would be nice to at least get rid of one real problem.

**Comment by dleach02** [comment]
@mnkp can you approve this PR as a partial step in the direction you are proposing?

**Comment by mnkp** [comment]
> @mnkp can you approve this PR as a partial step in the direction you are proposing?

Yes. Regardless of the concerns I rose we shouldn't enter the deep sleep automatically. It's too drastic an event and should happen under full control of the application.

**Review by mnkp — APPROVED** [review]

**Comment by mnkp** [comment]
> I've commented on #21118.

@pabigot I don't see your comment. Maybe you forgot to submit the review?

**Comment by wentongwu** [comment]
> > I have some WIP that implements deep sleep state 1 with a standby mode where most power domains are shut off, except a few that retain just enough logic to allow the CPU to resume from the same point of execution where it went to sleep.
> 
> Such behavior is currently not taken into account by Zephyr power management subsystem. We have sleep state where neither CPU context nor device configuration is lost or deep sleep state where both CPU context and device configuration are lost. That's according to the documentation. Implementation suggests something else. It looks like we need to clarify SoC/Device power levels.
> 

Actually we have such system enabled based on the current residency policy, if system doesn't support deep sleep, just configure CONFIG_SYS_POWER_DEEP_SLEEP_STATES=n as I mentioned in #20792, I don't think this PR should be merged, at least it broken my system.

**Pull request merged**
