### PR TITLE
Add device tree support for nios2f and nios2-qemu

### PR DESCRIPTION
**Pull request by SavinayDharmappa**

### CODE REVIEW

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
Why are we doing this?
This appears to be taking information in system.h and duplicating it in dts files.
What problem does this solve?

**Comment by SavinayDharmappa** [comment]
@andrewboie  as a part of dts migration of all arch/ we are deriving RAM and ROM address from dts. The idea is to put all hardware information at once place i. e dts. As part of this I have done the changes.

**Comment by andrewboie** [comment]
> The idea is to put all hardware information at once place 

NACK

For Nios II CPU SOC builds, all the hardware information is already in one place: system.h.
For example, the nios2f-zephyr SOC definition, look at:
arch/nios2/soc/nios2f-zephyr/include/system.h
I see no point to copying this stuff to DTS files, we now have the same info in two different places, how does this benefit us?

**Comment by nashif** [comment]
> NACK
> 
> For Nios II CPU SOC builds, all the hardware information is already in one place: system.h.
> For example, the nios2f-zephyr SOC definition, look at:
> arch/nios2/soc/nios2f-zephyr/include/system.h
> I see no point to copying this stuff to DTS files, we now have the same info in two different places, how does this benefit us?

This applies to almost EVERY board/soc in zephyr. look at all the hal files where headers define every aspect of the system, the way the vendor wanted to do that, done in completely different ways. So, there is nothing special about NIOS here.

We need to move all architectures to DTS, otherwise we will not be able to move to the next step of using DTS to replace Kconfig for peripheral configuration. DTS will unify how we define basic data needed to boot and operate any of the platforms we support, this will be the one place, not the vendor provided files.

**Comment by andrewboie** [comment]
> We need to move all architectures to DTS, otherwise we will not be able to move to the next step of using DTS to replace Kconfig for peripheral configuration. DTS will unify how we define basic data needed to boot and operate any of the platforms we support, this will be the one place, not the vendor provided files.

I still do not see what problem we are solving here.
Can you describe a *specific* scenario on Nios II which this change makes simpler?
From my point of view we are duplicating information and fixing something that isn't broken.
A real-world specific example would be extremely helpful.

**Comment by galak** [comment]
The issue isn't NIOS II specific, its about support across Zephyr.  We are trying to utilize the Device Tree to describe HW in an architecture agnostic way, such that we can utilize that info across all the architectures.  So having NIOS II not support DTS means that we have to support 2 ways of doing everything.  For example, how we might specify which I2C controller a sensor is on.  Today we have to support specifying a name in Kconfig & dts.  Once all SoCs across all arch's and drivers use dts, we can remove doing this multiple ways.  It also removes the user from having to get such cfg info correct.

**Review by nashif — DISMISSED** [review]

**Comment by nashif** [comment]
@SavinayDharmappa please test this with all nios2 boards, for example run 'sanitycheck -a nios2'

```
v -o CMakeFiles/lib__libc__newlib.dir/libc-hooks.c.obj   -c /home/nashif/Work/github/zephyr/lib/libc/newlib/libc-hooks.c
In file included from /home/nashif/Work/github/zephyr/include/arch/nios2/arch.h:19:0,
                 from /home/nashif/Work/github/zephyr/include/arch/cpu.h:19,
                 from /home/nashif/Work/github/zephyr/lib/libc/newlib/libc-hooks.c:7:
/home/nashif/Work/github/zephyr/lib/libc/newlib/libc-hooks.c: In function ‘_sbrk’:
/home/nashif/Work/github/zephyr/sanity-out/altera_max10/samples/boards/altera_max10/pio/test/zephyr/include/generated/generate
d_dts_board.h:38:23: error: ‘CONFIG_SRAM_SIZE_0’ undeclared (first use in this function)
 #define _RAM_SIZE    (CONFIG_SRAM_SIZE_0 * 1024)
                       ^
/home/nashif/Work/github/zephyr/lib/libc/newlib/libc-hooks.c:30:24: note: in expansion of macro ‘_RAM_SIZE’
 #define MAX_HEAP_SIZE (_RAM_SIZE - USED_RAM_SIZE)
                        ^~~~~~~~~
/home/nashif/Work/github/zephyr/lib/libc/newlib/libc-hooks.c:162:26: note: in expansion of macro ‘MAX_HEAP_SIZE’
  if ((heap_sz + count) < MAX_HEAP_SIZE) {
                          ^~~~~~~~~~~~~
/home/nashif/Work/github/zephyr/sanity-out/altera_max10/samples/boards/altera_max10/pio/test/zephyr/include/generated/generate
d_dts_board.h:38:23: note: each undeclared identifier is reported only once for each function it appears in
 #define _RAM_SIZE    (CONFIG_SRAM_SIZE_0 * 1024)
                       ^
/home/nashif/Work/github/zephyr/lib/libc/newlib/libc-hooks.c:30:24: note: in expansion of macro ‘_RAM_SIZE’
 #define MAX_HEAP_SIZE (_RAM_SIZE - USED_RAM_SIZE)
                        ^~~~~~~~~
/home/nashif/Work/github/zephyr/lib/libc/newlib/libc-hooks.c:162:26: note: in expansion o

```

**Review by nashif — CHANGES_REQUESTED** [review]
fails on max10

**Comment by nashif** [comment]
recheck

**Review by nashif — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]
I still have some doubts but I'm going to go with the prevailing opinion on this one.

**Pull request merged**
