### PR TITLE
drivers: set LIS2DH default trigger mode to "EDGE_BOTH"

### LINKED ISSUE #71227: drivers: invalid trigger default value for LIS2DH (and LIS3DH etc.)
The default values for `int1-gpio-config` and `int2-gpio-config` are not useable (`GPIO_INT_EDGE`).

The issue was introduced on solving #63736 and is still present in the current `main`-branch.

I suspect `GPIO_INT_EDGE_BOTH` was the indended flag.

**To Reproduce**
- checkout d1591cd363d5cc23929fbd85ddbf79c4b106a377 (`main`-branch)
- build an example using the LIS2DH
- try to activate the trigger with the default value

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK 0.16.5
 - d1591cd363d5cc23929fbd85ddbf79c4b106a377

### PR DESCRIPTION
**Pull request by deveritec-jusc**
Previous value just activated the ability to trigger for both edges, without (de)-activating the gpio. This caused an assrtion error in GPIO.h.

Fixes #71227

### CODE REVIEW

**Comment by deveritec-rosc** [comment]
> Have you tested it solves the #71227? What trigger have you set in that case? Any Motion on int2? (By the way the PR looks good to me, just wanted to get more details. Maybe you can add something here, thx)

Tested it without problems. We are using the `SENSOR_TRIG_DELTA` which is mapped to the "anymotion" trigger on int2 (wasn't aware that there is a special property necessary to use INT1).

One more thing: the PR also changes the dts-macro name from `LIS2DH_DT_GPIO_INT_EDGE` to `LIS2DH_DT_GPIO_INT_EDGE_BOTH`, so it may break code. Is this okay, or should I roll this back?

**Comment by avisconti** [comment]
> > Have you tested it solves the #71227? What trigger have you set in that case? Any Motion on int2? (By the way the PR looks good to me, just wanted to get more details. Maybe you can add something here, thx)
> 
> Tested it without problems. We are using the `SENSOR_TRIG_DELTA` which is mapped to the "anymotion" trigger on int2 (wasn't aware that there is a special property necessary to use INT1).
> 

OK, very good!

> One more thing: the PR also changes the dts-macro name from `LIS2DH_DT_GPIO_INT_EDGE` to `LIS2DH_DT_GPIO_INT_EDGE_BOTH`, so it may break code. Is this okay, or should I roll this back?

No, I will keep this part as you did. I believe this PR is correct and I'm approving it.
Neverthelss, I have this doubt that #63736 could be broken. But in this case we will address it later if the case. To me GPIO_INT_EDGE at 0 is wrong and must be fixed. Thanks.

**Review by avisconti — APPROVED** [review]

**Comment by avisconti** [comment]
Added lso @fabiobaltieri . Would be great Fabio if you could help us in the review and see if we are missing something. Thanks in advance.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@deveritec-rosc what was the error exactly? You say assertion, do you mean build error or something else?

**Comment by deveritec-rosc** [comment]
> @deveritec-rosc what was the error exactly? You say assertion, do you mean build error or runtime error or something else? Unclear from the bug

It was a runtime assertion. The problem was that
```c
	__ASSERT((flags & (GPIO_INT_DISABLE | GPIO_INT_ENABLE)) != 0U,
		 "Must either enable or disable interrupts");
```
was issued if `GPIO_INT_EDGE` was used.

**Comment by fabiobaltieri** [comment]
@deveritec-rosc thanks, yeah that flag was straight wrong, thanks for catching it, for future bugs I'd suggest quoting the exact error log on the issue, helps triaging a bit.

Curious because there's many platforms that do not support both-edge or level interrupts, and we use those on generic drivers so that's something we should keep more in mind I suppose. :-/

**Pull request merged**
