### PR TITLE
[RFC] [DNM] dts: bindings: remove nordic,nrf-uarte from dts/dtsi/overlays/bindings

### PR DESCRIPTION
**Pull request by barsok**
I have a suggestion to remove string: "nordic,nrf-uarte" from compatible and related .yaml file and would like to ask for comments.

The reasons are:
- "nordic,nrf-uarte" is actually never used, it is always overwritten with "nordic,nrf-uart"
- failing to overwrite leads to compilation errors as no code expects  NORDIC_NRF_UART**E**_40002000_BASE_ADDRESS
- uart**e** driver proposed in PR #8640 is created with "compatible = nordic,nrf-uart" defines in mind

Signed-off-by: Bartosz Sokolski <bartosz.sokolski@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
@barsok I have no objections to this as long as the selection of UART vs UARTE in SoCs where both are available can be done easily through some means. What would that be, Kconfig?

**Comment by barsok** [comment]
@carlescufi PR #8640 introduces new settings in Kconfig which let the user select whether they want to use UART or UARTE

**Review by galak — CHANGES_REQUESTED** [review]
Nack.  This shouldn't be handled via Kconfig, it should be handled via DT like it is.

I don't understand what issue you are running into when the compatible is set to "nordic,nrf-uarte"

**Comment by carlescufi** [comment]
@galak I think the issue is that the same hardware can be accessed by 2 different drivers, same register address space. In the UARTE PR (#8640) the selection of the driver is done in Kconfig, not in DT because this is in the gray area of software/hardware.

**Comment by galak** [comment]
> @galak I think the issue is that the same hardware can be accessed by 2 different drivers, same register address space. In the UARTE PR (#8640) the selection of the driver is done in Kconfig, not in DT because this is in the gray area of software/hardware.

At some point we will be able to remove the port selection from Kconfig, and it will just be the driver.  So doing this with DT to start with is the way to go.  Its pretty straight forward to get the UARTE driver to use DT.

**Comment by galak** [comment]
Closing this as the proper way is to fixup #8640 to handle UARTE.

**Comment by galak** [comment]
> At present UART-E is absolutely not handled via device tree. If you fail to switch compatible back to "nordic,nrf-uart", your code will not compile. The "generated_dts...h" will contain labels with "UARTE" and not "UART". Of course one could provide the fixup files, but these fixup files would "merge" defines to single "UART_0_BAUDRATE" etc, and then split again to different drivers. It's completely uncomprehensible.

This is done once in the SOC dts fixup so the user isn't going to 

> UART and UART-E are not compatible and expression in dtsi "compatible = nordic,nrf-uart, nordic,nrf-uarte" is false. For example, they cannot share the driver. They share the same address space, but in silicon they are different devices. For now, they do share the purpose so some settings are the same, like rx-pin, tx-pin, baud rate etc so they can both be handled with one entry.

I agree they aren't the same device and there for not the same compatible.  We can remove the compatible property from the SoC dtsi and force the user / board dtsi to explicitly set it, the idea of "compatible = nordic,nrf-uart, nordic,nrf-uarte" was to convey that it should be one or the other.

> The introduced UART-E driver will take Kconfig approach (please remember: for now)

I don't see why we need to take the Kconfig option.

**Comment by galak** [comment]
Take a look at #8761

**Comment by carlescufi** [comment]
>I don't see why we need to take the Kconfig option.

This is what we cover in #8758

**Comment by galak** [comment]
> This is what we cover in #8758

Fair enough, the Kconfig bit doesn't concern me right now, however we should be using the proper compatible in dt for the device that is actually used, and thus #8761 should hopefully clean all this up.

**Pull request closed without merging**
