### PR TITLE
boards: stm32: Turn hardware stack protection on by default

### PR DESCRIPTION
**Pull request by erwango**
Enable HW stack protection by default on all STM32 when possible.
This excludes all series based on M0(FO) and M0+(G0/L0).
Also this is made only on boards with enabled MPU (SRAM > 64K).

Cf similar change on nRF boards: #28470

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by erwango** [comment]
^^ @carlescufi , @ioannisg , @MaureenHelm

**Review by galak — COMMENTED** [review]
Would it make sense to just default this at the SoC level?

**Comment by erwango** [comment]
> Would it make sense to just default this at the SoC level?

Discussed [here](https://github.com/zephyrproject-rtos/zephyr/pull/28470#issuecomment-694275764) already. @ioannisg is opposed to this. So maybe symbol could be `default y` once enabled on all supporting boards.

**Review by ABOSTM — COMMENTED** [review]
LGTM.
Why not activating HW_STACK_PROTECTION for M0+ board ? (the one for which MPU is supported and enebaled)

**Comment by erwango** [comment]
> LGTM.
> Why not activating HW_STACK_PROTECTION for M0+ board ? (the one for which MPU is supported and enebaled)

HW_STACK_PROTECTION has dependence on !ARMV6_M_ARMV8_M_BASELINE which is selected by `CPU_CORTEX_M0PLUS`. Maybe @ioannisg could provide more insight here.

BTWk, I mised the dependence on `CPU_CORTEX_M_HAS_SPLIM` that make this change compatible with nucleo_l5

**Review by FRASTM — APPROVED** [review]

**Comment by ioannisg** [comment]
> e one for which MPU is supported and enebaled

@ABOSTM the MPU_STAC_GUARD feature is not supported in Baseline Cortex-M. The dependency is there for a reason :)

**Comment by erwango** [comment]
> BTW, I missed the dependence on `CPU_CORTEX_M_HAS_SPLIM` that make this change compatible with nucleo_l5

This was actually fine

**Comment by ABOSTM** [comment]
> The dependency is there for a reason :)

Yes probably, but I still don't know the reason :-)
Is there something missing in Cortex-M0+ with MPU that prevent to use HW_STACK_PROTECTION?
From hardware point of view, MPU is not sufficient ?

**Comment by ioannisg** [comment]
> > The dependency is there for a reason :)
> 
> Yes probably, but I still don't know the reason :-)
> Is there something missing in Cortex-M0+ with MPU that prevent to use HW_STACK_PROTECTION?
> From hardware point of view, MPU is not sufficient ?

Good question. So in Cortex-M0+ the minimum MPU region size appears to be 256 bytes; I am not sure (on top of my head) if this is implementation-specific of generic to ARMv6-M. Now, 256 B is a lot of space to waste for a guard, for each thread, in SoCs like Cortex-M0+, with, normally, not so much ram available. 

To support the feature we only need some rework of the ARCH macros that define the minimum guard size. Doable.

**Comment by ABOSTM** [comment]
> Good question. So in Cortex-M0+ the minimum MPU region size appears to be 256 bytes; I am not sure (on top of my head) if this is implementation-specific of generic to ARMv6-M. Now, 256 B is a lot of space to waste for a guard, for each thread, in SoCs like Cortex-M0+, with, normally, not so much ram available.
> 
> To support the feature we only need some rework of the ARCH macros that define the minimum guard size. Doable.

OK thanks

**Comment by erwango** [comment]
Failures in BK:
INFO    -  69/391 96b_argonkey              samples/sensor/lsm6dsl/sample.sensor.lsm6dsl       FAILED Build failure (build)
INFO    - 114/391 96b_argonkey              samples/boards/96b_argonkey/sensors/sample.board.96b_argonkey.sensors FAILED Build failure (build)

Reported here: https://github.com/zephyrproject-rtos/zephyr/issues/28565

**Comment by erwango** [comment]
@galak @ioannisg Is that ok if I remove the BK temp commit now ?

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
> @galak @ioannisg Is that ok if I remove the BK temp commit now ?

Yes

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by galak** [comment]
Merge as this already passed CI.

**Pull request merged**
