### PR TITLE
tests: drivers: counter: counter_basic_api

### PR DESCRIPTION
**Pull request by RichardSWheatley**
Enable reliable_cancel_capable feature for Ambiq counter

Signed-off-by: Richard Wheatley <richard.wheatley@ambiq.com>

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]
LGTM - although, this looks like it could be solved using devictree in a cleaner way.

**Comment by RichardSWheatley** [comment]
@cfriedt what is your suggestion? If there is a cleaner way, I will change it.

**Comment by cfriedt** [comment]
> @cfriedt what is your suggestion? If there is a cleaner way, I will change it.
> I am simply using the exact same way others have done.

Exactly - the cleaner way would be much more involved. It would require adding a new devictree binding and dt chosen node for this test.

Technically, that could potentially be done tree-wide, but that would probably be better to propose first as an rfc.

**Comment by RichardSWheatley** [comment]
> > @cfriedt what is your suggestion? If there is a cleaner way, I will change it.
> > I am simply using the exact same way others have done.
> 
> Exactly - the cleaner way would be much more involved. It would require adding a new devictree binding and dt chosen node for this test.
> 
> Technically, that could potentially be done tree-wide, but that would probably be better to propose first as an rfc.

I see what you mean and I agree.
I do not like in-sample/in-test configs.

Once my other development is done, I would like to revisit this topic.

Thanks for commenting, I will make a note of your suggestion for RFC.

**Review by nordic-krch — APPROVED** [review]

**Pull request merged**
