### PR TITLE
hwmv2: Added Board Support for Starfive VisionFive2 RISC-V Single Board Computer

### PR DESCRIPTION
**Pull request by pfarwsi**
These list of patches contain Board support files for running Zephyr on the Starfive VisionFive2 RISC-V Single Board Computer based on JH7110 SOC. It's a basic support, no drivers other than UART have been tested.

### CODE REVIEW

**Comment by pfarwsi** [comment]
@carlescufi We do not see any merge conflict at the patches from our end causing the 4 pipelines to fail. Why do they still fail when you do a force push? Can you please point out or suggest if these are failing due to us? We are out of clue here.

**Comment by fkokosinski** [comment]
Hey @pfarwsi, now that the `collab-hwm` branch has been merged into the `main` branch, I suppose you could retarget your changes to the `main` branch.

**Comment by pfarwsi** [comment]
@fkokosinski Retargeted to main branch.

**Comment by fkokosinski** [comment]
@pfarwsi thanks! It looks like your branch is out of date. Could you rebase it? Thanks

**Comment by pfarwsi** [comment]
@fkokosinski Rebased the collab-hwm branch with upstream and pointing to main branch now. We are upto-date with the collab-hwm.

**Comment by pfarwsi** [comment]
@fkokosinski Any update on this PR?

**Comment by kanakshilledar** [comment]
@nordicjm Due to this PR having a lot of changes which is not rebased. We have created another PR #69808  which only has our commits.

**Pull request closed without merging**
