### PR TITLE
Bluetooth: controller: Use inline wrapper function

### PR DESCRIPTION
**Pull request by DhruvaG2000**
This commit aims to solve https://github.com/zephyrproject-rtos/zephyr/issues/28959

Signed-off-by: Dhruva Gole <goledhruva@gmail.com>

### CODE REVIEW

**Review by cvinayak — CHANGES_REQUESTED** [review]
The changes here does match the commit title.

The goal is to use wrapper functions like below:
```
static inline void foo_check_and_do(bool flag)
{
    if (flag) {
        foo();
    }
}
```

Please refer to https://github.com/zephyrproject-rtos/zephyr/pull/28932#issuecomment-704074630

**Comment by DhruvaG2000** [comment]
> The changes here does match the commit title.
> 
> The goal is to use wrapper functions like below:
> 
> ```
> static inline void foo_check_and_do(bool flag)
> {
>     if (flag) {
>         foo();
>     }
> }
> ```
> 
> Please refer to [#28932 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/28932#issuecomment-704074630)

oh okayy so if I understand correctly, as described in the comment

```
static inline void peripheral_latency_cancel(struct ll_conn *conn, uint16_t handle)
{
    if (conn->lll.role) {
        peripheral_latency_cancel_(conn, handle);
    }
}
```

in my case it will look something like 
```C
// implement the func first in the `slave.c` file 
static int enc_rsp_send(struct ll_conn *conn)
{
...
}

static inline void ull_slave_enc_rsp_send(struct ll_conn *conn)
{
if (conn->lll.role)
 {
      enc_rsp_send(conn);
 }

}
```

something like this?

**Comment by cvinayak** [comment]
> 
> in my case it will look something like
> 
> ```c
> // implement the func first in the `slave.c` file 
> static int enc_rsp_send(struct ll_conn *conn)
> {
> ...
> }
> 
> static inline void ull_slave_enc_rsp_send(struct ll_conn *conn)
> {
> if (conn->lll.role)
>  {
>       enc_rsp_send(conn);
>  }
> 
> }
> ```
> 
> something like this?

No, please address the issue at hand, to only refactor existing `if` constructs, do not move or rewrite implementation (see CI failure for details).

**Comment by DhruvaG2000** [comment]
> No, please address the issue at hand, to only refactor existing `if` constructs, do not move or rewrite implementation (see CI failure for details).

I do understand why the CI fails, it's cuz I have baically copy pasted the function from one code to anoher without paying attention to the scope of variables that were used and stuff. (So let's forget about my code in this PR for a moment)

I understand that what I have done rn is wrong, but I do now yet understand what the comment that you are pointing to exactly achieves?
```c
static inline void peripheral_latency_cancel(struct ll_conn *conn, uint16_t handle)
{
    if (conn->lll.role) {
        peripheral_latency_cancel_(conn, handle);
    }
}
```

what I can infer from this is that it's just a recursive function, then how is it helping exactly?

Rather the code that you mentioned [here](https://github.com/zephyrproject-rtos/zephyr/pull/38647#pullrequestreview-758706955) makes more sense to me as a wrapper function, so it would basically be something like 

```C
static inline void check_and_do_enc_rsp_send(bool flag)
{
    if (flag ) { // flag can be set in just one place in the code under #if defined(CONFIG_BT_PERIPHERAL)

        enc_rsp_send();
    }
}
```

**Comment by carlescufi** [comment]
@cvinayak could you reply to the comment above?

**Comment by DhruvaG2000** [comment]
I am not sure what exactly is to be done here. Closing for now.

**Pull request closed without merging**
