### PR TITLE
Bluetooth: fix C++ compile error

### PR DESCRIPTION
**Pull request by rhssk**

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
Fix the compliance failure by adding a body to the commit message, something like:

> C++ disallows implicit cast to enum values.

**Review by joerchan — APPROVED** [review]

**Comment by jhedberg** [comment]
Wouldn't it make more sense to use a packed enum (i.e. compress the enum to minimum size, in this case one octet) instead of `uint8_t` in `struct bt_buf_data`? That was there's no typecast needed at all.

**Comment by jhedberg** [comment]
If you need a reference for my packed enum suggestion, take a look at e.g. `bt_conn_state_t` in `subsys/bluetooth/host/conn_internal.h` and how it's placed into `struct bt_conn`. It only takes up space of one octet there.

**Review by pabigot — APPROVED** [review]
I think this is fine as-is, it fixes the visible problem.  Changing the type of the referenced field could also be appropriate but is more invasive and IMO should be done by the BT maintainers.

**Pull request merged**
