### PR TITLE
fs/nvs: fix NVS of 2-sectors configuration

### PR DESCRIPTION
**Pull request by nvlsianpu**
merge after: #16255

This patch fixes following bug:

After first GC operation the 1st sector had become scratch
and the 2nd sector had became write sector. After that NVS
was initialize (via reboot) again - it recognized the 1st
sector as write sector and 2nd as undone GC destination sector,
therefore it cleared 2nd sector and  re-run GC, which implied data loss.

### CODE REVIEW

**Comment by nvlsianpu** [comment]
cc @kapi-no

**Comment by Laczen** [comment]
Why such a difficult fix? Did I overlook something in the code change proposed in #16211 ? The idea in the code is simple: a closed sector followed by a non closed defines the start as being the non closed. If however you cannot find a closed sector while going through all sectors the start is the first sector, except in the special case of only 2 sectors where you will never find a closed sector. This latter case can be handled gracefully inside the for loop. Any error like a non-finished gc will be handled by code later on.

In fact the original nvs_addr_advance() at the end of the for loop was only active for the last sector, as in all other cases it was reset by the addr = ... at the start of the for loop.

In the code you also refer to a scratch sector, nvs has no such thing.

**Review by kapi-no — APPROVED** [review]
LGTM

**Comment by nvlsianpu** [comment]
Yes, you overlooked case when a sector was closed and GC was interrupted.
I think the  scratch is very common term, but yes will change it to follow NVS terminology.

**Comment by Laczen** [comment]
This was not overlooked, if a sector was closed it would never have reached the comparison at the end of the for loop..

**Comment by kapi-no** [comment]
That is true, but the flash_erase at the end of nvs_startup function would wipe the valid data.

**Comment by Laczen** [comment]
Would it ? I don't think so, it would erase the current writing sector (not the closed sector) and restart the gc.

**Comment by nvlsianpu** [comment]
> That is true, but the flash_erase at the end of nvs_startup function would wipe the valid data.

That is true.

I written this patch that way because of better legibility, this makes maintenance easier.

**Comment by kapi-no** [comment]
@Laczen, well, you are right, it would not. However, I still prefer the @nvlsianpu solution, because it has more explicit logic and that makes code easier to analyze.

**Comment by Laczen** [comment]
So again, why this complex change ? Making the logic more explicit seems like a bad reason.

There was a bug inside nvs_startup code that only appeared when 2 sectors are used. The code presumed that if there where no closed sectors the first sector should be used as writing sector, this is wrong in the case of two sectors. So let's just add a check where we now this is the case, it will even speed up the code and avoid any unnecessary addr_advance. The proposed for loop at startup becomes:

```
	for (u16_t i = 0; i < fs->sector_count; i++) {
		addr = (i << ADDR_SECT_SHIFT) + fs->sector_size - ate_size;
		rc = nvs_flash_cmp_const(fs, addr, 0xff,
					  sizeof(struct nvs_ate));
		if (rc) {
			/* closed sector */
			nvs_sector_advance(fs, &addr);
			rc = nvs_flash_cmp_const(fs, addr, 0xff,
						  sizeof(struct nvs_ate));
			if (!rc) {
				/* open sector */
				break;
			}
		}
                if (i == (fs->sector_count - 1)) {
			/* none of the sectors where closed, in most cases we can set
		 	 * the address to the first sector, except when there are only
		 	 * two sectors. Then we can only set it to the first sector if
		 	 * the last sector contains no ate's. So we check this first 
		 	 */
			rc = nvs_flash_cmp_const(fs, addr - ate_size, 0xff,
					  sizeof(struct nvs_ate));
			if (rc) {
				/* we found data */
				break;
			}
			nvs_sector_advance(fs, &addr);
		}
	}
```

At the end of this loop the addr is pointing to the correct sector. The aim of this routine is to set the correct start address not to search for a closed sector followed by a open sector.

**Comment by nvlsianpu** [comment]
I'm considering your proposal.

**Comment by nvlsianpu** [comment]
What about:

```
	u16_t i;

	k_mutex_lock(&fs->nvs_lock, K_FOREVER);

	ate_size = nvs_al_size(fs, sizeof(struct nvs_ate));
	/* step through the sectors to find the last sector */
	for (i = 0; i < fs->sector_count; i++) {
		addr = (i << ADDR_SECT_SHIFT) + fs->sector_size - ate_size;
		rc = nvs_flash_cmp_const(fs, addr, 0xff,
					  sizeof(struct nvs_ate));
		if (rc) {
			/* closed sector */
			nvs_sector_advance(fs, &addr);
			rc = nvs_flash_cmp_const(fs, addr, 0xff,
						  sizeof(struct nvs_ate));
			if (!rc) {
				/* open sector */
				close_open_found = true;
				break;
			}
		}
	}

	if (i == fs->sector_count) {
		/* none of the sectors where closed, in most cases we can set
	 	 * the address to the first sector, except when there are only
	 	 * two sectors. Then we can only set it to the first sector if
	 	 * the last sector contains no ate's. So we check this first 
	 	 */
		rc = nvs_flash_cmp_const(fs, addr - ate_size, 0xff,
				  sizeof(struct nvs_ate));
		if (!rc) {
			/* we not found any data */
			nvs_sector_advance(fs, &addr);
		}
	}
```

**Comment by Laczen** [comment]
> What about:
> 
> ```
> 	u16_t i;
> 
> 	k_mutex_lock(&fs->nvs_lock, K_FOREVER);
> 
> 	ate_size = nvs_al_size(fs, sizeof(struct nvs_ate));
> 	/* step through the sectors to find the last sector */
> 	for (i = 0; i < fs->sector_count; i++) {
> 		addr = (i << ADDR_SECT_SHIFT) + fs->sector_size - ate_size;
> 		rc = nvs_flash_cmp_const(fs, addr, 0xff,
> 					  sizeof(struct nvs_ate));
> 		if (rc) {
> 			/* closed sector */
> 			nvs_sector_advance(fs, &addr);
> 			rc = nvs_flash_cmp_const(fs, addr, 0xff,
> 						  sizeof(struct nvs_ate));
> 			if (!rc) {
> 				/* open sector */
> 				close_open_found = true;
> 				break;
> 			}
> 		}
> 	}
> 
> 	if (i == fs->sector_count) {
> 		/* none of the sectors where closed, in most cases we can set
> 	 	 * the address to the first sector, except when there are only
> 	 	 * two sectors. Then we can only set it to the first sector if
> 	 	 * the last sector contains no ate's. So we check this first 
> 	 	 */
> 		rc = nvs_flash_cmp_const(fs, addr - ate_size, 0xff,
> 				  sizeof(struct nvs_ate));
> 		if (!rc) {
> 			/* we not found any data */
> 			nvs_sector_advance(fs, &addr);
> 		}
> 	}
> ```

Yes, this would work as well, no need to keep track of close_open_found. And change `/* we not found any data */` to `/* empty ate */`.

**Comment by nvlsianpu** [comment]
@carlescufi @Laczen Analyzed your proposal - you have been right from the beginning.
The patch is reworked, please review in your convenience.

**Review by Laczen — APPROVED** [review]

**Review by rakons — APPROVED** [review]

**Comment by nvlsianpu** [comment]
Fix commit can be backported to 1.14.

**Pull request merged**
