### PR TITLE
Gsm ppp setup hooks

### PR DESCRIPTION
**Pull request by tautologyclub**
This actually works fine but is not quite ready to leave the WIP stage before some more input. It's based on an unmerged PR (https://github.com/zephyrproject-rtos/zephyr/pull/38596) for convenience only. Some background to why this is an important patch:  

We're currently using U-Blox SARA R4 modems for multiple projects, and recently I've been using both Simcom and Quectel modems for projects. We're using Zephyr gsm_ppp for all of them. They've all had some minor or major quirks that required patching the gsm_ppp driver. For the Ublox modem, we've had to patch in support for a ton of required AT commands. The Simcom modem had a bunch of quirks that needed to be worked around using AT. I'm sure we're not the only ones.

I've tried porting our Ublox patches to use my proposed hook system instead and it works fine. Which basically means that this should cover almost all conceivable use cases :D 

A snippet of typical usage follows:

```
// file: gsm_ppp_ublox_sara_r4.c
...

int gsm_ppp_setup_hook(struct modem_context *ctx, struct k_sem *sem)
{
	int ret;

       /* Set the profile */
       ret = modem_cmd_send_nolock(&ctx->iface,
				   &ctx->cmd_handler,
				   NULL, 0,
				   "AT+UMNOPROF=" STRINGIFY(CONFIG_MODEM_GSM_MNOPROF),
				   sem,
				   K_SECONDS(2));
        if (ret < 0) return ret;

	ret = gsm_setup_psm(ctx, sem);
	if (ret < 0) {
		LOG_WRN("gsm_setup_psm returned %d", ret);
		return ret;
	}

	ret = gsm_setup_urat(ctx, sem);
	if (ret < 0) {
		LOG_WRN("gsm_setup_urat returned %d", ret);
		return ret;
	}

	ret = gsm_setup_ubandmask(ctx, sem);
	if (ret < 0) {
		LOG_WRN("gsm_setup_ubandmask returned %d", ret);
		return ret;
	}

	return ret;
}
```

This file gets compiled as part of my application, but of course it's 100% conceivable to upstream special modem setups as well. 

My main gripe with it is the need to use internal APIs (modem_context and modem_cmd_handler). But because these hooks are used for extending a driver, not for application logic, maybe it's not a huge deal.

### CODE REVIEW

**Comment by tautologyclub** [comment]
@jukkar @ycsin @bbilas @weinholtendian @rlubos

**Comment by ycsin** [comment]
I can see that this is useful for a lot of scenarios, but we had #38946 merged and [it used callback instead of weak linked functions](https://github.com/zephyrproject-rtos/zephyr/pull/38946#issuecomment-930132947), although I'm not sure if the `gsm_ppp` driver would ever support multiple modems, wouldn't this PR go against that PR?

Also, I'm not sure if the hooks introduced in this PR would be enough for everyone, would it be feasible to have a pre and post hook for each state of the modem?

**Comment by tautologyclub** [comment]
> I can see that this is useful for a lot of scenarios, but we had #38946 merged and [it used callback instead of weak linked functions](https://github.com/zephyrproject-rtos/zephyr/pull/38946#issuecomment-930132947), although I'm not sure if the `gsm_ppp` driver would ever support multiple modems, wouldn't this PR go against that PR?

I like weak linkage because there's so little design involved. With callbacks the user has to implement some kind of `gsm_callbacks_init` function with a `SYS_INIT` macro and they have to consider the init priority so that their init is always called before gsm ppp gets inited etc.

But I realize weak linkage is sort of controversial, so I don't have a strong opinion. Callbacks would be fine by me. Would very much like to hear what @jukkar and other maintainers think.

> Also, I'm not sure if the hooks introduced in this PR would be enough for everyone, would it be feasible to have a pre and post hook for each state of the modem?

Exposing all internal state is bad because everything we expose implicitly gets transformed into a public API instantly. Which means ANY changes to the driver will be difficult because we have to keep in mind all possible use cases of our (now public) API. Being extremely mindful of stuff like this is how Linux got where it is today. We should 100% learn from that.

Before considering extending this, I'd like to see some use cases for which this is NOT sufficient.

**Comment by jukkar** [comment]
> But I realize weak linkage is sort of controversial, so I don't have a strong opinion. Callbacks would be fine by me.

I am not big fan of weak linkage style, and we are not using it much in zephyr anyway. It also prevents to have multiple instance of the driver (although this is probably not a big concern atm).

**Comment by tautologyclub** [comment]
@jukkar You would approve if it was callback-based tho?

**Comment by jukkar** [comment]
> You would approve if it was callback-based tho?

Yes, I would prefer cb based solution :+1:

**Comment by slide333333** [comment]
Any update on this one? What can we do to get this one merged?

**Comment by tautologyclub** [comment]
The reason I forgot about this was the general state of disarray in gsm_ppp at the time, with a bunch of floating PRs and conflicting ideas on how the driver should develop. Maybe things has calmed down now though, so I'll try to look into reviving this.

**Comment by tautologyclub** [comment]
Opened a new PR: https://github.com/zephyrproject-rtos/zephyr/pull/52110

This PR was based on v2.7 (I think). The old PR was well-tested. The new one isn't, but feel free to test and/or give comments.

**Pull request closed without merging**
