### PR TITLE
xtensa: add sample_controller32 SoC and qemu_xtensa/sample_controller32/mpu board

### PR DESCRIPTION
**Pull request by dcpleung**
This adds the SoC and board files to support testing Xtensa MPU via QEMU.

Depends on:
* QEMU changes: https://github.com/zephyrproject-rtos/qemu/pull/8
* Toolchain: https://github.com/zephyrproject-rtos/sdk-ng/pull/748
* HAL: https://github.com/zephyrproject-rtos/hal_xtensa/pull/28

### CODE REVIEW

**Review by cfriedt — COMMENTED** [review]
LGTM - just some cache API testsuite failing

**Comment by dcpleung** [comment]
The cache failure is due to https://github.com/zephyrproject-rtos/zephyr/issues/72775 which is on the board `apollo4p_blue_kxr_evb` and unrelated to this.

**Review by nashif — DISMISSED** [review]

**Review by andyross — DISMISSED** [review]
Nice

**Review by teburd — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by dcpleung** [comment]
Rebased due to HAL SHA has been updated in main.

**Review by ceolin — APPROVED** [review]
awesome

**Review by andyross — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Pull request merged**
