### PR TITLE
cmake: Removed KBuild

### PR DESCRIPTION
**Pull request by SebastianBoe**
This commit removes KBuild, see the migration PR for details

This script was used to remove kbuild:

find . -name Makefile       -exec git rm {} \;
find . -name Makefile.board -exec git rm {} \;
find . -name "Makefile.*"   -exec git rm {} \;
find . -name Kbuild         -exec git rm {} \;

git rm \
   scripts/basic/fixdep.c \
   scripts/Kbuild.include \
   scripts/mkmakefile

git reset HEAD doc/Makefile
git checkout doc/Makefile

Signed-off-by: Sebastian Boe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by nashif** [comment]
samples/application_development/external_lib/mylib/Makefile should not be removed AFAIK

**Comment by SebastianBoe** [comment]
> samples/application_development/external_lib/mylib/Makefile should not be removed AFAIK

Good catch. You are correct.

**Comment by nashif** [comment]
and CI would probably fail because of the htmldoc goal in the top-level Makefile. So either keep a Makefile in top level with just this target and support 'help' later with general help re cmake, or change CI to build documentation from doc/

**Comment by SebastianBoe** [comment]
> change CI to build documentation from doc/
Done. Waiting for CI to test.

**Review by nashif — APPROVED** [review]

**Pull request merged**
