### PR TITLE
libc: malloc: implement malloc in terms of realloc

### PR DESCRIPTION
**Pull request by cfriedt**
A call to `malloc(size)` is equivalent to a call to `realloc(NULL, size)` for all values of `size`.

### CODE REVIEW

**Comment by cfriedt** [comment]
Coding guidelines failure is a false positive

**Comment by andyross** [comment]
I think this is likely to increase generated code size, when the intent is the opposite.  The reason is that (1) realloc and alloc are in fact two different chunks of code implementing different algorithms over the same tool set and (2) realloc of a NULL pointer is implemented by recursively calling alloc (unsurprisingly).

So before, code that called malloc() and never realloc() (the common case) would include only the alloc implementation.  Now it needs both.

**Comment by cfriedt** [comment]
> I think this is likely to increase generated code size, when the intent is the opposite. The reason is that (1) realloc and alloc are in fact two different chunks of code implementing different algorithms over the same tool set and (2) realloc of a NULL pointer is implemented by recursively calling alloc (unsurprisingly).

The intent was just to reduce the number of LoC, but yeah, code size is of concern.

> So before, code that called malloc() and never realloc() (the common case) would include only the alloc implementation. Now it needs both.

I can't recall exactly why `sys_heap_aligned_alloc()` isn't just a wrapper around `sys_heap_aligned_realloc()` as well. 

If that were the case, there would really just be one implementation and code space would not really be increased by a significant factor.

**Comment by npitre** [comment]
This depends what is more important: optimizing for code lines reduction
or final binary size reduction. Both is best but if we have to choose
I think that binary size reduction is more important for a project like Zephyr.

Given that most applications have no use for realloc, having a simpler
alloc direct path allows for garbage-collecting the bigger realloc code
at link time. There is even a shortcut in the code to make the allocation
faster when the alignment parameter is not relevant. Funneling everything
through the realloc path would discard those advantages.

**Comment by andyross** [comment]
> I can't recall exactly why sys_heap_aligned_alloc() isn't just a wrapper around sys_heap_aligned_realloc() as well.

For exactly the same reason. :)

The problem of "is there a way to adjust the heap such that the data can be expanded or shrunk in place" is a different algorithm than "find me a free block anywhere in the heap", and requires different code to implement.  And as realloc() is the less common utility, it would be good if code that didn't need it didn't pay the overhead.

**Comment by cfriedt** [comment]
> > I can't recall exactly why sys_heap_aligned_alloc() isn't just a wrapper around sys_heap_aligned_realloc() as well.
> 
> For exactly the same reason. :)
> 
> The problem of "is there a way to adjust the heap such that the data can be expanded or shrunk in place" is a different algorithm than "find me a free block anywhere in the heap", and requires different code to implement. And as realloc() is the less common utility, it would be good if code that didn't need it didn't pay the overhead.

True - I'm always thinking in the back of my mind "what is easier to maintain" vs "what is optimal for Z" (Z being size or speed). Will close, because I think the general consensus is to optimize for size.

**Pull request closed without merging**
