### PR TITLE
net: ip: net_mgmt: Support system work queue and synchronous callbacks

### PR DESCRIPTION
**Pull request by pdgendt**
Add Kconfig choice for the user to select how Network Events are handled. It's own thread, the system work queue or synchronous when events are emitted.

By default a separate thread is created to be backwards compatible.

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
Looks reasonable.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
LGTM.

Just pondering aloud here about the separate thread. Should we make the system workq the default, would there be any backward compatible issues with it? Other than the relevant config options not needed and perhaps causing warnings.
No need to change anything in this version, we can tweak it later if needed.

**Comment by rlubos** [comment]
> Just pondering aloud here about the separate thread. Should we make the system workq the default, would there be any backward compatible issues with it?

I'd be cautious with that, net mgmt handlers are often potentially blocking (they use mutexes) so using system work queue may affect the whole system negatively. There are probably cases when memory savings are more important, but I'm not sure if it should be the default choice.

**Comment by jukkar** [comment]
> net mgmt handlers are often potentially blocking

Indeed, that is a good point.

**Comment by pdgendt** [comment]
> I'd be cautious with that, net mgmt handlers are often potentially blocking (they use mutexes) so using system work queue may affect the whole system negatively. There are probably cases when memory savings are more important, but I'm not sure if it should be the default choice.

@rlubos Should I be worried about usage in other subsystems that things might break?

**Comment by pdgendt** [comment]
I see locking in the following callbacks:
```
zephyr/subsys/net/conn_mgr/events_handler.c
    conn_mgr_iface_events_handler
    conn_mgr_ipv6_events_handler
    conn_mgr_ipv4_events_handler

zephyr/subsys/net/ip/dhcpv4.c
    dhcpv4_iface_event_handler

zephyr/subsys/net/ip/dhcpv6.c
    dhcpv6_iface_event_handler
```

**Comment by rlubos** [comment]
> @rlubos Should I be worried about usage in other subsystems that things might break?

Not necessarily break, just introduce potential delays in system-wide use work queue. I didn't analyze each mgmt handler in detail to know if more serious consequences are possible (like potential deadlock).

> I see locking in the following callbacks:

I think there's more than just that. OpenThread will also lock it's mutex, just not directly in the mgmt handler, but in subroutines. Plus there are many other scenarios, that could potentially lead to block, like calling a function from some subsystem, that can itself be mutex protected, or I'm seeing that  updatehub for example can do transfer directly from the callback, so there's another potential delay from pkt/buffer allocation.

**Comment by cfriedt** [comment]
Nice 👍

**Pull request merged**
