### PR TITLE
Settings: Fix incorrect return of -EINVAL for deleted entries

### LINKED ISSUE #17415: Settings Module - settings_line_val_read() returning -EINVAL instead of 0 for deleted setting entries
When using the Settings module we found that when we delete a settings entry, upon reset and settings load, it was being reloaded with the previous value prior to the deleted entry. 

Upon investigation I found that the reason for this was that the settings_line_val_read() function was returning -EINVAL when it read the deleted (NULL) entry, rather than a settings size of 0, so our code was not loading the NULL entry but retaining the previous version of the setting.

I have made a suggested change (see attached image for code before & after the fix) to that function and it seems to fix the problem here. Could you please see if this is a fix that should be made?

Regards,
Declan Traill

Zephyr1_14_Settings_Suggested_Change

### PR DESCRIPTION
**Pull request by DeclanTraill**
Fixes #17415
For settings_line_val_read function with following .conf setting:
CONFIG_SETTINGS_USE_BASE64=y

Signed-off-by: Declan Traill <declan.traill@setec.com.au>

### CODE REVIEW

**Comment by DeclanTraill** [comment]
If approved, this fix should also be applied to 1.14.1 branch of Zephyr.

**Comment by ioannisg** [comment]
@DeclanTraill thanks for the bug-fix PR.

As I see, the PR targets master branch, not the 1.14 (LTS) branch. So, now, I am wondering: is #17415 a bug for master, too? 
- If yes, please, change the description of #17415, to indicate that this is a bug in both master and 1.14 branches.
- If no, then submit this PR against the 1.14 branch.

**Comment by DeclanTraill** [comment]
@ioannisg Ok, done...

**Comment by nvlsianpu** [comment]
@DeclanTraill Thanks for the fix. I have fixing scheduled on my side - but it is great that you made the patch.
Can you provide another commit with test case which reproduces the issue, so will be visible that the patch works well on the 1st sight?

**Comment by DeclanTraill** [comment]
Hi Andrej,
 
    I have created a new test case file and made changes to support it (attached).
I haven’t actually tested it, but it should do the trick.
 
Regards,
Declan

**Comment by DeclanTraill** [comment]
Correction….    One of the files I sent you hadn’t been saved before I copied it into the email.
 
Here (attached) is the correct version…
 
Regards,
Declan

**Comment by nvlsianpu** [comment]
@DeclanTraill You cant update PR via email. This need to be done via `git`.

**Review by nwsetec — APPROVED** [review]

**Review by nwsetec — COMMENTED** [review]
LGTM

**Comment by kqian0327** [comment]
mute the thread.





--

Kun Qian
 
Email:qiankun0327@126.com
 
TEL: 15827638917
 

At 2019-08-20 06:35:39, "Nick Ward" <notifications@github.com> wrote:


@nwsetec commented on this pull request.

LGTM

**Comment by nvlsianpu** [comment]
Here test for exercise the issue https://github.com/zephyrproject-rtos/zephyr/pull/18518

This PR fixes it correctly.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
Test applied here for showing the fix.

**Comment by nvlsianpu** [comment]
@carlescufi PR fixes the issue (see #18518 which reproduced the bug).
Pleas merge.

**Review by carlescufi — APPROVED** [review]

**Comment by nwsetec** [comment]
@carlescufi @nvlsianpu this PR has the backport label but was never added to the 1.14.1 milestone.  This is PR should also be applied to 1.14.1

**Comment by carlescufi** [comment]
@nvlsianpu can you please send a PR against v1.14-branch?

**Comment by nvlsianpu** [comment]
@carlescufi @nwsetec Yes, will do.

**Pull request merged**
