### PR TITLE
[RFC] net: ethernet: Set dest MAC address for IPv4 mcast

### LINKED ISSUE #1544: regression: net: K64F: DHCP seems to fail a lot after 91041f9e
It's not 100% but most of the time, DHCP seems to fail on master branch using K64F.

I'm testing a revert on 91041f9e7363e5ccd984dfef7adbe9bd4b84b572 to see if that restores normal behavior.

### PR DESCRIPTION
**Pull request by jukkar**

### CODE REVIEW

**Comment by mike-scott** [comment]
Testing this today.  Thank you @jukkar

**Comment by mike-scott** [comment]
@jukkar I tested this and it doesn't fix the issue in our CI lab.  I notice that this does not fully revert the original commit.  I'm testing a full revert of the commit in our CI lab to make sure that it does indeed fix us.

**Comment by mike-scott** [comment]
@jukkar I confirmed again that performing a full revert of 91041f9 fixes our CI testing.

**Comment by mike-scott** [comment]
So the issue is more to do with the change to net_pkt_ll_dst(pkt)->addr = (u8_t *)dst->addr;

**Comment by mike-scott** [comment]
I added some BEFORE/AFTER logging to the original commit where it's changing net_pkt_ll_dst(pkt)->addr and saw the following:
***** BOOTING ZEPHYR OS v1.9.0 - BUILD: Sep 20 2017 12:18:27 *****
shell> [net/dhcpv4] [ERR] net_dhcpv4_start: IFACE MAC:00:04:9F:0D:27:8A
[dev/eth_mcux] [INF] eth_mcux_phy_event: Enabled 100M full-duplex mode.
[net/ethernet] [ERR] ethernet_send: >>> BEFORE: FF:FF:FF:FF:FF:FF
[net/ethernet] [ERR] ethernet_send: >>> AFTER: 9C:B6:D0:19:FA:6D
[net/ethernet] [ERR] ethernet_send: >>> BEFORE: FF:FF:FF:FF:FF:FF
[net/ethernet] [ERR] ethernet_send: >>> AFTER: 9C:B6:D0:19:FA:6D
[net/ethernet] [ERR] ethernet_send: >>> BEFORE: FF:FF:FF:FF:FF:FF
[net/ethernet] [ERR] ethernet_send: >>> AFTER: 9C:B6:D0:19:FA:6D
[net/ethernet] [ERR] ethernet_send: >>> BEFORE: FF:FF:FF:FF:FF:FF
[net/ethernet] [ERR] ethernet_send: >>> AFTER: 9C:B6:D0:19:FA:6D

[FAILED TO GET DHCP]

**Comment by mike-scott** [comment]
After leaving the device on for another 30 or so seconds:
[net/ethernet] [ERR] ethernet_send: >>> BEFORE: FF:FF:FF:FF:FF:FF
[net/ethernet] [ERR] ethernet_send: >>> AFTER: FF:FF:FF:FF:FF:FF
[net/ethernet] [ERR] ethernet_send: >>> BEFORE: FF:FF:FF:FF:FF:FF
[net/ethernet] [ERR] ethernet_send: >>> AFTER: FF:FF:FF:FF:FF:FF

And now I have a DHCP IP assigned.

**Comment by jukkar** [comment]
Ok, good to know. I will investigate why the other change is causing issues.

**Comment by jukkar** [comment]
@mike-scott Sent a new version that tries to make sure that we do not mess with dst eth address unless needed.

**Review by mike-scott — APPROVED** [review]
Looks good to me.  I'm seeing normal looking DHCP broadcasts when I turn on debugging.   I'm running a test CI loop now.

**Pull request merged**
