### PR TITLE
kernel: add k_realloc

### PR DESCRIPTION
**Pull request by maxbachmann**
This adds a k_realloc function, that allows to reallocate memory
from the heap memory pool. It uses a similar implementation to
realloc.

Signed-off-by: Maximilian Bachmann <m.bachmann@acontis.com>

### CODE REVIEW

**Comment by jukkar** [comment]
Do we really want to support `k_realloc()` as the API is a bad design.

**Review by tyrantlizard77 — COMMENTED** [review]
This PR collides with @andyross's work to get k_malloc() to use k_heap() internally.
I also agree with @jukkar that the upstream realloc() is not a great design to emulate.

**Comment by sylvioalves** [comment]
@maxbachmann check this out: https://github.com/zephyrproject-rtos/zephyr/pull/28611
It might be helpful if you wish to get realloc implementation.

**Comment by andyross** [comment]
Yeah, sorry, I didn't see this when it came by.  There is in fact a heap-internal optimized sys_heap_realloc() implementation in that linked PR.

**Pull request closed without merging**
