### PR TITLE
doc: power_management: add diagrams illustrating power management

### PR DESCRIPTION
**Pull request by wentongwu**
Add diagram showing the current system power management and the central
method of device power management.

The diagrams were made using draw.io and can be edit using draw.io.

Signed-off-by: Wentong Wu <wentong.wu@intel.com>

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
Thanks. Lines through the boxes are a bit wonky looking, but OK fo now.

**Comment by pizi-nordic** [comment]
Some comments to the picture:

- The CPU could resume when it stopped in deep sleep state, however this is not mandatory like in normal sleep state. The CPU could exit from deep sleep state also through reset.

- The relation between peripherals and SoC sleep state requires some comments. I see the intention, but the way how this topic is presented is not clear.

**Comment by wentongwu** [comment]
> Some comments to the picture:
> 
> * The CPU could resume when it stopped in deep sleep state, however this is not mandatory like in normal sleep state. The CPU could exit from deep sleep state also through reset. On the picture it always resumes through reset.

@pizi-nordic Thanks for the review, I added the reboot from deep sleep state for the picture, please review. 

> * The relation between peripherals and SoC sleep state requires some comments. I see the intention, but the way how this topic is presented is not clear.

Sorry, I didn't get the idea, you mean coupling device power states with system power states?

**Comment by pizi-nordic** [comment]
> Sorry, I didn't get the idea, you mean coupling device power states with system power states?

In the deep sleep the system could suspend devices too. As far as I understood, this is represented by "Power Gate" and green colour of the devices in the picture. At first glance this is not obvious in my opinion and some kind of note should be added there.

**Comment by wentongwu** [comment]
> > Sorry, I didn't get the idea, you mean coupling device power states with system power states?
> 
> In the deep sleep the system could suspend devices too. As far as I understood, this is represented by "Power Gate" label and green colour of the devices in the picture. At first glance this is not obvious in my opinion and some kind of note should be added there.

ok, thanks, please re-visit the new picture.

**Comment by carlescufi** [comment]
@pizi-nordic @pabigot please re-review

**Review by pizi-nordic — APPROVED** [review]
Looks good. Thank you.

**Pull request merged**
