### PR TITLE
drivers: can: sam: use UPLL clock instead of PLLA clock

### LINKED ISSUE #45012: sam_e70b_xplained: failed to run test case tests/drivers/can/timing/drivers.can.timing
**Describe the bug**
The test case failed after commit id: 5961ad2af8f3<Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/can/timing/src/main.c:194: test_timing_values: (sp_err >= 0 is false)>.The root cause is not clear yet.

**To Reproduce**
1. source zephyr-env.sh
2. west build -p always -b sam_e70b_xplained tests/drivers/can/timing
3. Open another terminal and execute: picocom -b 115200 /dev/ttyACM0
4. west flash
5. See error
 or
2. twister --device-testing --hardware-map $HOME/sam_e70b_xplained.file -T tests/drivers/can/timing -vv
3. See error

**Expected behavior**
Test case should pass as expected.

**Impact**
The test case drivers.can.timing failed.

**Logs and console output**
```
DEBUG   - DEVICE: testing on device CAN_0
DEBUG   - DEVICE: Running test suite can_timing_tests
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_set_timing_min
DEBUG   - DEVICE: PASS - test_set_timing_min in 0.1 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_set_timing_max
DEBUG   - DEVICE: PASS - test_set_timing_max in 0.1 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_timing
DEBUG   - DEVICE: testing bitrate 20000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 130, phase_seg2 = 19, prescaler = 50 OK, sample point error 0.2%
DEBUG   - DEVICE: testing bitrate 50000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 15 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 125000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 209, phase_seg2 = 30, prescaler = 5 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 250000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 3 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 130, phase_seg2 = 19, prescaler = 2 OK, sample point error 0.2%
DEBUG   - DEVICE: testing bitrate 800000, sample point 80.0% (valid):
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/can/timing/src/main.c:194: test_timing_values: (sp_err >= 0 is false)
DEBUG   - DEVICE: unknown error -22
DEBUG   - DEVICE: FAIL - test_timing in 0.80 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_timing_data
DEBUG   - DEVICE: testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 25, phase_seg2 = 4, prescaler = 10 OK, sample point error 0.9%
DEBUG   - DEVICE: testing bitrate 1000000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 25, phase_seg2 = 4, prescaler = 5 OK, sample point error 0.9%
DEBUG   - DEVICE: testing bitrate 500000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 26, phase_seg2 = 3, prescaler = 10 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 23, phase_seg2 = 6, prescaler = 10 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 100.0% (invalid): OK
DEBUG   - DEVICE: testing bitrate 8000001, sample point 75.0% (invalid): OK
DEBUG   - DEVICE: PASS - test_timing_data in 0.60 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: Test suite can_timing_tests failed.
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: 3388c175cce6eae39d7aabc0b45b2cfc
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
DEBUG   - run status: sam_e70_xplained/tests/drivers/can/timing/drivers.can.timing failed
INFO    - 1/1 sam_e70_xplained          tests/drivers/can/timing/drivers.can.timing        FAILED Failed (device 4.982s)
```

**Environment :**
OS: Linux,
Toolchain Zephyr SDK 0.13.2
Commit SHA or Version: 5961ad2af8f3

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Use the UPLLCK clock for the CAN controller as recommended by the Atmel SAM E70 data sheet.

Fixes: #45012

Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
The `can_sam_get_core_clock()` function likely needs updating as well to reflect the change in CAN core clock frequency, but I do not have the hardware to test with.  @nandojve Any ideas?

**Comment by nandojve** [comment]
> 

Hi @henrikbrixandersen ,
Let me check

**Comment by nandojve** [comment]
> > 
> 
> Hi @henrikbrixandersen , Let me check

@henrikbrixandersen ,

May you check if below enables UPLLCK at 480 MHz:

```diff
diff --git a/soc/arm/atmel_sam/same70/soc.c b/soc/arm/atmel_sam/same70/soc.c
index 77a7fe0cf3..bd0e77c9ae 100644
--- a/soc/arm/atmel_sam/same70/soc.c
+++ b/soc/arm/atmel_sam/same70/soc.c
@@ -177,6 +177,15 @@ static ALWAYS_INLINE void clock_init(void)
                ;
        }
 
+       /* Setup UPLL */
+       PMC->CKGR_UCKR = CKGR_UCKR_UPLLCOUNT(0x3Fu);
+                      | CKGR_UCKR_UPLLEN;
+
+       /* Wait for PLL lock */
+       while (!(PMC->PMC_SR & PMC_SR_LOCKU)) {
+               ;
+       }
+
        /*
         * Final setup of the Master Clock
         */
```

**Comment by henrikbrixandersen** [comment]
> May you check if below enables UPLLCK at 480 MHz:

Thanks! I do not have access to the hardware, but perhaps @shaoanxli can check?

**Comment by shaoanxli** [comment]
> > May you check if below enables UPLLCK at 480 MHz:
> 
> Thanks! I do not have access to the hardware, but perhaps @shaoanxli can check?

Is there any good way to get UPLLCK? It seems no register to get the UPLLCK.

**Comment by nandojve** [comment]
> Is there any good way to get UPLLCK?

The below is supposed to work.

```diff
diff --git a/soc/arm/atmel_sam/same70/soc.c b/soc/arm/atmel_sam/same70/soc.c
index 77a7fe0cf3..bd0e77c9ae 100644
--- a/soc/arm/atmel_sam/same70/soc.c
+++ b/soc/arm/atmel_sam/same70/soc.c
@@ -177,6 +177,15 @@ static ALWAYS_INLINE void clock_init(void)
                ;
        }
 
+       /* Setup UPLL */
+       PMC->CKGR_UCKR = CKGR_UCKR_UPLLCOUNT(0x3Fu);
+                      | CKGR_UCKR_UPLLEN;
+
+       /* Wait for PLL lock */
+       while (!(PMC->PMC_SR & PMC_SR_LOCKU)) {
+               ;
+       }
+
        /*
         * Final setup of the Master Clock
         */
```

**Comment by shaoanxli** [comment]
The UPLLCK seems to setup successfully , but the test failed , logs and console output shows:

```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.0.0-3206-gf7171e20b33e  ***
DEBUG   - DEVICE: testing on device CAN_0 @ 150000000 Hz
DEBUG   - DEVICE: Running test suite can_timing_tests
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_set_timing_min
DEBUG   - DEVICE: PASS - test_set_timing_min in 0.1 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_set_timing_max
DEBUG   - DEVICE: PASS - test_set_timing_max in 0.1 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_timing
DEBUG   - DEVICE: testing bitrate 20000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 130, phase_seg2 = 19, prescaler = 50 OK, sample point error 0.2%
DEBUG   - DEVICE: testing bitrate 50000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 15 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 125000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 209, phase_seg2 = 30, prescaler = 5 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 250000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 3 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 130, phase_seg2 = 19, prescaler = 2 OK, sample point error 0.2%
DEBUG   - DEVICE: testing bitrate 800000, sample point 80.0% (valid):
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/can/timing/src/main.c:194: test_timing_values: (sp_err >= 0 is false)
DEBUG   - DEVICE: unknown error -22
DEBUG   - DEVICE: FAIL - test_timing in 0.80 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_timing_data
DEBUG   - DEVICE: testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 25, phase_seg2 = 4, prescaler = 10 OK, sample point error 0.9%
DEBUG   - DEVICE: testing bitrate 1000000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 25, phase_seg2 = 4, prescaler = 5 OK, sample point error 0.9%
DEBUG   - DEVICE: testing bitrate 500000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 26, phase_seg2 = 3, prescaler = 10 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 23, phase_seg2 = 6, prescaler = 10 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 100.0% (invalid): OK
DEBUG   - DEVICE: testing bitrate 8000001, sample point 75.0% (invalid): OK
DEBUG   - DEVICE: PASS - test_timing_data in 0.60 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: Test suite can_timing_tests failed.
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: 52876579eaf0bab6807fb28529187fe9
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
```

**Comment by nandojve** [comment]
> The UPLLCK seems to setup successfully , but the test failed 

Hi @shaoanxli,

Let me check!

**Comment by shaoanxli** [comment]
> > The UPLLCK seems to setup successfully , but the test failed
> 
> Hi @shaoanxli,
> 
> Let me check!

This error seems to occur here(drivers/can/can_common.c) : 107  , when bitrate=800000 :

```
if (core_clock % (prescaler * bitrate)) {
	/* No integer ts */
	continue;
}
```

**Comment by henrikbrixandersen** [comment]
> The UPLLCK seems to setup successfully , but the test failed , logs and console output shows:
> 
> ```
> DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.0.0-3206-gf7171e20b33e  ***
> DEBUG   - DEVICE: testing on device CAN_0 @ 150000000 Hz

The `can_sam_get_core_clock()` function needs to be updated to report the correct clock frequency and you need to use one of the clock dividers recommended by the data sheet (see the linked issue).

Without those changes there are no changes to the CAN timing calculations.

**Comment by henrikbrixandersen** [comment]
@shaoanxli, @nandojve I have tried to incorporate the needed changes as good as I can from studying the datasheet and the suggested code from @nandojve. Please test - both the CAN timing test cases and the actual CAN bitrate as presented on the CAN bus.

@alexanderwachter You wrote the original driver - can you assist in testing?

**Comment by nandojve** [comment]
> @shaoanxli, @nandojve I have tried to incorporate the needed changes as good as I can from studying the datasheet and the suggested code from @nandojve. Please test - both the CAN timing test cases and the actual CAN bitrate as presented on the CAN bus.
> 
> @alexanderwachter You wrote the original driver - can you assist in testing?

Hi folks,

There is nothing wrong with this patch. You just need select correct divisor at devicetree. With 24 CAN clock will be 20MHz. Please, change it to 6 then clock will be 80MHz. See below result at SAMV71_XULT:

```
*** Booting Zephyr OS build zephyr-v3.0.0-3510-g9a8162aca685  ***
testing on device CAN_1 @ 80000000 Hz
Running test suite can_timing_tests
===================================================================
START - test_set_timing_min
 PASS - test_set_timing_min in 0.1 seconds
===================================================================
START - test_set_timing_max
 PASS - test_set_timing_max in 0.1 seconds
===================================================================
START - test_timing
testing bitrate 20000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 20 OK, sample point error 0.0%
testing bitrate 50000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 8 OK, sample point error 0.0%
testing bitrate 125000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 139, phase_seg2 = 20, prescaler = 4 OK, sample point error 0.0%
testing bitrate 250000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 139, phase_seg2 = 20, prescaler = 2 OK, sample point error 0.0%
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 139, phase_seg2 = 20, prescaler = 1 OK, sample point error 0.0%
testing bitrate 800000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 79, phase_seg2 = 20, prescaler = 1 OK, sample point error 0.0%
testing bitrate 1000000, sample point 75.0% (valid): prop_seg = 0, phase_seg1 = 59, phase_seg2 = 20, prescaler = 1 OK, sample point error 0.0%
testing bitrate 125000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 143, phase_seg2 = 16, prescaler = 4 OK, sample point error 0.0%
testing bitrate 125000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 255, phase_seg2 = 64, prescaler = 2 OK, sample point error 0.0%
testing bitrate 125000, sample point 100.0% (invalid): OK
testing bitrate 8000001, sample point 75.0% (invalid): OK
 PASS - test_timing in 0.123 seconds
===================================================================
START - test_timing_data
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 27, phase_seg2 = 4, prescaler = 5 OK, sample point error 0.0%
testing bitrate 1000000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 13, phase_seg2 = 2, prescaler = 5 OK, sample point error 0.0%
testing bitrate 500000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 17, phase_seg2 = 2, prescaler = 8 OK, sample point error 0.0%
testing bitrate 500000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 31, phase_seg2 = 8, prescaler = 4 OK, sample point error 0.0%
testing bitrate 500000, sample point 100.0% (invalid): OK
testing bitrate 8000001, sample point 75.0% (invalid): OK
 PASS - test_timing_data in 0.60 seconds
===================================================================
Test suite can_timing_tests succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

BTW, don't forget to add `soc: arm: atmel: same70: enable the UPLL clock` to samv71.

**Comment by henrikbrixandersen** [comment]
@nandojve Thank you so much for your help on co-authoring and verifying this fix :) I have marked it ready for review.

**Comment by nandojve** [comment]
> @nandojve Thank you so much for your help on co-authoring and verifying this fix :) I have marked it ready for review.

Hi @henrikbrixandersen , you are welcome!
BTW, it should be `nandojve@gmail.com` in this case. Thank you!

**Comment by henrikbrixandersen** [comment]
> Hi @henrikbrixandersen , you are welcome! BTW, it should be `nandojve@gmail.com` in this case. Thank you!

Fixed.

**Review by nandojve — APPROVED** [review]

**Review by alexanderwachter — APPROVED** [review]
Cannot get my hands on the HW at the moment. Did somebody test?

Edit: never mind. Test results were hidden in the APP 🤦‍♂️

**Comment by shaoanxli** [comment]
> Cannot get my hands on the HW at the moment. Did somebody test?
> 
> Edit: never mind. Test results were hidden in the APP 🤦‍♂️

I tried the test on the HW . The test pass.
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.0.0-3507-g6388778fb17d  ***
DEBUG   - DEVICE: testing on device CAN_0 @ 80000000 Hz
DEBUG   - DEVICE: Running test suite can_timing_tests
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_set_timing_min
DEBUG   - DEVICE: PASS - test_set_timing_min in 0.1 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_set_timing_max
DEBUG   - DEVICE: PASS - test_set_timing_max in 0.1 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_timing
DEBUG   - DEVICE: testing bitrate 20000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 20 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 50000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 8 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 125000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 139, phase_seg2 = 20, prescaler = 4 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 250000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 139, phase_seg2 = 20, prescaler = 2 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 139, phase_seg2 = 20, prescaler = 1 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 800000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 79, phase_seg2 = 20, prescaler = 1 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 1000000, sample point 75.0% (valid): prop_seg = 0, phase_seg1 = 59, phase_seg2 = 20, prescaler = 1 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 125000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 143, phase_seg2 = 16, prescaler = 4 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 125000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 255, phase_seg2 = 64, prescaler = 2 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 125000, sample point 100.0% (invalid): OK
DEBUG   - DEVICE: testing bitrate 8000001, sample point 75.0% (invalid): OK
DEBUG   - DEVICE: PASS - test_timing in 0.123 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_timing_data
DEBUG   - DEVICE: testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 27, phase_seg2 = 4, prescaler = 5 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 1000000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 13, phase_seg2 = 2, prescaler = 5 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 17, phase_seg2 = 2, prescaler = 8 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 31, phase_seg2 = 8, prescaler = 4 OK, sample point error 0.0%
DEBUG   - DEVICE: testing bitrate 500000, sample point 100.0% (invalid): OK
DEBUG   - DEVICE: testing bitrate 8000001, sample point 75.0% (invalid): OK
DEBUG   - DEVICE: PASS - test_timing_data in 0.60 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: Test suite can_timing_tests succeeded
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: 63937deb897c652468f6c0e64355cba8
DEBUG   - DEVICE: PROJECT EXECUTION SUCCESSFUL
```

**Pull request merged**
