### PR TITLE
lib: posix: semaphore: use consistent timebase in sem_timedwait

### PR DESCRIPTION
**Pull request by cfriedt**
In the Zephyr implementation, `sem_timedwait()` uses a possibly very different time base for comparison via `k_uptime_get()` (uptime in ms).

The standard specifies that comparisons should use `CLOCK_REALTIME`.  An implementation detail - Zephyr uses the value of `k_uptime_get()` when processing `clock_gettime(CLOCK_REALTIME, ..)`. However, there is an offset that can be modified at any time via `clock_settime(CLOCK_REALTIME, ..)`. As such, there is no guarantee whatsoever that `clock_gettime(CLOCK_REALTIME, ..)` will be consistent with `k_uptime_get()`.

The solution is to use `clock_gettime(CLOCK_REALTIME, ..)` internally within `sem_timedwait()` which ensures a consistent time base for comparison.

For reference, [the testsuite](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/posix/common/src/semaphore.c#L83) and [the spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_timedwait.html) both use and specify to compare with `CLOCK_REALTIME`.
    
Fixes #46807

### CODE REVIEW

**Comment by cfriedt** [comment]
This blocks https://github.com/zephyrproject-rtos/zephyr/pull/46809

**Review by andyross — DISMISSED** [review]

**Comment by cfriedt** [comment]
* add explicit `depends on POSIX_CLOCK` to `PTHREAD_IPC` (for `semaphore.c`)

**Comment by keith-packard** [comment]
Hrm. I'd call this out as a gap in the POSIX spec -- semaphores are forced to use the REALTIME clock, which changes when the system time is adjusted. Pthread condition variables have `pthread_condattr_setclock` which allows applications to switch to MONOTONIC, but there's no equivalent for pthread mutexes or posix semaphores.

Reviewing the Zephyr implementation of pthread condition variables and mutexes shows that they *always* use MONOTONIC, which is a variation from POSIX. Given that MONOTONIC is effectively always what applications want, I think zephyr semaphores should probably vary from POSIX in this case too.

What is needed is some way to catch likely problems in porting POSIX code to Zephyr. It's tempting to actually *remove* the REALTIME clockid so that applications using that in conjunction with these APIs would fail to build.

**Comment by cfriedt** [comment]
> Hrm. I'd call this out as a gap in the POSIX spec -- semaphores are forced to use the REALTIME clock, which changes when the system time is adjusted. 

Yes, that's an obvious gap. It should be taken into account by the API consumer.

> Pthread condition variables have `pthread_condattr_setclock` which allows applications to switch to MONOTONIC, but there's no equivalent for pthread mutexes or posix semaphores.
> 
> Reviewing the Zephyr implementation of pthread condition variables and mutexes shows that they _always_ use MONOTONIC, which is a variation from POSIX. Given that MONOTONIC is effectively always what applications want, I think zephyr semaphores should probably vary from POSIX in this case too.

There is a difference though - the specification for `sem_timedwait()` says that REALTIME should be used, but the specification for pthread cond / mutexes does not.

> What is needed is some way to catch likely problems in porting POSIX code to Zephyr. It's tempting to actually _remove_ the REALTIME clockid so that applications using that in conjunction with these APIs would fail to build.

It's debatable. I think if we did do that, and then later tried to pass some sort of POSIX certification, then we would likely have to undo the work that we did. Maybe we could continue discussion on Discord on that topic.

This PR, OTOH, is about fixing a fairly well-defined bug and unblocking additional work such as https://github.com/zephyrproject-rtos/zephyr/issues/46793.

**Comment by keith-packard** [comment]
> There is a difference though - the specification for `sem_timedwait()` says that REALTIME should be used, but the specification for pthread cond / mutexes does not.

Current POSIX requires condition variables support a clockid, and also does specify that mutexes use REALTIME. Sorry I can't provide direct links to the relevant specs, the current POSIX spec is a lovely frame page. 

https://pubs.opengroup.org/onlinepubs/9699919799/

> It's debatable. I think if we did do that, and then later tried to pass some sort of POSIX certification, then we would likely have to undo the work that we did. Maybe we could continue discussion on Discord on that topic.

Yeah, but the POSIX spec is really bad in this area and causes applications to have persistent bugs related to timing in the very rare instances where the system time is changed. And, currently, all of Zephyr uses MONOTONIC for timeouts, which is a technically better answer here, except that it conflicts with the POSIX spec.

> This PR, OTOH, is about fixing a fairly well-defined bug and unblocking additional work such as #46793.

It fixes a bug related to standards conformance and leaves applications open to timing bugs forever. I'm not sure that's a net win. I'd rather see Zephyr remove support for REALTIME clockid as that would weed out applications misusing that value...

**Comment by andyross** [comment]
Not engaging on the standards minutiae, as that's... really kind of not my thing.

>  I'd rather see Zephyr remove support for REALTIME clockid as that would weed out applications misusing that value...

We don't really have a "real time" clock subsystem anyway, in the sense of something that tracks corrections from external time sources.   The kernel provides k_uptime_ticks() as the base API, and that's just a system uptime from whenever the subsystem initialized (not always when power was provided, and definitely not the origin of the hardware counter(s) in use). 

A quick read shows that POSIX just implements REALTIME via a configurable offset and expects someone else will come along and call clock_settime().  But no one does, so it doesn't matter.

If removing CLOCK_REALTIME (until we have a realtime subsystem we can use to implement it) is an option that preserves compliance to whoever cares, then that sounds appealing to me.

**Comment by keith-packard** [comment]
> Not engaging on the standards minutiae, as that's... really kind of not my thing.

Yeah, that's kinda where we are here though. And in the historical mistakes made during the slow changes in POSIX related to time.

> We don't really have a "real time" clock subsystem anyway, in the sense of something that tracks corrections from external time sources. The kernel provides k_uptime_ticks() as the base API, and that's just a system uptime from whenever the subsystem initialized (not always when power was provided, and definitely not the origin of the hardware counter(s) in use).

That's kinda surprising -- I'd expect there to be a full NTP and potentially even PTP implementation available in Zephyr.

> If removing CLOCK_REALTIME (until we have a realtime subsystem we can use to implement it) is an option that preserves compliance to whoever cares, then that sounds appealing to me.

No, removing CLOCK_REALTIME is in violation of the POSIX spec as semaphores, mutexes are defined in terms of this clock, and condition variables uses this clock basis by default. What it would uncover is places where applications are going to have bugs whenever Zephyr gains a more complete REALTIME implementation based on NTP/PTP. Not even providing REALTIME would force code being ported from POSIX to fix these bugs before they could potentially happen.

**Comment by andyross** [comment]
> That's kinda surprising -- I'd expect there to be a full NTP and potentially even PTP implementation available in Zephyr.

Closest we have is SNTP, but it's just the protocol.  There's no systemwide arbiter of "real time" which protocol engines can inform and from which subsystems like POSIX can abstract.

**Review by andyross — APPROVED** [review]
Refresh +1

The fix seems entirely unobjectionable.  The need for a proper real time subsystem is for sure a long term thing (and well outside of my expertise umbrella anyway)

**Review by stephanosio — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
