### PR TITLE
rtio: Fix cpp compatibility

### PR DESCRIPTION
**Pull request by wojciechslenska**
Fixed comparison between signed(int64_t) and unsigned(uint64_t) variables.

Fixed the following g++ compilation error:
```
In file included from /mycode/zephyr/include/zephyr/drivers/sensor.h:27,

/mycode/zephyr/include/zephyr/rtio/rtio.h: In function 'int z_impl_rtio_cqe_copy_out(rtio*, rtio_cqe*, size_t, k_timeout_t)':
/mycode/zephyr/include/zephyr/rtio/rtio.h:1385:44: error: comparison of integer expressions of different signedness: 'uint64_t' {aka 'long long unsigned int'} and 'int64_t' {aka 'long long int'} [-Werror=sign-compare]
 1385 |         } while (copied < cqe_count && end > k_uptime_ticks());
 ```

### CODE REVIEW

**Comment by teburd** [comment]
I don't disagree this is a bug, but the fix is wrong. The end value here should be changed to use signed. Casting ticks to unsigned here looks wrong.

**Comment by teburd** [comment]
related I believe #58186

**Comment by wojciechslenska** [comment]
> I don't disagree this is a bug, but the fix is wrong. The end value here should be changed to use signed. Casting ticks to unsigned here looks wrong.

Changed based on your suggestion.

**Review by teburd — APPROVED** [review]

**Comment by andyross** [comment]
The timer API is signed[1] because you want to subtract times to get deltas, and negative/overflowed values in that space mean "before", which is generally valid and what you want.  Unsigned values dealing with timer math are almost always a mistake, even though "uptime" itself is an unambiguously a positive value.

[1] Except for the legacy _get_32() variants of the APIs, which were originally specified unsigned.

**Review by mbolivar-nordic — APPROVED** [review]

**Pull request merged**
