### PR TITLE
drivers: gpio_nrfx: Correct the way the callbacks are fired

### LINKED ISSUE #15119: GPIO callback not disabled from an interrupt
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/issues/10186 is back again.

In new hw version we can no longer use single callback as we have pins scattered on two ports. We need to disable callbacks for both ports at the same time in the single interrupt. Yet the current infrastructure makes it impossible.

I will narrow it to nrf52 case. `gpiote_event_handler` first checks which ports/pins fired and then trigger callbacks for port 0 followed by callbacks for port 1.
In our case we want to disable interrupt for port 1 when servicing port 0 interrupt. The way function is implemented it does not work as local copy of what fired was already made.

**To Reproduce**
Configure pin interrupt on two ports. Hook a callback to each port. Disable both callbacks from isr. Trigger interrupt on both pins at the same time. Observed that disable does not work for port 1 and isr is still called.

**Expected behavior**
Disable isr should not be called.

**Impact**
Can be serious if not handled correctly/unexpected.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
ncs zephyr: `0bf5263b0522bb5cfac84eefdfdee86dc2c67e3e` (upstream `d3bb3cf`)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by anangl**
Add additional masking of the pins with fired callback triggers
against the currently enabled callbacks, in order to not call
handlers for callbacks that got disabled in some other callback
handlers that were called in the same ISR execution.

Fixes #15119.

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
Looks OK to me.

**Review by Mierunski — APPROVED** [review]

**Comment by anangl** [comment]
Rebased on master in order to restart CI, as it failed in a [strange way](https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/48284/1/console) which does not seem to be related to the changes introduced by this PR.

**Comment by ioannisg** [comment]
@pdunaj , @pizi-nordic please review

**Review by pizi-nordic — APPROVED** [review]

**Comment by ioannisg** [comment]
@Mierunski could you tell if this patch needs to be back-ported to 1.14? At least, the bug is reported before the 1.14 release, AFAICS...

**Comment by Mierunski** [comment]
It should be back-ported in my opinion

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
