### PR TITLE
kconfig: modules: Avoid including Kconfig.tls-generic twice

### PR DESCRIPTION
**Pull request by ulfalizer**
The glob in modules/Kconfig accidentally picked up Kconfig.tls-generic,
which is only supposed to be included from modules/Kconfig.mbedtls.

Replace the globbing with explicit 'source's to fix it. Best to avoid
globbing unless absolutely necessary, because it tends to pick up random
non-checked-in files as well.

Use 'source' instead of 'osource' since the files are known to exists.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
I am OK with this, it's safer anyway.
The commit message has a mistake in it:

>Also use 'source' instead of 'rsource', to make the paths greppable.
'rsource' is mostly meant for rare out-of-tree cases.

In fact, `osource` is being used.

**Review by tejlmand — APPROVED** [review]
This change itself look good to me.
However, this PR made me wonder if the Kconfig.\<vendor\> and so should be moved to the module itself.
Zephyr modules supports loading of Kconfig files when used as a zephyr module.

As example, when using NCS and not having cloned `modules/hal/stm32`, then symbols such as: `HAS_STM32CUBE` still shows up in searches, and when enabling `Show-all` in menuconfig.

**Comment by ulfalizer** [comment]
> The commit message has a mistake in it:
> 
> > Also use 'source' instead of 'rsource', to make the paths greppable.
> > 'rsource' is mostly meant for rare out-of-tree cases.
> 
> In fact, `osource` is being used.

Fixed. Confused it with a different spot.

**Comment by carlescufi** [comment]
> This change itself look good to me.
> However, this PR made me wonder if the Kconfig.<vendor> and so should be moved to the module itself.
> Zephyr modules supports loading of Kconfig files when used as a zephyr module.
> 
> As example, when using NCS and not having cloned `modules/hal/stm32`, then symbols such as: `HAS_STM32CUBE` still shows up in searches, and when enabling `Show-all` in menuconfig.

@tejlmand we have tried that in the past and it doesn't work. The moment you start removing projects from the manifest (like Intel and  Nordic do in their downstream) all sorts of problems pop up in Kconfig.

**Comment by ulfalizer** [comment]
Yeah, I'm not sure we need more module stuff. Don't think it's proven to be more helpful than a source of problems at this point.

**Pull request merged**
