### PR TITLE
GMAC: reduce memory pressure on the IP stack

### PR DESCRIPTION
**Pull request by aurel32**
There have been many complaints that the GMAC ethernet driver put too much pressure on the IP stack. This PR partially addresses this. I know that some people will still feel grumpy about that, but that is a first step. After this PR, the minimum values are:
NET_BUF_TX_COUNT=0
NET_BUF_RX_COUNT=24

Contrary to what I have seen there is no minimum value enforced on NET_PKT_TX_COUNT or CONFIG_NET_PKT_RX_COUNT.

### CODE REVIEW

**Comment by jukkar** [comment]
> Contrary to what I have seen there is no minimum value enforced on NET_PKT_TX_COUNT or CONFIG_NET_PKT_RX_COUNT.

There should be a check for CONFIG_NET_PKT_RX_COUNT as having that set to 0 means that we are not able to receive any packet. I can send a patch that fixes it.
Also having CONFIG_NET_PKT_TX_COUNT set to 0 does not seem make sense either as we would not be able send anything which seems quite pointless.

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by aurel32** [comment]
> There should be a check for CONFIG_NET_PKT_RX_COUNT as having that set to 0 means that we are not able to receive any packet. I can send a patch that fixes it.
> Also having CONFIG_NET_PKT_TX_COUNT set to 0 does not seem make sense either as we would not be able send anything which seems quite pointless.

Indeed, and probably the same for `NET_BUF_RX_COUNT` and  `NET_BUF_TX_COUNT`. That said I think the check should be at the IP stack level and not the driver level.

**Comment by jukkar** [comment]
> Indeed, and probably the same for `NET_BUF_RX_COUNT` and `NET_BUF_TX_COUNT`. That said I think the check should be at the IP stack level and not the driver level.

Indeed. I will send a PR for this.

**Comment by jukkar** [comment]
The PR #13307 will check the minimum values for net_pkts and net_bufs.

**Review by pfalcon — APPROVED** [review]
@aurel32: I appreciate your paying attention gradually working on these matters. And yes, I hope these are first steps and we can establish best practices how to deal with such cases (as of course we want more drivers to use DMA, etc. acceleration eventually).

**Pull request merged**
