### PR TITLE
[DNM] LD: Don't force a reference to the symbol _OffsetAbsSyms

### PR DESCRIPTION
**Pull request by SebastianBoe**
A reference to the symbol '_OffsetAbsSyms' is being artificially
forced by a command line argument to the linker.

As far as possible one should not be passing flags to the linker through the
build system. Instead one should write appropriate linker scripts.

This patch removes the command line argument to the linker.

TODO: Find out why we need to force the symbol and if necessary how to
continue to force it.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
This PR is not ready for review, it exists to run CI.

I want to simplify the linker command line as much as possible. This PR looks at the flag

-u_OffsetAbsSyms

What is it doing? Why does it do it like this? Are there any alternatives?

It appears to exist to force the object file offsets.o to be included in the link. But we already have a mechanism for that, whole-archive. So I don't see why we should be using a different mechanism here.

Unless there is a difference between whole-archive and forcing a single symbol in an object file to be referenced. It could be that this is an optimization, that moving offsets into whole-archive will cause all symbols in offsets.o to be included, whereas before symbols would be cherry-picked.

First off, we need to run CI to find out if simply removing it causes any failures.

**Comment by tejlmand** [comment]
In general, the whole-archive is not a good approach, as it will always keep everything, hence the linker cannot remove unused public function, and it remove the possibility to do link time optimization in future.
It also bears the risk of having larger than neccesary libraries.

Ideally, this flag should go to the library that provides the symbol, as described in #8445 
To me, using the -u_OffsetsAbsSyms is in fact added by someone who knows the right way
And adding this flag ensure that only this symbol is kept. Linker can still optimize on the remaining part of the library

**Comment by aescolar** [comment]
Note that whole-archive when used in combination with gc-sections does still result in the linker garbage collecting what it can. In that case, whole-archive will have the linker grab all symbols from its input (even if it does not know yet about their possible use), and will save you from needing to worry about including libraries multiple times in the linker command line, or worrying about their order.

**Comment by tejlmand** [comment]
this is the nice thing with CMake.
You don't need to worry about this.

If I create libA, and states libA depends on libB, and I have stated libB depends on libC, then CMake takes care of the order.
And if I also state libB depends back on libA, then CMake will ensure the circular dependency i handled correctly.

The one writing libA, on need to consider, am I dependent on libB, cause i'm using functions from libB API.

and we don't need to use compiler specific linker flags.

**Pull request closed without merging**
