### PR TITLE
samples: net: sockets: Create a test for socket offloading

### PR DESCRIPTION
**Pull request by jukkar**
Create a test of socket offloading. Build the test for
cc3220sf_launchxl board.

This tries to catch the issue in #27587 and depends on #27588

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by vanti** [comment]
@jukkar do you know why the existing `echo` and `http_get` samples are not getting built when PRs are submitted? I'd have expected them to catch the failures. Adding new tests is fine, but the existing ones should be built as well.

**Comment by jukkar** [comment]
> do you know why the existing `echo` and `http_get` samples are not getting built when PRs are submitted? I'd have expected them to catch the failures. Adding new tests is fine, but the existing ones should be built as well.

One explanation might be that sanity is probably not run for cc3220sf_launchxl or cc3235sf_launchxl by default. As the sample.yaml in those directories does mention these boards in the whitelisting, the tests are not built and we missed the build issue.

This PR creates offloading test that is specifically run for cc3220sf_launchxl board, and now the offloading case is tested properly.

**Comment by nandojve** [comment]
> @jukkar do you know why the existing `echo` and `http_get` samples are not getting built when PRs are submitted? I'd have expected them to catch the failures. Adding new tests is fine, but the existing ones should be built as well.

related: #27151

**Comment by vanti** [comment]
> One explanation might be that sanity is probably not run for cc3220sf_launchxl or cc3235sf_launchxl by default. As the sample.yaml in those directories does not mention these boards in the whitelisting, the tests are not built and we missed the build issue.
> 
> This PR creates offloading test that is specifically run for cc3220sf_launchxl board, and now the offloading case is tested properly.

@jukkar I tried the binaries built by sanitycheck, and they have some runtime errors. For example, echo_server has this output:

```
    [00:00:03.952,000] <inf> wifi_simplelink: [WLAN EVENT] STA Connected to the AP: ThingsNet, BSSID: 2c:30:33:51:53:33
    [00:00:03.952,000] <inf> wifi_simplelink: [NETAPP EVENT] IP set to: IPv4=192.0.2.1, Gateway=0.0.0.0
    uart:~$ *** Booting Zephyr OS build zephyr-v2.3.0-1884-g2f99f44c1413  ***
    [00:00:06.882,000] <inf> wifi_simplelink: [NETAPP EVENT] IP Acquired: IPv6=fe80:0000:0000:0000:4206:a0ff:fe97:62cc
    [00:00:06.889,000] <inf> net_config: Initializing network
    [00:00:06.889,000] <inf> net_config: IPv4 address: 192.0.2.1
    [00:00:06.889,000] <wrn> net_if: no l2 for iface 0x20001fbc, discard pkt
    [00:00:06.893,000] <inf> net_echo_server_sample: Run echo server
    [00:00:06.893,000] <inf> net_echo_server_sample: Network connected
    [00:00:06.893,000] <inf> net_echo_server_sample: Starting...
    [00:00:06.896,000] <err> net_echo_server_sample: Failed to bind TCP socket (IPv4): 112
    [00:00:06.896,000] <inf> net_echo_server_sample: Stopping...
```

I think we should either fix these, or given the purpose of this PR, simply add the offloading test cases to http_get and echo instead, since those are the samples that are known to work on cc3220sf_launchxl and actually have a default configuration in boards/cc3220sf_launchxl.conf.

**Comment by jukkar** [comment]
> I think we should either fix these, or given the purpose of this PR, simply add the offloading test cases to http_get and echo instead, since those are the samples that are known to work on cc3220sf_launchxl and actually have a default configuration in boards/cc3220sf_launchxl.conf.

Sure, this quick PR was just created to catch the build issue, but if the application does not work in the board, then that is of course bad. I can send a new version that only adds the tests to http_get and echo.

**Review by pfalcon — APPROVED** [review]

**Comment by vanti** [comment]
I think the test case requires `harness: net` since it requires a network setup to run.

**Comment by jukkar** [comment]
> I think the test case requires `harness: net` since it requires a network setup to run.

http_get already has net harness defined in common section, echo test was missing that.

**Review by vanti — APPROVED** [review]
Thanks @jukkar. LGTM!

**Review by nashif — APPROVED** [review]

**Pull request merged**
