### PR TITLE
boards: arm: mimxrt10*_evk: Enable MPU

### PR DESCRIPTION
**Pull request by galak**
The MPU should have been enabled on all these boards since they have
Cortex-M7 and need mpu for caching support.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
Looks fine to me.
I think this goes together with the earlier PR that corrects CPU_HAS_MPU to CPU_HAS_ARM_MPU for the corresponding SOCs

**Comment by agansari** [comment]
Shouldn't CPU_HAS_ARM_MPU once set, also select CONFIG_ARM_MPU?

**Comment by ioannisg** [comment]
> 
> 
> Shouldn't CPU_HAS_ARM_MPU once set, also select CONFIG_ARM_MPU?

No, CPU_HAS_ARM_MPU defines SOC capabilities. CONFIG_ARM_MPU is a "user" option, adding support for Memory Protection to the build. CPU_HAS_ARM_MPU shall select the cross-arch option CPU_HAS_MPU

**Comment by agansari** [comment]
> > Shouldn't CPU_HAS_ARM_MPU once set, also select CONFIG_ARM_MPU?
> 
> No, CPU_HAS_ARM_MPU defines SOC capabilities. CONFIG_ARM_MPU is a "user" option, adding support for Memory Protection to the build. CPU_HAS_ARM_MPU shall select the cross-arch option CPU_HAS_MPU

Okay, thank you.

**Review by aurel32 — APPROVED** [review]
LGTM

**Review by nashif — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
Good catch, thanks @galak!

**Pull request merged**
