### PR TITLE
Added dummy display driver

### LINKED ISSUE #12001: Dummy Display driver for native_posix
**Is your feature request related to a problem? Please describe.**
The current native_posix SDL based display driver is not cleaning up its used memory, this is caused mainly by the SDL and OpenGL libraries and as such can not be corrected. The net results is that it is very hard to use valgrind once the SDL based display is enabled due to the large amount, ~3MB, of memory that is not cleaned up.

**Describe the solution you'd like**
Add a dummy display driver for native_posix that only implements the API

**Describe alternatives you've considered**
None

**Additional context**
See discussion https://github.com/zephyrproject-rtos/zephyr/pull/9149#discussion_r234434131 for more context

This feature could also be useful for running display related code in CI without including SDL2 (and all it dependencies) into the docker CI container

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Added dummy display driver

This driver can be used in CI together with a native posix target

fixes: #12001

### CODE REVIEW

**Review by aescolar — APPROVED** [review]
To me, it seems fine, but I'm no display API expert.

**Comment by aescolar** [comment]
Sidetrack: It seems a bit inconvenient that, to change the display driver that is initialized one needs to change the application. E.g.:
```diff
diff --git a/samples/display/cfb/src/main.c b/samples/display/cfb/src/main.c
index c4e74cbd27..a36b0b0d10 100644
--- a/samples/display/cfb/src/main.c
+++ b/samples/display/cfb/src/main.c
@@ -17,6 +17,10 @@
 #define DISPLAY_DRIVER                         "SSD1306"
 #endif
 
+#if defined (CONFIG_DUMMY_DISPLAY)
+#define DISPLAY_DRIVER                         "DUMMY_DISPLAY"
+#endif
+
 #ifndef DISPLAY_DRIVER
 #define DISPLAY_DRIVER "DISPLAY"
 #endif
```

**Comment by vanwinkeljan** [comment]
@aescolar Thx for the review!

On the sidetrack: 
> Sidetrack: It seems a bit inconvenient that, to change the display driver that is initialized one needs to change the application. E.g.:
> 

There is not need to change the code if ```CONFIG_DUMMY_DISPLAY_DEV_NAME``` is set to  ```"DISPLAY"``` instead of the default value (```"DUMMY_DISPLAY"```).  I tried this with the CFB sample + overlay config and it was working fine:

overlay-dummy-display.conf
```
CONFIG_DUMMY_DISPLAY_DEV_NAME="DISPLAY"
CONFIG_DUMMY_DISPLAY_X_RES=250
CONFIG_DUMMY_DISPLAY_Y_RES=120
```

Cmake cmd:
```
cmake -DOVERLAY_CONFIG="overlay-dummy-display.conf" -DBOARD=native_posix -GNinja ..
```

**Review by nashif — APPROVED** [review]

**Comment by aescolar** [comment]
> There is not need to change the code

( Yes.. and one could also have set the `DISPLAY` define [once I had seen in the code that the `DISPLAY` macro was the problem] from the cmake command line).
But I was thinking, is that I do not really see the point of these `*_DISPLAY_DEV_NAME` being anything else than "DISPLAY" by default.
As a side-effect that would avoid needing to do anything more than selecting a driver thru Kconfig)

**Comment by vanwinkeljan** [comment]
>But what I was thinking, is that I do not really see the point of these *_DISPLAY_DEV_NAME being anything else than "DISPLAY" by default.

The only reason I can come up with is that if you would have multiple displays you could get a name clash if they all default to "DISPLAY"

**Pull request merged**
