### PR TITLE
driver: dac: add nxp mcxn10 dac support

### PR DESCRIPTION
**Pull request by ZhaoxiangJin**
add nxp mcxn10 dac support, the local test has passed

### CODE REVIEW

**Comment by marcusfolkesson** [comment]
Could you please rephrase the commit message, it should point to the board rather than driver: dac.
E.g.
board: mcxn10: add nxp dac support

**Comment by ZhaoxiangJin** [comment]
> Could you please rephrase the commit message, it should point to the board rather than driver: dac. E.g. board: mcxn10: add nxp dac support

Hi @marcusfolkesson, thanks for your comment here, could you please give your reason here? And I would like to share some examples of what I've seen. They all used **samples: drivers: xxx: xxx** format.
image
image
From the Zephyr doc description, the **area** domain is used to indicate where the change was changed, so, I think using **samples: drivers: xxx: xxx** format is better than **board: mcxn10: add nxp dac support** format, because other users can easily know this changed code located at area samples/drivers/dac, and from the **summary of change** domain, the user can know this change is used to support frdm_mcxn947 dac example.
image

**Review by danieldegrasse — DISMISSED** [review]

**Review by danieldegrasse — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Comment by ZhaoxiangJin** [comment]
Could anyone help to merge this PR? thanks in advance.

**Comment by decsny** [comment]
> Could anyone help to merge this PR? thanks in advance.

have to wait at least 33 more hours to allow reviews 

https://[zephyrproject-rtos.github.io/zephyr-merge-list/](https://zephyrproject-rtos.github.io/zephyr-merge-list/)

**Review by martinjaeger — DISMISSED** [review]

**Comment by ZhaoxiangJin** [comment]
To resolve conflicts, forced pushed just now.

**Review by martinjaeger — DISMISSED** [review]

**Review by danieldegrasse — DISMISSED** [review]

**Comment by ZhaoxiangJin** [comment]
conflict again, updated and force pushed.

**Review by danieldegrasse — APPROVED** [review]

**Comment by ZhaoxiangJin** [comment]
Hi @martinjaeger, help to review, thanks, NXP frdm_mcxn947 board related files are too prone to conflicts.

**Review by martinjaeger — APPROVED** [review]

**Comment by ZhaoxiangJin** [comment]
Can anyone help merge this PR? Thanks.

**Pull request merged**
