### PR TITLE
drivers: pm: add pm_policy_state_lock for drivers

### PR DESCRIPTION
**Pull request by AlessandroLuo**
Added pm_policy_state_lock to prevent memory power off during data transfer

### CODE REVIEW

**Review by RichardSWheatley — APPROVED** [review]

**Review by aaronyegx — APPROVED** [review]
LGTM.

**Comment by RichardSWheatley** [comment]
> The following west manifest projects have been modified in this Pull Request:
> 
> | Name | Old Revision | New Revision | Diff |
> | ---- | ------------ | ------------ |------|
> | hal_ambiq | https://github.com/zephyrproject-rtos/hal_ambiq/commit/df4a9863f87cf75dc0b4a8e47483c87363d0e8f0 | https://github.com/zephyrproject-rtos/hal_ambiq/commit/d3092f9b82874a1791baa3ac41c3795d108fbbdb (main) | [zephyrproject-rtos/hal_ambiq@df4a9863..d3092f9b](https://github.com/zephyrproject-rtos/hal_ambiq/compare/df4a9863f87cf75dc0b4a8e47483c87363d0e8f0..d3092f9b82874a1791baa3ac41c3795d108fbbdb) |
> 
> *Note: This message is automatically posted and updated by the Manifest GitHub Action.* 

@zeonchew thus change in the HAL must first be made to Ambiqsuite.

We are not supposed to be allowing differences in HALs.

**Comment by zeonchew** [comment]
> > The following west manifest projects have been modified in this Pull Request:
> > 
> > 
> > 
> > Name
> > Old Revision
> > New Revision
> > Diff
> > 
> > 
> > 
> > 
> > hal_ambiq
> > [zephyrproject-rtos/hal_ambiq@df4a986](https://github.com/zephyrproject-rtos/hal_ambiq/commit/df4a9863f87cf75dc0b4a8e47483c87363d0e8f0)
> > [zephyrproject-rtos/hal_ambiq@d3092f9](https://github.com/zephyrproject-rtos/hal_ambiq/commit/d3092f9b82874a1791baa3ac41c3795d108fbbdb) (main)
> > [zephyrproject-rtos/hal_ambiq@df4a9863..d3092f9b](https://github.com/zephyrproject-rtos/hal_ambiq/compare/df4a9863f87cf75dc0b4a8e47483c87363d0e8f0..d3092f9b82874a1791baa3ac41c3795d108fbbdb)
> > 
> > 
> > 
> > _Note: This message is automatically posted and updated by the Manifest GitHub Action._
> 
> @zeonchew thus change in the HAL must first be made to Ambiqsuite.
> 
> We are not supposed to be allowing differences in HALs.

Apologies for the wrong flow. Let me do the backporting to Ambiqsuite immediately.

**Comment by kartben** [comment]
This introduced a warning/error due to pm_state now being unused in SPI driver
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11473956312/job/31929160542#step:12:1

@AlessandroLuo

**Comment by AlessandroLuo** [comment]
> This introduced a warning/error due to pm_state now being unused in SPI driver https://github.com/zephyrproject-rtos/zephyr/actions/runs/11473956312/job/31929160542#step:12:1
> 
> @AlessandroLuo

@kartben already a PR for this https://github.com/zephyrproject-rtos/zephyr/pull/80275

**Pull request merged**
