### PR TITLE
net/ip: fix input packet filtering criteria

### PR DESCRIPTION
**Pull request by ghost**
The "is this packet for us?" filter in net_ipv4_input() has a minor
logic error which fails to discard many packets which are.. not for us.

Fixes: #14647

Signed-off-by: Charles E. Youse <charles.youse@intel.com>

### CODE REVIEW

**Comment by gnuless** [comment]
@dgloeck @jukkar I haven't tested these changes, but I believe they are correct. I'd appreciate it if you could verify.

**Review by jukkar — CHANGES_REQUESTED** [review]
We should never get into this function if the network packet destination IPv{4|6} address is not ours. Those things are already checked in ipv4.c:net_ipv4_input() line 211 and ipv6.c:net_ipv6_input() line 462 before the connection.c:net_conn_input() is called.
Could you elaborate how did you see this issue, perhaps attach pcap file that shows what the packet looks like?

Edit: as the bug was about IPv4 broadcast address, then ignore my references for IPv6 above. Anyway, we have a check for broadcast addresses in ipv4.c line 211, could you check what it does wrong in that line?

**Review by tbursztyka — DISMISSED** [review]

**Comment by gnuless** [comment]
@jukkar I believe there's a flaw in the logic of that filter that makes it too permissive. The && at the end of line 212 should be a ||. Basically, there are four criteria checked on the input packet.

1. It's for a unicast or broadcast address that we care about (my_addr)
2. It's for a multicast address we care about (addr_mcast)
3. It's an all-subnet UDP broadcast but we're not doing DHCP
4. It's a TCP packet that arrived at a broadcast address assigned to the incoming interface

Currently the logic says "drop the packet if it's (not #1 and not #2), and (either #3 or #4).
I think the logic should say "drop the packet if it's (not #1 and not #2), OR (either #3 or #4).

As it stands, any packet that gets through L2 that doesn't violate the case-specific restrictions outlined by #3 and #4 will get passed to the upper layers, if I'm reading this right.

**Comment by dgloeck** [comment]
e82769c596249884aa9f240f1e551540667b3a37 works, no more bogus ICMP replies

**Review by jukkar — APPROVED** [review]
Thanks Charles!

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
