### PR TITLE
drivers: timer: extend nrf_rtc_timer to handle overflow

### PR DESCRIPTION
**Pull request by ankuns**
This is equivalent of https://github.com/zephyrproject-rtos/zephyr/pull/39099 PR
which has been merged and then reverted https://github.com/zephyrproject-rtos/zephyr/pull/41342

### CODE REVIEW

**Comment by carlescufi** [comment]
Do Not Merge until the BabbleSim hardware models have been updated.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
I wonder why we're not catching the missing RTC overflow handling in the [hw models](https://github.com/BabbleSim/ext_NRF52_hw_models) in this PR. Bluetooth tests should fail, I have no idea why they don't. @aescolar any ideas?

**Comment by ahasztag** [comment]
I've added a pull request adding overflow event and trigger overflow task to Babblesim: https://github.com/BabbleSim/ext_NRF52_hw_models/pull/24

**Review by nordic-krch — APPROVED** [review]

**Review by jciupis — APPROVED** [review]

**Comment by carlescufi** [comment]
Retested running all bsim tests to make sure they are all fine.

**Pull request merged**
