### PR TITLE
tests: socket: poll, select: Fix non-blocking timing tests

### PR DESCRIPTION
**Pull request by pfalcon**
The original test assumed that non-blocking select call would return
immediately, but actually it can be preempted by higher-priority
thread. So, we can account that it may possibly be delayed by a
scheduler quant of time (but otherwise we assume that testing
environment is light on other threads and their work, and one
quant is the most we can be delayed by).

Also, enable CONFIG_QEMU_TICKLESS_WORKAROUND. Most other
timing-related tests have this enabled, and it may affect
stability of QEMU testing too.

Fixes: #12994

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
>  but actually it can be preempted by higher-priority
thread

BTW this is not actually what I think is happening. We're not scheduling another thread, we're just getting a timer interrupt during the call which advances the system clock by whatever granularity the timer interrupt runs at (10ms)

**Comment by pfalcon** [comment]
> we're just getting a timer interrupt during the call which advances the system clock by whatever granularity the timer interrupt runs at (10ms)

Ok, now I got it. I thought I account for this using "1" (not 0) in `zassert_true(tstamp <= 1, "");` I might imagine that we "long enough" scheduling quantum, to avoid scheduling overheads, but somehow it didn't occur to me that we might have "pretty low resolution" timing source too, though in retrospect it's indeed pretty obvious to tie both to the same timer interrupt.

Ok, let me update the commit message.

**Comment by pfalcon** [comment]
Ok, updated both description and the test itself, to use `<= FUZZ` instead of magic `<= 1+ FUZZ`, hope it won't start to fail again due to that ;-). Also did the same for tests/net/socket/poll, which used exactly the same code patterns.

And I guess we should explicitly document that k_uptime_get/k_uptime_get_32 even though returns time in milliseconds, doesn't have to have millisecond *resolution*.

**Review by nashif — APPROVED** [review]

**Review by andyross — APPROVED** [review]
FWIW: a more robust way to do this check would be to make sure the calling thread is cooperative and at the highest priority (which eliminates the "another thread may preempt" problem) and test the timing with k_cycle_get_32() which is finer than tick resolution now on all systems.

**Pull request merged**
