### PR TITLE
Bluetooth: L2CAP: ECRED fixes

### PR DESCRIPTION
**Pull request by Vudentz**

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]
Should this be backported to stable releases? If so, please add the appropriate labels.

**Review by joerchan — APPROVED** [review]

**Comment by jhedberg** [comment]
@Vudentz which releases should this be backported to? Please add the labels for those (the automatic backport PR creation works again, but not for the generic "Backport" label)

**Comment by Vudentz** [comment]
> @Vudentz which releases should this be backported to? Please add the labels for those (the automatic backport PR creation works again, but not for the generic "Backport" label)

Ive added the version where ECRED support has already been introduced.

**Comment by joerchan** [comment]
AFAIK ECRED was first introduced in the 2.3 release, should we add it there as well?

**Comment by carlescufi** [comment]
> AFAIK ECRED was first introduced in the 2.3 release, should we add it there as well?

Backports only go back 2 releases.

**Pull request merged**
