### PR TITLE
 tests/drivers/counter/counter_basic_api  for rtc and timer counters

### PR DESCRIPTION
**Pull request by FRASTM**
When testing the tests/drivers/counter/counter_basic_api on stm32 boards when RTC is enabled, 
it is also possible to run the test on timer counter.
This is done when _also_ enabling all the timer counter on stm32 boards in each board overlay file:

-  nucleo_f091rc.overlay
-  nucleo_f103rb.overlay
-  nucleo_f207zg.overlay 
-  nucleo_f429zi.overlay 
-  nucleo_f746zg.overlay 
-  nucleo_g071rb.overlay  
-  nucleo_g474re.overlay   
-  nucleo_h743zi.overlay     
-  nucleo_l152re.overlay    
-  nucleo_wb55rg.overlay   
-  stm32f3_disco.overlay  
-  stm32h735g_disco.overlay  
-  stm32h747i_disco_m7.overlay
- nucleo_wl55jc

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
See comment on commit "tests: drivers: counter running on stm32 timer-counter instances"

**Comment by FRASTM** [comment]
Rebase on 81872eb7015f745127841c0a1fee96aa1d2d52d9

**Comment by FRASTM** [comment]
CI failure : see https://github.com/zephyrproject-rtos/zephyr/pull/56947

**Comment by FRASTM** [comment]
rebase on 63ed1d977a2b47d1820447f34ac5c9c8ed30f7ca after updating the modules/hal/stm32

**Comment by gmarull** [comment]
> CI failure : build failed on `west build -p auto -b mimxrt1060_evk tests/drivers/counter/counter_basic_api` does not depend on the PR Probably due to commit [a5fd0d1](https://github.com/zephyrproject-rtos/zephyr/commit/a5fd0d184a15d0af52599e0f5f5af880f353c6d4) of the PR #51217 @gmarull could you please have a look

FYI https://github.com/zephyrproject-rtos/zephyr/pull/57026

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
