### PR TITLE
soc: added I2C_1 labels for kl2x

### LINKED ISSUE #21275: kl2x soc fixup is missing I2C_1 labels
**Describe the bug**
soc/nxp_kinetis/kl2x/dts_fixup.h is missing labels for I2C_1 

**To  Reproduce**
1. enable CONFIG_I2C and CONFIG_I2C_1 in a project using frdm_kl25z board
2. west build .
3.  error: 'DT_I2C_MCUX_1_BASE_ADDRESS' undeclared here (not in a function); did you mean 'DT_I2C_MCUX_0_BASE_ADDRESS'?
   .base = (I2C_Type *)DT_I2C_MCUX_ ## n ## _BASE_ADDRESS, \

**Expected behavior**
The app should compile without errors.

**Impact**
Showstopper

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Toolchain Zephyr SDK

### PR DESCRIPTION
**Pull request by vladoatanasov**
Added I2C_1 labels to dts_fixup file for kl2x soc

Closes https://github.com/zephyrproject-rtos/zephyr/issues/21275

### CODE REVIEW

**Comment by carlescufi** [comment]
@vladoatanasov you can find tips on how to fix the CI issues here:
https://docs.zephyrproject.org/latest/contribute/index.html#contribution-tools-and-git-setup

**Comment by carlescufi** [comment]
@vladoatanasov please rebase on top of master instead of merging, so you end up with a single commit in the Pull Request. Also check your git credentials (`user.name` and `user.email` in your `~/.gitconfig`), they need to match the Signed-off-by line.

**Comment by vladoatanasov** [comment]
> @vladoatanasov please rebase on top of master instead of merging, so you end up with a single commit in the Pull Request. Also check your git credentials (`user.name` and `user.email` in your `~/.gitconfig`), they need to match the Signed-off-by line.

Thanks for the tips, should be all good now

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Thanks @vladoatanasov for the fix! Code changes look good, but the commit message needs to be amended.
```
added I2C_1 labels for kl2x soc in dts_fixup.h

Signed-off-by: Vladimir Atanasov <vlado.atanasov@gmail.com>

added I2C_1 labels for kl2x soc
```
Will you please remove the lines after the Signed-off-by?

**Comment by vladoatanasov** [comment]
> Thanks @vladoatanasov for the fix! Code changes look good, but the commit message needs to be amended.
> 
> ```
> added I2C_1 labels for kl2x soc in dts_fixup.h
> 
> Signed-off-by: Vladimir Atanasov <vlado.atanasov@gmail.com>
> 
> added I2C_1 labels for kl2x soc
> ```
> 
> Will you please remove the lines after the Signed-off-by?

Fixed, sorry about that, it was automatically generated from the squish I executed

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
