### PR TITLE
kernel: update z_arch_switch() documentation

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Clarify the intended design and how to implement optimally.

Relates to: #19759

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by gnuless** [comment]
Have we abandoned the idea of just passing z_arch_switch() a pair of `struct k_thread` pointers?

**Comment by gnuless** [comment]
If `switch_handle` is meant to be a stack pointer, then don't pretend it's some opaque type that architectures are allowed to do whatever they want with.  Call it `stack_pointer`.

**Review by ghost — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by andrewboie** [comment]
Updated; added comments on how to use ___thread_t_switch_handle_OFFSET instead of de-referencing switched_from all the way. @andyross please let me know if I got this right or if there's anything else worth adding.

**Comment by andrewboie** [comment]
also @vonhust FYI -- see #19952 , ARC code should do this as well instead of NULL checking.

**Comment by gnuless** [comment]
OR we could just change `z_arch_switch()` to work for the general case, rather than make everybody bend over backwards to accommodate the special case where all the context is a stack pointer?

**Comment by gnuless** [comment]
_but muh Linux!_
```
`	/*
	 * void __switch_to(struct thread_info *prev,
	 *      	    struct thread_info *next,
	 *		    struct task_struct *tsk) ;
	 */
```

**Review by ghost — CHANGES_REQUESTED** [review]
I would like someone to justify these semantics of `z_arch_switch()` before we bless them in the documentation.

**Comment by andrewboie** [comment]
> OR we could just change `z_arch_switch()` to work for the general case, rather than make everybody bend over backwards to accommodate the special case where all the context is a stack pointer?

My understanding from offline discussion with @andyross is that supporting the stack switching scheme makes some optimizations possible on Xtensa which would not be if xtensa stored all its context in the thread struct.

With #19952 in place, I don't feel any more that we need to re-implement anyone's current z_arch_switch() implementation, other than applying the same fix to ARC (instead of the NULL check it has now). I think we can move on to other matters.

**Comment by gnuless** [comment]
> My understanding from offline discussion with @andyross is that supporting the stack switching scheme makes some optimizations possible on Xtensa which would not be if xtensa stored all its context in the thread struct.

So then Xtensa can store a stack pointer in its k_thread (which it does, in the void *switch_handle) and use some form of offset addressing to get it, rather than forcing everyone else to play games.

That's the general case - "give me some k_threads and I'll get/store what I need from them", not, "let's optimize for the case where all we need is a stack pointer!".

Your own protection code on x86 could benefit from storing more context than a stack pointer (like, CR3) in the thread struct,  I mean, since we've resorted to counting instructions in context switches..

**Comment by andrewboie** [comment]
> So then Xtensa can store a stack pointer in its k_thread (which it does, in the void *switch_handle) and use some form of offset addressing to get it, rather than forcing everyone else to play games.
> 
> That's the general case - "give me some k_threads and I'll get/store what I need from them", not, "let's optimize for the case where all we need is a stack pointer!".

@gnuless This is really a discussion for you and @andyross I'm Swiss neutrality at this point. You guys can hash it out here. I don't see anything particularly onerous about the stack-based method FWIW, this seems to me a six-of-one, half-dozen-of-the-other. But I don't have a stake in this, you guys hash it out.

> Your own protection code on x86 could benefit from storing more context than a stack pointer (like, CR3) in the thread struct, I mean, since we've resorted to counting instructions in context switches..

Can you point me to specifics on this? I'm happy to address this but I'm not 100% sure what you're referring to.

**Comment by gnuless** [comment]
> @gnuless This is really a discussion for you and @andyross I'm Swiss neutrality at this point. 

No need to play Switzerland.  I'll play the Vichy and sell my soul for filthy lucre.

**Review by ghost — APPROVED** [review]
At least I get to live in up in Morocco.

**Comment by gnuless** [comment]
> Can you point me to specifics on this? I'm happy to address this but I'm not 100% sure what you're referring to.

You mean like the part where you call `z_x86_swap_update_page_tables()` with a pointer to the incoming `k_thread`?  And then dereference that `k_thread` to find a member called called `stack_obj` which you use to find the page tables for the thread?

Try moving that to the `z_arch_switch()` structure.  Now you have to repeat your 'adjustment' of `switch_handle` on the incoming thread _to find data in the the thread struct_ like **everybody else with anything but trivial context they can push on the stack** does.

Tsk, tsk, Andrew.  How dare you want more context than the general registers.  I give you two demerits.

**Comment by gnuless** [comment]
Really, CR3 should be simply stored in the task struct and it should be loaded directly.  If you're worried about unnecessary TLB flushes, use the G flag on global pages which is expressly for that purpose.  Similarly, store the kernel stack there and don't make the load of the kernel stack dependent on a conditional branch.

Ordinarily these are not things that I would care about, EXCEPT that I was handed an argument earlier today about how _one additional indirection_ (to deal with the `z_arch_switch()` mis-specification) was unacceptable on the context-switching path.

**Comment by andrewboie** [comment]
> Really, CR3 should be simply stored in the task struct and it should be loaded directly. If you're worried about unnecessary TLB flushes, use the G flag on global pages which is expressly for that purpose. Similarly, store the kernel stack there and don't make the load of the kernel stack dependent on a conditional branch.

I see it now, yes this could be optimized by caching CR3 and updating it if it's not the same between incoming/outgoing.

**Comment by gnuless** [comment]
> My understanding from offline discussion with @andyross is that supporting the stack switching scheme makes some optimizations possible on Xtensa which would not be if xtensa stored all its context in the thread struct.

What I am suggesting does not, by any means, preclude Xtensa or anyone else from storing context on the stack if they want to.  I merely state that

`void z_arch_switch(struct k_thread *, struct k_thread *)`  

is a better generalization.  It's even better on Xtensa -- it requires the addition of (no pun intended) _one_ addition instruction to the `xtensa_switch` code but **eliminates** other arithmetic generated by the compiler in the calling sequence to `z_arch_switch()`.  Someone, somewhere, has to compute the offset of the `switch_handle` member; the current structure merely hides the fact that the compiler has to do it instead of the assembly.  Simply declare a `stack_pointer` member in `struct k_thread` and let the assembly do the offset arithmetic.

**So at best, the use of `z_arch_switch()` in its present configuration is not an optimization, it's a wash.**  I can even imagine that, recast to take `k_thread *` arguments, someone could micro-optimize @andyross -style, and `xtensa_switch` would a lose an instruction or two.
 
But the real problem is, that even if it did require an extra instruction or two for Xtensa, the abstraction is too specific; it implicitly assumes that:

1. there is no need for the switch function to access the outgoing context, despite the fact that part of its job is to save the outgoing context, and
2. a simple opaque word value is sufficient information to restore the incoming context

This imposes an additional cost on architectures/implementations that stray from the simplistic "all I need is a stack pointer for my context" model.

> With #19952 in place, I don't feel any more that we need to re-implement anyone's current z_arch_switch() implementation, other than applying the same fix to ARC (instead of the NULL check it has now). I think we can move on to other matters.

I vehemently disagree.  For architectures that need more than just one opaque pointer as context, or wish to store context somewhere off-stack for other reasons (i.e., @andrewboie's memory protection code), we need to respecify the interface.

The current "workarounds" for this in ARC and x86 clearly demonstrate this: not only does the compiler do unnecessary arithmetic in the calling sequence to `z_arch_switch()`, the switching assembly then has to "undo" that arithmetic.  The fix in #19952 is a *clever* workaround, but it's still a *workaround*, and it's making a mockery of the idea of a `switch_handle` as an abstraction, instead taking advantage of the fact that it is a member of the desired `k_thread`, breaking the abstraction entirely.

There is simply no reason why `z_arch_switch()` is tailored as it is to the special case when there's no benefit to specifying it that way; on the contrary, it leads to suboptimal sequences and broken abstraction for everything but that special case.

**Comment by gnuless** [comment]
So just to summarize.  If we change to `void z_arch_switch(struct k_thread *, struct k_thread *)` we have these objective benefits:

1. have no impact, or possibly a positive impact, on the `xtensa_switch` sequence
2. avoid awkard workaround instruction sequences in the ARC architectures and x86 architectures
3. reduce the number of instructions generated in `do_swap` when invoking `z_arch_switch()`
4. eliminate a member of k_thread (`switch_handle`) and the need to update it in the interrupt path

What are the downsides?

**Comment by vonhust** [comment]
> also @vonhust FYI -- see #19952 , ARC code should do this as well instead of NULL checking.

Understood,  will change after #19952 is merged

**Review by andyross — APPROVED** [review]
+1 for the doc changes, obviously.

I'm not sure I understand the depth of the argument here.  At the level of implementation, the difference between the two APIs is a constant integer offset on the second argument of the function.  Either can be pretty trivially implemented in terms of the other.  If there's consensus on the choice, I don't see why we can't do it that way.

I'd much rather the argument be about moving to stack frame storage for contexts (at least on x86 and Xtensa, I don't know ARC well[1]), which is the metaphor the original API was designed to encourage.  While porting a z_swap() style switch might be simpler as a programming task, there are real and non-trivial benefits to stacked contexts.

But as for the API?  Yeah, sure.

[1] FWIW: ARM too (which doesn't support switch as it has no need, but will someday if it does SMP) has hardware support for partial frame stacking that would work more naturally by leaving the interrupted frames on their own stacks.  Again, this isn't a weird or unique thing to z_arch_switch().  It's a very common paradigm.

**Comment by andyross** [comment]
Picking out one technical bit:

 >  Your own protection code on x86 could benefit from storing more context than a stack pointer (like, CR3) in the thread struct, I mean, since we've resorted to counting instructions in context switches..

Why not just push CR3 to the stack?  I mean, it's not like this is a fundamentally different concept, you can put data anywhere you want.  The core benefit to doing it on the stack is that (1) the hardware on almost all architectures has already done some of it for you, and (2) you don't need access to the current thread pointer on interrupt entry and can avoid the somewhat complicated assembly code needed to extract it.  If you follow the code on x86_64 and count instructions, you can see that the number of instructions required to affect the context switch is just a tiny number (four, in fact) higher than the number of instructions required to spill and fill each register.  There aren't even any logic branches!  The jump from the user code to the kernel switch routine is an inline CALL that also has the side effect of pushing the return address for us.

I mean... there's a real technical argument here, and at this point I know I won't win it, but there are better ways to do this, and z_arch_switch() was designed for the benefit of the better scheme.

But sure, it can work under a thread based one too.

**Comment by andrewboie** [comment]
> Why not just push CR3 to the stack?

@andyross yeah this was pretty much how I was contemplating fixing this.
Push CR3 onto the stack at the beginning of z_arch_swap().
Then on the way out, pop it back into a register, compare with current CR3 value, update if necessary.

Given that this code only runs when KPTI is *disabled* (not the case for any of our current boards as they are all Meltdown vulnerable), this fix isn't high on my priority list, but that's how I'd imagine I'd do it.

I'd also push/pop _main_tss.esp0 values.

If there's a strong argument that thread-based switching is clearly better than stack-based switching, at this time I do not see it.

**Comment by gnuless** [comment]
> Why not just push CR3 to the stack? I mean, it's not like this is a fundamentally different concept, you can put data anywhere you want.

Well, typically the stack pointer and CR3 change together, atomically, because the stack you want is only visible in the target context's page tables.

**Comment by gnuless** [comment]
> If there's a strong argument that thread-based switching is clearly better than stack-based switching, at this time I do not see it.

That's NOT the argument that I'm making.  I'm saying that `z_arch_switch()` in its present form is unnecessarily biased towards that mechanism.  The two different forms of `z_arch_switch()` are nearly isomorphic.  You can translate either presentation to the other with little difficulty.  You can do stack-based or thread-based context switching with either.  For stack-based switching, they're essentially equivalent in terms of cost.  For thread-based switching, however, the `switch_handle` form is cumbersome and comes at a cost.  If the general, straightforward solution is also the less burdensome for all conceivable scenarios, I'm not sure what the argument is for using the specific version that has known costs in present (not imaginary) use cases could be.

**Comment by andrewboie** [comment]
> That's NOT the argument that I'm making. I'm saying that z_arch_switch() in its present form is unnecessarily biased towards that mechanism. 

Thinking aloud, we could perhaps define some mutually exclusive Kconfigs and have something like

```
#ifdef CONFIG_SWITCH_THREAD
extern void z_arch_switch_thread(struct k_thread *incoming, struct k_thread *outgoing);
#endif
#ifdef CONFIG_SWITCH_STACK
extern void z_arch_switch_stack(void *switched_to, void *switched_from)
#endif
```

Which arches could select as needed.

But I mean, I'm still baffled at your point of view.
Unlike me, you already knew that this was really intended for stack-based switching from the get-go, you told me as much in an email last week.
And just now you also agree that these are isomorphic.
So why did you decide to do a thread-based z_arch_swap() for x86 long instead of a stack based one??? This seems like a problem of your own making. If this is just an elaborate way of making some point about the abstract-ness of the interface there are better ways of communicating this..

**Comment by gnuless** [comment]
> Thinking aloud, we could perhaps define some mutually exclusive Kconfigs and have something like
> 
> ```
> #ifdef CONFIG_SWITCH_THREAD
> extern void z_arch_switch_thread(struct k_thread *incoming, struct k_thread *outgoing);
> #endif
> #ifdef CONFIG_SWITCH_STACK
> extern void z_arch_switch_stack(void *switched_to, void *switched_from)
> #endif
> ```

No, no, no.  That sort of special-casing is precisely what I'm trying to eliminate!  We need fewer special cases, fewer convoluted constructions, not more.

> So why did you decide to do a thread-based z_arch_swap() for x86 long instead of a stack based one???

Because that was the intent of its creators - that's why they have `callee_save` and other fields architecturally defined.  If you meant why did I create `z_arch_switch()` to make it stack-based, it's because was a trivial transformation of existing, working code to go from swap to switch and I wasn't going to rewrite it all, especially when I'm not entirely sold that the stack thing is the best approach.  But again, this isn't an argument about that. 

> you already knew that this was really intended for stack-based switching from the get-go

I didn't.  I wrote a `swap()` function in the original.  For why `switch` follows the same scheme, see above.

> But I mean, I'm still baffled at your point of view.

Then I'm explaining it poorly.

**Comment by andrewboie** [comment]
>  If you meant why did I create z_arch_switch() to make it stack-based, it's because was a trivial transformation of existing, working code to go from swap to switch and I wasn't going to rewrite it all

Alright, that's fair.

> No, no, no. That sort of special-casing is precisely what I'm trying to eliminate! We need fewer special cases, fewer convoluted constructions, not more.

My thinking was that this would not be invasive since z_arch_switch() is invoked in just one spot in ksched.h. And then they could be documented as being specific to stacks/threads rather than left vague. But I am not attached to this, other ideas lets consider them.

For now, I'm inclined to merge this patch as it provides some useful context to the switch function, such that people doing arch ports in the future may have an easier time.

**Comment by andrewboie** [comment]
Also let me take another stab at the problem statement as you see it @gnuless :

We have an API for context switching which on the surface appears to be an abstraction to let the arch code do context switching as it sees fit, but actually is really designed for stack-based switching. Doing this with thread pointers has unexpected complications and some minor inefficiencies and this API definition should be made more specific to its intended purpose.

If I've got that right, then I think there is a corollary: we have two arch ports that do thread-based switching (ARC, x86 long). If we revise the API to clearly indicate that this is a mechanism for stack-based switching, what do we do with these?

As far as the fate of z_arch_swap(), I opened an enhancement GH the other day to convert all remaining arches to switch see #19932 , I'd like to see swap eventually purged.

**Comment by gnuless** [comment]
> If I've got that right, then I think there is a corollary: we have two arch ports that do thread-based switching (ARC, x86 long). If we revise the API to clearly indicate that this is a mechanism for stack-based switching, what do we do with these?

I'd say move them to stack-based switching then.  Rename `switch_handle` to `stack_pointer` even, and be very explicit that we do our context storage on the stack.  That's fine.  In that case, I'd **still** argue to change the arguments to `k_thread *`:  the argument for that is:

1. it does not impose any additional costs in the existing implementations. we're just changing where the offset computation occurs (in the switch proper rather than the caller of switch),
2. it does not require convoluted (if clever) tricks to get more information if we need to restore the context.

#2 is not a "but maybe someday we might..." over-engineering thing.  Think again of caching CR3 -- I don't know if you saw my previous comment but storing it on the stack will impose limitations that we probably don't want to live with in perpetuity (namely, that the outgoing and incoming contexts must both have mapping for the incoming thread's stack -- you can't get at CR3 if it's not...).  That's just one example.  There might be others that crop up later.

Short story: changing the API slightly in this way costs nothing, results in something that is more obviously understood (oooh, that's a STACK POINTER! I get it) and is future proof in a straightforward way (need a new data member? no tricks required).  

That's really the entirety of my point.... 

.... I told you I was explaining it badly.

> For now, I'm inclined to merge this patch as it provides some useful context to the switch function, such that people doing arch ports in the future may have an easier time.

Yeppers, no problems here.  Documentation good.  I've said my piece about the specification.

**Comment by gnuless** [comment]
> I mean... there's a real technical argument here, and at this point I know I won't win it, but there are better ways to do this, and z_arch_switch() was designed for the benefit of the better scheme.

Yeah, I'm not necessarily making the point that we should be storing the context in the `k_thread`.  I'm 98% sold on that, your points are valid.  It's just about the arguments to `z_arch_switch()` being too limiting for some realistic cases.

**Comment by andrewboie** [comment]
Very very good point here.
Can't pop the new cr3 off the incoming stack if it's not in the address space. It only works now because we have identity page tables. Still contemplating this but it's been on my mind.

On Oct 21, 2019 3:28 PM, "Charles E. Youse" <notifications@github.com> wrote:

Why not just push CR3 to the stack? I mean, it's not like this is a fundamentally different concept, you can put data anywhere you want.

Well, typically the stack pointer and CR3 change together, atomically, because the stack you want is only visible in the target context's page tables.

**Comment by andyross** [comment]
> Can't pop the new cr3 off the incoming stack if it's not in the address space

FWIW: the address space of all z_arch_switch'd stacks is going to be the kernel space already, so it's a non-issue for the specific API we're talking about.  It's true that there's some work to do on interrupt entry if a userspace context was interrupted, but because of the address space change required by KPTI, we have to take that cost under all circumstances anyway.  That is: the trampoline code needs to save the interrupted CR3 somewhere that is neither the kernel stack nor the thread struct initially, so the final destination doesn't matter much at all.  Realistically the entry code would stick it in a register and save off the original register contents somewhere in the trampoline memory, at which point we can store it wherever we want in kernel-address-space half of interrupt entry.

Again, memory is memory.  It's not like indirecting off the stack pointer instead of a GPR creates fundamental logic problems.

**Comment by gnuless** [comment]
> FWIW: the address space of all z_arch_switch'd stacks is going to be the kernel space already

That's true *now*.  It is by no means a safe assumption that all kernel stacks for every thread are (or should be visible) from every other thread context, kernel-space or no.  And I'm not talking about whacky schemes-- even Unix processes from the very early days had kernel stacks that were only visible from their own contexts.

Zephyr's own memory protection and security models are very much works in progress, with new information and new requirements appearing all the time.  Why paint ourselves into a corner?

**Comment by gnuless** [comment]
> Push CR3 onto the stack at the beginning of z_arch_swap().  Then on the way out, pop it back into a register, compare with current CR3 value, update if necessary.

> I'd also push/pop _main_tss.esp0 values.

Another argument against this strategy is that we're forced -- unnecessarily -- to take unchanging data about a thread and write it onto the stack and read it off the stack.  Why are we taking, known, static values about a thread (which could easily be stored in, and referenced in, their `k_thread`) and instead 'caching' them on the stack ...?  These gymnastics are only necessary because we're trying to insist that the context-switching primitive use only the stack in its operation.

**Comment by gnuless** [comment]
> That is: the trampoline code needs to save the interrupted CR3 somewhere that is neither the kernel stack nor the thread struct initially, so the final destination doesn't matter much at all.

I don't see this at all.  CR3 is basically a static attribute of a `k_thread`.  Transition to the kernel via the trampoline doesn't have to save CR3 anywhere.  We know which thread we interrupted.

But this is a digression...

**Comment by andrewboie** [comment]
> It's true that there's some work to do on interrupt entry if a userspace context was interrupted, but because of the address space change required by KPTI, we have to take that cost under all circumstances anyway. 

I think we will be OK - regardless of whether KPTI is in effect or not, we will always end up on a kernel stack, this is handled I believe correctly by existing code. If KPTI is disabled, there's still an automatic stack switch to the kernel stack on IRQs due to us setting the esp0 pointer in _main_tss. We shouldn't ever end up in a situation where we are in z_arch_swap()/z_arch_switch() on a user mode stack; this would be a DoS concern since a thread could constuct a stack context which faults when the kernel switching code in supervisor mode tries to push more stuff onto it.

My intention for virtual address spaces was that the kernel stacks would always be in the kernel's half of memory and global to all address spaces. I think we're OK for this particular scenario.

> Another argument against this strategy is that we're forced -- unnecessarily -- to take unchanging data about a thread and write it onto the stack and read it off the stack. Why are we taking, known, static values about a thread (which could easily be stored in, and referenced in, their k_thread) and instead 'caching' them on the stack ...?

If we can show that this is faster when we have a thread pointer available (and I think it is) then this is a good example. Because we'd only need logic in the second half of the function when we restore context. I can put together a prototype of both approaches for fixing this on 32-bit to illustrate, I can spend some time on this when I get back from France.

**Pull request merged**
