### PR TITLE
board: arm: black_f407zg_pro: Initial support 

### PR DESCRIPTION
**Pull request by jukkar**
Add support for black_f407zg_pro board which is based on stm32f407zg soc.

### CODE REVIEW

**Comment by erwango** [comment]
@jukkar can you rebase and rework to comply with :
#24097 
#24446
#24434

**Comment by jukkar** [comment]
Rebased and updated according to comments

**Review by erwango — APPROVED** [review]
LGTM, but we'll need to synchronize with on going https://github.com/zephyrproject-rtos/zephyr/pull/24396.
Similar impact than SPI/UART/I2C, but additionally, you'll need to disabled can1 in dts.

**Comment by erwango** [comment]
Please rebase following merge of https://github.com/zephyrproject-rtos/zephyr/pull/24396

**Comment by jukkar** [comment]
Updated according to comments.

**Review by erwango — APPROVED** [review]

**Pull request merged**
