### PR TITLE
Fix for:  mcumgr over serial does not add CRC to length of packet len

### PR DESCRIPTION
**Pull request by de-nordic**
Corrected documentation and fix in code.

https://github.com/zephyrproject-rtos/zephyr/issues/39546

### CODE REVIEW

**Comment by de-nordic** [comment]
Example of echo response with correct packet length:
```
$$ sudo ~/go/bin/mcumgr --loglevel=debug -t 1200 --conntype serial --connstring dev=/dev/ttyACM0,baud=115200 echo hello
DEBU[2021-11-05 12:33:25.113] Using connection profile: name=unnamed type=serial connstring=dev=/dev/ttyACM0,baud=115200
DEBU[2021-11-05 12:33:25.114] {add-nmp-listener} [serial_sesn.go:213] seq=66
DEBU[2021-11-05 12:33:25.114] Encoded &{NmpBase:{hdr:{Op:2 Flags:0 Len:0 Group:0 Seq:66 Id:0}} Payload:hello} to:
00000000  a1 61 64 65 68 65 6c 6c  6f                       |.adehello|
DEBU[2021-11-05 12:33:25.115] Encoded:
00000000  02 00 00 09 00 00 42 00  a1 61 64 65 68 65 6c 6c  |......B..adehell|
00000010  6f                                                |o|
DEBU[2021-11-05 12:33:25.115] Tx NMP request: 00000000  02 00 00 09 00 00 42 00  a1 61 64 65 68 65 6c 6c  |......B..adehell|
00000010  6f                                                |o|
DEBU[2021-11-05 12:33:25.115] Base64 encoding request:
00000000  02 00 00 09 00 00 42 00  a1 61 64 65 68 65 6c 6c  |......B..adehell|
00000010  6f                                                |o|
DEBU[2021-11-05 12:33:25.115] Tx serial
00000000  06 09                                             |..|
DEBU[2021-11-05 12:33:25.115] Tx serial
00000000  41 42 4d 43 41 41 41 4a  41 41 42 43 41 4b 46 68  |ABMCAAAJAABCAKFh|
00000010  5a 47 56 6f 5a 57 78 73  62 38 45 4a              |ZGVoZWxsb8EJ|
DEBU[2021-11-05 12:33:25.115] Tx serial
00000000  0a                                                |.|
DEBU[2021-11-05 12:33:25.122] Rx serial:
00000000  06 09 41 42 51 44 41 41  41 4b 41 41 42 43 41 4c  |..ABQDAAAKAABCAL|
00000010  39 68 63 6d 56 6f 5a 57  78 73 62 2f 2f 64 6c 41  |9hcmVoZWxsb//dlA|
00000020  3d 3d                                             |==|
DEBU[2021-11-05 12:33:25.122] Decoded input:
00000000  03 00 00 0a 00 00 42 00  bf 61 72 65 68 65 6c 6c  |......B..arehell|
00000010  6f ff                                             |o.|
DEBU[2021-11-05 12:33:25.122] rx nmp response: 00000000  03 00 00 0a 00 00 42 00  bf 61 72 65 68 65 6c 6c  |......B..arehell|
00000010  6f ff                                             |o.|
DEBU[2021-11-05 12:33:25.123] Received nmp rsp: &{NmpBase:{hdr:{Op:3 Flags:0 Len:10 Group:0 Seq:66 Id:0}} Payload:hello Rc:0}
DEBU[2021-11-05 12:33:25.123] {remove-nmp-listener} [serial_sesn.go:213] seq=66
hello
```

Decoded rx paket:
```
$$ echo ABQDAAAKAABCAL9hcmVoZWxsb//dlA== | base64 -d | hexdump -C
00000000  00 14 03 00 00 0a 00 00  42 00 bf 61 72 65 68 65  |........B..arehe|
00000010  6c 6c 6f ff dd 94                                 |llo...|
```
clearly shows 0x0014 as packet length

**Review by nordicjm — APPROVED** [review]

**Review by rerickson1 — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
Please add this to the release notes

**Review by mniestroj — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Comment by de-nordic** [comment]
> 
> 
> Please add this to the release notes

Done.

**Comment by de-nordic** [comment]
@carles added release notes, please re-review.

**Review by rerickson1 — APPROVED** [review]

**Comment by de-nordic** [comment]
@carles ping.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
