### PR TITLE
Revert "zefi.py: Use cross compiler while building zephyr"

### LINKED ISSUE #31517: UP² broken (git bisect findings inside)
**Describe the bug**
Any samples running on UP² that has a console output should work, but it does not anymore.

**To Reproduce**

I tried the tests/arch/x86/info sample
up_squared board  (so x86_64) on multiboot (zephyr.strip)

**Expected behavior**
A lot of output on the multiboot, acpi and RTC

**Impact**
I cannot test my work on UP² atm, and I am using it extensively

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain:Zephyr SDK
 - Commit SHA: ef1b4d45b0ae1fe3cfd9e85d45acdf595a23a3b1

**Additional context**

I ran a git bisect, and it finds the commit 5c47bbc5010d98c6f6d795aa6d268138c3463bbd

It previously was commit 3660040e22042e0e67005da0a7229fc224e089d0 which was the same before it got reverted.

### PR DESCRIPTION
**Pull request by finikorg**
Fixes broken Up2 and EHL.

This reverts commit 513b9f598fc1135219d555013e8aa821447662d9.

Fixes: #31517

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]
@finikorg I needed to revert both Andrew's PR (the revert is already merged upstream) and this zefi PR for the images to be correct again.

**Comment by jhedberg** [comment]
@finikorg seems like you forgot the Signed-off-by line (which is why the Compliance check fails)

**Comment by jhedberg** [comment]
For reference, without this revert the EFI BIOS on EHL throws this error: 
```
Could not boot image: Exec format error (http://ipxe.org/2e008081)
```

**Review by galak — CHANGES_REQUESTED** [review]
It feels like reverting this PR isn't needed.  Is there any understanding why the host x86 `gcc` is ok, but the sdk `x86_64-zephyr-elf-objcopy` and `x86_64-zephyr-elf-gcc` are not?

**Comment by finikorg** [comment]
> It feels like reverting this PR isn't needed. Is there any understanding why the host x86 `gcc` is ok, but the sdk `x86_64-zephyr-elf-objcopy` and `x86_64-zephyr-elf-gcc` are not?

I have not stated that! The patch breaks build for efi images, that's why I am reverting it.

**Comment by galak** [comment]
> I have not stated that! The patch breaks build for efi images, that's why I am reverting it.

Sure, but the difference with and without your revert is the use of the host gcc/objcopy v the SDK version.  Is there any understanding of what issue might exist with the SDK x86_64 gcc/objcopy.

**Comment by finikorg** [comment]
> > I have not stated that! The patch breaks build for efi images, that's why I am reverting it.
> 
> Sure, but the difference with and without your revert is the use of the host gcc/objcopy v the SDK version. Is there any understanding of what issue might exist with the SDK x86_64 gcc/objcopy.

There seems to be missing parameters: https://github.com/zephyrproject-rtos/zephyr/commit/513b9f598fc1135219d555013e8aa821447662d9#r46237858

**Comment by galak** [comment]
@finikorg I think you are correct about the SDK objcopy not supporting the proper formats.

I wonder about something like:

```
diff --git a/arch/x86/zefi/zefi.py b/arch/x86/zefi/zefi.py
index f2d54cb9ed..d3514391a8 100755
--- a/arch/x86/zefi/zefi.py
+++ b/arch/x86/zefi/zefi.py
@@ -127,7 +127,7 @@ def build_elf(elf_file):
                     "zefi.elf"], check = True)
 
     # Convert it to a PE-COFF DLL.
-    cmd = [args.objcopy,
+    cmd = [args.objcopy, "--target=efi-app-x86_64",
         "-j", ".text", "-j", ".reloc", "-j", ".data",
         "zefi.elf", "zephyr.efi"]
     verbose(" ".join(cmd))
diff --git a/boards/x86/ehl_crb/CMakeLists.txt b/boards/x86/ehl_crb/CMakeLists.txt
index fa6ae14ba8..a4887e50f1 100644
--- a/boards/x86/ehl_crb/CMakeLists.txt
+++ b/boards/x86/ehl_crb/CMakeLists.txt
@@ -3,7 +3,7 @@ if(CONFIG_BOARD_EHL_CRB)
 set_property(GLOBAL APPEND PROPERTY extra_post_build_commands
   COMMAND ${PYTHON_EXECUTABLE} ${PROJECT_SOURCE_DIR}/arch/x86/zefi/zefi.py
   -c ${CMAKE_C_COMPILER}
-  -o ${CMAKE_OBJCOPY}
+  -o objcopy
   -f ${PROJECT_BINARY_DIR}/${CONFIG_KERNEL_BIN_NAME}.elf
   $<$<BOOL:${CMAKE_VERBOSE_MAKEFILE}>:--verbose>
   WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
diff --git a/boards/x86/up_squared/CMakeLists.txt b/boards/x86/up_squared/CMakeLists.txt
index 2d3cf9af0b..298a615f8a 100644
--- a/boards/x86/up_squared/CMakeLists.txt
+++ b/boards/x86/up_squared/CMakeLists.txt
@@ -3,7 +3,7 @@ if(CONFIG_BOARD_UP_SQUARED)
 set_property(GLOBAL APPEND PROPERTY extra_post_build_commands
   COMMAND ${PYTHON_EXECUTABLE} ${PROJECT_SOURCE_DIR}/arch/x86/zefi/zefi.py
   -c ${CMAKE_C_COMPILER}
-  -o ${CMAKE_OBJCOPY}
+  -o objcopy
   -f ${PROJECT_BINARY_DIR}/${CONFIG_KERNEL_BIN_NAME}.elf
   $<$<BOOL:${CMAKE_VERBOSE_MAKEFILE}>:--verbose>
   WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
```

**Review by jhedberg — CHANGES_REQUESTED** [review]
I'd suggest going with the fix from #31540 instead

**Comment by nashif** [comment]
obsoloted by #31540

**Pull request closed without merging**
