### PR TITLE
ci: move to using SDK 0.11.0

### PR DESCRIPTION
**Pull request by galak**
Move to docker image 0.11.1 to get final release of SDK 0.11.0.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by tyrantlizard77 — COMMENTED** [review]
wasn't there a hack put somewhere to skip Cortex-R? that should be removed

**Comment by galak** [comment]
> wasn't there a hack put somewhere to skip Cortex-R? that should be removed

Don't know, but will let the Cortex-R guys submit a PR to change things once this is merged.

**Comment by nashif** [comment]
> Don't know, but will let the Cortex-R guys submit a PR to change things once this is merged.

boards/arm/qemu_cortex_r5/board.cmake

```
# FIXME++: This forces the CI to use the Xilinx QEMU included in the Zephyr SDK
#          0.11.0-alpha-8 for testing. This should be removed once the Zephyr
#          SDK 0.11.0 release is mainlined.
set(CI_QEMU_PATH
  /opt/sdk/zephyr-sdk-0.11.0-alpha-8/sysroots/x86_64-pokysdk-linux/usr/bin
  )

if(EXISTS ${CI_QEMU_PATH})
  set(ENV{QEMU_BIN_PATH} ${CI_QEMU_PATH})
endif()
# FIXME--
```


should be removed.

**Comment by galak** [comment]
> > Don't know, but will let the Cortex-R guys submit a PR to change things once this is merged.
> 
> boards/arm/qemu_cortex_r5/board.cmake
> 
> ```
> # FIXME++: This forces the CI to use the Xilinx QEMU included in the Zephyr SDK
> #          0.11.0-alpha-8 for testing. This should be removed once the Zephyr
> #          SDK 0.11.0 release is mainlined.
> set(CI_QEMU_PATH
>   /opt/sdk/zephyr-sdk-0.11.0-alpha-8/sysroots/x86_64-pokysdk-linux/usr/bin
>   )
> 
> if(EXISTS ${CI_QEMU_PATH})
>   set(ENV{QEMU_BIN_PATH} ${CI_QEMU_PATH})
> endif()
> # FIXME--
> ```
> 
> should be removed.

Removed.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
> Removed.

Thanks!
Going forward, let's never do that again...

**Review by nashif — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
