### PR TITLE
Driver: Flash: STM32: Do not use semaphore if multithreading isn't defined

### PR DESCRIPTION
**Pull request by Benichou34**
In STM32 flash driver, do not use semaphore if multithreading isn't defined.
If multithreading isn't defined, a call to sem_give function generates a hardware fault exception.

### CODE REVIEW

**Comment by galak** [comment]
Curious why you have multithreading off, mind letting us know what situation you are using Zephyr w/o multithreading enabled?

**Comment by erwango** [comment]
Aside from the multithreading on/off disussion, another use case for semaphore to limit flash access is dual core chips.

**Comment by Benichou34** [comment]
> Curious why you have multithreading off, mind letting us know what situation you are using Zephyr w/o multithreading enabled?
We using MCUboot with Zephyr. In this case, MCUboot is building without multithreading.

**Comment by jli157** [comment]
> > Curious why you have multithreading off, mind letting us know what situation you are using Zephyr w/o multithreading enabled?
> 
> We using MCUboot with Zephyr. In this case, MCUboot is building without multithreading.

I also found MCUBoot can't boot up if multithreading is disabled on STM32F4 boards.

**Comment by nashif** [comment]
@jli157 

> I also found MCUBoot can't boot up if multithreading is disabled on STM32F4 boards.

Mcuboot should also work with multithreading enabled. the only reason multi-threading is disabled is to save some flash on small devices. So if you have no space issues, you should be able to enable it and use the drivers.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@Benichou34, can you rebase this PR?

**Comment by Benichou34** [comment]
> @Benichou34, can you rebase this PR?
@erwango Done

**Comment by erwango** [comment]
@galak, seems the discussions on this is done now. Is it still 'DNM' from your point of view?

**Comment by aescolar** [comment]
@Benichou34 What is the status of this PR? Nothing seems to have happened for quite a while. If you do not plan to continue with it, would you consider closing it?
@galak is the DNM still relevant?

**Review by nashif — APPROVED** [review]

**Comment by erwango** [comment]
@galak, @nashif can we merge this one now?

**Review by Laczen — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
