### PR TITLE
cmake: DTS post-processing of ELF file depends on CONFIG_HAS_DTS

### LINKED ISSUE #34416: Configuration HAS_DTS has no function, preventing compile for vendors without device tree
DTS has been made mandatory, however certain vendors do not want to go down that road.
Where an empty device tree in certain configurations is sufficient, in others, the number of hacks needed to compile is unreasonable.

**Expected behavior**
It should be possible to use- and unset the existing CONFIG_HAS_DTS to compile zephyr on vendor platforms.

**Impact**
Currently a local hack is used to compile without DTS. This can quickly be made into a PR if accepted (the "if/endif" added to CMakeLists.txt):

```
if(CONFIG_HAS_DTS)
  # dev_handles.c is generated from ${ZEPHYR_PREBUILT_EXECUTABLE} by
  # gen_handles.py
  add_custom_command(
    OUTPUT dev_handles.c
    COMMAND
    ${PYTHON_EXECUTABLE}
    ${ZEPHYR_BASE}/scripts/gen_handles.py
    --output-source dev_handles.c
    --kernel $<TARGET_FILE:${ZEPHYR_PREBUILT_EXECUTABLE}>
    --zephyr-base ${ZEPHYR_BASE}
    DEPENDS ${ZEPHYR_PREBUILT_EXECUTABLE}
    )
  set_property(GLOBAL APPEND PROPERTY GENERATED_KERNEL_SOURCE_FILES dev_handles.c)
endif()
```

### PR DESCRIPTION
**Pull request by mtpr-ot**
Only run gen_handles.py if CONFIG_HAS_DTS is set. This enables vendors
without device tree implementations to compile without the generated
dependencies.

Fixes #34416.

Signed-off-by: Morten Priess <mtpr@oticon.com>

### CODE REVIEW

**Comment by mtpr-ot** [comment]
Closed/reopened to rerun CI

**Comment by mtpr-ot** [comment]
Can anybody help with the CI errors? Is it because some configurations are using DTS, but somehow set CONFIG_HAS_DTS=n?

**Comment by tejlmand** [comment]
> Can anybody help with the CI errors? Is it because some configurations are using DTS, but somehow set CONFIG_HAS_DTS=n?

@pabigot can you assist ?

**Comment by pabigot** [comment]
> > Can anybody help with the CI errors? Is it because some configurations are using DTS, but somehow set CONFIG_HAS_DTS=n?
> 
> @pabigot can you assist ?

In `arch/Kconfig` the SPARC architecture doesn't have `select HAS_DTS`.  Adding a commit that "fixes" that would probably make it work.  Not sure why it isn't there @martin-aberg 

I suspect platforms that don't have devicetree aren't going to make it very far in the Zephyr of the future.  @galak @mbolivar-nordic FYI in case this is something to consider from an architectural level.

**Comment by mtpr-ot** [comment]
> In `arch/Kconfig` the SPARC architecture doesn't have `select HAS_DTS`. Adding a commit that "fixes" that would probably make it work. Not sure why it isn't there @martin-aberg

Thanks! I will add a commit with that selected.

**Comment by mtpr-ot** [comment]
> I suspect platforms that don't have devicetree aren't going to make it very far in the Zephyr of the future

I can understand that from a Zephyr architectural perspective. I will inform my colleagues of the deprecation, and hopefully we can go the DTS-way in the next generation.

**Comment by mbolivar-nordic** [comment]
> I suspect platforms that don't have devicetree aren't going to make it very far in the Zephyr of the future. @galak @mbolivar-nordic FYI in case this is something to consider from an architectural level.

That is my general impression as well, as documented in https://docs.zephyrproject.org/latest/guides/dts/design.html#single-source-for-all-hardware-information though this is ongoing work.

Basic things like "be able to create a struct device that isn't from devicetree" will continue to work "forever", though, as far as I know. I never use platforms without DTS though, not sure if we've got project level decisions made on the future of `CONFIG_HAS_DTS=n`.

**Review by tejlmand — APPROVED** [review]

**Comment by martin-aberg** [comment]
@pabigot Thank you for the heads-up regarding the missing `HAS_DTS`.

@mtpr-ot Thank you for the fix.

**Comment by mtpr-ot** [comment]
@pabigot, so is this acceptable for the time being?

**Review by pabigot — APPROVED** [review]
> @pabigot, so is this acceptable for the time being?

I don't like it, because it seems clear DTS is not an optional part of Zephyr, but until that's written into policy this seems the only way to make progress.  Presumably some day somebody will get rid of `CONFIG_HAS_DTS` entirely and the hack will be removed at that point.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
