### PR TITLE
soc/intel_adsp: Robustify logging code

### LINKED ISSUE #29430: up_squared_adsp: Sanitycheck can not run test case on Up_Squared_ADSP board
**Describe the bug**
Sanitycheck can run on up_squared_adsp board.

**To Reproduce**
**Run this command:**
sanitycheck -W -p up_squared_adsp --device-testing -T samples/hello_world/ --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/up_squared_adsp/tools/up_squared_adsp_flash.sh, /home/ztest/work/sof/rimage/keys/otc_private_key.pem" --device-serial-pty="/home/ztest/work/ambient/set_ambient /home/ztest/work/zephyrproject/zephyr/boards/xtensa/up_squared_adsp/tools/mbterm.py" -x=CONFIG_IPM=y -x=CONFIG_CONSOLE=y -x=CONFIG_LOG_PRINTK=n

See sanitycheck will skip sample

**Expected behavior**
sanitycheck can run normal on adsp board

**Impact**
All test cases can not be run on up_squared_adsp

**Logs and console output**
DEBUG   - platform filter: ['up_squared_adsp']
DEBUG   -     arch_filter: None
DEBUG   -      tag_filter: None
DEBUG   -     exclude_tag: None
INFO    - Building initial testcase list...
DEBUG   - up_squared_adsp           samples/hello_world/sample.basic.helloworld        SKIPPED: Excluded tags per platform (only_tags)
INFO    - 1 test configurations selected, 1 configurations discarded due to filters.

Device testing on:

| Platform        | ID   | Serial device   |
|-----------------|------|-----------------|
| up_squared_adsp |      |                 |

INFO    - Adding tasks to the queue...
DEBUG   - DONE FEEDING

DEBUG   - running footprint_reports
INFO    - 0 of 0 tests passed (0.00%), 0 failed, 1 skipped with 0 warnings in 2.32 seconds
INFO    - In total 0 test cases were executed on 1 out of total 297 platforms (0.34%)
INFO    - 0 tests executed on platforms, 0 tests were only built.

Hardware distribution summary:

| Board           | ID   |   Counter |
|-----------------|------|-----------|
| up_squared_adsp |      |         0 |

**Environment (please complete the following information):**
OS: Fedora28
Toolchain: Zephyr-sdk-0.11.3
Commit ID: a8a92ce

### PR DESCRIPTION
**Pull request by andyross**
[Note: This is just the logging code.  I still need to resurrect and push a quick addition of "west flash" integration and some documentation before sanitycheck integration can be considered complete.  Just an issue of typing though.]

The existing implementation of the adsplog.py script worked fine for
individual runs (e.g. when running specific code) but had no support
for detecting system reset events and thus could not be used for
monitoring applications like test automation.  It also could not
handle the case where a rapid log burst would overflow the buffer
before being noticed at the client.  Also, the protocol here was also
rife with opportunities for race conditions.  Fix all that up via what
is mostly a rewrite of the script.  The protocol itself hasn't
changed, just the handling.

Also includes some changes to the trace_out.c code on the device side.
These are required to get ordering correct to make race conditions
tractably handleable on the reader side.

Some of the specific cases that are managed:

* There is a 0.4s backoff when a reset is detected.  Continuing to
  poll the buffer has been observed to hang the device (I'm fairly
  sure this is actually a hardware bug, reads aren't visible to the
  DSP software).

* The "no magic number" case needs to be reserved for detecting system
  reset.

* Slot data must be read BETWEEN two reads of the ID value to detect
  the case where the slot gets clobbered while being read.

* The "currently being filled" slot needs to always have an ID value
  that does not appear in sequence from the prior slot.

* We need to check the full history in the buffer at each poll to
  detect resets, which opens up a race between the read of the "next
  slot" (which is absent) and the full history retrieval (when it can
  now be present!).  Detect that.

* A null termination bug in the current output slot got fixed.

Broadly: this was a huge bear to make work.  It sounds like this
should be a simple protocol, but it's not in practice.

Also: clean up the error reporting in the script so it can handle new
PCI IDs being added, and reports permissions failures on the required
sysfs file as a human-readable error.

Fixes #29430

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Comment by nashif** [comment]
@jocelyn-li  can you please verify this fix?

**Comment by LeiW000** [comment]
I have just asked @KangJianX  to verifiy it.

**Comment by KangJianX** [comment]
@andyross  I verified this patch, sanitycheck can get multiple testing results, it is better than previously. But I check the result found  **handle.log is not correct**, the result is that I specific when used sanitycheck last time.

**Comment by andyross** [comment]
Add back the @finikorg 's flash script that got dropped a while back (slightly modified for current paths).  Add more detail to the documentation section.

@KangJianX: it seems to be working for me right now, can you revisit with the newer instructions I just pushed and see if that addresses your concerns?  Obviously reports of test failures should be separate bugs, I see a few of those have snuck in.

**Review by LeiW000 — COMMENTED** [review]
For the code itself, it look good to me.  Jian is still verifying it to confirm if the issue can be totally fixed with it

**Comment by KangJianX** [comment]
@andyross It seems not work.
I use command by your commit like: **twister -p intel_adsp_cavs15 --device-testing -T tests/kernel/semaphore/semaphore/ --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh, /home/ztest/work/sof/rimage/keys/otc_private_key.pem" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py"** 

Terminal log is:
INFO    - Zephyr version: zephyr-v2.4.0-2574-ge64f4f950e
INFO    - JOBS: 4
INFO    - Building initial testcase list...
INFO    - 1 test suites (1 configurations) selected, 0 configurations discarded due to filters.

Device testing on:

| Platform          | ID   | Serial device   |
|-------------------|------|-----------------|
| intel_adsp_cavs15 |      |                 |

INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue

ERROR   - intel_adsp_cavs15         tests/kernel/semaphore/semaphore/kernel.semaphore  FAILED: Timeout
ERROR   - see: /home/ztest/work/zephyrproject/zephyr/twister-out/intel_adsp_cavs15/tests/kernel/semaphore/semaphore/kernel.semaphore/handler.log
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    1
INFO    - 0 of 1 test configurations passed (0.00%), 1 failed, 0 skipped with 0 warnings in 96.38 seconds
INFO    - In total 23 test cases were executed, 0 skipped on 1 out of total 314 platforms (0.32%)
INFO    - 1 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board             | ID   |   Counter |
|-------------------|------|-----------|
| intel_adsp_cavs15 |      |         1 |
INFO    - Saving reports...
INFO    - Writing xunit report /home/ztest/work/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/ztest/work/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Writing JSON report /home/ztest/work/zephyrproject/zephyr/twister-out/twister.json
INFO    - Run completed

The handle.log:
ERROR: Cannot open b'/sys/bus/pci/devices/0000:00:0e.0/resource4' for reading.

**Comment by andyross** [comment]
>  ERROR: Cannot open b'/sys/bus/pci/devices/0000:00:0e.0/resource4' for reading.

That's covered in the documentation changes included in this PR.  Regular users can't do I/O to PCI devices. The earlier scheme used a separate utility to set a capability on the process so it could read from /dev/mem.  All this one requires is file I/O privileges to a file in sysfs.  But you do have to set it.

Just "`chmod 666 /sys/bus/pci/devices/0000:00:0e.0/resource4`" should be enough.  Or obviously you can run it as root.

The golden standard here would be to write a udev rule that detected the device by its PCI ID and set the group ownership of that file to some particular group like "adsplog", that it had group read privileges, and make sure your test user is a member.   But that's a sysadmin thing at the CI level and sort of out of scope.

**Review by nashif — APPROVED** [review]

**Pull request merged**
