### PR TITLE
net: lib: socketutils, sntp: Allow to build for CONFIG_POSIX_API

### PR DESCRIPTION
**Pull request by pfalcon**
socketutils and SNTP APIs were previously tested only with CONFIG_NET_SOCKETS_POSIX_NAMES. Make required changes for them to work with CONFIG_POSIX_API too (mostly, including POSIX headers in this case). Add CI cases to track this.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by jukkar** [comment]
> This is required to make it work with CONFIG_POSIX_API.

Why is that?

**Comment by pfalcon** [comment]
> Why is that?

Why is that is what exactly? This PR includes update for SNTP client sample, which doesn't build for CONFIG_POSIX_API without the preceding patch in this PR.

**Comment by jukkar** [comment]
> This is required to make it work with CONFIG_POSIX_API.

You said that this is required because of posix api option. So what kind of issues there are if that symbol is enabled?

**Comment by pfalcon** [comment]
> You said that this is required because of posix api option. So what kind of issues there are if that symbol is enabled?

With POSIX_API, only `zsock_*` functions are available. To make bare POSIX names available, it requires to include POSIX headers, and we don't want to introduce unneeded dependencies on POSIX subsys into other subsystems, like networking.

How it worked before is it was tested with only CONFIG_NET_SOCKETS_POSIX_NAMES=y, which is another, though adhoc, way to get get bare POSIX names, but which is not compatible with CONFIG_POSIX_API (because these 2 options define bare names in 2 different sets of headers, and of course if 2 get inadvertently included, there's a declaration conflicts). We discussed CONFIG_NET_SOCKETS_POSIX_NAMES vs CONFIG_POSIX_API matters thoroughly enough (I hope) over the last couple of months, so I would hope everyone is in loop.

**Comment by pfalcon** [comment]
(I see CI is red, will look into that.)

**Comment by pfalcon** [comment]
To get CI pass here (for newly enabled sample config), need to merge https://github.com/zephyrproject-rtos/zephyr/pull/18939 into this PR (done, CI started).

**Review by rveerama1 — APPROVED** [review]

**Review by jukkar — CHANGES_REQUESTED** [review]
> How it worked before is it was tested with only CONFIG_NET_SOCKETS_POSIX_NAMES=y, which is another, though adhoc, way to get get bare POSIX names, but which is not compatible with CONFIG_POSIX_API (because these 2 options define bare names in 2 different sets of headers, and of course if 2 get inadvertently included, there's a declaration conflicts)

I would prefer if we could use the posix function names here. Also we could add check into sockets.h so that if CONFIG_POSIX_API is enabled together with CONFIG_NET_SOCKETS_POSIX_NAMES=y, then we just do not create the posix socket function prototypes in socket.h. Wouldn't that solve the issue?

**Comment by pfalcon** [comment]
> I would prefer if we could use the posix function names here.

But see above - that means including references to POSIX subsystem (specifically, POSIX headers) into "net core". Previously, we avoided that, with POSIX being strictly a layer on top of "core net API", with "net core" not containing references to POSIX subsys. Are you sure you want to break that convention?

Another option is to redefine the scope of the SNTP lib, and say that it's not a "net core", but merely as "userspace convenience" lib. We already have precedents like that - just include/net/socketutils.h as included in this patch. I'd be very much +1 for such redefinition.

OTOH, SNTP still seems "special". I actually word on a patch to use SNTP to set POSIX real time clock on system startup.

@jukkar, Can you please weigh on these arguments and confirm that you'd like to go with inclusion of POSIX headers?

**Comment by pfalcon** [comment]
> Also we could add check into sockets.h so that if CONFIG_POSIX_API is enabled together with CONFIG_NET_SOCKETS_POSIX_NAMES=y, then we just do not create the posix socket function prototypes in socket.h. 

When the issue of POSIX subsys with "native BSD-like sockets" initially popped up, I made a call, whether we try to mask the issue for as long as possible, or vice-versa, expose it, setting 2 as not compatible. There was not much feedback, so I went for "fail fast" approach, because we already have to many dark corners to debug.

> Wouldn't that solve the issue?

No, because we do need "posix socket function prototypes", and they come from 2 different header sets in case of CONFIG_POSIX_API vs !CONFIG_POSIX_API.

**Review by jukkar — APPROVED** [review]

**Pull request merged**
