### PR TITLE
extensions.cmake: add two cc/compile_options callgraph comments

### PR DESCRIPTION
**Pull request by marc-hb**
This would have saved me about an hour exploring the code and piecing it
together.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by mbolivar — COMMENTED** [review]
I'm not sure about this one. I won't -1, but this feels like the sort of thing that is easy enough to grep for.

**Comment by marc-hb** [comment]
>  but this feels like the sort of thing that is easy enough to grep for

Absolutely; if everyone interested has about an hour to waste. Being new to this code this is approximately how long it took me. Don't forget there are many more functions than the ones I selected.

Now of course this entire framework should be some day properly documented in a new section in the developer guide, think something like PR #13805. However that's a longer term documentation project; this PR is just a quick fix to save questions on Slack and/or wasting time.

**Comment by SebastianBoe** [comment]
Improvements to the documentation are always welcome.

Did you discover this documentation:
https://github.com/zephyrproject-rtos/zephyr/pull/15377/files#diff-e64e7d3f59d40d3325fa7a458c531dd3R337

and would that have helped?

AFAICT what this ascii art is trying to convey is (attempted) documented there.

Perhaps the zephyr_* API should be referencing the zephyr_library_* API to ensure it is easier to discover.

In any case, we don't want to convey the same thing differently in two different places, so perhaps the ascii art should be moved to the zephyr_library_* API docs.

**Comment by marc-hb** [comment]
> Did you discover this documentation: https://github.com/zephyrproject-rtos/zephyr/pull/15377/files#diff-e64e7d3f59d40d3325fa7a458c531dd3R337 and would that have helped?

(This links fast forwards to the `1.2 zephyr_library_*` section in the same file)

Yes, I did read these comments. And then scroll up and read others. And then scroll down and read more. And then used grep and read more. And then I got tired of getting lost and drew this tiny "map"/cheat sheet. At the end of it all I thought it could save others time hence this PR.

Section `1.2 zephyr_library_` is specific to (surprise) `zephyr_library_` functions and located at line 330 so probably not the best introduction to the grander `zephyr_` scheme of things?

**Review by SebastianBoe — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
