### PR TITLE
tests: adc: Make project config file dependent on board.

### PR DESCRIPTION
**Pull request by m-kru**
Include project configuration file based on target board, not on ADC
resolution.

Signed-off-by: Michał Kruszewski <michal.kruszewski@nordicsemi.no>

### CODE REVIEW

**Comment by m-kru** [comment]
@nashif @tbursztyka

**Review by nashif — CHANGES_REQUESTED** [review]
what is the point of adding all those board configs when they are the same? I would prefer one single configuration that works for everyone and move the platforms related information to the board or SoC.

**Comment by nashif** [comment]
also, commenting the QMSI values out will just disable testing of those, not sure this is the right approach, I would remove those completely , so you can have 1 single prj.conf that works for everyone:


```
CONFIG_ADC=y
CONFIG_ZTEST=y
CONFIG_BATTERY_SENSE=y
```

**Comment by m-kru** [comment]
@nashif What do you mean by 
> move the platforms related information to the board or SoC.

    CONFIG_BATTERY_SENSE=y
is platform specific.

**Comment by nashif** [comment]
> move the platforms related information to the board or SoC.
> CONFIG_BATTERY_SENSE=y
> is platform specific.

Yes, I figured, but if the option is not available on other platforms, it just goes away, so you can keep it in here. Is this option always required for ADC on this platform? if yes, might have it part of the board configuration as well.

**Comment by m-kru** [comment]
@nashif So where should I put platform specific options that are not always required or the ones that are used to set some choice options, for example resolution?

**Comment by MaureenHelm** [comment]
> Is this option always required for ADC on this platform? if yes, might have it part of the board configuration as well.

Agree, see #4202

**Comment by nashif** [comment]
Closing this as it was dealt with in #4203 and #4202.

**Pull request closed without merging**
