### PR TITLE
MAINTAINERS: Add collaborator for OA TC6 and T1S driver (lan865x)

### PR DESCRIPTION
**Pull request by lmajewski**
I can help with maintaining this particular driver.

### CODE REVIEW

**Comment by lmajewski** [comment]
@MaureenHelm - gentle ping on this PR

**Comment by lmajewski** [comment]
> @MaureenHelm - gentle ping on this PR

Is there any issue with this PR?

**Review by carlescufi — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]
Needs to be rebased

**Comment by lmajewski** [comment]
@MaureenHelm - I've rebased it on the newest main.

**Review by kartben — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Review by aescolar — CHANGES_REQUESTED** [review]
Thanks @lmajewski, but first you need to be added as contributor to the project.
Please create a "Contributor Nomination" issue for that.
After that, adding a new area in the maintainers file and a new maintainer would need TSC approval.

**Comment by aescolar** [comment]
> @aescolar - please find the "Contributor Nomination" issue: #71616

Thanks @lmajewski , the TSC is having a face to face meeting this week, so it may take a bit longer than normally to get a response. If in 1 week you don't here anything please ping in that ticket.

**Comment by nashif** [comment]
those are instances of the ethernet subsystem, we do not maintain instances in the maintainer file, they will need to be part of a subsystem, i.e. ethernet. Until we have a better way for managing instances, i.e. driver implementation, I suggesy you add yourself as  contributor in the ethernet driver area.

**Review by decsny — APPROVED** [review]

**Comment by decsny** [comment]
@pdgendt you should add yourself next

**Review by MaureenHelm — APPROVED** [review]

**Comment by lmajewski** [comment]
@nashif @carlescufi - gentle ping on this patch...

**Review by aescolar — APPROVED** [review]

**Pull request merged**
