### PR TITLE
manifest: Bump libmetal and open-amp

### PR DESCRIPTION
**Pull request by carlocaione**
To v2024.05.0

### CODE REVIEW

**Comment by arnopo** [comment]
Hi @carlocaione 
building `samples/subsys/ipc/openamp_rsc_table/` generate following warning 
```
[24/182] Building C object zephyr/CMakeFiles/zephyr.dir/lib/open-amp/resource_table.c.obj
In file included from /zephyrproject/zephyr/lib/open-amp/./resource_table.h:11,
                 from /zephyrproject/zephyr/lib/open-amp/resource_table.c:30:
/zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/virtio.h:83:2: warning: #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined" [-Wcpp]
   83 | #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined"
      |  ^~~~~~~
[26/182] Building C object CMakeFiles/app.dir/src/main_remote.c.obj
In file included from /zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/rpmsg_virtio.h:19,
                 from /zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/open_amp.h:12,
                 from /zephyrproject/zephyr/samples/subsys/ipc/openamp_rsc_table/src/main_remote.c:16:
/zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/virtio.h:83:2: warning: #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined" [-Wcpp]
   83 | #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined"
      |  ^~~~~~~
      

```
The issue is linked to the replacement of `VIRTIO_DRIVER_ONLY `and  `VIRTIO_DEVICE_ONLY `by `VIRTIO_DRIVER_SUPPORT `and `VIRTIO_DEVICE_SUPPORT`      

I haven't found a clean way to fix it yet

**Comment by carlocaione** [comment]
> Hi @carlocaione building `samples/subsys/ipc/openamp_rsc_table/` generate following warning
> 
> ```
> [24/182] Building C object zephyr/CMakeFiles/zephyr.dir/lib/open-amp/resource_table.c.obj
> In file included from /zephyrproject/zephyr/lib/open-amp/./resource_table.h:11,
>                  from /zephyrproject/zephyr/lib/open-amp/resource_table.c:30:
> /zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/virtio.h:83:2: warning: #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined" [-Wcpp]
>    83 | #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined"
>       |  ^~~~~~~
> [26/182] Building C object CMakeFiles/app.dir/src/main_remote.c.obj
> In file included from /zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/rpmsg_virtio.h:19,
>                  from /zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/open_amp.h:12,
>                  from /zephyrproject/zephyr/samples/subsys/ipc/openamp_rsc_table/src/main_remote.c:16:
> /zephyrproject/modules/lib/open-amp/open-amp/lib/include/openamp/virtio.h:83:2: warning: #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined" [-Wcpp]
>    83 | #warning "VIRTIO_DRIVER_SUPPORT and/or VIRTIO_DEVICE_SUPPORT should be defined"
>       |  ^~~~~~~
>       
> ```
> 
> The issue is linked to the replacement of `VIRTIO_DRIVER_ONLY `and `VIRTIO_DEVICE_ONLY `by `VIRTIO_DRIVER_SUPPORT `and `VIRTIO_DEVICE_SUPPORT`
> 
> I haven't found a clean way to fix it yet

This is my fix https://github.com/zephyrproject-rtos/zephyr/pull/74186/commits/7da4a2cf09bed3aa2825ff74173c14ac7efedb44 as part of the Zephyr PR.

**Comment by carlocaione** [comment]
@arnopo your fix is working so I think it is worth to have an open-amp minor release for that. Still some tests on zephyr are failing with the new release.

**Comment by arnopo** [comment]
> @arnopo your fix is working so I think it is worth to have an open-amp minor release for that. 
I will send a PR  on open-amp.
>Still some tests on zephyr are failing with the new release.
Seem related to BT,  is rpmsg used in the test project?

**Comment by arnopo** [comment]
> > @arnopo your fix is working so I think it is worth to have an open-amp minor release for that.
> 
> I will send a PR on open-amp.

https://github.com/OpenAMP/open-amp/pull/596

**Comment by carlocaione** [comment]
@arnopo no idea and I don't even the hardware anymore to reproduce it. @Thalley @carlescufi anyone from Nordic who wants to take a look at this?

**Comment by Thalley** [comment]
> @arnopo no idea and I don't even the hardware anymore to reproduce it. @Thalley @carlescufi anyone from Nordic who wants to take a look at this?

Can you elaborate on what you'd like us to look at?

**Comment by arnopo** [comment]
> > @arnopo no idea and I don't even the hardware anymore to reproduce it. @Thalley @carlescufi anyone from Nordic who wants to take a look at this?
> 
> Can you elaborate on what you'd like us to look at?

Hello @Thalley ,

We need your assistance to understand what is failing during the bsim-test. The failure appears to be related to the update of the OpenAMP or libmetal library, but there is nothing evident in the test log. Can you help us investigate this issue?

https://github.com/zephyrproject-rtos/zephyr/actions/runs/9512500748/job/26220609947?pr=74186

**Comment by Thalley** [comment]
> > > @arnopo no idea and I don't even the hardware anymore to reproduce it. @Thalley @carlescufi anyone from Nordic who wants to take a look at this?
> > 
> > 
> > Can you elaborate on what you'd like us to look at?
> 
> Hello @Thalley ,
> 
> We need your assistance to understand what is failing during the bsim-test. The failure appears to be related to the update of the OpenAMP or libmetal library, but there is nothing evident in the test log. Can you help us investigate this issue?
> 
> https://github.com/zephyrproject-rtos/zephyr/actions/runs/9512500748/job/26220609947?pr=74186

The BSIM test that fails looks like it's failing on the nrf52_bsim which doesn't use this, so I think the failing BSIM test is unrelated to this PR. There has been a lot of fixes merged in the last 5 days, so I would suggest to retrigger the test to see if it still fails. 

For the logging issue I have no idea unfortunately. To make sure there's an issue, I would also retry that.

**Comment by arnopo** [comment]
Bsim tests still fail, but errors seem different. :worried:

**Comment by Thalley** [comment]
> Bsim tests still fail, but errors seem different. 😟

At least it's nRF53 failures this time :D Looks like segmentation faults - Should be possible to re-run those tests locally with Valgrind

**Comment by aescolar** [comment]
@carlocaione @arnopo 
```
==4312==    at 0x8121455: ept_cb (ipc_rpmsg_static_vrings.c:237)
==4312==    by 0x8157DBD: rpmsg_virtio_rx_callback (rpmsg_virtio.c:594)
==4312==    by 0x81565B9: virtqueue_notification (virtqueue.c:600)
==4312==    by 0x81215F1: mbox_callback_process (ipc_rpmsg_static_vrings.c:313)
==4312==    by 0x815AED8: work_queue_main (work.c:688)
==4312==    by 0x811E482: z_thread_entry (thread_entry.c:48)
```
The segfault happens because priv (ept->priv in caller) is null and being derefferenced.

**Comment by arnopo** [comment]
I think I have found the regression. 

I have updated the https://github.com/OpenAMP/open-amp/pull/596 adding
https://github.com/OpenAMP/open-amp/pull/596/commits/8d08fae0dac792ba21ae3b00c0745ae593f6df2f patch 

could you please update openamp module and rerun CI?

**Comment by carlocaione** [comment]
@arnopo done. Let's see.

**Comment by carlocaione** [comment]
@arnopo yeah, it looks fine now. If you push a new release I'll take that into the `zephyr-openamp` repo.

**Comment by arnopo** [comment]
> @arnopo yeah, it looks fine now. If you push a new release I'll take that into the `zephyr-openamp` repo.

Yes sure, we have to do more tests and add to v2024.05.01 release to fix this. I will ping you when ready. 
Your review on the https://github.com/OpenAMP/open-amp/pull/596 would be appreciate in this context.
Thanks in advance

**Comment by nashif** [comment]
@carlocaione  can you please update? the PRs were merged, so manifest needs to be updated.

**Comment by carlocaione** [comment]
> @carlocaione can you please update? the PRs were merged, so manifest needs to be updated.

@nashif you are rushing things. We have to wait for https://github.com/OpenAMP/open-amp/pull/596 to be merged, after that I have to fix https://github.com/zephyrproject-rtos/open-amp/pull/19 (that was supposed not to be merged) and after that we can update and merge this one.

**Comment by arnopo** [comment]
> > @carlocaione can you please update? the PRs were merged, so manifest needs to be updated.
> 
> @nashif you are rushing things. We have to wait for [OpenAMP/open-amp#596](https://github.com/OpenAMP/open-amp/pull/596) to be merged, after that I have to fix [zephyrproject-rtos/open-amp#19](https://github.com/zephyrproject-rtos/open-amp/pull/19) (that was supposed not to be merged) and after that we can update and merge this one.

the  [OpenAMP/open-amp#596](https://github.com/OpenAMP/open-amp/pull/596)  is no merged

**Review by arnopo — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Pull request merged**
