### PR TITLE
boards: nrf52840_pca10059: Enable ADC in DT

### LINKED ISSUE #17671: ADC not supported by nrf52840_pca10059 DTS file
**Describe the bug**
nrf52840_pca10059 (Dongle)'s [description page](https://docs.zephyrproject.org/latest/boards/arm/nrf52840_pca10059/doc/index.html) says it supports ADC, but its DTS file doesn't have a status describer like in [nrf52840_pca10056's](https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/nrf52840_pca10056/nrf52840_pca10056.dts#L106).

This leads to several compilation failures related to the ADC.

**To Reproduce**
1. Add `CONFIG_ADC=y` to `hello_world`'s config file
2. Run `west build -b nrf52840_pca10059`
3. See error

**Expected behavior**
Compile without failure.

**Impact**
Showstopper

**Console output**
```FAILED: zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_nrfx_saadc.c.obj 
ccache /home/joaocordeiro/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBUILD_VERSION=v1.14.1-rc1 -DKERNEL -DNRF52840_XXAA -D_FORTIFY_SOURCE=2 -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../../../kernel/include -I../../../arch/arm/include -I../../../include -I../../../include/drivers -Izephyr/include/generated -I../../../soc/arm/nordic_nrf/nrf52 -I../../../soc/arm/nordic_nrf/include -I../../../lib/libc/minimal/include -I../../../ext/hal/cmsis/Include -I../../../ext/hal/nordic/nrfx -I../../../ext/hal/nordic/nrfx/drivers/include -I../../../ext/hal/nordic/nrfx/hal -I../../../ext/hal/nordic/nrfx/mdk -I../../../ext/hal/nordic/. -isystem /home/joaocordeiro/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/include -isystem /home/joaocordeiro/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/include-fixed -Os -nostdinc -g -Wall -Wformat -Wformat-security -Wno-format-zero-length -imacros /home/joaocordeiro/zephyrproject/zephyr/samples/hello_world/build/zephyr/include/generated/autoconf.h -ffreestanding -Wno-main -fno-common -mthumb -mcpu=cortex-m4 -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -Wno-pointer-sign -Wno-unused-but-set-variable -fno-reorder-functions -fno-defer-pop -Werror=implicit-int -Wpointer-arith -ffunction-sections -fdata-sections -mabi=aapcs -march=armv7e-m -std=c99 -MD -MT zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_nrfx_saadc.c.obj -MF zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_nrfx_saadc.c.obj.d -o zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_nrfx_saadc.c.obj   -c /home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c
In file included from ../../../include/arch/arm/cortex_m/irq.h:17,
                 from ../../../include/arch/arm/arch.h:27,
                 from ../../../include/arch/cpu.h:17,
                 from ../../../include/kernel_includes.h:34,
                 from ../../../include/kernel.h:17,
                 from ../../../include/device.h:11,
                 from ../../../include/adc.h:16,
                 from /home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_context.h:11,
                 from /home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:8:
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c: In function 'init_saadc':
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:377:18: error: 'DT_NORDIC_NRF_SAADC_ADC_0_IRQ' undeclared (first use in this function); did you mean 'DT_NORDIC_NRF_I2C_I2C_0_IRQ'?
  NRFX_IRQ_ENABLE(DT_NORDIC_NRF_SAADC_ADC_0_IRQ);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/irq.h:256:43: note: in definition of macro 'irq_enable'
 #define irq_enable(irq) z_arch_irq_enable(irq)
                                           ^~~
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:377:2: note: in expansion of macro 'NRFX_IRQ_ENABLE'
  NRFX_IRQ_ENABLE(DT_NORDIC_NRF_SAADC_ADC_0_IRQ);
  ^~~~~~~~~~~~~~~
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:377:18: note: each undeclared identifier is reported only once for each function it appears in
  NRFX_IRQ_ENABLE(DT_NORDIC_NRF_SAADC_ADC_0_IRQ);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/irq.h:256:43: note: in definition of macro 'irq_enable'
 #define irq_enable(irq) z_arch_irq_enable(irq)
                                           ^~~
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:377:2: note: in expansion of macro 'NRFX_IRQ_ENABLE'
  NRFX_IRQ_ENABLE(DT_NORDIC_NRF_SAADC_ADC_0_IRQ);
  ^~~~~~~~~~~~~~~
In file included from ../../../include/arch/arm/arch.h:27,
                 from ../../../include/arch/cpu.h:17,
                 from ../../../include/kernel_includes.h:34,
                 from ../../../include/kernel.h:17,
                 from ../../../include/device.h:11,
                 from ../../../include/adc.h:16,
                 from /home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_context.h:11,
                 from /home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:8:
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:380:7: error: 'DT_NORDIC_NRF_SAADC_ADC_0_IRQ_PRIORITY' undeclared (first use in this function); did you mean 'DT_NORDIC_NRF_I2C_I2C_0_IRQ_PRIORITY'?
       DT_NORDIC_NRF_SAADC_ADC_0_IRQ_PRIORITY,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/arch/arm/cortex_m/irq.h:85:28: note: in definition of macro 'Z_ARCH_IRQ_CONNECT'
  z_irq_priority_set(irq_p, priority_p, flags_p); \
                            ^~~~~~~~~~
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:379:2: note: in expansion of macro 'IRQ_CONNECT'
  IRQ_CONNECT(DT_NORDIC_NRF_SAADC_ADC_0_IRQ,
  ^~~~~~~~~~~
In file included from ../../../include/adc.h:16,
                 from /home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_context.h:11,
                 from /home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:8:
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c: At top level:
/home/joaocordeiro/zephyrproject/zephyr/drivers/adc/adc_nrfx_saadc.c:397:28: error: 'DT_NORDIC_NRF_SAADC_ADC_0_LABEL' undeclared here (not in a function); did you mean 'DT_NORDIC_NRF_I2C_I2C_0_LABEL'?
 DEVICE_AND_API_INIT(adc_0, DT_NORDIC_NRF_SAADC_ADC_0_LABEL,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/device.h:107:11: note: in definition of macro 'DEVICE_AND_API_INIT'
   .name = drv_name, .init = (init_fn),     \
           ^~~~~~~~
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.10.0
 - Commit: 03a52401c6826511fc6fb9a9aecbefc72f092982 @ v1.14-branch

**Additional context**
I was able to compile it by adding this ADC status descriptor to the [DTS file](https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/nrf52840_pca10059/nrf52840_pca10059.dts):
```
&adc {
	status ="ok";
};
```

That way I was able to use P0.02, P0.29, and P0.31 as analog inputs.

### PR DESCRIPTION
**Pull request by carlescufi**
Enable the ADC in the basic DT configuration.

Fixes #17671

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Review by anangl — APPROVED** [review]

**Comment by carlescufi** [comment]
@galak I have had to revert your commit 5071eeec8bb101776db8640daafa8543cdcecc43 because that virtualcom is actually used, as seen when building the `samples/subsys/usb/console` sample for a Nordic board that supports USB:;

```
nrf52840_pca10059.dts.pre.tmp:5.9-13: ERROR (path_references): /chosen: Reference to non-existent node or label "usb_cdc"
```

**Comment by anangl** [comment]
@carlescufi 
> @galak I have had to revert your commit [5071eee](https://github.com/zephyrproject-rtos/zephyr/commit/5071eeec8bb101776db8640daafa8543cdcecc43) because that virtualcom is actually used

It seems that instead of reverting this commit, the overlay referring this no longer existing `usb_cdc` node (i.e. [this file](https://github.com/zephyrproject-rtos/zephyr/blob/312f05eaef21da538d6bde38248d4dfcbe9810bc/samples/subsys/usb/console/app.overlay)) should be removed. The app takes the name of the console device from the Kconfig option `CONFIG_UART_CONSOLE_ON_DEV_NAME` and this option is set in [proj.conf](https://github.com/zephyrproject-rtos/zephyr/blob/312f05eaef21da538d6bde38248d4dfcbe9810bc/samples/subsys/usb/console/prj.conf#L10).

**Comment by carlescufi** [comment]
> CONFIG_UART_CONSOLE_ON_DEV_NAME

Thanks @anangl, I've updated this as per your comments

**Comment by jfischer-phytec-iot** [comment]
@carlescufi see also https://github.com/zephyrproject-rtos/zephyr/pull/17661 and https://github.com/zephyrproject-rtos/zephyr/pull/17655

**Comment by carlescufi** [comment]
> @carlescufi see also #17661 and #17655

Right @jfischer-phytec-iot, so as per [this comment](https://github.com/zephyrproject-rtos/zephyr/pull/17661#issuecomment-513254183) we remove the .overlay, agreed?

**Review by jfischer-no — APPROVED** [review]

**Review by lemrey — APPROVED** [review]

**Pull request merged**
