### PR TITLE
SPI initialization fixes

### PR DESCRIPTION
**Pull request by mbolivar**
Fixes (well, once fix applied twice) to the init routines for new-style SPI drivers. Please see the commit log for a083c37 for details.

@ldts, @tbursztyka, am I missing something?

### CODE REVIEW

**Comment by mbolivar** [comment]
@superna9999 -- sorry, I should have pinged you on this as well.

**Review by galak — DISMISSED** [review]
Its annoying, but duplicate the commit message rather than referring to the other commit, its not going to necessarily be obvious in history what the reference to STM32 means.

**Review by tbursztyka — DISMISSED** [review]
Indeed, thanks!

**Review by superna9999 — APPROVED** [review]

**Comment by mbolivar** [comment]
> Its annoying, but duplicate the commit message rather than referring to the other commit, its not going to necessarily be obvious in history what the reference to STM32 means.

Done.

**Review by nashif — APPROVED** [review]

**Pull request merged**
