### PR TITLE
ci: add .codecov.yml for codecov.io configuration/ build with -O0

### LINKED ISSUE #5548: coverage should be collected from code built with -O0
Confirmed by @nashif in https://github.com/zephyrproject-rtos/zephyr/issues/5546#issuecomment-355027044 ,  we don't build coverage test with special compile options (which means they're built with -Os).

But "man gcov" says:

> You should compile your code without optimization if you plan to use
       gcov because the optimization, by combining some lines of code into one
       function, may not give you as much information ...

Indeed, a question was posed why we neither "hit" nor "miss" lines in the code which should be covered: https://github.com/zephyrproject-rtos/zephyr/issues/5546#issuecomment-355014291

lcov-generated stats also show white spots in those places: http://docs.zephyrproject.org/coverage/misc/printk.c.gcov.html , so it's not codecov.io.

I modified CMakeLists.txt locally:

~~~
-set_ifndef(OPTIMIZE_FOR_SIZE_FLAG  "-Os")
+set_ifndef(OPTIMIZE_FOR_SIZE_FLAG  "-O0")
~~~

and ran "sanitycheck -s tests/kernel/common/test -v --coverage" locally, confirming that the generated report doesn't have white spots in the discussed places. (attached, renamed to .txt due to github stupidity:
[printk.c.gcov.html.txt](https://github.com/zephyrproject-rtos/zephyr/files/1600952/printk.c.gcov.html.txt)
)

### PR DESCRIPTION
**Pull request by nashif**
This is the default config for codecov.io, we will exclude unrelated data once we have a good baseline.

Also build with -O0 to get more information. 
 
Fixes #5548

### CODE REVIEW

**Comment by pfalcon** [comment]
Typo fix in the commit message:

> default confif

**Comment by pfalcon** [comment]
> with the exclusion of tests/samples added for Zephyr.

We provably want to exclude 3rd-party libs too, unless we want to burden our CI with running their native testsuites.

**Comment by nashif** [comment]
> We provably want to exclude 3rd-party libs too, unless we want to burden our CI with running their native testsuites.

Right, lets do that step by step. I am learning lots of thing about our code by looking at the full picture right now, obviously the only coverage we get at the moment is with things we can build and run using the native_posix port, so it will be a while before we hit any of the HALs and other external libraries and subsystems.

**Review by pfalcon — APPROVED** [review]
Can't link to exactfile in codecov.io report, but this fixed printk.c coverage anomalies reported in https://github.com/zephyrproject-rtos/zephyr/issues/5546.
  
https://codecov.io/gh/zephyrproject-rtos/zephyr/pull/5542/changes#L104

**Pull request merged**
