### PR TITLE
manifest: Patch mbedtls

### PR DESCRIPTION
**Pull request by SebastianBoe**
Include permanent patch needed by TF-M.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
mbedtls patch with detailed information:

https://github.com/zephyrproject-rtos/mbedtls/pull/28

**Comment by SebastianBoe** [comment]
There is something strange going on with the mbedTLS version control.

I see there are two branches in https://github.com/zephyrproject-rtos/mbedtls.

zephyr and master.

Is master deprecated in favour of zephyr?

I thought we were renaming master to main.

If this PR is merged as-is it will do a lot more than just remove the static keyword.

**Comment by d3zd3z** [comment]
> Is master deprecated in favour of zephyr?

A branch called 'zephyr' has become the convention for modules that use upstream history, with a few extra commits merged in to make it compatible with Zephyr. The main branch will remain for mbed TLS 2.6.x, whereas the zephyr branch will hold the tree starting with Mbed TLS 3.0.0. This Zephyr branch will contain the upstream history, with our patches to make it work with Zephyr.

So, for changes that affect 'main' on Zephyr, they should go in the 'zephyr' branch. For changes on backports, the old 'master' may be needed.

Unfortunately, west's file doesn't show what branch the commits are from, so this isn't really made clear anywhere.

**Comment by SebastianBoe** [comment]
@d3zd3z , @microbuilder : Needs +1.

This has already been accepted, but it was applied on the wrong branch.

**Review by microbuilder — APPROVED** [review]

**Review by d3zd3z — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@carlescufi : Merge needed

**Pull request merged**
