### PR TITLE
subsys: Initiate to POST_KERNEL

### LINKED ISSUE #8199: Tests: Crypto: rand32 faults on nrf51_pca10028 and nrf52_pca10040
**Test location:** tests/crypto/rand32/

**Test identifier:** crypto.rand32.random_hw_xoroshiro.rand32

**Configuration file:** prj_hw_random_xoroshiro.conf

**Execution log:**
On nrf51_pca10028:

```
***** HARD FAULT *****
Executing thread ID (thread): 0x00000000
Faulting instruction address: 0xf3efb662
Fatal fault in ISR! Spinning...

```

On nrf52_pca10040:

```
***** MPU FAULT *****
Executing thread ID (thread): 0x00000000
Faulting instruction address: 0x20000cc0
Data Access Violation
Address: 0x9
Fatal fault in essential thread! Spinning...
```
**Latest Commit on which the test fails:** 265f502b8e48ba3299bfbbef7814cbab196af0b3

### PR DESCRIPTION
**Pull request by punitvara**
Change initialization from PRE_KERNEL_2 to
POST_KERNEL

Fixes #8199

Signed-off-by: Punit Vara <punit.vara@intel.com>

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
This was changed just recently to address another bug:
fcc56e315f1dcc0c25422cb528662fe8dfe0b059

**Review by lpereira — CHANGES_REQUESTED** [review]
Why would changing this to POST_KERNEL help with that crash?

All the entropy drivers are initialized in PRE_KERNEL_1; this being initialized in PRE_KERNEL_2 means that it'll be able to use the entropy drivers just fine to kick off the RNG.

The xoroshiro initialization is pretty trivial and does not require multithreading to be initialized: it just makes a call to entropy_get_entropy() and gives every thread in the system, current and future, access to the state semaphore.  All that it does is OK to be done in this context.

Are we hitting some issue because the bg_thread has to be running for some reason?  I worry that this change, even if it makes the bad behavior go away, is masking a more serious issue that we have to look into.

**Comment by andrewboie** [comment]
I'd like to understand why this change fixes the issue, it's not clear to me either.

**Comment by punitvara** [comment]
CC @ramakrishnapallala

 @lpereira @andrewboie the reason for failure is because of the following line in entropy_nrf5_get_entropy
 k_sem_take(&dev_data->sem_sync, K_FOREVER);

Here k_sem_take tries to pend the thread but we have not even called the  prepare_multithreading(dummy_thread) at this point of time, so it's crashing on k_sem_take.

So we have two options, either change the init to POST_KERNEL or don't call the entropy_get_entropy() from xoroshiro128_initialize().

**Comment by ramakrishnapallala** [comment]
@lpereira  If we have dependencies with PRE_KERNEL* then we can move the entropy_get_entropy() to xoroshiro128_next. please let me know if you have any concern.

**Comment by nashif** [comment]
please close this one if not relevant anymore.

**Comment by punitvara** [comment]
Will submit another PR to resolve this. Closing as of now.

**Comment by punitvara** [comment]
In current implementation of zephyr, interrupts are locked at reset are unlocked just before jumping to main. Xoroshiro driver requires interrupts to be fired at initialization which is currently at PRE_KERNEL_2. Because we will never get interrupt at PRE_KERNEL_2 stage, we have to push initialization to POST_KERNEL. Hence, reopening this pull request. Since I find that this is the only options. @nashif

**Comment by lpereira** [comment]
This isn't the right fix.  `__stack_chk_guard` is initialized in `_Cstart()` right after `PRE_KERNEL_2` is setup, but before `POST_KERNEL`.  Is this failing because `CONFIG_ENTROPY_HAS_DRIVER` is not defined, and `sys_rand32_get()` is being used to gather a random number during early boot (in `z_early_boot_rand32_get()`), or because of something else?

**Comment by AdithyaBaglody** [comment]
@lpereira what you are saying about the early boot is completely correct. If there is a need for the subsystem to be up at pre_kernel_2 then we should move it early_boot_rand32_get. 

But I don't see why a subsystem needs to be enabled before the kernel. This is a unique behavior for a subsystem. AFAIK we need to move this to post_kernel to make it similar to other subsystems and also without changing the rand32 function being used.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@lpereira this is IMHO the right fix. See my comment here: https://github.com/zephyrproject-rtos/zephyr/issues/8199#issuecomment-417887358. 
A separate PR to address the fact that there are still some issues with `z_early_boot_rand32_get()` on nRF.

**Comment by carlescufi** [comment]
@lpereira @AdithyaBaglody @nashif 
I see now that some configurations might require xoroshiro to be up pre-kernel, see here: https://github.com/zephyrproject-rtos/zephyr/pull/8207#pullrequestreview-126350299

In that case I suggest we go with option 2) in https://github.com/zephyrproject-rtos/zephyr/issues/8199#issuecomment-417887358

**Comment by carlescufi** [comment]
@lpereira 

>All the entropy drivers are initialized in PRE_KERNEL_1; this being initialized in PRE_KERNEL_2 means that it'll be able to use the entropy drivers just fine to kick off the RNG

No, because in the nRF case, the entropy driver uses a semaphore and the scheduler has not been initialized yet. That's why we have the special `z_early_boot_rand32_get()`

**Comment by lpereira** [comment]
I'm closing this PR as the proposed solution is invalid.  See discussion in #8199 for a proper fix.

**Pull request closed without merging**
