### PR TITLE
bluetooth: controller: Default stream count based upon app configs

### PR DESCRIPTION
**Pull request by rugeGerritsen**
When building ISO applications on a device that has the host and controller on the same core, the application developer shouldn't have to set controller specific configurations.

Without this change the samples iso_receive and iso_broadcast will fail to run on NRF52 series devices as the samples try to set up two streams but the controller is configured to support only one.

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]

**Comment by cvinayak** [comment]
If possible replace commit title to "Bluetooth: Controller:..."

**Comment by cvinayak** [comment]
@erbr-ot  or @thoh-ot  hope the changes to test conf files are ok?

**Review by thoh-ot — APPROVED** [review]

**Comment by rugeGerritsen** [comment]
> 2\. `BT_ISO_MAX_CIG`

@Thalley , I agree with your observations here. We should refine this further. To me it looks like we may need to change either controller or host configurations options:

As you mentioned, setting `BT_ISO_MAX_CHAN=2` indicates that you want to use at maximum two concurrent ISO streams, but not what type of streams. 
 - If all the controller features are enabled, it means it will assume worst case = expect any type of stream combination. That is, we need to allocate 2+2+2 controller streams.
 - If either of the controller features `BT_CTLR_ADV_ISO`, `BT_CTLR_SYNC_ISO` or `BT_CTLR_CONN_ISO` are disabled, we will not allocate controller memory for it. These controller configs are guarded by the host-level ISO configs, so disabling `BT_ISO_BROADCAST` will also disable controller memory allocation.

Could you elaborate on how you envisioned utilizing `BT_ISO_MAX_CIG `and `BT_ISO_MAX_BIG`. AFAIK, if either of these are set to 0, we will not allocate controller memory for it

**Comment by Thalley** [comment]
@rugeGerritsen 

> Could you elaborate on how you envisioned utilizing BT_ISO_MAX_CIG and BT_ISO_MAX_BIG. AFAIK, if either of these are set to 0, we will not allocate controller memory for it

Similar to the changes made for ISO_CHAN and the corresponding controller options, `BT_ISO_MAX_CIG` should also be the default for `BT_CTLR_CONN_ISO_GROUPS`, and similarly `BT_CTLR_ADV_ISO_SET` should default to `BT_ISO_MAX_BIG` (kind of, since `BT_ISO_MAX_BIG` is also a common config for BIGs in the host either as receiver or advertiser).

**Comment by rugeGerritsen** [comment]
> > @rugeGerritsen
> > > Could you elaborate on how you envisioned utilizing BT_ISO_MAX_CIG and BT_ISO_MAX_BIG. AFAIK, if either of these are set to 0, we will not allocate controller memory for it
> > 
> > 
> > Similar to the changes made for ISO_CHAN and the corresponding controller options, `BT_ISO_MAX_CIG` should also be the default for `BT_CTLR_CONN_ISO_GROUPS`, and similarly `BT_CTLR_ADV_ISO_SET` should default to `BT_ISO_MAX_BIG` (kind of, since `BT_ISO_MAX_BIG` is also a common config for BIGs in the host either as receiver or advertiser).
> 
> I can create a PR for that! :)

Created https://github.com/zephyrproject-rtos/zephyr/pull/72147

**Pull request merged**
