### PR TITLE
samples: flash_shell: verify written bytes

### PR DESCRIPTION
**Pull request by jeppenodgaard**
Add an optional compare buffer to check if bytes read match a provided buffer and print an error if they differ.

This PR was originally part of https://github.com/zephyrproject-rtos/zephyr/pull/53857.

### CODE REVIEW

**Review by nordicjm — COMMENTED** [review]
I wonder if these functions should just be removed since there already is a general flash test as part of the flash shell, doesn't really need a separate implementation in a sample: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/flash_shell.c#L203

**Comment by jeppenodgaard** [comment]
@de-nordic @nordicjm I created https://github.com/zephyrproject-rtos/zephyr/issues/57242 to address the issue.

**Review by de-nordic — COMMENTED** [review]
Fix CI issues. Rebase?

**Review by de-nordic — DISMISSED** [review]

**Review by nashif — DISMISSED** [review]

**Comment by jeppenodgaard** [comment]
@nashif @de-nordic I rebased to resolve conflicts and removed the `adafruit_kb2040` in `samples/drivers/flash_shell/sample.yaml` exclude since it does not seem to fail anymore.

**Review by de-nordic — APPROVED** [review]

**Comment by jeppenodgaard** [comment]
@nashif or @nordicjm do you have time to take another look?

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
