### PR TITLE
dts_fixup: Remove redefined CONFIG_WDT_0_NAME

### PR DESCRIPTION
**Pull request by qianfan-Zhao**
The marco 'CONFIG_WDT_0_NAME' are defined in Kconfig, doesn't need
defined in dts_fixup.h

Signed-off-by: qianfan Zhao <qianfanguijin@163.com>

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
afaik it should be removed from kconfig or disabled for drivers enabling DTS. It should come from DTS at the end.

**Comment by galak** [comment]
I'm with Anas, that I'd rather we remove the Kconfig option instead of removing this from DT.

**Review by ioannisg — COMMENTED** [review]
Remove option from Kconfig then?

**Comment by galak** [comment]
> I should waiting all the watchdog drivers support DT. Then can remove the Kconfig options.
> 
> Some soc driver doesn't support watchdog dts(such as sam)

Just a quick look for SAM, we have dts/bindings/watchdog/atmel,sam-watchdog.yaml.  Do we not use DT for it?

**Comment by qianfan-Zhao** [comment]
@galak Sorry it's my wrong.

Seems what I need to it remove the Kconfig options and add somethings like this in dts_fixup.h

```
#define CONFIG_WDT_0_NAME CONFIG_WDT_SAM_LABEL
```

**Comment by nashif** [comment]
all those changes do not apply anymore.

**Pull request closed without merging**
