### PR TITLE
ci: set_assignee: pick next area when submitter = assignee

### PR DESCRIPTION
**Pull request by nashif**
Address the cases where submitter is also the maintainer of the code
changed and other areas are being changed. In this case, assign to the
next area maintainers instead of assigning to submitter.

Example: maintainer of component A introduced significant of changes to
area A but also makes changes to other areas B and C. Right now
maintainers of B and C are added as reviewers.

This change will assign to the next area after A in cases where the
submitter is also the maintainer of area A.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by fabiobaltieri — CHANGES_REQUESTED** [review]
Does not strike me as a great idea to do this check without any line number threshold, wouldn't this just assign everything to wide open areas for areas where the maintainer is very active on their own stuff? Seems like a big step backward.

What problem are we addressing? This is a case where maintainer approval was not an issue and now suddenly it is.

**Comment by fabiobaltieri** [comment]
> touches other areas making signifcant changes as well

Sure but this is not modeling any of the "significant" part right? One line of overlap (which happens all the time if you touch, say, a binding or test) and the PR goes somewhere random.

**Comment by henrikbrixandersen** [comment]
I am open to trying this, as I do recognize the issues, we've seen regarding this in the past. However, I think we should keep a close eye on how this works out in practice and be ready to roll this back if too many PRs gets assigned "wrong" (e.g. assigned to next area maintainer, but only a few insignificant lines were changed in that area).

I'd still prefer a limit on the LoC changed before picking next area maintainer.

**Comment by nashif** [comment]
> Sure but this is not modeling any of the "significant" part right? One line of overlap (which happens all the time if you touch, say, a binding or test) and the PR goes somewhere random.

Binding, samples, docs, does not really matter. Those are areas and all areas are treated the same, if we do not care about changes to bindings and they are fiar game for anyone to change as they wish, we probably do not need to have an area for bindings or setup the wildcards in a way where not every single binding change is part of the bindings area, i.e binding for i2c should be part of I2c and so on.

Reiterating, since the submitter can't approve their own PR anyways, any 2 random reviews from non-maintainers will make the PR mergeable. Having the maintainer of the next significanly changed area assignee will help prevent that and we do not run into situations where changes to other areas go in un-noticed.

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by nashif** [comment]
> Then drop [`main`/MAINTAINERS.yml#L812](https://github.com/zephyrproject-rtos/zephyr/blob/main/MAINTAINERS.yml?rgh-link-date=2024-06-26T10%3A49%3A44Z#L812) before doing this change, it's not messing this up now just because there's no maintainers, ~but how about docs then?~ no wildcard for doc/ so I guess that's fine.

dropped

**Review by fabiobaltieri — APPROVED** [review]
Worth a try.

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
