### PR TITLE
Revert "drivers: watchdog: wdt_nrfx: Implement disable API"

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
This reverts commit 415b6fc945fd3748d2c8c5191abbc484fe551cad.

This does not even compile as it attempts to do assignment to a read-only object (config->config.behaviour).

Breaking change introduced in #64298 (cc: @carlescufi, @nika-nordic):

```
[113/171] Building C object zephyr/drivers/watchdog/CMakeFiles/drivers__watchdog.dir/wdt_nrfx.c.obj
FAILED: zephyr/drivers/watchdog/CMakeFiles/drivers__watchdog.dir/wdt_nrfx.c.obj 
ccache /opt/toolchains/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DKERNEL -DNRF52833_XXAA -DPICOLIBC_INTEGER_PRINTF_SCANF -D_FORTIFY_SOURCE=1 -D_POSIX_C_SOURCE=200809 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/pan1782_evb/samples/shields/npm6001_ek/sample.shields.npm6001_ek/zephyr/include/generated -I/__w/zephyr/zephyr/soc/arm/nordic_nrf/nrf52 -I/__w/zephyr/zephyr/lib/posix/getopt/. -I/__w/zephyr/zephyr/soc/arm/nordic_nrf/common/. -I/__w/zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/__w/zephyr/zephyr/modules/cmsis/. -I/__w/zephyr/modules/hal/nordic/nrfx -I/__w/zephyr/modules/hal/nordic/nrfx/drivers/include -I/__w/zephyr/modules/hal/nordic/nrfx/mdk -I/__w/zephyr/zephyr/modules/hal_nordic/nrfx/. -I/__w/zephyr/modules/debug/segger/SEGGER -I/__w/zephyr/modules/debug/segger/Config -isystem /__w/zephyr/zephyr/lib/libc/common/include -Wshadow -fno-strict-aliasing -Werror -Os -imacros /__w/zephyr/zephyr/twister-out/pan1782_evb/samples/shields/npm6001_ek/sample.shields.npm6001_ek/zephyr/include/generated/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft --sysroot=/opt/toolchains/zephyr-sdk-0.16.3/arm-zephyr-eabi/arm-zephyr-eabi -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/samples/shields/npm6001_ek=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections --specs=picolibc.specs -D_POSIX_THREADS -std=c99 -MD -MT zephyr/drivers/watchdog/CMakeFiles/drivers__watchdog.dir/wdt_nrfx.c.obj -MF zephyr/drivers/watchdog/CMakeFiles/drivers__watchdog.dir/wdt_nrfx.c.obj.d -o zephyr/drivers/watchdog/CMakeFiles/drivers__watchdog.dir/wdt_nrfx.c.obj -c /__w/zephyr/zephyr/drivers/watchdog/wdt_nrfx.c
/__w/zephyr/zephyr/drivers/watchdog/wdt_nrfx.c: In function 'wdt_nrf_setup':
/__w/zephyr/zephyr/drivers/watchdog/wdt_nrfx.c:34:34: error: assignment of member 'behaviour' in read-only object
   34 |         config->config.behaviour = NRF_WDT_BEHAVIOUR_RUN_SLEEP_MASK |
      |                                  ^
/__w/zephyr/zephyr/drivers/watchdog/wdt_nrfx.c:42:42: error: assignment of member 'behaviour' in read-only object
   42 |                 config->config.behaviour &= ~NRF_WDT_BEHAVIOUR_RUN_SLEEP_MASK;
      |                                          ^~
/__w/zephyr/zephyr/drivers/watchdog/wdt_nrfx.c:47:42: error: assignment of member 'behaviour' in read-only object
   47 |                 config->config.behaviour &= ~NRF_WDT_BEHAVIOUR_RUN_HALT_MASK;
      |                                          ^~
/__w/zephyr/zephyr/drivers/watchdog/wdt_nrfx.c:50:37: error: assignment of member 'reload_value' in read-only object
   50 |         config->config.reload_value = data->m_timeout;
      |                                     ^
```

### CODE REVIEW

**Review by fabiobaltieri — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
The compliance check failure is due to the original formatting of the file. Unrelated to the revert.

**Comment by fabiobaltieri** [comment]
Compliance check is complaining for the style of a comment, you may want to edit that.

**Comment by fabiobaltieri** [comment]
> The compliance check failure is due to the original formatting of the file. Unrelated to the revert.

Yeah either edit or have someone with bypass permissions to merge.

**Comment by martinjaeger** [comment]
Oops. Must have overlooked that in my second-pass review.

Another related PR, but don't have the time right now to check if it fixes the issue: https://github.com/zephyrproject-rtos/zephyr/pull/65287

**Review by martinjaeger — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
