### PR TITLE
posix: Fix FS issues with newlib

### PR DESCRIPTION
**Pull request by krish2718**

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]

**Review by cfriedt — CHANGES_REQUESTED** [review]
It looks like this test fails for xtensa

```
    Assertion failed at WEST_TOPDIR/zephyr/tests/posix/fs/src/test_fs_file.c:329: posix_fs_file_test_test_fs_fopen: test_file_fopen() == TC_PASS is false
```

**Comment by krish2718** [comment]
> It looks like this test fails for xtensa
> 
> ```
>     Assertion failed at WEST_TOPDIR/zephyr/tests/posix/fs/src/test_fs_file.c:329: posix_fs_file_test_test_fs_fopen: test_file_fopen() == TC_PASS is false
> ```

Yes, I have fixed a failure for qemu_x86, but fopen still fails with xtensa, looking in to, also moved the tests to a separate test suite with close.

**Comment by krish2718** [comment]
The below fix solves CI issue for `qemu_xtensa` , but I still don't understand the root cause:

```
diff --git a/include/zephyr/posix/fcntl.h b/include/zephyr/posix/fcntl.h
index 9689d1ae8c3..449dd9b1ce3 100644
--- a/include/zephyr/posix/fcntl.h
+++ b/include/zephyr/posix/fcntl.h
@@ -9,6 +9,8 @@
 
 #ifdef CONFIG_PICOLIBC
 #define O_CREAT 0x0040
+#elif defined(CONFIG_NEWLIB_LIBC) && defined(CONFIG_XTENSA)
+#define O_CREAT 0x0100
 #else
 #define O_CREAT 0x0200
 #endif
```

But the fcntl is properly set to `0x200` for default and `0x40` for picolib which matches Zephyr's `fcntl.h` definitions:

```
$agi _FCREAT zephyr-sdk-0.16.5-1/xtensa-dc233c_zephyr-elf
zephyr-sdk-0.16.5-1/xtensa-dc233c_zephyr-elf/xtensa-dc233c_zephyr-elf/sys-include/sys/_default_fcntl.h
18:#define      _FCREAT         0x0200  /* open with file create */
52:#define      O_CREAT         _FCREAT
115:#define     FCREAT          _FCREAT

zephyr-sdk-0.16.5-1/xtensa-dc233c_zephyr-elf/xtensa-dc233c_zephyr-elf/include/sys/_default_fcntl.h
18:#define      _FCREAT         0x0200  /* open with file create */
52:#define      O_CREAT         _FCREAT
115:#define     FCREAT          _FCREAT

zephyr-sdk-0.16.5-1/xtensa-dc233c_zephyr-elf/picolibc/xtensa-dc233c_zephyr-elf/sys-include/sys/_default_fcntl.h
19:#define      _FCREAT         0x0040  /* open with file create */
53:#define      O_CREAT         _FCREAT
116:#define     FCREAT          _FCREAT

zephyr-sdk-0.16.5-1/xtensa-dc233c_zephyr-elf/picolibc/include/sys/_default_fcntl.h
19:#define      _FCREAT         0x0040  /* open with file create */
53:#define      O_CREAT         _FCREAT
116:#define     FCREAT          _FCREAT
```
@cfriedt any clues as to why the above fix works?

**Comment by krish2718** [comment]
BTW, I have also observed that `O_APPEND` value varies, `newlib` defines it as `#define _FAPPEND        0x0008` and Zephyr as  `#define O_APPEND   0x0400`.

**Comment by jukkar** [comment]
I noticed in with native_sim boards, where both the host and zephyr are providing values for same symbols, at least currently it is important to include proper header file so that proper value is selected for the compilation.
For example if including `fcntl.h` you might get either the host header or zephyr header (depending on how things are setup), but if you include `zephyr/posix/fcntl.h` you will get zephyr version and an error if host header was suppose to be used.
Got hit by this sometime ago and trying to figure out what was wrong as a bit difficult, this was fixed by d7c9d67a9c3c9f641f58e894a8df4587df0cc8ef

**Comment by krish2718** [comment]
Thanks @jukkar . Yes, I too had been bitten on header file inclusion esp. POSIX related ones. But unfortunately in this case, including the Zephyr one doesn't help. Unlike `open` we don't directly pass the flags for `fopen` the string `w+` is translated to flags by `libc` and `fs.c` in Zephyr converts the flags from POSIX ( `zephyr/posix/fcntl.h`) to Zephyr, this is where there are issues w.r.t Xtensa arch.

**Review by jukkar — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
Yea, that is strange. In any case, a bunch of this functionality will likely be moved soon (at least the POSIX part).

**Review by rlubos — APPROVED** [review]

**Pull request closed without merging**
