### PR TITLE
Remove redundant samples and tests

### PR DESCRIPTION
**Pull request by SebastianBoe**

### CODE REVIEW

**Review by pfalcon — CHANGES_REQUESTED** [review]
> static_lib is insignificantly different from external_lib and can be safely removed.

It may look insignificant, but people who contributed it (and who approved it) thought the difference is worthy an explicit example. And to trace the history:

1. static_lib was added first. It shows how to build a 3rd-party lib using Zephyr build system (together with the main app).
2. external_lib shows how to take an existing prebuilt library and link a Zephyr app with it. However, as there's no guaranteed lib lying outside Zephyr tree, it builds a sample lib in-tree, but uses a full path to link to it, arguably easily portable to a true external lib.

Consequently, between the 2, static_lib is a better example to keep in-tree. And I'd say, external_lib is worth staying, if it was added in the first place, what it shows isn't yet a FAQ, but was asked more than once already.

While writing this, I thought it's worth giving -1 here.

**Comment by nashif** [comment]
does not really matter who was first, this is needed for the cmake migration, both in CMake look exactly the same and we should keep just one.

@SebastianBoe you can remove this at the same time we remove Kbuild, that should be fine, to avoid any confusion.

**Comment by nashif** [comment]
close by mistake

**Comment by SebastianBoe** [comment]
Thank you @pfalcon , I now understand the distinction between the two, I was not aware
that they were distinct in KBuild.

Anas is right, after the migration the procedure for integrating with a prebuilt lib
is the same as the procedure for integrating with the output of an external build system.

So two samples will not be necessary.

For reference:
https://github.com/zephyrproject-rtos/zephyr/blob/cmake_migration/samples/application_development/external_lib/CMakeLists.txt#L44

**Comment by pfalcon** [comment]
> Anas is right, after the migration the procedure for integrating with a prebuilt lib is the same as the procedure for integrating with the output of an external build system.

Then my personal suggestion is to keep "static_lib" naming (because there's a difference after all).

**Pull request closed without merging**
