### PR TITLE
Fix locked IRQ support in LiteX timer

### LINKED ISSUE #23622: litex_vexriscv: k_busy_wait() never returns if called with interrupts locked
**Describe the bug**
k_busy_wait() never returns if called with interrupts locked on the `litex_vexriscv` platform, which uses `litex_timer` system timer.

For more details, refer to the issue #23519.

### PR DESCRIPTION
**Pull request by mateusz-holenko**
This reimplements z_timer_cycle_get_32() so it works
when IRQs are locked and solves the hung
k_busy_wait() problem.

This fixes #23622.

### CODE REVIEW

**Review by pabigot — COMMENTED** [review]
I was asked to review this to get it moving, but I don't have the hardware to run this. Can you provide some more information about how this actually works?  

From what I can see there's an 8-bit `TIMER_EV_PENDING` register that is written every time there's a timer IRQ, and the original tick/cycle count corresponded to the number of times the timer IRQ fired.  So this is essentially a `CONFIG_TICKLESS=n` system, as it says in a comment.

From what I can see [the solution](https://github.com/zephyrproject-rtos/zephyr/issues/23622#issuecomment-627143267) involves adding two new registers: `TIMER_TOTAL_UPDATE` is an 8-bit write-only(?) register at 0x44.  Writing something to it causes a 64-bit read-only(?) register `TIMER_TOTAL` to advance by some amount (I assume).  In the change it is the value of this register that becomes the cycle counter.

What I don't see is how advances to the cycle counter due to timer interrupts correspond to tick events: the timer interrupt doesn't write to `TIMER_TOTAL_UPDATE`.  So time only advances when somebody calls `z_timer_cycle_get_32()`?

There must be magic somewhere in the implementation of the TIMER peripheral but I don't see any dependency in this PR on an external definition of the SOC that adds the new magic.  Shouldn't that be here somewhere, or at least documented in the description of the PR?

**Comment by mateusz-holenko** [comment]
> I was asked to review this to get it moving, but I don't have the hardware to run this. Can you provide some more information about how this actually works?

Of course - I'll answer the specific questions below.

> From what I can see there's an 8-bit TIMER_EV_PENDING register that is written every time there's a timer IRQ, and the original tick/cycle count corresponded to the number of times the timer IRQ fired. So this is essentially a CONFIG_TICKLESS=n system, as it says in a comment.

That's correct. We assume timer IRQs are generated periodically every 10ms and on each interrupt we call `z_clock_announce(1)` to move time forward in Zephyr.

> From what I can see the solution involves adding two new registers: TIMER_TOTAL_UPDATE is an 8-bit write-only(?) register at 0x44. Writing something to it causes a 64-bit read-only(?) register TIMER_TOTAL to advance by some amount (I assume). In the change it is the value of this register that becomes the cycle counter.

The original timer wrapped after generating an IRQ event (in the Zephyr configuration it was every 10 ms).

We extended it with the additional CSRs for keeping the "uptime", i.e., the number of total timer cycles. `TIMER_TOTAL` keeps the accumulated value of cycles passed from the system start regardless of the number of IRQs generated or the configured load/reload values.

As for the width of registers - LiteX can map a single CSR into a series of registers. The details are described in  https://github.com/enjoy-digital/litex/wiki/CSR-Bus, but the general idea is that a single 32-bit LiteX CSR is de facto a series of 4 consecutive 32-bit registers, each keeping only 8-bits of data.

This is also the reason why we need the `TIMER_TOTAL_UPDATE` register - writing to it latches the current timer value and allows to read it safely later. It updates the value of the `TIMER_TOTAL` register with the current value of the uptime timer (the number of clock cycles from the system start).

As it requires 8 * 8-bit reads (`TIMER_TOTAL` is a 64-bit width CSR) to get the value from HW, it would be practically impossible to do that on running clock.

> What I don't see is how advances to the cycle counter due to timer interrupts correspond to tick events: the timer interrupt doesn't write to TIMER_TOTAL_UPDATE. 

The fact we are in the IRQ handler already tells us that the 10ms passed - there is no need to read the actual value of the timer. Having the `TIMER_RELOAD` register set to a non-zero value automatically starts the countdown again after generating the IRQ, so there is no need to reconfigure the timer on each IRQ. Writing to `TIMER_EV_PENDING` clears the IRQ pending flag in order for HW to generate the interrupt the next time.

> So time only advances when somebody calls z_timer_cycle_get_32()?

With enabled interrupts times advances thanks to the `litex_timer_irq_handler` automatically every 10ms.

With disabled interrupts the time flow is visible only by polling the value of `z_timer_cycle_get_32()`. This is similar to what is done in: https://github.com/stephanosio/zephyr/blob/7a178042f50462e984e3853292799b91c3bdb4e8/drivers/timer/xlnx_psttc_timer.c#L194.

The problem we see with this approach is wrapping of the uptime timer. LiteX HW uptime timer is 64-bit wide, but we must cast it to a 32-bit value. This means that with the current implementation of `k_busy_wait` it is possible to finish it earlier than expected (if it's called just before wrapping of the timer's value).

This, however, seems to be a general problem in Zephyr (not limited to our implementation) and probably should be discussed separately.

> There must be magic somewhere in the implementation of the TIMER peripheral but I don't see any dependency in this PR on an external definition of the SOC that adds the new magic. Shouldn't that be here somewhere, or at least documented in the description of the PR?

You are right, we should have linked to the timer's definition. The extension to the timer HW was done in: https://github.com/enjoy-digital/litex/commit/be25500e9173b0e7c0ec6e8d5f626cc7f52a9484.
 
Adding the uptime CSRs is optional and currently not enabled by default in LiteX. We are working on publishing our own LiteX-based platform for Zephyr that includes all the necessary configuration so that recreating the SoC is easy for everyone.

**Review by pabigot — APPROVED** [review]
Thanks; this makes sense now and seems like a good solution.

If the register were named `TIMER_TOTAL_LATCH` it'd perhaps have been more clear, at least to me; "update" suggested it was providing a value that was to be added to the timer.

**Comment by pabigot** [comment]
Actually, you may want to put a spinlock around the body of `z_timer_cycle_get_32()`, since it is possible to have that function invoked from interrupts, and that timer read is in no way atomic.

**Comment by carlescufi** [comment]
> Actually, you may want to put a spinlock around the body of `z_timer_cycle_get_32()`, since it is possible to have that function invoked from interrupts, and that timer read is in no way atomic.

@mateusz-holenko @kgugala @PiotrZierhoffer @pgielda could you make this additional change so we can merge this?

**Comment by mateusz-holenko** [comment]
@carlescufi We are working on this.

**Comment by carlescufi** [comment]
> @carlescufi We are working on this.
Thanks for the update!

**Comment by carlescufi** [comment]
> @carlescufi We are working on this.

Thanks for the update!

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
