### PR TITLE
openisa_rv32m1: kconfig: Remove base address/size symbols

### PR DESCRIPTION
**Pull request by ulfalizer**
RISCV_RV32M1_VECTOR_BASE_ADDR is unused after commit 34b0516466
("boards: riscv32: rv32m1_vega: enable MCUboot for ri5cy core") (it was
called RISCV32_RV32M1_BASE_ADDR then).

RISCV_RV32M1_VECTOR_SIZE is still used, but is always 0x100, so remove
it too.

These symbols were only defined in a Kconfig.defconfig file.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@lylezhu2014 @alexandru-porosanu-nxp will you please take a look at this?

**Comment by alexandru-porosanu-nxp** [comment]
LGTM, tested by applying over the BLE SW LL on Vega (#19710)

**Review by MaureenHelm — APPROVED** [review]

**Comment by ioannisg** [comment]
> RISCV_RV32M1_VECTOR_SIZE is still used, but is always 0x100, so remove it too.

I'd say, replacing a hard-coded value with a macro or Kconfig is straightforward; doing the opposite needs to be justified, cause it makes the code less maintainable.

Having the VECTOR_SIZE in the linker file be taken from the Kconfig symbol makes the code easier to read, and extend, later, if there are other SoCs, SoC-variants with different size.

IMHO, there's nothing wrong with hidden symbols being defined with a single default and used only once. And it's the best way to share symbols between linker and compiler

**Comment by ulfalizer** [comment]
> > RISCV_RV32M1_VECTOR_SIZE is still used, but is always 0x100, so remove it too.
> 
> I'd say, replacing a hard-coded value with a macro or Kconfig is straightforward; doing the opposite needs to be justified, cause it makes the code less maintainable.
> 
> Having the VECTOR_SIZE in the linker file be taken from the Kconfig symbol makes the code easier to read, and extend, later, if there are other SoCs, SoC-variants with different size.
> 
> IMHO, there's nothing wrong with hidden symbols being defined with a single default and used only once. And it's the best way to share symbols between linker and compiler

I think it makes it harder to read. `#define VECTOR_SIZE 0x100` says a lot more than `#define VECTOR_SIZE CONFIG_RISCV_RV32M1_VECTOR_SIZE`, because it tells you that it's currently constant.

If it stops being constant, then a symbol could be added back.

**Review by karstenkoenig — APPROVED** [review]
Oh weird I totally ran this on my board and it worked, must have forgotten to approve it

**Comment by karstenkoenig** [comment]
> I think it makes it harder to read. `#define VECTOR_SIZE 0x100` says a lot more than `#define VECTOR_SIZE CONFIG_RISCV_RV32M1_VECTOR_SIZE`, because it tells you that it's currently constant, and what the value is.
> 
> If it stops being constant, then a symbol could be added back.

Also wouldn't the vector size have to rather be in the dts definition than KConfig according to the KConfig/DTS split?

**Comment by ulfalizer** [comment]
> > I think it makes it harder to read. `#define VECTOR_SIZE 0x100` says a lot more than `#define VECTOR_SIZE CONFIG_RISCV_RV32M1_VECTOR_SIZE`, because it tells you that it's currently constant, and what the value is.
> > If it stops being constant, then a symbol could be added back.
> 
> Also wouldn't the vector size have to rather be in the dts definition than KConfig according to the KConfig/DTS split?

Not sure how it's handled atm, but could make more sense in devicetree at least. At least the Kconfig symbols aren't user-configurable, so can't mess it up in `menuconfig` or configuration files.

**Comment by alexandru-porosanu-nxp** [comment]
> > > I think it makes it harder to read. `#define VECTOR_SIZE 0x100` says a lot more than `#define VECTOR_SIZE CONFIG_RISCV_RV32M1_VECTOR_SIZE`, because it tells you that it's currently constant, and what the value is.
> > > If it stops being constant, then a symbol could be added back.
> > 
> > 
> > Also wouldn't the vector size have to rather be in the dts definition than KConfig according to the KConfig/DTS split?
> 
> Not sure how it's handled atm, but could make more sense in devicetree at least. At least the Kconfig symbols aren't user-configurable, so can't mess it up in `menuconfig` or configuration files.

It's something HW specific, so it does make sense to have it in the DT.

**Pull request merged**
