### PR TITLE
soc: xtensa: intel_s1000: Encode IRQ in dts

### PR DESCRIPTION
**Pull request by galak**
Move IRQ number encoding out of dts_fixup.h and into the dtsi files.
For now just change devices on the dw_intc.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@rgundi, @SavinayDharmappa can you guys review/comment on this.

**Comment by nashif** [comment]
@dcpleung can you please verify on s1000?

**Review by sathishkuttan — COMMENTED** [review]
I understand that the goal is to eliminate as much as possible from the `fixup` file.
I do however propose that we come up with a better mechanism to both **describe** the interrupt in DTS as well as **generate** the encoding.

- **Describing** the interrupt can be done by just 2 parameters
    - The parent controller, if there is one
    - the input interrupt number in that parent controller.
- **Encoding** the interrupt can then be generated by following the parent nodes and using their interrupt assignments in their respective bit-fields.

**Comment by galak** [comment]
> I understand that the goal is to eliminate as much as possible from the `fixup` file.
> I do however propose that we come up with a better mechanism to both **describe** the interrupt in DTS as well as **generate** the encoding.
> 
> * **Describing** the interrupt can be done by just 2 parameters
>   
>   * The parent controller, if there is one
>   * the input interrupt number in that parent controller.
> * **Encoding** the interrupt can then be generated by following the parent nodes and using their interrupt assignments in their respective bit-fields.

So I feel like my change is a short term solution.  I'm not quite clear why the IRQs are done this way on S1000.  Is it because of how the hardware works or how Zephyr's cascaded interrupt handling works.  If its because of Zephyr's cascading, than I think we need to fix that.

**Comment by galak** [comment]
> The hierarchical interrupt aggregation is typical whenever there are more hardware interrupts than what a CPU has or a single interrupt controller can take, and is not unique to S1000.
> When I first looked at the IRQ encoding, it was hard for me to understand as well and when I dug into it, I found that the way Zephyr defines the IRQs is through a single 32 bit number and this encoding is a way to represent an interrupt that is aggregated at multiple levels - I understood this from [docs.zephyrproject.org/latest/kernel/other/interrupts.html#multi-level-interrupt-handling](https://docs.zephyrproject.org/latest/kernel/other/interrupts.html#multi-level-interrupt-handling)
> 
> In the PR I referenced, I created a macro to perform this encoding (because I had to resort to reverse engineering the encoding of magic numbers that formed the IRQ) and my wish is to move them to DTS in a way I described earlier. Currently many blocks in S1000 are still defined through Kconfig and not in DTS.

I haven't looked at the details, but what this means is we need to update the DTS generation script to walk the interrupt controller hierarchy to produce the proper value.  In the short term I'd like to go ahead with my change as it means we can make progress on cleaning up the SPI, I2C, etc designware drivers.

**Comment by sathishkuttan** [comment]
> In the short term I'd like to go ahead with my change

OK as a short term arrangement.

**Comment by nashif** [comment]
btw, multi level interrupts are being used in some riscv32 boards as well. rv32m1_vega if I remember correctly.

**Comment by galak** [comment]
> OK as a short term arrangement.

@sathishkuttan can you test this to see it works ok on S1000 and Approve if so.

**Comment by sathishkuttan** [comment]
> can you test this to see it works ok on S1000 and Approve if so.

unfortunately, mainline is broken on S1000. @rgundi confirmed this as well. In my case it was a silent crash (or a block forever) in I2C driver. I'll first have to find a better baseline and then if I manage to apply this change, I can test it. Just from code review, it looks OK though and I'll approve based on just code review.

**Comment by galak** [comment]
> unfortunately, mainline is broken on S1000. @rgundi confirmed this as well. In my case it was a silent crash (or a block forever) in I2C driver. I'll first have to find a better baseline and then if I manage to apply this change, I can test it. Just from code review, it looks OK though and I'll approve based on just code review.

Are the dts interrupt numbers adjusted from their real hardware values?  I'm trying to understand the difference between the doc and value that is used today.  The doc seems to imply a +1 that occurs as we travel levels.

**Comment by sathishkuttan** [comment]
> Are the dts interrupt numbers adjusted from their real hardware values?

Yes, because 0 has a special meaning as in the note at https://docs.zephyrproject.org/latest/kernel/other/interrupts.html#multi-level-interrupt-handling
> The bit positions for LEVEL 2 and onward are offset by 1, as 0 means that interrupt number is not present for that level.

So if an interrupt is tied to bit 0 or an interrupt controller, it would have to be specified as 1.

**Comment by galak** [comment]
> > Are the dts interrupt numbers adjusted from their real hardware values?
> 
> Yes, because 0 has a special meaning as in the note at [docs.zephyrproject.org/latest/kernel/other/interrupts.html#multi-level-interrupt-handling](https://docs.zephyrproject.org/latest/kernel/other/interrupts.html#multi-level-interrupt-handling)

What exactly does that mean.  Trying to figure out what case this is trying to encode.

> 
> > The bit positions for LEVEL 2 and onward are offset by 1, as 0 means that interrupt number is not present for that level.
> 
> So if an interrupt is tied to bit 0 of an interrupt controller, it would have to be specified as 1.

**Comment by sathishkuttan** [comment]
> What exactly does that mean. Trying to figure out what case this is trying to encode.

Perhaps it would help if the original author/mastermind behind the multi-level interrupt definition in Zephyr chimes in with what his/her thinking was. @nashif do you know who it is?

From reading code and docs, my understanding is as follows.
- In the example provided in the documentation, consider the 2 interrupt sources, B and D
- B is at LEVEL 2 and D is at LEVEL 3
- An 8 bit number should be used to indicate both the level AND the interrupt bit number at that level
- Hence the value of 0 in this 8 bit number indicates that the interrupt in question does not belong at the level but in a lower level of the hierarchy.
- A non-zero value indicates that the interrupt in question is tied through this level either directly or through another level of interrupt controller. The actual bit position in hardware for this interrupt at this level is `value - 1`

I'm afraid this is my limit and anything further in terms of explanation will have to come from the higher power that defined this mechanism :)

**Comment by rgundi** [comment]
> > What exactly does that mean. Trying to figure out what case this is trying to encode.
> 
> Perhaps it would help if the original author/mastermind behind the multi-level interrupt definition in Zephyr chimes in with what his/her thinking was. @nashif do you know who it is?
> 
> From reading code and docs, my understanding is as follows.
> 
> * In the example provided in the documentation, consider the 2 interrupt sources, B and D
> * B is at LEVEL 2 and D is at LEVEL 3
> * An 8 bit number should be used to indicate both the level AND the interrupt bit number at that level
> * Hence the value of 0 in this 8 bit number indicates that the interrupt in question does not belong at the level but in a lower level of the hierarchy.
> * A non-zero value indicates that the interrupt in question is tied through this level either directly or through another level of interrupt controller. The actual bit position in hardware for this interrupt at this level is `value - 1`
> 
> I'm afraid this is my limit and anything further in terms of explanation will have to come from the higher power that defined this mechanism :)

@sathishkuttan seems to have understood this correctly. I'll still make an attempt with an example if it helps.

Let's for the sake of discussion, assume there are only 2 interrupt levels viz. LEVEL1 and LEVEL2. The multi-level interrupt architecture assigns 1 byte for each interrupt level. So, since we have only 2 levels, let's consider only 2 byte numbers for simplicity. LEVEL1 is nothing but the native interrupts. An interrupt on Bit4 (starting from Bit0) is represented as 0x0004 over here. The 0x00 here denotes that it is NOT a LEVEL2 interrupt. Let's assume a cascade interrupt controller is connected to Bit6 in LEVEL1. i.e. it will be represented as 0x0006. This cascade interrupt controller is nothing but the LEVEL2 interrupt controller. An interrupt on Bit0 in this LEVEL2 interrupt controller is now represented as 0x0106. It can't be represented as 0x0006 coz that would indicate the cascade interrupt controller itself which is a native interrupt. That is the reason why we have the "offset by 1" for all interrupts LEVEL2 onwards.

**Review by rgundi — APPROVED** [review]
LGTM

**Pull request merged**
