### PR TITLE
i.MX8M clk fix

### PR DESCRIPTION
**Pull request by MrVan**

### CODE REVIEW

**Comment by MrVan** [comment]
@dleach02 any comments?

**Comment by danieldegrasse** [comment]
@MrVan [this line in nxp_imx8ml_m7.dtsi](https://github.com/zephyrproject-rtos/zephyr/blob/b9c345b1a5eaed94c75e07a0f05c9a9e7ba2c56f/dts/arm/nxp/nxp_imx8ml_m7.dtsi#L168) needs to be updated if you change the clock definition names. That seems to be what's causing the CI failure.

**Comment by MrVan** [comment]
> @MrVan [this line in nxp_imx8ml_m7.dtsi](https://github.com/zephyrproject-rtos/zephyr/blob/b9c345b1a5eaed94c75e07a0f05c9a9e7ba2c56f/dts/arm/nxp/nxp_imx8ml_m7.dtsi#L168) needs to be updated if you change the clock definition names. That seems to be what's causing the CI failure.

Thanks for pointing out this. Fixed.

**Review by danieldegrasse — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by MrVan** [comment]
> this breaks CI and main branch

@nashif would you please share me the details? There was no error in this PR CI.

**Comment by MrVan** [comment]
> > this breaks CI and main branch
> 
> @nashif would you please share me the details? There was no error in this PR CI.

Just see your PR. Indeed, two PRs not synced, forgot to rebase this PR after 8MM-A53 PR in. Will take care in future. THanks.

**Pull request merged**
