### PR TITLE
driver: timer: npcx: fix the failure of the timer_behavior testsuite

### LINKED ISSUE #59594: npcx9m6f_evb: kernel/timer/timer_behavior/ failing
**Describe the bug**
Tests from kernel/timer/timer_behavior/ failing, not a single test case pass. 

**To Reproduce**
  1. cd <path/to>zephyrproject/zephyr
  2. source zephyr-env.sh
  3. twister --device-testing --hardware-map <path/to>/map.yaml -T tests/kernel/timer/timer_behavior/ -vv

**Expected behavior**
The tests pass

**Impact**
annoyance

**Logs and console output**
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.2.0-2474-g1aebcec02ff9 ***
DEBUG   - DEVICE: Running TESTSUITE timer_jitter_drift
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_jitter_drift
DEBUG   - DEVICE: periodic timer behavior test
DEBUG   - -- west flash: using runner openocd
-- runners.openocd: Flashing file: /home/ztest/zephyrproject/zephyr/twister-out/npcx9m6f_evb/zephyr/tests/kernel/ti

DEBUG   - DEVICE: periodic timer samples gathered, calculating statistics
DEBUG   - DEVICE: timer clock rate 15000000, kernel tick rate 1000, expected period 1000 us, samples 7000, period 1
DEBUG   - DEVICE: statistics samples 7000, rollovers 0, mean 2198.162029 us, variance 138.655087 us, stddev 11.7751
DEBUG   - DEVICE: statistics samples 7000, rollovers 0, mean 32972.430429 cycles, variance 31197.394588 cycles, std
DEBUG   - DEVICE: timer start cycle 310370, end cycle 231117383, total time 15387134.200000, expected time 7000000.
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_behavior/src/jitter_drift.c:195: 
DEBUG   - DEVICE: Longest timer period too long (off by more than expected 10%)
DEBUG   - DEVICE: FAIL - test_jitter_drift in 16.093 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE timer_jitter_drift failed.
DEBUG   - DEVICE: Running TESTSUITE timer_tick_train
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_one_tick_timer_train
DEBUG   - DEVICE: Initializing 4 Timers, Tick Rate 1000Hz, Expecting 2500 callbacks in 11000 ms
DEBUG   - DEVICE: Starting Timers with Skews
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 0
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 55
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 110
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 165
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 220
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 274
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 329
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 384
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 439
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 493
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 548
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 603
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 658
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 712
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 767
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 822
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 877
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 931
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 986
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1041
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1096
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1150
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1205
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1260
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1315
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1369
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1424
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1479
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1534
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1588
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1643
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1698
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1753
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1807
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1862
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1917
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 1972
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2027
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2081
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2136
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2191
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2246
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2300
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2355
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2410
DEBUG   - DEVICE: Faking busy work, remaining timers is 4, timer callbacks 2465
DEBUG   - DEVICE: One Tick Timer Train Done, took 11683 ms, busy loop ran 46 times
DEBUG   - DEVICE: Timer 0 max delta 69654 cycles or 4644 us
DEBUG   - DEVICE: Timer 1 max delta 69681 cycles or 4645 us
DEBUG   - DEVICE: Timer 2 max delta 69662 cycles or 4644 us
DEBUG   - DEVICE: Timer 3 max delta 69657 cycles or 4644 us
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_behavior/src/tick_timer_train.c:1
DEBUG   - DEVICE: Expected timer train to finish in under 11000 milliseconds, took 11683
DEBUG   - DEVICE: FAIL - test_one_tick_timer_train in 11.734 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE timer_tick_train failed.
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY START ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: SUITE FAIL -   0.00% [timer_jitter_drift]: pass = 0, fail = 1, skip = 0, total = 1 duration = 16.
DEBUG   - DEVICE: - FAIL - [timer_jitter_drift.test_jitter_drift] duration = 16.093 seconds
DEBUG   - DEVICE: 
DEBUG   - DEVICE: SUITE FAIL -   0.00% [timer_tick_train]: pass = 0, fail = 1, skip = 0, total = 1 duration = 11.73
DEBUG   - DEVICE: - FAIL - [timer_tick_train.test_one_tick_timer_train] duration = 11.734 seconds
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY END ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: 9fff733e18c4bd6078438aad2254fdbf
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
DEBUG   - run status: npcx9m6f_evb/zephyr/tests/kernel/timer/timer_behavior/kernel.timer.timer failed

**Environment:**
 - OS: Linux
 - Toolchain Zephyr SDK 16.0
 - Commit: tested on the newest and older, always the same issue

### PR DESCRIPTION
**Pull request by ChiHuaL**
The `cyc_sys_announced` (tick to be announced) was updated with the current timer will cause the time drift and induce the jitter when running the timer_behavior test suite. This PR fixed it by updating it at the tick boundary). The sys_clock_set_timeout API also changed because the above modification.
Also, as the npcx event timer is running at 32768 Hz (to support the low power sleep mode), it might introduce the deviation of (+/-) 30.5 us when converting the system time to event count. This PR increases the stdev tolerance in the test's Kconfig when npcx chip is used

This PR passed the long run stress (warm reboot) on the Chromebook platform. 

Fixes #59594

### CODE REVIEW

**Review by teburd — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Review by npitre — CHANGES_REQUESTED** [review]
This is introducing unneeded divisions and divisions are costly 
_especially_ 64-bits ones.

You already maintain `cyc_sys_announced`. Similarly, you just have to 
add some `last_elapsed` variable holding the last value your 
`sys_clock_elapsed()` returned, and set it to 0 when `npcx_itim_evt_isr()` 
is invoked. This will allow you to greatly simplify 
`npcx_itim_start_evt_tmr_by_tick()` like this:

```
static int npcx_itim_start_evt_tmr_by_tick(int32_t ticks)
{
        k_spinlock_key_t key = k_spin_lock(&lock);

        if (ticks == K_TICKS_FOREVER) {
                cyc_evt_timeout = NPCX_ITIM32_MAX_CNT;
        } else {
                uint64_t delta_cycs;

                if (ticks <= 0) {
                        ticks = 1;
                }

                delta_cycs = (last_elapsed + ticks) * SYS_CYCLES_PER_TICK;
                cyc_evt_timeout =
                        MIN(DIV_ROUND_UP(delta_cycs, SYS_CYC_PER_EVT_CYC), NPCX_ITIM32_MAX_CNT);
        }
[...]
```

This way you don't have to sample npcx_itim_get_sys_cyc64() again as it is 
already factored into `last_elapsed`.

You may have a look at riscv_machine_timer.c, arm_arch_timer.c or hpet.c for
examples of the above.

Now... if your timer cannot generate interrupts closer than 32768 Hz appart 
then you might consider setting `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC` to 
32768 and getting rid of `SYS_CYC_PER_EVT_CYC`. This way the system will be 
aware of your timer's true precision and no relaxation of the timer test 
will be needed.

**Comment by ChiHuaL** [comment]
> This is introducing unneeded divisions and divisions are costly _especially_ 64-bits ones.
> 
> You already maintain `cyc_sys_announced`. Similarly, you just have to add some `last_elapsed` variable holding the last value your `sys_clock_elapsed()` returned, and set it to 0 when `npcx_itim_evt_isr()` is invoked. This will allow you to greatly simplify `npcx_itim_start_evt_tmr_by_tick()` like this:
> 
> ```
> static int npcx_itim_start_evt_tmr_by_tick(int32_t ticks)
> {
>         k_spinlock_key_t key = k_spin_lock(&lock);
> 
>         if (ticks == K_TICKS_FOREVER) {
>                 cyc_evt_timeout = NPCX_ITIM32_MAX_CNT;
>         } else {
>                 uint64_t delta_cycs;
> 
>                 if (ticks <= 0) {
>                         ticks = 1;
>                 }
> 
>                 delta_cycs = (last_elapsed + ticks) * SYS_CYCLES_PER_TICK;
>                 cyc_evt_timeout =
>                         MIN(DIV_ROUND_UP(delta_cycs, SYS_CYC_PER_EVT_CYC), NPCX_ITIM32_MAX_CNT);
>         }
> [...]
> ```
> 
> This way you don't have to sample npcx_itim_get_sys_cyc64() again as it is already factored into `last_elapsed`.
> 
> You may have a look at riscv_machine_timer.c, arm_arch_timer.c or hpet.c for examples of the above.

Thank you for the suggestion. I have followed the similar way of riscv_machine_timer.c/hpet.c to set the next timeout to reduce the computation overhead of uint64 division.
> Now... if your timer cannot generate interrupts closer than 32768 Hz appart then you might consider setting `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC` to 32768 and getting rid of `SYS_CYC_PER_EVT_CYC`. This way the system will be aware of your timer's true precision and no relaxation of the timer test will be needed.

For NPCX chip, it uses two hardware timer modules
1.  ITIM64 timer (system timer): It is a 64-bit timer which sources from 15 MHz to records the absolute timestamp. Our application need a higher resolution timer. That's why I set CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC = 150000000.
Please note that the  timer module cannot be configured to generate the interrupt at a **absolute** timestamp. So we use another timer module:
2. event timer: it is source from 32.768 KHz because it need to keep counting when chip enters deep sleep,
 Every time the system need to generate a timeout event, we must set it to the specific timeout count. The timeout event will generate after the timer counts down to zero.

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by npitre** [comment]
> 1. ITIM64 timer (system timer): It is a 64-bit timer which sources from 
> 15 MHz to records the absolute timestamp. Our application need a higher 
> resolution timer. That's why I set 
> CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC = 150000000.

Just to be sure: 15 MHz --> CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC = 15000000
not 150000000.

> 2. event timer: it is source from 32.768 KHz because it need to keep 
> counting when chip enters deep sleep

OK. Just make sure CONFIG_SYS_CLOCK_TICKS_PER_SEC <= 32.768 and that should
be fine.

Now a few details with the patch.

* The `last_elapsed = 0` must be within the locked area in
   `npcx_itim_evt_isr()`.

* You can migrate another 64-bits divide to 32-bits like this:

```
--- a/drivers/timer/npcx_itim_timer.c
+++ b/drivers/timer/npcx_itim_timer.c
@@ -152,16 +152,18 @@ static int npcx_itim_start_evt_tmr_by_tick(int32_t ticks)
 	} else {
 		uint64_t next_cycs;
 		uint64_t curr = npcx_itim_get_sys_cyc64();
+		uint32_t dcycles;
 
 		if (ticks <= 0) {
 			ticks = 1;
 		}
 
 		next_cycs = (last_ticks + last_elapsed + ticks) * SYS_CYCLES_PER_TICK;
-		if (unlikely((int64_t)(next_cycs - curr) <= 0)) {
+		dcycles = next_cycs - curr;
+		if (unlikely((int32_t)dcycles <= 0)) {
 			cyc_evt_timeout = 1;
 		} else {
-			cyc_evt_timeout = MIN(DIV_ROUND_UP((next_cycs - curr), SYS_CYC_PER_EVT_CYC),
+			cyc_evt_timeout = MIN(DIV_ROUND_UP(dcycles, SYS_CYC_PER_EVT_CYC),
 					      NPCX_ITIM32_MAX_CNT);
 		}
 
```

* The `DIV_ROUND_UP()` above is likely wrong. By rounding up you're likely
  to overshoot the needed waiting period. The timer subsystem already rounds
  up when necessary and it is able to cope if ticks are reported sooner.
  Please change that to a regular division. Maybe that'll even make the 
  `TIMER_TEST_MAX_STDDEV` relaxation unnecessary.

**Comment by npitre** [comment]
Code looks good.

Last question: is the change to `TIMER_TEST_MAX_STDDEV` still needed?

**Comment by ChiHuaL** [comment]
> Code looks good.
> 
> Last question: is the change to `TIMER_TEST_MAX_STDDEV` still needed?

Yes, it still needs to relax the TIMER_TEST_MAX_STDDEV.

**Review by npitre — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
