### PR TITLE
Bluetooth: Controller: Add missing nRF53x Tx Power Kconfig

### PR DESCRIPTION
**Pull request by KyraLengfeld**
This commit adds missing tx power config options for nrf53 SoCs.

### CODE REVIEW

**Review by thoh-ot — DISMISSED** [review]

**Review by AyturkDuzen — APPROVED** [review]

**Review by cvinayak — CHANGES_REQUESTED** [review]
Please change commit title to `Bluetooth: Controller: Add missing nRF53x Tx Power Kconfig`

Otherwise LGTM.

**Review by cvinayak — COMMENTED** [review]
Could you update this file too: https://github.com/zephyrproject-rtos/zephyr/blob/bc27635b0dda77ece5303297075131ce88becb29/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_txp.h

**Comment by KyraLengfeld** [comment]
> Could you update this file too: https://github.com/zephyrproject-rtos/zephyr/blob/bc27635b0dda77ece5303297075131ce88becb29/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_txp.h

Sure, do you know of any other files I should consider as well? I haven't contributed to these parts before, so I might have missed more.

**Comment by cvinayak** [comment]
> > Could you update this file too: https://github.com/zephyrproject-rtos/zephyr/blob/bc27635b0dda77ece5303297075131ce88becb29/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_txp.h
> 
> Sure, do you know of any other files I should consider as well? I haven't contributed to these parts before, so I might have missed more.

I just looked for where the others where used, and only found these. You should be good with this one file.

**Comment by KyraLengfeld** [comment]
> > > Could you update this file too: https://github.com/zephyrproject-rtos/zephyr/blob/bc27635b0dda77ece5303297075131ce88becb29/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_txp.h
> > 
> > 
> > Sure, do you know of any other files I should consider as well? I haven't contributed to these parts before, so I might have missed more.
> 
> I just looked for where the others where used, and only found these. You should be good with this one file.

I tried grepping for defines and thought to add usage of the power levels also to this file https://github.com/zephyrproject-rtos/zephyr/blob/bc27635b0dda77ece5303297075131ce88becb29/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5340.h#L430 
You can see the changes here: https://github.com/zephyrproject-rtos/zephyr/pull/60244/files#diff-95aef72be12cd1c4c85e766577ff626ab0b2adbbf8cd5058969626aa46c03b0f

**Comment by KyraLengfeld** [comment]
> > > > Could you update this file too: https://github.com/zephyrproject-rtos/zephyr/blob/bc27635b0dda77ece5303297075131ce88becb29/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_txp.h
> > > 
> > > 
> > > Sure, do you know of any other files I should consider as well? I haven't contributed to these parts before, so I might have missed more.
> > 
> > 
> > I just looked for where the others where used, and only found these. You should be good with this one file.
> 
> I tried grepping for defines and thought to add usage of the power levels also to this file
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/bc27635b0dda77ece5303297075131ce88becb29/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5340.h#L430
> 
> 
> You can see the changes here: https://github.com/zephyrproject-rtos/zephyr/pull/60244/files#diff-95aef72be12cd1c4c85e766577ff626ab0b2adbbf8cd5058969626aa46c03b0f
> Please confirm if that was correct, as only positive power levels weren't there (compared to also some negative ones in the other two files). For the 'hal_radio_tx_power_floor' function itself I wouldn't know any specifics why max should be 0dBm, when the SoC is capable of more but I might be wrong with that :)

I see that the positive values weren't added in 'hal_radio_tx_power_floor' on purpose, see https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c#L317

Therefore I removed my additions in [subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5340.h](https://github.com/zephyrproject-rtos/zephyr/pull/60244/files#diff-95aef72be12cd1c4c85e766577ff626ab0b2adbbf8cd5058969626aa46c03b0f)

**Comment by KyraLengfeld** [comment]
Seems Vinayak is in vacation. The PR should be updated according to his comments though. Requesting Thomas again, if I have two approvals I will make a request for merge.

**Review by kruithofa — APPROVED** [review]
LGTM

**Review by hermabe — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
