### PR TITLE
board: arm: add support for stm32f0_disco

### PR DESCRIPTION
**Pull request by jmtorrespalma**
Support SoC and peripherals for [`STMF0Discovery`](http://www.st.com/en/evaluation-tools/stm32f0discovery.html).

This board was released a few years ago and due to its low price and quality, got very popular and widely used so I thought it would be great for Zephyr to have mainstream support.

Simple examples have been tested and run fine, but some extra tweaking is required to get more complex examples working due to small memory (8KB RAM).

If the patch is welcomed, documentation and extra work on stm32f0 devices will be done for extra testing and support.

My only concern is about copyright assignment, I do this on my free time so I used my own name in copyright headers, please correct me if that is not the right approach.

### CODE REVIEW

**Comment by erwango** [comment]
@jmtorrespalma : can you check this is not the same board as being ported in #5855 ?

**Comment by jmtorrespalma** [comment]
@erwango seems to be exactly the same as #5855

**Comment by erwango** [comment]
>  seems to be exactly the same as #5855

So maybe you can close this one and once #5855 is merged, you can do a new PR with the additional pinmux you're offering on the board?

**Comment by jmtorrespalma** [comment]
>So maybe you can close this one and once #5855 is merged, you can do a new PR with the additional pinmux you're offering on the board?

I will wait for it to be merged and then introduce the rest of my changes rebased on it. We can still reopen here if #5855 does not end up merged

**Pull request closed without merging**
