### PR TITLE
Add strcspn and iscntrl to minimal libc

### PR DESCRIPTION
**Pull request by tgorochowik**
This PR adds the definitions for `strcspn` and `iscntrl` to the minimal libc library (strings).

### CODE REVIEW

**Review by pfalcon — APPROVED** [review]
These should have "libc: minimal: add ..." titles, otherwise look good, thanks for improving minlibc.

**Review by nashif — CHANGES_REQUESTED** [review]
I am reopening a branch I started working on last year to import a more complete base libc to replace minimal libc which includes all those functions you are adding. 

Lets put this on hold, you can add those function to the sample for now while we try to get a more complete c library.

**Comment by pfalcon** [comment]
> now while we try to get a more complete c library.

We already have "a more complete c library", it's called Newlib. What we need is to elaborate minimal libc, while keeping it minimal by the code size. Anyway, let's what that "more complete base libc" might be...

**Comment by nashif** [comment]
> a more complete c library

more complete than the minimal libc but still minimal and basic that is part of the Zephyr project. So we agree.

Not everyone wants or needs newlib.

**Comment by andrewboie** [comment]
Has anyone looked into nano-newlib as a replacement for minimal libc?
Really we need to get out of the C library business...I would prefer we just moved to third-party C libraries we can add to the west manifest and purged minimal libc from the tree completely

**Comment by nashif** [comment]
> Has anyone looked into nano-newlib as a replacement for minimal libc?

that is what I am looking into now.

**Comment by Nukersson** [comment]
> I am reopening a branch I started working on last year to import a more complete base libc to replace minimal libc which includes all those functions you are adding.
> 
> Lets put this on hold, you can add those function to the sample for now while we try to get a more complete c library.

@nashif Could you please provide the link to your active working new `new libc` implementation here?

**Pull request closed without merging**
