### PR TITLE
Fix stm32f4 usart io

### LINKED ISSUE #15349: stm32: uart fix pin pull-up
**Is your enhancement proposal related to a problem? Please describe.**
1. Pull-up are enable on the TX pins of stm32 uart, they are unnecessary and a waste of energy since TX pins are always driven by the peripheral.
2. Pull-ups are not enable on RX pins, this is a problem when the uart is not connected (a shell uart for instance).
( see defines in drivers/pinmux/stm32/pinmux_stm32).

**Describe the solution you'd like**
Remove pull-ups on outputs and enable pull-ups on inputs.

**Describe alternatives you've considered**
Enable pull-ups only on dis-connectable uart rx pins.

### PR DESCRIPTION
**Pull request by overheat**
1. Pull-ups are not enabled on RX pins. It will cause serious and very confusing communication issue when the device deployed into a real work environment.
2. Pull-up on the TX pins are unnecessary and consume power.

Fixes: #15349

### CODE REVIEW

**Comment by erwango** [comment]
This setting was actually made on purpose, cf https://github.com/zephyrproject-rtos/zephyr/pull/9519.
I think that the solution we need is a fix that switches the pin configuration after UART init (and should address whole STM32 family, not only F4 series).

**Comment by overheat** [comment]
@erwango Got it, thanks! But it is not elegant and easily confused people. I think to move the TX pin setup go with the USART controller config is a better solution. What's your opinion?

**Comment by erwango** [comment]
> move the TX pin setup go with the USART controller config is a better solution

Sorry, I did not get the point. Can you elaborate?

**Comment by overheat** [comment]
I mean like @ibisz said in #9519, "Another solution is to move the TX pin setup after the USART controller enable." is a better solution.

**Pull request closed without merging**
