### PR TITLE
drivers: sensor: lsm6dsl: Fix lsm6dsl gyroscope full range setting

### PR DESCRIPTION
**Pull request by valkjsaaa**
Bug 1: Fix lsm6dsl_gyro_set_fs_raw does not clear FS125 to register when setting the full range to be other values.

Bug 2: Fix lsm6dsl_gyro_channel_get does not use the current gyro_sensitivity when getting data from the gyroscope.

This has been tested with an STM32H7 dev board connected to LSM6DSL via SPI.

We tried the following code:
```
        struct sensor_value g_full_scale_attr;

	const int32_t g_full_scale_target_degree = 2000;

	sensor_degrees_to_rad(g_full_scale_target_degree, &g_full_scale_attr);

	if (sensor_attr_set(accel_dev, SENSOR_CHAN_GYRO_XYZ, SENSOR_ATTR_FULL_SCALE,
			    &g_full_scale_attr) < 0) {
		printk("Cannot set full scale for gyro.\n");
		return 0;
	}
```

Before the fix, the output gyroscope value is still clearly capped at ~2.2 rad/s or 125 dps, and after the fix, the value can go above the limit.

Also, thanks to Tyler Chen <tyler@skywalk.dev> for his contribution.

### CODE REVIEW

**Review by mniestroj — CHANGES_REQUESTED** [review]
Nice catch!

Please fix your commit title, as it says about "magnetometer", while code changes are related to "gyroscope" only.

Otherwise LGTM!

**Comment by valkjsaaa** [comment]
> Nice catch!
> 
> Please fix your commit title, as it says about "magnetometer", while code changes are related to "gyroscope" only.
> 
> Otherwise LGTM!

fixed ;)

**Review by mniestroj — APPROVED** [review]

**Comment by MaureenHelm** [comment]
@avisconti please take a look

**Review by avisconti — APPROVED** [review]
LGTM

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
