### PR TITLE
[TOPIC-BLE-LLCP]: Disable running the permutations of KConfig script

### PR DESCRIPTION
**Pull request by kruithofa**
Disables the running of the build of possible KConfig permutations for the refactored controller on PR
due to the runtime of > 1 hour
Instead added a single configuration in 'tests/bluetooth/init' which compiles  for one configuration-set
of the refactored controller

Signed-off-by: Andries Kruithof (Andries.Kruithof@nordicsemi.no)

### CODE REVIEW

**Review by erbr-ot — APPROVED** [review]
LGTM

**Review by thoh-ot — APPROVED** [review]

**Review by erbr-ot — APPROVED** [review]
LGTM

**Review by erbr-ot — APPROVED** [review]
Really LGTM

**Review by erbr-ot — APPROVED** [review]
No, really!

**Pull request merged**
