### PR TITLE
samples: net: echo_server: Decrease buffer for atsamr21_xpro

### LINKED ISSUE #28341: No SRAM available to link echo_server for atsamr21 with ieee802154.overlay
**Describe the bug**
From 2.3 to 2.4 the net samples pair echo-server/client increase the SRAM requirements.  Since CI doesn't build all combinations, (even for a release like 2.4.0-rc1) the problem was detected only now.

https://github.com/zephyrproject-rtos/zephyr/blob/bc8832f6c8792a541e3000fc42a914955beaf989/samples/net/sockets/echo_server/sample.yaml#L17-L19

Build error:
```
west build -b atsamr21_xpro samples/net/sockets/echo_server -- -DOVERLAY_CONFIG=overlay-802154.conf
-- west build: generating a build system
Including boilerplate (Zephyr base): /home/gfbudke/zephyros/mainline/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/gfbudke/zephyros/mainline/zephyr/samples/net/sockets/echo_server
-- Zephyr version: 2.4.0-rc1 (/home/gfbudke/zephyros/mainline/zephyr)
-- Found Python3: /usr/bin/python3.7 (found suitable exact version "3.7.3") found components:  Interpreter 
-- Found west (found suitable version "0.7.2", minimum required is "0.7.1")
-- Board: atsamr21_xpro
-- Cache files will be written to: /home/gfbudke/.cache/zephyr
-- Found toolchain: zephyr (/home/gfbudke/zephyr-sdk-0.11.3)
-- Found dtc: /home/gfbudke/zephyr-sdk-0.11.3/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/gfbudke/zephyros/mainline/zephyr/boards/arm/atsamr21_xpro/atsamr21_xpro.dts
atsamr21_xpro.dts.pre.tmp:141.28-146.5: Warning (spi_bus_bridge): /soc/sercom@42001800: node name for SPI buses should be 'spi'
  also defined at atsamr21_xpro.dts.pre.tmp:285.10-289.3
  also defined at atsamr21_xpro.dts.pre.tmp:402.10-422.3
<stdout>: Warning (spi_bus_reg): Failed prerequisite 'spi_bus_bridge'
atsamr21_xpro.dts.pre.tmp:101.29-105.5: Warning (unique_unit_address_if_enabled): /soc/pinmux@41004400: duplicate unit-address (also used in node /soc/gpio@41004400)
atsamr21_xpro.dts.pre.tmp:106.29-110.5: Warning (unique_unit_address_if_enabled): /soc/pinmux@41004480: duplicate unit-address (also used in node /soc/gpio@41004480)
atsamr21_xpro.dts.pre.tmp:221.24-227.5: Warning (unique_unit_address_if_enabled): /soc/gpio@41004500: duplicate unit-address (also used in node /soc/pinmux@41004500)
-- Generated zephyr.dts: /home/gfbudke/zephyros/mainline/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/gfbudke/zephyros/mainline/zephyr/build/zephyr/include/generated/devicetree_unfixed.h
Parsing /home/gfbudke/zephyros/mainline/zephyr/samples/net/sockets/echo_server/Kconfig
Loaded configuration '/home/gfbudke/zephyros/mainline/zephyr/boards/arm/atsamr21_xpro/atsamr21_xpro_defconfig'
Merged configuration '/home/gfbudke/zephyros/mainline/zephyr/samples/net/sockets/echo_server/prj.conf'
Merged configuration '/home/gfbudke/zephyros/mainline/zephyr/samples/net/sockets/echo_server/boards/atsamr21_xpro.conf'
Merged configuration 'overlay-802154.conf'
Configuration saved to '/home/gfbudke/zephyros/mainline/zephyr/build/zephyr/.config'
Kconfig header saved to '/home/gfbudke/zephyros/mainline/zephyr/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/gfbudke/zephyr-sdk-0.11.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gfbudke/zephyros/mainline/zephyr/build
-- west build: building application
[1/192] Preparing syscall dependency handling

[187/192] Linking C executable zephyr/zephyr_prebuilt.elf
FAILED: zephyr/zephyr_prebuilt.elf 
: && ccache /home/gfbudke/zephyr-sdk-0.11.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc    zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj  -o zephyr/zephyr_prebuilt.elf  -Wl,-T zephyr/linker.cmd -Wl,-Map=/home/gfbudke/zephyros/mainline/zephyr/build/zephyr/zephyr_prebuilt.map -Wl,--whole-archive app/libapp.a zephyr/libzephyr.a zephyr/arch/common/libarch__common.a zephyr/arch/arch/arm/core/aarch32/libarch__arm__core__aarch32.a zephyr/arch/arch/arm/core/aarch32/cortex_m/libarch__arm__core__aarch32__cortex_m.a zephyr/lib/libc/minimal/liblib__libc__minimal.a zephyr/lib/posix/liblib__posix.a zephyr/boards/arm/atsamr21_xpro/libboards__arm__atsamr21_xpro.a zephyr/subsys/net/libsubsys__net.a zephyr/subsys/net/l2/ieee802154/libsubsys__net__l2__ieee802154.a zephyr/subsys/net/ip/libsubsys__net__ip.a zephyr/subsys/net/lib/config/libsubsys__net__lib__config.a zephyr/subsys/net/lib/conn_mgr/libsubsys__net__lib__conn_mgr.a zephyr/subsys/random/libsubsys__random.a zephyr/drivers/gpio/libdrivers__gpio.a zephyr/drivers/spi/libdrivers__spi.a zephyr/drivers/serial/libdrivers__serial.a -Wl,--no-whole-archive zephyr/kernel/libkernel.a zephyr/CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj -L"/home/gfbudke/zephyr-sdk-0.11.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/9.2.0/thumb/v6-m/nofp" -L/home/gfbudke/zephyros/mainline/zephyr/build/zephyr -lgcc -Wl,--print-memory-usage zephyr/arch/common/libisr_tables.a -mcpu=cortex-m0plus -mthumb -mabi=aapcs -Wl,--gc-sections -Wl,--build-id=none -Wl,--sort-common=descending -Wl,--sort-section=alignment -Wl,-u,_OffsetAbsSyms -Wl,-u,_ConfigAbsSyms -nostdlib -static -no-pie -Wl,-X -Wl,-N -Wl,--orphan-handling=warn && :
Memory region         Used Size  Region Size  %age Used
           FLASH:      123168 B       256 KB     46.98%
            SRAM:       32832 B        32 KB    100.20%
        IDT_LIST:          56 B         2 KB      2.73/home/gfbudke/zephyr-sdk-0.11.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/9.2.0/../../../../arm-zephyr-eabi/bin/ld: zephyr/zephyr_prebuilt.elf section `noinit' will not fit in region `SRAM'
/home/gfbudke/zephyr-sdk-0.11.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/9.2.0/../../../../arm-zephyr-eabi/bin/ld: section .intList VMA [0000000020008000,0000000020008037] overlaps section noinit VMA [00000000200039d0,000000002000803f]
/home/gfbudke/zephyr-sdk-0.11.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/9.2.0/../../../../arm-zephyr-eabi/bin/ld: region `SRAM' overflowed by 64 bytes
collect2: error: ld returned 1 exit status
%
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/gfbudke/zephyros/mainline/zephyr/build
```

**To Reproduce**
1. west build -b atsamr21_xpro samples/net/sockets/echo_server -- -DOVERLAY_CONFIG=overlay-802154.conf
2. See error

**Expected behavior**
Build on CI and locally with errors.

**Impact**
This implies that CI is not trustworthy or Zephyr doesn't rely care about it. This just confirms what already was addressed at #27151. CI should run the minimal configuration to ensure that all paths are covered. It should tell to people that something is not right. "A CI that don't work as expected is worst than not have a CI".

CI should run all configurations for release otherwise is useless.

**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK 0.11.3
 - Commit bc8832f6c8

### PR DESCRIPTION
**Pull request by nandojve**
From 2.3 to 2.4 the net samples pair echo-server/client increase the SRAM requirements. Since CI doesn't build all combinations, (even for a release like 2.4.0-rc1) the problem was detected only now.  Decrease buffers for atsamr21_xpro on both echo_server/client sample pair.

Fixes #28341.

Signed-off-by: Gerson Fernando Budke <nandojve@gmail.com>

### CODE REVIEW

**Comment by nandojve** [comment]
sanitycheck error is not related with this PR:

```
CMake Error at /usr/local/share/cmake-3.13/Modules/TestBigEndian.cmake:49 (message):
  no suitable type found
Call Stack (most recent call first):
  /var/lib/buildkite-agent/zephyr-module-cache/modules/lib/openthread/CMakeLists.txt:50 (TEST_BIG_ENDIAN)

-- Configuring incomplete, errors occurred!
See also "/workdir/zephyr/sanity-out/nrf52840dk_nrf52840/samples/net/sockets/echo_client/sample.net.sockets.echo_client.nrf_openthread/CMakeFiles/CMakeOutput.log".
See also "/workdir/zephyr/sanity-out/nrf52840dk_nrf52840/samples/net/sockets/echo_client/sample.net.sockets.echo_client.nrf_openthread/CMakeFiles/CMakeError.log".
```

It seems more evidence that CI not run all configs: #27151

**Review by jukkar — COMMENTED** [review]
Change looks ok, I just wonder how usable the application is after these changes. How well you tested this?

**Comment by nandojve** [comment]
> Change looks ok, I just wonder how usable the application is after these changes. How well you tested this?

Hi @jukkar, both client/server are working OK using samr21 and combining with sam4e + rf231 for instance.
I'll add DNM to add netif at board yaml file.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
