### PR TITLE
drivers: ieee802154: fix ACK length handling

### PR DESCRIPTION
**Pull request by edmont**
OpenThread expects the FCS field at the end of the ACK frame to be passed with `otPlatRadioTxDone`.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by aurel32** [comment]
This PR seems to adds a lot of logs messages each time a packet is sent:

```
[00:01:01.879,577] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.896,209] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.907,623] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.921,020] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.932,434] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.946,807] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.960,205] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.972,625] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.984,008] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:01.996,398] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:02.001,770] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:02.013,214] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:02.020,629] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:02.035,095] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
[00:01:02.047,180] <inf> ieee802154_nrf5: ACK packet not handled - releasing.
```

Is it related to some other changes that need to go together?

**Comment by rlubos** [comment]
Must've been an overlook, @edmont you should also increase the expected ACK length at https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/openthread/platform/radio.c#L45

**Review by rlubos — CHANGES_REQUESTED** [review]
Just not to get merged prematurely

**Review by rlubos — APPROVED** [review]
Thanks.

**Comment by aurel32** [comment]
Thanks, I confirm that the log messages have disappeared.

**Pull request merged**
