### PR TITLE
net: ieee802154: Extend TX API with TX mode

### PR DESCRIPTION
**Pull request by rlubos**
Introduce TX mode parameter in the `tx` API:
* Existing drivers will use `IEEE802154_TX_MODE_DIRECT` if they did not report CSMA/CA capability or `IEEE802154_TX_MODE_CSMA_CA` if they did.
* Add CSMA/CA support to `ieee802154_nrf5`.
* Use the new feature in OpenThread.

### CODE REVIEW

**Comment by rlubos** [comment]
FYI @MarekPorwisz @tkons

**Review by tbursztyka — APPROVED** [review]
just fix the checkpatch finding

**Review by MarekPorwisz — APPROVED** [review]

**Review by nandojve — APPROVED** [review]

**Comment by rlubos** [comment]
Looks that the CI in this PR is affected by #23625 (due to hal_nordic update). I'll monitor it and rebase once #23625 is sorted out.

**Comment by rlubos** [comment]
`hal_nordic` dependency got merged, `west.yml` updated. From my side, the PR is ready to merge.

**Review by mariuszpos — APPROVED** [review]

**Comment by rlubos** [comment]
@jukkar Could we merge already or do we wait for more feedback?

**Review by jukkar — APPROVED** [review]

**Pull request merged**
