### PR TITLE
dts: bindings: adc: add shunt sensor

### PR DESCRIPTION
**Pull request by ualbertagreen**
Add bindings for a current sensor using a shunt resistor.

Signed-off-by: Jason Yuan <jasonyuan@google.com>

### CODE REVIEW

**Review by x64x2 — DISMISSED** [review]

**Review by galak — COMMENTED** [review]
Is there some code that goes along or utilizes this?

**Review by galak — CHANGES_REQUESTED** [review]
Does the following binding cover what you need:

https://www.kernel.org/doc/Documentation/devicetree/bindings/iio/afe/current-sense-shunt.yaml

If so, lets follow that binding for this purpose

**Comment by ualbertagreen** [comment]
> Does the following binding cover what you need:
> 
> https://www.kernel.org/doc/Documentation/devicetree/bindings/iio/afe/current-sense-shunt.yaml
> 
> If so, lets follow that binding for this purpose

The binding has been edited to be the same as the Linux standard; however, I have kept the `gain` property in there because most of the time a shunt resistor is used, the shunt voltage need to be amplified to be measured. The `gain` property has a default of 1 so the binding can be used the same way as the Linux binding when the property is not desired.

**Review by fabiobaltieri — APPROVED** [review]
May make sense to followup on a separate PR with a sample to use this, maybe even having some common code under adc to handle both this and `voltage-divider` (which right now is only used under a board specific sample), at least for the data structure that holds this and some macro helper to populate it from the device tree.

**Comment by ualbertagreen** [comment]
Hi @galak could you review again? Thanks.

**Comment by galak** [comment]
as @fabiobaltieri said I'd like to see some code that actually utilizes this.  We don't normally take bindings w/o some code utilizing it in zephyr itself.

**Comment by ualbertagreen** [comment]
> as @fabiobaltieri said I'd like to see some code that actually utilizes this. We don't normally take bindings w/o some code utilizing it in zephyr itself.

I'm stacking this Pr with #54286 so that the binding and the code that utilize it can be viewed at the same place. Closing this one.

**Comment by fabiobaltieri** [comment]
@ualbertagreen I think that the request was to have some *code* that utilize the binding. Like a sample, not a dts file. It would make more sense to have the binding and a sample on this PR and the specific board instantiation on a separate PR, but regardless there's no sample code in https://github.com/zephyrproject-rtos/zephyr/pull/54286 either.

**Comment by ualbertagreen** [comment]
> @ualbertagreen I think that the request was to have some _code_ that utilizes the binding. Like a sample, not a dts file. It would make more sense to have the binding and a sample on this PR and the specific board instantiation on a separate PR, but regardless there's no sample code in #54286 either.

Right but I can't have a sample code that utilizes this binding without a board that utilizes this binding, and the only board I have with a current sensor is the Twinkie. So to me it made more sense to stack everything together. I've commented in the other PR about my plans to add a sample code.

**Pull request closed without merging**
