### PR TITLE
drivers: display: display_mcux_elcdif: Add power management

### PR DESCRIPTION
**Pull request by pdgendt**
Add suspend/resume actions for the MCUX eLCDIF display driver.

### CODE REVIEW

**Review by gmarull — COMMENTED** [review]
how is this expected to be used? Could you add support for runtime PM?

**Comment by pdgendt** [comment]
> how is this expected to be used?

For example, on the `mimxrt1064_evk` board using `CONFIG_PM` to enable the suspend mode, this is required to stop the `DOTCLK` during the suspend.

> Could you add support for runtime PM?

On my custom board I have application code that, with `CONFIG_PM_DEVICE_RUNTIME` enabled, suspends the display before the system suspend. Is this what you mean @gmarull ?

**Comment by pdgendt** [comment]
@danieldegrasse would it be possible for you to create a test/sample on the `mimxrt1064_evk` board with the low power suspend/resume and a display connected?
I think this PR would be required to make that work.

**Comment by dleach02** [comment]
> @danieldegrasse would it be possible for you to create a test/sample on the `mimxrt1064_evk` board with the low power suspend/resume and a display connected? I think this PR would be required to make that work.

@pdgendt I think you should add the test/sample as part of your PR.

**Comment by pdgendt** [comment]
> @pdgendt I think you should add the test/sample as part of your PR.

@dleach02 @danieldegrasse What I suggested was to run an existing sample, like the `lvgl` one, but with `CONFIG_PM` and `CONFIG_PM_DEVICE` enabled on the `EVK` with a display.

**Comment by DerekSnell** [comment]
> @dleach02 @danieldegrasse What I suggested was to run an existing sample, like the `lvgl` one, but with `CONFIG_PM` and `CONFIG_PM_DEVICE` enabled on the `EVK` with a display.

Hi @pdgendt ,
Unfortunately I see issues when I try your test.  I am using the MIMXRT1064-EVK board with the build command below.  Initially the app works, the "hello world" button is displayed, and the seconds are updated.  Tapping the button initially works well too.  But I found if I tap the button a few times, the app crashes and the display goes white.  If I build the same LVGL sample in your PR without selecting the `CONFIG_PM` Kconfigs, I can tap the button 50+ times without any issue.

```
west build -b mimxrt1064_evk samples\subsys\display\lvgl --pristine -- -DCONFIG_PM=y -DCONFIG_PM_DEVICE=y
```

Are you able to replicate this?  Thanks

**Comment by pdgendt** [comment]
> Unfortunately I see issues when I try your test. I am using the MIMXRT1064-EVK board with the build command below. 

Hi @DerekSnell,

Is this with or without the changes from this PR? I don't have issues when the low power mode isn't used, but I do need the changes if `CONFIG_PM` and `CONFIG_PM_DEVICE` are enabled.

**Comment by DerekSnell** [comment]
> That's too bad. Would you be able to test without the PR changes, but with `CONFIG_PM` and `CONFIG_PM_DEVICE` enabled, to verify that this also isn't broken?

Hi @pdgendt ,
I tested from main branch (9d2fe69b4efcbf0959f8ec9c1fe07157d50d8450) using the same build command below.  The LVGL sample does not run correctly.  The display backlight comes on, but the display is all white.  I am also unable to reflash it in this state, which indicates the MCU is always in the low-power mode.

I also tested from the commit a5e301e06feaaedd291c88ec895f19406ad4e2ae your PR is based on, and I see the same issue.

```
west build -b mimxrt1064_evk samples\subsys\display\lvgl --pristine -- -DCONFIG_PM=y -DCONFIG_PM_DEVICE=y
```

**Comment by pdgendt** [comment]
Thanks @DerekSnell for testing this.

Does this imply that the display driver for the EVK doesn't work with the `PM` options enabled? Does it make sense to open an issue, or is this not a supported use case?

I guess that low power modes are tricky to get working with all/any other samples.

**Comment by DerekSnell** [comment]
> Does this imply that the display driver for the EVK doesn't work with the `PM` options enabled? Does it make sense to open an issue, or is this not a supported use case?

Hi @pdgendt ,
I do not think we should assume this is an issue with the display driver.  All we know at the moment is that the LVGL sample does not function correctly in this configuration.  Someone will need to investigate to determine the cause.

Yes, it makes sense to create an Issue for this.  I would add as an Enhancement request, not a bug, since this sample was not a requirement when the PM feature was added and tested.  Plus, I don't think this limitation needs to hinder future releases.

Are you willing to create that issue?  And reference this PR?  Thanks

**Comment by pdgendt** [comment]
> Yes, it makes sense to create an Issue for this. I would add as an Enhancement request, not a bug, since this sample was not a requirement when the PM feature was added and tested. Plus, I don't think this limitation needs to hinder future releases.
> 
> Are you willing to create that issue? And reference this PR? Thanks

Done

**Comment by pdgendt** [comment]
Closing for now

**Pull request closed without merging**
