### PR TITLE
LwM2M changes #1

### PR DESCRIPTION
**Pull request by mike-scott**
- Selecting the LwM2M library should automatically select NET_APP_CLIENT
- Removed NET_APP and NET_APP_CLIENT in LwM2M samples .conf files.
- Removed unused CONFIG_NET_L2_BT source in LwM2M samples as there is no .conf file to support BT.

### CODE REVIEW

**Comment by mike-scott** [comment]
@rbtchc please take a long and as soon as this is merged I will post set #2

**Comment by rbtchc** [comment]
LGTM

**Comment by mike-scott** [comment]
@jukkar Please take a look.  These should be fairly easy to merge.

**Review by jukkar — APPROVED** [review]
Looks just fine

**Pull request merged**
