### PR TITLE
PM: Add testing pm_device_state_str function in device_driver_init testcase.

### PR DESCRIPTION
**Pull request by gbarkadiusz**
Add calling the pm_device_state_str function to increase code coverage of subsys/pm/device.c file.

### CODE REVIEW

**Comment by nashif** [comment]
can't this be added to some existing PM test?

**Comment by gbarkadiusz** [comment]
It can be added to existing PM tests. For example to [pm/device_driver_init](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/subsys/pm/device_driver_init) test.

**Comment by gbarkadiusz** [comment]
@nashif According to your recommendation, I've added additional function to already existing test.

**Review by tmleman — DISMISSED** [review]

**Review by ceolin — CHANGES_REQUESTED** [review]
instead of just calling `pm_device_state_str()` you probably could check the return of this function.  Something like:
```
zassert_not_null(pm_device_state_str(state), "Device state str is NULL"); 
/* have to change according the state you expect here */
zassert_equal(strcmp("active",  pm_device_state_str(state)), 0, "Invalid device state str"); 
```

**Comment by gbarkadiusz** [comment]
@ceolin Adding `zassert_not_null(pm_device_state_str(state), "Device state str is NULL");` seems to be enough because checking appropriate state according to expected is already tested.
`zassert_equal(state, value, "Unexpected device state");`

**Comment by ceolin** [comment]
> @ceolin Adding `zassert_not_null(pm_device_state_str(state), "Device state str is NULL");` seems to be enough because checking appropriate state according to expected is already tested. `zassert_equal(state, value, "Unexpected device state");`

The state is checked indeed, but you are checking the state string which is different. Just checking that `pm_device_state_str(state)` is not null is incomplete, you should check that this function is also return a correct string.

**Review by ceolin — APPROVED** [review]

**Comment by ceolin** [comment]
> > > @ceolin Adding `zassert_not_null(pm_device_state_str(state), "Device state str is NULL");` seems to be enough because checking appropriate state according to expected is already tested. `zassert_equal(state, value, "Unexpected device state");`
> > 
> > 
> > The state is checked indeed, but you are checking the state string which is different. Just checking that `pm_device_state_str(state)` is not null is incomplete, you should check that this function is also return a correct string.
> 
> @ceolin Could you take a look again?

Thanks !

**Comment by ceolin** [comment]
@JordanYates  @nashif  could please take a look on this ?

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
oops

**Pull request merged**
