### PR TITLE
github: security: Fix supported versions

### PR DESCRIPTION
**Pull request by ceolin**
Update supported versions in the github security
policy.

### CODE REVIEW

**Comment by ceolin** [comment]
Not sure if we should update directly to 3.5 though.

**Review by nashif — DISMISSED** [review]

**Comment by kartben** [comment]
> Not sure if we should update directly to 3.5 though.

... and then update again on Oct 31 (EOL for 3.3), etc. 
If you don't mind an external link then maybe you should just point to https://docs.zephyrproject.org/latest/releases/index.html#supported-releases ?

**Review by stephanosio — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@ceolin I think it would make sense to mention 3.5 directly into this so we can merge it and have the documentation snapshot referring to the current version.

**Comment by fabiobaltieri** [comment]
> That is not part of the documentation AFAIK, this is for the page that appears when you click in the security tab in Zephyr's github page. I can move directly to next release though, since we are just a few days from there.

Hey, we talked about this in the release meeting and think that there's some consensus that this should probably point at 3.5. Could you make the change please?

**Comment by ceolin** [comment]
> > That is not part of the documentation AFAIK, this is for the page that appears when you click in the security tab in Zephyr's github page. I can move directly to next release though, since we are just a few days from there.
> 
> Hey, we talked about this in the release meeting and think that there's some consensus that this should probably point at 3.5. Could you make the change please?

yep, absolutely. Done

**Review by fabiobaltieri — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
