### PR TITLE
soc: esp32s3: added initial support

### PR DESCRIPTION
**Pull request by sylvioalves**
This brings initial support to ESP32-S3 SoC and ESP32-S3 DevKitM board.

### CODE REVIEW

**Comment by sylvioalves** [comment]
@carlescufi, CI is failing due to typedef used in `pincontrol` content. Is is already been used elsewhere:  
```c
 NEW_TYPEDEFS: do not add new typedefs
File:soc/xtensa/esp32s3/pinctrl_soc.h
Line:23
Error: Process completed with exit code 1.
```

Can this be accepted?

**Comment by sylvioalves** [comment]
PR is ready for review. Twister will fail as toolchain is not yet added into current SDK. All twister tests passed in local environment when running `./scripts/twister -p esp32s3_devkitm`.

**Review by uLipe — DISMISSED** [review]
LGTM.

**Review by LucasTambor — DISMISSED** [review]

**Review by marekmatej — DISMISSED** [review]

**Comment by sylvioalves** [comment]
@stephanosio, would you check this and let me know how to proceed?

**Comment by sylvioalves** [comment]
@carlescufi, anyway you can check this PR and evaluate next action? ESP32-S3 SDK is still pending as well: https://github.com/zephyrproject-rtos/sdk-ng/pull/612

**Comment by stephanosio** [comment]
> @stephanosio, would you check this and let me know how to proceed?

https://github.com/zephyrproject-rtos/sdk-ng/pull/612#issuecomment-1362279159

We are currently in feature merge freeze for the upcoming v3.3 release. This PR can be merged after v3.3 is released and merge window is open again.

**Review by marekmatej — DISMISSED** [review]

**Review by mniestroj — DISMISSED** [review]

**Comment by carlescufi** [comment]
@sylvioalves can you please check why CI is failing?

**Comment by sylvioalves** [comment]
> @sylvioalves can you please check why CI is failing?

@carlescufi CI fails because ESP32-S3 toolchain isn't available yet. @stephanosio, any updates on this?

**Review by uLipe — APPROVED** [review]

**Comment by sylvioalves** [comment]
Last push was to change `toolchain: espressif` in order to make CI to pass and let this be merged. Once SDK 0.16.0 gets released, I submit another PR enabling S3 to work with Zephyr's troolchain.

**Review by mniestroj — APPROVED** [review]

**Pull request merged**
