### PR TITLE
samples: Add wasm-micro-runtime samples

### PR DESCRIPTION
**Pull request by wenyongh**
A hello world sample and an app manager sample.

Signed-off-by: Wenyong Huang <wenyong.huang@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
@wenyongh  Can you please stop closing and creating new PRs? You should be able to update the same PR with any changes required, you do not need to close and open a new PR for each iteration.

**Comment by wenyongh** [comment]
> @wenyongh Can you please stop closing and creating new PRs? You should be able to update the same PR with any changes required, you do not need to close and open a new PR for each iteration.

@nashif , really sorry to disturb you all! I am not so familiar with the patch commit procedure, it checks so strictly, and some errors seem not easy to fix. Sorry again, I will try again without creating new PR. Thanks a lot!

**Comment by utzig** [comment]
> > @wenyongh Can you please stop closing and creating new PRs? You should be able to update the same PR with any changes required, you do not need to close and open a new PR for each iteration.
> 
> @nashif , really sorry to disturb you all! I am not so familiar with the patch commit procedure, it checks so strictly, and some errors seem not easy to fix. Sorry again, I will try again without creating new PR. Thanks a lot!

Your commit message must be broken in max 72 columns. When you change something, fixup/squash the commit and force-push, there is not need to close and open a new PR.

**Comment by wenyongh** [comment]
@utzig thanks a lot! I have updated the commit message to fix the max 72 columns broken issue, and committed my own repo with a small change, but it still reports the same error, what should I do? How to "fixup/squash the commit and force-push"?

**Comment by utzig** [comment]
> @utzig thanks a lot! I have updated the commit message to fix the max 72 columns broken issue, and committed my own repo with a small change, but it still reports the same error, what should I do? How to "fixup/squash the commit and force-push"?

Well, not easy to summarize in a message, but you should read this: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell. `fixup` and `squash` are operations on `rebase` (which is a git command/operation), force-push means `git push --force`. You should also use a branch when developing some feature, not `master` as you are doing. Reading the chapter in the book above should help clarify this...

**Comment by wenyongh** [comment]
@utzig thanks a lot, I know the rebase, squash and push -f  operations of git, we usually use them in command line, but the issue is that how to use these commands to operate the PR under command line instead of UI? In zephyr master repo or my own repo? I have updated the commit message, but it still reports max 72 columns broken error in Commit 9956514fd9:
    3: UC4 Line exceeds max length (148>72): ...

What the commit 9956514fd9 is? I checked all the commits, but cannot find a commit named "9956514fd9". And why it doesn't take effect after I updated the title and commit message, and even submitted a new commit in my own repo? Should I download the github tool?

**Pull request closed without merging**
