### PR TITLE
tests: subsys: sensing: set CONFIG_EMUL=y

### LINKED ISSUE #73846: tests/subsys/sensing/ failing to build in main
**Describe the bug**
tests/subsys/sensing/ is failing to build in main

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=native_sim  ../tests/subsys/sensing/
3. ninja

**Expected behavior**
No build failures or warnings

**Impact**
CI failing in multiple PRs, main CI failing.

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/9397269764/job/25880300357 

**Environment (please complete the following information):**
 - OS: CI (Ubuntu 22.04)
 - Toolchain (e.g Zephyr SDK, ...): gcc 11 or 12
 - Commit SHA or Version used: main as of now c5e591bf44f90bd0ad93e173663e419d68c86d55

**Additional context**
Introduced by #73124 
https://github.com/zephyrproject-rtos/zephyr/commit/a736f150f7e64a63df8d1c7fb3d5321bd2357078

Note: The test built with warnings already in the PR branch.

### PR DESCRIPTION
**Pull request by fabiobaltieri**
The test is broken in CI because the emulated spi bus is not built in, adding an explicit CONFIG_EMUL=y to the test config.

Edit by @aescolar:
* issue introduced by #73124
* Fixes #73846

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by martinjaeger** [comment]
Thanks for the quick fix. This is still giving me a compiler warning:

```
$ west build -p -b native_sim tests/subsys/sensing -T subsys.sensing 
[...]
In function ‘sensor_later_config’,
    inlined from ‘sensing_runtime_thread’ at zephyr/subsys/sensing/sensor_mgmt.c:230:5:
zephyr/subsys/sensing/sensor_mgmt.h:29:73: warning: array subscript -1 is outside array bounds of ‘struct sensing_sensor[16777215]’ [-Warray-bounds=]
[...]
```

Maybe something to be fixed outside this PR?

**Comment by fabiobaltieri** [comment]
> Maybe something to be fixed outside this PR? Let's see if it passes CI.

Yeah I don't see that in https://github.com/zephyrproject-rtos/zephyr/actions/runs/9397269764/job/25880300357 for some reasons, if you have an obvious fix for that we can add it up but if CI passes as is we can handle it separately.

**Comment by martinjaeger** [comment]
> Yeah I don't see that in https://github.com/zephyrproject-rtos/zephyr/actions/runs/9397269764/job/25880300357 for some reasons, if you have an obvious fix for that we can add it up but if CI passes as is we can handle it separately.

Had a quick look, but didn't fully understand the `for_each_sensor_reverse` macro, yet. Interesting that it passes LLVM build, which is usally quite pedantic ;)

**Comment by aescolar** [comment]
@fabiobaltieri I'd just revert the PR. The build warnings were there already in the PR and I don't think it went  thru proper review

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
