### PR TITLE
samples: boards: Merge nrf91/ with nrf52/ and rename it to nrf/

### PR DESCRIPTION
**Pull request by anangl**
The following samples:
- boards/nrf91/nrfx
- boards/nrf52/power_mgr

are actually not specific to nRF91 and nRF52 Series SoCs, respectively,
hence the current naming of the above board/ subdirectories may be
misleading. Thus, use nrf/ directory for holding all nRF board specific
samples that apply to several boards.

Relates to #20779.

### CODE REVIEW

**Review by ulfalizer — COMMENTED** [review]
Looks like there's some references that need to be updated too (at least in docs):

```
$ git grep samples/boards/nrf52/
doc/releases/release-notes-1.14.rst:* :github:`9290` - [Coverity CID :187325] Control flow issues in /samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/src/mesh/device_composition.c
doc/releases/release-notes-1.14.rst:* :github:`9289` - [Coverity CID :187326] Control flow issues in /samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/src/mesh/device_composition.c
doc/releases/release-notes-2.0.rst:* :github:`15771` - [Coverity CID :198010]Control flow issues in /samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/src/storage.c
samples/boards/nrf52/mesh/onoff-app/README.rst:This sample can be found under :zephyr_file:`samples/boards/nrf52/mesh/onoff-app` in the
samples/boards/nrf52/mesh/onoff-app/README.rst:   :zephyr-app: samples/boards/nrf52/mesh/onoff-app
samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/README.rst:This sample can be found under :zephyr_file:`samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app` in the
samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/README.rst:   :zephyr-app: samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app
samples/boards/nrf52/power_mgr/README.rst:   :zephyr-app: samples/boards/nrf52/power_mgr
scripts/sanity_chk/sanity_last_release.csv:samples/boards/nrf52/power_mgr/sample.board.nrf52.pm.low_power_state,arm,nrf51_pca10028,True,,,False,,15673,13883
scripts/sanity_chk/sanity_last_release.csv:samples/boards/nrf52/mesh/onoff-app/sample.bluetooth.mesh.onoff,arm,nrf52840_pca10056,True,,,False,,182004,178897
scripts/sanity_chk/sanity_last_release.csv:samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/sample.bluetooth.mesh.onoff_level_lighting_vnd,arm,nrf52840_pca10056,True,,,False,,171081,149757
scripts/sanity_chk/sanity_last_release.csv:samples/boards/nrf52/power_mgr/sample.board.nrf52.pm.low_power_state,arm,nrf52840_pca10056,True,,,False,,17730,16667
scripts/sanity_chk/sanity_last_release.csv:samples/boards/nrf52/power_mgr/sample.board.nrf52.pm.low_power_state,arm,nrf52_pca10040,True,,,False,,17674,16567
```

```
$ git grep samples/boards/nrf91/
samples/boards/nrf91/nrfx/README.rst:The code can be found in :zephyr_file:`samples/boards/nrf91/nrfx`.
samples/boards/nrf91/nrfx/README.rst:   :zephyr-app: samples/boards/nrf91/nrfx
```

**Comment by anangl** [comment]
Updated paths to samples mentioned in their documentation. @ulfalizer thanks for pointing them out.
Not sure if I should update the paths in `sanity_last_release.csv`. I'm not familiar with scripts that use this file.

**Review by pabigot — COMMENTED** [review]
This makes sense, with one minor concern:  Do all of these examples build on all Nordic platforms?  I'm wondering about the nrf52 mesh example, which might not fit in the nrf51.  Should the example documentation indicate when a SOC family won't work with it?

**Comment by anangl** [comment]
> This makes sense, with one minor concern: Do all of these examples build on all Nordic platforms?

No, for sure the mesh examples cannot be built for nRF91, for instance. As I see it, placing these examples in `nrf/` directory does not imply they should be buildable for all nRF SoCs, it rather indicates that they are nRF specific, so they can't be used on other platforms.

> I'm wondering about the nrf52 mesh example, which might not fit in the nrf51. Should the example documentation indicate when a SOC family won't work with it?

Currently the documentation in both mesh examples states "This sample has been tested on the Nordic nRF52840-PDK board, but would likely also run on the nrf52_pca10040 board". Is that not enough?

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> This makes sense, with one minor concern: Do all of these examples build on all Nordic platforms? I'm wondering about the nrf52 mesh example, which might not fit in the nrf51. Should the example documentation indicate when a SOC family won't work with it?

I agree with @anangl. I understand that the top-level name is a bit misleading, but I still think this is the better middle-ground between being very specific and ending up with a reasonable folder layout.

**Comment by pabigot** [comment]
> I agree with @anangl. I understand that the top-level name is a bit misleading, but I still think this is the better middle-ground between being very specific and ending up with a reasonable folder layout.

I don't have a problem with moving things under one roof, I just thought it might be worth going a little further to make it easy for people looking at the samples to determine whether they were relevant to their targets.

**Review by dbkinder — APPROVED** [review]
doc changes LGTM

**Review by dbkinder — COMMENTED** [review]
FYI, Since we're moving samples and not board documentation around, I don't feel compelled to put a redirect link in place where the old sample docs were (done in ``doc/conf.py``)

**Comment by carlescufi** [comment]
> > I agree with @anangl. I understand that the top-level name is a bit misleading, but I still think this is the better middle-ground between being very specific and ending up with a reasonable folder layout.
> 
> I don't have a problem with moving things under one roof, I just thought it might be worth going a little further to make it easy for people looking at the samples to determine whether they were relevant to their targets.

Let's follow this up with documentation.

**Pull request merged**
