### PR TITLE
Various LwM2M Changes

### PR DESCRIPTION
**Pull request by mike-scott**
I've had these 5 patches in my local queue for a while now, and figured I would never submit them due to the incoming socket re-work.

However, it might be that someone is using the current LwM2M work and I think these should go ahead and be applied.

### CODE REVIEW

**Comment by mike-scott** [comment]
ci-retest

**Comment by mike-scott** [comment]
(retesting w/ better sanity coverage)

**Comment by mike-scott** [comment]
ci-recheck

**Comment by mike-scott** [comment]
recheck

**Comment by mike-scott** [comment]
@jukkar let me know if we're willing to pull in a few fixes to the net_buf LwM2M lib or if we're basically not accepting any more fixes.

**Comment by rveerama1** [comment]
@mike-scott jukka is on holiday. I will @tbursztyka to comment on it.

**Review by tbursztyka — APPROVED** [review]
lgtm

**Pull request merged**
