### PR TITLE
irq: doc: fix misspelled reference to k_spinlock

### PR DESCRIPTION
**Pull request by kartben**
k_spinlock_t might have actually never existed (?) Rename to k_spinlock.

### CODE REVIEW

**Review by andyross — DISMISSED** [review]
Indeed, we never had a typedef for the spinlock, only `k_spinlock_key_t`.  Surely a typo.  FWIW: pedantically it would be `struct k_spinlock` and not just `k_spinlock` as it's not a symbol.  But I really doubt we're consistent at that level in the docs.  Really I think English might be best here: "... implementation of spinlocks is correct."

**Review by nashif — DISMISSED** [review]

**Comment by kartben** [comment]
> Really I think English might be best here: "... implementation of spinlocks is correct."

I tend to agree. Updated, thanks!

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Comment by kartben** [comment]
rebased to get hotfix #73806 that was causing CI to fail.

**Review by dcpleung — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Comment by kartben** [comment]
rebased again this time due to #73872. Hopefully CI will be green now :)

**Review by aescolar — APPROVED** [review]

**Pull request merged**
