### PR TITLE
usb: device: hid: instance definition in devicetree

### PR DESCRIPTION
**Pull request by XenuIsWatching**
If a device had more than 1 hid defined, there was an issue where all the hids defined would get the same configurations from the KConfigs, and each HID interface couldn't get separate settings. This moves those definitions in to devicetree.

### CODE REVIEW

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Under no circumstances will enspoints and their properties be described in devicetree.  This is property served by software configuration, may be present but need not be used. Even with new device support where relevant Kconfig options no longer play a role, no chance for this.

**Comment by XenuIsWatching** [comment]
> Under no circumstances will enspoints and their properties be described in devicetree. This is property served by software configuration, may be present but need not be used. Even with new device support where relevant Kconfig options no longer play a role, no chance for this.

I really do not understand you're reasoning here at all. That doesn't really work out if each instance of HID in a composite device needs a different configuration (such as one does not need an OUT EP for HID or a bInternval needs to be set differently). Right now, it's done with KConfigs, but with KConfigs... either ALL instances get the same configuration or they don't, but with devicetree each instances can get separate configurations.

**Comment by desowin** [comment]
The devicetree syntax is nicely suited for describing endpoints even if devicetree purpose is to describe hardware. I am not sure about the "zephyr,usb-hid" compatible as it basically calls for each class to have their own compatible. I am not sure either whether describing, configuring and assigning all endpoints to some class (i.e. any endpoint can be assigned to some class, either the same or not) using devicetree would be appropriate.

Regardless if the configuration is done via devicetree or something else, I think the user should be able to force specific endpoint numbers used by a given class (and not rely on automatic assignment by the stack) as such feature is really needed when creating new device version that reuses existing host software.

One thing, that needs to be somehow handled in the new stack is handling of dual speed devices (i.e. when High-Speed capable device is connected to Full-Speed only host). The old stack is pretty bad on this and not easy to adapt. However, for new stack, it should be possible for the developer to somehow provide configuration for both speeds - especially because the configuration can differ in functionality (the other speed descriptor is there for a reason after all).

**Comment by XenuIsWatching** [comment]
> The devicetree syntax is nicely suited for describing endpoints even if devicetree purpose is to describe hardware. I am not sure about the "zephyr,usb-hid" compatible as it basically calls for each class to have their own compatible. I am not sure either whether describing, configuring and assigning all endpoints to some class (i.e. any endpoint can be assigned to some class, either the same or not) using devicetree would be appropriate.

Yeah, but then it's up to the class subsys to then describe the EP descriptors, and for when/if USB 3 ever comes to Zephyr, it's gonna get even more complicated with all the additional SS EP descriptors that would describe the Burst value which is then written to the usb hardware registers. My concern with KConfigs, is that it's really an ALL or NONE configuration and with devicetree you can instance which ones get the configuration, for example with this, one of the HID interfaces could get an OUT EP along with a different bInterval and mps value.

As for each USB class having their own compatible... Isn't that already how the Audio and CDC ACM classes already work

> Regardless if the configuration is done via devicetree or something else, I think the user should be able to force specific endpoint numbers used by a given class (and not rely on automatic assignment by the stack) as such feature is really needed when creating new device version that reuses existing host software.

I'm not so sure why a user would need to force an _"endpoint"_ number.... however, a user would likely need to force an _"interface"_ number especially on a composite device which is something that is currently not possible when mixed with other USB classes. For example, when a software engineer is connected to a composite usb device with multiple HIDs (and other classes), the interface number is typically hard coded. I would think that if a endpoint number is fixed in software that would not be a good way of having your software written for USB...

**Comment by jfischer-no** [comment]
> Regardless if the configuration is done via devicetree or something else, I think the user should be able to force specific endpoint numbers used by a given class (and not rely on automatic assignment by the stack) as such feature is really needed when creating new device version that reuses existing host software.

This is only useful if the development of the corresponding host application has failed completely and hardcoded addresses are used instead of reading interface descriptors. Nevertheless, it is planned to add such functionality.

**Comment by jfischer-no** [comment]
> Yeah, but then it's up to the class subsys to then describe the EP descriptors, and for when/if USB 3 ever comes to Zephyr, it's gonna get even more complicated with all the additional SS EP descriptors that would describe the Burst value which is then written to the usb hardware registers. My concern with KConfigs, is that it's really an ALL or NONE configuration and with devicetree you can instance which ones get the configuration, for example with this, one of the HID interfaces could get an OUT EP along with a different bInterval and mps value. This would also get rid of the need for `device_get_binding` which is now giving deprecated warnings.

Still, HID instance is not a driver, but rather a service (there is also no driver API for audio or HID). DT is for drivers and describes hardware (may be virtual), and that is why I am not convinced, and that is apart from the fact that the bindings for HID instances are in no way meant to describe endpoint properties directly. I am also not saying everything has to come from Kconfig. New device support takes a slightly different approach, we could leave it to user to define HID instance context and pass it by usb_hid_init() (I will draft this approach for the HID support in new device support). Since both MPS and bInterval are resources (not from HID but provided for it) they could also have appropriate API to change it at runtime. (Same text as on discord).
Even if it would be acceptable to use DT for services (which IMO is not right), identifiers should be chosen differently and have no direct reference to USB resources, so describe HID profiles (think towards BT HID).

btw, where do you see device_get_binding() being deprecated?

> 
> As for each USB class having their own compatible... Isn't that already how the Audio and CDC ACM classes already work

No, "zephyr,cdc-acm-uart" is for the UART driver side and describes virtual UART, not USB device resource side, it is different to your approach. IIRC audio mixes both sides, but only *-sync-type is not right.

> I'm not so sure why a user would need to force an _"endpoint"_ number.... however, a user would likely need to force an _"interface"_ number especially on a composite device which is something that is currently not possible when mixed with other USB classes. For example, when a software engineer is connected to a composite usb device with multiple HIDs (and other classes), the interface number is typically hard coded. I would think that if a endpoint number is fixed in software that would not be a good way of having your software written for USB...

With our (desired) dynamic configuration possibilities (in new stack also at runtime), it is impossible to have hardcoded interface number in composite configuration. It is also not necessary, instead interface string descriptor index should be used (current stack can do it with a workaround, new one should support it, not sure if it is already the state, in any case ping me about it if necessary).

**Pull request closed without merging**
