### PR TITLE
pwm: fix pwm_pin_set_usec on 32 bit MCU

### LINKED ISSUE #6015: PWM on 32bit arch can get 0 pulse_cycle because of 64bit calculation
In the file zephyr/include/pwm.h, 64 bit is used to calculate the period an the pulse. On a 32 bit machine we might get `0` for the `pulse_cycles` or `period_cycles`. A suggestion could be to change `pulse_cycles = (pulse * cycles_per_sec) / USEC_PER_SEC;` to `pulse_cycles = (cycles_per_sec / USEC_PER_SEC) * pulse;`
Here is a snippet of the modified function that works for me:

```
static inline int pwm_pin_set_usec(struct device *dev, u32_t pwm,
				   u32_t period, u32_t pulse)
{
	u32_t period_cycles, pulse_cycles, cycles_per_sec;

	if (pwm_get_cycles_per_sec(dev, pwm, (u32_t*)&cycles_per_sec) != 0) {
		return -EIO;
	}
	
	period_cycles = (cycles_per_sec / USEC_PER_SEC) * period;
	pulse_cycles = (cycles_per_sec / USEC_PER_SEC) * pulse;

	return pwm_pin_set_cycles(dev, pwm, period_cycles, pulse_cycles);
}
```

### PR DESCRIPTION
**Pull request by tmauron**
Fixes #6015
Signed-off-by: Thibaut Mauron <tmauron@logitech.com>

### CODE REVIEW

**Comment by nashif** [comment]
@MaureenHelm can you take a look at this please?

**Comment by galak** [comment]
@tmauron curious under what conditions you see this issue.

**Comment by carlescufi** [comment]
@tmauron apologies for the huge delay in reviewing this PR. We are now catching up and we've added a few reviewers, hopefully this will be reviewed soon.

**Comment by carlescufi** [comment]
@cvinayak @pizi-nordic can you please review this PR?

**Review by pizi-nordic — CHANGES_REQUESTED** [review]

**Comment by gamnes** [comment]
If https://github.com/zephyrproject-rtos/zephyr/issues/6958 - "Update PWM API for dynamic prescaler computation", 'drivers should be able to handle directly pwm_pin_set_usec', gets developed and merged, any problems that may exist with calculating period_cycles will be handled in the drivers pin_set function instead. 
I suggest that issue #6958 is completed first, then we can revisit this issue if necessary when the calculation if done inside the pin_set function.

**Pull request closed without merging**
