### PR TITLE
modules: canopennode: Updated CANopenNode driver to v2.0

### PR DESCRIPTION
**Pull request by alibenpeng**
This commit updates the existing zephyr driver for canopennode from v1.3 to v2.0 and adds support for all new upstream driver features. The motivation for this was that I needed the ASCII gateway feature, which is not available in v1.3.
I ran checkpatch on my own code, but the stuff in the objdict-directory of the example is autogenerated and won't pass. But I hardly even touched that, so it should be fine.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@henrikbrixandersen ping

**Comment by alibenpeng** [comment]
This needs the canopennode repo to track v2.0, but I don't know the procedure for doing that.

**Comment by MaureenHelm** [comment]
> This needs the canopennode repo to track v2.0, but I don't know the procedure for doing that.

https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Please follow the procedure in https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules for proposing a change to the CANopenNode module.

Your commits contain a lot of seemingly unrelated code reformatting, making the actual functional changes very difficult to review. Please remove this code reformatting.

I am not still convinced that forcing users to update to CANopenNode v2.0 will be beneficial due to the amount of API changes (which is why I have kept it at v1.3).

**Pull request closed without merging**
