### PR TITLE
Bluetooth: BAP: Shell: Fixed cmd_stream_qos and cmd_sync_broadcast

### PR DESCRIPTION
**Pull request by LuckeTech**
Added missing initializer for int err.

### CODE REVIEW

**Comment by Thalley** [comment]
@LuckeTech for next time, please update your PRs instead of creating new ones :)

**Review by Thalley — APPROVED** [review]

**Comment by LuckeTech** [comment]
What's the problem with the compliance check? I added 

Signed-off-by: Benjamin Lucke <benjamin@lucke.tech>

**Comment by MariuszSkamra** [comment]
The sign-off email address does not match the patch author email.
I think you have to set your email in git settings
```
git config --global user.email "YOUR_EMAIL"
```

image

**Comment by Thalley** [comment]
> The sign-off email address does not match the patch author email. I think you have to set your email in git settings
> 
> ```
> git config --global user.email "YOUR_EMAIL"
> ```
> 
> image
> 
> See this page: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

And once that has been set, you can signoff your existing commit with `git commit --amend --signoff`

**Review by MariuszSkamra — APPROVED** [review]

**Comment by LuckeTech** [comment]
This reconfig of the email is not working.

**Comment by Thalley** [comment]
> This reconfig of the email is not working.
> 
> Edit: My github is set a private, so all config is rewritten with a hidden emailaddress and author will be set to LuckeTech.

So is mine; that's is not the issue. Something must've gone wrong in your configuration. 

If you want to try with a new commit (you don't have to create new PRs every time, you can just push on the same branch), try with `git commit -s` which automatically adds the (correct) signoff line.

**Comment by Thalley** [comment]
> I won't create a new PR, don't worry. I'm not able to configure this stuff as you need it.

I think that's a shame, because you clearly found an issue and made a solution for it :) Don't let git get you down (we've all been there).

**Comment by Thalley** [comment]
> There is an other issue inside `cmd_send`, this command can run illegal actions. It's needed to check the len to min_octets_per_frame and also to max_octets_per_frame. Quick and dirty fix `if (len != default_stream->qos->sdu)`

That's when sending LC3 data, right? 

If you are up for it, you can try with another PR to fix that :) Else I would appreciate it if you could create a Github bug report for this

**Pull request closed without merging**
