### PR TITLE
arc: Convert to CONFIG_MP_MAX_NUM_CPUS

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Review by ruuddw — APPROVED** [review]

**Comment by galak** [comment]
@evgeniy-paltsev  any reason for DNM.  At this point for ARC the settings should be the same.

**Comment by evgeniy-paltsev** [comment]
@galak as I understand the changes for boards/arc/hsdk/board.cmake are not correct - we should pass number of cpus zephyr is running on and not the `CONFIG_MP_MAX_NUM_CPUS`.

But yep, I need to find some time to investigate it more deeply.

**Comment by ruuddw** [comment]
My understanding of these changes are to have more uniform terminology. CONFIG_MP_MAX_NUM_CPUS doesn't indicate the number of CPUs the hardware has, but the maximum number of CPUs that Zephyr may use.

**Comment by galak** [comment]
The intent is CONFIG_MP_MAX_NUM_CPUS is the same as CONFIG_MP_NUM_CPUS unless you need it otherwise.  The otherwise case is if you want to detect the number of CPUs at runtime.  So for ARC this should be a noop right now.

**Comment by evgeniy-paltsev** [comment]
> The otherwise case is if you want to detect the number of CPUs at runtime.

Ok, if its about about runtime detection than it's probably fine.

**Review by evgeniy-paltsev — APPROVED** [review]

**Pull request merged**
