### PR TITLE
Bluetooth: Mesh: Add initial configuration client support

### PR DESCRIPTION
**Pull request by jhedberg**
Add initial configuration client support, and extend the shell and mesh_demo app to use it. Due to the configuration client being a large API, now is also a good point to refactor the monolithic single mesh.h public header file into a new include/bluetooth/mesh/ subdirectory.

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by jhedberg** [comment]
recheck

**Comment by jhedberg** [comment]
@rymanluk @michal-narajowski FYI, some API changes here that need to be synced to MyNewt

**Comment by dbkinder** [comment]
This PR had an unnoticed error (fixed by #4979) 

    /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include/bluetooth/mesh/health_srv.h:15: warning: missing title after \defgroup bt_mesh_health_srv

**Pull request merged**
