### PR TITLE
doc: irq: fix function link

### PR DESCRIPTION
**Pull request by simhein**
fix not correct shown function link for irq_connect_dynamic.

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by kartben — CHANGES_REQUESTED** [review]
Thanks Simon! just did a quick " c:func:" search across the entire repo and turns out there is another wrong link in the very same file, at line 557. Would you mind also fixing it? (note that since it's an internal symbol, it won't generate a hyperlink though)

https://github.com/zephyrproject-rtos/zephyr/blob/b84bab36b94164b87257894b3de873f60bcee5e3/doc/kernel/services/interrupts.rst#L557

**Comment by simhein** [comment]
> Thanks Simon! just did a quick " c:func:" search across the entire repo and turns out there is another wrong link in the very same file, at line 557. Would you mind also fixing it? (note that since it's an internal symbol, it won't generate a hyperlink though)
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/b84bab36b94164b87257894b3de873f60bcee5e3/doc/kernel/services/interrupts.rst#L557

Sure, will fix it

**Comment by kartben** [comment]
> > Thanks Simon! just did a quick " c:func:" search across the entire repo and turns out there is another wrong link in the very same file, at line 557. Would you mind also fixing it? (note that since it's an internal symbol, it won't generate a hyperlink though)
> 
> feature creep :-D

well i'd rather address it now than open an issue or another PR (issue and PR creep :P) or just forget about it, especially since I'm sure @simhein doesn't mind :)

**Comment by kartben** [comment]
But I probably shouldn't have "requested changes", I give you that @nashif  :)

**Review by kartben — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
