### PR TITLE
dts: stm32: stm32u5: Add sdmmc1 and sdmmc2 configuration

### PR DESCRIPTION
**Pull request by avisconti**
Provide the soc configuration for sdmmc1 and sdmmc2 controllers. This includes registers address, clocks, resets and interrupt line details.

### CODE REVIEW

**Review by gautierg-st — DISMISSED** [review]

**Comment by avisconti** [comment]
@gautierg-st I saw that you approved this PR. But I have a doubt concerning the clock. I'm currently using HSI48, because otherwise the stm32-sdmmc driver will refuse it. What is your opinion? Question also open to all reviewer. Is this correct?

**Comment by gautierg-st** [comment]
> @gautierg-st I saw that you approved this PR. But I have a doubt concerning the clock. I'm currently using HSI48, because otherwise the stm32-sdmmc driver will refuse it. What is your opinion? Question also open to all reviewer. Is this correct?

Technically, the SDMMC domain clock can be chosen between ICLK and PLL1P. But ICLK is itself chosen among HSI48, PLL2Q, PLL1Q and MSIK. HSI48 is the value by default for ICLK.

Currently, configuring ICLK is unsupported. If support for ICLK comes in the future, the clock source for SDMMC will have to be replaced with STM32_SRC_ICLK. But for now, setting HSI48 as clock source is correct.
Maybe you can just add a comment for this in the dtsi, to explain the situation and maybe prevent a future oversight.

**Comment by avisconti** [comment]
> > @gautierg-st I saw that you approved this PR. But I have a doubt concerning the clock. I'm currently using HSI48, because otherwise the stm32-sdmmc driver will refuse it. What is your opinion? Question also open to all reviewer. Is this correct?
> 
> Technically, the SDMMC domain clock can be chosen between ICLK and PLL1P. But ICLK is itself chosen among HSI48, PLL2Q, PLL1Q and MSIK. HSI48 is the value by default for ICLK.
> 
> Currently, configuring ICLK is unsupported. If support for ICLK comes in the future, the clock source for SDMMC will have to be replaced with STM32_SRC_ICLK. But for now, setting HSI48 as clock source is correct. Maybe you can just add a comment for this in the dtsi, to explain the situation and maybe prevent a future oversight.

ok, I'll add exactly your comment, thanks.

**Comment by avisconti** [comment]
@gautierg-st if you can review again. Thx

**Review by gautierg-st — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
did you run any testcase based on  sdmmc for stm32U5  ?

**Pull request merged**
