### PR TITLE
samples: Bluetooth: direction_finding_connectionless_rx: Update config to allow build for nRF5340 APP core

### PR DESCRIPTION
**Pull request by ppryga-nordic**
Move BLE controller configuration to board specific *.conf overlay.
That is required to make possible to build sample code for nRF5340,
where BLE controller is part of separate image aimed for network
core.

The PR may be merged when this PR: #36047 is merged into main.

### CODE REVIEW

**Review by Thalley — APPROVED** [review]

**Comment by ppryga** [comment]
Removed files that didn't belong to the PR.

**Review by Thalley — APPROVED** [review]

**Comment by ppryga** [comment]
@jhedberg @joerchan could you take a look on the PR?

**Comment by cvinayak** [comment]
Can we avoid turning on `CONFIG_BT_CTLR_ADV_EXT=y`, as this is still experimental (until we complete conformance tests) ?

**Comment by ppryga** [comment]
> Can we avoid turning on `CONFIG_BT_CTLR_ADV_EXT=y`, as this is still experimental (until we complete conformance tests) ?

@cvinayak without advertising extensions the features is not working. Maybe it would be better to put an information about use of experimental features?

**Comment by cvinayak** [comment]
> 
> 
> > Can we avoid turning on `CONFIG_BT_CTLR_ADV_EXT=y`, as this is still experimental (until we complete conformance tests) ?
> 
> @cvinayak without advertising extensions the features is not working. Maybe it would be better to put an information about use of experimental features?

Ok, I will send a PR adding CMake warning message when advertising extensions in Controller is enabled.

**Comment by joerchan** [comment]
> Ok, I will send a PR adding CMake warning message when advertising extensions in Controller is enabled.

@cvinayak We don't do that for any of the other experimental features, so I don't think we should add it now.
I think having it enabled in this sample is fine.

**Review by joerchan — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
