### PR TITLE
drivers: eeprom: Enable read and fill shell commands to operate on whole eeprom

### PR DESCRIPTION
**Pull request by chrta**
The logic is in-part copied from the equivalent flash shell commands.

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Thanks! This is a much better implementation. 

One wish, though. Please do not use `todo` as a variable name. It triggers my brains internal alarm for "unfinished code" when I read it 😉

**Comment by chrta** [comment]
> One wish, though. Please do not use todo as a variable name. It triggers my brains internal alarm for "unfinished code" when I read it

No problem. I just copied the names from the flash shell. Do you have a suggestion for a variable name?

**Comment by henrikbrixandersen** [comment]
> No problem. I just copied the names from the flash shell. Do you have a suggestion for a variable name?

"pending"?

**Review by henrikbrixandersen — APPROVED** [review]
Looks good, thanks. Sorry my review took so long.

**Review by jakub-uC — APPROVED** [review]

**Pull request merged**
