### PR TITLE
WIP: boards: arm: add initial support for OLIMEX STM32-H405 board

### PR DESCRIPTION
**Pull request by frantony**
boards: arm: add initial support for OLIMEX STM32-H405 board

The board features a STM32F405RGT6 MCU.

The code is based on boards/arm/olimex_stm32_p405 and boards/arm/olimex_stm32_h103.

TODO:

- [ ] <s>use `boards/arm/olimex_stm32_h103/doc/img/olimex_stm32_h103_*.jpg`</s>;
-   [ ] doc: add comment on REV C pcb use;
- [ ] use `interface/ftdi/olimex-arm-usb-tiny-h.cfg` in JTAG mode (at the moment only stlink in SWD mode is mentioned, e.g. see `boards/arm/olimex_stm32_h103/support/openocd_olimex_jtag.cfg`);
- [ ] fix `boards/arm/olimex_stm32_p405` parts (e.g. ``BOOTING ZEPHYR OS v1.8.99 - BUILD: Aug  4 2017 14:54:40``);
- [ ] check pin map table;
- [ ] test more samples.

Tested samples:

- [x] subsys/shell/shell_module (via uart and usb_otg)
- [x] hello_world
- [ ] basic/blinky
- [ ] basic/button
- [ ] gui/lvgl + SHIELD=ssd1306_128x64
- [ ] philosophers
- [ ] sensor/hmc5883l
- [ ] synchronization
- [ ] tests/drivers/entropy

See also:

 * https://github.com/zephyrproject-rtos/zephyr/pull/27084

### CODE REVIEW

**Comment by erwango** [comment]
@frantony Do you plan to continue this PR?
If yes, can you rebase on top of master and switch to device tree based pin configuration ?

**Comment by frantony** [comment]
@erwango 

> Do you plan to continue this PR?

Yes, I'm planning to continue this PR.

> If yes, can you rebase on top of master and switch to device tree based pin configuration ?

I see many patches on switching UART to DT configurateion, e.g. e5d3ee18cb9e9b33c970a91600fc6d9eaf17f34e, so I can easely do rebase.

The only problem is that I have no much time to test my changes on real hardware.

I'll try to push updated version this week.

**Comment by erwango** [comment]
@frantony no rush, you might want to wait that usb conversion of USB pinmux is done as well.

**Comment by frantony** [comment]
@erwango 

I see that you have done usb pinmux conversion (e.g. https://github.com/zephyrproject-rtos/zephyr/commit/199cf5668bfb975f31931b62987719d1b95638fe).

I'll update the PR this week.

**Comment by frantony** [comment]
OLIMEX STM32-H405 support is added in https://github.com/zephyrproject-rtos/zephyr/pull/41675.

**Pull request closed without merging**
