### PR TITLE
net: lwm2m: send REGISTRATION_FAILURE event on error

### PR DESCRIPTION
**Pull request by SeppoTakalo**
Two more issues were noticed on discussion  at https://github.com/zephyrproject-rtos/zephyr/issues/76422#issuecomment-2262470068

## net: lwm2m: send REGISTRATION_TIMEOUT event on error

When socket errors call sm_handle_timeout_state() we might be
in a state where application assumes we are in registered state
but we are dropping it.
Therefore we must ensure that all registration states emit
REGISTRATION_TIMEOUT event for application
to indicate that we have lost the connection to server.

## net: lwm2m: Reset retry counter on update

On a successful update we should reset the retry counter, similarly
like we do on successful registration.

@SebastianSchueller  please review.

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Review by SebastianSchueller — APPROVED** [review]
Nice, I think this should fix the issues we observed!
I think it might be good to add the new event / state transitions to the [docs](https://docs.zephyrproject.org/latest/connectivity/networking/api/lwm2m.html#lwm2m-engine-and-application-events)?

**Comment by SeppoTakalo** [comment]
Yes, I think I need to update the documentation...

But I also started wondering if we should leave the REGISTRATION_FAILURE event to indicate only that server have rejected our registration. Then REGISTRATION_TIMEOUT would be indication of any CoAP failure.

That would be clear:
* REGISTRATION_FAILURE: most probably we don't recover. Might be configuration issue. Dropping to bootstrap might be the only recovery.
* REGISTRATION_TIMEOUT: would be socket error (network lost) or CoAP timeout (network error). DTLS handshake might recover.

Should I refactor the PR to this?

**Comment by SebastianSchueller** [comment]
I think that makes sense, yeah.

**Comment by SeppoTakalo** [comment]
Now fixed the documentation and changed the logic so that REGISTRATION_FAILURE is only result of a server rejecting the registration.
REGISTRATION_TIMEOUT is a result of any transmission timeouts or socket errors.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
