### PR TITLE
can't set alarm after alarm cancel for rpi_pico counter

### PR DESCRIPTION
**Pull request by kilejin**
for rpi_pico counter,  cancelling alarm  prevents from setting alarm again.
alarm setting function checks channel callback and if callback is registered it returns -EBUSY.
but alarm cancel function doesn't clear callback function. this prevents from alarm setting after alarm cancel.

### CODE REVIEW

**Review by soburi — DISMISSED** [review]

**Comment by yonsch** [comment]
@kilejin Thank you for this fix.
The CI is failing because the commit message is not formatted correctly. You can find instructions here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines
You'll need to override the old commit, either with `amend`, `reset` or `rebase` and push with `-f`. Welcome!

**Review by soburi — APPROVED** [review]

**Review by soburi — CHANGES_REQUESTED** [review]
It's seems contain unrelated commits.

**Comment by kilejin** [comment]
@soburi 
I'm sorry. i meant to rebase since i saw a compliance check fail about that.

**Review by soburi — APPROVED** [review]

**Comment by kilejin** [comment]
@soburi sorry for bothering you. can you explain what's problem. i see that the commit message follows the rule.
but compliance check fails again.

**Comment by soburi** [comment]
@kilejin 

> d00518e56514f68a578b4836b9db410100fffe87: author email (kilejin <kilejin@gmail.com>) does not follow the syntax: First Last <email>.

It means the commit message's mail address requires `first` and `last` name.
For example, my commit has author line as

```
Author: TOKITA Hiroshi <tokita.hiroshi@gmail.com>
```

Edit it with git command such like

```
git config user.name "[your first name] [your last name]"
```

**Comment by kilejin** [comment]
@soburi  oh! i see. there is author line. thank you.

**Review by yonsch — APPROVED** [review]
Thanks!

**Comment by yonsch** [comment]
@soburi Can you take a look?

**Comment by soburi** [comment]
@yonsch 

> @soburi Can you take a look?

OK. I reviewed the PR, and already approved it. 😋

**Pull request merged**
