### PR TITLE
ap4 kxr add rtc

### PR DESCRIPTION
**Pull request by RichardSWheatley**
add rtc capability for KXR

### CODE REVIEW

**Review by decsny — APPROVED** [review]

**Comment by bjarki-andreasen** [comment]
Notify ci channel on discord, wait for fix, then rebase :)

**Review by bjarki-andreasen — APPROVED** [review]

**Review by aaronyegx — APPROVED** [review]

**Comment by bjarki-andreasen** [comment]
it may need another rebase...

**Comment by swift-tk** [comment]
> it may need another rebase...

Author is on vaction.

**Comment by bjarki-andreasen** [comment]
@RichardSWheatley could you look into why `west build -p -b apollo4p_blue_kxr_evb/apollo4p_blue zephyr/tests/subsys/mgmt/mcumgr/os_mgmt_info -T mgmt.mcumgr.os.info.bt` is failing, or maybe find someone who can look into it, its something regarding sys random missing

**Comment by aaronyegx** [comment]
It seems all Bluetooth samples and testcases are affected. See issue https://github.com/zephyrproject-rtos/zephyr/issues/82344. It should be sys random issue.

**Comment by aaronyegx** [comment]
Just rebase to rerun the CI check, it seems the previous CI failure is addressed in mainline.

**Review by AlessandroLuo — APPROVED** [review]

**Pull request merged**
