### PR TITLE
bluetooth: kconfig: Add channel sounding kconfigs

### PR DESCRIPTION
**Pull request by sean-madigan**
Add new controller and host kconfigs for Bluetooth 6.0 Channel Sounding and Channel Sounding Test.

### CODE REVIEW

**Review by hermabe — APPROVED** [review]

**Comment by jhedberg** [comment]
Don't we have the convention or requiring at least some kind of users (implementation) for any new Kconfig options? What's your plan with that part? A follow-up PR? This is a bit like adding a new API without any implementation, which isn't something that's generally allowed in Zephyr.

**Comment by sean-madigan** [comment]
> Don't we have the convention or requiring at least some kind of users (implementation) for any new Kconfig options? What's your plan with that part? A follow-up PR? This is a bit like adding a new API without any implementation, which isn't something that's generally allowed in Zephyr.

Yes, the idea is to add the Channel Sounding host implementation in follow up PRs

**Comment by jhedberg** [comment]
> Yes, the idea is to add the Channel Sounding host implementation in follow up PRs

The single commit in this PR is small and simple enough, that I think it'd make sense to just have that as the first commit of the first "implementation" PR.

**Comment by sean-madigan** [comment]
> > Yes, the idea is to add the Channel Sounding host implementation in follow up PRs
> 
> The single commit in this PR is small and simple enough, that I think it'd make sense to just have that as the first commit of the first "implementation" PR.

Sure, no worries

**Comment by sean-madigan** [comment]
To be added in first implementation PR

**Pull request closed without merging**
