### PR TITLE
drivers/clock_control/smartbond: Always calibrate RC32K

### PR DESCRIPTION
**Pull request by ydamigos**
RC32K clocks HW FSM. We should always calibrate it.

### CODE REVIEW

**Comment by ioannis-karachalios** [comment]
Since the RC32K calibration is mandatory then `CALIBRATION_INTERVAL` is not allowed to be zero. Currently, the calibration interval is based on the `calibration-interval` binding property (see `renesas,smartbond-lp-osc.yaml` - the `description` also needs update) which is not marked as mandatory and it can have zero value. To my view, and since all calibration tasks use the same interval, it would be better to introduce a Kconfig option, instead. For instance:

```
config SMARTBOND_LP_OSC_CALIBRATION_INTERVAL
  int "Low power oscillators calibration interval"
  default 1
  range 1 10
  help
    Time in seconds between calibration of low power clock RC32K and RCX.
```

**Comment by ydamigos** [comment]
@ioannis-karachalios Done. I also added a build assertion to prevent user from disabling RC32K.

**Comment by ioannis-karachalios** [comment]
> int "Low-power oscillators calibration interval"
>   default 1
>   range 1 10
>   help
>     Time in seconds between calibration of low power clock RC32K and RCX.

**Comment by ioannis-karachalios** [comment]
Changes look neat and clear :)

**Review by ioannis-karachalios — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by andrzej-kaczmarek — APPROVED** [review]

**Review by blauret — APPROVED** [review]

**Pull request merged**
