### PR TITLE
usb: device: cdc_acm: send more than 1 byte in poll out

### LINKED ISSUE #52872: Logging to USB CDC ACM limited to very low rate
**Describe the bug**
Logging, using the Zephyr logging system and the log_backend_uart, is limited to about 2200 bytes/sec when the uart is a USB CDC ACM UART.  This is quite slow.  USB should be capable for much higher speed.

Logging to the shell_uart_backend, with the shell also on a USB CDC ACM uart, isn't limited to this low speed.

It's specific to the interaction between the USB CDC ACM uart and the logging uart backend.

**To Reproduce**
Log more than 2200 bytes/sec continuously to the backend log_backend_uart with a USB CDC ACM uart.  Eventually the logging system's buffer will fill and messages will start getting dropped.

**Expected behavior**
The logging system should be able to achieve a much higher data rate before dropping messages.

**Impact**
Logging over USB CDC ACM is very limited.  This is especially bad for devices which do not have another logging interface.

**Logs and console output**
USB captures from log_backend_uart and shell_uart_backend.
[usb_captures.zip](https://github.com/zephyrproject-rtos/zephyr/files/10181593/usb_captures.zip)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: GNU
 - Commit SHA or Version used: b05b8ad63acf30e08a570ce553831a06db27a2e0
 - Nordic NRF52840

**Additional context**
The USB URBs will contain at exactly one byte of data with log_backend_uart.  With shell_uart_backend, the URBs contain more data.

The issue appears to be a compounding limitations in cdc_acm and log_backend_uart.
* log_backend_uart will only write one byte a time with uart_poll_out() unless the async UART API is enabled.
* cdc_acm does not support the async UART API, only the polling and interrupt-driven UART APIs.
* log_backend_uart does not support the interrupt-driven UART API.
* cdc_acm does not appear to allow merging multiple bytes written with uart_poll_out() into a single URB.

### PR DESCRIPTION
**Pull request by desowin**
Schedule CDC ACM tx work to happen 1 ms after first unprocessed data write. This gives enough leeway for the task writing to the queue to write more than 1 byte before USB workqueue preempts and schedules IN transfer. Sending more than 1 byte at a time increases data throughput because transaction overhead remains the same regardless of packet size.

Prior to this change, virtually every IN transaction carried only one character when CDC ACM was used as a console.

Related to #52981
Fixes #52872

### CODE REVIEW

**Comment by nordicjm** [comment]
Tested on nRF5340, deferred logging throughput now reaching ~107KBps, minimal logging ~45KBps, increase from the highest before this fix of ~9KBps in deferred logging mode.

@xyzzy42 this should fix the issues you have seen

**Review by nordicjm — APPROVED** [review]

**Comment by nordicjm** [comment]
Only comment would be is if a "1ms" delay is acceptable, for the majority of people, it's not an issue, but 1ms is not guaranteed to be 1ms, and for some applications that need speed of data over throughput, is this going to cause them problems? FTDI's driver (at least in windows) allows control of this per connected device, to favour throughput OR latency.

**Comment by xyzzy42** [comment]
I wonder if "panic" mode is affected?  Normally, the log backend switches from async mode to polled mode with a normal uart when panic is set.  I imagine the reason is so logs might still go out if scheduling is broken or the CPU is halted or reset as soon as the panic log is sent, synchronously with poll mode, out the uart.  Which probably doesn't really work on USB anyway, even before this change to add a delay.

I fixed this problem for myself by adding interrupt-driven UART mode support into the logging uart backend.  I can compare to this fix, but I think performance will be very similar between the two.

**Comment by desowin** [comment]
> Only comment would be is if a "1ms" delay is acceptable, for the majority of people, it's not an issue, but 1ms is not guaranteed to be 1ms, and for some applications that need speed of data over throughput, is this going to cause them problems?

I guess by "speed of data" you mean latency, because by reducing latency you inevitably lower the amount of data you can send in given time interval (due to overhead and the fact that all USB communication is always initiated by host). I think expecting really low latency on USB is unreasonable, it is not low-latency medium.

I don't think the delay is going to cause problems other than eventually uncovering that the CDC ACM poll out implementation is not blocking as it should be according to `uart_poll_out` documentation.
https://github.com/zephyrproject-rtos/zephyr/blob/d46b9bd124119b9a8809c6e25acbfb175f5b221b/include/zephyr/drivers/uart.h#L561-L567

> FTDI's driver (at least in windows) allows control of this per connected device, to favour throughput OR latency.

This is achieved by setting the latency in FTDI device using USB control transfer. When the latency timer expires in FTDI chip, it arms the IN bulk endpoint with the modem status lines status (2 bytes) and (if any) actual data. If latency timer does not expire, then the IN bulk endpoint is only armed once the packet would be Max Packet Size (i.e. Max Packet Size - 2 bytes payload data is collected in FIFO).

Arming IN endpoint is the only a part of latency issue on which the device has control. The other part of the latency is related to when host issues IN transaction, which is completely independent from the device (and forcing URB every 1 payload byte is really wasteful).

> I wonder if "panic" mode is affected? Normally, the log backend switches from async mode to polled mode with a normal uart when panic is set. I imagine the reason is so logs might still go out if scheduling is broken or the CPU is halted or reset as soon as the panic log is sent, synchronously with poll mode, out the uart. Which probably doesn't really work on USB anyway, even before this change to add a delay.

No, this would be unaffected (i.e. it didn't work before and won't work after) because the actual transmission was handled by workqueue. This PR only prevents the workqueue from immediately preempting virtually every character write.

**Review by jfischer-no — APPROVED** [review]

**Comment by trentp-igor** [comment]
On a nRF52480, with a USB 2.0 hub (for power) between the host and bus, I get, sustained, with deferred logging.

* 50 KB/sec with this PR.  Yes, multiple bytes per URB are sent.  It's ~2 KB/sec without.
* 105 kB/sec with my interrupt-driven log backend uart.

So directly supporting the FIFO concept is somewhat better.

There is a much bigger problem.

I also have a shell running on a different USB CDC ACM endpoint.  With this PR, that ACM endpoint stops working once the other endpoint starts log TX at high speed.  The interrupt-driven support works fine with both ACM endpoints and logging at double the rate.

**Comment by trentp-igor** [comment]
> I guess by "speed of data" you mean latency, because by reducing latency you inevitably lower the amount of data you can send in given time interval (due to overhead and the fact that all USB communication is always initiated by host). I think expecting really low latency on USB is unreasonable, it is not low-latency medium.

IMHO, a better way to measure would be to look at command-response transaction rate.  Send a byte from host to device.  When the device gets the byte it sends another byte back to host.  Host gets that byte and then sends another, etc.  It's like sending commands over a UART to the device and waiting for responses and seeing what kind of throughput you can achieve.  If the commands are fast, the latency hit for each command ends up creating the throughput limit.

I think that's where the extra 1 ms would show up.

That said, we do have a client with a device that uses Nordic ESB to send data, in one direction only, to another device to act as an ESB to USB gateway and they are very concerned about latency.  USB is far from an ideal low latency interface here, but there are not a lot of other options in this space when you take things like custom PCI-Express expansion cards off the table.

**Comment by desowin** [comment]
> I also have a shell running on a different USB CDC ACM endpoint. With this PR, that ACM endpoint stops working once the other endpoint starts log TX at high speed. The interrupt-driven support works fine with both ACM endpoints and logging at double the rate.

What do you mean by stops working? Is it entering an endless log loop (see #53032)? Or does it drop data (due to the non-blocking nature of the way ringbuf is used in CDC ACM, which is wrong imho, but seems to be there for some reason)?

**Comment by desowin** [comment]
> IMHO, a better way to measure would be to look at command-response transaction rate. Send a byte from host to device. When the device gets the byte it sends another byte back to host. Host gets that byte and then sends another, etc. It's like sending commands over a UART to the device and waiting for responses and seeing what kind of throughput you can achieve. If the commands are fast, the latency hit for each command ends up creating the throughput limit.

This sounds like an artificial benchmark to me. Make the payloads more realistic, e.g. 10 bytes long command and response, and you'll see drastically different results.

> That said, we do have a client with a device that uses Nordic ESB to send data, in one direction only, to another device to act as an ESB to USB gateway and they are very concerned about latency. USB is far from an ideal low latency interface here, but there are not a lot of other options in this space when you take things like custom PCI-Express expansion cards off the table.

Unless the client is always sending one byte payloads, I can't foresee a real degradation due to this change. In fact, this is likely to help due to significantly reduced CPU usage when payload is larger than 1 byte. Measure how much time is spent in USB workqueue with and without this change to get the feeling of how much overhead there is.

**Comment by trentp-igor** [comment]
> > I also have a shell running on a different USB CDC ACM endpoint. With this PR, that ACM endpoint stops working once the other endpoint starts log TX at high speed. The interrupt-driven support works fine with both ACM endpoints and logging at double the rate.
> 
> What do you mean by stops working? Is it entering an endless log loop (see #53032)? Or does it drop data (due to the non-blocking nature of the way ringbuf is used in CDC ACM, which is wrong imho, but seems to be there for some reason)?

Since the test breaks my logging, it's hard to tell what broke exactly!  The console no longer responds.  No echo back and it doesn't act on commands, even without uart output, either.  I can see from a USB trace on the host side that the bulk out URB sending data data to the console completes.  The bulk in URB expected immediately afterward from the echo back never happens.

I have USB on it's own queue, not the system queue.  Both endpoints would share the single USB queue.  I suspect that's where the issue is.  Some sort of "never get to the front of the queue" problem on the other endpoint's work.  It's easy to see that the hardware and USB driver, via the interrupt-driven mode logging backend, can handle double the data rate with the same endpoints with a problem.

**Comment by desowin** [comment]
> Since the test breaks my logging, it's hard to tell what broke exactly! The console no longer responds. No echo back and it doesn't act on commands, even without uart output, either. I can see from a USB trace on the host side that the bulk out URB sending data data to the console completes. The bulk in URB expected immediately afterward from the echo back never happens.

Do you use `uart_irq_callback_user_data_set`? Can you share the sample?

**Comment by desowin** [comment]
@trentp-igor When using two CDC ACM instances, one for console and one for shell, I can get the shell to stop working by starving the thread. Otherwise, I can get both logger and console to stop working if I close CDC ACM logging port and reopen it. The root cause (not yet identified, I am on it) might be the same in your case, but it might be something different as well.

**Comment by trentp-igor** [comment]
> This sounds like an artificial benchmark to me. Make the payloads more realistic, e.g. 10 bytes long command and response, and you'll see drastically different results.

I imagine the payloads don't need to get very long before the efficiency improvement offered by multi-byte USB URBs exceeds the reduced channel utilization due to more latency.  Under 10 bytes, going by how many URBs per 1 ms seem to be possible.

But if someone cared about throughput, they really should be using interrupt-driven or async mode anyway.  The polling uart interface is fundamentally less than ideal for this purpose.

The app I'm using runs on custom hardware.  But I need to debug another problem on a dev board that can be probed so I'll see if I can make a minimal example. Which will be more useful anyway.  AFAIK, spew deferred logs from main() while also having a shell on another CDC ACM uart is all that is needed.  But maybe the ADC on a SPI interface is somehow needed in some bizarre twist?

**Comment by desowin** [comment]
> I imagine the payloads don't need to get very long before the efficiency improvement offered by multi-byte USB URBs exceeds the reduced channel utilization due to more latency. Under 10 bytes, going by how many URBs per 1 ms seem to be possible.

I wouldn't be surprised if you could observe efficiency improvement already when payload is 2 bytes...

For full-speed, the absolute maximum is 19 URBs per 1 ms regardless of the data size you send. Note that this absolute maximum is unachievable unless you have dedicated host controller for that particular device **and** the target never NAKs a single IN transaction (which is pretty much impossible if target USB device peripheral does not support dual buffering) **and** host is fast enough to process the URBs.

> The app I'm using runs on custom hardware. But I need to debug another problem on a dev board that can be probed so I'll see if I can make a minimal example. Which will be more useful anyway. AFAIK, spew deferred logs from main() while also having a shell on another CDC ACM uart is all that is needed. But maybe the ADC on a SPI interface is somehow needed in some bizarre twist?

`main()` default priority is higher than shell default priority, so that can starve the shell. However, other than starving the shell thread in a way such that the handler for signal raised in https://github.com/zephyrproject-rtos/zephyr/blob/8bc094610c5dd69f6ba0085fb3fe7d18167164c9/subsys/shell/shell.c#L1154-L1157 is never called, I cannot get the shell to die no matter how much I write on the other CDC ACM interface.

Can you also reproduce the shell issue when shell thread priority is higher than default (enable priority override with `SHELL_THREAD_PRIORITY_OVERRIDE` Kconfig option and set priority with `SHELL_THREAD_PRIORITY` Kconfig option)?

**Comment by desowin** [comment]
> On a nRF52480, with a USB 2.0 hub (for power) between the host and bus, I get, sustained, with deferred logging.
> 
>     * 50 KB/sec with this PR.  Yes, multiple bytes per URB are sent.  It's ~2 KB/sec without.
> 
>     * 105 kB/sec with my interrupt-driven log backend uart.
> 
> 
> So directly supporting the FIFO concept is somewhat better.

Yes, it is because you waste less less time by sending less than Max Packet Size packets (i.e. the send is only scheduled *after* `cdc_acm_fifo_fill()` finishes writing the data) and waste less cpu time in actually writing to the ringbuffer (it does start playing a role). Increase the latency from `K_MSEC(1)` to `K_MSEC(2)` to see the speed go higher (at the cost of latency when just a single byte is sent). Note that with 2 ms, I still don't get Max Packet Size data packets, so it is *still* CPU limited, not bus limited.

**Comment by desowin** [comment]
The `K_MSEC(1)` is not really that bad from latency perspective. Without this PR, I could get a 1 byte payload on nRF52840DK CDC ACM IN endpoint (note that this is with application not doing anything useful!) on average every 0.34 ms. There is significant number of NAKed IN transactions in between the 1 byte payload data packets. This clearly shows that the bandwidth is limited due to device CPU processing power and not due to the USB bus.

This PR effectively reduces the latency if the payload is more than 2 bytes and the host does not individually process the bytes, e.g. like real-time MIDI messages on serial MIDI do. It does so thanks to significantly reduced CPU processing.

**Comment by trentp-igor** [comment]
Raising the shell priority (to a lesser number) so that it is higher than the logging thread allows the shell to work again at high log rates.  The significant CPU usage report is: shell_uart (13) 0%, usbworkq (-1) 10%, main (0) 4%, and logging (14) 63%.

So it's CPU bound, primarily stuffing bytes into the USB queue one at a time.  Shell was the only thing affected because logging was already the 2nd lowest priority.

Using interrupt-driven mode for logging reduces usage to: shell_uart 0%, usbworkq 18%, main 5%, logging 18%, idle 38%.  The logging thread now blocks waiting for USB to get the URBs out.

**Comment by trentp-igor** [comment]
With unmodified zephyr, shell and logging are equal priority (lowest) and we have: shell_uart 0%, usbworkq 51%, main 4%, logging 10%.  Almost no idle time.

If I adjust logging thread to be a higher priority than shell it causes the shell lockup.

So it's CPU bound between usbworkq and logging, with no blocking on the hardware.  But it is interesting, that changing the way items are added to the usb work queue causes the shell to get CPU time with equal priority to logging thread vs needing a higher priority to get CPU time.

I would have expected two equal priority threads to both get some share when all higher priority threads have blocked.

My code for interrupt-driven mode has two flaws:

1. UART interrupt-driven API support is optional in a UART driver, but there is no workable way to detect its presence.  `uart_irq_callback_user_data_set()` returns void.  The ASYNC UART API is also optional, but `uart_callback_set()` returns `-ENOSYS` so this can be detected.  Seems like a flaw in the UART APIs to me.
2. The cdc acm in interrupt-driven mode will block forever after one interrupt if no host is connected.  I don't think it should do this.  There seems no good way to deal with it.  I have the backend just wait a while and then drop a message if there are no interrupts.

**Comment by jfischer-no** [comment]
> My code for interrupt-driven mode has two flaws:

Okay, its more OT, please open a PR or discussion for your concern, I am locking the conversation here.

**Comment by desowin** [comment]
> > It is surprising how without this PR the shell could work,
> 
> Actually not, it does not use poll API.

Taking things out of context leads to simple but incorrect answers. Shell doesn't but logging does use poll API. The context was that there were two CDC ACM instances, one used for logging (poll API) and one used for shell **and** that this PR in such situation would starve shell, but wouldn't starve it without this PR. My suspicion is that the change is related to the fact that `k_work_submit_to_queue` calls `z_reschedule_unlocked`, but `k_work_schedule_for_queue` doesn't even if called with `K_NO_WAIT`.

**Comment by jfischer-no** [comment]
> > > It is surprising how without this PR the shell could work,
> > 
> > 
> > Actually not, it does not use poll API.
> 
> Taking things out of context leads to simple but incorrect answers. Shell doesn't but logging does use poll API. 

Logging uses poll if ASYNC API is not available, or IIRC shell is not enabled, but probably not if there are two instances.

>The context was that there were two CDC ACM instances, one used for logging (poll API) and one used for shell **and** that this PR in such situation would starve shell, but wouldn't starve it without this PR.

Sorry, I may not be able to filter out the relevant parts of many OT, but the two statements confuse me `It is surprising how without this PR the shell could work,` and `but wouldn't starve it without this PR`, what have I missed?

**Comment by desowin** [comment]
> Sorry, I may not be able to filter out the relevant parts of many OT, but the two statements confuse me `It is surprising how without this PR the shell could work,` and `but wouldn't starve it without this PR`, what have I missed?

There is application with two CDC ACM instances (used simultaneously, i.e. appearing as separate ttyACM/COM ports):
  * one CDC ACM instance used by shell thread (using `cdc_acm_fifo_fill`)
  * another CDC ACM instance used by logging thread (using `cdc_acm_poll_out`)

And now there are two builds:
  * one with this PR merged - where the shell "stops working", which was resolved to "shell thread is starved"
  * one without this PR merged, otherwise the same - where the shell works just fine (and therefore shell thread is not starved)

The "Actually not, it does not use poll API." in no way explains the surprising starvation. The starvation is surprising because in both builds the shell was running at the same priority as logging thread, and with this PR the USB workqueue uses significantly less CPU time leaving more processing power available to other thread. The only suspicion right now is that it is somehow related to the fact that `k_work_schedule_for_queue` does not call `z_reschedule_unlocked` like `k_work_submit_to_queue` does.

**Pull request merged**
