### PR TITLE
Bluetooth: controller: ticker stop at absolute tick

### PR DESCRIPTION
**Pull request by cvinayak**
Update ticker_stop interface to take absolute tick, so as
to correctly calculate the end of previous ticks_slot.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by mtpr-ot** [comment]
Should some of these commits perhaps be squashed?

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Comment by cvinayak** [comment]
> 
> 
> Should some of these commits perhaps be squashed?

yes, will do. This PR is still a draft, nRF51 testing does not result in my expectations, first event is still missing. Once, I have something satisfactory I will send a normal PR.

Also, should I conditional compile the changes in this PR? split controller (and faster MCU) does not need to have previous slot to be shortened, to accommodate slow CPU overhead in preparing first event).

**Comment by mtpr-ot** [comment]
> Also, should I conditional compile the changes in this PR? split controller (and faster MCU) does not need to have previous slot to be shortened, to accommodate slow CPU overhead in preparing first event).

I'm a bit torn between the clean change and compile flags here. I made the TICKER_EXT interface to avoid the need to add new unused parameters all over the code. For this purpose I would prefer either an unconditional change (as in PR), or a new unconditional "ticker_stop_specific" or similar function.

**Comment by cvinayak** [comment]
> 
> 
> > Also, should I conditional compile the changes in this PR? split controller (and faster MCU) does not need to have previous slot to be shortened, to accommodate slow CPU overhead in preparing first event).
> 
> I'm a bit torn between the clean change and compile flags here. I made the TICKER_EXT interface to avoid the need to add new unused parameters all over the code. For this purpose I would prefer either an unconditional change (as in PR), or a new unconditional "ticker_stop_absolute" or similar function.

I will go with `ticker_stop_absolute`

**Comment by cvinayak** [comment]
Superceded by #23152

**Pull request closed without merging**
