### PR TITLE
doc: reorganise sections and consolidate documentation of subsystems

### PR DESCRIPTION
**Pull request by nashif**
This is a continuation of work started some time ago to modularize the documentation
and remove the confusing Reference and Guides sections which are becoming a dumping
ground for all new documentation without a clear definition of what is an API and
what is a guide which ends up in documentation of subsystems being split and very
difficult to find or use.

End goal is to get rid of both Reference and Guides sections or limit what goes 
in there and integrate most of the docs in those areas in top level sections
that are more intuitive and easy to find.

This is all open for discussion and we need to figure out the naming of the main
sections and where each subsystems ends, but something along those lines
is what being proposed here:

- Introduction
- Development and Contribution Process
- Getting Started Guide
- Contribution Guidelines
- Build and Configuration Guidelines
  - Build System (Cmake)
  - Kconfig (Software Configuration)
  - DTS (Hardware Configuration)
- Modules and West
- The Zephyr Kernel (or just Kernel)
- Architectures
- Hardware Support / Device Drivers / ????
  - Device Driver Model
  - some aspects of DTS, see build and config above?
  - Pinctrl?
  - Peripheral API reference
  - 
- Connectivity
  - Bluetooth
  - Networking

- OS Services
  - Memory Management
  - User Space
  - Power Management
  - Logging
  - Shell
  - Settings
  - ...
- Libraries and Utilities
  - Resource Management
  - Formatted output
  - ...

Partially addresses #33725

Preview: https://builds.zephyrproject.io/zephyr/pr/41154/docs/

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
Thanks for this! I think we all agree we need a good clean rework.

> This is all open for discussion and we need to figure out the naming of the main sections and where each subsystems ends, but something along those lines is what being proposed here:

I want to know more about why you are proposing this from a high level before diving too deep into the details.

How does it specifically address the concerns and open issues raised by the UX study, for example?

Some particular questions that are near and dear to me:

- How will it help us solve problems like generating hardware support information on a per-board basis from devicetree/device drivers, for a particular example? I think there is a gap between "architecture" and "board" here where the docs are concerned, and it's that we don't have a place to document support for individual SoCs (like SoC DTSI, peripheral info in there, associated drivers, etc.) or refer to that documentation from board docs, even though that is an important part of how the code itself is organized
- I see that you want to get rid of guides vs reference, but you don't justify why. I think guides, or tutorial material, is critically important and I want to understand the reasoning and goals behind your proposal here too.

**Review by carlescufi — DISMISSED** [review]
I looked at the changes and many make sense to me, but I am left with a feeling of unease when looking at some others. I think that before we start moving top-level items around we should first agree that the proposed layout is what we want to converge into. For example, I am unsure about not placing Bluetooth and Networking inside a potential subsystems category, because that is what it looks like in the code.

**Comment by nashif** [comment]
> How does it specifically address the concerns and open issues raised by the UX study, for example?

which concerns exactly are you referring to? I looked at the list of items, most of them are about content and not structure if I am not mistaken.

> I want to know more about why you are proposing this from a high level before diving too deep into the details.

Lots of details in #33725, but, the main issue we have right now is very suboptimal structure making it very difficult navigating through the docs. For example the separation between API reference and the actual documentation of a subsystem, `guides` becoming a dumping ground for new component without any structure, so you end up having 'Coccinelle' documentation at the same level we have 'Bluetooth' and 'Networking', etc.


> * How will it help us solve problems like generating hardware support information on a per-board basis from devicetree/device drivers, for a particular example? 

Such information would end up in the board docs I guess. Do we have plans to do this and what is missing to support this beside figuring out the structure

> I think there is a gap between "architecture" and "board" here where the docs are concerned, and it's that we don't have a place to document support for individual SoCs (like SoC DTSI, peripheral info in there, associated drivers, etc.) or refer to that documentation from board docs, even though that is an important part of how the code itself is organized

For SoCs and hardware support in general this could end up in a new section encapsulating all hardware related information if that what is needed. Right now the structure is based on the existing docs, however given the above, we can  move into the direction which would support SoCs and automated documentation coming in the future.

> I see that you want to get rid of guides vs reference, but you don't justify why. I think guides, or tutorial material, is critically important and I want to understand the reasoning and goals behind your proposal here too.

Touched on this above, but having guides as the single place where each new subsystem or component is added does not scale anymore and is very difficult to navigate. With the new structure, the amount of content we have under guides or reference will be reduced to a minimum hopefully. Goal is to move majority of those items to top level sections that are easier to find and easier to navigate. If we identify that we still have pages that are categorised as guides and do not fit anywhere also, this where we should consider leaving the top level Guides pages but with more control on what ends up in there.

**Comment by nashif** [comment]
> I think that before we start moving top-level items around we should first agree that the proposed layout is what we want to converge into.

yes, agree that we have to agree, consider this PR as the trigger.




> For example, I am unsure about not placing Bluetooth and Networking inside a potential subsystems category, because that is what it looks like in the code.

Both Bluetooth and Networking are under one chapter in this case. I do not think it helps if we dumped everything under subsystems in one category in the docs. This is where we have to categorize the subsystems based on the usage. So as described in the proposal above I would distinguish between the different subsystems, ie.. connectivity (net, bluetooth, ..), os services (logging, shell, debugging, tracing, ...), libraries etc...

**Comment by nashif** [comment]
for the lazy, here is the new left side bar...

image

**Comment by nashif** [comment]
> I looked at the changes and many make sense to me, but I am left with a feeling of unease when looking at some others. I think that before we start moving top-level items around we should first agree that the proposed layout is what we want to converge into. For example, I am unsure about not placing Bluetooth and Networking inside a potential subsystems category, because that is what it looks like in the code.

@carlescufi  please provide more input in the related issue or here. _"left with a feeling of unease  when looking at some others"_ is a bit vague..

**Comment by carlescufi** [comment]
I'd like to make progress with this @nashif, wondering why this PR differs quite a bit from the proposal you made here:
https://github.com/zephyrproject-rtos/zephyr/issues/33725#issuecomment-994790970

**Review by carlescufi — CHANGES_REQUESTED** [review]
Looks quite good, I have a few suggestions by looking at the [rendered output](https://builds.zephyrproject.io/zephyr/pr/41154/docs/index.html)

1. Rename "The Kernel" with "Kernel"
2. Devicetree guide should be under "Build and Configuration systems"
3. Why still the separate section "REFERENCE" when we could move this into the respective areas?
4. I really liked @mbolivar-nordic's [proposals](https://github.com/zephyrproject-rtos/zephyr/issues/33725#issuecomment-1040678367) of:
   - A "Developing with Zephyr" section
   - A "Development and Governance" section (though this needs a new name because I really don't think we should repeat "Developing" and "Development"
   - A "Contributing to Zephyr" section
 
Could we add those here too?

cc @mbolivar-nordic @gmarull

**Comment by nashif** [comment]
update:
- Went all the way and removed both `reference` and `guides` sections
- Moved content to where it made most sense, some items needs some additional thought
- Tried as much as possible not to change content and get into the second stage of the overhaul. Any refinement to the documentation in their new location will need to be done after this PR get merged.

**Comment by nashif** [comment]
output https://builds.zephyrproject.io/zephyr/pr/41154/docs/

**Review by carlescufi — DISMISSED** [review]
This looks quite good for a first pass. Let's get it in and build on top, thank you @nashif

**Comment by henrikbrixandersen** [comment]
This looks like a good foundation for further improving our documentation. Better than what we have now, I think.

**Review by MaureenHelm — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
At least, this looks to be much better organised than the status quo.

**Pull request merged**
