### PR TITLE
Bluetooth: controller: Fix control procedure transaction violation checks

### PR DESCRIPTION
**Pull request by cvinayak**
Fix the following control procedure handling to check transaction violations:
- Feature Exchange response
- Unknown Control Procedure response
- Reject Extended Indication dispatch
- Data Length Update response
- Ping response
- PHY Update response

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by sjanc** [comment]
So what exactly is fixed by this PR?    If remote request is ignored, link will drop anyway, right?

**Comment by cvinayak** [comment]
> 
> 
> So what exactly is fixed by this PR? If remote request is ignored, link will drop anyway, right?

The PR is addressing repeated duplicate control PDUs reception which deplete the control Tx PDU pool if the duplicate PDUs are not dropped. In the implementation where Rx (data/control) PDUs and done events are processed synchronously, on depletion of control Tx pool, done event processing is stalled causing assertion.

**Comment by sjanc** [comment]
what do you mean by "repeated duplicate control PDUs"?

**Comment by cvinayak** [comment]
Example, Central sending repeated Feature Exchange without receiving a response from peer (nacking).

```
central                          Peripheral
--------                         ----------
	|                                |
	|--------- FEATURE_REQ---------->|
	|<--------   EMPTY  -------------| 
	|                                |
	|                                |
	|--------- FEATURE_REQ---------->|
	|<--------   EMPTY  -------------| 
	|                                |
	|                                |
	|--------- FEATURE_REQ---------->|
	|<--------   EMPTY  -------------| 
	|                                |
	|                                |
				  ...
	|--------- FEATURE_REQ---------->|
	|<--------   EMPTY  -------------| 
	|                                |
	|                                |
```

**Comment by andrzej-kaczmarek** [comment]
So do I understand correctly that central sent FEATURE_REQ, peripheral sent empty PDU with NAK, then central retransmitted that same PDU and it causes issue on peripheral?

**Comment by cvinayak** [comment]
> 
> 
> So do I understand correctly that central sent FEATURE_REQ, peripheral sent empty PDU with NAK, then central retransmitted that same PDU and it causes issue on peripheral?

No, central sends repeated new FEATURE_REQ PDU and NACKs any receptions from peripheral.

**Comment by sjanc** [comment]
And this device is acting like that for every procedure? what device is it?

**Comment by andrzej-kaczmarek** [comment]
So this is not a correct way of handling issue - we should disconnect link upon receiving 2nd LL_FEATURE_REQ.

See Core 5.2, Vol 1, Part E, 2.7 _Responding to invalid behavior_

> If a device receives a packet or PDU that it supports but is not permitted in its current state, the sending device has exhibited invalid behavior. Unless the specification states a particular action to be taken, the receiving device should respond in one of the following ways:
> _(...)_
> * If the packet or PDU was received from the peer device in a connection, either immediately terminate that connection or consider the connection to be lost.

and then:

> Note: Examples of packets or PDUs not permitted in the current state include:
> _(...)_
> Two consecutive LL_FEATURE_REQ PDUs sent by a master device with no LL_FEATURE_RSP sent by the slave between them

**Comment by cvinayak** [comment]
The full spec text is:

> 2.7 RESPONDING TO INVALID BEHAVIOR
If a device receives a packet or PDU that it supports but is not permitted in its current state, the sending device has exhibited invalid behavior. Unless the specification states a particular action to be taken, the receiving device should respond in one of the following ways:
• Ignore the packet or PDU.
• Attempt to recover the situation (e.g. by sending a rejection response) while both not violating the specification and being prepared for the sending device to be in a state where one or both devices cannot recover.
• If the packet or PDU was received from the peer device in a connection, either immediately terminate that connection or consider the connection to be lost.

The term `should` is used in the specification, and does not strictly enforce termination as the first action, and suggests to ignore PDU, attempt to recover, or terminate under security procedure scenario.

**Comment by andrzej-kaczmarek** [comment]
That's correct, but I think silently ignoring PDU should not be used on connections since you are intentionally going out of sync with peer. Quoted section in spec was added due to errata 9674 which covers handling connection PDUs and ignoring silently is not mentioned there.

I would still personally go for termination as it can't go wrong. You don't really know what will happen if you reject PDU that is not "rejectable" under normal circumstances.

**Comment by cvinayak** [comment]
A spoofed control PDU will result in connection termination, hence ignoring the PDU on invalid behavior provides better user experience.

**Comment by andrzej-kaczmarek** [comment]
If you want to terminate connection by spoofing PDU, it's much easier to use LL_TERMINATE_IND for this purpose ;)

**Comment by cvinayak** [comment]
Likelihood of TERMINATE_IND (yes under deliberate attack but otherwise) is lower compared to FEATURE_REQ which get exchanged when new connections are created when large number of devices are in a room. Access address and channel need to match, but it is possible.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@kruithofa @sjanc @andrzej-kaczmarek @wopu-ot @thoh-ot please review

**Review by kruithofa — APPROVED** [review]

**Pull request merged**
