### PR TITLE
net: ip: Add missing include guards

### PR DESCRIPTION
**Pull request by nordicjm**
Adds include guards to header files where it was missing

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Originally these were left away on purpose as these private files are really meant for private use in one or two .c files and not to be included by other .h files. So if one sees an error somewhere about these then that indicates misuse where these private files are included in .h file.
So in this respect I think we should not add these guards.

**Comment by nordicjm** [comment]
The conflict seems to be between mbedtls, psa and shell in downstream ncs:
```
In file included from ../../../../../zephyr/subsys/net/lib/shell/common.h:26,
                 from ../../../../../nrf/subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h:28,
                 from ../../../../../nrf/ext/oberon/psa/core/include/psa/crypto_struct.h:127,
                 from ../../../../../nrf/ext/oberon/psa/core/include/psa/crypto.h:4058,
                 from ../../../../../nrf/ext/oberon/psa/core/include/mbedtls/legacy_or_psa.h:104,
                 from ../../../../../modules/crypto/mbedtls/include/mbedtls/x509_crt.h:27,
                 from ../../../../../modules/crypto/mbedtls/include/mbedtls/ssl.h:35,
                 from ../../../../../modules/crypto/mbedtls/include/mbedtls/net_sockets.h:44,
                 from ../../../../../zephyr/subsys/net/lib/sockets/sockets_tls.c:46:
../../../../../zephyr/subsys/net/ip/net_private.h:30:7: error: redefinition of 'union net_mgmt_events'
   30 | union net_mgmt_events {
      |       ^~~~~~~~~~~~~~~
In file included from ../../../../../zephyr/subsys/net/lib/shell/common.h:26,
                 from ../../../../../nrf/subsys/nrf_security/include/psa/crypto_driver_contexts_primitives.h:27,
                 from ../../../../../nrf/ext/oberon/psa/core/include/psa/crypto_struct.h:79:
../../../../../zephyr/subsys/net/ip/net_private.h:30:7: note: originally defined here
   30 | union net_mgmt_events {
      |       ^~~~~~~~~~~~~~~
```

Whilst the file *should* only be included once, I see no harm in having an include guard for these

**Comment by jukkar** [comment]
> subsys/net/lib/shell/common.h

The actual error is there, the header file should not include this network private header file.

**Review by jukkar — CHANGES_REQUESTED** [review]
Let me set my -1 for this change. The fix should be done in those .h files that try to include these private header.

**Comment by jukkar** [comment]
> subsys/net/lib/shell/common.h

I can provide a fix for this.

**Comment by nordicjm** [comment]
> > subsys/net/lib/shell/common.h
> 
> The actual error is there, the header file should not include this network private header file.

With it removed from this file, there are many, many warnings emitted, e.g.:
```
/tmp/aa/zephyr/subsys/net/lib/shell/tcp.c:83:28: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'int' [-Wformat=]
   83 |                         PR("Connecting from [%s]:%u ",
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
   84 |                            net_sprint_ipv6_addr(&net_sin6(myaddr)->sin6_addr),
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            |
      |                            int
/tmp/aa/zephyr/subsys/net/lib/shell/common.h:12:41: note: in definition of macro 'PR'
   12 |         shell_fprintf(sh, SHELL_NORMAL, fmt, ##__VA_ARGS__)
      |                                         ^~~
/tmp/aa/zephyr/subsys/net/lib/shell/tcp.c:83:47: note: format string is defined here
   83 |                         PR("Connecting from [%s]:%u ",
      |                                              ~^
      |                                               |
      |                                               char *
      |                                              %d
/tmp/aa/zephyr/subsys/net/lib/shell/tcp.c:86:28: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'int' [-Wformat=]
   86 |                         PR("to [%s]:%u\n",
      |                            ^~~~~~~~~~~~~~
   87 |                            net_sprint_ipv6_addr(&net_sin6(addr)->sin6_addr),
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            |
      |                            int
/tmp/aa/zephyr/subsys/net/lib/shell/common.h:12:41: note: in definition of macro 'PR'
   12 |         shell_fprintf(sh, SHELL_NORMAL, fmt, ##__VA_ARGS__)
      |                                         ^~~
/tmp/aa/zephyr/subsys/net/lib/shell/tcp.c:86:34: note: format string is defined here
   86 |                         PR("to [%s]:%u\n",
      |                                 ~^
      |                                  |
      |                                  char *
      |                                 %d
```

**Comment by jukkar** [comment]
> from ../../../../../nrf/subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h

There seems to be an error here. Why the network shell "common.h" is tried to include by this crypto header.

**Comment by nordicjm** [comment]
> > from ../../../../../nrf/subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h
> 
> There seems to be an error here. Why the network shell "common.h" is tried to include by this crypto header.

Right you are. @joerchan one for you, `subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h` has:
```
#include "common.h"

#include "psa/crypto_driver_common.h"
```
There is no common.h in this folder, so the include path one is used, needs the file adding to the same folder or renamed to something that's not generic.

**Comment by jukkar** [comment]
I renamed the net-shell `common.h` to be more unique in order to avoid possible naming conflicts. #66496

**Comment by joerchan** [comment]
> > > from ../../../../../nrf/subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h
> > 
> > 
> > There seems to be an error here. Why the network shell "common.h" is tried to include by this crypto header.
> 
> Right you are. @joerchan one for you, `subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h` has:
> 
> ```
> #include "common.h"
> 
> #include "psa/crypto_driver_common.h"
> ```
> 
> There is no common.h in this folder, so the include path one is used, needs the file adding to the same folder or renamed to something that's not generic.

@nordicjm That file is in NCS. Nothing to do for this project.



> > > from ../../../../../nrf/subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h
> > 
> > 
> > There seems to be an error here. Why the network shell "common.h" is tried to include by this crypto header.
> 
> Right you are. @joerchan one for you, `subsys/nrf_security/include/psa/crypto_driver_contexts_composites.h` has:
> 
> ```
> #include "common.h"
> 
> #include "psa/crypto_driver_common.h"
> ```
> 
> There is no common.h in this folder, so the include path one is used, needs the file adding to the same folder or renamed to something that's not generic.

Yeeeeah. That common.h file is in mbedtls. So that is not an easy fix there.

**Comment by nordicjm** [comment]
> Yeeeeah. That common.h file is in mbedtls. So that is not an easy fix there.

What about having the base path as the include so that you then have to have `library/config.h`? It's not great but at least it will prevent problems with other libraries and user code

**Comment by joerchan** [comment]
> > Yeeeeah. That common.h file is in mbedtls. So that is not an easy fix there.
> 
> What about having the base path as the include so that you then have to have `library/config.h`? It's not great but at least it will prevent problems with other libraries and user code

@nordicjm The files that use this header are built as part of the mbedtls library. All of the sources and headers have this include path. I'm not against fixing this issue, but I think to avoid any issues it needs to be done starting in mbedtls.
Example:
https://github.com/Mbed-TLS/mbedtls/blob/development/library/aes.c#L14

**Pull request closed without merging**
