### PR TITLE
device: Fixed CPP compatiblity for driver instantation

### LINKED ISSUE #54737: Wrong order of member initialization for macro Z_DEVICE_INIT
**Describe the bug**
I am trying to develop a driver with C++ and based on the boilerplate for many drivers I see that the structs are initialized basically with `DT_INST_FOREACH_STATUS_OKAY`. I noticed a compiler error for C++ due to the wrong order of the initialization of `struct device` within the macro Z_DEVICE_INIT.  

**To Reproduce**
Develop a driver with C++ and use the macro `DT_INST_FOREACH_STATUS_OKAY`

**Expected behavior**
No compiler error regarding struct order initiliazation.

**Impact**
Have to redefine the Z_DEVICE_INIT to develop C++ drivers.

### LINKED ISSUE #54739: C++ Compatibility for DEVICE_DT_INST_DEFINE
**Describe the bug**
C++ source files cannot use the macro for driver development `DEVICE_DT_INST_DEFINE.` As far as I have tested there are two main issues with the macro . 

1. Calling `Z_DEVICE_INIT` uses the wrong order of initiliazition which is a must for C++ compatibility.
2. When macro `Z_DEVICE_HANDLES_DEFINE`  is called, the macro `Z_DEVICE_HANDLES_SECTION` uses the `weak `attribute. For C++ it also requires the keyword `extern` otherwise the compiler throws the error: `error: weak declaration of '__devicehdl_dts_ord_XXXXXX' must be public`. 

I have made a pull request that fixes these issues : https://github.com/zephyrproject-rtos/zephyr/pull/54762

I have made some preliminary tests by developing drivers with C++ and the zephyr macros and I am satisfied that I can now integrate C++ syntax to my projects. Feel free to discuss if there is something else that still has to be changed to make the current C Macros compatible for C++ driver development.

### PR DESCRIPTION
**Pull request by vChavezB**
The macro `DEVICE_DT_INST_DEFINE` is not compatible with C++.  Thus developing drivers with CPP is not possible. There are two macros that cause this problem.

1.   `Z_DEVICE_INIT` : Has wrong order of initialization for the struct `device`
2.   `Z_DEVICE_HANDLES_DEFINE` : By using the __weak attribute with the variable declared with `Z_DEVICE_HANDLES_NAME`, C++ throws the error "weak declaration must be public".

This commit fixes the issue by first rearranging the order of initialization of the members in the macro `Z_DEVICE_INIT`. Secondly, a macro called `Z_DEVICE_HANDLES_EXTERN` has been added. This allows to declares the variable defined by `Z_DEVICE_HANDLES_NAME` as `extern` if used in a CPP context.

Signed-off-by: Victor Chavez <chavez-bermudez@fh-aachen.de>

Fixes #54739
Fixes #54737

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]

**Review by galak — COMMENTED** [review]
Does c++ not respect the named initializers?  (ie the issue w/ordering in Z_DEVICE_INIT)?

If not, probably good to add a comment about needing the order of init to match the struct elements for C++

**Comment by vChavezB** [comment]
> Does c++ not respect the named initializers?

The struct order defined in https://github.com/zephyrproject-rtos/zephyr/blob/06d5bc51b580777079bb0b7e769e4127598ea5ee/include/zephyr/device.h#L378-L405 does not match the order of initialization of the macro `Z_DEVICE_INIT `https://github.com/zephyrproject-rtos/zephyr/blob/06d5bc51b580777079bb0b7e769e4127598ea5ee/include/zephyr/device.h#L855-L864.

Initialization order does not matter if compiling with clang (gives only ISO c++ warning) but GCC does not allow this. See code snippet https://godbolt.org/z/Ecahjbe6Y

**Review by galak — APPROVED** [review]

**Comment by vChavezB** [comment]
Just as info, I messed up while trying to fix the commit message to pass the zephyr guideline pipeline. That is the reason now this pull-requests states that 5000+ files have been modified.

**Comment by carlocaione** [comment]
No need to close the PR. Just force push the correct commits on top of `main`

**Comment by vChavezB** [comment]
> No need to close the PR. Just force push the correct commits on top of `main`

Yes, I will check that. Actually I am not sure that I closed it directly, I force pushed a commit and the pull-request closed-itself (at least thats my impression).

Thanks for the suggestion.

**Pull request closed without merging**
