### PR TITLE
drivers: flash: stm32: Fix insufficient wait time

### LINKED ISSUE #16934: drivers: flash: stm32l4: Erase wait time is not enough
**Describe the bug**
`flash_erase` cannot erase a page from the STM32L4 SOC flash. I've seen it, after investigating why MCUboot would never perform swapping and always resulted in *panic*.

I concluded that the erase time of a 2K page is not enough. STM32L496xx datasheet states in *6.3.10 Flash memory characteristics*, that the maximum erase time is 24.47ms. It is also noted that these characteristics are *guaranteed by design*. I tried wait times for `flash_stm32_wait_flash_idle` from 25ms (initial) up to 30ms. The 30ms one worked all the times I tested. It seems that the erase time is a little bit off.

I've also studied the code of [texane/stlink](https://github.com/texane/stlink/blob/d040db5585d33dc36bd8ae093c024583ef1b4f74/src/common.c#L1629) just to get an idea of how they erase a page. They just [poll on the `SR_BUSY` bit](https://github.com/texane/stlink/blob/d040db5585d33dc36bd8ae093c024583ef1b4f74/src/common.c#L597). So it works.

For a quick test I created a sample that replicates the issue on Nucleo L496ZG:

**main.c**:
```c
/*
 * Copyright (c) 2019 Centaur Analytics, Inc
 */

#include <zephyr.h>
#include <misc/printk.h>
#include <flash.h>

#define FLASH_TEST_OFFSET 0x080000

void main(void)
{
    struct device *flash_dev;
    int rc;

    flash_dev = device_get_binding(DT_FLASH_DEV_NAME);
    if (!flash_dev) {
        printk("Cannot bind to %s\n", DT_FLASH_DEV_NAME);
        goto fail_exit;
    }

    flash_write_protection_set(flash_dev, false);

    printk("Trying to erase one page at offset 0x%04x\n", FLASH_TEST_OFFSET);
    rc = flash_erase(flash_dev, FLASH_TEST_OFFSET, FLASH_PAGE_SIZE);
    if (rc == -EINVAL) {
        printk("Invalid range\n");
        goto fail_exit;
    } else if (rc == -EIO) {
        printk("IO error\n");
        goto fail_exit;
    } else if (rc < 0) {
        printk("Could not erase area\n");
        goto fail_exit;
    }

    printk("Success\n");

fail_exit:
    while (1) {
        k_sleep(1000);
    }
}
```

**prj.conf**:
```
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_FLASH=y
CONFIG_FLASH_HAS_PAGE_LAYOUT=y
```

**To Reproduce**
1. west build -b nucleo\_l496zg -s samples/flash\_erase\_page
2. st-flash write build/zephyr/zephyr.bin 0x8000000

**Expected behavior**
The page should have been erased in the time stated by the Datasheet.

**Impact**
no comment

**Screenshots or console output**
One can see the outcome if modifies the `STM32_FLASH_TIMEOUT` from 25ms to 30ms for `CONFIG_SOC_SERIES_STM32L4X`:

**@25ms**:
```
Trying to erase one page at offset 0x80000
IO Error
```

**@30ms**:
```
Trying to erase one page at offset 0x80000
Success
```

**Environment:**
 - OS: GNU/Linux
 - Toolchain: Zephyr SDK
 - Zephyr tags/v1.14.0

**Additional context**
> I know that, if I'm not missing something, this is not a Zephyr problem, but a ST one. I'm reporting here to be sure.

If the workaround seems OK, I could open a PR and also add a test sample.

### PR DESCRIPTION
**Pull request by gon1332**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/16934

### CODE REVIEW

**Comment by gon1332** [comment]
@erwango 

Also, it would be good if this finds its way to 1.14.

**Comment by ioannisg** [comment]
@erwango please review this minor bug-fix

**Comment by ioannisg** [comment]
Change unsufficient to insufficient in the commit title.

**Comment by gon1332** [comment]
> Change unsufficient to insufficient in the commit title.

Oops. Done.

**Review by aurel32 — APPROVED** [review]
Looks good to me.

**Review by erwango — COMMENTED** [review]
I'm fine with the change but I think there is nothing L4 specific in this approach. What about extending the change to the whole driver (whole stm32 family)?

To do this, I'd propose to rename current soc specific defines to STM32_FLASH_MAX_ERASE_TIME
and redefine STM32_FLASH_TIMEOUT as
```
#define STM32_FLASH_TIMEOUT     2 * STM32_FLASH_MAX_ERASE_TIME
```
Maybe @superna9999 can comment.

**Comment by gon1332** [comment]
> I'm fine with the change but I think there is nothing L4 specific in this approach. What about extending the change to the whole driver (whole stm32 family)?
> 
> To do this, I'd propose to rename current soc specific defines to STM32_FLASH_MAX_ERASE_TIME
> and redefine STM32_FLASH_TIMEOUT as
> 
> ```
> #define STM32_FLASH_TIMEOUT     2 * STM32_FLASH_MAX_ERASE_TIME
> ```
> 
> Maybe @superna9999 can comment.

Your proposition is logical. I only had a hesitation, because I don't have other SOC's to test. On the other side, this patch does not restrict but gives more time for the operation to complete.

So here are the changes for the whole STM32 family.

**Review by erwango — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by joerchan** [comment]
@gon1332 Automatic backport failed, it needs to be done manually.

**Pull request merged**
