### PR TITLE
drivers: bbram: Add it8xxx2 BBRAM driver implementation

### PR DESCRIPTION
**Pull request by yperess**
Note that the it8xxx2 does not support a status register so that functionality is omitted.

Signed-off-by: Yuval Peress <peress@chromium.org>

---
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37851)

### CODE REVIEW

**Review by brockus-zephyr — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37851)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @galak, @GTLin08, @jackrosenthal, @keith-zephyr, and @sjg20)

**Review by keith-zephyr — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37851)* status: all files reviewed, 1 unresolved discussion (waiting on @ChiHuaL, @galak, @GTLin08, @jackrosenthal, @mbolivar-nordic, @MulinChao, @sjg20, @WealianLiao, and @yperess)

___
*[dts/riscv/it8xxx2.dtsi, line 40 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37851#-Mho_UlQ1oemMv9qcFMa:-Mho_UlQ1oemMv9qcFMb:bsmdyqn) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/4711fd69982c65d9fe510d53c23022859180e188/dts/riscv/it8xxx2.dtsi#L40)):*
> ```
> 			compatible = "ite,it8xxx2-bbram";
> 			status = "okay";
> 			reg = <0x00f02200 0xbf>;
> ```

Size is 192 bytes - 0xc0.

**Review by brockus-zephyr — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37851)* status: all files reviewed, 1 unresolved discussion (waiting on @ChiHuaL, @galak, @GTLin08, @jackrosenthal, @mbolivar-nordic, @MulinChao, @sjg20, @WealianLiao, and @yperess)

**Review by keith-zephyr — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37851)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChiHuaL, @galak, @GTLin08, @jackrosenthal, @mbolivar-nordic, @MulinChao, @sjg20, and @WealianLiao)

**Review by GTLin08 — APPROVED** [review]

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
A few more follow ups beyond the above comment.  I also think CI should probably be build testing the things in drivers/bbram with a new subdirectory of tests/drivers/build_all.

**Review by brockus-zephyr — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37851)* status: all files reviewed, 3 unresolved discussions (waiting on @ChiHuaL, @galak, @jackrosenthal, @mbolivar-nordic, @MulinChao, @sjg20, and @WealianLiao)

**Comment by yperess** [comment]
@mbolivar-nordic I've update the PR to include build-only tests. That's the best I could find for making sure that the bbram drivers are up and running. Please point me in the right direction if there's a `qemu` platform that could run actual tests on the driver or if there's a better way to do this.

**Comment by yperess** [comment]
I split this up into 2 commits.

**Review by mbolivar-nordic — APPROVED** [review]
Looks good to me, glad to see that build testing is catching a few things that have snuck in.

**Pull request merged**
