### PR TITLE
sanitycheck: Make --hardware-map and --west-flash together

### PR DESCRIPTION
**Pull request by oyvindronningstad**
When passing a using --hardware-map, sanitycheck would ignore extra
args passed via --west-flash, such as --west-flash="--erase".

This is because the command with the extra args was overwritten by the
command with the runner info from the hardware map.

This patch merges those code paths so they are aware of each other and
of --west-runner.

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
I don't know this code super well, but I tested this with `--hardware-map` + `--device-testing` and it worked for me as described in the commit log, with and without `--west-flash=--erase`.

**Comment by galak** [comment]
@oyvindronningstad can you rebase to fix the merge conflict.

**Review by tejlmand — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
the flashing activity and using west is per instance and not for running with hardware map which might have multiple devices of different types that may or may not support the flash options you are supplying on the command line.

We should instead consider adding such option to the flasher per target in the hardware map. If you are just testing one device, you do not need the hardwaremap and can still use the --west-flash options.

**Comment by oyvindronningstad** [comment]
> the flashing activity and using west is per instance and not for running with hardware map which might have multiple devices of different types that may or may not support the flash options you are supplying on the command line.
> 
> We should instead consider adding such option to the flasher per target in the hardware map. If you are just testing one device, you do not need the hardwaremap and can still use the --west-flash options.

I'm testing multiple nrf devices, all of which are using nrfjprog. This change is a concrete improvement for that use case.

I get the point that there might be a mix of runners in the hardware map. I don't see the harm with this change though, since if there's a mix of runners, the call will likely fail gracefully when encountering an arg the runner doesn't recognize. Alternatively I could also add a check that will fail immediately if --west-flash is given together with a hardware map with a mix of runners.

Putting the args in the hardware map sounds counter to the idea of the hardware map as purely a description of the hardware (if this is a distinction we want to make). Also, it's much less convenient, you would likely need duplicate hardware map files for different use cases (e.g. one file with `--erase` and one without).

**Comment by nashif** [comment]
ok, this used to work:
```sanitycheck --device-testing --device-serial /dev/ttyACM9 -T samples/hello_world/ -p nrf52840dk_nrf52840 --west-flash="--snr=000683292894" -vv --west-runner nrfjprog```

now it does not:

```
DEBUG   - Flash command: ['west', 'flash', '--skip-rebuild', '-d', '/home/nashif/zephyrproject/zephyr/sanity-out/nrf52840dk_nrf52840/samples/hello_world/sample.basic.helloworld', '--runner', 'nrfjprog', '--', '--snr=000683292894', '--snr', None]
ERROR   - 'nrf52840dk_nrf52840/samples/hello_world/sample.basic.helloworld' generated an exception:
ERROR   - Traceback (most recent call last):
ERROR   -   File "/home/nashif/zephyrproject/zephyr/scripts/sanity_chk/sanitylib.py", line 2957, in execute
ERROR   -     data = future.result()
ERROR   -   File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
ERROR   -     return self.__get_result()
ERROR   -   File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
ERROR   -     raise self._exception
ERROR   -   File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
ERROR   -     result = self.fn(*self.args, **self.kwargs)
ERROR   -   File "/home/nashif/zephyrproject/zephyr/scripts/sanity_chk/sanitylib.py", line 2076, in process
ERROR   -     self.run()
ERROR   -   File "/home/nashif/zephyrproject/zephyr/scripts/sanity_chk/sanitylib.py", line 2242, in run
ERROR   -     instance.handler.handle()
ERROR   -   File "/home/nashif/zephyrproject/zephyr/scripts/sanity_chk/sanitylib.py", line 679, in handle
ERROR   -     with subprocess.Popen(command, stderr=subprocess.PIPE, stdout=subprocess.PIPE) as proc:
ERROR   -   File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
ERROR   -     restore_signals, start_new_session)
ERROR   -   File "/usr/lib64/python3.7/subprocess.py", line 1482, in _execute_child
ERROR   -     restore_signals, start_new_session, preexec_fn)
ERROR   - TypeError: expected str, bytes or os.PathLike object, not NoneType
'nrf52840dk_nrf52840/samples/hello_world/sample.basic.helloworld' generated an exception: expected str, bytes or os.PathLike object, not NoneType
```

**Review by nashif — CHANGES_REQUESTED** [review]
--snr is getting null when using --device-serial, ie.. not using hardware map file.

**Comment by oyvindronningstad** [comment]
Sorry, must have messed up the conflict resolution.

Tested now with and without hardware map.

**Review by nashif — APPROVED** [review]

**Pull request merged**
