### PR TITLE
twister: footprint: Add optional detailed JSON report on symbols

### PR DESCRIPTION
**Pull request by golowanow**
An alternative implementation to #72131 

New Twister option `--footprint-report` is introduced to collect and report detailed memory footprint results (for symbols) as an additional JSON file. By default, the new option is disabled.

The new option implies and extends `--create-rom-ram-report`, so currently there are three choices: 'ROM', 'RAM', and 'all' to select which memory areas data report additionally as `twister_footprint.json`.
In case of a custom report name, or per-platform report mode, it is always composed with the rightmost `_footprint.json` suffix.

The additional detailed JSON report has similar structure as `twister.json` and compelements it, also having a reduced set of the testsuite properties:
- instead of `testcases` list it contains `footprint` object with `rom.json` and `ram.json` artifacts embedded;
- other properites are limited to represent the context of the testsuite build execution, thus to allow further data processing consistently and independently from the `twister.json`;
- 'filtered' test instances are not included into the footprint report.

### CODE REVIEW

**Review by hakehuang — DISMISSED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
I see 
```
        {
            "name":"tests/kernel/threads/no-multithreading/kernel.threads.no-multithreading",
            "arch":"arm",
            "platform":"frdm_k64f",
            "path":"tests/kernel/threads/no-multithreading",
            "run_id":"e9cceb9c408e27ddbf022f436c5ff082",
            "status":"filtered",
            "reason":"Not in testsuite platform allow list",
            "build_time":"0.00"
        },
``` 
in the footprint report, there is no need to list testsuites that are not never built in the footprint report.

**Comment by golowanow** [comment]
@nashif 
> in the footprint report, there is no need to list testsuites that are not never built in the footprint report.

added to not include 'filtered' instances.

**Comment by golowanow** [comment]
review comments, some improvements, and rebased to resolve merge conflict.
@nashif, @hakehuang please have a look again.

**Comment by golowanow** [comment]
dear reviewers, up to your attention

**Review by hakehuang — DISMISSED** [review]

**Comment by golowanow** [comment]
rebased resolving merge conflicts

**Review by nashif — APPROVED** [review]
This is now loading existing standalone json data into another json structure, it would be great to see where this is all going and how this approach will replace the infrastructure under scripts/footprint and ultimately generate the results and footprint available on stats.zephyrproject.org.

**Comment by golowanow** [comment]
> This is now loading existing standalone json data into another json structure,

the existing json data remains the same being complimented with another optional json of similar structure enriched by the footprint data.

> it would be great to see where this is all going and how this approach will replace the infrastructure under scripts/footprint and ultimately generate the results and footprint available on stats.zephyrproject.org.

I can prepare a presentation for the Testing WG meeting for how the footprint data looks like on Elasticsearch/Kibana dashboard with multiple aggregation levels/subsystems - this way it should allow to resolve #49227 and improve [stats.zephyrproject.org](https://stats.zephyrproject.org/testing/d/SSxr5P6Gk/footprint-tracking?orgId=1) either using the new data structure, or migrating the current Grafana dashboard to ELK.

There are no plans to replace `scripts/footprint` at the moment, although it might be extended with more tools/examples to gather footprint statistics from Elasticsearch.

Also, there is a useful extension for [scripts/ci/upload_test_results_es.py](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/ci/upload_test_results_es.py) script which might be upstreamed later as a follow-up for this PR, if accepted.

**Comment by golowanow** [comment]
@hakehuang could you please refresh your review after rebase ?

**Review by hakehuang — APPROVED** [review]

**Comment by nashif** [comment]
> I can prepare a presentation for the Testing WG meeting for how the footprint data looks like on Elasticsearch/Kibana dashboard with multiple aggregation levels/subsystems - this way it should allow to resolve #49227 and improve [stats.zephyrproject.org](https://stats.zephyrproject.org/testing/d/SSxr5P6Gk/footprint-tracking?orgId=1) either using the new data structure, or migrating the current Grafana dashboard to ELK.
> 

This is not related to the testing WG at all.

> There are no plans to replace `scripts/footprint` at the moment, although it might be extended with more tools/examples to gather footprint statistics from Elasticsearch.
> 
> Also, there is a useful extension for [scripts/ci/upload_test_results_es.py](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/ci/upload_test_results_es.py?rgh-link-date=2024-06-05T12%3A44%3A34Z) script which might be upstreamed later as a follow-up for this PR, if accepted.

I am not following:
- What is the next step after this PR that would move us from grafana and current scripting for footprint tracking in scripts/footprint to elasticsearch and more granular reporting?

**Comment by golowanow** [comment]
@nashif, thank you for accepting this PR; answering your question:

> I am not following, clarifying question below:
> * What is the next step after this PR that would move us from grafana and current scripting for footprint tracking in scripts/footprint to elasticsearch and more granular reporting?

The next step is to upstream extended `scripts/ci/upload_test_results_es.py` which facilitatates json transformations to upload into a 'Kibana-friendly' data index ('Kibana-friendly' means no need in custom charts to show hierarchical data like the footprint).

> This is not related to the testing WG at all.

it might be any other relevant Zephyr working group you'd advice to ask for feedback, or should I file an RFC ?

**Pull request merged**
