### PR TITLE
soc: rt11xx: usb2: Typo in clock initialization of usb2

### LINKED ISSUE #81027: Typo error in soc nxp rt11xx usb2 clock initialization
**Describe the bug**

In file soc.c under directory soc/nxp/imxrt/imxrt11xx line 539.  This part of code is obviously used to initialize the usbs but use usb1 as device tree node label.

### PR DESCRIPTION
**Pull request by Raymond0225**
a typo in usb2 clock initialization which impact the function of usb2.
 

Fixes #81027

### CODE REVIEW

**Comment by decsny** [comment]
if it is a bug, then you will have to link a bug report to merge to 4.0.

**Comment by Raymond0225** [comment]
> if it is a bug, then you will have to link a bug report to merge to 4.0.

it is a bug reported by someone but no bug report, how to do?

**Comment by decsny** [comment]
> > if it is a bug, then you will have to link a bug report to merge to 4.0.
> 
> it is a bug reported by someone but no bug report, how to do?

you just need to make a github issue on this repo with the bug report template

**Comment by Raymond0225** [comment]
> bug report created: #81027

**Review by dleach02 — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Pull request merged**
