### PR TITLE
Refactor locking in TCP2

### PR DESCRIPTION
**Pull request by jukkar**
This one removes a separate lock in TCP2 and starts to use the same lock as in net_context. This hopefully will get rid of deadlocks in heavy load. See also #29444

### CODE REVIEW

**Comment by ohitz** [comment]
@jukkar I did a first quick test. Apart from the `Invalid TCP state: 0` assertion you have probably also seen, I noticed that in our application HTTP uploads are more than 10 times slower.

**Comment by jukkar** [comment]
> I noticed that in our application HTTP uploads are more than 10 times slower.

That is quite unexpected result.

**Comment by ohitz** [comment]
> > I noticed that in our application HTTP uploads are more than 10 times slower.
> That is quite unexpected result.

Maybe don't pay too much attention to that as long as there are assertion failures.

**Comment by jukkar** [comment]
> Apart from the `Invalid TCP state: 0` assertion you have probably also seen

I have not seen this assert error yet, I am using both the `dumb_http_server` and `echo_server` applications in mimxrt1050_evk and qemu_x86 boards. The http sample app feels very sluggish, but I did not notice too big difference in echo-server speed (no hard numbers here, just monitoring the echo-client output in Linux host).

**Comment by ohitz** [comment]
> > Apart from the `Invalid TCP state: 0` assertion you have probably also seen
> I have not seen this assert error yet

Some of the buildkite tests mention that error, that's why I thought you would be aware of it: https://buildkite.com/zephyr/zephyr/builds/11729

**Comment by jukkar** [comment]
> Some of the buildkite tests mention that error

Ah, those are in the unit tests, the errors might be related to the way the unit test is working. I will check that of course.

**Comment by ohitz** [comment]
> Ah, those are in the unit tests, the errors might be related to the way the unit test is working. I will check that of course.

Ok. I saw that assertion also when running our application but didn't pay too much attention. I'll recheck.

**Comment by jukkar** [comment]
> I saw that assertion also when running our application but didn't pay too much attention. I'll recheck.

I figured it out why the assert is triggered. In the test, there are two threads, `ztest_thread` is sending data and `rx_q[0]` is receiving the SYN|ACK packet. Both want to have the net_context->lock held, bug because in the unit test everything is happening lightning fast, there is a deadlock (rx thread cannot proceed because the lock is already held).
In real life this is harder to see but I suppose you caught the same issue. In the test app, there is eventually a timeout and the connection is teared down, and the test app eventually tries to access a connection which has been already cleared (thus the state is set to 0 which is invalid value).
It really looks like we need to have two locks involved after all, it is not clear to me how we could solve this with one lock.

**Comment by ohitz** [comment]
Thanks Jukka for the explanation.

I inserted a breakpoint where I get the assertion failure. Here follows the backtrace, is this the problem you suspect?

```
#0  tcp_in (conn=conn@entry=0x20245000 <_k_mem_slab_buf_tcp_conns_slab+2744>, pkt=<optimized out>, pkt@entry=0x20240a98 <_k_mem_slab_buf_rx_pkts+144>)
    at zephyr/subsys/net/ip/tcp2.c:1484
#1  0x600a165c in tcp_recv (net_conn=<optimized out>, pkt=0x20240a98 <_k_mem_slab_buf_rx_pkts+144>, ip=<optimized out>, proto=<optimized out>, 
    user_data=0x20220714 <contexts+608>) at zephyr/subsys/net/ip/tcp2.c:1110
#2  0x600a097a in net_conn_input (pkt=pkt@entry=0x20240a98 <_k_mem_slab_buf_rx_pkts+144>, ip_hdr=ip_hdr@entry=0x20234830 <rx_stack+3968>, proto=<optimized out>, 
    proto_hdr=proto_hdr@entry=0x2023482c <rx_stack+3964>) at zephyr/subsys/net/ip/connection.c:738
#3  0x600b8a30 in net_ipv4_input (pkt=pkt@entry=0x20240a98 <_k_mem_slab_buf_rx_pkts+144>) at zephyr/subsys/net/ip/ipv4.c:325
#4  0x600b73f4 in process_data (is_loopback=<optimized out>, pkt=0x20240a98 <_k_mem_slab_buf_rx_pkts+144>)
    at zephyr/subsys/net/ip/net_core.c:118
#5  processing_data (pkt=0x20240a98 <_k_mem_slab_buf_rx_pkts+144>, is_loopback=<optimized out>) at zephyr/subsys/net/ip/net_core.c:132
#6  0x60094c82 in z_work_q_main (work_q_ptr=0x2021dc78 <rx_classes>, p2=<optimized out>, p3=<optimized out>) at zephyr/lib/os/work_q.c:33
#7  0x600b418c in z_thread_entry (entry=0x60094c1d <z_work_q_main>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>)
    at zephyr/lib/os/thread_entry.c:29
```

I tried to get the error with one of the sample programs, but I failed.

**Comment by jukkar** [comment]
> Here follows the backtrace, is this the problem you suspect?

Yes, that is probably the same issue. The assert happened in 1484 line in unit test too. From the backtrace it is not possible to see the actual root cause for this issue.

**Comment by ohitz** [comment]
Ok thanks Jukka! I'll then try to report other deadlocks I can find. From my point of view the stack has already become much more stable in the last two weeks.

**Pull request closed without merging**
