### PR TITLE
RFC: shell: Refactor shell input registration

### PR DESCRIPTION
**Pull request by finikorg**
Refactor input registration for shell. This removes ugly ifdefs and
makes it possible to use API from the sample.

Signed-off-by: Andrei Emeltchenko <andrei.emeltchenko@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
#8269 is doing the same, @pfalcon

**Comment by finikorg** [comment]
@nashif @pfalcon PR #8269 does not look good enough to me. I want to make webusb shell so I would like to use API from the sample. I think it is also possible that some of CONFIG_*_CONSOLE are defined together, then it is unpredictable behaviour, depending on the order.

**Comment by pfalcon** [comment]
> I think it is also possible that some of CONFIG_*_CONSOLE are defined together, then it is unpredictable behaviour, depending on the order.

Do we have a ticket on this? It's the first time I hear that there's unpredictable behavior there. We probably need more info.

**Review by pfalcon — CHANGES_REQUESTED** [review]
Commit message doesn't correspond to the changes made by this patch. It's not just "Refactor shell input registration", it specifically switches from supporting multiple console input sources to supporting just a single input source - without mentioning that and giving the reason.

Also, I'm not sure that the specific pattern used - having different source files define the same symbol - is a good one. It for example precludes making a build test for all console types - instead multiple tests for each console types has to be defined. (Not too big inconvenience if done for good reason, but no reasons are given, while an assumption would be that if it was done like it is now, then there were reasons for that.)

**Comment by pfalcon** [comment]
Also from commit message:

> makes it possible to use API from the sample

What "sample" is meant there?

**Comment by finikorg** [comment]
@pfalcon If you check sources for input registration you notice that it cannot support multiple input sources. Typical code is:
```
void uart_register_input(struct k_fifo *avail, struct k_fifo *lines,
			 u8_t (*completion)(char *str, u8_t len))
{
	avail_queue = avail;
	lines_queue = lines;
```
This is actually a bug and it should be noticed by using the same symbol. About build tests: this is the case when they fail to catch a bug. They should notice that this combination is wrong.

**Comment by finikorg** [comment]
@pfalcon OK, I see that it is possible to use input multiple source and my solution allow only one. About sample: I want to add another shell input source. At the moment I need to include it to the stack and use defines.

**Comment by pfalcon** [comment]
> OK, I see that it is possible to use input multiple source and my solution allow only one.

Yes, and I don't see immediate problems with multiple sources working: a source would get a buffer from "avail" fifo, fill it in, and when a line is complete, puts in "ready" fifo. I don't remember if I tried multiple source myself, but again, from just reviewing the code, I don't see why it wouldn't work, and I guess other folks like @jukkar tried it.

> About sample: I want to add another shell input source. At the moment I need to include it to the stack and use defines.

That's exactly what https://github.com/zephyrproject-rtos/zephyr/pull/8269 is doing: it abstracts a way to register this fifo-based line input from individual drivers to the console subsystem. You'd need to just call console_register_line_input(), and it will take care of registering that with particular drivers, based on Kconfig settings. That's the pattern we follow in the rest of Zephyr: we don't call directly into drivers, but instead have a "subsystem layer", often a very simple shim. That was missed for console, and #8269 seeks to address that. So I hope, it can work for you.

**Comment by finikorg** [comment]
@pfalcon Actually you still have the same code which register _everything_ like it was before
```
/* Register serial console handler */
+#ifdef CONFIG_UART_CONSOLE
+	uart_register_input(avail_queue, out_queue, completion);
+#endif
+#ifdef CONFIG_TELNET_CONSOLE
+	telnet_register_input(avail_queue, out_queue, completion);
+#endif
+#ifdef CONFIG_NATIVE_POSIX_STDIN_CONSOLE
+	native_stdin_register_input(avail_queue, out_queue, completion);
+#endif
+#ifdef CONFIG_WEBSOCKET_CONSOLE
+	ws_register_input(avail_queue, out_queue, completion);
+#endif
```
I want to register my own input from the sample, it means I have to hardcode this input to this super registrator.

**Comment by pfalcon** [comment]
> I want to register my own input from the sample, it means I have to hardcode this input to this super registrator.

Ok, so do you say that you want not just use console services, i.e. receive input, but *produce* console input? But the console input is produced by a *console driver* (UARt driver, telnet driver, etc.). So, I'm not sure how you'd go about doing that "from a sample", it roughly would be the same as if you'd want to add a sensor from a sample. I'm not sure if that's possible. You'd need to have a separate driver, and separate sample for it. This driver vs app separation gets even more important with kernel/userspace separation - I'm not too fancy of it myself, but @andrewboie does a lot of work on it, and everything in Zephyr should now work/be designed with that split in mind.

So all in all, making all drivers implement the same function name for this operation, and relying on being able to override it in application source code looks like hack done just for this adhoc purpose. If there's a need to register a "custom" input registration routine, I'd suggest to add a call like set_custom_register_input_func(), and set a func pointer to call in console_register_line_input() in addition to defined driver function. But as far as I can tell, that's not compatible with kernel/userspace split, because drivers and console live in kernel space and can't rely on calling back into the userspace code.

**Comment by finikorg** [comment]
@pfalcon Please look at #8490

**Comment by pizi-nordic** [comment]
CC: @nordic-krch

**Comment by nordic-krch** [comment]
Dedicated memory section could be used for registering a console. That would remove this fixed connection between shell and consoles. Such memory section would be in flash and would need to contain only a function pointer to the function. Shell exposes a macro e.g. SHELL_CONSOLE_REGISTER(_func) which creates entry in the memory section. Shell on init iterates and registers all consoles.
The same case is in logging subsystem which supports multiple backends and this scheme is applied there.

**Review by pizi-nordic — CHANGES_REQUESTED** [review]
I also think that registration using dedicated section in flash will be better.

**Pull request closed without merging**
