### PR TITLE
ARM: Introduce gigadevice gd32f403

### PR DESCRIPTION
**Pull request by nandojve**
This introduce GigaDevice ARM SoC vendor. The minimal support is added just to bring up the gd32f403e_eval board.

depends on ~#38658 #38659 #38660~

### CODE REVIEW

**Comment by nandojve** [comment]
Added DNM until got all depends merged.

**Comment by nandojve** [comment]
Rebase and reorganize due to restrictions of #38659

**Review by cameled — COMMENTED** [review]
HAL location issue need to be confirm.

**Review by tejlmand — CHANGES_REQUESTED** [review]

**Review by tejlmand — APPROVED** [review]
lgtm

**Review by gmarull — APPROVED** [review]
Even though some adjustments will have to be done when new families are added, I think it's good enough to move on, so I'm ok as it is now. Thanks, @nandojve!

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
