### PR TITLE
samples: Bluetooth: mesh_demo: Increase ISR_STACK_SIZE value

### LINKED ISSUE #20414: nRF51 issues with the split link layer
**Executive summary**

The micro:bit and other nRF51-based targets have issues with the split link layer. Reverting to the legacy link layer works fine.
This is however a bug. The micro:bit and any other nRF51-based board should work with the split link layer, that is with:
```
CONFIG_BT_LL_SW_SPLIT=y
CONFIG_BT_LL_SW_LEGACY=n
```

**Describe the bug**
After compiling the Mesh_Demo sample for the BBC Micro:bit it works  but has issues:
- Intermittently reboots
- Often 'crashes' on booting
- Fatal error reports for ticker_users memory locations

Often the application will run for a few minutes after booting and then either begin rebooting or return a fatal error.

**To Reproduce**
Follow steps indicated described sample, which need to be updated to use the WEST tool.

**Expected behavior**
The sample in 1.14 ran smoothly without issue

**Impact**
Issues with the Micro:bit are always both annoyance and potential showstopper as they are used as demo/training devised by many.

**Screenshots or console output**
**FATAL ERROR**
> [0m[00:00:32.221,679] [1B][1;31m<err> os: Faulting instruction address (r15/pc): 0x20000cdc[1B][0m
> [00:00:32.221,740] [1B][1;31m<err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0[1B][0m
> [00:00:32.221,801] [1B][1;31m<err> os: Current thread: 0x20000f90 (unknown)[1B][0m
> [00:00:32.259,094] [1B][1;31m<err> os: Halting system[1B][0m
> 
image

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

INTERMITTENT REBOOT
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> 1 hops
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> 1 hops
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> 1 hops
> 1 hops
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> 1 hops
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Initializing...
> Unicast address: 0x0b0c
> Bluetooth initialized
> Mesh initialized
> Loading stored settings
> Using stored settings
> Subscribing to heartbeat messages
> [00:00:00.114,624] [1B][0m<dbg> bt_hci_core.bt_hci_cmd_send_sync: opcode 0x200a status 0x00[1B][0m
> [1B][1;31m--- 504 messages dropped ---
> [1B][0m[00:00:00.129,608] [1B][0m<dbg> bt_mesh_adv.bt_mesh_scan_cb: len 25: 182a37b1aaf678f238803f1b1911fa7~[1B][0m
> [1B][1;31m--- 13 messages dropped ---
> [1B][0m[00:00:00.129,669] [1B][0m<dbg> bt_mesh_net.bt_mesh_net_recv: rssi -58 net_if 0[1B][0m
> [00:00:00.129,821] [1B][0m<dbg> bt_ctlr_hci_driver.recv_thread: blocking[1B][0m
> [1B][1;31m--- 260 messages dropped ---
> 

**Additional context**
I have attempted to adjust the memory settings in order to oleviate issues but have not been successful.

### PR DESCRIPTION
**Pull request by cvinayak**
Split Link Layer implementation uses 80 bytes more ISR stack
in comparison to Legacy Link Layer, hence increase the
required ISR_STACK_SIZE for the BBB micro:bit mesh_demo
sample.

Fixes #20414.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@WilliamGFish FYI, fixes #20414

**Review by jhedberg — CHANGES_REQUESTED** [review]
Wouldn't it make more sense to increase the default for the SoC/board so that any app using it gets the right value? Or is there something special about this particular app that makes for a unique requirement?

**Comment by cvinayak** [comment]
> 
> 
> Wouldn't it make more sense to increase the default for the SoC/board so that any app using it gets the right value? Or is there something special about this particular app that makes for a unique requirement?

The required max ISR stack size is 424 bytes for peripheral and central, which dont use other peripherals ISRs.

The default ISR_STACK_SIZE is 2048 for the ARM arch, which was being overridden for BBC micro:bit to 640 bytes.

As ISR stack size is dependent on applications use of nested IRQ priorities and implementation inside such ISR callbacks (in mesh_demo, the button_pressed), the total stack size is best defined by samples.

**Review by jhedberg — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Review by trond-snekvik — APPROVED** [review]

**Comment by jhedberg** [comment]
I forgot to ask: is this something we'd want to backport to 2.1.1?

**Pull request merged**
