### PR TITLE
tests: Bluetooth: Update PTS ICS with new spec versions

### PR DESCRIPTION
**Pull request by Thalley**
Added support for BAP 1.0.2, CSIS 1.01, PACS 1.0.2, PBP 1.0.1 Enabled support for extended adv in the LL (mandatory requirement) Enabled support for multiple BIGs support in the LL.

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

**Review by sjanc — CHANGES_REQUESTED** [review]
there are some consistency check failures in BAP and CSIP

eg BAP 4/1 and 26/1 (and couple more) were disabled but those are mandatory 

also some erratum are enabled which are no longer valid for BAP 1.0.2 (BAP 27/4)

**Comment by Thalley** [comment]
@sjanc Not sure what do to here. cc @asbjornsabo @koffes 

My project passes all consistency checks, but if I export it and the import the export, then it fails. 
One of the consistency failures is 
image
which is 
image

But as you point out, the erratum is not applicable for 1.0.2, but 1.0 is mandatory to select and the erratum is mandatory if 1.0 is selected. 
The above table 4/1 was enabled in my project before export, but was disabled when it was imported again. 

All the consistency check failures are the same (for both CSIP and BAP):
Version 1.0 is mandatory, but they have mandatory errata that conflict with the most recent versions of the specs (1.0.2 for BAP and 1.0.1 for CSIP). 

As mentioned, I can enable the 1.0 versions and then consistency checks pass. When exporting the ICS files, they stay, but exporting the .bqw removes them. 

Creating a new draft and importing the ICS files preserves the BAP and CSIP choices (and does not have consistency checks), but removes `<Feature>CORE 12/1</Feature>` and `<Feature>CORE 2/60</Feature>` in both files. 

So the tool is not only contradicting itself, it also fails to export correct and import correctly. 

The closest to a working version is to import the ICS in this PR and then enable the 2 missing core features...

**Comment by Thalley** [comment]
I've raised https://support.bluetooth.com/hc/en-us/requests/148278 for the import/export issues

**Comment by Thalley** [comment]
Import should work OK now btw, since I manually added the features that was removed during the export

**Comment by Thalley** [comment]
@sjanc @jhedberg @carlescufi please do review as we are currently using older versions of some LE Audio specs in the automated tests

**Review by jhedberg — APPROVED** [review]

**Review by sjanc — APPROVED** [review]

**Pull request merged**
