### PR TITLE
stm32: Configure SPI using new pinctrl via DT

### PR DESCRIPTION
**Pull request by erwango**
Only draft for now, as there are some enhancements I'd like to add before getting it merged.

This is fully functional, but raises some questions that might have impact on DT pincrl API, which will be better be sorted sooner than later. Let me share my can of worms:
1. Support using regular expression in pinctrl bindings (such as "pinctrl-\d+") to avoid redundant documentation of pinctrl-0 and pinctrl-1
2. Add support for "pinctrl-names" in `st_stm32_dt.h`. To do that, I'd like to avoid complete duplication of existing macros, so ideally a way to retrieve idx of pinctrl-idx from pcintrl-name would be ideal. And that doesn't seem to be available yet.
3. Enhance spi_pin_nss management: not sure an array is strictly required as we want only a 1 pin list. One idea would be to get PINCTRL macros returning NULL when needed and use a pointer to store the pin config. 
Though, at the end we'll want PINCTRL macros to return errors when empty. So returning NULL should only be done on optional pinctrl (such as "nss", but not on "default"). 
That might be done by using pinctrl-0 as "required true" and pinctrl-1 as "required false" (Conflicts with point 1). So we'd need different macros for optional and mandatory pinctrl-

### CODE REVIEW

**Comment by gmarull** [comment]
I think that the handling of nss in a single pinctrl kind of breaks the rules of how Linux uses pinctrl entries. My understanding is that Linux uses multiple pinctrl entries to represent *states*, named by `pinctrl-names`, e.g. `default` or `sleep`. So if we want to move forward staying close to what Linux does, we should have a single pinctrl entry for SPI that contains or not the NSS signal.

Ref. https://wiki.st.com/stm32mpu/wiki/Pinctrl_overview

**Comment by erwango** [comment]
> I think that the handling of nss in a single pinctrl kind of breaks the rules of how Linux uses pinctrl entries.

Right. I hesitated between both versions, but was focused on pure dev aspects, so forgot about the API.
Will update.

**Comment by erwango** [comment]
Thoughts on `nss` pin handling:
- Having a nss pin dedicated pintcrl (such as `pinctrl-1 = <&spi1_nss_pa4>;`) is not in line with current Linux usage as it does not describe a device pinctrl state per se.
- Alternative is having different default states `default` and `default-nss` such as `pinctrl-0 = <&miso &mosi &sck>;` and `pinctrl-1 = <&miso &mosi &sck &nss>;`. Though it doesn't fit strictly with Linux neither as  `default-nss` is not part of expected states. This is not an issue for now, but might break a potential upcoming pinctrl api.
- Last solution is to fit nss configuration w/o specific pinctrl state. So `default` would be either 3 or 4 pins.
    - The only way to check the nss pin configuration for the spi driver would be to count the number of pins in the pinctrl state:
         - 3 pins > "no nss"
         - 4 pins > "nss pin configured".
    - Either a check is done to ensure this configuration is aligned with CONFIG_SPI_STM32_USE_HW_SS value. An error should be returned in case of misalignment.
    - Either `CONFIG_SPI_STM32_USE_HW_SS` is removed and driver behavior is aligned on nss configuration (ie based on number of pins in the pinctrl state). Advantage on this method is that `nss` could be used per device and is simple for user to control.

For simplicity, I would opt for this last option: Remove `CONFIG_SPI_STM32_USE_HW_SS` and adapt SPI driver based on number of PINs.

**Comment by gmarull** [comment]
>   * The only way to check the nss pin configuration for the spi driver would be to count the number of pins in the pinctrl state:
>     
>     * 3 pins > "no nss"
>     * 4 pins > "nss pin configured".
>   * Either a check is done to ensure this configuration is aligned with CONFIG_SPI_STM32_USE_HW_SS value. An error should be returned in case of misalignment.
>   * Either `CONFIG_SPI_STM32_USE_HW_SS` is removed and driver behavior is aligned on nss configuration (ie based on number of pins in the pinctrl state). Advantage on this method is that `nss` could be used per device and is simple for user to control.
> 
> For simplicity, I would opt for this last option: Remove `CONFIG_SPI_STM32_USE_HW_SS` and adapt SPI driver based on number of PINs.

If we end up following Linux approach the driver just manages states, so it would not have direct knowledge of the number of pins. In fact, the state is automatically set before driver probe (according to ST pinctrl overview), just managed manually when using PM (when resuming or suspending).

**Comment by erwango** [comment]
> If we end up following Linux approach the driver just manages states, so it would not have direct knowledge of the number of pins. In fact, the state is automatically set before driver probe (according to ST pinctrl overview), just managed manually when using PM (when resuming or suspending).

In Linux, the driver still accesses the pinctrl state, at least for "default"/"sleep" states switch. So it still has the ability to access the number of pins of a given state.

**Comment by gmarull** [comment]
> > If we end up following Linux approach the driver just manages states, so it would not have direct knowledge of the number of pins. In fact, the state is automatically set before driver probe (according to ST pinctrl overview), just managed manually when using PM (when resuming or suspending).
> 
> In Linux, the driver still accesses the pinctrl state, at least for "default"/"sleep" states switch. So it still has the ability to access the number of pins of a given state.

@erwango yes, access to available states, but `default` state could be used to either configure 3 or 4 pins. So if a driver doesn't use PM on Linux it will not call pinctrl at all, this is what I understand from docs and by looking at some drivers.

**Comment by erwango** [comment]
> @erwango yes, access to available states, but default state could be used to either configure 3 or 4 pins. So if a driver doesn't use PM on Linux it will not call pinctrl at all, this is what I understand from docs and by looking at some drivers.

The doc just provides meaningful examples, but API more open than what is documented and isn't restricted to PM use. So driver can access for specific needs.
From:  https://github.com/STMicroelectronics/linux/blob/v5.4-stm32mp/Documentation/devicetree/bindings/pinctrl/pinctrl-bindings.txt
"For a client device to operate correctly, certain pin controllers must
set up certain specific pin configurations. Some client devices need a
single static pin configuration, e.g. set up during initialization. Others
need to reconfigure pins at run-time, for example to tri-state pins when the
device is inactive. Hence, each client device can define a set of named
states. The number and names of those states is defined by the client device's
own binding."

So I don't think that we should too much stick to a pure and restricted PM usage for this API.

Anyway, I'm open to alternatives.

**Comment by gmarull** [comment]
@erwango I understand, but still, the driver deals with states, not with pinctrl configurations directly. So we could in theory have either `default` or `default-nss`, the difference is that the first would not require any driver interaction while the second would require to be manually activated using `pinctrl_select_state` (Linux terms).

Another option would be to have a `cs-gpios` dt-binding, and if NULL, assume NSS is used, otherwise use gpio-controlled CS.

**Comment by erwango** [comment]
> Another option would be to have a cs-gpios dt-binding, and if NULL, assume NSS is used, otherwise use gpio-controlled CS.

`cs-gpios` bt bindings is there already, only thing is that it is not accessed by driver, which can be done easily.
We can indeed assume `cs-gpios` and NSS pins are mutually exclusive, I'm not clear to say if !`cs-pgio` => NSS and vice versa.

Btw, I had a look to other SPI drivers and it seems some other can have multiple SS pins (spi_mcuxx_flexcomm.c for instance), but it doesn't seem their behavior is influenced. I see  no check vs potential `cs-gpios`, so I assume they rely on supposedly correct configuration.
Maybe we should just do the same: do nothing, just keep current code and assume user provides correct configuration (and warn them to do so eventually).

**Comment by erwango** [comment]
After debate it appears that best solution regardig NSS pins should be to do nothing specific in SPI driver:
-current behavior
-if we want to support linux like pinctrl API, there is not much we can do. States names are tightly controlled and counting pins is fragile

Closing and will open a new clean one

**Pull request closed without merging**
