### PR TITLE
drivers: clock_control: stm32h7: fix comment mistake 'bansk'

### PR DESCRIPTION
**Pull request by cameled**
Signed-off-by: Oliver Yang <cameledyang@pm.me>

### CODE REVIEW

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by FRASTM — APPROVED** [review]

**Comment by galak** [comment]
You need to update the commit message to follow the contribution guidelines.

**Comment by cameled** [comment]
@galak Thanks for your advice, I have change the commit message.

**Comment by cameled** [comment]
something wrong, reopen open it.

**Pull request merged**
