### PR TITLE
kernel: rework kobject metadata generation not to use gperf

### PR DESCRIPTION
**Pull request by dcpleung**
Due to the use of gperf to generate hash table for kobjects, the addresses of these kobjects cannot change during the last few phases of linking (especially between zephyr_prebuilt.elf and zephyr.elf). Because of this, the gperf generated data needs to be placed at the end of memory to avoid pushing symbols around in memory. This prevents moving these generated blocks to earlier sections, for example, pinned data section needed for demand paging.
    
This changes how the kobject list is generated. Instead of using gperf, our own script now generates C source file containing the list. Since the number of kobjects is consistent (once started building), the size of this list remains constant throughout different stages of linking, and thus no longer requires putting all related data structures at the end of RAM. Note that non-final version of the list still is needed to be linked in intermediate binaries so the addresses of the kobjects would remain constant at later linker stages.

Alternative to #33687

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@dcpleung I haven't looked at how gperf works or this PR, so feel free to disregard if I'm talking nonsense, but:

The usual way to generate a perfect hash table is a randomized algorithm, so it would make sense that it could vary in size across runs.

However, I don't see why that has to be a problem here: why can't we allocate a fixed size memory region in the linker for the table generated by gperf, and keep perfect hashing? As long as the table doesn't overflow the region, we should be fine, and anyway we can make a knob to tune the region size for that.

**Comment by dcpleung** [comment]
@mbolivar-nordic The biggest uncertainty is the size of the hash table generated by gperf. It is partially related to how many kernel objects in the build. However, gperf tends to insert empty elements in the hash table and this contributes to the issue at hand. It is impossible to know how many empty ones will get inserted. When the address of one kobj moves, the new hash table may be vastly different. One might simply reserves too much space (and thus wasting a bunch), or reserves too little so they are constantly chasing a moving goal post. Here is another solution (https://github.com/zephyrproject-rtos/zephyr/pull/33687) where the reservation of space is done automatically during build time. It's not perfect, but does keep using the hash table.

**Comment by mbolivar-nordic** [comment]
> Might need a fudging factor of 2 or more, and will need to output some messages if not enough is reserved during build.

At some point if the fudge factor is too large, then we have a problem with the tool. Why not start with 2 and see how it goes?

**Comment by mbolivar-nordic** [comment]
Another potential alternative: https://pypi.org/project/perfect-hash/

> Generate a minimal perfect hash function for a given set of keys. A given code template is filled with parameters, such that the output is code which implements the hash function. Templates can easily be constructed for any programming language. [...] a perfect hash function is called “minimal” when it maps N keys to N consecutive integers, usually in the range from 0 to N-1.

**Comment by dcpleung** [comment]
Let me spin up another draft PR for the fudge factor idea.

**Comment by dcpleung** [comment]
Updated #33687 with the idea of fudging factor.

**Comment by dcpleung** [comment]
Appreciate some reviews to get this or #33687 merged.

**Comment by dcpleung** [comment]
#33687 is merged, so closing this one.

**Pull request closed without merging**
