### PR TITLE
NPCX: Correct ESPICFG fields

### PR DESCRIPTION
**Pull request by DianaZig**
The parameters to FIELD() should be the position and size of each bit
field.  Correct the size of IOMODE and MAXFREQ.  Otherwise, the MAXFREQ
field is overwritten by the IOMODE update during espi_npcx_configure().

Signed-off-by: Diana Zigterman <dzigterman@google.com>

---
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39383)

### CODE REVIEW

**Review by MulinChao — APPROVED** [review]
Oops. Thanks for correcting these fields. We will double check all of them and make sure there are no the same issues.

**Review by WealianLiao — APPROVED** [review]

**Review by brockus-zephyr — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39383#-:-MluPAfY-rXtQRmxXApX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChiHuaL, @jackrosenthal, @keith-zephyr, @sjg20, and @yperess)

**Review by yperess — APPROVED** [review]

**Review by brockus-zephyr — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChiHuaL, @jackrosenthal, @keith-zephyr, and @sjg20)

**Comment by brockus-zephyr** [comment]
Can someone with the power to merge, please land this PR?

**Review by theotherjimmy — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]

**Pull request merged**
