### PR TITLE
xtensa: remove ELF section address rewriting

### PR DESCRIPTION
**Pull request by lyakh**
Now rimage can handle both cached and uncached addresses correctly, ELF rewriting isn't needed any more.

### CODE REVIEW

**Comment by lyakh** [comment]
As https://github.com/thesofproject/sof/pull/7226 and https://github.com/thesofproject/sof/pull/7250 prove, this PR together with one of https://github.com/thesofproject/rimage/pull/149 or https://github.com/thesofproject/rimage/pull/148 make rewriting section addresses in ELF images superfluous

**Comment by softwarecki** [comment]
Why can't we implement this with linker scripts, but we need to perform additional address manipulation on the linked binary?

**Review by kv2019i — COMMENTED** [review]
The "now rimage" part in commit message would really benefit from some pointer to the rimage change that is needed. Otherwise looks good.

@nashif Can we somehow ensure the rimage usd in twister is upgraded first, or do we need to keep backwards-compatibility with older rimage binaries? I guess at least twister is using rimage built outside.

**Comment by lyakh** [comment]
> Why can't we implement this with linker scripts, but we need to perform additional address manipulation on the linked binary?

@softwarecki we aren't adding address manipulations, we're removing them. If we could get rid of rimage and do everything it does today with linker scripts, that would be great. Otherwise we're still using our two steps: linker + rimage. The difference is that with XTOS we linked everything to cached addresses and then converted those, that we wanted to have uncached at run-time. Now we use the linker to place whole sections at cached or uncached addresses, so rimage now has to take that into account too.

**Comment by softwarecki** [comment]
Sorry, my previous comment was partly due to a misunderstanding of the issue. I thought we were modifying the addresses to affect the process of code loading/execution. I read the description in the fix_elf_addrs.py file. Do I understand correctly that this is just a workaround for some rimage limitations? If so, I agree that we should remove this script and improve rimage. It seems to me that we should teach rimage to fully handle noncachable addresses.

**Review by andyross — APPROVED** [review]

**Review by softwarecki — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
