### PR TITLE
manifest: update hal_nxp

### PR DESCRIPTION
**Pull request by dleach02**
HAL update removes unneeded files to reduce the size of the NXP HAL.

### CODE REVIEW

**Comment by dleach02** [comment]
Internal build test across all NXP platforms passed

**Review by danieldegrasse — DISMISSED** [review]

**Comment by hakehuang** [comment]
> Internal build test across all NXP platforms passed

run testing is PASS for all boards below.

```
    ["-p", "frdm_kw41z"],
    ["-p", "frdm_kl25z"],
    ["-p", "frdm_k64f"],
    ["-p", "frdm_k82f"],
    ["-p", "mimxrt1024_evk"],
    ["-p", "mimxrt1010_evk"],
    ["-p", "mimxrt1015_evk"],
    ["-p", "mimxrt1020_evk"],
    ["-p", "mimxrt1050_evk"],
    ["-p", "mimxrt1060_evk"],
    ["-p", "twr_ke18f"],
    ["-p", "twr_kv58f220m"],
    ["-p", "lpcxpresso55s28"],
    ["-p", "mimxrt595_evk_cm33"]
```

**Review by hakehuang — DISMISSED** [review]

**Comment by mmahadevan108** [comment]
Kindly update `west.yml`

**Comment by dleach02** [comment]
> Kindly update `west.yml`

Manifest updated

**Review by mmahadevan108 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
