### PR TITLE
Change default testing board from native_posix to native_sim, switch integration platform to native_sim, and a few minors

### PR DESCRIPTION
**Pull request by aescolar**
* Change default testing board from native_posix to native_sim
* Change the approx. 100 tests which still set integration_platform to native_posix(_64) to native_sim(_64)
* Changed CI workflows (codecov and clang) to use native_sim instead of native_posix)
* And a few other related minors:
  * A few minor comments fixes where native_posix is replaced with native_sim, or the posix architecture where applicable.
  * tests/drivers/flash_simulator: Switch the native overlays to be based on the native_sim one
  * twister tests: Replace native_posix with native_sim for its test data
  * tests/drivers/charger/sbs_charger: Fix test filter
  * tests/lib/c_lib/common: Do not skip part of test for all posix boards
  * tests/subsys/bindesc/definition: Enable for native_sim
  * tests/kernel/common: Enable errno test on native_sim
  * tests/kernel/sched/schedule_api: Replace delay with Z_SPIN_DELAY()

After this, native_sim is the default test platform where native_posix was, following the agreed strategy described in https://github.com/zephyrproject-rtos/zephyr/issues/58305

----

Background: during this release native_sim is replacing native_posix as the main host test/development platform.

### CODE REVIEW

**Comment by nashif** [comment]
we need to also change `.github/workflows/codecov.yaml` to point to native_sim

**Comment by aescolar** [comment]
> we need to also change `.github/workflows/codecov.yaml` to point to native_sim

Changed

**Review by PerMac — DISMISSED** [review]

**Review by gopiotr — DISMISSED** [review]

**Comment by nashif** [comment]
need a rebase

**Review by fabiobaltieri — DISMISSED** [review]

**Review by PerMac — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
LGTM

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
