### PR TITLE
Bluetooth: controller: Add missing BT_DEBUG_ENABLED define

### PR DESCRIPTION
**Pull request by cvinayak**
Add missing BT_DEBUG_ENABLED definitions.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by George-Stefan** [comment]
Shouldn't the Vega LLL be updated as well?

**Comment by alexandru-porosanu-nxp** [comment]
@cvinayak , @carlescufi , I'm thinking that when a change in the "common" part of the SW LL is being changed, this should be propagated to all the SW LLs. In this case I'm thinking of the VEGA one. Otherwise, if the changes are split in multiple PRs over the LLs, they might become unsynchronized. Let me know your thoughts on this.

**Review by carlescufi — APPROVED** [review]

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Comment by cvinayak** [comment]
> Shouldn't the Vega LLL be updated as well?

Yes, will follow up. Is the tests/bluetooth builds covered for VEGA board under CI? This will help build regressions if any. And as I dont have ways to do runtime tests on VEGA board, someone else needs to test and approve changes impacting VEGA boards.

**Comment by alexandru-porosanu-nxp** [comment]
> > Shouldn't the Vega LLL be updated as well?
> 
> Yes, will follow up. Is the tests/bluetooth builds covered for VEGA board under CI? This will help build regressions if any. And as I dont have ways to do runtime tests on VEGA board, someone else needs to test and approve changes impacting VEGA boards.

We can run a smoke test on the VEGA board. Actually, we do have a sort of daily-regression testing here on VEGA, based on sanitycheck. Currently it's pretty basic, but it ensures that the basic functionalities should work

**Review by alexandru-porosanu-nxp — APPROVED** [review]

**Pull request merged**
