### PR TITLE
doc: bluetooth: List BLE controller HW requirements

### PR DESCRIPTION
**Pull request by spbnick**
Add a list of hardware/peripheral requirements of the BLE controller,
as provided by Vinayak Kariappa Chettimada on Discord #nordic.

Throw in a few more doc/comment tweaks.

@carlescufi, @cvinayak, please comment with, or push your amendments.

### CODE REVIEW

**Review by cvinayak — CHANGES_REQUESTED** [review]
> Add a list of hardware/peripheral requirements of the BLE controller,
as provided by Vinayak Kariappa Chettimada on Discord #nordic.

Do not need my name in the commit message, instead add in signed-off-by

**Comment by spbnick** [comment]
I think I applied all suggestions, except the one renaming "timer" to "packet timer", as per the inline comment. @cvinayak, please object if you feel it's needed after all.

I also expanded some more abbreviations, following what @cvinayak started, fixed formatting, a few cases of missing hyphens and commas, and replaced "Lower Linker Layer" with "Lower Link Layer".

Please take a look and suggest further amendments, if necessary!

**Review by cvinayak — COMMENTED** [review]
LGTM.

Future improvement would  be to add a 2D table of hardware required vs hardware instances used in specific SoCs, information in the table cell as to whether bare-metal use or shared via Zephyr driver model etc. For example, Clock is used via zephyr driver model, RTC is accessed bare-metal, PPI used in nRF52 Series, DPPI used in nRF53 Series, etc...

**Comment by spbnick** [comment]
Thanks a lot, @cvinayak! Indeed those improvements would be very useful.

Removing draft status, ready for review now!

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Review by cvinayak — APPROVED** [review]

**Comment by spbnick** [comment]
@carlescufi, could you maybe provide the required review, or ping someone who can? Thank you.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
This looks great, thank you @spbnick!

**Pull request merged**
