### PR TITLE
net: http: HTTP library bugfixes

### PR DESCRIPTION
**Pull request by mike-scott**
This patch series cleans up several issues w/ the new API (some of which were fixed in the previous API but not carried forward):
- When HTTP server responds to PUT/POST requests with no body (IE: status code in headers only) the request will timeout
- The "timeout" parameter in http_client_send_req() was being used for TCP connection.  In some cases users call this with K_NO_WAIT so that it was immediately returning an -ETIMEDOUT error.  Previous API used a different value to avoid that behavior.
- Patch 9489fa54cc3c0225b094886a1a04e02508d56704 ("net: http: Fix http_prepare_and_send") added incorrect http_send_flush() logic so that every incoming data will be flushed.
- When using http_client_send_get_req() an additional CRLF would be added to the protocol header letting servers think that the headers ended there.

### CODE REVIEW

**Comment by mike-scott** [comment]
When testing these patches, I also included https://github.com/zephyrproject-rtos/zephyr/pull/6167

**Comment by mike-scott** [comment]
To be clear: PR https://github.com/zephyrproject-rtos/zephyr/pull/6167 is required along with these changes to fix up our HTTP-based sample.

**Comment by mike-scott** [comment]
Fixed checkpatch error

**Review by jukkar — DISMISSED** [review]
Thanks Mike, LGTM.

**Comment by mike-scott** [comment]
retest

**Comment by mike-scott** [comment]
recheck

**Comment by pfalcon** [comment]
Commit message of "net: http: client: handle empty body for PUT/POST request response"

> ... fixed handling of HTTP responses without body tags.

I guess word "tags" is stray here (there're no "tags" in HTTP, only in HTML).

**Comment by pfalcon** [comment]
> net: http: client: dont use request timeout for connecting 

We have AI now, the build fails, asking for details ;-) (in the commit message).

**Comment by mike-scott** [comment]
Heh, fixing patch descriptions.

**Comment by mike-scott** [comment]
@pfalcon please re-review patch descriptions.  I clarified the silly debug patch w/o a description.  It was previously applied but was lost during API removal.  And, I replaced "tags" with "content" in the referenced patch.  No code was changed.

**Comment by pfalcon** [comment]
This patchset looks good for me otherwise.

One note however is that I wonder if http_send_chunk() should call http_send_flush() in the end. @mike-scott, you can see for yourself if you're aware otherwise that any call (accept that high-level http_request()) may actually not send any data to peer until http_send_flush() is called.

**Review by pfalcon — DISMISSED** [review]
Thanks!

**Comment by pfalcon** [comment]
> One note however is that I wonder if http_send_chunk() should call http_send_flush() in the end. @mike-scott, you can see for yourself if you're aware otherwise that any call (accept that high-level http_request()) may actually not send any data to peer until http_send_flush() is called.

So, this is definitely shouldn't be part of this patch. And we either need to make http_send_chunk() call http_send_flush() (which might be ok for chunked transfer encoding, and much less ok for non-chunked T-E), or explicitly document that any "send" func may buffer data until http_send_chunk() is called (which is more "verbose", but flexible and efficient solution).

**Comment by mike-scott** [comment]
> So, this is definitely shouldn't be part of this patch. And we either need to make http_send_chunk() call http_send_flush() (which might be ok for chunked transfer encoding, and much less ok for non-chunked T-E), or explicitly document that any "send" func may buffer data until http_send_chunk() is called (which is more "verbose", but flexible and efficient solution).

I actually *DO* think this belongs here.  I wasn't looking to debate a longer term fix.  We have a window for that which is now closed.  Zephyr is in "bugfix" only mode for the upcoming v1.11 release (rc1 has already been cut).  I'm merely fixing the existing logic.

If @jukkar wants, I can take a look at the logic in http_send_chunk() and propose a larger patch, but something tells me this is probably the right fix for now.

**Comment by mike-scott** [comment]
Ugh.. this was lost too during HTTP API remove patch: https://github.com/zephyrproject-rtos/zephyr/commit/e04a5412a12f6b18b8f142aa488f75f1f81aa93f

**Comment by mike-scott** [comment]
@jukkar @pfalcon the reason some of these patches were lost was that @rveerama1 staged the API removal Nov 9th. and it was never updated when it was merged Jan 29th. :/

Should I add back https://github.com/zephyrproject-rtos/zephyr/commit/e04a5412a12f6b18b8f142aa488f75f1f81aa93f as well?

**Comment by mike-scott** [comment]
Added back the other missing commit.  @pfalcon @jukkar please review again as adding this patch didn't automatically remove you previous approvals. :/

**Comment by pfalcon** [comment]
> Added back the other missing commit.

Yeah, that does complicate this PR ;-). So, why did you remove http_send_chunk() and not setting Content-Length?

As I probably already mentioned, I think that HTTP client should support all valid combinations of: HTTP 1.0, Connection: close, Content-Length, Transfer-Encoding: chunked. Of course, there's no talking on implementing that here/now (it's unclear how to do that at all, given that there's seemingly an agreement to move to sockets). Instead, we just talk of "make it work [better]" workarounds for 1.11.

**Comment by pfalcon** [comment]
> So, why did you remove http_send_chunk() and not setting Content-Length?

Ok, answering myself: because you do it in the `if (req->payload && req->payload_size)` branch. Logically, if we have payload size specified for a request (which would mean entire request), then we can use Content-Length, and don't need to send it TE-chunked. Otherwise, a client may set req->payload=NULL and call http_send_chunk() to write request body incrementally.

**Comment by pfalcon** [comment]
Ceveats are in details as usual. For example, what if a client wants to issue an empty body? Seems to be pretty legitimate, but a quick google-up shows that it's a known contention point. We have that too, so I think we should change that if to `if (req->payload) {` with this patch too. Let me suggest that before approving it.

**Comment by mike-scott** [comment]
> Ceveats are in details as usual. For example, what if a client wants to issue an empty body? Seems to be pretty legitimate, but a quick google-up shows that it's a known contention point. We have that too, so I think we should change that if to if (req->payload) { with this patch too. Let me suggest that before approving it.

To summarize:
- change "if" block to only check for a valid req->payload (dropping req->payload_size)
- Only add "Content-length" header if user specifies req->payload_size

Does that sound right?

**Comment by mike-scott** [comment]
> Ceveats are in details as usual. For example, what if a client wants to issue an empty body? Seems to be pretty legitimate, but a quick google-up shows that it's a known contention point. We have that too, so I think we should change that if to if (req->payload) { with this patch too. Let me suggest that before approving it.

To summarize:
- change "if" block to only check for a valid req->payload (dropping req->payload_size)
- Only add "Content-length" header if user specifies req->payload_size

Does that sound right?

**Comment by mike-scott** [comment]
Hm.. your recommended change would cause -EINVAL return when calling http_prepare_and_send() with a payload_size == 0.  I don't think we want that.

**Comment by pfalcon** [comment]
>     change "if" block to only check for a valid req->payload (dropping req->payload_size)

Yes.

>    Only add "Content-length" header if user specifies req->payload_size

Yes, including 0. User specifies req->payload_size if they specified non-NULL req->payload.

> Hm.. your recommended change would cause -EINVAL return when calling http_prepare_and_send() with a payload_size == 0. I don't think we want that.

Sure, we don't. So, we'd need to figure why it does that and deter it from doing that. If you don't think that should be done in the scope of this patch, fine. Then we'll just have a bug with handling sending of empty body - like various other HTTP have, random example: https://github.com/requests/requests/issues/4215 . Fix can fix it later too of course.

**Comment by mike-scott** [comment]
> ... Then we'll just have a bug with handling sending of empty body - like various other HTTP have ...

I would prefer a separate patch/PR to address empty body / content-length handling.  I don't want to throw xxx fix into the mix just prior to release.  Remember: this last patch was actually approved and merged, but lost during clean up of APIs: https://github.com/zephyrproject-rtos/zephyr/blob/8dd852dc924bdddfae36e021edd102614a41d0e5/subsys/net/lib/http/http_app_client.c#L124

**Review by pfalcon — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
