### PR TITLE
Select proper IPv4 address when replying to mcast ICMPv4 echo-reply

### LINKED ISSUE #16257: net: icmpv4: Zephyr sends echo reply with multicast source address
If Zephyr receives echo request with multicast destination address 224.0.0.1 it sends response with source address 224.0.0.1. In logs it prints:

```
net_icmpv4.icmpv4_handle_echo_request: (0x56630c90): Received Echo Request from 192.0.2.10 to 224.0.0.1
net_icmpv4.icmpv4_handle_echo_request: (0x56630c90): Sending Echo Reply from 224.0.0.1 to 192.0.2.10
```

In this case source address should be that of Zephyr 192.0.2.1

[echo-reply-src-multicast.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3198044/echo-reply-src-multicast.pcap.gz)

### PR DESCRIPTION
**Pull request by jukkar**
This PR takes global address selection commits from @tbursztyka #16171 PR as they are useful here.

Fixes #16257

### CODE REVIEW

**Comment by rmstoi** [comment]
Echo reply has correct source address with this PR

But, it still prints wrong log message:
`Sending Echo Reply from 224.0.0.1 to 192.0.2.10`

**Comment by jukkar** [comment]
> But, it still prints wrong log message:
> `Sending Echo Reply from 224.0.0.1 to 192.0.2.10`

Fixed the debug print.

**Comment by jukkar** [comment]
Fixed typos in commit messages

**Comment by rmstoi** [comment]
Tiny commit message typo:

net/iface: Modify function to **ge** ipv6 global address

**Review by rmstoi — APPROVED** [review]

**Comment by tbursztyka** [comment]
> This PR takes global address selection commits from @tbursztyka #16171 PR

Hum the IPv4 patch yes, but the IPv6 one?

**Comment by jukkar** [comment]
> Hum the IPv4 patch yes, but the IPv6 one?

The IPv6 one says "There is no impact as this function is not used anywhere yet." and the IPv4 one says "As for IPv6, let's create the same function on IPv4 side." --> I took both. Should not be a big issue as these were suppose to come in connection mgr patch.

**Comment by tbursztyka** [comment]
@jukka ok

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
