### PR TITLE
Add BeagleConnect Freedom

### PR DESCRIPTION
**Pull request by jadonk**
BeagleConnect is a trademark of the BeagleBoard.org Foundation. BeagleConnect Freedom is the first device to implement the BeagleConnect technology that exposes microcontroller hardware interfaces to Linux devices. BeagleConnect Freedom utilizes a Texas Instruments (TI) CC1352P microcontroller which provides an ARM Cortex-M4 CPU, 2.4GHz radio, SubGHz radio, and many other microcontroller peripherals and features.

See https://beagleconnect.org for details.

Reviews requested from @statropy @Pillar1989 @cfriedt @Yadnik1 and @vaishnav98

Previous pull-request at https://github.com/zephyrproject-rtos/zephyr/pull/36703

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]
🙌🥳

**Comment by jadonk** [comment]
> @jadonk - you may need to rebase to latest from main or `v2.7.0-rc3`. There was a problem with the 0.13.0 SDK in CI and the 0.13.1 SDK in CI works now.

Rebase applied cleanly. My full testing, however, requires a number of outstanding patches against mainline to run the Greybus stack. Let me know if you have any suggestions on testing that.

**Comment by jadonk** [comment]
@vaishnavachath @cfriedt BeagleConnect Freedom has been updated to use CC1352P7 now. Shall I wait for CC1352P7 support to be merged ahead of submitting the new PR for the device?

**Comment by vaishnavachath** [comment]
@jadonk I will try to add CC1352P7 base support over this weekend, will need corresponding hal_ti updates as well, I would recommend posting P7 updates on BeagleConnect Freedom post that.

**Comment by cfriedt** [comment]
I would be OK reviewing board + plus new SoC in the same PR. Just remember to keep separate commits for board, soc, drivers, tests, etc, which I think you've probably already done.

If you're using this PR again, just remember to rebase on latest main.

You'll need to update west.yml to point at the the hal/ti pr and we'll do this weird little dance with Zephyr CI for merging dependent PRs in different repos.

**Pull request closed without merging**
