### PR TITLE
logging: Add default log level option to log_config template

### PR DESCRIPTION
**Pull request by nordic-krch**
Template was setting INF level as a default one and it was not possible
to change that. Extended it by adding optional default-log-level variable
which can pass default log level to the template.

Additionally, added documentation in the template file.

Here is an example where logging are fixed to ERR probably because template could not be used and INF was not an option since UART is typically used for logging/console:
https://github.com/zephyrproject-rtos/zephyr/blob/0426a5a682e5c1b9620042f0410d6c7f1b10cc27/drivers/serial/uart_nrfx_uarte.c#L19
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by nordic-krch** [comment]
@ulfalizer @carlescufi do you know how to handle that documentation failure?

In general, i am trying to add optional variable to kconfig template and apply default setting if this optional variable is not created. To handle that I am creating:
```
config $(module)_LOG_LEVEL_DUMMY_$(default-log-level)
	bool
	default y
```
Since currently `default-log-level` is not created in all uses there is `CONFIG_FOO_LOG_LEVEL_DUMMY_` option created and documentation complains with:
```
Error: /home/runner/work/zephyr/zephyr/doc/_build/rst/doc/reference/kconfig/CONFIG_ADC_LOG_LEVEL_DUMMY_.rst:36: WARNING: Unknown target name: "adc_log_level_dummy"
```

**Comment by carlescufi** [comment]
> @ulfalizer @carlescufi do you know how to handle that documentation failure?

I will try to take a look at this post-2.5 and come up with a solution.

**Comment by nordic-krch** [comment]
@carlescufi found the solution. RST didn't like kconfig name that ended with `_`. Modified the template and now documentation is green.

**Pull request closed without merging**
