### PR TITLE
dts: riscv: neorv32: update DTS for newer neorv32

### PR DESCRIPTION
**Pull request by arturkow2**
This allows Zephyr to partially work on Orangecrab with Neorv32 1.9.0. It outputs hello and hangs:

```
*** Booting Zephyr OS build zephyr-v3.5.0-2018-g2a6cec0687c2 ***
```

The reason is currently unknown, it works fine, allowing for complete boot on older Zephyr (356c8cbe63ae01b3ab438382639d25bb418a0213).

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi @arturkow2, thanks for your PR.

I'm not sure I follow - the NEORV32 version that is currently targeted by the `neorv32` Zephyr platform is 1.8.6. Your PR is meant to change that, but is only limited to dts changes. What about:
* Board documentation changes,
* Board revision changes, and
* SoC version changes?

**Comment by henrikbrixandersen** [comment]
Please coordinate your efforts with author of #66722.

**Comment by MaureenHelm** [comment]
@fkokosinski can you please revisit?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
This is missing updates to documetation, Kconfig etc.

**Comment by fkokosinski** [comment]
Hi @arturkow2. Any chance of getting this updated? :)

**Comment by arturkow2** [comment]
I made some changes, updated for yet newer neorv32 version, updated docs and Kconfig though I haven't run compliance checks yet.
Additionally, I updated sysinfo and UART drivers, fixed UART RX. Still, leaving this as draft because OS still doesn't work properly - task scheduling does not work, Zephyr does not switch tasks unless explicitly yielded, that happens despite machine IRQ arriving, sometimes Zephyr just hangs.

**Comment by robhancocksed** [comment]
I have an MR here which has some core updates to Zephyr to work with NEORV32 v1.9.8: https://github.com/zephyrproject-rtos/zephyr/pull/71294 . There's some discussion ongoing about whether or how Zephyr should support different incompatible NEORV32 core revisions.

**Pull request closed without merging**
