### PR TITLE
drivers: serial: Add mmio8 driver

### PR DESCRIPTION
**Pull request by olofk**
Add a simple serial driver that only supports writing output to
a single register

Signed-off-by: Olof Kindgren <olof.kindgren@gmail.com>

### CODE REVIEW

**Comment by ioannisg** [comment]
Is there any SoC in the tree that uses this driver?

**Comment by olofk** [comment]
I have two out-of-tree SoC that uses this. I might upstream them later on, but as they are FPGA-based it might make more sense to keep them closer to the source so that the SoC/board support can change with the RTL changes.

Regardless of that, I have found it quite handy to just have a register where I can dump stdout for simulations or easy tunnel through a high-throughput protocol (e.g via ethernet, or to RAM) where I don't have to worry about backoresssure.

In the long term this driver could also potentially be extended with device tree-controlled flags/regs to add rx support and full/empty flags but I believe it's useful already as it is

**Comment by galak** [comment]
Sorry this didn't get any review, any plans to update this?

**Comment by olofk** [comment]
This is pretty outdated now and I don't have time to update it. I think we can close this and I will open a new PR at some point with a more modern implementation that has device tree entries and such.

**Pull request closed without merging**
