### PR TITLE
Fix test order of SDMMC test, and update SDHC test to new ZTEST API

### PR DESCRIPTION
**Pull request by danieldegrasse**
Fix the test order of the SDMMC test. The init test must be run first, to correctly initialize the SD card prior to attempting to use it. This is done via renaming the test. Per the documentation for ztest, this method is permitted:

> By default the tests are sorted and ran in alphanumerical order. Test cases may be dependent on this sequence.

Additionally, update the SD host controller test to use the ZTEST API

### CODE REVIEW

**Review by mmahadevan108 — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by aaronemassey** [comment]
> This is done via renaming the test. Per the documentation for ztest, this method is permitted:

The documentation about the test ordering exists for debugging purposes and general knowledge purposes. It is *not* intended to be leveraged as a way to organize tests and is not a guaranteed part of the API.

This is what the setup, before, after parts of a test suite are used for.

**Comment by henrikbrixandersen** [comment]
The need for initialization code to run only once and at the very start of the test suite is not limited to SDMMC. I have tried to illustrate the issue in #48747.

**Comment by danieldegrasse** [comment]
> The documentation about the test ordering exists for debugging purposes and general knowledge purposes. It is _not_ intended to be leveraged as a way to organize tests and is not a guaranteed part of the API.

@aaronemassey If that is the case, then the [test framework documentation](https://docs.zephyrproject.org/latest/develop/test/ztest.html?highlight=testing%20framework#shuffling-test-sequence) needs to be updated, as it currently says the following:

> By default the tests are sorted and ran in alphanumerical order. Test cases may be dependent on this sequence.

The other concern I have about moving the first test in this suite to the setup phase is that that test can fail (and in fact is the test most likely to). If that test fails, the test framework does not display the standard `PROJECT EXECUTION FAILED` banner, which will make it more difficult for tools like twister to pick up the test failure here.

**Comment by henrikbrixandersen** [comment]
> The other concern I have about moving the first test in this suite to the setup phase is that that test can fail (and in fact is the test most likely to). If that test fails, the test framework does not display the standard PROJECT EXECUTION FAILED banner, which will make it more difficult for tools like twister to pick up the test failure here.

https://github.com/zephyrproject-rtos/zephyr/pull/48768 deals with this.

**Pull request merged**
