### PR TITLE
[TOPIC-BLE-LLCP] WIP: New test concept

### PR DESCRIPTION
**Pull request by thoh-ot**
WIP: New test concept, based on PR 23093 with an extra commit

### CODE REVIEW

**Comment by cvinayak** [comment]
Rename `tx_alloc_peek` to `tx_alloc_is_available`

**Comment by cvinayak** [comment]
After LP_COMMON_STATE_WAIT_TX, there has to be a state to wait for Tx Ack, this is the state that shall be used to detect collisions (local initiated and acked, and reception of collision).

**Comment by cvinayak** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/d3cc09dec2c5717e8802b877a7640abc08b0a2ad/subsys/bluetooth/controller/ll_sw/ull_llcp.c#L1745

The check has to be with a list of received opcode's. Example, enc_req can be responded with a reject_ind.

**Comment by thoh-ot** [comment]
> Rename `tx_alloc_peek` to `tx_alloc_is_available` , similarly other `_peek` if they are not returning the buffer.
> 
> May be just use mem_tx.free as the peek. NULL or not NULL.

Renaming _peek is fine with me. Looking a .free seems a bit like a leaky abstraction but i'm fine with it for optimizing the performance.

**Comment by thoh-ot** [comment]
> After LP_COMMON_STATE_WAIT_TX, there has to be a state to wait for Tx Ack, this is the state that shall be used to detect collisions (local initiated and acked, and reception of collision).

Havn't gotten around to the collisions resolving yet, but will make a note to myself regarding this.

**Comment by thoh-ot** [comment]
> https://github.com/zephyrproject-rtos/zephyr/blob/d3cc09dec2c5717e8802b877a7640abc08b0a2ad/subsys/bluetooth/controller/ll_sw/ull_llcp.c#L1745
> 
> The check has to be with a list of received opcode's. Example, enc_req can be responded with a reject_ind.

Working on a code path that handles the LL_UNKNOW_RSP, LL_REJECT_IND and LL_REJECT_EXT_IND.

**Review by cvinayak — APPROVED** [review]

**Pull request closed without merging**
