### PR TITLE
lib/posix/fs: fix end-of-dir in readdir

### PR DESCRIPTION
**Pull request by dariis**
POSIX readdir should return NULL if end of dir is reached and
leave errno untouched.

Signed-off-by: Rico Ganahl <rico.ganahl@bytesatwork.ch>

### CODE REVIEW

**Comment by dariis** [comment]
@pfalcon @nashif Have I misunderstood something about end-of-dir?

**Comment by dariis** [comment]
@galak Just wanted to bump the PR.

**Comment by dariis** [comment]
Please check my changes, some external libs crash which check for end of dir in POSIX manner.

**Review by mbolivar-nordic — COMMENTED** [review]
@cfriedt @aescolar I know that this isn't native_posix, but this area has no active maintainer; could you take a look if you have time?

**Comment by cfriedt** [comment]
@dariis - LGTM, but could you also please provide an accompanying test in `tests/posix/fs/src/test_fs_dir.c`?

**Comment by dariis** [comment]
@cfriedt Just give me some time, I will have a look.

**Comment by cfriedt** [comment]
@dariis, I'm going to create a bug report for you, since I would also like this fix to be included in v2.7 LTS and a bug report is required for the backport. It's a relatively trivial fix, so I don't foresee any difficulty.

**Review by cfriedt — APPROVED** [review]
LGTM - Thanks @dariis

**Review by mbolivar-nordic — APPROVED** [review]

**Pull request merged**
