### PR TITLE
tests: net: sockets: Extend TLS test suite

### PR DESCRIPTION
**Pull request by rlubos**
A first batch of tests for TLS sockets, covering expected socket
behaviors:
  * Verify that blocking/non-blocking tx/rx work as expected
  * Verify that timeouts on tx/rx are calculated properly
  * Verify proper behaviors when interacting with a socket from
    different threads (close/shutodown/send).

I intend to add more test cases, covering `poll()` functionality for TLS and also others covering more TLS/DTLS-specific functionality (CID etc.), but I think this can be done in stages, no to bloat the PR.

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]
LGTM.

Just thinking aloud here, I am pondering the use of `k_sleep()` in the test cases when waiting connection to close. I noticed in TCP and UDP socket tests that the test cases wait quite long time in qemu_x86 for example. With native_sim the tests worked fast (no sleeping there) but that board does not support usermode so qemu tests are needed too.
When adding the sleeps together, the tests might wait a long time when run sequentially.
So I am wondering if it would be possible to tweak the sleeps to be `k_sem_wait()` or similar that could be made end the wait early. WDYT?

**Comment by rlubos** [comment]
@jukkar That's a good point. The sole reason that delay exists is the TCP `TCP_TIME_WAIT` state and the time TCP context spend in it when TCP connection is finished. If we skip the delay in test, we may run out of net_contexts if the tests execute quickly.

For the TLS tests, I've lowered the TIME_WAIT timeout, to keep the tests running smoother, but I started to wonder if we could simply get rid of that delay overall for tests (i. e. set the timeout value to 0). I gave it a shot, and it seems that TLS test suite "almost works", I can see that all tests but one pass, and the one that fails is just an error code mismatch when `connect()` is expected to fail. I'll dig further to see if I can find the reason of that.

**Comment by rlubos** [comment]
@jukkar Ok, I've found the culprit of the different behavior with `TCP_TIME_WAIT` delay disabled.

There is a thing in a TCP stack, that when we send a packet to our own address (loopback), the packet is not sent directly, but scheduled for transmission on the TCP workqueue:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp.c#L1301
This works fine in general, but if we set `TCP_TIME_WAIT` delay to 0, when the TCP connection teardown exchange takes place, the final ACK does not have a chance to get sent, because we enter `tcp_timewait_timeout()` handler before, which releases the TCP context on the TCP stack behalf:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp.c#L3006
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp.c#L1642

So in result, the other end retransmits the FIN|ACK packet, and gets RST reply (as the port is no longer open), which causes unexpected behavior.

So it seems that for tests we can't really set the `TCP_TIME_WAIT` delay to 0, unless we refactor the TCP stack considerably. But at least it can be reduced to the bare minimum, to reduce the impact on the test execution time.

**Review by jukkar — DISMISSED** [review]
Thanks, this looks very good now. At some point we need to tweak the UDP and TCP socket tests, they for some reason run very long time without any visible reason (in qemu_x86).

Did a small experiment with qemu_x86
* UDP test 1.3 sec which is probably ok, I remember it taking longer when testing the `recvmsg()` implementation but the running time is now ok.
* TCP test took 121 sec which seems to be excessive.

**Comment by rlubos** [comment]
Ok, found the root cause of the test failure, keeping DNM until https://github.com/zephyrproject-rtos/zephyr/pull/66391 is merged.

**Comment by rlubos** [comment]
Removed DNM, the fix has been merged.

**Comment by rlubos** [comment]
I've had to disable `vmu_rt1170` from the test suite, as the build failed due to unresolved bug, see https://github.com/zephyrproject-rtos/zephyr/issues/61246 for details (closed in favour of https://github.com/zephyrproject-rtos/zephyr/issues/61129).

**Review by jukkar — APPROVED** [review]
Looks very nice!

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
