### PR TITLE
samples: boards: Rename microbit dir to bbc_microbit

### PR DESCRIPTION
**Pull request by galak**
Have the sample directory match what we call the board name directory.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by jhedberg** [comment]
Would it make more sense to rename the board to just `microbit`? I don't think that adds any more ambiguity over `bbc_microbit`

**Comment by jhedberg** [comment]
The downside of any of this is that it renders existing documentation references stale (inside the tree we can handle, but I bet there's plenty outside of the project)

**Comment by galak** [comment]
> Would it make more sense to rename the board to just `microbit`? I don't think that adds any more ambiguity over `bbc_microbit`

I don't have any issue one way or the other, however renaming bbc_microbit to 'microbit' means touch a bunch of other places like:

```
boards/arm/bbc_microbit/Kconfig.defconfig:	default "bbc_microbit"
boards/arm/bbc_microbit/bbc_microbit.yaml:identifier: bbc_microbit
boards/arm/bbc_microbit/doc/board.rst:.. _bbc_microbit:
boards/arm/bbc_microbit/doc/board.rst:The bbc_microbit board configuration supports the following nRF51
boards/arm/bbc_microbit/doc/board.rst:   :board: bbc_microbit
doc/release-notes-1.11.rst:* :github:`3351` - Missing board documentation for arm/bbc_microbit board
doc/release-notes-1.9.rst:* :jira:`ZEP-2229` - test_time_slicing_preemptible fails on bbc_microbit and other NRF boards
samples/basic/button/README.rst:- bbc_microbit
samples/basic/servo_motor/sample.yaml:    platform_whitelist: arduino_101 quark_d2000_crb bbc_microbit
samples/bluetooth/hci_uart/CMakeLists.txt:if(BOARD STREQUAL bbc_microbit)
samples/bluetooth/hci_uart/sample.yaml:      nrf52_pca10040 bbc_microbit
samples/bluetooth/ibeacon/sample.yaml:    platform_whitelist: bbc_microbit qemu_x86
samples/bluetooth/mesh/sample.yaml:    platform_whitelist: bbc_microbit nrf51_blenano qemu_x86
samples/bluetooth/mesh_demo/sample.yaml:    platform_whitelist: bbc_microbit nrf51_blenano qemu_x86
samples/boards/bbc_microbit/display/README.rst:   :board: bbc_microbit
samples/boards/bbc_microbit/display/sample.yaml:    platform_whitelist: bbc_microbit
samples/boards/bbc_microbit/pong/README.rst:   :board: bbc_microbit
samples/boards/bbc_microbit/pong/sample.yaml:    platform_whitelist: bbc_microbit
samples/boards/bbc_microbit/sound/README.rst:   :board: bbc_microbit
samples/boards/bbc_microbit/sound/sample.yaml:    platform_whitelist: bbc_microbit
samples/drivers/led_ws2812/sample.yaml:    platform_whitelist: 96b_carbon bbc_microbit
samples/sensor/fxos8700/README.rst:present on the :ref:`frdm_kl25z`, :ref:`bbc_microbit`, and
samples/sensor/fxos8700/README.rst:   :board: bbc_microbit
samples/sensor/thermometer/README.txt:It can be built and executed on bbc_microbit as follows:
tests/bluetooth/mesh/testcase.yaml:    platform_whitelist: bbc_microbit
```

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
I would leave the name as is.

**Pull request merged**
