### PR TITLE
gpio: davinci: Add pinmuxing

### PR DESCRIPTION
**Pull request by dnltz**
This pull request adds pinmux support to the Davinci GPIO driver. Moreover, it adds the gpio0 node to the am62x_m4.dtsi and muxes the MCU LED for the phyBOARD-Lyra. There is no dedicated LED for the MCU subsystem on the AM62x SK. Therefore, I didn't add any mux options for this board.

I also changed the am62x_m4_init sys call priority to "EARLY" because the pinctrl_ti_k3 driver started with PRE_KERNEL_1 as well and it didn't mux correctly.

### CODE REVIEW

**Comment by dnltz** [comment]
@vaishnavachath can you take a look into this PR?

**Comment by vaishnavachath** [comment]
@dnltz apologies for the delay, the changes looks good, can you please confirm, if it is the MMR Unlock that is causing issues with pinmux setting or RAT Init?, trying to understand why it was not seen in previous testing, init level EARLY is being used only for very few devices, as long as there is no objection regarding usage for init level EARLY this looks okay.

**Review by vaishnavachath — APPROVED** [review]

**Comment by dnltz** [comment]
@vaishnavachath I cannot say for sure but I figured out the pinmux values got written to the register without any effect. I watched the register values in parallel from Linux and they kept the reset values. However, the LED started blinking after I set the register manually from Linux. So, I guess the MMR was still locked and it just ignored all writes.

**Comment by dnltz** [comment]
@galak are you the correct person to ping to make some progress on this PR?

**Comment by dnltz** [comment]
Hey @mnkp can you take a look?

**Comment by dnltz** [comment]
@MaureenHelm I'm not quite sure what to do but this PR is close to two months old now. I guess I need another review but no one replies here :(

**Comment by vaishnavachath** [comment]
@cfriedt , would it be possible to get another approval for this PR? this has been tested on AM62X platforms.

**Review by cfriedt — APPROVED** [review]
LGTM

**Pull request merged**
