### PR TITLE
Fix timeout for fvp_baser_aemv8r_aarch32

### PR DESCRIPTION
**Pull request by manuargue**
This is a follow-up patch to address https://github.com/zephyrproject-rtos/zephyr/pull/47579#discussion_r917705816 and https://github.com/zephyrproject-rtos/zephyr/pull/47579#discussion_r917580682.
Timeout for tests/posix/common must be still increased (was 120 sec).

### CODE REVIEW

**Comment by cfriedt** [comment]
failing tests look unrelated. @manuargue - you may need to rebase once there is a fix in

**Comment by manuargue** [comment]
> failing tests look unrelated. @manuargue - you may need to rebase once there is a fix in

tests seems to be fixed @cfriedt, I have rebased `main`. Would you mind to please have another look and approve the changes if there's no further comments? Thanks

**Review by cfriedt — APPROVED** [review]

**Comment by cfriedt** [comment]
cc @carlescufi

**Comment by manuargue** [comment]
> cc @carlescufi

Hi @carlescufi, may I have your review on this pr? Thanks

**Review by stephanosio — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
