### PR TITLE
random: Remove duplicated code

### PR DESCRIPTION
**Pull request by ceolin**
All implementations of random number generator where duplicating logic for sys_rand23_get. Since this subsystem already has a logic to generate random values of arbitrary size, we can generically implement sys_rand32_get on top of that.

### CODE REVIEW

**Review by maass-hamburg — CHANGES_REQUESTED** [review]
Looks good, but IMO the filenames should also be changed accordingly (remove the `32`)

**Comment by ceolin** [comment]
> Looks good, but IMO the filenames should also be changed accordingly (remove the `32`)

Good point. That's fair.

**Review by maass-hamburg — APPROVED** [review]
LGTM

**Review by d3zd3z — CHANGES_REQUESTED** [review]
Code looks fine. Commit text has a small typo: rand23 instead of rand32.

**Comment by ceolin** [comment]
> Code looks fine. Commit text has a small typo: rand23 instead of rand32.

fixed ! Thanks for pointing it out.

**Review by nashif — APPROVED** [review]

**Review by d3zd3z — APPROVED** [review]

**Pull request merged**
