### PR TITLE
net: lib: sockets: Fix zsock_select

### LINKED ISSUE #34563: net: lib: sockets: Unable to select() file descriptors with number >= 32
**Describe the bug**
zsock_select() cannot poll file descriptors if all the file descriptors in readfds or writefds are all greater than or equal to 32.

**To Reproduce**
1. Create 32 threads to accept 32 TCP connections, each thread handles one TCP connection. Some of the file descriptor returned by zsock_accept() are >= 32.
2. In each thread, use zsock_select() to poll read event for the file descriptor. If the file descriptor >= 32, it never becomes ready for reading even there is data received.

**Solution**
In zsock_select(), when there is no any bit set in the first 32 bits of readfds, we should still add 32 to fd_no before iterating to next bitset, so I add `fd_no += 32;`  as following (code in red color):

image

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: abb94b1198ec6ce618f61dff367275f96cad4eca

### PR DESCRIPTION
**Pull request by chyu313**
zsock_select() cannot poll file descriptor (number >= 32).

Fixes #34563

Signed-off-by: Chih Hung Yu <chyu313@gmail.com>

### CODE REVIEW

**Review by pfalcon — APPROVED** [review]
Good catch, thanks!

**Comment by pfalcon** [comment]
It would be nice to get more detailed commit message though, e.g. "When a whole word in FD_SET was skipped due to being empty, corresponding fd number was not updated, leading to wrong fd's being passed to poll()".

**Review by jukkar — APPROVED** [review]

**Comment by jukkar** [comment]
@chyu313 checkpatch reports that there is a file permission issue, could you fix it
```
ERROR:EXECUTE_PERMISSIONS: do not set execute permissions for source files
```
Also there was a comment about commit message, perhaps you can tweak the message in the same go.

**Comment by chyu313** [comment]
> @chyu313 checkpatch reports that there is a file permission issue, could you fix it
> 
> ```
> ERROR:EXECUTE_PERMISSIONS: do not set execute permissions for source files
> ```
> 
> Also there was a comment about commit message, perhaps you can tweak the message in the same go.

@pfalcon @jukkar I have tweaked the commit message and fix file permission issue.

**Comment by pfalcon** [comment]
Thanks!

**Review by pfalcon — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by jukkar** [comment]
checkpatch script complains about too long like in commit message
```
5: UC4 Line exceeds max length (73>72): "When a whole word in FD_SET was skipped due to being empty, corresponding"
```

**Comment by chyu313** [comment]
Due to incorrect rebase commit, I will close this Pull Request and open another Pull Request

**Comment by jukkar** [comment]
You could have just force push correct branch over a failed rebase commit, there is no need to create a new PR. Anyway, it is now there so lets use the new one then.

**Pull request closed without merging**
