### PR TITLE
boards: stm32l496g_disco: Fix joystick pins polarity

### PR DESCRIPTION
**Pull request by tlr-id**
While testing ZephyrRTOS with a ```STM32L496g_disco``` kit, I noticed that the ```samples/basic/button``` wasn't working, and basically anything joystick-related wasn't working (wasn't entering the callback declared).

After some research, I found that there was a problem with the GPIO pins declaration for the Joystick. They were declared by defaults as pull-up instead of pull-down.

This should fix the issue.

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by gpaquet85** [comment]
@erwango justb for my information with block: HW Test label you mean that you have to test it before ?
For your information, I also tested it and it works ;)

**Comment by ABOSTM** [comment]
Hi @gpaquet85,
In fact, we have some doubt on `GPIO_ACTIVE_LOW `  because I think gpio will be set high when joystick is pressed.
And I wanted to test on a boards.
And also I wanted to check coherence across all STM32 boards. Because I think some are really active low.
I will check that on Monday.

**Comment by gpaquet85** [comment]
Ok no problem. Thanks for the explanation ;)
Let us know if any

**Review by ABOSTM — CHANGES_REQUESTED** [review]
@tlr-id , I  confirm that for this board, joystick should be GPIO_ACTIVE_HIGH.
Can you please take it into account in this PR ?

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
