### PR TITLE
ext: hal: altera: Don't depend on NEWLIB_LIBC

### PR DESCRIPTION
**Pull request by pfalcon**
Contrary to what was written in its Kconfig, hal/altera depends not
on Newlib, but on a baseline POSIXish define like O_NONBLOCK. Minimal
libc now provides them, so there're no issues with building Altera
for either minimal on newlib libc.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by nashif** [comment]
adding empty headers is not the way to go though, there is another major bug that we need to address first with the toolchain that can help with this and other things you are doing wrt posix, file descriptors etc. see #8944

**Comment by pfalcon** [comment]
> adding empty headers is not the way to go though

I can add copyright header if you insist. But otherwise, it follows the great pattern of sys/cdefs.h: https://github.com/zephyrproject-rtos/zephyr/blob/master/lib/libc/minimal/include/sys/cdefs.h , which serves us great in its empty shape for 1.5 years.

> there is another major bug that we need to address first with the toolchain that can help with this and other things you are doing wrt posix, file descriptors etc. see #8944

Hopefully not, as definitions of compiler-bound types and functions (as present in the toolchain headers) *hopefully* don't cross their roads with POSIX stuff. And I thought I approved #8944, but see I didn't. Well, I now actually a bit more on galak's side there on possibility of header conflicts, that's what I was getting last 2-3 days. I can approve it if you need yet another voice there though ;-).

But anyway, we wouldn't be taking headers like fcntl.h and sys/stat.h from compiler (hopefully!), because those are truly libc's.

**Comment by pfalcon** [comment]
> it follows the great pattern of sys/cdefs.h: https://github.com/zephyrproject-rtos/zephyr/blob/master/lib/libc/minimal/include/sys/cdefs.h

So, switched to follow https://github.com/zephyrproject-rtos/zephyr/blob/master/lib/libc/minimal/include/time.h instead.

**Comment by nashif** [comment]
> it follows the great pattern of sys/cdefs.h: [/lib/libc/minimal/include/sys/cdefs.h@`master`](https://github.com/zephyrproject-rtos/zephyr/blob/master/lib/libc/minimal/include/sys/cdefs.h) , which serves us great in its empty shape for 1.5 years.

This file is being removed in #8944 

I am fine merging this PR now to get things aligned and not use newlib for that board, but please mark the commit adding sys/stat.h as [REVERTME]




> Hopefully not, as definitions of compiler-bound types and functions (as present in the toolchain headers) _hopefully_ don't cross their roads with POSIX stuff.

Those are not gcc header, those are headers from the libc coming with the toolchain. This is the behaviour we see with all non-zephyr SDK toolchain and that fact that we do things differently is leading to the confusion.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
looks like you missed one: 

i9:zephyr(master): git grep NEWLIB boards/
boards/nios2/altera_max10/altera_max10_defconfig:CONFIG_NEWLIB_LIBC=y

**Comment by pfalcon** [comment]
@nashif : Will fix. So far, driven by CI failures ;-)

**Pull request merged**
