### PR TITLE
Fix types in OpenAMP resource table

### PR DESCRIPTION
**Pull request by glneo**
Update the resource table struct to use fixed width types and use the `fw_resource_table` type when we can.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@carlocaione please take a look

**Review by arnopo — APPROVED** [review]
reviewed and tested on stm32mp15

**Review by iuliana-prodan — APPROVED** [review]
Tested on imx8mp_evk//adsp

**Comment by arnopo** [comment]
@carlocaione : Please, could you take a look and confirm if the updates are ok for you? Thanks in advance!

**Review by carlocaione — APPROVED** [review]

**Pull request merged**
