### PR TITLE
manifest: update mcuboot

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Synchronized up to:
https://github.com/mcu-tools/mcuboot/commit/e51218160987126058751124cdbbf0ff6949ba44

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
Can you update the changeloog?

**Comment by henrikbrixandersen** [comment]
> Can you update the changeloog?

@nvlsianpu I will. Currently looking into how https://github.com/mcu-tools/mcuboot/commit/e75e33d9817fefb8ec37b5979f93e3dd41e81b8f was tested. I cannot get MCUboot to compile with `CONFIG_LOG_MINIMAL` due to undefined references to `log_init()` and `log_process()`.

**Comment by henrikbrixandersen** [comment]
I opened a PR against upstream MCUboot for fixing compilation with `CONFIG_LOG_MINIMAL=y`: https://github.com/mcu-tools/mcuboot/pull/911

**Comment by henrikbrixandersen** [comment]
@nvlsianpu Do you mean the ChangeLog within the Zephyr release notes? If yes, I am unsure of what level of detail to document the changes pulled in by this re-synchronisation.

**Comment by nvlsianpu** [comment]
@henrikbrixandersen 


Ad note similar as I did in https://github.com/zephyrproject-rtos/zephyr/pull/29238
Only zephyr related things.
basing on your list you can add:

```
* bootloader:

  * Kconfig: allow xip-revert only for xip-mode
  * ext: tinycrypt: update ctr mode to stream
  * use minimal CBPRINTF implementation
  * configure logging to LOG_MINIMAL by default
  * boot: cleanup NXP MPU configuration before boot
  * fix nokogiri<=1.11.0.rc4 vulnerability

* imgtool:

  * Add support for setting fixed ROM address into image header
```

**Comment by henrikbrixandersen** [comment]
> Ad note similar as I did in #29238
> Only zephyr related things.
> basing on your list you can add:

@nvlsianpu Thanks! Added.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@henrikbrixandersen zephyr-rtos/mcuboot updated, you can update SHA

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen zephyr-rtos/mcuboot updated, you can update SHA

Thanks. Updated.

**Review by utzig — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@carlescufi May you merge?

**Pull request merged**
