### PR TITLE
drivers: gpio: Place API into iterable section

### PR DESCRIPTION
**Pull request by pdgendt**
Add wrapper DEVICE_API macro to all gpio_driver_api instances.

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by yishai1999** [comment]
Maybe adapt `gpio_shell.c` to use the API check instead of what it does now which is check that the `gpio-controller` property exists.

**Comment by henrikbrixandersen** [comment]
> Maybe adapt `gpio_shell.c` to use the API check instead of what it does now which is check that the `gpio-controller` property exists.

I'm a big fan of smaller, self-contained PRs. I'd suggest to leave all shell changes out of the PRs moving the API structs, and do small, incremental follow-up PRs instead.

**Comment by pdgendt** [comment]
Yes, I planned to do some follow-up PRs for that, this should be as simple as possible to review as many reviewers are pulled in.

**Review by dleach02 — APPROVED** [review]
Somehow I get to be the assignee for all these "iterable section" PRs. Do we have a place in our documentation that should be updated with this guidance?

**Comment by pdgendt** [comment]
> Somehow I get to be the assignee for all these "iterable section" PRs. Do we have a place in our documentation that should be updated with this guidance?

The [device driver model](https://docs.zephyrproject.org/latest/kernel/drivers/index.html#driver-apis) page has been updated. I don't really know why you got assigned in all of these, but NXP drivers are changed too.

**Pull request merged**
