### PR TITLE
settings: Moving initialization code to proper backend sources

### PR DESCRIPTION
**Pull request by de-nordic**
Backend initialization code has been moved from common settings_init.c
to proper backend source files. Missing static specifiers have been
added.
Minor cleanup has been done to source files: exported functions have
been moved to the end of source files and definitions of static variables,
that are used by only a single function, have been moved from global
scope into functions that use them.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Review by fnde-ot — APPROVED** [review]
LGTM, thanks a lot for the nice cleanup!

**Comment by de-nordic** [comment]
> 
> 
> LGTM, thanks a lot for the nice cleanup!

Thank you for reviewing.

**Comment by Laczen** [comment]
@de-nordic, nice cleanup. Isn't this new setup limiting on selecting the backend ? Suppose I wish to use both nvs and fcb at the same time (e.g. to do a upgrade), is this possible ? Maybe if the routines would be renamed settings_xxx_backend_init() and included in settings_xxx.h it would be possible to have a more general setup.

**Comment by de-nordic** [comment]
> 
> 
> @de-nordic, nice cleanup. Isn't this new setup limiting on selecting the backend ? Suppose I wish to use both nvs and fcb at the same time (e.g. to do a upgrade), is this possible ? Maybe if the routines would be renamed settings_xxx_backend_init() and included in settings_xxx.h it would be possible to have a more general setup.

The former code did not allow that either, because all init functions have been named the same way., but selected via preprocessor directives according to build configuration. This cleanup does not alter code functionally nor on object level, it only moves code around, look at subsys/settings/src/settings_init.c (the former version).

Settings, in theory, allow multiple data sources and one destination (as documentation states https://docs.zephyrproject.org/latest/reference/storage/settings/settings.html?highlight=settings#backends).

**Comment by Laczen** [comment]
@de-nordic, you are right, the former code also didn't allow this. I still think it would be cleaner that the backend routines would not define a init function with the same name, because it will never be possible to support this. If a different name is used it could also (in future) easily be included in the settings_store_itf.

**Comment by de-nordic** [comment]
> 
> 
> @de-nordic, you are right, the former code also didn't allow this. I still think it would be cleaner that the backend routines would not define a init function with the same name, because it will never be possible to support this. If a different name is used it could also (in future) easily be included in the settings_store_itf.

Sure. Not in this PR. This is "janitoring" job and I do not want to mix functional changes with simple cleanup as I want this PR to maintain complete code compatibility on source text level, so that with given configuration for former code, the compilation of this PR will behave (with some exceptions) exactly as in case of former code.

It does not seem that anyone uses the possibility for multiple src/dst yet, because no one bothered to fix the former code.

I do, though, consider further changes, including suggested by renaming of init functions.

**Comment by Laczen** [comment]
> > @de-nordic, you are right, the former code also didn't allow this. I still think it would be cleaner that the backend routines would not define a init function with the same name, because it will never be possible to support this. If a different name is used it could also (in future) easily be included in the settings_store_itf.
> 
> Sure. Not in this PR. This is "janitoring" job and I do not want to mix functional changes with simple cleanup as I want this PR to maintain complete code compatibility on source text level, so that with given configuration for former code, the compilation of this PR will behave (with some exceptions) exactly as in case of former code.
> 
> It does not seem that anyone uses the possibility for multiple src/dst yet, because no one bothered to fix the former code.
> 
> I do, though, consider further changes, including suggested by renaming of init functions.

I understand, I wouldn't call it "janitoring", it does more then just cleaning it moves the "furniture" in the "right room". However it does do something bad: now the mutual exclusiveness is in one file, the PR moves them in separate files. I would propose: keep the mutual exclusiveness in one file (settings_init.c) and move the "furniture" to the "correct room".

**Comment by nvlsianpu** [comment]
@Laczen "mutual exclusiveness" - Can you clarify your thought?

**Comment by nvlsianpu** [comment]
@de-nordic pleas clean the checkpatch warning

**Comment by Laczen** [comment]
> @Laczen "mutual exclusiveness" - Can you clarify your thought?

Selecting one backend excludes the others and vice versa. If you have the same (non static) routines in several files you are excluding the others if one is selected.

**Comment by nvlsianpu** [comment]
Can we just add Kconfig for not including back-end build-in initialization routines

**Comment by Laczen** [comment]
> Can we just add Kconfig for not including back-end build-in initialization routines?

This could be done but seems odd, the initialization routines will be needed anyhow.

**Comment by de-nordic** [comment]
@Laczen The cleanup is compatible with current state of Kconfig, that does NOT allow selection of multiple src/dst backends for settings. The feature you are advocating for does not seem to be used by anyone since no one bothered to fix it. Let's leave changes enabling the feature to other PR.

**Comment by fnde-ot** [comment]
@nvlsianpu @de-nordic Note that multiple src/dst using existing backends could be implemented with CONFIG_SETTINGS_CUSTOM and custom init/load/save functions that could use existing backend functions and do any fancy thing one might need (ROM storage for default settings, FCB+NVS in different Flash chips, ...).

**Comment by de-nordic** [comment]
> 
> 
> @nvlsianpu @de-nordic Note that multiple src/dst using existing backends could be implemented with CONFIG_SETTINGS_CUSTOM and custom init/load/save functions that could use existing backend functions and do any fancy thing one might need (ROM storage for default settings, FCB+NVS in different Flash chips, ...).

Yes I know, but there is no code supporting CONFIG_SETTINGS_CUSTOM out-of-the-box at this time, additionally the current Kconfig menu mutually excludes using CUSTOM with any other backend.

There are some things that need fixing.

**Comment by fnde-ot** [comment]
> Yes I know, but there is no code supporting CONFIG_SETTINGS_CUSTOM out-of-the-box at this time, additionally the current Kconfig menu mutually excludes using CUSTOM with any other backend.

Well that's exactly the point of CONFIG_SETTINGS_CUSTOM, the custom code (init, load/save) is meant to be elsewhere (out-of-tree or in the application layer). We already use for our non-standard way of loading and storing settings from different sources as we do not have Flash.

**Comment by de-nordic** [comment]
> 
> 
> > Yes I know, but there is no code supporting CONFIG_SETTINGS_CUSTOM out-of-the-box at this time, additionally the current Kconfig menu mutually excludes using CUSTOM with any other backend.
> 
> Well that's exactly the point of CONFIG_SETTINGS_CUSTOM, the custom code (init, load/save) is meant to be elsewhere (out-of-tree or in the application layer). We already use for our non-standard way of loading and storing settings from different sources as we do not have Flash.

@fnde-ot Do I break your software? I do not think that the change should affect users of custom solution. If project uses custom solution with any of existing backends, it has too modify Kconfig and probably code in settings_init.c anyway.

**Comment by de-nordic** [comment]
> 
> 
> > > Yes I know, but there is no code supporting CONFIG_SETTINGS_CUSTOM out-of-the-box at this time, additionally the current Kconfig menu mutually excludes using CUSTOM with any other backend.
> > 
> > 
> > Well that's exactly the point of CONFIG_SETTINGS_CUSTOM, the custom code (init, load/save) is meant to be elsewhere (out-of-tree or in the application layer). We already use for our non-standard way of loading and storing settings from different sources as we do not have Flash.
> 
> @fnde-ot Do I break your software? I do not think that the change should affect users of custom solution. If project uses custom solution with any of existing backends, it has too modify Kconfig and probably code in settings_init.c anyway.

@fnde-ot it is always nice to have opinion of the real live user of subsystem in review. Btw. are you sing dynamic handlers?

**Comment by fnde-ot** [comment]
> @fnde-ot Do I break your software? I do not think that the change should affect users of custom solution. If project uses custom solution with any of existing backends, it has too modify Kconfig and probably code in settings_init.c anyway.

@de-nordic Thanks for asking, but we just use SETTINGS_CUSTOM with our own code (we do not use existing backends), so your changes should not break our software.

I just meant that this custom backends could be a nice way to handle multiple src/dst if need be, potentially reusing existing backends (which would indeed require modifying Kconfig and the way we initialize, or just copying the code elsewhere).

**Comment by fnde-ot** [comment]
> @fnde-ot it is always nice to have opinion of the real live user of subsystem in review. Btw. are you sing dynamic handlers?

If you mean the settings_load_subtree_direct functionality then yes! And actually Zephyr now uses this as well to load CCC settings when a device connects (see CONFIG_BT_SETTINGS_CCC_LAZY_LOADING).

**Comment by de-nordic** [comment]
> 
> 
> > @fnde-ot it is always nice to have opinion of the real live user of subsystem in review. Btw. are you sing dynamic handlers?
> 
> If you mean the settings_load_subtree_direct functionality then yes! And actually Zephyr now uses this as well to load CCC settings when a device connects (see CONFIG_BT_SETTINGS_CCC_LAZY_LOADING).

No I mean CONFIG_SETTINGS_DYNAMIC_HANDLERS, the CONFIG_BT_... and settings_load_subtree_direct seem independent from the configuration item.

**Comment by fnde-ot** [comment]
> No I mean CONFIG_SETTINGS_DYNAMIC_HANDLERS, the CONFIG_BT_... and settings_load_subtree_direct seem independent from the configuration item.

Oh, in that case we do not use dynamic handlers, we only use the bluetooth settings which are all static AFAIK.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@carlescufi merge.

**Comment by Laczen** [comment]
@carescufi, Please do not merge. The PR distributes the same (non static) function `settings_backend_init()` over multiple files. This makes it impossible to use multiple backends at the same time (now and in future).
@de-nordic, sorry about this but I really think it is not good.

**Comment by carlescufi** [comment]
@de-nordic and @nvlsianpu please reply to @Laczen ’s objections.

**Comment by carlescufi** [comment]
@Laczen can you outline a proposal? I still think this could be done in a follow-up PR

**Comment by nvlsianpu** [comment]
@Laczen 
> This makes it impossible to use multiple backends at the same time (now and in future).

Rather it kept it as is. Currently cant compile multiple back-ends as well. Understood that it is the problem - but we wan't to improve that in one of very next patch. This patch is for cleanup only.

**Comment by de-nordic** [comment]
> 
> 
> @de-nordic and @nvlsianpu please reply to @Laczen ’s objections.

Yeah sure. It never worked as intended and my changes have neither broken nor improved anything in the matter of the voiced concern. Current Kconfig and building process does not allow this to work as expected by @Laczen. I just move things around in here not fix them.

This can be fixed with another PR and I do not want to mix goals within one PR.

I do respect @Laczen concern and reasoning, I just do not find it OK to do the changes within this PR.

**Comment by Laczen** [comment]
@nvlsianpu, @de-nordic, I am not trying to add any functionality. As I said before: just don't use the same name in the different backend files. This is my concern.

Give the `settings_backend_init` a suffix _fs, _nvs, _fcb and expose them through the header file. Define a `settings_backend_init()` in `settings_init.c` that calls the appropiate `settings_backend_init_xxx()` based on configuration.

This way there are no multiple `settings_backend_init` routines in separate files, nothing is changed in the behaviour or functionality now, but it is possible to change it in future without reverting some of the work.

**Comment by de-nordic** [comment]
> Give the `settings_backend_init` a suffix _fs, _nvs, _fcb and expose them through the header file. Define a `settings_backend_init()` in `settings_init.c` that calls the appropiate `settings_backend_init_xxx()` based on configuration.
> 

@Laczen so yes, you are requesting code that has never been there, because there has to be support added to call differently named init functions, depending on configuration. Again: something that has not been provided prior to this PR.

**Comment by Laczen** [comment]
> > Give the `settings_backend_init` a suffix _fs, _nvs, _fcb and expose them through the header file. Define a `settings_backend_init()` in `settings_init.c` that calls the appropiate `settings_backend_init_xxx()` based on configuration.
> 
> @Laczen so yes, you are requesting code that has never been there, because there has to be support added to call differently named init functions, depending on configuration. Again: something that has not been provided prior to this PR.

@de-nordic, please, I'm not asking for any support for differently called init functions, just keep `settings_backend_init()` in `settings_init.c` and let this `settings_backend_init()` call the appropiate function or keep it like before and redefine `settings_backend_init()` for every backend like it was.

**Comment by Laczen** [comment]
@nvlsianpu, @de-nordic, @carlescufi, it is bad design to define a non static function in several files. I am fine with whatever method is used to avoid this, I only proposed one solution.

**Comment by carlescufi** [comment]
> @nvlsianpu, @de-nordic, @carlescufi, it is bad design to define a non static function in several files. I am fine with whatever method is used to avoid this, I only proposed one solution.

You mean like here:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/crypto.c#L116
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/controller/crypto/crypto.c#L36

we have used this pattern before, where depending on which Kconfig options you choose one or the other implementation is picked up by the compiler and used. This is even used all over the kernel:

This is also used in the arch interface: https://github.com/zephyrproject-rtos/zephyr/blob/master/include/sys/arch_interface.h

I personally have no issue with having `settings_backend_init()` be implemented in multiple places given that we only support a single settings backend at the moment but I also do not mind implementing [your proposal](https://github.com/zephyrproject-rtos/zephyr/pull/20975#issuecomment-565018246)

Perhaps @jhedberg and @ioannisg who know the usages of this patter I have listed above, can comment.

**Comment by de-nordic** [comment]
With exception to a few lines where I have added `static` storage specifier addition of a few declarations and some lines to Kconfig,  my work mostly consists of moving existing code blocks around.

@Laczen proposal if fine but can be implemented as separate PR, together with enabling multi-backed support - which seems to be in place, but not supported by current Kconfig, etc.

We are dragging high profile community members, to this PR, to discuss what could have been resolved with other PR. I have not invented anything worth the attention, I have not broken anything, I have slightly improved code structure.

I have done changes that deem to reflect, most accurately, the state that have existed prior to my "work".

**Comment by Laczen** [comment]
@nordic-de, I also didn't like the dragging of high profile community members, especially not trying to imply that I think they have done a bad design. The situations shown are situations where it is intentionally made to be exclusive, which is not what this PR is about.

But all this discussion is not worth it, I don't care anymore. All I asked was less than 2 minutes work and since these 2 minutes seem to be to much, go ahead, and undo some of the work in the next PR.

**Comment by carlescufi** [comment]
Merging, additional changes requested by @Laczen coming up in follow-up PRs.

**Pull request merged**
