### PR TITLE
cmake: 'ninja flash' support for sam4s_xplained

### PR DESCRIPTION
**Pull request by fallrisk**
Added support for the command `ninja flash` for the Atmel SAM4S Xplained
board.

Signed-off-by: Justin Watson <jwatson5@gmail.com>

### CODE REVIEW

**Comment by MaureenHelm** [comment]
Does `ninja debug` also work with this change? I think it should.

Please also update the board doc accordingly.

**Comment by fallrisk** [comment]
You're right it does also add support for `ninja debug`. Do you want me to add a note to the commit message?

Saying, "update the board doc accordingly," do you mean remove the sections on flashing with JLinkExe and replace with just a call to `ninja flash`?

**Comment by galak** [comment]
> You're right it does also add support for ninja debug. Do you want me to add a note to the commit message?

do update the commit message.

**Comment by MaureenHelm** [comment]
> Saying, "update the board doc accordingly," do you mean remove the sections on flashing with JLinkExe and replace with just a call to ninja flash?

yes

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
