### PR TITLE
boards: mimxrt1040_evk: add boot and slot partitions

### PR DESCRIPTION
**Pull request by butok**
Add boot and slot partitions for mimxrt1040_evk.
Enable MCUBoot support for it.

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@butok Can you please share details on how this was tested.

**Comment by butok** [comment]
> @butok Can you please share details on how this was tested.

It was tested on MIMXRT1040-EVK board (public release), using the MCUBoot test application (tests/boot/test_mcuboot).

**Review by danieldegrasse — APPROVED** [review]
In order to test this PR, it must be rebased onto the latest main (so that the updates to MCUBoot module to support this board are included). With those changes, `tests/boot/test_mcuboot` functions as expected.

**Comment by hakehuang** [comment]
I rebase to the latest code at zephyr-v3.5.0-2951-g8d2749b058, however my board has not console output

I rebase to the latest code at zephyr-v3.5.0-2951-g8d2749b058, however my board has not console output

```
west build --sysbuild -b mimxrt1040_evk
west flash
```
west build --sysbuild -b mimxrt1040_evk
west flash
```

**Comment by butok** [comment]
> however my board has not console output
Try to power off/on.

**Comment by danieldegrasse** [comment]
> I rebase to the latest code at zephyr-v3.5.0-2951-g8d2749b058, however my board has not console output
> 
> I rebase to the latest code at zephyr-v3.5.0-2951-g8d2749b058, however my board has not console output
> 
> ```
> west build --sysbuild -b mimxrt1040_evk
> west flash
> ```
> 
> west build --sysbuild -b mimxrt1040_evk west flash

@hakehuang did you remove the onboard WiFi module before flashing? I have noticed that is usually required with this EVK

**Comment by hakehuang** [comment]
> It flashes & works for me with the installed M.2.

@danieldegrasse @butok , can you paste your log here? I think my board has some reworks that impacts, I need some time to work it out. but it will be not the blocker.

**Comment by danieldegrasse** [comment]
> @danieldegrasse @butok , can you paste your log here? I think my board has some reworks that impacts, I need some time to work it out. but it will be not the blocker.

```
$ west build -p always -b mimxrt1040_evk tests/boot/test_mcuboot --sysbuild
$ west flash
```

```
*** Booting Zephyr OS build zephyr-v3.5.0-3083-gce5efc670717 ***
Launching primary slot application on mimxrt1040_evk
Secondary application ready for swap, rebooting*** Booting Zephyr OS build zephyr-v3.5.0-3083-gce5efc6*
I: Starting bootloader
I: Primary image: magic=good, swap_type=0x3, copy_done=0x1, image_ok=0x1
I: Secondary image: magic=good, swap_type=0x3, copy_done=0x3, image_ok=0x1
I: Boot source: none
I: Image index: 0, Swap type: perm
I: Starting swap using move algorithm.
I: Bootloader chainload address offset: 0x10000
I: Jumping to the first image slot
*** Booting Zephyr OS build zephyr-v3.5.0-3083-gce5efc670717 ***
Swapped application booted on mimxrt1040_evk
```

**Review by hakehuang — APPROVED** [review]

**Pull request merged**
