### PR TITLE
docs: fix idle prio in cooperative mode

### PR DESCRIPTION
**Pull request by hlleng**
https://docs.zephyrproject.org/latest/kernel/services/threads/index.html#id12   in this part, it describe -1 in cooperative mode. but from the code
image

and 
```c
#define K_HIGHEST_THREAD_PRIO (-CONFIG_NUM_COOP_PRIORITIES)
#define K_LOWEST_THREAD_PRIO CONFIG_NUM_PREEMPT_PRIORITIES
#define K_IDLE_PRIO K_LOWEST_THREAD_PRIO
```
when disable `CONFIG_MULTITHREADING`, the `CONFIG_NUM_PREEMPT_PRIORITIES` is 0.

Signed-off-by: honglin leng <a909204013@gmail.com>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
Thanks!

**Comment by carlescufi** [comment]
@andyross please take a look

**Comment by lenghonglin** [comment]
image

> The idle thread always uses the lowest configured thread priority. If this makes it a cooperative thread, the idle thread repeatedly yields the CPU to allow the application's other threads to run when they need to.

Is it necessary to delete the following paragraph？(` If this makes it a cooperative thread, the idle thread repeatedly yields the CPU to allow the application's other threads to run when they need to.`)

**Review by andyross — APPROVED** [review]
This is technically correct and very reasonable.

But really this mess with the idle thread is a design bug we should fix at some point.  The root issue here is that we allow the system to have zero preemptible priorities, and when that is true the architecture layer can use that hint[1] to eliminate some code from the interrupt return path: if you know the interrupted thread cannot be preempted, then you never need to context switch at interrupt return time.

There are two big reasons this optimization isn't very valuable though: first, you still need the context switch code for cooperative switching, and almost all architectures end up sharing almost all that code with the interrupt return path anyway[2].  You don't actually save much code, and to the extent you save cycles it's only a tiny handful (just enough to do the "if the threads are different" check) and at the **wrong side of the interrupt**.  Generally you want to work top optimize interrupt **entry** latency.  Exit latencies are much less critical.

And the second reasons is that having saved that code from the interrupt exit we then need to put its logical equivalent (a cooperative context switch via thread yield) right back into the idle thread.  Because the idle thread always needs to be preemptible, by definition.  And because we're doing it there, after interrupt exit, we're actually **hurting** latencies for any thread that was woken up.

It's just a mistake.  We should ensure that there is always at least one preemptible priority for the idle thread and remove all the legacy complexity.

[1] IIRC ARM32 is the only one that actually does this.

[2] IIRC including ARM32!

**Comment by lenghonglin** [comment]
> This is technically correct and very reasonable.
> 
> But really this mess with the idle thread is a design bug we should fix at some point. The root issue here is that we allow the system to have zero preemptible priorities, and when that is true the architecture layer can use that hint[1] to eliminate some code from the interrupt return path: if you know the interrupted thread cannot be preempted, then you never need to context switch at interrupt return time.
> 
> There are two big reasons this optimization isn't very valuable though: first, you still need the context switch code for cooperative switching, and almost all architectures end up sharing almost all that code with the interrupt return path anyway[2]. You don't actually save much code, and to the extent you save cycles it's only a tiny handful (just enough to do the "if the threads are different" check) and at the **wrong side of the interrupt**. Generally you want to work top optimize interrupt **entry** latency. Exit latencies are much less critical.
> 
> And the second reasons is that having saved that code from the interrupt exit we then need to put its logical equivalent (a cooperative context switch via thread yield) right back into the idle thread. Because the idle thread always needs to be preemptible, by definition. And because we're doing it there, after interrupt exit, we're actually **hurting** latencies for any thread that was woken up.
> 
> It's just a mistake. We should ensure that there is always at least one preemptible priority for the idle thread and remove all the legacy complexity.
> 
> [1] IIRC ARM32 is the only one that actually does this.
> 
> [2] IIRC including ARM32!

So, It mean idle thread should not be cooperative thread though `CONFIG_MULTITHREADING=y`

**Pull request merged**
