### PR TITLE
Simplify building when civetweb module is present

### LINKED ISSUE #17996: BUILD_ASSERT not active in three of five shippable platforms
Lack of a terminating semicolon after a `BUILD_ASSERT()` macro in a push to #17749 was diagnosed only in two platforms; three shippable builds plus my development environment didn't see it and passed.

I'm wondering if the recent appearance of these messages, captured from an initial `west build` targeting nrf52840_pca10056, in conjunction with the description in #8160, is why three of five shippable platforms, as well as development builds with SDK 0.10.1, do not enable `BUILD_ASSERT`:

```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- The ASM compiler identification is GNU
...
-- Configuring C Compiler
-- Performing Test HAVE_C_FLAG_STD_C11
-- Performing Test HAVE_C_FLAG_STD_C11 - Failed
-- Performing Test HAVE_C_FLAG_STD_C99
-- Performing Test HAVE_C_FLAG_STD_C99 - Failed
-- Performing Test HAVE_C_FLAG_STD_C89
-- Performing Test HAVE_C_FLAG_STD_C89 - Failed
```
Claims that GCC 8.3.0 doesn't have those flags are blatantly false, and `BUILD_ASSERT` should be default-enabled everywhere it could possibly be supported.

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
It was reported that Civetweb build is too complicated when we're building unrelated apps.

It is already fixed on civetweb master, this PR only bumps the module.

This PR is possibly related to #17996

### CODE REVIEW

**Review by pabigot — APPROVED** [review]
I can't confirm that this fixes the behavior where `BUILD_ASSERT()` had no effect because I can't reproduce that locally.  I can confirm that this patch eliminates the gratuitous cmake output that suggests GCC doesn't have flags that it actually does.

**Review by galak — APPROVED** [review]

**Review by SebastianBoe — APPROVED** [review]

**Comment by ioannisg** [comment]
>This PR possibly fixes #17996

Right now, if we merge this PR, #17996 will close. If we are not sure, we should not have that text in the description

**Comment by PiotrZierhoffer** [comment]
@ioannisg you're absolutely right - I updated the description.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
While I am fine with this patch, we urgently need to document a set of rules for repos pointed to by the west.yml manifest. I think this should point to our own GitHub org, and not civetweb's. That said, this can wait since we don't have those yet.

**Pull request merged**
