### PR TITLE
- installation script updated according to previous steps

### PR DESCRIPTION
**Pull request by yerpj**

### CODE REVIEW

**Review by dbkinder — CHANGES_REQUESTED** [review]
In context, this change is fine so I'd approve.  However there are problems with the commit message that need to be addressed (signed-off-by missing, title format needs to be of the form "doc: update installation instructions", etc.)  See the shippable log for details.

**Comment by yerpj** [comment]
I'm sorry I was not aware of the commit conventions. You previously said  
> Can you fix your commit message (commit -s --amend should do the trick.)

What does `-s`mean? I did not find any help on that.

**Comment by andrewboie** [comment]
From the git commit --help:

```
       -s, --signoff
           Add Signed-off-by line by the committer at the end of the commit log message. The
           meaning of a signoff depends on the project, but it typically certifies that committer
           has the rights to submit this work under the same license and agrees to a Developer
           Certificate of Origin (see http://developercertificate.org/ for more information).
```

**Comment by dbkinder** [comment]
It may be that you also don't have git configured with the signed-off-by information (your name and email address) as well.  Check out http://docs.zephyrproject.org/contribute/contribute_guidelines.html#development-tools-and-git-setup

**Comment by yerpj** [comment]
new attempt of PR with a correct signed-off-by. New PR here https://github.com/zephyrproject-rtos/zephyr/pull/4740

**Pull request closed without merging**
