### PR TITLE
Driver: Uart: Add support of 9 bits data length for STM32

### PR DESCRIPTION
**Pull request by Benichou34**
Some STM32 MCU (F0, F1, F2, F3, F4, L0, L4) supports USART/UART with 9bits data word length.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Txs!
Though, please split your change into 2 commits. One commit should be dedicated to api, as it may impact other drivers.

**Comment by Benichou34** [comment]
Hello @erwango 
I splitted my changes into 2 commits.

**Review by erwango — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
i'm not expert in stm32 peripherals but change looks good.

**Review by galak — APPROVED** [review]

**Comment by erwango** [comment]
@galak, can we merge this one now?

**Pull request merged**
