### PR TITLE
I2c shell names

### PR DESCRIPTION
**Pull request by keith-zephyr**
Add a config option to allow users to set  friendly names for the I2C controllers used with the I2C shell command.

### CODE REVIEW

**Comment by keith-zephyr** [comment]
Test failures look to be unrelated to this change.

**Review by galak — CHANGES_REQUESTED** [review]
I'd suggest first looking at adding devicetree alias support to the shell commands.  Such that one could utilize the "alias" instead of the node name.

**Comment by keith-zephyr** [comment]
> I'd suggest first looking at adding devicetree alias support to the shell commands. Such that one could utilize the "alias" instead of the node name.

Aliases currently require the source code to know the name of the alias a build time.  This isn't my desired use case, as I want each board to define the friendly names.  

Looking at the generated devicetree, I only see a mapping from the alias to the node name and there isn't a reverse mapping to get from the node name back to the alias.  In addition, you can specify multiple aliases to the same node name, so I'm not sure how the shell command would decide which one to use.

```
soc-if {
    i2c0_0: io_i2c_ctrl0_port0 { ... };
aliases {
    my-i2c = &i2c0_0;
```
This creates the entry:
```
#define DT_N_ALIAS_my_i2c                 DT_N_S_soc_if_S_io_i2c_ctrl0_port0
```

One benefit of the approach of this PR, is avoiding the use of the `shell_device_lookup()` function, which returns a list of all enabled devices and allows the user to select a  non I2C controller and crash the system. https://github.com/zephyrproject-rtos/zephyr/issues/44789

**Comment by galak** [comment]
I'm not keen on the devicetree node addition for this purpose.  We can add the reverse lookup for the alias if needed, but aliases gives a way to name a node if you don't like the node name.  I don't like the idea of adding some name that is specific to the shell in this way.

**Comment by keith-zephyr** [comment]
I'll investigate using the aliases, or potentially another devicetree extension to specify friendly names and provide some type checking.

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Prior relevant discussion: https://github.com/zephyrproject-rtos/zephyr/pull/44790#pullrequestreview-941530568

- With the iterable section of i2c bus controllers described there, the `i2c-controllers` property is not necessary.
- The shell could build on top of that to make nicer names, like numbered controllers from 0 onwards
- The application can still override the `label` properties for the relevant nodes to make `i2c-controller-names` unnecessary too, no?

Given the above I'm not sure this is the right approach.

**Pull request closed without merging**
