### PR TITLE
nRF: change UART DT pinmux properties to tx-gpios, rx-gpios, rts-gpios, cts-gpios

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This continues work begun in #31965 by making a similar change to UART bindings.

A prototypical example is to specify TX and RX like this in an overlay:

```
   &uart0 {
         tx-gpios = <&gpio0 1 0>;
         rx-gpios = <&gpio1 4 0>;
   };
```

Instead of:

```
   &uart0 {
         tx-pin = <1>;
         rx-pin = <36>;
   };
```

The old style is still supported, but at most one property in each pair can be given. Provide error checking and understandable error messages for invalid configurations.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
Blocked on  #31965; only the final 3 commits are truly part of this PR.

**Review by dcpleung — APPROVED** [review]
UART changes look good.

**Comment by mbolivar-nordic** [comment]
I found some RST docs that still reference the old properties. I'll update those too.

**Review by joerchan — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Rebased on master now that #31965 is merged. Driver changes are ready for review.

DNM for now since it has increased the BK parallelism and I still need to update the RST files. That will require pulling some additional docs patches out of an older PR.

**Comment by carlescufi** [comment]
@mbolivar-nordic please rebase

**Comment by mbolivar-nordic** [comment]
Abandoning due to https://github.com/zephyrproject-rtos/zephyr/pull/31965#issuecomment-820421152

**Pull request closed without merging**
