### PR TITLE
Enable SMP mode on all tests, fix bugs

### PR DESCRIPTION
**Pull request by andyross**
A bunch of test work to re-enable SMP on all tests (there are two missing, which seem to be bugs in posix and cmsis_v1 -- will file bugs on those), and targetted fixes for the inevitable kernel bugs they exposed.

### CODE REVIEW

**Comment by andyross** [comment]
Addresses #14639.

Note that this is never going to pass a regular CI run given how many tests it touches.  It has to be validated manually.

Also note that the "long line" errors are entirely lines that were too long already and are single expressions that won't split.  Some tests have really long names, and all I'm doing is adding four bytes to the unit_test() macro name.

**Review by dcpleung — APPROVED** [review]

**Comment by gnuless** [comment]
> Tests are treated with a combination of
flagging specific cases as "1cpu" where we have short-running tests
that can be independently run in an otherwise SMP environment, and via
setting CONFIG_MP_NUM_CPUS=1 where that's not possible (which still
runs the full SMP kernel config, but with only one CPU available).

I'm not convinced this is not just sweeping the problem under the rug again, albeit in a subtly different and more clever fashion.  If we're testing features in an SMP environment, shouldn't we replicate an SMP environment?  Disabling all CPUs but one, or pegging all the CPUs but one, isn't really representative of normal operation.

If the problem is that the tests are written improperly (that is, assuming one CPU), then shouldn't they be rewritten?

**Comment by andyross** [comment]
> If the problem is that the tests are written improperly (that is, assuming one CPU), then shouldn't they be rewritten?

Do we have a volunteer?

To be honest, rewriting tests is itself a kind of sweeping under the rug: our promise to users is that the code continues to do what we thought it did.  Rewriting tests so that they pass is itself sort of a way to fool ourselves that we haven't broken anything.  It's absolutely routine that strange old tests break new code in unexpected ways because of edge case assumptions (c.f. some of the fixes in this very PR about where reschedule points are, which weren't ever really documented).  And that's a good thing.

**Comment by gnuless** [comment]
> To be honest, rewriting tests is itself a kind of sweeping under the rug

If I write a test that assumes that `char` is signed, and it doesn't run properly on a MIPS, then rewriting the test to remove the assumption isn't sweeping anything under the rug, nor is it breaking any promise to users.  It's simply fixing a flawed test.

**Comment by andyross** [comment]
Heh, the checkpatch errors hid a commented-out pair of test cases that never got a fix.  Fixed now.  Note that since there's concern about risk that this involves an actual detectable difference between scheduling in SMP and UP which has been addressed by relaxing the test a bit.  See comments in the third-to-last commit that was just added.  It wouldn't be impossible to unify the behavior between the two, but there would be significant complexity and some performance cost.

**Comment by gnuless** [comment]
> In effect, in UP mode "yield" and "reschedule" mean very slightly different things where in SMP they act the same.

This touches upon what I was trying to express the other day, that the SMP vs non-SMP schedulers seem rife with lots of subtle differences of this sort, both in observed behavior by clients, and inside the scheduler code.  As an RTOS, Zephyr should have rock-solid and well-defined behavior where scheduling is concerned.

**Review by ghost — APPROVED** [review]
I think we have farther to go with SMP testing but this is a step in the right direction...

**Comment by gnuless** [comment]
> We don't document either behavior, as it happens. 

> (c.f. some of the fixes in this very PR about where reschedule points are, which weren't ever really documented)

Our documentation is weak in a lot of areas, and this is obviously one of those.  "Someday" we should really nail down some critical core features, like scheduling ...

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@andyross two tests at least failing:
```
cat sanity-out/qemu_x86_64/tests/kernel/sched/schedule_api/kernel.sched.multiq/handler.log
SeaBIOS (version rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org)
Booting from ROM..Running test suite threads_scheduling
===================================================================
starting test - test_bad_priorities
PASS - test_bad_priorities
===================================================================
starting test - test_priority_cooperative
PASS - test_priority_cooperative
===================================================================
starting test - test_priority_preemptible
PASS - test_priority_preemptible
===================================================================
starting test - test_yield_cooperative
PASS - test_yield_cooperative
===================================================================
starting test - test_sleep_cooperative
PASS - test_sleep_cooperative
===================================================================
starting test - test_sleep_wakeup_preemptible
PASS - test_sleep_wakeup_preemptible
===================================================================
starting test - test_pending_thread_wakeup
PASS - test_pending_thread_wakeup
===================================================================
starting test - test_time_slicing_preemptible
PASS - test_time_slicing_preemptible
===================================================================
starting test - test_time_slicing_disable_preemptible
PASS - test_time_slicing_disable_preemptible
===================================================================
starting test - test_lock_preemptible
PASS - test_lock_preemptible
===================================================================
starting test - test_unlock_preemptible
PASS - test_unlock_preemptible
===================================================================
starting test - test_unlock_nested_sched_lock
PASS - test_unlock_nested_sched_lock
===================================================================
starting test - test_sched_is_preempt_thread
PASS - test_sched_is_preempt_thread
===================================================================
starting test - test_slice_reset
PASS - test_slice_reset
===================================================================
starting test - test_slice_scheduling
ABCDEFGHI
ABCDEFGHI
ABCD
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

E
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

F
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

G
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

H
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

I
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee



    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

A
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

B
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

C
    Assertion failed at ZEPHYR_BASE/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:63: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expee

FAIL - test_slice_scheduling
===================================================================
starting test - test_priority_scheduling
PASS - test_priority_scheduling
===================================================================
starting test - test_wakeup_expired_timer_thread
ABCDEFGHI
PASS - test_wakeup_expired_timer_thread
===================================================================
starting test - test_user_k_wakeup
PASS - test_user_k_wakeup
===================================================================
starting test - test_user_k_is_preempt
PASS - test_user_k_is_preempt
===================================================================
Test suite threads_scheduling failed.
===================================================================
PROJECT EXECUTION FAILED
```

and tests/kernel/sched/schedule_api/kernel.sched

**Comment by galak** [comment]
Want to rebase this one?

**Comment by carlescufi** [comment]
Any reason we haven't merged this?

**Pull request merged**
