### PR TITLE
drivers: pinmux: remove drivers/pinmux/pinmux.h

### PR DESCRIPTION
**Pull request by galak**
The file is only really used on STM32 SoCs so we can move the contents that are relevant into pinmux_stm32.h and remove the file.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by gmarull — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
I may have missed have missed very latest evolutions, but I still see it included in several files.
And `struct pin_config` is in use at least on stm32 targets

**Review by nashif — CHANGES_REQUESTED** [review]
git grep  "drivers/pinmux.h" | wc -l
68

**Comment by nashif** [comment]
> git grep "drivers/pinmux.h" | wc -l

ok, that is a different one... but still, there are some users.

**Comment by galak** [comment]
> ok, that is a different one... but still, there are some users.

Yeah, fixed that now.

**Review by erwango — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
