### PR TITLE
drivers: I2C: Add PEC support

### PR DESCRIPTION
**Pull request by GRobertZieba**
Certain I2C devices support packet-error checking (PEC). If a device supports PEC then a CRC8 checksum byte can be sent to/received from the device to support detection of corrupted communication. This commit adds `i2c_pec_transfer_start` and `i2c_pec_transfer_continue` primitives to support this functionality as well as test coverage for the new functionality.

Change-Id: I163f25650daefd02661e3322e7131a3ae3e88cc1

### CODE REVIEW

**Comment by teburd** [comment]
Is PEC specific to smbus? We have an smbus API for drivers in the tree if so.

**Comment by GRobertZieba** [comment]
> Is PEC specific to smbus? We have an smbus API for drivers in the tree if so.

I went back and forth on this. PEC is part of the SMBus spec, but the big issue I see is that there's nothing in the tree that uses smbus-device.yaml and only a single use of smbus-controller.yaml. But I see I2C DT bindings for devices that I know are actually SMBus devices.

Any existing code that wants to use PEC with these peripherals would need an additional SMBus driver and then do any refactoring that comes with switching the driver. This commit would give existing I2C-based code an easy way to access features like PEC. If people are interested in moving towards a more strict SMBus/I2C distinction then something like this would be a good idea anyway since it provides an easy way for existing code to transition.

I also think that any PEC implementation should provide low-level access to allow for workarounds in cases where a peripheral may have quirks in its implementation. The message based I2C API is a better match for this functionality vs the higher-level SMBus API.

**Comment by fabiobaltieri** [comment]
Wasn't SMBUS implementation supposed to be an extension of the I2C one? https://github.com/zephyrproject-rtos/zephyr/issues/37101 literally says "Add SMbus API by extending the existing I2C API." (as it is in Linux) but then https://github.com/zephyrproject-rtos/zephyr/pull/49688 looks like it's been implemented as a standalone thing. cc @finikorg

**Comment by finikorg** [comment]
I had first version as extension of I2C but then it was decided on ARCH meeting to separate SMBus API from I2C.

**Comment by fabiobaltieri** [comment]
> I had first version as extension of I2C but then it was decided on ARCH meeting to separate SMBus API from I2C.

That's unfortunate, what was the plan for using device drivers on both busses?

**Comment by henrikbrixandersen** [comment]
> I had first version as extension of I2C but then it was decided on ARCH meeting to separate SMBus API from I2C.

I still question if this was the right decision...

I wouldn't want to add SMBus-specific extensions to our I2C driver API. That would just confuse things even further.

**Comment by fabiobaltieri** [comment]
> Well, not a stock I2C controller, right? But an SMBus-capable I2C controller, for which we do not have an SMBus driver for in-tree?

Sure, then a controller could implement the extra api or not (what's special about it? thought most i2c controller could do both)

**Comment by teburd** [comment]
Shouldn't it be possible to have a smbus struct device that composes on top of an i2c peripheral driver? As in a struct device implementing the smbus API with a pointer to the i2c device and a shared data/config struct pair. An optional i2c() function for smbus could be provided even if you want to use i2c APIs without doing another DEVICE_DT_GET.

I don't think what was decided was wrong. That sort of composition should be perfectly fine.

**Comment by fabiobaltieri** [comment]
> Shouldn't it be possible to have a smbus struct device that composes on top of an i2c peripheral driver? As in a struct device implementing the smbus API with a pointer to the i2c device and a shared data/config struct pair. An optional i2c() function for smbus could be provided even if you want to use i2c APIs without doing another DEVICE_DT_GET.

An smbus controller backed by a generic i2c driver? Ok but then still, existing i2c drivers would have to be ported to work with both. Unless we also do an i2c controller backed by an smbus one. Then they can be nested indefinitely, cool. :-)

> I don't think what was decided was wrong. That sort of composition should be perfectly fine.

I think an example could help but I'm not convinced it was a good idea.

**Comment by GRobertZieba** [comment]
>Shouldn't it be possible to have a smbus struct device that composes on top of an i2c peripheral driver? As in a struct device implementing the smbus API with a pointer to the i2c device and a shared data/config struct pair. An optional i2c() function for smbus could be provided even if you want to use i2c APIs without doing another DEVICE_DT_GET.

Was the original intent behind the design to have separate I2C and SMBus controllers in the devicetree that use the same hardware bus? My concern was that I've encountered bugs that required enabling PEC for a single device on a bus. The separation in the API made me think that switching one device over would require switching everything over to SMBus, up to the MCU controllers. But if it's just moving an entry from `i2c0` to `smbus0` then I'm okay with that. I still don't like having separate drivers, but implementing a "create an SMBus driver and get an I2C one for (essentially) free" type system should be fairly straight forward. Converting this change into a device that implements SMBus on top of I2C (with software PEC checking) wouldn't be hard either.

**Comment by teburd** [comment]
> > Shouldn't it be possible to have a smbus struct device that composes on top of an i2c peripheral driver? As in a struct device implementing the smbus API with a pointer to the i2c device and a shared data/config struct pair. An optional i2c() function for smbus could be provided even if you want to use i2c APIs without doing another DEVICE_DT_GET.
> 
> Was the original intent behind the design to have separate I2C and SMBus controllers in the devicetree that use the same hardware bus? My concern was that I've encountered bugs that required enabling PEC for a single device on a bus. The separation in the API made me think that switching one device over would require switching everything over to SMBus, up to the MCU controllers. But if it's just moving an entry from `i2c0` to `smbus0` then I'm okay with that. I still don't like having separate drivers, but implementing a "create an SMBus driver and get an I2C one for (essentially) free" type system should be fairly straight forward. Converting this change into a device that implements SMBus on top of I2C (with software PEC checking) wouldn't be hard either.

The intent, from my part, was having a separation of concerns. I'm far from an smbus expert here, but to me when I look at it, it looks like a protocol and some additional requirements placed on i2c, kind of like a protocol/superset of functionality on top of an i2c signaling layer. Maybe I'm thinking about it wrong though. 

At the time of the discussion there was also an i3c driver being added which could also be viewed as a bit of a superset of i2c. So there was also that consideration as I recall.

**Comment by fabiobaltieri** [comment]
> The intent, from my part, was having a separation of concerns. I'm far from an smbus expert here, but to me when I look at it, it looks like a protocol and some additional requirements placed on i2c, kind of like a protocol/superset of functionality on top of an i2c signaling layer. Maybe I'm thinking about it wrong though.

Linux seems to be happy to emulate smbus commands using an i2c controller https://elixir.bootlin.com/linux/latest/source/drivers/i2c/i2c-core-smbus.c#L553, the whole smbus story is implemented in `i2c` (unlike i3c). Would it make sense to rethink the API implementation so we could do the same? Anything to avoid a storm of multi-bus patches.

What's in smbus that can't be implemented over i2c?

**Comment by finikorg** [comment]
> > The intent, from my part, was having a separation of concerns. I'm far from an smbus expert here, but to me when I look at it, it looks like a protocol and some additional requirements placed on i2c, kind of like a protocol/superset of functionality on top of an i2c signaling layer. Maybe I'm thinking about it wrong though.
> 
> Linux seems to be happy to emulate smbus commands using an i2c controller https://elixir.bootlin.com/linux/latest/source/drivers/i2c/i2c-core-smbus.c#L553, the whole smbus story is implemented in `i2c` (unlike i3c). Would it make sense to rethink the API implementation so we could do the same? Anything to avoid a storm of multi-bus patches.
> 
> What's in smbus that can't be implemented over i2c?

Some controllers have hardware support for SMBus commands, so we would need to emulate first I2C and then emulate from I2C SMBus.

**Comment by GRobertZieba** [comment]
Is there modern controller hardware that supports SMBus, but not generic I2C? I'm aware of some examples in the linux kernel (which treats SMBus as an extension of I2C), but they seem to be legacy devices.

I did also want to mention that AFAIK PEC is the only SMBus feature that the existing I2C sub-system doesn't cover. SMBus formalizes block read/writes which are present as the `i2c_burst_*` functions and has support for devices to initiate communication with the controller (It looks like the `i2c_target_*` functions implement this). Unless I've missed something, the main differences are in the formalization of electrical details of the bus (e.g. minimum frequency, voltages, etc).

**Comment by GRobertZieba** [comment]
Adding the architectural review label since there hasn't been any recent further discussion. The two approaches that I would advance are:

* Keep the current separation between I2C/SMBus and convert this PR into a software bridge that provides an SMBus implementation on top of I2C
* Reassess having I2C and SMBus as separate busses

**Comment by carlescufi** [comment]
Architecture WG:

- The PEC feature is included in both SMBus and the I2C standard
- @GRobertZieba mentions that PEC is the only I2C standard feature that is not supported today in Zephyr
- @henrikbrixandersen counters that PEC is actually an SMBus feature, not an I2C one
- The issue is duplication between SMBus and PEC
- @GRobertZieba suggests creating an SMBus controller on top of I2C that implements things like PEC
- @henrikbrixandersen likes the idea, suggests using the I2C/I3C model for the I2C/SMBus problem

**Pull request closed without merging**
