### PR TITLE
boards: frdm_mcxc444: Add i2c support

### PR DESCRIPTION
**Pull request by NeilChen93**
Enable i2c and configure it to read accelerometer sensor on the board. Test it using sample.sensor.accel_polling.

### CODE REVIEW

**Review by danieldegrasse — DISMISSED** [review]

**Review by dleach02 — DISMISSED** [review]

**Comment by kartben** [comment]
@NeilChen93 ping -- this too needs rebasing

**Comment by mmahadevan108** [comment]
Please add this to the release notes

**Comment by kartben** [comment]
> Please add this to the release notes

As briefly discussed in a recent release meeting, this level of detail might not be desirable and @fabiobaltieri and I are currently working on a proposal to slightly revamp release notes, and we're thinking that "board changes" like this one here possibly don't belong to the release notes. I wouldn't delay this PR since release notes can always be added later

**Comment by danieldegrasse** [comment]
@NeilChen93 thanks for rebasing- there is unfortunately another merge conflict :/, it needs another rebase

**Review by danieldegrasse — DISMISSED** [review]
One trick I use to avoid the *endless* rebase conflicts- if you sort the YAML supported list alphabetically, you won't be changing the same line in every PR. You can also just put the new definition further up in the list so it doesn't touch the same line

**Review by mmahadevan108 — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
