### PR TITLE
cmake: replace PROJECT_SOURCE_DIR with ZEPHYR_BASE (#7173)

### LINKED ISSUE #7173: Difference between the ZEPHYR_BASE and PROJECT_SOURCE_DIR CMake variables is unclear
To me anyway.

`cmake/kconfig.cmake` references `kconfig.py` via `${PROJECT_SOURCE_DIR}/scripts/kconfig/kconfig.py`, while you have e.g. `include(${ZEPHYR_BASE}/boards/common/pyocd.board.cmake)` in other places.

Looking at https://github.com/zephyrproject-rtos/zephyr/blob/master/cmake/app/boilerplate.cmake#L75, they seem to be synonyms.

@SebastianBoe  pointed out that `PROJECT_SOURCE_DIR` is a standard CMake variable, so maybe `ZEPHYR_BASE` is just a synonym for people who aren't very familiar with CMake (like me :). Would be nice to have it documented if that's it.

### PR DESCRIPTION
**Pull request by alext-mkrs**
I've simply followed @SebastianBoe's suggestion from the original issue and put the comment describing why we use `ZEPHYR_BASE` instead of `PROJECT_SOURCE_DIR` + replaced all the relevant entries.

Tested by building `hello_world` for several boards ensuring no errors.

~There's one thing that potentially needs correcting - [some of the lines](https://github.com/zephyrproject-rtos/zephyr/blob/master/CMakeLists.txt#L365-L366) had end-of-line comments, aligned with comments on other lines - and current patch breaks the alignment. That's the price of such alignment - git history pollution.~

~What would be the preferred way to deal with this (no relevant information in coding style doc):~
~1. just leave as is~
~1. correct in a separate patch~
~1. correct in the same patch with variable replacement~
~1. anything else?~ Already corrected, see discussion below.

This fixes #7173.

### CODE REVIEW

**Review by ulfalizer — APPROVED** [review]
Looks good to me. Someone more familiar with our CMake files ought to check as well though.

I prefer to preserve alignment even if makes the history a bit messier.

**Comment by alext-mkrs** [comment]
Thanks @ulfalizer. Yep, per our IRC chat I've corrected the algnment to be the same style it was before the variable update - at the cost of extra lines captured in the commit (luckily it's just one file and like 3 cases). I've also just removed a couple of files from `ext`, which slipped in + rebased on top the the master as of right now.

**Review by rgundi — APPROVED** [review]
LGTM

**Comment by alext-mkrs** [comment]
Thanks for reviews. Should I trigger checks again - as @ulfalizer noted, one of the jobs timed out?

**Comment by ulfalizer** [comment]
@alext-mkrs 
Probably fine anyway.

I think the timeout is set so that it juuust barely doesn't make it when you touch files for all boards. I've ran it into myself. ;)

**Comment by alext-mkrs** [comment]
@ulfalizer, I see - ok, let me leave it as-is then, unless someone requests a re-check - to decrease the build system load :)

**Review by SebastianBoe — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
