### PR TITLE
all: Fix "#if IS_ENABLED(CONFIG_FOO)" occurrences

### PR DESCRIPTION
**Pull request by erwango**
Clean up occurrences of "#if IS_ENABLED(CONFIG_FOO)" an replace with classical "#if defined(CONFIG_FOO)".

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by de-nordic — COMMENTED** [review]
Why?

**Comment by erwango** [comment]
> Why?

`#if IS_ENABLED` is unnecessarily complex way to perform a basic `#if defined()`

**Review by de-nordic — DISMISSED** [review]
Flash subsystem and FAT FS tests look OK.

**Review by Thalley — COMMENTED** [review]
BT Audio looks OK; if we want to enforce something like this, we need to add it in CI.

**Comment by sjanc** [comment]
> > Why?
> 
> `#if IS_ENABLED` is unnecessarily complex way to perform a basic `#if defined()`

Just my two cents:
"#if IS_ENABLED(FOO)" is useful since you can grep for IS_ENABLED(FOO) and see all occurrences of config option, both preprocessor and compiler eliminated

**Comment by Thalley** [comment]
> Just my two cents: "#if IS_ENABLED(FOO)" is useful since you can grep for IS_ENABLED(FOO) and see all occurrences of config option, both preprocessor and compiler eliminated

Yeah, if we replaced all `#if defined(CONFIG_...)` with `#if IS_ENABLED(CONFIG_...)`, otherwise you'll still have to search for both :)

**Review by rlubos — DISMISSED** [review]
Networking part LGTM

**Comment by Laczen** [comment]
Doesn't this have an influence on the generated documentation ?

**Review by stephanosio — CHANGES_REQUESTED** [review]
> Fix "#if IS_ENABLED(CONFIG_FOO)" occurrences

I would also ask the same question: why?

It is **not** incorrect to use `IS_ENABLED` alongside `#if` -- this is more or less a style issue on which we do not currently have any specific guidelines.

If we are "fixing" this, there should also be a clear guideline that states that `#if defined(CONFIG_FOO)` or `#ifdef CONFIG_FOO` must be used instead of `#if IS_ENABLED(CONFIG_FOO)`.

**Comment by erwango** [comment]
> > Fix "#if IS_ENABLED(CONFIG_FOO)" occurrences
> 
> I would also ask the same question: why?
> 
> It is **not** incorrect to use `IS_ENABLED` alongside `#if` -- this is more or less a style issue on which we do not currently have any specific guidelines.
> 
> If we are "fixing" this, there should also be a clear guideline that states that `#if defined(CONFIG_FOO)` or `#ifdef CONFIG_FOO` must be used instead of `#if IS_ENABLED(CONFIG_FOO)`.

Here is documentation abstract for `IS_ENABLED`.
```
 * That is, it works similarly to <tt>\#if defined(CONFIG_FOO)</tt>
 * except that its expansion is a C expression. Thus, much <tt>\#ifdef</tt>
 * usage can be replaced with equivalents like:
 *
 *     if (IS_ENABLED(CONFIG_FOO)) {
 *             do_something_with_foo
 *     }
 *
 * This is cleaner since the compiler can generate errors and warnings
 * for @p do_something_with_foo even when @p CONFIG_FOO is undefined.
```
I'm not sure, reading these lines, why one would chose to use `#if IS_ENABLED` instead of `#if defined`.
Note that `the compiler can generate errors and warnings` doesn't apply in this case.

But I'm fine with adding a note clarifying the intent.

**Comment by erwango** [comment]
Added a comment in `IS_ENABLED` doc, don't hesitate to suggest better wording, as I'm affraid I'm just adding more confusion to the reader.

**Review by gmarull — APPROVED** [review]
+1, no need for macro hackery when not required.

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
