### PR TITLE
boards: arm: lpcxpresso55s28_ns: Remove from CI

### PR DESCRIPTION
**Pull request by galak**
We have no means to test lpcxpresso55s28_ns in CI as there is no
    upstream TFM support for this platform.  So remove the board YAML
    file so we don't attempt to build it in CI.
    
    Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by microbuilder — APPROVED** [review]

**Review by chrta — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by ioannisg — CHANGES_REQUESTED** [review]
Fine with the change, but i think the argumentation (in the commit message) is wrong, really.
We _could_ have the secure component build in out-of-tree repos. So in Zephyr one could only care to have the non-secure FW support for the board. And the Secure FW does not need to be TFM.

This is what we do in Nordic, where we do not have our secure FW code-based in the upstream project (note, TFM is not Nordic's default Secure FW solution). So we use Zephyr for the _NS targets which are present in upstream.

So, OK to remove the NS if the platform maintainers agree, but the reasoning should just be "not interested"

What we really need is not to run CI in upstream, if upstream does not have an in-tree solution for Secure Fw.

**Comment by galak** [comment]
> So, OK to remove the NS if the platform maintainers agree, but the reasoning should just be "not interested"

@chrta was the one who submitted this and he has signed off on the removal.

**Comment by ioannisg** [comment]
> > So, OK to remove the NS if the platform maintainers agree, but the reasoning should just be "not interested"
> 
> @chrta was the one who submitted this and he has signed off on the removal.

To clarify, I only suggest changing the commit message, to something that looks like a good argument for removal. Not having TFM support for this board is not good enough, IMHO. nRF boards had _NS targets defined in Zephyr for several years, before they got TFM support :)

**Comment by galak** [comment]
> > 
> 
> To clarify, I only suggest changing the commit message, to something that looks like a good argument for removal. Not having TFM support for this board is not good enough, IMHO. nRF boards had _NS targets defined in Zephyr for several years, before they got TFM support :)

@ioannisg how about this fix instead.

**Comment by MaureenHelm** [comment]
@chrta How are you using the _ns board configuration without TFM? Did you agree with @galak to just remove the yaml (remove from CI) or to remove the _ns board configuration entirely? I worry it will break if we don't build it in CI.

**Comment by chrta** [comment]
@MaureenHelm I am not using the _ns board configuration. When i ported it, it was also present in the 55s16 board. This is the reason why i added it. I am fine with both solutions.

**Review by ioannisg — APPROVED** [review]
Yeap, if this does the job, I am fine with that, thanks @galak :)

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
