### PR TITLE
llext: Split off llext related cmake functionality

### PR DESCRIPTION
**Pull request by teburd**
Moves the llext related functionality that was in the ever growing
extensions.cmake into its own llext.cmake module. Include the module in
zephyr_default.cmake by default.

Assign maintainership of llext.cmake to the LLEXT area. These functions
and the entire cmake module are LLEXT specific and should be maintained
by LLEXT maintainers.

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
>  Moves the llext related functionality that was in the ever growing                                
> extensions.cmake into its own llext.cmake module. Include the module in                           
> zephyr_default.cmake by default.                                                                  
                                                                                                    
True that the list of llext related functions are growing, but as long as those                     
are well organized in its own section, then that is still maintainable.                             
                                                                                                    
As long as we still don't have a proper CMake doc generator in place for our                        
CMake extension functions then having a common extensions.cmake file is actually                    
very helpful, compared to have to guess where a function might be defined.                          
                                                                                                    
There are exceptions to that, and one is for purely self-contained and reusable                     
CMake modules, such as the `yaml.cmake`. The `yaml.cmake` doesn't                                   
rely on anything else in Zephyr and can actually be re-used anywhere.                               
                                                                                                    
Other example is when a CMake module creates an internal function for scoping                       
purposes or to structure loading of internal part, such as the `pre_dt.cmake`.                      
                                                                                                    
`llext` is not really there as the llext functions are highly dependent on the                      
Zephyr toolchain bintools and linker properties, not to mention the dependency                      
on `zephyr_interface`.                                                                              
                                                                                                    
Long term it is a desire to get the Zephyr CMake modules to be transformed                          
better into re-usable modules with proper dependency handling.                                      
First step was simply to cleanup,as was done in https://github.com/zephyrproject-rtos/zephyr/pull/41301.
and small steps are taken to cleanup, for example on the Kconfig and dts parts                      
with the introduction sysbuild and HWMv2.                                                           
                                                                                                    
But moving the llext functions to `llext.cmake` doesn't seem consider the                           
dependencies to other parts.                                                                        
                                                                                                    
> Assign maintainership of llext.cmake to the LLEXT area. These functions                           
> and the entire cmake module are LLEXT specific and should be maintained                           
> by LLEXT maintainers.                                                                             
                                                                                                    
With the types of CMake functions introduced for llext, then I think it's very                      
important that build system maintainer is part of reviewing / assignee on                           
the llext CMake functions introduced.

**Comment by teburd** [comment]
> > Moves the llext related functionality that was in the ever growing
> > extensions.cmake into its own llext.cmake module. Include the module in
> > zephyr_default.cmake by default.
> 
> True that the list of llext related functions are growing, but as long as those are well organized in its own section, then that is still maintainable.

I disagree, extensions.cmake is quite confusing and large. It's not at all clear in perusing the git source where the cmake functions for llext would be. Moving them to a separate llext.cmake makes a great deal of sense to me. Very hard to understand the pushback here. llext related functions should be in a llext.cmake.

> 
> As long as we still don't have a proper CMake doc generator in place for our CMake extension functions then having a common extensions.cmake file is actually very helpful, compared to have to guess where a function might be defined.
> 
> There are exceptions to that, and one is for purely self-contained and reusable CMake modules, such as the `yaml.cmake`. The `yaml.cmake` doesn't rely on anything else in Zephyr and can actually be re-used anywhere.
> 
> Other example is when a CMake module creates an internal function for scoping purposes or to structure loading of internal part, such as the `pre_dt.cmake`.
> 
> `llext` is not really there as the llext functions are highly dependent on the Zephyr toolchain bintools and linker properties, not to mention the dependency on `zephyr_interface`.
> 
> Long term it is a desire to get the Zephyr CMake modules to be transformed better into re-usable modules with proper dependency handling. First step was simply to cleanup,as was done in #41301. and small steps are taken to cleanup, for example on the Kconfig and dts parts with the introduction sysbuild and HWMv2.
> 
> But moving the llext functions to `llext.cmake` doesn't seem consider the dependencies to other parts.
> 
> > Assign maintainership of llext.cmake to the LLEXT area. These functions
> > and the entire cmake module are LLEXT specific and should be maintained
> > by LLEXT maintainers.
> 
> With the types of CMake functions introduced for llext, then I think it's very important that build system maintainer is part of reviewing / assignee on the llext CMake functions introduced.

Then by all means I'll add you as a collaborator if you'd like, but these cmake changes should not be assigned to you alone. You are clearly quite busy as it takes some time to review things. This entire area of Zephyr is moving fast, perhaps breaking some things we go back and fix along the way. That's just fine at this point. What isn't fine is taking many weeks and a month plus of review cycling to get trivial build changes in.

If you insist this needs to remain in the build system area of Zephyr, then I'd like to insist that a co-maintainer be added to the build system area of Zephyr so we can continue to move quickly. Someone not from the same company preferably.

Other crucial areas of Zephyr have co-maintainers from different companies and this seems to help ensure things move quickly and with less bias towards one companies goals. I do not need to be that co-maintainer myself, nor would I want to be.

My goal here is to speed things up, that's it.

**Comment by nashif** [comment]
> > Assign maintainership of llext.cmake to the LLEXT area. These functions
> > and the entire cmake module are LLEXT specific and should be maintained
> > by LLEXT maintainers.
> 
> With the types of CMake functions introduced for llext, then I think it's very important that build system maintainer is part of reviewing / assignee on the llext CMake functions introduced.

the change is not excluding this from the build system area, it is just adding it into the the area it actually supports, so basically depending on the change and PR, either of of the maintainers would be assigned but everyone will be added as reviewers. There is no problem with that IMO.

Similar to many areas, there is the AREA and its instances, like a driver subsystem and API and the drivers, the subsystem maintained one person, the instances by different people. You (and everyone else) probably do not want to be added as as the assignee on every cmake file change across the tree.
In this case, as long as the changes are self-contained (in an extension) and related to one area, they should be part of that area and not the subsystem providing the infrastructure for extensions.

**Comment by tejlmand** [comment]
> Very hard to understand the pushback here. llext related functions should be in a llext.cmake.

You seem to only notice the first comment, which is that I don't see zephyr_extension.cmake as being unmaintainable.
But that's just a viewpoint and **not** an argument as to why llext should stay in `zephyr_extensions.cmake`.

Did you look at any of the arguments which follows the comment ?

> llext is not really there as the llext functions are highly dependent on the
Zephyr toolchain bintools and linker properties, not to mention the dependency on zephyr_interface.


...
> Long term it is a desire to get the Zephyr CMake modules to be transformed
better into re-usable modules with proper dependency handling.

So if you want to have a llext CMake module, then make sure that dependencies are setup correctly, meaning dependent modules are also included.
I know this is not true for all Zephyr CMake modules today, but when introducing new Zephyr CMake modules, then this should be ensured, else it will become harder to cleanup if all new modules are also entangled.

Note, the `zephyr_interface` itself is a tricky one, because that lib, for historic reasons, is still being created in Zephyr's CMakeLists.txt, and thus after other other Zephyr CMake modules are loaded.
An issue that https://github.com/zephyrproject-rtos/zephyr/pull/41301 didn't address.
https://github.com/zephyrproject-rtos/zephyr/blob/c50777a8431157bd4ab3a2c2e2a37e8151ae07da/CMakeLists.txt#L105

**Comment by tejlmand** [comment]
note, it can be acceptable to address the `zephyr_interface` dependency at a later point in time.

**Comment by tejlmand** [comment]
> @tejlmand the change is not excluding this from the build system area, it is just adding it into the the area it actually supports, ...

All true, my main reason for the comment was more to highlight that using the maintainer as argument for splitting things into a dedicated CMake module is imo not a good arguments in itself.
Creating a llext CMake module should be because it makes sense, and in such case the other part of my comment should be addressed.

**Pull request closed without merging**
