### PR TITLE
test: make hello_world sample C++

### PR DESCRIPTION
**Pull request by yperess**
There's a bug currently that seems to manifest if your main function is in a .cpp file. We should migrate the simplest sample (once the issue is fixed) to avoid regression.

Signed-off-by: Yuval Peress <peress@google.com>

### CODE REVIEW

**Comment by stephanosio** [comment]
> There's a bug currently that seems to manifest if your main function is in a .cpp file.

Can you please elaborate?

**Review by stephanosio — CHANGES_REQUESTED** [review]
We should not be making `hello_world` sample C++. If any, a separate `hello_world_cpp` sample should be added.

**Comment by yperess** [comment]
> > There's a bug currently that seems to manifest if your main function is in a .cpp file.
> 
> Can you please elaborate?

I created https://github.com/zephyrproject-rtos/zephyr/issues/52376, the `main` function is never called. I ran it through a debugger, it just calls `board/posix/native_posix/main.c`'s main function and hangs.

**Comment by stephanosio** [comment]
> We should migrate the simplest sample (once the issue is fixed) to avoid regression.

Also note that we already have a sample that has `main` in a CPP file:
https://github.com/zephyrproject-rtos/zephyr/blob/84c09433b574b40a7d673fb47a1600c64b1d57c8/samples/subsys/cpp/cpp_synchronization/src/main.cpp#L133

So this is not necessary.

**Pull request closed without merging**
