### PR TITLE
[DNM] cmake toolchain cleanup system include handling

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
All this is a wip in progress to cleanup how we get the include path for libgcc, libc, and c++ headers.  This seems to fix libc with the SDK toolchain and cross-toolchain on fedora.

@aurel32 can you try this on debian.

**Comment by aurel32** [comment]
> All this is a wip in progress to cleanup how we get the include path for libgcc, libc, and c++ headers. This seems to fix libc with the SDK toolchain and cross-toolchain on fedora.

I still do not get why we use `-notstdinc` if we just re-add all those path manually.
 
> @aurel32 can you try this on debian.

It works for finding the libc, but it doesn't work for C++ headers, neither in debian nor with SDK 0.1.0. You can find a way to test that in PR #13646

**Comment by aurel32** [comment]
> > All this is a wip in progress to cleanup how we get the include path for libgcc, libc, and c++ headers. This seems to fix libc with the SDK toolchain and cross-toolchain on fedora.
> 
> I still do not get why we use `-notstdinc` if we just re-add all those path manually.

Also note that this strategy will not work for include paths added by a spec file, like it should be done in PR #12735 (but it's not done like that yet).

**Comment by marc-h38** [comment]
About the [DNM] tag: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Pull request closed without merging**
