### PR TITLE
tests: mem_protect: Clone integration test cases from sample

### PR DESCRIPTION
**Pull request by enjiamai**
There are several good integration test cases in sample, it's worthy
to reuse them to be an kernel intergation test cases.  We just clone
them and make some change to fit the ztest framework. Clone producer-
consumer and shared memory test cases to test  multiple feature such
as IPC, device, syscall, etc.

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

**Review by andyross — APPROVED** [review]
No complaints, but aren't the samples already built and validated as part of CI and the test suite?  What benefit does being a ztest test bring?

**Comment by enjiamai** [comment]
> No complaints, but aren't the samples already built and validated as part of CI and the test suite? What benefit does being a ztest test bring?

Hi, @andyross , my understanding is the samples are not validated by daily QA test and CI. For the CI part, I need to confirm it. If it is already covered by CI, and we can use the sample test cases as integration testing directly,  I believe we don't have to do this.
Speaking of ztest, I don't think it's so necessary to use it here. Just a little benefit: it can reduce some code, and judgment looks more clear.  This is my thought. Thank you! ^^

**Review by LeiW000 — APPROVED** [review]

**Comment by galak** [comment]
Do we need the sample anymore that this is cloned from?

**Comment by enjiamai** [comment]
> Do we need the sample anymore that this is cloned from?

Sorry for the reply late. Thanks for your review, @galak. Do you think would it be better if make more changes to it instead of just clone it?
Excuse me, @nashif , I really need your help on this, do you think should I just clone it or not? Or we can just leverage these sorts of samples as integration test cases directly? thank you!

**Review by nashif — CHANGES_REQUESTED** [review]
we should leave the sample as is and just use it as  test where needed.

**Comment by enjiamai** [comment]
> we should leave the sample as is and just use it as test where needed.

Got your point I know how to do for the next step, thank you.

**Pull request closed without merging**
