### PR TITLE
lib: os: poweroff: migrate TI platform

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Comment by fgrandel** [comment]
@gmarull Looks good from a driver viewpoint but I'm not deep enough into the source code of the TI power mgmt driver to be 100% sure this works. Did you have a chance to test this on real hardware?

**Comment by gmarull** [comment]
> @gmarull Looks good from a driver viewpoint but I'm not deep enough into the source code of the TI power mgmt driver to be 100% sure this works. Did you have a chance to test this on real hardware?

not really, this is just a 1:1 conversion from SOFT_OFF code.

**Comment by fgrandel** [comment]
Ok, let's see what Vaishnav thinks.

**Review by vaishnavachath — APPROVED** [review]

**Comment by gmarull** [comment]
@fgrandel would you mind approving if this works for you?

**Review by ghost — APPROVED** [review]

**Comment by fgrandel** [comment]
@gmarull Thanks for migrating this to the CC13/26xx driver!

**Pull request merged**
