### PR TITLE
drivers: spi: npcx: add SPI support to access the SPI flash

### PR DESCRIPTION
**Pull request by ChiHuaL**
The FIU/UMA module in the NPCX chip provides an dedicated SPI interface
to access the internal SPI flash. This PR adds the driver support for it

Signed-off-by: Jun Lin <CHLin56@nuvoton.com>

---
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644)

### CODE REVIEW

**Review by jackrosenthal — APPROVED** [review]

**Review by keith-zephyr — COMMENTED** [review]
> Reviewed 14 of 18 files at r1, 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644)* status: all files reviewed, 1 unresolved discussion (waiting on @ChiHuaL, @galak, @mbolivar-nordic, @MulinChao, @nashif, @sjg20, @ssekar15, @tbursztyka, @tejlmand, @WealianLiao, and @yperess)

___
*[drivers/spi/spi_npcx_fiu.c, line 96 at r3](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644#-MnBcTQt6Y05JVTfAUg6:-MnBaxjb1Oo76HbkXAl7:b4o9bh4) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fe8d6643cb29451eaeec387c129c0aa1e1980a77/drivers/spi/spi_npcx_fiu.c#L96)):*
> ```C
> 	/* Assert chip assert */
> 	spi_npcx_fiu_cs_level(dev, 0);
> 	spi_context_buffers_setup(ctx, tx_bufs, rx_bufs, 1);
> ```

It looks like the spi_nor.c driver supports an 8 byte word size.  Can the NPCX FIU driver support this word size?

**Review by ChiHuaL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644)* status: all files reviewed, 1 unresolved discussion (waiting on @galak, @keith-zephyr, @mbolivar-nordic, @MulinChao, @nashif, @sjg20, @ssekar15, @tbursztyka, @tejlmand, @WealianLiao, and @yperess)

___
*[drivers/spi/spi_npcx_fiu.c, line 96 at r3](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644#-MnBcTQt6Y05JVTfAUg6:-MnOKjC0-u5gCyCZxnT4:bl4blys) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fe8d6643cb29451eaeec387c129c0aa1e1980a77/drivers/spi/spi_npcx_fiu.c#L96)):*
<details><summary><i>Previously, keith-zephyr (Keith Short) wrote…</i></summary><blockquote>

It looks like the spi_nor.c driver supports an 8 byte word size.  Can the NPCX FIU driver support this word size?
</blockquote></details>

I am not sure if we understand your question correctly. Do you refer to the setting [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/spi_nor.c#L1231)?
If it is, this macro is finally expanded to set the bit masks (word_size) of the member ".operation" of the structure [spi_config](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/spi.h#L247)  
According to the [defination](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/spi.h#L230), the "word_size" means the size of a data frame in **bits**.
NPCX FIU module can support it.

**Review by keith-zephyr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644)* status: all files reviewed, 1 unresolved discussion (waiting on @ChiHuaL, @galak, @mbolivar-nordic, @MulinChao, @nashif, @sjg20, @ssekar15, @tbursztyka, @tejlmand, @WealianLiao, and @yperess)

___
*[drivers/spi/spi_npcx_fiu.c, line 96 at r3](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644#-MnBcTQt6Y05JVTfAUg6:-MnRBdn3DPczduW04UqY:b-uv4ta) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/fe8d6643cb29451eaeec387c129c0aa1e1980a77/drivers/spi/spi_npcx_fiu.c#L96)):*
<details><summary><i>Previously, ChiHuaL (Jun Lin) wrote…</i></summary><blockquote>

I am not sure if we understand your question correctly. Do you refer to the setting [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/spi_nor.c#L1231)?
If it is, this macro is finally expanded to set the bit masks (word_size) of the member ".operation" of the structure [spi_config](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/spi.h#L247)  
According to the [defination](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/spi.h#L230), the "word_size" means the size of a data frame in **bits**.
NPCX FIU module can support it.
</blockquote></details>

Thanks for the clarification.

**Review by keith-zephyr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @galak, @mbolivar-nordic, @MulinChao, @nashif, @sjg20, @ssekar15, @tbursztyka, @tejlmand, @WealianLiao, and @yperess)

**Pull request merged**
