### PR TITLE
boards: riscv: remove beaglev_starlight_jh7100

### PR DESCRIPTION
**Pull request by cfriedt**
Unfortunately, this board did not make it to production.

https://bit.ly/42T4Aof

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]

**Review by galak — COMMENTED** [review]
should we note this in release notes?

**Comment by cfriedt** [comment]
> should we note this in release notes?

Probably a good idea - done!

**Review by nordicjm — DISMISSED** [review]

**Review by kartben — APPROVED** [review]
thanks for paying attention, @cfriedt!

**Review by kartben — DISMISSED** [review]

**Review by carlocaione — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Review by vaishnavachath — APPROVED** [review]

**Comment by nashif** [comment]
Original submitter: @rajnesh-kanwal FYI

**Comment by evgeniy-paltsev** [comment]
@cfriedt 

looks like this PR breaking upstream CI:

```
ERROR   - tests/drivers/fuel_gauge/sbs_gauge/drivers.sbs_gauge_new_api.emulated_64_bit_i2c_addr - platform_allow - unrecognized platform - beaglev_starlight_jh7100
Changed files:
=========
include/zephyr/toolchain/mwdt.h
=========
Traceback (most recent call last):
  File "./scripts/ci/test_plan.py", line 335, in <module>
    f.process()
  File "./scripts/ci/test_plan.py", line 108, in process
    self.find_excludes()
  File "./scripts/ci/test_plan.py", line 290, in find_excludes
    self.get_plan(_options, True)
  File "./scripts/ci/test_plan.py", line 118, in get_plan
    with open(fname, newline='') as jsonfile:
FileNotFoundError: [Errno 2] No such file or directory: '_test_plan_partial.json'
Error: Process completed with exit code 1.
```

**Comment by cfriedt** [comment]
I'll get it in a few minutes

**Comment by cfriedt** [comment]
Someone else got to it first :-)
#56399

**Pull request merged**
