### PR TITLE
snippets: intel_socfpga: add support for Intel SoC FPGA Agilex series

### PR DESCRIPTION
**Pull request by tanmaykathpalia**
Intel Agilex and Agilex5 board support recently was added to 
Zephyr mainline. With this snippet, all the required drivers can
be enabled and it can be used in any application.

Signed-off-by: Tanmay Kathpalia <tanmay.kathpalia@intel.com>

### CODE REVIEW

**Comment by tanmaykathpalia** [comment]
@carlescufi @tejlmand @jfischer-no @nordicjm please have a look and provide your feedback.

**Comment by tejlmand** [comment]
not sure I understand why this is a snippet, and why a snippet should:
> enabling all peripherals for supported boards.

There is a reason why Zephyr states:
https://docs.zephyrproject.org/latest/hardware/porting/board_porting.html#general-recommendations
> Unless explicitly recommended otherwise by this section, leave peripherals and their drivers disabled by default.

So having a snippet for a given board to simple enable all peripherals seems plain wrong to me.

A snippet should cover some specific use-case, for example the `cdc-acm`.
If a given sample should enable certain peripherals, like the `subsys/shell_module`, then such sample should have board specific overlay's / config fragments according to its specific needs.

**Review by tejlmand — CHANGES_REQUESTED** [review]
not sure I understand why this is a snippet, and why a snippet should:
> enabling all peripherals for supported boards.

There is a reason why Zephyr states:
https://docs.zephyrproject.org/latest/hardware/porting/board_porting.html#general-recommendations
> Unless explicitly recommended otherwise by this section, leave peripherals and their drivers disabled by default.

So having a snippet for a given board to simple enable all peripherals seems plain wrong to me.

A snippet should cover some specific use-case, for example the `cdc-acm`.
If a given sample should enable certain peripherals, like the `subsys/shell_module`, then such sample should have board specific overlay's / config fragments according to its specific needs.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
>@carlescufi @tejlmand @jfischer-no @nordicjm please have a look and provide your feedback.

Your PR makes no sense.

**Comment by tanmaykathpalia** [comment]
@tejlmand @jfischer-no   Can you suggest some other way so that we can enable all the peripherals for an application? As this is a requirement for us to enable all the peripherals for the shell application and earlier we created a configuration file and device tree overlay in the "samples/subsys/shell/shell_module/boards/" folder which @kartben suggested in [PR 65753](https://github.com/zephyrproject-rtos/zephyr/pull/65753) to make a snippet for the same.

**Comment by kartben** [comment]
> @tejlmand @jfischer-no   Can you suggest some other way so that we can enable all the peripherals for an application? As this is a requirement for us to enable all the peripherals for the shell application and earlier we created a configuration file and device tree overlay in the "samples/subsys/shell/shell_module/boards/" folder which @kartben suggested in [PR 65753](https://github.com/zephyrproject-rtos/zephyr/pull/65753) to make a snippet for the same.
> 

I think I initially suggested you create a dedicated sample, either for your specific board in boards/, or for your newly introduced subsystem.

**Comment by tanmaykathpalia** [comment]
Closing this PR, as the changes in this PR are not aligned the way snippets are meant to be used.

**Pull request closed without merging**
