### PR TITLE
hal: stm32f2x: usbotg_fs: fix VBUS sensing deactivation

### PR DESCRIPTION
**Pull request by ibisz**
The error is detected if USART1 TX configured to PA9 and RX to PA10.
The serial cable removal stops the USB communication.
In case of VBUS sensing deactivation, erroneously
both USB_OTG_GCCFG_VBUSBSEN and
USB_OTG_GCCFG_NOVBUSSENS are set in GCCFG.
Correct handling is:
 - VBUS sensing deactivation: set USB_OTG_GCCFG_NOVBUSSENS in GCCFG.
 - VBUS sensing activation:   set USB_OTG_GCCFG_VBUSBSEN in GCCFG.

ST Bug Tracker ID: 34714
  
Signed-off-by: Istvan Bisz <istvan.bisz@t-online.hu>

### CODE REVIEW

**Comment by erwango** [comment]
Looks ok to me, but adding @ydamigos  to the review

**Comment by qianfan-Zhao** [comment]
@ibisz Means if both USB_OTG_GCCFG_VBUSBSEN and USB_OTG_GCCFG_NOVBUSSENS was set, NOVBUSSENS doesn't take affect?

**Comment by ydamigos** [comment]
Looks good. I agree with @ibisz on this. The reference manual doesn't give us a clear picture on this (if setting USB_OTG_GCCFG_NOVBUSSENS overrides an already set USB_OTG_GCCFG_VBUSBSEN). I believe it is safer to set them alternatively.
@erwango Before approving the PR which changes ext HAL files is it possible to get some input from ST on this?

**Comment by ibisz** [comment]
@qianfan-Zhao, Yes, this is my conclusion based on my tests.

**Comment by ibisz** [comment]
I will try to do it.
Is it possible to share the link to the ST bug-tracker system to avoid inutile efforts regarding the already known issues testing/fixing?

Thanks

**Comment by erwango** [comment]
@ibisz 

> Is it possible to share the link to the ST bug-tracker system to avoid inutile efforts regarding the already known issues testing/fixing?

I would love to, but unfortunately this is for internal use only.

**Comment by ibisz** [comment]
@erwango, Done. Thanks for the advice.

**Review by ydamigos — APPROVED** [review]

**Comment by ibisz** [comment]
@erwango Can you please make a review?

**Review by erwango — APPROVED** [review]

**Pull request merged**
