### PR TITLE
Fix Bug in Kconfig file of icm42688 driver

### PR DESCRIPTION
**Pull request by shenyi97**
The config option of driver icm42688 appeared unexpectedly in menuconfig when the app use other sensors.The bug is fixed by slightly modifing the Kconfig file of icm42688

### CODE REVIEW

**Review by yperess — DISMISSED** [review]

**Review by tristan-google — DISMISSED** [review]
Welcome and thanks for contributing to the Zephyr project! Looks like the CI caught a formatting issue --if you could correct that we should be able to get this landed pretty quickly.

**Comment by tristan-google** [comment]
Could you squash these two commits and force-push so that we only merge one commit for this fix?

**Comment by shenyi97** [comment]
> Welcome and thanks for contributing to the Zephyr project! Looks like the CI caught a formatting issue --if you could correct that we should be able to get this landed pretty quickly.

Thanks, the formatting issue was correted.

**Comment by shenyi97** [comment]
> Could you squash these two commits and force-push so that we only merge one commit for this fix?

Sure

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — COMMENTED** [review]
The code change looks good, but please fix the failed compliance check.

```
 1: UC2 Signed-off-by: must have a full name
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 c4f72fa9725165f813b4d81b53390c02a8c11a54: author email (shenxuyang <shenyi97@hotmail.com>) does not follow the syntax: First Last <email>.
```

**Review by kartben — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
