### PR TITLE
Bluetooth: MCS: Disable OACP checksum support

### PR DESCRIPTION
**Pull request by piotrnarajowski**
This is needed to properly initialize media player for GMCS tests. This feature was enabled for OTS tests, but is not needed for GMCS tests and is causing all CAP and GMCS test cases to fail.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr OTS/SR/CR/BV-03-C CAP/INI/UST/BV-02-C GMCS/SR/SGGIT/CHA/BV-03-C

**Review by Thalley — APPROVED** [review]

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Reason unknown

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Reason unknown

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>CAP     CAP/INI/UST/BV-02-C             BUILD_OR_FLASH ERROR<br>GMCS    GMCS/SR/SGGIT/CHA/BV-03-C       BUILD_OR_FLASH ERROR<br>OTS     OTS/SR/CR/BV-03-C               BUILD_OR_FLASH ERROR</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>CAP     CAP/INI/UST/BV-02-C             PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-03-C       PASS<br>OTS     OTS/SR/CR/BV-03-C               PASS</details>

**Review by sjanc — APPROVED** [review]

**Comment by Thalley** [comment]
@piotrnarajowski why was this closed?

**Comment by piotrnarajowski** [comment]
@Thalley looks like PR https://github.com/zephyrproject-rtos/zephyr/pull/73017 which is already merged contains similar changes

**Comment by Thalley** [comment]
Ah, thanks. Please do add a description when closing PRs in the future :)

**Pull request closed without merging**
