### PR TITLE
dts: nxp: nxp_rt: Fix unit-address for usb node

### PR DESCRIPTION
**Pull request by galak**
The first reg of the node is 0x402E0200 so the unit address should match
that.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by MaureenHelm — COMMENTED** [review]
This is a little confusing because `ext/hal/nxp/mcux/devices/MIMXRT1052/MIMXRT1052.h` says address 0x402E0200 is USB2, not USB1. @MarkWangChinese does the node name also need to be updated to `usbd2`?

**Comment by MarkWangChinese** [comment]
> This is a little confusing because `ext/hal/nxp/mcux/devices/MIMXRT1052/MIMXRT1052.h` says address 0x402E0200 is USB2, not USB1. @MarkWangChinese does the node name also need to be updated to `usbd2`?

Hi @MaureenHelm, thanks @galak, the address is 0x402E0000 for the usbd1, and we don't add the usbd2 yet in the dts because the Zephyr usb device stack only supports one controller instance. I think reg = <0x402E0200 0x1000>; is wrong, need change as reg = <0x402E0000 0x200>;

**Comment by galak** [comment]
> Hi @MaureenHelm, thanks @galak, the address is 0x402E0000 for the usbd1, and we don't add the usbd2 yet in the dts because the Zephyr usb device stack only supports one controller instance. I think reg = <0x402E0200 0x1000>; is wrong, need change as reg = <0x402E0000 0x200>;

which port was meant to be used on the mimxrt1050_evk?

In the dts/arm/nxp/nxp_rt.dtsi we should both USB1 and USB2 defined.

**Comment by galak** [comment]
I updated this to change the label to usbd1 to usbd2 as that makes the most sense right now.  If the board uses USBD1, lets fix this up to add that into nxp_rt.dtsi.

**Comment by MarkWangChinese** [comment]
USB1 is used on the mimxrt1050_evk. Updating this to usbd2 and adding usbd1 make sense too. Will you help add the usbd1 or I need do another pull-request?

**Review by MaureenHelm — APPROVED** [review]
Thanks @galak 

> Will you help add the usbd1 or I need do another pull-request?

@MarkWangChinese Please create another PR.

**Pull request merged**
