### PR TITLE
i2c: stm32: Convert driver to DT_ macros

### PR DESCRIPTION
**Pull request by erwango**
Convert stm32 i2c driver to new DT macros.
Clean up stm32 board files from I2C related Kconfig symbols

### CODE REVIEW

**Review by galak — APPROVED** [review]
Is the clock stuff why we need NODELABEL for I2C?

**Comment by erwango** [comment]
> Is the clock stuff why we need NODELABEL for I2C?

Yes

**Review by avisconti — APPROVED** [review]
LGTM

**Comment by galak** [comment]
Going to merge as this will never pass CI due to large number of STM32 platforms.

**Pull request merged**
