### PR TITLE
samples: drivers: can: reduce board specifics

### PR DESCRIPTION
**Pull request by karstenkoenig**
Reworked the CAN driver sample to be working more out of the box based
on SW0 and LED0 definitions in DTS for the button and led.
Also moved the mcp2515 overlay and config into a boards subfolder to
reduce clutter in the main directory.

Signed-off-by: Karsten Koenig <karsten.koenig.030@gmail.com>

### CODE REVIEW

**Comment by karstenkoenig** [comment]
@alexanderwachter This should make the CAN sample more widely usable without touching LED and BUTTON KConfig stuff and also creates a boards folder

@DWagenk You requested the SW0 and LED0 changes, here you go :-)

@jfischer-phytec-iot This would provide a board folder in the samples to just add in the reel board overlay and project config. It also tries to cleanly handle the button GPIO config via SW0_GPIO_FLAGS defines that you did here:
https://github.com/zephyrproject-rtos/zephyr/pull/15295/commits/5572cb4c74757c2725dbe2a978c96566079c1e32

**Comment by alexanderwachter** [comment]
As far as #13262 gets merged I'll create a new sample from scratch without any button's and LED's but periodic transmissions and printk. The actual one is to complicate regarding GPOI.

**Comment by karstenkoenig** [comment]
Ah awesome, well that's way cleaner and yes it sounds like a better 'sample'
What do you think, should I just close this one or should I leave it if there is holdups on your driver refactoring?

**Comment by alexanderwachter** [comment]
I think we should keep this PR. Maybe I'll keep the LED with an ifdef LED0_PORT or kind like that.
LED's are always good for a quick check when more boards are connected through CAN but only one is connected trough UART.

**Comment by karstenkoenig** [comment]
@alexanderwachter 
The sanity check fails building the sample for the nucleo_l432kc board now. Technically the sample in its current state (before and after this pr) doesn't work on the board out of the box as there is no button. True bummer actually, I have the board too and like it for its size, why couldn't they have squeezed in a button?
Is there a way to remove the board from the automatic builds? It's taken from this file as far as I can see, but that is autogenerated, and I don't see any whitelisting of nucleo_l432kc in samples/drivers/CAN
https://github.com/zephyrproject-rtos/zephyr/blob/master/scripts/sanity_chk/sanity_last_release.csv

**Comment by alexanderwachter** [comment]
@karstenkoenig AFAIK it is built because the board yaml file contains something like
```
supported:
- can
```
You can try to remove that line.

**Review by dbkinder — APPROVED** [review]

**Comment by karstenkoenig** [comment]
Canceled this PR, @alexanderwachter has better plans for the sample and will along get rid of the handrolled gpio assignments. The fixes for the mcp2515 dts will be broken into their own pull request

**Comment by alexanderwachter** [comment]
Here is the plan: #18081

**Pull request closed without merging**
