### PR TITLE
 cmake: Zephyr ALLOW_EMPTY library property

### PR DESCRIPTION
**Pull request by tejlmand**
This commit is an alternative to #37910

 drives: cmake: zephyr_library_property(ALLOW_EMPTY TRUE) on drivers lib

This commit now sets the Zephyr library property `ALLOW_EMPTY` to
silence the warning:
`No SOURCES given to Zephyr library: drivers__interrupt_controller`

-----

 cmake: Zephyr ALLOW_EMPTY library property

This introduces a dedicated zephyr_library_property() function which
provides a common way to set Zephyr build system known properties on
Zephyr libraries.

As a first common property is the `ALLOW_EMPTY` property which allows
to create a `zephyr_library()` without putting any content inside of it.

In general libraries should not be created unless there are files to
places inside of it, however in some cases there are so many
`zephyr_library_sources_ifdef(<setting> <file.c>)`
where testing each setting before creating the library may not be
desired.

This commit allows the following construct in those cases:
```
zephyr_library()
zephyr_library_property(ALLOW_EMPTY TRUE)
zephyr_library_sources_ifdef(CONFIG_SETTING_1 file_1.c)
zephyr_library_sources_ifdef(CONFIG_SETTING_2 file_2.c)
...
zephyr_library_sources_ifdef(CONFIG_SETTING_n file_n.c)

```

### CODE REVIEW

**Comment by SebastianBoe** [comment]
What does an empty library look like in the build logs and in the generated build system?

**Comment by SebastianBoe** [comment]
Ah, I see now.

So we still have the library in the build logs and in the generated build system.

This mechanism slows down the build and pollutes the build logs and the generated build system with noise. This noise can confuse users as to what is actually included in the build and is annoying for a user to sift through to find the things that are actually included in the build.

I don't support this.

It is better if we write the build scripts such that the library is not added in the first place.

**Comment by tejlmand** [comment]
> This mechanism slows down the build

It doesn't, cause the library is removed from all build targets
https://github.com/zephyrproject-rtos/zephyr/blob/b78d6740ec3510cc99b41c998544bcac747b4e40/CMakeLists.txt#L719

meaning no build will include this empty library.

> pollutes the build logs 

Which build logs are you referring to ?
If looking at verbose ninja, the `libdrivers__interrupt_controller.a` is not present there because it is not built:
```
$ ninja -v > build.log
$ grep libdrivers__interrupt_controller.a build.log
# <no hits>
```

But if we check the same log for the gpio lib, you'll get:
```
$ grep libdrivers__gpio.a build.log
[100/149] : && ccache /opt/cmake-3.20.2-linux-x86_64/bin/cmake -E rm -f zephyr/drivers/gpio/libdrivers__gpio.a && ccache /opt/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-ar qc zephyr/drivers/gpio/libdrivers__gpio.a  zephyr/drivers/gpio/CMakeFiles/drivers__gpio.dir/gpio_nrfx.c.obj && ccache /opt/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-ranlib zephyr/drivers/gpio/libdrivers__gpio.a && :
[142/149] : ...
[149/149] : ...
```

So the only overhead you could argue is present is the `zephyr_library_property(ALLOW_EMPTY TRUE)` call, and the check for that property.
But you would one way or another have to perform such a test.
You just propose to form a list, and then carry out an empty test on that list instead.

For reference, I just executed two CMake invocations of hello_world:
`zephyr/main`
```
$ time cmake -GNinja -DBOARD=nrf52840dk_nrf52840 -Bbuild samples/hello_world/
.....
________________________________________________________
Executed in    2.94 secs   fish           external 
   usr time    2.20 secs    0.00 millis    2.20 secs 
   sys time    0.53 secs   24.29 millis    0.51 secs 
```

and with #38347 
```
$ time cmake -GNinja -DBOARD=nrf52840dk_nrf52840 -Bbuild samples/hello_world/
.....
________________________________________________________
Executed in    2.74 secs   fish           external 
   usr time    2.20 secs    0.00 millis    2.20 secs 
   sys time    0.48 secs   24.24 millis    0.45 secs 
```

I consider the slight variation to be normal system variation here.

**Comment by tejlmand** [comment]
> It doesn't, cause the library is removed from all build targets

Which is very different from the `empty_file.c` case, that would actually create the library and add the file, causing it to be compiled and thus show up in build logs. Very different from this solution.

**Comment by SebastianBoe** [comment]
Ah, I was not aware of this change https://github.com/zephyrproject-rtos/zephyr/commit/d95200447b98d3a182b8edce9606f0617384bee2

Then this is fine.

**Comment by carlescufi** [comment]
> Ah, I was not aware of this change [d952004](https://github.com/zephyrproject-rtos/zephyr/commit/d95200447b98d3a182b8edce9606f0617384bee2)
> 
> Then this is fine.

Can you approve it @SebastianBoe please?

**Review by SebastianBoe — APPROVED** [review]

**Comment by tejlmand** [comment]
> 
> 
> Ah, I was not aware of this change [d952004](https://github.com/zephyrproject-rtos/zephyr/commit/d95200447b98d3a182b8edce9606f0617384bee2)
> 
> Then this is fine.

@SebastianBoe Thanks for paying attention.
It's nice to have you back with an eye for the CMake details, highly appreciated 😄

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
