### PR TITLE
drivers: serial: uart_nrfx_uarte: Patch RX init

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
The initialization of the UARTE is attempting to handle potential improper handover from the bootloader. This handling is additional complexity which should be fixed in the bootloader or whatever component is failing to deinit the UART properly.

This commit removes the handling of improper handover from the bootloader, while additionally clearing the ERROR flag when suspending the UARTE component.

Alternative to #74300

Looking into why this was added, see #26555 which indentifies that MCUBoot fails to properly clean up the uarte, which results in the cleanup being moved to the application (instead of being fixed in MCUBoot). The cleanup has been added to is fixed in the NCS fork of MCUBoot, and the cleanup should likely be ported to the upstream MCUBoot fork.

### CODE REVIEW

**Comment by bjarki-andreasen** [comment]
@de-nordic I see you added some cleanup of UARTE to the NCS fork of mcu_boot, do you think it makes sense to add a function like `boot_console_deinit()` to zephyr's MCUBoot fork to properly reset the UARTE device driver?

**Review by nordic-krch — APPROVED** [review]

**Comment by M1cha** [comment]
While this sounds correct in theory, you can't really update mcuboot in-field (easily and without risks). So removing all workarounds from the UART driver means, that every user of this driver has to implement their own workarounds in their apps.

**Comment by bjarki-andreasen** [comment]
> While this sounds correct in theory, you can't really update mcuboot in-field (easily and without risks). So removing all workarounds from the UART driver means, that every user of this driver has to implement their own workarounds in their apps.

That is indeed what I'm proposing, if there is a bug in a user's mcuboot, workarounds must be added to any application which will be running with that specific bootloader. Every driver should not try to predict any and all possible mis-configurations just in case. These predictions themselves are added complexity which come with their own bugs.

**Comment by nordic-krch** [comment]
Also it's worth noting that workaround is flawed as it predicts that UARTE RX is still active based on RXSTARTED event being set and then expects RXTO event to arrive. RXSTARTED being set does not guaranty that RX is still active and RXTO may not come. Someone hit that and added case for ERROR event being set but it will also not work in all cases (in particular if RXSTARTED is set but RX is stopped then endless loop will be hit).

@bjarki-andreasen when do you plan to take it out of draft?

**Comment by bjarki-andreasen** [comment]
> @bjarki-andreasen when do you plan to take it out of draft?

Did not realize it was in draft :D

**Comment by bjarki-andreasen** [comment]
Rebase and re-running CI, CI was last run before 3.7 :)

**Review by anangl — APPROVED** [review]

**Comment by ball-hayden** [comment]
Hi @bjarki-andreasen 

I think we're being bitten by this.

> That is indeed what I'm proposing, if there is a bug in a user's mcuboot, workarounds must be added to any application which will be running with that specific bootloader.

May I ask what your proposal is for how the application should work around the bootloader handing off UART in a bad state?

**Comment by bjarki-andreasen** [comment]
> Hi @bjarki-andreasen
> 
> I think we're being bitten by this.
> 
> > That is indeed what I'm proposing, if there is a bug in a user's mcuboot, workarounds must be added to any application which will be running with that specific bootloader.
> 
> May I ask what your proposal is for how the application should work around the bootloader handing off UART in a bad state?

Depends, is your bootloader immutable? then add whatever code is needed to undo what your bootloader is doing wrong to your application. If it is not, fix the bootloader and update it.

**Comment by ball-hayden** [comment]
> is your bootloader immutable?

Yes.

Can you link back to the fix to the bootloader that allows the removal of this workaround, please? That would be very helpful in "adding whatever code is needed".

In case it's helpful to anyone else that lands here, this is my current proposed workaround:

```c
#include <hal/nrf_uarte.h>

static int uart_handoff_workaround(void)
{
  NRF_UARTE_Type *uarte = NRF_UARTE1;

  nrf_uarte_disable(uarte);
  nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_ENDRX);
  nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_ERROR);
  nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_RXSTARTED);
  nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_RXTO);
  nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_TXSTARTED);
  nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_TXSTOPPED);

  return 0;
}

SYS_INIT(uart_handoff_workaround, PRE_KERNEL_1, 0);

```

**Comment by JordanYates** [comment]
Running into the same issue as others, upgrading devices with a v3.9 era bootloader and the new application uses an extra ~600uA...

**Comment by JordanYates** [comment]
Also, removing the patch here without a corresponding update to MCUboot to fix the root cause is unhelpful :/

**Comment by JordanYates** [comment]
To expand upon the workaround that @ball-hayden proposed, I am using this in my `board.c`, which handles stopping any pending RX, while handling the caveat @nordic-krch mentioned with a 100ms timeout.
```
#ifdef CONFIG_BOOTLOADER_MCUBOOT

#include <zephyr/kernel.h>
#include <hal/nrf_uarte.h>

/* MCUboot does not properly cleanup the UART peripheral before booting the application.
 * If left enabled, this draws an extra 600uA until the first time the application uses
 * the UART port again. The workaround in the UARTE driver was removed in v4.0 without a
 * corresponding fix to MCUboot. Even if it were fixed in MCUboot, this would still be
 * required to obtain the proper behaviour when updating devices with a pre-fix bootloader.
 */
static int uart_handoff_workaround(void)
{
	NRF_UARTE_Type *uarte = NRF_UARTE0;

	if (nrf_uarte_event_check(uarte, NRF_UARTE_EVENT_RXSTARTED)) {
		nrf_uarte_task_trigger(uarte, NRF_UARTE_TASK_STOPRX);
		/* Wait up to 100ms for task to stop */
		for (int i = 0; i < 1000; i++) {
			if (nrf_uarte_event_check(uarte, NRF_UARTE_EVENT_RXTO) ||
			    nrf_uarte_event_check(uarte, NRF_UARTE_EVENT_ERROR)) {
				/* RX terminated, break*/
				break;
			}
			/* Wait 100us before next check */
			k_busy_wait(100);
		}
	}
	nrf_uarte_disable(uarte);
	nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_ENDRX);
	nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_ERROR);
	nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_RXSTARTED);
	nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_RXTO);
	nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_TXSTARTED);
	nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_TXSTOPPED);
	return 0;
}

SYS_INIT(uart_handoff_workaround, PRE_KERNEL_1, 0);

#endif /* CONFIG_BOOTLOADER_MCUBOOT */
```

**Pull request merged**
