### PR TITLE
drivers: fixed return code bug in eth_stm32_hal_set_config()

### PR DESCRIPTION
**Pull request by BWeiberg**
Signed-off-by: Bernd Weiberg <bernd.weiberg@siemens.com>

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

**Comment by erwango** [comment]
@BWeiberg Thanks for this contribution.
Can you fix the guidelines compliance issue, regarding your commit message, reported by automated checks:
```
1: UC6 Body has no content, should at least have 1 line.
```

**Review by KozhinovAlexander — DISMISSED** [review]

**Review by erwango — DISMISSED** [review]

**Comment by erwango** [comment]
@jukkar can you re-approve?

**Comment by jukkar** [comment]
There is still this error that needs fixing
```
2: B4 Second line is not empty: "the function eth_stm32_hal_set_config() located in drivers/ethernet/eth_stm32_hal.c"
2: UC4 Line exceeds max length (83>75): "the function eth_stm32_hal_set_config() located in drivers/ethernet/eth_stm32_hal.c"
4: UC4 Line exceeds max length (86>75): "This commit fixes the return statement so that the real result (ret) will be returned."
```

**Comment by BWeiberg** [comment]
Sorry guys this is my first contribution to zephyr. I'am still not famillar with the commit guidelines.
Now all checks have been passed successfully.
So please re-approve.

**Review by carlescufi — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
