### PR TITLE
samples: mesh: nrf52: minor improvements & resolved the issue which is introduced by PR:9521

### PR DESCRIPTION
**Pull request by vikrant8052**
Removed redundant lines of code which are inappropriate
as per latest implementation.

Removed bug which get introduced by PR:9521. Because of it
not able to save App's variable on SoC flash.

### CODE REVIEW

**Comment by jhedberg** [comment]
recheck

**Comment by vikrant8051** [comment]
I've rechecked. Do you find flaw in latest changes ?

**Comment by vikrant8051** [comment]
@carlescufi @jhedberg @nvlsianpu 
Please note that after merging PR:9521 persistence storage mechanism is not
working as per expectations. Following issue has observed:
1) After reset provisioned NODE not get discover
2) Sometimes APP key have to reassign 
etc. etc.

**Review by nvlsianpu — APPROVED** [review]
great you found that!

**Comment by jhedberg** [comment]
> I've rechecked. Do you find flaw in latest changes?

@vikrant8051 my "recheck" comment wasn't for you. It was a command to the automated build-system which had a failure which was not related to this PR. Posting a "recheck" comment causes the build system to re-try the build.

**Pull request merged**
