### PR TITLE
tests: net: buf: Fix cloning of zero-sized buffers

### PR DESCRIPTION
**Pull request by rettichschnidi**
For zero sized buffers, instead of pointing to a buffer, net_buf->__buf
is NULL. For this reason, when cloning a buffer, the code needs to check
__buf before dereferencing it.

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

**Comment by rettichschnidi** [comment]
Rebased because of a conflict.

**Review by jhedberg — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
Nit: split into 2 commits?

**Comment by rettichschnidi** [comment]
> Nit: split into 2 commits?

Done

**Comment by pdgendt** [comment]
> > Nit: split into 2 commits?
> 
> Done

The first commit subject shouldn't start with `tests: `.

**Review by jukkar — APPROVED** [review]

**Pull request merged**
