### PR TITLE
boards/efr32mg_sltb004a: use crystal instead of RC oscillator

### LINKED ISSUE #17630: efr32mg_sltb004a tick clock error
The application below, when built for `efr32mg_sltb004a` emits the timestamp information at 2 s intervals.  It appears the clock is running at half the expected speed.

```
#include <zephyr.h>
#include <misc/printk.h>
#include <stdio.h>

static void timer_handler(struct k_timer *tmr)
{
	u32_t t = k_uptime_get_32();
	unsigned int ms = t % 1000;
	t /= 1000;
	unsigned int s = t % 60;
	t /= 60;
	unsigned int min = t % 60;
	unsigned int hr = t / 60;

	printf("%u:%02u:%02u.%03u ; stuff\n",
	       hr, min, s, ms);
}
K_TIMER_DEFINE(tmr, timer_handler, NULL);

void main(void)
{
	printk("Hello World! %s\n", CONFIG_BOARD);
	printf("%u ticks/s = %u us/tick\n",
	       CONFIG_SYS_CLOCK_TICKS_PER_SEC,
	       1000000U / CONFIG_SYS_CLOCK_TICKS_PER_SEC);
	k_timer_start(&tmr, 0, K_SECONDS(1));
	k_sleep(K_FOREVER);
}
```

### PR DESCRIPTION
**Pull request by pabigot**
Selection of the HFRCO causes the SOC to stay at its power-up frequency
of 19 MHz.  Switch to the HFXO to use the configured frequency.

Closes #17630

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

**Review by chrta — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
Do we need to back port this @pabigot ?

**Comment by pabigot** [comment]
@ioannisg Yes.  I've added the label.

**Comment by ioannisg** [comment]
@mnkp would you like to provide some feedback in this bug-fix PR?

**Review by mnkp — APPROVED** [review]
Sorry for the delay reviewing the PR.

**Pull request merged**
