### PR TITLE
Update ism330dhcx_spi.c

### PR DESCRIPTION
**Pull request by cooked**
fix ism330dhcx spi passing correct handle to ctx

### CODE REVIEW

**Comment by flamerten** [comment]
Hello, can I check if this fix was tested with the actual sensor? I pulled the commit and ran into the following problem. Before I also had a [ticket](https://devzone.nordicsemi.com/f/nordic-q-a/98991/nrf52840dk---unable-to-get-ism330dhcx-on-spi-working) with the Noridic Dev Zone with not being able to work with the ISM330DHCX via SPI.

When i enable logging, this is the error.

`[00:00:00.250,488] <inf> ISM330DHCX: chip id 0x0, chip id should be 0x6b
[00:00:00.250,518] <dbg> ISM330DHCX: ism330dhcx_init_chip: Invalid chip id 0x0
[00:00:00.250,549] <dbg> ISM330DHCX: ism330dhcx_init: failed to initialize chip
*** Booting Zephyr OS build v3.2.99-ncs2 ***
[00:00:00.250,640] <inf> basic_IMU: Error: Device "ism330dhcx@0" is not ready; check the driver initialization logs for errors.

[00:00:00.250,640] <inf> basic_IMU: Unable to retrieve IMU`

**Comment by flamerten** [comment]
Hello, may i check if you were able to run SPI with the actual ISM330DHCX sensor? I've been facing problems trying to get the sensor to work with Zephy from a few days, and have raised a [ticket](https://devzone.nordicsemi.com/f/nordic-q-a/98991/nrf52840dk---unable-to-get-ism330dhcx-on-spi-working) here in the Noridc Dev Zone.

I faced this issue after pulling this fix
```
[00:00:00.250,488] <inf> ISM330DHCX: chip id 0x0, chip id should be 0x6b
[00:00:00.250,518] <dbg> ISM330DHCX: ism330dhcx_init_chip: Invalid chip id 0x0
[00:00:00.250,549] <dbg> ISM330DHCX: ism330dhcx_init: failed to initialize chip
*** Booting Zephyr OS build v3.2.99-ncs2 ***
[00:00:00.250,640] <inf> basic_IMU: Error: Device "ism330dhcx@0" is not ready; check the driver initialization logs for errors.

[00:00:00.250,640] <inf> basic_IMU: Unable to retrieve IMU
```
Are there any possible reasons why I could be running into this issue? Is it mainly a Zephyr Issue? I have rules out any electrical reasons, and was able to work with SPI using the same sensor on another framework(Arduino IDE)

**Review by avisconti — APPROVED** [review]
Good catch! Thanks

**Comment by cooked** [comment]
> Good catch! Thanks

my bad, didn't read the guidelines on commit formatting before pushing the PR so the CI failed. 
is there a way to fix the comment in the previous commit or should I make a new PR? (sorry, I'm quite a noob contributing to large projects)

thanks for the help

**Comment by avisconti** [comment]
> > Good catch! Thanks
> 
> my bad, didn't read the guidelines on commit formatting before pushing the PR so the CI failed. is there a way to fix the comment in the previous commit or should I make a new PR? (sorry, I'm quite a noob contributing to large projects)
> 
> thanks for the help

Usually I do changes locally and git push -f on the same branch.

**Comment by dipakgmx** [comment]
> [00:00:00.250,488] <inf> ISM330DHCX: chip id 0x0, chip id should be 0x6b

I see the same behaviour on my end too.

**Comment by avisconti** [comment]
> Hello, may i check if you were able to run SPI with the actual ISM330DHCX sensor? I've been facing problems trying to get the sensor to work with Zephy from a few days, and have raised a [ticket](https://devzone.nordicsemi.com/f/nordic-q-a/98991/nrf52840dk---unable-to-get-ism330dhcx-on-spi-working) here in the Noridc Dev Zone.
> 
> I faced this issue after pulling this fix
> 
> ```
> [00:00:00.250,488] <inf> ISM330DHCX: chip id 0x0, chip id should be 0x6b
> [00:00:00.250,518] <dbg> ISM330DHCX: ism330dhcx_init_chip: Invalid chip id 0x0
> [00:00:00.250,549] <dbg> ISM330DHCX: ism330dhcx_init: failed to initialize chip
> *** Booting Zephyr OS build v3.2.99-ncs2 ***
> [00:00:00.250,640] <inf> basic_IMU: Error: Device "ism330dhcx@0" is not ready; check the driver initialization logs for errors.
> 
> [00:00:00.250,640] <inf> basic_IMU: Unable to retrieve IMU
> ```
> 
> Are there any possible reasons why I could be running into this issue? Is it mainly a Zephyr Issue? I have rules out any electrical reasons, and was able to work with SPI using the same sensor on another framework(Arduino IDE)

You mean that before this fix you had ism330dhcx working on spi and after it you had not? Should be the opposite... Please provide more info

**Comment by dipakgmx** [comment]
@avisconti Not the OP commentor, but am facing a similar issue. Am on Zephyr 3.2 release and using the module with the SPI bus. Prior to the suggested fix, the application would crash, since an illegal pointer was being passed around. With the fix suggested, the SPI could initialise, but I see the reply for the version via the SPI bus is 0.

**Comment by flamerten** [comment]
@avisconti Apologies for not being clearer.

My environment is nRF Connect SDK v2.3.0, which is based on Zephyr. Without this fix, as @dipakgmx mentioned, the program would crash before the main stage.

```
[00:00:00.376,464] <err> os: ***** BUS FAULT *****
[00:00:00.376,495] <err> os: Precise data bus error
[00:00:00.376,495] <err> os: BFAR Address: 0xff4672b5
[00:00:00.376,525] <err> os: r0/a1: 0x00005285 r1/a2: 0x00000010 r2/a3: 0xff4672b5
[00:00:00.376,525] <err> os: r3/a4: 0x2000286c r12/ip: 0x20002884 r14/lr: 0x0000d71b
[00:00:00.376,556] <err> os: xpsr: 0x01000000
[00:00:00.376,556] <err> os: Faulting instruction address (r15/pc): 0x0000d6be
[00:00:00.376,586] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.376,617] <err> os: Current thread: 0x200008d0 (main)
```
This was due to a specific line in the `ism330dhcx_spi.c` file that is fixed by this pull request. 

```
C:/ncs/v2.3.0/zephyr/drivers/sensor/ism330dhcx/ism330dhcx_spi.c:57
```

With this pull request, the problem appears to be fixed. However, when trying to use the actual ISM330DHCX sensor, the driver does not appear to detect that it is the correct sensor.

```
#define IMU0_NODE DT_NODELABEL(imu_1)
static const struct device *get_ism_device(void)
{
	const struct device *const dev = DEVICE_DT_GET(IMU0_NODE);

	if (dev == NULL) {
		LOG_ERR("\nError: no device found.\n");
		return NULL;
	}

	if (!device_is_ready(dev)) {
		LOG_ERR("\nError: Device \"%s\" is not ready; "
		       "check the driver initialization logs for errors.\n",
		       dev->name);
		return NULL;
	}
}
```

This leads to the error mentioned above. With some debugging, it seems that the chip id that is returned is not what the driver expects. 

```
[00:00:00.250,488] <inf> ISM330DHCX: chip id 0x0, chip id should be 0x6b
[00:00:00.250,518] <dbg> ISM330DHCX: ism330dhcx_init_chip: Invalid chip id 0x0
```

It seems to arise from the [ism330dhcx.c file](https://github.com/zephyrproject-rtos/zephyr/blob/63e7f106eac5047313b96bfe06377b54d450fd66/drivers/sensor/ism330dhcx/ism330dhcx.c#L684) and the driver is unable to read the sensor properly.

**Review by MaureenHelm — COMMENTED** [review]
Thanks for the fix. The code change looks good, but you need to amend your commit to fix the failed compliance check.
```
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 ab04334a5f52745992ddadddb929848ff5cd86e2: author email (Stefano Cottafavi <stefano.cottafavi@gmail.com>) needs to match one of the signed-off-by entries.
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 1: UC2 Commit message does not contain a 'Signed-off-by:' line
1: UC3 Commit title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Update ism330dhcx_spi.c"
```

**Comment by MaureenHelm** [comment]
Please address the failed compliance check:
```
Error: Merge commits not allowed, rebase instead
```

**Comment by kartben** [comment]
Hi @cooked  -- are you able to fix your branch by removing the merge commits which shouldn't be there? It's perfectly fine to force push your amended commits to your PR branch.

**Pull request closed without merging**
