### PR TITLE
tests: drivers: i2s: i2s_api: Update tests to use DEVICE_DT_GET

### PR DESCRIPTION
**Pull request by benjaminbjornsson**

### CODE REVIEW

**Review by galak — DISMISSED** [review]

**Comment by nandojve** [comment]
Hi @benjaminbjornsson ,

Please address CI errors.

**Comment by benjaminbjornsson** [comment]
> Hi @benjaminbjornsson ,
> 
> Please address CI errors.

Finally managed to solve it :)

**Review by nandojve — APPROVED** [review]

**Comment by galak** [comment]
@benjaminbjornsson any reason for DNM?

**Review by galak — CHANGES_REQUESTED** [review]
Do you need the dtsi changes to nodelabels in boards/arm and dts/arm/nxp/nxp_rt.dtsi.

Since you are using the `test_i2s_rx` and `test_i2s_tx` can we just add overlays using the nodelabels that nxp_rt already has, and atmel sam.

**Comment by benjaminbjornsson** [comment]
> @benjaminbjornsson any reason for DNM?

I realized that the Kconfig that is removed in this PR is used by two boards during board init. Need to have another look at this.

**Comment by benjaminbjornsson** [comment]
> @benjaminbjornsson do you intend on returning to this PR and addressing the comments from @galak?

@dleach02, unfortunately no. won't have time to make it in the foreseeable future.

**Pull request closed without merging**
