### PR TITLE
Regulator single threaded sleep clean up

### PR DESCRIPTION
**Pull request by rriveramcrus**
The regulator subsystem is required to support single and multithreaded platforms.

#63994 eliminates the need to use conditional preprocessor directives to call `k_busy_wait` on single threaded platforms.

### CODE REVIEW

**Review by kartben — APPROVED** [review]

**Comment by rriveramcrus** [comment]
>Looks like the commit messages should start with "Reverts commit ..." unless I am missing something?
Thanks for the cleanup!

Hey @kartben, e375d82 is the commit that fixes this issue, it is not being reverted. I will make amend my commit messages to make this more clear.

**Comment by kartben** [comment]
> >Looks like the commit messages should start with "Reverts commit ..." unless I am missing something?
> Thanks for the cleanup!
> 
> Hey @kartben, e375d827244cbbf141220ea684f4b06af30633f0 is the commit that fixes this issue, it is not being reverted. I will make amend my commit messages to make this more clear.

Ah right, don't bother though, I just read it again and it makes sense. It probably can be improved indeed but also fine as-is in the end :)

**Review by nashif — APPROVED** [review]

**Comment by kartben** [comment]
@rriveramcrus thanks for the update on the commit message - perfect! 👌

**Review by gmarull — APPROVED** [review]

**Review by aasinclair — APPROVED** [review]
Thanks :-)

**Review by nashif — APPROVED** [review]

**Pull request merged**
