### PR TITLE
drivers: input: MCUX GPT PPM input driver

### PR DESCRIPTION
**Pull request by bperseghetti**
MCUX GPT based driver sample for PPM capture as an input driver.

### CODE REVIEW

**Review by fabiobaltieri — CHANGES_REQUESTED** [review]
Hi, I'm a bit lost, why is this under input? IMX GPT should already be covered by `drivers/counter/counter_mcux_gpt.c`, why a specialized driver?

**Comment by PetervdPerk-NXP** [comment]
It's a driver that implements the RC PPM protocol but that needs a HW specific timer to decode the analog channels which get passed to the input subsystem based on the dts mapping.

I've updated the yaml to explain it a bit further

PPM input driver using NXP MCUX General-Purpose Timer (GPT) This driver implements the PPM protocol used in RC radio to send out analogue joystick and switches output.  The driver binds this to the Zephyr input system using INPUT_EV_CODES.

The following examples defines a a binding of 2 joysticks using 4 PPM channels
```
  &gpt5 {
    compatible = "nxp,gpt-ppm-input";
    pinctrl-0 = <&pinmux_gpt_ppm>;
    pinctrl-names = "default";
    capture-channel = <1>;
    right_stick_x {
      channel = <1>;
      label = "Right stick x";
      type = <INPUT_EV_ABS>;
      zephyr,code = <INPUT_ABS_RX>;
    };
    right_stick_y {
      channel = <2>;
      label = "Right stick y";
      type = <INPUT_EV_ABS>;
      zephyr,code = <INPUT_ABS_RY>;
    };
    left_stick_x {
      channel = <3>;
      label = "Left stick x";
      type = <INPUT_EV_ABS>;
      zephyr,code = <INPUT_ABS_X>;
    };
    left_stick_y {
      channel = <4>;
      label = "Left stick y";
      type = <INPUT_EV_ABS>;
      zephyr,code = <INPUT_ABS_Y>;
    };
  };
```

**Comment by fabiobaltieri** [comment]
> PPM input driver using NXP MCUX General-Purpose Timer (GPT) This driver implements the PPM protocol used in RC radio to send out analogue joystick and switches output. The driver binds this to the Zephyr input system using INPUT_EV_CODES.

Ok thanks, that makes a lot more sense to me now (somehow my brain was stuck on "pulse per minute"), so this is an input counterpart of https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/basic/servo_motor. That is really cool, but should not be implemented using the counter APIs rather than bound to a specific capture device implementation? That way we could have a single capture -> input device for RC PPM devices that works with any capture driver.

**Comment by fabiobaltieri** [comment]
> Using the counter API wouldn't be impossible. But current counter_driver_api is a bit lacking, no support for setting trigger type (rissing, falling, both), no predivider support, every alarm resets the interrupt, so you need to set it up again (that would skew the incoming data). Also the decoding has to happen in the ISR so we want to keep that as small as possible.

Right but then maybe there's some improvement to be done on the counter API? I'm admittedly fairly unfamiliar with it but if it's inadequate to read something simple as an RC PPM signal maybe we are doing something wrong. @nordic-krch any insight on this?

**Comment by bperseghetti** [comment]
> > Using the counter API wouldn't be impossible. But current counter_driver_api is a bit lacking, no support for setting trigger type (rissing, falling, both), no predivider support, every alarm resets the interrupt, so you need to set it up again (that would skew the incoming data). Also the decoding has to happen in the ISR so we want to keep that as small as possible.
> 
> Right but then maybe there's some improvement to be done on the counter API? I'm admittedly fairly unfamiliar with it but if it's inadequate to read something simple as an RC PPM signal maybe we are doing something wrong. @nordic-krch any insight on this?

I think until there is another vendor using PPM for their on their hardware it might be premature to attempt a "generalized counter/PPM".

If/when there is need/support from another vendor for their own PPM input, I think that's when extra time could be allocated to finding commonality and refining a system like that.  At that point we could/would also update ours accordingly.

**Comment by fabiobaltieri** [comment]
> Right but then maybe there's some improvement to be done on the counter API? I'm admittedly fairly unfamiliar with it but if it's inadequate to read something simple as an RC PPM signal maybe we are doing something wrong. @nordic-krch any insight on this?

@nordic-krch any feedback on this ^^?

**Comment by fabiobaltieri** [comment]
@bperseghetti sorry I realized just now while reviewing something else that the pulse with capture API is actually part of PWM, not counter, what you need should be exactly `CONFIG_PWM_CAPTURE`.

Is there an existing driver there that provides that functionality for the platform you are working on? If not, the right thing to do would be to port the capture code over to a driver for it, and use that API to implement the input stuff.

Reference:

https://github.com/zephyrproject-rtos/zephyr/blob/00e94614899ecb30e2ae101eacbfb3ee03b5289f/include/zephyr/drivers/pwm.h#L439-L443

**Comment by PetervdPerk-NXP** [comment]
So it seems indeed that CONFIG_PWM_CAPTURE can also capture pulse widths, and the API itself seems to be more advanced then the counter API as well.

However for PPM we're using a pin that's connected to the GPT module instead of the FlexPWM module. Reason is that GPT has a 32-bit counter and it's own clock whereas a PWM module typically shares it with other pins and precision tends to lower.

So that would mean would have to make a duplicate mcux-gpt timer driver just to talk to the PWM_CAPTURE API. I suppose we should wait for the counter_driver_api to improve.

For now we can just let the driver live under Cognipilot/Cerebri.

**Comment by fabiobaltieri** [comment]
> So that would mean would have to make a duplicate mcux-gpt timer driver just to talk to the PWM_CAPTURE API. I suppose we should wait for the counter_driver_api to improve.

I think that would be the right thing to do in this case.

**Comment by henrikbrixandersen** [comment]
> > So that would mean would have to make a duplicate mcux-gpt timer driver just to talk to the PWM_CAPTURE API.
> 
> I think that would be the right thing to do in this case, don't see a particular problem with a dedicated capture only gpt driver, seems like it's a functionality it provides so why not. @anangl @henrikbrixandersen
> 
> It's not like it'd be a new case for NXP (or other) platforms anyway, `flexspi` for example has both a `memc` and a `flash` driver.

Agreed. A separate MCUX GPT driver implementing the PWM capture API is certainly an option, just make sure to use a dedicated devicetree compatible for this.

**Comment by PetervdPerk-NXP** [comment]
Sure but it seems that both the pwm_capture and counter_driver_api are a kinda a duplicate of each-other anyhow. Whereas pwm_capture has a more advanced configuration features such as edge selection feature and counter_driver_api has an alarm feature. But alas they're mostly doing the same thing.

So duplicating GPT seems counterintuitive to me and would be bad from the maintenance perspective.

**Comment by sumitbatra-nxp** [comment]
How about this- 
1. We do necessary changes for capture functionality in the counter driver (including rising, falling edge, pre-divider)
2. Expose an API to set the callback on capture event
3. This Callback API triggers the RC PPM decode code in the input subsystem

**Comment by fabiobaltieri** [comment]
> * We do necessary changes for capture functionality in the counter driver (including rising, falling edge, pre-divider)

Why not use the PWM capture API? It already exists and seems like it does what you want already.

**Pull request closed without merging**
