### PR TITLE
NVS improvements

### PR DESCRIPTION
**Pull request by aurel32**
This patchset consists in minor improvements found while reviewing the NVS code. @Laczen, this is what I talked about in #8141.

### CODE REVIEW

**Comment by Laczen** [comment]
Hi @aurel32, thanks for the proposed changes. The changes are ok, only the CRC calculation I am a bit hesitating: changes to the ate structure (not putting the CRC at the end) would brake the calculation method.

**Comment by aurel32** [comment]
@Laczen, I guess we can check the offset of the CRC field at build time and error out if it's not anymore at the end. Would that work for you?

**Comment by nvlsianpu** [comment]
@Laczen
> I guess we can check the offset of the CRC field at build time and error out if it's not anymore at the end. Would that work for you?

I'm willing agree with @aurel32. Add static assertion, and  also cosmnent on struct nvs_ate::crc8 that it is expected to be the last one.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@Laczen @nvlsianpu please review...

**Comment by Laczen** [comment]
Hi @aurel32, I agree with the comment and static assert.

**Comment by aurel32** [comment]
I have just pushed a new version that has a built-in assert. I have also added a few other fixes or improvements found in the meantime.

**Review by Laczen — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]
looks good now - just fix the commit message and we can merge this.

**Comment by aurel32** [comment]
@Laczen, @nvlsianpu, thanks for the review. I have just pushed a new version without code change, just a wrapping of the lines in the last commit.

**Pull request merged**
