### PR TITLE
usb: device: remove USB H4 Bluetooth function and sample

### PR DESCRIPTION
**Pull request by jfischer-no**
There is very high confidence that this sample has no user or use on the host side (there is no implementation in btusb to handle it). Furthermore, the functionality can also be provided by the sample/bluetooth/hci_usb sample.

cherry-picked from #80985

### CODE REVIEW

**Review by cvinayak — CHANGES_REQUESTED** [review]
as the sample documentation states:
> Turn a Zephyr board into a USB H4 Bluetooth dongle (Linux/BlueZ only).

This sample covers `CONFIG_USB_DEVICE_BT_H4=y`

**Comment by jfischer-no** [comment]
> as the sample documentation states:
> 
> > Turn a Zephyr board into a USB H4 Bluetooth dongle (Linux/BlueZ only).


No matter what the documentation says, there is no support for this in btusb. The only purpose why it could be there was/is in fact served with hci_usb.

> This sample covers `CONFIG_USB_DEVICE_BT_H4=y`

Do you want me to remove it immediately and not deprecate with the legacy USB stack?

**Comment by cvinayak** [comment]
@jhedberg  I was of the belief that Bluez had support for this vendor specific btusb support that did a pass-through of all HCI types (including ISO data) over USB transport... is this is not true, I have no objection to remove this sample.

@Thalley you may want to make a comment here https://github.com/zephyrproject-rtos/zephyr/issues/44013 on the actions taken by this PR

**Comment by jhedberg** [comment]
> @jhedberg I was of the belief that Bluez had support for this vendor specific btusb support that did a pass-through of all HCI types (including ISO data) over USB transport... is this is not true, I have no objection to remove this sample.

This support isn't upstream in Linux/BlueZ, AFAIK. I did a quick check with @Vudentz and he was fine with this sample getting removed. I also got the impression that there might be some standard coming for this at some point, in which case the sample would either way need to be removed or overhauled.

**Comment by jfischer-no** [comment]
> I also got the impression that there might be some standard coming for this at some point, in which case the sample would either way need to be removed or overhauled.

https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/hci_usb was used for this, but this cannot be discussed openly.

**Review by Thalley — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> There is very high confidence that this sample has no user or use on the host side (there is no implementation in btusb to handle it).

...can we add analytics to west so we have data of what samples are used? 👀 (/me ducks)

**Comment by jfischer-no** [comment]
> > There is very high confidence that this sample has no user or use on the host side (there is no implementation in btusb to handle it).
> 
> ...can we add analytics to west so we have data of what samples are used? 👀 (/me ducks)

What is west? (⊙.☉)7

**Pull request merged**
