### PR TITLE
drivers: flash: nrf_qspi_nor: support read of sub-word lengths

### LINKED ISSUE #15289: Zephyr module uses `\` in path on windows when creating Kconfig files
The script `zephyr_modules.py` uses `os.path.abspath` when generating Kconfig include files for windows.

This causes the generated file to contain path like:
```
osource "c:\projets\..."
``` 
cause the load to fail in windows.

Instead posix style paths should be used.

### LINKED ISSUE #25289: mcuboot incompatible with Nordic QSPI flash driver
mcuboot does not work with the Nordic QSPI flash API because the `flash_area_read_is_empty()` extended API that is in:

* mcuboot: boot/zephyr/flash_map_extended.c
* zephyr: subsys/dfu/boot/mcuboot.c

is being invoked to verify that a single byte is uninitialized.  The Nordic QSPI flash API requires that all bus transactions be for a multiple of four bytes (this is a hardware limitation).

Consequently the read of an image state field fails, which causes mcuboot to panic.

Patching the call to read 4 bytes and only use the first allows mcuboot to work.  However, the proper fix is likely to be to special-case transfers of less than 4 bytes in the QSPI driver.

### PR DESCRIPTION
**Pull request by pabigot**
mcuboot and possibly other tools read single byte values to determine
the state of objects.  Rather than fail to do the read of values too
short for this peripheral detect the situation and read into a stack
buffer that meets the length criteria, and on success copy the data
into the provided buffer.

Fixes #25289

### CODE REVIEW

**Comment by pabigot** [comment]
Tested and confirmed this fixes the mcuboot issue identified in #25263

**Comment by pabigot** [comment]
Hadn't noticed this had no reviewers.  It may be worth considering for 2.3.0.

**Comment by pabigot** [comment]
This is wrong; it doesn't handle misaligned reads.  Defer in favor of backport of downstream patch.

**Comment by pabigot** [comment]
Reconsidering, this would fix mcuboot for 2.3.0; the downstream patch seems to have design questions that will delay it.

**Comment by sigvartmh** [comment]
I'm Okei with adding this upstream. If we can have a write patch downstream.

**Comment by pabigot** [comment]
To clarify: the "write patch" referenced works around a limitation of the QSPI peripheral that the source address for material to write must be located in RAM, not in flash.

A fix for that is needed, possibly added along with the alignment expectations in #23628 (i.e. that any address can be used for the source of data to write).  If we want this PR to supply a basic fix for mcuboot and be merged 2.3.0 it probably won't happen here.

**Review by nvlsianpu — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
