### PR TITLE
tests: flash: simulator: test preserving contents across `sys_reboot`

### PR DESCRIPTION
**Pull request by JordanYates**
Add a test for the flash simulator preserving memory across a `sys_reboot` through the use of memory regions.

### CODE REVIEW

**Comment by JordanYates** [comment]
> Question: this is only possible for devices that keep memory contents unmodified between resets?

Yes, if the memory contents are modified then this doesn't work.
It also doesn't work for the `native_sim` platforms because `sys_reboot` causes the sim to exit, not restart.
`mps2/an385` was chosen because it is a simulated platform that can also run twister coverage tests.
The coverage tests are the point of this for me, I want to coverage test libraries that interact with the reboot API and NVS.

**Comment by Laczen** [comment]
@JordanYates, the flash simulator also has an option to create the flash simulator in a memory region. This ensures that the location doesn't change.

**Comment by JordanYates** [comment]
> @JordanYates, the flash simulator also has an option to create the flash simulator in a memory region. This ensures that the location doesn't change.

The location changing was not the issue, but the behavior of not erasing the RAM can be obtained by using the memory region. PR has been updated to just be a test for that functionality

**Review by Laczen — APPROVED** [review]
LGTM

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
