### PR TITLE
net: shell: Added missing check for eth iface in "net iface" cmd

### PR DESCRIPTION
**Pull request by JanGeorgi**
checking if iface is ethernet, before calling ethernet api func

Signed-off-by: Jan Georgi <jan.georgi@lemonbeat.com>

### CODE REVIEW

**Review by jukkar — APPROVED** [review]
Indeed, good catch!

**Comment by pfalcon** [comment]
I'd like to mention that now there's literally 3 code chunks one after another, each guarded by `if (net_if_l2(iface) == &NET_L2_GET_NAME(ETHERNET))`. I'm not sure if it would make sense to merge them together. But then there's a small code size penalty due to these repetitive checks. But then it's in the shell code, which isn't supposed to be enabled in production, so again, hopefully it's all ok.

**Comment by jukkar** [comment]
> I'd like to mention that now there's literally 3 code chunks one after another, each guarded by `if (net_if_l2(iface) == &NET_L2_GET_NAME(ETHERNET))`. I'm not sure if it would make sense to merge them together.

I noticed that too but currently the `if` checks are enabled only for different Kconfig options. In order to keep the code blocks a bit more readable and separated, I think the current code is fine.

**Review by pfalcon — APPROVED** [review]

**Comment by jukkar** [comment]
@JanGeorgi there is some unrelated errors in sanitycheck. Could you rebase against latest upstream and resubmit?

**Pull request merged**
