### PR TITLE
samples: bluetooth: Enable PM on rd_rw612_bga

### PR DESCRIPTION
**Pull request by yeaissa**
Enable power management by default for rd_rw612_bga on peripheral_ht and central_ht samples

### CODE REVIEW

**Comment by Thalley** [comment]
Why on these specific samples?

**Comment by yeaissa** [comment]
> Why on these specific samples?
1) Those are the samples we run on the CI
2) We want to have some BLE samples with power management enabled as a demonstration

Thank you,

**Comment by Thalley** [comment]
> > Why on these specific samples?
> 
>     1. Those are the samples we run on the CI
> 
>     2. We want to have some BLE samples with power management enabled as a demonstration
> 
> 
> Thank you,

Thanks. 

Could you add that to the commit message? It's nice to have that sort of information in our git history :)

**Review by decsny — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by dleach02** [comment]
@jhedberg can you provide your review

**Pull request merged**
