### PR TITLE
Update NXP HAL to add mcux-sdk

### PR DESCRIPTION
**Pull request by mmahadevan108**
`mcux-sdk` is added to get SDK drivers from the `mcux-sdk` github repo

### CODE REVIEW

**Comment by hakehuang** [comment]
@mmahadevan108 besides the eth_mcux.c phy issue, dma driver alsow fails in rt series

```
2021-10-29 19:18:43,988 - twister - ERROR - Including boilerplate (Zephyr base): /home/shared/disk/zephyr_project/zephyr_phy/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer
-- Zephyr version: 2.7.99 (/home/shared/disk/zephyr_project/zephyr_phy/zephyr), build: v2.7.99-637-gcbb5139dceb5
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.0") found components: Interpreter
-- Found west (found suitable version "0.10.1", minimum required is "0.7.1")
-- Board: mimxrt1060_evk
-- Cache files will be written to: /home/ubuntu/.cache/zephyr
-- Using toolchain: zephyr 0.13.1 (/home/ubuntu/zephyr-sdk)
-- Found dtc: /home/ubuntu/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk.dts
-- Generated zephyr.dts: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/device_extern.h
-- Including generated dts.cmake file: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/dts.cmake
Parsing /home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer/Kconfig
Loaded configuration '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk_defconfig'
Merged configuration '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer/prj.conf'
Configuration saved to '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/.config'
Kconfig header saved to '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/ubuntu/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Found Git: /usr/bin/git (found version "2.17.1")
Load components for MIMXRT1062:
driver_common component is included.
driver_reset component is included.
device_CMSIS component is included.
CMSIS_Include_core_cm component is included.
driver_edma component is included.
CMake Error at /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/mcux-sdk/drivers/edma/driver_edma.cmake:14 (include):
  include could not find requested file:

    driver_dmamux
Call Stack (most recent call first):
  /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/hal_nxp.cmake:20 (include)
  /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/hal_nxp.cmake:74 (include_driver_ifdef)
  /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/CMakeLists.txt:94 (include)


driver_dmamux component is included.
driver_lpuart component is included.
driver_igpio component is included.
driver_cache_armv7_m7 component is included.
driver_xip_board_evkmimxrt1060 component is included.
-- Configuring incomplete, errors occurred!
See also "/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/CMakeFiles/CMakeOutput.log".
See also "/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/CMakeFiles/CMakeError.log".

```

**Comment by mmahadevan108** [comment]
> @mmahadevan108 besides the eth_mcux.c phy issue, dma driver alsow fails in rt series
> 
> ```
> 2021-10-29 19:18:43,988 - twister - ERROR - Including boilerplate (Zephyr base): /home/shared/disk/zephyr_project/zephyr_phy/zephyr/cmake/app/boilerplate.cmake
> -- Application: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer
> -- Zephyr version: 2.7.99 (/home/shared/disk/zephyr_project/zephyr_phy/zephyr), build: v2.7.99-637-gcbb5139dceb5
> -- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.0") found components: Interpreter
> -- Found west (found suitable version "0.10.1", minimum required is "0.7.1")
> -- Board: mimxrt1060_evk
> -- Cache files will be written to: /home/ubuntu/.cache/zephyr
> -- Using toolchain: zephyr 0.13.1 (/home/ubuntu/zephyr-sdk)
> -- Found dtc: /home/ubuntu/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
> -- Found BOARD.dts: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk.dts
> -- Generated zephyr.dts: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/zephyr.dts
> -- Generated devicetree_unfixed.h: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/devicetree_unfixed.h
> -- Generated device_extern.h: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/device_extern.h
> -- Including generated dts.cmake file: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/dts.cmake
> Parsing /home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer/Kconfig
> Loaded configuration '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk_defconfig'
> Merged configuration '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer/prj.conf'
> Configuration saved to '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/.config'
> Kconfig header saved to '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/autoconf.h'
> -- The C compiler identification is GNU 10.3.0
> -- The CXX compiler identification is GNU 10.3.0
> -- The ASM compiler identification is GNU
> -- Found assembler: /home/ubuntu/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
> -- Found Git: /usr/bin/git (found version "2.17.1")
> Load components for MIMXRT1062:
> driver_common component is included.
> driver_reset component is included.
> device_CMSIS component is included.
> CMSIS_Include_core_cm component is included.
> driver_edma component is included.
> CMake Error at /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/mcux-sdk/drivers/edma/driver_edma.cmake:14 (include):
>   include could not find requested file:
> 
>     driver_dmamux
> Call Stack (most recent call first):
>   /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/hal_nxp.cmake:20 (include)
>   /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/hal_nxp.cmake:74 (include_driver_ifdef)
>   /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/CMakeLists.txt:94 (include)
> 
> 
> driver_dmamux component is included.
> driver_lpuart component is included.
> driver_igpio component is included.
> driver_cache_armv7_m7 component is included.
> driver_xip_board_evkmimxrt1060 component is included.
> -- Configuring incomplete, errors occurred!
> See also "/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/CMakeFiles/CMakeOutput.log".
> See also "/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/CMakeFiles/CMakeError.log".
> ```

Thank you, this has been fixed by a change to HAL layer cmake file.

**Comment by hakehuang** [comment]
> > @mmahadevan108 besides the eth_mcux.c phy issue, dma driver alsow fails in rt series
> > ```
> > 2021-10-29 19:18:43,988 - twister - ERROR - Including boilerplate (Zephyr base): /home/shared/disk/zephyr_project/zephyr_phy/zephyr/cmake/app/boilerplate.cmake
> > -- Application: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer
> > -- Zephyr version: 2.7.99 (/home/shared/disk/zephyr_project/zephyr_phy/zephyr), build: v2.7.99-637-gcbb5139dceb5
> > -- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.0") found components: Interpreter
> > -- Found west (found suitable version "0.10.1", minimum required is "0.7.1")
> > -- Board: mimxrt1060_evk
> > -- Cache files will be written to: /home/ubuntu/.cache/zephyr
> > -- Using toolchain: zephyr 0.13.1 (/home/ubuntu/zephyr-sdk)
> > -- Found dtc: /home/ubuntu/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
> > -- Found BOARD.dts: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk.dts
> > -- Generated zephyr.dts: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/zephyr.dts
> > -- Generated devicetree_unfixed.h: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/devicetree_unfixed.h
> > -- Generated device_extern.h: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/device_extern.h
> > -- Including generated dts.cmake file: /home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/dts.cmake
> > Parsing /home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer/Kconfig
> > Loaded configuration '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/boards/arm/mimxrt1060_evk/mimxrt1060_evk_defconfig'
> > Merged configuration '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/tests/drivers/dma/loop_transfer/prj.conf'
> > Configuration saved to '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/.config'
> > Kconfig header saved to '/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/zephyr/include/generated/autoconf.h'
> > -- The C compiler identification is GNU 10.3.0
> > -- The CXX compiler identification is GNU 10.3.0
> > -- The ASM compiler identification is GNU
> > -- Found assembler: /home/ubuntu/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
> > -- Found Git: /usr/bin/git (found version "2.17.1")
> > Load components for MIMXRT1062:
> > driver_common component is included.
> > driver_reset component is included.
> > device_CMSIS component is included.
> > CMSIS_Include_core_cm component is included.
> > driver_edma component is included.
> > CMake Error at /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/mcux-sdk/drivers/edma/driver_edma.cmake:14 (include):
> >   include could not find requested file:
> > 
> >     driver_dmamux
> > Call Stack (most recent call first):
> >   /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/hal_nxp.cmake:20 (include)
> >   /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/hal_nxp.cmake:74 (include_driver_ifdef)
> >   /home/shared/disk/zephyr_project/zephyr_phy/modules/hal/nxp/mcux/CMakeLists.txt:94 (include)
> > 
> > 
> > driver_dmamux component is included.
> > driver_lpuart component is included.
> > driver_igpio component is included.
> > driver_cache_armv7_m7 component is included.
> > driver_xip_board_evkmimxrt1060 component is included.
> > -- Configuring incomplete, errors occurred!
> > See also "/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/CMakeFiles/CMakeOutput.log".
> > See also "/home/shared/disk/zephyr_project/zephyr_phy/zephyr/twister-out/mimxrt1060_evk/tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer/CMakeFiles/CMakeError.log".
> > ```
> 
> Thank you, this has been fixed by a change to HAL layer cmake file.

@mmahadevan108 , Thanks, CI testing will feedback tomorrow.

**Comment by hakehuang** [comment]
@mmahadevan108  still has failure isse on flash driver with re series, in my rt1060 platform, all flash application fails
```
E: Halting system
E: ***** HARD FAULT *****
E:   Debug event
E: r0/a1:  0x00000000  r1/a2:  0x80001158  r2/a3:  0x800007dc
E: r3/a4:  0x00000c00 r12/ip:  0x150b0000 r14/lr:  0x600045d3
E:  xpsr:  0x01000000
E: Faulting instruction address (r15/pc): 0x600045da
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x800005b8 (main)
E: Halting system
```

**Comment by mmahadevan108** [comment]
> @mmahadevan108 still has failure isse on flash driver with re series, in my rt1060 platform, all flash application fails tests/drivers/flash tests/subsys/fs/littlefs
> 
> ```
> E: Halting system
> E: ***** HARD FAULT *****
> E:   Debug event
> E: r0/a1:  0x00000000  r1/a2:  0x80001158  r2/a3:  0x800007dc
> E: r3/a4:  0x00000c00 r12/ip:  0x150b0000 r14/lr:  0x600045d3
> E:  xpsr:  0x01000000
> E: Faulting instruction address (r15/pc): 0x600045da
> E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
> E: Current thread: 0x800005b8 (main)
> E: Halting system
> ```

@hakehuang Thank you for your testing. I have fixed the issue and update the HAL PR.

**Review by galak — CHANGES_REQUESTED** [review]
there is already a devicetree standard on how ethernet phy's should be represented, see:

https://git.kernel.org/pub/scm/linux/kernel/git/devicetree/devicetree-rebasing.git/tree/Bindings/net/ethernet-phy.yaml

**Comment by mmahadevan108** [comment]
@galak I have simplified updates to the `eth_mcux` driver to delete the device tree changes.

**Comment by hakehuang** [comment]
> there is already a devicetree standard on how ethernet phy's should be represented, see:
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/devicetree/devicetree-rebasing.git/tree/Bindings/net/ethernet-phy.yaml

@galak linux phy structure requires to add phy driver for each type of phy and does not have hal layer, whereas in zephyr, the phy driver are from HAL layer usually, and the basic idea is the same just has different, just with different details. Do you think it is necessary to have a discussion topic on how zephyr choose the devicetree structure?

**Comment by mmahadevan108** [comment]
@galak I have update the PR to not have changes to the device tree. Can you take a look.

**Review by galak — APPROVED** [review]

**Comment by dleach02** [comment]
@hakehuang, can you run a test pass with this PR before we move to merge and report status here?

**Review by danieldegrasse — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
Congrats, great to see this happening!

> @hakehuang, can you run a test pass with this PR before we move to merge and report status here?

Adding the DNM label until this is complete.

**Comment by dleach02** [comment]
@MaureenHelm, @hakehuang reported internally that all tests are now passing. But I'll let him officially report it on this PR.

**Comment by hakehuang** [comment]
> @MaureenHelm, @hakehuang reported internally that all tests are now passing. But I'll let him officially report it on this PR.

@MaureenHelm , @dleach02 , @mmahadevan108 , all regression test PASS with latest change

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
