### PR TITLE
Make generated *.ld files deterministic

### PR DESCRIPTION
**Pull request by marc-hb**
gen_app_partitions.py: make generated/app_smem_*.ld files deterministic
gen_relocate_app.py: make generated/linker_relocate.ld deterministic

Dictionaries are not ordered in Python 3.5 and before, so building twice
in a row could lead to a different sections/partitions order, different
build/zephyr/include/generated/linker_relocate.d, code_relocation.c,
build/zephyr/include/generated/app_smem_*.ld and different binaries.

### CODE REVIEW

**Comment by marc-hb** [comment]
cc @varun-sha , @AdithyaBaglody (can't be added as reviewers)

**Review by tyrantlizard77 — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
Looks ok.
If this is to be merged, I'd like the commit bodies to contain some text that reflects the changes in the patches (not just the rationale)

**Comment by marc-hb** [comment]
> 'd like the commit bodies to contain some text that reflects the changes in the patches (not just the rationale)

Done. No code change.

**Review by wentongwu — APPROVED** [review]

**Comment by sigvartmh** [comment]
Quick question why is sort used instead of an actual ordered dict?  https://docs.python.org/3/library/collections.html#collections.OrderedDict

**Comment by marc-hb** [comment]
Thanks @sigvartmh for the attention to detail and post-merge review, really appreciated.

> Quick question why is sort used instead of an actual ordered dict?

Good question, both approaches an be used. When there's only one output function sorting is easier so that's what I did here for gen_app_partitions.py. In other cases I've used an OrderedDict.

> partsorted = OrderedDict(sorted(partitions.items(), key=lambda x: x[1][SZ], reverse=True))

I tested again and this doesn't work with Python 3.5, investigating why now. You're right I should have either fixed or removed this and explained why it doesn't work.

PS: @ulfalizer is on vacation

**Comment by marc-hb** [comment]
> partsorted = OrderedDict(sorted(partitions.items(), key=lambda x: x[1][SZ], reverse=True))

This commit is much worse than a no-op: I missed and broke that decreasing size order implemented by @dcpleung in PR #14243. Apologies.

Full explanation, revert and proper determism fix in PR #17132, thanks in advance for reviewing quickly.

**Pull request merged**
