### PR TITLE
doc: add python pip requirements.txt

### PR DESCRIPTION
**Pull request by nashif**
List all required modules in one file and just call pip with this file to
install all needed modules instead of listing them individually.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by dbkinder — DISMISSED** [review]
Looks OK,  but I haven't tested myself (what happens if some of these packages are already installed in some other path, e.g., user vs system).  Need to fix the commit message line length :)

**Review by pfalcon — CHANGES_REQUESTED** [review]
May I suggest following change: requirements for docs generation should be split from other dependencies. And I think that doc generation instructions should suggest usage of virtualenv (or we standardize on modern version of Python3, venv). Reason: many distro already come with e.g. distutils installed, and oftentimes, people have a particular version of Sphinx installed from distro packages too. Forcing updates to those packages installed globally may break distro/other projects.

**Comment by nashif** [comment]
> May I suggest following change: requirements for docs generation should be split from other dependencies. 

Why? We need to have everything installed for developers to verify their changes and that includes documentation, so I would really prefer to just install everything needed for development in one shot and not have to sets of requirements and add more confusion. 

Using virtual environment would be nice but right now I would consider it as a second step after this, my change just moves things into one file, we have been asking for a specific version of sphinx already.

**Review by dbkinder — DISMISSED** [review]
There are more python/pip install packages being proposed in other PRs ( #820 for example) that need to be coordinated with this change.

**Pull request merged**
