### PR TITLE
To improve redabiltiy of BT_DATA helper macro.

### PR DESCRIPTION
**Pull request by tomasApo**
I swapped the `data_len` and `data fields`.

### CODE REVIEW

**Review by hermabe — CHANGES_REQUESTED** [review]
I am not sure how this improves the readability.

Also, this is invalid in C++ where the designators have to be in declaration order (https://eel.is/c++draft/diff.iso#diff.dcl-9).

**Comment by tomasApo** [comment]
> I am not sure how this improves the readability.
 
It improves readability by aligning the order of the macro parameters `_type`, `_data`, `_data_len`  with the designators  `.type`, `.data_len,`, `.data`. So struct members are initialized in the same order as they are declared.

> Also, this is invalid in C++ where the designators have to be in declaration order (https://eel.is/c++draft/diff.iso#diff.dcl-9).

Apologies @hermabe, I might be missing something. Doesn't this strengthen the commit request as now they are in declaration order so its more compatible with C++?

**Comment by jhedberg** [comment]
> Apologies @hermabe, I might be missing something. Doesn't this strengthen the commit request as now they are in declaration order so its more compatible with C++?

The definition of the `bt_data` struct is here:
https://github.com/zephyrproject-rtos/zephyr/blob/c0bb064d4e38d11d4df9e0090619c832c1a267a5/include/zephyr/bluetooth/bluetooth.h#L439-L443

I think you might be confusing with the macro parameter order? (I don't think C++ has any issue with that)

**Comment by tomasApo** [comment]
> The definition of the `bt_data` struct is here:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/c0bb064d4e38d11d4df9e0090619c832c1a267a5/include/zephyr/bluetooth/bluetooth.h#L439-L443
> 
> I think you might be confusing with the macro parameter order? (I don't think C++ has any issue with that)

Yes I was confusing it with the macro parameter. Thank you for your patience

**Pull request closed without merging**
