### PR TITLE
Minor fix for Windows setup instructions

### PR DESCRIPTION
**Pull request by yerpj**

### CODE REVIEW

**Review by dbkinder — CHANGES_REQUESTED** [review]
While the change to the .rst content is fine, the commit message has issues.  If you look at the PR summary in GitHub you'll see that test have failed.  Click on the shippable "details" and you'll eventually find that the group 3 tests have failed (that's the group where documentation is built) and the errors say:

```
 Failures
Commit Message / Documentation / Coding Style / gitlint / Commit message style

failure: commit message error on range: origin/master..HEAD

1: UC2 Body does not contain a 'Signed-Off-By' line
1: UC3 Title does not follow [subsystem]: [subject]: "- installation script updated according to previous steps"
3: B6 Body message is missing
```

So the signed-off-by is still missing. The commit title must start with a subsystem name, something like "doc: fix windows install instructions". A good title should fix the "missing body" error, but you could add a short message saying something like, "As written, the instructions incorrectly assume you're in the zephyr directory and won't find the scripts folder."

**Comment by dbkinder** [comment]
shippable is still unhappy with the commit message:

    1: UC2 Body does not contain a 'Signed-Off-By' line
    1: UC3 Title does not follow [subsystem]: [subject]: "- installation script updated according to previous steps"
    3: B6 Body message is missing

**Comment by pfalcon** [comment]
@yerpj: Please squash everything down to a single commit (with the correct message and its length).

Actually, I'd recommend to put "cd zephyr" somewhere there. @carlescufi : Maybe you (or other of your folks caring about Windows) could do that.

**Comment by carlescufi** [comment]
@yerpj agreed with @pfalcon, please add "$ cd zephyr" instead of adding zephyr/ to the command

**Pull request closed without merging**
