### PR TITLE
eeprom_at2x: Support at24c04, at24c08 and at24c16

### PR DESCRIPTION
**Pull request by findlayfeng**
at24c04, at24c08 and at24c16 have a special data address representation,
the high-order bits are inserted into the device address.

Signed-off-by: fengch <i@fengch.me>

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
@findlayfeng Thank you for your contribution! I see that you have added support for multiple new address widths in one commit. Could you please split them up into separate commits in order to improve traceability and make it easier to assess your proposed changes?

Could you also please - just on this PR - provide DTS examples for how you would configure these EEPROMs in the device tree?

Just out of curiosity, do you have a board equipped with all these different EEPROMS that you intend to run Zephyr on?

**Comment by KwonTae-young** [comment]
I recently tried `AT24C04`.
I applied this PR and did the device-tree as below and it worked fine.
```
&i2c1 {
	clock-frequency = <400000>;
	status = "ok";

	eeprom: eeprom@50 {
		compatible = "atmel,at24";
		reg = <0x50>;
		label = "EEPROM";
		size = <512>;
		pagesize = <32>;
		address-width = <9>;
		timeout = <5>;
	};
};
```

**Comment by kurddt** [comment]
@henrikbrixandersen Since the board I'm working on use on `AT24C04` compatible chip, I'm interested in updating this PR in order to see it merged someday. 

Concerning your previous comment I don't really see how this PR could be split in several commits for each address widths since the implementation of the new supported width (9, 10, 11) is quite generic.

Also the current implementation seems to remove the support of the 16 address width, I will see to correct that

**Comment by kurddt** [comment]
Actually I'm not convinced that using the address width is the way to go.

Those chips seems to have been made so that you address two at24c04 chip than one at24c08. Using the size of the device and the address width (8 or 16) is enough to determine if the device uses several addresses (or use several physical component)

**Comment by henrikbrixandersen** [comment]
Thank you for your pull request. I am closing it in favour of #29046, which allows accessing multiple AT24cXX devices as one, larger EEPROM.

**Pull request closed without merging**
