### PR TITLE
drivers: can: reset statistics when starting the CAN controller

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Reset CAN controller statistics when starting the CAN controller.

### CODE REVIEW

**Review by alexanderwachter — COMMENTED** [review]
wouldn't it be nicer to have an inline function instead of a macro?

**Comment by henrikbrixandersen** [comment]
> wouldn't it be nicer to have an inline function instead of a macro?

Please be more specific on why you think an inline function would be "nicer"?

The new macro follows the naming scheme of the existing `CAN_STATS` macros and can be defined to nothing when `CONFIG_STATS` is not enabled.

**Review by martinjaeger — DISMISSED** [review]
LGTM

**Comment by henrikbrixandersen** [comment]
Removed dangling `\` on `CAN_STATS_RESET(dev_)`.

**Review by martinjaeger — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by str4t0m — APPROVED** [review]

**Pull request merged**
