### PR TITLE
Fixed microbit v2 lsm303agr irq pin

### LINKED ISSUE #44622: Microbit v2 board dts file for lsm303agr int line
There is a bug on the microbit v2 board on bbc_microbit_v2.dts file: 

line 104 and 112 needs to be 

`irq-gpios = <&gpio0 25 (GPIO_PULL_UP | GPIO_ACTIVE_LOW)>;`
**NOT**
`irq-gpios = <&gpio0 25 GPIO_ACTIVE_HIGH>;`

someone missed the change from v1.5.
As you can see here, the NOR gate on the **Motion Sensor** is active low [https://github.com/microbit-foundation/microbit-v2-hardware/blob/main/V2/MicroBit_V2.0.0_S_schematic.PDF].

**To Reproduce**
1. Create a Zephyr project for microbit v2 board
2. Config interrupts for lis2dh (driver for lsm303agr) on proj.conf 
```
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LIS2DH_OPER_MODE_HIGH_RES=y
CONFIG_LIS2DH_ACCEL_RANGE_2G=y
CONFIG_LIS2DH_ODR_6=y
CONFIG_LIS2DH_TRIGGER_GLOBAL_THREAD=y
CONFIG_GPIO=y
```
3. There is another bug in v2.20 boards on interface IC firmware for interrupt line. The lsm303agr and the interface IC share the same line for I2C interrupts. The line remains low after the boot due to an unhandled interrupt, so you have to issue a read_response command [https://tech.microbit.org/software/spec-i2c-protocol/#readresponse] to the interface IC to release the line.
```
    int nack;   
    uint8_t value[2] = {0x10, 0x01};
    uint8_t resp[16];  
    nack=i2c_write(i2c, &value, 2, 0x70);
    if (nack!=0)
	{
		printf("Error writing i2c slave\n");
	}	

    nack=i2c_read(i2c, &resp, 11, 0x70);
    if (nack!=0)
	{
		printf("Error reading i2c slave\n");
	}	
```
5. After releasing the line you can see that it needs a pullup and is active low.

**Expected behavior**
GPIO should be configured as active low with pullup resistor as described by the schematic.

**Impact**
You cannot interact with the onboard lsm303agr and receive DRDY or other interrupts.

**Environment**
 - Micro:bit v2.20 board, 
 - Zephyr 2.20701.220216
 - Platformio

### PR DESCRIPTION
**Pull request by liliumjsn**
As you can see here, the NOR gate on the Motion Sensor is active low [https://github.com/microbit-foundation/microbit-v2-hardware/blob/main/V2/MicroBit_V2.0.0_S_schematic.PDF].

Fixes: #44622

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
This looks correct to me from a quick look at the schematic linked in the PR description:



U2 in this case is the nRF52833.



@LingaoM could you please review and approve if you agree?

**Review by mbolivar-nordic — DISMISSED** [review]

**Review by LingaoM — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
@liliumjsn please address the compliance failure:

```
040dd2c449c64ef7c77424bb79b22edd1259d4ac: author email (Lilium JSN <karapatisjim@gmail.com>) needs to match one of the signed-off-by entries.
```

**Comment by mbolivar-nordic** [comment]
@liliumjsn do you plan on returning to this PR?

**Comment by liliumjsn** [comment]
I don't think that I'm gonna chase down twister failures for such a simple fix.

**Comment by mbolivar-nordic** [comment]
@liliumjsn the compliance error is a problem with your commit log, that's all.

**Comment by mbolivar-nordic** [comment]
@liliumjsn please fix the compliance errors; everything else is green on rebase.

```

b82da75fa86b34016e592ed753cb45975db12f68: author email (Lilium JSN <karapatisjim@gmail.com>) needs to match one of the signed-off-by entries.
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

1: UC2 Body does not contain a 'Signed-off-by:' line
1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Fixed microbit v2 lsm303agr irq pin"
```

**Pull request closed without merging**
