### PR TITLE
Allow incoming network traffic throttling

### PR DESCRIPTION
**Pull request by jukkar**
There has been long discussion about throttling incoming network traffic, for example here #27662. Right now it is easy to prevent device functioning properly if the device receives a lot of incoming network traffic.

This PR proposes one option how a throttling could be done. The idea is that supporting network device driver could define a "throttler" that could be configured by the upper network stack. The throttler could be configured with some limits, like bytes/sec and if the limit would be crossed, the device driver could start to throttle the traffic automatically. It would also be possible to manually enable/disable incoming network traffic if the device is flooded with data.

I added a example code to the native_sim Ethernet driver, it does not do anything but shows the general idea.

I am collecting feedback here whether we need such a feature or not, and does the API look usable. Please take a look and comment.

### CODE REVIEW

**Comment by pdgendt** [comment]
Should it be the responsibility of the individual drivers to each implement this if desired? I don't actually see it being used currently in the `native_sim` driver...

Can we keep this as a part of the `struct iface`, where the throttling could be done when passing from/to drivers to/from upper layers, maybe using some socket handling?

**Comment by jukkar** [comment]
> Should it be the responsibility of the individual drivers to each implement this if desired? I don't actually see it being used currently in the `native_sim` driver...

Yes, that was the point. The implementation would be done by the driver. I did not bother to actually implement the functionality to native_sim driver, just added stubs there so the usage of them could be seen.


> Can we keep this as a part of the `struct net_if`, where the throttling could be done when passing from/to drivers to/from upper layers, maybe using some socket handling?

Perhaps, but if the driver does not have support for throttling, then placing the code to net_if would be kind of pointless and just using extra memory.

**Comment by pdgendt** [comment]
> > Should it be the responsibility of the individual drivers to each implement this if desired? I don't actually see it being used currently in the `native_sim` driver...
> 
> Yes, that was the point. The implementation would be done by the driver. I did not bother to actually implement the functionality to native_sim driver, just added stubs there so the usage of them could be seen.

If the throttling is as "simple" as dropping packets, I think the overhead could be kept small and useful for testing purposes. A driver could report the throttling capability to the interface and fallback to the software implementation if not available.
 
> > Can we keep this as a part of the `struct net_if`, where the throttling could be done when passing from/to drivers to/from upper layers, maybe using some socket handling?
> 
> Perhaps, but if the driver does not have support for throttling, then placing the code to net_if would be kind of pointless and just using extra memory.

True, but having to add some boilerplate code to drivers that do have support is the other tradeoff. I guess either option has it's up/downsides.

**Comment by cfriedt** [comment]
Is there a "standard" for this type of thing? It would be nice to simply follow an established pattern.

**Comment by jukkar** [comment]
> If the throttling is as "simple" as dropping packets, I think the overhead could be kept small and useful for testing purposes. A driver could report the throttling capability to the interface and fallback to the software implementation if not available.

Throttling could mean dropping packets, or programming the chip not to accept packets etc. Anyway IMHO something quite low level so that we would not consume too much resources from the upper level stack.
I was not really thinking about testing here but a real life scenario where the resource constrained device is unable to cope with the amount of incoming traffic. Which then causes problems in upper stack like out of memory issues, general slowness of the device etc. This is probably not very typical scenario so if people think that this is not worth pursuing, then that is a ok result too. I am trying to get feedback here for a problem described in at least one issue (I think I have seen discussion in some other venue but could find one this one report).

> True, but having to add some boilerplate code to drivers that do have support is the other tradeoff. I guess either option has it's up/downsides.

There could be API for that. For example driver would know how large packet it just got, it could feed that number to an API that could tell whether the packet should be dropped.

> Is there a "standard" for this type of thing? It would be nice to simply follow an established pattern.

Dunno, Linux has various QoS options https://superuser.com/questions/66574/how-to-throttle-bandwidth-on-a-linux-network-interface but I think those are kind of overkill for us.

**Pull request closed without merging**
