### PR TITLE
Bluetooth: Audio: Update audio location definitions

### PR DESCRIPTION
**Pull request by 0bijian0**
The meaning of bit0 in the audio location bitmap will change to mono audio, so we update the audio location macro and releated test cases.

Refer to BT SIG ES-23615.

### CODE REVIEW

**Review by MariuszSkamra — DISMISSED** [review]

**Review by larsgk — DISMISSED** [review]

**Comment by Thalley** [comment]
This should not be merged before the change to location fields are published (and fully accepted; seems like there are still some discussions on how to deal with it).

**Comment by 0bijian0** [comment]
> This should not be merged before the change to location fields are published (and fully accepted; seems like there are still some discussions on how to deal with it).
ok

**Comment by Thalley** [comment]
See https://bluetooth.atlassian.net/browse/ES-22266 and https://bluetooth.atlassian.net/browse/ES-22952 for the ongoing discussion w.r.t. the change in location

**Comment by 0bijian0** [comment]
> See https://bluetooth.atlassian.net/browse/ES-22266 and https://bluetooth.atlassian.net/browse/ES-22952 for the ongoing discussion w.r.t. the change in location

The audio location 0x00000000 will be used for mono audio in "E22266_CR_R09_ASA.docx", shall we merge this PR?

**Comment by Thalley** [comment]
> > See https://bluetooth.atlassian.net/browse/ES-22266 and https://bluetooth.atlassian.net/browse/ES-22952 for the ongoing discussion w.r.t. the change in location
> 
> The audio location 0x00000000 will be used for mono audio in "E22266_CR_R09_ASA.docx", shall we merge this PR?

No, because the erratum has not yet been accepted or incorporated.

**Comment by 0bijian0** [comment]
> 



> > > See https://bluetooth.atlassian.net/browse/ES-22266 and https://bluetooth.atlassian.net/browse/ES-22952 for the ongoing discussion w.r.t. the change in location
> > 
> > 
> > The audio location 0x00000000 will be used for mono audio in "E22266_CR_R09_ASA.docx", shall we merge this PR?
> 
> No, because the erratum has not yet been accepted or incorporated.

get

**Comment by carlescufi** [comment]
@0bijian0 please rebase

**Pull request closed without merging**
