### PR TITLE
ext: nordic: Move configuration from cmake to cpp

### PR DESCRIPTION
**Pull request by SebastianBoe**
There are several issues with this driver. Firstly, it is polluting
the global space of defines instead of just locally where it is
needed. Also, it is using CMakeLists.txt for something that can be done
with the preprocessor. As a general principle, it is better to do
something with the preprocessor than with build script code.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by KaSroka** [comment]
This defines will be used by several files in new 15.4 driver.

**Comment by hubertmis** [comment]
The purpose of `nrf_drv_radio802154_config.h` file is to allow project-specific configuration of the driver. Application developer may overwrite any of default values defined in this file with project-specific value.
In legacy driver implementation that is present in Zephyr repo (all functions implemented in the `nrf_drv_radio802154.c` file) only this single file uses project-specific constants defined in `nrf_drv_radio802154_config.h`. But in current implementation (https://github.com/NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver) these defines are used in a few files related to the driver (all in the driver directory). Moreover, current implementation changed define name to include module-related prefix `NRF_DRV_RADIO802154_` instead of `RADIO_`.
@SebastianBoe, I'm not sure if this comment addresses your concerns. I'm not a Zephyr expert and I'm not sure what is the problem here :)

**Comment by SebastianBoe** [comment]
> This defines will be used by several files in new 15.4 driver.

Okay, what about a private header file then, like this https://github.com/zephyrproject-rtos/zephyr/pull/5222/commits/ad8be82339516ab391bddd8cc8b5984e29aa9b80?

**Comment by SebastianBoe** [comment]
The problem is doing stuff in the build system that should be done with the preprocessor.

It is a goal for the build system to be as simple as possible. I want to get this right here,
so we don't copy this technique everywhere.

@KaSroka , @hubertmis : What do you think about the proposed patch?

If you wish, you could decline this PR and do an equivalent patch upstream to avoid conflicts.

**Comment by KaSroka** [comment]
It looks ok, to be honest I don't know why this config was in CMakeLists.txt

**Comment by hubertmis** [comment]
New patch looks very good. It should be easy to use new file with new driver config approach after merging upstream driver to zephyr project.

**Comment by SebastianBoe** [comment]
All right, I'll close this PR then.

Thanks for the feedback!

**Pull request closed without merging**
