### PR TITLE
Bluetooth: Controller: Fix reschedule of ticker with yield, re-enable bsim audio tests using ext_adv

### PR DESCRIPTION
**Pull request by cvinayak**
Fix reschedule for ticker that yield so that it is placed
in the middle of its available ticks slot window duration
after the overlap. This will help avoid the rescheduled
ticker from getting into a livelock of being overlapped
at every interval.

Fixes commit e1cd5ba77f59 ("Bluetooth: Controller: Fix to
reschedule after overlap when yielding").

Remove a duplicated advertising set in the CAP acceptor babblesim
test. The advertising set is configured in test_start_adv.

The BSIM test for the CAP acceptor used legacy instead
of extended advertising.

This also adds the required advertising data and validation
on the CAP initiator and CAP commander.

This PR also reverts commit 18119e8f6e3d735f5fbe09f443b02ef8fdb285f5 and 1320b3dd6616c517c6de382163eab21b69b417aa
Audio tests are enabled back, but change to random number seed is retained for the multiple identity test.

### CODE REVIEW

**Comment by valeriosetti** [comment]
FYI new AC tests commented out in #82217 with [this commit](https://github.com/valeriosetti/zephyr/commit/43dd9c173f8d253dd484282bd5e911b21730b095)

**Comment by Thalley** [comment]
@cvinayak this PR is doing a lot more than reverting a specific commit now. Can you update the PR title and description?

**Review by Thalley — APPROVED** [review]
LGTM assuming that it uses the newest version of the commit from https://github.com/zephyrproject-rtos/zephyr/pull/80840 :)

**Comment by cvinayak** [comment]
> LGTM assuming that it uses the newest version of the commit from #80840 :)

Did a local fetch, rebase and diff of the commit -> appears same. #80840 can be rebase after this PR gets merged so that #80840 will appear as "merged" in github.

**Review by kruithofa — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
