### PR TITLE
dts: qemu_crotex_m3: select uart2 for uart-pipe in case of bluetooth

### PR DESCRIPTION
**Pull request by SavinayDharmappa**
patch selects uart 2 instance incase of CONFIG_BLUETOOTH enabled.
This change is required for qemu as tester app with qemu.conf was
using CONFIG_UART_PIPE_ON_DEV_NAME="UART2". This is a fix for
Jira ZEP-2412.

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Is there a reason we can't just change the test to use uart1?

**Comment by jukkar** [comment]
Note that there is a typo in commit subject, s/crotex/cortex/
Also follow syntax for Jira entries, so "Jira: ZEP-2412" instead of the last sentence.

**Comment by SavinayDharmappa** [comment]
@galak  can you refer to following commits ea8ca, bab3. It has the reason. I didn't understood there commit message completely. If there is a better solution let me know

**Comment by galak** [comment]
@SavinayDharmappa which commit?

**Comment by galak** [comment]
Can you change tests/bluetooth/tester/qemu.conf:

CONFIG_UART_PIPE_ON_DEV_NAME="UART_2"

to 

CONFIG_UART_PIPE_ON_DEV_NAME="UART_1"

**Comment by SavinayDharmappa** [comment]
@galak  
commit ea8ca7d400ffd7835ba47fe1e571075fad4db49d
Author: Mariusz Skamra <mariusz.skamra@tieto.com>
Date:   Fri Mar 24 10:09:08 2017 +0100

    Bluetooth: tester: Fix UART issue on qemu

    This fixes an issue introduced by bab3aafa2d1d687c0fa4d67bfdffa44fb8f66078,
    which changed the default value of UART_PIPE_ON_DEV_NAME to the same
    used by BLUETOOTH_UART_ON_DEV_NAME. Due to this, the BTP and HCI were using
    the same UART.

    Change-Id: Ib59819e49610f28f4c89c0304d024bb1b6aa506a
    Signed-off-by: Mariusz Skamra <mariusz.skamra@tieto.com>

**Comment by galak** [comment]
I see, what if we change uart-pipe to uart2 always, what happens than?

**Comment by SavinayDharmappa** [comment]
@galak  As per my understanding uart2 is for uart-pipe when BT is used. In other case uart1 is used for uart-pipe.
commit bab3aafa2d1d687c0fa4d67bfdffa44fb8f66078
Author: Richard Peters <mail@richardpeters.de>
Date:   Thu Feb 9 01:13:47 2017 +0100

    qemu_cortex_m3: fixed network connectivity

    The wrong UART was set on for the qemu_cortex_m3 slip (uart pipe) device

    Change-Id: If6d6af0f32ef02ccc559cd1fff90ea499cc378c4
    Signed-off-by: Richard Peters <mail@richardpeters.de>

**Comment by galak** [comment]
Take a look at PR #926 and lets see if that solution works.

**Comment by rmstoi** [comment]
PR #926 does not work. With PR #914 tester works.

**Comment by galak** [comment]
@rmstoi can you explain how to test

**Comment by SavinayDharmappa** [comment]
@galak can we merge this patch. As other patch is not working as bluetooth tester app on Qemu is broken which is blocking ruslan

**Comment by galak** [comment]
Looks like we can make progress with #926 so closing this out.

**Pull request closed without merging**
