### PR TITLE
i3c: add sedi i3c driver

### PR DESCRIPTION
**Pull request by leifuzhao**
This gives initial support to the design ware i3c controller used in intel ish.

### CODE REVIEW

**Review by XenuIsWatching — CHANGES_REQUESTED** [review]
Theres many many issues here with this PR... I'm not sure where to begin

If this really is the snps designware i3c as the description implies, then this is a duplicate of https://github.com/zephyrproject-rtos/zephyr/pull/64528

**Review by gmarull — CHANGES_REQUESTED** [review]
work should converge to https://github.com/zephyrproject-rtos/zephyr/pull/64528, agreed this proposal has quite a few issues

**Comment by leifuzhao** [comment]
> Theres many many issues here with this PR... I'm not sure where to begin
> 
> If this really is the snps designware i3c as the description implies, then this is a duplicate of #64528

The zephyr driver has two modes. One is native driver mode, the other is the HAL mode, the two mode drivers could co-exist. The ISH drivers use HAL mode, for example, the previous upstreamed i2c driver uses sedi HAL to perform low level operation and config while there is another native i2c driver for the same designware  i2c IP. The ISH i3c driver follows the same way with other upstreamed ISH drivers such as i2c driver. So this PR could co-exist with PR #64528, they fulfill different job.

**Comment by gmarull** [comment]
> > Theres many many issues here with this PR... I'm not sure where to begin
> > If this really is the snps designware i3c as the description implies, then this is a duplicate of #64528
> 
> The zephyr driver has two modes. One is native driver mode, the other is the HAL mode, the two mode drivers could co-exist. The ISH drivers use HAL mode, for example, the previous upstreamed i2c driver uses sedi HAL to perform low level operation and config while there is another native i2c driver for the same designware i2c IP. The ISH i3c driver follows the same way with other upstreamed ISH drivers such as i2c driver. So this PR could co-exist with PR #64528, they fulfill different job.

-1 on using HALs for generic IPs like Synopsys DW I3C. Vendor-specific code should only exist for any wrapper/vendor quirks.

**Comment by leifuzhao** [comment]
> > > Theres many many issues here with this PR... I'm not sure where to begin
> > > If this really is the snps designware i3c as the description implies, then this is a duplicate of #64528
> > 
> > 
> > The zephyr driver has two modes. One is native driver mode, the other is the HAL mode, the two mode drivers could co-exist. The ISH drivers use HAL mode, for example, the previous upstreamed i2c driver uses sedi HAL to perform low level operation and config while there is another native i2c driver for the same designware i2c IP. The ISH i3c driver follows the same way with other upstreamed ISH drivers such as i2c driver. So this PR could co-exist with PR #64528, they fulfill different job.
> 
> -1 on using HALs for generic IPs like Synopsys DW I3C. Vendor-specific code should only exist for any wrapper/vendor quirks.

The HAL code used is not stay in zephyr repo, rather it resides in another opensource repo, the code submitted here for upstreaming only only contains API calls to HAL.

**Comment by gmarull** [comment]
> > > > Theres many many issues here with this PR... I'm not sure where to begin
> > > > If this really is the snps designware i3c as the description implies, then this is a duplicate of #64528
> > > 
> > > 
> > > The zephyr driver has two modes. One is native driver mode, the other is the HAL mode, the two mode drivers could co-exist. The ISH drivers use HAL mode, for example, the previous upstreamed i2c driver uses sedi HAL to perform low level operation and config while there is another native i2c driver for the same designware i2c IP. The ISH i3c driver follows the same way with other upstreamed ISH drivers such as i2c driver. So this PR could co-exist with PR #64528, they fulfill different job.
> > 
> > 
> > -1 on using HALs for generic IPs like Synopsys DW I3C. Vendor-specific code should only exist for any wrapper/vendor quirks.
> 
> The HAL code used is not stay in zephyr repo, rather it resides in another opensource repo, the code submitted here for upstreaming only only contains API calls to HAL.

This approach doesn't make sense for vendor-agnostic IP.

**Pull request closed without merging**
