### PR TITLE
[RFC] [DNM] drivers: serial: gecko: Split device tree info for usart based uart

### PR DESCRIPTION
**Pull request by chrta**
This prepares the implemenation of an usart based spi driver.
The naming convention is inspired by the atmel sercom driver.

Signed-off-by: Christian Taedcke <hacking@taedcke.com>

### CODE REVIEW

**Comment by chrta** [comment]
@mnkp Please also review

**Comment by mnkp** [comment]
I believe this PR is not required and we should not merge it. Let me explain the rationale.

On Atmel SoCs we often have a situation where a driver (e.g. serial, i2c) can be implemented using different hardware modules. I.e. there is more than one hardware module that can be used to provide a given feature. Since the driver's source code differs significantly from hardware module to hardware module we have to differentiate the implementations. Following naming convention was used to achieve this goal '_driver_name_-sam-_hardware_module_.c'. And thus we have: i2c_sam_twi.c, i2c_sam_twihs.c. Here TWI and TWIHS are two distinct hardware modules that can be used to build I2C driver. The DTS naming convention is a bit different, we have 'atmel,sam-_driver_name_-_hardware_module_'.

On SiLabs SoCs the only way to implement the SPI driver is to use the USART hardware module. Since there is no possibility for confusion a name like spi_gecko.c would work fine. Internally this driver would use the USART module. That said also in case of SiLabs SoCs it probably would make sense to decorate driver names with the hardware module if the direct connection between the driver name and the name of the hardware module used by the driver is not obvious. I.e. a better name for the SPI driver would likely be spi_gecko_usart.c.

However, I believe we should do it on per driver basis. In this case there is no need to decorate uart driver name since here the connection between the driver name and an underlying hardware module used by the driver is straightforward. This approach is also used by Atmel drivers in Zephyr.

**Comment by chrta** [comment]
@mnkp Thank you for the detailed feedback.

I would like to be able to use the same usart device tree for the usart based serial driver and later for the usart based spi driver. I though for this is have to split up the yaml files to have the common dts/bindings/arm/silabs,gecko-usart.yaml file and then two additional files, one for the serial driver and one for the spi driver.

For the serial driver, the uart peripheral (only on the older EFM32 avalable, like EFM32WG) and the usart peripheral can be used. For the spi driver, only the usart driver can be user.

What would be the correct approach here?

**Comment by mnkp** [comment]
If we want to follow the example of the atmel sercom driver then we may leave the current gecko drivers and DTS files as is. 

In principle we need to write a new spi driver and probably name it spi_gecko_usart.c and add a .yaml file named silabs,gecko-spi-usart.yaml (the file needs to contain compatible property matching its name). Then the board dts file would be able to choose between different drivers by modifying compatible property of the usartx node.

**Comment by chrta** [comment]
@mnkp Ok, so the usart yaml stay as it is and per default it is wired to the serial driver. Only if we choose to use it as spi, we add the comatible information for the spi driver, correct?

**Comment by chrta** [comment]
Ok, thx. So i will close this, since it is not necessary.

**Pull request closed without merging**
