### PR TITLE
Bluetooth: controller: split: Fix central assert on multiple reconnections

### LINKED ISSUE #22003: 'central' failure on nrf52_pca10040
**Describe the bug**
When running the central sample on the latest master (33929cb96052af3c61367d00f55cfe4bbaabe470), after a couple of connect/disconnects, an assertion is triggered, as per the log below
```
*** Booting Zephyr OS build zephyr-v2.1.0-1124-g33929cb96052  ***
Bluetooth initialized
Scanning successfully started
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
ASSERTION FAIL [e] @ ZEPHYR_BASE/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:589
```
**To Reproduce**
1. cmake -Bbuild_nrf -G"Eclipse CDT4 - Ninja" -DBOARD=nrf52_pca10040 /work/b06830/zephyr/zephyr-source/samples/bluetooth/central
3. west flash -d build_nrf
4. the following assertion failed can be seen on the board's serial port:
"ASSERTION FAIL [e] @ ZEPHYR_BASE/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:589"

**Expected behavior**
The central sample should run endlessly with  multiple connect/disconnect events

**Impact**
High

**Screenshots or console output**
```
*** Booting Zephyr OS build zephyr-v2.1.0-1124-g33929cb96052  ***
Bluetooth initialized
Scanning successfully started
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
Disconnected: 5d:c0:95:93:b9:24 (random) (reason 0x16)
Device found: 5d:c0:95:93:b9:24 (random) (RSSI -26)
Connected: 5d:c0:95:93:b9:24 (random)
ASSERTION FAIL [e] @ ZEPHYR_BASE/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:589
```

**Environment (please complete the following information):**
 - Linux
 - Zephyr SDK
 - 33929cb96052af3c61367d00f55cfe4bbaabe470

**Additional context**
Bisecting the tree shows that the first bad commit is the following:

commit 7417e6e09e7affdde503d347ff37b24ec695f9c9
Author: Vinayak Kariappa Chettimada <vich@nordicsemi.no>
Date:  Thu Dec 5 14:24:43 2019 +0530
   Bluetooth: controller: split: conn handle invalidation on release
   
   Move invalidation of connection handle to connection context
   release done on release of terminate rx node.
   
   Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

The PR introducing the commit is https://github.com/zephyrproject-rtos/zephyr/pull/20186

Reverting the aforementioned commit will enable the proper functionality for the central

### PR DESCRIPTION
**Pull request by cvinayak**
This reverts commit 7417e6e.
This reverts commit d3e3f8d.

Updated the lll_conn_flush interface to pass the connection
handle while the LLL connection context stored handle has
been invalidated.

Fixes #22003.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by George-Stefan — APPROVED** [review]

**Comment by alexandru-porosanu-nxp** [comment]
I've tested on VEGABoard and the previous behavior (the assertion) doesn't happen. I guess that Nordic is fixed as well.

**Review by alexandru-porosanu-nxp — APPROVED** [review]

**Review by wopu-ot — CHANGES_REQUESTED** [review]
I to not think that the PR solves the issue the original PR tried to solve: the mayfly_enqueue in ull_conn.c:1640 may be chained instead of being called inline, which causes the LLL to see the already invalidated handle. As far as I can tell, ll_conn_handle_get(conn) in line 1742 could have the same problem and some other mechanism is needed to ensure that lll_conn_flush sees the handle intact.

**Comment by George-Stefan** [comment]
ll_conn_handle_get(conn) returns the correct handle even if lll->handle is invalid.
In lll_conn_flush(), use the ne whandle param, not lll->handle

**Comment by wopu-ot** [comment]
> ll_conn_handle_get(conn) returns the correct handle even if lll->handle is invalid.
> In lll_conn_flush(), use the new handle param, not lll->handle

I stand corrected. I will need some time to think through the interaction with our LLL.

**Comment by bu5hm4nn** [comment]
👍 This pull request fixes crashes we were having after a few minutes of continuous transfer when running HCI_UART with BlueZ 5.52 and connecting with mutliple devices especially Android devices.

**Comment by mtpr-ot** [comment]
This PR also fixes race condition where slave ull_conn_done is invoked after flush. This would give an assert in ticker_update_conn_op_cb, as it attempted to update the ticker drift after ticker node had been stopped. I strongly recommend to merge this PR - @wopu-ot, any objections?

**Review by mtpr-ot — APPROVED** [review]

**Review by wopu-ot — APPROVED** [review]

**Pull request merged**
