### PR TITLE
samples: bluetooth: Add support for hci 3wire

### PR DESCRIPTION
**Pull request by LingaoM**
Add support 3wire hci uart.

### CODE REVIEW

**Comment by jhedberg** [comment]
@LingaoM have you tested this against Zephyr's own h5.c or just with a Linux host?

**Comment by LingaoM** [comment]
> ?

just use hciattach test，

**Comment by jhedberg** [comment]
@LingaoM sorry, I forgot about this one. Could you please rebase to see that nothing has broken meanwhile? We also need at least one other review.

**Comment by LingaoM** [comment]
> @LingaoM sorry, I forgot about this one. Could you please rebase to see that nothing has broken meanwhile? We also need at least one other review.

Done.

**Review by jori-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
