### PR TITLE
samples: net: echo-client: Increase buf count for frdm-k64f

### LINKED ISSUE #7678: Unstable ping RTT with ethernet ipv4 networking
The ping response time suddenly degrades with ipv4/ethernet on nxp-frdm-k64f board.
To reproduce the issue, run samples/net/echo_client with CONF_FILE=prj_frdm_k64f.conf. 
Run 'ping 192.0.2.1' from the machine configured with PEER_IPV4_ADDR=192.0.2.2.

For first 60-70 ping requests, the response time is about .2ms.
Then suddenly, ping response time degrades to more than 200ms and at times goes as high as 1s.

(The problem does not reproduce on qemu.)

### PR DESCRIPTION
**Pull request by jukkar**
Increasing the network buffer count for frdm-k64f so that the
device will not run out of memory so easily.

Fixes #7678

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by pfalcon** [comment]
I'd like to challenge this with https://github.com/zephyrproject-rtos/zephyr/pull/7831 . Apparently, it's not a good way when some developers increase buffers, and other decrease. @jukkar, I encourage you to not workaround the issues by throwing more memory to the fire. That's masking the issues instead of resolving them, and even that starts to fail, as my PR shows.

**Review by pfalcon — DISMISSED** [review]
Actually, it seems that with #7678,  #7571, #7818 people finally start to put Zephyr's IP stack to some use and spot all the issues with it. As someone experiencing these issues for 2nd year, let me make a case here and give -1, encouraging instead proper analysis and debugging of the underlying issue(s).

(Yeah, I'm just afraid that @nashif will merge this without looking, and we'll miss a chance to draw the core team to these issues for few more months.)

**Comment by pfl** [comment]
> Actually, it seems that with #7678, #7571, #7818 people finally start to put Zephyr's IP stack to some use and spot all the issues with it. As someone experiencing these issues for 2nd year, let me make a case here and give -1, encouraging instead proper analysis and debugging of the underlying issue(s).
> 
> (Yeah, I'm just afraid that @nashif will merge this without looking, and we'll miss a chance to draw the core team to these issues for few more months.)

Do you have an analysis on what issues enabling more buffers are hiding? Can you suggest a fix?

**Comment by jukkar** [comment]
I could not reproduce the issue described in #7678 but as the device seemed to run out of memory the next logical step is to increase amount of memory. I was expecting the reporter to test if this helps his scenario.

Our buffer counts are typically quite small in various configurations even if the device itself has plenty of memory available. I think you are mixing out-of-memory cases and buffer bloat scenarios in various bugs that you started to comment things.

**Review by tbursztyka — APPROVED** [review]

**Comment by pfalcon** [comment]
@pfl :

> Do you have an analysis on what issues enabling more buffers are hiding?

I'm doing analysis on the various aspects of the IP stack working, and share any notes on the problem spots I see, e.g. a recent such comment: https://github.com/zephyrproject-rtos/zephyr/issues/7578#issuecomment-390691809 . Overall, we have many different issues, which interact in unpredictable ways, which complicate both "static" analysis and trying to reproduce (even isolate from others) a particular issue in practice.

> Can you suggest a fix?

Unfortunately, no so far. That's why I think it's important that other developers joined forces trying to reproduce and debug such issues, instead of working around by adding more buffers.

**Comment by pfalcon** [comment]
@jukkar: 

> I could not reproduce the issue described in #7678 but as the device seemed to run out of memory the next logical step is to increase amount of memory. I was expecting the reporter to test if this helps his scenario.

I added a steps to reproduce #3132 issue (which appears to be just the generic variant of #7678): https://github.com/zephyrproject-rtos/zephyr/issues/3132#issuecomment-391702396 . It's just a single extra step after reproducing https://github.com/zephyrproject-rtos/zephyr/pull/7831 , so I hope you can give it a try.

> Our buffer counts are typically quite small in various configurations even if the device itself has plenty of memory available.

I don't see a problem here. We should target the IP stack working reliably with the minimal memory requirements. Devices which have more memory can just benefit for particular applications targeted at them (for example, they could handle more concurrent connections or have higher throughput). But the baseline should be the stack working in the minimum memory requirements, and for many sample-style applications that's 1 receive and 1 transmit packets, couple with fragment space to hold data for those packets. So, we should not increase pkt/netbuf counts, but decrease them, then figure out why it doesn't work as expected, then try to fix it (either by documenting true minimums, or better by making it work with bare minimums, or explicitly error out if not possible).

> I think you are mixing out-of-memory cases and buffer bloat scenarios in various bugs that you started to comment things.

I'm mixing up, because there's a whole mixup of issues in the IP stack, and now more people start to see some of them too. Can you please try to reproduce them on your side, that's the first step to untangle the matter.

**Review by nashif — APPROVED** [review]

**Pull request merged**
