### PR TITLE
[Backport v2.7-branch] arm cortex_m: cmsis.h - Fix IRQn_Type enum

### LINKED ISSUE #41012: irq_enable() doesn’t support enabling NVIC IRQ number more than 127
**Describe the bug**
We are updating kscan driver for MEC172x microchip device. The kscan peripheral is routed to NVIC 135. In the driver init function we enable NVIC 135 by calling the function irq_enable() and passing the IRQ number from the device instance. 

The function irq_enable() casts the IRQ number input to IRQn_type enum (defined in cortex_m/[cmsis.h](https://github.com/MicrochipTech/zephyr/blob/main/include/arch/arm/aarch32/cortex_m/cmsis.h)) which results as a signed 8-bit number. The function will write the NVIC Set Enable register only if the signed 8-bit number is not negative. The NVIC irq 135 results in a negative number (see register R0, R3 in snapshot which shows the conversion). Hence the NVIC register is not written.

Attached screenshot of the debugger window inside function irq_enable()

The platform we are using is mec172xevb_assy6906

Note that if we add one last member to the IRQn_type structure (as the below line), then the issue gets resolved, as compiler no longer treats IRQn_type as 8-bit.

max_IRQn = 0x100,

We are unable to submit the MEC172x kscan driver without this fix in Zephyr core.
screenshot-irq_enable_debug

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 4495f43dca440de4e1aa810f7448625a351f61da from #41279

Fixes #41012

### CODE REVIEW

**Comment by hunterhu3000** [comment]
This background of this PR is that we found a test case fail in v2.7, see issue https://github.com/zephyrproject-rtos/zephyr/issues/51147. And found the commit https://github.com/zephyrproject-rtos/zephyr/commit/4495f43dca440de4e1aa810f7448625a351f61da can fix it. So it would be good if we can backport the patch to v2.7

**Comment by hunterhu3000** [comment]
No idea why the CI fails.

**Comment by MaureenHelm** [comment]
> It looks like the CI do not like "typedef". It seems this rule is added in after v3.0. Do we need to rewrite this patch, or can we ignore the CI fail and merge it directly, @MaureenHelm @galak @ioannisg

No, I believe the failed check was overridden by an admin when the original PR was merged into main.

**Review by cfriedt — APPROVED** [review]

**Comment by cfriedt** [comment]
LGTM - @jvasanth1 - can you please ack as the Microchip maintainer?

**Review by jvasanth1 — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]

**Pull request merged**
