### PR TITLE
boards: hexiwear_kw40z: Remove I2C pins and dts enablement

### PR DESCRIPTION
**Pull request by galak**
The pin number should be 7, not 6.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@MaureenHelm should we even have I2C enabled for hexiwear_kw40z? (since these pin's conflict with the UART pins).

**Comment by MaureenHelm** [comment]
> @MaureenHelm should we even have I2C enabled for hexiwear_kw40z? (since these pin's conflict with the UART pin

No, this doesn't make sense.

**Comment by galak** [comment]
> No, this doesn't make sense.

??

**Comment by MaureenHelm** [comment]
> > No, this doesn't make sense.
> 
> ??

It doesn't make sense to have I2C enabled on hexiwear_kw40z, because as you pointed out, these pins conflict with the UART. We should just remove I2C references from this board configuration.

**Comment by galak** [comment]
> > 
> 
> It doesn't make sense to have I2C enabled on hexiwear_kw40z, because as you pointed out, these pins conflict with the UART. We should just remove I2C references from this board configuration.

Updated the PR to remove the I2C bits.

**Review by MaureenHelm — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
