### PR TITLE
RFC: Reformat FS subsystem to 100 characters per line

### PR DESCRIPTION
**Pull request by de-nordic**
The PR re-formats VFS, FATFS and LittleFS driver to 100 characters per line to unify usage of the line length across sources, allowing to concatenate some of the source lines and improve code readability; the change also removes doubt whether using 100 characters would break source style.

### CODE REVIEW

**Comment by de-nordic** [comment]
@carles @nvlsianpu What do you think about such move? I have decided to propose the change because often people are reluctant to use 100 characters per line, in existing code, to avoid breaking style of the file. The change removes such doubt out of equation.

**Comment by cfriedt** [comment]
I'm ok with longer line lengths

**Comment by de-nordic** [comment]
> 
> 
> I'm ok with longer line lengths

I know, everyone seems to be. I was rather asking what do you think of rewriting these files for that reason. You know, it might be considered pointless move by some.

**Comment by Laczen** [comment]
IMO 100 characters per line is not a good idea, it would be better to reduce from 80 to 70 characters per line. Why is this ? Simple, most code will be studied and reviewed in a files changed view as part of a PR. In a split view 70 characters can be viewed next to each other without any word wrapping. Of course we could state that you need to look at the code in a unified view, this removes any advantages of the split view.

Take a look at the present PR, how much is disturbed by the word wrapping by github ?

**Comment by nvlsianpu** [comment]
I see no problem with having any new patch aligned to 100 character in file which is legacy aligned to 80 character.
I think rewriting code from 80 to 100 as a task is wasting of time, but you already did it. I Can accept that.
100 characters lines are allowed in zephyr-code since a while

As @Laczen mention some of use prefer to look at changes in split view. In that case longer lines are problematic especially if view is narrowed  somewhy.

**Pull request closed without merging**
