### PR TITLE
intel_adsp: hda: simplify pm logic

### PR DESCRIPTION
**Pull request by ceolin**
- Remove duplicated call
- Simplify `intel_adsp_hda_dma_start` pm logic.

### CODE REVIEW

**Comment by ceolin** [comment]
@tmleman would you mind take a look on it ? Especially the commit 5d419bdf49bc74f49ff857aa041cea57d8cfc498

**Review by tmleman — CHANGES_REQUESTED** [review]
> The distinction is not necessary because if the device is ACTIVE,
pm_device_runtime_get won't trigger any device pm specific code.

But `pm->usage` will be out of balance. You can call multiple times **start** and **stop** for the same dma instance and channel. For example call start 8 times and stop only once, it should work.

**Comment by ceolin** [comment]
> > The distinction is not necessary because if the device is ACTIVE,
> > pm_device_runtime_get won't trigger any device pm specific code.
> 
> But `pm->usage` will be out of balance. You can call multiple times **start** and **stop** for the same dma instance and channel. For example call start 8 times and stop only once, it should work.

Thanks for reviewing it ! It seems that the only case where `pm_device_runtime_get` is not called is when `intel_adsp_hda_is_enable()` it true, so I moved `pm_device_runtime_get` to after this check to avoid that logic. Does `intel_adsp_hda_is_enable` require the device be active ?  or this change is ok ?

**Comment by tmleman** [comment]
> Does `intel_adsp_hda_is_enable` require the device be active ?

I'm not sure, my assumption was that the power domain must be on. PG on power domain can be prevented also from HOST side. So this can work because domain was wake up without the involvement of FW on DSP. However, I don't know if it would be correct to rely on such a dependency in the driver.

An alternative solution would be to rely not on a hardware register but on an variable in memory where each bit would represent a channel already in use in the instance.

**Comment by teburd** [comment]
In the end I think because of the nature of DMA, the ability to call start/stop multiple times, and the way in which SoF uses DMA (without interrupts!) it becomes very hard to balance the pm get/put calls internally.

SoF *knows* in its pipeline code what DMAs are active when. Externalizing the pm calls makes really good sense here. Or maybe at least moving them up a level to the thing using DMA, e.g. the dai layer.

**Pull request closed without merging**
