### PR TITLE
drivers: add Atmel SAM PWM driver

### PR DESCRIPTION
**Pull request by aurel32**
This patch adds basic support for the PWM devices available on the Atmel
SAM family. Beside enabling the driver, everything is selected through
the device tree, including enabling the PWM0 and PWM1 devices. Thus
CONFIG_PWM_0 and CONFIG_PWM_1 are ignored.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]
Driver looks good, but can you enable it on at least one board (add pwm to the board's `supported` list and configure pins)? I'd like to make sure it gets built in CI. Please have a look at `tests/drivers/pwm` and `samples/basic/`

**Comment by aurel32** [comment]
> Driver looks good, but can you enable it on at least one board (add pwm to the board's `supported` list and configure pins)? I'd like to make sure it gets built in CI. Please have a look at `tests/drivers/pwm` 

Yes, I can try to do that for the SAM E70 Xplained board, but I will need some guidance to select the pin to configure as this board currently lacks way to configure pin alternate functions through DT (something on my TODO list). In addition the only LED available on the board is not connected to a pin configurable as PWM. As the Arduino connectors are not soldered, I believe it is better to configure the PWM pins of the "Xplained Pro Standard Extension Header" which are standard on this series of board. Correct?

> and `samples/basic/`

The sample PWM driver assume that a LED is connected to the PWM port. Should I assume that users will connect a LED on the connector (what I have done myself to test this driver)? In that case should I use the `pwm-led0` DT property anyway?

**Comment by MaureenHelm** [comment]
> As the Arduino connectors are not soldered, I believe it is better to configure the PWM pins of the "Xplained Pro Standard Extension Header" which are standard on this series of board. Correct?

Either option is fine.

> The sample PWM driver assume that a LED is connected to the PWM port. Should I assume that users will connect a LED on the connector (what I have done myself to test this driver)? In that case should I use the `pwm-led0` DT property anyway?

This should probably be done in a device tree overlay for the specific sample, unless we introduce an arduino_pwm alias similar to arduino_serial and arduino_spi. @erwango have you thought about this?

**Comment by aurel32** [comment]
> Hi, Aurelien,
> 
> Do we need to update the soc\arm\atmel_sam\same70\dts_fixup.h as well?

There is no need for that, as it uses the new DT names, which do not contain the addresses.

**Comment by aurel32** [comment]
@MaureenHelm I have just pushed a new version adding the pinmux configuration to the SAM E 70 XPlained board, and updating `pwm_api` to support that board.

**Review by dbkinder — APPROVED** [review]
doc change LGTM

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
