### PR TITLE
samples: config: Replace deprecated OVERLAY_CONFIG by EXTRA_CONF_FILE

### PR DESCRIPTION
**Pull request by butok**
The OVERLAY_CONFIG was deprecated and replaced by EXTRA_CONF_FILE since Zephyr v3.4. 
Upgrade the legacy code to use EXTRA_CONF_FILE.

### CODE REVIEW

**Comment by kartben** [comment]
Hey, this is great, thanks for spotting this and sending the PR @butok.
It would actually be even better to completely drop all references to `OVERLAY_CONFIG` altogether, but I guess this can be done in a follow-up PR too (poke @tejlmand)

However, for the sake of not leaving the tree in too much of a "half-fixed" situation, could you please make sure your commit is either fixing everything, or really limits itself to *just* samples like your commit message and PR title currently suggest.

Thanks!

**Comment by butok** [comment]
> Hey, this is great, thanks for spotting this and sending the PR @butok. It would actually be even better to completely drop all references to `OVERLAY_CONFIG` altogether, but I guess this can be done in a follow-up PR too (poke @tejlmand)
> 
> However, for the sake of not leaving the tree in too much of a "half-fixed" situation, could you please make sure your commit is either fixing everything, or really limits itself to _just_ samples like your commit message and PR title currently suggest.
> 
> Thanks!

It is stuck by twister selftests. 
It's unclear...

**Comment by butok** [comment]
Hi @kartben and @tejlmand 

We have: now
- Zephyr code relies on both OVERLAY_CONFIG and EXTRA_CONF_FILE.
- Replacing of deprecated  OVERLAY_CONFIG is not enough, as it's still used.

Unfortunately, have to close the PR, as it is out of scope of this simple change.

Proposal:
- It have to be fixed as the legacy OVERLAY_CONFIG  does not work for some cases.
- It should be fixed by an author of new EXTRA_CONF_FILE or by Nordic as their tests are failed.

Lesson:
- If was decided to deprecate something , it have to be remove immediately. Otherwise you have to support & test both code.

**Comment by Thalley** [comment]
> Hi @kartben and @tejlmand
> 
> We have now:
> 
>     * Zephyr code relies on both OVERLAY_CONFIG and EXTRA_CONF_FILE.
> 
>     * Replacing of deprecated  OVERLAY_CONFIG is not enough, as it's still used.
> 
> 
> Unfortunately, have to close the PR, as it is out of scope of this simple change.
> 
> Proposal:
> 
>     * It have to be fixed as the legacy OVERLAY_CONFIG  does not work for some cases.
> 
>     * It should be fixed by an author of new EXTRA_CONF_FILE or by Nordic as their tests are failed.
> 
> 
> Lesson:
> 
>     * If was decided to deprecate something, it have to be removed immediately. Otherwise, we have to support & test both code.

Can we add a deprecation warning during build somehow when `OVERLAY_CONFIG` is used?

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Comment by butok** [comment]
> > Hi @kartben and @tejlmand
> > We have now:
> > ```
> > * Zephyr code relies on both OVERLAY_CONFIG and EXTRA_CONF_FILE.
> > 
> > * Replacing of deprecated  OVERLAY_CONFIG is not enough, as it's still used.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unfortunately, have to close the PR, as it is out of scope of this simple change.
> > Proposal:
> > ```
> > * It have to be fixed as the legacy OVERLAY_CONFIG  does not work for some cases.
> > 
> > * It should be fixed by an author of new EXTRA_CONF_FILE or by Nordic as their tests are failed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Lesson:
> > ```
> > * If was decided to deprecate something, it have to be removed immediately. Otherwise, we have to support & test both code.
> > ```
> 
> Can we add a deprecation warning during build somehow when `OVERLAY_CONFIG` is used?

It's better to raise a compilation error, as warnings are ignored.

**Review by kartben — CHANGES_REQUESTED** [review]
> However, for the sake of not leaving the tree in too much of a "half-fixed" situation, could you please make sure your commit is either fixing everything, or really limits itself to just samples like your commit message and PR title currently suggest.

This hasn't been addressed?

**Comment by butok** [comment]
> > However, for the sake of not leaving the tree in too much of a "half-fixed" situation, could you please make sure your commit is either fixing everything, or really limits itself to just samples like your commit message and PR title currently suggest.
> 
> This hasn't been addressed?

Closing PR, as the Bluetooth CI is failed for Nordic.
**Please, somebody from Nordic will not forget and follow-up. 
It's buggy as it is now**

**Pull request closed without merging**
