### PR TITLE
drivers: ieee802154: cc13xx_cc26xx_subg: fix timing regression

### LINKED ISSUE #63324: drivers: ieee802154: cc13xx_cc26xx_subg: timing regression
**Describe the bug**

a12a6ab5b94a0aa4cc53c4b507bd8c5085a30910 introduced a timing regression into the CC13/26xx driver. The backoff and CCA times are calculated incorrectly due timing being based on the wrong channel page and due to a missing ns to us conversion.

PR already attached.

**To Reproduce**

1. execute echo client/server
2. observe increased PER and failed clear channel assessments (resulting in dropped UDP packets)

**Expected behavior**

PER should not be changed.

**Impact**

Considerably increased PER for the CC13/26xx driver.

**Logs and console output**

Logs similar to:

```
[00:00:01.849,090] <err> net_echo_client_sample: UDP IPv6: Data packet not received
[00:00:03.583,312] <err> net_echo_client_sample: UDP IPv6: Data packet not received
[00:00:04.754,791] <err> net_echo_client_sample: UDP IPv6: Data packet not received
[00:00:33.926,239] <wrn> net_ieee802154: Clear channel assessment failed: dropping fragment 0x20008dd4 on interface 0x200013f0.
[00:00:35.602,233] <wrn> net_ieee802154: Clear channel assessment failed: dropping fragment 0x20008dd4 on interface 0x200013f0.
[00:00:37.125,793] <wrn> net_ieee802154: Clear channel assessment failed: dropping fragment 0x20008dd4 on interface 0x200013f0.
```

**Environment (please complete the following information):**

any

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by ghost**
Fixes a timing regression introduced by commit a12a6ab5b94a0aa4cc53c4b507bd8c5085a30910.

This caused a massively increased package error rate.

Fixes: #63324.

### CODE REVIEW

**Comment by fgrandel** [comment]
@niflostancu While testing for #63255 also found this timing regression. Luckily this was easy to bisect. Maybe you could ACK for fast merging?

**Review by rlubos — APPROVED** [review]

**Comment by niflostancu** [comment]
Sorry, I was AFK this weekend. I tested this on my devices, working as expected ;)

**Comment by fgrandel** [comment]
> Sorry, I was AFK this weekend. I tested this on my devices, working as expected ;)

Thanks for testing! :-)

**Comment by fgrandel** [comment]
@cfriedt @vaishnavachath  or @jukkar Could you maybe provide a 2nd ACK? Has been tested on hardware by myself and @niflostancu Thanks!

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
