### PR TITLE
Move wait_q.h/timeout_q.h to be internal kernel headers

### PR DESCRIPTION
**Pull request by nashif**
wait_q.h and timeout_q.h are not a public header and should not be exposed as such. Move it back to kernel/include and change code to not use it.

- kernel: move timeout_q.h to kernel/includ
- arch: remove wait_q.h include
- kernel: move wait_q.h header to be internal

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Review by carlocaione — DISMISSED** [review]

**Comment by cfriedt** [comment]
sof seems to depend on `zephyr/timeout_q.h`

**Comment by nashif** [comment]
> sof seems to depend on `zephyr/timeout_q.h`

yep, this needs to be fixed...  @lyakh  @kv2019i  can you please take a look and see how you can drop this dependency on this header and API which is an internal zephyr kernel API. Sorry about the confusion.

**Comment by henrikbrixandersen** [comment]
> yep, this needs to be fixed... @lyakh @kv2019i can you please take a look and see how you can drop this dependency on this header and API which is an internal zephyr kernel API. Sorry about the confusion.

@lyakh @kv2019i You may be able to find inspiration for the conversion in commit 7f7201f79ba6cfcf3070ec1cd38265754b1b5c8b

**Comment by kv2019i** [comment]
SOF side change under review at https://github.com/thesofproject/sof/pull/8146 . We had a very specific case where we needed to call z_abort_timeout() on "timer->timeout" directly -- discussion now ongoing whether we can simply replace with k_timer_stop() or is there something stop does that causes as problems (and maybe something that needs to be kept in public interface of the timer).

**Review by cfriedt — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Makes sense.  Really a cleanup of the kernel/include directory wouldn't be a bad idea.

**Pull request merged**
