### PR TITLE
menuconfig: Fix some minor graphical glitching and add custom styles

### PR DESCRIPTION
**Pull request by ulfalizer**
Update menuconfig.py to upstream revision 35a60b786c646.

This fixes some minor graphical glitching, with parts of lines that
don't fit the terminal wrapping around to the next line, and some
headings disappearing.

This version also adds supports for custom style definitions,
contributed by Mitja Horvat (punkfluid). Colors can be specified both by
number and in #RRGGBB notation. Color accuracy varies depending on
terminal capabilities, but will usually be good.

### CODE REVIEW

**Comment by ulfalizer** [comment]
recheck

**Comment by ulfalizer** [comment]
@nordic-krch 
Looks like something is wonky with the documentation for the Kconfig template: https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/22316/7/tests

**Comment by ulfalizer** [comment]
Think this fixes it: https://github.com/zephyrproject-rtos/zephyr/pull/10000 (nice quads)

**Comment by nordic-krch** [comment]
@ulfalizer thanks for fixing it. I see that you've been honored for :)

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
>Think this fixes it: #10000 (nice quads)

Nice reference.

**Pull request merged**
