### PR TITLE
Fix x86 (-m32) compilation with ZEPHYR_TOOLCHAIN_VARIANT=host

### PR DESCRIPTION
**Pull request by marc-hb**
These two patches are a complete compilation fix for the following x86 boards:

  galileo, minnowboard, qemu_x86, qemu_x86_nommu, up_squared,  up_squared_sbl

They are an incomplete fix for the following x86 boards which still fail (no regression) with "-lgcc not found"

  arduino_101, qemu_x86_nommu, quark_d2000_crb, quark_se_c1000_devboard,  tinytile

(I don't know whether the second subset can ever be supported by ZEPHYR_TOOLCHAIN_VARIANT=host)

Please share any suggestion to avoid the cmake code duplication.

### CODE REVIEW

**Comment by marc-hb** [comment]
Force pushed to fix gitlint commit message errors, zero code change. (I wrongly assumed gitlint was smart enough to find all commits on the branch. It has to be told how many manually.)

**Comment by marc-hb** [comment]
Any feedback from @andyross , @aurel32 , @galak,  @tejlmand or other appreciated.

**Review by SebastianBoe — DISMISSED** [review]
> Please share any suggestion to avoid the cmake code duplication.

I can't see any clean way to avoid the duplication without doing a complete overhaul that merges gcc/target.cmake with host-gcc/target.cmake.

**Comment by SebastianBoe** [comment]
@aescolar : FYI

**Comment by mped-oticon** [comment]
> Please share any suggestion to avoid the cmake code duplication.

The problem arises because host-gcc is subtly different than the normal cross compiling gcc. Thus the overlap is significant.

I suggest to factor out the common parts between host-gcc and gcc into a CMake macro, e.g. `toolchain_gcc_common_libgcc()`.

**Review by mped-oticon — DISMISSED** [review]
Other than the duplication, LGTM.

**Comment by marc-hb** [comment]
> I can't see any clean way to avoid the duplication without doing a complete overhaul that merges gcc/target.cmake with host-gcc/target.cmake.

> The problem arises because host-gcc is subtly different than the normal cross compiling gcc. Thus the overlap is significant.

 I never had any plan to look at any code duplication beyond this libgcc linking issue. Are you both referring to some larger (and more subtle) duplication?
 
> I suggest to factor out the common parts between host-gcc and gcc into a CMake macro, e.g. `toolchain_gcc_common_libgcc()`.

So I tried to move this code to a new macro in `zephyr/cmake/extensions.cmake` and (limited) testing showed no issue. Is `extensions.cmake` the right place for such a new macro?

For the macro name `zephyr_link_libgcc()` would be more consistent with the other macros and functions already in extensions.cmake, any objection/bikeshedding?

Now I just found that this code is *already* duplicated in `compiler/clang/target.cmake`!  A new, first and a "zero-change" refactoring commit will merely introduces the new macro. The two existing commits will be stacked on top of that.

**Comment by nashif** [comment]
> So I tried to move this code to a new macro in `zephyr/cmake/extensions.cmake` and (limited) testing showed no issue. Is `extensions.cmake` the right place for such a new macro?

i would not put the macro in extensions, this is toolchain related so I would put this in its own file or something that is toolchain related.

**Comment by nashif** [comment]
we also need to fix all the warnings about orphan linker sections.

**Comment by marc-hb** [comment]
> we also need to fix all the warnings about orphan linker sections.

For personal convenience I just turned off LINKER_ORPHAN_SECTION_WARN in Kconfig

In my experience 99% of these warnings are:

```
/usr/bin/ld: warning: orphan section `.note.GNU-stack' from `drivers/spi/libdrivers__spi.a(spi_intel.c.obj)' being placed in section `.note.GNU-stack'.
/usr/bin/ld: warning: orphan section `.note.GNU-stack' from `drivers/serial/libdrivers__serial.a(uart_ns16550.c.obj)' being placed in section `.note.GNU-stack'.
/usr/bin/ld: warning: orphan section `.note.GNU-stack' from `kernel/libkernel.a(device.c.obj)' being placed in section `.note.GNU-stack'.
/usr/bin/ld: warning: orphan section `.note.GNU-stack' from `kernel/libkernel.a(errno.c.obj)' being placed in section `.note.GNU-stack'.
etc.
```
AFAIK `.note.GNU-stack` is metadata for the linker itself and not meant to be placed anywhere so this looks like a linker bug to me (triggered when using a linker script?) So no idea what to do about .note.GNU-stack warning but if you have suggestion(s) then I'm happy to try (then I would also begin with filing a bug to avoid off-topic discussions here)

**Comment by nashif** [comment]
@marc-hb We can discard most of those, they are already being discarded for x86_64 so I think we need to put the discard in a more common place.

**Comment by marc-hb** [comment]
Two suggested locations for the new macro:
A. `/cmake/toolchain/libgcc.cmake`
B. `/cmake/compiler/libgcc.cmake`
Both new files. There are 262 *.cmake files already but none yet in these specific directories.

A. On one hand this code affects `TOOLCHAIN_LIBS` and linking.
B. On the other hand `libgcc` is very much part of the C compiler. The existing, duplicated code is currently in `compiler/clang/target.cmake` and `compiler/gcc/target.cmake` and it will still be invoked from there.

`zephyr_link_libgcc()` macro name OK? Zephyr already has `zephyr_link_libraries()` and cmake has `target_link_librairies()`

PS: if maintainers want to name the file `thing.cmake` and the macro `link_stuff()` then fine by me.

**Review by aescolar — DISMISSED** [review]
A quick trial for native_posix in a Ubuntu 18.04 machine with the default gcc, shows a few linker warnings. 
```
build$ cmake ../samples/hello_world/ -DBOARD=native_posix -GNinja
[..]
build$ ninja
[0/1] Re-running CMake...
Zephyr version: 1.13.99
-- Selected BOARD native_posix
Parsing Kconfig tree in Kconfig
Loading build/zephyr/.config as base
Configuration written to 'zephyr/.config'
-- Cache files will be written to: .cache/zephyr
-- Configuring done
-- Generating done
-- Build files have been written to: build
[69/69] Linking C executable zephyr/zephyr.elf
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
```

**Comment by marc-hb** [comment]
> /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc

(... then it finds and links to /usr/lib/gcc/x86_64-linux-gnu/7/**32**/libgcc.a instead)

This warning is not specific to native_posix, it's just more repetitive and more visible with native_posix.
I admit I didn't pay much attention to it because I thought it was caused by the default "multilib" configuration. After a bit more testing I now see it's caused by a combination of two cmake issues:
A. The -L LIBGCC_DIR logic which I copied from compiler/gcc/target.cmake is at best spurious in this case cause the built-in search path is enough
B. TOOLCHAIN_C_FLAGS is uninitialized/empty which means gcc --print-gcc-file-name is invoked *without*   -m32
  
Removing the 3 lines of -L LIBGCC_DIR code makes the warning go away, I will do this.
B. is harmless as long as gcc doesn't start giving different basenames, e.g. libgcc32.vs libgcc64.a. Now passing an empty TOOLCHAIN_C_FLAGS argument is confusing so I'll have a look at this; any clue appreciated.

**Review by andyross — COMMENTED** [review]
Broadly approve, and am not bothered by the mild duplication either.  Not actually a +1 because honestly I only do toddler-level cmake and am not the right person to review. :)

**Review by nashif — APPROVED** [review]

**Comment by marc-hb** [comment]
This -lgcc addition broke [qemu_]x86_64 when ZEPHYR_TOOLCHAIN_VARIANT=host, tentative fix in PR #12805. More details there.

**Pull request merged**
