### PR TITLE
kernel: mutex: fix races when lock timeout

### LINKED ISSUE #48056: Possible null pointer dereference after k_mutex_lock times out
**Describe the bug**

Assume thread A holds a mutex and thread B tries to lock it with a timeout, when that time comes up B gets unpended by z_thread_timeout and thus removed from the mutex's wait queue.

If however A unlocks this mutex before B being rescheduled again, the mutex->owner field will be set to null because B is not on the wait queue anymore. And when B finally gets resheduled again it will dereference the null pointer (mutex-owner) here

```
static bool adjust_owner_prio(struct k_mutex *mutex, int32_t new_prio)
{
	if (mutex->owner->base.prio != new_prio) {
```

as @peter-mitsis pointed out in #47906 , complete steps of one possible scenario are:

1. A low priority thread (Tlow) locks mutex A.
2. A high priority thread (Thigh) blocks on mutex A, boosting the priority of Tlow.
3. Thigh times out waiting for mutex A.
4. Before Thigh has a chance to execute, Tlow unlocks mutex A (which now has no owner) and drops its own priority.
5. Thigh now gets a chance to execute and finds that it timed out, and then enters the block of code to lower the priority of the thread that owns mutex A (now nobody).
6. Thigh tries to the dereference the owner of mutex A (which is nobody, and thus it is NULL). This leads to an exception.

**To Reproduce**

Use this test code as an app

```c
#include <kernel.h>
#include <sys/printk.h>

#define TIMEOUT_MS   	100
#define STACKSZ         8192

static struct k_mutex mutex;
static struct k_thread thread;

K_THREAD_STACK_DEFINE(stack, STACKSZ);

void test_thread(void *p1, void *p2, void *p3)
{
    ARG_UNUSED(p1);
    ARG_UNUSED(p2);
    ARG_UNUSED(p3);

    k_mutex_lock(&mutex, K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}

void main(void)
{
    k_mutex_init(&mutex);

    k_thread_create(&thread, stack, K_THREAD_STACK_SIZEOF(stack),
                    test_thread, NULL, NULL, NULL, 8, 0, K_NO_WAIT);

    k_mutex_lock(&mutex, K_FOREVER);

    k_sleep(K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}
```

`west build -b qemu_cortex_a53 path_to_the_above_app -t run # will data abort`

**Expected behavior**

Should not dereference a null pointer.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**

*** Booting Zephyr OS build 38de9b0156a8  ***
[00:00:00.000,000] <dbg> os: k_sched_unlock: scheduler unlocked (0x40017600:0)
[00:00:00.010,000] <dbg> os: setup_thread_stack: stack 0x4005fa40 for thread 0x40017000: obj_size=8192 buf_start=0x4005fa40  buf_size 8192 stack_ptr=0x40061a40
[00:00:00.010,000] <dbg> os: z_impl_k_mutex_lock: 0x40017600 took mutex 0x40017900, count: 1, orig prio: 0
[00:00:00.010,000] <dbg> os: z_impl_k_mutex_lock: adjusting prio up on mutex 0x40017900
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_unlock: mutex 0x40017900 lock_count: 1
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_unlock: new owner of mutex 0x40017900: (nil) (prio: -1000)
[00:00:00.120,000] <dbg> os: k_sched_unlock: scheduler unlocked (0x40017600:0)
main 40
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: on mutex 0x40017900 got_mutex value: -11
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: 0x40017000 got mutex 0x40017900 (y/n): y
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: 0x40017000 timeout on mutex 0x40017900
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: adjusting prio down on mutex 0x40017900
[00:00:00.120,000] <err> os: ELR_ELn: 0x0000000040006c30
[00:00:00.120,000] <err> os: ESR_ELn: 0x0000000096000006
[00:00:00.120,000] <err> os:   EC:  0x25 (Data Abort taken without a change in Exception level)
[00:00:00.120,000] <err> os:   IL:  0x1
[00:00:00.120,000] <err> os:   ISS: 0x6
[00:00:00.120,000] <err> os: FAR_ELn: 0x000000000000001a
[00:00:00.120,000] <err> os: TPIDRRO: 0x0100000040017978
[00:00:00.120,000] <err> os: x0:  0x0000000040017900  x1:  0x0000000000000000
[00:00:00.120,000] <err> os: x2:  0x0000000000000000  x3:  0x0000000000000000
[00:00:00.120,000] <err> os: x4:  0x0000000000000000  x5:  0x0000000000000003
[00:00:00.120,000] <err> os: x6:  0x000000000000000a  x7:  0x0000000000000000
[00:00:00.120,000] <err> os: x8:  0x000000000000002f  x9:  0x00000000ffffffff
[00:00:00.120,000] <err> os: x10: 0x0000000000000000  x11: 0x0000000000000000
[00:00:00.120,000] <err> os: x12: 0x0000000000000000  x13: 0x0000000000000000
[00:00:00.130,000] <err> os: x14: 0x0000000000000000  x15: 0x0000000000000000
[00:00:00.130,000] <err> os: x16: 0x0000000000000000  x17: 0x0000000000000000
[00:00:00.130,000] <err> os: x18: 0x0000000000000000  x30: 0x0000000040007204
[00:00:00.130,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.130,000] <err> os: Current thread: 0x40017000 (unknown)
[00:00:00.130,000] <err> os: Halting system

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: v2.7.2

### PR DESCRIPTION
**Pull request by SeediqQ**
Say threadA holds a mutex and threadB tries
to lock it with a timeout, a race would occur
if threadA unlock that mutex after threadB
got unpended by sys_clock and before it gets
scheduled and calls k_spin_lock.

This patch fixes this issue by checking the
mutex's status again after k_spin_lock calls.

Fixes #48056

Signed-off-by: Qi Yang <qi.yang@cmind-semi.com>

### CODE REVIEW

**Comment by SeediqQ** [comment]
Been doing some tests on my code lately and found something that seems to be related to zephyr/kernel/mutex.

**Describe the bug**

Assume thread A holds a mutex and thread B tries to lock it with a timeout, when that time comes up B gets unpended by z_thread_timeout and thus removed from
the mutex's wait queue.

If however A unlocks this mutex before B being rescheduled again, the mutex->owner field will be set to null because B is not on the wait queue anymore. And
when B finally gets resheduled again it will dereference the null pointer (mutex-owner) here

`
static bool adjust_owner_prio(struct k_mutex *mutex, int32_t new_prio)
{
	if (mutex->owner->base.prio != new_prio) {
`

**To reproduce**

I have tested the following code with v2.7-branch & qemu_cortex_a53

`
#include <kernel.h>
#include <sys/printk.h>

#define TIMEOUT_MS   	100
#define STACKSZ         8192

static struct k_mutex mutex;
static struct k_thread thread;

K_THREAD_STACK_DEFINE(stack, STACKSZ);

void test_thread(void *p1, void *p2, void *p3)
{
    ARG_UNUSED(p1);
    ARG_UNUSED(p2);
    ARG_UNUSED(p3);

    k_mutex_lock(&mutex, K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}

void main(void)
{
    k_mutex_init(&mutex);

    k_thread_create(&thread, stack, K_THREAD_STACK_SIZEOF(stack),
                    test_thread, NULL, NULL, NULL, 8, 0, K_NO_WAIT);

    k_mutex_lock(&mutex, K_FOREVER);

    k_sleep(K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}
`

Not sure if #22521 is related.

Please let me know if I'm getting this right and have some review on my pull request, thank you!

**Review by peter-mitsis — COMMENTED** [review]
I don't think that this proposed change in behaviour is right. Among other things, it creates a rather large problem.

By the time the calling thread reaches this timeout handling section (which exists to lower the priority of the owning thread--see priority inheritance), an undetermined amount of time has passed from the moment the thread timed-out (and was taken off the timer queue) to the time it executes. This could be microseconds, seconds, minutes, hours, days, .... Consequently we can not lock the mutex here as that would violate the timeout semantics.

**Comment by SeediqQ** [comment]
Hi @peter-mitsis, thanks for the comment!
 
> By the time the calling thread reaches this timeout handling section (which exists to lower the priority of the owning thread--see priority inheritance), an undetermined amount of time has passed from the moment the thread timed-out (and was taken off the timer queue) to the time it executes. This could be microseconds, seconds, minutes, hours, days, .... 

This I totally agree with you, and "this timeout handling section , which exists to lower the priority of the owning thread" is where that NULL pointer has been dereferenced (because unlock could happen during this "undetermined amount of time") and this PR is only trying to handle this problem.

> Consequently we can not lock the mutex here as that would violate the timeout semantics.

Yes, I think you are right about violating the timeout semantics here, but we certainly don't want to continue lowering the priority of the owning thread here if the mutex is already unlocked (in that case there aren't any owning thread), maybe just returning -EAGAIN without locking the mutex here? It seems strange to me though, because that mutex is safe to be locked at that condition. What do you think about this?

**Comment by SeediqQ** [comment]
> I think I follow you now. Sometimes it takes me a little while to get the right model in my head. :)

My apologies for not describing it in the right way, it seems much more clear to describe the scenario in steps. :)

>1. A low priority thread (Tlow) locks mutex A.
>2. A high priority thread (Thigh) blocks on mutex A, boosting the priority of Tlow.
>3. Thigh times out waiting for mutex A.
>4. Before Thigh has a chance to execute, Tlow unlocks mutex A (which now has no owner) and drops its own priority.
>5. Thigh now gets a chance to execute and finds that it timed out, and then enters the block of code to lower the priority of the thread that owns mutex A (now nobody).
>6. Thigh tries to the dereference the owner of mutex A (which is nobody, and thus it is NULL). This leads to an exception.

Yes! This is what I mean, mostly.

Just that I don't think it is limited to low priority thread in step1 and high priority thread in step2, a high priority thread in step1 and a low prio thread in step2 (or the same prio in both steps) can also leads to the same error condition. Maybe I'll open an issue and try to describe it again there as you suggested.

>Of the three options, I think the second (B) is the simplest and most straight-forward to implement. 

Agreed! 

And just curious about Option C, to make sure I understand you correctly, did you mean to use a special timeout routine for mutex lock instead of the z_thread_timeout routine that are used for all IPC primitives? So that the cleaning up routine can be moved to this special timeout routine (and be done immediately)?

>I would also recommend filing an issue describing this behaviour and sequence of events.

Will do that, thanks for reminding!

**Review by peter-mitsis — DISMISSED** [review]

**Comment by peter-mitsis** [comment]
@SeediqQ - Looks like there was a compliance check that failed that should be fixed. If I follow it correctly, this only affects the commit message signing.

**Comment by SeediqQ** [comment]
> @SeediqQ - Looks like there was a compliance check that failed that should be fixed. If I follow it correctly, this only affects the commit message signing.

Sorry about that, I thought I already fixed this Signed of by line in 41c86c5, but it seems CI is still complaining about it. I am trying a rebase right now. But I did not find where I can retrriger, maybe need your approval? @peter-mitsis

**Comment by peter-mitsis** [comment]
I gave approval for the run, but for some reason it is still failed with the same error, event though it looks to me that it should not have done so.

**Comment by SeediqQ** [comment]
Is there anything I should do about this Compliance Check?

**Review by andyross — CHANGES_REQUESTED** [review]
I think I see the race, but like Peter I'm not convinced this is a fix.

Putting a soft -1 on this (i.e. "break if it someone else needs it merged because it fixes a live issue") for now.  As it happens I have some of my own work in this space that I'm getting ready to submit. that would obviate it.

And indeed, the priority inheritance scheme is a little racy.  Another one I stumbled on is that thread abort doesn't interact with it either.

**Comment by SeediqQ** [comment]
> I think I see the race, but like Peter I'm not convinced this is a fix.

Hi @andyross, thx for the comments. Not sure what you mean here though, it did fixed this race issue for me, mind to explain more?

My option is that the root cause of this race is the non-atomicy between unpending a timed-out thread and the cleanup routine in that thread's context. So fix is either make unpending plus cleanup atomic as suggested by peter's option C or do checks before the cleanup routine as suggested by peter's option B (which is implemented in this PR). We agreed on option B because of its simplicity.

> As it happens I have some of my own work in this space that I'm getting ready to submit. that would obviate it.

That would also be great! Looking forward to see it. :)

> And indeed, the priority inheritance scheme is a little racy. Another one I stumbled on is that thread abort doesn't interact with it either.

Again looking forward to see your work on this. Since you mentioned, priority inheritance does not interact with thread priority set too I suspect.

**Review by andyross — DISMISSED** [review]
@peter-mitsis  pinged me.  No reason not to approve this.  As teased earlier, the k_zync feature in #48340 involves a complete rewrite of priority inheritence (AFAICT it's not subject to this particular race, and fixes a few other interactions with thread lifecycle that I stumbled on, though not all).  But that's at least a release out, we should still fix bugs that exist in the tree now.

**Review by peter-mitsis — DISMISSED** [review]

**Comment by nashif** [comment]
@SeediqQ  you need to fix your commit messages:


b40ed952ee3cfc30bd05436e3be5cc71c9c9ad0a: author email (qi.yang <qi.yang@cmind-semi.com>) needs to match one of the signed-off-by entries.
b40ed952ee3cfc30bd05436e3be5cc71c9c9ad0a: author email (qi.yang <qi.yang@cmind-semi.com>) does not follow the syntax: First Last <email>.

**Comment by nashif** [comment]
> Author: qi.yang <qi.yang@cmind-semi.com>

should be `Qi Yang`

**Comment by SeediqQ** [comment]
> > Author: qi.yang [qi.yang@cmind-semi.com](mailto:qi.yang@cmind-semi.com)
> 
> should be `Qi Yang`

Done. Sorry for the first-time contributor errors.

**Review by peter-mitsis — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Refresh +1

**Pull request merged**
