### PR TITLE
global: Remove leading/trailing blank lines in files

### PR DESCRIPTION
**Pull request by ulfalizer**
Remove leading/trailing blank lines in .c, .h, .py, .rst, .yml, and
.yaml files.

Will avoid failures with the new CI test in
https://github.com/zephyrproject-rtos/ci-tools/pull/112, though it only
checks changed files.

Move the 'target-notes' target in boards/xtensa/odroid_go/doc/index.rst
to get rid of the trailing blank line there. It was probably misplaced.

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by vanwinkeljan — APPROVED** [review]
+1 for display related changes

**Review by aescolar — COMMENTED** [review]
No complaints from me. (Given that the only meaningful change seems to be the xtensa doc change, I let the respective maintainers be the ones who give approval)

**Review by finikorg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by avisconti — APPROVED** [review]

**Review by ruuddw — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by vanti — APPROVED** [review]

**Comment by galak** [comment]
Marking this TSC to see if we want to merge this for the release.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
doc changes LGTM.

**Comment by carlescufi** [comment]
As per TSC meeting there is no one actively requesting this PR to be merged during the feature freeze window, so it will be deferred until 2.1 is released.

**Review by joerchan — APPROVED** [review]

**Review by franciscomunoz — APPROVED** [review]

**Review by albertofloyd — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]

**Comment by dbkinder** [comment]
Is it a (new) requirement not to have leading/trailing blank lines in these files?  We should document that in our coding/documenting guidelines (and enforce it as we do for trailing white-space on lines).

**Comment by ulfalizer** [comment]
> Is it a (new) requirement not to have leading/trailing blank lines in these files? We should document that in our coding/documenting guidelines (and enforce it as we do for trailing white-space on lines).

Think it's usually a typo, so don't know if it would help to document it.

**Comment by ulfalizer** [comment]
Rebased now.

**Pull request merged**
