### PR TITLE
drivers: rtc: add rtc support for apollo3&3p

### PR DESCRIPTION
**Pull request by AlessandroLuo**
Add RTC support for Apollo3 and Apollo3 Plus Soc

### CODE REVIEW

**Review by aaronyegx — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]
Looks good :)

**Review by RichardSWheatley — COMMENTED** [review]
Was this retested with the Apollo4p?

This was tested using the original code on the ap4p. Code outside the addition for ap3 was modified.

**Comment by RichardSWheatley** [comment]
> Was this retested with the Apollo4p?
> 
> This was tested using the original code on the ap4p. Code outside the addition for ap3 was modified.

@AlessandroLuo my apologies. I should have tested it before commenting.
Works great for the ap4p. I will add the kxr as you suggested.

**Review by RichardSWheatley — APPROVED** [review]
Thank you for removing the empty return statements for ambiq hal alarm set and alarm get.

**Review by bjarki-andreasen — APPROVED** [review]

**Pull request merged**
