### PR TITLE
Update gpio_shell.c

### PR DESCRIPTION
**Pull request by tomaszduda23**
Add pull up/down in gpio shell.

### CODE REVIEW

**Review by stephanosio — CHANGES_REQUESTED** [review]
Please review the [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html).

**Comment by mmahadevan108** [comment]
@tomaszduda23 I see the commit message missing `Signed-off` and a `Commit description` per the below section:
https://docs.zephyrproject.org/latest/contribute/guidelines.html#tools-and-git-setup

Please help add these to the commit.

**Review by cfriedt — DISMISSED** [review]

**Comment by cfriedt** [comment]
Change looks fine. I guess I will need to re-ack when the commit message is amended.

**Review by stephanosio — APPROVED** [review]
Looks reasonable.

**Review by cfriedt — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
