### PR TITLE
doc: releases: remove v3.3.0 from supported releases

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
As of October 31, 2023, Zephyr v3.3.0 is no longer supported.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
I suggest we make an effort to merge the currently open backports against v3.3 prior to merging this PR.

**Review by fabiobaltieri — DISMISSED** [review]

**Review by kartben — CHANGES_REQUESTED** [review]
I'll have a look tomorrow when on a computer but there is at least one other place that needs updating, the "version selector" in the left navigation menu.

**Comment by kartben** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/60311

**Comment by henrikbrixandersen** [comment]
@kartben Updated, thanks.

**Review by kartben — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
