### PR TITLE
sample: net: wifi: reduce timeout for ICMP probe sent by server

### PR DESCRIPTION
**Pull request by gangli02**
DHCPv4 server will probe the offered IP address (send ICMP echo request)
and wait for 1s (default) before offering the address. STA sends out DHCP
discover, but gets no response. Windows automatically assigns the network
card an IP address of 169.254.xx.xx.
So set timeout for ICMP probe sent by the server to 10ms.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Could you add information to the commit message why this change is needed?

**Comment by gangli02** [comment]
> Could you add information to the commit message why this change is needed?

Updated to commit message.

DHCPv4 server will probe the offered IP address (send ICMP echo request) and wait for 1s (default) before offering the address. STA sends out DHCP discover, but gets no response. Windows automatically assigns the network card an IP address of 169.254.xx.xx. So set timeout for ICMP probe sent by the server to 10ms.

**Review by krish2718 — DISMISSED** [review]

**Review by jukkar — COMMENTED** [review]
10 ms sounds like a very short timeout, are you sure there is enough time to get a possible reply before offering the address to the client.
This value is used when checking if there are any duplicate IPv4 addresses in the system, the default value 1 sec is quite large but this 10 ms sounds quite short one. How well have you tested this, would 100 ms value work with Windows?

**Comment by gangli02** [comment]
> 10 ms sounds like a very short timeout, are you sure there is enough time to get a possible reply before offering the address to the client. This value is used when checking if there are any duplicate IPv4 addresses in the system, the default value 1 sec is quite large but this 10 ms sounds quite short one. 

The original intention was to turn off the server icmp probe, so it was set to 10ms. 

> How well have you tested this, would 100 ms value work with Windows?

Sure, from the test results, Windows sends a DHCP discover, and if no DHCP offer is received within about 400ms, it will automatically assign a 169.254.xx.xx. So if it is changed to 100ms, I think it will also work. 

Another question:
The client receives the DHCP ACK message, then it will perform a final check (e.g., ARP for allocated network address). If the client detedts that the address is already in use, it will send a DHCP DECLINE message to the server and restarts the configuration process.
If both the server and the client do ARP, will there be duplication? 
Of course, checking if the IP address is allocated before sending the DHCP OFFER message can avoid the reconfiguration process caused by address conflicts.

**Comment by jukkar** [comment]
> The original intention was to turn off the server icmp probe, so it was set to 10ms.

If you set the value to 0, then the probing is disabled

**Comment by jukkar** [comment]
> The client receives the DHCP ACK message, then it will perform a final check (e.g., ARP for allocated network address). If the client detedts that the address is already in use, it will send a DHCP DECLINE message to the server and restarts the configuration process.

Yes, and when server gets the decline, it will not try to use that address.

> If both the server and the client do ARP, will there be duplication?

This should not cause any problems.

> Of course, checking if the IP address is allocated before sending the DHCP OFFER message can avoid the reconfiguration process caused by address conflicts.

This is what is done in zephyr DHCPv4 server implementation, the offer message is sent after the ICMP probe has timeouted.

**Comment by gangli02** [comment]
> This is what is done in zephyr DHCPv4 server implementation, the offer message is sent after the ICMP probe has timeouted.

Got it, I will change the timeout to 100ms.

**Comment by gangli02** [comment]
@jukkar , I have changed it to 100ms, please review it again.

**Review by krish2718 — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
