### PR TITLE
Bluetooth: controller: radio: Fix compilation error

### PR DESCRIPTION
**Pull request by ppryga-nordic**
Fix compilation error caused by use of wrong header file:
nrfx/hal/nrf_radio.h instead of hal/nrf_radio.h.

Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>

### CODE REVIEW

**Comment by ppryga** [comment]
Noting changes, just re-run build to verify if unit tests failures were an accident.

**Review by cvinayak — APPROVED** [review]
Approved based on dbf9d99

**Review by kruithofa — APPROVED** [review]

**Comment by ppryga** [comment]
Rebased due to merge: https://github.com/zephyrproject-rtos/zephyr/pull/31529. It fixes issues with CI.

**Comment by ppryga** [comment]
@carles can you merge the PR? Thank you in advance!

**Pull request merged**
