### PR TITLE
Revert "logging: Add support to backends to switch log format at runt…

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This reverts commit c0d7e10beb252a4b136bc79e9e4a746e10ebd3f1.

It is causing twister errors on main. To reproduce these errors, run:

$ ./scripts/twister  -T tests/subsys/logging/log_stack -p qemu_leon3

This fails in CI and on my machine with Zephyr SDK 0.13.2.

I don't have a fix at this time, so I am proposing a revert unless a
better idea comes up in the short term.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by nordic-krch** [comment]
@mbolivar-nordic i will take a look and will try to fix it. `log_stack` test is tracking unexpected increase of stack usage by logging. Need to check why stack usage increased. If i don't come back within an hour with counterproposal we can revert to unblock.

**Comment by nordic-krch** [comment]
Adjusted test results: #43160. Though, seems crazy that calling a function pointer increases stack usage by 100 bytes. Other platforms show no increase.

**Comment by mbolivar-nordic** [comment]
Thanks @nordic-krch !

**Comment by andyross** [comment]
> seems crazy that calling a function pointer increases stack usage by 100 bytes.

Welcome to the world of SPARC register windows, and gcc's historical inability (shared with a kinda similar architecture on xtensa, FWIW) to optimize them well.  You push 32 bytes minimum with every frame, and the compiler has a hard time mapping local variables into those 8 registers and tends to use more.  Two such calls (are there two?  I don't remember the PR well) would easily do that.

**Pull request closed without merging**
