### PR TITLE
lib: os: fix comments for final else in if...else if structures

### PR DESCRIPTION
**Pull request by jenmwms**
The final else {} in the if...else if is missing required
comment (non-empty, ';' is not sufficient). This adds a comment 
to comply with CG 15.7.

Signed-off-by: Jennifer Williams <jennifer.m.williams@intel.com>

### CODE REVIEW

**Comment by jenmwms** [comment]
Hi @andyross  - Can you please help me compose a brief comment to describe these final 'else {}' statements across lib/os? 
note : a couple early-return type of structure that could be refactored, but after last time I'm advised that activity should be done by the code owner (you) so I am capturing comment until we can take time to refactor.

**Comment by nashif** [comment]
if this is a draft or work in progress  with placeholders to be replaces, please mark it as such.

**Comment by jenmwms** [comment]
Hi @andyross   Can you please help capture a brief comment to each of these else cases for CG 15.7? Similar to the recent kernel/poll effort in this regard, I need to capture a source code comment to fully close the violation with the code structure as it is. 

(I understand refactoring may be tempting, and as code owner you can always do that in a separate effort. If it gets merged in, I'll just close this PR.)

**Comment by jenmwms** [comment]
Hi @andyross - ping

**Review by andyross — APPROVED** [review]
Looks fine.  The rule is silly, but this explains what the meaning is as well as anything else.  We can always come back and refactor these as the code evolves in the future.

**Comment by jenmwms** [comment]
> Looks fine. The rule is silly, but this explains what the meaning is as well as anything else. We can always come back and refactor these as the code evolves in the future.

Hi @andyross - These generic comments are not sufficient (under my current direction from Anas). We need to update each to be uniquely describing the case. This is similar to the recent kernel/poll effort in this regard, we need to capture a specific source code comment to fully close the violation with the code structure as it is.

**Comment by andyross** [comment]
So we can't refactor the code because that's out of scope but we have to pretend like we knew what we were doing anyway?

... I don't think this is a good use of time, sorry.  Either we bite the bullet and actually refactor code (not comments) to avoid the collision with the coding standard or we just accept that we're blindly following the coding standard and comment the fact that we are.  Trying to retcon an "explanation" for something that doesn't actually have one is doing all the work of the former with none of the long term benefit.

I'm begging off from this, sorry.  It's... I mean, this is just busywork, and I'm really busy.

**Comment by jenmwms** [comment]
> So we can't refactor the code because that's out of scope but we have to pretend like we knew what we were doing anyway?
> 
> ... I don't think this is a good use of time, sorry. Either we bite the bullet and actually refactor code (not comments) to avoid the collision with the coding standard or we just accept that we're blindly following the coding standard and comment the fact that we are. Trying to retcon an "explanation" for something that doesn't actually have one is doing all the work of the former with none of the long term benefit.
> 
> I'm begging off from this, sorry. It's... I mean, this is just busywork, and I'm really busy.

I hear your frustration and respectfully ask that you work with me to find a resolution here. I'm busy, too, and just trying to follow the directions in place for me. 

How about this compromise - please back me up in merging the generic comments (current state of this PR). I see you have approved that status and no further changes are needed.

**Review by laurenmurphyx64 — APPROVED** [review]

**Review by yerabolu — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
i'd rather close this PR and leave the violation in place and not merge those generic comments. Either refactor, or explain why this is happening, but please let's not add such comments, this serves no purpose and few violations more among the other 1000s are not going harm anything.

Keeping the violation in place will always be a reminder that something needs to be fixed here. 

Besides, most of this is not really @andyross related, lib/os is maintained by many others.

**Comment by jenmwms** [comment]
> i'd rather close this PR and leave the violation in place and not merge those generic comments. Either refactor, or explain why this is happening, but please let's not add such comments, this serves no purpose and few violations more among the other 1000s are not going harm anything.
> 
> Keeping the violation in place will always be a reminder that something needs to be fixed here.
> 
> Besides, most of this is not really @andyross related, lib/os is maintained by many others.

Thanks for the feedback. After our sync offline today, I will transition this final effort to Andy to keep this on the radar to take care of. Thanks for all the cycles to make progress and get to a point of agreement and handoff.

**Pull request closed without merging**
