### PR TITLE
boards: arm: fix gpio-led flags on adi_eval_adin1110ebz/adin2111ebz

### PR DESCRIPTION
**Pull request by jpmur**
This board's user LEDs are active-LOW, instead of active-HIGH

image image
(adi_eval_adin1110ebz) (adi_eval_adin2111ebz)

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]
Similar change needed for `adi_eval_adin2111ebz`?

**Review by MaureenHelm — DISMISSED** [review]
@spectrum70 @pamolloy

**Comment by nashif** [comment]
rebase please

**Comment by jpmur** [comment]
> rebase please

Done

**Review by MaureenHelm — APPROVED** [review]

**Comment by jpmur** [comment]
@nashif This PR has been sitting for some time - I think it can be merged.

**Comment by MaureenHelm** [comment]
@carlocaione mind taking a quick look?

**Comment by spectrum70** [comment]
Hi,, testing this.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
