### PR TITLE
posix: convert static inline functions to library functions

### PR DESCRIPTION
**Pull request by cfriedt**
With `CONFIG_NET_SOCKETS_POSIX_NAMES` being deprecated, convert static inlines in headers to prototypes, and move implementations to `lib/posix/options/net.c`.

Since select and poll should technically also operate on non-socket file descriptors, these may be relocated in the future.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
> convert static inlines in headers to prototypes, and move implementations to lib/posix/options/net.c

No real objection to this, but why we couldn't leave the static inline functions in place?
This somewhat important information is missing from commit msg.

**Comment by cfriedt** [comment]
> why we couldn't leave the static inline functions in place?

Good question.

The main reason is that we want posix api functions to be regular library function symbols that are not directly associated with a Zephyr system call.

I would say, the secondary (although probably more important reason) is that many posix functions also act as pthread cancellation points (something that still needs to be implemented across the board).

The third reason is space and flexibility.  Additionally, the more that is added to an inline function, the less sense it makes to be inline to begin with. Implementation details may vary but the API should remain relatively untouched (we want to avoid surprises when making implementation adjustments and it helps to encapsulate that in a .c file).

> This somewhat important information is missing from commit msg.

I'll update the commit message.

**Review by ycsin — APPROVED** [review]

**Comment by cfriedt** [comment]
* added additional notes to the commit message

**Review by jukkar — APPROVED** [review]
Thanks!

**Review by pdgendt — APPROVED** [review]

**Pull request merged**
