### PR TITLE
tests: posix: remove unrelated tags

### PR DESCRIPTION
**Pull request by nashif**
Remove unrelated tags: net, socket.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]

**Review by cfriedt — CHANGES_REQUESTED** [review]
Network and socket calls are tested to ensure they are available with the POSIX api

**Comment by cfriedt** [comment]
> Network and socket calls are tested to ensure they are available with the POSIX api

I can also see crc as being pretty critical for a lot of networking topics.

**Comment by nashif** [comment]
> Network and socket calls are tested to ensure they are available with the POSIX api

This is however testing posix, not networking or sockets. By that logic we will be adding tags for everything being called in those tests.

**Comment by nashif** [comment]
> I can also see crc as being pretty critical for a lot of networking topics.

ditto

**Comment by cfriedt** [comment]
> > Network and socket calls are tested to ensure they are available with the POSIX api
> 
> This is however testing posix, not networking or sockets. By that logic we will be adding tags for everything being called in those tests.

If someone changes network or socket code, these tests should be run to check that there have been no regressions.

Is that not how tags work anymore?

**Comment by nashif** [comment]
> If someone changes network or socket code, these tests should be run to check that there have been no regressions.

yes, that is what happens right now. But if you change posix subsystem, this specific test will be excluded. This is a broken logic the way we have it and we are trying to fix this with https://github.com/zephyrproject-rtos/zephyr/pull/65257/.

In the maintainer file we could have:

```
"Networking: BSD sockets":
  status: odd fixes
  collaborators:
    - rlubos
    - jukkar
  files:
    - samples/net/sockets/
    - subsys/net/lib/sockets/
    - tests/net/socket/
  labels:
    - "area: Sockets"
  tests:
    - net.socket
    - portability.posix.headers
    - ```

which will run the posix test when ever the socket subsystem is changed and if posix changed, it will run the posix tests as expected.

Tag importance for picking what tests will run will go away once the above PR is merged, this PR trying to mitigate around issues we have seen in the posix area where changes go in and they are not tested because of bad logic and the net tag.

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
