### PR TITLE
modules: cmsis: fix Cortex-A support

### PR DESCRIPTION
**Pull request by JiafeiPan**
CMSIS Cortex-A only supports AARCH32, remove dependency on
AARCH64 Cortex-A.

Signed-off-by: Rui Sousa <rui.sousa@nxp.com>

### CODE REVIEW

**Comment by JiafeiPan** [comment]
Dear maintainers, any comments for this PR? thanks.

**Comment by JiafeiPan** [comment]
Hi, @nashif, would you help to review this patch or anybody else? thanks.

**Comment by JiafeiPan** [comment]
@povergoing , would you please help to review this PR, thanks.

**Review by povergoing — APPROVED** [review]

**Comment by JiafeiPan** [comment]
@carlocaione would you please help to review this patch, thanks.

**Review by carlocaione — APPROVED** [review]

**Pull request merged**
