### PR TITLE
board/iotdk: Add support of cmsis_rtos_v2_apis on iotdk board

### PR DESCRIPTION
**Pull request by chen-png**
When running cmsis_rtos_v2_apis on iotdk board, it will read the unallocated stack region, this 
operation is not allowed by the stack checking of iotdk board. So we modify the iotdk board  config to close the stack checking in this testcase, thus it can support cmsis_rtos_v2_apis running successfully on iotdk board.
Fix_issue: #17852 
Signed-off-by: chen-png <peng1.chen@intel.com>

### CODE REVIEW

**Review by ruuddw — CHANGES_REQUESTED** [review]
Disabling stack checking on board level doesn't seem to be the right solution, I suggest you fix the test (or, disable it for this test only - I don't know the test details, but cmsis-rtos api test doesn't seem relevant for ARC)

**Review by LeiW000 — APPROVED** [review]
It looks good to me. 

I don't think the failure in "Shippable" has anything to do with this change. It must be caused by another commit, which has been merged.

**Comment by LeiW000** [comment]
Hi Ruuddw:
   Could you help to take look at the code?  Thanks.

**Review by ruuddw — APPROVED** [review]
ok, disabling stack checking is local to this test now.
It would be even better to fix the test so it doesn't access unallocated stack memory!

**Comment by andrewboie** [comment]
> It would be even better to fix the test so it doesn't access unallocated stack memory!

It's not really the test, it's the way stack_analyze() works unfortunately.
The stack buffer is filled with 0xAA bytes at thread initialization, and then the buffer is scanned to see how much of it is still there. The fix needs to be in stack_analyze() when it tries to examine the currently running thread.

**Comment by ruuddw** [comment]
I remember the stack_analyze() issue, indeed that's not really part of this PR. And, no easy workaround. ok to skip ARC for this test, though I'd prefer a finer grain exclusion of only the test for 'free' stack so the other tests are covered.

**Comment by chen-png** [comment]
Hi Anas:
Could you take a look at this workaround and is it acceptable?

**Review by vonhust — CHANGES_REQUESTED** [review]
Not only iotdk, but all arc targets with stack checking will fail on this tests. So my suggestion is for all arc targets, disable stack checking for this test

**Comment by andrewboie** [comment]
I think the approach should be as follows:

1) Update the documentation for stack_analyze() to indicate that it shouldn't be called on the stack for the currently running thread.
2) Update the test so that the test doesn't analyze the stack of the currently running thread. It's OK to analyze another thread, just not the currently running one.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
as indicated, let's fix the test so it doesn't analyze stack of a currently running thread

**Comment by chen-png** [comment]
see #22520 .

**Pull request closed without merging**
