### PR TITLE
fix CONFIG_STACK_CANARIES with CONFIG_USERSPACE

### LINKED ISSUE #13642: stack canaries don't work with user mode threads
Enabling CONFIG_STACK_CANARIES breaks user mode threads. Entering any function will result in a memory protection error, for example on x86:

```
***** CPU Page Fault (error code 0x00000004)
User thread read address 0x00413000
PDE: 0x027 Present, Writable, User, Execute Enabled
PTE: 0x800000002 Non-present, Writable, Supervisor, Execute Disable
Current thread ID = 0x004021c0
eax: 0x00001398, ebx: 0x00400033, ecx: 0x00000ffc, edx: 0x00409000
esi: 0x00407000, edi: 0x00409fe8, ebp: 0x00409fe4, esp: 0x00409fd0
eflags: 0x00000246 cs: 0x002b
call trace:
eip: 0x0000253f
Fatal fault in thread 0x004021c0! Aborting.
```

The memory address 0x00413000 points to __stack_chk_guard:

```
(gdb) x/fx 0x00413000
0x413000 <__stack_chk_guard>:	0x589a24a0
```

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Stack canaries rely on a global variable containing the generated stack canary value. This was faulting from user threads since the storage area is in kernel memory. Now it is stored in a generic partition for C library globals.

Fixes #13642

### CODE REVIEW

**Comment by lpereira** [comment]
Seems sane.

(That shared space is good for other things, too.  For instance, to obtain system globals, like the current uptime, you can avoid syscalls.)

**Review by ioannisg — APPROVED** [review]
Looks OK to me, pls, fix the conflicts.

**Comment by andrewboie** [comment]
Don't merge this yet -- in further testing, when I enable stack canaries globally for qemu_x86, seeing failures...digging in to see what's going on

**Review by andyross — APPROVED** [review]
Can't see anything wrong, to the extent of my familiarity with stack canaries.

But aesthetically, this seems sorta cart-before-the-horse.  A more generic TLS framework would have made this trivial.

**Review by nashif — APPROVED** [review]

**Comment by andrewboie** [comment]
> But aesthetically, this seems sorta cart-before-the-horse. A more generic TLS framework would have made this trivial.

I don't disagree, but that has to wait until the merge window opens for 1.15

**Pull request merged**
