### PR TITLE
dts: fixes around uart node

### PR DESCRIPTION
**Pull request by erwango**
This PR proposes 4 differents fixes:

*fix stm32f469i_disco copy/paste error in board fixup file
*create uart node a part from usart node as uart not could not be compiled as of now
*update uart node from uart@ to serial@ to align with stm32 linux dtsi files
*rework stm32f4 dtsi family tree

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Will wait on PR #211 to get merged, as that will impact this.  Otherwise looks good.

**Comment by galak** [comment]
PR #211 is merged so a rebase should pick the changes I mentioned

**Comment by erwango** [comment]
Push issue.. Don't take latest commits into account

**Comment by erwango** [comment]
@atorgue, can you review this?

**Review by galak — CHANGES_REQUESTED** [review]
Rather than duplicating the UARTs in the various SoC dts, how about using /delete-node/ to remove them in the SoC specific files?

**Comment by erwango** [comment]
I'm affraid this won't work. This means put all IPs in a common file and it happens there could be divergences in a same series that end up in incompatible properties for some nodes.
For instance STM32F407 and STM32F413 are both supersets of STM32F411, STM32F469 is a superset of STM32F407 but:
STM32F469: QUADSPI IRQ = 91
STM32F413: QUADSPI IRQ = 92
This is the first example I found on the F4 boards available in Zephyr, there might be much more  on other STM32 boards out there.

**Review by galak — APPROVED** [review]

**Pull request merged**
