### PR TITLE
net: tcp: Extend TCP receive queue timeout

### PR DESCRIPTION
**Pull request by ssharks**
After several fixes of the re-ordering logic in TCP, the receive queue works as intended and cleans itself up properly. Previously the default timeout was 100 ms, which pretty much disables it for real applications.

Increase the timeout to 5 seconds to actually enable it for in practice. This should help pass much more of the Maxwell Pro tests.

This is the first step before removing the timeout completely.

Signed-off-by: Sjors Hettinga <s.a.hettinga@gmail.com>

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Five seconds timeout feels very long, as we have limited number of network buffers usually and we would easily run out of them if there is reasonable amount of network traffic. Perhaps we could have a bit lower timeout value, wdyt?

**Comment by jukkar** [comment]
BTW, I would not be too concerned about maxwell pro tests. They are probably more optimized for bigger machines with more resources than zephyr. We should set the defaults so that it fits to zephyr use cases, and not try to optimize it with some testing tool.

**Comment by rlubos** [comment]
I agree with @jukkar, 100ms might be too short, but 5 seconds seems to be too long indeed, given that AFAIR the initial retransmission time is like 200 ms?

**Comment by ssharks** [comment]
The receive queue is only activated in case of out of order data. It holds out of order data for the missing packet to arrive. This missing packet should be either be send as a consequence timeout, which is at least 1 second for PC TCP stacks or be activated by a triple duplicate ACK (meaning the TCP receive queue needs to be >= 4 * MSS). Usually this needs at least 100 ms to be triggered.

With the latest fixes in upon reception the new packet is combined with the existing queued data throwing out (partially duplicate) data. Apart from maybe some addition buffers due to boundary conditions, the receive queue should never contain more buffers than would fit in the TCP receive queue for that reason.

To work properly in real situations, the receive queue should be at least 2 seconds. Would that be a better value?

**Comment by rlubos** [comment]
> To work properly in real situations, the receive queue should be at least 2 seconds. Would that be a better value?

I'd say to stick to the reasonable minimum (suggested 2 seconds).

**Comment by jukkar** [comment]
Two seconds sounds much better than five. So +1 from me.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
