### PR TITLE
ITE: drivers/i2c: it8xxx2: add mutex lock

### PR DESCRIPTION
**Pull request by GTLin08**
Add mutex lock to prevent race conditions.

Signed-off-by: Tim Lin <tim2.lin@ite.corp-partner.google.com>

---
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/36684)

### CODE REVIEW

**Review by keith-zephyr — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/36684)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brockus-zephyr and @sjg20)

**Review by brockus-zephyr — APPROVED** [review]
Verified it locally

**Review by brockus-zephyr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/36684)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sjg20)

**Comment by nashif** [comment]
what is the story with 'Reviewable'?

**Comment by keith-zephyr** [comment]
> what is the story with 'Reviewable'?

The  extra comment is inserted by https://reviewable.io/.  I'm not sure if there is a setting to disable adding the extra context.  I and couple team members are trying out reviewable in hopes that it provides a better PR review interface than the Github interface.

**Pull request merged**
