### PR TITLE
input: unify gpio-keys and zephyr,gpio-keys

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Hi, this is a proposal to merge the `gpio-keys` and `zephyr,gpio-keys` bindings. The two were originally split out because the `zephyr,` one was living under GPIO at the time, which is pretty much always enabled and would have taken over all the samples using the GPIO directly. This is not much the case anymore as the driver is now behind `CONFIG_INPUT`, which is disabled by default.

I'm proposing to merge back the two bindings and eventually get rid of the `zephyr,gpio-keys` one. This would make `gpio-keys` works similarly to `gpio-leds`, where the LED subsystem driver takes over only when the subsystem is enabled.

~~As part of this I'll set input codes for all the current in-tree boards, only did the `nrf*` ones in this example just to start the discussion (there's 300+ to be changed, won't bother if we decide to not do this).~~

This would be useful to have boards working with input out of the box, but also for samples that wants to use the debounced input key driver.

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]
+1

**Review by jfischer-no — DISMISSED** [review]
+1

**Review by tmon-nordic — DISMISSED** [review]
This would allow to get rid of the overlay in #61104 completely if the sample was converted to just use INPUT_KEY_ codes directly.

**Comment by fabiobaltieri** [comment]
Alright I added a bunch of input code definitions, set about a million input codes (mostly KEY_0... or KEY_A... but not always) and fixed few other issues I bumped into.

Also ended up adding an extra patch to delete the `zephyr,gpio-keys` entirely... figured that since the API is unstable we may as well treat it as such.

Good to go for what I'm concerned, let me know what you think.

**Review by gmarull — APPROVED** [review]

**Review by nandojve — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
