### PR TITLE
net: lwm2m: Fix overlapping buffers

### LINKED ISSUE #64011: lwm2m: Resource instance buffers are overlapping
**Describe the bug**
 
When LwM2M object gives engine a buffer for multiple resource instances using for example `INIT_OBJ_RES_MULTI_DATA_LEN()` macro, the engine does not calculate buffer pointers correctly.

Second resource instance will get a buffer that is 1 byte pass the first instance.
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/lwm2m/lwm2m_object.h#L254 uses loop index to calculate start of next buffer. It should use buffer size as well.

**To Reproduce**
1. Run LwM2M client
2. Create portfolio object (16)
3. write "a" to `16/0/0/0`
4. write "b" to `16/0/0/1`
5. Read `16/0/0/0` which now contains `ab`.

**Expected behavior**
Buffers should not overlap

**Impact**
Fortunately, this is only visible on Portfolio object, as rest of the objects don't statically set the buffers for resource instances.

### PR DESCRIPTION
**Pull request by SeppoTakalo**
## net: lwm2m: Properly initialize buffers for resource instance
      
When resource instances are initialized, we must calculate
beginning of the data buffer using the index and maximum
data length. Otherwise buffers would overlap with previous.
      
Fixes #64011

## net: lwm2m: Count nul terminator in string size

As the lwm2m_registry.c and specificly lwm2m_set()
functions already ensure null-terminator on string and
count that into string lenght, the content type handlers
should do the same.

When string is written, strlen()+1 is the data length.
When string is read, use the data length, so we don't
leak uninitialized strings. If buffer overrun have
removed the null-terminator the strlen() migh be larger
than data_len.

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]

**Comment by SeppoTakalo** [comment]
Hold on until merging this. I found issue with the fix also.

Fix: Pointer arithmetics previously worked on static sizes (uint8_t, uint16_t, uint32_t, etc), but not on char or opaque buffers. Now they work on opaque buffers and strings, but are broken on fixes sizes.

The macro needs to be `(uint8_t *) data_ptr + (i * data_size)`  so that pointer is first converted to object pointer that is size of 1, then we can calculate the correct offset. This is because these are macros, and sometimes the data_ptr was pointing to, for example, `uint32_t` so `data_ptr +1` is same as data_ptr going forward `sizeof(uint32_t)`.

**Comment by SeppoTakalo** [comment]
Secondly: Fixing the content formatters to respect the `data_len` reveals that many objects don't properly initialize the len. So we leak strings with lots of null-terminator.
For example, device object's binding mode should be `"U"`, but in SenML-CBOR you get `"U\0\0\0\0"`.

I'll try to fix those that I find.

**Comment by SeppoTakalo** [comment]
Mentioned issues now fixed in this PR.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@SeppoTakalo @rlubos setting milestone to 3.6, please reach out if you think this should be a blocker for 3.5

**Comment by SeppoTakalo** [comment]
@fabiobaltieri that is fine.

Only real object that is broken, is the Portfolio object, that has no other uses that being used in the interoperability tests.

**Pull request merged**
