### PR TITLE
boards: renesas: Add I2C support for Renesas RA4, RA2 devices

### PR DESCRIPTION
**Pull request by khoa-nguyen-18**
Enable I2C support on these boards:
- ek_ra4w1
- ek_ra4m2
- ek_ra4m3
- ek_ra2a1

### CODE REVIEW

**Review by thaoluonguw — DISMISSED** [review]
It looks good to me.

**Review by soburi — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by khoa-nguyen-18** [comment]
just rebase main to solve conflicts

**Review by soburi — DISMISSED** [review]

**Review by duynguyenxa — DISMISSED** [review]

**Comment by kartben** [comment]
@khoa-nguyen-18 conflicting again :/

**Comment by khoa-nguyen-18** [comment]
> @khoa-nguyen-18 conflicting again :/

I have rebased and solved conflicts, sorry for this inconvenience.

**Review by soburi — DISMISSED** [review]

**Comment by khoa-nguyen-18** [comment]
@teburd Could you please revisit this PR?

**Review by soburi — APPROVED** [review]

**Review by thaoluonguw — APPROVED** [review]

**Review by KhiemNguyenT — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Pull request merged**
