### PR TITLE
tests/schedule_api: Correct tick/ms math for non-divisible clocks

### LINKED ISSUE #29705: reel_board: tests/kernel/sched/schedule_api/ fails on multiple boards
EDIT: Affects multiple Nordic boards and mec15xxevb_assy6853

**Describe the bug**
Running tests/kernel/sched/schedule_api/ on reel board. Assertion in test_slice_reset failed in both kernel.scheduler and kernel.scheduler.multiq testcases. 

**To Reproduce**
1. west build -p auto -b reel_board tests/kernel/sched/schedule_api/
2. west flash

**Expected behavior**
Test should pass.

**Impact**
Test suite fails.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-1133-ge4e3ab3cc315  ***
Running test suite threads_scheduling
===================================================================
START - test_bad_priorities
PASS - test_bad_priorities
===================================================================
START - test_priority_cooperative
PASS - test_priority_cooperative
===================================================================
START - test_priority_preemptible
PASS - test_priority_preemptible
===================================================================
START - test_priority_preemptible_wait_prio
PASS - test_priority_preemptible_wait_prio
===================================================================
START - test_yield_cooperative
PASS - test_yield_cooperative
===================================================================
START - test_sleep_cooperative
PASS - test_sleep_cooperative
===================================================================
START - test_sleep_wakeup_preemptible
PASS - test_sleep_wakeup_preemptible
===================================================================
START - test_pending_thread_wakeup
PASS - test_pending_thread_wakeup
===================================================================
START - test_time_slicing_preemptible
PASS - test_time_slicing_preemptible
===================================================================
START - test_time_slicing_disable_preemptible
PASS - test_time_slicing_disable_preemptible
===================================================================
START - test_lock_preemptible
PASS - test_lock_preemptible
===================================================================
START - test_unlock_preemptible
PASS - test_unlock_preemptible
===================================================================
START - test_unlock_nested_sched_lock
PASS - test_unlock_nested_sched_lock
===================================================================
START - test_sched_is_preempt_thread
PASS - test_sched_is_preempt_thread
===================================================================
START - test_slice_reset
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:91: thread_time_slice: (t <= expected_slice_max is false)
timeslice too big, expected 6555 got 7208
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:88: thread_time_slice: (t >= expected_slice_min is false)
timeslice too small, expected 6553 got 617
FAIL - test_slice_reset
===================================================================
START - test_slice_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
PASS - test_slice_scheduling
===================================================================
START - test_priority_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
PASS - test_priority_scheduling
===================================================================
START - test_wakeup_expired_timer_thread
PASS - test_wakeup_expired_timer_thread
===================================================================
START - test_user_k_wakeup
PASS - test_user_k_wakeup
===================================================================
START - test_user_k_is_preempt
PASS - test_user_k_is_preempt
===================================================================
Test suite threads_scheduling failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS
 - Toolchain Zephyr SDK 0.11.2
 - Zephyr version zephyr-v2.4.0-1133-ge4e3ab3cc315

### PR DESCRIPTION
**Pull request by andyross**
Adjusting the tick alignment of this test caused it to start breaking
on nRF5 platforms, which use a 32768 Hz clock that doesn't divide
evenly into the millisecond precision used by the test.  The "half
slice" math ended up being wrong by a bit.

Convert to ticks first before computing the cycle delay needed.

Fixes #29705

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by andyross** [comment]
This should fix the problem detailed in #29705 , unfortunately my Nordic board seems to have given up the ghost, so I can't test it directly.  DNM for now pending confirmation on hardware.

@maksimmasalski @pabigot @ioannisg if you guys have cycles to verify that would be helpful.

**Comment by pabigot** [comment]
Still fails:
```
*** Booting Zephyr OS build zephyr-v2.4.0-1658-g9b24fa78c586  ***
Running test suite threads_scheduling
===================================================================
START - test_bad_priorities
 PASS - test_bad_priorities
===================================================================
START - test_priority_cooperative
 PASS - test_priority_cooperative
===================================================================
START - test_priority_preemptible
 PASS - test_priority_preemptible
===================================================================
START - test_priority_preemptible_wait_prio
 PASS - test_priority_preemptible_wait_prio
===================================================================
START - test_yield_cooperative
 PASS - test_yield_cooperative
===================================================================
START - test_sleep_cooperative
 PASS - test_sleep_cooperative
===================================================================
START - test_sleep_wakeup_preemptible
 PASS - test_sleep_wakeup_preemptible
===================================================================
START - test_pending_thread_wakeup
 PASS - test_pending_thread_wakeup
===================================================================
START - test_time_slicing_preemptible
 PASS - test_time_slicing_preemptible
===================================================================
START - test_time_slicing_disable_preemptible
 PASS - test_time_slicing_disable_preemptible
===================================================================
START - test_lock_preemptible
 PASS - test_lock_preemptible
===================================================================
START - test_unlock_preemptible
 PASS - test_unlock_preemptible
===================================================================
START - test_unlock_nested_sched_lock
 PASS - test_unlock_nested_sched_lock
===================================================================
START - test_sched_is_preempt_thread
 PASS - test_sched_is_preempt_thread
===================================================================
START - test_slice_reset

    Assertion failed at ../src/test_sched_timeslice_reset.c:91: thread_time_slice: (t <= expected_slice_max is false)
timeslice too big, expected 6555 got 7204

    Assertion failed at ../src/test_sched_timeslice_reset.c:88: thread_time_slice: (t >= expected_slice_min is false)
timeslice too small, expected 6553 got 474
 FAIL - test_slice_reset
===================================================================
START - test_slice_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
 PASS - test_slice_scheduling
===================================================================
START - test_priority_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
 PASS - test_priority_scheduling
===================================================================
START - test_wakeup_expired_timer_thread
 PASS - test_wakeup_expired_timer_thread
===================================================================
START - test_user_k_wakeup
 PASS - test_user_k_wakeup
===================================================================
START - test_user_k_is_preempt
 PASS - test_user_k_is_preempt
===================================================================
Test suite threads_scheduling failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Comment by maksimmasalski** [comment]
> This should fix the problem detailed in #29705 , unfortunately my Nordic board seems to have given up the ghost, so I can't test it directly. DNM for now pending confirmation on hardware.
> 
> @maksimmasalski @pabigot @ioannisg if you guys have cycles to verify that would be helpful.

Great! I will try test it on the Microchip and reel board.

**Comment by maksimmasalski** [comment]
reel_board result
```
START - test_slice_reset

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:91: thread_tim)
timeslice too big, expected 6555 got 7187

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:88: thread_tim)
timeslice too small, expected 6553 got 612
 FAIL - test_slice_reset
```

Can't test Microchip, can't access it remotely today(

**Comment by maksimmasalski** [comment]
Same on the Microchip mec15xxevb_assy6853
```
START - test_slice_reset

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/)
timeslice too big, expected 6555 got 7208

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/)
timeslice too small, expected 6553 got 599
 FAIL - test_slice_reset

```

**Comment by andyross** [comment]
It's surely going to be the same on all these boards, they have exactly the same timer configuration.  I'm going to need to head to the office at some point and dig up hardware, I suspect.

**Comment by maksimmasalski** [comment]
> It's surely going to be the same on all these boards, they have exactly the same timer configuration. I'm going to need to head to the office at some point and dig up hardware, I suspect.

I would like to join you if I can! Unfortunately, at my home working location I don't have any measurement equipment like oscilloscope.

**Comment by PerMac** [comment]
@andyross  Any luck with solving the issue?

**Comment by andyross** [comment]
Merged as part of a different PR, kill this one

**Pull request closed without merging**
