### PR TITLE
Bluetooth: Controller: Build vendor LLL as library

### PR DESCRIPTION
**Pull request by cvinayak**
Build vendor LLL as separate library so that independent compiler flags can be supplied if required.

### CODE REVIEW

**Comment by cvinayak** [comment]
@dleach02 as a codeowner of openisa, could you review the changes I have done to CMakelists (the building is covered in CI though) and hope its fine on target.

**Review by thoh-ot — APPROVED** [review]

**Comment by cvinayak** [comment]
@henrikbrixandersen @MaureenHelm This PR is only refactoring the CMakelists, the builds are covered in the CI, and only need a second approval from @dleach02 as a codeowner of openisa. Can this be included in Zephyr v3.6?

**Review by kruithofa — APPROVED** [review]

**Comment by cvinayak** [comment]
Added DNM, until an approval from @dleach02

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen @MaureenHelm This PR is only refactoring the CMakelists, the builds are covered in the CI, and only need a second approval from @dleach02 as a codeowner of openisa. Can this be included in Zephyr v3.6?

Unfortunately, this has not yet been approved. We are a bit too late in the release process (hard freeze is tomorrow) to bring in this kind of refactoring, sorry. I have removed this from the v3.6.0 milestone.

**Comment by aescolar** [comment]
@dleach02, please note your review is gating this PR

**Comment by aescolar** [comment]
@cvinayak do you still want to gate this PR merge until @dleach02 's review? or should it just be merged?

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
apologies for not seeing this... HWMv2 distracted me

**Comment by fabiobaltieri** [comment]
hey @cvinayak, I just bisected an issue to this PR, since this my nrf52 devices are getting a random address every time and the log shows:

```
[00:00:00.477,447] <wrn> bt_id: No static addresses stored in controller                                                               
```

Is this something you could look into?

**Pull request merged**
