### PR TITLE
Add support for nRF54H20 to nrfutil runner

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Comment by gmarull** [comment]
Note: compliance failure doesn't provide enough context to resolve the issue (if relevant at all)

```
Check warning on line 1 in scripts/west_commands/tests/test_nrf.py

GitHub Actions
/ Run compliance checks on patch series (PR)
R0801
scripts/west_commands/tests/test_nrf.py:1 Similar lines in 2 files
```

**Review by carlescufi — DISMISSED** [review]
LGTM, reviewed offline

**Review by anangl — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Review by tmon-nordic — DISMISSED** [review]

**Review by tmon-nordic — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]
not sure what the deal with that warning is either, can't even make it fire locally

**Review by tejlmand — CHANGES_REQUESTED** [review]
> elftools are part of the Zephyr requirements.txt, Python will be
explicit enough if a module is missing. Adding install instructions is
also a poor approach, because it may depend on the environment user is
working on so there's a chance it's inacurate.

This is not the reason.
The core reason is described here:
https://github.com/zephyrproject-rtos/zephyr/blob/c45026fc084ff28d70608ef8625991d4acec3ebc/scripts/west_commands/runners/core.py#L386-L392

Remember that all runners will loaded by the west extension, even if they are not used in the current instance.

Surely, `elftools` is part of Zephyr requirements, but if we start to differentiate between package A and B, then we easily end in a situation where one bad runner can impact several users who don't care.
For this reason I actually think the current distinction between standard and non-standard-library modules is the cleanest split.

And as long as this requirement exists in `core.py`, then we should not remove the current implementation as it actually follows the described design rule.

**Review by tejlmand — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
