### PR TITLE
soc: nxp: ke1xf: set ip clock in dts

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Move the selection of the IP clock source for the modules in the NXP
Kinetis KE1xF SoCs from being hardcoded in soc.c to being specified in
the device tree.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Can I ask why?

We might also want a header in `include/dt-bindings/clock/` so that these magic numbers are easier to read, however I'm concerned with the defines sync with the HAL.

**Comment by henrikbrixandersen** [comment]
> Can I ask why?

The different modules in the SoC come with their own prescalers and ability to select the IP clock source. In order to meet e.g. a specific sample rate of the ADC12 module you need to match the IP clock frequency and the prescaler/divider.

Another use-case is to fully disable any unused clocks in order to reduce power consumption. Currently, Zephyr only supports RUN mode on the KE1xF series, but I have pending patches to implement VLPR and HSRUN modes.

I am working with a few custom boards (out-of-tree) that have rather strict timing requirements for their peripherals, and I would like to be able to specify the full clocking scheme, including the IP clock source, for these boards.

> We might also want a header in `include/dt-bindings/clock/` so that these magic numbers are easier to read, however I'm concerned with the defines sync with the HAL.

The "magic" numbers are (conceptually, at least) SoC specific - same as the offset for the given clock register in the PCC module. The good part is, that the number is written verbatim to the PCS register in the PCC. I don't think this necessarily calls for another header, but I can add one if needed.

**Comment by ioannisg** [comment]
@MaureenHelm should we try to push this in 2.0?

**Comment by henrikbrixandersen** [comment]
recheck

**Comment by ioannisg** [comment]
@MaureenHelm ping

**Comment by henrikbrixandersen** [comment]
@MaureenHelm Anything preventing this from going into the tree?

**Review by MaureenHelm — COMMENTED** [review]
I like this idea, as it allows an application to change the peripheral clock source with a dts overlay. I think I could have used this to speed up the counter API tests for Kinetis.

Please have a look at the shippable failures.

**Comment by galak** [comment]
> I like this idea, as it allows an application to change the peripheral clock source with a dts overlay. I think I could have used this to speed up the counter API tests for Kinetis.
> 
> Please have a look at the shippable failures.

If we go down this path, we should probalby introduce a `include/dt-bindings/clock/kinetis_pcc.h` that has #defines for the magic values.

**Review by galak — CHANGES_REQUESTED** [review]
Add a header that defines the magic numbers.

**Comment by henrikbrixandersen** [comment]
> Add a header that defines the magic numbers.

@galak Header added.

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
