### PR TITLE
soc/intel_adsp: Fix the PFN width in cavs-fw.py loader

### PR DESCRIPTION
**Pull request by smrtos**
Change the PFN field width from 54 to 55 to follow the Linux Doc.
(https://www.kernel.org/doc/html/latest/admin-guide/mm/pagemap.html)
Otherwise issue may arise if physical address beyond 2^66 is mapped.

Refactor the v15 and v25 scripts to extract the common part.
This is to suppress the pylint duplicate code check.

Signed-off-by: Shao Ming <ming.shao@intel.com>

### CODE REVIEW

**Review by andyross — APPROVED** [review]

**Review by KangJianX — CHANGES_REQUESTED** [review]
Should fix the CI failures.

**Review by peter-mitsis — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by chen-png — APPROVED** [review]

**Comment by smrtos** [comment]
The CI failed for this pylint issue:

`R0801: Similar lines in 2 files`

According to [here](https://pycodequ.al/docs/pylint-messages/r0801-duplicate-code.html), it suggests code refactoring, which doesn't mean much here.

According to [here](https://github.com/PyCQA/pylint/issues/3239#issuecomment-553002656), it is a false positive and can be worked around by tuning the pylint settings in CI.

Anyone could help here?

**Comment by smrtos** [comment]
> Should fix the CI failures.

The CI failed for this pylint issue:

`R0801: Similar lines in 2 files`

According to [here](https://pycodequ.al/docs/pylint-messages/r0801-duplicate-code.html), it suggests code refactoring, which doesn't mean much here.

According to [here](https://github.com/PyCQA/pylint/issues/3239#issuecomment-553002656), it is a false positive and can be worked around by tuning some pylint settings in CI.

Anyone could help here?

**Review by andyross — APPROVED** [review]
The CI warning isn't fixable here.  These files really are nearly identical, they're in tree like this only because I ran out of time trying to make it work as a unified file.

**Review by KangJianX — APPROVED** [review]

**Comment by smrtos** [comment]
It seems a lot of people are having such issue with pylint.
And pylint is lacking the ability to suppress this warning.  (https://github.com/PyCQA/pylint/issues/214)
If there's no other way out, I guess I'll have to refactor the 2 script files.

**Comment by smrtos** [comment]
The pylint check passed. Finally!

**Pull request merged**
