### PR TITLE
Fix a writing mistake

### PR DESCRIPTION
**Pull request by xiaoliang314**

### CODE REVIEW

**Comment by ioannisg** [comment]
@xiaoliang314 , thanks for you contribution. Would you mind checking out the project contribution guidelines here: http://docs.zephyrproject.org/contribute/contribute_guidelines.html and polish your PR? Thanks!

**Comment by xiaoliang314** [comment]
@ioannisg Thank you for the documentation, I am very willing to follow it.

**Comment by pfalcon** [comment]
@xiaoliang314, for example, I'd suggest to use the commit title of: "Bluetooth: mesh: Fix missing semicolon at the end of statement"

**Comment by jhedberg** [comment]
@xiaoliang314 are you going to update this PR with the suggested fixes? It's basically only the commit message that you need to fix up. The commit message summary can be like @pfalcon suggested. Additionally you need a short body to the commit message (can be just a simple sentence) and then you also need a Signed-off-by line (which git will auto-generate for you when you pass -s to git commit).

**Comment by xiaoliang314** [comment]
@pfalcon @jhedberg Thank you for your guidance. This is my first time using github. Now, I think I know what to do.

**Comment by pfalcon** [comment]
@xiaoliang314 : Great! Please let us know if you're able to update this PR in next 1-2 days. Zephyr's 1.13 release is just around the corner, and it would be nice to get this patch in. Thanks!

**Pull request closed without merging**
