### PR TITLE
sample: usb: remove less useful samples

### PR DESCRIPTION
**Pull request by jfischer-no**
Remove hid, wpanusb, cdc_acm_composite samples.

### CODE REVIEW

**Comment by tmon-nordic** [comment]
What is the reason behind wpanusb removal? @finikorg can you port wpanusb to device_next?

**Review by finikorg — APPROVED** [review]
Ok to remove, the kernel driver is not going to be upstreaming soon.

**Review by jukkar — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]

**Comment by carlescufi** [comment]
@kartben PTAL

**Review by henrikbrixandersen — APPROVED** [review]

**Review by kartben — APPROVED** [review]
@jfischer-no  it can be in a follow-up PR but it would be good to add redirects in `doc/_scripts/redirects.py` so that people browsing e.g https://docs.zephyrproject.org/3.7.0/samples/net/wpanusb/README.html don't land on a 404 when clicking "The latest development version of this page may be more current than this released 3.7.0 version."

**Pull request merged**
