### PR TITLE
Introduce new config scheme

### PR DESCRIPTION
**Pull request by SebastianBoe**
#### Problem
There are two problems with the way do configuration;

Firstly, this code is duplicated across all applications:
`selected_board = env_has_board ? env["BOARD"] : default_board_for_application`
`selected_conf_file = env_has_conf ? env["CONF_FILE"] : default_conf_for_application`

Secondly, environment variables are used to configure Zephyr[0].

#### Solution proposal
All environment variables are removed except for ZEPHYR_BASE (was not able to get rid of it).
All business logic regarding BOARD and CONF_FILE has been removed from the applications.
4 configuration file types are created to replace the above mechanisms.

The new system works like this:

CMake command line arguments are supported and have the highest precedence.
The intended use-case is temporary configuration that will not be shared to other developers
through version control.

`cmake -DBOARD=qemu_x86 [...]`

To reduce CMake command line verbosity the user may choose to create
a file like zephyr/samples/path/to/app/local-defaults.cmake.
`echo "set(BOARD qemu_x86)" >> $APPLICATION_SOURCE_DIR/local-defaults.cmake)`

To emulate having an exported BOARD environment variable and also to deprecate the environment variables PREBUILT_HOST_TOOLS, ZEPHYR_SDK_INSTALL_DIR, and ZEPHYR_GCC_VARIANT, the file $ZEPHYR_BASE/local-defaults.cmake has been created.

Example:
```
# Gitignored file

set(PREBUILT_HOST_TOOLS     /home/sebo/workspace_zephyr/.build)
set(ZEPHYR_SDK_INSTALL_DIR  /home/sebo/zephyr-sdk)
set(ZEPHYR_GCC_VARIANT      zephyr)
# set(BOARD      arduino_101)
```

To replace business logic in applications like ...
`
if(DEFINED ENV{BOARD})
  set(BOARD $ENV{BOARD})
else()
  set(BOARD bbc_microbit)
endif()
`
... applications may have a file $APPLICATION_SOURC_DIR/defaults.cmake
that might look like this:
`set(BOARD bbc_microbit)`

Finally, the version controlled file $ZEPHYR_BASE/defaults.cmake exists to allow fallback
configuration. Currently it is just defining set(BOARD qemu_x86). This allows us to omit
many config files, and may in the future allow Zephyr forks to have different default 
configurations. (This follows the convention-over-configuration principle)

Precedence rules:
1. Optional CMake command line arguments (cmake -DBOARD=qemu_x86)
2. The optional gitignored file $APPLICATION_SOURCE_DIR/local-defaults.cmake
3. The optional gitignored file $ZEPHYR_BASE/local-defaults.cmake
4. The optional version controlled file $APPLICATION_SOURCE_DIR/defaults.cmake
5. The version controlled file $ZEPHYR_BASE/defaults.cmake

[0] I can elaborate on the downsides of environment variables if necessary.

### CODE REVIEW

**Comment by nashif** [comment]
> [0] I can elaborate on the downsides of environment variables if necessary.

please do

**Comment by nashif** [comment]
> There are two problems with the way do configuration;

> Firstly, this code is duplicated across all applications:
> selected_board = env_has_board ? env["BOARD"] : default_board_for_application
> selected_conf_file = env_has_conf ? env["CONF_FILE"] : default_conf_for_application

why not have this code go into some macro, for example:

set_board(qemu_x86)
set_config(prj.conf)

and override if those are set in the environment for example? I am not sure I like introducing another file with this data is the right solution.

**Comment by SebastianBoe** [comment]
> why not have this code go into some macro

Because CONF_FILE and BOARD need to be set before boilerplate is executed. A set_board() macro
would require another line of boilerplate, giving us two pieces of boilerplate, as opposed to the 1 block it has today. The user also needs to understand the difference of having his code before or after the boilerplate block.

Getting rid of the BOARD and CONF_FILE configuration means the user can always have the boilerplate at the top of the CMakeLists.txt file and not think about what happens if code is placed above the boilerplate.

**Comment by SebastianBoe** [comment]
> I am not sure I like introducing another file with this data is the right solution.

I am open for other solutions.

**Comment by nashif** [comment]
> Because CONF_FILE and BOARD need to be set before boilerplate is executed. A set_board() macro
would require another line of boilerplate, giving us two pieces of boilerplate, as opposed to the 1 block it has today. The user also needs to understand the difference of having his code before or after the boilerplate block.

I see, now I remember we had the same issue with make

**Comment by SebastianBoe** [comment]
> [0] I can elaborate on the downsides of environment variables if necessary.

Using environment variables means teaching users how to use environment variables. Using CMakeLists.txt code requires no extra training as CMake will already be technology they need to
learn. (Edit this file, vs. (if windows run this program, if OSX edit .initrc, if zsh edit bla bla, if bash edit yada yada).

Deprecating environment variables means that two different shells that execute the same command on the same files will produce the same result.

The Zephyr environment variables are mixed into system environment variables. Finding out how a user has configured Zephyr is easy if the configuration is grouped together in a single config file for all users. If we use environment variables we have to search several (platform-dependent) locations to find out how the user is setting up his environment. For instance, inspecting them is easier;

printenv | egrep "ZEPHYR|PREBUILT"
vs.
cat $ZEPHYR_BASE/local-defaults.cmake

When CMakeLists.txt code is executed the environment variable will be evaluated and the generated build system will only see the resulting value. It will not realize that a environment variable change will require a reconfiguration. If the configuration is encoded in CMakeLists.txt code however, changing the configuration will cause a change in CMakeLists.txt code and generated build systems will Re-configure when any CMakeLists.txt code changes.

**Comment by nashif** [comment]
I am aware of the pitfalls of env variables, I thought it made sense to have this  explained as part of this PR for the curious reader.

> printenv | egrep "ZEPHYR|PREBUILT"
vs.
cat $ZEPHYR_BASE/local-defaults.cmake

right now I have:
```
core:hidapi(master): cat ~/.zephyrrc
#export ZEPHYR_SDK_INSTALL_DIR=/home/nashif/Work/SDK/0.8.2
#export ZEPHYR_SDK_INSTALL_DIR=/home/nashif/Work/SDK/0.8.2
export ZEPHYR_SDK_INSTALL_DIR=/home/nashif/Work/SDK/0.9.1
export IAMCU_TOOLCHAIN_PATH=/opt/issm/tools/compiler/
export IAMCU_TOOLCHAIN_DIR=/opt/issm/tools/compiler/bin
export ZEPHYR_GCC_VARIANT=zephyr
export ISSM_INSTALLATION_PATH=/opt/issm
export IA_VERSION=gcc-ia/5.2.1
export ARC_VERSION=gcc-arc/4.8.5
export USE_CCACHE=1
export BUILDDIR=/var/www/html/zephyr/
export ZEPHYR_FLASH_OVER_DFU=y
export ESP_IDF_PATH=~/Work/esp32/esp-idf/
export ESPRESSIF_TOOLCHAIN_PATH=~/Work/SDK/xtensa-esp32-elf/
export ESP_DEVICE=/dev/ttyUSB1
```
So basically we had this before...

I am personally not really attached to have a default board defined in the makefile for all of those tests and samples, the yaml file should be able to provide this information as well and a developer will get used to run cmake with -DBOARD or set it in his own application. 

Need to think about it a bit more though...

**Comment by pfalcon** [comment]
Just a bit of a user feedback. I tried to take CMake stuff easy (based on face to face discussion at the last minisummit that everything will be ok). But seeing such patch titles and looking at stuff like `set(BOARD bbc_microbit)` starts to give me shivers, and I know it's only beginning. Are we still on the track to have CMake being run once, generating real makefiles, and user forgetting about its existence (for example, releases would have real makefiles committed into git)? And then users just run make BOARD=foo like before. No? Sad. Maybe there was no such goal with this recent work at all? Even sadder, because that's what I heard (or understood) how it's supposed to work.

**Comment by nashif** [comment]
> But seeing such patch titles and looking at stuff like set(BOARD bbc_microbit) starts to give me shivers, and I know it's only beginning.

why does this give you shivers? 

set(BOARD XYZ) 
BOARD ?= XYZ

Whats the difference? It is almost the same number of characters :)

> Are we still on the track to have CMake being run once, generating real makefiles, and user forgetting about its existence (for example, releases would have real makefiles committed into git)? And then users just run make BOARD=foo like before. No? Sad. 

I guess you are talking about the samples, right?
Having a wrapper Makefile that would call cmake (the 2 steps needed to build with cmake) is a no-brainer, i think we should provide an example how to do that and have it somewhere, however, I am still not decided if this is the right thing to do. We are all used to typing make and finger memory is hard to get rid off, but in the last weeks I got used to do things with cmake and you can always alias the steps in your own environment. Anyways, need more input from people once we have all boards and samples/tests converted to CMake.

**Comment by SebastianBoe** [comment]
> Need to think about it a bit more though...
I will be awaiting more feedback.

**Comment by SebastianBoe** [comment]
@nashif : We need to get a conclusion on this PR before we port more samples/tests/"sample documentation".

**Comment by SebastianBoe** [comment]
@nashif : I am open for reworking parts of it, but I still think the main idea here makes sense.

**Comment by nashif** [comment]
> @nashif : I am open for reworking parts of it, but I still think the main idea here makes sense.

How about we stop defining default boards in the top Makefile and depend on having the board either set directly in the makefile using cmake set or on the command line, does this solve the issue? The way we are doing things is actually buggy, I found many cases where setting board to something by default causes rebuild issues.

**Comment by SebastianBoe** [comment]
@nashif : I can accept this for now, will close this PR and open a new one that introduces this policy.

We can do further improvements if necessary after the merge or as a response to user feedback.

**Pull request closed without merging**
