### PR TITLE
arm64: deny FPU access when CONFIG_FPU=n

### PR DESCRIPTION
**Pull request by npitre**

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
Not familiar of the details in reset.c, but the change looks sensible.
However, I'd like to ask why the -mgeneral-regs-only is required? Don't we have a way to define the -mfpu instead, as we do for cortex-m?

```
  list(APPEND TOOLCHAIN_C_FLAGS   -mfpu=${FPU_FOR_${GCC_M_CPU}})
  list(APPEND TOOLCHAIN_LD_FLAGS  -mfpu=${FPU_FOR_${GCC_M_CPU}})
```
...so if we do not define anything, we do not compile/link with FPU instructions at all?

**Comment by npitre** [comment]
> However, I'd like to ask why the -mgeneral-regs-only is required? Don't we have a way to define the -mfpu instead, as we do for cortex-m?

The aarch64 toolchain doesn't have such option:

```
aarch64-zephyr-elf-gcc: error: unrecognized command-line option '-mfpu='; did you mean '-mcpu='?
```

**Comment by ioannisg** [comment]
> However, I'd like to ask why the -mgeneral-regs-only is required? Don't we have a way to define the -mfpu instead, as we do for cortex-m?
> The aarch64 toolchain doesn't have such option: ``` aarch64-zephyr-elf-gcc: error: unrecognized command-line option '-mfpu='; did you mean '-mcpu='? ```

Understood, thanks. Then i guess the -mgeneral-regs-only will do the job.
Adding @tejlmand , with whom I did a similar investigation some time ago.

**Review by ioannisg — APPROVED** [review]
@tejlmand pls take a quick look

**Review by carlocaione — APPROVED** [review]

**Comment by npitre** [comment]
@nashif Could you please merge? the CI failure is unrelated to this.

**Review by tejlmand — APPROVED** [review]

**Comment by tejlmand** [comment]
> @nashif Could you please merge? the CI failure is unrelated to this.

Is it ?
Not from what I can tell:
```
/workdir/zephyr/lib/os/cbprintf_packaged.c:350:23: error: '-mgeneral-regs-only' is incompatible with the use of floating-point types
  350 |     v.ld = va_arg(ap, long double);
      |                       ^
/workdir/zephyr/lib/os/cbprintf_packaged.c:354:9: error: '-mgeneral-regs-only' is incompatible with the use of floating-point types
  354 |     v.d = va_arg(ap, double);
        |                      ^
......
```
so it seams we have code that is not compatible with the `-mgeneral-regs-only` flag.

**Comment by npitre** [comment]
On Fri, 7 May 2021, Torsten Tejlmand Rasmussen wrote:

> so it seams we have code that is not compatible with the `-mgeneral-regs-only` flag.

Hmmm... I wasn't expecting CI to override the CONFIG_FPU default.
This can wait then.

**Review by tejlmand — CHANGES_REQUESTED** [review]
blocking to avoid accidental merge.

**Comment by npitre** [comment]
> blocking to avoid accidental merge.

I repushed on latest master where all tests pass for me.

**Comment by npitre** [comment]
On Fri, 7 May 2021, Torsten Tejlmand Rasmussen wrote:

> > >  blocking to avoid accidental merge.
> >
> > I repushed on latest master where all tests pass for me.
> 
> I'm able to reproduce.

Yeah... I found the problem. The AARCH64_CORTEX_R was missing the FPU=y 
default. I (re)pushed a fix.

**Comment by tejlmand** [comment]
> Yeah... I found the problem. The AARCH64_CORTEX_R was missing the FPU=y default. I (re)pushed a fix.

I tested on your latest push:
```

**Comment by npitre** [comment]
> without this PR, I can build the kernel.common with CONFIG_FPU=n without errors.

Note that FPU=n is actually not supported right now. The fact that you 
get build failures is the exact manifestation of that fact.

**Comment by tejlmand** [comment]
> Note that FPU=n is actually not supported right now.

So then why is this an imply and not a select ?
https://github.com/zephyrproject-rtos/zephyr/blob/0428cb8025f75a81f3c73a12afc0c26e2365a8be/arch/arm64/core/Kconfig#L22

and if it is changed to a `select`, then why would this be needed, if FPU is always true:
https://github.com/zephyrproject-rtos/zephyr/blob/0428cb8025f75a81f3c73a12afc0c26e2365a8be/arch/arm64/core/CMakeLists.txt#L39

**Comment by npitre** [comment]
On Fri, 7 May 2021, Torsten Tejlmand Rasmussen wrote:

> > Note that FPU=n is actually not supported right now.
> 
> So then why is this an imply and not a select ?

Because, while it is not "supported", you can still use FPU=n in your 
own build if you are lucky i.e. don't need any of the code containing 
floats.

Right now the compiler complains if floats are used with FPU=n but 
eventually float-containing code will simply be omitted. That work 
hasn't been submitted yet hence the "unsupported" stance.

**Comment by tejlmand** [comment]
> Because, while it is not "supported", you can still use FPU=n in your own build if you are lucky i.e. don't need any of the code containing floats. 

How so ?
The failing file is `  cbprintf_packaged.c`.
Which is being unconditionally included into Zephyr build here:
https://github.com/zephyrproject-rtos/zephyr/blob/730acbd6ed85a5ee30d66f305cfc159b24643468/lib/os/CMakeLists.txt#L7

So how can a user avoid the compile error when `CONFIG_FPU=n` if this file is always being included in the build ?

> Right now the compiler complains if floats are used with FPU=n but eventually float-containing code will simply be omitted. That work hasn't been submitted yet hence the "unsupported" stance.

When that is in place, a `select FPU` can then be removed, or should we wait until that work is in place before merging this PR ?

For now, it seems to me that this PR removes a possibility to use `CONFIG_FPU=n`.
This means the PR actually limits the current set of supported options for arm64, but without solving any real issue.
If this does solve a real issue, could you open a dedicated issue with good description of what is failing without this patch, and then relate this PR as a fix of that issue.

**Comment by npitre** [comment]
> The failing file is `  cbprintf_packaged.c`.
> So how can a user avoid the compile error when `CONFIG_FPU=n` if this file is always being included in the build ?

You can either omit it from the build if you don't use the logging 
facility, or comment out the small part of the code dealing with floats.

And You'll have to omit timeutil.c from the build too.

And then select CONFIG_CBPRINTF_NANO instead of 
CONFIG_CBPRINTF_COMPLETE.

At that point you'll have something that builds successfully in most 
cases but not all. The sensor subsystem is also a float user, and some 
of the shell code too. And some CI tests assume floats as well.

So in short, this is doable with small hacks as stated in the commit 
log, but not out of the box yet.

> > Right now the compiler complains if floats are used with FPU=n but eventually float-containing code will simply be omitted. That work hasn't been submitted yet hence the "unsupported" stance.
> 
> When that is in place, a `select FPU` can then be removed, or should we wait until that work is in place before merging this PR ?

I think it should be merged now because the option still brings value to 
those willing to do with the needed manual adjustments.

> For now, it seems to me that this PR removes a possibility to use `CONFIG_FPU=n`.

Not at all. It enforces the conditions for FPU=n to be used. As I said 
you still can use it with some manual adjustments to the code. If you 
use FPU=n without this PR then you're exposing yourself to the 
possibility of data corruptions without being aware of them.

> This means the PR actually limits the current set of supported options for arm64, but without solving any real issue.

I'll simply say that I disagree with that statement.

> If this does solve a real issue, could you open a dedicated issue with good description of what is failing without this patch, and then relate this PR as a fix of that issue.

I invite you to have a look at #32192 and #32195.

**Comment by tejlmand** [comment]
> >  The failing file is ` cbprintf_packaged.c`. So how can a user avoid the compile error when `CONFIG_FPU=n` if this file is always being included in the build ?
>
> You can either omit it from the build if you don't use the logging facility, or comment out the small part of the code dealing with floats. And You'll have to omit timeutil.c from the build too. And then select CONFIG_CBPRINTF_NANO instead of CONFIG_CBPRINTF_COMPLETE. At that point you'll have something that builds successfully in most cases but not all. The sensor subsystem is also a float user, and some of the shell code too. And some CI tests assume floats as well. So in short, this is doable with small hacks as stated in the commit log, but not out of the box yet.

As the user would anyway need to make modifications to Zephyr, then I assume such a user could also comment out  Kconfig `select FPU`, like this:
```
config CPU_AARCH64_CORTEX_R
	bool
	select CPU_CORTEX
	select HAS_FLASH_LOAD_OFFSET
	select CPU_HAS_FPU
#	select FPU
#	select FPU_SHARING
```

imo, if we know the build will fail when doing `CONFIG_FPU=n`, unless you implement the changes you describe, then I would say this should be a `select`. Feel free to make a comment in Kconfig with that `select` on why a select is used, and what is need in order to support `CONFIG_FPU=n`.

> So in short, this is doable with small hacks as stated in the commit log, but not out of the box yet.

and when that is in place, a `select` can be changed to an `imply`.

>  If you use FPU=n without this PR then you're exposing yourself to the possibility of data corruptions without being aware of them.

So there is a real bug.
That's not clear from the commit message, so could add that information to the commit message, or file a real issue.



> >  This means the PR actually limits the current set of supported options for arm64, but without solving any real issue.
>
> I'll simply say that I disagree with that statement.

Well, with the information you had provided up until then, that was the only conclusion I could make.
With your additional description in your last comment, then I agree this PR solves a real issue, and this should be highlighted in the commit message and/or a dedicated issue.


> I invite you to have a look at #32192 and #32195.

Those two issues doesn't describe the fact that today's solution of `CONFIG_FPU=n` on arm64 may result in corrupted data.

**Pull request closed without merging**
