### PR TITLE
Bluetooth: Fix regression in mesh tests

### PR DESCRIPTION
**Pull request by cvinayak**
Related to, and fixes to #6083 

- Fix missing implementation in ticker to remove soft latencies in periodic ticker due to scheduling latencies.
- Account for scan window duration in advertising delay and hence advertising duration.
- Minor refactoring and compilation fixes.

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
1st commit: s/disable/disabled

**Comment by carlescufi** [comment]
Can the last commit have a negative effect when running with an external controller?

**Comment by jhedberg** [comment]
> Can the last commit have a negative effect when running with an external controller?

Or on a pre-5.0 controller, for that matter, i.e. a controller with a minimum advertising interval of 100ms. To me it looks like the only penalty is the added 10ms to the duration, just like there is for the Zephyr controller. We use a 10ms scan window for all controllers, so that part shouldn't be affected.

**Comment by carlescufi** [comment]
>Or on a pre-5.0 controller, for that matter, i.e. a controller with a minimum advertising interval of 100ms. To me it looks like the only penalty is the added 10ms to the duration, just like there is for the Zephyr controller. We use a 10ms scan window for all controllers, so that part shouldn't be affected.

Right, it's what I seemed to read as well but wanted to check, thanks!

**Review by MariuszSkamra — APPROVED** [review]
I confirm, the fix works well, all the tests that were failing, are passing now.

 1/13   MESH   MESH/NODE/IVU/BI-01-C   PASS
 2/13   MESH   MESH/NODE/IVU/BI-02-C   PASS
 3/13   MESH   MESH/NODE/IVU/BI-04-C   PASS
 4/13   MESH   MESH/NODE/IVU/BI-05-C   PASS
 5/13   MESH   MESH/NODE/IVU/BI-06-C   PASS
 6/13   MESH   MESH/NODE/IVU/BI-05-C   PASS
 7/13   MESH   MESH/NODE/IVU/BV-01-C   PASS
 8/13   MESH   MESH/NODE/IVU/BV-03-C   PASS
 9/13   MESH   MESH/NODE/IVU/BV-04-C   PASS
10/13   MESH   MESH/NODE/IVU/BV-05-C   PASS
11/13   MESH   MESH/NODE/KR/BI-05-C    PASS
12/13   MESH   MESH/NODE/KR/BV-02-C    PASS
13/13   MESH   MESH/NODE/KR/BV-03-C    PASS

**Comment by MariuszSkamra** [comment]
Tested on combined build nrf52840 board and QEMU with USB dongle

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
