### PR TITLE
west: Update bash autocomplete file

### PR DESCRIPTION
**Pull request by carlescufi**
Update the existing bash autocomplete with the latest commands and
command-line switches.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
Will post a zsh autocomplete file next.

**Review by henrikbrixandersen — APPROVED** [review]
LGTM

**Review by dkalowsk — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]
One missing feature I noticed today is that `west init -m path/to/local/repository` doesn't complete `path/to/local/repository`. Would it be possible to add that at some point?

**Comment by mbolivar-nordic** [comment]
@carlescufi twister is failing :(

**Comment by stephanosio** [comment]
Rebased to fix CI failure

**Review by stephanosio — APPROVED** [review]

**Comment by carlescufi** [comment]
> One missing feature I noticed today is that `west init -m path/to/local/repository` doesn't complete `path/to/local/repository`. Would it be possible to add that at some point?

I assume you mean `west init -l` ? This works fine for me locally.

**Pull request merged**
