### PR TITLE
west.yml: Update hal_silabs module to SiLabs SDK v2.7.3

### PR DESCRIPTION
**Pull request by mnkp**
This commit updates west.yml to point hal_silabs module to SiLabs SDK v2.7.3.

Depends on zephyrproject-rtos/hal_silabs/pull/5.

### CODE REVIEW

**Comment by mnkp** [comment]
Shippable failed due to EFM32HG series SoCs including the following in the device header file (e.g. Device/SiliconLabs/EFM32HG/Include/efm32hg308f64.h)
```
#define ARM_MATH_CM0PLUS
#include "arm_math.h"     /* To get __CLZ definitions etc. */
```
`arm_math.h` is part of CMSIS-DSP library which is not included in the list of Zephyr modules.

As the comment suggests `arm_math.h` was included to get `__CLZ`, however `__CLZ` is provided by the standard CMSIS library and not CMSIS-DSP. The fact that `arm_math.h` is included at all is likely an error. Especially that EFM32HG series is the only one doing so. I'll double check with my contact at Silabs unless someone form SiLabs team (@stevew817) will comment first. Most likely it will be enough to patch the header files.

**Comment by stephanosio** [comment]
> As the comment suggests `arm_math.h` was included to get `__CLZ`, however `__CLZ` is provided by the standard CMSIS library and not CMSIS-DSP. The fact that `arm_math.h` is included at all is likely an error.

https://github.com/zephyrproject-rtos/cmsis/blob/a2b82e79bd8ac156fb283d5f52fa0a2373962cf9/CMSIS/Core/Include/cmsis_gcc.h#L1078

`__CLZ` is indeed provided by CMSIS-Core, and there is no need to include a CMSIS-DSP header just to get that.

FYI, if it does require CMSIS-DSP for whatever reason though, this is currently WIP (#21600).

**Comment by chrta** [comment]
> As the comment suggests arm_math.h was included to get __CLZ, however __CLZ is provided by the standard CMSIS library and not CMSIS-DSP. The fact that arm_math.h is included at all is likely an error.

This was also an issue in the previously/currenlty used gecko sdk, see commit https://github.com/zephyrproject-rtos/hal_silabs/commit/fca4c5a0e8a1f8087e011fc9243f998ff5fc71fd 
Maybe this was necessary for an older CMSIS version?

**Review by chrta — APPROVED** [review]
As soon as the hal pr is merged and this west.yml is updated, i am fine with merging this.

**Review by galak — APPROVED** [review]

**Pull request merged**
