### PR TITLE
Bluetooth: Workaround privacy feature issue

### LINKED ISSUE #4989: Bluetooth: PTS fails to connect to Zephyr
HW
- Tester application running on QEMU
- Bluetooth USB dongle or Zephyr based (hci_uart) bt dongle
or 
- Tester combined build on nrf52 board

PTS fails to connect to the Zephyr. Note that only few test cases are failing due to this, the rest of tests is passing. PTS orders IUT to enable advertising, then tries to connect. Connection fails to be established. 

Steps to reproduce:
- Run one of the failing test cases
- PTS will try to connect to the IUT
- Connection will fail (Disconnection with Reason: Connection Failed to be Established)

Regression found in following test cases:
GATT/SR/GAW/BI-01-C
GATT/SR/GAS/BV-01-C

Git bisect testing pointed **a74feaaf557012d42ace232d0411d9275e21e066** as first bad commit. Tests are passing on build before this commit.

I enclose [debug logs](https://pastebin.com/fZfcbVBN), [btmon](https://pastebin.com/X2EPBrUz) and [Protocol Viewer logs](https://drive.google.com/file/d/1hiBc8D0BiKDJA2fUkszQQX16oKoLKDjT/view?usp=sharing) running on current master - new (7f6070fb6c3b5075040c3de7880edaad697de762) and old, before the change (on 7762578de4b7bc5784b08dc0a71a64615d82a471) [debug logs](https://pastebin.com/TE0AeMPv), [btmon](https://pastebin.com/AuDrZdTX), [PV logs](https://drive.google.com/file/d/1ZDLiDuaxHKvkqwVd_Vc6IgqoclmriQD3/view?usp=sharing)

### LINKED ISSUE #5486: Bluetooth: Cannot connect to prevoiusly disconnected device when BT_PRIVACY is enabled
After successful disconnection, one cannot reconnect to the device.
Advertising packets from remote device are not received (remote advertises - advertisements are visible on another device) so that General Connection Establishment Procedure fails.

Configuration:
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_BT_SIGNING=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_PRIVACY=y
CONFIG_BT_TINYCRYPT_ECC=y
[debug_privacy_enabled.log](https://github.com/zephyrproject-rtos/zephyr/files/1588886/iut-zephyr.log)
[traces_privacy_enabled.txt](https://github.com/zephyrproject-rtos/zephyr/files/1588883/traces_privacy_enabled.txt)

With CONFIG_BT_PRIVACY=n reconnection is successful.
[debug_privacy_disabled.log](https://github.com/zephyrproject-rtos/zephyr/files/1588856/iut-zephyr.log)
[traces_privacy_disabled.txt](https://github.com/zephyrproject-rtos/zephyr/files/1588866/traces_privacy_disabled.txt)

HW:
QEMU
Zephyr-based HCI BT controller running on nrf52840_pca10056 (hci-uart sample)
Head: 2e9064b7d646e97336f9aaa867487bd96514821b

Found during PTS testing.
Affected TC: GATT/CL/GAW/BV-02-C

I suspect controller issue

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This fixes intercompatibility issues with controllers supporting
privacy feature.
Core Spec requires to use network privacy mode as a default when
peer device provides its IRK during bonding when LL Privacy is used,
which is the case for Zephyr. We've seen devices including PTS
which exchanges it's IRK but is not aware about network privacy
mode. This results in Zephyr not able do be reconnect to such bonded
devices.
This workaround sets device privacy mode to be able to reconnect
to such devices.

Fixes #4989
Fixes #5486

Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
I'm fine with this, longer term we can decide if we really want to support network privacy mode.

**Review by jhedberg — APPROVED** [review]

**Review by jhedberg — CHANGES_REQUESTED** [review]
Question: how does this behave on a 4.0 controller (e.g. using qemu with laptop)? We should not send commands that we can a priori discover whether they're supported or not.

**Comment by carlescufi** [comment]
@jhedberg but in that case you should not be calling `addr_res_enable()` at all should you? Since that is a 4.2 feature

**Comment by carlescufi** [comment]
Wait, address resolution was introduced in 4.2 but network/device privacy modes in 5.0 right? so there actually needs to be a double-check of version or check the supported commands

**Comment by jhedberg** [comment]
@carlescufi `addr_res_enable()` will not be called if `bt_dev.le.rl_entries` is 0, and it will be 0 for any older controller.

**Comment by carlescufi** [comment]
@jhedberg then why are we worried about 4.0 controllers? the new command is only invoked in `addr_res_enable()`

**Comment by jhedberg** [comment]
@carlescufi actally not just that, but `bt_dev.le.rl_size` is checked also before enabling address resolution (which will also be 0 for older controllers). It's not clear however that the new code that this PR adds is behind similar conditions.

**Comment by carlescufi** [comment]
@jhedberg nope, I misread the patch, skipped the "folding" line. Your concerns are indeed justified I think

**Review by jhedberg — APPROVED** [review]
@carlescufi the new code is actually invoked from `bt_id_add()` however that one has exactly the checks I mentioned, so it seems the PR is free from this issue. Sorry for the noise.

**Comment by carlescufi** [comment]
@jhedberg That's fine, the GitHub display is really misleading sometimes

**Comment by jhedberg** [comment]
> @jhedberg That's fine, the GitHub display is really misleading sometimes

@carlescufi yep, I've started using `git pr <PR id>` more often because of this. It'd be good practice to use it always since only that way you get the full picture, e.g. it's impossible to check the correctness of the git author field in the web interface.

**Comment by carlescufi** [comment]
@jhedberg pro-tip, you can do `git pr clean` to delete all the local `pr/*` branches

**Pull request merged**
