### PR TITLE
net: Fix usage of strncpy in net_if_get_name and net_if_set_name

### PR DESCRIPTION
**Pull request by de-nordic**
Correct buffer size parameter.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Do we really need this change, I mean that we are checking the lengths just before the strncpy() so the current values should be fine?

**Comment by de-nordic** [comment]
> Do we really need this change, I mean that we are checking the lengths just before the strncpy() so the current values should be fine?

Static analysis will not know that and will be bothered.
But, if we do all checks before is the strncpy needed anyway? Range check is additional cmp in copy loop that seems unneeded.

**Comment by jukkar** [comment]
> Static analysis will not know that and will be bothered. But, if we do all checks before is the strncpy needed anyway? Range check is additional cmp in copy loop that seems unneeded.

Good point, `memcpy()` should be enough here. Could you change it to use memcpy instead?

**Review by jukkar — APPROVED** [review]

**Review by ssharks — APPROVED** [review]
Interesting change, what static code analysis are you running by the way?

**Review by rlubos — APPROVED** [review]

**Pull request merged**
