### PR TITLE
added status commands, runtime init, cmd callbacks, events handling

### PR DESCRIPTION
**Pull request by adakus**

### CODE REVIEW

**Review by stephanosio — COMMENTED** [review]
Please review the [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html).

**Comment by sidcha** [comment]
Yes, +1 on reading the contributions guidelines.

And, please spit this PR into (at least) 4 commits; one for each feature.

**Comment by sidcha** [comment]
@adakus, Also, please drop changes related to events handling and cmd callbacks. I've completed the backport (along with others) from LibOSDP and should have a PR with those changes by the week.

**Comment by sidcha** [comment]
@adakus, see #46449.

**Pull request closed without merging**
