### PR TITLE
cleanup: soc: it8xxx2: remove unnecessary code

### PR DESCRIPTION
**Pull request by Dino-Li**
Code removed:
- IT8XXX2 doesn't support soc level software interrupt hence remove them.
- To use common macro to access csr (control status register).
- To remove CONFIG_RISCV_HAS_PLIC related code. IT8XXX2 uses its own
  interrupt controller code.
- To remove ite_write and ite_read. We don't use them anymore.

Code changed:
- Return true from arch_irq_is_enabled() when external interrupt-enable
  bit, and SOC's IER are both true.

Signed-off-by: Dino Li <Dino.Li@ite.com.tw>

---
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/38864)

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]
LGTM.

**Review by brockus-zephyr — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/38864)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dcpleung, @GTLin08, @jackrosenthal, @katsuster, @keith-zephyr, @kgugala, @mgielda, @nashif, @pgielda, and @sjg20)

**Review by keith-zephyr — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/38864)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dcpleung, @GTLin08, @jackrosenthal, @katsuster, @kgugala, @mgielda, @nashif, @pgielda, and @sjg20)

**Review by fkokosinski — APPROVED** [review]
LGTM

**Pull request merged**
