### PR TITLE
tests: arch: arm: arm_irq_vector_table: exclude Renesas RA ICU

### LINKED ISSUE #74398: `tests/arch/arm/arm_irq_vector_table` fails to build when intc driver directly uses `_sw_isr_table`
**Describe the bug**

Tested on 4d0a8c1e8b8316ec5071a3fcc98cd292d3bc4e6d.

`tests/arch/arm/arm_irq_vector_table` fails to build for targets where the interrupt controller driver directly references `_sw_isr_table`. This test n-selects the `CONFIG_GEN_ISR_TABLES` option, causing a build error.

Affected platforms (discovered so far):
* `arduino_uno_r4_wifi`
* `mikroe_clicker_ra4m1`

The interrupt controller driver in question: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_renesas_ra_icu.c.

**To Reproduce**
1. `west build -p -b arduino_uno_r4_wifi tests/arch/arm/arm_irq_vector_table`
2. See error

**Expected behavior**
The test can be successfully built for said platforms.

**Impact**
Showstopper (discovered in #74390).

**Logs and console output**
```
/home/filip/zephyrproject/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a(intc_renesas_ra_icu.c.obj): in function `ra_icu_query_available_irq':
/home/filip/zephyrproject/zephyrproject/zephyr/drivers/interrupt_controller/intc_renesas_ra_icu.c:47: undefined reference to `_sw_isr_table'
/home/filip/zephyrproject/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a(intc_renesas_ra_icu.c.obj): in function `ra_icu_query_irq_config':
/home/filip/zephyrproject/zephyrproject/zephyr/drivers/interrupt_controller/intc_renesas_ra_icu.c:73: undefined reference to `_sw_isr_table'
/home/filip/zephyrproject/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a(intc_renesas_ra_icu.c.obj): in function `ra_icu_irq_connect_dynamic':
/home/filip/zephyrproject/zephyrproject/zephyr/drivers/interrupt_controller/intc_renesas_ra_icu.c:99: undefined reference to `z_isr_install'
/home/filip/zephyrproject/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a(intc_renesas_ra_icu.c.obj): in function `ra_icu_irq_disconnect_dynamic':
/home/filip/zephyrproject/zephyrproject/zephyr/drivers/interrupt_controller/intc_renesas_ra_icu.c:118: undefined reference to `z_isr_install'
Memory region         Used Size  Region Size  %age Used
           FLASH:       26913 B       240 KB     10.95%
             RAM:        5536 B        32 KB     16.89%
        IDT_LIST:          0 GB        32 KB      0.00%
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: 4d0a8c1e8b8316ec5071a3fcc98cd292d3bc4e6d.

### PR DESCRIPTION
**Pull request by soburi**
This fix will comprehensively exclude not only the Arduino Uno R4 Minima but also any board that uses the Renesas RA ICU.

Fixes #74398

### CODE REVIEW

**Review by ithinuel — CHANGES_REQUESTED** [review]
The commit message explains what we can see in the commit diff.

Could you explain why disabling the tests is a good choice in this case?

As far as I understand, the `GEN_ISR_TABLES` config is an optional feature that this interrupt controller driver requires.
Maybe adding a `depend on` in the platform's Kconfig could also help ensure this is handled at the right level. I.E. these platforms/SoCs require this feature, so this should probably be reflected in their config (Kconfig/defconfig)

**Comment by soburi** [comment]
> The commit message explains what we can see in the commit diff.
> 
> Could you explain why disabling the tests is a good choice in this case?
> 
> As far as I understand, the `GEN_ISR_TABLES` config is an optional feature that this interrupt controller driver requires. Maybe adding a `depend on` in the platform's Kconfig could also help ensure this is handled at the right level. I.E. these platforms/SoCs require this feature, so this should probably be reflected in their config (Kconfig/defconfig)

First, in this test, CONFIG_GEN_ISR_TABLES is disabled in https://github.com/zephyrproject-rtos/zephyr/blob/dcf42917c550714d2457947538b9e29d083e872e/tests/arch/arm/arm_irq_vector_table/prj.conf#L2.

So, if you specify a dependency with depends on, this setting will overwrite it and the problem will not be resolved.

If add `select GEN_ISR_TABLES`, the build itself will pass without any problems, but from the perspective of evaluating this test, that is, evaluating the behavior when an ISR table is defined by the user in the code without generating an ISR_TABLE, I do not think it is a correct test.

The Renesas RA has an NVIC interrupt controller, but this is combined with an RA-specific ICU module to perform a kind of dynamic interrupt setting. In other words, there is no one-to-one correspondence between the irq number and the content notified by the irq.
This is different behavior from what the test code expects, so I think it would be better to exclude it.

**Comment by ithinuel** [comment]
Indeed `select GEN_ISR_TABLES` satisfies the build and running the test may not be really relevant. However, the build system outputs a warning about the config being assigned an `n` but still getting the value `y` which is more sound even outside of the context of this test. 

E.G. a user trying to save some ram by disabling this option will see that it is required by the SOC family instead of hitting this same error are possible reporting it again here.

Instead, I think the tests could benefit from having a filter on the effective value of that config E.G.

```yaml
common:
  filter: (CONFIG_ARMV6_M_ARMV8_M_BASELINE or CONFIG_ARMV7_M_ARMV8_M_MAINLINE) and not CONFIG_GEN_ISR_TABLES
```

This way, the test will be skipped (so no foul on the CI) AND the user will get a better experience to understand what is happening.

**Comment by soburi** [comment]
> Indeed `select GEN_ISR_TABLES` satisfies the build and running the test may not be really relevant. However, the build system outputs a warning about the config being assigned an `n` but still getting the value `y` which is more sound even outside of the context of this test.
> 
> E.G. a user trying to save some ram by disabling this option will see that it is required by the SOC family instead of hitting this same error are possible reporting it again here.
> 
> Instead, I think the tests could benefit from having a filter on the effective value of that config E.G.
> 
> ```yaml
> common:
>   filter: (CONFIG_ARMV6_M_ARMV8_M_BASELINE or CONFIG_ARMV7_M_ARMV8_M_MAINLINE) and not CONFIG_GEN_ISR_TABLES
> ```
> 
> This way, the test will be skipped (so no foul on the CI) AND the user will get a better experience to understand what is happening.

It's a smart solution!
I applied this suggestion and repush it.

**Review by ithinuel — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]
Thanks for the fix :)

**Comment by aescolar** [comment]
> This way, the test will be skipped (so no foul on the CI) 

We can do this, but please note that to use the `filter` twister will still run the cmake step and then check the resulting kconfig output against the filter. While a platform filter is handled right away on the twister side.

**Pull request merged**
