### PR TITLE
meta issue for reproducible builds (was: tests/determinism.sh)

### PR DESCRIPTION
**Pull request by marc-hb**
These tests are in a "work4me" state. They all proved valuable because they all found issues and all passed a fair number of times in some configuration(s)/environment(s). However for either passing or finding issues they may require:
- magic test parameters
- fixes not merged or not submitted yet
- additional tools like disorderedfs
- additional test steps like comparing checksums across different environments

I'm sharing this very early draft for two purposes:

1. Provide more detailed reproduction information and transparency for related fixes. There's only so much test code that can be put in a commit message.

2. Gather feedback and ideas about what could be an acceptable, high-level test *design* so CI can hopefully catch the most basic regressions some day. Please don't spend time reviewing any implementation detail because I doubt the final test design (if any) will look similar to this prototype.

Here a list of fixes that some past, present or future version of (some of) these tests have helped with:

- #13608  
- #13446 
- #14119 
- #14119
- #14594 
- #14595 
- #14775 
- #14776
- #15094
- #14804
- #15043
- #15128
- #15313 
- #15376
- #15578 
- #11717 
- #16368 
- #16466 
- #16536 
- #16917 
- #16965

- #17494
[strip-nondeterminism MR4](https://salsa.debian.org/reproducible-builds/strip-nondeterminism/merge_requests/4) ar.pm: Don't corrupt tables of symbols and long filenames
- #17495 
- #19444

- #53286
- #66009
- #66014
- #70132

[diffoscope MR 29](https://salsa.debian.org/reproducible-builds/diffoscope/merge_requests/29) Catch failures to disassemble and rescue all other differences
[diffoscope issue 64](https://salsa.debian.org/reproducible-builds/diffoscope/issues/64) Remove elf.StaticLibFile: it's a serious design flaw

- https://github.com/thesofproject/sof/issues/7114
- https://github.com/thesofproject/sof/pull/7428
- https://github.com/thesofproject/sof/issues/9034
- https://github.com/thesofproject/sof/issues/9797
- https://github.com/zephyrproject-rtos/zephyr/pull/51954

### CODE REVIEW

**Comment by nashif** [comment]
``determinism`` might be a bit confusing name, how about reproducible_builds or something that is closer to what this is about.

**Review by carlescufi — COMMENTED** [review]
Just a general comment, without getting into the particulars of this change (which by the way looks pretty interesting as a concept to me). Can we write this in Python? This would be good for 2 reasons:

1. Most people contributing to Zephyr are more or less comfortable with Python at this point. Less so with bash.
2. It would work on Windows, which is a supported platform

**Comment by marc-hb** [comment]
Thanks @carlescufi , yes python shouldn't be a problem. Just a bit more verbose that's all :-)

But even before looking at the programming language I would like ideas and directions about where this could/should fit in the grand testing architecture scheme of things. Like: still sitting on top of sanitycheck like this? Or as additional --feature(s) embedded inside sanitycheck itself instead? Other? If not embedded in sanitycheck then how could CI run the most basic of these tests and catch the most basic regressions? Additional github check?

**Comment by nashif** [comment]
> But even before looking at the programming language I would like ideas and directions about where this could/should fit in the grand testing architecture scheme of things. Like: still sitting on top of sanitycheck like this? Or as additional --feature(s) embedded inside sanitycheck itself instead? Other? If not embedded in sanitycheck then how could CI run the most basic of these tests and catch the most basic regressions? Additional github check?

this will run on its own in a nightly job, not per PR and not with check_compliance.

**Comment by marc-hb** [comment]
Thanks @nashif , this answers my main question.

Here's how I see the next steps:
1. Share here my most recent updates and fixes to this shell script 
2. Rewrite it in `tests/build_reproduction.py` and submit a new PR
3. Archive this shell script PR.

**Comment by nashif** [comment]
are you planning for this to be merged?

**Comment by marc-hb** [comment]
No, I will push another one. This script has pretty much been entirely rewritten. I will just keep using the description for bookmarks

**Pull request closed without merging**
