### PR TITLE
Driver for the LSM9DS1 sensor (accelerometer, gyroscope, magnetometer)

### PR DESCRIPTION
**Pull request by biwecka**
This driver adds support for the LSM9DS1 sensor.
At the moment I have problems with the driver only being functional if CONFIG_LPS22HB, CONFIG_APDS9960 and CONFIG_LPS22HB are also enabled.

I'll be very thankful for any help!

### CODE REVIEW

**Review by eHammarstrom — CHANGES_REQUESTED** [review]
You are missing DTS bindings,

see `dts/bindings/sensor`.

How do you currently attach this sensor to an i2c bus in your dts file?

**Comment by carlescufi** [comment]
@biwecka thanks for the contribution! Please squash your commits into a meaningful set, as per https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow.

Use `git rebase -i <upstream>/master` to edit your commit history.

**Comment by biwecka** [comment]
> You are missing DTS bindings,
> 
> see `dts/bindings/sensor`.
> 
> How do you currently attach this sensor to an i2c bus in your dts file?

That's the I²C part of my devicetree. I'm using an Arduino Nano 33 BLE Sense and therefore had to port the board before developing the driver. You can find the complete file on my GitHub https://github.com/biwecka/zephyr/tree/board_arduino_nano_33_ble_sense_nrf52840/boards/arm/arduino_nano_33_ble_sense.

```
&i2c1 {
    compatible = "nordic,nrf-twi";
    status = "okay";
    clock-frequency = <I2C_BITRATE_FAST>;
    sda-pin = <14>;
    scl-pin = <15>;

    apds9960: apds9960@39 {
        compatible = "avago,apds9960";
        label = "APDS9960";
        reg = <0x39>;
        int-gpios = <&gpio0 19 (GPIO_PULL_UP | GPIO_ACTIVE_LOW)>;
    };

    lps22hb_press: lps22hb_press@5c {
        compatible = "st,lps22hb-press";
        label = "LPS22HB";
        reg = <0x5c>;
    };

    hts221: hts221@5f {
        compatible = "st,hts221";
        label = "HTS221";
        reg = <0x5f>;
    };

    lsm9ds1: lsm9ds1@6B {
        compatible = "st,lsm9ds1";
        label = "LSM9DS1";
        // Set subaddr. for accl/gyro and magn sensor.
        reg = <0x6B 0x1E>;
    };
};
```

**Comment by eHammarstrom** [comment]
@biwecka  You should review one of the YAML files in `dts/bindings/sensor` similar to your driver.
I did not find `st,lsm9ds1.yaml` in https://github.com/biwecka/zephyr/tree/board_arduino_nano_33_ble_sense_nrf52840/dts/bindings/sensor.
Correct me if the binding definition is found elsewhere.

**Comment by biwecka** [comment]
> @biwecka You should review one of the YAML files in `dts/bindings/sensor` similar to your driver.
> I did not find `st,lsm9ds1.yaml` in https://github.com/biwecka/zephyr/tree/board_arduino_nano_33_ble_sense_nrf52840/dts/bindings/sensor.
> Correct me if the binding definition is found elsewhere.

You're absolutely right. There is no binding for the LSM9DS1 because I didn't know about these bindings. Thank you very much for pointing this out. I'm new to Zephyr and this is my first attempt on building a new driver.
Did you have a chance to look at the I²C part of the devicetree? If so, is it correct?

**Comment by avisconti** [comment]
@biwecka 
I think that all new ST sensor drivers should use the stmemsc HAL i/f in the modules section. Moreover you miss dts and test part at least. And multi instance.

1. The stmemsc part is in zephyrproject/modules/hal/st/sensor/stmemsc.
2. you can refer to 1921a2d84e for a complete driver
3. Check a driver multi instance example as in #29361

**Comment by biwecka** [comment]
@eHammarstrom I added a `st,lsm9ds1.yaml` binding. Now everything works as expected and without enabling the other sensor's drivers. But I'm not sure if the binding really fixed the issue because before adding the binding I was not able to reproduce the error. In the meantime I hat do reinstall my operating system and thus the toolchain. Maybe the issue was fixed by that.

@avisconti Is using the stmemsc HAL a necessity? Because I'm glad the driver works like it is now and would not like to change its implementation.

**Comment by avisconti** [comment]
> @avisconti Is using the stmemsc HAL a necessity? Because I'm glad the driver works like it is now and I would not like to change its implementation.

@biwecka 
Let's say that my intention was to use the HAL for every new driver implemente, but since LSM9DS1 is an old component maybe we can accept as it is.
I have to check all other points though.

**Comment by avisconti** [comment]
@biwecka 
Can you squash the commits together?
Also, what about multi-instance? I guess that new drivers have to implement it. What do you think @MaureenHelm ?
Moreover I do no see the test part (tests/drivers/build_all).

**Comment by avisconti** [comment]
Is this PR still of interest?

**Comment by eHammarstrom** [comment]
@avisconti Would increase support for the nano 33 ble board, but it should ideally use the ST HAL.

**Comment by biwecka** [comment]
I opened this PR to contribute the driver, which I implemented as part of my thesis at university, to the Zephyr project.
In the meantime I shifted focus and don't work on embedded systems anymore.
Unfortunately I don't have the time to convert this driver to ST HAL in my freetime.

It would be great if someone is interested in this PR and in the Arduino Nano 33 BLE Sense in general
because apart from this driver I also worked on a board definition, the digital microphone and on using MCUboot.
If someone would like to take over this PR I would also provide all the other code.

Alternatively what I could do would be resolving the errors in the compliance checks to merge this PR. But then I'd leave the driver code as it is.

**Pull request closed without merging**
