### PR TITLE
drivers: i2c: mcux_lpi2c: Fix unexpected I2C start condition

### PR DESCRIPTION
**Pull request by loicpoulain**
Ensure that no I2C start condition is inserted between messages of
a same transfer, except if explicitely requested (restart flag).

This fix issue with I2C register write functions.

Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

### CODE REVIEW

**Comment by loicpoulain** [comment]
@MaureenHelm , any comments this patch?

**Comment by MaureenHelm** [comment]
This is an interesting fix. @jfischer-phytec-iot, could the same fix be applied to i2c_mcux.c to fix #8684?

**Comment by jfischer-phytec-iot** [comment]
@MaureenHelm Yes, I tested the it with ssd1306 and apd9960 on kw41z, so it should also be applied to i2c_mcux.c. (My workaround was to use transfer.subaddress.)

**Comment by MaureenHelm** [comment]
@loicpoulain Will you please update this PR to apply the same change to i2c_mcux.c?

**Comment by loicpoulain** [comment]
> @loicpoulain Will you please update this PR to apply the same change to i2c_mcux.c?

Done

**Comment by jfischer-phytec-iot** [comment]
recheck

**Review by jfischer-no — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
Thanks @loicpoulain !

**Pull request merged**
