### PR TITLE
OTG-FS enabling for STM32L475 disco iot board

### PR DESCRIPTION
**Pull request by loicpoulain**
This patch enable USB for the disco_l475_iot board.
- Enable correct USB pinmux
- Enable usbotgfs node in dts
- Add support for LSE clock
- Add support for MSI PLL-Mode
- Add support for MSI as source clock for USB

### CODE REVIEW

**Review by ydamigos — COMMENTED** [review]
I tried it on my board. It recognizes the USB ACM device but it fails to connect with `failed to set dtr/rts` in linux kernel error.

**Comment by loicpoulain** [comment]
Thanks for testing @ydamigos, I'm going to check this sample as well (only tested usb-net for now).

**Comment by loicpoulain** [comment]
Today I tried cdc_acm on my side as well and I get same error as @ydamigos (failed to set dtr/rts). Looking at the code, it seems the USB controller does not generate generates SETUP complete IRQ (USB_OTG_DOEPINT_STUP) anymore (after a certain sequence). This causes control transfer failure and leads to cdc_acm errors...  However host is still sending new SETUP tentatives, controller correctly generates SETUP PKT RECEIVED interrupt (STS_SETUP_UPDT) but never generates the SETUP complete one.
It's interesting to note that I also generated a cdc_acm sample from STM32CubeMX application and I obtained same errors. So upper stack does not seem to be the problem here.

**Comment by erwango** [comment]
@ydamigos , @loicpoulain , any news on that problem?
Did you manage to identify CubeMx issue?

**Comment by ydamigos** [comment]
@erwango Unfortunately, I didn't have much time to check it. I'll try to do it asap.

**Comment by loicpoulain** [comment]
@erwango, this seems to be L4 specific yes and since it reproduced with cube MX, it's probably an hardware or Hal issue. Can you check internally if it's a known or reported issue. We can speak next week and I can also share the cubeMX config if necessary.

**Comment by erwango** [comment]
@loicpoulain , thanks for the update.
Do you think it could be linked to the board itself (as we were uncertain USB could work w/o HW fix) or more likely L4 generic?

**Review by erwango — COMMENTED** [review]
@loicpoulain , any update on this one?

**Comment by nashif** [comment]
ping @loicpoulain

**Comment by loicpoulain** [comment]
> ping @loicpoulain

I've sent some debug info to Erwan for internal investigation.
This is not strictly a blocker since the problem does not occur with all USB classes (e.g. ok with USB ECM/EEM), but let's wait a bit more to see if root cause can be found on ST side.

**Comment by erwango** [comment]
@loicpoulain, I rebased your change and got it working.
Issue lies in missing configuration of SYS_CLOCK_HW_CYCLES_PER_SEC.
It is set depending of the use case in Kconfig.defconfig, so you need to tweak this part to set it to 48000000 in case USB is used.
Can you cross check and confirm?

**Comment by loicpoulain** [comment]
@erwango , I rebased and do not observe the issue anymore, not sure why.
@ydamigos can you please check/test again?

**Review by ydamigos — APPROVED** [review]
@loicpoulain USB ACM device works now.

**Review by erwango — APPROVED** [review]
Works perfectly

**Comment by erwango** [comment]
CI failed due to mps2_an385 issue

**Comment by erwango** [comment]
recheck

**Pull request merged**
