### PR TITLE
tests: bluetooth: Showing HCI error

### PR DESCRIPTION
**Pull request by ahmedmoheb-nordic**
An HCI error is generated with the following scenario
- Start a scan procedure and connect to the first peripheral
- From the 'connected' callback, set the security level for the current connection and start a new scan procedure
- When the second device is found, start a new connection to the second peripheral

You should be able to navigate to "**~/zephyrproject/zephyr/tests/bluetooth/bsim_bt/bsim_test_conn_stress**" and run the test script that through "**./tests_scripts/conn_stress.sh**" that should build and run the applications using BabbleSim

Edit: Add a screen shot
Screenshot from 2022-11-02 09-15-06

### CODE REVIEW

**Comment by ahmedmoheb-nordic** [comment]
@jori-nordic

**Comment by ahmedmoheb-nordic** [comment]
@alwa-nordic

**Comment by jori-nordic** [comment]
@ahmedmoheb-nordic is that a bug, did you already open an issue for this?

**Comment by ahmedmoheb-nordic** [comment]
> @ahmedmoheb-nordic is that a bug, did you already open an issue for this? If not, could you do it? I'm closing this as this looks like a patch to reproduce an issue, not to fix it.

I created the following issue https://github.com/zephyrproject-rtos/zephyr/issues/53046

**Pull request closed without merging**
