### PR TITLE
samples: led_strip: fix bbc_microbit.conf location

### PR DESCRIPTION
**Pull request by simonguinot**
Commit 55d9d1c6bab3
("samples: led: consolidate LED samples under same directory") moved the led_strip sample from samples/drivers to samples/drivers/led.

But commit f54a53b4b3a8
("drivers: ws2812_gpio: Make timing configurable and less hardware dependend") was merged at the same time and added the bbc_microbit.conf file to the old location.

This patch moves bbc_microbit.conf to its correct location.

### CODE REVIEW

**Review by kartben — APPROVED** [review]

**Review by bbilas — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Comment by kartben** [comment]
@simonguinot fix compliance check please

**Comment by simonguinot** [comment]
> @simonguinot fix compliance check please

Hello @kartben. If possible I'd like the line keep uncut the following line in the commit message:
`("drivers: ws2812_gpio: Make timing configurable and less hardware dependend")`

Indeed this allows someone looking for that commit title in the git history to also hit that commit. It is used in the Linux kernel and I think it is smart.

Let me know if it is possible, else I'll cut the line.

**Comment by kartben** [comment]
@simonguinot 
We could ask for one of the admins to override the compliance check, but oth one can always search for the beginning of the string, right?

**Comment by simonguinot** [comment]
> @simonguinot We could ask for one of the admins to override the compliance check, but oth one can always search for the beginning of the string, right?

@kartben You do that when you search in the git history ? :) I cut the line... But I think it is not good to blindly enforce policies.

**Pull request merged**
