### PR TITLE
Tfm nrf patches

### PR DESCRIPTION
**Pull request by SebastianBoe**
Cherry-pick various tf-m nrf patches that are too important to wait
for a new upmerge.

### CODE REVIEW

**Comment by microbuilder** [comment]
@SebastianBoe If we can get the upmerge in today, are any of these still relevant?

**Comment by SebastianBoe** [comment]
Yes. They have all been merged to TF-M after the 1.5 release.

(one is still in review, but is trivial and expected to be merged soon)

**Comment by SebastianBoe** [comment]
Sorry, this branch is branched off of the 1.5 update. So it is only the last two commits that are relevant.

**Review by microbuilder — APPROVED** [review]

**Comment by SebastianBoe** [comment]
Green CI, so this is ready for review @microbuilder .

Essentially, there are a lot of changes that were made after 1.5 that our customers want.

We considered a second upmerge, or cherry-picking, and decided it was safest to cherry-pick.

**Comment by microbuilder** [comment]
@SebastianBoe Cherry-picking does put a burden on Zephyr for future updates, but given the deadline, we can merge this in, but I'd prefer a clean upmerge to a specific TF-M commit to make the 1.6.0 update process easier.

**Review by microbuilder — APPROVED** [review]
Tested on `nrf5340dk_nrf5340_cpuapp_ns`

**Comment by SebastianBoe** [comment]
@joerchan has tested locally.

@joerchan please confirm.

**Comment by joerchan** [comment]
Tested both nrf53 and nrf91 with and without IPC. All good.

**Review by joerchan — APPROVED** [review]

**Comment by microbuilder** [comment]
@SebastianBoe Please update west.yaml to point to the proper commit ... I merged the changes to the TF-M repo in.

**Comment by SebastianBoe** [comment]
Done.

@carlescufi : Ready for merging

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
