### PR TITLE
soc: esp32: refactor esp32_net

### PR DESCRIPTION
**Pull request by LucasTambor**
SOC_ESP32_NET is now SOC_ESP32_APPCPU, fallowing espressif's
naming convention in the same manner as ESP32S3 app cpu.

SOC_ESP32_APPCU is now a subset of SOC_SERIES_ESP32.

Add support for ESP32S3 in the IPM sample.

This PR also changes the necessary files, samples and tests
to keep everything compliant and bisectable.

### CODE REVIEW

**Review by uLipe — DISMISSED** [review]
It is now far cleaner than the first ESP32 Net concept :)

**Comment by uLipe** [comment]
Just a question, have you tested the openamp samples that support the esp32 AMP mode? The esp32 net concept was built initially for that :)

**Comment by LucasTambor** [comment]
@uLipe So the openamp sample relies on the `--sysbuild` arg to build for the remote board. Right now it conflicts with how we build for MCUboot so it is not working haha. It needs some additional work yet, but not related to SOC support, only build stuff.

**Comment by cfriedt** [comment]
> @uLipe So the openamp sample relies on the `--sysbuild` arg to build for the remote board. Right now it conflicts with how we build for MCUboot so it is not working haha. It needs some additional work yet, but not related to SOC support, only build stuff. 

It's been a while, but a while ago, I tried using MCUBoot with esp32-c3.

It was tricky, and for sure I'm a n00b when it comes to MCUBoot.

Don't mean to derail code review, so apologies.

Is there a link to follow for #exactsteps to get MCUBoot working for e.g. the devkitm?

Curious, because the A-B firmware update strategy is quite common, and I know that there are a number of tools to orchestrate FW update roll-outs. I'd like to use one on that platform..

**Comment by sylvioalves** [comment]
> > @uLipe So the openamp sample relies on the `--sysbuild` arg to build for the remote board. Right now it conflicts with how we build for MCUboot so it is not working haha. It needs some additional work yet, but not related to SOC support, only build stuff.
> 
> @LucasTambor
> 
> It's been a while, but I tried using MCUBoot with esp32-c3.
> 
> It was tricky, and for sure I'm a n00b when it comes to MCUBoot.
> 
> Don't mean to derail code review, so apologies.
> 
> Is there a link to follow for #exactsteps to get MCUBoot working for e.g. the devkitm?
> 
> Curious, because the A-B firmware update strategy is quite common, and I know that there are a number of tools to orchestrate FW update roll-outs. I'd like to use one on that platform..

@cfriedt, sorry to step in. You can easily build application with MCUBoot enabled as done for any other SoC:  
```c
west build -p -b esp32c3_devkitm ../bootloader/mcuboot/boot/zephyr/
west build -p -b  esp32c3_devkitm samples/hello_world -DCONFIG_BOOTLOADER_MCUBOOT=y
```
:)

**Review by sylvioalves — APPROVED** [review]

**Review by marekmatej — APPROVED** [review]

**Comment by carlescufi** [comment]
@kartben can you take a look?

**Comment by nashif** [comment]
re-assign, this is more of an esp relatged change.

**Pull request merged**
