### PR TITLE
shell: fix coverity issue in uart backend

### LINKED ISSUE #14814: [Coverity CID :196642]Error handling issues in /subsys/shell/shell_uart.c
Static code scan issues seen in File: /subsys/shell/shell_uart.c
 Category: Error handling issues
 Function: uart_rx_handle
 Component: Other
 CID: 196642
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by jakub-uC**
Fixed coverity issue CID 196642

Fixes #14814

Signed-off-by: Jakub Rzeszutko <jakub.rzeszutko@nordicsemi.no>

### CODE REVIEW

**Review by Mierunski — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by aescolar — CHANGES_REQUESTED** [review]
@jarz-nordic The coverity error is about not checking the ring_buf_put_finish() return value, which may indicate an error.
With this change you are explicitly ignoring it.
So, shouldn't the commit message explain why it is ok to ignore the error?

Another nit: The commit title is not really descriptive. Something like "shell: UART: ignore errors in ring_buf_put_finish" would be more meaningful.

**Comment by jarz-nordic** [comment]
@aescolar : I've added an ASSERT to check if function returned an error.

**Review by aescolar — APPROVED** [review]

**Review by aescolar — COMMENTED** [review]
One thing left: The commit message is still not really appropriate.

**Comment by carlescufi** [comment]
@aescolar sorry, did not realize you had one more comment. We can live with the commit message not being very descriptive though.

**Pull request merged**
