### PR TITLE
drivers: gpio: Add open drain output support for STM32

### PR DESCRIPTION
**Pull request by rosterloh**
Support configuring output as open drain instead of push pull
for STM32 devices with the GPIO_DS_DISCONNECT_HIGH flag

Signed-off-by: Richard Osterloh <richard.osterloh@gmail.com>

### CODE REVIEW

**Comment by erwango** [comment]
@rosterloh, thanks for proposal. 
Please note imminent driver rework due to new GPIO API introduction, merged yesterday actually (#16648). So please have a look and check if it fits your need.

**Comment by rosterloh** [comment]
Is there a PR already for migrating the gpio_stm32 driver to the new API?

**Comment by erwango** [comment]
> Is there a PR already for migrating the gpio_stm32 driver to the new API?

Only an issue for now, https://github.com/zephyrproject-rtos/zephyr/issues/19270.
Things should move next week

**Comment by rosterloh** [comment]
I'm happy with the way this is implemented in #19607 so I'm closing this PR

**Pull request closed without merging**
