### PR TITLE
tests: adc_api: add counter handler to avoid exception

### PR DESCRIPTION
**Pull request by hakehuang**
add counter interrupt handler for a valid test cases

### CODE REVIEW

**Comment by hakehuang** [comment]
this is a workaround for #72080

**Review by decsny — CHANGES_REQUESTED** [review]
I am not sure what you are trying to fix but this is not the way to do it

**Comment by hakehuang** [comment]
> I am not sure what you are trying to fix but this is not the way to do it

@decsny this is a workaround for https://github.com/zephyrproject-rtos/zephyr/issues/72080, the pit counter driver missing a protestction, if we provide a null callback, this will crash the system.

**Comment by decsny** [comment]
> > I am not sure what you are trying to fix but this is not the way to do it
> 
> @decsny this is a workaround for #72080, the pit counter driver missing a protestction, if we provide a null callback, this will crash the system.

The top callback is allowed to be NULL in the API, the fact it crashes the system is a bug from the driver. In fact, the fact the test tests this case where the callback is NULL I think is the point of the test. So we should fix the bug rather than stop testing the case that is failing.

**Comment by hakehuang** [comment]
> The top callback is allowed to be NULL in the API. This is something being tested by the test. We should fix the bug that was caught by the test rather than remove the case from the test that did its job.

@decsny , this adc_dma case is not intented to test the pit callback issue, we need add a case in counter testing.

**Comment by hakehuang** [comment]
fix by https://github.com/zephyrproject-rtos/zephyr/pull/72485

**Pull request closed without merging**
