### PR TITLE
LwM2M packet ref/unref and pending process fixes

### PR DESCRIPTION
**Pull request by mike-scott**
This patchset does the following:

- Cleans up the packet ref/unref during send and retransmit (including replacement fix for https://github.com/zephyrproject-rtos/zephyr/pull/4391)
- Avoid calling back into the packet pending process during re-transmits which was randomly causing 2 packets to be generated.

### CODE REVIEW

**Comment by rbtchc** [comment]
Do we need to strip the headers at retransmit function?
I found that the first thing that net_pkt_send_pkt() does is to strip the IP + UDP/TCP header if it's there.

**Comment by mike-scott** [comment]
@nashif The Codecov report looks suspect.  There's no way this patchset impacts:
arch/posix/soc/inf_clock/soc.c
tests/kernel/obj_tracing/src/philosopher.c

**Comment by mike-scott** [comment]
@rbtchc I actually added this based on your patch to the coap-client 4 months ago:
https://github.com/zephyrproject-rtos/zephyr/commit/d2e98c86fa6c6c5f8b967d94eea3d2ec5ab02fc9

When I saw it, I thought this was a very good idea.  But, now I see that the coap-client sample is using net_context_sendto() and not using net_app_send_pkt() where you are correct, it immediately removes the IP / UDP headers if present.

Will remove that patch.  Nice catch.

**Comment by mike-scott** [comment]
Dropped header strip patch.  Diff: https://hastebin.com/casinepova.cs

**Review by rbtchc — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Comment by mbolivar** [comment]
> @nashif The Codecov report looks suspect. There's no way this patchset impacts:
> arch/posix/soc/inf_clock/soc.c
> tests/kernel/obj_tracing/src/philosopher.c

Yup, known issue: https://github.com/zephyrproject-rtos/zephyr/issues/5546

**Pull request merged**
