### PR TITLE
stm32: lptim: Allow to override configuration check

### LINKED ISSUE #50224: tests/kernel/tickless/tickless_concept: Failed on STM32
tests/kernel/tickless/tickless_concept fails on STM32 platforms.

Reason is that test set tick freq to 100 and enables PM which due to recent changes is detected as a misconfiguration.

### PR DESCRIPTION
**Pull request by erwango**
Fixes: #50224

### CODE REVIEW

**Review by andyross — CHANGES_REQUESTED** [review]
Can you make these warnings?  Tick rate is an application configurable, and it's intended to be set and tuned by app authors based on the specific precision/power requirements of their systems as they intend to deploy them.  It's not a hardware feature and it's not something the platform should be trying to enforce.

There's also a portability issue, where if you have software that thinks it's authorized to set rules like this, you end up in collisions when you want one tick rate but some driver your customer is integrating is written to assume a different one.

And Zephyr already does its best to try to match timeouts to tick units and has APIs that are in general tolerant of time unit rounding issues, so I guess  I'm not understanding what your complaint is and (strongly) suspect the root cause lies elsewhere.

If you want a "recommended/tested/supported" configuration expressed in documentation and as a warning at build time (but please write and link the docs so users understand what you're trying to enforce!), I think that sounds great.  I just don't think we should be trying to lock down the tick rate, it's an app API and the app should be able to tune it.

**Comment by erwango** [comment]
> Can you make these warnings?

If we're generating warning when configuration differs from the recommended settings, we'll get CI failures in tests which are using a different configuration (such as `tests/kernel/tickless_concept`).

> Tick rate is an application configurable, and it's intended to be set and tuned by app authors based on the specific precision/power requirements of their systems as they intend to deploy them. It's not a hardware feature and it's not something the platform should be trying to enforce.

That's what this new Kconfig option should provide. Enabling `STM32_LPTIM_TICK_FREQ_RATIO_OVERRIDE`, user can set whatever configuration suits the application.

> And Zephyr already does its best to try to match timeouts to tick units and has APIs that are in general tolerant of time unit rounding issues, so I guess I'm not understanding what your complaint is and (strongly) suspect the root cause lies elsewhere.

These settings (LSE>4096 / LSI>4000) are coming from long period of maturation of this driver. Defining platform specific `SYS_CLOCK_TICKS_PER_SEC` looks quite a common practice (see in `soc/`).
The reason we're now facing this issue is that LPTIM source clock is now defined from device tree and the LSE>4096 / LSI>4000 setting we used to do using Kconfig at soc level has now to be done at board level since we're not able to get the LPTIM dt defined source in Kconfig as we used to do here (kept temprarily for backward compatibility):
https://github.com/zephyrproject-rtos/zephyr/blob/e7b6e0286a7874185cfe98ccc2885a5583716a85/soc/arm/st_stm32/common/Kconfig.defconfig.series#L19-L22
It should now be done at board level and hence we need a way to inform the user that he's advised to do this configuration on his board. But completely preventing deviations was, I agree, an abuse, which I'm trying to fix here.

I see 3 options then:
- Stopping differentiating LSI/LSE and use 4096 for both, which will be precise for LSE and rough for LSI, but LSI is not expected to be a precise source clock anyway. This has to be tested first.
- Add a Kconfig dt function to extract the clock source from dt and perform the same configuration depending on clock source as we used to do sometime ago
- Generating an assert, as warning are excluded. But assert are only seen if enabled...
 
> If you want a "recommended/tested/supported" configuration expressed in documentation and as a warning at build time (but please write and link the docs so users understand what you're trying to enforce!), I think that sounds great. I just don't think we should be trying to lock down the tick rate, it's an app API and the app should be able to tune it.

Providing a pointer to a documentation would indeed be great, but today I'm not sure where we can document these platform specific behaviors. The only documentation section available today would be board's but copy/pasting in each board's ... well, no.

**Comment by erwango** [comment]
About 

> Stopping differentiating LSI/LSE and use 4096 for both, which will be precise for LSE and rough for LSI, but LSI is not expected to be a precise source clock anyway. This has to be tested first.

It seems this was originally done in order to avoid time drift (due to accumulations of small rounding errors) in long duration tests (several days)

**Comment by erwango** [comment]
@andyross Are you fine with the latest proposal ?

**Review by andyross — APPROVED** [review]
I guess this is fine.  I still strongly suspect that there's a root cause elsewhere, even if it's bad time conversion assumptions in the test.  But certainly this won't hurt anything.

**Review by FRASTM — APPROVED** [review]

**Pull request merged**
