### PR TITLE
Flash map maintnance: splitting flash_map.c into separate sources

### PR DESCRIPTION
**Pull request by de-nordic**
The PR consists of two commits:
- changing how `flash_get_layout` obtains access to flash_area object by using `flash_area_open` instead of `get_flash_area_from_id`;
- splits `flash_map.c` into `flash_map.c`, `flash_map_layout.c`, `flash_map_integrity.c` and `flash_map_priv.h`; first file will not contain common public interface, the two other c units contain functions that are conditionally compiled, depending on Kconfig options, and the `flash_map_priv.h` contains inline helper.

### CODE REVIEW

**Review by nvlsianpu — APPROVED** [review]
Looks fine.
If this helps with maintenance I have no objections.

**Comment by de-nordic** [comment]
Ping @carlescufi @nashif

**Comment by de-nordic** [comment]
@carlescufi @nashif @galak Can you look at this? This does not change anything in code or subsystem functionality, it only splits the code into separate units  and moves ifdefs, that controlled compilation within units, into the CMakeLists.txt.

**Comment by de-nordic** [comment]
@cfriedt Do you think this could go in with LTS? This is not feature, the code has been divided into sub-units, the change, from functional point of view, is not visible to the end-user.

**Comment by cfriedt** [comment]
I'm ok with this, given that there is not really any API change.

**Comment by nashif** [comment]
what blocker bug is this fixing exactly?

**Comment by de-nordic** [comment]
> 
> 
> what blocker bug is this fixing exactly?

None.
It does not fix anything, it does not break anything, does not introduce new code. The thing just splits source into separate units, in places where code have been ifdefed with Kconfig options, and moves the conditional compilation into CMakeLists.txt.

**Review by nandojve — APPROVED** [review]
LGTM

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
