### PR TITLE
dts: bindings: vendor-prefixes: Add moortec prefix

### PR DESCRIPTION
**Pull request by bearzly**
Moortec (now part of Synopsys) is a semiconductor company which provides process, voltage, and temperature (PVT) monitoring IP for SoCs.

### CODE REVIEW

**Comment by bearzly** [comment]
Hi, we don't have a binding/driver to contribute right now, but I hope we can have this accepted as an accepted vendor prefix. cc @mfischer

**Review by nordicjm — CHANGES_REQUESTED** [review]
We only add here when there something being added in tree (i.e. part of the same PR) which uses it

**Comment by bearzly** [comment]
Fair enough, but that doesn't seem to be consistent

For example https://github.com/zephyrproject-rtos/zephyr/commit/8b968146769c9daf98117ef96a89ec687af880fb added Fanke but there are no bindings using fanke

Also https://github.com/zephyrproject-rtos/zephyr/commit/25ac2fa064187835946e8ba39a739bf5e82f3ec0 added AAEON but there are no bindings using AAEON

In fact, only 25% of the vendor prefixes are actually in use by a binding in the zephyr tree

```
for v in (grep -v '#' dts/bindings/vendor-prefixes.txt | grep -v -e '^$' | awk '{print $1}')
                                            ag "compatible.*$v" dts/bindings/ > /dev/null
                                            echo "$v $status"
                                        end
```

-> 181 vendors in use in at least one bindings, 532 vendors not used in any binding

**Comment by nordicjm** [comment]
> For example https://github.com/zephyrproject-rtos/zephyr/commit/8b968146769c9daf98117ef96a89ec687af880fb added Fanke but there are no bindings using fanke

There is actually, https://github.com/zephyrproject-rtos/zephyr/tree/main/boards/fanke board name folders must be as per the prefixes in the vendor file

> Also https://github.com/zephyrproject-rtos/zephyr/commit/25ac2fa064187835946e8ba39a739bf5e82f3ec0 added AAEON but there are no bindings using AAEON

If not used then it shouldn't have been added

> -> 181 vendors in use in at least one bindings, 532 vendors not used in any binding

The file originated from the linux kernel, so any in there might not have a reference. The rule is for adding **new** vendors not existing ones

**Review by kartben — CHANGES_REQUESTED** [review]
https://docs.zephyrproject.org/latest/build/dts/bindings-upstream.html#rules-for-vendor-prefixes

> Do not submit additions to Zephyr’s dts/bindings/vendor-prefixes.txt file unless you also include users of the new prefix. This means at least a binding and a devicetree using the vendor prefix, and should ideally include a device driver handling that compatible.

**Comment by bearzly** [comment]
Ahhh thank you for the doc link! I didn't realize that I could have an out-of-tree vendor list, which will solve my problems until we have a driver to upstream.

I will withdraw this PR, thank you for the feedback.

**Pull request closed without merging**
