### PR TITLE
board: nucleo_f411re: Configure USB and use as networking default

### PR DESCRIPTION
**Pull request by JoeHut**
Configure USB on nucleo_f411re.
Enable USB in board dts file.
Configure Ethernet over USB as default networking interface.

Signed-off-by: Johannes Hutter <johannes.5494@gmail.com>

### CODE REVIEW

**Review by erwango — COMMENTED** [review]
Thanks for this proposal.
First question: how do you connect USB here, as there is no USB connector on the board?

I'm trying to evaluate this change against recent #6858,
promoting board configuration guidelines.
Good thing is that it provides default network interface
to the board.
Though, I wonder about the pin configuration.
Since there is no USB connector on the board, you are configuring pins of CN10 connector. Does it enable use of a specific expansion board (using ST morpho connector).

PS: I don't want to create a pin configuration police. So I think it is ok if one wants to configure some pins as long as we keep compatibility with main board connector (arduino in this case). I just want to be sure to understand the use case here

**Comment by JoeHut** [comment]
Ah, you're right. I actually use it with a custom connector. I thought it may be useful for developers that want to enable USB in combination with this board, since I had to figure it out on my own. But I understand that it probably is not too useful without an onboard connector.

**Review by dbkinder — APPROVED** [review]

**Comment by erwango** [comment]
> I actually use it with a custom connector

Ok, then i'm affraid this will be too much specific for upstream.
Proposing to reject

**Comment by erwango** [comment]
@JoeHut , ok to close?

**Comment by galak** [comment]
As this patch was for a customer board cfg, going to close

**Comment by JoeHut** [comment]
Sorry, I was on vacation. Makes sense it got closed.

**Pull request closed without merging**
