### PR TITLE
doc: release-notes-4.0: Add Silabs notes

### PR DESCRIPTION
**Pull request by asmellby**
Add noteworthy additions for Silabs socs, boards and drivers.

### CODE REVIEW

**Comment by jhedberg** [comment]
Thanks @asmellby! I think we might want to mention something in the "HALs" section as well? https://github.com/zephyrproject-rtos/zephyr/blob/c50777a8431157bd4ab3a2c2e2a37e8151ae07da/doc/releases/release-notes-4.0.rst?plain=1#L984-L990

**Review by jhedberg — DISMISSED** [review]

**Review by jerome-pouiller — DISMISSED** [review]

**Comment by asmellby** [comment]
Rebased to resolve conflicts with Renesas additions.

**Review by jhedberg — DISMISSED** [review]

**Review by mmahadevan108 — DISMISSED** [review]

**Comment by jhedberg** [comment]
@asmellby new conflicts have crept in

**Review by dkalowsk — DISMISSED** [review]

**Comment by mmahadevan108** [comment]
Please rebase and fix the merge conflict

**Review by jhedberg — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
