### PR TITLE
samples: Bluetooth: multiple central connections to peripherals

### PR DESCRIPTION
**Pull request by cvinayak**
This sample and babblesim test following issues:
1. Uncovers an out-of-bound memory access in controller related to ULL reference count accessed after ULL context was released, assertion in ull.c file #35013
2. New connection establishments fail with reason 0x3E when peripheral does not except connection indication, suspected to be related to PHY update or Connection Update being in progress
3. MTU exchange fails when performing on simultaneous connections, this could be due to deadlock in the peripheral as single device used, but stil worth investigating
4. SMP pairing failures when performing simultaneous pairing procedures on multiple connections, this could be due to deadlock in the peripheral as single device used, but stil worth investigating
5. Assertion in hci_core.c:312

Application demonstrating BLE Central role functionality by scanning for other
BLE devices and establishing connection to upto 62 peripherals with a strong
enough signal.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

Below is the CONFIG_BT_CTLR_DEBUG_PINS=y logic analyzer capture of closely scheduled 62 BLE connections of 200ms connection interval between two nRF52840 DK:
image

Sniffer trace (simulated nrf52_bsim target):
image

sniffer trace file:
[SixtyTwoConnections.zip](https://github.com/zephyrproject-rtos/zephyr/files/5708776/SixtyTwoConnections.zip)

### CODE REVIEW

**Comment by cvinayak** [comment]
Converted back to draft, as following issues observed, :
1. Deadlock/assert in HCI command status/response in hci_core.c: Guessing here, possible race condition attempting to stop advertising while LE connection parameter request is being responded to by host? (This PR has auto connection update disabled in the peripheral sample for this reason).
2. PHY update procedure on few connections end up with supervision timeout, it is observed that packets are being nack-ed.

Need analysis.

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
@cvinayak can we move this out of draft?

**Comment by joerchan** [comment]
@cvinayak I think this would be better as a test. We still have these two issues related to using the identities API:
https://github.com/zephyrproject-rtos/zephyr/issues/31588
https://github.com/zephyrproject-rtos/zephyr/issues/22049

I would prefer to not use the identities API in samples until these are resolved.
I also think using the API in this way is kind of hacky in order to establish multiple connections between the same devices, which shouldn't be done, so I don't think it works good as a sample.

**Comment by cvinayak** [comment]
> 
> 
> @cvinayak I think this would be better as a test. We still have these two issues related to using the identities API:
> #31588
> #22049
> 
> I would prefer to not use the identities API in samples until these are resolved.
> I also think using the API in this way is kind of hacky in order to establish multiple connections between the same devices, which shouldn't be done, so I don't think it works good as a sample.

I will move back to draft for my personal use to stress test the scheduling on target.

Should I send a separate PR for this: https://github.com/zephyrproject-rtos/zephyr/pull/30735/commits/7fa3b26d2375d750e6766d030edcf37c902811f7 ?

**Comment by joerchan** [comment]
> Should I send a separate PR for this: 7fa3b26 ?

Yes, that makes sense.

**Comment by cvinayak** [comment]
Re-open this issue as a bug has been discovered relating to out-of-bound memory access when initiator is immediately started after previous connection complete.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
