### PR TITLE
 net: mqtt: Add write message handler

### LINKED ISSUE #22679: MQTT publish causes unnecessary TCP segmentation
**Describe the bug**
For some reason MQTT publishing sends publish packet and its payload in separate packets [code](https://github.com/zephyrproject-rtos/zephyr/blob/5476e0b365ac05c5355e10558fb2d2b30f7be179/subsys/net/lib/mqtt/mqtt.c#L264)

So even if the payload is just 1 byte, then you'll have 2 TCP packets and (usually) 2 TCP ACKs flying in the air to get that one byte delivered. This is a bit of an issue if you are doing this on top of some low bandwidt IoT network.

Maybe there is a good reason to do this, but I can't figure out what that would be.(Just trying out zephyr for the first time)

**To Reproduce**
Run any MQTT publish code and see the tcpdump.

**Expected behavior**
One TCP segment to deliver MQTT publish+payload

**Impact**
Non-optimal network usage & battery consumption

### PR DESCRIPTION
**Pull request by rlubos**
Add new transport handler for MQTT, with sendmsg-like functionality.
This allows TCP transport to send PUBLISH packets w/o fragmentation at
the TCP layer. Implement this new functionality for all existing
transports.

Fixes #22679

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
FYI @JusbeR

**Review by jukkar — APPROVED** [review]

**Review by mrfuchs — APPROVED** [review]
Works in my setup with `mqtt_client.transport.type = MQTT_TRANSPORT_SECURE_WEBSOCKET`.

**Comment by jhedberg** [comment]
@jukkar this seems more of an enhancement than a bug fix. Were you planning on requesting TSC approval for it (considering that you added the 2.2 milestone)?

**Comment by jukkar** [comment]
> this seems more of an enhancement than a bug fix

True, I will set the milestone to 2.3 which is more appropriate in this case.

**Comment by WilliamGFish** [comment]
Can we double check this PR as my MQTT connections now reject upon first message send...

**Comment by rlubos** [comment]
@WilliamGFish Any more details on your setup perhaps? I've tested this change with qemu/local mosquitto server and nRF91 (offloaded sockets) with nRF Cloud, both worked fine.

**Comment by WilliamGFish** [comment]
> @WilliamGFish Any more details on your setup perhaps? I've tested this change with qemu/local mosquitto server and nRF91 (offloaded sockets) with nRF Cloud, both worked fine.

I am using the esp32 (esp8266 modem driver) with offloaded sockets. This was working two days ago and had sen t over 500,000 messages without a failure. 

This wold be using the NET_TCP option therefore using the **mqtt_client_tcp_write_msg()** function. Not sure quite was is happening as error code does not appear to make sense (EKEYEXPIRED )

**Comment by WilliamGFish** [comment]
Found there is a bug/s in the modem driver that has been dramatically exposed by these changes.

**Comment by mike-scott** [comment]
@WilliamGFish Cool!  Which driver?

**Comment by WilliamGFish** [comment]
I am using the Particle Argon with esp32 (esp8266 modem driver) with offloaded sockets. This was working two days ago and had sent over 500,000 messages without a failure.

The offending logic in {esp8266_offload.c} esp8266_sendto()
```
	if (sock->type == SOCK_STREAM) {
		if (!esp8266_socket_connected(sock)) {
			esp8266_unlock(dev);
			return -ENOTCONN;
// 		} else if (dst_addr) {
// 			esp8266_unlock(dev);
// LOG_DBG("ERROR: dst_addr %d", ret);				
// 			return -EISCONN;
```

The logic seems confusing but by removing this the driver is back working again.

I am looking at other drivers but haven't found the same unusual logic.

**Comment by jbrzozoski** [comment]
Doh.  This pull request breaks MQTT for sufficiently large payloads.  The call to sendmsg only checks pass/fail, not how many bytes were sent...  Our application is stuck on this, so I'll be working on a fix.  I expect to have one within a day or so.

**Comment by jbrzozoski** [comment]
And it looks like the implementation of `sendmsg` over in the NRF sockets version falls back for large paylods to looping with `send` on each iovec and _also_ doesn't notice partial transmits. :exploding_head: 
Somebody owes me a cookie when I'm done with this.

**Comment by jbrzozoski** [comment]
After a bit more reading, I realized sendmsg is supposed to be all or nothing, and never return partial success.  My issue was entirely in the NRF sendmsg implementation.  I just opened a pull request with a fix on the NRF repository [here](https://github.com/nrfconnect/sdk-nrf/pull/3178).

**Pull request merged**
