### PR TITLE
Broadcast source unit test inval stop

### PR DESCRIPTION
**Pull request by Thalley**

### CODE REVIEW

**Review by larsgk — DISMISSED** [review]

**Review by cvinayak — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@Thalley sorry, merge conflict with your other PR :-) can you rebase?

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Review by cvinayak — DISMISSED** [review]

**Review by larsgk — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Comment by carlescufi** [comment]
@cvinayak @larsgk please re-review

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by cvinayak — DISMISSED** [review]

**Review by larsgk — DISMISSED** [review]

**Comment by carlescufi** [comment]
@Thalley please rebase

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by cvinayak — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
