### PR TITLE
Driver/bq35100

### PR DESCRIPTION
**Pull request by Emir-Oguz**

### CODE REVIEW

**Comment by dleach02** [comment]
Something is messed up with this PR. 111 commits with 260 files changed. I suggest you close this and try again with a clean PR.

**Comment by MaureenHelm** [comment]
> Please rebase to the latest main branch and force push, this will reduce your PR to just your own commits. You can find more details here: docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

Please let us know if you need help with this. You will also need to squash your fixup commits

**Comment by cfriedt** [comment]
@Emir-Oguz - there are too many commits in this PR. I think you need to rebase as @MaureenHelm has said. 

You may need to check that your remotes and branches are set up properly. Can you check the following?
1. `git remote -vv` should look something like this
```
arithmetics-ITS	git@github.com:arithmetics-ITS/zephyr.git (fetch)
arithmetics-ITS	git@github.com:arithmetics-ITS/zephyr.git (push)
origin	https://github.com/zephyrproject-rtos/zephyr (fetch)
origin	https://github.com/zephyrproject-rtos/zephyr (push)
```
2. `git branch -vv` should look something like this
```
...
main                                                             c817a09b0a [origin/main] ..
...
```
3. At that point you should be able to do this:
```
git checkout main
git fetch origin && git pull
# below, we assume you have a local branch driver/bq35100 which tracks remote branch arithmetics-ITS/driver/bq35100
git checkout driver/bq35100
git rebase main
git push --force arithmetics-ITS
```

**Comment by MaureenHelm** [comment]
It looks like this branch is still under development and not ready for code review.

**Pull request closed without merging**
