### PR TITLE
test: workqueue : add testcase to improve coverage

### PR DESCRIPTION
**Pull request by yingmingx**
Set work item's flag in pending state, it cannot be append to a
workqueue. Improve branch coverage of function k_work_submit_to_queue().

Signed-off-by: Ying ming <mingx.ying@intel.com>

### CODE REVIEW

**Review by enjiamai — APPROVED** [review]

**Review by LeiW000 — APPROVED** [review]

**Review by pabigot — COMMENTED** [review]
I'm not a fan of this sort of whitebox mutation of state; it's why this test can't be used to validate the behavior of a replacement implementation.  But given the way the test application is today this isn't wrong.

**Comment by yingmingx** [comment]
> I'm not a fan of this sort of whitebox mutation of state; it's why this test can't be used to validate the behavior of a replacement implementation. But given the way the test application is today this isn't wrong.

Thank you for you comment. I got you point. Test cases should not be white boxed. So I have changed my code using more ordinary API.

**Comment by LeiW000** [comment]
@pabigot , are you OK with the code now? If yes, please help to approve it.

**Review by pabigot — APPROVED** [review]
It doesn't hurt, it's not wrong, it checks a box.  OK.

**Pull request merged**
