### PR TITLE
drivers: modem: modem_cmd_handler.c: Drop cmd from buf if args are missing

### PR DESCRIPTION
**Pull request by XavierChapron**
In 90c6dc5e7f45ba696de42ab2e02c0f31e07843e0, a change was introduced to
    allow a modem commands determine if they have enough data or not.
    In a situation where some data where missing, the command should return
    -EAGAIN and this should lead to another call of the command with more
    data.
    In this commit, the argument parser was also allowed to return -EAGAIN
    to request more data due to missing arguments.
    
    However, this can't work because in cmd_handler_process_rx_buf() before
    calling process_cmd():
    - we make sure that a CR/LF has been found.
    - we compute match_len which can't be greater than the distance to the
      next CR/LF.
    Therefore, even if the command argument parser ask for more data by
    returning -EAGAIN, next call will have the same value for match_len,
    meaning that the parsing of argument will result in the same missing
    argument situation.
    This leads to an infinite loop of parsing the same data over and over in
    an infinite loop.
    
    This commit change this behavior to always drop the data in such a
    situation. The command will not be answered and will therefore timeout,
    but at least, next commands will correctly parse their returned data.

### CODE REVIEW

**Comment by XavierChapron** [comment]
Looking at this again, I need to change some things.
The EAGAIN behavior is valid when used from the modem cmd, but not for the argument parser...

**Comment by XavierChapron** [comment]
Updated, and the change looks less controversial!

**Review by jukkar — DISMISSED** [review]
LGTM

**Review by rerickson1 — CHANGES_REQUESTED** [review]
Typo in commit description
> In a situation where some data where missing

"In a situation where some data is missing" may be better wording.

**Comment by XavierChapron** [comment]
@rerickson1 @jukkar I've update the PR to address @rerickson1 comment.

I have also:
- fix some other typos in the commit log and in the comment
- Add a LOG_ERR when `process_cmd()` return an error.

**Review by rerickson1 — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
