### PR TITLE
doc: languages: rust: Fix a few typos and markups

### PR DESCRIPTION
**Pull request by yashi**
This commit fixes a few typos, capitalization, and markups in the rust document.

### CODE REVIEW

**Comment by ycsin** [comment]
We do not have an entry for the Rust in the MAINTAINERS.yml yet?

**Comment by yashi** [comment]
@ycsin It does but it doesn't specify `doc/develop/languages/rust`.

```
❯ ~/go/bin/yq eval '.Rust' MAINTAINERS.yml
status: maintained
maintainers:
  - d3zd3z
files:
  - cmake/modules/rust.cmake
  - lib/rust/
  - samples/rust/
labels:
  - "area: Rust"
```

I've added a commit to add the doc.

**Review by kartben — APPROVED** [review]

**Review by ycsin — APPROVED** [review]

**Comment by kartben** [comment]
@d3zd3z you might want to merge this

**Comment by d3zd3z** [comment]
This is inapplicable, as work is now happening on the https://github.com/zephyrproject-rtos/zephyr-lang/rust/ repo, and not here.

**Pull request closed without merging**
