### PR TITLE
remove custom reset handling from nrf54h20/nrf9280 jlink scripts

### PR DESCRIPTION
**Pull request by jonathannilsen**
Update the JLink scripts for nrf54h20dk/nrf9280pdk to work with the latest secure domain firmware v9.0.0

### CODE REVIEW

**Review by bjarki-andreasen — COMMENTED** [review]
Do we have this new behavior documented somewhere? it seems like this change is quite substantial for there not to be a debugging guide somewhere, maybe even a migration guide entry

**Comment by karstenkoenig** [comment]
> Do we have this new behavior documented somewhere? it seems like this change is quite substantial for there not to be a debugging guide somewhere, maybe even a migration guide entry

No good point, I don't think it is tracked yet and will try to add something for it

**Review by karstenkoenig — APPROVED** [review]
I like the global resets more every day...

**Review by bjarki-andreasen — APPROVED** [review]

**Comment by karstenkoenig** [comment]
> > Do we have this new behavior documented somewhere? it seems like this change is quite substantial for there not to be a debugging guide somewhere, maybe even a migration guide entry
> 
> No good point, I don't think it is tracked yet and will try to add something for it

@bjarki-andreasen https://github.com/nrfconnect/sdk-nrf/pull/19608

**Review by masz-nordic — APPROVED** [review]

**Pull request merged**
