### PR TITLE
soc: arm: stm32: implement VOS switch for H7 series

### PR DESCRIPTION
**Pull request by benediktibk**
Implement correct VOS switch for H7 series.

Signed-off-by: Benedikt Schmidt <benedikt.schmidt@embedded-solutions.at>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
This requires a bit more details:
- why is this made a SoC option (and why not a board or application specific configuration) ?
- If this has to be SoC defined, why isn't it common to all STM32H7 SoCs ?
- Why ODEN method is preferred over DIRECT ?

**Comment by benediktibk** [comment]
> This requires a bit more details:
> 
>     * why is this made a SoC option (and why not a board or application specific configuration) ?
> 
>     * If this has to be SoC defined, why isn't it common to all STM32H7 SoCs ?
> 
>     * Why ODEN method is preferred over DIRECT ?

Of course:
This option is SoC specific as the correct method to switch into VOS0 depends only on the SoC itself, according to the reference manual. It is independent of the external circuitry, hence, not board or application specific.
Unfortunately, it differs within the STM32H7 series, as some of these require either the ODEN bit to be set, others allow a direct switch into VOS0. Therefore, there is no real preference for ODEN or DIRECT. It is only necessary to use the correct method per SoC, the other one is invalid anyway.

**Review by FRASTM — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
> This option is SoC specific as the correct method to switch into VOS0 depends only on the SoC itself, according to the reference manual. It is independent of the external circuitry, hence, not board or application specific.
Unfortunately, it differs within the STM32H7 series, as some of these require either the ODEN bit to be set, others allow a direct switch into VOS0. Therefore, there is no real preference for ODEN or DIRECT. It is only necessary to use the correct method per SoC, the other one is invalid anyway.

Ok, thanks for these details.
I feel we should start moving this PWR configuration piece to device tree. This should have already been the case for SMPS, which I tolerated as Kconfig, but now it is clear that we can't continue adding more Kconfig around this.
My idea is to add a `pwr` node with matching compatible that provides the properties we need, then query these properties from soc_power.
Once done, SMPS will have to be transition to dts too (but that is not a request for you).

**Comment by benediktibk** [comment]
Just to ensure I get it right: I should move as part of this PR the VOS configuration into the devicetree, but can leave SMPS as it is currently?

**Comment by benediktibk** [comment]
Would you mind if I add a separate issue for moving VOS and SMPS configuration together into the devicetree and work on this afterwards myself? I think this would speed up things a bit, at least on my side.

**Comment by erwango** [comment]
> Just to ensure I get it right: I should move as part of this PR the VOS configuration into the devicetree, but can leave SMPS as it is currently?

Indeed, I'm not asking you to transition SMPS.
(That will have to be done, but that would not be fair to ask you to do it).

**Review by ABOSTM — CHANGES_REQUESTED** [review]
Hi @benediktibk ,
I have 2 concerns about this PR:
* Looking at Datasheet: DS12930 Rev 1
image
So VOS0 is available only in case of LDO regulator not with SMPS

* Also in Reference Manual RM0399 Rev 3:
  §7.6.2:

>   VOS0 deactivation must be managed by software before the
> system enters low-power mode.

So I am afraid thing are more complex if we want to make use of VOS0, as we need to manage it when entering and exiting LowPower.

**Comment by benediktibk** [comment]
Hi @ABOSTM,
thanks for the review, I did not catch this caveat on the H747. My work originated from the H735 where there is no such restriction. But this is a solvable issue, as I could implement VOS1 as well, besides VOS0.

Regarding the low power switches, these are not yet implemented at all for the H7 series. This pull request should actually prepare everything for https://github.com/zephyrproject-rtos/zephyr/pull/41871, which then implements the low power states.

**Pull request closed without merging**
