### PR TITLE
arch: arm: aarch32: fix section alignment behind rodata start marker

### LINKED ISSUE #39978: logging.log2_api_deferred and logging.msg2 tests fail on qemu_cortex_a9
**Describe the bug**
The `logging.log2_api_deferred` tests fail at run-time on `qemu_cortex_a9`.

**To Reproduce**
```
twister -v -N -T tests/subsys/logging/log_api -p qemu_cortex_a9
```

**Expected behavior**
All tests pass.

**Impact**
"Deferred logging" API test is broken on `qemu_cortex_a9`.

**Logs and console output**
```
$ scripts/twister -v -N -T tests/subsys/logging/log_api -p qemu_cortex_a9
ZEPHYR_BASE unset, using "/home/stephanos/Dev/zephyrproject/zephyr"
Renaming output directory to /home/stephanos/Dev/zephyrproject/zephyr/twister-out.18
INFO    - Zephyr version: v2.7.99-878-gc03519fffc6a
INFO    - JOBS: 60
INFO    - Using 'gnuarmemb' toolchain.
INFO    - Building initial testcase list...
INFO    - 18 test scenarios (18 configurations) selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    -  1/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_immediate_rt_filter PASSED (qemu 2.604s)
INFO    -  2/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_deferred_no_overflow PASSED (qemu 2.650s)
INFO    -  3/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_immediate PASSED (qemu 2.658s)
INFO    -  4/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_immediate_static_filter PASSED (qemu 2.692s)
INFO    -  5/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_immediate_rt_filter PASSED (qemu 2.591s)
INFO    -  6/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_deferred_overflow PASSED (qemu 2.799s)
INFO    -  7/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_deferred_no_overflow PASSED (qemu 2.562s)
INFO    -  8/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_deferred_overflow_rt_filter PASSED (qemu 2.663s)
INFO    -  9/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_immediate_static_filter PASSED (qemu 2.572s)
INFO    - 10/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_deferred_overflow_rt_filter FAILED Failed (qemu 2.649s)
ERROR   - see: /home/stephanos/Dev/zephyrproject/zephyr/twister-out/qemu_cortex_a9/tests/subsys/logging/log_api/logging.log2_api_deferred_overflow_rt_filter/handler.log
INFO    - 11/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_deferred_static_filter FAILED Failed (qemu 2.682s)
ERROR   - see: /home/stephanos/Dev/zephyrproject/zephyr/twister-out/qemu_cortex_a9/tests/subsys/logging/log_api/logging.log2_api_deferred_static_filter/handler.log
INFO    - 12/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_deferred_func_prefix PASSED (qemu 2.828s)
INFO    - 13/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_immediate_64b_timestamp PASSED (qemu 2.434s)
INFO    - 14/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_deferred_static_filter PASSED (qemu 2.708s)
INFO    - 15/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_deferred_overflow PASSED (qemu 2.731s)
INFO    - 16/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_deferred_func_prefix FAILED Failed (qemu 2.805s)
ERROR   - see: /home/stephanos/Dev/zephyrproject/zephyr/twister-out/qemu_cortex_a9/tests/subsys/logging/log_api/logging.log2_api_deferred_func_prefix/handler.log
INFO    - 17/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log2_api_deferred_64b_timestamp PASSED (qemu 2.832s)
INFO    - 18/18 qemu_cortex_a9            tests/subsys/logging/log_api/logging.log_api_immediate PASSED (qemu 2.703s)

INFO    - 15 of 18 test configurations passed (83.33%), 3 failed, 0 skipped with 0 warnings in 13.26 seconds
INFO    - In total -12 test cases were executed, 30 skipped on 1 out of total 402 platforms (0.25%)
INFO    - 18 test configurations executed on platforms, 0 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing xunit report /home/stephanos/Dev/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/stephanos/Dev/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
```

[logging.log2_api_deferred_overflow_rt_filter log](https://gist.github.com/stephanosio/597bf6812ff4846e7c2154fefb6d497b)
[logging.log2_api_deferred_static_filter](https://gist.github.com/stephanosio/8ef2a148f654e078cbbc6b5bba4fd0bb)
[logging.log2_api_deferred_func_prefix](https://gist.github.com/stephanosio/1d6aa212168ebc7a194972e242be594a)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: GNU Arm Embedded 10-2020-q4-major
 - Commit SHA: c03519fffc6ac66b0e4feea3742701e05b7a38ec

**Additional context**
* ~~These tests do not fail on `qemu_cortex_a9` when compiling with the Zephyr SDK.~~ UPDATE: This now fails with the Zephyr SDK as well; it has to do with a bug in the linker script (refer to the comments in this issue).
* Across all the emulated platforms, GNU Arm Embedded-specific failures are observed only on `qemu_cortex_a9`.

### PR DESCRIPTION
**Pull request by ibirnbaum**
Fixes #39978.

This commit assigns the __rodata_region_start marker to the ROMABLE region
prior to the inclusion of linker/common-rom.ld, linker/thread-local-storage.ld and
linker/cplusplus-rom.ld. Prior to this fix, the __rodata_region_start marker was
properly aligned and indicated the expected memory location for the start of the
rodata section and similar sections, but it was disconnected from the ROMABLE
region into which the subsequent sections are being integrated, resulting in place-
ment of those sections right behind the previous section in the ROMABLE region
and therefore at addresses below the __rodata_region_start marker.

For the sake of consistent behaviour, the end marker of the text region
has been modified accordingly.

Signed-off-by: Immo Birnbaum <Immo.Birnbaum@weidmueller.com>

### CODE REVIEW

**Review by nordic-krch — APPROVED** [review]
start of the rodata section in map file looks ok.

**Comment by nordic-krch** [comment]
With this  #40842 and #40848 could be reverted. Not sure though if that should be part of this PR. If not it may be forgotten.

**Review by stephanosio — COMMENTED** [review]
> With this #40842 and #40848 could be reverted. Not sure though if that should be part of this PR. If not it may be forgotten.

#40842 and #40848 should indeed be reverted here so that we can verify that this PR fixes the existing issues.

**Comment by ibirnbaum** [comment]
Additionally reverted #40842 and #40848 and the test have passed.

**Comment by nordic-krch** [comment]
Great! Can you add "Fixes ..." to PR message so that issues get closed automatically.

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
