### PR TITLE
boards: m5stack: Add support for M5Stack NanoC6

### PR DESCRIPTION
**Pull request by kartben**
This adds support for M5Stack NanoC6, an ESP32-C6 based development board with a tiny form factor.

- [ ] add docs
- [ ] figure out why UART doesn't work (might be a limitation of ESP32C6 port?)

### CODE REVIEW

**Comment by raffarost** [comment]
hi @kartben 
can you describe your uart problem, so we could try to help?
have you tried compiling with -DCONFIG_SHELL=y ?

**Comment by kartben** [comment]
@raffarost I found my issue -- https://community.m5stack.com/topic/6621/why-is-the-serial-print-not-working-in-the-m5nanoc6-unit?_=1722353057614
How would I go about enabling USB serial, if at all possible?

**Comment by raffarost** [comment]
Hi @kartben,
I did some checking and I'm still unsure if we already support it.
On C6, adding the following to `esp32c6_common.dtsi` seems to properly enable `SERIAL_ESP32_USB`:
```
		usb_serial: uart@6000f000 {
			compatible = "espressif,esp32-usb-serial";
			reg = <0x6000F000 0x1000>;
			status = "disabled";
			interrupts = <USB_SERIAL_JTAG_INTR_SOURCE>;
			interrupt-parent = <&intc>;
			clocks = <&rtc ESP32_USB_MODULE>;
		};
```
The USB driver Kconfig `SERIAL_ESP32_USB` mentions it would work as a UART interface.
By adding the following to the board's DTS:
```
	chosen {
		zephyr,sram = &sram0;
		zephyr,console = &usb_serial;
		zephyr,shell-uart = &usb_serial;
(...)
&usb_serial {
	status = "okay";
};
```
Unfortunately was not enough to make it work, so I'm not sure if it's the wrong approach or some setting is missing.
Just sharing as you might have some idea yourself, or maybe @LucasTambor or @sylvioalves could have a better input.

**Comment by raffarost** [comment]
It turns out clock control implementation for USB peripheral was missing for C6, causing it to hang at startup.
If you want to give it a try, the following PR's should fix the issue (using the configuration posted above):
PR #76515
PR #308 (HAL)

**Comment by kartben** [comment]
@raffarost 

```
*** Booting Zephyr OS build v3.7.0-232-g15899e7c6696 ***
Hello World! m5stack_nanoc6/esp32c6
```

Thanks! :)

**Pull request closed without merging**
