### PR TITLE
subsys: usb: class: hid: Allow control of USB poll interval

### PR DESCRIPTION
**Pull request by pdunaj**
This closes issue #10807

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Review by finikorg — APPROVED** [review]
LGTM

**Comment by aurel32** [comment]
This looks like a good idea to make this configurable, and it looks like the correct way to do that. That said, I think the name and the description of the option are wrong. The `bInterval` field corresponds to a period in number of frames, and not to a frequency in Hz. In full speed mode, there is one frame per millisecond, so this corresponds to the number of milliseconds between two polls.

I guess the option should be changed to `USB_HID_POLL_INTERVAL_MS` and the help text to `Polling interval in ms selected by the USB HID Device.`

**Comment by pdunaj** [comment]
@aurel32 , thanks for spotting this - text was obviously wrong.

**Review by aurel32 — APPROVED** [review]
Thanks for the update, it looks all fine to me

**Comment by pdunaj** [comment]
hi @carlescufi , can you merge this?

**Pull request merged**
