### PR TITLE
cmake: modules: extensions: Check for missing blobs in `zephyr_blobs_verify`

### PR DESCRIPTION
**Pull request by pdgendt**
Add a separate warning/error message if a blob is missing.

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
iirc this was intentionally done this way because we don't want all modules to warn or fail just because a user have installed the module, remember all modules, even those a user may not care about, are pulled in when doing `west update`.

Therefore only blobs that the user has already fetched (and thereby indicated that he wants to use) are being checked.

@carlescufi feel free to comment.

**Comment by tejlmand** [comment]
principle was rejected in the past here: https://github.com/zephyrproject-rtos/zephyr/pull/67593#pullrequestreview-1823160548

**Comment by pdgendt** [comment]
> iirc this was intentionally done this way because we don't want all modules to warn or fail just because a user have installed the module, remember all modules, even those a user may not care about, are pulled in when doing `west update`.
> 
> Therefore only blobs that the user has already fetched (and thereby indicated that he wants to use) are being checked.
> 
> @carlescufi feel free to comment.

@tejlmand This hasn't changed, the function would've already warned/errored, but now there is a distinct message for a missing file, instead of a file without a valid hash.

It still only considers `FILES` that are passed as arguments, or all files for a module if `MODULE` is specified.

**Review by tejlmand — APPROVED** [review]
> @tejlmand This hasn't changed, the function would've already warned/errored, but now there is a distinct message for a missing file, instead of a file without a valid hash.

thanks for clarifying.

Approved 👍

**Review by lylezhu2012 — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
