### PR TITLE
Spi api fix

### PR DESCRIPTION
**Pull request by tbursztyka**
I don't know how this vendor attribute came in. I don't remember agreeing on this, moreover for something which breaks struct alignment and for a feature that is useless afaik: if CS (aka nss in stm32's vocabulary) is handled externally: the driver knows about it through the cs pointer in config, so it can handle it accordingly.

### CODE REVIEW

**Comment by superna9999** [comment]
The behaviour is not only related to CS GPIO, since it should do-able to avoid CS completely and only use the MISO/MOSI/CLK signals.
But the feature was used to enable CS-less slave SPI transfers since in the general use-case, the CS is taken from the pad, and if CS is not used all transfers will fail.
Finally having a vendor attribute in the configuration is mandatory for such corner use cases...

**Comment by tbursztyka** [comment]
No I am certain we can avoid a vendor specific attribute.

In most controllers actually, there is no control over the logic of CS at all, and wire it up or not: the transfer will work anyway. If you don't care of any data back actually you can even wire only MOSI/CLK.

If really this stm32 controller needs this NSS IGNORE, then let's enable the possibility to pass a cs pointer, with a NULL gpio_dev, make spi_context handling this case. Done. 

We should always avoid SoC/Arch/vendor specific in these generic API. I am using SPI quite a lot in my drivers, and I really don't want to have SoC/Arch/vendor stuff controlled over #ifdefs there just because we fail to find a generic way. Also, by experience, the tiny bit of  "flexibility" you offer to users about that, and they will just use it as crazy, nullifying the generic aspect of the API. Fixing that afterwards is painful. We still have this legacy SPI API lurking around for instance...

**Comment by superna9999** [comment]
Ok then for this specific use case

**Comment by erwango** [comment]
@tbursztyka : I guess you'll need to update drivers/bluetooth/hci/spi.c:133 as well to remove vendor field.
Last, we'll be able to update code under CONFIG_BT_SPI_BLUENRG to take advantage of spi_context_.. (not required to do it within current PR, though).

**Review by superna9999 — APPROVED** [review]
If spi_context handles NULL gpio_dev, :shipit:

**Comment by tbursztyka** [comment]
@erwango : good point, missed that one. PR updated

**Review by erwango — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
