### PR TITLE
size_report: sort nodes by size, descending

### PR DESCRIPTION
**Pull request by arbrauns**
This makes the tool much more useful for its primary purpose, finding things that are large.

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
I disagree. When looking for the size of a specific area, the current sorting makes much more sense.

**Comment by kartben** [comment]
> I disagree. When looking for the size of a specific area, the current sorting makes much more sense.

I can see a use case for both. Maybe this should be a `--sort=xxx` CLI option, @arbrauns?

**Comment by arbrauns** [comment]
> I can see a use case for both. Maybe this should be a `--sort=xxx` CLI option, @arbrauns?

Any idea how to shoehorn that into e.g. `west build -t ram_report`?

**Comment by nashif** [comment]
```
    ├── drivers                                                                                   132   0.32%
    │   ├── clock_control                                                                           4   0.01%
    │   │   ├── clock_control_mcux_mcg.c                                                            2   0.00%
    │   │   │   └── __devstate_dts_ord_64                                                           2   0.00%
    │   │   └── clock_control_mcux_sim.c                                                            2   0.00%
    │   │       └── __devstate_dts_ord_10                                                           2   0.00%
    │   ├── gpio                                                                                   70   0.17%
    │   │   └── gpio_mcux.c                                                                        70   0.17%
    │   │       ├── __devstate_dts_ord_20                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_22                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_27                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_29                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_70                                                           2   0.00%
    │   │       ├── gpio_mcux_port0_data                                                           12   0.03%
    │   │       ├── gpio_mcux_port1_data                                                           12   0.03%
    │   │       ├── gpio_mcux_port2_data                                                           12   0.03%
    │   │       ├── gpio_mcux_port3_data                                                           12   0.03%
    │   │       └── gpio_mcux_port4_data                                                           12   0.03%
    │   ├── pinctrl                                                                                10   0.02%
    │   │   └── pinctrl_kinetis.c                                                                  10   0.02%
    │   │       ├── __devstate_dts_ord_19                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_21                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_26                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_28                                                           2   0.00%
    │   │       └── __devstate_dts_ord_69                                                           2   0.00%
    │   ├── serial                                                                                 20   0.05%
    │   │   └── uart_mcux.c                                                                        20   0.05%
    │   │       ├── __devstate_dts_ord_80                                                           2   0.00%
    │   │       ├── __devstate_dts_ord_83                                                           2   0.00%
    │   │       ├── uart_mcux_0_data                                                                8   0.02%
    │   │       └── uart_mcux_1_data                                                                8   0.02%
    │   └── timer                                                                                  28   0.07%
    │       └── cortex_m_systick.c                                                                 28   0.07%
    │           ├── announced_cycles                                                                8   0.02%
    │           ├── cycle_count                                                                     8   0.02%
    │           ├── last_load                                                                       4   0.01%
    │           ├── lock                                                                            4   0.01%
    │           └── overflow_cyc                                                                    4   0.01%
```

vs new sorting

```
│   ├── drivers                                                                                   132   0.32%
│   │   ├── gpio                                                                                   70   0.17%
│   │   │   └── gpio_mcux.c                                                                        70   0.17%
│   │   │       ├── gpio_mcux_port4_data                                                           12   0.03%
│   │   │       ├── gpio_mcux_port3_data                                                           12   0.03%
│   │   │       ├── gpio_mcux_port2_data                                                           12   0.03%
│   │   │       ├── gpio_mcux_port1_data                                                           12   0.03%
│   │   │       ├── gpio_mcux_port0_data                                                           12   0.03%
│   │   │       ├── __devstate_dts_ord_29                                                           2   0.00%
│   │   │       ├── __devstate_dts_ord_70                                                           2   0.00%
│   │   │       ├── __devstate_dts_ord_22                                                           2   0.00%
│   │   │       ├── __devstate_dts_ord_27                                                           2   0.00%
│   │   │       └── __devstate_dts_ord_20                                                           2   0.00%
│   │   ├── timer                                                                                  28   0.07%
│   │   │   └── cortex_m_systick.c                                                                 28   0.07%
│   │   │       ├── cycle_count                                                                     8   0.02%
│   │   │       ├── announced_cycles                                                                8   0.02%
│   │   │       ├── last_load                                                                       4   0.01%
│   │   │       ├── overflow_cyc                                                                    4   0.01%
│   │   │       └── lock                                                                            4   0.01%
│   │   ├── serial                                                                                 20   0.05%
│   │   │   └── uart_mcux.c                                                                        20   0.05%
│   │   │       ├── uart_mcux_1_data                                                                8   0.02%
│   │   │       ├── uart_mcux_0_data                                                                8   0.02%
│   │   │       ├── __devstate_dts_ord_83                                                           2   0.00%
│   │   │       └── __devstate_dts_ord_80                                                           2   0.00%
│   │   ├── pinctrl                                                                                10   0.02%
│   │   │   └── pinctrl_kinetis.c                                                                  10   0.02%
│   │   │       ├── __devstate_dts_ord_28                                                           2   0.00%
│   │   │       ├── __devstate_dts_ord_69                                                           2   0.00%
│   │   │       ├── __devstate_dts_ord_21                                                           2   0.00%
│   │   │       ├── __devstate_dts_ord_26                                                           2   0.00%
│   │   │       └── __devstate_dts_ord_19                                                           2   0.00%
│   │   └── clock_control                                                                           4   0.01%
│   │       ├── clock_control_mcux_mcg.c                                                            2   0.00%
│   │       │   └── __devstate_dts_ord_64                                                           2   0.00%
│   │       └── clock_control_mcux_sim.c                                                            2   0.00%
│   │           └── __devstate_dts_ord_10                                                           2   0.00%

```

> I disagree. When looking for the size of a specific area, the current sorting makes much more sense.

@henrikbrixandersen does not sorting makes more sense? As long as we retain the structure and only sort within the existing structure, it looks actually much better and is easier on the eye.

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen does not sorting makes more sense? As long as we retain the structure and only sort within the existing structure, it looks actually much better and is easier on the eye

Try running it on a complex application instead of just a sample.

**Comment by arbrauns** [comment]
> Try running it on a complex application instead of just a sample.

I can't post the output here, but I do this frequently and sorting by size is the only thing that makes sense for me. If I wanted to know how large a certain component is, I'd simply search for it anyway rather than trying to find it in the alphabetical list.

**Comment by kartben** [comment]
> > I can see a use case for both. Maybe this should be a `--sort=xxx` CLI option, @arbrauns?
> 
> Any idea how to shoehorn that into e.g. `west build -t ram_report`?

maybe @nashif can help here, hopefully there is a way that doesn't involve appending something like "-- -DSORT=size" since it's a bit convoluted.

Re: sorting by name, I still think that another valid use case, as one may want to quickly eyeball the size of a specific "group" of symbols, based on their prefix/namespace, so they would want to find them all grouped together.

**Comment by henrikbrixandersen** [comment]
> I can't post the output here, but I do this frequently and sorting by size is the only thing that makes sense for me. If I wanted to know how large a certain component is, I'd simply search for it anyway rather than trying to find it in the alphabetical list.

Sorting by name allows one to compare sizes across changes in code/Kconfig/DTS by using textual comparison (e.g. `diff`). I use that a lot. If the sorting changes due to the code/Kconfig/DTS changes, this will be much more difficult.

**Comment by nashif** [comment]
> maybe @nashif can help here, hopefully there is a way that doesn't involve appending something like "-- -DSORT=size" since it's a bit convoluted.
> 
> Re: sorting by name, I still think that another valid use case, as one may want to quickly eyeball the size of a specific "group" of symbols, based on their prefix/namespace, so they would want to find them all grouped together.

maybe by allowing to supply options to the script via environment, for example:

```diff
index 5cd3246f972..87429e5a791 100644
--- a/cmake/reports/CMakeLists.txt
+++ b/cmake/reports/CMakeLists.txt
@@ -4,6 +4,7 @@ set(flag_for_ram_report ram)
 set(flag_for_rom_report rom)
 set(flag_for_footprint all -q)
 set(report_depth 99)
+set(size_report_opt $ENV{SIZE_REPORT_OPTS})

 if(DEFINED ZEPHYR_WORKSPACE)
   set(workspace_arg "--workspace=${ZEPHYR_WORKSPACE}")
@@ -21,6 +22,7 @@ foreach(report ram_report rom_report footprint)
     -o ${CMAKE_BINARY_DIR}
     ${workspace_arg}
     -d ${report_depth}
+    ${size_report_opt}
     ${flag_for_${report}}
     DEPENDS ${logical_target_for_zephyr_elf}
             $<TARGET_PROPERTY:zephyr_property_target,${report}_DEPENDENCIES>
@@ -40,6 +42,7 @@ if (CONFIG_BUILD_WITH_TFM)
       -o ${CMAKE_BINARY_DIR}
       ${workspace_arg}
       -d ${report_depth}
+      ${size_report_opt}
       ${flag_for_${report}}
       DEPENDS tfm
       USES_TERMINAL
@@ -59,6 +62,7 @@ if (CONFIG_TFM_BL2)
     -o ${CMAKE_BINARY_DIR}
     ${workspace_arg}
     -d ${report_depth}
+    ${size_report_opt}
     ${flag_for_${report}}
     DEPENDS tfm
     USES_TERMINAL
```


then you could do `export SIZE_REPORT_OPTS=--size-sorted` and run the command to get sorted output

**Comment by arbrauns** [comment]
If this is so controversial I guess I'll keep it downstream.

**Pull request closed without merging**
