### PR TITLE
posix: fnmatch: move from lib/util to lib/posix since it is a posix function

### LINKED ISSUE #55184: lib: util: move fnmatch to lib/posix since its a posix function
**Is your enhancement proposal related to a problem? Please describe.**
Just perusing over what is in `lib/util`, I happened to find `fnmatch()`. Had never heard of it before, so checked if there was a manual page. 

As it so happens, there is! And it's a POSIX function.
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fnmatch.html
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/fnmatch.h.html

**Describe the solution you'd like**
Should therefore be moved to the POSIX library.

**Describe alternatives you've considered**

**Additional context**
Will be part of v3.3 POSIX Roadmap

### PR DESCRIPTION
**Pull request by cfriedt**
**Note: Scancode / license failure is a false positive (the files were simply moved and reformatted and CI thinks they are new)**

* lib: posix: move `fnmatch()` from `lib/util` to `lib/posix`
* posix: fnmatch: add extern C decls when using C++
* tests: posix: add coverage for fnmatch
* posix: fnmatch: fix compliance issues

See also
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fnmatch.html
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/fnmatch.h.html

Fixes #55184

### CODE REVIEW

**Comment by carlescufi** [comment]
+1 from me on the idea and approach

**Comment by cfriedt** [comment]
* fix code formatting issues

**Comment by cfriedt** [comment]
* workaround for the following warning
```
/__w/zephyr/zephyr/tests/posix/common/src/fnmatch.c: In function 'posix_apis_fnmatch':
/__w/zephyr/zephyr/tests/posix/common/src/fnmatch.c:76:44: error: "/*" within comment [-Werror=comment]
   76 |         /* zassert_ok(fnmatch("*[[:alpha:]]/*[[:alnum:]]", "a/b", FNM_PATHNAME)); */
```

**Comment by cfriedt** [comment]
* update `"fnmatch.h"` in `lib/posix/fnmatch.c`

**Comment by cfriedt** [comment]
* convert DOS line endings to unix in `lib/posix/fnmatch.c`

**Comment by cfriedt** [comment]
* remove assignments from within conditionals

**Comment by cfriedt** [comment]
* rebase

**Comment by cfriedt** [comment]
The lack of good coding standards in `fnmatch.c` are strong.

**Comment by kartben** [comment]
Sorry for the very naive question but wouldn't it make sense to use the implementation from picolibc?

**Comment by cfriedt** [comment]
> Sorry for the very naive question but wouldn't it make sense to use the implementation from picolibc?

We will be adopting all of the POSIX headers from either PicoLibC or Newlib at some point. 

Currently there are no plans for mass adoption of POSIX sources or selectively choosing any from PicoLibC. Preferably, Zephyr POSIX sources would be Apache-2.0 licensed as well because each time a non-Apache licensed source file is used, it needs to get TSC approval.

**Comment by cfriedt** [comment]
> To say that `fnmatch.c` was severely lacking decent coding standards would be an understatement. It took several attempts to try and make it kosher.

Never did I think I would be leaving such a harsh critique of Guido Van Rossum's code 😅

**Comment by cfriedt** [comment]
@carlescufi - should be good to review now

**Review by carlescufi — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
