### PR TITLE
Selective IEEE 802.15.4 TX channel

### PR DESCRIPTION
**Pull request by edmont**
This PR adds the possibility to conveniently specify desired TX channel for every IEEE 802.15.4 transmission.

### CODE REVIEW

**Comment by edmont** [comment]
Converted to draft until updated Nordic HAL is added.

**Review by jciupis — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by canisLupus1313 — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
See #61227 :

> All future additions to the public IEEE 802.15.4 driver API SHALL either prove (by letting the API docs point to appropriate sections of current/future standard versions) that they are vendor and upper-layer agnostic or they SHALL be encapsulated in separate files selected via Kconfig/Devicetree if (and only if) the specific vendor/upper-layer stack is active. An appropriate [architectural pattern has been established and exemplified](https://github.com/zephyrproject-rtos/zephyr/pull/60343) ("vendor extensions", "protocol extensions").

Can you please at least provide a rationale why you need this and in which context. Plus it would be nice if you pointed out how this can be used in a vendor/protocol agnostic context - as you wish to work in the shared (rather than driver/protocol specific) namespace. It is  not immediately obvious to me why the standard conforming existing MAC PIB attribute implementation of "phyCurrentChannel" via `set_channel()` is insufficient and why we need a seemingly redundant additional solution. Without further explanation this just looks like one of those mere wrappers around a proprietary solution. MCPS-DATA.request (i.e. the standard primitive closest to `tx()`) does explicitly NOT have a channel attribute which may or may not be relevant here but should at least be explained.

Plus from a generic architectural viewpoint, this change does not even represent a simplification at the calling site much less within the driver. It introduces additional complexity throughout the stack without any obvious justification.

If this is just a vendor/protocol proprietary extension then please introduce a separate nRF5 or OT net_packet header file that encapsulates your addition and keep the generic stack free from proprietary code.

**Comment by jciupis** [comment]
@fgrandel the change is intended to be an optimization for use cases where the channel needs to be changed frequently. Consider a scenario where 802.15.4 API calls are costly, for example in power consumption and/or time, because of implementation details of the driver and the underlying hardware. To reduce the performance penalty in such scenarios, @edmont suggested to allow the channel to provided as a parameter to the transmission. This way only one API call (`tx`) instead of two (`set_channel` and `tx`) can be made to transmit a frame on a channel different than `phyCurrentChannel`.

One example where such optimization could be beneficial is CSL over multiple channels as described in IEEE 802.15.4-2020 Section 6.12.2.7 where `macCslChannelMask` is nonzero. Probably there are more scenarios where such optimization would be useful, both vendor/protocol agnostic and vendor/protocol specific.

I agree that functionally this change adds redundancy, and as a result it also adds complexity. Personally I'm fine with moving it to a proprietary extension as you suggested. I disagree though that it's out of place to propose such change to the shared namespace.

**Comment by fgrandel** [comment]
> the change is intended to be an optimization

In this case, this clearly is a **premature optimization** unless you first prove *by measurement* that:
1. There actually *is* a performance requirement justified by some standard that cannot be met w/o optimization.
2. The proposed optimization provably *solves* the performance problem.

As an example see https://github.com/zephyrproject-rtos/zephyr/pull/58439#issuecomment-1585746656.

And then there are much better ways (see architectural concerns below) to improve performance that should be explored first: If we could optimize the established `configure()` path this would immediately benefit everyone. Can you please trace it so we can analyze the actual bottlenecks?

My *architectural* concerns with this pattern are:
- **Standard Conformance**: We have an existing pattern that is better in line with standard primitives.
- **Scalability**: If we generally allow this pattern then the number of IEEE 802.15.4 RX/TX parameters that potentially could be added to `net_pkt` is enormous.
- **Data Normalization**: The packet is used across all interfaces and drivers. From a normalization perspective it clearly isn't the best place for driver/protocol-specific data. IMO none of the subsystem-, driver- and protocol-specific parameters should ever have made it into the packet unless they're actually required in application space or allocated conditionally.
- **Encapsulation**: Parameters that are internal to L2 should not be placed in a structure that is potentially visible outside L2.
- **Inconsistency**: From an API perspective there should be one single way to solve a problem.

> One example where such optimization could be beneficial is CSL over multiple channels as described in IEEE 802.15.4-2020 Section 6.12.2.7 where macCslChannelMask is nonzero.

A more obvious example for frequent channel changes is channel hopping as `macCslChannelMask` is just a variant of frequency diversity. I cannot see any obvious reason why `macCslChannelMask` requires an optimization that channel hopping does not require. The proposed pattern does *not* work for channel hopping, though (e.g. due to packet fragmentation or re-send requirements that cannot be configured at packet level), so at the very least a pattern should be proposed that works for channel hopping, too.

Overall, given all those concerns, the change simply isn't very convincing.

**Comment by jciupis** [comment]
> Overall, given all those concerns, the change simply isn't very convincing.

I understand, you've raised valid concerns regarding scalability, encapsulation etc. Let's then proceed with making this a proprietary extension as you suggested earlier.

**Comment by fgrandel** [comment]
> Let's then proceed with making this a proprietary extension as you suggested earlier.

Ok.

It would be great if - as a preparatory commit - you could also move the existing OT- and driver- specific parameters to the same file if that's not too much work for you. That way we'd even improve on the existing architecture.

If you check you'll find that almost all of them are either only used for OpenThread or for the nRF5 driver and should not be directly exposed to the subsystem. The only parameters that immediately make sense in application space, AFAICS, are LQI and RSSI.

**Comment by edmont** [comment]
Lets proceed as discussed and move this feature out of the common namespace.

**Pull request closed without merging**
