### PR TITLE
code_data_relocation: also match on object file name

### PR DESCRIPTION
**Pull request by tari**
Compilers are free to generate sections with the same name between files, which would be handled incorrectly by `gen_relocate_app`: all sections with the same name would be relocated, regardless of the file they came from. As a concrete example, I've observed strings being placed in `.rodata.str1.4` sections in many different files. Relocating rodata in one file containing that section causes all files' strings to be relocated as well.

This change makes `gen_relocate_app` refer to the object file name as well as section name, to avoid relocating sections with the same name in other files. While doing so, the script is refactored some to be more understandable:

 * Functions that logically add items to a dict now return a new dict, which is merged by the caller. This makes it easier to reason about where values come from.
 * Type hints are added throughout, with some new types defined to more clearly represent the use of values
 * Documentation is added for some functions
 * Moved some duplicated logic into dedicated functions

### CODE REVIEW

**Comment by carlescufi** [comment]
@tari sorry for the lack of reviews. Please rebase your PR and resolve the conflict.

**Comment by carlescufi** [comment]
@dcpleung @tejlmand please take a look

**Review by dcpleung — DISMISSED** [review]

**Comment by tari** [comment]
Rebased.

**Comment by teburd** [comment]
@dcpleung can you please re-review

**Review by dcpleung — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
