### PR TITLE
Fix typo: "CMSI" -> "CMSIS"

### PR DESCRIPTION
**Pull request by dreiss**
Signed-off-by: David Reiss <dreiss@meta.com>

### CODE REVIEW

**Review by dkalowsk — DISMISSED** [review]

**Comment by dreiss** [comment]
@nashif , can you land this?

**Review by martinjaeger — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
@dreiss sorry, but you need to fix your commit message. An empty body is not allowed and we require a subsystem/area. It has to look like this:

```
doc: Fix typo: "CMSI" -> "CMSIS"

A nonempty description of the change; yes, this is required even for trivial changes

Signed-off-by: Your Name <your.email@address>
```

**Comment by mbolivar-nordic** [comment]
> @dreiss sorry, but you need to fix your commit message.

(this is why the compliance check in CI is failing)

**Review by stephanosio — DISMISSED** [review]

**Comment by stephanosio** [comment]
Please fix the commit message as Marti mentioned above.

This can be merged after the feature freeze today since it is a documentation bug fix.

**Comment by dreiss** [comment]
Done.

**Review by stephanosio — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
