### PR TITLE
samples: net: Update overlay-bt.conf in various samples

### PR DESCRIPTION
**Pull request by rlubos**
`CONFIG_NET_L2_BT` no longer forces required BT configuration, but
depends on a user to set a valid configuration instead. Hence, we
need to select a proper configuration in the overlay config file.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Review by jukkar — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by pfalcon** [comment]
> CONFIG_NET_L2_BT no longer forces required BT configuration, but
depends on a user to set a valid configuration instead.

I wonder why that happened, looks rather verbose. IMHO, good enough defaults should have been used instead.

**Comment by mike-scott** [comment]
@rlubos Thank you for submitting this fix.  I hit this yesterday and had just begun debugging it.  This looks good from a bugfix point of view.

I was wondering 2 things (general question):
1. How does a Kconfig change go in which breaks 4 samples?
2. Seems like Zephyr has a problem enabling configurations in a consistent manner.  See https://github.com/zephyrproject-rtos/zephyr/pull/14057#discussion_r266643731 for more discussion, but it's reflected here where we now have 4 identical overlay-bt.conf files which need to be maintained.  Then we have sort of the wild west of per board Kconfig.defconfig conditional settings (where if xxx config is enabled we set some defaults).   Each board choosing how they want to setup various defaults and under what circumstances.  Also complicating matters, is we are moving away from using "select" in Kconfig to "depends", rather than looking at how "imply" would solve the same issues w/o forcing broken defaults.

For 1.15 we should look at how/why and where we are setting up default configurations and possibly setup some kind of boads/common-overlays/* if we feel that's the right solution.

Note, that I didn't even bring up the complication of SHIELD configurations .. we probably need to solve the base Zephyr issues first.

**Review by mike-scott — APPROVED** [review]

**Comment by pfalcon** [comment]
> For 1.15 we should look at how/why and where we are setting up default configurations and possibly setup some kind of boads/common-overlays/* if we feel that's the right solution.

Reading thru all this, I'd say we should have a good criteria what can go into board config/overlays and what shouldn't. E.g., the changes in this PR fine-tune BT config, and BT is in no way board-specific, so should not appear in board common configs. Of course, there's going to be (unfortunate) exceptions. (E.g. if one board doesn't/can't implement some generic features, and those need to be overridden just for it.)

**Comment by jukkar** [comment]
We should have a way to have "global" config overlays. For example in qemu_x86 it would be nice to use overlay-e1000.conf when compiling zephyr. This overlay is found only in couple of samples which is quite annoying actually. The same overlay-e1000.conf could be used in all the samples as it only contains generic options.

**Comment by pfalcon** [comment]
> We should have a way to have "global" config overlays.

One way to achieve that would be add specially defined options (in special Kconfig.* files) which would `select` needed other options. E.g. CONFIG_ADHOC_GIMME_E1000 (the whole point is that they should be named distinctly and clearly).

**Comment by jukkar** [comment]
> CONFIG_ADHOC_GIMME_E1000

I did not meant that. In order to select that symbol you would need to have this set in your overlay file anyway.
I was thinking something like what we do right now so
```
cmake .. -DBOARD=qemu_x86 -DOVERLAY_CONFIG=overlay-e1000.conf
```
but if the overlay-e1000.conf would not be found in local sample directory, a global directory would be searched and the overlay would be used if found there.

**Comment by pfalcon** [comment]
Yep, that would sound good, though probably would take more changes to do.

**Comment by jukkar** [comment]
Created enhancement #14740 for the overlay issue.

**Comment by mike-scott** [comment]
> the changes in this PR fine-tune BT config, and BT is in no way board-specific, so should not appear in board common configs. Of course, there's going to be (unfortunate) exceptions

@pfalcon my idea was identical to @jukkar .. I confused the issue by mentioning boards/common-overlay dir, but common overlay dir could be anywhere.

**Review by galak — APPROVED** [review]

**Pull request merged**
