### PR TITLE
Bluetooth: controller: split: Fix pipeline for continuous events

### PR DESCRIPTION
**Pull request by cvinayak**
Fix the pipeline prepare-resume implementation to correctly
handle multiple continuous events that request resume on
being pre-empted.

Symptoms of the bug being, when having continuous scanning,
and an active peripheral if a directed advertising is
started the peripheral event are not scheduled causing link
supervision timeout.

This is fixed by not having an enqueued resume event
prepared if there is an enqueued new non-resume event in the
pipeline.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
Tested on nRF52840 + nRF51

**Comment by aescolar** [comment]
@cvinayak : RAM size issue in mesh sample (again)

**Comment by cvinayak** [comment]
> @cvinayak : RAM size issue in mesh sample (again)

Reduced some RAM usage, but need to do some manual testing before I remove DNM.

**Review by mtpr-ot — APPROVED** [review]
No comments to Nordic-specific changes. Common changes look good.

**Pull request merged**
