### PR TITLE
Bluetooth: Mesh: Fix RPL storage timeout handling

### LINKED ISSUE #15904: concerns with use of CONFIG_BT_MESH_RPL_STORE_TIMEOUT in examples
[CONFIG_BT_MESH_RPL_STORE_TIMEOUT](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_BT_MESH_RPL_STORE_TIMEOUT.html) is used in multiple examples with values like 120 or 600, and its documentation suggests that this would reduce the frequency at which sequence numbers are persisted to flash.

In implementation, this option has an effect [only if it is strictly less](https://github.com/zephyrproject-rtos/zephyr/blob/735b287243115ce5595f43f812b5bd59f806472e/subsys/bluetooth/host/mesh/settings.c#L821) than [CONFIG_BT_MESH_STORE_TIMEOUT](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_BT_MESH_STORE_TIMEOUT.html), which defaults to 2 seconds.

None of this is wrong, but the override of this symbol in the examples is misleading as it has no impact on behavior.  In particular it doesn't mitigate against exceeding the flash write/erase endurance in mesh nodes with roles that require local processing of a large number of messages, which would be a motivator for increasing the RPL store timeout.

### PR DESCRIPTION
**Pull request by jhedberg**
The default values for the timeouts, as well as non-defaults in most
Mesh samples, use a higher value for the RPL than then generic mesh
storage timeout. This hasn't had any effect in practice since the code
only uses the RPL timeout if it is *smaller* than the generic one.

The original intention of the code was to use the RPL timeout,
regardless of what the generic one is, whenever the RPL is the only
thing that needs updating. Add some helper macros to track the various
groups of pending flags, and perform the appropriate checks to apply
the RPL timeout whenever it's smaller than the generic timeout, or if
there are no other items to store besides the RPL.

Fixes #15904

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
Disclaimer: only compile-tested so far. @pabigot would you be able to test that this does the right thing?

**Review by carlescufi — APPROVED** [review]
LGTM for the overall change

**Review by pabigot — CHANGES_REQUESTED** [review]
Nope, this doesn't work right.

I cherry-picked to my fork where I instrument flash erases and bytes written, and ran it on a mesh node that receives health reports at 1/60 Hz from six nodes and has `CONFIG_BT_MESH_RPL_STORE_TIMEOUT=120`.  I get this:

```
Mesh initialised OK
Waiting 120 seconds per 41
0:00:14.375: 0006 health: 00 fffe 0; 0 0
Waiting 120 seconds per 41
0:00:27.625: 0004 health: 00 fffe 0; 0 0
Waiting 120 seconds per 41
0:00:33.250: 0003 health: 00 fffe 0; 0 0
Waiting 120 seconds per 41
0:00:51.882: 0005 health: 00 fffe 0; 0 0
Waiting 120 seconds per 41
0:00:59.937: 0002 health: 00 fffe 0; 0 0
Waiting 0 seconds per 441
0:01:01.382: 0001 health: 00 fffe 0; 0 48
Waiting 120 seconds per 41
0:01:14.500: 0006 health: 00 fffe 0; 0 48
Waiting 120 seconds per 41
0:01:27.656: 0004 health: 00 fffe 0; 0 48
Waiting 120 seconds per 41
0:01:51.976: 0005 health: 00 fffe 0; 0 48
Waiting 120 seconds per 41
0:01:59.937: 0002 health: 00 fffe 0; 0 48
0:02:00.226: 0001 health: 00 fffe 0; 0 48
....
Waiting 120 seconds per 41
0:06:33.382: 0003 health: 00 fffe 0; 0 48
```

The "Waiting" is the `BT_DBG` in settings.c converted to a `printk` and adding display of `bt_mesh.flags`; the trailing `; 0 48` shows no page erases and 48 bytes written at 01:01.382 because `SEQ` became pending.  Over five minutes later, it still hasn't written anything more; the next `SEQ` isn't due for another two hours.

You'll need to cache the previous deadline and only reschedule the work when the new deadline is earlier than the previous one, rather than recalculate the deadline from the start every time.

This isn't new, it would probably only have been observable in a mesh that saw local-relevant messages at a rate faster than 1/2 Hz.  Here, it's become obvious.

**Comment by jhedberg** [comment]
@pabigot I pushed a second patch that should hopefully fix the issue you observed. As you say this is an independent issue which existed before this PR, but since it's in the same function I suppose it's convenient to cover it in the same PR - this way we also get both easily backported to 1.14.

**Review by pabigot — APPROVED** [review]
This one seems to flush at the expected rate.

**Pull request merged**
