### PR TITLE
random: Rename random header

### PR DESCRIPTION
**Pull request by ceolin**
rand32.h does not make much sense, since the random subsystem provides more APIs than just getting a random 32 bits value.

Rename it to random.h and get consistently with other subsystems.

### CODE REVIEW

**Review by cfriedt — DISMISSED** [review]
LGTM

**Review by nandojve — DISMISSED** [review]

**Review by de-nordic — DISMISSED** [review]
Flash simulator changes look okay

**Review by ghost — DISMISSED** [review]
Just to understand the rationale behind this... Why not `zephyr/random.h` ? Do we have any reason to assume that additional random/... headers will appear? If so - then shouldn't we give a more specific name to this one? If not -> zephyr/random.h might be more appropriate if we touch this anyway now?

But otherwise ok from an ieee802154 subsys perspective.

**Review by andyross — APPROVED** [review]
Was all about to do the pedant thing about how header names are APIs, but you actually handled the deprecation already. :)

**Comment by ceolin** [comment]
Btw, the new version I've pushed was just to address a documentation issue and rebased with latest head.

**Review by de-nordic — APPROVED** [review]
Flash simulator ok.

**Review by kartben — APPROVED** [review]

**Comment by jhedberg** [comment]
@ceolin is this something you are hoping would be included still for 3.5? If so, please set the milestone.

**Comment by ceolin** [comment]
> @ceolin is this something you are hoping would be included still for 3.5? If so, please set the milestone.

I rather have this in 3.5, but it is not critical. Will add the milestone but feel free to push it if needed.

**Review by nandojve — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
