### PR TITLE
net: ipv6: Drop packet with my source address and port

### PR DESCRIPTION
**Pull request by rmstoi**
If a UDP packet with source IPv6 address same as the address of echo
server is received, it causes echo server to recursively send the packet
to itself, resulting in a crash and memory depletion. This commit fixes
the crash by dropping the packet.

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>

### CODE REVIEW

**Review by pfalcon — CHANGES_REQUESTED** [review]
> it causes echo server to recursively send the packet to itself

Then the problem is apparently with "echo server", and that's where it should be fixed, not in the IP stack. How does loopback is supposed to work otherwise?

And it's unclear how this can be a problem for  "echo server" either, there's nothing wrong with receiving and replying to echo requests on the same interface - as long as port number is different, of course.

**Comment by jukkar** [comment]
> Then the problem is apparently with "echo server", and that's where it should be fixed, not in the IP stack. How does loopback is supposed to work otherwise?

The problem is that we currently accept packet that is coming from external network interface (so not loopback) where source address is our own address.

**Comment by pfalcon** [comment]
> The problem is that we currently accept packet that is coming from external network interface (so not loopback) where source address is our own address.

Then I'd suggest to double-check that the change is made on the code path which is used only for external interfaces, add code comment about this, and update commit message to mention that (and also to remove references to UDP and echo server, as TCP and other applications would be affected too). Also, similar change should be done for IPv4 too (if it's already present, worth mentioning that in the commit message either). Thanks.

**Comment by pfalcon** [comment]
(The original CI report was https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/14842/summary/console)

**Comment by pfalcon** [comment]
recheck

**Comment by pfalcon** [comment]
@rmstoi:

> the problem is not only with echo server, it is with whole IP stack. I just use echo server for testing.  You can reproduce this issue sending UDP packet with source address 2001:db8::1.

It would be nice to better understand where the problem happens (i.e. where infinite loop or recursive call happens), and it's actual nature (I for example don't have an idea how it could work with different source/destination port numbers). I don't have an easy way to forge a packet with an arbitrary address, if you can describe how to reproduce your test, I'd be interested to try it.

> Loopback seems to work

As you can see from the CI report, the number of tests are broken (some exactly use loopback capabilities to test networking functionality with CI).

> Basically it is a DOS attack, after which IP stack does not recover.

Sure, I'm all for fixing it, but let's try to understand the root issue better and describe it better for the folks who'll be looking at the stack later (so I hope my suggestions for comments/commit message make sense).

**Comment by rmstoi** [comment]
recheck

**Comment by rmstoi** [comment]
recheck

**Review by pfalcon — APPROVED** [review]
Looks good, thanks. (And just in case, I looked for another "validate" function where these checks could be merged, and didn't immediately see one.)

**Review by jukkar — APPROVED** [review]

**Comment by rmstoi** [comment]
@pfalcon Thanks!

**Pull request merged**
