### PR TITLE
ext: gecko: Update Silabs Gecko HAL to v5.6.1

### PR DESCRIPTION
**Pull request by chrta**
Origin: Silicon Labs Gecko SDK
URL: https://www.silabs.com/products/development-tools/software/simplicity-studio
Version: v5.6.1
Purpose: Add support for Silicon Labs EXX32 SoCs
License: Zlib
Maintained-by: External

Signed-off-by: Christian Taedcke <hacking@taedcke.com>

### CODE REVIEW

**Comment by chrta** [comment]
Since the Gecko SDK on github is no longer maintained, this version was taken from the Linux version of Simplicity Studio 4 and copied into the zephyr ext/hal folder.
Most changes are whitespace changes (line endings). I did not change the line endings to reduce the diff to keep the original files as is.

**Comment by chrta** [comment]
@galak @MaureenHelm No reviewer is assigned for this pull request.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Can you updated & resolve the merge conflicts.

**Comment by chrta** [comment]
@galak Done (rebased and added EFM32PG12 files)

**Comment by mnkp** [comment]
> Most changes are whitespace changes (line endings). I did not change the line endings to reduce the diff to keep the original files as is.

It's a big diff, I didn't check what are the line endings and it's not clear to me from the above comment, but in general I think we should better make sure that all are uniform and aligned with Zephyr's '\n'. checkpatch does this check on the native code and prevents pushing files with incorrect line endings but ext/ is excluded.

Most of the tools these days are agnostic but there are always a few used by someone that fail in some strange way if line endings don't match.

**Comment by chrta** [comment]
@mnkp I just checked. Previously dos line ending were used (v5.1.2), because these line ending are used in the Silabs SDK in this version. Now all files have unix line endings.

**Comment by mnkp** [comment]
@chrta thanks for the info and updating SiLabs SDK, the change is most welcome!

**Pull request merged**
