### PR TITLE
net: coap_client: Various fixes

### PR DESCRIPTION
**Pull request by SeppoTakalo**
This is quite long chain of fixes that I noticed when I started to fix just some simple error cases.
See individual commits for explanations.

## Main refactoring of socket handling thread

Refactor the CoAP retry handling into the handle_poll() function,
so that we only try to send retries if the socket reports POLLOUT.
POLLOUT means that socket is capable of sending, and most probably would not block.

Also move the receiving into same loop inside `handle_poll()`, so when `poll()` reports POLLIN
we recv() the message and handle it before proceeding to other sockets.
This removes variable 'response_ready' from the client structure.

Socket errors are also handled inside `handle_poll()` and signalled immediately using `cancel_request_with()` instead of delivering it through variable `socket_error` to one loop above. This maintains the functionality introduced in https://github.com/zephyrproject-rtos/zephyr/pull/80303 but uses `cancel_request_with()` to call the callback, instead of separate function.

Also fix tests to handle POLLOUT flag and add support for testing
multiple clients.

## Minor fixes

* Global mutex to protect internal list of clients
* Release internal structures if first message failed to send. If we report failure immediately in `coap_client_req()` nothing needs to be handled in internal thread.
* Socket errors, other than `EAGAIN` cause request to be cancelled, and callback to be called
* `EGAIN` does not cause CoAP retry counter to be increased. Instead try to send same packet once `poll()` returns POLLOUT.
* Every time we release internal request structure, it goes through  `reset_internal_request()`
* Stop request when receiving CoAP RESET message
* Send CoAP RESET if we receive request that we are not handling.
* Increase test coverage

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
Looks good (save the conflicting change)

**Comment by SeppoTakalo** [comment]
I'll start working on rebase as the https://github.com/zephyrproject-rtos/zephyr/pull/80303 actually addressed the same issue than one of my changes, but did it differently.

I'll refactor this a bit..

**Comment by SeppoTakalo** [comment]
Updated the description to covers the intention of this PR.

**Review by rlubos — APPROVED** [review]
Looks good

**Review by simensrostad — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
