### PR TITLE
pm: Make APIs consistent with the rest of the subsystem

### PR DESCRIPTION
**Pull request by ceolin**
- Rename APIs to align with the rest of the subsystem
- Replace macros with inline functions

v2:
- Fix an undefined reference caused by one of the renamings.

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]

**Review by carlocaione — DISMISSED** [review]
LGTM

**Review by brockus-zephyr — DISMISSED** [review]

**Review by chrta — DISMISSED** [review]

**Review by GTLin08 — DISMISSED** [review]

**Review by albertofloyd — DISMISSED** [review]

**Review by dleach02 — DISMISSED** [review]

**Comment by dleach02** [comment]
@ceolin will you address the conflicts?

**Comment by ceolin** [comment]
> @ceolin will you address the conflicts?

yep, doing it.

**Comment by ceolin** [comment]
I've rebased this pr. Please can you re-review it :)

**Review by carlocaione — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
