### PR TITLE
RP2040 basic support (draft)

### PR DESCRIPTION
**Pull request by ioannisg**
Draft PR for RP2040 basic support

- [x]  SoC and SoC series definition
- [ ]  Device tree support
- [ ]  Board support (pico)
- [ ]  Basic drivers
       - timer (SysTick)
       - serial

- [ ] Requires HAL definition

### CODE REVIEW

**Comment by atharvalele** [comment]
Hey! I'm interested in Zephyr and helping with the port for RPi Pico. Do you have any suggestions/tasks that I might take up?

I've gone through the documentation at https://docs.zephyrproject.org/1.12.0/porting/board_porting.html

**Comment by burumaj** [comment]
I don't think the serial driver has to be implemented. The UART peripheral is based on the ARM PL011, which is already supported by zephyr.

**Comment by burumaj** [comment]
Another thing that would need to happen is adding a stage 2 bootloader. This part would be responsible for initializing the XIP hardware. This how the pico sdk does this (https://github.com/raspberrypi/pico-sdk/tree/master/src/rp2_common/boot_stage2).
For the pico this would be using [boot2_w25q080.S](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/boot_stage2/boot2_w25q080.S) file. This code needs to be located at the start of the firmware image to be bootable. 

Since this is a board specific property this should probably be placed in the pico board folder. Another option I can see to do this, is to configure this when selecting the SoC for example add this to KConfig.series:

```
if SOC_SERIES_RP20XX
choice BOOT_STAGE2_LOADER
    prompt "Support for XIP flash"

config SOC_BOOT_STAGE2_W25Q080
    bool "w25q080 stage 2"

endchoice
endif
```
then add configs options for all supported flash devices.  Probably starting out with all devices supported by pico-sdk.

**Comment by coderkalyan** [comment]
Hello @ioannisg , I also started this but seems you've made more progress than I have! Let me know if I can be of help

**Comment by soundsreal** [comment]
hi @ioannisg any work on the device tree support? I just bought a few chips, keen on helping out.

**Comment by gmarull** [comment]
Support has been merged now, closing

**Pull request closed without merging**
