### PR TITLE
arm: mcux (RT1060 EVK) fix USB fail when using on-chip memory, fix #27268

### LINKED ISSUE #27268: usb: mcux RT1060 EVK - when using on-chip memory, USB fails
**Describe the bug**
USB fails to configure when using on-chip memory rather than the default external DDR RAM.

**To Reproduce**
Change the default DATA_LOCATION to DATA_OCRAM instead of DATA_SEMC.
(be sure to unplug the USB port between resets - I have seen it mask the issue if left plugged in.)
using the samples/subsys/usb/hid example

**Expected behavior**
USB should configure and work.

**Impact**
USB showstopper

**Logs and console output**
-- Using DATA_SEMC (normal and expected):
*** Booting Zephyr OS build zephyr-v2.3.0-1418-g68ef393d2551  ***
[00:00:00.005,000] <dbg> main.composite_pre_init: HID Device: dev 0x80002058
[00:00:00.005,000] <dbg> main.main: Starting application
[00:00:00.189,000] <dbg> main.status_cb: status 1 unhandled
[00:00:00.314,000] <dbg> main.status_cb: status 1 unhandled
[00:00:02.440,000] <dbg> main.send_report: Wrote 2 bytes with ret 0

-- Using DATA_OCRAM (bug):
*** Booting Zephyr OS build zephyr-v2.3.0-1418-g68ef393d2551  ***
[00:00:00.005,000] <dbg> main.composite_pre_init: HID Device: dev 0x20202058
[00:00:00.005,000] <dbg> main.main: Starting application
[00:00:00.006,000] <err> os: ***** BUS FAULT *****
[00:00:00.006,000] <err> os:   Precise data bus error
[00:00:00.006,000] <err> os:   BFAR Address: 0xdd416a2c
[00:00:00.006,000] <err> os: r0/a1:  0x20200600  r1/a2:  0xdd416a28  r2/a3:  0x00000001
[00:00:00.006,000] <err> os: r3/a4:  0x94cefdf7 r12/ip:  0x00000040 r14/lr:  0x60007d53
[00:00:00.006,000] <err> os:  xpsr:  0xa1002c00
[00:00:00.006,000] <err> os: Faulting instruction address (r15/pc): 0x60007d2a
[00:00:00.006,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.006,000] <err> os: Current thread: 0x20202320 (unknown)
[00:00:00.053,000] <err> os: Halting system

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA 68ef393d255152797d99a271487839d5a70139ab (July 29, 2020)

**Additional context**

I have located the general area where the fault is occurring:

usb_dc_mcux_ehci.c:  lines 203..
```
if (k_mem_pool_alloc(&ep_buf_pool, block, cfg->ep_mps, K_MSEC(10))) {
	LOG_ERR("Memory allocation time-out");
	return -ENOMEM;
}
```

### PR DESCRIPTION
**Pull request by CristXu**
Adds the couple SCB_DisableDcache & SCB_EnableDcache when
config the non-cache area

Signed-off-by: Crist Xu <crist.xu@nxp.com>

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Can you explain in the commit message why disabling the cache before setting up the mpu region addresses the issue.

**Comment by CristXu** [comment]
> Can you explain in the commit message why disabling the cache before setting up the mpu region addresses the issue.

Updated， And could you please help try if this can fix the issue?

**Review by galak — COMMENTED** [review]
I dont know enough about the ARM cache's to say, but it seems like having the code you had before was safer.  To Disable (which will Clean & Invalidate) the d-cache and having it disabled before we setup the MPU region.

@ioannisg @MaureenHelm any thoughts?

**Comment by CristXu** [comment]
> I dont know enough about the ARM cache's to say, but it seems like having the code you had before was safer. To Disable (which will Clean & Invalidate) the d-cache and having it disabled before we setup the MPU region.
> 
> @ioannisg @MaureenHelm any thoughts?

**Review by ioannisg — CHANGES_REQUESTED** [review]
I think that the cleaning and invalidation of the D-cache has little to do with the MPU driver initialization, ti begin with. 

So I would better see this called in SoC init or platform-init code.
Also, for platforms that have Cache (not sure if this is present in all Cortex-M7 implementations, maybe @CristXu you can investigate this).

**Comment by CristXu** [comment]
> I think that the cleaning and invalidation of the D-cache has little to do with the MPU driver initialization, ti begin with.
> 
> So I would better see this called in SoC init or platform-init code.
> Also, for platforms that have Cache (not sure if this is present in all Cortex-M7 implementations, maybe @CristXu you can investigate this).

Through the Cortex-m7's block diagram, it seems that both the D-Cache & I-Cache are all exists, but yes, i will investigate some MCU to see if they all support the cache.
image

**Comment by carlescufi** [comment]
@MaureenHelm @jfischer-phytec-iot @CristXu can we agree to a fix here?

**Comment by carlescufi** [comment]
@CristXu will you pick this up this week or next? We need to fix this for 2.4.

**Comment by CristXu** [comment]
> @CristXu will you pick this up this week or next? We need to fix this for 2.4.

Hi，I am waiting for the reponse from the reviewer, no one comment or approve my method.

**Comment by ioannisg** [comment]
@CristXu thanks for your investigation.

I think that calling the SCB function for cleaning and invalidating the cache for all Cortex-M7 should be OK to do.

My concern is that it should be executed
- only if the no-cache region is used (there are #ifdef's for this)
- as part of some ARCH-initialization code. I feel, it should not be done in the static region configuration. I think it fits better in some cortex-m init code, or, at a last resort inside arm_mpu_init code

**Comment by CristXu** [comment]
> @CristXu thanks for your investigation.
> 
> I think that calling the SCB function for cleaning and invalidating the cache for all Cortex-M7 should be OK to do.
> 
> My concern is that it should be executed
> 
> * only if the no-cache region is used (there are #ifdef's for this)
> * as part of some ARCH-initialization code. I feel, it should not be done in the static region configuration. I think it fits better in some cortex-m init code, or, at a last resort inside arm_mpu_init code

Hi, Updated the new code, put the cache operation inside the arm_mpu_init, controlled by the CONFIG_NOCACHE_MEMORY

**Review by ioannisg — APPROVED** [review]
LGTM now

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
