### PR TITLE
doc: conf.py: revert 2e99de80 (unnecessary and breaks PDF build)

### PR DESCRIPTION
**Pull request by kartben**
This reverts commit 2e99de80472b80f36303ff85c8ed5d54dfe73ef4 as it's introducing an unneeded change that also happens to break PDF build as it is making the assumption that the build output folder is always `html` (but it can be `latex`, etc.)

### CODE REVIEW

**Comment by kartben** [comment]
@JordanYates please confirm I didn't oversee anything.
BTW, it looks as if `html-live` and `html-live-fast` require `html` target to have run once first, as it wants the html build folder to exist. Should the html-live CMake target depend on html?

**Comment by JordanYates** [comment]
The commit is definitely required on my end.. Reverting it results in
```
(.zephyr_venv) jordan@TAURUS:~/code/zephyr/zephyr/doc$ make html-live
cmake \
        -GNinja \
        -B_build \
        -S. \
        -DDOC_TAG=development \
        -DSPHINXOPTS="-j auto -W --keep-going -T" \
        -DSPHINXOPTS_EXTRA="" \
        -DLATEXMKOPTS="-halt-on-error -no-shell-escape" \
        -DDT_TURBO_MODE=0
Loading Zephyr module(s) (Zephyr base): doc
-- Found Python3: /home/jordan/code/.zephyr_venv/bin/python (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter
-- Cache files will be written to: /home/jordan/.cache/zephyr
-- Found west (found suitable version "1.2.0", minimum required is "1.0.0")
-- Zephyr base: /home/jordan/code/zephyr/zephyr
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen dot
-- Found LATEX: /usr/bin/latex  found components: PDFLATEX
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jordan/code/zephyr/zephyr/doc/_build
cmake --build _build --target html-live
[0/2] Generating Devicetree bindings documentation...
[1/2] Running Sphinx HTML autobuild...
[sphinx-autobuild] Starting initial build
[sphinx-autobuild] > sphinx-build -b html -c /home/jordan/code/zephyr/zephyr/doc -d /home/jordan/code/zephyr/zephyr/doc/_build/doctrees -w /home/jordan/code/zephyr/zephyr/doc/_build/html.log -t development -j auto -W --keep-going -T /home/jordan/code/zephyr/zephyr/doc/_build/src /home/jordan/code/zephyr/zephyr/doc/_build/html
Running Sphinx v6.2.1
usage: sphinx-autobuild [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-autobuild: error: unrecognized arguments: --watch --ignore /home/jordan/code/zephyr/zephyr/doc/_build/src /home/jordan/code/zephyr/zephyr/doc/_build/html

Traceback (most recent call last):
  File "/home/jordan/code/.zephyr_venv/lib/python3.10/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/jordan/code/zephyr/zephyr/doc/conf.py", line 12, in <module>
    args = get_parser().parse_args()
  File "/usr/lib/python3.10/argparse.py", line 1848, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.10/argparse.py", line 2606, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.10/argparse.py", line 2593, in exit
    _sys.exit(status)
SystemExit: 2
...
```

There is also no requirement to run `html` before `html-live`, it takes care of the first build.

**Comment by kartben** [comment]
@JordanYates at the risk of stating the obvious, are you `rm -rf _build` prior to building? Also, which version of autobuild are you running? Latest version has a hard check for html folder existence (but it might be a bug?) https://github.com/sphinx-doc/sphinx-autobuild/commit/41a7d8ced2a23a3dc533341a2950209ab871eece

**Comment by kartben** [comment]
On main:

```
cd doc
pip3 install -r ./requirements.txt --no-cache-dir --force-reinstall -U
rm _build -Rf && make html-live

...

[1/2] Running Sphinx HTML autobuild...
Traceback (most recent call last):
  File "/Users/kartben/zephyrproject/.venv/bin/sphinx-autobuild", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/kartben/zephyrproject/.venv/lib/python3.12/site-packages/sphinx_autobuild/__main__.py", line 34, in main
    args, build_args = _parse_args(list(argv))
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kartben/zephyrproject/.venv/lib/python3.12/site-packages/sphinx_autobuild/__main__.py", line 101, in _parse_args
    args.outdir = Path(sphinx_args.outputdir).resolve(strict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1240, in resolve
    s = self._flavour.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 427, in realpath
  File "<frozen posixpath>", line 462, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kartben/zephyrproject/zephyr/doc/_build/html'
FAILED: CMakeFiles/html-live /Users/kartben/zephyrproject/zephyr/doc/_build/CMakeFiles/html-live 
cd /Users/kartben/zephyrproject/zephyr/doc/_build && /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E env DOXYGEN_EXECUTABLE=/opt/homebrew/bin/doxygen DOT_EXECUTABLE=/opt/homebrew/bin/dot DOCS_HTML_DIR=/Users/kartben/zephyrproject/zephyr/doc/_build/html /Users/kartben/zephyrproject/.venv/bin/sphinx-autobuild --watch /Users/kartben/zephyrproject/zephyr/doc --ignore /Users/kartben/zephyrproject/zephyr/doc/_build -b html -c /Users/kartben/zephyrproject/zephyr/doc -d /Users/kartben/zephyrproject/zephyr/doc/_build/doctrees -w /Users/kartben/zephyrproject/zephyr/doc/_build/html.log -t development -j auto -W --keep-going -T /Users/kartben/zephyrproject/zephyr/doc/_build/src /Users/kartben/zephyrproject/zephyr/doc/_build/html
ninja: build stopped: subcommand failed.
make: *** [html-live] Error 1

```

**Comment by JordanYates** [comment]
> @JordanYates at the risk of stating the obvious, are you `rm -rf _build` prior to building? Also, which version of autobuild are you running? Latest version has a hard check for html folder existence (but it might be a bug?) [sphinx-doc/sphinx-autobuild@41a7d8c](https://github.com/sphinx-doc/sphinx-autobuild/commit/41a7d8ced2a23a3dc533341a2950209ab871eece)

Okay, the behavior has changed after updating from `2024.04.16` to `2024.09.03`. Presumably something to do with:
`Fix running sphinx-autobuild via entry point scripts.`
https://github.com/sphinx-doc/sphinx-autobuild/blob/main/NEWS.rst#20240903---2024-09-03

**Comment by kartben** [comment]
> There is also no requirement to run html before html-live, it takes care of the first build.

That's also what I seemed to remember from having tested the PR a few weeks back. 
So could it be that both this PR is needed, and a bug should be filed against sphinx-autobuild given it doesn't seem to properly address "clean builds" anymore?

**Comment by JordanYates** [comment]
> > There is also no requirement to run html before html-live, it takes care of the first build.
> 
> That's also what I seemed to remember from having tested the PR a few weeks back. So could it be that both this PR is needed, and a bug should be filed against sphinx-autobuild given it doesn't seem to properly address "clean builds" anymore?

Looks like it already exists: https://github.com/sphinx-doc/sphinx-autobuild/issues/177.

As for the rest, I'm not convinced that attempting to re-parse the CLI arguments is the best solution, but I guess it doesn't break non-HTML output like my change did. Alternate option is to make a change like the following and use the new variable in `conf.py`:
```
add_doc_target(
  html
  COMMAND ${CMAKE_COMMAND} -E env ${SPHINX_ENV} OUTPUT_FOLDER=${DOCS_HTML_DIR}
  ...
)
```

**Comment by JordanYates** [comment]
Linked PR in Sphinx autobuild has been merged and a new release is available.
I validated that `make html-live` now works correctly from the doc folder without a previous run.

**Pull request closed without merging**
