### PR TITLE
ext: hal: Make Nordic HALs a Zephyr module

### PR DESCRIPTION
**Pull request by carlescufi**
Moved to an external repo,
https://github.com/zephyrproject-rtos/hal_nordic.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
given that this is just code restructuring without any functional changes, I propose to move all other ext/ components into modules and have this be part of 2.0. After feature freeze is the right time to do that, before it is always in conflict with some PR. Given this is not a new feature and no functional changes are introduced, we should attempt to have 2.0 ext/ free.

**Comment by carlescufi** [comment]
> given that this is just code restructuring without any functional changes, I propose to move all other ext/ components into modules and have this be part of 2.0. After feature freeze is the right time to do that, before it is always in conflict with some PR. Given this is not a new feature and no functional changes are introduced, we should attempt to have 2.0 ext/ free.

I second that proposal.

**Comment by galak** [comment]
> I second that proposal.

I'm for it as well, but obviously any such proposal would need TSC approval.

**Comment by ioannisg** [comment]
Could this, instead, be done, _first_, after we release 2.0?

**Review by galak — APPROVED** [review]

**Pull request merged**
