### PR TITLE
[Backport v3.1-branch] Bluetooth: Controller: Fix Tx Buffer allocation for Encryption Request

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 1f2cbbf3186f9db2bd8e18e2c465070f03523365~3..1f2cbbf3186f9db2bd8e18e2c465070f03523365 from #46253

### CODE REVIEW

**Comment by jhedberg** [comment]
Do we really want to backport the new sample too? Wouldn’t the controller fix commit be sufficient?

**Review by carlescufi — APPROVED** [review]

**Comment by cvinayak** [comment]
> Do we really want to backport the new sample too? Wouldn’t the controller fix commit be sufficient?

Good point, what has been the convention? We do not need to have the test that uncovers a bug?
(I am ok with just the bug fix being backported)

**Comment by jhedberg** [comment]
> > Do we really want to backport the new sample too? Wouldn’t the controller fix commit be sufficient?
> 
> Good point, what has been the convention? We do not need to have the test that uncovers a bug? (I am ok with just the bug fix being backported)

@carlescufi any thoughts on this?

**Review by cvinayak — APPROVED** [review]

**Comment by carlescufi** [comment]
> > > Do we really want to backport the new sample too? Wouldn’t the controller fix commit be sufficient?
> > 
> > 
> > Good point, what has been the convention? We do not need to have the test that uncovers a bug? (I am ok with just the bug fix being backported)
> 
> @carlescufi any thoughts on this?

Yes, Given that it's a new sample, I would be in favor of backporting it as long as it works, because it has no chance of disrupting the 3.1.0 BLE stack.

**Comment by fabiobaltieri** [comment]
@cvinayak do you have a bug report we can use for this?

**Pull request closed without merging**
