### PR TITLE
samples: net: mqtt: updating TLS certificate for test.mosquitto.org

### PR DESCRIPTION
**Pull request by mtahirbutt**
Signed-off-by: Tahir Akram <mtahirbutt@hotmail.com>

This PR address the update of fresh TLS certificate
(valid till 07.06.2030) for test.mosquitto.org.
The IP address is also updated in addition.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
The PR itself looks ok, but could you change the commit message a bit. We always put the signed-off-by: line at the end of the message.

**Review by rlubos — COMMENTED** [review]
I don't think we should replace the default certificate in the sample, wasn't the current one was set to be used with `net-tools` MQTT TLS test? (https://github.com/zephyrproject-rtos/zephyr/pull/23720)

**Comment by jukkar** [comment]
> wasn't the current one was set to be used with `net-tools` MQTT TLS test? (#23720)

Indeed, that is good point. Lets keep the default one as is.

@mtahirbutt If you want, you could supply a PR that allows user to read the cert from a user supplied file. Something like this is done in test_certs.h already but currently it is only enabled for offloaded sockets. I think we could allow it for normal sockets too.

**Comment by mtahirbutt** [comment]
> 
> 
> > wasn't the current one was set to be used with `net-tools` MQTT TLS test? (#23720)
> 
> Indeed, that is good point. Lets keep the default one as is.
> 
> @mtahirbutt If you want, you could supply a PR that allows user to read the cert from a user supplied file. Something like this is done in test_certs.h already but currently it is only enabled for offloaded sockets. I think we could allow it for normal sockets too.

alright, thanks for the response

**Pull request closed without merging**
