### PR TITLE
docs: acrn: update the documentation of setting the ACRN hypervisor

### PR DESCRIPTION
**Pull request by enjiamai**
Add some descriptions of hybrid scenario of ACRN hypervisor, and
completed the configurations that we are using to build ACRN. This
configuration change for ACRN hypervisor is necessary when our Zephyr
application is using over than one CPU for it.

Signed-off-by: Enjia Mai <enjia.mai@intel.com>

### CODE REVIEW

**Review by aasthagr — APPROVED** [review]

**Comment by laurenmurphyx64** [comment]
Hi Maksim! Here's [the link to my patch with the suggested edits](https://gist.githubusercontent.com/laurenmurphyx64/a191653d26b5cbc8703c8ba6d6294dd0/raw/39628f6fb78b2a8c31bb322f97365dfb263b25fe/edits.patch). I'm not too familiar with ACRN, so if my edit makes a statement incorrect, let me know.

**Comment by maksimmasalski** [comment]
> Hi Maksim! Here's [the link to my patch with the suggested edits](https://gist.githubusercontent.com/laurenmurphyx64/a191653d26b5cbc8703c8ba6d6294dd0/raw/39628f6fb78b2a8c31bb322f97365dfb263b25fe/edits.patch). I'm not too familiar with ACRN, so if my edit makes a statement incorrect, let me know. Tag me when you've reviewed and decided which / any of the edits to add and I'll add my approval to the PR after 👍

Lauren, you are always doing perfect patches, thanks^_^

**Comment by enjiamai** [comment]
Hi @laurenmurphyx64 , @maksimmasalski  I updated the content according to your suggestion, could you please take a look at it? thanks!

**Review by maksimmasalski — APPROVED** [review]

**Comment by enjiamai** [comment]
> Hi @enjiamai, sorry I didn't get a chance to look before it merged but it looks good to me!

No worry, thanks so much for your patch of review :)

**Pull request merged**
