### PR TITLE
Bluetooth: ISO: Fix BIG cleanup

### LINKED ISSUE #35838: Bluetooth: ISO: BIG termination doesn't fully unref the connection
**Describe the bug**
After https://github.com/zephyrproject-rtos/zephyr/commit/80c824f18ee80caa5bd162b9d2957dde1639add6 was merged BIG termination no longer works as intended as it is missing a bt_conn_unref on termination. 

**To Reproduce**
1. Create BIG
2. Terminate BIG

**Expected behavior**
On BIG termination, the bt_conn should reach 0 ref's and be fully cleaned up. 

**Impact**
Break Broadcast ISO termination

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/commit/80c824f18ee80caa5bd162b9d2957dde1639add6

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Fix a regression for cleaning up BIGs added by
80c824f18ee80caa5bd162b9d2957dde1639add6

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

Fixes #35838

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
@Thalley if you think this needs to go to 2.6 I think you'll need to open an issue and link this one to it. AFAIK only PRs that close issues are accepted at this late stage of the release process.

**Comment by Thalley** [comment]
> @Thalley if you think this needs to go to 2.6 I think you'll need to open an issue and link this one to it. AFAIK only PRs that close issues are accepted at this late stage of the release process.

@jhedberg Thanks, created an issue for it

**Review by joerchan — APPROVED** [review]
Changes looks OK.

The commit message could have been better. It does not explain what the regression was, also I don't see all the changes in this commit in the regression commit, the unref in the for loop looks unrelated to me.

**Comment by Thalley** [comment]
> Changes looks OK.
> 
> The commit message could have been better. It does not explain what the regression was, also I don't see all the changes in this commit in the regression commit, the unref in the for loop looks unrelated to me.

Agreed. Updated it to be more descriptive.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
