### PR TITLE
arch: riscv: pmp: Support fixed SoC PMP regions

### LINKED ISSUE #39922: Instruction fetch fault happens on RISC-V with XIP and userspace enabled
**Describe the bug**
When run samples/userspace/hello_world_user on hifive1_revb with XIP enabled, instruction fetch fault happens.

The value set to the pmpaddr1 register was not appropriate for NAPOT format.
pmpaddr0 : 0x20000004 (NA4   0x80000010 - 0x80000013)
pmpaddr1 : 0x08006442 (NAPOT invalid value)
pmpaddr2 : 0x20000c7f (NAPOT 0x80003000 - 0x800033FF)
pmpcfg0  : 0x001b1d11

**Expected behavior**
"Table 3.9: NAPOT range encoding in PMP address and configuration registers" of "Volume II: RISC-V Privileged Architectures V1.10" says,
> aaaa...aaa0 NAPOT 8-byte NAPOT range
> aaaa...aa01 NAPOT 16-byte NAPOT range
> aaaa...a011 NAPOT 32-byte NAPOT range
> ...

The size part of NAPOT value should be power of two. And when the size is larger than 16 bytes, LSB bit should be 1.

**To Reproduce**
1. Modify samples/userspace/hello_world_user/src/main.c so that the link result does not exceed the RAM capacity.
```
< #define USER_STACKSIZE	2048

> #define USER_STACKSIZE	1024
```
2. west build -b hifive1_revb samples/userspace/hello_world_user
3. cd build/zephyr
4. $ZEPHYR_SDK_INSTALL_DIR/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-objcopy -O ihex zephyr.elf zephyr.hex
5. Write zephyr.hex to the Hifive1 revB board and run.

**Logs and console output**
> *** Booting Zephyr OS build v2.7.99-779-gf6e829a68b1a  ***
> E:
> E:  mcause: 1, Instruction Access fault
> E:   mtval: 2001367c
> E:      a0: 20010e7c    t0: 20013680
> E:      a1: 00000000    t1: 200137fc
> E:      a2: 00000000    t2: 7fffffff
> E:      a3: 00000000    t3: 2001d484
> E:      a4: 00000001    t4: 2001d484
> E:      a5: 80000000    t5: 2001d484
> E:      a6: 00000000    t6: 2001d484
> E:      a7: ffffffff
> E:                      tp: 2001d484
> E:      ra: 200137c0
> E:    mepc: 2001367c
> E: mstatus: 00000080
> E:
> E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
> E: Current thread: 0x80000048 (unknown)
> E: Halting system

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Toolchain: zephyr-sdk-0.13.1
 - Version: v2.7.99
 - Commit: f6e829a68b1ae7b127bb847d0947df0cc9f708a2
 - Target: hifive1_revb

**Additional context**

Workaround:
The value of pmpaddr is calcuteled at zephyr/arch/riscv/core/pmp/core_pmp.c.
```
 234 :        ulong_t rom_size = (ulong_t) __rom_region_size;
 250 :        thread->arch.u_pmpaddr[index] = TO_PMP_NAPOT(rom_start, rom_size);
 251 :        uchar_pmpcfg[index++] = PMP_NAPOT | PMP_R | PMP_X;
```
In this implementation, rom_size is expected to be power of two.
For workaround, change zephyr/include/arch/riscv/common/linker.ld as following,
```
< __rom_region_size = __rom_region_end - __rom_region_start;

> __rom_region_size_orig = __rom_region_end - __rom_region_start;
> __rom_region_size = (1 << LOG2CEIL(__rom_region_size_orig));
```

After changes, 
pmpaddr0 : 0x20000004 (NA4   0x80000010 - 0x80000013)
pmpaddr1 : 0x08007fff (NAPOT 0x20000000 - 0x2003FFFF)
pmpaddr2 : 0x20000c7f (NAPOT 0x80003000 - 0x800033FF)
pmpcfg0  : 0x001b1d11

### PR DESCRIPTION
**Pull request by cwshu**
Support fixed SoC PMP regions to set ROM and RAM default access policies. 
And it provide each SoC to customize these regions based on it's memory layout.
In this PR, we only implement ROM protection. RAM protection support is the future work.

This PR introduce 2 ways to use SoC PMP regions:

1. By default, SoC use common SoC PMP regions
2. SoC could define and use custom SoC PMP regions by new Kconfig option: `CONFIG_CPU_HAS_CUSTOM_FIXED_SOC_PMP_REGIONS`

If SoC only use 1 FLASH + 1 SRAM and the all start addresses of them match the alignment of PMP region, SoC could use common PMP regions. Otherwise, SoC needs to use custom PMP regions.
Lets FE310 SoC use custom PMP regions to align the flash start in PMP region of some FE310 boards

Also, this PR create new directory `soc/riscv/common` to place common fixed SoC PMP regions, which follows Cortex-M design in `soc/arm/common`. Another way is placing them in `soc/riscv/riscv-privilege/common/`.  I am not sure if any non-privileged SoC has standard RISC-V PMP or not (vexriscv PMP plugin?). Because PMP implementation is at `arch/riscv/`, I assume non-privileged SoCs may use it so I places them in `soc/riscv/common`.

Fix #39922

depend on #39299 (This PR only contains last 2 commits)

### CODE REVIEW

**Comment by cwshu** [comment]
#41399 has the same issue as #39922. This PR partially fix #41399.
Change to non-draft for reviewing since there are many issues related to this PR.

**Comment by fkokosinski** [comment]
Hi, I wanted to test your changes on `hifive1` board. Unfortunately, I wasn't able to build binaries properly from your branch (rebased onto the branch you've said here that this PR is dependent on). I've made the following modification to the `samples/userspace/hello_world_user/prj.conf`:

    +CONFIG_RISCV_PMP=y
    +CONFIG_PMP_STACK_GUARD=y

I'm attaching the [log file](https://github.com/zephyrproject-rtos/zephyr/files/7801428/hifive1_userspace_hello_world_log.txt) to this comment. Most of the errors there seem to be syntax-related. Could you maybe elaborate on how you were testing these changes?

**Comment by cwshu** [comment]
@fkokosinski Thanks for your testing!

It looks like a bug in `CONFIG_PMP_STACK_GUARD=y`, I will try to fix it soon.
I will test `CONFIG_PMP_STACK_GUARD=y` at 1st time sending PR #39299. it may got broken when rebasing.

You could try it with `CONFIG_RISCV_PMP=y` only at first, I will verify it on `qemu_riscv32_xip` at least.

**Comment by cwshu** [comment]
@fkokosinski PMP stack guard bug has been fixed.
I could run `hello_world_user` sample on `qemu_riscv32_xip` with these additional configs

```
CONFIG_RISCV_PMP=y
CONFIG_PMP_STACK_GUARD=y

# avoid ram overflow
CONFIG_MAIN_STACK_SIZE=2048
```

p.s. QEMU needs to be patched, since PMP stack guard will hit an overflow bug of 4GB (2^XLEN bytes) PMP NAPOT region in QEMU. I will send QEMU bugfix to upstream later.
https://github.com/cwshu/qemu/tree/pmp_shift_overflow

**Comment by cwshu** [comment]
Sorry, I have wrongly deleted this branch.
Re-open this PR.

**Comment by fkokosinski** [comment]
> @fkokosinski PMP stack guard bug has been fixed. I could run `hello_world_user` sample on `qemu_riscv32_xip` with these additional configs
> 
> ```
> CONFIG_RISCV_PMP=y
> CONFIG_PMP_STACK_GUARD=y
> 
> # avoid ram overflow
> CONFIG_MAIN_STACK_SIZE=2048
> ```
> 
> p.s. QEMU needs to be patched, since PMP stack guard will hit an overflow bug of 4GB (2^XLEN bytes) PMP NAPOT region in QEMU. I will send QEMU bugfix to upstream later. https://github.com/cwshu/qemu/tree/pmp_shift_overflow

Hi, I can confirm that now I can successfully build the aforementioned sample for `hifive` board. Unfortunately, it seems to not be working, i.e. I'm not getting any output from UART.

**Comment by fkokosinski** [comment]
@cwshu your latest commits seem to have fixed the issues that I previously had on the `hifive1` board (as described above). Could you rebase your branch, as it now has conflicts?

**Comment by cwshu** [comment]
@fkokosinski
OK, I will rebase this PR and verify it on QEMU. 
However, I am busy in this weekday, so I will do it in the weekend.

**Comment by fkokosinski** [comment]
Hi @cwshu!

https://github.com/zephyrproject-rtos/zephyr/pull/44651 has landed since your last update here. Could you perhaps take a loot and test if it supersedes your changes introduced by this PR, as you modify the same files here?

**Pull request closed without merging**
