### PR TITLE
Enabling support of TI CC1352P7 Launchpad

### PR DESCRIPTION
**Pull request by anobli**
This adds support of the TI CC1352P7 Launchpad.
The launchpad is very similar the the CC1352P1-Launchxl.
To leverage the maintenance,  this creates a common folder to share sources between the CC1352P1-Launchxl. and CC1352P7-LP.

### CODE REVIEW

**Comment by kartben** [comment]
@anobli can you please update the PR title? This looks like more than "Enabl[ing] support of OpenThread on TI CC1352P7" :)

**Comment by vaishnavachath** [comment]
@jadonk @Ayush1325

**Comment by vaishnavachath** [comment]
@anobli Can you please separate these PR to have the platform additions and Openthread support addition into separate PRs?

**Comment by cfriedt** [comment]
@anobli - you may want to run the following to check coding style

```shell
./scripts/checkpatch.pl -g main..
```

and if there are any tests failing, use

```shell
twister -i -p <platform> -s <foo.test.label>
```

Looks good though 👍 

Zephyr has a code freeze atm due to the lts release cycle, so it might take a bit of time.

**Comment by anobli** [comment]
> @anobli Can you please separate these PR to have the platform additions and Openthread support addition into separate PRs?

I have opened another PR: https://github.com/zephyrproject-rtos/zephyr/pull/74501

**Review by cfriedt — APPROVED** [review]

**Review by vaishnavachath — APPROVED** [review]

**Pull request merged**
