### PR TITLE
ipc: Remove multi-instance backend

### PR DESCRIPTION
**Pull request by carlocaione**
Remove the legacy multi-instance backend and the sample. I don't think there is anyone actively using this.

@hubertmis do you know if someone is still interested in this backend?

### CODE REVIEW

**Comment by hubertmis** [comment]
@grochu, do you know if the legacy ipc_service backend is used anywhere?

**Comment by arnopo** [comment]
Duplication between this one and #41785 ?

**Comment by carlocaione** [comment]
> Duplication between this one and #41785 ?

Oh, fun.  Closing that down (they are the same PR).

**Review by arnopo — APPROVED** [review]
I see no reason on my side to keep it.
Nitpicking : what about splitting in  2 commits one to remove the sample, the second one to  remove the service?

**Review by carlescufi — APPROVED** [review]

**Comment by grochu** [comment]
> @grochu, do you know if the legacy ipc_service backend is used anywhere?

@hubertmis it is (or rather was) OK to remove it.

**Pull request merged**
