### PR TITLE
Bluetooth: controller: Restructure LLL include files

### PR DESCRIPTION
**Pull request by wopu-ot**
Move LLL header files for all roles to common folder. Move
vendor-specific content to internal header files, in particular ADV
buffer handling. Define the vendor-specific type lll_adv_pdu in a
separate header file lll_adv_pdu.h to avoid cyclic dependency when
moving ADV buffer handling to internal header file. Make sure all
internal header files are in vendor-specific folders.

The goal is to have a more consistent structure for LLL header files
and allow unconditional inclusion of non-internal LLL header files.

### CODE REVIEW

**Comment by Thalley** [comment]
This is quite similar to the changes proposed in https://github.com/zephyrproject-rtos/zephyr/pull/29785. Might be worth checking out the comments from @thoh-ot from that PR.

**Comment by Thalley** [comment]
@wopu-ot I don't have a great overview of these files, but it's a bit concerning that a restructure or move of files causes a deletion of almost 160 lines of code. Is that due to removal of some duplicated code, or?

**Comment by wopu-ot** [comment]
> @wopu-ot I don't have a great overview of these files, but it's a bit concerning that a restructure or move of files causes a deletion of almost 160 lines of code. Is that due to removal of some duplicated code, or?

Yes, the change removes duplicated files and definitions. There is no point in having every LLL repeat the definition of interfaces that are necessarily the same.

**Comment by wopu-ot** [comment]
> This is quite similar to the changes proposed in #29785. Might be worth checking out the comments from @thoh-ot from that PR.

The key difference is that this PR separates the common and vendor-specific definitions rather than moving lll_adv.h as it is. I hope that @thoh-ot will agree with this approach.

**Comment by thoh-ot** [comment]
> > This is quite similar to the changes proposed in #29785. Might be worth checking out the comments from @thoh-ot from that PR.
> 
> The key difference is that this PR separates the common and vendor-specific definitions rather than moving lll_adv.h as it is. I hope that @thoh-ot will agree with this approach.

Yes i agree, as this ensures that common LLL interfaces stay the same, while still supporting vendor specific details.

**Review by cvinayak — APPROVED** [review]
quick-ack. No strong opposition to the changes here.

**Review by thoh-ot — APPROVED** [review]

**Pull request merged**
