### PR TITLE
doc: remove SYS_LOG from documentation

### PR DESCRIPTION
**Pull request by nashif**
Make old and obsoleted SYS_LOG orphan until we completely remove it.

### CODE REVIEW

**Review by pabigot — COMMENTED** [review]
It really would be good to leave a pointer to the system that replaces it, in case somebody's bookmarked the page.

**Comment by nashif** [comment]
> It really would be good to leave a pointer to the system that replaces it, in case somebody's bookmarked the page.

not sure what you mean.

**Comment by pabigot** [comment]
> not sure what you mean.

If I go to an API page (from a bookmark, or because Google indexed it and it came up first in the list) and I see a subtle " (Deprecated)" in the header (if I even notice that), my first question will be "So what am I supposed to use instead?".

Yes, somebody who gets there can look a little further up the screen to "Logging >> System Logging" and try to go up a level to see what else might be available.  It just seems like a little more effort here would provide a more natural and supportive user experience.

**Comment by pabigot** [comment]
Link to #12235

**Review by dbkinder — APPROVED** [review]
LGTM

**Review by pabigot — APPROVED** [review]

**Pull request merged**
