### PR TITLE
drivers: timer: fix the use of K_FOREVER and add support for the SAMD/E5x

### PR DESCRIPTION
**Pull request by nzmichaelh**
Change K_FOREVER for the new K_TICKS_FOREVER.

The COUNT register on the ~SAMD51~ SAMD/E5x RTC can only be read if the read synchronisation mode is enabled.

Signed-off-by: Michael Hope <mlhx@google.com>

### CODE REVIEW

**Review by nandojve — CHANGES_REQUESTED** [review]
This will enable all SAM0 series. I only suggest to update commit message to reflect that.

**Comment by nzmichaelh** [comment]
> This will enable all SAM0 series. I only suggest to update commit message to reflect that.

Done

**Review by nandojve — APPROVED** [review]

**Comment by nzmichaelh** [comment]
Rebased to check the buildkite error.

**Review by nandojve — APPROVED** [review]

**Review by stephanosio — CHANGES_REQUESTED** [review]
> Change K_FOREVER for K_TICKS_FOREVER.

> The COUNT register on the SAMD/E5x RTC can only be read if the read
synchronisation mode is enabled.

Could you separate these into two commits?

**Comment by nzmichaelh** [comment]
> Could you separate these into two commits?

Done

**Review by stephanosio — APPROVED** [review]
LGTM

**Pull request merged**
