### PR TITLE
spi: sam: Refactor driver to use SPI RTIO common APIs

### PR DESCRIPTION
**Pull request by ubieda**
### Description
This PR refactors the SPI SAM driver to use SPI RTIO common APIs in a similar approach followed on spi_mcux_lpspi.

### Testing
Build SPI Loopback sample with and without CONFIG_SPI_RTIO:
``` console
west build -b robokit1 tests/drivers/spi/spi_loopback -- -DCONFIG_SPI_RTIO=y

west build -b robokit1 tests/drivers/spi/spi_loopback -- -DCONFIG_SPI_RTIO=n
```
> [!NOTE]
> Running tests on-target is pending, as of lack of hardware.

### CODE REVIEW

**Comment by ubieda** [comment]
@teburd would you mind running a smoke-test on the robokit? I've built it and it looks okay but it's much better if it passes the tests.

**Comment by teburd** [comment]
I can test against the icm42688, don’t recall if the Sam has an internal loop back feature. The robot doesn’t easily expose the spi bus for looping.

**Comment by ubieda** [comment]
Hopefully we'll have time to get this in before feature freeze.

**Review by MaureenHelm — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Comment by ubieda** [comment]
@tbursztyka may I get this reviewed? Thanks!

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
