### PR TITLE
libc: Move strnlen/abort into common

### PR DESCRIPTION
**Pull request by galak**
Move the strnlen/abort implementation into common.

### CODE REVIEW

**Review by keith-packard — APPROVED** [review]
Looks good. Might note that strnlen is in POSIX but not C, leading to its inclusion in the common code for non-POSIX C libraries.

**Review by stephanosio — APPROVED** [review]

**Comment by keith-packard** [comment]
> Yea, but it is part of `POSIX_C_LANG_SUPPORT`, which basically extends the ISO C; so, I would say this is one POSIX thing that may actually belong in the `lib/libc` and not the `lib/posix` :)

Good luck creating rules for what lives where :-)

> By the way, I am trying to come up with a list of "allowed" non-ISO functions including the ones from POSIX in #57598 (`strnlen` is one of them).

I'd suggest just starting with what minimal libc includes and consider additions on a case-by-case basis...

**Comment by cfriedt** [comment]
Since this is a POSIX function, i would probably say the implementation should live in `lib/posix` as part of #51211.

**Comment by keith-packard** [comment]
> Since this is a POSIX function, i would probably say the implementation should live in `lib/posix` as part of #51211.
> 
> Of course, the prototype lives in `<string.h>` and conforming libc's probably have a conditional visibility macro

That's a fine question -- they're part of the POSIX C library specification, that's true, but they're also not OS dependent, and many (even non-POSIX) C libraries probably include them. So, they'll need to be conditionally compiled to not conflict with the libc version (which are likely more efficient).

**Pull request merged**
