### PR TITLE
Atmel sam gpio dts enhancements.

### PR DESCRIPTION
**Pull request by galak**
Cleanup Atmel gpio support to use DTS and have boards do that for LED & buttons

### CODE REVIEW

**Comment by galak** [comment]
@fallrisk any update on this?

**Comment by MaureenHelm** [comment]
This looks fine, except for the usage of GPIO_INT. @galak Do you want to wait for an agreement on #10339, or merge this now and fix it up later with everything else?

**Review by fallrisk — COMMENTED** [review]
The generated.h file looks odd with the repeated names:
GPIO_KEYS_GPIO_KEYS_BUTTON_1_GPIO_CONTROLLER
Are they supposed to say GPIO_KEYS twice? None of the other definitions are repetitive.

None of the samples seem to be updated, such as blinky, blink_led, drivers/gpio, button. I don't see how you want me to test it against one of the samples. I felt like I should be able to test it against one of the samples; or were you wanting me to write an application to test them? Should there be a dts.fixup in the board directory like there is in the SoC directories?

**Comment by galak** [comment]
> The generated.h file looks odd with the repeated names:
> GPIO_KEYS_GPIO_KEYS_BUTTON_1_GPIO_CONTROLLER
> Are they supposed to say GPIO_KEYS twice? None of the other definitions are repetitive.
> 

This should be fixed with some recent updates to the dts generation script.

> None of the samples seem to be updated, such as blinky, blink_led, drivers/gpio, button. I don't see how you want me to test it against one of the samples. I felt like I should be able to test it against one of the samples; or were you wanting me to write an application to test them? Should there be a dts.fixup in the board directory like there is in the SoC directories?

The samples don't need updating since we generate SW0_GPIO_* defines that they use for buttons or LED0_* defines for leds.

**Comment by galak** [comment]
@fallrisk you should be able to just build & run samples/basic/button & samples/basic/blinky on both boards and they should work.

**Comment by fallrisk** [comment]
I tried to build samples/basic/blinky for the sam_e70_xplained and I get the following errors:

error: ‘LED0_GPIO_PORT’ undeclared
error: ‘LED0_GPIO_PIN’ undeclared

**Comment by galak** [comment]
> I tried to build samples/basic/blinky for the sam_e70_xplained and I get the following errors:
> 
> error: ‘LED0_GPIO_PORT’ undeclared
> error: ‘LED0_GPIO_PIN’ undeclared

ok, let me try

**Comment by MaureenHelm** [comment]
> > This looks fine, except for the usage of GPIO_INT. @galak Do you want to wait for an agreement on #10339, or merge this now and fix it up later with everything else?
> 
> would like to merge it and deal with that later.

Works for me.

> fixed, the dts for sam_e70_xplained.dts had led0, sw0 in the wrong place (should be aliases, not compatibles).

Do you know why CI didn't catch it?

**Comment by galak** [comment]
> Do you know why CI didn't catch it?

Yeah, not sure on that one, let me look.  Looks like because the board.yaml doesn't list 'gpio'.

**Review by fallrisk — APPROVED** [review]
I tested samples/basic/blinky and samples/basic/button on the sam4s_xplained and the sam_e70_xplained. Both passed both tests.

**Pull request merged**
