### PR TITLE
drivers/flash/nrf_qspi_nor: Add support for nRF53 Series SoCs

### PR DESCRIPTION
**Pull request by anangl**
Improve the way the nrf_qspi_nor driver configures the SCK frequency,
to properly support QSPI also on nRF53 Series SoCs that use a different
base clock frequency (96 MHz).
Add also a relevant configuration in the spi_flash sample so that it
can run on the nRF5340 DK. This DK is equipped with the MX25R64
flash memory, so add a dts node for that chip in the board definition,
as well as the missing QSPI node in the nRF5340 SoC definition.

Relevant page in the nRF5340 (P)DK documentation can be found [here](https://infocenter.nordicsemi.com/topic/ug_nrf5340_pdk/UG/nrf5340_PDK/hw_external_memory.html).

### CODE REVIEW

**Review by pabigot — APPROVED** [review]
Seems to work.  It would be nice to add some of the other spi-nor samples, e.g. littlefs, but that could be done later.

**Comment by anangl** [comment]
There is still some issue with the SCK frequency (it turns out to be 4 times lower than expected). DNM until I sort it out.

**Comment by anangl** [comment]
Added required configuration of the HFCLK192M clock divider. The SCK frequency is correct now.

**Comment by ioannisg** [comment]
@anangl have you tried any relevant tests (if such exist) on nrf53?

**Comment by anangl** [comment]
> @anangl have you tried any relevant tests (if such exist) on nrf53?

I tried only the spi_flash sample for which a configuration is added in this PR. I can add a configuration also for the littlefs sample, as @pabigot suggested above.

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
> > @anangl have you tried any relevant tests (if such exist) on nrf53?
> 
> I tried only the spi_flash sample for which a configuration is added in this PR. I can add a configuration also for the littlefs sample, as @pabigot suggested above.

You or @pabigot  could do it in a separate PR, agreed.

**Pull request merged**
