### PR TITLE
Fixed build error for custom stm32g030xx boards

### PR DESCRIPTION
**Pull request by DanHigginbotham**
'RCC_PLLCFGR_PLLQ' & 'RCC_PLLCFGR_PLLQ_Pos' were undefined and needed to be 'RCC_PLLCFGR_PLLP' & 'RCC_PLLCFGR_PLLP_Pos'

### CODE REVIEW

**Comment by ycsin** [comment]
You will need to squash your commits, and comply with the Zephyr commit standard. The code that you removed is likely there for a reason, maybe you need to verify if it is only undefined for g030xx, and use preprocessor macro to compile conditionally?

**Comment by erwango** [comment]
> You will need to squash your commits, and comply with the Zephyr commit standard.

+1
See: https://static.sched.com/hosted_files/zephyr2022/a3/HOWTO_Get_Your_Zephyr_Patches_Merged_ZDS_2022.pdf

> The code that you removed is likely there for a reason, maybe you need to verify if it is only undefined for g030xx, and use preprocessor macro to compile conditionally?

Also please explain in which conditions you're seeing this issue (SHA1 used, target, ...).

**Comment by str4t0m** [comment]
The PLL-Q Divider is present on all STM32G0 SoCs but G030, G050, and G070. And also most other series.
Therefore please don't remove the code, but exclude this code only if PLL-Q is not available as ycsin already mentioned.
It should be fine to set the prescaler only when it is really used/configured in devicetree.
So instead of  `#if STM32_PLL_Q_DIVISOR` you could use `#if STM32_PLL_Q_ENABLED`.

**Comment by Higgy710** [comment]
If statement needs to be changed to STM32_PLL_Q_ENABLED
Closing request and opening a new one with corrections

**Pull request closed without merging**
