### PR TITLE
Bluetooth: tester: Disable support for HCI Vendor extensions in QEMU

### PR DESCRIPTION
**Pull request by MariuszSkamra**
Various types of dongles can be used with QEMU including those that
do not support Zephyr HCI Vendor extensions.

Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
I guess as start this should be fine, but something must be done if one wants to enable Zephyr VS commands with qemu, either as whitelist/blacklist as someone suggested or perhaps have btproxy intercepting this sort of commands at runtime.

**Review by jhedberg — CHANGES_REQUESTED** [review]
I discussed this matter offline with Carles, and I think it might be better if instead do some basic heuristics at runtime to try to guess whether the controller has a chance of handling the VS commands. A simple test for now would be that it is at least Bluetooth 5.0 and does not have a public address. Since we don't want this code to be there when you always build your host for a controller that supports the VS commands it'd be behind a new Kconfig variable.

**Comment by carlescufi** [comment]
@jhedberg @Vudentz agree that the heuristics are better than just disabling it. It's very useful to have those on QEMU when running Zephyr's Host against Zephyr controllers

**Comment by carlescufi** [comment]
@MariuszSkamra @Vudentz can we drop this PR and instead submit the heuristics one? I can take a look tomorrow if no one else has the time

**Pull request closed without merging**
