### PR TITLE
kernel: include: Fix warning when !CONFIG_SYS_CLOCK_EXISTS

### PR DESCRIPTION
**Pull request by carlocaione**
Small fix to mute an annoying warning.

### CODE REVIEW

**Comment by ulfalizer** [comment]
> ## Gitlint issues
> 6: UC4 Line exceeds max length (81>72): " warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]"

Speaking of annoying warnings... wonder if that one should be turned into an information message instead.

**Comment by carlocaione** [comment]
Yes please. My change is even shortening the line length.

**Review by carlescufi — APPROVED** [review]
LGTM, will let @andyross and @andrewboie take a look

**Comment by carlocaione** [comment]
ping

**Review by nashif — APPROVED** [review]

**Pull request merged**
