### PR TITLE
drivers: clock_control: Agilex5 clock control driver updates

### PR DESCRIPTION
**Pull request by gdengi**
The Agilex5 clock controller/manager IP registers are updated with the correct divider values by bootloader via hand-off
data, so now we can use the clock controller to get the clock value of each peripheral during run time.

As an example and test, remove hard-coded clock values from device tree nodes of UART and TIMER, and instead
read the clock values from the clock controller during run time.

### CODE REVIEW

**Comment by gdengi** [comment]
@nordic-krch @carlocaione Kindly review this PR and let me know your feedback. Thank you.

**Comment by gdengi** [comment]
Dear @nordic-krch, kindly review this PR whenever you are available and provide your feedback for the same. Thank you.

**Review by nordic-krch — APPROVED** [review]

**Comment by gdengi** [comment]
Dear @carlocaione, Kindly review this PR whenever you are available and provide your feedback for the same. Thank you.

**Comment by gdengi** [comment]
Dear @SgrrZhf @povergoing @carlocaione @npitre, kindly review this PR and let me know your comments. Thank you.

**Comment by gdengi** [comment]
Hello @carlocaione , @npitre , @povergoing , @SgrrZhf ,

Kindly review this PR and let me know your feedback. Thank you.

**Review by nashif — APPROVED** [review]

**Pull request merged**
