### PR TITLE
kernel: mem_slab: always validate memory address on free

### PR DESCRIPTION
**Pull request by xodus7**
Allowing an invalid address to be "freed" when asserts are disabled is dangerous and can lead to a very hard class of bugs (and potential security issues) to troubleshoot. This change always validates the address before adding it to the free list and adds a return code so clients can chose to check if the free succeeded. The assert is left in place so these issues can still be caught when asserts are enabled.

### CODE REVIEW

**Comment by xodus7** [comment]
I ran into this issue when upgrading my project to 3.7 from 3.4 (API change) where we ended up adding stack address to the free list which much later caused stack corruption and MPU fault. Enabling asserts is not possible due to code space limitations.. I believe it's better to fail here runtime potentially causing memory starvation than to allow bad addresses to be added to slab free list and all the tricky bugs and security issues that may come from that.

 I have not updated unit tests yet because I first want to gauge the appetite for such a change

**Review by andyross — COMMENTED** [review]
Not sure I see the value here?  Generally Zephyr philosophy has been to **not** engage in too much defensive coding and rely on assertions out of a concern for code size on constrained systems.  We can't test for every possible mistake, so we leave that stuff as a policy decision to higher levels.

And in this case the assert was already there and should have caught your error.

Not a strong -1 if someone feels we want to start being stricter about this stuff, though.  The test is cheap enough (though that modulus operation bugs me).

**Comment by npitre** [comment]
Following your logic, the same should be done to sys_heap_free() as 
well.

I don't think the return code is a good idea though. What can each 
caller do at run time to deal with the fact that your code is buggy? 
Having the free() code simply call k_panic() instead would be a better 
outcome. And then of course you should fix your code.

**Comment by xodus7** [comment]
> Not sure I see the value here? Generally Zephyr philosophy has been to **not** engage in too much defensive coding and rely on assertions out of a concern for code size on constrained systems. We can't test for every possible mistake, so we leave that stuff as a policy decision to higher levels.
> 
> And in this case the assert was already there and should have caught your error.

Enabling asserts expands the code size considerable so was not enabled in my case, this lead to very hard to track down stack corruption (even tracing this to offending function was not trivial easy). I'm also thinking about other conditions that are not exactly pure logic errors (thinking security). That said I'm not disagreeing with your points but do think this case is a candidate for the occasional exception.

**Comment by xodus7** [comment]
> Following your logic, the same should be done to sys_heap_free() as well. I don't think the return code is a good idea though. What can each caller do at run time to deal with the fact that your code is buggy? Having the free() code simply call k_panic() instead would be a better outcome. And then of course you should fix your code.

I could get behind k_panic as alternative to return code.

**Comment by andyross** [comment]
> Enabling asserts expands the code size considerable so was not enabled in my case,

It shouldn't be that bad.  The intent is that all development should always be done with asserts enabled, and that it should be lightweight enough to permit that on all platforms.  If this is really a hardship it's probably worth submitting a bug with numbers.  We might want to go on a diet; optimization is in the air at the moment.

**Comment by xodus7** [comment]
> It shouldn't be that bad. The intent is that all development should always be done with asserts enabled, and that it should be lightweight enough to permit that on all platforms. If this is really a hardship it's probably worth submitting a bug with numbers. We might want to go on a diet; optimization is in the air at the moment.

25KB on one of our builds, doesn't sound like a lot but in some cases where resources were extremely tight (and this was >5% of our total budget) it was enough to have to disable... Just to be clear, I believe this check is worth the small overhead regardless of the assert issue. It guards against issues that could stem from unexpected code paths or even triggered by external stimuli (security issues). It's better in those cases to fail intentionally rather than as some consequence later.

**Review by npitre — APPROVED** [review]
The modulus is a concern but typically this is a power of 2 or a relatively
small number that ought to resolve quickly.

**Comment by cfriedt** [comment]
Just adding my 2c - there is a whole class of bugs that should have an assertion at development time and otherwise a big at runtime, and I think it can be done in a pretty clean way.

Something like `BUG_ON()` in the Linux kernel would probably go a good distance in Zephyr too.

**Comment by xodus7** [comment]
> Something like `BUG_ON()` in the Linux kernel would probably go a good distance in Zephyr too. I think the end result is basically what @npitre suggested.

Something like this?

```
#if __ASSERT_ON
#define __BUG() __ASSERT_NO_MSG(false)
#define __BUG_ON(test) __ASSERT_NO_MSG(test)
#else
#define __BUG()                                     \
	do {                                        \
		k_panic();                          \
	} while (false)

#define __BUG_ON(test)                              \
	do {                                        \
		if (!(test)) {                      \
			k_panic();                  \
		}                                   \
	} while (false)
#endif
```

**Comment by cfriedt** [comment]
> > Something like `BUG_ON()` in the Linux kernel would probably go a good distance in Zephyr too. I think the end result is basically what @npitre suggested.
> 
> Something like this?

Just about. My thoughts were that a Kconfig option around `k_panic()` might be useful in so e cases. E.g. a remote device in the field could `printk()` or `LOG_WARN_ONCE()`.

**Comment by xodus7** [comment]
> Just about. My thoughts were that a Kconfig option around `k_panic()` might be useful in so e cases. E.g. a remote device in the field could `printk()` or `LOG_WARN_ONCE()`.

I put together a prototype/proposal: https://github.com/zephyrproject-rtos/zephyr/pull/80459

**Review by peter-mitsis — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
