### PR TITLE
[backport v2.7-branch] drivers: clock_control: More power supply modes for STM32H7

### LINKED ISSUE #41089: [backport v2.7-branch] backport of #40862 (power modes for STM32H7)
Some boards on STM32H7 uses SMPS with different power supply configurations. So Zephyr 2.7 can't start without property power supply and clock init sequence. PR #40862 add support for all possible power supply configurations.

I suggest to backport #40862 to zephyr 2.7, so more boards can start.

### PR DESCRIPTION
**Pull request by belolap**
Backport of  #40862. 

Fixes #41089.

### CODE REVIEW

**Comment by erwango** [comment]
Thanks @belolap.
Though, for clarity, I think we should first merge https://github.com/zephyrproject-rtos/zephyr/pull/41267.
Then push current one on top.
I agree that's the same at the end, but it might be better to keep same commits than what we had on main.
Since LTS is supposed to last for 2 years, if someone in one or two years does some archaeology in that part,
that one might be happy to find equivalent stuff in both branches.
So, as long as intermediate commits are not fully wrong, I'd prefer we keep them.

**Comment by belolap** [comment]
No problem. We can keep it open and I'll rebase commit after if it will be needed.

**Comment by cfriedt** [comment]
@belolap - can you please rebase and fix merge conflicts?

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@belolap , would you min rebasing since #41267 was merged ?

**Comment by belolap** [comment]
Hi @cfriedt, @erwango! Give me several hours.

**Comment by belolap** [comment]
@cfriedt done!

**Pull request merged**
