### PR TITLE
Do not call various sockets calls via ioctl handler

### LINKED ISSUE #27480: remove use of ioctl() within the network stack
**Is your enhancement proposal related to a problem? Please describe.**
There is an ioctl-like interface used within the networking code. I say ioctl-like but it really isn't ioctl because these functions are truly variadic instead of 2 or 3 args with the third optional arg a void pointer.

Ioctls are bad. This thread concisely explains from Linus Torvalds himself what the problems are: https://yarchive.net/comp/linux/ioctl.html

Right now, the way ioctl is used internally by networking all it does is defeat type safety. There are no advatages. We can of course keep vtable-like abstractions in the kernel, but these APIs need to have proper prototypes, see the Zephyr driver model as an example.

**Describe the solution you'd like**
Any use if ioctl() removed from the kernel with the exception of what's minimally needed for POSIX compatibility, and such code MUST be limited to lib/posix and nowhere wlse.

### PR DESCRIPTION
**Pull request by jukkar**
* Do not route close() calls via ioctl() as that is error prone and quite pointless. Instead create a callback for close() in fdtable and use it directly.
* Also remove getsockname() from ioctl() and provide a pointer to it in vtable

This has partial fix to #27480

### CODE REVIEW

**Comment by jukkar** [comment]
Lets start with smaller steps and remove first the `close()` call from `ioctl()` as this is the easiest change.

**Comment by andrewboie** [comment]
This is a good change but doesn't completely fix #27480. vtable->ioctl needs to be completely removed before that's done. Please amend the PR description to remove "Fixes" as that will result in it being auto-closed when this is merged.

**Comment by jukkar** [comment]
* Removed the "Fixes" line as this is not yet fixing the issue fully
* Separated `getsockname()` from ioctl call

**Comment by pfalcon** [comment]
> Do not route close() calls via ioctl() as that is error prone and quite pointless.

It's not pointless, it saves code memory (both for extra vmethod pointer, and for handler function prolog/epilog, which, multiplied over several implementations, leads to noticeable overhead). This is similar to any other code I've written for Zephyr, which was originally presented as "RTOS which can run in 16K". Obviously, when I write code for Linux, I do it differently, but then it can't run in 16K.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Looks good.

**Pull request merged**
