### PR TITLE
[RFC] SPI: Add API support for DDR, Dual, Quad and Octal modes

### PR DESCRIPTION
**Pull request by tbursztyka**
SPI enhanced modes
=================

DDR: Double Data Rate
Dual: Dual MOSI lines
Quad: Quad MOSI lines
Octal: Octal MOSI lines
DQO: Dual Quand Octal

These modes comprise: DDR, Dual, Quad, Octal and the
specific command/address/data format

Uses cases
---------------

- single MOSI line: cmd / addr / data ddr
- single MOSI line: cmd / addr ddr / data ddr
- single MOSI line: cmd ddr / addr ddr / data ddr
- single MOSI line: cmd ddr
- single MOSI line: data ddr
- DQO MOSI lines: cmd single/addr single/data
- DQO MOSI lines: cmd single/addr/data
- DQO MOSI lines: cmd/addr/data
- DQO MOSI lines: cmd
- DQO MOSI lines: data
- DBO uses cases with DDR

Design
---------

Besides the operation attribute of struct spi_config, all goes through
a newly added u16_t attribute in struct spi_buf: flags.

Firts 9 bits are containing config flags, next 2 bits are the command
length (set to 0 if the cmd/addr format is not in use) and the last 5 bits
are the address length (set to 0 if the addr is not present or if the cmd/addr
format is not in use). Command length is a multiple of 4 (4, 8, 12, 16, ...)
and address length is a multiple of 2 factor 4 (4, 8, 16 ...)

**The good side of this approach:** it does not require changes on any existing SPI controller
drivers nor SPI device drivers.

**The drawback:** if only one SPI controller can support these modes, it adds up
16bits to each and every struct spi_buf in the system. Hopefully this is still
a relatively small amount of data (looks like uncommon for a driver to use more
than 2 struct spi_buf, and if does it will usually be due to a lack of factorization).

SPI configuration
----------------------

```
spi_config {
	   ...
	   .operation = SPI_LINES_<SINGLE/DUAL/QUAD/OCTAL>
	   ...
}
```

Basic cmd/addr format transaction usage
----------------------------------------------------

Note: 8bits length cmd/addr are used for these examples, but it's trivial to
use other size.

**TX only:**

```
u8_t tx_buf[] = { CMD, ADDR };

struct spi_buf buf[2] =  {
	{
		.buf = tx_buf,
       		.len = 2,
		.flags = SPI_EM_CMD_<mode> | SPI_EM_ADDR_<mode> |
       	      	       SPI_EM_CMD_LENGTH_SET(SPI_EM_CMD_LEN_8_BITS) |
		       SPI_EM_ADR_LENGTH_SET(SPI_EM_ADR_LEN_8_BITS)
	},
	{
		.buf = data,
 		.len = data_length
	}
};

struct spi_buf_set tx {
       .buffers = buf,
       .count = 2
};

spi_transceive(spi_dev, spi_cfg, &tx, NULL)
```

**RX added**

```
u8_t tx_buf[] = { CMD, ADDR };

struct spi_buf buf_tx[1] =  {
	{
		.buf = tx_buf,
       		.len = 2,
		.flags = SPI_EM_CMD_<mode> | SPI_EM_ADDR_<mode> |
       	      	       SPI_EM_CMD_LENGTH_SET(SPI_EM_CMD_LEN_8_BITS) |
		       SPI_EM_ADR_LENGTH_SET(SPI_EM_ADR_LEN_8_BITS)
	}
};

struct spi_buf_set tx {
       .buffers = buf_tx,
       .count = 1
};

struct spi_buf buf_rx[1] =  {
	{
		.buf = data,
 		.len = data_length
	}
};

struct spi_buf_set rx {
       .buffers = buf_rx,
       .count = 1
};

spi_transceive(spi_dev, spi_cfg, &tx, &rx)
```

**In case no address is given**

```
u8_t tx_buf[] = { CMD };

struct spi_buf buf_tx[1] =  {
	{
		.buf = tx_buf,
       		.len = 2,
		.flags = SPI_EM_CMD_<mode> | SPI_EM_ADDR_<mode> |
       	      	       SPI_EM_CMD_LENGTH_SET(SPI_EM_CMD_LEN_8_BITS) |
		       SPI_EM_ADR_LENGTH_SET(SPI_EM_ADR_NONE)
	}
};
```

etc ...

About JEDEC
------------------

spi_nor.c could be improved in order to be able to use DQO modes if configured
as well as enabling hardware optimizations.

Configuring is trivial, as seen above, and does not need any particular explanation.
It would be just Kconfig/DTS based.

Enabling hardware optimizations would be done by adding SPI_EM_FLASH_JEDEC flag to
the buf's flags attribute. If the controller has no optimizations, it will silently
ignore it and make the transaction as usual.
If it does, here is what will be possible to do in the controller driver on a write
order for instance where the controller can handle WREN by itself:
(here it's assumed the controller can do generic spi transaction as well as
 providing optimizations for flash)

spi_nor: generate a WREN transaction
ctlr   : look at first spi buf flags. If flash/jedec, it will take a look at the
       	 content of the spi buf and if it's WREN. do nothing.
spi_nor: generate a PP transaction
ctlr   : look at first spi buf flags. If flash/jedec, it will take a look at the
       	 content of the spi buf and if it's PP: setup the address found in the buf
	 generate an internal PP instruction etc...

The idea is basically looking at the preliminary buffer of the transaction where
the driver could grab the necessary info in order to use hw optimizations.
Or to summarize:
- non hw jedec optimized SPI controller:
      would feed the buffer(s) directly to the wires
- hw jewed optimized SPI controller:
      would interpret the first buffer and feed any subsequent buffer as data to
      the wires

**Good side of this approach**: It can reuse spi_nor already, no need for a new API and its related drivers (and thus to need of 2 drivers in case a generic SPI controller also provides jedec hw optimizations)

**Drawback of this approach**: might add a really tiny bit of overhead (which can be neglected imo)  for jedec hw optimized drivers compared to a dedicated API/drivers.

### CODE REVIEW

**Comment by tbursztyka** [comment]
@fabled  @psidhu

**Review by pabigot — COMMENTED** [review]
The API changes look comprehensive and reasonable, though we're missing the devicetree extensions necessary to identify the signals and describe the access protocol for the subordinate devices.  Also we can't really validate the API until we see how it's going to be implemented and used.

I believe the extensions may be suitable for implementation on some of the dual/quad/octo SPI peripherals provided by various vendors.  I don't believe Nordic QSPI could use it for anything that isn't a JEDEC device.  IMO multiple vendors should confirm a desire and intent to implement the extended API before it's added.

Also, discussion in #17902 failed to identify any non-4-wire SPI-ish device of interest that isn't a serial memory, either JEDEC SPI or Hyperbus.  The only Zephyr APIs for serial memory I can see are flash area/map ones, which provide synchronous read/write/erase address/size operations.

The settings and file system APIs available at user/library level all use the flash API underneath, and are inherently synchronous.

So for the purpose of supporting serial memory extending the basic Zephyr SPI API means new flash drivers will have to be written using it to provide access to JEDEC and Hyperbus memory devices (*maybe* it could be pasted into the existing JEDEC one).  That could be done, but is likely to be more complex than simply implementing the existing flash API on top of the peripheral directly.

So: ok from a technical perspective, but an overriding "why are we doing this" from a project perspective.

**Comment by tbursztyka** [comment]
> we're missing the devicetree extensions necessary to identify the signals and describe the access protocol for the subordinate devices.

That will need another PR, since many SPI device configuration bits and pieces need to be made available through dts and not only these newly added ones.

>  I don't believe Nordic QSPI could use it for anything that isn't a JEDEC device.

According to the datasheet, it seems to support custom commands. See  https://infocenter.nordicsemi.com/topic/ps_nrf52840/qspi.html?cp=3_0_0_5_18#register.CINSTRCONF 
Using such capability would only require to avoid the flag SPI_EM_FLASH_JEDEC (as long as the first buffer still describes a cmd/addr format obviously).

> Also, discussion in #17902 failed to identify any non-4-wire SPI-ish device of interest that isn't a serial memory, either JEDEC SPI or Hyperbus. 

You missed the relevant post there then. See https://github.com/zephyrproject-rtos/zephyr/issues/17902#issuecomment-546853434

There are devices outside using dual/quad/octal mosi lines which are not flash memories.

> new flash drivers will have to be written using it to provide access to JEDEC and Hyperbus memory devices (maybe it could be pasted into the existing JEDEC one).

From what I saw, I think this can be fully solved via improving spi_nor.c using the proposed API here. No need of new drivers so far.

**Comment by pabigot** [comment]
> > we're missing the devicetree extensions necessary to identify the signals and describe the access protocol for the subordinate devices.
> 
> That will need another PR, since many SPI device configuration bits and pieces need to be made available through dts and not only these newly added ones.

Yes, updating the SPI infrastructure for devicetree is important.  Particularly the `spi-cpol` and `spi-cpha` properties.  It would be good to see progress on that.

> You missed the relevant post there then. See [#17902 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/17902#issuecomment-546853434)
> 
> There are devices outside using dual/quad/octal mosi lines which are not flash memories.

I believe you missed that the described CEC1702 acts as a bus controller, not a device on the bus.  I have yet to see a datasheet for a SPI subordinate ("slave") device that uses dual/quad/octal data lines and isn't essentially a memory.  If you can identify one, please, point to it.

For the rest: I see your argument, I simply don't find it compelling.

I have no intention of blocking what you propose, but I do wish that Zephyr enhancements followed a process that took into account more than the first step towards an underdefined goal.

**Comment by tbursztyka** [comment]
>  If you can identify one, please, point to it.

oh yes wrong comment, just the above the one I linked, about some DAC/ADC that can be interfaced via quad spi.

**Comment by pabigot** [comment]
> oh yes wrong comment, just the above the one I linked, about some DAC/ADC that can be interfaced via quad spi.

See https://github.com/zephyrproject-rtos/zephyr/issues/17902#issuecomment-546919805.  I couldn't find any.  (I don't believe they don't exist, but like a unicorn, I haven't seen one myself.)

**Comment by tbursztyka** [comment]
@pabigot some do talk about supporting QSPI (which sounds weird for a DAC) but I could not find the programming details.

**Comment by kamlaz** [comment]
@tbursztyka 
Clear and good looking API. 
Unfortunately I have some doubts :

1. Does address and command fields has to be checked at every transmission?

```
struct spi_buf buf[2] =  {
	{
		.buf = tx_buf,
       		.len = 2,
		.flags = SPI_EM_CMD_<mode> | SPI_EM_ADDR_<mode> |
       	      	       SPI_EM_CMD_LENGTH_SET(SPI_EM_CMD_LEN_8_BITS) |
		       SPI_EM_ADR_LENGTH_SET(SPI_EM_ADR_LEN_8_BITS)
	},
```
I am afraid that it might (as you mentioned) add overhead that could be not acceptable using features that require high performance (like XIP). The same problem will occur when you need to transfer huge files - it is just waste of time to check flags every transmission.

2.  How are you going to read BUSY flag from JEDEC device? Using transceive?
3.  Imo using "transceive" function in context of JEDEC devices is not clear. Memory devices usually operate in PP or READ instructions instead of transceive. 

>According to the datasheet, it seems to support custom commands. See https://infocenter.nordicsemi.com/topic/ps_nrf52840/qspi.html?cp=3_0_0_5_18#register.CINSTRCONF
Using such capability would only require to avoid the flag SPI_EM_FLASH_JEDEC (as long as the first buffer still describes a cmd/addr format obviously).

In fact Nordic QSPI peripherial is available to send custom commands, but with some limitations:
- command has limited length (up to nine bytes)
- filling input buffer with custom command is not convenient, since you have to split your buffer into two pieces - write first byte of your buffer as `op_code` and the rest of the buffer to the tx_buf

4.  How are you going to solve problem of talking with few flash memories using one peripheral? There should be a way to configure driver to communicate with desired memory device using individual CS pin. Important is fact that driver should support hardware handling of this pin. In any other case performing any high throughput data communication will not be effective.

**Comment by pabigot** [comment]
> @pabigot some do talk about supporting QSPI (which sounds weird for a DAC) but I could not find the programming details.

Datasheet link or it didn't happen....  (Look at the functional diagram to confirm there are SPI signals other than MISO/MOSI/SCK/CSn; that's where the ones I looked at failed.)

**Comment by mtahirbutt** [comment]
Hi, I am trying to make work quadflash with disco_l475_iot1, I am investigating quadspi in this regard. I just found update on spi.h file for incorporating SPI_LINES_QUAD, but do not know how to configure pins for CS as stm32l475 MCU has multiple pins supporting CS for QUADSPI and additionally how can I configure that with DTS file etc. Because normally the control signals(CS,spi_max_frequency, Clock Phase) can be configured in the DTS file, but I do not find these kind of information with Quad SPI. please comment, thanks a lot in advance.

**Comment by tbursztyka** [comment]
@mtahirbutt you don't need this extension to make it work, ST comes with its HAL so it should expose what you need to make a flash driver. Unless you still need native SPI API... let us know. See existing flash driver (and qspi ones like drivers/flash/nrf_qspi_nor.c ) for more info.

**Pull request closed without merging**
