### PR TITLE
sample: drivers: enc28j60: Ethernet controller sample app

### PR DESCRIPTION
**Pull request by jukkar**
Example how to use enc28j60 Ethernet controller.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

As agreed in API meeting, here is a sample for enc28j60 Ethernet controller. This initial version is using black_f407ve board as that was the only one that I had setup to use enc28j60. Other boards can be added by placing proper config files to board directory and adding whitelisting entries to sample.yaml file.

### CODE REVIEW

**Comment by jukkar** [comment]
ping @nashif @carlescufi

**Review by galak — CHANGES_REQUESTED** [review]
Based on API meeting today, rather than introducing a specific sample for enc28j60, can we decide which networking sample/test might make sense for ethernet?  ./samples/net/sockets/echo_client/server?

**Comment by jukkar** [comment]
> Based on API meeting today, rather than introducing a specific sample for enc28j60, can we decide which networking sample/test might make sense for ethernet? ./samples/net/sockets/echo_client/server?

That is problematic as the overlay is board specific so you would have multiple overlays for enc28j60 in each sample. Also we cannot pick that said overlay automatically as there is no board that has controller by default.

**Comment by galak** [comment]
> That is problematic as the overlay is board specific so you would have multiple overlays for enc28j60 in each sample. Also we cannot pick that said overlay automatically as there is no board that has controller by default.

Not sure I follow the comment about `multiple overlays for each sample`

We've have cases in all over the place for sensors or such that don't exist directly on a board but has a board overlay that shows how it can exist on a board (even if that requires being wired up).

**Comment by jfischer-phytec-iot** [comment]
@jukkar I think it would be easier to add generic _arduino_ shield support for the ENC28J60 controller,  like we have it for few display controller.

**Comment by jukkar** [comment]
> I think it would be easier to add generic _arduino_ shield support for the ENC28J60 controller, like we have it for few display controller.

Ok, makes sense. Lets close this one.

**Pull request closed without merging**
