### PR TITLE
MXRT600: Update defconfig SYS_CLOCK value

### PR DESCRIPTION
**Pull request by mmahadevan108**
The clock has been lowered temporarily to 48MHz

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @MaureenHelm

**Comment by mmahadevan108** [comment]
cc @agansari @dleach02

**Comment by galak** [comment]
Why?

**Comment by mmahadevan108** [comment]
> Why?

The power API for this platform is available in binary form which cannot be included inside Zephyr. This platform is running at the slower default speed till we have a way to call the power API's to raise the core voltages.

**Comment by galak** [comment]
> > 
> 
> The power API for this platform is available in binary form which cannot be included inside Zephyr. This platform is running at the slower default speed till we have a way to call the power API's to raise the core voltages.

Would be good to add something like this to the commit message to explain why the frequency was changed.

**Comment by mmahadevan108** [comment]
> > > 
> > 
> > 
> > The power API for this platform is available in binary form which cannot be included inside Zephyr. This platform is running at the slower default speed till we have a way to call the power API's to raise the core voltages.
> 
> Would be good to add something like this to the commit message to explain why the frequency was changed.

Thank you, I have updated the commit message to include more information

**Review by MaureenHelm — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
