### PR TITLE
dts: nordic: nrf9160: Remove redundant aliases

### PR DESCRIPTION
**Pull request by anangl**
Several aliases were added to nrf9160[ns].dtsi files solely for
the purpose of getting base addresses of certain hardware modules
via DT_ macros generated for these aliases.
Since for one-instance modules the same can be now achieved with
standard DT_INST_0_* macros, there is no need to keep these aliases.

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
@anangl will you send similar PRs for nRF51,52 SOCs? Or this is not required?

**Comment by anangl** [comment]
Forgot about nrf9160ns.dtsi. Found one more such alias.

**Comment by anangl** [comment]
@ioannisg
> @anangl will you send similar PRs for nRF51,52 SOCs? Or this is not required?

I haven't found such aliases for nRF51/52 SoCs. The ones we've got for them we still need, for drivers.
I'm wondering about [this one](https://github.com/zephyrproject-rtos/zephyr/blob/a56695db9a123ef70a3a9f31db421777b53fb396/dts/arm/nordic/nrf9160.dtsi#L32). It seems to be used only [in dts_fixup.h](https://github.com/zephyrproject-rtos/zephyr/blob/a56695db9a123ef70a3a9f31db421777b53fb396/soc/arm/nordic_nrf/nrf91/dts_fixup.h#L21). Probably it can be replaced with DT_INST_0, too.

**Review by ioannisg — APPROVED** [review]

**Review by ulfalizer — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by ioannisg — COMMENTED** [review]
@anangl is there a reason not to remove the Watchdog, as well?

**Comment by anangl** [comment]
> @anangl is there a reason not to remove the Watchdog, as well?

Yes, macros generated for this alias are [used also by our watchdog driver](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/watchdog/wdt_nrfx.c#L165). And I don't want to touch it now. Same story is with aliases for `adc` or `qdec`, for example. Besides, currently we have only single instances of these peripherals but this may change in some future.

**Pull request merged**
