### PR TITLE
Convert NXP Kinetis Pinmux to get info from devicetree (for device objects, not pins)

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
This is based on how the rv32m1 pinmux driver & board code works.

**Review by nandojve — APPROVED** [review]
TAGOIO example.

**Review by pabigot — APPROVED** [review]
Seems good.

I was unaware of `__unused`.  Maybe we should use that to eliminate one of the motivations for #30761.

**Review by MaureenHelm — APPROVED** [review]
Thanks @galak

**Review by henrikbrixandersen — APPROVED** [review]
Thanks!

**Pull request merged**
