### PR TITLE
drivers: can: Add SocketCAN support to mcux flexcan driver

### PR DESCRIPTION
**Pull request by MaureenHelm**
Used the SocketCAN initalization code from the can_stm32.c driver which
successfully initializes SocketCAN for the Flexcan driver

Signed-off-by: Peter van der Perk <peter.vanderperk@nxp.com>

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Looks good. However, is there a reason for only adding it for FlexCAN instance 0? Can we add the same for FlexCAN instance 1?

**Comment by PetervdPerk-NXP** [comment]
Hi @henrikbrixandersen, I'm the author this commit. The reason why I only added SocketCAN support for FlexCAN instance 0 has multiple reasons. First I'm only in the possession a FRDM-K64F board which only has 1 CAN bus therefore I would be unable to test it. Furthermore  [socket_can_generic.h](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/can/socket_can_generic.h) only provides a single socket_can_context therefore I'm not even sure if the zephyr socketCAN implementation supports multiple CAN controllers.

**Comment by henrikbrixandersen** [comment]
> Hi @henrikbrixandersen, I'm the author this commit. The reason why I only added SocketCAN support for FlexCAN instance 0 has multiple reasons. First I'm only in the possession a FRDM-K64F board which only has 1 CAN bus therefore I would be unable to test it. Furthermore [socket_can_generic.h](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/can/socket_can_generic.h) only provides a single socket_can_context therefore I'm not even sure if the zephyr socketCAN implementation supports multiple CAN controllers.

@PetervdPerk-NXP Okay. Even though our SocketCAN layer only supports one context there might be boards using CAN1 and not CAN0. Perhaps we could allow for the SocketCAN context on either CAN0 or CAN1?

@alexanderwachter Any input on how to support multiple CAN devices under Zephyr SocketCAN?

**Comment by alexanderwachter** [comment]
@henrikbrixandersen no Idea how to support multiple CAN on socketCAN. @jukkar do you know how to handle this?

I general, we should move the socketCAN stuff from the driver to a common file. Like I did it for 6LoCAN (can_net.c).

**Comment by jukkar** [comment]
> @jukkar do you know how to handle this?

Currently the `drivers/can/socket_can_generic.h` contains `socket_can_context_1` static variable for one CAN bus. That would need to be changed so that the driver itself would allocate and manage it, so basically moving that variable out of that file. The functions in that file are generic so they can be used by all CAN drivers. We could of course create .c file etc for these, so basically making a proper library out of it.

**Comment by alexanderwachter** [comment]
@henrikbrixandersen @jukkar with the generic solution where we have a can_socket.c file, we could use the DT_CAN_PRIMARY label to define the primary interface, and depending on whether a DT_CAN_SECONDARY label exists, we can add more interfaces. Which interface to use is then up to the sockets API.

**Comment by jukkar** [comment]
@alexanderwachter @henrikbrixandersen Please remember that for each CAN socket "interface", the driver needs to have a call to `NET_DEVICE_INIT()` with proper context params. That macro will cause a network interface to be created which is the input/output point towards network stack.

**Comment by alexanderwachter** [comment]
> Please remember that for each CAN socket "interface", the driver needs to have a call to `NET_DEVICE_INIT()` with proper context params. That macro will cause a network interface to be created which is the input/output point towards network stack.

That's the plan! We can also remove the thread because `net_pkt_rx_alloc_with_buffer` can be called from an ISR when using K_NOWAIT. Or we can use the "new" can_attach_workq and use the system work-queue to process incoming packets.

**Comment by henrikbrixandersen** [comment]
> 
> 
> @henrikbrixandersen @jukkar with the generic solution where we have a can_socket.c file, we could use the DT_CAN_PRIMARY label to define the primary interface, and depending on whether a DT_CAN_SECONDARY label exists, we can add more interfaces. Which interface to use is then up to the sockets API.

Sounds good. I suggest we open another Issue/PR for dealing with this and accept this PR as-is.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by alexanderwachter — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
