### PR TITLE
include: arch: riscv: rename global macro

### PR DESCRIPTION
**Pull request by karstenkoenig**
SR and LR were used as global names for load and store RISC-V assembler
operations, colliding with other uses such as SR for STATUS REGISTER in
some peripherals. Renamed them to a longer more specific name to avoid
the collision.

Signed-off-by: Karsten Koenig <karsten.koenig.030@gmail.com>

### CODE REVIEW

**Comment by karstenkoenig** [comment]
Tested this on a vega board, so only for RV32. There it also clashed with the status register of the LPSPI peripheral :-) 

Ping @npitre 
You've introduced the macros to use different operations based on either RV32 or RV64. I think I caught all of them based on your commit here
https://github.com/zephyrproject-rtos/zephyr/commit/0440a815a91b83bdb27e272b9770f558c1b8975c

**Comment by npitre** [comment]
This is fine with me.

**Review by nategraff-sifive — APPROVED** [review]
LGTM

**Comment by ioannisg** [comment]
@karstenkoenig @nategraff-sifive is this considered a bug-fix or enhancement? I.e. do we require this in 2.0?

**Review by nashif — APPROVED** [review]

**Comment by karstenkoenig** [comment]
I'd say it's a bugfix, SR is present on NXP/Freescale peripherals (RTC, LSSPI, MU) so there is a collision on the RV32M1 SoC. They aren't used yet on that SoC afaik, but if somebody were to use 2.0 as a starting point for it, it'd be annoying.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by ioannisg** [comment]
> 
> 
> @karstenkoenig @nategraff-sifive is this considered a bug-fix or enhancement? I.e. do we require this in 2.0?
Thanks @karstenkoenig 

@nategraff-sifive @nashif just give a green light if this is required for 2.0.0

**Comment by nategraff-sifive** [comment]
I think this should go in 2.0.0.

**Comment by ioannisg** [comment]
@karstenkoenig could you rebase this one to latest master?

**Comment by karstenkoenig** [comment]
@ioannisg done, rebased onto current master and verified hello-world is still working on the openvega board

**Pull request merged**
