### PR TITLE
tests: devicetree: fix gpio intc `interrupt-cells` and add IRQN test

### PR DESCRIPTION
**Pull request by ycsin**
can probably be backported to 3.6?

### CODE REVIEW

**Comment by ycsin** [comment]
cc @LaurentiuM1234

**Review by bjarki-andreasen — CHANGES_REQUESTED** [review]
The use of pin and flags as the interrupt-cells is intentional :) The binding `vnd,gpio-intc-device` is a gpio controller which also acts a an interrupt controller, hence why it has pin number and flags, instead of IRQ number and prioriy, which both don't make sense for a GPIO controller :)

This test is specifically designed to ensure this is possible to match the devicetree specification.

I will suggest you create a new test specifically for multilevel interrupts, using the existing `test_intc` node which is a generic interrupt controller, which is a child of `test_cpu_intc`

**Comment by ycsin** [comment]
Oops, I thought that was simply a copy pasta typo

> I will suggest you create a new test specifically for multilevel interrupts, using the existing test_intc node which is a generic interrupt controller, which is a child of test_cpu_intc

Sure, this should work as well

> The binding `vnd,gpio-intc-device` is a gpio controller which also acts a an interrupt controller, hence why it has pin number and flags, instead of IRQ number and prioriy, which both don't make sense for a GPIO controller :)

This seems to prioritize its gpio-controller properties over its interrupt-controller properties, does that mean that we have to take extra care to differentiate between a typical/real interrupt node (by checking if it has the `irq` prop) versus a gpio/interrupt-node that's 'acting' as an interrupt controller that are listed in the `interrupts-extended` node?

```c
/* devicetree_generated.h */
/* west build -b qemu_x86 -p auto -t run tests/lib/devicetree/api */
...
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_NUM 2
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_0_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_0_VAL_irq 70
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_0_VAL_irq_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_0_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_0_VAL_priority 7
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_0_VAL_priority_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_0_CONTROLLER DT_N_S_test_S_interrupt_controller_bbbbcccc
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_1_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_1_VAL_pin 30
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_1_VAL_pin_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_1_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_1_VAL_flags 3
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_1_VAL_flags_EXISTS 1
#define DT_N_S_test_S_interrupt_holder_extended_IRQ_IDX_1_CONTROLLER DT_N_S_test_S_gpio_1234abcd
```

Would it be more intuitive if we differentiate between an interrupt controller vs a gpio controller? What's the benefit of mixing the two?

**Comment by bjarki-trackunit** [comment]
@ycsin Mixing the two is essential as this allows us to use the same APIs and macros for any type of interrupt controller. This is the primary goal of the new IRQ subsystem I have been sharing :)

I do see that we use irq as a generic property for interrupt line number, and I am okay renaming pin to irq, as the pin number and interrupt line should be identical anyway :)

**Pull request closed without merging**
