### PR TITLE
hwinfo: Rename MCUX syscon driver to RT6xx

### PR DESCRIPTION
**Pull request by galak**
The NXP MCUX syscon driver is really specific to RT6xx SoCs and thus
should be renamed.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
LPC devices provide a 128-bit UUID. The location of this can vary, suggest renaming to` hwinfo_mcux_lpc` or `hwinfo_lpc`

**Comment by galak** [comment]
> LPC devices provide a 128-bit UUID. The location of this can vary, suggest renaming to` hwinfo_mcux_lpc` or `hwinfo_lpc`

I glanced at the LPC54114 and LPC55S69 manuals and didn't see UUID registers.  On 55S69 seems like its via a flash rom API, and not a register read.

So what other devices have UUID registers?

**Comment by mmahadevan108** [comment]
> > LPC devices provide a 128-bit UUID. The location of this can vary, suggest renaming to` hwinfo_mcux_lpc` or `hwinfo_lpc`
> 
> I glanced at the LPC54114 and LPC55S69 manuals and didn't see UUID registers. On 55S69 seems like its via a flash rom API, and not a register read.
> 
> So what other devices have UUID registers?

In LPC55S69, its available in Protected Flash Space. It is documented in 49.8 section of the RM

**Comment by galak** [comment]
> In LPC55S69, its available in Protected Flash Space. It is documented in 49.8 section of the RM

(What version of the RM are you looking at?)

And on LPC54114?

**Comment by mmahadevan108** [comment]
> > In LPC55S69, its available in Protected Flash Space. It is documented in 49.8 section of the RM
> 
> (What version of the RM are you looking at?)
> 
> And on LPC54114?

I was looking at an older version, section 48.8 in the latest User Manual for LPC55S6X and LPC55S2X. I do not see a Unique ID available on LPC54114. I have tested on LPC55S6X board.

**Comment by galak** [comment]
Closing this in favor of #36522 36522

**Pull request closed without merging**
