### PR TITLE
doc: add 'Open on GitHub' links

### PR DESCRIPTION
**Pull request by gmarull**
This PR adds a new extension that allows to add 'Open on GitHub' links on all documentation pages that have a corresponding rst file in the Zephyr repository. The extension has multiple configuration options, such as documents to be excluded (e.g. auto-generated pages) or VCS prefixes since Zephyr has docs in multiple locations.

The idea behind this extension is to provide easy access to the document sources on GitHub.

**How does it look like?**

image

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
What will the edit button do when clicked? Prompt you to fork the project, create a branch, etc.? I mean, will the existing workflow for getting changes accepted into the tree be encouraged when clicking this button?

**Comment by mbolivar-nordic** [comment]
> What will the edit button do when clicked? Prompt you to fork the project, create a branch, etc.? I mean, will the existing workflow for getting changes accepted into the tree be encouraged when clicking this button?

I didn't build it, but it looks like it just takes you to the github https://github.com/zephyrproject-rtos/zephyr/blob/... page.

E.g. for https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/index.rst, I see a pencil icon that takes me to an edit page like this:

https://github.com/zephyrproject-rtos/zephyr/edit/main/doc/index.rst

I followed instructions to create a pull request, but I do not like the results:

https://github.com/zephyrproject-rtos/zephyr/pull/36604

This created a branch within the zephyrproject organization, not my own fork.

So I'm -1 on this, as we don't want to encourage that; do we?

**Review by nashif — CHANGES_REQUESTED** [review]
same concern as @mbolivar-nordic, not sure what is the value otherwise.

**Comment by gmarull** [comment]
@mbolivar-nordic @nashif maybe we have some GitHub settings that have to be adjusted? Projects like Godot do the right thing when clicking on GitHub edit button:

image

**Comment by mbolivar-nordic** [comment]
From your screenshot: "You're making changes in a project you don't have write access to. We've created a fork [...]".

I do have write access to zephyr (which means I can create branches, not that I can merge to the main branch), so that probably explains it. @gmarull you could confirm that by clicking on the button when logged in to an unprivileged GH account.

I'm still not sure about this one even if that is the reason. There are a lot of people with write access, and oddly we can create branches, but not delete them. So if we merge this, it will probably increase the number of branches in the zephyr project repo, which the admins with 'delete branch' privileges will have to keep cleaning up.

**Comment by nashif** [comment]
The should not have contributions come in via the web UI, we had issues with this in the past, someone with enough permissions might even merge the change directly without signed-off and without going through the review, this happened before. The only way to change docs I would say should be by changing the files directly and submitting PRs like you do when you change code.

**Comment by gmarull** [comment]
Would `Open on GitHub` text be better? I think it still has value: brings the user to GitHub and you can also see the page source.

**Comment by gmarull** [comment]
> From your screenshot: "You're making changes in a project you don't have write access to. We've created a fork [...]".
> 
> I do have write access to zephyr (which means I can create branches, not that I can merge to the main branch), so that probably explains it. @gmarull you could confirm that by clicking on the button when logged in to an unprivileged GH account.
> 
> I'm still not sure about this one even if that is the reason. There are a lot of people with write access, and oddly we can create branches, but not delete them. So if we merge this, it will probably increase the number of branches in the zephyr project repo, which the admins with 'delete branch' privileges will have to keep cleaning up.

That brings another question: should branch creation be restricted? I think GH branch protection rules should allow to do that. @nashif

**Comment by nashif** [comment]
> That brings another question: should branch creation be restricted? I think GH branch protection rules should allow to do that. @nashif

not, if you have write access, you can still create branches even with protection

**Comment by mbolivar-nordic** [comment]
> Would `Open on GitHub` text be better?

That makes sense to me. I won't bikeshed the specifics as long as editing isn't what's being recommended given the issues with branching.

**Comment by gmarull** [comment]
I have updated the PR so that it now renders "Open on GitHub".

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by carlescufi** [comment]
@nashif please re-review

**Review by carlescufi — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
