### PR TITLE
General fixes related with wrong sign type

### PR DESCRIPTION
**Pull request by ceolin**
- Remove dead code related with compare unsigned type with < 0
- Change unsigned variables to signed when they are assigned to signed variable

### CODE REVIEW

**Review by jukkar — APPROVED** [review]
LGTM

**Review by nvlsianpu — APPROVED** [review]

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
Pleas correct commit messages.
Code itself is fine, thanks for the patch.

**Review by alexanderwachter — APPROVED** [review]

**Review by nandojve — APPROVED** [review]
Thank you @ceolin !

**Review by Navin-Sankar — APPROVED** [review]

**Comment by ceolin** [comment]
> Pleas correct commit messages.
> Code itself is fine, thanks for the patch.

done, could you please check it again.

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
