### PR TITLE
Interrupt timing of host dma l1 exit

### PR DESCRIPTION
**Pull request by jsarha**

### CODE REVIEW

**Comment by plbossart** [comment]
Initial commit from @abonislawski was used in the mtl-005-stable branch: https://github.com/thesofproject/zephyr/commits/mtl-005-drop-stable

@abonislawski @mwasko are you good with the port done by @jsarha ?

**Review by abonislawski — COMMENTED** [review]
oops, I forgot about this

but Im ok if @jsarha want to maintain this PR

**Comment by jsarha** [comment]
Intel SOF CI results with this change are available here: https://github.com/thesofproject/sof/pull/7922

**Comment by jsarha** [comment]
@plbossart I am leaving for two week vacation after today, but I am sure @abonislawski is able to help with this better that I could.

**Comment by abonislawski** [comment]
> @plbossart I am leaving for two week vacation after today, but I am sure @abonislawski is able to help with this better that I could.

Ok, so I created #60512

**Comment by kv2019i** [comment]
Replaced by https://github.com/zephyrproject-rtos/zephyr/pull/60512

**Pull request closed without merging**
