### PR TITLE
 boards: shields: Introduce frdm_cr20a shield

### LINKED ISSUE #7462: Convert mcr20a to be a shield when that functionality is merged
The mcr20a should be treated like a shield, so once we support shields, we should move the mcr20 support over to that.

### PR DESCRIPTION
**Pull request by MaureenHelm**
Introduces an arduino-compatible shield for the mcr20a radio
transceiver and converts net samples to use it.

Fixes #7462

### CODE REVIEW

**Review by mike-scott — COMMENTED** [review]
These shield changes definitely feel like they are moving in a good direction:
- Ignoring the 82 lines of doc addition, the overall diff for this is a wash (+39,-39)
- Shield functionality should in theory be usable by every sample that can benefit from it, not just the few pre-configured sample.

@erwango should we hold off on this commit until we move from .conf file to Kconfig.defconfig for shields?  Or let it in knowing this shield will also need to be migrated slightly later.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by dbkinder — APPROVED** [review]
+1 for doc changes

**Comment by mike-scott** [comment]
I wont hold this PR up for future shield changes.  LGTM

**Review by mike-scott — APPROVED** [review]

**Pull request merged**
