### PR TITLE
add qemu_x86_coverage target

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Add a target built and run by CI which enables CONFIG_COVERAGE=y, to help catch issues with code coverage as they happen.

### CODE REVIEW

**Comment by andrewboie** [comment]
> boards/x86/qemu_x86/qemu_x86_coverage.dts missing copyright.

Is this check broken?
The first line of the file is:

    /* SPDX-License-Identifier: Apache-2.0 */

**Comment by nashif** [comment]
> Is this check broken?

no, it is complaining about copyright, you only have the license.

**Review by dcpleung — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by nashif** [comment]
I am getting build failures when trying locally.

**Comment by andrewboie** [comment]
> I am getting build failures when trying locally.

@nashif can you be a little more specific

**Comment by nashif** [comment]
> @nashif can you be a little more specific

```
i9:zephyr((HEAD detached from upstream/pull/15886)): sanitycheck -p qemu_x86_coverage -f
JOBS: 40
Cleaning output directory /home/nashif/Work/zephyrproject/zephyr/sanity-out
19 tests selected, 0 tests discarded due to filters
total complete:    2/  19  10%  failed:    0

qemu_x86_coverage         samples/philosophers/sample.philosopher.fifos      FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.fifos/handler.log

total complete:    3/  19  15%  failed:    1

qemu_x86_coverage         samples/philosophers/sample.philosopher.stacks     FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.stacks/handler.log

total complete:    4/  19  21%  failed:    2

qemu_x86_coverage         samples/portability/cmsis_rtos_v1/philosophers/sample.philosopher.same_prio FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/portability/cmsis_rtos_v1/philosophers/sample.philosopher.same_prio/handler.log

total complete:    5/  19  26%  failed:    3

qemu_x86_coverage         samples/portability/cmsis_rtos_v1/philosophers/sample.philosopher.semaphores FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/portability/cmsis_rtos_v1/philosophers/sample.philosopher.semaphores/handler.log

total complete:    6/  19  31%  failed:    4

qemu_x86_coverage         samples/philosophers/sample.philosopher.preempt_only FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.preempt_only/handler.log

total complete:    7/  19  36%  failed:    5

qemu_x86_coverage         samples/philosophers/sample.philosopher.semaphores FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.semaphores/handler.log

total complete:    8/  19  42%  failed:    6

qemu_x86_coverage         samples/portability/cmsis_rtos_v2/philosophers/sample.philosopher.same_prio FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/portability/cmsis_rtos_v2/philosophers/sample.philosopher.same_prio/handler.log

total complete:    9/  19  47%  failed:    7

qemu_x86_coverage         samples/portability/cmsis_rtos_v2/philosophers/sample.philosopher.semaphores FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/portability/cmsis_rtos_v2/philosophers/sample.philosopher.semaphores/handler.log

total complete:   10/  19  52%  failed:    8

qemu_x86_coverage         samples/philosophers/sample.philosopher.same_prio  FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.same_prio/handler.log

total complete:   11/  19  57%  failed:    9

qemu_x86_coverage         samples/philosophers/sample.philosopher            FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher/handler.log

total complete:   12/  19  63%  failed:   10

qemu_x86_coverage         samples/philosophers/sample.philosopher.static     FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.static/handler.log

total complete:   13/  19  68%  failed:   11

qemu_x86_coverage         samples/drivers/crypto/sample.driver.crypto.mbedtls.micro FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/drivers/crypto/sample.driver.crypto.mbedtls.micro/handler.log

total complete:   14/  19  73%  failed:   12

qemu_x86_coverage         samples/portability/cmsis_rtos_v1/philosophers/sample.philosopher FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/portability/cmsis_rtos_v1/philosophers/sample.philosopher/handler.log

total complete:   15/  19  78%  failed:   13

qemu_x86_coverage         samples/portability/cmsis_rtos_v2/philosophers/sample.philosopher FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/portability/cmsis_rtos_v2/philosophers/sample.philosopher/handler.log

total complete:   16/  19  84%  failed:   14

qemu_x86_coverage         samples/philosophers/sample.philosopher.coop_only  FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.coop_only/handler.log

total complete:   17/  19  89%  failed:   15

qemu_x86_coverage         samples/philosophers/sample.philosopher.lifos      FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/philosophers/sample.philosopher.lifos/handler.log

total complete:   18/  19  94%  failed:   16

qemu_x86_coverage         samples/drivers/crypto/sample.driver.crypto.mbedtls FAILED: timeout
	see: sanity-out/qemu_x86_coverage/samples/drivers/crypto/sample.driver.crypto.mbedtls/handler.log

total complete:   19/  19  100%  failed:   17
2 of 19 tests passed with 0 warnings in 71 seconds
```

**Review by nashif — APPROVED** [review]

**Comment by marc-hb** [comment]
I love CI and I love code coverage in CI even more. However I'm not enamoured with the new `qemu_x86_coverage` "platform(s)" hiding a mere Kconfig change that AFAIK can be performed from the sanitycheck command line. Has any Kconfig change been disguised as a platform before? This one in particular is completely platform-independent; orthogonal.

@nashif what would it take to implement a new, separate CI check for code coverage? This could be the start of actually reporting code coverage results and metrics (which are obviously not PASS/FAIL). Except for the git rebase bug that made it useless, I'm curious how codecov worked, did it rely on gcov?

In the mean time I have to keep a local sanitycheck hack to exclude qemu_x86_coverage (it includes paths in binaries).

**Pull request merged**
