### PR TITLE
samples: net: echo_async_select: Use read()/write() if possible

### LINKED ISSUE #25407: No tests/samples covering socket read()/write() calls
While support for POSIX read()/write() calls was implemented for some time (enabled by CONFIG_POSIX_API option), there're no tests or samples using this feature. This can lead to regressions and must be addressed.

### PR DESCRIPTION
**Pull request by pfalcon**
If build with full POSIX API, use read()/write() instead of
recv()/send() calls for sockets.

We have read()/write() support for a while, but no samples/tests
actually performed at least a build test for it (so it will be
done now).

Fixes: #25407
Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
@cfriedt: Please review too. And I would appreciate if you performed the similar conversion for your socketpair test(s), as was suggested in the original review. (I didn't want to push with that in the original review, given the amount changes you already made, but I would expect you to follow the suggestion given then. Thanks.)

**Comment by cfriedt** [comment]
I found some really strange behaviour when I used `read()` / `write()` with `CONFIG_POSIX_API=y`, in that it would actually just write to stdout instead of to the actual socket. Maybe things have changed since I tested that, so I'll have a look. 

Also, looks like you need to include `<posix/unistd.h>` to avoid the implicit function declaration warning (promoted to error).

**Comment by pfalcon** [comment]
@cfriedt, thanks for looking.

> I found some really strange behaviour when I used read() / write() with CONFIG_POSIX_API=y, in that it would actually just write to stdout instead of to the actual socket.

As we discussed, you found that behavior with CONFIG_POSIX_API=n (unless you have a reproduction testcase).

> Also, looks like you need to include <posix/unistd.h> to avoid the implicit function declaration warning (promoted to error).

I don't see any such warning with either Zephyr or Linux, and likely reason that `<unistd.h>` (sic) is already included.

CI fails because `platform_whitelist: qemu_x86` directive in sample.yaml doesn't seem to have effect (it starts to build for know-broken pseudo-targets like native_posix_64). Investigating.

**Comment by pfalcon** [comment]
Ah, d'oh, I see the problem -  committed extra code lying in my workcopy. Let's call it Friday afternoon. Fixing.

**Comment by pfalcon** [comment]
Ok, pushed changes for just echo_async_select, as was intended.

**Comment by cfriedt** [comment]
Ok, I'll create a ticket for socketpair tests. Unfortunately, I have no reviewer privs here, so I can only say :+1:

**Comment by pfalcon** [comment]
> Ok, I'll create a ticket for socketpair tests. 

Thanks!

> Unfortunately, I have no reviewer privs here, so I can only say +1

Yep, you don't have suitable level of membership so I can add you as a reviewer. However, on any project on github, for any PR, you can go to "Files changed" tab (https://github.com/zephyrproject-rtos/zephyr/pull/25356/files here), then you'll see green "Review changes" button near top left corner. Clicking on it, you can leave you review. (And that would be appreciated, because one of the problem with POSIX subsys is that I'm the only codeowner, so if I submit PR, there can nobody else to review. So, people interested in the POSIX subsys should keep together and help each other with reviews. Thanks.)

**Review by cfriedt — APPROVED** [review]
Looks good to me. Regular read(2) write(2) support is a must for streaming APIs.

**Review by jukkar — APPROVED** [review]

**Comment by pfalcon** [comment]
Created a related bug ticket: https://github.com/zephyrproject-rtos/zephyr/issues/25407 , marking for 2.3.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
