### PR TITLE
Fixes issues after moving to DTS

### PR DESCRIPTION
**Pull request by nashif**
- Flashing problems due to dependency on Kconfig options in the past
- Generate a valid header file and introduce options to extract script

### CODE REVIEW

**Comment by nashif** [comment]
still not perfect, the file is parsed too late and is not available for flash, need to figure out dependencies

**Comment by nashif** [comment]
updated and seems to work now.

**Comment by agross-linaro** [comment]
I already had a set of patches in progress on this.  I am going to push mine and we can figure out which or what combination of them to use.  They are both pretty similar for the most part.

**Review by MaureenHelm — APPROVED** [review]
Tested `make flash` with frdm_k64f and openocd 0.10.0, works fine.

**Review by agross-oss — CHANGES_REQUESTED** [review]
Changing a dts file does not cause the config to be rebuilt.  Something with the dependencies is not quite right.

Also, during builds the config file gets iterated over more than it should.  This is due to the odd way in which the -include causes an implicit dependency.  The first time through the dotconfig=1, the auto.conf gets generated but the environment variables are not sourced.  This in turn causes the config to get generated with ARCH='' which throws it all off.  Subsquent runs through the makefile, it redoes the config file again.

**Review by galak — CHANGES_REQUESTED** [review]
Would like to go w/andy's changes to the script and the Makefile changes are pretty similar.

**Comment by nashif** [comment]
not that this PR fixes a second issue, not only the flash problem, so this needs to be addressed in Andy's version if you want to take it.

**Comment by galak** [comment]
What's the second issue?

**Comment by agross-linaro** [comment]
I think he is referring to the endif fixup stuff.  The fixup append was happening outside of the endif of the include file.  So if this was included multiple times you'll get redeclarations.

**Comment by nashif** [comment]
> What's the second issue?

ZEP-2147

**Comment by nashif** [comment]
ok, closing this one to avoid confusion with what Andy submitted, not ideal to have 2 PRs doing the same thing

**Pull request closed without merging**
