### PR TITLE
drivers: sensor: lis2dh: Level triggered interrupts

### PR DESCRIPTION
**Pull request by tautologyclub**
Both DRDY and motion interrupts behaves like level signals since they
remain asserted until they're cleared. Configuring them as edge
interrupts is dangerous because if we ever miss an interrupt, it may
never get cleared and thus will never trigger again.

Treating them as edge signals seems to have no advantages, other than
being marginally simpler to implement.

Signed-off-by: Benjamin Lindqvist <benjamin.lindqvist@endian.se>

### CODE REVIEW

**Comment by tautologyclub** [comment]
@avisconti They're both tested thoroughly now - using the new setup on a customer project.

**Comment by avisconti** [comment]
> @avisconti They're both tested thoroughly now - using the new setup on a customer project.

Can you add details on the test done (e.g. board, i2c and/or spi, ...) in the PR header itself?

**Comment by tautologyclub** [comment]
@avisconti Sorry it was a while ago I submitted a PR, will this do? I'd be happy to expand if not.

**Review by avisconti — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by petrovichkr** [comment]
This PR breaks compability with STM32 because STM32 doesn't support level triggered interrupts.

**Comment by tautologyclub** [comment]
> This PR breaks compability with STM32 because STM32 doesn't support level triggered interrupts.

So lis2dh is broken for stm32 currently?

**Comment by petrovichkr** [comment]
> > This PR breaks compability with STM32 because STM32 doesn't support level triggered interrupts.
> 
> So lis2dh is broken for stm32 currently?

Yes, the new trigger mechanism does not work on STM32.

Moreover, the driver initialization always completes successfully because the return value of `gpio_pin_interrupt_configure_dt` is not checked in the `setup_intX` routines. However, this is an another issue.

**Pull request merged**
