### PR TITLE
pm: device: Simplify device states

### PR DESCRIPTION
**Pull request by ceolin**
- Remove PM_DEVICE_STATE_LOW_POWER and PM_DEVICE_STATE_OFF as proposed and discussed in PM: Simplify device power states #38619

- Add new function to query which will be the next power state to be used by the SoC

- Simplified fdc2x1x power management due the device power states changes. Not need to handle case where the device was suspended and then went to OFF.

### CODE REVIEW

**Review by teburd — APPROVED** [review]
This seems to simplify device pm states nicely, I'm wary of how pm_power_state_next_get(void) appears thinking about how that might play in an SMP system as its used here, its not clear to me if there's a distinction between a global power state vs a per cpu power state in power.c at the moment, and something that might need clarification

**Review by gmarull — APPROVED** [review]
LGTM

**Review by JordanYates — CHANGES_REQUESTED** [review]
I disagree with removing `PM_DEVICE_STATE_OFF`. Just because current drivers don't use it doesn't mean that it is not needed for smooth handling of power transitions.

There can be a large difference in the setup required to bring a device to active state based on whether the device was previously unpowered, or sitting in a low power mode. Similarly there can be differences in the optimal pin configuration for both states.

For both of these reasons I use `PM_DEVICE_STATE_OFF` in my OOT device drivers that handle power domains properly.

I don't have a problem with combining `PM_DEVICE_STATE_SUSPENDED` and `PM_DEVICE_STATE_LOW_POWER`.

**Comment by ceolin** [comment]
> I disagree with removing `PM_DEVICE_STATE_OFF`. Just because current drivers don't use it doesn't mean that it is not needed for smooth handling of power transitions.
> 
> There can be a large difference in the setup required to bring a device to active state based on whether the device was previously unpowered, or sitting in a low power mode. Similarly there can be differences in the optimal pin configuration for both states.
> 
> For both of these reasons I use `PM_DEVICE_STATE_OFF` in my OOT device drivers that handle power domains properly.
> 
> I don't have a problem with combining `PM_DEVICE_STATE_SUSPENDED` and `PM_DEVICE_STATE_LOW_POWER`.

another thing, there is an issue to discuss this open for while https://github.com/zephyrproject-rtos/zephyr/issues/38619, please take a look in the backlog.

**Review by keith-zephyr — APPROVED** [review]

**Comment by cfriedt** [comment]
@MaureenHelm - please have a look

**Comment by ceolin** [comment]
> > I disagree with removing `PM_DEVICE_STATE_OFF`. Just because current drivers don't use it doesn't mean that it is not needed for smooth handling of power transitions.
> > There can be a large difference in the setup required to bring a device to active state based on whether the device was previously unpowered, or sitting in a low power mode. Similarly there can be differences in the optimal pin configuration for both states.
> > For both of these reasons I use `PM_DEVICE_STATE_OFF` in my OOT device drivers that handle power domains properly.
> > I don't have a problem with combining `PM_DEVICE_STATE_SUSPENDED` and `PM_DEVICE_STATE_LOW_POWER`.
> 
> I tend to agree with @JordanYates , I think we need at least three states for devices. Gyroscopes, for example, can take a long time to boot because they contain a mechanical oscillator that needs to stabilize. Consequently, they may have an intermediate low-power state between "off" and "active" that takes less time to wake up than from a cold boot.

And that is fine, they can have internal states based on system power states. But from the kernel perspective, the device is not active. The problem in having a third stage is, how is supposed to be used ? when kernel should set a device to OFF ?  If a another device is explicitly doing `pm_device_state_set(dev, PM_DEVICE_STATE_OFF)`, it is doing it wrong, this API is not intended to  be used for runtime device power management. Having a third state from device runtime power management is a big problem, what happen if the device is requested to suspend, then to power off and finally to become active ? What should be the final state ? suspended ? powered off ? or active ?

Note, devices can have as many internal states they want internally, they can check the appropriate state using the new API that returns what is the next system power state.

**Comment by ceolin** [comment]
@MaureenHelm @JordanYates I've changed the PR to keep `STATE_OFF`, but it would be really good if you can explain how you use this state right now, the use case is not clear for me at the moment, and would be nice to have it clarified to have the use case covered in further changes.

**Comment by JordanYates** [comment]
> @MaureenHelm @JordanYates I've changed the PR to keep STATE_OFF, but it would be really good if you can explain how you use this state right now, the use case is not clear for me at the moment, and would be nice to have it clarified to have the use case covered in further changes.

I'm not sure how I can be much clearer than in my original comment:

> There can be a large difference in the setup required to bring a device to active state based on whether the device was previously unpowered, or sitting in a low power mode. Similarly there can be differences in the optimal pin configuration for both states.

The states in this PR are used to notify device drivers about requested changes to their operation mode. A device being powered off is different from a device sitting in a low power mode. Unless the on->off transitions move to a separate notification API, we need both `OFF` and `SUSPEND` to be able to differentiate between the two states.

**Comment by JordanYates** [comment]
> I completely understand the differences, I'm asking how you are using this state right now, since it is not used by the kernel nor device runtime. Another argument is, some devices can have multiple low power states and they will need to handle it internally, that is similar if STATE_OFF is removed.

Ah, basically I have an additional API which handles power domains, as Zephyr obviously doesn't yet.
The requirement I enforce is that my API is called before `device_pm_get`, and optionally after `device_pm_put`.
For example.
```
const struct device *accelerometer = DEVICE_DT_GET(DT_INST(0, blah));

device_req_power_domain(accelerometer);

device_pm_get(accelerometer);

/* Do things */

device_pm_put(accelerometer);

/* Optional depending on whether you want the accelerometer to remain powered */
device_rel_power_domain(accelerometer);
```
Where the `power_domain` functions iterate over supported devices and call `pm_device_state_set` with `PM_DEVICE_STATE_OFF` and `PM_DEVICE_STATE_LOW_POWER` directly. They are implemented over the `onoff_manager` API, so they are implicitly thread-safe.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
