### PR TITLE
[Backport v3.2-branch] drivers: intc: mchp_ecia_xec: Ensure correct device init order

### LINKED ISSUE #56067: Fix build issues with arm clang compiler for mec17xx platforms
There are a number of different failures we see when building the arm clang compiler when building the mec17xx platforms.

### PR DESCRIPTION
**Pull request by zephyrbot**
Fixes #56067
Backport 161ca0376f85b0de2999b646b8fd4f56b8c51e75 from #56577

### CODE REVIEW

**Comment by galak** [comment]
Part of #56067

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
@carlescufi ping on review/merge for 3.2

**Comment by mbolivar-nordic** [comment]
> @carlescufi ping on review/merge for 3.2

think you meant @fabiobaltieri @mmahadevan108

**Review by fabiobaltieri — APPROVED** [review]

**Comment by jgl-meta** [comment]
@jvasanth1  If you approve of this can you check it in?

**Review by albertofloyd — APPROVED** [review]

**Pull request merged**
