### PR TITLE
Net: dumb http server fixes

### PR DESCRIPTION
**Pull request by jukkar**

### CODE REVIEW

**Review by tgorochowik — COMMENTED** [review]
s/dump/dumb/g in the commit messages (?)

**Comment by jukkar** [comment]
> s/dump/dumb/g in the commit messages (?)

Ouch, indeed :) Will send fixed version.

**Review by pfalcon — CHANGES_REQUESTED** [review]
+1 for the changes overall, but please change title of 2nd commit to "samples: net: dumb_http_server: Check for EOF while skipping headers". And apparently, update description too, because there actually was a pretty serious issue that of EOF happened in HTTP headers, this sample would go into infinite loop.

**Comment by jukkar** [comment]
Rebased against latest master

**Comment by jukkar** [comment]
ping @pfalcon

**Comment by pfalcon** [comment]
> +1 for the changes overall, but please change title of 2nd commit to "samples: net: dumb_http_server: Check for EOF while skipping headers". 

@jukkar, please apply the suggestion above.

**Comment by pfalcon** [comment]
I might also suggest to print a warning-like message, as EOF in headers is not a normal situation.

**Comment by jukkar** [comment]
> please apply the suggestion above.

Hmm, I thought I had fixed that. I will resend proper version asap.

**Review by pfalcon — APPROVED** [review]
Thanks!

**Comment by jukkar** [comment]
> I might also suggest to print a warning-like message, as EOF in headers is not a normal situation.

I did not add any warning prints here, the connection could close at any time and we are printing info about that at the end of the func.

**Comment by pfalcon** [comment]
> I did not add any warning prints here, the connection could close at any time and we are printing info about that at the end of the func.

Sounds good, if someone faces a problem with it, can be added later.

**Pull request merged**
