### PR TITLE
Bluetooth: BAP: Unicast client shall support 0 or > 1 endpoints

### PR DESCRIPTION
**Pull request by Thalley**
As per table 4.2 in BAP v1.0.1, the BAP unicast client shall support at least 2 (> 1) endpoints in either direction if it supports that direction.

Since Kconfig does not support such requirements (0 || > 1), this is done using a BUILD_ASSERT.

### CODE REVIEW

**Review by larsgk — APPROVED** [review]

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]
I cannot find the statement in the BAP spec that mandates 1 > 0 EP support on Client side

**Comment by Thalley** [comment]
> I cannot find the statement in the BAP spec that mandates 1 > 0 EP support on Client side

@MariuszSkamra It is mandated by Table 4.2 in BAP:

image

Audio Configuration 6(i) is mandatory to support for a Unicast Client that supports the Audio Source role, and Audio Configuration 9(i) is mandatory to support if the Client supports the Audio Sink role. 

Since support of Audio Sink / Audio Source is (currently) determined by whether the number of endpoints > 0, we can say that we must support 6(i) if `CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT > 0` and we must support 9(i) if `CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT > 0`. Both 6(i) and 9(i) requires 2 endpoints in the same direction to be supported.

**Comment by MariuszSkamra** [comment]
Thank You, I overlooked this one, I was looking for an exact sentence.
TBH that's kind'a stupid though to mandate client to handle 2 microphones.
So if a initiator implementation is about to be certified including support for 2 earbuds, it needs to handle 4 source ASE case if I understand correctly

**Review by MariuszSkamra — APPROVED** [review]

**Comment by Thalley** [comment]
> Thank You, I overlooked this one, I was looking for an exact sentence. TBH that's kind'a stupid though to mandate client to handle 2 microphones, should be up to implementation.

Yeah, agree on that one :)

**Pull request merged**
