### PR TITLE
cmsis: Update ARM CMSIS headers to version 5.2.0

### PR DESCRIPTION
**Pull request by ioannisg**
This commit updates the (ext) ARM CMSIS headers to version 5.2.0,
taken from https://github.com/ARM-software/CMSIS_5/tree/5.2.0.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
@carlescufi , @skordal, @pizi-nordic

**Review by carlescufi — CHANGES_REQUESTED** [review]
Commit format must comply with contribution guidelines. Take a look at previous commits and here:
http://docs.zephyrproject.org/contribute/contribute_guidelines.html

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@ioannisg why not the latest revision of the master branch btw?

**Review by MaureenHelm — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
What about updating to 5.2.1-dev3 instead?  This gets us some various fixes to the headers.

Also, need to update ext/hal/cmsis/README, and remove CMSIS_END_USER_LICENCE_AGREEMENT.*

**Comment by ioannisg** [comment]
@galak,first, thanks for catching the need for updating the README. Fixed now. Also removed the license agreement files, as ARM has switched to Apache 2.0 open source license since version 5.0.0.

As for the 5.2.1-dev release; it is supposed to be a pre-release (i.e. incomplete), so I would be a bit reluctant to bring it into Zephyr, instead of an official (and complete) release. 

Quoting ARM, regarding 5.2.1-dev:
"This development release is based on the development branch. Its intention is to give early access to the latest component added: CMSIS-NN."

**Comment by nashif** [comment]
> As for the 5.2.1-dev release; it is supposed to be a pre-release (i.e. incomplete), so I would be a bit reluctant to bring it into Zephyr, instead of an official (and complete) release.

I agree we should not include unofficial releases and instead stick to released versions, once 5.2.1 is ready we can move to it.

**Review by galak — APPROVED** [review]

**Pull request merged**
