### PR TITLE
manifest: update cmsis-nn to v5.0.0

### PR DESCRIPTION
**Pull request by JordanYates**
Update cmsis-nn to version 5.0.0.
Revision history can be found at:
https://arm-software.github.io/CMSIS-NN/latest/rev_hist.html

New upstream revision is the v5.0.0 release tag + `module.yml`  https://github.com/ARM-software/CMSIS-NN/commit/e042bf748ee808f138f4d85b7d690aad445f6367

### CODE REVIEW

**Review by XenuIsWatching — APPROVED** [review]

**Review by XenuIsWatching — CHANGES_REQUESTED** [review]
It looks like some build issues need to be resolved with tflite-micro

**Comment by JordanYates** [comment]
Yea, the `tflite-micro` fork hasn't been updated for almost 3 years, so this may not be trivial

**Comment by XenuIsWatching** [comment]
> Yea, the `tflite-micro` fork hasn't been updated for almost 3 years, so this may not be trivial

it was only updated 8 months ago.... although the branch should probably be named to 'zephyr' something
https://github.com/zephyrproject-rtos/tflite-micro/tree/main

**Comment by kartben** [comment]
@JordanYates do you want to try to get this in for 3.7? Looks like it needs rebasing to trigger CI

**Comment by JordanYates** [comment]
> @JordanYates do you want to try to get this in for 3.7? Looks like it needs rebasing to trigger CI EDIT: or maybe those were legit failures, looking at the comment history,

The master plan was always to wait for v6.0.0 to come out instead haha.
New PR #73995.

**Pull request closed without merging**
