### PR TITLE
pm: remove device management from system PM

### PR DESCRIPTION
**Pull request by gmarull**
Managing devices as part of the system power transitions, e.g., suspend all devices when going to idle, has always been a fragile approach. The existence of CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE alone proofs that. If we nowadays enable CONFIG_PM and CONFIG_PM_DEVICE, the PM subsystem will iterate over all devices and try to suspend them when entery any of the low power modes. There are a few exceptions, e.g. if device is busy, is a wakeup source, etc. This may sound like a _good_ idea, but has some fundamental flaws:

1. In this context one can't block, so if I have e.g. an I2C/SPI sensor device, and I turn on CONFIG_PM+CONFIG_PM_DEVICE my system won't work at all. See e.g. https://github.com/zephyrproject-rtos/zephyr/issues/55598
2. We suspend/resume devices for any low power state, no matter if idle, s2ram, etc.
2. We iterate over all devices twice on every suspend/resume sequence

With respect to devices, the proposed alternative is to just use the PM runtime API, which decouples system power states from devices. For drivers that really need to take some actions when the system goes to a low power state, can register the appropriate callbacks using the `pm_notifier_*` APIs. This makes sure that first, only devices that need to take some actions are called, and second, we eliminate blocking devices from the equation. With this method, devices will also get called with the next power state as an argument, letting them to perform specific actions for each power state.

### CODE REVIEW

**Comment by ceolin** [comment]
> Managing devices as part of the system power transitions, e.g., suspend all devices when going to idle, has always been a fragile approach. The existence of CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE alone proofs that. If we nowadays enable CONFIG_PM and CONFIG_PM_DEVICE, the PM subsystem will iterate over all devices and try to suspend them when entery any of the low power modes. There are a few exceptions, e.g. if device is busy, is a wakeup source, etc. This may sound like a _good_ idea, but has some fundamental flaws:
> 
> 1. In this context one can't block, so if I have e.g. an I2C/SPI sensor device, and I turn on CONFIG_PM+CONFIG_PM_DEVICE my system won't work at all

Why ? in this case the sensor will be called before the bus, if the sensor is doing something and can't be suspended
it should return an error, then the system will continue active (and resume already suspended devices)

> 2. We suspend/resume devices for any low power state, no matter if idle, s2ram, etc.

That's true, there is an on going discussion to tell which low power states should suspend devices. That probably address this problem and give more flexibility for users.

> 3. We iterate over all devices twice on every suspend/resume sequence

You mean, one time when suspending and another time when resuming.

> 
> With respect to devices, the proposed alternative is to just use the PM runtime API, which decouples system power states from devices. For drivers that really need to take some actions when the system goes to a low power state, can register the appropriate callbacks using the `pm_notifier_*` APIs. This makes sure that first, only devices that need to take some actions are called, and second, we eliminate blocking devices from the equation. With this method, devices will also get called with the next power state as an argument, letting them to perform specific actions for each power state.

I am not convinced that just removing it is the right approach. Solving problem 2 is not complicated and this will remove part of the cost of the item 3 because the subsystem will iterate over devices only when needed.
For item 1, the driver itself can already solve the problem, adding a constraint in the system ` pm_policy_state_lock_get` or setting the bus and other dependencies busy to avoid the system to suspend them.

And if this feature is not wanted at all, the target can use `CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE`

**Comment by gmarull** [comment]
> > Managing devices as part of the system power transitions, e.g., suspend all devices when going to idle, has always been a fragile approach. The existence of CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE alone proofs that. If we nowadays enable CONFIG_PM and CONFIG_PM_DEVICE, the PM subsystem will iterate over all devices and try to suspend them when entery any of the low power modes. There are a few exceptions, e.g. if device is busy, is a wakeup source, etc. This may sound like a _good_ idea, but has some fundamental flaws:
> > 
> > 1. In this context one can't block, so if I have e.g. an I2C/SPI sensor device, and I turn on CONFIG_PM+CONFIG_PM_DEVICE my system won't work at all
> 
> Why ? in this case the sensor will be called before the bus, if the sensor is doing something and can't be suspended it should return an error, then the system will continue active (and resume already suspended devices)
> 

Because you can't perform blocking calls in that context. If you have a system where you enable device PM, and it turns out that e.g. an I2C sensor has support for PM, you won't be able to enter any low-power state. See e.g. https://github.com/zephyrproject-rtos/zephyr/issues/55598. This is a major design flaw that can't be easily solved, and it's in part why we have device runtime PM.

> > 2. We suspend/resume devices for any low power state, no matter if idle, s2ram, etc.
> 
> That's true, there is an on going discussion to tell which low power states should suspend devices. That probably address this problem and give more flexibility for users.

Even if solved, the (1) problem persists. But the question is: why not use other mechanisms such as notifier or device runtime PM? (Note: I'll open a PR to modify notifiers so that they get device context when called, so it can be used from drivers).

> 
> > 3. We iterate over all devices twice on every suspend/resume sequence
> 
> You mean, one time when suspending and another time when resuming.

Yes

> 
> > With respect to devices, the proposed alternative is to just use the PM runtime API, which decouples system power states from devices. For drivers that really need to take some actions when the system goes to a low power state, can register the appropriate callbacks using the `pm_notifier_*` APIs. This makes sure that first, only devices that need to take some actions are called, and second, we eliminate blocking devices from the equation. With this method, devices will also get called with the next power state as an argument, letting them to perform specific actions for each power state.
> 
> I am not convinced that just removing it is the right approach. Solving problem 2 is not complicated and this will remove part of the cost of the item 3 because the subsystem will iterate over devices only when needed. For item 1, the driver itself can already solve the problem, adding a constraint in the system ` pm_policy_state_lock_get` or setting the bus and other dependencies busy to avoid the system to suspend them.

`pm_policy_state_lock_get` doesn't solve (1). This API is designed so that drivers can't tell the system to not enter a particular low-power state temporarily (e.g. because a UART is still transmitting and, if the system is suspended, pending data will be lost).
> 
> And if this feature is not wanted at all, the target can use `CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE`

IIRC `CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE` exists because (1) is a known issue, so at least you have a way to get rid of the problem.

**Comment by JordanYates** [comment]
The automatic transition of external devices based on the SoC state has never really made sense to me, but as I don't use system power states beyond idle it has never affected me.

**Comment by knthm** [comment]
At least from my perspective I think this is a good approach; I found the existence of `CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE` confusing, especially since it's the default and you have to develop at least a cursory understanding of System/Device PM to understand what it even does.

**Comment by ceolin** [comment]
> > > Managing devices as part of the system power transitions, e.g., suspend all devices when going to idle, has always been a fragile approach. The existence of CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE alone proofs that. If we nowadays enable CONFIG_PM and CONFIG_PM_DEVICE, the PM subsystem will iterate over all devices and try to suspend them when entery any of the low power modes. There are a few exceptions, e.g. if device is busy, is a wakeup source, etc. This may sound like a _good_ idea, but has some fundamental flaws:
> > > 
> > > 1. In this context one can't block, so if I have e.g. an I2C/SPI sensor device, and I turn on CONFIG_PM+CONFIG_PM_DEVICE my system won't work at all
> > 
> > 
> > Why ? in this case the sensor will be called before the bus, if the sensor is doing something and can't be suspended it should return an error, then the system will continue active (and resume already suspended devices)
> 
> Because you can't perform blocking calls in that context. If you have a system where you enable device PM, and it turns out that e.g. an I2C sensor has support for PM, you won't be able to enter any low-power state. See e.g. #55598. This is a major design flaw that can't be easily solved, and it's in part why we have device runtime PM.

I know about it, that is why returning an error would stop the transition. My point is that just removing it does not solve the problem. If a device register to receive notifications to do power management when the system is going to low power it still can't block because the notification callback happens from the idle thread.

> 
> > > 2. We suspend/resume devices for any low power state, no matter if idle, s2ram, etc.
> > 
> > 
> > That's true, there is an on going discussion to tell which low power states should suspend devices. That probably address this problem and give more flexibility for users.
> 
> Even if solved, the (1) problem persists. But the question is: why not use other mechanisms such as notifier or device runtime PM? (Note: I'll open a PR to modify notifiers so that they get device context when called, so it can be used from drivers).

I am not against it, just think that allowing the target select which states should trigger power management is flexible enough. There are targets that use it to simplify their power management flow. If one does not it, this can be disabled not selecting any state to automatically trigger device power managment.

> 
> > > 3. We iterate over all devices twice on every suspend/resume sequence
> > 
> > 
> > You mean, one time when suspending and another time when resuming.
> 
> Yes
> 
> > > With respect to devices, the proposed alternative is to just use the PM runtime API, which decouples system power states from devices. For drivers that really need to take some actions when the system goes to a low power state, can register the appropriate callbacks using the `pm_notifier_*` APIs. This makes sure that first, only devices that need to take some actions are called, and second, we eliminate blocking devices from the equation. With this method, devices will also get called with the next power state as an argument, letting them to perform specific actions for each power state.
> > 
> > 
> > I am not convinced that just removing it is the right approach. Solving problem 2 is not complicated and this will remove part of the cost of the item 3 because the subsystem will iterate over devices only when needed. For item 1, the driver itself can already solve the problem, adding a constraint in the system ` pm_policy_state_lock_get` or setting the bus and other dependencies busy to avoid the system to suspend them.
> 
> `pm_policy_state_lock_get` doesn't solve (1). This API is designed so that drivers can't tell the system to not enter a particular low-power state temporarily (e.g. because a UART is still transmitting and, if the system is suspended, pending data will be lost).

Drivers can set constraints to states that trigger device power management when they can't be suspended. That's complicated, it is, but it is possible.

> 
> > And if this feature is not wanted at all, the target can use `CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE`
> 
> IIRC `CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE` exists because (1) is a known issue, so at least you have a way to get rid of the problem.

Lets remove it and let the target selected which states should trigger device power management (which can be no one)

**Comment by ceolin** [comment]
> At least from my perspective I think this is a good approach; I found the existence of `CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE` confusing, especially since it's the default and you have to develop at least a cursory understanding of System/Device PM to understand what it even does.

don't disagree, my proposal is to remove this symbol and let the target select which states it wants to trigger power management (including not trigger it at all).

**Comment by ceolin** [comment]
I am aware of applications relying on this behavior. I am in favor of promoting device runtime power management, but that require drivers to do more work and we don't have many of them doing it properly.  The system pm is something that works in many cases, obviously there are cases where it does  not work, that is why the proposal to let the target select which states should do it makes sense for me.
When we get more drivers doing device runtime properly and it starts to become the default solution we can think about removing it imho.

**Comment by JordanYates** [comment]
> When we get more drivers doing device runtime properly and it starts to become the default solution we can think about removing it imho.

On that note, #60411 is attempting to progress making it easier to do device runtime PM properly (and is how I write drivers internally)

**Comment by gmarull** [comment]
> I am aware of applications relying on this behavior.

I honestly doubt many people are doing that because of (1). By doing a quick grep in tree, many drivers implementing PM hooks make use of blocking calls (about half of them), some others are bus devices (I2C/SPI) so because of (1) they are indirectly affected if they have any child implementing PM. What I'm aware of is about many people doing _manual_ device PM using `pm_device_action_run`.

At the very least, I think we should deprecate this device PM model, I can't see how it can be fixed and there are better alternatives. I think device PM is just more confusing/frustrating by having this feature.

**Comment by ceolin** [comment]
> > I am aware of applications relying on this behavior.
> 
> I honestly doubt many people are doing that because of (1). By doing a quick grep in tree, many drivers implementing PM hooks make use of blocking calls (about half of them), some others are bus devices (I2C/SPI) so because of (1) they are indirectly affected if they have any child implementing PM. What I'm aware of is about many people doing _manual_ device PM using `pm_device_action_run`.

intel adsp used by SoF is using this model. I had a long discussion and recommended device runtime as the way to go, but they decided that this model is the one that fits better their application. Note that this firmware is used in a context that is different from most iot devices, they are part of bigger platform and the firmware power management is triggered by an external entity.
That's one example in tree and upstream that is using it and I've heard others using it too, so please don't assume that you are seeing all use cases. 


> 
> At the very least, I think we should deprecate this device PM model, I can't see how it can be fixed and there are better alternatives. I think device PM is just more confusing/frustrating by having this feature.

I not convinced that this has to be deprecated. In my opinion this should be made optional so it does not cause problems in target using device runtime power management. I agree with you in promoting device runtime, but that does not imply in removing (or even deprecate) device power management for now.

**Review by ceolin — CHANGES_REQUESTED** [review]
Due commented reasons.

**Comment by gmarull** [comment]
> Due commented reasons.

I’ll propose an alternative to the current system device PM model, so we’ll have a clear alternative for those who need to run device actions when system transitions to a low power state. I’ll need some prep-work before though.

I think it will help on deprecating this model, which I think doesn’t benefit device PM as a whole.

**Pull request closed without merging**
