### PR TITLE
net: coap: Fix coap_packet_get_payload() function

### LINKED ISSUE #36739: coap_packet_get_payload() returns the wrong size
The function `coap_packet_get_payload()` returns the wrong size, it  returns the number of bytes left for payload, no the actual payload size.
the current calculation is:
```
payload_len = cpkt->max_len - cpkt->hdr_len - cpkt->opt_len;
```
Which means that `payload_len` includes the unused bytes.

Snippet create packet:
```
#define MAX_COAP_MSG_LEN 768
#define COAP_UPLINK_TOKENLEN 2
	u8_t *payload, size_t plsize;
	enum coap_method code;
	const char uri[] = "/meta"
	u8_t *format = NULL;
	struct coap_packet request;
	int ret = 0;
	static u8_t buffer[MAX_COAP_MSG_LEN];
	u8_t *token = next_nonzero_coap_token(COAP_UPLINK_TOKENLEN);
	u8_t type = COAP_TYPE_NON_CON;
	u16_t id = coap_next_id();

	if (coap_packet_init(&request, buffer, sizeof buffer, 1,
			     type,
			     COAP_UPLINK_TOKENLEN,
			     token,
			     code, id) ||
	    coap_packet_append_option(&request, COAP_OPTION_URI_PATH,
				      uri, strlen(uri)) ||
	    (format && coap_packet_append_option(&request,
						 COAP_OPTION_CONTENT_FORMAT,
						 format, sizeof(*format)))) {
		LOG_ERR("CoAP packet wrapping error");
		return -EINVAL;
	}
	if (payload == 0 && plsize == 0)
		return 0;

	if (coap_packet_append_payload_marker(&request) ||
	    coap_packet_append_payload(&request, payload, plsize)) {
		LOG_ERR("CoAP payload error");
		return -EINVAL;
	}
       return 0;

```
Evaluating with the snippet from above:
```
/* Header length : (version + type + tkl) + code + id + [token] */
token = 2
hdr_len = 1 + 1 + 2 + 2 = 6
opt_len = 5 
payload_len = max_len - hdr_len - opt_len;
payload_len = 768 - 6 - 5 = 757;
```
The offset is moving with every append, therefore this actual pyload length can be calculated as follows:
```
payload_len = cpkt->offset - cpkt->hdr_len - cpkt->opt_len - 1;
```

This is what I get on my log:
```
15:11:39.771551 -- CoAP --
15:11:39.771581 version: 1
15:11:39.771611    code: 2
15:11:39.783170      id: 0xA785
15:11:39.783268     tkn: 0xDDB6
15:11:39.783305 tkn_len: 2
15:11:39.783333  pl_len: 757
15:11:39.783362    type: NON
15:11:39.783390  method: coap post
[00:10:27.547,943] <dbg> tx_manager: tx coap
15:11:39.783460 52 02 a7 85 dd b6 b4 6d |R......m
15:11:39.783492 65 74 61 ff a1 12 78 1a |eta...x.
15:11:39.783521 31 2e 33 2e 30 2d 72 63 |1.3.0-rc
15:11:39.783555 32 2d 36 66 66 30 62 38 |2-6ff0b8
15:11:39.783588 30 30 30 39 2d 64 69 72 |0009-dir
15:11:39.783616 74 79                   |ty      
15:11:39.783648 -- END CoAP --
```

This is what I would expect:

```
15:11:39.771551 -- CoAP --
15:11:39.771581 version: 1
15:11:39.771611    code: 2
15:11:39.783170      id: 0xA785
15:11:39.783268     tkn: 0xDDB6
15:11:39.783305 tkn_len: 2
15:11:39.783333  pl_len: 30
15:11:39.783362    type: NON
15:11:39.783390  method: coap post
[00:10:27.547,943] <dbg> tx_manager: tx coap
15:11:39.783460 52 02 a7 85 dd b6 b4 6d |R......m
15:11:39.783492 65 74 61 ff a1 12 78 1a |eta...x.
15:11:39.783521 31 2e 33 2e 30 2d 72 63 |1.3.0-rc
15:11:39.783555 32 2d 36 66 66 30 62 38 |2-6ff0b8
15:11:39.783588 30 30 30 39 2d 64 69 72 |0009-dir
15:11:39.783616 74 79                   |ty      
15:11:39.783648 -- END CoAP --
```

**Environment:**
 - OS:Linux
 - zephyr v1.14.1

### PR DESCRIPTION
**Pull request by rlubos**
This PR inlcudes:
* small cleanup in the CoAP library along with a fix in `coap_packet_get_payload()` 
* small cleanup in LwM2M library, where `opt_len` field was used directly (which no longer is expected to include Payload Marker)
* extra checks in existing CoAP tests, to verify that internal fields in the CoAP packet struture are set correctly

Fixes #36739

### CODE REVIEW

**Comment by rlubos** [comment]
Note that changes in unit tests are not using `ztest` API to be consistent with the existing code base, there's a pending issue to convert entire test suite to `ztest`, I'll address this in a separate PR.

**Comment by rlubos** [comment]
FYI @efra-mx-aqua

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by efra-mx-aqua** [comment]
@rlubos I was just about submit a similar PR, hehehe, pretty much the same solution.

**Comment by rlubos** [comment]
> @rlubos I was just about submit a similar PR, hehehe, pretty much the same solution.

I strongly encourage to approve then

**Review by efra-mx-aqua — APPROVED** [review]
It looks good

**Review by pdgendt — APPROVED** [review]

**Pull request merged**
