### PR TITLE
[Backport v3.1-branch] Fix leaks with cloned packets

### LINKED ISSUE #48263: [v3.1-branch] net: net_bufs are leaked when net_pkt_shallow_clone() is used
**Describe the bug**

This issue is already fixed in main by the pr https://github.com/zephyrproject-rtos/zephyr/pull/45659

From the relevant commit message https://github.com/zephyrproject-rtos/zephyr/commit/f12f9d5e95a83af96d4f09b4c882de5581b78971:

> net: pkt: Fix leak when using shallow clone
>
> Currently a shallow clone of a packet will bump the reference count on
> all the fragments. The net_pkt_unref() function, however, only drops the
> reference count on the head fragment. Fix this by only bumping the ref
> count on the head buf during shallow clone.
>
> Only bumping the ref count of head is more in line with the idea that
> head buf is not responsible for the fragments of its child.
> 
> Signed-off-by: Andriy Gelman <andriy.gelman@gmail.com>

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport d67a13036878bee5f9c8de51f8b023d7f6a357fe~3..d67a13036878bee5f9c8de51f8b023d7f6a357fe from #45659

Fixes #48263

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Comment by talih0** [comment]
There's a typo in the commit message... sorry

> tests: net: Add test to detect leak in pkt shallow clone
> Checks that taking a shallow of a packet

should be
Checks that taking a shallow clone of a packet

LGTM otherwise

**Comment by chrta** [comment]
@rlubos Should i create an issue related to this pr and edit the pr description to contain the "fixes #..." so the "Backport Issue Check / Backport Issue Check (pull_request_target)" is green?

**Comment by rlubos** [comment]
> @rlubos Should i create an issue related to this pr and edit the pr description to contain the "fixes #..." so the "Backport Issue Check / Backport Issue Check (pull_request_target)" is green?

Please do so, I believe it is required to backport a bugfix.

**Review by chrta — APPROVED** [review]
Already using this code in a zephyr fork. This fixes the issue when routing between interfaces.

**Pull request merged**
