### PR TITLE
x86: pcie: fallback to config via PIO

### LINKED ISSUE #27339: up_squared: Zephyr does not boot via grub anymore
**Describe the bug**
Trying this https://docs.zephyrproject.org/latest/boards/x86/up_squared/doc/index.html#preparing-the-boot-device
Grub boots, but nothing appears on the console once zephyr has supposedly started.

**To Reproduce**
Just follow the link information

**Expected behavior**
the sample should print out something into the ftdi console

**Environment (please complete the following information):**
 - OS: Linux
- Board: UP squared

### LINKED ISSUE #27867: up_squared: couldn't get test result from serial of each test.
**Describe the bug**
for up_squared, when using zephyr.strip file and usb disk to run tests on this board, couldn't get test result from serial for each test.

the good commit is 4cf1832fa8, but for the latest, it's broken.

**To Reproduce**
1.  west build -b up_squared -p auto samples/hello_world/
2.  west flash ~/up_squared.sh
3.  see error

**Logs and console output**
there is nothing in the console, it seems that the test doesn't boot up.

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.4
 - CommitID: 6a8c622bcca

### PR DESCRIPTION
**Pull request by dcpleung**
When probing for PCI-E device resources, it is possible that
configuration via MMIO is not available. This may caused by
BIOS or its settings. So when CONFIG_PCIE_MMIO_CFG=y, have
a fallback path to config devices via PIO. The inability to
config via MMIO has been observed on a couple UP Squared
boards.

Fixes #27339

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — COMMENTED** [review]
This looks reasonable to me -- if z_acpi_find_table() fails, try PIO instead.

But I don't yet grok if this would fix https://github.com/zephyrproject-rtos/zephyr/issues/27867 since the bisect for that led to my paging code rewrite; you'd think it would never work if the culprit was being unable to probe.

Testing today on my Up Extreme board...

**Comment by dcpleung** [comment]
This doesn't fix #27867 when booting under EFI with MMIO_CFG turned on.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by chen-png** [comment]
tested it on up_squared, it didn't fix #27867.

**Comment by tbursztyka** [comment]
@dcpleung at least I get the boot banner on EFI boot which is an improvement as I did not get anything before (besides zefi print outs). You don't get it on you side?

**Review by tbursztyka — APPROVED** [review]

**Comment by dcpleung** [comment]
@tbursztyka there is nothing being printed if boots from GRUB before this patch. With this patch, I got the usual hello world message.

**Comment by dcpleung** [comment]
BTW, I am getting the usual printouts from `tests/arch/x86/info` on my board.

**Comment by andrewboie** [comment]
Let's get this in.

#27867 we are pretty sure is due to the ACPI code reading the RSDP in the first memory page, which my paging PR changed to be always marked non-present to catch NULL pointer dereferences. Adding a memory mapping call there should fix it.

**Pull request merged**
