### PR TITLE
release: 1.14.1: add list of fixed bugs

### PR DESCRIPTION
**Pull request by nashif**
Add list of all bugs addressed in this release.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by dbkinder — CHANGES_REQUESTED** [review]
Can we get these sorted by issue number?

**Comment by pabigot** [comment]
I think these backports are missing:
* #17955 - disk_sdhc: fixing the sending of commands with r1 response
* #18551 - C++: fix builds with non-Zephyr toolchain
* #19229 - drivers: spi_nor: fix writes across page boundaries

**Comment by nashif** [comment]
> I think these backports are missing:
> 
>     * #17955 - disk_sdhc: fixing the sending of commands with r1 response
> 

is there, #15444


>     * #18551 - C++: fix builds with non-Zephyr toolchain

This one is still open.

> 
>     * #19229 - drivers: spi_nor: fix writes across page boundaries

That one is missing indeed,  bug is 18935

**Comment by pabigot** [comment]
> > ```
> > * #18551 - C++: fix builds with non-Zephyr toolchain
> > ```
> 
> This one is still open.

Typo; meant 18552, the issue is #15603 which I've now closed.

**Comment by nashif** [comment]
> Typo; meant 18552, the issue is #15603 which I've now closed.

ok, need to add the pattern (close #XYZ) to the script to catch this, preferred way is:
```
Fixes #5730
```

**Review by dbkinder — APPROVED** [review]
LGTM, thanks

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
