### PR TITLE
docs: RTIO documentation updates

### PR DESCRIPTION
**Pull request by teburd**
Updates docs to account for the large number of changes that have occured since the initial documentation was written.

### CODE REVIEW

**Comment by teburd** [comment]
I can rebase this on top of what you've done in #60646 as this is maybe a bit more significant of a change

**Comment by teburd** [comment]
Related comment https://github.com/zephyrproject-rtos/zephyr/pull/57823#issuecomment-1644062892

**Review by yperess — APPROVED** [review]

**Comment by yperess** [comment]
> @yperess I can rebase this on top of what you've done in #60646 as this is maybe a bit more significant of a change

Sorry, I missed this when I did the other doc change. I'll close it.

**Review by kartben — APPROVED** [review]
Great, thanks! 
Not blocking but, since you already have an "Examples" section in there, I wonder if you should maybe add some wording to link to the sensor_batch_processing sample, just to make it even easier for folks to discover.

**Pull request merged**
