### PR TITLE
usb: add {get,set}_{vendor,product}_id

### PR DESCRIPTION
**Pull request by jmgao**
Add runtime getters/setters for the vendor and product ids that were
previously only configurable at build time via USB_DEVICE_{VID,PID}.

### CODE REVIEW

**Comment by finikorg** [comment]
What is the use case for the feature?

**Comment by jmgao** [comment]
The use case I have is to emulate a certain device (a Nintendo Switch controller) when I detect that I'm connected to a specific type of host, but there are other use cases that I know of that would benefit from being able to change these IDs at runtime (e.g. talking to a device that supports the [Android Open Accessory protocol](https://source.android.com/devices/accessories/aoa2#detecting-android-open-accessory-20-support), which identifies capabilities via product ID).

**Review by jfischer-no — CHANGES_REQUESTED** [review]
This patch does not respect device state and can not be accepted.
Also the reason for this patch did not really convinced me.

**Comment by jmgao** [comment]
Ok.

**Pull request closed without merging**
