### PR TITLE
Fix for TCP2 statemachine gets stuck in TCP_FIN_WAIT_2 state

### LINKED ISSUE #37842: TCP2 statemachine gets stuck in TCP_FIN_WAIT_2 state
**Describe the bug**
TCP2 statemachine gets stuck in TCP_FIN_WAIT_2 state (in tcp_in() function) when server responds with [ FIN, PSH, ACK ]. I think it is plausible that servers respond with these flags on a client side initiated close (I observed the problem with a device communicating with an AWS service). Therefore I think this is a bug. After some time the fin_timer runs out and tcp_fin_timeout() function is called. The final ACK to the server is never sent, which is not very clean.

**To Reproduce**
1. take an example which uses tcp sockets, make sure server responds with [FIN, PSH, ACK] on tcp connection termination.
2. trace network traffic with wireshark
3. client is never going to send final ACK specified in the TCP close sequence. (https://www.geeksforgeeks.org/tcp-connection-termination/) 
4. tcp_fin_timeout() is being called which should not be the case.

**Expected behavior**
[FIN, PSH, ACK] flags should be accepted in TCP_FIN_WAIT_2 and client (zephyr) sends final ACK frame to the server.

**Impact**
We are facing problems with tcp_fin_timeout (other problem) in our project that's why we've found this issue.

**Logs and console output**
zephyr_terminating_tcp_connection

**Environment (please complete the following information):**
 - Zephyr v2.6 branch
 - Server which terminates tcp connection with a frame with flags [FIN, PSH, ACK]

**Possible Fix ?**
Change tcp2 lines 1911 to 1922 like this:
```
	case TCP_FIN_WAIT_2:
		if (th && (FL(&fl, ==, FIN, th_seq(th) == conn->ack) ||
			   FL(&fl, ==, FIN | ACK, th_seq(th) == conn->ack) ||
			   FL(&fl, ==, FIN | PSH | ACK, th_seq(th) == conn->ack))) { // <----- this line fixed the problem for me
			/* Received FIN on FIN_WAIT_2, so cancel the timer */
			k_work_cancel_delayable(&conn->fin_timer);

			conn_ack(conn, + 1);
			tcp_out(conn, ACK);
			next = TCP_TIME_WAIT;
		}
		break;
```

### PR DESCRIPTION
**Pull request by nimarty**
Possible fix for issue: https://github.com/zephyrproject-rtos/zephyr/issues/37842

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
The fix looks good, you just need to adjust the commit message a bit so that checkpatch will pass.
Make it something like
```
net: tcp: accept [FIN, PSH, ACK] in TCP_FIN_WAIT_2 state

TCP state machine gets stuck in TCP_FIN_WAIT_2 state (in tcp_in() function)
when server responds with [ FIN, PSH, ACK ]

Fixes #37842
```
and add also `Signed-of-by` at the end of the message.

**Review by jukkar — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]

**Comment by nimarty** [comment]
These commit message compliance checks are crazy restrictive...

**Comment by nimarty** [comment]
Finally :)

**Review by rlubos — APPROVED** [review]
LGTM 👍

**Pull request merged**
