### PR TITLE
drivers: can: stm32fd: add clock source selection

### LINKED ISSUE #44985: tests: drivers: can: timing: failure to set bitrate of 800kbit/s on nucleo_g474re
**Describe the bug**
The `drivers/can/can_stm32fd.c` uses the PCLK clock as clock source for the FDCAN IP. This clock is 170MHz, at least on the nucleo_g474re board. This prevents the use of the CAN in Automation (CiA) standard bitrate of 800kbit/s (170000000/(n * 800000) is not an integer).

**To Reproduce**
1. west build -b nucleo_g474re tests/drivers/can/timing/
2. west flash
3. See error

**Expected behavior**
CAN in Automation standard bitrates can be met.

**Impact**
CAN in Automation standard bitrates cannot be met, causing the CAN timing tests to fail.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-2817-g536e06118159  ***
testing on device CAN_1
Running test suite can_timing_tests
===================================================================
START - test_set_timing_min
 PASS - test_set_timing_min in 0.1 seconds
===================================================================
START - test_set_timing_max
 PASS - test_set_timing_max in 0.1 seconds
===================================================================
START - test_timing
testing bitrate 20000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 217, phase_seg2 = 32, prescaler = 34 OK, sample point error 0.3%
testing bitrate 50000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 174, phase_seg2 = 25, prescaler = 17 OK, sample point error 0.0%
testing bitrate 125000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 237, phase_seg2 = 34, prescaler = 5 OK, sample point error 0.0%
testing bitrate 250000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 118, phase_seg2 = 17, prescaler = 5 OK, sample point error 0.0%
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 147, phase_seg2 = 22, prescaler = 2 OK, sample point error 0.5%
testing bitrate 800000, sample point 80.0% (valid): 
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/can/timing/src/main.c:194: test_timing_values: (sp_err >= 0 is false)
unknown error -22
 FAIL - test_timing in 0.80 seconds
===================================================================
START - test_timing_data
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 28, phase_seg2 = 5, prescaler = 10 OK, sample point error 2.3%
testing bitrate 1000000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 28, phase_seg2 = 5, prescaler = 5 OK, sample point error 2.3%
testing bitrate 500000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 17, phase_seg2 = 2, prescaler = 17 OK, sample point error 0.0%
testing bitrate 500000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 15, phase_seg2 = 4, prescaler = 17 OK, sample point error 0.0%
testing bitrate 500000, sample point 100.0% (invalid): OK
testing bitrate 8000001, sample point 75.0% (invalid): OK
 PASS - test_timing_data in 0.60 seconds
===================================================================
Test suite can_timing_tests failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS
 - Toolchain: Zephyr SDK v0.14.0
 - Commit SHA: 536e061181599c94e19991cf4550336d1ec2cbb4

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
- Print the CAN core clock frequency along with the device name to aid in debugging CAN timing test case errors.
- Add support for selecting the CAN clock source. Change previously hardcoded value of PCLK1 to HSE.
- Rename `CONFIG_CAN_STM32_CLOCK_DIVISOR` to `CONFIG_CAN_STM32FD_CLOCK_DIVISOR` to match driver Kconfig name.

Fixes: #44985

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
```
*** Booting Zephyr OS build zephyr-v3.0.0-2820-g61aa93a2db93  ***
testing on device CAN_1 @ 24000000 Hz
Running test suite can_timing_tests
===================================================================
START - test_set_timing_min
 PASS - test_set_timing_min in 0.1 seconds
===================================================================
START - test_set_timing_max
 PASS - test_set_timing_max in 0.1 seconds
===================================================================
START - test_timing
testing bitrate 20000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 209, phase_seg2 = 30, prescaler = 5 OK, sample point error 0.0%
testing bitrate 50000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 209, phase_seg2 = 30, prescaler = 2 OK, sample point error 0.0%
testing bitrate 125000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 167, phase_seg2 = 24, prescaler = 1 OK, sample point error 0.0%
testing bitrate 250000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 83, phase_seg2 = 12, prescaler = 1 OK, sample point error 0.0%
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 41, phase_seg2 = 6, prescaler = 1 OK, sample point error 0.0%
testing bitrate 800000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 23, phase_seg2 = 6, prescaler = 1 OK, sample point error 0.0%
testing bitrate 1000000, sample point 75.0% (valid): prop_seg = 0, phase_seg1 = 17, phase_seg2 = 6, prescaler = 1 OK, sample point error 0.0%
testing bitrate 125000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 171, phase_seg2 = 20, prescaler = 1 OK, sample point error 0.5%
testing bitrate 125000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 152, phase_seg2 = 39, prescaler = 1 OK, sample point error 0.4%
testing bitrate 125000, sample point 100.0% (invalid): OK
testing bitrate 8000001, sample point 75.0% (invalid): OK
 PASS - test_timing in 0.123 seconds
===================================================================
START - test_timing_data
testing bitrate 500000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 20, phase_seg2 = 3, prescaler = 2 OK, sample point error 0.0%
testing bitrate 1000000, sample point 87.5% (valid): prop_seg = 0, phase_seg1 = 20, phase_seg2 = 3, prescaler = 1 OK, sample point error 0.0%
testing bitrate 500000, sample point 90.0% (valid): prop_seg = 0, phase_seg1 = 20, phase_seg2 = 3, prescaler = 2 OK, sample point error 2.5%
testing bitrate 500000, sample point 80.0% (valid): prop_seg = 0, phase_seg1 = 18, phase_seg2 = 5, prescaler = 2 OK, sample point error 0.9%
testing bitrate 500000, sample point 100.0% (invalid): OK
testing bitrate 8000001, sample point 75.0% (invalid): OK
 PASS - test_timing_data in 0.60 seconds
===================================================================
Test suite can_timing_tests succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL

```

**Review by martinjaeger — COMMENTED** [review]
I realize this PR mainly intends to fix a bug. However, it introduces quite a few new Kconfigs related to clock control.

After the initial version of the STM32 CAN-FD driver (where this code section originates from) was merged, the STM32 clock control was moved to Devicetree.

Should we not move the CAN clock source selection to Devicetree as well?

**Comment by henrikbrixandersen** [comment]
> Should we not move the CAN clock source selection to Devicetree as well?

I will look into that going forward, but it's a bit complicated as the clock settings are not per-instance, but for all FDCAN instances.

**Review by erwango — APPROVED** [review]
Hopefully soon replaced by https://github.com/zephyrproject-rtos/zephyr/pull/42097 (and derivates), but ok for now.

**Review by martinjaeger — APPROVED** [review]

**Pull request merged**
