### PR TITLE
soc: silabs: Facilitate non-Gecko SoC support

### PR DESCRIPTION
**Pull request by rettichschnidi**
This is the result of rebasing #64209 on the most recent main.

Putting those commits in a separate PR because I think it is the right thing to do, regardless of the SiM3U support.

### CODE REVIEW

**Comment by jerome-pouiller** [comment]
Hello @rettichschnidi,

I understand your point however, I have some concern with "gecko" naming. Currently, "gecko" include series 0, 1 and 2. However, future series 3 won't use "gecko" branding. In addition, series 0 and 1 are going to be deprecated by upstream. So, my initial goal was to get rid of "gecko" name because [it is going to become confusing][1].

One idea would be use `efr32` instead of `gecko`. Unfortunately, this code also supports `efm32` (same features than `efr32`, but without Radio).

Otherwise, since `SOC_VENDOR_SILABS` does not appear to frequently in the code, maybe we could just replace it by `SOC_FAMILY_SILABS_S0 || SOC_FAMILY_SILABS_S1 || SOC_FAMILY_SILABS_S2`. This is not super fancy, but I believe it reflects the truth.

For `common/`, I feel we could resolve the dependencies directly from `common/CMakelists.txt` (`soc_power.c` and `soc_power_pmgr.c`, soc.c has so many `#ifdef` I wonder if it make sense to share it, `SOC_LINKER_SCRIPT` can be shared with `sim3u`).

What is your thoughts?

[1]: https://quotesondesign.com/phil-karlton/

**Comment by rettichschnidi** [comment]
> I understand your point however, I have some concern with "gecko" naming. Currently, "gecko" include series 0, 1 and 2. However, future series 3 won't use "gecko" branding. In addition, series 0 and 1 are going to be deprecated by upstream. 

Out of curiosity: What does deprecated buy upstream mean? Is there an issue for this?

> Otherwise, since `SOC_VENDOR_SILABS` does not appear to frequently in the code, maybe we could just replace it by `SOC_FAMILY_SILABS_S0 || SOC_FAMILY_SILABS_S1 || SOC_FAMILY_SILABS_S2`. This is not super fancy, but I believe it reflects the truth.

👍

> For `common/`, I feel we could resolve the dependencies directly from `common/CMakelists.txt` (`soc_power.c` and `soc_power_pmgr.c`, soc.c has so many `#ifdef` I wonder if it make sense to share it, `SOC_LINKER_SCRIPT` can be shared with `sim3u`).

👍

> What is your thoughts?

Will give this a try, and update this PR then.

**Comment by jerome-pouiller** [comment]
> > I understand your point however, I have some concern with "gecko" naming. Currently, "gecko" include series 0, 1 and 2. However, future series 3 won't use "gecko" branding. In addition, series 0 and 1 are going to be deprecated by upstream.
> 
> Out of curiosity: What does deprecated buy upstream mean? Is there an issue for this?

Maybe *deprecated* is not the right word. If I understand right, series 0/1 will not new features. Thus, code for series 0/1 may diverge from the code for series 2+. However, Zephyr mostly imports low level driver that doesn't change so much. So, the impact for Zephyr is still a bit unclear. Let's just be prepared to support series 0/1 and series 2+ separately.

**Comment by alexanderwachter** [comment]
Dismissed my assignment. I'm absolutely not familiar with silabs.

**Comment by rettichschnidi** [comment]
@jerome-pouiller Updated the PR. Better?

**Review by jerome-pouiller — APPROVED** [review]
Fine for me.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
