### PR TITLE
tests: Misc test fixes for fvp_base_revc_2xaemv8a

### LINKED ISSUE #45111: fvp_base_revc_2xaemv8a: multiple test failures
**Describe the bug**

Multiple tests fail for `fvp_base_revc_2xaemv8a`.

* fvp_base_revc_2xaemv8a: [3 failures](https://gist.github.com/stephanosio/8393439c0c7f85837034130f73ef8595)
    * [tests/ztest/error_hook/testing.ztest.error_hook: Failed](https://gist.github.com/stephanosio/8393439c0c7f85837034130f73ef8595#file-gistfile1-txt-L7)
    * [tests/kernel/mem_protect/mem_map/kernel.memory_protection.mem_map: Timeout](https://gist.github.com/stephanosio/8393439c0c7f85837034130f73ef8595#file-gistfile1-txt-L109)
    * [tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls: Timeout](https://gist.github.com/stephanosio/8393439c0c7f85837034130f73ef8595#file-gistfile1-txt-L753)

**To Reproduce**

```
scripts/twister -v -N --inline-logs -p fvp_base_revc_2xaemv8a
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK 0.14.1
 - Commit SHA: 4842d94f17e7

**Additional context**

See https://github.com/zephyrproject-rtos/zephyr/issues/43852#issuecomment-1107855478

### PR DESCRIPTION
**Pull request by carlocaione**
Fix several tests for the `fvp_base_revc_2xaemv8a` board.

See https://github.com/zephyrproject-rtos/zephyr/issues/43852#issuecomment-1107855478 

Fixes #45111

### CODE REVIEW

**Review by stephanosio — COMMENTED** [review]
I can confirm that this fixes `tests/ztest/error_hook/testing.ztest.error_hook` and `tests/kernel/mem_protect/mem_map/kernel.memory_protection.mem_map`, but `tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls` still fails for me.

Is this supposed to fix all of the failures mentioned in #45111?

UPDATE: `tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls` does not fail. It just takes longer than 60 seconds (almost 120 seconds) on my local machine. We should update the timeout for this test to a higher value.

**Comment by carlocaione** [comment]
> Is this supposed to fix all of the failures mentioned in #45111?

Yes, and for me it passes with 30s timeout. I increased that to 120s now as suggested.

**Comment by stephanosio** [comment]
> Yes, and for me it passes with 30s timeout. I increased that to 120s now as suggested.

I meant the twister timeout. The in-test timeout of 30s is working for me too.

```diff
diff --git a/tests/kernel/mem_protect/syscalls/testcase.yaml b/tests/kernel/mem_protect/syscalls/testcase.yaml
index ac40693175..2ef11e89af 100644
--- a/tests/kernel/mem_protect/syscalls/testcase.yaml
+++ b/tests/kernel/mem_protect/syscalls/testcase.yaml
@@ -5,3 +5,4 @@ tests:
     # FIXME: This test may fail for qemu_arc_em on certain host systems.
     #        See foss-for-synopsys-dwc-arc-processors/qemu#66.
     platform_exclude: qemu_arc_em
+    timeout: 180
```

**Comment by carlocaione** [comment]
> I meant the twister timeout. The in-test timeout of 30s is working for me too.

right :) added the twister timeout.

**Review by stephanosio — APPROVED** [review]

**Review by povergoing — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
