### PR TITLE
net: sockets should select dns Kconfig

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Used by getaddrinfo().

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by pfalcon** [comment]
Yes, but getaddrinfo() isn't exactly mandatory part of sockets API, a particular app doesn't have to use it. And I'm sure if DNS_RESOLVER is selected, DNS code won't be linked away even if not used.

**Comment by andrewboie** [comment]
> Yes, but getaddrinfo() isn't exactly mandatory part of sockets API, a particular app doesn't have to use it. And I'm sure if DNS_RESOLVER is selected, DNS code won't be linked away even if not used.

When system calls are implemented the build breaks because getaddrinfo() ends up in the system call table and there is no DNS implementation to support it. The only thing saving us from this issue previously was gc-sections:

```
libzephyr.a(getaddrinfo.c.obj): In function `dns_get_addr_info':
/home/apboie/projects/zephyr/include/net/dns_resolve.h:329: undefined reference to `dns_resolve_get_default'
/home/apboie/projects/zephyr/include/net/dns_resolve.h:329: undefined reference to `dns_resolve_name'
/home/apboie/projects/zephyr/include/net/dns_resolve.h:329: undefined reference to `dns_resolve_get_default'
/home/apboie/projects/zephyr/include/net/dns_resolve.h:329: undefined reference to `dns_resolve_name'
collect2: error: ld returned 1 exit status
```

**Comment by pfalcon** [comment]
Ok, why not do it the other way around: if CONFIG_DNS_RESOLVER is not defined, don't compile in getaddrinfo() (compile dummy which always returns error)?

**Comment by andrewboie** [comment]
Is there some specific advantage to the alternate approach?

**Comment by pfalcon** [comment]
> Is there some specific advantage to the alternate approach?

As I mentioned, not all socket applications require getaddrinfo. I'd like to avoid association sockets == bloat. It's pretty hard to optimize these things afterwards (when they accumulate in multiples), especially if it may be a "breaky" change requiring users to patch their configs. It makes sense to think it out beforehand and keep it all finegrained and configurable. If you're busy with other things, I can prepare a patch tomorrow.

**Comment by andrewboie** [comment]
>  If you're busy with other things, I can prepare a patch tomorrow.

Sure, thanks

**Review by pfalcon — CHANGES_REQUESTED** [review]
Per the discussion, submitted alternative patch which doesn't force DNS resolver for sockets, leaving its control to a user: https://github.com/zephyrproject-rtos/zephyr/pull/9050

**Pull request closed without merging**
