### PR TITLE
Custom formatting in printk

### PR DESCRIPTION
**Pull request by nordic-krch**
PR presents a demo which shows how custom formatting could be added to printk. It allows extending formatting (e.g. bluetooth address) without modifying printk module.

The idea has been going back and forth started by @jhedberg (https://github.com/zephyrproject-rtos/zephyr/pull/16819#discussion_r293681721) but i wanted to keep printk unspoiled allowing for external extensions.

When user wants to format data in specific way, he must provide data and function which can format it. A memory object with data and function pointer is created (in case of logger it will be allocated from logger memory pool) and pointer to that object is passed as the parameter with`%pZ` format specifier. Printk then reads function pointer from memory object and calls to this function passing memory object and `out_char` function.

When this approach is applied to the logger that will provide couple of improvements, mainly:
- less ram memory used since only data is stored and not stringified version of data (e.g. 7 bytes of ble address instead of  ~25 bytes of address string).
- no need for strdup buffer pool. Single buffer pool used for log messages and memory objects
- improved performance - converting data to string is done when log is processed and not when called

Solution is based on new data object which I called memory object (`memobj`). It is capable of storing variable length data in fragmented chunks (allocated from mem_slab). It favors memory usage efficiency over memory access time (access must happen through API).

Modified `hello world` shows how new feature can be used.

`printk("BLE addr %pZ", bt_le_addr_dup(&addr)`

where `bt_le_addr_dup` provides function capable of BLE address formatting (`format_bt_addr_le_t`):
```
void *bt_le_addr_dup(const bt_addr_le_t *addr)
{
	return mem_dup((u8_t *)addr, sizeof(bt_addr_le_t), format_bt_addr_le_t);
}
```

### CODE REVIEW

**Comment by jukkar** [comment]
Could we support similar format specifiers as what Linux is using? (of course not all are applicable for Zephyr)

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/core-api/printk-formats.rst

**Comment by nordic-krch** [comment]
@jukkar my idea was a bit different. To not extend vprintf function but keep it as is with one specifier (currently `%pZ`) which allows custom formatting. Function for formatting is implemented in the subsystem that needs the formatting, e.g. ble address formatting function is in Bluetooth subsystem.

If you think about sharing code between linux and zephyr then that would need to be reconsidered.

**Comment by jukkar** [comment]
> @jukkar my idea was a bit different. To not extend vprintf function but keep it as is with one specifier (currently `%pZ`) which allows custom formatting. Function for formatting is implemented in the subsystem that needs the formatting, e.g. ble address formatting function is in Bluetooth subsystem.

I was thinking this a bit differently. I think the generic modifiers like for MAC address %pM could be made available for all subsystems (at least for networking and Bluetooth could use these).
If the subsystem would need some specific stuff to be printed, then the %pZ... could be used for that purposes (to extend the standard modifiers).

> If you think about sharing code between linux and zephyr then that would need to be reconsidered.

I was not thinking about that. We probably cannot take the code anyway because of the license issues.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
I feel fairly strongly we should not go in this direction.

The advantages of this approach were stated as:

>    less ram memory used since only data is stored and not stringified version of data (e.g. 7 bytes of ble address instead of ~25 bytes of address string).
>    no need for strdup buffer pool. Single buffer pool used for log messages and memory objects
>   improved performance - converting data to string is done when log is processed and not when called

However I think this PR loses sight of what we want high performance logging to eventually be. We want high performance logging to not do any runtime stringification of any data at all. As discussed in #18147, we want to strip all the format strings out of the binary, and for any event just log a pointer and any additonal arguments supplied, which must be either integral values or pointers to strings in ROM. Trying to implement this for backends which are going to stringify stuff at runtime is a waste of time.

In an environment where all the format strings are not available at runtime, there is *no* reliable way to determine whether a value passed in is an object whose contents need to be dereferenced and dumped out to the log stream, or a value which simply needs to be written. The technique proposed to compare the value to the range of addresses representing the buffer pool is not reliable, and probably represents a security concern if we are trying to log from user mode.

If you want to log a binary object to the log stream, we need distinct macros for this. One which can take *any* object pointer along with a size, and will handle copying the data into a buffer and then write the data out to the backend in raw form. Another one specifically for null terminated C strings.

So my counter-proposal is an API:

```
log_object("BLE addr", &addr, sizeof(addr));
```

Which just writes the data directly to the stream, in hexdump form if the backend is text and not binary. You can turn it into something human readable in postprocessing. I would not necessarily object to having a system of format codes:

```
log_object("BLE addr", "%pZ", &addr, sizeof(addr));
```

Which are only used during postprocessing to identify the data type in an automated fashion, but **at runtime we *MUST* be working with pointer/size pairs and not just pointers and variadic functions. Otherwise this is fundamentally unsafe.**

**Comment by nordic-krch** [comment]
@andrewboie 

> However I think this PR loses sight of what we want high performance logging to eventually be.

That's true because when PR was created this requirement was not on a table.

> log_object("BLE addr", &addr, sizeof(addr));

That would work but i'm afraid is not that user friendly and it implies that some things are log differently than another. Let consider case when user wants to log number of received bytes from given address. Traditionally it would look like:
```
LOG("received %d bytes from %s", n, addr_to_str(addr))
```
with custom formatter it would look like:
```
LOG("received %d bytes from %pZ", n, log_addr_dup(addr))
```
with in place address logging proposed in https://github.com/zephyrproject-rtos/zephyr/issues/18147#issuecomment-519862992 it would look like:
```
LOG("received %d bytes from" ADDR_FSPEC, n, ADDR_STRARG(addr))
```
with you proposal (if i understood correctly) it would look like:
```
LOG("received %d bytes from" n);
log_object("addr", &addr, sizeof(addr));
```

> The technique proposed to compare the value to the range of addresses representing the buffer pool is not reliable, and probably represents a security concern if we are trying to log from user mode.

Yes, that is a security concern especially with no access to the format string. However, I was thinking that it is doable to rework log macros so that allocated object could get a reference to the log message it was created for something like:
```
#define LOG(str, ...) \
    log_msg *_logger_msg = alloc(cnt_args(__VA_ARGS__); \
    create_msg(msg, __VA_ARGS__)

#define LOG_OBJ(ptr, func) \
    obj *o = alloc(); \
    o.func = func; \
    o.ref = _logger_msg; \
    ....
```
if log message arguments are evaluated after message is allocated (cnt_args does not evaluate arguments) then macro used as an argument has access to message address which can be stored in the object. Then when logger is freed and candidate for object is found it can be checked if it is allocated and hold reference to that message. Maybe there is a better way to create a reference that will allow to determine it exclusively. This is just a proposal.

**Pull request closed without merging**
