### PR TITLE
Net-app API removal

### PR DESCRIPTION
**Pull request by jukkar**
This PR removes the net-app API. The PR #9832 should be merged first before this one.

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]

**Comment by jukkar** [comment]
> How to understand that? It's not the case that this PR is merged, while #9832 isn't, as the tenses used imply.

This is to be understood so that the #9832 needs to be merged first before this can be merged. The sanitychecker will fail currently for this one as lwm2m code is still using net-app in master.

**Comment by pfalcon** [comment]
> This is to be understood so that the #9832 needs to be merged first before this can be merged.

I fixed grammar usage if you don't mind. Leaving adding DNM label to yourself though.

**Comment by jukkar** [comment]
> Leaving adding DNM label to yourself though.

No need for DNM in this case, this is to be merged right after the lwm2m socket code is merged and sanity passes.

**Review by dbkinder — DISMISSED** [review]
deleting net-app-api.rst means you'll need to remove the reference to it in subsystems/networking/networking.rst  (the doc build will complain about this when the CI process finishes)

**Comment by jukkar** [comment]
New version after lwm2m was updated. This one also removes net-app from the documentation.

**Comment by mike-scott** [comment]
@jukkar all clear on my end.

I'll miss the IRC sample :/

**Review by mike-scott — APPROVED** [review]

**Comment by tbursztyka** [comment]
@mike-scott It will be easier to redo it with socket actually, if you are interested ;)

**Comment by mike-scott** [comment]
@tbursztyka I had considered converting it.  Maybe I'll take a look tomorrow.  My Zephyr time is a bit limited atm.

**Review by rveerama1 — APPROVED** [review]

**Pull request merged**
