### PR TITLE
ev11l78a: configure DAC peripheral

### PR DESCRIPTION
**Pull request by Flameeyes**
ev11l78a: configure DAC peripheral

This configures the DAC in the same way as it is configured for the
arduino_zero and other similar boards.

It also includes the board in the DAC tests.

Signed-off-by: Diego Elio Pettenò <flameeyes@meta.com>

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/zephyrproject-rtos/zephyr/pull/62478).
* #61740
* __->__ #62478
* #61797

### CODE REVIEW

**Review by martinjaeger — CHANGES_REQUESTED** [review]
The first two commits don't seem to be related or required for the DAC. If that's tje case, please remove them from this PR.

Otherwise looks good.

**Comment by nandojve** [comment]
You need rebase : )

**Comment by nandojve** [comment]
Ping

**Comment by Flameeyes** [comment]
Rebased, This still include the commit from #61797 because of how Sapling handles the stack — there's a ReviewStack UI that wraps around the pull request, otherwise feel free to wait for the review until the dependent change is merged.

**Comment by nandojve** [comment]
Hi @Flameeyes ,

The #61797 got in.

**Pull request closed without merging**
