### PR TITLE
[WIP] drivers: adc: add adc driver support for STM32

### PR DESCRIPTION
**Pull request by cybertale**
These series of commits is planning for adding ADC driver support for STM32 series soc, this first commit is for adding basic dts support.
Also for solving the issue #10896.

Signed-off-by: Song Qiang <songqiang1304521@gmail.com>

### CODE REVIEW

**Comment by erwango** [comment]
^^ @ekarlso

**Comment by ekarlso** [comment]
@cybertale I already have some code, should we collaborate?

**Comment by cybertale** [comment]
Hi @ekarlso, that would be great! I just wrote some skeloton code and hadn't test them. If you already have some code that's working then we won't need to start from beginning!

**Comment by cybertale** [comment]
I invited you as a collaborator, feel free to commit so we can talk about the code! :)

**Comment by ekarlso** [comment]
@cybertale are you on Slack and if not would you mind joining ?

**Comment by ekarlso** [comment]
new code pushed to https://github.com/ekarlso/zephyr/tree/stm32-adc

**Comment by cybertale** [comment]
Hi @ekarlso , very sorry for the late reply, I got a serious flue and didn't touch the computer for several days. Of course joining slack is good! How do I join your channels?

**Comment by ekarlso** [comment]
@cybertale You need to join the zephyr projects slack channels, you will be autojoined to the #general channels.

**Comment by cybertale** [comment]
Development moves to #13447 so this PR is closed.

**Pull request closed without merging**
