### PR TITLE
drivers: sensor: bme680: delete un-reach code

### PR DESCRIPTION
**Pull request by DavidLin1577**
deleted can not reach code '	return 0;' 。
Signed-off-by: David Lin <linpeng1577@gmail.com>

### CODE REVIEW

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Thanks for the patch @DavidLin1577 !

The code changes look good, but please amend your commit to fix the gitlint and identity/emails failures.

**Comment by DavidLin1577** [comment]
Deleted can not reach code '	return 0;' 。
Signed-off-by: DavidLinux1577 linpeng1577@gmail.com

**Comment by DavidLin1577** [comment]
> **Some checks failed. Please fix and resubmit.**
> 
> ## Gitlint issues
> 1: UC2 Body does not contain a 'Signed-off-by:' line
> 1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Update bme680.c"
> 3: UC4 Line exceeds max length (94>72): "1. delete can not reach code '	return 0;' in function 'bme680_reg_read' and 'bme680_reg_write'"
> 
> ## Identity/Emails issues
> 7f44b58f0bd5528eac0a0abcd8c3c4647d4164f4: author email (LinPeng [linpeng1577@gmail.com](mailto:linpeng1577@gmail.com)) needs to match one of the signed-off-by entries.
> 7f44b58f0bd5528eac0a0abcd8c3c4647d4164f4: author email (LinPeng [linpeng1577@gmail.com](mailto:linpeng1577@gmail.com)) does not follow the syntax: First Last .
> 
> _Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages._

**Review by DavidLin1577 — COMMENTED** [review]
**drivers: sensor: bme680: delete un-reach code**
Deleted can not reach code '	return 0;' 。
Signed-off-by: David Lin <linpeng1577@gmail.com>

**Review by DavidLin1577 — COMMENTED** [review]
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the
    best of my knowledge, is covered under an appropriate open
    source license and I have the right under that license to
    submit that work with modifications, whether created in whole
    or in part by me, under the same open source license (unless
    I am permitted to submit under a different license), as
    Indicated in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including
    all personal information I submit with it, including my
    sign-off) is maintained indefinitely and may be redistributed
    consistent with this project or the open source license(s)
    involved.

Signed-off-by: David Lin <linpeng1577@gmail.com>

**Review by DavidLin1577 — COMMENTED** [review]
**drivers: sensor: bme680: delete un-reach code**
deleted can not reach code '	return 0;' 。
Signed-off-by: David Lin <linpeng1577@gmail.com>

**Comment by MaureenHelm** [comment]
Please squash your changes locally into one commit, then force push the branch to your GitHub remote. See the [Contribution Workflow](https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow) for more details.

**Comment by DavidLin1577** [comment]
OK，thanks linpeng1577 邮箱：linpeng1577@gmail.com 签名由 网易邮箱大师 定制 On 01/22/2020 06:56, Maureen Helm wrote: Please squash your changes locally into one commit, then force push the branch to your GitHub remote. See the Contribution Workflow for more details. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request closed without merging**
