### PR TITLE
subsys: console: Refactor code to allow per-UART "tty" wrapper

### PR DESCRIPTION
**Pull request by pfalcon**
Instead of having just one static "UART console" device, allow to
instantiate buffered, interrupt-driven POSIX-like "tty" wrapper for
any underlying device. Then, use this functionality to provide
compatible "console API".

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
Inspired by https://github.com/zephyrproject-rtos/zephyr/pull/6344#issuecomment-405202826. Depends on https://github.com/zephyrproject-rtos/zephyr/pull/8951 .

@andrewboie : This is next steps based on our conversation re: evolution of "console" approach. But as you can see, this next step isn't even adding read()/write() calls! It's generalizing "console" subsystem to be "tty" subsystem, to be applicable to more than one underlying UART device. Just of such tty devices will be "a console" (and not only a tty device can be a console of course).

Re: naming. I initially named the thing "buffered serial", trying to give it "modern, clearer name". But it went only longer and hardly clearer. Everyone knows what this thing is - ol' good tty. So a did search-and-replace on it before submitting.

**Comment by pfalcon** [comment]
recheck

**Review by tyrantlizard77 — COMMENTED** [review]
LGTM
However this does change a public API, any possibility to declare a new one for serial subsystem and deprecate the old?

**Comment by pfalcon** [comment]
This PR now includes https://github.com/zephyrproject-rtos/zephyr/pull/8951, in which it depends, to make CI pass.

**Comment by pfalcon** [comment]
@andrewboie 

> LGTM
However this does change a public API, any possibility to declare a new one for serial subsystem and deprecate the old?

The main change of this PR, "subsys: console: Refactor code to allow per-UART "tty" wrapper", actually specifically does not change API of the console subsys. I may imagine you had a look at the PR already with https://github.com/zephyrproject-rtos/zephyr/pull/8951 included (initially only the "subsys: console" commit was part of the PR, but that of course failed CI, so I had to pull in dependency to show that CI passes).

(With that in mind, we both know that API of console subsys will have to change, it just takes time and consideration to arrive at the final API, so doing it step by step makes sense.)

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by pfalcon** [comment]
This was rebased to fix merge conflict after recent merges. Passes CI, approved. @nashif: Ping.

**Review by jakub-uC — APPROVED** [review]

**Pull request merged**
