### PR TITLE
[Backport v1.14-branch] Settings: Fix incorrect return of -EINVAL for deleted entries

### PR DESCRIPTION
**Pull request by nvlsianpu**
Backport #17446 to v1.14 branch

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@nwsetec

**Review by nwsetec — APPROVED** [review]

**Comment by nwsetec** [comment]
Thanks @nvlsianpu!

**Comment by nwsetec** [comment]
Hi @carlescufi can this be merged for 1.14.1?

**Comment by carlescufi** [comment]
@nwsetec yes, this is trivial, I can merge it now

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
