### PR TITLE
doc: new look and feel

### PR DESCRIPTION
**Pull request by gmarull**
A new look and feel for the Zephyr documentation. It is largely based on the work done by Godot Engine docs, but with some Zephyr specific customizations. Feedback on style issues/tweaks are welcome.

Current PR build can be viewed here: https://teslabs.github.io/zephyr-docs-test/

image

image

Part of #33127

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
*enthusiastic applause*

**Comment by carlocaione** [comment]
Can the width of the page be a bit more "adaptive"? On 3840x2160 the page is way too narrow.
Screenshot from 2021-03-13 14-02-23

**Review by nashif — CHANGES_REQUESTED** [review]
- need to move back to variable width, right now it is fixed
- try to keep the colors consistent with what we have on www.zephyrproject.org. 
- drop the gradient color or keep it close to what we have on www.zephyrproject.org

**Comment by gmarull** [comment]
@nashif 

> * need to move back to variable width, right now it is fixed

IMO fixed width documents are more readable. In the end they behave as an actual document (PDF, book...). As of today Zephyr docs on wide displays (e.g. UWD, my case) require wide-angle eye motion (bad) unless you make the window size small enough. We can add an extra media query for large displays (i.e. a bit wider for big displays, would solve @carlocaione complain).

image
_Zephyr docs on UWD as of today_

> * try to keep the colors consistent with what we have on [www.zephyrproject.org](http://www.zephyrproject.org).

Can you specify which colors? I've tried to use many of the options given in the Zephyr guidelines. One thing that I have tried is using blue for sidebar, but then purple accent color can't be used (poor contrast), even logo would need some tweaks like glow or shadow. Summarizing, please provide some guidance here, e.g. drop purple from sidebar and make it blue based?

image

> * drop the gradient color or keep it close to what we have on [www.zephyrproject.org](http://www.zephyrproject.org)

Fixed.

image

**Comment by mbolivar-nordic** [comment]
> IMO fixed width documents are more readable. In the end they behave as an actual document (PDF, book...). As of today Zephyr docs on wide displays (e.g. UWD, my case) require wide-angle eye motion (bad) unless you make the window size small enough.

+1

**Comment by laurenmurphyx64** [comment]
Maybe the option would be distracting to others or doesn't fit on the page, but I think it would be nice to have the ability to select dark / light mode. I'm on Ubuntu 18 so (as far as I know) Chrome isn't picking up the dark / light mode from my system correctly.

**Comment by gmarull** [comment]
@laurenmurphyx64 it seems to be possible, I'll give it a try https://web.dev/prefers-color-scheme/#dark-mode-but-add-an-opt-out

**Review by carlescufi — APPROVED** [review]
I am fine with fixed width as long as it's reasonably sized based on screen width. Regarding the other changes, it was about time we gave this website a visual update!
Thanks @gmarull for putting this together.

**Comment by carlescufi** [comment]
> * need to move back to variable width, right now it is fixed

My vote goes to switch to fixed width, but align to the left:

image

**Comment by carlocaione** [comment]
I must admit that I don't fully understand the choice of a fixed width. People buys 4k or ultra-wide monitors to be able to have more content on the screen without a constant scrolling. Forcing a fixed width is basically preventing that. Can we at least have a proportional width with an upper threshold maybe?

**Comment by nashif** [comment]
> IMO fixed width documents are more readable.

I am fine with fixed in general, we just need to go through the docs and make sure any pictures or tables we have are aligned correctly. Look at https://teslabs.github.io/zephyr-docs-test/guides/coding_guidelines/index.html?highlight=coding%20guideline#main-rules for example.

> As of today Zephyr docs on wide displays (e.g. UWD, my case) require wide-angle eye motion (bad) unless you make the window size small enough.

Just make the browser window match your preferences? Who does have a full screen browser on a wide screen anyways...

**Comment by gmarull** [comment]
> I must admit that I don't fully understand the choice of a fixed width. People buy 4k or ultra-wide monitors to be able to have more content on the screen without a constant scrolling. Forcing a fixed width is basically preventing that. Can we at least have a proportional width with an upper threshold maybe?

I think 4K or UW monitors are useful when tiling windows/editor tabs (this is what I do).

> > IMO fixed width documents are more readable.
> 
> I am fine with fixed in general, we just need to go through the docs and make sure any pictures or tables we have are aligned correctly. Look at https://teslabs.github.io/zephyr-docs-test/guides/coding_guidelines/index.html?highlight=coding%20guideline#main-rules for example.
> 

We may make the page a bit wider to cover these cases, some others can likely be adjusted though.

> > As of today Zephyr docs on wide displays (e.g. UWD, my case) require wide-angle eye motion (bad) unless you make the window size small enough.
> 
> Just make the browser window match your preferences? Who does have a full screen browser on a wide screen anyways...

It's an extreme case, but shows that docs responsivenes is not great.

I'll make a list of well-established projects that have their docs available publicly so that we can compare.

**Comment by gmarull** [comment]
I've collected a list of projects to see what are the popular approaches (feel free to edit, may be biased).

| Project                                                                       | Fixed width content? | Content alignment | Others                                           |
|-------------------------------------------------------------------------------|----------------------|-------------------|--------------------------------------------------|
| [Swift](https://docs.swift.org/swift-book/)                                   | YES                  | left              |                                                  |
| [Tensorflow](https://www.tensorflow.org/api_docs)                             | YES                  | center            | Navbar sticks to the left                        |
| [Github Docs](https://docs.github.com/en/github)                              | YES                  | center            | Navbar sticks to the left                        |
| [Kernel](https://www.kernel.org/doc/html/latest/)                             | NO                   | left              |                                                  |
| [Espressif SDK](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/) | YES                  | left              |                                                  |
| [Tailwind CSS](https://tailwindcss.com/docs/)                                 | YES                  | center            |                                                  |
| [ReactJS](https://reactjs.org/docs/getting-started.html)                      | YES                  | center            | Navbar sticks to the right                       |
| [Python](https://docs.python.org/3/)                                          | YES                  | left              |                                                  |
| [Rust](https://doc.rust-lang.org/std/index.html)                              | YES                  | left              |                                                  |
| [Go](https://golang.org/doc/)                                                 | YES                  | left              | Titles background expand to full width           |
| [Flutter](https://flutter.dev/docs/development/ui/widgets-intro)              | YES                  | center            | Navbar sticks to the left, page TOC to the right |

Summary:
- Fixed width: clearly wins
- Content align/others:
  - Left align seems to be more popular
  - Center align + left sidebar seems like an interesting option

**Comment by gmarull** [comment]
options for fixed width:

* align=center

image

* align=left:

image

* align=center content, navbar sticks to the left

image

**Comment by erwango** [comment]
- align=center content, navbar sticks to the left

**Comment by gmarull** [comment]
@laurenmurphyx64 added light/dark selector

**Comment by carlescufi** [comment]
dev-review:

- Marketing team notified, expected to take a look
- @kestewart there are `.css` and `.js` files that are `cc-by-3.0` licensed. The charter states that documentation will be made available under the `cc-by-4.0` license. However, the mentioned files are not part of the documentation content, but rather supporting files for the web itself.

**Comment by mbolivar-nordic** [comment]
I'm voting for align left.

**Comment by galak** [comment]
> I'm voting for align left.

I'm vote for align left as well.

**Comment by gmarull** [comment]
@carlescufi Any feedback from marketing guys?

**Comment by gmarull** [comment]
I'm voting for:
- align=center content, navbar sticks to the left

**Comment by kestewart** [comment]
@carlescufi - is there a compelling reason why Teslabs Engineering S.L.is insisting on CC-BY-3.0,  rather than just using CC-BY-4.0?    Has someone asked them to change it?

**Comment by gmarull** [comment]
@kestewart the original license is CC-BY-3.0, so I guess we need to preserve that.

**Comment by kestewart** [comment]
@gmarull - if Teslabs Engineering S.L. is the original author,  they can change the license.

**Comment by gmarull** [comment]
> @gmarull - if Teslabs Engineering S.L. is the original author, they can change the license.

I'm just the author of some changes, but most content comes from Godot. I suppose we also need to add their copyright (was not present in the original files).

**Comment by kestewart** [comment]
@gmarull - yes please add the copyright for Godot, if you've derived the files from their starting point.

**Review by kestewart — CHANGES_REQUESTED** [review]
Please make sure that the original copyright is preserved in files that have been imported from other projects.   If no specific copyright was in the file, take the copyright information from the project that the file was found in.

**Review by kestewart — APPROVED** [review]
Copyrights have been updated and look reasonable.  Thanks.

**Comment by kestewart** [comment]
Marketing committee reviewed in earlier meeting and didn't raise any issues.   Suggestion is to go forward and continue to evolve.    Thanks for all the hard work and patience that has gone in to shepherding this change through.

**Comment by nashif** [comment]
voting align=left

**Comment by gmarull** [comment]
modified to have align=left

**Review by nashif — APPROVED** [review]

**Pull request merged**
