### PR TITLE
LE Audio: VCP API refactor

### LINKED ISSUE #45621: LE Audio: Update VCP API with new naming scheme
**Is your enhancement proposal related to a problem? Please describe.**
Apply the new naming scheme from https://github.com/zephyrproject-rtos/zephyr/issues/40920 to the MICP implemenation and API

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Refactor the API of the VCP, following the same pattern as https://github.com/zephyrproject-rtos/zephyr/pull/46655

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/45621

### CODE REVIEW

**Review by kruithofa — DISMISSED** [review]

**Review by MariuszSkamra — DISMISSED** [review]

**Comment by Thalley** [comment]
@kruithofa @MariuszSkamra You've both previously approved this - Will you do a re-review please?

**Review by MariuszSkamra — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Comment by carlescufi** [comment]
@Thalley please rebase

**Comment by Thalley** [comment]
@kruithofa @MariuszSkamra rebased to solve merge conflicts (just the `zephyr_fag.svg` file). Please re-approve :)

**Review by MariuszSkamra — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased on https://github.com/zephyrproject-rtos/zephyr/pull/51897

**Review by kruithofa — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

**Pull request merged**
