### PR TITLE
drivers: set ALLOW_EMPTY property to TRUE

### PR DESCRIPTION
**Pull request by ycsin**
A few drivers have this set to fix the build warnings already, this PR tries to fix the remaining ones.

### CODE REVIEW

**Comment by ycsin** [comment]
Adding this to v3.7 milestone as I reckon this should be nice to have so that users on LTS do not have to see the warnings in the terminal when they build OOT drivers

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Thanks!

**Comment by henrikbrixandersen** [comment]
Isn't that warning desired to have? You enable a subsystem, but no drivers in that subsystem is enabled. What is the use-case?

**Review by gmarull — COMMENTED** [review]
not approving, as the warning indicates a configuration issue.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
This hides configuration issues without a justified use-case.

**Comment by fabiobaltieri** [comment]
@gmarull @henrikbrixandersen I think that the intent is to not have the warning if the subsystem is enabled only with out-of-tree drivers, see the commit message, I don't think it's a bad idea.

**Comment by henrikbrixandersen** [comment]
> @gmarull @henrikbrixandersen I think that the intent is to not have the warning if the subsystem is enabled only with out-of-tree drivers, see the commit message, I don't think it's a bad idea.

When using out-of-tree drivers, you use `zephyr_library_amend()` which causes the library to not become empty.

**Comment by fabiobaltieri** [comment]
> When using out-of-tree drivers, you use `zephyr_library_amend()` which causes the library to not become empty.

Neat, didn't know about that, I think that makes more sense then.

**Comment by ycsin** [comment]
So we should actually remove these instances instead?

https://github.com/zephyrproject-rtos/zephyr/blob/2871c87aaec004cf4fe8e61a8d15c35b6d8ab677/drivers/cache/CMakeLists.txt#L6

**Comment by henrikbrixandersen** [comment]
> So we should actually remove these instances from tree instead?
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/2871c87aaec004cf4fe8e61a8d15c35b6d8ab677/drivers/cache/CMakeLists.txt#L6

Not necessarily. There are some use-cases, e.g. cache handling, where you wish to be able to enable a subsystem "if possible".

**Comment by fabiobaltieri** [comment]
Some of those could probably go though, would be nice if we could customize the error message but I doubt it's possible.

**Pull request closed without merging**
