### PR TITLE
boards: enable uart if BT_DEBUG_MONITOR is on

### PR DESCRIPTION
**Pull request by erwango**
To enable tracing with BT_DEBUG_MONITOR, UART_CONSOLE should be
deactivated, but it still requires UART to be enabled

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by ydamigos — COMMENTED** [review]
Why did you leave out stm32f072_eval and stm32f072b_disco?

**Comment by erwango** [comment]
> Why did you leave out stm32f072_eval and stm32f072b_disco?

Have been merged in between, good catch, thanks!

**Comment by ydamigos** [comment]
I get the point that you can connect an external bluetooth module to the boards, but it is a little confusing to see BT_DEBUG_MONITOR in board's defconfig file for board's without bluetooth support enabled.

**Comment by erwango** [comment]
This was the fastest solution, but I agree this could be cleaner.
I'll try to come up with another solution

**Comment by ydamigos** [comment]
> This was the fastest solution, but I agree this could be cleaner.
I'll try to come up with another solution

You could use a different UART (if it is available) for BT_DEBUG_MONITOR.

**Comment by erwango** [comment]
> You could use a different UART (if it is available) for BT_DEBUG_MONITOR.

Yes, but then you need to enable it in dts, configure pinmux, ...
Using existing and configured UART is much easier and the way it is advised to be used.

**Review by galak — CHANGES_REQUESTED** [review]
Can this be SERIAL_HAS_DRIVER instead of UART_CONSOLE || BT_DEBUG_MONITOR?

**Comment by erwango** [comment]
> Can this be SERIAL_HAS_DRIVER instead of UART_CONSOLE || BT_DEBUG_MONITOR?

Well, we can have SERIAL_HAS_DRIVER without any console required. So I don't think it would match.
Besides, I had a look to SERIAL_HAS_DRIVER and I wonder if it is actually useful anyhow. It is only used once, in zephyr/drivers/console/Kconfig:
````
config UART_CONSOLE
	bool
	prompt "Use UART for console"
	default n
	depends on SERIAL && SERIAL_HAS_DRIVER
	select CONSOLE_HAS_DRIVER
````

But, indeed we should be able to define an intermediate flag to mention that console/debug output is required on uart. Say a new flag that should be selected by UART_CONSOLE and BT_DEBUG_MONITOR.
What about : 
````
config SERIAL_OUTPUT
        default n
        help
          Route any instance flow on serial ouput
````

Then this flag could replace UART_CONSOLE || BT_DEBUG_MONITOR

**Comment by erwango** [comment]
Closing for now

**Pull request closed without merging**
