### PR TITLE
samples: drivers: lora: build with newlib

### PR DESCRIPTION
**Pull request by alexanderwachter**
The loramac-node library uses math functions from math.h that
are not included in the minimal lib.
This commit changes the samples project config to always build
with newlib.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
No objections but how this did work before this commit?

**Comment by alexanderwachter** [comment]
@carlescufi the 96b_wistrio selects newlib by default.

**Review by Mani-Sadhasivam — APPROVED** [review]

**Comment by KubaFYI** [comment]
> @carlescufi the 96b_wistrio selects newlib by default.

Note, this might not apply to some other boards which also might want to use the Lora stack. I'm working with a samd21 based Adafruit Feather M0 LoRa and had to enable newlib manually. Might be worth making newlib a prereq for the lora stack?

**Comment by carlescufi** [comment]
> > @carlescufi the 96b_wistrio selects newlib by default.
> 
> Note, this might not apply to some other boards which also might want to use the Lora stack. I'm working with a samd21 based Adafruit Feather M0 LoRa and had to enable newlib manually. Might be worth making newlib a prereq for the lora stack?

I do think that would be the better fix @alexanderwachter and @Mani-Sadhasivam

**Comment by Mani-Sadhasivam** [comment]
> > > @carlescufi the 96b_wistrio selects newlib by default.
> > 
> > 
> > Note, this might not apply to some other boards which also might want to use the Lora stack. I'm working with a samd21 based Adafruit Feather M0 LoRa and had to enable newlib manually. Might be worth making newlib a prereq for the lora stack?
> 
> I do think that would be the better fix @alexanderwachter and @Mani-Sadhasivam

I thought about it before but I was not sure what would be the appropriate place for adding this. NEWLIB is required by loramac stack, so should we just add it to `modules/Kconfig.loramac-node`?

**Comment by alexanderwachter** [comment]
Dependency added.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
