### PR TITLE
Bluetooth: Host: Remove `bt_buf_get_cmd_complete`

### LINKED ISSUE #64158: Bluetooth: HCI command corruption on `NUM_COMPLETED_PACKETS `
**Describe the bug**

HCI command buffers can be corrupted by the host receiving a `BT_HCI_OP_HOST_NUM_COMPLETED_PACKETS` (opcode 0x0c35) response at an inopportune time.

`hci_core.c` assigns `bt_dev.sent_cmd` before actually sending the command to the HCI backend:
https://github.com/zephyrproject-rtos/zephyr/blob/625d1bfc61b576514c123be0e63f38470b998a4b/subsys/bluetooth/host/hci_core.c#L2692-L2696

`bt_buf_get_cmd_complete`, which is used to allocate a buffer for the command response, naively re-uses the command buffer and overwrites the packet type and length.

https://github.com/zephyrproject-rtos/zephyr/blob/625d1bfc61b576514c123be0e63f38470b998a4b/subsys/bluetooth/host/buf.c#L89-L103

`BT_HCI_OP_HOST_NUM_COMPLETED_PACKETS` is a special command in that it ignores the normal flow control, and *normally* does not receive a response. From the BT spec:

> Normally, no event is generated after the HCI_Host_Number_Of_Completed_Packets command has completed. However, if the HCI_Host_Number_Of_Completed_Packets command contains one or more invalid parameters, the Controller shall return an HCI_Command_Complete event with a failure status indicating the Invalid HCI Command Parameters error code.

If such a response is received, after the host has assigned `bt_dev.sent_cmd`, but before it is actually sent, the buffer allocation function will corrupt the command parameters, usually leading to the HCI backend rejecting the command as invalid.

**Expected behavior**
Receiving `BT_HCI_OP_HOST_NUM_COMPLETED_PACKETS` should not corrupt pending HCI commands.

**Impact**
Arbitrary HCI command failures

### PR DESCRIPTION
**Pull request by alwa-nordic**
`bt_buf_get_cmd_complete` is broken due to https://github.com/zephyrproject-rtos/zephyr/issues/64158, and fixing it would require changing its signature and put even more complexity into the HCI drivers, as it would require the drivers to perform an even deeper peek into the event in order to observe the opcode.

Instead of the above, this patch removes the use of `bt_buf_get_cmd_complete` and adds logic to allow the host to accept command complete events in normal event buffers.

The above means performing a copy into the destination buffer, which is the original command buffer. This is a small inefficiency for now, but we should strive to redesign the host into a streaming architecture as much as possible and handle events immediately instead of retaining buffers.

This fixes https://github.com/zephyrproject-rtos/zephyr/issues/64158: Like all command completed events, the completion event for `BT_HCI_OP_HOST_NUM_COMPLETED_PACKETS` is now placed in normal event buffers. The the logic where the host discards this event is already present. Since it's discarded, it will not interfere with the logic around `bt_dev.cmd_send`.

### CODE REVIEW

**Review by jori-nordic — APPROVED** [review]

**Comment by jhedberg** [comment]
I'm not opposed to this change, but another reason (besides being an optimisation) for the reuse is that it completely eliminates one category of bugs, namely deadlocks caused by `bt_hci_cmd_send_sync()` blocking in a thread that would also be needed to free up buffers for the command complete event reception.

**Comment by jhedberg** [comment]
> I'm not opposed to this change, but another reason (besides being an optimisation) for the reuse is that it completely eliminates one category of bugs, namely deadlocks caused by `bt_hci_cmd_send_sync()` blocking in a thread that would also be needed to free up buffers for the command complete event reception.

and to continue on this thought: unless my memory fails me, the feature was originally inspired by wanting to get rid of fighting deadlocks like this. It was introduced in commit 50678b03cb468a907d15eaa94d7a824cae18988d but unfortunately the commit message doesn't seem to go into much detail besides mentioning "reducing pressure on the RX buffer pool". The feature would have its 7th anniversary in a few days :)

Btw, might be worth to do some profiling to see what kind of impact this has on the performance of Bluetooth Mesh, since that actually depends on a continuous stream of HCI commands (as opposed to ACL packets) for the transmission of data. @PavelVPV FYI.

**Comment by alwa-nordic** [comment]
The CI error is unrelated.

**Comment by alwa-nordic** [comment]
I think the deadlocking problems the host has can really only be solved a principled way: We must stop blocking the event stream from the controller. All these priority levels and extra pools and stuff are just band-aids without technical soundness.

I mean all events must be treated as ISR. And I mean the event buffer must be made available for the next event immediately without any dependencies. If an event handler must keep data around, it must have it's own buffers (it can copy data into or give to the driver for DMA), or it can choose to drop the data. The handler cannot delay the event stream.

It's also not true that deadlocks caused by `bt_hci_cmd_send_sync` are eliminated, as far as I understand. The reason is that the event stream is serial at transport level. The command complete can be stuck behind other events. The host cannot peek into the future of the physical UART RX wire.

**Comment by PavelVPV** [comment]
> Btw, might be worth to do some profiling to see what kind of impact this has on the performance of Bluetooth Mesh, since that actually depends on a continuous stream of HCI commands (as opposed to ACL packets) for the transmission of data. @PavelVPV FYI.

I cherry-picked these 4 commits to the nrf connect sdk fork and ran our performance tests. The relay node performance is not changed. Throughput varies within the margin of error.

**Comment by jhedberg** [comment]
> It's also not true that deadlocks caused by `bt_hci_cmd_send_sync` are eliminated, as far as I understand. The reason is that the event stream is serial at transport level. The command complete can be stuck behind other events. The host cannot peek into the future of the physical UART RX wire.

That's a good point. And as a general design approach what you suggest sounds like the only safe bet. What mitigates the current situation a little bit is the concept of "discardable" events (e.g. advertising reports) but that doesn't cover everything that could be in the transport queue.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
