### PR TITLE
board: serpente fix dts (samd2x.dtsi)

### PR DESCRIPTION
**Pull request by Laczen**
move port a under pinmux a and port b under pinmux b to remove dts
errors.

Signed-off-by: Laczen JMS <laczenjms@gmail.com>

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
If you want to fix this, than the solution would be to either split the regs for a port so

GPIO is <0x41004400 0x30>;

and

PINMUX is <0x41004430 0x30>;

and fixup the drivers.  You'll need to also deal with the bit of PINMUX config that the GPIO driver needs for interrupt handle case.

**Comment by Laczen** [comment]
> If you want to fix this, than the solution would be to either split the regs for a port so
> 
> GPIO is <0x41004400 0x30>;
> 
> and
> 
> PINMUX is <0x41004430 0x30>;
> 
> and fixup the drivers. You'll need to also deal with the bit of PINMUX config that the GPIO driver needs for interrupt handle case.

I did this in analogy with st devices where gpio is defined under pinmux. I have not changed any registers nor did I verify that the original dts was correct.

**Comment by galak** [comment]
> I did this in analogy with st devices where gpio is defined under pinmux. I have not changed any registers nor did I verify that the original dts was correct.

Wasn't aware of the change for ST, but would say its probably not the proper fix for the issue there either.

**Comment by Laczen** [comment]
> > I did this in analogy with st devices where gpio is defined under pinmux. I have not changed any registers nor did I verify that the original dts was correct.
> 
> Wasn't aware of the change for ST, but would say its probably not the proper fix for the issue there either.

It's not a change for ST, it's how it is defined (e.g. stm32f412.dtsi).

**Pull request closed without merging**
