### PR TITLE
tests/bsim: Reorder tests to avoid failure in GATT/SR/GAS/BV-01-C

### LINKED ISSUE #70380: Bluetooth EDTT GATT test: GATT/SR/GAS/BV-01-C failing in main
**Describe the bug**
GATT/SR/GAS/BV-01-C is currently failing in main in CI 

**To Reproduce**
1. WORK_DIR=${ZEPHYR_BASE}/bsim_out tests/bsim/bluetooth/ll/compile.sh
2. tests/bsim/bluetooth/ll/edtt/tests_scripts/gatt.llcp.sh
3. See error

**Expected behavior**
No failures

**Impact**
CI/development blocked when BT workflow is triggered

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/8327849361/job/22786496845?pr=70375#step:13:752

**Environment (please complete the following information):**
 - OS: Linux - Ubuntu 22.04 / CI
 - Toolchain: Host gcc 11/12
 - Commit SHA or Version used: Main as of now: 369e40b27bca1f08fefe23924f7dc82dd096c53f

**Additional context**
The issue appeared after 6622f0b3aa919b0b4a066c88cba7441ec34fbf81 was merged, but that change passed all BT tests in CI (https://github.com/zephyrproject-rtos/zephyr/actions/runs/8296066070/job/22704378439), which indicates the failure is due to a combination with some other change which got into main in the meanwhile.
Given that this change causes a minor time difference, and that a fix (https://github.com/zephyrproject-rtos/zephyr/pull/70379) which simply changes the order in which the test is executed gets the test to pass again, it would indicate the test is too time sensitive.

### PR DESCRIPTION
**Pull request by aescolar**
GATT/SR/GAS/BV-01-C has just broken due to what appears like a minor timing change.
This indicates the test may be too time sensitive. Just reordering the tests, it passes again.
So let's reorder the test list, and we get the minor benefit of having them more alphabetically ordered.

Fixes: #70380

### CODE REVIEW

**Comment by jhedberg** [comment]
@aescolar are you (or someone else) planning to continue investigating this to figure out the root cause? It's not exactly ideal that we have CI tests which depend on what tests run before or after them.

**Review by jhedberg — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by jori-nordic** [comment]
```
CONFIG_BT_AUTO_PHY_UPDATE=n
CONFIG_BT_AUTO_DATA_LEN_UPDATE=n
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n
```
Fixes it. Controller bug then?

**Comment by jori-nordic** [comment]
Given we have a proper fix, shall we revert this @aescolar ? Or do we keep the alphabetical list.

**Comment by aescolar** [comment]
> Given we have a proper fix, shall we revert this @aescolar ? Or do we keep the alphabetical list.

@jori-nordic Up to you, but not like this change harms in any way I guess :)

**Comment by jori-nordic** [comment]
Let's keep it

**Pull request merged**
