### PR TITLE
Make cavstool code more shareable

### PR DESCRIPTION
**Pull request by jsarha**
The cavstool.py has a lot of useful but complex code in it to access DSP memory, but it looks to be grown quite hard to maintain. This PR makes some critical changes there to make some of the functions in cavstool.py shareable from outside the module to avoid growing it even more or forking the code. Much more could be done to that direction, but since I do not understand too well what it is doing, I am proceeding in baby steps and doing only what I need.

The motivation to these changes is to allow debug_stream.py [1] from SOF side to access its debug window slot directly using cavstool.py functions.

[1] https://github.com/thesofproject/sof/blob/main/tools/debug_stream/debug_stream.py

### CODE REVIEW

**Comment by jsarha** [comment]
The PR requiring this change is here: https://github.com/thesofproject/sof/pull/9498

**Review by kv2019i — COMMENTED** [review]
Thanks @jsarha . Looks good for the most part, a few minor comments inline, please check.

**Review by kv2019i — DISMISSED** [review]
Good for me now! You do need to address the CI compliance check fails before this can be merged.

**Comment by jsarha** [comment]
Fix couple of pylint issues for CI compliance checks.

**Comment by jsarha** [comment]
> Fix couple of pylint issues for CI compliance checks.

And one more.

**Review by dcpleung — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Seems clean enough, though I absolutely agree that this has grown beyond the original organization and maybe a rewrite might be worth thinking about.  Note that MediaTek DSPs have a broadly similar MMIO interface to device SRAM, and it would be good for them to evolve in the direction of sharing the same host-side log code.

**Pull request merged**
