### PR TITLE
Bluetooth: controller: Prepare to introduce LL split architecture

### PR DESCRIPTION
**Pull request by cvinayak**
Preparation to introduce the Upper Link Layer (ULL) and
Lower Link Layer (LLL) split architecture.

- Move SoC dependent HAL to vendor specific folder.
- Preparation to split data structures into ULL and LLL
  types.
- Added more role and state conditional compilations.
- Added some work-in-progress implementation of advertising
  extensions, will be used as inspiration in the new split
  architecture work.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by dleach02** [comment]
Do you have a higher level document/diagram of the abstraction and APIs between the layers? Or do we have to drill into the files?

**Comment by cvinayak** [comment]
@dleach02 Hi, for publicly available brief high level diagram, you can refer to my talk at ELCE, slide 18 onwards, https://events.linuxfoundation.org/wp-content/uploads/2017/12/Bluetooth-Low-Energy-Controller-in-Zephyr-OS-Vinayak-Kariappa-Chettimada-Nordic-Semiconductor-ASA.pdf

I have not got yet into upstreaming any better documentation yet, but could happen in the future.

**Review by sjanc — APPROVED** [review]
It is huge change but in general looks good to me.

**Review by aescolar — APPROVED** [review]
I thought it was obvious from our talks that I'm ok with it :) (haven't check this particular commit, but I'm guessing it does not differ much from the current ull_lll branch)

**Comment by jhedberg** [comment]
> @jhedberg any comments on this one? Mostly refactoring but would be good to hear from you.

@carlescufi a bit too big for a thorough review, but from what I can see it looks good to me. That said, it would have been nice to have this split up into more patches (e.g. it seems to be touching the Bluetooth shell which could at least partially have been split to an independent patch).

**Comment by cvinayak** [comment]
@jhedberg as part of the rebase to resolve conflict I will give a try to separate out the shell changes.

**Comment by carlescufi** [comment]
Right now the folder structure looks like:

```
├── crypto
├── hal
├── hci
├── include
├── ll_sw
│   └── nordic
│       └── hal
│           └── nrf5
│               └── radio
├── ticker
└── util
```
And `hal` only contains headers. Do we need that `hal` folder, or can we move it to `ll_sw/nordic/hal`?

**Comment by cvinayak** [comment]
@carlescufi the top level hal is common interface signature for other vendor's hal implementations.

**Comment by carlescufi** [comment]
>@carlescufi the top level hal is common interface signature for other vendor's hal implementations.

Fine, not sure I like it still but I will wait for the actual refactor to come in in order to have a better picture and suggest other folder names or locations.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
