### PR TITLE
debug: generate call graph profile data using gprof

### PR DESCRIPTION
**Pull request by nashif**
This will generate profile data that can be analyzed using gprof. When
you build the application (currently for native_posix only), after
running the application you will get a file "gmon.out" with the call
graph which can be processed with gprof:

  gprof build/zephyr/zephyr.exe gmon.out > analysis.txt

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
example output from samples/synchronization:
output

**Comment by nashif** [comment]
or the text output from gprof:

```
Flat profile:

Each sample counts as 0.01 seconds.
 no time accumulated

  %   cumulative   self              self     total
 time   seconds   seconds    calls  Ts/call  Ts/call  name
  0.00      0.00     0.00      266     0.00     0.00  char_out
  0.00      0.00     0.00      205     0.00     0.00  hwm_find_next_timer
  0.00      0.00     0.00      194     0.00     0.00  hwtimer_update_timer
  0.00      0.00     0.00      186     0.00     0.00  get_host_us_time
  0.00      0.00     0.00      185     0.00     0.00  hwtimer_timer_reached
  0.00      0.00     0.00      123     0.00     0.00  hw_irq_ctrl_change_lock
  0.00      0.00     0.00       60     0.00     0.00  posix_irq_lock
  0.00      0.00     0.00       56     0.00     0.00  posix_irq_unlock
  0.00      0.00     0.00       49     0.00     0.00  pc_safe_call
  0.00      0.00     0.00       41     0.00     0.00  hwm_get_time
  0.00      0.00     0.00       24     0.00     0.00  pc_safe_call
  0.00      0.00     0.00       18     0.00     0.00  update_cache
  0.00      0.00     0.00       16     0.00     0.00  sys_clock_elapsed
  0.00      0.00     0.00       15     0.00     0.00  posix_change_cpu_state_and_wait
  0.00      0.00     0.00       15     0.00     0.00  posix_wait_until_allowed
  0.00      0.00     0.00       14     0.00     0.00  extract_decimal
  0.00      0.00     0.00       14     0.00     0.00  outs
  0.00      0.00     0.00       13     0.00     0.00  z_reset_time_slice
  0.00      0.00     0.00       12     0.00     0.00  arch_swap
  0.00      0.00     0.00       12     0.00     0.00  posix_swap
  0.00      0.00     0.00       11     0.00     0.00  hw_irq_ctrl_get_highest_prio_irq
  0.00      0.00     0.00       11     0.00     0.00  sys_dlist_remove
  0.00      0.00     0.00       10     0.00     0.00  elapsed
  0.00      0.00     0.00        9     0.00     0.00  ready_thread
  0.00      0.00     0.00        8     0.00     0.00  hw_irq_ctrl_get_cur_prio
  0.00      0.00     0.00        8     0.00     0.00  hw_irq_ctrl_set_cur_prio
  0.00      0.00     0.00        8     0.00     0.00  posix_halt_cpu
  0.00      0.00     0.00        7     0.00     0.00  hw_irq_ctrl_get_current_lock
  0.00      0.00     0.00        7     0.00     0.00  hw_irq_ctrl_irq_raise_prefix
  0.00      0.00     0.00        7     0.00     0.00  hw_irq_ctrl_set_irq
  0.00      0.00     0.00        7     0.00     0.00  hw_irq_ctrl_timer_triggered
  0.00      0.00     0.00        7     0.00     0.00  hwtimer_set_silent_ticks
  0.00      0.00     0.00        7     0.00     0.00  irq_raising_from_hw_now
  0.00      0.00     0.00        7     0.00     0.00  next_timeout
  0.00      0.00     0.00        7     0.00     0.00  posix_interrupt_raised
  0.00      0.00     0.00        7     0.00     0.00  posix_irq_full_unlock
  0.00      0.00     0.00        7     0.00     0.00  posix_irq_handler
  0.00      0.00     0.00        7     0.00     0.00  sys_clock_set_timeout
  0.00      0.00     0.00        7     0.00     0.00  unready_thread
  0.00      0.00     0.00        6     0.00     0.00  sys_clock_tick_get
  0.00      0.00     0.00        6     0.00     0.00  sys_clock_tick_get_32
  0.00      0.00     0.00        5     0.00     0.00  cbvprintf
  0.00      0.00     0.00        5     0.00     0.00  hwtimer_wake_in_time
  0.00      0.00     0.00        5     0.00     0.00  printk
  0.00      0.00     0.00        5     0.00     0.00  run_native_tasks
  0.00      0.00     0.00        5     0.00     0.00  vprintk
  0.00      0.00     0.00        5     0.00     0.00  z_impl_k_sem_take
  0.00      0.00     0.00        5     0.00     0.00  z_impl_z_current_get
  0.00      0.00     0.00        5     0.00     0.00  z_reschedule
  0.00      0.00     0.00        4     0.00     0.00  add_to_waitq_locked
  0.00      0.00     0.00        4     0.00     0.00  arch_busy_wait
  0.00      0.00     0.00        4     0.00     0.00  arch_new_thread
  0.00      0.00     0.00        4     0.00     0.00  encode_uint
  0.00      0.00     0.00        4     0.00     0.00  hw_irq_ctrl_clear_irq
  0.00      0.00     0.00        4     0.00     0.00  hw_irq_ctrl_get_prio
  0.00      0.00     0.00        4     0.00     0.00  k_thread_name_get
```

**Comment by aescolar** [comment]
Neat, one note, you can use valgrind's callgrind without any compile options 
```
valgrind --tool=callgrind --dump-instr=yes --collect-jumps=yes zephyr.exe
```

**Review by aescolar — APPROVED** [review]
LGTM. Should we add a small section in the doc for this? (and maybe also callgrind)

**Comment by nashif** [comment]
> Neat, one note, you can use valgrind's callgrind without any compile options

right, my goal is to see if we can go beyond native_posix and enable this on some of the other targets, something similar to what is being done here...

https://dzone.com/articles/using-gnu-profiling-gprof-with-arm-cortex-m

**Comment by teburd** [comment]
Very cool indeed, look forward to seeing gprof dumping all sorts of great stuff

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
