### PR TITLE
ipc: Call ipm_set_enabled() also for dual IPM support

### PR DESCRIPTION
**Pull request by carlocaione**
The IPC drivers rpmsg_service and rpmsg_multi_instance are not
explicitly enabling the IPM channels when two different devices are used
for TX and RX. While this could be redundant for some IPM drivers, in
some cases the hardware needs to be enabled before using it.

Add the missing calls to ipm_set_enabled() for both the devices.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

### CODE REVIEW

**Review by hubertmis — APPROVED** [review]

**Comment by carlocaione** [comment]
tagging @maje-emb as well

**Review by doki-nordic — APPROVED** [review]

**Review by hubertmis — CHANGES_REQUESTED** [review]
Seems rpmsg_service sample for nRF53 stopped working after this change

**Comment by maje-emb** [comment]
After first testing: it seems that the ipc_service and rpmsg_multi_intentions samples also stopped working. Tested on nRF5340.

**Comment by carlocaione** [comment]
@hubertmis @maje-emb uhm, on a second thought I'm not convinced anymore that is the correct fix. The API documentation says indeed that `.set_enabled` `Enable interrupts and callbacks for inbound channels` https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/ipm.h#L205. So the correct fix here is just call `set_enabled` on the RX channel.

**Review by hubertmis — APPROVED** [review]
Verified rpmsg_service sample works fine on nRF5340

**Comment by maje-emb** [comment]
ipc_service and rpmsg_multi_instance samples also work fine.

**Pull request merged**
