### PR TITLE
samples/bluetooth: Relax RSSI requirement 

### PR DESCRIPTION
**Pull request by aescolar**
samples/bluetooth/central_multilink: Relax RSSI requirement
samples/bluetooth/mtu_update: Relax RSSI requirement

The sample was only willing to connect if the pair RSSI level
was over -40/-35dBm. That is ok when testing physically keeping
devices at less than ~1 meter from each other.
But in CI we test with a default attenuation of 60dB between
devices and the Tx power is 0dBm.
Which causes the tests based on this sample to fail.

### CODE REVIEW

**Comment by aescolar** [comment]
The test can be seen failing if using the latest magic modem model
https://github.com/BabbleSim/ext_2G4_modem_magic/commit/26051fdf51f3d9931796876db0080a30297b0d2a

**Comment by Thalley** [comment]
> which is too high if the modem model reports a realistic RSSI value.

So the argument here is that the check (`if (rssi < -40) {`) in the sample is an unrealistic value? 

If that is the case, shouldn't the sample be updated then? 
If the case is that `-40` can be considered realistic, is there a reason why we wouldn't use that in BSIM by default?

**Comment by aescolar** [comment]
The test in
https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/mtu_update/central/src/central_mtu_update.c#L133
Is too tough if the attenuation in the channel is 60dB (the Tx power level is 0dBm)

**Comment by Thalley** [comment]
> The test in https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/mtu_update/central/src/central_mtu_update.c#L133 Is too tough if the attenuation in the channel is 60dB (the Tx power level is 0dBm)

Right, so the my question was whether it would be better to update the sample? The majority of our samples use `-70` instead of `-40` for the RSSI check

**Comment by aescolar** [comment]
@Thalley That may be reasonable.

**Comment by Thalley** [comment]
@theob-pro do you remember why you chose `-40` as the cutoff for the sample?

**Comment by theob-pro** [comment]
> @theob-pro do you remember why you chose `-40` as the cutoff for the sample?

Yes, I choose that value because there was a lot of noise in the office. You can change it, that's not a problem.

**Comment by Thalley** [comment]
> > @theob-pro do you remember why you chose `-40` as the cutoff for the sample?
> 
> Yes, I choose that value because there was a lot of noise in the office. You can change it, that's not a problem.

I suggest to just change it to `-70` then. There is another sample, `samples/bluetooth/central_multilink/src/central_multilink.c` which have the same "issue", which may need a similar "fix".

**Comment by aescolar** [comment]
Fixed both samples, so they have less tough RSSI requirements, instead of reducing the channel attenuation on the test.

**Review by Thalley — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Review by theob-pro — APPROVED** [review]

**Pull request merged**
