### PR TITLE
MAINTAINERS: Update Renesas RA Platforms and hal_renesas maintainers

### PR DESCRIPTION
**Pull request by ydamigos**
Added to Renesas RA Platforms:

maintainers -> KhiemNguyenT
collaborators ->  duynguyenxa, thaoluonguw

Added to hal_renesas:

collaborators -> soburi, duynguyenxa, thaoluonguw

### CODE REVIEW

**Comment by ydamigos** [comment]
@KhiemNguyenT @ioannis-karachalios @duynguyenxa @thaoluonguw please have a look.

**Review by soburi — APPROVED** [review]

**Review by ioannis-karachalios — APPROVED** [review]

**Comment by KhiemNguyenT** [comment]
I agreed this PR.

**Review by MaureenHelm — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by aescolar — CHANGES_REQUESTED** [review]
@KhiemNguyenT @duynguyenxa @thaoluonguw do not seem to be project contributors.
Please create a "contributor nomination" issue first. Otherwise it won't be possible to assign them to reviews, and their reviews will not count for the merge criteria.
Once they have been added as contributors to the project, the MAINTAINERS file can be updated.

**Comment by ydamigos** [comment]
> @KhiemNguyenT @duynguyenxa @thaoluonguw do not seem to be project contributors. Please create a "contributor nomination" issue first. Otherwise it won't be possible to assign them to reviews, and their reviews will not count for the merge criteria. Once they have been added as contributors to the project, the MAINTAINERS file can be updated.

Opened "contributor nomination" issues:
https://github.com/zephyrproject-rtos/zephyr/issues/75664
https://github.com/zephyrproject-rtos/zephyr/issues/75667

Can I open an issue for @KhiemNguyenT without "Supporting Documents"?

**Comment by aescolar** [comment]
> Can I open an issue for @KhiemNguyenT without "Supporting Documents"?

You can open it :), it will be evaluated based on its merit.

**Comment by ydamigos** [comment]
> > Can I open an issue for @KhiemNguyenT without "Supporting Documents"?
> 
> You can open it :), it will be evaluated based on its merit.

https://github.com/zephyrproject-rtos/zephyr/issues/75687

**Review by ioannis-karachalios — APPROVED** [review]

**Review by duynguyenxa — APPROVED** [review]

**Review by thaoluonguw — APPROVED** [review]

**Review by KhiemNguyenT — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Pull request merged**
