### PR TITLE
Bluetooth: controller: ISR, main and Sys work Q stack usage

### PR DESCRIPTION
**Pull request by cvinayak**
Added implementation to log the ISR, Main and System work
queue stack usages when CONFIG_INIT_STACKS is enabled.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
Approving, though I really think it'd be better if there was a system-wide helper for this, so that not every place has to go through this declaration of extern variables (which is quite error prone and will break if the definition of the original declaration changes)

**Comment by cvinayak** [comment]
@jhedberg on second thought, I agree with you, the log should come from some kernel file, not from bluetooth files. Should I close/cancel this PR?

**Comment by cvinayak** [comment]
Closing. The log should come from some kernel file/thread, not from Bluetooth threads.

**Comment by carlescufi** [comment]
I don't think we should close this @cvinayak. This is a reasonable short-term solution and it will be useful. I myself have added this code locally several times. I would merge this.

**Comment by jhedberg** [comment]
> @jhedberg on second thought, I agree with you, the log should come from some kernel file, not from bluetooth files.

@cvinayak I'll leave the decision on this PR to you and @carlescufi . As for the system-wide API, I think the ideal would be one which dumps all threads in the system using `k_thread_foreach()`, similar to what the "kernel stacks" shell command does  (see `cmd_kernel_stacks()` in `subsys/shell/modules/kernel_service.c`). That'd then also include printing the name of the thread provided that `CONFIG_THREAD_NAME=y`.

**Pull request closed without merging**
