### PR TITLE
drivers/flash/stm32/ospi: Fix llvm compilation error

### PR DESCRIPTION
**Pull request by de-nordic**
Fix compilation error on variable used for size of array.

Fixes #61804

Dumb fix for the issue. I guess that MIN would not let the array to be larger than 20 anyway.

### CODE REVIEW

**Review by danielstuart14 — COMMENTED** [review]
https://github.com/zephyrproject-rtos/zephyr/blob/8023d59509d9226bb4293d852f6562c3f7a02b54/drivers/flash/flash_stm32_qspi.c#L1312

QSPI driver has the same issue of VLA inside struct. Would be nice if this was also fixed in the same PR. 

-----------------------------------------------------------------------------------------

https://github.com/zephyrproject-rtos/zephyr/blob/8193c6b83f4b4942ec84108d6e80919235514c0c/drivers/flash/flash_stm32_ospi.c#L2211-L2212

I think it should be something like this:
`ret = ospi_read_sfdp(dev, jesd216_param_addr(PHP),
					     (uint8_t *)u2.dw, sizeof(uint32_t) * MIN(php->len_dw, 20));`

This way the transaction is still of the same length as before.

**Comment by erwango** [comment]
@de-nordic Thanks for fixing this. Comments from @danielstuart14 looks sane, do you plan to address them ?

**Comment by de-nordic** [comment]
> @de-nordic Thanks for fixing this. Comments from @danielstuart14 looks sane, do you plan to address them ?



> @de-nordic Thanks for fixing this. Comments from @danielstuart14 looks sane, do you plan to address them ?

Getting a free fix from competition and yet still impatient.

**Comment by erwango** [comment]
> Getting a free fix from competition and yet still impatient.

:-D Sorry, it was just a status update, didn't want to rush you . Thanks again !

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Pull request merged**
