### PR TITLE
soc: neorv32: NEORV32 core updates and new drivers

### PR DESCRIPTION
**Pull request by robhancocksed**
Various NEORV32-related updates/fixes:

- Update to support core revision 1.9.8. Note that this removes support for previous versions, as maintaining support for multiple versions seems rather impractical due to all the register location changes etc. Since this is a soft CPU core, it is assumed that users can upgrade their logic revision to match, which avoids the burden of trying to maintain support for multiple different versions.
- Fixed issues with UART driver in interrupt mode.
- Fixed compiled/linked code attempting to use RISC-V atomic instructions which NEORV32 doesn't yet support.
- Added support for the XIRQ external interrupt controller.
- Added support for watchdog timer.

Core revision updates based on a previous MR https://github.com/zephyrproject-rtos/zephyr/pull/66722 from @VolodymyrSvintozelskyi

### CODE REVIEW

**Comment by nordicjm** [comment]
> Update to support core revision 1.9.8. Note that this removes support for previous versions, as maintaining support for multiple versions seems rather impractical due to all the register location changes etc. Since this is a soft CPU core, it is assumed that users can upgrade their logic revision to match, which avoids the burden of trying to maintain support for multiple different versions.

Think a discussion is needed around that, you are silently breaking a board for all existing users which itself is not a good thing, but for an lts release just does not sit right

**Comment by robhancocksed** [comment]
> > Update to support core revision 1.9.8. Note that this removes support for previous versions, as maintaining support for multiple versions seems rather impractical due to all the register location changes etc. Since this is a soft CPU core, it is assumed that users can upgrade their logic revision to match, which avoids the burden of trying to maintain support for multiple different versions.
> 
> Think a discussion is needed around that, you are silently breaking a board for all existing users which itself is not a good thing, but for an lts release just does not sit right

It's not entirely clear how widely used the NEORV32 Zephyr port currently is yet in order to know whether this would cause a major issue for anyone. Some of the issues in previous versions of the core were causing some problems that were difficult to fix at the OS level - for example, the implementation-specific peripheral interrupts couldn't be cleared at the CPU core level in a consistent way between devices, meaning that the drivers ended up needing to manipulate the RISC-V CSRs in order to clear the interrupt properly. With the 1.9.8 release that is no longer needed. So I think it would be pretty difficult to support the existing core versions like 1.8.6 in general.

**Comment by robhancocksed** [comment]
It looks like the failing checks at the moment seem to be some test infrastructure issues (403 errors)?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Please split this into multiple PRs: One for updating the core support, and individual PRs after that for adding new drivers. The rationale for this is, that the different driver classes require reviews from different people. 

Please also see https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html

**Comment by nordicjm** [comment]
> > > Update to support core revision 1.9.8. Note that this removes support for previous versions, as maintaining support for multiple versions seems rather impractical due to all the register location changes etc. Since this is a soft CPU core, it is assumed that users can upgrade their logic revision to match, which avoids the burden of trying to maintain support for multiple different versions.
> > 
> > 
> > Think a discussion is needed around that, you are silently breaking a board for all existing users which itself is not a good thing, but for an lts release just does not sit right
> 
> It's not entirely clear how widely used the NEORV32 Zephyr port currently is yet in order to know whether this would cause a major issue for anyone. Some of the issues in previous versions of the core were causing some problems that were difficult to fix at the OS level - for example, the implementation-specific peripheral interrupts couldn't be cleared at the CPU core level in a consistent way between devices, meaning that the drivers ended up needing to manipulate the RISC-V CSRs in order to clear the interrupt properly. With the 1.9.8 release that is no longer needed. So I think it would be pretty difficult to support the existing core versions like 1.8.6 in general.

It's still a board with an implementation which people _might_ be using though, and if someone gets zephyr 3.6 and builds for `neorv32` and uses it (note: **no** version in the board name), then it works fine, then gets zephyr 3.7 and builds for `neorv32` then suddenly it doesn't work, that's not good. Other boards use board revisions properly, for example `nrf9160dk@0.7.0/nrf9160` and `nrf9160dk@0.14.0/nrf9160`, both versions are supported.

**Comment by henrikbrixandersen** [comment]
> It's still a board with an implementation which people _might_ be using though, and if someone gets zephyr 3.6 and builds for `neorv32` and uses it (note: **no** version in the board name), then it works fine, then gets zephyr 3.7 and builds for `neorv32` then suddenly it doesn't work, that's not good. Other boards use board revisions properly, for example `nrf9160dk@0.7.0/nrf9160` and `nrf9160dk@0.14.0/nrf9160`, both versions are supported. Maybe having a new version added and deprecating the old one if the old one has issues, but I don't think it should be removed for at least 2 zephyr releases that the new one has been added to, then it can be removed.

Not sure why the revision is not visible in the board target for the neorv32 board. The board _does_ have a revision (I introduced that for the exact problem outlined above). Shouldn't https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/others/neorv32/board.yml cause the board to have revision 1.8.6?

**Comment by nordicjm** [comment]
> > It's still a board with an implementation which people _might_ be using though, and if someone gets zephyr 3.6 and builds for `neorv32` and uses it (note: **no** version in the board name), then it works fine, then gets zephyr 3.7 and builds for `neorv32` then suddenly it doesn't work, that's not good. Other boards use board revisions properly, for example `nrf9160dk@0.7.0/nrf9160` and `nrf9160dk@0.14.0/nrf9160`, both versions are supported. Maybe having a new version added and deprecating the old one if the old one has issues, but I don't think it should be removed for at least 2 zephyr releases that the new one has been added to, then it can be removed.
> 
> Not sure why the revision is not visible in the board target for the neorv32 board. The board _does_ have a revision (I introduced that for the exact problem outlined above). Shouldn't https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/others/neorv32/board.yml cause the board to have revision 1.8.6?

Yes, but that's the default version so people will be using `cmake -DBOARD=neorv32 app` and that'll be it, now with these changes that will not change but suddenly it's building for a different soc version and will not build on the old one

**Comment by robhancocksed** [comment]
> > > > Update to support core revision 1.9.8. Note that this removes support for previous versions, as maintaining support for multiple versions seems rather impractical due to all the register location changes etc. Since this is a soft CPU core, it is assumed that users can upgrade their logic revision to match, which avoids the burden of trying to maintain support for multiple different versions.
> > > 
> > > 
> > > Think a discussion is needed around that, you are silently breaking a board for all existing users which itself is not a good thing, but for an lts release just does not sit right
> > 
> > 
> > It's not entirely clear how widely used the NEORV32 Zephyr port currently is yet in order to know whether this would cause a major issue for anyone. Some of the issues in previous versions of the core were causing some problems that were difficult to fix at the OS level - for example, the implementation-specific peripheral interrupts couldn't be cleared at the CPU core level in a consistent way between devices, meaning that the drivers ended up needing to manipulate the RISC-V CSRs in order to clear the interrupt properly. With the 1.9.8 release that is no longer needed. So I think it would be pretty difficult to support the existing core versions like 1.8.6 in general.
> 
> It's still a board with an implementation which people _might_ be using though, and if someone gets zephyr 3.6 and builds for `neorv32` and uses it (note: **no** version in the board name), then it works fine, then gets zephyr 3.7 and builds for `neorv32` then suddenly it doesn't work, that's not good. Other boards use board revisions properly, for example `nrf9160dk@0.7.0/nrf9160` and `nrf9160dk@0.14.0/nrf9160`, both versions are supported. Maybe having a new version added and deprecating the old one if the old one has issues, but I don't think it should be removed for at least 2 zephyr releases that the new one has been added to, then it can be removed.

For most of the DTS changes it would be possible to split up the files by version, though the question remains about how many versions we would eventually accumulate or need to support. It's a bit dirtier in that it's not just a difference at the board level but at the SoC level, so we would need to maintain separate .dtsi files for each version.

The bigger problem comes in with the actual code changes. In soc/neorv32/soc.h a bunch of the bits in the SYSINFO register were moved around, and in soc/neorv32/soc_irq.S some of the core interrupt handling code needs to be different between revisions. I'm not really sure how it's possible to support multiple versions there in a reasonable fashion?

I do suspect that the previous core revision was not widely used "in anger" with Zephyr due to the stability problems caused by some of the interrupt handling issues. This has been cleaned up and made a lot easier to support in current revisions of the core.

**Comment by nordicjm** [comment]
I would ask for a decision from @nashif about getting rid of old soc revisions and if there should be any time that it remains for being (deprecated) before being removed

**Comment by robhancocksed** [comment]
I raised this issue under this NEORV32 discussion: https://github.com/stnolting/neorv32/discussions/172

@stnolting (main NEORV32 developer) commented "In my humble opinion, only the latest/current version should be supported. Anything else would be far too much work in the end." and "this project is under constant development. Breaking changes are not planned, but they happen from time to time, especially when we discover a severe bug. And isn't such a bug-fix ultimately a "breaking" change?"

**Comment by robhancocksed** [comment]
I have pulled out the UART driver changes into https://github.com/zephyrproject-rtos/zephyr/pull/72385 as they are not directly dependent on anything else in the core updates. The WDT driver can't be extracted yet as it's dependent on some core device tree updates. If we agree on a path forward on the core updates, I can pull that out as a separate PR once the core changes go in.

**Comment by robhancocksed** [comment]
This PR needs some updates according to some feedback, but it's ultimately still waiting for a decision or discussion about whether we need to continue supporting old versions of the NEORV32 core in Zephyr. NEORV32 upstream suggests that would be too big of a maintenance burden, and I would tend to agree given that they tend to make changes in register mappings etc. on a somewhat regular basis.

**Comment by robhancocksed** [comment]
I haven't had much time to look at this lately, but if there are no objections to the general approach of just supporting the latest/recent version of NEORV32, then I can get this brought up to date and split up as needed..

**Comment by henrikbrixandersen** [comment]
> I haven't had much time to look at this lately, but if there are no objections to the general approach of just supporting the latest/recent version of NEORV32, then I can get this brought up to date and split up as needed..

No objections from my side. That would be a welcome addition.

**Pull request closed without merging**
