### PR TITLE
ec_host_cmd: spi_stm32: prevent accessing null pointer

### PR DESCRIPTION
**Pull request by niedzwiecki-dawid**
There is a possibility that the SPI STM32 Host Command backend is being suspended, without earlier initialization.

Make sure we are not accessing uninitialized pointer, namely the cs structure.

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
Feels like a problem with init sequencing though, how did you bump into this? Would it be possible to add a build check to prevent this in the first place? Or fix up some dependency in the devicetree so that it's checked automatically.

**Comment by niedzwiecki-dawid** [comment]
No exactly. This happens on FPMCU, one build includes SPI and UART backends. We detect in runtime, which one is used by AP and call the HC init after that (`CONFIG_EC_HOST_CMD_INITIALIZE_AT_BOOT=n`). I've added suspending an unused backed (SPI in this case), which causes using the cs structure, in the suspend procedure, which is not initialized.

**Comment by fabiobaltieri** [comment]
Ok, how about adding a flag to the device context to signal that the initialization has been completed and error out in the power management calls instead? That way you'd defend from any other potential initialize stuff as well, not just the gpio

**Comment by niedzwiecki-dawid** [comment]
Hmm, not sure, but I feel like calling pm action on a HC backend, that is not initialized is not a bad thing. The idea is to call the suspend for the unused backend and lock the pm state. Returning an error wouldn't allow to do that.

**Comment by fabiobaltieri** [comment]
Ok, then I would add the check to the resume code path as well, just in case it ends up getting called while not initialized a well for whatever reason, you'd get an error rather than crashing the whole thing.

**Review by fabiobaltieri — APPROVED** [review]

**Review by duda-patryk — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
