### PR TITLE
litex-vexriscv: Updates to drivers and device tree

### PR DESCRIPTION
**Pull request by michalsieron**
Updates for LiteX i2c, i2s and spi drivers so they support both 8-bit and 32-bit Control/Status registers
Also fix for ethernet driver and i2s sample

Because of default LiteX settings, I changed register data in device tree to 32-bit CSR variant.
Reference SoC [zephyr-on-litex-vexriscv](https://github.com/litex-hub/zephyr-on-litex-vexriscv) will be updated soon as well.

### CODE REVIEW

**Review by tgorochowik — DISMISSED** [review]

**Review by fkokosinski — DISMISSED** [review]

**Review by tgorochowik — APPROVED** [review]

**Comment by tgorochowik** [comment]
Marking this as a bugfix as this will help us avoid getting more reports like these: #44478 #42685 which all come from the fact of the reconfiguration possibilities.

**Review by fkokosinski — APPROVED** [review]

**Review by mbolivar-nordic — COMMENTED** [review]
Thanks for the patches. I read through them and I agree that they look like bugfixes, so I am going to merge them.

However, this pull request was marked "bug" but has no corresponding issue filed as far as I can tell. Since the pull request was opened during the stabilization period, it would have been better if you had filed an issue as well. @tgorochowik please take note.

**Comment by xyzzy42** [comment]
This broke the documentation build check.

dts/riscv/riscv32-litex-vexriscv.dtsi is included into an rst file, and the edited clock node was used as the start-at tag, which is no longer found and causes a failure building docs.

**Comment by stephanosio** [comment]
> This broke the documentation build check.

Fixed by https://github.com/zephyrproject-rtos/zephyr/pull/45907

**Pull request merged**
