### PR TITLE
boards: arm: wio terminal: separate buttons and joystick definition

### LINKED ISSUE #67049: Only the first five gpio-keys of wio-terminal seem to work
**Describe the bug**
Using two different [`wio_terminal`](https://docs.zephyrproject.org/latest/boards/arm/wio_terminal/doc/index.html) I could reproduce the weird behaviour, that only the first 5 entries in [`gpio-keys` or buttons](https://github.com/zephyrproject-rtos/zephyr/blob/e8ba19e0eee25cbaf694e0472ea0c266be69a3c3/boards/arm/wio_terminal/wio_terminal.dts#L50-L93) seem to work.

They are ordererd as:
```
	/* Buttons */
	gpio_keys {
		compatible = "gpio-keys";
		user_button_0: button_0 {...};
		user_button_1: button_1 {...};
		user_button_2: button_2 {...};
		joy_sel: joystick_selection {...};
		joy_down: joystick_down {...};
		joy_up: joystick_up {...};
		joy_left: joystick_left {...};
		joy_right: joystick_right {...};
	};
```
and just the buttons `_0`, `_1`, `_2` and `_selection` and `_down` are working. This can be observed in the [lvgl sample](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/display/lvgl) or with the following code:

```c
static void input_cb(struct input_event *evt)
{

  char buf[1000];
  snprintf(buf, sizeof(buf), "type: %d, code: %d, value: %d", evt->type, evt->code, evt->value);
  ... // print buf to display
}
INPUT_CALLBACK_DEFINE(NULL, input_cb);
```
Using this code only the first five entries show any sign of reaction.

The weird behaviour is, that reordering the entries to
```
	/* Buttons */
	gpio_keys {
		compatible = "gpio-keys";
		user_button_0: button_0 {...};
		joy_sel: joystick_selection {...};
		joy_left: joystick_left {...};
		joy_right: joystick_right {...};
		user_button_1: button_1 {...};
		user_button_2: button_2 {...};
		joy_down: joystick_down {...};
		joy_up: joystick_up {...};
	};
```
makes `_0`, `_selection`, `_left`, `_right` and `_1` available and allows to actually use the button matrix of the lvgl example.

**To Reproduce**
 ```
$ west build -b wio_terminal samples/subsys/display/lvgl
$ west flash
```
observe that button grid is displayed but only the select (press on joystick) has a visual reaction.

Reorder the entries as above, rebuild and flash and observe that right and left joystick movement is now working as expected.

**Expected behavior**
I would expect that all gpio_keys are working

**Impact**
Some buttons of the wio_terminal are not usable for no clear reason.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: bf2bdcf6f79cf9711b1fdee3f2d91a5e61603f29

### PR DESCRIPTION
**Pull request by joelguittet**
The purpose of this separation is to avoid conflict initializing gpio-keys because button 0 and joystick up have a shared interrupt source. Joystick is now configured using polling mode option.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/67049

### CODE REVIEW

**Comment by maxhbr** [comment]
at least in https://github.com/zephyrproject-rtos/zephyr/pull/67208#issuecomment-1883515868 there was discussion to reverse it and have the joystick with interrupts and the 3 buttons with polling mode:

> +1 for having the 3 "normal" buttons use the new polling mode, and leave the 5 joystick buttons as regular interrupt-driven keys

**Comment by joelguittet** [comment]
> at least in [#67208 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/67208#issuecomment-1883515868) there was discussion to reverse it and have the joystick with interrupts and the 3 buttons with polling mode:
> 
> > +1 for having the 3 "normal" buttons use the new polling mode, and leave the 5 joystick buttons as regular interrupt-driven keys

True, and this was something I initiated. Will modify.

**Comment by joelguittet** [comment]
@maxhbr done

**Comment by joelguittet** [comment]
Hello @maxhbr 

I made an overlay a bit different, I added the `input` entries, but this doesn't help. Then I made a little bit more modifications: I removed the buttons in the dts, so I kept only inputs-codes from the joystick. Seems working (at least the basics left/right/enter events).

=> The lvgl_xxx_input do not work when there are multiple gpio-keys compatible node in the board definition. @faxe1008 maybe this is somethingyou know more than us ?

**Comment by joelguittet** [comment]
@kartben this PR has no automatic reviewers assigned. Maybe you can help here ? Thanks!

**Comment by joelguittet** [comment]
@maxhbr I have updated this PR:
- the device tree has now the joystick configured in polling mode. Buttons need toi be set with interrupt to prevent the `<err> app: failed to enable button callback: -16` error you have reported in the lvgl sample.
- I have added wio terminal configuration and overlay for the lvgl sample. Seems to be working according to me, can you check this is suitable ? Thanks!

**Review by maxhbr — APPROVED** [review]
I tested it and it works perfectly fine. Great! :tada:

**Review by kartben — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
