### PR TITLE
Revert "samples: sockets: Don't open the socket if the test protocol …

### PR DESCRIPTION
**Pull request by pfalcon**
…is enabled"

This reverts commit da0f3311ff1dddca06c42220bd51857fb3b4080a.

### CODE REVIEW

**Comment by pfalcon** [comment]
A visibly local-debugging change has got into mainline, apparently overlooked while handling the massive https://github.com/zephyrproject-rtos/zephyr/pull/20027. It breaks building this sample for native POSIX systems, which is one of the primary purposes of this sample - to ensure that Zephyr's implementation of POSIX is actually compatible with other POSIX systems, and it's possible to write POSIX applications portable to Zephyr. The issue was pointed out by @aescolar.

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by pfalcon** [comment]
Thanks for review. Added sign-off to make checkstyle happy.

**Review by ozhuraki — APPROVED** [review]
LGTM

**Pull request merged**
