### PR TITLE
drivers: gpio: Unavailable pins Px15.

### PR DESCRIPTION
**Pull request by baden**
Unable using all pins PA15, PB15, PC15, etc.

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]
LGTM, thanks.

**Review by kartben — APPROVED** [review]
Nice catch!
Please look into the reported compliance issues. Thanks!

**Comment by cyliangtw** [comment]
Thanks, it could fix the missing pins of Px15.

Remind to resolve the failing of signed-off-by in compliance Checks by:
 `$ git commit -s  -m "drivers: gpio: fix bug of unavailable pins Px15`

**Comment by kartben** [comment]
@baden could you please look at amending your commit as per the latest posted comment?
Thanks!

**Comment by kartben** [comment]
cherry-picked in #72216

**Pull request closed without merging**
