### PR TITLE
Shell kernel cmds adaptation

### LINKED ISSUE #8880: Adapt kernel commands to new shell subsystem
In subsys/shell/kernel_service.c shell commands are implemented. They need to be ported to new shell once available.

### PR DESCRIPTION
**Pull request by nordic-krch**
PR contains #9362 and should be merged together or after 'parent' PR.

Commands from kernel_service.c ported to new shell subsystem.

Fixes #8880

### CODE REVIEW

**Comment by nashif** [comment]
@nordic-krch please rebase

**Comment by nordic-krch** [comment]
rebased, removed DNM label.

**Comment by nashif** [comment]
I am not getting the expected command when I run this for qemu_x86

**Comment by nordic-krch** [comment]
@nashif by default kernel commands are disabled in menuconfig in this example. I ran enable them by default.

**Comment by nashif** [comment]
> @nashif by default kernel commands are disabled in menuconfig in this example. I ran enable them by default.

ah, no wonder. Not sure why it was disabled. Can we enable this again?

**Review by nashif — APPROVED** [review]

**Pull request merged**
