### PR TITLE
Bluetooth: controller: fixing CIS establish flow for refactored LLCP

### PR DESCRIPTION
**Pull request by erbr-ot**
Latest modification to LLCP removed 'monitoring' of cis->established flag in LLCP, relying instead on signal through ULL.

For this to work properly the signal must also be generated, so this is introduced. Note - checking of cis->established flag could be removed if caller ensures only calling once (on establish condition)

### CODE REVIEW

**Review by Thalley — DISMISSED** [review]

**Review by mtpr-ot — DISMISSED** [review]
LGTM

**Comment by erbr-ot** [comment]
trigger CI rerun

**Review by Thalley — APPROVED** [review]

**Review by mtpr-ot — APPROVED** [review]
Still LGTM

**Comment by Thalley** [comment]
@carlescufi Can you please merge this ASAP? It's blocking Bluetooth Audio CI :)

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
