### PR TITLE
boards: shields: add MikroElektronika ACCEL Click shield

### PR DESCRIPTION
**Pull request by iandmorris**
Add shield definition for the MikroElektronika ACCEL Click. The ACCEL Click carries a ADXL345 3-axis accelerometer sensor in a mikroBUS form factor.

### CODE REVIEW

**Review by kartben — COMMENTED** [review]
Great!

I think it would be better to have all variations of ACCEL clicks be *revisions* of a base ACCEL shield (which would be this one). Would you be able to give this a try and rework the existing ACCEL 13, if you think it's a good idea?

Also, I would love to figure out a way to auto-generate shield definitions for clicks somehow. It feels like Mikroelektronika already maintains and provides at least *some* metadata for each click in their GitHub repo, but definitely not to the point where part numbers or I2C addresses of the sensors are captured. Maybe I should try to reach out to them to see what would be possible :)

**Comment by iandmorris** [comment]
@kartben, I like your suggestions. Let me take a look and see if I can figure out how to create variants that are revisions of this base shield.

**Comment by kartben** [comment]
Great! I think one of the main benefits will be to minimize the overhead for someone interested in contributing a new click shield where another variant already exists, since they will have a lot less boilerplate files to create (docs, Kconfig, ...). Speaking of docs, we'll likely want to have some kind of "framework" there to have a consistent way to describe all the variants on the same page.

**Comment by iandmorris** [comment]
@kartben , just getting back to this and it seems like the best approach might be as detailed here:

https://docs.zephyrproject.org/latest/hardware/porting/shields.html#shield-variants

Do you agree?

**Comment by kartben** [comment]
> @kartben , just getting back to this and it seems like the best approach might be as detailed here:
> 
> [docs.zephyrproject.org/latest/hardware/porting/shields.html#shield-variants](https://docs.zephyrproject.org/latest/hardware/porting/shields.html#shield-variants)
> 
> Do you agree?

yep, +1!

I think the only drawback I can envision is that this means we slightly deviate from the "actual" commercial name of the shields. I.e.  where someone would expect a `mikroe_accel13_click` for the "ACCEL 13" they would now look for `mikroe_accel_click_13` which might be (slightly, imo?) confusing. But I think the benefits we get in terms of consolidating docs, common DT bits, etc. far outweigh this minor inconvenience. In fact, if really needed, we might be able to setup "shield aliases" similar to how there is a concept of board aliases.

Would also be curious to hear @erwango's thoughts on the topic.

**Comment by iandmorris** [comment]
@erwango, do you have any comments regarding the use of [shield variants](https://docs.zephyrproject.org/latest/hardware/porting/shields.html#shield-variants) to support different Mikroe Accel Click shield boards with a common set of shield files, as described above?

**Pull request closed without merging**
