### PR TITLE
boards: Add UART6 for 96b_carbon

### PR DESCRIPTION
**Pull request by ric96**
Enabled UART 6 on pin PC6 and PC7 for 96b_carbon

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

### CODE REVIEW

**Comment by ric96** [comment]
@galak any clue on why the tests are failing?

**Comment by ydamigos** [comment]
You should rebase your PR with the latest master branch. I believe, it is missing commit 7b6f371e2ae861fbf774388494dbd3c31a67f7c1.

**Review by galak — COMMENTED** [review]
Why?  Is something connected to USART6?

**Comment by ydamigos** [comment]
>Why? Is something connected to USART6?

USART6 is available on 96b_carbon's J1 connector (30 pins connector).

**Comment by ric96** [comment]
@galak as @ydamigos said, just want to expose the uart6 (pc6 and pc7) on the 30 pin connector

**Review by galak — APPROVED** [review]

**Pull request merged**
