### PR TITLE
i2c: add target mode to Silicon Labs Gecko I2C driver

### PR DESCRIPTION
**Pull request by kmeinhar**
This commits adds the ability to use Silicon Lab chips as an I2C target.
This could be used together with the EEPROM target driver.

@fkokosinski

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi @kmeinhar, thanks for this PR.

Could you:
1. Remove formatting changes from this PR, or at least move them to a different commit? That would make reviewing your changes much easier.
2. Try running `tests/drivers/i2c/i2c_target_api`?

**Comment by fkokosinski** [comment]
@kmeinhar it seems that there's a misformatted commit on your branch (more details in the compliance check job). Could you fix that?

**Comment by kmeinhar** [comment]
> @kmeinhar it seems that there's a misformatted commit on your branch (more details in the compliance check job). Could you fix that?

Thanks for checking, sadly I was not yet able to find the time to fix it. I will ping you once the PR is in a clean state.

**Review by teburd — APPROVED** [review]

**Comment by teburd** [comment]
All commits need a message body, will reapprove once CI passes

**Comment by kmeinhar** [comment]
The Checks are now all green and all commits have a message body.
Could you take another look? @fkokosinski and @teburd

**Review by fkokosinski — APPROVED** [review]
LGTM

**Pull request merged**
