### PR TITLE
Add DMA support on STM32C0-series

### PR DESCRIPTION
**Pull request by benjaminbjornsson**
It is possible to build and run `tests/drivers/dma/chan_blen_transfer/` using west with passing test results.
However, when running with twister on target it is filtered with too little memory.

Not really sure what's the best way to verify this drivers functionality.

### CODE REVIEW

**Comment by erwango** [comment]
> It is possible to build and run `tests/drivers/dma/chan_blen_transfer/` using west with passing test results.
However, when running with twister on target it is filtered with too little memory.

This 16K ram limit was set by @nashif in [`2de59023`](https://github.com/zephyrproject-rtos/zephyr/commit/2de59023dc726e61244eb7cca17252294016c65a#diff-6ed1a3afc196729b853ece75d45cb1f57b0e68d15abaa5c1758b95cef4e8d86c), but indeed, on STM32, this test requires less than 6K.
I had a quick check on various platform, and it seems that this test has indeed variing requirements in terms of memory footprint (usually under 16K though), which I guess is the reflect of DMA driver implementation that can highly differ depending on architectures. But this observation also shows that the test itself doesn't abuse of memory resources.

One idea could be to add a "low footprint" variant in yaml which would run on a selected set of platforms.
Another idea is to simply remove this limit assuming that each architecture implement a DMA driver which fits its resources and the test itself won't add too much additional load on platform resources.

**Comment by erwango** [comment]
@benjaminbjornsson I'd propose to go with "One idea could be to add a "low footprint" variant in yaml which would run on a selected set of platforms."

**Comment by benjaminbjornsson** [comment]
@erwango sorry for my late response, great idea with a low footprint variant. Have updated with a 6k ram variant that only runs on nucleo c031c6 for now.

**Comment by erwango** [comment]
@benjaminbjornsson Please rebase

**Review by gautierg-st — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
