### PR TITLE
tests: drivers: build_all: split gsm and add mux test

### PR DESCRIPTION
**Pull request by ycsin**
- Fix compilation issue due to unmatched `size_t` variable types for 32 & 64 bit MCU
- Fix `gsm_mux` macro namespace issue with `nuvoton_pfm_m487`
- Split gsm driver test out and add build test for the MUX configuration

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]
Looks ok to me

**Comment by ycsin** [comment]
Haven't gone through thoroughly but seems like it found some issues with 64bit soc?
```
/__w/zephyr/zephyr/drivers/console/gsm_mux.c:247:31: note: format string is defined here
  247 |   LOG_DBG("%d: Too long msg (%d)", __LINE__, ret - sizeof(out));
      |                              ~^
      |                               |
      |                               int
      |                              %ld
```

and redefinition of a macro in `nuvoton_pfm_m487`?

```
/__w/zephyr/zephyr/drivers/console/gsm_mux.c:33: error: "PF" redefined [-Werror]
   33 | #define PF 0x10  /* Poll / Final       */
      | 
In file included from /__w/zephyr/modules/hal/nuvoton/m48x/Devices/M480/Include/NuMicro.h:12,
                 from ../../../../../../../soc/arm/nuvoton_numicro/m48x/soc.h:12,
                 from ../../../../../../../include/arch/arm/aarch32/cortex_m/cmsis.h:17,
                 from ../../../../../../../include/arch/arm/aarch32/mpu/arm_mpu_v7m.h:11,
                 from ../../../../../../../include/arch/arm/aarch32/mpu/arm_mpu.h:14,
                 from ../../../../../../../include/arch/arm/aarch32/arch.h:194,
                 from ../../../../../../../include/arch/cpu.h:19,
                 from ../../../../../../../include/kernel_includes.h:33,
                 from ../../../../../../../include/kernel.h:17,
                 from /__w/zephyr/zephyr/drivers/console/gsm_mux.c:10:
/__w/zephyr/modules/hal/nuvoton/m48x/Devices/M480/Include/M480.h:375: note: this is the location of the previous definition
  375 | #define PF                   ((GPIO_T *)  GPIOF_BASE)
      | 
```

**Comment by rlubos** [comment]
> seems like it can only build for either the `native_posix` or the `native_posix64`, is there any workaround for this? I can only think of up-casting all of them to `unsigned long int`.
> 
> ```
> /__w/zephyr/zephyr/drivers/console/gsm_mux.c:221:47: error: format specifies type 'long' but the argument has type 'unsigned int' [-Werror,-Wformat]
>                 LOG_DBG("%d: Too long msg (%ld)", __LINE__, ret - sizeof(out));
>                                            ~~~              ^~~~~~~~~~~~~~~~~
>                                            %u
> ```
> 
> @rlubos @jukkar

Yeah, those errors are a bit of a pain. In theory, it should be possible to use fixed-size types and symbols from https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/libc/minimal/include/inttypes.h, but I recall that the compiler still complained on some platforms when I tried to use them to address this issue in some other PR. I've ended up doing exactly what you suggest, i.e. leaving the type used in the string as it was, and explicitly casting the argument provided (https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/lwm2m/lwm2m_util.c#L384).

Perhaps someone has a better solution though, I would be happy to hear if this could be addressed in a better way.

**Review by jukkar — APPROVED** [review]
Thanks, LGTM!

**Review by rlubos — APPROVED** [review]

**Review by rerickson1 — APPROVED** [review]

**Pull request merged**
