### PR TITLE
mgmt: mcumgr: Fix Bluetooth notification issue

### LINKED ISSUE #49661: mcumgr: bt transport runs in system workqueue thread and can cause resource deadlock
**Describe the bug**
The bluetooth transport for mcumgr runs in the system workqueue, this presents a problem if there are limited numbers of buffers as sending notifications over bluetooth will take a buffer, or wait indefinitely if there is not one available, and the buffers are freed up in a system workqueue task, which means if there are insufficient buffers available, the code will deadlock until the other bluetooth device disconnects

**To Reproduce**
Use bluetooth mcumgr transport and send a lot of data in one go e.g. 80 byte payload with 4.0 MTU (23 bytes)

**Expected behavior**
The data to be sent successfully without the code locking up

**Impact**
Showstopper

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 
 - Commit SHA or Version used: 88aa873fbc544b99c1e48e37d5c74662f90b3de0

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes an issue whereby smp_bt runs from the system workqueue, which
would cause it to lock up if there were insufficient buffers, by now
running it in a separate workqueue.

Fixes #49661

### CODE REVIEW

**Comment by stephanosio** [comment]
Rebased to fix CI failure

**Comment by nordicjm** [comment]
Reworked this to fix the issue differently, moved mcumr SMP to its own dedicated work queue and added delays to the SMP BT notifications if sending fails, plus trying to reduce the MTU until it is not at an acceptable level which might help if there is a larger MTU than outgoing buffer size for Bluetooth

**Comment by stephanosio** [comment]
Needs a rebase

**Comment by nordicjm** [comment]
> Needs a rebase

Rebased

**Review by de-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
