### PR TITLE
riscv: timer: Avoid potential overflow in tick difference calculations

### PR DESCRIPTION
**Pull request by robhancocksed**
In sys_clock_set_timeout, the number of ticks into the future was clamped to avoid potentially causing calculations based on tick differences to overflow. However, this didn't prevent the case where the timeout was repeatedly reset to the maximum interval into the future before the timer ISR ever fires. This can happen if a timeout is repeatedly added and then removed before expiry and no other pending timers are active. In this case, once more than 2^32 ticks expire after the last timer ISR, the tick difference calculations overflow causing all kinds of havoc, such as the TIMECMP value being set to a time in the past and the timer ISR firing continuously.

Add a check to explicitly clamp the number of cycles since the last timer ISR for TIMECMP to 2^31 to ensure that the timer ISR fires at least that many cycles, to avoid this potential overflow.

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
Sorry, this slipped through the cracks.   Can you explain the failure case here a little better?   As I see it last_count is set affirmatively to the correct value every time through the ISR.  It's true that it can wrap around (after a **long** time),  but the calculation it's used in will always produce the correct answer for when to schedule the next interrupt?

**Comment by robhancocksed** [comment]
> Sorry, this slipped through the cracks. Can you explain the failure case here a little better? As I see it last_count is set affirmatively to the correct value every time through the ISR. It's true that it can wrap around (after a **long** time), but the calculation it's used in will always produce the correct answer for when to schedule the next interrupt?

The failure case we saw was on the NEORV32 FPGA soft core platform, where we were doing a firmware update operation, which involved a bunch of writes to SPI flash. Each of the write operations set a timeout timer, but which normally always get cancelled prior to expiry, and since no other timeouts were active, no timer ISRs actually run during this process. The firmware update process could take over 34 seconds, which is the time it takes for 2^32 clock cycles to elapse at 125 MHz clock rate. Afterwards, the next time the timer ISR does fire, things started going haywire with it running continuously due to the TIMECMP values being always in the past.

The problem is essentially that the existing code made sure that a timeout wasn't set more than 2^31 cycles into the future, but it didn't make sure that it wasn't set more than 2^31 (or even 2^32) cycles since the last timer ISR. If that happens, the conversion of dcycles from uint64_t to cycle_diff_t in timer_isr overflows:
```
	uint64_t now = mtime();
	uint64_t dcycles = now - last_count;
	uint32_t dticks = (cycle_diff_t)dcycles / CYC_PER_TICK;
```

which causes a bunch of subsequent incorrect calculations. This change essentially forces the timer ISR to fire no later than 2^31 cycles after the previous one if any timeout is active.

I guess this is kind of the tradeoff with the optimization of trying to do most of the harder calculations using 32-bit rather than 64-bit math. There might be a better solution, but this was a rather painful problem to track down, and I wouldn't want anyone else to run into it, heheh.

**Comment by andyross** [comment]
> If that happens, the conversion of dcycles from uint64_t to cycle_diff_t in timer_isr overflows:

I'm still not seeing it? In the example you snipped, mtime(), now, dcycles, last_count and the division that produces dticks are all 64 bit.  Where's the overflow?

**Comment by andyross** [comment]
Oh wait, I see it.  "cycles_diff_t" is an architecture dependent type (it's typedef'd to an unsigned long) and the cast is on the dcycles numerator and not the result of the division.  So on your riscv32 platform you do indeed truncate before dividing.

Seems like this is mostly a typo, and the expression should have been "`dticks = (uint32_t)(dcycles / CYC_PER_TICK);`" instead.  Can you try that?   The 64 bit divide is nontrivially expensive, but the truth is that it's clear this driver was written to be 64 bit native.   If we want to optimize for 32 bit platforms it has a ton more work needed.

**Comment by teburd** [comment]
This seems like a very testable case and I’d love to see the test scenario added to a timer test. We’ve had subtle bugs before that take a great deal of time to find. This sort of test the extremes setup would be useful imho.

**Comment by robhancocksed** [comment]
> Oh wait, I see it. "cycles_diff_t" is an architecture dependent type (it's typedef'd to an unsigned long) and the cast is on the dcycles numerator and not the result of the division. So on your riscv32 platform you do indeed truncate before dividing.
> 
> Seems like this is mostly a typo, and the expression should have been "`dticks = (uint32_t)(dcycles / CYC_PER_TICK);`" instead. Can you try that? The 64 bit divide is nontrivially expensive, but the truth is that it's clear this driver was written to be 64 bit native. If we want to optimize for 32 bit platforms it has a ton more work needed.

I suspect if we changed that to do a native 64-bit divide, then it's not really worth having this cycle_diff_t type involved at all. It looks like that was something added by @npitre in "riscv: timer: driver revamp" and committed by @nashif, there was a note that "Runtime 64-bits divisions on 32-bits hardware are very expensive".

**Comment by npitre** [comment]
> Seems like this is mostly a typo, and the expression should have been "
> dticks = (uint32_t)(dcycles / CYC_PER_TICK);

No no. That _is_ exactly what this code is meant to avoid.
64-bit divisions on 32-bit archs are a real pain. Even more so if no
actual div instruction are available.

**Comment by andyross** [comment]
> No no. That is exactly what this code is meant to avoid.

Yeah, but it's wrong.  :) Can we refactor this to discriminate on sizeof(long) or whatever so the single division gets emitted correctly on 64 bit platforms and we pay the cost of the more elaborate clamping only where needed?

**Comment by npitre** [comment]
I agree something is wrong.

And this PR is probably the right fix ... well I'll even say "implementation"
for the original intended purpose, and I probably went overboard with 
complicated upfront clamping when it can be done much more directly.

Let me think about it.

**Comment by npitre** [comment]
This PR is not sufficient to fix the flawed clamping logic.

Please have a look at PR #72326 where I reworked it, fixing more flaws
along the way.

**Pull request closed without merging**
