### PR TITLE
tests: buf: Make testcase looks similar to other testcases

### PR DESCRIPTION
**Pull request by punitvara**
All test case should have entry function in main.c file and
other functions should be called from separate file.

JIRA: ZEP-2249

Signed-off-by: Punit Vara <punit.vara@intel.com>

### CODE REVIEW

**Comment by Vudentz** [comment]
Reading the jira description does really say we should split the files in certain order, having more files just for the sake of looking similar sounds pretty weak argument.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
NACK

The linked JIRA 2249 is about the *output* of the test cases.
I see no value in splitting up the files like this

**Comment by punitvara** [comment]
@andrewboie @Vudentz  If file structure will be same , then probably in future if we want python script for some case this consistent file structure could be easy to parse. What do you think ?

**Comment by Vudentz** [comment]
@punitvara we should probably not impose any rules regarding files structures, not sure about python scripting, I don't think we would like to bring python dependencies down to tests.

**Comment by punitvara** [comment]
@Vudentz  Ok. I am closing this.

**Pull request closed without merging**
