### PR TITLE
sample/shields: Fix printf with float

### PR DESCRIPTION
**Pull request by avisconti**
After that libc printf() switched to cbprintf() as basis (see 7cf9a8c)
there is a need to declare CONFIG_CBPRINTF_FP_SUPPORT=y in every sample
code that needs to print floats out.

NOTE:
This PR is fixing all x_nucleo shields, but there is one other shield, lmp90100_evb, which seems to require same change. I do not have that board to test it out. Nevertheless, the fix seems quite simple and should not break anything. So, let's decide whether to include that shield also in this PR.

### CODE REVIEW

**Review by pabigot — COMMENTED** [review]
I'm not sure doing this in the shields is the right approach.  Rather it should be done in samples that use floating point formatting.  It's not too hard to locate those; I'll try to get a PR in this morning, then we can see whether that's a more targeted solution.

**Comment by pabigot** [comment]
> Rather it should be done in samples that use floating point formatting.

Of course, this is where that's being done.  It's just doing a few of them.  Lemme see how a tree-wide approach works....

**Comment by pabigot** [comment]
#30058 is another possible solution.

**Comment by avisconti** [comment]
> #30058 is another possible solution.

Yes, I know that I'm touching only a few of them. A smart recursive command is of course better. Let me check your command better. It seems the right direction

**Comment by avisconti** [comment]
> > #30058 is another possible solution.
> 
> Yes, I know that I'm touching only a few of them. A smart recursive command is of course better. Let me check your command better. It seems the right direction

@pabigot 
It seems, at a first glance, that x_nucleo_iks01a3/sensorhub is somehow missing.

**Comment by avisconti** [comment]
@pabigot 
x_nucleo_iks01a3/sensorhub is using shub.conf and not prj.conf. I think that's why.

**Comment by avisconti** [comment]
Also x_nucleo_iks02a1/sensorhub is missing for the same reason. I don't know why I used shub.conf instead of prj.conf, my bad. But I don't think there was any requirement on the conf name, right?

**Comment by avisconti** [comment]
superseeded by #30058

**Pull request closed without merging**
