### PR TITLE
Fix Coverity scan issues in tinycrypt

### PR DESCRIPTION
**Pull request by ramakrishnapallala**
Fixes Coverity scan reported issues.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Changes to ext/ should be made to the upstream repos and imported back in.  We should submit patches to https://github.com/01org/tinycrypt

**Comment by lpereira** [comment]
The patch is correct, but please send it upstream first.  When it's accepted by TinyCrypt, we can merge it in Zephyr as a backport.  They're often very responsive.

**Review by lpereira — APPROVED** [review]
The patch is correct, but please send it upstream first. When it's accepted by TinyCrypt, we can merge it in Zephyr as a backport. They're often very responsive.

**Comment by lpereira** [comment]
This patch has been [reviewed and accepted upstream](https://github.com/01org/tinycrypt/pull/25).  It can be merged into Zephyr now.

**Review by nashif — APPROVED** [review]

**Pull request merged**
