### PR TITLE
arch/arm: Fix gcc-9.2 warning with z_arch_syscall_invoke6

### PR DESCRIPTION
**Pull request by galak**
Fix the following warning from gcc-9.2:

arm/syscall.h:52:2: error: listing the stack pointer register 'sp'
 in a clobber list is deprecated [-Werror=deprecated]
   52 |  __asm__ volatile("svc %[svid]\n"
      |  ^~~~~~~

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
Yeah, I know this is depreciated, but this should be warning in GCC not error...
Maybe with 9.2 this has changed.

**Comment by galak** [comment]
> Yeah, I know this is depreciated, but this should be warning in GCC not error...
> Maybe with 9.2 this has changed.

it is a warning and we treat warnings as errors w/sanitycheck.  Already made a similar change on x86.

commit 885b1ee7dee796bba4723cd84ce6641b38003808
Author: Kumar Gala <kumar.gala@linaro.org>
Date:   Thu Oct 3 18:31:51 2019 -0500

    arch/x86: Fix gcc-9.2 warning with z_arch_syscall_invoke6

**Comment by ioannisg** [comment]
> > Yeah, I know this is depreciated, but this should be warning in GCC not error...
> > Maybe with 9.2 this has changed.
> 
> it is a warning and we treat warnings as errors w/sanitycheck. Already made a similar change on x86.
> 
> commit [885b1ee](https://github.com/zephyrproject-rtos/zephyr/commit/885b1ee7dee796bba4723cd84ce6641b38003808)
> Author: Kumar Gala [kumar.gala@linaro.org](mailto:kumar.gala@linaro.org)
> Date: Thu Oct 3 18:31:51 2019 -0500
> 
> ```
> arch/x86: Fix gcc-9.2 warning with z_arch_syscall_invoke6
> ```

Sure. Now that you are here, let me see if we can clean up the syscall stuff for ARM. hang on

**Comment by ioannisg** [comment]
@galak i wonder if you could just add "ip" to clobber for all syscall invoke functions.
Not seen any errors, but i assume it's the right thing to do

**Comment by galak** [comment]
> @galak i wonder if you could just add "ip" to clobber for all syscall invoke functions.
> Not seen any errors, but i assume it's the right thing to do

Any update on this, would like to merge this at least to make progress on the gcc-9 front...

**Comment by andrewboie** [comment]
> @galak i wonder if you could just add "ip" to clobber for all syscall invoke functions.
Not seen any errors, but i assume it's the right thing to do

why would IP be clobbered? Can you give more detail? After the system call returns IP is just the next instruction after the SW trap

**Review by tyrantlizard77 — APPROVED** [review]
this looks good to me.
I don't get why "sp" was there in the first place, invoking a syscall should not clobber the stack pointer on any arch.

**Comment by ioannisg** [comment]
> > @galak i wonder if you could just add "ip" to clobber for all syscall invoke functions.
> > Not seen any errors, but i assume it's the right thing to do
> 
> Any update on this, would like to merge this at least to make progress on the gcc-9 front...

Looking at it today.

**Comment by ioannisg** [comment]
@andrewboie @galak , as said, "sp" should be removed, no objection to this.

Regarding "ip", the reason for adding this, is that arch_syscall_invoke6(...) is almost-always inlined, so the "ip" might be holding some value from previous calculations in the same routine; we need to tell compiler that "ip" is changed inside the SVC call framework, and, therefore, it should not be used to store stuff. Note that we do this for the other caller-saved registers (i.e. r1, r2, r3) in the rest of arch_syscall_invokeX(...) functions. [r0 not needed as it hold the return value from the system call].

I believe we should clobber "ip" for all system call invoke functions to prevent compiler errors, that's why I 've been holding this PR :)

Copying @stephanosio; maybe he has a better view of this.

Below there's a sample code, that **(I think)** it confirms my findings.

**Comment by ioannisg** [comment]
The following source code from `tests/kernel/mem_protect/syscalls/main.c` compiles into the ASM code below, using
- zephyr SDK
- ARMv6-M architecture
```

	zassert_equal(syscall_arg64_big(1, 2, 3, 4, 5, 6),
		      z_impl_syscall_arg64_big(1, 2, 3, 4, 5, 6),
		      "syscall didn't match impl");

```
```
 8000b6a:	2300      	movs	r3, #0
 8000b6c:	2102      	movs	r1, #2
 8000b6e:	2001      	movs	r0, #1
 8000b70:	f7ff ffa2 	bl	8000ab8 <z_impl_syscall_arg64_big>
 8000b74:	4684      	mov	ip, r0
 8000b76:	9105      	str	r1, [sp, #20]
extern u64_t z_impl_syscall_arg64_big(u32_t arg1, u32_t arg2, u64_t arg3, u32_t arg4, u32_t arg5, u64_t arg6);
static inline u64_t syscall_arg64_big(u32_t arg1, u32_t arg2, u64_t arg3, u32_t arg4, u32_t arg5, u64_t arg6)
{
#ifdef CONFIG_USERSPACE
	u64_t ret64;
	if (z_syscall_trap()) {
 8000b78:	2e00      	cmp	r6, #0
 8000b7a:	d026      	beq.n	8000bca <test_arg64+0xb2>
		union { struct { uintptr_t lo, hi; } split; u64_t val; } parm0;
		parm0.val = arg3;
		union { struct { uintptr_t lo, hi; } split; u64_t val; } parm1;
		parm1.val = arg6;
		uintptr_t more[] = {
 8000b7c:	2306      	movs	r3, #6
 8000b7e:	9309      	str	r3, [sp, #36]	; 0x24
 8000b80:	2300      	movs	r3, #0
			*(uintptr_t *)&arg5,
			parm1.split.lo,
			parm1.split.hi,
			(uintptr_t)&ret64
 8000b82:	aa06      	add	r2, sp, #24
		uintptr_t more[] = {
 8000b84:	9508      	str	r5, [sp, #32]
 8000b86:	920b      	str	r2, [sp, #44]	; 0x2c
 8000b88:	930a      	str	r3, [sp, #40]	; 0x28
	register u32_t ret __asm__("r0") = arg1;
 8000b8a:	2001      	movs	r0, #1
	register u32_t r1 __asm__("r1") = arg2;
 8000b8c:	2102      	movs	r1, #2
	register u32_t r2 __asm__("r2") = arg3;
 8000b8e:	2203      	movs	r2, #3
	register u32_t r5 __asm__("r5") = arg6;
 8000b90:	ad08      	add	r5, sp, #32
	register u32_t r6 __asm__("r6") = call_id;
 8000b92:	26b5      	movs	r6, #181	; 0xb5
	__asm__ volatile("svc %[svid]\n"
 8000b94:	df03      	svc	3
		};
		(void)arch_syscall_invoke6(*(uintptr_t *)&arg1, *(uintptr_t *)&arg2, parm0.split.lo, parm0.split.hi, *(uintptr_t *)&arg4, (uintptr_t) &more, K_SYSCALL_SYSCALL_ARG64_BIG);
		return (u64_t)ret64;
 8000b96:	9806      	ldr	r0, [sp, #24]
 8000b98:	9b07      	ldr	r3, [sp, #28]
		      "syscall didn't match impl");

	u64_t syscall_retval = syscall_arg64_big(1, 2, 3, 4, 5, 6);
	u64_t retval = z_impl_syscall_arg64_big(1, 2, 3, 4, 5, 6);

	zassert_equal(syscall_retval,
 8000b9a:	4662      	mov	r2, ip
 8000b9c:	4050      	eors	r0, r2
 8000b9e:	9a05      	ldr	r2, [sp, #20]
 8000ba0:	4912      	ldr	r1, [pc, #72]	; (8000bec <test_arg64+0xd4>)
 8000ba2:	4053      	eors	r3, r2
 8000ba4:	4318      	orrs	r0, r3
 8000ba6:	4243      	negs	r3, r0
 8000ba8:	4158      	adcs	r0, r3
 8000baa:	4b0c      	ldr	r3, [pc, #48]	; (8000bdc <test_arg64+0xc4>)
 8000bac:	b2c0      	uxtb	r0, r0
 8000bae:	9301      	str	r3, [sp, #4]
 8000bb0:	4b0c      	ldr	r3, [pc, #48]	; (8000be4 <test_arg64+0xcc>)
 8000bb2:	003a      	movs	r2, r7
 8000bb4:	9300      	str	r3, [sp, #0]
 8000bb6:	2381      	movs	r3, #129	; 0x81
 8000bb8:	005b      	lsls	r3, r3, #1
 8000bba:	f7ff fd3b 	bl	8000634 <z_zassert.constprop.9>
		      retval,
		      "syscall didn't match impl");
```

You can spot, perhaps, that "ip" is holding the return value of the call to `z_impl_syscall_arg64_big` and is used later in the assert statement.

**Comment by stephanosio** [comment]
I think there is a slight misunderstanding as to what "ip" register stands for ARM (it is not "instruction pointer" like in x86). ip aka. r12 is Intra-Procedure scratch register which can be clobbered by callee, just like r0-r3.

That said, it is important to note that SVC call on Cortex-M architecture raises SVCall exception, which, just like any other exception, triggers automatic exception stack frame preservation. Note that the Cortex-M exception stack frame includes r0-r3 and r12 (=ip); hence, it is not necessary to worry about ip getting clobbered by the SVCall handler.

**Review by ioannisg — APPROVED** [review]
approving this, but the extra commit should be looked at by others

**Comment by ioannisg** [comment]
> I think there is a slight misunderstanding as to what "ip" register stands for in ARM (it is not "instruction pointer" like in x86). ip aka. r12 is Intra-Procedure scratch register which can be clobbered by callee, just like r0-r3.

Exactly
 
> That said, it is important to note that SVC call on Cortex-M architecture raises SVCall exception, which, just like any other exception, triggers automatic exception stack frame preservation. Note that the Cortex-M exception stack frame includes r0-r3 and r12 (=ip); hence, it is not necessary to worry about ip getting clobbered by the SVCall handler.

The stacking of IP upon exception entry is absolutely accurate, @stephanosio , however the system calls in ARM Cortex-M are not performed _entirely_ in the SvC Handler. The handler only "prepares" the call, elevating the privileges,  however, the actual call is executed once the SvC handler _returns_ to the system call dispatcher, running in thread mode, and there, IP is not protected any more

**Comment by andrewboie** [comment]
> I think there is a slight misunderstanding as to what "ip" register stands for in ARM (it is not "instruction pointer" like in x86). ip aka. r12 is Intra-Procedure scratch register which can be clobbered by callee, just like r0-r3.

Thanks, this is exactly what confused me.

**Comment by galak** [comment]
LGTM.

**Pull request merged**
