### PR TITLE
[DNM] rebased topic-gpio build test 20200125

### PR DESCRIPTION
**Pull request by pabigot**
Several conflicts resolved.

Upstream merged #19510 which added a sample for CANopen.  This sample checks for active level using an expression that is compile-time false in topic-gpio, causing a build failure.  Commit  39086e08de2e6d8961d8ba2447d26954bac58a15 has been added here to resolve this.

In cleanup the non-standard commit subject prefix `[TOPIC-GPIO] ` was removed from the following commits:
```
* e7b086dd7d [Mon Oct 7 13:29:50 2019 -0700 vincent.wan@linaro.org] [TOPIC-GPIO] gpio: Update cc13x2/cc26x2 gpio driver to use new gpio api
* 73fccc156c [Wed Sep 25 13:54:43 2019 -0700 vincent.wan@linaro.org] [TOPIC-GPIO] gpio: Update cc32xx gpio driver to use new gpio api
```

### CODE REVIEW

**Comment by pabigot** [comment]
For the record: the canopen sample has to be converted here because this code:

```
[140/159] Building C object CMakeFiles/app.dir/src/main.c.obj
../src/main.c: In function 'led_callback':
../src/main.c:71:42: warning: bitwise comparison always evaluates to false [-Wtautological-compare]
   71 |  if ((led->flags & GPIO_INT_ACTIVE_HIGH) == GPIO_INT_ACTIVE_LOW) {
      |   
```
produces a build failure in CI.  In the topic branch both active level flags are distinct non-zero values, so the test can never succeed.

**Comment by henrikbrixandersen** [comment]
> For the record: the canopen sample has to be converted here because this code:

@pabigot CANopen sample changes verified on `twr_ke18f` and `frdm_k64f` development boards. Thank

**Comment by pabigot** [comment]
Aborting: merge of #21776 requires another rebase.  Reopening when that's done.

**Comment by pabigot** [comment]
Pushed all but DNM commit to topic branch.

**Pull request closed without merging**
