### PR TITLE
tests: Bluetooth: split `id_addr_update` test

### PR DESCRIPTION
**Pull request by jori-nordic**
Split FW into two images, one for central one for peripheral.

The SoftDevice controller's connection contexts are not role-agnostic: some are reserved for the peripheral roles some for the central roles.

Splitting the test into two images is anyway "The right thing (TM)", it's just that we sometimes take the shortcut of using a single image to go faster.

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

**Comment by Thalley** [comment]
> The SoftDevice controller's connection contexts are not role-agnostic: some are reserved for the peripheral roles some for the central roles.

Can you elaborate on this? Is the test causing issues for the SDC? Is something not working as expected if the SDC has been compiled for both cental and peripheral?

**Review by theob-pro — APPROVED** [review]

**Comment by jori-nordic** [comment]
> Can you elaborate on this

So when you have both `BT_CENTRAL=y` and `BT_PERIPEHRAL=y`, you have this logic kicking in:
https://github.com/jori-nordic/sdk-nrf/blob/2cac07ce70bffb7e65d31223b356306564c4e50b/subsys/bluetooth/controller/hci_driver.c#L42

I can't fix that downstream (not nicely at least) for this one test, apart from mirroring the build folder and building with `CONFIG_BT_CTLR_SDC_PERIPHERAL_COUNT=2`. 

Building with separate images is a lil bit wasteful of CI time - as you build twice - but it's more correct, as the real devices will likely only have one role compiled in.

I tried to fix this properly in sdk-nrf, ie having `BT_MAX_CONN` decoupled from the LL's role-specific memory but it caused so much pain by breaking CI tests, both build and runtime, that [I reverted](https://github.com/nrfconnect/sdk-nrf/pull/10867/files). 
I was a concerned that it'd break the customers' builds the same way, and it's my understanding we're trying to avoid that now in Zephyr and NCS.

**Comment by Thalley** [comment]
> Building with separate images is a lil bit wasteful of CI time - as you build twice - but it's more correct, as the real devices will likely only have one role compiled in.

Agreed that most devices won't have both, but there certainly are devices that are both. One example are a pair of TWS earbuds or hearing aids, where one is connected to e.g. a phone as peripheral, but connected to the other earbud as the central. 

IMO it sounds like this is an issue that should be fixed, rather than modifying the test that is failing. That being said, the purpose of the test being modified isn't to test this, so I'm fine with updating the test, but Nordic probably shouldn't ignore the above issue.

**Review by Thalley — APPROVED** [review]

**Comment by jori-nordic** [comment]
@Thalley nothing's broken when building with SDC, what I was trying to say is that if you have a combined build, you'd have to also have SDC-specific conf options to select how many peripherals you want. 
And adding a downstream config option to upstream is a no-no.

**Pull request merged**
