### PR TITLE
stm32: Make CLOCK_CONTROL selected by default on family

### PR DESCRIPTION
**Pull request by erwango**
- Select `CLOCK_CONTROL` by default on STM32 family
- Related clean up

### CODE REVIEW

**Comment by gautierg-st** [comment]
You're missing nucleo_u031r8 that was recently merged here: #77706

**Comment by erwango** [comment]
> You're missing nucleo_u031r8 that was recently merged here: #77706

Fixed, Thanks

**Review by gautierg-st — DISMISSED** [review]

**Review by duda-patryk — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
````
Area matches: {<Area STM32 Platforms>: 122, <Area ADI Platforms>: 3, <Area Google Platforms>: 2, <Area Drivers: Clock control>: 0}
...
candidate maintainers: {'erwango': 122, 'MaureenHelm': 3, 'fabiobaltieri': 2, 'keith-zephyr': 2, 'nordic-krch': 0}
Picked assignees: ['fabiobaltieri', 'keith-zephyr'] (1.14% ownership)
```

@nashif fyi

**Review by MaureenHelm — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]

**Comment by nashif** [comment]
> Area matches: {<Area STM32 Platforms>: 122, <Area ADI Platforms>: 3, <Area Google Platforms>: 2, <Area Drivers: Clock control>: 0}
> ...
> candidate maintainers: {'erwango': 122, 'MaureenHelm': 3, 'fabiobaltieri': 2, 'keith-zephyr': 2, 'nordic-krch': 0}
> Picked assignees: ['fabiobaltieri', 'keith-zephyr'] (1.14% ownership)

only issue is see here is that it picked you instead of Maureen, otherwise the script is doing what it is supposed to do, no?

**Comment by erwango** [comment]
- rebased

**Review by fabiobaltieri — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
