### PR TITLE
aarch32: timer: guard against use-before-init

### PR DESCRIPTION
**Pull request by yroeht**
This caused a call to arm_arch_timer_count() before arm_arch_timer_init().

See #51035 for some investigation of what was going on.

Signed-off-by: Théophile Ranquet <theophile.ranquet@gmail.com>

### CODE REVIEW

**Comment by yroeht** [comment]
There may be other instances of `arm_arch_timer_count` being called (as in, here, a call to `LOG_DBG`) before the timer is properly initialized, which may fail silently as this this one did. Not sure how to proceed to identity those.

**Review by carlocaione — DISMISSED** [review]
Please, write a small recap of the problem and how this change is fixing the issue in the commit message. In general we want to be `git blame` and `git log` friendly to not force people to retrieve some web-based ticket to understand what's going on with the change.

**Comment by yroeht** [comment]
> Please, write a small recap of the problem and how this change is fixing the issue in the commit message. In general we want to be `git blame` and `git log` friendly to not force people to retrieve some web-based ticket to understand what's going on with the change.

Is this better?

```
commit 76f508e6049f2889d811b68d2234b6259b163a64 (HEAD -> main, origin/main, origin/HEAD)
Author: Théophile Ranquet <theophile.ranquet@gmail.com>
Date:   Tue Oct 11 11:05:55 2022 +0200

    mmu: do not log before timer init
    
    syscon_generic_init(), at run level PRE_KERNEL_1, calls z_phys_map()
    which included a timestamped log message output via LOG_DBG.  This
    caused a call to arm_arch_timer_count() before arm_arch_timer_init(),
    which is only called at PRE_KERNEL_2.
    
    The resulting premature arm_arch_timer_count() call caused a read at an
    invalid address, which by chance in all current use-cases did not cause
    any data abort, but was not actual timer data.
    
    This starts to cause actual data aborts when memory layout is modified,
    such as the exception vector (non-)relocation in #51035, which no longer
    maps at 0x0.
    
    Signed-off-by: Théophile Ranquet <theophile.ranquet@gmail.com>
```

**Comment by yroeht** [comment]
To be honest, this occurs only in a LOG_DBG in Xilinx code, `uart_xlnx_ps_init@drivers/serial/uart_xlnx_ps.c`
which seems to call DEVICE_MMIO_MAP early.

```
(gdb) bt
#0  arm_arch_timer_count () at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/arch/arm/aarch32/cortex_a_r/sys_io.h:57
#1  sys_clock_elapsed () at /home/tranquet/zephyrproject-yroeht/zephyr/drivers/timer/arm_arch_timer.c:141
#2  0x0010bed4 in elapsed () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/timeout.c:64
#3  0x0010c5f8 in sys_clock_tick_get () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/timeout.c:292
#4  0x0010c688 in z_impl_k_uptime_ticks () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/timeout.c:308
#5  0x00105db8 in k_uptime_ticks () at /home/tranquet/zephyrproject-yroeht/build/zephyr/include/generated/syscalls/kernel.h:574
#6  k_uptime_get () at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/kernel.h:1618
#7  k_uptime_get_32 () at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/kernel.h:1642
#8  default_lf_get_timestamp () at /home/tranquet/zephyrproject-yroeht/zephyr/subsys/logging/log_core.c:200
#9  0x00106318 in z_log_msg_commit (msg=0x128000 <buf32>) at /home/tranquet/zephyrproject-yroeht/zephyr/subsys/logging/log_core.c:551
#10 0x0010cb54 in z_log_msg_runtime_vcreate (domain_id=0 '\000', data=0x0, dlen=0, package_flags=64, ap=..., fmt=0x0, level=<optimized out>, source=<optimized out>)
    at /home/tranquet/zephyrproject-yroeht/build/zephyr/include/generated/syscalls/log_msg.h:75
#11 z_log_msg_runtime_create (domain_id=0 '\000', source=<optimized out>, level=level@entry=4 '\004', data=0x0, dlen=0, package_flags=64, fmt=fmt@entry=0x111678 "arch_mem_map(%p, 0x%lx, %zu, %x) offset %lu", 
    package_flags=64, dlen=0, data=0x0, domain_id=0 '\000') at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/logging/log_msg.h:559
#12 0x0010d044 in z_phys_map (virt_ptr=0x0, phys=3758100480, size=76, flags=flags@entry=10) at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/mmu.c:748
#13 0x001095a4 in device_map (flags=2, size=<optimized out>, phys_addr=<optimized out>, virt_addr=<optimized out>) at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/sys/device_mmio.h:99
#14 uart_xlnx_ps_init (dev=0x10f038 <__device_dts_ord_17>) at /home/tranquet/zephyrproject-yroeht/zephyr/drivers/serial/uart_xlnx_ps.c:291
#15 0x001097a0 in z_sys_init_run_level (level=level@entry=0) at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/device.c:70
#16 0x00109b78 in z_cstart () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/init.c:447
#17 0x0010759c in z_arm_prep_c () at /home/tranquet/zephyrproject-yroeht/zephyr/arch/arm/core/aarch32/prep_c.c:260
#18 0x0010870c in z_arm_reset () at /home/tranquet/zephyrproject-yroeht/zephyr/arch/arm/core/aarch32/cortex_a_r/reset.S:229
```

Maybe a driver-level fix would be more appropriate? Is that even possible? @ibirnbaum

**Comment by ibirnbaum** [comment]
> To be honest, this occurs only in Xilinx code, `uart_xlnx_ps_init@drivers/serial/uart_xlnx_ps.c` which seems to call DEVICE_MMIO_MAP early. In context of the test suite of course, the other drivers do it as well as far as I can tell.
> 
> ```
> (gdb) bt
> #0  arm_arch_timer_count () at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/arch/arm/aarch32/cortex_a_r/sys_io.h:57
> #1  sys_clock_elapsed () at /home/tranquet/zephyrproject-yroeht/zephyr/drivers/timer/arm_arch_timer.c:141
> #2  0x0010bed4 in elapsed () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/timeout.c:64
> #3  0x0010c5f8 in sys_clock_tick_get () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/timeout.c:292
> #4  0x0010c688 in z_impl_k_uptime_ticks () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/timeout.c:308
> #5  0x00105db8 in k_uptime_ticks () at /home/tranquet/zephyrproject-yroeht/build/zephyr/include/generated/syscalls/kernel.h:574
> #6  k_uptime_get () at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/kernel.h:1618
> #7  k_uptime_get_32 () at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/kernel.h:1642
> #8  default_lf_get_timestamp () at /home/tranquet/zephyrproject-yroeht/zephyr/subsys/logging/log_core.c:200
> #9  0x00106318 in z_log_msg_commit (msg=0x128000 <buf32>) at /home/tranquet/zephyrproject-yroeht/zephyr/subsys/logging/log_core.c:551
> #10 0x0010cb54 in z_log_msg_runtime_vcreate (domain_id=0 '\000', data=0x0, dlen=0, package_flags=64, ap=..., fmt=0x0, level=<optimized out>, source=<optimized out>)
>     at /home/tranquet/zephyrproject-yroeht/build/zephyr/include/generated/syscalls/log_msg.h:75
> #11 z_log_msg_runtime_create (domain_id=0 '\000', source=<optimized out>, level=level@entry=4 '\004', data=0x0, dlen=0, package_flags=64, fmt=fmt@entry=0x111678 "arch_mem_map(%p, 0x%lx, %zu, %x) offset %lu", 
>     package_flags=64, dlen=0, data=0x0, domain_id=0 '\000') at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/logging/log_msg.h:559
> #12 0x0010d044 in z_phys_map (virt_ptr=0x0, phys=3758100480, size=76, flags=flags@entry=10) at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/mmu.c:748
> #13 0x001095a4 in device_map (flags=2, size=<optimized out>, phys_addr=<optimized out>, virt_addr=<optimized out>) at /home/tranquet/zephyrproject-yroeht/zephyr/include/zephyr/sys/device_mmio.h:99
> #14 uart_xlnx_ps_init (dev=0x10f038 <__device_dts_ord_17>) at /home/tranquet/zephyrproject-yroeht/zephyr/drivers/serial/uart_xlnx_ps.c:291
> #15 0x001097a0 in z_sys_init_run_level (level=level@entry=0) at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/device.c:70
> #16 0x00109b78 in z_cstart () at /home/tranquet/zephyrproject-yroeht/zephyr/kernel/init.c:447
> #17 0x0010759c in z_arm_prep_c () at /home/tranquet/zephyrproject-yroeht/zephyr/arch/arm/core/aarch32/prep_c.c:260
> #18 0x0010870c in z_arm_reset () at /home/tranquet/zephyrproject-yroeht/zephyr/arch/arm/core/aarch32/cortex_a_r/reset.S:229
> ```
> 
> Maybe a driver-level fix would be more appropriate? Is that even possible? @ibirnbaum

Your stacktrace displays the same scenario as the one investigated in #51035, only that in this case, the UART driver happened to be the first to map memory via than the MMU instead of the syscon driver (which requires CONFIG_PINCTRL=1 to be involved). As mentioned before, it doesn't matter which device driver is initialized first: out of the driver's init function (14), mapping of the respective register space is invoked (13, 12), and within the kernel's z_phys_map function, LOG_DBG is called (12 -> 11). It's only the entry 14 that changes depending on whatever driver is called first, the rest is always identical and unrelated to the logging call.

**Comment by yroeht** [comment]
I phrased that poorly.

My question is: does `z_phys_map` get called in other ways than by `device_map` during PRE_KERNEL_1? If not, a change to the callee may be worth considering.

It seems like `z_phys_map` is also called from `./arch/x86/core/acpi.c`. With the proposed patch, we would lose logging there as well. I am not qualified to tell whether that is acceptable or not.

**Comment by ibirnbaum** [comment]
x86 is potentially affected, too, as this arch has MMU support. So two of the preconditions for running into this issue are fulfilled: z_phys_map is present & can be called and the log level can be configured to always output LOG_DBG messages. The crash won't happen on x86 if either address 0 is valid memory or the x86 timer driver is accessible without having to set up a MMU mapping first (i.e., by using the return value of the rdtsc instruction for timestamping).

**Comment by yroeht** [comment]
What do you think about this rather than removing the LOG_DBG?

```
diff --git a/include/zephyr/arch/arm/aarch32/cortex_a_r/timer.h b/include/zephyr/arch/arm/aarch32/cortex_a_r/timer.h
index d513ecdffc..52bb7a17f1 100644
--- a/include/zephyr/arch/arm/aarch32/cortex_a_r/timer.h
+++ b/include/zephyr/arch/arm/aarch32/cortex_a_r/timer.h
@@ -41,9 +41,12 @@ DEVICE_MMIO_TOPLEVEL_STATIC(timer_regs, ARM_TIMER_NODE);
 
 #define TIMER_REG_GET(offs) (DEVICE_MMIO_TOPLEVEL_GET(timer_regs) + offs)
 
+static bool arm_arch_timer_inited = false;
+
 static ALWAYS_INLINE void arm_arch_timer_init(void)
 {
        DEVICE_MMIO_TOPLEVEL_MAP(timer_regs, K_MEM_CACHE_NONE);
+       arm_arch_timer_inited = true;
 }
 
 static ALWAYS_INLINE void arm_arch_timer_set_compare(uint64_t val)
@@ -122,6 +125,9 @@ static ALWAYS_INLINE uint64_t arm_arch_timer_count(void)
        uint32_t lower;
        uint32_t upper, upper_saved;
 
+       if (!arm_arch_timer_inited)
+               return 0;
+
        /* To get the value from the Global Timer Counter register proceed
         * as follows:
         * 1. Read the upper 32-bit timer counter register.
         * 
```

**Review by andyross — CHANGES_REQUESTED** [review]
Not really my subsystem but I'm going to jump in with a -1 here anyway.

How is an issue of the form "do not log before ..." not a critical bug with the relevant log backend?  You can't have rules like this if logging is going to work for users.  Early logging is one of the very few debugging techniques available on most platforms, and it has to work.

It sounds like the root cause is that some backend (or maybe the whole subsystem) can't handle the case where it can't get a timestamp yet?  Can we please fix that instead?  Logging without a timestamp should work!   Check your dmesg after boot on a linux system, for example.

**Comment by yroeht** [comment]
> It sounds like the root cause is that some backend (or maybe the whole subsystem) can't handle the case where it can't get a timestamp yet? Can we please fix that instead?

It sounds like you agree with the patch commented just above, I will go ahead and submit that as the PR instead then.

**Comment by carlocaione** [comment]
> It sounds like you agree with the patch commented just above, I will go ahead and submit that as the PR instead then.

No, I think that @andyross suggested that this should be fixed (possibly) at logging subsystem level, not here. @nordic-krch what do you think?

**Comment by nordic-krch** [comment]
How logging could check if timer is up and running?

One thing that logging could do is to start using timer from `PRE_KERNEL_2` phase. Or safer would be `POST_KERNEL`?
Would that solve the issue?

**Comment by yroeht** [comment]
How de we feel about the current state of this proposal? Can we expect something to happen? This is currently blocking my other PR https://github.com/zephyrproject-rtos/zephyr/pull/51035

**Comment by carlocaione** [comment]
> How logging could check if timer is up and running?
> 
> One thing that logging could do is to start using timer from `PRE_KERNEL_2` phase. Or safer would be `POST_KERNEL`? Would that solve the issue?

@yroeht can you chime in here?

**Pull request closed without merging**
