### PR TITLE
[wip] scripts: ci: Merge back the ci-tools repository into scripts/ci

### PR DESCRIPTION
**Pull request by ulfalizer**
Having ci-tools as a separate repository has turned out to be awkward
and error-prone in practice. Previously, check_compliance.py could be
updated with a single PR against the Zephyr repository, which would
automatically run the new version against Zephyr. Now, two separate PRs
have to be updated in tandem: one that updates ci-tools, and one that
updates west.yml in the Zephyr repository to point to the new version of
ci-tools.

There are some other issues too:

  - CI silently hangs if there's a problem fetching the ci-tools
    repository. This happens pretty often due to merge conflicts in
    west.yml.

  - Updating test code together with a related change in the Zephyr
    repository is awkward.

  - Managing configuration files and whitelists for tests is awkward.

    I'm planning to add another test that might need a whitelist.

  - The ci-tools scripts are hard to find. I've seen people ask where
    they are a couple of times on Slack.

This merge commit moves the contents of scripts/ in the ci-tools
repository back to scripts/ci/ in the Zephyr repository, in a way that
preserves history.

This script was used to rewrite commits on the ci-tools master branch to only
keep stuff that touches scripts/. It also moves all files from scripts/* to
scripts/ci/\*, in a way that makes it look like all changes were done to
scripts/ci/* originally.

    #!/bin/sh

    git filter-branch -f --prune-empty --tree-filter "
        # Remove everything but scripts/ and the stuff in it from the commit
        find ! -path './scripts*' -delete

        # Move scripts/* to scripts/ci/*, if it exists in the commit
        if [ -e scripts ]; then
            mv scripts ci
            mkdir scripts
            mv ci scripts
        fi
    "

The modified ci-tools master branch was then merged into the Zephyr
repository like this:

    $ git remote add ci-tools ci-tools  # After cloning and modifying ci-tools
    $ git fetch ci-tools
    $ git merge --allow-unrelated-histories ci-tools/master

More updates are needed, e.g. to hook up the scripts in the ci-pipelines
to the new location. Merging this shouldn't break stuff though, since
the ci-tools repository is still there.

### CODE REVIEW

**Comment by ulfalizer** [comment]
Related ci-tools PRs:

 - [check_compliance.py: Whitelist example symbols from the script itself](https://github.com/zephyrproject-rtos/ci-tools/pull/102) (ready to merge)
 - [zephyr_commit_rules.py: Fix pylint warning re. 'len(urls) > 0'](https://github.com/zephyrproject-rtos/ci-tools/pull/103) (ready to merge)

Related ci-pipelines PR:

 - [https://github.com/zephyrproject-rtos/ci-pipelines/pull/17](https://github.com/zephyrproject-rtos/ci-pipelines/pull/17)

**Comment by marc-hb** [comment]
There are pros and cons and I'm not sure which ones outweigh the others. The current situation is really not as bad as the emphatic description states, more details below.

The biggest issue I see tying the two back together is the lack of flexibility for "CI developers": to enhance and test CI tools I've been regularly testing different versions/branches of ci-tools on a fixed version of the code and vice versa, after merging back it will be practically impossible. It also implies a directory filter on all git commands, slower git bisects and git blames, etc.

For non-CI developers merging together may be slightly more convenient but how much more really? In fact how many non-CI developers use ci-tools and will this really increase their number?

As moving and renaming is very disruptive this needs more reviewers, at least all the CI developers. Oh... wait... ;-)

> Previously, check_compliance.py could be updated with a single PR against the Zephyr repository, which would automatically run the new version against Zephyr. Now, two separate PRs have to be updated in tandem: 

This is a generic usability issue with west, fixing it in just this one place will have no effect for all the other places/modules where this is also an issue. @mbolivar is there already a west UI issue to automate this better?

> Updating test code together with a related change in the Zephyr repository is awkward.

Same?

> CI silently hangs if there's a problem fetching the ci-tools repository. This happens pretty often due to merge conflicts in west.yml.

Similarly, this is just lack of error handling in CI that should be fixed independently of this anyway. Error handling => never tested! Is there already a github issue for this particular hang?

BTW separate repos is exactly the super convenient way I typically test error handling in ci-tools: just move the main repo back to a failing version, done.


> Managing configuration files and whitelists for tests is awkward.

Not sure which particular files but in general configuration files never belong to the tool that reads them, they belong to the repo of whatever they're configuring. That's the whole point of configuration files! To make the same tool(s) behave differently for different projects.

So, move only these config files to the main repo, problem solved?

> The ci-tools scripts are hard to find. I've seen people ask where they are a couple of times on Slack.

From a non-CI developer perspective this would just move them to a different directory, no big difference really.

**Comment by marc-hb** [comment]
> I don't know a better way,

I don't think the design could be simplified either, I mean not without changing major west design decisions so I'm not suggesting that. However I think it could be semi-automated better.

**Comment by mbolivar** [comment]
> However I think it could be semi-automated better.

I am really open to suggestions here. I believe on the client side we'd probably want a west extension that used the GitHub API to open multiple pull requests at the same time or something/somehow. I don't have any ideas on the server side.

**Comment by marc-hb** [comment]
Lookin for what's repetitive, the 1. creation of the `west.yml` draft PR needed to trigger CI, and 2. its "upgrade" to the final SHA1  could probably be both better automated: https://docs.zephyrproject.org/2.0.0/guides/modules.html#changes-to-existing-modules

**Comment by ulfalizer** [comment]
> The biggest issue I see tying the two back together is the lack of flexibility for "CI developers": to enhance and test CI tools I've been regularly testing different versions/branches of ci-tools on a fixed version of the code and vice versa, after merging back it will be practically impossible.

What tests did you use it for? Never needed/wanted this flexibility myself, so curious.

> It also implies a directory filter on all git commands, slower git bisects and git blames, etc.

Which `check_compliance.py` test did you debug with `git bisect`? Never came up for me.

(Not saying it didn't for you. Just curious.)

> > Previously, check_compliance.py could be updated with a single PR against the Zephyr repository, which would automatically run the new version against Zephyr. Now, two separate PRs have to be updated in tandem:
> 
> This is a generic usability issue with west, fixing it in just this one place will have no effect for all the other places/modules where this is also an issue. @mbolivar is there already a west UI issue to automate this better?

It's a generic issue with multi-repo. Splitting a single repository into multiple repositories by itself always makes it more awkward to work on (or you'd have a separate repo for every directory), so there has to be some big payoff to make it worthwhile. Not seeing it with `ci-tools`.

> Similarly, this is just lack of error handling in CI that should be fixed independently of this anyway. Error handling => never tested! Is there already a github issue for this particular hang?

No issue that I know of.

It happens because the scripts in [ci-pipelines](https://github.com/zephyrproject-rtos/ci-pipelines/blob/master/shippable.jobs.yml) fail, and they don't report back anywhere that I think.

> BTW separate repos is exactly the super convenient way I typically test error handling in ci-tools: just move the main repo back to a failing version, done.

Which test did you test like that? Personally, I just drop a random `CONFIG_UNUSED` into some file and run the undefined Kconfig symbol test, etc.

> > Managing configuration files and whitelists for tests is awkward.
> 
> Not sure which particular files but in general configuration files never belong to the tool that reads them, they belong to the repo of whatever they're configuring. That's the whole point of configuration files! To make the same tool(s) behave differently for different projects.
> 
> So, move only these config files to the main repo, problem solved?

Nicer to just drop them next (or in the test) when it's a fixed configuration. Removes an unnecessary layer of indirection.

I don't think we have any test configuration files where people would be changing them a lot or need to maintain a bunch of different versions of (almost never see people change them). Might be different if we had, though I'd just manage it with plain Git branching, which is what it's for.

> > The ci-tools scripts are hard to find. I've seen people ask where they are a couple of times on Slack.
> 
> From a non-CI developer perspective this would just move them to a different directory, no big difference really.

It breaks `git grep`, which is pretty big to me (goes for other modules too). Also breaks `git log` for changes that touch multiple repositories, and a bunch of other nice version control stuff.

Also assumes you're using `west`.

It feels like we fall in some fanciness trap sometimes, and end up introducing a bunch of problems that are much more time-consuming and awkward to deal with than the original problem we were trying to solve. We shouldn't get suspicious if something is done in a very direct and simple way, without many files or layers.

Instead of adding more complexity and workarounds for problems we probably introduced ourselves, I think we should scale back a bit on the multi-repo stuff a bit, and save it for the truly independent and standalone stuff.

I've worked on some multi-repo stuff that was forked from the Zephyr repositories recently where I needed to touch many repositories, and it was easily the most frustrating and slow development experience of my career so far. The reason I care is that I know that it'll scare new developers off. I want to make stuff easy and painless and transparent for people. Trying to look too fancy and jumping on flavor-of-the-week trends like multi-repo and Dockerizing everything just adds unnecessary layers of indirection and causes pain.

**Comment by marc-hb** [comment]
> What tests did you use it for? Never needed/wanted this flexibility myself, so curious.

So let's say you add a new [ci-tools] check or fix/enhance an existing one. It typically finds new issues in the main repo (or any other non-ci-tools repo; I will stick to "main repo" for simplicity). You go and fix these issues in the main repo, test everything and upload everything for review. Now of course the reviewer(s) ask for some changes in ci-tools. The most efficient way to properly re-test the review updates is to flip the main repo back and forth between failing and passing versions of the latter.

"No tests testing the tests, too bad!" seems to be a common misconception. The *production code* is what tests the tests, it's _reflexive_. Or maybe it's not a misconception but an excuse to give test PRs even less coverage than production code PRs?

Don't get me wrong: (unit) tests very tightly coupled to the production code must generally be in sync and belong to the same repo. Really not the case for the couple ci-tools features I worked on. I admittedly don't know anything about the device tree and kconfig checks. As often maybe the best answer is somewhere in the middle, I mean maybe parts of ci-tools belong to the main repo whereas others not so much.

> Which check_compliance.py test did you debug with git bisect

I don't remember sorry. I might have. Not possible any more with only one repo because git bisect would move check_compliance.py and its input data at the same time.


>  it was easily the most frustrating and slow development experience of my career so far.

> Splitting a single repository into multiple repositories by itself always makes it more awkward to work on...

"awkward" and "most frustrating" are super vague, please elaborate with real examples and real use cases.

> ...(or you'd have a separate repo for every directory)

Of course not, not for anything tightly coupled.

> so there has to be some big payoff to make it worthwhile. Not seeing it with ci-tools.

"big" is relative but I did show some actual payoff above.

> I don't think we have any test configuration files where people would be changing them a lot or need to maintain a bunch of different versions (almost never see people change them). 

That's just because Zephyr's multi repos organization is new so no one uses check_compliance.py on other repos yet.  Modules cloned from different companies / projects are unlikely to have the same codestyle.

> It breaks git grep, which is pretty big to me (goes for other modules too). 

Google's repo has `repo grep` shortcut and when I don't have a clue I miss it. If you miss it often then I agree something is probably wrong in the current repos organization. Examples? I wouldn't write that the lack of `west grep` "breaks" git grep though, BTW west has a `forall` command which should make implementing the shortcut relatively easy; I mean if you can't wait for @mbolivar to provide a built-in :-)

> Also breaks git log for changes that touch multiple repositories, and a bunch of other nice version control stuff.

Please provide real examples of changes that touch multiple repos. Again: maybe parts of ci-tools are tightly coupled to the main repo and should move there whereas others not so much. Moving them gradually is also less likely to break things.

> Also assumes you're using west.

Errr... yes?!? I thought we were discussing multi-repos...

> end up introducing a bunch of problems that are much more time-consuming and awkward to deal with than the original problem we were trying to solve.

Engineering = trade-offs. Different use cases can require different trade-offs and you can never please everyonel; tough!

> we should scale back a bit on the multi-repo stuff, and save it for the truly independent and standalone stuff.

The parts of ci-tools I worked on were truly independent and I actually leveraged that. 

> Trying to look too fancy and jumping on flavor-of-the-week trends like multi-repo 

You may not personally benefit from the multi-repo approach but don't dismiss it as a fad when it has been extensively discussed and documented. Appearing like you don't know anything about it is unlikely to help this particular PR.

The need for a second level of versioning is not a "flavor of the week". It is relatively new only because distributed version control is relatively new. Sure, it's easier to throw everything in just one giant SVN or Perforce repo, however that simply doesn't work for open-source collaborations combining various pieces from multiple places. Even Google has to stop using Piper when doing open-source

https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext

**Review by mbolivar — COMMENTED** [review]
>>  Trying to look too fancy and jumping on flavor-of-the-week trends like multi-repo

> [...]Appearing like you don't know anything about it is unlikely to help this particular PR.

I wanted to let some time go by to see if anyone else cared to review before commenting, but no one has and I basically agree with this.

Absent a more compelling reason than "I don't like it", I see no reason to merge this.

**Comment by marc-hb** [comment]
> Google's repo has repo grep shortcut and when I don't have a clue I miss it. [...] BTW west has a forall command which should make implementing the shortcut relatively easy; I mean if you can't wait for @mbolivar to provide a built-in :-)

Filed request for `west repo` shortcut at https://github.com/zephyrproject-rtos/west/issues/337

@mbolivar is requesting a "popular vote"

**Comment by carlescufi** [comment]
This is not going to be merged, can be reopened later.

**Pull request closed without merging**
