### PR TITLE
sys/util: fix macro support when building with C++

### LINKED ISSUE #27404: IS_ENABLED not working with C++ (was: Is DT_INST_FOREACH_STATUS_OKAY broken on v2.3?)
I am experimenting with implementing a custom device driver using devicetree. There I encountered the macro `DT_INST_FOREACH_STATUS_OKAY(fn)`. And despite my bindings and devicetree + overlays being correct, nothing happens.

I then managed to track down the issue: `DT_INST_FOREACH_STATUS_OKAY` uses `COND_CODE_1`, which conditionally expands, depending on whether the first parameter is `1` or not. As first parameter `DT_HAS_COMPAT_STATUS_OKAY` is used, which is supposed to expand to `1` if there is at least one compatible device on the devicetree. `DT_HAS_COMPAT_STATUS_OKAY` itself uses `IS_ENABLED` and thus actually expands to `true` or `false`. Thus `COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(...), ("yay"), ("nay"))` always expands to "nay".

If I `#define _XXXXtrue _YYYY,` beforehand, it works as expected.

Minimal working example:
```
#include <zephyr.h>

//#define _XXXXtrue _YYYY,    // uncomment this for "yay"

// using c++11 constexpr here for convenience
constexpr const char* test = COND_CODE_1(
	DT_HAS_COMPAT_STATUS_OKAY(nordic_nrf_spi),   // choose anything available on your devicetree
	("yay"),
	("nay")
);
// test gets initialized as "nay"

void main() { }
```

I am on commit c0d3c8004422b359fd2b6257a2c8e226eff54dd6(current head of v2.3-branch). I am developing using a cmake based vscode setup.

Am I doing something wrong, or must this be fixed?

Best regards,
Armin

### PR DESCRIPTION
**Pull request by pabigot**
true and false in a C environment are macros that are defined to 1 and 0 respectively.  In C++ they are keywords, and as such cause failures when macro tests require they expand to a 1 or 0 token.  Use the actual token values rather than the macro names when defining the macros.

Also fix a C++ issue in ztest, and rework the util test to do tests in both C and C++ environments.

Fixes #27404.

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
I didn't verify that test.inc matches the removed lines exactly, but assuming that's what was done, LGTM

**Comment by pabigot** [comment]
Sanitycheck will fail with this error:
```
-- Build files have been written to: /mnt/nordic/zp/zephyr/sanity-out/unit_testing/tests/unit/util/utilities.dec
Scanning dependencies of target kobj_types_h_target
[ 14%] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h
[ 14%] Built target kobj_types_h_target
Scanning dependencies of target testbinary
[ 28%] Building C object CMakeFiles/testbinary.dir/main.c.o
[ 42%] Building CXX object CMakeFiles/testbinary.dir/maincxx.cxx.o
[ 57%] Building C object CMakeFiles/testbinary.dir/mnt/nordic/zp/zephyr/lib/os/dec.c.o
[ 71%] Building C object CMakeFiles/testbinary.dir/mnt/nordic/zp/zephyr/subsys/testsuite/ztest/src/ztest.c.o
[ 85%] Building C object CMakeFiles/testbinary.dir/mnt/nordic/zp/zephyr/subsys/testsuite/ztest/src/ztest_mock.c.o
[100%] Linking CXX executable testbinary
/usr/bin/ld: i386 architecture of input file `CMakeFiles/testbinary.dir/main.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `CMakeFiles/testbinary.dir/mnt/nordic/zp/zephyr/lib/os/dec.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `CMakeFiles/testbinary.dir/mnt/nordic/zp/zephyr/subsys/testsuite/ztest/src/ztest.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `CMakeFiles/testbinary.dir/mnt/nordic/zp/zephyr/subsys/testsuite/ztest/src/ztest_mock.c.o' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/testbinary.dir/build.make:144: testbinary] Error 1
make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/testbinary.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

at least on Ubuntu 20.04.  This is because the test seems to use two different architectures. If I add `CMAKE_CXX_FLAGS=-m32` it works.

I can add that inside the test CMakeLists.txt if that's the right fix, otherwise I'll need instructions from somebody who understands how the unit test area is supposed to work.

**Comment by pabigot** [comment]
> I didn't verify that test.inc matches the removed lines exactly, but assuming that's what was done, LGTM

```
tirzah[171]$ pwd
/mnt/nordic/zp/zephyr/tests/unit/util
tirzah[172]$ git show HEAD^:./main.c > main.c-
tirzah[173]$ diff -uw test.inc main.c-
--- test.inc	2020-08-11 16:12:05.813623937 -0500
+++ main.c-	2020-08-11 16:17:48.823547770 -0500
@@ -384,12 +384,7 @@
 	zassert_equal(a[4], 5, NULL);
 }
 
-#if __cplusplus
-extern "C" void test_cxx(void);
-void test_cxx(void)
-#else
-void test_cc(void)
-#endif
+void test_main(void)
 {
 	ztest_test_suite(test_lib_sys_util_tests,
 			 ztest_unit_test(test_u8_to_dec),
tirzah[174]$ 
```

**Comment by pabigot** [comment]
@mbolivar-nordic  thanks for the clue in https://github.com/zephyrproject-rtos/zephyr/issues/27404#issuecomment-670017128 which made it trivial to identify the problem.

**Review by nordic-krch — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
