### PR TITLE
tfm: Change TFM_BL2 config from a choice to a bool

### PR DESCRIPTION
**Pull request by oyvindronningstad**
The choice allowed for using TFM's own default. We now need full
knowledge over whether BL2 is enabled or not (e.g. to do signing),
so remove this option and simplify to a bool.

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

### CODE REVIEW

**Review by hakonfam — APPROVED** [review]
:pray:

**Review by ioannisg — APPROVED** [review]
looks ok to me.
i never liked the tf-m default options - better Zephyr to have full control over BL2 inclusion in the tfm build

**Review by microbuilder — APPROVED** [review]

**Comment by ioannisg** [comment]
@agansari could you take a quick look, as well?

**Review by tejlmand — APPROVED** [review]

**Comment by ioannisg** [comment]
@MaureenHelm (or @agansari ) pls, take a quick look at this minor change :)

**Review by tejlmand — APPROVED** [review]
Re-approved after tfm/CMakeLists.txt code move from https://github.com/zephyrproject-rtos/trusted-firmware-m/pull/46

**Comment by ioannisg** [comment]
@oyvindronningstad this now needs another rebase

**Pull request merged**
