### PR TITLE
tests: spi_loopback: Rework test

### PR DESCRIPTION
**Pull request by galak**
* Move test to using devicetree for various "device" params.
* Move test to using spi_dt_spec to simplify code

Signed-off-by: Kumar Gala <galak@kernel.org>

### CODE REVIEW

**Comment by galak** [comment]
marked dnm - need to fix / remove SPI_LOOPBACK_FAST_FREQ

**Comment by erwango** [comment]
@galak, as expected this test failed on our bench since https://github.com/zephyrproject-rtos/zephyr/pull/48358 was merged. Out of curiosity I launched a campaign using current PR and I still see issues so most likely it requires a bit more work.
Do you have the same status on your side, or do you want me to dig a little bit more ?

**Comment by galak** [comment]
> @galak, as expected this test failed on our bench since #48358 was merged. Out of curiosity I launched a campaign using current PR and I still see issues so most likely it requires a bit more work.
> Do you have the same status on your side, or do you want me to dig a little bit more ?

Any sense how its failing.

**Comment by erwango** [comment]
> > @galak, as expected this test failed on our bench since #48358 was merged. Out of curiosity I launched a campaign using current PR and I still see issues so most likely it requires a bit more work.
> > Do you have the same status on your side, or do you want me to dig a little bit more ?
> 
> Any sense how its failing.

I didn't investigated yet, I wanted to know if you were done with it first. I'll check this tomorrow.

**Comment by erwango** [comment]
> @galak, as expected this test failed on our bench since #48358 was merged. Out of curiosity I launched a campaign using current PR and I still see issues so most likely it requires a bit more work. Do you have the same status on your side, or do you want me to dig a little bit more ?

All tests are passed now.

**Review by erwango — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]
Nice cleanup

**Comment by galak** [comment]
@glaubermaroto mind doing a review/approval since you tested this on esp32.

**Comment by glaubermaroto** [comment]
LGTM. Working fine on Espressif boards.

**Review by glaubermaroto — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
