### PR TITLE
drivers: pinmux: stm32: STM32F7 added ETH support to pinmux

### PR DESCRIPTION
**Pull request by therealprof**
This patch adds support for Ethernet in the STM32F7 famlily
microcontrollers

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
@erwango Can you review please? This is a broken out patch from a larger patch set to bring up the Nucleo-F746ZG including networking; I tend to get easily confused with too many open construction sites. ;)

**Review by erwango — COMMENTED** [review]
If this is to add ETH pinmux to the familly, why not adding PC2, PC3?

**Comment by therealprof** [comment]
@erwango Because they're not needed. This is modelled after the pinmux configuration for the F4 which also doesn't define them. I also have a similar patch for the F2 once support lands.

I don't know what PC2 and PC3 do from the top of my head but I can look it up and add them if you prefer.

**Comment by erwango** [comment]
@therealprof , well looking to a F7 datasheet, these also have ethernet function

**Comment by therealprof** [comment]
@erwango Those are for MII operation, you should find a few more pins required for MII mode but I'm not sure whether the driver actually supports MII mode at the moment, the typical implementations (also the one on the Nucleos) use RMII mode.

**Comment by erwango** [comment]
@therealprof , ok, my bad, I'm not too much familiar with eth

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
