### PR TITLE
boards: nios2: enable icount for qemu_nios2 platform

### LINKED ISSUE #25918: qemu_nios2 crash when enabled icount
seems when qemu runes instruction WRCTL of nios2 arch with icount enabled, there will be crash. 
Screenshot from 2020-06-03 13-47-27

### PR DESCRIPTION
**Pull request by wentongwu**
Enable icount for qemu_nios2 platform.

Fixes: #25918.

Signed-off-by: Wentong Wu <wentong.wu@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
what's gating this? the new 0.12 SDK currently being tested has QEMU 5.1 in it

**Comment by wentongwu** [comment]
> what's gating this? the new 0.12 SDK currently being tested has QEMU 5.1 in it

@andrewboie I think we can merge this PR after the CI updates its SDK to 0.12, otherwise CI will fail like this one.

**Comment by wentongwu** [comment]
thought CI has switched to 0.12.0, but https://github.com/zephyrproject-rtos/zephyr/pull/31230 indicates me it's not. will trigger new CI run for this PR when https://github.com/zephyrproject-rtos/zephyr/pull/31230 merged.

**Comment by wentongwu** [comment]
@nashif with new SDK, icount for qemu_nios2 is working well, could you please help merge this PR. thanks

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@wentongwu  please rebase and push again

**Comment by wentongwu** [comment]
> @wentongwu please rebase and push again

@nashif done, Thanks

**Pull request merged**
