### PR TITLE
rebase topic-ble-llcp onto current master

### PR DESCRIPTION
**Pull request by ppryga-nordic**
I've rebased topic-ble-llcp onto current master branch.
Please review it.

### CODE REVIEW

**Comment by thoh-ot** [comment]
Rebases of topic branches are not done through normal PR's. They are done through force pushes to the topic branch itself and requires that the branch is unlocked for changes.

**Comment by carlescufi** [comment]
@ppryga as @thoh-ot mentioned, rebasing is not done with a PR. I will close this to avoid noise, and we can rebase the topic branch together later.

**Comment by ppryga** [comment]
@carlescufi @thoh-ot I'm sorry for making mess. I didn't know about it. I will follow it in futute. Thank you!

**Comment by thoh-ot** [comment]
@ppryga No worries, did the same mistake myself the first time.

**Pull request closed without merging**
