### PR TITLE
zephyr: remove deprecated functions

### PR DESCRIPTION
**Pull request by ycsin**
Removed the following functions/symbols that have been marked as deprecated for more than 2 releases:

- `bt_le_whitelist_add`
- `JSON_TOK_LIST_START`
- `JSON_TOK_LIST_END`
- `lwm2m_engine_update_observer_min_period`
- `lwm2m_engine_update_observer_max_period`
- `lwm2m_engine_create_obj_inst`
- `lwm2m_engine_delete_obj_inst`
- `lwm2m_engine_set_opaque`
- `lwm2m_engine_set_string`
- `lwm2m_engine_set_u8`
- `lwm2m_engine_set_u16`
- `lwm2m_engine_set_u32`
- `lwm2m_engine_set_u64`
- `lwm2m_engine_set_s8`
- `lwm2m_engine_set_s16`
- `lwm2m_engine_set_s32`
- `lwm2m_engine_set_s64`
- `lwm2m_engine_set_bool`
- `lwm2m_engine_set_float`
- `lwm2m_engine_set_objlnk`
- `lwm2m_engine_set_time`
- `lwm2m_engine_get_opaque`
- `lwm2m_engine_get_string`
- `lwm2m_engine_get_u8`
- `lwm2m_engine_get_u16`
- `lwm2m_engine_get_u32`
- `lwm2m_engine_get_u64`
- `lwm2m_engine_get_s8`
- `lwm2m_engine_get_s16`
- `lwm2m_engine_get_s32`
- `lwm2m_engine_get_s64`
- `lwm2m_engine_get_bool`
- `lwm2m_engine_get_float`
- `lwm2m_engine_get_objlnk`
- `lwm2m_engine_get_time`
- `lwm2m_engine_register_read_callback`
- `lwm2m_engine_register_pre_write_callback`
- `lwm2m_engine_register_validate_callback`
- `lwm2m_engine_register_post_write_callback`
- `lwm2m_engine_register_exec_callback`
- `lwm2m_engine_register_create_callback`
- `lwm2m_engine_register_delete_callback`
- `lwm2m_engine_set_res_buf`
- `lwm2m_engine_set_res_data`
- `lwm2m_engine_set_res_data_len`
- `lwm2m_engine_get_res_buf`
- `lwm2m_engine_get_res_data`
- `lwm2m_engine_create_res_inst`
- `lwm2m_engine_delete_res_inst`
- `lwm2m_engine_path_is_observed`
- `LWM2M_RD_CLIENT_EVENT_REG_UPDATE_FAILURE`
- `lwm2m_engine_send`
- `lwm2m_send`
- `lwm2m_engine_enable_cache`
- `openthread_set_state_changed_cb`
- `zephyr_smp_rx_req`
- `zephyr_smp_alloc_rsp`
- `zephyr_smp_free_buf`
- `dns_sd_extract_service_proto_domain`
- `settings_mount_fs_backend`

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by Thalley** [comment]
The changes to BT seems fine, but it's missing quite a few: https://github.com/zephyrproject-rtos/zephyr/issues/73843 

Should we remove the missing ones in this PR, or create a follow-up PR?

**Comment by ycsin** [comment]
> The changes to BT seems fine, but it's missing quite a few: https://github.com/zephyrproject-rtos/zephyr/issues/73843 
> 
> Should we remove the missing ones in this PR, or create a follow-up PR? 

Would you be able to create a follow up PR?

**Comment by Thalley** [comment]
> > The changes to BT seems fine, but it's missing quite a few: #73843
> > Should we remove the missing ones in this PR, or create a follow-up PR?
> 
> Would you be able to create a follow up PR?

@carlescufi were you planning on doing that?

**Review by SeppoTakalo — APPROVED** [review]
LwM2M looks OK.

**Review by rlubos — APPROVED** [review]

**Comment by aescolar** [comment]
Bulk changing the milestone from everything which did not make it to the v3.7.0 freeze deadline
and which is not labeled as a bug or documentation (or does not appear clearly as only containing
a bug fix or a documentation change).
If you disagree about this change please add the milestone again.

Please note that until rc2 only PRs containing bug fixes, docs and tests can be merged.
After that and until release only bug fixes and docs changes.

Exceptions require approval by the release team and a vote by the TSC.
https://docs.zephyrproject.org/latest/project/release_process.html#stabilization-phase

**Comment by ycsin** [comment]
> Bulk changing the milestone from everything which did not make it to the v3.7.0 freeze deadline and which is not labeled as a bug or documentation (or does not appear clearly as only containing a bug fix or a documentation change). If you disagree about this change please add the milestone again.
> 
> Please note that until rc2 only PRs containing bug fixes, docs and tests can be merged. After that and until release only bug fixes and docs changes.
> 
> Exceptions require approval by the release team and a vote by the TSC. https://docs.zephyrproject.org/latest/project/release_process.html#stabilization-phase

I think it only makes sense if this can go into v3.7, so that we don't have to maintain these functions for another 2 years, otherwise we can probably take the time and let the maintainers/collaborators to take over

**Comment by ycsin** [comment]
Split the commit into more commits, PTAL, thanks.

**Review by jhedberg — APPROVED** [review]

**Comment by carlescufi** [comment]
> > > The changes to BT seems fine, but it's missing quite a few: #73843
> > > Should we remove the missing ones in this PR, or create a follow-up PR?
> > 
> > 
> > Would you be able to create a follow up PR?
> 
> @carlescufi were you planning on doing that?

Yep, working on it @Thalley

**Pull request merged**
