### PR TITLE
cmake: Toolchain abstraction: Abstraction of compiler warning flags

### PR DESCRIPTION
**Pull request by daor-oti**
The intent here is to abstract Zephyr's dependence on toolchains, 
thus allowing for easier porting to other, perhaps commercial, toolchains 
and/or usecases.

No functional change expected.

-------------

Part of #16031

### CODE REVIEW

**Review by mped-oticon — APPROVED** [review]
LGTM

**Review by SebastianBoe — APPROVED** [review]

**Review by ozhuraki — APPROVED** [review]
LGTM

Perhaps, for a future direction, it would be more practical not to hardcode the specific presets, but to blacklist the ones known not to work/incompatible.

And, for a slightly higher level picture on this, it would make sense to analyze what’s common/differs conceptually among 2+ different compilers:

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
https://clang.llvm.org/docs/UsersManual.html

**Review by tyrantlizard77 — DISMISSED** [review]
Why do the warnings need to be split between 3 files? 
This would be a lot clearer if we just had 1 file with the warning options per toolchain

**Comment by daor-oti** [comment]
@andrewboie The reasons for the split into the separate files, instead of just one, are:
- To keep as much visible as possible from the CMakeLists.txt, here mostly the -DW macros.
- To keep in line with the way the previous toolchain abstractions has been implemented, for example the optimization and cpp dialect flags, just to mention a few. 
- and to make it possible to keep common flags in one file and more specific ones in another. This to limit the number of files which requires change in cases where the flags needs update, thus change one file instead of many.

**Comment by andrewboie** [comment]
> @andrewboie The reasons for the split into the separate files, instead of just one, are:
> 
> * To keep as much visible as possible from the CMakeLists.txt, here mostly the -DW macros.
> * To keep in line with the way the previous toolchain abstractions has been implemented, for example the optimization and cpp dialect flags, just to mention a few.

We have optimization settings for a single toolchain spread across multiple files? Where?

> * and to make it possible to keep common flags in one file and more specific ones in another. This to limit the number of files which requires change in cases where the flags needs update, thus change one file instead of many.

This is needlessly confusing, if I want to see or modify the warning options for GCC I should not have to dig through 3 different small files, put all the warning options for GCC in one file please

**Comment by daor-oti** [comment]
@andrewboie The dw macros I can move to the warning_base file, as they are common to current toolchains. I was referring to separation into dw macros and placing them into a separate file, regarding the optimization and cpp dialect flags.
Concerning the extended warning flags, they really need to be in a separate file, otherwise all of the flags common to most toolchains needs repeat in the toolchain(s) which need add of a few flags. See difference between the extended flags for cpp and clang. This means that x files needs edit, instead of one, which is less desirable than having to look into two files for the warning flags.

**Comment by carlescufi** [comment]
@daor-oti can you please rebase against the latest master? @mped-oticon and @aescolar can help out I am sure

**Comment by daor-oti** [comment]
@carlescufi Sure thing, sorry for the inconvenience.

**Comment by aescolar** [comment]
Hi @andrewboie , It would seem @daor-oti has addressed your concerns, would you be so kind as to take another look, or dismiss your review?

**Pull request merged**
