### PR TITLE
drivers: nrfwifi: Fix offloaded raw tx apis

### LINKED ISSUE #80809: drivers: nrfwifi: Offloaded Raw TX feature broken
**Describe the bug**

When testing `offloaded raw TX` feature on nRF7002DK, no frames were seen OTA.

**To Reproduce**

* Build [sample](https://github.com/nrfconnect/sdk-nrf/tree/main/samples/wifi/offloaded_raw_tx) for nRF7002DK
* Flash and test, no packets seen OTA

**Expected behavior**

Sniffer should see the packets.

**Impact**
Feature is broken

**Logs and console output**
NA

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK,
 - Commit SHA or Version used: Latest

**Additional context**
The feature flag is not passed to the OS agnostic code.

### PR DESCRIPTION
**Pull request by kapbh**
Add and remove Kconfig in cmake.
Add changes to fix regularity domain of offloaded raw tx.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/80809

### CODE REVIEW

**Review by sachinthegreen — DISMISSED** [review]

**Review by sachinthegreen — DISMISSED** [review]

**Review by krish2718 — DISMISSED** [review]

**Comment by dkalowsk** [comment]
@jukkar is this needed for 4.0?

**Comment by krish2718** [comment]
> @jukkar is this needed for 4.0?

It is a bug fix to get that feature (offloaded raw tx) working, so, yes.

**Comment by dkalowsk** [comment]
> > @jukkar is this needed for 4.0?
> 
> It is a bug fix to get that feature (offloaded raw tx) working, so, yes.

okay if that is the case, @krish2718 it's going to need an Issue/Bug number attached to it now as we're at RC2 and later.

**Comment by krish2718** [comment]
> > > @jukkar is this needed for 4.0?
> > 
> > 
> > It is a bug fix to get that feature (offloaded raw tx) working, so, yes.
> 
> okay if that is the case, @krish2718 it's going to need an Issue/Bug number attached to it now as we're at RC2 and later.

Updated description with bug reference, thanks.

**Review by jukkar — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by sachinthegreen — DISMISSED** [review]

**Review by krish2718 — APPROVED** [review]

**Review by sachinthegreen — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]

**Pull request merged**
