### PR TITLE
drivers: modem: ublox-sara-r4: adjust send length

### PR DESCRIPTION
**Pull request by hwilmers**
- limit max. number of bytes when sending to socket
  The number of bytes sent to a socket in one transaction
  is limited to 512 in HEX mode (Sara-R4), and to 1024
  otherwise. This corresponds to numbers given in the
  manual for ublox cellular modems.

- report number of bytes actually sent, as reported by modem
  After writing data to a socket, we now return the number of
  bytes actually written, as reported by the modem.

Signed-off-by: Hans Wilmers <hans@wilmers.no>

### CODE REVIEW

**Comment by mike-scott** [comment]
@hwilmers Can the 2 patches be squashed together?

**Comment by hwilmers** [comment]
@mike-scott Yes, the patches can be squashed together. Shall I do that?

**Comment by mike-scott** [comment]
@hwilmers I'm going to pull a squashed version into my PR, so no need to fix here.

**Comment by hwilmers** [comment]
@mike-scott ok, thank you!

**Comment by mike-scott** [comment]
@hwilmers patches squashed and added here: https://github.com/zephyrproject-rtos/zephyr/pull/22149

**Review by mike-scott — CHANGES_REQUESTED** [review]
Let's block merging on this PR until it's closed.

**Comment by hwilmers** [comment]
(closed via #22149)

**Pull request closed without merging**
