### PR TITLE
drivers: serial: Fix race condition in nRF5 UART TX

### PR DESCRIPTION
**Pull request by durub**
Fix a somewhat rare race condition when the thread gets
preempted in the middle of sending a byte through UART.

If the other thread also sends another byte through UART
and "consumes" the EVENTS_TXDRDY value, the first thread
will get stuck in the while loop forever.

By moving the reset to the function start, we guarantee that
the baseline state of EVENTS_TXRDY is 1. Therefore, the first
thread will continue normally when it executes again.

Signed-off-by: Thiago Silveira <thiago@exati.com.br>

### CODE REVIEW

**Comment by durub** [comment]
A little tricky to reproduce, and I don't have an easy test case on hand. I was reproducing this on our own project. At first I tried to lock the scheduler in a printk-heavy area of the code, and that fixed the issue. I investigated further and pinpointed it to the `uart_nrf5_poll_out` while loop.

I also found that RIOT-OS had the same issue in the past, with the exact same fix: https://github.com/RIOT-OS/RIOT/issues/5954

**Comment by durub** [comment]
I also removed the documentation part about checking if the transmitter is empty. This doesn't seem to be done at the moment or before. Maybe writing to `uart->TXD` does it implicitly, but reading the datasheet, it doesn't appear to have this information readily accessible.

Thoughts?

cc @carlescufi @cvinayak

**Review by carlescufi — COMMENTED** [review]
No objections from me, but will let @anangl take a look at it before I approve.

**Comment by anangl** [comment]
The patch is okay.
From what I see, it fixes the handling of the `TXDRDY` event in general. Currently, the event is cleared at the exit of `_poll_out`, and this is not entirely good since the same event is also used by "interrupt driven" API to provide TX status (`_tx_complete` and `_tx_ready`). In case someone decided to combine usage of both APIs (what is not forbidden, I guess), this would mean troubles.

Regarding the removed documentation part - indeed, the current implementation does not do exactly what UART API states it should do. Actually, it should wait until the transmitter becomes empty before writing a new character there, i.e. do it like this:
```
 	/* Wait for transmitter to be ready */
 	while (!uart->EVENTS_TXDRDY) {
 	}

	/* reset transmitter ready state */
	uart->EVENTS_TXDRDY = 0;

 	/* send a character */
 	uart->TXD = (u8_t)c;
```
But then, we would fall into a similar issue. When the thread is preempted between clearing the `TXDRDY` event and writing to TXD, then the preempting thread would hang on the `while` loop if it tried to call `_poll_out` as well.

Therefore, I think the patch is the best what we can do to provide "thread safety" here without introducing some locking.
Maybe it would be worth mentioning in the code that the `while` loop has to be placed after the write to TXD (and consequently, `_poll_out` can't wait for empty transmitter right before writing to TXD) to avoid the rare yet possible race condition.

**Comment by carlescufi** [comment]
@anangl thanks for the thorough explanation.
@durub mind adding a comment in the code reflecting what @anangl mentions?

**Review by anangl — APPROVED** [review]

**Comment by durub** [comment]
I chatted with @anangl over IRC and we agreed on the comment in the commit.

@carlescufi, I think this is ready now! @anangl, thanks for the explanation and help.

**Review by carlescufi — APPROVED** [review]

**Comment by leodesigner** [comment]
Hi,
After this commit the shell is broken. (nrf52 custom board)
Just no reaction to any command at all.
```
***** Booting Zephyr OS 1.11.99 *****
Zephyr Shell, Zephyr version: 1.11.99
Type 'help' for a list of available commands
shell> 
help
help
```
Before this commit shell is responding to the commands.
Should I open the issue ?

**Comment by carlescufi** [comment]
@leodesigner I can reproduce, let me open the issue

**Pull request merged**
