### PR TITLE
drivers: ramdisk: use devicetree to instantiate RAM disk

### LINKED ISSUE #61629: driver: ramdisk: add user allocation of ramdisk buffer
**Is your enhancement proposal related to a problem? Please describe.**
I think it would be useful if the ramdisk could be used as a general purpose method of sending arbitrary data to a device via USB. The use-case is a imxrt1060 mcu with LCD display, where we use the ramdisk for 2 framebuffers shared with the display_mcux_elcdif driver. This way the "dd" linux command can be used to write directly to the display framebuffer, without any extra copying needed to update the display.

**Describe the solution you'd like**
I propose to add configuration option CONFIG_DISK_RAM_USER_ALLOCATION to the ramdisk driver:
 
```Kconfig
config DISK_RAM_USER_ALLOCATION
    bool "RAM buffer is allocated by User"
    help
      RAM buffer is allocated in user space.
      Address of RAM buffer is set by ioctl command DISK_IOCTL_SET_RAMBUF_ADDR
```
 

With this configuration set, the ramdisk driver does not allocate the rambuffer, instead the buffer is allocated by the user and the ioctl disk command DISK_IOCTL_SET_RAMBUF_ADDR, is used to configure the ramdisk buffer address eg.:

```c
uint32_t cmd_buf = (uint32_t)p_buf;
if (disk_access_ioctl(disk_pdrv, DISK_IOCTL_SET_RAMBUF_ADDR, &cmd_buf) != 0) {
    LOG_ERR("Disk ioctl DISK_IOCTL_SET_RAMBUF_ADDR failed");
}
```

### PR DESCRIPTION
**Pull request by jfischer-no**
Rework RAM disk driver to be configured using devicetree and support multiple instances.

This patch also removes a copy of the RAM disk driver, tests/subsys/fs/fat_fs_dual_drive/src/disk_access_test_drv.c, that was there for testing multiple disk drivers support.

Bonus: one SYS_INIT() less.

Resolves: #61629

### CODE REVIEW

**Comment by Laczen** [comment]
@jfisher-no, with a small change this PR can have a further improvement: if the ramdisk in devicetree would have a phandle to a memory region (similar to the phandle for the flashdisk) you could derive the sector_count from the memory section size (and check if the size is a multiple of the sector-size). The main advantage of this is that the memory region is not cleared during a "hot" reboot (and in some devices even in case of a reset) this would allow the ramdisk to persist over reboots, the disadvantage is that the memory region needs to be declared at the end of ram.
This behavior could also be made optional depending on the existence of the phandle (this method is e.g. used in the flash_simulator).

**Review by cfriedt — DISMISSED** [review]
LGTM wrt POSIX

**Comment by Laczen** [comment]
@jfischer-no if you would like to postpone the possibility to use a memory region to a later moment: this can be done if instead of the sector count the disk size is specified in dts.

**Review by tmon-nordic — DISMISSED** [review]

**Comment by jfischer-no** [comment]
To dump SRAM on nRF52840:
```diff
diff --git a/samples/subsys/usb/mass/ramdisk.overlay b/samples/subsys/usb/mass/ramdisk.overlay
index ff09a0f8ca7..83aa9f0527b 100644
--- a/samples/subsys/usb/mass/ramdisk.overlay
+++ b/samples/subsys/usb/mass/ramdisk.overlay
@@ -9,6 +9,7 @@
                compatible = "zephyr,ram-disk";
                disk-name = "RAM";
                sector-size = <512>;
-               sector-count = <192>;
+               sector-count = <512>;
+               ram-region = <&sram0>;
        };
 };
```

**Comment by Laczen** [comment]
> To dump SRAM on nRF52840:
> 
> ```diff
> diff --git a/samples/subsys/usb/mass/ramdisk.overlay b/samples/subsys/usb/mass/ramdisk.overlay
> index ff09a0f8ca7..83aa9f0527b 100644
> --- a/samples/subsys/usb/mass/ramdisk.overlay
> +++ b/samples/subsys/usb/mass/ramdisk.overlay
> @@ -9,6 +9,7 @@
>                 compatible = "zephyr,ram-disk";
>                 disk-name = "RAM";
>                 sector-size = <512>;
> -               sector-count = <192>;
> +               sector-count = <512>;
> +               ram-region = <&sram0>;
>         };
>  };
> ```

That is cool, maybe unwanted, but cool nonetheless.

**Comment by Laczen** [comment]
@jfischer-no, looks ok. My preference would be to specify a size instead of the block count in the dts. The block count could easily be derived from the size and the size can be optional (derived from the ram-region or generate build error message if the size is missing for non ram-region setup).

**Review by tmon-nordic — DISMISSED** [review]

**Comment by jfischer-no** [comment]
> @jfischer-no, looks ok. My preference would be to specify a size instead of the block count in the dts. The block count could easily be derived from the size and the size can be optional (derived from the ram-region or generate build error message if the size is missing for non ram-region setup).

That is not how block devices are described.

**Comment by Laczen** [comment]
> > @jfischer-no, looks ok. My preference would be to specify a size instead of the block count in the dts. The block count could easily be derived from the size and the size can be optional (derived from the ram-region or generate build error message if the size is missing for non ram-region setup).
> 
> That is not how block devices are described.

Most (all ?) block devices are not described by their block count, they are reporting a block count. The size is even unknown at compile time. If I would buy a block device I will select a size (a 4GB card, a 128GB SSD, ...) not a block count.
Using the size for describing a (emulated) disk seems the logical approach. This would indeed be translated at compile time to a block count, but this does not have to be the description in the dts. It would just be easier for the user to specify a size instead of a block count.

**Comment by jfischer-no** [comment]
> > > @jfischer-no, looks ok. My preference would be to specify a size instead of the block count in the dts. The block count could easily be derived from the size and the size can be optional (derived from the ram-region or generate build error message if the size is missing for non ram-region setup).
> > 
> > 
> > That is not how block devices are described.
> 
> Most (all ?) block devices are not described by their block count, they are reporting a block count. The size is even unknown at compile time. If I would buy a block device I will select a size (a 4GB card, a 128GB SSD, ...) not a block count. Using the size for describing a (emulated) disk seems the logical approach. This would indeed be translated at compile time to a block count, but this does not have to be the description in the dts. It would just be easier for the user to specify a size instead of a block count.

We are not a retail store, please stop boring me with that nonsense. Driver code and function is based on blocks and block sizes, the same for the backend it uses, e.g. file system or USB MSC, hence host driver. The raw capacity of the volume is clearly given by simple multiplication.

**Comment by de-nordic** [comment]
> > > @jfischer-no, looks ok. My preference would be to specify a size instead of the block count in the dts. The block count could easily be derived from the size and the size can be optional (derived from the ram-region or generate build error message if the size is missing for non ram-region setup).
> > 
> > 
> > That is not how block devices are described.
> 
> Most (all ?) block devices are not described by their block count, they are reporting a block count. The size is even unknown at compile time. If I would buy a block device I will select a size (a 4GB card, a 128GB SSD, ...) not a block count. Using the size for describing a (emulated) disk seems the logical approach. This would indeed be translated at compile time to a block count, but this does not have to be the description in the dts. It would just be easier for the user to specify a size instead of a block count.

That is for people to by stuff, so they knew how much they are left after windows eats up 40GiB.
Note also that we have B and iB notations, you sell disks in B to customers and iB to professionals.
There are tools like mdconfig in FreeBSD that will take size of device in bytes, but then internally this is converted to blocks using the system standard block size and the md device is configured with size of blocks.
Systems use blocks.

**Comment by Laczen** [comment]
@de-nordic, your reference to mdconfig just confirms my proposal: when a disk is described the size is used (either as a real size or as a multiplication of 512 (not the block-size)). This is exactly what I propose: for the definition (in the dts) specify the size. Internally use the block size, it was never proposed differently. In other places were blocks are used (flash) also the size is specified.

@jfischer-no, relax this a little, read my proposal again, look at what it would mean for the user. Does the user know how many blocks are needed or does the user know how much ram can be spared/is needed ?

**Comment by jfischer-no** [comment]
> @de-nordic, your reference to mdconfig just confirms my proposal: when a disk is described the size is used (either as a real size or as a multiplication of 512 (not the block-size)). This is exactly what I propose: for the definition (in the dts) specify the size. Internally use the block size, it was never proposed differently. In other places were blocks are used (flash) also the size is specified.
> 
> @jfischer-no, relax this a little, read my proposal again, look at what it would mean for the user. Does the user know how many blocks are needed or does the user know how much ram can be spared/is needed ?

Sorry, my tea delivery has arrived, I am relaxed again. We are not a pony farm, the user must know what he does / needs. The current configuration is still clear and unambiguous, your suggestion is not. This is the last I want to say about this.

**Review by cfriedt — APPROVED** [review]

**Review by Laczen — APPROVED** [review]
@cfriedt I am just surprised as to why the sector count can't be calculated as `DT_INST_PROP(inst, size) / DT_INST_PROP(inst, sector_size)` with (if wanted) a BUILD_ASSERT if `DT_INST_PROP(inst, size) % DT_INST_PROP(inst, sector_size) != 0`. Where size is the size of the allocated buffer.

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
