### PR TITLE
tests: Remove CONFIG_COMMAND_STACK_SIZE assignments

### PR DESCRIPTION
**Pull request by ulfalizer**
CONFIG_COMMAND_STACK_SIZE was removed in 4f798177cfff ("kernel: remove
old micro/nanokernel C code"). Its help text was "Microkernel server command
stack size (in packets)".

Signed-off-by: Ulf Magnusson <Ulf.Magnusson@nordicsemi.no>

### CODE REVIEW

**Comment by ulfalizer** [comment]
CC @andrewboie

**Comment by ulfalizer** [comment]
recheck

**Comment by ulfalizer** [comment]
recheck

**Review by nashif — APPROVED** [review]

**Comment by galak** [comment]
The CI failures are related to:

commit efe0c4b7647c5e5aa53af47679bb8625fb387b19 (refs/bisect/bad)
Author: Andrew Boie <andrew.p.boie@intel.com>
Date:   Mon May 21 12:44:38 2018 -0700

    tests: enable user mode by default

**Pull request merged**
