### PR TITLE
fix clang format issues for various drivers

### PR DESCRIPTION
**Pull request by najumon1980**
Fixes for error and warning reported by latest clang format tool on various drivers and subsystem such as gpio, wdt, rtc, ioapic, lapic and acpi.

### CODE REVIEW

**Review by bjarki-andreasen — APPROVED** [review]
Looks good :)

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
This is a needless change that will only make backporting of potential bug fixes less likely to apply cleanly. 

Furthermore, clang-format is just a helper tool. Blindly applying its formatting like this is not the intention.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
This is a needless change that will only make backporting of potential bug fixes less likely to apply cleanly. 

Furthermore, clang-format is just a helper tool. Blindly applying its formatting like this is not the intention.

**Comment by najumon1980** [comment]
> This is a needless change that will only make backporting of potential bug fixes less likely to apply cleanly.
> 
> Furthermore, clang-format is just a helper tool. Blindly applying its formatting like this is not the intention.

I am not sure how l

> This is a needless change that will only make backporting of potential bug fixes less likely to apply cleanly.
> 
> Furthermore, clang-format is just a helper tool. Blindly applying its formatting like this is not the intention.

I am not sure how long we can keep away from latest format and this prevent us from running clang tool during new additions/modification on these driver files. Better we should update to latest format and if someone back port any of these changes to LTS branch (I believe LTS support is 2 years) then let do with latest format.

**Comment by nordicjm** [comment]
> > This is a needless change that will only make backporting of potential bug fixes less likely to apply cleanly.
> > Furthermore, clang-format is just a helper tool. Blindly applying its formatting like this is not the intention.
> 
> I am not sure how l
> 
> > This is a needless change that will only make backporting of potential bug fixes less likely to apply cleanly.
> > Furthermore, clang-format is just a helper tool. Blindly applying its formatting like this is not the intention.
> 
> I am not sure how long we can keep away from latest format and this prevent us from running clang tool during new additions/modification on these driver files. Better we should update to latest format and if someone back port any of these changes to LTS branch (I believe LTS support is 2 years) then let do with latest format.

Maybe this would be of use to you: https://offlinemark.com/2021/04/02/surgical-formatting-with-git-clang-format/

**Review by nordicjm — CHANGES_REQUESTED** [review]
Agree with @henrikbrixandersen these changes are not needed and make backports and even just checking files between versions impossible

**Review by jfischer-no — CHANGES_REQUESTED** [review]
No, it is valid original coding style. Just do not use stupid clang-format tool.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
> This is a needless change that will only make backporting of potential bug fixes less likely to apply cleanly.
> 
> Furthermore, clang-format is just a helper tool. Blindly applying its formatting like this is not the intention.

There are 1000s of changes going in and being proposed that break backporting EVERY day. If you have an issue with a specific style change, please point this out.

@najumon1980  is only changing the whole tree, just those things that concerns him and the platforms he maintains.

If there is a rule that says: "Once code is in the tree, though shall never touch the or fix the style", please point me to that...

**Comment by nashif** [comment]
> No, it is valid original coding style. Just do not use stupid clang-format tool.

This is vague, if something is wrong with the changes, please point them out. I see this review to be based on bias and own preferences and not based on facts.

**Review by gmarull — APPROVED** [review]
I have to say that I'd like to see more clang-format adoption. Refactoring Zephyr without an autoformatter is really a pain. You only see this problem in some C/C++ projects in 2023. Reformats are a problem for history, back ports, etc. but the more you wait, the worse it is in the end. I don't see any major issues introduced by this reformat.

**Comment by jfischer-no** [comment]
> > No, it is valid original coding style. Just do not use stupid clang-format tool.
> 
> This is vague, if something is wrong with the changes, please point them out. I see this review to be based on bias and own preferences and not based on facts.

No, this changes are based own bias and own preferences and not on facts that this is the valid coding style passing checkpatch. Especially reformatting parameters/arguments is not necessary and not acceptable.

> I have to say that I'd like to see more clang-format adoption. Refactoring Zephyr without an autoformatter is really a pain.

Then you are doing something wrong with Zephyr.

**Pull request closed without merging**
