### PR TITLE
kconfig: add support for escaped characters in the macro call

### PR DESCRIPTION
**Pull request by barnas-michal**
This commit adds support to escape the characters in the macros calls. Some device tree nodes can have commas in their names and they couldn't be used as argument in the macros.

Example of Kconfig code that requires the characters escaping is: 
`default y if $(dt_chosen_enabled,"zephyr,console")`

### CODE REVIEW

**Comment by jackrosenthal** [comment]
kconfiglib is third-party. should this be sent upstream?

**Review by tejlmand — CHANGES_REQUESTED** [review]
kconfiglib is a python implementation based on the language definition here:
https://www.kernel.org/doc/html/latest/kbuild/kconfig-language.html

afaik, the current implementation in Kconfiglib is correct, so we should not deviate how kconfiglib works, unless there are really good reasons.

Please note the issue with commas in devicetree names can easily be handle using this principle:
https://github.com/zephyrproject-rtos/zephyr/blob/f24b5b4b43bdb7067b8a701294909e744b8eace2/Kconfig.zephyr#L96-L102

**Comment by tejlmand** [comment]
docs being improved here: https://github.com/zephyrproject-rtos/zephyr/pull/51808

**Comment by semihalf-barnas-michal** [comment]
@tejlmand Thanks for the clarification and the update to the documentation. If that's the desired way, I am closing this PR.

**Pull request closed without merging**
