### PR TITLE
random: deprecate xoroshiro128+ in favor of xoshiro128++

### PR DESCRIPTION
**Pull request by JordanYates**
Deprecate the xoroshiro128+ PRNG algorithm in favour of xoshiro128++. xoshiro128++ is a drop-in replacement which is invisible from the user perspective.

xoroshiro128+ is unsuitable because it is explicitly a floating-point PRNG, not a general-purpose PRNG. This means that the lower 4 bits of the output are actually linear, not random (from the designers, https://prng.di.unimi.it/). This means 1/8th of the generated data is not random.

Additionally, xoroshiro128+ is not a 32bit algorithm, it operates on 64bit numbers. For the vast majority of Zephyr devices, this makes the PRNG slower than it needs to be. The replacement (xoshiro128++) is 32bit, with no loss in state space (still 128 bit).

### CODE REVIEW

**Comment by JordanYates** [comment]
The old implementation is removed instead of hanging around as there is no user visible change in behavior and a bad PRNG is really not something that should be selectable because a user thinks they know better.

**Comment by JordanYates** [comment]
The license action is failing due to the `cc0-1.0` license.
This is the same license as the original `xoroshiro128+` implementation.

**Comment by JordanYates** [comment]
@dleach02 this is ready to be reviewed despite the failing CI.

**Review by ceolin — APPROVED** [review]

**Comment by dleach02** [comment]
Not familiar with the license type. I'm okay with the general change but we need approval of the license before including.

**Comment by JordanYates** [comment]
> Not familiar with the license type. I'm okay with the general change but we need approval of the license before including.

As noted in my comment, this is the same license as the function I am deprecating, and the new code comes from the same source.
Does this still need TSC approval? @carlescufi @nashif

**Comment by carlescufi** [comment]
> > Not familiar with the license type. I'm okay with the general change but we need approval of the license before including.
> 
> As noted in my comment, this is the same license as the function I am deprecating, and the new code comes from the same source.
> Does this still need TSC approval? @carlescufi @nashif

I have raised this for today's TSC now @JordanYates. Sorry for not sending an agenda but it was short-notice for me that I'd stand-in for Anas.

**Review by carlescufi — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
TSC is fine with this, no objections were raised.

**Pull request merged**
