### PR TITLE
LE Audio: PAC type rename and type cleanup

### LINKED ISSUE #43693: LE Audio: Rename enum bt_audio_pac_type
**Is your enhancement proposal related to a problem? Please describe.**
The enum is used to describe the direction, or type, or an endpoint and/or stream. Furthermore, it is used for broadcast endpoints as well, so the `PAC` infix is not very fitting. 

**Describe the solution you'd like**
The name should be change to something more generic. 

`bt_audio_type` is a bit too generic IMO, perhaps `bt_audio_ep_type`? 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
The goal of this PR was to rename the `enum bt_audio_pac_type`. To do this properly, some cleanup had to be done to avoid confusion with the (unused) endpoint type. Furthermore, the implementation used the term `type` and `dir` interchangeably, so the code was also updated to be more consistent.  

fixes https://github.com/zephyrproject-rtos/zephyr/issues/43693

### CODE REVIEW

**Review by MariuszSkamra — DISMISSED** [review]
LGTM

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by MariuszSkamra — APPROVED** [review]

**Review by Casper-Bonde-Bose — APPROVED** [review]
Approve as the intension of the PR was to get rid of BT_AUDIO_EP_LOCAL as well as cleanup of the audio direction confusion.
But I'm wondering if BT_AUDIO_EP_LOCAL served a purpose in the case where a CAP commander is not located on the same device as the Initiator. But in the current CAP specification a CAP commander cannot configure unicast streams - hence it makes more sense to remove now and add if the specification adds this feature at some point.

**Review by carlescufi — APPROVED** [review]

**Comment by Thalley** [comment]
> Approve as the intension of the PR was to get rid of BT_AUDIO_EP_LOCAL as well as cleanup of the audio direction confusion. But I'm wondering if BT_AUDIO_EP_LOCAL served a purpose in the case where a CAP commander is not located on the same device as the Initiator. But in the current CAP specification a CAP commander cannot configure unicast streams - hence it makes more sense to remove now and add if the specification adds this feature at some point.

The idea behind the LOCAL endpoint, was to differenciate between `bt_audio_ep` located on the BAP unicast client and the BAP unicast server (as the original API for the unicast client was quite different). Today all the `bt_audio_ep` represent a _remote_ ASE.

**Pull request merged**
