### PR TITLE
scripts: west: nrfjprog: add choice for nRF91

### PR DESCRIPTION
**Pull request by ioannisg**
Add the NRF91 choice for nrfjprog.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
We need to see what we do about this particular one, because we are in the process of switching to using west, so I am not sure if we'll do another update of the west tree copy in zephyr before then. In any case we need to submit to the west repo, but maybe we want to reopen this as well if we really need this soon. @mbolivar thoughts?

**Comment by carlescufi** [comment]
@MaureenHelm actually the commands are now again part of zephyr. I have submitted the counterpart PR to the topic-west branch here: https://github.com/zephyrproject-rtos/zephyr/pull/12773

**Review by carlescufi — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
looking good

**Comment by MaureenHelm** [comment]
> actually the commands are now again part of zephyr. I have submitted the counterpart PR to the topic-west branch here: #12773

Oh, I missed that. Sorry!

**Comment by mbolivar** [comment]
@carlescufi so you are proposing making this change to the copy in zephyr first, then merging west?

If we're going to merge west tomorrow, can't this wait for that?

**Comment by carlescufi** [comment]
@mbolivar yes, I agree. Now that #12773 is merged, let's wait for west to be merged. Closing this.

**Pull request closed without merging**
