### PR TITLE
[TOPIC: DTS] scripts: dts: Let bindings provide multiple compatibles in a simple way

### PR DESCRIPTION
**Pull request by ulfalizer**
```
Background
==========

Some important background first (sorry for the tl;dr, but to show that
there's research behind this, because you might think there wasn't when
you first look at it :).

I looked into the dt-schema format and tools some more. Here's how it
works at a high level:

 - dt-schema is used to verify device tree nodes against schema files
   (bindings). It checks properties and values.

 - Before they're validated, .dts files need to be transformed into YAML
   format, because the dt-schema tools use jsonschema
   (https://python-jsonschema.readthedocs.io/en/stable/) to do the
   actual validation work.

   There's an (undocumented, I think) 'dtc -O yaml' flag that does the
   transformation.

   The whole 'properties:' thing, etc., is from jsonschema. dt-schema is
   a pretty thin wrapper around it.

 - Device tree nodes are matched to bindings via a 'select:' field in
   the binding. This field can contain any condition (which is evaluated
   by jsonschema).

 - If there's no 'select:', dt-schema creates one by going through the
   specification for 'compatible' (it can also do the node name). This
   seems to just be a blind extraction of all the strings mentioned.

   The generated 'select:' looks like this:

   select:
       properties:
           compatible:
               contains:
                   enum:
                       - "foo,device"
                       - "bar,device"
                       - ...

    'contains:' is a standard jsonschema thing. Without it, 'compatible'
    would be required to be exactly one of the 'enum' strings, and
    wouldn't be able to have multiple strings in it.

The last point is important, because dt-schema is actually used to
validate 'compatible'. The auto-generation of 'select:' is just a
niceity.

Because dt-schema bindings actually validate 'compatible', it is
specified in many different ways in Linux. Some examples:

  - Documentation/devicetree/bindings/usb/generic-ehci.yaml:

      compatible:
        contains:
          const: generic-ehci

      ('compatible' must have 'generic-ehci' as an element. 'const' is
        another standard jsonschema thing.)

  - Documentation/devicetree/bindings/arm/psci.yaml:

      compatible:
        oneOf:
          - const: arm,psci
          - const: arm,psci-0.2
          - items:
            - const: arm,psci-1.0
            - const: arm,psci-0.2

      ('compatible' must be set in one of these ways:

         compatible = "arm,psci";
         compatible = "arm,psci-0.2";
         compatible = "arm,psci-1.0", "arm,psci-0.2";

       'items' is another jsonschema thing.)

  - Documentation/devicetree/bindings/spi/allwinner,sun4i-a10-spi.yaml:

      compatible:
        const: allwinner,sun4i-a10-spi

      ('compatible' must be set exactly like this:

         compatible = "allwinner,sun4i-a10-spi";)

Note that the schema below would not do the right thing if you wanted to
require 'compatible' to have one of the elements "foo" or "bar" in it
(would need to add a 'contains:'):

    properties:
        compatible:
            enum:
                - "foo"
                - "bar"

Motivation
==========

If we want to reuse the dt-schema/jsonschema tools, dtlib might have to
spit out YAML (along with some method for encoding phandles, etc.) The
alternative is to reimplement the jsonschema logic ourselves (most
likely in a worse way).

IMO, what we have now is actually a lot nicer than dt-schema in many
ways:

 - We check the device tree directly, without converting it to a
   different format first.

   This saves us from having to come up with an encoding for things like
   phandles, and lets us generate much better error messages.

 - Our format is a lot less bloated and easier to understand and work
   with, while still probably covering 99% of what you need in practice.

 - I think our code is easier to follow. The dt-schema code seems pretty
   cryptic and poorly documented in parts.

 - We have zero dependencies.

My suggestion is to not try to imitate dt-schema for its own sake (we
can still steal good ideas from it). dt-schema went all-in on the
jsonschema thing, and its design reflects that. We'd probably be
creating some kind of half-arsed jsonschema-ish if we tried (a worse
dt-schema).

If we use our strengths instead, we can make the binding format even
simpler and nicer. This commit does that by moving 'compatible:' to the
top level, allowing a list of strings, and getting rid of the magic
'constraint:' field. It makes sense for us to treat 'compatible'
specially, because it's crucial to how bindings work in Zephyr, and
doesn't work like other properties.

See the test-bindings/ changes for how it looks in practice.

Note that just replacing 'constraint:' with an 'enum:' will make 'enum:'
work differently for 'compatible' than it does for any other property
(see the end of the background section), and to do it in a "proper"
dt-schema-like way, we'd need a ton more infrastructure.

For backwards compatibility, 'properties: compatible: constraint: ...'
is still accepted, and is treated the same as a single-element
'compatible:'.
```

### CODE REVIEW

**Review by b0661 — COMMENTED** [review]
I could not get whether this is already covered - shouldn´t there be a test case for something like:
```
flash@2,0 {
            compatible = "samsung,k8f1315ebm", "cfi-flash";
        }
```

Compatibles listed from specific to less specific are usual at least in Linux.

If there is a "samsung,k8f1315ebm"-binding it shall be used. If there is none the "cfi-flash"-binding shall be used.  

The test should be extended by test cases for:
```
compatible = "compatible-with-no-binding", "compatible-with-binding";  
  ->  binding "compatible-with-binding" used for node
compatible = "compatible-with-high-prio-binding", "compatible-with-low-prio-binding";
  -> binding "compatible-with-high-prio-binding" used for node
```

**Comment by pabigot** [comment]
@ulfalizer Thanks for going through this.

I think the first step is a policy decision that has to go to TSC: **Is Zephyr mandated to be device-tree compatible with Linux and other systems?**  If so, then we have to follow Linux in heading towards dt-schema in all its complexity.  If not, we can do our own thing, though we'll have years of questions about "How come your stuff don't work with dt-schema?", and "OK, so how do I do this thing that I can do in dt-schema?".

This may be like MISRA: we have to do it, even if it causes pain.

**Comment by b0661** [comment]
@pabigot 

> Is Zephyr mandated to be device-tree compatible with Linux and other systems? 

The question as formulated may generate a mis-understanding. It is not about device-tree compatibility (the *.dts files). It is about how to describe the bindings (the *.yaml files). Zephyr can be device tree compatible but still using it´s own way to describe the bindings without using the json-schema way of Linux.

**Comment by galak** [comment]
> The question as formulated may generate a mis-understanding. It is not about device-tree compatibility (the *.dts files). It is about how to describe the bindings (the *.yaml files). Zephyr can be device tree compatible but still using it´s own way to describe the bindings without using the json-schema way of Linux.

Thinking of the bindings or dts as Linux specific is incorrect.  While Linux may be a main driver, the work around DTS from a binding and .dts file point of view should be utilizable by any software project.

My desire has always been that we move to dt-schema / json-schema binding definitions in Zephyr as than the work we are doing around bindings can be shared between other projects.  This was one of the main goals of doing dts in the first place.  While we haven't had a TSC specific direction on the specific item of binding format, we can raise that issue if its needed.

**Comment by galak** [comment]
I'd rather we not treat 'compatible' special in the binding files and utilize the enum concept.  We still need to deal with the few rare cases of 'device_type' matching as well.  I don't see a reason to create a new syntax for 'compatible' matching when the enum concept would work perfectly well.

**Comment by pabigot** [comment]
@b0661 you raise a good point, but like many things it's not binary.  I've updated [the comment](https://github.com/zephyrproject-rtos/zephyr/pull/18507#issuecomment-522981496) to identify some of the places where compatibility is important and crosses lines between source and binding.

I would really like to have a document describing the plan--what we are and are not trying to do, and the high level technical drivers for acceptable solutions--so it's not mostly in @galak's head with clues in sprinkled about in various comments in github issues, PRs, and slack threads.

Once there's a plan, it would be good to have TSC approval so we can slow down (if not stop) all this confusion about what we're trying to do, and instead just point to the existing approved description.

**Comment by galak** [comment]
> I'd rather we not treat 'compatible' special in the binding files and utilize the enum concept. We still need to deal with the few rare cases of 'device_type' matching as well. I don't see a reason to create a new syntax for 'compatible' matching when the enum concept would work perfectly well.

From the commit message:
> Note that just replacing 'constraint:' with an 'enum:' will make 'enum:'
work differently for 'compatible' than it does for any other property
(see the end of the background section), and to do it in a "proper"
dt-schema-like way, we'd need a ton more infrastructure.

Not sure I follow what the issue / difference is.  Today 'enum' is mostly for scalar types.  We just don't currently support enum on a list/array type.   If we do, than how would its functionality differ for 'compatible'?  Also, not reading the last bit of the background section, not sure I follow the bit about what support multiple compatibles as 'OR' would look like in dt-schema/json.

**Comment by ulfalizer** [comment]
> Not sure I follow what the issue / difference is. Today 'enum' is mostly for scalar types. We just don't currently support enum on a list/array type. If we do, than how would its functionality differ for 'compatible'? Also, not reading the last bit of the background section, not sure I follow the bit about what support multiple compatibles as 'OR' would look like in dt-schema/json.

See this part:

```
Note that the schema below would not do the right thing if you wanted to
require 'compatible' to have one of the elements "foo" or "bar" in it
(would need to add a 'contains:'):

    properties:
        compatible:
            enum:
                - "foo"
                - "bar"
```

What that specification means in jsonschema is that `compatible` must be "foo" or "bar". If the node that's being validated has something like this, then it will fail to validate:

    compatible = "foo", "something";

This is why you ran into that implementation snag in https://github.com/zephyrproject-rtos/zephyr/pull/18313. It's not how `enum` works.

It's helpful to [skim the jsonschema spec.](https://json-schema.org/specification.html) There was a misunderstanding earlier related to `oneOf` and `device_type` too.

We could of course say "meh, we'll just let `enum` work differently", but then you lose the entire reason for imitating dt-schema in the first place, which is to be helpful to people who already know it (since we don't implement all the other jsonschema stuff), because the global `compatible:` is nicer in all other ways.

See the various other ways of specifying compatible too, like this one:

```
  - Documentation/devicetree/bindings/arm/psci.yaml:

      compatible:
        oneOf:
          - const: arm,psci
          - const: arm,psci-0.2
          - items:
            - const: arm,psci-1.0
            - const: arm,psci-0.2

      ('compatible' must be set in one of these ways:

         compatible = "arm,psci";
         compatible = "arm,psci-0.2";
         compatible = "arm,psci-1.0", "arm,psci-0.2";

       'items' is another jsonschema thing.)
```

If we wanted to property pretend that we're jsonschema, we'd need this by the way:

```
properties:
    compatible:
        contains:
            enum:
                - "foo"
                - "bar"
```

That's just plain horrible to me.

**Comment by ulfalizer** [comment]
@b0661 
> I could not get whether this is already covered - shouldn´t there be a test case for something like:
> 
> ```
> flash@2,0 {
>             compatible = "samsung,k8f1315ebm", "cfi-flash";
>         }
> ```

Yeah, good to have a test for it. Added one in a separate commit.

**Comment by ulfalizer** [comment]
> We could of course say "meh, we'll just let `enum` work differently", but then you lose the entire reason for imitating dt-schema in the first place, which is to be helpful to people who already know it (since we don't implement all the other jsonschema stuff). The global `compatible:` is nicer in all other ways.

...and the reason we don't implement it is that we'd then need to have dtlib produce an intermediate format (with messy encoding for phandles and stuff) to hand to jsonschema, which is much worse than what we currently do.

What we have now kicks dt-schema's ass, basically, especially if we take it a bit further and get rid of some of the quirky stuff. I think we should do that instead of implement some cheap dt-schema knockoff.

**Comment by galak** [comment]
How do we handle the `device_type` matching case?

**Comment by galak** [comment]
The reason I was suggesting `enum` is to see how we could possibly convert our bindings to jsonschema/dt-schema in the future.  So how do various semantics we have map.  I'd argue that our current use of `enum` maps specifically to `contains: enum:` from the json schema point of view.

If we wanted to mimic things I guess we'd need to support these specific cases:

```
select:
  properties:
    compatible:
      contains:
        enum:
```

and

```
select:
  properties:
    compatible:
      contains:
        const:
```

So at least I can see how we'd convert `compatible: ` to one of these 2.

**Comment by ulfalizer** [comment]
> How do we handle the `device_type` matching case?

For Zephyr, we shouldn't. It's old legacy crap that we don't need, and just adds confusion. We should rise above the level of just pattern-matching and look at why things are used, and if they're any good on their own. A mess that looks vaguely familiar is still a mess.

To support it in edtlib for other projects, I think it would be simplest to have a

     device_type: foo

field at the top level in the binding. Don't think it's high-prio though.

> The reason I was suggesting `enum` is to see how we could possibly convert our bindings to jsonschema/dt-schema in the future. So how do various semantics we have map. I'd argue that our current use of `enum` maps specifically to `contains: enum:` from the json schema point of view.

If the project switches to jsonschema one day (not sure how we'd use the dt-schema tools directly), it won't be that hard to convert the bindings anyway. I'd consider it a downgrade.

> If we wanted to mimic things I guess we'd need to support these specific cases:
> 
> ```
> select:
>   properties:
>     compatible:
>       contains:
>         enum:
> ```
> 
> and
> 
> ```
> select:
>   properties:
>     compatible:
>       contains:
>         const:
> ```
> 
> So at least I can see how we'd convert `compatible: ` to one of these 2.

I don't think we should mimic it, because it only really makes sense if you're actually jsonschema, and looks horrible and confusing and redundant otherwise. Especially to newcomers who have no way of knowing that it's just a silly hardcoded thing internally.

```
If we wanted to properly pretend that we're jsonschema, we'd need this by the
way:

properties:
    compatible:
        contains:
            enum:
                - "foo"
                - "bar"

That's just plain horrible to me.
```

Sorry for being cranky, but I'm really tired of this dt-schema (cargo) cult. As far as I'm concerned, dt-schema can take a hike, and I'm probably the guy who knows it the best at this point.

Let's just create something nice that works well for us instead, without everything being about how much we superficially look like dt-schema. I promise people will like it.

**Comment by galak** [comment]
On `device_type`, I'm well aware of your feeling that we shouldn't utilize in Zephyr, but one of the main intents of device tree usage in Zephyr has always been on sharing that device tree with other projects.  As such we can't just ignore long establish ways of doing things.

I'm not looking to utilize `device_type` for anything new, but for the one major use of `device_type = memory`.  There has been a desire to share DTS with Linux for example on STM32 SoCs that have both Linux & Zephyr support.

The cases that we have 'true SRAM' will stay as they are, its only the few cases of real SDRAM/DDR that I plan on moving to `device_type = memory`.

**Comment by ulfalizer** [comment]
@galak 
A desire from who? Most people were perfectly happy to remove `device_type`.

No one will miss it when it's gone, trust me. At the moment, it's just more stuff that people blindly copy around because they assume it must be good for something.

**Comment by ulfalizer** [comment]
Replaced with https://github.com/zephyrproject-rtos/zephyr/pull/18766.

**Pull request closed without merging**
