### PR TITLE
boards: arm: stm32f469i_disco: doc: fix small typo

### PR DESCRIPTION
**Pull request by pamolloy**

### CODE REVIEW

**Review by FRASTM — DISMISSED** [review]

**Comment by FRASTM** [comment]
This typo is common to many  ./boards/arm/. Probably a copy-paste which was propagated during months...

**Comment by pamolloy** [comment]
> This typo is common to many ./boards/arm/. Probably a copy-paste which was propagated for months...

Wow, yup, nearly 90 times. Should I fix them all in one commit?

**Comment by erwango** [comment]
> Wow, yup, nearly 90 times. Should I fix them all in one commit?

Would be great. One commit would do.

**Review by nandojve — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
Note to release engineers: Trivial label is still applicable here even if this grew to updating many more lines -- it's still a trivial typo fix.

Thanks, @pamolloy!

**Review by erwango — APPROVED** [review]
Thanks!

**Pull request merged**
