### PR TITLE
samples: application_development: drop oot board/driver samples 

### PR DESCRIPTION
**Pull request by gmarull**
Because there are more comprehensive examples in the Zephyr's
example-application repository. Application development samples page now
points to example-application as well.

### CODE REVIEW

**Review by martinjaeger — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by nashif** [comment]
> Because there are more comprehensive examples in the Zephyr's
> example-application repository. Application development samples page now
> points to example-application as well.

do we build those tests/samples on each PR? Wouldn't issues be discovered late if we have to rely on example-application to verify oot drivers/board? Maybe it is time to link tests of example-application into main CI for each PR similar to how we do it with other modules.

**Comment by fabiobaltieri** [comment]
> do we build those tests/samples on each PR? Wouldn't issues be discovered late if we have to rely on example-application to verify oot drivers/board? Maybe it is time to link tests of example-application into main CI for each PR similar to how we do it with other modules.

There's a nightly run there https://github.com/zephyrproject-rtos/example-application/actions?query=event%3Aschedule, would not be too hard to have a separate test for this inside the main repo.

**Comment by gmarull** [comment]
> > do we build those tests/samples on each PR? Wouldn't issues be discovered late if we have to rely on example-application to verify oot drivers/board? Maybe it is time to link tests of example-application into main CI for each PR similar to how we do it with other modules.
> 
> There's a nightly run there https://github.com/zephyrproject-rtos/example-application/actions?query=event%3Aschedule, would not be too hard to have a separate test for this inside the main repo.

testing in the main repo creates a circular dependency ;-)

**Comment by kartben** [comment]
@gmarull If you have a chance, could you add entries to `doc/_scripts/redirects.py` so that ex. https://docs.zephyrproject.org/3.4.0/samples/application_development/out_of_tree_board/README.html properly redirects folks who click "The [latest development version](https://docs.zephyrproject.org/latest/samples/application_development/out_of_tree_board/README.html) of this page may be more current than this released 3.4.0 version."?
Thanks!

**Comment by gmarull** [comment]
> @gmarull If you have a chance, could you add entries to `doc/_scripts/redirects.py` so that ex. https://docs.zephyrproject.org/3.4.0/samples/application_development/out_of_tree_board/README.html properly redirects folks who click "The [latest development version](https://docs.zephyrproject.org/latest/samples/application_development/out_of_tree_board/README.html) of this page may be more current than this released 3.4.0 version."? Thanks!

Hmmm, we can't change released docs, right?

**Comment by kartben** [comment]
> > @gmarull If you have a chance, could you add entries to `doc/_scripts/redirects.py` so that ex. https://docs.zephyrproject.org/3.4.0/samples/application_development/out_of_tree_board/README.html properly redirects folks who click "The [latest development version](https://docs.zephyrproject.org/latest/samples/application_development/out_of_tree_board/README.html) of this page may be more current than this released 3.4.0 version."? Thanks!
> 
> Hmmm, we can't change released docs, right?

Ya but it's the other way around :) The 3.4.0 page tries to send people to https://docs.zephyrproject.org/latest/samples/application_development/out_of_tree_board/README.html, which is a 404 right now -- if you add a redirect from application_development/out_of_tree_board --> application_development/ it will take care of taking the visitor to the actual "more current" information.

**Pull request merged**
