### PR TITLE
[RFC] Kconfig: Configure IRQ_NUMS using edt

### PR DESCRIPTION
**Pull request by erwango**
Each soc should provide IRQ_NUMS as the highest IRQ number used in the binary to set the size of the irq table.
Provide a utility function to get this information from device tree.

Simplify SoC porting and saves a few binary bytes by setting IRQ_NUM value that reflects the exact needs of the application

### CODE REVIEW

**Comment by erwango** [comment]
I'll fix reported build issues, though I don't get why `qemu_cortex_r5` and `bcm958402m2_a72` could be impacted by this change, as I don't see no reason the function is run when building these targets.

**Review by mbolivar-nordic — COMMENTED** [review]
Do we need `CONFIG_NUM_IRQS` at all? Does a user ever need to override the value from DT?

**Comment by erwango** [comment]
> Do we need `CONFIG_NUM_IRQS` at all? Does a user ever need to override the value from DT?

I guess that's a question for arch maintainers

**Comment by mbolivar-nordic** [comment]
> > Do we need `CONFIG_NUM_IRQS` at all? Does a user ever need to override the value from DT?
> 
> I guess that's a question for arch maintainers

cc @andrewboie as I'm guessing not on Cortex-M devices

**Comment by erwango** [comment]
> Do we need CONFIG_NUM_IRQS at all? Does a user ever need to override the value from DT?

@aescolar, would you be impacted ?

**Comment by mbolivar-nordic** [comment]
> > Do we need `CONFIG_NUM_IRQS` at all? Does a user ever need to override the value from DT?
> 
> I guess that's a question for arch maintainers

@ioannisg @carlocaione can you comment for Arm?

**Comment by carlocaione** [comment]
Yes. AArch64 is actually planning to use `CONFIG_NUM_IRQS` in #33282 (see https://github.com/zephyrproject-rtos/zephyr/pull/33282/files). We use that to check if the IRQ is out of bounds because sometimes we receive a spurious IRQ from the GIC with intid == 1023. That said I can rework that PR to not use `CONFIG_NUM_IRQS` if needed.

**Comment by mbolivar-nordic** [comment]
@carlocaione I looked at that PR and I see CONFIG_NUM_IRQs is read, but I don't see the value being overridden.

The question is basically if you ever need to dynamically allocate interrupts outside of the range of numbers that are known in the DTS file. If nobody needs to do that, we can just provide ZEPHYR_DT_NUM_IRQS which reads the value from DTS directly, and not have to 'indirect' the  value through Kconfig. The reason things are the way they are now is that CONFIG_NUM_IRQS is older in Zephyr than DTS.

**Comment by carlocaione** [comment]
> The question is basically if you ever need to dynamically allocate interrupts outside of the range of numbers that are known in the DTS file.

Uhm, outside the range probably not but not known to the DTS file yes, IPI / SGI for example.

**Comment by mbolivar-nordic** [comment]
OK, so sounds like a maximum value determined by DT is OK in the Aarch64 case at least then, right?

**Comment by carlocaione** [comment]
> OK, so sounds like a maximum value determined by DT is OK in the Aarch64 case at least then, right?

Correct.

Another point I think is to rework a bit the dynamic IRQ allocation to take into account the upper bound. There is also something to fix for example in `tests/kernel/interrupt/src/nested_irq.c`

**Review by galak — CHANGES_REQUESTED** [review]
I'd like to see if we can move some of the kconfig "code" into edtlib.py

What I've wanted for sometime is to add a Controller class for things like IRQController, GPIOController, etc.. and you could than get access to all the "irqs", "gpios", etc for that controller.  We can than also easily have a method on the Controller class to get the "highest" number.

**Comment by aescolar** [comment]
> > Do we need CONFIG_NUM_IRQS at all? Does a user ever need to override the value from DT?
> 
> @aescolar, would you be impacted ?

That for the ping @erwango . Nope, POSIX arch boards get the total number of interrupts from the HW models directly without user configurability.

**Comment by erwango** [comment]
> That for the ping @erwango . Nope, POSIX arch boards get the total number of interrupts from the HW models directly without user configurability.

@aescolar by HW model, do you mean DTS? And is that fine if IRQ_NUM Kconfig symbol is purely removed ?

**Comment by aescolar** [comment]
> > That for the ping @erwango . Nope, POSIX arch boards get the total number of interrupts from the HW models directly without user configurability.
> 
> @aescolar by HW model, do you mean DTS? And is that fine if IRQ_NUM Kconfig symbol is purely removed ?

I mean HW simulation models :) (e.g. https://github.com/BabbleSim/ext_NRF52_hw_models/) . CONFIG_IRQ_NUM is not used for any purpose (AFAIK) in the POSIX arch.

**Comment by erwango** [comment]
@aescolar ok then. Thanks for the feedback!

**Comment by mbolivar-nordic** [comment]
> What I've wanted for sometime is to add a Controller class for things like IRQController, GPIOController, etc.. and you could than get access to all the "irqs", "gpios", etc for that controller. We can than also easily have a method on the Controller class to get the "highest" number.

That doesn't affect the question of whether or not we need to keep the Kconfig option or not, right?

**Comment by erwango** [comment]
> What I've wanted for sometime is to add a Controller class for things like IRQController, GPIOController, etc.. and you could than get access to all the "irqs", "gpios", etc for that controller. We can than also easily have a method on the Controller class to get the "highest" number.

I had a preliminary look and from what I can see a similar class already exists (`ControllerAndData`). So, is the idea to add complementary functions to this class ?

**Comment by mbolivar-nordic** [comment]
>  So, is the idea to add complementary functions to this class ?

The idea would be to subclass edtlib.Node with edtlib.Controller, and subclass Controller with edtlib.GpioController, edtlib.InterruptController, etc. Then depending on the devicetree, allocate some nodes as the appropriate controller nodes instead of plain edtlib.Node. That would in turn let you add controller-specific APIs to the subclasses.

**Comment by erwango** [comment]
> > So, is the idea to add complementary functions to this class ?
> 
> The idea would be to subclass edtlib.Node with edtlib.Controller, and subclass Controller with edtlib.GpioController, edtlib.InterruptController, etc. Then depending on the devicetree, allocate some nodes as the appropriate controller nodes instead of plain edtlib.Node. That would in turn let you add controller-specific APIs to the subclasses.

Thanks @mbolivar-nordic for these details.

I had a first look. From what I saw (please correct me), when adding these classes, we'll create some redundancy with existing part of the code that deals with controllers already (specially for interrupts). 
So either:
- we refactor these parts to make use of controllers
- we keep that part separate for now. Accept there is some redundancy and use controller sub-classes separately for dedicated usage (at least in this first step)

Tbh, I'm not comfortable with the first option, and you'll probably spend more time in reviewing than implementing yourself the whole stuff. Though, I can have a try on the second part, which seems feasible with some time and few review iterations

@mbolivar-nordic, @galak, please let me know if you're fine with this second proposal.

**Comment by mbolivar-nordic** [comment]
Erwan Gouriou ***@***.***> writes:
> @mbolivar-nordic, @galak, please let me know if you're fine with this second proposal.

I'm OK with that as a starting out point. I expect having something
generic will reveal a lot about what we need to do to the current
special cases anyway.

**Comment by galak** [comment]
> I'm OK with that as a starting out point. I expect having something generic will reveal a lot about what we need to do to the current special cases anyway.

I think I'm fine with that, but not 100% sure I'm clear on what you mean.  Are you saying have a unique interrupt controller class and gpio controller class that don't inherit from the same thing?  If so, I'm fine with that and we can refactor later.

**Comment by erwango** [comment]
> > I'm OK with that as a starting out point. I expect having something generic will reveal a lot about what we need to do to the current special cases anyway.
> 
> I think I'm fine with that, but not 100% sure I'm clear on what you mean. Are you saying have a unique interrupt controller class and gpio controller class that don't inherit from the same thing? If so, I'm fine with that and we can refactor later.

Point is that once they will be available, there would potentially be existing parts of the code that could take advantage of it.
Anyway, I'll have a first try and then we'll see.

**Comment by erwango** [comment]
@galak @mbolivar-nordic. Unfortunately, I had no time to spend sufficient time on this to make it progress.
I won't be able to make this progress next month neither (holidays), so please don't wait for me on that point
if you want to see short term progress.

**Pull request closed without merging**
