### PR TITLE
logging: add STP transport and raw data output support for syst

### PR DESCRIPTION
**Pull request by wentongwu**
Add STP transport support for MIPI SyS-T with Kconfig MIPI_SYST_STP.
And with Kconfig MIPI_SYST_RAW_DATA, add raw data output support for
MIPI SyS-T protocol stack.

Signed-off-by: Wentong Wu <wentong.wu@intel.com>

### CODE REVIEW

**Comment by wentongwu** [comment]
Depends on https://github.com/zephyrproject-rtos/mipi-sys-t/pull/2

**Comment by wentongwu** [comment]
@nashif @andrewboie @nordic-krch could you please help review this PR? Thanks

**Comment by wentongwu** [comment]
this PR will add more code when https://github.com/zephyrproject-rtos/zephyr/pull/29482 merged.

**Comment by wentongwu** [comment]
@nashif ping...

**Comment by wentongwu** [comment]
ping

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by carlescufi** [comment]
@nordic-krch would you mind taking a look please? It would be good to have the maintainer approve this.

**Review by nordic-krch — APPROVED** [review]
Looks ok from code perspective. I'm not familiar with syst backend thus cannot comment on functionality.

**Pull request merged**
