### PR TITLE
boards: arm: add the Arduino Nano 33 IOT

### PR DESCRIPTION
**Pull request by nzmichaelh**
The Arduino Nano 33 IOT is a a small form factor development board with USB, Wifi, Bluetooth, a 6 axis IMU, and secure element.

This adds the basic support for the SAMD21.  Follow up PRs will add the IMU driver and, hopefully, a NINA Wifi driver.

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
Looks fine to me

**Comment by nzmichaelh** [comment]
@ioannisg thanks.  I'm planning on getting the IMU working and then turning off the 'draft' bit.

**Review by galak — APPROVED** [review]

**Comment by nzmichaelh** [comment]
The IMU driver PR is in-flight but will need some work.  Might as well land this.

**Comment by WilliamGFish** [comment]
@nzmichaelh  Good work, there is an existing driver for the ESP32 which the Ublox module is based on. It is for a UART Wi-Fi modem but could be worth looking at. There may be a fair amount of commonality bar the different i/f (UART vs SPI)

I am working on the principle that the Arduino board uses the AT command firmware rather than anything special.

**Comment by nzmichaelh** [comment]
Thanks @WilliamGFish FYI I gave this a try when I first got the board and it kind of worked.  The NINA was 2 MiB of flash so needs a special build.

There's advantages in supporting the NINA directly as well - less work for the user, the SPI bus is faster, and it solves flow control issues as the device can control how fast data is received.

The downside is yet another driver which means more bugs :)

**Comment by WilliamGFish** [comment]
I hoped they hadn't created a unique firmware for the Nina, the Particle board has a custom firmware with a restricted command set. 
I had to reprogram the esp with a stock ROM to get everything working. 

As an aside, I'm looking at the Nano 33 Sense (nrf52840) but I'm not proficient at BOSSA. So could use some help.

**Comment by nzmichaelh** [comment]
The Sense seems to use a NINA-B3X which is a nRF52840 under the hood.  BOSSA is SAM0 only, so I suspect you'll end up using a different bootloader - but might still end up using the Arduino 1200 baud reset trigger.

**Comment by WilliamGFish** [comment]
Arduino use BOSSA to program via thier IDE, so it can be done. I don't want to have to charge the firmware first. On 27 Jul 2020 19:01, Michael Hope <notifications@github.com> wrote:
The Sense seems to use a NINA-B3X which is a nRF52840 under the hood.  BOSSA is SAM0 only, so I suspect you'll end up using a different bootloader - but might still end up using the Arduino 1200 baud reset trigger.

**Pull request merged**
