### PR TITLE
remove flag for dwarf v4

### PR DESCRIPTION
**Pull request by benediktibk**
Pyelftools supports dwarf v5 since 0.28, therefore there is no need anymore to enforce dwarf v4.

### CODE REVIEW

**Comment by benediktibk** [comment]
The actual fix which enabled the usage of DWARF v5 came from here: https://github.com/eliben/pyelftools/issues/588

**Review by tejlmand — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
@benediktibk main is very unhappy right now :) https://github.com/zephyrproject-rtos/zephyr/actions/runs/12430745435

lining up a revert...

cc @tejlmand @fabiobaltieri

**Comment by benediktibk** [comment]
Weird how the tests for this PR ran successfully ...

**Comment by fabiobaltieri** [comment]
> Weird how the tests for this PR ran successfully ...

Unfortunately the testsplan of the PR is different then the one om main (which is also a subset of all possible combinations of tests and platforms) so some platform specific things are bound to be missing and found later unfortunately. You can use the list from https://github.com/zephyrproject-rtos/zephyr/runs/34712367603 to run them manually, seems something on just a couple of platforms.

**Pull request merged**
