### PR TITLE
genrest: De-spam docs by skipping direct deps. in more places

### PR DESCRIPTION
**Pull request by ulfalizer**
Similar deal to commit cc14c40a2d ("kconfiglib: Unclutter symbol
strings, avoid redundant writes, misc.").

Hide the direct dependencies in the defaults, selects, and implies
sections. Do the same in menuconfig/guiconfig as well.

This uses a new Kconfiglib API, so update Kconfiglib to upstream
revision 164ef007a8. This also includes some minor optimizations and
cleanups.

### CODE REVIEW

**Comment by ulfalizer** [comment]
Before:

before

After:

after

(Though there are examples where it helps more.)

CC @carlescufi 
This is just some vacation stuff. Need to learn to unplug and not look at code, because I always find missing stuff that annoys me... :P

**Review by nashif — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
LTGM.  While you're in there, if you were to change ``if's`` to just ``ifs`` that would be good.  That's a misuse of an apostrophe (should be used to indicate possession, not plural).

**Comment by ulfalizer** [comment]
@dbkinder 
Fixed. Was going for some "not a literal if" thing, but I guess it looks confusing.

**Review by dbkinder — APPROVED** [review]
Thanks :)

**Comment by carlescufi** [comment]
> This is just some vacation stuff. Need to learn to unplug and not look at code, because I always find missing stuff that annoys me... :P

Hehe, welcome to the club :)

**Pull request merged**
