### PR TITLE
Bluetooth: controller: split: Assorted control procedure fixes

### PR DESCRIPTION
**Pull request by cvinayak**
These are some of ported commits from legacy controller implementation to split controller.

See individual commits for details.

### CODE REVIEW

**Comment by cvinayak** [comment]
@wopu-ot @thoh-ot can I get some reviews here? How does this PR go with your internal testing?

**Comment by wopu-ot** [comment]
> @wopu-ot @thoh-ot can I get some reviews here? How does this PR go with your internal testing?

Internal testing looks okay, but I am struggling to find time to review the code.

**Comment by cvinayak** [comment]
@wopu-ot ok. 

@aescolar do we need to merge before v2.1 code freeze or we can take the merge starting next week when I will concentrate on getting conformance test passing? I have few more commits waiting in my private branch due to dependencies that need to be sent as PR.

**Comment by aescolar** [comment]
> @aescolar do we need to merge before v2.1 code freeze or we can take

This is a fix, not a new feature, so it should be ok to merge it after feature freeze. But it is also quite extensive, so it would be nice to get it in relatively soon to have some more mileage before the release. Meaning, your call when to merge it :)

**Review by thoh-ot — APPROVED** [review]
Internally EBQ testing shows no regression from this PR

**Comment by aescolar** [comment]
@carlescufi As agreed yesterday, this PR would then be mergable, If you still think so, please do the honors :)

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
