### PR TITLE
PTP bug fixes

### PR DESCRIPTION
**Pull request by kartben**
I spent some time playing with PTP and pulled my hair out with a couple issues which I am hoping the two commits in this PR are the correct fix for.
This was tested on STM32F746G DISCO

### CODE REVIEW

**Review by jukkar — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Comment by kartben** [comment]
@awojasinski ideally you can also test on your hardware :) Thanks in advance!

**Comment by awojasinski** [comment]
@kartben thanks for spotting the bug. I don't know how I overlooked that. Yes, I'll test that on my setup today afternoon but LGTM

**Review by awojasinski — APPROVED** [review]

**Comment by awojasinski** [comment]
I have some troubles with sending packets from Linux to dev board but I don't want to block PR

**Comment by kartben** [comment]
> I have some troubles with sending packets from Linux to dev board but I don't want to block PR

Would be curious to know on what boards you've tested (either pre or post- my PR). 
FWIW, on STM32H7 and H5 there seems to be a recent(ish) regression in the HAL causing PTP to not work properly. See https://discord.com/channels/720317445772017664/883445358821249084/1258808027507855380

**Pull request merged**
