### PR TITLE
 boards: Rename mimxrt1050_evk to add -b suffix 

### PR DESCRIPTION
**Pull request by MaureenHelm**
Make it clear that we are supporting the EVKB version of the board (A1
silicon), not the discontinued EVK version of the board (A0 silicon).
This unfortunately causes documentation links to change, but removes
ambiguity in the code and documentation.

### CODE REVIEW

**Review by MeganHansen — COMMENTED** [review]
Did you add "-b" or "b" standalone without the "-"? If you follow exact NXP part numbering, it would/should be imxrt1050_evkb (without "-" and without "m" at front).  I agree to add the "b" in any case, so please consider approved, with the "b" or "-b" appendage.

**Review by dbkinder — APPROVED** [review]
doc changes LGTM, thanks.

**Review by jhqian — COMMENTED** [review]
Hi @MaureenHelm, I'm not very sure why it is necessary to change it to mimxrt1050-evkb. If we're going to keep only board EVK for RT1050 in zephyr, it does not much difference to leave it as is, and perhaps add a config item in the Kconfig the differentiate the A0 and A1 silicon if necessary. By the way, the new board name is IMXRT1050-EVKB, no leading M.

**Review by nashif — APPROVED** [review]

**Review by agansari — APPROVED** [review]
> IMXRT1050-EVKB, no leading M.

I would drop the M, but it looks a lot better than before.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@MaureenHelm I see there's still a couple of unresponded comments so I'll hold off on merging this.

**Comment by MaureenHelm** [comment]
> Did you add "-b" or "b" standalone without the "-"? If you follow exact NXP part numbering, it would/should be imxrt1050_evkb (without "-" and without "m" at front). I agree to add the "b" in any case, so please consider approved, with the "b" or "-b" appendage.

@MeganHansen I changed the name from `mimxrt1050_evk` to `mimxrt1050_evkb`. By "standard", do you mean the orderable part number for the board? The MCUXpresso SDK calls this board `evkbimxrt1050` in the file system.

> I'm not very sure why it is necessary to change it to mimxrt1050-evkb. If we're going to keep only board EVK for RT1050 in zephyr, it does not much difference to leave it as is, and perhaps add a config item in the Kconfig the differentiate the A0 and A1 silicon if necessary. By the way, the new board name is IMXRT1050-EVKB, no leading M.

@jhqian I'm not eager to change the name at all, but I'm concerned that we will confuse people if we don't. I started to update the existing board doc page for A1 silicon, and it was really awkward to say "we call this board `evk` in zephyr but really we mean `evkb`"

> I would drop the M, but it looks a lot better than before.

If we drop the M, we should probably do it for all rt boards.

Marking as DNM for now until we have a consensus on naming scheme, because I don't want to change it more than once.

**Comment by agansari** [comment]
>  I'm not eager to change the name at all, but I'm concerned that we will confuse people if we don't. 

> If we drop the M, we should probably do it for all rt boards.

Agree with both statements , the reason I suggested removing M from MIMX... is to make i.MX family naming less confusing.
As this pull request refers to 1050, we can postpone this for another pull request.

**Comment by jhqian** [comment]
@MaureenHelm , I don't think we need to remove all the leading M for all the RT boards, since others do have that M. IMHO, either we change it to exactly the same what is printed on the PCB or just leave it. Perhaps, we can add a note in the board doc to clarify it.

**Pull request closed without merging**
