### PR TITLE
MAINTAINERS: Remove myself from POSIX subsys maintainers.

### PR DESCRIPTION
**Pull request by pfalcon**
To not keep the entry empty, move to collaborators.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
Recently, I couldn't pay much attention to the maintenance of the POSIX subsys, and this PR reflects that.

**Review by ioannisg — CHANGES_REQUESTED** [review]
@pfalcon  I suppose the area should be set to "orphaned", if you are not planning to maintain it any more.

**Comment by pfalcon** [comment]
@ioannisg: I wasn't sure what the process is, maybe there's some call/period for new maintainer to surface, and only then it's set to "orphaned". If that should be done in this patch, I'll do that.

**Comment by pfalcon** [comment]
@ioannisg: Updated.

**Review by ioannisg — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
