### PR TITLE
Bluetooth: host: Update configuration of L2CAP RX MTU setting

### LINKED ISSUE #25652: smp_svr fails for nrf5340
[placeholder for proper bug report when I have time]

Message is incorrectly split when transferring image in `smp_svr` for nRF5340

Perform FOTA for smp_svr using nRF Connect on iOS

The mcumgr response should be sent as a fragmented L2CAP-messag, instead it is split up.

See filenames in wireshark trace for relevant packets.

[trace.zip](https://github.com/zephyrproject-rtos/zephyr/files/4687442/trace.zip)

### LINKED ISSUE #26536: The CONFIG_BT_L2CAP_RX_MTU setting is not reflected correctly in the build
**Describe the bug**
The `CONFIG_BT_L2CAP_TX_MTU` and `CONFIG_BT_L2CAP_RX_MTU` setting are not reflected correctly in the build. The resulting negotiated mtu capped to 68 bytes.

**To Reproduce**
1. Set `CONFIG_BT_L2CAP_TX_MTU` and `CONFIG_BT_L2CAP_RX_MTU` to 255
2. Create a ble service with read and notify characteristic
3. Create notification with payload at least 70 bytes long
4. Open NRF connect android app, go to setting and select `Connectivity` and enable `Auto request maximum MTU`. This will negotiate MTU to 517 bytes.
5. Scan, and connect to the ble device then in the characteristic created in 2, enable notification on that service.

**Expected behavior**
The negotiated MTU should be 255 `min(server_mtu, client_mtu)`, `min(255, 517)` and the notification is triggered successfully. 

**Impact**
*showstopper*

**Logs and console output**
```
[00:00:09.949,859] <dbg> bt_att.find_info_cb: handle 0x0017
[00:00:09.964,996] <dbg> bt_att.att_rsp_sent: conn 0x200019e4 att 0x200026f0
[00:00:09.965,026] <dbg> bt_att.att_pdu_sent: conn 0x200019e4 att 0x200026f0
[00:00:09.972,167] <dbg> bt_att.bt_att_recv: Received ATT code 0x02 len 2
[00:00:09.972,198] <dbg> bt_att.att_mtu_req: Client MTU 517
[00:00:09.972,229] <dbg> bt_att.att_mtu_req: Server MTU 68
[00:00:09.972,229] <dbg> bt_att.att_mtu_req: Negotiated MTU 68
[00:00:09.987,121] <dbg> bt_att.att_rsp_sent: conn 0x200019e4 att 0x200026f0
[00:00:09.987,152] <dbg> bt_att.att_pdu_sent: conn 0x200019e4 att 0x200026f0
[00:01:04.166,870] <wrn> bt_att: ATT MTU exceeded, max 68, wanted 77
[00:01:04.166,870] <wrn> bt_gatt: No buffer available to send notification
```

**Environment (please complete the following information):**
 - OS: Mac
 - PlatformIo
 - 2.2

**Additional context**
In `subsys/bluetooth/host/att_internal.h` line 12
```
#if BT_L2CAP_RX_MTU < CONFIG_BT_L2CAP_TX_MTU
#define BT_ATT_MTU BT_L2CAP_RX_MTU
#else
#define BT_ATT_MTU CONFIG_BT_L2CAP_TX_MTU
#endif
```

while the `BT_L2CAP_RX_MTU` is defined in `subsys/bluetooth/host/l2cap_internal.h` line 196.
```
#if defined(CONFIG_BT_HCI_ACL_FLOW_CONTROL)
#define BT_L2CAP_RX_MTU CONFIG_BT_L2CAP_RX_MTU
#else
#define BT_L2CAP_RX_MTU (CONFIG_BT_RX_BUF_LEN - \
			 BT_HCI_ACL_HDR_SIZE - BT_L2CAP_HDR_SIZE)
#endif
```

As the snippet indicates, unless the `CONFIG_BT_HCI_ACL_FLOW_CONTROL` is set to `y`, the `BT_L2CAP_RX_MTU` will be set to that following calculation. Which I believe resulting in 68 by default. 

My solution is to set `CONFIG_BT_HCI_ACL_FLOW_CONTROL` to `y` then the `server_mtu` value is calculated correctly. The documentation of this config doesn't mention anything about how it is affecting the MTU negotiation.

**Suggestion**
If this is intended, please update the documentation. If not, please address this MTU configuration so that less coupled with that guard.

### PR DESCRIPTION
**Pull request by joerchan**
Remove dependency on CONFIG_BT_ACL_FLOW_CONTROL and use
CONFIG_BT_L2CAP_RX_MTU always to set L2CAP RX MTU.
The ATT MTU is set from two different KConfig options depending
on if CONFIG_BT_ACL_FLOW_CONTROL is enabled, which makes it
a confusing option and hard to provide a conf file that
supports multiple board configurations.

This changes the behavior when CONFIG_BT_ACL_FLOW_CONTROL and
CONFIG_BT_BUF_RX_LEN was used to set the L2CAP RX MTU, and by
extension the ATT MTU.

Fixes: #26536

Fix smp_svr Bluetooth configuration for when BT_HCI_ACL_FLOW_CONTROL
option has been enabled. In this case the CONFIG_BT_L2CAP_RX_MTU
is used instead of CONFIG_BT_RX_BUF_LEN to set the RX MTU.
This lead to a negotiated MTU of 23, which is not supported by
the SMP_SVP protocol.

Removed the board specific configuration files as these are just
duplications of the overlay-bt.conf or overlay-bt-tiny.conf and
the readme specifies how these should be used.

Fixes: #25652

### CODE REVIEW

**Comment by hakonfam** [comment]
@nvlsianpu should the SMP code be aware that it requires a specific MTU, and give a warning/error if this is not configured correctly? With only this fix I suspect that users might end up in the same situation when re-cofiguring the sample, or including the subsystems from another sample.

**Comment by joerchan** [comment]
For reference: https://github.com/apache/mynewt-mcumgr/issues/6

**Comment by nvlsianpu** [comment]
>should the SMP code be aware that it requires a specific MTU, and give a warning/error if this is not configured correctly? With only this fix I suspect that users might end up in the same situation when re-cofiguring the sample, or including the subsystems from another sample.

@hakonfam I can add an assertion to [smp_bt_init()](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/mgmt/smp_bt.c#L193).

Is that you were suggesting?

**Review by nvlsianpu — COMMENTED** [review]
Maybe CMakeLists.txt can be modified so it will set OVERLAY_CONFIG variable for nRF boards.
?

**Comment by joerchan** [comment]
> Maybe CMakeLists.txt can be modified so it will set OVERLAY_CONFIG variable for nRF boards.
> ?

Not sure that is a good idea, some might wish to use smp_svr on nRF boards without bluetooth.

**Comment by hakonfam** [comment]
> > should the SMP code be aware that it requires a specific MTU, and give a warning/error if this is not configured correctly? With only this fix I suspect that users might end up in the same situation when re-cofiguring the sample, or including the subsystems from another sample.
> 
> @hakonfam I can add an assertion to [smp_bt_init()](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/mgmt/smp_bt.c#L193).
> 
> Is that you were suggesting?

That would be good

**Review by hakonfam — APPROVED** [review]
I have verified that it fixes the issues reported.

**Review by nvlsianpu — COMMENTED** [review]
Can smp_svr  sample manual be updated to reflect the fact that need to be build with appropriate *.conf file for given target?
Previously it was building right away for nrf51dk, nrf52dk, nrf52840dk.

**Comment by joerchan** [comment]
> Can smp_svr sample manual be updated to reflect the fact that need to be build with appropriate *.conf file for given target?
> Previously it was building right away for nrf51dk, nrf52dk, nrf52840dk.

@nvlsianpu Isn't what is already there good enough?

**Review by nvlsianpu — APPROVED** [review]
> Can smp_svr sample manual be updated to reflect the fact that need to be build with appropriate *.conf file for given target?
Previously it was building right away for nrf51dk, nrf52dk, nrf52840dk.

> @nvlsianpu Isn't what is already there good enough?

You are right, https://docs.zephyrproject.org/latest/samples/subsys/mgmt/mcumgr/smp_svr/README.html#building-the-sample-application is enough descriptive. I missed that.

**Review by Vudentz — APPROVED** [review]
LGTM

**Pull request merged**
