### PR TITLE
bluetooth: controller: remove redundant header inclusions

### PR DESCRIPTION
**Pull request by ioannisg**
nrf_timer.h and nrf_ppi.h are included by including
radio_nrf5.h, so we do not need to include them in
radio.c.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
@cvinayak please, take a quick  look

**Review by cvinayak — APPROVED** [review]

**Review by aescolar — COMMENTED** [review]
About the ifdef comments +1
About the header inclusion: I do not think it is too good practice to get required headers thru other headers. But that is a bit of a preference thing. So I do not give a + or -1

**Comment by ioannisg** [comment]
> 
> 
> About the ifdef comments +1
> About the header inclusion: I do not think it is too good practice to get required headers thru other headers. But that is a bit of a preference thing. So I do not give a + or -1

Thanks. It is actually a very good practice, because you can include the header files through platform-specific headers (which are anyway included in radio.c)

My purpose is to avoid as much as I can, having all these #ifdef NRF_SOC_SERIES_A, #ifdef NRF_SOC_SERIES_B defined in radio.c which should serve as common for all platforms.

**Comment by ioannisg** [comment]
BTW, @aescolar I like to  invite you in this kind of reviews because these changes might affect the simulator

**Comment by aescolar** [comment]
> BTW, @aescolar I like to invite you in this kind of reviews because these changes might affect the simulator

@ioannisg Thanks :) (Note that the nrf52_bsim is built and a couple of testcases with BLE traffic are run in the simulator in CI, so hopefully it does not break)

**Pull request merged**
