### PR TITLE
p4wq: add optional group_id priority

### PR DESCRIPTION
**Pull request by abonislawski**
Example set of changes to support SOF_SCHEDULE_COMM scheduler:
https://github.com/thesofproject/sof/issues/7238

The main changes is group_id in work item which allows work items to be sorted by groups within the same priority.

### CODE REVIEW

**Review by aborisovich — DISMISSED** [review]

**Review by peter-mitsis — CHANGES_REQUESTED** [review]
I think this should be ok. However, there is one thing that I would like to see before giving it the final thumbs up--the initialisation of the group_id in the test code that is not group_id related.

Although `k_p4wq_work1 item` resides within is a global variable (`test_item items[]`) and will  be auto-initialized to zero when the BSS is zeroed, I would still like to see that it is explicitly assigned in the tests where it is not used. Since Zephyr tests are used as reference material for application developers, it is worthwhile to provide them examples that show all the fields getting initialized (particularly since someone, somewhere, sometime is going to allocate this item on a stack).

**Review by marcinszkudlinski — DISMISSED** [review]

**Comment by abonislawski** [comment]
@peter-mitsis  sorry, almost forgot about this :) added group_id initialization to previous tests

**Review by andyross — CHANGES_REQUESTED** [review]
Sorry, I missed this when it came by the first time.

I don't know that I like this direction.  It's sort of breaking the original metaphor.  P4WQ items are "like threads".  They schedule like threads, and preempt like threads.

But this feature doesn't work like that.  If you add a work item at priority 0 to a queue, and there is a work item of priority 1 that is already running, the old work item will be preempted by the scheduler and the new item will run immediately.  That feature won't work with "groups", because the OS scheduler doesn't understand what a group is.

There's also an orthogonality problem: Zephyr allows an arbitrary number of priorities (well, it's a byte, so 256 currently, but that can be fixed), and within those the EDF deadline acts as a 31 bit "subpriority" already.  Can't you map "groups" onto the existing mechanisms, maybe with some extra scheduling APIs in the kernel?

**Comment by aborisovich** [comment]
> But this feature doesn't work like that. If you add a work item at priority 0 to a queue, and there is a work item of priority 1 that is already running, the old work item will be preempted by the scheduler and the new item will run immediately. That feature won't work with "groups", because the OS scheduler doesn't understand what a group is.

This is exactly the point we are trying to achieve here.
The intent is to use this P4WQ using a single worker thread so items currently executed will not be preempted when new item of lower priority arrives to the queue. We need this for the new scheduler, have a look at RFC https://github.com/thesofproject/sof/issues/7238 .

**Comment by aborisovich** [comment]
@andyross so you suggest that we should implement a completely new queue to Zephyr to fulfill those requirements?

**Comment by andyross** [comment]
I'm saying that the design needs some rethought if the idea of "preemption" and "priority" in the SOF scheduler doesn't match the one in the Zephyr scheduler.  That just sounds like a mistake.  If you're trying to **prevent** the Zephyr kernel from preempting a thread, you should be using a zephyr priority to do that.

**Comment by andyross** [comment]
OK, having read through the RFC, it looks like you just want to have your "groups" be in-order things.  You want all of the first group to complete before the second group runs, etc...  The reason this collides with p4wq is that the p4wq metaphor is that all the tasks should be runnable immediately.  It doesn't understand the idea of ordering, its tasks are like threads.  You use them like threads.  Threads don't do in-order processing either.

This sounds like a job for a compound data structure.  Use something like a regular work queue (with a manager thread running at high priority of course) as your "group manager".  Each group runs in order, and the callback:

1. Adds all the parallel p4wq items for the group to the queue
2. Takes a semaphore N times, once for each item

And each p4wq "group item" callback then does its normal work, and finishes by giving the semaphore.

This should be no more than a few dozen lines of code.  And it doesn't really have to be a work queue, a manager thread of your own would be fine too.

**Comment by aborisovich** [comment]
@abonislawski Close? Looks like we need to add completely new abstraction to Zephyr.

**Comment by abonislawski** [comment]
yes we can close this one

**Pull request closed without merging**
