### PR TITLE
tests: drivers: build_all: Add a build_all test for usb

### PR DESCRIPTION
**Pull request by soburi**
The test targets the following devices at this time.

- diodes,pi3usb9201
- maxim,max3421e_spi

### CODE REVIEW

**Review by keith-zephyr — DISMISSED** [review]

**Review by cfriedt — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]
Please add an entry in MAINTAINERS.yml for this.

**Comment by soburi** [comment]
@henrikbrixandersen 

> Please add an entry in MAINTAINERS.yml for this.

I updated it. Thank you for reviewing.

**Review by keith-zephyr — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]

**Comment by tmon-nordic** [comment]
This seems to cover the host, while there already is a build_all device overlay in https://github.com/zephyrproject-rtos/zephyr/tree/1e83368d88222ae573fe5ff6ad1b7b8187cee554/tests/subsys/usb/device_next

**Review by cfriedt — APPROVED** [review]

**Comment by kartben** [comment]
ping @jfischer-no

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
