### PR TITLE
updatehub: Move from lib to subsys:mgmt folder

### PR DESCRIPTION
**Pull request by nandojve**
Zephyr introduced subsys/mgmt folder for MCU management. Move UpdateHub to this newly and dedicated space.

~It should be merged after #27269.~

CC @otavio

### CODE REVIEW

**Comment by MaureenHelm** [comment]
> It should be merged after #27269.

This is done. Please rebase

**Comment by nandojve** [comment]
Rebased, I'll keep DNM till run tests more tests with HW.

**Comment by carlescufi** [comment]
Thanks!

Can you also move the sample?
https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/updatehub

to perhaps `samples/mgmt/updatehub`?

**Comment by nandojve** [comment]
> Thanks!
> 
> Can you also move the sample?
> https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/updatehub
> 
> to perhaps `samples/mgmt/updatehub`?

Done!

**Comment by nandojve** [comment]
fix nits.

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
