### PR TITLE
drivers: counter_nrfx_*: Port driver to DTS

### PR DESCRIPTION
**Pull request by pizi-nordic**
This PR ports the counter_nrfx_rtc and counter_nrfx_timer to DTS infrastructure.
Still, work is motivated by the needs of device-level power management.

### CODE REVIEW

**Review by anangl — APPROVED** [review]

**Review by pabigot — CHANGES_REQUESTED** [review]
I think two things need to be added to the device bindings:
* Both RTC and TIMER require a property that specifies the number of capture/compare registers available on the specific peripheral instance.
* TIMER also requires a property indicating supported bit widths.  Not sure how that would best be expressed e.g. as a bit mask, an array of allowed widths, or individual boolean properties.

Both of these affect the capabilities of the specific driver instances, though they are currently retrieved through reference to HAL defines, e.g.
```
                         .max_top_value = (TIMER##idx##_MAX_SIZE == 32) ?       \
                                        0xffffffff : 0x0000ffff,               \
                        .freq = TIMER_CLOCK /                                  \
                                (1 << CONFIG_COUNTER_TIMER##idx##_PRESCALER),  \
                        .count_up = true,                                      \
                        .channels = CC_TO_ID(TIMER##idx##_CC_NUM),             \
```
so it doesn't really have to be done now.

The instance pointer should be derived from the DT node unit address rather than a HAL macro, too.

**Comment by pizi-nordic** [comment]
@pabigot: What I need currently is only DTS-based naming of the device and this is why the changes are minimal. You are right that additional properties should be introduced as well as instance address should be taken from the DTS. Unfortunately there is no driver for nrf5x peripheral which is really doing that - all the drivers are using nrfx layer which is using HAL to obtain device properties. We stared to fix this in the when we added support for the nrf9x, however the work is still not complete.

**Review by pabigot — DISMISSED** [review]

**Review by pabigot — COMMENTED** [review]
Previous requested changes are logged in #13796.

I don't feel I can really approve this as I haven't looked at it closely or tested it, but I have no objections.

**Comment by pizi-nordic** [comment]
@pabigot: Thank you.

**Review by pdunaj — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
Looks ok to me - I did a pass on the DTS changes.

**Pull request merged**
