### PR TITLE
doc: Add networking information to 2.0 release note

### PR DESCRIPTION
**Pull request by jukkar**
Contains major networking changes between 1.14 and 2.0 releases.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
@jukkar any of these enhancements that could be listed in the Major/Key enhancement section?

**Comment by jukkar** [comment]
> @jukkar any of these enhancements that could be listed in the Major/Key enhancement section?

Most probably yes, I can add some of the enhancements there too.

**Comment by jukkar** [comment]
New version adding networking major enhancements to main chapter.

**Comment by aescolar** [comment]
@ioannisg You may want to merge this ones relatively fast (with only very superficial reviews) and then polish it afterwards, otherwise there will be merge conflicts as people tries to add their parts

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg You may want to merge this ones relatively fast (with only very superficial reviews) and then polish it afterwards, otherwise there will be merge conflicts as people tries to add their parts

I would need David to review, ideally, but also some other networking person that knows the enhancements

**Review by dbkinder — APPROVED** [review]
Agree that we should merge these release notes additions and do a final review and cleanup closer to the release.  That said, I wonder if all these "add support for..." bullets can be consolidated, organized, or summarized differently (when we do the cleanup edits).

**Comment by ioannisg** [comment]
> 
> 
> Agree that we should merge these release notes additions and do a final review and cleanup closer to the release. That said, I wonder if all these "add support for..." bullets can be consolidated, organized, or summarized differently (when we do the cleanup edits).

I assume so, @dbkinder , but let @jukkar comment on that as well :)
So, then, let's merge these PRs fast and review the final release notes at the end.

**Comment by jukkar** [comment]
>  That said, I wonder if all these "add support for..." bullets can be consolidated, organized, or summarized differently (when we do the cleanup edits).

I agree, there is quite a lot of repetition of this "Add support ..." or "... fixes...". We had something like this in previous release note but it would make sense to reformat this a bit. I did not manage to do better than this atm, sorry about that.

**Pull request merged**
