### PR TITLE
soc: imxrt1064: Minor fixes with CONFIG_PM build

### PR DESCRIPTION
**Pull request by pdgendt**
This PR fixes 2 issues when building with `CONFIG_PM` on the the i.MX RT1064 SoC.

### CODE REVIEW

**Review by danieldegrasse — APPROVED** [review]

**Comment by pdgendt** [comment]
@danieldegrasse is the low-power mode tested on the mimxrt1064 evk if it works properly?

**Comment by danieldegrasse** [comment]
@pdgendt I have not tested with that setup, no. As you can see, the code will disable the video PLL when entering low power mode, but I have not verified this using a display. The code *should* simply reenable the PLL with the same configuration when exiting low power mode. Are you seeing different behavior?

My testing was done by running the `tests/subsys/pm/power_mgmt_soc` test. Regression testing was also run against this board using twister (see the initial PR: https://github.com/zephyrproject-rtos/zephyr/pull/41172#pullrequestreview-897129154)

**Review by galak — APPROVED** [review]

**Comment by danieldegrasse** [comment]
@pdgendt What is your test setup? I assume you have a display connected to the EVK, but what sample are you running and flashing?

**Comment by pdgendt** [comment]
> @pdgendt What is your test setup? I assume you have a display connected to the EVK, but what sample are you running and flashing?

@danieldegrasse it’s a custom board with custom display connected to eLCDIF

**Comment by danieldegrasse** [comment]
@pdgendt Thank you for the clarification- I think this may be enough for me to test with, but an example would also be helpful if you are willing to provide one. If the issue appears without any changes being made to the display, it is likely an issue with the low power mode code implementation. I'll try a minimal application with the display driver enabled like you described and see what occurs on the EVK.

**Comment by pdgendt** [comment]
@danieldegrasse Thanks for getting back with the results.

I can't really give a sample where the issue is reproducible, I have enabled all drivers for my custom board and tried to put it into the suspend state. This is where it goes wrong, so it can be any peripheral.

I'll get back to you once I figure it out.

**Comment by pdgendt** [comment]
@danieldegrasse I've made a minimal application, where I can go into `suspend` after a delay but it fails to wake up.
Board `defconfig`
```
CONFIG_SOC_MIMXRT1064=y
CONFIG_SOC_SERIES_IMX_RT=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_GPIO=y
CONFIG_MPU=y
CONFIG_ARM_MPU=y
CONFIG_PINCTRL=y
CONFIG_FPU=y
CONFIG_FP_HARDABI=y
CONFIG_XIP=y
```
prj.conf
```
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_IDLE_STACK_SIZE=4096
```
main.c
```c
#include <stdio.h>
#include <zephyr/zephyr.h>
#include <zephyr/device.h>
#include <zephyr/pm/policy.h>

LOG_MODULE_REGISTER(main);

static int32_t sleep_time_ms = 20000;

/* This has to be done before anything tries to sleep, which means
 * before the threading system starts up between PRE_KERNEL_2 and
 * POST_KERNEL.  Do it at the start of PRE_KERNEL_2.
 */
static int disable_suspend(const struct device *dev)
{
	ARG_UNUSED(dev);

	if (!pm_policy_state_lock_is_active(PM_STATE_SUSPEND_TO_IDLE, PM_ALL_SUBSTATES)) {
		pm_policy_state_lock_get(PM_STATE_SUSPEND_TO_IDLE, PM_ALL_SUBSTATES);
	}

	return 0;
}
static int enable_suspend(const struct device *dev)
{
	ARG_UNUSED(dev);

	if (pm_policy_state_lock_is_active(PM_STATE_SUSPEND_TO_IDLE, PM_ALL_SUBSTATES)) {
		pm_policy_state_lock_put(PM_STATE_SUSPEND_TO_IDLE, PM_ALL_SUBSTATES);
	}

	return 0;
}
SYS_INIT(disable_suspend, PRE_KERNEL_2, 0);

void main(void)
{
	while (true) {
		k_msleep(sleep_time_ms);
		printk("suspending\n");
		enable_suspend(NULL);

		k_msleep(sleep_time_ms);
		printk("wakeup\n");
		disable_suspend(NULL);
	}
}
```
Also worth noting is that I have a reduced DCD header compared to the imx rt1064 evk where all `EMC` and `SEMC` entries are removed.

It's hard to figure out, since the debugger can't be used, any suggestions on how to find the issue?
Thanks!

**Pull request merged**
