### PR TITLE
sflist: move proxy node implementation to data structure API

### PR DESCRIPTION
**Pull request by pabigot**
k_queue uses a proxy sflist node to avoid exposing kernel pointer to
user mode.  Move the data structure for this into the sflist API and
add a helper function so that the same functionality can be used by
other sflist applications.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
No objection, I assume you have uses for this in the future.

**Comment by pabigot** [comment]
Yes. `k_queue` is not ideal for managing submitted work items since its lock is not helpful given that another lock is needed to accurately track the state of the work item.  The original draft work2 implementation in #29618 used `slist`, but after reviewing what `k_submit_to_user_queue` is probably supposed to do it seems I'd need `sflist` so the work items for a queue can be managed without exposing unrelated items.  It's still not clear how userspace use of work queues/items is supposed to work, but I expect to need this proxy capability there.

**Comment by andrewboie** [comment]
> It's still not clear how userspace use of work queues/items is supposed to work, but I expect to need this proxy capability there.

I don't think it's best to expand the scope of proxy queue nodes. This got invented so the existing queue API could work with userspace in some form.
It introduces a hard dependency on runtime memory allocations. This is far from ideal for an RTOS.
Better would be to have options for what kind of data structure is used for workqueues.

**Review by andyross — COMMENTED** [review]
This isn't a big deal, really, but it seems like we're evolving in the wrong direction here.  The slist API was originally just a singly-linked list, a textbook data structure analogous to dlist with no dependence on anything else.  Then it had to grow a place to store per-node flags for the benefit of userspace queues.  Now it's absorbing more queue-specific behavior.  Is that really what we want?  What does someone who wants a singly-linked list use?

I dunno, I guess my intuition is that we probably want to move this into queue and have it do its own list management since it's so diverged from the "just a linked list" model that it started with.

And then, if (as I assume?) you have a second user that wants the proxy node ability, create a "flagged proxy list" abstraction that could be used by both queue and whatever else wants it.

But mostly I'm just wanting the "just a dumb list" data structure back.

**Comment by pabigot** [comment]
I don't see this as adding queue-specific behavior.  I see it as a way to allow incorporation of things into lists without leaking information about the list contents to userspace: the use case that motivated adding the proxy to `k_queue` originally.

It's already in `k_queue`, and I (potentially) need it in something that has different list behavior and requirements (in particular it doesn't need a lock because it's always used in contexts where another lock is held).  It only makes sense with sflist because you need to be able to tell from the node itself whether it's a "real" node or a proxy node, which requires a flag.

**Comment by pabigot** [comment]
I no longer need this feature, so we can leave it as a wart on `k_queue`.

**Pull request closed without merging**
