### PR TITLE
drivers: spi: mcux_flexcomm: fix chip select bug w/ intermediate dma …

### LINKED ISSUE #59575: drivers: spi: spi_mcux_flexcomm: transceive_dma() releases chip select in the middle of multi-buffer transfers
When more the spi_buf_set has more than one entry, the transceive_dma() will create multiple DMA transfer requests to the SPI controller. However, chip select is released after each intermediate transfer, instead of being asserted for the entire buf_set.

Reproduced on RT595 EVK and confirmed on a logic-analyzer

Chip select should be asserted for the entire transfer request, even if the request involves more than one spi_buf in the set.

This bug prevents usage of >1 in the spi_buf_set.

### PR DESCRIPTION
**Pull request by mjchen0**
…transfers

Fix for bug:
https://github.com/zephyrproject-rtos/zephyr/issues/59575

The dma version of the version of the driver can
invoke multiple intermediate dma transfers, like
when the spi_buf_set count is greater than one.
However, there is a bug where chip select is not kept asserted for all intermediate dma transfers required to process the entire spi_buf_set.

### CODE REVIEW

**Comment by decsny** [comment]
hi @mjchen0 , thank you for the pull request, do you know a good way for us to test it?

**Comment by mjchen0** [comment]
A stock RT595EVK has no SPI peripherals. We found this bug while working on a driver for an external SPI display, connected to HS_SPI1 on the JP26 connector. To reproduce the bug, just write some code that does a SPI transceive with buf_set count > 1 to HS_SPI1, and put the JP26 pins on a logic analyzer or scope. Even though buf_set count is > 1, chip select should be kept asserted for the entire transfer.

**Review by mmahadevan108 — APPROVED** [review]
Thanks for the fix

**Comment by mmahadevan108** [comment]
@mjchen0, can you please help address the Compliance check failure.

**Review by tbursztyka — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
