### PR TITLE
arch: riscv: stacktrace: allow different number of frames

### LINKED ISSUE #74713: [Coverity CID: 392520] Same on both sides in arch/riscv/core/stacktrace.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/dcf42917c550714d2457947538b9e29d083e872e/arch/riscv/core/stacktrace.c

Category: Incorrect expression
Function: `walk_stackframe`
Component: Architectures
CID: [392520](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=392520)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/dcf42917c550714d2457947538b9e29d083e872e/arch/riscv/core/stacktrace.c#L191

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=392520

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CONSTANT_EXPRESSION_RESULT). ([CWE-569](http://cwe.mitre.org/data/definitions/569.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by ycsin**
Set max frames to:
- CONFIG_EXCEPTION_STACK_TRACE_MAX_FRAMES on exception
- CONFIG_ARCH_STACKWALK_MAX_FRAMES on `arch_stack_walk()`

Fixes #74713

image

https://github.com/zephyrproject-rtos/zephyr/blob/dcf42917c550714d2457947538b9e29d083e872e/arch/riscv/core/stacktrace.c#L17-L18

An error is raised when `CONFIG_EXCEPTION_STACK_TRACE_MAX_FRAMES` equals to the `CONFIG_ARCH_STACKWALK_MAX_FRAMES` in the `MAX()` macro

### CODE REVIEW

**Comment by cfriedt** [comment]
To be honest, this sounds like more of a bug in our `MAX()` implementation. 

```cpp
#define MAX(a, b) (((a) > (b)) ? (a) : (b))
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
```

Should be
```cpp
#define MAX(a, b) (((a) >= (b)) ? (a) : (b))
#define MIN(a, b) (((a) <= (b)) ? (a) : (b))
```

in `<zephyr/sys/util.h>`

**Review by cfriedt — CHANGES_REQUESTED** [review]
Would rather see the bug fixed in `MIN()` and `MAX()`

**Comment by ycsin** [comment]
> To be honest, this sounds like more of a bug in our `MAX()` implementation.
> 
> ```c++
> #define MAX(a, b) (((a) > (b)) ? (a) : (b))
> #define MIN(a, b) (((a) < (b)) ? (a) : (b))
> ```
> 
> Should be
> 
> ```c++
> #define MAX(a, b) (((a) >= (b)) ? (a) : (b))
> #define MIN(a, b) (((a) <= (b)) ? (a) : (b))
> ```
> 
> in `<zephyr/sys/util.h>`

Wouldn't this make the error to be something like `8 >= 8 is always true...`?

**Comment by ycsin** [comment]
Closed in favor of #77067

**Pull request closed without merging**
