### PR TITLE
Bluetooth: controller: legacy: Fix Data Length Tx Rx time

### PR DESCRIPTION
**Pull request by cvinayak**
Fix Data Length Update procedure calculation of transmit
and receive time.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
With this PR all DLE plus PHY tests for controller with Coded PHY support pass.

**Review by mtpr-ot — DISMISSED** [review]
LGTM

**Comment by cvinayak** [comment]
~Testing with Controller without Coded PHY support in progress...~
Testing on nRF52_pca10040 (with no coded PHY support) too passed all DLE and PHY tests.

**Review by kruithofa — DISMISSED** [review]
LGTM

**Comment by cvinayak** [comment]
@mtpr-ot  @kruithofa Please review changes in this PR, and check if they are correctly applied to split controller.

**Comment by cvinayak** [comment]
Close and reopen to re-trigger CI.

**Comment by kruithofa** [comment]
LGTM

**Review by kruithofa — APPROVED** [review]

**Pull request merged**
