### PR TITLE
fs: fcb: Make FCB work with sectors larger than 16K

### LINKED ISSUE #45345: Make FCB work with sectors larger than 16K
**Is your enhancement proposal related to a problem? Please describe.**
FCB currently only supports sectors up to 16K.
It further does only abide to the underlying flash alignment constraints by pure chance at some places.
E.g. in `fcb_append()` the line `fcb->f_active.fe_elem_off = sizeof(struct fcb_disk_area);` will abide alignment
constraints if `sizeof(struct fcb_disk_area)` happens to be a multiple of the alignment.

Stumbled upon this while working with an STM32H7, which has 128K sectors and which has 32byte
write block size.

**Describe the solution you'd like**
I'd like to have FCB work with sectors larger than 16K and with all flash alignment constraints.

Would be closed by https://github.com/zephyrproject-rtos/zephyr/pull/45366

**Describe alternatives you've considered**
NVS, but NVS does currently also not work with the H7: https://github.com/zephyrproject-rtos/zephyr/issues/45031

### PR DESCRIPTION
**Pull request by jachatzi**
Enhance FCB to also work with sectors larger than 16K and
to handle larger flash alignment constraints correctly.

Length field of the meta data of an entry can now span
up to 4 bytes instead of 2.
Element offset and buffer sized get set at least to the
alignment value.

The test in test_fcb_len now only checks specific values
of the length field, as the test would otherwise take too
long with the increased max size.

Tested on nucleo_h743zi, native_posix and native_posix_64.

Closes: https://github.com/zephyrproject-rtos/zephyr/issues/45345

Signed-off-by: Achatzi Julian <jachatzi@baumer.com>

### CODE REVIEW

**Comment by jachatzi** [comment]
Will work on the failing test of the settings module ASAP (lots of meetings -.-)

**Comment by Laczen** [comment]
@jachatzi, is it needed to supports entries larger than 16kB? Could you split the alignment problem from the sector size problem?

**Comment by jachatzi** [comment]
> @jachatzi, is it needed to supports entries larger than 16kB? Could you split the alignment problem from the sector size problem?

Well not for me, but there is fcb_test_append_too_big which starts at the sections size and then reduces the length to the biggest one which fits into fcb with that section size. So if i got a section > 16K I also have a largest possible element to be stored in fcb which is larger than 16K. 
Of course I could also change the test to start from `FCB_MAX_LEN` instead of `fcb->f_active.fe_sector->fs_size;`.
The first got to me when the test failed, but now that you're asking I think I might have been mislead by this test -.-

So if this is better I'd could rewind the changes for allowing entries larger than 16K, such that we only have it supporting sectors larger 16K with "big" write block sizes. Whout this be ok?

**Comment by Laczen** [comment]
> So if this is better I'd could rewind the changes for allowing entries larger than 16K, such that we only have it supporting sectors larger 16K with "big" write block sizes. Would this be ok @Laczen ?

Yes, just correct the alignment problem.

**Comment by jachatzi** [comment]
@Laczen finally found time to remove the changes to allow for larger data too.

There is one thing in fcb which I'd like too fix too: in fcb.h the maximum data length is defined as: `FCB_MAX_LEN	(CHAR_MAX | CHAR_MAX << 7)`. The intended value is `0x3FFF`, as two of the 16 bits are used as meta data. Building for `native_posix` also 
gives this value. Building for `nucleo_h743zi` somewhere in the build `char`s are getting defined as unsigned. Thus, on the H7 we we get `0x7FFF` for `FCB_MAX_LEN`. So at least the check in `fcb_put_len` does check against the wrong max length.
Should I open a new issue and PR for that?

**Comment by jachatzi** [comment]
@Laczen ist this PR ok now?

**Review by Laczen — COMMENTED** [review]
@jachatzi, please remove the flash.bin file from the PR.

**Comment by Laczen** [comment]
> @Laczen finally found time to remove the changes to allow for larger data too.
> 
> There is one thing in fcb which I'd like too fix too: in fcb.h the maximum data length is defined as: `FCB_MAX_LEN (CHAR_MAX | CHAR_MAX << 7)`. The intended value is `0x3FFF`, as two of the 16 bits are used as meta data. Building for `native_posix` also gives this value. Building for `nucleo_h743zi` somewhere in the build `char`s are getting defined as unsigned. Thus, on the H7 we we get `0x7FFF` for `FCB_MAX_LEN`. So at least the check in `fcb_put_len` does check against the wrong max length. Should I open a new issue and PR for that?

I would need to recheck the code for this. A length of 16383 would be represented by a value of 0x7FFF, I am unsure if `FCB_MAX_LEN` is referring to the largest value that can be generated or the length of the entry.

**Comment by jachatzi** [comment]
> @jachatzi, please remove the flash.bin file from the PR.

Done

**Comment by jachatzi** [comment]
> > @Laczen finally found time to remove the changes to allow for larger data too.
> > There is one thing in fcb which I'd like too fix too: in fcb.h the maximum data length is defined as: `FCB_MAX_LEN (CHAR_MAX | CHAR_MAX << 7)`. The intended value is `0x3FFF`, as two of the 16 bits are used as meta data. Building for `native_posix` also gives this value. Building for `nucleo_h743zi` somewhere in the build `char`s are getting defined as unsigned. Thus, on the H7 we we get `0x7FFF` for `FCB_MAX_LEN`. So at least the check in `fcb_put_len` does check against the wrong max length. Should I open a new issue and PR for that?
> 
> I would need to recheck the code for this. A length of 16383 would be represented by a value of 0x7FFF, I am unsure if `FCB_MAX_LEN` is referring to the largest value that can be generated or the length of the entry.

Ok, I'll open a new issue regarding this in a few days. There I'll also explain why I think it's wrong with more detail, so that we can go on with this PR.

**Comment by Laczen** [comment]
@jachatzi, for me the PR is OK. I will wait for other change request to approve (because otherwise the system requires me to re-approve).

@nvlsianpu, @de-nordic, could you have a look?

**Comment by jachatzi** [comment]
> @jachatzi, for me the PR is OK. I will wait for other change request to approve (because otherwise the system requires me to re-approve).

If you mean the `FCB_MAX_LEN` topic with "other change request" I'll do this in a completely new PR as it doesn't matter for that one.

**Comment by Laczen** [comment]
> > @jachatzi, for me the PR is OK. I will wait for other change request to approve (because otherwise the system requires me to re-approve).
> 
> If you mean the `FCB_MAX_LEN` topic with "other change request" I'll do this in a completely new PR as it doesn't matter for that one.

No, this is not what I meant, every time a push is made (after a change request), a new approve is required.

But keep the FCB_MAX_LEN change indeed for a different PR. If I remember correctly the representation on flash is a "variable length integer", where the first bit of a char is an indication that there is more data. We can discuss this in a separate PR.

**Review by de-nordic — APPROVED** [review]
Looks OK

**Review by Laczen — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Comment by jachatzi** [comment]
@Laczen Who is going to merge this? Sorry for the maybe dumb question, it's my first PR here :)

**Pull request merged**
