### PR TITLE
samples: dfu: enable outputing hex file

### PR DESCRIPTION
**Pull request by jli157**
hex file is required by 'west sign' by default.

Signed-off-by: Jun Li <jun.r.li@intel.com>

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
I do not understand the motivation. Are not all three formats {elf, bin, hex} always generated? west sign can also deal with binary and it is not the part of build process for this sample.

**Comment by nashif** [comment]
> I do not understand the motivation. Are not all three formats {elf, bin, hex} always generated?

it is not default for all boards, it is default for nrf boards however. So depending on the board, it might not be enabled by default.

**Comment by jli157** [comment]
STM32 SoCs don't enable this option by default. How can I run `west sign` without the hex file? It seems required when running the command.

**Review by carlescufi — APPROVED** [review]

**Comment by jfischer-phytec-iot** [comment]
>STM32 SoCs don't enable this option by default. How can I run west sign without the hex file? It seems required when running the command.

No, see https://docs.zephyrproject.org/latest/guides/west/sign.html?highlight=west%20sign --bin

>Also, it should be good to use this sample to demonstrate the usages of west sign. The readme is out-of-date.

No, west is optional.

**Review by jfischer-no — APPROVED** [review]

**Comment by jli157** [comment]
> > STM32 SoCs don't enable this option by default. How can I run west sign without the hex file? It seems required when running the command.
> 
> No, see https://docs.zephyrproject.org/latest/guides/west/sign.html?highlight=west%20sign --bin
> 
> > Also, it should be good to use this sample to demonstrate the usages of west sign. The readme is out-of-date.
> 
> No, readme is no out-of-date, west is optional.



> > STM32 SoCs don't enable this option by default. How can I run west sign without the hex file? It seems required when running the command.
> 
> No, see https://docs.zephyrproject.org/latest/guides/west/sign.html?highlight=west%20sign --bin
> 
> > Also, it should be good to use this sample to demonstrate the usages of west sign. The readme is out-of-date.
> 
> No, readme is no out-of-date, west is optional.

I always get errors when run with the option `--bin` 
```
$ west sign -t imagetool --bin -- --key /home/projects/pub_zephyr/mcuboot/root-rsa-2048.pem 
usage: west sign [-h] [-d BUILD_DIR] [-f] -t {imgtool} [-p TOOL_PATH] [--bin]
                 [-B BIN] [--hex] [-H HEX]
                 [tool_opt [tool_opt ...]]
west sign: error: argument -t/--tool: invalid choice: 'imagetool' (choose from 'imgtool')

```
And this way is also not correct: 
```
$ west sign -t imagetool --bin build/zephyr/zephyr.bin -- --key /home/projects/pub_zephyr/mcuboot/root-rsa-2048.pem 
usage: west sign [-h] [-d BUILD_DIR] [-f] -t {imgtool} [-p TOOL_PATH] [--bin]
                 [-B BIN] [--hex] [-H HEX]
                 [tool_opt [tool_opt ...]]
west sign: error: argument -t/--tool: invalid choice: 'imagetool' (choose from 'imgtool')

```

**Comment by jli157** [comment]
> > STM32 SoCs don't enable this option by default. How can I run west sign without the hex file? It seems required when running the command.
> 
> No, see https://docs.zephyrproject.org/latest/guides/west/sign.html?highlight=west%20sign --bin
> 
> > Also, it should be good to use this sample to demonstrate the usages of west sign. The readme is out-of-date.
> 
> No, readme is no out-of-date, west is optional.

`west sign -t imgtool --bin -- --key /home/projects/pub_zephyr/mcuboot/root-rsa-2048.pem` works without the hex output enabled.  Thank you! 

I guess I can just give up and close this PR?

**Comment by nashif** [comment]
> I guess I can just give up and close this PR?

yeah, especially that it only touches a sample, you probably need generated hex everywhere, not only this sample.

closing for you :)

**Comment by jli157** [comment]
@jfischer-phytec-iot the `west sign` command with the option `--bin` can generate `zephyr.signed.bin` for sure. But the command still reports errors complaining it can't find `zephyr.hex` file to generate the signed hex version. Sounds like an issue? 

```
$ west sign -t imgtool --bin -- --key /home/projects/pub_zephyr/mcuboot/root-rsa-2048.pem
Traceback (most recent call last):
  File "/home/uwb/.local/bin/imgtool", line 10, in <module>
    sys.exit(imgtool())
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/imgtool/main.py", line 154, in sign
    img.load(infile)
  File "/home/.local/lib/python3.6/site-packages/imgtool/image.py", line 122, in load
    ih = IntelHex(path)
  File "/home/.local/lib/python3.6/site-packages/intelhex/__init__.py", line 90, in __init__
    self.loadhex(source)
  File "/home/.local/lib/python3.6/site-packages/intelhex/__init__.py", line 199, in loadhex
    fobj = open(fobj, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/projects/pub_zephyr/zephyr/samples/subsys/usb/dfu/build/zephyr/zephyr.hex'
```

**Comment by jfischer-phytec-iot** [comment]
@jli157 I can confirm that it does not work without a hex file. For me (build for the reel board, cmake -DBOARD=reel_board ../) `west sign -t imgtool --tool-path ~/src/mcuboot/scripts/imgtool.py --bin -- --key ~/src/mcuboot/root-rsa-2048.pem  --header-size 0x200 --align 8 --version 1.2 --slot-size 0x67000` generates both files zephyr.signed.hex and zephyr.signed.bin. And _west sign_ will fail if I disable the output of hex files.

I guess the correct option is **--no-hex**, see _scripts/west_commands/sign.py_
`west sign -t imgtool --tool-path ~/src/mcuboot/scripts/imgtool.py --no-hex -- --key ~/src/mcuboot/root-rsa-2048.pem  --header-size 0x200 --align 8 --version 1.2 --slot-size 0x67000`
At least it works for me. Sorry for trouble.

**Comment by jli157** [comment]
> @jli157 I can confirm that it does not work without a hex file. For me (build for the reel board, cmake -DBOARD=reel_board ../) `west sign -t imgtool --tool-path ~/src/mcuboot/scripts/imgtool.py --bin -- --key ~/src/mcuboot/root-rsa-2048.pem --header-size 0x200 --align 8 --version 1.2 --slot-size 0x67000` generates both files zephyr.signed.hex and zephyr.signed.bin. And _west sign_ will fail if I disable the output of hex files.
> 
> I guess the correct option is **--no-hex**, see _scripts/west_commands/sign.py_
> `west sign -t imgtool --tool-path ~/src/mcuboot/scripts/imgtool.py --no-hex -- --key ~/src/mcuboot/root-rsa-2048.pem --header-size 0x200 --align 8 --version 1.2 --slot-size 0x67000`
> At least it works for me. Sorry for trouble.

Good to know. Anyway, I've submitted a PR #16022 to generate hex file for boards I'm using.

**Pull request closed without merging**
