### PR TITLE
boards: arm: particle_*: remove SPI default enablement

### PR DESCRIPTION
**Pull request by mike-scott**
The nRF52840-based Particle.io boards have an external flash
module that is connected via SPI interface.  Originally,
the goal was to place the flash part into deep power down
mode and save 9 uA in sleep mode, but this was never
implemented in a board initialization file.

Let's remove the default y behavior for SPI as each sample
will turn it on if needed, and it can cause certain out of
tree samples to behave badly (where CONFIG_MULTITHREADING=n).

Long term: we need a better solution for handling samples
that don't fit the requirements for certain drivers, but
for now this will clean up some board usability issues.

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
@carlescufi @galak Disabling the external flash (and SPI) when compiling MCUboot for the Particle IO boards is not the greatest solution to unblocking MCUboot use.  In theory, the external flash could be used for storing image data, etc.  But, I don't think MCUboot support's external flash yet, though.

Hopefully, this solution is "good enough" for now to unblock use of MCUboot on these boards.

**Review by pabigot — APPROVED** [review]
Seems OK for 1.14, but as you suggest there really ought to be a better way.  Also seems odd if SPI requires multithreading but I2C doesn't.

**Review by carlescufi — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
I do not like this change, we are creating a precedent here and we might end up having loads of conditionals on different drivers and IOs just because mcuboot has multithreading=n by default. Either add overlays in mcuboot overriding this or do not disable multithreading by default in mcuboot and make it a space saving option, not a default.

**Comment by mike-scott** [comment]
@nashif I know you like to throw MCUboot under the bus, but this isn't actually specific to MCUboot.  This isn't specific to SPI not working when MULTITHREADING=n.

We can overlay MCUboot all we want, but if someone compiles Zephyr with MULTITHREADING=n, then these boards won't boot.

**Comment by nashif** [comment]
> I know you like to throw MCUboot under the bus

your commit message start with "MCUBoot", not throwing anyone under the bus :)

So should we go and start adding conditionals for everything in Zephyr that uses semaphores?

**Comment by mike-scott** [comment]
@nashif Most boards don't enable SPI by default (8 total).  They leave the samples to do that.  I'm guessing here, (and @pabigot can correct me if I'm wrong) but the intent was to enable the external flash transparently for samples to use much in the same way we do the internal flash.  As far as I can tell, that intent isn't realized.

So there's an argument that we shouldn't be enabling SPI by default at all here.

**Comment by mike-scott** [comment]
> So should we go and start adding conditionals for everything in Zephyr that uses semaphores?

If by *everything* you mean:
"Should we add conditionals where the board default enables a piece of hardware like SPI for a driver that isn't usable under certain circumstances?"
Then yes.

TBH, this is a fairly small set of boards and getting smaller as the default enable behavior is shrinking.

**Comment by andrewboie** [comment]
Forgive me if this is a dumb idea or has already been considered.

But it seems we keep tripping over the use of semaphores in drivers when multithreading is disabled.

Would it be possible to implement an alternate semaphore convention for this configuration, where thread-to-thread semaphore contention is nonexistent, and the only case we consider is where a thread sleeps on a semaphore that will eventually be given by an ISR or something?

**Comment by mike-scott** [comment]
@andrewboie @andyross had a great write up in some PR where he broke down the 3 use-cases we have for semaphores across the Zephyr code-base.

He went on to explain that we would probably need to convert a portion of the semaphore uses to a new primitive, so that we could easily distinguish which would and wouldn't have problems in !MULTITHREADING use-case.

Of course, I could be remembering this inaccurately.

**Comment by andyross** [comment]
(I wish I could find that too, btw.)

Yeah, the idea was that some drivers use a semaphore just to allow a thread to wait for something.  But with no threads to switch to, wait just degrades to a spin loop waiting for an ISR to signal completion.

And of course some drivers are just using the semaphore to serialize thread mode access to the API, but that's just a noop with one thread.

I think there might have been another case identified too, but the basic idea is that we could have a set of one-thread-friendly "IPC" primitives that drivers that cared about CONFIG_MULTITHREADING could use instead of the standard tools.

That said, as @nashif points out, CONFIG_MULTITHREADING saves all of like 2kb of code right now, and even with extra tuning to remove bits of the scheduler and timer subsystems that snuck back in since it was introduced, it's not ever going to save more than 3-4kb.

**Comment by pabigot** [comment]
> I'm guessing here, (and @pabigot can correct me if I'm wrong) but the intent was to enable the external flash transparently for samples to use much in the same way we do the internal flash. As far as I can tell, that intent isn't realized.

Actually the primary driver was to support a board initialize routine to put the MX25L32 into deep power down mode and save 9 uA in sleep mode, but I ran out of time to spend on Zephyr before I could get that merged.  But full support for the external flash would have followed.  I have hopes of getting back to Zephyr in a couple weeks after I get some other work to a releasable state.

**Comment by mike-scott** [comment]
@andyross @nashif I hear the size argument quite a lot lately (that 3-4k doesn't matter), consider an mcuboot example for HW with 256k of flash:
```
16k for bootloader
96k slots (0,1)
32k scratch
16k storage
```

3-4k for the bootloader is **huge** for code that can't be removed any other way.

It isn't until you expand the bootloader to 32k+ that 3-4k bloat is only an inconvenience.  Could the above example do that?  Who knows.. maybe in a production scenario where scratch could be smaller.  96k sample size is already very small, and it would depend on storage needs.

**Comment by nashif** [comment]
> 3-4k for the bootloader is **huge** for code that can't be removed any other way.

it is and I do not think anybody is arguing with that. 

However, the approach of making things depend on multi-threading being enabled or not is not the right solution IMO. you could start by removing SPI from _defconfig and enabling/disabling it in the application and based on your needs, not sure why we have to make this depend on multithreading and it seems very odd.

Back to the size discussion, what numbers are you getting now with this board and what are your targets?

We something as specific as the bootloader we do need to accept that custom configurations will be required when building mcuboot. It seems to me like we are trying to have every board supported with default mcuboot configuration and instead of doing this in mcuboot we are changing Zephyr and board configurations in Zephyr which is mostly focused on the application side.

And it is quite surprising to see the mcuboot configuration disabling `CONFIG_MULTITHREADING=n` and yet having `CONFIG_DEBUG=y`, `CONFIG_LOG=y` with many modules enabled by default, `CONFIG_BOOT_BANNER=y` and other options that might help reduce the size if disabled.

The discussion here is, do we really want to make drivers mcuboot/single-thread aware, and how do we want to do that. I do no think the answer is making drivers depend on MULTITHREADING.

**Comment by pabigot** [comment]
If all we need to do is make MCUBoot work on Particle boards then remove the default-enable of SPI from them, and I regret enabling it in the first place.  The boards are new and if somebody wants to use the flash they can enable the driver in their application.

The bigger concern from my perspective is that some driver implementations require features (e.g. `MULTITHREADING`), but Zephyr apparently does not produce a build failure when those requirements aren't satisfied.

I completely agree the answer is not to make default-enable of generic drivers in each board depend on the specific configuration features the driver implementation requires on that platform.  Nor is it to make MCUBoot know it has to disable certain drivers on certain boards.  It should be to make the platform driver implementations fail to build when their configuration requirements aren't satisfied, so failures aren't deferred to runtime crashes and we would have discovered this problem long ago.

How that's done should be another issue as it goes across the entire project.

**Comment by andyross** [comment]
For clarity: the benefit to disabling multithreading right now is 1.5-2k of code size.  The 3-4k number represents my guess of a maximal effectiveness if someone goes in and works to remove the bits I can see still being included in the link.

**Comment by mike-scott** [comment]
I'm going to re-stage this PR per @pabigot comments with the default SPI enablement removed.

However, we should really start a new issue to track how we are going to deal with the drivers vs. MULTITHREADING.  We've had a lot of discussion on the subject that keeps "going away".

**Review by pabigot — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
