### PR TITLE
net: lwm2m: correct lwm2m discover operation behavior

### LINKED ISSUE #4941: LwM2M: support discovery other than '/'
Current implementation ignores the "path" given by the caller and always return all the resources device possessed by the device.

Tested  with
1. commit 697e30459d1b559bf21ef25efd68720504a26a8e
1. wakaama lwm2m server
    - use command **disc** <client_id> <path>

Resources associated w/ the path is expected instead and to follow [LwM2M specification](http://www.openmobilealliance.org/release/LightweightM2M/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf) 5.4.2

### PR DESCRIPTION
**Pull request by rbtchc**
According to LwM2M specification 20170208-A, there are two different
discover interfaces supported by the device.
1.  Bootstrap discover (sec 5.2.7.3) (To be implemented)
1.  Device management discover interface (Sec 5.4.2)
     - object ID is required (i.e. root directory discover is not allowed)
     - attributes should be responded accordingly when implemented
 
This patch corrects the behavior according to the spec and summarized as follow
1. Modify ".well-known/core" to report only the first level of the resource directory.
    e.g. `</0>,</1>,</3>,</3303>,</6>,</.well-known/core>`
1.  Respond to caller only when object ID is provided unless it's bootstrap discover

Fixes #4941

### CODE REVIEW

**Comment by mike-scott** [comment]
Hi Robert,

You are correct that the LwM2M specification does not mention .well-known/core support.  But I'd like to keep this functionality to preserve generic CoAP client testing.

Also, IIRC Leshan HTTP ReST client API "discover" operation does not supply an object id by default.

So I would like to preserve that functionality.

**Comment by rbtchc** [comment]
@mike-scott 
I'm also hesitated to remove .well-known/core at first.
My understanding is that the device doesn't accept requests from any address other than the server.
So I'm not sure that we can still issue a resource discovery from a CoAP client.

To the Leshan HTTP REST client API, may I ask is there any document describes how to use it to do the discover operation? I could update the patch and test it before I submit again.
I was using wakaama to issue the discover op to the client.
Its CLI is actually disallowed us to do the "/" discovery (and matched lwm2m specification)

**Comment by rbtchc** [comment]
Just check on Leshan server REST API.
You can issue discover op on any given object/object instance/resource except the root directory.

Here's how.
<pre>
http://<leshan server ip>:<leshan web port>/api/clients/<device name>/<obj>/discover
</pre>
Appending "discover" at the end of URI will instruct leshan server to issue a discover to the device.
When "discover" is missing, the response is actually coming from the resource directory and that was reported by lwm2m device at the registration time. No discover op is issued.

Also, leshan client does not respond to root directory discover as well.
However, it does respond to the .well-known/core. But I strongly believe that's because it's starting w/ a CoAP server.

**Comment by mike-scott** [comment]
Can we keep .well-known/core but deny discover on root?

**Comment by rbtchc** [comment]
@mike-scott 
Yes, I will modify ".well-known/core" discover handler to respond with only the first level of resources such as objects and .well-known-core (referencing Leshan client)

`</0>,</1>,</3>,</3303>,</6>,</.well-known/core>`

**Comment by rbtchc** [comment]
Changes
1. Add .well-known/core back at ddc1848de0bae836b8f16fdbb1a94ce0abed5968
1. Rebase to latest master commit

**Comment by rbtchc** [comment]
rebase on top of master branch. add e62ee5cddc55f834608e6d87a7530b5f36643be4 to remove checking input format for discover op.

**Review by mike-scott — CHANGES_REQUESTED** [review]
I'd like to see the middle 2 commits squashed please.

**Comment by rbtchc** [comment]
Updated w/ no code changes. Squash middle two commits into one and update description accordingly.

**Comment by rbtchc** [comment]
Update to separate well-known/core discover from lwm2m discover to handle corner cases.
Diff: https://hastebin.com/xukiqewihu.cs

**Comment by rbtchc** [comment]
Node code change, add more comment : https://hastebin.com/otawuloqor.cpp

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by mike-scott** [comment]
I think we missed the v1.10 cut off for this one.  We can work out a merge order for v1.11 once that window opens.

**Comment by mike-scott** [comment]
Adding @jukkar and @nashif

**Pull request merged**
