### PR TITLE
doc: genrest: Optionally use separate index page for all symbols

### PR DESCRIPTION
**Pull request by ulfalizer**
Add an option --separate-all-index that makes genrest.py generate a
separate index-all.rst index page that lists all symbols, instead of
listing all symbols in index.rst. index-all.rst is linked from
index.rst.

This was motivated by an external project where index.rst becomes the
top-level page, which runs into a Sphinx bottleneck with
sphinx_rtd_theme. See https://github.com/sphinx-doc/sphinx/issues/6909.

Also unclutter the generated documentation a bit by removing some
headings. This makes the navigation menu on the left nicer too.

Piggyback making genrest.py executable, which is handy when running it
manually.

### CODE REVIEW

**Comment by ulfalizer** [comment]
Screenshot with `--separate-all-index` (though it's not passed in Zephyr):

Skärmbild från 2019-12-10 15-40-03

**Comment by ulfalizer** [comment]
Unrelated failure, in case it's persistent:

```
zephyr/CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj -L"/opt/sdk/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/thumb/v6-m/nofp" -L/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/bbc_microbit/tests/bluetooth/mesh/bluetooth.mesh.main.microbit/zephyr -lgcc -Wl,--print-memory-usage -mthumb -mcpu=cortex-m0 -Wl,--gc-sections -Wl,--build-id=none -Wl,--sort-common=descending -Wl,--sort-section=alignment -u_OffsetAbsSyms -u_ConfigAbsSyms -nostdlib -static -no-pie -Wl,-X -Wl,-N -Wl,--orphan-handling=warn -Wl,--fatal-warnings -mabi=aapcs -march=armv6s-m && :
Memory region         Used Size  Region Size  %age Used
           FLASH:       94217 B       256 KB     35.94%
            SRAM:       17672 B        16 KB    107.86%
        IDT_LIST:         120 B         2 KB      5.86/opt/sdk/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: zephyr/zephyr_prebuilt.elf section `datas' will not fit in region `SRAM'
/opt/sdk/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: section .intList VMA [0000000020004000,0000000020004077] overlaps section datas VMA [0000000020003d00,000000002000437b]
/opt/sdk/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: region `SRAM' overflowed by 1288 bytes
collect2: error: ld returned 1 exit status
%
ninja: build stopped: subcommand failed.
```

**Review by dbkinder — APPROVED** [review]
I'm fine with a separate "all symbols" page for the Zephyr docs, particularly as you've pictured, and stop putting all the symbols on the main page.

**Comment by ulfalizer** [comment]
> I'm fine with a separate "all symbols" page for the Zephyr docs, particularly as you've pictured, and stop putting all the symbols on the main page.

Updated `CMakeLists.txt` to use the new option in Zephyr too. Agree that it turned out pretty nicec after removing the headings, as suggested by @ru-fu.

**Review by ru-fu — APPROVED** [review]
The output looks good. I didn't review the code though. ;)

**Pull request merged**
