### PR TITLE
Bluetooth: l2cap: plug l2cap metadata leak

### PR DESCRIPTION
**Pull request by jori-nordic**
Releases the metadata cells when releasing the buffers associated with a l2cap channel upon channel destroy.

If a disconnect happens at the wrong time, then it's possible that a pending TX buffer is freed by `l2cap_chan_destroy` but its metadata storage cell is not.

### CODE REVIEW

**Comment by jori-nordic** [comment]
Some more context:
This was found when developing a test for an upcoming PR.

Symptom was that the test was hanging. With the other changes removed the test hangs all the time, but we can see from  the debug logs that after a disconnect, and after the channels are destroyed, there are still metadata cells that remain allocated.

https://github.com/jori-nordic/zephyr/tree/7568f6db62fca6fc6f4c9d767dd6a0cbdc28af1e/./

Excerpts from the debug logs, right after starting iteration 2.
Running without the fix
```
d_00: @00:00:07.785737   [00255123] <wrn> main: Sync point: Connected
d_00: @00:00:07.835541   [00256755] <inf> bt_conn: allocated bufs: 0
d_00: @00:00:07.835541   [00256755] <inf> bt_l2cap: alloc l2cap meta (in-use 2)
```

And with the fix
```
d_00: @00:00:07.785737   [00255123] <wrn> main: Sync point: Connected
d_00: @00:00:07.835541   [00256755] <inf> bt_conn: allocated bufs: 0
d_00: @00:00:07.835541   [00256755] <inf> bt_l2cap: alloc l2cap meta (in-use 0)
```

**Comment by Thalley** [comment]
Ping @Tronil

**Comment by larsgk** [comment]
Hi @jori-nordic - did you see https://github.com/zephyrproject-rtos/zephyr/pull/65678 ?

**Comment by jori-nordic** [comment]
Ah shoot, I thought @Tronil 's PR already got in.
Yeah it's fixing the same stuff.

**Comment by larsgk** [comment]
> Ah shoot, I thought @Tronil 's PR already got in. Yeah it's fixing the same stuff.

I think it's just waiting for someone to merge.  Hopefully soon ;)

**Comment by jori-nordic** [comment]
Closing as dupe of #65678 

At least now [we have a test](https://github.com/zephyrproject-rtos/zephyr/pull/65678#issuecomment-1825329111)

**Pull request closed without merging**
