### PR TITLE
arch: arm: mpu: get REGION_SIZE_<X> defines directly from ARM CMSIS

### PR DESCRIPTION
**Pull request by ioannisg**
This commit re-defines the REGION_SIZE_<x> macros, present in
include/arch/arm/cortex_m/mpu/arm_mpu_v7m.h, with the help of
the existing ARM MPU regions size definitions in ARM CMSIS.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
By the way, there seems to be no code-ownership for the recently introduced file: include/arch/arm/cortex_m/mpu/arm_mpu_v7m.h

**Review by galak — COMMENTED** [review]
I wondering if we should just have a CMSIS define header for beetle.

**Comment by galak** [comment]
Take a look at #8765

**Review by galak — COMMENTED** [review]
Looks good, will let you rebase / fixup now that beetle uses CMSIS.

**Comment by ioannisg** [comment]
Re-based.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
