### PR TITLE
boards: arm: Standardise naming of NS boards

### LINKED ISSUE #36270: TF-M: introduce uniformity in Non-Secure target names
**Is your enhancement proposal related to a problem? Please describe.**
Currently, the names we choose for the non-secure version of TrustZone-enabled platforms have different suffix versions:
All `_ns`, `ns`, `_nonsecure` are used. This affects board names as well as KConfig options for SoC, Board, and .DTS file names.

**Describe the solution you'd like**
Ideally, we should pick one option to use in Zephyr and force this as a convention.

We should probably do this for the LTS2.

### PR DESCRIPTION
**Pull request by microbuilder**
This PR renames all non-secure board targets to make use of a standard `_ns` suffix.

Boards Concerned:

- `bl5340_dvk` (`bl5340_dvk_cpuappns` -> `bl5340_dvk_cpuapp_ns`)
- `lpcxpresso55s69` (`lpcxpresso55s69_ns` already good)
- `mps2_an521` (`mps2_an521_nonsecure` -> `mps2_an521_ns`)
- `musca_b1` (`v2m_musca_b1_nonsecure` -> `v2m_musca_b1_ns`)
- `musca_s1` (`v2m_musca_s1_nonsecure` -> `v2m_musca_s1_ns`)
- `nrf5340dk_nrf5340` (`nrf5340dk_nrf5340_cpuappns` -> `nrf5340dk_nrf5340_cpuapp_ns`)
- `nrf9160dk_nrf9160` (`nrf9160dk_nrf9160ns` -> `nrf9160dk_nrf9160_ns`)
- `nucleo_l552ze_q` (`nucleo_l552ze_q_ns` already good)
- `stm32l562e_dk` (`stm32l562e_dk_ns` already good)

Resolves #36270

 Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>

### CODE REVIEW

**Review by gmarull — COMMENTED** [review]
It would probably be good to document this convention (maybe in https://docs.zephyrproject.org/latest/guides/porting/board_porting.html ?)

**Comment by microbuilder** [comment]
> It would probably be good to document this convention (maybe in https://docs.zephyrproject.org/latest/guides/porting/board_porting.html ?)

Good idea. Writing some proper TF-M documentation is on the ToDo list for 2.7.0 (https://github.com/zephyrproject-rtos/zephyr/issues/36294), and I'll add a note on naming conventions in an upcoming documentation PR.

**Review by gmarull — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by ioannisg** [comment]
We need to document somewhere that this is an established convention, now.

**Comment by microbuilder** [comment]
> We need to document somewhere that this is an established convention, now.

I'm planning on putting a documentation PR together this week, and I'll include this.

**Comment by mbolivar-nordic** [comment]
Too late now, but it would have been nice to add entries to boards/deprecated.cmake for these.

**Comment by mbolivar-nordic** [comment]
This also missed some renames required in modules. At least mcuboot/boot/zephyr/Kconfig is stale now:

https://github.com/zephyrproject-rtos/mcuboot/blob/7a5196820ba48a6ad7e7d573c9048c021960677c/boot/zephyr/Kconfig#L522

@microbuilder @ioannisg was this just an oversight?

**Comment by ioannisg** [comment]
> This also missed some renames required in modules. At least mcuboot/boot/zephyr/Kconfig is stale now:
> 
> https://github.com/zephyrproject-rtos/mcuboot/blob/7a5196820ba48a6ad7e7d573c9048c021960677c/boot/zephyr/Kconfig#L522
> 
> @microbuilder @ioannisg was this just an oversight?

Yeap, probably forgotten.

**Comment by ioannisg** [comment]
> Too late now, but it would have been nice to add entries to boards/deprecated.cmake for these.

We can still do that, right?

**Comment by mbolivar-nordic** [comment]
> > @microbuilder @ioannisg was this just an oversight?
> 
> Yeap, probably forgotten.

OK, I sent a fix: https://github.com/mcu-tools/mcuboot/pull/1082

**Comment by mbolivar-nordic** [comment]
> > Too late now, but it would have been nice to add entries to boards/deprecated.cmake for these.
> 
> We can still do that, right?

"Too late not to have started causing problems for out of tree users"; I should have said :).

I sent a fix: https://github.com/zephyrproject-rtos/zephyr/pull/37290

**Comment by mbolivar-nordic** [comment]
> This PR renames all non-secure board targets to make use of a standard `_ns` suffix.

Looks like some boards were not handled in this PR that should have been.

```
$ west boards -n ns$ | grep -v _ns$
circuitdojo_feather_nrf9160ns
nrf9160_innblue21ns
nrf9160_innblue22ns
sparkfun_thing_plus_nrf9160ns
thingy53_nrf5340_cpuappns
```

**Pull request merged**
