### PR TITLE
libc: Fix fwrite function name

### LINKED ISSUE #14275: [ci.foundries.io] regression 4344e27 all: Update reserved function names
**Describe the bug**
Since the merge of 4344e27 all ARM based builds in sanitycheck have been failing the "tests/benchmarks/app_kernel/benchmark.application" test:

https://ci.foundries.io/projects/zephyr/builds/5287

The build break as can be sane for [blenano2](https://ci.foundries.io/projects/zephyr/builds/5287/sanity-compile-nrf52/artifacts/console.log) is:
~~~
[ 96%] Linking C executable zephyr_prebuilt.elf
cd /tmp/outdir/nrf52_blenano2/tests/benchmarks/app_kernel/benchmark.application/zephyr && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/zephyr_prebuilt.dir/link.txt --verbose=1
ccache /opt/toolchains/zephyr-sdk-0.9.5/sysroots/x86_64-pokysdk-linux/usr/bin/arm-zephyr-eabi/arm-zephyr-eabi-gcc    CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj  -o zephyr_prebuilt.elf -T linker.cmd -Wl,-Map=/tmp/outdir/nrf52_blenano2/tests/benchmarks/app_kernel/benchmark.application/zephyr/zephyr.map -u_OffsetAbsSyms -u_ConfigAbsSyms -Wl,--whole-archive ../app/libapp.a libzephyr.a arch/arch/arm/core/libarch__arm__core.a arch/arch/arm/core/cortex_m/libarch__arm__core__cortex_m.a arch/arch/arm/core/cortex_m/mpu/libarch__arm__core__cortex_m__mpu.a lib/libc/minimal/liblib__libc__minimal.a drivers/serial/libdrivers__serial.a -Wl,--no-whole-archive kernel/libkernel.a CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj -L"/opt/toolchains/zephyr-sdk-0.9.5/sysroots/armv5-zephyr-eabi/usr/lib/arm-zephyr-eabi/6.2.0/armv7e-m" -L/tmp/outdir/nrf52_blenano2/tests/benchmarks/app_kernel/benchmark.application/zephyr -lgcc -Wl,--print-memory-usage -mthumb -nostdlib -static -no-pie -Wl,--fatal-warnings -Wl,-X -Wl,-N -Wl,--gc-sections -Wl,--build-id=none -Wl,--orphan-handling=warn -mabi=aapcs 
Memory region         Used Size  Region Size  %age Used
           FLASH:       26496 B       512 KB      5.05%
            SRAM:       22732 B        64 KB     34.69%
        IDT_LIST:          40 B         2 KB      1.95lib/libc/minimal/liblib__libc__minimal.a(stdout_console.c.obj): In function `z_zephyr_fwrite':
/tmp/outdir/nrf52_blenano2/tests/benchmarks/app_kernel/benchmark.application/zephyr/include/generated/syscalls/libc-hooks.h:19: undefined reference to `z_impl_z_zephyr_fwrite'
~~~

### PR DESCRIPTION
**Pull request by galak**
Commit 4344e27c267e1139c26dbd9cafcca4b3069ea821 changed the reserved
function names, but got the naming wrong for fwrite.  Change fwrite to
match fputc naming and fixes build issues.

Fixes #14275

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@doanac should fix the issue.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
I'm not sure I completely understand this patch.

Wouldn't the correct fix be to fix the name of the implementation function:
`z_impl__zephyr_fwrite`

to `z_impl_z_zephyr_fwrite`?

Andrew

**Comment by galak** [comment]
> I'm not sure I completely understand this patch.
> 
> Wouldn't the correct fix be to fix the name of the implementation function:
> `z_impl__zephyr_fwrite`
> 
> to `z_impl_z_zephyr_fwrite`?
> 
> Andrew

I changed it so the style matched what we had (and works) for fputc.

**Review by tyrantlizard77 — APPROVED** [review]
I see, there was an inconsistency on how the patch refactored the syscalls.
Fine with letting this in for now since the relevant code needs attention anyway.

**Comment by pfl** [comment]
There was something fishy with some function names indeed. It somehow went south with the initial renaming attempt, and as there were a bunch of other issues needing attention, this was left in its current state. Thanks for fixing.

**Review by pfl — DISMISSED** [review]
Functions should not start with an underscore, so please consider a new name for this and the other libc functions.

**Comment by galak** [comment]
> Functions should not start with an underscore, so please consider a new name for this and the other libc functions.

The functions don't start with an underscore when actually built.

**Comment by pfl** [comment]
> > Functions should not start with an underscore, so please consider a new name for this and the other libc functions.
> 
> The functions don't start with an underscore when actually built.

Your change means _zephyr_fwrite is being used by something else, and that was missed in the renaming patch. I can see z_impl__zephyr_fwrite in libc/minimal stdout_console.c, could that be fixed up instead? In the end we need to comply with MISRA C rules all over the code base, so now would be the chance of polishing also this occurrence.

**Pull request merged**
