### PR TITLE
boards: sam_e70_xplained: added default pin config for additional 3 qdecs

### PR DESCRIPTION
**Pull request by tswaehn**
this is relates to [issue #65610](https://github.com/zephyrproject-rtos/zephyr/issues/65610)

### CODE REVIEW

**Review by nandojve — CHANGES_REQUESTED** [review]
Changes seems Ok,

You need to follow Zephyr coding procedures in regards to commit messages, see [commit message guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines)

For instance:

```
boards: arm: sam_e70_xplained: Add missing qdec

The sam_e70_xplained dts provides the configuration for qdec0, 1x
qdec at TC0. However it is missing the entries for the qdec1-qdec3.
This added the missing configurations.

Fixes #65610

Signed-off-by: Sven Ginka <sven.ginka@gmail.com>
```

**Comment by nandojve** [comment]
ping

**Comment by tswaehn** [comment]
allright. commit messages should be ok now.

**Comment by nandojve** [comment]
Please, add this as a second commit at #68189

**Pull request closed without merging**
