### PR TITLE
MAINTAINERS: Add myself to mcu manager as collaborator

### PR DESCRIPTION
**Pull request by nordicjm**
Signed-off-by: Jamie McCrae <jamie.mccrae@lairdconnect.com>

### CODE REVIEW

**Review by MaureenHelm — APPROVED** [review]

**Comment by de-nordic** [comment]
@lairdjm Why? You have not yet contributed anything to the mcumgr subsystem. You have logged some issues but no proposed fixes.

**Comment by lairdjm** [comment]
@de-nordic I have a number of changes to propose and submit PR's for once mcumgr is forked for zephyr

**Comment by de-nordic** [comment]
> 
> 
> @de-nordic I have a number of changes to propose and submit PR's for once mcumgr is forked for zephyr

That does not require being collaborator.

**Review by nashif — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> > @de-nordic I have a number of changes to propose and submit PR's for once mcumgr is forked for zephyr
> 
> That does not require being collaborator.

No, but it's great to know. Thanks @lairdjm :)

**Pull request merged**
