### PR TITLE
add an error check of flash_area_open()

### PR DESCRIPTION
**Pull request by Hxinrong**
### Contribution description
tests/subsys/settings/fcb/src/settings_test_fcb.c : add an error check of flash_area_open() in config_wipe_fcb()

### Signed-off
Signed-off-by: Xinrong Han hanxr19@mails.tsinghua.edu.cn

### Issue
Fixes parts of #30195

### CODE REVIEW

**Review by nvlsianpu — COMMENTED** [review]
looks fine, please fix the commit message.

**Comment by Hxinrong** [comment]
I have fixed the commit message. Is it not proper?

**Comment by nvlsianpu** [comment]
``` console
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

e675309c2f2ecf984b3e460d28e63b78f273aa03: author email (Han Xinrong <hanxr19@mails.tsinghua.edu.cn>) needs to match one of the signed-off-by entries.
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

1: UC5 Title exceeds max length (85>75): "tests: subsys: settings: fcb: settings_test_fcb: add error check in config_wipe_fcb()"
Error: Process completed with exit code 1.
```

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@Hxinrong You need to reduce the line length in title of the commit message for the check to pass:

```
1: UC5 Title exceeds max length (85>75): "tests: subsys: settings: fcb: settings_test_fcb: add error check in config_wipe_fcb()"
Error: Process completed with exit code 1.
```

**Comment by carlescufi** [comment]
@Hxinrong do you have plans to address the review comments? Otherwise, could someone else take over the PR?

**Pull request closed without merging**
