### PR TITLE
tests: timer_behavior: accuracy improvements

### PR DESCRIPTION
**Pull request by npitre**
Don't sample the first entry outside the timer as this is a different
code path which produces a different offset from the clock tick.

Use sys_clock_hw_cycles_per_sec() to be compatible with systems that
read their hardware clock frequency at run time.

Perform cycle difference computations with uint64_t. If ever the
magnitude of the absolute clock cycle values is greater than 52 bits
then the cast to a double will actually lose accuracy.

### CODE REVIEW

**Review by andyross — APPROVED** [review]

**Comment by teburd** [comment]
I think its ok that we are dropping the first sample here as it seems to cause problems in general. I do think it'd be good to measure single shot timer variance as another behavioral check then though. My thinking in measuring it was... the initial delay should still be within the bounds of the requested timeout, but clearly reality is there's probably more error than the periodic case due to tick alignment.

So measuring the following sort of timer with repeated samples should be done separately if we are removing the first sample from the general test case.

k_timer_start(tmer, K_USEC(1), K_NO_WAIT); 

This should, in the ideal scenario, produce a timeout in ~1us with some bounds on acceptable variance, min, max just like the jitter testing does now.

**Comment by npitre** [comment]
The first sample, when taken outside the timer IRQ path, happened farther
away from the tick transition than the other samples. This made the first
period artificially shorter and not representative of the test.

Testing only the timer start could be done reusing the same stat gathering
code. I suspect the results would be the same as this is really the
hardware's consistency being measured here.

Yet the timer_tick_train test does heavily exercize `k_timer_start()`
already. Isn't that one sufficient?

**Comment by teburd** [comment]
> The first sample, when taken outside the timer IRQ path, happened farther away from the tick transition than the other samples. This made the first period artificially shorter and not representative of the test.
> 
> Testing only the timer start could be done reusing the same stat gathering code. I suspect the results would be the same as this is really the hardware's consistency being measured here.
> 
> Yet the timer_tick_train test does heavily exercize `k_timer_start()` already. Isn't that one sufficient?

It does excercise the one shot timers but does not do the stats analysis like the jitter drift test does. :+1: from me, more of a note on maybe a future improvement here is doing stats on the one shots as well

**Review by teburd — APPROVED** [review]

**Comment by npitre** [comment]
Well OK. Should be trivial to do. In a separate PR though.

**Pull request merged**
