### PR TITLE
soc: nxp_lpc: Enable powerquad on lpc55s69

### PR DESCRIPTION
**Pull request by MaureenHelm**
Enables powerquad hardware acceleration of cmsis-dsp functions on
the lpc55s69 soc.

~~Currently this only builds with the gnuarmemb toolchain; still need to
resolve issues building the powerquad driver with the zephyr sdk.~~
Requires Zephyr SDK v0.11.3 or later to pick up a GCC fix for CRC32
intrinsics from arm_acle.h.

Tested on lpcxpresso55s69_cpu0 with tests/lib/cmsis_dsp/filtering. The
updated FIR pattern in the previous commit allows the subtest
test_arm_fir_q15 to pass by removing small block sizes not supported by
powerquad. There are also failures in correlation subtests that still
need debugging.

Other tests in tests/lib/cmsis_dsp have not been tried yet.

Temporarily points west.yml to an nxpmicro remote for cmsis and nxp_hal
repos to avoid creating extra module PRs while this zephyr PR is in
draft state.

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

### CODE REVIEW

**Comment by galak** [comment]
are the changes to the pat files expected?

**Comment by MaureenHelm** [comment]
> are the changes to the pat files expected?

Yes. That's the "updated FIR pattern" mentioned in the commit message.

@galak Could you please try building this with the zephyr sdk? There seem to be some missing toolchain defines expected by `arm_acle.h`

**Comment by stephanosio** [comment]
> are the changes to the pat files expected?

We could potentially rework the test to skip the unsupported block sizes for PowerQuad, in order to use the existing patterns. I could probably look into this next week.

**Comment by stephanosio** [comment]
> > are the changes to the pat files expected?
> 
> We could potentially rework the test to skip the unsupported block sizes for PowerQuad, in order to use the existing patterns. I could probably look into this next week.

This should allow the existing pattern to be used: https://github.com/stephanosio/zephyr/commit/87f8eadd7fcd07c155e6e4054d39323d0d0ae2a4

Branch at https://github.com/stephanosio/zephyr/tree/powerquad

**Pull request closed without merging**
