### PR TITLE
gpio: remove deprecated API functions/macros

### PR DESCRIPTION
**Pull request by mnkp**
This commit removes API functions and macros which were deprecated in 2.2 release. GPIO drivers are updated accordingly.

In case of several drivers removal of `gpio_pin_enable_callback`, `gpio_pin_disable_callback` functions required code modifications to the interrupt handler. Affected drivers shall be retested on hardware.

Affected drivers:
Driver | Eval Board | Test passed
-|-|-
gpio_cc13xx_cc26xx | cc1352r1_launchxl | gpio_api_1pin, gpio_basic_api
gpio_cc32xx | cc3220sf_launchxl | gpio_basic_api
gpio_esp32 | esp32_devkit_v4 | gpio_basic_api
gpio_gecko | efr32_radio_brd4250b | gpio_api_1pin
gpio_imx | mimxrt1060_evk | gpio_basic_api
gpio_mchp_xec | mec15xx_assy6853 | gpio_basic_api, gpio_api_1pin
gpio_mcux | frdm_k64f | gpio_basic_api
gpio_mcux_igpio | |
gpio_mcux_lpc | lpcxpresso55s69_cpu0 | gpio_basic_api
gpio_nrfx | nrf52840dk_nrf52840 | gpio_api_1pin, gpio_basic_api
gpio_rv32m1 | rv32m1_vega_ri5cy | gpio_basic_api
gpio_stm32 | nucleo_wb55rg | gpio_api_1pin
gpio_sx1509b | particle_xenon+breakout | gpio_basic_api

Other changes:
- tests/drivers/gpio/gpio_basic_api/src/test_deprecated.c removed
- removed old macros from `include/dt-bindings/gpio/gpio.h` (**this macros were not explicitly marked as deprecated**)

### CODE REVIEW

**Review by nandojve — APPROVED** [review]
For Atmel SAM/SAM0

Tested with samples/net/sockets/echo_*
Server: SAM4E_XPRO + RF2XX
Client: atsamr21_xpro

**Review by scottwcpg — APPROVED** [review]

**Comment by mnkp** [comment]
I pushed new version containing name changes suggested by @pabigot.

@pabigot do you happen to have some boards which would allow you to test some of the drivers from the "affected drivers" list? The modifications done in this PR are not dramatic, but it would be good to test it on real hardware.

**Comment by pabigot** [comment]
Yes, I think I can do these:
```
gpio_cc13xx_cc26xx	cc1352r1_launchxl
gpio_esp32	esp32
gpio_imx	mimxrt1060_evk
gpio_mcux_lpc	lpcxpresso55s69
gpio_rv32m1	rv32m1_vega_ri5cy
gpio_sx1509b    xenon+breakout
```
Will report back when I've checked them.  (PR looks fine now, holding approval until I've tested what I can.)

**Review by pabigot — APPROVED** [review]
Looks good, boards I have all pass basic (and 1pin on the ones I tried that supported it).

**Comment by dcpleung** [comment]
I tried this PR with `gpio_mchp_xec` on `mec15xx_assy6853` and both `gpio_basic_api` and `gpio_1pin_api` passed.

**Review by dcpleung — APPROVED** [review]

**Comment by mnkp** [comment]
Thanks everyone for the reviews and especially for testing on hardware!

**Pull request merged**
