### PR TITLE
tests:log_immediate: add a delay for intel_adsp

### PR DESCRIPTION
**Pull request by ghost**
For intel_adsp platforms, we may miss the early log of log_immediate,
so add a delay for those platforms.

Signed-off-by: Guo Lixin <lixinx.guo@intel.com>

### CODE REVIEW

**Review by nordic-krch — DISMISSED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
did you try running the test with CONFIG_BOOT_DELAY for this platform? Adding platform specific code in a generic tests is not a solution.

**Comment by LixinGuoX** [comment]
> did you try running the test with CONFIG_BOOT_DELAY for this platform? Adding platform specific code in a generic tests is not a solution.

Yes, we use CONFIG_BOOT_DELAY=500 in our daily testing, but for this case, we need at least 2500ms. It will be applied to all other tests and increase the total execution time.
Also this issue happens when using west build and cavstool.py to catch log, will see if there is a better way to get the missing log.

**Comment by LixinGuoX** [comment]
Hi, @edersondisouza  , I saw you changed this from 0.1 to 1 seconds to fix #44925, sleeping for 1 seconds will result in the loss of early log for log_immediate.
https://github.com/zephyrproject-rtos/zephyr/blob/d130160813fb52ee87a2d0c4a4fb8e57d466f181/soc/xtensa/intel_adsp/tools/cavstool.py#L443
I am wondering is it ok for you if we set this back? I will also check if this change would affect #44925, thanks.

**Comment by edersondisouza** [comment]
> Hi, @edersondisouza , I saw you changed this from 0.1 to 1 seconds to fix #44925, sleeping for 1 seconds will result in the loss of early log for log_immediate.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/d130160813fb52ee87a2d0c4a4fb8e57d466f181/soc/xtensa/intel_adsp/tools/cavstool.py#L472
> 
> 
> I am wondering is it ok for you if we set this back? I will also check if this change would affect #44925, thanks.

You can check it now. Unfortunately, last time I checked, this was indeed necessary =/

**Comment by edersondisouza** [comment]
@LixinGuoX did you check if reducing the sleep didn't trigger #44925? Any results?

**Comment by LixinGuoX** [comment]
#47070 fixed the problem in cavstool.py, so close this PR.

**Pull request closed without merging**
