### PR TITLE
cmake: Zephyr CMake package clean-up and minor fix

### LINKED ISSUE #27375: "west zephyr-export" dumps stack if cmake is not installed
**Describe the bug**
The `west zephyr-export` command should fail gracefully if cmake is not installed, but it does not

**To Reproduce**
1. uninstall cmake
2. make sure no cmake user package entries exist for zephyr (maybe; optional -- that's how I tested)
3. `west zephyr-export`

Output:

```
$ west zephyr-export
FATAL ERROR: CMake is not installed or cannot be found; cannot build.
Traceback (most recent call last):
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/export.py", line 59, in run_cmake_and_clean_up
    lines = run_cmake(['-S', str(path), '-B', str(path)],
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/zcmake.py", line 44, in run_cmake
    log.die('CMake is not installed or cannot be found; cannot build.')
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/log.py", line 146, in die
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbolivar/.virtualenvs/west-test/bin/west", line 8, in <module>
    sys.exit(main())
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 780, in main
    app.run(argv or sys.argv[1:])
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 339, in run_command
    self.run_extension(args.command, argv)
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/app/main.py", line 409, in run_extension
    command.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/home/mbolivar/.virtualenvs/west-test/lib/python3.8/site-packages/west/commands.py", line 116, in run
    self.do_run(args, unknown)
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/export.py", line 48, in do_run
    run_cmake_and_clean_up(share / 'zephyr-package' / 'cmake')
  File "/home/mbolivar/zephyrproject/zephyr/scripts/west_commands/export.py", line 62, in run_cmake_and_clean_up
    msg = [line for line in lines if not line.startswith('-- ')]
```

**Expected behavior**

No stack dump, just a clean error message

**Impact**

Annoyance

**Environment (please complete the following information):**

 - Commit SHA or Version used: d5e1753eb6c36421a87b535e8e6cb3a9d50e06e4

### PR DESCRIPTION
**Pull request by tejlmand**
Fixes: #27375

This is a cleanup of the Zephyr CMake package export.
The code has been simplified so that the export now happens through a CMake
script. This avoids several generated CMake build files compared to previous
export mode, and thus removes the need for a CMake pristine script.

A benefit of this cleanup is that it also fixes #27375.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
This is a bigger patch than I expected. I confirmed it did fix the bug I reported by testing it, but did not look at the code in detail.

**Comment by tejlmand** [comment]
> 
> 
> This is a bigger patch than I expected. I confirmed it did fix the bug I reported by testing it, but did not look at the code in detail.

Only because I have wanted to do this cleanup for some time now.
And the benefit of the cleanup is fixing the error at the same time, win-win.

**Comment by mbolivar-nordic** [comment]
>  And the benefit of the cleanup is fixing the error at the same time, win-win.

No objections to the patch at all, I just wanted to note that I didn't look very hard at it, mostly just tested it fixed my bug.

**Comment by tejlmand** [comment]
@nashif Comments ?

**Review by nashif — APPROVED** [review]

**Pull request merged**
