### PR TITLE
The TCP recv window is not updated after the recv_cb for the application is invoked

### PR DESCRIPTION
**Pull request by mohankumarkumar**
The TCP recv window is not updated after the recv_cb for the application
is invoked, which results in the window size becoming 0 on the Zephyr
side. This stalls the zperf tcp download performance test.

With this patch, the TCP window size is updated after the recv_cb is
invoked, which increases the window size after the application consumes
the packet.

This patch tested on Qemu and ESP32 using the following commands.

Zephyr    -> zperf tcp download 5001
Linux/mac -> iperf -l 1K -V -c 10.0.0.39 -p 5001

### CODE REVIEW

**Comment by rlubos** [comment]
Hi @mohankumarkumar, this PR is addresssing the same issue as https://github.com/zephyrproject-rtos/zephyr/pull/43379, please have a look.

I would rather avoid decreasing the window at the net_context level - merely leaving the recv_cb does not mean that the data was already consumed (and thus corresponding net_pkt's freed). For instance most commonly used socket layer will put the packet on it's own queue in the recv handler, the data is only read after `recv()` or similar is issued after such event, and that's where we decrease the window size for sockets.

**Comment by nashif** [comment]
@mohankumarkumar signed-off should be in the body of the commit message and not in the title of the PR or commit

**Comment by mohankumarkumar** [comment]
@rlubos Thanks for the pointer about [43379](https://github.com/zephyrproject-rtos/zephyr/pull/43379)! With socket APIs, I know that recv window is updated in recv(), which makes sense. With context APIs, we can update the recv window in a generic way rather than application updating it. Having said that, I understand that socket API is the preferred one for the applications, and we need to only handle context API changes in legacy application, which you are handling in 43379. I left a comment in 43379 to merge that change soon, which will unblock Zperf on mainline. Thanks again!

@nashif Thanks! I will follow that from next commit.

**Comment by mohankumarkumar** [comment]
This is handled in [43379](https://github.com/zephyrproject-rtos/zephyr/pull/43379).

**Pull request closed without merging**
