### PR TITLE
samples:net:wifi:boards: rdrw612bga: Modify CONFIG_POSIX_MAX_FDS config.

### PR DESCRIPTION
**Pull request by Liam-qk**
[Reproduce issue]
    1. Connect In-STA to Ex-AP
       wifi connect WiFi_STA_HE_1.1.8 1234567890 3 2 2

    2. Start APUT with ACS using below commands
       wifi ap enable nxp-AP 161 1234567890 3

    3. Connect Ex-STA to APUT and verify association using ping traffic

    4. Now start two TCP server
      zperf tcp download -I ml 5001 192.168.0.252
      zperf tcp download -I up 6002 192.168.10.1

    Observed behavior:
    =============

    Second TCP server fails to start

    [Analysis]
    1. After starting uap and a tcp server, there is only one allocatable fd resource left in the fdtable.
    2. When two TCP clients try to establish a connection with the server at the same time,
       the second client cannot be assigned an fd, resulting in a failure.

    [Fix]
    Increase the maximum number of open file descriptors.

### CODE REVIEW

**Review by jukkar — APPROVED** [review]

**Comment by kartben** [comment]
Could the commit message be updated to reflect the *why*, please? I think this can be important for others to understand why/when they may need to do something similar with their own boards. Thanks!

**Comment by NXP-Liam-Li** [comment]
> Could the commit message be updated to reflect the _why_, please? I think this can be important for others to understand why/when they may need to do something similar with their own boards. Thanks!

**Comment by NXP-Liam-Li** [comment]
Ok, has already updated commit log and pull request comment.

**Comment by NXP-Liam-Li** [comment]
Hi @kartben , @krish2718 @nashif @rlubos , pls help to review this PR. Thanks~

**Review by rlubos — APPROVED** [review]

**Pull request merged**
