### PR TITLE
[Backport v2.7-branch] Toolchain/zephyr sdk 0 11 cleanup

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 92a1ca61eb1ba94015a0226ac4e4e1907d480d19~3..92a1ca61eb1ba94015a0226ac4e4e1907d480d19 from #41247

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/46994

### CODE REVIEW

**Review by stephanosio — APPROVED** [review]
As noted in 64d00caee4bba0957bda52411e8416edd405e2df, the commit b973cdc9e874daacbed79b6dd8b25333826db2dc, which is part of the Zephyr 2.7.0 release, updated the minimum required Zephyr SDK version to 0.13, and therefore the legacy SDK support should have been removed for 2.7.0; but, it was overlooked and removed later in the 3.0, so we should backport these patches to the 2.7 as a clean-up.

In addition, the legacy SDK support code included some leftover hacks from 483b4ff030768af23d738c4a65076648be9e9af4 for the Xtensa toolchains, and this breaks the Xtensa builds with the Zephyr SDK 0.14.0 and above (see https://github.com/thesofproject/sof/pull/5654#issuecomment-1091046334).

**Comment by stephanosio** [comment]
NOTE: The documentation build failure has nothing to do with this PR, and will be fixed by #44565.

**Comment by stephanosio** [comment]
Rebased

**Review by marc-hb — COMMENTED** [review]
> This reverts commit 820d327.

This SHA looks incorrect. Github can find it but I cannot find it in any branch. I think references like this should refer to commits that are [actually in the history of the current branch](https://github.com/zephyrproject-rtos/zephyr/commits/v2.7-branch/cmake/toolchain/zephyr/generic.cmake). I recommend  https://github.com/zephyrproject-rtos/zephyr/commit/b557bd90a664

> Remove xtensa specific workaround as this code is now present in Zephyr
SDK cmake code.

To provide more context I recommend `git cherry-pick -x`  https://github.com/zephyrproject-rtos/zephyr/commit/92a1ca61eb1ba for this one (with -x)

**Comment by stephanosio** [comment]
> This SHA looks incorrect. Github can find it but I cannot find it in any branch. I think references like this should refer to commits that are actually in the history of the current branch. I recommend [b557bd9](https://github.com/zephyrproject-rtos/zephyr/commit/b557bd90a664672e5febce74e0206eca383fcb63)

Unfortunately, none of these commits are mine and I would like to not touch the commits that were "cherry-picked" themselves from the main.

**Comment by stephanosio** [comment]
> To provide more context I recommend git cherry-pick -x https://github.com/zephyrproject-rtos/zephyr/commit/92a1ca61eb1ba for this one (with -x)

Done.

p.s. we should update the backport action to do this (cherry-pick with `-x`) by default.

**Comment by marc-hb** [comment]
> I would like to not touch the commits that were "cherry-picked" themselves from the main.

In that case use the -x option, so at least one reference is correct :-)

EDIT: done!

**Review by cfriedt — APPROVED** [review]
I'm OK with this, but yea, let's wait until @tejlmand is back from leave

**Comment by dkalowsk** [comment]
> As noted in [64d00ca](https://github.com/zephyrproject-rtos/zephyr/commit/64d00caee4bba0957bda52411e8416edd405e2df), the commit [b973cdc](https://github.com/zephyrproject-rtos/zephyr/commit/b973cdc9e874daacbed79b6dd8b25333826db2dc), which is part of the Zephyr 2.7.0 release, updated the minimum required Zephyr SDK version to 0.13, and therefore the legacy SDK support should have been removed for 2.7.0; but, it was overlooked and removed later in the 3.0, so we should backport these patches to the 2.7 as a clean-up.
> 
> In addition, the legacy SDK support code included some leftover hacks from [483b4ff](https://github.com/zephyrproject-rtos/zephyr/commit/483b4ff030768af23d738c4a65076648be9e9af4) for the Xtensa toolchains, and this breaks the Xtensa builds with the Zephyr SDK 0.14.0 and above (see [thesofproject/sof#5654 (comment)](https://github.com/thesofproject/sof/pull/5654#issuecomment-1091046334)).

Thanks for providing this background detail @stephanosio.  I remove my earlier objection to this PR with the additional information.

**Review by dkalowsk — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
lgtm.

and sorry for the noise of having refered to the wrong SHA when reverting.
Creates unnecessary noise, but I agree with @stephanosio , better not modify the commit message when cherry picking from main.

**Comment by marc-hb** [comment]
> and sorry for the noise of having refered to the wrong SHA when reverting.
Creates unnecessary noise, but I agree with @stephanosio , better not modify the commit message when cherry picking from main.

In our local stable Zephyr branch I did not really "change" the original commit message but I ... _appended_ the real SHA1 :-)

**Comment by cfriedt** [comment]
@stephanosio - technically this does not need an issue as it's CI related, but iirc, you preferred to file an issue. Do you have an issue to link with this yet? Otherwise, it is ready to merge, so I am ready to do that if you give the OK.

**Comment by stephanosio** [comment]
I have created the issue https://github.com/zephyrproject-rtos/zephyr/issues/46994.

**Pull request merged**
