### PR TITLE
scripts: support for build meta file creation

### PR DESCRIPTION
**Pull request by tejlmand**
This commit is motivated by the west discussion in:
https://github.com/zephyrproject-rtos/west/issues/548

The commit provides the abilty to generate a build meta info file
containing lists of:
- Zephyr:         path and revision
- Zephyr modules: name, path, and revision
- West projects:  path and revision

For Zephyr or Zephyr modules the revision will be `null` if it is not
under git version control.

If Zephyr, a modules, or a project has uncommitted changes, the revision
will be marked dirty.

If west is not installed or used for the build process, the
west-projects list will be empty.

If a project is both a Zephyr module and a west project it will show up
in both lists.

Similar to Zephyr, which is independently referred as the Zephyr in use
but also listed as west project when west is used.
This is important in case ZEPHYR_BASE was manually set and pointing to
a different Zephyr repository.

The build meta file is not created per default but can be enabled with
the BUILD_OUTPUT_META Kconfig setting.

A project using west and having an extra Zephyr module loaded not
controlled using git can look like:
```
zephyr:
  path: /.../zephyr
  revision: 863600cd0e3c0a271e86629c5089821e5e4380cc-dirty
modules:
- name: mcuboot
  path: /.../bootloader/mcuboot
  revision: c61538748ead773ea75a551a7beee299228bdcaf
- name: local_module
  path: /.../local_module
  revision: null
west:
  manifest: /.../zephyr/west.yml
  projects:
  - path: /.../zephyr
    revision: 863600cd0e3c0a271e86629c5089821e5e4380cc-dirty
  - path: /.../bootloader/mcuboot
    revision: c61538748ead773ea75a551a7beee299228bdcaf
  - path: /.../tools/net-tools
    revision: f49bd1354616fae4093bf36e5eaee43c51a55127
```

And without west:
```
zephyr:
  path: /.../zephyr
  revision: 863600cd0e3c0a271e86629c5089821e5e4380cc-dirty
modules:
- name: hal_nordic
  path: /.../modules/hal/nordic
  revision: a6e5299041f152da5ae0ab17b2e44e088bb96d6d
west: null
```

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Review by theotherjimmy — CHANGES_REQUESTED** [review]
Looks good so far. It would be nice to have a description of what this meta file is expected to look like.

**Comment by tejlmand** [comment]
> Looks good so far. It would be nice to have a description of what this meta file is expected to look like.

Good point, will do that.

**Review by SebastianBoe — APPROVED** [review]

**Comment by xnlcasad** [comment]
>This is undesirable in resource-constrained embedded for several reasons.

Please note that we only embed the sha of the the superproject which cascades down to all submodules thanks to git including the submodules sha1s in the superproject itself.

>I regularly diff binary files to prove that two different builds result in the same binary, or a specific desired change in the generated machine code. These SHA's showing up in the diff would cause noise.

Agree, unless you know _exactly_ which bytes can change on a binary due to sha1 difference. In our case, the added value of uniquely identifying your sources for each binary shifts the balance towards keeping the _single_ git superproject sha1 in the binary.

>SHA's are big and take up a lot of space.

Always possible to shorten, and keep only one.

**Review by xnlcasad — APPROVED** [review]
As commented above, i think this can work, even though I would have looked for a more git submodule flavour to this solution. Thanks !

**Comment by tejlmand** [comment]
Marked `[DNM]` for now.

There is nothing wrong in the solution and it works as intended, but @xnlcasad does present an interesting use-case and I will allow myself to do some thinking regarding this, and see if this could include broader use-cases or if dedicated PRs should be raised later with extended functionality.

**Comment by marc-hb** [comment]
> I regularly diff binary files to prove that two different builds result in the same binary, or a specific desired change in the generated machine code.  These SHA's showing up in the diff would cause noise.

I do that very regularly too and when I expect them to be exactly the same I override the VERSION using some flag/envvar or sourcecode hack as a last resort. When I expect them to be different then the noise is always small compared to the expect difference (BTW https://diffoscope.org/ rocks with ELF files)

> SHA's are big and take up a lot of space.

For most git projects 8 bytes are enough.

> This is undesirable in resource-constrained embedded for several reasons.

Yet it seems relatively common practice.

**Comment by tejlmand** [comment]
> BTW, if you are luckily enough to use Zephyr as the manifest repository then the CONFIG_BOOT_BANNER will put the Zephyr SHA in the binary.

Thanks for the hint, just be aware that feature has a minor flaw https://github.com/zephyrproject-rtos/zephyr/issues/39503
but if only using builds produced by a CI, then it should not be problematic in real world but may cause confusion when using locally produced test builds.

**Comment by tejlmand** [comment]
> We'd normally include the git hash of all the git repos used to build a binary in the binary itself, for each commit of the app's history. (done indirectly thru the sha1 of the git superproject which already includes the sha1s of all the submodules)

Yes, and this is possible as long as all code is located in the same tree.
Now, with Zephyr it is possible to inject code from outside Zephyr ( or the `west workspace` for those using `west`) by using `ZEPHYR_EXTRA_MODULES`.

Also, users may not use `west` in which case they will include all modules as described: https://docs.zephyrproject.org/latest/guides/modules.html#without-west

But we could consider to support the following:
- If any Zephyr module (and when `west` is used also any `west` project) is dirty, then propagate the knowledge to the manifest repo status.
- Ability to mark if extra Zephyr modules were injected, for example marking with `-extra`
- When `west` is used, mark if the modules used by Zephyr is in accordance with the projects in the manifest file.
  That way, the SHA of the manifest repo can be marked with `-off`.
- When `west` is used, mark if a project is using branches, with `-branch`
  
With Zephyr being the manifest, then Zephyr SHA could look like:
- `<SHA>-dirty`: when there are uncommited changes in Zephyr repo or a module repo.
- `<SHA>-extra`: when there are extra Zephyr modules added to the build.
- `<SHA>-off`: (`west` only) when the Zephyr modules are not identical to the SHAs specified by the manifest.
- `<SHA>-branch`: (`west` only) when the Zephyr modules are not a SHA but tracking a branch.

of course combinations, like `<SHA>-dirty-off`, are possible.

It would be up to the application on how to include such knowledge into the sample.
I think the boot banner should stay as it is, cause it refers purely to Zephyr, and is just a single repo.

But if having the infrastructure in place, an app could decide to also include the `manifest` repo revision into its build.
A manifest repo revision that is opt-in with the above info and is pure, like just `<SHA>` is then known to be:
- clean in manifest and module repos (missing `-dirty`)
- No extra Zephyr modules were in use (missing `-extra`)
- module SHAs are matching the manifest SHAs (missing `-off`, `west` only)
- module are SHAs only, (missing `-branch`, `west` only)
in which case the SHA of the manifest repo SHA will also identifies all Zephyr modules uniquely.

**Comment by tejlmand** [comment]
> I never suggested removing the -dirty/-off/-branch flags. I always saw them as essential. :-)

I know, I just wanted to emphasize that those flags would be better to use than a non-trustworthy remote if your intentions are to fail the build on certain build combinations.

> Not quite. Consider the scenario where the manifest repo does not have the default manifest file, and instead has multiple manifest directories each with an alternate set of manifest fragments. For instance: $workspace/$mainifest_repo/zephyr/manifests/zephyrproject-rtos/$tag/ and $workspace/$manifest_repo/zephyr/manifests/nrfconnect/$tag/.
> 
> Additional information is needed to know exactly "the" manifest file that establishes the build tree. 

Such as what I do here:
https://github.com/tejlmand/multi_manifest_repo
https://github.com/tejlmand/multi_manifest_repo/blob/main/nRF_connect_SDK/west.yml
https://github.com/tejlmand/multi_manifest_repo/blob/main/vanilla_zephyr/west.yml

and as I wrote earlier:
> If your manifest repo is also a Zephyr module then it will be listed both under Zephyr modules and west projects.
> And I assume the path there will be identical to your manifest path.

now, the repo I just linked is only a manifest repo and not a Zephyr module, but I just tried to build `hello_world` for `native_posix` and checked the output of the generated meta file, and as expected the path listed is the manifest path.

So when I build `nRF_connect_SDK/west.yml` then I'll get:
```
$ west config manifest.path multi_manifest_repo/nRF_connect_SDK
$ west update
$ cmake -GNinja -DBOARD=native_posix -Bbuild samples/hello_world/ -DCONFIG_BUILD_OUTPUT_META=y
$ ninja -Cbuild
$ grep -A1 'multi_manifest_repo' build/zephyr/zephyr.meta
- path: /projects/github/ncs/multi_manifest_repo/nRF_connect_SDK
  revision: 900d0cbbf8c044f50fa688ed4b8897c4c7b99cc5
```
and then I can switch to `vanilla_zephyr`, as:
```
$ west config manifest.path multi_manifest_repo/vanilla_zephyr
$ west update
$ rm -rf build; cmake -GNinja -DBOARD=native_posix -Bbuild samples/hello_world/ -DCONFIG_BUILD_OUTPUT_META=y
$ ninja -Cbuild
$ grep -A1 'multi_manifest_repo' build/zephyr/zephyr.meta
- path: /projects/github/ncs/multi_manifest_repo/vanilla_zephyr
  revision: 900d0cbbf8c044f50fa688ed4b8897c4c7b99cc5
```

as you can see, the manifest path and the revision is part of the build meta info.

Shouldn't that be sufficient ?

> > You may propose that we include the remote from where west will fetch revisions, but that is not the same as
> 
> Your phrasing above captures my intent better than mine. This would work for me.

Good to know, although i'm still not convinced adding this info to the meta build file is a good idea, as I wrote:
`Because adding the remote to the meta file could be wrong information to the user, it should be done with care.`
But nice to know what the proposal is about :+1:

Would like more readers to provide their view on whether such info is considered important.
Afterall, as I just showed, the revision of the manifest project and the manifest path should uniquely identify the manifest file in use.

**Comment by tejlmand** [comment]
@gregshue did some more playing around, and it seems the behavior is depending on what is in `self::path`, but also whether the `.west/config` contains:
```
[manifest]
path = multi_manifest_repo/vanilla_zephyr
file = west.yml
```
or the alternative:
```
[manifest]
path = multi_manifest_repo
file = vanilla_zephyr/west.yml
```
It was the first version which printed to "nice" project path in the meta file.

Going to look a bit more into this.

**Comment by gregshue** [comment]
@tejlmand 

> Shouldn't that be sufficient ?

Yes, that will be sufficient.  For some reason, "manifest path" brought to mind the mounted location to the manifest repo rather than the location of the manifest file within the repo. Thank you for your patience.

> Going to look a bit more into this.

Thanks for looking.  It sounds like this is a good test case. :-)

**Comment by tejlmand** [comment]
> > Going to look a bit more into this.
> 
> Thanks for looking. It sounds like this is a good test case. :-)

@gregshue It sure is.

I have pushed an update which now includes the `manifest path` to the meta info.
See the updated output sample here:
https://github.com/zephyrproject-rtos/zephyr/pull/39382#issue-756763397

**Comment by tejlmand** [comment]
Removed `DNM`.

Currently working on this enhancement: https://github.com/zephyrproject-rtos/zephyr/pull/39382#issuecomment-945575014
but will open dedicated PR for this enhancement as to allow proper review and feedback on such extension.

**Comment by gregshue** [comment]
@tejlmand I see your commit comment says:

> For Zephyr or Zephyr modules the revision will be `null`

Is this still true?

**Comment by tejlmand** [comment]
> > For Zephyr or Zephyr modules the revision will be `null`
> 
> Is this still true?

I guess I only wrote have the sentence I was thinking of.
What I meant was probably:
> For Zephyr or Zephyr modules the revision will be `null` if it is not under git version control.

**Comment by tejlmand** [comment]
> Currently working on this enhancement: [#39382 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/39382#issuecomment-945575014)
> but will open dedicated PR for this enhancement as to allow proper review and feedback on such extension.

Find extension PR here: https://github.com/zephyrproject-rtos/zephyr/pull/40085

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@theotherjimmy @mbolivar-nordic could you take another look please?

**Review by theotherjimmy — APPROVED** [review]

**Review by cfriedt — CHANGES_REQUESTED** [review]
Not a hard NAK, but I haven't seen the term SBOM mentioned anywhere in this conversation. 

Am I misinterpreting the point of this PR?

**Comment by cfriedt** [comment]
Tagging @kestewart here because she would have a much better understanding of how this PR might relate to an SBOM.

**Comment by tejlmand** [comment]
> Not a hard NAK, but I haven't seen the term SBOM mentioned anywhere in this conversation.
> 
> Am I misinterpreting the point of this PR?

Yes, because this is not an SBOM.
You may say it contains a single piece of information that would be needed for an SBOM, but an SBOM is much more than this PR.

Some parts missing before it could be even considered close to an SBOM would be:
- What toolchain was used
- What C library was linked
- Which python packages was used *
- What licenses are active for the software components
- and probable more

* = although the `scripts/requirements.txt` pointed to by the Zephyr revision is known, we don't know if / which of those packages are actually installed (and their version)

So this is far from an SBOM.
But it does contain a list of Zephyr modules / repositories that was included as part of the build.

Also note, the fact that a Zephyr module was considered as part of the build is not the same as that module is required to rebuild.
For example, a user might build `hello_world` for a nRF52840dk and both `hal/nordic` and `hal/stm` will be present as Zephyr modules. But because the build targeted `nRF52840` then the code in `hal/stm` was never active, so the build can be reproduced both with and without `hal/stm` being present.

The meta file only informs what was present, not what is strictly needed (which could be a subset of what is present).

@cfriedt if there is a desire for a SBOM feature, then I would suggest that a dedicated feature request is created, as that would be a different feature. An SBOM feature will of course benefit and build upon the functionality provided by this PR.

**Comment by cfriedt** [comment]
> @cfriedt if there is a desire for a SBOM feature, then I would suggest that a dedicated feature request is created, as that would be a different feature. An SBOM feature will of course benefit and build upon the functionality provided by this PR.

But we already support generating SBOM's, so why wouldn't we just use the existing standard?

Not a hard NAK just thought I would point out the similarities.

**Review by cfriedt — APPROVED** [review]

**Comment by cfriedt** [comment]
> @cfriedt if there is a desire for a SBOM feature, then I would suggest that a dedicated feature request is created, as that would be a different feature. An SBOM feature will of course benefit and build upon the functionality provided by this PR.

We already support generating SBOMs. And the objectives here are pretty similar.

Examples:
* Any SPDX file from a Zephyr release
* https://github.com/opensbom-generator/spdx-sbom-generator#module-structure-json-example
* https://github.com/CycloneDX/sbom-examples/blob/master/cern-lhc-vdm-editor-e564943/bom.json

**Comment by tejlmand** [comment]
> @tejlmand - we already support generating SBOM's, so why wouldn't we just use the existing standard?
> 
> Not a hard NAK just thought I would point out the similarities.

Interesting, I wasn't aware of the `west spdx` extension in Zephyr until you pointed it out.
https://docs.zephyrproject.org/latest/guides/west/zephyr-cmds.html?highlight=spdx#software-bill-of-materials-west-spdx
https://github.com/zephyrproject-rtos/zephyr/pull/34555

I was only invited to the party on the old and closed PR here: https://github.com/zephyrproject-rtos/zephyr/pull/31065

Looking at the spdx files generated there, it tells you which files were used in the build, their checksum, and license. All very important pieces on information.

However, as I far as I can tell the revision of any repository is not included, which means it's practically impossible to go back from the checksum to the repository revision if you want to re-create the build.
Or am I missing something ?

Feel free to open a suggestion if the info generated here should be part of the spdx file.

**Pull request merged**
