### PR TITLE
devicetree: expand use cases for some main macros

### LINKED ISSUE #55115: `DT_FOREACH_PROP_ELEM()` in a `zephyr,user` node inferred property does not work if a single item is supplied
**Describe the bug**
`DT_FOREACH_PROP_ELEM()` in a `zephyr,user` node inferred property does not work if a single phandle is used.

A related bug is this also does not work for a single string, but the underlying problem is different.

**To Reproduce**
```c
/ {
        user: zephyr,user {
            one-string = "one";
            two-string = "one", "two";
            one-handle = <&user>;
            two-handle = <&user>, <&user>;
        };
};

#define PHANDLE_TO_DEVICE(node_id, prop, idx) \
     DEVICE_DT_GET(DT_PHANDLE_BY_IDX(node_id, prop, idx)),

// This fails
const struct device *one_dev[] = { DT_FOREACH_PROP_ELEM(ZEPHYR_USER_NODE, one_handle, PHANDLE_TO_DEVICE) };
// This works
const struct device *two_dev[] = { DT_FOREACH_PROP_ELEM(ZEPHYR_USER_NODE, two_handle, PHANDLE_TO_DEVICE) };

// This also fails
const char *one_string[] = { DT_FOREACH_PROP_ELEM_SEP(ZEPHYR_USER_NODE, one_string, DT_PROP_BY_IDX, (,)) };
// This works
const char *two_string[] = { DT_FOREACH_PROP_ELEM_SEP(ZEPHYR_USER_NODE, two_string, DT_PROP_BY_IDX, (,)) };
```

**Expected behavior**
All should work.

**Impact**
Code that allows one or more items to be specified in zephyr,user nodes doesn't work.  It needs to be written to either allow exactly one item or two or more items.

**Additional context**
There are two different causes here.

For phandles, the issue is that the inferred type is `phandle` and not `phandles`.  While `phandle` is treated as an array of length 1, and will have `_IDX` and `_LEN` macros generated, the code to that generates the `_FOREACH_PROP_ELEM` macro does not do this.  It does not consider `phandle` to be an array.

For strings, the issue is similar, in that the inferred type is `string` and not `string-array`.  However, the `FOREACH_PROP_ELEM` code however *does* generate a macro for properties of type `string`.  But the rest of the macros, `_IDX` and `_LEN`, are not generated for `string` properties, so it still doesn't work.

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Allow using `DT_PROP_LEN()` and `DT_PROP_BY_IDX()` with properties of type `phandle` and `string`. This also allows using `DT_FOREACH_PROP_ELEM()` with both types, which this PR verifies is possible in the test cases.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/55115

### CODE REVIEW

**Comment by xyzzy42** [comment]
Doesn't this mean an inferred string property will return the number of strings if there is more than one, or the number of characters in the string if there is only one?  I.e., there's no way to get consistent behavior for inferred string properties?

Someone is going to have a property with two+ strings and use the length, then change the dts to have one string and be very confused that their code still compiles, but the length is now wrong.

A single string is already a character array as returned by `DT_PROP()`, no need to use a for each to get an array, and the length is already available with `sizeof()` or `strlen()`.

So I'd make foreach and length of a single string be 1.

I'll also mention that the Linux `of_property_read_string_array()` and `of_property_count_strings()` functions work this way too.

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by gmarull — DISMISSED** [review]

**Review by galak — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
> So this basically treats `string` as a degenerate case of `string-array`. That's fine too and I think your argument makes sense.

Updated accordingly

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
@xyzzy42 I'm going to hold off on asking for another +1 and merging this until you confirm the latest is OK for you, just FYI

**Comment by trentp-igor** [comment]
I think this makes sense.  Solves most of the issues for inferred properties.

**Review by gmarull — APPROVED** [review]

**Comment by talih0** [comment]
@mbolivar-nordic, this seems to break build for west build -p -b esp32c3_devkitm -T tests/drivers/uart/uart_async_api/drivers.uart.async_api

**Comment by talih0** [comment]
@trentp-igor, their interrupts are just an array
https://github.com/zephyrproject-rtos/zephyr/pull/58157#pullrequestreview-1437435798

**Pull request merged**
