### PR TITLE
Bluetooth_Le_Audio: MICP

### LINKED ISSUE #47858: LE Audio: Remove "Input" from MICP
**Is your enhancement proposal related to a problem? Please describe.**
It was assumed that MICP was Microphone **Input** Control Profile, but the **I** is not for **Input** but rather the **i** in M**i**crophone. 

**Describe the solution you'd like**
Any place that says `Microphone Input Control` should be renamed to `Microphone Control`. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Meshram-Vibhor**
Renamed Microphone Input Control to Microphone Control. Release notes kept unchanged.
Fixes #47858

### CODE REVIEW

**Review by Thalley — CHANGES_REQUESTED** [review]
@Meshram-Vibhor The PR looks good, just need to fix your commit message.

`Bluetooth_Le_Audio: MICP` should be `Bluetooth: Audio: MICP` and then you need to fix your signed-off-by name as it requires a <FirstName LastName Email> construct (see the failing compliance test).

**Comment by Thalley** [comment]
> @Meshram-Vibhor The PR looks good, just need to fix your commit message.
> 
> `Bluetooth_Le_Audio: MICP` should be `Bluetooth: Audio: MICP` and then you need to fix your signed-off-by name as it requires a construct (see the failing compliance test).

Oh, sorry, should have been more explicit: The one-line commit message should also make sense :)

Suggest to make it something like `Bluetooth: Audio: Remove "input" from MICP naming`

**Review by Thalley — CHANGES_REQUESTED** [review]
See comment

**Comment by Meshram-Vibhor** [comment]
@Thalley  Changes made as you suggested.

**Comment by Thalley** [comment]
> @Thalley Changes made as you suggested.

The commit message is still failing the check :( Please review your signoff line

**Comment by Meshram-Vibhor** [comment]
@Thalley Signoff line seems correct. The current commit ID is `9d67adc60988c26de23750aaa7c72f390b6c8b32`. However this compliance check is running on `f17f665ad8546efb7bc36162ea23a3c1ff60627d`. Not sure why this is happening.

**Comment by Thalley** [comment]
> @Thalley Signoff line seems correct. The current commit ID is `9d67adc60988c26de23750aaa7c72f390b6c8b32`. However this compliance check is running on `f17f665ad8546efb7bc36162ea23a3c1ff60627d`. Not sure why this is happening.

Indeed, the signoff line looks correct now - But you still have an empty commit message :) Please add a commit message stating (briefly) what is being changed, and why

**Comment by Meshram-Vibhor** [comment]
@Thalley Changes made as you suggested.

**Review by Thalley — DISMISSED** [review]

**Comment by larsgk** [comment]
Is the signed off check failing because the account email has a dash and doesn't match First/Last name of the signed off by names?:

> From dc4c0bb3309043c5dc8051fe34f0747abcbd6e6e Mon Sep 17 00:00:00 2001
> From: Meshram-Vibhor <vibhor69meshram@gmail.com>
> Date: Tue, 21 Feb 2023 21:05:11 +0530
> Subject: [PATCH] Bluetooth: Audio: Remove "Input" from MICP naming
> 
> Removed "Input" from Microphone Input Control Profile.
> Release notes kept unchanged.
> 
> Signed-off-by: Vibhor Meshram <vibhor69meshram@gmail.com>

**Comment by Thalley** [comment]
Not really sure why the compliance is failing, or what to do to fix it. @carlescufi Do you know?

**Review by szymon-czapracki — DISMISSED** [review]

**Comment by carlescufi** [comment]
@Meshram-Vibhor you need to run:
`git commit --amend --author="Vibhor Meshram <vibhor69meshram@gmail.com>`

**Comment by Meshram-Vibhor** [comment]
Changes made.
Thanks @carlescufi

**Review by larsgk — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Pull request merged**
