### PR TITLE
west.yml: Migrate to TF-M 1.8

### PR DESCRIPTION
**Pull request by d3zd3z**
Move TF-M to 1.8 and mbed TLS to 3.4

Not currently working as mbed TLS will being worked on, but it is failing before that.

### CODE REVIEW

**Comment by joerchan** [comment]
> Move TF-M to 1.8 and mbed TLS to 3.4
> 
> Not currently working as mbed TLS will being worked on, but it is failing before that.

Isn't CI green? That's highly suspicious

**Comment by d3zd3z** [comment]
I'll have to try to figure out what is going on here. This shouldn't be passing, as these tests don't even get through cmake.

**Comment by d3zd3z** [comment]
I mistyped the PR number and this was still testing tf-m 1.7.  This should have tfm-1.7 as well as mbedtls 3.4. It doesn't build yet.

**Comment by microbuilder** [comment]
@joerchan When you have time, can you please do a review of this and test on Nordic HW? Thanks.

**Review by microbuilder — CHANGES_REQUESTED** [review]
Please add another commit here, updating the 3.5 release notes doc to at least mention the update to TF-M version 1.8.0 in the appropriate section.

**Review by joerchan — CHANGES_REQUESTED** [review]
In the interest of a bisectable history I think the 7 first commits (all except doc update) needs to be squashed to one commit.
Having 4 different updates for these repositories in the manifest, and also the other changes leaves the history with commits that will not build.

Apart from that, this looks good.

Ran the TF-M regression tests and the PSA architecture tests on nrf53 DK and it they all pass.

**Review by joerchan — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Comment by microbuilder** [comment]
@nashif Do you mind merging this in? I think Carles is on vacation. Thanks!

**Pull request merged**
