### PR TITLE
compiler: clang: Add setting of ARM related flags

### PR DESCRIPTION
**Pull request by galak**
Mimic what we have in cmake/compiler/gcc/target.cmake for clang
targetting ARM.  Match gcc behavior by setting -fshort-enums

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
Is it possible to re-use instead of copying the code?

**Comment by galak** [comment]
> Is it possible to re-use instead of copying the code?

open to suggestions, while clang and gcc do similar things, I doubt something like IAR would utilize the same flags/options.  So not sure how we remove the duplication.

**Comment by sigvartmh** [comment]
gcc-toolchain-flag.cmake file?

**Comment by galak** [comment]
@SebastianBoe take a look now, refactor to reduce duplication.

**Review by SebastianBoe — APPROVED** [review]

**Review by vanwinkeljan — APPROVED** [review]

**Pull request merged**
