### PR TITLE
Adding: NEO-M8 Driver Support for MIMXRT1062-FMURT6

### PR DESCRIPTION
**Pull request by mayankmahajan-nxp**
1. Added a device driver for ublox NEO-M8 GNSS module.
    1. NMEA message types supported: GGA.
    2. Bus implementations: UART.
    3. In protocols: 
        1. Supported: Ublox, NMEA, RICTM2.
        2. Tested: Ublox.
    4. Out protocols supported:
        1. Supported: Ublox, NMEA, RICTM3.
        2. Tested: Ublox, NMEA.
3. Added a sample application for demonstration of NEO-M8 with MIMXRT1062-FMURT6.

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
hey folks, there's some work ongoing for supporting gnss devices with a subsystem in https://github.com/zephyrproject-rtos/zephyr/pull/61073, that'll likely cover common NMEA devices as a start, you may want to hold back on this and build on top of that one instead

@bjarki-trackunit

**Comment by bjarki-trackunit** [comment]
Hi, the work being done in #61073 is working towards a common `gnss.h` header which supports a variety of GNSS modems through abstractions of common features and data representations.

The functions in `struct neom8_api` can largely be molded to fit the more generic functions in #61073 `include/drivers/gnss.h` which will allow for interacting with GNSS modems from different vendors identically, which greatly reduces documentation and unit test development, while improving code portability :)

Features that don't fit the common functions and enums in #61073 `include/drivers/gnss.h` can be exposed through a private header as you have done in this PR :)

**Comment by mayankmahajan-nxp** [comment]
@bjarki-trackunit. We appreciate your work in #61073, but do you have any tentative date/timeline by when you expect your PR to be merged into mainline? As it will impact our project timelines as well. 

Meanwhile we are porting our GNSS driver & application as per [#61073] design and will also give you feedback on your PR page in case we find something missing.

**Comment by bjarki-trackunit** [comment]
> @bjarki-trackunit. We appreciate your work in #61073, but do you have any tentative date/timeline by when you expect your PR to be merged into mainline? As it will impact our project timelines as well.
> 
> Meanwhile we are porting our GNSS driver & application as per [#61073] design and will also give you feedback on your PR page in case we find something missing.

API implementations usually take months to be merged with main, and for good reason :) They need to be documented, tested, and most importantly aligned with the Zephyr community.

What I would suggest is to fork Zephyr, and include this PR in your fork, or copy the code in this PR out-of-tree, while its being developed. waiting for it to be merged to main will likely result in substantial delays.

I believe this PR will be functional (API implementation usable, utilities working and tested, including sample application and GNSS driver (for the Quectel L76LB)) within 2 weeks, at which point I believe the PR will not be stable enough to base you driver on. There will of course be concurrent (hopefully small) changes and additions until it is merged at some point in the future in any case.

Hope this information can help you plan out your work :)

**Comment by sumitbatra-nxp** [comment]
> 

Thanks for your reply @bjarki-trackunit .. As I understand we have 2 options - 
1. Get our PR merged as it is for now. But keep track of your PR and when it is merged with main, then modify driver as per your GNSS library design.
2. Holdback our PR till your PR gets merged with main.
What is your suggestion ?

**Comment by fabiobaltieri** [comment]
>     1. Get our PR merged as it is for now. But keep track of your PR and when it is merged with main, then modify driver as per your GNSS library design.

This won't get through in its current form, "misc" devices and driver with device specific APIs are rarely accepted and have to be well justified (as in: no sense to make a subsystem for them, which is clearly not the case here). You'd be better off keeping it off tree for now, maybe make a separate module for it if you need to distribute it, and maybe work towards future integration.

**Comment by bjarki-trackunit** [comment]
Hi again, the GNSS API and subsystem is ready and has been merged :)

**Pull request closed without merging**
