### PR TITLE
[TOPIC-GPIO] gpio: gecko: Add init macro and support for more ports

### PR DESCRIPTION
**Pull request by chrta**
This introduces a macro to initialize gpio ports to the gecko gpio driver. This macro simplified adding support for port g to port k.
These ports are also added to the efr32mg12p soc dtsi file.
Port k will actually be used in the pull request #20194 which adds a basic spi driver to the efr32mg board that connects to a spi nor flash.

### CODE REVIEW

**Comment by galak** [comment]
Its probably best this was done against the 'topic-gpio' branch.

**Comment by chrta** [comment]
@galak OK, i will change the target branch to topic-gpio

**Comment by chrta** [comment]
Sorry, because of the branch changes, a lot of reviewers were requested automatically. Should i delete them manually?
Now the target branch is topic-gpio.

**Comment by galak** [comment]
> Sorry, because of the branch changes, a lot of reviewers were requested automatically. Should i delete them manually?
> Now the target branch is topic-gpio.

I updated the reviewers list.

**Review by mnkp — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
