### PR TITLE
manifest: update cmsis-dsp to v1.16.2

### PR DESCRIPTION
**Pull request by XenuIsWatching**
Update cmsis-dsp module to v1.16.2

### CODE REVIEW

**Comment by XenuIsWatching** [comment]
@stephanosio Would you mind also taking a look at the error in the CIs. Something like this below looks like another fun compiler bug :( especially since it's in a function that involves the ARM MVE (Helium).
```
modules/lib/cmsis-dsp/Source/MatrixFunctions/arm_mat_cmplx_mult_f16.c:419: undefined reference to `__ARM_undef'
```

**Comment by mmahadevan108** [comment]
@XenuIsWatching are the CI failures fixed
@stephanosio can you help review

**Review by stephanosio — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
@mmahadevan108 why was this labelled as a backport? doesn't look like a bug fix? Please close the backport PR if it's indeed a mistake. Thanks!

**Comment by mmahadevan108** [comment]
Backport was added as this was not done in time for the 4.0 release

**Comment by kartben** [comment]
> Backport was added as this was not done in time for the 4.0 release
> 

But this is not fixing a bug, is it? What's the point of doing a feature freeze if we then "open the gates" again for the maintenance releases (and risk compromising the stability the feature freeze was aiming at establishing).
If it's really important to backport it for some reason, I think it needs to be done as an exception just like when we vote on accepting something that missed the feature freeze.

**Comment by mmahadevan108** [comment]
True, thats a good point. Backporting this would be more of an enhancement than a bug fix. We can bring this up in the release meeting.

**Comment by kartben** [comment]
@mmahadevan108 but has anyone even *asked* for this to be backported though? I wouldn't bother bringing this to the release meeting if there is no evidence anyone actually wants/needs this tbh, i.e. I would just close this PR

**Pull request merged**
