### PR TITLE
[Backport v2.7-branch] Bluetooth: controller: Add missing NULL assign to df_cfg in ll_adv_set

### LINKED ISSUE #43602: [v2.7] Bluetooth: controller: Missing NULL assign to df_cfg in ll_adv_set
**Describe the bug**
`ll_adv_set` stores pointer to direction finding TX configuration.
When `ll_reset` is executed the pointer in not NULL assigned.
That leads to erroneous behavior e.g. `df_cfg->is_enabled` was set
to TRUE even the functionality was not enabled.

**Impact**
Touches direction finding functionality only, so it isn't showstopper in general but block use of direction finding.

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 5dd5902f67bfb42e138832b4f466561e253e45cd from #40699

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/43839

### CODE REVIEW

**Comment by cfriedt** [comment]
@ppryga - you may need to create a separate PR to get this into `v2.7-branch`. It seems the backport does not apply cleanly / tests are failing for some reason.

**Comment by ppryga** [comment]
The CI failed on some stuff that is not related with changes introduced by commit in the PR.
I'm not able to re-run or re-base the branch on top of main. 
Can someone try to re-run the CI?

**Comment by cfriedt** [comment]
@nashif - just wondering what to do here. The change itself is fairly trivial and applies cleanly, but CI fails due to a bunch of renode errors.

**Comment by ppryga** [comment]
> @nashif - just wondering what to do here. The change itself is fairly trivial and applies cleanly, but CI fails due to a bunch of random errors.

I agree, it is a bit wired for me, the CI failing on those not PR related things.

**Comment by ppryga** [comment]
> @ppryga - It looks like this needs an issue associated with it for the backport.
Do you mean, new issue and PR to make the bug-fix to get to backport? To "remove" the CI problems.

**Comment by cfriedt** [comment]
> > @ppryga - It looks like this needs an issue associated with it for the backport.
> 
> Do you mean, new issue and PR to make the bug-fix to get to backport? To "remove" the CI problems.

I see that there is a new PR at #42132, so that's fine (I see the CI issue is not resolved), but all back-ported changes do need an issue for audit purposes.

Should this one be closed in favour of #42132?

**Comment by cfriedt** [comment]
@carlescufi - perhaps you would like to create an issue for this backport?

**Comment by cfriedt** [comment]
@ppryga, @carlescufi - it looks like we still need an issue filed for this backport.

**Comment by ppryga** [comment]
@cfriedt it looks the PR is green now, why it can't be merged?

**Comment by cfriedt** [comment]
@ppryga - needs an issue for the backport (original PR had no linked issue, FWICT). I think we still need a maintainer approval as well.

Mentioned a few times already, but every backport needs an issue. If the original PR to main has a linked issue, that is sufficient.

**Comment by ppryga** [comment]
@cfriedt thank you for clarification. I've forgotten that the original PR hadn't got an issue assigned.

@cvinayak @Thalley could you approve this PR to get it merged into v2.7-branch?

**Review by Thalley — APPROVED** [review]

**Comment by cfriedt** [comment]
> @cfriedt thank you for clarification. I've forgotten that the original PR hadn't got an issue assigned.
> 
> @cvinayak @Thalley could you approve this PR to get it merged into v2.7-branch?

@ppryga - it still needs an issue to be backported, regardless of who approves it.

**Comment by ppryga** [comment]
@cfriedt Issue created: https://github.com/zephyrproject-rtos/zephyr/issues/43839 but I can't assign this branch there.

**Comment by cfriedt** [comment]
@cvinayak - can you ack as controller maintainer?

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
