### PR TITLE
arch: x86: Use precalculated symbol offsets

### PR DESCRIPTION
**Pull request by peter-mitsis**
**Current design:**
Assembly code for each of the architectures need to know the offset of various fields in various kernel structures so that they can be properly manipulated. At the current time, these offsets are generated at build time via the GEN_OFFSET_SYM() macro--this requires a separate build step to generate those values--every time stuff gets built.

**Proposed design:**
The need for the offsets in assembly does not go away. However, these proposed changes are a significant step towards eliminating the need for that separate built step. It does this by doing two things for the x86 architecture:
   1. Using a variable to identify the offset of key fields within the _k_thread_ structure--_arch_ and _callee_saved_.
   2. Applying pre-calculated offsets instead of the offsets generated from a separate build step.

This set of commits does not yet completely eliminate the need for the GEN_OFFSET_SYM() derived macros for x86, as there are still some generic kernel ones that are still needed (for now). It is also acknowledged that there will be some minor runtime performance impacts here as extra addition and subtraction operations are required to switch the base register used in memory accesses between the base _k_thread_ address, the __callee_saved_t_  address and the __thread_arch_t_ address.

I would ultimately like to see this style of change done to the rest of the architectures, but I figure it is best to "test the waters" with one before investing additional time and effort with the remainder.

### CODE REVIEW

**Comment by carlocaione** [comment]
My impression is that we are trying to get rid of a compilation step at the cost of code readability, maintainability, size and performance. Is it worth it?

About readability and maintainability.  We have now all the offsets manually hard-coded in header files. That means not only that when we change something in a struct we have to fix all the offsets but this is generally a bad idea when you have for example nested structs (offsets of offsets of offsets ...). Also, architectures like RISCV not even have a fixed / standardized struct for the ESF for example, so all the offsets became platform and not arch dependent anymore.

@peter-mitsis is there a very fundamental reason you want to do this? I don't want to step on your toes but I feel like this should be at least discussed (again?) and agreed in the arch meeting.

**Comment by peter-mitsis** [comment]
@carlocaione - I appreciate the valuable feedback. The readability and maintainability are definitely potential issues with the approach. I also agree that manually pre-calculated offsets are often (with good reason) viewed with suspicion.

From what I can tell, most of the structures for which we need assembly offsets are relatively straight-forward and/or only need to be coded up once. I may have missed some cases, but a historical reading seems to suggest that those structures are quite stable. Using the past as a predictive model for the future, it seems reasonable to assume that they won't be changing often in the future. (I don't see the RISCV esf offsets as insurmountable.)

That still leaves the nested structures (such as k_thread->arch and k_thread->callee_saved) to deal with. Admittedly,  this draft came out rather ugly, which naturally leads to your other point relating to readability, maintainability, size and performance. I'm going to mark this PR as "Do Not Merge"--I've got a couple more ideas that I would like to try to explore.

**Comment by npitre** [comment]
I'm rather confused by this PR.

Hardcoding numeric value in the code compared to having those values
automatically computed can never be a good thing. This is prone to mistakes,
especially if some common structure is changed and then all architectures
have to be adjusted. This is true regardless how unlikely such changes may
be.

Furthermore, this PR as presented does regress code size and runtime.
Even if minuscule, this is not a tradeoff that should be made in favor of
better build time. If the build is too slow for you then get a bigger
build system or find a better way to achieve the same build result.

The build system ought to be smart enough with proper dependencies to
determine when those offsets don't have to be regenerated anyway.

So this is a -1 from me.

**Comment by peter-mitsis** [comment]
@npitre - The approach I've been trying of hard-coding the offsets and storing key offset values within a minimal set global variables is looking less likely to pan out ... especially as I had originally envisioned. It is not looking so bad for the architectures that use CONFIG_USE_SWITCH (such as x86/intel64), as they only need a couple of variables to store key offsets in the k_thread structure. However, those that use the old _swap_ method (such as x86/ia32), the resulting changes have a much more significant negative impact on speed, size, and complexity.

I have explored a little along the lines of restricting such changes to those platforms that use CONFIG_USE_SWITCH, but I suspect that that is going to result in more longer term problems as that would result in two parallel build systems where some platforms could use GEN_OFFSET_SYM() and some could not. This is certainly not ideal, and is very likely a headache in the making.

Most likely, I am going to be putting this idea back into storage.

**Comment by npitre** [comment]
The GEN_OFFSET_SYM() concept is sane. If its implementation has issues 
then _that_ is what should be fixed. Offsets don't have to be 
regenerated on every build if the source for those offsets didn't 
change.

**Pull request closed without merging**
