### PR TITLE
kernel/userspace: Fix dynamic thread stack allocation at userspace

### PR DESCRIPTION
**Pull request by edersondisouza**
It wasn't saving adjusted stack size at either the private stack or the k_object, thus failing subsequent checks.

Test added to check for this case and prevent regressions.

### CODE REVIEW

**Review by peter-mitsis — DISMISSED** [review]

**Review by nashif — DISMISSED** [review]

**Review by dcpleung — DISMISSED** [review]

**Comment by cfriedt** [comment]
LGTM - just one minor suggestion

**Comment by kartben** [comment]
> LGTM - just one minor suggestion 

@cfriedt looks like you may have forgotten to add it to your review

**Review by teburd — DISMISSED** [review]

**Comment by edersondisouza** [comment]
v2: 
  - Simplify testcase.yaml - no need for another entry, if we enable `CONFIG_DYNAMIC_OBJECTS`.

**Review by dcpleung — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
Thanks for the fix @edersondisouza 👍

**Review by teburd — APPROVED** [review]

**Comment by edersondisouza** [comment]
Any comments, @andyross?

**Pull request merged**
