### PR TITLE
Param check for all cfg client cmd

### PR DESCRIPTION
**Pull request by haoyanbiao**
add param check for all cfg client cmd

### CODE REVIEW

**Review by trond-snekvik — APPROVED** [review]

**Comment by PavelVPV** [comment]
This change looks opposite to the changes in that PR: https://github.com/zephyrproject-rtos/zephyr/pull/40994.

**Review by carlescufi — CHANGES_REQUESTED** [review]
Please use `CHECKIF` so that those checks can be optionally disabled.

**Comment by michal-narajowski** [comment]
My original goal in https://github.com/zephyrproject-rtos/zephyr/pull/40737 and later in https://github.com/zephyrproject-rtos/zephyr/pull/40994 was to allow for the Cfg Cli and Health Cli API to be used in a non-blocking way. So If the user passed NULL pointer for output argument then the API would not wait for a response before returning. These checks defeat the purpose of that so the question becomes how we want to achieve async API. Maybe it should be a separate API?

**Review by trond-snekvik — CHANGES_REQUESTED** [review]
Blocking this, as we'd like to be able to use these functions with NULL parameters for responses, as Michał proposes, so we can send messages that don't block until they get a response.

**Comment by haoyanbiao** [comment]
> Blocking this, as we'd like to be able to use these functions with NULL parameters for responses, as Michał proposes, so we can send messages that don't block until they get a response.



> Blocking this, as we'd like to be able to use these functions with NULL parameters for responses, as Michał proposes, so we can send messages that don't block until they get a response.

In the config client context, create a callback for each opcode. The user can select blocking and non blocking modes. The blocking mode blocks and returns according to the existing mechanism. If NULL parameter is passed, the corresponding parameter is returned through callback? In blocking mode, whether to trigger callback?

**Pull request closed without merging**
