### PR TITLE
clang-format: improve and update

### PR DESCRIPTION
**Pull request by gmarull**
The number of options available on clang-format has become quite
extensive over-time, making a dumped file difficult to read or maintain.
In this patch, the .clang-format has been re-written by inheriting from
LLVM (default) since most of the options can be re-used to match the
Zephyr/Linux coding style conventions.

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]
I haven’t tested it but the changes look reasonable.

**Comment by ppryga** [comment]
I didn't compare inherited options. I assume that you have tested it and results are exactly the same or even better due to enabling of options that were commented out for backward compatibility. Am I right with my assumption?

**Review by teburd — DISMISSED** [review]
I tried this out on the existing code base and, at least personally, I thought it did a really nice job.

It aligned macro and function arguments that were previously unaligned. It removed extraneous spaces, which there were surprisingly things like
``` c
uint32_t x =  123;
```
Where the double spacing after the = would be fixed to a single space.

It generally made things more, not less, readable. I didn't run checkpatch after, that might be an interesting bout to see if they agree.

**Comment by nashif** [comment]
getting:

```
clang-format kernel/sem.c
/home/nashif/Work/zephyrproject/zephyr/.clang-format:63:20: error: unknown enumerated scalar
SpaceBeforeParens: ControlStatementsExceptControlMacros
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error reading /home/nashif/Work/zephyrproject/zephyr/.clang-format: Invalid argument

```


clang-format version 12.0.1 (Fedora 12.0.1-1.fc34)

**Comment by gmarull** [comment]
> getting:
> 
> ```
> clang-format kernel/sem.c
> /home/nashif/Work/zephyrproject/zephyr/.clang-format:63:20: error: unknown enumerated scalar
> SpaceBeforeParens: ControlStatementsExceptControlMacros
>                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Error reading /home/nashif/Work/zephyrproject/zephyr/.clang-format: Invalid argument
> ```
> 
> clang-format version 12.0.1 (Fedora 12.0.1-1.fc34)

Commented out this option (available since `13.0`)

**Comment by erwango** [comment]
I'm not sure how to do this and avoiding bike-shading but in order to help getting a consensus on the change and not coming back on it later, would it be possible to demonstrate the result if this change, so each one can have a chance to give his opinion and commonly agree on the result?
For sure, one can do it in his side and see if happy with the result, but demonstration result depends on the sample file used. Having a draft PR which uses this change to comment would be nice, IMO.

**Comment by nashif** [comment]
@gmarull  can this PR also remove .uncrustify.cfg and replace uncrustify with clang-format in the docs as well, related bug #41281  dealing with this assigned to you to close in one shot :)

**Comment by teburd** [comment]
This isn't stale, and I still care

**Comment by cfriedt** [comment]
> It generally made things more, not less, readable. I didn't run checkpatch after, that might be an interesting bout to see if they agree.

`checkpatch.pl` is both a formatting tool and linter. The clang solution uses `clang-tidy` as the linter and `clang-format` as the formatter. As long as `clang-format` and `checkpatch.pl` agree on formatting, we should be good.

It should be noted that the clang tooling actually uses LLVM as the C / C++ parser, so it's quite accurate as it's derived from the AST. IIRC, `checkpatch.pl` might only be suitable for C, so we may eventually want to replace it with `clang-format` and also introduce `clang-tidy` into CI.

**Comment by gmarull** [comment]
> 
> @gmarull - that mirrors my experiences as well. It's probably something that is worth fixing upstream on behalf of the Zephyr project if we were to adopt `clang-format`.

Agreed, would be nice to have these small issues fixed upstream.

**Review by teburd — APPROVED** [review]
Yes please

**Review by stephanosio — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
+1 to clang-format, @nashif and @MaureenHelm ping

**Review by MaureenHelm — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
