### PR TITLE
samples: flash_shell: skip boards without zephyr,flash-controller

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add a `dt_chosen_enabled(chosen)` filter function to sanitycheck. The function returns true if the devicetree /chosen node contains 'chosen' and the referenced node is enabled.

Adjust the sanitycheck filter of the flash shell sample to depend on the board having a chosen zephyr,flash-controller devicetree node (as this is what is referenced in `flash_shell.c`).

This fixes sanitycheck compilation failures for boards which has `CONFIG_FLASH_HAS_DRIVER_ENABLED=y` but no `zephyr,flash-controller` chosen node.

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
The buildkite failures are unrelated to this PR:
- hexiwear_kw40z board configuration fails to compile the MCUX FTFX driver
- stm32h747i_disco_m4 board configuration get compilation errors due to unused, but selected, stm32 uart driver

**Comment by nashif** [comment]
> The buildkite failures are unrelated to this PR:

aren't those triggered by the change though and how the filter has changed? To merge this we would need to fix those.

**Comment by MaureenHelm** [comment]
> * hexiwear_kw40z board configuration fails to compile the MCUX FTFX driver

The flash driver isn't supported on the KW40 because this SoC has a very old version of the SDK. I think we can just remove the `zephyr,flash-controller` chosen node for this SoC. @galak any objections?

**Comment by galak** [comment]
> The flash driver isn't supported on the KW40 because this SoC has a very old version of the SDK. I think we can just remove the `zephyr,flash-controller` chosen node for this SoC. @galak any objections?

No objections.

**Comment by galak** [comment]
@henrikbrixandersen ping on fixing the CI failure?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen ping on fixing the CI failure?

I will take a look at it tonight.

**Review by MaureenHelm — APPROVED** [review]

**Comment by nashif** [comment]
btw, there was a PR that did part of this:

https://github.com/zephyrproject-rtos/zephyr/pull/29116, we should close...

**Review by nashif — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@erwango Any input on how to handle the `stm32h747i_disco_m4` compilation failure (`CONFIG_UART_STM32` is automatically enabled based on `CONFIG_SERIAL=y` and `CONFIG_SOC_FAMILY_STM32=y`, but the `stm32h747i_disco_m4` does not have any serial ports enabled in dts, so compilation fails due to warning about unused api structs in the stm32 uart driver)?

**Comment by galak** [comment]
@henrikbrixandersen what about having the filter be:

`filter: CONFIG_FLASH_HAS_DRIVER_ENABLED and dt_chosen_enabled("zephyr,flash-controller")`

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen what about having the filter be:
> 
> `filter: CONFIG_FLASH_HAS_DRIVER_ENABLED and dt_chosen_enabled("zephyr,flash-controller")`

@galak Thanks, I have updated the filter to use that. I have also removed the explicit `CONFIG_SERIAL=y` from the flash_shell sample.

**Comment by erwango** [comment]
@henrikbrixandersen 

> @erwango Any input on how to handle the stm32h747i_disco_m4 compilation failure 

> (CONFIG_UART_STM32 is automatically enabled based on CONFIG_SERIAL=y and CONFIG_SOC_FAMILY_STM32=y

No issue with this part.
The unusual thing here is CONFIG_SERIAL enabled in sample's prj.conf. This is one of the very few peripheral drivers flags that are left for activation as part of the default board configuration (with other basics: GPIO, CLOCK_CONTROL, ..).
This _m4 target was configured with this expectation. So from this point of view, I'd advise to clean the sample configuration.

> but the stm32h747i_disco_m4 does not have any serial ports enabled in dts, so compilation fails due to warning about unused api structs in the stm32 uart driver)?

Reason for this configuration is that the console is rooted by default on the _m7 target of this dual core board.
Though, I agree this could be seen as abusive and what could be done is to enable SERIAL and keep CONSOLE disabled. I'll have a try and see if this works. One risk is to fault in samples/tests making wrong assumptions on those flags (like filter on SERIAL=y and then enable CONSOLE).

**Pull request merged**
