### PR TITLE
boards: acrn_ehl_crb: Fix being able to build EDAC driver

### PR DESCRIPTION
**Pull request by jhedberg**
These two patches make it possible to build the EDAC driver for the acrn_ehl_crb board.

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by jenmwms — COMMENTED** [review]
This looks reasonable to me. Unfortunately I cannot test on HW at the moment, working to resolve. I'll reach out to see if someone else can help test it out too.

**Comment by jhedberg** [comment]
@jenmwms to be clear, the intention of this PR is to make the driver buildable, nothing else. I don't think @finikorg tested on ACRN when implementing the driver. I'd propose to resolve any runtime issues as a separate task later.

**Comment by enjiamai** [comment]
@jhedberg @jenmwms  After verifying in acrn_ehl_crb,  the build problem was solved.

**Comment by finikorg** [comment]
> 
> 
> @jenmwms to be clear, the intention of this PR is to make the driver buildable, nothing else. I don't think @finikorg tested on ACRN when implementing the driver. I'd propose to resolve any runtime issues as a separate task later.

I was tedting it on ACRN and it was not working starting from PCI IDs and exposing needed registers.

**Pull request merged**
