### PR TITLE
net: tcp: Notify TX window avaialbility 

### LINKED ISSUE #45367: net: tcp: Scheduling dependent throughput
**Describe the bug**
The throughput with the TCP stack for large transfers is even in ideal situations dependent on scheduling / timing. Even till the point where it can fail entirely.

The situation is happening on an proprietary embedded system in combination with an Azure cloud application, when sending data. Receiving data does not prose challenges so far.
It can also be reproduced using a modified testcase in https://github.com/ssharks/zephyr/tree/net/tcp_throughput using the Qemu x86 emulator.

In this modified testcase the debug logging has been enabled, which shows various unexpected messages like:
`[00000400] <err> net_pkt: Data buffer (68) allocation failed.`
Also rather big time leaps where within almost 100 ms, no action takes place without clear explanation:
```
[00000910] <dbg> net_tcp: tcp_unsent_len: (rx_q[0]): unsent_len=0
[00001000] <dbg> net_tcp: tcp_window_full: (test_v4_send_recv_large): conn: 0x1703f8 window_full=0

```
**To Reproduce**
Run ./scripts/twister -T tests/net/socket/tcp -p qemu_x86
And look in the generated handler.log

**Expected behavior**
The transfer should complete in ~1 second instead of > 20 seconds without a clear difference between platforms and cooperative or preemptive scheduling.

**Impact**
The current TCP implemenation is not workable for uploading larger payloads

**Logs and console output**
Log files of both the test in cooperative and preemptive scheduling have been attached. The preemptive case failed with a timeout.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...
[handler_coop.log](https://github.com/zephyrproject-rtos/zephyr/files/8629030/handler_coop.log)
[handler_preempt.log](https://github.com/zephyrproject-rtos/zephyr/files/8629032/handler_preempt.log)

### LINKED ISSUE #45426: Data buffer allocation: TCP stops working
**Describe the bug**

**Symptom:**
TCP connection is broken and neither recovers nor closes (remains ESTABLISHED).
Indicating errors in log are:
[conn: ... packet allocation failed](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp.c#L1020)
and
[Data buffer ... allocation failed](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/net_pkt.c#L1197)  

**_Supposed_ reason:**
TCP TX packets and buffers are shared resource.
They are used for sending data over TCP, re-sending data over TCP and a bunch of other things - dhcp, icmp and probably some others.

In case of sending and resending data, first net_context.c and then tcp.c allocates packets and buffers from the same slab and net_buffer_pool, respectively.

Normally it wouldn't be a problem, but TCP is usually called via sockets, and in many cases the socket is accessed again and again without any kind of polling.
Even if polling is explicitly called, it doesn't change anything. See: https://github.com/zephyrproject-rtos/zephyr/issues/5842

If socket is in blocking mode, then connection is slow because of sleeping (see e.g. https://github.com/zephyrproject-rtos/zephyr/issues/45367)
If socket is in non-blocking mode, then net_context.context_sendto is called without any delay whatsoever.

context_sendto then keeps allocating memory from TX buffers. If the window is full, it's released _almost_ right away.
However, since it's called again and again (see above), it has a lot of impact.

At the same time, tcp_send_data tries to allocate buffers for the queue. 
And it might not be able to do that, since context_sendto keeps occupying the buffers.
tcp_send_data  is also called from tcp_resend_data, in this case lost packets are not resent.

The problem is likelier to happen "in the wild" where networks are unstable.
E.g. for us, it was a showstopper in case of a weak Wi-Fi signal, where resends were necessary not only on a data link layer, but also on the TCP layer.
I.e., as stated above, big chunks to non-blocking socket + TCP resends.

**Propose fix**
Lock TCP (using tcp::lock) before allocating packet in net_context, preventing race condition.
Then, once the mutex is unlocked and resend was pending, it will be executed right away.
If we try to execute it at the same with context_sendto, then resend doesn't have memory.

Tested fix implemented in https://github.com/zephyrproject-rtos/zephyr/pull/45437, and unlike timing/buffers adjustments, this seems to solve the issue, not just reduce it's probability.

**To Reproduce**
- any networking application, e.g. http webserver
- Keep sending data in big chunks in a non-blocking socket.
- increase chunks fed to sockets to 4096+ Bytes (assuming we use default settings for CONFIG_NET_PKT_TX_COUNT (14), CONFIG_NET_BUF_TX_COUNT (36) and CONFIG_NET_BUF_DATA_SIZE (128)) and do NOT set CONFIG_NET_TCP_MAX_SEND_WINDOW_SIZE)  
- Make sure sometimes TCP resends are needed (pick unstable medium (weak Wi-Fi), or drop packets in driver sporadically, or use some problem simulator, e.g. netem https://wiki.linuxfoundation.org/networking/netem)

I'll try to add a demo app or twister test for QEMU to reproduce that and will reference it here.

**Expected behavior**
TCP keeps working, regardless of how aggressive we call the socket and with which amount of user data.

**Impact**
Showstopper for applications which need long-term stability.

**Logs and console output**
[00:36:03.926,940] <err> net_pkt: Data buffer (1328) allocation failed.
[00:36:03.926,971] <err> net_tcp: conn: 0x2003595c packet allocation failed, len=1280
[00:36:04.227,142] <err> net_pkt: Data buffer (1328) allocation failed.
[00:36:04.227,172] <err> net_tcp: conn: 0x2003595c packet allocation failed, len=1280
[00:36:04.527,374] <err> net_pkt: Data buffer (1328) allocation failed.
[00:36:04.527,404] <err> net_tcp: conn: 0x2003595c packet allocation failed, len=1280
[00:36:04.827,545] <err> net_pkt: Data buffer (1328) allocation failed.
[00:36:04.827,575] <err> net_tcp: conn: 0x2003595c packet allocation failed, len=1280

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain: [Zephyr SDK NRF version 2.7.99](https://github.com/nrfconnect/sdk-zephyr/tree/v2.7.99-ncs1) 

**Additional context**

### PR DESCRIPTION
**Pull request by rlubos**
This PR adds a mechanism which allows the TCP layer to notify the TX window state to the upper layer through a semaphore. This allows to achieve better throughput in low buffer scenarios, as the socket layer does not need to wait blindly, as well as to implement POLLOUT functionality.

Additionally, improve ZWP transmission logic, by dedicating a separate timer for ZWP sending. This is essantial for POLLOUT to work correctly, as we're not triggering send in this case, which was the place ZWP was sent before.

Fixes #45367
Fixes #45426

### CODE REVIEW

**Comment by rlubos** [comment]
CC @ssharks @AndreyDodonov-EH Please review as well.

**Comment by AndreyDodonov-EH** [comment]
@rlubos Looks great, I'll try to test and review it.

Btw, should I open a small PR extending http_client with the call to poll?

**Comment by rlubos** [comment]
> @rlubos Looks great, I'll try to test and review it.
> 
> Btw, should I open a small PR extending http_client with the call to poll?

Would be great if you could do that.

**Comment by ssharks** [comment]
Looks great. The only thing I find hard to judge. The checking for the full and afterwards taking a semaphore is no atomic operation. Are you sure this cause a deadlock due to a scheduler? Can you elaborate a little on that?

**Comment by ssharks** [comment]
I don't know how to enter a proper review comment on an untouched line.

In function tcp_window_full:
bool window_full = !(conn->unacked_len < conn->send_win);
I think should be 
bool window_full = !(conn->send_data_total < conn->send_win);

As I read the code, send_data_total keeps track of the data in the send_data, while unacked_len is used for (re)transmission and can be reset to 0 in case of retransmissions.
The naming is confusing and more suitable names would be a bonus I think

**Comment by rlubos** [comment]
> Looks great. The only thing I find hard to judge. The checking for the full and afterwards taking a semaphore is no atomic operation. Are you sure this cause a deadlock due to a scheduler? Can you elaborate a little on that?

All those operations (semaphore take/give and window check) take place after the TCP connection mutex is acquired, so it should be safe. In case the scheduler kicks in inbetween those operations, and we for example receive an ACK after we judged the window should be locked, the receiver thread will wait on the mutex until we release it. So in such case, we'll lock the window, but release it just after we're able to process the ACK.

**Comment by rlubos** [comment]
> I don't know how to enter a proper review comment on an untouched line.
> 
> In function tcp_window_full: bool window_full = !(conn->unacked_len < conn->send_win); I think should be bool window_full = !(conn->send_data_total < conn->send_win);
> 
> As I read the code, send_data_total keeps track of the data in the send_data, while unacked_len is used for (re)transmission and can be reset to 0 in case of retransmissions. The naming is confusing and more suitable names would be a bonus I think

This might be a good point, but I need to investigate this further, I wouldn't dare to change this blindly w/o analyzing possible consequences first. I think though we should keep track of this possible change separately, i.e. out of the contex of this PR.

**Comment by carlescufi** [comment]
@AndreyDodonov-EH and @ssharks please approve the PR if it fixes your issues.

**Comment by ssharks** [comment]
It looks good. As I'm close to a product release, I can't test it in the application at the moment. Yesterday I checked the performance gain in the testcase, which is substantial.

**Review by AndreyDodonov-EH — APPROVED** [review]
Looks great to me.
@carlescufi Also fixes our issue, as long as polling is called on the higher level.

**Review by ssharks — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by ssharks** [comment]
I submitted a related PR: https://github.com/zephyrproject-rtos/zephyr/pull/45740

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
