### PR TITLE
drivers: flash: stm32 ospi flash driver the correct erase instruction

### PR DESCRIPTION
**Pull request by FRASTM**
Use the most adapted instruction for the sector erase command It can be 0x20 or ox21 or 0x21DE in octo - DTR mode. The value is given by the SFDP table and  filled in the erase_types  table the during the SFDP discovery process.

This PR fixes an error found in the https://github.com/zephyrproject-rtos/zephyr/pull/66229

### CODE REVIEW

**Comment by FRASTM** [comment]
tested on stm32u585 disco kit with west build -p auto -b b_u585i_iot02a samples/drivers/spi_flash
--> sector erased  is correctly read at 0xFF 

```
ospi-nor-flash@70000000 SPI flash testing                                                                                                     
==========================                                                                                                                    
                                                                                                                                              
Perform test on single sector                                                                                                                 
Test 1: Flash erase                                                                                                                           
 erase cmd = 0x20                                                                                                                             
 erase cmd = 0x21de                                                                                                                           
 erase cmd = 0x21de                                                                                                                           
 erase cmd = 0x21de                                                                                                                           
Flash erase succeeded!     
...    
```

**Comment by FRASTM** [comment]
add another check in the samples/drivers/spi_flash after erasing,
In case the erase sector does not give 0xFF:
                                                                                              
```
Perform test on single sector                                                                                                                         
Test 1: Flash erase                                                                                                                                   
Erased Data do not match 0xffffffff    
```

**Review by de-nordic — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by Laczen — APPROVED** [review]

**Comment by FRASTM** [comment]
CI faiure due to https://github.com/zephyrproject-rtos/zephyr/issues/70445

**Comment by erwango** [comment]
@nashif CI is broken due to https://github.com/zephyrproject-rtos/zephyr/issues/70445 which is waiting for https://github.com/zephyrproject-rtos/zephyr/pull/70548. Would it be possible to merge it anyway ?
Current PR is fixing an issue seen by several users (see https://github.com/zephyrproject-rtos/zephyr/discussions/70844 for instance)

**Comment by FRASTM** [comment]
a CI failure remains (not related to this PR) when building  
`west build -p auto -b em_starterkit/emsk_em11d samples/drivers/spi_flash
`
even on SHA1  b9f3d68863b9f75dcc1dfac7dd7ff269b99cd118

**Pull request merged**
