### PR TITLE
samples: move video from subsys to drivers

### PR DESCRIPTION
**Pull request by josuah**
"Video subsystem for Zephyr" is actually only defined as a driver and the examples include `<zephyr/drivers/video.h>`.

This moves the `sample/subsys/video` to the `sample/drivers/video` directory to reflect that.

### CODE REVIEW

**Comment by josuah** [comment]
Affecting these ongoing PRs:
- #71463
- #72633
- #72254
- #66994

**Review by carlescufi — DISMISSED** [review]

**Comment by josuah** [comment]
I rebased for solving a merge conflict.

**Comment by josuah** [comment]
#66994 already picked this new directory tree, but no conflict regardless of the order they are added.

**Review by kartben — CHANGES_REQUESTED** [review]
can you please add the appropriate redirect entries in `doc/_scripts/redirects.py`?
This allows to properly redirect people browsing e.g. https://docs.zephyrproject.org/3.6.0/samples/subsys/video/capture/README.html and clicking on "see the most recent version... " link

**Review by kartben — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Pull request merged**
