### PR TITLE
cmake & dts changes to move board related dts files into board dir

### PR DESCRIPTION
**Pull request by galak**
Move .fixup and .dts files out of the dts/ dir into the board dirs.  This makes the board ports more standalone to allow for having a board port completely outside of the tree.

### CODE REVIEW

**Review by carlescufi — COMMENTED** [review]
I remember this move being mentioned some time back, can someone remind me of the advantage of having those files in boards/ ? Is it to make it easier to have out-of-tree boards that are self-contained?

**Comment by galak** [comment]
> I remember this move being mentioned some time back, can someone remind me of the advantage of having those files in boards/ ? Is it to make it easier to have out-of-tree boards that are self-contained?

Yes, the main idea is to make it easier to have a board port outside of the tree.  Also, I think its best to keep all board related data/code/etc with the board, makes it easier to review all in one place.

**Review by carlescufi — APPROVED** [review]
LGTM

**Review by SebastianBoe — APPROVED** [review]
The cmake-related changes are fine.

For future reference;

set_ifndef(FIXUP_FILE my_file.fixup)

is a clean way to have overridable variables.

**Comment by galak** [comment]
> The cmake-related changes are fine.
> 
> For future reference;
> 
> set_ifndef(FIXUP_FILE my_file.fixup)
> 
> is a clean way to have overridable variables.

cool, I'll update the PR to do that instead.

**Comment by SebastianBoe** [comment]
So, what made you decide what stays, and what moves?

(I have been curious as to the difference between .dts and .dtsi really)

**Comment by galak** [comment]
> So, what made you decide what stays, and what moves?
> 
> (I have been curious as to the difference between .dts and .dtsi really)

the .dts files are for the board, the .dtsi are for the SoC.  Right now the .fixup files are board specific.  So the .dtsi and yaml files stay for now in the dts/.  We could move the .dtsi files into SoC, but its gets a bit more messy since the .dtsi can get shared between different SoCs of the same family.

**Comment by MaureenHelm** [comment]
The changes look fine, but you're missing the Signed-off-by in the third commit

**Comment by galak** [comment]
> The changes look fine, but you're missing the Signed-off-by in the third commit

thanks for catching that.  fixed now.

**Pull request merged**
