### PR TITLE
test: arm: irq: Add overlays files for Infineon boards

### PR DESCRIPTION
**Pull request by npal-cy**
[Infineon: board: Add CONFIG_GPIO to defconfigs](https://github.com/zephyrproject-rtos/zephyr/commit/b94bb41cfef3f588bdb2a9857427aa13a8acc7c8) 

Add CONFIG_GPIO from defconfigs for Infineon boards.

Revert pull/81377, which affect some ble samples which
used GPIO.

Signed-off-by: Nazar Palamar <nazar.palamar@infineon.com>

[test: arm: irq: Add overlays files for Infineon boards](https://github.com/zephyrproject-rtos/zephyr/commit/86139976baf96c3fb88455a448e862b371f3e599) 

Changed interrupt priority for GPIO, default 6 is not suitable for
for the ZERO_LATENCY_IRQS function used in this test.
used in this test.

FIX CI: https://github.com/zephyrproject-rtos/zephyr/actions/runs/11524969451/job/32695832470?pr=80025
Signed-off-by: Nazar Palamar <nazar.palamar@infineon.com>

### CODE REVIEW

**Review by ifyall — APPROVED** [review]

**Comment by mmahadevan108** [comment]
I had expressed my concerns about deleting GPIO from the `defconfig` https://github.com/zephyrproject-rtos/zephyr/pull/81377#discussion_r1842586180 
However you had mentioned that change was needed for the zero latency use-case. 
Can you please explain what you are changing here?

**Review by thedjnK — CHANGES_REQUESTED** [review]
This was literally removed not even 1 day ago https://github.com/zephyrproject-rtos/zephyr/commit/7e1b00d35eb5f21c98c844a589f6d745ab0fcdba why was this removed only to be re-added?

**Comment by npal-cy** [comment]
> I had expressed my concerns about deleting GPIO from the `defconfig` [#81377 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/81377#discussion_r1842586180)
> However you had mentioned that change was needed for the zero latency use-case.
> Can you please explain what you are changing here?

Yes this changes was fixed zero latency use-case, but i found it affected some sample(https://github.com/zephyrproject-rtos/zephyr/pull/81435). So before 4.0 release it safe to fix locally only zero latency by adding overlay files rather then add overlays to a lot set of samples...(see my closed PR https://github.com/zephyrproject-rtos/zephyr/pull/81435)

**Comment by npal-cy** [comment]
> This was literally removed not even 1 day ago [7e1b00d](https://github.com/zephyrproject-rtos/zephyr/commit/7e1b00d35eb5f21c98c844a589f6d745ab0fcdba) why was this removed only to be re-added?

see my comment [above](https://github.com/zephyrproject-rtos/zephyr/pull/81464#issuecomment-2479991112).

**Review by dkalowsk — APPROVED** [review]

**Comment by thedjnK** [comment]
> Revert pull/81377, which affect some ble samples which used GPIO.

If a sample needs GPIO then the sample should enable it

**Comment by npal-cy** [comment]
> If a sample needs GPIO then the sample should enable it

Hi [thedjnK](https://github.com/thedjnK), need some clarification here.

1. If board has some LED/buttons defined in board DTS, should we mandatory enable  CONFIG_GPIO or not?

2. "If a sample needs GPIO then the sample should enable..."  I came to the same conclusion when I disabled GPIO from the board defconfig (https://github.com/zephyrproject-rtos/zephyr/commit/7e1b00d35eb5f21c98c844a589f6d745ab0fcd). but in https://github.com/zephyrproject-rtos/zephyr/pull/81435 was explained that GPIO should be enabled by board-specific conf files (https://github.com/zephyrproject-rtos/zephyr/pull/81435#issuecomment-2478625648). 
 I have decided to revert https://github.com/zephyrproject-rtos/zephyr/commit/7e1b00d35eb5f21c98c844a589f6d745ab0fcdba. Otherwise, I will have to go over all the samples and check if they use GPIO. If so, I will need to add the board-specific configuration files to enable board.

**Review by ithinuel — APPROVED** [review]

**Comment by thedjnK** [comment]
> If board has some LED/buttons defined in board DTS, should we mandatory enable CONFIG_GPIO or not?

It should be in the defconfig yes

> "If a sample needs GPIO then the sample should enable..." I came to the same conclusion when I disabled GPIO from the board defconfig (https://github.com/zephyrproject-rtos/zephyr/commit/7e1b00d35eb5f21c98c844a589f6d745ab0fcd). but in https://github.com/zephyrproject-rtos/zephyr/pull/81435 was explained that GPIO should be enabled by board-specific conf files (https://github.com/zephyrproject-rtos/zephyr/pull/81435#issuecomment-2478625648).

@Thalley seems like there is a problem with the samples, there should be #ifdef's for the GPIOs, one has it correct: https://github.com/npal-cy/zephyr-1/blob/35cd59ce4cee79aec8cb4956bb01d417c731d87e/samples/bluetooth/peripheral_hr/src/main.c#L122 but this is wrong because it assumes GPIO support is always enabled: https://github.com/npal-cy/zephyr-1/blob/35cd59ce4cee79aec8cb4956bb01d417c731d87e/samples/bluetooth/mesh/src/board.c#L14 a board might have buttons defined but if `CONFIG_GPIO=n` then the buttons shouldn't even be looked at

**Review by thedjnK — APPROVED** [review]
Changes here are OK but (outside scope of this PR) Bluetooth samples should be fixed so that having GPIO disabled does not cause build errors

**Pull request merged**
