### PR TITLE
Bluetooth: controller: consider host ctrl feature bits in feat exchange

### PR DESCRIPTION
**Pull request by erbr-ot**
Host controlled feature bits were not considered in feature exchange procedure. This is fixed.

Signed-off-by: Erik Brockhoff <erbr@oticon.com>

### CODE REVIEW

**Review by kruithofa — DISMISSED** [review]

**Review by mtpr-ot — COMMENTED** [review]
Don't know how important it is, but maybe fix the spelling mistake in the commit message header?

**Comment by erbr-ot** [comment]
Spelling mistake fixed and rebased

**Review by wopu-ot — DISMISSED** [review]

**Comment by erbr-ot** [comment]
rebase

**Comment by erbr-ot** [comment]
rebase

**Review by wopu-ot — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
