### PR TITLE
Fix links to docs.zephyrproject.org

### PR DESCRIPTION
**Pull request by ivakyb**
append /index.html, and now browser loads page with CSS.

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by pfalcon** [comment]
@ivakyb: Thanks for the patch. You would need to fix commit message issues above, e.g. use `README: Fix links to docs.zephyrproject.org` as the commit title, have a "Signed-off-by:" line (with a real name, I believe), etc.

**Comment by ivakyb** [comment]
Yes. I will pay attention to gpg

On 18 February 2019 18:24:17 EET, Paul Sokolovsky <notifications@github.com> wrote:
>@ivakyb: Thanks for the patch. You would need to fix commit message
>issues above, e.g. use `README: Fix links to docs.zephyrproject.org` as
>the commit title, have a "Signed-off-by:" line (with a real name, I
>believe), etc.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/zephyrproject-rtos/zephyr/pull/13454#issuecomment-464797804

-- 
Простите за краткость, создано в K-9 Mail.

**Review by dbkinder — APPROVED** [review]
Technically this change shouldn't be needed: the server should redirect an http reference to a folder into a reference to an index.html file in that folder.   That said, there does seem to be a server configuration issue where this redirection isn't happening if the folder reference doesn't end with a ``/``, so this PR fixes the problem. @nashif

**Comment by ivakyb** [comment]
> Technically this change shouldn't be needed

Sure this is server's problem. But easier to fix it here.

**Comment by ivakyb** [comment]
I don't understand what is wrong with my **Identity/Email ** — why checks fail?

**Comment by nashif** [comment]
> I don't understand what is wrong with my **Identity/Email ** — why checks fail?

this is your commit:

```
commit adc8ca01ccef60b532ba1a39e9f3cfc4ef02b68f (HEAD, upstream/pull/13454)
Author: kyb <i.kyb@ya.ru>
Date:   Sun Feb 17 00:29:31 2019 +0200

    doc: Fix links to docs.zephyrproject.org

    append /index.html, and now browser loads page with CSS.

    Signed-off-by: Ivan kyb Kuvaldin <i.kyb@ya.ru>
```

See that Author has:

`kyb <i.kyb@ya.ru>` 

while your signed-off-by has:

`Ivan kyb Kuvaldin <i.kyb@ya.ru>`

They have to match.

**Comment by ivakyb** [comment]
Hm...
```
commit 60f9d347c87da0a1ee89160c147a2ad63c0ce794
Author: kyb <i.kyb@ya.ru>
Date:   Sun Feb 17 00:29:31 2019 +0200

    doc: Fix links to docs.zephyrproject.org

    append /index.html, and now browser loads page with CSS.

    Signed-off-by: kyb <i.kyb@ya.ru>
```
Still failed.

**Comment by ivakyb** [comment]
Hooray!

**Pull request merged**
