### PR TITLE
x86: ia32: executing in virtual address space

### PR DESCRIPTION
**Pull request by dcpleung**
This adds the necessary bits to enable running code in virtual address space (as defined by `CONFIG_KERNEL_VM_BASE` and `CONFIG_KERNEL_VM_SIZE`). This also adds a new `qemu_x86_virt` board for testing.

### CODE REVIEW

**Review by andyross — APPROVED** [review]
This all seems OK to me.  I worry about the paradigm though: this seems to be doing a whole lot of "if phys do this, if virt do this".  Wouldn't it make more sense to work toward a paradigm where we have a single kernel linked in a single space, and then a loader/setup/wrapper layer that is responsible for putting it there (either via loading at a physical address or via mapping it virtually)?  I worry a little about maintainability I guess.

**Review by jhedberg — APPROVED** [review]

**Comment by dcpleung** [comment]
(Note that compliance check failures are about having similar lines of Python code in different files. Not a real failure in my mind.)

GDT, IDT and page tables need to have physical addresses, and most changes under `arch/` are about this (and also boot from physical addresses). The address translations needed here cannot be avoided.

The Python script added under `boards/x86/qemu_x86` is strictly for QEMU. QEMU looks at the program header segments for any PT_LOAD entries, and start copying from ELF to the indicated memory addresses. Modifying the ELF file is simply nudging the QEMU loader to load into available memory. Writing a loader ourselves requires some creative linker script magic. The linker skips any BSS/noinit sections when packing into a loadable binary (one that can be put onto flash), so we will need to know load address to virtual address mapping without ELF file during runtime. So the currently method is a lot less invasive one to get QEMU running.

**Comment by nashif** [comment]
> (Note that compliance check failures are about having similar lines of Python code in different files. Not a real failure in my mind.)

still need to resolve this, i.e. by adding a comment to tell pylint to skip those warnings.

**Comment by dcpleung** [comment]
> still need to resolve this, i.e. by adding a comment to tell pylint to skip those warnings.

Looks like disabling duplicate code checking across file is broken: https://github.com/PyCQA/pylint/issues/214

**Pull request merged**
