### PR TITLE
cmake: fix CONF_FILE parsing to allow for cmake lists

### PR DESCRIPTION
**Pull request by mrrosen**
Change how the CONF_FILE cmake variable is handled by kconfig.cmake to be a string instead of just expecting a string with space-separated file names. This change allows for the use of more modular style for setting CONF_FILE in the event of multiple config files. See the thread on the zephyr-devel mailing list subject line "[Zephyr-devel] How to support multiple defconfigs to be merged?"

### CODE REVIEW

**Comment by ulfalizer** [comment]
Might want to check if any updated should be made to http://docs.zephyrproject.org/application/application.html (`doc/application/application.rst`) as well.

**Review by SebastianBoe — APPROVED** [review]

**Comment by carlescufi** [comment]
@mrrosen @ulfalizer agreed, we should probably update the doc. There are multiple instances there of `CONF_FILE` followed by something like "files separated by a single space"

**Comment by mrrosen** [comment]
@carlescufi I agree the documentation should be changed; just making sure I fully understand all the way to set `CONF_FILE` so I update it correctly.

One question I do have is whether or not a single spaced list is actually a good way to go about it rather than a semi-colon separated list (ie "file1.conf;file2.conf;file3.conf" instead of "file1.conf file2.conf file3.conf"). Eliminating spaces would also make paths containing spaces work as well (though I dont know if that would actually work with the rest of the build system) at the cost of backwards compatibility.

**Comment by carlescufi** [comment]
@mrrosen I do not know if there were any reasons for selecting spaces over semicolons in the first place. I think @mbolivar might be able to weigh in here.

**Comment by carlescufi** [comment]
@mrrosen regardless of the doc update (which could actually come in a second PR since the doc would not be wrong in the meantime) you need to add a body to your commit message to pass CI.

**Comment by mrrosen** [comment]
@carlescufi I modified the commit to have a body; as for the documentation and possible changing the style of `CONF_FILE` to use semicolon instead of space, should we make a thread on the devel mailing list, an issue or keep the discussion in this PR?

**Comment by mbolivar** [comment]
> @mrrosen I do not know if there were any reasons for selecting spaces over semicolons in the first place. I think @mbolivar might be able to weigh in here.

Historical reasons.  That's the way the Makefiles used to work.

**Comment by carlescufi** [comment]
@mrrosen I would just document that both are accepted by the build system and let the user choose between spaces or semicolons

**Comment by mrrosen** [comment]
@carlescufi I can do that; though the reason I bring it up is that if you allow both, it means your file paths cannot have spaces (or maybe you just have to properly escape them?), enforcing semicolons only seems to be a common why of listing files/paths.

**Review by dbkinder — APPROVED** [review]
OK

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
