### PR TITLE
doc: mem_mgmt: fix mem_non_cacheable code

### PR DESCRIPTION
**Pull request by butok**
Fix the mem_non_cacheable code according its comment.

### CODE REVIEW

**Comment by butok** [comment]
@kartben it looks like an issue in the doc CI.

**Review by dcpleung — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
> @kartben it looks like an issue in the doc CI.

re-triggering the job did the trick. Thanks!

**Comment by butok** [comment]
> > @kartben it looks like an issue in the doc CI.
> 
> re-triggering the job did the trick. Thanks!

Hi @kartben
Could you suggest how to do the re-triggering, for a next time? I do not want to disturb you for the CI fails.

**Comment by kartben** [comment]
@butok not sure if you have permissions for that but you should typically see a button to re-run failed jobs on the job's status page e.g. https://github.com/zephyrproject-rtos/zephyr/actions/runs/9644508172

**Pull request merged**
