### PR TITLE
drivers: audio: mpxxdtyy: Handle PCM block sizes of more than 1 ms

### LINKED ISSUE #69447: drivers: audio: mpxxdtyy: Driver is only able to handle PCM block size of 1 ms
**Describe the bug**
The DMIC driver API allows the user to choose an arbitrary PCM block size, as demonstrated by the sample at `samples/drivers/audio/dmic`. However, the `mpxxdtyy` microphone drivers only work properly when the PCM block size is equal to 1 millisecond of audio (for a sampling frequency of 16 kHz, this is 16 samples or 32 bytes).  Otherwise, only the first millisecond of each PCM block contains the audio signal, and the rest are garbage values.

The issue is caused by the PDM to PCM filtering layer. The functions `Open_PDM_Filter_64()` and `Open_PDM_Filter_128()`, part of the OpenPDMFilter library, do not take a signal length parameter and process a fixed length of 1 millisecond of audio.

Since I assume that this is the intended behavior of the OpenPDMFilter library, a potential workaround would be to call the filtering function multiple times for each PDM/PCM block in the `mpxxdtyy` driver, once for each millisecond of audio.

**To Reproduce**
Build and run the sample at `samples/drivers/audio/dmic` with a MPxxDTyy microphone connected to the I2S bus and inspect the PCM blocks returned by `dmic_read()`.

**Expected behavior**
The PCM blocks should contain the audio signal acquired from the microphone, regardless of the block size.

### PR DESCRIPTION
**Pull request by petarsusac**
The `Open_PDM_Filter_64()/Open_PDM_Filter_128()` functions of the third-party OpenPDMFilter library are designed to handle a fixed PCM block size of 1 ms of audio. This PR allows the MPxxDTyy drivers to use a block size of more than 1 ms by calling the filtering function multiple times, once for each ms of audio.

The fix was only tested for the mono audio case (tested on the STM32 Nucleo-F746ZG development board with a CCA02M2 microphone shield), however it should work for the stereo case as well.

Fixes zephyrproject-rtos/zephyr#69447

### CODE REVIEW

**Review by avisconti — DISMISSED** [review]
Not too easy to understand pdm buffer displacement, but seems ok. And I know you tested it...

**Comment by kartben** [comment]
> Not too easy to understand pdm buffer displacement, but seems ok. And I know you tested it...

It probably wouldn't hurt to try to add some comments in the code?

**Comment by avisconti** [comment]
> > Not too easy to understand pdm buffer displacement, but seems ok. And I know you tested it...
> 
> It probably wouldn't hurt to try to add some comments in the code?

Yeah, it would be nice!
@petarsusac can you just add a comment? Thanks

**Comment by petarsusac** [comment]
@avisconti @kartben thank you for your suggestions. I have added a comment explaining how the PDM buffer offset is calculated. Let me know if the explanation is not clear enough. I also rearranged the enclosing switch/case statement to avoid code duplication. 

Also, I noticed and fixed a mistake in the PDM offset calculation which only affected the stereo case. Since I am still working on a setup with two microphones so I can test stereo audio acquisition, could I ask you to take a look at the latest changes and check if my logic is correct even in that case?

**Comment by avisconti** [comment]
> > @avisconti @kartben thank you for your suggestions. I have added a comment explaining how the PDM buffer offset is calculated. Let me know if the explanation is not clear enough. I also rearranged the enclosing switch/case statement to avoid code duplication.
> > Also, I noticed and fixed a mistake in the PDM offset calculation which only affected the stereo case. Since I am still working on a setup with two microphones so I can test stereo audio acquisition, could I ask you to take a look at the latest changes and check if my logic is correct even in that case?
> 
> The code seems correct to me. However, I didn't even notice the issue you are talking about, so I'm not sure if it is ok in mono case...
> 
> I like the way you have also re-arrange the code. May I suggest one more improvements? Maybe we can define an array of library conversions routines, something like
> 
> ```
> struct {
>       *lib_api (uint8_t* data, uint16_t* dataOut, uint16_t volume, TPDMFilter_InitStruct *Param);
> } pdm_filter_api[2] = {
>     Open_PDM_Filter_64 (uint8_t* data, uint16_t* dataOut, uint16_t volume, TPDMFilter_InitStruct *Param);
>     Open_PDM_Filter_128 (uint8_t* data, uint16_t* dataOut, uint16_t volume, TPDMFilter_InitStruct *Param);
> };
> ```
> 
> and then call only once lib_api[idx] with proper idx. It's just brainstorming, sorry.

@petarsusac , never mind. I think ikt's ok like this

**Review by avisconti — DISMISSED** [review]

**Comment by petarsusac** [comment]
> I like the way you have also re-arrange the code. May I suggest one more improvements? Maybe we can define an array of library conversions routines, something like
> 
> ```
> struct {
>       *lib_api (uint8_t* data, uint16_t* dataOut, uint16_t volume, TPDMFilter_InitStruct *Param);
> } pdm_filter_api[2] = {
>     Open_PDM_Filter_64 (uint8_t* data, uint16_t* dataOut, uint16_t volume, TPDMFilter_InitStruct *Param);
>     Open_PDM_Filter_128 (uint8_t* data, uint16_t* dataOut, uint16_t volume, TPDMFilter_InitStruct *Param);
> };
> ```
> 
> and then call only once lib_api[idx] with proper idx. It's just brainstorming, sorry.

I like this idea, but I think it might be out of scope for this PR. Maybe I can get it done in a separate PR once this is merged?

**Review by avisconti — APPROVED** [review]

**Comment by avisconti** [comment]
@fabiobaltieri I know you are very active in many sectors of zephyr. May you possibly take a look to this fix as well? Thanks!

**Review by kv2019i — APPROVED** [review]
Not familiar with the hardware at all, but code seems legit and given this is ok @avisconti , fine for me as well.

**Pull request merged**
