### PR TITLE
bluetooth: host: Add callback to notify of RPA changes

### PR DESCRIPTION
**Pull request by fnde-ot**
Add a callback to be called any time the random private address
is modified, so to notify the application of any changes.

Signed-off-by: François Delawarde <fnde@oticon.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
How does this handle controller-side privacy, i.e. when the controller is responsible for generating the RPA? There doesn't seem to be any mention in the PR description, documentation, or Kconfig dependencies, that this is limited to host-side privacy.

**Comment by fnde-ot** [comment]
> How does this handle controller-side privacy, i.e. when the controller is responsible for generating the RPA? There doesn't seem to be any mention in the PR description, documentation, or Kconfig dependencies, that this is limited to host-side privacy.

Good point, ideally I would like for this to also work also when controller-side privacy is enabled. I will try to find out where is the ideal place to setup this callback so it works in both cases..

**Comment by joerchan** [comment]
@fnde-ot As Johan pointed out there is also the controller-based privacy RPAs, and there is not one address, but one address per entry in the resolving list. And over HCI there is no way to be notified about the RPA timeout.

Can I ask what is the intended use-case for this feature? We have ways of getting the RPA for certain use-cases.

**Comment by fnde-ot** [comment]
@joerchan That's right, and I don't see any easy way to do what we want.

Use-case is mostly to obtain the RPA used in advertisement PDUs for testing. That said, having knowledge about the advertisement RPA in the application layer could make for interesting use-cases if we could share it to other devices using OOB methods.

**Comment by fnde-ot** [comment]
Closing PR, this is not the right approach nor the right time to do this.

**Pull request closed without merging**
