### PR TITLE
input: convert xpt2046 from kscan

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Convert the XPT2046 driver to the input subsystem.

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
@SeppoTakalo I don't have any hardware to test this and there's no board with it, I added it to the `build_all` target so it's built tested but you could give it a try?

**Review by gmarull — APPROVED** [review]

**Comment by SeppoTakalo** [comment]
How is this supposed to be tested?
I only used it through LVGL module, but is it not refactored yet?

```
modules/lvgl/lib..__modules__lib__gui__lvgl__zephyr.a(lvgl.c.obj): in function `z_impl_kscan_enable_callback':
/Users/st/src/ncs/zephyr/include/zephyr/drivers/kscan.h:108: undefined reference to `__device_dts_ord_99'
```

**Comment by SeppoTakalo** [comment]
At least according to LOG output, it seem to react OK:
```
[00:00:13.138,336] <dbg> xpt2046: xpt2046_work_handler: raw: x=1535 y= 643 ==> x=   0 y=   7
[00:00:13.432,739] <dbg> xpt2046: xpt2046_work_handler: raw: x=2299 y= 970 ==> x=  45 y=  61
[00:00:13.434,509] <dbg> xpt2046: xpt2046_work_handler: raw: x=2413 y=1044 ==> x=  63 y=  73
[00:00:13.929,046] <dbg> xpt2046: xpt2046_work_handler: raw: x=1408 y= 592 ==> x=   0 y=   0
[00:00:13.930,725] <dbg> xpt2046: xpt2046_work_handler: raw: x=1897 y= 791 ==> x=   0 y=  31
[00:00:13.934,844] <dbg> xpt2046: xpt2046_work_handler: raw: x=1652 y= 695 ==> x=   0 y=  15
[00:00:14.005,432] <dbg> xpt2046: xpt2046_work_handler: raw: x=1733 y= 748 ==> x=   0 y=  24
[00:00:14.932,067] <dbg> xpt2046: xpt2046_work_handler: raw: x=1791 y= 627 ==> x=   0 y=   4
[00:00:15.239,227] <dbg> xpt2046: xpt2046_work_handler: raw: x=1853 y= 786 ==> x=   0 y=  30
[00:00:17.728,912] <dbg> xpt2046: xpt2046_work_handler: raw: x=3691 y=3386 ==> x= 258 y= 461
[00:00:17.962,127] <dbg> xpt2046: xpt2046_work_handler: raw: x=4017 y=3006 ==> x= 308 y= 398
[00:00:21.735,870] <dbg> xpt2046: xpt2046_work_handler: raw: x=3925 y=3232 ==> x= 294 y= 435
[00:00:21.979,125] <dbg> xpt2046: xpt2046_work_handler: raw: x=3951 y=3124 ==> x= 298 y= 417
[00:00:23.276,367] <dbg> xpt2046: xpt2046_work_handler: raw: x=4031 y=3192 ==> x= 310 y= 429
[00:00:23.577,209] <dbg> xpt2046: xpt2046_work_handler: raw: x=4050 y=3168 ==> x= 313 y= 425
```

Few touches on top left corner and then few touches to bottom right.
But I have nothing that uses the input subsystem... I assume this is still OK.

**Review by SeppoTakalo — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> How is this supposed to be tested? I only used it through LVGL module, but is it not refactored yet?
> 
> ```
> modules/lvgl/lib..__modules__lib__gui__lvgl__zephyr.a(lvgl.c.obj): in function `z_impl_kscan_enable_callback':
> /Users/st/src/ncs/zephyr/include/zephyr/drivers/kscan.h:108: undefined reference to `__device_dts_ord_99'
> ```

Yeah for LVGL right know you'd have to enable both `CONFIG_KSCAN` and `CONFIG_INPUT`  and modify the devicetree entry to add the compatibility device, see https://docs.zephyrproject.org/latest/services/input/index.html#kscan-compatibility for an example.

It should be fine if you got those messages, they are at the same spot where the events are sent so it should be all good. Thanks!

**Pull request merged**
