### PR TITLE
arch: xtensa: change syscall exception message handling

### PR DESCRIPTION
**Pull request by sylvioalves**

### CODE REVIEW

**Comment by sylvioalves** [comment]
@andyross @dcpleung This PR is related to #68524. Would be good some input from you. Thanks.

**Review by dcpleung — COMMENTED** [review]
Hm... this is supposed to be an error because we don't have code to handle syscalls if userspace is not enabled. IMHO, picolib doing syscall for NOP is weird.

**Review by uLipe — APPROVED** [review]

**Comment by dcpleung** [comment]
From I have seen in the bug report, it is a picolibc problem as it is treating a call to simulator (`SYS_nop` as defined in `simcall.h`) as if it is a syscall (`SIM` vs `SYS`). They need to remove the `syscall` instruction.

**Comment by sylvioalves** [comment]
> From I have seen in the bug report, it is a picolibc problem as it is treating a call to simulator (`SYS_nop` as defined in `simcall.h`) as if it is a syscall (`SIM` vs `SYS`). They need to remove the `syscall` instruction.

To be honest I don't see how this is linked to libc as this is related to xtensa architecture. Anyway, the same "issue" also happens when using MINIMAL_LIBC or NEWLIB_LIBC. Any fix in PICOLIBC would be required in others as well.

**Review by andyross — APPROVED** [review]
Could just remove it entirely.   There's a "real" syscall handler in place for userspace now, and this is just a stub leftover from very early platform bringup.

**Comment by dcpleung** [comment]
> > From I have seen in the bug report, it is a picolibc problem as it is treating a call to simulator (`SYS_nop` as defined in `simcall.h`) as if it is a syscall (`SIM` vs `SYS`). They need to remove the `syscall` instruction.
> 
> To be honest I don't see how this is linked to libc as this is related to xtensa architecture. Anyway, the same "issue" also happens when using MINIMAL_LIBC or NEWLIB_LIBC. Any fix in PICOLIBC would be required in others as well.

??? Where is this `syscall` instruction coming from? One shouldn't be using `syscall` if there is no handler for them.

**Comment by sylvioalves** [comment]
> > > From I have seen in the bug report, it is a picolibc problem as it is treating a call to simulator (`SYS_nop` as defined in `simcall.h`) as if it is a syscall (`SIM` vs `SYS`). They need to remove the `syscall` instruction.
> > 
> > 
> > To be honest I don't see how this is linked to libc as this is related to xtensa architecture. Anyway, the same "issue" also happens when using MINIMAL_LIBC or NEWLIB_LIBC. Any fix in PICOLIBC would be required in others as well.
> 
> ??? Where is this `syscall` instruction coming from? One shouldn't be using `syscall` if there is no handler for them.

I might have mistakenly written "not linked to libc". Well, it is due to `setjmp` call as reported. And that call triggers syscall expection.  The point is whether we should handle it as `LOG_ERR` or not. I agree with @andyross comment above.

**Comment by dcpleung** [comment]
Aside from the syscall instruction issue... even if you change it to `LOG_DBG`, increasing logging level to debug will still trigger the issue. From my point of view, this is just hiding the issue and defers to the next person to deal with it.

Can't think of a good way forward for now. If you want to avoid the issue at all, you need to remove the log line. However, removing the log line hides that there is a `syscall` somewhere not being handled. Hm...

**Comment by andyross** [comment]
Yeah, the root cause here turns out to be a ton more complicated.  See comment in linked bug.  Still no reason not to merge this patch though, which is perfectly benign and probably a better choice for all apps.

**Comment by dcpleung** [comment]
The only problem I have is that... increasing logging level will result in the error resurfacing again. Which is going to be very confusing to developers and even might make them think it's an issue with the logging subsys (which is definitely not).

**Comment by sylvioalves** [comment]
@andyross, thanks for the whole analysis, very interesting.  
@dcpleung I guess this would confuse any xtensa's arch SoC whenever 'setjmp' is called (when syscall is triggered). Anyway, from my perspective, having some ERR log in my screen is not that same as DEBUG logging.   

So, my conclusion is:  
1. Keep as is and close the issue.  
2. Change the log output to inform that syscall exception handler was called (but not throwing error-message-dump-like).  
3. Remove all logging output.

**Comment by dcpleung** [comment]
TBH, from my point of view, it should be an error as you are using syscall where there is no handler implemented. Changing it to `LOG_DBG` is simply hiding an error.

However, the real issue is here is the syscall with `SYS_nop` (or rather value 0). So to proper fix the issue, the caller must be modified to not emit syscall. And the fix should not be hiding the error.

**Pull request closed without merging**
