### PR TITLE
drivers:ethernet:eth_w5500 fixes,command read_back/reset pin toggle

### LINKED ISSUE #29013: [Coverity CID :214870] Untrusted loop bound in drivers/ethernet/eth_w5500.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/ethernet/eth_w5500.c

Category: Insecure data handling
Function: `w5500_rx`
Component: Drivers
CID: [214870](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=214870)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by Hari-haranb**
added changes for eth_w5500  command read back  and change from k_sleep to k_busy_wait
which will allow other threads to wakeup.
added  toggle reset gpio in w5500_init function

coverity CID:214870

### CODE REVIEW

**Review by parthitce — APPROVED** [review]
LGTM

**Review by rlubos — APPROVED** [review]

**Comment by lucasgcbkhomp** [comment]
@parthitce I've been keeping an eye on the W5500 driver and tested this on my setup, the following line during initialization causes the interface to lock up and emmit a `Failed to read from RTR register` and have the module kill itself.

https://github.com/zephyrproject-rtos/zephyr/blob/0a758c36c864cc138941848f42c8ea4aa7dc95b3/drivers/ethernet/eth_w5500.c#L511

Is it a problem with this code or is it relying on something else that got updated elsewhere? I had to remove that line for a fork I'm making.

**Comment by parthitce** [comment]
@Hari-haranb Could you please verity the deadlock from your end? IMO this shouldn't block as the sleep time after pulling low is as per the datasheet.

**Comment by lucasgcbkhomp** [comment]
> @Hari-haranb Could you please verity the deadlock from your end? IMO this shouldn't block as the sleep time after pulling low is as per the datasheet.

@parthitce @carlescufi Please consider reverting this PR in the meantime. It's a dubious change, and there is no Issue thread detailing what exactly it's trying to fix for anybody else to chime in.

As I'm meant to guess, the way it is now tells me that the author uses `GPIO_ACTIVE_HIGH` for the reset pin on the board they developed, which will actually result in the same RTR read problem in the previous driver version. They then modified the initialization by getting the reset pin be in an [inverse state from the way it was before](https://github.com/zephyrproject-rtos/zephyr/pull/46139/files#diff-4f94d6b5c5958ba15b8eaccbe1fc763fcf066ac537fe22df2972b78075f7d2a0L510-R511). When I change my own board's `.dst` to reset `GPIO_ACTIVE_HIGH`, it works like it used to. If this guess is correct then this change is currently going [against the documentation](https://docs.zephyrproject.org/3.0.0/reference/devicetree/bindings/ethernet/wiznet%2Cw5500.html) and is most likely going to break every other board application using this driver. 

The [previous PR](https://github.com/zephyrproject-rtos/zephyr/pull/45765) to this driver had quite a few people (including me) discussing the reproducible problems at length as well as testing multiple possible solutions before anything got in. This change has had neither and personally I don't know what the rest of the included changes are doing since there's nothing provided to reproduce and test them against.

**Comment by honestech74** [comment]
@carlescufi @parthitce @Hari-haranb  I agreed with @lucasgcbkhomp. It doesn't work for me either. A few people(including me and @lucasgcbkhomp) met the deadlock and we were happy with #45765 (took a long time to test it). I think it might have to be reverted to the previous PR. Also as @lucasgcbkhomp mentioned, there is no issue related to this PR.

**Pull request merged**
