### PR TITLE
LE Audio: Broadcast audio test update

### LINKED ISSUE #44944: LE Audio: Add ISO part to broadcast audio bsim tests
**Is your enhancement proposal related to a problem? Please describe.**
Broadcast ISO should be working in the babblesim now, and as such the broadcast audio bsim tests can be expanded upon to fully utilize the API. 

**Describe the solution you'd like**
The babblesim tests need to fully use the API including creating and syncing to the BIG. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Updates the broadcast audio babblesim tests to use ISO, as well as fixing a few bugs found along the way. 

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/44944

### CODE REVIEW

**Comment by Thalley** [comment]
Updated to resolve merge conflicts

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by MariuszSkamra — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts and fix https://github.com/zephyrproject-rtos/zephyr/pull/46204#discussion_r914560169

**Review by asbjornsabo — APPROVED** [review]
LGTM

**Review by MariuszSkamra — APPROVED** [review]

**Pull request merged**
