### PR TITLE
net: gptp_md: Fix correction field resolution

### PR DESCRIPTION
**Pull request by MartinFletzer**
Fix time resolution for assignmend of follow_up_correction_field.

Signed-off-by: Martin Fletzer <martin.fletzer@kftec.at>

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Could you elaborate the commit message more, now it does not explain why we are changing the code.

**Comment by MartinFletzer** [comment]
From https://www.ieee802.org/1/files/public/docs2007/as-garner-protocol-state-machines-frame-formats-0307.pdf: The correctionField is the value of the correction measured in nanoseconds and multiplied by 2^16. 
And Zephyr uses just nanoseconds for gptp_md_sync_info::follow_up_correction_field. Because of this, in file gptp_md.c in line 53/54 hdr->correction_field is shifted left by 16 to convert the value of gptp_hdr::correction_field for a ptp network packet.

Should I just expand the commit message, or does the patch need rework in general?

**Comment by jukkar** [comment]
Please update the commit message with the text you wrote above, and force push a new version. It is nice to have proper commit message that tells **why** some change is done, it helps later if one wants to figure out what some patch is doing with the code. I have no problem with the actual change.

**Comment by rlubos** [comment]
@MartinFletzer The commit message lines are too lengthy, please refactor them:
> 4: UC4 Line exceeds max length (100>75): "  The correctionField is the value of the correction measured in nanoseconds and multiplied by 2^16."
5: UC4 Line exceeds max length (79>75): "Zephyr uses just nanoseconds for gptp_md_sync_info::follow_up_correction_field."
6: UC4 Line exceeds max length (76>75): "Therefore the value must be shifted by 2^16 when reading the network packet."

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
