### PR TITLE
net: dns: Make dispatcher check also network interface

### PR DESCRIPTION
**Pull request by jukkar**
As the DNS might listen to multicast addresses (like in mDNS) in different network interfaces, make sure to check the network interface index when registering the dispatcher context. This allows two mDNS registrations to more than one network interface.

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Comment by jukkar** [comment]
Noticed extra issues after proper testing

**Comment by kica-z** [comment]
I think the code: 
```c
if (ctx->sock == entry->sock) {
	if (found == NULL) {
		found = entry;
	} else {
		dup = true;
	}
	continue;
}
```
would also work but the file descriptor handling and back-linking would still be necessary (i guess, i am still figuring out what that part does). Also semantically the approach with the interface id makes more sense.

**Comment by kica-z** [comment]
@jukkar I am still not sure why the separate `ipv6_fds` and `ipv4_fds` arrays are necessary. Couldn't the `mdns_responder_context` be adjusted to hold as many fds as there are interfaces? Then the old way of using the context would still work right?

**Review by rlubos — APPROVED** [review]

**Comment by jukkar** [comment]
> I am still not sure why the separate `ipv6_fds` and `ipv4_fds` arrays are necessary. Couldn't the `mdns_responder_context` be adjusted to hold as many fds as there are interfaces? Then the old way of using the context would still work right?

The two arrays are related how socket services api work. We have two socket service context structs in mdns, one for IPv4 and one for IPv6. When those socket service contexts are registered, the socket services API needs to know what file descriptors it needs to monitor in one array. This is what the `ipv6_fds` and `ipv4_fds` are for. The `mdns_responder_context` contains information about one mdns listener, it cannot contain information about all the interfaces.

**Review by pdgendt — APPROVED** [review]

**Comment by kica-z** [comment]
But as far as I can see you set the same content within the `ctx` as well as the `ipv4/6_fds` so why does the old code no longer work? There are as many contexts as there are interfaces after all. - Sorry if i am missing something obvious.
```c
ctx->dispatcher.fds = ctx->fds;
ctx->dispatcher.fds_len = ARRAY_SIZE(ctx->fds);
```

**Comment by jukkar** [comment]
> But as far as I can see you set the same content within the `ctx` as well as the `ipv4/6_fds` so why does the old code no longer work? There are as many contexts as there are interfaces after all. - Sorry if i am missing something obvious.
> 
> ```c
> ctx->dispatcher.fds = ctx->fds;
> ctx->dispatcher.fds_len = ARRAY_SIZE(ctx->fds);
> ```

This function is called multiple times but with the same `ctx`, the latter calls will overwrite the `ctx->dispatcher.fds` with new value which means that the we effectively only listen on the last socket. This was not a problem earlier when the system was monitoring only one interface (because of other bug), but now it is because the other problem was solved in previous commit.

**Comment by kica-z** [comment]
But istn't there one ctx per interface (array size `v4_ctx` is `MAX_IPV4_IFACE_COUNT`)? And as far as i can see for each `ctx` the function `register_dispatcher` is only called once. Did i miss something here?

**Comment by kica-z** [comment]
> Note that there are two different contexts here. Each dispatcher context (`struct mdns_responder_context`) has one socket that it is interested in. But all IPv4 sockets share the same socket_service context (`v4_svc` variable) and that one expects the polled socket descriptors in one array. Similar thing for IPv6 sockets. So we collect the polled sockets in one array. You can see this easily by `net sockets` shell command if you do not apply the commit `net: mdns_responder: Register properly multiple sockets`. In that case there is only one socket listed in the output, the other ones have -1 as a socket descriptor.

@jukkar Thanks for the explanation 👍

**Pull request merged**
