### PR TITLE
Adding support for adafruit can picowbell for rpi_pico

### PR DESCRIPTION
**Pull request by joeker64**

### CODE REVIEW

**Review by kartben — CHANGES_REQUESTED** [review]
Very cool, thanks for taking the time to submit this PR! Could you please also update the documentation page to add info for this new shield (+picture)

**Comment by joeker64** [comment]
> Very cool, thanks for taking the time to submit this PR! Could you please also update the documentation page to add info for this new shield (+picture)

Will do thanks, also accidentally clicked for re-review so just ignore that :)

**Comment by joeker64** [comment]
Rebased commit and now have updated the documentation

**Comment by kartben** [comment]
@joeker64 I know you've already opened a new PR, but typically you shouldn't need to, as pretty much any mistake can be fixed by force-pushing to the branch.
Could you please address the review comments from this PR in the new one (I see that you already fixed the image size, thx!)

**Comment by joeker64** [comment]
I accidentally included other commits in the rebase so just panicked and closed the pull to do a fresh restart. I'll apply the updates now

**Pull request closed without merging**
