### PR TITLE
WIP: update clang-format for Zephyr

### PR DESCRIPTION
**Pull request by pabigot**
The goal of #21392 to be able to reduce arguments about style by establishing a baseline policy: if the file content is left unmodified by clang-format, the style is acceptable.  Released versions of clang-format lack a configuration option required by Zephyr's style.

clang-format-12 (expected for release this fall) eliminates this gap by adding an option for `SpaceBeforeParens` that does not introduce a space in `FOR_EACH` control macro expressions like:

    SYS_SLIST_FOR_EACH_CONTAINER_SAFE(&dlci_active_t1_timers, dlci, next, node) { ... }

This branch updates the in-tree `.clang-format`, which tracks the Linux one, to:
* enable the options that were disabled because they were unavailable to clang-format-4 or clang-format-5
* add Zephyr-specific options not yet upstream (ATT only `SpaceBeforeParens: ControlStatementsExceptForEachMacros`
* additional updates to remain in sync with Linux

If you are interested in evaluating clang-format as an alternative to uncrustify please try the version in this branch, and propose changes to the configuration, so when clang-12 is released we're able to make progress on #21392.

### CODE REVIEW

**Comment by pabigot** [comment]
[git-clang-format](https://github.com/llvm/llvm-project/blob/master/clang/tools/clang-format/git-clang-format) is intended to support checking conformance of changes.  I'll be evaluating this over the next couple months.

**Comment by galak** [comment]
Do you know if there is ubuntu package or pre-built binary for the clang-format v12?

**Comment by pabigot** [comment]
> Do you know if there is ubuntu package or pre-built binary for the clang-format v12?

Probably not, since 12 is the next release of the entire system.  I did something like the following.

```
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
mkdir build && cd build
TAG=$(git describe --tags)-$(date +%Y%m%d)
cmake -G Ninja \
  -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi" \
  -DCMAKE_INSTALL_PREFIX=/usr/local/llvm-${TAG} \
  -DCMAKE_BUILD_TYPE=Release \
  ../llvm \
  2>&1 | tee cmo
ninja
ninja install
cd /usr/local
rm -f llvm
ln -s llvm-${TAG} llvm
cd bin
ln -s ../llvm/bin/clang-format
```

**Comment by chrta** [comment]
> Do you know if there is ubuntu package or pre-built binary for the clang-format v12?

It is available in the llvm apt repo now, e.g. for focal via `deb http://apt.llvm.org/focal/ llvm-toolchain-focal main`, see https://apt.llvm.org/

**Comment by pabigot** [comment]
I have no plans to do more with this, so whoever wants to take it on is free to do so.

**Pull request closed without merging**
