### PR TITLE
stm32h7 series - remove explicit fullibc selection

### PR DESCRIPTION
**Pull request by KozhinovAlexander**
Remove explicit fullibc support since same approach used by `stm32f7` series. 

Partially solves #27373

### CODE REVIEW

**Comment by Nukersson** [comment]
@ABOSTM @gmarull @carlescufi Please provide your expert opinion.

**Comment by Nukersson** [comment]
The open questions from @ABOSTM are:

> > soc/arm/st_stm32f7/stm32f7/Kconfig.series - does not contain REQUIRES_FULL_LIBC also
> 
> That doesn't mean H7 don't require it. There may be other solutions that keep REQUIRES_FULL_LIBC and remove your errors ...
> My understanding is that there are 2 issues:
> 
> 1. The warning which comes from the fact that the test defines CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE (prj.conf)  even when not needed (when REQUIRES_FULL_LIBC is defined). This could for example be solved by changing the sample.
> 2. The compilation error. This look to me like the test is not designed to work with the full LibC.
>    So now,
> 
> * should we adapt the sample to work with both non-full and full libC?
> * exclude the board for this test (as it is not compatible with full libC)?
> * or change the driver to not use the Full LibC (like you proposed) ?
>   Honestly I don't know. And prefer to open the discussion.
> 
> > And you will see which impact explicit select of `REQUIRES_FULL_LIBC` has on this sample
> 
> My concern is not about this sample, but about the impact on all others samples and tests.
> I want to avoid regressions.

**Comment by gmarull** [comment]
@Nukersson This change LGTM. After looking in detail, I don't see any reason why soc Kconfig selects this setting, in fact it's the only soc doing that. Could you adjust commit message to be more clear, e.g. `soc: arm: stm32h7: remove explicit full libc selection`?

**Comment by Nukersson** [comment]
> @Nukersson This change LGTM. After looking in detail, I don't see any reason why soc Kconfig selects this setting, in fact it's the only soc doing that. Could you adjust commit message to be more clear, e.g. `soc: arm: stm32h7: remove explicit full libc selection`?

@gmarull Done as proposed.

**Comment by Nukersson** [comment]
@ABOSTM @erwango Please see the comment above from @gmarull. I hope, it can clarify, why I am proposing this change.

**Review by gmarull — APPROVED** [review]
LGTM

**Comment by ABOSTM** [comment]
I am sorry, no time today, it is my turn to leave for vacations, 2 weeks  :-)

**Comment by Nukersson** [comment]
> I am sorry, no time today, it is my turn to leave for vacations, 2 weeks :-)

Wish you great vacations! Hope @gmarull can do the review.

**Review by carlescufi — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
