### PR TITLE
drivers: arm: stm32: adc: Added Shared IRQ

### PR DESCRIPTION
**Pull request by ycsin**
Cherry picked #37585, some modifications to resolve merge conflict due to 93956b207386d1833d162c3ee9b71c6bd8a81da3, b0cdef3c25c2ac92627f158700efdb9203ecb51a

⚠ untested code

CC @mcscholtz

### CODE REVIEW

**Comment by ycsin** [comment]
Ops, sorry for the noise

**Review by erwango — APPROVED** [review]
Thanks @ycsin for taking this
Approved as I can see that, aside required rebase changes, this is the same code as #37585 which was reviewed and approved.

**Comment by mcscholtz** [comment]
Thanks @ycsin for taking this. 

Due to part shortages we had to switch parts and can no longer spend any time on this. Sorry for my lack of communications.

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
