### PR TITLE
GSM modem support for particle_boron board

### PR DESCRIPTION
**Pull request by jukkar**
I was not able to fully test this as the board was constantly crashing shortly after boot. I also saw crashes without these patches so the culprit is most likely elsewhere.

### CODE REVIEW

**Review by pfl — APPROVED** [review]

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by jukkar** [comment]
Postponing this to 2.3 in order to do more testing with this board.

**Review by carlescufi — APPROVED** [review]

**Comment by jukkar** [comment]
Requires more TLC, I removed the milestone as this might not make to 2.3

**Comment by WilliamGFish** [comment]
Is this still an active PR? If so I may be able to attempt to test.

**Comment by jukkar** [comment]
> Is this still an active PR? If so I may be able to attempt to test.

I got sidetracked with other tasks so this has not been progressing lately. It would be great if you can try it and give feedback.

**Comment by 24601** [comment]
Anything a person who wants to see this work can help with? Would love to see this working.

**Comment by jukkar** [comment]
> Anything a person who wants to see this work can help with? Would love to see this working/merged.

It would be greatl if more testing is done, and as there is probably changes required, a PR fixing the issues would be nice too (but not mandatory).

**Comment by WilliamGFish** [comment]
Okay, I think there are two issues:
1. The device definition has an error, should be:
```
DEVICE_DEFINE(gsm_ppp, GSM_MODEM_DEVICE_NAME, gsm_init,device_pm_control_nop, &gsm, NULL,
	      POST_KERNEL, CONFIG_MODEM_GSM_INIT_PRIORITY, NULL);

```
The change get the device to 'boot' without errors but never starts.


2. The other is the modem has not be "powered-up" as the gpio pin haven't been initialised 
Not sure how best to address this whilst being flexible.
 
Billy..

**Comment by jukkar** [comment]
> I think there are two issues:
> 
>     1. The device definition has an error, should be:
> 
> 
> ```
> DEVICE_DEFINE(gsm_ppp, GSM_MODEM_DEVICE_NAME, gsm_init,device_pm_control_nop, &gsm, NULL,
> 	      POST_KERNEL, CONFIG_MODEM_GSM_INIT_PRIORITY, NULL);
> ```

Hmm, indeed. It seems that commit 5e97d779bba79653a4df3273c918aa3bbe9c7ddf converted earlier `DEVICE_INIT()` to `DEVICE_DEFINE()` incorrectly. I will send a fix for this. Thanks for the info.

**Comment by jukkar** [comment]
> I will send a fix for this

Fix at #30047

**Comment by WilliamGFish** [comment]
> > I will send a fix for this
> 
> Fix at #30047

I've managed to get the Ublox modem working as PPP but its very messy at the moment. I'll look to tidy up in the next few days.

TLS is not working but it appears the non-secure sockets are just fine.

Will..

**Comment by jukkar** [comment]
> Ublox modem working as PPP

That is very good news, thanks for working on this! :+1:

**Pull request closed without merging**
