### PR TITLE
dts: stm32f429vX: Fix delete-node syntax

### PR DESCRIPTION
**Pull request by ydamigos**
Fix delete-node syntax.

Signed-off-by: Yannis Damigos <giannis.damigos@gmail.com>

### CODE REVIEW

**Comment by ydamigos** [comment]
@DWagenk Could you also check it?

**Review by erwango — APPROVED** [review]
Thanks for this catch.
Looking in linux, it seems another fix could be removing the `&`:
``` 		/delete-node/ spi5;```

**Comment by ydamigos** [comment]
>Looking in linux, it seems another fix could be removing the &: `/delete-node/ spi5;`

I tested it and it works but I avoided it because I didn't find anything like `
/delete-node/ label;` in DT specification.

**Comment by ydamigos** [comment]
There are `/delete-node/ node-name;` and `/delete-node/ &label;` but not `/delete-node/ label;` (only label without `&`)

**Comment by DWagenk** [comment]
Looks good. Learned something new again...

**Review by nashif — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
