### PR TITLE
soc: stm32: update soc config flag to reflect flash size variant

### PR DESCRIPTION
**Pull request by erwango**
In order to to be able to distinguish flash size variants of SoCs when needed (for instance in dts/arm/st/mem.h file), rename some CONFIG_SOC_SMT32XXX flags

### CODE REVIEW

**Review by galak — COMMENTED** [review]
In commit message: stm32f429zi did you mean stm32f429xi

**Comment by erwango** [comment]
Actually I meant stm32f429zi since this is the exact soc in use in stm32f4-disco board.
Same for stm32l476rg used in nucleo_l476rg board in next commit.
For stm32f407xg, I kept the x since soc is not actually used in any board right now, it could be any package variant and I kept the mystery.

**Comment by galak** [comment]
Ok, so little confused if stm32f429zi than why use stm32f429xi in code?

**Comment by erwango** [comment]
In STM32 SoCs naming convention, first letter after chip ('z' in stm32f429zi case) is the pin package variant (32 pin, 64 72, 81, 100, 132, 144, 169....).
Since first stm32 porting this information was removed. I don't think zephyr cares about this right now, and keeping the information will add complexity in configuration, so I think we can  keep it that way.

**Review by galak — APPROVED** [review]

**Pull request merged**
