### PR TITLE
add more test on the stm32wl55 nucleo board

### PR DESCRIPTION
**Pull request by FRASTM**
this PR adds 
- tests/drivers/pwm/pwm_api/
- tests/drivers/dma/loop_transfer and tests/drivers/dma/chan_blen_transfer 

on the nucleo_wl55jc board increasing the test coverage on that target.

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
west build -p auto -b nucleo_wl55jc tests/drivers/pwm/pwm_api/
```
Running test suite pwm_basic_test
===================================================================
START - test_pwm_usec
[PWM]: 1, [period]: 2000, [pulse]: 1000
[PWM]: 1, [period]: 2000, [pulse]: 2000
[PWM]: 1, [period]: 2000, [pulse]: 0
 PASS - test_pwm_usec in 3.12 seconds
===================================================================
START - test_pwm_nsec
[PWM]: 1, [period]: 2000000, [pulse]: 1000000
[PWM]: 1, [period]: 2000000, [pulse]: 2000000
[PWM]: 1, [period]: 2000000, [pulse]: 0
 PASS - test_pwm_nsec in 3.13 seconds
===================================================================
START - test_pwm_cycle
[PWM]: 1, [period]: 64000, [pulse]: 32000                                       
[PWM]: 1, [period]: 64000, [pulse]: 64000                                       
[PWM]: 1, [period]: 64000, [pulse]: 0                                           
 PASS - test_pwm_cycle in 2.12 seconds                                          
===================================================================             
Test suite pwm_basic_test succeeded                                             
================================
```===================================             
PROJECT EXECUTION SUCCESSFUL

**Comment by FRASTM** [comment]
west build -p auto -b nucleo_wl55jc tests/drivers/dma/chan_blen_transfer
```
*** Booting Zephyr OS build zephyr-v3.0.0-361-g248433792be8  ***                
Running test suite dma_m2m_test                                                 
===================================================================             
START - test_dma_m2m_chan0_burst8                                               
Preparing DMA Controller: Chan_ID=6, BURST_LEN=1                                
Starting the transfer                                                           
DMA transfer done                                                               
It is harder to be kind than to be wise........                                 
 PASS - test_dma_m2m_chan0_burst8 in 2.13 seconds                               
===================================================================             
START - test_dma_m2m_chan1_burst8                                               
Preparing DMA Controller: Chan_ID=10, BURST_LEN=1                               
Starting the transfer                                                           
DMA transfer done                                                               
It is harder to be kind than to be wise........                                 
 PASS - test_dma_m2m_chan1_burst8 in 2.13 seconds                               
===================================================================             
START - test_dma_m2m_chan0_burst16                                              
Preparing DMA Controller: Chan_ID=6, BURST_LEN=2                                
Starting the transfer                                                           
DMA transfer done                                                               
It is harder to be kind than to be wise........                                 
 PASS - test_dma_m2m_chan0_burst16 in 2.13 seconds                              
===================================================================             
START - test_dma_m2m_chan1_burst16                                              
Preparing DMA Controller: Chan_ID=10, BURST_LEN=2                               
Starting the transfer                                                           
DMA transfer done                                                               
It is harder to be kind than to be wise........                                 
 PASS - test_dma_m2m_chan1_burst16 in 2.13 seconds                              
===================================================================             
Test suite dma_m2m_test succeeded                                               
===================================================================             
PROJECT EXECUTION SUCCESSFUL 
```

**Comment by FRASTM** [comment]
west build -p auto -b nucleo_wl55jc tests/drivers/dma/loop_transfer/
```

*** Booting Zephyr OS build zephyr-v3.0.0-361-g248433792be8  ***
Running test suite dma_m2m_loop_test
===================================================================
START - test_dma_m2m_loop
DMA memory to memory transfer started on DMAMUX_1
Preparing DMA Controller
this platform do not support the dma channel
Starting the transfer on channel 11 and waiting for 1 second
Each RX buffer should contain the full TX buffer string.
RX data Loop 0: The quick brown fox jumps over the lazy dog
RX data Loop 1: The quick brown fox jumps over the lazy dog
RX data Loop 2: The quick brown fox jumps over the lazy dog
RX data Loop 3: The quick brown fox jumps over the lazy dog
RX data Loop 4: The quick brown fox jumps over the lazy dog
Finished: DMA
 PASS - test_dma_m2m_loop in 1.49 seconds
===================================================================
START - test_dma_m2m_loop_suspend_resume
DMA memory to memory transfer started on DMAMUX_1                               
Preparing DMA Controller                                                        
this platform do not support the dma channel                                    
Starting the transfer on channel 11 and waiting for 1 second                    
Suspended transfers                                                             
dma suspend not supported                                                       
 PASS - test_dma_m2m_loop_suspend_resume in 0.21 seconds                        
===================================================================             
Test suite dma_m2m_loop_test succeeded                                          
===================================================================             
PROJECT EXECUTION SUCCESSFUL  
```

**Review by ABOSTM — DISMISSED** [review]

**Review by erwango — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Review by erwango — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/43162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmarull and @nashif)

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
