### PR TITLE
doc: add rule based page html hooks to coding guidelines

### PR DESCRIPTION
**Pull request by romkell**
Add rule based page hook to allow to jump to
the respective rule directly.

Example:

.../coding_guidelines/index.html#misrac-rule-2-2

Signed-off-by: Roman Kellner <rkellner@baumer.com>

### CODE REVIEW

**Review by mbolivar-nordic — DISMISSED** [review]

**Review by gmarull — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
@romkell please fix the compliance failure. You need to add a `Signed-off-by:` line to your commit message. See the contribution guidelines or other commit messages for examples.

**Review by stephanosio — DISMISSED** [review]
Please update either the commit author name or the sign-off name to fix the compliance check failure:

> author email (Kellner Roman <rkellner@baumer.com>) needs to match one of the signed-off-by entries.

**Comment by mbolivar-nordic** [comment]
@romkell we cannot merge this until you fix the commit message

**Comment by romkell** [comment]
> @romkell we cannot merge this until you fix the commit message

@mbolivar-nordic Changed git config settings, soft reset, re-commited with identical commit comment and force pushed. I hope that does the trick.

**Review by stephanosio — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Pull request merged**
