### PR TITLE
dts: nordic: Fix vendor prefix for flash controller

### PR DESCRIPTION
**Pull request by galak**
The vendor prefix for the flash controller should be "nordic," not
"nrf,".

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Comment by ioannisg** [comment]
@galak @anangl, for this to work, we might need to rename nrf -> nordic inside the flash-controller binding.yaml

**Comment by anangl** [comment]
> @galak @anangl, for this to work, we might need to rename nrf -> nordic inside the flash-controller binding.yaml

It is done in this PR, see [this](https://github.com/zephyrproject-rtos/zephyr/pull/12476/files#diff-088eebb73716f9310e04613815392f17R13) and [this](https://github.com/zephyrproject-rtos/zephyr/pull/12476/files#diff-fc4f3e3ba51cd2ebb6638d98590c8c47R13) change. Or did I miss something?

**Comment by ioannisg** [comment]
> 
> 
> > @galak @anangl, for this to work, we might need to rename nrf -> nordic inside the flash-controller binding.yaml
> 
> It is done in this PR, see [this](https://github.com/zephyrproject-rtos/zephyr/pull/12476/files#diff-088eebb73716f9310e04613815392f17R13) and [this](https://github.com/zephyrproject-rtos/zephyr/pull/12476/files#diff-fc4f3e3ba51cd2ebb6638d98590c8c47R13) change. Or did I miss something?

Ah you are right - i missed that. I think the error might lie in the format of flash-controller node definition in dts. I will investigate.

**Comment by ioannisg** [comment]
I pushed a commit to fix flash driver macros in dts.fixup.h
@anangl @galak please, revisit

**Review by anangl — APPROVED** [review]

**Pull request merged**
