### PR TITLE
Openocd improvements

### PR DESCRIPTION
**Pull request by mniestroj**
This PR contains two major changes:
- stop concatenating zephyr.elf file to flash commands in cmake files, use cfg.elf_file / cfg.hex_file instead; this allows to overwrite file used with either --elf-file or --hex-file,
- use hex file instead of elf file for flash command, so we can flash signed image, which is only in hex and bin format (but not in elf format).

### CODE REVIEW

**Review by mbolivar — APPROVED** [review]
This isn't exactly backwards compatible, but I agree it's an improvement. I'm +1 to get this into 2.0.

@erwango, ok for you?

**Review by carlescufi — APPROVED** [review]

**Comment by ioannisg** [comment]
@erwango could you please, take a look?

**Comment by ioannisg** [comment]
Adding 2.0 milestone, assuming that the review will be completed in-time for 2.0.

**Comment by ioannisg** [comment]
@galak @MaureenHelm FYI

**Review by galak — APPROVED** [review]

**Comment by ioannisg** [comment]
Let's get this in; if there's a need to patch it, we can do it later and @erwango gets a chance to review it

**Comment by carlescufi** [comment]
Merged as per @ioannisg comment, @erwango please review once you have a chance and we can follow-up with a bugfix.

**Pull request merged**
