### PR TITLE
 usb: move USB_DEVICE_REMOTE_WAKEUP option to drivers, remove USB_SCD_ATTRIBUTES macro

### PR DESCRIPTION
**Pull request by jfischer-no**
Remove USB_SCD_ATTRIBUTES macro.
USB_SCD_ATTRIBUTES is a configuration dependent macro
that does not map any part of the spec and does not
belong to usb_ch9 header.

Move USB_DEVICE_REMOTE_WAKEUP option to drivers.
Kconfig USB_DEVICE_REMOTE_WAKEUP option depends only on
USB device controller capability, but is not controlled
by the USB device controller drivers configuration.
Move USB_DEVICE_REMOTE_WAKEUP option to drivers and
make it promptless.

### CODE REVIEW

**Review by nvlsianpu — COMMENTED** [review]
Shouldn't USB_DEVICE_REMOTE_WAKEUP be kept selectable?
Driver might introduce a HAS_xxx property instead.

My rationale is that someone might want to disable this USB feature in aproject.

**Comment by emob-nordic** [comment]
> Shouldn't USB_DEVICE_REMOTE_WAKEUP be kept selectable? Driver might introduce a HAS_xxx property instead.
> 
> My rationale is that someone might want to disable this USB feature in aproject.

I was thinking the same way, but if the application does not wish to support this feature, it could not use it (do not call `usb_wakeup_request`). From performance perspective this change is addition of setting one bool variable instead of responding with NACK to SET/GET feature request. For `HAS_xx` i don't know.

**Comment by jfischer-no** [comment]
> Shouldn't USB_DEVICE_REMOTE_WAKEUP be kept selectable? Driver might introduce a HAS_xxx property instead.
> 
> My rationale is that someone might want to disable this USB feature in aproject.

It would not be rational to turn it off. And I do not want to complicate it unnecessarily.

**Review by eobalski — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]
> USB device may only use this feature (to wake up the host) if it is explicitly enabled by the host (Set Feature request).

I was thinking that this is working this way. Thanks for confirmation.

**Review by carlescufi — APPROVED** [review]

**Comment by ycsin** [comment]
Is there anything here (header?) that should be backported?

**Pull request merged**
