### PR TITLE
Driver: gpio: Add support of Open Drain GPIO for STM32

### PR DESCRIPTION
**Pull request by Benichou34**
Add ability to configure an output GPIO as Open Drain.
Add GPIO_OPEN_DRAIN flags for use with gpio_pin_configure.

### CODE REVIEW

**Review by mnkp — CHANGES_REQUESTED** [review]
Zephyr aims to be compatible with Linux DTS. The relevant bindings for the GPIO node are defined in [Linux's dt-bindings gpio.h](https://elixir.bootlin.com/linux/latest/source/include/dt-bindings/gpio/gpio.h). To fulfill this requirement the flag to configure open drain mode should be called GPIO_OPEN_DRAIN. `gpio_stm32.c` needs to be updated.

There is no need to modify `include/dt-bindings/gpio/gpio.h` file since there exists already PR #12651 which attempts to add the flag (along with several others).

**Comment by Benichou34** [comment]
Renamed GPIO_PUD_OPEN_DRAIN by GPIO_OPEN_DRAIN.
I waiting for PR #12651.

**Comment by erwango** [comment]
@Benichou34 

> I waiting for PR #12651.

PR #12651 has been closed. Any other plans vs current PR?

**Comment by Benichou34** [comment]
Superseded by PR #16648

**Pull request closed without merging**
