### PR TITLE
mr_canhubk3: disable FS26 SBC watchdog by default

### PR DESCRIPTION
**Pull request by manuargue**
Default to use FS26 SBC in debug mode for this board configuration and provide instructions on how to enable it when required. Having it enabled by default causes multiple test and samples failures, for instance, as a side effect of not being able to close the initialization phase within the timeout.

At the moment there is no complete driver for the FS26 SBC but only for its watchdog functionality. Keep at least some build-only tests for it.

### CODE REVIEW

**Comment by manuargue** [comment]
cc @PetervdPerk-NXP @bperseghetti

**Review by dleach02 — APPROVED** [review]

**Review by PetervdPerk-NXP — APPROVED** [review]

**Review by PetervdPerk-NXP — CHANGES_REQUESTED** [review]
When fs26 driver is disabled, then fs26 chip watchdog can still reset the chip.
Please add behaviour if zephyr wdog is disabled the fs26 also gets disabled so that watchdog doesnt reset chip.

**Comment by manuargue** [comment]
> When fs26 driver is disabled, then fs26 chip watchdog can still reset the chip.

With the changes on this PR, the FS26 needs to be started in debug mode, so there won't be a reset triggered. To use it in normal mode, the application needs to enable the FS26 wdog driver by following [these steps](https://github.com/zephyrproject-rtos/zephyr/blob/8a1cbe433e5a5d85c662b9a6fe5bc8474fababa4/boards/arm/mr_canhubk3/doc/index.rst?plain=1#L219-L232).

> Please add behaviour if zephyr wdog is disabled the fs26 also gets disabled so that watchdog doesnt reset chip.

Moving the FS26 wdog initialization from a wdog driver to a board init routine does not help with the problem, as the initialization still needs to be done and it conflicts with various tests. The concern is that the lists of tests conflicting will grow over time, and those tests would otherwise pass if the wdog initialization does not need to be done. And also the wdog driver (that does the initialization) cannot be disabled in the affected tests, otherwise it would trigger a reset as you said. Hence the reason to disable it in the default configuration.

If these changes present a usability concern, we will need to address each test separately and this would be then the justification for not disabling it in the default board config.

**Comment by PetervdPerk-NXP** [comment]
The FS26 SBC on startup has watchdog that has to disabled if you intend to not use the watchdog.

I can be turned through SPI or through the FS26 Debug mode hardaware mode.
However the FS26 debug mode iss complex to setup, you need a 12V power supply and do the jumper stuff.

In the end I want to have 3 possible behaviors

1. FS26 as a Watchdog and S32K344 has to respond to watchdog challenges
2. FS26 gets disabled on startup by the S32K344 you can do this through by writing WDW_PERIOD_DISABLE | WDW_RECOVERY_DISABLE to the WDW_DURATION on the FS26 on startup
3. A user overrides the FS26 through the jumper thus putting it in debug mode

For the out-of-the-box end-user experience 1 or 2 is acceptable, having 3 as the default is not.

**Pull request closed without merging**
