### PR TITLE
flash: stm32 l4 fix

### PR DESCRIPTION
**Pull request by jamike**
Here are fixes  on stm32l4 flash driver
flash write access on L4 64bits  fetches wrong data to write.
flash read access on l4 64 bits implements align check not needed

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Can you fix the commit message, should be something like:
'flash: stm32: ...'

**Review by galak — COMMENTED** [review]
In flash: stm32l4xx fix:..

the subject of the commit message should contain a bit of detail on what the fix or issue was.

**Review by erwango — APPROVED** [review]

**Comment by jamike** [comment]
Is something still blocking the merge ?

**Comment by galak** [comment]
Can you rebase the patches against the lastest arm branch, and cleanup the commit message a little so that the line brakes are around 70 chars, and there isn't any space before the ':'

**Comment by jamike** [comment]
Do I missed a comment ? I think it is ready for merge .

**Review by galak — APPROVED** [review]

**Pull request merged**
