### PR TITLE
tests: bsim_bt: Add BLE connection test with split controller arch

### PR DESCRIPTION
**Pull request by aescolar**
To also cover the new split controller architecture (with a common ULL and vendor dependent LLL).
Add a connection testcase (without encryption so far) for the nrf52_bsim configured with the split controller architecture.
This is just the exact same as the Basic_con test but building the test with CONFIG_BT_LL_SW_SPLIT=y.
Privacy and data lenght extensions are so far disabled as the new controller does not yet support them.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
LGTM

**Comment by jhedberg** [comment]
Looks generally good, but why `Basic_con_split` instead of `basic_conn_split`? I.e. why the capital letter and a different short form for "connection" than we use e.g. in our API (bt_conn)?

**Comment by aescolar** [comment]
> why Basic_con_split instead of basic_conn_split

I hadn't give it any thought. I can certainly rename them to that if you prefer.

**Comment by jhedberg** [comment]
> I hadn't give it any thought. I can certainly rename them to that if you prefer.

If there wasn't a clear rationale, then yes please. It would at least be more consistent with the existing conventions in the tree, e.g. I haven't seen many mixed-case file names.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
