### PR TITLE
More coverage backports to v1.14

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Backport a few more PRs to v1.14 to address coverage gaps.

Also allow building with 0.10.1 SDK since code coverage is broken on x86 in 0.10.0. It's just a copy of the 0.10.0 configuration.

Partial fix for: #16011 
Fixes: #16010

### CODE REVIEW

**Comment by nashif** [comment]
There is a commit here that is deprecating an API, we should not be deprecating APIs in 1.14, need to backport this without a deprecation.

**Comment by andrewboie** [comment]
@nashif from @andyross commit message:

```
This is an oddball API.  It's untested.  In fact testing its proper
behavior requires very elaborate automation (you need a device outside
the Zephyr hardware to measure real world time, and a mechanism for
getting the device into and out of idle without using the timer
driver).  And this makes for needless difficulty managing code
coverage metrics.

It was always just a hint anyway.  Mark the old API deprecated and
replace it with a kconfig tunable.  The effect of that is just to
change the timeout value passed to the timer driver, where we can
manage code coverage metrics more easily (only one driver cares to
actually support this feature anyway).

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>
```

How do we proceed?

**Comment by pfalcon** [comment]
> Also allow building with 0.10.1 SDK 

+1 on that, it would fix https://github.com/zephyrproject-rtos/zephyr/issues/17487

**Review by pfalcon — APPROVED** [review]
I reviewed patches included in this PR, all make sense.

My only concern is the "toolchain: allow 0.10.1 SDK" commit, which seems to be adhocly written for 1.14 branch, instead of cherry-picked from master. This immediately leads to "why??". But the master commit answers it: 8e2b9b4ac7faf501bb6251c6acd1a3315e325746 "sdk: add support for 0.10.1 and remove 0.9.5". Gentlemen, can we please refrain from mixing unrelated changes in one commit? (And yes, each SDK version is independent, adding one and removing another maybe logically correlated, but should nor be physically (== in one commit) depend on each other). Ping to @nashif as the author of that commit.

**Comment by pfalcon** [comment]
@andrewboie, I approved this from my side. If there're further complication with the entirety of this PR, could you please split SDK 0.10.1 upgrade into a separate PR for streamlined processing of it?

**Comment by andrewboie** [comment]
> There is a commit here that is deprecating an API, we should not be deprecating APIs in 1.14, need to backport this without a deprecation.

@nashif went on vacation without providing specifics on what he wanted to see here, for now dropping that commit.

**Comment by andrewboie** [comment]
@carlescufi @galak @MaureenHelm can you review?

**Review by carlescufi — APPROVED** [review]
LGTM, nice that you added 0.10.1 support, this will come in very handy in general.

**Comment by andrewboie** [comment]
@carlescufi can you merge this?

**Pull request merged**
