### PR TITLE
fs: introduce FS_O_TRUNC fs_open flag

### PR DESCRIPTION
**Pull request by invoxiaamo**
Let's add LFS_O_TRUNC has a supported flag for fs_open.
=> aligned with the open() usage
=> most FS already support a similar translation of this flag
=> provide a proper support for fopen("path", "w") which is a common pattern to create fresh file when using posix API

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
This needs a test that verifies it works correctly on all in-tree file systems.

I have a recollection this was proposed before, and it was discovered that the semantics of the flag was sufficiently different for littlefs and FatFs that it couldn't be done.  But I may be mixing that up with another flag.

**Comment by invoxiaamo** [comment]
> This needs a test that verifies it works correctly on all in-tree file systems.
> 
> I have a recollection this was proposed before, and it was discovered that the semantics of the flag was sufficiently different for littlefs and FatFs that it couldn't be done. But I may be mixing that up with another flag.

No problem to implement additional tests to tests/subsys/fs/fat_fs_api:
- open with FS_O_CREATE | FS_O_TRUNC on an existing file and check the empty content

FS_O_TRUNC without FS_O_CREATE can be manage by truncating the file after fatfs f_open. I just wonder if this unusual usage need to be fully implemented or not ?

**Comment by pabigot** [comment]
> FS_O_TRUNC without FS_O_CREATE can be manage by truncating the file after fatfs f_open. I just wonder if this unusual usage need to be fully implemented or not ?

Whatever the Zephyr API specifies must happen needs to be implemented and tested.  If the API specification is unclear, that needs to be fixed.

**Comment by invoxiaamo** [comment]
> Whatever the Zephyr API specifies must happen needs to be implemented and tested. If the API specification is unclear, that needs to be fixed.

The question was related to the way FA_APPEND was not implemented on Fatfs. I can be implemented (ie. seeking at end on every write) but the choice was made to not implement it. I guess this is due to the large amount of code required for this flag.
Zephyr still target small embedded devices and I just wonder how to balance between "full support" and "limited features support". 
Personally, I'm fine with full support when the implementation is light (which will be the case with TRUNC)

**Review by de-nordic — CHANGES_REQUESTED** [review]
I think that `FS_O_TRUC` should be completely served within `fs_open` with no changes to file systems drivers.
If this gets implemented in `fs_open`, then we get:
 - common code that implements the feature across all file systems without modifications to dedicated drivers;
 - implementation for systems that does not directly support, it within driver, as long as they provide `open` and `truncate` callbacks;
 - simpler error management;
 - reduced code duplication when each system driver implements the feature itself (yeah I know that currently each file system does that anyway).

I know that the current implementation of `fs_open` flags can be improved.

**Comment by invoxiaamo** [comment]
> I think that FS_O_TRUC should be completely served within fs_open with no changes to file systems drivers.

I don't really agree. Drivers are here to manage what can't be factorized, and flags translation is part of it.

Here is one example:
This pull request is a first step before submitting a "semihosting_fs" which allow access of the host (PC) FS from ARM through GDB / GDB+Qemu (https://developer.arm.com/documentation/dui0471/g/semihosting/semihosting-operations).
This is very useful for dev / testing / big file recoding while little flash, etc..

Unfortunately, there is not "truncate" operation available, and consequently, open+create+truncate can only be performed at driver open level.

**Comment by pabigot** [comment]
> > Whatever the Zephyr API specifies must happen needs to be implemented and tested. If the API specification is unclear, that needs to be fixed.
> 
> The question was related to the way FA_APPEND was not implemented on Fatfs. I can be implemented (ie. seeking at end on every write) but the choice was made to not implement it. I guess this is due to the large amount of code required for this flag.

IIRC it was more that it couldn't easily match the behavior of the same flag on other file systems.

I don't object to `FS_O_TRUNC` being implemented at the file system level, rather than in the wrappers, but only if the behavior is the same on all file systems, as verified by a test.  If it can't, then it needs to be done at the wrapper level, or not done at all.  (My opinon, though, @nvlsianpu owns file systems in Zephyr.)

**Comment by de-nordic** [comment]
> 
> IIRC it was more that it couldn't easily match the behavior of the same flag on other file systems.
> 
Yes that is true, in case of ELM FAT it means that the file position will be set at the end on open but till not be reset to that position on every write.

**Comment by de-nordic** [comment]
> 
> Unfortunately, there is not "truncate" operation available, and consequently, open+create+truncate can only be performed at driver open level.

That is actually valid point.

**Review by nashif — COMMENTED** [review]
> Master+o trunc 

Please update the title of the PR with something that readable and can be understood.

**Comment by de-nordic** [comment]
@invoxiaamo Are you willing to add the tests?

**Comment by invoxiaamo** [comment]
hello @de-nordic. I was in holidays and my spare time to work on Zephyr has collapsed in the meantime. I still will to finalize this feature + tests but don't expect any progress too soon...

**Comment by pabigot** [comment]
I'm going to mark this stale, since it had no activity for a long time until zephyrbot touched it.  If it's still going anywhere please remove the label and update it.

**Pull request closed without merging**
