### PR TITLE
dts: Add support for specifier-space property.

### PR DESCRIPTION
**Pull request by carlocaione**
Currently all the *-names and *-cells properties are derived from the name of the base 'name'-s property. This is a limitation because:

- It forces the base property name to be plural ending in -s
- It doesn't allow the english exception of plural words ending in -es

With this patch we add one additional property 'specifier-space' that can be used to explicitly specify the base property name.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>
Suggested-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

This was suggested in #38616 and I want to push it to unblock the IPM work that is using the mailbox bindings.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
I'd like to see this property be required and update the bindings that need to set it as well.

**Comment by carlocaione** [comment]
> I'd like to see this property be required

AFAICT the only bindings requiring this are the ones ending with `*-gpios` (and in the future `mboxes`) or do you mean required for all the `phandle-array` bindings (a bit an overkill)?

**Comment by carlocaione** [comment]
@galak I added a new commit to "fix" the `*-gpios` properties and removed the special case.

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Thanks a lot for taking this on. I've got some comments related to polishing this up a bit and maintaining standalone edtlib tests, but no fundamental objections.

**Review by mbolivar-nordic — APPROVED** [review]
I appreciate the effort, thanks.

**Review by galak — CHANGES_REQUESTED** [review]
Hmm, wasn't expect that we'd have to add this to all the `<FOO>-gpios` bindings.

I guess if we need this, I'd prefer some solution that didn't have to add this to every binding in this way.  Something where we could do a regex `*-gpios` and have a `gpio-consumer.yaml` or something added in the `base.yaml`

**Comment by carlocaione** [comment]
> FWIW, I think preserving the existing special casing for foo-gpios is probably OK. I'm just opposed to adding more special casing when a general mechanism seems clear.

Ok, so the general consensus is to reintroduce the special case for `*-gpios` in the `edtlib` and keep the `specifier-space` for all the less common cases?

**Review by mbolivar-nordic — APPROVED** [review]
I just took a quick look; I'm assuming the only change you made is the one we've just discussed.

**Review by galak — APPROVED** [review]

**Pull request merged**
