### PR TITLE
Bluetooth: controller: Refactor LL up and downstream interface

### PR DESCRIPTION
**Pull request by cvinayak**
Rename some legacy upstream and downstream interfaces in
radio_* namespace to ll_* namespace for consistency.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
This is great, finally cleaning up all that legacy.

**Comment by carlescufi** [comment]
@jhedberg are you OK with this?

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
> @jhedberg are you OK with this?

@carlescufi yes looks fine to me

**Comment by carlescufi** [comment]
@cvinayak can you rebase this?

**Comment by cvinayak** [comment]
@carlescufi rebased.

**Pull request merged**
