### PR TITLE
dts: bindings: base: Undeprecate label

### PR DESCRIPTION
**Pull request by decsny**
Label property is described in DT spec and does not need to be deprecated in base.yaml anymore. It was originally deprecated to discourage what was previously the most common use case of labels in zephyr which was the old device_get_binding, which was rightfully removed. However, labels do have a purpose as described in DT spec of providing a human readable string to software to describe the device, which there is some use for.

The description of a label should be given in the device binding, as stated in DT spec.

Label properties should be of type string.

TODO:
 - [x] ensure documentation of correct and incorrect usage of the label property

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]
# -1

If used as before. According to the spec,

> The label property defines a human readable string describing a device. The binding for a given device
specifies the exact meaning of the property for that device.

Examples of this usecase can be found in e.g. LED/Buttons. But going back to labels as unique identifiers for devices is a big no for me.

**Comment by gmarull** [comment]
> # -1

* If used as before. According to the spec,

> The label property defines a human readable string describing a device. The binding for a given device
specifies the exact meaning of the property for that device.

Examples of this usecase can be found in e.g. LED/Buttons. But going back to labels as unique identifiers for devices is a big no for me.

**Comment by decsny** [comment]
> # -1
> 
> If used as before. According to the spec,
> 
> > The label property defines a human readable string describing a device. The binding for a given device
> > specifies the exact meaning of the property for that device.
> 
> Examples of this usecase can be found in e.g. LED/Buttons. But going back to labels as unique identifiers for devices is a big no for me.

I am not sure why you are putting -1, if you agree with me.

**Comment by gmarull** [comment]
> > # -1
> > If used as before. According to the spec,
> > > The label property defines a human readable string describing a device. The binding for a given device
> > > specifies the exact meaning of the property for that device.
> > 
> > 
> > Examples of this usecase can be found in e.g. LED/Buttons. But going back to labels as unique identifiers for devices is a big no for me.
> 
> I am not sure why you are putting -1, if you agree with me. I am pretty sure my message said the old usage was rightfully removed, and the reason I want to undeprecate this is for cases where we want to use it as the DT spec says it should be used, ie a human readable string. Which part of that did you -1 ?

Maybe I was scared about bringing it back without making it clear it's not going to bring back, e.g. `device_get_binding()`. We should probably raise this to the Arch WG. I also think it'd probably be better to follow what `gpio-leds` did with `label`, to avoid misuses, that is, if you want label you need to manually extract it, but it won't be available anywhere by default as we had before.

**Comment by decsny** [comment]
> > > # -1
> > > If used as before. According to the spec,
> > > > The label property defines a human readable string describing a device. The binding for a given device
> > > > specifies the exact meaning of the property for that device.
> > > 
> > > 
> > > Examples of this usecase can be found in e.g. LED/Buttons. But going back to labels as unique identifiers for devices is a big no for me.
> > 
> > 
> > I am not sure why you are putting -1, if you agree with me. I am pretty sure my message said the old usage was rightfully removed, and the reason I want to undeprecate this is for cases where we want to use it as the DT spec says it should be used, ie a human readable string. Which part of that did you -1 ?
> 
> Maybe I was scared about bringing it back without making it clear it's not going to bring back, e.g. `device_get_binding()`. We should probably raise this to the Arch WG. I also think it'd probably be better to follow what `gpio-leds` did with `label`, to avoid misuses, that is, if you want label you need to manually extract it, but it won't be available anywhere by default as we had before.

Like I have on the TODO item, I'm going to put documentation about what specifically it is for, and forbid other usages. Also, AFAIK all the code and logic for the things like device_get_binding has actually been removed from the tree and so it would require a big PR to reintroduce the ability to do things with labels like that. I don't think this is a topic worth the arch WG time.

**Review by gmarull — COMMENTED** [review]
existing `label` should be adjusted to not redefine type?

**Review by tejlmand — APPROVED** [review]
Based on details from the discussion, then undeprecate `label` is fine if it used purely as going to be used as described.

**Review by gmarull — APPROVED** [review]

**Pull request merged**
