### PR TITLE
sample: tfm: fix the digest index check

### PR DESCRIPTION
**Pull request by rajkan01**
From non-secure to secure message digest valid index values from 0 to 5 but secure side check at the 5th index and return an error, so update the index validation to accept the 5th index message-digest request from non-secure side.

Signed-off-by: Rajkumar Kanagaraj <rajkumar.kanagaraj@linaro.org>

### CODE REVIEW

**Review by joerchan — CHANGES_REQUESTED** [review]
There are 5 indexes, ranging 0 to 4. The change in this PR is creating an index out of bounds access by allowing the index 5, i.e the 6th index, and printing 6 Digests.

**Comment by rajkan01** [comment]
> There are 5 indexes, ranging 0 to 4. The change in this PR is creating an index out of bounds access by allowing the index 5, i.e the 6th index, and printing 6 Digests.

From the non-secure side, loop starts from 0 to 5 of total expected run of 6 digest values 
https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/tfm_integration/tfm_secure_partition/src/main.c#L17

**Comment by joerchan** [comment]
Yes, the 6th run is expected to end with "Status: -135"

**Comment by rajkan01** [comment]
> Yes, the 6th run is expected to end with "Status: -135"

Why we do need to show the user error status rather to show the digest calculated values

**Comment by microbuilder** [comment]
@joerchan It wasn’t clear to me what the error code meant here or if it was intentional. A comment might be useful, but if it’s intentional fair enough.

**Comment by rajkan01** [comment]
as the tfm_sample_partition sample expected to return the last message-digest request from the non-secure side to secure should return an error status of -135 (at the 5th index request) due to that I am closing this PR

**Comment by joerchan** [comment]
@rajkan01 @microbuilder 
Yes, I agree that this is something that can be improved. I was also puzzled the first time I ran the sample as the print of the error code looks like a failure of the sample.

My memory is also failing me as I thought this was explained in the readme of the sample, but it is not the case.

So we should improve this, either by removing the last call to the digest function, or changing updating the readme and print to explain this better.
```diff
@@ -17,7 +17,9 @@ void main(void)
        for (int key = 0; key < 6; key++) {
                psa_status_t status = dp_secret_digest(key, digest, sizeof(digest));
 
-               if (status != PSA_SUCCESS) {
+               if (status == PSA_ERROR_INVALID_ARGUMENT && key == 5) {
+                       printk("No valid secret for key, received expected error code\n");
+               } else if (status != PSA_SUCCESS) {
                        printk("Status: %d\n", status);
                } else {
                        printk("Digest: ");
```
Maybe something like this? Feel free to suggest a better explanation.

**Comment by rajkan01** [comment]
Couldn't able to reopen this PR so created the new PR https://github.com/zephyrproject-rtos/zephyr/pull/45173 with suggested changes

**Pull request closed without merging**
