### PR TITLE
samples: net: lwm2m_client: build break fixes for k64F and pca10056

### PR DESCRIPTION
**Pull request by mike-scott**
Over the last 2 weeks we've seen several DTS related changes which are causing build breaks when using the modem overlay in the lwm2m_client sample:
- DT_* changes affected the defines in the generated DTS files
- Some DTS properties were missed when moving from the soc area to the sample

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
While not technically related, can we fix the fact that the sample only builds for qemu_x86 via sanitycheck.

./scripts/sanitycheck -N -T samples/net/lwm2m_client -l

I think samples/net/lwm2m_client/sample.yaml  needs fixing.

**Comment by mike-scott** [comment]
@galak So you're putting my build break patch on hold until I add a feature to the .yaml?

**Comment by galak** [comment]
> @galak So you're putting my build break patch on hold until I add a feature to the .yaml?

Well how is the build breaking?  I'm just saying w/o the yaml fix we aren't actually able to regress your fix ;).

**Comment by mike-scott** [comment]
Which targets would we like to test build?  I've tested: k64f, BLENano2, reel_board, disco_l475_iot1, nrf52840_pca10056, etc.   However, there are often overlays involved (such as overlay-bt.conf).

And of course if we want to test the modem we need k64f or nrf52840_pca10056 w/ overlay-wncm14a2a.conf.

**Comment by nashif** [comment]
start with k64f and pca10056

**Comment by galak** [comment]
> I've added sanity testing for all of the various overlays so that we should be covered. If it's too much, let me know.

Thanks!

**Review by galak — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
