### PR TITLE
NUCLEO-H745ZI-Q move to device pinconfig

### LINKED ISSUE #29109: HAL STM32 Missing ETH pin control configurations in DT files
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
Current device-tree pin control approach misses ethernet pins configurations (especially [stm32h745zitx-pinctrl.dtsi](https://github.com/zephyrproject-rtos/hal_stm32/blob/master/dts/st/h7/stm32h745zitx-pinctrl.dtsi))

**Describe why you are asking for this support?**
I am working on #29108

### PR DESCRIPTION
**Pull request by KozhinovAlexander**
Move whole board to device-tree pin config approach.

### CODE REVIEW

**Comment by martinjaeger** [comment]
Hello @Nukersson.

We are currently moving towards the new pin control configuration via DT for all boards. The progress is tracked in https://github.com/zephyrproject-rtos/zephyr/issues/28999.

I suggest that we update the I2C for all boards at once in a single commit in order to simplify review.

**Comment by Nukersson** [comment]
> Hello @Nukersson.
> 
> We are currently moving towards the new pin control configuration via DT for all boards. The progress is tracked in https://github.com/zephyrproject-rtos/zephyr/issues/28999.
> 
> I suggest that we update the I2C for all boards at once in a single commit in order to simplify review.
 
Thank you @martinjaeger I will let this PR as DNM and remove i2c pinctrl later. Hovewer, this PR will stay and should be later merged, as I am planning to implement eth pins support.

**Comment by erwango** [comment]
@Nukersson please align with @gmarull, as per https://github.com/zephyrproject-rtos/zephyr/issues/28999

**Comment by Nukersson** [comment]
> @Nukersson please align with @gmarull, as per https://github.com/zephyrproject-rtos/zephyr/issues/28999

Alright. Will be done.

**Comment by Nukersson** [comment]
Closed due to #28999

**Pull request closed without merging**
