### PR TITLE
kernel: sparse fixes

### PR DESCRIPTION
**Pull request by bboozzoo**
Fix some issues identified with sparse.

I'm using the following revision of sparse:
```
commit 14964df5373292af78b29529d4fc7e1a26b67a97
Author: Luc Van Oostenryck <luc.vanoostenryck@gmail.com>
Date:   Sun Mar 19 19:01:18 2017 +0100
```
There is also a bunch of warnings raised for minimal libc. My bet is that most of these are false positive and would be better addressed in sparse.

### CODE REVIEW

**Comment by bboozzoo** [comment]
checkpatch fails because of sparse output in commit messages:

```            Commit 7734717a24:
1: T1 Title exceeds max length (74>72)
5: B1 Line exceeds max length (193>72)

Commit bea9a91309:
4: B1 Line exceeds max length (81>72)```

I can wrap the lines if that's preferred

**Comment by bboozzoo** [comment]
Just for the record, commit message line length test is the only one that fails.

**Review by andyross — APPROVED** [review]
Changes all seem straightforward and sane

**Review by tyrantlizard77 — APPROVED** [review]
LGTM

**Pull request merged**
