### PR TITLE
subsys: comply to coding guidelines MISRA C:2012 Rule 14.4 for do-while violations

### PR DESCRIPTION
**Pull request by simhein**
Fix coding guideline MISRA C:2012 Rule 14.4 do-while violations in subsys:
> The controlling expression of an if statement
> and the controlling expression of an iteration-statement shall have
> essentially Boolean type.

Use `do { ... } while (false)' instead of `do { ... } while (0)'.

This PR is part of the enhancement issue #48002 which port the coding guideline fixes done by BUGSENG on the https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-auditable-branch back to main

The commit in this PR is a subset of the original auditable-branch commit:
5d02614e34a86b549c7707d3d9f0984bc3a5f22a

### CODE REVIEW

**Comment by Thalley** [comment]
> Fix coding guideline MISRA C:2012 Rule 14.4 in subsys:
> 
> > The controlling expression of an if statement
> > and the controlling expression of an iteration-statement shall have
> > essentially Boolean type.
> 
> This PR is part of the enhancement issue #48002 which port the coding guideline fixes done by BUGSENG on the https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-auditable-branch back to main
> 
> The commit in this PR is a subset of the original auditable-branch commit: [5d02614](https://github.com/zephyrproject-rtos/zephyr/commit/5d02614e34a86b549c7707d3d9f0984bc3a5f22a)

Is this a WIP? Because the change at this point is really quite small compared to what the PR description says, as this only changes `0` to `false` in a couple of `do { .. } while (0)`. 

Are you planning on doing the entire Rule 14.4 in the subsystem directory in a single PR, or split it into multiple PRs?

**Comment by simhein** [comment]
> > Fix coding guideline MISRA C:2012 Rule 14.4 in subsys:
> > > The controlling expression of an if statement
> > > and the controlling expression of an iteration-statement shall have
> > > essentially Boolean type.
> > 
> > 
> > This PR is part of the enhancement issue #48002 which port the coding guideline fixes done by BUGSENG on the https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-auditable-branch back to main
> > The commit in this PR is a subset of the original auditable-branch commit: [5d02614](https://github.com/zephyrproject-rtos/zephyr/commit/5d02614e34a86b549c7707d3d9f0984bc3a5f22a)
> 
> Is this a WIP? Because the change at this point is really quite small compared to what the PR description says, as this only changes `0` to `false` in a couple of `do { .. } while (0)`.
> 
> Are you planning on doing the entire Rule 14.4 in the subsystem directory in a single PR, or split it into multiple PRs?

For the subsys part the PR shall be named partly comply and it should not be WIP.
Forgot to name it that way thanks for pointing me to that.
To comply complete to Rule 14.4 this is an iterative process and more PR's shall follow. So yes this is basically a part of multiple PRs

The intention and first step here is to take the work from BUGSENG which was done on the auditable branch and move it back to the main to not start from scratch with the violations.

**Comment by Thalley** [comment]
> > > Fix coding guideline MISRA C:2012 Rule 14.4 in subsys:
> > > > The controlling expression of an if statement
> > > > and the controlling expression of an iteration-statement shall have
> > > > essentially Boolean type.
> > > 
> > > 
> > > This PR is part of the enhancement issue #48002 which port the coding guideline fixes done by BUGSENG on the https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-auditable-branch back to main
> > > The commit in this PR is a subset of the original auditable-branch commit: [5d02614](https://github.com/zephyrproject-rtos/zephyr/commit/5d02614e34a86b549c7707d3d9f0984bc3a5f22a)
> > 
> > 
> > Is this a WIP? Because the change at this point is really quite small compared to what the PR description says, as this only changes `0` to `false` in a couple of `do { .. } while (0)`.
> > Are you planning on doing the entire Rule 14.4 in the subsystem directory in a single PR, or split it into multiple PRs?
> 
> For the subsys part the PR shall be named partly comply and it should not be WIP. Forgot to name it that way thanks for pointing me to that. To comply complete to Rule 14.4 this is an iterative process and more PR's shall follow. So yes this is basically a part of multiple PRs
> 
> The intention and first step here is to take the work from BUGSENG which was done on the auditable branch and move it back to the main to not start from scratch with the violations.

That makes more sense :) Instead of using `partly` I will suggest that you specify what part is being doing (e.g. this complies to Rule 14.4 for `do-while` loops only), so that we do not end up with multiple PRs with the same name (as they will all `partly` comply with Rule 14.4) :)

**Comment by Thalley** [comment]
@simhein The commit message also needs to be updated, as they also references fixes that are not fixed by this PR/commit.

**Comment by simhein** [comment]
> @simhein The commit message also needs to be updated, as they also references fixes that are not fixed by this PR/commit.

@Thalley updated both PR and commit message. I hope it makes now more sense :)

**Review by jori-nordic — DISMISSED** [review]
bluetooth/ changes ok

**Review by nordic-krch — DISMISSED** [review]

**Comment by Thalley** [comment]
@simhein PR name and commit message OK now :)

**Review by ppryga-nordic — DISMISSED** [review]

**Review by alwa-nordic — CHANGES_REQUESTED** [review]
Please [include what you use]. `false` is defined in `stdbool.h`.

[include what you use]: https://include-what-you-use.org/

**Comment by simhein** [comment]
> Please [include what you use](https://include-what-you-use.org/). `false` is defined in `stdbool.h`.

I feel like this needs to be discussed on project level as a guideline and not for this specific PR.
Because if this shall be done stdbool.h also needs to be included everywhere bool as type is used.
And this is definitely not the case in the whole project or am I wrong on this point?

**Comment by kruithofa** [comment]
There are a few 'while (0)' statements left that are unchanged. Will these come in a separate PR?
The 'while (1)' statements are unchanged. Will these also come in a separate PR?

**Review by kruithofa — CHANGES_REQUESTED** [review]
There are a few 'while (0)' statements left that are unchanged. Will these come in a separate PR?
The 'while (1)' statements are unchanged. Will these also come in a separate PR?

**Comment by sjanc** [comment]
hmm shouldn't stdbool.h be explicitly included too in files using true/false?

**Review by alwa-nordic — DISMISSED** [review]

**Comment by Thalley** [comment]
> There are a few 'while (0)' statements left that are unchanged. Will these come in a separate PR? The 'while (1)' statements are unchanged. Will these also come in a separate PR?

This is answered in the commit message I believe: This PR/commit only adds the "fix" for the `do-while` loops.

**Comment by Thalley** [comment]
> > > Please [include what you use](https://include-what-you-use.org/). `false` is defined in `stdbool.h`.
> > 
> > 
> > I feel like this needs to be discussed on project level as a guideline and not for this specific PR. Because if this shall be done stdbool.h also needs to be included everywhere bool as type is used. And this is definitely not the case in the whole project or am I wrong on this point?
> 
> It's general good practice in C. If you don't include what you use, you set up mines for a future developer to step on. If you use `false` without `#include <stdbool.h>`, it works because one of the other headers accidentally re-export stdbool. If that other header stops using bool in the future, it will cause compilation errors and force that future developer to "clean up" after others. It's littering. It's a simple enough problem to fix when it blows up, so I'm not too concerned about this (if it's against this project's practice to include stdbool.h).

If the case really is that we cannot rely on headers included by other header files, then each .c file would end up including a lot headers files each. 

What we could do is to include `stdbool.h` in `zephyr/types.h` where we already include 
```
#include <stddef.h>
#include <stdint.h>
```

**Comment by simhein** [comment]
> > There are a few 'while (0)' statements left that are unchanged. Will these come in a separate PR? The 'while (1)' statements are unchanged. Will these also come in a separate PR?
> 
> This is answered in the commit message I believe: This PR/commit only adds the "fix" for the `do-while` loops.

This is true also  it is stated in the message "Use do { ... } while (false)' instead of do { ... } while (0)'."
It could be that are some while (0) changes are missing in this PR because the work was done on a 2.7 branch and the main moved on.  So to answer @kruithofa  questions _'Will these come in a separate PR? The 'while (1)' statements are unchanged. Will these also come in a separate PR?'_ 
1. Yes for the do while (1) a separate PR will be created
2. For the missing while(0) i will check the commit and fix them because mixed coding styles are not good.

**Comment by simhein** [comment]
> > > > Please [include what you use](https://include-what-you-use.org/). `false` is defined in `stdbool.h`.
> > > 
> > > 
> > > I feel like this needs to be discussed on project level as a guideline and not for this specific PR. Because if this shall be done stdbool.h also needs to be included everywhere bool as type is used. And this is definitely not the case in the whole project or am I wrong on this point?
> > 
> > 
> > It's general good practice in C. If you don't include what you use, you set up mines for a future developer to step on. If you use `false` without `#include <stdbool.h>`, it works because one of the other headers accidentally re-export stdbool. If that other header stops using bool in the future, it will cause compilation errors and force that future developer to "clean up" after others. It's littering. It's a simple enough problem to fix when it blows up, so I'm not too concerned about this (if it's against this project's practice to include stdbool.h).
> 
> If the case really is that we cannot rely on headers included by other header files, then each .c file would end up including a lot headers files each.
> 
> What we could do is to include `stdbool.h` in `zephyr/types.h` where we already include
> 
> ```
> #include <stddef.h>
> #include <stdint.h>
> ```

I think this is a good idea, Can I add this as commit to this PR or should I do a extra PR for it?

**Review by yperess — DISMISSED** [review]

**Review by PavelVPV — DISMISSED** [review]

**Comment by alwa-nordic** [comment]
> > > > > Please [include what you use](https://include-what-you-use.org/). `false` is defined in `stdbool.h`.
> > > > 
> > > > 
> > > > I feel like this needs to be discussed on project level as a guideline and not for this specific PR. Because if this shall be done stdbool.h also needs to be included everywhere bool as type is used. And this is definitely not the case in the whole project or am I wrong on this point?
> > > 
> > > 
> > > It's general good practice in C. If you don't include what you use, you set up mines for a future developer to step on. If you use `false` without `#include <stdbool.h>`, it works because one of the other headers accidentally re-export stdbool. If that other header stops using bool in the future, it will cause compilation errors and force that future developer to "clean up" after others. It's littering. It's a simple enough problem to fix when it blows up, so I'm not too concerned about this (if it's against this project's practice to include stdbool.h).
> > 
> > 
> > If the case really is that we cannot rely on headers included by other header files, then each .c file would end up including a lot headers files each.
> > What we could do is to include `stdbool.h` in `zephyr/types.h` where we already include
> > ```
> > #include <stddef.h>
> > #include <stdint.h>
> > ```
> 
> I think this is a good idea, Can I add this as commit to this PR or should I do a extra PR for it?

I think it's best to put it in a separate PR.

**Review by jhedberg — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Review by MariuszSkamra — DISMISSED** [review]

**Review by cfriedt — DISMISSED** [review]

**Review by aaronemassey — DISMISSED** [review]

**Review by ppryga-nordic — DISMISSED** [review]

**Comment by simhein** [comment]
resolved conflicts

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by PavelVPV — APPROVED** [review]

**Comment by alwa-nordic** [comment]
Just for clarification: What is "essentially Boolean type"?

**Comment by simhein** [comment]
> Just for clarification: What is "essentially Boolean type"?

MISRA defines the so called _"The essential type model"_ which is basically a mapping of the c arithemtic data types to the MISRA so called essential type.
For example:
```
Essentially Boolean = _Bool
Essentially char = char
Essentially signed = signed char, signed short, signed int, signed long, signed long long
...
```

The reason behind this model is:
1. To support a stronger system of type-checking
2. Provide a basis for defining rules to control the use of implicit and explicit type conversions
3. Address some of the type conversions anomalies found within ISO C

**Comment by simhein** [comment]
I will close this PR, because we need to revisit and review the Guideline/Misra Rule 14.4 if it is applicable for the **do { ... } while (0)** constructs or if it needs to be deviated/justified and we can leave it as it is.

**Pull request closed without merging**
