### PR TITLE
mgmt/mcumgr: Fix UART processing of TX frames

### LINKED ISSUE #37893: mcumgr_serial_tx_pkt with len==91 fails to transmit CRC
`mcumgr_serial_tx_frame` will end the fragment once the maximum size of 128 bytes of header+base64 data is reached, which corresponds to 91 bytes of binary data.

If the entire frame is exactly 91 bytes long, the CRC will not be sent. There is only one fragment sent, missing the CRC field.

https://github.com/zephyrproject-rtos/zephyr/blob/21d1ad3762302b3e461953df59430c77e0709274/subsys/mgmt/mcumgr/serial_util.c#L234-L242

### PR DESCRIPTION
**Pull request by de-nordic**
The commit fixes problem with UART TX frame processing, which was
caused by incorrect output buffer size evaulation, where input buffer
of certain len would cause entire output frame to be filled with no
place left for CRC causing a transmission to hang.
The commit, additionally, moves input buffer reminder processing out of
the input buffer processing loop.

Fixes #37893

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Comment by de-nordic** [comment]
@sw Can you take a look?

**Comment by de-nordic** [comment]
> The frame sent by `mcumgr_serial_tx_frame` is 135 bytes long. (or 132 if you don't count the 0x06 0x09 and linefeed, which is how you're supposed to count I believe).

Ha, according to https://github.com/zephyrproject-rtos/zephyr/blob/main/include/mgmt/mcumgr/serial.h... you are right. Fixed.

> The condition for the while loop needs to be adjusted. I wonder if it would be best to get rid of `dst_off` and only use `src_off`?

Done.  Now I calculate "triplets" as  the min value of how many triplets are there in input buffer against how many four byte chunks will fit into output frame.

**Comment by de-nordic** [comment]
@sw Can you look again?

**Review by sw — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@lairdjm could you please review this one?

**Review by nordicjm — APPROVED** [review]

**Comment by lairdjm** [comment]
I had been looking at the apache mcumgr documentation before and never noticed there was any description of the frames in zephyr, definitely confusing.

**Comment by de-nordic** [comment]
> 
> 
> I had been looking at the apache mcumgr documentation before and never noticed there was any description of the frames in zephyr, definitely confusing.

@lairdjm The frames are not specific for Zephyr, rather for serial transport, description is also here https://github.com/zephyrproject-rtos/zephyr/blob/main/include/mgmt/mcumgr/serial.h.
I am currently working on documenting payload structure for commands.

**Pull request merged**
