### PR TITLE
NXP: Add support for Kinetis K8x SoC series and FRDM-K82F development board

### PR DESCRIPTION
**Pull request by fbrozovic**
This patch series adds support for the NXP Kinetis K8x SoC series and the FRDM-K82F development board.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Looks pretty good to me.  I'd suggest having the HAL update going over here:

https://github.com/zephyrproject-rtos/hal_nxp

**Comment by fbrozovic** [comment]
@galak Alright, I submitted a PR for the HAL. Since the NXP HAL is not added to west.yml yet, should I add it in this PR?

**Comment by galak** [comment]
> @galak Alright, I submitted a PR for the HAL. Since the NXP HAL is not added to west.yml yet, should I add it in this PR?

I'd leave this PR as is for now.  As we have:

https://github.com/zephyrproject-rtos/zephyr/pull/18469

Once that gets merged, we can rebase your PR on top of it.

**Comment by fbrozovic** [comment]
> Once that gets merged, we can rebase your PR on top of it.

OK, same thing applies for #17118 then - I will create another HAL PR for that.

**Review by dbkinder — APPROVED** [review]
doc changes LGTM, thanks.

**Comment by fbrozovic** [comment]
Previously failing tests were addressed, just waiting on zephyrproject-rtos/hal_nxp#2 to be merged now.

**Comment by galak** [comment]
Looks like this is exposing an issue on mimxrt1015_evk, with LPUART4.  Not sure what the intent with LPUART4 was.

@jhqian, @MaureenHelm we have the driver for LPUART_4 enabled in the defconfig but not in the .dts.  Since the LPUART driver didn't support CONFIG_UART_MCUX_LPUART_4 we didn't see this.  Should we remove it from the defconfig (as below) or update dts?:

diff --git a/boards/arm/mimxrt1015_evk/Kconfig.defconfig b/boards/arm/mimxrt1015_evk/Kconfig.defconfig
index 7085044022..1fc09a802f 100644
--- a/boards/arm/mimxrt1015_evk/Kconfig.defconfig
+++ b/boards/arm/mimxrt1015_evk/Kconfig.defconfig
@@ -36,9 +36,6 @@ if UART_MCUX_LPUART
 config UART_MCUX_LPUART_1
        default y
 
-config UART_MCUX_LPUART_4
-       default y
-
 endif # UART_MCUX_LPUART
 
 endif # BOARD_MIMXRT1015_EVK

**Comment by fbrozovic** [comment]
@galak I just added a commit adjusting the mimxrt1015_evk defconfig to include `default y if BT_UART` on UART4, since it seems that the other mimxrt evk boards do the same.

**Comment by galak** [comment]
LGTM.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
@MaureenHelm can you take a look
@dbkinder can you look at the docs.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
