### PR TITLE
V2.6 branch - add microsecond precision to zsock_select() consistent with Linux

### PR DESCRIPTION
**Pull request by bob2oneil**
The following discussion describes the issue with the **zsock_select**() implementation, which accepts a microsecond precision timeout value, but then rounds up to milliseconds and uses **zsock_poll**() under the covers.  This request it then to restore the fidelity of this timeout to the microsecond precision from the original Linux implementation of select().  Jukka Rissanen comments here on this topic and outlines a strategy for implementing these changes, with an internal zsock_poll() to add fidelity back to the **zsock_select**() implementation.  Refer to the following URL for this conversation:

https://github.com/zephyrproject-rtos/zephyr/discussions/36072

### CODE REVIEW

**Comment by galak** [comment]
@bob2oneil is there a fix on the main branch for this?

**Comment by galak** [comment]
> @bob2oneil is there a fix on the main branch for this?

Or do you need to rebase this on the main branch.

**Comment by bob2oneil** [comment]
This may not have been the best vehicle for requesting a change, I got this direction from Jukka.  If that is the case, please let me know and I will close this out and use another method.

**Comment by jukkar** [comment]
> This was more of a wish request manifesting as a PR as suggested by Jukka.

Please change (and test) the code and then send the result to review (as a PR), we can then discuss how it works / what needs to be changed. 
I am closing this as there is no change here.

**Pull request closed without merging**
