### PR TITLE
Use picolibc for cbprintf (when building with picolibc)

### PR DESCRIPTION
**Pull request by keith-packard**
Picolibc's tinystdio implementation already provides a callback-based architecture, so `cbvprintf` can be implemented using that instead of replicating that functionality in Zephyr. This provides a few benefits:

 1. Smaller code size. Picolibc's printf implementation is smaller than the zephyr cbprintf implementation
 2. Verified standards conformance. Picolibc's printf code is continuously validated against a large suite of tests ensuring that it generates POSIX compatible output.
 3. Sharing with applications using stdio. Any application which uses both stdio functions (like sprintf) and cbprintf APIs will now share a common underlying formatted output path, further saving code space.
 4. Matching functionality between stdio and cbprintf APIs. Applications can count on precisely the same results using either API.

A second PR to use picolibc for printk will be posted shortly; that required an update to picolibc's cmake support which is winding its way through picolibc CI.

### CODE REVIEW

**Review by andyross — DISMISSED** [review]
To be clear: I've only reviewed the zephyr changes and am taking the list of advantages on faith.  In some sense this is sort of a shame as the cbprintf code is a recent contribution and I for one thought it was pretty nifty.  But better code is better code, and no doubt picolibc's implementation is nifty too.

**Comment by keith-packard** [comment]
> To be clear: I've only reviewed the zephyr changes and am taking the list of advantages on faith. In some sense this is sort of a shame as the cbprintf code is a recent contribution and I for one thought it was pretty nifty. But better code is better code, and no doubt picolibc's implementation is nifty too.

Yes, the cbprintf stuff is nifty -- turns out the author of picolibc's stdio had exactly the same idea, just many years ago, and decided to embed it in stdio itself, rather than creating a parallel world. 

Really, the key advantage is having only one implementation of 'printf' in the system. Picking the picolibc one instead of the zephyr one has additional advantages of reduced code size and POSIX standards conformance. Oh, and exact floating point output, which probably isn't relevant for most users.

**Review by stephanosio — DISMISSED** [review]
Looks reasonable.

**Review by nordic-krch — COMMENTED** [review]
looks ok. One thing: the commit message with v2 v3 stuff. Could you clean this up?

**Comment by carlescufi** [comment]
>Picolibc already provides the functionality offered by cbprintf, so
there's no reason to use the larger and less functional version included
in zephyr.

I wonder if we should consider replacing cbprintf with code from upstream picolibc @nordic-krch and @npitre?

**Comment by keith-packard** [comment]
> looks ok. One thing: the commit message with v2 v3 stuff. Could you clean this up?

Do you want me to remove the 'changelog' in the commit message? I'm not sure what the local conventions are for this kind of information.

**Comment by carlescufi** [comment]
> > looks ok. One thing: the commit message with v2 v3 stuff. Could you clean this up?
> 
> Do you want me to remove the 'changelog' in the commit message? I'm not sure what the local conventions are for this kind of information.

Yes please. We don't use changelogs or version number in commits/series.

**Comment by keith-packard** [comment]
> Yes please. We don't use changelogs or version number in commits/series.

Updated (and rebased)

**Review by stephanosio — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Commit messages fixed

**Pull request merged**
