### PR TITLE
board: riscv: add qemu_riscv32_xip board to test XIP mode

### PR DESCRIPTION
**Pull request by cwshu**
After #31166 changes QEMU board, there is no RISC-V QEMU platform running in XIP mode.
To verify XIP mode in RISC-V (e.g. RISC-V linker script, ...), add qemu sifive_e board back for running XIP test only.
(like qemu_x86_xip)

### CODE REVIEW

**Review by katsuster — APPROVED** [review]

**Comment by katsuster** [comment]
@galak
Sorry to ask you, can we proceed this PR?? RISC-V port reviewers are very few...

**Comment by MaureenHelm** [comment]
Will you please rebase so we can make sure CI still passes?

**Comment by cwshu** [comment]
Rebased

**Review by MaureenHelm — APPROVED** [review]

**Comment by carlescufi** [comment]
>MaureenHelm requested a review from galak 12 hours ago

Failed to see this before merging, sorry @MaureenHelm, @galak

**Pull request merged**
