### PR TITLE
net: sockets: Implement MSG_TRUNC flag

### LINKED ISSUE #10494: sockets: Implement MSG_TRUNC flag for recv()
Feature request from @mike-scott. He'd like to estimate a buffer size required to receive a complete UDP datagram. Per POSIX semantics, a recv() for SOCK_DGRAM will drop any unread data belonging to datagram.

Doing "man recv" on Linux, one can see:

~~~
       MSG_TRUNC (since Linux 2.2)
              For    raw   (AF_PACKET),   Internet   datagram   (since   Linux
              2.4.27/2.6.8), netlink (since Linux 2.6.22), and  UNIX  datagram
              (since  Linux 3.4) sockets: return the real length of the packet
              or datagram, even when it was longer than the passed buffer.
~~~

The expectation is that combined with MSG_PEEK (which we already implement), this flag would give the effect desired by @mike-scott.

TODO:

* Confirm that MSG_TRUNC indeed can be combined with MSG_PEEK
* Analyze POSIX compatibility of this feature

### PR DESCRIPTION
**Pull request by rlubos**
Add implementation of the MSG_TRUNC `recv()` flag for UDP and DTLS sockets along with unit tests.

Resolves #10494

### CODE REVIEW

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by pfalcon** [comment]
@rlubos: Did you notice this fails CI with:

```
/workdir/zephyr/subsys/net/lib/sockets/sockets_tls.c: In function 'recvfrom_dtls_common':
/workdir/zephyr/subsys/net/lib/sockets/sockets_tls.c:1679:4: error: implicit declaration of function 'dtls_peer_address_get' [-Werror=implicit-function-declaration]
```

Perhaps, you moved the call to that function from #ifdef guarded region to outside of it?

**Review by pfalcon — APPROVED** [review]
Eyeballed and looks fine, especially given that there're tests. Just need to fix compile error 
apparently #ifdef matter).

**Comment by rlubos** [comment]
> Perhaps, you moved the call to that function from #ifdef guarded region to outside of it?

Yes, that was an overlook from my side, thanks. I've sent a fix.

**Pull request merged**
