### PR TITLE
soc: arm: replace 'nuvoton' folder name with 'nuvoton_numicro'

### PR DESCRIPTION
**Pull request by MulinChao**
During modifying the file used by Nuvoton NPCX platform in the MAINTAINERS file, we found users might get confused to soc names between 'soc/nuvoton' and 'soc/nuvoton_npcx'. This PR is an attempt to reduce this ambiguity. If it is not suitable, I will close it later.

In this PR, we changed soc folder name from 'soc/nuvoton' to 'soc/nuvoton_numicro'. Most soc vendors name their soc folders by the company name with SOC_FAMILY suffix instead of the company name directly. It is clearer if the soc company has different product lines that aim to the specific markets.

Hence, the 'numicro' suffix is used for Nuvoton Microcontroller production line in this PR. It is easier to distinguish the 'npcx' suffix used for Nuvoton Embedded Controller (EC) of Notebook PC product line.

Here is the console output with 'samples/hello_world' application after applying this PR. 
*** Booting Zephyr OS build zephyr-v2.6.0-1626-g86f1b66a29ae  ***
Hello World! nuvoton_pfm_m487

Any comment for this attempt is appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37430)

### CODE REVIEW

**Review by keith-zephyr — COMMENTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37430)* status: all files reviewed, 1 unresolved discussion (waiting on @ChiHuaL, @galak, @ioannisg, @jackrosenthal, @MaureenHelm, @MulinChao, @sjg20, @ssekar15, and @WealianLiao)

___
*[MAINTAINERS.yml, line 1294 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37430#-MgGcaGP8JtsQoku3s2l:-MgGcaGQ4Vjf87IhLV9U:bpdw3ps) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/a4b5bc90b0923026946c627fed39901730f4cde7/MAINTAINERS.yml#L1294)):*
> ```YAML
>         - "platform: Synopsys"
> 
> Nuvoton_NPCX Platforms:
> ```

Is a Nuvoton_numicro section needed?

**Comment by MulinChao** [comment]
> > Reviewed 20 of 20 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37430)_ status: all files reviewed, 1 unresolved discussion (waiting on @ChiHuaL, @galak, @ioannisg, @jackrosenthal, @MaureenHelm, @MulinChao, @sjg20, @ssekar15, and @WealianLiao)
> 
> _[MAINTAINERS.yml, line 1294 at r1](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37430#-MgGcaGP8JtsQoku3s2l:-MgGcaGQ4Vjf87IhLV9U:bpdw3ps) ([raw file](https://github.com/zephyrproject-rtos/zephyr/blob/a4b5bc90b0923026946c627fed39901730f4cde7/MAINTAINERS.yml#L1294)):_
> 
> > ```yaml
> >         - "platform: Synopsys"
> > 
> > Nuvoton_NPCX Platforms:
> > ```
> 
> Is a Nuvoton_numicro section needed?

Good idea. I will add this section later.

**Comment by MulinChao** [comment]
Besides adding the 'Nuvoton_Numicro Platform' section in this update, I change the status of 'Nuvoton_NPCX Platform' section from 'orphaned' to 'maintained' since we do maintain npcx drivers continuously. This update also adds the reviewers in 'collaborators' property and thanks for the contribution of reviewing npcx drivers.

**Comment by MulinChao** [comment]
> > Is a Nuvoton_numicro section needed?
> 
> Good idea. I will add this section later.

Done.

**Review by keith-zephyr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/37430)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @ChiHuaL, @galak, @ioannisg, @jackrosenthal, @keith-zephyr, @MaureenHelm, @sjg20, @ssekar15, and @WealianLiao)

**Review by jackrosenthal — APPROVED** [review]

**Comment by cfriedt** [comment]
Gah - merged this before I saw the 19/20 reviewable status. I've not used that tool before. Please advise if you would like the commit reverted for now.

**Comment by keith-zephyr** [comment]
> Gah - merged this before I saw the 19/20 reviewable status. I've not used that tool before. Please advise if you would like the commit reverted for now.

This was my mistake with reviewable.  I did review all the files and marked the PR as approved.  Some of us are using reviewable because it can provide diffs between patchsets.  You should consider the approval votes as the source of truth here and ignore the reviewable status.  As long as no reviewers have requested changes, the PR should have the green light to merge.

**Pull request merged**
