### PR TITLE
drivers: usb/stm32: use dts information to populate clock settings

### LINKED ISSUE #10450: usb/stm32: use dts extracted information to populate clock settings
"clocks" property is missing in stm32 usb nodes, which prevents using #define CONFIG_xxx for clock related usb configuration code:

```
static int usb_dc_stm32_clock_enable(void)
{
	struct device *clk = device_get_binding(STM32_CLOCK_CONTROL_NAME);
	struct stm32_pclken pclken = {

#ifdef CONFIG_USB_HS_BASE_ADDRESS
		.bus = STM32_CLOCK_BUS_AHB1,
		.enr = LL_AHB1_GRP1_PERIPH_OTGHS
#else /* CONFIG_USB_HS_BASE_ADDRESS */

#ifdef USB
		.bus = STM32_CLOCK_BUS_APB1,
		.enr = LL_APB1_GRP1_PERIPH_USB,

#else /* USB_OTG_FS */

#ifdef CONFIG_SOC_SERIES_STM32F1X
		.bus = STM32_CLOCK_BUS_AHB1,
		.enr = LL_AHB1_GRP1_PERIPH_OTGFS,
#else
		.bus = STM32_CLOCK_BUS_AHB2,
		.enr = LL_AHB2_GRP1_PERIPH_OTGFS,
#endif /* CONFIG_SOC_SERIES_STM32F1X */

#endif /* USB */

#endif /* CONFIG_USB_HS_BASE_ADDRESS */
	};
```

Rather than using the hardcoded #defines LL_APB1_GRP1_P_XXX and STM32_CLOCK_BUS_XXX,
instance configuration code, should rather use the equivalent coming from dts #define generation.

Cf example in drivers/can/stm32_can.c:
```
static const struct can_stm32_config can_stm32_cfg_1 = {
[... ]
.pclken = {
.enr = CONFIG_CAN_1_CLOCK_BITS,
.bus = CONFIG_CAN_1_CLOCK_BUS,
},
.config_irq = config_can_1_irq
};
```
This should be done in 3 steps:
-Populate "clocks" property in USB nodes in stm32 dtsi files (might be partially done already)
-Populate the CONFIG_ <> generated defined in stm32 fixup files
-Update stm32 serial instantiation code to use CONFIG_ symbols and take advantage of this to simplify declaration preprocessor macros

### PR DESCRIPTION
**Pull request by FRASTM**
This patch uses "clocks" property in stm32 usb nodes for clock related usb configuration code of each stm32 soc.

Fixes #10450

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Review by erwango — APPROVED** [review]
LGTM, but will let others cross check on buses, specially on L4 series.

**Comment by FRASTM** [comment]
./scripts/sanitycheck --tag usb -p stm32f469i_disco
JOBS: 4

Building testcase defconfigs...
Filtering test cases...
13 tests selected, 115061 tests discarded due to filters
total complete:   13/  13  100%  failed:    0
13 of 13 tests passed with 0 warnings in 197 seconds

**Review by ydamigos — APPROVED** [review]
LGTM

**Comment by FRASTM** [comment]
recheck

**Review by galak — APPROVED** [review]

**Pull request merged**
