### PR TITLE
Close

### PR DESCRIPTION
**Pull request by iotmember**
+ nRF51822
+ Bluetooth Low Energy
+ DAPLink interface
+ UNO pinout
+ 4 power

+ Wiki: https://vngiotlab.github.io/vbluno/

+ The following samples were tested:
hello_world
basic/button
basic/blinky
bluetooth/peripheral_hr
bluetooth/beacon

Signed-off-by: Nam Do Thanh <robotden@gmail.com>

### CODE REVIEW

**Comment by iotvietmember** [comment]
Hi @galak : We want to add support for VBLUno51 board. Could you please review 
[my commit](https://github.com/zephyrproject-rtos/zephyr/pull/603/commits/9df25be35a912bd317eaf2bc9d1a959acc980e20)
Many thanks

**Comment by cvinayak** [comment]
Signed off by in Pr comment, use full name.

**Comment by cvinayak** [comment]
Copyright to be correct and up to date, 2017?

**Comment by iotvietmember** [comment]
Hi @cvinayak : Thanks for your comment. I have fixed copyright comment in code. Could you please see [this commit](https://github.com/zephyrproject-rtos/zephyr/pull/603/commits/f301b8e04c4e553fb2642a46711ad6bc842b5003)
Many thanks.

**Comment by cvinayak** [comment]
Hi @iotvietmember, use your name in all your commit signed-off-by too. And, only clean commit history, no merge commits.

**Comment by iotvietmember** [comment]
Hi @cvinayak, Do I need to clean all commit history and only use 1 commit?

**Comment by iotvietmember** [comment]
Close and create again

**Pull request closed without merging**
