### PR TITLE
Mcp2518fd driver - Fix filtering RTR CAN frames

### PR DESCRIPTION
**Pull request by talih0**
The mcp251xfd doesn't apply hardware filtering on the RTR flag. The frame is written to the fifo regardless of the flag. Thus we need to explicitly check that the frame matches the stored filter before notifying the user. Also if the frame doesn't match, we need check whether another stored filter matches the frame.

After this change, tests receive_ext_id_rtr and receice_std_id_rtr
are no longer skipped and successfully pass in tests/drivers/can/api.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@henrikbrixandersen ping

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Not all CAN controllers support RTR filtering. This is allowed by the Zephyr CAN API and API tests. 

I have just opened another PR for removing software-based RTR filtering from the Bosch M_CAN driver (#65058).

**Comment by talih0** [comment]
Closing the RTR filtering PR for now. 
@henrikbrixandersen, I've moved the other commits to https://github.com/zephyrproject-rtos/zephyr/pull/65435

**Comment by talih0** [comment]
Closing the RTR filtering PR for now.
@henrikbrixandersen, I've moved the other commits to https://github.com/zephyrproject-rtos/zephyr/pull/65435

**Pull request closed without merging**
