### PR TITLE
tests: subsys/fs/nvs: Move to new ztest api

### PR DESCRIPTION
**Pull request by simhein**
Convert nvs tests to use new ztest API

related: https://github.com/zephyrproject-rtos/zephyr/issues/47002

Signed-off-by: Simon Hein <SHein@baumer.com>

### CODE REVIEW

**Comment by carlescufi** [comment]
@Laczen @nvlsianpu can you please take a look?

**Comment by Laczen** [comment]
@simhein, where is the new ztest api documented ? https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/develop/test/ztest.rst seems to be about the old API.

**Comment by simhein** [comment]
@Laczen Yes that is true in the documentation is only the old API described. I think @aaronemassey is working on this and will update the documentation.

I used the https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/testsuite/ztest/include/zephyr/ztest_test_new.h as "documentation" and the description of the issue #47002 to migrate the tests into the new API

**Comment by Laczen** [comment]
> @Laczen Yes that is true in the documentation is only the old API described. I think @aaronemassey is working on this and will update the documentation.
> 
> I used the https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/testsuite/ztest/include/zephyr/ztest_test_new.h as "documentation" and the description of the issue #47002 to migrate the tests into the new API

I am having doubts whether this test is using the new API as intended. I would expect the setup function to return a pointer to the fs (instead of NULL) and the tests to use this as their input. Of course with the limited documentation this is only speculation from my side. The test will be OK, but it would not be an example for new users to develop new tests.

**Comment by simhein** [comment]
> > @Laczen Yes that is true in the documentation is only the old API described. I think @aaronemassey is working on this and will update the documentation.
> > I used the https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/testsuite/ztest/include/zephyr/ztest_test_new.h as "documentation" and the description of the issue #47002 to migrate the tests into the new API
> 
> I am having doubts whether this test is using the new API as intended. I would expect the setup function to return a pointer to the fs (instead of NULL) and the tests to use this as their input. Of course with the limited documentation this is only speculation from my side. The test will be OK, but it would not be an example for new users to develop new tests (if my speculation is correct).

New documentation PR https://github.com/zephyrproject-rtos/zephyr/pull/47569 was merged I will update this PR with the changes according to the documentation

**Comment by simhein** [comment]
@Laczen I have updated the PR and now use the new Ztest fixture for the nvs fs and the sim stats. Also ZTEST_F is used instead of ZTEST which provides the fixture to every test function

**Review by Laczen — DISMISSED** [review]
Looks good to me.

**Comment by simhein** [comment]
@nvlsianpu Can you please take a look on the PR?

**Review by de-nordic — DISMISSED** [review]

**Comment by carlescufi** [comment]
@simhein please rebase, thanks!

**Comment by simhein** [comment]
> @simhein please rebase, thanks!

@carlescufi rebase done.

**Review by nvlsianpu — APPROVED** [review]

**Review by Laczen — APPROVED** [review]

**Pull request merged**
