### PR TITLE
Bind to non default interface if using unspecified address

### PR DESCRIPTION
**Pull request by jukkar**
If we have multiple network interfaces, then bind to proper interface as decided by destination IP address.
To test this more easily, I added VLAN support to echo-server in second commit.

### CODE REVIEW

**Comment by leodido99** [comment]
Tested on my setup and works as advertised. Thanks

**Comment by pfalcon** [comment]
@jukkar: So, can you explain how this fixes https://github.com/zephyrproject-rtos/zephyr/issues/9935 ?

Let's look at the sequence:

1. A new context is created (remote addr not set).
2. net_context_connect() is called, passed remote addr.
3. One of the first things net_context_connect() does is calling bind_default() (remote addr still not set on context).
4. bind_default() is not passed anything but context. It calls net_context_bind() which you patch.
5. Your patch selects outgoing iface based on context->remote, which is again, not set.

So, this patch is good, but doesn't seem to be enough to fix #9935. To fix that, bind_default() call should be moved until after the addr from input param is copied into context->remote.

But if you see what the code in net_context_connect() does is that while it sets context->remote, it also caches context->local in a local var. And ->local will be now updated with these changes to net_context_bind().

Why it does that caching is i beyond me, and it's needed only for the TCP case, as it gets passed to net_tcp_connect(). But net_tcp_connect also gets passed context ptr, so would have access to local/remote addrs from it. Tell me now what requires cleanup in the IP stack...

So, let me know if you'd like this to be approved ahead of following fixes - but please remove "Fixes: #9935". Or let me know if you'd like to do follow up with the above. I'd be glad to join in with fixing that, but I'm packing for a conference next week, so might be not able to get it for a couple of weeks or so. Thanks.

**Comment by jukkar** [comment]
Fixed to pass sanity tests.

**Comment by jukkar** [comment]
recheck

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
