### PR TITLE
samples: up_squared: gpio_counter: Remove sample code

### PR DESCRIPTION
**Pull request by galak**
The gpio_counter does not build, the code references defines that don't
exist anymore in the tree.  Remove the test since its doesn't compile
and isn't every built by sanitycheck.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
please file a bug and it will be fixed.

@dcpleung  can you please it and add the sample to sanitycheck?

**Comment by galak** [comment]
Opened issues #10993 and #10994

**Comment by dcpleung** [comment]
PR #11006 should fix the build errors.

**Comment by nashif** [comment]
lets close this one now that we have a fix.

**Pull request closed without merging**
