### PR TITLE
SPI: async methods update

### PR DESCRIPTION
**Pull request by tbursztyka**
Using only struct k_poll_signal has proven to be too limited. (It's an issue for sensor subsystem for instance)

### CODE REVIEW

**Comment by teburd** [comment]
I think its great to create convenience around using other IPC mechanisms. However, I would prefer to see this done in a different way by giving a function pointer and void * to the drivers with conveniences around using various IPC mechanisms to help ensure correct usage. The docs and samples can all show using IPC mechanisms and enforce this mentality the right way is using kernel objects not callbacks in almost all cases.

The benefits of this route are
1. No branching required in the ISR
2. No struct/async func changes needed for new or custom notifiers (new IPC of the week comes along...)
3. Custom behavior is allowed, but could induce some warnings in the default Kconfig setup
    Ex: Check the pointer given as a callback without turning off some Kconfig flag, this dumps warnings in your face in the logs.

Perhaps some friendly macros might help, and be the default in samples and docs.

Ex: 
``` c
#define sem_notifier(sem) &sem_async_notify, sem

spi_transcieve_async(spi_dev, config, tx_bufs, rx_bufs, sem_notifier(mysem));
```

I don't dislike the struct object, and it could support a callback as well, but there are some other reasons to reconsider the callback with a void* userdata param.

**Comment by tbursztyka** [comment]
Updated the API with a specific SPI_ASYNC_MODE_CALLBACK (to use with much care) and more embedded documentation

**Comment by UnicycleBloke** [comment]
This looks like a good improvement, but I am concerned about the size of the image. Would it make sense for the preferred notification method to a compile time configuration option to reduce baggage? For example, my application might only use the callback method.

Is there a similar initiative for I2C? UART? It would better to have some kind of uniform vision across the APIs for this kind of thing.

**Comment by tbursztyka** [comment]
> This looks like a good improvement, but I am concerned about the size of the image. Would it make sense for the preferred notification method to a compile time configuration option to reduce baggage? For example, my application might only use the callback method.

Callback is the biggest object there (it's a union: it will be the size of the biggest object in it). Opting out the callback could be on the other side, something to consider.

> Is there a similar initiative for I2C? UART? It would better to have some kind of uniform vision across the APIs for this kind of thing.

Yes, actually the idea is to try it out on SPI. Once proven to fit people needs and that it works well, we'll probably generalize the method.

**Comment by UnicycleBloke** [comment]
> Callback is the biggest object

Actually I was thinking more about the code. It seems like the code would switch on the notification method even if I only used, say, callbacks. Would it make sense to have a compiler option to remove the redundant code? Maybe I misunderstood.

**Comment by tbursztyka** [comment]
> > Callback is the biggest object
> 
> Actually I was thinking more about the code. It seems like the code would switch on the notification method even if I only used, say, callbacks. Would it make sense to have a compiler option to remove the redundant code? Maybe I misunderstood.

The code, like just this tiny function there: https://github.com/zephyrproject-rtos/zephyr/pull/43102/commits/d0f708c8f7dae7474d9972bff2a3d00741d77eea#diff-d7395fd8923a57e55e91609c974e745addf376984886245b0771a8e8a9ed6beeR176

? We are talking of just a tiny bunch of bytes here, probably not even half a kb.

**Comment by UnicycleBloke** [comment]
> > > Callback is the biggest object
> > 
> > 
> > Actually I was thinking more about the code. It seems like the code would switch on the notification method even if I only used, say, callbacks. Would it make sense to have a compiler option to remove the redundant code? Maybe I misunderstood.
> 
> The code, like just this tiny function there: [d0f708c#diff-d7395fd8923a57e55e91609c974e745addf376984886245b0771a8e8a9ed6beeR176](https://github.com/zephyrproject-rtos/zephyr/commit/d0f708c8f7dae7474d9972bff2a3d00741d77eea#diff-d7395fd8923a57e55e91609c974e745addf376984886245b0771a8e8a9ed6beeR176)
> 
> ? We are talking of just a tiny bunch of bytes here, probably not even half a kb.

Tiny overall, or tiny difference? Half a KB is significant. My client has a 64KB ROM. A modest test application consumed 40KB.

**Comment by UnicycleBloke** [comment]
> If that's a real zephyr test application, please note that it embeds zephyr test framework, which is at least around 20kb

I meant a toy application with some GPIO, a PWM, a UART (async). and a tiny bit of logging. I was not much impressed by how large this image was. I tried west build -r rom_report and saw that it was mostly Zephyr components being much larger than I expected.

**Comment by tbursztyka** [comment]
> Out of curiosity, I had a try using `tests/drivers/spi/spi_loopback` with frdm_k64f. Surprisingly, there's actually one kb (1052b to be precise) of difference, if I try to minimize `async_notify` to the only callback case.

Indeed, and it's not the added code that adds up, it's the unilateral calls to k_mutex, k_sem, k_work stuff etc... Which means the linker will embed what's necessary, even if it's unused. Forgot about it...

We will need a seamless way to manage that. Or else it will be a burden having new config options here and there. You might want to use a k_sem object and not wanting to link again k_mutex or/and k_work etc.. so having a config option for cb object only is not going to be the solution.

**Comment by nashif** [comment]
@tbursztyka  you never commented or gave any response to the proposal from @teburd https://github.com/zephyrproject-rtos/zephyr/pull/43102#issuecomment-1050011561. Can you please look at this approach as an alternative?

**Comment by tbursztyka** [comment]
> @tbursztyka you never commented or gave any response to the proposal from @teburd [#43102 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/43102#issuecomment-1050011561). Can you please look at this approach as an alternative?

Well, unless I am missing something, it's quite the same thing as my proposal, minor the fact it misses the status code that needs to be provided to the user when this one uses a semaphore, a mutex or a work (which is something you need: the user has to know if the transaction went well or not). And the fact that it's not explicit in the object in can deal with in the API front. (besides some documentation I guess). I am personally not super found of such opaque way, I like the API code to be self-explanatory (or almost)

It has the same issue as unilaterally calling k_sem_*/k_mutex_*/k_workq_* in spi_context side, it obviously also needs to check the type of callback (instead of my proposal checking a "mode", ok that saves 4bytes but it's not like you are going to have 100 async structs).

@teburd was mostly requiring a callack/user_data mode for good reasons, which is addressed in my proposal as well.

**Comment by teburd** [comment]
> > @tbursztyka you never commented or gave any response to the proposal from @teburd [#43102 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/43102#issuecomment-1050011561). Can you please look at this approach as an alternative?
> 
> Well, unless I am missing something, it's quite the same thing as my proposal, minor the fact it misses the status code that needs to be provided to the user when this one uses a semaphore, a mutex or a work (which is something you need: the user has to know if the transaction went well or not). And the fact that it's not explicit in the object in can deal with in the API front. (besides some documentation I guess). I am personally not super found of such opaque way, I like the API code to be self-explanatory (or almost)
> 
> It has the same issue as unilaterally calling k_sem__/k_mutex__/k_workq_* in spi_context side, it obviously also needs to check the type of callback (instead of my proposal checking a "mode", ok that saves 4bytes but it's not like you are going to have 100 async structs).
> 
> @teburd was mostly requiring a callack/user_data mode for good reasons, which is addressed in my proposal as well.

Primarily yes, for the use cases I care about callbacks are the most useful option. I think some of the feedback from others here is telling that I'm not alone. There shouldn't be a cost to only using one of the options in ROM or processing time. Callbacks have no inherent cost other than the two words to store. The object has seemingly both a ROM and branch in ISR costs.

I agree that the status code should be provided back, that too could be done with the callback setup with type specific data provided in a common async.h header perhaps along with the function symbols that use them.

``` c
struct async_sem data;
spi_transcieve_async(spi_dev, config, tx_bufs, rx_bufs, async_sem_fn, &data);
k_sem_take(&data.sem, K_FOREVER);
if(data.status != 0) { LOG_ERR("tranfer failed"); }
```

So perhaps even clearer still. The linker could still GC unused stuff like normal presumably. No branch logic required in an ISR. This seems genuinely useful in many scenarios to me and has zero cost other than some required documentation pushing people towards using the _async calls this way.

I also have some future ideas for improving async I/O in a larger way that maybe aligns closer to the safer, ISR context avoiding callbacks that are otherwise here. That could be enabled easier with a callback today.

**Comment by tbursztyka** [comment]
@teburd I completely missed the fact you provide a generic cb for sem handling (same for mutex etc...) thus enabling an easy use for most cases (i.e. the non-cb ones, enabling quick macros for setting it up), thus the branching going away indeed.

**Comment by teburd** [comment]
@tbursztyka I'm working on prototyping this out in the context of an i2c_transfer_async, and I'd really love your feedback once I have something to show

**Comment by tbursztyka** [comment]
> @tbursztyka I'm working on prototyping this out in the context of an i2c_transfer_async, and I'd really love your feedback once I have something to show

Definitely yes

**Review by jackrosenthal — APPROVED** [review]

**Pull request closed without merging**
