### PR TITLE
TF-M: provide option for non-secure targets to request TF-M to issue system resets

### PR DESCRIPTION
**Pull request by ioannisg**
Add the infrastructure to issue system resets for Non-Secure Cortex-M builds with TF-M.

TF-M does not allow Non-Secure system reset by default. This needs to be done with a non-secure callable API.
This PR:
- provides this functionality for Non-Secure builds to request system resets, using tfm_platform_system_reset
- introduces functionality to initialize the TFM NS API at boot time
- ~~fixes dependencies for BUILD_WITH_TFM~~
- ~~introduces an option that signifies that the default NS interface is used (native), and sets up the required dependencies.~~
- implements the TF-M NS interface, natively, in Zephyr, using directly the required mutex APIs

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
It turns out you don't need the native interface or the CMSIS support. The samples had their own workarounds, and I have pulled it out into its own file in https://github.com/zephyrproject-rtos/zephyr/pull/33553. See if it solves your problem.

**Comment by ioannisg** [comment]
> @ioannisg It turns out you don't need the native interface or the CMSIS support. The samples had their own workarounds, and I have pulled it out into its own file in #33553. See if it solves your problem.

Thanks for the proposal @oyvindronningstad. I had also seen this myself while browsing the samples. However, I think that Zephyr should have an option to support the native TF-M interface, which based on CMSIS RTOS V2, as community might prefer that one instead of whatever we would like to define ourselves.

The interface you present in #33553 should be the foundation of Zephyr's TF-M NS interface; currently it is minimal, so we need to do enhancements there.

**Comment by oyvindronningstad** [comment]
> However, I think that Zephyr should have an option to support the native TF-M interface, which based on CMSIS RTOS V2, as community might prefer that one instead of whatever we would like to define ourselves.

@ioannisg I don't see much reason though, since it's not really native. The osMutexAcquire eventually leads to a k_mutex_lock, so with the zephyr version we just cut out the indirection and call k_mutex_lock directly. I might be missing something though.

**Comment by ioannisg** [comment]
@oyvindronningstad i dragged your commit into this PR, which now introduces the Zephyr, (native) NS interface.

**Comment by oyvindronningstad** [comment]
be01fd87fbcfe78ad315ed9bc9c22824e6401777 can be merged into a14eb1575c81d361b162e86e7cdcfe824de3afb1 since it is where the actual file is removed.

**Review by oyvindronningstad — APPROVED** [review]
LGTM. No comments except the merging of commits

**Comment by ioannisg** [comment]
> LGTM. No comments except the merging of commits

The reason that i pulled this out was to ease reviewing, as it does not have anything to do with moving the NS interface, it is a minor cleanup patch. But, since it is part of your original commit, actually, I will pull this back, if you insist  @oyvindronningstad  :) :)

**Comment by ioannisg** [comment]
@oyvindronningstad thanks for cooperating on this PR, btw.

**Review by microbuilder — APPROVED** [review]

**Comment by ioannisg** [comment]
Rebased, to get TF-M v1.3.0 -RC1

**Comment by ioannisg** [comment]
@oyvindronningstad @microbuilder I added a patch to disable Audit Log for profile:medium builds, due to the upstream bug reported here: https://developer.trustedfirmware.org/T907

**Pull request merged**
