### PR TITLE
drivers: clock_control: clock_control_ra.c: clock divider fix

### PR DESCRIPTION
**Pull request by iandmorris**
The clock divider value is not being applied as the address of the register to which it is being written is incorrect. A check of all RA MCU datasheets confirms that, in all cases, the SCKDIVCR register is at an offset of 0x20 (and not 0x21).

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]
LGTM

**Comment by iandmorris** [comment]
@nordic-krch, would you mind taking a look at this when you get time. thanks!

**Review by nordic-krch — APPROVED** [review]

**Comment by iandmorris** [comment]
@henrikbrixandersen, do I need to do something else to get this merged? I see one of the tests failed but I believe this was due to a lack of resources, rather than anything in this fix.... Should I rebase and push again just to get the tests to re-run (although I think that will require people to approve again)?

**Comment by nordic-krch** [comment]
@iandmorris  yes you can try to rebase. and yes that will require another round of approvals.

**Review by nashif — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
