### PR TITLE
modules: tfm: Fix cmake warnings for unused variables

### PR DESCRIPTION
**Pull request by joerchan**
Fix cmake warnings for TF-M build system when PSA tests are not enabled.
This produces the following warnings:
"
CMake Warning:
  Manually-specified variables were not used by the project:

    PSA_TOOLCHAIN_FILE
    TOOLCHAIN
"

These warnings can point to cache or config variables being updated in
the TF-M build system so keep this free of warnings.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Review by microbuilder — APPROVED** [review]

**Review by SebastianBoe — APPROVED** [review]

**Comment by microbuilder** [comment]
Is it worth putting some sort of comment here to indicate why the `inherit` value is needed in this case, since the reason will be lost over time? It's available in the commit history, but putting a comment above that block to give some context might help in the future if the same method is used in other TF-M repos to pass the toolchain up to TF-M, or just to put a sign post down for future debugging.

**Comment by SebastianBoe** [comment]
If this were documented then something like this:

PSA_ARCH_TEST is an independent project and build system and needs it's own toolchain configuration. This is done by setting toolchain to INHERIT. When INHERIT is configured we can use some downstream patches to fix the toolchain configuration.

The above is not explained very well, but is the best I can remember. We have some downstream patches related to toolchain configuration that we should have upstreamed. Sorry about that.

**Comment by joerchan** [comment]
I didn't understand that unfortunately. Is TOOLCHAIN a PSA/TFM variable, or is this cmake behavior?
PSA_TOOLCHAIN_FILE should control the PSA toolchain, so not sure what this does in addition to that.

**Comment by SebastianBoe** [comment]
It's a PSA variable.

It sets the type of toolchain, as opposed to the path.

The type again changes which toolchain config files are sourced.

The INHERIT config file that is sourced is fairly useless, so we only set it to INHERIT so that the other config files don't corrupt the build IIRC.

Sorry for being vague, I am being as specific as I can, wrt. what I remember.

**Pull request merged**
