### PR TITLE
drivers: dma: stm32 dma source and dest data size must be equal

### PR DESCRIPTION
**Pull request by FRASTM**
This PR will check the source and dest data width of the dma channels
Both value must be equal (to 1 for BYTE, 2 for HALF-WORD, 4 for WORD data size), else the use case is not supported. 
It also simplifies the dma_stm32_width_config function.

This is verified with an error raised `E: source and dest data size differ.`
when  using a `tests/drivers/dma/loop_transfer/dma.c `where, for example, :
	dma_cfg.source_data_size = 1U;
	dma_cfg.dest_data_size = **2**U;

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
We can take even more advantage from this simplification:
`source_periph` could be removed from `dma_stm32_width_config`
The related code within this function (if/else) could be removed as well.

**Comment by FRASTM** [comment]
in case the `dma_stm32_width_config()` is simplified (and even possibly suppressed), 
we would lose all the code, in case, later, the `config->source_data_size` and `config->dest_data_size` are different in a further usecase.

**Comment by FRASTM** [comment]
to simplify code, the `dma_stm32_width_config()` function is suppressed as both config->source_data_size and config->dest_data_size are equal, 
(`msize` unused var is also removed)

**Review by erwango — CHANGES_REQUESTED** [review]
No that call to `dma_stm32_width_config` is suppressed, 
`dma_stm32_width_config` could be safely deleted

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
