### PR TITLE
Bluetooth: BAP: Shell: Fixed cmd_stream_qos

### PR DESCRIPTION
**Pull request by LuckeTech**
Fixed cmd_stream_qos. Added missing initialisation of variable int err.

### CODE REVIEW

**Review by Thalley — CHANGES_REQUESTED** [review]
Seems like it was only missing in `cmd_stream_qos` (which you also mention in your commit message). Can you please revert all the other (unnecessary) changes? 

Your commit title should also be `Bluetooth: BAP: Shell: Fixed cmd_stream_qos`

**Comment by Thalley** [comment]
> > Seems like it was only missing in `cmd_stream_qos` (which you also mention in your commit message). Can you please revert all the other (unnecessary) changes?
> > Your commit title should also be `Bluetooth: BAP: Shell: Fixed cmd_stream_qos`
> 
> I fixed the same problem on a different function and created a PR. [Bluetooth: BAP: Shell: Fixed cmd_sync_broadcast](https://github.com/zephyrproject-rtos/zephyr/pull/64132)

You can add that change to this PR as well :) Either in the same commit, or a new one

**Comment by Thalley** [comment]
@LuckeTech please squash your commits :)

**Comment by LuckeTech** [comment]
> Seems like it was only missing in `cmd_stream_qos` (which you also mention in your commit message). Can you please revert all the other (unnecessary) changes?
> 
> Your commit title should also be `Bluetooth: BAP: Shell: Fixed cmd_stream_qos`

**Comment by LuckeTech** [comment]
> Seems like it was only missing in `cmd_stream_qos` (which you also mention in your commit message). Can you please revert all the other (unnecessary) changes?
> 
> Your commit title should also be `Bluetooth: BAP: Shell: Fixed cmd_stream_qos`
Done.

**Review by Thalley — APPROVED** [review]

**Review by larsgk — APPROVED** [review]

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]
Please fix the commit message:

- Add "signed-off-by: line. See https://docs.zephyrproject.org/latest/contribute/guidelines.html#developer-certification-of-origin-dco

**Pull request closed without merging**
