### PR TITLE
samples: Bluetooth: Mesh: remove support nrf51DK platform in ble mesh samples and tests 

### PR DESCRIPTION
**Pull request by alxelax**
1. Remove nrf51dk* platform from ble mesh samples
2. Remove nrf51dk* and microbit platforms from ble mesh tests

Reasons: 
1. nrf51 was discontinued quite long time ago.
2. nrf51 has low RAM size that is 98-99% full even with the very reduced configuration. nrf51 usage doesn't have sense for any practical ble mesh solutions.
3. microbit v1 uses nrf51 chip.
4. microbit v1 platform has been left as available platform in mesh samples for demonstrations and education purposes.

### CODE REVIEW

**Review by kartben — DISMISSED** [review]
The README for mesh_demo needs to be updated as it refers to microbit
The is also a microbit.c file (+ reference to it in CMakesLists.txt that probably needs to be removed too? Unless it can be easily adapted to provide similar functionality for microbit v2 (which would be probably be great)

**Comment by alxelax** [comment]
> The README for mesh_demo needs to be updated as it refers to microbit The is also a microbit.c file (+ reference to it in CMakesLists.txt that probably needs to be removed too? Unless it can be easily adapted to provide similar functionality for microbit v2 (which would be probably be great)

Hi @kartben, microbit support is still left for `mesh_demo` and `mesh` sample apps. I guess any documentation changes are not required.

**Comment by carlescufi** [comment]
Labeled DNM until we get a conclusion on what to do with nRF51.

**Comment by kartben** [comment]
> > The README for mesh_demo needs to be updated as it refers to microbit The is also a microbit.c file (+ reference to it in CMakesLists.txt that probably needs to be removed too? Unless it can be easily adapted to provide similar functionality for microbit v2 (which would be probably be great)
> 
> Hi @kartben, microbit support is still left for `mesh_demo` and `mesh` sample apps. I guess any documentation changes are not required.

Sorry, yes, I looked at the changes to quickly, my bad.

**Review by Andrewpini — DISMISSED** [review]

**Comment by Balaklaka** [comment]
Should this be added to the release notes?

**Comment by alxelax** [comment]
> Should this be added to the release notes?

It isn't removing nrf51 completely. If anybody wants he\she can still build it. This PR just removes it from CI and from tests.

**Review by cvinayak — DISMISSED** [review]
board.h
microbit.conf
microbit_gatt.conf
microbit.c

Should not be removed, right?

**Comment by alxelax** [comment]
> board.h microbit.conf microbit_gatt.conf microbit.c
> 
> Should not be removed, right?

These files are still there for samples. I only removed them for the test (as we discussed).

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@kartben please take another look

**Review by PavelVPV — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by jori-nordic** [comment]
> It isn't removing nrf51 completely. If anybody wants he\she can still build it. This PR just removes it from CI and from tests

That pretty much means "nrf51 is not supported any more", and people will get frustrated because they can't easily see which boards are really supported without having to grep the CI/tests yaml files. 
We had such a person raise a ticket for a Bluetooth sample, and while his delivery wasn't the best, he still has a valid point.

**Pull request merged**
