### PR TITLE
kconfig: remove Enable from boolean prompts

### PR DESCRIPTION
**Pull request by gmarull**
According to Kconfig guidelines, boolean prompts must not start with
"Enable...". This PR removes all usages of `bool "Enable..."` and introduces a CI check to prevent new cases in the future. Note that due to these changes, certain prompts may need some tweaks (check 2nd commit for some I've already adjusted).

Note that Kconfig symbols in modules (e.g. LVGL) are ignored since we have no control on them.

### CODE REVIEW

**Review by de-nordic — CHANGES_REQUESTED** [review]
Shouldn't the requirement be covered by checkpatch rather than CI only?

**Review by nashif — CHANGES_REQUESTED** [review]
not really sure about this treewide thing and who started it, but it does not make sense to me and should not be used in commits, it seems like it is used to pass CI only.

Instead, and since you are changing kconfig primarily, why not `kconfig: ...`

**Comment by gmarull** [comment]
> Shouldn't the requirement be covered by checkpatch rather than CI only?

We already do other Kconfig checks in a similar way, and they can also be run locally, e.g. `python3 scripts/ci/check_compliance.py -m Kconfig`.

**Review by nashif — APPROVED** [review]

**Review by nandojve — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
mgmt/mcumgr, fs (VFS), storage/flash_map and drivers/flash look OK. Thanks.

**Review by carlescufi — APPROVED** [review]

**Review by npitre — APPROVED** [review]

**Pull request merged**
