### PR TITLE
Bluetooth: controller: split: Fix Rx reserved for conn cmplt

### PR DESCRIPTION
**Pull request by cvinayak**
When both central and peripheral are supported, one each Rx
node will be needed by connectable advertising and the
initiator, hence conditionally set the count.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@thoh-ot @mtpr-ot could you please review?

**Review by mped-oticon — APPROVED** [review]
Makes good sense from PR description. Would be nice to have that in code too as commentary.

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Comment by cvinayak** [comment]
> 
> 
> Makes good sense from PR description. Would be nice to have that in code too as commentary.

Updated the commit with comment added in code too.

**Pull request merged**
