### PR TITLE
sensor: vl53l0x: make xshut pin control optional

### PR DESCRIPTION
**Pull request by avisconti**
The XSHUT pin, used to shutdown the device when it is not
in current use, is optional and some boards (like ArgonKey)
leave it tied to vdd. So, the driver must provide a way to
make this part configurable.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Comment by avisconti** [comment]
@erwango

**Comment by avisconti** [comment]
@ydamigos 
Can you add label also here pls? Area is sensor again.

**Review by galak — APPROVED** [review]

**Review by VVESTM — CHANGES_REQUESTED** [review]
Hi @avisconti, is it possible to also update the default prj.conf or the README.rst ? 
By default, the sample has been done on disco_l475_iot1, so I would like to have this xshut enabled in the prj.conf, or at least commented in this file. (So user can easily activate it)

Else, I'm OK with the change.

Thanks

**Comment by avisconti** [comment]
@VVESTM 
Do you mean modify prj.conf of vl53l0x sample?
I think that code should stay independent from which board it is running on. So, maybe, it would be better to change configuration inside disco_l475_iot1 board. For example, I may modify the disco_l475_iot1_defconfig file. What do you think?

**Comment by avisconti** [comment]
No, found it!
I would rather change boards/arm/disco_l475_iot1/Kconfig.defconfig
There is already a section for defining vl53l0x xshut stuff!!
@VVESTM

**Comment by VVESTM** [comment]
@avisconti 
Yes, you're right, you can add the information in boards/arm/disco_l475_iot1/Kconfig.defconfig file.

**Review by VVESTM — APPROVED** [review]

**Comment by VVESTM** [comment]
@avisconti 
Thanks for this update !

**Review by ydamigos — APPROVED** [review]

**Comment by avisconti** [comment]
@VVESTM @ydamigos 
I do not have the disco_l475_iot1, so I was not able to test it on that particular board. 
But it should work well as before, because the XSHUT code is correctly compiled in.

**Comment by VVESTM** [comment]
I did the test on this disco_l475_iot1 board before to approve your PR @avisconti. It is working as before...

**Pull request merged**
