### PR TITLE
Create GitHub workflow for snapshotting open bugs

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This pull request follows up on discussion from the past few weeks' TSC and release readiness meetings.

At the TSC, I presented some basic bug analysis results using a script which can fetch bugs from GitHub, then categorize them by area, platform, and age. The TSC reaction was positive to using this framework for driving bug counts down during release times, and for tracking bugs over time.

On Discord, I followed up with @stephanosio about how to move this forward. We informally agreed that saving a snapshot of serialized bug data each week or so and uploading them to S3 for offline analysis would be best.

At subsequent release readiness meetings, I realized that the best time to do this snapshotting is right after we finish the initial triaging of that week's bugs. This ensures that priority, platform, and area are all set to the best of our ability as a project. @stephanosio suggested using a workflow_dispatch workflow for this purpose, so we can do this during the release meeting on demand.

This PR adds a simple script for saving the bugs, and a copy/pasted attempt at the workflow. I need some help from @stephanosio to finish the workflow itself and make sure I haven't missed anything there, but the bug snapshot script itself is working fine for me locally.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@mmahadevan108 @fabiobaltieri this is mostly an FYI since you're up next

**Comment by marc-hb** [comment]
> saving a snapshot of serialized bug data each week or so and uploading them to S3 for offline analysis

Imagine a world where Github issues would be version-controlled... They could try using this newfangled thing called "git"?

Couldn't resist sorry.


BTW https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types
> GitHub's **REST API** considers every pull request to be an issue, but not every issue is a pull request.

**Comment by dleach02** [comment]
> uploading them to S3 for offline analysis

how does one see this data on S3?

**Comment by mbolivar-nordic** [comment]
> how does one see this data on S3?

My expectation is that you will not see the data on S3, but you will rather see the results of the subsequent analysis.

**Comment by stephanosio** [comment]
> how does one see this data on S3?

For now, this is just "pickling" the raw data snapshot for future analysis/visualisation.

The workflow will be implemented such that it posts a link to the "pickle" uploaded to the S3 in the workflow summary (similar to how it is done for the PR docs).

Note that the reason we are using the S3 bucket instead of the workflow artifacts is that the latter may get pruned.

**Comment by mbolivar-nordic** [comment]
> Note that the reason we are using the S3 bucket instead of the workflow artifacts is that the latter may get pruned.

Any updates on this bucket and how to use it from the workflow, BTW?

**Comment by stephanosio** [comment]
> Any updates on this bucket and how to use it from the workflow, BTW?

I am testing some things in https://github.com/zephyrproject-rtos/zephyr-testing now. I will push something that works in this PR this weekend.

**Review by stephanosio — DISMISSED** [review]
Tested in https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/2352017426

**Comment by mbolivar-nordic** [comment]
Fixed a couple of bugs caught by the python linter

**Review by stephanosio — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
