### PR TITLE
Add support for free-fall triggering to sensor api

### PR DESCRIPTION
**Pull request by danb-swiftlabs**

### CODE REVIEW

**Review by MaureenHelm — APPROVED** [review]

**Review by avisconti — APPROVED** [review]
LGTM, even if I was expecting this commit in a more complete PR.

**Comment by danb-swiftlabs** [comment]
It's my first Zephyr PR. Happy to hear suggestions on things I could add.

**Comment by avisconti** [comment]
> It's my first Zephyr PR. Happy to hear suggestions on things I should add.

Basically, this PR is addin a new trigger type, which makes perfectly sense. But no one is using it yet. So, I was expecting this PR to provide commits of driver/sample that makes use of it. But maybe they will come later on.

**Comment by danb-swiftlabs** [comment]
Ah, got it. Yes this is being used by a BMX160 driver that I'm working on, however for now it is a little half-baked and therefore I was intending to keep it out of tree for now at least.

I assume in general any commits should be more polished.

**Comment by siltemc** [comment]
Hi @danb-swiftlabs  I am interested in the BMX160 driver you are working on. I am also trying to develop with this sensor. Would you be interested in sharing it? If so, would you be able to message me on the zephyr slack about it? I am @silt on slack.

**Comment by avigreen1978** [comment]
@danb-swiftlabs Can you please share that BMX160 driver?

**Pull request merged**
