### PR TITLE
doc: starting draft for 1.8 release notes

### PR DESCRIPTION
**Pull request by dbkinder**
Signed-off-by: David Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
submit to 1.8 branch, we will then push it to master once 1.8 is tagged.

**Comment by pfalcon** [comment]
I'd suggest adding something like "IP stack improvements" to "Major enhancements".

"Drivers and Sensors" could list: "UART interrupt-driven API is better defined" and "Support for pull-style console API".

**Comment by dbkinder** [comment]
Resubmitting to 1.8 branch (and fixing trailing white space :)

**Comment by dbkinder** [comment]
I'm not sure how to get this submitted to the 1.8 branch so I'm reopening it here

**Comment by dbkinder** [comment]
new PR submitted to 1.8 branch (thanks for help Anas)

**Pull request closed without merging**
