### PR TITLE
 Bluetooth: controller: Use find_lsb_set instead of custom ffs 

### PR DESCRIPTION
**Pull request by cvinayak**
Use globally available find_lsb_set in Zephyr instead of a
custom find first set function.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by jhedberg** [comment]
Is there a good reason not to use the find_lsb_set() helper that's globally available in Zephyr? On ARM (include/arch/arm/cortex_m/asm_inline_gcc.h) it simply maps to __builtin_ffs().

**Review by jhedberg — COMMENTED** [review]
See my earlier comment

**Comment by cvinayak** [comment]
@jhedberg yes, for some reason I could not find it when I initially wanted it. I will update this PR to use the builtin... please request changes this PR.

**Comment by cvinayak** [comment]
Pushed the updates.

**Review by jhedberg — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
