### PR TITLE
board: nucleo_f412zg: Configure I2C and USB

### PR DESCRIPTION
**Pull request by erwango**
Configure I2C and USB on nulceo_f412zg
It allows to run a Sensor Dashboard demo on Micropython

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Enable USB in defconfig?

**Comment by erwango** [comment]
> Enable USB in defconfig?

I didn't want to enable it by default. I think it should rather be enabled in application.
I enabled I2C as it is more generally required and have smaller footprint impact.
 Agreed this could miss consistency.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
@erwango I'm going to merge #4376 - does this need any updating for dt based on that?

**Comment by ydamigos** [comment]
>I didn't want to enable it by default. I think it should rather be enabled in application.
I enabled I2C as it is more generally required and have smaller footprint impact.
Agreed this could miss consistency.

The user should enable usb in application's prj.conf and DT overlay.

**Comment by erwango** [comment]
> @erwango I'm going to merge #4376 - does this need any updating for dt based on that?

Since usb is not enabled, I think we're good.
As mentioned by ydamigos, USB will be enabled in application with overlay (which I'll have to do in my application btw)

**Pull request merged**
