### PR TITLE
PCIe: Introduce helper to look up devices based on VID/DID

### PR DESCRIPTION
**Pull request by jhedberg**
Currently the only in-tree place that benefits from this is the ivshmem driver, but this is likely to be needed for more and more use cases whenever the BDF value isn't known up-front (e.g. in the case of removable PCIe devices).

### CODE REVIEW

**Comment by jhedberg** [comment]
I have a feeling that eventually we'll want to do centralised PCIe device enumeration and driver initialisation, so that these three-levels of for-loops don't have to be done for every device that needs looking up. I.e. drivers would instead register supported VID/DID values to a PCIe "bus driver" which would then go ahead and make callbacks to drivers whenever a matching device is found.

The one thing I'm wondering is would we still want to list such devices in DTS as well. The problem with using the new `PCIE_BDF_NONE` macro in DTS is that since we're using `reg = <bdf, id>;` the DTS parser requires the bdf to match the beginning of the node declaration, e.g. an UART with BDF 0xca00 is required to be delared as `uart2: uart@ca00 {` in DTS. So if we use `PCIE_BDF_NONE` the "header" would have identical values for multiple nodes, which is something I suspect isn't allowed.

**Comment by jhedberg** [comment]
Answering one of my concerns: I think we need to move away from `reg = <...>;` in DTS, at least for nodes that we don't know the BDF up-front. Instead, I'd suggest introducing a new optional `pcie-id` property that is mandatory if `reg = ..` isn't given for a node that sits under a PCIe bus.

**Comment by galak** [comment]
> Answering one of my concerns: I think we need to move away from `reg = <...>;` in DTS, at least for nodes that we don't know the BDF up-front. Instead, I'd suggest introducing a new optional `pcie-id` property that is mandatory if `reg = ..` isn't given for a node that sits under a PCIe bus.

So I think we should start trying to see if we can work towards encoding PCIe nodes according to devicetree spec:

Here's an example of what the dts should look like:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/platform/ce4100/falconfalls.dts#n68

Can you possible work up a dts for one of the platforms you are interested in and we can try and see what tooling improvements we need to add for PCIe support.  I can help with questions on the node properties (the reg/range property for PCI can be confusing)

**Review by finikorg — APPROVED** [review]
LGTM

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
