### PR TITLE
modules: correct cmsis kconfig folder name

### PR DESCRIPTION
**Pull request by XenuIsWatching**
The names have of cmsis_dsp and cmsis_nn underscores within them. Somehow it was still being found
within the build but not with building documents. This renames them to the correct name of the module

Also, cmsis was moved to be an external KConfig (https://github.com/zephyrproject-rtos/cmsis/commit/1abf29132e608826752e2edd1f4799a065db4031) This removes the unnecessary (but not causing any harm) source of the KConfig which is done automatically as well as adds a comment if it is not available.

### CODE REVIEW

**Review by kartben — APPROVED** [review]
Thanks!
FWIW I am still unclear on why I had local failures locally when building the documentation but nothing CI would catch.

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by SeppoTakalo** [comment]
Fixed #63159

**Comment by marc-hb** [comment]
Another, imx8m-specific regression spotted in the SOF daily build:

https://github.com/thesofproject/sof/actions/runs/6333016092/job/17200480375

cc: @dbaluta , @iuliana-prodan , @LaurentiuM1234 
```
Loaded configuration '/zep_workspace/zephyr/boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m_defconfig'
Merged configuration '/zep_workspace/sof/app/prj.conf'
Merged configuration '/zep_workspace/sof/app/boards/nxp_adsp_imx8m.conf'
warning: HAS_CMSIS_CORE (defined at modules/cmsis/Kconfig:7) has direct dependencies 0 with value n, but is currently being y-selected by the following symbols:
 - HAS_MCUX (defined at modules/Kconfig.mcux:6), with value y, direct dependencies SOC_FAMILY_KINETIS || SOC_FAMILY_IMX || SOC_FAMILY_LPC || SOC_FAMILY_NXP_ADSP || SOC_FAMILY_NXP_S32 (value: y), and select condition SOC_FAMILY_KINETIS || SOC_FAMILY_IMX || SOC_FAMILY_LPC || SOC_FAMILY_NXP_ADSP || SOC_FAMILY_NXP_S32 (value: y)

error: Aborting due to Kconfig warnings
```

**Comment by iuliana-prodan** [comment]
> Another, imx8m-specific regression spotted in the SOF daily build:
> 
> https://github.com/thesofproject/sof/actions/runs/6333016092/job/17200480375
> 
> cc: @dbaluta , @iuliana-prodan , @LaurentiuM1234
> 
> ```
> Loaded configuration '/zep_workspace/zephyr/boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m_defconfig'
> Merged configuration '/zep_workspace/sof/app/prj.conf'
> Merged configuration '/zep_workspace/sof/app/boards/nxp_adsp_imx8m.conf'
> warning: HAS_CMSIS_CORE (defined at modules/cmsis/Kconfig:7) has direct dependencies 0 with value n, but is currently being y-selected by the following symbols:
>  - HAS_MCUX (defined at modules/Kconfig.mcux:6), with value y, direct dependencies SOC_FAMILY_KINETIS || SOC_FAMILY_IMX || SOC_FAMILY_LPC || SOC_FAMILY_NXP_ADSP || SOC_FAMILY_NXP_S32 (value: y), and select condition SOC_FAMILY_KINETIS || SOC_FAMILY_IMX || SOC_FAMILY_LPC || SOC_FAMILY_NXP_ADSP || SOC_FAMILY_NXP_S32 (value: y)
> 
> error: Aborting due to Kconfig warnings
> ```

Thanks @marc-hb 
Sent a fix - https://github.com/zephyrproject-rtos/zephyr/pull/63279

**Pull request merged**
