### PR TITLE
nrf52: i2c_twim: Fix static 400uA current

### PR DESCRIPTION
**Pull request by gumulka**
Hardware error described here:
https://infocenter.nordicsemi.com/topic/errata_nRF52832_Rev2/ERR/nRF52832/Rev2/latest/anomaly_832_89.html

When using GPIOTE and TWIM and PM_DEVICE, then the device must be turned off and then on again after suspending, otherwise there is a constant 400uA current draw.

This should be seen in cooperation with https://github.com/zephyrproject-rtos/hal_nordic/pull/180

### CODE REVIEW

**Comment by MaureenHelm** [comment]
> This should be seen in cooperation with [zephyrproject-rtos/hal_nordic#180](https://github.com/zephyrproject-rtos/hal_nordic/pull/180)

Then you probably need to update `west.yml` accordingly

@anangl please take a look

**Comment by gumulka** [comment]
> Then you probably need to update `west.yml` accordingly

I did not want to link to a non-main branch in here, therefor I did not change it yet.

**Comment by MaureenHelm** [comment]
> > Then you probably need to update `west.yml` accordingly
> 
> I did not want to link to a non-main branch in here, therefor I did not change it yet.

Please see https://docs.zephyrproject.org/latest/develop/modules.html#submitting-changes-to-modules

**Comment by gumulka** [comment]
> Please see https://docs.zephyrproject.org/latest/develop/modules.html#submitting-changes-to-modules

Thank you. I was not aware of this. The DNM Label is not added and everything should be fine, I just need someone to review it.

**Comment by MaureenHelm** [comment]
> > Please see [docs.zephyrproject.org/latest/develop/modules.html#submitting-changes-to-modules](https://docs.zephyrproject.org/latest/develop/modules.html#submitting-changes-to-modules)
> 
> Thank you. I was not aware of this. The DNM Label is now added and everything should be fine, I just need someone to review it.

You need to address the twister build failures

**Comment by gumulka** [comment]
> You need to address the twister build failures

Finally managed to do just that. Now it really just needs a reviewer. :)

Could you remove the "stale" label?

**Comment by gumulka** [comment]
@anangl could I get a review from someone?

**Comment by anangl** [comment]
> @anangl could I get a review from someone?

Please see this comment: https://github.com/zephyrproject-rtos/hal_nordic/pull/180#issuecomment-2497279046.

**Pull request closed without merging**
