### PR TITLE
net: Convert drivers to new DT device

### PR DESCRIPTION
**Pull request by galak**
* Introduce networking version of the DEVICE DT APIs
* Convert ethernet drivers over to use new APIs

### CODE REVIEW

**Comment by galak** [comment]
@jukkar I kept the naming conversion that networking uses, but wonder about using `_DEFINE` instead of `_INIT` to be consistent with `device.h`?

**Review by pabigot — APPROVED** [review]
As far as I can tell the in-tree devicetree labels match the former Kconfig variables so should be fine.

**Comment by jukkar** [comment]
> I kept the naming conversion that networking uses, but wonder about using `_DEFINE` instead of `_INIT` to be consistent with `device.h`?

I do not have any preference here. Probably makes sense to rename now if we are doing it.

**Review by KozhinovAlexander — APPROVED** [review]
Since it is only renamings, no logic were and tests are passing changed: LGTM

**Review by jukkar — APPROVED** [review]

**Comment by galak** [comment]
> I do not have any preference here. Probably makes sense to rename now if we are doing it.

I went ahead and renamed the DT versions to `_DEFINE`

**Review by erwango — APPROVED** [review]

**Pull request merged**
