### PR TITLE
PWM related fixes for rpi_pico board

### PR DESCRIPTION
**Pull request by ghost**
Minor fixes to get PWM timing right and PWM samples working on rpi_pico board.

### CODE REVIEW

**Comment by yonsch** [comment]
Thanks, looking good. @burumaj , can you take a look? And @bartao , can you fix the failing test?

**Comment by bartao** [comment]
> Thanks, looking good. @burumaj , can you take a look? And @bartao , can you fix the failing test?

@yonsch, the failing test is fixed. Could you please have a look again. Thanks.

**Review by yonsch — APPROVED** [review]

**Review by simonguinot — APPROVED** [review]
I don't think that enabling the CONFIG_LOG_MODE_IMMEDIATE for the led_pwm sample is very useful. None of the LED samples use it and no one complained so far.

But it is not wrong anyway and the changes on the led_pwm sample are looking good to me.

**Comment by carlescufi** [comment]
> I don't think that enabling the CONFIG_LOG_MODE_IMMEDIATE for the led_pwm sample is very useful. None of the LED samples use it and no one complained so far.

Agreed, I will revert that change.

**Comment by bartao** [comment]
> > I don't think that enabling the CONFIG_LOG_MODE_IMMEDIATE for the led_pwm sample is very useful. None of the LED samples use it and no one complained so far.
> 
> Agreed, I will revert that change. @bartao any objections? I see you reasoned that they weren't appropriate, but did you see a significant delay between the LED status changed and the printing of the message?

@carlescufi , yes, message printing gets delayed up to 1 second in this case, which is really confusing and caused me trouble during debugging.

Right after power on, the initial booting messages get printed together with "Turned on" and the LED turns on. That is fine so far.

But when the LED turns off roughly one second later, the expected "Turned off" message is not printed.

After another second the LED brightness starts to increase again. At this point the message "Turned off", which was expected already a second ago, and the new message "Increasing brightness gradually" are printed right after each other without any delay between them. There is a delay of one second between the two events, but no delay between the corresponding messages.

When you keep it running and catch some later iteration, it can be seen that "Turned on" and "Turned off" are printed together without any delay between the messages. That is really confusing, when you know that the LED is on for a second.


Thanks for review and merging.

**Comment by simonguinot** [comment]
Honestly I don't remember such delays. But I am OK with this change anyway.

**Pull request merged**
