### PR TITLE
Bluetooth: controller: Fix HCI LE Add Device to Whitelist

### PR DESCRIPTION
**Pull request by cvinayak**
According to BT Spec v5.1 Vol 2 Part E Section 7.8.16, if the
device is already in the White List, the controller should not
add the device to the White List and should return success.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by joerchan** [comment]
This messes up the host count of how many devices are in the whitelist. 

The best way to solve that would be to remove the wl_entries check in the host. I guess we will have to let the controller handle the "is the whitelist empty" check as well.

**Comment by joerchan** [comment]
@cvinayak Is the same "rule" there for duplicate entries in the resolving list?

**Comment by carlescufi** [comment]
> @cvinayak Is the same "rule" there for duplicate entries in the resolving list?

I don't think so:

```
This command may be used at any time when address resolution is disabled in
the Controller.
The added device shall be set to Network Privacy mode.
When a Controller cannot add a device to the list because there is no space
available, it shall return the error code Memory Capacity Exceeded (0x07).
```

**Comment by carlescufi** [comment]
> This messes up the host count of how many devices are in the whitelist.
> 
> The best way to solve that would be to remove the wl_entries check in the host. I guess we will have to let the controller handle the "is the whitelist empty" check as well.

Yes, I think that's the correct approach.

**Review by joerchan — APPROVED** [review]
Will create PR to handle host whitelist count.

**Pull request merged**
