### PR TITLE
include: misc: util.h: Rename min/max to MIN/MAX

### PR DESCRIPTION
**Pull request by carlos-stuart**
**include: misc: util.h: Rename `min`/`max` to `MIN`/`MAX`**

**Possible bug? Not compatible with C++ STL**

There are issues using lowercase `min` and `max` macros when compiling a C++
application with a third-party toolchain such as GNU ARM Embedded when
using some STL headers i.e. `<chrono>`.

This is because there are actual C++ functions called `min` and `max`
defined in some of the STL headers and these macros interfere with them.
By changing the macros to UPPERCASE, which is consistent with almost all
other pre-processor macros this naming conflict is avoided.

Signed-off-by: Carlos Stuart <carlosstuart1970@gmail.com>

### CODE REVIEW

**Comment by carlos-stuart** [comment]
> Found the following issues, please fix and resubmit:
> 
> ## commit message syntax issues
> 1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Renaming min/max macros to MIN/MAX"

Fixed. Force pushed.

**Review by andyross — APPROVED** [review]
No complaints about this patch.  We probably always should have declared these as obvious macros.

But regarding C++: if you're hitting namespacing errors, you almost certainly have code doing promiscuous "using std;" which is very much discouraged by the community.  Those function templates are in a namespace for a reason, and the global namespace in the C++ standard library is deliberately unpopulated precisely to allow for interoperation with crufty C libraries like ours.

**Review by pfalcon — DISMISSED** [review]
> crufty C libraries like ours.

Let's talk improving that. Following https://github.com/zephyrproject-rtos/zephyr/issues/12129 & https://github.com/zephyrproject-rtos/zephyr/issues/12935, there would be 2 choices:

1. Namespace symbols, e.g. Z_MIN, Z_MAX. People should love that.
2. For people who don't love that, there's an option to clear partition includes into public (included by client applications) and private (included solely by Zephyr's own source code). Public headers should never include private headers, only Zephyr source files using them should include private headers. Them, MIN/MAX can be used. Maybe, because it appears to conflict with libc's sys/param.h header.

**Comment by carlos-stuart** [comment]
> No complaints about this patch. We probably always should have declared these as obvious macros.
> 
> But regarding C++: if you're hitting namespacing errors, you almost certainly have code doing promiscuous "using std;" which is very much discouraged by the community. Those function templates are in a namespace for a reason, and the global namespace in the C++ standard library is deliberately unpopulated precisely to allow for interoperation with crufty C libraries like ours.

I've been using the following C++ code as an example:

```
#include <algorithm>

#include <zephyr.h>

void main()
{
        int d = std::max({1, 2, 3});
        printk("%d\n", d);
}
```
I've been compiling with the latest GNU ARM Embedded Toolchain, with the following Kconfig configuration (on top of base defaults):

```
CONFIG_CPLUSPLUS=y
CONFIG_LIB_CPLUSPLUS=y
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_NEWLIB_LIBC=y
```

I can resolve the above (trivial) example by changing the order of the two headers, or by `#undef max` after the Zephyr header, however neither of those are ideal and become harder to implement in more complex applications.

I've included the error below for reference but it's fairly obvious:

```
../src/main.cpp:9:35: error: macro "max" passed 3 arguments, but takes just 2
         int d = std::max({1, 2, 3});
                                   ^
../src/main.cpp: In function 'void main()':
../src/main.cpp:9:22: error: cannot resolve overloaded function 'max' based on conversion to type 'int'
         int d = std::max({1, 2, 3});
                      ^~~
```

**Comment by carlos-stuart** [comment]
> > crufty C libraries like ours.
> 
> Let's talk improving that. Following #12129 & #12935, there would be 2 choices:
> 
> 1. Namespace symbols, e.g. Z_MIN, Z_MAX. People should love that.
> 2. For people who don't love that, there's an option to clear partition includes into public (included by client applications) and private (included solely by Zephyr's own source code). Public headers should never include private headers, only Zephyr source files using them should include private headers. Them, MIN/MAX can be used. Maybe, because it appears to conflict with libc's sys/param.h header.

Interesting reading through those other pull requests. I'm all for any solution and happy to take all of your steer on the best way to resolve this.

Funnily enough I've had issues with another library I'm playing with (adding support for `std::mutex` (pretty much done - so I can use `std::scoped_lock` etc.) and `std::thread` (a work in progress - possibly less useful but an interesting exercise none the less)) where the `max` macro can't be found in spite of including the Zephyr header, so I've had to define it myself just above a definition of an array of thread stacks.

**Comment by carlos-stuart** [comment]
I'll keep chasing down the issues with Shippable as I'm been manually verifying every change rather than doing a global find/replace. Hopefully catch the last of the missing changes soon.

It should then be trivial to find/replace on the patch to change the name if we want, or maybe find another solution entirely.

**Comment by pfalcon** [comment]
> It should then be trivial to find/replace on the patch to change the name if we want, or maybe find another solution entirely.

It would be definitely good to get more opinions about this change. And the timing isn't exactly best - an announcement just went that 1.14-rc1 was tagged, and the master is now in code-freeze, with only bugfixes allowed. So, it now depends whether the core maintainers would consider this a "bugfix" or not. If yes, I'd be happy to remove my -1. If no, it may spend enough time in the queue anyway. In either case, more opinions can be collected in the meantime.

**Comment by carlos-stuart** [comment]
> > It should then be trivial to find/replace on the patch to change the name if we want, or maybe find another solution entirely.
> 
> It would be definitely good to get more opinions about this change. And the timing isn't exactly best - an announcement just went that 1.14-rc1 was tagged, and the master is now in code-freeze, with only bugfixes allowed. So, it now depends whether the core maintainers would consider this a "bugfix" or not. If yes, I'd be happy to remove my -1. If no, it may spend enough time in the queue anyway. In either case, more opinions can be collected in the meantime.

Yeah, I realise the timing isn't great. I made sure my other PRs were in before the freeze as they were more important to me (as I've shown above there are workarounds for this), however since Zephyr supports both C++ userspace code and external tool chains I do wonder whether this could be considered a "bugfix" - hopefully we'll get more opinions soon. All tests are now passing at least.

Thanks for your comments.

**Comment by carlos-stuart** [comment]
@nashif Would you consider this as a bug fix? It's currently breaking code I'm developing - while it is possible to work around in trivial examples it becomes harder in code consisting of many external libraries etc.

**Review by jukkar — APPROVED** [review]
Using MIN() and MAX() LGTM. Not sure if it is really worth renaming them to Z_MIN() or Z_MAX().

**Comment by mped-oticon** [comment]
Regardless of the C++ debate, I'm all for macros being named all-caps.
Another incoherent macro is `ceiling_fraction` -- also commonly known as `CEIL_DIV`.

**Review by mped-oticon — APPROVED** [review]

**Review by loicpoulain — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Comment by carlos-stuart** [comment]
> Regardless of the C++ debate, I'm all for macros being named all-caps.
> Another incoherent macro is `ceiling_fraction` -- also commonly known as `CEIL_DIV`.

Would be pretty easy to factor into this PR if you want me to?

Any other inconsistent macros people want renaming/UPPERCASING?

**Review by nashif — APPROVED** [review]

**Comment by andrewboie** [comment]
> But regarding C++: if you're hitting namespacing errors, you almost certainly have code doing promiscuous "using std;" which is very much discouraged by the community.

Namespace doesn't matter, this is macro replacement at work.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by carlos-stuart** [comment]
Rebased on to master to resolve conflicts. Any further opinions on whether this is 'bug' like enough to make it into the LTS?

**Pull request merged**
