### PR TITLE
samples: usb: cdc_acm*: Fix device testing

### PR DESCRIPTION
**Pull request by galak**
The device testing harness for the cdc_acm & cdc_acm_composite samples
has some expected console output to tell if the sample is running
propertly.  However that output is handled via LOG_DBG() statements in
the code.  To ensure we see those LOG_DBG() statements enable
CONFIG_LOG_IMMEDIATE.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by jfischer-no — CHANGES_REQUESTED** [review]
CONFIG_LOG_IMMEDIATE=y should not be used with usb device stack because it impacts the performance of the system and will lead to timeouts during enumeration/configuration of the usb device, it may work for LOG_LEVEL_ERR only.

**Comment by galak** [comment]
> CONFIG_LOG_IMMEDIATE=y should not be used with usb device stack because it impacts the performance of the system and will lead to timeouts during enumeration/configuration of the usb device, it may work for LOG_LEVEL_ERR only.

will switch to using printk for what we need then.

**Review by jfischer-no — APPROVED** [review]

**Comment by finikorg** [comment]
@galak Do those printk really help? I think they expect that we connect via USB to the Host.

**Comment by jfischer-phytec-iot** [comment]
I have an alternative patch for that.

**Comment by jfischer-phytec-iot** [comment]
@finikorg @galak Please take a look at #18573 - commit 055d785ab49062aa0b365dc3c7fc1ddf94d1b4a7

**Comment by galak** [comment]
> @galak Do those printk really help? I think they expect that we connect via USB to the Host.

It does.  The testing harness for these tests should be improved for having communication on both sides of the USB link.  However, right now it just expects that the Zephyr side is ready.  So printk addresses the main issue of getting the output into the log.

**Review by jfischer-no — APPROVED** [review]
@galak Thanks

**Review by nashif — APPROVED** [review]

**Pull request merged**
