### PR TITLE
Net: ICMP fixes

### PR DESCRIPTION
**Pull request by finikorg**

### CODE REVIEW

**Review by tbursztyka — CHANGES_REQUESTED** [review]
s/legth/length on your 2nd patch's commit message

Also, replace icmp by icmpv4 in your commit message.

That said, maybe you should merge your 2 patches in one.

**Review by pfalcon — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by jukkar — CHANGES_REQUESTED** [review]
This conflicts with #1455

**Comment by finikorg** [comment]
@jukkar I made rebase against master just now, so I do not understand what are the conflicts

**Comment by pfalcon** [comment]
@finikorg : And yet Github shows:

~~~
Conflicting files
subsys/net/ip/l2/ethernet.c
~~~

That's because commit "net: l2: Correct debug message and avoid unneeded assignment" touches file which was already changed. It also has nothing to do with the topic of this pull request, which is "Fix ICMP length and checksum". So, my suggestions: 1) drop that commit from this PR; 2) resubmit it separately if needed; 3) in general, try to avoid putting unrelated changes into a single PR. YMMV

**Comment by finikorg** [comment]
Finally I got changes, so I rebased patchset

**Comment by pfalcon** [comment]
This will conflict with https://github.com/zephyrproject-rtos/zephyr/pull/1480. So many examples of why putting unrelated changes to a PR only causes delays with processing a PR.

**Comment by tbursztyka** [comment]
yep, better splitting PR per domain/subject.

That said, is there a way to

**Comment by tbursztyka** [comment]
( github's UI and me are not getting along very well... )

**Comment by finikorg** [comment]
This may conflict only because that ^&* line is touched on a daily basis, just merge whatever you want and I will rebase again

**Comment by finikorg** [comment]
Now I have removed the last commit

**Review by pfalcon — APPROVED** [review]
Thanks! Let me approve this patch, though I believe @tbursztyka might try to ask "is there a way to reproduce an issue which this patch fixes?" (based on yesterday's IRC discussion with @jukkar). (I myself trust that if this patch is made, then it fixes some issue.)

**Comment by tbursztyka** [comment]
@pfalcon Why commenting like that? You might want to read your irc chat more carefully, I did not raise any concern about that patchset myself.

**Comment by pfalcon** [comment]
@tbursztyka : Because:

1. Your comment at https://github.com/zephyrproject-rtos/zephyr/pull/1376#issuecomment-329085813 "That said, is there a way to" is apparently cut abruptly.

2. Yesterday on IRC, @jukkar wrote:

> &lt;jukkar1> tobur: can you check https://github.com/zephyrproject-rtos/zephyr/pull/1376, you requested changes there
> &lt;jukkar1> I wonder what kind of condition in https://github.com/zephyrproject-rtos/zephyr/pull/1376 causes the errors, I have not seen any issues with ARP regarding checksum etc

3. I generally trying to be helpful with finding a process with quick turnaround of high quality patches. This patch indeed doesn't mention when the issue it fixes happens, other people mentioned that, so I don't consider it's bad idea to mention that again, and sorry if I mis-matched 2) and 1) above, and your cut phrase was about something else (indeed, that was finger-in-the-sky guess, sorry again).

**Review by jukkar — APPROVED** [review]

**Comment by tbursztyka** [comment]
@pfalcon yep, don't guess what I could say :)  and to me this patch seems logical.
(I wanted to ask about PR dependency in my cut sentence, did not notice it sorry, I could have edited it)

@jukkar let me try these 2 patches, as ping currently does not work for me, this could fix it. (but replying to a ping works).

**Review by tbursztyka — APPROVED** [review]

**Comment by tbursztyka** [comment]
Yep, ping works again now

**Review by nashif — APPROVED** [review]

**Pull request merged**
