### PR TITLE
maintainers: make gmarull the maintainer of the device driver model area

### PR DESCRIPTION
**Pull request by gmarull**
Since I've been working on device.h for a while, I propose to become the maintainer of the device driver model in Zephyr.

### CODE REVIEW

**Review by carlocaione — APPROVED** [review]
I STRONGLY OPPOSE

**Review by carlescufi — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
Thanks for stepping up. Is @tbursztyka okay with this?

**Review by mbolivar-nordic — APPROVED** [review]
Makes sense to me.

**Review by nashif — APPROVED** [review]
needs @tbursztyka approval.

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
