### PR TITLE
drivers: Fit for missing PM callbacks

### LINKED ISSUE #21418: Crash when suspending system
**Describe the bug**
We enabled watchdog. Now when system goes to sleep crash happens.

**To Reproduce**
Enable watchdog in a application that uses power management. Wait for it. Observe crash when `sys_pm_suspend_devices` is called.

**Expected behavior**
System should just go to sleep.

**Impact**
Showstopper.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
master

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pdunaj**
Fixes #21418

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
I believe it would be more robust to switch to using `DEVICE_AND_API_INIT` which does the right thing whether or not device power management is enabled.

**Review by pabigot — APPROVED** [review]

**Comment by carlescufi** [comment]
@pdunaj can you take a look at the shippable failure?

**Comment by pabigot** [comment]
I've found there's a "play" button on the shippable page that triggers a retest, which is more effective that close/reopen.  (This failure appears to be a shippable error unrelated to this PR).

**Comment by pdunaj** [comment]
Unfortunately I don't see "play" - maybe I need to be logged in.
Hi @carlescufi , could you check if you rerun tests?

**Comment by carlescufi** [comment]
@pdunaj this is a known issue. Wait until https://github.com/zephyrproject-rtos/zephyr/pull/21451 is merged and then rebase on top of the latest master.

**Comment by pdunaj** [comment]
Rebased

**Comment by pdunaj** [comment]
@carlescufi , ready for merging

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
