### PR TITLE
Update civetweb to latest one

### PR DESCRIPTION
**Pull request by KozhinovAlexander**
Should be merged after [this](https://github.com/zephyrproject-rtos/civetweb/pull/7)

### CODE REVIEW

**Comment by gudnimg** [comment]
Note: this PR will close issue https://github.com/zephyrproject-rtos/zephyr/issues/33520

**Review by galak — APPROVED** [review]

**Review by pfalcon — COMMENTED** [review]
@Nukersson : This PR doesn't pass CI, and that may be the reason why it doesn't get further reviewing. There're at least 2 issues: a) commit message not compliant to Zephyr requirements; b) non-compliant Signed-Off-By (lacks email address).

**Comment by Nukersson** [comment]
> @Nukersson : This PR doesn't pass CI, and that may be the reason why it doesn't get further reviewing. There're at least 2 issues: a) commit message not compliant to Zephyr requirements; b) non-compliant Signed-Off-By (lacks email address).
> 

My best thanks for pointing on that. I will take care in it today.

**Comment by Nukersson** [comment]
> @Nukersson : This PR doesn't pass CI, and that may be the reason why it doesn't get further reviewing. There're at least 2 issues: a) commit message not compliant to Zephyr requirements; b) non-compliant Signed-Off-By (lacks email address).

I am also need merge from this one: https://github.com/zephyrproject-rtos/civetweb/pull/7

**Pull request closed without merging**
