### PR TITLE
 cc3200: Remove TI cc3200 SOC and LaunchXL board support

### PR DESCRIPTION
**Pull request by GAnthony**
Effectively, the CC3220 SOC replaces the CC3200.
    
This patch removes the following:
    * the imported CC3200 SDK
    * CC3200 SOC, board, DTS files.
    * adjusts other files where cc3200 was mentioned.
    
Also, it fixes explicit references to CC3200 in generic CC32xx driver files.

### CODE REVIEW

**Review by pfalcon — CHANGES_REQUESTED** [review]
Can this at least be done *after* 1.9.0 release?

**Comment by nashif** [comment]
> Can this at least be done after 1.9.0 release?

Reasoning? We are still in development phase of 1.9.0, if this needs to go, now is the right time.

**Comment by pfalcon** [comment]
Because dropping things is kinda sad. Given that 1.9.0 is *almost* frozen, would be nice to let cc3200 survive in it.

(Unless I'm missing something and cc3220 config will work on genuine cc3200 boards, which I doubt, and the commit message doesn't specify explicitly.)

**Comment by GAnthony** [comment]
The cc3200 was deprecated in Zephyr in v1.8, so this PR is actually overdue.

The cc3220 is meant to be a (better) replacement for the cc3200 (more Flash, more security, better WiFi), but has all the same peripherals as the cc3200 - so nothing is really being lost. 

Also, the cc3220 SDK has been restructured, and the cc3200 SDK doesn't fit that structure anymore.

**Review by pfalcon — APPROVED** [review]

**Pull request merged**
