### PR TITLE
tests: drivers: enable more tests for nrf54l10 and nrf54l05

### PR DESCRIPTION
**Pull request by nordic-piks**
counter_basic_api, i2s_api, i2s_speed, uart_async_api

### CODE REVIEW

**Review by miha-nordic — APPROVED** [review]

**Comment by nordic-piks** [comment]
All working fine at DK (with this change)

**Comment by nordic-piks** [comment]
This is follow-up of #81711

**Comment by nordic-piks** [comment]
The reason this is marked as Trivial is that the overlays are almost identical to the existing L15 ones, so there really no logic added at all.

**Comment by nordic-krch** [comment]
If there are almost the same as for nrf54l15dk_nrf54l15 could you move those to a common dtsi file so there is less files to maintain?

**Comment by nordic-piks** [comment]
> If there are almost the same as for nrf54l15dk_nrf54l15 could you move those to a common dtsi file so there is less files to maintain?

Good idea, thanks, changed.

**Review by nordic-segl — APPROVED** [review]

**Review by nordic-bami — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Review by nordic-pikr — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Pull request merged**
