### PR TITLE
logging: dictionary: Support unsigned integers

### PR DESCRIPTION
**Pull request by glarsennordic**
Add unsigned integer support to the log parser.

This does not change the underlying log format,
it only allows the log parser to more accurately
read the log format.

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Comment by glarsennordic** [comment]
Adding DNM until @plskeggs has a chance to review

**Review by plskeggs — APPROVED** [review]

**Comment by glarsennordic** [comment]
Keeping DNM until I do a little extra testing for good measure

**Comment by glarsennordic** [comment]
I experienced some technical difficulties tonight. I will do the thorough testing tomorrow.

**Review by nordic-krch — APPROVED** [review]

**Comment by glarsennordic** [comment]
I have now tested the following function with a variety of input numbers:

```c
static void test_number(unsigned long long int num) {
	LOG_ERR("TEST c: %c", (char)num);
	LOG_ERR("TEST d: %d", (int)num);
	LOG_ERR("TEST ld: %ld", (long int)num);
	LOG_ERR("TEST lld: %lld", (long long int)num);
	LOG_ERR("TEST i: %i", (int)num);
	LOG_ERR("TEST li: %li", (long int)num);
	LOG_ERR("TEST lli: %lli", (long long int)num);
	LOG_ERR("TEST o: %o", (int)num);
	LOG_ERR("TEST lo: %lo", (long int)num);
	LOG_ERR("TEST llo: %llo", (long long int)num);
	LOG_ERR("TEST u: %u", (unsigned int)num);
	LOG_ERR("TEST lu: %lu", (unsigned long int)num);
	LOG_ERR("TEST llu: %llu", (unsigned long long int)num);
	LOG_ERR("TEST x: %u", (unsigned int)num);
	LOG_ERR("TEST lx: %lu", (unsigned long int)num);
	LOG_ERR("TEST llx: %llu", (unsigned long long int)num);
	LOG_ERR("TEST X: %u", (unsigned int)num);
	LOG_ERR("TEST lX: %lu", (unsigned long int)num);
	LOG_ERR("TEST llX: %llu", (unsigned long long int)num);
}
```

Both binary logs and UART logs agree on all inputs I've provided with a single exception: Invalid char values are just printed as `0` on the binary logs side.

Which TBH I think is fine.

**Comment by glarsennordic** [comment]
So, to be clear, ready for merge

**Pull request merged**
