### PR TITLE
arch: arc: refactor the arc stack check support

### LINKED ISSUE #7885: em_starterkit_em7d_v22 failing multiple tests in user mode
We recently enabled user mode by default when running tests cases on hardware that is capable of it, and I am seeing a bunch of failures on this ARC board. The following tests are either hanging or crashing with an exception:

tests/kernel/msgq/msgq_api
tests/kernel/mem_pool/sys_mem_pool
tests/kernel/queue/
tests/kernel/mem_protect/mem_protect
tests/kernel/poll
tests/kernel/semaphore/semaphore
tests/kernel/stack/stack_api

### PR DESCRIPTION
**Pull request by vonhust**
* the original stack check codes have no consideration
  for userspace case. This will wrong cause possible stack
  check exception.
* this commit refactors the arc stack check support to
  support the usperspace.

* this commit fixes #7885. All the failed tests in #7885
  are run again to verify this commit. The test results are ok

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

### CODE REVIEW

**Review by ruuddw — COMMENTED** [review]
Looks ok Wayne, just two small comments:
- arch/arc/inlcude/kernel_arch_thread.h line 68 has a tab before the ;
-


- swap_macros.h: the load_stack_check_regs macro expects thread struct pointer in r2, and uses r3 as scratch. I think it's good to mention that in a comment

**Review by tyrantlizard77 — COMMENTED** [review]
Does this work correctly if a thread was running in supervisor mode, and then calls k_thread_user_mode_enter()? Are there any differences if a thread starts with K_USER, or starts in supervisor mode and then enters user mode later?

The logic in _new_thread() seems misplaced to me, not all user threads start that way.

**Comment by vonhust** [comment]
@andrewboie  I already added corresponding  codes in
`FUNC_NORETURN void _arch_user_mode_enter(k_thread_entry_t user_entry`

k_thread_user_mode_enter() will call _arch_user_mode_enter.

**Review by ruuddw — APPROVED** [review]
One more minor, triggered by Andrew's remark: the ARC specific user_mode_enter set's the K_USER flag, but that generic user_mode_enter code did that already.

**Pull request merged**
