### PR TITLE
use the right clock busses for STM32F0 series UARTs

### LINKED ISSUE #5406: UART1 on STM32F0 Series not working: errors in makro to enable clock
STM32F0 Series has no real APB2 clock, but uses APB1 GRP2 instead.

UART initialization code in drivers/serial/uart_stm32.c for UART1 (UART6 to UART8 might be effected, too, but they are not present on the SoCs I have available) tries to initialize STM32_CLOCK_BUS_APB2 but should Initialize STM32_CLOCK_BUS_APB1_2 instead.
Same for the generated LL_APB2_GRP1_PERIPH_USART1 instead of LL_APB1_GRP2_PERIPH_USART1 that would be correct for F0 Series.

My temporary fix, generic enough, that it could work as a general fix, but still not beatuiful:
https://gist.github.com/DWagenk/6c37b20b3ffd8f92646d901ec25104ee#file-uart_stm32-c-diff

Anybody here that has a better fix? maybe just having a different #define for STM32_CLOCK_UART(...) on F0 that can "translate" **APB2** to **APB1, GRP2**?

### PR DESCRIPTION
**Pull request by dwagenk**
This fixes #5406.

removed the string-concatenation in clock init macro and give full clock bus names in UART init functions instead.
@erwango please review

### CODE REVIEW

**Comment by erwango** [comment]
Side comment: This whole part of code should be removed once we're able to generate driver initialization based on dts.
Anyway, would it be possible to try something like:
 #ifdef CONFIG_UART_STM32_PORT_1
#ifdef CONFIG_SOC_SERIES_STM32F0X
#define clock_bus STM32_CLOCK_BUS_APB1_2
#else 
#define clock_bus STM32_CLOCK_BUS_APB2
#endif
UART_DEVICE_INIT_STM32(1, clock_bus, LL_APB2_GRP1_PERIPH_USART1)
#endif	/* CONFIG_UART_STM32_PORT_1 */

We might not save lines, but would make it bit easier to read/review.

**Review by erwango — CHANGES_REQUESTED** [review]
Refactoring requested

**Comment by DWagenk** [comment]
@erwango initially I thought it could be that simple, too. But it's not just the clock bus, that needs to be adjusted, but also the LL_APB2_GRP1_ becomes LL_APB1_GRP2_ on F0. And on non F0 SoCs there are different defines depending on the selected UART being an UART or an USART. On F0 they are all USARTs.
Only USART 2 and 3 are compatible between F0/non-F0 SoCs in their defines needed for initialization.

I liked the readablility of one init-block for F0 and one for non-F0 better than having the F0/non-F0 logic inside the 
#ifdef CONFIG_UART_STM32_PORT_1
[...]
#endif
blocks.



One last Idea, although I find it kind of a dirty hack:
Insert the following block @ line 365:
```c
#ifdef CONFIG_SOC_SERIES_STM32F0X
#define STM32_CLOCK_BUS_APB2               STM32_CLOCK_BUS_APB1_2
#define LL_APB2_GRP1_PERIPH_USART1         LL_APB1_GRP2_PERIPH_USART1
/* USART 2 and 3 are compatible in their defines for F0/non-F0 SoCs */
#define LL_APB1_GRP1_PERIPH_UART4          LL_APB1_GRP1_PERIPH_USART4
#define LL_APB1_GRP1_PERIPH_UART5          LL_APB1_GRP1_PERIPH_USART5
#define LL_APB2_GRP1_PERIPH_UART6          LL_APB1_GRP2_PERIPH_USART6
#define LL_APB1_GRP1_PERIPH_UART7          LL_APB1_GRP2_PERIPH_USART7
#define LL_APB1_GRP1_PERIPH_UART8          LL_APB1_GRP2_PERIPH_USART8
/* UART 9 and 10 don't exist on F0 SoCs */
#endif

and probably we should undef all of this at the end of file again...
```

**Review by erwango — APPROVED** [review]
Hopefully this part of code has limited life duration due to dts works. No need for too much nitpicks in these conditions.

**Pull request merged**
