### PR TITLE
tests: kernel: move arch-specific kernel tests under arch subdirectory

### PR DESCRIPTION
**Pull request by ioannisg**
That's a cleanup PR.

This commit moves the arm-specific and x86-specific kernel tests in 'arm'
subdirectory under tests/kernel/.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@ioannisg actually, we might consider moving those out of the kernel and putting them under tests/arch/<arch>/...

tests/kernel/static_id would then end up in tests/arch/x86/static_idt, what do you think?

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg actually, we might consider moving those out of the kernel and putting them under tests/arch//...
> 
> tests/kernel/static_id would then end up in tests/arch/x86/static_idt, what do you think?

I am not sure, actually, it is a bit of a mix, here.
For instance, zero-latency IRQs is an ARM-specific kernel feature.
RAMFUNC, or run-time NMI are ARCH-ARM features, on the other hand.

And all of them are actually using ZTEST, so they use the zephyr kernel.

That said, I am not in (stong) favor of either sub-directory, All I wanted is to have them grouped together into an "arm" subdir.

I am fine as well with putting then under tests/arch/arm.

**Comment by nashif** [comment]
@ioannisg kernel here is what is implemented in kernel/. ztest is used for all tests, not only kernel.
The idea is to have the structure of tests/ reflect where things are implemented, so if something is implemented (and configured) in arch/ it should go into tests/arch/, and from first look most of those tests are not implemeted as part of the kernel (scheduler, kernel objects) but in arch/.

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg kernel here is what is implemented in kernel/. ztest is used for all tests, not only kernel.
> The idea is to have the structure of tests/ reflect where things are implemented, so if something is implemented (and configured) in arch/ it should go into tests/arch/, and from first look most of those tests are not implemeted as part of the kernel (scheduler, kernel objects) but in arch/.

Got it @nashif, thanks. Check the updated patch; I moved, also the statid_idx test,

**Comment by ioannisg** [comment]
@aescolar pls take a quick look

**Comment by aescolar** [comment]
@ioannisg : I saw the changes, but did not think they would be problematic.

**Review by aescolar — APPROVED** [review]
No complaints from my side

**Review by MaureenHelm — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
