### PR TITLE
WIP misc: slist: Rework sys_slist_get_not_empty

### PR DESCRIPTION
**Pull request by pfalcon**
Magic spell to address #4022.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by jukkar** [comment]
I would suggest a bit more verbose commit message, it is very unclear from comment what the fix is doing.

**Comment by pfalcon** [comment]
@jukkar , yeah, expect continuation of #4022 detective. This was mostly posted to have a CI run.

**Comment by pfalcon** [comment]
> yeah, expect continuation of #4022 detective.

That went as https://github.com/zephyrproject-rtos/zephyr/issues/4022#issuecomment-336844059 , including as the last step, spotting the real issue.

This patch is no longer considered a fix, but a possible optimization, subject for more assessment. See https://github.com/zephyrproject-rtos/zephyr/pull/4350 instead.

**Comment by pfalcon** [comment]
Ok, I withdraw this patch. Checking with x86 showed that sample app's total size increased by 8 bytes, whice ARM stayed the same. Both are likely subject to code section alignment though.

Looking at the assembly, the compiler definitely had to materialize 0 to a register with this patch, which it didn't have to do before. On the other hand, the efficiency on the current code depends on compiler's reusing `node->next` as a common subexpression. If I write such code, I'd introduce an explicit variable (`sys_snode_t *next = node->next`), to make such common subexpression reuse unavoidable for the compiler, but well, GCC does CSE itself well in this case, so I guess it makes no sense to patch the code just from a paranoia that some compiler won't.

**Pull request closed without merging**
