### PR TITLE
tests: obj_tracing: account for BT semaphore

### LINKED ISSUE #5247: Object tracing test case fails in NRF boards
The test case in tests/kernel/obj_tracing fails for NRF board due to an extra  semaphore than the expected number. 

Steps to reproduce: 

- cd <ZEPHYR_BASE>/tests/kernel/obj_tracing
- mkdir build && cd build && cmake -DBOARD=nrf51_pca10028 ..
- /nrfjprog/nrfjprog --eraseall -f nrf51
- /nrfjprog/nrfjprog --program build/zephyr/nrf52_pca10040/zephyr.hex -f nrf51
- /nrfjprog/nrfjprog --reset -f nrf51

Execution log:
```

 ***** BOOTING ZEPHYR OS v1.10.0-rc2 (delayed boot 1000ms) - BUILD: Dec  4 2017 09:10:07 *****
 starting test - OBJECT TRACING TEST
 SEMAPHORE REF: 0x20001164
 SEMAPHORE REF: 0x20001148
 SEMAPHORE REF: 0x2000112c
 SEMAPHORE REF: 0x20001110
 SEMAPHORE REF: 0x200010f4
 SEMAPHORE REF: 0x20004778
 SEMAPHORE QUANTITY: 6
 FAIL - object_monitor.
 ===================================================================
 COOP: 0x20000000 OPTIONS: 0x00, STATE: 0x00
 COOP: 0x20000230 OPTIONS: 0x00, STATE: 0x00
 COOP: 0x200001c0 OPTIONS: 0x00, STATE: 0x00
 COOP: 0x20000150 OPTIONS: 0x00, STATE: 0x00
 COOP: 0x200000e0 OPTIONS: 0x00, STATE: 0x02
 COOP: 0x20000070 OPTIONS: 0x00, STATE: 0x02
 PREMPT: 0x2000129c OPTIONS: 0x00, STATE: 0x02
 COOP: 0x20000ee8 OPTIONS: 0x01, STATE: 0x00
 THREAD QUANTITY: 8
 PASS - test_thread_monitor.
 ===================================================================

```
#

The failure is found only on NRF board.

The execution log when run on qemu_cortex_m3:
```
[QEMU] CPU: cortex-m3
***** BOOTING ZEPHYR OS v1.10.0-rc2 - BUILD: Dec  4 2017 10:11:44 *****
starting test - OBJECT TRACING TEST
SEMAPHORE REF: 0x200004c4
SEMAPHORE REF: 0x200004b0
SEMAPHORE REF: 0x2000049c
SEMAPHORE REF: 0x20000488
SEMAPHORE REF: 0x20000474
SEMAPHORE QUANTITY: 5
PASS - object_monitor.
===================================================================
COOP: 0x20000000 OPTIONS: 0x00, STATE: 0x00
COOP: 0x20000208 OPTIONS: 0x00, STATE: 0x00
COOP: 0x200001a0 OPTIONS: 0x00, STATE: 0x00
COOP: 0x20000138 OPTIONS: 0x00, STATE: 0x02
COOP: 0x200000d0 OPTIONS: 0x00, STATE: 0x02
COOP: 0x20000068 OPTIONS: 0x00, STATE: 0x00
PREMPT: 0x20000504 OPTIONS: 0x00, STATE: 0x02
COOP: 0x2000027c OPTIONS: 0x01, STATE: 0x00
THREAD QUANTITY: 8
PASS - test_thread_monitor.
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

### PR DESCRIPTION
**Pull request by nashif**
On boards that enable Bluetooth by default, account for 1 more semaphore
when testing.

Fixes #5247

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
Seems a bit arbitrary and fragile to me, but not sure if we can do any better. FWIW, did you figure out exactly which semaphore this is? I'd have expected there to be multiple ones coming from Bluetooth.

**Comment by jhedberg** [comment]
Actually, if this test doesn't use/need Bluetooth, can you force CONFIG_BT=n in its configuration?

**Review by jhedberg — DISMISSED** [review]
See my earlier comments

**Comment by nashif** [comment]
> Actually, if this test doesn't use/need Bluetooth, can't you force CONFIG_BT=n in its configuration?

we could

**Pull request merged**
