### PR TITLE
spsc_pbuf: fix cache invalidation in spsc_pbuf_free

### PR DESCRIPTION
**Pull request by bluerise**
In case the read index points to the end of the packet buffer and thus wraps around, we must not invalidate the cache, otherwise we draw outside of the lines and purge data outside of our responsibility.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@andyross will you please take a look?

**Comment by MaureenHelm** [comment]
@peter-mitsis would you please take a look?

**Review by peter-mitsis — APPROVED** [review]

**Comment by mfischer** [comment]
@cfriedt

**Review by cfriedt — APPROVED** [review]

**Comment by cfriedt** [comment]
I reopened - looks like it was marked as stale and closed by the bot.

Looks fine to me otherwise.

**Comment by MaureenHelm** [comment]
@bluerise will you please rebase to rerun CI? The results are 5 months old

**Review by andyross — APPROVED** [review]
Looks like I missed this the first time around and it otherwise got dropped.  Explanation sounds correct and code looks good.  Lockless algorithms are so hard though that I sort of despair of relying on code review as a correctness check though.

Should get @nordic-krch to look at this too.

**Pull request merged**
