### PR TITLE
Bluetooth: controller: split: Move invalidation of connection handle

### PR DESCRIPTION
**Pull request by wopu-ot**
Move invalidation of connection handle when flushing TX buffers into
LLL context. Otherwise, LLL may or may not see invalidated handle
depending on mayfly scheduling.

Signed-off-by: Wolfgang Puffitsch <wopu@demant.com>

### CODE REVIEW

**Review by cvinayak — CHANGES_REQUESTED** [review]
@wopu-ot ```tx_lll_flush``` does not depend on the value of the handle, hence the code in ULL seems good the way it is now. Unless, vendor specific ```lll_conn_flush``` needs a valid handle value to perform LLL flush? 

The current invalidation is needed before the call to ```ull_conn_tx_demux``` to flush buffers in Tx FIFO from Thread context.

**Comment by wopu-ot** [comment]
Yes, `lll_conn_flush` needs a valid handle. Maybe moving the handle invalidation and the call to `ull_conn_tx_demux` to a mayfly that is spun up by `tx_lll_flush` is needed to get the ordering right? Or do you foresee any other issues with such a solution?

**Comment by mtpr-ot** [comment]
I'll take a look at the new commit

**Comment by cvinayak** [comment]
@aescolar I have pushed my commit over @wopu-ot commit, if you can get someone to check if addresses the original issue of this PR, and get some approval, I can squash the two commits before merge

**Review by mtpr-ot — APPROVED** [review]
Looks good, I approve

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
