### PR TITLE
boards: update nrf51_ble400 configurations

### PR DESCRIPTION
**Pull request by yang325**
nrf51_ble400 core board upgrades chip to nRF51822_QFAC

Signed-off-by: Freddie Yang <freddie.yang325@outlook.com>

### CODE REVIEW

**Comment by yang325** [comment]
@carlescufi As requested in issue #47272

**Review by carlescufi — DISMISSED** [review]
LGTM, thanks you!

**Comment by carlescufi** [comment]
@anangl I'd like you to take a look at this one

**Review by carlescufi — COMMENTED** [review]
@yang325 could you please add a comment in the [doc page](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/nrf51_ble400/doc/index.rst) linking to this product page:
https://www.waveshare.com/core51822-b.htm

And mentioning that this board covers Rev3 in Zephyr?

**Review by gmarull — COMMENTED** [review]
Ok if the previous version is no longer available, otherwise please add a board revision instead.

**Review by anangl — APPROVED** [review]

**Comment by yang325** [comment]
@carlescufi Could you kindly remind me if new PR is what you asked?

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
No, this is fine now.

**Pull request merged**
