### PR TITLE
lib/pthread: Fix create/join race in thread lifecycle

### LINKED ISSUE #56163: posix: pthread: race condition between pthread_create() and pthread_join()
**Previous Title**
posix_common derived test fails on some qemu platforms when the CONFIG_TICKLESS_KERNEL=n is added

**Describe the bug**
posix_common derived test fails on some qemu platforms when the CONFIG_TICKLESS_KERNEL=n is added

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 qemu_cortex_r5 and qemu_cortex_a53
 - What have you tried to diagnose or workaround this issue?
 see discussion https://github.com/zephyrproject-rtos/zephyr/pull/55208 
1. add a delay in the test_pthread_descriptor_leak loop can help
2. use tickless mode can work as well
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
No.

**To Reproduce**
1. add CONFIG_TICKLESS_KERNEL=n to prj.conf
2.  do below
```
west build -b qemu_cortex_r5 -- -DCONFIG_NEWLIB_LIBC=y
west build -t run
```

**Expected behavior**
PASS

**Impact**
some potential race condition in pthread handling

**Logs and console output**

```
*** Booting Zephyr OS build zephyr-v3.3.0-1516-g1dce3c3ee2e9 ***
...
===================================================================
START - test_pthread_descriptor_leak

    Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/pthread.c:598: posix_apis_test_pthread_descriptor_leak: (pthread_join(pthread1, &unused) is non-zero)
unable to join thread 31
 FAIL - test_pthread_descriptor_leak in 0.032 seconds
===================================================================
START - test_sleep
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/sched.c:1797
        aborted _current back from dead
E: r0/a1:  0x00000004  r1/a2:  0x00000705  r2/a3:  0xff00002c
E: r3/a4:  0x000089b9 r12/ip:  0x000242e8 r14/lr:  0x0000b2a1
E:  xpsr:  0x0000013f
E: Faulting instruction address (r15/pc): 0x0000c934
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x20038 (unknown)
E: Halting system
...
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: zephyr-v3.3.0-1516-g1dce3c3ee2e9

### PR DESCRIPTION
**Pull request by andyross**
The pthread_join() implementation was done using a condition variable and not k_thread_join(), and that's actually fatal.  It's not possible in Zephyr to guarantee a thread has exited in a race-free way without calling either k_thread_abort() or k_thread_join().

This opened a hole where an app could call pthread_join(), which would go to sleep waiting on the condition variable, which would be signaled from the exit path of the thread, and then return to call pthread_create() (and thus k_thread_create()) on the same pthread_t object (and thus the same struct k_thread) BEFORE THE EARLIER THREAD HAD ACTUALLY EXITED.

This makes the scheduler blow up, at least on SMP (I wasn't personally able to make it happen on uniprocessor configs, though the race is present always).

Rework to call k_thread_join().  There's no other correct way to do this.

Fixes #56163

### CODE REVIEW

**Comment by andyross** [comment]
Note that this may not be completely conformant to POSIX semantics.  There's a pthread_detach() implementation using that same condition variable, and I suspect these two need to be unified.  Hopefully someone with more POSIX-fu than I can explain the requirements.

But the race needs to be addressed by using k_thread_join().

**Comment by andyross** [comment]
Oh, and to be clear: I tested this with @cfriedt 's rig in #57637 which reverts some recent workarounds to make the bug more visible.

Also: the checkpatch failure is a false positive.  POSIX does indeed use positive errno values.

**Review by hakehuang — DISMISSED** [review]
nice shot.

**Comment by andyross** [comment]
I had a chance to look up pthread_detach(), btw.  And indeed, the treatment here is insufficient.  The documented behavior of pthread_detach() is that it wakes up any threads blocked in a pthread_join() call[1].  And now that that's a k_thread_join() we need some way to do that out of the scheduler (which is probably just as simple as a z_thread_wake_joiners() or something -- just a little lock around an unpend_all() call).

Let me stick a DNM on this for now, pending a little bit of thought.

[1] For the life of me, I can't understand why!  The "meaning" of the call is that the OS can clean the thread up instead of holding on to things like its result code and process ID until something retrieves them (analogous to the way unix processes live as zombies until something calls wait()).  But... that doesn't mean that you **can't** join it!  This is just inventing a special edge case when none was needed.  POSIX, I swear...

**Comment by andyross** [comment]
New version, updated as described.  This one seems to be working for me both through a full twister and on the test rig.  Please re-review.

**Comment by cfriedt** [comment]
> New version, updated as described.  This one seems to be working for me both through a full twister and on the test rig.  Please re-review. 

I unfortunately force-pushed on my branch, but I should be able to test it out without the additional commit.

Will give it a shot shortly.

**Comment by andyross** [comment]
Close this.  Patches got folded into #57637 and discussion continues there

**Pull request closed without merging**
