### PR TITLE
drivers: usb_dc_nrfx: Make USB3CV Chapter 9 Tests pass

### LINKED ISSUE #16326: USB3CV Chapter 9 Tests failures
**Describe the bug**
Following USB3CV Chapter 9 tests fail on `nrf52840_pca10056`:
- 9.12
- 9.21
- 9.16

**To Reproduce**
1. Build `hid` sample for `nrf52840_pca10056`
2. Flash
3. Run USB3CV tests

**Expected behavior**
Tests pass.

**Environment (please complete the following information):**
- Zephyr commit: 03ef375f5f4b8a2ff864f97d155a058f3ae5a07a

### PR DESCRIPTION
**Pull request by anangl**
This PR contains three patches that make it possible to pass USB3CV Chapter 9 Tests also with the `hid` sample.

Fixes #16326.

**usb: kconfig: nrf52840: Enable REMOTE_WAKEUP option only when needed**

This patch removes the "hard" selection of the USB_DEVICE_REMOTE_WAKEUP Kconfig option for USB devices made on the nRF52840 SoC. Now it's up to the application to decide if it wants to enable the option. This change makes it possible to pass the USB3CV Chapter 9 Tests for applications that don't use the remote wakeup feature, since when a USB device only reports that it supports this feature, and the mentioned option makes it to do so, one of the test cases expects the USB device to actually
perform the remote wakeup. And when the feature is not reported as supported, the test case is skipped.

**Revert "drivers: usb: usb_dc_nrfx: Set cfg.en to false on Reset"**

This reverts commit 03ef375.

The cfg.en flag contains only the state of the endpoint as seen by the shim. It is mainly used to enable the endpoints when the USB peripheral becomes ready for operation (and the USB stack may want to enable some endpoints earlier, especially the control ones, so the operation must be sometimes deferred). In particular, setting this flag to false has no effect on the actual state of the endpoint in the hardware. Moreover, this flag was set to false for all the endpoints, including the control ones which should not be disabled, so such operation actually fooled the shim.

**drivers: usb_dc_nrfx: Add pre-transfer checks if endpoint is enabled**

The shim didn't check if a given endpoint was enabled before requesting the nrfx_usbd driver to perform a read or write operation on it. In certain circumstances this led to nrfx_usbd driver being stuck in a loop waiting for the associated DMA transfer to complete.

### CODE REVIEW

**Comment by anangl** [comment]
@jfischer-phytec-iot Could you try if it fixes also #16599? I believe it will, as I can produce the same symptoms as you described there (nrfx_usbd driver stuck in the loop in `usbd_dmareq_process`) just by letting the `hid` sample run for some time (send at least one report) and then trying to start the USB3CV tests. And this PR solves the problem.

**Comment by anangl** [comment]
Changed the way of enabling `USB_DEVICE_REMOTE_WAKEUP` in the `hid-mouse` sample, so that it is done only for the nRF52840 SoC (as the feature is so far implemented only for it).

**Review by jfischer-no — APPROVED** [review]
LGTM, but it does not fix the issue #16599 as a whole, the device will still not recover from suspend request, just try out `power off` - `power on` in bluetoothctl. Anyway, lets merge this patches.

**Review by masz-nordic — APPROVED** [review]

**Comment by ioannisg** [comment]
@finikorg could you review?

**Comment by ioannisg** [comment]
> 
> 
> @jfischer-phytec-iot Could you try if it fixes also #16599? I believe it will, as I can produce the same symptoms as you described there (nrfx_usbd driver stuck in the loop in `usbd_dmareq_process`) just by letting the `hid` sample run for some time (send at least one report) and then trying to start the USB3CV tests. And this PR solves the problem.

@jfischer-phytec-iot could you address this comment?

**Review by finikorg — APPROVED** [review]
LGTM

**Comment by jfischer-phytec-iot** [comment]
>@jfischer-phytec-iot could you address this comment?

@ioannisg I did, see above.

**Comment by ioannisg** [comment]
> 
> 
> > @jfischer-phytec-iot could you address this comment?
> 
> @ioannisg I did, see above.

Yeap, sorry, missed that.

**Pull request merged**
