### PR TITLE
Increase usefulness of Makefile.export

### PR DESCRIPTION
**Pull request by mbolivar**
It's convenient for glue outside of the Zephyr build system to know which script could be used to flash an image. Let's include that in the 'outputexports' results in place of (the unused and Linux-specific) INSTALLKERNEL.

### CODE REVIEW

**Review by pfalcon — DISMISSED** [review]
@daniel-thompson : FYI

**Comment by galak** [comment]
Should we export DEBUG_SCRIPT as well?

**Review by galak — CHANGES_REQUESTED** [review]
if we do FLASH_SCRIPT you probably need to do OPENSDA_FW, PYOCD_TARGET, NRF_FAMILY, and a slew of other things (look at all the various FLASH_SCRIPTs we have)

**Comment by mbolivar** [comment]
> if we do FLASH_SCRIPT you probably need to do OPENSDA_FW, PYOCD_TARGET, NRF_FAMILY, and a slew of other things (look at all the various FLASH_SCRIPTs we have)

Good point. I'll add these too.

**Comment by mbolivar** [comment]
@galak rebased and added everything I found relevant in the current Makefile.boards.

**Comment by mbolivar** [comment]
What would you say to another patch on this series to also include generated_dts_board.conf?

**Comment by mbolivar** [comment]
Looks like exporting the emulator info breaks various tests. I'm disabling that for now. I ran sanitycheck locally and saw one failure (in qemu_x86_iamcu/tests/kernel/workq/work_queue) that was not reproducible and wasn't build system related (the test ran, but not all the work items completed, on the first try. On a second try, it passed).

**Comment by mbolivar** [comment]
PLEASE DON'T MERGE YET.

The current approach fails if any variables in Makefile.board are set with ?=. I'm testing another approach now.

**Comment by mbolivar** [comment]
> PLEASE DON'T MERGE YET.
> 
> The current approach fails if any variables in Makefile.board are set with ?=. I'm testing another approach now.

Updated, should be good to go now.

**Review by galak — CHANGES_REQUESTED** [review]
The commit message for 'build: export flashing and debugging', isn't quite clear on how we are accomplishing FLASH_SCRIPT, etc..

**Comment by mbolivar** [comment]
> The commit message for 'build: export flashing and debugging', isn't quite clear on how we are accomplishing FLASH_SCRIPT, etc..

Updated to make it more clear -- how's that?

**Comment by galak** [comment]
I was just saying add something about how include Makefile.board ends up getting all the variables exported that we want/need.

**Comment by mbolivar** [comment]
> I was just saying add something about how include Makefile.board ends up getting all the variables exported that we want/need.

Here is what I had added to the commit log:

```
Rather than maintaining a list of variables in the main Makefile which
are defined in the various per-board Makefile.board files, just ensure
that the Makefile.board, when present, is included by the generated
Makefile.export. This allows users of Makefile.export to have
FLASH_SCRIPT and friends defined when the board tooling provides
them. (Users of Makefile.export will need to cope with these variables
being undefined if not given in Makefile.board or if that file is not
provided on a given target.)
```

That was in addition to this, which was already there, and explains that the variables of interest come from Makefile.board:

```
Zephyr supports the flash and debug targets via per-board information
in Makefile.board files. It is sometimes convenient to know this
information when inspecting the build artifacts or doing exotic
builds, so include it in the file generated by outputexports.
```

Do you want me to make a list of all the variables which may be added in Makefile.board and add that to the commit message? Sorry, I'm confused about what you're looking for.

**Comment by mbolivar** [comment]
This needed a rebase, so I've done that and tried to make it even more clear. If there's something I'm missing, could you please suggest some text to add to the commit log?

**Review by galak — APPROVED** [review]

**Pull request merged**
