### PR TITLE
tests: semaphore: categorize test cases and increase groups of it

### PR DESCRIPTION
**Pull request by enjiamai**
This PR is trying to show a methodology of how to categorize our test cases. It did not change the logic and nature of the test cases, just move and categorize them. At this moment I just want to show you the conception of it.

it contains two commits:
(1) tests: semaphore: categorize the semaphore test cases

    Categorize the semaphore test cases into three group:
    - The first group is the module testing, target to verify the
    semaphore API itself. Ex. testsuite: semaphore_api.

    - The second group is the integration testing, target to verify
    the semaphore works with other modules or usage in the system.
    Ex. testsuite: sys_sem.

    - The third group is fault injection testing, target to passing
    incorrect parameters to semaphore, to verify the errors
    can be detected and be handled.
    Ex. testsuite: semaphore_error_case

(2) docs: change the group of semaphore test cases

    Modified the test group of semaphore test cases, from the original:
    all_tests -> kernel_semaphore_tests
    to
    all_tests -> kernel_semaphore_tests
                    |- semaphore_module_tests
                    |- semaphore_integation_tests
                    |- semaphore_negative_tests
                    |- semaphore_validation_tests (would be add later)

### CODE REVIEW

**Comment by nashif** [comment]
It would be very helpful and useful to define what those categories are first, start a new section in the documentation describing each category and what type of tests each category includes with some examples.
In addition you could describe how the categorization is done using doxygen and what structure you expect. Basically come up with the spec and documentation first, then once we agree on this, we can convert all tests to follow this model.

What you are doing in this PR with doxygen grouping looks fine to me.

**Comment by nashif** [comment]
also, such change needs to go to the main branch.

**Comment by enjiamai** [comment]
Thanks for your feedback, @nashif , we will try to add a describing section and example, also the doxygen part. And we are clear for the process, will upstream to mainline first.

**Comment by nashif** [comment]
@enjiamai  please fix this

**Comment by enjiamai** [comment]
Excuse me, @nashif , I am working on it now.

**Comment by dleach02** [comment]
@enjiamai Do you plan on revisiting this PR?

**Comment by enjiamai** [comment]
> @enjiamai Do you plan on revisiting this PR?

Hi @dleach02 . Yes, I will go back on this within 1~2 weeks. Should I remove the stale or close it and re-open it until I can keep working on it? Thanks for your reminder!

**Comment by henrikbrixandersen** [comment]
> Hi @dleach02 . Yes, I will go back on this within 1~2 weeks. Should I remove the stale or close it and re-open it until I can keep working on it? Thanks for your reminder!

You could put it in "draft" state until it is ready for reviews.

**Comment by enjiamai** [comment]
Ok, got it. @henrikbrixandersen @dleach02 , thank you!

**Pull request closed without merging**
