### PR TITLE
ignore '.' prefixed directories

### PR DESCRIPTION
**Pull request by sprhawk**
I'm using ccls, and it will generate .ccls-cache under applicaton root, it will be parsed by parse_syscalls.py

### CODE REVIEW

**Review by tejlmand — COMMENTED** [review]
I believe placing code under a `.` prefixed directory would generally be unwise, but today it's not directly forbidden.

So before merging this PR, then I believe we should describe such restriction in the Zephyr docs.
For example in 'Application Development'

**Comment by tejlmand** [comment]
the commit has errors:
```
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 d2f81d04497287b89ec36133fb709607fa2a3d0c: author email (Yang Hongbo <yanghongbo@iotpi.io>) needs to match one of the signed-off-by entries.
Error: See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines for more details

 1: UC2 Commit message does not contain a 'Signed-off-by:' line
1: UC3 Commit title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "ignore '.' prefixed directories"
1: UC6 Commit message body is empty, should at least have 1 line(s).
3: B6 Body message is missing
Error: Process completed with exit code 1.
```

Please take a look at commit message guidelines: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

**Comment by sprhawk** [comment]
> .
> 
> So before merging this PR, then I believe we should describe such restriction in the Zephyr docs. For example in 'Application Development'

I think maybe there is a config item to exclude specified directories are better solution?

**Comment by MaureenHelm** [comment]
@tejlmand please revisit

**Review by tejlmand — COMMENTED** [review]
I notice that your PR description states:
> I'm using ccls, and it will generate .ccls-cache under applicaton root

Are you doing in-source builds and not using a dedicated build folder ?

Please note that CMake advices against using in-source builds where build and source folders are identical, ref: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Getting%20Started.html#directory-structure
> In-source builds where the source and binary directories are the same are supported but should be avoided if possible.

**Comment by sprhawk** [comment]
> I notice that your PR description states:
> 
> > I'm using ccls, and it will generate .ccls-cache under applicaton root
> 
> Are you doing in-source builds and not using a dedicated build folder ?
> 
> Please note that CMake advices against using in-source builds where build and source folders are identical, ref: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Getting%20Started.html#directory-structure
> 
> > In-source builds where the source and binary directories are the same are supported but should be avoided if possible.

Let's say my application structure as follow:

application_root:
    - build/
    - CMakeLists.txt
    - boards/
    - src/
    - include/
    - .ccls-cache

whereas `.ccls-cache` is generated by default under my application_root, and `parse_syscalls.py` will analyze the `.ccls-cache`. I think it'd better to ignore folders prefixed with `.`.

I can also use `.dir-locals.el` to put that `.ccls-cache` under `build` to workaround with it.

**Pull request closed without merging**
