### PR TITLE
modbus: add user data for adu callback

### PR DESCRIPTION
**Pull request by parthitce**
add user data for adu callback, which helps in passing
socket and relevant application parameters.

Signed-off-by: Parthiban Nallathambi <parthiban@linumiz.com>

### CODE REVIEW

**Comment by jfischer-no** [comment]
Thanks @parthitce , I will try to find time for review asap, give me a nudge if it takes too long.

**Review by jfischer-no — APPROVED** [review]

**Comment by parthitce** [comment]
@MaureenHelm @galak @carlescufi @nashif ping!

**Comment by parthitce** [comment]
@MaureenHelm @galak @carlescufi @nashif ping!

**Review by henrikbrixandersen — APPROVED** [review]
LGTM

**Pull request merged**
