### PR TITLE
doc: introduction: Improve style and grammar across the chapter

### PR DESCRIPTION
**Pull request by kobelev-dev**
doc: introduction: More consistent doc style across the chapter and better English grammar

These changes are cosmetic and they do not change the meaning of the document.

Signed-off-by: Kirill Kobelev <kobelev17@cdsan.com>

### CODE REVIEW

**Review by kartben — DISMISSED** [review]

**Comment by kartben** [comment]
Oops, sorry that this never was reviewed. Thanks for the PR!
Can you please fix your commit message and make sure the commit is signed off too?

**Comment by kartben** [comment]
Hi @kobelev-dev!
You're getting there :) Only one commit with all your changes would be sufficient, so could you please force push just one single commit to your branch? It needs to be signed off (that, you got right in your commit 203e62c062d1beb75f6b86738b1098f21a4b17c5), and the commit title should indeed be in the form of "doc: ..." but it needs to be less than 72 characters, so maybe "doc: introduction: Improve style and grammar across the chapter"?

Thanks!

**Comment by kobelev-dev** [comment]
Hi @kartben 
I made one more attempt after manipulations. I had to reinsert the changes as I lost them in my first rebase attempt. So please look again. There is just one commit there now.

It is still not clear to me if the subject of a commit and the first line of description should be both present or not. when editing here on GitHub in a browser it asks to enter them both. In VS code there is just one edit box.

Is this a normal procedure to propose any change (including in code) as single commit? AFAIK commits can be squashed while merging the PR. Although I never did that on GitHub.

**Comment by kartben** [comment]
> Hi @kartben I made one more attempt after manipulations. I had to reinsert the changes as I lost them in my first rebase attempt. So please look again. There is just one commit there now.

Thanks for your patience! In the future, if you "lose" commits I would recommend using `git reflog`. This would show you the SHA-1 of *all* recent commits in your repo, even the ones that may have ended up becoming "orphans". This way you can then cherry-pick the changes, or reset to the commit, etc.

> It is still not clear to me if the subject of a commit and the first line of description should be both present or not. When editing here on GitHub in a browser it asks to enter them both. In VS code there is just one edit box.

It's all one "message" but typically the first line is the "title", followed by a blank line, and then the rest would be considered the commit message.

> Is this a normal procedure to propose any change (including in code) as single commit? AFAIK commits can be squashed while merging the PR. Although I never did that on GitHub.

It depends on the project's practices. In Zephyr we don't squash commits and they end up being merged (well, rebased) as-is. In your case, all the changes are part of the same "fixing grammar" thingy so it makes sense to group them, but it may have been two commits if you had e..g first fixed some spelling and grammar error and then proposed reformatting of the file, or moved sections around. Your PR would have still been something along the lines of "Improve Intro section" but then two commits 1/ fix grammar 2/ re-order sections. If that makes sense :)

Anyhow, thanks very much again! If you wrap your commit message so that it doesn't exceed the 75 characters max length, you should now be good to go.

**Comment by kobelev-dev** [comment]
Hi @kartben 
Thanks for your explanations and I am sorry for so long delay. I mastered a little bit my knowledge in git. I understand what I am doing better now.

So, I updated the commit message and pushed forward 220 commits on the main branch in the main repo. But now I see that I am a couple of commits back again. Will that be automatically fixed when the final merge will happen? Once this PR will be approved almost certain more commits will be done.

The commits tab shows 2 commits, but to my understanding the first one is not relevant. It is not part of the branch any more.

image

I hope that I finally did it right. Thanks for spending your time with me.

**Comment by kobelev-dev** [comment]
Looks like I need to abandon this and to start over clean.
I will do that tomorrow.

**Pull request closed without merging**
