### PR TITLE
samples: mesh: nrf52: improved coding style, way to save default & target values on flash

### PR DESCRIPTION
**Pull request by vikrant8052**
1. Removed redundant code.
2. Implement thing based on single struct light_ctl_state pointer
    in entire Application.
3. Rename attribute in enum state_binding : CTL to CTL_LIGHT
4. Separately saved default & last target values of lightness,
    temperature & delta_uv on flash (using settings layer).

Signed-off-by: Vikrant More <vikrant8051@gmail.com>

### CODE REVIEW

**Comment by vikrant8051** [comment]
please wait ...work is in progress

**Comment by vikrant8051** [comment]
@cvinayak @carlescufi Are you able to connect  to any Bluetooth Zephyr App over GATT (in case of any nRF52 board running latest master branch) ?

**Comment by cvinayak** [comment]
Please elaborate on your observations. We have been lately stress testing peripheral and central applications, and fixes been upstreamed, hence I can state that we are able to connect applications over GATT.

-Vinayak

**Comment by vikrant8051** [comment]
@cvinayak Let me test it again. Thank you for your reply.

**Comment by vikrant8051** [comment]
@cvinayak 
Just now I synced with master branch & now everything is working perfectly fine.

**Comment by vikrant8051** [comment]
Please don't merge. Small changes have to be done by adding new commit

**Comment by cvinayak** [comment]
> @cvinayak
> Just now I synced with master branch & now everything is working perfectly fine.

Thanks for testing. Please log a github issue and assign to me if you face issues in future related to controller. When assigned, its more visible to me on github.

**Review by trond-snekvik — APPROVED** [review]

**Comment by vikrant8051** [comment]
Please don't merge. Small changes have to be done by adding new commit

**Comment by jhedberg** [comment]
> Please don't merge. Small changes have to be done by adding new commit

@vikrant8051 I couldn't merge even if I wanted to since the project is in the stabilisation phase for Zephyr 2.2, i.e. only PRs that fix important bugs are allowed.

**Comment by vikrant8051** [comment]
I've added last commit (#10) plus updated commit #3.

**Comment by joerchan** [comment]
@vikrant8051 @jhedberg @trond-snekvik @carlescufi 
This is looking more like an application and less like a sample. If it is an application I don't think it makes sense to keep this under samples here. If this is vikrants mesh application it would make more sense to have this in an independent repository probably, vikrant could then do as he pleases with his application without needed approval from all of us.

**Comment by vikrant8051** [comment]
@joerchan It is due to rebase issue, system automatically send review request to many reviewers.
Sorry for the inconvenience.

**Comment by jhedberg** [comment]
> @joerchan It is due to rebase issue, system automatically send review request to many reviewers.
Sorry for the inconvenience.

I think that's a bit beside the point @joerchan was trying to make. I've also had the same thought many times. Samples are supposed to be fairly small and static, i.e. they shouldn't need much updating. This sample has had numerous 1000+ line PRs since it was created, and the sample itself is rather huge. So I do think it's worth considering if it'd make sense to host it in an independent repository.

**Comment by vikrant8051** [comment]
After merging this PR, App will be in most robust state.
Plz note that non of the other Mesh App is following PTS norm & 
giving example of state transition, state binding.

**Comment by jhedberg** [comment]
@vikrant8051 a PR was recently merged that did the following path rename: `samples/boards/{nrf52 => nrf}`. This means that you will have to rebase this PR before it can be merged.

**Comment by joerchan** [comment]
> After merging this PR, App will be in most robust state.
> Plz note that non of the other Mesh App is following PTS norm &
> giving example of state transition, state binding.

Alright. And then it should remain? Otherwise I think we should consider extracting it out.
Just my suggestion, I guess you MESH guys know the answer to this.

**Comment by vikrant8051** [comment]
> @vikrant8051 a PR was recently merged that did the following path rename: samples/boards/{nrf52 => nrf}. This means that you will have to rebase this PR before it can be merged.

Done !!

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
