### PR TITLE
Bluetooth: Mesh: Persistent storage support

### LINKED ISSUE #7073: Full persistent storage support for Bluetooth
The Bluetooth stack should have integrated support for storing persistently (in flash) any security keys, Client Characteristic Configuration (CCC) as well as Mesh network state. Currently the stack does have the bt_storage API, but it was never used for anything else than the identity address and local IRK.

The idea is to take advantage of the recently introduced settings API, allowing either FCB or a filesystem to be used as the backend.

- [x] Pairing keys storage (`struct bt_keys`). Merged as #7226
- [ ] GATT CCC storage (coming from #7417)
- [ ] Mesh Storage (coming from #7368 and #7428 )

### PR DESCRIPTION
**Pull request by jhedberg**
Support for Mesh persistent storage. Still work in progress: not all information is getting stored and no proper testing has been done. The code is however complete enough for initial reviews & testing.

TODO list:

- [x] Basic Mesh network information
- [x] Replay Protection List & Local Sequence Number
- [x] Network Keys
- [x] Application Keys
- [ ] Model publication
- [ ] Model subscription
- [ ] Model binding
- [ ] Any other Configuration Server model states
- [x] Reduce sequence number stores (e.g. store every 100th and add 100 at boot)
- [x] Reduce RPL stores (e.g. have a timer to store at most once per minute)
- [x] `bt_mesh_reset()` clears all stored values
- [ ] Proper testing (also against the PTS)

Fixes #7073 once GATT CCC storage has been implemented (ping @Vudentz)

### CODE REVIEW

**Comment by jhedberg** [comment]
@bixivs FYI

**Comment by jhedberg** [comment]
@michal-narajowski FYI

**Comment by carlescufi** [comment]
CC @oyvindronningstad @lemrey

**Comment by vikrant8051** [comment]
I merged this PR in my local repository, & flashed $zephyr/samples/bluetooth/mesh eg. on nrf52840_PDK
& try to provision it using #meshctl 


And got this fault, on serial terminal, after executing -> appkey-add 1 command

[bt] [DBG] bt_mesh_store_app_key: (0x200020b8) Saving AppKey bt/mesh/AppKey/1 as value AAAAKqKm3tWgeYzqtXh8o645/AAAAAAAAAAAAAAAAAAAAAA=
***** USAGE FAULT *****
  Executing thread ID (thread): 0x20002120
  Faulting instruction address:  0x20007608
  Illegal load of EXC_RETURN into PC
Fatal fault in thread 0x20002120! Aborting.

**Comment by jhedberg** [comment]
@vikrant8051 I hit the same issue earlier today myself. The reason was an overflow of the Bluetooth receive thread stack (it was set at 2k but with the AppKeyAdd it went to 2700). I've updated the mesh sample prj.conf to use a 3k stack now, i.e. `CONFIG_BT_RX_STACK_SIZE=3072`

**Comment by jhedberg** [comment]
@vikrant8051 Also note that model publication/subscription and app key binding is storage is not yet implemented (as indicated by the TODO list in the beginning of this PR)

**Comment by vikrant8051** [comment]
@jhedberg 
Thanks for you response. I added CONFIG_BT_RX_STACK_SIZE=3072 in prj.conf  & after that everything works as expected. 

But as per my observations, performance of Node degrade drastically. Initially I thought it is because of overhead of Serial debug terminal & so I commented all debug parameters in pro.conf. But that doesn't help. 

When I removed,

**if (IS_ENABLED(CONFIG_SETTINGS)) {
		settings_load();
	}** 

from bt_ready() & 

**#CONFIG_BT_SETTINGS=y
#CONFIG_FLASH=y
#CONFIG_FLASH_PAGE_LAYOUT=y
#CONFIG_FLASH_MAP=y
#CONFIG_FCB=y
#CONFIG_SETTINGS=y
#CONFIG_SETTINGS_FCB=y** 

from prj.conf then performance is perfect & very responsive. 



----------------------------------------------------------------------------------------------------------------------------
Note:
Overview of my implementation, 
There are 4 Models on single Node which is in my case #nRF52840_PDK,
--> Generic OnOFF server
--> Generic OnOFF client
--> Generic Level Server
--> Generic Level Client

Button 1 -> publish Generic ON to group 0xC000
Button 2 -> publish Generic OFF to group 0xC000
Button 3 -> Publish Generic Level value = 2000
Button 4 -> Publish Generic Level value = 20000

LED1 -> Generic OnOFF server
LED 3, LED4 -> for Generic Level Server
       ----> Led3 (On) , Led4 (Off) -> when receives value below 10000
       ----> Led3 (Off) , Led4 (On) -> when receives value above 10000

**Comment by vikrant8051** [comment]
Let me try this with multiple Nodes.

**Comment by vikrant8051** [comment]
I tried it with two nodes. Yes performance degrade surely. Without latest updates, if I press Button1/2 on any of the NODE, instantaneously LED1 on all boards turns ON/OFF resp. But now it is taking some time to react & sometimes not even receives any message from Publisher.

**Comment by jhedberg** [comment]
@vikrant8051 what value do you have for `CONFIG_BT_MESH_RPL_STORE_TIMEOUT`? In my PR I set it to `CONFIG_BT_MESH_RPL_STORE_TIMEOUT=5` for `samples/bluetooth/mesh`. If it's set to the default (0) then the RPL will get written to flash for every received message. That's the only think I could think of so far that could potentially have a substantial impact on performance.

**Comment by jhedberg** [comment]
@vikrant8051 I just pushed an update to this PR to make 5 seconds the default RPL store timeout. I'm still curious to hear if this was the cause of your performance degradation however.

**Comment by vikrant8051** [comment]
@jhedberg I've added CONFIG_BT_MESH_RPL_STORE_TIMEOUT=5 in my prj.conf.
Now it perform like as expected....very responsive :) :) 

Note:
----------------------------------------------------------------------------------------------------------------------------------
I execute following steps/commands to merge this PR,

    cd $(zephyr_base)

    git fetch origin pull/7368/head:BluetoothMesh

    git checkout BluetoothMesh

But there was no such parameter is available in samples/bluetooth/mesh/prj.conf. 
I've added thse two parameters manually,

CONFIG_BT_RX_STACK_SIZE=3072
CONFIG_BT_MESH_RPL_STORE_TIMEOUT=5

**Comment by jhedberg** [comment]
For the reviewers: I've removed the "WIP" and "DNM" tags, since as far as the functionality this PR implements is concerned, it seems to be working quite well. I.e. I'm not opposed to merging this one, and then working on the remaining TODO items in a separate PR. I think this is worth considering since this PR is quite large already.

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by jhedberg** [comment]
I've merged this now, and moved the remaining items to #7428

**Comment by Laczen** [comment]
@jhedberg I was wondering, is it really required to save the rpl? What would happen if it was not saved, would it just allow one replay after reboot?

**Comment by jhedberg** [comment]
@Laczen I suppose it depends on the use case of the device. E.g. if it's a door lock, I'd be quite careful in studying the various replay attack possibilities. Even one replay could mean that an attacker can open the lock when the owner is not around.

**Comment by Laczen** [comment]
I didn't realize the mesh security is so dependent on the rpl. For a key I wouldn't rely on one message to open a lock (even with the mesh protection), for any other device requiring two messages after reboot should restore the rpl protection.

**Pull request merged**
