### PR TITLE
boards/x86/acrn: build it in x86_64 mode

### PR DESCRIPTION
**Pull request by ZideChen0**
- added CONFIG_X86_64 since ACRN hypervisor supports x86_64 arch only.
- removed CONFIG_SET_GDT because Zephyr doesn't support it in x86_64,
  and ACRN doesn't need the guest to setup GDT during boot time.
- added CONFIG_X2APIC since it's preferred by ACRN.
- include sysapic.h in x86_64 as well so that it gets built if
  CONFIG_LOAPIC is enabled in x86_64 build.

Signed-off-by: Zide Chen <zide.chen@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
```
[28/77] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj
FAILED: zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj 
ccache /opt/sdk/zephyr-sdk-0.11.1/x86_64-zephyr-elf/bin/x86_64-zephyr-elf-gcc -DBUILD_VERSION=zephyr-v2.1.0-2100-g04084a1f02a1 -DKERNEL -D_FORTIFY_SOURCE=2 -D__ZEPHYR__=1 -I../../../../../../../include -Izephyr/include/generated -I../../../../../../../soc/x86/ia32 -isystem ../../../../../../../lib/libc/minimal/include -isystem /opt/sdk/zephyr-sdk-0.11.1/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/9.2.0/include -isystem /opt/sdk/zephyr-sdk-0.11.1/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/9.2.0/include-fixed -m64    -Os -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/acrn/tests/subsys/debug/tracing/tracing.backends.openocd/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -m64 -Wa,--divide -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-address-of-packed-member -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -Werror -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/subsys/debug/tracing=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr=ZEPHYR_BASE -ffunction-sections -fdata-sections -march=x86-64 -std=c99 -nostdinc -MD -MT zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj -MF zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj.d -o zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj   -c /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/debug/openocd.c
In file included from ../../../../../../../include/kernel_includes.h:16,
                 from ../../../../../../../include/kernel.h:17,
                 from /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/debug/openocd.c:7:
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/debug/openocd.c:58:20: error: 'struct _callee_saved' has no member named 'esp'; did you mean 'rsp'?
   58 |       callee_saved.esp),
      |            
```

Looks like this is trying to build some openocd code that assumes 32-bit (note esp and not rsp)

**Comment by ZideChen0** [comment]
> ```
> [28/77] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj
> FAILED: zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj 
> ccache /opt/sdk/zephyr-sdk-0.11.1/x86_64-zephyr-elf/bin/x86_64-zephyr-elf-gcc -DBUILD_VERSION=zephyr-v2.1.0-2100-g04084a1f02a1 -DKERNEL -D_FORTIFY_SOURCE=2 -D__ZEPHYR__=1 -I../../../../../../../include -Izephyr/include/generated -I../../../../../../../soc/x86/ia32 -isystem ../../../../../../../lib/libc/minimal/include -isystem /opt/sdk/zephyr-sdk-0.11.1/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/9.2.0/include -isystem /opt/sdk/zephyr-sdk-0.11.1/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/9.2.0/include-fixed -m64    -Os -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/acrn/tests/subsys/debug/tracing/tracing.backends.openocd/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -m64 -Wa,--divide -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-address-of-packed-member -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -Werror -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/subsys/debug/tracing=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr=ZEPHYR_BASE -ffunction-sections -fdata-sections -march=x86-64 -std=c99 -nostdinc -MD -MT zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj -MF zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj.d -o zephyr/CMakeFiles/zephyr.dir/subsys/debug/openocd.c.obj   -c /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/debug/openocd.c
> In file included from ../../../../../../../include/kernel_includes.h:16,
>                  from ../../../../../../../include/kernel.h:17,
>                  from /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/debug/openocd.c:7:
> /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/debug/openocd.c:58:20: error: 'struct _callee_saved' has no member named 'esp'; did you mean 'rsp'?
>    58 |       callee_saved.esp),
>       |            
> ```
> 
> Looks like this is trying to build some openocd code that assumes 32-bit (note esp and not rsp)

This is not an issue introduced by this patch, is it correct? In master, I saw some problem with "west build -b qemu_x86_64 samples/hello_world/" if I enabled CONFIG_OPENOCD_SUPPORT.

Probably need to fix it in openocd in a separate patch?

**Comment by andrewboie** [comment]
> This is not an issue introduced by this patch, is it correct? In master, I saw some problem with "west build -b qemu_x86_64 samples/hello_world/" if I enabled CONFIG_OPENOCD_SUPPORT.
> 
> Probably need to fix it in openocd in a separate patch?

For some reason this PR is causing this to induce a CI failure when it didn't before. We can't check anything in which breaks CI, so this PR will need at least a workaround.

**Comment by andrewboie** [comment]
This seems to fix it:

```
diff --git a/subsys/debug/openocd.c b/subsys/debug/openocd.c
index 9ed76ddf09..bf1acf9c04 100644
--- a/subsys/debug/openocd.c
+++ b/subsys/debug/openocd.c
@@ -54,8 +54,13 @@ size_t _kernel_openocd_offsets[] = {
        [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
                                                callee_saved.sp),
 #elif defined(CONFIG_X86)
+#if defined(CONFIG_X86_64)
+       [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
+                                               callee_saved.rsp),
+#else
        [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
                                                callee_saved.esp),
+#endif
 #elif defined(CONFIG_NIOS2)
        [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
                                                callee_saved.sp),
```

There's another build issue with the loapic timer driver and some hard-coded assembly for reading the TSC if CONFIG_EXECUTION_BENCHMARKING is enabled, why this is not an inline function baffles me. I'm looking into it.

There's also an issue with how tests/arch/x86/static_idt is filtered.

Im working on patches for all of these.

**Comment by ZideChen0** [comment]
> This seems to fix it:
> 
> ```
> diff --git a/subsys/debug/openocd.c b/subsys/debug/openocd.c
> index 9ed76ddf09..bf1acf9c04 100644
> --- a/subsys/debug/openocd.c
> +++ b/subsys/debug/openocd.c
> @@ -54,8 +54,13 @@ size_t _kernel_openocd_offsets[] = {
>         [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
>                                                 callee_saved.sp),
>  #elif defined(CONFIG_X86)
> +#if defined(CONFIG_X86_64)
> +       [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
> +                                               callee_saved.rsp),
> +#else
>         [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
>                                                 callee_saved.esp),
> +#endif
>  #elif defined(CONFIG_NIOS2)
>         [OPENOCD_OFFSET_T_STACK_PTR] = offsetof(struct k_thread,
>                                                 callee_saved.sp),
> ```
> 
> There's another build issue with the loapic timer driver and some hard-coded assembly for reading the TSC if CONFIG_EXECUTION_BENCHMARKING is enabled, why this is not an inline function baffles me. I'm looking into it.
> 
> There's also an issue with how tests/arch/x86/static_idt is filtered.
> 
> Im working on patches for all of these.

Then this PR can wait until your patch is merged. I can close the PR for now.

**Comment by ZideChen0** [comment]
> The fixes I made in #22560 will need to be applied before this will pass.
> 
> Also, you made several changes which are not closely related, I would appreciate if you split your patch into individual logical changes.

I can wait until #22560 is done as well. And will split it two patches: 1) acrn specific  2) header changes in arch.h. 

Or even better, if you can address this generic issue into your #22534, then I can only touch board acrn.

**Comment by andrewboie** [comment]
> 
> 
> > The fixes I made in #22560 will need to be applied before this will pass.
> > Also, you made several changes which are not closely related, I would appreciate if you split your patch into individual logical changes.
> 
> I can wait until #22560 is done as well. And will split it two patches: 1) acrn specific 2) header changes in arch.h.
> 
> Or even better, if you can address this generic issue into your #22534, then I can only touch board acrn.

Mine should be in fairly soon, rebase and force push after that and we'll see where we are at with CI.

**Comment by andrewboie** [comment]
@ZideChen0 just push a new revision to this PR when it's ready, no need to close this and open another. We prefer code review history to not span multiple PRs.

**Comment by andrewboie** [comment]
@ZideChen0 my PR has been merged, can you rebase?

**Comment by ZideChen0** [comment]
> @ZideChen0 my PR has been merged, can you rebase?

Yes, noticed that this morning. Rebased, and doing sanity tests.

**Comment by mbolivar** [comment]
Looks like a potentially incorrect rebase? I'm removing myself from review

**Comment by andrewboie** [comment]
@ZideChen0 I don't think your rebase was executed properly.

Usually you just need to do, while on your forked branch:

```
git rebase origin/master
git push -f
```

**Comment by ZideChen0** [comment]
> @ZideChen0 I don't think your rebase was executed properly.
> 
> Usually you just need to do, while on your forked branch:
> 
> ```
> git rebase origin/master
> git push -f
> ```

Done. Thanks for your help.

**Review by tyrantlizard77 — APPROVED** [review]
rebase looks correct and patches look good.

please fix the gitlint issue noted with one of your commit messages.

**Review by nashif — APPROVED** [review]

**Pull request merged**
