### PR TITLE
boards: arm: add dma test support for some nucleo boards

### PR DESCRIPTION
**Pull request by cybertale**
Add DMA test support for 'loop_transfer', 'chan_blen_transfer' on
NUCLEO_F091RC/F103RB/F207ZG/F302RF8/F401RE/F746ZG/L073RZ/L476RG.

Signed-off-by: Song Qiang <songqiang1304521@gmail.com>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
I wonder if there would be a way to assign `.overlay` and `prj.conf` files through `testcae.yaml` so we don't have so much files and redundancy. (And we'd still need to add new boards manually)

Something like:
```
  peripheral.dma.interactive:
    depends_on: dma
    filter = DMA_STM32_V1
    extra_args: CONF_FILE=prj_dma_stm32_v1.conf
    extra_args: OVERLAY_CONFIG=dma_stm32_v1.overlay
    min_ram: 16
    tags: drivers dma
    harness: keyboard
```

Some more info on sanitycheck yaml capabilities in `doc/guides/test/sanitycheck.rst`

**Comment by cybertale** [comment]
> I wonder if there would be a way to assign `.overlay` and `prj.conf` files through `testcae.yaml` so we don't have so much files and redundancy. (And we'd still need to add new boards manually)
> 
> Something like:
> 
> ```
>   peripheral.dma.interactive:
>     depends_on: dma
>     filter = DMA_STM32_V1
>     extra_args: CONF_FILE=prj_dma_stm32_v1.conf
>     extra_args: OVERLAY_CONFIG=dma_stm32_v1.overlay
>     min_ram: 16
>     tags: drivers dma
>     harness: keyboard
> ```
> 
> Some more info on sanitycheck yaml capabilities in `doc/guides/test/sanitycheck.rst`

I see `CONF_FILE` is supported but OVERLAY_CONFIG is not supported in the system. Another thing I'm thinking about is that if we supply `CONF_FILE` and `OVERLAY_CONFIG` in testcase.yaml, is it still possible to build the project in project folder through `cmake -Bbuild -DBOARD=...`, `ninja` ?

Better solution for `CONF_FILE` in this project is someday we can support calculating how many `HEAP_MEM_POOL_SIZE do` we need in the system, rather than setting a sum value in app folder.

**Comment by erwango** [comment]
> is it still possible to build the project in project folder through cmake -Bbuild -DBOARD=..., ninja ?

Fair point. One alternative, which would be compatible with CI and manual testing, is to tweak CMakeLists.txt test file. It should allow to add appropriate overlay and do the `MEM_POOL` update.
It will likely still be board specific, but spares a good amount of files.

**Comment by cybertale** [comment]
> > is it still possible to build the project in project folder through cmake -Bbuild -DBOARD=..., ninja ?
> 
> Fair point. One alternative, which would be compatible with CI and manual testing, is to tweak CMakeLists.txt test file. It should allow to add appropriate overlay and do the `MEM_POOL` update.
> It will likely still be board specific, but spares a good amount of files.

I actually did tweak the CMakeList.txt file in the very first version of that PR.
The problem is, in the CMakeList.txt, before the 
```
include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
```
, little environment variables are available, like BOARD. CONFIG_DMA_STM32_V1 or CONFIG_SOC_STM32XX are all not avalible. And after this line, we have these defines but our modification to CONF_FILE and many other things wouldn't work, because they have already been processed.
So I had to do this:
```
if (BOARD is nuelo_f091rc or nucleo_f103rb ... )
        [modification for CONF_FILE]
```
This is not good, we have to include the check for every board.
It seens like we have to make changes to the `boilerplate.cmake` file to achieve what we want.

**Comment by erwango** [comment]
> I actually did tweak the CMakeList.txt file in the very first version of that PR.

Indeed, so now at least we're sure we've studied all alternatives ;-)

> So I had to do this:
```
if (BOARD is nuelo_f091rc or nucleo_f103rb ... )
        [modification for CONF_FILE]
```
> This is not good, we have to include the check for every board.

Not sure is not worse than adding 2 files per board finally.
After seeing all possible ways to do this, I'd say this is the less bad actually.

> It seens like we have to make changes to the boilerplate.cmake file to achieve what we want

Agreed there is currently a missing link to achieve scalable tests definitions, I'm open to study this in another PR. But maybe not block current PR on this.

**Review by erwango — APPROVED** [review]

**Comment by nashif** [comment]
@erwango  why do we need all those overlays adding dma here, can't this be part of the board DTS instead, just like everything else?

**Comment by erwango** [comment]
> @erwango why do we need all those overlays adding dma here, can't this be part of the board DTS instead, just like everything else?

@nashif I can't recall why we excluded this option in first place but this indeed much simpler and I can't get you wrong today.
@cybertale ?

**Review by erwango — CHANGES_REQUESTED** [review]
Need to be reviewed following recent changes on DMA

**Comment by erwango** [comment]
@cybertale  I'm closing this PR. Please feel free to re-open it if need be.

**Pull request closed without merging**
