### PR TITLE
doc: Add 'project timeline' to glossary

### PR DESCRIPTION
**Pull request by romkell**
Transfer 'safety certification project timeline' from
safety committee google drive glossary to zephyr doc glossary.

### CODE REVIEW

**Comment by kartben** [comment]
@romkell could you explain what you're trying to accomplish with this PR? It doesn't seem to add a lot of value but I am sure I am missing something regarding maybe some of the documentation requirements for safety|
Thanks!

**Comment by romkell** [comment]
> > It is planned that I do that as a PR per term.
> 
> really? Why?, can you please just dump everything in one PR please? We need to see if that fits here or if we need to find a better, more suitable place for this. For example, whatever you are submitting in this PR does not qualify as a glossary item IMO.

Not every term in the google drive safety glossary in its current state adds value IMO. But the people who added those must have had an intention to put those there.
For the why: in order to be able to handle each separately. Merge what is valuable (without being blocked), modify, extend or drop what is not.

For this PR: the original term was "project timeline" where I will revert to just to preserve the original. The "safety certification" I just made up to make it at least a little more understandable in the context of the whole zephyr project.

Collecting all terms from the safety glossary in one PR is less work for me.

I feel creating an RFC issue, transfer the existing safety glossary to there is the most suitable approach.
- it is public to the Safety WG (which requested more insight, which is absolutely needed)
- The terms can be discussed, refined or dropped
- the further process can be defined (1 PR per term or all in one) 

@kestewart @nashif @kartben : Any other suggestions how to continue with the topic?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
We have project timelines for non-safety related activities as well. This seems oddly specific.

**Comment by nashif** [comment]
outdated and being a draft, the bot is not able to make it stale, so closing. Reopen if you think otherwise.
Outdated PR.  Given it is in draft mode, the bot is not able to make it stale, so closing. Reopen if you think otherwise.
This is a manual cleanup activity due to the large number of open PRs which is becoming unmanageable. Many PRs are left open with no intention to move them forward.

**Pull request closed without merging**
