### PR TITLE
drivers: dma: intel-adsp-hda: modify stop dma logic

### PR DESCRIPTION
**Pull request by kv2019i**
Commit b2eaa6448076 ("drivers: dma: intel-adsp-hda: add delay to stop host dma") added a wait on GBUSY state to host DMA stop.

This is problematic as in some case (like SOF chain-DMA usage), the host DMA side RUN bit is not cleared when intel_adsp_hda_dma_stop() is called. It is not possible to wait on GBUSY bit as there are valid cases where it can remain set.

Address the original problem described in SOF bug 8686 and add a polling check for intel_adsp_hda_is_enabled(). As per the bug description, in some cases the GEN/FIFORDY bits are not cleared immediately and if a new call to intel_adsp_hda_dma_stop() is made, the PM refcounting will go haywire.

Link: https://github.com/thesofproject/sof/issues/8686

### CODE REVIEW

**Comment by kv2019i** [comment]
Marking with DNM until @RanderWang has reviewed this. I'm not 100% sure I understood the problematic sequence correctly and I've not been able to reproduce the original problem. Based on my understanding we should not need to poll for GEN/FIFORDY status like this. But alas, we have seen bugs with unblanaced pm-refcounting, so the logic in this function must be wrong somehow.

**Review by teburd — APPROVED** [review]
The busy wait here isn't really needed and could be NULL unless you want to give a little breathing room on a bus between polling the hw registers. I get this is a shared device though so perhaps a good reason to keep it!

**Review by RanderWang — APPROVED** [review]
LGTM.

**Comment by RanderWang** [comment]
@kv2019i  I updated the log in https://github.com/thesofproject/linux/pull/4798#issuecomment-1922659595

**Comment by marc-hb** [comment]
> Commit b2eaa6448076 ("drivers: dma: intel-adsp-hda: add delay to stop host dma") 

That was e021ccfc7452

**Comment by teburd** [comment]
Removing DNM as Rander has approved

**Review by nashif — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
