### PR TITLE
log_link: fix the log_link test failure on adsp boards

### LINKED ISSUE #51418: Intel CAVS: Assertion failed in tests/subsys/logging/log_links
**Describe the bug**
On intel_adsp_cavs15/18/25 platform, tests/subsys/logging/log_links failed due to assertion failure.
Bisect result: c0aca6af7aa2dfae63c937e567b0c4ba5a13f571

**To Reproduce**
1. west build -p always -b intel_adsp_cavs15 tests/subsys/logging/log_links
2. west flash --remote-host=(ip address to DUT) --config-dir=/home/ztest/cavs/config/ --pty
3. see error

**Logs and console output**
```
START - test_log_domain_count
 PASS - test_log_domain_count in 0.001 seconds
===================================================================
START - test_log_domain_name_get
 PASS - test_log_domain_name_get in 0.001 seconds
===================================================================
START - test_log_runtime_level_set

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/logging/log_links/src/main.c:196: test_single_runtime_level: (*link_level not equal to 2)
1:0 Unexpected compiled level (got:4 exp:2)
 FAIL - test_log_runtime_level_set in 0.001 seconds
===================================================================
START - test_log_source_count
 PASS - test_log_source_count in 0.001 seconds
===================================================================
START - test_log_source_name_get
 PASS - test_log_source_name_get in 0.001 seconds
===================================================================
TESTSUITE log_links failed.
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 15.0
 - Commit SHA: c0aca6af7aa2dfae63c937e567b0c4ba5a13f571

### PR DESCRIPTION
**Pull request by smrtos**
The log_link tests are meant to work with 2 mock log backends.
But Intel ADSP platform has an extra default backend named
"log_backend_adsp" when CONFIG_LOG_BACKEND_ADSP=y, which will
mess things up.

Fix it by disabling the default backend.

Signed-off-by: Ming Shao <ming.shao@intel.com>

Fix: https://github.com/zephyrproject-rtos/zephyr/issues/51418

### CODE REVIEW

**Comment by nordic-krch** [comment]
In `prj.conf` I tried to disable all potential default backends. Would that work if ADSP is added there?

**Comment by smrtos** [comment]
> In `prj.conf` I tried to disable all potential default backends. Would that work if ADSP is added there?

I tried adding `CONFIG_LOG_BACKEND_ADSP=n` to `prj.conf`. It can pass.

But I can't explain why the log can still be output even no backend is there.

**Comment by smrtos** [comment]
OK, I think it's safe to simply put the `CONFIG_LOG_BACKEND_ADSP=n` in the `prj.conf`.
Because all the test logs are from the ztest fx. And ztest fx use `printk()`.

https://github.com/zephyrproject-rtos/zephyr/blob/78809549ee4cf7de3150ff4c3887011825584547/subsys/testsuite/include/zephyr/tc_util.h#L25


And on ADSP platforms, the `printk()` is based on the `winstream_console`.
https://github.com/zephyrproject-rtos/zephyr/blob/78809549ee4cf7de3150ff4c3887011825584547/drivers/console/winstream_console.c#L41-L47

Which is stuffed into the printk implementation by overriding the weak symbol below:

https://github.com/zephyrproject-rtos/zephyr/blob/78809549ee4cf7de3150ff4c3887011825584547/lib/os/printk.c#L45-L54

I will re-push it.

**Comment by smrtos** [comment]
@nordic-krch  re-pushed.

**Review by nordic-krch — APPROVED** [review]

**Review by chen-png — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
