### PR TITLE
Samples: SMF: Add sample for SMF framework

### PR DESCRIPTION
**Pull request by glenn-andrews**
This PR adds a sample demonstrating the use of the State Machine Framework (SMF)

Instructions are in the README.rst for the sample.

Miro Samek was contacted and gave approval to use the state diagram in Figure 2.11 of Practical UML Statecharts in C/C++, 2nd Edition as the basis of this demo.

### CODE REVIEW

**Comment by glenn-andrews** [comment]
Need to fix sample.yaml with the correct test harness, since it's a console application that doesn't exit. Any gurus able to provide insight?

**Comment by glenn-andrews** [comment]
I've got tests 'working' by going build-only and skipping the ones that failed. Is this okay?

**Comment by PerMac** [comment]
Since you've wrote "It should be possible to build and **run** this sample on almost any board or emulator" I believe you misused "build_only: true". Skipping the failing tests can be correct but it is good to know why. Is it an error to be fixed, a required feature is missing or something else? With >500 platforms it is not expected that you have to figure this out. E.g. you can copy the error into the comments for reviewers to have a look or help to determine if it should be escalated. 
You can verify the sample by using `harness: console` and describing more details in `harness_config`: regexes to look for, and if they should be ordered". Here is an example https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/philosophers/sample.yaml#L12

**Review by kartben — COMMENTED** [review]
This is very nice, thank you so much for taking the time to put this together.
I am a bit concerned about the fact it uses a sample from a book which, while apparently available for free, is still "Copyright / All rights reserved" content AFAICT.

**Comment by glenn-andrews** [comment]
> I am a bit concerned about the fact it uses a sample from a book which, while apparently available for free, is still "Copyright / All rights reserved" content AFAICT.

Understood. Which is why I requested approval from Mirao Samek, the author and received it. Should I put in a comment "Used with permission of the Author"

**Comment by kartben** [comment]
> > I am a bit concerned about the fact it uses a sample from a book which, while apparently available for free, is still "Copyright / All rights reserved" content AFAICT.
> 
> Understood. Which is why I requested approval from Mirao Samek, the author and received it. Should I put in a comment "Used with permission of the Author"

Oh I'm sorry, I completely missed this. Very thoughtful of you to reach out to the author and yes, having it in the actual README and header comment in main.c would be good.

**Comment by glenn-andrews** [comment]
> having it in the actual README and header comment in main.c would be good.

Done

**Comment by glenn-andrews** [comment]
Build errors on the boards I was ignoring:

https://github.com/zephyrproject-rtos/zephyr/actions/runs/8421925576/job/23060492853

**Comment by glenn-andrews** [comment]
> looks like you could probably make your prj.conf more "minimal", and not enable things like `CONFIG_DEBUG`, `CONFIG_DEBUG_THREAD_INFO` or `CONFIG_THREAD_NAME` that AFAICT are not strictly needed for the code sample to work.

Done, and it looks like it worked.

**Review by PerMac — CHANGES_REQUESTED** [review]
The sample doesn't work on hardware. It doesn't print anything, just starts shell. It seems it is missing `CONFIG_LOG_BACKEND_UART=y` in prj.conf. With it works as described

**Comment by glenn-andrews** [comment]
> The sample doesn't work on hardware. It doesn't print anything, just starts shell. It seems it is missing `CONFIG_LOG_BACKEND_UART=y` in prj.conf. With it works as described

Strange, works on the `disco_l475_iot1` which implies the disco has the UART backend enabled by default and your board doesn't, or perhaps one of the configs I deleted implied it. Either way, fixed.

**Review by PerMac — DISMISSED** [review]
Verified on nrf52840dk/nrf52840. Looks good from a testing perspective. I haven't review the app code itself.

**Comment by glenn-andrews** [comment]
Here's Fig 2.11 if people want to play with it. I could have included it in the documentation, but I think I should direct traffic to the eBook as a thank you to Dr. Samek.
Screenshot 2024-02-24 094654

**Comment by glenn-andrews** [comment]
Sorry. Working to fix this snafu

**Comment by glenn-andrews** [comment]
I have no idea what I did. Starting again with https://github.com/zephyrproject-rtos/zephyr/pull/70921

**Pull request closed without merging**
