### PR TITLE
Bluetooth: controller: Remove redundant include of cmsis.h

### PR DESCRIPTION
**Pull request by cvinayak**
Remove the redundant include of cmsis.h as soc.h already
includes it as necessary.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by aescolar — APPROVED** [review]
Thanks

**Comment by aescolar-ot** [comment]
Do you want to clean up also in https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/clock_control/nrf5_power_clock.c#L14
&
https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/timer/nrf_rtc_timer.c#L11

**Comment by cvinayak** [comment]
@aescolar-ot Thank you. Done.

**Review by carlescufi — APPROVED** [review]
LGTM

**Pull request merged**
