### PR TITLE
buildkite: update pipeline to use new dockerfiles release

### PR DESCRIPTION
**Pull request by ioannisg**
Update buildkite to use dockerfiles release 0.11.10.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

This bumps cmake version to 3.15.7

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Looks good, update .buildkite/daily.yml as well.

**Comment by ioannisg** [comment]
> Looks good, update .buildkite/daily.yml as well.

yeap, done.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Can we add to this pr removing the `pip3 install` in `.buildkite/run.sh`

**Comment by ioannisg** [comment]
> Can we add to this pr removing the `pip3 install` in `.buildkite/run.sh`

That's actually a good idea - see how things run without the temp hacks in .buildkite 👍

**Review by nashif — APPROVED** [review]

**Pull request merged**
