### PR TITLE
drivers: eeprom: atmel,at2x: improve devicetree bindings + Kconfig descriptions

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Improve the devicetree binding and Kconfig descriptions for the atmel,at24 and atmel,at25 EEPROM compatibles. These compatibles work for a number of different EEPROM families manufactured by vendors other than Atmel.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
> So I'd propose to do it the other way round: Provide a compatible per supported family reference (`st,m95xxx` for instance for st case). This binding doesn't have to involve any code addition/modification, but point to the usage of atmel compatible, in the very same way you put it in [`dts/bindings/mtd/atmel,at25.yaml`](https://github.com/zephyrproject-rtos/zephyr/pull/73512/files#diff-a8c39e0b574bc1d6181381191cb1dc26d2624a0798831b578e56336fe6ae2b31)
> 
> ```
>       eeprom@1 {
>         compatible = "st,m95256", "st,m95xxx", "atmel,at25";
> ```

A compatible with no driver binding just for the sake of it appearing in a list is a slippery slope, in my opinion.

Anyways, this is just the first part (or rather second, first part is still outstanding) of the solution I proposed in [the https://docs.zephyrproject.org/latest/hardware/peripherals/eeprom.html](https://github.com/zephyrproject-rtos/zephyr/pull/73136#issuecomment-2124645129). I still plan to enhance the documentation for this under https://docs.zephyrproject.org/latest/hardware/peripherals/eeprom.html, but that will be a separate PR.

**Comment by erwango** [comment]
> A compatible with no driver binding just for the sake of it appearing in a list is a slippery slope, in my opinion.

Agree that abuses should be avoided but I just think that documented bindings should be a trusted source of information about what is supported or not. Having documentation bindings doesn't seem something we should avoid to me.

 > @erwango Do you disagree with any of the proposed changes in this PR, if you consider them a step towards reducing the confusion?

Not disagreeing. Just skeptical on the efficiency. Definitely documentation, as mentioned, will be a good complement.
So I'm not blocking and maybe if we see more intents to provide st,m25xx implementation after this, we'll have to revisit.

**Comment by henrikbrixandersen** [comment]
My concern with adding just one binding like this for documentation purposes is, that there are _lots_ of similar devices, where the same logic could be applied, potentially leading to a lot of these "documentation purposes" bindings.

If we just stick to serial (I2C and SPI) EEPROMs compatible with the atmel,at2x bindings, there are quite a few of these. Please take a look at all the different vendors and families listed in the corresponding Linux bindings:
- https://elixir.bootlin.com/linux/latest/source/Documentation/devicetree/bindings/eeprom/at24.yaml
- https://elixir.bootlin.com/linux/latest/source/Documentation/devicetree/bindings/eeprom/at25.yaml

How about our `jedec,spi-nor` binding? There are many vendors and families supported by that one as well, do we add bindings for all of these for documentation purposes as well?

From the top of my head, the following Zephyr bindings fall in the same class:
- `dts/bindings/led_strip/ws2812.yaml`: There are many addressable LEDs using the same protocol.
- `dts/bindings/regulator/regulator-gpio.yaml`: Lots of GPIO controlled regulators out there.
- `dts/bindings/regulator/regulator-fixed.yaml`: Perhaps even more fixed regulators?
- `dts/bindings/phy/can-transceiver-gpio.yaml`: This bindings supports pretty much all the vendor/families of CAN transceivers, I have ever used.
- ...

For each of the above bindings, one could argue that it is difficult to find out if a particular make/model of a given device is supported by that binding, but adding "documentation purposes" bindings for each vendor,family will quickly become a maintenance burden - and perhaps even lead to more confusion for users wanting to use a different make/model, which _does not_ have a "documentation purpose" binding, but works just as well with the common driver.

**Comment by benediktibk** [comment]
I agree with @erwango, having this documentation is definitely helpful. But I would still go down the road of adding a compatible to avoid unnecessary confusion for users. I understand the issue with maintaining to many compatibles, but I think one compatible per chip family/vendor is a good compromise. Also in the other similar cases, which @henrikbrixandersen  has mentionend.

**Review by gmarull — APPROVED** [review]

**Comment by erwango** [comment]
> From the top of my head, the following Zephyr bindings fall in the same class:

I'm not fully in line, these bindings are truly generic, because the don't include any vendor name, we can understand the concept could apply to any compatible part. This is not exactly the same case here.
Approving anyway.

**Review by erwango — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
at24 device user is happy.

**Pull request merged**
