### PR TITLE
boards: posix: native_posix_64: Add sim: native

### LINKED ISSUE #54605: native_posix_64 platform broken in Twister
**Describe the bug**
When using Twister to run tests for the `native_posix_64` platform, the test binary is built but not ran. This can be seen by looking for test output of the form
```
DEBUG   - my.coo.test: No status
```
More specifically, when Twister is working properly, you see the following phases occur in the output
1. Calling cmake: ...
2. build test: ...
3. Determine test cases for ...
4. run test: ...
5. Spawing process: ...

However, when using the `natve_posix_64` platform, steps 4 and 5 don't happen.
This problem can be traced to `scripts/pylib/twister/twisterlib/testinstance.py` in the `setup_handler` method of the `TestInstance` class, whose code is reproduced here:
```
    def setup_handler(self, env):
        if self.handler:
            return

        options = env.options
        handler = Handler(self, "")
        if options.device_testing:
            handler = DeviceHandler(self, "device")
            handler.call_make_run = False
            handler.ready = True
        elif self.platform.simulation != "na":
            if self.platform.simulation == "qemu":
                handler = QEMUHandler(self, "qemu")
                handler.args.append(f"QEMU_PIPE={handler.get_fifo()}")
                handler.ready = True
            else:
                handler = SimulationHandler(self, self.platform.simulation)

            if self.platform.simulation_exec and shutil.which(self.platform.simulation_exec):
                handler.ready = True
        elif self.testsuite.type == "unit":
            handler = BinaryHandler(self, "unit")
            handler.binary = os.path.join(self.build_dir, "testbinary")
            if options.enable_coverage:
                handler.args.append("COVERAGE=1")
            handler.call_make_run = False
            handler.ready = True

        if handler:
            handler.options = options
            handler.generator_cmd = env.generator_cmd
            handler.generator = env.generator
            handler.suite_name_check = not options.disable_suite_name_check
        self.handler = handler
```
This method attempts to determine the proper subclass of `Handler` to use for a given test. It chooses among `DeviceHandler`, `QEMUHandler`, `SimulationHandler`, and `BinaryHandler`. In the case of the correctly working platform `native_posix`, the code traces a path through `self.platform.simulation != "na"` (which is true) and then `self.platform.simulation == "qemu"` (which is false), to end up getting a `SimulationHandler` and having the handler's `ready` field being set to `True`. The problem with `native_posix_64` is that it does not have its `simulation` field set in its yaml file, and so the code ends up with no handler and thus no `ready` field being set to True. Ultimately, this leads to the `process` function in `scripts/pylib/twister/twisterlib/runner.py` not transitioning from the `gather_metrics` operation, to the `run` operation.

**To Reproduce**
```
# Navigate to Zephyr source root directory
source zephyr-env.sh
twister -vv -T tests/subsys/logging/log_backend_fs/ -p native_posix_6
```
You would expect to see
```
...
DEBUG   - OUTPUT: ===================================================================
DEBUG   - OUTPUT: START - test_fs_nonexist
DEBUG   - OUTPUT:  SKIP - test_fs_nonexist in 0.000 seconds
DEBUG   - OUTPUT: ===================================================================
DEBUG   - OUTPUT: START - test_log_fs_file_content
DEBUG   - OUTPUT:  PASS - test_log_fs_file_content in 0.000 seconds
DEBUG   - OUTPUT: ===================================================================
DEBUG   - OUTPUT: START - test_log_fs_file_size
DEBUG   - OUTPUT:  PASS - test_log_fs_file_size in 0.000 seconds
DEBUG   - OUTPUT: ===================================================================
DEBUG   - OUTPUT: START - test_log_fs_files_max
DEBUG   - OUTPUT:  PASS - test_log_fs_files_max in 0.000 seconds
DEBUG   - OUTPUT: ===================================================================
...
```
but instead you see
```
...
DEBUG   - logging.log_backend_fs.automounted.fs_nonexist: No status
DEBUG   - logging.log_backend_fs.automounted.log_fs_file_content: No status
DEBUG   - logging.log_backend_fs.automounted.log_fs_file_size: No status
DEBUG   - logging.log_backend_fs.automounted.log_fs_files_max: No status
DEBUG   - logging.log_backend_fs.automounted.wipe_fs_logs: No status
DEBUG   - logging.log_backend_fs.manualmounted.native_posix_64.fs_nonexist: No status
DEBUG   - logging.log_backend_fs.manualmounted.native_posix_64.log_fs_file_content: No status
DEBUG   - logging.log_backend_fs.manualmounted.native_posix_64.log_fs_file_size: No status
DEBUG   - logging.log_backend_fs.manualmounted.native_posix_64.log_fs_files_max: No status
...
```

**Impact**
This makes it impossible to correctly run tests against the `native_posix_64` platform. Furthermore, the exit code from this problem is `0`, which may give someone a false positive that their tests are passing.

### PR DESCRIPTION
**Pull request by pdietl**
boards: posix: native_posix_64: Add sim: native

If one does not specify `simulation: native` in a `testcase.yaml` file,
then when trying to run tests with `native_posix_64` as the platform,
the `TestInstance.setup_handler` method in
`scripts/pylib/twister/twisterlib/testinstance.py` will not assign a handler and
one's tests will be marked as ran, but the test output will all be of the
form "... No status" since the test binary is built but not ran.

Fixes #54605

Signed-off-by: Pete Dietl <petedietl@gmail.com>

### CODE REVIEW

**Comment by pdietl** [comment]
@henrikbrixandersen @maciejbaczmanski

**Review by aescolar — DISMISSED** [review]

**Comment by pdietl** [comment]
@aescolar sorry, I updated the commit message to fix a grammar mistake.

**Review by stephanosio — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by maciejbaczmanski** [comment]
Hi, commit message mentions `scripts/pylib/twister/twisterlib/handler.py` file and `Handler.setup_handler` method, but they don't seem to match ones in repo.

**Review by aescolar — DISMISSED** [review]

**Comment by aescolar** [comment]
@pdietl would you be so kind as to create a bug report to link to this issue (to follow the procedure, we need one to merge after the rc)

**Comment by pdietl** [comment]
> scripts/pylib/twister/twisterlib/handler.py

I'll fix the commit message.

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by pdietl** [comment]
> @pdietl would you be so kind as to create a bug report to link to this issue (to follow the procedure, we need one to merge after the rc)

Done! https://github.com/zephyrproject-rtos/zephyr/issues/54605

**Review by aescolar — DISMISSED** [review]

**Comment by aescolar** [comment]
@pdietl you can run gitlint locally to help with the compliance issues :)

**Review by maciejbaczmanski — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Pull request merged**
