### PR TITLE
Bluetooth: gatt: Fix DB corruption when adding/removing service

### PR DESCRIPTION
**Pull request by joerchan**
Fix an issue in the gatt_register routine where removing a service and
adding it again would cause the database to have non-ascending
orderdered handles numbers and lead to an incomplete service discovery.

Fix: Go through the database and look for a place where to insert
the new service.

Fixes: #17294

Backporting of:
#16593

### CODE REVIEW

**Comment by jhedberg** [comment]
@joerchan AFAIk the static services don't exist in 1.14 so #17265 should not be needed (in fact it'll likely cause build failure). @Vudentz can you confirm?

**Comment by Vudentz** [comment]
> @joerchan AFAIk the static services don't exist in 1.14 so #17265 should not be needed (in fact it'll likely cause build failure). @Vudentz can you confirm?

Yep, this should not be needed on 1.14, only the fix to not always append services which cause the corruption in the database.

**Comment by joerchan** [comment]
@jhedberg Yes, that seems correct. Will revert that.

**Comment by joerchan** [comment]
FYI: The merge conflicts was simply because the 'U' suffix had been added.

**Review by jhedberg — APPROVED** [review]

**Comment by joerchan** [comment]
@Vudentz Does it look correct now?

**Review by Vudentz — APPROVED** [review]

**Comment by joerchan** [comment]
Close because this backport is included in #18122

**Pull request closed without merging**
