### PR TITLE
drivers: eth: enc424j600: Add VLAN support

### PR DESCRIPTION
**Pull request by jukkar**
Add Virtual LAN support to enc424j600 Ethernet driver.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
Something is wrong in data reception, sometimes I see messages like
`<err> ethdrv: Maximum frame length (1518) exceeded (65531)`
so the data length is calculated wrongly if VLAN is enabled. I am investigating this.

**Comment by jukkar** [comment]
The issue with the enc424j600 driver is not related to these VLAN changes. I am seeing
```
[00:00:59.388,366] <err> ethdrv: Maximum frame length exceeded
```
with the upstream too, after this message connectivity does not work any more.
Steps to reproduce:
In Zephyr
```
$ cd samples/net/sockets/echo_server
$ cmake . -B buid -DBOARD=reel_board -DSHIELD=link_board_eth -DCONF_FILE="prj.conf;overlay-dhcp.conf"
$ make -C build flash
```
In Linux
```
$ cd net-tools
$ ./echo-client 192.0.2.1 -t -e
```

**Comment by jfischer-phytec-iot** [comment]
@jukkar I will check it.

**Comment by jukkar** [comment]
@jfischer-phytec-iot thanks. I did some quick debugging, and it looks like that the memory gets corrupted if there is lot of incoming traffic. I tried to enable flow control by setting `ENC424J600_ECON2_AUTOFC` but did not see any improvement in functionality.

**Comment by jukkar** [comment]
Just updated the branch with some additional settings (like enabling automatic flow control) that did not help with the issue.

**Comment by jukkar** [comment]
I tried the same test with enc28j60 as the drivers are quite similar and did not see same kind of issue there. The device seemed to read data ok when stress testing the system with lot of incoming packets. There was issues in that driver too as it printed errors on TX. These could be related to my cheap enc28j60 dongle thou.

**Review by tbursztyka — APPROVED** [review]

**Comment by jukkar** [comment]
Closing for now. Will need more investigation and TLC in the future.

**Pull request closed without merging**
