### PR TITLE
kernel: dynamic: use 4k stack size for x86

### PR DESCRIPTION
**Pull request by cfriedt**
x86 architectures require a dynamic stack size that is a multiple of 4096 bytes due to mmu restrictions.

For example, this test would previously fail when using the default dynamic stack size of 1024 bytes for 32-bit platforms (because a specific board configuration file was not present).

```shell
west build -p auto -b qemu_x86/atom/nopae -t run tests/posix/common/ -- -DCONFIG_USERSPACE=y
```

It would pass with an additional argument
```
west build -p auto -b qemu_x86/atom/nopae -t run tests/posix/common/ -- -DCONFIG_USERSPACE=y -DCONFIG_DYNAMIC_THREAD_STACK_SIZE=4096
```

Add a special default for x86 when using dynamic thread stacks.

The x86 default removes the need for `boards/qemu_x86*.conf`, with the exception of `qemu_x86_tiny`.
    
`qemu_x86_tiny` did not have sufficient memory (or configuration) to run the non-userspace tests, so bump up the available ram from 256k to 512k for this test and clone the `.conf` from the demand paging tests.
    
Eventually, the common posix test should be split into more concise functional categories to reduce ram requirements.

### CODE REVIEW

**Review by peter-mitsis — DISMISSED** [review]

**Comment by cfriedt** [comment]
* adjusted default conditionals

**Comment by cfriedt** [comment]
Additional bugfixes from @fgrandel for `qemu_x86_tiny` 🙏

**Review by ycsin — APPROVED** [review]
I wonder if having a BUILD_ASSERT somewhere to make sure that it is always the multiple of 4096 would help?

**Comment by cfriedt** [comment]
> I wonder if having a BUILD_ASSERT somewhere to make sure that it is always the multiple of 4096 would help?

Actually, there are per-arch macros that should round / pad stacks. It's confusing to me why they don't seem to work for x86. The extra .conf is required for for tiny as well.

**Review by bjarki-andreasen — APPROVED** [review]

**Pull request merged**
