### PR TITLE
drivers: lpc55s36: Remove deprecated CSS driver

### LINKED ISSUE #69961: tests: lpcxpresso55s36 : samples build failure
**Describe the bug**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>

CASE_NAME | ZEPHYR_VERSION | RESULT | PLATFORM | TEST_PATH
-- | -- | -- | -- | --
sample.posix.gettimeofday | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/posix/gettimeofday
sample.posix.eventfd | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/posix/eventfd
sample.net.sockets.socketpair | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/socketpair
sample.net.sockets.big_http_download | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/big_http_download
sample.net.sockets.big_http_download.posix | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/big_http_download
sample.net.sockets.big_http_download.ci | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/big_http_download
sample.net.sockets.can.one_socket | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/can
sample.net.sockets.can.two_sockets | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/can
sample.net.sockets.http_get | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/http_get
sample.net.sockets.http_get.posix | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/http_get
sample.net.sockets.dumb_http_server | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/dumb_http_server
sample.net.sockets.dumb_http_server.posix | v3.6.0-610-g39f710136ef7 | Build   failure | lpcxpresso55s36 | samples/net/sockets/dumb_http_server

</body>

</html>

**To Reproduce**
scripts/twister -p lpcxpresso55s36  -T samples/net/sockets

**Expected behavior**
Build PASS

**Impact**
board networking features

**Logs and console output**

```
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c: In function 'mcuxClCss_Ckdf_Sp800108_Async':
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/platforms/LPC55S3x/inc/ip_platform.h:32:32: error: 'CSS_BASE' undeclared (first use in this function); did you mean 'SCS_BASE'?
   32 | #define IP_CSS ((ip_css_Type *)CSS_BASE)
      |                                ^~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/inc/internal/mcuxClCss_Internal.h:37:33: note: in expansion of macro 'IP_CSS'
   37 | #define MCUXCLCSS_ISBUSY (1U == IP_CSS->CSS_STATUS_b.CSS_BUSY)
      |                                 ^~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c:37:9: note: in expansion of macro 'MCUXCLCSS_ISBUSY'
   37 |     if (MCUXCLCSS_ISBUSY)
      |         ^~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/platforms/LPC55S3x/inc/ip_platform.h:32:32: note: each undeclared identifier is reported only once for each function it appears in
   32 | #define IP_CSS ((ip_css_Type *)CSS_BASE)
      |                                ^~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/inc/internal/mcuxClCss_Internal.h:37:33: note: in expansion of macro 'IP_CSS'
   37 | #define MCUXCLCSS_ISBUSY (1U == IP_CSS->CSS_STATUS_b.CSS_BUSY)
      |                                 ^~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c:37:9: note: in expansion of macro 'MCUXCLCSS_ISBUSY'
   37 |     if (MCUXCLCSS_ISBUSY)
      |         ^~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c: In function 'mcuxClCss_Hkdf_Rfc5869_Async':
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/platforms/LPC55S3x/inc/ip_platform.h:32:32: error: 'CSS_BASE' undeclared (first use in this function); did you mean 'SCS_BASE'?
   32 | #define IP_CSS ((ip_css_Type *)CSS_BASE)
      |                                ^~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/inc/internal/mcuxClCss_Internal.h:37:33: note: in expansion of macro 'IP_CSS'
   37 | #define MCUXCLCSS_ISBUSY (1U == IP_CSS->CSS_STATUS_b.CSS_BUSY)
      |                                 ^~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c:68:9: note: in expansion of macro 'MCUXCLCSS_ISBUSY'
   68 |     if (MCUXCLCSS_ISBUSY)
      |         ^~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c: In function 'mcuxClCss_Hkdf_Sp80056c_Async':
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/platforms/LPC55S3x/inc/ip_platform.h:32:32: error: 'CSS_BASE' undeclared (first use in this function); did you mean 'SCS_BASE'?
   32 | #define IP_CSS ((ip_css_Type *)CSS_BASE)
      |                                ^~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/inc/internal/mcuxClCss_Internal.h:37:33: note: in expansion of macro 'IP_CSS'
   37 | #define MCUXCLCSS_ISBUSY (1U == IP_CSS->CSS_STATUS_b.CSS_BUSY)
      |                                 ^~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c:95:9: note: in expansion of macro 'MCUXCLCSS_ISBUSY'
   95 |     if (MCUXCLCSS_ISBUSY)
      |         ^~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c: In function 'mcuxClCss_TlsGenerateMasterKeyFromPreMasterKey_Async':
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/platforms/LPC55S3x/inc/ip_platform.h:32:32: error: 'CSS_BASE' undeclared (first use in this function); did you mean 'SCS_BASE'?
   32 | #define IP_CSS ((ip_css_Type *)CSS_BASE)
      |                                ^~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/inc/internal/mcuxClCss_Internal.h:37:33: note: in expansion of macro 'IP_CSS'
   37 | #define MCUXCLCSS_ISBUSY (1U == IP_CSS->CSS_STATUS_b.CSS_BUSY)
      |                                 ^~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c:121:9: note: in expansion of macro 'MCUXCLCSS_ISBUSY'
  121 |     if (MCUXCLCSS_ISBUSY)
      |         ^~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c: In function 'mcuxClCss_TlsGenerateSessionKeysFromMasterKey_Async':
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/platforms/LPC55S3x/inc/ip_platform.h:32:32: error: 'CSS_BASE' undeclared (first use in this function); did you mean 'SCS_BASE'?
   32 | #define IP_CSS ((ip_css_Type *)CSS_BASE)
      |                                ^~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/inc/internal/mcuxClCss_Internal.h:37:33: note: in expansion of macro 'IP_CSS'
   37 | #define MCUXCLCSS_ISBUSY (1U == IP_CSS->CSS_STATUS_b.CSS_BUSY)
      |                                 ^~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/modules/hal/nxp/mcux/mcux-sdk/components/css_pkc/src/comps/mcuxClCss/src/mcuxClCss_Kdf.c:147:9: note: in expansion of macro 'MCUXCLCSS_ISBUSY'
  147 |     if (MCUXCLCSS_ISBUSY)
      |         ^~~~~~~~~~~~~~~~
[172/217] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/ipv6_nbr.c.obj
ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used:  v3.6.0-610-g39f710136ef7

### PR DESCRIPTION
**Pull request by dleach02**
CSS was deprecated from the mcu-sdk. Removing driver from lpc55s36 to clear build error.

This is a temporary patch to remove the build error.

Fixes #69961

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
> CSS was deprecated from the mcu-sdk. Removing driver from lpc55s36 to clear build error.

Is there a replacement for the CSS driver?

**Comment by decsny** [comment]
> > CSS was deprecated from the mcu-sdk. Removing driver from lpc55s36 to clear build error.
> 
> Is there a replacement for the CSS driver? As far as I can tell, it has not been deprecated within the Zephyr tree.

No and we are immediately removing it from zephyr

**Comment by hakehuang** [comment]
@dleach02  need remove below, to re-enable twister on this platform.

https://github.com/zephyrproject-rtos/zephyr/blob/c38ea288eee954c0ba9e51a79eb16390f3476e5e/boards/nxp/lpcxpresso55s36/lpcxpresso55s36.yaml#L23

**Review by hakehuang — DISMISSED** [review]
full regression build and sanity check run pass, on lpcxpresso55s36, but looks like imx8qxp_mek/mimx8qx6/adsp has issue with head, let me regression with mainline code

mainline code with commit https://github.com/zephyrproject-rtos/zephyr/commit/b9f3d68863b9f75dcc1dfac7dd7ff269b99cd118 is ok
•	name :imx8qxp_mek/mimx8qx6/adsp
•	tests :116
•	failures :0
•	errors :0
•	skipped :0


code with this PR HAL fails
•	name :imx8qxp_mek/mimx8qx6/adsp
•	tests :116
•	failures :0
•	errors :116
•	skipped :0

**Review by mmahadevan108 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@ceolin , could you help take a look at this PR.

**Review by ceolin — APPROVED** [review]

**Pull request merged**
