### PR TITLE
cmake: "dummy-flash" device tree fix

### PR DESCRIPTION
**Pull request by diegosueiro**
Create aditional variable node_address to store the definition type
for nand flash.

#6365
Signed-off-by: Diego Sueiro <diego.sueiro@gmail.com>

### CODE REVIEW

**Review by galak — COMMENTED** [review]
What actual issue are you trying to fix?

**Comment by diegosueiro** [comment]
@galak,

> What actual issue are you trying to fix?

If you look at the issue #6366 you will see the error message when I try to generated_dts_board.h from a dts without the "zephyr,flash" property entry.

I validated this change with and without the "zephyr,flash" property entry it is working properly.

**Comment by diegosueiro** [comment]
@galak,

Any feedbacks on this?

**Comment by nashif** [comment]
> If you look at the issue #6366 you will see the error message when I try to generated_dts_board.h from a dts without the "zephyr,flash" property entry.

you are referencing this same PR here, what is the correct issue number?

**Comment by diegosueiro** [comment]
@nashif,

> you are referencing this same PR here, what is the correct issue number?

Sorry for the confusion. The issue is #[6365](https://github.com/zephyrproject-rtos/zephyr/issues/6365)

**Comment by galak** [comment]
> @galak,
> 
> Any feedbacks on this?

I need to look into this further and understand what's happening.

**Comment by galak** [comment]
@diegosueiro do we still need this?

**Comment by diegosueiro** [comment]
@galak,

Are we going to address this issue?
I found a solution described [here](https://github.com/zephyrproject-rtos/zephyr/issues/6365#issuecomment-389265713) but you haven't given me any feedback.

**Pull request closed without merging**
