### PR TITLE
Bluetooth: Mesh: Fix IV Update tests when duration is unknown

### PR DESCRIPTION
**Pull request by jhedberg**
When we get provisioned we can't know how long the network has been in
the current IV Update state. Introduce a special value for
bt_mesh.last_update to indicate that we don't know the duration.

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
@kkietava @petrip @rymanluk FYI

**Comment by jhedberg** [comment]
@MariuszSkamra it'd be good to run IV update PTS tests on this one

**Comment by jhedberg** [comment]
@MariuszSkamra I think that's because I wasn't updating the timestamp for beacons that are "no-op" when we have no prior timestamp. I've fixed this now, so please test again. I also added a third patch to remove what looks to me like a redundant condition, so it'll be interesting to see if that has any side effects as well.

**Comment by jhedberg** [comment]
@MariuszSkamra did you have a chance to re-run the tests?

**Comment by MariuszSkamra** [comment]
Still not passing.
 1/10   MESH   MESH/NODE/IVU/BV-03-C   PASS                     
 2/10   MESH   MESH/NODE/IVU/BV-01-C   PASS                     
 3/10   MESH   MESH/NODE/IVU/BV-05-C   PASS                     
 4/10   MESH   MESH/NODE/IVU/BV-02-C   PASS                     
 5/10   MESH   MESH/NODE/IVU/BV-04-C   PASS                     
 6/10   MESH   MESH/NODE/IVU/BI-04-C   PASS                     
 7/10   MESH   MESH/NODE/IVU/BI-02-C   PASS                     
 8/10   MESH   MESH/NODE/IVU/BI-01-C   FAIL                     
 9/10   MESH   MESH/NODE/IVU/BI-06-C   PASS                     
10/10   MESH   MESH/NODE/IVU/BI-05-C   PASS   

MESH/NODE/IVU/BI-01-C requires to send Secure Network Beacon with IV Update flag not set.
After provosioning, PTS asks to make sure that IV Update procedure was performed less that 96 hours ago (so that IV Update flag is not set). We respond "OK" by default. No action is performed.
MMI description: "Please make sure IUT has performed an IV Update procedure less than 96 hours ago. PTS will verify IUT does not perform another update. Order IUT to generate non-connectable Secure Network beacons (Mesh Beacon with Beacon type = 0x01)."

I checked the  logs, and the problem is that PTS receives Secure Beacon with IV Update: IV Update Active flag set.

**Comment by jhedberg** [comment]
@MariuszSkamra my latest fix was based on step 2 in the test case description:

> 2. The Lower Tester generates a Secure Network beacon using the same network credentials and
IV Index as the IUT (n), advertises this beacon periodically, and scans for neighboring beacons.

With my change, when we receive one of these initial beacons the time stamp should get updated instead of remaining as `IV_UPDATE_UNKNOWN`. Any idea why it's not happening could you investigage?

Alternatively, perhaps the description of the test case implies that we should be forcing an update to the IUT using `bt_mesh_iv_update()` to ensure that the "less than 96 hours ago" requirement is fulfilled.

**Comment by jhedberg** [comment]
Sorry, it's actually step 1 for BI-01-C (I was looking at BV-05-C). The step description is essentially the same though.

**Comment by MariuszSkamra** [comment]
Failing case: https://pastebin.com/cwjgbhbF
Passing case: https://pastebin.com/XPTt9MV2

**Comment by jhedberg** [comment]
I'll quote here the relevant part from the failing log:

```
[bt] [DBG] secure_beacon_recv: (0x20001944) flags 0x00 id 711f93c6346a15b6 iv_index 0x0000000a
[bt] [DBG] secure_beacon_recv: (0x20001944) net_idx 0x0000 iv_index 0x0000000a, current iv_index 0x0000000a
[bt] [DBG] bt_mesh_net_iv_update: (0x20001944) Same IV Index in normal mode
[bt] [DBG] bt_mesh_beacon_recv: (0x20001944) 22 bytes: 0102711f93c6346a15b60000000b444ad118e40a55e3
[bt] [DBG] secure_beacon_recv: (0x20001944) flags 0x02 id 711f93c6346a15b6 iv_index 0x0000000b
[bt] [DBG] secure_beacon_recv: (0x20001944) net_idx 0x0000 iv_index 0x0000000b, current iv_index 0x0000000a
[bt] [DBG] bt_mesh_net_iv_update: (0x20001944) IV Update state entered. New index 0x0000000b
```

The "Same IV Index in normal mode" log indicates that a branch which calls update_ivu_timestamp() was taken. The later log "IV Update state entered. New index 0x0000000b" indicates that none of the following branches were taken:

```
        if (bt_mesh.last_update != IV_UPDATE_UNKNOWN &&
            !(IS_ENABLED(CONFIG_BT_MESH_IV_UPDATE_TEST) && bt_mesh.ivu_test)) {
                s64_t delta = k_uptime_get() - bt_mesh.last_update;

                if (delta < K_HOURS(96)) {
                        BT_WARN("IV Update before minimum duration");
                        return false;
                }
```

Since `bt_mesh.last_updated` should have been updated based on the first log I referred to, the only explanation I can think of why the above branches were not entered is that `CONFIG_BT_MESH_IV_UPDATE_TEST=y`. Is that the case @MariuszSkamra ? Only other explanation is if you didn't test with the patches in this PR.

**Comment by jhedberg** [comment]
@MariuszSkamra nevermind - I had a really silly bug in my PR:

```
--- a/subsys/bluetooth/host/mesh/net.c
+++ b/subsys/bluetooth/host/mesh/net.c
@@ -633,7 +633,7 @@ void bt_mesh_net_sec_update(struct bt_mesh_subnet *sub)
 
 static void update_ivu_timestamp(void)
 {
-       if (bt_mesh.iv_update == IV_UPDATE_UNKNOWN) {
+       if (bt_mesh.last_update == IV_UPDATE_UNKNOWN) {
                bt_mesh.last_update = k_uptime_get();
        }
 }
```

**Comment by jhedberg** [comment]
@MariuszSkamra I'm updated the PR with the fix. Could you please re-test one more time, thanks.

**Comment by MariuszSkamra** [comment]
All pass now, thanks.            
 1/10   MESH   MESH/NODE/IVU/BV-03-C   PASS             
 2/10   MESH   MESH/NODE/IVU/BV-01-C   PASS      
 3/10   MESH   MESH/NODE/IVU/BV-05-C   PASS                     
 4/10   MESH   MESH/NODE/IVU/BV-02-C   PASS                     
 5/10   MESH   MESH/NODE/IVU/BV-04-C   PASS                     
 6/10   MESH   MESH/NODE/IVU/BI-04-C   PASS                             
 7/10   MESH   MESH/NODE/IVU/BI-02-C   PASS        
 8/10   MESH   MESH/NODE/IVU/BI-01-C   PASS                     
 9/10   MESH   MESH/NODE/IVU/BI-06-C   PASS                     
10/10   MESH   MESH/NODE/IVU/BI-05-C   PASS

**Comment by jhedberg** [comment]
> All pass now, thanks.

Thanks @MariuszSkamra 

Now I'd just need a review from one of the formal reviewers with merge access. Ping @Vudentz @sjanc @carlescufi

**Review by sjanc — APPROVED** [review]

**Pull request merged**
