### PR TITLE
all SYS_LOG_* configs need to depend on SYS_LOG

### PR DESCRIPTION
**Pull request by nashif**

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Shouldn't this be other way around, meaning we should select SYS_LOG if individual debugging is activated?

**Comment by nashif** [comment]
> Shouldn't this be other way around, meaning we should select SYS_LOG if individual debugging is activated?

How do you turn off all syslogging in an application? Do I have to go to every component syslog variable and turn it off? using select for this type of thing is wrong IMO, thats why I always have issues turning off logging in network application that automatically enable that in mysterious ways. 

A config file of an application should be able to have lots of sys log related variables configured and turned on with one master switch that can turn it of completely, that is CONFIG_SYS_LOG.

**Comment by jukkar** [comment]
> How do you turn off all syslogging in an application? Do I have to go to every component syslog variable and turn it off? using select for this type of thing is wrong IMO, thats why I always have issues turning off logging in network application that automatically enable that in mysterious ways.
> 
> A config file of an application should be able to have lots of sys log related variables configured and turned on with one master switch that can turn it of completely, that is CONFIG_SYS_LOG.

For networking stuff there is CONFIG_NET_LOG that will turn on/off all the network debugging.

**Comment by jukkar** [comment]
Anyway, I am fine with the change. So +1 for the network related changes.

**Comment by nashif** [comment]
> For networking stuff there is CONFIG_NET_LOG that will turn on/off all the network debugging.

Thats the thing, you are globally enabling SYS_LOG, so if I try to disable this for debugging some driver that has nothing to do with networking, I can't. It makes Kconfig behave in unexpected ways and itself will be hard to debug ;-(

Anyways, I added the dependency to avoid stray Kconfig variables but the issue with select is something we need to optimize

**Review by galak — APPROVED** [review]

**Pull request merged**
