### PR TITLE
Litex: clock: Undefined behavior due to unchecked return code

### PR DESCRIPTION
**Pull request by franc0is**
Found via static analysis. Two separate error paths where failing to check the return code leads to undefined behavior:
1. In `litex_clk_get_phase`, the divider stays set to 0 when `litex_clk_get_clkout_divider` errors out, which leads to a division by 0.
2. In `litex_clk_calc_duty_normal`, the `duty` struct is used uninitialized if `litex_clk_get_duty_cycle` errors out.

In both case, checking the return code and returning early resolves the issue.

### CODE REVIEW

**Review by fkokosinski — APPROVED** [review]
LGTM

**Review by mateusz-holenko — APPROVED** [review]
Looks fine to me

**Comment by kartben** [comment]
rebased to trigger CI

**Review by maass-hamburg — APPROVED** [review]

**Comment by kartben** [comment]
re-assigning as per recent update to MAINTAINERS.yml

**Pull request merged**
