### PR TITLE
west.yml: Update NXP HAL MCUX-SDK to 2.15.000

### PR DESCRIPTION
**Pull request by dleach02**
Update NXP HAL mcux-sdk to 2.15.000

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@hakehuang, can we run a full test cycle on this HAL update PR.

**Comment by hakehuang** [comment]
> @hakehuang, can we run a full test cycle on this HAL update PR.

sure, testing kicked

**Comment by mmahadevan108** [comment]
@hakehuang, thank you for testing. I have pulled in the fixes to the HAL drivers and it fixes the build failures you reported.

**Comment by hakehuang** [comment]
> @hakehuang, thank you for testing. I have pulled in the fixes to the HAL drivers and it fixes the build failures you reported.

regression on RT595 test done. no new issues found. All NXP board build PASS and board testing for BLEP(except imx8/9 series) are done. No new issues found

**Review by danieldegrasse — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Comment by hakehuang** [comment]
update status. 

other than issue: #69730 

below are new failures

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<body>
CASE_NAME | ZEPHYR_VERSION | RESULT | PLATFORM | TEST_PATH
-- | -- | -- | -- | --
drivers.adc | v3.6.0-456-g7333186002cd | Build   failure | lpcxpresso55s69/lpc55s69/cpu0 | tests/drivers/adc/adc_api


</body>

</html>

**Comment by fabiobaltieri** [comment]
Thanks @dleach02, had a quick look at the diffstat, noticed you dropped few more files :-) I'd suggest filtering out all png as well for the next round, just a couple megs of them in there but they'll add over time.

**Pull request merged**
