### PR TITLE
arc: hsdk: bug fixes and new feature supports

### PR DESCRIPTION
**Pull request by IRISZZW**
This PR includes necessary bug fixes and some new feature supports of arc hsdk board. To avoid the possible confilcts of separate PR, I use one single PR to include all commits.

### So please review the code in the unit of commit.

### CODE REVIEW

**Comment by vonhust** [comment]
@IRISZZW , pls the fix comment and coding style. You can refer  https://docs.zephyrproject.org/latest/contribute/index.html#coding-style

**Comment by ulfalizer** [comment]
Hmm... I should fix the CI `checkpatch` output so that it uses a code block. Wonder if that's a regression.

**Comment by ulfalizer** [comment]
(FWIW, I think we should start allowing `//` comments. Everything that might have had trouble with them is long gone I think, and it's a cleaner and more compact syntax.)

**Review by dbkinder — APPROVED** [review]
Doc changes LGTM, thanks!

**Review by abrodkin — APPROVED** [review]
Please care to write commit messages where you explain what was the problem you're dealing with and why did you fix it the way you did.

For example I don't understand what kind of bug "arc: hsdk: dts: bug fix" really fixes. And yes it
s not clear from the change itself. Moreover I guess HSDK's .dts was copied over from the Linux source tree and then if you really fixes a valid problem we'll need to do similar change to the same file in the Linux kernel but so far I'm not convinced there's a problem to start with.

**Review by nashif — APPROVED** [review]

**Pull request merged**
