### PR TITLE
arch: arm: atmel_sam: Map the whole RAM in MPU

### PR DESCRIPTION
**Pull request by tgorochowik**
Only the first memory region was mapped in MPU.

The header specifies two regions for all possible RAM sizes for atmel
socs so this change will work fine even for devices for which a single
region would be enough.

Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>

### CODE REVIEW

**Review by tyrantlizard77 — DISMISSED** [review]

**Comment by andrewboie** [comment]
Note: for configurations where CONFIG_SRAM_SIZE is a power of two, we are wasting an MPU region by splitting it into two equal halves, see definitions in arch/arm/common/soc/atmel_sam/common/arm_mpu_mem_cfg.h

Would be better to revise that header and have an #ifdef around the second region definition, to use only if the total RAM size isn't a power of two.

**Comment by tgorochowik** [comment]
@andrewboie Thanks! I guess that makes sense, please see the updates.

Question: is it ok to leave the `_0` suffix even if there is just one region? I think I saw somewhere that you have a convention not to use the suffix when there is just a single region, but leaving it like this requires fewer `ifdefs` so I guess it makes sense to keep it in this case.

**Review by ioannisg — APPROVED** [review]
Looks ok to me

**Review by tyrantlizard77 — APPROVED** [review]
thanks!!

**Pull request merged**
