### PR TITLE
drivers: eeprom: shell cmd write can now handle hex data

### PR DESCRIPTION
**Pull request by chrta**
Modified eeprom shell write command to be able to handle hex data
bytes.

Signed-off-by: Christian Taedcke <christian.taedcke@lemonbeat.com>

### CODE REVIEW

**Comment by chrta** [comment]
With this change the format of the input data (write cmd) and output data (read cmd) is the same. Also this is the same way as it is done in the flash write command, see https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/flash/flash_shell.c#L114

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Thank you for your contribution. However, I would rather not change this.

The current code accepts not only decimal values, but also hex if you write them with a `0x` prefix. Your change requires the input to be in hexadecimal, resulting in less flexibility.

**Comment by chrta** [comment]
@henrikbrixandersen Thank you for your feedback. The commit message and title is misleading, but in my opinion the code change improves the user experience.
Me and my colleague were confused by the implementation, since it is not obvious, when not looking into the implementation. Without this change the behaviour is as follows:
```
uart:~$ eeprom 
eeprom - EEPROM shell commands
Subcommands:
  read   :<device> <offset> <length>
  write  :<device> <offset> [byte0] <byte1> .. <byteN>
  size   :<device>
  fill   :<device> <offset> <length> <pattern>
```

So the documentation of the write command indicates to input each `byte`, not mentioning the format. When i print the eeprom content:
```
uart:~$ eeprom read EEPROM_0 0 8
Reading 8 bytes from EEPROM, offset 0...
00000000: ff ff ff ff ff ff ff ff                          |........         |
```

Every byte is displayed as hex without any prefix.

Now when i want to write the same content back assuming the argument format for write is the same as it is for the read output (for the first three byte):
```
uart:~$ eeprom write EEPROM_0 0 ff ff ff 
Writing 3 bytes to EEPROM...
Verifying...
Verify OK
uart:~$ eeprom read EEPROM_0 0 8
Reading 8 bytes from EEPROM, offset 0...
00000000: 00 00 00 ff ff ff ff ff                          |........         |
```

So there is no error message, just 0 is written without any indication of an error.

Of course this would work:
```
uart:~$ eeprom write EEPROM_0 0 0xff 0xff 0xff
uart:~$ eeprom write EEPROM_0 0 255 255 255
uart:~$ eeprom write EEPROM_0 0 0377 0377 0377
```

I think also this is confusing if it is not documented:
```
uart:~$ eeprom write EEPROM_0 0 010 010 010
Writing 3 bytes to EEPROM...
Verifying...
Verify OK
uart:~$ eeprom read EEPROM_0 0 8
Reading 8 bytes from EEPROM, offset 0...
00000000: 08 08 08 ff ff ff ff ff                          |........         |

```

So with my purposed change we will lose the ability to enter decimal and octal values, but imho the format of the `byte` input behaves with "less surprises".

**Comment by henrikbrixandersen** [comment]
> So with my purposed change we will lose the ability to enter decimal and octal values, but imho the format of the `byte` input behaves with "less surprises".

I am sorry, but I disagree that the proposed behavior has "less surprises".

It is quite common to use `strtoul(..., NULL, 0)` for argument parsing in open-source shell utilities and leave the base up to the user. I would be very surprised if entering "10" would actually mean 16 decimal (as opposed to entering "0x10" where I of course would expect it to mean 16 decimal).

**Comment by chrta** [comment]
@henrikbrixandersen OK, i see that you have a different opinion here. But i would like to hear an opinion from someone else here who also uses the eeprom shell commands to have a 3rd opinion.

I still think that the current eeprom shell command interface could benefit from this change.

**Pull request closed without merging**
