### PR TITLE
lib: posix: support for pthread_attr_setstacksize()

### LINKED ISSUE #44722: lib: posix: support for pthread_attr_setstacksize
**Is your enhancement proposal related to a problem? Please describe.**
We already support `pthread_attr_getstacksize()`. It would also make sense to support `pthread_attr_setstacksize()`.

**Describe the solution you'd like**
A static inline implementation should suffice.

**Describe alternatives you've considered**
The status quo, which is non-standard.

**Additional context**
Note: this is not a (thread) runtime operation, and is used prior to calling `pthread_create()`.

### PR DESCRIPTION
**Pull request by cfriedt**
We already support `pthread_attr_getstacksize()`. It would also make sense to support `pthread_attr_setstacksize()`. 

Fixes #44722

(Compliance check is a false positive)

### CODE REVIEW

**Comment by cfriedt** [comment]
Compliance check is a false positive

**Review by stephanosio — DISMISSED** [review]

**Comment by cfriedt** [comment]
Just noticed this:
```
3: UC4 Line exceeds max length (76>75): "Tests for `pthread_attr_setstacksize(3)` and `pthread_attr_getstacksize(3)`."
```

Will fix it up

**Comment by cfriedt** [comment]
@stephanosio - sorry for the rebase, just wanted to keep line lengths legal. Please ack again when you have a minute.

**Review by stephanosio — APPROVED** [review]

**Review by povergoing — APPROVED** [review]
LGTM

**Pull request merged**
