### PR TITLE
adi_sdp_k1: Enable usb cdc support

### PR DESCRIPTION
**Pull request by ahaslam2**
This PR adds support for usb cdc on the adi sdp k1.

the PR includes:
- patch to fix to avoid disabling ULPI clk in case of external ULPI phy.
- DT changes to enable ulpi phy and usb udc on sdp_k1.

Validated using a sdp_k1 revE using the  samples/subsys/usb/cdc_acm application: the board enumerates correctly on a linux pc, and opening the ttyACMx
device we are able to see the characters that are echoed back.

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]

**Comment by jfischer-no** [comment]
DNM until @erwango reviewed clock changes.

**Review by erwango — DISMISSED** [review]

**Review by jfischer-no — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Review by tmon-nordic — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]
Needs converting to hwmv2

**Comment by kartben** [comment]
Hi @ahaslam2  -- can you please rebase your change to pick up the recent modifications around "hardware model v2"?

**Review by tmon-nordic — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
@nordicjm please revisit

**Pull request merged**
