### PR TITLE
arch: ARM: set -mabi and -march in linker flags

### PR DESCRIPTION
**Pull request by aurel32**
Some toolchains are built with multilib enabled in order to provide
multiple versions of the same library, optimized for different ABI
or architecture. They require the -march= and -mabi= options to be
passed at link time. This is important for example when linking with
newlib.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

### CODE REVIEW

**Comment by aurel32** [comment]
I have just pushed a new version with an additional commit doing the same for -mthumb, -mcpu, -mfpu and -mfloat-abi as we can't always get -march defined (e.g. for Cortex-M7).

**Review by SebastianBoe — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@nashif : This is ready to be merged.

**Review by ioannisg — CHANGES_REQUESTED** [review]
As far as I could see, -march option is not appended.
If so, please, update the commit message.

**Comment by aurel32** [comment]
> As far as I could see, -march option is not appended.
> If so, please, update the commit message.

@ioannisg, the -march option is different for each CPU, so is passed through `${ARCH_FLAG}` which  is defined a few lines above. I have updated the commit message to make that more clear. No code change.

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
