### PR TITLE
[RFC][WIP] SOCKS5 proxy server implementation

### PR DESCRIPTION
**Pull request by tgorochowik**
This PR adds an initial lib implementation of SOCKS proxy (version 5).

What is working:
* TCP connections without any authentication
* IPv4 addressing

Sample test/network setup:
* Zephyr node running a HTTP server (e.g. `192.168.0.100`)
* Zephyr node running this proxy server (e.g. `192.168.0.150`)
* A PC with `curl` installed.

With that setup, it should be possible to download what's the http server is serving through the proxy node with:
```
$ curl --socks5 192.168.0.150:1080 192.168.0.100
<html>
  <head>
    <meta charset="UTF-8">
    <title>Zephyr HTTP server sample</title>
  </head>

  <body>
    <div>
      <p>It works!</p>
    </div>
  </body>
</html>
```

I am opening this PR early in hope to:
* Receive early general review that to avoid that when the socks5 server is complete and there is more code with possibly the same issues
* Trigger some discussion about how the network app api could be improved

About the API:
The most problematic thing in my opinion is that all the callbacks lack per-connection private data. What I have in mind is a server application with multiple clients connected at once.

For the `recv` or `send` callback, we do get the `pkt` which has `net_context` - which is you could say could act as an identifier of the peer that is connected.

For the `connect` callback, there is no such thing. And it could be very useful when using it with some protocols that require initializing a state machine.
The `close` callback is not even called for each peer closing its connection. Its called only once, after all the connections have been closed.

In the current socks5 code, you can see these issues are worked around. The per-connection private data pointers are selected based on their state (to initialize: `socks_find_free_client_slot`) and then using the remote data to see which private data should be used (`recv` cb: `socks_find_client`). Checking which client disconnected is guesswork. We don't even get the callback if there is another client that did not terminate its connection yet.

I think it would be the best not to have to implement such helpers at all. It would be the best if API could do this for us.

Here are some ideas that I hope to receive some comments to:
* The `net_app_ctx` struct should get something like: `void *connection_data[CONFIG_NET_APP_SERVER_NUM_CONN]`. All the callbacks should be able to use this pointer (e.g. via an argument). Users could then set this to point to their app specific per-peer data in the `connect` callback, and then use it in the `recv`, `send`, and `close` callbacks
* The `close` callback should be called for EACH peer that closes its connection. That was  actually the case prior to: https://github.com/zephyrproject-rtos/zephyr/commit/88e8119078f - I think that the problem this commit solved could be solved differently (in the http code)

The _problem_ with this approach is that the client implementations in net app api use the same interface for callbacks. Being a client implicates being the only peer, so the per-connection pointers are completely redundant in this case.

I am open to all comments on about the current SOCKS5 implementation and about the API issues (and possible solutions) that this implementation uncovers. If there is an easier and more reliable way to work-around those issues I would be glad to hear about it as well.

Thanks!

### CODE REVIEW

**Comment by pfalcon** [comment]
net_app is deprecated. BSD Sockets is the networking API in Zephyr.

**Review by tbursztyka — CHANGES_REQUESTED** [review]
Hum, there is a big issue with this lib: it uses net_app, net_context, net_pkt, etc... 

It should be using socket exclusively. It was decided (almost a year ago in fact) that socket should be the unique end point for the user (and libraries etc...). All the other are net core only. (net_app is probably going to /dev/null)
There is an going work to change how net_pkt works (see PR #11775) and that's going to affect your code heavily. You would be using socket: it wouldn't affect at all.

I am sorry if the communication was unclear about this big moves.

**Comment by tgorochowik** [comment]
@pfalcon @tbursztyka ok thanks! It is quite confusing actually, especially that the net_app API is marked as EXPERIMENTAL - it looks almost like it is the _next_ thing.

I am glad we did not continue with other features of SOCKS with this implementation then! Better now than later.

Could we somehow explicitly mark the net_app API as deprecated then? Be it in Kconfig, or with some comments at the beginning of the source respective files?

**Comment by pfalcon** [comment]
@tgorochowik :

> net_app API is marked as EXPERIMENTAL - it looks almost like it is the next thing.

Well, EXPERIMENTAL just means it's subject to change, a change may include going away too...

> Could we somehow explicitly mark the net_app API as deprecated then? Be it in Kconfig, or with some comments at the beginning of the source files?

So, the actual state of net_app I'd describe as "pre-deprecation". The idea is:

1. All previous networking facilities weren't migrated to sockets yet, so socket networking is not yet "there".
2. With that in mind, and even without that, the idea is to not "disturb" users. If net_app-based protocol implementations work for them, they continue to use them, until socket-based implementations appear.
3. But given already spent effort to migrate protocol libs to sockets, which only continues, it would be quite fair to not accept implementations based on net_app into mainline, and in general, encourage users to start new implementations with sockets instead.

The migration process requirements/status is tracked via https://github.com/zephyrproject-rtos/zephyr/issues/7591

**Comment by tgorochowik** [comment]
Ok thanks, that makes perfect sense!

Of course I do understand what experimental means, all I'm saying that it is just quite easy to misinterpret it (which I did) I also do agree that it is more than fair not to accept new implementations with that API now that I know what you know (especially that I believe this API is not fully functional).

What about at least adding a note to the beginning of:
https://docs.zephyrproject.org/1.13.0/subsystems/networking/net-app-api.html
Saying to at least consider (like you said *encourage*) using sockets instead?

Anyway: that is just a suggestion in hope nobody else falls into the same trap. I am closing this PR for now, thanks for your time!

**Comment by pfalcon** [comment]
@tgorochowik: I agree that we definitely need to do something to "spead the word". If you have very quick idea to implement in that regard, like adding a notice like you propose, feel free to shoot a PR (dunno if such would be accepted right away, but worth a try). Otherwise, I consider it to be in my queue to do various things in that regard (tickets to refer people to, posts to maillists, etc.).

**Comment by pfalcon** [comment]
@tgorochowik: I hope that this was closed by mistake or to trigger CI. The PR itself is even marked for 1.14.0 (though I'm not sure if keep pushing more and more stuff into it), and lack of reply is due to all-hands work on other areas before 1.14 freeze.

**Comment by pfalcon** [comment]
@tgorochowik: Ok, thanks for explanation, sounds good. It's just that just yesterday at the networking meeting we were talking that the more samples we have the better, because otherwise we can't exercise socket API and networking in general. So, any code written is useful and precious, though of course each of us should be ready that it may take extra time to get it reviewed (and changes may be requested, as usual).

**Pull request closed without merging**
