### PR TITLE
net: sockets: Allow to create both native and offloaded sockets

### PR DESCRIPTION
**Pull request by rlubos**
So far it was impossible to create both native and offloaded sockets (in
case mutliple interfaces are avaialble) as the decission regarding
socket implementation is made solely on the addres family, socket type
and socket protocol. This makes it impossible to differentiate between
offloaded and native sockets based only on this information.

Fix this, by introducing NET_SOCKET_OFFLOADED_REGISTER macro, allowing
to explictly mark the socket implementation as offloaded. Additionally,
add SOCK_NATIVE flag that can be or'ed with the targeted socket type
(for instance SOCK_STREAM | SOCK_NATIVE), which makes it explicit that
native socket should be created instead of an offloaded one.

With this approach, offloaded sockets takes preference, being the
default choice when creating socket (provided that the offloaded
impelmentatinon matches the family/type/protocol as indicated by
is_suported() function. However, if the socket type is or'ed with
SOCK_NATIVE flag, the offloaded implementations are skipped and a native
socket is created instead.

### CODE REVIEW

**Comment by junqingzou** [comment]
Solution verified with Nordic nRF Connection SDK, concurrent TLS solutions by both SOCK_NATIVE and offload (modem) sockets.

**Review by junqingzou — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
LGTM

**Review by pfalcon — CHANGES_REQUESTED** [review]
I find this solution rather hacky, not well-thought-out, unscalable. What if there will be 2 or more offloaded interfaces? Why an offloaded interface (a random offloaded interface among many?) is made default, and generic sockets (supposedly more feature-rich/compliant) require an adhoc non-standard flag to be accessed?

Yet when the idea of pluggable socket family handlers was implemented, I suggested @jukkar to implement it in a more generic way, exactly to cover such usecases. That consisted of:

1. Having a "priority" for registered socket handler (similar to other registration "priorities" used throughout Zephyr).
2. Have an "is_handled_by" callback in each socket handler implementation, which would be passed socket() parameters and could return true if that handler should handle that combination.

That would cover cases of: a) having any number of offloaded/non-offloaded socket implementations; b) allow more flexible ordering using "priorities" (which can be made configurable using Kconfig); c) wouldn't enforce non-standard, inflexible things like SOCK_NATIVE (native should be default, then offloaded implementations can specify any number of adhoc flags on their side).

Note that still wouldn't be the "right" way to do it. The right way is to dispatch based on the socket address (local/remote), i.e. based on the routing table. Because that's how it would usually work in practice - each interface would deal with particular networks (their addresses), and that's exactly what's encoded in the routing table. That would work like any other real OS works (e.g.  Linux), allow routing between native/offloaded interfaces (which is probably not supported by Zephyr), etc. Of course, implementing that would take much more effort and considerable refactoring, so I don't suggest to do it here.

But let me humbly give -1 and request serious consideration of making socket handler registration more flexible and configurable, instead of applying once-off patches on top of already not flexible enough infrastructure.

**Comment by mniestroj** [comment]
I do agree with most of @pfalcon comments. SOCK_NATIVE flag seems to be a hacky way of managing one native and one offloaded interface. There will still be no way of using more native or more offloaded interfaces. Besides, application layer should not be aware of type of network interfaces (whether they are offloaded or native). I think that socket creation should be postponed, so that it is "finished" after getting more information from connect() or bind() calls, taking into account routing table (or after manually binding socket to specific interface with SO_BINDTODEVICE).

**Comment by rlubos** [comment]
Thank you for the feedback. I'll try to shed some more light on my reasoning here. Let's first consider the current appraoch to allow the coexistence of native/offloaded sockets, w/o major stack rework.

@pfalcon 

> 2. Have an "is_handled_by" callback in each socket handler implementation, which would be passed socket() parameters and could return true if that handler should handle that combination.

We actually already have `is_supported()` callback that verifies family/type/protocol combination. The problem is that this does not solve the issue when multiple socket implementations (offloaded or not) support the same set of these parameters.

> What if there will be 2 or more offloaded interfaces?

The idea was that particular offloaded implementations could be enabled/disabled by modifying the return value of the `is_supported()` callback with some custom API (not present in this PR as it was supposed only to support native/offloaded coexistence). I don't see any other way to support multiple offloaded interfaces w/o more invasive changes (i. e. already mentioned postponing of socket creation).

> Why an offloaded interface (a random offloaded interface among many?) is made default, and generic sockets (supposedly more feature-rich/compliant) require an adhoc non-standard flag to be accessed?

This indeed might've been driven more by our specific use-case and could be a subject of change. In our scenario, we use a standard socket API with offloaded sockets, but optionally we also allow to create a native TLS socket, but I guess it could also be possible to make the native default. Or just drop the idea, if the priorities are implemented.


> 1. Having a "priority" for registered socket handler (similar to other registration "priorities" used throughout Zephyr).

Actually, the ambiguity in the socket processing order was the main reason to go upstream with these changes, otherwise, I would be able to implement the offloaded/native socket cooperation on the nRF side entirely. I've approached this by prioritizing the offloaded sockets in general over the native ones, but allowing to specify priorities at per socket implementation basis sounds more flexible. I think that for short term solution I'll actually try to add the priorities instead.

@mniestroj

> There will still be no way of using more native or more offloaded interfaces.

See above, but do you see any case when multiple native socket implementations (i.e. sitting on top of Zephyr networking stack) would support the same subset of family/type/protocol? As far as I understand it's only an issue when offloading is involved.

### ---

Now as for the "right" way of binding a socket with an implementation/interface by postponing the actual socket creation, I thought of this as well initially, as this sounded the most flexible way from the application point of view. I gave up on the idea however due to several reasons (apart from the complexity and possible regressions since the change would be way more invasive):
 * There'd be a need for some kind of `socket_context` structure that would keep the socket parameters along with the pointer to the actual socket implementation context (`net_context` for instance for the native sockets) for each socket - hence extra RAM consumption.
 * Additional logic would be needed in each socket call that'd check if the socket was bound already or not, which means extra processing time on each call.
 * Currently the error reporting is pretty obvious - if you run out of `net_context`s for instance, you fail to create a socket. With a "delayed" creation, the error would occur at some later point which might be confusing.
 
Do we really want this? Note that it would impact the native stack only applications as well I believe, ifdef slicing such changes sounds like a nightmare to me. If you're really convinced however we should go this way I might add this to my TODO list for further investigation.

**Comment by pfalcon** [comment]
@rlubos 

> We actually already have is_supported() callback that verifies family/type/protocol combination. The problem is that this does not solve the issue when multiple socket implementations (offloaded or not) support the same set of these parameters.

Oops, I stand corrected. Indeed, it's there. I just remember we had some discussion regarding that with @jukkar, apparently I argued that with a callback, net_socket_register->family isn't needed, as callback can test it itself, and forgot that both were implemented (and missed to check before posting).

> This indeed might've been driven more by our specific use-case

Yes, I understand that, and from that PoV, this PR offers a simple and obvious fix (workaround). But it doesn't scale, as being pointed out. So, if some other party will get another usecase, there may be different, partial adhoc solutions, which need to be maintained going forward. It may be better to think of more general (but still reachable) solution right away.

> but allowing to specify priorities at per socket implementation basis sounds more flexible. I think that for short term solution I'll actually try to add the priorities instead.

Thanks for giving it a try!

> Now as for the "right" way of binding a socket with an implementation/interface by postponing the actual socket creation, I thought of this as well initially, as this sounded the most flexible way from the application point of view. I gave up on the idea however due to several reasons

I fully agree that it would be substantial change and **don't** call it to be done in the context of this PR. Just mentioning if for future planning, e.g. if a usecase comes up when socket implementation should be selected based on destination address, then it makes sense to tie it with the routing table (instead of looking for an adhoc solution).

**Comment by rlubos** [comment]
Closing this in favour of #38739.

**Pull request closed without merging**
