### PR TITLE
[v3.2-branch] mgmt: mcumgr: Fix Bluetooth transport issues

### LINKED ISSUE #51804: [v3.2-branch] Bluetooth: Application with buffer that cannot unref it in disconnect handler leads to advertising issues
**Describe the bug**
This issue has been found with a peripheral zephyr device which supports 1 connection, the application works by receiving BT data and then putting it into a fifo to be processed by a dedicated (non-system) workqueue which will send responses to it and unref the connection, an issue arises however in this application if the remote device disconnects prior to the task having finished, the application attempts to restart advertising using the system workqueue from the disconnection handler. The problem is that because the other task contains references to the connection, restarting advertising fails with error -12. Therefore the application is unable to restart advertising and then is in a dead state. Upping the connection count to 2 does work around this issue, but is not an acceptable solution due to the additional RAM usage (which is essentially wasted).
Some operations can also take longer than others, e.g. a image erase command can take upwards of 5 seconds to process.

**To Reproduce**
mcumgr has this issue

**Expected behavior**
To be able to restart advertising, from the system workqueue, triggered in the disconnect handler

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Commit SHA or Version used: This is apparent in an nRF connect SDK sample application (samples/matter/lock) using the softdevice, but should be reproducible with any application that uses bluetooth, I did not attempt seeing if this issue was present in the zephyr controller but would imagine it would be given that it is caused by the limit of connection references/handles being reached

Copy of https://github.com/zephyrproject-rtos/zephyr/issues/51714 but for v3.2-branch.

### PR DESCRIPTION
**Pull request by nordicjm**
This fixes issues with the Bluetooth SMP transport whereby deadlocks could arise from connection references being held in long-lasting mcumgr command processing functions.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/51714

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
```
../../../../../../../../include/zephyr/mgmt/mcumgr/smp.h:141:26: error: 'struct smp_transport' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
  141 | void smp_rx_clear(struct smp_transport *zst, bool clear_all, void *arg);
```

Missing dependency?

**Comment by stephanosio** [comment]
The PR to main, https://github.com/zephyrproject-rtos/zephyr/pull/51757, has not been merged yet.

**Comment by fabiobaltieri** [comment]
@nordicjm can you address https://github.com/zephyrproject-rtos/zephyr/pull/51644#issuecomment-1298877950 as well while you are at it?

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri what if this is a heavily modified backport, i.e. where a cherry-pick would not apply?

As long as the patch is based on another one, I'd say that it still makes sense to have a reference to it in the commit message, something like "this is a heavily modified version of <short hash>: <description>".

**Review by de-nordic — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
