### PR TITLE
tests: kernel: Add test to verify k_thread_user_mode_enter()

### PR DESCRIPTION
**Pull request by spoorthik**
Test to verify k_thread_user_mode_enter() when usermode is
not enabled or supported by architecture. The thread which calls
k_thread_user_mode_enter() with CONFIG_USERSPACE disabled or
architecture doesn't support usermode, should be marked
as user thread and if it is essential, then it has to be cleared.

Signed-off-by: Spoorthi K <spoorthi.k@intel.com>

### CODE REVIEW

**Comment by spoorthik** [comment]
@AdithyaBaglody @andrewboie: This test cases fails on qemu_x86, minnowboard and freedom_k64f, please refer the console log below. 

Would you please review the test case and let me know if I need to raise a issue for these crashes?

On qemu_x86:
```
starting test - test_user_mode
***** CPU Page Fault (error code 0x00000005)
User thread read address 0x00401248
PDE: 0x027 Present, Writable, User, Execute Enabled
PTE: 0x80000000263 Present, Writable, Supervisor, Execute Disable
Current thread ID = 0x004181e0
eax: 0x000012ad, ebx: 0x004181e0, ecx: 0x00000000, edx: 0x004181e0
esi: 0x00000000, edi: 0x0040efec, ebp: 0x0040efd0, esp: 0x0040dff8
eflags: 0x00000246 cs: 0x002b
call trace:
eip: 0x00006b01
     0x000027bd (0x4181e0)
Fatal fault in thread 0x004181e0! Aborting.
```

On freedom_k64f:
```
starting test - test_user_mode
***** BUS FAULT *****
  Executing thread ID (thread): 0x20002870
  Faulting instruction address:  0x6366
  Precise data bus error
  Address: 0x200004a4
  NXP MPU error, port 3
    Mode: User, Data Address: 0x200004a4
    Type: Read, Master: 0, Regions: 0x8800
Fatal fault in thread 0x20002870! Aborting.
```

On minnowboard:
```
starting test - test_user_mode
***** CPU Page Fault (error code 0x00000005)
User thread read address 0x0010c248
PDE: 0x027 Present, Writable, User, Execute Enabled
PTE: 0x80000000263 Present, Writable, Supervisor, Execute Disable
Current thread ID = 0x001231c0
eax: 0x0010028d, ebx: 0x001231c0, ecx: 0x00000000, edx: 0x001231c0
esi: 0x00000000, edi: 0x00119fec, ebp: 0x00119fd0, esp: 0x00118ff8
eflags: 0x00210246 cs: 0x002b
eip: 0x001057b0
Fatal fault in thread 0x001231c0! Aborting.
```

And passes on qemu_cortex_m3, qemu_nios2, qemu_xtensa, arduino_101, quark_d2000_crb and quark_se_c1000_devboard.

**Comment by ioannisg** [comment]
I am wondering @spoorthik : is the test passing for any board having the ARM MPU?

**Comment by spoorthik** [comment]
@ioannisg : I have checked on freedom_k64f and on sam_e70_xplained. And it fails on both the boards. 

To be specific, call to _is_thread_essential() after entering user mode is causing the crash.

Console log on sam_e70_xplained
```
starting test - test_user_mode
***** MPU FAULT *****
  Executing thread ID (thread): 0x2040323c
  Faulting instruction address:  0x40518e
  Data Access Violation
  Address: 0x2040047c
Fatal fault in thread 0x2040323c! Aborting.
```

**Comment by andrewboie** [comment]
> And passes on qemu_cortex_m3, qemu_nios2, qemu_xtensa, arduino_101, quark_d2000_crb and quark_se_c1000_devboard.

That's because none of those boards enable user mode.

**Comment by ramakrishnapallala** [comment]
@andrewboie what is usage of k_thread_user_mode_enter() for kernel thread (if user space is not enabled)?

does it make sense to move the function under #ifdef CONFIG_USERSPACE? if not how can we test this API in kernel mode?

**Comment by andrewboie** [comment]
> @andrewboie what is usage of k_thread_user_mode_enter() for kernel thread (if user space is not enabled)?

There isn't any use-case

**Comment by spoorthik** [comment]
@andrewboie: The intention of writing the test case is to improve the code coverage of k_thread_user_mode_enter() on native posix. Please help me understand how can we do that.

**Comment by andrewboie** [comment]
> @andrewboie: The intention of writing this test case is to improve the code coverage of k_thread_user_mode_enter() on native posix. Please help me understand how can we do that.

native_posix doesn't support user mode so I don't see this as a particularly productive use of our time.

**Comment by ramakrishnapallala** [comment]
@andrewboie so how we should approach this from the testing point of view, should we leave this function as dead code in case non-userspace enabled platforms?

**Comment by nashif** [comment]
@andrewboie 
> There isn't any use-case other than very crude portability to targets that don't support user mode

then

> native_posix doesn't support user mode so I don't see this as a particularly productive use of our time.

so the API can be called in native_posix, and should address the coverage problem, but placing it in this test project will not work they way you are doing it, the test itself should be run on non-userspace platforms only, i.e only native_posix in this case.

This qualifies as a test, it goes into branches that have not been tested/verified yet.

**Comment by spoorthik** [comment]
@nashif: I have modified the test so that the test can be called by the non-userspace platforms only. Is this what you were expecting? Can you please review.

**Comment by spoorthik** [comment]
Shippable is failing due to unrelated build error, it has nothing to do with the current patch:

```
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h: In function ‘LPUART_GetDataRegisterAddress’:
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h:500:30: error: ‘LPUART_Type {aka struct <anonymous>}’ has no member named ‘data’
     return (uint32_t) & (base->DATA);
                              ^~
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h: In function ‘LPUART_WriteByte’:
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h:602:9: error: ‘LPUART_Type {aka struct <anonymous>}’ has no member named ‘data’
     base->DATA = data;
         ^~
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h: In function ‘LPUART_ReadByte’:
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h:624:21: error: ‘LPUART_Type {aka struct <anonymous>}’ has no member named ‘data’
         return (base->DATA & 0x7F);
                     ^~
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h:628:20: error: ‘LPUART_Type {aka struct <anonymous>}’ has no member named ‘data’
         return base->DATA;
                    ^~
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/ext/hal/nxp/mcux/drivers/imx/./fsl_lpuart.h:633:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
```

**Comment by spoorthik** [comment]
@andrewboie @nashif: Would you please review the changes and let me know what modifications are required for the test?

**Comment by nashif** [comment]
recheck

**Comment by nashif** [comment]
recheck

**Review by nashif — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Pull request merged**
