### PR TITLE
Kconfig.zephyr: check priorities by default

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Final chapter of the build time priority checking series, this PR contains few fixes for the last devices that were failing `build_all` tests and enable build time priority checking by default.

We had this in our internal repo for a while and worked alright, I've hunted down all the failures in the PR and main run and got all them sorted one at a time, now it should be possible to enable this by default and have the CI catch initialization errors automatically.

Dependencies:

- #58312
- #58333
- #59633
- #59634
- #59635
- #60168
- #60169
- #60170
- #60178
- #60221
- #60223
- #60304
- #60338
- #60340
- #60889
  - #60814
  - #60816
  - ~~#60913~~
  - #61095
  - #60982

Push check branch on testing: https://github.com/zephyrproject-rtos/zephyr-testing/tree/vfabio-testing-branch

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
@manuargue this is the last down I have:

```
$ west build -p -b s32z270dc2_rtu0_r52 -T samples/boards/nxp_s32/netc/sample.boards.nxp_s32.netc.psi
$ ./scripts/build/check_init_priorities.py -vv
...
ERROR: /soc/ethernet@74000000/ethernet@74b00000 POST_KERNEL 60 79 < /soc/ethernet@74000000/mdio@74b60000/ethernet-phy POST_KERNEL 80 78
```

that's `ethernet-phy` under `netc` which would imply that `netc` initializes before, but that implication is not correct, I think that the fix is to move `emdio: mdio@74b60000 {` up one level in https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nxp/nxp_s32z27x_r52.dtsi#L607.

If that's correct and you want to open a PR and test it it'd be cool!

**Comment by manuargue** [comment]
> that's `ethernet-phy` under `netc` which would imply that `netc` initializes before, but that implication is not correct, I think that the fix is to move `emdio: mdio@74b60000 {` up one level in https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nxp/nxp_s32z27x_r52.dtsi#L607.
> 
> If that's correct and you want to open a PR and test it it'd be cool!

hi @fabiobaltieri , let me have a look because it may not be so trivial due to the way the HAL does the ethernet controller components initialization.

**Comment by fabiobaltieri** [comment]
> > that's `ethernet-phy` under `netc` which would imply that `netc` initializes before, but that implication is not correct, I think that the fix is to move `emdio: mdio@74b60000 {` up one level in https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nxp/nxp_s32z27x_r52.dtsi#L607.
> > If that's correct and you want to open a PR and test it it'd be cool!
> 
> hi @fabiobaltieri , let me have a look because it may not be so trivial due to the way the HAL does the ethernet controller components initialization.

Hey I don't think we should change how init is done in this case, just the way the peripheral are declared in the tree.

**Comment by fabiobaltieri** [comment]
> Hey I don't think we should change how init is done in this case, just the way the peripheral are declared in the tree.

Actually I was reading it wrong, this may use a priority change, could you check if https://github.com/zephyrproject-rtos/zephyr/pull/60913 makes sense?

**Review by cfriedt — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
