### PR TITLE
scripts: Add flash and debug support using pyOCD on NXP boards

### PR DESCRIPTION
**Pull request by MaureenHelm**
Adds a new debug support script using pyOCD and configures most NXP
boards so they can use it. frdm_kw41z is the one exception because pyOCD
doesn't yet support kw41z. Tested with pyOCD v0.8.0 and the latest
DAPLink firmware for each board.

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@flit, @dleach02

**Review by galak — COMMENTED** [review]
any plans to add pyOCD to sdk?

**Review by galak — CHANGES_REQUESTED** [review]
Looks good, can we document (maybe in the commit message) the new env vars that a user can set:
PYOCD_FLASHTOOL
PYOCD_GDBSERVER

**Comment by MaureenHelm** [comment]
> any plans to add pyOCD to sdk?

Nothing concrete yet, but yes I've thought about it. Also looking into RTOS awareness. There's a PR open to RTOS awareness to pyOCD...thinking about extending it for Zephyr.

> Looks good, can we document (maybe in the commit message) the new env vars that a user can set:
> PYOCD_FLASHTOOL
> PYOCD_GDBSERVER

Will do, thanks.

**Comment by MaureenHelm** [comment]
Updated the commit message and rebased to the latest arm branch

**Review by galak — APPROVED** [review]

**Pull request merged**
