### PR TITLE
Bluetooth: Mark bt_<type>_err_to_str() APIs experimental

### PR DESCRIPTION
**Pull request by rugeGerritsen**
It was pointed out in a future PR that they should have a corresponding experimental Kconfig entry.

See PR #73795.

This updates the APIs added in PR #73826 and PR #74295.

### CODE REVIEW

**Review by alwa-nordic — APPROVED** [review]

**Comment by rugeGerritsen** [comment]
Should I create a corresponding bug entry to ensure this gets merged into the 3.7 release?

**Review by Thalley — COMMENTED** [review]
This looks weird to me. 

Adding experimental is not really a bug, but rather an oversight that can be considered a doc update effectively. 

This PR, however, does much more than marking them experimental. It adds a bunch of new Kconfig options that modify the behavior of the functions. I'd call that an enhancement. 

What I would suggest is to either
1) Only make them as experimental in the documentation (without adding the Kconfig options)
2) Add the Kconfigs with the EXPERIMENTAL but without modifying the behavior of the functions (but still guard the implementations). 

I'm OK with the change overall, but unsure whether this can go into 3.7 as this is technically a feature/API change.

**Review by jhedberg — DISMISSED** [review]

**Comment by rugeGerritsen** [comment]
> This looks weird to me.
> 
> Adding experimental is not really a bug, but rather an oversight that can be considered a doc update effectively.
> 
> This PR, however, does much more than marking them experimental. It adds a bunch of new Kconfig options that modify the behavior of the functions. I'd call that an enhancement.
> 
> What I would suggest is to either
> 
> 1. Only make them as experimental in the documentation (without adding the Kconfig options)
> 2. Add the Kconfigs with the EXPERIMENTAL but without modifying the behavior of the functions (but still guard the implementations).
> 
> I'm OK with the change overall, but unsure whether this can go into 3.7 as this is technically a feature/API change.

Yes, there are several options we can choose from.
What I want to avoid is that users start relying on the return values from these functions that were introduced very recently.

With option 2 you mean the following, right?

```c 
#if defined(CONFIG_BT_HCI_ERR_TO_STR)
const char *bt_hci_err_to_str(uint8_t hci_err);
#end
```

**Review by hermabe — APPROVED** [review]

**Comment by Thalley** [comment]
> > This looks weird to me.
> > Adding experimental is not really a bug, but rather an oversight that can be considered a doc update effectively.
> > This PR, however, does much more than marking them experimental. It adds a bunch of new Kconfig options that modify the behavior of the functions. I'd call that an enhancement.
> > What I would suggest is to either
> > 
> > 1. Only make them as experimental in the documentation (without adding the Kconfig options)
> > 2. Add the Kconfigs with the EXPERIMENTAL but without modifying the behavior of the functions (but still guard the implementations).
> > 
> > I'm OK with the change overall, but unsure whether this can go into 3.7 as this is technically a feature/API change.
> 
> Yes, there are several options we can choose from. What I want to avoid is that users start relying on the return values from these functions that were introduced very recently.
> 
> With option 2 you mean the following, right?
> 
> ```c
> #if defined(CONFIG_BT_HCI_ERR_TO_STR)
> const char *bt_hci_err_to_str(uint8_t hci_err);
> #end
> ```

Almost. We generally only guard the implementations, and not the definitions, so the `#if defined(CONFIG_BT_HCI_ERR_TO_STR)` would be applied the source file(s) rather than the header file(s). 

Based on the other approvals, I can see that I'm outnumbered, so feel free to keep as is (also why I didn't mark this as a change request)

**Comment by rugeGerritsen** [comment]
@Thalley , I believe your suggestion makes more sense. Then customers cannot use the API at all.
I have no strong preference on this one. Returning an empty string seems fine as well

**Comment by alwa-nordic** [comment]
> This PR, however, does much more than marking them experimental. It adds a bunch of new Kconfig options that modify the behavior of the functions. I'd call that an enhancement.

> unsure whether this can go into 3.7 as this is technically a feature/API change.

I consider the changes in this PR as a fixup to the previous PRs. Those PRs forgot the experimental marker, which it should have had, to comply with the Zephyr API lifecycle process. My opinion is that the change is important and small enough to warrant accepting during freeze.

> Add the Kconfigs with the EXPERIMENTAL but without modifying the behavior of the functions (but still guard the implementations).

I think this is an OK option. These are pure functions, so it's easy for users to copy the implementation into their project if we decide to remove or change them. It could pose an upgrade hazard if we change the behavior without changing the type signature of the functions, but since they are documented experimental, we can maybe ignore this.

**Comment by rugeGerritsen** [comment]
> 
> > Add the Kconfigs with the EXPERIMENTAL but without modifying the behavior of the functions (but still guard the implementations).
> 
> I think this is an OK option. These are pure functions, so it's easy for users to copy the implementation into their project if we decide to remove or change them. It could pose an upgrade hazard if we change the behavior without changing the type signature of the functions, but since they are documented experimental, we can maybe ignore this.

In order to proceed with something like https://github.com/zephyrproject-rtos/zephyr/pull/75442, we need to always have a definition of string functions available, unless the samples will be configured to use some wrapper function.

**Comment by alwa-nordic** [comment]
> > > Add the Kconfigs with the EXPERIMENTAL but without modifying the behavior of the functions (but still guard the implementations).
> > 
> > 
> > I think this is an OK option. These are pure functions, so it's easy for users to copy the implementation into their project if we decide to remove or change them. It could pose an upgrade hazard if we change the behavior without changing the type signature of the functions, but since they are documented experimental, we can maybe ignore this.
> 
> In order to proceed with something like #75442, we need to always have a definition of string functions available, unless the samples will be configured to use some wrapper function.

I quoted the wrong option :sweat_smile:. I meant to say that I'm OK the the following option:

> Only make them as experimental in the documentation (without adding the Kconfig options)

I.e. change this PR to purely a documentation fixup.

**Review by jori-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
