### PR TITLE
net: context: tcp: set the pkt appdatalen info when sending packets

### PR DESCRIPTION
**Pull request by simple2017**
when received an ACK, we need the pkt appdatalen info to calculate seq which determine these packets should be released.

### CODE REVIEW

**Comment by pfalcon** [comment]
@simple2017 : Thanks for resubmitting this from gerrit! Perhaps you could fill in your name in Github profile, so it was easier to recognize you ;-). 

@jukkar , @tbursztyka : So, do you guys agree with @nashif's RFC that all patches should be submitted against master? Otherwise, we'll keeping having issues with stray commits like this.

**Comment by jukkar** [comment]
> So, do you guys agree with @nashif's RFC that all patches should be submitted against master? Otherwise, we'll keeping having issues with stray commits like this.

This is submitted against master which is fine, we all agree on this.

**Review by jukkar — CHANGES_REQUESTED** [review]
The patch itself looks ok. I would like to get the commit message a bit better, perhaps something like this (feel free to edit the message as needed and remember not to exceed the max line length in commit msg)

net: context: Set TCP app data len when sending packet

When we send TCP data segment, we need to set the length of the application data by calling net_pkt_set_appdatalen(). This is done so that sequence number can be properly advanced when we receive ACK to that pending packet.

**Comment by pfalcon** [comment]
@jukkar :

> This is submitted against master which is fine, we all agree on this.

Yes, just seems to be submitted from net branch against master, why a couple of extra commits. Hopefully net branch will be fully flushed to master.

**Comment by simple2017** [comment]
Thanks all, @pfalcon @jukkar  Maybe I should close this pull request and follow your advice to reopen a pull request against the master branch. Because I found some extra commits included in my single commit when using net branch. In the new pull request I will modify the commit message format errors and patch-check problem.

**Comment by jukkar** [comment]
> Yes, just seems to be submitted from net branch against master, why a couple of extra commits. Hopefully net branch will be fully flushed to master.

Those extra commits are really annoying, but I think we can safely ignore them at this point.

**Comment by jukkar** [comment]
> Thanks all, @pfalcon @jukkar Maybe I should close this pull request and follow your advice to reopen a pull request against the master branch. Because I found some extra commits included in my single commit when using net branch. In the new pull request I will modify the commit message format errors and patch-check problem.

No need to close this PR. Just fix the commit message issues and whatever is needed to make Shippable happy. So please re-submit this PR with fixes.

**Comment by simple2017** [comment]
@jukkar OK, I got it, thanks a lot.

**Comment by pfalcon** [comment]
@simple2017 : Please squash your 2 commits together (but use the most recent commit message of course).

**Comment by pfalcon** [comment]
Ok, based on IRC discussion with @jukkar that it would be nice to understand effect of this change better (i.e. know what it fixes and what doesn't), I played with it today. I first tried to do fault injection on packet receive path, verifying that it works as expected for HTTP client type load. Then my idea was that maybe it would work for HTTP server style too, by dropping peer's ACKs, thus triggering Zephyr to do rexmits, and trigger bad things. But that didn't really work.

So, I went for fault inject on send path too, and that immediately showed the effect of the change. So, without this change, with send pkt drop I saw with a test server in MicroPython:

~~~
Connected to 192.0.2.1.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.0 200 OK

Hello #0 from MicroPython!
~~~

At which point no further data were received, connection just hanged, and Wireshark showed rexmits storm, but all in vain.

With this patch, the output was below, as expected from the server. For reference, my test patch is at https://github.com/pfalcon/zephyr/commits/net-pkt-fault-inject

~~~
Connected to 192.0.2.1.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.0 200 OK

Hello #0 from MicroPython!
HTTP/1.0 200 OK

Hello #1 from MicroPython!
HTTP/1.0 200 OK

Hello #2 from MicroPython!
HTTP/1.0 200 OK

Hello #3 from MicroPython!
HTTP/1.0 200 OK

Hello #4 from MicroPython!
HTTP/1.0 200 OK

Hello #5 from MicroPython!
HTTP/1.0 200 OK

Hello #6 from MicroPython!
HTTP/1.0 200 OK

Hello #7 from MicroPython!
HTTP/1.0 200 OK

Hello #8 from MicroPython!
HTTP/1.0 200 OK

Hello #9 from MicroPython!
HTTP/1.0 200 OK

Hello #10 from MicroPython!
HTTP/1.0 200 OK

Hello #11 from MicroPython!
HTTP/1.0 200 OK

Hello #12 from MicroPython!
HTTP/1.0 200 OK

Hello #13 from MicroPython!
HTTP/1.0 200 OK

Hello #14 from MicroPython!
HTTP/1.0 200 OK

Hello #15 from MicroPython!
HTTP/1.0 200 OK

Hello #16 from MicroPython!
HTTP/1.0 200 OK

Hello #17 from MicroPython!
HTTP/1.0 200 OK

Hello #18 from MicroPython!
HTTP/1.0 200 OK

Hello #19 from MicroPython!
Connection closed by foreign host.
~~~

**Comment by pfalcon** [comment]
Nest test - problem I repeated with HTTP client connection to http://archive.ubuntu.com - expectedly, doesn't help, as it's client (recv) application.

**Comment by pfalcon** [comment]
Final test I wanted to perform. It's my understanding that @jukkar wondered whether this change would improve TCP behavior of https://gerrit.zephyrproject.org/r/#/c/13077/ . Though I may miss something, and he meant another test. Anyway, I tried it, and well, for it patch doesn't have any visible effect, after few packets, processing still deadlocks.

Anyway, I see that @simple2017 has squashed 2 commits together, so this should be ready to merge, and make pretty good improvements already.

**Review by jukkar — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]

**Comment by pfalcon** [comment]
@simple2017 : Great work, congrats on your first patch merged! ;-) Hope it will be easier next time, looking forward to new IP stack fixes that you found.

**Pull request merged**
