### PR TITLE
tests: lib: cmsis_dsp: fix incorrect testcase number in report

### PR DESCRIPTION
**Pull request by enjiamai**
The testcase failure numbers of tests/lib/cmsis_dsp is not correct
in the twister's report. A recent twister overhaul reveals this
problem. This is because some tests cannot be parsed well in twister,
related to how it was written. Ex. existing ifdef/else macro made it
hard to get all the correct testcases.

The current solution is to deal with those tests individually in the
testcase.yaml file by listing the target running testcases explicitly.

Signed-off-by: Enjia Mai <enjia.mai@intel.com>

### CODE REVIEW

**Review by stephanosio — DISMISSED** [review]

**Comment by enjiamai** [comment]
Thanks! @stephanosio :)

**Comment by JordanYates** [comment]
Is manually listing 1500 test cases really the best way to solve this?
I can imagine these lists will quickly be outdated if any more tests are added, its not obvious that they should be updated.

**Comment by enjiamai** [comment]
> Is manually listing 1500 test cases really the best way to solve this? I can imagine these lists will quickly be outdated if any more tests are added, its not obvious that they should be updated.

No, this is not a good way, I think it's temporary solution until we can make twister parse all the tests correctly, or change the code to adapt twister. It is not easy for twister to parse the source code correctly without considering the kernel config.

**Comment by enjiamai** [comment]
Excuse me, add missing test cases which in CONFIG_CMSIS_DSP_FLOAT16 for CONFIG_FPU=n  scenario.

**Comment by enjiamai** [comment]
It seem like the build failure of rpi_pico board is due to CI. I saw this build failure also without a change.

**Comment by enjiamai** [comment]
Close this PR because there is a fix for it. See https://github.com/zephyrproject-rtos/zephyr/pull/46278 please

**Pull request closed without merging**
