### PR TITLE
STM32: Convert boards to devicetree for USB pins configuration

### PR DESCRIPTION
**Pull request by erwango**
Based on https://github.com/zephyrproject-rtos/zephyr/pull/29403

### CODE REVIEW

**Comment by avisconti** [comment]
@erwango 
LGTM at a quick glance.
I can also test it out on sensortile_box, but not this week.

**Review by gmarull — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by avisconti** [comment]
> @erwango
> LGTM at a quick glance.
> I can also test it out on sensortile_box, but not this week.

@erwango 
Tested on sensortile_box board. It communicates well with minicom thru USB

**Review by avisconti — APPROVED** [review]

**Comment by carlescufi** [comment]
@erwango please rebase

**Comment by erwango** [comment]
@carlescufi rebase done, this is now ready to merge. Give me a go and I'll remove the BK temp patch.

**Comment by galak** [comment]
> @carlescufi rebase done, this is now ready to merge. Give me a go and I'll remove the BK temp patch.

@erwango remove the bk patch and I'll merge.

**Comment by erwango** [comment]
> @erwango remove the bk patch and I'll merge.

@galak done.
Interestingly, BK was not restarted. Not sure if it's a feature, but this is nice.

**Comment by galak** [comment]
Merged as was passing CI.

**Comment by galak** [comment]
Noticed a few USB cases that might have been missed:

```
boards/arm/b_l072z_lrwan1/pinmux.c:     {STM32_PIN_PA11, STM32L0_PINMUX_FUNC_PA11_USB_DM},
boards/arm/b_l072z_lrwan1/pinmux.c:     {STM32_PIN_PA12, STM32L0_PINMUX_FUNC_PA12_USB_DP},
boards/arm/nucleo_g431rb/pinmux.c:      {STM32_PIN_PA11, STM32G4X_PINMUX_FUNC_PA11_USB_DM},
boards/arm/nucleo_g431rb/pinmux.c:      {STM32_PIN_PA12, STM32G4X_PINMUX_FUNC_PA12_USB_DP},
boards/arm/nucleo_g474re/pinmux.c:      {STM32_PIN_PA11, STM32G4X_PINMUX_FUNC_PA11_USB_DM},
boards/arm/nucleo_g474re/pinmux.c:      {STM32_PIN_PA12, STM32G4X_PINMUX_FUNC_PA12_USB_DP},
```

**Comment by erwango** [comment]
> Noticed a few USB cases that might have been missed:

Yes, I'm taking care of the G4 and having a look to the lrwan.

**Pull request merged**
