### PR TITLE
kernel: avoid SCA warning "extra semicolon ignored"

### PR DESCRIPTION
**Pull request by romkell**
The marco _POLL_EVENT causes static code analysis warnings due to a remaining semicolon in the case _POLL_EVENT is empty.

./zephyr/include/zephyr/kernel.h:1746:13: warning #381-D: extra ";" ignored
./zephyr/include/zephyr/kernel.h:2958:13: warning #381-D: extra ";" ignored
./zephyr/include/zephyr/kernel.h:4268:13: warning #381-D: extra ";" ignored
./zephyr/include/zephyr/kernel.h:4708:13: warning #381-D: extra ";" ignored

Move the semicolon into the macro and remove the semicolons behind the macros where used in the struct declarations. Rename to _DECL_POLL_EVENT for better recognition.

### CODE REVIEW

**Comment by nashif** [comment]
suggestion for commit message and in general when dealing with issues reported by tools:

> kernel: avoid SCA warning "extra semicolon ignored"

need to avoid such commit messages, the title should describe the change within the context of the code, i.e. `kernel: poll: remove extra semicolons in macros` or whatever. 

Then in the commit message explain why the change is needed and not what the tool is reporting.

At the end of the commit message, you can mention how the issue was found, i..e 'Found using XX tool'

**Comment by peter-mitsis** [comment]
The technical aspect of the work looks good. Clean up the commit message as per the suggestion from @nashif, and you will get a +1 from me.

**Review by cfriedt — COMMENTED** [review]
Technically, `_[A-Z]` is a reserved prefix 🤷‍♂️. I would be happy with double underscore and lowercase. Otherwise, prefix with Z and it can be a part of The Great Renaming.

**Comment by romkell** [comment]
> Technically, `_[A-Z]` is a reserved prefix 🤷‍♂️. I would be happy with double underscore and lowercase. Otherwise, prefix with Z and it can be a part of The Great Renaming.

According to ISO/IEC 9899:201x chapter 7.1.3:

```
"...identifiers which are always reserved either for any use or for use as file
scope identifiers.
- All identifiers that begin with an underscore and either an uppercase letter or another
underscore are always reserved for any use."
```
So `__DECL_POLL_EVENT` would not work either. I am fine with `Z_DECL_POLL_EVENT` if that is what we do meanwhile before The Great Renaming.

**Comment by nashif** [comment]
> Technically, `_[A-Z]` is a reserved prefix 🤷‍♂️. I would be happy with double underscore and lowercase. Otherwise, prefix with Z and it can be a part of The Great Renaming.

that is feature creep, just leave it as is, there is no needed to change the prefix, this needs to be addressed somewhere else and is not what this PR is trying to do.

**Review by peter-mitsis — APPROVED** [review]

**Comment by romkell** [comment]
> that is feature creep, just leave it as is, there is no need to change the prefix, this needs to be addressed somewhere else and is not what this PR is trying to do.

Feature creep is technically correct, but it was me who started renaming to `_DECL_POLL_EVENT` for better understanding IMO.
Since the change is local (even though in a header) and does not spread to other files, I feel an extra branch / PR for such changes is over-management. Is it really undesired to do minor rewording together with "technical" changes?

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
