### PR TITLE
arm: soc: nRF52: Add workaround for incorrect RESETREAS bits (errata 136)

### PR DESCRIPTION
**Pull request by durub**
This workaround fixes the issue that, after pin reset, RESETREAS bits other
than RESETPIN might also be set.

The workaround was added to both nRF52832 and nRF52840 SoCs.

Signed-off-by: Thiago Silveira <thiago@exati.com.br>

### CODE REVIEW

**Comment by carlescufi** [comment]
@anangl FYI

**Review by cvinayak — COMMENTED** [review]
If this is what is derived from MDK, this looks good to me.

**Comment by durub** [comment]
It is derived from MDK. Each function was extracted from its' SoC file.

**Review by cvinayak — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
I will approve this but we need to update to a more recent version of the MDK to get this workaround and the new nomenclature

**Comment by carlescufi** [comment]
@nashif I think this is ready for merging

**Pull request merged**
