### PR TITLE
scripts: dts: improve error message on compatible type error

### PR DESCRIPTION
**Pull request by mbolivar**
Print the offending value and its type.

### CODE REVIEW

**Review by ulfalizer — APPROVED** [review]
Could print `compatible` directly too, instead of the type. Think some other places do that.

**Comment by mbolivar** [comment]
> Could print `compatible` directly too, instead of the type. Think some other places do that.

I'm printing both the compatible and its type

**Comment by ulfalizer** [comment]
> > Could print `compatible` directly too, instead of the type. Think some other places do that.
> 
> I'm printing both the compatible and its type

Oh, sorry, didn't notice. That's even better then.

**Review by carlescufi — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by mbolivar** [comment]
I'm a bit surprised this got merged during freeze, but I guess it's a small patch; thanks!

**Pull request merged**
