### PR TITLE
Fix spelling in EEPROM driver sample

### PR DESCRIPTION
**Pull request by bossssie**
Fix spelling error from EERPOM to EEPROM

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]
Thank you.

**Review by de-nordic — APPROVED** [review]
Looks OK, but it looked funnier before.

**Comment by henrikbrixandersen** [comment]
You need a signed-off-by line in your commit message.

**Comment by henrikbrixandersen** [comment]
@bossssie Please fix the commit message to include the signed-off-by line so this can be merged.

**Comment by bossssie** [comment]
I tried changing it, i'm not really experienced yet with Git so I can't seem to change it

**Comment by henrikbrixandersen** [comment]
> I tried changing it, i'm not really experienced yet with Git so I can't seem to change it

Please see https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow (bullet 15) for instructions.

**Comment by henrikbrixandersen** [comment]
> I tried changing it, i'm not really experienced yet with Git so I can't seem to change it

Please reach out on Zephyr Discord if you need further help with this.

**Comment by henrikbrixandersen** [comment]
Superseeded by #43517.

**Pull request closed without merging**
