### PR TITLE
preparation for RV64 support

### PR DESCRIPTION
**Pull request by npitre**
This contains generic changes for supporting both RV32 and RV64 on Zephyr.

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
doc changes are OK, though renaming the ``boards/riscv32/`` folder to ``boards/riscv/`` will break external links to those board documents :(

**Comment by npitre** [comment]
On Wed, 24 Jul 2019, David Kinder wrote:

> doc changes are OK, though renaming the ``boards/riscv32/`` folder to ``boards/riscv/`` will break external links to those board documents :(

A redirect on the website for that directory could be set.

**Comment by dbkinder** [comment]
Yes we have a mechanism for generating redirects.  Take a look in the doc/conf.py around line 300.  You can add an update to conf.py in this PR to add the redirects for the (I think 5) renamed .rst files as explained there.

**Review by nategraff-sifive — APPROVED** [review]
:tada: Looks great to me, modulo the Mi-V errors in shippable!

**Pull request merged**
