### PR TITLE
drivers: ethernet: remove sections.ld for SOC_SERIES_STM32H5X

### LINKED ISSUE #66309: nucleo_h563zi: SRAM3 cannot be used and memory corruption when using SRAM1 and 2
I'm trying to relocate a buffer in SRAM3 on my nucleo_h563zi.

I've followed : https://docs.zephyrproject.org/latest/kernel/code-relocation.html

1. CONFIG_CODE_DATA_RELOCATION=y in prj.conf.
2. zephyr_code_relocate(FILES src/firmware.c LOCATION SRAM3) in cmakelists
3. firmware.c only containing: uint8_t firmware_image[10] = {0,1,2,3,4,5,6,7,8,9};

**Expected behavior**
Compilation successfull, buffer stored in SRAM3 and being able to read it.

**Impact**
I'm trying to setup firmware update on the dev board so I need to store the fw image on SRAM3 as it is the only one big enough. Later I'm gonna use an external flash to buffer the image.

**Logs and console output**
linker_zephyr_pre0.cmd:252 cannot move location counter backwards (from 2009bce0 to 20050000)

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain Zephyr SDK
 - Commit : ed610400bcb74338d25e4b29f948709efe12f3a3

**Additional context**
It's compiling correctly if I set SRAM1 or 2. 

The problem then is that if I declare for example my buffer like this at compile time :
uint8_t firmware_image[10] = {0,1,2,3,4,5,6,7,8,9};
When I read it then the output is: 
[00:00:30.005,000] <inf> main: fw[0] = 00
[00:00:30.005,000] <inf> main: fw[1] = 01
[00:00:30.005,000] <inf> main: fw[2] = 02
[00:00:30.005,000] <inf> main: fw[3] = 03
[00:00:30.005,000] <inf> main: fw[4] = 00
[00:00:30.005,000] <inf> main: fw[5] = 80
[00:00:30.005,000] <inf> main: fw[6] = E1
[00:00:30.005,000] <inf> main: fw[7] = A4
[00:00:30.005,000] <inf> main: fw[8] = F9
[00:00:30.005,000] <inf> main: fw[9] = 32

If I set it at runtime:
for (uint32_t i = 0U; i <10; i++) {
        firmware_image[i] = i;
}

then when reading it:
[00:00:30.005,000] <inf> main: fw[0] = 00
[00:00:30.005,000] <inf> main: fw[1] = 01
[00:00:30.005,000] <inf> main: fw[2] = 02
[00:00:30.005,000] <inf> main: fw[3] = 03
[00:00:30.005,000] <inf> main: fw[4] = 04
[00:00:30.005,000] <inf> main: fw[5] = 05
[00:00:30.005,000] <inf> main: fw[6] = 06
[00:00:30.005,000] <inf> main: fw[7] = 07
[00:00:30.005,000] <inf> main: fw[8] = 08
[00:00:30.005,000] <inf> main: fw[9] = 09

So 2 problems : 
SRAM3 not compiling
memory corrupted if initialised at compile time

### PR DESCRIPTION
**Pull request by Desvauxm-st**
remove section(".eth_stm32_desc") and
section(".eth_stm32_desc") for SOC_SERIES_STM32H5X

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/66309

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
I think following file is now useless: 
https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/arm/st_stm32/stm32h5/sections.ld

Please remove it (and usage in CMakeLists.txt)

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Comment by christiansandberg** [comment]
How does this change affect performance of Ethernet on H5? If I understand it correctly the buffers are placed in SRAM3 since Ethernet MAC should have fast bus multiplex with SRAM3.

image

**Comment by erwango** [comment]
> How does this change affect performance of Ethernet on H5? If I understand it correctly the buffers are placed in SRAM3 since Ethernet MAC should have fast bus multiplex with SRAM3.
> 
> image

No Impact on performance. This change is just a clean up of implementation leftover (see https://github.com/zephyrproject-rtos/zephyr/issues/66309#issuecomment-1851985074)

**Comment by christiansandberg** [comment]
I think there was a good reason for linking those buffers to SRAM3 instead of being implicitly placed (usually in SRAM1). But it would be good if STM could comment on the benefits.

**Pull request merged**
