### PR TITLE
Add timer20 device for stm32g4

### PR DESCRIPTION
**Pull request by pdietl**
Signed-off-by: Pete Dietl <petedietl@gmail.com>

### CODE REVIEW

**Review by theotherjimmy — APPROVED** [review]

**Review by ABOSTM — CHANGES_REQUESTED** [review]
@pdietl Thanks for this Pull Request.
You should add a body to you commit message to fix CI Compliance check.
Also addition of TIM20 should be moved to another file (see inline comment)

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by pdietl** [comment]
@theotherjimmy Can I has reapprove plz? :)

**Review by theotherjimmy — APPROVED** [review]
Yeah, sure.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
Even if the CI issue doesn't seem related indeed, things are always faster when CI is passed.
Would you mind rebasing and push again to see if the issue disappear ?

**Comment by Jeepgoing** [comment]
Request merge this to [https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-branch](https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-branch)

**Comment by erwango** [comment]
> Request merge this to https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-branch

@cfriedt, @nashif what is the policy wrt backports on LTS?
We usually limit backports to bug fixes. Is that the same for LTS? 
I've checked [related documentation](https://docs.zephyrproject.org/latest/development_process/release_process.html?highlight=lts#long-term-support-and-maintenance) but it might not be sufficiently clear about this specific part.

**Comment by cfriedt** [comment]
> > Request merge this to https://github.com/zephyrproject-rtos/zephyr/tree/v2.7-branch
> 
> @cfriedt, @nashif what is the policy wrt backports on LTS?
> We usually limit backports to bug fixes. Is that the same for LTS? 
> I've checked [related documentation](https://docs.zephyrproject.org/latest/development_process/release_process.html?highlight=lts#long-term-support-and-maintenance) but it might not be sufficiently clear about this specific part.
> 

Yes, that's correct. Afaik, all backports need to go through the CRB which should happen on Tuesday.

**Comment by erwango** [comment]
Thanks @cfriedt , so in current case where PR add a device description, no backport possible, is that correct ?

**Comment by cfriedt** [comment]
> Thanks @cfriedt , so in current case where PR add a device description, no backport possible, is that correct ?

@nashif might know some additional details. I see what you mean though. If there are no code changes, no DTS changes, only DTS additions..

**Pull request merged**
