### PR TITLE
dma: ace: Add ace gpdma driver

### PR DESCRIPTION
**Pull request by ceolin**
Add ace gpdma driver.

Co-authored-by: Adrian Bonislawski <adrian.bonislawski@intel.com>
Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Review by teburd — DISMISSED** [review]
There's some stuff we can clean up on this and soc.c, but this gets us the driver at least to work towards that

**Review by teburd — DISMISSED** [review]

**Comment by ceolin** [comment]
> can we just unify both cavs and ace drivers please and have just driver with differences controlled by feature kconfigs? The drivers look awfully similar.

Yep, I can do it. I just think we should have it merged or remove the reference ASAP. The way it is now the tree is incosistent.

**Comment by ceolin** [comment]
v2:

 - Merge cAVS and ACE gpdma drivers.

**Review by nashif — APPROVED** [review]

**Review by andyross — APPROVED** [review]
I very much like the second patch.  Though maybe squashing these two together would be clearer to see in the tree, vs. adding new files then deleting them one patch later?  Maybe you guys could rock-paper-scissors to see who gets the Author: tag?

**Review by teburd — APPROVED** [review]

**Pull request merged**
