### PR TITLE
drivers: entropy: stm32: Convert to device tree based configuration

### PR DESCRIPTION
**Pull request by erwango**
Define rng node on strm32 series supported by entropy driver.
Update driver to query configuration from dt.
Update platforms that used to enable entropy by default
Add 3 platforms to extend driver coverage
Update entropy sample to pass in CI

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Can you see if #24006 works w/regards to the regex YAML change.

**Comment by erwango** [comment]
> Can you see if #24006 works w/regards to the regex YAML change.

Tested ok and better indeed.
Removing my related commit

**Comment by galak** [comment]
Did you intend to have the commit for 'stm32f413 is a derivate of stm32f412' in this PR?

**Review by galak — APPROVED** [review]

**Comment by erwango** [comment]
> Did you intend to have the commit for 'stm32f413 is a derivate of stm32f412' in this PR?

Yes

**Comment by galak** [comment]
I changed the driver to use DT_INST_LABEL(0) instead of CONFIG_ENTROPY_NAME

**Comment by erwango** [comment]
> I changed the driver to use DT_INST_LABEL(0) instead of CONFIG_ENTROPY_NAME

Will have some tests.

**Comment by erwango** [comment]
> I changed the driver to use DT_INST_LABEL(0) instead of CONFIG_ENTROPY_NAME

Tested ok

**Pull request merged**
