### PR TITLE
linker: correct linker script _flash_used calculation

### PR DESCRIPTION
**Pull request by tejlmand**
Linker scripts contains a `.last_section` section that is placed in rom region as NOLOAD for the purpose of retrieve the actual number of bytes contained in the image. See d85efe0b10f1f8ed4b854717f994062a4bbffe26

However, a previous section may cause the location counter to be incremented for alignment purposes. This can result in the size of the image to be 0x10FA but location counter to be 0x1100 because it has been aligned for next section placement.

By removing NOLOAD and write 0xE015 (end of last section) to the section we ensure that data is written after alignment of location counter, and thereby forces the image size to be in sync with the location counter.

Using 0xE015 also serves as identifier that end of last section is present.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

--------

*Note:* this is labelled `bug` as it fixes a bug that has been identified and reported downstream of Zephyr, but no bug has been filed directly against Zephyr project.

### CODE REVIEW

**Comment by nordicjm** [comment]
CC @joerchan possible TF-M size issue?

**Comment by tejlmand** [comment]
> I am getting `elftools.common.exceptions.DWARFError: Expected supported DWARF version. Got '5'` when trying to run these commands on the current zephyr main branch and this PR.

@joerchan  i'm not able to get this error when running `ninja ram_report` or `ninja rom_report` on zephyr main with this PR.
Tried several samples under `samples/tfm_integration/`.

Could you be a bit more specific as to when this happens / the sample for which you see this error.
We did have some issues with dwarf-5 and the linker, but those are expected to be solved here: #50117

**Comment by joerchan** [comment]
@tejlmand `ram_report` works, `tfm_ram_report` does not.

**Comment by nordicjm** [comment]
> @tejlmand ram_report works, tfm_ram_report does not.

Sounds like tfm is not pulling in the build flags from zephyr

**Comment by tejlmand** [comment]
> > @tejlmand ram_report works, tfm_ram_report does not.
> 
> Sounds like tfm is not pulling in the build flags from zephyr

tfm is not pulling anything, we must pass everything to TF-M build.
Ref: https://github.com/zephyrproject-rtos/zephyr/blob/9ac6779b2dd006cffe93684cb794ba267e03e775/modules/trusted-firmware-m/CMakeLists.txt#L279-L291

**Review by nordicjm — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Should `soc/riscv/riscv-privilege/andes_v5/ae350/linker.ld` be fixed as well?

**Comment by tejlmand** [comment]
> Should `soc/riscv/riscv-privilege/andes_v5/ae350/linker.ld` be fixed as well?

@fabiobaltieri Thanks for leading my attention to this file.
Fixed.

> That has also a referencde to to .last_section. I also can't quite grasp the scope of this feature, it's only for linker scripts of aarch32, arm64 and riscv, should the Kconfig options be in the same context?

As this is a bug fix, I prefer not to touch other platmorms for now, so Kconfig is updated to reflect this dependency.

In addition an enhancement issue has been created: #50840
so we can consider aligning all linker templates so they support the `.last_section`.

**Comment by fabiobaltieri** [comment]
@microbuilder can you have a look into this? Last chance to get it in 3.2.

**Review by nordicjm — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@tejlmand, I have deleted the 3.2 milestone as we are too close to the release. Please tag this for a future release.

**Review by microbuilder — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
