### PR TITLE
NPM1300 GPIO updated for new silicon revision

### PR DESCRIPTION
**Pull request by aasinclair**
Status readback has been added in the latest silicon revision on the NPM1300. 

The GPIO driver has been updated to add support for port_get_raw and port_toggle_bits,
and an associated button has been added to the shield overlay.

### CODE REVIEW

**Comment by aasinclair** [comment]
Ping @gmarull

**Review by gmarull — APPROVED** [review]

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
How will these changes work on older silicon? Do we need to support multiple revisions? Can the revision be determined at run-time?

**Comment by aasinclair** [comment]
> How will these changes work on older silicon? Do we need to support multiple revisions? Can the revision be determined at run-time?

@henrikbrixandersen The early silicon was only for development and will not be publicly released, only the new revision will be sold.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Not sure why @erwango is assigned to this PR...

**Pull request merged**
