### PR TITLE
Usb: Implement SET_INTERFACE and add missing definitions

### PR DESCRIPTION
**Pull request by finikorg**

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
please look at  #716 and  b53c893

**Comment by finikorg** [comment]
Rebased

**Comment by finikorg** [comment]
Rebased

**Comment by finikorg** [comment]
Rebased

**Comment by finikorg** [comment]
Added USB Configuration change callback parameter

**Comment by jfischer-phytec-iot** [comment]
So any interest in co-operation? Look at #716 (d96b106, b3577c5) again, there everything should be prepared for CDC-ECM but RNDIS is unfortunately missing. Composite support is well working, at last on Kinetis (like K64F). DW driver is unfortunately limited to endpoints and not so well tested.
And is it a good solution to add class specific stuff to usb_common.h?

**Comment by finikorg** [comment]
@jfischer-phytec-iot Hi, I like your proposals in general. I will rebase my code on top of your code when it is upstream.

**Comment by finikorg** [comment]
If you make your approach to coexist with existing method I would port also hci_usb and wpanusb gadgets if this is needed

**Comment by finikorg** [comment]
Rebased

**Comment by finikorg** [comment]
@jfischer-phytec-iot @andyross Gentlemen what is the status with USB pull requests? Are they stall? I am going to add support for RNDIS and ECM and need those definitions in my pull request or I can use @jfischer-phytec-iot method if it is accepted

**Comment by nashif** [comment]
can you please give some details on the dependencies of the PRs and who wants what PR to be applied first? It is confusing right now, too many USB related changes.

**Comment by finikorg** [comment]
@nashif my current PR does not break existing code, just adds definitions. It should be safe to apply them. I tested PR #852 and enablind DMA mode breaks my code but deselecting DMA works, I believe patches like 5754e89eabb5785ff8b734a3bf9c7c46a1c6131d are useful.

**Review by nashif — APPROVED** [review]

**Pull request merged**
