### PR TITLE
net: lwm2m: Fix LwM2M pause and resume

### PR DESCRIPTION
**Pull request by jheiskan81**
Fixed unstable thread state read for detect engine thread
state.
Fixed engine missing socket context add.

This fix a case when lwm2m_pause() is called at any state.

Signed-off-by: Juha Heiskanen <juha.heiskanen@nordicsemi.no>

### CODE REVIEW

**Comment by jheiskan81** [comment]
@rlubos @SeppoTakalo Please review this fix.

**Comment by jheiskan81** [comment]
@juhaylinen Can you review and test at your branch.

**Review by SeppoTakalo — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Comment by juhaylinen** [comment]
@jheiskan81 I tested the PR and it fixes the issue I was seeing earlier on my branch

**Comment by stephanosio** [comment]
Rebased to fix CI failure

**Review by rlubos — DISMISSED** [review]

**Review by SeppoTakalo — DISMISSED** [review]

**Comment by jheiskan81** [comment]
rebased with main branch

**Comment by jheiskan81** [comment]
resolved confict and rebased.

**Review by SeppoTakalo — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
