### PR TITLE
doc: Add secure sockets documentation

### PR DESCRIPTION
**Pull request by rlubos**
Add documentation for secure sockets subsystem.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
@pfalcon FYI, this PR should satisfy final request from #9926

**Review by nashif — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]
Thanks!

**Review by dbkinder — CHANGES_REQUESTED** [review]

**Comment by rlubos** [comment]
@dbkinder Thank you for the feedback, I've applied the fixes and reworked the options documentation to reference doxygen instead.

**Review by dbkinder — APPROVED** [review]
+1 for doc changes, thanks!

**Pull request merged**
