### PR TITLE
usb : class: hid: Fix fault due to unaligned access

### LINKED ISSUE #11266: intel_s1000: usb_hid: load/store alignment exception
When USB HID class is initialized in Intel S1000 SoC/CRB, a load/store exception occurs due to the assignment below in function `usb_set_hid_report_size` in file `subsys/usb/class/hid/core.c`

`hid_cfg.if0_hid.subdesc[0].wDescriptorLength =
                sys_cpu_to_le16(report_desc_size);`

### PR DESCRIPTION
**Pull request by SavinayDharmappa**
patch fix fault due to unaligned access while setting hid
report size on xtensa platform.

Fixes #11266

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

### CODE REVIEW

**Review by rgundi — COMMENTED** [review]
LGTM. @finikorg @jfischer-phytec-iot Do you think this UNALIGNED_PUT should be used only for Xtensa platform? If it is generic, we can as well take out the __packed from the structure.

**Comment by finikorg** [comment]
@rgundi we cannot make descriptor table not packed. It is returned via USB requests.

**Comment by rgundi** [comment]
> @rgundi we cannot make descriptor table not packed. It is returned via USB requests.

Thanks. So, should this UNALIGNED_PUT be used only for Xtensa platform?

**Comment by jfischer-phytec-iot** [comment]
@SavinayDharmappa :confused:, what is about #8495?

**Comment by finikorg** [comment]
> > @rgundi we cannot make descriptor table not packed. It is returned via USB requests.
> 
> Thanks. So, should this UNALIGNED_PUT be used only for Xtensa platform?

I think it is OK to have it for all platforms, maybe only it is better to use instead sys_put_le16().

**Comment by jfischer-phytec-iot** [comment]
@SavinayDharmappa Do you like to take the changes from #8495 over?

**Comment by nashif** [comment]
remove "subsys: " from the commit messages...

**Comment by nashif** [comment]
> @SavinayDharmappa Do you like to take the changes from #8495 over?

@SavinayDharmappa  we should do that.

**Comment by SavinayDharmappa** [comment]
@nashif  @jfischer-phytec-iot  #8495 have similar changes for other class of usb other than hid. I am not sure how would it affect the system.

**Comment by finikorg** [comment]
> @nashif @jfischer-phytec-iot #8495 have similar changes for other class of usb other than hid. I am not sure how would it affect the system.

Most of those are not needed since they use PUT_UNALIGNED with 1 byte. The only other change needed is modification of wTotalLength IIRC. So please use sys_put_le16() for those 2 changes.

**Comment by jfischer-phytec-iot** [comment]
>Most of those are not needed since they use PUT_UNALIGNED with 1 byte. The only other change needed is modification of wTotalLength IIRC. So please use sys_put_le16() for those 2 changes.

Let's merge it and discuss further in #8495.

**Review by jfischer-no — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
