### PR TITLE
Remove remnants of k_mem_block usage

### PR DESCRIPTION
**Pull request by peter-mitsis**
Usage of k_mem_pool was phased out a few years ago. However, there still remained a few references here and there. These commits remove what should hopefully be those last few remnants.

### CODE REVIEW

**Comment by peter-mitsis** [comment]
Hmm. The debug/percepio module references k_mem_block. Digging into this.

**Review by nashif — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]
drivers: usb LGTM

**Review by jhedberg — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by jhedberg** [comment]
@andyross this still requires your approval (as the assignee) before it can be merged

**Review by andyross — APPROVED** [review]
Yes please

**Pull request merged**
