### PR TITLE
samples:fs_sample: add required meta info for twister

### PR DESCRIPTION
**Pull request by hakehuang**
in harness_fixure definition, type and regex is must have

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]

**Comment by hakehuang** [comment]
@kabeljan @Laczen @nashif please help to review thanks

**Comment by Laczen** [comment]
@hakehuang, sorry but twister is not my forte. I am removing the review request.

**Comment by hakehuang** [comment]
@kabeljan @nashif  please help to take a look, thanks.

**Comment by hakehuang** [comment]
@kabeljan @nashif please help to take a look, thanks.

**Comment by kabeljan** [comment]
Hi,
I think I was mistakenly mentioned.

I think you have to mention @kartben instead of @kabeljan .

**Comment by hakehuang** [comment]
@kartben please take a look

**Review by kartben — APPROVED** [review]

**Pull request merged**
