### PR TITLE
implement parallel mode in TLE9104

### PR DESCRIPTION
**Pull request by benediktibk**
Implement the parallel mode in the powertrain switch TLE9104. This allows that OUT1 and OUT2 are controlled together, as well as OUT3 and OUT4.

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
Perhaps add an entry in the release notes for this?

**Comment by benediktibk** [comment]
Force pushed an amend for the release notes.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@ifyall , can you help review

**Comment by ifyall** [comment]
@mmahadevan108 My team and I don't have any experience with this part. I looked at the changes, but without sitting down and studying the datasheet, I can't say if the code changes are correct. I can't do that at this time.

Thanks for reaching out, sorry I couldn't help.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
