### PR TITLE
tests bsim bt audio: Increase execution timeout

### LINKED ISSUE #80907: tests/bsim/bluetooth/audio/ tend to timeout in CI
**Describe the bug**
tests/bsim/bluetooth/audio/test_scripts/bap_broadcast_audio_assistant_incorrect_code.sh
tests/bsim/bluetooth/audio/test_scripts/bap_unicast_audio.sh
tests/bsim/bluetooth/audio/test_scripts/bap_unicast_audio_acl_disconnect.sh
Tend to timeout in CI (real time timeout which kills simulations which otherwise seem stuck)
This is just due to a too tight timeout, which depending on the CI runners load/speed can trigger.

**To Reproduce**
Difficult to reproduce locally.
But the timeouts can be seen for example in https://github.com/zephyrproject-rtos/zephyr/actions/runs/11666290372/job/32515451164?pr=80788#step:13:2693

**Expected behavior**
Test not timing out in CI

**Impact**
PRs CI failing at random, confused developers, and developers retrigering CI (wasting developer and CI time).
Overall developers not trusting CI

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11666290372/job/32515451164?pr=80788#step:13:2693

**Environment (please complete the following information):**

 - OS: CI (Ubuntu 22.04)
 - Toolchain (e.g Zephyr SDK, ...): Host gcc 12(?)
 - Commit SHA or Version used: Main as of now.

### PR DESCRIPTION
**Pull request by aescolar**
These tests have been seen failing in CI due to the real time execution timeout. Let's increase it so it does not happen.

Sits on top of the hotfix:
* https://github.com/zephyrproject-rtos/zephyr/pull/80894

Otherwise CI will fail due to that other bug

Fixes #80907

### CODE REVIEW

**Comment by Thalley** [comment]
@aescolar why not remove the extra commit so we can approve this right away?

**Comment by aescolar** [comment]
> @aescolar why not remove the extra commit so we can approve this right away?

The extra commit is needed as otherwise CI will fail due to the issue that other hotfix is fixing.
You can approve it right away, and we can merge it right away either before or after the other hotfix (git will drop the other commit if went it before)

**Comment by Thalley** [comment]
> > @aescolar why not remove the extra commit so we can approve this right away?
> 
> The extra commit is needed as otherwise CI will fail due to the issue that other hotfix is fixing. You can approve it right away, and we can merge it right away either before or after the other hotfix (git will drop the other commit if went it before)

But the rebase will require a new re-review, right? 
Re-triggering CI after https://github.com/zephyrproject-rtos/zephyr/pull/80894 is merged would require fewer steps :)

**Comment by aescolar** [comment]
> But the rebase will require a new re-review, right?

There is no need for rebase. git properly realizes the commit is the same and ignores it. This PR can be merged as is even after https://github.com/zephyrproject-rtos/zephyr/pull/80894 would have been merged.

> We also don't want to accidentally merge this before https://github.com/zephyrproject-rtos/zephyr/pull/80894 either

Why not? :), both need merging anyhow.

**Comment by Thalley** [comment]
> Why not? :), both need merging anyhow.

Why not close the other then? 

It's just messy to have the same commits in (now 3) PRs.

**Review by Thalley — APPROVED** [review]
The first commit really shouldn't be in this PR, but the timeout changes are fine

**Comment by mmahadevan108** [comment]
@aescolar , the first commit is not related to this bug fix.

**Review by cvinayak — APPROVED** [review]
This PR is needed as CI fails during my mornings these days :-)  like https://github.com/zephyrproject-rtos/zephyr/actions/runs/11697983422/job/32577543076?pr=80733

First commit is already in the main now, rebase merge should take care of it.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
Merging as hotfix.

**Pull request merged**
