### PR TITLE
bluetooth: id: fix uninitialized RPA for non-default identities

### PR DESCRIPTION
**Pull request by kapi-no**
This change fixes uninitialized RPA values for advertising sets of non-default Bluetooth identities. The regression has been introduced in the following commit:

https://github.com/zephyrproject-rtos/zephyr/commit/8d6b206064c915316245616a718ae29eb157a717

The follow-up fix for the default Bluetooth identity has been introduced in a separate commit:

https://github.com/zephyrproject-rtos/zephyr/commit/88c20b9cddf0bd5e5d6c163611b2563f9266be6f

Non-default Bluetooth identities can be loaded from the Settings subsystem. In this case, RPAs of related advertising sets to these identities are left uninitialized as the bt_id_create() function context is not executed. As a result, the RPA is not created for advertising sets of non-default Bluetooth identities, and the advertising is started with the 00:00:00:00:00:00 address.

### CODE REVIEW

**Review by theob-pro — CHANGES_REQUESTED** [review]
Fix is great. Just add a test to reproduce the issue please.

**Comment by kapi-no** [comment]
Rebased my code on top of the current main branch. The unaffected BabbleSim test started to fail in my PR

**Comment by kapi-no** [comment]
It seems that BabbleSim tests still fail because of the following test:

tests/bsim/bluetooth/host/l2cap/send_on_connect/tests_scripts/l2cap.sh

Can someone take a look at it? Or maybe even there is a PR fixing it? I haven't touched the test so it seems strange that it is failing

**Comment by theob-pro** [comment]
> It seems that BabbleSim tests still fail because of the following test:
> 
> tests/bsim/bluetooth/host/l2cap/send_on_connect/tests_scripts/l2cap.sh
> 
> Can someone take a look at it? Or maybe there is a PR fixing it? I haven't touched the test so it seems strange that it is failing

It will be fixed when this PR is merged: https://github.com/zephyrproject-rtos/zephyr/pull/64549

**Review by theob-pro — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Pull request merged**
