### PR TITLE
civetweb: remove obsolete code

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
OBSOLETE, replaced by: https://github.com/zephyrproject-rtos/zephyr/pull/46746

### CODE REVIEW

**Comment by stephanosio** [comment]
FYI @Nukersson

**Comment by Nukersson** [comment]
BTW Does somebody working on lean Websocket server solution specific for Zephyr?

**Comment by gmarull** [comment]
In general, I think non-core modules should not even be part of Zephyr `west.yaml`. They can be maintained outside of Zephyr and applications can pull them as needed. Other examples would be e.g. LVGL.

**Review by gmarull — APPROVED** [review]

**Comment by Nukersson** [comment]
> In general, I think non-core modules should not even be part of Zephyr `west.yaml`. They can be maintained outside of Zephyr and applications can pull them as needed. Other examples would be e.g. LVGL.

This approach sounds good to me, cause there is too much ping-pong with integrations steps needed to be done by Zephyr developers. It would be great if newlibc would cover more and more functionality and stay stable, than samples with civetweb etc. could be done. The only question: How could none-core modules be added as none-core samples to Zephyr for sake of showcase etc.?

**Comment by mbolivar-nordic** [comment]
Closing this for now given the discussion at the TSC which said we would prefer to deprecate rather than outright remove for v3.1. If nobody steps up to maintain this by the time 3.2 is getting close to release, though, we are going to remove this module.

**Pull request closed without merging**
