### PR TITLE
tests: drivers: spi: Add negative test cases

### PR DESCRIPTION
**Pull request by nordic-segl**
Extend test coverage by adding tests that check invalid use of the SPI API.

### CODE REVIEW

**Comment by nordic-segl** [comment]
This test is based on code added in https://github.com/zephyrproject-rtos/zephyr/pull/67994

**Comment by nordic-segl** [comment]
@nordic-krch: Could You take a look?

**Comment by nordic-segl** [comment]
I run our CI on this PR - spi_error_cases is passing on both nRF targets.

**Review by nordic-bami — APPROVED** [review]

**Review by nordic-piks — APPROVED** [review]

**Review by nordic-piks — APPROVED** [review]

**Comment by nordic-segl** [comment]
Kind reminder - please find some time to do the review.

**Comment by nordic-segl** [comment]
[rebased on top of main - 6a42ede43b53ceffddeaa814b4bd99284c25240d]

**Comment by nordic-segl** [comment]
It works in CI
08:35:50  INFO    - 1/2 nrf54l15pdk/nrf54l15/cpuapp tests/drivers/spi/spi_error_cases/drivers.spi.spi_error_cases PASSED (device: 1057717622, 6.688s)
08:35:50  INFO    - 2/2 nrf52840dk/nrf52840       tests/drivers/spi/spi_error_cases/drivers.spi.spi_error_cases PASSED (device: 683921412, 8.419s)

**Review by tbursztyka — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Pull request merged**
