### PR TITLE
boards: arduino_nano_33_ble: Correct certain PWM LED settings

### PR DESCRIPTION
**Pull request by anangl**
This is a follow-up to commit f4a0ddd8afa1c2b99a30dcd940f34304ce678c93.

According to the schematic, the LED connected to the P1.09 pin is
active high. Therefore, the PWM1 instance that is configured to drive
the LED should not use the "nordic,invert" property.

Since the yellow LED and the SCK line of spi2 use the same pin
(P0.13), they cannot be used together. Consequently, the pin
should not be assigned to the same PWM instance as other pins
that drive LEDs, as the limitation of usage would apply to the
whole PWM instance (it acquires all the pins assigned to it on
initialization of the PWM driver, regardless of whether the PWM
signal is eventually generated on particular outputs or not).

Use a separate PWM instance (disabled by default) for driving
the yellow LED.

### CODE REVIEW

**Comment by anangl** [comment]
@benjaminbjornsson Could you test these changes? I don't have the arduino_nano_33_ble board.

**Comment by benjaminbjornsson** [comment]
@anangl Of course, I'll test it tomorrow. And thank you for correcting my mistakes.

**Comment by benjaminbjornsson** [comment]
@anangl Yellow light is off as it should when running rgb_led. However, I'd like to see the user LED turned on at boot to indicate that the board is powered. Otherwise it looks good to me.

**Comment by anangl** [comment]
> I'd like to see the user LED turned on at boot to indicate that the board is powered. Otherwise it looks good to me.

@benjaminbjornsson Then the LED needs to be turned on explicitly, for example, in the [initialization routine](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/arduino_nano_33_ble/board.c#L10-L22) for this board, similarly to how the I2C pull-ups are activated.

**Review by jfischer-no — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
