### PR TITLE
drivers: flash: introduce on-chip flash driver for TI CC13xx/CC26xx

### PR DESCRIPTION
**Pull request by pepe2k**
This PR includes a basic driver for built-in flash on the Texas Intruments SimpleLink CC13xx/CC26xx SoC series and corresponding DTS bindings. The driver makes use of driverlib HAL from TI's SDK and was tested on two LaunchXL development boards with CC1352R and CC2652R SoCs:

- CC1352R1 LaunchXL
- CC26x2R1 LaunchXL

Tests were done using:

- flash shell sample (`samples/drivers/flash_shell`)
- littlefs filesystem sample (`samples/subsys/fs/littlefs`)*
- MCUboot (`bootloader/mcuboot/boot/zephyr`)*

\* additional changes in DTS for the boards were required (partitions table) and are not part of this changeset (will be introduced later)

This PR depends on: https://github.com/zephyrproject-rtos/hal_ti/pull/37

Some additional information about the implementation:

1. TI's Technical Reference Manual for CC13x2 and CC26x2 points out that "An individual 64-bit word can be programmed to change bits 1 to 0" but it seems this 'alignment' requirement is handled internally by the ROM function and thus `write-block-size` is set to `1`.

2. Interrupts, VIMS and line buffers are disabled during flash content update (write or erase) and restored afterwards as recommended by TI.

3. Only RAM to flash write is supported (source of data to be written to flash can't point to flash).

4. The driver doesn't take care of flash sector protection disable as that functionality is handled by CCFG. Write or erase requests which refer to a protected area will fail.

### CODE REVIEW

**Review by mbolivar-nordic — COMMENTED** [review]
For bisectability, I think the commit adding the bindings should be moved before the commit adding the driver which uses them.

**Comment by pepe2k** [comment]
@mbolivar-nordic 
> For bisectability, I think the commit adding the bindings should be moved before the commit adding the driver which uses them.

OK, should I reorder and force-push with a rebase on "main" then?

Thanks,
Piotr

**Review by cfriedt — DISMISSED** [review]
LGTM - please get approval from @nvlsianpu as well

**Review by mbolivar-nordic — COMMENTED** [review]
DT portions LGTM

**Comment by pepe2k** [comment]
Rebased on current `main`, no new changes were introduced.

**Review by cfriedt — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]
blindly re-approving

**Pull request merged**
