### PR TITLE
libc/minimal: add support for gmtime and its reverse "timegm"

### PR DESCRIPTION
**Pull request by pabigot**
This PR replaces #17003, using the standard name `gmtime` for conversion between `struct tm` and `time_t`.  The `gmtime` function is added to minimal libc, and a sys library supporting time-related operations is added for the reverse function compatible with the GLIBC `timegm` extension.

This adds the POSIX `gmtime_r` instead of the C `gmtime_s` because the former is more common and, in fact, is currently used in stm32 drivers.

### CODE REVIEW

**Comment by pabigot** [comment]
I've updated the code so the words "public domain" are in a separate comment from the one that providesd the proper `SPDX-License-Identifier`.  This seems to be the best we do in this situation since SPDX [doesn't support structured acknowledgement](https://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files) of public domain origins without a registered dedication, and that's way too much work. 

> Found the following issues, please fix and resubmit:
> 
> ## License issues
> In most cases you do not need to do anything here, especially if the files
> reported below are going into ext/ and if license was approved for inclusion
> into ext/ already. Fix any missing license/copyright issues. The license
> exception if a JFYI for the maintainers and can be overriden when merging the
> pull request.
> 
> * lib/libc/minimal/source/time/gmtime.c is not apache-2.0 licensed: public-domain
> * lib/libc/minimal/source/time/gmtime.c has non-permissive license: public-domain
> * lib/os/timeutil.c is not apache-2.0 licensed: public-domain
> * lib/os/timeutil.c has non-permissive license: public-domain

**Comment by pabigot** [comment]
I've decoupled this from the POSIX subsystem, hopefully reducing any impediments to it being processed towards a merge.

There's nothing I can do about the license check failure, which seems to be based on the words "public domain" appearing in the file outside the license block.

**Review by pfalcon — APPROVED** [review]
Looks good, thanks for refactoring. (Can't vouch that there's nothing to improve here or something won't need a change later, but definitely looks good for the initial in, and surely useful).

**Review by carlescufi — APPROVED** [review]
This looks good and addresses all the discussion points that we have raised priorly

**Pull request merged**
