### PR TITLE
sanitycheck: record benchmark results

### PR DESCRIPTION
**Pull request by nashif**
Add a method to capture benchmark data and save it as a CSV file for
later prociessing. This will help with tracking benchmark data or any
data generated by test applications.

### CODE REVIEW

**Comment by marc-hb** [comment]
Can't find anything wrong the implementation details, however I don't know what is the purpose of this file and classes so I can't say much. Maybe this is a good opportunity to add a couple pydocs?

**Comment by marc-hb** [comment]
Wow, the codecov disco ball just crashed the party... 20 days after the last code push which makes it hilariously more [bogus](https://github.com/codecov/codecov-bash/issues/83) than ever.
@nashif this had been disabled for some time, right?

**Comment by mbolivar** [comment]
```
/usr/bin/ld: /home/mbolivar/zephyr/zephyr/sanity-out/qemu_x86_64/tests/benchmarks/timing_info/benchmark.timing.default_kernel/zephyr/arch/arch/x86_64/core/xuk-stub32.o: in function `cstart':
xuk-stub32.c:(.text+0x20e): undefined reference to `__stack_chk_fail'
```

**Comment by nashif** [comment]
added to overhaul PR.

**Pull request closed without merging**
