### PR TITLE
BLE Mesh stack could be compiled with C++ compiler

### LINKED ISSUE #11940: Ble mesh stack not compatible with c++
To @jhedberg 
If I include BLE mesh stack into project, it is not possible to compile with c++ compiler.

Header files of BLE Stack are not equiped with extern "C".

Header files must be equiped with macros.
#ifdef __cplusplus
extern "C"{
#endif

#ifdef __cplusplus
}
#endif

### PR DESCRIPTION
**Pull request by rokobert**
Add preprocessor directive for C++ compatibility.

Fixes #11940

### CODE REVIEW

**Comment by jhedberg** [comment]
@rokobert looks generally ok, but could you please squash the commits into a single one - there's no need to split these up one per mesh header file. Also fix the commit message to start with "Bluetooth: Mesh: Add header file support for C++", include at least a one-line message body (could be what you now have in the PR description), and also add a Signed-off-by line (it'll be auto-generated when you pass -s to git commit).

**Comment by carlescufi** [comment]
@rokobert thanks for the PR. To add to what @jhedberg already explained in detail, there is a page with additional information here: 
https://docs.zephyrproject.org/latest/contribute/contribute_guidelines.html#commit-guidelines

**Comment by jhedberg** [comment]
@rokobert there was no need to open a new PR (#11966) for the requested changes - all you needed to do is to push --force to the branch you used for this PR. In the future please do that instead of opening new PRs. I'll close this one to avoid confusion.

**Comment by rokobert** [comment]
I'm sorry for that. I'm quite new to github colaboration.

Regards,
Robert

V V sob., 8. dec. 2018 ob 10:59 je oseba Johan Hedberg <
notifications@github.com> napisala:

**Pull request closed without merging**
