### PR TITLE
dts: arm/arm64: remove DTS 'label' property requirement from gic and …

### PR DESCRIPTION
**Pull request by galak**
…timer

The armv8 timer, arm gic, and arm gic-v3-its don't use or need the devicetree
label property.  Update the dts bindings to not require it and remove setting of
the label property in dts files.

Signed-off-by: Kumar Gala <galak@kernel.org>

### CODE REVIEW

**Review by carlocaione — DISMISSED** [review]
LGTM

**Comment by galak** [comment]
@povergoing looks like the xen platform is missing a <board>.yaml.  Is this on purpose?

**Comment by povergoing** [comment]
> @povergoing looks like the xen platform is missing a .yaml. Is this on purpose?

Umm, apparently not no purpose. But xen platform is under development, we will add it soon

**Review by povergoing — DISMISSED** [review]

**Comment by galak** [comment]
> Umm, apparently not no purpose. But xen platform is under development, we will add it soon

This is a problem as CI will not pass for this PR because they are missing.

**Comment by povergoing** [comment]
> > Umm, apparently not no purpose. But xen platform is under development, we will add it soon
> 
> This is a problem as CI will not pass for this PR because they are missing.

How could I fix for it? I push a commit on your `dts-remove-label-req` branch or create another PR?

**Review by SgrrZhf — DISMISSED** [review]

**Review by luca-fancellu — DISMISSED** [review]

**Comment by galak** [comment]
rebased to pull in xen board/dts fixes from https://github.com/zephyrproject-rtos/zephyr/pull/46506

**Review by carlocaione — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by povergoing — APPROVED** [review]

**Pull request merged**
