### PR TITLE
kernel: Bring back object tracking

### LINKED ISSUE #40119: OBJECT_TRACING for kernel objects
Unfortunately, the object tracing for kernel objects was dropped from version 2.5 to 2.6. 

Our (Lauterbach) debuggers provide a Zephyr awareness, that allows to list and inspect threads and kernel objects. We used the linked list created by CONFIG_OBJECT_TRACING to show tables of created objects, e.g. semaphores or mutexes. Since Zephyr version 2.6, this linked list is no longer configurable, which makes it impossible for debuggers to find and display created objects.

It would be great to get the linked list back in the kernel objects, e.g. like it was in k_mutex of 2.5:
https://github.com/zephyrproject-rtos/zephyr/blob/8be935fe5cda14db37549446e2d571b485cddf0e/include/kernel.h#L3087

### PR DESCRIPTION
**Pull request by edersondisouza**
~~[Still missing some documentation comments]~~

When CONFIG_TRACING_OBJECT_TRACKING is enabled, the kernel will keep
lists of some objects (detailed below), so that debuggers or other tools
can keep track of them.

The lists of objects are:

struct k_timer *_track_list_k_timer;
struct k_mem_slab *_track_list_k_mem_slab;
struct k_sem *_track_list_k_sem;
struct k_mutex *_track_list_k_mutex;
struct k_stack *_track_list_k_stack;
struct k_msgq *_track_list_k_msgq;
struct k_mbox *_track_list_k_mbox;
struct k_pipe *_track_list_k_pipe;
struct k_queue *_track_list_k_queue;

Note that while CONFIG_TRACING is needed, one can always use
CONFIG_TRACE_NONE=y. Also, tracking will only be done for objects that
are also being traced (so, to prevent tracking of some type of object,
such as k_timer, just make CONFIG_TRACING_TIMER=n).

Some simple "sanity checking" tests are also added in this patch.

Fixes #40119

Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>

### CODE REVIEW

**Comment by tleksell-pe** [comment]
Great work, I like the idea that this can be run in parallel with the other tracing cores. 

I'm thinking that we could achieve a slightly neater design which allows separate tracing/tracking configurations (and object tracking without CONFIG_TRACING) if the tracing/tracking enable/disable is managed in the SYS_PORT_TRACING_X macros themselves. That is, instead of "disabling" the SYS_PORT_TRACING_X macro as a whole if CONFIG_TRACING isn't set, we could do something similar to this:

      #define SYS_PORT_TRACING_OBJ_INIT(obj_type, obj, ...) \
         do { \
            #if defined(CONFIG_TRACING)
            SYS_PORT_TRACING_TYPE_MASK(obj_type, \
               _SYS_PORT_TRACING_OBJ_INIT(obj_type)(obj, ##__VA_ARGS__)); \
            #endif

            #if defined(TRACING_OBJECT_TRACKING)
            SYS_PORT_TRACKING_TYPE_MASK(obj_type, \
               _SYS_PORT_TRACKING_OBJ_INIT(obj_type)(obj, ##__VA_ARGS__)); \
            #endif
      } while (false)

This might not be strictly necessary but let me know what you think, with both tracing and tracking disabled this would become the same as

      #define SYS_PORT_TRACING_OBJ_INIT(obj_type, obj, ...) do { } while (false)

**Comment by edersondisouza** [comment]
Hi @tleksell-pe 

My main concern with this idea is that then we are effectively "hiding" tracking behind tracing. I wanted to preserve the idea that "object tracking comes from tracing", so making it depend on `CONFIG_TRACING` made sense to me. After all, tracking happens (for dynamically instantiated objects) inside `SYS_PORT_TRACING_OBJ_INIT`.

Any thoughts?

**Comment by edersondisouza** [comment]
v2: Added some bits of documentation.

**Comment by tleksell-pe** [comment]
@edersondisouza Good point, for this implementation I've considered the following design alternatives (other than the one proposed by this implementation)

1. Make tracking another tracing core implementation. While this solution is tempting it would not allow tracing and tracking in parallel and still requires the TRACKING_FIELD object link injection, or we would break external systems that rely on this kind of linking (e.g. Lauterbach OS awareness for Zephyr).
2. Make a separate tracking system independent of the tracing system but with a similar design. Not necessarily a good alternative, this might be a step back and litters the Zephyr kernel source with more hook macros.

All this considered, I agree with this implementation. While tracking does not have to stem from `SYS_PORT_TRACING_OBJ_INIT` (see design alternative 2), tracking and tracing are closely related. The alternative designs are interesting but they come with their own problems.

@edersondisouza have you tested this implementation with Lauterbach OS awareness for Zephyr?

**Comment by edersondisouza** [comment]
@tleksell-pe About testing with Lauterbach OS awareness, not really. As I didn't reuse previous API entry points literally, I'd guess things wouldn't work out of the box, maybe some tweaks would be necessary.

**Comment by nashif** [comment]
@rdienstbeck FYI

**Comment by edersondisouza** [comment]
Removed draft status as "pre-review" was OK and it pass all checks now.

**Review by tleksell-pe — APPROVED** [review]
It seems that this change works as intended with respect to Lauterbach Zephyr awareness (#40119), great work on bringing this back @edersondisouza

**Comment by rdienstbeck** [comment]
Hi all,
As already mentioned in #40119, I implemented it and tested it in our debugger. It is exactly what we need. Many thanks for this! A already tested this approach with our Zephyr Awareness, see attached picture.
It's now part of CONFIG_TRACING, which also offers a lot of options (and additional code) for tracing, while it is not exactly for tracing but only for keeping a list of objects. Me, personally, I'd put it to kernel debugging options rather than to tracing, but I'll leave the positioning of the option up to you Zephyr experts.
mutex
..

**Review by dcpleung — APPROVED** [review]

**Comment by nashif** [comment]
@edersondisouza  Can you please add some documentation, beside including the doxygen data, i.e. what is this for, some example usage, etc.

**Comment by edersondisouza** [comment]
@nashif Sure, will work on that!

**Comment by edersondisouza** [comment]
v3: More docs - @nashif please, let me know if the updated patch covers your asking or if I'm still missing some bits.

**Review by nashif — APPROVED** [review]

**Pull request merged**
