### PR TITLE
util.h: Add log2ceil function

### PR DESCRIPTION
**Pull request by oyvindronningstad**
Using __builtin_clz() and friends.

This is a function that I have found useful here and there, but has been missing from Zephyr AFAICT, so this is my proposal. Parameter and return types can be discussed. I can add tests if desired, just tell me where.

### CODE REVIEW

**Review by cfriedt — CHANGES_REQUESTED** [review]
@oyvindronningstad - funny that you've made this PR today, since there was a bit of discourse from @JordanYates & I on the same topic.

Personally, I think Jordan's approach is the correct one.
* provide a macro as the implementation with C11 Generics
* macro can use `__builtin_clz()`, etc, as it is compile-time const
* if necessary / desired, create a static inline wrapper that simply calls the macro

See https://github.com/zephyrproject-rtos/zephyr/pull/53583#issuecomment-1374708668

Likely the macro should be relocated to `sys/util.h` or `sys/util_macro.h`.  FWIU, Zephyr is still does not officially C11 (for generics), but it is already present in `cbprintf.h`, and all of our toolchains already support C11.

**Comment by oyvindronningstad** [comment]
@cfriedt Ok, so you're proposing adding a LOG2CEIL in the style of that LOG2? Probably makes sense to add it in #53405, or what do you think?

**Comment by cfriedt** [comment]
> @cfriedt Ok, so you're proposing adding a LOG2CEIL in the style of that LOG2? Probably makes sense to add it in #53405, or what do you think?
> 
> Funny timing indeed :)

I could add it to #53405 if you like, but I would much rather you update your PR. We're a couple of days away from feature freeze from what I understand, and it's unlikely that anything other than v3.3 features and bugfixes will get merged soon, so we could revisit this after the release. Does that work for you?

**Comment by cfriedt** [comment]
> @cfriedt Ok, so you're proposing adding a LOG2CEIL in the style of that LOG2? Probably makes sense to add it in #53405, or what do you think?
> 
> Funny timing indeed :)

Sure - I can add it to #53405 - I'll credit you with it in the commit message and add some testing too.

**Comment by oyvindronningstad** [comment]
Will be added in #53405

**Pull request closed without merging**
