### PR TITLE
samples: drivers: uart: echo_bot: Add support for mec15xxevb_assy6853 board

### PR DESCRIPTION
**Pull request by ambranaam**
The  "echo_bot" sample didn't work on the "mec15xxevb_assy6853" board.

I identified three problems:

- The serial ISR callback function "serial_cb()" never returns.
- The board goes to a deep sleep state after a short moment. In this mode the UARTs are powered down and do no longer work.
- The "uart_bot" requires the shell UART to be enabled/defined, which was not the case for the "mec15xxevb_assy6853" board.

With all these fixes the "echo_bot" example is working well on my "mec15xxevb_assy6853" board.

Please find commits with fixes for all three problems.

### CODE REVIEW

**Comment by dcpleung** [comment]
Please update the commit messages according to the guideline here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

Also, remove the merge commits.

**Comment by ambranaam** [comment]
> Please update the commit messages according to the guideline here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

Done.

**Review by dcpleung — CHANGES_REQUESTED** [review]
Please update the commit messages according to the guideline here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

Also, remove the merge commits.

**Comment by ambranaam** [comment]
> Please update the commit messages according to the guideline here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines
> 
> Also, remove the merge commits.

Done.

**Review by dcpleung — COMMENTED** [review]
Could you rebase to see if that clears out the CI errors?

**Comment by ambranaam** [comment]
> Could you rebase to see if that clears out the CI errors?

Done.

**Review by dcpleung — APPROVED** [review]

**Pull request closed without merging**
