### PR TITLE
stm32: dt-bindings: fix AFIO_MAPR bit pos

### PR DESCRIPTION
**Pull request by mkolchurin**
according to RM0008 position of bit SPI3_REMAP is 28. Also test it on STM32F105VCT6

Signed-off-by: Maxim Kolchurin maxim.kolchurin@gmail.com

### CODE REVIEW

**Review by erwango — DISMISSED** [review]

**Review by ABOSTM — COMMENTED** [review]
@mkolchurin thanks for this Pull Request.
I agree with this change.
By the way could you also change  
* CAN2 --> bit 22
* ETH --> bit 21

**Review by FRASTM — DISMISSED** [review]

**Review by erwango — DISMISSED** [review]

**Comment by erwango** [comment]
@mkolchurin Please fix compliance issue reported in failing checks:
```
author email (Maxim Kolchurin <maxim.kolchurin@gmail.com>) needs to match one of the signed-off-by entries.
```
Hint: `git commit --amend --author="John Doe <john@doe.org>"`

**Review by erwango — DISMISSED** [review]

**Comment by erwango** [comment]
Seems that sign-off-by misses the <> around the email.

**Review by FRASTM — DISMISSED** [review]

**Comment by erwango** [comment]
@mkolchurin ping

**Comment by mbolivar-nordic** [comment]
Needs a rebase. @erwango could you please take another look when that is done?

**Review by erwango — DISMISSED** [review]

**Review by erwango — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
