### PR TITLE
Use Zephyr SDK 0.16.4

### PR DESCRIPTION
**Pull request by dbaluta**
This series updates the CI to use the CI Docker image v0.26.6 and the Zephyr SDK 0.16.4

- This pulls in toolchain for imx8ulp board.

### CODE REVIEW

**Comment by ycsin** [comment]
how about https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/develop/toolchains/zephyr_sdk.rst ?

**Comment by dbaluta** [comment]
> how about https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/develop/toolchains/zephyr_sdk.rst ?

Good catch. Fixed.

**Review by iuliana-prodan — APPROVED** [review]

**Review by LaurentiuM1234 — APPROVED** [review]

**Review by stephanosio — CHANGES_REQUESTED** [review]
Blocking until the CI image v0.26.6 is cached in the AMI.

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
CI infrastructure has been updated to use the new AMI with the Docker image v0.26.6 cached. Merging.

**Pull request merged**
