### PR TITLE
Update TFM overview.rst

### PR DESCRIPTION
**Pull request by butok**
Refresh TFM overview:
- Update TFM v1.4 to current v1.8
- Delete the "Audit log" service which was removed from TFM.

### CODE REVIEW

**Comment by kartben** [comment]
Thanks! Looks like you will want to remove the merge commit from your PR, make sure that the commit is signed off, and commit message/description following contributing guidelines https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

**Comment by butok** [comment]
Thank you. 
I will close the PR, and will try it later with a reformatted commit message.

**Comment by kartben** [comment]
That's not necessary, you could also amend your commits and just push force to your branch. In fact, it's the preferred approach :)

**Comment by kartben** [comment]
That's not necessary, you could also amend your commits and just push force to your branch. In fact, it's the preferred approach :)

**Comment by butok** [comment]
Thank you for the suggestion.

**Pull request closed without merging**
