### PR TITLE
soc: arm: stm32l0: Add PM support

### PR DESCRIPTION
**Pull request by abxy**
Enable power management using deep-sleep and existing LPTIM timer driver
STM32L0 series SoCs.

Signed-off-by: Alexander Mihajlovic <a@abxy.se>

### CODE REVIEW

**Comment by ycsin** [comment]
You might want to take a look at #35987

**Comment by erwango** [comment]
@abxy Thanks for contributing this ! What would be great is to enable PM on an in tree board, so we can get this build/tested in CI. Would you be able to add this as well (aim would be to be able to run `tests/subsys/pm/power_mgmt_soc`)?

**Comment by erwango** [comment]
> You might want to take a look at #35987

Right! Thanks @ycsin for reminding this PR.
@abxy can you have a check on #35987 ?

**Comment by abxy** [comment]
Thanks for the pointer! I'll test #35987 for my use case. That PR seems like a better base than mine either way.

**Comment by abxy** [comment]
Closing in favor of #35987

**Pull request closed without merging**
