### PR TITLE
stm32f4_disco: Fix user button polarity

### LINKED ISSUE #30224: stm32f4_disco: User button press is inverted
**Describe the bug**

The User button is inverted and reads 0 when pressed and 1 when released.

The [schematic for all 4 revisions of this board](https://www.st.com/en/evaluation-tools/stm32f4discovery.html) clearly shows that the button is pulled down by external resistor instead of up and a button press overrides the pull-down resistor.

**To Reproduce**

Check for `samples/basic/button`. The LED should lit up when the button is not pressed for this board.

**Expected behavior**

A non-inverted User button that when pressed reads 1

**Impact**

Minor annoyance. Needs to override the configuration in overlay DTS.

**Logs and console output**

Should be straightforward without logs.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: GCC ARM Embedded Toolchain
 - Commit SHA or Version used: Latest master.

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by dogtopus**
Fixes #30224

### CODE REVIEW

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by erwango** [comment]
@dogtopus CI is failing due to incomplete commit message.

It should looks like:
```
<path>: <component>: Title

Commit description.

Signed-off-by: <name> <email>
```

Cf https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for this contribution!

In order to pass automated checks, please fix commit message.

**Comment by dogtopus** [comment]
Sorry. Can't make this work because the DCO conflicts with my current privacy setup.

**Pull request closed without merging**
