### PR TITLE
Revert changes to gen_idt build that cause compilation issues

### PR DESCRIPTION
**Pull request by nashif**
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/47)

### CODE REVIEW

**Comment by galak** [comment]
What was the build issue, can you open a JIRA for it?

**Comment by pfalcon** [comment]
I noticed the issues after that change too. But I wouldn't haste with just reverting it, instead would ask if @galak would want to investigate them. In my case, I got reports that gen_idt executable wasn't available - apparently, in outdir/. Instead, it was built inside Zephyr tree, in scripts/gen_idt, like this:

~~~
zephyr/scripts/gen_idt$ ls -l
total 132
-rwxrwxr-x 1 pfalcon pfalcon 38693 Apr 28 13:57 gen_idt
-rw-rw-r-- 1 pfalcon pfalcon 15378 Mar 12 18:19 gen_idt.c
-rw-rw-r-- 1 pfalcon pfalcon 54360 Apr 28 13:57 gen_idt.o
-rw-rw-r-- 1 pfalcon pfalcon   324 May  2 10:37 Makefile
-rw-rw-r-- 1 pfalcon pfalcon   447 Mar 12 18:19 version.c
-rw-rw-r-- 1 pfalcon pfalcon   291 Mar 12 18:19 version.h
-rw-rw-r-- 1 pfalcon pfalcon  7416 Apr 28 13:57 version.o
~~~

Removing obj/exe files there recovered the build.

**Comment by nashif** [comment]
The build issue in the commit message.

https://jira.zephyrproject.org/browse/ZEP-2101

**Comment by nashif** [comment]
I will still wait for a fix, however, this PR should be ready to be merged if we have no solution in place. Right now I am getting reports from people being stuck not able to build anything on X86.

**Comment by pfalcon** [comment]
For me it happened with local builds. How it happened is that I built the same in-tree sample for multiple boards, perhaps with cleaning inbetween. I didn't look for pattern, but I'd start with "make pristine", following by building non-x86 board, then build for "make BOARD=qemu_x86" and see if it happens.

**Pull request closed without merging**
