### PR TITLE
boards: arm: b_l072z_lrwan1: Enable the USB controller

### PR DESCRIPTION
**Pull request by andysan**
The STM32L072CZ MCU has a built-in USB device controller which is supported by Zephyr's USB STM32 driver. The b_l072z_lrwan1 board has a micro-USB connector that is wired to the MCU via two solder bridges (SB15 and SB16) that need to be closed to connect the data lines.

Update the board documentation to describe the solder bridges and enable the USB controller in the device tree.

*Testing:* Tested with the `samples/subsys/usb/console` example. 
*Depends on:* https://github.com/zephyrproject-rtos/hal_stm32/pull/53 (already merged)

### CODE REVIEW

**Comment by emob-nordic** [comment]
Made it DNM untill proper SHA is provided in the west manifest.

**Review by gmarull — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Even if this is require HW board modification, please provide pinmux.c update

**Comment by andysan** [comment]
> Even if this is require HW board modification, please provide pinmux.c update

I have updated the PR to configure the pins as inputs. The actual configuration doesn't matter much since the USB block will override it as soon as it is enabled.

**Review by MaureenHelm — APPROVED** [review]

**Comment by andysan** [comment]
> Even if this is require HW board modification, please provide pinmux.c update

This should be fixed now. Are you ok with the proposed change?

**Review by erwango — APPROVED** [review]

**Pull request merged**
