### PR TITLE
RFC: usb: hid: Move HID defines usable for HID over GATTP into common header.

### PR DESCRIPTION
**Pull request by petejohanson**
* Move the HID *defines* to be separate from the USB HID subsystem
  implementation so they can be reusabe for BLE HID over GATTP.

This I discuss in Slack as an option to make more of the HID defines usable for bluetooth uses as well.

Thoughts?

### CODE REVIEW

**Review by jfischer-no — CHANGES_REQUESTED** [review]
No, why? What prevents you to include it in a Bluetooth project?

**Comment by petejohanson** [comment]
@jfischer-phytec-iot Right now, to use any of these HID defines in a project that is using bluetooth but *not* USB, you need to `CONFIG_USB=y` to use them, since the header *also* brings in the methods/definitions from the USB subsystem/driver.

It's certainly a niche edge case, but something I was noticing.

**Comment by jfischer-phytec-iot** [comment]
> @jfischer-phytec-iot Right now, to use any of these HID defines in a project that is using bluetooth but _not_ USB, you need to `CONFIG_USB=y` to use them, since the header _also_ brings in the methods/definitions from the USB subsystem/driver.
> 
> It's certainly a niche edge case, but something I was noticing.

you could cover the USB HID implementation specified types and interfaces, having two usb hid headers is confusing.

```diff
diff --git a/include/usb/class/usb_hid.h b/include/usb/class/usb_hid.h
index 83cc7defbc..a4eca9ffd4 100644
--- a/include/usb/class/usb_hid.h
+++ b/include/usb/class/usb_hid.h
@@ -55,35 +55,6 @@ struct usb_hid_descriptor {
 #define HID_SET_IDLE           0x0A
 #define HID_SET_PROTOCOL       0x0B
 
-/* Public headers */
-
-typedef int (*hid_cb_t)(struct usb_setup_packet *setup, s32_t *len,
-                       u8_t **data);
-typedef void (*hid_int_ready_callback)(void);
-typedef void (*hid_protocol_cb_t)(u8_t protocol);
-typedef void (*hid_idle_cb_t)(u16_t report_id);
-
-struct hid_ops {
-       hid_cb_t get_report;
-       hid_cb_t get_idle;
-       hid_cb_t get_protocol;
-       hid_cb_t set_report;
-       hid_cb_t set_idle;
-       hid_cb_t set_protocol;
-       hid_protocol_cb_t protocol_change;
-       hid_idle_cb_t on_idle;
-       /*
-        * int_in_ready is an optional callback that is called when
-        * the current interrupt IN transfer has completed.  This can
-        * be used to wait for the endpoint to go idle or to trigger
-        * the next transfer.
-        */
-       hid_int_ready_callback int_in_ready;
-#ifdef CONFIG_ENABLE_HID_INT_OUT_EP
-       hid_int_ready_callback int_out_ready;
-#endif
-};
-
 /* HID Report Definitions */
 
 /* HID Items types */
@@ -430,6 +401,36 @@ enum hid_kbd_led {
        HID_KBD_LED_KANA        = 0x10,
 };
 
+#if defined(CONFIG_USB_DEVICE_HID)
+/* Public headers */
+
+typedef int (*hid_cb_t)(struct usb_setup_packet *setup, s32_t *len,
+                       u8_t **data);
+typedef void (*hid_int_ready_callback)(void);
+typedef void (*hid_protocol_cb_t)(u8_t protocol);
+typedef void (*hid_idle_cb_t)(u16_t report_id);
+
+struct hid_ops {
+       hid_cb_t get_report;
+       hid_cb_t get_idle;
+       hid_cb_t get_protocol;
+       hid_cb_t set_report;
+       hid_cb_t set_idle;
+       hid_cb_t set_protocol;
+       hid_protocol_cb_t protocol_change;
+       hid_idle_cb_t on_idle;
+       /*
+        * int_in_ready is an optional callback that is called when
+        * the current interrupt IN transfer has completed.  This can
+        * be used to wait for the endpoint to go idle or to trigger
+        * the next transfer.
+        */
+       hid_int_ready_callback int_in_ready;
+#ifdef CONFIG_ENABLE_HID_INT_OUT_EP
+       hid_int_ready_callback int_out_ready;
+#endif
+};
+
 /* Register HID device */
 void usb_hid_register_device(struct device *dev, const u8_t *desc, size_t size,
                             const struct hid_ops *op);
@@ -445,6 +446,8 @@ int hid_int_ep_read(const struct device *dev, u8_t *data, u32_t max_data_len,
 /* Initialize USB HID */
 int usb_hid_init(const struct device *dev);
 
+#endif /* if defined(CONFIG_USB_DEVICE_HID) */
+
 #ifdef __cplusplus
 }
 #endif
```

**Comment by petejohanson** [comment]
@jfischer-phytec-iot Makes a lot more sense. I've just opened #25049 to replace this one that uses your suggested approach.

**Pull request closed without merging**
