### PR TITLE
Support deprecation of Kconfig symbols

### PR DESCRIPTION
**Pull request by tejlmand**
In #46061 Civetweb was deprecated, and a deprecation feature implemented in CMake which uses the kconfig sysmbol to determine if a warning must be printed.

Instead of doing this through CMake, move the functionality into kconfig.
This is also aligned with how experimental features are handled.

### CODE REVIEW

**Comment by carlescufi** [comment]
Note that the same was done for TinyCBOR, see:
- https://github.com/zephyrproject-rtos/zephyr/pull/44635/files
- https://github.com/zephyrproject-rtos/tinycbor/compare/40daca97b478989884bffb5226e9ab73ca54b8c4..9e1f34bc08123aaad7666d3652aaa839e8178b3b

But this is much cleaner, thank you!

**Review by carlescufi — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by galak** [comment]
Marked this DNM, because I'd like us to determine and document a policy w/regards to deprecation of Kconfig symbols.

**Review by MaureenHelm — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by carlescufi** [comment]
> Marked this DNM, because I'd like us to determine and document a policy w/regards to deprecation of Kconfig symbols.

Isn't the policy orthogonal to the functionality? As it stands this PR is useful to deprecate entire modules that can be turned on/off with a single Kconfig symbol.

**Comment by galak** [comment]
> Isn't the policy orthogonal to the functionality? As it stands this PR is useful to deprecate entire modules that can be turned on/off with a single Kconfig symbol.

It is, the docs area gray area, but will add something to the policy working group queue.

**Review by mbolivar-nordic — COMMENTED** [review]
Late to the party,  but I agree this is cleaner. Thanks.

**Pull request merged**
