### PR TITLE
net: tcp: net_tcp_queue_pkt: Lock while appending to sent_list

### PR DESCRIPTION
**Pull request by pfalcon**
net_tcp_queue_pkt() is a single point where packets are added to
tcp->sent_list, and this happens from application thread. This
list is also accessed (iterated on, items removed) from a number
of delayed work handlers. These handlers are serialized among
themselves. Thus, the only issue is serializing access to this
list between net_tcp_queue_pkt() running in app thread and
delayes works running in own cooperatively scheduled thread.

This patch does this, and as adding to the list is very quick
operation, it just uses irq_lock(), as interrupt jitter added
is very minimal and usage of mutex would likely give the same
amount of jitter anyway.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
This is resubmit of code which initially appeared in https://github.com/zephyrproject-rtos/zephyr/pull/9592, but it was suggested to split it off.

Besides description in the commit message, see also previous discussion in https://github.com/zephyrproject-rtos/zephyr/pull/9592#discussion_r212294702

**Comment by pfalcon** [comment]
@jukkar, @tbursztyka: ping

**Review by jukkar — CHANGES_REQUESTED** [review]
I think it is wrong to use irq_lock() here, it is just too heavy operation to be done here.
The #8674 tried to implement locking in net_context but it requires still a bit more TLC and testing.

**Comment by pfalcon** [comment]
Assumed to be superseded by https://github.com/zephyrproject-rtos/zephyr/pull/8674.

**Pull request closed without merging**
