### PR TITLE
settings: add support for backend definition in devicetree

### PR DESCRIPTION
**Pull request by mniestroj**
Settings subsystem is all about using non-volatile storage capabilities of
used platform. So far all the storage backends are on top of flash memory.
However, this might be extended to EEPROM, secure storage or any other
type. For each of those it looks like migration from Kconfig to devicetree
would be good way forward.

First of all migration to devicetree allows to instantiate multiple
settings backends, where each can be configured on different flash
partition.

Define common properties for `zephyr,settings,TYPE` bindings, which for now
contains only priority in which such settings backend will be initialized.

Introduce devicetree variants of `SETTINGS_STORE_STATIC_DEFINE()` macro, so
that instantiating backends directly from devicetree node identifiers will
be possible.

Introduce following compatible strings:
- `zephyr,settings,fcb`
- `zephyr,settings,file`
- `zephyr,settings,nvs`

and instantiate each node with this compatible from corresponding settings
backend implementation.

Select `SETTINGS_NONE_INIT` whenever there are some enabled devicetree nodes
with above compatible strings. This will make sure that Kconfig
configured backend won't be enabled at the same time.

Depends on (and contains commits from): #53140

### CODE REVIEW

**Comment by Laczen** [comment]
@mniestroj, IMO the backend configuration of the settings system should not be done by using devicetree. It should be possible however to support multiple backends and a custom configuration. To achieve this a `settings_backend_init()` function should be created/creatable by the user.

**Comment by de-nordic** [comment]
Settings are not my area of expertise, but I agree with @Laczen . I also think that configuring software database, which settings are, by hardware description files will not be accepted.
What is probably needed instead is a method to register backends that could be used with SYS_INIT or something like this.

**Comment by de-nordic** [comment]
This depends on commits from https://github.com/zephyrproject-rtos/zephyr/pull/53140, where my comments have been left with no responses.

**Review by de-nordic — CHANGES_REQUESTED** [review]
https://github.com/zephyrproject-rtos/zephyr/pull/53161#issuecomment-1499253389

**Pull request closed without merging**
