### PR TITLE
cmsis rtos: restructure cmsis rtos folder, move include files to lib/

### PR DESCRIPTION
**Pull request by nashif**
Part of include/ cleanup and restructuring.

### CODE REVIEW

**Comment by nashif** [comment]
@galak @carlescufi here goes my first patch for cleaning up include/...

**Comment by galak** [comment]
So I wondering about applications having to include headers from lib/.  Should this instead be something like include/zephyr/compat/cmsis_rtos ?

**Comment by nashif** [comment]
> So I wondering about applications having to include headers from lib/. Should this instead be something like include/zephyr/compat/cmsis_rtos ?

We decided to put things like this and updatehub.h in lib/include I thought.

btw, this is not a zephyr API and do not think compat (for compatibility I guess) is the right terminology here. I would rather keep it simple.

Also, we still did not decide to move zephyr APIs under include/zephyr. I actually dislike the idea as a whole right now and think should keep the same structure we have now + the improvements, namespacing and restructuring we agreed on.

**Comment by nashif** [comment]
closing, done in a different PR

**Pull request closed without merging**
