### PR TITLE
net: http: Remove the old legacy API

### PR DESCRIPTION
**Pull request by jukkar**
There are no internal users for old HTTP API so removing it.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by pfalcon** [comment]
What about external users? Can't we do this post 1.10 release?

**Comment by jukkar** [comment]
Well, @nashif wanted it like this so I sent this patch.
I prepared the earlier HTTP patches for the normal deprecation process in mind but if that is not needed then so be it.

**Comment by mbolivar** [comment]
We are still using the old API, FWIW

**Review by pfalcon — CHANGES_REQUESTED** [review]
Based on the above, proposed to postpone until after 1.10 release.

**Comment by mike-scott** [comment]
We are having issues / fixing bugs in the new HTTP API.  Let's keep the legacy API around till 1.10 to buy some time for our changes to get merged in.

**Comment by nashif** [comment]
ok, lets move it to 1.11

**Comment by nashif** [comment]
rebase please

**Comment by jukkar** [comment]
Rebased against master

**Review by pfalcon — APPROVED** [review]

**Review by mike-scott — APPROVED** [review]
LGTM.  We are not using legacy HTTP APIs any longer.

**Review by nashif — APPROVED** [review]

**Pull request merged**
