### PR TITLE
board: arm: Enable MPU for all STM32 boards supporting it

### PR DESCRIPTION
**Pull request by ABOSTM**
board: arm: Enable MPU for all STM32 boards supporting it

Only boards with at least 64K Flash will activate MPU because:
MPU + UERSPACE + All switches implicity activated
(CONFIG_MPU_STACK_GUARD, CONFIG_ARM_STACK_PROTECTION ...)
will consume about 40K Flash
(value computed on nucleo_f767_zi on tests/arch/arm/arm_ramfunc/).

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
LGTM, but this does not have too much of an effect until CONFIG_ARM_MPU is enabled in the corresponding boards' defconfig files

**Comment by ABOSTM** [comment]
@ioannisg Thanks for your remark I completly missed that point.
I fully reworked the PR.

**Review by ioannisg — APPROVED** [review]
LGTM

**Comment by ABOSTM** [comment]
Edit:
L0 is now part of this PR thanks to discussion #26119

**Comment by ioannisg** [comment]
@galak @erwango could you take a look here?
BTW, not sure why CI times-out - could it be that the PR simply changes too many things?

**Review by erwango — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
merging by hand due to type of changes this will always timeout in CI.

**Pull request merged**
