### PR TITLE
drivers: timer: cc13x2_cc26x2: reduce MAX_TICKS by 1

### LINKED ISSUE #20715: rtc driver may interrupt in a short time for large timeouts on cc13x2/cc26x2
**Describe the bug**
In cc13x2_cc26x2_rtc_timer.c, depending on the setting for CONFIG_SYS_CLOCK_TICKS_PER_SEC and on the timing, z_clock_set_timeout may round up the timeout to the next tick, resulting in setThreshold() being called with a value greater than (0x80000000 + current counter value). In this case, setThreshold() would set the comparator to a value very close to the current count, thinking that the timeout had already expired.

**Expected behavior**
Large timeouts should result in the comparator being set to a value corresponding to MAX_TICKS.

**Impact**
This results in more RTC interrupts than is necessary, potentially wasting cycles and power.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.10.3
 - Commit SHA or Version used: 86461ac559a6c9a45e39ecff2beaecf785994e8a

### PR DESCRIPTION
**Pull request by vanti**
MAX_TICKS needs to be reduced by 1 to accommodate for rounding up in
z_clock_set_timeout(), in such a way to avoid violating the assumption
in setThreshold() where the comparator would not be set to a value
that exceeds 0x80000000 + current count.

Fixes #20715

Signed-off-by: Vincent Wan <vincent.wan@linaro.org>

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
Please, add brackets to explicitly indicate precedence in the introduced expressions

**Comment by vanti** [comment]
Added parentheses based on feedback from @ioannisg.

**Review by ioannisg — COMMENTED** [review]
Thanks for the update. Could you have a #define COUNTER_MAX, to represent the maximum value the hardware can use? See the SysTick or the nRF RTC timer, for example. Then you can use it in line 46 instead of the hard-coded value. That's perhaps minor, but improves presentation and aligns with other timer drivers.

**Review by pabigot — CHANGES_REQUESTED** [review]
Alternatively, take the solution out of #21017, fix it to be correct, and use that?  If you agree that attempt is wrong only in an easily-correctable detail.

**Comment by ioannisg** [comment]
> Alternatively, take the solution out of #21017, fix it to be correct, and use that? If you agree that attempt is wrong only in an easily-correctable detail.

@pabigot I'd separate these two issues. This PR only reduces MAX TICKS by 1, as we do in nRF RTC and SysTick timers, as well, The truncation with MAX_CYC can still be done in #21017, what do you think?

**Comment by pabigot** [comment]
> > Alternatively, take the solution out of #21017, fix it to be correct, and use that? If you agree that attempt is wrong only in an easily-correctable detail.
> 
> @pabigot I'd separate these two issues. This PR only reduces MAX TICKS by 1, as we do in nRF RTC and SysTick timers, as well, The truncation with MAX_CYC can still be done in #21017, what do you think?

I think @vanti noted in https://github.com/zephyrproject-rtos/zephyr/pull/21017/files#r351026561 that if #20939 were corrected then this PR is no longer necessary.  If that's true, I would rather have this PR fix #20939 and take that driver out of #21017, since I don't know when #21017 will get merged.

**Comment by vanti** [comment]
@ioannisg @pabigot Yes as I noted in #21017, this fix is no longer necessary with the changes in that PR. I see the latter has 2.1 as milestone, which would be fine with me. I am closing this one with the assumption that we will honor it.

**Pull request closed without merging**
