### PR TITLE
Limit mcux drivers to SoCs that have the associated hardware

### PR DESCRIPTION
**Pull request by MaureenHelm**
Before this patch series, it was possible in Kconfig to enable the mcux ethernet driver, for example, on an NXP SoC like kw41z that doesn't have ethernet hardware. This would cause compiler errors, but let's catch it earlier in Kconfig. Some newer mcux drivers already do this, so make the older mcux drivers consistent with the newer ones.

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
I would declare the HAS_<Peripheral|FEATURE> globally and not make them SoC/Vendor specific, this way they can be used by other SoCs from other vendors and keep Kconfig option count and complexity sane.

**Comment by MaureenHelm** [comment]
> I would declare the HAS_<Peripheral|FEATURE> globally and not make them SoC/Vendor specific, this way they can be used by other SoCs from other vendors and keep Kconfig option count and complexity sane.

The problem is that I have different variants of the same peripheral type, and each variant has its own driver. For example, there are two types of UARTs, three types of SPIs, two types of I2Cs in the Kinetis family (not all of these variants are in Zephyr yet). So I'm trying to prevent someone from accidentally choosing the wrong variant, or enabling a peripheral that doesn't even exist on a particular SoC.

**Comment by nashif** [comment]
> The problem is that I have different variants of the same peripheral type, and each variant has its own driver.

You mean UART vs LPUART? We can define those variants globally as well if needed, might be mcux specific right now, but can be used by other vendors that might implement this in the future...

**Comment by MaureenHelm** [comment]
> You mean UART vs LPUART? We can define those variants globally as well if needed, might be mcux specific right now, but can be used by other vendors that might implement this in the future...

Yes. I don't think it makes sense to define LPUART globally because it's tied to the hardware and will always be mcux/nxp-specific.

**Comment by nashif** [comment]
Low Power UART seems to be a very generic term to me :)

**Comment by pfalcon** [comment]
I believe I saw LPUART term in EFM32's ;-).

**Comment by nashif** [comment]
also ST has [that](http://www.st.com/content/ccc/resource/technical/document/application_note/c3/77/09/03/41/31/46/0b/DM00151811.pdf/files/DM00151811.pdf/jcr:content/translations/en.DM00151811.pdf).

**Comment by MaureenHelm** [comment]
> I believe I saw LPUART term in EFM32's ;-).

**Comment by MaureenHelm** [comment]
Doh, I accidentally clicked "close and comment".

> I believe I saw LPUART term in EFM32's ;-).

Presumably with a different register programming model and thus a different driver, so wouldn't overloading the Kconfig just cause confusion?

**Comment by nashif** [comment]
Defining HAS_LPUART globally and using it in different SoCs would not affect registers and drivers, it is just a flag that any SoC can use to select the right set of hardware configuration. We do have this problem where this type of information is being repeated for every vendor and this actually causes more confusion and kconfig overload.

**Pull request closed without merging**
