### PR TITLE
soc: nordic_nrf: Add validation of base addresses defined in dts

### PR DESCRIPTION
**Pull request by anangl**
Add a set of build time assertions that checks if the peripheral base
addresses defined in dts nodes match the values provided by nrfx/MDK.

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]
Would be nice if DT could #include the MDK headers, but I see the MDK headers define integers like

`0x5002b000UL`

while DT needs integers formatted as 

```
0x5002A000 and
5002a000
```

```
		cryptocell: crypto@5002a000 {
			compatible = "nordic,nrf-cc310";
			reg = <0x5002A000 0x1000>;
			label = "CRYPTOCELL";
			status = "okay";
			#address-cells = <1>;
			#size-cells = <1>;
			cryptocell310: crypto@5002b000 {
				compatible = "arm,cryptocell-310";
				reg = <0x5002B000 0x1000>;
				interrupts = <42 1>;
				label = "CRYPTOCELL310";
			};
		};

```

`#define NRF_CRYPTOCELL_BASE         0x5002A000UL
`

Having DT #include headers from the MDK is fairly straightforward, but I don't see the MDK generating integers formatted as we want them any time soon.

**Review by carlescufi — APPROVED** [review]
Nice, thanks!

**Comment by carlescufi** [comment]
> Having DT #include headers from the MDK is fairly straightforward, but I don't see the MDK generating integers formatted as we want them any time soon.

Yeah, that is a good point that we could raise with @simtind

**Comment by anangl** [comment]
Solved the issue with missing `NRF_GPIO` symbol for nRF9160.

**Comment by ioannisg** [comment]
nice work @anangl !

**Pull request merged**
