### PR TITLE
Soc arm cleanup systick

### PR DESCRIPTION
**Pull request by ioannisg**
The PR clean-up the inconsistencies with SysTick In ARM platforms:
- Adds the `CPU_HAS_SYSTICK` selection in ARCH for ARMv7-M and ARMv8-M Mainline architectures
- Renames it to `CPU_CORTEX_M_HAS_SYSTICK`, to look similar to all other `CORTEX_M__HAS `options.
- Cleans up ARM ARMv7-M platforms definitions, so they don't need to define CPU_HAS_SYSTICK anymore
- **Removes the default system timer selection for ARM platforms**
   - We have 3 timers at the moment (SysTick, Nordic RTC and SAM0 RTC). Remove default y option.
- Explicitly set the system timer selection in all ARM boards/platforms. This was already done for 70% of the boards - now it is done for all.

In addition, the PR cleans up some left-out direct `CPU_CORTEX_M `Selections in ARM SOCs.

The main reason for the patch (besides the obvious enhancement of clean-up) is to decouple HW capability options (CPU_HAS_) from system configuration.

### CODE REVIEW

**Review by ulfalizer — APPROVED** [review]
Looks reasonable.

Maybe `soc: arm: rename CPU_HAS_SYSTICK to CPU_CORTEX_M_HAS_SYSTICK` could mention why it was renamed in the commit message.

**Review by pizi-nordic — APPROVED** [review]

**Review by andyross — APPROVED** [review]
No reason not to do this, but is SysTick such a weird default?  I mean, it's architecturally specified and always present.  Even nRF and SAM can use it even though they have alternatives they'd like to be default.

**Comment by ioannisg** [comment]
> 
> 
> Looks reasonable.
> 
> Maybe `soc: arm: rename CPU_HAS_SYSTICK to CPU_CORTEX_M_HAS_SYSTICK` could mention why it was renamed in the commit message.

Will do, thanks.
It is added only in the PR description.

**Review by ydamigos — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by ioannisg** [comment]
@carlescufi @galak @MaureenHelm, some help needed on this one - CI times-out continuously, due to the patch introducing changes in a relatively high number of platforms.

**Pull request merged**
