### PR TITLE
pm: fix weaks usage

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Review by carlocaione — DISMISSED** [review]

**Review by ceolin — CHANGES_REQUESTED** [review]
Giving -1 because it needs more discussion. The reason of having this API as weak symbol is to allow applications to have their own implementation. The idea is that Zephyr's code base implement them as weak and let applications overwrite them if needed. If we drop the weak usage we probably need to add a new symbol for applications overwrite them, similar with what we do in pm policy.

**Comment by gmarull** [comment]
> Giving -1 because it needs more discussion. The reason of having this API as weak symbol is to allow applications to have their own implementation. The idea is that Zephyr's code base implement them as weak and let applications overwrite them if needed. If we drop the weak usage we probably need to add a new symbol for applications overwrite them, similar with what we do in pm policy.

Is this something documented? TBH, I think it's a bad idea to let applications decide how an SoC enters low-power states, since this typically involves very specific actions. If certain SoCs need more flexibility, they can always provide Kconfig options to tune settings, or, provide extra hooks.

**Review by andyross — DISMISSED** [review]
Mostly sidestepping the argument to leave a drive-by +1.  As the code exists today, this is all very solid cleanup and IMHO should merge.  If we want to allow app overrides to the core PM hooks, that seems fine too but it's not a feature yet, isn't documented or tested, and is trivial to add back when we get there.

**Comment by gmarull** [comment]
last push: fixed one issue in intel_adsp soc code

**Review by carlocaione — DISMISSED** [review]

**Review by carlocaione — APPROVED** [review]

**Comment by ceolin** [comment]
> > Giving -1 because it needs more discussion. The reason of having this API as weak symbol is to allow applications to have their own implementation. The idea is that Zephyr's code base implement them as weak and let applications overwrite them if needed. If we drop the weak usage we probably need to add a new symbol for applications overwrite them, similar with what we do in pm policy.
> 
> Is this something documented? TBH, I think it's a bad idea to let applications decide how an SoC enters low-power states, since this typically involves very specific actions. If certain SoCs need more flexibility, they can always provide Kconfig options to tune settings, or, provide extra hooks.

That's fair enough.

**Review by ceolin — APPROVED** [review]

**Pull request merged**
