### PR TITLE
mgmt/osdp: Fix broken link in README.rst

### LINKED ISSUE #66411: Broken Link in Documentation:  'samples/subsys/mgmt/osdp/README'
**Bug Title**
The link to LibOSDP Github Library does no longer works.

**Bug Description**
The Link to LibOSDP in the Zephyr Documentation here: [Zephyr OSDP Docs](https://docs.zephyrproject.org/latest/samples/subsys/mgmt/osdp/README.html)

The Link seems to be broken, it no longer navigates to LibOSDP Library.
Here is the new Link URL: __https://github.com/goToMain/libosdp__
For verification: [LibOSDP Repo](https://github.com/goToMain/libosdp)

**Environment**
* Page: `samples/subsys/mgmt/osdp/README`
* Version: main
* SHA-1: c529b6fa8f053ee8a7c55bb961e5a39e42853fd3

screenshot of bug

### PR DESCRIPTION
**Pull request by Ryanjwoodward**
Updated the URL Link to LibOSDP Library in samples/subsys/mgmt/osdp/README

### CODE REVIEW

**Comment by sidcha** [comment]
@Ryanjwoodward thank you for the PR.

The commit message needs the following:

1. For changes to this subsys, we have subject commit prefix "mgmt/osdp: ".
2. A "Signedoff-by:" tag
3. And a short description of what you are changing in commit body.

**Review by nashif — APPROVED** [review]

**Comment by kartben** [comment]
@Ryanjwoodward Thanks for the PR! Can you please squash all your commits into the second one (maybe update the title to "mgmt/osdp: Fix broken link in README.rst", and simply force push to your branch when that's done so that your PR is then just one commit for the fix?
Thanks!

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
Please check the squashed commit as it seems the "actual" commit is unnecessarily lumped under a commit with title "Squashed commit of the following". Hopefully a simple `git commit --amend` should take care of allowing you to properly rewrite the title and remove the indenting. Almost there! :)

image

**Comment by Ryanjwoodward** [comment]
The Commit now appears, from my view, as:
Screenshot 2023-12-12 at 11 09 53 AM

Thank you for your patience with me, as a first time contributor :)

**Review by sidcha — APPROVED** [review]

**Review by r2r0 — APPROVED** [review]

**Comment by kartben** [comment]
@Ryanjwoodward please mark the PR as "ready for review" :)

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
