### PR TITLE
Bluetooth: OTS: Fix issue with callbacks not being set

### LINKED ISSUE #72471: Bluetooth OTS asserts or fail on runtime depending on configuration options
**Describe the bug**
Currently OTS code asserts or fails depending on configuration selected in Kconfig.
Eg enabling CONFIG_BT_OTS_OACP_CHECKSUM_SUPPORT results in assert on init for instances that doesn't implement obj_cal_checksum callback.  Similarly bt_ots_obj_add() may fail if added object has unsupported (ie. disabled in Kconfig) feature.

Since Kconfig is global configuration this leads to confusion where multiple OTS instances are created (eg some might be internal like in MCS case) user might not have control over what is implemented/required by OTS instance...

Either optional features should be made mandatory (ie no kconfig option to disable or always require to implement all callbacks) or some runtime disablement (eg masking out disabled features) could be added.   Otherwise one may end up in case where is it impossible to use multiple OTS instances with contradicting features enabled.

note: There are also few other issues with OTS  API (ie no userdata for callbacks) so maybe this issue should cover more overhaul as enhancement instead of bug?

### PR DESCRIPTION
**Pull request by Thalley**
The checks for callbacks in bt_ots_init did not correctly take the ots_init->features.oacp into account for all callbacks, which caused some issues.

Slightly optimized the check for ots->cb->obj_read by moving the check and reducing the number of places the code calls oacp_read_proc_cb.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/72471

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

**Comment by sjanc** [comment]
we should be also able to revert https://github.com/zephyrproject-rtos/zephyr/pull/73017/files with this patch, right?

**Comment by Thalley** [comment]
> we should be also able to revert https://github.com/zephyrproject-rtos/zephyr/pull/73017/files with this patch, right?

Added a commit to remove that. 

@sjanc Can you ping the bot to run a test that caused the issue before? Just to double check that this fix really fixes that issue, of if something is broken.

**Comment by sjanc** [comment]
#AutoPTS run zephyr nrf52 OTS

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/75382#issuecomment-2208294318, board: nrf52, estimated start time: 10:08:50, test case count: 50, estimated duration: 0:26:01<details><summary>Test cases to be run</summary>OTS/SR/SGGIT/SER/BV-01-C<br>OTS/SR/SGGIT/CHA/BV-01-C<br>OTS/SR/SGGIT/CHA/BV-03-C<br>OTS/SR/SGGIT/CHA/BV-04-C<br>OTS/SR/SGGIT/CHA/BV-05-C<br>OTS/SR/SGGIT/CHA/BV-10-C<br>OTS/SR/SGGIT/CHA/BV-11-C<br>OTS/SR/SGGIT/CHA/BV-13-C<br>OTS/SR/SGGIT/CHA/BV-14-C<br>OTS/SR/SGGIT/CHA/BV-15-C<br>OTS/SR/CR/BV-01-C<br>OTS/SR/CR/BV-02-C<br>OTS/SR/CR/BV-03-C<br>OTS/SR/CR/BV-04-C<br>OTS/SR/CR/BV-07-C<br>OTS/SR/CR/BV-08-C<br>OTS/SR/CRL/BV-01-C<br>OTS/SR/CW/BV-01-C<br>OTS/SR/CWL/BV-01-C<br>OTS/SR/CON/BV-01-C<br>OTS/SR/CON/BV-02-C<br>OTS/SR/CON/BV-03-C<br>OTS/SR/OASP/BV-01-C<br>OTS/SR/OASP/BV-02-C<br>OTS/SR/OASP/BV-03-C<br>OTS/SR/OASP/BV-04-C<br>OTS/SR/OASP/BV-05-C<br>OTS/SR/OASP/BV-06-C<br>OTS/SR/OASP/BV-07-C<br>OTS/SR/OAE/BI-01-C<br>OTS/SR/OAE/BI-03-C<br>OTS/SR/OAE/BI-04-C<br>OTS/SR/OAE/BI-05-C<br>OTS/SR/OAE/BI-06-C<br>OTS/SR/OAE/BI-08-C<br>OTS/SR/OAE/BI-09-C<br>OTS/SR/OAE/BI-12-C<br>OTS/SR/OAE/BI-13-C<br>OTS/SR/OLSP/BV-01-C<br>OTS/SR/OLSP/BV-02-C<br>OTS/SR/OLE/BI-01-C<br>OTS/SR/OLE/BI-03-C<br>OTS/SR/OLE/BI-04-C<br>OTS/SR/OLE/BI-05-C<br>OTS/SR/OME/BI-01-C<br>OTS/SR/OC/BV-01-C<br>OTS/SR/OTD/BI-01-C<br>OTS/SR/OTD/BI-04-C<br>OTS/SR/OTD/BI-05-C<br>OTS/SR/DLO/BV-01-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>OTS     OTS/SR/CON/BV-03-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/71754<br>OTS     OTS/SR/OC/BV-01-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/71754<br>OTS     OTS/SR/OTD/BI-04-C              MISSING WID ERROR<br>OTS     OTS/SR/OTD/BI-05-C              FAIL<br>OTS     OTS/SR/SGGIT/CHA/BV-15-C        FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/71754</details>
<details><summary>Successful tests</summary>OTS     OTS/SR/CON/BV-01-C              PASS<br>OTS     OTS/SR/CON/BV-02-C              PASS<br>OTS     OTS/SR/CR/BV-01-C               PASS<br>OTS     OTS/SR/CR/BV-02-C               PASS<br>OTS     OTS/SR/CR/BV-03-C               PASS<br>OTS     OTS/SR/CR/BV-04-C               PASS<br>OTS     OTS/SR/CR/BV-07-C               PASS<br>OTS     OTS/SR/CR/BV-08-C               PASS<br>OTS     OTS/SR/CRL/BV-01-C              PASS<br>OTS     OTS/SR/CW/BV-01-C               PASS<br>OTS     OTS/SR/CWL/BV-01-C              PASS<br>OTS     OTS/SR/DLO/BV-01-C              PASS<br>OTS     OTS/SR/OAE/BI-01-C              PASS<br>OTS     OTS/SR/OAE/BI-03-C              PASS<br>OTS     OTS/SR/OAE/BI-04-C              PASS<br>OTS     OTS/SR/OAE/BI-05-C              PASS<br>OTS     OTS/SR/OAE/BI-06-C              PASS<br>OTS     OTS/SR/OAE/BI-08-C              PASS<br>OTS     OTS/SR/OAE/BI-09-C              PASS<br>OTS     OTS/SR/OAE/BI-12-C              PASS<br>OTS     OTS/SR/OAE/BI-13-C              PASS<br>OTS     OTS/SR/OASP/BV-01-C             PASS<br>OTS     OTS/SR/OASP/BV-02-C             PASS<br>OTS     OTS/SR/OASP/BV-03-C             PASS<br>OTS     OTS/SR/OASP/BV-04-C             PASS<br>OTS     OTS/SR/OASP/BV-05-C             PASS<br>OTS     OTS/SR/OASP/BV-06-C             PASS<br>OTS     OTS/SR/OASP/BV-07-C             PASS<br>OTS     OTS/SR/OLE/BI-01-C              PASS<br>OTS     OTS/SR/OLE/BI-03-C              PASS<br>OTS     OTS/SR/OLE/BI-04-C              PASS<br>OTS     OTS/SR/OLE/BI-05-C              PASS<br>OTS     OTS/SR/OLSP/BV-01-C             PASS<br>OTS     OTS/SR/OLSP/BV-02-C             PASS<br>OTS     OTS/SR/OME/BI-01-C              PASS<br>OTS     OTS/SR/OTD/BI-01-C              PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-01-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-03-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-04-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-05-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-10-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-11-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-13-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-14-C        PASS<br>OTS     OTS/SR/SGGIT/SER/BV-01-C        PASS</details>

**Comment by Thalley** [comment]
@sjanc Based on the results above, is this solution as expected? At least it doesn't look like it's asserting

**Comment by sjanc** [comment]
#AutoPTS run zephyr GMCS/SR/MCP

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/75382#issuecomment-2208644781, board: nrf53, estimated start time: 12:31:56, test case count: 80, estimated duration: 1:34:28<details><summary>Test cases to be run</summary>GMCS/SR/MCP/BV-01-C<br>GMCS/SR/MCP/BV-02-C<br>GMCS/SR/MCP/BV-70-C<br>GMCS/SR/MCP/BV-03-C<br>GMCS/SR/MCP/BV-04-C<br>GMCS/SR/MCP/BV-71-C<br>GMCS/SR/MCP/BV-05-C<br>GMCS/SR/MCP/BV-06-C<br>GMCS/SR/MCP/BV-72-C<br>GMCS/SR/MCP/BV-07-C<br>GMCS/SR/MCP/BV-08-C<br>GMCS/SR/MCP/BV-73-C<br>GMCS/SR/MCP/BV-09-C<br>GMCS/SR/MCP/BV-10-C<br>GMCS/SR/MCP/BV-11-C<br>GMCS/SR/MCP/BV-74-C<br>GMCS/SR/MCP/BV-12-C<br>GMCS/SR/MCP/BV-13-C<br>GMCS/SR/MCP/BV-14-C<br>GMCS/SR/MCP/BV-75-C<br>GMCS/SR/MCP/BV-15-C<br>GMCS/SR/MCP/BV-16-C<br>GMCS/SR/MCP/BV-17-C<br>GMCS/SR/MCP/BV-76-C<br>GMCS/SR/MCP/BV-18-C<br>GMCS/SR/MCP/BV-19-C<br>GMCS/SR/MCP/BV-20-C<br>GMCS/SR/MCP/BV-77-C<br>GMCS/SR/MCP/BV-21-C<br>GMCS/SR/MCP/BV-22-C<br>GMCS/SR/MCP/BV-23-C<br>GMCS/SR/MCP/BV-78-C<br>GMCS/SR/MCP/BV-24-C<br>GMCS/SR/MCP/BV-25-C<br>GMCS/SR/MCP/BV-26-C<br>GMCS/SR/MCP/BV-79-C<br>GMCS/SR/MCP/BV-27-C<br>GMCS/SR/MCP/BV-28-C<br>GMCS/SR/MCP/BV-29-C<br>GMCS/SR/MCP/BV-80-C<br>GMCS/SR/MCP/BV-30-C<br>GMCS/SR/MCP/BV-31-C<br>GMCS/SR/MCP/BV-32-C<br>GMCS/SR/MCP/BV-34-C<br>GMCS/SR/MCP/BV-35-C<br>GMCS/SR/MCP/BV-36-C<br>GMCS/SR/MCP/BV-33-C<br>GMCS/SR/MCP/BV-37-C<br>GMCS/SR/MCP/BV-38-C<br>GMCS/SR/MCP/BV-39-C<br>GMCS/SR/MCP/BV-40-C<br>GMCS/SR/MCP/BV-41-C<br>GMCS/SR/MCP/BV-42-C<br>GMCS/SR/MCP/BV-43-C<br>GMCS/SR/MCP/BV-44-C<br>GMCS/SR/MCP/BV-45-C<br>GMCS/SR/MCP/BV-46-C<br>GMCS/SR/MCP/BV-47-C<br>GMCS/SR/MCP/BV-48-C<br>GMCS/SR/MCP/BV-49-C<br>GMCS/SR/MCP/BV-50-C<br>GMCS/SR/MCP/BV-51-C<br>GMCS/SR/MCP/BV-52-C<br>GMCS/SR/MCP/BV-53-C<br>GMCS/SR/MCP/BV-54-C<br>GMCS/SR/MCP/BV-55-C<br>GMCS/SR/MCP/BV-56-C<br>GMCS/SR/MCP/BV-57-C<br>GMCS/SR/MCP/BV-58-C<br>GMCS/SR/MCP/BV-59-C<br>GMCS/SR/MCP/BV-60-C<br>GMCS/SR/MCP/BV-61-C<br>GMCS/SR/MCP/BV-62-C<br>GMCS/SR/MCP/BV-63-C<br>GMCS/SR/MCP/BV-64-C<br>GMCS/SR/MCP/BV-65-C<br>GMCS/SR/MCP/BV-66-C<br>GMCS/SR/MCP/BV-67-C<br>GMCS/SR/MCP/BV-68-C<br>GMCS/SR/MCP/BV-69-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GMCS    GMCS/SR/MCP/BV-09-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/67312<br>GMCS    GMCS/SR/MCP/BV-17-C             FAIL - ERRATA Request ID 31410<br>GMCS    GMCS/SR/MCP/BV-20-C             FAIL - ERRATA Request ID 31410<br>GMCS    GMCS/SR/MCP/BV-26-C             FAIL - ERRATA Request ID 31410<br>GMCS    GMCS/SR/MCP/BV-68-C             FATAL ERROR</details>
<details><summary>Successful tests</summary>GMCS    GMCS/SR/MCP/BV-01-C             PASS<br>GMCS    GMCS/SR/MCP/BV-02-C             PASS<br>GMCS    GMCS/SR/MCP/BV-03-C             PASS<br>GMCS    GMCS/SR/MCP/BV-04-C             PASS<br>GMCS    GMCS/SR/MCP/BV-05-C             PASS<br>GMCS    GMCS/SR/MCP/BV-06-C             PASS<br>GMCS    GMCS/SR/MCP/BV-07-C             PASS<br>GMCS    GMCS/SR/MCP/BV-08-C             PASS<br>GMCS    GMCS/SR/MCP/BV-10-C             PASS<br>GMCS    GMCS/SR/MCP/BV-11-C             PASS<br>GMCS    GMCS/SR/MCP/BV-12-C             PASS<br>GMCS    GMCS/SR/MCP/BV-13-C             PASS<br>GMCS    GMCS/SR/MCP/BV-14-C             PASS<br>GMCS    GMCS/SR/MCP/BV-15-C             PASS<br>GMCS    GMCS/SR/MCP/BV-16-C             PASS<br>GMCS    GMCS/SR/MCP/BV-18-C             PASS<br>GMCS    GMCS/SR/MCP/BV-19-C             PASS<br>GMCS    GMCS/SR/MCP/BV-21-C             PASS<br>GMCS    GMCS/SR/MCP/BV-22-C             PASS<br>GMCS    GMCS/SR/MCP/BV-23-C             PASS<br>GMCS    GMCS/SR/MCP/BV-24-C             PASS<br>GMCS    GMCS/SR/MCP/BV-25-C             PASS<br>GMCS    GMCS/SR/MCP/BV-27-C             PASS<br>GMCS    GMCS/SR/MCP/BV-28-C             PASS<br>GMCS    GMCS/SR/MCP/BV-29-C             PASS<br>GMCS    GMCS/SR/MCP/BV-30-C             PASS<br>GMCS    GMCS/SR/MCP/BV-31-C             PASS<br>GMCS    GMCS/SR/MCP/BV-32-C             PASS<br>GMCS    GMCS/SR/MCP/BV-33-C             PASS<br>GMCS    GMCS/SR/MCP/BV-34-C             PASS<br>GMCS    GMCS/SR/MCP/BV-35-C             PASS<br>GMCS    GMCS/SR/MCP/BV-36-C             PASS<br>GMCS    GMCS/SR/MCP/BV-37-C             PASS<br>GMCS    GMCS/SR/MCP/BV-38-C             PASS<br>GMCS    GMCS/SR/MCP/BV-39-C             PASS<br>GMCS    GMCS/SR/MCP/BV-40-C             PASS<br>GMCS    GMCS/SR/MCP/BV-41-C             PASS<br>GMCS    GMCS/SR/MCP/BV-42-C             PASS<br>GMCS    GMCS/SR/MCP/BV-43-C             PASS<br>GMCS    GMCS/SR/MCP/BV-44-C             PASS<br>GMCS    GMCS/SR/MCP/BV-45-C             PASS<br>GMCS    GMCS/SR/MCP/BV-46-C             PASS<br>GMCS    GMCS/SR/MCP/BV-47-C             PASS<br>GMCS    GMCS/SR/MCP/BV-48-C             PASS<br>GMCS    GMCS/SR/MCP/BV-49-C             PASS<br>GMCS    GMCS/SR/MCP/BV-50-C             PASS<br>GMCS    GMCS/SR/MCP/BV-51-C             PASS<br>GMCS    GMCS/SR/MCP/BV-52-C             PASS<br>GMCS    GMCS/SR/MCP/BV-53-C             PASS<br>GMCS    GMCS/SR/MCP/BV-54-C             PASS<br>GMCS    GMCS/SR/MCP/BV-55-C             PASS<br>GMCS    GMCS/SR/MCP/BV-56-C             PASS<br>GMCS    GMCS/SR/MCP/BV-57-C             PASS<br>GMCS    GMCS/SR/MCP/BV-58-C             PASS<br>GMCS    GMCS/SR/MCP/BV-59-C             PASS<br>GMCS    GMCS/SR/MCP/BV-60-C             PASS<br>GMCS    GMCS/SR/MCP/BV-61-C             PASS<br>GMCS    GMCS/SR/MCP/BV-62-C             PASS<br>GMCS    GMCS/SR/MCP/BV-63-C             PASS<br>GMCS    GMCS/SR/MCP/BV-64-C             PASS<br>GMCS    GMCS/SR/MCP/BV-65-C             PASS<br>GMCS    GMCS/SR/MCP/BV-66-C             PASS<br>GMCS    GMCS/SR/MCP/BV-67-C             PASS<br>GMCS    GMCS/SR/MCP/BV-69-C             PASS<br>GMCS    GMCS/SR/MCP/BV-70-C             PASS<br>GMCS    GMCS/SR/MCP/BV-71-C             PASS<br>GMCS    GMCS/SR/MCP/BV-72-C             PASS<br>GMCS    GMCS/SR/MCP/BV-73-C             PASS<br>GMCS    GMCS/SR/MCP/BV-74-C             PASS<br>GMCS    GMCS/SR/MCP/BV-75-C             PASS<br>GMCS    GMCS/SR/MCP/BV-76-C             PASS<br>GMCS    GMCS/SR/MCP/BV-77-C             PASS<br>GMCS    GMCS/SR/MCP/BV-78-C             PASS<br>GMCS    GMCS/SR/MCP/BV-79-C             PASS<br>GMCS    GMCS/SR/MCP/BV-80-C             PASS</details>

**Comment by sjanc** [comment]
@Thalley yeap, looks OK to me

**Review by sjanc — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]

**Pull request merged**
