### PR TITLE
boards: mimxrt1024_evk: enable mcux ethernet driver and pins

### PR DESCRIPTION
**Pull request by aunsbjerg**
Enables the mcux ethernet driver and pin muxes on the
mimxrt1024_evk board in the same way as is done on the
mimxrt1020_evk and mimxrt1050_evk.

Documentation updated accordingly.

Signed-off-by: Mikkel Jakobsen <mikkel.aunsbjerg@prevas.dk>

### CODE REVIEW

**Comment by aunsbjerg** [comment]
DNM until I iron some issues I only found after rebasing to latest main.

**Review by dleach02 — APPROVED** [review]

**Comment by aunsbjerg** [comment]
Added the quickfix from #38186 and now everything works as expected.

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Please add `netif:eth` to the supported list in the board yaml.

**Comment by aunsbjerg** [comment]
> Please add `netif:eth` to the supported list in the board yaml.

The supported list was empty, so I took the libery of adding the basic features based on the `mimxrt1020_evk`. Let me know if you'd rather just have `netif:eth`.

**Review by MaureenHelm — APPROVED** [review]
>> Please add netif:eth to the supported list in the board yaml.

> The supported list was empty, so I took the libery of adding the basic features based on the mimxrt1020_evk. Let me know if you'd rather just have netif:eth.

Thanks for doing this. Unfortunately it uncovered some unrelated issues, so unless you want to fix those too, I suggest limiting the list to netif:eth for now so we can get this PR merged before the window closes tomorrow.

**Comment by MaureenHelm** [comment]
Needs rebase

**Pull request merged**
