### PR TITLE
[backport v1.14-branch]sdk: add support for Zephyr SDK 0.11

### PR DESCRIPTION
**Pull request by wentongwu**
This adds support for Zephyr SDK 0.11.* which is backported from master branch.

### CODE REVIEW

**Comment by marc-hb** [comment]
The `-x` option of `git cherry-pick -x` is extremely useful for reviewing backports because it helps compare with the original commits. There are even scripts that parse the output of `-x` to automate that comparison.

This `-x` option doesn't seem very popular in this branch though... is there some backporting guide in Zephyr documentation?

As an example here's one battle-hardened (10,000s of commits) backporting guide:
https://chromium.googlesource.com/chromiumos/docs/+/master/kernel_faq.md#UPSTREAM_BACKPORT_FROMLIST_and-you

**Review by tejlmand — APPROVED** [review]
PR is ok in terms of introducing Zephyr SDK 0.11.

Haven't verified that going for Zephyr SDK 0.11 fixes the issue #26659

**Comment by nashif** [comment]
> Fixes #26659

no issue with this number

**Comment by nashif** [comment]
CI on this PR is still using 0.10.3, did you run a complete sanitycheck with the 0.11 SDK?

**Comment by wentongwu** [comment]
> > Fixes #26659
> 
> no issue with this number

updated, it has been transferred to https://github.com/zephyrproject-rtos/sdk-ng/issues/237 after this PR.

**Comment by wentongwu** [comment]
> CI on this PR is still using 0.10.3, did you run a complete sanitycheck with the 0.11 SDK?

ongoing

**Comment by wentongwu** [comment]
> CI on this PR is still using 0.10.3, did you run a complete sanitycheck with the 0.11 SDK?

@nashif there are some problems in CI after upgrade SDK to 0.11.4, almost every platform has problem, I'm not sure anyone would like to look at them. Can we build another SDK which just upgrade GCC for arc platform based on 0.10.3, others have no changes?

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by stephanosio** [comment]
> there are some problems in CI after upgrade SDK to 0.11.4, almost every platform has problem, I'm not sure anyone would like to look at them

Do you have an error log somewhere?

> Can we build another SDK which just upgrade GCC for arc platform based on 0.10.3 to fix the issue [zephyrproject-rtos/sdk-ng#237](https://github.com/zephyrproject-rtos/sdk-ng/issues/237), others have no changes?

@galak @tejlmand How do you suggest we proceed with this given that there is no relation between the Zephyr version and the SDK version, and there is no scheme to support backporting in any practical sense?

**Comment by wentongwu** [comment]
> > there are some problems in CI after upgrade SDK to 0.11.4, almost every platform has problem, I'm not sure anyone would like to look at them
> 
> Do you have an error log somewhere?

I run CI on qemu_x86 and qemu_riscv32, both of which doesn't work at all. And also there are random errors on mps2_an385 and qemu_cortex_m3, but just one or two. Maybe all the errors are related to qemu instead of tool chain, but didn't get chance to debug.

**Comment by marc-hb** [comment]
> there are some problems in CI after upgrade SDK to 0.11.4, almost every platform has problem, I'm not sure anyone would like to look at them.

You could start by looking at a couple. In my experience it's better when everything fails in CI rather than just a few platforms because it's then much more likely that all platforms fail with the same error(s).

**Comment by tejlmand** [comment]
> > Can we build another SDK which just upgrade GCC for arc platform based on 0.10.3 to fix the issue [zephyrproject-rtos/sdk-ng#237](https://github.com/zephyrproject-rtos/sdk-ng/issues/237), others have no changes?
> 
> @galak @tejlmand How do you suggest we proceed with this given that there is no relation between the Zephyr version and the SDK version, and there is no scheme to support backporting in any practical sense?

This was exactly the reason for https://github.com/zephyrproject-rtos/sdk-ng/pull/199 cause after `cmake/toolchain/zephyr/0.x` folder is no longer needed in the Zephyr repo, then no backport is needed when a new SDK is released.
This has nothing to do with version numbers in sync.

But of course, Zephyr 1.14 doesn't have those changes: https://github.com/zephyrproject-rtos/zephyr/pull/24143/
so it is stuck at SDK `0.10` without a backport.

@wentongwu Should we consider including https://github.com/zephyrproject-rtos/zephyr/pull/24143/ into this backport, as to allow future use of SDK 0.12 without yet another backport PR ?

**Pull request closed without merging**
