### PR TITLE
Host conformance backport v1.14

### PR DESCRIPTION
**Pull request by joerchan**
All host unmerged backporting issues combined

 - https://github.com/zephyrproject-rtos/zephyr/pull/17464
 Bluetooth: Add BT_SMP_ENFORCE_MITM option
 - https://github.com/zephyrproject-rtos/zephyr/pull/17601
  Bluetooth: tester: Enable Mesh Friend support
 - https://github.com/zephyrproject-rtos/zephyr/pull/17602
 Bluetooth: shell: Fix L2CAP connect parameters count
 - https://github.com/zephyrproject-rtos/zephyr/pull/17605
 Bluetooth: tester: Update to recent conn param related changes in BTP
 - https://github.com/zephyrproject-rtos/zephyr/pull/17606
 Bluetooth: tester: Enable GAP writable device name
 - https://github.com/zephyrproject-rtos/zephyr/pull/17638
  Bluetooth: tester: Change RPA timeout
 - https://github.com/zephyrproject-rtos/zephyr/pull/17859
 Bluetooth: GATT: Fix byte order for database hash
 - https://github.com/zephyrproject-rtos/zephyr/pull/17862
 Bluetooth: GATT: Add BTP Discover All Primary Services command handler
 - https://github.com/zephyrproject-rtos/zephyr/pull/17939
Bluetooth: Shell: Fix unregister GATT Metrics vendor service
 - https://github.com/zephyrproject-rtos/zephyr/pull/17981
Bluetooth: Host: Fix wrong init address when controller resolved address
 - https://github.com/zephyrproject-rtos/zephyr/pull/18025
 Bluetooth: Controller: Fix privacy advertiser connect peer address type
 - https://github.com/zephyrproject-rtos/zephyr/pull/18036
 Bluetooth: Host: Fix bug in creating connection with wrong own address.
 - https://github.com/zephyrproject-rtos/zephyr/pull/17673
 Bluetooth: Mesh: Fix rejecting invalid remote public key
 - https://github.com/zephyrproject-rtos/zephyr/pull/18056
Bluetooth: SMP: Fix SMP identity distributing IRK for ID 0 always
 - https://github.com/zephyrproject-rtos/zephyr/pull/16593
 Bluetooth: gatt: Fix DB corruption when adding/removing service
 - https://github.com/zephyrproject-rtos/zephyr/pull/16629 OBS OBS
 Bluetooth: host: Fix gatt indicate when conn is NULL
 - https://github.com/zephyrproject-rtos/zephyr/pull/17724
Bluetooth: Host: Fix advertiser state flags

 - https://github.com/zephyrproject-rtos/zephyr/pull/17575
Bluetooth: GATT: Use atomic_t for subscribe flags
Bluetooth: GATT: Fix not canceling on unsubscribe
Bluetooth: ATT: Fix bt_att_req_cancel clearing outstanding request

 - https://github.com/zephyrproject-rtos/zephyr/pull/17465
 Bluetooth: GATT: Fix segfault discover descriptors all UUIDs

 - https://github.com/zephyrproject-rtos/zephyr/pull/17233 replaced by: https://github.com/zephyrproject-rtos/zephyr/pull/17476
doc: Bluetooth: Update PICS to ICS
doc: Bluetooth: Add ICS for Mesh Profile
doc: Bluetooth: Update SM ICS to 7.4.1
doc: Bluetooth: Update L2CAP ICS to 7.4.1
doc: Bluetooth: Update GATT ICS to 7.4.1
doc: Bluetooth: Update GAP ICS to 7.4.1

 - https://github.com/zephyrproject-rtos/zephyr/pull/17878
 Bluetooth: Settings: Fix generated identity not persistently stored.
 - https://github.com/zephyrproject-rtos/zephyr/pull/17836
 Bluetooth: SMP: Fix peripheral security request with authenticated keys
 - https://github.com/zephyrproject-rtos/zephyr/pull/17798
bluetooth: Fix an undefined behavior

 - https://github.com/zephyrproject-rtos/zephyr/pull/16178
Bluetooth: gatt: Reuse existing handles from a previously added service

 - https://github.com/zephyrproject-rtos/zephyr/pull/18091
Bluetooth: controller: Fix assert in RPA timeout for advertiser

 - https://github.com/zephyrproject-rtos/zephyr/pull/18250 
Bluetooth: Host: fix missing interval_min copy

 - https://github.com/zephyrproject-rtos/zephyr/pull/18264
Bluetooth: Host: Set Kconfig RPA timeout in controller
Bluetooth: Host: Fix RPA timer not running

- https://github.com/zephyrproject-rtos/zephyr/pull/18026
Bluetooth: Mesh: LPN: Remove msg from cache on rejection

- https://github.com/zephyrproject-rtos/zephyr/pull/18219
Bluetooth: Mesh: Move heartbeat sending to transport layer
Bluetooth: Mesh: Move heartbeat sending to transport layer 
Bluetooth: Mesh: Move heartbeat sending to transport layer

- https://github.com/zephyrproject-rtos/zephyr/pull/18221
Bluetooth: Mesh: Fix resending segments on correct bearer

- https://github.com/zephyrproject-rtos/zephyr/pull/18223
Bluetooth: Mesh: Fix canceling publication retransmission timer

- https://github.com/zephyrproject-rtos/zephyr/pull/18225
Bluetooth: Mesh: Fix canceled buffer memory leak 
Bluetooth: Mesh: Fix not sending all segments through the Friend Queue 

- https://github.com/zephyrproject-rtos/zephyr/pull/18230
Bluetooth: Mesh: Fix starting IV Update when not on primary subnet

- https://github.com/zephyrproject-rtos/zephyr/pull/18285
Bluetooth: Mesh: Fix reference count imbalance in bt_mesh_net_resend()
Bluetooth: Mesh: Introduce a helper for send callback finalization 

 ----

Fixes: #17971
Fixes: #17294

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
LGTM, For the doc changes, I'm assuming there were no new changes introduced by this backport to the 1.14 branch.

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

**Comment by joerchan** [comment]
@jhedberg It says you force-pushed, did you modify any commits, or just add commits?

**Comment by jhedberg** [comment]
@joerchan I updated the last two commits to match the fixed ones in #18219

**Pull request merged**
