### PR TITLE
drivers: adc: fix IF_ENABLED macro usage in ADS1X1X trigger

### PR DESCRIPTION
**Pull request by Benni77**
This pull request fixes a configuration issue in the ADS1X1X ADC driver where the alert/ready GPIO wasn't being properly configured even when specified in devicetree.

The root cause was that the ADC_ADS1X1X_TRIGGER macro was being defined empty when alert_rdy_gpios were present in devicetree. However, the IF_ENABLED macro evaluates to true only if a macro is both defined AND equals 1 (effectively equivalent to `#if defined(CONFIG_FLAG) && (CONFIG_FLAG == 1)`).

This affected the GPIO configuration in the driver:
- The structure member definition: https://github.com/zephyrproject-rtos/zephyr/blob/28bd478a0b709774534adbec8060097bd87cf28c/drivers/adc/adc_ads1x1x.c#L139
- Was not being included in the config struct: https://github.com/zephyrproject-rtos/zephyr/blob/28bd478a0b709774534adbec8060097bd87cf28c/drivers/adc/adc_ads1x1x.c#L814

The fix explicitly defines ADC_ADS1X1X_TRIGGER as 1 when alert_rdy_gpios are present in devicetree, ensuring proper conditional compilation of the GPIO configuration.

@efra-mx what do you think about this?

### CODE REVIEW

**Comment by efra-mx** [comment]
I have not worked with this module in a while.

I will have a look later during the week.

**Review by anangl — APPROVED** [review]

**Comment by Benni77** [comment]
@efra-mx any news on this?

**Comment by efra-mx** [comment]
> @efra-mx any news on this?

You are correct!. It looks good

**Comment by efra-mx** [comment]
I cannot give approval sadly

**Comment by Benni77** [comment]
@kartben would you mind reviewing/approving?

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
@Benni77 looks good, thank you!
However, you need to please fix the compliance issues (i.e. correctly add sign off entry, wrap commit message, etc.)
Once you've ameneded the commit, you may force-push to your branch (and this should not dismiss the existing +1, btw :) )

**Comment by Benni77** [comment]
Thanks for pointing out @kartben. Commit message should be fixed now :) 🤞

**Pull request merged**
