### PR TITLE
Bluetooth: Mesh: Clean up sample config

### PR DESCRIPTION
**Pull request by trond-snekvik**
Removes redundant and invalid configurations from the bluetooth/mesh
sample. Removes some stale disabled config entries.

Fixes L2CAP related warning in config step of sample.

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

### CODE REVIEW

**Comment by jhedberg** [comment]
Are you sure this doesn't break anything, e.g. qemu_x86 which might need some of these? Thinking e.g. of the tinycrypt option.

**Comment by trond-snekvik** [comment]
Right. Apparently RX_MTU and tinycrypt is needed for QEMU, which means that we won't be able to get around the warning for L2CAP on the nRF boards. I tried enabling `BT_HCI_ACL_FLOW_CONTROL`, but that appears to not be working at all on that platform.

Will put those configs back in

**Comment by jhedberg** [comment]
@trond-snekvik I suppose the clean way to get rid of all warnings would be to have per-board configs. That can be left for another PR however.

**Review by jhedberg — APPROVED** [review]

**Comment by trond-snekvik** [comment]
The CI build failure looked unrelated, did a rebase with master to trigger a clean rerun

**Pull request merged**
