### PR TITLE
[TOPIC-GPIO] Convert actinius_icarus and degu_evk boards to new GPIO API

### PR DESCRIPTION
**Pull request by anangl**
Pairs of gpio_pin_configure/gpio_pin_write are replaced with calls to
gpio_pin_configure that configure a given pin as output with the proper
initial state.

### CODE REVIEW

**Comment by anangl** [comment]
@alextsam Could you verify that the changes for the actinius_icarus board are correct? I don't have such board at hand to check it myself. @takumiando Could you check the changes for the degu_evk board? I don't have this one either.

**Review by mnkp — APPROVED** [review]

**Comment by takumiando** [comment]
@anangl Thank you for your fix! I checked and approved your changes.

**Comment by alextsam** [comment]
@anangl the changes are good, thank you! However, should I update also the device tree to use the new defines? eg currently we have `GPIO_INT_ACTIVE_LOW` which I guess should be replaced with `GPIO_ACTIVE_LOW` etc

**Review by mnkp — CHANGES_REQUESTED** [review]
> should I update also the device tree to use the new defines? eg currently we have `GPIO_INT_ACTIVE_LOW` which I guess should be replaced with `GPIO_ACTIVE_LOW` etc

Thanks @alextsam for pointing it out. I overlooked this during the review. It's best if we do it in this PR. I'm marking it as changes requested.

**Comment by anangl** [comment]
> > should I update also the device tree to use the new defines? eg currently we have `GPIO_INT_ACTIVE_LOW` which I guess should be replaced with `GPIO_ACTIVE_LOW` etc
> 
> Thanks @alextsam for pointing it out. I overlooked this during the review. It's best if we do it in this PR. I'm marking it as changes requested.

Yes, my bad, I focused only on changes in code and forgot about dts files. Thanks @alextsam!
I'll update dts files for both boards in a moment.

**Review by mnkp — APPROVED** [review]

**Comment by alextsam** [comment]
Thank you very much for the changes! One small thing that I just noticed is line 102:
```
		irq-gpios = <&gpio0 28 0>, <&gpio0 29 0>;
```
the 0 did not matter there before, but now with the logical read this should be fixed to 
```
		irq-gpios = <&gpio0 28 GPIO_ACTIVE_HIGH>, <&gpio0 29 GPIO_ACTIVE_HIGH>;
```
Should I push to anangl:gpio/convert_nrf_boards so then you just squash?

**Comment by anangl** [comment]
@alextsam
> the 0 did not matter there before, but now with the logical read this should be fixed to
> 
> ```
> 		irq-gpios = <&gpio0 28 GPIO_ACTIVE_HIGH>, <&gpio0 29 GPIO_ACTIVE_HIGH>;
> ```

There is no need to change it. `GPIO_ACTIVE_HIGH` has value of `0`, and it is the default setting. In most such cases (not all, I know) `0` is used, not `GPIO_ACTIVE_HIGH`. Thus, I think it will be better to keep it as it is. See https://github.com/zephyrproject-rtos/zephyr/pull/16648#discussion_r313248778.

**Pull request merged**
