### PR TITLE
drivers: flash: update gd32 flash v2

### LINKED ISSUE #65763: GD32 flash(v2) driver bank0 writing problem.
Hello
Nowadays, I'm trying to integrate GD32F103 to Zephyr 3.5 and I have encountered a problem about bank0 writing function.

I believe the code at flash_gd32_v2.c (gd32_fmc_v2_bank0_write) -> line 80
	flash_prg_t *prg_flash = (flash_prg_t *)((uint8_t *)SOC_NV_FLASH_SIZE + offset);
should be
	flash_prg_t *prg_flash = (flash_prg_t *)((uint8_t *)SOC_NV_FLASH_ADDR + offset);

Thanks.

### PR DESCRIPTION
**Pull request by cameled**
There have some incorrect usage of bank0/1 size and bank0/1 page size.

Fix: #65763

### CODE REVIEW

**Comment by cameled** [comment]
It's ready to review now.

**Review by de-nordic — DISMISSED** [review]
Looks OK.

**Comment by nandojve** [comment]
Hi @cameled ,

We need make sure this is at least building with tests/drivers/flash/common/testcase.yaml. Can you add an entry at
```
  drivers.flash.common.gd32:
    platform_allow:
      - <board 1>
      - <board 2>
      - <board N>
```
You don't need add all boards. One board per driver variation is Ok.
Then each board must have the `flash` entry at <board>.yaml file in the `supported` list.

**Comment by cameled** [comment]
> Hi @cameled ,
> 
> We need make sure this is at least building with tests/drivers/flash/common/testcase.yaml. Can you add an entry at
> 
> ```
>   drivers.flash.common.gd32:
>     platform_allow:
>       - <board 1>
>       - <board 2>
>       - <board N>
> ```
> 
> You don't need add all boards. One board per driver variation is Ok. Then each board must have the `flash` entry at .yaml file in the `supported` list.


Sure, I will try to add it later today.

**Comment by cameled** [comment]
For gd32a503 build, there have a ``note`` as below. 
```
-- west build: building application
[1/139] Preparing syscall dependency handling

[2/139] Generating include/generated/version.h
-- Zephyr version: 3.5.99 (/home/cameled/Builds/zephyrproject/zephyr), build: zephyr-v3.5.0-2357-g11f7bbd131f3
[94/139] Building C object zephyr/arch/arch/arm/c...CMakeFiles/arch__arm__core__mpu.dir/arm_mpu.c.obj
/home/cameled/Builds/zephyrproject/zephyr/arch/arm/core/mpu/arm_mpu.c: In function 'z_arm_mpu_init':
/home/cameled/Builds/zephyrproject/zephyr/arch/arm/core/mpu/arm_mpu.c:474:9: note: '#pragma message: Null-Pointer exception detection cannot be configured on un-mapped flash areas'
  474 | #pragma message "Null-Pointer exception detection cannot be configured on un-mapped flash areas"
      |         ^~~~~~~
[138/139] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       35727 B       384 KB      9.09%
             RAM:        7048 B        48 KB     14.34%
        IDT_LIST:          0 GB         2 KB      0.00%
[139/139] cd /home/cameled/Builds/zephyrproject/z...ilds/zephyrproject/zephyr/build/zephyr/zephyr.elf
```

I tried to fix it, but below comparison looks always true. 
```
#if defined(CONFIG_NULL_POINTER_EXCEPTION_DETECTION_MPU)
#if (defined(CONFIG_ARMV8_M_BASELINE) || defined(CONFIG_ARMV8_M_MAINLINE)) && \
	(CONFIG_FLASH_BASE_ADDRESS > CONFIG_CORTEX_M_NULL_POINTER_EXCEPTION_PAGE_SIZE)
#pragma message "Null-Pointer exception detection cannot be configured on un-mapped flash areas"
#else
```

**Comment by cameled** [comment]
@nandojve Could please help to confirm all three boards add to flash common test correctly?

**Comment by nandojve** [comment]
Hi @cameled ,

> @nandojve Could please help to confirm all three boards add to flash common test correctly?
> 
> EDIT: I checked the CI log, looks three boards build flash common test passed.

You need to fix, see below:

```diff
diff --git a/boards/arm/gd32a503v_eval/gd32a503v_eval.yaml b/boards/arm/gd32a503v_eval/gd32a503v_eval.yaml
index 396e68d24b..e2e2145d9a 100644
--- a/boards/arm/gd32a503v_eval/gd32a503v_eval.yaml
+++ b/boards/arm/gd32a503v_eval/gd32a503v_eval.yaml
@@ -16,6 +16,7 @@ supported:
   - counter
   - dac
   - dma
+  - flash
   - gpio
   - pwm
   - spi
diff --git a/boards/arm/gd32f470i_eval/gd32f470i_eval.yaml b/boards/arm/gd32f470i_eval/gd32f470i_eval.yaml
index 868e4907f3..9537f9aef3 100644
--- a/boards/arm/gd32f470i_eval/gd32f470i_eval.yaml
+++ b/boards/arm/gd32f470i_eval/gd32f470i_eval.yaml
@@ -14,6 +14,7 @@ toolchain:
 supported:
   - counter
   - dac
+  - flash
   - gpio
   - i2c
   - pwm
diff --git a/boards/riscv/gd32vf103v_eval/gd32vf103v_eval.yaml b/boards/riscv/gd32vf103v_eval/gd32vf103v_eval.yaml
index 306d3e1149..857fe8adf6 100644
--- a/boards/riscv/gd32vf103v_eval/gd32vf103v_eval.yaml
+++ b/boards/riscv/gd32vf103v_eval/gd32vf103v_eval.yaml
@@ -10,10 +10,11 @@ flash: 128
 toolchain:
   - zephyr
 supported:
-  - uart
+  - dma
+  - flash
   - gpio
   - pwm
-  - watchdog
-  - dma
   - spi
+  - uart
+  - watchdog
 vendor: gd
diff --git a/tests/drivers/flash/common/testcase.yaml b/tests/drivers/flash/common/testcase.yaml
index c61763bfd8..a3624f76be 100644
--- a/tests/drivers/flash/common/testcase.yaml
+++ b/tests/drivers/flash/common/testcase.yaml
@@ -35,9 +35,6 @@ tests:
     integration_platforms:
       - qemu_x86
       - mimxrt1060_evk
-      - gd32vf103v_eval
-      - gd32a503v_eval
-      - gd32f470i_eval
   drivers.flash.common.tfm_ns:
     build_only: true
     filter: (CONFIG_FLASH_HAS_DRIVER_ENABLED and CONFIG_TRUSTED_EXECUTION_NONSECURE
@@ -95,3 +92,8 @@ tests:
       - atsamd20_xpro
       - atsamr21_xpro
       - atsame54_xpro
+  drivers.flash.common.gd32:
+    platform_allow:
+      - gd32vf103v_eval
+      - gd32a503v_eval
+      - gd32f470i_eval
```

> I tried to fix it, but below comparison looks always true. CONFIG_FLASH_BASE_ADDRESS is flash base address 0x08000000, and CONFIG_CORTEX_M_NULL_POINTER_EXCEPTION_PAGE_SIZE default value is 0x400.

Please, address this at arm channel because it is not clear to me too.

**Comment by cameled** [comment]
@nandojve CI test done.
Screenshot from 2023-12-01 10-30-46

**Review by nandojve — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
