### PR TITLE
tests: More SMP disablement

### PR DESCRIPTION
**Pull request by andyross**
A few more test cases that are measurably unreliable when run in SMP.
For the most part these work most of the time (though the semaphore
one was pretty borderline -- I measured about 25% failures), but are
measurably unstable against the backdrop of known qemu instability.
Something is clearly going on and we need to come back to these to fix
threadsafety issues.

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by andyross** [comment]
Stuck a "bug" label on this, but it fixes a verbally-reported failure (and others I found), so there's no related issue opened.  Let me know if I should open one to get this merged for 1.14.

**Comment by andrewboie** [comment]
Is there a bug open to track the issues we are seeing?

**Comment by andyross** [comment]
No, but there should be.  Will open one right now for 1.15.

**Comment by andyross** [comment]
OK, filed as an enhancement for 1.15: #14639

**Review by dcpleung — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Pull request merged**
