### PR TITLE
cmake: convert ARCH_DIR path to CMake style

### PR DESCRIPTION
**Pull request by dleach02**
Windows build needs this when generating offsets.c

### CODE REVIEW

**Comment by dleach02** [comment]
@tejlmand, I needed to do this fix for Windows builds. But to be honest, not sure if there isn't a better place for this.

**Comment by tejlmand** [comment]
> @tejlmand, I needed to do this fix for Windows builds. But to be honest, not sure if there isn't a better place for this.

if this is needed here, then it's a more fundamental problem and we should ensure that ARCH_DIR is correct from the start.
Probably the reason for the change is that we have switched from determine arch dir based on folder (in CMake) to use python, and thus python might give us a native path, not a posix path.

Will take a look, thanks for finding this.

**Comment by tejlmand** [comment]
please take a look here: #69023

**Comment by tejlmand** [comment]
Closing as https://github.com/zephyrproject-rtos/zephyr/pull/69023 has been merged.

**Pull request closed without merging**
