### PR TITLE
settings: NVS: add entry into cache after writing

### PR DESCRIPTION
**Pull request by alxelax**
Settings NVS adds entry into Settings NVS cache after writing it into flash. Previously, the entry was added into cache only on the second writing attempt that caused very huge timing despite cache was enabled since it was still empty.

Scenario: store ble mesh replay protection list with 255 entries by button pressing(in real life by timer):
proof1
Right picture with this improvement. The second attempt is encircled in red.
Branch with testing app: https://github.com/alxelax/zephyr/tree/settings_with_large_rpl
Referenced sample: bluetooth/mesh. Referenced device: nrf52840dk_nrf52840
You can see the second attempt takes to write RPL about 30 seconds because cache is empty.
If build cache during the first writing attempt, then it takes about 1.7 seconds (improvement).

### CODE REVIEW

**Comment by alxelax** [comment]
Seems reviewer assigning script doesn't work properly for Settings. I added all participants who reviewed initial settings cache PR + @LingaoM. Sorry, if somebody was added by mistake.

**Comment by Laczen** [comment]
Hi @alxelax, thanks for the PR.

This is a strange change, from the first look it seems to be adding to the hash table before the write has been performed.

I don't see (in code) why it would only be added on the second write attempt: as soon as a name and name_id is written it is added. What I do see is that on every load the hash table is rebuild, might this be the cause of the slower second attempt  ?

**Comment by alxelax** [comment]
> Hi @alxelax, thanks for the PR.
> 
> This is a strange change, from the first look it seems to be adding to the hash table before the write has been performed.
> 
@Laczen,

Hm. Whether the writing has been performed here?: https://github.com/alxelax/zephyr/blob/setting_nvs_cache_improve/subsys/settings/src/settings_nvs.c#L319
I guess writing happens synchronously and after leaving the writing function data is in flash. In time adding entry into cache, data was already stored in flash.

> I don't see (in code) why it would only be added on the second write attempt: as soon as a name and name_id is written it is added. What I do see is that on every load the hash table is rebuild, might this be the cause of the slower second attempt ?

It would be added on the second write attempt because on the first attempt `settings_nvs` tries to find string that does not exist yet here: https://github.com/alxelax/zephyr/blob/setting_nvs_cache_improve/subsys/settings/src/settings_nvs.c#L231-L251
Since the string does not exist yet, the loop cannot overcome this condition: https://github.com/alxelax/zephyr/blob/setting_nvs_cache_improve/subsys/settings/src/settings_nvs.c#L249-L251
but adding to cache happens right behind this condition here: https://github.com/alxelax/zephyr/blob/setting_nvs_cache_improve/subsys/settings/src/settings_nvs.c#L255

Cache is left empty on the first writing attempt, since writing loop is left here: https://github.com/alxelax/zephyr/blob/setting_nvs_cache_improve/subsys/settings/src/settings_nvs.c#L234 for every new entry. That means on the second attempt, `setting_nvs` has to go over all stored entries in NVS application table to find the string and to build the cache table. This is the reason the second attempt takes so bad performance time.

**Comment by Laczen** [comment]
@alxelax I see, indeed only the second time a save is done it will be added to the cache.

I wonder if we shouldn't just move lines 254-256 to line 324 and always update the cache table.

**Comment by alxelax** [comment]
@Laczen,
> 
> I wonder if we shouldn't just move lines 254-256 to line 324 and always update the cache table.

yep, sounds reasonable but moving this at the end of the function. Somewhere here: https://github.com/alxelax/zephyr/blob/setting_nvs_cache_improve/subsys/settings/src/settings_nvs.c#L327

I'll update PR

**Review by Laczen — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

**Review by LingaoM — APPROVED** [review]

**Pull request merged**
