### PR TITLE
soc: it8xxx2: enable CONFIG_UART_NS16550_WA_ISR_REENABLE_INTERRUPT

### PR DESCRIPTION
**Pull request by Dino-Li**
Fix issue where console get stuck.

Signed-off-by: Dino Li <Dino.Li@ite.com.tw>

---
This change is [Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39126)

### CODE REVIEW

**Review by fkokosinski — APPROVED** [review]
LGTM

**Review by henrikbrixandersen — APPROVED** [review]
A better description of the actual fix in the commit message would be nice.

**Review by brockus-zephyr — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GTLin08, @jackrosenthal, @katsuster, @keith-zephyr, @kgugala, @mgielda, @pgielda, and @sjg20)

**Review by brockus-zephyr — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/zephyrproject-rtos/zephyr/39126#-:-MlLoIIeAEbRRZgfEhx2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GTLin08, @jackrosenthal, @katsuster, @keith-zephyr, @kgugala, @mgielda, @pgielda, and @sjg20)

**Pull request merged**
