### PR TITLE
ci: fix broken microsoft repo

### PR DESCRIPTION
**Pull request by maass-hamburg**
temporary fix broken microsoft repo

https://github.com/microsoft/linux-package-repositories/issues/130

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by nashif** [comment]
what microsoft repo?

**Review by stephanosio — APPROVED** [review]
While a better fix would be [to (temporarily) get rid of the Microsoft products repository from the APT source list](https://github.com/microsoft/linux-package-repositories/issues/130#issuecomment-2074645171), this should do for now since it is only a temporary fix until Microsoft fixes their servers and we do not require any packages from `https://packages.microsoft.com/ubuntu/22.04/prod`.

**Comment by fabiobaltieri** [comment]
> what microsoft repo?

An Ubuntu mirror used by the github runners I guess, could we just wait out? Sounds pretty bad, would  be surprised if they fix longer than any routine github outage anyway.

**Comment by stephanosio** [comment]
> what microsoft repo?

Apparently GitHub runners have these Microsoft APT repositories added by default.

**Comment by stephanosio** [comment]
> could we just wait out?

Given that there are already over 20 PR runs affected by this and this will likely keep piling up, we would want a temporary fix in ASAP.

**Pull request merged**
