### PR TITLE
Development

### PR DESCRIPTION
**Pull request by scottwcpg**
The update contains four commits:
MEC1501 headers to ext/hal/microchip/mec
MEC1501 DTSI file to dts/arm/microchip
MEC1501 SoC folder/files to soc/arm/microchip/mec
MEC1501 board folder/files to boards/arm/mec15xxevb_assy6853
Hello world example can be built and prints out expected message on UART 0 of MEC1501 EVB.

### CODE REVIEW

**Comment by carlescufi** [comment]
@scottwcpg thanks for the PR and welcome. Since this seems to be a work in progress, I have taken the liberty to tag it as DNM (Do Not Merge).

**Comment by scottwcpg** [comment]
My apologies for this being pushed to zephyr instead of my fork at github.com/MicrochipTech/zephyr.  git remote -v shows I'm pointing to my fork but the push went here. I cloned MicrochipTech/zephyr and then ran west init -l zephyr/ and west update.  Could the west tool have changed something to cause my push to go here instead of my fork?

**Comment by aescolar** [comment]
@mbolivar , @carlescufi , @tejlmand : Please see comment above

**Comment by aescolar** [comment]
@scottwcpg If you did not intend for this PR to be sent upstream, I will then close it.

**Comment by mbolivar** [comment]
> Could the west tool have changed something to cause my push to go here instead of my fork?

West doesn't create pull requests, so I'm not sure how that could have happened, sorry.

**Pull request closed without merging**
