### PR TITLE
Kernel: Fix missing unlock when waiting memory

### PR DESCRIPTION
**Pull request by LingaoM**
Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

### CODE REVIEW

**Comment by LingaoM** [comment]
Did I understand it wrong?

**Review by stephanosio — CHANGES_REQUESTED** [review]
This change is simply wrong.

**Comment by stephanosio** [comment]
> Did I understand it wrong?

Yes, see `z_pend_curr` implementation.

**Comment by LingaoM** [comment]
> This change is simply wrong.

sorry for this

**Pull request closed without merging**
