### PR TITLE
drivers: adc: Add STM32L1X ADC support

### PR DESCRIPTION
**Pull request by takumiando**
Add ADC driver support for STM32L1X SoC series.

### CODE REVIEW

**Review by FRASTM — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Please rebase, following merge of #23285

**Comment by takumiando** [comment]
@erwango 
Thanks for your reviewing!
I modified my patch to `DT_INST` format.

**Review by erwango — CHANGES_REQUESTED** [review]
@takumiando, change is fine. Only issue is that it is not enabled on any board and then it can't be verified by sanitycheck (compilation or test).
If you're working on a board supported in zephyr tree, can you enable the support of ADC and check that `tests/drivers/adc/adc_api` is passing ?

**Comment by takumiando** [comment]
@erwango , I found that the commit 7b563f16356291e3bbb5397a8e26e9c6a244c039 disables to get ADC1 name from `DT_ADC_1_NAME`!
So we cannot pass `tests/drivers/adc/adc_api` and cannot enable `CONFIG_ADC_SHELL`.

Should we revert the changes to `dts_fixup.h` in 7b563f16356291e3bbb5397a8e26e9c6a244c039?

**Comment by takumiando** [comment]
@erwango , How about these changes?

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for taking the request into account.

So far, only ADC_1 is enabled, available on STM32 SoCs in zephyr.
So we can, for now, safely define:
#define ADC_DEVICE_NAME DT_INST_0_ST_STM32_ADC_LABEL
This will be valid until a board enables 2 adc instances and wants to run test only on the second instance.
So I'd prefer you use this and not revert the fixup changes.

**Comment by takumiando** [comment]
How about `adc_shell`?
Where should I define ADC device name in this case?
If I can ignore about this case, I will apply `#define ADC_DEVICE_NAME DT_INST_0_ST_STM32_ADC_LABEL` to `tests/drivers/adc/adc_api`.

**Comment by erwango** [comment]
> How about adc_shell?

Ah, I oversaw this one.  Ok, well that's fine for now, please keep your change as is.

**Review by erwango — APPROVED** [review]

**Comment by takumiando** [comment]
>Ah, I oversaw this one. Ok, well that's fine for now, please keep your change as is.

Okay.
We should think about generic device name in Zephyr.

**Comment by erwango** [comment]
> We should think about generic device name in Zephyr.

True. This is valid for all peripherals, we need to define a mechanism (likely based on dts aliases).

**Review by galak — APPROVED** [review]

**Pull request merged**
