### PR TITLE
Bluetooth: Controller: Fix missing DTM Tx/Rx reset on HCI Reset Command

### LINKED ISSUE #39973: Bluetooth: hci_usb example returning "Unknown HCI Command" after reset.
**Describe the bug**
A hci_usb firmware built on the Zephyr 2.7.0 with DTM support (CONFIG_BT_TESTING) is used for DTM tests. After a reset of the hardware a transmitter test can be started with the "LE Transmitter Test" command. When this running test is stopped with a "Controller Reset" (instead of a regular test termination) the next start of a test returns "Unknown HCI Command".

**To Reproduce**
1. Extend configuration for hci_usb sample with DTM support
2. Build project and flash it to a nrf52840dk board.
3. Initiate a "LE transmitter Test" command
4. Reset by a "Reset Controller" command
5. Initiate a 2nd "LE transmitter Test" command
6. See error

**Expected behavior**
It is expected that a DTM test may be restarted normally after a controller reset.

**Impact**
annoyance

**Logs and console output**
I've recorded the HCI communication and stored it to a cfa file for wireshark:
[HCI-Log.zip](https://github.com/zephyrproject-rtos/zephyr/files/7456058/HCI-Log.zip)

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain Zephyr SDK
 - Version 2.7.0

### PR DESCRIPTION
**Pull request by cvinayak**
Fix missing implementation to reset DTM Tx/Rx reset on HCI
Reset Command.

Fixes #39973.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by thoh-ot — APPROVED** [review]

**Comment by AdrianEggenberger** [comment]
The fix solves the issue with the reset. So the issue #39973 can be fixed by the PR.

May I add a question here that is related to the issue? The error "UnknownHciCommand" is reported when the ll layer has already a test running. This is still the case if we start the test twice in a row. Shouldn't the returned error value be another error value?

**Comment by cvinayak** [comment]
> May I add a question here that is related to the issue? The error "UnknownHciCommand" is reported when the ll layer has already a test running. This is still the case if we start the test twice in a row. Shouldn't the returned error value be another error value?

I have added a new commit to this PR to return different error codes.

**Comment by AdrianEggenberger** [comment]
Now in case of two test start in a row the second fails with "CommandDisallowed" what seems to make sense.
The changes look fine for me.

**Comment by cvinayak** [comment]
@AdrianEggenberger as I work remote and have no access to RF tester, there has not been much enhancements to DTM implementation, please feel free to contribute enhancements related to latest BT Specification updates.

**Review by Thalley — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
