### PR TITLE
sanitycheck: Add exception check

### LINKED ISSUE #30752: ARC: passed tests marked as failed when running sanitycheck on nsim_* platforms
**Describe the bug**

The 531fe89e80f859d9bc820418059cec93463e0539 commit of #28372 causes regression for ARC.
When we running sanitycheck on nsim_* platforms we get some exception from sanitycheck code and mark test as FAILED however it successfully passed.

Here is an example on exception:
```
Exception in thread Thread-15603:
Traceback (most recent call last):
  File "/home/paltsev/CodeData/zephyr/zephyr-arc-64/zephyr/scripts/sanity_chk/sanitylib.py", line 496, in _output_handler
    proc.wait(0.1)
  File "/usr/lib64/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib64/python3.7/subprocess.py", line 1645, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['make', 'run']' timed out after 0.1 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/paltsev/CodeData/zephyr/zephyr-arc-64/zephyr/scripts/sanity_chk/sanitylib.py", line 498, in _output_handler
    self.terminate(proc)
  File "/home/paltsev/CodeData/zephyr/zephyr-arc-64/zephyr/scripts/sanity_chk/sanitylib.py", line 456, in terminate
    os.kill(child.pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process

ERROR   - nsim_em                   tests/kernel/mutex/sys_mutex/system.mutex          FAILED: Failed
ERROR   - see: /home/paltsev/CodeData/zephyr/zephyr-arc-64/zephyr/sanity-out/nsim_em/tests/kernel/mutex/sys_mutex/system.mutex/handler.log
```

In the `tests/kernel/mutex/sys_mutex/system.mutex/handler.log` everything looks OK:
```
 [-snip-]
[100%] Built target zephyr_final
Scanning dependencies of target run
Console now belongs to UART, hit CRTL-] to return to simulator.
*** Booting Zephyr OS build zephyr-v2.4.0-1942-g531fe89e80f8  ***
Running test suite mutex_complex
===================================================================
START - test_mutex
START - Test kernel Mutex API
===================================================================
Done LOCKING!  Current priority = 5
Testing recursive locking
Recursive locking tests successful
 PASS - test_mutex
===================================================================
START - test_user_access
E: syscall check_sys_mutex_addr failed check: Memory region 0x80000c08 (size 4) write access denied
E: syscall check_sys_mutex_addr failed check: Memory region 0x80000c08 (size 4) write access denied
 PASS - test_user_access
===================================================================
START - test_supervisor_access
 PASS - test_supervisor_access
===================================================================
Test suite mutex_complex succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```
The tests fail randomly. Usually 2-9 tests fail for nsim_em for each sanitycheck run.

**To Reproduce**
Lunch sanitycheck for nsim_em with toolchain usage from Zephyr SDK.
```
./scripts/sanitycheck --platform nsim_em
```

**Impact**
The random failing of tests on nsim_* platforms block it usage in verification.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.11.4 (same situation with 0.12.0-beta-1)
 - nSIM: 2020.09 (same situation 2020.06)
 - Commit: 531fe89e80f859d9bc820418059cec93463e0539 (or later)

### PR DESCRIPTION
**Pull request by wangnuannuan**
Add exception check for psutil when running CI with nSIM

Fixes #30752

Signed-off-by: Jingru Wang <jingru@synopsys.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by abrodkin** [comment]
Would be good to have more details on why that situation happens in the first place. Otherwise we are just masking some real problem.

**Comment by wangnuannuan** [comment]
This exception happens when the testcase failed, but not all failed tests cause this exception.
Here I print the children processes information before killing them. The log shows that child process `nsimdrv` has become a zombie process, so parent process can't terminate it by calling `proc.wait(0.1)`, so kill command doesn't apply to it.
```
INFO    - Total complete:   52/  86  60%  skipped:   23, failed:   26
 ./sanity-out/nsim_em/tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random - psutil.Process(pid=4616, name='make', status='sleeping', started='05:49:40')
 ./sanity-out/nsim_em/tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random - psutil.Process(pid=4626, name='make', status='sleeping', started='05:49:41')
 ./sanity-out/nsim_em/tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random - psutil.Process(pid=5178, name='make', status='sleeping', started='05:49:47')
 ./sanity-out/nsim_em/tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random - psutil.Process(pid=5179, name='nsimdrv', status='zombie', started='05:49:47')
 Exception in thread Thread-402:
 Traceback (most recent call last):
   File "./zephyr/scripts/sanity_chk/sanitylib.py", line 501, in _output_handler
     proc.wait(0.1)
   File "/depot/Python/Python-3.7.0/lib/python3.7/subprocess.py", line 971, in wait
     return self._wait(timeout=timeout)
   File "/depot/Python/Python-3.7.0/lib/python3.7/subprocess.py", line 1593, in _wait
     raise TimeoutExpired(self.args, timeout)
 subprocess.TimeoutExpired: Command '['make', 'run']' timed out after 0.1 seconds
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/depot/Python/Python-3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
     self.run()
   File "/depot/Python/Python-3.7.0/lib/python3.7/threading.py", line 865, in run
     self._target(*self._args, **self._kwargs)
   File "./zephyr/scripts/sanity_chk/sanitylib.py", line 503, in _output_handler
     self.terminate(proc)
   File "./zephyr/scripts/sanity_chk/sanitylib.py", line 458, in terminate
     os.kill(child.pid, signal.SIGTERM)
 ProcessLookupError: [Errno 3] No such process

 stty: standard input: Inappropriate ioctl for device


 ERROR   - nsim_em                   tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random FAILED: Failed
 ERROR   - see: ./sanity-out/nsim_em/tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random/handler.log
```

And the `try-exception` doesn't affect sanitycheck's judgment of test result, because the test result have been obtained before it is called.

**Review by abrodkin — CHANGES_REQUESTED** [review]
Good explanation posted above! May we have it merged in the commit message (so that it gets also visible at the justification of this PR)?

@evgeniy-paltsev looks reasonable? Pls review and ack/nack.

**Comment by evgeniy-paltsev** [comment]
Fixies: #30752

**Comment by evgeniy-paltsev** [comment]
@wangnuannuan could you please update the commit message, so we can have it merged ASAP?
Thanks!

PS: haven't notice that it actually addresses the current issue with random failures on nsim_* platforms and not the issue with exception with pid file missing (which has been already fixed)

**Review by evgeniy-paltsev — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]
Adding error messages in the commit message don't hurt while allowing for retrospective analysis. But OK now it's better than it was and we need it to get sensible results, so we're good to go now.

**Pull request merged**
