### PR TITLE
arch/xtensa: Fix return context for nested interupts

### PR DESCRIPTION
**Pull request by andyross**
The xtensa interrupt return path was forgetting to check the nested interrupt state and calling into the scheduler to select the context to which to return, which of course is completely wrong.  We MUST return to the ISR we interrupted.

In fact in practice this was only visible in the case of a nested interrupt that causes a context switch, otherwise the "interrupted" argument just gets returned and things work.  In particular, it can happen when the nested context is a fatal exception that aborts the current thread, which is how this was discovered.  The timing required to see this on live interrupts on real applications is likely to have been extremely difficult to detect.

### CODE REVIEW

**Comment by andyross** [comment]
Fix for the nested interrupt return bug.  Took a little puzzling to figure out how to write a test case for this, but I had a cute idea that works (even on qemu) and shows the problem.  Classic bisection cycle though: people will just have to take me on faith that the test in the SECOND patch here does indeed fail on xtensa (it blows up and times out) and that it's fixed by the FIRST.  Either that or pull it apart and hand-verify.

**Comment by andyross** [comment]
Should unblock #45570 though, please try

**Comment by andyross** [comment]
(And this is a good candidate for backporting, once merged.  Frequency is likely to be very low in real apps but severity is quite high.)

**Review by dcpleung — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by laurenmurphyx64 — APPROVED** [review]
Works like a charm with https://github.com/zephyrproject-rtos/zephyr/pull/45570! Thanks Andy!

**Comment by hongshui3000** [comment]
Thanks for solving this issue, I mentioned the issue I had last time. https://github.com/zephyrproject-rtos/zephyr/issues/40946

**Pull request merged**
