### PR TITLE
Add SO_PRIORITY support to setsockopt

### PR DESCRIPTION
**Pull request by jukkar**

### CODE REVIEW

**Review by pfalcon — CHANGES_REQUESTED** [review]
> Allow user to set the socket priority using setsockopt() call.

What is "socket priority"? Is it the order in which sockets are killed by OOM killer? 

Bottom line: Never head about SO_PRIORITY. Please explain in the commit message what it does and what standard defines it.

**Comment by pfalcon** [comment]
Beyond need for more detailed commit message, looks good, thanks.

**Comment by jukkar** [comment]
> Bottom line: Never head about SO_PRIORITY. Please explain in the commit message what it does and what standard defines it.

You could just either do "man socket" or do some interweb seach.
http://man7.org/linux/man-pages/man7/socket.7.html and search SO_PRIORITY

**Comment by pfalcon** [comment]
> You could just either do "man socket" 

If it's not clear, it's not about "me", it's about having clear, self-describing messages for the changes.

**Comment by jukkar** [comment]
Added more description to commit msg.

**Review by pfalcon — APPROVED** [review]
Thanks. Though some reference to existing docs for this option would be even better.

**Comment by jukkar** [comment]
recheck

**Comment by jukkar** [comment]
Rebased against latest upstream

**Pull request merged**
