### PR TITLE
Move Bluetooth controller tests to new ZTEST API

### PR DESCRIPTION
**Pull request by nashif**
- Bluetooth: tests: move ctrl_api to new ztest api
- Bluetooth: tests: move ctrl_chmu to new ztest api
- Bluetooth: tests: move ctrl_cis_create to new ztest api
- Bluetooth: tests: move ctrl_cis_terminate to new ztest api
- Bluetooth: tests: move ctrl_collision to new ztest api
- Bluetooth: tests: move ctrl_version to new ztest api
- Bluetooth: tests: move ctrl_unsupported to new ztest api
- Bluetooth: tests: move ctrl_tx_queue to new ztest api
- Bluetooth: tests: move ctrl_terminate to new ztest api
- Bluetooth: tests: move ctrl_tx_buffer_alloc to new ztest api
- Bluetooth: tests: move ctrl_le_ping to new ztest api
- Bluetooth: tests: move ctrl_invalid to new ztest api
- Bluetooth: tests: move ctrl_hci to new ztest api
- Bluetooth: tests: move ctrl_sca_update to new ztest api
- Bluetooth: tests: move ctrl_phy_update to new ztest api
- Bluetooth: tests: move ctrl_min_used_chans to new ztest api
- Bluetooth: tests: move ctrl_data_length_update to new ztest api
- Bluetooth: tests: move ctrl_encrypt to new ztest api

### CODE REVIEW

**Comment by kruithofa** [comment]
@nashif this seems a duplicate of PR #53099 where the tests are moved to the new ZTEST API and additional cleanup is done.

**Comment by nashif** [comment]
> I propose to close this PR, and keep all the cleanup to the unittests in PR #53099

why is it DNM and how can we unblock it?

**Comment by kruithofa** [comment]
> > I propose to close this PR, and keep all the cleanup to the unittests in PR #53099
> 
> why is it DNM and how can we unblock it?

NOTE: set to DNM until @tejlmand has had time to review

unblocking: I will rebase and address any comments that come

**Comment by nashif** [comment]
> unblocking: I will rebase and address any comments that come

please do, we need to deprecate old ztest API and right now bluetooth is one of the main remaining users. I will close this PR once I see movement on https://github.com/zephyrproject-rtos/zephyr/pull/53099

**Pull request closed without merging**
