### PR TITLE
MAINTAINERS: Add cfriedt as maintainer for FPGA drivers

### PR DESCRIPTION
**Pull request by cfriedt**
Add myself as maintainer for FPGA drivers.

Signed-off-by: Chris Friedt <cfriedt@meta.com>

### CODE REVIEW

**Comment by cfriedt** [comment]
Would be great to see some collaborators here as well.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by stephanosio** [comment]
cc @msierszulski

**Review by tgorochowik — APPROVED** [review]
Feel free to add me or @fkokosinski as collaborators to help us keep track of that. Adding @msierszulski should be okay too, but he might be unavailable a little bit more often

**Comment by cfriedt** [comment]
> Feel free to add me or @fkokosinski as collaborators to help us keep track of that. Adding @msierszulski should be okay too, but he might be unavailable a little bit more often

Will do with a follow-up PR

**Pull request merged**
