### PR TITLE
samples: cellular: fix dts overlay path

### PR DESCRIPTION
**Pull request by karthi012**
fix dtsi include path for board nrf9160dk_nrf52840

### CODE REVIEW

**Review by tomi-font — DISMISSED** [review]
Thanks!

**Comment by tomi-font** [comment]
@karthi012 While we're at it, do you mind making the same fix for `samples/bluetooth/hci_uart/boards/nrf9160dk_nrf52840.overlay` in this PR?

**Review by kartben — DISMISSED** [review]

**Comment by karthi012** [comment]
> @karthi012 While we're at it, do you mind making the same fix for `samples/bluetooth/hci_uart/boards/nrf9160dk_nrf52840.overlay` in this PR? (There it seems like both `.dtsi` includes would benefit from the added `nrf52840/`.)

Please have a look.

**Review by tomi-font — APPROVED** [review]
Perfect, thanks!

**Review by jukkar — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
