### PR TITLE
doc: update gsg with sdk v0.11.0

### PR DESCRIPTION
**Pull request by nashif**
We are now using 0.11.0, so update the getting started guide.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
Want to wait on this because there will be a SDK 0.11.1 shortly for 2 fixes:

1. openocd missed some patches for ARC and Zephyr awareness in a rebase
2. newlib change for syscall naming confusion [existed in 0.10.x as well, but would like to transition / fix for SDK 0.11.x]

**Review by tyrantlizard77 — APPROVED** [review]
we really ought to fix maintaining this information in two different files, they say the same thing

**Comment by nashif** [comment]
> Want to wait on this because there will be a SDK 0.11.1 shortly for 2 fixes:

eta?

**Comment by galak** [comment]
> eta?

Today / Monday.  Wanted to get a bit of testing on SDK 0.11.0 with CI to see if any other issues came up that needed fixing before trying to get SDK 0.11.1 out.

**Comment by nashif** [comment]
> Today / Monday. Wanted to get a bit of testing on SDK 0.11.0 with CI to see if any other issues came up that needed fixing before trying to get SDK 0.11.1 out.

ok. Btw, keeping it at 0.10.x is more problematic because of all the platform support that we added which depends on 0.11.0. Not everyone uses open-ocd or newlib. So we could now move to 0.11.0 to encourage people to move away from old 0.10.3 and update to 0.11.1 when it is released. my 2 cents.

**Comment by galak** [comment]
I've pushed out SDK 0.11.1 if you want to update this, as well as this PR #22416, which makes SDK 0.11.x required.

**Comment by nashif** [comment]
> I've pushed out SDK 0.11.1 if you want to update this, as well as this PR #22416, which makes SDK 0.11.x required.

I am adding this commit to #22416

**Pull request closed without merging**
