### PR TITLE
bluetooth: host: Expose structs and prototypes in public headers

### PR DESCRIPTION
**Pull request by jrth**
In order for custom settings backends to be able to extract settings
values for efficient storage, expose structs from keys.h and gatt.c, as
well as bt_settings_encode_key and bt_settings_decode_key prototypes.

Signed-off-by: Jens Rehhoff Thomsen <jrth@oticon.com>

### CODE REVIEW

**Comment by Vudentz** [comment]
The backend is not supposed to know about these details, at least not a generic one, are you guys trying to change the format or something?

**Review by jhedberg — CHANGES_REQUESTED** [review]
I had the same reaction as @Vudentz - custom settings backends (i.e. those implementing `struct settings_store_itf`) should not know anything about the specific content or structure of data that's stored.

If you're looking to use something else than the settings subsystem we'd need to do a more substantial refactoring so that the exact choice of storage is abstracted away from the stack. Btw, I don't see you covering Mesh in any way in this PR, i.e. it looks incomplete to me from that perspective as well.

**Comment by jrth** [comment]
Yes we need this change to support our legacy format. The other thing is that it will help us fulfill our strong memory constraints by having the opportunity not to store unnecessary ccc information.

**Comment by Vudentz** [comment]
> Yes we need this change to support our legacy format. The other thing is that it will help us fulfill our strong memory constraints by having the opportunity not to store unnecessary ccc information.

What unnecessary information, we could fix that but afaik we just have the handle and value stored per ccc.

**Comment by jhedberg** [comment]
> Yes we need this change to support our legacy format. The other thing is that it will help us fulfill our strong memory constraints by having the opportunity not to store unnecessary ccc information.

It'd be good to start off with what exactly your requirements are. I.e. describe in more detail what your format is, what info you want to store, what you don't want to store etc. It's also unclear to me if this is at all related to the settings subsystem, or if you're doing something incompatible/independent with it.

**Comment by fnde-ot** [comment]
As Jens mentioned, our most important requirement is to be able to load/store data from/to our own custom legacy format, that is also used by many of our external tools.

This format is designed to save space as to comply with storage size requirements. For example in our use-case we do not need to store both master and slave LTK in legacy pairing as we do not care about role reversal. Another example is that we only store the value of the CCC in a specific array position and use the index to derive the handle.

**Comment by jhedberg** [comment]
@fnde-ot ok, thanks for clarifying. To do something like that properly/cleanly I can think of two possible options:

 1. Create a proper abstraction for the storage rather than directly depending on settings. That way you can make your own backend that can do the translation you need.
2. Divorce `bt_keys` from the storage format and instead create a more optimised version based on what you need. What you describe could make more generally sense than just for your product needs, and we could e.g. have a Kconfig option or similar to state that we only ever want to store one of the LTK roles. In fact, perhaps we can do this without any new options, e.g. so that we don't store the slave role key if `CONFIG_BT_PERIPHERAL` is not enabled?

Out of the above the second option would be the least amount of effort, and would benefit other users of the stack as well.

**Comment by jhedberg** [comment]
Just to follow-up on my previous comment, maybe a separate storage format isn't needed if we add some more `#ifdef`s based on configured features.

**Comment by fnde-ot** [comment]
I agree that things could definitly be optimized (option 2) for generic use-cases and it could be ground for another PR. Unfortunately it still would not fit with our use-case where we have to use a custom format under our control, that multiple external tools depend on.

We could however work with option 1 and have another abstraction where we could plug-in a custom out-of-tree backend plugged into the host layer that would have access to the internal structure defs to do this kind of translation. We just thought that the settings subsystem with custom-backends was actually meant to be this abstraction.

Another requirement I forgot to mention would be to be able to inject keys (using settings_runtime_set) from the application into the host layer without having to perform a real pairing. This PR would also allow for that to happen!

Is it that bad for the application layer to have access to settings content format?

**Comment by jhedberg** [comment]
>  We just thought that the settings subsystem with custom-backends was actually meant to be this abstraction.

To my understanding the data passed to/from the settings backends is opaque (i.e. essentially just byte arrays), meaning the specific content and structure is not exposed there. Perhaps I've misunderstood something - maybe @nvlsianpu can correct me if I'm wrong about this (please see the full discussion above)

**Comment by jhedberg** [comment]
@fnde-ot what we could consider doing though is add a layer between settings and Bluetooth. I.e. settings stays as the ultimate backend, but we add a translation layer between it and the runtime structs of the Bluetooth stack.

**Comment by fnde-ot** [comment]
@jhedberg, @nvlsianpu, Yes the data passed to/from the settings backend is opaque, we however can derive data format from the key (fx. "bt/keys/..." will have data formatted as "struct bt_keys"). Exposing those structs would allow for more 'intelligent' backends.

@jhedberg, This is a valid option indeed, it would however introduce additional complexity and maintenance cost, for example when adding new features such as 'on-demand loading' of some of the settings to save memory.

**Comment by Vudentz** [comment]
>  Another example is that we only store the value of the CCC in a specific array position and use the index to derive the handle.

That would only work static database since with dynamic database the CCC position can change at runtime.

Im curius how it would be more compact than the current format since you need the index would be up to the last database handle, or it is the CCC position based on the UUID lookup, even in case you would have to maintain non-configure CCCs on the array so depending on how many the peer is actually setting it would not save anything comparing to handle+value tuples.

**Comment by fnde-ot** [comment]
@Vudentz Indeed we store unsubscribed entries as well, space savings depend on typical use-case (if typical clients subscribe to most CCCs).

In any case, I don't really see a reason to why we should not expose those structs since settings backends can now be part of the application. It would be a nice feature to allow those backends to translate contents, or to allow the application to craft and inject custom settings using setting_runtime interface.

**Comment by Vudentz** [comment]
> @Vudentz Indeed we store unsubscribed entries as well, space savings depend on typical use-case (if typical clients subscribe to most CCCs).

With a dynamic db that means we would have to switch left and right the number of entries and the database changes, so complexity would increase quite a lot.

> In any case, I don't really see a reason to why we should not expose those structs since settings backends can now be part of the application. It would be a nice feature to allow those backends to translate contents, or to allow the application to craft and inject custom settings using setting_runtime interface.

In the other hand should tools such that you are proposing exists in a forma of open source, I mean we should concentrate in mainting these tools to manipulate the settings format used upstream and we do these changes to promote companies doing their on format on top we will never advance with such tools. These tools could then have translation between old/proprietary format to the latest format.

**Comment by fnde-ot** [comment]
> With a dynamic db that means we would have to switch left and right the number of entries and the database changes, so complexity would increase quite a lot.

I agree, that is why we do not want to upstream our custom storage format, rather just have the possibility of making such translations specific to our use-case and constraints.

> In the other hand should tools such that you are proposing exists in a forma of open source, I mean we should concentrate in mainting these tools to manipulate the settings format used upstream and we do these changes to promote companies doing their on format on top we will never advance with such tools. These tools could then have translation between old/proprietary format to the latest format.

Not sure what you mean about tools, I just think it would be nice for a settings backend registered in the application layer to understand the content of settings in case such backend needs to do some translation. :-)

**Comment by jhedberg** [comment]
>  I just think it would be nice for a settings backend registered in the application layer to understand the content of settings in case such backend needs to do some translation

A settings backend having knowledge what the content behind a certain key is kind of breaks the encapsulation layers, I think, and goes beyond purpose of settings backends. IMO a more appropriate place for such translation should be above settings (i.e. between settings and Bluetooth in this case). It'd be good to hear some opinion from the settings developers on this, e.g. @nvlsianpu  @kapi-no and @Laczen.

**Comment by Laczen** [comment]
I don't think there is something against using extra information in the backend. As long as the translation between the backend data storage and the variable name - value pair is done OK. A custom backend could IMO decide not to store anything (and to always load standard value), this is up to the designer of the custom backend.
However I am not sure this translation needs to expose all structs and prototypes. Could this not be done by including the required header files in the custom backend ? It seems to be a very specific use case.

**Comment by fnde-ot** [comment]
> However I am not sure this translation needs to expose all structs and prototypes. Could this not be done by including the required header files in the custom backend ? It seems to be a very specific use case.

We are unfortunately not allowed to include internal headers in our application where our backend is located (Zephyr is considered as SOUP for us).

**Comment by Vudentz** [comment]
> > With a dynamic db that means we would have to switch left and right the number of entries and the database changes, so complexity would increase quite a lot.
> 
> I agree, that is why we do not want to upstream our custom storage format, rather just have the possibility of making such translations specific to our use-case and constraints.
>
> > In the other hand should tools such that you are proposing exists in a forma of open source, I mean we should concentrate in mainting these tools to manipulate the settings format used upstream and we do these changes to promote companies doing their on format on top we will never advance with such tools. These tools could then have translation between old/proprietary format to the latest format.
> 
> Not sure what you mean about tools, I just think it would be nice for a settings backend registered in the application layer to understand the content of settings in case such backend needs to do some translation. :-)

If I got the problem right the thing you are trying to accomplished is to be able to upgrade a non-zephyr image to a zephyr one, that can be accomplished by in the first boot detecting that it is an old/proprietary format then converting it to zephyr one, one could even do this as part of firmware downloading phase so you don't have to carry this over indefinately which adds overhead in terms of code size vs some possible saving on flash which you apparently agree is marginal and adds a lot more complexity.

If we agree to concentrate on one format that means we can have tools to manage the settings i.e. create a facture reset image, injecting paired devices into the settings or mounting the setting  changing it, etc.

**Comment by fnde-ot** [comment]
> If I got the problem right the thing you are trying to accomplished is to be able to upgrade a non-zephyr image to a zephyr one

@Vudentz Not really, we're trying to make Zephyr work with our own storage format because our requirements make it impossible to use a generic storage format that works for all use-cases.

@jhedberg Fair enough, let's wait for opinions from settings developers. We are open to consider another approach if exposing storage format is considered harmful.

**Comment by Vudentz** [comment]
> > If I got the problem right the thing you are trying to accomplished is to be able to upgrade a non-zephyr image to a zephyr one
> 
> @Vudentz Not really, we're trying to make Zephyr work with our own storage format because our requirements make it impossible to use a generic storage format that works for all use-cases.

Are these requirement captured somewhere?

**Comment by Laczen** [comment]
> > However I am not sure this translation needs to expose all structs and prototypes. Could this not be done by including the required header files in the custom backend ? It seems to be a very specific use case.
> 
> We are unfortunately not allowed to include internal headers in our application where our backend is located (Zephyr is considered as SOUP for us).

@fnde-ot, If you want to get to the tasty meatballs in the soup you have to eat it :grinning:

**Comment by nvlsianpu** [comment]
@fnde-ot  @jhedberg I relay think that custom back-end support is something you should use. Maybe some capability is missing in the settings API (tell me what). If we need a layer between settings and bt_setting (as your storage is not really compatible, so making a back-end doesn't make any sense) we can consider it, especial if it is possible to reduce overhead (nearly) zero if settings is chosen.

I fill I don't know what is the question to be answered by me after whole conversation - feel free to ask me right questions :D

**Comment by nvlsianpu** [comment]
BTW @fnde-ot setting has API for subtree loading.

**Comment by fnde-ot** [comment]
@nvlsianpu The specific question is whether you think it is a good idea to expose settings storage format (as proposed in this PR) for custom settings backends to be able to extract content and translate it to another format.

The drawback would be that it kind of breaks encapsulation layers, so instead maybe a new layer should be added above settings to perform such translation.

**Comment by fnde-ot** [comment]
Nice feature!

Note that if a custom settings backend had the ability to decode settings contents, it could implement its own algorithm to discard settings considered unimportant and make room for new storage. For example maybe you have pairing data that you should never remove, however old they might be.

See: https://github.com/zephyrproject-rtos/zephyr/pull/19242

**Comment by fnde-ot** [comment]
Please vote on whether you think this PR is a good idea or not.

In the latter case, we can close this PR, regroup and think about another approach to solve our problem! :)

**Comment by carlescufi** [comment]
@joerchan, @nvlsianpu, @rakons and @MarekPieta could you please voice your opinion?

**Review by Laczen — APPROVED** [review]

**Review by rakons — APPROVED** [review]

**Comment by joerchan** [comment]
I'm fine with this approach to expose the structures to allow the application control over the bond storage. 
It would be helpful to add documentation so that the user can properly understand what all this is and how it should use it.
For example how should a new key be added to the stack, how can it properly react to a newly created bond or a bond that has been erased?

**Comment by jrth** [comment]
Based on the comments I will close this PR and maybe come up with a more clean approach in another PR.

**Pull request closed without merging**
