### PR TITLE
test: schedule_api : add error test

### PR DESCRIPTION
**Pull request by yingmingx**
Add error test of api in sched.c to improve
branch and line coverage.

Signed-off-by: Ying ming <mingx.ying@intel.com>

### CODE REVIEW

**Review by enjiamai — CHANGES_REQUESTED** [review]
The common fatal and assert handler has been merged, could you please leverage them instead? thanks!  
please refer to https://github.com/zephyrproject-rtos/zephyr/pull/30150

**Review by LeiW000 — CHANGES_REQUESTED** [review]
As Enjia said, please remove the code related to test assert().

**Comment by yingmingx** [comment]
> The common fatal and assert handler has been merged, could you please leverage them instead? thanks!
> please refer to #30150

Hi, enjia. All the assert related code have been removed and fatal framework have been used. Please help to give another look, thanks.

**Comment by yingmingx** [comment]
> As Enjia said, please remove the code related to test assert().

Hi, Steven. All the assert related code have been removed. Please help to give another look, thanks.

**Review by enjiamai — CHANGES_REQUESTED** [review]
Hi, could you please put the test cases into schedule_api testsuite,  try to not add a new testsuite for it.

**Comment by yingmingx** [comment]
Close this PR because the content is merge in https://github.com/zephyrproject-rtos/zephyr/pull/31218.

**Pull request closed without merging**
