### PR TITLE
Cleanup Zephyr L2 wifi header files

### PR DESCRIPTION
**Pull request by kapbh**
The header file contains mixture of functions (to get user friendly name) and static arrays. Replacing functions and static arrays to extern arrays. Initialize arrays in C file.

### CODE REVIEW

**Review by jukkar — CHANGES_REQUESTED** [review]
Overall this is a good idea but I would prefer we do it a little bit differently.

So instead of exposing the string arrays directly, create a function that returns the string that corresponds to the enum value like this:

In wifi.h have this (with the other functions and also documentation for them):
```
const char * const wifi_security2str(enum wifi_security_type security);
```
Then the corresponding implementation in .c:
```
const char * const wifi_security2str(enum wifi_security_type security)
{
	switch (security) {
	case WIFI_SECURITY_TYPE_NONE:
		return "OPEN";
	case WIFI_SECURITY_TYPE_WEP:
		return "WEP";
	case WIFI_SECURITY_TYPE_WPA_PSK:
		return "WPA-PSK";
	case WIFI_SECURITY_TYPE_PSK:
		return "WPA2-PSK";
	case WIFI_SECURITY_TYPE_PSK_SHA256:
		return "WPA2-PSK-SHA256";
	case WIFI_SECURITY_TYPE_SAE:
		return "WPA3-SAE";
	case WIFI_SECURITY_TYPE_WAPI:
		return "WAPI";
	case WIFI_SECURITY_TYPE_EAP:
		return "EAP";
	case WIFI_SECURITY_TYPE_UNKNOWN:
	default:
		return "UNKNOWN";
}
```
So basically what we had earlier but not inlining the functions in header file.

**Comment by krish2718** [comment]
@jukkar Regarding enum's vs. const array, my preference was enum's, same as you,but based on https://github.com/zephyrproject-rtos/zephyr/pull/52166#discussion_r1030241734 modified it to const array. I still prefer enum's but just pointing out the history.

**Comment by jukkar** [comment]
Please change the code to use the enum + function (non inline one). We are using that design patter in networking currently so the wifi code should follow suit.

**Review by jukkar — APPROVED** [review]
Thanks, LGTM!

**Review by krish2718 — APPROVED** [review]

**Pull request merged**
