### PR TITLE
soc: xtensa: fix the direct usage of log only and loading firmware

### PR DESCRIPTION
**Pull request by enjiamai**
The new client-server-based cavstool has broken the SOF CI testing
due to not considering that loading firmware and output log directly
without daemon is still necessary. Fix that when it is not running
as a daemon.

Signed-off-by: Enjia Mai <enjia.mai@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Can you please also restore the old filename / full backward compatibility?

**Comment by marc-hb** [comment]
This new client-server approach implemented in #44188 makes a lot of sense when using  `twister`, in fact this is exactly what I felt was missing when I tried to use twister to run ADSP tests a long time ago (and then gave up and went back to testing SOF only...) No one wants to have a Zephyr workspace duplicated on each test system; great job @enjiamai .

However this client-server, "embedded" development model does not make sense for a SOF and https://github.com/thesofproject/sof-test  because:
- SOF is loaded from `/lib/firmware/` by the Linux kernel
- SOF testing requires deploying other files to the test system (dictionary, various binaries,...)
- sof-test does not run remotely, it's installed directly on the test system and run entirely on it.

For the reasons above, SOF already has some various SOF-specific tools to deploy more than just the firmware to test systems.

While SOF test systems are usually not a good place to write and compile code, most of them are running a full-blown Linux Operating System and it would be inconvenient and a waste to treat that OS on SOF test systems as a limited, "embedded" OS and not to take advantage of it to run tests. Even ChromeOS has enough code to run sof-test! https://github.com/thesofproject/sof-test/issues/576

So I think we really need BOTH models: the client/server approach for `twister` and the sof-test approach where `cavstool.py` is invoked directly and locally on a firmware that has already been loaded. I have not tested this PR but it goes in the right direction, thanks.

cc: @dbaluta , @cujomalainey

**Review by marc-hb — APPROVED** [review]
I have cherry-picked this PR locally and it fixes SOF testing for me. I don't understand the new code yet to review it but I'm approving anyway because this PR is extremely likely to fix SOF CI.

Please help review this urgently.

**Review by yerabolu — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by kv2019i** [comment]
Thanks @enjiamai and @marc-hb !

**Pull request merged**
