### PR TITLE
[RFC] [DNM] Onoff canceling in progress and notifier updates

### PR DESCRIPTION
**Pull request by nordic-krch**
Extended onoff to be capable of canceling requests/releases at any point, for any client.
After this change, cancel behave the same way for each client. By now, last client was left in the difficult position since his operation could not be cancelled.
It supports also double cancellation (cancellation of cancellation).
There is always at least one client to notify about operation error.

With this feature, implementation of notifier becomes trivial. Updated notifier.

Modified notifier API to always return result through callback and aligned tests.

Notifier tests are passing after this change. On another branch (with onoff from master) there are tests for onoff cancelation extension which are passing.

This PR in this form is not intended to be merged, it's only for discussion.

Note: notifier implementation is in draft case (e.g. atomic flags access missing, etc.), mainly to showcase capabilities of onoff cancel feature.

### CODE REVIEW

**Comment by nordic-krch** [comment]
@pabigot can you take a look at what i've done in onoff cancellation. I think that i got reliable solution when it comes to cancelling operations at any time with the same behavior for each client (no -EWOULDBLOCK for last client). This simplifies a lot the notifier. I've added draft implementation.

Tests for onoff cancellation are here (https://github.com/zephyrproject-rtos/zephyr/pull/23087/commits/f4e0f984c7d5967858a111bb1001c5d3cf9133d0) where they are implemented on onoff from master.

With this change, i believe that functions for cancelling ongoing request and release are not necessary.

**Comment by pabigot** [comment]
> @pabigot can you take a look at what i've done in onoff cancellation. I think that i got reliable solution when it comes to cancelling operations at any time with the same behavior for each client (no -EWOULDBLOCK for last client). This simplifies a lot the notifier. I've added draft implementation.

I'm skeptical of this whole approach, but setting that aside:

The onoff test fails three cases.  Please make it work then I'll look more.  Coverage should be comparable to the original.

**Comment by pabigot** [comment]
The implementation breaks with this sequence:

* An onoff service is off.
* Client A initiates a transition to on via cliA.  The service enters TO_ON and adds cliA to the clients list.
* Client A cancels the cliA transition.  The cliA reference moves from the clients list to releaser and is flagged as cancelling.
* Client B initiates a transition to on via cliB.  The service is in TO_ON, and cliB is added to the clients list.
* Client B cancels the cliB transition.  The cliA references moves from the clients list to releaser, overwriting cliB which was stored there, and is flagged as cancelling.

At this point the clients list is empty, releaser points to cliB, and the service has lost cliA which will never be notified.

I don't know whether this can be fixed; I don't understand exactly what you're trying to do or what semantics you want for cancelled operations.  I do like the fact you're not attempting to actually abort the in-progress transitions anymore, but instead maintain state so that the reverse transition is synthesized automatically based on whether the cancelled operation is still recorded when the transition stops, rather like the notifier does.

If we give up on the goal of always having at least one client remaining to receive notification of transition failures, things can be simplified by removing the asymmetry between the clients and the single releaser.  Instead both request and release operations can be present in the client list, and are processed when the transition completes.  This avoids the problem above where releaser gets clobbered.  See #23512 for an implementation.

**Review by pabigot — COMMENTED** [review]
(This was specific to 9392a4ffac6cab534149098bd462136cbd3536a0 which replaces the `onoff_notifier` implementation:)

How can this be safe?  There's nothing that prevents a callback from manipulating the notifier `state` field while another thread is inspecting it in a request or release call.  Just adding a lock won't help because it'll have to be released so the core onoff API can be invoked, at which point you still need to check to see if other events occurred during the unlock period.

I understand that the notifier implementation in #23229 is complex, but I don't think it's any more complex than it has to be.  AFAICT supporting cancel does *not* make it simpler.

**Pull request closed without merging**
