### PR TITLE
kconfig: Drop support for CONFIG_TOOLCHAIN_VARIANT

### PR DESCRIPTION
**Pull request by SebastianBoe**
The Kconfig option TOOLCHAIN_VARIANT (not to be confused with
ZEPHYR_TOOLCHAIN_VARIANT) is a legacy configuration option that has
very few use-cases and can easily be dropped.

It's functionality is easily covered by CONFIG_X86_IAMCU and
ZEPHYR_TOOLCHAIN_VARIANT.

This commit removes all references of it from Zephyr.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by nashif** [comment]
what about the usage with xtensa? You are removing the configurations and providing no solution for those...

**Review by tyrantlizard77 — DISMISSED** [review]
This breaks the ability for the particular build of the XCC compiler to be selected unless I'm missing something.

**Comment by SebastianBoe** [comment]
> This breaks the ability for the particular build of the XCC compiler to be selected unless I'm missing something.

I can't see any support like this in-tree.

**Comment by SebastianBoe** [comment]
> what about the usage with xtensa? You are removing the configurations
> and providing no solution for those...
> 
-- @nashif 


There are no users in-tree, so this is a safe change for Zephyr, which
leaves users ...

AFAICT the purpose of TOOLCHAIN_VARIANT is for application code 
and build scripts to be Kconfigurable depending on the toolchain version.

The way this is implemented today doesn't make any sense because it
is the SoC and not the toolchain that is specifying the revision.

Since neither the mechanism or the name are well-suited I would
suggest we remove it and then re-introduce another more appropriately
named and implemented mechanism when the use-case resurfaces.

Alternatively, we could at least move the definition out of mainline
misc/Kconfig and into arch/xtensa to avoid confusing arm and x86 users
with a confusingly named (ZEPHYR_TOOLCHAIN_VARIANT vs. TOOLCHAIN_VARIANT) 
xtensa quirk.

**Comment by rgundi** [comment]
XCC currently uses an environment variable defined as TOOLCHAIN_VER to pick the tool chain version (like RF-2015.3-linux). So, this variable is analogous to TOOLCHAIN_VARIANT.  Can't recall why i used TOOLCHAIN_VER instead of reusing TOOLCHAIN_VARIANT though. Assuming TOOLCHAIN_VER is rechristened as TOOLCHAIN_VARIANT, I don't see any other architecture use this (as Xtensa is more of a soft core and each version of the core will have to only use the corresponding version of the toolchain).

**Comment by SebastianBoe** [comment]
@andrewboie : Please re-asses your review when convenient.

**Comment by nashif** [comment]
ok, i see now that is not being used and I also am fine removing this variable, because it does sound like ZEPHYR_TOOLCHAIN_VARIANT and might be confusing, but never liked the amount of env variables needed to build xtensa, so we need a cleaner way with less variables defined on the env.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
please rebase

**Comment by SebastianBoe** [comment]
rebased.

@andrewboie : Your review comment was addressed in https://github.com/zephyrproject-rtos/zephyr/pull/7274#issuecomment-385898030

please re-asses your review when convenient.

**Comment by SebastianBoe** [comment]
Will await for master to re-open before I rebase (again) as I assume this won't be merged into master during the release cycle.

**Comment by nashif** [comment]
> Will await for master to re-open before I rebase (again) as I assume this won't be merged into master during the release cycle.

why not? This is not a new feature, this is a fix. please rebase

**Pull request merged**
