### PR TITLE
dts: opentitan: update plic interrupt count to match spec

### PR DESCRIPTION
**Pull request by ngm0**
previously `184`, update to `182`, per:
https://opentitan.org/book/hw/top_earlgrey/ip_autogen/rv_plic/

### CODE REVIEW

**Comment by ngm0** [comment]
@snematbakhsh PTAL.

**Comment by snematbakhsh** [comment]
> @snematbakhsh PTAL.

LGTM (need to ask a maintainer for official approval though).

182 matches the current OT implementation: https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/ip_autogen/rv_plic/data/rv_plic.hjson#L40

Just a reminder that ndev = 182 actually means we have only 181 "real" interrupt sources because 0 is reserved (see https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic.adoc#4-interrupt-identifiers-ids). That aligns with the zephyr rv_plic driver and the OT implementation, but might confuse those who look at dts (13f8d809300299cb56abf763d289e0b2eec0d4dc seems like evidence of past confusion).

**Review by snematbakhsh — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Comment by ngm0** [comment]
@ycsin this patch could use review as well.

**Review by ycsin — APPROVED** [review]

**Comment by ycsin** [comment]
@ngm0  I don't think the CI failure is related to this PR, probably needs a rebase to fix

**Pull request merged**
