### PR TITLE
soc: sensry: udma, pad renaming

### PR DESCRIPTION
**Pull request by tswaehn**
Before that fix the names for UDMA could be misleading. With that fix the namespace is clear and easy to follow. Same applies for peripheral addresses and pad config.

### CODE REVIEW

**Comment by tswaehn** [comment]
dear @dcpleung would be great to understand if there is anything missing, or things that I should modify. 

big thanks in advance.

**Review by dcpleung — APPROVED** [review]

**Comment by tswaehn** [comment]
dear @fkokosinski,
Could you please check if there are things that need modifications?

Thank you in advance

**Comment by tswaehn** [comment]
@andyross , @teburd I would be happy to get feedback on what changes needed to get this PR approved. Could you spare some minutes on this?

thank you in advance.

**Comment by tswaehn** [comment]
dear @andyross 

this ticket is basically renaming in the drivers of our soc. its open for more than a month. I would be happy to understand if I need to change something that makes it accepting. thus it would be awesome if you could check and / or accept the changes.

**Comment by tswaehn** [comment]
I am stuck with this for 2 months. What cloud be the reason?

**Comment by tswaehn** [comment]
Is something missing?

Can we merge?

**Review by teburd — APPROVED** [review]
Really this should be 3 commits in my opinion, one for each area (uart, timer, soc). Not a blocker for me though.

**Comment by tswaehn** [comment]
> Really this should be 3 commits in my opinion, one for each area (uart, timer, soc). Not a blocker for me though.

understood, will do

**Pull request merged**
