### PR TITLE
boards: arm: apollo4p_evb Shield Support

### PR DESCRIPTION
**Pull request by RichardSWheatley**
Correct pinctrl for rev2 board.
Rename IOM to SPI in ambiq_apollo4p.dtsi

### CODE REVIEW

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Please split the sensor changes and apollo board changes into separate commits

**Comment by RichardSWheatley** [comment]
> Please split the sensor changes and apollo board changes into separate commits

You want me to put the 5 lines of one sensor change on a separate pull request?

**Comment by RichardSWheatley** [comment]
> Please split the sensor changes and apollo board changes into separate commits

Removed Sensor changes from this pull request altogether.

**Review by MaureenHelm — DISMISSED** [review]

**Comment by RichardSWheatley** [comment]
> Please split the sensor changes and apollo board changes into separate commits

@MaureenHelm 

Again, thanks for the assistance!

I will take the time to reread the docs on pull requests and issues.

I have also just found the Discord chats for questions prior to pull requests.

**Comment by RichardSWheatley** [comment]
Can we please get some eyes on this?
With sugar on top!

**Review by MaureenHelm — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]
LGTM

**Pull request merged**
