### PR TITLE
1.9.1 fixes for the BLE Controller

### PR DESCRIPTION
**Pull request by carlescufi**

### CODE REVIEW

**Comment by carlescufi** [comment]
@cvinayak please review the commit list against https://github.com/zephyrproject-rtos/zephyr/milestone/8?closed=1 to double-check

**Comment by carlescufi** [comment]
@nashif please don't merge until we've run EBQ against this branch, I will update here

**Comment by cvinayak** [comment]
Commit list looks good to me. Will wait for EBQ results.

**Review by cvinayak — APPROVED** [review]
No new issues seen so far in 8 iterations of EBQ tests.
Only, TP/CON/SLA/BV-12-C is failing which is to be fixed by EBQ team (EBQ-2621) in their next release.

**Comment by carlescufi** [comment]
@nashif ready to merge

**Pull request merged**
