### PR TITLE
drivers: intc: plic: workaround for non-zero `CONFIG_RV_BOOT_HART`

### LINKED ISSUE #65489: [RISC-V] drivers: intc_plic: Hardcodes enables interrupts for context 0 only, cannot enable interrupts on cores.
**Describe the bug**
Changes introduced in commits 8db1a5a, 0e6bef2 and 39433f06 hard code the values for irq enable offset for context 0 in the PLIC. This is a show stopper for multicore platforms that want to run a zephyr application on a single core, other than on the first core. A wider problem is that it only considers a single context to handle interrupts, but what about SMP applications?
 As an example, Polarfire SoC  utilizes the different contexts for the PLIC for the different modes (Machine, Supervisor ) such that
```
context 0 = hart 0 machine mode interrupt enables, 
context 1 = hart 1 machine mode interrupt enables,
context 2 = hart 1 supervisor mode interrupt enables
context 3 = hart 2 machine mode interrupt enables
.
.
.
context x = hart 4 supervisor mode interrupt enables
 ```

A previous solution for a single core application to run on, for instance a HART other than HART 0 was to use a devicetree overlay which describes the PLIC's registers. an example (for HART 1)
```
&plic {
	reg = <0x0c000000 0x00002000
			0x0c002080 0x001fe000
			0x0C201000 0x3e000000>;
};

```
The above would enable interrupts for HART 1 (PLIC context 1). However, this solution is now broken.

**To Reproduce**
For a multi core platform such as mpfs_icicle, compile any sample application that uses PLIC interrupts. in prj.conf, set CONFIG_RV_BOOT_HART=1 (or 2, 3, etc)
The PLIC will not service the interrupt

**Expected behavior**
Any given core in a multi core platform should have its interrupts enabled.

**Impact**
Show stopper

**Environment (please complete the following information):**
 - OS: Linux, 
 - Toolchain Zephyr SDK,  0.16.3
 - ad788ad51173c08dc237653df132d500b0e40d26

### PR DESCRIPTION
**Pull request by ycsin**
Before 39433f0669f1fd620f36605d1c3df61a6cf97ae2, it was possible to trick Zephyr into thinking that hart 1 is hart 0 by modifying the register base addresses.

Workaround that by using `CONFIG_RV_BOOT_HART` and offset that in the driver instead.

Fixes #65489

### CODE REVIEW

**Comment by con-pax** [comment]
Hi @ycsin,

Thanks for taking the time to try this. I tested this out locally (in our case: PolarFire SoC,) and the outcome is it will work  when CONFIG_RV_BOOT_HART=1 (u54_1). However, It does not work when CONFIG_RV_BOOT_HART=4 (u54_4). The reason is because the privilege modes contexts are not taken into consideration.
you can see in the [SiFive FU540-C000 Manual](https://static.dev.sifive.com/FU540-C000-v1.0.pdf) and [PolarFire SoC TRM](https://ww1.microchip.com/downloads/aemDocuments/documents/FPGA/ProductDocuments/ReferenceManuals/PolarFire_SoC_FPGA_MSS_Technical_Reference_Manual_VC.pdf) in the PLIC chapter:
```
Context 0 is for HART 0 M Mode Enables,
Context 1 and 2 are for HART 1 M and S Mode Enables,
Context 3 and 4 are for HART 2 M and S Mode Enables, 
Context 5 and 6 are for HART 3 M and S Mode Enables,
Context 7 and 8 are for HART 4 M and S Mode Enables,
``` 

This solution is a step in the right direction, however the best solution should take into consideration SMP, where each CPU/HART can handle interrupts.

Kind Regards,
Conor

**Comment by con-pax** [comment]
> Thanks for testing, I've just pushed another revision, could you try again?

Hey, yep sure thing: I can test again tomorrow morning (GMT)

**Comment by con-pax** [comment]
Hey @ycsin,

Apologies for the delay. I was sidetracked yesterday. I tested the change and unfortunately it produces a system failure during the plic init function.

I have been working on a solution today. Its definitely a "Work in Progress" but I thought I would share it with you now: https://github.com/polarfire-soc/zephyr/tree/mpfs-icicle_plic_multi-context_support

**Comment by ycsin** [comment]
Closed, should work directly towards a fix instead

**Comment by ycsin** [comment]
> "Work in Progress"

Hey @con-pax, do you have a plan to move this forward?

**Comment by con-pax** [comment]
> > "Work in Progress"
> 
> Hey @con-pax, do you have a plan to move this forward?

Hey @ycsin yep, should be pushing in a couple of hours

**Comment by con-pax** [comment]
> Hey @ycsin yep, should be pushing in a couple of hours

Just finishing up twister testing locally, so it will be tomorrow morning before I can push.

**Pull request closed without merging**
