### PR TITLE
Prevent null-deref to fix seg fault in cbvprintf on strlen(NULL)

### PR DESCRIPTION
**Pull request by devanl**
Fix for https://github.com/zephyrproject-rtos/zephyr/issues/76509

### CODE REVIEW

**Comment by pdgendt** [comment]
@devanl please read the [guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#pull-request-guidelines) on how to format the `git` commits.

Also squash your commits into a single commit.

**Comment by pdgendt** [comment]
Also just force push on this PR, no need to open a new PR.

**Comment by devanl** [comment]
Is this waiting for anything besides review that I can support here?

**Comment by RafaelLaya** [comment]
> Is this waiting for anything besides review that I can support here?

In my short experience I've found you usually need to get CI green before people start reviewing. I think it's because folks with review access usually have to optimize their time and so they probably filter PRs by those that have green CI

In your case it seems you're only failing two compliance checks: 
"1: UC5 Commit title exceeds max length (83>75)"

"3: UC4 Commit message body line exceeds max length (93>75)"

**Comment by kartben** [comment]
> Is this waiting for anything besides review that I can support here?

As suggested by @pdgendt , please read the contribution guidelines as they contain the answers regarding how to get the compliance check to stop complaining :) thanks!

**Review by dcpleung — APPROVED** [review]

**Comment by RafaelLaya** [comment]
bump @nordic-krch  can we get the 2nd approval? :D

**Review by pdgendt — APPROVED** [review]
Nit: change the commit subject to have `lib: os: ` prefix. (changing commit message does not retrigger CI and doesn't dismiss approvals)

**Comment by devanl** [comment]
not sure what I did to close this...

**Comment by devanl** [comment]
attempt to reopen

**Comment by nordic-krch** [comment]
Something got messed up as commit show >5000 modified files.

**Pull request closed without merging**
