### PR TITLE
github: hello_world_multiplatform: run on any script changes

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Open up the hello_world_multiplatform filter to run on any PR changing anything in scripts. This should catch twister regressions as well.

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]
Thanks.

**Comment by fabiobaltieri** [comment]
The initial filter there was a bit of a rough guess, would be a good idea to revisit that list ~every time we hit a regression there

**Review by kartben — APPROVED** [review]

**Comment by nashif** [comment]
> Open up the hello_world_multiplatform filter to run on any PR changing anything in scripts. This should catch twister regressions as well.

were there any regression recently with twister?

**Comment by henrikbrixandersen** [comment]
> were there any regression recently with twister?

Yes, fixed by https://github.com/zephyrproject-rtos/zephyr/pull/83030

**Review by nashif — APPROVED** [review]

**Pull request merged**
