### PR TITLE
boards: nucleo_l432kc: configure serial pins using dts

### PR DESCRIPTION
**Pull request by lochej**
usart2 and usart1 pins are now configured through device tree.

Signed-off-by: Jeremy LOCHE <lochejeremy@gmail.com>

### CODE REVIEW

**Comment by lochej** [comment]
@galak @gmarull @erwango  Something is wrong with the pinctrl DTS for stm32l43x series, **usart2_rx_pa15** is a valid configuration and actually is the default one for nucleo_l432kc but is not available in pinctrl DT. This problem might also have appeared for other DT. Cannot tell right now.
image
image

**Comment by gmarull** [comment]
Thanks for reporting @lochej ! I have found the problem and opened a PR with a fix: https://github.com/zephyrproject-rtos/hal_stm32/pull/66

**Comment by galak** [comment]
@lochej can you update west.yml in this PR to point to updated PR on the hal_stm32 repo.

**Comment by lochej** [comment]
> @lochej can you update west.yml in this PR to point to updated PR on the hal_stm32 repo.

Absolutely, that's a good idead 👍

**Comment by lochej** [comment]
> @lochej can you update west.yml in this PR to point to updated PR on the hal_stm32 repo.

Now that this PR works with the appropriate fix PR provided in HAL_STM32,  we should just wait till https://github.com/zephyrproject-rtos/hal_stm32/pull/66 is merged and then we'll unlock this one 👍

**Review by gmarull — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by galak** [comment]
@lochej I merged the hal PR, so can you update west.yml to the SHA.

**Comment by lochej** [comment]
> 
> 
> @lochej I merged the hal PR, so can you update west.yml to the SHA.

Can't edit right now, but will do in the evening of week end for sure 👍

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by lochej** [comment]
> @lochej can you update west.yml in this PR to point to updated PR on the hal_stm32 repo.

That's now added, west points to latest commit of hal_stm32 ! 😄

**Comment by lochej** [comment]
I'm closing this PR as I have merged it with #28954

**Pull request closed without merging**
