### PR TITLE
west.yml: hal_nordic: nrfx: make it a zephyr_library()

### PR DESCRIPTION
**Pull request by marc-hb**
See https://github.com/zephyrproject-rtos/hal_nordic/pull/6

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Comment by carlescufi** [comment]
@marc-hb thanks! this is ready to merge if you remove the Draft tag

**Comment by marc-hb** [comment]
> this is ready to merge if you remove the Draft tag

It wasn't ready because the manifest was still pointing at `pull/head/6`. I fixed that but got a merge conflict because another PR  updated the same reference before me. This conflict is correctly reported by Shippable, no issue there. On the other hand all the other CI checks seem stuck, is it because of the conflict?

@nashif , @galak , @ulfalizer , are you interested in investigating a potential issue where CI checks hang when there's a manifest conflict? I have the rebase ready and I can force push it but there's no rush at all, it can wait for any number of CI investigations.

**Comment by ulfalizer** [comment]
> @nashif , @galak , @ulfalizer , are you interested in investigating a potential issue where CI checks hang when there's a manifest conflict? I have the rebase ready and I can force push it but there's no rush at all, it can wait for any number of CI investigations.

Guessing `ci-tools` never gets fetched at all, since it's fetched via the manifest nowadays. Haven't looked at the CI code that handles that part though.

Would be nice if we could get `ci-tools` back into the main repo.

**Comment by marc-hb** [comment]
> Guessing ci-tools never gets fetched at all, since it's fetched via the manifest nowadays.

That would totally explain why they can't run when there's a conflict in the manifest, nice guess!

That doesn't explain why the failure to (find and) run them doesn't get reported. Well, considering normal error handling never gets tested, imagine asynchronous error handling :-)

**Comment by marc-hb** [comment]
Superseded by PR #19399. I'm leaving this CI crime scene "as is" for investigation(s). Unsubscribe if you don't care about CI.

**Pull request closed without merging**
