### PR TITLE
testsuite: Ifdef an include

### PR DESCRIPTION
**Pull request by ceolin**
shell.h must be included only if CONFIG_SHELL is
defined, otherwise this will pull unused code.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — COMMENTED** [review]
what problem does this solve??

**Comment by ceolin** [comment]
> what problem does this solve??

if you remove shell code and try to build Zephyr it will fail even if you don't need to use this code. We should be able to remove code that are not being used.

**Comment by ceolin** [comment]
> > what problem does this solve??
> 
> if you remove shell code and try to build Zephyr it will fail even if you don't need to use this code. We should be able to remove code that are not being used.

of course it is just used in tests, but I don't see any reasons not doing it

**Review by nashif — APPROVED** [review]

**Comment by ceolin** [comment]
Added a new commit just adding a missing header that was needed.

**Pull request merged**
