### PR TITLE
tests: Bluetooth: Mesh: Fix non-deterministic behavior in bsim tests

### LINKED ISSUE #55821: Not deterministic some of bsim mesh tests behavior
**Describe the bug**
Bsim mesh tests those use backchannel for synchronization between two emulated devices break deterministic test behavior.
Test behavior is changed from run to run. Since backchannel is used before access to bsim emulated Phy there is time drift between processes as consequence there is some drift test access to Phy. It might cause radio collisions and unstable test behavior.

Please take a look at communication in this PR for details: https://github.com/zephyrproject-rtos/zephyr/pull/55771#discussion_r1135857543

**To Reproduce**
1. build bsim tests for mesh
2. run va.sh test once
3. add bsim run option `-argsmain -stop_on_diff`
4. run it again
5. see result of not deterministic behavior

sample of mistaken behavior
```
p_2G4:  Comp: Device 0, Rx 4 differs
p_2G4:  Comp: Read:"99864,4294967295,0x8E89BED6,16,2.000000,0.000000,2,0,40,16,1000000,110474,110871,-1,0,0,0,0,110474,4,0.000000,0,"
p_2G4:  Comp:      "99864,4294967295,0x8E89BED6,16,2.000000,0.000000,2,0,40,16,1000000,129822,129823,-1,0,0,0,0,129822,4,0.000000,0,"
p_2G4:  Comp:                                                                           ^
```

**Expected behavior**
No difference in test logs\results between runs

**Impact**
Stability of Bluetooth CI test results. Potential failed Bluetooth CI plan (even changes are not related to failed test)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: cb2bc394df7eb4fbf1223903bf43b3c1b22f8333

**Additional context**
Seems backchannel is not suitable functionality for synchronization between emulated devices.

### PR DESCRIPTION
**Pull request by PavelVPV**
This PR fixes non-deterministic behavior in mesh bsim tests by removing the source of this behavior. To synchronize devices from now on we should only use `k_sleep`. Phy resync time is reduced to 100ms for all mesh tests to make `k_sleep` more relevant when it is used to synchronize devices.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/55821

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Comment by aescolar** [comment]
@PavelVPV @alxelax let's have a quick chat tomorrow about this.
I will just reject to ensure it does not get merged before we have the opportunity to discuss it calmly.

**Review by aescolar — DISMISSED** [review]
see previous comment

**Comment by alxelax** [comment]
> @PavelVPV @alxelax let's have a quick chat tomorrow about this. I will just reject to ensure it does not get merged before we have the opportunity to discuss it calmly.

Discussed issue with @aescolar IRL. It will be helpful to have a command line option for bsim to have processes (with emulated devices) synchronized before test scenarios run.

The current implementation that is based on backchannel should be removed. Seems it has been added without deep understanding how it works. The current PR is Ok form me.

**Review by alxelax — APPROVED** [review]

**Review by aescolar — COMMENTED** [review]
Note: The decision about how mesh tests should be belongs to those working on the mesh area. My involvement here is only as the undelaying tooling provider.
I have nothing against this change in particular.

**Pull request merged**
