### PR TITLE
stm32:  Select GPIO when required

### PR DESCRIPTION
**Pull request by erwango**
Select GPIO when required directly in stm32 drivers so that it is not required anymore to do it at board level.
Clean up stm32 based boards.

### CODE REVIEW

**Comment by danieldegrasse** [comment]
No sure why I was set as assignee, @erwango feel free to move this to whoever you feel is appropriate

**Comment by fabiobaltieri** [comment]
> No sure why I was set as assignee, @erwango feel free to move this to whoever you feel is appropriate

Because 736e6b7e749d346e66c08281914397c35439bda5, I'll open a rollback.

**Comment by erwango** [comment]
Generates a dependency loop... Interesting

**Comment by duda-patryk** [comment]
> Generates a dependency loop... Interesting

Yup. That's why `depends on` is preferred over `select`. Ideally, `select` should be used to enable options that can't be set manually.

**Pull request closed without merging**
