### PR TITLE
ext: hal: nordic: Update nrfx to version 1.7.1

### PR DESCRIPTION
**Pull request by anangl**
Updates nrfx to the recently released version. See
https://github.com/NordicSemiconductor/nrfx/blob/v1.7.1/CHANGELOG.md
for a list of changes that this version introduces.

Origin: nrfx
License: BSD 3-Clause
URL: https://github.com/NordicSemiconductor/nrfx/tree/v1.7.1
commit: 9d68726e41c321f1772c187bd12d82f5b13104f1
Purpose: Provide peripheral drivers for Nordic SoCs
Maintained-by: External

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
Looks like there are no MDK changes, right?

**Comment by anangl** [comment]
> Looks like there are no MDK changes, right?

That's right. There were no changes in MDK between nrfx v1.6.2 and v1.7.0.

**Review by nvlsianpu — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@carles @anangl I think this PR can go with 'backport v1.14-branch’ tag.
I suggested this as have the same idea for #15118
What are your opinions?

**Review by nvlsianpu — APPROVED** [review]

**Comment by carlescufi** [comment]
@nvlsianpu I think it would be too much to backport this. We are supposed to backport fixes, and this is a bit too much.

**Pull request merged**
