### PR TITLE
mgmt/mcumgr: Move SMP transport to own sub-dir

### PR DESCRIPTION
**Pull request by de-nordic**
The lib/transport directory has been moved up, directly under the
subsys/mgmt/mcumgr, and all transport files have been moved to
that directory.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]

**Comment by nordicjm** [comment]
Needs rebase

**Review by nordicjm — DISMISSED** [review]

**Review by nvlsianpu — DISMISSED** [review]

**Comment by carlescufi** [comment]
@de-nordic please rebase

**Comment by nordicjm** [comment]
Needs rebase

**Comment by carlescufi** [comment]
@de-nordic please rebase

**Review by nordicjm — DISMISSED** [review]

**Comment by nordicjm** [comment]
@de-nordic needs rebase

**Review by carlescufi — DISMISSED** [review]

**Review by nvlsianpu — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Comment by nordicjm** [comment]
@de-nordic needs rebase

**Review by nvlsianpu — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
