### PR TITLE
sys_heap heap allocator optimizations

### PR DESCRIPTION
**Pull request by npitre**
This goes on top of PR #23941 and therefore patches from PR #23941 are included here.

This series implements an assortment of optimizations providing both
execution efficiency and footprint overhead reduction. Because of that, a few tests presuming a higher overhead are now failing.

I'm posting this here for people to see and comment.

### CODE REVIEW

**Comment by andrewboie** [comment]
parent PR now merged, please rebase

**Comment by npitre** [comment]
On Tue, 14 Apr 2020, Andrew Boie wrote:

> parent PR now merged, please rebase

Done.

**Comment by andrewboie** [comment]
Bunch of tests failing with "    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/lifo/lifo_usage/src/main.c:329: test_timeout_lifo_thread: packet != NULL is false"

Gonna kick CI again to make sure.

**Comment by andrewboie** [comment]
Seeing a consistent assertion failure:

```
starting test - test_mheap_block_desc

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_heap/mheap_api_concept/src/test_mheap_concept.c:129: test_mheap_block_desc: block_fail is not NULL
```

kicking again to make sure

**Comment by npitre** [comment]
On Mon, 11 May 2020, Andrew Boie wrote:

> Seeing a consistent assertion failure:
> 
> ```
> starting test - test_mheap_block_desc
> 
>     Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_heap/mheap_api_concept/src/test_mheap_concept.c:129: test_mheap_block_desc: block_fail is not NULL
> ```

OK, found it.

The last patch is titled "sys_heap: reduce the size of struct 
z_heap_bucket by half". It is missing the following bit to a file that 
didn't exist when the patch was initially created:

```
diff --git a/include/mempool_heap.h b/include/mempool_heap.h
index df64322b50..439371556d 100644
--- a/include/mempool_heap.h
+++ b/include/mempool_heap.h
@@ -35,7 +35,7 @@ struct k_mem_pool {
  * that k_heap does not.  We make space for the number of maximum
  * objects defined, and include extra so there's enough metadata space
  * available for the maximum number of minimum-sized objects to be
- * stored: 8 bytes for each desired chunk header, and a 24 word block
+ * stored: 8 bytes for each desired chunk header, and a 12 word block
  * to reserve room for a "typical" set of bucket list heads (this size
  * was picked more to conform with existing test expectations than any
  * rigorous theory -- we have tests that rely on being able to
@@ -46,7 +46,7 @@ struct k_mem_pool {
 		K_HEAP_DEFINE(poolheap_##name,				\
 			      ((maxsz) * (nmax))			\
 			      + 8 * ((maxsz) * (nmax) / (minsz))	\
-			      + 24 * sizeof(void *));			\
+			      + 12 * sizeof(void *));			\
 		struct k_mem_pool name = {				\
 			.heap = &poolheap_##name			\
 		}
```

Should be fine now.

**Comment by andrewboie** [comment]
```
[0mSeaBIOS (version rel-1.12.1-0-ga5cab58-dirty-20200214_052440-f7294c49af13-zephyr
)
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build v2.3.0-rc1-25-g401d2147465a  ***
Running test suite mempool
===================================================================
starting test - test_pool_block_get

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_pool/mem_pool/src/main.c:178: pool_block_get_work: (rv not equal to tests[i].rcode)
k_mem_pool_alloc() expected 0, got -12
size: 512, timeout: 0

FAIL - test_pool_block_get
===================================================================
starting test - test_pool_block_get_timeout

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_pool/mem_pool/src/main.c:178: pool_block_get_work: (rv not equal to tests[i].rcode)
k_mem_pool_alloc() expected 0, got -11
size: 4096, timeout: 100

FAIL - test_pool_block_get_timeout
===================================================================
starting test - test_pool_block_get_wait

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_pool/mem_pool/src/main.c:271: test_pool_block_get_wait: (rv not equal to 0)
k_mem_pool_alloc(3000) expected 0, got -11

FAIL - test_pool_block_get_wait
===================================================================
starting test - test_pool_malloc
PASS - test_pool_malloc
===================================================================
Test suite mempool failed.
===================================================================
PROJECT EXECUTION FAILED
```

Still failing.

**Review by andyross — APPROVED** [review]
Just throwing up my +1 for when this exits the CI banging phase.  These all look great to me.

**Comment by npitre** [comment]
On Tue, 12 May 2020, Andy Ross wrote:

> Just throwing up my +1 for when this exits the CI banging phase.  These all look great to me.

Thanks.

What is not great are all those tests: some of them are pure bollocks in 
the context of the heap allocator.

Some patches in this series reduce the heap footprint overhead and then 
some allocation tests pass when they were expected to fail with ENOMEM. 
So futzing with the fake numbers within Z_MEM_POOL_DEFINE() make them 
pass but then other tests start failing for the opposite reason.

So I just picked another semi-random number to satisfy all tests... 
unless I missed some.

**Comment by carlescufi** [comment]
There are some build failures here that I am not sure are attributable to this PR's changes. @nashif any ideas?

**Comment by carlescufi** [comment]
The current failure in `qemu_arc_em` is almost certainly unrelated to this PR.

```
Failures

 Sanitycheck / qemu_arc_em:tests/kernel/lifo/lifo_usage/kernel.lifo.usage / tests/kernel/lifo/lifo_usage/kernel.lifo.usage

*** Booting Zephyr OS build zephyr-v2.3.0-488-g6c7ca9602316  ***
Running test suite test_lifo_usage
===================================================================
starting test - test_lifo_nowait
PASS - test_lifo_nowait
===================================================================
starting test - test_lifo_wait
PASS - test_lifo_wait
===================================================================
starting test - test_timeout_empty_lifo
PASS - test_timeout_empty_lifo
===================================================================
starting test - test_timeout_non_empty_lifo
PASS - test_timeout_non_empty_lifo
===================================================================
starting test - test_timeout_lifo_thread
PASS - test_timeout_lifo_thread
===================================================================
starting test - test_timeout_threads_pend_on_lifo
 thread (q order: 2, t/o: 0, lifo 0x8040621c)

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/lifo/lifo_usage/src/main.c:140: test_multiple_threads_pending: (data->timeout_order not equal to ii)
 *** thread 2 woke up, expected 1

FAIL - test_timeout_threads_pend_on_lifo
===================================================================
Test suite test_lifo_usage failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Comment by stephanosio** [comment]
> The current failure in `qemu_arc_em` is almost certainly unrelated to this PR.

@carlescufi The QEMU ARC platform does not have icount enabled and can be quite unstable when running sanitychecks (basically the same issue we had with other platforms earlier). Re-triggering should fix the problem.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
