### PR TITLE
kernel/queue: Remove interior use of k_poll()

### LINKED ISSUE #25904: kernel: k_queue_get return NULL before timeout
**Describe the bug**
The API call `k_queue_get` return no data element before timeout has expired.
Calling either `k_queue_get(queue, K_FOREVER);` or `k_queue_get(queue, K_SECONDS(20))` return `NULL` within one second.

This appears to occur because two threads are both waiting for an element in the queue.
Once an element is posted to the queue, both threads are woken, one will retrieve the new element, while the other will discover an empty queue.

This is a regression from: 7832738ae985a63febb8f82e7c4e34824f48486e
Specifically this change:
```
-static void *k_queue_poll(struct k_queue *queue, s32_t timeout)
+static void *k_queue_poll(struct k_queue *queue, k_timeout_t timeout)
 {
        struct k_poll_event event;
-       int err, elapsed = 0, done = 0;
+       int err;
        k_spinlock_key_t key;
        void *val;
-       u32_t start;
 
        k_poll_event_init(&event, K_POLL_TYPE_FIFO_DATA_AVAILABLE,
                          K_POLL_MODE_NOTIFY_ONLY, queue);
 
-       if (timeout != K_FOREVER) {
-               start = k_uptime_get_32();
-       }
-
-       do {
-               event.state = K_POLL_STATE_NOT_READY;
-
-               err = k_poll(&event, 1, timeout - elapsed);
-
-               if (err && err != -EAGAIN) {
-                       return NULL;
-               }
+       event.state = K_POLL_STATE_NOT_READY;
+       err = k_poll(&event, 1, timeout);
 
-               key = k_spin_lock(&queue->lock);
-               val = z_queue_node_peek(sys_sflist_get(&queue->data_q), true);
-               k_spin_unlock(&queue->lock, key);
+       if (err && err != -EAGAIN) {
+               return NULL;
+       }
 
-               if ((val == NULL) && (timeout != K_FOREVER)) {
-                       elapsed = k_uptime_get_32() - start;
-                       done = elapsed > timeout;
-               }
-       } while (!val && !done);
+       key = k_spin_lock(&queue->lock);
+       val = z_queue_node_peek(sys_sflist_get(&queue->data_q), true);
+       k_spin_unlock(&queue->lock, key);
 
        return val;
```
Reverting this change (using legacy timeout API) fixes the issue.
The commit message says this:
```
    Also in queue.c, a (when POLL was
    enabled) a similar loop was needlessly used to try to retry the
    k_poll() call after a spurious failure.  But k_poll() does not fail
    spuriously, so the loop was removed.
```
The loop appears to have been removed for the wrong reason.

**To Reproduce**
The current steps involves 2 nRF52 dev-kits and a few manual steps.
I can try to make a more minimal failing test if needed, otherwise I can verify using my current setup.

Use branch: https://github.com/joerchan/zephyr/tree/bt-recv-deadlock-debug
```
export BOARD=nrf52840dk
west build test/bluetooth/shell 
west flash --erase 
west build samples/bluetooth/peripheral
west flash --erase
# Attach one terminal to each

# shell terminal:
bt init
bt connect <id addr>
bt gatt exchange-mtu
```

**Console output**
peripheral sample:
```
Advertising successfully started
Connected: 4e:1a:6f:9b:b8:00 (random)
Write: count= 122, len= 2440, rate= 19523 bps.
Write: count= 1266, len= 25320, rate= 202578 bps.
Write: count= 1815, len= 36300, rate= 290408 bps.
Write: count= 1768, len= 35360, rate= 282880 bps.
Write cmd failed (-55).
Write: count= 1222, len= 37964, rate= 303758 bps.
[00:00:13.090,026] <err> bt_conn: k_is_in_isr 0
[00:00:13.090,057] <err> bt_conn: conn_tx_alloc timeout 0 secs.

[00:00:13.090,087] <err> bt_conn: Unable to allocate TX context
Write: count= 603, len= 37386, rate= 299444 bps.
LE conn param updated: int 0x0028 lat 0 to 42
Write: count= 529, len= 32798, rate= 262680 bps.
Write: count= 594, len= 36828, rate= 294957 bps.
Write: count= 654, len= 40548, rate= 324750 bps.
Write: count= 671, len= 41602, rate= 333049 bps.
Disconnected (reason 0x13)
Write cmd failed (-57).
```

**Expected behavior**
k_queue_get should not return NULL before timeout has passed.

**Impact**
This breaks the current flow-control behavior of Bluetooth, the attempted k_queue_get from BT RX thread will drop the attempt to answer the ATT request and will result in a disconnected ATT channel.

**Additional context**
CONFIG_POLL is enable
Blocker to fix: https://github.com/zephyrproject-rtos/zephyr/issues/23364

### PR DESCRIPTION
**Pull request by andyross**
The k_queue data structure, when CONFIG_POLL was enabled, would
inexplicably use k_poll() as its blocking mechanism instead of the
original wait_q/pend() code.  This was actually racy, see commit
b173e4353fe5.  The code was structured as a condition variable: using
a spinlock around the queue data before deciding to block.  But unlike
pend_current_thread(), k_poll() cannot atomically release a lock.

A workaround had been in place for this, and then accidentally
reverted (both by me!) because the code looked "wrong".

This is just fragile, there's no reason to have two implementations of
k_queue_get().  Remove.

Note that this also removes a test case in the work_queue test where
(when CONFIG_POLL was enabled, but not otherwise) it was checking for
the ability to immediately cancel a delayed work item that was
submitted with a timeout of K_NO_WAIT (i.e. "queue it immediately").
This DOES NOT work with the origina/non-poll queue backend, and has
never been a documented behavior of k_delayed_work_submit_to_queue()
under any circumstances.  I don't know why we were testing this.

Fixes #25904

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
@andyross  can you please add a test for this or is this already covered by other tests?

**Comment by carlescufi** [comment]
@andyross Thanks for the patch. After discussing this PR in the release readiness meeting, we would like to have a test that verifies this doesn't reappear before merging the PR.

**Comment by pabigot** [comment]
I think we need an explicit test for the failing situation in #25904: two threads waiting on a queue, something's added, both threads get woken and the last one doesn't get a value.

**Review by joerchan — APPROVED** [review]
Tested this PR and the reported problem is now fixed.

**Review by nashif — APPROVED** [review]

**Comment by andyross** [comment]
OK, test added.  There's obviously no way from within CI to validate that this **does** fail on master, but trust me it does and it's fixed with the first patch. :)

Note that the nature of the fix is such that the race just doesn't make sense (the original loop in k_queue never had that behavior anyway).  So at some point we'll want to yank this regression test too, I suspect.  But it's low overhead.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> OK, test added. There's obviously no way from within CI to validate that this **does** fail on master, but trust me it does and it's fixed with the first patch. :)
> 
> Note that the nature of the fix is such that the race just doesn't make sense (the original loop in k_queue never had that behavior anyway). So at some point we'll want to yank this regression test too, I suspect. But it's low overhead.

Right, but just in case we ever go back to the old implementation, doesn't hurt to have it for now :)

**Comment by pabigot** [comment]
> OK, test added. There's obviously no way from within CI to validate that this **does** fail on master, but trust me it does and it's fixed with the first patch. :)

Outside of CI the test doesn't fail for me on master.   But neither does the case I was concerned about.  So given the fix works, it's probably good.

**Comment by andyross** [comment]
FWIW: the base tests/kernel/queue test always worked.  It's not using CONFIG_POLL.

There's a separate prj-poll.conf that enables it, and sanitycheck is configured to run both.  Basically if you run "sanitycheck -T tests/kernel/queue" you should see this case fail on that half of the test (and, IIRC, some others that happen to enable CONFIG_POLL as part of the platform config).

**Review by tyrantlizard77 — APPROVED** [review]

**Pull request merged**
