### PR TITLE
DTS cleanup for nRF5340 SoC and its IPC nodes

### PR DESCRIPTION
**Pull request by kapi-no**
1st commit:

Cleaned up the IPC configuration for nRF5340 SoC in Device Tree. This
change fixes the (simple_bus_reg) warning about the missing or empty
reg/ranges property.

This is a follow-up to commit cf6a58d3f61aa163d149a3c3ff6389285bd09c13.

2nd commit:

Added chosen syntax in Device Tree to abstract the IPC device that is
used with the IPC service module in the Bluetooth HCI RPMsg driver.
Ported affected boards to declare this alias.

### CODE REVIEW

**Review by jori-nordic — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

**Comment by kapi-no** [comment]
Rebasing my commits because of some unrelated CI failures. The PR diff did not change

**Review by anangl — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

**Comment by kapi-no** [comment]
Pushed a patch to align DTS overlays in the samples/subsys/ipc/ipc_service/ directory with the new IPC description in DTS

**Comment by Thalley** [comment]
PR is missing a description

**Comment by kapi-no** [comment]
@Thalley, I added the description for both commits

**Comment by kapi-no** [comment]
It seems that CI is happy now. Please rereview

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
