### PR TITLE
Arty

### PR DESCRIPTION
**Pull request by MervatELalem**

### CODE REVIEW

**Comment by mgielda** [comment]
Hi @MervatELalem, thank you for the contribution! For the sake of clarity, please rename this PR - this is about GothamSoC support, not about the Arty board itself (which is just the platform you're running GothamSoC on I assume, but it's not the real target here).

**Comment by galak** [comment]
Please look at adding device tree support for both the SoC and devices (like UART).

**Comment by nashif** [comment]
I am a bit confused why this is coming from @Mani-Sadhasivam fork and yours, are you collaborating in this fork? seems weird.

**Comment by Mani-Sadhasivam** [comment]
Hi @nashif 

This is a RISCV core I was playing on the Arty board for learning purposes and it is not meant to be included in zephyr. Not sure how @MervatELalem submitted this without asking me.

Closing this PR.

**Pull request closed without merging**
