### PR TITLE
boards: nucleo_l4r5zi: Correct SPI1 SCK pin setting

### LINKED ISSUE #28303: nucleo_l4r5zi uses wrong pinmux setting
The nucleo_l4r5zi  board uses the wrong pinmux setting, this causes SPI shields to not work out of the box.

PR #28243 has a fix for this.

### PR DESCRIPTION
**Pull request by lowlander**
The original configuration mentioned, quote;

/* SPI1_SCK should output on PA5, but is used for LD2 */

But according the the schematic MB1312 from  7-11-2019 LD2 is on pin PB6 or PB7 (jumper selectable). And PA5 shares LD1 with PC7, but the default jumper settings are that PC7 controls the LD1, and PA5 is not connected to anything but the extension header.

Also the DTS file already has the green_led_0 (LD1) on pin PC7, and blue_led_0 (LD2) on pin PB7.

So changed pinmux to set PA5 to SPI1 SCK to make Arduino shields work that need SPI1.

Fixes #28303

### CODE REVIEW

**Review by lochej — APPROVED** [review]

**Comment by lochej** [comment]
Verified with datasheet:

image
image

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by martinjaeger — CHANGES_REQUESTED** [review]
The new pin setting should also be updated in `doc/index.rst`.

**Comment by lowlander** [comment]
> The new pin setting should also be updated in `doc/index.rst`.

Good point, didn't think about that.

**Review by martinjaeger — APPROVED** [review]

**Comment by erwango** [comment]
@lowlander fox for the CI issue has been merged, so it should go away after rebase.
Also, since this change is actually fixing something, it can merged for V2.4.0 as long as you have a matching issue.

**Comment by lowlander** [comment]
@erwango there i no bug report, but I can make one, or is that cheating ?

**Comment by lochej** [comment]
> 
> 
> @erwango there is no bug report, but I can make one, or is that cheating ?

It is not cheating because your fix allows to use Arduino shield which should be the default behavior and was not possible due to bad configuration from the beginning. 

You can clearly justify this PR.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
