### PR TITLE
samples: sensor: Add overlays for bme280 and bme680

### LINKED ISSUE #23148: bme280 sample does not compile
**Describe the bug**
The https://docs.zephyrproject.org/latest/samples/sensor/bme280/README.html build instructions do not build. The recommended board (nrf52840_pca10056) doesn't have that sensor in its DTS, so the reason why is clear, but all in-tree samples should compile.

I am unable to find a board in tree which *does* have this sensor in its DTS.

It's not clear to me whether or how mainline CI is building this sample. It seems like the fixture restriction is bypassing it:

```
sanitycheck -vv -T samples/sensor/bme280/ -p nrf52840_pca10056
...
DEBUG   - nrf52840_pca10056         samples/sensor/bme280/sample.sensor.bme280         SKIPPED: No hardware support
DEBUG   - nrf52840_pca10056         samples/sensor/bme280/sample.sensor.bme280.spi     SKIPPED: No hardware support
```

**To Reproduce**
1. cd zephyr
2. west build -b nrf52840_pca10056 samples/sensor/bme280
3. observe build error

```
In file included from /home/mbolivar/zp/zephyr/drivers/sensor/bme280/bme280.c:24:0:
/home/mbolivar/zp/zephyr/drivers/sensor/bme280/bme280.h:114:2: error: #error "BME280 device type not specified"
 #error "BME280 device type not specified"
  ^~~~~
/home/mbolivar/zp/zephyr/drivers/sensor/bme280/bme280.c: In function 'bme280_init':
/home/mbolivar/zp/zephyr/drivers/sensor/bme280/bme280.c:370:22: warning: unused variable 'data' [-Wunused-variable]
  struct bme280_data *data = dev->driver_data;
                      ^~~~
In file included from ../include/drivers/sensor.h:23:0,
                 from /home/mbolivar/zp/zephyr/drivers/sensor/bme280/bme280.c:11:
/home/mbolivar/zp/zephyr/drivers/sensor/bme280/bme280.c: At top level:
/home/mbolivar/zp/zephyr/drivers/sensor/bme280/bme280.c:398:29: error: 'DT_INST_0_BOSCH_BME280_LABEL' undeclared here (not in a function); did you mean 'DT_INST_0_SOC_NV_FLASH_LABEL'?
 DEVICE_AND_API_INIT(bme280, DT_INST_0_BOSCH_BME280_LABEL, bme280_init, &bme280_data,
                             ^
../include/device.h:106:11: note: in definition of macro 'DEVICE_AND_API_INIT'
   .name = drv_name, .init = (init_fn),     \
           ^~~~~~~~
```

**Expected behavior**
Following build instructions for built-in samples should not result in compile errors.

**Environment (please complete the following information):**
 - Commit SHA or Version used: today's master (b96477dd69)

### PR DESCRIPTION
**Pull request by carlescufi**
Fixes #23148.

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Can you also update `sample.yml` to make sure we start building these samples in CI?

**Comment by carlescufi** [comment]
> Can you also update `sample.yml` to make sure we start building these samples in CI?
@MaureenHelm 
I added a `platform_whitelist` entry, but I am not sure that ensures they will build in CI.

**Review by pabigot — APPROVED** [review]
This works for me on real BME280 hardware though I had to change to the secondary address for the breakout board I have.  AFAICT the sample won't build in CI because of the filters.  It wasn't obvious how to fix that.

**Comment by mbolivar** [comment]
> I added a `platform_whitelist` entry, but I am not sure that ensures they will build in CI.

It doesn't, but if I add this, it does:

```
diff --git a/samples/sensor/bme280/sample.yaml b/samples/sensor/bme280/sample.yaml
index 703a3143be..d5788d898e 100644
--- a/samples/sensor/bme280/sample.yaml
+++ b/samples/sensor/bme280/sample.yaml
@@ -4,7 +4,6 @@ tests:
   sample.sensor.bme280:
     harness: console
     tags: sensors
-    depends_on: i2c bme280
     platform_whitelist: nrf52840_pca10056
     harness_config:
         type: one_line
```

(Checked with `sanitycheck -vv -T samples/sensor/bme280/`)

**Comment by carlescufi** [comment]
> > I added a `platform_whitelist` entry, but I am not sure that ensures they will build in CI.
> 
> It doesn't, but if I add this, it does:
> 
> ```
> diff --git a/samples/sensor/bme280/sample.yaml b/samples/sensor/bme280/sample.yaml
> index 703a3143be..d5788d898e 100644
> --- a/samples/sensor/bme280/sample.yaml
> +++ b/samples/sensor/bme280/sample.yaml
> @@ -4,7 +4,6 @@ tests:
>    sample.sensor.bme280:
>      harness: console
>      tags: sensors
> -    depends_on: i2c bme280
>      platform_whitelist: nrf52840_pca10056
>      harness_config:
>          type: one_line
> ```
> 
> (Checked with `sanitycheck -vv -T samples/sensor/bme280/`)

Right, but I am not sure we want to remove that line, since it will likely break conditional building of samples later down the line. Thoughts @nashif?

**Comment by nashif** [comment]
if you have platform_whitelist then depends_on is useless. Our intention was to get rid of depends_on and get the data from dts, but that never happend. To build this test, the depends_on would need to be removed.

**Review by MaureenHelm — APPROVED** [review]

**Review by mbolivar — APPROVED** [review]

**Pull request merged**
