### PR TITLE
scripts: compliance: check for merge commits

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Add a compliance check that fails if the PR contains merge commits.

```
$ ./scripts/ci/check_compliance.py --annotate -m MergeCommits -c origin/main..
Running MergeCommits     tests in /usr/local/google/home/fabiobaltieri/zephyrproject/zephyr ...

Complete results in compliance.xml
$ git merge origin/main
...
$ ./scripts/ci/check_compliance.py --annotate -m MergeCommits -c origin/main..
Running MergeCommits     tests in /usr/local/google/home/fabiobaltieri/zephyrproject/zephyr ...
1 checks failed
ERROR   : Test MergeCommits failed: 
Merge commits not allowed: f7ad71f40c <- ('e721f60484', '5c773ae45e')

Complete results in compliance.xml
$ 
```

### CODE REVIEW

**Review by carlescufi — CHANGES_REQUESTED** [review]
I actually have an alternative in a local branch that I think is simpler. Let me open a PR.

**Comment by fabiobaltieri** [comment]
> I actually have an alternative in a local branch that I think is simpler. Let me open a PR.

Cool, not a fun of  having to do a second run, curious to see what you got instead.

**Comment by carlescufi** [comment]
> > I actually have an alternative in a local branch that I think is simpler. Let me open a PR.
> 
> Cool, not a fun of having to do a second run, curious to see what you got instead.


> > I actually have an alternative in a local branch that I think is simpler. Let me open a PR.
> 
> Cool, not a fun of having to do a second run, curious to see what you got instead.

Sure, will do as soon as I finish today's meetings

**Comment by fabiobaltieri** [comment]
> Sure, will do as soon as I finish today's meetings

No rush.

**Comment by carlescufi** [comment]
Simpler alternative here: #52639

**Pull request closed without merging**
