### PR TITLE
kconfig: Fail in CI if Kconfig files reference undefined symbols

### PR DESCRIPTION
**Pull request by ulfalizer**
Add a helper module scripts/ci/list_undef_kconfig_refs.py that searches
the entire Kconfig tree and reports any references to undefined Kconfig
symbols. Use it to add a new check to scripts/ci/check-compliance.py.

Also allow list_undef_kconfig_refs.py to be run standalone.

Example error:

<pre>
Error: Found references to undefined Kconfig symbols:

BAR
===

- Referenced at Kconfig:12:

config FOO
      bool
      depends on BAR

- Referenced at Kconfig:16:

menu "menu"
      depends on BAR
</pre>

### CODE REVIEW

**Comment by ulfalizer** [comment]
CC @nashif @SebastianBoe

**Review by nashif — CHANGES_REQUESTED** [review]
nice addition, but I would prefer to have this run as part of other compliance tests and report output like we do with gitlint and checkpatch, i.e. it should not abort the CI with exit, instead it should report the results in the junit xml file (and fail).

**Comment by ulfalizer** [comment]
@nashif 
Fixed.

Doing a test build without the fix for the undefined reference to SOC_NRF52810 to check that it works.

**Comment by ulfalizer** [comment]
Yep, seems to work.

**Comment by ulfalizer** [comment]
recheck

**Review by nashif — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
