### PR TITLE
sensor: add driver for ch101

### PR DESCRIPTION
**Pull request by yperess**
Implement the driver for the CH101 ToF sensor along with 2 firmwares provided by TDK:
1. GPR (general purpose range-finding)
2. GPR SR (GPR short range)

Additional firmwares are included in this PR to make it easier for the next person. They are not added, but should be simple enough for someone else to introduce a new Kconfig/enum and link the firmware files. This was done because adding them later would be much much harder.

**Note:** I'm working on the license headers

### CODE REVIEW

**Comment by teburd** [comment]
This might take a little bit to get to, as its quite large, but its on my list of PRs to review.

**Comment by yperess** [comment]
> This might take a little bit to get to, as its quite large, but its on my list of PRs to review.

Thanks Tom, I'll be making a push later today. It will split this into a few commits and make the soniclib match the Zephyr style. Also, I found the license for these so I'm updating the copyright comments at the top of the files.

**Comment by yperess** [comment]
OK, I reduced the scope of the PR to make it easier for review. Note that I got the copyright information from https://github.com/InvenSenseInc/tdk_robotics_rbx_drivers_code/blob/develop/COPYING

**Comment by yperess** [comment]
Marking as a WIP because it still needs unit tests and an updated license

**Comment by teburd** [comment]
I think the only alternative easily available here is to put the chirp soniclib in a module and use that from the driver. The BSD license should be allowable in the module then, while keeping all the code in the zephyr tree apache 2.0

**Pull request closed without merging**
