### PR TITLE
esp32: fix build error due to BIT conflict

### LINKED ISSUE #11077: Compiler warning at include/misc/util.h when building for ESP32
We have a compiler warning being treated as error, thus stopping build.

The issue as reported says that 

` #define BIT(n)  (1UL << (n))`

is re-defined at _/zephyr/include/misc/util.h:135_

Well, it complains because when we build with our toolchains, **esp-idf** already includes it at 
_esp-idf/components/soc/esp32/include/soc/soc.h:128_

as `#define BIT(nr)                 (1UL << (nr))`

So we should probably not include our definition when building for ESP32.

### PR DESCRIPTION
**Pull request by nashif**
Fixes #11077

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Heh, I remember chasing this long ago and getting confused about header dependence and giving up.  Nice to see it's that simple

**Comment by nashif** [comment]
closing for a bit, this is more involved than I thought.

**Comment by andyross** [comment]
Double heh. :)  Yeah, I forget all the details but I know I wound up giving up too.

**Review by rgundi — COMMENTED** [review]
LGTM

**Pull request closed without merging**
