### PR TITLE
dts: nordic: nrf5340: Change nRF5340 IPC backend to icbmsg

### PR DESCRIPTION
**Pull request by dchat-nordic**
Change the default IPC backend of nRF5340 to icbmsg.

### CODE REVIEW

**Review by rerickson1 — DISMISSED** [review]

**Review by kl-cruz — DISMISSED** [review]

**Comment by dchat-nordic** [comment]
@masz-nordic or @anangl please review

**Review by masz-nordic — DISMISSED** [review]

**Comment by anangl** [comment]
This PR conflicts with #74707. I think it would be better to wait for it to get in first. The amount of changes will be smaller then.

**Review by anangl — DISMISSED** [review]

**Review by anangl — APPROVED** [review]

**Comment by dchat-nordic** [comment]
@kl-cruz @rerickson1 @masz-nordic  Please rereview since the push revoked the approves. The pushed changes adjusted a board after https://github.com/zephyrproject-rtos/zephyr/pull/74707

**Review by kl-cruz — APPROVED** [review]

**Review by jaz1-nordic — APPROVED** [review]

**Comment by cvinayak** [comment]
This PR increase RAM usage in the samples/bluetooth/hci_ipc sample... is this intentional?

**Pull request merged**
