### PR TITLE
drivers: clock_control: Migrate to new logging subsys

### PR DESCRIPTION
**Pull request by Olivier-ProGlove**
Migrate from `SYS_LOG` to `LOG` logging mechanism.

Signed-off-by: Olivier Martin <olivier.martin@proglove.de>

### CODE REVIEW

**Comment by Olivier-ProGlove** [comment]
I have rebased the pull-request to fix the conflict after this pull-request has been merged https://github.com/zephyrproject-rtos/zephyr/commit/8cf8db3a73aa0658d728006e93d9ef5e0361a1b2

**Review by nordic-krch — CHANGES_REQUESTED** [review]
missing LOG_MODULE_REGISTER. Compilation will probably fail when logs are actually enabled in kconfig.

**Comment by nashif** [comment]
cherrypicked in #10029

**Comment by nashif** [comment]
addressed in #10029

**Pull request closed without merging**
