### PR TITLE
Cmake fix extra cflags for unittest

### PR DESCRIPTION
**Pull request by SebastianBoe**

### CODE REVIEW

**Comment by SebastianBoe** [comment]
BTW, do you know if KBuild supported this?

I see that KBuild produces a bunch of warnings, but is not given Werror. This PR will
probably be blocked in CI now that Werror is enabled in CI.

TODO: Fix warnings ...

**Comment by SebastianBoe** [comment]
fixes https://github.com/zephyrproject-rtos/zephyr/issues/4853

**Comment by SebastianBoe** [comment]
@inakypg : -Werror was not (for whatever reason) used in CI for unit tests before the CMake migration.

Adding support for EXTRA_CFLAGS exposes some pre-existing warnings. 
I am not familiar with how ztest integrates with Zephyr header files, so for this to be
merged I am going to need some help with fixing the warnings.

**Comment by inakypg** [comment]
Thxs for working on this.
I think KBuild did support it -- the warnings might come from the new syscall code and things we'd have run into anyway? Anyhoo, they shall be fixed and is good it is complaining, so we know they have to be worked on.
If @nashif is ok, I think this change shall go in.

**Comment by andrewboie** [comment]
@SebastianBoe 

>  -Werror was not (for whatever reason) used in CI for unit tests before the CMake migration.

Sanitycheck sets -Werror in EXTRA_CFLAGS

**Comment by SebastianBoe** [comment]
> Sanitycheck sets -Werror in EXTRA_CFLAGS

Blocked by https://github.com/zephyrproject-rtos/zephyr/pull/4887

**Comment by SebastianBoe** [comment]
Closing. Will re-open when #4887 is resolved.

**Review by nashif — APPROVED** [review]

**Pull request merged**
