### PR TITLE
cmake: increase minimal required version to 3.15.7

### PR DESCRIPTION
**Pull request by ioannisg**
Move to minimum required cmake version 3.15.7.
This is already a requirement for certain external
projects that integrate with Zephyr.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
@tejlmand please take a look into this draft PR

**Review by tejlmand — CHANGES_REQUESTED** [review]
> Move to minimum required cmake version 3.15.7.

Why 3.15.7 ?
Why not just 3.15 as in TF-M.
https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/53704fdf3462ac1b1044bbabc897a608034c9bcb/trusted-firmware-m/CMakeLists.txt#L8


3.15.7 is from Feb 2020, whereas 3.15.0 is from July 2019, and I currently see no reason why `.7` is important.

**Comment by tejlmand** [comment]
Not sure this is the right place, but I think it would be valuable to have a wider discussion on how to handle CMake minimum version (maybe process WG ?).

3.15 is not required because Zephyr repo uses 3.15 or newer features, but because a Zephyr module does.
But not all Zephyr users may use this module, and for sure not those using another arch than arm, but because of TF-M, they will be required to update their CMake.

Later Zephyr module X requires 3.18, are we then jumping whole Zephyr again ?

It's nice to know that everything, including modules will build if you have the CMake version required by Zephyr, but it is also nice for users if their distro installed CMake version is capable of building and testing native posix Zephyr samples out of the box.

And then the principle discussion whether Zephyr should bump version each time some module decides to bump their version.

**Review by nashif — CHANGES_REQUESTED** [review]
fully agree with @tejlmand, if we are moving cmake versions, this should be driven by zephyr itself, not a module.
Last time we did this it was not pleasant for many users and environments where updating to newest cmake was not as easy as you would think.

**Comment by nashif** [comment]
> Not sure this is the right place, but I think it would be valuable to have a wider discussion on how to handle CMake minimum version (maybe process WG ?).

This is not a process WG topic IMO, this probably fits better in your toolchain WG :)

**Comment by mbolivar-nordic** [comment]
- Ubuntu 20.04 (current LTS) has CMake 3.16.3, so this would be OK there.
- Debian stable only has 3.13.4, though, so Debian users would need to move beyond stable for this to work.
- Centos 8 (the latest) only has CMake 3.11, so it doesn't matter as those users are already behind. I assume the same is true for the latest RHEL, but I don't know for sure.
- Bleeding edge distros like Fedora and Arch should be fine, of course.

So at least this wouldn't break Ubuntu...

**Pull request closed without merging**
