### PR TITLE
gPTP support for Atmel SAM E70

### PR DESCRIPTION
**Pull request by jukkar**

### CODE REVIEW

**Review by galak — DISMISSED** [review]
Rather than updating the HAL this way, lets pull an update from http://packs.download.atmel.com/ for SAME70 that has a fix for the issue.

**Comment by PiotrZierhoffer** [comment]
@galak ,

We tried to follow your advice and update the whole HAL. Unfortunately, it proved to be quite problematic.

The current version used by Zephyr is 2.0. The change this PR introduces is available in HAL 2.3. Unfortunately, this version also introduces changes in the GMAC register addresses. We think they are not correct.

The relevant diff is as follows:
```
-#define REG_GMAC_ISRPQ          (0x40050400) /**< (GMAC) Interrupt Status Register Priority Queue  (index = 1) 0 */
-#define REG_GMAC_ISRPQ0         (0x40050400) /**< (GMAC) Interrupt Status Register Priority Queue  (index = 1) 0 */
-#define REG_GMAC_ISRPQ1         (0x40050404) /**< (GMAC) Interrupt Status Register Priority Queue  (index = 1) 1 */
+#define REG_GMAC_ISRPQ          (0x400503FC) /**< (GMAC) Interrupt Status Register Priority Queue (index = 1) 0 */
+#define REG_GMAC_ISRPQ0         (0x400503FC) /**< (GMAC) Interrupt Status Register Priority Queue (index = 1) 0 */
+#define REG_GMAC_ISRPQ1         (0x40050400) /**< (GMAC) Interrupt Status Register Priority Queue (index = 1) 1 */
```

This is a breaking change, and it is inconsistent with the documentation as well:

`... the addresses of this registers are defined as follows: address + (index * 0x04) [index being equal to 1 or 2]`

Other registers did not change.

We are trying to contact Microchip to confirm it is an actual bug, but it may not get fixed for a while. Since there are some changes to the HAL already committed in Zephyr (mainly fixing the compilation issues, I think), our proposition is to keep the change suggested in this PR and update the HAL with a new, correct version. The diff will be smaller and it won't require testing of each and every part of the system (which would be a good idea after we update the HAL).

**Comment by nashif** [comment]
@PiotrZierhoffer please follow the same approach we had with the frdm_k64 support, document the change in the README in ext/

**Comment by jukkar** [comment]
Uploaded new version which adds proper README file to Atmel HAL

**Review by nashif — APPROVED** [review]

**Pull request merged**
