### PR TITLE
boards: riscv: gd32vf103v_eval: initial support

### PR DESCRIPTION
**Pull request by gmarull**
Add initial support for the GD32VF103V-EVAL board. The board is based on
the GD32VF103 RISC-V MCU. Only UART has been enabled for now, allowing
to run the "hello_world" sample.

This board can run on Zephyr now largerly thanks to the initial work
done by @soburi.

Note that this board requires using the riscv-openocd fork, however,
programming is slow when using OpenOCD even though it works (including
debugging). J-Link option has also been enabled as it seems to be more
realiable and works _out of the box_. Some details are given in the
board documentation file.

Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>

### CODE REVIEW

**Review by nandojve — CHANGES_REQUESTED** [review]
Hi @gmarull ,

PR LGTM. I think you should add entries at CODEOWNERS and MAINTAINERS to tracking changes. 

I noted that besides @soburi is a collaborator I can't add him into reviews. Is this happen with you too?

**Review by soburi — COMMENTED** [review]
LGTM

**Comment by gmarull** [comment]
> Hi @gmarull ,
> 
> PR LGTM. I think you should add entries at CODEOWNERS and MAINTAINERS to tracking changes.
> 
> I noted that besides @soburi is a collaborator I can't add him into reviews. Is this happen with you too?

Done. I guess @soburi has not been added yet to the collaborators group. @nashif ping.

**Review by nandojve — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]
LGTM. Didn't have time to double-check the register addresses against the device manual, though.

**Review by katsuster — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Pull request merged**
