### PR TITLE
fs: nvs: initialize using device reference

### LINKED ISSUE #43229: nvs: change nvs_init to accept a device reference
## Introduction

`nvs_init()` now accepts the name of a flash device, forcing the usage of `device_get_binding()`. This adds unnecessary runtime overhead when the flash device can be obtained at compile time, e.g. with `DEVICE_DT_GET()`.

### Problem description

The NVS API is marked as stable, the proposed change would break all direct users of the NVS API. However, the change has low impact (a single API call).

### Proposed change

Change `nvs_init()` to be like:

```c
/**
 * @brief nvs_init
 *
 * Initializes a NVS file system in flash.
 *
 * @param fs Pointer to file system
 * @param dev Pointer to flash device
 * @retval 0 Success
 * @retval -ERRNO errno code if error
 */
int nvs_init(struct nvs_fs *fs, const struct device *dev);
```

## Detailed RFC

https://github.com/zephyrproject-rtos/zephyr/pull/43220
https://github.com/zephyrproject-rtos/zephyr/pull/43260

### Proposed change (Detailed)

N/A

### Dependencies

Settings NVS backend

### Concerns and Unresolved Questions

N/A

## Alternatives

- Deprecate `nvs_init()`
- Create `nvs_mount()`, an equivalent to `nvs_init()` that expects `.flash_device` to be initialized.

### PR DESCRIPTION
**Pull request by gmarull**
Instead of accepting a device name, thus requiring runtime device
fetching, accept a device reference. This allows API users to obtain a
device reference at compile time using DEVICE_DT_GET. nvs_init() API
assumes the device is operational now, so checking for device readiness
is responsability of the API clients.

Resolves https://github.com/zephyrproject-rtos/zephyr/issues/43229

### CODE REVIEW

**Review by Laczen — APPROVED** [review]
@gmarull, thanks for the PR

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
@gmarull this is the second PR I've seen from you today that changes a stable API without going through the stable API change process. Please be more careful to check that the APIs you are changing are either not marked stable in https://docs.zephyrproject.org/latest/reference/api/overview.html, or that you also provide the RFC issue etc needed to change them as described in the stability documentation

**Comment by gmarull** [comment]
> @gmarull this is the second PR I've seen from you today that changes a stable API without going through the stable API change process. Please be more careful to check that the APIs you are changing are either not marked stable in [docs.zephyrproject.org/latest/reference/api/overview.html](https://docs.zephyrproject.org/latest/reference/api/overview.html), or that you also provide the RFC issue etc needed to change them as described in the stability documentation

Opened https://github.com/zephyrproject-rtos/zephyr/pull/43220

**Comment by gmarull** [comment]
Closing in favor of https://github.com/zephyrproject-rtos/zephyr/pull/43260

**Pull request closed without merging**
