### PR TITLE
Remove legacy SYS_LOG logger

### PR DESCRIPTION
**Pull request by ulfalizer**
The old logger is no longer used. Remove it.

Original PR, that just changed a prompt: https://github.com/zephyrproject-rtos/zephyr/pull/14847

```
logging: kconfig: Remove legacy SYS_LOG symbols

Replaced by the new CONFIG_LOG system.

Also remove the "Logging Options" menu and turn the LOG symbol into a
'menuconfig', with prompt "Logging", which appears in the top menu. LOG
and its dependent symbols make up all of the logging Kconfig symbols
now.

Piggyback some minor cleanup.
```

```
logging: doc: Remove SYS_LOG-related documentation

Replaced by the new CONFIG_LOG system.
```

```
logging: Remove SYS_LOG implementation

Replaced by the new CONFIG_LOG system.
```

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
doc changes look OK, but our [guidelines](https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html#deprecated) say that APIs marked as deprecated will remain for 2 releases before being removed. (This API was marked deprecated January 2019 and has never been released as a deprecated API.)  Unless this is an "Unstable API", in which case, nevermind.

**Comment by ulfalizer** [comment]
> doc changes look OK, but our [guidelines](https://docs.zephyrproject.org/latest/development_process/api_lifecycle.html#deprecated) say that APIs marked as deprecated will remain for 2 releases before being removed. (This API was marked deprecated January 2019 and has never been released as a deprecated API.)

@nashif ?

We should either fix the prompts (https://github.com/zephyrproject-rtos/zephyr/pull/14847) or remove it at least. The way it is now, it's super confusing.

**Review by jukkar — APPROVED** [review]

**Comment by pfalcon** [comment]
> but our guidelines say that APIs marked as deprecated will remain for 2 releases before being removed. (This API was marked deprecated January 2019 and has never been released as a deprecated API.) Unless this is an "Unstable API", in which case, nevermind.

Whole Zephyr development is series of exceptions and leaps of faith like that ("why support 2 loggers/2 network API/2 whatever's in LTS and thus for a couple of years, let's remove it before it") ;-).

**Comment by nordic-krch** [comment]
@dbkinder , @pfalcon new logger was already present in 1.13. Sys_log might not be deprecated there but new logger appeared as clear replacement for sys_log.

Frankly speaking, i think that guidelines in that case is wishful thinking as zephyr is still in very immature state and setting such expectations adds more limits to the improvements than gain for the user.

**Review by jfischer-no — APPROVED** [review]

**Review by mnkp — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
