### PR TITLE
logging: use runtime message creation when logging is disabled

### LINKED ISSUE #57970: LOG macros with CONFIG_NO_OPTIMIZATIONS & CONFIG_LOG disabled causes a blowout of the stack use
**Describe the bug**

Functions with LOG macros will use abnormal amounts of stack space if CONFIG_LOG is disabled AND CONFIG_NO_OPTIMIZATIONS=y is set.

Create a simple function (I expanded on hello_world): 

image

Then compile the project with:

CONFIG_NO_OPTIMIZATIONS=y
#CONFIG_LOG=y
CONFIG_MYAPP_LOG_LEVEL_ERR=y

Because CONFIG_LOG is disabled, the function myfoo2() only increments the cnt2. But the compiler generates a function preamble that decides to adjust the stack pointer by 0x0154 bytes or 340 bytes.

image

If you turn on CONFIG_LOG the SP adjustment is 32 bytes:

image

And if you use any other optimization level, the code doesn't have these pre/postambles.

**Expected behavior**
Shouldn't do this. We should be able to reliably use any debug level (within limits).

**Impact**
CONFIG_NO_OPTIMIZATIONS is practically useless without making huge adjustments to the stack sizes.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain (e.g Zephyr SDK, ...) 
 - Commit SHA: 7039f8ce9c2787f37f5a97c3aca1e1541a0d7d07

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

### PR DESCRIPTION
**Pull request by marcowidmer**
Fixes #57970

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@nordic-krch @dcpleung can you take a look please?

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Comment by dleach02** [comment]
okay... cool that this is being addressed.

**Comment by marcowidmer** [comment]
@dleach02 Were you able to test this?

**Comment by dleach02** [comment]
Yes, this fixed my problem. Sorry for the delayed response.

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
@nashif how do we "kick" this to get it to run through all the CI?

**Comment by kartben** [comment]
@nordic-krch please rebase to trigger CI

**Comment by marcowidmer** [comment]
@kartben done

**Pull request merged**
