### PR TITLE
Fix IPv4 link local address configuration

### PR DESCRIPTION
**Pull request by pfl**
This PR is fixing the ARP packet type issue and the sender IP address in the ARP announce packets in #15373.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Minor thing about commit subject, please add "net:" prefix to both commit.
The code looks good.

**Comment by pfl** [comment]
> Minor thing about commit subject, please add "net:" prefix to both commit.

Updated all three of them.

**Review by jukkar — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Comment by pfl** [comment]
The third patch trying to unset the extra padding did not work. Apparently the size needs to be nudged in place, but I don't know how.

**Comment by jukkar** [comment]
@pfl please create github issue for the padding problem, and lets fix it in separate PR.

**Comment by pfl** [comment]
Issue for the extra padding is #15522

**Pull request merged**
