### PR TITLE
scripts: tests: twister: TestSuite tests expansion

### PR DESCRIPTION
**Pull request by LukaszMrugala**
This should increase the coverage of the testsuite.py module up to 100%.
Some tests have been commented out, as the code under test is incorrect. Thus the real increase is 99%. See relevant Issues:
- #60877 
- #60835

When fixing those Issues, one should uncomment the relevant tests.

### CODE REVIEW

**Review by hakehuang — DISMISSED** [review]
just a question on whether there is  a grphic view on the pytest converage?

**Comment by LukaszMrugala** [comment]
> just a question on whether there is a grphic view on the pytest converage?

If you follow the process specified in a README [here](https://github.com/zephyrproject-rtos/zephyr/tree/main/scripts/tests/twister), you can get a nice HTML report with a per-file per-line breakdown.

**Comment by LukaszMrugala** [comment]
Compliance fix for name shadowing.

**Review by nashif — APPROVED** [review]

**Comment by LukaszMrugala** [comment]
Are we waiting for #60877 with this?

**Review by PerMac — APPROVED** [review]

**Pull request merged**
