### PR TITLE
drivers/flash/flash_simulator: erase posix flash in initialization

### PR DESCRIPTION
**Pull request by nvlsianpu**
After startup the native_posix flash was filed by 0x00 instead
of 0xff, which is not coherent with erased byte value which
is 0xff for the native_posix target.

Such inconsistent behavior makes for instance running
a storage system designed(or configured) for a flash device
with 0xff as erased byte values problematic.

This patch makes flash erased after flash device file was created.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Review by Laczen — CHANGES_REQUESTED** [review]
This fix would "erase" flash.bin every time the flash simulator is used in native_posix.
It should only erase when a new file is created (or when all entries are "0").

**Comment by joerchan** [comment]
thanks @nvlsianpu . Bluetooth shell works with native posix now.

**Review by vanwinkeljan — CHANGES_REQUESTED** [review]
As @Laczen stated this will break the functionality of persisting data over multiple runs.

> It should only erase when a new file is created (or when all entries are "0").

Actually I would rather keep this behaviour and fix the bug in the actual code.
If the flash is not in the correct state the application code should take care of erasing the flash.

**Comment by nvlsianpu** [comment]
@vanwinkeljan 
> Actually I would rather keep this behaviour and fix the bug in the actual code.
If the flash is not in the correct state the application code should take care of erasing the flash.

As I mention this is not a bug - NVS recognizes something which looks incompatible with its design, so returns with error. It should be up to that application what should be done (this was behavior chosen for NVS, other storage might try to fix the flash area as you proposed.)

Suggestion by @Laczen is relevant to our case.

**Comment by vanwinkeljan** [comment]
> As I mention this is not a bug - NVS recognizes something which looks incompatible with its design, so returns with error. It should be up to that application what should be done (this was behavior chosen for NVS, other storage might try to fix the flash area as you proposed.)

I did not say it is a bug in NVS but rather one in the application code, should the code not recover from this?

**Comment by nvlsianpu** [comment]
^^ In most cases - it should.

What about suggestion that
> It should only erase when a new file is created (or when all entries are "0").

**Comment by vanwinkeljan** [comment]
> What about suggestion that
>
> >It should only erase when a new file is created (or when all entries are "0").

I could agree with erasing the complete flash if a new file is create.
But I would not check for all "0" and erase the complete flash especially if we make sure that the flash is in erased state after file creation, as in this case a flash with all "0" was intentionally created.

**Comment by Laczen** [comment]
> > What about suggestion that
> > > It should only erase when a new file is created (or when all entries are "0").
> 
> I could agree with erasing the complete flash if a new file is create.
> But I would not check for all "0" and erase the complete flash especially if we make sure that the flash is in erased state after file creation, as in this case a flash with all "0" was intentionally created.

Correct, it should only be erased when a new file is created.

And indeed, it should be the application that decides to act upon a failed initialization. What the NVS init is reporting is correct and the application should decide to erase the flash. However this should not be done "automatically" by some hidden function in the `settings` module.

**Comment by nvlsianpu** [comment]
@vanwinkeljan updated to what @Laczen suggested.

**Review by vanwinkeljan — APPROVED** [review]

**Review by Laczen — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@carlescufi @nashif please review in your convenience.

**Pull request merged**
