### PR TITLE
Add I2C support to STM32L0 and enable I2C1 port on NUCLEO-L073RZ

### PR DESCRIPTION
**Pull request by tagunil**
I've enabled only I2C1 because of rules defined in #5653 and discussed with @erwango.

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
+1 for docs

**Review by ydamigos — APPROVED** [review]
LGTM

**Comment by erwango** [comment]
@tagunil : LGTM, Was that tested?

**Comment by tagunil** [comment]
Yes, it was tested with slightly modified i2c_api test.

**Comment by erwango** [comment]
ok, thanks

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
