### PR TITLE
subsys: fs: initial ext2 implementation

### PR DESCRIPTION
**Pull request by fkokosinski**
First PR from the series of PRs that will bring ext2 implementation into Zephyr. The following operations are implemented:
* mount
* mkfs
* statvfs
* unmount

In addition, there are also a few new tests added for the implemented functions.

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi @de-nordic, could you take a look at this PR?

**Comment by fkokosinski** [comment]
Hi @Laczen! Since you've been assigned as a reviewer here, could you take a look at this PR?

**Comment by Laczen** [comment]
Hi @fkokosinski, my knowledge of ext2 is too limited to do a proper review. I am removing myself as reviewer. But as you are proposing to use this on flash: is this a good match ?

**Comment by de-nordic** [comment]
This will not get in till the feature freeze for 3.3.
I am not in favor of this feature because:
 1) It is still "initial": in context of small RTOS this means it has not been sufficiently evaluated yet and will probably grow.
 2) This has quite significant requirements and with lack of evaluation and real life testing again 1).
 3) This does not fix any of current problems we have with existing file systems like lack of flash wear-balancing, limited efficiency, lack of stable storage.

If this would be already proven implementation that has gone through some period of field testing and "initial" could be dropped form the title then 3) does not matter that much.
Right now I am reluctant to take this as this looks more like "this can be done" academic type of feature, and yes I can see it can be done, than something useful at large.
I think this should be taken to TSC for discussion.

**Comment by tgorochowik** [comment]
Hi Dominik, thank you for your reply.
I understand your concerns and I think I understand where they are coming from. The PR comes with targets for in-memory filesystem and flash filesystem.
The flash target that was chosen in this PR is unfortunate, and indeed not the main target for this filesystem. This was however done only because this allowed us to make this PR as small as possible to make the review process easier.

Also please note that this adds a new feature that is completely optional and does not change any of the existing codebase.

As for the actual purpose - I assume you say that this is only an academic type of feature because of your focus on microcontrollers. Please note however, that Zephyr has multiple targets where having an ext2 filesystem is beneficial (including non-microcontroller ones). In fact we started working on this because of the need for this in the products we are working on where we’re using Zephyr.

Here are some details I can share about the products, I think it’s sufficient to explain the needs:
* A smart camera product, used with other OS currently, Zephyr is to be a drop in replacement (so has to work with current hw), the videos are saved to an ext2 formatted storage
* A bootloader and a supervisor for a RISC-V platform, being a bootloader is indeed not the main use case for Zephyr, but seeing the number of useful features Zephyr has made it a good match.

That being said, we will close this PR for now and re-open this once the SD drivers are in a state we consider them being ready for mainlining. This will make this PR bigger but should make it clearer about where this is useful.

**Comment by Laczen** [comment]
@tgorochowik, your remarks make it clear what the use would be. What if you would target ramdisk or flashdisk ? These are intermediate layers that would make a step to using sd very small.

**Comment by tgorochowik** [comment]
Thank you for the suggestion, we'll evaluate these options

**Comment by de-nordic** [comment]
@tgorochowik Thanks for understanding.
I have seen the code and one of the comments I have: you should probably used Disk Access API rather than the Flash Map API, because using the former you can address access to MMC/SD, flash or RAM disk or any other type registered with proper driver (https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/disk)

**Pull request closed without merging**
