### PR TITLE
ci: twister: Parallelise Blackbox tests

### PR DESCRIPTION
**Pull request by LukaszMrugala**
Current Blackbox tests take up about 30-60 minutes (mostly c. 45 minutes), which is far too long.
This change makes every test file concurrent, greatly reducing time taken.

Actions related to blackbox tests generate warnings. Those are fixed by https://github.com/zephyrproject-rtos/zephyr/pull/71144.

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
That is a lot of instances to launches for something like that, we need to improve the performance in the test itself before we attempt to push this on multiple builders, I do not think this requires so many builders. Please reconsider the strategy and look into improving the test execution first.

**Comment by LukaszMrugala** [comment]
> That is a lot of instances to launches for something like that, we need to improve the performance in the test itself before we attempt to push this on multiple builders, I do not think this requires so many builders. Please reconsider the strategy and look into improving the test execution first.

I have spent some time profiling Twister in order to find places that could be improved in order to gain desired speedups. As we want a noticeable effect, we ought to consider only those code fragments that have the greatest impact.

I have compiled a list of most impactful terminal code fragments - code that is outside of Twister and thus can be considered uneditable by us for the purposes of this task.

| Unique static   terminals:       | Time percentage: |
|----------------------------------|------------------|
| Cmake subprocess                 | 65,78%           |
| pykwalify.core.Core.validate()   | 8,66%            |
| yaml.safe_load()                 | 8,65%            |
| ProjectBuilder.run() (not terminal)             | 6,83%            |
| re.match()                       | 4,01%            |
| Manifest.from_file()             | 1,11%            |
| pykwalify.core.Core().validate() | 1,11%            |
| yaml.load()                      | 1,02%            |
| pykwalify.core.Core()            | 0,15%            |
| file.open()                      | 0,12%            |
| git describe subprocess          | 0,09%            |
| git show subprocess              | 0,04%            |
| list.extend(Path.rglob())        | 0,00%            |
| REST                             | 2,43%            |

From this we can see that our main timesinks are: running CMake (65,78% of the `main()` time) and working with YAMLs (19,60% of the `main()` time considering only the `pykwalify` and `yaml` functions). This already takes up over 80% of the time.

Specific CMake runs are:
- CMake.run_cmake()` (36,33% of the `main()` time)
- CMake.run_build()` (21,80% of the `main()` time)
- TwisterEnv.run_cmake_script()` (7,68% of the `main()` time)

Those are once-per-test calls. We cannot make less of them and making them faster seems quite hard.

I am currently investigating a possibility of making fewer YAML loads, which could give us some benefit. It could take a bit of time.

Concurrency seems like our only quick option for now, sans a big overhaul. What number of runners per Python version seems reasonable? Currently we test on 5 Python versions, so 1 runner per every testfile gave us 100 runners overall. Given our typical runner load, I think 20 is an overkill, c. 8 seems to give the greatest speedup.

I can also enable pytest to run on multiple cores at once, but that will not give us big speedups - runners are 2-core machines.

**Comment by LukaszMrugala** [comment]
Improving test execution in Python code is contained [here](https://github.com/zephyrproject-rtos/zephyr/pull/71694).

**Comment by LukaszMrugala** [comment]
> That is a lot of instances to launches for something like that, we need to improve the performance in the test itself before we attempt to push this on multiple builders, I do not think this requires so many builders. Please reconsider the strategy and look into improving the test execution first.

There have been some performance improvements, but they have been quite meager. Attempt of parallelising this on-runner via `pytest-xdist` is dissapointing - we gain almost nothing, as our runners are 2-core, and lose the per-testfile results view. Should we try to parallelise this on many runners as was originally proposed here and if yes, on how many, or should we just close this PR?

**Pull request closed without merging**
