### PR TITLE
tests: bluetooth: kconfig: Do not assign promptless BT_MESH_PROV

### PR DESCRIPTION
**Pull request by ulfalizer**
Assignments have no effect on promptless symbols. Flagged by
https://github.com/zephyrproject-rtos/zephyr/pull/20742.

BT_MESH_PROV is already selected by BT_MESH_PB_ADV and BT_MESH_PB_GATT,
which these configuration files enable.

### CODE REVIEW

**Comment by jhedberg** [comment]
@tsvehagen any comments on this one?

**Comment by jhedberg** [comment]
I don't think these apps ever had provisioner support. I might remember wrong though. So the right action may be to remove these rather than renaming them.

**Comment by ulfalizer** [comment]
> I don't think these apps ever had provisioner support. I might remember wrong though. So the right action may be to remove these rather than renaming them.

Alright, I'll wait for some more feedback. I'm a compete Bluetooth noob.

**Comment by tsvehagen** [comment]
It should not be changed to `BT_MESH_PROVISIONER` so if `BT_MESH_PROV` is not needed then just remove it :+1:

**Comment by jhedberg** [comment]
@ulfalizer like @tsvehagen said could you update the PR to remove these instead. Thanks.

**Comment by jhedberg** [comment]
@ulfalizer like @tsvehagen said could you update the PR to remove these instead. Thanks.

**Comment by ulfalizer** [comment]
> It should not be changed to `BT_MESH_PROVISIONER` so if `BT_MESH_PROV` is not needed then just remove it

Changed. See updated commit message.

**Comment by jhedberg** [comment]
@ulfalizer FWIW, the `BT_MESH_PROV` gets selected by `BT_MESH_PB_ADV` and `BT_MESH_PB_GATT`.

**Comment by jhedberg** [comment]
> @ulfalizer FWIW, the BT_MESH_PROV gets selected by BT_MESH_PB_ADV and BT_MESH_PB_GATT.

Just to continue on that point: I don't think the commit message needs to mention `BT_MESH_PROVISIONER` at all. That's a new feature that was recently added and didn't exist when these samples and configurations were created. The only thing `BT_MESH_PROVISIONER` has in common is that it also requires the mesh provisioning protocol (`BT_MESH_PROV`) just like `BT_MESH_PB_ADV` and `BT_MESH_PB_GATT` (which have existed since the introduction of the mesh stack to Zephyr)

**Comment by ulfalizer** [comment]
> @ulfalizer FWIW, the `BT_MESH_PROV` gets selected by `BT_MESH_PB_ADV` and `BT_MESH_PB_GATT`.

Oh, right, had missed some selecting symbols. That makes it easier then. Updated the commit message.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
