### PR TITLE
drivers: clock_control: fix incorrectly allocated structure in clock control drivers

### PR DESCRIPTION
**Pull request by ndrs-pst**
- set `clock_control_driver_api` as `static const`
By using `static const`, we ensure immutability, leading to usage of only
`.rodata` and a reduction in the `.data` area.
- remove '&' when assigning `clock_control_xxx_init`
Remove address-of operator ('&') when assigning `clock_control_xxx_init`
function pointer in `DEVICE_DT_INST_DEFINE` macro.

### CODE REVIEW

**Comment by ndrs-pst** [comment]
Rebased to current `main` due to conflict in `drivers/clock_control/clock_stm32_ll_u5.c`

**Review by erwango — DISMISSED** [review]

**Comment by danieldegrasse** [comment]
Looks like the NRF auxpll driver might also need a cleanup:

```
$ grep -r "static struct clock_control_driver_api" drivers/clock_control
drivers/clock_control/clock_control_nrf_auxpll.c:static struct clock_control_driver_api clock_control_nrf_auxpll_api = {
```

Also, I think the init cleanup is needed for a few more drivers

```
$ grep -r "DEFINE(.*, &.*init," drivers/clock_control
drivers/clock_control/clock_control_adsp.c:DEVICE_DT_DEFINE(DT_NODELABEL(clkctl), &cavs_clock_ctrl_init, NULL,
drivers/clock_control/clock_stm32_mux.c:DEVICE_DT_INST_DEFINE(id, &stm32_clk_mux_init, NULL,  
```

May be missing additional cases here, this is just what I found with grep

**Comment by ndrs-pst** [comment]
@danieldegrasse Thanks for catching that! I've just force-pushed to address them.

**Review by danieldegrasse — APPROVED** [review]

**Review by ifyall — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Comment by erwango** [comment]
@nordic-krch Should this go in V3.7.0 ?

**Comment by nordic-krch** [comment]
> Should this go in V3.7.0 ?

If possible, yes.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> If possible, yes.

Wouldn't hurt to retitle the PR, "fix some incorrectly allocaed structure" sounds more stabilization than "refactor etc etc"

**Comment by ndrs-pst** [comment]
@fabiobaltieri How about this new title?
```
drivers: clock_control: fix incorrectly allocated structure in clock control drivers
```

**Pull request merged**
