### PR TITLE
boards: microchip: Delete pinmux.c file

### PR DESCRIPTION
**Pull request by mmahadevan108**
`pinmux` API is deprecated in 3.2 release. 

The transition to `pinctrl` for `mec1501modular_assy6885` and `mec15xxevb_assy6853` boards is being worked as part of PR https://github.com/zephyrproject-rtos/zephyr/pull/48893

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
I think we want to also drop `CONFIG_PINMUX=y` from the two `_defconfig` files.

**Comment by mmahadevan108** [comment]
> I think we want to also drop `CONFIG_PINMUX=y` from the two `_defconfig` files.

Thank you, updated and removed `CONFIG_PINMUX`

**Review by fabiobaltieri — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
what is wrong with #50326? This change is going to break the board for those who use it.

**Comment by mmahadevan108** [comment]
> what is wrong with #50326? This change is going to break the board for those who use it.

PR https://github.com/zephyrproject-rtos/zephyr/pull/50326 is one option

We would also like to consider the option of merging PR https://github.com/zephyrproject-rtos/zephyr/pull/46318, this PR and whatever work has been done as part of PR https://github.com/zephyrproject-rtos/zephyr/pull/48893 . @jvasanth1 can continue fixing the remaining items post 3.2 release.

**Comment by nashif** [comment]
> We would also like to consider the option of merging PR #46318

PR https://github.com/zephyrproject-rtos/zephyr/pull/50326 does include #46318 already.

**Comment by fabiobaltieri** [comment]
> what is wrong with #50326? This change is going to break the board for those who use it.

It seems like https://github.com/zephyrproject-rtos/zephyr/pull/48893 got most of the peripherals sorted, if we review and merge that PR and drop what's still in pinmux.c with this one, then we should still have the board still partially functional and CI running the build for all SoC drivers. Then we can deprecate pinmux for good and document the known issue for the peripherals that have not been ported yet, and either have those fixed before the release or for v3.2.1, and have a minimal amount of changes for doing that. How does that sound?

**Comment by str4t0m** [comment]
@mmahadevan108 Maybe you could add another commit also removing the `CONFIG_PINMUX` from the following boards.
`arm/lpcxpresso51u68/lpcxpresso51u68_defconfig:CONFIG_PINMUX=y`
`xtensa/esp32_net/esp32_net_defconfig:CONFIG_PINMUX=n`

Those should no longer have any affect.

**Comment by nashif** [comment]
> How does that sound?

this needs to be left to the maintainer of the platform and all should be done in the same PR (https://github.com/zephyrproject-rtos/zephyr/pull/48893). I do not see how this PR can be useful or productive on its own.

**Review by gmarull — APPROVED** [review]

**Comment by mmahadevan108** [comment]
Addressed as part of PR https://github.com/zephyrproject-rtos/zephyr/pull/48893

**Pull request closed without merging**
