### PR TITLE
Bluetooth: host: GATT: Lazyloading cleanup at disconnect

### PR DESCRIPTION
**Pull request by kimsekkelund**
Mark the ram version of the ccc_cfg as free after ccc has been
stored when a bonded device disconnects.
If the device use lazy loading of settings then ccc_cfg was not
cleaned up properly when a bonded device disconnects. This
resulted in the ccc system ran out of ccc_cfg resources after
having disconnected CONFIG_BT_MAX_CONN times.

Signed-off-by: Kim Sekkelund <ksek@oticon.com>

### CODE REVIEW

**Comment by kimsekkelund** [comment]
This fix might also address issue https://github.com/zephyrproject-rtos/zephyr/issues/26924

**Comment by joerchan** [comment]
> This fix might also address issue #26924

@johnsmithecon Can you check this?

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks generally good, but could this be split up into two commits? One which moves the function to the new place (which I assume is done to avoid forward declarations) and another which does the changes to the function. That way it'll be easier to see in the diff what you've changed. You might also want to add "GATT" to the subject since I thought this was about general connection cleanup in `conn.c` when I first read it.

**Review by joerchan — APPROVED** [review]
Looks good.

I was gonna say something similar about the need to move the functions. I think I would have preferred a forward declaration. I don't understand why they are avoided. I find it a bit annoying to move functions up and down because of this.

**Comment by johnsmithecon** [comment]
> > This fix might also address issue #26924
> 
> @johnsmithecon Can you check this, if you have CONFIG_BT_SETTINGS_CCC_LAZY_LOADING enabled?

I don't have any mention of CONFIG_BT_SETTINGS_CCC_LAZY_LOADING in my proj.conf file. Does this mean that it is not enabled?

**Comment by joerchan** [comment]
`BT_SETTINGS_CCC_LAZY_LOADING` is `default y` so that would probably mean that it is enabled. In `build/zephyr/.config` the final configuration can be seen.

**Comment by joerchan** [comment]
@kimsekkelund It would be best to change the title of the first commit. It doesn't reflect the contents of the commit now.

**Comment by kimsekkelund** [comment]
> @kimsekkelund It would be best to change the title of the first commit. It doesn't reflect the contents of the commit now.

I have changed the commit message for the first commit and pushed.
FYI: I will be out of office the next three weeks

**Comment by johnsmithecon** [comment]
@joerchan I can confirm that this does not fix the "No space to store CCC cfg" issue

**Comment by joerchan** [comment]
@jhedberg This one is ready.

**Review by jhedberg — APPROVED** [review]

**Comment by BeckmaR** [comment]
I am currently running into a very similar issue, sadly I'm bound to zephyr 2.2.1 due to Bluetooth SIG certification.

Why do you only clean up the CCCs when lazy loading is enabled? To me it seems like these should always be cleaned up, since that's exactly the issue I'm seeing - after disconnecting a bonded device, CCC configs are not available for the next (non-bonded) peer.

**Comment by joerchan** [comment]
@BeckmaR Do you have LazyLoading enabled? Maybe you are running into the bug that this PR fixed?
Maybe cherry-pick the fixes (2 commits)?

**Comment by BeckmaR** [comment]
@joerchan I do have lazy loading enabled, but I can sadly not cherry-pick these commits since our customer wants a clean zephyr due to BT certification issues.
However, the question I'm asking is basically whether the bug that this PR fixed isn't still there if lazy loading is disabled? 

The way I understand it, in that case (let's call it static loading), there is an additional number of ccc cfgs allocated for the paired peers:
```c
#if IS_ENABLED(CONFIG_BT_SETTINGS_CCC_LAZY_LOADING)
	#define BT_GATT_CCC_MAX (CONFIG_BT_MAX_CONN)
#else
	#define BT_GATT_CCC_MAX (CONFIG_BT_MAX_PAIRED + CONFIG_BT_MAX_CONN)
#endif
```
Let's say both values are 1, so we can store 1 paired, not connected peer's (Alice) CCCs and one currently connected, but not paired one (Bob). If Bob disconnects, his CCC config is not cleared, since lazy loading is disabled. If a third peer Carol now connects he can't store his CCC config, since Bob's is still there. So basically I think for lazy loading you can always clear all CCC configs, and for non-lazy loading you'd need to clear all CCCs of peers that are not paired - Bob - to make room for Carol.

**Comment by joerchan** [comment]
@BeckmaR If you are running into the same problem that this PR fixed then disabling CCC_LAZY_LOADING should make it go away.
If it doesn't then you are facing a different issue.

**Comment by BeckmaR** [comment]
@joerchan Disabling lazy loading did not help and I don't see any code that would reset CCCs of non-paired peers.

**Pull request merged**
