### PR TITLE
USB: Add BOS Descriptor API

### PR DESCRIPTION
**Pull request by finikorg**
Implement API for USB Binary Device Object Store descriptors. This is needed because MS OS Descriptors version 2 would use this API.

### CODE REVIEW

**Review by nashif — DISMISSED** [review]
with so many commits, please provide a summary in the PR body about this new API/Feature

**Comment by finikorg** [comment]
@nashif updated info

**Comment by jfischer-phytec-iot** [comment]
@finikorg please rebase

**Comment by finikorg** [comment]
@jfischer-phytec-iot rebased

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
