### PR TITLE
TF-M: Upmerge to v1.3.0-RC1

### PR DESCRIPTION
**Pull request by oyvindronningstad**
In preparation of TFM 1.3.

We can merge this, or wait for 1.3 to be merged first.

### CODE REVIEW

**Comment by galak** [comment]
> We can merge this, or wait for 1.3 to be merged first.

I think its find for us to merge tfm 1.3-rc1 support and update this again as future rc's and 1.3 comes out.

**Comment by oyvindronningstad** [comment]
@jamike Is it true that you maintain STM platforms in TFM? Can you help with the build error (https://buildkite.com/zephyr/zephyr/builds/24693#c5194975-659f-4d18-8e7b-64b3f35d27f8)? There seems to be a problem with flash segments overlapping between S and NS. I can't quite figure out where the different flash segments come from.

**Comment by galak** [comment]
> @jamike Is it true that you maintain STM platforms in TFM? Can you help with the build error (https://buildkite.com/zephyr/zephyr/builds/24693#c5194975-659f-4d18-8e7b-64b3f35d27f8)? There seems to be a problem with flash segments overlapping between S and NS. I can't quite figure out where the different flash segments come from.

@yestin and @erwango as well might be able to help with this.

**Comment by jamike** [comment]
Hello,
Yes the board is maintained in https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git , I tested several configuration using external flash for downloading slot with arm-none-eabi, the build and execution is OK
Which config do you used ?

**Comment by erwango** [comment]
@jamike what if we don't use external flash ? What would be required to take it into account and make use of it in a NS application (is QSPI driver support required, should we support execution from external flash) ?

**Comment by jamike** [comment]
@erwango<https://github.com/erwango> I  tested in config without external flash. It works as well .

**Comment by oyvindronningstad** [comment]
> 
> @erwango I tested in config without external flash. It works as well

@jamike What configuration did you test? Upstream TFM, or via Zephyr? Did you test this PR specifically, because that is where the error is. I have confirmed it locally, it's a build error.

To reproduce:

    west build -b stm32l562e_dk_ns samples/tfm_integration/tfm_ipc/ -p

on Zephyr commit 7e5b90718af0c967eb1a2e2001ccef5da98ae990

**Comment by erwango** [comment]
@oyvindronningstad what would be helpful is to provide the TFM configuration used in this sample application. Can you provide this ?

**Comment by oyvindronningstad** [comment]
> 
> 
> @oyvindronningstad what would be helpful is to provide the TFM configuration used in this sample application. Can you provide this ?

For example the cmake call arguments?

**Comment by erwango** [comment]
> For example the cmake call arguments?

I guess this should do, txs.

**Comment by yestin** [comment]
I am able to reproduce the build error on stm32l562e_dk board after downloading the PR and do a `west update`.

As @erwango mentioned, the new TFM release adds the external flash support for stm32l562e_dk board and is enabled by default. So the secure image is built with the flash layout that has the external flash support, but the non-secure Zephyr image is still built with the flash layout that only consider the internal flash. The mismatch has caused the build break.

After I applying the following new layout, the build seems to be successful and the image is also bootable.

```diff
--- a/samples/tfm_integration/tfm_ipc/boards/stm32l562e_dk_ns.overlay
+++ b/samples/tfm_integration/tfm_ipc/boards/stm32l562e_dk_ns.overlay
@@ -30,18 +30,18 @@

                boot_partition: partition@0 {
                        label = "mcuboot";
-                       reg = <0x00000000 0x00013000>;
+                      reg = <0x00000000 0x00019000>;
                        read-only;
                };
                /* Secure image primary slot */
-               slot0_partition: partition@00013000 {
+              slot0_partition: partition@00019000 {
                        label = "image-0";
-                       reg = <0x00013000 0x00038000>;
+                      reg = <0x00019000 0x00038000>;
                };
                /* Non-secure image primary slot */
-               slot1_partition: partition@0004B000 {
+              slot1_partition: partition@00051000 {
                        label = "image-1";
-                       reg = <0x0004B000 0x0002A000>;
+                      reg = <0x00051000 0x0002A000>;
                };
                /*
                 * The flash starting at 0x7F000 and ending at
```

**Comment by oyvindronningstad** [comment]
Thanks a lot @yestin, that worked nicely here as well.

**Review by galak — APPROVED** [review]

**Review by erwango — APPROVED** [review]
Thanks @yestin!

**Review by ioannisg — COMMENTED** [review]
Thanks @oyvindronningstad 
(Let me do some basic testing before merging this)

**Review by ioannisg — APPROVED** [review]

**Review by galak — COMMENTED** [review]
What's the upstream bug around AUDIT LOG?  Is this bug filed?  Do we know if this will be fixed as part of v1.3.0?

**Review by microbuilder — APPROVED** [review]

**Comment by oyvindronningstad** [comment]
> 
> 
> What's the upstream bug around AUDIT LOG? Is this bug filed? Do we know if this will be fixed as part of v1.3.0?

https://developer.trustedfirmware.org/T892

No movement on it yet.

**Comment by ioannisg** [comment]
Since we decided to do an upmerge, I think we have to temporarily live without the audit log, but I am confident this will be fixed for v1.3.0.

**Pull request merged**
