### PR TITLE
[Backport v3.2-branch] Update to Clang 15

### LINKED ISSUE #56067: Fix build issues with arm clang compiler for mec17xx platforms
There are a number of different failures we see when building the arm clang compiler when building the mec17xx platforms.

### PR DESCRIPTION
**Pull request by zephyrbot**
Fixes #56067

Backport 39af51372dd2020e6a2397d0b2c04797102f3775~9..39af51372dd2020e6a2397d0b2c04797102f3775 from #50049

### CODE REVIEW

**Comment by stephanosio** [comment]
@galak Since you requested this backport, could you provide some rationale on why this is necessary?

**Review by galak — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
No problem with this since the Zephyr SDK version has not changed as part of this update, and the update to Clang 15 does not introduce any breaking changes.

**Comment by stephanosio** [comment]
DNM until the node image is updated to cache the CI image v0.24.3.

**Comment by stephanosio** [comment]
> DNM until the node image is updated to cache the CI image v0.24.3.

Node image has been updated. Merging.

**Pull request merged**
