### PR TITLE
kernel: init: generate init entries as arrays

### PR DESCRIPTION
**Pull request by JordanYates**
This is an attempt to progress features that will be required by #22545, which I see as:
1. Method to specify dependencies between init objects (whether #49318 or otherwise)
2. Method to reorder init entries, based on the information gained from 1.

All ordering is currently done through linker section naming. Reordering the init entries in later linker passes cannot be done without changing the sections associated with each init entry. As this information is in the compiled object object files, this would require either recompiling the source or modifying the object files in-place. The first is not practical due to compile time considerations, the second for incremental recompilation reasons.

Generating C arrays that are then used for later linker passes will allow the tool that generates the arrays to take advantage of additional information available after the first linker pass.

This approach has two main consequences:
* All device structures must be globally visible (not static)
* Init functions must be globally visible (not static)

The first is a minor change, as only manually instantiated devices (not through devicetree) are currently static. The second is a much larger change, necessitating treewide changes. Only enough init functions are currently updated to enable `west build -b qemu_cortex_m3 zephyr/tests/lib/devicetree/devices/ -t run` to pass, to minimize noise on this PR while it is in draft.

This PR only introduces the infrastructure, and does not attempt to take advantage of any dependency information.

The generated source file looks like this for the working test:
```
/*
 * Generated by gen_init_arrays.py
 */
#include <zephyr/device.h>

/* Init functions */
int dev_init(const struct device *dev);
int sys_clock_driver_init(const struct device *dev);
int uart_console_init(const struct device *dev);
int ti_lm3s6965_init(const struct device *dev);
int uart_stellaris_init(const struct device *dev);

/* Manually instantiated devices */
extern const struct device __device_manual_dev;

/* Init Level: PRE_KERNEL_1 */
const struct init_entry init_entries_PRE_KERNEL_1[] __attribute__((__section__(".z_init_PRE_KERNEL_1"))) = {
	{.init = ti_lm3s6965_init, .dev = NULL},
	{.init = uart_stellaris_init, .dev = NULL},
	{.init = uart_stellaris_init, .dev = &__device_dts_ord_20},
	{.init = uart_stellaris_init, .dev = &__device_dts_ord_19},
	{.init = uart_stellaris_init, .dev = &__device_dts_ord_18},
	{.init = uart_console_init, .dev = NULL},
	{.init = dev_init, .dev = &__device_dts_ord_25},
};

/* Init Level: PRE_KERNEL_2 */
const struct init_entry init_entries_PRE_KERNEL_2[] __attribute__((__section__(".z_init_PRE_KERNEL_2"))) = {
	{.init = sys_clock_driver_init, .dev = NULL},
};

/* Init Level: POST_KERNEL */
const struct init_entry init_entries_POST_KERNEL[] __attribute__((__section__(".z_init_POST_KERNEL"))) = {
	{.init = dev_init, .dev = &__device_dts_ord_26},
	{.init = dev_init, .dev = &__device_dts_ord_27},
	{.init = dev_init, .dev = &__device_dts_ord_29},
	{.init = dev_init, .dev = &__device_dts_ord_28},
	{.init = dev_init, .dev = &__device_dts_ord_31},
	{.init = dev_init, .dev = &__device_dts_ord_33},
	{.init = dev_init, .dev = &__device_dts_ord_24},
	{.init = dev_init, .dev = &__device_manual_dev},
	{.init = dev_init, .dev = &__device_dts_ord_30},
};

/* Init Level: APPLICATION */
const struct init_entry init_entries_APPLICATION[] __attribute__((__section__(".z_init_APPLICATION"))) = {
};

/* Init Level: SMP */
const struct init_entry init_entries_SMP[] __attribute__((__section__(".z_init_SMP"))) = {
};
```

### CODE REVIEW

**Comment by JordanYates** [comment]
One cheap win that this sort of approach enables (without any additional dependency information), is a resolution to the problem in #47150. Examine the initial ordering for devices with the same init function/api pointer, and reorder them to respect any devicetree dependencies between them.

A more invasive diagnostic could be to produce warnings/errors if the init ordering does not match devicetree dependency ordering.

**Comment by nordicjm** [comment]
> All device structures must be globally visible (not static)
> Init functions must be globally visible (not static)

These two changes are pretty huge, the unfortunate thing is that these then present function visibility to applications which should not be visible, as possible abuse, misuse or even an attack vector, and defeats the purpose of having these functions only callable through the public API functions (if the driver allows it). I made some changes to test ordering on https://pastebin.com/UjUU1QQW with the idea of checking if a single driver with multiple possible bus types would work (SPI/I2C) but would need the additional work of re-ordering to be able to test that.

**Comment by JordanYates** [comment]
> the unfortunate thing is that these then present function visibility to applications which should not be visible, as possible abuse, misuse or even an attack vector, and defeats the purpose of having these functions only callable through the public API functions (if the driver allows it)

I agree that losing the ability to have the init functions `static` is a downside of this approach, part of posting this PR was to see if anyone could come up with an alternate solution to the problem.

I would like to dig a little deeper into your abuse/misuse/attack comment. We're compiling embedded code here, if someone absolutely wants to rerun an init function (which is going to exist in the .lst file regardless), they can just construct a pointer and jump to it. I don't see how this is any different/worse than any code being able to arbitrarily corrupt other devices by doing `((uint8_t*)(DEVICE_DT_GET(nodelabel)->data))[2]++;`. Maybe I'm missing some consideration here though.

> I made some changes to test ordering on https://pastebin.com/UjUU1QQW with the idea of checking if a single driver with multiple possible bus types would work (SPI/I2C) but would need the additional work of re-ordering to be able to test that.

Sorry I'm not sure what you're trying to say here, or how the multiple bus types are relevant.

**Comment by nordicjm** [comment]
> I agree that losing the ability to have the init functions static is a downside of this approach, part of posting this PR was to see if anyone could come up with an alternate solution to the problem.

An alternative that comes to mind would be to have this processing take place in the kernel itself, though this would mean larger output size. Then the hierarchy/dependency list would need to be presented by going through the devicetree.

> I would like to dig a little deeper into your abuse/misuse/attack comment.

One part of this is preventing application code from calling the driver functions manually without going through the API, there are drivers that do this already, e.g. https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/counter/rtc_mcp7940n.c#L395 of which I find ghastly. True, for attacks any instruction can be jumped to.

> Sorry I'm not sure what you're trying to say here, or how the multiple bus types are relevant.

Some drivers have support for different bus interfaces, so I created that, more as a note to myself, to check proper priority handling works when e.g. a board has 2 devices, which happens to be the same sensor/driver, one instance on the SPI bus and one on the I2C bus to ensure that the priority of the devices is set correctly.

**Comment by tbursztyka** [comment]
> > All device structures must be globally visible (not static)
> > Init functions must be globally visible (not static)
> 
> These two changes are pretty huge, the unfortunate thing is that these then present function visibility to applications which should not be visible, as possible abuse, misuse or even an attack vector, and defeats the purpose of having these functions only callable through the public API functions (if the driver allows it).

Non static device object is a non-issue.
Init functions on the other side, is mostly an annoyance (abuse/attack have always been there, static or not since you can access to the init entry anyway). Now one will have to make sure its device driver's init function, for instance, is unique. Annoyance being that, as long as you do not compile the 2+ drivers that use same init function name it will be fine, but as soon as you do: it will break and it will require a bit of cleaning.

@JordanYates You've been working on this issue (init ordering) for quite some time. But the root problem is how it's done in the first place: a few device instance are not (not yet at least) DTS based, the non-device related init entries (sys_init) cannot be DTS based... etc... As far as I see it, as long as it's done that way we'll be doomed to find a hack around it as you do.
For instance switching to an ideal situation such as: 
- making all devices DTS based (no manual ones anymore)
- adding a dedicated description of the sys_init, something like DTS for dedicated to sys_init in yaml/else (user would use DTS aliases to relate the devices(s) and the relevant sys_init) with its own python script.

would solve it since from the order given by DTS, then the sys_init description, all the init entries could be properly ordered, it would also remove the level/prio as well.

But it's an ideal way, and the current context is far from it. I am not saying you should stop working on this, but perhaps change the approach. That said, such hack could be an in-between solution.

**Comment by JordanYates** [comment]
> @JordanYates You've been working on this issue (init ordering) for quite some time. But the root problem is how it's done in the first place: a few device instance are not (not yet at least) DTS based, the non-device related init entries (sys_init) cannot be DTS based... etc... As far as I see it, as long as it's done that way we'll be doomed to find a hack around it as you do.

I don't have any strong opinions about requiring all devices to comes from devicetree, beyond noting that I've seen a lot of devices in the networking layers that are purely software constructs. Given the discussions I have seen about software in devicetree (i.e. not happening) I doubt this could be resolved without introducing another class of objects (devices, sys_init, soft_devices)

> adding a dedicated description of the sys_init, something like DTS for dedicated to sys_init in yaml/else (user would use DTS aliases to relate the devices(s) and the relevant sys_init) with its own python script.

To solve this completely, the following dependency information needs to be able to be expressed:
- [x]  Device that depends on other device (Devicetree currently solves)
- [ ]  Device that depends on SYS_INIT
- [ ]  SYS_INIT that depends on device
- [ ]  SYS_INIT that depends on SYS_INIT

Only the first is provided by devicetree, but the devicetree/device model needs to be extended to handle the second.
The options for doing so are:
1. Devicetree itself (Minimal chance of acceptance)
2. Devicetree binding files (Minimal chance of acceptance)
3. At the location of device instantiation (#49318 approach, also solves 3rd and 4th requirements)
4. A new associated file (yaml or otherwise)

I am not convinced that the overhead of adding a new type of file (and all the infrastructure that implies) would be a net gain over simply requiring uniqueness of SYS_INIT function names. The advantage is obviously that the init orders could be determined BEFORE any source is compiled, removing the need for parsing the `.elf`. In a completely greenfield scenario I could maybe see this working, if we had a `softtree` (devicetree but for software) instead of Kconfig. But all the extra utility that a `softtree` could provide (properties, bindings etc) over dependencies are currently provided by Kconfig.

Absent `softtree` and the removal of Kconfig, I see this:
```
SYS_INIT(my_init_function);
SYS_INIT_DEPENDS_ON(my_init_function , DT_ALIAS(console), SYS_INIT_REF(KERNEL));

DEVICE_DT_DEFINE(my_nodelabel, ...);
DEVICE_DT_DEPENDS_ON(my_nodelabel , SYS_INIT_REF(KERNEL));
```
As superior to:
```
my_code_subsystem:
  enabled_with: CONFIG_CONSOLE && CONFIG_MY_SUBSYS
  depends_on:
    - dt_alias(console)
    - kernel

some_device:
  nodelabel: my_nodelabel
  depends_on:
    - kernel
```
```
SYS_INIT_NEW(my_code_subsystem, my_init_function);
DEVICE_DT_DEFINE(my_nodelabel, ...);
```

If that is the way that the project wants to go that is fine, I just probably won't have the time to implement such a wide-ranging feature.

**Comment by tbursztyka** [comment]
> I don't have any strong opinions about requiring all devices to comes from devicetree, beyond noting that I've seen a lot of devices in the networking layers that are purely software constructs. Given the discussions I have seen about software in devicetree (i.e. not happening) I doubt this could be resolved without introducing another class of objects (devices, sys_init, soft_devices)

I meant something about that yes. Pure hw devices would come from DTS, and the "in-between layer" would provide the rest (pure sys_init and soft-devices indeed), but... (see below)

>     1. Devicetree itself (Minimal chance of acceptance)
> 
>     2. Devicetree binding files (Minimal chance of acceptance)
> 

Yep it's never going to happen. Issue being that DTS is meant to be OS agnostic it seems, or at least that's the goal.

> I am not convinced that the overhead of adding a new type of file (and all the infrastructure that implies) would be a net gain over simply requiring uniqueness of SYS_INIT function names. The advantage is obviously that the init orders could be determined BEFORE any source is compiled, removing the need for parsing the `.elf`. 

What worries me is that knowing how badly our init ordering is flawed: hacking around it is probably not going to be solid enough. Currently, it's almost 100% manual ordering. With your PR it adds some automation to fix any potential manual errors. Thus my point: why not going full automatic, but again: 

> In a completely greenfield scenario I could maybe see this working, if we had a `softtree` (devicetree but for software) instead of Kconfig. But all the extra utility that a `softtree` could provide (properties, bindings etc) over dependencies are currently provided by Kconfig.

Yes exactly... Kconfig is on the way. It is partially acting like a softtree but it's not meant for it and thus does a poor job there.
However, I don't see a softtree working on its own without Kconfig since this one is nice for enabling big software features/subsystems, the softtree would use the Kconfig options to know which sys_init/soft_devices are then present. 
  
> If that is the way that the project wants to go that is fine, I just probably won't have the time to implement such a wide-ranging feature.

yes it's a tremendous amount of work. The softtree is imo much cleaner and solid in the long run but: we still have some parts of Kconfig that should belong to DTS (pure hw config stuff), manual hw device instance that should go DTS, and this is the tip of the iceberg that needs to be cleaned up *before* starting to introduce any softtree. And then we must ensure that such mess does not get introduced again...

Perhaps your approach is in fine the most realistic one. I am not blocking this PR because of that. Let's see what others think.

**Comment by JordanYates** [comment]
> Currently, it's almost 100% manual ordering. With your PR it adds some automation to fix any potential manual errors. Thus my point: why not going full automatic

This is meant to be the other side of #49318. It provides the "automatic" dependency info, this provides the mechanism to act upon it. I split it up to ease review. Assuming both sides are accepted, it's just a matter of playing with `gen_init_entries.py` to automatically order everything.

**Pull request closed without merging**
