### PR TITLE
boards nrfbsim docs: Explain relation between native sim and nrfbsim

### PR DESCRIPTION
**Pull request by aescolar**
Add a section to the docs ellaborating on the relationship between Zephyr, the native simulator, the nRF HW models and BabbleSim.

Link to rendered docs (when completed) 
https://builds.zephyrproject.io/zephyr/pr/78480/docs/boards/native/doc/bsim_boards_design.html#id8

### CODE REVIEW

**Review by theob-pro — DISMISSED** [review]
A nice thing that could be done is to export the SVG so it can adapt according to light/dark theme. You can do that with draw.io, at the export you need to select `Appearance: Automatic`:

Screenshot of the SVG export window of draw.io

Other than that the explanation is clear.

**Comment by aescolar** [comment]
> A nice thing that could be done is to export the SVG so it can adapt according to light/dark theme. You can do that with draw.io, at the export you need to select `Appearance: Automatic`:

Thanks @theob-pro . I tried to do the change, though I do not know how to test the local render of the pages in dark mode. So let's see if it looks good after the PR docs build :)

**Comment by theob-pro** [comment]
> > A nice thing that could be done is to export the SVG so it can adapt according to light/dark theme. You can do that with draw.io, at the export you need to select `Appearance: Automatic`:
> 
> Thanks @theob-pro . I tried to do the change, though I do not know how to test the local render of the pages in dark mode. So let's see if it looks good after the PR docs build :)

Tested it, it looks good :slightly_smiling_face: 
Screenshot of the rendered documentation added in this PR in dark mode

**Review by theob-pro — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]
thanks

**Comment by kartben** [comment]
> A nice thing that could be done is to export the SVG so it can adapt according to light/dark theme. You can do that with draw.io, at the export you need to select `Appearance: Automatic`:
> 
> Screenshot of the SVG export window of draw.io
> Other than that the explanation is clear.

@aescolar Actually, can you please also make sure tick the "Include a copy of my diagram" box? This way the svg can be edited way more easily by anyone later, as it will just load in drawio as if it were a "native" diagram.

**Comment by aescolar** [comment]
> Actually, can you please also make sure tick the "Include a copy of my diagram" box? 

@kartben Done

**Review by theob-pro — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Pull request merged**
