### PR TITLE
susbsys: settings: optimized fcb compression for deleted entry

### PR DESCRIPTION
**Pull request by nvlsianpu**
During the compression an empty settings entry was
copied to the scratch sector form the oldest sector in case
lack of newer entry version in fcb storage.

This doesn't make sense as empty entry and lack of entry has
similar meaning.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@jhe - I can add test for this patch in few days. In case you won't wait this can be merged earlier.

**Comment by jhedberg** [comment]
@nvlsianpu any update on testing this patch?

**Comment by carlescufi** [comment]
@jhedberg I believe @nvlsianpu has the 1.12 coverity issues to deal with (we need to get them down to be able to release) so this might be slightly delayed.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@nvlsianpu is this tested?

**Comment by nvlsianpu** [comment]
I'm writing test for this right now.

**Comment by nvlsianpu** [comment]
@carlescufi @jhedberg I have added the test.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
