### PR TITLE
nRF54H20 EngB fixes

### PR DESCRIPTION
**Pull request by 57300**
Certain Kconfigs were only enabled for or in relation to nRF54H20 EngC (default chip revision). Align EngB as well.

### CODE REVIEW

**Review by nordicjm — CHANGES_REQUESTED** [review]
Engineering B is being removed: https://github.com/zephyrproject-rtos/zephyr/pull/80163

**Comment by 57300** [comment]
> Engineering B is being removed: #80163

We should not remove it until NCS 2.8.0 is released.

**Comment by carlescufi** [comment]
> > Engineering B is being removed: #80163
> 
> We should not remove it until NCS 2.8.0 is released.

Let's do that then, agreed. Let's merge this first and then merge #80163

**Review by carlescufi — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Comment by 57300** [comment]
Added remaining changes that I missed yesterday. I haven't updated tests, assuming we don't need EngB coverage upstream.

**Review by anangl — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by masz-nordic — APPROVED** [review]

**Comment by tmon-nordic** [comment]
`west build -p -b nrf54h20dk@0.8.0/nrf54h20/cpuapp -d build-cdc-fp1/ samples/subsys/usb/cdc_acm/ -- -DCONF_FILE=usbd_next_prj.conf` fails with nrf-regtool 7.0.0:
```
-- Found nrf-regtool (found suitable version "7.0.0", minimum required is "5.6.0")
Usage: nrf-regtool generate [OPTIONS]
Try 'nrf-regtool generate -h' for help.

Error: Invalid value: Generating from DTS is only supported for peripheral BICR
```

**Comment by 57300** [comment]
> `west build -p -b nrf54h20dk@0.8.0/nrf54h20/cpuapp -d build-cdc-fp1/ samples/subsys/usb/cdc_acm/ -- -DCONF_FILE=usbd_next_prj.conf` fails with nrf-regtool 7.0.0:
> 
> ```
> -- Found nrf-regtool (found suitable version "7.0.0", minimum required is "5.6.0")
> Usage: nrf-regtool generate [OPTIONS]
> Try 'nrf-regtool generate -h' for help.
> 
> Error: Invalid value: Generating from DTS is only supported for peripheral BICR
> ```

I haven't rebased this PR on top of ff70e2f4c44d3e2cfbe2d03b846c2ee570086905, which is needed for nrf-regtool 7.0.0 to work. You may consider rebasing it locally, or waiting ~3h for this PR to be mergeable.

**Review by tmon-nordic — APPROVED** [review]

**Pull request merged**
