### PR TITLE
samples: bluetooth: ipsp: Bump max number of contexts

### PR DESCRIPTION
**Pull request by pfalcon**
This sample includes builtin UDP and TCP echo servers, max
MAX_CONTEXTS=3 as set previously, they just didn't work.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
I have a feeling that @galak and @nashif are now set as code owners for every patch. If being a code owner means that patch is blocked until they review it, it sucks, e.g. nothing in this patch requires @galak and @nashif involvement.

**Comment by pfalcon** [comment]
Spotted while testing https://github.com/zephyrproject-rtos/zephyr/pull/803 and friends. I'd also like to draw attention to other issues ipsp sample has: https://jira.zephyrproject.org/browse/ZEP-2422 , https://jira.zephyrproject.org/browse/ZEP-2423 .

**Review by mbolivar — COMMENTED** [review]
I'm confused about how this is a fix. In main.c, get_context() calls net_context_get() exactly three times. That's the only place I see where net_context_get() is called in this sample. Is there something behind the scenes which is getting the other three?

**Comment by pfalcon** [comment]
The aim: ensure that ipsp sample works (i.e. pumps IPv6 packets).

The tool of choice: ping6. Outcome: ICMP is broken: https://jira.zephyrproject.org/browse/ZEP-2422

Studying ipsp shows that it also sets up listening contexts for UDP and TCP on port 4242 (thus, duplicating echo_server functionality).

The next tool of choice: telnet. Outcome: connection immediately closed.

Enabling global logging, among few hundreds lines a line found along the "failed to allocate accept context".

Bumping max ctx num allows to telnet echo to work, and even in that run, ping6 randomly worked too: https://jira.zephyrproject.org/browse/ZEP-2422?focusedCommentId=19394&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19394

**Comment by mbolivar** [comment]
I see. So there are some extra contexts that are in use that aren't apparent from the application source. Thanks!

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
