### PR TITLE
ztest: Update the new ZTEST APIs tests/net/socket/[o-s]*

### PR DESCRIPTION
**Pull request by hunterhu3000**

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]

**Comment by enjiamai** [comment]
Hi, @hunterhu3000 , I did not see you used ZTEST_USER instead of old ztest_user_unit_test(), is there any reason we did not use it?

**Comment by hunterhu3000** [comment]
> Hi, @hunterhu3000 , I did not see you used ZTEST_USER instead of old ztest_user_unit_test(), is there any reason we did not use it?

Yes, I'll modify and push another patch. Thank you

**Comment by hunterhu3000** [comment]
in tests/net/socket/socketpair, there are tests both in kernel space and user space. Both of them will call k_work_submit(). There is a global variable k_sys_work_q in it. I wonder if this global variable is in kernel space, the user space test will fail. (Correct me if I'm wrong)
If we have to test the fuctions in kernel space and user space, I think it would be safe to split them into two parts, one for ZTEST and the other for ZTEST_USER

**Comment by enjiamai** [comment]
> in tests/net/socket/socketpair, there are tests both in kernel space and user space. Both of them will call k_work_submit(). There is a global variable k_sys_work_q in it. I wonder if this global variable is in kernel space, the user space test will fail. (Correct me if I'm wrong) If we have to test the fuctions in kernel space and user space, I think it would be safe to split them into two parts, one for ZTEST and the other for ZTEST_USER

Hi @hunterhu3000 , my suggestion:
1. We should have a setup function to run k_thread_system_pool_assign(k_current_get()) first; ( This will be in kernel space.)
2. Then you can define ZTEST_USER(xxx) for all the ztest_user_unit_test(xxx).
3. You don't have to add #ifndef TEST_IN_USERSPACE and extra "net.socket.socketpair.user" for them.

**Comment by hunterhu3000** [comment]
> > in tests/net/socket/socketpair, there are tests both in kernel space and user space. Both of them will call k_work_submit(). There is a global variable k_sys_work_q in it. I wonder if this global variable is in kernel space, the user space test will fail. (Correct me if I'm wrong) If we have to test the fuctions in kernel space and user space, I think it would be safe to split them into two parts, one for ZTEST and the other for ZTEST_USER
> 
> Hi @hunterhu3000 , my suggestion:
> 
> 1. We should have a setup function to run k_thread_system_pool_assign(k_current_get()) first; ( This will be in kernel space.)
> 2. Then you can define ZTEST_USER(xxx) for all the ztest_user_unit_test(xxx).
> 3. You don't have to add #ifndef TEST_IN_USERSPACE and extra "net.socket.socketpair.user" for them.

The patch still have some problems. Let me find out a better way to update the test case.

**Comment by hunterhu3000** [comment]
The PR contains too many patches and not easy to maintain. I'll split it into several PRs.

**Pull request closed without merging**
