### PR TITLE
scripts: unify unit testing

### PR DESCRIPTION
**Pull request by gmarull**
The idea behind these changes is to have a single place for scripts unit testing. As of today, there are at least two places where one can find pytest based tests: `tests` and `west_commands/tests`. `dts` also has its own set of tests, but it looks like it will be moved to a standalone library so I haven't done anything there. Having a single place for tests makes things easier, for things such as: shared fixtures, single entry point for CI, etc.

### CODE REVIEW

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Putting a -1 on this for now as I don't think a common folder is necessarily the right thing.

These scripts have different requirements on their test environments and I think it's good that they are allowed to differ.

**Comment by gmarull** [comment]
> Putting a -1 on this for now as I don't think a common folder is necessarily the right thing.
> 
> These scripts have different requirements on their test environments and I think it's good that they are allowed to differ.

The idea is to have a folder for the common cases, that does not force people to use it (e.g. `dts` has its own set of tests). I think pytest is flexible enough to accommodate different needs, e.g. we can have tags, multiple conftest.py for fixtures/specifics that only apply to tests on a subfolder, etc.

What I'd like is to have a place to add my `test_x.py` unit-test suite and see that CI exercises it without more effort. Stuff like `scripts/west_commands/run_tests.py` or a custom `README.md` for twister tests makes things unnecessarily complex and more difficult to maintain. If we talk about system-level testing, then I understand that requirements may be more diverse and it may justify a completely separate CI/test suite.

**Comment by mbolivar-nordic** [comment]
OK, then I don't think the west command tests belong in the common folder :)

Have you considered using tox instead?

**Comment by gmarull** [comment]
> OK, then I don't think the west command tests belong in the common folder :)
> 

they can be left alone then, but having something like `scripts/west_commands/run_tests.py` raises my eyebrows. In the end, one can always do `pytest tests/west_commands` to just run `west_commands` tests. I still don't see why they have specific needs.

> Have you considered using tox instead?

I'm not a fan of tox, but it can be added to have the "run tox to check all" as an optional thing. If there is intereset in moving this forward I can add it, otherwise I'll need to create yet another workflow to handle some tests I'm planning to add and that do not fit in any of the current setups as they are specific to either west_commands or twister.

**Comment by mbolivar-nordic** [comment]
> having something like `scripts/west_commands/run_tests.py` raises my eyebrows.

Yeah, I agree it's weird. I added it because I wanted it to be easy for people to run the tests on their local machines in both Windows and Linux.

**Pull request closed without merging**
