### PR TITLE
kernel: sem: Ensure that initial count is lesser or equal than limit

### PR DESCRIPTION
**Pull request by lpereira**
Ensure this value during static initialization (with build assertions),
and dynamic initializations through system calls.

If initial count is larger than the limit, it's possible for the count
to wraparound, causing locking issues.

Signed-off-by: Leandro Pereira <leandro.pereira@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]
LGTM

**Comment by andrewboie** [comment]
recheck

**Comment by lpereira** [comment]
BUILD_ASSERT() seems to be quite broken -- fixed some of it in this PR, but happy to split.

**Comment by lpereira** [comment]
Found a way to workaround the seemingly spurious warning that GCC was generating.  Force-pushed to test in CI.

**Review by nashif — APPROVED** [review]

**Pull request merged**
