### PR TITLE
Bluetooth: tbs: change notifications

### PR DESCRIPTION
**Pull request by piotrnarajowski**
Change notifications for tbs functions. This is needed to reproduce this [issue](https://github.com/zephyrproject-rtos/zephyr/issues/68173).
work in progress

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
@Thalley This is an RFC, could you please take a look? Came across this issue while going through TBS tests that require updating characteristic values with value len > ATT_MTU-3. Without this workaround, bt_gatt_notify_uuid doesn't work and returns -ENOMEM

**Comment by piotrnarajowski** [comment]
@Thalley I can't realy find the way to make one generic ntf function...

**Comment by Thalley** [comment]
> @Thalley I can't realy find the way to make one generic ntf function...

I don't have a line-by-line solution either, but possible the way that MCS implements it could be useful as inspiration: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/mcs.c#L965-L995

**Comment by Thalley** [comment]
As discussed with @sjanc the right solution may be to implement/fix https://github.com/zephyrproject-rtos/zephyr/issues/64175

**Pull request closed without merging**
