### PR TITLE
drivers: spi: Support NXP i.MX ECSPI

### PR DESCRIPTION
**Pull request by pdgendt**
Add a driver implementation for NXP's Enhanced Configurable SPI.

### CODE REVIEW

**Review by tbursztyka — COMMENTED** [review]
Overall, it looks fine to me.

One question however: does the HAL let you access the hw on a lower level so you could avoid doing a local copy (tx_data/rx_data)?  If not then, well it's a HAL issue we can't fix.

**Comment by pdgendt** [comment]
> Overall, it looks fine to me.
> 
> One question however: does the HAL let you access the hw on a lower level so you could avoid doing a local copy (tx_data/rx_data)? If not then, well it's a HAL issue we can't fix.

I'll look into this.

**Comment by pdgendt** [comment]
> One question however: does the HAL let you access the hw on a lower level so you could avoid doing a local copy (tx_data/rx_data)? If not then, well it's a HAL issue we can't fix.

@tbursztyka not sure if there is a way around this, from `modules/hal/nxp/mcux/mcux-sdk/devices/MIMX8ML8/MIMXML8_cm7.h`:

```c
/*! BURST_LENGTH
 *  0b000000000000..A SPI burst contains the 1 LSB in a word.
 *  0b000000000001..A SPI burst contains the 2 LSB in a word.
 *  0b000000000010..A SPI burst contains the 3 LSB in a word.
 *  0b000000011111..A SPI burst contains all 32 bits in a word.
 *  0b000000100000..A SPI burst contains the 1 LSB in first word and all 32 bits in second word.
 *  0b000000100001..A SPI burst contains the 2 LSB in first word and all 32 bits in second word.
 *  0b111111111110..A SPI burst contains the 31 LSB in first word and 2^7 -1 words.
 *  0b111111111111..A SPI burst contains 2^7 words.
 */
```

**Comment by decsny** [comment]
> I've added the i.MX 8MP EVK board for the `spi_loopback` test so it builds using CI, however it would be nice if someone could verify if the tests actually works as I don't have the hardware.
> 
> @dleach02 anyone from NXP that could help out here?

@iuliana-prodan

**Comment by iuliana-prodan** [comment]
> > I've added the i.MX 8MP EVK board for the `spi_loopback` test so it builds using CI, however it would be nice if someone could verify if the tests actually works as I don't have the hardware.
> > @dleach02 anyone from NXP that could help out here?
> 
> @iuliana-prodan

@pdgendt @decsny I'm sorry, but I cannot help you here. This code runs on M7 core and I'm in charge of the DSP from i.MX8MPlus. :)
We usually run Linux on A core and start the DSP (with Zephyr) from Linux.
I believe @JiafeiPan can help here, he's the codeowner of mimx8mp_evk.

@JiafeiPan can you, please, verify this PR?

**Comment by JiafeiPan** [comment]
> > > I've added the i.MX 8MP EVK board for the `spi_loopback` test so it builds using CI, however it would be nice if someone could verify if the tests actually works as I don't have the hardware.
> > > @dleach02 anyone from NXP that could help out here?
> > 
> > 
> > @iuliana-prodan
> 
> @pdgendt @decsny I'm sorry, but I cannot help you here. This code runs on M7 core and I'm in charge of the DSP from i.MX8MPlus. :) We usually run Linux on A core and start the DSP (with Zephyr) from Linux. I believe @JiafeiPan can help here, he's the codeowner of mimx8mp_evk.
> 
> @JiafeiPan can you, please, verify this PR?

Sorry for late response, will look at this PR.

**Comment by JiafeiPan** [comment]
> > > > I've added the i.MX 8MP EVK board for the `spi_loopback` test so it builds using CI, however it would be nice if someone could verify if the tests actually works as I don't have the hardware.
> > > > @dleach02 anyone from NXP that could help out here?
> > > 
> > > 
> > > @iuliana-prodan
> > 
> > 
> > @pdgendt @decsny I'm sorry, but I cannot help you here. This code runs on M7 core and I'm in charge of the DSP from i.MX8MPlus. :) We usually run Linux on A core and start the DSP (with Zephyr) from Linux. I believe @JiafeiPan can help here, he's the codeowner of mimx8mp_evk.
> > @JiafeiPan can you, please, verify this PR?
> 
> Sorry for late response, will look at this PR.

@pdgendt I tested your PR on imx8mp_evk with application tests/drivers/spi/spi_loopback/,  the Zephyr is crash with the following log:
*** Booting Zephyr OS build v3.6.0-342-ga6d725857128 ***
Running TESTSUITE spi_loopback
===================================================================
START - test_spi_loopback
I: SPI test on buffers TX/RX 0x200002e0/0x200002c0, frame size = 8
I: SPI test slow config
I: Start complete multiple
I: Passed
I: Start complete loop
I: Passed
I: Start null tx
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x0
E: r0/a1:  0x30820000  r1/a2:  0x00000000  r2/a3:  0x20000100
E: r3/a4:  0x00000012 r12/ip:  0x00007461 r14/lr:  0x0000332d
E:  xpsr:  0x81000000
E: Faulting instruction address (r15/pc): 0x00003054
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x200002f8 (test_spi_loopback)
E: Halting system

So please investigate this issue.

**Review by JiafeiPan — CHANGES_REQUESTED** [review]
Please fix crash issue firstly.

**Comment by JiafeiPan** [comment]
> Hey @JiafeiPan,
> 
> Thanks for testing, may I ask how you run/test this?

bootup imx8mp-evk board into uboot command line, then execute `tftp 0x48000000 imx8mp/zephyr.bin;  cp.b 0x48000000 0x7e0000 20000; bootaux 0x7e0000`

**Comment by pdgendt** [comment]
> Please fix crash issue firstly.

@JiafeiPan With the latest version I can run the `spi_loopback` test successully!

```
SUITE PASS - 100.00% [spi_loopback]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.070 seconds
 - PASS - [spi_loopback.test_spi_loopback] duration = 0.070 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

@tbursztyka I tried to improve the driver with using a dynamic burst mechanism (like in linux [`drivers/spi/spi-imx.c`](https://github.com/torvalds/linux/blob/master/drivers/spi/spi-imx.c)) to tx/rx entire buffers in one go, but didn't find a way to make it work.

This can be done in a follow-up PR.

**Comment by Fladdan** [comment]
Hi @pdgendt

I use your ecspi driver since a while from your forked zephyr repo since a while for testing on an imx8mp. What I canged was enabling the clocks for the ECSPI peripherals. e.g. `CLOCK_EnableClock(kCLOCK_Ecspi1);` in the soc.c. 

I try to test your current code on my EVK as well.

I'm not so familiar with the CI hardware tests of Zephyr. is there really an EVK board connected to the CI?

**Comment by pdgendt** [comment]
> I use your ecspi driver since a while from your forked zephyr repo since a while for testing on an imx8mp. What I canged was enabling the clocks for the ECSPI peripherals. e.g. `CLOCK_EnableClock(kCLOCK_Ecspi1);` in the soc.c.
> 
> I try to test your current code on my EVK as well.
> 
> I'm not so familiar with the CI hardware tests of Zephyr. is there really an EVK board connected to the CI?

Hi @Fladdan,

The previous driver implementation has some flaws, there are still optimizations that can be done with using the burst mechanism, but I don't have the bandwidth to continue on that.

I'm not sure if the CI will always run tests on actual hardware, but at least we need to have the option. This way NXP (or other developers) can verify if the driver works properly.

**Comment by pdgendt** [comment]
Rebase on latest `main`

@JiafeiPan care to review & test?

**Comment by pdgendt** [comment]
Updated HAL revision and rebased on latest `main`

**Review by JiafeiPan — DISMISSED** [review]
Verified on imx8mp,  all test pass:

```
Booting Zephyr OS build v3.6.0-1572-gf2948833b18f
Running TESTSUITE spi_loopback
===================================================================`
START - test_spi_loopback

I: SPI test on buffers TX/RX 0x200001e0/0x200001c0, frame size = 8
I: SPI test slow config
I: Start complete multiple
I: Passed
I: Start complete loop
I: Passed
I: Start null tx
I: Passed
I: Start half start
I: Passed
I: Start half end
I: Passed
I: Start every 4
I: Passed
I: Start rx bigger than tx
I: Passed
I: Start async call
I: Passed
I: SPI test fast config
I: Start complete multiple
I: Passed
I: Start complete loop
I: Passed
I: Start null tx
I: Passed
I: Start half start
I: Passed
I: Start half end
I: Passed
I: Start every 4
I: Passed
I: Start rx bigger than tx
I: Passed
I: Start async call
I: Passed
I: Start complete loop
I: Passed
I: Start complete loop
I: Passed
I: All tx/rx passed
 PASS - test_spi_loopback in 0.069 seconds
===================================================================
TESTSUITE spi_loopback succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [spi_loopback]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.069 seconds
 - PASS - [spi_loopback.test_spi_loopback] duration = 0.069 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Review by decsny — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Comment by pdgendt** [comment]
@tbursztyka Friendly ping

**Comment by pdgendt** [comment]
Rebased (again) due to HAL changes

**Review by decsny — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
