### PR TITLE
Master branch hotfix: sanitycheck filter broken

### LINKED ISSUE #20371: Sanitycheck filtering broken
As of now, in the master branch, the sanitycheck filtering is broken for boards without DTS, as some tests will be unfiltered if the board does not have DTS info (the default behavior should probably have been the opposite, but never mind that now)

This was introduced in #20204, and partially fixed in #20365

For more info see https://github.com/zephyrproject-rtos/zephyr/pull/20119#issuecomment-550134769

### PR DESCRIPTION
**Pull request by aescolar**
#20204 broke master for boards without DTS
#20365 tried to partially fix it, but the filtering in
sanitycheck remained broken
Let's quickly revert it to allow other PRs to come in,
and then resubmit them in a separate PR.

Fixes #20371

### CODE REVIEW

**Comment by galak** [comment]
How is filtering broken?  how to reproduce the issue?

**Review by galak — CHANGES_REQUESTED** [review]
Before we merge this would like to understand how things are broken and see if we can fix the issue vs reverting things.

**Comment by stephanosio** [comment]
@galak 
https://github.com/zephyrproject-rtos/zephyr/pull/20119#issuecomment-550134769
https://github.com/zephyrproject-rtos/zephyr/pull/20119#issuecomment-550188228
https://github.com/zephyrproject-rtos/zephyr/pull/20119#issuecomment-550194806

**Comment by aescolar** [comment]
@galak please see the description in the issue #20371 I just wrote

**Comment by aescolar** [comment]
@galak all I'm trying to do is to do the quickest patch we can here (which by default is a revert), so master is backup.
Then we can discuss about the solution a bit more calmly (I need to run to a 1.5h meeting now)

**Comment by ioannisg** [comment]
> Before we merge this would like to understand how things are broken and see if we can fix the issue vs reverting things.

@galak that's totally fair of course. Would you mind taking a look at the failures in #20152 ? Seems nrf52_bsim is picked for mem_protection tests, which it should not, cause user mode is supported in x86, arc, arm, not posix. That's how I ran into this issue, in the first place.

**Comment by stephanosio** [comment]
@galak Technically, it is only "broken" if a board does not have dts (e.g. nrf52_bsim does not have a dts).

**Comment by aescolar** [comment]
Note that it is also broken for off-tree boards without DTS (so just adding an empty dts file for the nrf52_bsim does not fix that)

**Comment by galak** [comment]
got a fix, or at least one that makes `./scripts/sanitycheck -v -p nrf52_bsim -l ` this work.

**Comment by galak** [comment]
Take a look at #20373.  This should hopefully fix the issue.

**Pull request closed without merging**
