### PR TITLE
stm32  with external NOR ospi flash in MemoryMapped mode

### PR DESCRIPTION
**Pull request by FRASTM**
This PR is enabling the MemoryMapped to access the octo NOR flash  at the end of the initialization.
With this configuration, the NOR flash access is done with memcopy in read or write
Note that the erase is not supported but writing is possible in MemoryMapped mode.
(It is not recommended to fill the memory with 0xFFFFFFFF)

The drivers detects the CONFIG_STM32_MEMMAP flag to enable the MemoryMapped mode.

### CODE REVIEW

**Comment by FRASTM** [comment]
Add a commit to enable the ospi NOR flash of the stm32h7b3i_dk in MemoryMapped mode
requires mpu region definition

**Comment by de-nordic** [comment]
> This PR is enabling the MemoryMapped to access the octo NOR flash at the end of the initialization. With this configuration, the NOR flash access is done with memcopy in read or write Note that the erase is not supported but writing is possible in MemoryMapped mode. (It is not recommended to fill the memory with 0xFFFFFFFF)

Maybe this could be useful here https://github.com/zephyrproject-rtos/zephyr/issues/62228.

**Comment by Laczen** [comment]
@FRASTM, thanks for the PR.

Is my conclusion correct that when using XIP and memory mapped mode there is no part of the flash device that can be used by a fs (that always need an erase) ?

**Comment by FRASTM** [comment]
> @FRASTM, thanks for the PR.
> 
> Is my conclusion correct that when using XIP and memory mapped mode there is no part of the flash device that can be used by a fs (that always need an erase) ?

Yes, "Memory-mapped mode: This mode mounts the Flash chip as read-only memory in the STM32’s internal memory space"

**Comment by Laczen** [comment]
> > @FRASTM, thanks for the PR.
> > Is my conclusion correct that when using XIP and memory mapped mode there is no part of the flash device that can be used by a fs (that always need an erase) ?
> 
> Yes, "Memory-mapped mode: This mode mounts the Flash chip as read-only memory in the STM32’s internal memory space"

Probably I am missing something. Why is a flash driver created for read-only memory ?

**Comment by Laczen** [comment]
@FRASTM Is it not possible to use the flash in memory map mode while keeping the ability to write and erase the flash ?

**Comment by FRASTM** [comment]
> @FRASTM Is it not possible to use the flash in memory map mode while keeping the ability to write and erase the flash ?

No, the MemMap is used for XiP, so reading-only

**Comment by Laczen** [comment]
> > @FRASTM Is it not possible to use the flash in memory map mode while keeping the ability to write and erase the flash ?
> 
> No, the MemMap is used for XiP, so reading-only

I don't think that it is needed for the MemMap mode to create a flash driver.

If a flash driver is created all functionality should be available. This is possible if the flash driver with MemMap support would be created that supports flash writing and erasing by going out of MemMap mode (copying some routines to ram, disabling interrupts, ...), doing the write/erase in "indirect" mode and then restoring the MemMap mode. Is this the ultimate goal of the PR ?

**Comment by FRASTM** [comment]
rebase on 9019e468392a22e274282517a037c079ab1592c0
Define the CONFIG_STM32_MEMMAP for stm32 ospi flash driver (--> required when building the mcuboot  with sysbuild)

**Comment by FRASTM** [comment]
rebase on release 3.5.0

**Comment by Laczen** [comment]
@FRASTM, is it not possible (like e.g. in `flash_mcux_flexspi_hyperflash.c`) to enable also the flash erase and write in the XIP (MEMMAP) case?

**Comment by FRASTM** [comment]
When the CONFIG_STM32_MEMMAP is set
this version adds an Abort function to resume the MemoryMapped mode, so that erasing is possible and restore the MemoryMapped mode after completion
Note that flash read and write are using memcpy.

**Comment by Laczen** [comment]
> When the CONFIG_STM32_MEMMAP is set this version adds an Abort function to resume the MemoryMapped mode, so that erasing is possible and restore the MemoryMapped mode after completion Note that flash read and write are using memcpy.

Nice, if write works with memcpy that is OK. Is it not needed to disable irq's when memory mapped mode is aborted (would there be irq code that is not available during the erase) ?

**Comment by FRASTM** [comment]
Rebase on d7873e25fdd88c8740ef7ba9ef1ca5c3ef1bce5c
Requires https://github.com/zephyrproject-rtos/zephyr/pull/67989
Requires MCUboot PR https://github.com/zephyrproject-rtos/mcuboot/pull/112
Add an example samples/subsys/fs/littlefs/  where the application is running in external NOR memory (XiP) and  where the lfs1 partition is in internal MCU memory.

The slot1 where to execute the application is located in external flash memory and chosen  as `zephyr,code-partition = &slot1_partition;`

1. building/linking The sample application with 
> west build -p always -b b_u585i_iot02a samples/subsys/fs/littlefs/ --sysbuild    
 -DCONFIG_FLASH_BASE_ADDRESS=0x70000000
 -DSB_CONFIG_BOOTLOADER_MCUBOOT=y

2. sign The sample application with 
> west sign -t imgtool -- --key ../bootloader/mcuboot/root-rsa-2048.pem

3. load   sample application with STM32CubeProgrammer at address of the external flash slot1
> ~/STMicroelectronics/STM32CubeProgrammer/bin/STM32_Programmer_CLI -c port=swd -el ~/STMicroelectronics/STM32CubeProgrammer/bin/ExternalLoader/MX25LM51245G_STM32U585I-IOT02A.stldr -d build/littlefs/zephyr/zephyr.signed.bin 0x70100000 -rs

**Comment by FRASTM** [comment]
*** Booting Zephyr OS build zephyr-v3.5.0-3956-gbea3951f1683 ***
I: Starting Direct-XIP bootloader
I: Image 0 Primary slot: Image not found
I: Secondary slot: version=0.0.0+0
I: Image 0 loaded from the secondary slot
I: Bootloader chainload address offset: 0x100000
I: Jumping to the image slot
I: NOR init'd in MemMapped mode

I: littlefs partition at /lfs1
I: LittleFS version 2.5, disk version 2.0
I: FS at flash-controller@40022000:0xd0000 is 8 0x2000-byte blocks with 512 cyce
I: sizes: rd 256 ; pr 256 ; ca 4096 ; la 256
I: Automount /lfs1 succeeded
*** Booting Zephyr OS build zephyr-v3.5.0-3956-gbea3951f1683 ***
Sample program to r/w files on littlefs
Area 0 at 0xd0000 on flash-controller@40022000 for 65536 bytes
/lfs1 automounted
/lfs1: bsize = 256 ; frsize = 8192 ; blocks = 8 ; bfree = 6
                                                                                
Listing dir /lfs1 ...                                                           
[FILE] boot_count (size = 1)                                                    
[FILE] pattern.bin (size = 547)                                                 
/lfs1/boot_count read count:4 (bytes: 1)                                        
/lfs1/boot_count write new boot count 5: [wr:1]                                 
------ FILE: /lfs1/pattern.bin ------                                           
05 aa aa aa aa aa aa aa 06 aa aa aa aa aa aa aa                                 
...                             
                                                                
I: /lfs1 unmounted                                                              
/lfs1 unmount: 0

**Comment by FRASTM** [comment]
> > When the CONFIG_STM32_MEMMAP is set this version adds an Abort function to resume the MemoryMapped mode, so that erasing is possible and restore the MemoryMapped mode after completion Note that flash read and write are using memcpy.
> 
> Nice, if write works with memcpy that is OK. Is it not needed to disable irq's when memory mapped mode is aborted (would there be irq code that is not available during the erase) ?

Write is not really guarantee. in memorymapped mode : with stm32u585, the data written (with memcopy) and read back (in memcopy) are correct but do not seem persistent in flash !?

**Comment by Laczen** [comment]
@FRASTM, your commit comments are still showing that erase and write is not supported, is this still the case ? If erase works, can't you use the same methodology (go out of memmap, do erase, return to memmap) for the write ?

**Comment by de-nordic** [comment]
> stm32u585

https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf

RM0456 Rev 5 1061/3637
RM0456 Octo-SPI interface (OCTOSPI)
1095
28.4.11 OCTOSPI memory-mapped mode:

"It is not recommended to program the flash memory using the memory-mapped writes:
the indirect-write mode fulfills this operation."

Page 1064 explains more.

Reads/writes to OSPI connected, memory-mapped, device will be probably cached, so unless you invalidate cache and force OQSPI to re-read the area then you will not know whether data has been written correctly, as it seems that there is no auto-erase on writes are probably not verified.

**Comment by FRASTM** [comment]
> @FRASTM, your commit comments are still showing that erase and write is not supported, is this still the case ? If erase works, can't you use the same methodology (go out of memmap, do erase, return to memmap) for the write ?

Yes it works : erasing/writing the NOR octo-flash after aborting the mem map mode.

**Comment by FRASTM** [comment]
adding a commit to abort the memorymapped mode before erasing or writing to the external NOR octoflash

**Comment by FRASTM** [comment]
The PR #68597 is now replacing this PR

**Pull request closed without merging**
