### PR TITLE
tests: posix: common: do not overspecify pthread_attr_t

### LINKED ISSUE #67178: tests: posix: pthread_attr_destroy() not consistently called after pthread_attr_init()
**Describe the bug**

Pthread stacks should be managed by `pthread_attr_init()` and `pthread_attr_destroy()`.

Dynamic thread stacks (including pooled thread stacks) were not done in Zephyr this way due to... difficulties getting that accepted in the first place (it took years), but also due to the implementation of the POSIX API, testsuite, and so on.

The model is clear - either use a `NULL` `pthread_attr_t *` and the implementation will manage the stack for the caller, or call `pthread_attr_init()` **with a matching call** to `pthread_attr_destroy()`.

In many areas in the POSIX testsuite, calls to `pthread_attr_destroy()` were missing or an assertion would occur prior to `pthread_attr_destroy()` being called.

It would seem that the testsuite leaks memory and resources substantially due to this.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? All
 - What have you tried to diagnose or workaround this issue? #67094 #67085
 - Is this a regression? No.
 
**To Reproduce**
1. Pull in #67223 (it's actually too late now, because that PR pulls in much of the cleanup from #67575)
2. Execute tests where there is a call to `pthread_attr_init()` but no matching call to `pthread_attr_destroy()`, or tests that assert before calling `pthread_attr_destroy()`
3. See error

**Expected behavior**
There should be no memory leaks

**Impact**
It's a showstopper for #51211 which is why I'm in such a hurry to fix it 😁 

**Logs and console output**
Would see things like
```shell
E: Unable to allocate thread stack
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.4
 - Commit: c0bb064d4e

**Additional context**

This bug will likely be comprised of several partial fixes
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/67094
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/67575
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/67223

### PR DESCRIPTION
**Pull request by cfriedt**
Originally, Zephyr only supported statically defined thread stacks.

That is actually the exception in terms of how pthreads are typically spawned. The norm is simply passing a `NULL` `pthread_attr_t *` and using a stack allocated by the implementation.

For the vast majority of test cases involving typically trivial workloads, there is zero need to manually specify stack sizes, priorities, scheduling parameters, etc, unless actually testing that functionality, and therefore no reason to specify `pthread_attr_t`, since `NULL` will simply pull from the pool of preallocated thread stacks.

This highlights an aspect of the testsuite that needs to be fixed as part of #67091

Moreover, virtually everywhere we have used `pthread_attr_init()`, there is insufficient care taken to call `pthread_attr_destroy()` in the various failure cases. That complexity is mitigated by using automatic thread stacks, as the POSIX API manages the thread stack for us. The significance of this is quite obvious once those functions are modified to manage thread stacks (rather than funnelling it all into `pthread_create()`), because not calling `pthread_attr_destroy()` translates to memory leaks.

By passing in a `NULL` `pthread_attr_t *` to `pthread_create()` we can avoid retrofitting dozens of `pthread_attr_destroy()` instances throughout the testsuite while simultaneously making the tests more concise and easier to maintain.

Additionally, make tests more concise / accurate by switching to e.g. `zassert_ok()`, rather than `zassert_false()`, `zassert_not_null()` rather than `zassert_equal((int)x, (int)y)`, etc.

This PR fixes a difficult-to-enumerate number of bugs in the POSIX testsuite.

(Partially)
Fixes #67178

### CODE REVIEW

**Review by keith-packard — DISMISSED** [review]
Good cleanup in general, just one suggestion -- I'd leave the active code outside the zassert calls so that they just verify values and don't have the action include. e.g.
instead of
```
zassert_ok(pthread_setspecific(key, value), "pthread_setspecific failed");
```
use
```
ret = pthread_setspecific(key, value);
zassert_ok(ret, "pthread_setspecific failed");
```

**Comment by cfriedt** [comment]
> Good cleanup in general, just one suggestion -- I'd leave the active code outside the zassert calls so that they just verify values and don't have the action include.

I do see the usefulness in keeping temporary variables around but also feel it's a matter of personal preference / utility. Definitely agree if the value is read / written more than once in a test.

Worthwhile suggestion in any case.

**Comment by cfriedt** [comment]
+ rwlock

**Comment by keith-packard** [comment]
> > Good cleanup in general, just one suggestion -- I'd leave the active code outside the zassert calls so that they just verify values and don't have the action include.
> 
> I do see the usefulness in keeping temporary variables around but also feel it's a matter of personal preference / utility. Definitely agree if the value is read / written more than once in a test.

I was thinking more as a way to ensure the 'real' code was visible by separating it from the 'test framework' bits. Kinda like making sure that your 'assert' statements never have side-effects.

**Review by ycsin — APPROVED** [review]
LGTM

**Comment by cfriedt** [comment]
> I was thinking more as a way to ensure the 'real' code was visible by separating it from the 'test framework' bits. Kinda like making sure that your 'assert' statements never have side-effects.

It would be beneficial to do that if this were an `__ASSERT()` or `__ASSERT_NO_MSG()` or just plain old `assert()` in regular application code because one needs to be careful that the `assert()` could be a macro that is switched off (and therefore the internal call might not work), or that somehow the contents of the function call might interfere with the assert macro.

But this is an integration test intentionally written for the ZTest framework. So there is no need to be cautious that zasserts would evaluate to nothing. Functions also definitely do evaluate correctly from within zassert statements.

**Comment by cfriedt** [comment]
@keith-packard - could you please re-approve?

**Review by keith-packard — APPROVED** [review]

**Pull request merged**
