### PR TITLE
kernel: Fix double-list-removal corruption case in timeout handling

### LINKED ISSUE #8669: fault during my timer testing
hello
I found a fault during my timer testing.

zephyr version:    1.9.1
code:
```
_struct k_timer test_timer, test_timer2;
static void test_timeout_event(os_timer *timer)
{
}

static void test2_timeout_event(os_timer *timer)
{
    k_timer_start(&test_timer, K_MSEC(10), K_MSEC(20));
}

void test_timer(void)
{
    k_timer_init(&test_timer, test_timeout_event, NULL); 
    k_timer_init(&test_timer2, test2_timeout_event, NULL); 

    k_timer_start(&test_timer, K_MSEC(10), K_MSEC(20));  

    while(1) {
        k_timer_start(&test_timer2, K_MSEC(100), 0);  
        k_sleep(K_MSEC(1000));
    }
}
```

analysis:
when timer1 & timer2  expired in the same tick,   timer1 & timer2 will be dequeue  from _timeout_q to expired.
In timer2 callback function, k_timer_start(&test_timer, K_MSEC(10), K_MSEC(20)) will re-insert timer1 to _timeout_q.  After timer2 callback function, the expired sys_dlist(in _handle_expired_timeouts()) has changed. 
The callback of timer linked in the _timeout_q will be called in order. when run last timeout(_timeout_q which actually is not a timer structure)，run timeout->func will trigger a fault.

### PR DESCRIPTION
**Pull request by andyross**
This fixes #8669, and is distressingly subtle for a one-line patch:

The list iteration code in _handle_expired_timeouts() would remove the
timeout from our (temporary -- the dlist header is on the stack of our
calling function) list of expired timeouts before invoking the
handler.  But sys_dlist_remove() only fixes up the containing list
pointers, leaving garbage in the node.  If the action of that handler
is to re-add the timeout (which is very common!) then that will then
try to remove it AGAIN from the same list.

Even then, the common case is that the expired list contains only one
item, so the result is a perfectly valid empty list that affects
nothing.  But if you have more than one, you get a corrupt cycle in
the iteration list and things get weird.

As it happens, there's no value in trying to remove this timeout from
the temporary list at all.  Just iterate over it naturally.

Really, this design is fragile: we shouldn't be reusing the list nodes
in struct _timeout for this purpose and should figure out some other
mechanism.  But this fix should be good for now.

### CODE REVIEW

**Comment by nashif** [comment]
Hey @andyross, is this covered with tests or do we need to add one?

**Comment by andyross** [comment]
Added #9627 to track the need for refactoring here.

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by findlayfeng** [comment]
new bug

**Comment by nordic-krch** [comment]
@andyross @nashif when working on new shell #9362 we encountered an issue (hardfault) after rebase on master. I couldn't figure out the issue so i ended up rebasing back and finally found that https://github.com/zephyrproject-rtos/zephyr/pull/9620/commits/2376a770790c97fe89b6e87b8e0c8a53585d7b26 introduces this fault.

Example is fairly simple. It has two periodic instances of k_timer. When only one is running app is stable, enabling second periodic timer results in hardfault. Can you recommend something?

**Comment by carlescufi** [comment]
Could this actually be also the source of some faults we've been seing recently?

**Comment by nordic-krch** [comment]
in my case it was usually **hardfault** pointing to _sys_dlist_peek_prev_no_check_ or **mpu fault** (attempt to execute from ram address)

**Comment by jarz-nordic** [comment]
I've also observed this problem when I used: k_sleep(1); in my application. When I have replaced `k_sleep(1);` with `k_busy_wait(1000);` problem is gone.
My error msg is following:
capture

**Comment by carlescufi** [comment]
@jarz-nordic does reverting this commit also fix it for you if you use `k_sleep(1)`?

**Comment by jarz-nordic** [comment]
@carlescufi @nordic-krch @andyross : Once I've reveted this commit the problem is gone.

**Comment by carlescufi** [comment]
@andyross as the original author of this patch, could you take a look at the reports here?

**Pull request merged**
