### PR TITLE
drivers: pwm: remove extraneous whitespace

### PR DESCRIPTION
**Pull request by pabigot**
PR was merged before this was cleaned up.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by pabigot** [comment]
I agreed to provide this, so here it is, but I'm not convinced it's worth the time we're going to spend on it.

For the record I tested:
```
git ls-tree --name-only -r HEAD \
| sed -r -e '/\.(der|gif|png|jpeg|PNG|qpf|qsf|qsys|bin|jpg|pdf|vsdx|sof|v|svg)$/d' \
| xargs sed -i -r \
      -e cmd
```
for the following `cmd`:

* 's@( +)\t@\t@g': 63 files have a space before a tab
* 's@\s+$@@g': 4 files have trailing whitespace.  Two are probably non-Unix newlines, one is the pwm.h file, another is probably raw import from another project (comment lines that have a single ` * ` between paragraphs end in a space).
* '${/^$/d}': 169 files have trailing empty lines

**Review by galak — APPROVED** [review]

**Comment by andrewboie** [comment]
>  but I'm not convinced it's worth the time we're going to spend on it.

Then please stop wasting everyone's time with PRs like this?

**Comment by andrewboie** [comment]
meanwhile the doc build is failing in this header

```
 ---- New errors/warnings not tracked as .known-issues/, please fix them ----

/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'period' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'pulse' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'period' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'pulse' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'period' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'pulse' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'period' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'pulse' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'period' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'pulse' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'period' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
/home/apboie/projects/zephyr/zephyr/include/drivers/pwm.h:77: warning: argument 'pulse' from the argument list of pwm_pin_set_cycles has multiple @param documentation sections
```

**Comment by marc-hb** [comment]
A very simple, good rule of thumb with whitespace/indentation/etc.:
- get it right when that part of the code is changing anyway for some other reason
- otherwise don't add noise to the git history and don't break git blame, rebase, merge, cherry-pick etc.

That's exactly why tools like check_compliance.py, checkpatch etc. try to focus as much as possible on changes only and don't scan the entire code base (which is also much faster)

**Pull request merged**
