### PR TITLE
Cellular fixes

### PR DESCRIPTION
**Pull request by KimBP**
Looking a bit into the new cellular stuff I realized more of the samples can't build with the different boards.
So little is needed to make it work, so worth it I think

### CODE REVIEW

**Review by bjarki-andreasen — CHANGES_REQUESTED** [review]
Changes to devicetree compatibles, in this case redefining the compatible used in the cellular driver, which results in the driver not building at all for any board (more specifically not creating any struct devices when built), is a no from me :)

**Comment by rerickson1** [comment]
For `pinnacle_100_dvk` and `mg100` to work with the cellular modem sample, board overlays are needed in the sample.

**Comment by KimBP** [comment]
Yes - I guess you are right. My misunderstanding. 
This was purely based on my build result. Unfortunately my only modem is on a (yet) unsupported board, so haven't had a change to verify it.
I'll retract this PR

**Comment by KimBP** [comment]
> For `pinnacle_100_dvk` and `mg100` to work with the cellular modem sample, board overlays are needed in the sample.

That's one way to solve the lack of the modem alias. Still though you'll get a linker conflict with multiple definitions of  __devices_dts_ord_xx (defined in both modem_cellular.c.obj and the hl8700 driver)

**Comment by rerickson1** [comment]
> > For `pinnacle_100_dvk` and `mg100` to work with the cellular modem sample, board overlays are needed in the sample.
> 
> That's one way to solve the lack of the modem alias. Still though you'll get a linker conflict with multiple definitions of __devices_dts_ord_xx (defined in both modem_cellular.c.obj and the hl8700 driver)

You need a kconfig overlay to disable the HL7800 driver.

**Pull request closed without merging**
