### PR TITLE
mgmt: mcumgr: transport: shell: Add optional input expiration

### LINKED ISSUE #54411: mgmt: mcumgr: Shell transport can lock shell up until device is rebooted
**Describe the bug**
The shell mcumgr transport can lock the shell up until the device is rebooted if the data is corrupt or interrupted, this is because the shell will be locked waiting for the end of the mcumgr packet, which it never gets.

Instead, there should be a (configurable) timeout to allow dropping any pending data and returning the state back to normal.

**Expected behavior**
Shell to not lock up

**Impact**
Showstopper

### PR DESCRIPTION
**Pull request by nordicjm**
Adds an optional feature that can be used to time out a partially
    received MCUmgr packet over the shell interface. Prior to this
    change, if a header was received, then the whole shell would be
    unavailable until the module is rebooted or additional full MCUmgr
    packet was sent.

Fixes #54411

### CODE REVIEW

**Comment by nordicjm** [comment]
Could enable this by default?
Enabling features uses 104 bytes of flash and 64 bytes of RAM extra (nrf52840)

**Comment by de-nordic** [comment]
I am fine with having this on by default.
Regarding timing: the SMP requests come in frames that have some expected structure and MTU and waiting for next expected character (byte) of the frame should be rather based on the baud rate of the medium. Knowing how long it takes to send one character we have some expectancy in how long it will take to send entire frame, this means that we expect next characters to come at some specified pace.
IMHO we should set the timeout to characters over medium. For example we wait time equivalent to N characters before releasing shell and dropping frame. The question is: are we able to get current baud rate of the medium?

**Comment by nordicjm** [comment]
I set this as 3 seconds because that is long enough to not cause any issues at usable baud rates. The idea of this is just for recovery of the device, so the go application has a 10 second response timeout by default but can use retries if it does not get a response. The timeout to me is not so important, it's more preventing the shell from locking up where there might not be an easy way to restart the module (this was actually an issue with a specific zephyr user some years ago whereby the zephyr device was in a high place that users could not access and the shell locking up was a dire situation)

**Comment by de-nordic** [comment]
> I set this as 3 seconds because that is long enough to not cause any issues at usable baud rates. The idea of this is just for recovery of the device, so the go application has a 10 second response timeout by default but can use retries if it does not get a response. The timeout to me is not so important, it's more preventing the shell from locking up where there might not be an easy way to restart the module (this was actually an issue with a specific zephyr user some years ago whereby the zephyr device was in a high place that users could not access and the shell locking up was a dire situation)

Taking into account that this is frame based protocol, the timeout should be based on expected time frame gets transferred. This is not character based protocol, it is sub-band in character based communication, but it is frame based.
Even Zephyr app is pushing SMP frame via UART, from frame buffer that has been completed before first frame character is send.

IMHO timeout for sub-band, frame based communication should be based on time device is able to wait for next symbol of the frame.

**Review by de-nordic — DISMISSED** [review]
Provides fix for a problem, although I would rather have symbol time over medium based timeout (https://github.com/zephyrproject-rtos/zephyr/pull/55594#issuecomment-1474225496).

**Review by de-nordic — APPROVED** [review]
Looks OK (https://github.com/zephyrproject-rtos/zephyr/pull/55594#pullrequestreview-1346461943)

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
