### PR TITLE
openamp: Bump to v2022.04.0

### PR DESCRIPTION
**Pull request by carlocaione**
Bump OpenAMP to v2022.04.0 and fix Zephyr terminology linked to OpenAMP.

Note: there is still some terminology to fix in Zephyr but this PR is only fixing what's strictly related to OpenAMP.

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]

**Comment by arnopo** [comment]
Due to the suppression of potentially objectionable terms  some build warning should occurs

to avoid this 

VIRTIO_DEV_SLAVE should be replaced by VIRTIO_DEV_DEVICE in:
-samples/subsys/ipc/openamp_rsc_table/src/main_remote.c
- subsys/ipc/ipc_service/lib/ipc_static_vrings.c
- subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.h

VIRTIO_DEV_MASTER should be replaced by VIRTIO_DEV_DRIVER in:
- subsys/ipc/ipc_service/lib/ipc_static_vrings.c
- subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.h

RPMSG_MASTER sould be replaced by RPMSG_HOST in 
- subsys/ipc/ipc_service/lib/ipc_rpmsg.c
- subsys/ipc/rpmsg_service/rpmsg_backend.c
- samples/subsys/ipc/openamp/src/main.c
- samples/subsys/ipc/openamp_performance/src/main.c

CONFIG_OPENAMP_MASTER and CONFIG_OPENAMP_SLAVE cthat are Zephyr config are optional to update

**Comment by carlocaione** [comment]
@arnopo I should have already addressed your comments in this PR

**Comment by arnopo** [comment]
> @arnopo I should have already addressed your comments in this PR

Also a wrong review here?  I don't know wat i have reviewed but certainly not the good one.  Another time my apologizes

**Review by arnopo — DISMISSED** [review]
LGTM
Should the CONFIG_OPENAMP_MASTER and CONFIG_OPENAMP_SLAVE be updated also?

**Comment by carlocaione** [comment]
> Should the CONFIG_OPENAMP_MASTER and CONFIG_OPENAMP_SLAVE be updated also?

Yes, but that will break a lot of users so it must be done carefully with deprecation. I'll push another PR for that.

**Review by arnopo — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
