### PR TITLE
drivers: can: add missing can_set_mode() syscall handler + test case

### LINKED ISSUE #44361: drivers: can: missing syscall verifier for can_set_mode()
**Describe the bug**
The `can_set_mode()` API function is a system call, but it is missing a `z_vrfy_can_set_mode()` verification function.

**To Reproduce**
1. Enable `CONFIG_USERSPACE=y` and `CONFIG_CAN=y` 
2. Call `can_set_mode()` from a userspace thread
3. See error

```
*** Booting Zephyr OS build zephyr-v3.0.0-2032-g9a8d8e69494b  ***
Running test suite can_api_tests
===================================================================
START - test_set_loopback
E: Unimplemented system call
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0xe000ed00
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x20000120 (test_set_loopback)
E: Halting system
```

**Expected behavior**
The syscall should have a verification function.

**Impact**
Unable to call `can_set_mode()` from userspace.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS
 - Toolchain: Zephyr SDK v0.14.0
 - Commit SHA: 50cc558924d1a6cdaed2a0fc9efd9979aafa0417

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
- Add missing syscall verification handler for `can_set_mode()`.
- Run the test case for `can_set_mode()` in userspace to validate the syscall handler.

Fixes: #44361

### CODE REVIEW

**Review by alexanderwachter — DISMISSED** [review]

**Review by str4t0m — DISMISSED** [review]

**Review by str4t0m — DISMISSED** [review]

**Review by alexanderwachter — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]

**Comment by MaureenHelm** [comment]
Please rebase

**Comment by henrikbrixandersen** [comment]
> Please rebase

@MaureenHelm Done, thanks.

**Review by alexanderwachter — DISMISSED** [review]

**Review by str4t0m — DISMISSED** [review]

**Review by karstenkoenig — DISMISSED** [review]

**Comment by carlescufi** [comment]
@henrikbrixandersen please rebase

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen please rebase

Rebased after merge of 28d9278358e3bd63694fbd1dee733a8a439f6ff6.

**Review by martinjaeger — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
