### PR TITLE
docs: Fix documentation for mailbox k_mbox_msg.tx_block 

### PR DESCRIPTION
**Pull request by rodrigopex**
- Replace old tx_block.pool_id to tx_block.data;
- Fix code examples.

Signed-off-by: Rodrigo Peixoto rodrigopex@ayna.tech

### CODE REVIEW

**Comment by dbkinder** [comment]
recheck

**Comment by nashif** [comment]
please fix both issues:

1: UC2 Body does not contain a 'Signed-Off-By' line
1: UC3 Title does not follow [subsystem]: [subject]: "Fix mailbox k_mbox_msg.tx_block documentation"

**Review by nashif — CHANGES_REQUESTED** [review]
Fix remaining issues:

1: UC2 Body does not contain a 'Signed-Off-By' line
1: UC3 Title does not follow [subsystem]: [subject]: "Fix mailbox k_mbox_msg.tx_block documentation"

**Review by dbkinder — APPROVED** [review]
Doc change looks OK, but there are check errors that need fixing (as Anas noted).

**Comment by rodrigopex** [comment]
I'll fix this today.

**Comment by dbkinder** [comment]
Assuming you're using a git shell command to submit stuff, make sure your git setup has your username and email:

    git config --global user.name "David Developer"
    git config --global user.email "david.developer@company.com" 

Amend your current commit with:

    git commit -s --amend

Update the title to be "docs: Fix mailbox k_mbox_msg.tx_block documentation", and verify your signed-off-by line is now there.  Save your commit changes and do a forced push from your branch (looks like you did this change on your master branch instead of a new working branch) so:

    git push -f origin master

That should update the PR properly with your amended commit.  You might read through http://docs.zephyrproject.org/contribute/contribute_guidelines.html too.

**Comment by rodrigopex** [comment]
Thank you very much. I'll do this right now.

**Comment by rodrigopex** [comment]
Done.

**Comment by dbkinder** [comment]
Sigh.  Looks like your signed-off-by name and email needs to match your GitHub account name and email: author email (Rodrigo Peixoto <rodrigopex@gmail.com>) needs to match one of the signed-off-by entries.  You used a different email rodrigopex@ayna.tech

**Comment by rodrigopex** [comment]
This is a secondary email from my github account. Is this an issue? I am
using this at the company.

**Comment by rodrigopex** [comment]
I have added this to the github. It was not there yet.

**Comment by dbkinder** [comment]
recheck

**Comment by dbkinder** [comment]
Still failing because the signed-off-by email isn't your primary GitHub email (I think).  GitHub says your primary/author email is (rodrigopex@gmail.com) and it "needs to match one of the signed-off-by entries" in the commit message (rodrigopex@ayna.tech).

 https://help.github.com/articles/using-a-verified-email-address-in-your-gpg-key/

**Comment by rodrigopex** [comment]
Sorry about that. Now my primary email is rodrigopex@ayna.tech.

**Comment by dbkinder** [comment]
recheck

**Comment by nashif** [comment]
```
Author:     Rodrigo Peixoto <rodrigopex@gmail.com>
AuthorDate: Sun Apr 22 18:22:09 2018 -0300
Commit:     Rodrigo Peixoto <rodrigopex@ayna.tech>
CommitDate: Wed Apr 25 10:53:05 2018 -0300

    docs: Fix mailbox k_mbox_msg.tx_block documentation

    - Replace old tx_block.pool_id to tx_block.data;
    - Fix code examples.

    Signed-off-by: Rodrigo Peixoto <rodrigopex@ayna.tech>
```

author does not match signed-off-by.

This needs to be fixed.

**Comment by nashif** [comment]
and this has nothing to do with github email, it is your local git configuration.

**Comment by nashif** [comment]
obsoleted with #8387

**Pull request closed without merging**
