### PR TITLE
Fix undefined reference to `__log_current_const_data_get' when using LOG_MODULE_DECLARE

### LINKED ISSUE #10026: undefined reference to `__log_current_const_data_get' when using LOG_MODULE_DECLARE
With this change: https://github.com/nashif/zephyr/commit/e94e0c987be5032bb6b76e32e6b45a4bcc43b702

I get
```
kernel/libkernel.a(userspace.c.obj): In function `_impl_k_object_alloc':
/home/nashif/Work/github/zephyr/kernel/userspace.c:228: undefined reference to `__log_current_const_data_get'
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by nordic-krch**
Fixing compilation failure when LOG_MODULE_DECLARE() is used. Added test to cover usage of that macro.

One thing to note. With current scheme (LOG_MODULE_DECLARE/LOG_MODULE_REGISTER taking module name) it is forbidden to use LOG_MODULE_DECLARE() in headers thus logging in static inline function in header is impossible. That is because both macros creates static inline function with the same name: __log_current_dynamic_data_get().

Fixes #10026

### CODE REVIEW

**Comment by nordic-krch** [comment]
fyi: @mbolivar @galak

**Review by carlescufi — APPROVED** [review]
Looks fine to me

**Review by pizi-nordic — APPROVED** [review]

**Review by mbolivar — APPROVED** [review]
Seems fine, tested locally, confirmed test_module.c compiles

**Comment by carlescufi** [comment]
@nordic-krch seems some tests are running out of RAM with the patch, can you take a look and blacklist/whitelist/modify as required?

**Comment by nordic-krch** [comment]
@carlescufi its not ram size issue, it looks more like a compiler issue (https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/22615/5/console): 

> Unable to reach log_dynamic_test (at 0x004001f0) from the global pointer (at 0x00408628) because the offset (-33848) is out of the allowed range, -32678 to 32767.

There is plenty of ram but it seems like offset is limited to 32k. I've added altera_max10 and qemu_nios2 to platform_exlude list. Unless somebody knows how to fix it.

**Comment by nashif** [comment]
@nordic-krch 

> @carlescufi its not ram size issue, it looks more like a compiler issue

Can you open a bug about this so we do not lose track of it?

**Pull request merged**
