### PR TITLE
net: sockets: socketpair: Fix poll signalling

### LINKED ISSUE #36447: net: socket: socketpair: Poll call resetting all events
**Describe the bug**
At the beginning of poll() call every events on all file descriptors are systematically cleared, here :
socketpair.c: zsock_poll_prepare_ctx(): k_poll_signal_reset((*pev)->obj);

**To Reproduce**
- scenario 1 (on file descriptor addition to poll):
	Create two threads (one will be called client and one server), one socketpair with one end belonging to server
	and the other end to client. On server side make a call to poll() with this fd immediatelly. On client side try to write immediately.
	Start Client thread long before server thread. Poll() on server side will never exit.
- scenario 2 (in preemptive case only):
	While handling events after a poll() the server performs a read/write operation, the write call reschedule the client. Then the client
	will immediatelly send a request to the server and wait its response with a poll(). The poll() reschedules the server that will begin a new poll loop,
	thus resetting all the events including our new client request.

**Expected behavior**
Beginning a poll() should not reset all the incoming events and
events shall be reset only when they are treated.
- scenario 1 :
	We expect poll() to not reset all the events after addition of a file descriptor to fd set in order for the server to treat client request.
- scenario 2 :
	We expect the poll() not to reset the events that would occur in the middle of two server poll() calls.

**Impact**
Loss of events on file descriptor while using poll() call on socketpair and application deadlocks when both 
client and server use poll() to synchronise communication.

**Environment (please complete the following information):**
 - OS: WSL2 on Windows
 - Toolchain Zephyr SDK : 11.4

**Additional context**
fix proposition:
 - Suppress reset signal write in prepare stage of poll function
 - Put reset signal at the end of a application read on socket
[0001-patch-kernel-socketpair.c.zip](https://github.com/zephyrproject-rtos/zephyr/files/6692431/0001-patch-kernel-socketpair.c.zip)

### PR DESCRIPTION
**Pull request by rlubos**
In case read or write were called before the actual poll() call, the poll() function was not signalled correctly about such events, which in order could lead to a deadlock if the poll() was called with infinite timeout.

Additionally, add unit tests that cover this scenario, to make sure poll() events are signalled correctly.

Fixes #36447

### CODE REVIEW

**Comment by rlubos** [comment]
BTW, when I read the code, I found the signal names a bit confusing. I do understand where do the names come from, however, names like `write_signal` -> `readable` and `read_signal` -> `writeable` would be more descriptive in my opinion.

Then, if we write to a socket, the `remote->readable` is raised instead of `remote->write_signal`, and respectively, when there no more room for data to write, `remote->writeable` is reset, instead of `remote->read_signal`. Up for discussion whether to change.

**Comment by cfriedt** [comment]
> Then, if we write to a socket, the `remote->readable` is raised instead of `remote->write_signal`, and respectively, when there no more room for data to write, `remote->writeable` is reset, instead of `remote->read_signal`. Up for discussion whether to change.

I'm ok with that change too if it increases clarity

**Review by cfriedt — APPROVED** [review]
LGTM

**Comment by rlubos** [comment]
@cfriedt Thanks, I've added a commit that renames the signals, please have a look. From my perspective (a guy who analyzed this code for the first time) it's easier to follow what's going on now.

**Comment by cfriedt** [comment]
@rlubos - just one minor comment to fixup a comment. Other than that, looks great. Thank you for fixing the bug and also thanks for adding to the test suite 🙂

**Review by mniestroj — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by romaric35** [comment]
@rlubos thank you for taking into account this issue so fast and more thoroughly than expected from our side. It is good to see such a living community.

**Pull request merged**
