### PR TITLE
net: events: change management event codes

### PR DESCRIPTION
**Pull request by mbolivar**
As discussed in https://github.com/zephyrproject-rtos/zephyr/issues/6413.

Renumber each layer's command codes to try to avoid false positives. See commit log for summary.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Having one event / bit can be problematic in long run as we can easily run out of bits for each event. If we start to combine the bits like what you actually did for 15.4 commands, then that can lead to hard to track errors if developer accidentally sets same set of bits for two commands.
I think we should keep the command list simple (==sequential) even though it can lead some more work in the receiving side.

**Comment by mbolivar** [comment]
> then that can lead to hard to track errors if developer accidentally sets same set of bits for two commands.

I don't see how that could happen easily. The enum is declared in a single statement.

If you are NAKing this patch please say so and I'll drop it. But I think it offers concrete benefits in the form of reduced memory pressure on the event queue.

**Comment by jukkar** [comment]
> If you are NAKing this patch please say so and I'll drop it. But I think it offers concrete benefits in the form of reduced memory pressure on the event queue.

I think we are still in discussion phase :) I am just pondering this aloud what issues we might have with this.
One problem I tried to explain is that if someone looks the events in the header file and sees clear use of bits, then there is an expectation that every event matches one bit. Even if we explain this clearly in the documentation that this is not the case, someone will get this wrong anyway. If the event numbers are just plain enums, it is quite obvious that each event number needs to be handled in certain way.

**Review by tbursztyka — CHANGES_REQUESTED** [review]
I understand your point but it's not a nice way to solve know core logic limit to user APIs. It's a burden to maintain and it will eventually be nullified by interfaces having much more than 16 events. Plus the gain is very limited actually as all events do not happen to be raised at same rate. 

Also, you mixed up things: commands are never pushed as events, there is dedicated enums for events. You modified the wrong ones.

For instance, 15.4 has only 1 event, not more than 16.
bt as well, etc...

**Comment by mbolivar** [comment]
> Even if we explain this clearly in the documentation that this is not the case, someone will get this wrong anyway.

This, I think, is a problem either way.

Since sample code has already been accepted into Zephyr (which has been corrected as a result of this issue) that treated masks as if false positives were impossible, I think the API is already confusing and subject to people getting things wrong.



> I understand your point but it's not a nice way to solve know core logic limit to user APIs. It's a burden to maintain and it will eventually be nullified by interfaces having much more than 16 events. Plus the gain is very limited actually as all events do not happen to be raised at same rate.
> 
> Also, you mixed up things: commands are never pushed as events, there is dedicated enums for events. You modified the wrong ones.
> 
> For instance, 15.4 has only 1 event, not more than 16.
> bt as well, etc...

Hm, sorry, I am sure you are right but I don't understand what you mean. Aren't these the values which are used as command codes to eventually OR into the events?

**Comment by tbursztyka** [comment]
>Hm, sorry, I am sure you are right but I don't understand what you mean. Aren't these the values which are used as command codes to eventually OR into the events?

No. You mixed up request cmd code, and event cmd code.

**Comment by jukkar** [comment]
I think this can be closed, re-open if needed.

**Pull request closed without merging**
