### PR TITLE
tests: Enable the pca9555 chip on mec172xevb_assy6906

### PR DESCRIPTION
**Pull request by hunterhu3000**
Enable the pca9555 chip on mec172xevb to test the I2C function
1. Add tests/boards/mec172xevb_assy6906/i2c_api
2. The HW connections are described in README.txt
3. Use I2C01 to connect the PCA9555, as I2C00 is for UART2

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

### CODE REVIEW

**Comment by hunterhu3000** [comment]
As there is no I2C test case for mec172xevb_assy6906, it is helpful to use the on board pca9555 to test the I2C and add it into the daily test.

**Comment by enjiamai** [comment]
Hi @hunterhu3000 , would you like to move this test to new ztest API also?

**Comment by hunterhu3000** [comment]
> Hi @hunterhu3000 , would you like to move this test to new ztest API also?

Done

**Review by enjiamai — APPROVED** [review]
LGTM.

**Comment by hunterhu3000** [comment]
This PR is a request from openEC team. They want to add an I2C test in the daily test on mec172xevb_assy6906 and track the quality of the driver.
@MaureenHelm @albertofloyd Could you please help to review and +1? Thanks

**Review by albertofloyd — APPROVED** [review]

**Pull request merged**
