### PR TITLE
drivers/dma/loop_transfer: Move from tests to samples and small regex fix

### LINKED ISSUE #31226: tests/drivers/dma/loop_transfer does not use ztest
**Describe the bug**
`tests/drivers/dma/loop_transfer` is implemented as a sample.
It does not use ztest harness and does not provide a verdict

**Expected behavior**
Either it should be reworked to provide a verdict uing ztest, either it should be moved to `samples/drivers`

### PR DESCRIPTION
**Pull request by erwango**
Move drivers/dma/loop_transfer from tests to samples as it is actually implemented as a sample.
Additionally small fix in regex harness is done.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/31226

### CODE REVIEW

**Review by FRASTM — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
This should be converted to a test because it behaves as such. This does not pass the threshold of a sample IMO.

**Comment by erwango** [comment]
> This does not pass the threshold of a sample IMO.

I'm curious, what is the threshold of a sample ?

**Comment by erwango** [comment]
@nashif Can you elaborate on "This does not pass the threshold of a sample IMO."?
Looking at `tests/drivers/dma`, `chan_blen_transfer` is testing the exact same thing. 
If we convert this one to test we'd end up having 2 redundant tests.

**Comment by nashif** [comment]
> @nashif Can you elaborate on "This does not pass the threshold of a sample IMO."?
> Looking at `tests/drivers/dma`, `chan_blen_transfer` is testing the exact same thing.
> If we convert this one to test we'd end up having 2 redundant tests.

then we probably should remove it or merge them into one test.

**Review by galak — APPROVED** [review]

**Comment by hakehuang** [comment]
> > @nashif Can you elaborate on "This does not pass the threshold of a sample IMO."?
> > Looking at `tests/drivers/dma`, `chan_blen_transfer` is testing the exact same thing.
> > If we convert this one to test we'd end up having 2 redundant tests.
> 
> then we probably should remove it or merge them into one test.

the two cases test different functionalities:
1. the loop_transfer is a basic check with simple settings on fixed channel.
2. the chan_blen_transfer is a channal test with different settings. 
the problem of this two cases are they do no tuse ztest to wrapper, and the m2m is not a good demo, because no one will use dma to memory to memory copy, it is just a function test on dma engine. So I support @nashif that we apply ztest to wrapper thoes wto cases.  As to whether to merge the two cases in one, I think it is not necessary. IMHO, a simple case may easier for us to maintain and understand.

**Comment by erwango** [comment]
> 2\. As to whether to merge the two cases in one, I think it is not necessary. I

Thanks for the lightning on the sample.

Regarding the test, I don't think we should maintain a more simple version of the test. We maintain the test to verify things are working as expected. If checks in the simple reversion are redundant, I don't see a value to maintain it, it could be removed.

**Comment by hakehuang** [comment]
> > 2. As to whether to merge the two cases in one, I think it is not necessary. I
> 
> Thanks for the lightning on the sample.
> 
> Regarding the test, I don't think we should maintain a more simple version of the test. We maintain the test to verify things are working as expected. If checks in the simple reversion are redundant, I don't see a value to maintain it, it could be removed.

However, it is not a usual practice to remove a working case, duplicating check does not hurt.

**Comment by erwango** [comment]
> there is one test point which is not coverred in chan_blen test, which is to write to different dst address for several times,

@hakehuang I had missed this, txs. I'll move the sample to a test and submit again.

**Comment by erwango** [comment]
Closing and pushing a new PR.

**Pull request closed without merging**
