### PR TITLE
tests: fix text output in timing_info test

### PR DESCRIPTION
**Pull request by maksimmasalski**
After reviewing that test I found output looks too messy.
1. Remove words starting from capital letter in the middle of the
sentence.

Signed-off-by: Maksim Masalski <maksim.masalski@intel.com>

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
This breaks the recording feature in testcase.yaml, this is probably what you should  need anyways if you are trying to parse the output. All results are stored in recording.csv

**Comment by maksimmasalski** [comment]
> This breaks the recording feature in testcase.yaml, this is probably what you should need anyways if you are trying to parse the output. All results are stored in recording.csv

What exactly breaks the recording feature, change of the zero-padding? If yes, we can keep that zero-padding as exists, just maybe change text.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
you need to rebase

**Comment by maksimmasalski** [comment]
> you need to rebase

Done.

**Comment by maksimmasalski** [comment]
@nashif Anas, I'm thinking, maybe it will be a good idea to add test ID to each test when generating csv table. That way it will be easier to maintain tests, if they will be uploaded to the database, and their names will be updated in the future.

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
