### PR TITLE
logging: Add log backend lock

### PR DESCRIPTION
**Pull request by teburd**
When SMP is in use the log backend should not be re-entered concurrently as it results in log output being mangled.

Imagine two cores with log immediate mode enabled where the log message is concurrently being processed by the backend.

Mangled output is highly likely as each backend is almost certainly a single byte stream being written to (uart, shared memory, dma channel, etc).

Found while diagnosing some mangled output with the hda log backend.

### CODE REVIEW

**Comment by teburd** [comment]
Feels like the ideal scenario on SMP would be either separate backend instances per core so they can internally deal with this
*or*
Some sort of mpsc queue setup with messages put in the queue, and a try lock around the processing loop over it.

**Comment by dcpleung** [comment]
I don't think this is needed for deferred mode as log is processed in a thread. Maybe #ifdef for immediate mode only?

**Comment by teburd** [comment]
> I don't think this is needed for deferred mode as log is processed in a thread. Maybe #ifdef for immediate mode only?

In deferred mode panic mode induces the same behavior

**Comment by teburd** [comment]
RFC and DNM because its unclear this is the right spot to do this, at the moment the backends themselves are sort of responsible for dealing with the issue as can be seen in mtrace, adsp, and hda

**Pull request closed without merging**
