### PR TITLE
tests: add min_ram to test applications

### PR DESCRIPTION
**Pull request by hakehuang**
add min_ram to some test applications

TWR_KE18F and FRDM_KL25Z

Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
Would be good to explain which platform it is that is running out of space with these tests.

**Comment by hakehuang** [comment]
> Would be good to explain which platform it is that is running out of space with these tests.

on FRDM_KL25Z and TWR_KE18F

**Comment by andyross** [comment]
I meant include the note in the commit message :)

**Comment by hakehuang** [comment]
> I meant include the note in the commit message :)

sorry, my bad. Updated the commit message

**Review by MaureenHelm — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@hakehuang Please rebase.

**Comment by cfriedt** [comment]
@hakehuang - is this ready to be merged when conflicts are resolved?

**Comment by hakehuang** [comment]
> @hakehuang - is this ready to be merged when conflicts are resolved?

yes. Thanks.

**Review by dcpleung — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
