### PR TITLE
[Backport v2.7-branch] spi: nrfx_spi*: only run uninit if configured

### PR DESCRIPTION
**Pull request by JordanYates**
Manual copy of #42348 that contains the fix from #42579

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/42299

### CODE REVIEW

**Comment by cfriedt** [comment]
@JordanYates - is there an existing issue for the backport?

**Comment by JordanYates** [comment]
> @JordanYates - is there an existing issue for the backport?

The original issue was #42299

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by cfriedt** [comment]
LGTM - @tbursztyka - can you ack as SPI maintainer?

**Comment by cfriedt** [comment]
@tbursztyka - please ack

**Pull request merged**
