### PR TITLE
kconfig: Remove assignments to promptless SOC_FAMILY_NRF symbol

### PR DESCRIPTION
**Pull request by ulfalizer**
SOC_FAMILY_NRF has no prompt. Assignments in configuration files have no
effect on symbols without prompts. A prompt means the symbol is
user-configurable.

SOC_FAMILY_NRF is instead enabled indirectly through being selected by
other symbols.

Detected through some work-in-progress improved error checking.

### CODE REVIEW

**Comment by ulfalizer** [comment]
The reason this wasn't detected is that the symbol still ended up as `y` as intended. Improved version will detect it anyway.

**Review by ioannisg — APPROVED** [review]

**Review by SebastianBoe — APPROVED** [review]
Nice

**Comment by ulfalizer** [comment]
Times out.

**Comment by ulfalizer** [comment]
@nashif @carlescufi 
Note that this one is a timeout, if that's the reason it wasn't merged along with https://github.com/zephyrproject-rtos/zephyr/pull/20718, https://github.com/zephyrproject-rtos/zephyr/pull/20719, and https://github.com/zephyrproject-rtos/zephyr/pull/20720.

Rebased now, will probably time out again.

**Review by nashif — APPROVED** [review]

**Comment by ulfalizer** [comment]
Still timing out. It's safe to merge.

**Comment by ulfalizer** [comment]
@carlescufi @nashif 
Ping

It's just timing out.

**Pull request merged**
