### PR TITLE
Tfm update for nrf5340dk

### PR DESCRIPTION
**Pull request by ioannisg**
Bump TFM version to 1.2.0 RC2.
This brings support for nRF5340 DK.

TF-M module pull request: https://github.com/zephyrproject-rtos/trusted-firmware-m/pull/28

Tested build on all platforms

Tested the integration samples on
- nrf5340 PDK
- nrf534 DK
- nRF9160
- mps2
- nucleo l552ze_q

### CODE REVIEW

**Comment by ioannisg** [comment]
Sanity Check failure:


```
CMake Error at CMakeLists.txt:8 (cmake_minimum_required):
--
  | CMake 3.15 or higher is required.  You are running version 3.13.1

```

@carlescufi @galak we need a CMake update for TF-M v1.2

**Review by microbuilder — APPROVED** [review]
Tested successfully on `lpcxpresso55s69_ns` with default settings via `west build -p -b lpcxpresso55s69_ns zephyr/samples/tfm_integration/psa_level_1/ --`:

```
=== [SAU NS] =======
NS ROM Base: 0x00040000
NS ROM Limit: 0x0007FFFF
NS DATA Base: 0x20022000
NS DATA Limit: 0x20043FFF
NSC Base: 0x1003FCC0
NSC Limit: 0x1003FD20
PERIPHERALS Base: 0x40000000
PERIPHERALS Limit: 0x4010FFFF
=== [AHB MPC NS] =======
NS ROM Base: 0x00040000
NS ROM Limit: 0x0007FFFF
NS DATA Base: 0x20022000
NS DATA Limit: 0x20043FFF
[Sec Thread] Secure image initializing!
Booting TFM v1.1
[Crypto] MBEDTLS_TEST_NULL_ENTROPY is not suitable for production!
*** Booting Zephyr OS build zephyr-v2.4.0-1437-gb9752f96d850  ***
[00:00:00.000,000] <inf> app: app_cfg: Creating new config file with UID 0x1055cfda7a
[00:00:00.825,000] <inf> app: att: System IAT size is: 362 bytes.
[00:00:00.825,000] <inf> app: att: Requesting IAT with 64 byte challenge.
[00:00:01.207,000] <inf> app: att: IAT data received: 362 bytes.
...
```

**Comment by microbuilder** [comment]
Also test on QEMU with `$ west build -p -b mps2_an521_nonsecure zephyr/samples/tfm_integration/psa_level_1/ -t run`

**Comment by ioannisg** [comment]
Thanks @microbuilder for the testing

**Comment by galak** [comment]
> @carlescufi @galak we need a CMake update for TF-M v1.2

Do we know if there's a reason TFM needs this version of cmake?

**Comment by carlescufi** [comment]
> > @carlescufi @galak we need a CMake update for TF-M v1.2
> 
> Do we know if there's a reason TFM needs this version of cmake?

@tejlmand I think we discussed this recently, do you recall?

**Comment by tejlmand** [comment]
> > > @carlescufi @galak we need a CMake update for TF-M v1.2
> > 
> > 
> > Do we know if there's a reason TFM needs this version of cmake?
> 
> @tejlmand I think we discussed this recently, do you recall?

I don't recall that we knew why they changed, only that they did change.
But looking at this commit:
https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/commit/?id=698173275839bbe1f724e3f8c580578fdf3371d3

I see that they now do:
```
set(CMAKE_PROJECT_INCLUDE_BEFORE ${CMAKE_SOURCE_DIR}/cmake/disable_compiler_detection.cmake)
```
`CMAKE_PROJECT_INCLUDE_BEFORE` is new CMake variable introduced with 3.15.

**Comment by ioannisg** [comment]
> > @carlescufi @galak we need a CMake update for TF-M v1.2
> 
> Do we know if there's a reason TFM needs this version of cmake?

@galak, not really. I remember I posted a comment in the TFM Review: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/6604, and I do not recall getting an explicit response from Raef (but maybe @microbuilder knows).

**Comment by microbuilder** [comment]
> @galak, not really. I remember I posted a comment in the TFM Review: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/6604, and I do not recall getting an explicit response from Raef (but maybe @microbuilder knows).

That comment was the main reason I was aware of. We needed the `CMAKE_PROJECT_INCLUDE_BEFORE` option to properly manage the build order, and to have the flexibility to change the toolchain settings early enough.

**Review by tejlmand — APPROVED** [review]

**Comment by tejlmand** [comment]
@ioannisg could you please post a Zephyr wide bump to CMake 3.15, and update the docs.
Similar to this PR: https://github.com/zephyrproject-rtos/zephyr/pull/12022

**Comment by ioannisg** [comment]
> @ioannisg could you please post a Zephyr wide bump to CMake 3.15, and update the docs.
> Similar to this PR: #12022

@tejlmand yeap, will do.

**Comment by ioannisg** [comment]
@galak  this is now passing nicely with the CMake updates.

**Comment by galak** [comment]
Marked it DNM for west.yml.

**Review by anangl — APPROVED** [review]

**Review by agansari — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Pull request merged**
