### PR TITLE
boards: intel/adsp/ace30_ptl: CONFIG_MAX_THREAD_BYTES to 3

### PR DESCRIPTION
**Pull request by dcpleung**
Set CONFIG_MAX_THREAD_BYTES to 3 for board `intel_adsp/ace30_ptl` as overlay in some tests as this is required for some kernel tests to build.

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
FWIW: doing this at the board level bumps the size of the kobj header by a full word (2 is as many bytes as it has room for by default) for all apps, including production SOF firmware which seems **really** unlikely to go past the 16 thread limit.  It's annoying to do this at the test level, but tests tend to use a lot of threads where actual audio firmware doesn't.

**Comment by marc-hb** [comment]
I was just wondering about the "range" of this `_defconfig` file and @andyross pre-empted my question...

While SOF could/should? configure this itself, it does not look like it does now. So this is effectively a "sneaky" change for application whether it's the Right Thing or not. And it's not like people pay a lot of attention to Kconfig in general; ahem: #73733

At the very least the commit message should be "louder"; right now it sounds like a pure test change.

**Comment by dcpleung** [comment]
Hm... that's true. Let me move all this into the tests board overlay.

**Comment by dcpleung** [comment]
Done. Moved the kconfig into board overlay for those tests.

**Review by andyross — APPROVED** [review]

**Review by softwarecki — APPROVED** [review]

**Pull request merged**
