### PR TITLE
kconfig: Rebase to latest Kconfiglib

### PR DESCRIPTION
**Pull request by carlescufi**
A lot of improvements have made it into Kconfiglib since we introduced
it into Zephyr. This rebases our 2 Zephyr-specific commits into the
latest Kconfiglib upstream.

Origin: https://github.com/carlescufi/Kconfiglib/tree/zephyr

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
CC @ulfalizer

**Comment by carlescufi** [comment]
Note: I have not done the whole process of having 3 commits (original import and then our patches) because I keep those in my tree, and I feel it's unnecessary since I do provide the tree URL in the commit message.

**Comment by carlescufi** [comment]
Also note that with this update we get a few more Kconfig warnings, which is something I personally find useful, there are some fixes that should be done in some of the Kconfig files.

**Comment by carlescufi** [comment]
Updated to use our new official "fork" here: https://github.com/zephyrproject-rtos/Kconfiglib/tree/zephyr

**Review by galak — APPROVED** [review]

**Pull request merged**
