### PR TITLE
picolibc: Enable use of toolchain 'release' build

### PR DESCRIPTION
**Pull request by keith-packard**
Picolibc can be built so that it installs both a minsize and release version. For toolchains which support that, the release version can be selected using --picolibc-buildtype=release. Enable the picolibc build type to be selected when compiling a Zephyr application by exposing the existing Kconfig values and setting the --picolibc-buildtype depending on their value.

Toolchains supporting this mode must set the TOOLCHAIN_HAS_PICOLIBC_DUAL value alongside their existing TOOLCHAIN_HAS_PICOLIBC value.

This can be tested using the existing Debian arm-none-eabi toolchain:

    $ export TOOLCHAIN_HAS_PICOLIBC=y
    $ export CROSS_COMPILE=/usr/bin/arm-none-eabi-
    $ export ZEPHYR_TOOLCHAIN_SUPPORTS_THREAD_LOCAL_STORAGE=y
    $ west build -b qemu_cortex_m3 samples/hello_world -- \
	-DTOOLCHAIN_HAS_PICOLIBC=y \
	-DTOOLCHAIN_HAS_PICOLIBC_DUAL=y \
	-DCONFIG_PICOLIBC_USE_MODULE=n

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]
LGTM

**Comment by keith-packard** [comment]
I'm exploring another option here -- building the toolchain with -Os multilib configurations. That's requiring some gcc hacks, but the results would be completely transparent to the user -- build and link with -Os and you get size-optimized libraries for everything from the toolchain.

**Comment by cfriedt** [comment]
There will always be those who need to squeeze every drop of performance / speed out of every cycle and those who need to use as few .text bytes as possible to get some functionality.

Sometimes, it's possible to have both.

Probably `-Os` would work for the average Zephyr user. For those who need extra performance, building as a module with `-03` or something could work.

Your plan sounds good to me.

**Comment by keith-packard** [comment]
Patches for gcc have been submitted upstream; a test toolchain build with patches for gcc and crosstool-ng has been posted. We'll see how viable this approach is, but it sure looks cleaner than the --picolibc-buildtype=release hack.

**Pull request closed without merging**
