### PR TITLE
drivers: spi: stm32: optimize use of fifo

### PR DESCRIPTION
**Pull request by mgritz**
Optimize usage of some STM32 SPI peripheral's builtin 4-octet-FIFOs. Only takes effect if the SPI interface is compatible="st,stm32-spi-fifo" and not operated in CONFIG_STM32_SPI_INTERRUPT or _DMA mode.

Instead of sending and receiving single frames as the SPI master ensure the FIFOs are filled up and as many frames as possible within one go.

This allows for a slight speedup in situations where the SPI clock runs close to the CPU clock rate. In this case the spi context advancement takes longer than the actual byte transaction and can be done in parallel to the SPI peripheral working from/to the FIFOs.

Transaction before, on an STM32F303, one clock (yellow) "block" is one frame (whole transaction is 7 frames here, with a context switch after the first 3):

and after this change:

### CODE REVIEW

**Comment by erwango** [comment]
Thanks for this PR. Please note there is a PR under review, on a good way to be merged soon, on similar topic: https://github.com/zephyrproject-rtos/zephyr/pull/63173. It would be nice that you have a check on this first.
^^@dgastonochoa

**Review by dgastonochoa — CHANGES_REQUESTED** [review]
Would it be possible to see the test plan? Have you run the SPI loopback tests?

**Comment by erwango** [comment]
Is this PR still valid now that https://github.com/zephyrproject-rtos/zephyr/issues/66326 was merged ?

**Comment by mgritz** [comment]
> Is this PR still valid now that #66326 was merged ?

Naw, #63173 and #66326 supersede this.

**Pull request closed without merging**
