### PR TITLE
soc: nordic: nrf54h: handle SPU DMASEC setting for CCM030

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Comment by gmarull** [comment]
This is an alternative to https://github.com/nrfconnect/sdk-zephyr/pull/1582 (it looks it's all we need, in the end). However, I'm still not convinced this is the right approach, specially after seeing:

https://github.com/zephyrproject-rtos/hal_nordic/blob/13ac55b5b52c905642e9c54f069109d188aa5840/drivers/nrf_802154/driver/src/nrf_802154_aes_ccm_acc_ccm.c#L213-L217

To me, this setting should be handled by whoever manages CCM. Let's discuss the approach.

**Comment by carlescufi** [comment]
> This is an alternative to [nrfconnect/sdk-zephyr#1582](https://github.com/nrfconnect/sdk-zephyr/pull/1582) (it looks it's all we need, in the end). However, I'm still not convinced this is the right approach, specially after seeing:
> 
> https://github.com/zephyrproject-rtos/hal_nordic/blob/13ac55b5b52c905642e9c54f069109d188aa5840/drivers/nrf_802154/driver/src/nrf_802154_aes_ccm_acc_ccm.c#L213-L217
> 
> To me, this setting should be handled by whoever manages CCM. Let's discuss the approach.

@hubertmis could you please weigh in?

**Comment by hubertmis** [comment]
> @hubertmis could you please weigh in?

I understand we discuss the best way to manage the SPU peripheral in Zephyr.

I see we have the following options:

1. Fully-fledged SPU driver with API available to all potential users (https://github.com/nrfconnect/sdk-zephyr/pull/1582)
2. Simplified SPU configuration during system initialization presented in this PR
3. SPU configuration for peripheral X done by device driver X

To show which one is preferable I would like to discuss SPU usage scenarios:

1. TrustZone enabled: SPU is used by TF-M to prevent access from NS application (Zephyr) to selected peripherals
2. TrustZone disabled: SPU is used by Zephyr to enable access to everything it needs

The device driver shall not be aware if they run in scenario 1 or 2. So it rules out solution 3.

The SPU configuration in scenario 1 is going to be complicated, so the TF-M implementation should contain the fully-fledged SPU to easily configure this peripheral. But it applies to TF-M, not to Zephyr.

The SPU configuration in scenario 1 is simple (perhaps fully contained in this PR), so the solution from this PR should be enough.

Because of this, I recommend following this PR, porting https://github.com/nrfconnect/sdk-zephyr/pull/1582 to TF-M, and removing things like https://github.com/zephyrproject-rtos/hal_nordic/blob/13ac55b5b52c905642e9c54f069109d188aa5840/drivers/nrf_802154/driver/src/nrf_802154_aes_ccm_acc_ccm.c#L213-L217 from other device drivers.

**Comment by gmarull** [comment]
> > @hubertmis could you please weigh in?
> 
> I understand we discuss the best way to manage the SPU peripheral in Zephyr.
> 
> I see we have the following options:
> 
> 1. Fully-fledged SPU driver with API available to all potential users ([[nrf noup] DNM: drivers: misc: add temporary SPU driver nrfconnect/sdk-zephyr#1582](https://github.com/nrfconnect/sdk-zephyr/pull/1582))
> 2. Simplified SPU configuration during system initialization presented in this PR
> 3. SPU configuration for peripheral X done by device driver X
> 
> To show which one is preferable I would like to discuss SPU usage scenarios:
> 
> 1. TrustZone enabled: SPU is used by TF-M to prevent access from NS application (Zephyr) to selected peripherals
> 2. TrustZone disabled: SPU is used by Zephyr to enable access to everything it needs
> 
> The device driver shall not be aware if they run in scenario 1 or 2. So it rules out solution 3.
> 
> The SPU configuration in scenario 1 is going to be complicated and application-specific, so the TF-M implementation should contain the fully-fledged SPU to easily configure this peripheral. But it applies to TF-M, not to Zephyr.
> 
> The SPU configuration in scenario 1 is simple (perhaps fully contained in this PR), so the solution from this PR should be enough.
> 
> Because of this, I recommend following this PR, porting [nrfconnect/sdk-zephyr#1582](https://github.com/nrfconnect/sdk-zephyr/pull/1582) to TF-M, and removing things like https://github.com/zephyrproject-rtos/hal_nordic/blob/13ac55b5b52c905642e9c54f069109d188aa5840/drivers/nrf_802154/driver/src/nrf_802154_aes_ccm_acc_ccm.c#L213-L217 from other device drivers.

So, from what I understand, Zephyr only needs to deal with scenario (2), TrustZone disabled. In such case, who should be responsible for configuring the SPU? Should it be the driver as in the 802154 case? The SPU API can be discussed in more detail I guess, my main concern is who should be the client of such API. soc.c doesn't seem like a clean approach.

**Comment by hubertmis** [comment]
> So, from what I understand, Zephyr only needs to deal with scenario (2)

That's correct. In scenario (1) Zephyr has no access to SPU registers.

> who should be responsible for configuring the SPU?

I don't think the device drivers should worry about the security settings of the SoC. The device drivers should start with the assumption they can use the peripherals they need. Something else in the system should configure SPU before the drivers are initialized.

soc.c is one solution that in my opinion is fine.

Another option would be to create a minimal SPU driver with initialization priority pre-other-drivers that just configures CCM DMA properties (I understand all other security configurations are good enough as reset values).

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
