### PR TITLE
tests/kernel/sleep: relax upper bound to support additional delays

### LINKED ISSUE #17965: kernel/sleep/ test failed on reel_board.
**Describe the bug**
Running test suite sleep on reel_board,  it failed with error message "elapsed_ms <= UPPER_BOUND_MS is failed, overslept".

**To Reproduce**
1. west build -b reel_board -p=auto tests/kernel/sleep/
2. west flash

**Screenshots or console output**
image

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-SDK-0.10.1
 - Commit ID: 14db558939db

### PR DESCRIPTION
**Pull request by pabigot**
Nordic platforms measure ticks in cycles of a 32 KiHz clock for which
the minimum compare delay is 2 ticks.  The test assumed an upper bound
of four ticks delay per loop iteration, resulting from alignment at
various layers.  This delay is met on Nordic for tick rates at or below
16384, but is too short for the default 32768 Hz tick rate.

Instrumentation confirms that the usleep test loop body on Nordic at 32
KiHz ticks takes 153 ms which is 5 ticks, and that the requested 1 tick
timeout delay is being increased to 2 ticks to meet the requirements of
the underlying hardware compare.

Relax the upper bound by one tick for platforms using this system timer
at the highest rate.

Closes #17965.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
I don't see any harm of this, but would like @pizi-nordic and @andyross to have a look

**Review by pizi-nordic — APPROVED** [review]

**Comment by ioannisg** [comment]
@andyross ping :)

**Comment by pabigot** [comment]
Please also see https://github.com/zephyrproject-rtos/zephyr/issues/17965#issuecomment-522777680 for an adjustment that's probably necessary.  There will definitely be a need for follow-on investigation to determine whether underneath this is a hardware problem, an unavoidable interaction with jlink hardware, or failure to properly initialize the system to mitigate against the effects of jlink hardware.

**Comment by pabigot** [comment]
Revised per earlier comment to account for code path that sets timeout three times.  @jfischer-phytec-iot could you please verify this works on the reel board variants?

**Review by jfischer-no — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
