### PR TITLE
tests: fs: fat_fs_api: add support for testing SDMMC devices

### PR DESCRIPTION
**Pull request by danieldegrasse**
Add support for testing SDMMC devices to the fatfs API test. This also requires wiping the beginning of the disk at the start of the test, in order to make sure a filesystem partition is not present on the SD card from a previous run of the test

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@sylvioalves sorry for the ping here, I don't fully understand the twister error here: 
```
Generating files from /__w/zephyr/zephyr/twister-out/m5stack_core2_esp32_procpu/tests/subsys/fs/fat_fs_api/filesystem.fat.api.sdmmc/zephyr/zephyr.elf for board: m5stack_core2
esptool.py v4.7.0
Creating esp32 image...
ROM segments hidden - only RAM segments are visible to the ROM loader!
Merged 17 ELF sections
Traceback (most recent call last):
  File "/__w/zephyr/modules/hal/espressif/tools/esptool_py/esptool.py", line 37, in <module>
    esptool._main()
  File "/__w/zephyr/modules/hal/espressif/tools/esptool_py/esptool/__init__.py", line 1166, in _main
    main()
  File "/__w/zephyr/modules/hal/espressif/tools/esptool_py/esptool/__init__.py", line 979, in main
    operation_func(args)
  File "/__w/zephyr/modules/hal/espressif/tools/esptool_py/esptool/cmds.py", line 1037, in elf2image
    image.save(args.output)
  File "/__w/zephyr/modules/hal/espressif/tools/esptool_py/esptool/bin_image.py", line 781, in save
    assert (f.tell() + 8 + self.ROM_LOADER.BOOTLOADER_FLASH_OFFSET) % (
AssertionError
ninja: build stopped: subcommand failed.
```

I can't reproduce this locally with `west build -p -b m5stack_core2/esp32/procpu tests/subsys/fs/fat_fs_api -T filesystem.fat.api.sdmmc -DCONF_FILE=prj_sdmmc.conf`, but I can reproduce it with twister: `west twister -p m5stack_core2/esp32/procpu -s tests/subsys/fs/fat_fs_api/filesystem.fat.api.sdmmc`. Looking at the outputs, the image sizes seem different, but it isn't clear why:

Working example with `west build`:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      196580 B   16776960 B      1.17%
     iram0_0_seg:       50432 B       224 KB     21.99%
     dram0_0_seg:       36560 B       192 KB     18.60%
  dram0_shm0_seg:          0 GB         2 KB      0.00%
  dram0_sem0_seg:          0 GB          8 B      0.00%
     dram0_1_seg:          0 GB         0 GB
     irom0_0_seg:       65508 B     16380 KB      0.39%
     drom0_0_seg:         64 KB     16380 KB      0.39%
    rtc_iram_seg:          0 GB         8 KB      0.00%
    rtc_slow_seg:          0 GB         4 KB      0.00%
        IDT_LIST:          0 GB         8 KB      0.00%
```
Broken example with twister:
```
            FLASH:      196596 B   16776960 B      1.17%
     iram0_0_seg:       50432 B       224 KB     21.99%
     dram0_0_seg:       36560 B       192 KB     18.60%
  dram0_shm0_seg:          0 GB         2 KB      0.00%
  dram0_sem0_seg:          0 GB          8 B      0.00%
     dram0_1_seg:          0 GB         0 GB
     irom0_0_seg:       65524 B     16380 KB      0.39%
     drom0_0_seg:         64 KB     16380 KB      0.39%
    rtc_iram_seg:          0 GB         8 KB      0.00%
    rtc_slow_seg:          0 GB         4 KB      0.00%
        IDT_LIST:          0 GB         8 KB      0.00%
```

Any idea why the twister image would be a different size?

**Comment by sylvioalves** [comment]
@danieldegrasse, the issue is already known in our side and we have a fix already for it. However, `west build` and `twister` output having different values is something new. I will check it. Let me rebuild this locally with the fix we created. Ping you back soon.

**Comment by danieldegrasse** [comment]
> @danieldegrasse, the issue is already known in our side and we have a fix already for it. However, west build and twister output having different values is something new. I will check it. Let me rebuild this locally with the fix we created. Ping you back soon.

@sylvioalves any news here?

**Comment by sylvioalves** [comment]
> > @danieldegrasse, the issue is already known in our side and we have a fix already for it. However, west build and twister output having different values is something new. I will check it. Let me rebuild this locally with the fix we created. Ping you back soon.
> 
> @sylvioalves any news here?

@danieldegrasse, sorry for taking that long. Will submit a fix tomorrow.

**Comment by sylvioalves** [comment]
@danieldegrasse would you rebase this?

**Review by sylvioalves — APPROVED** [review]

**Comment by sylvioalves** [comment]
@danieldegrasse do you need this to be merged within v3.7.0?

**Comment by danieldegrasse** [comment]
> @danieldegrasse do you need this to be merged within v3.7.0?

Not particularly, no. The additional test coverage would be a nice to have though

**Comment by danieldegrasse** [comment]
@de-nordic ping, could you take a look at this change?

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
