### PR TITLE
tests: improve test filtering for CI

### PR DESCRIPTION
**Pull request by nashif**
- tests: do not filter on SMP, use board yaml file
- tests: improve filtering and use integration_platforms

### CODE REVIEW

**Comment by evgeniy-paltsev** [comment]
> tests: do not filter on SMP, use board yaml file

I'm OK with this change (for ARC), but I'm wondering about the rationale - if this is just a cleanup or we try to fix some issues with current implementation?

**Comment by nashif** [comment]
> I'm OK with this change (for ARC), but I'm wondering about the rationale - if this is just a cleanup or we try to fix some issues with current implementation?

this is about optimizing the amount of stuff we have to build to be able to run a test, filters are very expensive and require us to spend most of the time figuring out if a test needs to be run, so doing static filters helps a lot and reduces the build time and cost of CI.

**Review by dcpleung — DISMISSED** [review]

**Review by evgeniy-paltsev — CHANGES_REQUESTED** [review]
In case of ARC platforms the `supported: smp` section is missing in the

boards/arc/hsdk/hsdk.yaml
boards/arc/hsdk4xd/hsdk4xd.yaml

**Comment by evgeniy-paltsev** [comment]
> this is about optimizing the amount of stuff we have to build to be able to run a test, filters are very expensive and require us to spend most of the time figuring out if a test needs to be run, so doing static filters helps a lot and reduces the build time and cost of CI.

Ok, didn't thought about CI time optimization, thanks for explanation!

Though, in case of SMP we also often filter out the platforms which supports SMP (as thest is UP only). So probably we need to introduce the negative version of `depends_on` later.

**Review by jhedberg — APPROVED** [review]

**Review by evgeniy-paltsev — APPROVED** [review]

**Pull request merged**
