### PR TITLE
west: hostap: update hostap revision

### PR DESCRIPTION
**Pull request by fengming-ye**
Update hostap revision to PR.

### CODE REVIEW

**Review by krish2718 — DISMISSED** [review]

**Comment by krish2718** [comment]
Can you please update the manifest, as the PR is merged.

**Comment by fengming-ye** [comment]
> Can you please update the manifest, as the PR is merged.

updated to latest bug fix commit

**Comment by aescolar** [comment]
Discussed during release meeting that this is a too big change to make it to 3.7
CC @dleach02

**Comment by krish2718** [comment]
> Discussed during release meeting that this is a too big change to make it to 3.7 CC @dleach02

The current manifest is too old and looking at the list of commits, its mostly bug fixes, except for few DPP related additions (but they are purely guarded by DPP which won't be available in this release), so, IMHO, we should go ahead with this PR for 3.7.0.

**Review by rlubos — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by aescolar** [comment]
> so, IMHO, we should go ahead with this PR for 3.7.0.

Merged following your request and @jukkar recommendation.

In any case, please note the commit msg for manifest updates to modules should include a motivation of why the update is done. Getting a short list of the updates/changes in the module brought by the update is also very welcome.
https://docs.zephyrproject.org/latest/develop/modules.html#synchronizing-with-upstream
*When synchronizing a module with upstream it is mandatory to document the rationale for performing the particular update*

**Pull request merged**
