### PR TITLE
Bluetooth: Controller: Fix CIS accept fails with unsupp parameters

### LINKED ISSUE #60132: LE Audio: Controller: Failed to establish a second CIS with Packetcraft controller
**Describe the bug**
The PTS tests with 2 CIS fails because the second CIS could not be established. Looking for an explanation I tested samples/bluetooth/unicast_audio_client app with samples/bluetooth/unicast_audio_server app on nrf5340dk boards, with 2 bidirectional CISes configuration, switching between Zephyr and Packetcraft controller.

There is no problem with second CIS when Zephyr controller is on both sides of a connection. But in Zephyr <-> Packetcraft connection the second CIS always fails to be established. Is there a known solution for this issue?

**Btmon logs**
[unicast_client_zephyr.log](https://github.com/zephyrproject-rtos/zephyr/files/11977129/unicast_client_zephyr.log)
[unicast_server_packetcraft.log](https://github.com/zephyrproject-rtos/zephyr/files/11977130/unicast_server_packetcraft.log)

**To Reproduce**
**Unicast Client: Zephyr Host + Zephyr Controller:**
In samples/bluetooth/hci_rpmsg, build the netcore binary:

`west build -b nrf5340dk_nrf5340_cpunet -- -DOVERLAY_CONFIG=nrf5340_cpunet_iso-bt_ll_sw_split.conf`

Flash the controller with:
`west flash --recover`

In samples/bluetooth/unicast_audio_client build the appcore binary:
[unicast_client.config.txt](https://github.com/zephyrproject-rtos/zephyr/files/11979294/unicast_client.config.txt)
`west build -b nrf5340dk_nrf5340_cpuapp . -- -DOVERLAY_CONFIG=unicast_client.config.txt`

Flash the app with:
`west flash`

**Unicast Server: Zephyr Host + Packetcraft Controller:**
Download the controller binary:
https://github.com/nrfconnect/sdk-nrf/blob/v2.4.99-dev2/lib/bin/bt_ll_acs_nrf53/bin/ble5-ctr-rpmsg_3393.hex

and flash with:
`nrfjprog --program *.hex --chiperase --coprocessor CP_NETWORK -r`

In samples/bluetooth/unicast_audio_server build the appcore binary:
[unicast_server.config.txt](https://github.com/zephyrproject-rtos/zephyr/files/11979303/unicast_server.config.txt)
`west build -b nrf5340dk_nrf5340_cpuapp . -- -DOVERLAY_CONFIG=unicast_server.config.txt`

Flash the app with:
`west flash`

### PR DESCRIPTION
**Pull request by cvinayak**
Fix CIS accepted by Host being failed in the Controller with
reason 0x20 Unsupported LL Parameter Value, but relaxing the
check that the ACL connection is sufficiently placed such
that the time reservation using in the Controller
implementation does not overlap with the CIG event.

Fixes #60132.

### CODE REVIEW

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1914697651 after 14:29:39.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1915373760 after 20:04:52.

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1915462929 after 21:02:53.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/USR/SCC/BV-135-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1918390663 after 06:05:59.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>BAP     BAP/USR/SCC/BV-135-C            PASS</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/USR/SCC/BV-135-C BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1923683113 after 13:14:42.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>
<details><summary>Successful tests</summary>BAP     BAP/USR/SCC/BV-135-C            PASS</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BASS/SR/CP/BV-04-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1923908118 after 15:05:41.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>BASS    BASS/SR/CP/BV-04-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BASS/SR/CP/BV-04-C BASS/SR/CP/BV-05-C BASS/SR/CP/BV-06-C BASS/SR/CP/BV-07-C BASS/SR/CP/BV-12-C BASS/SR/CP/BV-13-C BASS/SR/CP/BV-14-C BASS/SR/CP/BV-15-C BASS/SR/CP/BV-17-C BASS/SR/CP/BV-18-C BASS/SR/CP/BV-19-C BASS/SR/CP/BV-20-C BASS/SR/SPE/BI-05-C BASS/SR/SPE/BI-06-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1924258184 after 17:52:17.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BASS    BASS/SR/CP/BV-13-C              FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-15-C              BTP ERROR - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-19-C              FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-20-C              FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/SPE/BI-06-C             FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications</details>
<details><summary>Successful tests</summary>BASS    BASS/SR/CP/BV-04-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-05-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-06-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications and https://bluetooth.atlassian.net/browse/ES-24765<br>BASS    BASS/SR/CP/BV-07-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-12-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-14-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-17-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/CP/BV-18-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications<br>BASS    BASS/SR/SPE/BI-05-C             PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/64449 Missing notifications</details>

**Comment by cvinayak** [comment]
> AutoPTS Bot results:
> Failed tests
> BASS BASS/SR/CP/BV-13-C FAIL - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-15-C BTP ERROR - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-19-C FAIL - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-20-C FAIL - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/SPE/BI-06-C FAIL - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> Successful tests
> BASS BASS/SR/CP/BV-04-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-05-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-06-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications and https://bluetooth.atlassian.net/browse/ES-24765
> BASS BASS/SR/CP/BV-07-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-12-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-14-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-17-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/CP/BV-18-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications
> BASS BASS/SR/SPE/BI-05-C PASS - ERRATA https://github.com/[/issues/64449](https://github.com/zephyrproject-rtos/zephyr/issues/64449) Missing notifications

@mkasenberg could check if the above failures still related to #64449 which I believe is fixed upstream.

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1935576943 after 10:18:33.

**Comment by mkasenberg** [comment]
> @mkasenberg could check if the above failures still related to #64449 which I believe is fixed upstream.

No, the issue with missing notifications is fixed indeed. The failures are related to something in app or host layer.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1935576943 after 10:53:56.

**Comment by cvinayak** [comment]
> AutoPTS Bot failed: Build and flash step failed

Thank you for your quick responses.... do you know what happened here?

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Build and flash step failed

**Comment by mkasenberg** [comment]
> > AutoPTS Bot failed: Build and flash step failed
> 
> Thank you for your quick responses.... do you know what happened here?

Some PTS dongle issues, let me restart the tester PC

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1935576943 after 11:11:23.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1936047352 after 15:38:45.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C BAP/UCL/STR/BV-526-C BAP/UCL/STR/BV-527-C BAP/UCL/STR/BV-528-C BAP/UCL/STR/BV-529-C BAP/UCL/STR/BV-531-C BAP/UCL/STR/BV-532-C BAP/UCL/STR/BV-533-C BAP/USR/STR/BV-362-C BAP/USR/STR/BV-365-C BAP/USR/STR/BV-366-C BAP/USR/STR/BV-377-C BAP/USR/STR/BV-380-C BAP/USR/STR/BV-383-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1936157555 after 16:47:06.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/UCL/STR/BV-526-C            PTS TIMEOUT - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/UCL/STR/BV-527-C            PTS TIMEOUT - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/UCL/STR/BV-528-C            PTS TIMEOUT - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/UCL/STR/BV-531-C            PTS TIMEOUT - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/UCL/STR/BV-532-C            FATAL ERROR - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/USR/STR/BV-362-C            INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/USR/STR/BV-365-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/USR/STR/BV-366-C            INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/USR/STR/BV-377-C            INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/USR/STR/BV-380-C            PTS TIMEOUT - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/USR/STR/BV-383-C            INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>
<details><summary>Successful tests</summary>BAP     BAP/UCL/STR/BV-529-C            PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established<br>BAP     BAP/UCL/STR/BV-533-C            PASS (3) - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1938601156 after 13:38:31.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/UCL/STR/BV-525-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/68227#issuecomment-1938839112 after 15:59:52.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/UCL/STR/BV-525-C            FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/60132 2th CIS not established</details>

**Comment by cvinayak** [comment]
Closing see: https://github.com/zephyrproject-rtos/zephyr/issues/60132#issuecomment-1999158416

**Pull request closed without merging**
