### PR TITLE
Stm32 g0 improvements

### PR DESCRIPTION
**Pull request by kiram9**
Add device tree nodes and peripheral support for STM32G0. 
Add alt mode gpio mux support definitions for STM32G0 71xx and 81xx and 41xx and 31xx series for pinmux helper. 
    Signed-off-by: Kieran Levin <ktl@frame.work>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for this contribution!

Before proceeding with the detailed review, could you please:
- split your changes into topic commits (one commit per logical subsystems (adc, dma, spi, pinmux, ..))
- indicate which tests have been run? which platform used ?

Thanks!

**Comment by kiram9** [comment]
I will look at splitting this out.

**Comment by erwango** [comment]
Please rebase, following merge of #23285

**Comment by kiram9** [comment]
I started breaking this out to: 
https://github.com/zephyrproject-rtos/zephyr/pull/23657 
https://github.com/zephyrproject-rtos/zephyr/pull/23659

**Pull request closed without merging**
