### PR TITLE
poll: Enable multiple threads to use k_poll in the same object

### PR DESCRIPTION
**Pull request by Vudentz**

### CODE REVIEW

**Comment by pfalcon** [comment]
Well, that's how bloat rises - first k_poll() was optional, now there's talk to depend on it, then instead of one poller per object there's need to put same obj into multiple pollers, and then later you can't fit your kernel in 800K or something, and someone tells we need another OS to cover that usecase ;-).

Jokes off, I really think that with such developments, we should keep k_poll an optional feature, and try to code core functionality without relying on it (thus maybe extending existing functionality where needed). My 2 cents of course.

**Comment by Vudentz** [comment]
Note that _wait_q which is present in all objects supporting waiters does work exactly like I implemented here, so in theory, we can replace the _wait_q with poll_events without adding a single byte to them.

Considering both net and bluetooth depend on k_poll I have a hard time seeing it as optional, except if the board doesn't do any networking but I wouldn't call those IoT devices, yet we can consider leaving the k_poll optional and reuse the _wait_q area like was done in k_queue, though that needs different configuration to test which is something we would like to avoid.

Also please remember that k_poll was introduced to reduce the number of threads/stacks, and that is a lot more than this would be adding, which is sys_dnode_t to each event, so it still a very good trade.

**Comment by pfalcon** [comment]
Compelling reasons, +1 from me, taken as a part of the overall evolution (e.g. possible further refactors to wait_q). Don't feel knowledgeable enough to actually approve though ;-).

**Review by rsalveti — APPROVED** [review]
LGTM, and fixes the issue I originally reported (ZEP-2553).

**Review by nashif — APPROVED** [review]

**Comment by pfalcon** [comment]
For ref, ZEP-2553 is now https://github.com/zephyrproject-rtos/zephyr/issues/3983

**Pull request merged**
