### PR TITLE
driver: uart: ns16550: convert to DT_INST_*

### PR DESCRIPTION
**Pull request by fabled**
Change to code to use the automatically generated DT_INST_*
defines and remove the now unneeded fixups.

Signed-off-by: Timo Teräs <timo.teras@iki.fi>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Review by scottwcpg — APPROVED** [review]

**Comment by fabled** [comment]
Please review now. I am also looking into implementing hardware flow control for ns16550 where the automatic hardware flow control on chip level is not supported (manually controlling RTS/CTS wires in software - is there perhaps any other driver already doing this that could be used as reference?). Thanks!

**Comment by fabled** [comment]
```
starting test - test_k_sleep
 thread sleeping for 50 milliseconds
 thread back from sleep
FAIL - thread_sleep@707. timestamp out of range, got 53

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/context/src/main.c:775: test_k_sleep: (rv not equal to 0)
 *** thread timed out waiting for thread on k_sleep().
FAIL - test_k_sleep
```
Is this some known intermittent test suite failure? I don't think I changed anything that could result this...

**Comment by carlescufi** [comment]
> Is this some known intermittent test suite failure? I don't think I changed anything that could result this...

Yes, this is not related to your patch. If you need CI to be rerun and don't want to rebase, just post a comment.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by jhedberg** [comment]
@fabled a conflict seems to have crept up with `soc/x86/apollo_lake/dts_fixup.h`, so you'll need to rebase

**Comment by fabled** [comment]
> @fabled a conflict seems to have crept up with `soc/x86/apollo_lake/dts_fixup.h`, so you'll need to rebase

Rebased. Thanks.

**Review by jenmwms — APPROVED** [review]

**Pull request merged**
