### PR TITLE
include: migrate includes to <zephyr/...>

### PR DESCRIPTION
**Pull request by gmarull**
In order to bring consistency in-tree, migrate all includes within
include directory to the new prefix <zephyr/...>. Note that the
conversion has been scripted, refer to zephyrproject-rtos#45388 for more
details.

### CODE REVIEW

**Review by de-nordic — DISMISSED** [review]
include/zephyr/fs/* looks OK.

**Review by ycsin — DISMISSED** [review]

**Comment by Thalley** [comment]
In the future, will PRs that do not use `<zephyr/...>` fail in CI? In other words, is this a change that will be enforced automatically?

**Review by carlocaione — DISMISSED** [review]

**Comment by gmarull** [comment]
> In the future, will PRs that do not use `<zephyr/...>` fail in CI? In other words, is this a change that will be enforced automatically?

I think they should. I think it's just about forcing `CONFIG_LEGACY_INCLUDE_PATH=n` on CI. Let's discuss this once in-tree is migrated (and oot modules as well, like mcuboot).

**Review by stephanosio — DISMISSED** [review]

**Review by stephanosio — APPROVED** [review]

**Comment by jhedberg** [comment]
>> In the future, will PRs that do not use `<zephyr/...>` fail in CI? In other words, is this a change that will be enforced automatically?

> I think they should. I think it's just about forcing `CONFIG_LEGACY_INCLUDE_PATH=n` on CI. Let's discuss this once in-tree is migrated (and oot modules as well, like mcuboot).

I'm not so sure that will work, since there will meanwhile likely be new PRs getting merged that use legacy paths -you'll always be playing a catch-up game. What would be needed is a CI check that fails PRs if they add *new* include statements using legacy paths.

**Review by dcpleung — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
