### PR TITLE
samples: echo_client: Set correct own and peer's addresses

### PR DESCRIPTION
**Pull request by ozhuraki**
The echo_server is at 192.0.2.2, 2001:db8::2.

So, the own addresses should be, correspondingly 192.0.2.1, 2001:db8::1.

The qemu_x86 overlay samples/net/sockets/echo_client/boards/qemu_x86.conf
is an extra source of confusion here (it just duplicates the wrong
configuration, making it obscure and difficult to find the problem),
removed.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/14654

Signed-off-by: Oleg Zhurakivskyy <oleg.zhurakivskyy@intel.com>

### CODE REVIEW

**Comment by rlubos** [comment]
I have a mixed feeliings here. This indeed make qemu vs Linux work out of the box, but breaks qemu vs qemu or board vs board communication, which is IMO a more common use case. We could update `echo_server/prj.conf` as well, but that would contradict to what @jukkar wrote [here](https://github.com/zephyrproject-rtos/zephyr/issues/14654#issuecomment-474314805). Can't we simply stress it out in the documentation that address swap is needed? Or provide a separate overlay config for qemu <> Linux?

**Comment by pfalcon** [comment]
For me this patch also looks confusing, or possibly a result of confusion. There're comments in those config files that they're configured for qemu <-> qemu connection, and linux <-> qemu case needs patching.

> The echo_server is at 192.0.2.2, 2001:db8::2.

Which echo_server exactly? samples/net/sockets/echo_server is at 192.0.2.1, 2001:db8::1, which are the default addresses for Zephyr samples.

> We could update echo_server/prj.conf as well, but that would contradict to what @jukkar wrote here.

And I would be strongly -1 on that. I always use server-type apps on Zephyr side for testing, while client on Linux, and would prefer that config to work out of the box.

I have to admit I almost never use echo_client for testing, as it's much less comfortable and requires much more handwork. So, I wouldn't be a strong stakeholder of what default setup is for echo_client (qemu<->qemu vs linux<->qemu), but I'd let the original author decide, and if @rlubos says it's qemu<->qemu, and that's what we have now, I'd avoid just switching it around and confusing people. Of course, unless there're strong and convincing arguments for switchover.

**Comment by ozhuraki** [comment]
@rlubos @pfalcon @tedd-an 

This might make sense, and I am not against your arguments.

However, what the bug report is about, is described as the most common usage scenario, as per documentation:

```
One of the most common usage scenario
is to run echo-client application inside QEMU.
```

Anyway, the documentation probably beats commit’s comments.

So, please be more concrete with the usage scenarios, document/send patches.

If this brakes anything for you, let’s fix it.

**Review by jukkar — CHANGES_REQUESTED** [review]
Lets not do it like this. It really depends on different persons how they feel like testing with echo-server / client.
As I wrote in #14654 lets try to keep things like we have it now so

qemu<->qemu
server is in 192.0.2.1 or 2001:db8::1
client is in 192.0.2.2 or 2001:db8::2

zephyr<->linux (qemu or native_posix)
zephyr is in 192.0.2.1 or 2001:db8::1
linux is in 192.0.2.2 or 2001:db8::2

Perhaps the patch could be against documentation where this could be explained.

**Comment by ozhuraki** [comment]
@jukkar @rlubos @pfalcon

OK. I will take another look.

What actually makes sense here is to clearly document both cases first.

If qemu to qemu is more common, let’s document it, keep the configuration intact and provide an overlay/document BKM for a less common case.

**Comment by pfalcon** [comment]
I believe this issue was fixed in alternative way by https://github.com/zephyrproject-rtos/zephyr/pull/14690 . Please let me close this, as otherwise it's hard to keep track of what PRs are active and which aren't, in these hot last weeks before 1.14. If there's a mistake or misunderstanding, please reopen.

**Pull request closed without merging**
