### PR TITLE
doc: doxygen: upgrade to 1.12.0

### PR DESCRIPTION
**Pull request by gmarull**
Use latest version

### CODE REVIEW

**Comment by kartben** [comment]
@gmarull 1.12.0 has now been released :)

**Review by nashif — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by kartben** [comment]
@gmarull something's wrong with https://docs.zephyrproject.org/latest/doxygen/html/modules.html - could you please have a look, I am off today/tomorrow

**Comment by gmarull** [comment]
> @gmarull something's wrong with https://docs.zephyrproject.org/latest/doxygen/html/modules.html - could you please have a look, I am off today/tomorrow

Apparently they're now called "topics" https://docs.zephyrproject.org/latest/doxygen/html/topics.html

**Comment by kartben** [comment]
> > @gmarull something's wrong with https://docs.zephyrproject.org/latest/doxygen/html/modules.html - could you please have a look, I am off today/tomorrow
> 
> Apparently they're now called "topics" https://docs.zephyrproject.org/latest/doxygen/html/topics.html

Ah, nevermind, I think the Zephyr Doxygen homepage was serving a cached version when I checked, so it still had the Modules link. You must have wondered why I bothered telling you something was "wrong" :)
All good then, and I actually like it that they moved away from "Modules"

**Pull request merged**
