### PR TITLE
doc: add support for kconfig role and directive

### LINKED ISSUE #36570: Use a custom role for Kconfig configuration options
**Is your enhancement proposal related to a problem? Please describe.**
We are misusing :option: to mark and reference Kconfig options. This role is for command line options and not for configuration options. If you look at https://docs.zephyrproject.org/latest/genindex-C.html you will see that it is being indexed as command line options in a very user unfriendly way.

**Describe the solution you'd like**
If there is no role that would give us what we need, create a custom role :config: and use that instead.

We can also skip the indexing, because the configuration options index is created by us anyways, no need to have any of those options listed in the main index generated by sphinx.

**Describe alternatives you've considered**

Use pre-existing role, but I could not find anything suitable.

### PR DESCRIPTION
**Pull request by gmarull**
Add a new extension to support the `:kconfig:` role and `.. kconfig::` directive. This removes the need of using `:option:`. A new `@kconfig{}` alias has also been added for Doxygen docstrings.

Fixes #36570

### CODE REVIEW

**Comment by nashif** [comment]
You need to change this as well:

```
ALIASES += option{1}="\verbatim embed:rst:inline :option:`\1` \endverbatim"

```
in doc/zephyr.doxyfile.in

**Review by mbolivar-nordic — APPROVED** [review]
Looks good, but is there a deprecation plan for `@option{}`?

**Review by nashif — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by gmarull** [comment]
> Looks good, but is there a deprecation plan for `@option{}`?

@nashif ?

**Comment by nashif** [comment]
> Looks good, but is there a deprecation plan for `@option{}`?

Maybe add a comment next to the alias and declare it deprecated and that it will be removed after next release. Do not think it is worth it to go through the effort of erroring out on this similar to what we do with macros and APIs

**Comment by gmarull** [comment]
> > Looks good, but is there a deprecation plan for `@option{}`?
> 
> Maybe add a comment next to the alias and declare it deprecated and that it will be removed after next release. Do not think it is worth it to go through the effort of erroring out on this similar to what we do with macros and APIs

done

**Comment by nashif** [comment]
> done

and to make it known, add this to the doc section of the release notes :)

**Pull request merged**
