### PR TITLE
devicetree: remove DT_HAS_NODE_STATUS_OKAY

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Several #25009 reviewers agreed that `DT_HAS_NODE_STATUS_OKAY(...)` was an undesirable API for the following reasons:

- it's inconsistent with the rest of the `DT_NODE_HAS_FOO` names
- `DT_NODE_HAS_FOO_BAR_BAZ(node)` was agreed upon as a shorthand
  for macros which are equivalent to `DT_NODE_HAS_FOO(node) && DT_NODE_HAS_BAR(node) && DT_NODE_HAS_BAZ(node)`, and `DT_HAS_NODE_STATUS_OKAY` is an odd duck
- `DT_NODE_HAS_STATUS(..., okay)` was viewed as more readable anyway
- it is seen as a somewhat aesthetically challenged name

Replace all users with `DT_NODE_HAS_STATUS(..., okay)`, which is semantically equivalent but came along later in the development of the patch series.

This is mostly done with sed, but a few remaining cases were done by hand, along with whitespace, docs, and comment changes.

The desire was to remove this macro in #25009, but it was decided the churn on other PRs was already too great, so it's being proposed as a post-rc1 change instead.

### CODE REVIEW

**Review by vanwinkeljan — APPROVED** [review]
+1 for the display changes

**Review by ioannisg — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]

**Comment by galak** [comment]
Built test over at https://buildkite.com/zephyr/zephyr-testingx/builds/181#035b1c5a-9f8f-4641-8349-84ffca8dea1a w/o any issues.

**Comment by pabigot** [comment]
> Built test over at https://buildkite.com/zephyr/zephyr-testingx/builds/181#035b1c5a-9f8f-4641-8349-84ffca8dea1a w/o any issues.

Interesting, but you have to be a member of Zephyr to see that page.  Collaborators not included.

**Comment by galak** [comment]
> Interesting, but you have to be a member of Zephyr to see that page. Collaborators not included.

Now should be generally visible.

**Review by erwango — APPROVED** [review]
Passing on all STM32

**Pull request merged**
