### PR TITLE
soc: arm: nxp_kinetis: ke1xf: convert clock ip source code to new DT API

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Convert the code for setting the clock IP source of the various IPs present in the NXP KE1xF SoC series to the new DT API.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Review by galak — COMMENTED** [review]
I was think we'd move these to drivers like it is on openisa.

**Comment by henrikbrixandersen** [comment]
> I was think we'd move these to drivers like it is on openisa.

The clock IP source setting is clock-controller specific (and thus SoC specific). It was moved _from_ drivers _to_ SoC previously.

**Comment by galak** [comment]
> > I was think we'd move these to drivers like it is on openisa.
> 
> The clock IP source setting is clock-controller specific (and thus SoC specific). It was moved _from_ drivers _to_ SoC previously.

I'm fine w/this, but at some point we should put this back in the drivers.

**Comment by henrikbrixandersen** [comment]
@galak I'll see if I can come up with a good solution for moving these calls to the drivers instead. For now, I'd like if we could merge this API conversion.

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
