### PR TITLE
boards: nxp: frdm_mcxw71: Add LinkServer runner support

### PR DESCRIPTION
**Pull request by butok**
Adds the LinkServer runner support for the FRDM-MCXW71 board.

### CODE REVIEW

**Review by dleach02 — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Comment by decsny** [comment]
does board doc need update then

**Review by danieldegrasse — DISMISSED** [review]
Board doc does need an update, this changes the default runner for the board because we include Linkserver first. I'd like to see a section mentioning that you need to install the linkserver debug host tools to debug the board. An example of a doc page that outlines this is the LPC55S36: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/nxp/lpcxpresso55s36/doc/index.rst?plain=1#L162

Please feel free to dismiss my block once the documentation has been updated to specify that the default runner is Linkserver.

**Comment by butok** [comment]
> Board doc does need an update, this changes the default runner for the board because we include Linkserver first. I'd like to see a section mentioning that you need to install the linkserver debug host tools to debug the board. An example of a doc page that outlines this is the LPC55S36: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/nxp/lpcxpresso55s36/doc/index.rst?plain=1#L162
> 
> Please feel free to dismiss my block once the documentation has been updated to specify that the default runner is Linkserver.

Hi @danieldegrasse you can unblock it.

The documentation already declares that  the board is configured by default to use the MCU-Link CMSIS-DAP Onboard Debug Probe. And Jlink is optional via "west flash -r jlink".

**Comment by danieldegrasse** [comment]
> The documentation already declares that the board is configured by default to use the MCU-Link CMSIS-DAP Onboard Debug Probe. And Jlink is optional via "west flash -r jlink".

Sure, I saw that- the specific change I'm asking for is that we call out the need to download the Linkserver binary. I'll dismiss my block though, because you are correct that the documentation right now is unlikely to mislead users.

**Review by mmahadevan108 — CHANGES_REQUESTED** [review]
Update the board documentation page to indicate this support. Similar to other boards such as [FRDM-MCXN947](https://docs.zephyrproject.org/latest/boards/nxp/frdm_mcxn947/doc/index.html#configuring-a-debug-probe)

**Comment by butok** [comment]
> Update the board documentation page to indicate this support. Similar to other boards such as [FRDM-MCXN947](https://docs.zephyrproject.org/latest/boards/nxp/frdm_mcxn947/doc/index.html#configuring-a-debug-probe)

@mmahadevan108 
Additional information is only on how to reprogram to the default CMSIS-DAP firmware (which is already programmed by default). It is only useful for someone who has already reprogrammed it to JLINK.
Nothing wrong. Just please confirm, are you sure you want to duplicate this for each platform?

**Comment by danieldegrasse** [comment]
> Additional information is only on how to reprogram to the default CMSIS-DAP firmware (which is already programmed by default). It is only useful for someone who has already reprogrammed it to JLINK.
Nothing wrong. Just please confirm, are you sure you want to duplicate this for each platform?

Personally, I like having the blub in each board linking to the update process- since most users won't be reading every board doc page. That being said, certainly won't block over it

**Comment by butok** [comment]
@mmahadevan108 
Added chapter "Using LinkServer".

**Review by danieldegrasse — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
Thank you for making the change.

**Pull request merged**
