### PR TITLE
drivers: hwinfo: add NXP MCUX RCM hwinfo driver

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add driver shim for the NXP MCUX Reset Control Module (RCM) for determining reset cause.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
This was tested on the `frdm_k64f` and the `twr_ke1xf` boards. It was compile-tested for the `ip_k66f` board.
There are other supported NXP SoC in the tree, which also contain the RCM module, but I have no hardware for test and verification of those.

**Comment by henrikbrixandersen** [comment]
@arvinf FYI.

**Review by alexanderwachter — APPROVED** [review]
LGTM

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
> This was tested on the frdm_k64f and the twr_ke1xf boards. It was compile-tested for the ip_k66f board.
There are other supported NXP SoC in the tree, which also contain the RCM module, but I have no hardware for test and verification of those.

Thanks @henrikbrixandersen. Could you go ahead and add `HAS_MCUX_RCM` to the other SoCs? I tested this on `frdm_k64f`, `frdm_kl25z`, and `frdm_k22f`. The remaining boards will be covered in our board farm testing.

**Comment by henrikbrixandersen** [comment]
> Could you go ahead and add `HAS_MCUX_RCM` to the other SoCs? I tested this on `frdm_k64f`, `frdm_kl25z`, and `frdm_k22f`. The remaining boards will be covered in our board farm testing.

@MaureenHelm I have added it to all the supported Kinetis SoCs where the MCUXpresso SDK indicates presence of the RCM.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
