### PR TITLE
board: arm: support cm4 debug way

### PR DESCRIPTION
**Pull request by Lucien-Zhao**
Signed-off-by: Lucien-Zhao <lucien.zhao@nxp.com>

### CODE REVIEW

**Review by danieldegrasse — APPROVED** [review]
These changes on my system. I know that within the MCUXpresso IDE a jlinkscript file is used when debugging the Cortex M4 core. @Lucien-Zhao, do you know what the purpose of that script file in the SDK is?

**Comment by dleach02** [comment]
@Lucien-Zhao, can you rebase your branch and push out an update to see if it will work around the CI failure?

**Comment by Lucien-Zhao** [comment]
> These changes on my system. I know that within the MCUXpresso IDE a jlinkscript file is used when debugging the Cortex M4 core. @Lucien-Zhao, do you know what the purpose of that script file in the SDK is?

This script is used to help debugger connect to cm4 core. Due to default core is cm7, so debugger can't connect cm4 core directly, this script will release cm4 core.

**Comment by Lucien-Zhao** [comment]
> @Lucien-Zhao, can you rebase your branch and push out an update to see if it will work around the CI failure?

OK, I will try rebase on my local and push.

**Comment by danieldegrasse** [comment]
> This script is used to help debugger connect to cm4 core. Due to default core is cm7, so debugger can't connect cm4 core directly, this script will release cm4 core.

So without that JLink script file, the requirement to connect to the CM4 core is that the CM7 core already be running code? I'm just trying to understand what functionality we will lose by not having the script file in Zephyr

**Comment by Lucien-Zhao** [comment]
> > This script is used to help debugger connect to cm4 core. Due to default core is cm7, so debugger can't connect cm4 core directly, this script will release cm4 core.
> 
> So without that JLink script file, the requirement to connect to the CM4 core is that the CM7 core already be running code? I'm just trying to understand what functionality we will lose by not having the script file in Zephyr

In jlinkscript, cm7 will be redirected to a loop defined by ROM code and release cm4 core to run. RT1170 boot core on your board is cm7 and cm4 core is halted. If you debug with cm4 core, you only download the cm4 image, however cm4 core can't run directly.

**Review by dleach02 — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
