### PR TITLE
tests/kernel/mem_protect/userspace: Additional tests for userspace

### PR DESCRIPTION
**Pull request by jedomagalski**
Added three tests for kernel objects focusing on 1) revoking
access to a k_object that the thread does not have
permissions to access, 2) accessing a k_object after
permissions to access it were revoked, and 3) trying to
revoke access to a k_object from a parent thread by a
child thread.  Additionally, added a test for
k_thread_user_mode_enter().

revoke_noperms_object() tests by calling
k_object_access_revoke() on a semaphore (kernel object) that it
does not have access to (ksem).

access_after_revoke() tests ability to access a semaphore after
access has been revoked by itself.

revoke_other_thread() tests whether a thread can revoke access
for an object for which it has permissions from a thread for
which it does not have permissions.

user_mode_enter() tests whether k_thread_user_mode_enter()
truly enters user mode.

Tested on qemu_x86 and frdm_k64 with pr-4974 applied, passes
on qemu_x86 but requires small fix for ARM (will submit
separately).

Signed-off-by: Joshua Domagalski <jedomag@tycho.nsa.gov>

### CODE REVIEW

**Comment by stephensmalley** [comment]
FYI, fix for ARM on top of pr-4974 is at https://github.com/stephensmalley/zephyr/commit/8c9a66e01fd3cb1e8ea76d1ff75d5fe48de57c3c

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
Looks like we are getting lots of CI failures.
We probably need to disable user mode Kconfig on ARM since it isn't completely implemented yet.
See #5819

**Comment by agross-linaro** [comment]
thats fine.  we can fix it up when we get the userspace patches merged.

**Comment by andrewboie** [comment]
recheck

**Review by stephensmalley — APPROVED** [review]

**Pull request merged**
