### PR TITLE
soc: xtensa: intel_adsp: cavs: fix sparse warnings on unsafe cached/uncached conversions

### PR DESCRIPTION
**Pull request by kv2019i**

### CODE REVIEW

**Comment by kv2019i** [comment]
SOF CI test run with this PR: https://github.com/thesofproject/sof/pull/8117

**Comment by kv2019i** [comment]
FYI @lyakh @marc-hb

**Comment by kv2019i** [comment]
V2 uploaded addressing comments and CI fails on Zephyr side. Marking as ready for review.

**Comment by kv2019i** [comment]
V3 uploaded:
 - fix the commit message also in the first patch

**Review by andyross — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by softwarecki — APPROVED** [review]

**Review by marcinszkudlinski — APPROVED** [review]

**Pull request merged**
