### PR TITLE
drivers: bluetooth: hci: Multiple write support for BlueNRG-MS

### PR DESCRIPTION
**Pull request by HoZHel**
Provide multiple write transaction support for BlueNRG-MS, st_hci_spi_v1 protocol. Since by default, BlueNRG-MS write buffer supports up to 127 bytes; however, it is possible to have consecutive write transactions so as to send data more than 127 bytes.

### CODE REVIEW

**Comment by msmttchr** [comment]
@arbrauns, could you please have a look at this change and provide some feedback ?

**Comment by jori-nordic** [comment]
@HoZHel adding you in https://github.com/zephyrproject-rtos/zephyr/pull/67784

**Comment by HoZHel** [comment]
The failed check is not related to my changes.

**Comment by HoZHel** [comment]
@jhedberg  Would you please take a look at the PR?

**Review by jori-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
