### PR TITLE
pm: policy: Consider substates for state lock functions

### PR DESCRIPTION
**Pull request by carlocaione**
Extend the current `pm_policy_state_lock_*()` functions to support substates.

### CODE REVIEW

**Comment by ceolin** [comment]
I don't see anything wrong with the patch. Just thinking if wouldn't be better having only one API to lock states that covers states and substates, this way we could avoid having to lists to track locks and also two different calls to check if  a state is locked.

**Comment by ceolin** [comment]
> > Just thinking if wouldn't be better having only one API to lock states that covers states and substates, this way we could avoid having to lists to track locks and also two different calls to check if a state is locked.

> Yes. I added a new API because I didn't want to break the API and all the platforms already using those. Is this API considered stable or we can break it? 

I believe so, this API is still considered experimental. I rather having it changed than having the same functionality duplicated.

**Comment by carlocaione** [comment]
@ceolin modifying this API is proving to be a bit of a PITA because external modules are using this API.

**Comment by carlocaione** [comment]
@ceolin this is ready for review again.

**Review by gmarull — DISMISSED** [review]
LGTM

**Review by ceolin — DISMISSED** [review]

**Comment by carlocaione** [comment]
@ceolin @gmarull pushed again with the correct SHA for `hal_ti`.

**Review by gmarull — APPROVED** [review]

**Comment by carlocaione** [comment]
given that the `hal_ti` changes were merged, should we merge this like ASAP?

**Review by ceolin — APPROVED** [review]

**Pull request merged**
