### PR TITLE
[WIP] drivers: modem: gsm: mux: Support GSM 07.10 muxing protocol

### PR DESCRIPTION
**Pull request by jukkar**
Add support to GSM 07.10 muxing protocol which is used to
share the same UART for PPP and AT commands. This allows e.g.
the modem to send SMS and have PPP connection at the same
time.

This is pretty much work in progress, it compiles but will not work as full support is not yet there.

### CODE REVIEW

**Comment by mike-scott** [comment]
@jukkar was this going to be reintroduced at a later time?

**Comment by jukkar** [comment]
@mike-scott Yes, I am working on it right now. I will re-submit when it is in somewhat usable state. It will most probably miss the 2.2 deadline.

**Comment by GeorgeGkinis** [comment]
Happy to know there will be an implementation of the GSM 07.10 protocol. I have been looking for an implementation for a long time!

I did some research about eating implementations and made a feature request at Espressif for the ESP-IDF. 

Details about the search result and all implementations I could find here : https://github.com/espressif/esp-idf/issues/4688

**Comment by jukkar** [comment]
Hi @GeorgeGkinis I am hopefully be able to send the mux code to review soon. My implementation is not using virtual UARTs as Zephyr does not have that kind of concept and I did not want to start to implement this kind of big feature just for muxing. Virtual UART support could be done at some point if needed. So for SMSs and location data, some kind of APIs are needed to pass the data to/from applications.
Anyway, my code is able to create the DLCIs and negotiate the channels to modem, I am using SIM808 for testing. Problem is that when I try to send AT commands to the correct DLCI (after establishing the channels), the modem just refuses to respond. Difficult to know what is going on as there are not really any examples in Internet for normal packet flow when using muxing. If I am not able to resolve this soon, I will still send the PR for a review as a draft.

**Comment by GeorgeGkinis** [comment]
@jukkar maybe this could help.
Also many modems like in the example also have GPS. Please bear that in mind, as to allow the parsing of the incoming NMEA.

I found this packet flow example which uses a SIMCOM module.

http://lists.openvehicles.com/pipermail/ovmsdev/2017-October/003359.html

Thank your efforts!

**Comment by jukkar** [comment]
It seems that I cannot re-open this PR, so created a new one at #23422. Lets move the discussion there.

**Pull request closed without merging**
