### PR TITLE
doc: usb: add missing macro documentation, fix sample references, add note about planned deprecation

### PR DESCRIPTION
**Pull request by jfischer-no**
Add missing documentation to USBD_DEVICE_DEFINE,
USBD_CONFIGURATION_DEFINE and USBD_DEFINE_CLASS macros.

Remove references to new device APIs that are not supported by the
samples.

Add a note about about the deprecation of current USB device support.

### CODE REVIEW

**Review by tmon-nordic — DISMISSED** [review]

**Comment by aescolar** [comment]
@jfischer-no rebase needed.

> The head ref may contain hidden characters: "pr-device-next-doc-macros-\u04E8\u0440\u0456\u043A-\u0436\u043E\u049B"

First time I see this warning from GH..

**Comment by tmon-nordic** [comment]
> > The head ref may contain hidden characters: "pr-device-next-doc-macros-\u04E8\u0440\u0456\u043A-\u0436\u043E\u049B"
> 
> First time I see this warning from GH..

GitHub simply doesn't like Өрік-жоқ ending in the branch title. I would considered these Unicode characters harmless.

**Review by tmon-nordic — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
LGTM, nice.

**Comment by carlescufi** [comment]
@aescolar this should be ready to merge

**Comment by aescolar** [comment]
> @aescolar this should be ready to merge

@carlescufi there is no need to ping release managers unless something which was ready for more than a day did not get in. The merge queue dashboard shows what is ready ;). PRs are merged in batches.

**Pull request merged**
