### PR TITLE
tests: adding test cases for counter RTC on nucleo_l152 board

### PR DESCRIPTION
**Pull request by FRASTM**
This patch enables the RTC as counter feature so that the testcase tests/drivers/counter/counter_basic_api
can run on this nucleo_l152re board from STMicroelectronics

$ west build -p auto -b nucleo_l152re tests/drivers/counter/counter_basic_api/

Signed-off-by: Francois Ramu francois.ramu@st.com

### CODE REVIEW

**Comment by FRASTM** [comment]
START - test_all_channels                                       
Testing RTC_0                                                   
D: Set Alarm: 11                                                
                                                                
 PASS - test_all_channels                                       
================================================================
START - test_late_alarm                                         
Skipped for RTC_0                                               
 PASS - test_late_alarm                                         
================================================================
START - test_late_alarm_error                                   
Skipped for RTC_0                                               
 PASS - test_late_alarm_error                                   
================================================================
START - test_short_relative_alarm                               
                                                                 
 PASS - test_short_relative_alarm                               
================================================================
START - test_cancelled_alarm_does_not_expire                    
Skipped for RTC_0                                               
 PASS - test_cancelled_alarm_does_not_expire                    
================================================================
START - test_set_top_value_without_alarm                        
Skipped for RTC_0                                               
 PASS - test_set_top_value_without_alarm                        
================================================================
Test suite test_counter succeeded                               
================================================================
PROJECT EXECUTION SUCCESSFUL

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
@FRASTM please rebase

**Comment by carlescufi** [comment]
@FRASTM please rebase

**Comment by carlescufi** [comment]
@FRASTM please rebase

**Comment by ioannisg** [comment]
@ABOSTM maybe you could rebase this PR so we can get it in?

**Comment by FRASTM** [comment]
rebase

**Pull request merged**
