### PR TITLE
Get rid of 'option env' symbols + display properties on multi.def. symbols in the right place

### PR DESCRIPTION
**Pull request by ulfalizer**
This series adds two changes that are only related in that the first one makes the second one much cleaner to implement.

First change:
Get rid of `option env` symbols and have `$FOO` directly reference the environment variable `FOO`.

Second change:
For symbols defined in multiple locations (e.g., `Kconfig.defconfig` symbols), display all properties (`selects`, `defaults`, etc.) on the definition that actually has the property. This applies to the RST documentation and the menuconfig information display.

See the commit messages for longer descriptions and motivations. Some major Kconfiglib surgery was required here. The end result is cleaner codewise as well though.

Symbol reference before:

beforechange

Symbol reference after:

afterchange

### CODE REVIEW

**Comment by ulfalizer** [comment]
CC @carlescufi @SebastianBoe @mbolivar @dbkinder

**Review by carlescufi — COMMENTED** [review]
What happens to external apps using this for `ZEPHYR_BASE`? See for example here: https://github.com/runtimeco/mcuboot/blob/master/boot/zephyr/Kconfig#L149

**Comment by ulfalizer** [comment]
@carlescufi 
Whops, had missed that one.

Should be fine though, because the symbol is named the same as the environment variable. See the backwards compatibility note in the commit message in https://github.com/zephyrproject-rtos/zephyr/pull/7602/commits/d7128272f1c38f9f4fcb634fe8e3dd08c1a71ea7.

The symbol itself could be removed though. I'll do that.

**Comment by carlescufi** [comment]
>Whops, had missed that one.

You didn't, this is an external repository using Zephyr

**Comment by ulfalizer** [comment]
@carlescufi 
Hmm... would need to make sure that those don't use `option env=...` unless the symbol name matches the environment variable name.

It should be possible to fully support `option env=...` still if absolutely required, though it gets a bit ugly codewise.

**Comment by carlescufi** [comment]
>Hmm... would need to make sure that those don't use option env=... unless the symbol name matches the environment variable name.

Those using it for `ZEPHYR_BASE` should be fine, I don't think anyone uses anything else for that, but I'd like to hear @mbolivar 's opinion on this.

**Comment by ulfalizer** [comment]
I updated the error message when `source`ing a missing file to mention the new behavior, so should be pretty easy to debug at least, if people are using other `option env=...` symbols.

**Comment by carlescufi** [comment]
By the way @ulfalizer, is this the only way to extend a Kconfig tree from an external, out-of-tree app? Or is there another way to do this?

**Comment by mbolivar** [comment]
> Those using it for ZEPHYR_BASE should be fine, I don't think anyone uses anything else for that, but I'd like to hear @mbolivar 's opinion on this.

That's the only use case I'm aware of us having documentation for:

http://docs.zephyrproject.org/application/application.html#application-cmakelists-txt

Seems like this patch is missing an update to those docs, though (specifically doc/application/application-kconfig.include).

I appreciate all the cleanups and efforts to make Zephyr behave more "normally", just want to make sure we are communicating clearly with users and minimizing backwards-incompatible changes that break out of tree applications.

**Comment by ulfalizer** [comment]
@mbolivar 
Yeah, I agree that it's a bit arbitrary to have it in the board porting guide. At least there are some links to it from elsewhere.

**Comment by mbolivar** [comment]
> @mbolivar
> Alright, will look into updating the docs as well.

Docs changes seem good to me (though see comment about possible future work).

**Review by mbolivar — APPROVED** [review]
Tested that `menuconfig` doesn't break on mcuboot, seems fine to me.

**Review by nashif — APPROVED** [review]

**Comment by SebastianBoe** [comment]
NACK.

It used to be that the scope of environment variables that were used by Kconfig was limited to the symbols that used option env. So you had an explicit list of environment variables that were used by Kconfig.

This explicit list must still exist for scoping reasons.

To do this I would suggest that we modify the build scripts to invoke Kconfig with an explicit list of env vars that should be passed on.

**Pull request merged**
