### PR TITLE
tests: drivers: dac loopback test on stm32 boards

### PR DESCRIPTION
**Pull request by FRASTM**
Add configuration to run the tests/drivers/dac/dac_loopback on more stm32 platforms.

Adapting the ADC input channels for running the testcase tests/drivers/dac/dac_loopback on
(new version of the https://github.com/zephyrproject-rtos/zephyr/pull/50742)

nucleo_l073rz adc1 input read from A0 --> connect to A2 on CN8
nucleo_g071rb adc1 input read from A0 --> connect to A2 on CN8
stm32l562e_dk adc1 input 13 from A4 --> connect to A2 on CN19

Requires the https://github.com/zephyrproject-rtos/zephyr/issues/58931

Add the connection on the hw board and the **dac_adc_loopback fixture** to Pass the test.

Signed-off-by: Francois Ramu [francois.ramu@st.com](mailto:francois.ramu@st.com)

### CODE REVIEW

**Review by martinjaeger — COMMENTED** [review]
Why are the changes to the ADC clock dividers required? Would be good to state the reason in the commit message.

If that's a bug in the ADC driver, I'd suggest to open a dedicated PR for that.

**Review by gautierg-st — DISMISSED** [review]

**Comment by martinjaeger** [comment]
Added DNM in order to wait until #58932 is resolved.

**Comment by FRASTM** [comment]
Rebased on c8a9634a3099436e026ec534164ddf519da61167
Fix the ACQ time with MAX value (instead of 0)  for stm32 boards.

**Review by martinjaeger — APPROVED** [review]
Thanks for the updates.

**Review by gautierg-st — APPROVED** [review]

**Pull request merged**
