### PR TITLE
doc: reduce the amount of warning, tip and note boxes

### PR DESCRIPTION
**Pull request by nashif**
The getting started guide has way too many warnings, notes and tips it
makes it very difficult to read and at times it looks really scary and
over complicated. Integrate most of those boxes in the text rather than
in boxes to keep the text readable.

### CODE REVIEW

**Comment by carlescufi** [comment]
I wonder if we could merge this with https://github.com/zephyrproject-rtos/zephyr/pull/16064, since the latter substantially rewrites the guide anyway?

**Comment by mbolivar** [comment]
Yeah, i think a lot of the getting started items can simply be deleted as shown in the PR Carles links.

**Comment by nashif** [comment]
@mbolivar @carlescufi I am fine with that, we posted the PRs at the same time almost :)

@mbolivar I can close this PR if you look at it and get inspired to remove some of those annoying boxes we have all over the place.

**Comment by mbolivar** [comment]
> @mbolivar I can close this PR if you look at it and get inspired to remove some of those annoying boxes we have all over the place and integrate into your PR. (you are doing that already i see)

I can handle that, sure.

**Review by ioannisg — APPROVED** [review]
Looks good to me; I am also sometimes scared off by too many warnings.

**Comment by mbolivar** [comment]
@nashif I've taken a look at this and merged it into https://github.com/zephyrproject-rtos/zephyr/pull/16064 so I'm going to close this as we've agreed -- feel free to reopen if I screwed something up.

**Pull request closed without merging**
