### PR TITLE
drivers: sdhc: sdhc_spi: change to max frequency during data read and…

### PR DESCRIPTION
**Pull request by ivanwagner**
At the moment the only used speed is the default 400kHz. This patch includes the possibility to switch to specific device tree spi-max-frequency during data transfers (read / write).

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@ivanwagner [this section](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/sd/sdmmc.c#L1091) of SDMMC initialization should set a SPI based host controller to the maximum frequency. Do you not see this occurring in your application?

**Comment by ivanwagner** [comment]
> @ivanwagner [this section](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/sd/sdmmc.c#L1091) of SDMMC initialization should set a SPI based host controller to the maximum frequency. Do you not see this occurring in your application?

This is interesting. I will make some tests next week and give you an anwser.

**Comment by ivanwagner** [comment]
> @ivanwagner [this section](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/sd/sdmmc.c#L1091) of SDMMC initialization should set a SPI based host controller to the maximum frequency. Do you not see this occurring in your application?

I tested it and you are right. Frequencies are passed correctly we were measuring at the wrong time when lower frequencies are used during card init. So we can actually close this issue.

**Comment by danieldegrasse** [comment]
> I tested it and you are right. Frequencies are passed correctly we were measuring at the wrong time when lower frequencies are used during card init. So we can actually close this issue.

@ivanwagner, great, glad to hear the SD subsystem is working for you. I'll go ahead and close this PR, feel free to reopen it if needed

**Pull request closed without merging**
