### PR TITLE
tests: drivers: uart: uart_pm: Disable PM_DEVICE_SYSTEM_MANAGED

### PR DESCRIPTION
**Pull request by nordic-krch**
When PM_DEVICE_SYSTEM_MANAGED is enabled (and that's the default) all devices are suspended when device go to idle state (through pm subsystem and not through just cpu_idle). In this test we are manually controlling PM of the DUT so we don't want that.

Additionally, suspend action is taking a semaphore and it is illegal in idle thread (where system managment operates) which causes assert in kernel scheduler.

### CODE REVIEW

**Comment by nordic-krch** [comment]
This is a fix for the same issue that #79268 tries to fix.

However, the root cause is that `k_sem_take` is called in the context of idle thread (where `pm_suspend_devices()` is called when `CONFIG_PM_DEVICE_SYSTEM_MANAGED=y`) and there is an assert in scheduler:
https://github.com/zephyrproject-rtos/zephyr/blob/d0e793f607d55b08b336c369c8bcb1febe6e78fa/kernel/sched.c#L121
which seems to not accept taking semaphore from idle task (@andyross is that correct?). Since pm_action by default can be called from thread so `k_sem_take` is accepted there and it can cause issues in other devices as well. 

Another thing is that this test will soon be removed because it tests non-runtime PM API (calling `pm_device_action_run()` directly) and that is being replaced by runtime PM.

**Comment by nordic-krch** [comment]
fyi @nordic-segl

**Review by nordic-segl — APPROVED** [review]

**Review by gmarull — DISMISSED** [review]
Yet another case that shows how broken is “device pm”.

**Comment by nordic-segl** [comment]
I use same fix in sdk-zephyr in this PR:
https://github.com/nrfconnect/sdk-zephyr/pull/2052/files

I get build failures due to warnings treated as errors in Twister.
```
warning: PM (defined at soc/silabs/silabs_s2/efr32bg22/Kconfig.defconfig:12,
soc/silabs/silabs_s2/efr32bg27/Kconfig.defconfig:12,
soc/silabs/silabs_s2/efr32mg24/Kconfig.defconfig:12, subsys/pm/Kconfig:13) was assigned the value
'y' but got the value 'n'. Check these unsatisfied dependencies: ((SOC_SERIES_EFR32BG22 &&
SOC_VENDOR_SILABS) || (SOC_SERIES_EFR32BG27 && SOC_VENDOR_SILABS) || (SOC_SERIES_EFR32MG24 &&
SOC_VENDOR_SILABS) || (SYS_CLOCK_EXISTS && HAS_PM)) (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_PM and/or look up PM in the
menuconfig/guiconfig interface. The Application Development Primer, Setting Configuration Values,
and Kconfig - Tips and Best Practices sections of the manual might be helpful too.


/jenkins_workspace/workspace/latest_sdk-nrf_PR-17380/zephyr/tests/drivers/uart/uart_pm/prj.conf:4: warning:
attempt to assign the value 'n' to the undefined symbol PM_DEVICE_SYSTEM_MANAGED
```

Test Result (13 failures / +12)

    Build & Test with Twister / Twister ZEPHYR 13/15 / nrf52840dk/nrf52840:drivers.uart.pm.drivers.uart.pm
    Build & Test with Twister / Twister ZEPHYR 5/15 / nrf52840dk/nrf52840:drivers.uart.pm.async.drivers.uart.pm.async
    Build & Test with Twister / Twister ZEPHYR 13/15 / nrf52840dk/nrf52840:drivers.uart.pm.enhanced_poll.drivers.uart.pm.enhanced_poll
    Build & Test with Twister / Twister ZEPHYR 15/15 / nrf52840dk/nrf52840:drivers.uart.pm.int_driven.drivers.uart.pm.int_driven
    Build & Test with Twister / Twister ZEPHYR 10/15 / nrf52840dk/nrf52840:drivers.uart.pm.no_rxpin.drivers.uart.pm.no_rxpin
    Build & Test with Twister / Twister ZEPHYR 11/15 / nrf52840dk/nrf52840:drivers.uart.pm.async.enhanced_poll.drivers.uart.pm.async.enhanced_poll
    Build & Test with Twister / Twister ZEPHYR 9/15 / nrf52840dk/nrf52840:drivers.uart.pm.int_driven.enhanced_poll.drivers.uart.pm.int_driven.enhanced_poll
    Build & Test with Twister / Twister ZEPHYR 10/15 / nrf54h20dk/nrf54h20/cpuapp:drivers.uart.pm.drivers.uart.pm
    Build & Test with Twister / Twister ZEPHYR 7/15 / nrf54h20dk/nrf54h20/cpuapp:drivers.uart.pm.async.drivers.uart.pm.async
    Build & Test with Twister / Twister ZEPHYR 6/15 / nrf54h20dk/nrf54h20/cpuapp:drivers.uart.pm.int_driven.drivers.uart.pm.int_driven
    Build & Test with Twister / Twister ZEPHYR 15/15 / nrf54l15pdk/nrf54l15/cpuapp:drivers.uart.pm.drivers.uart.pm
    Build & Test with Twister / Twister ZEPHYR 4/15 / nrf54l15pdk/nrf54l15/cpuapp:drivers.uart.pm.async.drivers.uart.pm.async
    Build & Test with Twister / Twister ZEPHYR 1/15 / nrf54l15pdk/nrf54l15/cpuapp:drivers.uart.pm.int_driven.drivers.uart.pm.int_driven

**Comment by nordic-segl** [comment]
Maybe, instead setting
CONFIG_PM_DEVICE_SYSTEM_MANAGED=n
for all platforms, this KConfig can be set in boards/nrf54h20dk_nrf54h20_cpuapp.conf
???

**Review by masz-nordic — DISMISSED** [review]

**Comment by bjarki-andreasen** [comment]
> I use same fix in sdk-zephyr in this PR: https://github.com/nrfconnect/sdk-zephyr/pull/2052/files
> 
> I get build failures due to warnings treated as errors in Twister.
> 
> ```
> warning: PM (defined at soc/silabs/silabs_s2/efr32bg22/Kconfig.defconfig:12,
> soc/silabs/silabs_s2/efr32bg27/Kconfig.defconfig:12,
> soc/silabs/silabs_s2/efr32mg24/Kconfig.defconfig:12, subsys/pm/Kconfig:13) was assigned the value
> 'y' but got the value 'n'. Check these unsatisfied dependencies: ((SOC_SERIES_EFR32BG22 &&
> SOC_VENDOR_SILABS) || (SOC_SERIES_EFR32BG27 && SOC_VENDOR_SILABS) || (SOC_SERIES_EFR32MG24 &&
> SOC_VENDOR_SILABS) || (SYS_CLOCK_EXISTS && HAS_PM)) (=n). See
> http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_PM and/or look up PM in the
> menuconfig/guiconfig interface. The Application Development Primer, Setting Configuration Values,
> and Kconfig - Tips and Best Practices sections of the manual might be helpful too.
> 
> 
> /jenkins_workspace/workspace/latest_sdk-nrf_PR-17380/zephyr/tests/drivers/uart/uart_pm/prj.conf:4: warning:
> attempt to assign the value 'n' to the undefined symbol PM_DEVICE_SYSTEM_MANAGED
> ```
> 
> Test Result (13 failures / +12)
> 
> ```
> Build & Test with Twister / Twister ZEPHYR 13/15 / nrf52840dk/nrf52840:drivers.uart.pm.drivers.uart.pm
> Build & Test with Twister / Twister ZEPHYR 5/15 / nrf52840dk/nrf52840:drivers.uart.pm.async.drivers.uart.pm.async
> Build & Test with Twister / Twister ZEPHYR 13/15 / nrf52840dk/nrf52840:drivers.uart.pm.enhanced_poll.drivers.uart.pm.enhanced_poll
> Build & Test with Twister / Twister ZEPHYR 15/15 / nrf52840dk/nrf52840:drivers.uart.pm.int_driven.drivers.uart.pm.int_driven
> Build & Test with Twister / Twister ZEPHYR 10/15 / nrf52840dk/nrf52840:drivers.uart.pm.no_rxpin.drivers.uart.pm.no_rxpin
> Build & Test with Twister / Twister ZEPHYR 11/15 / nrf52840dk/nrf52840:drivers.uart.pm.async.enhanced_poll.drivers.uart.pm.async.enhanced_poll
> Build & Test with Twister / Twister ZEPHYR 9/15 / nrf52840dk/nrf52840:drivers.uart.pm.int_driven.enhanced_poll.drivers.uart.pm.int_driven.enhanced_poll
> Build & Test with Twister / Twister ZEPHYR 10/15 / nrf54h20dk/nrf54h20/cpuapp:drivers.uart.pm.drivers.uart.pm
> Build & Test with Twister / Twister ZEPHYR 7/15 / nrf54h20dk/nrf54h20/cpuapp:drivers.uart.pm.async.drivers.uart.pm.async
> Build & Test with Twister / Twister ZEPHYR 6/15 / nrf54h20dk/nrf54h20/cpuapp:drivers.uart.pm.int_driven.drivers.uart.pm.int_driven
> Build & Test with Twister / Twister ZEPHYR 15/15 / nrf54l15pdk/nrf54l15/cpuapp:drivers.uart.pm.drivers.uart.pm
> Build & Test with Twister / Twister ZEPHYR 4/15 / nrf54l15pdk/nrf54l15/cpuapp:drivers.uart.pm.async.drivers.uart.pm.async
> Build & Test with Twister / Twister ZEPHYR 1/15 / nrf54l15pdk/nrf54l15/cpuapp:drivers.uart.pm.int_driven.drivers.uart.pm.int_driven
> ```

This is a long standing issue, where many platforms define their own config PM which has nothing to do with zephyrs config...

**Comment by nordic-krch** [comment]
Moved to nrf54h20 config

**Review by bjarki-andreasen — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> Maybe, instead setting
> CONFIG_PM_DEVICE_SYSTEM_MANAGED=n

The whole PM story needs a good rework, see the discussion https://github.com/zephyrproject-rtos/zephyr/issues/75963, probably to do this as a stop gap now.

**Pull request merged**
