### PR TITLE
Bluetooth: ATT: Fix ATT corrupting mem_slab structure after free

### PR DESCRIPTION
**Pull request by joerchan**
Fix ATT releasing the att structure back to the memory slab allocator
before the structure is actually ready to be released. The memory slab
allocator will write context data inside the freed slab which is
currently being overwritten by l2cap during channel teardown.

This manifests as an "Unable to allocate ATT context for conn" when
reconnecting with multiple connections.

Since the l2cap channel is embedded inside of the ATT context and l2cap
still has a valid referenc to the l2cap channel we need to release the
ATT context at a later time.
This should be fixed by implementing the channel destroy function and
releasing the channel there.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@Vudentz @jhedberg I fixed the issue I was facing. Silly mistake with one corruption remaining. I think it has been fixed now but I would like @MarekPieta to confirm using the real setup.

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by Vudentz** [comment]
@joerchan  It looks like there are a few places which are missing the destroy callback.

**Comment by joerchan** [comment]
@Vudentz Thank you, missed the smp_null channel.

@jhedberg I have split the commits as suggested. I created 3 instead. One to introduce the destroy callback for fixed channels. One to free the ATT context in the destroy callback. 
The last one is moving the clear of the channel status bits from after the destroy callback. Instead I put this when the l2cap channel is created. I found this to be safer as we don't have to rely on the memory given to us to be zero-set.
@Vudentz This is different since you approved. (you approved that I just moved it before the destroy callback).

**Comment by MarekPieta** [comment]
I used my setup and confirmed that it works for me.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
