### PR TITLE
hwmv2: hardware model version 2 (squashed)

### PR DESCRIPTION
**Pull request by nordicjm**

### CODE REVIEW

**Comment by mmahadevan108** [comment]
Is there a need to list all the commit SHA's in the commit log. Instead could we point to the branch name since we plan to retain it.

**Comment by mmahadevan108** [comment]
Also should we update release notes and migration guide documents?

**Comment by carlescufi** [comment]
> Is there a need to list all the commit SHA's in the commit log. Instead could we point to the branch name since we plan to retain it.

It was agreed in the Discord conversation.

**Comment by carlescufi** [comment]
> Also should we update release notes and migration guide documents?

Good point, this needs to come straight after the merge.

**Pull request merged**
