### PR TITLE
tests: drivers: can: fold the CAN-FD tests into the main API tests

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Fold the CAN-FD specific tests into the main CAN API tests and stop treating the CAN-FD API functionality as an add-on to the CAN API. This further allows reusing the various test definitions, test frames, and test filters between the two test suites.

Remove the now unused "canfd" from lists of supported board features.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
@martinjaeger, @str4t0m, @alexanderwachter, @karstenkoenig: Any opinions on this?

**Comment by alexanderwachter** [comment]
Makes sense! Did not have time for a deep review so far.

**Comment by alexanderwachter** [comment]
@henrikbrixandersen I would rather keep the semaphore and queue local to the files where they are used. Moving the const data makes sense!
Not a blocker. Just my personal opinion.

**Review by alexanderwachter — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]
LGTM

**Pull request merged**
