### PR TITLE
kernel/timeout: Fix recursive spinlock in z_set_timeout_expiry()

### PR DESCRIPTION
**Pull request by andyross**
The z_set_timeout_expiry() function was added in part to simply the
locking strategy, but it missed a case where a function it was calling
was re-locking the same spinlock.  It "works"[1] in uniprocessor
environments, but can be a deadlock in SMP.

Fix this by moving the meat of the function to an unlocked utility,
use that locally, and turn the entry point into one that does locking.
Actually this only gets called from idle now, which is a use case that
will go away when TICKLESS_IDLE is removed as a separate feature (once
you know all timeouts are set tickless, you don't need to set it from
the idle entry at all).

Discovered via lucky inspection.

[1] It doesn't work.  It releases the lock prematurely at the end of
the inner block.  But in practice this wasn't discovered.

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by pabigot — APPROVED** [review]

**Review by pdunaj — APPROVED** [review]
Change is fine.
@pizi-nordic comment makes sense but it is not related to the issue described. In my opinion it should be done under different PR or issue.

**Review by pdunaj — CHANGES_REQUESTED** [review]
Just noticed that indeed there is part of the code that is not included in the new internal function as pointed by @pizi-nordic .

```
#ifdef CONFIG_TIMESLICING	#ifdef CONFIG_TIMESLICING
	if (_current_cpu->slice_ticks && _current_cpu->slice_ticks < ret) {		if (_current_cpu->slice_ticks && _current_cpu->slice_ticks < ret) {
		ret = _current_cpu->slice_ticks;			ret = _current_cpu->slice_ticks;
	}		}
#endif
```

**Comment by pabigot** [comment]
I think this issue has a risk of becoming like all the others related to timing I've encountered since starting with zephyr: mixing up multiple problems.

I have not looked at the time-slicing infrastructure because I don't care about the time-slicing infrastructure, but I can certainly believe that there's bad interaction between management of slice ticks and scheduling timeouts.

However I also believe, though I may be wrong, that the PR correctly eliminates a theoretical bug due to improperly nested lock regions.  Which is all it claims to do.

Unless the two concerns are coupled in a non-obvious way, I do not believe this PR should be blocked based on lingering concerns about time-slicing.

**Comment by pdunaj** [comment]
@pabigot Just to clarify. I also think that PR should only fix the described issue. If there is anything else it should be handled separately.
The thing is that `_add_timeout` and `z_set_timeout_expiry` while calling `_get_next_timeout_expiry` where also doing part related to `CONFIG_TIMESLICING`, while in the proposed internal function this part is gone. I.e. behavior will change as `slice_ticks` is not used anymore in these two calls.

If this is intended and correct then all is fine but it does not look right.

**Comment by andyross** [comment]
Oh, indeed.  The slice clamp happened outside the lock when the function was called unlocked, so apparently it didn't register to my brain which was focused on locking.  Now it's inside the lock always and the logic is identical to the old code.

**Review by pdunaj — APPROVED** [review]

**Review by pizi-nordic — APPROVED** [review]

**Pull request merged**
