### PR TITLE
console: Remove deprecated function console_register_line_input

### PR DESCRIPTION
**Pull request by galak**
console_register_line_input has been deprecated for at least 2 releases
so we can now remove it.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by pfalcon** [comment]
So, if I remember correctly, that function was introduced to preclude people from calling uart_register_input(), and native_stdin_register_input() hardware-specific functions, and at least abstract that behind a "console" interface. The real problem are those functions, console_register_line_input() is deprecated because those should be deprecated.

**Comment by galak** [comment]
> So, if I remember correctly, that function was introduced to preclude people from calling uart_register_input(), and native_stdin_register_input() hardware-specific functions, and at least abstract that behind a "console" interface. The real problem are those functions, console_register_line_input() is deprecated because those should be deprecated.

I think we can safely remove `native_stdin_register_input`.  However `uart_register_input` seems to still be used by `console_getline_init`

**Comment by galak** [comment]
Reference to commit that deprecated things 371aea873590666a79509b79350e07609777d930

**Review by ioannisg — APPROVED** [review]

**Comment by galak** [comment]
> > So, if I remember correctly, that function was introduced to preclude people from calling uart_register_input(), and native_stdin_register_input() hardware-specific functions, and at least abstract that behind a "console" interface. The real problem are those functions, console_register_line_input() is deprecated because those should be deprecated.
> 
> I think we can safely remove `native_stdin_register_input`. However `uart_register_input` seems to still be used by `console_getline_init`

@pfalcon any feedback on this?

**Review by mnkp — APPROVED** [review]

**Review by aescolar — APPROVED** [review]
No complaints about the native_posix driver changes.
I make no claims about the removal of the deprecated `console_register_line_input()`

**Pull request merged**
