### PR TITLE
Samples: Basic battery measurement with NRF ADC

### PR DESCRIPTION
**Pull request by zarnobarintive**
This simple sample shows how to configure SAADC on NRF52 chip to
perform VDD voltage measurement without any other HW wiring.

Signed-off-by: Bartłomiej Żarnowski <bartlomiej.zarnowski@intive.com>

### CODE REVIEW

**Comment by pabigot** [comment]
See also #21606. 

 I'm not sure how you measure *battery* without any external hardware like a voltage divider.  What this sample does is measure Vdd, which is the voltage supplied to the MCU.  Normally the external supplied voltage goes through some sort of converter that can increase or decrease voltage to meet the needs of the MCU.

**Comment by zarnobarintive** [comment]
Hi,
  Thanks for comment.

> See also #21606
I've seen it. It is more advanced and show how to calc voltage with greater precision when you have proper wiring. However currently I've on desk small board which uses battery as a power supply without any other power regulator, just 2 capacitors on power pins. I got request to measure voltage on MCU (as you pointed) and since there is no other circuits between MCU and battery, measured voltage is same as battery voltage. Precision of such measurement is not to great but there are use cases where it is sufficient. Since I spent some time to discover how to configure it with zephyr I thought it might be useful for someone, since there is not much docs about ADC on zephyr doc page.
Hope I answered your question.

**Comment by pabigot** [comment]
I think having an example of this is worthwhile, but I would like to see it integrated into the sample proposed by #21606.  This variant could be selected by `BOARD_ENABLE_DCDC` or by a sample-specific Kconfig option.  Then all the battery-measurement stuff would be in one place.

That would depend on #21606 being merged.

**Comment by carlescufi** [comment]
> I think having an example of this is worthwhile, but I would like to see it integrated into the sample proposed by #21606. This variant could be selected by `BOARD_ENABLE_DCDC` or by a sample-specific Kconfig option. Then all the battery-measurement stuff would be in one place.
> 
> That would depend on #21606 being merged.

#21606 is merged, perhaps you can consider integrating this sample into the one introduced by that PR @zarnobarintive?

**Comment by zarnobarintive** [comment]
> > I think having an example of this is worthwhile, but I would like to see it integrated into the sample proposed by #21606. This variant could be selected by `BOARD_ENABLE_DCDC` or by a sample-specific Kconfig option. Then all the battery-measurement stuff would be in one place.
> > That would depend on #21606 being merged.
> 
> #21606 is merged, perhaps you can consider integrating this sample into the one introduced by that PR @zarnobarintive?

Sure, just need to dig in into delivered code.

**Comment by zarnobarintive** [comment]
@carlescufi @pabigot 
Please check if this is what was expected. I tried to keep style of previous code.
I don't have idea how to proper choose ADC device for that example, that's why I hardcoded ADC_0. If some different approach is preferred please give me some hints.
I also not sure about result of method ```adc_raw_to_millivolts```, looks like raw values are more accurate to voltage set on power supply in my lab. But I'm not an expert in this area.

**Comment by pabigot** [comment]
I was envisioning a solution that shared a little more code, as in #22497.

Does that approach work for you?  If so it'd be great if you could grab that commit and update this to incorporate it along with the README that explains it all (which I somehow managed to miss in the original solution).

**Comment by zarnobarintive** [comment]
@pabigot I checked your solution and it looks like it's nothing to do from my side. Please deliver your code, I'll drop this PR.
I'm not having nrf52_pca20020 to test and I'm not familiar with this board so I would rather not write Readme file since I'm not sure how this voltage divider is controlled on it.
While reading your code it looks like curve to convert from mv is different for direct MCU voltage measurement, I wonder why? Usage of divider doesn't change shape of curve rather just scale it. Is there any other reason why it's changed to linear?

**Comment by pabigot** [comment]
OK; thanks, I'll clean up my commit, add a README, and submit it sometime relatively soon.

The existing curve is for a LiPo battery which supplies voltages that are too high to be used for a direct connection to Vdd: you'd burn out the chip.  I don't have a battery discharge curve for lower voltages so just picked a two point range from minimum to maximum.

That's the sort of information that will have to go into the README.

**Pull request closed without merging**
