### PR TITLE
tests/lib/heap_align: improve test

### PR DESCRIPTION
**Pull request by npitre**
Many issues:

- heapmem[] is of type uint64_t meaning that it contains HEAP_SZ * 16
  bytes but the heap is initialized with only 1/16 of that, making
  this test's memory footprint way too large.

- The test to ensure the heap is empty uses an allocation size of
  (heap_end - heap_start - 8) which is wrong as heap_end and heap_start
  are uint64_t pointer types and therefore their difference will be 8x
  smaller than intended. Furthermore, the 8 here is unnessary as the
  chunk header size is already included in the location of heap_start.

- The heap start address misalignment bare no purpose as the misaligned
  start of the free heap is already controlled by the variable prefix
  allocation size.

- Alignment and sizes should rather be expressed in terms of size_t
  rather than uintptr_t.

Fix those issues, and add a few more test angles:

- Make the prefix allocation itterate across the entire alignment range
  to exercize all possible misalignments.

- Vary the aligned allocation size to better exercize the pre-alignment
  allocation and suffix handling.

- Double the aligned allocation to add more variability in the heap
  structure.

- Test the testing of emptiness by making sure that no more allocations
  are possible when we think we allocated it all.

### CODE REVIEW

**Review by andyross — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
Some tests seem to be having issues:

```
tests/lib/heap_align/lib.heap_align in qemu_arc_em:tests/lib/heap_align/lib.heap_align
*** Booting Zephyr OS build zephyr-v2.3.0-609-ga8b382f1850b  ***
Running test suite lib_heap_align_test
===================================================================
START - test_aligned_alloc

    Assertion failed at WEST_TOPDIR/zephyr/tests/lib/heap_align/src/main.c:43: check_heap_align: (s != NULL is false)
suffix allocation failed (0/8/8)
 FAIL - test_aligned_alloc
===================================================================
Test suite lib_heap_align_test failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Comment by npitre** [comment]
On Fri, 26 Jun 2020, Andrew Boie wrote:

> Some tests seem to be having issues:

No idea how to reproduce that.

Here I get:

```
[ 98%] Building C object zephyr/CMakeFiles/zephyr_final.dir/isr_tables.c.obj
[100%] Linking C executable zephyr.elf
Generating files from zephyr.elf for board: qemu_arc_em
[100%] Built target zephyr_final

INFO    - 
/home/nico/zephyr/zephyrproject/zephyr/sanity-out/qemu_arc_em/tests/lib/heap_align/lib.heap_align/build.log
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    1
```

No idea what the above means either.

**Comment by npitre** [comment]
Never mind. Just found that "west update" is apparently my friend.

**Comment by andrewboie** [comment]
qemu_arc_em doesn't support icount and tests fail due to host clock synchronization issues which can confound timing-sensitive tests. That might have something to do with it?

Doing some runs locally to see if I can get it to fail.

**Comment by andrewboie** [comment]
I don't think this is icount. This is failing reliably for me:

```
$ sanitycheck -c -T tests/lib/heap_align/
INFO    - JOBS: 32
INFO    - Selecting default platforms per test case
INFO    - Building initial testcase list...
INFO    - 18 test configurations selected, 238 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:   13/  18  72%  skipped:    0, failed:    0
ERROR   - qemu_cortex_m0            tests/lib/heap_align/lib.heap_align                FAILED: Failed
ERROR   - see: /home/apboie/projects/zephyr3/zephyr/sanity-out/qemu_cortex_m0/tests/lib/heap_align/lib.heap_align/handler.log
INFO    - Total complete:   14/  18  77%  skipped:    0, failed:    1
ERROR   - mps2_an385                tests/lib/heap_align/lib.heap_align                FAILED: Failed
ERROR   - see: /home/apboie/projects/zephyr3/zephyr/sanity-out/mps2_an385/tests/lib/heap_align/lib.heap_align/handler.log
INFO    - Total complete:   15/  18  83%  skipped:    0, failed:    2
ERROR   - qemu_arc_em               tests/lib/heap_align/lib.heap_align                FAILED: Failed
ERROR   - see: /home/apboie/projects/zephyr3/zephyr/sanity-out/qemu_arc_em/tests/lib/heap_align/lib.heap_align/handler.log
INFO    - Total complete:   16/  18  88%  skipped:    0, failed:    3
ERROR   - qemu_nios2                tests/lib/heap_align/lib.heap_align                FAILED: Failed
ERROR   - see: /home/apboie/projects/zephyr3/zephyr/sanity-out/qemu_nios2/tests/lib/heap_align/lib.heap_align/handler.log
INFO    - Total complete:   18/  18  100%  skipped:    0, failed:    4
INFO    - 14 of 18 tests passed (77.78%), 4 failed, 0 skipped with 0 warnings in 24.29 seconds
INFO    - In total 1 test cases were executed on 18 out of total 257 platforms (7.00%)
INFO    - 17 tests executed on platforms, 1 tests were only built.
```

**Comment by npitre** [comment]
On Fri, 26 Jun 2020, Andrew Boie wrote:

> qemu_arc_em doesn't support icount and tests fail due to host clock synchronization issues which can confound timing-sensitive tests. That might have something to do with it?

No, nothing timing sensitive here. I reproduced on qemu_cortex_m0 anyway.
Apparently a math problem.

**Comment by npitre** [comment]
OK found it. The needed change is:

```
-uint8_t heapmem[HEAP_SZ];
+uint8_t __aligned(8) heapmem[HEAP_SZ];
```

The heap code uses memory starting from a 8-byte boundary. Because of 
possibly random linker placement for this array, the inferred internal 
heap size wasn't as large as expected in some cases.

**Review by nashif — APPROVED** [review]

**Pull request merged**
