### PR TITLE
libc: minimal: Introducing errnos for key management.

### PR DESCRIPTION
**Pull request by nilsMontenegro**

### CODE REVIEW

**Comment by nilsMontenegro** [comment]
@carlescufi You might want to check.

**Comment by lemrey** [comment]
Hi @nilsMontenegro , since the commit changes errno.h in the libc implementation, perhaps you could reword the commit message to begin with "libc: " ? :)

**Comment by carlescufi** [comment]
@nilsMontenegro 
Can you rebase your commits as per:

http://docs.zephyrproject.org/latest/contribute/contribute_guidelines.html#contribution-workflow

**Comment by nilsMontenegro** [comment]
@pfalcon Hi. We use these error codes in our projects. They are also a part of other public errno.h files.

**Comment by nilsMontenegro** [comment]
@lemrey Hi. I changed the commit message but it seems the headline will not change.

**Comment by pfalcon** [comment]
> I changed the commit message but it seems the headline will not change.

You would need to change PR's title manually. This is not strictly necessary, but will speed up the review process.

**Comment by pfalcon** [comment]
> the commit message should be:

Of course, feel free to edit as needed. That was just an example of a good commit message.

**Comment by nilsMontenegro** [comment]
Good morning.
@carlescufi Rebased.
@pfalcon Took your proposed commit message.

**Comment by nilsMontenegro** [comment]
@pfalcon OK, I see the problem now. There are more errno files in SDK. But they already define things differently:
zephyr-rtos:
#define ENOSR 74
SDK:
#define ENOSR 63
#define EMULTIHOP 74

**Comment by pfalcon** [comment]
> There are more errno files in SDK. But they already define things differently:

Yes, that's true. SDK's headers come from project called "Newlib": https://sourceware.org/newlib/ . And "minimal" libc as included in Zephyr tree indeed has different numeric errors codes for some errors than "Newlib" libc.

> Should I add the new error codes also into the SDK?

Well, if you know how... SDK comes from https://github.com/zephyrproject-rtos/meta-zephyr-sdk , and as explained above, errno values come from external project. I think, we'll need solve situation with Newlib as we go. So far, this patch looks good to me, thanks for the update.

**Review by pfalcon — APPROVED** [review]

**Comment by nilsMontenegro** [comment]
> Well, if you know how...
I don't. It is good that it can stay on this state for now.

**Review by nashif — APPROVED** [review]

**Pull request merged**
