### PR TITLE
flash: mcux: return success on write protect (HACK)

### PR DESCRIPTION
**Pull request by mbolivar**
Write protection is currently not supported by the mcux flash
driver. This prevents it from working with the DFU subsystem, which
checks the error codes from this routine. Hack it for now by faking
success.

### CODE REVIEW

**Comment by mbolivar** [comment]
@MaureenHelm this is as discussed yesterday. No worries if you don't want this in mainline.

**Review by MaureenHelm — COMMENTED** [review]
What do you think about doing a software lock instead?

**Comment by jfischer-phytec-iot** [comment]
This (hack or software lock) is also necessary to support OT on Kinetis SoCs (I did it exactly like that)

**Comment by mbolivar** [comment]
Sure! I'll add a software lock.

**Comment by mbolivar** [comment]
@MaureenHelm @jfischer-phytec-iot updated

**Review by jfischer-no — COMMENTED** [review]
LGTM

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
