### PR TITLE
 boards: arm: nrf5340dk_nrf5340: i2c pincontrol needs bias-pull-up flag

### PR DESCRIPTION
**Pull request by MasoudShiroei**
drivers: pinctrl_nrf: Extempt nrf53xx from overwriting drive mode for TWIM

Previously a patch merged to overwrite drive modes for TWIM pins for nrf ICs. But the patch is not working for nrf53. The patch was made 6 months ago here:
https://github.com/zephyrproject-rtos/zephyr/pull/47145

This patch extempt the nrf53 from overwriting the drive mode for TWIM pins. The TWIM pins work with default status S0S1.

Signed-off-by: Masoud Shiroei <masoud.shiroei@assaabloy.com>

### CODE REVIEW

**Comment by MasoudShiroei** [comment]
> I don't see why the nrf5340 would not work with this - what board did you test this with?

It is a custom board. I will try with nRF5340-DK and come back to you.

**Comment by nordicjm** [comment]
The bug here appears to be a missing `bias-pull-up;` from the board's pinctrl file

**Comment by MasoudShiroei** [comment]
> bias-pull-up;
I added `bias-pull-up;` to the dtsi file and it start working. Great. Shall I close the pull request?

**Comment by nordicjm** [comment]
You can, though it has highlighted an issue with the nrf5340dk as that boards needs the `bias-pull-up;` line added, up to you if you want to submit a patch to fix that, if not one of us can pick it up.

**Review by nordicjm — CHANGES_REQUESTED** [review]
Commit message should have full board name in e.g. `boards: arm: nrf5340dk_nrf5340: message here`
And first 2 commits can be dropped

**Comment by MasoudShiroei** [comment]
> bias-pull-up;
Feel free to pick it up. I close this pull request. 

> Commit message should have full board name in e.g. `boards: arm: nrf5340dk_nrf5340: message here` And first 2 commits can be dropped

Please pick it up. And Thanks for the help.

**Comment by MasoudShiroei** [comment]
The bug can be fixed by bias-pull-up;

**Pull request closed without merging**
