### PR TITLE
boards: lpcxpresso55s69_cpu1: Fix CI failures

### PR DESCRIPTION
**Pull request by danieldegrasse**
This PR fixes the following CI failures for the lpcxpresso55s69_cpu1 target:
- samples/sensor/thermometer/sample/sensor.thermometer: fix pulled in from #49172
- samples/drivers/flash_shell/sample.drivers.flash.shell: remove dependency on KConfig HAS_MCUX_IAP
- tests/drivers/build_all/model/drivers.model.build: exclude test, platform does not have enough flash

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@galak @fabiobaltieri FYI. @galak, I rebased this branch onto yours so CI can run against all 3 fixes.

@fabiobaltieri I'm using an alternative fix for the IAP node from your PR. I'd like to remove the dependency on HAS_MCUX_IAP from the flash driver, since that KConfig will be dropped in the future, so I moved the file to instead change behavior based on the DT_COMPAT string on the devicetree.

As far as the modem test build failure goes, I bisected back to 2.7.0 and the build still seemed broken. The `lpcxpresso55s69_ns` target has only 96KB of flash available (since TFM is enabled) , so I think that excluding the test based on flash size is fair.

**Review by fabiobaltieri — APPROVED** [review]
Good stuff, thanks!

**Review by galak — APPROVED** [review]

**Comment by danieldegrasse** [comment]
@fabiobaltieri I'm going to unlink the SOC_FLASH_LPC issue. I'd view this PR as a hotfix: the root issue is that the changes to link driver enablement to DTS turned on the flash driver for all LPC parts, as the flash controller node is not explicitly set to `status=disabled` in the SOC DTSI.

As a long term fix, I'm going to review our platforms and determine which had flash enabled as of zephyr 3.1, then enable flash on those platforms and disable it for others.

**Review by dleach02 — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri I'm going to unlink the SOC_FLASH_LPC issue. I'd view this PR as a hotfix: the root issue is that the changes to link driver enablement to DTS turned on the flash driver for all LPC parts, as the flash controller node is not explicitly set to `status=disabled` in the SOC DTSI.
> 
> As a long term fix, I'm going to review our platforms and determine which had flash enabled as of zephyr 3.1, then enable flash on those platforms and disable it for others.

Sounds good to me!

**Pull request merged**
