### PR TITLE
tests: Bluetooth: Mesh: Default to ext adv

### PR DESCRIPTION
**Pull request by HaavardRei**
Changes twister tests and nrf samples from using legacy adv to ext adv
since this is the default for Mesh. Legacy adv is still tested in bsim.

Removes redundant test configuration testing ext adv.

Removes redundant config for ext_adv in `multi_ext_adv.conf`.

### CODE REVIEW

**Review by alxelax — DISMISSED** [review]

**Review by Balaklaka — APPROVED** [review]

**Review by omkar3141 — DISMISSED** [review]

**Review by PavelVPV — DISMISSED** [review]

**Comment by HaavardRei** [comment]
Built and flashed onoff-app to a nrf52840dk, provisioned and tested sample.

**Comment by omkar3141** [comment]
As a sanity check, it will good to crosscheck in the build that `CONFIG_BT_EXT_ADV` is indeed getting set to `Y` and not getting overridden to `N`.

**Review by omkar3141 — APPROVED** [review]

**Comment by HaavardRei** [comment]
> As a sanity check, it will good to crosscheck in the build that `CONFIG_BT_EXT_ADV` is indeed getting set to `Y` and not getting overridden to `N`.

I did! :)

**Review by alxelax — APPROVED** [review]

**Comment by alxelax** [comment]
Hi @PavelVPV, this requires your attention.

**Review by PavelVPV — APPROVED** [review]

**Pull request merged**
