### PR TITLE
[Backport v2.7-branch] doc: Add link to J-Link virtual MSD disable for SMP

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 9ecc7ddff81457c1115424e0d52e1637b5fbda5a from #44500

### CODE REVIEW

**Comment by stephanosio** [comment]
Rebased

**Review by de-nordic — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by lairdjm** [comment]
@cfriedt And another for next 2.7 release please

**Comment by cfriedt** [comment]
@stephanosio - any idea why the documentation build would be failing?

**Comment by stephanosio** [comment]
> @stephanosio - any idea why the documentation build would be failing?

@gmarull Sphinx seems to be stuck. Any thoughts?

**Pull request closed without merging**
