### PR TITLE
arm: arc: don't disable the MPU when reprogramming

### PR DESCRIPTION
**Pull request by tyrantlizard77**
There's no need for this and problems can happen if an interrupt occurs during the time the MPU is disabled.

Fixes: #12548

### CODE REVIEW

**Review by aurel32 — APPROVED** [review]
Thanks for the quick patch. I confirm it works as expected and fixes the reported issue. And I also think this explains why we needed changes like 1397269335eef0c47586a689dd4094ef8b9d734f (which should kept for performances reasons anyway).

**Review by ruuddw — DISMISSED** [review]
ARC MPUv2 hardware manual recommends disabling during reprogramming. And, it is not used for 'no_cache' as in the issue that's being solved here. I didn't run extensive tests, but there might be some new issues introduced with this PR.
Also, could there be other effects of ISRs during reprogramming? What if an ISR triggers a reschedule?
It might be more safe to lock interrupts, instead (would that increase interrupt latency, or is this code already called with interrupts disabled in some cases?)

**Review by ioannisg — APPROVED** [review]
I am fine with the ARM changes.

**Comment by andrewboie** [comment]
> What if an ISR triggers a reschedule?

Actually this is a great point.
Let's say thread A is reprogramming the MPU, we get an IRQ which reschedules to thread B, which reprograms the MPU again, then we swap back to thread A, and "finish" reprogramming the MPU which is now probably in an inconsistent state.

I'm thinking now that we really to replace the mpu enable/disable calls with irq_lock/unlock
@ioannisg @agross-linaro any comments?

**Comment by aurel32** [comment]
> I'm thinking now that we really to replace the mpu enable/disable calls with irq_lock/unlock
> @ioannisg @agross-linaro any comments?

At least in the context switch case, looking at `core/swap_helper.S` it seems the IRQ are re-enabled 20 instructions before calling `configure_mpu_stack_guard`. I wonder if things can be shuffled a bit so that there is no need to call irq_lock/unlock around the MPU change.

**Comment by ioannisg** [comment]
>It might be more safe to lock interrupts, instead (would that increase interrupt latency, or is this code already called with interrupts disabled in some cases?)

It would significantly increase it - unless we make sure that only the actual reprogramming goes inside the critical sections

**Comment by ioannisg** [comment]
> Let's say thread A is reprogramming the MPU, we get an IRQ which reschedules to thread B, which reprograms the MPU again, then we swap back to thread A, and "finish" reprogramming the MPU which is now probably in an inconsistent state.

This is independent of having enable/disable of mpu, if i understand correctly

**Comment by andrewboie** [comment]
> This is independent of having enable/disable of mpu, if i understand correctly

It is, I'm trying to make sure that what we are doing in this area is 100% correct in all cases

**Comment by ioannisg** [comment]
> I'm thinking now that we really to replace the mpu enable/disable calls with irq_lock/unlock
@ioannisg @agross-linaro any comments?

@andrewboie I really need to think more of this but I do not see the problem of ISR (and rescheduling) during context-switch: 

I am looking at the documentation of pendSV for ARM:

/**
 *
 * @brief PendSV exception handler, handling context switches
 *
 * The PendSV exception is the only execution context in the system that can
 * perform context switching. When an execution context finds out it has to
 * switch contexts, it pends the PendSV exception.
 *
 * When PendSV is pended, the decision that a context switch must happen has
 * already been taken. In other words, when __pendsv() runs, we *know* we have
 * to swap *something*.
 */

From that I understand the if an ISR occurs during an ongoing context-switch it will only set the ongoing pendSV to "pending". So the context switch procedures are not nested. I think that when we reach the point of reprogramming the mpu, the switch to the new thread _will_ happen (cannot be stopped) so the re-programming is safe.

If an ISR triggers rescheduling, the new context-switch will start back-to-back , as soon as the current one finishes. This only adds overhead of programming the MPU twice, but does not leave the mpu in inconsistent state.

@agross-linaro some assistance here is appreciated.

**Comment by ioannisg** [comment]
#12817  makes this one obsolete

**Comment by ioannisg** [comment]
@andrewboie could you update this, so it does not contain the ARM changes any more?

**Comment by andrewboie** [comment]
OK, I'll just close as I think we don't need the ARC changes either.
The scheduling stuff I was worried about can be investigated separately

**Pull request closed without merging**
