### PR TITLE
doc: net: Update NAT options for Internet connectivity

### PR DESCRIPTION
**Pull request by jukkar**
The host NAT options for QEMU/native_sim Internet connectivity needs updating.

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by sense-Jo** [comment]
Hi @jukkar, thank you for this PR, which helped me to get a working internet connection in Qemu!
However, there was one thing I had to change: At least on my system, after following the guide on [Networking with QEMU](https://docs.zephyrproject.org/latest/connectivity/networking/qemu_setup.html#networking-with-qemu), the name of the network interface isn't `zeth`, but `tap0`.
Isn't the interface only named `zeth` when using the `net-setup.sh` script, while with the `./loop-socat.sh` and `./loop-slip-tap.sh`, which the guide for Qemu advises to use, the interface would usually be named `tap0`?

**Comment by jukkar** [comment]
> Isn't the interface only named `zeth` when using the `net-setup.sh` script, while with the `./loop-socat.sh` and `./loop-slip-tap.sh`, which the guide for Qemu advises to use, the interface would usually be named `tap0`?

Hi @sense-Jo, there are two guides for setting up qemu, one is with tap0 https://docs.zephyrproject.org/latest/connectivity/networking/qemu_setup.html#networking-with-qemu and the other is with zeth https://docs.zephyrproject.org/latest/connectivity/networking/qemu_eth_setup.html#networking-with-eth-qemu
So both zeth or tap0 are valid interfaces. We try to guide people to use zeth instead, as it is somewhat easier to setup in the host side.

**Comment by sense-Jo** [comment]
@jukkar I can see that there are multiple options of connecting a Zehpyr (Qemu) application to a network.
I just now understood that NAT/masquerading is required for both Qemu networking options, and apparently required as well when using the `native_*` targets.
Thus I wonder if it would make sense to move the instructions on NAT/masquerading to a separate page, maybe under [Networking](https://docs.zephyrproject.org/latest/connectivity/networking/index.html) and titled something like "Internet access from hosted applications"?

**Comment by jukkar** [comment]
> Thus I wonder if it would make sense to move the instructions on NAT/masquerading to a separate page, maybe under [Networking](https://docs.zephyrproject.org/latest/connectivity/networking/index.html) and titled something like "Internet access from hosted applications"

Could you propose a PR for that, we can then review and see what it looks like.

**Pull request merged**
