### PR TITLE
boards: riscv: add Seeed Studio xiao_esp32c3

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Hi! Got one of these to play with, not much into the board beside the MCU but it may be handy to have it defined since we have a node for the XIAO pinout. Bit of funkyness going on with `HEAP_MEM_POOL_SIZE`, seems like many ESP drivers depends on dynamic memory, I tried to give it a reasonable default so it can build all the samples without having overlays and per-board configs everywhere.

The CAN pin are not defined in the XIAO pinout so I just picked two free ones just so it can be used to loopback test the CAN driver.

-- 8< --

Add Seeed Studio xiao_esp32c3, an ESP32-C3 based board using the XIAO form factor.

### CODE REVIEW

**Review by cfriedt — COMMENTED** [review]
LGTM other than it might be a good idea to reduce the size of `xiao_esp32c.jpg` and `xiao_esp32c3_pinout.png`. The pinout should be converted to jpeg. I would suggest aiming for 10k-50k.

**Comment by fkokosinski** [comment]
> LGTM other than it might be a good idea to reduce the size of `xiao_esp32c.jpg` and `xiao_esp32c3_pinout.png`. The pinout should be converted to jpeg. I would suggest aiming for 10k-50k.

+1. You can use the Python script provided in this commit message: https://github.com/zephyrproject-rtos/zephyr/commit/e81e92dbb9092a3d67ec7e17f0c2190239635a50

**Comment by fabiobaltieri** [comment]
> > LGTM other than it might be a good idea to reduce the size of `xiao_esp32c.jpg` and `xiao_esp32c3_pinout.png`. The pinout should be converted to jpeg. I would suggest aiming for 10k-50k.
> 
> +1. You can use the Python script provided in this commit message: [e81e92d](https://github.com/zephyrproject-rtos/zephyr/commit/e81e92dbb9092a3d67ec7e17f0c2190239635a50)

Yup, done, had already shrank the images from the originals a bit but I squeezed them a bit more, converted the second to jpeg as well and compressed to quality 75, eneded up doing it straight on gimp, the snippets wasn't playing well with something on my system.

**Comment by sylvioalves** [comment]
Looks good!

**Review by sylvioalves — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Pull request merged**
