### PR TITLE
Ethernet: Fix stm32f2 compilation error

### LINKED ISSUE #81329: drivers/ethernet/eth_stm32_hal.c fails to build on F2 series
**Describe the bug**
drivers/ethernet/eth_stm32_hal.c fails to build on F2 series

**To Reproduce**
1. twister -p nucleo_f207zg/stm32f207xx -s samples/net/sockets/dumb_http_server/sample.net.sockets.dumb_http_server 

**Expected behavior**
No build errors

**Impact**

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/runs/32781331757
```
FAILED: zephyr/drivers/ethernet/CMakeFiles/drivers__ethernet.dir/eth_stm32_hal.c.obj 
ccache /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DHSE_VALUE=8000000 -DKERNEL -DK_HEAP_MEM_POOL_SIZE=1024 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DSTM32F207xx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/subsys/net/l2 -I/__w/zephyr/zephyr/twister-out/nucleo_f207zg_stm32f207xx/samples/net/sockets/dumb_http_server/sample.net.sockets.dumb_http_server/zephyr/include/generated/zephyr -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/nucleo_f207zg_stm32f207xx/samples/net/sockets/dumb_http_server/sample.net.sockets.dumb_http_server/zephyr/include/generated -I/__w/zephyr/zephyr/soc/st/stm32 -I/__w/zephyr/zephyr/include/zephyr/posix -I/__w/zephyr/zephyr/soc/st/stm32/common/. -I/__w/zephyr/zephyr/drivers -I/__w/zephyr/zephyr/soc/st/stm32/stm32f2x/. -I/__w/zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/__w/zephyr/zephyr/modules/cmsis/. -I/__w/zephyr/modules/hal/stm32/stm32cube/stm32f2xx/soc -I/__w/zephyr/modules/hal/stm32/stm32cube/stm32f2xx/drivers/include -I/__w/zephyr/modules/hal/stm32/stm32cube/common_ll/include -isystem /__w/zephyr/zephyr/lib/libc/common/include -Wshadow -fno-strict-aliasing -Werror -Os -imacros /__w/zephyr/zephyr/twister-out/nucleo_f207zg_stm32f207xx/samples/net/sockets/dumb_http_server/sample.net.sockets.dumb_http_server/zephyr/include/generated/zephyr/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m3 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft --sysroot=/opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/arm-zephyr-eabi -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/samples/net/sockets/dumb_http_server=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -specs=picolibc.specs -D_POSIX_THREADS -std=c99 -MD -MT zephyr/drivers/ethernet/CMakeFiles/drivers__ethernet.dir/eth_stm32_hal.c.obj -MF zephyr/drivers/ethernet/CMakeFiles/drivers__ethernet.dir/eth_stm32_hal.c.obj.d -o zephyr/drivers/ethernet/CMakeFiles/drivers__ethernet.dir/eth_stm32_hal.c.obj -c /__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:102:43: error: 'ETH_RX_DESC_CNT' undeclared here (not in a function); did you mean 'ETH_DMARXDESC_RWT'?
  102 | static ETH_DMADescTypeDef dma_rx_desc_tab[ETH_RX_DESC_CNT] __eth_stm32_desc;
      |                                           ^~~~~~~~~~~~~~~
      |                                           ETH_DMARXDESC_RWT
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:103:43: error: 'ETH_TX_DESC_CNT' undeclared here (not in a function)
  103 | static ETH_DMADescTypeDef dma_tx_desc_tab[ETH_TX_DESC_CNT] __eth_stm32_desc;
      |                                           ^~~~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:1328:43: error: 'HAL_ETH_MII_MODE' undeclared here (not in a function); did you mean 'IS_ETH_RX_MODE'?
 1328 |                                           HAL_ETH_MII_MODE : HAL_ETH_RMII_MODE,
      |                                           ^~~~~~~~~~~~~~~~
      |                                           IS_ETH_RX_MODE
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:1328:62: error: 'HAL_ETH_RMII_MODE' undeclared here (not in a function); did you mean 'IS_ETH_RX_MODE'?
 1328 |                                           HAL_ETH_MII_MODE : HAL_ETH_RMII_MODE,
      |                                                              ^~~~~~~~~~~~~~~~~
      |                                                              IS_ETH_RX_MODE
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:105:16: error: 'dma_tx_buffer' defined but not used [-Werror=unused-variable]
  105 | static uint8_t dma_tx_buffer[ETH_TX_DESC_CNT][ETH_MAX_PACKET_SIZE] __eth_stm32_buf;
      |                ^~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:104:16: error: 'dma_rx_buffer' defined but not used [-Werror=unused-variable]
  104 | static uint8_t dma_rx_buffer[ETH_RX_DESC_CNT][ETH_MAX_PACKET_SIZE] __eth_stm32_buf;
      |                ^~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:103:27: error: 'dma_tx_desc_tab' defined but not used [-Werror=unused-variable]
  103 | static ETH_DMADescTypeDef dma_tx_desc_tab[ETH_TX_DESC_CNT] __eth_stm32_desc;
      |                           ^~~~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/ethernet/eth_stm32_hal.c:102:27: error: 'dma_rx_desc_tab' defined but not used [-Werror=unused-variable]
  102 | static ETH_DMADescTypeDef dma_rx_desc_tab[ETH_RX_DESC_CNT] __eth_stm32_desc;
      |                           ^~~~~~~~~~~~~~~
```

**Environment (please complete the following information):**

 - OS: CI Ubuntu 22.04
 - Toolchain (e.g Zephyr SDK, ...) : 0.17
 - Commit SHA or Version used: main after fbeda5959dd82b58027c07f1ce95a58a9001626e

**Additional context**
Main after https://github.com/zephyrproject-rtos/zephyr/pull/79156 / fbeda5959dd82b58027c07f1ce95a58a9001626e

### PR DESCRIPTION
**Pull request by marwaiehm-st**
The reverted commit causes a compile error with the STM32F2 because
there are some variables used in the file eth_stm32_hal that are
not defined in the HAL module of the STM32F2 series,
such as 'ETH_RX_DESC_CNT' and  'HAL_ETH_MII_MODE'

Fixes #81329

### CODE REVIEW

**Comment by erwango** [comment]
@KozhinovAlexander FYI, reverting https://github.com/zephyrproject-rtos/zephyr/pull/79156 for v4.0 due to a build failure on F2 series. This is partly my bad as well as I built this change on a wide set of platforms but failed to find any issue.
Change will have to be adapted before being re-integrated on v4.1.0.

**Comment by erwango** [comment]
> But instead of reverting the change it may be much more simple just do #ifdef section with defines needed. Reason: such change for F2 would add at most 10 lines of code maybe instead of reverting 37+ lines. But it is just my view.

In usual merge window, this is what we'd do, but in current RC3 context, just reverting is the fastest, less risky and I guess the preferred option for release engineers

**Review by erwango — DISMISSED** [review]

**Comment by KozhinovAlexander** [comment]
> > But instead of reverting the change it may be much more simple just do #ifdef section with defines needed. Reason: such change for F2 would add at most 10 lines of code maybe instead of reverting 37+ lines. But it is just my view.
> 
> In usual merge window, this is what we'd do, but in current RC3 context, just reverting is the fastest, less risky and I guess the preferred option for release engineers

Ok I see. Thank you.

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Comment by KozhinovAlexander** [comment]
@marwaiehm-st it would be very very nice to add twister tests or at least build step for f2/f7/h7 mcu's s.t. Ci fails in the future if similar changes will happen.
To not overload centralized zephyr ci this build steps could be for example done within docker container on some st server or local machine.
@erwango What do you think?

**Comment by erwango** [comment]
> To not overload centralized zephyr ci this build steps could be for example done within docker container on some st server or local machine.
@erwango What do you think?

We have this running already (daily). This is what I tried to run on initial PR. We'll investigate why this F2 issue was missed.

**Comment by mmahadevan108** [comment]
@erwango , thank you. Please feel free to use the `backport-v4.0` label on the fix.

**Pull request merged**
