### PR TITLE
samples:drivers:led_sx1509b_intensity: New k_delayed_work API

### LINKED ISSUE #34098: Convert samples/drivers/led_sx1509b_intensity to new kwork API
Convert samples/drivers/led_sx1509b_intensity/src/main.c to use new kwork API.

See the following issue for details:

#33104

### PR DESCRIPTION
**Pull request by thebatfisk**
Fix #34098 by switching to new k_delayed_work API.

Signed-off-by: Erik Robstad <Erik.Robstad@nordicsemi.no>

### CODE REVIEW

**Review by pabigot — APPROVED** [review]
This precisely patches the [corresponding changes](https://github.com/zephyrproject-rtos/zephyr/pull/33924/commits/d4987a07601f1be9c771b7c97c40a93f573d7355) in #33924 so should be fine.  The sample is trivial enough there are no data races (nothing but the work thread does anything).

**Review by jfischer-no — APPROVED** [review]

**Review by jfischer-no — CHANGES_REQUESTED** [review]
#33390 does the same thing but probably a bit more correctly.

**Comment by pabigot** [comment]
@jfischer-no All three PRs do exactly the same trivial thing, but yes, #33390 has been sitting there for a month waiting for progress---so long I'd forgotten I'd provided it.

The lack of prompt reviews really wastes peoples time.

**Comment by jfischer-no** [comment]
> @jfischer-no All three PRs do exactly the same trivial thing, but yes, #33390 has been sitting there for a month waiting for progress---so long I'd forgotten I'd provided it.
> 
> The lack of prompt reviews really wastes peoples time.

@thebatfisk thanks for this PR but let us close it in favor of #33390. Can you please review/approve #33390?

**Comment by jfischer-no** [comment]
#33390 is merged.

**Pull request closed without merging**
