### PR TITLE
doc: espressif: Add missing images

### PR DESCRIPTION
**Pull request by marekmatej**
Update and add missing Espressif board images.

### CODE REVIEW

**Comment by sylvioalves** [comment]
`esp32_devkitc_*` has .jpg file but I think it is not used in the documentation. Can you update as well?

**Review by kartben — CHANGES_REQUESTED** [review]
Very nice!
Can you please use webp format instead, it will give much smaller files which is important to keep the main git repo size under control. Ideally you even have images with transparent background (which webp supports unlike jpg)
You can use `cwebp -resize 600 0 original_image.ext` to perform the conversion from the original image (either the ok mage files from this PR or, better, from the actual original / high resolution files you started from)

Thanks again!

**Review by nordicjm — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]
great work - thanks!

Note: ESP8684-DevKitM still missing

**Comment by kartben** [comment]
Also, just opened #81126 since it would have been nice for this PR to trigger CI, except it didn't due to only touching image files.

**Review by wmrsouza — DISMISSED** [review]

**Comment by marekmatej** [comment]
> Note: ESP8684-DevKitM still missing

adding esp8684 + rebase

**Comment by kartben** [comment]
> > Note: ESP8684-DevKitM still missing
> 
> adding esp8684 + rebase

yay, a transparent one! :) (which I think the others could be too, btw, since the officials docs since to have transparent hi-res PNGs that could be used as the source? https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32c3/hw-reference/esp32c3/user-guide-devkitc-02.html)

**Comment by marekmatej** [comment]
@kartben do you think this could make it to 4.0 release?

**Review by sylvioalves — APPROVED** [review]

**Review by wmrsouza — APPROVED** [review]

**Comment by kartben** [comment]
> > > > Note: ESP8684-DevKitM still missing
> > > 
> > > 
> > > adding esp8684 + rebase
> > 
> > yay, a transparent one! :) (which I think the others could be too, btw, since the officials docs seem to have transparent hi-res PNGs that could be used as the source? https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32c3/hw-reference/esp32c3/user-guide-devkitc-02.html)
> 
> Do you want me to replace all the images with the transparent bg ones?

Given that we wouldn't want to update them later since this forever clutters the main git repo, it would be great, yes. But I would also understand if you don't have the energy to do it.

**Comment by mmahadevan108** [comment]
@kartben , can you please approve if this looks fine to you.

**Review by kartben — APPROVED** [review]

**Pull request merged**
