### PR TITLE
libc/minimal: provide aligned allocators

### LINKED ISSUE #29519: kernel: provide aligned variants for allocators
**Is your enhancement proposal related to a problem? Please describe.**
While it is not really meaningful to provide allocators for arbitrary alignments (1, 2, 3, .., 42) it should certainly be feasible to adjust the existing allocators so that they are able to select memory blocks to return based on alignment criteria.

I think the generally accepted alignment constraints are that the alignment must be a multiple of the word size (i.e. `sizeof(void *)`). 

**Describe the solution you'd like**
* modify the allocators in question to accept an alignment parameter and rename
* create wrapper versions of the old allocators (which request alignment of `void *`, possibly static inline)
* adjust the primary allocation routines (It seems like it's mainly in `lib/os/mempool.c`)

**Describe alternatives you've considered**

I've only glanced at the allocator in `lib/os/mempool.c`, and it seems like a buddy allocator with some additional features.

If anyone is knowledgeable about the workings of `lib/os/mempool.c`, some input would be greatly appreciated on how to efficiently search through the metadata to find a suitably-aligned block.

The approach I've taken for a similar buddy allocator in the past is to look at each available order-N block, and then move to order-N+1, etc, but I don't know if that would be acceptable performance-wise for Zephyr. 

**Additional context**
This will be used for dynamic thread stacks, including #29029

### PR DESCRIPTION
**Pull request by cfriedt**
This change adds support for standardized aligned allocation APIs via `posix_memalign(3)` and `aligned_alloc(3)` in the minimal libc.

Fixes #29519

### CODE REVIEW

**Comment by maxbachmann** [comment]
> The biggest issue that I can see is that sys_mem_pool does not support aligned allocations, and it is non-obvious to me how to make it support aligned allocations efficientlly. The easiest way to support aligned allocations is to use the k_heap API (which uses sys_heap* under the hood.

In https://github.com/zephyrproject-rtos/zephyr/pull/28611 the sys_mem_pool allocator gets removed

**Comment by andrewboie** [comment]
mis-click sorry

can you set this as a Draft PR since it is still WIP

**Comment by cfriedt** [comment]
> > The biggest issue that I can see is that sys_mem_pool does not support aligned allocations, and it is non-obvious to me how to make it support aligned allocations efficientlly. The easiest way to support aligned allocations is to use the k_heap API (which uses sys_heap* under the hood.
> 
> In https://github.com/zephyrproject-rtos/zephyr/pull/28611 the sys_mem_pool allocator gets removed

Now it all makes sense! Thanks for pointing that out @maxbachmann

**Comment by cfriedt** [comment]
I cherry-picked from #30003 #28611, so please wait until after those are merged before reviewing.

**Comment by cfriedt** [comment]
Leaving this as a draft until #30003 and #28611 are merged.

**Comment by cfriedt** [comment]
Closing this in favour of #30363 for a couple of reasons.
* Newlib does not provide us with `aligned_alloc(3)` or `posix_memalign(3)` so it's pointless to offer in the minimal libc
* @andrewboie said I should just provide a `k_malloc_aligned()` instead and I probably should have just listened to him in the first place :wink: 

In any case, #30363 is really just recycling the `aligned_alloc(3)` implementation and test case from here and applying them to `k_malloc()` instead, so I didn't _really_ waste time / code... right? :man_shrugging:

**Comment by pfalcon** [comment]
> Newlib does not provide us with aligned_alloc(3) or posix_memalign(3) so it's pointless to offer in the minimal libc

I don't agree with the "pointless" valuation: POSIX provides them, that's pretty good a reason on its own.

That said, you're designer of this feature.

**Comment by cfriedt** [comment]
> > Newlib does not provide us with aligned_alloc(3) or posix_memalign(3) so it's pointless to offer in the minimal libc
> 
> I don't agree with the "pointless" valuation: POSIX provides them, that's pretty good a reason on its own.

Sorry, - it's definitely not "pointless". You're right. For my current purposes though (#29029) I can't use `posix_memalign()` unfortunately though, because it's not both in newlib and in the minimal libc.

I'll keep the branch around just in case we want to add this in the future. Personally, I think supporting standards are important.

**Comment by pfalcon** [comment]
> I unfortunately can't use posix_memalign() because it's not both in newlib and in the minimal libc.

That at least should lead to traces of ideas for some kind of "polyfills" (curse JavaScript for abusing thru the entire industry), where we can add functionality for both newlib and minlibs. Actually, we do things like that already - newlib doesn't ship e.g. select() implementation, we do.

(That's not call for action, just call for thinking and maybe planning ahead.)

**Pull request closed without merging**
