### PR TITLE
driver: interrupt_controller: Filter invalid channel for RV32M1 SOC

### PR DESCRIPTION
**Pull request by lylezhu2014**
Invalid channel should be filtered in intmux isr

Signed-off-by: Lyle Zhu <lyle.zhu@nxp.com>

### CODE REVIEW

**Comment by MaureenHelm** [comment]
How did you find this? What caused the invalid channel?

**Comment by lylezhu2014** [comment]
> How did you find this? What caused the invalid channel?

I am trying to enable the Vega ble demo via LPUART1 on ri5cy. The IRQ line of the LPUART1 is routed to the INTMUX on ri5cy core. Sometimes, the channel vector number is zero in the INTMUX ISR, and cause the systom fault.
And, refer to the INTMUX driver of the MCUXpresso SDK, the value zero of channel vector number should be filtered.

**Comment by MaureenHelm** [comment]
> > How did you find this? What caused the invalid channel?
> 
> I am trying to enable the Vega ble demo via LPUART1 on ri5cy. The IRQ line of the LPUART1 is routed to the INTMUX on ri5cy core. Sometimes, the channel vector number is zero in the INTMUX ISR, and cause the systom fault.
> And, refer to the INTMUX driver of the MCUXpresso SDK, the value zero of channel vector number should be filtered.

But why was the ISR invoked with channel number zero? It seems like this change is masking a different problem.

**Comment by lylezhu2014** [comment]
> > > How did you find this? What caused the invalid channel?
> > 
> > 
> > I am trying to enable the Vega ble demo via LPUART1 on ri5cy. The IRQ line of the LPUART1 is routed to the INTMUX on ri5cy core. Sometimes, the channel vector number is zero in the INTMUX ISR, and cause the systom fault.
> > And, refer to the INTMUX driver of the MCUXpresso SDK, the value zero of channel vector number should be filtered.
> 
> But why was the ISR invoked with channel number zero? It seems like this change is masking a different problem.



> > > How did you find this? What caused the invalid channel?
> > 
> > 
> > I am trying to enable the Vega ble demo via LPUART1 on ri5cy. The IRQ line of the LPUART1 is routed to the INTMUX on ri5cy core. Sometimes, the channel vector number is zero in the INTMUX ISR, and cause the systom fault.
> > And, refer to the INTMUX driver of the MCUXpresso SDK, the value zero of channel vector number should be filtered.
> 
> But why was the ISR invoked with channel number zero? It seems like this change is masking a different problem.



> > > How did you find this? What caused the invalid channel?
> > 
> > 
> > I am trying to enable the Vega ble demo via LPUART1 on ri5cy. The IRQ line of the LPUART1 is routed to the INTMUX on ri5cy core. Sometimes, the channel vector number is zero in the INTMUX ISR, and cause the systom fault.
> > And, refer to the INTMUX driver of the MCUXpresso SDK, the value zero of channel vector number should be filtered.
> 
> But why was the ISR invoked with channel number zero? It seems like this change is masking a different problem.

Please refer page 1243~1244 of Chapter 36 INTMUX of Vega RM.
`Unlike the NVIC, the INTMUX does not latch pending source
interrupts. This means that the INTMUX output channel ISRs
must check for and handle a 0 value of the CHn_VEC register
to account for spurious interrupts.`

For my changes, I added a more rigorous judgment. The vector number should be not less than VECN_OFFSET.

**Comment by MaureenHelm** [comment]
> Please refer page 1243~1244 of Chapter 36 INTMUX of Vega RM.
> `Unlike the NVIC, the INTMUX does not latch pending source interrupts. This means that the INTMUX output channel ISRs must check for and handle a 0 value of the CHn_VEC register to account for spurious interrupts.`

Ok. Will you please update the commit message to mention this?

**Comment by dleach02** [comment]
@lylezhu2014 will you be making the requested change to your commit message?

**Review by dleach02 — APPROVED** [review]
pending the change requested to the commit message to more accurately reflect the reason for the change.

**Review by dleach02 — CHANGES_REQUESTED** [review]
Please resolve the conflicts and update the commit message per the request.

**Comment by lylezhu2014** [comment]
Yes, I will fix the conflict and update the commit message.

**Comment by lylezhu2014** [comment]
> Please resolve the conflicts and update the commit message per the request.

My PR has the issue "-:3: ERROR:EXECUTE_PERMISSIONS: do not set execute permissions for source files
#3: FILE: drivers/interrupt_controller/intc_rv32m1_intmux.c"

Could you help me on this?

**Comment by MaureenHelm** [comment]
> My PR has the issue "-:3: ERROR:EXECUTE_PERMISSIONS: do not set execute permissions for source files
> #3: FILE: drivers/interrupt_controller/intc_rv32m1_intmux.c"
> 
> Could you help me on this?

I rebased and updated the file permissions.

**Comment by lylezhu2014** [comment]
> > My PR has the issue "-:3: ERROR:EXECUTE_PERMISSIONS: do not set execute permissions for source files
> > #3: FILE: drivers/interrupt_controller/intc_rv32m1_intmux.c"
> > Could you help me on this?
> 
> I rebased and updated the file permissions.

I saw. Thank you!

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
