### PR TITLE
doc: Hide internal driver API from public documentation.

### PR DESCRIPTION
**Pull request by kartben**

### CODE REVIEW

**Comment by kartben** [comment]
@nashif  before I put it out of draft mode, does this make sense to you?

**Comment by nashif** [comment]
hmm, do not think those should be marked internal, this is the interface each driver needs to implement. Those APIs shall not be called by the application but can be implemented out of tree. Need more eyes and feedback on this.

**Comment by kartben** [comment]
> hmm, do not think those should be marked internal, this is the interface each driver needs to implement. Those APIs shall not be called by the application but can be implemented out of tree. Need more eyes and feedback on this.

Mmm ok, thanks for the feedback --  I don't have a strong opinion but for what it's worth a majority of the drivers in-tree implement the pattern I've followed with this PR (this PR updates about ~20 driver APIs and I can count over 70 definition of `*_struct_api`s), so either way something needs to be done to make things consistent.

**Comment by kartben** [comment]
Would be curious to hear @gmarull's thoughts

**Comment by gmarull** [comment]
> Would be curious to hear @gmarull's thoughts

We've typically hidden internal API stuff (including driver-specific APIs). I think it's not a great solution because that information is still useful for driver developers. But I guess it will take time to fix.

I'd personally look into doing something around these lines:

1. Split headers into:
    a) consumer/client API
    b) driver-specific APIs (e.g. driver ops)
    c) optionally, additional internal/private headers where needed

Reasons: consumers are the most common users of an API, so having short and clean headers without tons of internal details helps. Driver developers also have a clear scope for their work. Note that the scope of all such headers would remain public because we rely on inlining.

2. (a) APIs are what we currently document and expose. (b) APIs should also be documented somewhere, because not all APIs have a 1:1 mapping between consumer API calls and driver ops (see for example regulators). 

3. Differentiate between (a), (b) and (c) in terms of stability. (a) should be the target for the stability criteria, (c) definitely not. I'd not offer any guarantees for (b) either because it makes internal API refactors more painful, disincentivizes upstreaming, and because being a consumer or a driver is just a different story.

**Pull request closed without merging**
