### PR TITLE
scripts: west: reference correct library name

### LINKED ISSUE #48626: jlink flasher not working with recent versions of pylink dependency
**Describe the bug**
 <snip>
  File ".../zephyr/scripts/west_commands/runners/jlink.py", line 162, in jlink_version
    lib = Library(dllpath=os.fspath(Path(self.commander).parent /
  File ".../.venv/lib/python3.8/site-packages/pylink/library.py", line 278, in __init__
    self.load(dllpath)
  File ".../.venv/lib/python3.8/site-packages/pylink/library.py", line 384, in load
    with open(self._path, 'rb') as inputfile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/SEGGER/JLink_V768b/jlinkarm.so'

**To Reproduce**
1. install latest python requirements in venv
2. west flash --runner=jlink -d some-binary-dir
3. see error

**Expected behavior**
Constructing the correct library name .../libjlinkarm.so

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: up-to-date JLink (v768b)
 - Commit SHA: 0200da97c2

PR with potential fix follows.

### PR DESCRIPTION
**Pull request by ghost**
Fixes: #48626

The correct libname is available in another variable than what the
script used before.

Signed-off-by: Florian Grandel <jerico.dev@gmail.com>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
This definitely used to work on Linux, so what changed? Is there a specific version at which the Library API changed? We should support both versions if so IMO.

**Comment by fgrandel** [comment]
> This definitely used to work on Linux, so what changed? Is there a specific version at which the Library API changed? We should support both versions if so IMO.

Not sure about the library version... Mine is:

```
> pip list | grep pylink
pylink-square                  0.14.1

```
Anything I can do to help you reproduce this?

**Comment by fgrandel** [comment]
I don't have time right now to provide a full fix but should be rather trivial to fix this based on the info provided...

**Comment by mbolivar-nordic** [comment]
> I don't have time right now to provide a full fix

OK, I'm going to close this PR but leave the issue open, then. Thanks for the report and investigation.

**Comment by gmarull** [comment]
FYI https://github.com/zephyrproject-rtos/zephyr/pull/48680

**Pull request closed without merging**
