### PR TITLE
ci: do not check for newlines

### LINKED ISSUE #27003: CMakeLists.txt newline check is too strict
**Describe the bug**
```
Please remove blank lines at end of 'arch/x86/CMakeLists.txt'
##[error]See https://docs.zephyrproject.org/latest/contribute/#coding-style for more details.
```

The problem is, the file looks like this:

```
    --kernel $<TARGET_FILE:${ZEPHYR_PREBUILT_EXECUTABLE}>
    --output pagetables.bin
    $<$<BOOL:${CMAKE_VERBOSE_MAKEFILE}>:--verbose>
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    DEPENDS ${ZEPHYR_PREBUILT_EXECUTABLE} ${GEN_MMU}
  )

  add_bin_file_to_the_next_link(pagetables_bin_target pagetables)
endif()
```

The endif() on the last line has a newline on the end of it. Only one.

I can understand forbidding multiple blank lines at the end, but forbidding the last line of build system code to have a newline on it is ridiculous.

### PR DESCRIPTION
**Pull request by nashif**
Remove nit check for newline in source files.

Fixes #27003

### CODE REVIEW

**Comment by pabigot** [comment]
AFAICT this check is correct, replicating one in `.git/hooks/pre-commit` for people who don't enable that check.  It's considered a whitespace error that can cause problems when the local environment end-of-line sequence does not match the repository configuration.

**Comment by nashif** [comment]
> AFAICT this check is correct, replicating one in `.git/hooks/pre-commit` for people who don't enable that check.

which one does it replicate?

**Comment by pabigot** [comment]
`git diff-index --check` which checks for whitespace; search for `core.whitespace` on https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration.  `blank-at-eof` is one of the three that are enabled by default.

**Comment by carlescufi** [comment]
I actually don't dislike that check, and as @pabigot says, it's a standard one. I won't block this if it annoys most people, but I'd rather leave it in.

**Comment by nashif** [comment]
is this part of the Linux kernel coding style which we are based on? Shouldn't this be covered by checkpatch already? The git configuration options above are not relevant IMO. 

checkpatch has some check which is now a warning. 

bottom line is that it is not clear where these guidelines are coming from and it is confusing and not something we ever had before they were added in the Nits thing.

**Comment by andrewboie** [comment]
This check requires that the last line of code in a file *not* end in a newline. I ran into this not long ago when I changed a CMakeLists.txt.

I can understand not wanting multiple newlines at the end of a file, but insisting on zero newlines at the end of a file is incomprehensible to me.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
let's close this, I can't seem to reproduce the reported issue where it flags a single trailing `\n`.

**Pull request closed without merging**
