### PR TITLE
cmake: Fixed NODE_ADDR

### PR DESCRIPTION
**Pull request by SebastianBoe**
Signed-off-by: Sebastian Boe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
BTW, was it considered to use a Kconfig variable for NODE_ADDR? Looks like the perfect fit from my desk.

**Comment by jhedberg** [comment]
> BTW, was it considered to use a Kconfig variable for NODE_ADDR? Looks like the perfect fit from my desk.

NODE_ADDR is completely specific to the mesh_demo app. Any other mesh-using app would use the mesh provisioning protocol to get its address, so I don't think this belongs in Kconfig.

**Review by jhedberg — APPROVED** [review]
Looks good to me

**Comment by SebastianBoe** [comment]
> NODE_ADDR is completely specific to the mesh_demo app. Any other mesh-using app would use the mesh provisioning protocol to get its address, so I don't think this belongs in Kconfig.

Right, sorry for presuming you didn't know what you were doing.

Perhaps in the future app's could have an optional Kconfig file to cover this use-case.
Using KCONFIG_ROOT for just one option is a bit overkill.

**Pull request merged**
