### PR TITLE
Interrupt controller DT macros and GPIO IRQ utilities

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
### Introduction
Implement interrupt-controller related macros to get the handle to an interrupt specifier's interrupt controller as described in [Devicetree specification v0.4](https://github.com/devicetree-org/devicetree-specification/releases/tag/v0.4) section 2.4.1, and add the utilities and macros required to use the devicetree specification.

### What will it solve
The following example shows how we currently configure GPIO routed interrupts in-tree for the ST LIS2DH, which generates two pin routed interrupts:
```
#include <zephyr/dt-bindings/gpio/gpio.h>
#include <zephyr/dt-bindings/sensor/lis2dh.h>

&i2c0 {
	sensor: lis2dh {
		compatible = "st,lis2dh";
		irq-gpios = <&gpio0 1 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>,
		            <&gpio0 2 GPIO_ACTIVE_HIGH>;
		int1-gpio-config = LIS2DH_DT_GPIO_INT_EDGE_RISING;
		int2-gpio-config = LIS2DH_DT_GPIO_INT_EDGE_RISING;
	};
};
```
This solution is not optimal, as it is not generic, and does not follow the devicetree specification 2.4.1. This results in custom bindings required to configure the interrupt lines, and makes it near impossible to create subsystems and other utilities which interact with interrupt generating devices generically (like a wakeup source subsystem, or generic utilities for interacting with interrupt requests)

### What does the solution look like
Using the properties for interrupt generating devices defined in the devicetree specification, the same sensor will take one of the following forms:
```
#include <zephyr/dt-bindings/gpio/gpio.h>
#include <zephyr/dt-bindings/interrupt-controller/irq.h>

&i2c0 {
	sensor: lis2dh {
		compatible = "st,lis2dh";
		interrupt-parent = <&gpio0>,
		interrupts = <1 (IRQ_TYPE_EDGE_RISING | GPIO_PULL_UP)>,
		             <2 IRQ_TYPE_EDGE_RISING>;
	};
};
```
or
```
#include <zephyr/dt-bindings/gpio/gpio.h>
#include <zephyr/dt-bindings/interrupt-controller/irq.h>

&i2c0 {
	sensor: lis2dh {
		compatible = "st,lis2dh";
		interrupts-extended = <&gpio0 1 (IRQ_TYPE_EDGE_RISING | GPIO_PULL_UP)>,
		                      <&gpio0 2 IRQ_TYPE_EDGE_RISING>;
	};
};
```
This is compatible with the Linux binding for the same sensor [st-sensors.yaml](https://www.kernel.org/doc/Documentation/devicetree/bindings/iio/st%2Cst-sensors.yaml)

Note: this also allows us to exchange the GPIO controller for a programmable interrupt controller potentially in the future like:
```
	&i2c0 {
		sensor: lis2dh {
			compatible = "st,lis2dh";
			interrupt-parent = <&pic0>,
			interrupts = <1 (IRQ_TYPE_EDGE_RISING | GPIO_PULL_UP)>,
			             <2 IRQ_TYPE_EDGE_RISING>;
		};
	};
```

### How will drivers use the new macros
Drivers will get a GPIO IRQ specification from the devicetree using a variation of `GPIO_IRQ_DT_SPEC_GET()` which initializes a `struct gpio_irq_dt_spec`, similar to how `GPIO_DT_SPEC_GET()` works.

```
struct foo_config {
	struct gpio_irq_dt_spec irq_spec;
};

const struct foo_config##inst = {
	.irq_spec = GPIO_IRQ_DT_SPEC_GET(inst),
};
```

Drivers will then utilize the `gpio_irq` utilities to configure a GPIO PIN as an interrupt as described by the spec.
```
struct foo_data {
	struct gpio_irq irq;
};

void foo_irq_handler(struct gpio_irq *irq)
{
	struct foo_data *data = CONTAINER_OF(irq, struct foo_data, irq);
	...
}

void foo_init(const struct device *dev)
{
	const struct foo_config *config = dev->config;
	struct foo_data *data = dev->data;

	/* Configure interrupt generating device to follow irq spec from devicetree */
	if (config->irq_spec.flags & IRQ_TYPE_EDGE_RISING) {
		...
	} else if (config->irq_spec.flags & IRQ_TYPE_EDGE_FALLING)
		...
	}

	/* Set pin interrupt and enable it according to irq spec from devicetree */
	gpio_irq_request_dt(&config->irq_spec, &data->irq, foo_irq_handler);
}
```

The `struct gpio_irq` instance is used to further interact with the GPIO pin interrupt
```
int foo_resume(const struct device *dev)
{
	struct foo_data *data = dev->data;

	return gpio_irq_enable(&data->irq);
}

int foo_suspend(const struct device *dev)
{
	struct foo_data *data = dev->data;

	return gpio_irq_disable(&data->irq);
}
```

#### What happens to `GPIO_ACTIVE_LOW` and `GPIO_INT_LEVELS_LOGICAL`
These flags are no longer useful as the `IRQ_TYPE_*` flags completely cover the information the GPIO flags where conveying. 
#### Can we still use generic and vendor specific `GPIO_*` flags like `GPIO_PULL_UP`?
Yes! except for the first 4 flags which configure GPIO output and logical states, which are now illegal, and are replaced by the 
new `IRQ_TYPE_*` flags.
#### Could we not just reuse `struct gpio_dt_spec`?
Technically yes, the layout of the structure is identical, but, this would be unsafe as it would indicate that the `struct gpio_irq_dt_spec` and `struct gpio_dt_spec` are interchangeable, which they are not. For `struct gpio_irq_dt_spec`, we enforce that the `controller`(`port`) is in fact also an interrupt controller, and we enforce that the `irq`(`pin`) is in fact from an interrupts property.

### CODE REVIEW

**Review by mbolivar-ampere — CHANGES_REQUESTED** [review]
Looks like a great idea. I found some issues with the implementation.

**Comment by bjarki-trackunit** [comment]
@mbolivar-ampere Thank you for reviewing, I'm currently writing the test suite :) just wanted to share the design a bit early :)

**Comment by mbolivar-ampere** [comment]
> just wanted to share the design a bit early :)

OK! Please consider using a draft PR in the future for work that is not ready. This looked like you wanted it in, especially since you asked for a review on Discord.

**Comment by bjarki-trackunit** [comment]
Added documentation for GPIO interrupt requests with examples and API overview

**Comment by bjarki-trackunit** [comment]
### Update
* Changed `_OPTIONAL_` to `_OPT_` to shorten macro names
* Fixed erroneous `IRQ_TYPE_*` usage in documentation and 
* Made functions in doc example driver static
* Added comment to doc example driver to configure sensor interrupt lines before enabling interrupt requests

**Comment by bjarki-trackunit** [comment]
### Update
* Added helper macros to validate and test `IRQ_TYPE_*` flags
* Implemented new helpers in GPIO IRQ utilities
* Added error handling if `gpio_irq_enable()` fails when requesting GPIO IRQ using `gpio_irq_request()`

**Comment by carlescufi** [comment]
Architecture WG:

- @henrikbrixandersen is worried that the current suggestion will still require clients using GPIO-based interrupts to handle it in the code with the GPIO API, instead of using the interrupt API. He mentions external interrupt controllers that have external pins available
- @henrikbrixandersen asks for an interrupt controller API and then map this to the existing GPIO controller API

**Comment by bjarki-trackunit** [comment]
Closing this PR for now since it will probably be reworked based on the a new interrupt controller API (this one once its ready hopefully #66505)

**Pull request closed without merging**
