### PR TITLE
soc: intel_adsp: update toolchain usage

### PR DESCRIPTION
**Pull request by dcpleung**
* Upates the manifest SHA to use the latest Xtensa HAL commit which is to support building intel_adsp_ace15_mtpm using Zephyr SDK.
* Update toolchain usage for both intel_adsp_cavs25 and ACE series.

Requires https://github.com/zephyrproject-rtos/sdk-ng/pull/651 and https://github.com/zephyrproject-rtos/sdk-ng/pull/664

### CODE REVIEW

**Comment by dcpleung** [comment]
Need this to work correctly: https://github.com/zephyrproject-rtos/sdk-ng/pull/651

**Comment by galak** [comment]
should be able to update this now

**Review by nashif — DISMISSED** [review]

**Review by stephanosio — COMMENTED** [review]
This will also need to update the minimum required Zephyr SDK version to 0.16.1.

**Comment by dcpleung** [comment]
@stephanosio This is because commit https://github.com/zephyrproject-rtos/hal_xtensa/commit/e636ce8fdf334addaae37fb2417dc2cb8bf7b50a on Xtensa HAL has been reverted for some other changes. Will need to reintroduce this for the SDK to work.

**Comment by dcpleung** [comment]
@stephanosio I have rebased and update `west.yml` to point to the PR in Xtensa HAL. If you fetch the new version, it should build correctly.

**Review by stephanosio — COMMENTED** [review]
This will be merged as part of https://github.com/zephyrproject-rtos/zephyr/pull/57840, which updates the CI to use the Zephyr SDK 0.16.1.

**Review by stephanosio — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Comment by dcpleung** [comment]
Use #57840 instead. Closing this...

**Pull request closed without merging**
