### PR TITLE
boards: arm: nordic: Add BG96 to RAK5010 board

### PR DESCRIPTION
**Pull request by gpaquet85**
Add BG96 in board description
Add W Disable Pin in BG96 descriptor

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by gpaquet85** [comment]
Hello @galak thanks for your review and approval. I'd like to fix failing checks but I don't really understand what to do to fix this. Can you please help me on this case ? Thanks for your support

**Comment by mbolivar-nordic** [comment]
> I'd like to fix failing checks but I don't really understand what to do to fix this.

Start by rebasing your PR, then see if any of the remaining errors are legitimate issues that need fixing.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by galak** [comment]
I suggest doing the following locally and make sure you get this to pass:

```
./scripts/twister -p rak5010_nrf52840
```

Doing a quick glance at the failures, you probably need to move how you are setting CONFIG_MODEM_QUECTEL_BG9X

Take a look at how its done here:

boards/arm/pinnacle_100_dvk/Kconfig.defconfig
boards/arm/particle_boron/Kconfig.defconfig

**Comment by gpaquet85** [comment]
> I suggest doing the following locally and make sure you get this to pass:
> 
> ```
> ./scripts/twister -p rak5010_nrf52840
> ```
> 
> Doing a quick glance at the failures, you probably need to move how you are setting CONFIG_MODEM_QUECTEL_BG9X
> 
> Take a look at how its done here:
> 
> boards/arm/pinnacle_100_dvk/Kconfig.defconfig
> boards/arm/particle_boron/Kconfig.defconfig

Hello @galak thanks a lot. I will do what you suggest. I think you're right

**Comment by gpaquet85** [comment]
Hi @galak @mbolivar  I think everything is cleaned from now. Let me know if any

**Comment by mbolivar-nordic** [comment]
Looks good! Your PR will have to wait to be merged until after the 2.5 release, since we're in the stabilization period now.

**Comment by gpaquet85** [comment]
> Looks good! Your PR will have to wait to be merged until after the 2.5 release, since we're in the stabilization period now.

ok thanks for your feedback ;)

**Pull request merged**
