### PR TITLE
doc: improve visibility of doc version menu

### PR DESCRIPTION
**Pull request by dbkinder**
Move the doc version selection menu from the bottom of the left nav menu
to above the TOC menu, making it more obvious.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
Here's what the doc version menu looks like with this PR (the doc version selection is above the nav menu instead of at the bottom corner of the nav menu)

image

**Review by jukkar — APPROVED** [review]
Looks much better this way, +1 from me.

**Comment by dbkinder** [comment]
@nashif ping

**Review by aescolar — APPROVED** [review]
Just wondering if it would make sense to increase slightly the font of the version displayed under the logo to make it a bit more obvious.

**Comment by dbkinder** [comment]
@nashif @galak can we get this merged for the 1.14 release, per TSC request.

**Pull request merged**
