### PR TITLE
drivers: pwm_nrfx: Wait until PWM is stopped

### PR DESCRIPTION
**Pull request by MarekPieta**
Change adds waiting until PWM is stopped. Without the change, calling the pwm_nrfx_pin_set function multiple times in quick succession could cause a race condition. One call stops PWM and the next call may fail to notice that the PWM is stopped.

### CODE REVIEW

**Review by anangl — APPROVED** [review]

**Comment by ioannisg** [comment]
This looks like a bug @anangl , isn't it?

**Comment by anangl** [comment]
> This looks like a bug @anangl , isn't it?

This makes the driver more robust, actually. But since in quite specific circumstances (`pwm_nrfx_pin_set()` would need to be called again in a time shorter than the PWM period) the PWM signal might not be started, such behavior can be classified as a bug.

**Comment by ioannisg** [comment]
> > This looks like a bug @anangl , isn't it?
> 
> This makes the driver more robust, actually. But since in quite specific circumstances (`pwm_nrfx_pin_set()` would need to be called again in a time shorter than the PWM period) the PWM signal might not be started, such behavior can be classified as a bug.

@anangl just asking: what is the cost of the busy wait here? Any negative impacts?

**Comment by anangl** [comment]
> @anangl just asking: what is the cost of the busy wait here? Any negative impacts?

It depends on the used duration of the PWM period and on the moment in this period at which the driver is requested to stop the PWM. The driver will busy wait until the end of the current period. Then the PWM peripheral in fact finishes generation of the signal and stops.
Perhaps it could be improved by doing this waiting instead when the PWM is to be started again and if at that point the PWM peripheral hasn't completed the recent stopping yet. Then this waiting would be performed only when it is indeed necessary. @MarekPieta have you tried to handle it this way?

**Comment by MarekPieta** [comment]
@anangl, I made requested change. Please re-review.

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
