### PR TITLE
doc: extensions: Show Kconfig options in search

### PR DESCRIPTION
**Pull request by kartben**
Show Kconfig options in search results, since that's how some people would expect to be able to find more details about
them.

@gmarull please let me know if there was a good reason for you to have excluded them (-1) back when you worked on this. Thanks!

### CODE REVIEW

**Review by gmarull — COMMENTED** [review]
at the time I disabled this was to reduce the search index size, should be checked just in case.

**Comment by kartben** [comment]
right, that's a great point! It looks like it brings a ~700K increase  (from 8.2M(!) originally.
FWIW I just enabled compression on our CloudFront instance, which should significantly help (with this, and more). The 8.2M index goes down to 1.53MB when gzipped and ~1M when brotli'd.

**Comment by gmarull** [comment]
> right, that's a great point! It looks like it brings a ~700K increase (from 8.2M(!) originally. FWIW I just enabled compression on our CloudFront instance, which should significantly help (with this, but not only, hopefully!). The 8.2M index goes down to 1.53MB when gzipped and ~1M when brotli'd.

ok, great, so not a big deal

**Review by gmarull — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by kartben** [comment]
working on a follow-up commit to address compliance check - will remove the unused imports, as it seems pylint is complaining about a deprecated module that's not used anyway.

**Review by gmarull — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
