### PR TITLE
Assorted userspace cleanups

### LINKED ISSUE #15304: merge gen_kobject_list.py and gen_priv_stacks.py
Generation of privilege mode stack buffers can take place in the main gen_kobject_list.py script, there's no actual need for them to be separate. Any data/bss for objects declared in the gperf C file already goes in an area of memory which can expand without limit.

We just need the main gperf table; for any thread's kobject, the data field will point to a struct containing the thread ID and a pointer to its stack buffer.

Should help with build times as we only need to scan the DWARF data once instead of twice.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
* Poorly named structs `_k_object`, `_k_thread_stack_element`, `_k_object_assignment` renamed to use z_ prefix, all are kernel-private
* The data member of `struct z_object` is now a union making the semantics much clearer
* Generation of privilege mode stacks is no longer a separate pass, logic merged into gen_kobject_list.py. this should speed up build times on ARM platforms.
* elf_helper.py merged back into gen_kobject_list.py

Fixes: #15304

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by andrewboie** [comment]
This seems to have broken `make clean; make`, investigating...

```
Traceback (most recent call last):
  File "/home/apboie/projects/zephyr2/zephyr/scripts/subfolder_list.py", line 80, in <module>
    main()
  File "/home/apboie/projects/zephyr2/zephyr/scripts/subfolder_list.py", line 44, in main
    os.symlink(directory, symlink)
FileExistsError: [Errno 17] File exists: '/home/apboie/projects/zephyr2/zephyr/include' -> '/home/apboie/projects/zephyr2/zephyr/tests/kernel/mem_protect/userspace/out/zephyr/misc/generated/syscalls_links/_home_apboie_projects_zephyr2_zephyr_include'
Traceback (most recent call last):
  File "/home/apboie/projects/zephyr2/zephyr/scripts/subfolder_list.py", line 80, in <module>
    main()
  File "/home/apboie/projects/zephyr2/zephyr/scripts/subfolder_list.py", line 44, in main
    os.symlink(directory, symlink)
FileExistsError: [Errno 17] File exists: '/home/apboie/projects/zephyr2/zephyr/include' -> '/home/apboie/projects/zephyr2/zephyr/tests/kernel/mem_protect/userspace/out/zephyr/misc/generated/syscalls_links/_home_apboie_projects_zephyr2_zephyr_include'
zephyr/CMakeFiles/kobj_types_h_target.dir/build.make:168: recipe for target 'zephyr/misc/generated/syscalls_subdirs.trigger' failed
make[2]: *** [zephyr/misc/generated/syscalls_subdirs.trigger] Error 1
make[2]: *** Deleting file 'zephyr/misc/generated/syscalls_subdirs.trigger'
CMakeFiles/Makefile2:733: recipe for target 'zephyr/CMakeFiles/kobj_types_h_target.dir/all' failed
make[1]: *** [zephyr/CMakeFiles/kobj_types_h_target.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
zephyr/CMakeFiles/driver_validation_h_target.dir/build.make:164: recipe for target 'zephyr/misc/generated/syscalls_subdirs.trigger' failed
make[2]: *** [zephyr/misc/generated/syscalls_subdirs.trigger] Error 1
CMakeFiles/Makefile2:765: recipe for target 'zephyr/CMakeFiles/driver_validation_h_target.dir/all' failed
make[1]: *** [zephyr/CMakeFiles/driver_validation_h_target.dir/all] Error 2
[  5%] Built target syscall_list_h_target
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by andrewboie** [comment]
@SebastianBoe I'm not sure what part of my CMakeLists.txt changes broke this, but I think there is an underlying bug -- even in a vanilla Zephyr tree, when I run "make clean" there's still tons of generated stuff left in build/zephyr/include/generated

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
Dependencies need to be fixed.

**Comment by andrewboie** [comment]
> 
> 
> I was not able to reproduce the issue of make clean not working.
> 
> But I see that this happens:
> 
> ```
> [  1%] Preparing syscall dependency handling
> [  1%] Preparing syscall dependency handling
> [  2%] Preparing syscall dependency handling
> 
> 
> 
> [  3%] Generating misc/generated/syscalls_subdirs.trigger
> [  4%] Generating misc/generated/syscalls_subdirs.trigger
> [  5%] Generating misc/generated/syscalls_subdirs.trigger
> [  6%] Generating misc/generated/syscalls.json, misc/generated/subsystems.json
> [  7%] Generating misc/generated/syscalls.json, misc/generated/subsystems.json
> [  7%] Generating misc/generated/syscalls.json, misc/generated/subsystems.json
> ```
> 
> Which usually means that commands are depending on a file, instead of a target that wraps the file.
> 
> "You can’t just depend on gen1 instead of gen1-wrapper, because it may end up being built multiple times!"
> 
> [samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands](https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/)

@SebastianBoe I can reproduce this *without* this PR.

For example, in master branch, I built, 'make clean', and 'make' again:

```
apboie@apboie-mobl4:~/projects/zephyr3/zephyr/tests/kernel/mem_protect/userspace/out master /home/apboie/projects/zephyr3/zephyr
$ mj
[  0%] Preparing syscall dependency handling
[  1%] Preparing syscall dependency handling
[  1%] Preparing syscall dependency handling



[  2%] Generating misc/generated/syscalls_subdirs.trigger
[  3%] Generating misc/generated/syscalls_subdirs.trigger
[  4%] Generating misc/generated/syscalls_subdirs.trigger
[  4%] Generating misc/generated/syscalls.json, misc/generated/subsystems.json
[  5%] Generating misc/generated/syscalls.json, misc/generated/subsystems.json
Traceback (most recent call last):
  File "/home/apboie/projects/zephyr3/zephyr/scripts/subfolder_list.py", line 80, in <module>
    main()
  File "/home/apboie/projects/zephyr3/zephyr/scripts/subfolder_list.py", line 56, in main
    os.symlink(directory, symlink)
FileExistsError: [Errno 17] File exists: '/home/apboie/projects/zephyr3/zephyr/include/dt-bindings/interrupt-controller' -> '/home/apboie/projects/zephyr3/zephyr/tests/kernel/mem_protect/userspace/out/zephyr/misc/generated/syscalls_links/_home_apboie_projects_zephyr3_zephyr_include_dt-bindings_interrupt-controller'
[  5%] Generating include/generated/driver-validation.h
[  6%] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h
zephyr/CMakeFiles/syscall_list_h_target.dir/build.make:166: recipe for target 'zephyr/misc/generated/syscalls_subdirs.trigger' failed
make[2]: *** [zephyr/misc/generated/syscalls_subdirs.trigger] Error 1
make[2]: *** Deleting file 'zephyr/misc/generated/syscalls_subdirs.trigger'
CMakeFiles/Makefile2:797: recipe for target 'zephyr/CMakeFiles/syscall_list_h_target.dir/all' failed
make[1]: *** [zephyr/CMakeFiles/syscall_list_h_target.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Built target driver_validation_h_target
[  6%] Built target kobj_types_h_target
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I think it is a race condition on whether the failure occurs, which is why I don't always see it.

Please reconsider your -1 as this issue is not related to this PR.

**Comment by andrewboie** [comment]
I opened https://github.com/zephyrproject-rtos/zephyr/issues/23504 as the problems seen are unrelated to this PR.

**Comment by andrewboie** [comment]
@SebastianBoe I've root-caused these problems to #23183 it's not this patch.

**Review by SebastianBoe — APPROVED** [review]
Removing NACK

**Pull request merged**
