### PR TITLE
Bluetooth: Allow disconnected state connections to be reconnected

### PR DESCRIPTION
**Pull request by jhedberg**
Make it possible to initiate new connections from within the
disconnect callback. This wasn't completely trivial since there was
connection cleanup done through deferred action using the CONN_CLEANUP
flag.
    
This patch moves the disconnected callbacks to be run after all
cleanup is done. We can't directly do this in the TX thread, since
that's internal, so we instead take advantage of the deferred work
support and do it using the update_work callback. Since the same
cleanup is needed also for BR/EDR connections the work definition is
moved from the LE-specific struct to the generic struct bt_conn.
    
A valid bt_conn object in disconnected state is a likely indication of
a connection reference leak, so there's a new BT_WARN() for this case
in bt_conn_create_le().

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Review by sjanc — APPROVED** [review]

**Comment by Vudentz** [comment]
The problem here is that the conn may have BT_CONN_CLEANUP so we will need to do something about it if the conn is reused, maybe call conn_cleanup.

**Comment by joerchan** [comment]
@Vudentz @jhedberg 
Would this work?
```
void bt_conn_set_state(struct bt_conn *conn, bt_conn_state_t state)
                 * again.
                 */
                bt_conn_ref(conn);
+
+               if (atomic_test_and_clear_bit(conn->flags, BT_CONN_CLEANUP)) {
+                       conn_cleanup(conn);
+               }
                break
```

We should also do a similar change for `bt_conn_create_slave_le`

**Comment by jhedberg** [comment]
@joerchan that might work, however I'm a bit afraid that the cleanup was designed to be done only from the TX thread for a reason (e.g. preventing some race conditions, etc). It's too long since I wrote that code so I'd need to spend some time re-learning & understanding it.

**Comment by jhedberg** [comment]
I've redone this PR by moving the disconnected callback *after* all the internal cleanup is done. I've also included the directed advertising use case here since it's essentially the same thing, i.e. #16480 can be closed (FYI @kapi-no). I'll still need to do some testing of this, so keeping the DNM flag until then.

**Comment by kapi-no** [comment]
> I've redone this PR by moving the disconnected callback after all the internal cleanup is done. I've also included the directed advertising use case here since it's essentially the same thing, i.e. #16480 can be closed (FYI @kapi-no). I'll still need to do some testing of this, so keeping the DNM flag until then.

okay, I will close my PR then.

And thanks for your help with this issue :)

**Comment by jhedberg** [comment]
Removed the DNM flag now. I've tested this to work well using unmodified peripheral app, as well as modified central_hr app which reconnects immediately from the disconnected callback. @Vudentz @joerchan could you guys review?

**Review by Vudentz — APPROVED** [review]
LGTM

**Pull request merged**
