### PR TITLE
cmake: armclang: Handle -mfpu=auto used by cortex-m55

### PR DESCRIPTION
**Pull request by galak**
arm-clang utilizes the gcc fpu flags, however -mfpu=auto is not a supported option in arm-clang.  For arm-clang we can mimic the auto behavior by just not setting the -mfpu option.

### CODE REVIEW

**Comment by galak** [comment]
Not 100% sure if this makes sense for the `FPU_FOR_cortex-m55+...` cases.

**Review by stephanosio — COMMENTED** [review]
If I remember correctly, the reason that I used `-mfpu=auto` instead of an explicit FPU type was that GCC complained about an incorrect FPU type when an explicit type (e.g. `fpv5-*`) was specified.

The problem was something like the `-mfpu` flag did not expose an option that exactly matched the FPU type internally expected by GCC for the specified `-march/-mcpu`.

I guess we will wait and see if all the CI tests (especially the MVE-enabled CMSIS-DSP ones) pass.

**Comment by galak** [comment]
Based on https://developer.arm.com/documentation/101754/0620/armclang-Reference/Other-Compiler-specific-Features/Supported-architecture-feature-combinations-for-specific-processors I think things will be ok since we aren't using an 'nofp' options as part of the cpu option.

**Comment by stephanosio** [comment]
> Based on https://developer.arm.com/documentation/101754/0620/armclang-Reference/Other-Compiler-specific-Features/Supported-architecture-feature-combinations-for-specific-processors I think things will be ok since we aren't using an 'nofp' options as part of the cpu option.

I am unable to reproduce whatever issue I think I was having in the past. No objections to this change; if anything breaks, we can fix it again in the future.

**Review by stephanosio — DISMISSED** [review]

**Comment by XenuIsWatching** [comment]
I don't think this is correct. I did a test to see what the compiler output was for not having the fpu flag (which is not required for the m55 on armclang) and having the flag gave a less optimal output for armclang where the auto vectorizer did not run with mve. 
It still compiled though.... so all the CIs are going to give a pass

This contains a simple loop that will be autovectorized allong with 4 different compiler outputs
1 with clang that has the fpu flags inferred from the cpu flags (as the fpu flag is not needed), and another with the mfpu flag set to `fpv5-d16`. You see that the one without the mfpu flag with use the MVE instructions
https://godbolt.org/z/Ef7avn8dM

**Review by XenuIsWatching — CHANGES_REQUESTED** [review]
I don't think this is working as intended. I did a test to see what the compiler output was for not having the fpu flag (which is not required for the m55 on armclang) and having the flag gave a less optimal output for armclang where the auto vectorizer did not run with mve.
It still compiled though.... so all the CIs are going to give a pass

This contains a simple loop that will be autovectorized along with 4 different compiler outputs
1 with clang that has the fpu flags inferred from the cpu flags (as the fpu flag is not needed), and another with the mfpu flag set to fpv5-d16. You see that the one without the mfpu flag with use the MVE instructions.
Others are just GCC with auto and fpv5-d16
https://godbolt.org/z/Ef7avn8dM

**Comment by galak** [comment]
> I don't think this is working as intended. I did a test to see what the compiler output was for not having the fpu flag (which is not required for the m55 on armclang) and having the flag gave a less optimal output for armclang where the auto vectorizer did not run with mve. It still compiled though.... so all the CIs are going to give a pass
> 
> This contains a simple loop that will be autovectorized along with 4 different compiler outputs 1 with clang that has the fpu flags inferred from the cpu flags (as the fpu flag is not needed), and another with the mfpu flag set to fpv5-d16. You see that the one without the mfpu flag with use the MVE instructions. Others are just GCC with auto and fpv5-d16 https://godbolt.org/z/Ef7avn8dM

which set of options are you saying is optimal?

**Comment by XenuIsWatching** [comment]
> > I don't think this is working as intended. I did a test to see what the compiler output was for not having the fpu flag (which is not required for the m55 on armclang) and having the flag gave a less optimal output for armclang where the auto vectorizer did not run with mve. It still compiled though.... so all the CIs are going to give a pass
> > This contains a simple loop that will be autovectorized along with 4 different compiler outputs 1 with clang that has the fpu flags inferred from the cpu flags (as the fpu flag is not needed), and another with the mfpu flag set to fpv5-d16. You see that the one without the mfpu flag with use the MVE instructions. Others are just GCC with auto and fpv5-d16 https://godbolt.org/z/Ef7avn8dM
> 
> which set of options are you saying is optimal?

The optimal option is no option for armclang :)
`-mfpu` is not needed for the m55.

**Comment by tejlmand** [comment]
> It probably just needs an if statement around the `-mfpu=auto` for only GCC

we should avoid compiler testing for a file which is intended for gcc, hint, notice the file name: `gcc-m-fpu.cmake`

which basically leave us with two other options:
- create a dedicated fpu file for armclang, which brings us back to where we were before: https://github.com/zephyrproject-rtos/zephyr/commit/6d4bce81ae5a2dbe984e5e4dc1e3aa7f0739e786
- Unset the `FPU_FOR_cortex-m55*` values after the gcc defaults has been included here: https://github.com/zephyrproject-rtos/zephyr/blob/82101f45e4996713c2b9f3b455a9ff593311ca5f/cmake/compiler/armclang/target.cmake#L13
   This has the benefit of re-using what can be re-used, while ensuring `armclang` specific overwrites when needed.

**Review by stephanosio — APPROVED** [review]

**Comment by XenuIsWatching** [comment]
> > It probably just needs an if statement around the `-mfpu=auto` for only GCC
> 
> we should avoid compiler testing for a file which is intended for gcc, hint, notice the file name: `gcc-m-fpu.cmake`

yeah... but I'd argue that file ought to be renamed as it is used by armclang and so is `gcc-m-cpu.cmake`.... but maybe another time for that

> Unset the FPU_FOR_cortex-m55* values after the gcc defaults has been included here

That does feel a little dirty (and likely will be reused for the m85 when support for that comes)... but it does work :shrug:

**Review by XenuIsWatching — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]

**Pull request merged**
