### PR TITLE
ext: hal: nordic: Update nrfx to version 1.1.0

### PR DESCRIPTION
**Pull request by anangl**
Updates nrfx to the recently released version.

This version introduces a new HAL for the RADIO peripheral (contained
in the "nrf_radio.h" file) and this HAL replaces the one temporarily
copied to the "nrfx/hal" folder in the Zephyr source tree (see commit
619790a9bcb3a6fea7a91af24007eba6404c1a2b). The nRF 802.15.4 radio
driver ("nrf_drv_radio802154.c") is updated accordingly to reflect
the changes between these two RADIO HAL implementations.

Origin: nrfx
License: BSD 3-Clause
URL: https://github.com/NordicSemiconductor/nrfx/tree/v1.1.0
commit: 293f553ed9551c1fdfd05eac48e75bbdeb4e7290
Purpose: Provide peripheral drivers for Nordic SoCs
Maintained-by: External

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Comment by anangl** [comment]
@aescolar

**Review by aescolar — COMMENTED** [review]
@anangl & @kl-cruz  Thanks!
No complaints from my side

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@kl-cruz is this OK with you?

**Comment by kl-cruz** [comment]
Checking...

**Review by kl-cruz — APPROVED** [review]
looks good!

**Pull request merged**
