### PR TITLE
[DNM] Add flexible top-level runner mechanism

### LINKED ISSUE #4957: Add build targets for each explicit debug/flash option
Its possible that boards support multiple flash/debug choices (ie boards/arm/frdm_kw41z/board.cmake).  We need a way to allow for the user to do something like 'make debug-jlink' or 'make debug-daplink' and have the right thing happen if the board supports both.

### PR DESCRIPTION
**Pull request by mbolivar**
The aim of this series is to introduce zephyr_run.py, a script which:

- can be invoked from a Zephyr build directory to easily flash and debug targets
- supports runtime option settings (i.e. set runner options like --gdb-port or --daparg-arg values when invoking the script, after running CMake)
- supports runtime runner selection (no need to set BOARD_FLASH_RUNNER once and for all; pick any supported runner using an option)
- supports querying the build tree's supported runners and getting detailed help on them

The ability to set values at runtime is the key reason this cannot be done in the build system alone.

It also supports being run from any other directory in the system (not just a build directory) by setting another option.

Putting it in scripts/ means it's on the user's PATH any time they've sourced zephyr-env.

This PR delegates to an existing script (zephyr_flash_debug.py) as an RFC, but will replace the existing script once cleaned up.

Here is the commit text from the main patch (the YAML referred to is introduced in 
25982a0):

```
This script parses the YAML file describing a run configuration which
is generated by CMake, and uses it to implement top-level flash,
debug, and debugserver targets.

The basic usages are equivalent to CMake, when run from the build
directory:

    zephyr_run.py flash        <----> ninja flash
    zephyr_run.py debug        <----> ninja debug
    zephyr_run.py debugserver  <----> ninja debugserver

However, zephyr_run.py supports important use cases that CMake can't.

1) Any arguments (after the command) not handled by zephyr_run.py
   are passed to the underlying runner. For example, if the runner
   supports --gdb-port, the default can be overridden like so:

   zephyr_run.py debugserver --gdb-port=1234

2) Any runner supported by the board can be selected at run time. For
   example, if the board defaults to pyocd but supports jlink, jlink
   can be selected like so:

   zephyr_run.py -r jlink debug

3) The runners.yml configuration can be persisted elsewhere, edited
   offline, and selected at runtime. For example, to flash based on a
   configuration in ~/cached-runners.yml:

   zephyr_run.py -f ~/cached-runners.yml flash

The script also supports an "info" command, which dumps information
about the available Zephyr runners in the build tree:

    zephyr_run.py info
    zephyr_run.py info SOME_RUNNER

For now, the scripts works by invoking zephyr_flash_debug.py. That
will be cleaned up, along with various other improvements to the
runners, in subsequent patches.
```

Arguably:

Fixes #4957

(though it does so with a script instead of additional CMake arguments)

### CODE REVIEW

**Comment by mbolivar** [comment]
> The ability to set values at runtime is the key reason this cannot be done in the build system alone.

I want to emphasize this point.

The only way to pass values to a CMake build system target at runtime is through the environment. It's been discussed elsewhere (#5153) why that's not ideal.

In particular:

https://github.com/zephyrproject-rtos/zephyr/issues/5153#issuecomment-361349632

**Review by carlescufi — COMMENTED** [review]
Thanks @mbolivar for proposing this. I will try it out today and report back. In the meantime, I just want to ask you how would this integrate with the future meta-tool described in #6205

**Comment by SebastianBoe** [comment]
Hi,

I really like that this proposal has a runner with a familiar
command line interface. And that it uses our configuration
system's metadata instead of inventing it's own configuration
system.

But I am concerned about a pitfall that users will often
encounter:

```
# Edit code
zephyr_run.py flash # Oops, silently flashes the wrong firmware

Or

# Edit code
cmake ..
zephyr_run.py flash # Still flashes the wrong firmware
```

I wonder if there is a way to retain the good parts of this
proposal, while avoiding the user-error pitfall it introduces.

Three half-baked ideas (that are not affected by this pitfall):

Have zephyr_run.py invoke ninja before it reads the configuration
information to ensure it is working on an up-to-date
configuration file and an up-to-date hex file.

Use Ninja's 'tool' infrastructure to extend (fork) Ninja with a
Zephyr runner tool.

Keep zephyr_run.py and it's CLI. Extend zephyr_flash_debug.py to
accept environment variables. Have zephyr_run.py invoke ninja
with environment variables based on the CLI input it was
given. PS: Notably, this proposal is not affected by the three
issues raised about an environment variable-based user-interface.

**Comment by b0661** [comment]
Hi,

maybe you can use the CMakeCache.txt file instead of generating a new configuration file for runners.  
By this a user only has to use the "normal" CMake configuration procedure.

There is an example how inline code generation can read (and write) CMakeCache.txt: https://github.com/b0661/zephyr/blob/46f932599dd48463a00f634c1721c2adae502119/scripts/codegen/cmake.py.

Bobby

**Comment by carlescufi** [comment]
@SebastianBoe 

You are right to point out the issues with running a decoupled script from the build system.

>Have zephyr_run.py invoke ninja before it reads the configuration
information to ensure it is working on an up-to-date
configuration file and an up-to-date hex file.

This seems both simple and effective. I have tested it locally and seems to work well.

**Comment by carlescufi** [comment]
@b0661 @SebastianBoe @mbolivar 

>maybe you can use the CMakeCache.txt file instead of generating a new configuration file for runners.

If that is the case then this sounds like a great idea to me.

**Comment by mbolivar** [comment]
Thanks to everyone for the feedback!

@carlescufi:
> I just want to ask you how would this integrate with the future meta-tool described in #6205

Long term, merging this into the meta-tool probably makes sense. Hard to be sure without a more concrete design for that, though.

I do think this feature gap needs closing ASAP, though, especially since the meta-tool is bogged down in the multi-repo question.

@b0661:
> maybe you can use the CMakeCache.txt file instead of generating a new configuration file for runners.

Thanks for bringing this up! I did consider that, and since it seems to be the reviewers' consensus, I will make that work. (Some other build system tweaks will be needed since the relevant state is in properties, not variables, which aren't stored in the cache).

I think having a stand-alone file in a common, "easy" format has advantages, though, which I'll put here for the record.

The main use case I care about is providing binary downloads with convenient flashing instructions to users. Since the runner package is stand-alone, it can be put on PyPI. It would then be trivial to modify the generated YML file to use relative paths and provide a tarball with this inside:

```
binary-dir/
└── zephyr
    ├── runners.yml   # has --kernel-bin=zephyr.bin, --kernel-hex=zephyr.hex, etc.
    ├── zephyr.bin
    ├── zephyr.elf
    └── zephyr.hex
```

It's possible to pare down CMakeCache.txt files to just contain runner state, edit it, and place that there instead of runners.yml, but that's messy and harder for people to get right. We could post-process the cache to generate a stripped-down file with a script to make that easier, but then the outcome is basically the same as what we have now.

More speculatively, I imagined that parsing the YAML might be easier for tools like IDEs that want to do things like provide flashing and debugging configuration wizards. But that's pure imagination :).

@SebastianBoe: 
> Have zephyr_run.py invoke ninja before it reads the configuration
> information to ensure it is working on an up-to-date
> configuration file and an up-to-date hex file.

With s/invoke ninja/invoke "cmake --build" if the script detects it's running in a build directory/, this one is my favorite, for the following reasons:

- it doesn't assume Ninja, and thus can work even with other generators, like makefiles and IDE solution files
- it doesn't keep zephyr_flash_debug.py around (this RFC is only using zephyr_flash_debug.py as a temporary shortcut.  I intend this script to replace zephyr_flash_debug.py.)

I actually wanted to include this in the RFC as I ran into this problem myself while I was testing it, but I was afraid you would object to this for some reason :). So :+1: since you're on board.

**Comment by mbolivar** [comment]
> There is an example how python scripts can read and write CMakeCache.txt: https://github.com/b0661/zephyr/blob/46f932599dd48463a00f634c1721c2adae502119/scripts/codegen/cmake.py.

@b0661, hrm, I didn't realize this commit was out of tree when I originally responded...

I'm hoping not to have to depend on the codegen + pinctrl pull request getting merged to finish this work. For now I'm just going to copy the file here to get things going. We can deal with cleanup as we go.

**Comment by b0661** [comment]
@mbolivar 

> I'm hoping not to have to depend on the codegen + pinctrl pull request getting merged to finish this work.

The example was just to show that it can be done. Relying on codegen does not make sense.

**Comment by MaureenHelm** [comment]
> More speculatively, I imagined that parsing the YAML might be easier for tools like IDEs that want to do things like provide flashing and debugging configuration wizards. But that's pure imagination :).

I've been looking at enhancing the pyocd and jlink runners to generate an eclipse launch file, which is in XML format, as mentioned in #6707. If we save runner configuration to YAML, would I instead need to parse the YAML to generate XML?

I tried out your changes with the pyocd runner, and found some weird behavior when debugging. If I CTRL-C to stop the code after it's been running, I get the following exception:
```
(gdb) c
Continuing.
^CTraceback (most recent call last):
  File "/home/maureen/zephyr/scripts/zephyr_run.py", line 279, in <module>
    main()
  File "/home/maureen/zephyr/scripts/zephyr_run.py", line 263, in main
    args.handler(args, unknown)
  File "/home/maureen/zephyr/scripts/zephyr_run.py", line 97, in command_handler
    subprocess.check_call(flash_debug_cmd)
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 559, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

I played around with arguments like daparg, gdb-port, and flashtool-opt at runtime, and they worked well. Nice work on the verbose help text too.

**Comment by mbolivar** [comment]
> The example was just to show that it can be done. Relying on codegen does not make sense.

I meant relying on the PR to get merged to have access to cmake.py within this work.

At any rate, tried to use the cmake.py you linked to, but found it had lots of problems:

- This access COMMENT is invalid and raises an error: https://github.com/b0661/zephyr/blob/46f932599dd48463a00f634c1721c2adae502119/scripts/codegen/cmake.py#L56
- The style does not match PEP8, which Zephyr's scripts now generally do
- the cache parsers incorrectly assume that __init__ can return a value (in this case, None) which will replace the constructed object, and rely on this behavior (which also causes errors)
- it incorrectly removes whitespace from values that the user put there
- it incorrectly removes "comments" within values (which can contain # and //)

How much are you relying on it? I don't think it's trustworthy. I'm rolling my own parser instead.

**Comment by mbolivar** [comment]
@MaureenHelm :
> I've been looking at enhancing the pyocd and jlink runners to generate an eclipse launch file, which is in XML format, as mentioned in #6707. If we save runner configuration to YAML, would I instead need to parse the YAML to generate XML?

These are orthogonal issues. By the time the runners get constructed in the create_from_args() methods, all of this config file parsing is already done. In create_from_args,  runner instances are constructed entirely from arguments passed to their `__init__` methods, so as long as the constructor arguments are OK for your use case, you shouldn't need to make any changes to your patches.

At any rate, I'm switching from YAML to putting this in the CMake cache, as recommended by @b0661 and seconded by @SebastianBoe and @carlescufi. That still won't affect anything lower level than zephyr_run.py.

> 
> I tried out your changes with the pyocd runner, and found some weird behavior when debugging. If I CTRL-C to stop the code after it's been running, I get the following exception:

Thanks for the report!

I think what's going on here is that GDB is a child of zephyr_flash_debug.py, which itself is a child of zephyr_run.py (since I'm taking a shortcut and invoking zephyr_flash_debug.py here instead of replacing it entirely). This means the signal handling set up by zephyr_flash_debug.py doesn't apply to zephyr_run.py, and you get this issue. You shouldn't (I will make sure) see it in the final submission.

**Comment by mbolivar** [comment]
@MaureenHelm @carlescufi @SebastianBoe @b0661: I've addressed all your suggestions and done a bunch of other cleanups. Thanks for the feedback!

I've tested this out with at least one (runner, command) pair (but as many as I was set up to do for each) on:

- frdm_k64f (pyocd)
- arduino_101 (dfu-util without ST extensions)
- nrf52_blenano2 (pyocd)
- disco_l475_iot1 (openocd)
- nrf52840_pca10056 (nrfjprog, jlink)
- 96b_carbon (dfu-util with ST extensions)

I've done a bunch of other cleanup as well, and am ready to drop the RFC.

**Comment by mbolivar** [comment]
Adding the milestone to try to get this merged in time for LTS.

**Comment by b0661** [comment]
@mbolivar 

>> The example was just to show that it can be done. Relying on codegen does not make sense.

> I meant relying on the PR to get merged to have access to cmake.py within this work.
> At any rate, tried to use the cmake.py you linked to, but found it had lots of problems
> How much are you relying on it? I don't think it's trustworthy. I'm rolling my own parser instead

I meant both - relying on the PR to get merged and on the CMakeCache related code. I took it "form the internet" to get a starting point but currently no inline code is using it.

Sorry for misguiding you to the mostly untested CMakeCache code and thanks for the analysis. I will remove the CMakeCache related code from CodeGen and look into your implementation.

**Comment by MaureenHelm** [comment]
I tested the new version out with pyocd and frdm_k64f, and confirm the signal issue I reported earlier is resolved. I would like to do some more testing with jlink and on Windows, but won't be able to get to it until later today or tomorrow.

**Comment by mbolivar** [comment]
> Sorry for misguiding you to the mostly untested CMakeCache code and thanks for the analysis. I will remove the CMakeCache related code from CodeGen and look into your implementation.

No worries -- if this gets merged first, we can pull the CMake cache code into its own module and work together on any API changes needed for your uses if that's helpful. Otherwise, it's simple enough code that I think duplicating it with small modifications in a couple of places isn't the worst.

**Review by carlescufi — COMMENTED** [review]
This works fine locally and I like the approach.

**Comment by mbolivar** [comment]
> @mbolivar I've approved this but I assume there will be a follow-up PR adding some documentation for the user?

Yup, definitely.

> The reason I mention this is that additional upcoming options like mass-erase will require them to use this directly?

Right. My next steps after this are to audit the existing options and make common functionality more uniform/generic and depend on runner capabilities.

So e.g. runners could declare a mass erase capability, which would then be exposed via  --mass-erase flag instead of the backend-specific situation we have now:

```
    board_runner_args(dfu-util "--dfuse-modifiers=force:mass-erase")
    board_runner_args(pyocd "--flashtool-opt=-ce")
```

There also name changes I want to do, like `--gdb-port` --> `--debug-port` to cover non-GDB cases the same way ZEPHYR_TOOLCHAIN_VARIANT came to be.

This makes the user experience more consistent across boards where possible.

That's a bit more effort though, so will come in a separate PR.

**Comment by mbolivar** [comment]
> There also name changes I want to do

(I'll keep existing names around, but have them trigger deprecation notices)

**Comment by MaureenHelm** [comment]
I tested on Windows with:
- frdm_k64f (pyocd)
- mimxrt1050_evk (jlink)
- lpcxpresso54114 (jlink)

It works nicely for debugging, even with spaces in the gdbserver path. There is a minor difference in how you invoke the script:
```
python %ZEPHYR_BASE%\scripts\zephyr_run.py debug --gdbserver "C:\Program Files (x86)\SEGGER\JLink_V631d\JLinkGDBServerCL.exe"
```

I hit an error flashing with jlink, but it looks like the problem is not related to your changes since I can reproduce it on master.

**Review by carlescufi — APPROVED** [review]

**Comment by nashif** [comment]
we are introducing a new command line tool ad hoc and a new way for doing things on the command line, not really opposed to the idea at all, this is what I did previously outside of the tree (washoe). Do we want to keep the name zephyr_run.py? if this is going to be made available as a first class command, I suggest we spend some time figuring out how this will fit with other things currently under discussion and probably give it a proper name. zephyr_run.py sounds weird to me at least :)

**Comment by mbolivar** [comment]
> we are introducing a new command line tool ad hoc and a new way for doing things on the command line, not really opposed to the idea at all, this is what I did previously outside of the tree (washoe).

Cool, glad you are OK with the general idea!

> Do we want to keep the name zephyr_run.py? if this is going to be made available as a first class command, I suggest we spend some time figuring out how this will fit with other things currently under discussion and probably give it a proper name.

This provides a convenient interface to the "runner" package, which lets you ... run Zephyr ...  for times when "make flash" etc. are not enough. I figured zephyr_run.py was self-explanatory, but I'm happy to change it.

If you're uncomfortable making this a "first class" command, how about I don't write the user-facing documentation just yet? That way it's still an implementation detail.

I would really like this to get merged if possible, though. It enables various use cases, like working with signed bootloader binaries instead of the default ones output by Zephyr, adding host-specific arguments to the runner needed in strange situations (like controlling DAP I/O characteristics in a VM), etc.

I know we want a meta-tool for this eventually, but the the meta-tool and multi-repo discussions are moving slowly, so I'm posting this to try get working code merged in the meantime. This doesn't break any documented functionality, so I hope it's OK.

> zephyr_run.py sounds weird to me at least :)

Sure thing -- any suggestions?

- run-zephyr.py
- zrun.py
- runz.py
- go-zephyr-go.py
- not-washoe.py ;)

**Comment by mbolivar** [comment]
@nashif have you had any more time to think about this?

Approval-wise I think this PR is good to go apart from your comments.

**Comment by mbolivar** [comment]
@MaureenHelm 
> There is a minor difference in how you invoke the script:

Looks like this is because zephyr-env.cmd does not affect PATH, the same way zephyr-env.sh does on POSIX hosts:

https://github.com/zephyrproject-rtos/zephyr/blob/master/zephyr-env.sh#L55

I'm not sure if the same effects are possible in the windows .cmd script.

**Review by SebastianBoe — APPROVED** [review]

**Comment by carlescufi** [comment]
@nashif should we still wait on this one? MCUboot would benefit from having this, even if later this is in fact replaced by the meta-tool.

**Comment by mbolivar** [comment]
This implementation has been incorporated into the initial west PR, #7491

**Pull request closed without merging**
