### PR TITLE
trusted-firmware-m: update to upstream release v.1.3.0

### PR DESCRIPTION
**Pull request by ioannisg**
Update TF-M module to the upstream release v1.3.0.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
Pending release notes entry.

**Comment by galak** [comment]
I merged the module side, so should be ready to update this now.

**Comment by oyvindronningstad** [comment]
I updated the SHA

**Review by oyvindronningstad — APPROVED** [review]

**Comment by ioannisg** [comment]
HW platforms tested:
- nrf53
- nrf91
- nucleo l552ze_q
- mps2_an521

**Review by tejlmand — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]
Tested on `lpcxpresso55s69_ns`

**Comment by ioannisg** [comment]
> Tested on `lpcxpresso55s69_ns`

Thanks! I should be able to do this myself, as well, since I have the board :)

Added a release notes' entry as well.

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
