### PR TITLE
drivers: flash: stm32l1: add initial L1x support

### PR DESCRIPTION
**Pull request by utzig**
Enable L1x flash erase/program using the stm32_v1 driver.

This currently works with something like:

```
uart:~$ flash test FLASH_CTRL 0x24000 0x100 3
Erase OK.
Write OK.
Erase OK.
Write OK.
Erase OK.
Write OK.
Erase-Write test done.
```

The secondary partition is located at `0x24000` in my overlay. I am also trying to add support for mcumgr image management on this device, but so far with no luck. This devices uses flash erased at `0`.

### CODE REVIEW

**Comment by FRASTM** [comment]
tested on nucleo l152re : 
(STM32L flash has dual banks. Bank (0) size is 256kb, base address is 0x8000000)
_samples/drivers/flash_shell/_
```
uart:~$ flash erase 0x1E000 0x1000
uart:~$ flash write 0x1E000 85 170 85 170 
Reading back written bytes: 
55 aa 55 aa 
```

_samples/hello_world_ 
Hello World! nucleo_l152re
with 
CONFIG_SHELL=y
CONFIG_FLASH_SHELL=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_LOG_LEVEL_DBG=y
CONFIG_LOG=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_NO_OPTIMIZATIONS=y

**Comment by utzig** [comment]
Got it working with MCUboot and mcugmr now. mcumgr PR: https://github.com/apache/mynewt-mcumgr/pull/102

My tests used this board https://www.st.com/en/evaluation-tools/32l152cdiscovery.html. The current overlay looks like this:

```
#include <mem.h>

// vim: syntax=dts

/ {
	chosen {
		zephyr,code-partition = &slot0_partition;
	};

	sram0: memory@20000000 {
		reg = <0x20000000 DT_SIZE_K(32)>;
	};

	soc {
		flash-controller@40023c00 {
			flash0: flash@8000000 {
				reg = <0x08000000 DT_SIZE_K(256)>;
			};
		};
	};
};

&flash0 {
	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;

		boot_partition: partition@0 {
			label = "mcuboot";
			reg = <0x00000000 0x00010000>;
			read-only;
		};

		slot0_partition: partition@10000 {
			label = "image-0";
			reg = <0x00010000 0x00014000>;
		};
		slot1_partition: partition@24000 {
			label = "image-1";
			reg = <0x00024000 0x00014000>;
		};

		storage_partition: partition@38000 {
			label = "storage";
			reg = <0x00038000 0x00008000>;
		};
	};
};
```

To build MCUboot:

```
west build -b stm32l1_disco -d build_boot bootloader/mcuboot/boot/zephyr -- -DDTC_OVERLAY_FILE=$(pwd)/l152c_discovery.overlay -DCONFIG_BOOT_SWAP_USING_MOVE=y -DCONFIG_BOOT_MAX_IMG_SECTORS=320
```

To build smp_svr:

```
west build -b stm32l1_disco zephyr/samples/subsys/mgmt/mcumgr/smp_svr -- -DDTC_OVERLAY_FILE=$(pwd)/l152c_discovery.overlay -DOVERLAY_CONFIG=overlay-shell.conf -DCONFIG_IMG_ERASE_PROGRESSIVELY=y -DCONFIG_IMG_MGMT_UL_CHUNK_SIZE=256 -DCONFIG_IMG_BLOCK_BUF_SIZE=256
```

Image upload, test, etc, and MCUboot all work correctly.

/cc @de-nordic @nvlsianpu

**Comment by erwango** [comment]
> The current overlay looks like this

@utzig Thanks, do you plan to push this overlay? I would find it would be valuable

**Review by erwango — APPROVED** [review]

**Comment by utzig** [comment]
> > The current overlay looks like this
> 
> @utzig Thanks, do you plan to push this overlay? I would find it would be valuable

Can do later today, where should I add it?

**Comment by erwango** [comment]
> Can do later today, where should I add it?

Nice! Directly in the board would be good (if I got your question right).

**Review by nvlsianpu — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
