### PR TITLE
drivers: entropy: Add DTS support to native-posix fake entropy driver

### PR DESCRIPTION
**Pull request by galak**
Add a YAML and DTS node for fake entropy driver.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by vanwinkeljan** [comment]
In general this looks good to me, I assume there is a good reason to add this DTS?
We always tried to keep the DTS at a minimum for native posix.

**Comment by galak** [comment]
> In general this looks good to me, I assume there is a good reason to add this DTS?
> We always tried to keep the DTS at a minimum for native posix.

Mostly that we are trying to get all drivers to use DTS and this is one of the small handful of entropy drivers that isn't using DTS.

**Comment by vanwinkeljan** [comment]
@aescolar your call as maintainer, for me it is OK

**Comment by galak** [comment]
> @aescolar your call as maintainer, for me it is OK

@vanwinkeljan @aescolar is on vacation for several weeks.

**Review by vanwinkeljan — APPROVED** [review]

**Pull request merged**
