### PR TITLE
drivers: wifi/airoc: update airoc_wifi_host_buffer_get

### PR DESCRIPTION
**Pull request by npal-cy**
Update airoc_wifi_host_buffer_get function to set final buff size based on input “size” param.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
LGTM, just fix the compliance issue.

**Comment by npal-cy** [comment]
hi @jukkar can we merge this on?

**Review by ifyall — APPROVED** [review]

**Comment by carlescufi** [comment]
@jukkar can you approve if happy?

**Review by ifyall — APPROVED** [review]

**Comment by npal-cy** [comment]
Hi @jukkar, @carlescufi this one as well as pull/74203 is critical to be present in 3.7 releases. Could you help with review?

**Review by jukkar — APPROVED** [review]

**Comment by ifyall** [comment]
Agreed, this should be marked 3.7.0.

**Pull request merged**
