### PR TITLE
driver: bt: esp32: use BUILD_ONLY_NO_BLOBS to allow CI tests

### PR DESCRIPTION
**Pull request by sylvioalves**
Add BUILD_ONLY_NO_BLOBS to allow CI tests.

Read this before: #80785

Depends on #82931 due to HAL merging sequence.

### CODE REVIEW

**Comment by jhedberg** [comment]
As suggested in https://github.com/zephyrproject-rtos/hal_espressif/pull/359#discussion_r1864432600 I think it would make sense to just have one option for all of this, since it's all about doing CI compile testing without blobs present. The specific feature(s) that blobs are needed for seems secondary.

**Comment by jhedberg** [comment]
This is starting to look pretty good to me. I'm hoping to get `hal_silabs` included as well, maybe not in this PR, but soon after it's been merged. Any particular reason why you're still keeping it as a Draft?

**Comment by sylvioalves** [comment]
PR is ready.

**Review by jhedberg — DISMISSED** [review]

**Review by wmrsouza — DISMISSED** [review]

**Review by raffarost — DISMISSED** [review]

**Review by uLipe — DISMISSED** [review]

**Comment by jhedberg** [comment]
@sylvioalves there's a bunch of conflicts that need fixing

**Review by jhedberg — DISMISSED** [review]

**Review by wmrsouza — DISMISSED** [review]

**Comment by kartben** [comment]
@sylvioalves this will need a rebase

**Review by wmrsouza — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by raffarost — APPROVED** [review]

**Pull request merged**
