### PR TITLE
tests: net: lib: lwm2m: content_senml_cbor: move to new ztest API

### PR DESCRIPTION
**Pull request by hunterhu3000**
Move net content_senml_cbor tests to use new ztest API

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

### CODE REVIEW

**Comment by hunterhu3000** [comment]
Add initial state of test_opaque in test_get_opaque()

**Review by rlubos — DISMISSED** [review]

**Comment by enjiamai** [comment]
It pass in my environment, maybe you need to rebase. Hi @hunterhu3000 , could please rebase it again by yourself to avoid the compliance check failure? Thanks.

**Comment by hunterhu3000** [comment]
> It pass in my environment, maybe you need to rebase. Hi @hunterhu3000 , could please rebase it again by yourself to avoid the compliance check failure? Thanks.

It is also pass on my test machine. It seems rebase does not fix the issue, it may be something related to the environment of the machine that runs the CI

**Review by rlubos — DISMISSED** [review]

**Comment by hunterhu3000** [comment]
@rlubos @enjiamai 
If test_put_opaque() is put before test_get_opaque() the test can pass without any CI failure.
Thanks to review

**Review by enjiamai — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
