### PR TITLE
[TOPIC: DTS] scripts: dts: Simplify and improve 'compatible' matching

### PR DESCRIPTION
**Pull request by ulfalizer**
scripts: dts: Simplify and improve 'compatible' matching

Instead of

    properties:
        compatible:
            constraint: "foo"

, just have

    compatible: "foo"

at the top level of the binding.

For backwards compatibility, the old 'properties: compatible: ...' form
is still accepted for now, and is treated the same as a single-element
'compatible:'.

The old syntax was inspired by dt-schema (though it isn't
dt-schema-compatible), which is in turn a thin wrapper around
json-schema (the idea is to transform .dts files into YAML and then
verify them).

Maybe the idea was to gradually switch the syntax over to dt-schema and
then be able to use unmodified dt-schema bindings, but dt-schema is
really a different kind of tool (a completely standalone linter), and
works very differently from our stuff (see schemas/dt-core.yaml in the
dt-schema repo to get an idea of just how differently).

Better to keep it simple.

This commit also piggybacks some clarifications to the binding template
re. '#cells:'.

### CODE REVIEW

**Comment by ulfalizer** [comment]
Piggybacking some license header nits.

**Comment by ulfalizer** [comment]
Gotta fix the old scripts too. Will do tomorrow.

**Comment by ulfalizer** [comment]
Updated now.

**Comment by ulfalizer** [comment]
@galak ping

Indirectly cleans up some stuff that should've been using `base.yaml`, like

```diff
diff --git a/dts/bindings/gpio/gpio-keys.yaml b/dts/bindings/gpio/gpio-keys.yaml
index 308986c3cf..e4dc96d348 100644
--- a/dts/bindings/gpio/gpio-keys.yaml
+++ b/dts/bindings/gpio/gpio-keys.yaml
@@ -9,12 +9,7 @@ title: GPIO KEYS
 description: >
     This is a representation of the GPIO KEYS nodes
 
-properties:
-    compatible:
-      constraint: "gpio-keys"
-      type: string-array
-      required: true
-      description: compatible strings
+compatible: "gpio-keys"
 
 sub-node:
     properties:
```

**Review by dbkinder — APPROVED** [review]
+1 for doc change :)

**Review by pabigot — CHANGES_REQUESTED** [review]
As a syntactic change this seems reasonable, but since it also adds a feature (support for multiple compatibles in the binding) I would like to see a more clear description of what "compatible" does, as it affects three domains: devicetree nodes, bindings, and drivers.

In base devicetree (from rev 0.3-rc2):

> The compatible property value consists of one or more strings that define the specific programming model for the device. This list of strings should be used by a client program for device driver selection.

So its primary role is to connect nodes to drivers that will use properties from the node.

Here in Zephyr (and in DT-Schema) it's also used to connect nodes to a binding (description) that can be used to validate the node content against driver expectations and to control how the node content is translated into named values in the generated header.

A scan through the PR suggests that no existing Zephyr binding uses a list of compatibles.

I can come up with a reason why somebody would want to provide multiple compatibles in a single binding, but it's not a reason that I would accept as a Zephyr maintainer.  (I think it might make sense in DT-Schema, which as you note has different scope and purpose.)

So: If the change to support multiple compatibles is to be kept in, I want `binding-template.yaml` to explain exactly when somebody should use a list instead of a single value.  If there's no good explanation, remove the list option.

Also, the same area should describe the infrastructure behavior when multiple bindings claim to provide the same compatible.  Does it produce an error?   If not, what does happen?  Either way the `binding-template.yaml` description, since it's specific to the Zephyr tooling, should describe what the Zephyr tooling will do.

I also want to see the documentation use more realistic examples.  `"bar"` and `"foo"` are horrible compatibles; `"manufacturer,model"` expresses what real values should look like (and matches the text in the devicetree specification).  If the list feature gets dropped, then we only need one example and that can be it.

**Comment by ulfalizer** [comment]
> So: If the change to support multiple compatibles is to be kept in, I want `binding-template.yaml` to explain exactly when somebody should use a list instead of a single value. If there's no good explanation, remove the list option.

@galak requested being able to match multiple compatibles, so you'd have to ask him. Seems pretty harmless to me at least, and maybe useful.

I'll de-foo it.

**Comment by ulfalizer** [comment]
De-foo'd

**Comment by ulfalizer** [comment]
@pabigot 
I've piggybacked some `#cells` clarifications now too. See if it looks better.

**Comment by pabigot** [comment]
> ```yaml
> compatible: ["manufacturer,device-v2", "manufacturer,device-v3"]
> ```

Yep, that's exactly the sort of thing that I imagined somebody would want to do.  I suspect it's trying to express what should be expressed by:
```
   compatible = "manufacturer,device-v3", "manufacturer,device-v2";
```
in the devicetree node, which says "This is a v3 device, but it's ok to use the v2 driver which may or may not look for the v3 compatible presence flag and adjust its functionality".  Which is how it works in Linux (pre-DT-Schema at least).

I don't believe the binding needs to list multiple compatibles to make that work.  The tooling just needs to generate:
```
#define DT_MANUFACTURER_DEVICE_V3 1
#define DT_MANUFACTURER_DEVICE_V2 1
```
so the driver can tell what features to enable.  (Actually the names need to be instance-specific, but I'm looking at an old tree for the example.)

This then brings up a disagreement I have with the clarification on multiple bindings with the same compatible.   The behavior should be to register the first binding encountered (based on the ordered search path), and ignore or at most warn about any subsequent bindings that try to provide structure for the same compatible.  That allows me to override with a custom driver that does use `compatible: "manufacturer,device-v3"` and adds additional properties to take advantage of v3-specific features not supported in the v2 implementation.

@galak how does this compare against the use case that motivated your request for multiple compatibles in the binding?

**Comment by ulfalizer** [comment]
> ```yaml
> compatible: ["manufacturer,device-v2", "manufacturer,device-v3"]
> ```
> 
> Yep, that's exactly the sort of thing that I imagined somebody would want to do.  I suspect it's trying to express what should be expressed by:
> ```
>    compatible = "manufacturer,device-v3", "manufacturer,device-v2";
> ```

Yeah, `-v2` vs. `-v3` was a bad example. I changed it to "foo" and "bar" instead.

@galak 
What were you gonna use it for again?

**Comment by ulfalizer** [comment]
Thought about it some more, and I think I agree with @pabigot.

Maybe it would get misused for the stuff I originally put in as an example, and maybe there aren't enough good uses to make up for it. Can't remember what @galak was going to use it for though.

I just hope this doesn't delay the PR by a few weeks more, now that it might finally be past the syntactic stuff. I've got other stuff that builds on it...

I'm fine with whatever in this case. It's up to you and @galak. As a compromise, I could always remove the possibility to put more than one compatible for this PR. Then it could be added back later if there turns out to be good uses.

**Comment by galak** [comment]
My intent with the feature was to handle where a single binding could be used for a number of different devices.  For example the slew of `dts/bindings/cpu/arm,cortex-m*.yaml` could be handled in a single `arm,cortex-m.yaml` binding.

I'm wondering if we need a better means of describing how a DT node matches a binding.  For example, we have `compatible` match, and we also have child/parent bus matching.  I clearly desire we have the ability to have a list of `compatible` in the binding and match `if any`.  I wonder if there's a case for matching `if all`.

**Comment by pabigot** [comment]
> My intent with the feature was to handle where a single binding could be used for a number of different devices. For example the slew of `dts/bindings/cpu/arm,cortex-m*.yaml` could be handled in a single `arm,cortex-m.yaml` binding.

The way to do it now would be to use `compatible = "arm,cortex-m3", "arm,cortex-m";` in the devicetree source.  Then, when there's actually a difference, adding the specific binding.
 
> I'm wondering if we need a better means of describing how a DT node matches a binding. For example, we have `compatible` match, and we also have child/parent bus matching. I clearly desire we have the ability to have a list of `compatible` in the binding and match `if any`. I wonder if there's a case for matching `if all`.

Of course there is.  I don't know what, but there'll be a situation where it's the best solution.  There are examples in Linux.

I fall back to my previously-stated position: we need a plan.  Absent a plan, we should be re-using existing active technology: DT-Schema.  If we can't even do that, then I have no hope that Zephyr will ever reach a level of maturity suitable for production-level applications with useful lifespan.

**Comment by galak** [comment]
Let's make the format change and keep the semantics the same as they are today, so we can progress this forward.

**Comment by ulfalizer** [comment]
Now updated to only accept a single compatible.

https://github.com/zephyrproject-rtos/zephyr/pull/18968 should go in first, so marking as DNM for now, in case I update it.

**Review by pabigot — APPROVED** [review]

**Comment by ulfalizer** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/18968 is in, so should be fine now unless there's review complaints.

Nice to let the CI check run to completion just in case though.

**Review by galak — APPROVED** [review]

**Pull request merged**
