### PR TITLE
Update revisions  on EFR32BG22 Thunderboard to HWMv2.

### PR DESCRIPTION
**Pull request by wkhadgar**
The current HWMv2 encourages the use of revisions not as different boards. This commit updates the current port to align with the HWMv2 goals.

### CODE REVIEW

**Review by nordicjm — COMMENTED** [review]
This is what was originally proposed in https://github.com/zephyrproject-rtos/zephyr/pull/69231 but was rejected by @jerome-pouiller

**Comment by wkhadgar** [comment]
> This is what was originally proposed in https://github.com/zephyrproject-rtos/zephyr/pull/69231 but was rejected by @jerome-pouiller

I wonder the reason to not have thunderboard revisions as proper A/B revisions... Took a look at the PR but didn't find the reason besides some comments on cleaning the boards tree later, is that it? Also, thanks for the response, I see that you also tried the same thing on your PR, sorry for not digging enough 😅

**Comment by nordicjm** [comment]
Underlying issue was posted on https://github.com/zephyrproject-rtos/hal_silabs/pull/58#discussion_r1499049643
> In fact, I believe we should keep efr32bg22_brd4184a and efr32bg22_brd4184b as two separated boards and get rid of CONFIG_BOARD_REVISION.
> 
> For information, the full names of the boards with revision are brd4184a rev A01, brd4184a rev A02, brd4184b rev A01, etc... But until now, we didn't have to change any configuration between the revisions.

**Comment by wkhadgar** [comment]
I see, in that case, doesn't the current docs kind of give the wrong impressions on revisions? Didn't got any mentions of those A01, A02..., and truly thought that that A/B where the true revisions. What do you think about that? 
I wonder if since dts changes are only needed between A/B, keeping them as Zephyr board revisions (like the current documentation states) is a better choice than keeping them as separate boards. I guess it may be easier to maintain this way and more aligned with all the other boards.

**Comment by nordicjm** [comment]
I would prefer they used board revisions properly but at the end of the day it's up to vendors how they want their boards structured.

**Comment by wkhadgar** [comment]
Yeah, that's what matters in the end, even when not the best option. I'll hope @jerome-pouiller take a second thought on this topic, at least for Thunderboard, these brd4184a and brd4184b with only minor DTS changes between them really feel like an anti-HWMv2 way of  representation.

**Comment by wkhadgar** [comment]
The CI check fails are not related to the changes in this PR. 
image
image

**Comment by wkhadgar** [comment]
Updated with the upstream.

**Comment by jerome-pouiller** [comment]
@wkhadgar, sorry for the delay.

In fact, boards have 3 components: product number, variant and revision, e.g. `BRD4184`, `B`, `A01`. We never separate product number and variant publicly. So, from HWMv2 point of view, `BRD4184A` and `BRD4184B` are different boards.

Furthermore, we do sell different variants of the same board product number in parallel. This is very common for radio boards, where the A, B, C, and D variants could have different sub-ghz matching for 434, 490, 868 and 915 MHz.

In this specific case, it is indeed a bit confusing because the A variant was discontinued when the B variant was released.

I would like to write this policy somewhere (with a copy of [this table][1] ). Do you think `boards/silabs/index.rst` would be the right place for that?

[1]: https://github.com/zephyrproject-rtos/zephyr/pull/69231#pullrequestreview-1893248972

**Comment by nordicjm** [comment]
@kartben

**Comment by jerome-pouiller** [comment]
> do you think this "no public variant" policy could be dismissed? Or is there an underlying issue that prevents the variants from being explicit?

humm... I don't get your point. The variant is always explicit.

> I think it would be great to have this table more accessible

I fully agree. I would be glad to review a such patch.

**Comment by wkhadgar** [comment]
> humm... I don't get your point. The variant is always explicit.

I mean to keep BG22 as a single board, and add A/B as variants from the HWMv2 point of view, instead of board revisions as I previously intended. We would get something like `brd4184/efr32bg22//a` and `brd4184/efr32bg22//b`

**Comment by wkhadgar** [comment]
> although in a slightly different way.

Quite smart way I would argue, didn't though about using the ``` slt` -/like naming to solve the inconsistency. (Even though if I ever did, I'm not sure if doing the full Silabs update to match this Thunderboard issue would be possible to me 😅)

Glad to see Silabs boards getting some attention and care! Thanks @asmellby for the big update!

**Pull request closed without merging**
