### PR TITLE
drivers: gpio: dw: Switch to `DT_INST_IRQN_BY_IDX`

### PR DESCRIPTION
**Pull request by xingrz**
As described in `doc/kernel/services/interrupts.rst`, multi-level interrupts are recorded in the ISR table using a value that is shifted (encoded) based on the level. The values passed to `IRQ_CONNECT` and `irq_enable`/`irq_disable` are also these encoded values, which are later used to extract the irq level and route these calls to the corresponding level of interrupt controller.

In previous versions, `gen_defines.py` implemented the corresponding encoding process, so the irq number we got through `DT_IRQ(node, irq)` was the encoded value. However, starting from #63289, this process has been moved to a C macro. As a result, we need to use `DT_IRQN(node)` to get the encoded value, instead of getting the as-seen irq cell value through `DT_IRQ(node, irq)`.

This PR updates `gpio-dw` to align with the mentioned changes. Thus, in SoCs where `gpio-dw` is connected to a secondary intc, the GPIO controller can be correctly connected to the ISR table via `IRQ_CONNECT`, and `irq_enable` can be routed to the correct intc instance.

### CODE REVIEW

**Comment by xingrz** [comment]
`grep`-ed treewide and didn't find any SoCs using this driver with multi-level interrupts. I think this fix won't break any existing in-tree boards.

**Comment by cfriedt** [comment]
cc @bjarki-trackunit, @ycsin

**Review by ycsin — DISMISSED** [review]
LGTM

**Comment by xingrz** [comment]
Updated

**Comment by cfriedt** [comment]
@xingrz it looks like an ifdef needs to be put around the isr for it to be compiled regularly

```
/__w/zephyr/zephyr/drivers/gpio/gpio_dw.c:387:13: error: ‘gpio_dw_isr’ defined but not used [-Werror=unused-function]
```

https://github.com/zephyrproject-rtos/zephyqr/actions/runs/8379204533/job/22945720630#step:12:4413

**Review by ycsin — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
