### PR TITLE
runners: jlink: manually check command output

### LINKED ISSUE #38592: flash runners: JLink provides no notifications of failures
**Describe the bug**
When flashing a board that uses the `JLink` runner, no notification is provided to the user if the flash command fails.

**To Reproduce**
1. Build any application for a board using the `JLink` runner
2. Run `west flash` with the board connected
3. Run `west flash` with the programmer disconnected

**Expected behavior**
Some error should be printed to the user

**Impact**
Annoyance

**Logs and console output**

One of these two commands was run with no board connected. Can you tell which?
```
C:\Users\Jordan\code\zephyr>west flash -d build\loci3\hello_world
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner jlink
-- runners.jlink: JLink version: 7.50a
-- runners.jlink: Flashing file: build\loci3\hello_world\zephyr\zephyr.hex

C:\Users\Jordan\code\zephyr>west flash -d build\loci3\hello_world
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner jlink
-- runners.jlink: JLink version: 7.50a
-- runners.jlink: Flashing file: build\loci3\hello_world\zephyr\zephyr.hex

C:\Users\Jordan\code\zephyr>
```

**Environment (please complete the following information):**
 - OS: Windows
 - Zephyr v2.7.0-rc1

### PR DESCRIPTION
**Pull request by JordanYates**
Manually check the output of the JLink tool when flashing, as failures
do not result in error codes being returned that `check_call` can
validate. The string "Writing failed." appears at the end of the output
if running the script fails:

```
Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Target connection not established yet but required for command.
Device "NRF52" selected.

Connecting to target via SWD
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
InitTarget() start
InitTarget() end
Cannot connect to target.

Writing failed.

Reading failed.

Script processing completed.
```

Fixes #38592.

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

### CODE REVIEW

**Review by carlescufi — COMMENTED** [review]
I am OK with this, but could we do both? i.e. check the return value and the output and fail if either of them fail? Then if JLink.exe gets their act together we will be ready for that.

**Comment by JordanYates** [comment]
> I am OK with this, but could we do both? i.e. check the return value and the output and fail if either of them fail? Then if JLink.exe gets their act together we will be ready for that.

The subprocess calls already do this (by raising exceptions):
```
def check_output(*popenargs, timeout=None, **kwargs):
    r"""Run command with arguments and return its output.

    If the exit code was non-zero it raises a CalledProcessError.  The
    CalledProcessError object will have the return code in the returncode
    attribute and output in the output attribute.
```

**Review by carlescufi — APPROVED** [review]

**Comment by cfriedt** [comment]
@mbolivar-nordic - can we get your ack?

**Review by gmarull — COMMENTED** [review]
I just have one comment regarding the removal of debug capability

**Pull request closed without merging**
