### PR TITLE
drivers: intc: add irq-manager driver and API

### PR DESCRIPTION
**Pull request by ycsin**
This driver rides on top of a typical interrupt controller and provide APIs to dynamically allocate interrupts line. The range of interrupts managed by this driver is configured in the devicetree.

### CODE REVIEW

**Review by decsny — CHANGES_REQUESTED** [review]
what's the use case of this? I am not keen to add another zephyr-ism in DT without a good reason

**Comment by ycsin** [comment]
> what's the use case of this? I am not keen to add another zephyr-ism in DT without a good reason

This pseudo driver is helpful in a scenario when multiple services need access to IRQs only when they are running, it allows a pool of IRQs to be shared by these services.

For example, the [perf tool](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/profiling/perf/perf.c) can be extended to support SMP by installing IPI ISRs on RISC-V to trigger each of the cores when it is running, these interrupt lines would usually be dormant when `perf` isn't running. With `irq-manager`, these interrupt lines can be used for other purposes.

**Comment by decsny** [comment]
There is not enough description in this PR of what this actually _is_ , I'm not clear even what aspect of IRQs this is supposedly managing, I'm not even sure what it means by allocating and freeing interrupt lines. And looking at what irq_base parameter is being used like, it looks like maybe this is the part that relates to hardware, but it seems architecture specific? I would ask you to improve the documentation but I am still skeptical of this whole PR, so instead can you just improve the PR description first ? And since it seems like each "irq manager" instance correlates directly to a single interrupt controller, why does there need to be a separate DT node to represent this driver ? that seems just not acceptable

**Comment by bjarki-andreasen** [comment]
I'm guessing the arch you are working with has dynamically routeable interrupts? as in an interrupt from one core can be connected to another interrupt generating device at runtime?

**Comment by decsny** [comment]
to be clear, whatever this is, I am not outright opposing it, it's just not clear to me what exactly this is, and it seems specific to some architecture but posing as a generic thing, this just needs more explanation.

**Comment by ycsin** [comment]
Pull this back to draft for now, will update the doc & comments later

**Pull request closed without merging**
