### PR TITLE
pinmux: stm32: add support for PA11/PA12 remap

### PR DESCRIPTION
**Pull request by gmarull**
This PR is part of some improvements while doing an initial port of the pinmux STM32 driver to the #37572 API

Certain STM32 SoCs (F0/G0) allow to remap PA11/12 to PA9/10. Some boards
were manually configuring this remap. This patch centralizes this
functionality to the pinmux driver, allowing boards to enable the remap
by just enabling appropriate Kconfig options.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
While at it, let's move this configuration to DT as a gpio property.

**Comment by gmarull** [comment]
> While at it, let's move this configuration to DT as a gpio property.

Can you suggest the bindings you're thinking of?

**Comment by erwango** [comment]
> Can you suggest the bindings you're thinking of?

I was thinking basic boolean props `remap_pa12_as_pa10` and `remap_pa11_as_pa9`.
Though, I don't think it's required to go that far as creating new stm32-gpio compats.
Defining these as optional to stm32-gpio is good enough (even if it would require
 x-check these are defined only for F0, G0 using Kconfig symbols).

**Comment by gmarull** [comment]
Closing in favor of #39106

**Pull request closed without merging**
