### PR TITLE
Bluetooth: Additional 1.9.2 fix

### PR DESCRIPTION
**Pull request by carlescufi**

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by cvinayak — CHANGES_REQUESTED** [review]
Fails a conformance test, requesting changes until fixed.

**Comment by carlescufi** [comment]
@cvinayak @jhedberg added last fix to pass conformance

**Comment by carlescufi** [comment]
Waiting for EBQ results before approving

**Comment by cvinayak** [comment]
All 271 conformance tests passed.

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
