### PR TITLE
boards: thingy53_nrf5340: Do not forward FEM SPI pins to cpunet

### PR DESCRIPTION
**Pull request by MarekPieta**
The SPI cannot be shared between the cores. The MPSL running on the network core does not support SPI comminucation yet, so the application core sets FEM's CS to inactive state.

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]

**Comment by MarekPieta** [comment]
Discussed offline with @anangl.
We decided that the CS pin will be again controlled by the app core and pulled up (it should be automatically done for all of the SPI peripherals by the SPI driver now). It cannot be used anyway, because SPI lines cannot be properly shared between app and net core and there are additional sensors connected over the same SPI lines.

**Review by anangl — DISMISSED** [review]

**Comment by MarekPieta** [comment]
Hi @anangl
Can we merge this one?

**Comment by jciupis** [comment]
@MarekPieta now that #43047 was merged please consider removing any SPI pins from the `nrf-gpio-forwarder` node defined for thingy53 board to make this PR complete.

**Comment by MarekPieta** [comment]
Hi @jciupis,
In that case I need to reimplement it before we merge it.

**Comment by MarekPieta** [comment]
Hi @anangl, @jciupis
The change was aligned with pin forwarder. Please review.

**Review by jciupis — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

**Comment by MarekPieta** [comment]
Force pushed and rebased to fix reported CI issue that was not related to the change

**Review by anangl — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Pull request merged**
