### PR TITLE
cpp: support for std::thread and std::this_thread

### LINKED ISSUE #25569: Support for std::thread and std::this_thread
**Is your enhancement proposal related to a problem? Please describe.**
It would be nice for C++ applications to be able to use [std::thread](https://en.cppreference.com/w/cpp/thread/thread) and [std::this_thread](http://www.cplusplus.com/reference/thread/this_thread/).

**Describe the solution you'd like**
To be able to use std::thread and this_thread. I can make a PR.

**Describe alternatives you've considered**
I recently created a PR to provide a sample for and to document the socketpair API (#25528) and was able to get threading working with a couple of defines and implementing [std::thread::join()](https://en.cppreference.com/w/cpp/thread/thread/join).

I also needed [nanosleep(2)](https://pubs.opengroup.org/onlinepubs/9699919799/functions/nanosleep.html) for [std::this_thread::sleep_for()](https://en.cppreference.com/w/cpp/thread/sleep_for)

However, there are also a couple of additional modes that will need testing. I thought it better to make a separate PR to address it.

**Additional context**

### PR DESCRIPTION
**Pull request by cfriedt**
This commit adds support for std::thread and std::this_thread
when the configured C++ standard is >= C++11.

The implementation uses POSIX threads under the hood.

Fixes #25569

### CODE REVIEW

**Review by pabigot — COMMENTED** [review]
This probably isn't going to go far until #21519 is settled and we have a thread-safe libc.

I suppose we could have thread support provided by POSIX as a stop-gap, as long as it's understood that the preferred solution is using native Zephyr threads.

**Comment by cfriedt** [comment]
> I suppose we could have thread support provided by POSIX as a stop-gap, as long as it's understood that the preferred solution is using native Zephyr threads.

The primary reason why I chose to piggyback on top of pthreads was because it was pretty trivially easy to do it, but I could try giving it a go with Zephyr threads. It would be kind of nice to separate those APIs.

**Comment by cfriedt** [comment]
Will reattempt with Zephyr threads shortly. Just wanted to make sure that everything compiled first.

Not crazy about the include/cpp/thread_bits.h file, but it works.

Also, kind of lame, but my debian gcc-arm-none-eabi toolchain does not have definitions for `thread::get_native_handle()` or `thread::hardware_concurrency()`. I'll see if I can update my toolchain and / or use the official zephyr one.

**Comment by cfriedt** [comment]
With `BOARD=native_posix_64` all of these tests pass now.

```console
*** Booting Zephyr OS build zephyr-v2.3.0-480-g6da849eb8163  ***
version 201703
Running test suite libcxx_tests
===================================================================
starting test - test_array
PASS - test_array
===================================================================
starting test - test_vector
PASS - test_vector
===================================================================
starting test - test_make_unique
PASS - test_make_unique
===================================================================
starting test - test_this_thread_get_id
PASS - test_this_thread_get_id
===================================================================
starting test - test_this_thread_yield
PASS - test_this_thread_yield
===================================================================
starting test - test_this_thread_sleep_until
PASS - test_this_thread_sleep_until
===================================================================
starting test - test_this_thread_sleep_for
PASS - test_this_thread_sleep_for
===================================================================
starting test - test_thread_get_id
PASS - test_thread_get_id
===================================================================
starting test - test_thread_native_handle
PASS - test_thread_native_handle
===================================================================
starting test - test_thread_hardware_concurrency
PASS - test_thread_hardware_concurrency
===================================================================
starting test - test_thread_join
PASS - test_thread_join
===================================================================
starting test - test_thread_detach
PASS - test_thread_detach
===================================================================
starting test - test_thread_swap
PASS - test_thread_swap
===================================================================
Test suite libcxx_tests succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```
However, I'm getting some warnings due to implicit cast / narrowing in `system_clock.h`
```console
[12/89] Building CXX object CMakeFiles/app.dir/src/stl/make_unique.cpp.obj
In file included from /home/chrisfriedt/workspace/zephyrproject/zephyr/include/kernel_includes.h:41,
                 from /home/chrisfriedt/workspace/zephyrproject/zephyr/include/kernel.h:17,
                 from /home/chrisfriedt/workspace/zephyrproject/zephyr/include/zephyr.h:18,
                 from /home/chrisfriedt/workspace/zephyrproject/zephyr/subsys/testsuite/ztest/include/ztest.h:57,
                 from /home/chrisfriedt/workspace/zephyrproject/zephyr/tests/application_development/libcxx/src/stl/make_unique.cpp:9:
/home/chrisfriedt/workspace/zephyrproject/zephyr/include/kernel.h: In function ‘int32_t k_msleep(int32_t)’:
/home/chrisfriedt/workspace/zephyrproject/zephyr/include/sys_clock.h:89:62: warning: narrowing conversion of ‘k_ms_to_ticks_ceil64(((uint64_t)((ms > 0) ? ms : 0)))’ from ‘uint64_t’ {aka ‘long unsigned int’} to ‘k_ticks_t’ {aka ‘long int’} inside { } [-Wnarrowing]
 # define Z_TIMEOUT_MS(t) Z_TIMEOUT_TICKS(k_ms_to_ticks_ceil64(MAX(t, 0)))
                                                              ^
/home/chrisfriedt/workspace/zephyrproject/zephyr/include/sys_clock.h:85:55: note: in definition of macro ‘Z_TIMEOUT_TICKS’
 #define Z_TIMEOUT_TICKS(t) ((k_timeout_t) { .ticks = (t) })
                                                       ^
/home/chrisfriedt/workspace/zephyrproject/zephyr/include/kernel.h:940:17: note: in expansion of macro ‘Z_TIMEOUT_MS’
  return k_sleep(Z_TIMEOUT_MS(ms));
                 ^~~~~~~~~~~~
```

Upon moving to `BOARD=qemu_cortex_m3`, I encountered some compile errors, due to the fact that we have not implemented `PTHREAD_MUTEX_INITIALIZER` and `PTHREAD_COND_INITIALIZER`.

```cpp
/* FIXME: these are going to be tricky to implement.  Zephyr has (for
 * good reason) deprecated its own "initializer" macros in favor of a
 * static "declaration" macros instead.  Using such a macro inside a
 * gcc compound expression to declare and object then reference it
 * would work, but gcc limits such expressions to function context
 * (because they may need to generate code that runs at assignment
 * time) and much real-world use of these initializers is for static
 * variables.  The best trick I can think of would be to declare it in
 * a special section and then initialize that section at runtime
 * startup, which sort of defeats the purpose of having these be
 * static...
 *
 * Instead, see the nonstandard PTHREAD_*_DEFINE macros instead, which
 * work similarly but conform to Zephyr's paradigms.
 */
/* #define PTHREAD_MUTEX_INITIALIZER */
/* #define PTHREAD_COND_INITIALIZER */
```

I believe the issues are in `include/bits/gthr-zephyr.h`, and we probably only need to instead call `pthread_mutex_init(3)` and `pthread_cond_init(3)`. So an easy fix.

**MOST IMPORTANTLY**, it should be noted that the gthr-zephyr.h file (or some variation of it) must ultimately be part of the SDK. I don't care to correct the whitespace formatting for it, but only to ensure that CI will pass before making a PR to the SDK so that `std::thread` may be enabled by default for any c++ std > C++98.

This PR is also blocked by #25973 (or #16435).

CC: @galak

**Comment by cfriedt** [comment]
Just remembered to check for `CONFIG_BOARD_NRF52_BSIM`

**Pull request closed without merging**
