### PR TITLE
x86: memory map BIOS Data Area

### LINKED ISSUE #27867: up_squared: couldn't get test result from serial of each test.
**Describe the bug**
for up_squared, when using zephyr.strip file and usb disk to run tests on this board, couldn't get test result from serial for each test.

the good commit is 4cf1832fa8, but for the latest, it's broken.

**To Reproduce**
1.  west build -b up_squared -p auto samples/hello_world/
2.  west flash ~/up_squared.sh
3.  see error

**Logs and console output**
there is nothing in the console, it seems that the test doesn't boot up.

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.4
 - CommitID: 6a8c622bcca

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Changes to paging code ensured that the NULL virtual page is
never mapped. Since RAM is identity mapped, on a PC-like
system accessing the BIOS Data Area in the first 4K requires
a memory mapping. We need to read this to probe the ACPI RSDP.

Additionally check that the BDA has something in it as well
and not a bunch of zeroes.

It is unclear whether this function is truly safe on UEFI
systems, but that is for another day.

Fixes: #27867

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
> It is unclear whether this function is truly safe on UEFI systems, but that is for another day.

I write this because we have a test for this in `tests/arch/x86/info`, but it is only allowed to run on upsquared. This is not good, this test ought to run on any PC-like target including all our QEMU targets. But in QEMU the code to probe the last 128K of the first megabyte results in the emulator suddenly exiting as soon as 0x00000000000f5910 (which is mapped in the page tables). Separate issue, we'll deal with it as an enhancement for 2.5

**Review by andyross — APPROVED** [review]
Makes sense.  I thought I'd convinced myself that this code would only execute during the initial memory mapping environment and didn't need mapping, but maybe that's wrong.

**Comment by andrewboie** [comment]
> Makes sense. I thought I'd convinced myself that this code would only execute during the initial memory mapping environment and didn't need mapping, but maybe that's wrong.

@andyross my paging changes broke this :) 
Before, this code ran with the flat page tables where we had the first 4GB identity mapped, or no page tables on 32-bit. Only later were the runtime page tables installed.
Now we use my build-generated page tables from the beginning, and I deliberately omitted the NULL page from being mapped to catch NULL dereferences.
Would like to get QEMU to exercise this, but I found some other problems. I'll be filing an enhancement on that.

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by chen-png** [comment]
tested, it fixed #27867.

**Pull request merged**
