### PR TITLE
Fix example in sparkfun,serlcd.yaml

### PR DESCRIPTION
**Pull request by cperkulator**
fix documentation to include `-ms`

### CODE REVIEW

**Review by thedjnK — COMMENTED** [review]
Needs commit message and correct sign off line with valid email, commit title must be correctly formatted too, see https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines for details

**Review by henrikbrixandersen — APPROVED** [review]
Looks good, but the compliance check failure needs to be addressed before this can be merged.

**Review by fabiobaltieri — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@cperkulator Any plans to fix the compliance failure?

**Comment by thedjnK** [comment]
ping @cperkulator

**Comment by cperkulator** [comment]
just pushed, hopefully that works. sorry about that!

**Review by decsny — APPROVED** [review]

**Comment by thedjnK** [comment]
@cperkulator there is an issue with the email sign off in the commit message

**Comment by cperkulator** [comment]
@thedjnK looks like this is all passing now. sorry for all the hassle

**Review by thedjnK — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Pull request merged**
