### PR TITLE
Save/restore devicetree's edtlib.EDT object

### LINKED ISSUE #26575: devicetree: need save/restore support for devicetree data
tl;dr: I need the EDT object that's constructed during devicetree processing to be persisted to disk so I can read it back and use its data to generate optimized dependency information to be used in the final application link.

The parts of #26388 related to using devicetree and macros to add dependency information to the device structure work well.  However the actual values of the device handles are not well chosen: devicetree ordinals are captured without regard to what devices are actually used in the application.  Thus there are gaps in the handle space, and dependencies are recorded to nodes that have no corresponding device.

The handle assignment can be cleaned up with a post-process step on `zephyr_prebuilt.elf`, much like what's done for kernel objects and system call support.  The concept is to link that image with the dependency arrays filled in from sections that encode the original ordinals, then to read the arrays from that image and map the ordinal-based handles to handles based on the devices used.  This would also mean that the handle for a specific device could be its offset from the start of the device table, making it trivial to map from the handle to the device pointer.

To accomplish this we'd need to construct the subgraph of the devicetree dependency graph that contains only the root and nodes that are present in the application.  To do that we need the devicetree state that includes the original dependency graph (as well as all the other data, for reasons).

To do that we need a way to save that state to a file in the build area, then load an EDT instance in post-processing.

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Fixes: #26575

This PR uses the standard [pickle](https://docs.python.org/3/library/pickle.html) module to save the devicetree information in a file, where it can be loaded later on in the build.

All that is necessary to restore the EDT object in another Python process are these lines of code, with one caveat:

```
import pickle

with open('/home/mbolivar/zp/zephyr/build/zephyr/edt.pickle', 'rb') as f:
    edt = pickle.load(f)
```

The caveat is that the restoring process needs to have `ZEPHYR_BASE/scripts/dts`  in `sys.path` before calling `pickle.load()`, so that function can `import edtlib` successfully.

### CODE REVIEW

**Review by galak — COMMENTED** [review]
can we tweak sanitycheck or kconfigfunctions.py to load the pickled ver?

**Comment by mbolivar-nordic** [comment]
> can we tweak sanitycheck or kconfigfunctions.py to load the pickled ver?

Good idea, now done with kconfigfunctions. LMK if you think sanitycheck would be good to do too.

**Comment by mbolivar-nordic** [comment]
>  LMK if you think sanitycheck would be good to do too.

I think what I'd like to do is get sanitycheck passing with just kconfigfunctions loading from the pickle file, then convert other in-tree users over to it as a separate PR, so we get two CI runs.

**Comment by mbolivar-nordic** [comment]
The compliance checks are complaining about legacy DT binding syntax.... in the test cases for the legacy binding syntax.

**Review by pabigot — APPROVED** [review]
This is working well for me; thanks.

**Comment by mbolivar-nordic** [comment]
Rebased and reordered commits for better bisectability

**Comment by mbolivar-nordic** [comment]
@galak I don't think the BK or compliance failures are related to this PR

**Comment by galak** [comment]
> @galak I don't think the BK or compliance failures are related to this PR

yeah, I don't get what is going on w/the compliance side

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
@mbolivar so the compliance check failures are introduced by commit a950c45316027d4596eb3c43a7e0897ce9dca1ff in this PR.  Can you look into that.

**Review by galak — CHANGES_REQUESTED** [review]
Need to fix the compliance check errors from devicetree.

**Comment by mbolivar-nordic** [comment]
Ah, I see the issue now. testedtlib had an unrelated test that was failing due to the move for where the warning gets issued. Thanks for tracking that down, it got lost in the noise since the first few lines of error output were about deprecated bindings.

**Review by galak — APPROVED** [review]

**Pull request merged**
