### PR TITLE
modules: hostap: src: add get_version cmd support

### PR DESCRIPTION
**Pull request by LiLongNXP**
Add get_version cmd support for "wifi version" cmd input

### CODE REVIEW

**Comment by gannicus-gj** [comment]
Hi @jukkar , @krish2718 
could you pls take time to review this, thanks

**Comment by krish2718** [comment]
LGTM, but I don't see a PR in hostap that implements the OP, can you please raise one and link using manifest?

**Comment by gannicus-gj** [comment]
> LGTM, but I don't see a PR in hostap that implements the OP, can you please raise one and link using manifest?
it is used in l2 wifi_mgmt.c
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/l2/wifi/wifi_mgmt.c#L741

**Review by jukkar — APPROVED** [review]

**Comment by LiLongNXP** [comment]
> LGTM, but I don't see a PR in hostap that implements the OP, can you please raise one and link using manifest?

hi Chaitanya, 
Since the change is under zephyr, there is no need to change the revision line in west.yml, could you please approve and merge this PR. Thanks.

**Review by krish2718 — APPROVED** [review]

**Pull request merged**
