### PR TITLE
 Revert "dts: Remove unused virtualcom device node from dts" 

### PR DESCRIPTION
**Pull request by jfischer-no**
Revert "dts: Remove unused virtualcom device node from dts" 

Remove CONFIG_UART_CONSOLE_ON_DEV_NAME from prj.conf
since it can be applied from DT_UART_CONSOLE_ON_DEV_NAME.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
What's the purpose of this change?  The sample code expects `CONFIG_UART_CONSOLE_ON_DEV_NAME` to be "CDC_ACM_0".  So not sure I get the point of trying to get it from DTS.  Also, this change will get whatever the board default for "zephyr,console" is set to.  Finally, having the "usb_cdc" device being compatible with the usb controller doesn't make any sense.

**Comment by jfischer-phytec-iot** [comment]
>So not sure I get the point of trying to get it from DTS

e581c31 is valid as long it is possible to obtain `UART_CONSOLE_ON_DEV_NAME` from [DT_UART_CONSOLE_ON_DEV_NAME](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/console/Kconfig#L13). nrf52840 boards do not pass CI, so either this patch or _samples/subsys/usb/console/app.overlay_ should be removed.

>Also, this change will get whatever the board default for "zephyr,console" is set to.

No, will be set to label of usb_cdc node.

**Comment by galak** [comment]
Ah, I think the better solution is to remove *.overlay files from the sample.

**Comment by jfischer-phytec-iot** [comment]
fixed by #17699

**Pull request closed without merging**
