### PR TITLE
samples: enable build only test for nxp_adsp_imx8m

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Test openamp_rsc_table sample also for nxp_adsp_imx8m.

### CODE REVIEW

**Review by carlocaione — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by gopiotr** [comment]
Hi. This PR probably impact on CI stability. Following CI errors are observed:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/5833168088/job/15820004207?pr=61224
https://github.com/zephyrproject-rtos/zephyr/actions/runs/5832264113/job/15817752848?pr=61390

@iuliana-prodan could you please provide fix for this? There is a conflict with board yaml definition here (`only_tags`):
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m.yaml#L7-L10
and with adding `nxp_adsp_imx8m` platform to `integration_platform` to `sample.yaml` where used tag is `ipm`. This cause conflict to Twister, because it try to build this sample for `nxp_adsp_imx8m` platform, but it can't, because this test is excluded by tag.
So, please remove this platform from `integration_platform` list from `samples/subsys/ipc/openamp_rsc_table/sample.yaml` or add `ipm` tag to `boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m.yaml` `only_tags` list.

Alternatively, @fabiobaltieri please revert this commit until fix will be provided.

**Comment by alxelax** [comment]
I see the same issue in my PR: https://github.com/zephyrproject-rtos/zephyr/actions/runs/5832459286/job/15819615833?pr=60831
Cannot pass CI due to this.

**Comment by iuliana-prodan** [comment]
> Hi. This PR probably impacts on CI stability. Following CI errors are observed: https://github.com/zephyrproject-rtos/zephyr/actions/runs/5833168088/job/15820004207?pr=61224 https://github.com/zephyrproject-rtos/zephyr/actions/runs/5832264113/job/15817752848?pr=61390
> 
> @iuliana-prodan could you please provide fix for this? There is a conflict with board yaml definition here (`only_tags`): https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m.yaml#L7-L10 and with adding `nxp_adsp_imx8m` platform to `integration_platform` to `sample.yaml` where used tag is `ipm`. This cause conflict to Twister, because it tries to build this sample for `nxp_adsp_imx8m` platform, but it can't, because this test is excluded by tag. So, please remove this platform from `integration_platform` list from `samples/subsys/ipc/openamp_rsc_table/sample.yaml` or add `ipm` tag to `boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m.yaml` `only_tags` list.
> 
> Alternatively, @fabiobaltieri please revert this commit until fix will be provided.

will fix it asap.

**Comment by iuliana-prodan** [comment]
> > Hi. This PR probably impacts on CI stability. Following CI errors are observed: https://github.com/zephyrproject-rtos/zephyr/actions/runs/5833168088/job/15820004207?pr=61224 https://github.com/zephyrproject-rtos/zephyr/actions/runs/5832264113/job/15817752848?pr=61390
> > @iuliana-prodan could you please provide fix for this? There is a conflict with board yaml definition here (`only_tags`): https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m.yaml#L7-L10 and with adding `nxp_adsp_imx8m` platform to `integration_platform` to `sample.yaml` where used tag is `ipm`. This cause conflict to Twister, because it tries to build this sample for `nxp_adsp_imx8m` platform, but it can't, because this test is excluded by tag. So, please remove this platform from `integration_platform` list from `samples/subsys/ipc/openamp_rsc_table/sample.yaml` or add `ipm` tag to `boards/xtensa/nxp_adsp_imx8m/nxp_adsp_imx8m.yaml` `only_tags` list.
> > Alternatively, @fabiobaltieri please revert this commit until fix will be provided.
> 
> will fix it asap.

Done: https://github.com/zephyrproject-rtos/zephyr/pull/61426
Sorry for any inconvenience

**Comment by fabiobaltieri** [comment]
> Alternatively, @fabiobaltieri please revert this commit until fix will be provided.

FYI it would have been more efficient for everyone if you had created a fix (or rollback) yourself. You did all the troubleshooting work (thanks for that), was probably less work to just send a PR than writing the whole story here.

**Pull request merged**
