### PR TITLE
Bluetooth: Audio: Shell: Audio shell improvements

### LINKED ISSUE #50944: LE Audio: Unicast client shell support for multiple streams in same unicast group
**Is your enhancement proposal related to a problem? Please describe.**
The current implementation (sha: 61d6532014c25fce5ea99662bd9e436ba0c89190) does not support configuring multiple audio streams as the unicast client. This is due to how the unicast group is created as part of the QoS configure operation (`cmd_qos`), which just sets a single stream. 

**Describe the solution you'd like**
The creating of the unicast group should at the very least use all configured streams, so that the user can configure multiple streams with `audio config` before calling `audio qos`. 

**Describe alternatives you've considered**
Alternatively we add a new command specifically for creating the unicast group to what the user want. 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
This commits allows for setting up multiple streams in
a single CIG as the unicast client.

It fixes an issue with the unicast server not using
the configured QoS when transmitting audio data.

Improves upon setting the preset for the different
type of streams.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/50944

### CODE REVIEW

**Comment by jhedberg** [comment]
Just looking at the content of the commit message, and number of lines changed, seems like this should be split up into multiple commute? Or does all of this rea

**Comment by Thalley** [comment]
> Just looking at the content of the commit message, and number of lines changed, seems like this should be split up into multiple commute? Or does all of this really hang together and would break bisectability if split up?

To some extent the fixes are quite highly coupled. 

There are 3 things fixed by this:
1) allows for setting up multiple streams in
a single CIG as the unicast client.

2) It fixes an issue with the unicast server not using
the configured QoS when transmitting audio data.

3) Improves upon setting the preset for the different
type of streams.

3) was done as part of fixing 1), but can technically be moved to its own change. 2) was also done as part of fixing 1), and while it technically could be fixed in its own commit after 1), the changes to 1) would basically revert all the changes as everything related to the Codec and QoS was refactored. 

I could move 3) to it's own commit before this, but that change won't really do anything until 1) is applied. 

I think my conclusion is that the changes could be moved to separate commits and 1) applied last, but the commits separately won't really have any affect and/or most of the changes would be refactored anyways. IMO this is better as a single commit.

**Comment by Thalley** [comment]
Rebased to solve merge conflict

**Review by larsgk — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by larsgk — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
