### PR TITLE
drivers: sensor: add MAX31855

### PR DESCRIPTION
**Pull request by ChristianHirsch**
add [MAX31855](https://datasheets.maximintegrated.com/en/ds/MAX31855.pdf) cold-junction compensated thermocouple-to-digital converter sensor driver and sample

### CODE REVIEW

**Comment by ChristianHirsch** [comment]
I have one open question: based on the [datasheet](https://datasheets.maximintegrated.com/en/ds/MAX31855.pdf) page 10, bit 16 indicates an error. before fetching the samples, I check the this bit, and if set it will return an error. but what is the proper error code for that?

**Comment by ChristianHirsch** [comment]
@MaureenHelm I'm a little bit confused: the Shippable status if FAILED. But I don't know if this is a problem with this PR. The failed testcases complain about missing defines for the `fxos8700` sensor. Can I ignore the failed tests?

**Comment by ChristianHirsch** [comment]
@nashif @galak anyone who can help me?

**Comment by ChristianHirsch** [comment]
@nashif why is this considered stale if I am waiting for reviews and do not get any answeres?

**Comment by nixward** [comment]
Hi @ChristianHirsch it looks like you need to rebase your branch to get rid of the conflicts. The Zephyr Slack area is a good place to talk to potential reviewers.

**Pull request closed without merging**
