### PR TITLE
boards: fix dts for nrf5340 and nrf9160

### PR DESCRIPTION
**Pull request by Laczen**
move kmu under flash_controller and power under clock
move sram0_s and sram0_ns under sram_image

this removes dts errors

Signed-off-by: Laczen JMS <laczenjms@gmail.com>

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Make the changes you describe don't make a lot of sense as the hierarchy in devicetree tends to have meaning.

So saying that the KMU is a child of the flash-controller isn't logically correct.  Same for Clock/Power, etc.

NAK.

**Comment by Laczen** [comment]
> Make the changes you describe don't make a lot of sense as the hierarchy in devicetree tends to have meaning.
> 
> So saying that the KMU is a child of the flash-controller isn't logically correct. Same for Clock/Power, etc.
> 
> NAK.

The register for the flash controller and the KMU is the same, which one should be considered the client or the parent is up for debate. However if we ever wish to use the KMU and the flash controller at the same time we should be able to lock access to the register. With the change an access to the KMU would require to lock the flash controller and this is OK.

The same is valid for the clock/power.

**Comment by galak** [comment]
> > Make the changes you describe don't make a lot of sense as the hierarchy in devicetree tends to have meaning.
> > So saying that the KMU is a child of the flash-controller isn't logically correct. Same for Clock/Power, etc.
> > NAK.
> 
> The register for the flash controller and the KMU is the same, which one should be considered the client or the parent is up for debate. However if we ever wish to use the KMU and the flash controller at the same time we should be able to lock access to the register. With the change an access to the KMU would require to lock the flash controller and this is OK.
> 
> The same is valid for the clock/power.

While they are at the same register address, I don't think that necessarily makes the relationship a child/parent one.  I leave it to the nordic guys to chime in on this as the experts for their SoC.  [@carlescufi @ioannisg ...]

**Comment by carlescufi** [comment]
> While they are at the same register address, I don't think that necessarily makes the relationship a child/parent one. I leave it to the nordic guys to chime in on this as the experts for their SoC. [@carlescufi @ioannisg ...]

@anangl and @ioannisg should chime in here.

**Comment by frkv** [comment]
The KMU hardware peripheral is coupled with using KMU-specific registers in UICR and is only indirectly coupled to the NVMC (because UICR is dependent on NVMC)

To be able to use the KMU functionality there is a distinction between "key storing" and "key pushing".

Key storing: registers in UICR and KMU hardware peripheral is used to load key to a specific flash location for the KMU storage and to write permissions. _Do note that the NVMC (flash controller) needs to be enabled to be able to write to UICR slots_.

Key pushing: Only the KMU hardware peripheral is used to enact the pushing of the key on the BUS interface.

I think that the grouping of KMU together with the flash controller may be a bit to removed. I'm sure this is because of the 0x39000 range, but I'm not too skilled in DTS to know if this should have any say on the grouping...

**Comment by Laczen** [comment]
@galak, I think someone with dts experience is required to shed a light on this problem.

The question is very simple: If you have two hardware devices that share the same register, how should these devices be defined in the dts ?

**Comment by Laczen** [comment]
> The KMU hardware peripheral is coupled with using KMU-specific registers in UICR and is only indirectly coupled to the NVMC (because UICR is dependent on NVMC)
> 
> To be able to use the KMU functionality there is a distinction between "key storing" and "key pushing".
> 
> Key storing: registers in UICR and KMU hardware peripheral is used to load key to a specific flash location for the KMU storage and to write permissions. _Do note that the NVMC (flash controller) needs to be enabled to be able to write to UICR slots_.
> 
> Key pushing: Only the KMU hardware peripheral is used to enact the pushing of the key on the BUS interface.
> 
> I think that the grouping of KMU together with the flash controller may be a bit too far removed. I'm sure this is because of the 0x39000 range, but I'm not too skilled in DTS to know if this should have any say on the grouping...

@frkv, thanks for your taughts and background on the kmu.

**Pull request closed without merging**
