### PR TITLE
NRFX-5977 Add mbox_error_cases

### PR DESCRIPTION
**Pull request by nordic-segl**
1. Add negative test cases for the MBOX driver.
    Confirm that driver implementation is aligned with
    the MBOX API documentation available at
    https://docs.zephyrproject.org/latest/hardware/peripherals/mbox.html
    
    Enable test execution on nRF54H20 Application and PPR cores.

2. According to the official MBOX API documentation 
    mbox_sen() shall return
    -EMSGSIZE – If the supplied data size is unsupported by the driver.
    
    Fix error code returned by the mbox_send().

3. Add overlay that enables execution of mbox_error_cases on
    nrf54l15pdk/nrf54l15/cpuapp.

### CODE REVIEW

**Comment by nordic-segl** [comment]
nrf54h20/cpuapp - works in upstream and NCS
nrf54h20/cpuppr - works in NCS (I tested only there)
nrf54l15/cpuapp - fails in upstream Zephyr (MBOX driver for 54l15 is not ported to NCS)

**Comment by nordic-segl** [comment]
FYI: @nordic-piks

**Comment by nordic-segl** [comment]
I get BUS FAULT on nrf54L15 Application core
```
START - test_05c_mbox_set_enabled_on_already_enabled_rx_channel
E: ***** BUS FAULT *****
E:   Precise data bus error
E:   BFAR Address: 0x5004c304
E: r0/a1:  0x00000000  r1/a2:  0x0000000f  r2/a3:  0x00008000
E: r3/a4:  0x5004c000 r12/ip:  0x000080f7 r14/lr:  0x0000095b
E:  xpsr:  0x01000200
E: Faulting instruction address (r15/pc): 0x000080ac
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20000160 (test_05c_mbox_set_enabled_on_al)
E: Halting system
```

**Review by nordic-piks — APPROVED** [review]

**Comment by nordic-segl** [comment]
Dear reviewers, please find some time to do the review.

**Comment by nordic-segl** [comment]
rebased on main@ad3e941ad3ed9e3e2f9032b0151558a948e99fb9

**Review by carlocaione — APPROVED** [review]

**Review by jaz1-nordic — APPROVED** [review]

**Review by masz-nordic — APPROVED** [review]

**Pull request merged**
