### PR TITLE
Introduce MBOX API

### LINKED ISSUE #38609: RFC: API Change: IPM
### Problem Description:
The IPM subsystem is used to send signals (or small messages) to other processors / CPU clusters. The current API has one big limitation: it assumes that the platform has only two CPUs (or one single channel). Looking at the current API the `ipm_send()` function doesn't take any parameter in input related to the destination CPU and the `ipm_register_callback()` function is only able to register one single callback, so the implicit assumption is that the IPM device is sending / receiving signals to / from a single remote endpoint / CPU.

When the hardware allows multiple channels (that is multiple CPUs) the solution adopted for example by the NRFX IPC driver was to allocate several instances of the same device (see https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/ipm/ipm_nrfx_ipc.c#L236) so that (among other things) was possible to register a different callback for each instance. This is of course highly discouraged when using DT because the IPM device instance should have only one single node into the DT.

### Proposed change:
The proposed change is to add a new `channel` parameter to the `ipm_send()` and `ipm_register_callback()` functions so that the user driver can send data through a specific channel on TX and hookup a callback on a specific channel on RX. We are also introducing a couple of DT helpers to allow the user devices to specify the channels of interest directly into the DT.

### Detailed RFC:
Everything is detailed in the PR https://github.com/zephyrproject-rtos/zephyr/pull/38523 and in the `ipm.h` file at https://github.com/zephyrproject-rtos/zephyr/blob/ea7831e7b3f20371181f976ae610dd5730b5c4b4/include/drivers/ipm.h#L22-L57

### PR DESCRIPTION
**Pull request by carlocaione**
As discussed during the latest TSC meeting about #38523 I'm here introducing a new MBOX API. I'm basically leveraging and extending the IPM API to support multiple channels and DT.

In this PR the NRFX driver is converted to use the new API and a sample running on the `nrf5340-dk` board is added to show the API functionality.

For all the DT helpers the proper tests are also added.

### CODE REVIEW

**Review by hubertmis — APPROVED** [review]
I like new mbox API very much now :+1:

**Review by arnopo — COMMENTED** [review]
minor comments else LGTM

**Review by arnopo — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by tejlmand — COMMENTED** [review]
Should the samples targetting `nrf5340dk` go under board specific samples ?

**Review by masz-nordic — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]

**Review by tejlmand — APPROVED** [review]
This has been agreed on Discord to address separately at later point.
https://github.com/zephyrproject-rtos/zephyr/pull/39470#discussion_r737503003

**Review by nashif — APPROVED** [review]

**Comment by lenghonglin** [comment]
if add `mbox` for multiple channels rather than modify `ipm` api.  
how about (static_vrings_mi)[https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/ipc/ipc_service/static_vrings_mi] this sample? Is it necessary to use the mBox interface to implement?

**Comment by carlocaione** [comment]
> how about [static_vrings_mi](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/ipc/ipc_service/static_vrings_mi) this sample? Is it necessary to use the mBox interface to implement?

The `static_vrings_mi` is still using IPM, but I recently introduced a new backend (see #40365) that is using the MBOX interface instead of IPM.

**Comment by lenghonglin** [comment]
> 
I wonder why not modify `ipm` and add an `mbox` driver instead.

**Comment by carlocaione** [comment]
> I wonder why not modify ipm and add an mbox driver instead.

This was extensively discussed. It was preferred to add a new MBOX API supporting multiple channels instead of breaking the stable IPM API.

**Pull request merged**
