### PR TITLE
drivers: Add functions to convert sensor value to and from float.

### PR DESCRIPTION
**Pull request by me-axentia**
Give users option to use single precision functions instead of existing double precision functions (for constrained systems).

Signed-off-by: Mattias Eriksson <me@axentia.se>

### CODE REVIEW

**Review by caspermeijn — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by gmarull — DISMISSED** [review]

**Review by avisconti — DISMISSED** [review]

**Comment by me-axentia** [comment]
Sorry about all the check fails. First time contributor.

**Comment by henrikbrixandersen** [comment]
> Sorry about all the check fails. First time contributor.

No problem. In general there's no reason to re-request reviews from people who already approved the PR unless you have made substantial changes to the contents.

**Comment by me-axentia** [comment]
> > Sorry about all the check fails. First time contributor.
> 
> No problem. In general there's no reason to re-request reviews from people who already approved the PR unless you have made substantial changes to the contents.

Oh I see.
All checks finally passed. No further action required from me, it is up to someone to decide if this should be merged or not?

**Comment by henrikbrixandersen** [comment]
> Oh I see. All checks finally passed. No further action required from me, it is up to someone to decide if this should be merged or not?

Correct. It will likely be processed after New Years. Thank you for your contribution!

**Comment by ycsin** [comment]
Is a check similar to #39229 required?

**Review by ycsin — CHANGES_REQUESTED** [review]
> Is a check similar to #39229 required?

**Comment by henrikbrixandersen** [comment]
@me-axentia Please rebase.

**Pull request closed without merging**
