### PR TITLE
boards: nxp: Add 'supported: flash'

### PR DESCRIPTION
**Pull request by butok**
- Adds 'supported: flash' to all NXP board .yaml with enabled flash controller support.
- Sorts supported features alphabetically.

### CODE REVIEW

**Review by manuargue — APPROVED** [review]
+1 for S32 changes. The rest looks good too, although I'm not sure how necessary is and how long going to last the alphabetical order...

**Comment by butok** [comment]
> +1 for S32 changes. The rest looks good too, although I'm not sure how necessary is and how long going to last the alphabetical order...

Ideally, all lists should be ordered in some way.
It brings a little order to the chaos, making it easier for people to search.

**Review by dleach02 — APPROVED** [review]

**Comment by danieldegrasse** [comment]
Do we ever use "depends_on" with the flash tag in tree? I'm grepping for it like this:

`grep -r -A 1 --include="*.yaml" "depends_on" $ZEPHYR_BASE | grep -B 1 "flash"`

I don't currently see any examples. Is this prep work for using the `flash` tag on tests?

**Comment by butok** [comment]
> Do we ever use "depends_on" with the flash tag in tree? I'm grepping for it like this:
> 
> `grep -r -A 1 --include="*.yaml" "depends_on" $ZEPHYR_BASE | grep -B 1 "flash"`
> 
> I don't currently see any examples. Is this prep work for using the `flash` tag on tests?

Step by step. The final goal is to use it for flash driver tests. Right now they use 'platform_allow'.

**Pull request merged**
