### PR TITLE
settings: (NVS) fetch sector size from driver

### PR DESCRIPTION
**Pull request by nvlsianpu**
NVS back-end initialization should fetch size of the flash erase blocks
from the flash API instead of DT. This allows to work well when used
storage partition is not located in embedded memory.

NVS back-end sector multiplier configuration was set to 8K as
DT value for native posix targets
flash sector sizes is 1 B, while its flash driver supports 8k.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@vanwinkeljan I wounder whether erase-block-size = <1>;  (see native_posix.dts) is intentionally set to 1.
The value is OK as posix flash "hardware" relay supports any alignment, but I'm just curious whether that was the reason for it.

**Review by kapi-no — APPROVED** [review]

**Comment by erwango** [comment]
I had a test on `sample/bluetooth/peripheral` using nucleo_f429zi + x_nucleo_idb05a1.
I get following error:
```
[00:00:00.006,000] <err> fs_nvs: Invalid sector size
[00:00:00.006,000] <err> bt_settings: settings_subsys_init failed (err -22)
```
Issue is `fs->sector_size = 0` in nvs_init, which is due to:
```
	nvs_sector_size = CONFIG_SETTINGS_NVS_SECTOR_SIZE_MULT *
			  hw_flash_sector.fs_size;
```
With `CONFIG_SETTINGS_NVS_SECTOR_SIZE_MULT` set to 1.
Then I'm loosing track.

Tbh, digging into it, I feel I need to cross check this is actually a regression

**Review by ioannisg — APPROVED** [review]

**Comment by Laczen** [comment]
@nvlsianpu, maybe this problem is more general (PR #19844 and ISSUE #19438) and it is not a good idea to use the driver to get the block size.
A solution might be that each of the fs (nffs, fcb, nvs, littlefs, ...) but also mcuboot would set a block size (or a minimal block size) that makes sense for the fs. The initialization could check if the proposed block size is OK from a flash point of view (multiple of the erase size) and if not increase the block size to get it OK. The number of blocks could then be retrieved by dividing the partition size by the block size.

**Comment by nvlsianpu** [comment]
What @erwango showed is bugs in flash driver implementation manifestation.

@Laczen I'm fine with that sometimes it would be better to provide block size for a flash client directly as you mention (but not sure whether for each client it would be better, especially mcuboot can operate on irregular flash layout well). Then this client block size should be checked with block size value supported by the flash driver - and the last value should be fetched form flash API (over flash_area API if needed).

Is what you men is to left behind CONFIG_SETTINGS_NVS_SECTOR_SIZE_MULT and use a new property like CONFIG_SETTINGS_NVS_SECTOR_SIZE?

**Comment by erwango** [comment]
> What @erwango showed is bugs in flash driver implementation manifestation.

Agreed. I'm about to raise a separate issue.

**Comment by Laczen** [comment]
@nvlsianpu, you are right about what I mean. For FCB and NVS I would say that they would require at least a sector size of 1kB (because otherwise it would be very limiting on the data that can be stored), for littlefs and nffs I would expect something of about 4kB (or more). For MCUboot I would also expect that there is some minimum sector size (at least 128bytes for encryption). These are properties that are not reflected in the driver, and if the driver would allow very small values we would get stuck.

So indeed, I would propose a property like CONFIG_NVS_SECTOR_SIZE, but to set a minimum value on this: CONFIG_NVS_MIN_SECTOR_SIZE default 1024, for a driver that would allow smaller "block erase sizes" 1024 would be selected, while for a driver that only allows 4096, 4096 would be seleced.

What @erwango showed is indeed a bug, but even without this bug it would be required to fiddle with the SECTOR_MULTIPLIER to get acceptable sector sizes.

**Comment by Laczen** [comment]
Maybe NVS_MIN_SECTOR_SIZE should not be a configuration value, but a define in nvs.h.

**Comment by vanwinkeljan** [comment]
> @vanwinkeljan I wounder whether erase-block-size = <1>; (see native_posix.dts) is intentionally set to 1.
The value is OK as posix flash "hardware" relay supports any alignment, but I'm just curious whether that was the reason for it.

@nvlsianpu Yes that was the reason, I just picked one as it is the minimum size supported.

**Review by erwango — APPROVED** [review]
tested ok on nucleo_f429zi (at least NVS init)

**Comment by erwango** [comment]
@nvlsianpu, discussing with @Laczen, it's possible that and issue remains.
Remaining issue on nucleo_f429zi was a partition configuration issue since storage partition was assign on a single NVS slot (while NVS expects minimum 2).
Error reported was `fs_nvs: Invalid sector size` logical since `hw_flash_sector.fs_size` was reported to 0 instead of 64 (as configured in dts).
If `hw_flash_sector.fs_size` was reported to 64, NVS would have been able to report the actual problem which was a sector count issue.

Can you cross check that there is no underlying issue in this fix which prevent to report the correct sector size ?

**Review by Laczen — APPROVED** [review]

**Review by vanwinkeljan — APPROVED** [review]

**Pull request merged**
