### PR TITLE
Bluetooth: Audio: Add support for encrypted broadcast

### PR DESCRIPTION
**Pull request by Thalley**
Add support for adding a broadcast code to the broadcast source.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

### CODE REVIEW

**Comment by Thalley** [comment]
@cvinayak Did the ZLL support encrypted broadcast? In other words, can I extend the BSIM tests with encryption?

**Comment by Thalley** [comment]
> @cvinayak Did the ZLL support encrypted broadcast? In other words, can I extend the BSIM tests with encryption?

It seems not :)

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by alexsven — APPROVED** [review]

**Review by asbjornsabo — APPROVED** [review]
LGTM

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
