### PR TITLE
Bluetooth: LC3: Fix prefer and streaming context macros

### PR DESCRIPTION
**Pull request by Thalley**
Fix the BT_CODEC_LC3_META (prefer context) and
BT_CODEC_LC3_CONFIG_META (streaming context) macros, as
they did not properly set the right values due to missing
parenthesis.

Also added casts to `uint8_t` to avoid compiler warnings on
e.g. GCC when assigning a non uint8_t value to a uint8_t array.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

### CODE REVIEW

**Review by cvinayak — CHANGES_REQUESTED** [review]
What about other place like here:
https://github.com/zephyrproject-rtos/zephyr/blob/a703cbe9ce1315f2460d86de7ee8a55190cf7995/include/zephyr/bluetooth/audio/lc3.h#L259-L267

**Comment by Thalley** [comment]
> What about other place like here:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/a703cbe9ce1315f2460d86de7ee8a55190cf7995/include/zephyr/bluetooth/audio/lc3.h#L259-L267

Hmm, for some reason these do not give the same warning error when building for some reason. Possible the cast to `uint8_t` is not needed then?

**Comment by MariuszSkamra** [comment]
> Hmm, for some reason these do not give the same warning error when building for some reason. Possible the cast to `uint8_t` is not needed then?

Indeed, I guess that fix for missing brackets would be sufficient

**Comment by Thalley** [comment]
> > Hmm, for some reason these do not give the same warning error when building for some reason. Possible the cast to `uint8_t` is not needed then?
> 
> Indeed, I guess that fix for missing brackets would be sufficient

Indeed. I'll try to remove the cast from my fixes in this PR and see if just adding the parenthesis is enough.

**Comment by Thalley** [comment]
Updated multiple macros to follow the same style and to ensure correctness.

**Comment by Thalley** [comment]
These macros should be updated with the SYS_ENCODE macros from https://github.com/zephyrproject-rtos/zephyr/pull/49683 at some point as well

**Review by cvinayak — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

**Pull request merged**
