### PR TITLE
dts: flash: nxp-iap: cleanups and updates.

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by nashif** [comment]
@galak, @MaureenHelm  still relevant? needs to be rebased.

**Comment by galak** [comment]
> @galak, @MaureenHelm still relevant? needs to be rebased.

rebased.  Should still be relevant.

**Comment by agansari** [comment]
> > @galak, @MaureenHelm still relevant? needs to be rebased.
> 
> rebased. Should still be relevant.

There is also the actual driver https://github.com/zephyrproject-rtos/zephyr/pull/26609

**Comment by galak** [comment]
> There is also the actual driver #26609

thanks for pointing that out.  Let me see if we should merge some of my commits in there.

**Pull request closed without merging**
