### PR TITLE
Fix lptim sys clock driver

### PR DESCRIPTION
**Pull request by bcluzel**
I use Zephyr with a stm32wl and lptim as the system clock source.
With Zephyr 3.6 I encountered 2 problems that I solved with these PR commits.

## Product never sleeping more than a few ticks

Caused by the line "next_arr = next_arr - 1;" making the condition "((autoreload - lp_time) < LPTIM_GUARD_VALUE)" line 276 always true which cause the timer to never reconfigure.

## Wrong Time measurement when using prescaler

When using the prescaler (tested with 16 and 128 with the SYS_CLOCK_TICKS_PER_SEC configured by default), I realized the time measurement was wrong (hours printed on the logs in few seconds of real time).
Saw accumulated_lptim_cnt getting wrongly incremented with MAX_UINT16 line 146. 
So far I understood that when sys_clock_announce is called line 156 in the isr, it ends up calling sys_clock_set_timeout with the max timeout possible and if autoreload_ready is true it does not reconfigure immediately the ARR. 
I fixed it by adding "autoreload_ready = false;" line 155.
  
This pr is fixing the two problems on my side.

### CODE REVIEW

**Comment by erwango** [comment]
> With Zephyr 3.6 I encountered 2 problems that I solved with these PR commits.

Do you mean these were regressions vs 3.5 ?

**Comment by bcluzel** [comment]
I just realized that I forgot to mention some important information:
I use CONFIG_PM | CONFIG_PM_DEVICE | CONFIG_PM_DEVICE_RUNTIME | CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE=n.

If I revert #66291 it also fix the issue.

**Comment by FRASTM** [comment]
@bcluzel, could you please detail how you display "hours printed on the logs in few seconds of real time"


In the PR #66291  the  z_cpus_pm_state[id].exit_latency_us  is setting the timeout value, and the stm32wl.dtsi does not define a 		_exit_latency_us_  so 0 is the default value
Are you able to test when a `exit-latency-us = <20>; ` is defined for the power-states of the stm32wl.dtsi

**Comment by bcluzel** [comment]
@FRASTM 
On my main project where I have many peripherals using the pm_device api if I don't  add "autoreload_ready = false;" line 155 i end up with logs like this at initialization:
```
[00:17:04.136,000] <inf> fs_nvs: 4 Sectors of 2048 bytes
[00:17:04.136,000] <inf> fs_nvs: alloc wra: 3, 778
[00:17:04.136,000] <inf> fs_nvs: data wra: 3, 430
[00:21:20.160,000] <inf> storage: App storage restored
[00:21:20.160,000] <inf> sensors_srv: Init start
[00:34:09.414,000] <inf> network: Init start
[01:08:18.562,000] <inf> plm: Init ok
```

The init procedure of our product take 2s in real time. But if you check the logs timestamps you can see the problem.

**Comment by bcluzel** [comment]
I also tested with exit-latency-us = <20>; added on all the power states and it does not solve the problem.

**Comment by FRASTM** [comment]
> I also tested with exit-latency-us = <20>; added on all the power states and it does not solve the problem.

Thanks, 
in between, I have found a mismatch in the LPTIM_CLOCK_SRC selection : PR #70784 
It can help restoring the power consumption

**Comment by bcluzel** [comment]
Converting this pr to a draft because I'm doing extensive testing and I'm not sure about the "autoreload_ready = false;".

**Pull request closed without merging**
