### PR TITLE
gecko: Fix sdid for xg27 part

### PR DESCRIPTION
**Pull request by silabs-ZoltanH**
Please see the original slcc sdid value:
https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.3/platform/Device/component/efr32bg27c140f768im40.slcc#L70

### CODE REVIEW

**Comment by fkokosinski** [comment]
Ok, so it looks like we have a regression for BG27 with your HAL changes:
```
samples/synchronization/sample.kernel.synchronization (efr32bg27_brd2602a:samples/synchronization/sample.kernel.synchronization) with error 
```

Could you take a look at it @zohavas?

**Comment by zohavas** [comment]
I looked and it seems, that with the wrong sdid, the commit missed the needed folder and config as well.
I will update the PR.

**Comment by zohavas** [comment]
@fkokosinski could you please rerun the test? I have updated the silabs_hal PR and on my local computer it is building correctly that application.

**Review by fkokosinski — APPROVED** [review]

**Comment by zohavas** [comment]
@fkokosinski do I need to do anything more to get this PR merged?

**Review by tgorochowik — APPROVED** [review]
Looks good, thanks

**Pull request merged**
