### PR TITLE
Lis2dh fix

### PR DESCRIPTION
**Pull request by avisconti**
This PR is fixing the bug reported into PR 7912 in the proper way, i.e. using the AUTOINCREMENT bit for I2C burst read/write operations.

### CODE REVIEW

**Review by erwango — APPROVED** [review]
+1 but would be good it is also verified by @ekalugin

**Comment by ekalugin** [comment]
+1 if it was verified with latest zephyr. On 1.8 this fix doesn't work for me.

**Comment by avisconti** [comment]
@ekalugin 
I tested it on top of 1.12.0-rc2
Not sure why on 1.8 shouldn't work... I could give a try.
But I'm pretty confident that AUTOINCREMENT is the thing that was missing. What is happening to you exactly?

**Comment by avisconti** [comment]
@ekalugin 
Did you apply the commit on top of 1.8 w/o issues? Or did you do the modifications manually?

**Comment by ekalugin** [comment]
It looks like it should be the missing part indeed, but for some reason I still see the same issue with autoincrement - driver cannot read anything feasible from the accelerometer registers.

I just manually changed the 1.8 code to enable autoincrement.

**Comment by avisconti** [comment]
For both burst_read and burst_write?

**Comment by avisconti** [comment]
I have access to your github repo. Can you possibly push a branch with autoincrement changes?
Thx!

**Comment by ekalugin** [comment]
Only for burst read (As well as my patch is only for reading function).
Just tried to add LIS2DH_AUTOINCREMENT_ADDR to burst_write, and as expected there were same result. Not sure if changes in burst_write could be anyhow critical since they are located only in driver init.

**Comment by ekalugin** [comment]
These autoincrement changes that I tried are trivial, they are just identical to one that you've proposed:

    status = lis2dh_burst_read(dev, LIS2DH_REG_STATUS |
                     LIS2DH_AUTOINCREMENT_ADDR,
                     lis2dh->sample.raw,
                     sizeof(lis2dh->sample.raw));

**Comment by avisconti** [comment]
The problem with burst_write w/o increment is that the init function is not initializing the register as expected. But for some reason it seems is not a problem even in my case. Nevertheless, it's a mistake because it is not writing all the registers, so we need to fix it.

**Comment by ekalugin** [comment]
For me replacement of burst_read was enough to make the driver work correctly. From other hand I don't observe any effect from adding LIS2DH_AUTOINCREMENT_ADDR flag.

**Comment by avisconti** [comment]
I'm not able to spot your issue. Maybe in zephyr 1.8 version of lis2dh there is something else that is preventing lis2dh i2c burst to work.

Anyway, I'm repushing the fix, because in this way is not working for SPI.

**Review by nashif — APPROVED** [review]

**Pull request merged**
