### PR TITLE
Bluetooth: Advertising API enhancements

### PR DESCRIPTION
**Pull request by jhedberg**
Three enhancements related to the advertising API. The first one adds an option to force advertising using the identity address. The second one removes the own_addr parameter which was largely a work-around/hack that has no in-tree users anymore. The third patch adds a new Kconfig debug option for mesh to take advantage of the new advertising option.

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by sjanc — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
OK I've reviewed this. The `own_addr` removal might be an issue for out-of-tree code but I see no reason to keep it either, so I'm all for removing it. The new option is also fine.

**Comment by jhedberg** [comment]
> OK I've reviewed this. The own_addr removal might be an issue for out-of-tree code but I see no reason to keep it either, so I'm all for removing it. The new option is also fine.

@carlescufi I'm not sure if we're considering this a formally stable API yet. I also doubt that anyone has started using it since it only supported NRPAs and was created for a very specific corner case. Because of this I'd like to get rid of it so we don't end up with it in the LTS release. You didn't explicitly say that you object to this, yet you marked as "request changes"?

**Review by carlescufi — APPROVED** [review]
Sorry @jhedberg, I meant to approve it!

**Pull request merged**
