### PR TITLE
boards: iotdk: add mpu and fpu configuration

### LINKED ISSUE #15483: add mpu and fpu support for arc iotdk
ARC iotdk is equipped with hardware fpu and ARC MPUv2.  The current support doesn't include the configuration of MPU and fpu.

### PR DESCRIPTION
**Pull request by vonhust**
* iotdk supports fpu and mpu

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

Fixes #15483

### CODE REVIEW

**Review by ruuddw — APPROVED** [review]

**Comment by ruuddw** [comment]
Though issue #15483 mentions enhancement, this PR actually contains a fix (incorrect SPI base address) as well, hence the backport label.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
@vonhust looks like a merge conflict needs to get resolved.

**Comment by galak** [comment]
> @vonhust looks like a merge conflict needs to get resolved.

ping @vonhust

**Comment by vonhust** [comment]
> > @vonhust looks like a merge conflict needs to get resolved.
> 
> ping @vonhust

sorry for delay. already made an update

**Pull request merged**
