### PR TITLE
drivers: ns16550: remove parent init level dependency

### LINKED ISSUE #62717: upsquared: tests/subsys/logging/log_immediate/logging.log_immediate fail
**Describe the bug**
Out of 2 tests in the test suite, 2 fail.
`tests/subsys/logging/log_immediate/logging.log_immediate`
and
`tests/subsys/logging/log_immediate/logging.log_immediate.clean_output`
fails.

**To Reproduce**
```twister --device-testing --hardware-map up2.map -T tests/subsys/logging/log_immediate/ -vv```

**Logs and console output**
```
DEBUG   - DEVICE: >>Checking Media Presence......
DEBUG   - DEVICE: >>Media Present......
DEBUG   - DEVICE: Downloading NBP file...
DEBUG   - DEVICE: ASSERTION FAIL [device_is_ready(uart_dev)] @ WEST_TOPDIR/zephyr/subsys/logging/backends/log_backend_uart.c:127
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Succeed to download NBP file.
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: RSDP found at 0x79c2e000
DEBUG   - DEVICE: Zeroing 4972568 bytes of memory at 0x110000
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 65536 data bytes to 0x100000 from image offset 32768
DEBUG   - DEVICE: Copying 2265056 data bytes to 0x5ce020 from image offset 98304
DEBUG   - DEVICE: Jumping to Entry Point: 0x1137 (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: ASSERTION FAIL [device_is_ready(uart_dev)] @ WEST_TOPDIR/zephyr/subsys/logging/backends/log_backend_uart.c:127
DEBUG   - Timed out while monitoring serial output on up_squared
DEBUG   - Process ssh -o StrictHostKeyChecking=no -tt zephyr@10.123.239.214 stty raw 115200 -F /dev/ttyUP2 && cat /dev/ttyUP2_2 terminated outs: None errs None
DEBUG   - Expected suite names:['log_immediate', 'log_immediate']
DEBUG   - Detected suite names:[]
DEBUG   - run status: up_squared/tests/subsys/logging/log_immediate/logging.log_immediate failed
INFO    - 1/2 up_squared                tests/subsys/logging/log_immediate/logging.log_immediate  FAILED Timeout (device: up2_2, 90.201s)
ERROR   - see: /home/zephyr/zephyrproject/zephyr/twister-out/up_squared/tests/subsys/logging/log_immediate/logging.log_immediate/handler.log
DEBUG   - Timed out while monitoring serial output on up_squared
DEBUG   - Process ssh -o StrictHostKeyChecking=no -tt zephyr@10.123.239.214 stty raw 115200 -F /dev/ttyUP2 && cat /dev/ttyUP2 terminated outs: None errs None
DEBUG   - Expected suite names:['log_immediate', 'log_immediate']
DEBUG   - Detected suite names:[]
DEBUG   - run status: up_squared/tests/subsys/logging/log_immediate/logging.log_immediate.clean_output failed
INFO    - 2/2 up_squared                tests/subsys/logging/log_immediate/logging.log_immediate.clean_output  FAILED Timeout (device: up2, 90.365s)
ERROR   - see: /home/zephyr/zephyrproject/zephyr/twister-out/up_squared/tests/subsys/logging/log_immediate/logging.log_immediate.clean_output/handler.log

INFO    - 2 test scenarios (2 test instances) selected, 0 configurations skipped (0 by static filter, 0 at runtime).
--------------------------------
Total test suites: 2
Total test cases: 2
Executed test cases: 2
Skipped test cases: 0
Completed test suites: 2
Passing test suites: 0
Failing test suites: 2
Skipped test suites: 0
Skipped test suites (runtime): 0
Skipped test suites (filter): 0
Errors: 0
--------------------------------
INFO    - 0 of 2 test configurations passed (0.00%), 2 failed, 0 errored, 0 skipped with 0 warnings in 103.30 seconds
INFO    - In total 2 test cases were executed, 0 skipped on 1 out of total 617 platforms (0.16%)
INFO    - 2 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board      | ID    |   Counter |
|------------|-------|-----------|
| up_squared | up2   |         1 |
| up_squared | up2_2 |         1 |
INFO    - Saving reports...
INFO    - Writing JSON report /home/zephyr/zephyrproject/zephyr/twister-out/twister.json
INFO    - Writing xunit report /home/zephyr/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/zephyr/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
INFO    - The following issues were found (showing the top 10 items):
INFO    - 1) tests/subsys/logging/log_immediate/logging.log_immediate on up_squared failed (Timeout)
INFO    - 2) tests/subsys/logging/log_immediate/logging.log_immediate.clean_output on up_squared failed (Timeout)
```

**Environment:**
- OS: Linux
- Toolchain: zephyr-sdk-0.16.0
- zephyr-v3.4.0-3801-g4856fd4cb6ce

### LINKED ISSUE #62761: up_squared: tests/subsys/logging/log_core_additional/ fail
**Describe the bug**
Out of 3 tests in the test suite, 2 fail.
`tests/subsys/logging/log_core_additional/logging.add.async`
and
`tests/subsys/logging/log_core_additional/logging.add.sync`
fails.

**To Reproduce**
```twister --device-testing --hardware-map up2.map -T tests/subsys/logging/log_core_additional/ -vv```

**Logs and console output**
```
2023-09-18 09:43:15,647 - twister - DEBUG - DEVICE: >>Checking Media Presence......
2023-09-18 09:43:15,649 - twister - DEBUG - DEVICE: >>Media Present......
2023-09-18 09:43:15,652 - twister - DEBUG - DEVICE: Downloading NBP file...
2023-09-18 09:43:16,024 - twister - DEBUG - DEVICE: 
2023-09-18 09:43:16,027 - twister - DEBUG - DEVICE: Succeed to download NBP file.
2023-09-18 09:43:16,095 - twister - DEBUG - DEVICE: *** Zephyr EFI Loader ***
2023-09-18 09:43:16,097 - twister - DEBUG - DEVICE: RSDP found at 0x79c34000
2023-09-18 09:43:16,101 - twister - DEBUG - DEVICE: Zeroing 4902936 bytes of memory at 0x115000
2023-09-18 09:43:16,149 - twister - DEBUG - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
2023-09-18 09:43:16,156 - twister - DEBUG - DEVICE: Copying 86016 data bytes to 0x100000 from image offset 32768
2023-09-18 09:43:16,162 - twister - DEBUG - DEVICE: Copying 2265056 data bytes to 0x5c2020 from image offset 118784
2023-09-18 09:43:16,188 - twister - DEBUG - DEVICE: Jumping to Entry Point: 0x1137 (48 31 c0 48 31 d2 48)
2023-09-18 09:43:16,430 - twister - DEBUG - DEVICE: ASSERTION FAIL [device_is_ready(uart_dev)] @ WEST_TOPDIR/zephyr/subsys/logging/backends/log_backend_uart.c:127
2023-09-18 09:43:57,267 - twister - DEBUG - Timed out while monitoring serial output on up_squared
2023-09-18 09:43:57,371 - twister - DEBUG - Expected suite names:['test_log_core_additional', 'test_log_core_additional']
2023-09-18 09:43:57,371 - twister - DEBUG - Detected suite names:[]
2023-09-18 09:43:57,372 - twister - DEBUG - run status: up_squared/tests/subsys/logging/log_core_additional/logging.add.async failed
2023-09-18 09:43:57,377 - twister - INFO - 3/3 up_squared                tests/subsys/logging/log_core_additional/logging.add.async  FAILED Timeout (device: up2, 63.638s)
2023-09-18 09:43:57,378 - twister - ERROR - see: /home/ztest/zephyrproject/zephyr/twister-out/up_squared/tests/subsys/logging/log_core_additional/logging.add.async/handler.log
2023-09-18 09:43:57,388 - twister - INFO - 3 test scenarios (3 test instances) selected, 1 configurations skipped (1 by static filter, 0 at runtime).
2023-09-18 09:43:57,388 - twister - INFO - 0 of 3 test configurations passed (0.00%), 2 failed, 0 errored, 1 skipped with 0 warnings in 145.58 seconds
2023-09-18 09:43:57,388 - twister - INFO - In total 20 test cases were executed, 16 skipped on 1 out of total 617 platforms (0.16%)
2023-09-18 09:43:57,389 - twister - INFO - 2 test configurations executed on platforms, 0 test configurations were only built.
2023-09-18 09:43:57,390 - twister - INFO - Saving reports...
2023-09-18 09:43:57,390 - twister - INFO - Writing JSON report /home/ztest/zephyrproject/zephyr/twister-out/twister.json
2023-09-18 09:43:57,393 - twister - INFO - Writing xunit report /home/ztest/zephyrproject/zephyr/twister-out/twister.xml...
2023-09-18 09:43:57,402 - twister - INFO - Writing xunit report /home/ztest/zephyrproject/zephyr/twister-out/twister_report.xml...
2023-09-18 09:43:57,412 - twister - INFO - -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
2023-09-18 09:43:57,412 - twister - INFO - The following issues were found (showing the top 10 items):
2023-09-18 09:43:57,412 - twister - INFO - 1) tests/subsys/logging/log_core_additional/logging.add.async on up_squared failed (Timeout)
2023-09-18 09:43:57,412 - twister - INFO - 2) tests/subsys/logging/log_core_additional/logging.add.sync on up_squared failed (Timeout)
```

**Environment:**
- OS: Linux
- Toolchain: zephyr-sdk-0.16.0
- zephyr-v3.4.0-3801-g4856fd4cb6ce

### LINKED ISSUE #65516: up_squared: tests/subsys/logging/log_custom_header/logging.log_custom_header ASSERTION FAIL.
**Describe the bug**
`tests/subsys/logging/log_custom_header/logging.log_custom_header' ASSERTION FAIL.

**To Reproduce**
```twister --device-testing --hardware-map up2.map -s tests/subsys/logging/log_custom_header/logging.log_custom_header -vv```

**Logs and console output**
```
DEBUG   - DEVICE: >>Checking Media Presence......
DEBUG   - DEVICE: >>Media Present......
DEBUG   - DEVICE: Downloading NBP file...
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Succeed to download NBP file.
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: RSDP found at 0x79c34000
DEBUG   - DEVICE: Zeroing 4907008 bytes of memory at 0x111000
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 69632 data bytes to 0x100000 from image offset 32768
DEBUG   - DEVICE: Copying 2265088 data bytes to 0x5bf000 from image offset 102400
DEBUG   - DEVICE: Jumping to Entry Point: 0x1137 (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: ASSERTION FAIL [device_is_ready(uart_dev)] @ WEST_TOPDIR/zephyr/subsys/logging/backends/log_backend_uart.c:127
```

**Environment:**
- OS: Linux
- Toolchain: zephyr-sdk-0.16.3
- zephyr-v3.5.0-556-g530a3092feef

### PR DESCRIPTION
**Pull request by najumon1980**
remove parent init level dependency for ns16550 driver such as PRE_KERNEL or POST_KERNEL. ns16550 driver init level change always to PRE_KERNEL and also removed Alder Lake board configuration with parent init dependency configuration.

Fixes #62717
Fixes #62761
Fixes #65516

### CODE REVIEW

**Comment by najumon1980** [comment]
@jhedberg could please verify this PR in ADL-N platform since I don't have access to lab today ?

**Comment by dcpleung** [comment]
DNM until tested.

**Comment by najumon1980** [comment]
Tested on ADL-N /RPL-S and is passing.

**Comment by dcpleung** [comment]
How about earlier UP Squared board (e.g. TGL)?

**Review by jhedberg — APPROVED** [review]
@najumon1980 this works fine on `up_squared` (see https://github.com/zephyrproject-rtos/zephyr/issues/62717#issuecomment-1822547850 )

Haven't tested on newer boards yet (like RPL or ADL - @finikorg do you have the time to check?)

**Comment by jhedberg** [comment]
> @najumon1980 this works fine on `up_squared` (see [#62717 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/62717#issuecomment-1822547850) )
> 
> Haven't tested on newer boards yet (like RPL or ADL - @finikorg do you have the time to check?)

Ah, I just saw https://github.com/zephyrproject-rtos/zephyr/pull/65428#issuecomment-1820237791 , i.e. seems like those are fine. @dcpleung looks like this should be ready to go in then, i.e. I'll remove the DNM label.

**Review by tbursztyka — APPROVED** [review]

**Review by finikorg — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
