### PR TITLE
drivers: spi: Add Ambiq MSPI driver 

### PR DESCRIPTION
**Pull request by msierszulski**
This PR adds the Ambiq  MSPI driver. It creates instances of this peripheral in the SoC and enables it in the board dts file.

It should be merged after merging https://github.com/zephyrproject-rtos/hal_ambiq/pull/6.

### CODE REVIEW

**Review by fkokosinski — DISMISSED** [review]
LGTM

**Review by kgugala — DISMISSED** [review]
LGTM

**Comment by fkokosinski** [comment]
Hi @msierszulski! I've merged https://github.com/zephyrproject-rtos/hal_ambiq/pull/6. Could you rebase your PR and point to the newest revision of the HAL in `west.yml`? Thanks!

**Comment by msierszulski** [comment]
Thanks @fkokosinski! The `west.yml` now points to the latest version of hal.  
@kgugala FYI

**Review by fkokosinski — APPROVED** [review]

**Review by kgugala — APPROVED** [review]
LGTM

**Pull request merged**
