### PR TITLE
hs{5,6}x support

### PR DESCRIPTION
**Pull request by shahab-vahedi**
These 2 changes:

1) Update HS6x board to support the latest GNU toolchain
2) Add support for HS5x board using GNU toolchain and QEMU

SDK needs to be updated as a result of these changes.
Please read each commit for further details.

### CODE REVIEW

**Comment by abrodkin** [comment]
@shahab-vahedi given the same functionality is already supported via https://github.com/zephyrproject-rtos/zephyr/pull/45469 can we just close this one now?

**Comment by shahab-vahedi** [comment]
@abrodkin I looked into [that](https://github.com/zephyrproject-rtos/zephyr/pull/45469) and I see divergences from this PR that are worth noting:

1. The output format for hs6x should be elf64-littlearc**64**. (`include/linker/linker-tool-gcc.h`, `arch/arc/CMakeLists.txt`)
2. `soc/arc/snps_qemu/CMakeLists.txt` hasn't been updated to use `CONFIG_ISA_ARCV2` i.s.o. `NOT CONFIG_64BIT`.
3. There is no QEMU board support for HS5x (`boards/arc/qemu_arc/qemu_arc_hs5x*`).
4. There is no QEMU SoC support for HS5x (`soc/arc/snps_qemu/Kconfig*`)

So I'd say that patch doesn't replace this one.

**Comment by abrodkin** [comment]
@evgeniy-paltsev could you please address comments of @shahab-vahedi above?

**Comment by evgeniy-paltsev** [comment]
> The output format for hs6x should be elf64-littlearc64 (include/linker/linker-tool-gcc.h, arch/arc/CMakeLists.txt)

It wouldn't work for current/latest Zephyr SDK. We are going to change that at same time as we update ARC GNU toolchain in Zephyr SDK. Alexey is working on that.

As for HS5x QEMU SoC / board - it would be added in next Zephyr release.

**Pull request closed without merging**
