### PR TITLE
dts: arm: nxp_rt118x: Complement full LPUART/GPIO devices and ocram spaces

### PR DESCRIPTION
**Pull request by lucien-nxp**
Complement full LPUART and GPIO devices, and ocram spaces

### CODE REVIEW

**Review by danieldegrasse — COMMENTED** [review]
Commit message needs to be updated to be more specific. Something like the following:

`dts: arm: nxp_rt118x: Complement full LPUART and GPIO devices, and ocram spaces`

You should also likely edit the title of the PR, just to make it clearer for reviewers

**Review by decsny — DISMISSED** [review]

**Comment by decsny** [comment]
agree to make the commit title/message to say rt118x

**Comment by lucien-nxp** [comment]
> Commit message needs to be updated to be more specific. Something like the following:
> 
> `dts: arm: nxp_rt118x: Complement full LPUART and GPIO devices, and ocram spaces`
> 
> You should also likely edit the title of the PR, just to make it clearer for reviewers

Thank you for reminding. I have correct the title for this PR.

**Comment by danieldegrasse** [comment]
Sorry to be such a stickler on this, but please include `rt118x` somewhere in the commit title. Currently the title doesn't really make it clear which device is being touched.

Something like
`dts: arm: nxp_rt118x: Complement full LPUART and GPIO devices, and ocram spaces`
or 
`dts: nxp: rt118x: Complement full LPUART and GPIO devices, and ocram spaces`

In terms of relevance, it is much more important which SOC series devicetree we are touching than the fact the SOC definition is for an ARM based part

**Comment by lucien-nxp** [comment]
> Sorry to be such a stickler on this, but please include `rt118x` somewhere in the commit title. Currently the title doesn't really make it clear which device is being touched.
> 
> Something like `dts: arm: nxp_rt118x: Complement full LPUART and GPIO devices, and ocram spaces` or `dts: nxp: rt118x: Complement full LPUART and GPIO devices, and ocram spaces`
> 
> In terms of relevance, it is much more important which SOC series devicetree we are touching than the fact the SOC definition is for an ARM based part

Sorry, I didn't notice that the first commit message you said also needs to be modified, I will change the commit message today.
Thank you for your stickler , it make me do better.😎

**Review by danieldegrasse — DISMISSED** [review]
Thanks for fixing this up!

**Review by dleach02 — DISMISSED** [review]

**Comment by dleach02** [comment]
@lucien-nxp can you address the merge conflict

**Comment by lucien-nxp** [comment]
> @lucien-nxp can you address the merge conflict

Sure, I have rebased my PR to the newest.

**Review by dleach02 — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Pull request merged**
