### PR TITLE
doc: Updated description grammar in mikro-bus.yaml file

### PR DESCRIPTION
**Pull request by shaggygi**
Fixed some of the wording within the description section of the mikro-bus.yaml file.

### CODE REVIEW

**Review by fabiobaltieri — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@shaggygi thanks for the fix, could you reword the commit message to match the contribution guidelines? https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

**Comment by shaggygi** [comment]
> could you reword the commit message to match the contribution guidelines?

My apologies as it is my first Zephyr PR.  Have another look for me.  Thx.

**Comment by fabiobaltieri** [comment]
> > could you reword the commit message to match the contribution guidelines?
> 
> My apologies as it is my first Zephyr PR. Have another look for me. Thx.

Hey no worries, you actually need to amend the commit and then force push it again, the full process is here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow, you are looking for the bit that says:

`git commit --amend -s`

and then

`git push -f` <- possibly passing the remote and branch name (`patch-2` in your case)

**Comment by shaggygi** [comment]
@fabiobaltieri Updated, but forgot the sign-off.  Pushed just now.  Thx

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri Updated, but forgot the sign-off. Pushed just now. Thx

Nearly there :-) break commit comment on 75 columns:

` 3: UC4 Commit message body line exceeds max length (84>75): "Fixed some of the wording within the description section of the mikro-bus.yaml file."`

**Comment by shaggygi** [comment]
> > @fabiobaltieri Updated, but forgot the sign-off. Pushed just now. Thx
> 
> Nearly there :-) break commit comment on 75 columns:
> 
> ` 3: UC4 Commit message body line exceeds max length (84>75): "Fixed some of the wording within the description section of the mikro-bus.yaml file."`

Well blame.  🤕  Please hold 😄

**Review by cfriedt — APPROVED** [review]

**Comment by shaggygi** [comment]
@fabiobaltieri sorry for my troubles, thanks for your patience.

**Pull request merged**
