### PR TITLE
Bluetooth: mesh: Fix Heartbeat Subscription Status

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This fixes Heartbeat Subscription Status parameters returned from
Heartbeat Subscription Get/Set messages.
Mesh Profile Specification quotes have been added to make this clear.

Note:
This patch introduces regression in MESH/NODE/CFG/HBS/BV-02-C, which
seems to have a bug, thus:
Test Spec Errata has been created for MESH/NODE/CFG/HBS/BV-02-C (CASE0040580)

Moreover, PTS issue created for MESH/NODE/CFG/HBS/BV-01-C (CASE0040579)

Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

### CODE REVIEW

**Comment by MariuszSkamra** [comment]
Let's wait for Bluetooth SIG and PTS response

**Comment by jhedberg** [comment]
Yeah, let's wait for a response. I'm a bit reluctant to changing too lightly this since the current code is the result of many hours of reading the spec, test spec and various errata I could find related to this feature, and the finally getting it to pass with the PTS (which apparently has changed its behavior in the latest versions since you created this PR).

**Comment by MariuszSkamra** [comment]
I've got feedback to my TSE, and seems that it is similar to the [TSE 9610](https://www.bluetooth.org/tse/errata_view.cfm?errata_id=9610) (rejected).
There is an explanation that "only if the source and destination are unchanged, then the periodLog being set to 0 keeps the count from resetting" . So current heartbeat_sub_set behaviour is correct.
Moreover there is existing [Spec Errata](https://www.bluetooth.org/errata/errata_view.cfm?errata_id=9609) that shall clarify this in Spec.

**Comment by jhedberg** [comment]
> I've got feedback to my TSE, and seems that it is similar to the TSE 9610 (rejected).
There is an explanation that "only if the source and destination are unchanged, then the periodLog being set to 0 keeps the count from resetting" . So current heartbeat_sub_set behaviour is correct.
There is existing Spec Errata that shall clarify this in Spec.

So this PR should be closed without merging?

**Comment by MariuszSkamra** [comment]
Yes, closing

**Pull request closed without merging**
