### PR TITLE
drivers: sensor: bmp388: fix register read for spi bus

### PR DESCRIPTION
**Pull request by toezi**
The BMP388 sensor, when using SPI, sends a dummy byte after receiving the address byte, similar to the BMI270. This dummy byte was not ignored and taken as response. Fixed it by ignoring the first 2 bytes and moved to burst read for improved efficiency.

### CODE REVIEW

**Comment by ubieda** [comment]
Please check #77907 as it appears to already address this issue.

**Comment by toezi** [comment]
> Please check #77907 as it appears to already address this issue.

Thank you for your quick response, and sorry for the inconvenience. I did not find that PR while checking for duplicates. It looks like this fixes the same issue.

**Comment by ubieda** [comment]
> > Please check #77907 as it appears to already address this issue.
> 
> 
> 
> Thank you for your quick response, and sorry for the inconvenience. I did not find that PR while checking for duplicates. It looks like this fixes the same issue.

No worries! Thanks for filing the PR. I'd suggest reviewing that one to make sure it meets your needs, as it appears closer to get merged in.

Hopefully you'll find something else to contribute on!

**Comment by toezi** [comment]
I surely will!

**Pull request closed without merging**
