### PR TITLE
net: http_server: Enable Bluetooth stack if configured

### PR DESCRIPTION
**Pull request by wbober**
This PR enables Bluetooth stack if Bluetooth L2 is
compiled in.

Change-Id: I8f8127031140f0603615af44e0809d203db32f48
Signed-off-by: Wojciech Bober <wojciech.bober@nordicsemi.no>

### CODE REVIEW

**Comment by Vudentz** [comment]
LGTM

**Review by Vudentz — APPROVED** [review]

**Comment by pfalcon** [comment]
@jukkar : Should this still be done like this, or is this handled by net_app now?

**Comment by jukkar** [comment]
> Should this still be done like this, or is this handled by net_app now?

This is not handled by net_app currently so instead of adding these setup settings to each and every sample application, we should instead do these setup's in one place only. Currently various network inits are done in subsys/net/lib/app/init.c and we should add these settings there.

**Review by jukkar — CHANGES_REQUESTED** [review]
See my comment about placing the initialization into net_app instead.

**Comment by pfalcon** [comment]
Ugh, then if net_app_init() is not enabled for http_server, and net_app doesn't support IP over BLE so far, then maybe this should be merged as is, and then someone knowldgeable with net_app refactor BLE support consistently? Of course, unless @wbober feel comfortable to implement that right away ;-).

**Comment by jukkar** [comment]
> Of course, unless @wbober feel comfortable to implement that right away

The changes in net_app init should be very simple, basically the changes done here could be added directly to subsys/net/lib/app/init.c. I have similar changes planned for 802.15.4 support, hopefully can send those changes later this week.

**Comment by wbober** [comment]
@jukkar Ok, I'll look into that by the end of the week.

**Comment by jukkar** [comment]
Example auto init for 802.15.4 is found in #840

**Comment by jukkar** [comment]
While fixing https://jira.zephyrproject.org/browse/ZEP-2395 I noticed that moving the BT ipsp init into net_app_init requires more work. So lets merge this so we are not blocked by it and figure out later how to do bt ipsp init in some later PR.

**Review by jukkar — APPROVED** [review]

**Pull request merged**
