### PR TITLE
posix: abstract pthread_key_t as uint32_t

### PR DESCRIPTION
**Pull request by cfriedt**
3 commits:

* lib: posix: pthread: rename pthread_key_lock to pthread_once_lock
* lib: posix: pthread_key: use spinlock instead of semaphore
* posix: key: abstract pthread_key_t as uint32_t

Please see each commit message for details.

### CODE REVIEW

**Comment by cfriedt** [comment]
This is blocked until #52173 is merged, so I'll keep it in draft.

**Review by jeremybettis — DISMISSED** [review]

**Comment by cfriedt** [comment]
* rebased

**Comment by cfriedt** [comment]
* fixed spelling mistake (implemenataiton -> implemenatation)
* added function pointer argument name which was previously never there (`void (*destructor)(void *)` -> `void (*destructor)(void *value)`)

**Comment by cfriedt** [comment]
@jeremybettis - are you OK to re-ACK?

**Comment by cfriedt** [comment]
@enjiamai @KangJianX @keith-packard @stephanosio - would gratefully accept an approval if anyone is feeling generous 😁

**Review by jeremybettis — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
