### PR TITLE
boards: rpi_pico: rpi_pico_w board definition

### PR DESCRIPTION
**Pull request by drensber**
This is a barebones implementation of the board definition for the Raspberry Pi Pico W. Effort has been made to abstract the features that are common to both the Pico and Pico W into a shared file when possible. This commit does not include the addition of bluetooth or wifi drivers for the W's Infineon module.

### CODE REVIEW

**Comment by drensber** [comment]
This is exactly the same changeset as https://github.com/zephyrproject-rtos/zephyr/pull/57437, except that it (hopefully) gets the "Author" field correct.

**Comment by soburi** [comment]
Please rename this branch to old one, and push with `-f` option.
Do not create a new PR on the same topic.

**Comment by drensber** [comment]
> Please rename this branch to old one, and push with `-f` option.
> Do not create a new PR on the same topic.

Why does the branch need to be renamed? My understanding is that the "Author" is an attribute of the PR, not the branch, and is immutable, so we need a new PR since the Author needs to change.

**Comment by soburi** [comment]
> My understanding is that the "Author" is an attribute of the PR, 

It is misunderstanding.
CI checks only commits. PR has no attribute.

```
commit d96424f27dad4e8dc2a69dbaee78855b0ae72ef7 (pr57437)
Author: beechwoods-software <davidr@beechwoods.com>
Date:   Thu Apr 13 13:37:12 2023 -0400
```

`Author:` is embed in commit.

#57739 not yet fixed.

**Comment by drensber** [comment]
> > My understanding is that the "Author" is an attribute of the PR,
> 
> It is misunderstanding. CI checks only commits. PR has no attribute.
> 
> ```
> commit d96424f27dad4e8dc2a69dbaee78855b0ae72ef7 (pr57437)
> Author: beechwoods-software <davidr@beechwoods.com>
> Date:   Thu Apr 13 13:37:12 2023 -0400
> ```
> 
> `Author:` is embed in commit.
> 
> #57739 not yet fixed.

I'm still confused. That commit was long ago squashed, so all of its attributes should be long gone (unless one of them was set in stone during the creation of the PR... in which case, it still seems like a new PR would be required... this is based on what I'm reading on the GitHub support site: https://github.com/orgs/community/discussions/15067).

**Comment by drensber** [comment]
OK, I did the reset and commit. I'll reopen this PR.

**Comment by soburi** [comment]
9f306108b60f20c5cd128307fcdef99bf4dac877 seem valid.
Pleaase push this commit as `beechwoods-software:rpi_pico_w` branch.

**Comment by drensber** [comment]
> [9f30610](https://github.com/zephyrproject-rtos/zephyr/commit/9f306108b60f20c5cd128307fcdef99bf4dac877) seem valid.
> Pleaase push this commit as `beechwoods-software:rpi_pico_w` branch.

I think I already have, no? It seems to have passed all  of the automated tests so far (including the one that used to fail the author check, I believe).

**Comment by soburi** [comment]
Could you reopen #57437?

**Comment by drensber** [comment]
> Could you reopen #57437?

Yes. It looks like I'm required to close this one before doing so.

**Comment by drensber** [comment]
Actually, it still won't let me reopen 57437. Do I need to go through the git reset HEAD~1 thing and push again while 57437 is open?

**Pull request closed without merging**
