### PR TITLE
stm32: drivers: Select PINCTRL when required

### PR DESCRIPTION
**Pull request by erwango**
Select PINCTRL when required directly in stm32 drivers so that it is not required anymore to do it at board level.
Clean up stm32 based boards.

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]

**Comment by erwango** [comment]
- Fixed line endings

**Review by gautierg-st — DISMISSED** [review]
Non blocking: Some defconfig files have two consecutive blank lines.
Otherwise LGTM

**Review by gmarull — DISMISSED** [review]

**Review by marwaiehm-st — DISMISSED** [review]

**Comment by erwango** [comment]
> Non blocking: Some defconfig files have two consecutive blank lines. Otherwise LGTM

I'll make some more clean up in these files, I'll try to do it at this moment.

**Review by fabiobaltieri — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Comment by erwango** [comment]
- Fixed wrong symbol update in drivers/disk/Kconfig.sdmmc
- Fixed missing OSPI update

**Comment by gautierg-st** [comment]
You're missing nucleo_u031r8 that was recently merged here: #77706

**Comment by erwango** [comment]
> You're missing nucleo_u031r8 that was recently merged here: #77706

Fixed, thanks

**Review by gmarull — APPROVED** [review]

**Review by marwaiehm-st — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
