### PR TITLE
net: conn: fix supplicant l2 recv unexpected frame

### PR DESCRIPTION
**Pull request by fengming-ye**
Supplicant create AF_PACKET proto ETH_P_PAE socket but receive other frames like ICMP and UDP and causes following issues.
1. When frame len exceeds MTU, net_pkt_clone cannot clone pkt. Thus dropped it and print warning log.
2. It will lower throughput performance as every packet is cloned.

Fix it by conn_raw_socket does not deliver pkts protocol not macted, after l2 processed, unless conn is raw.

### CODE REVIEW

**Review by gannicus-gj — APPROVED** [review]

**Comment by jukkar** [comment]
There is something wrong with CI so we cannot see test runs.
Anyway, I tried to run some of our raw tests manually and at least `af_packet` test fails
```
west build -p -b native_sim ~/zephyrproject/zephyr/tests/net/socket/af_packet \
-d ~zephyrproject/build/af_packet-test -t run -- \
-DCONFIG_NET_IF_LOG_LEVEL_DBG=y \
-DCONFIG_NET_LOG=y \
-DCONFIG_LOG_MODE_IMMEDIATE=y \
-DCONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
```
output
```
[00:00:00.000,000] <dbg> net_if: net_if_init: (main): 
[00:00:00.000,000] <dbg> net_if: init_iface: (main): On iface 0x806d5a0
[00:00:00.000,000] <dbg> net_if: net_if_ipv4_addr_add: (main): [0] interface 1 (0x806d5a0) address 127.0.0.1 type MANUAL added
[00:00:00.000,000] <dbg> net_if: init_iface: (main): On iface 0x806d5e0
[00:00:00.000,000] <wrn> net_if: You have 1 IPv4 net_if addresses but 2 network interfaces
[00:00:00.000,000] <wrn> net_if: Consider increasing CONFIG_NET_IF_MAX_IPV4_COUNT value.
[00:00:00.000,000] <dbg> net_if: net_if_post_init: (main): 
[00:00:00.000,000] <dbg> net_if: net_if_up: (main): iface 1 (0x806d5a0)
[00:00:00.000,000] <dbg> net_if: update_operational_state: (main): iface 1 (0x806d5a0), oper state UP admin UP carrier ON dormant OFF
[00:00:00.000,000] <dbg> net_if: net_if_up: (main): iface 2 (0x806d5e0)
[00:00:00.000,000] <dbg> net_if: update_operational_state: (main): iface 2 (0x806d5e0), oper state UP admin UP carrier ON dormant OFF
*** Booting Zephyr OS build v3.6.0-4474-g6422d0bcc203 ***
Running TESTSUITE socket_packet
===================================================================
START - test_packet_sockets
[00:00:00.000,000] <dbg> net_sock: z_impl_zsock_close: (test_packet_sockets): close: ctx=0x806e120, fd=0
[00:00:00.000,000] <dbg> net_sock: z_impl_zsock_close: (test_packet_sockets): close: ctx=0x806e1c4, fd=1
 PASS - test_packet_sockets in 0.000 seconds
===================================================================
START - test_packet_sockets_dgram
[00:00:00.000,000] <dbg> net_if: net_if_tx: (test_packet_sockets_dgram): Processing (pkt 0x8071ffc, prio 1) network packet iface 2 (0x806d5e0)
[00:00:00.000,000] <dbg> net_test: eth_fake_send: (test_packet_sockets_dgram): Sending data (24 bytes) to iface 2

[00:00:00.020,000] <dbg> net_if: net_if_tx: (test_packet_sockets_dgram): Calling context send cb 0x806e1c4 status 24

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/af_packet/src/main.c:351: socket_packet_test_packet_sockets_dgram: (ret not equal to sizeof(data_to_send))
Cannot receive all data (-1 vs 10) (-11)
 FAIL - test_packet_sockets_dgram in 0.240 seconds
===================================================================
START - test_raw_and_dgram_socket_exchange
[00:00:00.240,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Processing (pkt 0x8071ffc, prio 1) network packet iface 1 (0x806d5a0)
[00:00:00.240,000] <dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_excha): Sending data (24 bytes) to iface 1

[00:00:00.260,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Calling context send cb 0x806e268 status 24
[00:00:00.260,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e30c, pkt=0x8072308, st=0, user_data=(nil)
[00:00:00.300,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Processing (pkt 0x8071ffc, prio 1) network packet iface 2 (0x806d5e0)
[00:00:00.300,000] <dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_excha): Sending data (24 bytes) to iface 2

[00:00:00.320,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Calling context send cb 0x806e30c status 24

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/af_packet/src/main.c:493: socket_packet_test_raw_and_dgram_socket_exchange: (ret not equal to sizeof(data_to_send))
Cannot receive all data (-11)
 FAIL - test_raw_and_dgram_socket_exchange in 0.300 seconds
===================================================================
START - test_raw_and_dgram_socket_recv
[00:00:00.540,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_recv): Processing (pkt 0x8071ffc, prio 1) network packet iface 1 (0x806d5a0)
[00:00:00.540,000] <dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_recv): Sending data (24 bytes) to iface 1

[00:00:00.560,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_recv): Calling context send cb 0x806e3b0 status 24
[00:00:00.560,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e4f8, pkt=0x8072344, st=0, user_data=(nil)
[00:00:00.560,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e454, pkt=0x80722cc, st=0, user_data=(nil)
[00:00:00.560,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e30c, pkt=0x8072290, st=0, user_data=(nil)
[00:00:00.620,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_and_dgram_socket_recv): close: ctx=0x806e3b0, fd=4
[00:00:00.620,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_and_dgram_socket_recv): close: ctx=0x806e454, fd=5
[00:00:00.620,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_and_dgram_socket_recv): close: ctx=0x806e4f8, fd=6
 PASS - test_raw_and_dgram_socket_recv in 0.080 seconds
===================================================================
START - test_raw_packet_sockets
[00:00:00.620,000] <dbg> net_sock: zsock_socket_internal: (test_raw_packet_sockets): socket: ctx=0x806e4f8, fd=6
[00:00:00.620,000] <dbg> net_sock: zsock_socket_internal: (test_raw_packet_sockets): socket: ctx=0x806e59c, fd=7
[00:00:00.620,000] <dbg> net_sock_packet: zpacket_received_cb: (test_raw_packet_sockets): ctx=0x806e3b0, pkt=0x8071fc0, st=0, user_data=(nil)
[00:00:00.620,000] <dbg> net_sock: zsock_received_cb: (test_raw_packet_sockets): ctx=0x806e4f8, pkt=0x8071ffc, st=0, user_data=(nil)
[00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e3b0, fd=4
[00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e454, fd=5
[00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e4f8, fd=6
[00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e59c, fd=7
 PASS - test_raw_packet_sockets in 0.020 seconds
===================================================================
TESTSUITE socket_packet failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  60.00% [socket_packet]: pass = 3, fail = 2, skip = 0, total = 5 duration = 0.640 seconds
 - PASS - [socket_packet.test_packet_sockets] duration = 0.000 seconds
 - FAIL - [socket_packet.test_packet_sockets_dgram] duration = 0.240 seconds
 - FAIL - [socket_packet.test_raw_and_dgram_socket_exchange] duration = 0.300 seconds
 - PASS - [socket_packet.test_raw_and_dgram_socket_recv] duration = 0.080 seconds
 - PASS - [socket_packet.test_raw_packet_sockets] duration = 0.020 seconds

------ TESTSUITE SUMMARY END ------
```

**Comment by dleach02** [comment]
restarted CI

**Comment by fengming-ye** [comment]
> There is something wrong with CI so we cannot see test runs. Anyway, I tried to run some of our raw tests manually and at least `af_packet` test fails
> 
> ```
> west build -p -b native_sim ~/zephyrproject/zephyr/tests/net/socket/af_packet \
> -d ~zephyrproject/build/af_packet-test -t run -- \
> -DCONFIG_NET_IF_LOG_LEVEL_DBG=y \
> -DCONFIG_NET_LOG=y \
> -DCONFIG_LOG_MODE_IMMEDIATE=y \
> -DCONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
> ```
> 
> output
> 
> ```
> [00:00:00.000,000] <dbg> net_if: net_if_init: (main): 
> [00:00:00.000,000] <dbg> net_if: init_iface: (main): On iface 0x806d5a0
> [00:00:00.000,000] <dbg> net_if: net_if_ipv4_addr_add: (main): [0] interface 1 (0x806d5a0) address 127.0.0.1 type MANUAL added
> [00:00:00.000,000] <dbg> net_if: init_iface: (main): On iface 0x806d5e0
> [00:00:00.000,000] <wrn> net_if: You have 1 IPv4 net_if addresses but 2 network interfaces
> [00:00:00.000,000] <wrn> net_if: Consider increasing CONFIG_NET_IF_MAX_IPV4_COUNT value.
> [00:00:00.000,000] <dbg> net_if: net_if_post_init: (main): 
> [00:00:00.000,000] <dbg> net_if: net_if_up: (main): iface 1 (0x806d5a0)
> [00:00:00.000,000] <dbg> net_if: update_operational_state: (main): iface 1 (0x806d5a0), oper state UP admin UP carrier ON dormant OFF
> [00:00:00.000,000] <dbg> net_if: net_if_up: (main): iface 2 (0x806d5e0)
> [00:00:00.000,000] <dbg> net_if: update_operational_state: (main): iface 2 (0x806d5e0), oper state UP admin UP carrier ON dormant OFF
> *** Booting Zephyr OS build v3.6.0-4474-g6422d0bcc203 ***
> Running TESTSUITE socket_packet
> ===================================================================
> START - test_packet_sockets
> [00:00:00.000,000] <dbg> net_sock: z_impl_zsock_close: (test_packet_sockets): close: ctx=0x806e120, fd=0
> [00:00:00.000,000] <dbg> net_sock: z_impl_zsock_close: (test_packet_sockets): close: ctx=0x806e1c4, fd=1
>  PASS - test_packet_sockets in 0.000 seconds
> ===================================================================
> START - test_packet_sockets_dgram
> [00:00:00.000,000] <dbg> net_if: net_if_tx: (test_packet_sockets_dgram): Processing (pkt 0x8071ffc, prio 1) network packet iface 2 (0x806d5e0)
> [00:00:00.000,000] <dbg> net_test: eth_fake_send: (test_packet_sockets_dgram): Sending data (24 bytes) to iface 2
> 
> [00:00:00.020,000] <dbg> net_if: net_if_tx: (test_packet_sockets_dgram): Calling context send cb 0x806e1c4 status 24
> 
>     Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/af_packet/src/main.c:351: socket_packet_test_packet_sockets_dgram: (ret not equal to sizeof(data_to_send))
> Cannot receive all data (-1 vs 10) (-11)
>  FAIL - test_packet_sockets_dgram in 0.240 seconds
> ===================================================================
> START - test_raw_and_dgram_socket_exchange
> [00:00:00.240,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Processing (pkt 0x8071ffc, prio 1) network packet iface 1 (0x806d5a0)
> [00:00:00.240,000] <dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_excha): Sending data (24 bytes) to iface 1
> 
> [00:00:00.260,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Calling context send cb 0x806e268 status 24
> [00:00:00.260,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e30c, pkt=0x8072308, st=0, user_data=(nil)
> [00:00:00.300,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Processing (pkt 0x8071ffc, prio 1) network packet iface 2 (0x806d5e0)
> [00:00:00.300,000] <dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_excha): Sending data (24 bytes) to iface 2
> 
> [00:00:00.320,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Calling context send cb 0x806e30c status 24
> 
>     Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/af_packet/src/main.c:493: socket_packet_test_raw_and_dgram_socket_exchange: (ret not equal to sizeof(data_to_send))
> Cannot receive all data (-11)
>  FAIL - test_raw_and_dgram_socket_exchange in 0.300 seconds
> ===================================================================
> START - test_raw_and_dgram_socket_recv
> [00:00:00.540,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_recv): Processing (pkt 0x8071ffc, prio 1) network packet iface 1 (0x806d5a0)
> [00:00:00.540,000] <dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_recv): Sending data (24 bytes) to iface 1
> 
> [00:00:00.560,000] <dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_recv): Calling context send cb 0x806e3b0 status 24
> [00:00:00.560,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e4f8, pkt=0x8072344, st=0, user_data=(nil)
> [00:00:00.560,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e454, pkt=0x80722cc, st=0, user_data=(nil)
> [00:00:00.560,000] <dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x806e30c, pkt=0x8072290, st=0, user_data=(nil)
> [00:00:00.620,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_and_dgram_socket_recv): close: ctx=0x806e3b0, fd=4
> [00:00:00.620,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_and_dgram_socket_recv): close: ctx=0x806e454, fd=5
> [00:00:00.620,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_and_dgram_socket_recv): close: ctx=0x806e4f8, fd=6
>  PASS - test_raw_and_dgram_socket_recv in 0.080 seconds
> ===================================================================
> START - test_raw_packet_sockets
> [00:00:00.620,000] <dbg> net_sock: zsock_socket_internal: (test_raw_packet_sockets): socket: ctx=0x806e4f8, fd=6
> [00:00:00.620,000] <dbg> net_sock: zsock_socket_internal: (test_raw_packet_sockets): socket: ctx=0x806e59c, fd=7
> [00:00:00.620,000] <dbg> net_sock_packet: zpacket_received_cb: (test_raw_packet_sockets): ctx=0x806e3b0, pkt=0x8071fc0, st=0, user_data=(nil)
> [00:00:00.620,000] <dbg> net_sock: zsock_received_cb: (test_raw_packet_sockets): ctx=0x806e4f8, pkt=0x8071ffc, st=0, user_data=(nil)
> [00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e3b0, fd=4
> [00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e454, fd=5
> [00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e4f8, fd=6
> [00:00:00.640,000] <dbg> net_sock: z_impl_zsock_close: (test_raw_packet_sockets): close: ctx=0x806e59c, fd=7
>  PASS - test_raw_packet_sockets in 0.020 seconds
> ===================================================================
> TESTSUITE socket_packet failed.
> 
> ------ TESTSUITE SUMMARY START ------
> 
> SUITE FAIL -  60.00% [socket_packet]: pass = 3, fail = 2, skip = 0, total = 5 duration = 0.640 seconds
>  - PASS - [socket_packet.test_packet_sockets] duration = 0.000 seconds
>  - FAIL - [socket_packet.test_packet_sockets_dgram] duration = 0.240 seconds
>  - FAIL - [socket_packet.test_raw_and_dgram_socket_exchange] duration = 0.300 seconds
>  - PASS - [socket_packet.test_raw_and_dgram_socket_recv] duration = 0.080 seconds
>  - PASS - [socket_packet.test_raw_packet_sockets] duration = 0.020 seconds
> 
> ------ TESTSUITE SUMMARY END ------
> ```

**Comment by fengming-ye** [comment]
Hi @jukkar 
Thanks for helping run test.
This PR's intension is to block unneeded pkt for socket receiver.
I checked the failed test cases with my own debug log
===================================================================
START - test_packet_sockets_dgram
[00:00:00.000,000] ^[[0m<dbg> net_if: net_if_tx: (test_packet_sockets_dgram): Processing (pkt 0x807171c, prio 1) network packet iface 0x8073338/2^[[0m
[00:00:00.000,000] ^[[0m<dbg> net_test: eth_fake_send: (test_packet_sockets_dgram): Sending data (24 bytes) to iface 2
^[[0m
[00:00:00.020,000] ^[[0m<dbg> net_if: net_if_tx: (test_packet_sockets_dgram): Calling context send cb 0x8073ee4 status 24^[[0m
[00:00:00.020,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x22f0, pkt proto 0x800^[[0m
[00:00:00.020,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x22f0, pkt proto 0x800^[[0m

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/af_packet/src/main.c:351: socket_packet_test_packet_sockets_dgram: (ret not equal to sizeof(data_to_send))
Cannot receive all data (-1 vs 10) (-11)
 FAIL - test_packet_sockets_dgram in 0.240 seconds
===================================================================
START - test_raw_and_dgram_socket_exchange
[00:00:00.240,000] ^[[0m<dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Processing (pkt 0x807171c, prio 1) network packet iface 0x80732fc/1^[[0m
[00:00:00.240,000] ^[[0m<dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_excha): Sending data (24 bytes) to iface 1
^[[0m
[00:00:00.260,000] ^[[0m<dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Calling context send cb 0x8073f88 status 24^[[0m
[00:00:00.260,000] ^[[0m<dbg> net_sock_packet: zpacket_received_cb: (rx_q[0]): ctx=0x807402c, pkt=0x8071a28, st=0, user_data=(nil)^[[0m
[00:00:00.260,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x3, pkt proto 0x800^[[0m
[00:00:00.260,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x22f0, pkt proto 0x800^[[0m
[00:00:00.260,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x22f0, pkt proto 0x800^[[0m
[00:00:00.300,000] ^[[0m<dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Processing (pkt 0x807171c, prio 1) network packet iface 0x8073338/2^[[0m
[00:00:00.300,000] ^[[0m<dbg> net_test: eth_fake_send: (test_raw_and_dgram_socket_excha): Sending data (24 bytes) to iface 2
^[[0m
[00:00:00.320,000] ^[[0m<dbg> net_if: net_if_tx: (test_raw_and_dgram_socket_excha): Calling context send cb 0x807402c status 24^[[0m
[00:00:00.320,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x3, pkt proto 0x800^[[0m
[00:00:00.320,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x22f0, pkt proto 0x800^[[0m
[00:00:00.320,000] ^[[1;33m<wrn> net_conn: debug yfm block conn type 2 proto 0x22f0, pkt proto 0x800^[[0m

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/af_packet/src/main.c:493: socket_packet_test_raw_and_dgram_socket_exchange: (ret not equal to sizeof(data_to_send))
Cannot receive all data (-11)
 FAIL - test_raw_and_dgram_socket_exchange in 0.300 seconds
===================================================================


Could you pls share some knowledge why proto 0x22f0 should receive proto 0x0800 (ETH IP) pkt?
That will help on improving the PR.
Thanks.

**Comment by jukkar** [comment]
> Could you pls share some knowledge why proto 0x22f0 should receive proto 0x0800 (ETH IP) pkt?

Indeed, that is a good point and it really looks like our test is incorrect. Could you fix that to make sure the tests pass properly?

**Comment by fengming-ye** [comment]
> > Could you pls share some knowledge why proto 0x22f0 should receive proto 0x0800 (ETH IP) pkt?
> 
> Indeed, that is a good point and it really looks like our test is incorrect. Could you fix that to make sure the tests pass properly?

sure updated.

**Review by gannicus-gj — APPROVED** [review]

**Review by gannicus-gj — APPROVED** [review]

**Comment by fengming-ye** [comment]
Hi @jukkar 
There is issue found which need some discussion, that zephyr hostap l2_bridge_init create socket with protocol htons(ETH_P_EAPOL) (big-endian) but other sockets are using little-endian (appears to me).
So this commit will cause supplicant block EAPOL frame. Because conn->proto is big-endian but pkt->proto is little-endian.
Needs clarification here that is zephyr using socket protocol as little-endian or big-endian?

**Comment by fengming-ye** [comment]
created co-PR to fix supplicant l2_packet cannot receive issue
https://github.com/zephyrproject-rtos/hostap/pull/8

**Comment by jukkar** [comment]
> Needs clarification here that is zephyr using socket protocol as little-endian or big-endian?

The talking about little-endian / big-endian is really confusing when working with networking. We should talk about host byte order vs. network byte order so that it is easier to map the desired functionality to various specifications. Network byte order is always in big-endian, but host byte order can be either little- or big-endian. Typically with almost all modern hardware, the host byte order is in little-endian.

Some socket structures (like `struct sockaddr`) expect things to be in network byte order, but for example `socket()` API expect the parameters to be in host byte order.

**Comment by jukkar** [comment]
After looking the packet(7) socket documentation at https://www.man7.org/linux/man-pages/man7/packet.7.html, it seems that the protocol field needs to be network byte order for the packet sockets. The documentation talks only about `htons(ETH_P_ALL)` but I suppose using `htons` means that the protocol field for packet socket calls needs to be network byte order always.
I do not see handling for this in network stack, so we should fix this first and see how this changes the other proposed changes in this PR.

**Pull request closed without merging**
