### PR TITLE
[Backport v2.7-branch] uart_stm32: Fix conflict between poll_out and irq API

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport d42cef17b06465393462210a224fdc5cc58b1490 from #40173

### CODE REVIEW

**Comment by ycsin** [comment]
Associated issue https://github.com/zephyrproject-rtos/zephyr/issues/40775

**Comment by ycsin** [comment]
Backport of #40782 & #41116 depends on this

**Comment by cfriedt** [comment]
> Backport of #40782 & #41116 depends on this, I'm not sure if we should create a branch that patch the uart driver using the final version or backport all of the related and dependent PRs, thoughts? @cfriedt @erwango 

I'm impartial - as long as there is an issue filed ;-)

**Comment by ycsin** [comment]
> I'm impartial - as long as there is an issue filed ;-)

The initial PR #39752 is merged and backported without an issue filed, the author described the bug directly in the PR. The second PR #40173 is a continuation to fix the same issue and is merged without an issue filed; the bug and the reproduction steps are described directly in the PR. After this PR, it seems to generate some other issue as described by @erwango in #40775, which #40782 & #41116 are aimed to fix.

**Review by ycsin — APPROVED** [review]

**Comment by cfriedt** [comment]
@erwango - can you approve the backport?

**Comment by erwango** [comment]
> @erwango - can you approve the backport?

Approved but, we now need to complete the work and back port https://github.com/zephyrproject-rtos/zephyr/pull/40782 & https://github.com/zephyrproject-rtos/zephyr/pull/41116. @ycsin would you mind taking care of those ?

**Review by erwango — APPROVED** [review]

**Comment by ycsin** [comment]
> > @erwango - can you approve the backport?
> 
> Approved but, we now need to complete the work and back port #40782 & #41116. @ycsin would you mind taking care of those ?

I think they should probably just work? I had no issue cherry-picking them into my local 2.7 LTS branch.

**Comment by erwango** [comment]
> I think they should probably just work? I had no issue cherry-picking them into my local 2.7 LTS branch, I guess we just need to apply the backport label to them one by one after this one is merged

Point is that backport label is already added, but the backport PR didn't show up from what I can see. Unless I've missed them ?

**Comment by ycsin** [comment]
> > I think they should probably just work? I had no issue cherry-picking them into my local 2.7 LTS branch, I guess we just need to apply the backport label to them one by one after this one is merged
> 
> Point is that backport label is already added, but the backport PR didn't show up from what I can see. Unless I've missed them ?

Yup because they were missing this backport, should be a merge conflict.

Do you think if we should close this PR and have a new backport PR that cherry-pick all the commits from these 3 PR?

**Comment by erwango** [comment]
> Do you think if we should close this PR and have a new backport PR that cherry-pick all the commits from these 3 PR?

Since the PRs are small enough and impact a single file I think that would be fine.
Then, I don't know if we should keep 3 different commits or a single one. Maybe @cfriedt could give his advice on this particular point.
Let's start with 3 commits and we'll discuss with a squash is a better option.

**Comment by ycsin** [comment]
> I'm impartial - as long as there is an issue filed ;-)

https://github.com/zephyrproject-rtos/zephyr/pull/42786#issuecomment-1039485436

**Comment by ycsin** [comment]
#43156

**Pull request closed without merging**
