### PR TITLE
kconfig: Make header comments consistent globally

### PR DESCRIPTION
**Pull request by ulfalizer**
Similar deal to https://github.com/zephyrproject-rtos/zephyr/pull/20266,
cleaning up all header comments to use a consistent format. Also includes some
stuff I missed in the first PR.

Main commit:

```
kconfig: Clean up header comments and make them consistent

Use this short header style in all Kconfig files:

    # <description>

    # <copyright>
    # <license>

    ...

Also change all <description>s from

    # Kconfig[.extension] - Foo-related options

to just

    # Foo-related options

It's clear enough that it's about Kconfig.

The <description> cleanup was done with this command, along with some
manual cleanup (big letter at the start, etc.)

    git ls-files '*Kconfig*' | \
        xargs sed -i -E '1 s/#\s*Kconfig[\w.-]*\s*-\s*/# /'
```

Other stuff:

```
kconfig: Clean up 'config  FOO' (two spaces) definitions

Must've been copy-pasted around.
```

```
kconfig: Change some '#Comment' comments to '# Comment'

For consistency. Newly-introduced stuff.
```

### CODE REVIEW

**Comment by ulfalizer** [comment]
Semi-related PR: https://github.com/zephyrproject-rtos/ci-tools/pull/105

**Review by joerchan — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by vanwinkeljan — APPROVED** [review]

**Comment by ulfalizer** [comment]
Will always time out.

**Review by aescolar — APPROVED** [review]
No complains in my files (or the few other I checked, but I have not checked all)

**Comment by ulfalizer** [comment]
> No complains in my files (or the few other I checked, but I have not checked all)

Done three passes now, so rest should be fine too hopefully. Don't expect people to go through all of them (though feel free if you're bored).

**Review by finikorg — APPROVED** [review]
LGTM (for usb)

**Review by nvlsianpu — APPROVED** [review]
LGTM (FS, settings, flash, dfu, mcumgr, nRF Nordic boards)

**Comment by finikorg** [comment]
@ulfalizer Could you document templates in the Zephyr documentation?

**Comment by ulfalizer** [comment]
@finikorg 
Do you mean templates as in e.g. `./subsys/logging/Kconfig.template.log_config`, or just documenting the header format?

**Review by vanti — APPROVED** [review]
LGTM (SimpleLink changes)

**Comment by ulfalizer** [comment]
> @ulfalizer Could you document templates in the Zephyr documentation?

Added documentation for the header format. See the new `doc: kconfig: Document recommended header format` commit.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by finikorg** [comment]
> > @ulfalizer Could you document templates in the Zephyr documentation?
> 
> Added documentation for the header format. See the new `doc: kconfig: Document recommended header format` commit.

Thanks! That is what I meant.

**Pull request merged**
