### PR TITLE
coding guidelines: comply with MISRA C:2012 Rule 11.9

### PR DESCRIPTION
**Pull request by Abramo-Bagnara**
In particular:

- avoid to obtain an unwanted null pointer

Signed-off-by: Abramo Bagnara <abramo.bagnara@bugseng.com>

### CODE REVIEW

**Review by peter-mitsis — COMMENTED** [review]
I think the comment needs a little more clarification to indicate why we want to avoid constructing a null pointer. Something along the lines of ... 

"... to avoid constructing a null pointer (as per Zephyr coding guidelines rule 11.9) when ..."

Rationale: This change is somewhat esoteric. Without a more clear reason I worry that someone in the future is going to undo it without understanding why it was there in the first place.

**Comment by Abramo-Bagnara** [comment]
I guess there is a misunderstanding: apart MISRA rule 11.9 (that has helped to spot that), to build a null pointer instead of a 0-value fixed address is unwanted and not what it is meant when CONFIG_KERNEL_VM_BASE is 0.

According to C standard a null pointer is not a pointer to address 0, but a non-dereferenceable pointer to nowhere.

**Comment by dcpleung** [comment]
`Z_VIRT_RAM_START` is a pointer simply because we pass around addresses where `uint8_t *` is for virtual addresses and `uintptr_t` is for physical addresses. It is not constructed as a NULL pointer in any way if value is zero.

**Comment by Abramo-Bagnara** [comment]
According to C standard if CONFIG_KERNEL_VM_BASE is defined to 0 then

```#define Z_VIRT_RAM_START	((uint8_t *)CONFIG_KERNEL_VM_BASE)```

definitely expands to a NULL pointer, while ((uint8_t *)((void) 0, (uintptr_t)CONFIG_KERNEL_VM_BASE)) is a zero-value fixed address pointer.

C99 6.3.2.3p3: An integer constant expression with the value 0, or such an expression cast to type
void *, is called a null pointer constant.

C99 6.6p3: Constant expressions shall not contain assignment, increment, decrement, function-call,
or comma operators, except when they are contained within a subexpression that is not
evaluated.

**Review by peter-mitsis — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
