### PR TITLE
samples: mesh/onoff_level_lighting_vnd_app: corrected state binding & overall architecture

### PR DESCRIPTION
**Pull request by vikrant8052**
Update models publication message lengths as per Mesh Model
Specification. Fixed bug in binding of Light Lightness Actual
state & Generic Level state of Root Element. Update message
handlers & correct number of bytes that every handlers should
consider for their further processing as per Bluetooth SIG Mesh
Model Specification. Removed TID implementations wherever it is
not required as per Bluetooth SIG Mesh Model Specification.
Removed unnecessary comments. Add status code value to get publish
along with Light Lightness range status message.

### CODE REVIEW

**Comment by vikrant8051** [comment]
This for reference to all who are interested,

Under "**Definitions of models publication context**" I have maintain format of 
<opcode length> + <paramters length>

**Comment by vikrant8051** [comment]
https://www.bluetooth.com/develop-with-bluetooth/qualification-listing/qualification-test-tools/profile-tuning-suite

PTS is the tool that we must run against any commercial Bluetooth product before releasing it to the market. Zephyr maintainers run it periodically against the Zephyr Bluetooth stack, but it hasn't been run against new mesh (**Lighting**) models yet.

**Comment by vikrant8051** [comment]
PTS will be tested before next release (Zephyr 1.13). The PTS implements the tests found in the Mesh Model Test Specification, so that's by far the best way to ensure conformance with the specification. Reading the Test Specification is also a good way to sort out ambiguities in the Model Specification, since normally the Test Specification takes precedence over the Profile/Model specification.

**Comment by vikrant8051** [comment]
This is reference link for Test Specification: 
https://www.bluetooth.com/specifications/qualification-test-requirements#Mesh

**Comment by vikrant8051** [comment]
Hi @MariuszSkamra,
I need your help to test $zephyr/samples/boards/nrf52/mesh/onoff_level_lighting_vendor_app against PTS after merging this PR or it will be great, if you patched this PR with already available App & run PTS against it. 

Thank You !!

**Comment by vikrant8051** [comment]
@jhedberg Please merge it now.

Sorry for inconvenience you faced till date because of my unawareness about git commands :( but I'm in learning phase.

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by vikrant8051** [comment]
Thank you @jhedberg & @carlescufi.

**Pull request merged**
