### PR TITLE
Drivers: SPI: Implemented External Demultiplexing on SAME70

### PR DESCRIPTION
**Pull request by jmahkye**
The SAM E70 can now use an external DEMUX (4 to 160
for CS lines. This feature was previously unimplemented
and gives the user scope to use 15 CS lines instead of 4.

Signed-off-by: Jean-Marc Ah-Kye <jean-marc.ah-kye@cdo2.com>

### CODE REVIEW

**Comment by jmahkye** [comment]
Could I have some advice or how to sort resolve the conflict? Because I thought I resolved it with my last commit and I also cannot see any conflicts on my local repo.

**Comment by nandojve** [comment]
Hi @jmahkye ,

You need to follow [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/index.html). Zephyr uses fast-forward on the main repository and it is recommended you rebase every time before send an update. Merge is forbitten.

As a remind, you can run locally compliances check and a reduced tests set before send you PR. There are tools to do it and it is all documented.

My suggestion is you squash your commit and than fetch + rebase upstream/main and, finally, push -f.

**Review by tbursztyka — CHANGES_REQUESTED** [review]
Can you rebase your PR so only the commits you add appear ? (don't merge main into it, just rebase your branch against main branch instead)

**Comment by jmahkye** [comment]
Do I need to revert my previous rebase? and then redo it?

**Comment by nandojve** [comment]
Hi @jmahkye ,

We want to see only your commit `Drivers: SPI: Implemented External Demultiplexing on SAME70`
I recommend that you read [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/index.html), in special, Contribution Workflow.

I'm closing this for now. You can reopen at anytime after you have figure out git or you can just send another PR.

**Pull request closed without merging**
