### PR TITLE
Bluetooth: Audio: Add fallbacks codec functions that have an implied value (per the BAP spec)

### LINKED ISSUE #71597: LE Audio: Synchronize behavior of `bt_audio_codec_cfg_get_chan_allocation` and `bt_audio_codec_cfg_get_frame_blocks_per_sdu`
**Is your enhancement proposal related to a problem? Please describe.**
The values in the codec configuration for channel allocation and frame blocks per SDU both have an implicit value (`0` for the former, `1` for the latter). 

`bt_audio_codec_cfg_get_chan_allocation` is defined as 
```c
int bt_audio_codec_cfg_get_chan_allocation(const struct bt_audio_codec_cfg *codec_cfg,
					   enum bt_audio_location *chan_allocation)
```
and returns an error if the value is not found. 

`bt_audio_codec_cfg_get_frame_blocks_per_sdu` is 
```c
int bt_audio_codec_cfg_get_frame_blocks_per_sdu(const struct bt_audio_codec_cfg *codec_cfg,
						bool fallback_to_default)
```
and returns `1` if `fallback_to_default` is true and the value is not found.

**Describe the solution you'd like**
These two functions should have the same behavior. Either both should return an error if the value is not found, or both should have a `fallback_to_default` option. 

**Describe alternatives you've considered**
N/A

**Additional context**
The default behavior of these are defined in BAP 1.0.1 section 4.3.2:

> The Audio_Channel_Allocation LTV structure defined in Bluetooth Assigned Numbers [2] may be present in the Codec_Specific_Configuration field. The absence of the Audio_Channel_Allocation LTV structure shall be interpreted as a single channel with no specified Audio Location.

> The Codec_Frame_Blocks_Per_SDU LTV structure defined in Bluetooth Assigned Numbers [2] may be present in the Codec_Specific_Configuration field. The absence of the Codec_Frame_Blocks_Per_SDU LTV structure shall be interpreted as equivalent to a Codec_Frame_Blocks_Per_SDU value of 0x01.

### PR DESCRIPTION
**Pull request by Thalley**
BAP specifies that several of the codec config and codec capability values have an implied value if not explicitly set. 

fixes https://github.com/zephyrproject-rtos/zephyr/issues/71597#

### CODE REVIEW

**Comment by aescolar** [comment]
@Thalley a bit tangential but very related question: The BT audio APIs, are they considered unstable? (I guess not experimental anymore), and shouldn't it have a version doxygen tag similar to this: https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/bluetooth/bluetooth.h#L37-L38

Links:
* https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html
* https://docs.zephyrproject.org/latest/develop/api/overview.html#api-overview

**Comment by Thalley** [comment]
> @Thalley a bit tangential but very related question: The BT audio APIs, are they considered unstable? (I guess not experimental anymore), and shouldn't it have a version doxygen command similar to this: https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/bluetooth/bluetooth.h#L37-L38
> 
> Links:
> 
>     * https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html
> 
>     * https://docs.zephyrproject.org/latest/develop/api/overview.html#api-overview

We are in the progress of making them unstable instead of experimental: https://github.com/zephyrproject-rtos/zephyr/pull/72558

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
To reviewers: Noticed that a few other similar functions also have default values, so applied the same patch to them as well. Also fixed some found issues in the unit tests.

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Comment by larsgk** [comment]
> > @Thalley a bit tangential but very related question: The BT audio APIs, are they considered unstable? (I guess not experimental anymore), and shouldn't it have a version doxygen command similar to this: https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/bluetooth/bluetooth.h#L37-L38
> > Links:
> > ```
> > * https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html
> > 
> > * https://docs.zephyrproject.org/latest/develop/api/overview.html#api-overview
> > ```
> 
> We are in the progress of making them unstable instead of experimental: #72558

Please don't make them unstable ..... 🥁  (couldn't help it ;))

**Review by larsgk — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by larsgk — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by larsgk — DISMISSED** [review]

**Comment by Thalley** [comment]
Fixed CI issue

**Review by kruithofa — APPROVED** [review]

**Review by larsgk — APPROVED** [review]

**Pull request merged**
