### PR TITLE
fix new example location

### PR DESCRIPTION
**Pull request by kartben**

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
LGTM, thanks.

**Review by jukkar — APPROVED** [review]

**Comment by jukkar** [comment]
ping @kartben, do you have time to fix the issues that the sanitychecker is complaining?

**Comment by galak** [comment]
@kartben any plan to fix the issues reported by CI checks?

**Comment by jukkar** [comment]
As this PR seems to be abandoned, I created a new one at #23522 so this one can be closed.

**Pull request closed without merging**
