### PR TITLE
drivers: adc: support Nuvoton numaker m2l31x

### PR DESCRIPTION
**Pull request by cyliangtw**
This PR is to support ADC driver of Nuvoton NuMaker M2L31X series.

### CODE REVIEW

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by cyliangtw** [comment]
About the failing check of "`Run tests with twister / twister-build (1)`", it's not caused by this PR.
According to the build log, lpcxpresso55s69_lpc55s69_cpu0_ns seems fail to build `/tests/drivers/adc/adc_api/drivers.adc`.

The snippet of log as below:
```
/__w/zephyr/zephyr/tests/drivers/adc/adc_api/src/test_adc.c:45:2: error: #error "Unsupported board."
   45 | #error "Unsupported board."
      |  ^~~~~
```

**Comment by cyliangtw** [comment]
About "#error Unsupported board" of twister build on esp32/lpcxpresso55s69/mimxrt1176 platforms will be fixed in https://github.com/zephyrproject-rtos/zephyr/pull/71472

**Comment by cyliangtw** [comment]
Hi @fabiobaltieri , @ssekar15,
after PR https://github.com/zephyrproject-rtos/zephyr/pull/71472 was merged, this PR have  passed all checks.
if you are available, please look at this PR.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by cyliangtw** [comment]
Hi @ssekar15,
if you are available, please look at this PR.

**Review by ssekar15 — APPROVED** [review]
LGFM

**Review by ccli8 — APPROVED** [review]

**Pull request merged**
