### PR TITLE
drivers/sensor: lsm6dso: (FIX) enable interrupt selectively

### PR DESCRIPTION
**Pull request by ghost**
Issue detected at compilation time when CONFIG_LSM6DSO_ENABLE_TEMP flag enabled.
int2_route variable not initialized nor instanciated has been recently replaced by lsm6dso_int2_ctrl_t int2_ctrl;

### CODE REVIEW

**Comment by carlescufi** [comment]
@RomainArtifeel thanks for the contribution!

Please format the commit according to [our guidelines](https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines)

**Comment by RomainArtifeel** [comment]
@carlescufi  Thanks for the information : please find modifications.

**Review by gmarull — DISMISSED** [review]

**Comment by gmarull** [comment]
@RomainArtifeel please check compliance issues, seems like there's a commit formatting issue

**Review by avisconti — DISMISSED** [review]

**Review by MaureenHelm — COMMENTED** [review]
Thanks for the fix. Please rebase to pick up #42691, which will fix the twister failure. You'll also need to update your commit message to address the compliance failure:
```
Error: See docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

fb7fe6f72b937a4040bc603447b59b9021a19434: author email (RomainArtifeel <96049046+RomainArtifeel@users.noreply.github.com>) needs to match one of the signed-off-by entries.
fb7fe6f72b937a4040bc603447b59b9021a19434: author email (RomainArtifeel <96049046+RomainArtifeel@users.noreply.github.com>) does not follow the syntax: First Last <email>.
```

**Comment by MaureenHelm** [comment]
Why did you close this PR?

**Comment by petterssonandreas** [comment]
Since this PR was closed for some reason, I made a new PR: https://github.com/zephyrproject-rtos/zephyr/pull/44873

**Pull request closed without merging**
