### PR TITLE
C++ compat fix for LE Audio

### PR DESCRIPTION
**Pull request by jefffhaynes**
Designator order fix for compiling under C++.

### CODE REVIEW

**Review by Thalley — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]
Please provide commit message and amend `Signed-off-by:` line

**Comment by jefffhaynes** [comment]
Sorry, I probably just screwed this up.  I wasn't sure if it was waiting for me to do something and somehow I accidentally pushed a commit trying to sync my local repo.  Was the note from @MariuszSkamra for me or someone else?

Feel free to delete this PR.  Feels like more trouble than it's worth.

**Comment by Thalley** [comment]
> Sorry, I probably just screwed this up. I wasn't sure if it was waiting for me to do something and somehow I accidentally pushed a commit trying to sync my local repo. Was the note from @MariuszSkamra for me or someone else?
> 
> Feel free to delete this PR. Feels like more trouble than it's worth.

@jefffhaynes That was for you :) Please read https://docs.zephyrproject.org/latest/contribute/guidelines.html

3 things you need to fix for this PR:
1) A commit must have a commit message besides the first line
2) The commit headline must follow a pattern to note where it is adding/fixing something. In your case, the headline must be something like `bluetooth: Audio: C++ compat fix for LE Audio`
3) When modifying commits in a PR, please rebase and force push to avoid adding more commits. In this case, your PR should only be a single commit

**Review by Thalley — CHANGES_REQUESTED** [review]
Commits must be fixed

**Pull request closed without merging**
