### PR TITLE
TFM: Update dependencies to 1.6

### PR DESCRIPTION
**Pull request by theotherjimmy**
@microbuilder 

Signed-off-by: Jimmy Brisson <jimmy.brisson@linaro.org>

### CODE REVIEW

**Comment by theotherjimmy** [comment]
Updated PR dependencies. Force-pushed to re-trigger CI

**Comment by theotherjimmy** [comment]
I can't reproduce the errors locally :/

**Comment by theotherjimmy** [comment]
As far as I can tell, it's missing the version information from the command that signs the image. I can't imagine why.

**Comment by microbuilder** [comment]
> As far as I can tell, it's missing the version information from the command that signs the image. I can't imagine why.

This fails for me after a `west update`:

```bash
$ west build -p always -b mps2_an521_ns zephyr/samples/tfm_integration/tfm_secure_partition -t run
```

**Comment by theotherjimmy** [comment]
I don't know what I'm doing that's allowing this to continue, but that works on my system.

**Comment by microbuilder** [comment]
> I don't know what I'm doing that's allowing this to continue, but that works on my system.

What version of `imgtool` are you using?

```bash
$ imgtool version
1.8.0
```

**Comment by theotherjimmy** [comment]
```
    ; imgtool version
1.8.0
```

**Comment by theotherjimmy** [comment]
I know why mine works and yours does not. Rajkumar, through private chat, informed me that there's another place that uses the imgtool sign script: https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/31d4dce684178ce55eea7f6766a4ba99fc8e4675/bl2/ext/mcuboot/CMakeLists.txt#L138

Which is based on the TFM_VERSION variable:https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/31d4dce684178ce55eea7f6766a4ba99fc8e4675/bl2/ext/mcuboot/mcuboot_default_config.cmake#L52

Which is based on a git tag: https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/31d4dce684178ce55eea7f6766a4ba99fc8e4675/cmake/version.cmake

Which I have in my module:
```
    ; git -C modules/tee/tf-m/trusted-firmware-m/ tag -v TF-Mv1.6.0-RC3
object d9d497bde9399574487a2cfba4c1e6e6f4168dca
type commit
tag TF-Mv1.6.0-RC3
tagger Anton Komlev <anton.komlev@arm.com> 1649930862 +0100

Trusted Firmware-M v1.6.0 Release Candidate 3
```

Removing all tags reproduced the build error on my machine!

**Comment by theotherjimmy** [comment]
Looks like the tests I wrote for psa firmware update are failing with a secure fault because of an invalid entrypoint.

**Comment by microbuilder** [comment]
@theotherjimmy Do you mind updating this to point to the final 1.6.0 release? Thanks.

**Comment by erwango** [comment]
Tested `samples/tfm_integration/tfm_ipc` ok on `b_u585i_iot02a` and `stm32l562e_dk`.

**Comment by microbuilder** [comment]
@joerchan Can you let us know if this seems OK for the Nordic boards?

**Comment by microbuilder** [comment]
I'm happy with this once the dependencies are merged in.

If people can please test and those of you who are able to approve related PRs make a decision, I'd really like to get this in before Friday. Please review is possible.

**Comment by carlescufi** [comment]
@theotherjimmy please replace refs with SHAs in `west.yml`.

**Comment by theotherjimmy** [comment]
@carlescufi Done, with a rebase.

**Review by microbuilder — APPROVED** [review]
Thanks for all the hard work on this, Jimmy.

**Comment by microbuilder** [comment]
@carlescufi Do the release notes documenting the TF-M and MbedTLS update need to go into this PR, or in a separate one?

**Review by joerchan — APPROVED** [review]
The nordic boards look good with these changes.
I've run the PSA arch tests and the regression tests and all looks good.

@theotherjimmy Thank you for the hard work.

Checked the SHAs.

**Review by carlescufi — APPROVED** [review]
ACK on SHAs

**Comment by carlescufi** [comment]
> @carlescufi Do the release notes documenting the TF-M and MbedTLS update need to go into this PR, or in a separate one?

@microbuilder @theotherjimmy there is no real consensus on this matter. It can go either way. I'd ask you or @joerchan to volunteer to update the release notes with this info when we are close to releasing.

**Comment by microbuilder** [comment]
> @microbuilder @theotherjimmy there is no real consensus on this matter. It can go either way. I'd ask you or @joerchan to volunteer to update the release notes with this info when we are close to releasing.

I'll update them pre-release.

**Pull request merged**
