### PR TITLE
scripts: checkpatch: add Co-authored-by tag

### PR DESCRIPTION
**Pull request by bbilas**
Add `Co-authored-by` tag which is mainly used by Github.

FYI: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>

### CODE REVIEW

**Review by stephanosio — APPROVED** [review]
No objection to this change.

**Comment by stephanosio** [comment]
In the meantime, something is wrong:

```
eaaa0c13af010b5cffaae5a74f308f7ac59cb941:20: WARNING:BAD_SIGN_OFF: Do not use whitespace before Signed-off-by:
#20: FILE: scripts/checkpatch.pl:495:
 	Signed-off-by:|
...
```

This rule is not supposed to apply to the diffs:

https://github.com/zephyrproject-rtos/zephyr/blob/b2a4a3672f2128f9e3218141b532487515dc177c/scripts/checkpatch.pl#L2670

We need to re-evaluate #44118.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
holy....

```
Error: See https://docs.zephyrproject.org/latest/contribute/#coding-style for more details.

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:20: WARNING:BAD_SIGN_OFF: Do not use whitespace before Signed-off-by:
#20: FILE: scripts/checkpatch.pl:495:
 	Signed-off-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:20: WARNING:BAD_SIGN_OFF: Use a single space after Signed-off-by:
#20: FILE: scripts/checkpatch.pl:495:
 	Signed-off-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:20: ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#20: FILE: scripts/checkpatch.pl:495:
 	Signed-off-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:[22](https://github.com/zephyrproject-rtos/zephyr/runs/6083963496?check_suite_focus=true#step:9:22): WARNING:BAD_SIGN_OFF: Do not use whitespace before Co-developed-by:
#22: FILE: scripts/checkpatch.pl:497:
 	Co-developed-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:22: WARNING:BAD_SIGN_OFF: Use a single space after Co-developed-by:
#22: FILE: scripts/checkpatch.pl:497:
 	Co-developed-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:22: ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#22: FILE: scripts/checkpatch.pl:497:
 	Co-developed-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:22: WARNING:BAD_SIGN_OFF: Co-developed-by: must be immediately followed by Signed-off-by:
#22: FILE: scripts/checkpatch.pl:497:
 	Co-developed-by:|
 	Acked-by:|
eaaa0c13af010b5cffaae5a74f308f7ac59cb941:[23](https://github.com/zephyrproject-rtos/zephyr/runs/6083963496?check_suite_focus=true#step:9:23): WARNING:BAD_SIGN_OFF: Do not use whitespace before Acked-by:
#23: FILE: scripts/checkpatch.pl:498:
 	Acked-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:23: WARNING:BAD_SIGN_OFF: Use a single space after Acked-by:
#23: FILE: scripts/checkpatch.pl:498:
 	Acked-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:23: ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#23: FILE: scripts/checkpatch.pl:498:
 	Acked-by:|

eaaa0c13af010b5cffaae5a74f308f7ac59cb941:[24](https://github.com/zephyrproject-rtos/zephyr/runs/6083963496?check_suite_focus=true#step:9:24): WARNING:BAD_SIGN_OFF: Do not use whitespace before Tested-by:
#24: FILE: scripts/checkpatch.pl:499:
 	Tested-by:|

eaaa0c13af010b5cffaae5a74f[30](https://github.com/zephyrproject-rtos/zephyr/runs/6083963496?check_suite_focus=true#step:9:30)8f7ac59cb9[41](https://github.com/zephyrproject-rtos/zephyr/runs/6083963496?check_suite_focus=true#step:9:41):24: WARNING:BAD_SIGN_OFF: Use a single space after Tested-by:
#24: FILE: scripts/checkpatch.pl:[49](https://github.com/zephyrproject-rtos/zephyr/runs/6083963496?check_suite_focus=true#step:9:49)9:
 	Tested-by:|

eaaa0c13af010b5cffaae5a74f308f7ac[59](https://github.com/zephyrproject-rtos/zephyr/runs/6083963496?check_suite_focus=true#step:9:59)cb941:24: ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#24: FILE: scripts/checkpatch.pl:499:
 	Tested-by:|
```

**Comment by bbilas** [comment]
@stephanosio @nashif Unfortunately I'm not a Perl expert so someone else needs to take a look at it.

**Comment by stephanosio** [comment]
> @stephanosio @nashif Unfortunately I'm not a Perl expert so someone else needs to take a look at it.

Don't worry about it. I will look into it.

**Review by stephanosio — APPROVED** [review]
Although we have currently disabled commit message checking using the checkpatch in #44984, I am going to merge this since we may decide to re-enable it in the future, and this change is valid either way.

**Pull request merged**
