### PR TITLE
manifest: mbedtls: bump to 3.6.0

### PR DESCRIPTION
**Pull request by tomi-font**
https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.6.0
See details in commit messages.

### CODE REVIEW

**Comment by tomi-font** [comment]
FYI @ceolin @d3zd3z @dleach02

**Comment by tomi-font** [comment]
This is ready for review. @d3zd3z @ceolin @dleach02 @SebastianBoe

**Review by frkv — APPROVED** [review]
LGTM (pending adding dependency manifests inn and updating the SHA)

Great effort making sure TF-M 2.1.0 can be taken in in a reasonable time before Zephyr LTS

**Review by mswarowsky — APPROVED** [review]
Cannot judge on the mcuboot changes, but the rest looks ok for me

**Review by ithinuel — APPROVED** [review]

**Review by SebastianBoe — APPROVED** [review]
Leaving a green +1 because @mswarowsky and @frkv have reviewed with grey +1's.

**Review by frkv — APPROVED** [review]
Final LGTM +1

**Review by ceolin — APPROVED** [review]

**Pull request merged**
