### PR TITLE
doc: Getting Started: Add a note about building the blinky sample

### LINKED ISSUE #23169: "blinky" sample fails to build for BBC MicroBit (DT_ALIAS_LED0_GPIOS_CONTROLLER undefined)
**Describe the bug**
Following along in the Getting Started guide, I tried to build the "blinky" sample for the BBC MicroBit board. It fails due to a C compile error; apparently the constants for the LED0 pin are not defined as expected. The sample does build for the `reel_board`.

**To Reproduce**
1. Setup zephyr as per Getting Started Guide, steps 1-5
2. Follow step 6 by entering `west build -p auto -b bbc_microbit samples/basic/blinky`

**Expected behavior**
The build succeeds

**Impact**
To actually run the sample I need to build it for a board I have in my possession.
I would expect a minimal sample like this to build successfully for every supported board, especially since the guide doesn't specify any particular board but implies any will work.
I do own two other supported boards so I'm not dead in the water yet, but this is disappointing.

**Screenshots or console output**
```
[34/122] Building C object CMakeFiles/app.dir/src/main.c.obj
FAILED: CMakeFiles/app.dir/src/main.c.obj 
ccache /Users/snej/Couchbase/Embedded/Toolchain/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc -DBUILD_VERSION=v2.2.0-rc2-41-gb96477dd69bb -DKERNEL -DNRF51 -D_FORTIFY_SOURCE=2 -D__PROGRAM_START -D__ZEPHYR__=1 -I/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/include -Izephyr/include/generated -I/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/soc/arm/nordic_nrf/nrf51 -I/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/ext/hal/cmsis/Core/Include -I/Users/snej/Couchbase/Embedded/zephyrproject/modules/hal/nordic/nrfx -I/Users/snej/Couchbase/Embedded/zephyrproject/modules/hal/nordic/nrfx/drivers/include -I/Users/snej/Couchbase/Embedded/zephyrproject/modules/hal/nordic/nrfx/mdk -I/Users/snej/Couchbase/Embedded/zephyrproject/modules/hal/nordic/. -isystem /Users/snej/Couchbase/Embedded/zephyrproject/zephyr/lib/libc/minimal/include -isystem /Users/snej/Couchbase/Embedded/Toolchain/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/include -isystem /Users/snej/Couchbase/Embedded/Toolchain/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/include-fixed -Os -imacros/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mthumb -mcpu=cortex-m0 -imacros/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-address-of-packed-member -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/samples/basic/blinky=CMAKE_SOURCE_DIR -fmacro-prefix-map=/Users/snej/Couchbase/Embedded/zephyrproject/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/Users/snej/Couchbase/Embedded/zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections -mabi=aapcs -march=armv6s-m -std=c99 -nostdinc -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj   -c /Users/snej/Couchbase/Embedded/zephyrproject/zephyr/samples/basic/blinky/src/main.c
/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/samples/basic/blinky/src/main.c: In function 'main':
/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/samples/basic/blinky/src/main.c:24:27: error: 'DT_ALIAS_LED0_GPIOS_CONTROLLER' undeclared (first use in this function); did you mean 'DT_ALIAS_SW0_GPIOS_CONTROLLER'?
   24 |  dev = device_get_binding(DT_ALIAS_LED0_GPIOS_CONTROLLER);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           DT_ALIAS_SW0_GPIOS_CONTROLLER
/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/samples/basic/blinky/src/main.c:24:27: note: each undeclared identifier is reported only once for each function it appears in
/Users/snej/Couchbase/Embedded/zephyrproject/zephyr/samples/basic/blinky/src/main.c:29:32: error: 'DT_ALIAS_LED0_GPIOS_PIN' undeclared (first use in this function); did you mean 'DT_ALIAS_SW0_GPIOS_PIN'?
   29 |  ret = gpio_pin_configure(dev, DT_ALIAS_LED0_GPIOS_PIN,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~
      |                                DT_ALIAS_SW0_GPIOS_PIN
[47/122] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/clock_control/nrf_power_clock.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /Users/snej/Couchbase/Embedded/zephyrproject/zephyr/build
```

**Environment (please complete the following information):**
 - OS: macOS 10.15.3
 - Toolchain: GCC-ARM
 - Commit: b96477dd69bbc6b1830048e8eee59cf62c3684da (HEAD -> master, origin/master)

### PR DESCRIPTION
**Pull request by carlescufi**
See commit messages.
CC @snej.

Fixes #23169.

### CODE REVIEW

**Comment by mbolivar** [comment]
No objections to this PR, but this is a widespread problem with devicetree.

If we are going to take it seriously instead of just papering over it when a particular user notices it in a particular sample, we really ought to add build system support for semantics like "refuse to build this sample if the devicetree doesn't have a led0 alias, and print a clear error message if someone tries". This would also avoid the need for an FAQ that people wouldn't read anyway ;).

**Comment by carlescufi** [comment]
> No objections to this PR, but this is a widespread problem with devicetree.
> 
> If we are going to take it seriously instead of just papering over it when a particular user notices it in a particular sample, we really ought to add build system support for semantics like "refuse to build this sample if the devicetree doesn't have a led0 alias, and print a clear error message if someone tries". This would also avoid the need for an FAQ that people wouldn't read anyway ;).

Well, this is the sample at the end of the Getting Started Guide, so "papering over" might be a bit of an overstatement here. It is true that at some point we might switch samples, but "blinky" is a very typical starting point in RTOS like Zephyr.
I completely agree with the proposal to add build system support you refer to, but I disagree with the statement that claims a FAQ would not be read by users. You might underestimate how well Google indexes our documentation pages :)

**Comment by mbolivar** [comment]
> Well, this is the sample at the end of the Getting Started Guide, so "papering over" might be a bit of an overstatement here. It is true that at some point we might switch samples, but "blinky" is a very typical starting point for an RTOS like Zephyr.

Blinky is of course the hello world of embedded, but I still think solving this particular problem in documentation is a form of papering over a wider issue in a specific context.

Though I do agree this patch is an improvement!

> I completely agree with the proposal to add the build system support you refer to, but I disagree with the statement that claims a FAQ would not be read by users. You might underestimate how well Google indexes our documentation pages :)

Google's work is great, but that assumes people are [savvy to the relevant techniques](https://raw.githubusercontent.com/thepracticaldev/orly-full-res/master/googlingtheerrormessage-big.png) ...

**Comment by carlescufi** [comment]
> Google's work is great, but that assumes people are [savvy to the relevant techniques](https://raw.githubusercontent.com/thepracticaldev/orly-full-res/master/googlingtheerrormessage-big.png) ...

😆

**Review by jhedberg — APPROVED** [review]

**Comment by mbolivar** [comment]
@carlescufi what would you say to stacking this on top?

https://github.com/mbolivar/zephyr/tree/blinky-check-node

**Comment by carlescufi** [comment]
> @carlescufi what would you say to stacking this on top?
> 
> https://github.com/mbolivar/zephyr/tree/blinky-check-node

Looks great, thanks! can you push that to my branch? Not at my computer right now.

**Comment by mbolivar** [comment]
> Looks great, thanks! can you push that to my branch? Not at my computer right now.

Pushed a fixed up version and deleted my old branch.

**Comment by carlescufi** [comment]
Thanks @mbolivar!

**Pull request merged**
