### PR TITLE
arch: arm: stm32f7: Kconfig: select CPU_HAS_ARM_MPU

### PR DESCRIPTION
**Pull request by aurel32**
I am opening this PR as a way to discuss what should be done to enable MPU on the STM32F7 SoC, which compared to the previous series has cache at the CPU level.

From @erwango in PR #8647:
```
For flash, following settings are known to be working:
TEX0 , CACHEABLE =1, BUFFERABLE=0 , SHAREABLE=0
For peripherals, following should be used:
TEX0 , CACHEABLE =0, BUFFERABLE=1 , SHAREABLE=0
RAM should be set TEX0 , CACHEABLE =1. Other attributes (BUFFERABLE, SHAREABLE) could have various settings, but in order to save MPU sections we can set the same as Flash.
```

Currently the STM32 region definition is as follow (in `arch/arm/soc/st_stm32/common/arm_mpu_regions.c`):

```
static struct arm_mpu_region mpu_regions[] = {
        /* Region 0 */
        MPU_REGION_ENTRY("FLASH_0",
                         CONFIG_FLASH_BASE_ADDRESS,
                         REGION_FLASH_ATTR(REGION_FLASH_SIZE)),
        /* Region 1 */
        MPU_REGION_ENTRY("RAM_0",
                         CONFIG_SRAM_BASE_ADDRESS,
                         REGION_RAM_ATTR(REGION_SRAM_0_SIZE)),
        /* Region 2 */
        MPU_REGION_ENTRY("RAM_1",
                         (CONFIG_SRAM_BASE_ADDRESS + REGION_SRAM_1_START),
                         REGION_RAM_ATTR(REGION_SRAM_1_SIZE)),
};
```
From the attribute point of view, with the changes discussed in PR #8185, it is likely that:
- `REGION_RAM_ATTR` will be TEX0, CACHEABLE=1, BUFFERABLE=1, SHAREABLE=0
- `REGION_FLASH_ATTR `will be TEX0, CACHEABLE=1, BUFFERABLE=0, SHAREABLE=0

There is no peripherals entry, that said I am not sure one is needed, given the background 
has the same memory access attributes as the default memory, but accessible from privileged software only. None of the other SoC with an MPU configuration defines it, including the NXP IMX RT which has its cache enabled by default.

Now I wonder why there are two regions for the SRAM. They are contiguous and with the same property. In addition two that, there are wrong on the STM32F7, they are not split as 2 block identical size. Instead the RAM area start by the DTCM, followed by SRAM1 which is the main memory, followed by SRAM2 which is a small backup SRAM. I wonder if we should try to get the correct values from the device tree instead of `arch/arm/soc/st_stm32/common/arm_mpu_mem_cfg.h`.

The same way I guess the ITCM entry at address 0x00000000 is missing.

### CODE REVIEW

**Comment by andrewboie** [comment]
We know that #8185 in some form needs to be merged, but I don't know if @andyross has time to look into it further. Is there anyone who can pick up investigating that? I think we urgently need to fix the REGION_*_ATTR settings, they just aren't correct now.

The situation with the NXP MPU is even worse, see #7705

**Comment by erwango** [comment]
@aurel32 
> Now I wonder why there are two regions for the SRAM. They are contiguous and with the same property. 

IIRC, this was made originally due to the power of 2 constraint. Region size should be power of 2 and for some RAM sizes, it would create a too big region. So it was split in 2 regions with same attributes so RAM1 + RAM2 region would be better fit to the actual RAM size

**Comment by aurel32** [comment]
> IIRC, this was made originally due to the power of 2 constraint. Region size should be power of 2 and for some RAM sizes, it would create a too big region. So it was split in 2 regions with same attributes so RAM1 + RAM2 region would be better fit to the actual RAM size.

Ok, I get it now, I thought the goal was to match the different memory banks from the chip. In that case the mapping correctly covers DTCM + SRAM1 + SRAM2 on the STM32F7 family. The backup RAM is mapped as a peripheral, so the current code is also fine.

I guess it's therefore only missing the ITCM mapping, that said I don't think Zephyr currently provide a way to use it, at least not easily.

**Comment by erwango** [comment]
@aure32, what are your plans for this PR?

**Comment by aurel32** [comment]
@erwango, it seems support for caches + MPU enabled is still not fully working in Zephyr. I have opened issue #11069 mostly targeting the Atmel SAM E70, but I believe it also more or less apply to the STM32F7, given it has the caches enabled:
- arm_core_mpu_disable() is very likely missing a barrier like in the documentation
- enabling shareability on the RAM cause issues on the SAM E70, while it doesn't on the STM32F7 (or it could be that I haven't been able to reproduce them). In any case the Cortex M7 technical reference manual clearly says that cacheable shared locations are treated as being non-cacheable if CACR.SIWT = 0 (default) or as write-through if CACR.SIWT. We do not want that enabling the MPU disables the cache, so this has to be fixed.

For both this issues, I wanted to wait the confirmation that the test patch from #11069 actually fixes the issue seen on the SAM E70. Personally I have only been able to reproduce the issue on older Zephy versions, but I have also seen that the issue is very dependent on code/data location and alignment, and thus on the toolchain. Anyway, I am now convinced that the above two points are real bugs (even if they might not explain the original issue with the Atmel SAM E70), so I can prepare a pull request.

For the STM32F7, there is also the question of the ITCM memory. There is currently no MPU region affected to it, but we also do not provide a way to place code there, so maybe it's better to just ignore the issue for now.

After all of that I think we can safely enable the MPU on the STM32F7.

**Comment by erwango** [comment]
@aurel32 , fine then, thanks for detailed heads-up.

**Comment by aurel32** [comment]
@erwango, I believe it's now safe to enable the MPU on the STM32F7. I have just pushed a rebased version and removed the DNM tag.

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
