### PR TITLE
DTS: Convert MCUX ethernet to DT_INST/DT_NODELABEL usage

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
@MaureenHelm I have a question about how we might want to handle `ETH_MCUX_1_MAC_SELECT` in Kconfig.

Options I see:
1. Remove the option and just have the MAC address selection be the same regardless of instance (ie, if you have 2 ethernet controllers you get the setting of MAC_SELECT for both)
2. Move this to be a DTS property, makes the per instance choice a DTS property.
3. Interpret ETH_MCUX_1_MAC_SELECT to be for instance #1 and not `enet2`.

Thoughts?

**Comment by galak** [comment]
@jukkar 

> Options I see:
> 
> 1. Remove the option and just have the MAC address selection be the same regardless of instance (ie, if you have 2 ethernet controllers you get the setting of MAC_SELECT for both)
> 2. Move this to be a DTS property, makes the per instance choice a DTS property.
> 3. Interpret ETH_MCUX_1_MAC_SELECT to be for instance #1 and not `enet2`.
> 
> Thoughts?

@jukkar would appreciate your thoughts on how we interpret or handle these ethernet Kconfig symbols w/regards to changes in how we are doing things w/devicetree?

**Comment by jukkar** [comment]
What looks a bit weird is the replacement of `eth` to `enet`, I would prefer `eth` to be used as that is generic name for Ethernet interface and other boards use that name.
Other than that, I do not have any preference here as long as everything works ok.

**Comment by galak** [comment]
> What looks a bit weird is the replacement of `eth` to `enet`, I would prefer `eth` to be used as that is generic name for Ethernet interface and other boards use that name.
> Other than that, I do not have any preference here as long as everything works ok.

The use of 'enet' is based on the SoC UM and as such we've in general agreed on having that be a standard naming convention for devicetree nodelabel.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
