### PR TITLE
drivers/flash: select to allow flash write by MPU on ARM SoCs

### PR DESCRIPTION
**Pull request by nvlsianpu**
Added selection of MPU_ALLOW_FLASH_WRITE.
Using a flash driver while MPU is enable without
this option on doesn't make sense at all.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
I should did patch like that long time ago - but had idea and hope on better MPU area granularity on embedded flash.

**Review by Laczen — APPROVED** [review]

**Comment by ioannisg** [comment]
> I should did patch like that long time ago - but had idea and hope on better MPU area granularity on embedded flash.

@nvlsianpu the granularity on embedded flash won't come, until someone asks for it. Could you briefly specify your requirements for this?

**Review by ioannisg — COMMENTED** [review]
I don't like so much that this is done only for nrf, we are creating an inconsistency. Unless all other socs don't have that problem.

**Review by Laczen — CHANGES_REQUESTED** [review]
After studying ARM_MPU I agree with @ioannisg, some work should be put in granularity for flash writing, the flash writing should use the ARM_MPU to modify access to flash. The option MPU_ALLOW_FLASH_WRITE should be avoided.

**Comment by nvlsianpu** [comment]
@ioannisg @Laczen 
Actually this is the old story I had  signaled long time ago.
https://github.com/zephyrproject-rtos/zephyr/issues/5151

Currently MPU_ALLOW_FLASH_WRITE might be selected per each driver which requires it (so each SoC embedded flash diver on ARM core with MPU). Is this solution you can accept until better solution will come?

**Comment by Laczen** [comment]
> @ioannisg @Laczen
> Actually this is the old story I had signaled long time ago.
> #5151
> 
> Currently MPU_ALLOW_FLASH_WRITE might be selected per each driver which requires it (so each SoC embedded flash diver on ARM core with MPU). Is this solution you can accept until better solution will come?

Actually after some more reading I am doubting if we should use ARM_MPU for flash protection. What would the protection be against ? Malicious code or user error ? If it is malicious code are we sure that there is no method to work around the ARM_MPU, I guess there is. If it is user error it might be better to wrap this in something like flash_map (with constant region defines) and to do it for all devices independent of ARM_MPU.

**Comment by nvlsianpu** [comment]
Problem with that someone try write to SoC flash while MPU disallow that comes back all the time (most recent https://github.com/zephyrproject-rtos/zephyr/issues/27928). It is almost a bug that
@ioannisg Is that PR acceptable?

**Comment by nvlsianpu** [comment]
@ioannisg @carlescufi @nashif please revisit

**Comment by nvlsianpu** [comment]
> Actually after some more reading I am doubting if we should use ARM_MPU for flash protection. What would the protection be against ? Malicious code or user error ? If it is malicious code are we sure that there is no method to work around the ARM_MPU, I guess there is. If it is user error it might be better to wrap this in something like flash_map (with constant region defines) and to do it for all devices independent of ARM_MPU.

Have similar doubts, but this PR aim to soothe problem caused by MPU related issue, not to introduce better protection.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
> Have similar doubts, but this PR aim to soothe problem caused by MPU related issue, not to introduce better protection.

@Laczen I agree with @nvlsianpu here, point of this PR is not t rework MPU protection for flash but smoothen things for users (as several get trapped with this).

**Review by Laczen — APPROVED** [review]

**Comment by erwango** [comment]
@nvlsianpu would you mind rebasing ?

**Comment by nashif** [comment]
@nvlsianpu would you mind rebasing ?

**Review by nashif — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@nashif rebased

**Pull request merged**
