### PR TITLE
drivers: ssd16xx: rework (use bytestring property for LUT and registers)

### PR DESCRIPTION
**Pull request by jfischer-no**
drivers: ssd16xx: rework (use bytestring property for LUT and registers)
use case for #17395

WIP, there is more to improve and use cases for bytestring, updates will follow. ssd16xx_hink_e0154a05.overlay probably not correct (controller-* properties)

### CODE REVIEW

**Review by pabigot — COMMENTED** [review]
Yes, this is the general idea.  `SOFT_START` and possibly `GDV` are also candidates for bytestring values for this driver.

**Comment by vanwinkeljan** [comment]
Looks like a nice solution
Only problem that is see is that the actual LUT values ends up in a overlay file in the CFB sample.
Do you know of any device tree tric to make this DTS common?

**Comment by pabigot** [comment]
With the merge of #17354 you could have a directory of devicetree include files that can be included, but because the properties are at the same level as target-specific properties you have to do something like this:
```
&spi1 { /* */
        /* Override MISO to undefined pin */
        miso-pin = <63>; /* not connected */
        display@0 {
                reg = <0>;

                busy-gpios = <&gpio1 1 0>;
                rst-gpios = <&gpio1 2 0>;
                dc-gpios = <&gpio1 8 0>;

#if 0 /* 1in54 */
#include "waveshare,1in54.dtsi"
#elif 1 /* 1in54b */
#include "waveshare,1in54b.dtsi"
#elif 0 /* 4in2 */
#include "waveshare,4in2.dtsi"
#endif /* edp */
        };
};
```
I'm not sure if Kconfig symbols can be used when processing devicetree source; if so then the conditionals could be cleaned up.

**Comment by jfischer-phytec-iot** [comment]
>Only problem that is see is that the actual LUT values ends up in a overlay file in the CFB sample.

It is a temporary solution. I ordered a WS e-Paper Shield, maybe it is cleaner to create a shield for each display, for example `ws_hink_eo213g01`, I am trying it out.

**Comment by jfischer-phytec-iot** [comment]
ws_e_paper_shield


quickly hacked `boards/shields/ws_hink_eo213g01`.  Something like `boards/shields/arduino_epd_shield_* ` could also a good place for respective display documentation.

**Comment by pabigot** [comment]
Problems with the shield approach include:
* not every device will access the display through a shield;
* not every device (nrf52840_pca10056 I'm looking at you) provides pin assignments compatible with shields in the default device tree.

So while it's nice to have the device attributes paired with the bus and target-specific GPIO assignments in a self-contained devicetree node, the shield overlays will not eliminate the need to access display-specific property values in other overlays for other targets.

**Comment by jfischer-phytec-iot** [comment]
>not every device will access the display through a shield;

It is either a kind of shild or a component on the board. 

>not every device (nrf52840_pca10056 I'm looking at you) provides pin assignments compatible with shields in the default device tree.

That can be fixed, but maybe not for every device, I can do it for nrf52840_pca10056.

**Comment by pabigot** [comment]
> > not every device will access the display through a shield;
> 
> It is either a kind of shield or a component on the board.

Or a non-shield dev board using whatever pins are available.  I don't object to having a shield in Zephyr, I just want to point out that putting the data in a shield doesn't eliminate the problem of having to replicate display-specific properties in multiple locations when targets use the same display.  I don't know if it's worth trying to solve that.  In my development I'll use the technique I demonstrated of including a file with just display-specific properties into the target-specific devicetree node.

> > not every device (nrf52840_pca10056 I'm looking at you) provides pin assignments compatible with shields in the default device tree.
> 
> That can be fixed, but maybe not for every device, I can do it for nrf52840_pca10056.

See #13708 and #14255.  The problem just needs renewed attention, so we don't have to patch samples every couple weeks when somebody tries a new shield/dev-kit combination (e.g. #17473).  @carles fyi.

**Review by vanwinkeljan — APPROVED** [review]

**Comment by galak** [comment]
@jfischer-phytec-iot can you rebase this.

**Comment by ioannisg** [comment]
@jfischer-phytec-iot I moved this to 2.1 release, assuming this won't be worked until the deadline for 2.0. If there is a chance to finalize review and get it in for 2.0, pls, set 2.0 milestone.

**Comment by galak** [comment]
> ```
> 
> ```
> 
> 
> I'm not sure if Kconfig symbols can be used when processing devicetree source; if so then the conditionals could be cleaned up.

Kconfig symbols can't be used in DTS.

**Comment by jfischer-phytec-iot** [comment]
@pabigot @MaureenHelm @galak I need it for #17742 and #17741. Is something against it to merge?

**Review by pabigot — APPROVED** [review]
Seems fine.  I'd like to see a general solution for sharing devicetree fragments outside of shields (which was apparently my concern originally) but that's orthogonal to this PR in its current form.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
