### PR TITLE
github: Add support for using github workflow labeler

### PR DESCRIPTION
**Pull request by galak**
Converted the ci-tools/scripts/what_changed.py table into
.github/labeler.yml.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by nashif** [comment]
nice, does this need to be in the tree for it to work or should we expect it to label stuff just based on the PR?
Should we disable the what_chained.py job at the same time?

**Review by ioannisg — COMMENTED** [review]
How about adding the architecture label also for /include/arch/* ?

**Comment by galak** [comment]
> How about adding the architecture label also for /include/arch/* ?

did I miss this, or is this new?

**Comment by aescolar** [comment]
@galak @nashif So have you guys decided the labeling is then based on this instead of the maintainers file?

**Comment by nashif** [comment]
> @galak @nashif So have you guys decided the labeling is then based on this instead of the maintainers file?

we are moving existing functionality from shippable to GH actions, nothing more. When we get to the maintainers file, we will look into a solution using GH Actions. the plan is to move all CI checks to GH actions.

**Comment by aescolar** [comment]
> we are moving existing functionality from shippable to GH actions

So the idea is that you will use the pre-canned options from the marketplace? or also shoot some of our own scripts?

**Comment by galak** [comment]
Closing this for now as GH doesn't provide priv to forks, will track this issue to see if things change:

https://github.com/actions/labeler/issues/12

**Comment by nashif** [comment]
> So the idea is that you will use the pre-canned options from the marketplace? or also shoot some of our own scripts?

The idea is to start using GH actions for all of this and wherever there is a solution already, we should look into using it instead of implementing and maintaining our own. GH Actions is not about per-packaged solutions only, we can also run our own scripts, but we need to start moving into this direction.

**Pull request closed without merging**
