### PR TITLE
boards: sam_v71: enable GPIO driver

### PR DESCRIPTION
**Pull request by bbilas**
Enable missing GPIO driver which is needed to handle CS GPIOS in SPI driver.

MR has been tested by building spi_loopback sample only.

Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>

### CODE REVIEW

**Comment by bbilas** [comment]
It fixes the build failures related to spi_loopback sample and SPI driver itself:

https://buildkite.com/zephyr/zephyr/builds/45893#331870b3-1688-4aa5-9e33-4b40f3cf323b

**Comment by nandojve** [comment]
Is GPIO in the list of minimal configuration list?

**Comment by bbilas** [comment]
> Is GPIO in the list of minimal configuration list?

What list are you talking about?

**Comment by nandojve** [comment]
> > Is GPIO in the list of minimal configuration list?
> 
> What list are you talking about?

There is a minimal config list that each board should enable to run. As far I know, everything outside that, should be configured by App/Samples.

**Comment by bbilas** [comment]
> > > Is GPIO in the list of minimal configuration list?
> > 
> > 
> > What list are you talking about?
> 
> There is a minimal config list that each board should enable to run. As far I know, everything outside that, should be configured by App/Samples.

There is a supported features table https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/sam_v71_xult/doc/index.rst#supported-features, where GPIO is specified so I assume that GPIO driver should be enabled.

**Comment by nandojve** [comment]
> > > > Is GPIO in the list of minimal configuration list?
> > > 
> > > 
> > > What list are you talking about?
> > 
> > 
> > There is a minimal config list that each board should enable to run. As far I know, everything outside that, should be configured by App/Samples.
> 
> There is a supported features table https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/sam_v71_xult/doc/index.rst#supported-features, where GPIO is specified so I assume that GPIO driver should be enabled.

Is GPIO necessary to run Hello World?
If the answer is no board should not enable something that 

> > > > Is GPIO in the list of minimal configuration list?
> > > 
> > > 
> > > What list are you talking about?
> > 
> > 
> > There is a minimal config list that each board should enable to run. As far I know, everything outside that, should be configured by App/Samples.
> 
> There is a supported features table https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/sam_v71_xult/doc/index.rst#supported-features, where GPIO is specified so I assume that GPIO driver should be enabled.

No, any driver should be enabled when it is needed instead all the time. Otherwise we can spend a lot of flash for nothing. My suggestion is look how to enable by demand at Kconfig inspecting devicetree nodes. This could require some rework at SoC Kconfig too.

**Comment by danieldegrasse** [comment]
@bbilas Since this fix is for the SPI loopback examples only, you could set `CONFIG_GPIO=y` within a board specific overlay in the `boards` directory of the SPI loopback example for each of these boards, and avoid modifying the default configuration

**Comment by bbilas** [comment]
@nandojve @danieldegrasse I agree with you guys. I will send new patchsets.

**Comment by bbilas** [comment]
Superseded by https://github.com/zephyrproject-rtos/zephyr/pull/40241.

**Pull request closed without merging**
