### PR TITLE
sensor: bq274xx cleanup

### PR DESCRIPTION
**Pull request by olsky**
found a not-merged PR https://github.com/zephyrproject-rtos/zephyr/pull/42145 so decided to work on it. I will create separate PRs for cleanup, new features (as suggested in that PR).

Here is the first part: code cleanup.

restarting...

### CODE REVIEW

**Review by nixward — APPROVED** [review]
Nice work @olsky, just note in the Zephyr project it's preferred to finish a PR in the one it started in. It keeps the review context for other reviewers and less PRs to search through when people are looking for info.  For reviewers this PR started here: https://github.com/zephyrproject-rtos/zephyr/pull/56216

To get the compliance to pass you'll need to fix up the format of your git commit comments, see here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

As long as that's fixed up it looks good to me.

**Comment by nixward** [comment]
> > 
> 
> Hi @nixward 
> in an attempt to "revert/remove commits" on the branch, github closed PR (no idea why is that so). Thus I started a new PR, and collected changes in separate commits.
> 
> oops, signoff missing :-) need to fix that!
> 

No prob 👍

**Comment by nixward** [comment]
Hi @olsky if you're having trouble fixing the commit messages I asked Chat GPT3 for a description of how to do it :D, it needed a bit of editing but here it is:

1. Open your terminal or command prompt and navigate to the Zephyr Git repository where you want to modify the commit messages.
2. Type git rebase -i main. This will open up the interactive rebase tool in your default text editor (usually Vim).
3. In the interactive rebase tool, you should see a list of all the commits on the branch, starting from the earliest. In Vim press i to enter insert mode and find the commit(s) you want to modify and replace the word pick with reword at the beginning of the corresponding line. This tells Git that you want to edit the commit message.
4. Save and exit the file to close the editor (in the Vim editor, press Esc to exit insert mode and type :wq and press Enter). This will take you to the first commit you marked for editing.
5. The interactive rebase tool will prompt you to edit the commit message. The default text editor for Git is usually Vim, so you will see the Vim editor window.
6. To edit the message, press i to enter insert mode. This will allow you to modify the text.
7. Make the necessary changes to the commit message, then press Esc to exit insert mode.
8. To save the changes and exit the Vim editor, type :wq and press Enter. The colon : tells Vim that you are entering a command, and wq stands for "write and quit".
9. Repeat steps 6-8 for each commit message you selected to modify.
10. After the rebase is complete, you will need to force push the changes to the remote repository. Type git push --force to do this.

**Comment by olsky** [comment]
> 

Hi :-) right, me to asked the bigbro a question... here is what comes out, and I kind of like "the way" it thinks: just automate it :-D


_Hi BigBro, I was wondering, wouldnt it make sense to connect you to github repository, in a way that you could do some routine and time consuming job, especially with code cleanup, code formatting? Kindof boring job, I know, but someone has to do it, right?_


Hello! As an AI language model, I do not have the ability to connect to a GitHub repository directly. However, there are many automation tools available that can help with routine and time-consuming tasks such as code cleanup and formatting.

For example, you could use a pre-commit hook to automatically run a code formatter such as black or prettier on your code before committing changes to your repository. This can help ensure consistency and save time in the long run.

Alternatively, there are also code review tools such as CodeClimate and Codacy that can automatically analyze your code for issues such as code style violations and suggest fixes. These tools can integrate with your GitHub repository and provide feedback on every pull request or commit.

Overall, there are many automation tools available to help with routine tasks in software development, and it's always a good idea to explore these options to save time and improve code quality.

**Comment by nixward** [comment]
Fair point @olsky, apologies, take your time 👍

**Comment by nixward** [comment]
Just to be clear, I wasn't attempting to be smart in any of my comments above, I was just trying to help.  Apologies if it read that way.

**Comment by olsky** [comment]
> Just to be clear, I wasn't attempting to make a joke in any of my comments above. Apologies if it read that way.

no, totally fine! I was ref your prev post... time :)

**Comment by nixward** [comment]
Apologies @olsky, my comment above https://github.com/zephyrproject-rtos/zephyr/pull/56256#issuecomment-1491137843 was not intended to offend. It was something I'd had trouble with in the past so it was an honest attempt to help. If it was not helpful I'd imagined it would just be disregarded. Apologies if offense was caused, no malice intended. I'll be more careful with my comments in future.

**Comment by nixward** [comment]
> > Just to be clear, I wasn't attempting to make a joke in any of my comments above. Apologies if it read that way.
> 
> no, totally fine! I was ref your prev post... time :)

Ok cool, I believe I've misinterpreted the tone of your messages 😳 I'll think I'll stop commenting for awhile... 😄

**Comment by olsky** [comment]
No need to, really all fine, the fun fact is one freelance was working on this driver and supposed to fix all things but then moved on, so we kept a local copy of it, and in the meantime improved it. But also have little time to push all. I thought to make it now, and … time is our most critical thing… i will resume as soon as i have more time in a row.Best regards On 4. Apr 2023, at 13:36, Nick Ward ***@***.***> wrote:﻿


Just to be clear, I wasn't attempting to make a joke in any of my comments above. Apologies if it read that way.

no, totally fine! I was ref your prev post... time :)

Ok cool, I believe I've misinterpreted the tone of your messages 😳 I'll think I'll stop commenting for awhile... 😄

**Comment by nixward** [comment]
Hi @olsky, any luck with spare cycles to get this PR merged? I'm not sure what the process is but I'm happy to take over your PR in an attempt to get your commits merged if you're ok with that?

**Comment by olsky** [comment]
Hi Nick,Thank you for your message, yes sure: please get the pr if you have some spare time. Next few weeks I would be busy 😬Best regards OlehOn 3. Jun 2023, at 02:45, Nick Ward ***@***.***> wrote:﻿
Hi @olsky, any luck with spare cycles to get this PR merged? I'm not sure what the process is but I'm happy to take over your PR in an attempt to get your commits merged if you're ok with that?

**Comment by nixward** [comment]
Commits (with comments fixed) and moved to https://github.com/zephyrproject-rtos/zephyr/pull/58906

**Pull request closed without merging**
