### PR TITLE
multiple main CI fixes

### LINKED ISSUE #64846: main CI broken: tests/drivers/build_all/modem/drivers.modem.modem_cellular.build fails to build
**Describe the bug**
tests/drivers/build_all/modem/drivers.modem.modem_cellular.build fails to build on native_posix & qemu_x86 due to multiple issues.

At least the following issues cause the compiler to fail:
* a double pointer is provided where the compiler expected a pointer,
* `telit_me910g1_periodic_chat_script` being not defined.

**To Reproduce**
1. twister -p native_posix -s tests/drivers/build_all/modem/drivers.modem.modem_cellular.build
2. see error

or 

1. mkdir build; cd build
2. cmake -GNinja -DBOARD=native_posix ../tests/drivers/build_all/modem/ -DCONF_FILE=modem_cellular.conf
3. ninja

**Expected behavior**
No build issues

**Impact**
main development blocked when this test is triggered in CI

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/6769657675/job/18396479285?pr=64839#step:12:952
https://github.com/zephyrproject-rtos/zephyr/actions/runs/6769657666/job/18396537263?pr=64839#step:13:1079

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 22.04 CI
 - Toolchain (e.g Zephyr SDK, ...): Host gcc (11 or 12)
 - Commit SHA or Version used: main as of now f027b55d026e0626905c7d4def36468f67dd923b

**Additional context**
Introduced by c76d5b882c1416ce48b918a4d1e034b913baa873

### LINKED ISSUE #64850: main CI broken: samples/net/cloud/aws_iot_mqtt/sample.net.cloud.aws_iot_mqtt incorrect filter syntax
**Describe the bug**
The filter in samples/net/cloud/aws_iot_mqtt/sample.net.cloud.aws_iot_mqtt has incorrect syntax.

**To Reproduce**
1. twister -s samples/net/cloud/aws_iot_mqtt/sample.net.cloud.aws_iot_mqtt -p qemu_x86 
2. See twister python exception

**Expected behavior**
No python exception

**Impact**
main CI development blocked when the test is triggered

**Logs and console output**
```
  File "zephyr/scripts/pylib/twister/expr_parser.py", line 313, in parse
    ast = parser.parse(expr_text)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/lib/python3/dist-packages/ply/lex.py", line 393, in token
    newtok = self.lexerrorf(tok)
  File "zephyr/scripts/pylib/twister/expr_parser.py", line 98, in t_error
    raise SyntaxError("Unexpected token '%s'" % t.value)
SyntaxError: Unexpected token '&& not CONFIG_NATIVE_LIBC'
```
https://github.com/zephyrproject-rtos/zephyr/actions/runs/6769657666/job/18396537263?pr=64839#step:13:1078

**Environment (please complete the following information):**
 - OS: Linux, CI, Ubuntu 22.04
 - Toolchain (e.g Zephyr SDK, ...): python
 - Commit SHA or Version used: main as of now https://github.com/zephyrproject-rtos/zephyr/commit/f027b55d026e0626905c7d4def36468f67dd923b

**Additional context**
Introduced by 1e5c46df3df8e28c12e965ca4524af7cbdb53805, and only partially fixed by 4c21090dcb6690e0120d619df736fd6c1c6c7ac1

### PR DESCRIPTION
**Pull request by aescolar**
[Revert "drivers: modem: modem_cellular: Patch init scripts"](https://github.com/zephyrproject-rtos/zephyr/pull/64847/commits/b090eb0d41125439772494e5ad513bb3004dbc24)

This reverts commit https://github.com/aescolar/zephyr/commit/c76d5b882c1416ce48b918a4d1e034b913baa873.

This commit had caused the main branch CI to break as described in this issue:
https://github.com/zephyrproject-rtos/zephyr/issues/64846
This seems to be due to at least 2 separate bugs.

Let's revert it to unblock development.

----

[samples/net/cloud/aws_iot_mqtt: Fix sample yaml](https://github.com/zephyrproject-rtos/zephyr/pull/64847/commits/835b9ccf8d6d409d2783562a88d25cc47fead593)

The sample yaml filter syntax was incorrect.
Fix it.

-----

Fixes: #64846
Fixes: #64850

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
For the revert commit, it would be useful to have information in the commit message why the revert is being done.

**Comment by aescolar** [comment]
@jukkar the commit message has been updated to include the motivation. There is no changes otherwise.
CI in this PR was green before the new push.

**Review by jukkar — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by rerickson1 — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
forward fix: https://github.com/zephyrproject-rtos/zephyr/pull/64858

**Review by rerickson1 — CHANGES_REQUESTED** [review]
Blocking this in favor of the fix above.

**Pull request closed without merging**
