### PR TITLE
Dai misc additions

### PR DESCRIPTION
**Pull request by juimonen**
Add dai indexes and types to ssp and alh configs. These can be used in app for runtime device match when dts Labels are removed. see https://github.com/thesofproject/sof/pull/6132. Also fix dmic enum.

### CODE REVIEW

**Review by lgirdwood — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by abonislawski — COMMENTED** [review]
so now we have two copies of the same index variable?

	static struct dai_config dai_intel_alh_config_##n = {			\
		.type = DAI_INTEL_ALH,						\
		.dai_index = (n / DAI_NUM_ALH_BI_DIR_LINKS_GROUP) << 8 |	\
			(n % DAI_NUM_ALH_BI_DIR_LINKS_GROUP),			\
	};									\
	static struct dai_intel_alh dai_intel_alh_data_##n = {			\
		.index = (n / DAI_NUM_ALH_BI_DIR_LINKS_GROUP) << 8 |		\
			(n % DAI_NUM_ALH_BI_DIR_LINKS_GROUP),

**Comment by juimonen** [comment]
> so now we have two copies of the same index variable?
> 
> ```
> static struct dai_config dai_intel_alh_config_##n = {			\
> 	.type = DAI_INTEL_ALH,						\
> 	.dai_index = (n / DAI_NUM_ALH_BI_DIR_LINKS_GROUP) << 8 |	\
> 		(n % DAI_NUM_ALH_BI_DIR_LINKS_GROUP),			\
> };									\
> static struct dai_intel_alh dai_intel_alh_data_##n = {			\
> 	.index = (n / DAI_NUM_ALH_BI_DIR_LINKS_GROUP) << 8 |		\
> 		(n % DAI_NUM_ALH_BI_DIR_LINKS_GROUP),	
> ```

yeah it is not so nice, I committed the ssp, dmic came from other guy, and alh I think even from third person... and everybody seemed to want to do the nested configs in different way. 

This is a quick fix to compensate for the "Label" removal from zephyr dts. I think the dai_index should be put actually to dai_properties as dai_config is really more like runtime thing. You set it with set_config and you can ask the config with get_config. For example now when initializing the dai on sof side, not all config members are even set. However this requires dai API change, not a big one, but I would like to do that later.

And this is just for the symmetricity with other dais, dai_index member is there anyway, so no memory footprint is added. And if you don't want to have it here, it can set from the index in get_config to dai_index.

I can make it so, that in alh and ssp I take it from some other existing data and don't duplicate it?

**Comment by fabiobaltieri** [comment]
@juimonen hey just to clarify, can this be merged or you plan to work more on the PR?

**Comment by lgirdwood** [comment]
@juimonen pls confirm this is ready to merge.

**Comment by juimonen** [comment]
@fabiobaltieri @lgirdwood yes can be merged. I need to address the last comment in separate PR for possible dai api change. These commits should not harm/change any current logic.

**Pull request merged**
