### PR TITLE
kernel: posix: move sleep and usleep functions into c file.

### PR DESCRIPTION
**Pull request by youvedeep**
Currently sleep and usleep functions are into unistd.h file.
unistd includes toold chain secific unistd.h file and this file
too has declaration for these functions. This is in conflict when
posix specific unistd.h is included.

Signed-off-by: Youvedeep Singh <youvedeep.singh@intel.com>

### CODE REVIEW

**Comment by youvedeep** [comment]
Do not merge this as of now. We need some exper help to find out when to include tool chain specific unistd.h file.

**Review by eyuval — APPROVED** [review]

**Comment by eyuval** [comment]
I have found an easy way to reproduce the problem:
1. I am using the hello world sample and adding the following lines to the prj.conf
CONFIG_NEWLIB_LIBC=y
CONFIG_PTHREAD_IPC=y
2. in main.c I am adding the lines 
#include <posix/pthread.h>
#include <posix/unistd.h>

3. for compilation I am using the qemu_x86 board

Am I perhaps forbidden to use NEWLIB_LIBC with the zephyr posix stuff?

**Review by lpereira — APPROVED** [review]

**Comment by nashif** [comment]
> in main.c I am adding the lines
> #include <posix/pthread.h>
> #include <posix/unistd.h>

you should not include like this, instead:

#include <pthread.h>
#include <unistd.h>

**Review by nashif — APPROVED** [review]

**Comment by ramakrishnapallala** [comment]
@eyuval I have removed the dependency of NEWLIBC macros in posix headers. Now i am able to build and test posix tests with both configs enabled.
https://github.com/zephyrproject-rtos/zephyr/pull/6918

**Pull request merged**
