### PR TITLE
fs: explicitly initialize fs_file_t and fs_dir_t

### PR DESCRIPTION
**Pull request by Deedone**
C++ compilers forbid usage of compound literals with -Wpedantic enabled.
They also forbid the usage of designated initializers for standards lower than c++20.
So switch to explicit initialization, that would not make compilers angry at us.

### CODE REVIEW

**Review by de-nordic — CHANGES_REQUESTED** [review]
", {0} initializes only the first member of the structure," not true.
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4849.pdf
9.41,  (5.1) and (5.2).
Anyway, if you really want to do that, then put `memset` aside and just initialize members by hand.

**Comment by Deedone** [comment]
@de-nordic 
Indeed {0} initialized all of the members, I was confused by compiler warnings, that told me it is not:
`warning: missing initializer for member ‘fs_file_t::mp’ [-Wmissing-field-initializers]`

But I think memset is still the best way to do this, because
with {0} we get:
`warning: ISO C++ forbids compound-literals [-Wpedantic]`
and
`warning: missing initializer for member ‘fs_file_t::mp’ [-Wmissing-field-initializers]`
`warning: missing initializer for member ‘fs_file_t::flags’ [-Wmissing-field-initializers]`

with {0,0,0} we still get:
`warning: ISO C++ forbids compound-literals [-Wpedantic]`

with { .filep=0, .mp=0, .flags=0 } we get:
`warning: C++ designated initializers only available with ‘-std=c++20’ or ‘-std=gnu++20’ [-Wpedantic]`

some people on the internet suggest using oop style constructors, but that would not work in C

So if I'm not missing something, the only way to please all compilers is by using memset here.

**Comment by de-nordic** [comment]
> forbids compound-literals

So it basically is angry about cast on literal initializer assigned on value.

I have completely forgotten about the named member initialization (the .name thing) when writing this

> Anyway, if you really want to do that, then put memset aside and just initialize members by hand.

and was rather thinking about something less sophisticated:
```
zfp->file_p = NULL;
zfp->mp = NULL;
...
```

**Comment by Deedone** [comment]
@de-nordic 
Oops, I totally forgot about that approach, but it still seems to me that it is inferior to calling memset.

The reason is if we add or delete some members to `struct fs_file_t` in the future, it will require modifying the init code every time. And in the case of member addition, if the person adding the new member forgets to modify the init code, I am not sure that the compiler would notice it and complain about junk in the new field, leading to very confusing errors.
While memset will auto-adjust for any changes in the structures.

Can you please elaborate on why you don't like the memset approach so much? I feel like I am missing something because it looks like the most optimal for me.

**Comment by de-nordic** [comment]
> 
> The reason is if we add or delete some members to `struct fs_file_t` in the future, it will require modifying the init code every time. And in the case of member addition, if the person adding the new member forgets to modify the init code, I am not sure that the compiler would notice it and complain about junk in the new field, leading to very confusing errors. While memset will auto-adjust for any changes in the structures.

Yeah, I guess people should look what class constructors do when adding members. Tough life of a programmer.

Good if there are errors, because in such case it means that a person that has been modifying the structure has not looked in every place where they should. The init may do something more than just memset an object.

Of course there are no errors on the lack of init for something new, but If that gets through then maintainer may have a bad day. Static analysis may catch it later, so there is always hope.

> 
> Can you please elaborate on why you don't like the memset approach so much? I feel like I am missing something because it looks like the most optimal for me.

Well, to call memset you have to: store registers that are free to be modified by callee and these for params, then set params to registers, then put return address on stack, than call the function, then the function has some ifs to figure out how to approach buffer (size/alignment optimizations, etc), then it does what = does in loop,  which takes loop handling, than returns, restores context, etc.... all the stuff for unwinding the member assignment by doing = three times.
All that for convenience of not looking into the init function, which makes it bad argument in the first place.

**Review by de-nordic — APPROVED** [review]

**Comment by de-nordic** [comment]
Thanks. Looks OK.

**Review by Laczen — APPROVED** [review]

**Pull request merged**
