### PR TITLE
Remove all code deprecated a couple of releases ago

### PR DESCRIPTION
**Pull request by gmarull**
Remove all code deprecated before the 3.1 release. I hope I haven't made any mistake.

### CODE REVIEW

**Review by Laczen — DISMISSED** [review]

**Comment by gmarull** [comment]
added one last commit to fix missing include (reported by CI, likely because of zephyr/devicetree/zephyr.h removal, which included zephyr/toolchain.h).

**Review by de-nordic — DISMISSED** [review]
VFS subsys OK.

**Review by Laczen — DISMISSED** [review]
nvs changes OK

**Review by carlescufi — DISMISSED** [review]

**Review by galak — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Review by de-nordic — DISMISSED** [review]
VFS subsys OK.

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by Laczen — DISMISSED** [review]

**Comment by gmarull** [comment]
last push: more missing includes

**Review by galak — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
@gmarull are you expecting individual maintainers to make sure these removals are all reflected in the release notes?

**Comment by gmarull** [comment]
> @gmarull are you expecting individual maintainers to make sure these removals are all reflected in the release notes?

I guess each maintainer will update release notes once we approach the release dates.

**Pull request merged**
