### PR TITLE
samples: modules: lvgl: add keypad and encoder demo

### PR DESCRIPTION
**Pull request by everedero**
Adds the LVGL keypad and encoder demo to sample build.

### CODE REVIEW

**Comment by kartben** [comment]
Nice! Didn't know about this sample :)
@faxe1008 it almost feels like we should really get the "basic" sample back to a minimal one like we used to have if `demos` allows folks to quickly try out more complex scenarios, inc. input, on their boards?  But then there's also things like #67508 that can be quite useful ...

**Comment by faxe1008** [comment]
@everedero thanks for your submission, indeed this sample was missing :^). Overall looks fine to me, but I was wondering if an overlay might make sense here because this sample does not work "out of the box" with the `native_sim` as the sample readme would suggest. Using `zephyr,native-linux-evdev` could be an elegant solution for this.

@kartben agree on this. After this PR is merged pretty much all indev are covered in other samples (except the button indev one) and could be removed, making the sample more basic once again 👍

**Comment by everedero** [comment]
@faxe1008 That would be nice indeed, I will try to add this.

**Comment by everedero** [comment]
Will be done in PR #68168

**Pull request closed without merging**
