### PR TITLE
net: buf: Convert net_buf to use k_timeout_t where appropriate

### PR DESCRIPTION
**Pull request by jhedberg**
This patch updates the net_buf API to use k_timeout_t in essentially
all places where "s32_t timeout" was previously used. For the most
part the conversion is trivial, except for the places where
intermediate decrements of remaining timeout is needed. For this the
z_timeout_end_calc() API is used.

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
This has been tested to the extent that `tests/net/buf` both builds and its tests pass when `LEGACY_TIMEOUT_API` is disabled.

**Comment by jhedberg** [comment]
If this PR is fine, then I'd propose that we remove the `select LEGACY_TIMEOUT_API` from `NET_BUF` in `subsys/net/Kconfig` and add selects to the specific subsystems that use net_buf. That way each subsystem can be converted independently to k_timeout_t.

**Comment by jukkar** [comment]
> If this initial patch is fine, then I'd propose that I add a second one that removes the `select LEGACY_TIMEOUT_API` from `NET_BUF` in `subsys/net/Kconfig` and adds selects to the specific subsystems that use net_buf. That way each subsystem can be converted independently to k_timeout_t.

For networking subsystem itself, the select can be moved to `config NETWORKING` option before the conversion is done there.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by joerchan — COMMENTED** [review]
Looks good.
I think the explanation of the timeout parameter is a bit strange, using duration to explain timeout
Maybe switch "given duration before timing out" with "specified timeout"?

**Review by tbursztyka — APPROVED** [review]

**Comment by jhedberg** [comment]
> I think the explanation of the timeout parameter is a bit strange, using duration to explain timeout Maybe switch "given duration before timing out" with "specified timeout"?

It's not strange to me (which is why I used it) since a timeout is the maximum duration of the procedure before giving up. That said, I don't mind changing it - I'll update it based on your suggestion.

**Review by joerchan — APPROVED** [review]

**Pull request merged**
