### PR TITLE
doc: fix mgmt sample path

### PR DESCRIPTION
**Pull request by ifillonneau**
fix mgmt sample path in the documentation 

Signed-off-by: Ismael Fillonneau <ismael.fillonneau@stimio.fr>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@ifillonneau the commit message body cannot be empty. Please add a brief description of the channge.

**Comment by ifillonneau** [comment]
maybe I am wrong, but I directly modified the commit message in github. Is it the correct solution?

**Comment by carlescufi** [comment]
@ifillonneau no, that is the PR description. you need to do in your branch:

```
git commit --amend
<edit commit>
git push -f
```

**Review by dbkinder — APPROVED** [review]
thanks for fixing the docs.  we'll see if the commit message body works on the recheck

**Comment by carlescufi** [comment]
@ifillonneau you seem to have an extra tab somewhere in your commit message now:

https://github.com/zephyrproject-rtos/zephyr/pull/7111/commits/7b32a0b9a494c4d90f40c4b6d1fca421cbbf90a3

```
doc: fix mgmt sample path

     mgmt sample path in the documentation was incorrect

Signed-off-by: Ismael Fillonneau <ismael.fillonneau@stimio.fr>
```

The body line should be aligned to the left

**Comment by ifillonneau** [comment]
@carlescufi . ok, corrected.
Thanks for all advices.

**Comment by carlescufi** [comment]
@ifillonneau looks good now, thank you.

**Pull request merged**
