### PR TITLE
drivers: sensor: tsic_xx6: fix implicit sign extension

### LINKED ISSUE #74776: [Coverity CID: 368811] Unintended sign extension in drivers/sensor/tsic_xx6/tsic_xx6.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/dcf42917c550714d2457947538b9e29d083e872e/drivers/sensor/tsic_xx6/tsic_xx6.c#L164

Category: Integer handling issues
Function: `tsic_xx6_get_value`
Component: Drivers
CID: [368811](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=368811)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/dcf42917c550714d2457947538b9e29d083e872e/drivers/sensor/tsic_xx6/tsic_xx6.c#L164

```
158     static void tsic_xx6_get_value(const struct tsic_xx6_config *config, struct tsic_xx6_data *data,
159                             uint16_t data_bits)
160     {
161      int64_t tmp;
162    
163      /* Apply the datasheet formula scaled to micro celcius */
>>>     CID 368811:  Integer handling issues  (SIGN_EXTENSION)
>>>     Suspicious implicit sign extension: "data_bits" with type "uint16_t" (16 bits, unsigned) is promoted in "data_bits * (config->higher_temperature_limit - config->lower_temperature_limit)" to type "int" (32 bits, signed), then sign-extended to type "long long" (64 bits, signed).  If "data_bits * (config->higher_temperature_limit - config->lower_temperature_limit)" is greater than 0x7FFFFFFF, the upper bits of the result will all be 1.
164      tmp = data_bits * (config->higher_temperature_limit - config->lower_temperature_limit);
165      tmp = tmp * 1000000 / (BIT(config->data_bits) - 1);
166      tmp += (int64_t)config->lower_temperature_limit * 1000000;
167    
168      data->val.val1 = tmp / 1000000;
169      data->val.val2 = tmp % 1000000;
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_SIGN_EXTENSION). ([CWE-194](http://cwe.mitre.org/data/definitions/194.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=368811

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by jilaypandya**
This commit fixes issue #74776

### CODE REVIEW

**Review by jeppenodgaard — APPROVED** [review]
Thank you for fixing this.

**Comment by jeppenodgaard** [comment]
I think the commit message needs to be updated here as well:
https://github.com/zephyrproject-rtos/zephyr/pull/81178#pullrequestreview-2427301111

**Comment by jilaypandya** [comment]
> I think the commit message needs to be updated here as well:
> https://github.com/zephyrproject-rtos/zephyr/pull/81178#pullrequestreview-2427301111

Have adjusted the commit message

**Review by nashif — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
Ping @MaureenHelm , a simple one

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
