### PR TITLE
soc: stm32f103x8: Added support for can

### PR DESCRIPTION
**Pull request by optical-o**
STM32F103X8 Series have CAN.
https://www.st.com/en/microcontrollers-microprocessors/stm32f103c8.html

### CODE REVIEW

**Comment by GunZi200** [comment]
May be unrelated to this PR but I would think it is better to create a common `stm32f103.dtsi` file with nodes common to all f103 variants. For example CAN and USB is shared between them all. 🤔 There's potential for some cleanup here.

**Review by erwango — COMMENTED** [review]
Thanks for this addition.
Have you been able to validate CAN support on STM32F1 ?

**Comment by erwango** [comment]
> May be unrelated to this PR but I would think it is better to create a common stm32f103.dtsi file with nodes common to all f103 variants. For example CAN and USB is shared between them all. thinking There's potential for some cleanup here.

All STM32F103 variants include stm32f103X8.dtsi, so this is done as expected.
What I'd propose, if this is confirm that CAN1 performs well on STM32F1, is to add CAN node also on STM32F105, so all STM32F1 supported variants enjoy CAN feature.

**Comment by erwango** [comment]
@optical-o You'll need to update the commit message according to guidelines:
https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines

**Comment by optical-o** [comment]
I'm using STM32F103C8 and indeed the CAN is functional.

**Comment by optical-o** [comment]
I have changed the commit message hopefully according to the guidelines.

**Review by erwango — APPROVED** [review]

**Comment by GunZi200** [comment]
@optical-o 

CI is complaining the commit message line is too long

> 3: UC4 Line exceeds max length (105>72): "The stm32f103x8 series has CAN capability, this commits adds the CAN peripheral into the soc device tree."

Splitting this into two lines should work.

**Comment by optical-o** [comment]
I have modified the commit message to fit the character limit hopefully.

**Comment by GunZi200** [comment]
Yeah it worked but the build fails because of an issue on Zephyr’s master branch (it was fixed here: https://github.com/zephyrproject-rtos/zephyr/commit/a7d8ff40aa531186124ff0082999245c003d74af). 

Could you rebase your branch with the latest changes?

This should do the trick:
```
git remote add upstream https://github.com/zephyrproject-rtos/zephyr.git
git fetch upstream
git rebase upstream/master
git push -f
```

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by FRASTM — APPROVED** [review]

**Pull request merged**
