### PR TITLE
samples: nrf52: tickless: Update stale references to PM symbols

### PR DESCRIPTION
**Pull request by ulfalizer**
PM_CONTROL_OS was removed in commit c45961daae ("power: Rework OS <->
Application interface"), which I think says that it'd always be on in
practice now.

Some other symbols were renamed by that commit as well as commit
155e11ca2d ("power: rename residency policy Kconfig options").

Remove the PM_CONTROL_OS assignment and fix up the other symbol names.

Adding detection of unused symbols in samples and tests to CI.

### CODE REVIEW

**Comment by ulfalizer** [comment]
Marking as bug since it should prevent it from building due to the Kconfiglib warning.

**Review by pabigot — CHANGES_REQUESTED** [review]
Learning that we don't test sample builds for warnings in CI is not making me happy this morning.

While this looks reasonable I'm still getting the build warning with it.  It also occurs in the non-tickless configuration (which makes sense, since that is also tickless).  So in terms of making samples build without warnings we're not there yet.

```
warning: SYS_PM_MIN_RESIDENCY_SLEEP_1 (defined at subsys/power/policy/Kconfig:27) was assigned the
value '5000' but got the value ''. You can check symbol information (including dependencies) in the
'menuconfig' interface (see the Application Development Primer section of the manual), or in the
Kconfig reference at
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_1.html
(which is updated regularly from the master branch). See the 'Setting configuration values' section
of the Board Porting Guide as well.
```

**Comment by ulfalizer** [comment]
@pabigot 
Most warnings are turned into errors, so they get checked that way. This configuration must not be getting tested in CI.

The didn't-get-the-assigned-value warning is still just a warning though (as well as select-with-unsatisfied deps. warning), because it seemed like it might be a pain to fix them all when I originally cleaned out most of the warnings. I could check if it's still a pain later.

I'll look into what's causing that one.

**Comment by ulfalizer** [comment]
It's not a regression at least. You get the same warnings for `prj.conf` (which this PR doesn't touch).

The issue is that `SYS_PM_MIN_RESIDENCY_SLEEP_1` depends on `HAS_SYS_POWER_STATE_SLEEP_1`, which is `n`. It's a board-specific thing.

@mnkp @pizi-nordic 
Is the configuration re. `HAS_SYS_POWER_STATE_SLEEP_1` correct here? See this:

```
$ git grep HAS_SYS_POWER_SLEEP_STATE_1
arch/Kconfig:config HAS_SYS_POWER_STATE_SLEEP_1
include/power/power.h:# ifdef CONFIG_HAS_SYS_POWER_STATE_SLEEP_1
include/power/power.h:# ifdef CONFIG_HAS_SYS_POWER_STATE_SLEEP_1
kernel/Kconfig.power_mgmt:      depends on HAS_SYS_POWER_STATE_SLEEP_1 || \
soc/arm/silabs_exx32/common/soc_power.c:#ifdef CONFIG_HAS_SYS_POWER_STATE_SLEEP_1
soc/arm/silabs_exx32/common/soc_power.c:#endif /* CONFIG_HAS_SYS_POWER_STATE_SLEEP_1 */
soc/arm/silabs_exx32/efm32pg12b/Kconfig.series: select HAS_SYS_POWER_STATE_SLEEP_1
soc/arm/silabs_exx32/efr32fg1p/Kconfig.series:  select HAS_SYS_POWER_STATE_SLEEP_1
soc/arm/silabs_exx32/efr32mg12p/Kconfig.series: select HAS_SYS_POWER_STATE_SLEEP_1
subsys/power/policy/Kconfig:    depends on HAS_SYS_POWER_STATE_SLEEP_1
subsys/power/policy/policy_residency.c:#ifdef CONFIG_HAS_SYS_POWER_STATE_SLEEP_1
tests/kernel/profiling/profiling_api/Kconfig:   select HAS_SYS_POWER_STATE_SLEEP_1
```

The only things that seem to enable it are that exx32 SoCs.

**Comment by mnkp** [comment]
The `HAS_SYS_POWER_STATE_` pattern is central to the design of the power management subsystem as it needs to know exactly which power state SoC supports. It's better to grep for `HAS_SYS_POWER_STATE_` to judge its current usage. It's true however that few SoCs support power management. It looks like it's only SiLabs and Nordic at the moment. In the past also Intel had some power management code.

As for the NRF52, the `samples/boards/nrf52/power_mgr/` seems to be outdated / doesn't much the design of the NRF52 power subsystem. Looking at `soc/arm/nordic_nrf/nrf52/power.c` the SoC seems to support `SYS_POWER_STATE_DEEP_SLEEP_1` only. It doesn't define any other sleep states at all.

That's in contrary to the content of `samples/boards/nrf52/power_mgr/prj.conf` which defines `SYS_PM_MIN_RESIDENCY_SLEEP_1` which if valid only for Sleep 1. Someone would need to bring the sample code up to date or it should be removed.

**Review by pabigot — CHANGES_REQUESTED** [review]
The documented units for `CONFIG_SYS_PM_MIN*` are milliseconds; the change here appears to be using seconds.

I'm refreshing this example, so the changes here will be superseded.  This PR should only be merged if the result of the rework is not suitable for v2.1.

**Comment by ulfalizer** [comment]
@pabigot 
Is this PR still relevant?

**Comment by pabigot** [comment]
Since the sample is gone, no.

**Pull request closed without merging**
