### PR TITLE
TCP fixes

### LINKED ISSUE #38576: net shell: self-connecting to TCP might lead to a crash
**Describe the bug**
If a TCP socket is listening up, using net-shell's tcp connect command to it may lead to a crash

**To Reproduce**
1. west build -b qemu_x86_64 samples/net/sockets/echo_server
2. west build -t run
3. run this command: net tcp connect 192.0.2.1 4242
4. See error (sometime, it takes a few seconds before happening)

**Expected behavior**
Crash should not happen

**Additional context**
Haven't tried on other target than qemu_x86_64, but it's likely to exist on others.

### PR DESCRIPTION
**Pull request by tbursztyka**
2 important fixes:
- Fix local TCP connections (currently leads to non functioning connection and memory leak)
- Fix TCP disconnection initiated on Zephyr side (currently leads to memory leak)

### CODE REVIEW

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by pfalcon** [comment]
> Fix local TCP connections (currently leads to non functioning connection and memory leak)

This is pretty weird. Local TCP connections didn't work a few years ago, but since then, they were fixed and we even have a regression tests for them. Did you consider to add a testcase showing the current problem and that it's being fixed by these changes?

**Comment by jukkar** [comment]
> we even have a regression tests for them

This could still be a regression if the test sets `CONFIG_NET_LOOPBACK` and verifies things when only that is set. Just pondering here what might be the culprit, did not check the code.

**Comment by tbursztyka** [comment]
@pfalcon The commit message says all about the test case: net tcp connect <local ip> <port>

**Comment by cfriedt** [comment]
The test one test that is failing in CI (for both `qemu_x86` and `mps2_an385`) passes for me locally on this branch. I've heard about timing issues in qemu recently.

`twister -i -p mps2_an385 -T tests/net/tcp2`

**Comment by tbursztyka** [comment]
> This is pretty weird. Local TCP connections didn't work a few years ago, but since then, they were fixed and we even have a regression tests for them.

Actually, our tests are quite fragile against TCP scheduling change (as CI shows). They were really crafted against a certain scheduling behavior, with knowledge about things like "here we sleep for the packet to be processed" etc... Theoretically this should not happen, at least not in the socket based tests (the lower level ones are trickier).

**Comment by tbursztyka** [comment]
Many unrelated tests are failing, I guess due to CI being overloaded.  Like DAD test on ipv6, that does not involve TCP nor net_context etc...

**Comment by tbursztyka** [comment]
> The test one test that is failing in CI (for both `qemu_x86` and `mps2_an385`) passes for me locally on this branch. I've heard about timing issues in qemu recently.
> 
> `twister -i -p mps2_an385 -T tests/net/tcp2`

It's test related for some. At least I have a fix for tcp2. Still having issues on tls though

**Comment by tbursztyka** [comment]
I just added DNM because there is something that is a bit weird: why socket has to ref + 1 the net_context itself in case of TCP  and not net_context direct users? (like net_shell). I noted as well that socket never unref by itself net_context... so is net_context under-referenced by design or by miss? Imo, socket should not have to ref it. Let's see.
I need to verify that my net_context patch did not mess up with this logic.

**Comment by tbursztyka** [comment]
DNM label removed. It does not seem to pose any problem. Let's see what CI has to say then.

**Pull request merged**
