### PR TITLE
Bluetooth: Host: Reassemble extended advertising reports

### LINKED ISSUE #37368: Bluetooth: Host: Support receiving long advertising data
**Is your enhancement proposal related to a problem? Please describe.**
I want to be able to receive 1650 bytes of advertising data as supported by a given Bluetooth Controller. Currently the host forwards all advertising reports directly to the application regardless of the data status. Therefore, if the advertiser is transmitting more bytes than can fit into a report, the application is unable to decode the data as it does not have the context describing if the data is first, intermediate, or last.

The `data_status` is present in both HCI LE Extended Advertising Report event (Core v5.3, Vol 4, Part E, Section 7.7.65.13) and HCI LE Periodic Advertising Report event (Core v5.3, Vol 4, Part E, Section 7.7.65.15) 

**Describe the solution you'd like**
To simplify the application layer design, I would like the host to recombine the received advertising data. The data shall be forwarded once the controller has indicated that there is no more data to follow. 

This requires the host to allocate a scan buffer to store the intermediate received advertising data. If the host supports receiving periodic advertising data, it requires one more.

Once intermediate advertising data has been received, this data shall be copied over to the scan buffer allocated in the host.

The size of the scan buffers should be configurable.

Implemented in https://github.com/zephyrproject-rtos/zephyr/pull/37377

**Describe alternatives you've considered**
Instead of recombining advertising data in the host, this can be done in the application. That requires the data status to be forwarded. This approach is more error prone than letting the host recombine the data. If the application forgets to validate the data status flags, it may try to parse an intermediate fragment as if the data is complete.

Forwarding the data status to the application is implemented in https://github.com/zephyrproject-rtos/zephyr/pull/37336.

### PR DESCRIPTION
**Pull request by hermabe**
The host reassembles fragmented advertising reports from the controller.

Fragmented advertising reports from different advertisers may be
interleaved. If fragmented advertising reports from multiple advertisers
are received, only the first one is kept and reassembled. The rest are
discarded until the first one is complete.

If a complete advertising report is not received from an advertiser
within the timeout, the data is discarded and another advertiser is
allowed to be reassembled.

This PR is based on the work by @rugeGerritsen in #37377.

Fixes: #37368

---

There are a couple issues that need to be discussed:
- A single complete "short" advertising report and the last fragment in a series of fragmented advertising reports are equal. There is no way to disambiguate them by only looking at the advertising report. To be able to reassemble the data correctly, one thus need to know if an advertiser has sent incomplete data before. A list of a possibly unbounded number of advertisers must be kept. An advertiser can only be removed from the list if one has received an advertising report with `Data status` "complete".
- There is no way to know if two advertising reports from anonymous advertisers are from the same device/advertiser set and should be combined or if they are from different devices.

Most of the complexity in this PR arises because the controller may interleave fragmented advertising reports from different advertisers. For controllers that do no interleave advertising reports from different advertisers (like the Softdevice Controller), a much simpler implementation like the one in #37377 can be used. One solution to this is to hide the complex implementation that handles interleaving behind a Kconfig and let controllers that do not need it use the simpler implementation.

A solution in the spec is to add another bit to the `Event_Type`/`Data status` field which tells whether the advertising report is part of a chain of fragmented advertising reports or if it is complete by its own.

Tagging some people from previous discussions: @rugeGerritsen @Thalley @cvinayak

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
@sjanc , FYI

**Comment by sjanc** [comment]
"A solution in the spec is to add another bit to the Event_Type/Data status field which tells whether the advertising report is part of a chain of fragmented advertising reports or if it is complete by its own."

Data status:
0b00 = Complete
0b01 = Incomplete, more data to come
0b10 = Incomplete, data truncated, no more to come

Why is this not enough?

**Comment by hermabe** [comment]
I think you would still have the same problem. If you discard until you receive complete or truncated reports, you may have discarded the start of advertising data from other advertisers.

I am thinking a scenario like this, where fragmented adv reports from multiple advertisers (A and B) are interleaved:
- A1, More to come, added to reassembly buffer
- B1, More to come, discarded
- A2, Complete, added to reassembly buffer and event created
- B2, Complete, Must also be discarded because B1 was discarded. If event is created from this, data would be missing.

**Comment by sjanc** [comment]
You have advertiser address and SID in report to handle matching, haven't you?

**Comment by hermabe** [comment]
> Is this PR ready for review, or is it still a WIP?

The issue with anonymous advertisers is not resolved. That needs to be discussed. As mentioned above I would also like to keep a simpler solution for use with controllers that do no interleave advertising reports from different advertisers. A Kconfig for that is not implemented yet.

But please do comment on any issues in the current implementation you see.

**Review by Thalley — CHANGES_REQUESTED** [review]

**Comment by hermabe** [comment]
> For the sake of reassembly, the pair of {address, sid} is unique (except for anonymous advertising)

Yes, agree. However, we need to know if we previously have discarded any reports from this addr-sid pair. If we have, we must discard all further reports from this pair until a report with data_status=complete is received. If we reassemble reports for an addr-sid pair for which we have previously discarded reports from, the data would be incomplete.

Imagine two different series of adv reports received from the controller. Here A, B and C are different addr-sir pairs.

First example:
- A1, More to come, added to the reassembly buffer
- B1, More to come, have no more reassembly buffers, discarded
- A2, Complete, added to the reassembly buffer and event created. Reassembly buffer cleared.
- B2, Complete, Must be discarded because B1 was discarded. If event is created from this, data would be missing.

Second example:
- A1, More to come, added to the reassembly buffer
- B1, More to come, have no more reassembly buffers, discarded
- A2, Complete, added to the reassembly buffer and event created. Reassembly buffer cleared.
- C1, Complete, Should not be discarded as this is the only data from this advertiser.

In these examples B2 and C1 may have the exact same data. The only difference is the addr-sid pair. In the first example we have discarded data from B, so we cannot use the rest of the data until it sends a report with data_status=complete. In the second example, we have not discarded any data from C, so we should use the data and create an event.

**Comment by Thalley** [comment]
> I don't know how likely it is to lose reports over HCI.

That should never happen

> > I guess we need to have a discarded list as well, right?
> 
> I think the current list does that job, unless i misunderstand something. If an advertiser is in the list and we should not keep its reports, we have previously received a report from that advertiser and discarded it.

Does the current implementation support the scenario you created in https://github.com/zephyrproject-rtos/zephyr/pull/39352#issuecomment-940836275?

**Review by alwa-nordic — CHANGES_REQUESTED** [review]

**Review by cvinayak — CHANGES_REQUESTED** [review]
Could we

**Review by Thalley — CHANGES_REQUESTED** [review]

**Comment by cvinayak** [comment]
> Does anyone know if the Zephyr Controller interleaves adv reports?

Zephyr Controller does not interleave Extended Advertising Reports, but it appears Periodic Advertising Report implementation is heading towards a possibility of being interleaved as HCI LE Periodic Advertising Reports are generated without buffering of complete AUX_SYNC_IND+AUX_CHAIN_IND PDU chains.

**Comment by hermabe** [comment]
> It seems that discussion has stagnated a bit. Maybe we could have a meeting to recap the discussion and kickoff a new iteration?
I'm thinking, to get it going again, we could at first merge a simplistic implementation supporting only non-interleaved adv reports. This is sufficient for the SoftDeviceController at least.

Agree. The simple implementation seems sufficient for Softdevice controller and the Zephyr Link Layer for now.

**Comment by hermabe** [comment]
Closed in favor of #41337

**Pull request closed without merging**
