### PR TITLE
USB: Fixes for NXP kinetis driver

### PR DESCRIPTION
**Pull request by finikorg**
Cherry-picked from another PR

### CODE REVIEW

**Comment by galak** [comment]
If you desire this fix in 1.14, please open or associate this PR with an Issue.

**Comment by carlescufi** [comment]
@finikorg do we need this for 1.14? What PR is this cherry-picked from?

**Comment by finikorg** [comment]
> @finikorg do we need this for 1.14? What PR is this cherry-picked from?

cherr-picket from harness PR #14874

**Comment by finikorg** [comment]
Patches are applied in another PR, closing

**Pull request closed without merging**
