### PR TITLE
Add lsm6dso multi-instance and use stmemsc common routines

### PR DESCRIPTION
**Pull request by avisconti**
Make this driver multi-instance and use the new API.
    
This commit makes use of some DT macro helpers
In particular:
        - get bus devices with DEVICE_DT_GET
        - get SPI information with SPI_CONFIG_DT_INST
        - get drdy gpios with GPIO_DT_SPEC_GET

The int-pin information has been moved from Kconfig to DT. All the boards/shield using the lsm6dso driver has been updated accordingly. But I have a doubt on file    _./scripts/ci/check_compliance.py_ which is still including a reference to the non-existent symbol LSM6DSO_INT_PIN. Should I remove it as well?

Moreover the driver is now using the stmemsc common routines as requested in issue #33440.

Please note that the common stmemsc routines introduced in #33506 are not carrying the fix required by Nordic platforms yet. This has to be done as a separate PR later on.

### CODE REVIEW

**Comment by richardbarlow** [comment]
I have just verified that this works on the nRF5340 with the patch in #19901 manually applied. I'll create a PR with this additional patch once this change has been merged.

**Comment by richardbarlow** [comment]
@avisconti I'm not well versed in the Zephyr pull request workflow, so I may have missed something, but is there a reason why this PR is currently labelled DNM?

**Comment by avisconti** [comment]
> @avisconti I'm not well versed in the Zephyr pull request workflow, so I may have missed something, but is there a reason why this PR is currently labelled DNM?

@richardbarlow
It is just because it depends on #33506. As soon as that PR will get merged, I will rebase this on it, and remove the DNM.

**Comment by avisconti** [comment]
Rebased after #33506 was merged. I encorporated all suggestions that have been discussed there in a single commit. I will later create a common PR to align all other drivers to same implementation.

**Comment by avisconti** [comment]
@richardbarlow 
Once that this PR will be approved and merged can you possibly prepare a new PR with the changes required by Nordic platforms? Thanks!

**Review by mbolivar-nordic — APPROVED** [review]
LGTM. I just gave this a quick skim since it's following the lines already discussed in detail in the PR which introduced the stmemsc helpers.

**Review by erwango — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Pull request merged**
