### PR TITLE
drivers: pwm: clarify API details

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Clarify the PWM pwm_pin_set_cycles() function API details.

The API aims for synchronous (glitch-free) updates of the PWM period and pulse width, but not all PWM controllers support this.

Similarly, the API aims for independance between channels on multi-channel PWM controllers, but not all PWM controllers support this.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
This is an attempt to address the issues raised by @str4t0m in #34242 in a different way.

**Comment by str4t0m** [comment]
+1 for defining a default behavior for pulse and period update, as well as for the choice of doing it synchronously.
Additionally, I believe it would be helpful if all targets which can't or don't comply to the API specification mention the divergence in a common location. I'd suggest either in the bindings or directly in the source code.

**Comment by henrikbrixandersen** [comment]
> +1 for defining a default behavior for pulse and period update, as well as for the choice of doing it synchronously.
> Additionally, I believe it would be helpful if all targets which can't or don't comply to the API specification mention the divergence in a common location. I'd suggest either in the bindings or directly in the source code.

Right. If this PR is accepted there are a couple of steps, that needs to be performed (as we also discussed on Slack):
* The PWM capture/loopback tests need to have their timeouts adjusted to accommodate PWM controller drivers with synchronous updates of the PWM period/pulse width.
* The existing PWM drivers need to be examined one-by-one to either document their non-synchronous behavior - or implement synchronous behavior, if the underlying hardware supports it but the driver does not.

**Review by rerickson1 — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
