### PR TITLE
subsys/settings: Add const modifier to the value pointer

### PR DESCRIPTION
**Pull request by rakons**
Add const modifier to settings_save_one value pointer.

### CODE REVIEW

**Comment by rakons** [comment]
CC @kapi-no

**Review by jhedberg — APPROVED** [review]

**Review by fnde-ot — APPROVED** [review]

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
Change looks good to me, but still need to fix incompatible pointer issues in a few places.
Oh - I can see you already did that - I will accept this PR ASAP.

----
This is a crazy feature that you can edit somebody else message, even if it lefts a mark :)

**Comment by nvlsianpu** [comment]
```
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/subsys/bluetooth/host/settings.c:251:14: error: passing argument 1 of 'h->export' from incompatible pointer type [-Werror=incompatible-pointer-types]
    h->export(export_func);
```

**Review by kapi-no — APPROVED** [review]

**Comment by nvlsianpu** [comment]
> This is a crazy feature that you can edit somebody else message, even if it lefts a mark :)

Ja, Das ist fantastisch! Wunderbau!

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
