### PR TITLE
soc: expressif: esp32c3: Fix wrong placement of Kconfig

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes a wrong placement of a Kconfig which was put into the wrong file and was bleeding through to every board

### CODE REVIEW

**Comment by nordicjm** [comment]
@sylvioalves should this really be a choice that someone can enable or disable in menuconfig, will the existing part numbers have this new firmware applied and stay with the existing part numbers?

**Comment by sylvioalves** [comment]
> @sylvioalves should this really be a choice that someone can enable or disable in menuconfig, will the existing part numbers have this new firmware applied and stay with the existing part numbers?

Hi, 
1) Currently, only the `SOC_ESP32C3_FH4X` model is rev 1.1.
2) I'd rather use the new config `SOC_ESP32C3_REV_1_1` to indicate the SOC revision instead of the model itself as there could be new chip models using rev 1.1 rom functions.
3) `SOC_ESP32C3_REV_1_1` could be removed as an enable/disable option in menuconfig, i.e., removing the string after the `bool` entry. I just don't get why putting this in `kconfig.soc`is wrong? Is that only because it was made optional?

**Comment by nordicjm** [comment]
`Kconfig.soc` is for sysbuild, so unless there is a common sysbuild config that is being changed or sysbuild needs to know about this field then it should be in `Kconfig` which is not used by sysbuild but is used by normal builds

**Comment by sylvioalves** [comment]
> `Kconfig.soc` is for sysbuild

This is odd and new for me. If it is for sysbuild only, why do I get `SOC_PART_NUMBER` value in normal build as such as ` hello_world` without sysbuild?

**Comment by nordicjm** [comment]
> > `Kconfig.soc` is for sysbuild
> 
> This is odd and new for me. If it is for sysbuild only, why do I get `SOC_PART_NUMBER` value in normal build as such as ` hello_world` without sysbuild?

Worded wrongly, it is used in both applications and sysbuild but the options in `Kconfig.soc` are what sysbuild needs to work, so that's why `Kconfig.soc` declares the symbols for SoCs but does not select the type of CPU etc. because it doesn't need to know that

**Comment by nordicjm** [comment]
See https://docs.zephyrproject.org/latest/hardware/porting/soc_porting.html#write-kconfig-files for details

**Comment by sylvioalves** [comment]
> See https://docs.zephyrproject.org/latest/hardware/porting/soc_porting.html#write-kconfig-files for details

Got it, thanks!

**Review by sylvioalves — APPROVED** [review]

**Comment by sylvioalves** [comment]
@nordicjm built current main for another board target and I can see where the "bleeding" is:
`# CONFIG_SOC_ESP32C3_REV_1_1 is not set`

**Review by wmrsouza — APPROVED** [review]

**Comment by nordicjm** [comment]
> @nordicjm built current main for another board target and I can see where the "bleeding" is: `# CONFIG_SOC_ESP32C3_REV_1_1 is not set` However, it is only there because the kconfig is optional. So making it not optional means that it could stay in `kconfig.soc`, right?

The option being in a .config file is not the bleeding, the bleeding is configuring for a board, running menuconfig and seeing an irrelevant Kconfig option

**Pull request merged**
