### PR TITLE
lvgl: input: temporarry touch implementation

### PR DESCRIPTION
**Pull request by pavlohamov**
Add possibility to transfer mouse event as touch input event on the native_posix (x64) platform.
Use the sdl event filter to grab the mouse events
The main purpose of this code is to add possibility of UI debugging on the native platform (used as emulator) instead of target device. 
This approach is a bit crutchy, but is useful till touch sensor API is merged.

Comments are highly appreciated.

### CODE REVIEW

**Review by vanwinkeljan — CHANGES_REQUESTED** [review]
I think we best first define a touchscreen API and keep the code in lvgl.c common and move the proposed code in to a driver. We already now have 2 PRs floating around just hacking some code in to lvgl.c for touchscreen support, this is not maintainable.

**Comment by pavlohamov** [comment]
> 
> 
> I think we best first define a touchscreen API and keep the code in lvgl.c common and move the proposed code in to a driver. We already now have 2 PRs floating around just hacking some code in to lvgl.c for touchscreen support, this is not maintainable.

**Comment by pavlohamov** [comment]
@vanwinkeljan Totally agree. This solution is just a temporary crutch. I like the implementation based on new zio/rtio API https://github.com/zephyrproject-rtos/zephyr/pull/16119 But for now this PR seems to be abandoned (as whole topic-sensor branch)

**Comment by jfischer-phytec-iot** [comment]
@pavlohamov Please take a look at #22055

**Comment by pavlohamov** [comment]
> 
> 
> @pavlohamov Please take a look at #22055
 
many thanks for letting me know! Indeed i was waiting for this functionality.

Closing this PR

**Pull request closed without merging**
