### PR TITLE
drivers/clock_control: Add cAVS clock driver

### PR DESCRIPTION
**Pull request by edersondisouza**
Simple driver that allows one to choose the clock speed of xtensa cores.

Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>

This is an alternative implementation to https://github.com/zephyrproject-rtos/zephyr/pull/45396

### CODE REVIEW

**Comment by edersondisouza** [comment]
v2: 
 - Fix some include files issues;
 - Add a simple testcase.

**Review by andyross — DISMISSED** [review]
This one looks good to me too.  You could consider a two-layer architecture too where there's a soc-level driver and a higher level wrapper here.

**Comment by dcpleung** [comment]
If you are putting in under `drivers/clock_control`, I think you need to implement it using the clock_control API.

**Comment by edersondisouza** [comment]
> If you are putting in under `drivers/clock_control`, I think you need to implement it using the clock_control API.

I thought about that, but I'm not sure the mapping rate->clock is perfect, and, IIUC, not all other drivers inside `clock_control` use it as well.

But maybe I'm looking at bad examples. Do you think it makes sense to use set_rate to change the clock in use, @dcpleung?

**Comment by edersondisouza** [comment]
> A quick look says that all drivers implements those APIs. So I think this also needs to implement the clock control API.

I'm quite positive that `nrf_clock_calibration` doesn't, but maybe it's the odd one. I'll look into implementing it, thanks!

**Comment by andyross** [comment]
Is this a good time for me to drive by while saying that I liked this much better as a SOC-level driver?  There are good abstractions and bad abstractions, and "clock control" is IMHO closer to the latter.  It's just not a single, clear, standard Thing That Computers Do.  Everything does this a little differently.  Everything has weird rules that aren't well-captured by a single API.

Not otherwise engaging with the bikeshed.  But I see the consistency hobgoblins foolishly sharpening their perfect spears for another assault on the Merely Good.  Maybe we should just pick something and merge this?

**Comment by ceolin** [comment]
> > If you are putting in under `drivers/clock_control`, I think you need to implement it using the clock_control API.
> 
> I thought about that, but I'm not sure the mapping rate->clock is perfect, and, IIUC, not all other drivers inside `clock_control` use it as well.
> 
> But maybe I'm looking at bad examples. Do you think it makes sense to use set_rate to change the clock in use, @dcpleung?

I agree with @dcpleung, I find it very confuse a driver listed as
clock control that does not implment the clock control interface. I
believe most drivers here implement the basic interface and have their
additional API on top.

Regarding rate->clock that is probably not the best relation indeed. Though
rate is represented as an opaque type (clock_control_subsys_ratet_t)
so you can your own type.

Another possible problem with this implementation not following the
clock control API and not using a device handle associated with is that you basically
discards the possibility of this being used from an user thread. (I
know that these platforms don't have userspace, but future versions may have)

Looking the clock control API I just noticed that
clock_control_get_rate() is not using the opaque type and that looks wrong. But changing it you basically have 
set/get methods that use an opaque type defined by your driver, so it seems a fair map to me.

**Review by ceolin — DISMISSED** [review]

**Review by andyross — DISMISSED** [review]
Still +1.  This is my favorite version so far.

**Review by nordic-krch — DISMISSED** [review]
looks good

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

**Comment by edersondisouza** [comment]
v4:
 - Remove duplicated line from DTS binding;
 - Use proper include.

**Review by MaureenHelm — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Pull request merged**
