### PR TITLE
release: Zephyr 2.2.0-rc1

### PR DESCRIPTION
**Pull request by jhedberg**
Bumped to v2.2.0-rc1

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by galak** [comment]
Would like to see PR #22629 merged before, but not critical.  Build issue was reported in nightly builds

**Review by carlescufi — CHANGES_REQUESTED** [review]
Let's give #22013 a fighting chance

**Comment by galak** [comment]
> Would like to see PR #22629 merged before, but not critical. Build issue was reported in nightly builds

done

**Review by galak — APPROVED** [review]

**Comment by carlescufi** [comment]
> Let's give #22013 a fighting chance

Gave it a chance, but we've decided to postpone it to 2.3.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
