### PR TITLE
flash: stm32l4: disable dcache before writting

### PR DESCRIPTION
**Pull request by vaussard**
Disable the data cache before writing to Flash, in order to workaround
silicon errata 2.2.3: "Data cache might be corrupted during Flash memory
read-while-write operation". The data cache is conditionally re-enabled
once the write is completed.

This silicon bug has been encountered while stress testing the
implementation. Here are the events leading to the fault:
- Code is executing from Flash bank 1
- A write to Flash bank 2 is initiated
- The Cortex SysTick interrupt fires while waiting for Flash write
  completion

In that case, the Flash controller will perform a read-while-write
operation in order to execute the ISR code. As the data cache is enabled
by default after reset, a corruption occurs due to the silicon bug,
leading to bizarre data bus faults or unaligned access faults inside
_timer_int_handler() or one of the functions called by the ISR.

Applying the workaround devised by ST fixes the problem.

### CODE REVIEW

**Comment by vaussard** [comment]
@erwango I do not know if other STM32 MCUs are affected by this bug, I did not checked all the silicon errata ^_^. It took me some time to figure out why the systick ISR was faulting. Hardware bugs are always the most entertaining.

**Comment by aurel32** [comment]
> Disable the data cache before writing to Flash, in order to workaround
> silicon errata 2.2.3: "Data cache might be corrupted during Flash memory
> read-while-write operation". The data cache is conditionally re-enabled
> once the write is completed.
> 
> This silicon bug has been encountered while stress testing the
> implementation. Here are the events leading to the fault:
> 
>     * Code is executing from Flash bank 1
> 
>     * A write to Flash bank 2 is initiated

Many of the STM32L4 devices only have a single bank of flash. This issue is not listed in their errata sheet. Should we limit this workaround this to dual-bank devices, which if I understand correctly are the ones which can have >= 1MB of flash?

**Review by galak — APPROVED** [review]

**Comment by vaussard** [comment]
> Many of the STM32L4 devices only have a single bank of flash. This issue is not listed in their errata sheet. Should we limit this workaround this to dual-bank devices, which if I understand correctly are the ones which can have >= 1MB of flash?

Hi @aurel32, yes this is only needed for dual-bank devices as it affects read-while-write. From what I recall, I only saw 2 banks on devices with >= 1MB, but I would not swear that this is the case for all STM32L4xx.

I checked the errata of STM32F469/F479 and they are also affected. So this bug is present on at least another family.

I had an afterthought: disabling/enabling the data cache has probably some penalty. It may not be the most efficient to do that for each double-word. We could do that at the upper level. But some benchmarking would be needed to assess the impact on performances of both approaches.

**Comment by erwango** [comment]
> @erwango I do not know if other STM32 MCUs are affected by this bug, I did not checked all the silicon errata ^_^. It took me some time to figure out why the systick ISR was faulting. Hardware bugs are always the most entertaining.

Thanks for investigation and busting this out. On which SoC are you working on?
I'll check internally what other SoC references impacted by this issue. Meanwhile, as suggested by @aurel32, can you put the change under the SoC reference covered by the errata sheet ? (fyi, I've not seen in the first errata I've just checked (STM32L476xx/STM32L486x)).

**Review by erwango — CHANGES_REQUESTED** [review]
Fine with the change but please limit behavior on currently impacted references for now.

**Comment by aurel32** [comment]
> I'll check internally what other SoC references impacted by this issue. Meanwhile, as suggested by @aurel32, can you put the change under the SoC reference covered by the errata sheet ? (fyi, I've not seen in the first errata I've just checked (STM32L476xx/STM32L486x)).

@erwango I have checked the STM32L496 errata sheet: https://www.st.com/content/ccc/resource/technical/document/errata_sheet/group0/53/9a/db/26/c5/a9/4d/6d/DM00264473/files/DM00264473.pdf/jcr:content/translations/en.DM00264473.pdf

@vaussard Note that it should be possible to detect dual bank devices by checking if `FLASH_OPTR_DUALBANK`. It's the strategy used on STM32F7.

**Comment by vaussard** [comment]
> On which SoC are you working on?

STM32L4A6
That would be wonderful if you have an easy way to check which devices are affected.

> @vaussard Note that it should be possible to detect dual bank devices by checking if `FLASH_OPTR_DUALBANK`. It's the strategy used on STM32F7.

Unfortunately it does not look like that my STM32L4 has this bit of information. There is a `DUALBANK` configuration in the option bytes, but it is to allow operating as single or dual bank thus we cannot rely on it.

> Fine with the change but please limit behavior on currently impacted references for now.

Let's not rush and take some time to cook an appropriate solution for all affected devices. Let me know if you have an easy way to get that information.

**Comment by erwango** [comment]
> Let me know if you have an easy way to get that information.

I've sent an internal request. I'll get back to you as soon as I have a feedback.
Regarding an externally available way to get the info, I am not quite optimistic..

**Comment by aurel32** [comment]
> > @vaussard Note that it should be possible to detect dual bank devices by checking if `FLASH_OPTR_DUALBANK`. It's the strategy used on STM32F7.
> 
> Unfortunately it does not look like that my STM32L4 has this bit of information. There is a `DUALBANK` configuration in the option bytes, but it is to allow operating as single or dual bank thus we cannot rely on it.

I meant to check if this bit exists using `#ifdef FLASH_OPTR_DUALBANK`, which seems to be defined for the STM32L4A6. That doesn't tell you if the device actually runs in double bank mode, but it at least narrows down the number of affected SoCs. With the current HAL, only the STM32L471, STM32L475, STM32L476, STM32L485, STM32L486, STM32L496 and STM32L4A6 SoCs define this bit.

**Comment by erwango** [comment]
@vaussard, I'm trying to get internal feedback but no news for now. 
Though, I think it'd be good to have this in 1.14, so please do with available information for now. Seems that above proposal from @aurel32 is reasonable in this concern.

**Comment by vaussard** [comment]
Ok @erwango, I will proceed as suggested.

**Comment by erwango** [comment]
@vaussard , do you think you can submit something for 1.147 target?

**Comment by vaussard** [comment]
Yes @erwango, sorry I was on holidays for 1 week. I will do the change + validation ASAP when I cleared by backlog.

**Comment by galak** [comment]
> Yes @erwango, sorry I was on holidays for 1 week. I will do the change + validation ASAP when I cleared by backlog.

Be aware the window for 1.14 is getting short so please give this some attention if we want this fix in 1.14

**Comment by vaussard** [comment]
Shippable is failing for tests/kernel/semaphore/sema_api/, this does not look related to my PR. Should I rebase on master or recheck?

**Review by erwango — APPROVED** [review]
Did some basic non reression tests and this is working.
Though, I've not been able to exercise the silicon bug.

**Comment by vaussard** [comment]
Thank you @erwango. Yes it takes some time and effort to hit this silicon bug.

**Pull request merged**
