### PR TITLE
drivers: i2c: sifive Adjust calculation of clock speed.

### PR DESCRIPTION
**Pull request by aloeppert**
As measured before this change, the speeds of
STANDARD and FAST are above the maximum of each.

This change dials back the speeds to be under the
maximums for each speed and enables FAST_PLUS and
HIGH speeds as well.

Signed-off-by: Anthony Loeppert <anthony@loeppert.net>

### CODE REVIEW

**Comment by aloeppert** [comment]
Plots after this change:
standard:
STANDARD

fast:
FAST

fastplus:
FAST_PLUS

high:
HIGH

High looks a bit suspect as the clock doesn't reach 3.3V but enabled anyway.

**Review by pabigot — COMMENTED** [review]
So this is the can of worms:

Target                | STD | FAST | FAST+ | HIGH | ULTRA
--------------------- | --- | ---- | ----- | ---- | -----
frdm_k64f             | 104 | 925  |   -   |  -   |  - 
nucleo_l476rg         | 111 | 434  |   -   |  -   |  - 
nrf52840_pca10056     |  99 | 409  |   -   |  -   |  - 
hifive1_revb (master) | 111 | 471  | 1163  |  !   |  - 
hifive1_revb (pr)     | 104 | 387  | 793   |  !   |  - 

(For hifive1_revb master I used your patch to set the FAST+ and HIGH speeds, but removed the nudge.  I also verified the measurements match the unpatched code for STD and FAST+.  hifive1_revb (pr) uses your as-submitted patch.  The `!` on HIGH means that I2C did not work at that speed: the logic analyzer didn't show enough transitions on SCL to measure a frequency: that might be due to the IKS-01A3 shield which has a lot of stuff on the bus.)

So we see several things.  First, NXP (and SiLabs) don't agree with Nordic and ST on what "I2C_SPEED_FAST" means: they have 1 MHz while the others have 400 kHz.  Somebody should do something about that.  I've opened #24067 for that.

Second, pretty much everybody is faster than spec for at least one speed.

Looking at this PR alone: The algorithm currently used in this driver matches the [reference implementation](https://github.com/sifive/freedom-metal/blob/6fd4b0a4e1c12b9ab159aea42fbe5ff7e6f7e81f/src/drivers/sifive_i2c0.c#L71).  At some point the driver should switch to the reference implementation.  It does look like the hifive1_revb has the largest out-of-spec variance (over 15%), but since we observe similar errors in other platforms I'd rather follow the reference implementation algorithm until this switches to freedom-metal (which may need to be fixed as 15% is pretty high).

Just my opinion as I don't maintain this driver.

**Comment by aloeppert** [comment]
> So we see several things. First, NXP (and SiLabs) don't agree with Nordic and ST on what "I2C_SPEED_FAST" means: they have 1 MHz while the others have 400 kHz. Somebody should do something about that. I've opened #24067 for that.

> Just my opinion as I don't maintain this driver.

Thanks for taking a look and commenting!  I'll close this PR in favor of a holistic i2c approach you propose.

**Comment by Techniqueapple** [comment]
🥰🥰🥰🥰

**Pull request closed without merging**
