### PR TITLE
Refactor IPM mailboxes handling

### PR DESCRIPTION
**Pull request by finikorg**
Fixes issues accessing byte-by-byte 32 bits registers

### CODE REVIEW

**Review by tyrantlizard77 — DISMISSED** [review]

**Comment by andrewboie** [comment]
Might also be worthwhile to switch to QMSI driver if they have one.

**Comment by nashif** [comment]
> Might also be worthwhile to switch to QMSI driver if they have one.

Yes, we have a Jira open for this

**Review by nashif — CHANGES_REQUESTED** [review]
Can you please fix your commit messages? No Signed-off-by...

**Comment by finikorg** [comment]
I will add signed linew

**Pull request closed without merging**
