### PR TITLE
boards: arm: nucleo_g071rb enable PWM

### PR DESCRIPTION
**Pull request by ABOSTM**
boards: arm: nucleo_g071rb enable PWM

Tested with tests/drivers/pwm/pwm_api/
(requires https://github.com/zephyrproject-rtos/zephyr/pull/27204)
and with oscillo.

### CODE REVIEW

**Comment by ABOSTM** [comment]
Rebase

**Comment by ABOSTM** [comment]
Builkite error has nothing to do with current PR:
`117/202 qemu_x86_64               tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls FAILED Exited with 1 (qemu)`

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
Approved but DNM until #27204 is merged

**Review by FRASTM — APPROVED** [review]

**Comment by ABOSTM** [comment]
#27204 is now merged.
@carlescufi, @galak  @nashif could you merge this PR?

**Pull request merged**
