### PR TITLE
samples: tests: Rename duplicated testcases

### PR DESCRIPTION
**Pull request by katgiadla**
Names of some testcases are duplicated in another files.
This change rename duplicated testcases.

Signed-off-by: Katarzyna Giadla <katarzyna.giadla@nordicsemi.no>

### CODE REVIEW

**Review by PerMac — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Drive by kibitz: maybe it's worth having a warning in twister about this?  This happens all the time when people start new cases or tests by cutting and pasting old ones, and the current twister architecture (which disambiguates by directory) doesn't care.

Alternatively: give up and just allow these to be "local" names (and presumably much shorter names!) scoped to the test path.

**Comment by PerMac** [comment]
@andyross +1 for adding an error (after duplicates are removed) when a duplicate is detected. In theory names only have to be locally (in a yaml) independent. However, duplicates cause problems during reporting. Depending on the report type or a tool used for their analysis the same entries can overwritten. 

In the alternative you proposed the names would in the end be probably even longer. We would have to add also a path In order to maintain uniqueness in a report entries.

**Comment by andyross** [comment]
> However, duplicates cause problems during reporting.

Well, right, because of exactly this collision.  Twister itself views the test "name" from its perspective as "$PATH/$TAG", where the rest of the world downstream of the report generation sees only "$TAG".  So the suggestion becomes: get twister to emit (a cooked version of) the former and not the latter.  Then the case names become things like "smp" or "arc" or whatever special case is being exercised without the author needing to know the global name of the test under development.  It's a win or everyone.

**Review by anangl — APPROVED** [review]

**Review by PerMac — APPROVED** [review]

**Comment by PerMac** [comment]
I'm not sure if I'm following. You proposed that the test id would be mostly path dependent and only the last section will be user defined (in yaml)? If so, I think the argument by @nashif was that we don't want that due to tests changing their locations, which would change their id (sorry Anas if I got it wrong). 
TBH I am for this idea, IMO it would help with tests traceability. Currently their is no respected schema for scenarios names and simple grouping them by sections of their names doesn't work.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
