### PR TITLE
Deprecate MODEM_GSM_PPP driver

### PR DESCRIPTION
**Pull request by rerickson1**
The MODEM_GSM_PPP driver is now obsolete and is replaced by MODEM_CELLULAR.
The new MODEM_CELLULAR makes use of the new modem subsystem for better reuse and reliability.

### CODE REVIEW

**Comment by jukkar** [comment]
Also cmux and uart muxer can be deprecated as they are related to each other.
Fortunately the CONFIG_UART_MUX is already experimental so it simplifies things as we should be able to just remove it but CONFIG_GSM_MUX is not so that one need deprecation.
See relevant options in
```
drivers/console/Kconfig.gsm_mux
drivers/console/Kconfig
```

**Comment by ycsin** [comment]
cc @AzamLukman

**Comment by bjarki-trackunit** [comment]
@jukkar GSM_MUX is dependent on UART_MUX, even though its not obvious in the Kconfigs, removing it makes the GSM_MUX effectively useless. 

There is only one configuration used in-tree which uses GSM_MUX, and that is MODEM_GSM_PPP (gsm_ppp.c). MODEM_GSM_PPP enables GSM_MUX and NET_PPP (the ppp.c UART driver), which then selects UART_MUX, since this is effectively a dependency of GSM_MUX.

We should therefore deprecate the GSM_MUX, UART_MUX, and MODEM_GSM_PPP. When we finally get to remove it, we need to remove this https://github.com/zephyrproject-rtos/zephyr/blob/3384ebb00feb0de26b1f843eab01908a69db6332/drivers/net/ppp.c#L1008-L1026

After the three above modules are gone, we should consider reworking NET_PPP (ppp.c) with an implementation based on the modem modules. ppp.c can be directly replaced with a  `modem_ppp` instance connected to a `modem_backend_uart` instance.

**Comment by jukkar** [comment]
> @jukkar GSM_MUX is dependent on UART_MUX, even though its not obvious in the Kconfigs, removing it makes the GSM_MUX effectively useless.

Yes, I know that. I was not suggesting that we remove uart mux immediately.

> 
> There is only one configuration used in-tree which uses GSM_MUX, and that is MODEM_GSM_PPP (gsm_ppp.c). MODEM_GSM_PPP enables GSM_MUX and NET_PPP (the ppp.c UART driver), which then selects UART_MUX, since this is effectively a dependency of GSM_MUX.
> 
> We should therefore deprecate the GSM_MUX, UART_MUX, and MODEM_GSM_PPP. When we finally get to remove it, we need to remove this

Yes, those need to be removed at the same time after the deprecation time is done.

> 
> https://github.com/zephyrproject-rtos/zephyr/blob/3384ebb00feb0de26b1f843eab01908a69db6332/drivers/net/ppp.c#L1008-L1026
> 
> After the three above modules are gone, we should consider reworking NET_PPP (ppp.c) with an implementation based on the modem modules. ppp.c can be directly replaced with a `modem_ppp` instance connected to a `modem_backend_uart` instance.

Yes, agreed.

**Review by bjarki-andreasen — APPROVED** [review]
Looks good!

**Review by jukkar — APPROVED** [review]

**Review by ycsin — APPROVED** [review]

**Pull request merged**
