### PR TITLE
boards: shields: fix support for rk055hdmipi4ma0 on RT595

### LINKED ISSUE #69302: NXP: Shield rk055hdmipi4ma0 fails to build with mimxrt595_evk_cm33
With v3.6.0-rc3 tag, the [display sample](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/drivers/display) fails to build for the board `mimxrt595_evk_cm33` using the display shield `rk055hdmipi4ma0`.  

Reverting to 638e3d5d9c40b27ef745d6ebb131406aad728f53 when this shield was introduced, the sample builds and runs well on this hardware.

Below is the build log.

```
$ west build -b mimxrt595_evk_cm33 -d ../../display_RT500/ samples/drivers/display/ --pristine -- -DSHIELD=rk055hdmipi4ma0
-- west build: making build dir /home/snellda/zNXPmicro/display_RT500 pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/snellda/zNXPmicro/zephyrproject/zephyr/samples/drivers/display
-- CMake version: 3.28.3
-- Found Python3: /home/snellda/venv/bin/python (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /home/snellda/.cache/zephyr
-- Zephyr version: 3.6.0-rc3 (/home/snellda/zNXPmicro/zephyrproject/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Board: mimxrt595_evk_cm33
-- Shield(s): rk055hdmipi4ma0
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.4 (/home/snellda/zephyr-sdk-0.16.4)
-- Found toolchain: zephyr 0.16.4 (/home/snellda/zephyr-sdk-0.16.4)
-- Found Dtc: /home/snellda/zephyr-sdk-0.16.4/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/snellda/zNXPmicro/zephyrproject/zephyr/boards/arm/mimxrt595_evk/mimxrt595_evk_cm33.dts
-- Found devicetree overlay: /home/snellda/zNXPmicro/zephyrproject/zephyr/boards/shields/rk055hdmipi4ma0/rk055hdmipi4ma0.overlay
-- Found devicetree overlay: /home/snellda/zNXPmicro/zephyrproject/zephyr/boards/shields/rk055hdmipi4ma0/boards/mimxrt595_evk_cm33.overlay
devicetree error: /home/snellda/zNXPmicro/zephyrproject/zephyr/boards/shields/rk055hdmipi4ma0/boards/mimxrt595_evk_cm33.overlay:16 (column 1): parse error: undefined node label 'touch_controller_rk055hdmipi4ma0'
-- In: /home/snellda/zNXPmicro/display_RT500/zephyr, command: /home/snellda/venv/bin/python;/home/snellda/zNXPmicro/zephyrproject/zephyr/scripts/dts/gen_defines.py;--dts;/home/snellda/zNXPmicro/display_RT500/zephyr/zephyr.dts.pre;--dtc-flags;'-Wno-simple_bus_reg';--bindings-dirs;/home/snellda/zNXPmicro/zephyrproject/zephyr/dts/bindings;--header-out;/home/snellda/zNXPmicro/display_RT500/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/home/snellda/zNXPmicro/display_RT500/zephyr/zephyr.dts.new;--edt-pickle-out;/home/snellda/zNXPmicro/display_RT500/zephyr/edt.pickle;--vendor-prefixes;/home/snellda/zNXPmicro/zephyrproject/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /home/snellda/zNXPmicro/zephyrproject/zephyr/cmake/modules/dts.cmake:268 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /home/snellda/zNXPmicro/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /home/snellda/zNXPmicro/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/snellda/zNXPmicro/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/home/snellda/venv/bin/python -B/home/snellda/zNXPmicro/display_RT500 -GNinja -DBOARD=mimxrt595_evk_cm33 -DSHIELD=rk055hdmipi4ma0 -S/home/snellda/zNXPmicro/zephyrproject/zephyr/samples/drivers/display
```

### PR DESCRIPTION
**Pull request by danieldegrasse**
In 42c6f3311be (boards: stop using kscan for LVGL touch input), GT911
node label was renamed for rk055hdmipi4ma0 shield. The node label rename
was missed in the RT595 EVK overlay, fix this.

Fixes #69302

 drivers: display: display_hx8394: use MIPI LPM during init commands

 Although not documented in the HX8394 datasheet, it seems that the
 display fails to initialize if MIPI HS mode is used to send
 configuration commands. Therefore, we must make sure all initialization
 commands are sent with the MIPI_DSI_MSG_USE_LPM flag set

### CODE REVIEW

**Review by decsny — DISMISSED** [review]

**Review by dleach02 — DISMISSED** [review]

**Comment by mjchen0** [comment]
Is the reason my earlier change broke the rk055 display because it only supports high speed mode for DCS_LONG_WRITES and not for the other transfer types?

Since it's now possible to specify the speed/mode to use per transfer, it seems a bit odd that the speed default changes depending on the cmd/transfer type, and that the flag is ignored by the other transfer types.

If it's a limitation of the rk055 that some transfers should be high speed and some must be low speed, then it should use the msg flag to specify explicitly which mode to use (either high or low) for the particular cmd. Other MIPI DSI devices might be fine with always high speed cmds, which is the case for the display I was working with.

**Comment by danieldegrasse** [comment]
> Is the reason my earlier change broke the rk055 display because it only supports high speed mode for DCS_LONG_WRITES and not for the other transfer types?

> Since it's now possible to specify the speed/mode to use per transfer, it seems a bit odd that the speed default changes depending on the cmd/transfer type, and that the flag is ignored by the other transfer types.

I don't see anything in the datasheet for the HX8394 specifying that, but it is definitely possible I missed it. Some of the initialization commands for the HX8394 panel are long enough they should be sent in high speed mode, so I don't think there is an issue with the transition sequence to HS mode. I'll put a DNM on this until I get a chance to update the HX8394 panel driver to use low power mode for short commands.

**Comment by danieldegrasse** [comment]
hx8394 driver has been updated, removing DNM

**Review by dleach02 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@erwango, can you help review

**Comment by danieldegrasse** [comment]
@erwango friendly ping :)

**Review by erwango — APPROVED** [review]

**Pull request merged**
