### PR TITLE
emul: Add data and parent pointers to emulators

### PR DESCRIPTION
**Pull request by yperess**
Emulators are difficult to work with, they generally require maintaining
some state in a mutable data struct. Since the emulator struct doesn't
support a data field like devices do, the pattern seems to be to add it
to the configuration. This makes following the logic of where things are
difficult.

1. Add a `struct emul *parent` structure to the espi/i2c/spi emulator
   structs to make it easier when casting up.
2. Add a `void *data` field to `struct emul` to hold the data for
   emulators.

Signed-off-by: Yuval Peress <peress@chromium.org>

### CODE REVIEW

**Review by sjg20 — APPROVED** [review]
My original intent was to make emulators devices. This received strong pushback from one person, who (later) said that he no-longer had an opinion or a say in it...it was a bit confusing.

But anyway, we might consider making emulators into devices and putting them in the DT. It does feeling that you are solving the same problems over again, building infra that already exists for devices.

**Comment by yperess** [comment]
> My original intent was to make emulators devices. This received strong pushback from one person, who (later) said that he no-longer had an opinion or a say in it...it was a bit confusing.
> 
> But anyway, we might consider making emulators into devices and putting them in the DT. It does feeling that you are solving the same problems over again, building infra that already exists for devices.

Yes, I was very surprised they weren't devices. It seems odd to basically work with 2 different APIs and have them basically do the same thing. Would you like me to make that change here?

**Review by jeremybettis — APPROVED** [review]

**Comment by yperess** [comment]
Ping on this PR, looks like there are no objections here.

**Comment by yperess** [comment]
I force pushed with no changes to re-trigger the CI since it had the documentation build infra break

**Review by jackrosenthal — APPROVED** [review]

**Pull request merged**
