### PR TITLE
Revert "samples: net: lwm2m_client: Use Ethernet in QEMU Cortex-M3"

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
This reverts commit 8e3fc793d3bcb66ef347685bd4d610e04806a59b as it broke main (since the qemu_cortex_m3 excludes all tests with the net tag: https://github.com/zephyrproject-rtos/zephyr/actions/runs/3997309184/jobs/6858462310)

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
Does it have to revert all?

This app builds fine, but can we just drop those lines from "integration platforms"?

**Review by fabiobaltieri — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
> Does it have to revert all?
> 
> This app builds fine, but can we just drop those lines from "integration platforms"?

The exclude was put there in order to limit the number of platforms for running network tests in CI: de8d755c5403d7ac43bfd8c4c5860abb33c1a3a4

**Review by aescolar — APPROVED** [review]

**Comment by aescolar** [comment]
> Does it have to revert all?
> 
> This app builds fine, but can we just drop those lines from "integration platforms"?

As main is broken right now, it is best to revert right away, and reapply after with whatever fixes.

**Comment by SeppoTakalo** [comment]
Fix would be https://github.com/zephyrproject-rtos/zephyr/pull/54063

**Comment by fabiobaltieri** [comment]
Merging, I'm usually all for fix forward but it looks like the conversation is still open, let's revert and revisit.

**Pull request merged**
