### PR TITLE
kernel: Do not use sys_clock_ticks_per_sec in _ms_to_ticks()

### LINKED ISSUE #8895: Failed test: kernel.common.timing.pending on nrf51_pca10028 and nrf52_pca10040 (tests/kernel/pending/kernel.common.timing)
test fails on nrf51/nrf52

```
***** delaying boot 1000ms (per build configuration) *****
 ***** Booting Zephyr OS 1.12.99 (delayed boot 1000ms) *****
 Running test suite pend
 ===================================================================
 starting test - test_pending
 Testing preemptible threads block on fifos ...
 Testing fifos time-out in correct order ...
 Testing  fifos delivered data correctly ...
 Testing preemptible threads block on lifos ...
 Testing lifos time-out in correct order ...
 Testing lifos delivered data correctly ...
 Testing preemptible thread waiting on timer ...

     Assertion failed at zephyr.git/tests/kernel/pending/src/main.c:412: test_pending: ((timer_end_tick < timer_start_tick + NUM_SECONDS(1)) is true)
 Task waiting on timer error
 FAIL - test_pending
 ===================================================================
 ===================================================================
 RunID: ci-180710-1801-1919:lisa
 PROJECT EXECUTION FAILED

```

### PR DESCRIPTION
**Pull request by pizi-nordic**
The value of sys_clock_ticks_per_sec is obtained using
simple integer division with rounding toward zero. As result
using this variable in _ms_to_ticks() introduces some error.

This PR eliminates sys_clock_ticks_per_sec from equation
used in _ms_to_ticks() removing introduced error.

Also, this PR fixes #8895.

Please note, that this PR is based on top of #9137.

### CODE REVIEW

**Comment by pizi-nordic** [comment]
@andrewboie, @andyross: Some advice needed.

This PR introduces a correct a round up in _ms_to_ticks(), which fixes a shorter than expected sleep time when sleep over several ticks was requested. However this round-up introduced another errors which are visible here: https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/19362/5/tests

The tests fail because `N * rounded_up_ms_to_ticks(T)` is larger than `rounded_up_ms_to_ticks(N * T)` .
I do not know how to solve this problem in a correct way. IMHO we have the following options (short-term):

- Accept the situation and update failing tests.
- Round up `sys_clock_hw_cycles_per_tick` and use simple division in `_ms_to_ticks()`: In such case the `k_sleep()` and friends will always sleep longer than expected (but other side effects could appear).

What do you think?

**Review by andyross — APPROVED** [review]

**Comment by andyross** [comment]
Not having looked at the code: my preference would be to fix the test.  Hyper-tight tolerances on timer behavior is always going to cause problems.  The relevant standards (this is a POSIX test) don't general promise that anyway.

**Comment by pizi-nordic** [comment]
@andyross: I have one more question: At the moment the _ms_to_ticks() rounds up, while __ticks_to_ms() rounds down. As result, the `__ticks_to_ms(_ms_to_ticks(n)) != n`. Do you know what is the purpose of such design?

**Comment by andyross** [comment]
I don't.  And I'd be terrified to change it lest we break something subtle that relies on positive-definite timer intervals or something.

Really the whole low level timer subsystem needs rework.  I'm looking at it right not just in the context of spinlockification and realizing there's a bunch of odd cruft in there.

**Comment by pizi-nordic** [comment]
What I noted while working on https://github.com/zephyrproject-rtos/zephyr/issues/8896, is that we are often changing units. It works perfectly as long as there is no rounding during this conversion (or rounding is in the same direction, but this just hides the problem). IMHO a lot of issues popping up on nRF5x platform are related to loss of accuracy during these conversions.

Are there any plans to remove ticks from the Zephyr and leave tickess as only supported mode?
Also, could you please elaborate a bit more about current problems in tickless mode? (you mentioned some few weeks ago, but without details)

**Comment by ioannisg** [comment]
@pizi-nordic I am just wondering; does this PR overlap with #9137 ?

**Comment by pizi-nordic** [comment]
@ioannisg: As stated in the description:
> Please note, that this PR is based on top of #9137.
:)

**Pull request merged**
