### PR TITLE
DTS updates for HTS221 Sensor

### PR DESCRIPTION
**Pull request by galak**
* Move to using new defines to remove dts_fixup
* Move to get i2c addr & gpio info from DTS

### CODE REVIEW

**Review by erwango — APPROVED** [review]

**Review by avisconti — APPROVED** [review]

**Comment by galak** [comment]
@avisconti do you know how the HTS221 is wired up on the ArgonKey (ie is DRDY wired up to a GPIO and if so which one?)

**Comment by avisconti** [comment]
> @avisconti do you know how the HTS221 is wired up on the ArgonKey (ie is DRDY wired up to a GPIO and if so which one?)

It is connected to PA2 pad of stm32.

**Comment by galak** [comment]
> It is connected to PA2 pad of stm32.

Do you know what we should add to the DTS for this:

`<&gpioa 2 GPIO_INT_ACTIVE_LOW>;`

**Comment by avisconti** [comment]
> > It is connected to PA2 pad of stm32.
> 
> Do you know what we should add to the DTS for this:
> 
> `<&gpioa 2 GPIO_INT_ACTIVE_LOW>;`

Yes:
irq-gpios = <&gpioa 2 0>;

**Pull request merged**
