### PR TITLE
samples: bluetooth: peripheral_dis: add dst store

### PR DESCRIPTION
**Pull request by alexeRadu**
This will fix the error given while saving trying to save the
mac address to the store:

<err> bt_settings: Failed to save ID (err -2)

Signed-off-by: Radu Alexe <radu.alexe@nxp.com>

### CODE REVIEW

**Comment by Vudentz** [comment]
Im fine with this change Im just not so sure we want to keep this code in a sample like, at least I don't see the point of registering a settings backend.

**Comment by alexeRadu** [comment]
Can we then agree to keep this change now and later, if/when someone has the bandwidth to change this sample and remove the use of a backend?

**Comment by carlescufi** [comment]
@joerchan and @jhedberg can you take a look?

**Comment by joerchan** [comment]
Seems strange. Shouldn't it be possible to configure these as not writable? Which MAC addresses is being written to store?

**Comment by joerchan** [comment]
@alexeRadu Can you please provide some details to the issue,

**Comment by alexeRadu** [comment]
Sure,

the settings API works with backends that access different media (like Flash and filesystems) to save/load settings. There are several backends provided by the library but you can bypass it and create your own backend (which is exactly what was happening here in the *peripheral_dis* samples). The problem is that the sample only registers a src backend and not a dst backend so when the MAC is save it reports an error.

The patch creates a dummy dst backend so that the would be no error.

**Comment by joerchan** [comment]
> Im fine with this change Im just not so sure we want to keep this code in a sample like, at least I don't see the point of registering a settings backend.

Yeah, I agree, there is no reason to have a settings backend here.

**Comment by alexeRadu** [comment]
Fixed by @joerchan.

**Pull request closed without merging**
