### PR TITLE
Samples: Example how to use settings subsystem

### PR DESCRIPTION
**Pull request by zarnobarintive**
Example shows how to use settings with NVS backend.
It shows usage of save and save_one + set/export handlers.

Signed-off-by: Bartłomiej Żarnowski <bartlomiej.zarnowski@intive.com>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
Currently there is also PR:#20942 open for adding settings sample which shows all settings features exhaustively.

This PR is the basic one, therefore in my opinion we could have them both.

**Comment by zarnobarintive** [comment]
@nvlsianpu @nashif 
Is there any more requirements need to be fulfilled to have this PR approved and merged?

**Comment by nvlsianpu** [comment]
I would add at last one simulation target support (qemu, or native_posix) and harness, so sample will be checked in the CI.

**Comment by zarnobarintive** [comment]
> I would add at last one simulation target support (qemu, or native_posix) and harness, so sample will be checked in the CI.

Not sure what you mean "harness". I added ```qemu_cortex_m3``` target, and all looks fine from CI perspective.

**Comment by nvlsianpu** [comment]
@nashif This is more basic sample for the settings subsystem. I can accept it beside the one introduced in #20942 (which almost exhausted all possibilities of API usage).

Need your opinion before requesting any changes here (eg move this to a settings/basic and mine to settings/advance directories).

**Pull request closed without merging**
