### PR TITLE
WIFI: eswifi driver improvement blocking/non-blocking send/connect/recv

### PR DESCRIPTION
**Pull request by loicpoulain**
Current implementation unconditionnaly performs connect and send
synchronously. Add support for non-blocking version using eswifi
workqueue.

Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
Commit message:

> Current implementation unconditionnaly performs connect and send
synchronously. Add support for non-blocking version using eswifi
workqueue.

I'd suggest to use consistent terminology. "Synchronous" and "asynchronous" are too multi-faceted words. With respect to sockets, terms "blocking" and "non-blocking" are well-defined and should be rather used.

**Comment by pfalcon** [comment]
Also, this PR seems to have commits unrelated to the title of the PR (such unrelated commits are known to cause delays with reviews).

**Comment by loicpoulain** [comment]
@pfalcon, thanks, I'm going to split into two PRs.

**Comment by loicpoulain** [comment]
@jukkar , @tbursztyka, Can I have your review on this PR.

**Review by tbursztyka — APPROVED** [review]
looks fine, but a recheck for CI seems necessary

**Comment by jukkar** [comment]
recheck

**Review by jukkar — APPROVED** [review]
LGTM

**Pull request merged**
