### PR TITLE
drivers: dma: Add infineon xmc4xxx dma support and async uart

### PR DESCRIPTION
**Pull request by talih0**
Adds dma drivers and async uart for xmc4xxx SoCs.

### CODE REVIEW

**Comment by talih0** [comment]
Results of tests/drivers/uart/uart_async_api/

image

**Comment by talih0** [comment]
rebased to see if CI is fixed on main

**Comment by talih0** [comment]
ping

**Review by dcpleung — DISMISSED** [review]
LGTM on UART.

**Comment by talih0** [comment]
I updated the uart driver to handle interleaving async and polling api. 
This case isn't covered in uart_async_api test (It is covered in uart_mix_fifo_poll test, but this needs counter drivers which is not implemented for xmc yet).

I also updated how dma errors are handled. I noticed that most existing async driver implementations ignore dma errors. The same approach is now used in this PR (instead of aborting async transmit/receive after an error).

**Review by teburd — DISMISSED** [review]
dma lgtm

**Review by dcpleung — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@talih0 can you rebase please?

**Comment by talih0** [comment]
> @talih0 can you rebase please?

Yes sure, just rebased to fix the merge conflicts.

**Review by dcpleung — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Pull request merged**
