### PR TITLE
drivers: flash: spi_nor: Remove page alignment requirement for read

### PR DESCRIPTION
**Pull request by rgundi**
For flash R/W, the start address need not be aligned on a page size.

Signed-off-by: Rajavardhan Gundi <rajavardhan.gundi@intel.com>

### CODE REVIEW

**Review by sathishkuttan — APPROVED** [review]
LGTM

**Review by SavinayDharmappa — APPROVED** [review]

**Comment by sathishkuttan** [comment]
@rgundi I just noticed that there is a similar restriction on read. Writes do not need to be aligned to a page either. As long as the sector is previously erased and a location is not subsequently written to, it would be possible to write to that location. It would be better to remove the limitation on write as well and return error if the location is not previously erase.

**Comment by rgundi** [comment]
> @rgundi I just noticed that there is a similar restriction on write. Writes do not need to be aligned to a page either. As long as the sector is previously erased and a location is not subsequently written to, it would be possible to write to that location. It would be better to remove the limitation on write as well and return error if the location is not previously erase.

I too had noticed this but i wasn't sure if this was needed. In fact, there's even a parameter called write_block_size in flash_driver_api. I also noticed that not all flash drivers have tinkered around with this parameter. So, i believe it's ok to remove this restriction as well. However, i am not sure there's an efficient way to know if the location was previously erased. At least, none of the current drivers have this built-in.

**Comment by rgundi** [comment]
I also pushed another commit which removes the unused block_size parameter.

**Pull request merged**
