### PR TITLE
boards: thingy53_nrf5340: Remove CS configuration in board.c

### PR DESCRIPTION
**Pull request by volodymyr-bondarchuk**
CSs now are configured properly according to DTS description during SPI driver initialization.
Earlier, additional configuration was required due to a problem, fixed in f7466d2.

Signed-off-by: Volodymyr Bondarchuk <volodymyr.bondarchuk@nordicsemi.no>

### CODE REVIEW

**Comment by volodymyr-bondarchuk** [comment]
Hi @anangl
Could you review?

**Review by gmarull — CHANGES_REQUESTED** [review]
please delete dead code as well,

```c
#define ADXL362_NODE			DT_NODELABEL(adxl362)
#define ADXL362_GPIO_NODE		DT_SPI_DEV_CS_GPIOS_CTLR(ADXL362_NODE)
#define ADXL362_CS			DT_SPI_DEV_CS_GPIOS_PIN(ADXL362_NODE)
#define ADXL362_FLAGS			DT_SPI_DEV_CS_GPIOS_FLAGS(ADXL362_NODE)
```

**Comment by volodymyr-bondarchuk** [comment]
@gmarull , thanks. Dead code and unused includes are removed.

**Review by anangl — DISMISSED** [review]

**Comment by volodymyr-bondarchuk** [comment]
Last commit fixes commit message only for compliance checks,.

**Comment by volodymyr-bondarchuk** [comment]
Hi, sorry everyone.
I miss-clicked and did wrong push. I closed this PR. I will fix my branch and redo PR.

**Pull request closed without merging**
