### PR TITLE
drivers: adc: Add support for the ESP32 board

### PR DESCRIPTION
**Pull request by wolterhv**
This is the draft PR for the work on implementing an ADC driver for the ESP32. The related issue is #44908.

### CODE REVIEW

**Comment by wolterhv** [comment]
As a WIP, this implementation is not yet final in several aspects, including the calls to espressif library functions. In the final state, HAL calls will be favoured. The current objective is getting the driver to a functional state ASAP.

**Comment by sam131208** [comment]
It looks like it has stopped updating, will anyone continue to maintain it?

**Comment by sylvioalves** [comment]
There is still some pending changes in `hal` repository, which is ongoing.

**Comment by sam131208** [comment]
@sylvioalves   
  i add the adc to driver, and compile, get the error "fatal error: esp_adc_cal.h: No such file or directory "
  How can we add this file  to the include path.

**Comment by ashegheparyshun** [comment]
Hello everyone.
I' designing a PCB based on ESP32 for a project. As a part of the project I have to report battery level every 2 minutes. According to basic implementation of ADC which is already done (or going to) which pin number shall I use?

**Comment by wolterhv** [comment]
For reference, the implementation of this was taken over by @marekmatej and has now been merged in PR https://github.com/zephyrproject-rtos/zephyr/pull/52751

**Pull request closed without merging**
