### PR TITLE
samples: bluetooth: reduce RAM for hci_ipc df ll_sw_split

### PR DESCRIPTION
**Pull request by sean-madigan**
After stack size increase for IPC RAM now needs to be reduced in other areas.

Presumably the event buffer can be decreased by 1.

### CODE REVIEW

**Comment by sean-madigan** [comment]
IPC increase in question here https://github.com/zephyrproject-rtos/zephyr/pull/79557

**Review by cvinayak — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]
Presumably :sweat_smile:

**Review by Thalley — APPROVED** [review]

**Review by cvinayak — CHANGES_REQUESTED** [review]
@sean-madigan Do we need this any longer... upstream CI has not been failing to build... i guess the PR that needs more RAM upstream can do this change when need of RAM, right?

**Comment by sean-madigan** [comment]
Not required any more, IPC stack increase was reduced

**Pull request closed without merging**
