### PR TITLE
arm: kernel: don't do supervisor call in exception handler

### PR DESCRIPTION
**Pull request by chunlinhan**
Since the priority of svc exception is equal to other exceptions
(except systick and pendsv) in zephyr, do supervisor call in
exception handler will cause hardfault due to priority escalation.
Check if we're in exception handler in __swap. If we're in exception
handler, don't do supervisor call directly, but just unlock interrupts
and set pendsv bit in icsr instead.

Signed-off-by: Chunlin Han <chunlin.han@linaro.org>

### CODE REVIEW

**Comment by cvinayak** [comment]
Please give details to reproduce the issue (without this fix) in the commit message.

Caller of _swap (kernel API) would be using _is_in_isr(), maybe the root cause needs a fix. I am just interested in cause and symptom here.

**Comment by carlescufi** [comment]
@skordal, @ioannisg FYI

**Comment by chunlinhan** [comment]
@cvinayak 
You could replace tests/kernel/fatal/src/main.c with the following code.
Build & run it on frdm_k64f. You will see frdm_k64f keeps rebooting.
I found this issue when I tried PR #5197.

```
#include <zephyr.h>
#include <ztest.h>
#include <tc_util.h>
#include <kernel_structs.h>

#define STACKSIZE 2048
#define PRIORITY 5

static K_THREAD_STACK_DEFINE(alt_stack, STACKSIZE);
static struct k_thread alt_thread;
static volatile unsigned int expected_reason;

#ifndef CONFIG_ARM
FUNC_NORETURN
#endif
void _SysFatalErrorHandler(unsigned int reason, const NANO_ESF *pEsf)
{
    TC_PRINT("Caught system error -- reason %d\n", reason);

    if (reason == expected_reason) {
        ztest_test_pass();
    } else {
        ztest_test_fail();
    }

    k_thread_abort(_current);
#ifndef CONFIG_ARM
    CODE_UNREACHABLE;
#endif
}

void alt_thread1(void)
{
    // make it fault on purpose
    *(uint32_t *)0x0 = 0;
}

void testing_fatal(void)
{
    expected_reason = 0;
    k_thread_create(&alt_thread, alt_stack,
            K_THREAD_STACK_SIZEOF(alt_stack),
            (k_thread_entry_t)alt_thread1,
            NULL, NULL, NULL, PRIORITY, 0,
            K_NO_WAIT);

    k_sleep(1);
}

void test_main(void)
{
    ztest_test_suite(test_fatal, ztest_unit_test(testing_fatal));
    ztest_run_test_suite(test_fatal);
}
```

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by cvinayak** [comment]
@chunlinhan and @andrewboie, k_thread_create is not allowed from ISRs, k_thread_abort has no such checks, is this on purpose? Yes, k_thread_abort shall be allowed, but it shall not take the _Swap path if in ISRs.

Adding code to _Swap will only degrade Zephyr OS performance with unlikely tests in it.

**Comment by agross-linaro** [comment]
This is just an example.  The key point is that users/clients can create custom fatal handlers and these handlers could invoke a swap somehow while in exception mode.  If that occurs you'll get the hard fault.

I suppose you are right on the k_thread_abort.  Are you proposing we have a set pendsv inline function that does the setting of the pendv and do the checks for being in a exception handler in the k_thread_abort?  Do we have to do this with any other kernel API that could be called from a user defined handlers?

**Comment by chunlinhan** [comment]
@cvinayak , as @agross-linaro mentioned, the point is users might create its own fatal
handler and would call kernel APIs that would invoke _Swap() in their own fatal handler.
And yse, we could add the checks in the kernel APIs that would invoke _Swap(), but it just
moves the overhaeds from _Swap() to other kernel APIs. Furthermore, setting pendsv bit is
arch specific code, adding this into kernel APIs is not suitable. That's why I add the check
in _Swap() finally.

**Comment by cvinayak** [comment]
first, sorry for late responses.

> Are you proposing we have a set pendsv inline function that does the setting of the pendv and do the checks for being in a exception handler in the k_thread_abort? Do we have to do this with any other kernel API that could be called from a user defined handlers?
@agross-linaro, Yes. Most kernel API check for ISR/exception callability, hence a developer does perform a kernel call that is not allowed in ISR, expecting a hardfault is ok. Other way, if a kernel API is callable in ISR, then it perform tasks acceptable in a caller context, and switch to privileged/exception mode (using pendsv) to perform the rest.

Another topic, correct, if we discard using of svc #0, is there any other place svc is used by kernel?

**Comment by galak** [comment]
Can you rebase this to resolve merge conflicts.

**Comment by agross-linaro** [comment]
@cvinayak 
The svc is used for triggering a swap, offloading, and system calls (userspace stuff).  The reason svc was used for swapping was because the actual swapping is being done by the pendsv handler.  Because the pendsv handler is handled at the tail end of IRQs, this was a way to make sure only one swap was done even if there were multiple sources of a swap request (irq or otherwise).  That's my take on it.

The downside to changing everyone to toggling the pendsv directly is that we'd have a heck of a time making sure the behavior is the same.

Not sure where you are going with the IRQ priorities.   Can you elaborate?

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
So I think we need to think about this some more, especially since in a related patch we are changing k_is_in_isr() to return true for any exception which doesn't actually work.

For starters: please look at the vanilla _SysFatalErrorHandler() in arch/arm/core/sys_fatal_error_handler.c. It does a k_is_in_isr() check to determine whether we need to hang the system or just abort the current thread. _SysFatalErrorHandler() always runs in the context of a CPU exception, and if you change ARM's implementation to return true for any IRQ/exception this is not gonna work right, the system will always hang.

The semantics if k_is_in_isr() in this case is really "was the system handling an interrupt when the fatal CPU exception happened?".

On other arches (x86, Nios II, Xtensa, RiscV32) the common IRQ entry/exit code (not exceptions) increments/decrements a kernel.nested field and the implementation of k_is_in_isr() just returns that.

ARM is different animal. It is instead checking _IpsrGet() to fetch the currently executing vector AND also check the nested exception bit. If I understand what @agross-linaro has been telling me, this works poorly with system calls which run in context of SVC.

The vanilla handler, if it decides we are not in thread context also calls k_thread_abort(). This is an API that is legal to call from an exception. since _SysFatalErrorHandler() is running in supervisor mode (it's an exception) it should not be triggering another SVC exception, I'm not completely sure I grok why Chunlin is seeing what he is seeing.

I tried pulling Chunlin's sample code and it worked just fine in qemu_cortex_m3. Maybe this is an emulation bug, I don't know.

My post here is somewhat rambling I'm going to contemplate this some more. But I would prefer that this and the proposed ARM k_is_in_isr() change not go in for now for the time being.

**Comment by andrewboie** [comment]
Also to follow-up:
For the complexities of the k_is_in_isr() case, a workable and simple solution for ARM would be to not look at IPSR and instead increment/decrement kernel.nested in the IRQ (not exception) enter/exit code similar to how x86, Nios II, Xtensa, and RiscV32 do it.

**Comment by chunlinhan** [comment]
qemu v2.6.0 does not handle priority escalation well and my sample code crashes on my qemu v2.10.0.

Even modifying the k_is_in_isr() of ARM as x86 (inc/dec kernel.nested in IRQ), my sample code will still crash. (But I think modifying the k_is_in_isr() of ARM as x86 is worthwhile.)

The fault path of my sample code is as below:

alt_thread1() tries to write readonly address ->
usage fault ->
_SysFatalErrorHandler() ->
ztest_test_pass() ->
k_sem_give() ->
do_sem_give() (k_is_in_isr() returns false and _must_switch_threads() returns true) ->
svc #0 @ _Swap() ->
hard fault (due to priority escalation) ->
_SysFatalErrorHandler() ->
ztest_test_pass() ->
k_sem_give() ->
do_sem_give() (no thread to be unpended) ->
k_thread_abort() ->
_reschedule_threads() ->
svc #0 @ _Swap() ->
(enter lockup state due to we do svc in hard fault)

We can see the k_is_in_isr() in do_sem_give() will still return false, because we are in exception, the kernel.nested is 0.  _Swap() will be called and causes hard fault.

**Comment by andrewboie** [comment]
I believe @agross-linaro came up with some changes to __swap which should make this obsolete, can you guys confirm?

**Pull request closed without merging**
