### PR TITLE
scripts: mpu align for ro section of new memory region on non-XIP system

### PR DESCRIPTION
**Pull request by wentongwu**
on non-XIP system, loading address shouldn't be located on FLASH memory region.

on non-XIP system, SRAM is the default region, and relocated .data
section and .bss section of SRAM shouldn't be inserted between
_image_rom_start and _image_rom_end, because the memory region between
_image_rom_start and _image_rom_end will construct the mpu ro region.
Also for the newly added memory region on non-XIP system, the
relocated .text secition and .rodata section should also be mpu aligned.

### CODE REVIEW

**Comment by ioannisg** [comment]
Is this an ARM-only issue @wentongwu ?

**Comment by wentongwu** [comment]
> Is this an ARM-only issue @wentongwu ?

So far code relocation is enabled only on ARM platform.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by ioannisg** [comment]
@SebastianBoe @galak could you pls take a look

**Comment by SebastianBoe** [comment]
I will not have time unfortunately.

**Review by nashif — APPROVED** [review]

**Pull request merged**
