### PR TITLE
api: gpio: deprecate all gpio_port_ functions

### PR DESCRIPTION
**Pull request by mnkp**
Since 1.14 is going to be LTS release I propose to deprecate all gpio_port_ functions not to have to support them in the future. We have been planning to rework them for a long time. Sorry for a late PR.

The gpio_port_ functions provided by the gpio API do not provide currently a mask parameter. As such they operate on a full port only. In practice such functions are not useful. This commit deprecates them
to allow adding port functions with support for a mask parameter in the future.

### CODE REVIEW

**Comment by galak** [comment]
Please look at converting the in-tree users of these APIs to use the per pin APIs.

**Review by pabigot — DISMISSED** [review]
In the dev-review meeting today we were told that API shouldn't be deprecated unless there's a replacement ready to go.  While I approve in general of getting rid of the current port configuration and write/read operations, #10741 is not queued for 1.14 and I don't really like its approach, in part because it's a poor fit for configuring all GPIOs through a static configuration at startup, which is possibly its most common use case.

**Comment by mnkp** [comment]
> In the dev-review meeting today we were told that API shouldn't be deprecated unless there's a replacement ready to go.

In general that's a good rule. However the gpio_port_ functions in their current state are pretty much useless so there is nothing to replace really. If we get stuck with them for the whole 1.14 support period it's going to further hinder the long postponed GPIO API update. Sure, it should have been done earlier.

**Review by vanwinkeljan — APPROVED** [review]
MB display part looks good

**Comment by galak** [comment]
> In general that's a good rule. However the gpio_port_ functions in their current state are pretty much useless so there is nothing to replace really. If we get stuck with them for the whole 1.14 support period it's going to further hinder the long postponed GPIO API update. Sure, it should have been done earlier.

By replacement, I think that means any in tree users of the API.  We don't necessarily need a new API, but if we intend to deprecate and remove an API, in tree users need to be moved away from it.  (which in some cases may mean introduction of a new API).

**Comment by mnkp** [comment]
@galak all in tree uses of gpio_port_ functions are now removed. I've found only two places.

**Comment by pabigot** [comment]
> By replacement, I think that means any in tree users of the API. We don't necessarily need a new API, but if we intend to deprecate and remove an API, in tree users need to be moved away from it. (which in some cases may mean introduction of a new API).

OK, that's a good clarification.  Are these policies documented anywhere?  I don't see a deprecation policy in the documentation.

The issue in the dev-review telecon was `i2c_transfer()`, which while overly complex also cannot be made to work correctly on some platforms without significant effort (bypassing vendor HAL drivers).  There are two uses in `samples` for which we can't provide a workable replacement before the hard freeze deadline.  The conclusion during discussion was that we can't deprecate it for 1.14, even though we know it's not just useless, it's functionally wrong.

If Zephyr is expected to be the go-to solution for cross-platform embedded applications, at some point it'll have to start documenting and following a process for deprecating existing behavior, recognizing that not all uses are going to be in-tree, and not granting exceptions based on convenience.

**Comment by nashif** [comment]
> OK, that's a good clarification. Are these policies documented anywhere? I don't see a deprecation policy in the documentation.

how is this different from what we discussed today in the dev-review meeting?

> If Zephyr is expected to be the go-to solution for cross-platform embedded applications, at some point it'll have to start documenting and following a process for deprecating existing behavior, recognizing that not all uses are going to be in-tree, and not granting exceptions based on convenience.

agree on that, it is not documented in the official documents, but was agreed and documented in a previous TSC meeting and should be in the minutes somewhere. We need to put this in the documents which I am moving to rst/ these days.

**Review by galak — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by Mierunski — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
