### PR TITLE
lib: fnmatch: Fix line endings

### PR DESCRIPTION
**Pull request by carlescufi**
Line endings in fnmatch.[c,h] were committed with both the CR and LF
terminators. Remove the spurious CRs for consistency with the tree. On
Windows users should let Git itself deal with line endings.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Review by pdunaj — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by carlescufi** [comment]
@nashif compliance fails because of coding style. But this is an external file, I do not think we should enforce our coding style, especially anything beyond tabs/spaces.

**Comment by nashif** [comment]
> @nashif compliance fails because of coding style. But this is an external file, I do not think we should enforce our coding style, especially anything beyond tabs/spaces.

this is now part of Zephyr, IMO it should be fixed

**Comment by carlescufi** [comment]
> > @nashif compliance fails because of coding style. But this is an external file, I do not think we should enforce our coding style, especially anything beyond tabs/spaces.
> 
> this is now part of Zephyr, IMO it should be fixed

This will make it hard then to update in the future, are we sure?

**Comment by nashif** [comment]
> This will make it hard then to update in the future, are we sure?

I think yes, this is now zephyr code, I doubt something like will ever be updated or synced with upstream. Anytime anyone makes any changes to this file for whatever reason will be faced with the same style issues, so lets fix it and forget about it.

**Comment by galak** [comment]
@carlescufi looks like this needs rebase since we moved the files.

**Pull request closed without merging**
