### PR TITLE
doc: boards: Migrate -many- boards to new zephyr:board directive/role

### PR DESCRIPTION
**Pull request by kartben**
Examples of the PR applied to some boards:
- ST board example: https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/st/nucleo_c031c6/doc/index.html
- Espressif board example: https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/espressif/esp32_ethernet_kit/doc/index.html
- ADI board example: https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/adi/max32666evkit/doc/index.html
- NXP board example: https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/nxp/frdm_k64f/doc/index.html
- Infineon board example: https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/infineon/cy8ckit_062s4/doc/index.html

image

Kind of a big PR, but it's split in commits per vendor -- as some of the documentation pages (ex. samples) that now reference boards using the new `:zephyr:board:` directive sometimes mention multiple boards on the same line, this would lead to many conflicts based on the order in which PR are merged if I am to split the changes in multiple PRs.

There are still quite a few boards/vendors to migrate over but thought I would get the ball rolling :)

Some of the documentation pages that haven't been migrated yet are typically:
- documentation pages that correspond to multiple boards, as the `.. zephyr:board::` directive is designed for only one board per doc page at the moment (ex. https://docs.zephyrproject.org/latest/boards/intel/adl/doc/index.html which targets both `intel_adl_crb` and `intel_adl_rvp`)
- boards that have multiple SoCs and for which original author split the docs in multiple pages. (ex. https://docs.zephyrproject.org/latest/boards/arm/fvp_baser_aemv8r/doc/aarch32.html and https://docs.zephyrproject.org/latest/boards/arm/fvp_baser_aemv8r/doc/aarch64.html)
- boards with doc page that is incorrectly structured in the first place (ex., multiple titles, such as https://docs.zephyrproject.org/latest/boards/sparkfun/micromod/doc/index.html)

When it comes to deciding whether the main image in a board documentation page should be removed to only appear in the new "card", the thought process has been that whenever the image really only was there for illustration purposes, it's been removed (ex. https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/m5stack/m5stack_atoms3/doc/index.html) but when it is part of a narrative where being able to see the image right next to the text mentioning it, it's been preserved (but also appears in the card); ex. https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/particle/nrf51_blenano/doc/index.html#connections-and-ios

### CODE REVIEW

**Review by erwango — DISMISSED** [review]
ok for st boards

**Review by ifyall — DISMISSED** [review]

**Comment by kartben** [comment]
- Rebased to solve conflicts
- Updated the beagleboard commit to ensure the new BeagleBone AI-64 was covered

**Comment by nandojve** [comment]
Hi @kartben ,

No image from Atmel / GD should be removed. They are images from the development kit and should be kept.

**Comment by kartben** [comment]
> Hi @kartben ,
> 
> No image from Atmel / GD should be removed. They are images from the development kit and should be kept.

Can you elaborate? The images are still there, only they're showing in the "side card" now. 
https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/gd/gd32a503v_eval/doc/index.html

**Comment by nandojve** [comment]
> > Hi @kartben ,
> > No image from Atmel / GD should be removed. They are images from the development kit and should be kept.
> 
> @nandojve Can you elaborate? The images are still there, only they're showing in the "side card" now. https://builds.zephyrproject.io/zephyr/pr/80048/docs/boards/gd/gd32a503v_eval/doc/index.html

I understood now. The below don't affect the the outcome.

```diff
-.. image:: img/gd32a503v_eval.jpg
-     :align: center
-     :alt: gd32a503v_eval
```

Sorry about the noise.

**Review by nandojve — APPROVED** [review]

**Comment by kartben** [comment]
> Sorry about the noise.

That's no problem at all, really! I understand how the change can be confusing at first sight so no worries :)
For others wondering the same, this is something I have tried to explain in the initial comment in this PR ("When it comes to deciding whether the main image in a board documentation page [...]).

**Review by pdgendt — APPROVED** [review]
Nice work!

**Pull request merged**
