### PR TITLE
tests: drivers: sensor: temp_sensor: Add configs for rpi_pico die_temp

### PR DESCRIPTION
**Pull request by soburi**
Adds test configs for RaspberryPi Pico's die temp sensor.

### CODE REVIEW

**Review by MaureenHelm — COMMENTED** [review]
Any reason not to put this in the board dts?

**Comment by soburi** [comment]
@MaureenHelm 

> Any reason not to put this in the board dts?

The `temp_sensor label` is used only in one place, boards/tdk/robokit1/robokit1-common.dtsi, and is not commonly used. Therefore, it is not reasonable to modify it on the board side, and dealing with it in the test overlay is appropriate.

**Comment by soburi** [comment]
@MaureenHelm 
Could you revisit this PR?

**Review by ubieda — CHANGES_REQUESTED** [review]
> > Any reason not to put this in the board dts?
> 
> The `temp_sensor label` is used only in one place, boards/tdk/robokit1/robokit1-common.dtsi, and is not commonly used. Therefore, it is not reasonable to modify it on the board side, and dealing with it in the test overlay is appropriate.

It'll work either way but I think we'll want to stay away from cluttering samples/tests with overlays if we can avoid it.

In this case: `temp_sensor` is a generic node-label that could be used in places other than this test. See `samples/sensor/thermometer`, as a reference.

**Pull request closed without merging**
