### PR TITLE
ARC: boards: HSDK: get rid of pinmux usage

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
Pinmux is deprecated (see https://github.com/zephyrproject-rtos/zephyr/issues/39740) so let's get rid of it's usage for HSDK board.

As we call pinmux only once at init phase we simply do register setup in platform code instead of pinctrl.

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]
Where is the pinctrl driver?

**Comment by evgeniy-paltsev** [comment]
Hi @gmarull 

> Where is the pinctrl driver?

We don't need it - we used to use pinmux driver just to unconditionally set one SoC-specific register once during boot. But it's excessive to use pinmux / pinctrl for that. So we simply set this register from platform code and drop old pinmux driver.

**Comment by gmarull** [comment]
> Hi @gmarull
> 
> > Where is the pinctrl driver?
> 
> We don't need it - we used to use pinmux driver just to unconditionally set one SoC-specific register once during boot. But it's excessive to use pinmux / pinctrl for that. So we simply set this register from platform code and drop old pinmux driver.

To my understanding current pinmux driver allows to set alt funcs, it's not "one Soc-specific register",

https://github.com/zephyrproject-rtos/zephyr/blob/dfc4c3f8a6aa466548ac13f6bc0384936846b7a2/drivers/pinmux/pinmux_hsdk.c#L21-L34

https://github.com/zephyrproject-rtos/zephyr/blob/dfc4c3f8a6aa466548ac13f6bc0384936846b7a2/boards/arc/hsdk/pinmux.c#L19-L30

This functionality is now removed. Note that it is not acceptable anymore to do this sort of configuration at board level using custom C code.

**Comment by ruuddw** [comment]
The more advanced pinmux functionality isn't required/used by 'normal' applications, so this was the simpler solution. Evgeniy, maybe create an enhancement issue to add pinmux functionality for HSDK in the future using the new pinmux solution?

**Review by ruuddw — DISMISSED** [review]

**Comment by gmarull** [comment]
> The more advanced pinmux functionality isn't required/used by 'normal' applications,

what are 'normal' applications?

Does that mean boards using this SoC are always forced to route signals to the same set of pins?

**Review by abrodkin — DISMISSED** [review]

**Comment by evgeniy-paltsev** [comment]
Rebase to fix conflicts. @abrodkin  @ruuddw  - please approve again.

**Comment by evgeniy-paltsev** [comment]
> Does that mean boards using this SoC are always forced to route signals to the same set of pins?

Currently we don't support other configurations, so yes.

**Review by ruuddw — DISMISSED** [review]

**Review by abrodkin — DISMISSED** [review]

**Comment by evgeniy-paltsev** [comment]
Rebase to fix merge conflicts. @abrodkin @ruuddw - please approve again.

**Review by ruuddw — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]

**Comment by evgeniy-paltsev** [comment]
If there is no disagreement anymore, let's merge this.

**Review by henrikbrixandersen — APPROVED** [review]
I think this is acceptable for now, but a proper pinctrl driver should be added going forward. Please open a enhancement request issue for this when merged.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
