### PR TITLE
Drivers: Sensor: Bosch Bmp390 merge into bmp388 driver

### PR DESCRIPTION
**Pull request by ruehlchris**
Bmp390 is a drop-in replacement for the Bmp388 with same registers and features but different
chip-id.
- bmp388 = 0x50
- bmp390 = 0x60

This patches add support for compatible="bosch,bmp390" to the bmp388 driver and replace the fix check against a define with check against the device->data->chip-id. This implemented with minimal code changes.

Additionally:
- Replace a manual bit-shift operation with safe sys_get_le24().
- Use cast for int16_t struct members when read the calibration data from the chip.

Please review. Thanks.

### CODE REVIEW

**Review by faxe1008 — COMMENTED** [review]
From other in tree sensors a driver for multiple sensor of the same series is usually done by having one compatible "bmp3xx". You can peek at this sensor for example:
https://github.com/zephyrproject-rtos/zephyr/blob/40414f72e9fcec733b0ad4d046c3c042a579bb94/drivers/sensor/maxim/ds18b20/ds18b20.c#L367

Regarding the commits generally:

Most of the maintainers do not want pure formatting commits as it creates noise in the files history. If you need to change one line and can make its formatting more consistent, great. Otherwise most of the time do not bother with the formatting.

**Comment by ruehlchris** [comment]
> From other in tree sensors a driver for multiple sensor of the same series is usually done by having one compatible "bmp3xx". You can peek at this sensor for example:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/40414f72e9fcec733b0ad4d046c3c042a579bb94/drivers/sensor/maxim/ds18b20/ds18b20.c#L367
> 
> Regarding the commits generally:
> 
> Most of the maintainers do not want pure formatting commits as it creates noise in the files history. If you need to change one line and can make its formatting more consistent, great. Otherwise most of the time do not bother with the formatting.

I see, - ok noted with the formatting. I will drop this patch.
and I understand the solution you pointed out. Give me a little time to change it. 
@faxe1008 you recommend to change this Pull-request to a draft until I think be ready?

**Comment by faxe1008** [comment]
Since you did not open it as a draf, assignees are already there and will be getting notifcations I think. You can to make the process more transparent but does not change anything really.

**Comment by ruehlchris** [comment]
sorry guys, something goes wrong. I pulled my main and updated my branch. only 4 files had been changed.
Let me fix this , sorry for the noise.

**Pull request closed without merging**
