### PR TITLE
net: l2: Move individual L2 to dedicated directories

### PR DESCRIPTION
**Pull request by jukkar**
No need to keep technologies in main L2 directory so create
a directory for each of them.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by tbursztyka — COMMENTED** [review]
if there is one file that does not need its own directory that's the dummy l2 (it's a no true bearer afterall). It's never going to more that a bunch of lines in one file.

**Review by pfalcon — APPROVED** [review]
The commit message should have said that for consistency, move BT/WiFi L2 to own dirs, like ethernet, etc. already are.

Needs rebase.

**Comment by nashif** [comment]
rebase

**Comment by jukkar** [comment]
Resolve merge conflict

**Review by nashif — APPROVED** [review]

**Pull request merged**
