### PR TITLE
hostap: fix build error when disable enterprise mode

### PR DESCRIPTION
**Pull request by MaochenWang1**
In Kconfig, already check both dpp and enterprise mode for enable NO_CONFIG_BLOBS, so remove the wrong one in the cmakelist.

### CODE REVIEW

**Review by krish2718 — DISMISSED** [review]
How come no tests caught this? https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/net/wifi/configs/testcase.yaml

**Comment by MaochenWang1** [comment]
> How come no tests caught this? https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/net/wifi/configs/testcase.yaml

Maybe DPP is not enabled when you disable the enterprise?

**Review by jukkar — DISMISSED** [review]

**Comment by jukkar** [comment]
> How come no tests caught this? [](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/net/wifi/configs/testcase.yaml)

That is a good question, I wonder if we need to add more test scenarios to the wifi config tests?

@MaochenWang1 would it be possible to add tests that could catch the issue to this PR?

**Comment by MaochenWang1** [comment]
> > How come no tests caught this?
> 
> That is a good question, I wonder if we need to add more test scenarios to the wifi config tests?
> 
> @MaochenWang1 would it be possible to add tests that could catch the issue to this PR?

Hi @jukkar  @krish2718  can you help review again, I change the tests.

**Review by krish2718 — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
