### PR TITLE
Fix listening socket checks

### PR DESCRIPTION
**Pull request by jukkar**

### CODE REVIEW

**Comment by pfalcon** [comment]
>The listening state cannot be used to determine whether the
socket is a listening one because the state is set to listening
only when accept() is called. Because of this, create a new flag
that is set when app calls listen().

No, that's not correct. A socket is listening when listen() was called on it. accept() just retrieves next connection from connection queue, or waits for it, if it's empty.

You went to far with a workaround for apparently unrelated issue (https://github.com/zephyrproject-rtos/zephyr/pull/18965), which was merged despite having -1, and now you cascade even more makes-no-sense workarounds thru the IP stack. Please stop, get back to the original issue, and let's investigate and fix it properly. (If makes sense, with https://github.com/zephyrproject-rtos/zephyr/pull/11443 on the plate. And if not, just reverting https://github.com/zephyrproject-rtos/zephyr/pull/18965 should be good enough.)

**Comment by jukkar** [comment]
> No, that's not correct. A socket is listening when listen() was called on it. accept() just retrieves next connection from connection queue, or waits for it, if it's empty.

We do not have queueing support for incoming SYNs, perhaps we get that for the TCP2. All this is done because of that limitation. We can certainly remove the related stuff after the queueing is implemented.
These fixes are really needed in order to avoid crashes when application calls listen() but does not call accept().

**Comment by jukkar** [comment]
> You went to far with a workaround for apparently unrelated issue (#18965), which was merged despite having -1, and now you cascade even more makes-no-sense workarounds thru the IP stack. Please stop, get back to the original issue, and let's investigate and fix it properly. (If makes sense, with #11443 on the plate. And if not, just reverting #18965 should be good enough.)

You need to calm down with these accusations. We definitely cannot revert #18965 there was good reasons for that, you probably missed the point why that PR was done.

**Comment by pfalcon** [comment]
> You need to calm down with these accusations.

These are not accusations, but constatation of facts (at least, these are facts for me, but that's definitely still my opinion. I'm sorry, but I would consider it irresponsible and unprofessional, having such reservation, to withheld them in review, leaving another chance for deeper investigation of the problem.

> These fixes are really needed

Your call, I don't even try to -1 these and complicate your task, given that we're along that path already.

> We do not have queueing support for incoming SYNs

We definitely have something along those lines, see e.g. https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_NET_TCP_BACKLOG_SIZE.html . Apparently, it doesn't work as expected, and instead of fixing it, we put workaround like that. And let me point to the commit which introduced workaround, https://github.com/zephyrproject-rtos/zephyr/commit/1a6f4a6368960ddcbeb776f45f084163c7001f36 , its essence is an these words:

>  4) After the connection A is closed, the connection B
    gets accepted by application but now the closed
    connection A will cause confusion in the net-stack

"Confusion in the next-stack". That's all we know. Which confusion, why don't we fix the confusion instead of introducing workarounds like that - there're no answer to those questions.

**Comment by jukkar** [comment]
Replaced by #19919

**Pull request closed without merging**
