### PR TITLE
stm32: pinmux: spi: Opt for lower power consumption

### LINKED ISSUE #16739: spi: stm32: pinmux: default configuration does not opt for low power consumption
**Is your enhancement proposal related to a problem? Please describe.**
The SPI MOSI/MISO are configured as PP NOPULL from the pinmux. The use case is when having a SPI peripheral. Putting the board in STOP2 mode with the current configuration, the consumption is approximately 20uA (per pin) more than having those pins set as PP PULL{UP, DOWN}.

**Describe the solution you'd like**
I would like to have these pins configured as PP PULL{UP, DOWN} from the pinmux driver.

**Describe alternatives you've considered**
Set these pins as PULL{UP, DOWN} after Zephyr initialization from the application.

**Additional context**
Tested on a custom board with a STM32L496RE and on Nucleo L496ZG.

If you think that's OK, I can open a PR to fix this.

### PR DESCRIPTION
**Pull request by gon1332**
Fixes #16739. Changed the STM32's SPI MISO/MOSI configurations in order
to reduce the power consumption by approximately 20uA per pin.

Signed-off-by: Ioannis Konstantelias <ikonstadel@gmail.com>

### CODE REVIEW

**Comment by gon1332** [comment]
@erwango FYI

**Comment by erwango** [comment]
^^@Benichou34 @jli157 @frantony @lowlander @KwonTae-young 

Adding STM32 users in review to get feedback on this choice

**Review by b0661 — APPROVED** [review]
LGTM

**Review by avisconti — COMMENTED** [review]
@gon1332 
Can you add in the commit message few lines to specify the reason why putting PD instead of NOPULL
is lowering the power consumption? Just a couple of lines.

EDIT::
The rest LGTM

**Review by Mani-Sadhasivam — APPROVED** [review]

**Comment by gon1332** [comment]
> @gon1332
> Can you add in the commit message few lines to specify the reason why putting PD instead of NOPULL
> is lowering the power consumption? Just a couple of lines.

Done.

The document I've based my comment is [AN4899 - STM32 GPIO configuration for hardware settings
and low-power consumption](https://www.st.com/content/ccc/resource/technical/document/application_note/group0/13/c0/f6/6c/29/3b/47/b3/DM00315319/files/DM00315319.pdf/jcr:content/translations/en.DM00315319.pdf).

**Review by avisconti — APPROVED** [review]
OK, the commit msg looks clear to me. Thx!

**Comment by loicpoulain** [comment]
@gon1332, from you commit I understand the change is only requested for MISO? do you see improvement on adding the pull-down on MOSI as well?

**Comment by gon1332** [comment]
> @gon1332, from your commit I understand the change is only requested for MISO? do you see improvement on adding the pull-down on MOSI as well?

Yes. It was tested on both and saw the described results.

**Comment by loicpoulain** [comment]
> > @gon1332, from your commit I understand the change is only requested for MISO? do you see improvement on adding the pull-down on MOSI as well?
> 
> Yes. It was tested on both.

Ok thanks, LGTM.

**Review by loicpoulain — APPROVED** [review]

**Comment by avisconti** [comment]
> @gon1332, from your commit I understand the change is only requested for MISO? do you see improvement on adding the pull-down on MOSI as well?

@loicpoulain 
I have done same observation, but I concluded that in any case would be better to keep it in MOSI  because the SPI can be configured as slave.

**Review by erwango — APPROVED** [review]

**Review by ydamigos — APPROVED** [review]

**Pull request merged**
