### PR TITLE
lib: fdtable: fix reference counting in z_reserve_fd()

### LINKED ISSUE #27721: Concurrent file descriptor allocations may return the same descriptor
**Describe the bug**
File descriptors are currently allocated in various parts of the code base via

```
z_reserve_fd()
..
z_finalize_fd()
```

Internally, z_finalize_fd() is calling z_fd_ref() to add to the reference count of the fd that is being allocated. This is too late because if another thread also tries to allocate an fd, z_reserve_fd() may return the same one thinking that it is free, when in fact it is about to be finalized.

**To Reproduce**
1. Add the attached file to samples/net/sockets/echo_server/boards/cc3220sf_launchxl.conf
[cc3220sf_launchxl.conf.txt](https://github.com/zephyrproject-rtos/zephyr/files/5111360/cc3220sf_launchxl.conf.txt)
2. cd samples/net/sockets/echo_server
3. west build -b cc3220sf_launchxl
4. west flash
5. See error when the tcp thread tries to call listen(), which fails because the tcp socket's corresponding file descriptor is the same as the udp socket's.

```
*** Booting Zephyr OS build zephyr-v2.3.0-2002-g560b8d9fe005  ***
[00:00:00.963,000] <inf> wifi_simplelink: [WLAN EVENT] STA Connected to the AP: ThingsNet, BSSID: 2c:30:33:51:53:33
[00:00:00.965,000] <inf> wifi_simplelink: [NETAPP EVENT] IP set to: IPv4=192.168.1.144, Gateway=192.168.1.1
[00:00:00.968,000] <dbg> wifi_simplelink.simplelink_iface_init: MAC Address 40:06:a0:97:62:cc
[00:00:00.978,000] <inf> net_echo_server_sample: Run echo server
[00:00:00.978,000] <inf> net_echo_server_sample: Starting...
[00:00:00.980,000] <inf> net_echo_server_sample: Waiting for UDP packets on port 4242 (IPv4)...
[00:00:00.981,000] <err> net_echo_server_sample: Failed to listen on TCP socket (IPv4): 95
```

**Expected behavior**
There should be no errors, and the sample should be successful in listening to both tcp and udp sockets.

**Impact**
Potential concurrency issues in applications that allocate file descriptors in multiple threads.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Ubuntu 18.04
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.11.3
 - Commit SHA or Version used: 560b8d9fe005e295dfa5bccc2bc42a47cd77e1da

### PR DESCRIPTION
**Pull request by vanti**
The new fd entry should be reserved by incrementing its reference count
in z_reserve_fd() instead of z_finalize_fd() in order to avoid having
the same one being returned in a concurrent call. If for some reason
the fd is not finalized after z_reserve_fd() is called, it can be
freed via z_free_fd(), which would decrement the reference count.

Fixes #27721

Signed-off-by: Vincent Wan <vwan@ti.com>

### CODE REVIEW

**Comment by jukkar** [comment]
> Hmm, looks like some of the scenarios in the fdtable suite are failing on qemu_x86 with this change:

The reason for this is that the test expects that refcount is 0 at this point, but this commit changes that.
So we would need to remove the line 60 `zassert_equal(errno, EBADF, "errno not set");` as that is no longer a valid assumption.

For the failure in line 152, it was actually expecting to share the fd in order to verify that the refcounting works from multiple threads. With this commit, that assumption is no longer valid and the test would need to be rewritten.

**Comment by vanti** [comment]
In tests/lib/fdtable, I removed assertion in test_z_get_fd_obj, and simplified test_z_fd_multiple_access to just allocate fd in first thread and free it in the second thread. Now all checks have passed.

**Review by jukkar — APPROVED** [review]
Thanks @vanti, LGTM

**Review by rlubos — APPROVED** [review]
LGTM, I've hit the issue as well and was about to open a PR when I found this 👍

**Pull request merged**
