### PR TITLE
Select HAS_DTS_SPI in designware driver

### PR DESCRIPTION
**Pull request by MaureenHelm**
Makes the designware spi driver consistent with other spi drivers by
selecting HAS_DTS_SPI in the driver. This required adding spi nodes and
dts fixups to several arc and x86 socs, as well as enabling those nodes
in associated boards.

Also refactors the driver to use the base address, interrupt number, and
interrupt priority from dts.

This is being done in preparation making sensor drivers depend on HAS_DTS_SPI (#10115)

### CODE REVIEW

**Review by nashif — APPROVED** [review]
thanks, +1 for the initiative ;-)

**Review by SavinayDharmappa — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
I think there are some defines in soc/x86/intel_quark/quark_se/soc.h  which we can remove.

**Comment by galak** [comment]
We should close out PR #7870 at some point.

**Review by galak — CHANGES_REQUESTED** [review]
Looks like a few other places we can remove defines:
soc/arc/snps_emsk/soc.h
soc/x86/intel_quark/quark_d2000/soc.h
soc/x86/intel_quark/quark_se/soc.h
soc/arc/quark_se_c1000_ss/soc.h

**Comment by MaureenHelm** [comment]
> Looks like a few other places we can remove defines

Done. Also rebased to fix a merge conflict from #10245

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Wonder if we should open an issue for cleaning up the last bits of SPI_DW_ defines in the soc code (stuff like the IRQ flags and IRQ register offsets).

**Pull request merged**
