### PR TITLE
issue #20654

### PR DESCRIPTION
**Pull request by Ankush1oo8**
Resolve issue #20654 and made a documentaion for flash simulator
if ihave made any mistakes please feel free to correct me

### CODE REVIEW

**Comment by nashif** [comment]
please use a more descpretive title

**Comment by Ankush1oo8** [comment]
Like how
What is Flash simulator?

**Comment by Ankush1oo8** [comment]
if possible can you edit

> please use a more descpretive title

Cann you help with that please
if posible can you change it

**Review by thedjnK — COMMENTED** [review]
Some questions:

- How much of this did you personally write yourself?
- How familiar are you with the flash simulator driver?
- How accurate is the text in the PR?

**Comment by kartben** [comment]
Hi @Ankush1oo8 

Thanks very much for the PR -- it is always nice to see people trying to help tackle some of the issues that have been open for a very long time. However, in this particular situation, I don't think just asking ChatGPT to document flash_simulator.c is getting us to the level of detail that is really helpful for someone to really learn about the capabilities of the simulator.

As a thought, you may want to consider writing a new code sample that exercises `zephyr,sim-flash` and helps users understand some of the key features such as statistics collection, etc.

Would you be interested in doing that?

In any case you may want to have a look at our contribution guidelines and documentation writing guidelines (for example, the page you're proposing to add is not even "mounted" in the documentation's table of contents at the moment)

Thanks!

**Review by gmarull — CHANGES_REQUESTED** [review]
No AI garbage please.

**Comment by kartben** [comment]
@Ankush1oo8 so I take it that you are not interested in iterating on this and possibly contributing a code sample (or an improved doc page?)

**Comment by Ankush1oo8** [comment]
I want to contribute but i dont know how can i do that

**Comment by kartben** [comment]
> I want to contribute but i dont know how can i do that

I think I gave you some pointers/ideas above but let me know if you have specific questions

**Pull request closed without merging**
