### PR TITLE
sensors: lps2hh: Fix misspelled GPIOS_CONTROLLER references

### PR DESCRIPTION
**Pull request by ulfalizer**
DT_INST_0_ST_LPS22HH_CS_GPIO_CONTROLLER should be
DT_INST_0_ST_LPS22HH_CS_GPIOS_CONTROLLER, which is the name generated by
gen_defines.py.

Discovered while working on unrelated removing of special-casing for
clocks.

### CODE REVIEW

**Review by avisconti — CHANGES_REQUESTED** [review]
Good catch!!
The commit LGTM. Neverthelss I would kindly ask you if you could also enable LPS22HH in the tests part (i.e. sensors_i_z.conf and dts_fixup.h) for I2C/SPI so that he could be properly built. Unfortunately it seems there are no current platforms with LPS22HH sensor connected thru SPI, but at least we are ready.

**Comment by ulfalizer** [comment]
Enabled `CONFIG_LPS22HH` in `tests/drivers/build_all/sensors_i_z.conf`.

Not sure what to do in `tests/drivers/build_all/dts_fixup.h`. It already has the stuff below, and I2C and SPI can't be enabled at the same time.

```
#ifndef DT_INST_0_ST_LPS22HH_LABEL
#define DT_INST_0_ST_LPS22HH_LABEL ""
#define DT_INST_0_ST_LPS22HH_BUS_NAME ""
#define DT_INST_0_ST_LPS22HH_BASE_ADDRESS 0x19
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_PIN 0
#define DT_ST_LPS22HH_BUS_I2C 1
#endif
```

You could add commits to this PR if you want.

**Comment by avisconti** [comment]
> Enabled `CONFIG_LPS22HH` in `tests/drivers/build_all/sensors_i_z.conf`.
> 

Yes, but should be in alphabetical order.

> Not sure what to do in `tests/drivers/build_all/dts_fixup.h`. It already has the stuff below, and I2C and SPI can't be enabled at the same time.
> 
> ```c
> #ifndef DT_INST_0_ST_LPS22HH_LABEL
> #define DT_INST_0_ST_LPS22HH_LABEL ""
> #define DT_INST_0_ST_LPS22HH_BUS_NAME ""
> #define DT_INST_0_ST_LPS22HH_BASE_ADDRESS 0x19
> #define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_CONTROLLER ""
> #define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_FLAGS 0
> #define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_PIN 0
> #define DT_ST_LPS22HH_BUS_I2C 1
> #endif
> ```
> 
> You could add commits to this PR if you want.

Sure, I will push a commit for this part. Let's see if it works fine.

**Comment by avisconti** [comment]
> > Enabled `CONFIG_LPS22HH` in `tests/drivers/build_all/sensors_i_z.conf`.
> 
> Yes, but should be in alphabetical order.

It is already, sorry!
I will just add the dts_fixup part

**Comment by avisconti** [comment]
@ulfalizer 
I added a couple of commits that MUST BE squashed together with previous.
In the commit message I explained it, but I prefer you do that.
Let me know if you agree with the changes.

**Comment by ulfalizer** [comment]
> @ulfalizer
> I added a couple of commits that MUST BE squashed together with previous.
> In the commit message I explained it, but I prefer you do that.
> Let me know if you agree with the changes.

Looks good to me, thanks! Squashed them in.

`DT_INST_0_ST_LPS22HH_CS_GPIOS_FLAGS` seems unused, but maybe it was deliberate.

**Review by avisconti — APPROVED** [review]
Perfect!

**Comment by avisconti** [comment]
> > @ulfalizer
> > I added a couple of commits that MUST BE squashed together with previous.
> > In the commit message I explained it, but I prefer you do that.
> > Let me know if you agree with the changes.
> 
> Looks good to me, thanks! Squashed them in.
> 
> `DT_INST_0_ST_LPS22HH_CS_GPIOS_FLAGS` seems unused, but maybe it was deliberate.

I think it should be used in the driver when configuring the gpio. This flag is generated from dts to say if gpio is active high or low. But I think is missing in almost all the sensor drivers. I think I should do a global fix later on.

Thanks for the good catch!

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
