### PR TITLE
Bluetooth: GATT: Verify security when notifiying or indicating

### PR DESCRIPTION
**Pull request by Thalley**
Adds a security checks when notifying or indicating, such
that we don't send notifications for characteristics that
require encryption on an unencrypted link.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

### CODE REVIEW

**Review by joerchan — CHANGES_REQUESTED** [review]
Great!

Please add BT_GATT_PERM_AUTHEN_MASK, so that we can check for MITM as well.

**Comment by Thalley** [comment]
@joerchan I've updated the PR to use BT_GATT_PERM_READ_ENCRYPT and BT_GATT_PERM_READ_AUTHEN instead of BT_GATT_PERM_ENCRYPT_MASK and BT_GATT_PERM_AUTHEN_MASK, as a characteristic may support non-encrypted writes and encrypted reads, and it is for reads we really want to avoid notifying the values.

**Comment by joerchan** [comment]
> @joerchan I've updated the PR to use BT_GATT_PERM_READ_ENCRYPT and BT_GATT_PERM_READ_AUTHEN instead of BT_GATT_PERM_ENCRYPT_MASK and BT_GATT_PERM_AUTHEN_MASK, as a characteristic may support non-encrypted writes and encrypted reads, and it is for reads we really want to avoid notifying the values.

Good point!

**Review by joerchan — APPROVED** [review]

**Comment by Vudentz** [comment]
@Thalley Im afraid this may drop packets when reconnecting which will get very tricky to debug, so may need to add a warning when that happens and perhaps add a config options to not enforce this given that the CCC itself may only be writable when encrypted, or we attempt to encrypt by raising the security though that gets tricky since we would have to queue in the meantime.

**Comment by Thalley** [comment]
> @Thalley Im afraid this may drop packets when reconnecting which will get very tricky to debug, so may need to add a warning when that happens and perhaps add a config options to not enforce this given that the CCC itself may only be writable when encrypted, or we attempt to encrypt by raising the security though that gets tricky since we would have to queue in the meantime.

Adding warnings seem like a good idea. 

I'm not sure I follow the rest of your paragraph, but my point of view is that it is always better to drop a (notify/indicate) packet than to send something that should be encrypted, on a unencrypted link. 

In some of the upcoming LEA specs, we have some requirements for sending notifications after reconnection, and those specific implementation would have to check the return code (should do that anyways) when notifying to ensure that the notifications are sent (regardless of if it's "blocked" by permission or other).

**Comment by joerchan** [comment]
> @Thalley Im afraid this may drop packets when reconnecting which will get very tricky to debug, so may need to add a warning when that happens and perhaps add a config options to not enforce this given that the CCC itself may only be writable when encrypted, or we attempt to encrypt by raising the security though that gets tricky since we would have to queue in the meantime.

We wouldn't need to queue anything, as a server we don't send anything until the CCC has been subscribed to, and the CCC would not be restored until the bond has been re-established, I don't see this as a problem, if you wish to send something to a specific connection you wait for the CCC to be updated, or if you are broadcasting to all connections then you wouldn't know which connections it is sent to anyway, so queuing was anyway not possible.

**Comment by carlescufi** [comment]
@Vudentz can you please review?

**Comment by carlescufi** [comment]
> @Thalley Im afraid this may drop packets when reconnecting which will get very tricky to debug, so may need to add a warning when that happens and perhaps add a config options to not enforce this given that the CCC itself may only be writable when encrypted, or we attempt to encrypt by raising the security though that gets tricky since we would have to queue in the meantime.

Why would we drop them? Won't the application get an error instead?

**Comment by carlescufi** [comment]
@Vudentz ping

**Comment by Vudentz** [comment]
> > @Thalley Im afraid this may drop packets when reconnecting which will get very tricky to debug, so may need to add a warning when that happens and perhaps add a config options to not enforce this given that the CCC itself may only be writable when encrypted, or we attempt to encrypt by raising the security though that gets tricky since we would have to queue in the meantime.
> 
> @Vudentz
> Why would we drop them? Won't the application get an error instead?

If it is time sensitive it will have to drop the packet or queue in the application and wait until it encrypts which is what I suggested doing in the first place.

**Comment by Vudentz** [comment]
> > @Thalley Im afraid this may drop packets when reconnecting which will get very tricky to debug, so may need to add a warning when that happens and perhaps add a config options to not enforce this given that the CCC itself may only be writable when encrypted, or we attempt to encrypt by raising the security though that gets tricky since we would have to queue in the meantime.
> 
> We wouldn't need to queue anything, as a server we don't send anything until the CCC has been subscribed to, and the CCC would not be restored until the bond has been re-established, I don't see this as a problem, if you wish to send something to a specific connection you wait for the CCC to be updated, or if you are broadcasting to all connections then you wouldn't know which connections it is sent to anyway, so queuing was anyway not possible.

Lets say you are acting as a HID device, you start advertising when there is a button press etc, the device reconnects but encryption does not happen imediatelly, so in the meantime any notification/indication will fail, thus the application will be left with the decision to queue or drop the packets in the meantime, also note that it would be perfectly fine for the client enable encryption on demand so until it send anything that requires encryption then we are left with the server initiating the encryption if we want to make this works with such clients.

**Comment by Vudentz** [comment]
@Thalley Just to be clear here, we can either bite the bullet and do enforce permissions but that means the server/peripheral needs to start the encryption procedure or don't do it at all since the client/master is not required to encrypt the link and leaving this to applications to handle will just create duplicated code.

**Comment by Thalley** [comment]
> @Thalley Just to be clear here, we can either bite the bullet and do enforce permissions but that means the server/peripheral needs to start the encryption procedure or don't do it at all since the client/master is not required to encrypt the link and leaving this to applications to handle will just create duplicated code.

To me this seems like a simple choice: If a service/characteristic require encryption then we are not conforming to the spec if we ever send any data from the server/characteristic.

**Comment by Thalley** [comment]
> Lets say you are acting as a HID device, you start advertising when there is a button press etc, the device reconnects but encryption does not happen imediatelly, so in the meantime any notification/indication will fail, thus the application will be left with the decision to queue or drop the packets in the meantime, also note that it would be perfectly fine for the client enable encryption on demand so until it send anything that requires encryption then we are left with the server initiating the encryption if we want to make this works with such clients.

If a service is required to notify the current state when a (bonded) device reconnects (which is often the case), instead of notifying in the `connected` callback, the application (simply) needs to mark the connection with a pending notification flag, and then check the pending notification flag in the `security_changed` callback. 

The wording of notifying on reconnect might is a bit different from specification to specification, so some may need to queue/store the value on connection (if encryption is not done right away) if that is required.

**Review by asbjornsabo — APPROVED** [review]
LGTM

**Comment by joerchan** [comment]
@Vudentz The server shouldn't send anything unless the client has enabled notifications or indications, the CCCD value is not restored until the connection has been encrypted again. This is more about preventing the application from doing something stupid IMO.

**Comment by Vudentz** [comment]
> @Vudentz The server shouldn't send anything unless the client has enabled notifications or indications, the CCCD value is not restored until the connection has been encrypted again. This is more about preventing the application from doing something stupid IMO.

Well saying it stupid sounds little too much IMO, developers may not understand that read permissions are inherit to notifications as well, actually this may as well not work if for some reason the attribute has no read permission but enables with BT_GATT_CHRC_NOTIFY, so perhaps the application is not that stupid and in fact we need to add notification and indication permission separately in order to adhere to such design.

**Pull request merged**
