### PR TITLE
boards: esp32: add axp192 and mpu6886 to m5stickc_plus

### PR DESCRIPTION
**Pull request by jvermillard**
- fix i2c pin control
- configure axp192 mpu and the regulators
- configure the mpu6886

### CODE REVIEW

**Review by kartben — DISMISSED** [review]
cc @MrMarteng

**Comment by kartben** [comment]
@jvermillard It would probably be worthwhile to add `regulator` to the supported features in `boards/m5stack/m5stickc_plus/m5stickc_plus_esp32_procpu.yaml`

**Comment by jvermillard** [comment]
> @jvermillard It would probably be worthwhile to add `regulator` to the supported features in `boards/m5stack/m5stickc_plus/m5stickc_plus_esp32_procpu.yaml`

done

**Review by kartben — DISMISSED** [review]

**Comment by jvermillard** [comment]
Finally also added the RTC. I'm done with this one now 😀

**Review by kartben — DISMISSED** [review]

**Review by marekmatej — DISMISSED** [review]

**Review by sylvioalves — DISMISSED** [review]

**Comment by jvermillard** [comment]
rebased due to conflict

**Review by sylvioalves — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
