### PR TITLE
tests: gpio: Updated gpio configuration for all boards

### PR DESCRIPTION
**Pull request by shankarkm**
Updated gpio configuration for all boards

Signed-off-by: ravishankarkm <ravix.shankar.km@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
driver.json?

**Comment by shankarkm** [comment]
@nashif sorry. It should be samples/driver/gpio/src/main.c

**Review by kumarvikash1 — APPROVED** [review]
Changes looks good.

**Comment by carlescufi** [comment]
@shankarkm can you please rebase this?

**Review by galak — COMMENTED** [review]
Now that we have DT support for GPIO, we should add that to the test, and it might greatly reduce the amount of ifdef's here.

**Comment by galak** [comment]
@nashif can you take a look to see if we can merge this or what's next.  My DT comment about GPIO shouldn't hold this up.

**Pull request merged**
