### PR TITLE
drivers: bluetooth: hci: Fix uninitialized array index, issue #66806

### LINKED ISSUE #66806: [Coverity CID: 338094] Uninitialized array index read in drivers/bluetooth/hci/spi.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/bluetooth/hci/spi.c

Category: Memory - illegal accesses
Function: `bt_spi_get_header`
Component: Bluetooth
CID: [338094](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=338094)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/bluetooth/hci/spi.c#L220

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT). ([CWE-457](http://cwe.mitre.org/data/definitions/457.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by HoZHel**
Fix issue #66806 related to uninitialized array index, caused by PR #65172.

Fixes #66806

### CODE REVIEW

**Review by alwa-nordic — CHANGES_REQUESTED** [review]
I feel the commit message is lacking an explanation defending why it's ok to conflate invalid `op`s with `SPI_WRITE`. I'm sure you've put thought into it, but us reviewers don't know without being told. It's also good for future reading of git history.

**Comment by HoZHel** [comment]
> I feel the commit message is lacking an explanation defending why it's ok to conflate invalid `op`s with `SPI_WRITE`. I'm sure you've put thought into it, but us reviewers don't know without being told. It's also good for future reading of git history.

Since `bt_spi_get_header` is static and it's called in `bt_spi_rx_thread` and `bt_spi_send` with `op`s as `SPI_READ` and `SPI_WRITE` respectively, I didn't put any check on `op` for values rather than these two. However, if you prefer to have a check on it, I can add it and return `-EINVAL` for other values. Please, let me know.

**Comment by alwa-nordic** [comment]
> > I feel the commit message is lacking an explanation defending why it's ok to conflate invalid `op`s with `SPI_WRITE`. I'm sure you've put thought into it, but us reviewers don't know without being told. It's also good for future reading of git history.
> 
> Since `bt_spi_get_header` is static and it's called in `bt_spi_rx_thread` and `bt_spi_send` with `op`s as `SPI_READ` and `SPI_WRITE` respectively, I didn't put any check on `op` for values rather than these two. However, if you prefer to have a check on it, I can add it and return `-EINVAL` for other values. Please, let me know.

Ah, ok. I think adding an assertion will satisfy Coverity. I think that's clearer than the catch-all else and I would prefer it. Another option is to make the type of the op be an enum. Do you know why we have special values for SPI_READ and SPI_WRITE?

With your explanation, the catch-all else is acceptable, but not great.

**Comment by HoZHel** [comment]
> > > I feel the commit message is lacking an explanation defending why it's ok to conflate invalid `op`s with `SPI_WRITE`. I'm sure you've put thought into it, but us reviewers don't know without being told. It's also good for future reading of git history.
> > 
> > 
> > Since `bt_spi_get_header` is static and it's called in `bt_spi_rx_thread` and `bt_spi_send` with `op`s as `SPI_READ` and `SPI_WRITE` respectively, I didn't put any check on `op` for values rather than these two. However, if you prefer to have a check on it, I can add it and return `-EINVAL` for other values. Please, let me know.
> 
> Ah, ok. I think adding an assertion will satisfy Coverity. I think that's clearer than the catch-all else and I would prefer it. Another option is to make the type of the op be an enum. The enum might be best, since it will be zero-cost.
> 
> With your explanation, the catch-all else is acceptable, but not great.
> 
> EDIT: I'm also fine with returning `-EINVAL`, if you prefer that.

By assertion, do you mean using `BUILD_ASSERT()` or `__ASSERT()`?

**Comment by alwa-nordic** [comment]
> By assertion, do you mean using `BUILD_ASSERT()` or `__ASSERT()`?

I was thinking `__ASSERT_NO_MSG(op == SPI_READ || op == SPI_WRITE)`.

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
