### PR TITLE
The Linux development environment setups for Ubuntu and Fedora requir…

### PR DESCRIPTION
**Pull request by dleach02**
…es "ccache" to allow proper operation of the sanity test script.

### CODE REVIEW

**Comment by dbkinder** [comment]
signed-off-by line is missing from the commit (commit -s), and the title is too long (failing gitlint check).
@nashif you OK with this change?

**Review by dbkinder — CHANGES_REQUESTED** [review]
failing gitlint checks (see shippable log)

**Comment by dleach02** [comment]
Sorry about that. I've added the -s

**Comment by pfalcon** [comment]
@dleach02 : There're also commit message conventions to follow, https://github.com/zephyrproject-rtos/zephyr/blob/master/CONTRIBUTING.rst#commit-guidelines ("git log" for more examples).

**Comment by dleach02** [comment]
All checks passed ;-)

**Review by dbkinder — APPROVED** [review]
Thanks!  From a doc point of view we're good.  I'd like to get a technical reviewer to agree this is needed @nashif or @andrewboie for example...

**Comment by dleach02** [comment]
Understood. Just to be clear, I started from a fresh install of Ubuntu and was getting some guidance from Maureen about the sanity tests. It didn't work and the error indicated that ccache was missing so I installed that. I went ahead and created a Fedora build environment as well to see if this was common across both distros and it was.

Sorry for the problems in the commit though (my first one).

**Comment by dbkinder** [comment]
OK.  I see in .shippable.yml that ccache is indeed being used in our CI setup, so I suspect this is indeed an OK thing to add to the developer setup instructions (but I'm just the tech writer :)

**Comment by pfalcon** [comment]
Well, going that deep, nope, I don't think that ccache should be *needed* to start development. @dleach02 refers to sanitycheck as the cause of issue, and it has:

~~~
$ ./sanitycheck --help | grep ccache
WARNING scl::scl.<module>():53: can't import pykwalify; won't validate YAML (No module named 'pykwalify')
Generating LALR tables
                   [--compare-report COMPARE_REPORT] [--ccache] [-B SUBSET]
  --ccache              Enable the use of ccache when building
~~~

I.e. ccache should not be used unless explicitly enabled. But if @dleach02 verified that it's still called for nonetheless, well, then we have a bug and can merge this patch as workaround.

(Well, we could go for a fix, i.e. find where ccache unrightly called, but working around is apparently easier, given that we already call users to install a lot of unneeded stuff, e.g. majority of things in https://github.com/zephyrproject-rtos/zephyr/blob/master/scripts/requirements.txt are *not* needed for development, only for doc generation, which few people will do locally. At the time that file was merged, I proposed that we split it in 2 files - one for development, another for docgen (suggested to be run in virtualenv), but that didn't work).

**Comment by nashif** [comment]
> (Well, we could go for a fix, i.e. find where ccache unrightly called, but working around is apparently easier, given that we already call users to install a lot of unneeded stuff, e.g. majority of things in https://github.com/zephyrproject-rtos/zephyr/blob/master/scripts/requirements.txt are not needed for development, only for doc generation, which few people will do locally. At the time that file was merged, I proposed that we split it in 2 files - one for development, another for docgen (suggested to be run in virtualenv), but that didn't work).

Documentation is part of development, whether when you add an API or a board or a sample or a new subsystem, saying that we do not need those is not right, everyone who needs those when contributing to Zephyr or touching the code. It is easier  to setup everything in 1 go and not worry about it than having to install bits and pieces as you move along.

**Comment by andrewboie** [comment]
ccache isn't required, it only uses it if USE_CCACHE=1 is in your environment or you specifically tell sanitycheck to use it via command line arg.
any other behavior than this is a bug

**Comment by dleach02** [comment]
Folks, I did not dig into the reason for needing ccache and to be honest, I didn't even complete the running of the sanity test script (takes too long). This started off as a discussion I was having with Maureen and she had pointed me at this script. I went to run it and the error given was because the script needed ccache. Now if this is a bug in the script then we should fix the script and ignore the pull request. But as nashif says, the setup instructions should include everything that is needed instead of bits and pieces over time... 

Now to be clear, my Ubuntu and Fedora setups are fresh installs. I did the Fedora one to determine if it had a similar problem to my normal environment in Ubuntu. The setup instructions we have should assume a fresh setup (which I think it does). Not sure if the Zephyr infrastructure has a direct test for this but it would be useful to initiate tests from a virgin OS image to ensure that things don't creep in.

**Comment by pfalcon** [comment]
@dleach02 : It's great feedback, you're in a good position as a newcomer to spot things which the rest of folks take for granted, learned to workaround, or just some recent issues/regressions. So, it's really useful.

**Comment by pfalcon** [comment]
@nashif :

> Documentation is part of development

So, let me formulate it differently: It's one thing to request users to install innocent library like pyelftools globally (like we request (show) users). It's different matter to request the same for bunch of packages like sphinx or docutils. These are well-know and popular packages, usually shipped by OS. Overwriting them with Zephyr's random versions can destabilize the whole user system. (Like, you trick user into upgrading/downgrading docutils, then next Python package throws errors during installation.) An obvious solution is to split requirements in 2 and suggest to install the docs ones in virtualenv. If that doesn't ring a bell, we can wait until angry users with broken systems actually appear ;-).

**Comment by andrewboie** [comment]
@pfalcon sphinx and the rest of the documentation packages are so unstable that we really have to insist on specific versions of them or the documentation simply doesn't build, this is not gonna change for the foreseeable future, @dbkinder can give details offline if you really want them but getting on a soapbox about it doesn't help matters

**Comment by pfalcon** [comment]
> @pfalcon sphinx and the rest of the documentation packages are so unstable that we really have to insist on specific versions of them or the documentation simply doesn't build, this is not gonna change for the foreseeable future

Yeah, I didn't even mention that, because everyone seems to know that. The conclusion is the same though - we should recommend building docs in virtualenv (and not do that for normal zephyr building, because it's extra complication for starting up). And yep, I'm taking a chance to raise that issue in another newcomer report, sorry for hijacking the thread ;-).

**Comment by dbkinder** [comment]
Soooo.... back to whether ccache should be added to the packages to install in the documentation, or is there another patch in the works to fix use of ccache in sanitycheck?

**Pull request merged**
