### PR TITLE
spi: SAM add spin lock around all tx/rx/txrx funcs

### LINKED ISSUE #54461: SAM spi bus inoperable when interrupted on fast path
**Describe the bug**
The Atmel SAM fast tx/rx/txrx spi functions will leave the SPI bus in an inoperable state if interrupted, potentially spinning forever waiting on some data.

There are evidence from @yperess as he ran into trouble with faster data ready interrupts on the icm42688 with the tdk robokit.

**Expected behavior**
SAM fast spi driver functions should work properly when driver is interrupted.

**Impact**
This could lead product inoperative.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.15
 - Commit v3.3-RC2

### PR DESCRIPTION
**Pull request by teburd**
The fast tx/rx/txrx functions will leave the SPI bus in an inoperable state if interrupted, potentially spinning forever waiting on some data. Wrapping these operations in what amounts to a critical section using spin locks to avoid the issue.

I had this commit on a branch for awhile and was reminded by @yperess as he ran into trouble with faster data ready interrupts on the icm42688 with the tdk robokit

Signed-off-by: Tom Burdick <thomas.burdick@intel.com>

### CODE REVIEW

**Review by nandojve — APPROVED** [review]
I understand this is in fact fixes an issue so I took liberty to associate a bug for v3.3.

**Comment by teburd** [comment]
Thanks @nandojve yes it fixes it a bug for me

**Comment by yperess** [comment]
I tried cherry-picking this change ontop of my icm42688 interrupt commit (ToT on https://github.com/yperess/zephyr/tree/peress/sensor_shell) and I wasn't able to get things running past 12.5Hz still.

**Comment by pdgendt** [comment]
@yperess @teburd 
FYI: I have an open PR (#51694) to use the SPI interrupts instead of blocking in loops

**Comment by teburd** [comment]
> I tried cherry-picking this change ontop of my icm42688 interrupt commit (ToT on https://github.com/yperess/zephyr/tree/peress/sensor_shell) and I wasn't able to get things running past 12.5Hz still.

It's unlikely this is the only problem for that particular setup, but its one I definitely ran into.

**Comment by teburd** [comment]
> @yperess @teburd FYI: I have an open PR (#51694) to use the SPI interrupts instead of blocking in loops

I could be wrong but I'm not sure interrupt driven transfers is helpful here... my math could be very wrong, please correct me if so! sam e70 has a 2 byte transmit data register... at 20 MHz its going to be empty in 800ns. That's not very much time to poll, and an interrupt triggering context switching is going to probably be a lot more costly.

**Review by yperess — APPROVED** [review]
I got things working up to 8kHz of interrupts, limiting factor to getting 32kHz seems to be the context switching now so this is 100% needed to bridge the gap from 12.5Hz to 8kHz

**Comment by nandojve** [comment]
Hi @yperess ,

Thank you for the input. I was wondering if you could give us a more context about data sizes and what is the frequency you selected.

**Comment by yperess** [comment]
> Hi @yperess ,
> 
> Thank you for the input. I was wondering if you could give us a more context about data sizes and what is the frequency you selected.

Sure thing, I'll be happy to. I'm using the ICM42688 IMU on the TDK Robokit1 board. What I've done (PR will go up for review this week, I'm just not in a rush since we're still in feature freeze) is set up a trigger on `SENSOR_CHAN_ALL` and `SENSOR_TRIG_DATA_READY`. The handler will take samples for 5s at a time and print the average per channel. The sensor supports the following data which are sampled for each iteration:
- `SENSOR_CHAN_ACCEL_X`
- `SENSOR_CHAN_ACCEL_Y`
- `SENSOR_CHAN_ACCEL_Z`
- `SENSOR_CHAN_GYRO_X`
- `SENSOR_CHAN_GYRO_Y`
- `SENSOR_CHAN_GYRO_Z`
- `SENSOR_CHAN_DIE_TEMP`

On each interrupt, the sensor driver does the following:
1. [ISR] Post a `k_work` to the system work queue
2. [Handler] Read the status register (1 byte)
3. [handler] Read data registers (14 bytes)
4. Add values to the accumulators
5. Conditional print and reset accumulators if 5s passed

**Without this PR**
Once the sensor ODR (output-data-rate) was set above 12.5Hz the application would deadlock

** With this PR**
ODR can be set as high as 32kHz without an issue, but I can only handle 8kHz of data (so 75% of the samples are dropped) due to latency in context switching and data format conversion. But, there is no deadlock and the application keeps running.

**Comment by nandojve** [comment]
Just to inform, the XDMAC is a quite complex feature and can be used to do interesting things, see `Atmel AT17417: Usage of XDMAC on SAM S/SAM E/SAM V`. If you use a linked list all data can be transferred without CPU intervention.

I think it is possible add a feature on SPI that configure an interrupt to trigger a DMA linked list transfer, for instance. In this case, SPI driver reacts to that interrupt to enable the pre-programmed DMA transfer. Another interrupt could be configured to tell the consumer that the full transfer is done, allowing the consumer reschedule the post processing data. If you are luck, DMA can `striding` data during reception or even after using another DMA linked list operation on a MEM2MEM basis.

The other think that could be checked is to pre-program DMA to start a transfer using a PIOA line. I mean, instead process an interrupt a HW Trigger is made to enable a linked list transfer. The first item on the list is a PIOA line that will read a dummy data but the next linked list should be the SPI peripheral. This may mimics an event driver DMA transfer on the system which don`t require CPU. In this case there is a but, because I guess this works.

**Comment by teburd** [comment]
> Just to inform, the XDMAC is a quite complex feature and can be used to do interesting things, see `Atmel AT17417: Usage of XDMAC on SAM S/SAM E/SAM V`. If you use a linked list all data can be transferred without CPU intervention.
> 
> I think it is possible add a feature on SPI that configure an interrupt to trigger a DMA linked list transfer, for instance. In this case, SPI driver reacts to that interrupt to enable the pre-programmed DMA transfer. Another interrupt could be configured to tell the consumer that the full transfer is done, allowing the consumer reschedule the post processing data. If you are luck, DMA can `striding` data during reception or even after using another DMA linked list operation on a MEM2MEM basis.
> 
> The other think that could be checked is to pre-program DMA to start a transfer using a PIOA line. I mean, instead process an interrupt a HW Trigger is made to enable a linked list transfer. The first item on the list is a PIOA line that will read a dummy data but the next linked list should be the SPI peripheral. This may mimics an event driver DMA transfer on the system which don`t require CPU. In this case there is a but, because I guess this works.

This sounds like a great hardware feature, I think  st has similar abilities to trigger dma transfers with various trigger sources.

I have some thoughts on this stuff for sure, and how it might be exposed generally as a friendlier api than the st/sam specific setups

**Pull request merged**
