### PR TITLE
scripts: bossac: Support flashing at an offset.

### PR DESCRIPTION
**Pull request by nzmichaelh**
The Adafruit SAMD51 boards use a combined BOSSA / U2F bootloader that
resides in the first 16 KiB.  Add support for pulling the application
partition offset from the configuration and using that to offset where
the binary gets flashed.

Signed-off-by: Michael Hope <mlhx@google.com>

### CODE REVIEW

**Comment by mbolivar** [comment]
@nzmichaelh This looks fine, sorry for not reviewing it. Do you want to close this one and rebase and submit against https://github.com/zephyrproject-rtos/west? It'll make its way into mainline from there.

If you can add tests for bossac while you are there that would be an enormous favor! I don't have any boards that use it so I can't test it well.

**Comment by mbolivar** [comment]
@nzmichaelh ping?

**Comment by mbolivar** [comment]
Hi, I am wondering if any more work on this is planned.

**Comment by nashif** [comment]
@galak @mbolivar rebased and tested on Arduino Due, those some of the initially intended behaviour of getting flash address from build configuration (DTS) was not working on this board and had to be modified.

**Review by mbolivar — APPROVED** [review]
Looks fine to me. There are some whitespace issues that aren't worth quibbling about.

@nashif, as a heads up, I plan on revisiting all of these "flash at offset" options to try to unify them post-v1.14 so there is a consistent user interface. I also want to make them aware of DTS partitions, so we can get functionality similar to Android's `fastboot flash partition [filename]`. This will probably involve deprecating runner-specific options like this. But let's get it in for now.

**Comment by nashif** [comment]
> @nashif, as a heads up,

ok

**Pull request merged**
