### PR TITLE
sensor: lsm6dsl: allow LSM6DS3 WHO_AM_I value

### PR DESCRIPTION
**Pull request by mniestroj**
LSM3DS3 accelerometer is very similar to LSM6DSL, which is already
supported in Zephyr. The main difference between both chips is reduced
register map in LSM3DS3.

Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>

### CODE REVIEW

**Comment by avisconti** [comment]
@mniestroj 
In a recent past I have done this commit aca8ae3fd where I used same driver for different
component with same who_am_i.

But I think that when you have a different who_am_i it is better to have a different driver.
Moreover there are small differences in the two devices feature (filters, fifo, some bit in the registers) 
that this simple driver is not currently using. but that we could enable in the future.

**Comment by mniestroj** [comment]
@avisconti I just didn't want to copy-paste most of the driver and change who_am_i value, at least not for now. The major reason was code deduplication. However we can split drivers whenever we want to in later stages, when such need arises. My another idea was to have configurable WHO_AM_I value, so we can configure it from outside of Zephyr repository, e.g. with device-tree (preferred) or Kconfig. Last option that I have in my mind is to just skip who_am_i value verification.

**Review by avisconti — CHANGES_REQUESTED** [review]
In my opinion is better to have a different driver here, as the who_am_i is different.

**Comment by mniestroj** [comment]
Thanks for review! I'll close this PR, as new driver will likely be better part of new PR.

**Pull request closed without merging**
