### PR TITLE
Bluetooth: Mesh: LPN regressions

### PR DESCRIPTION
**Pull request by trond-snekvik**
Fixes three LPN regressions, where two were introduced in the credentials fix, and the last appears to have been lurking for a long time.

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by LingaoM — CHANGES_REQUESTED** [review]
https://github.com/zephyrproject-rtos/zephyr/blob/d5072d13786edc4bc34a169e743d5aeeee34a819/subsys/bluetooth/mesh/lpn.c#L560-L566

I think it is necessary to put this `lpn->lpn_counter++` in front, Comparing this count will be used in the key rephase phase, and lpn is obviously inconsistent with friend, which will cause disconnection.

**Comment by LingaoM** [comment]
> https://github.com/zephyrproject-rtos/zephyr/blob/d5072d13786edc4bc34a169e743d5aeeee34a819/subsys/bluetooth/mesh/lpn.c#L560-L566
> 
> I think it is necessary to put this `lpn->lpn_counter++` in front, Comparing this count will be used in the key rephase phase, and lpn is obviously inconsistent with friend, which will cause disconnection.

Also friend have same problem, i'll submit pr for this. https://github.com/zephyrproject-rtos/zephyr/blob/d5072d13786edc4bc34a169e743d5aeeee34a819/subsys/bluetooth/mesh/friend.c#L875-L880

**Comment by trond-snekvik** [comment]
@LingaoM this seems like a separate issue from the three # fixes in this pr. Let's make a separate pr for it

**Comment by LingaoM** [comment]
> @LingaoM this seems like a separate issue from the three # fixes in this pr. Let's make a separate pr for it

#30622

**Review by LingaoM — APPROVED** [review]

**Pull request merged**
