### PR TITLE
net: l2: ieee802154: pkt: fix cpp build failure

### LINKED ISSUE #62282: ieee802154: Build failes when including the file net/ieee802154_radio.h in a cplusplus file.
**Describe the bug**
Build fails when including the file zephyr/net/ieee802154_radio.h in a cplusplus file.

**To Reproduce**
1. mkdir net_ieee802154_radio_build_fail; cd net_ieee802154_radio_build_fail
2. west init -m https://github.com/Maartenwn/net_ieee802154_radio_build_fail.git --mr master
3. west update
4. cd net_ieee802154_radio_build_fail
5. west build -b nrf52840dk_nrf52840 -p
7. See error
8. change target_sources from main.cpp to main.c
9. west build 
10. See no error

**Expected behavior**
Including this header in a cplusplus file should compile.

**Impact**
Because of this issue we either have to fork zephyr or compile the file with fPermissive.

**Logs and console output**
`zephyr/include/zephyr/net/ieee802154_pkt.h:95:26: error: invalid conversion from 'void*' to 'net_pkt_cb_ieee802154*' [-fpermissive]
   95 |         return net_pkt_cb(pkt);
      |                ~~~~~~~~~~^~~~~
      |                          |
      |                          void*
`

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: 8350fc2c63b10836bf3bf18a55f692fc6077e864

### PR DESCRIPTION
**Pull request by ghost**
ieee802154_pkt.h: Add cast to support CPP.

Fixes: #62282

### CODE REVIEW

**Comment by fgrandel** [comment]
The test failures seem to be unrelated to this change. I can reproduce them locally on main. Not sure what's going on. Mainline broken?

**Comment by jukkar** [comment]
Fixed now in mainline, please re-submit.

**Review by jukkar — APPROVED** [review]

**Comment by fgrandel** [comment]
@cfriedt ACK? :-)

**Review by cfriedt — APPROVED** [review]
LGTM. Although AFAICT, 802.15.4 is the only consumer of this field. Even if the intent were to allow other L2s to override it, it isn't possible with the current struct. So maybe some future cleanup in the net code, but this works for now

**Review by carlescufi — APPROVED** [review]

**Comment by fgrandel** [comment]
> Although AFAICT, 802.15.4 is the only consumer of this field. Even if the intent were to allow other L2s to override it, it isn't possible with the current struct.

@cfriedt @rlubos Yes agreed - it was a conscious choice.

There is a comment at that field that gives the rationale: Robert and I tried to find a compromise that is not prematurely abstract but still architecturally way better than the previous solution. We now only depend on a single IEEE 802.15.4 specific field (and one conditional include) rather than globally exposing tens of IEEE 802.15.4 specific fields. Plus we can use memcpy to clone the whole well-encapsulated block rather than having to clone field by field which broke encapsulation even more and had to be updated with every new field (which is easy to forget).

It is trivial to change this field in the future to a union of conditionally included control block versions if other L2s want to have their own. Linux has a pre-allocated untyped array of 40 bytes as a control block but that's not acceptable in the embedded world IMO. We could have introduced a union right away but that's not nice with a single field. I discussed several versions of this with Robert and we agreed that that was a good middle ground for now.

**Pull request merged**
