### PR TITLE
drivers: gpio: esp32: fix device binding error

### LINKED ISSUE #30961: esp32 broken by devicetree device updates
This issue backs PR #30937 which fixes issue introduced by DT update: #30845 

Created to provide a way to improve visibility for a broken SOC not exposed by CI.

### PR DESCRIPTION
**Pull request by sylvioalves**
fix issue introduced by DT update: #30845 

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>

Fixes  #30961

### CODE REVIEW

**Review by pabigot — APPROVED** [review]
This happened because [my suggested cleanup](https://github.com/zephyrproject-rtos/zephyr/pull/30845/files#r545785111) was in ignorance of the fact that this one device didn't have a `label` property.

As a short-term fix this is fine.  Longer term we need #30941, but if there are concerns about the fact that creates device objects with a null label pointer (which is a new thing) it may take a while to come to agreement on what to do, so I'm OK with this going in now, and in fact adding the pinmux cells is worth it anyway.

**Comment by sylvioalves** [comment]
@pabigot Thanks. I agree that #30941 is the correct solution regarding DT update. I push this PR as short-term to get rid of build failure and because the the null pointer issue (pinmux driver X gpio DT instance).

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by sylvioalves** [comment]
I think this can be closed as it's been fixed in here: #30941
@pabigot make sense?

**Comment by nashif** [comment]
if it was fixed, lets close this one...

**Pull request closed without merging**
