### PR TITLE
sensors: Adds drivers for ICM20948 IMU

### PR DESCRIPTION
**Pull request by pollend**
This is just a cleaned up branch from #15271. I squashed the changes into a single commit. 

Signed-off-by: Michael Pollind <polli104@mail.chapman.edu>

### CODE REVIEW

**Comment by avigreen1978** [comment]
Any idea on why wasn't this merged?

**Comment by MaureenHelm** [comment]
> Any idea on why wasn't this merged?

It failed several CI checks

**Comment by pollend** [comment]
> > Any idea on why wasn't this merged?
> 
> It failed several CI checks

Is there still interest?

**Comment by avigreen1978** [comment]
> > > Any idea on why wasn't this merged?
> > 
> > 
> > It failed several CI checks
> 
> Is there still interest? I can update the PR

Yes, I am interested. Thanks :)

**Comment by pollend** [comment]
I can fix the PR and resolve the CI problem @MaureenHelm

**Comment by avigreen1978** [comment]
Any updates?

**Comment by pollend** [comment]
> Any updates?

I created another pr don't have the setup anymore to verify the sensor

**Pull request closed without merging**
