### PR TITLE
Bluetooth: include: Fix wrong docs

### PR DESCRIPTION
**Pull request by LingaoM**
We can't call function which used by static init variable.

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

### CODE REVIEW

**Comment by Thalley** [comment]
I am not sure I understand the need for this change, or your commit message. Can you elaborate?

**Comment by LingaoM** [comment]
strlen is function.

**Comment by LingaoM** [comment]
static int len = strlen(str); 

It is ok?

**Review by joerchan — APPROVED** [review]
Looks ok, All of our samples does it this way, just hidden behind macros.

**Review by Thalley — APPROVED** [review]

**Pull request merged**
