### PR TITLE
arch: riscv: revert `ARCH_STACK_PTR_ALIGN` change in #76791 to fix #76996

### LINKED ISSUE #76996: arch: riscv: update ARCH_STACK_PTR_ALIGN on RV32E to 4 bytes fails testing at nrf54l15 cpuflpr
**Describe the bug**
The tests:
~ 200 tests are affected.
example:
zephyr/tests/drivers/timer/nrf_grtc_timer

Observed for
- nrf54l15pdk/nrf54l15/cpuflpr

**To Reproduce**
1. have nrf54l15pdk/nrf54l15/cpuflpr connected
2. go to your zephyr dir
3. west build -b nrf54l15pdk/nrf54l15/cpuflpr --sysbuild -- -DSB_CONFIG_VPR_LAUNCHER=y
4. west flash --skip-rebuild --erase
5. See console output

**Expected behavior**
Valid console output but there is no console output at all.

**Impact**
Not clear

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.8
 - Commit SHA or Version used: v3.7.0-829-g15aab68d29d9

### PR DESCRIPTION
**Pull request by ycsin**
Partially undo #76045 (but keep the required part to fix the traces output) and partially revert #76791 (but keep the test)

Fixes #76996

### CODE REVIEW

**Comment by carlescufi** [comment]
@nordic-piks can you please check if this fixes the issue?

**Comment by nordic-piks** [comment]
> @nordic-piks can you please check if this fixes the issue?

Already checking, I will give update in a few hours.

**Comment by nordic-piks** [comment]
> > @nordic-piks can you please check if this fixes the issue?
> 
> Already checking, I will give update in a few hours.

It helps ;)

**Review by nordic-piks — APPROVED** [review]

**Review by fkokosinski — DISMISSED** [review]

**Comment by ycsin** [comment]
force pushed to resolve merge conflict

**Review by fkokosinski — APPROVED** [review]

**Review by masz-nordic — APPROVED** [review]

**Pull request merged**
