### PR TITLE
Revert "lib: support linking to POSIX API with 3rd-party libc" and do an appropriate fix

### PR DESCRIPTION
**Pull request by aescolar**
This reverts commit 6342aa3cc06858575b0d6e69d4a98658ae8a49b0.
   
This commit should never have been merged.
Apart from the fact that this change was rejected in previous review,
this change is wrong, for 2 reasons:
1. The POSIX_API (POSIX compatibility shim) cannot be built if the host libC is used.
2. The Zephyr libC CMake files were guarded so they would not be dragged when CONFIG_EXTERNAL_LIBC was selected.

-----

In theory one may want to build the POSIX compability shim
with a different C library than one provided with Zephyr,
so let's not prevent it

----

Background can be found in https://github.com/zephyrproject-rtos/zephyr/pull/66998#discussion_r1436380262 
The PR which introduced this is https://github.com/zephyrproject-rtos/zephyr/pull/67042

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]

**Review by thedjnK — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by cfriedt — CHANGES_REQUESTED** [review]
This was the suggestion you made. It was not rejected. I reject your rejection

**Comment by aescolar** [comment]
> This was the suggestion you made. It was not rejected. I reject your rejection

@cfriedt The thing is, you do not have the right to dismiss review comments, or circumvent reviews by creating another PR, labeling it trivial and merging it yourself.
If the rest of us did that this would be madness.

Please do not block this PR, as there is no technical reason why you would not want this in.

**Review by cfriedt — APPROVED** [review]
Looks fine, I guess.

Thanks for clarifying?

**Comment by cfriedt** [comment]
Technically, it's a perfectly legitimate use case and it would actually be quite helpful for external libc's to be able to link to common libc code (i.e. code in common/libc that is tailored for use with Zephyr so that there can be some commonality / lack of duplication / reduction in conflict).

So I don't actually see the point in excluding libc (and specifically libc/common) in this PR.

**Pull request merged**
