### PR TITLE
manifest: hal_nordic: update nrf_802154

### LINKED ISSUE #41375: hal_nordic: update 15.4 driver to newest version
**Is your enhancement proposal related to a problem? Please describe.**
actually I'm strugling with an issue in the frame filter of nordic's IEEE802.15.4 driver (https://discord.com/channels/720317445772017664/883445320812466209/922478238155018280).

**Describe the solution you'd like**
The issue is already fixed in the driver included in NCS, please update zephyr's `hal_nordic` to the latest version.

**Describe alternatives you've considered**
I could create a pull request, that fixes the bug (just three lines of code), but I'm pretty sure there are more improvements in the latest version of the hal.

### PR DESCRIPTION
**Pull request by ankuns**
This commit brings latest changes of nrf_802154 component
provided by hal_nordic module.

Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]

**Comment by carlescufi** [comment]
Delayed to 3.1.

**Review by gmarull — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
@ankuns please update this PR to use the final sha; https://github.com/zephyrproject-rtos/hal_nordic/pull/108 is merged

**Comment by ankuns** [comment]
Please merge after https://github.com/zephyrproject-rtos/zephyr/pull/42355 is merged

**Comment by carlescufi** [comment]
> Please merge after #42355 is merged, without that changes won't build

Please rebase and use eab07c9d86341b9f249afe8188cceab3b0dc90ef as a SHA

**Review by rlubos — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Pull request merged**
