### PR TITLE
doc: twister: ztest: Add test application diagram

### LINKED ISSUE #74151: Fix confusing wording about "test suite", "test", "test identifier", "test case", "test case project", "test projects", and "test scenario"
**Describe the bug**

The first sub-section in the "[Test Framework](https://docs.zephyrproject.org/latest/develop/test/ztest.html#test-framework)" is "[Creating a test suite](https://docs.zephyrproject.org/latest/develop/test/ztest.html#creating-a-test-suite)".  The sub-section states:

> Using Ztest to create a test suite is as easy as calling the `ZTEST_SUITE`.

Thus, readers, including me, assume that a "test suite" is something we define using `ZTEST_SUITE()`.  The first argument to the macro is `SUITE_NAME` as documented in https://docs.zephyrproject.org/apidoc/latest/ztest__test_8h.html .

The next sub-section is "[Adding tests to a suite](https://docs.zephyrproject.org/latest/develop/test/ztest.html#adding-tests-to-a-suite)". It says:

> [ZTEST](https://docs.zephyrproject.org/latest/develop/test/ztest.html#c.ZTEST) `(suite_name, test_name)` - Which can be used to add a test by `test_name` to a given suite by `suite_name`.

So if you have

```c
ZTEST(my_suite, test_my_test)
{
}
```

We all assume `my_suite` is a test suite and `test_my_test` is a test.  In fact, if you ask twister to print list of tests, it sort of prints the test I just added:

```
$ ./scripts/twister ... --list-tests
[...]
 - sec.sub.my_test
```

Now if you go to the next section, [Test Runner (Twister)](https://docs.zephyrproject.org/latest/develop/test/twister.html#test-runner-twister), you encounter a section called [Test Cases](https://docs.zephyrproject.org/latest/develop/test/twister.html#test-cases), which reads:

> Test cases are detected by the presence of a testcase.yaml or a sample.yaml files in the application’s project directory. This file may contain one or more entries in the test section each identifying a test scenario.

As I understand, this paragraph says:

- there is something called "test case".
- the entries in `.yaml` files are  test scenarios

And the following sentence makes me read more than twice.

> The name of each testcase needs to be unique in the context of the overall testsuite and has to follow basic rules:

"test case" is not defined here, but if you go back to "Test Framework, you can find:

> A test case project may consist of multiple sub-tests or smaller tests that either can be testing functionality or APIs.

With this, we can assume that "test case" is a project?

It also says "test case" must be unique _ in the context of the overall testsuite_. Remember test suite is some thing we defined in `.c`. Or is "testsuite" different from "test suite"?

And the following list talk about "test identifier" and not "testcase".  is "test identifier" a name of a testcase?

farther you go, on to `testcase.yaml` and the out put of `twister -h`, you get more confused by these words.

This came to me when I wanted to run a single test in my test suite.  That's doable for many non-embedded testing frameworks.  Thus, I first assumed that we can also do it.

**Expected behavior**
A clear and concise usage of the following words:

- "testsuite"
- "test suite"
- "test"
- "test identifier"
- "test case"
- "test scenario"
- "test case project"
- "test project"

**Impact**

Confusing.

**Additional context**

If you can tell me which is what, I can create a PR for this.  I hope my description is clear enough to realize that we have some wording problem. Thanks.

### PR DESCRIPTION
**Pull request by golowanow**
Add a diagram to illustrate a test application's project components with relationships between Ztest and Twister objects.

To help resolve #74151 together with #74669

The proposed diagram - https://builds.zephyrproject.io/zephyr/pr/74834/docs/develop/test/twister.html#id1

### CODE REVIEW

**Comment by yashi** [comment]
It'd be nicer if the diagram cares dark mode as well.

**Comment by golowanow** [comment]
> It'd be nicer if the diagram cares dark mode as well.

hmm, Chrome dark theme shows the same on the [page](https://builds.zephyrproject.io/zephyr/pr/74834/docs/develop/test/twister.html#id1) white background

**Comment by yashi** [comment]
This is what I got on my Chrome Version 126.0.6478.114 (Official Build) (64-bit) with the sun-moon toggle button at the top right corner of the page for the dark mode.

image

image

**Comment by golowanow** [comment]
> It'd be nicer if the diagram cares dark mode as well.

@yashi, the diagram adjusted.

**Review by yashi — DISMISSED** [review]

**Review by hakehuang — DISMISSED** [review]

**Comment by nashif** [comment]
some comments:

image


- The `test-identifier` and `test project group` is not clear and conflicts with existing terminology
- Do not use Test case for the test application, this is the source of all confusion and we shall not repeat this in the diagram.
- Need to should `1..n` possibility for scenarios, suites and test cases
- Need to show that in twister, a test instance is a match between a scenario and a target platform, this is not immediately visible in the diagram right now. Matching a scenario to a platform in twister is the core functionality of twister, everything else and terminology used in there for suites and cases should be considered internal and should not be mixed up with how the actual test code and test structure.

**Review by nashif — CHANGES_REQUESTED** [review]
see last comment, and rebase please

**Comment by golowanow** [comment]
@nashif, your comments should be addressed, please review again.

**Comment by golowanow** [comment]
@nashif, do you any comments on the updated diagram ?

**Comment by nashif** [comment]
> @nashif, do you any comments on the updated diagram ?

sorry, missed that.  lgtm.

**Review by nashif — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]

**Comment by PerMac** [comment]
@nashif General note: I think we added a new confusion to the picture :) TL;DR: Now we have a `configuration` keyword used in different contexts. 

When we were talking about terminology we decided that `test configuration (in docs) == test instance (in code)` i.e. a combination of a `scenario` and a `platform`. With recent changes in docs, reflected in Dmitrii's diagram, configuration is used to refer to the testcase/sample.yaml. This can have more meaning, since those yamls describes how to configure your tests/builds but this is not how it was used. From quick scan of twister docs it seems the `configuration` is no longer used in the `instance` meaning there, that's good. However, the `instance` meaning is still used in the twister's summary, (e.g. `10 of 20 test configurations passed` etc.) so this has to be addressed. And most likely this section https://docs.zephyrproject.org/latest/develop/test/twister.html#test-configuration will cause confusion now, since both `configurations` refers to yaml files (testcase.yaml and test_config.yaml). Maybe we should discuss the terminology again before further fixes, because it can end up in a whack-a-mole activity. 


> Need to show that in twister, a test instance is a match between a scenario and a target platform, this is not immediately visible in the diagram right now.  

I think this was not addressed but I don't know how to show this on such diagram... maybe in next iteration we would figure this out

**Review by PerMac — APPROVED** [review]

**Pull request merged**
