### PR TITLE
[RFC] Don't expose L2 implementation details through the L2 API

### PR DESCRIPTION
**Pull request by SebastianBoe**
We need to clean up our dependencies before OpenThread is merged
because when OpenThread is in the DAG it is really important that
components are coupled as loosely as posssible.

Tight coupling in a build system leads to an unnecessary amount of
rebuilding, which is fine for a small stack like ieee802154, but a problem
for a big one like OpenThread.

This is an RFC for a possible method to remove unnecessary
dependencies. It's success can be seen when you do this test:

1. make
2. touch ~/zephyr/include/net/ieee802154.h

Now that ieee802154.h is dirty, any source file that is including it must be rebuilt.

3.  make

Build output extract when this incremental build is done:
```

[  8%] Building C object CMakeFiles/app.dir/src/echo-server.c.obj
[  8%] Building C object CMakeFiles/app.dir/src/udp.c.obj
Scanning dependencies of target zephyr
[ 11%] Built target arch__x86__soc__ia32
[ 11%] Building C object zephyr/subsys/net/lib/app/CMakeFiles/subsys__net__lib__app.dir/init.c.obj
[ 11%] Building C object zephyr/subsys/net/lib/app/CMakeFiles/subsys__net__lib__app.dir/net_app.c.obj
[ 12%] Building C object zephyr/subsys/net/lib/app/CMakeFiles/subsys__net__lib__app.dir/server.c.obj
[ 12%] Building C object zephyr/subsys/net/lib/app/CMakeFiles/subsys__net__lib__app.dir/ieee802154_settings.c.obj
[ 32%] Built target kernel
[ 33%] Linking C static library libapp.a
[ 40%] Built target app
[ 41%] Linking C static library libsubsys__net__lib__app.a
[ 42%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/net_context.c.obj
[ 42%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/net_core.c.obj
[ 43%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/net_if.c.obj
[ 43%] Built target subsys__net__lib__app
[ 44%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/utils.c.obj
[ 45%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/6lo.c.obj
[ 45%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/net_pkt.c.obj
[ 46%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/icmpv6.c.obj
[ 47%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/ieee802154/ieee802154_uart_pipe.c.obj
[ 48%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/nbr.c.obj
[ 51%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/connection.c.obj
[ 51%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/net_shell.c.obj
[ 52%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/udp.c.obj
[ 52%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/ipv6.c.obj
[ 53%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/route.c.obj
[ 53%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/dummy.c.obj
[ 54%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154.c.obj
[ 56%] Linking C static library libzephyr.a
[ 56%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_frame.c.obj
[ 57%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_fragment.c.obj
[ 57%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_mgmt.c.obj
[ 58%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_radio_csma_ca.c.obj
[ 59%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_shell.c.obj
[ 82%] Built target zephyr
```

That is quite a few files, intuitively, you would not think that it
was necessary for echo-server to be rebuilt, but it is because the
ieee80215.h header file is leaking through the net_l2.h interface into
application source files.

Doing the same test after this patch yields much better results:

```
[ 16%] Built target app
[ 17%] Built target arch__x86__soc__ia32
Scanning dependencies of target subsys__net__ip
[ 17%] Built target linker_pass2_script
Scanning dependencies of target zephyr
[ 17%] Building C object zephyr/subsys/net/lib/app/CMakeFiles/subsys__net__lib__app.dir/ieee802154_settings.c.obj
[ 18%] Linking C static library libsubsys__net__lib__app.a
[ 38%] Built target kernel
[ 41%] Built target subsys__net__lib__app
[ 43%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_frame.c.obj
[ 43%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154.c.obj
[ 43%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_mgmt.c.obj
[ 45%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_shell.c.obj
[ 45%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/l2/ieee802154/ieee802154_radio_csma_ca.c.obj
[ 45%] Linking C static library libsubsys__net__ip.a
[ 46%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/ieee802154/ieee802154_uart_pipe.c.obj
[ 60%] Built target subsys__net__ip
[ 83%] Built target zephyr

```
Note that now, only files that look like they need to know somehting
about ieee80215.h are rebuilt.

If this direction is considered viable I can update the other
L2_CTX_TYPE defines to be consistent. Now that it is proven that it is
possible to solve this problem, perhaps someone has a much better
solution also ...

I know that it seems a trivial thing, but I would prefer to solve this
now, than to solve this as a part of the OpenThread merge, as that
patch is difficult enough to review as is ...

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
This relates to https://github.com/zephyrproject-rtos/zephyr/issues/5286

**Comment by SebastianBoe** [comment]
The change essentially tries to split net_l2.h in two header files. One that has symbols needed by those that are above the L2 interface, and one that has symbols needed by those that are below the interface.

This has the desired change of loosening the coupling in the build system.

**Review by tbursztyka — CHANGES_REQUESTED** [review]
No need to split net_l2.h actually.

See my PR  #5300, from that, ieee802154.h could own the IEEE802154_L2_CTX_TYPE, as now this header is included only by drivers and the l2 relevantly.

Well, let me update my PR to see if that would fix your issue, but I think it will.

**Comment by tbursztyka** [comment]
ok I updated the PR #5300 
does it fix your issue for OT?

(you'r right, we may have to move other *_CTX_TYPE to more relevant header)

**Comment by SebastianBoe** [comment]
Going to test, but yes, looks like that will do it! Great! :D

**Pull request closed without merging**
