### PR TITLE
Bluetooth: Audio - make module Kconfigs not check for BT_AUDIO

### PR DESCRIPTION
**Pull request by asbjornsabo**
Check for BT_AUDIO in the Kconfig files that didn't, for consistency
with the other Kconfig files.

There is an alternative approach that would also be consistent - that would be to check in _none_ of the files.
All Kconfig.<modules> files are rsourced (directly or indirectly) from the main Kconfig file _only_ if BT_AUDIO is defined.  As long as this is true, checking makes  no difference.
Not sure which approach is better.

### CODE REVIEW

**Comment by Thalley** [comment]
> There is an alternative approach that would also be consistent - that would be to check in none of the files.

Do we gain anything from having the BT_AUDIO Kconfig?

**Comment by asbjornsabo** [comment]
> > There is an alternative approach that would also be consistent - that would be to check in none of the files.
> 
> Do we gain anything from having the BT_AUDIO Kconfig?

At all, you mean?
IMO, it seems reasonable to have one top-level config to enable/disable the whole audio sybsystem.  It enforces some modularity. So I would say yes.

**Comment by Thalley** [comment]
> At all, you mean? IMO, it seems reasonable to have one top-level config to enable/disable the whole audio sybsystem. It enforces some modularity. So I would say yes.

But what should `BT_AUDIO` enable? Current it does not but just being a guard that doesn't really do anything. 
To me it is too generic to make any sense of, and given that Zephyr support both client and server (initiate/acceptor, or whatever terms makes the most sense here), we can't even use it enable common LE Audio profiles in a way that makes sense. 

I am not strictly against it, but as it right now I don't see the value of it.

**Comment by asbjornsabo** [comment]
> I am not strictly against it, but as it right now I don't see the value of it, unless we want to guard functionality such as VCP with it to hide Kconfigs in the GUI.

BT_AUDIO does not on its own enable anything in the implementation.  But it does disable things in the implementation, so it does act as an enable/disable in that way.
And I feel it has value as a group switch in Kconfig.  It modularizes, and reduces the number of items visible, which is a good thing.

OTOH, we will manage OK without it as well.

@carlescufi @jhedberg Do you have any advice on whether to keep BT_AUDIO as a config option to enable/disable the whole of le-audio?

**Comment by Thalley** [comment]
> BT_AUDIO does not on its own enable anything in the implementation. But it does disable things in the implementation, so it does act as an enable/disable in that way. And I feel it has value as a group switch in Kconfig. It modularizes, and reduces the number of items visible, which is a good thing.
> 

Good point. If we decide to go that route, I think a much cleaner solution would be to guard the the sourcing of the Kconfig files with it. 

I can see that we are already doing that: 
```c
if BT_AUDIO

config BT_CCID
	bool
	help
	  This hidden option is enabled when any of the content control
	  features are enabled.

rsource "Kconfig.baps"
rsource "Kconfig.vocs"
rsource "Kconfig.aics"
rsource "Kconfig.vcs"
rsource "Kconfig.mics"
rsource "Kconfig.csis"
rsource "Kconfig.otc"
rsource "Kconfig.mcs"

endif # BT_AUDIO
```
And as such, we do not need to `depend on` nor `if BT_AUDIO` in any of those files.

**Review by Thalley — CHANGES_REQUESTED** [review]
Please update the PR name as well :) 

Should we do something about `BT_AUDIO_DEBUG` while we are at it?

**Comment by Thalley** [comment]
> I think we should. For one thing, that is currently in Kconfig.baps, not in the main Kconfig. But it could probably just be totally removed?

I think we can just fully remove it. It's enough to guard the Kconfigs with BT_AUDIO without also guarding the debug Kconfigs with that. 

Since everything is guarded by `BT_AUDIO`, how do you feel about using the `BT_AUDIO` prefix for everything, e.g. `BT_AUDIO_VCS`?

**Comment by asbjornsabo** [comment]
> > I think we should. For one thing, that is currently in Kconfig.baps, not in the main Kconfig. But it could probably just be totally removed?
> 
> I think we can just fully remove it. It's enough to guard the Kconfigs with BT_AUDIO without also guarding the debug Kconfigs with that.

Agree - will fix

> Since everything is guarded by `BT_AUDIO`, how do you feel about using the `BT_AUDIO` prefix for everything, e.g. `BT_AUDIO_VCS`?

Sounds good to me.  If you are OK, I can add that as part of this PR.

**Comment by Thalley** [comment]
> > Since everything is guarded by `BT_AUDIO`, how do you feel about using the `BT_AUDIO` prefix for everything, e.g. `BT_AUDIO_VCS`?
> 
> Sounds good to me. If you are OK, I can add that as part of this PR.

If that also warrants an API update, such that all `bt_vcs_*` is changed to `bt_audio_vcs_`, then I think it's better to push to a different PR.

**Review by Thalley — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Pull request merged**
