### PR TITLE
build: Simplify zephyr interface header dependency on generated files 

### PR DESCRIPTION
**Pull request by joerchan**
Simplify zephyr interface header dependencies on the generated files
offsets.h and version.h

All targets that depend on zephyr header files must depend on both
zephyr_interface and zephyr_generated_headers.

Missing zephyr_generated_headers leads to a rarely triggered
rare race-condititon for source files for these generated header files.

Example:
zephyr/include/zephyr/linker/linker-defs.h:26:10:
| fatal error: offsets.h: No such file or directory
|     26 | #include <offsets.h>
|        |          ^~~~~~~~~~~
|  compilation terminated.

Depending on zephyr_generated_headers target is harder than depending
on zephyr_interface because zephyr_generated_headers is a custom command
and must have been declared before adding the dependency.
Since zephyr_interface is an interface library it does not have this
order requirement.

Simplify this by adding the generated headers offsets.h and version.h
to the zephyr_interface target instead and remove the
zephyr_generated_interface target that app has no dependency on.

### CODE REVIEW

**Comment by joerchan** [comment]
I had misunderstood the original issue, it is not that the 'app' didn't have the dependency.
The target that was missing the dependency was an external built project, and it could not add the dependency on the generated headers because it was declared before the custom target.
This makes fixing the dependency harder.

**Review by andyross — APPROVED** [review]
Seems clean and correct.  I'll always +1 header dependency cleanup

**Review by nordicjm — APPROVED** [review]

**Review by tejlmand — CHANGES_REQUESTED** [review]
please note that similar PR has already been blocked downstream here: 
https://github.com/nrfconnect/sdk-zephyr/pull/1149#pullrequestreview-1413362576

It has already been discussed and investigated, but short story is that this is seen when using `ExternalProject_Add()`.
A bit of extra info on why this may not fully solve issue noticed can been understood from those discussions in CMake:
https://discourse.cmake.org/t/add-custom-command-with-target-dependency-doesnt-rebuild/7029
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8002/diffs

so before accepting this change, a bit more investigation is needed.

Also, afaik only arch should use the offsets.h, not libraries in general.
I know the use-case in `ExternalProject_Add()` is a bit special but we should be very careful before adjusting this in Zephyr itself.

**Comment by joerchan** [comment]
@tejlmand The interface headers include offsets.h, so all users of the zephyr headers depend on offsets.h
This includes all libraries built, which must depend on both zephyr_interface and zephyr_generated_headers.

Because zephyr_generated_headers is a custom target instead of an interface library like zephyr_interface it has different properties, which ExternalProjectAdd needs to work around in order to get the dependency right.

```
ExternalProject_Add(my_external_project
    ...
    DEPENDS          zephyr_interface zephyr_generated_headers
)
```

Fails with the following error:
```
get_property could not find TARGET zephyr_generated_headers.  Perhaps it
  has not yet been created.
```
So here we are dependent on the target already having been created.

The alternative solution is this:
```
ExternalProject_Add(my_external_project
    ...
    DEPENDS          zephyr_interface
)
add_dependencies(my_external_project zephyr_generated_headers)
```
I have already added this as a workaround downstream.

However with the change in this PR there is no longer a requirement to depend on zephyr_generated_headers.

ExternalProject is not a special use case, this is part of zephyrs example on how to solve the use case of an externally built library.
See  `samples/application_development/external_lib`, here if the mylib in that sample was depending on zephyr headers it would have the same problem that we are facing.

**Comment by tejlmand** [comment]
> @tejlmand The interface headers include offsets.h, so all users of the zephyr headers depend on offsets.h

that's not what I see when searching for `offsets.h` in the generated dep files for a simple project:
```
$ grep offsets.h (find . -name '*.d')
./zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/scb.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/exc_exit.S.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/isr_wrapper.S.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/swap_helper.S.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/prep_c.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h
./zephyr/arch/arch/arm/core/aarch32/mpu/CMakeFiles/arch__arm__core__aarch32__mpu.dir/arm_core_mpu.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/arch/arch/arm/core/aarch32/mpu/CMakeFiles/arch__arm__core__aarch32__mpu.dir/arm_mpu.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/lib/libc/common/CMakeFiles/lib__libc__common.dir/source/stdlib/malloc.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/time/gmtime.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdout/stdout_console.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj.d: /projects/github/ncs/zephyr/kernel/include/kernel_offsets.h \
./zephyr/kernel/CMakeFiles/kernel.dir/kheap.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h
./zephyr/kernel/CMakeFiles/kernel.dir/init.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h \
./zephyr/kernel/CMakeFiles/kernel.dir/xip.c.obj.d: /projects/github/ncs/zephyr/build/zephyr/include/generated/offsets.h

```

But please note that `zephyr_interface` is not called interface because it's the interface API for Zephyr but because it's a CMake interface library. A CMake interface library is used to populate properties for the build system and to pass those around, it is not suppose to create artifacts on the disk, ref: https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries
> An INTERFACE library target does not compile sources and does not produce a library artifact on disk.
> ...
> An interface library created with the above signature has no source files itself and is not included as a target in the generated buildsystem.

> Fails with the following error:

But that can be controlled by relocating the definition of that target. 

> However with the change in this PR there is no longer a requirement to depend on zephyr_generated_headers.

but it muddies what a CMake interface library is.
As well as it doesn't clearly considers the CMake issue linked on target dependency when multiple targets depends on a created file. This means there could still be concurrency issues lurking in the dark, which may suddenly appear when using another build tool (ninja vs. make) or different number of build jobs. 

So for the above and without a deeper investigation, then i'm reluctant to approve those changes for something that is working in general case, and because I believe there are better ways to handle this, for example to define the generated headers target earlier.
Also note that it was not ExternalProject itself that was a special use-case, but the fact that your ExternalProject is depending directly on `offsets.h`.

**Comment by joerchan** [comment]
>So for the above and without a deeper investigation, then i'm reluctant to approve those changes for something that is working in general case, and because I believe there are better ways to handle this, for example to define the generated headers target earlier.
Also note that it was not ExternalProject itself that was a special use-case, but the fact that your ExternalProject is depending directly on offsets.h.

The external project is not depending on `offsets.h`, it's depending on zephyr/ztest.h
This is the call-chain:
```
include/zephyr/app_memory/app_memdomain.h:9,
subsys/testsuite/ztest/include/zephyr/ztest_test_deprecated.h:16,
subsys/testsuite/ztest/include/zephyr/ztest_test.h:14,
subsys/testsuite/ztest/include/zephyr/ztest.h:51,
```
Which gives this error:
```
/home/joakim/repos/ncs/zephyr/include/zephyr/linker/linker-defs.h
zephyr/include/zephyr/linker/linker-defs.h:26:10:
| fatal error: offsets.h: No such file or directory
```

> but it muddies what a CMake interface library is.
As well as it doesn't clearly considers the CMake issue linked on target dependency when multiple targets depends on a created file. This means there could still be concurrency issues lurking in the dark, which may suddenly appear when using another build tool (ninja vs. make) or different number of build jobs.

The zephyr_interface library already serves this purpose for for various other generated header files though.
SYSCALL_LIST_H_TARGET
DRIVER_VALIDATION_H_TARGET
KOBJ_TYPES_H_TARGET

These are all custom commands or targets, that needs to be generated before users of the zephyr interface headers can be compiled.

I supposed you could keep all of these in zephyr_generated_headers and then have zephyr_interface depend on zephyr_generated_headers, or demand that all users of zephyr interface headers needs to depend on zephyr_generated_headers and link against zephyr_interface.
This would have to be properly documented though.

I think in the end having a single target to link or depend on is better, and makes future support cases or similar issues easier.

**Comment by joerchan** [comment]
@tejlmand  Can you have a look at my reply?

**Comment by harristomyx** [comment]
Hi @tejlmand, is there any updates on this issue or a recommended way forward?

**Pull request closed without merging**
