### PR TITLE
samples: remove broken hci_uart support for bbc_microbit

### PR DESCRIPTION
**Pull request by SebastianBoe**
The hci_uart sample implies that it supports bbc_microbit but in
reality it does not build due to a performance regression.

Removing Makefile and KConfig references to bbc_microbit will prevent
customers from expecting it to build.

Alternatively; we could open a performance regression bug.

Signed-off-by: Sebastian Boe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
Why isn't this building actually? what's the performance regression?

**Comment by SebastianBoe** [comment]
LINK    zephyr.lnk
/home/sebo/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/real-ld: zephyr_prebuilt.elf section `noinit' will not fit in region `SRAM'
/home/sebo/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/real-ld: section .intList VMA [0000000020004000,0000000020004093] overlaps section noinit VMA [0000000020003490,0000000020004737]
/home/sebo/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/real-ld: region `SRAM' overflowed by 1848 bytes
collect2: error: ld returned 1 exit status

Looks like something is using too much SRAM.

**Review by jhedberg — CHANGES_REQUESTED** [review]
I'd prefer if we fix the Kconfig parameters instead of disabling the support completely. It's perfectly possible to fit the app in the 16k RAM that the micro:bit has. In the worst case we e.g. just lower the max number of supported connections.

**Comment by SebastianBoe** [comment]
Fair enough. Will open a bugreport instead.

**Comment by carlescufi** [comment]
@SebastianBoe or just disable privacy, that should make it fit again

**Comment by carlescufi** [comment]
@SebastianBoe actually, now privacy is disabled for nRF51 targets, so this might work again magically :)

**Comment by jhedberg** [comment]
I just built the hci_uart sample successfully for the micro:bit, so I wonder what issue you had (custom Kconfig changes?)

**Comment by jhedberg** [comment]
Total RAM usage was 14640, which is well below the limit

**Comment by carlescufi** [comment]
@jhedberg maybe it's the recently disabled privacy for nRF51 targets

**Comment by jhedberg** [comment]
@carlescufi yep, that sounds like a likely cause

**Comment by SebastianBoe** [comment]
Ah, yeah, fixed again.

Since microbit is susceptible to performance regressions, 
would it make sense to add this platform to the hci_uart
 whitelist to catch the next performance regression?

**Comment by carlescufi** [comment]
@SebastianBoe yes, I'm all for doing that

**Pull request closed without merging**
