### PR TITLE
bluetooth: conn: Add getter for authentication callbacks

### PR DESCRIPTION
**Pull request by MarekPieta**
Change introduces getter API for the registered Bluetooth authentication callbacks.

### CODE REVIEW

**Comment by jori-nordic** [comment]
What's the use-case for that ?

**Comment by MarekPieta** [comment]
This feature can be useful when we want to temporarily override Bluetooth authentication callbacks and then at some point assign back the set of callbacks that was used before.

Example use-case could be Fast Pair which uses various device capabilities (various sets of authentication callbacks) depending on connected Central:
* if the connected Central is Fast Pair Seeker, the device reports `Display/YesNo` device capability and exchanges passkeys encrypted via GATT instead of displaying them to achieve MITM protection (feature specific to Fast Pair)
* for other Centrals, default bonding capabilities are used (i.e. they still can use Just Works pairing)

See https://developers.google.com/nearby/fast-pair/specifications/service/gatt for details.

New API allows to override callbacks when authenticating with Fast Pair Seeker and then assign back application's callbacks to report proper capabilities in case of other Centrals (user must ensure that various procedures are not handled simultaneously)

**Comment by Thalley** [comment]
> 



> This feature can be useful when we want to temporarily override Bluetooth authentication callbacks and then at some point assign back the set of callbacks that was used before.
> 
> Example use-case could be Fast Pair which uses various device capabilities (various sets of authentication callbacks) depending on connected Central:
> 
>     * if the connected Central is Fast Pair Seeker, the device reports `Display/YesNo` device capability and exchanges passkeys encrypted via GATT instead of displaying them to achieve MITM protection (feature specific to Fast Pair)
> 
>     * for other Centrals, default bonding capabilities are used (i.e. they still can use Just Works pairing)
> 
> 
> See https://developers.google.com/nearby/fast-pair/specifications/service/gatt for details.
> 
> New API allows to override callbacks when authenticating with Fast Pair Seeker and then assign back application's callbacks to report proper capabilities in case of other Centrals (user must ensure that various procedures are not handled simultaneously)

This doesn't sound like a good idea. There's a reason why the auth callbacks are a singleton; there should only be one owner of it so that the owner can properly implement the callbacks. 

Allowing other modules/applications to get the pointer and override the callbacks sounds like it may break stuff. 

For the use case you have, why can the owner of the auth callbacks not simply override it, instead of allowing some other module/application to override it?

**Comment by MarekPieta** [comment]
In general, user application manages Bluetooth authentication callbacks.
There is no need for an application to access set of callbacks that are specific to the Fast Pair, the application also does not know when should it overwrite authentication callbacks (it must be done during one of the GATT writes that is handled internally by Fast Pair GATT Service). Even if we notify application that the callbacks needs to be updated, the application has no idea if there are any ongoing pairing procedures (the same case as for the Service), so it would not prevent callback managing problems. I am also working on additional change that would prevent updating the authentication callbacks while there is ongoing SMP pairing to prevent issue mentioned above.

I assumed that most of the applications does not modify the callbacks in runtime - the callbacks registered by application in general refer to hardware capabilities of the device. I also state in documentation that module overrides authentication callbacks during the Fast Pair procedure to prevent confusion.

**Comment by MarekPieta** [comment]
The structure with authentication callbacks itself cannot be modified, so it would not be broken. New API allows to temporarily pass responsibility for pairing to another module. It allows to integrate some vendor-specific pairing procedures in the background, transparently to the application, which could be convenient for users.

**Comment by Thalley** [comment]
> The structure with authentication callbacks itself cannot be modified, so it would not be broken. New API allows to temporarily pass responsibility for pairing to another module. It allows to integrate some vendor-specific pairing procedures in the background, transparently to the application, which could be convenient for users (integration is simplified).

I think it's hard for me to understand how the `const struct bt_conn_auth_cb *` returned is to be used. 

Since it's `const` you can't overwrite the callbacks, and thus I don't really seem what value it adds for the caller. 

Perhaps it's easier to understand if you, together with this new API, also adds a use for it.

**Comment by MarekPieta** [comment]
A subsystem wants to temporarily override the Bluetooth authentication callbacks to handle pairing in a custom way for a given peer. The subsystem then needs to assign back the set of authentication callbacks that was previously registered by the application, so that application can handle subsequent pairings using application's callbacks.

**Comment by Thalley** [comment]
> A subsystem wants to temporarily override the Bluetooth authentication callbacks to handle pairing in a custom way for a given peer. The subsystem then needs to assign back the set of authentication callbacks that was previously registered by the application, so that application can handle subsequent pairings using application's callbacks.

If I understand you correct, what you want to do is that you want to call `bt_conn_auth_cb_get`, and then call `bt_conn_auth_cb_register(NULL)` to unregister the application callbacks, call `bt_conn_auth_cb_register` with your own callback for Fast Pair, unregister your own callback with `bt_conn_auth_cb_register(NULL)` and then finally re-register the applications callbacks again? 

So
```c
const struct bt_conn_auth_cb fast_pair_cb;
const struct bt_conn_auth_cb *app_cb = bt_conn_auth_cb_get();
bt_conn_auth_cb_register(NULL);
bt_conn_auth_cb_register(&fast_pair_cb);
/* do fast pair */
bt_conn_auth_cb_register(NULL);
bt_conn_auth_cb_register(app_cb);
```
?

**Comment by MarekPieta** [comment]
@Thalley, correct.
With the current API, we will have to do it in this way. Maybe we could allow to simply override the authentication callbacks at some point, so we can simplify API calls a bit.

**Comment by kapi-no** [comment]
This feature is also necessary for the Find My use case when it is used with another Bluetooth application on the same device. Please see my old issue description:

https://github.com/zephyrproject-rtos/zephyr/issues/38336

Please note that this change is an intermediate step to a proper way of handling both use cases. Ideally, we want to have or implement an API that allows choosing the pairing method for each connected peer. 

With this change, we can avoid importing the Bluetooth structure for authentication callbacks into the user application

```
/* Import the authentication callback context
 * from zephyr/subsys/bluetooth/host/conn.c
 */
extern const struct bt_conn_auth_cb *bt_auth;
```

and use standard Bluetooth APIs to implement the necessary workarounds.

**Comment by sjanc** [comment]
I have mixed feelings about this approach,  auth callbacks are global and this may affect device (app) in unexpected way, especially if more devices are connected.

My guts tell me that this kind of features (eg fast pair) should be handled with-in stack..

**Comment by MarekPieta** [comment]
@sjanc, I think you are right that we may need a mechanism to control access to the authentication callbacks (to prevent unexpected behaviors). Adding parts of the code responsible for some vendor-specific pairing operations directly into lower layers of the Bluetooth stack is not best idea I think. In my opinion, we should focus on improving existing bt_auth_cb API to allow using it safely for various vendor-specific procedures.

**Comment by MarekPieta** [comment]
@sjanc, @Thalley, I understand your concerns and I would also want to eventually make Fast Pair's authentication callbacks used only for a given connection (that would allow us to avoid problems when various pairing flows are happening simultaneously).

Even with auth callbacks defined per connection, we will need to make sure that we do not swap the set of auth callbacks used by the SMP in the middle of pairing (so in case pairing was already started, we should not be able to set callbacks for a connection in the application; we need to wait until pairing is finished). I decided to limit my first PR to cover this part:
https://github.com/zephyrproject-rtos/zephyr/pull/46702 
Please review, I will introduce further changes in subsequent PRs.

**Comment by Thalley** [comment]
> @sjanc, @Thalley, I understand your concerns and I would also want to eventually make Fast Pair's authentication callbacks used only for a given connection (that would allow us to avoid problems when various pairing flows are happening simultaneously).
> 
> Even with auth callbacks defined per connection, we will need to make sure that we do not swap the set of auth callbacks used by the SMP in the middle of pairing (so in case pairing was already started, we should not be able to set callbacks for a connection in the application; we need to wait until pairing is finished). I decided to limit my first PR to cover this part: #46702 Please review, I will introduce further changes in subsequent PRs.

I personally think that the idea of getting, overwriting and using the application-registered auth callbacks is fundamentally flawed, regardless of how many checks we implement. I also do not see the need to use those callbacks for something that isn't placed in the application, and would rather use an internal API.

Can you elaborate on why you think we should overwrite the auth callbacks?

**Comment by jhedberg** [comment]
> I personally think that the idea of getting, overwriting and using the application-registered auth callbacks is fundamentally flawed, regardless of how many checks we implement. I also do not see the need to use those callbacks for something that isn't placed in the application, and would rather use an internal API.

I agree. I think we need to brainstorm a bit more about the desired use cases and possible solutions for enabling them.

**Comment by MarekPieta** [comment]
I understand that approach with introducing getter is not accepted, I will close this PR eventually. After discussion, I think I could introduce an API to register the authentication callbacks per connection. If set, the per-connection callbacks would be used instead of global callbacks for the given connection. This approach was suggested also by @sjanc and I think it's a good and quite flexible solution. It allows to easily integrate vendor-specific pairing flows that happen without application's interaction (also if the vendor-specific procedures are implemented outside Zephyr). I would say that the vendor-specific pairing flow handling is not part of Bluetooth stack (so I would prefer to avoid using internal Bluetooth stack API), it's more like a separate subsystem that should use public Bluetooth API.
What's your opinion on this @Thalley, @jhedberg? 

Please keep in mind that even if we decide to introduce the per-connection callbacks, we need to ensure that we are not updating authentication callbacks that are currently in use for a pairing). The https://github.com/zephyrproject-rtos/zephyr/pull/46702 only introduces a set of additional checks that prevent modifying authentication callbacks while they are in use. Modifying callbacks while pairing is ongoing may result in unexpected behavior (with my change, the function would simply return an error code to the application which prevents strange failures). If callbacks are not in use, the application could still update them.

**Comment by Thalley** [comment]
> I understand that approach with introducing getter is not accepted, I will close this PR eventually. After discussion, I think I could introduce an API to register the authentication callbacks per connection. If set, the per-connection callbacks would be used instead of global callbacks for the given connection. This approach was suggested also by @sjanc and I think it's a good and quite flexible solution. It allows to easily integrate vendor-specific pairing flows that happen without application's interaction (also if the vendor-specific procedures are implemented outside Zephyr). I would say that the vendor-specific pairing flow handling is not part of Bluetooth stack (so I would prefer to avoid using internal Bluetooth stack API), it's more like a separate subsystem that should use public Bluetooth API. What's your opinion on this @Thalley, @jhedberg?

I think I would need to see a proposed API before I fully understand how a per-connection callback would be a solution to this. 

> I would say that the vendor-specific pairing flow handling is not part of Bluetooth stack (so I would prefer to avoid using internal Bluetooth stack API), it's more like a separate subsystem that should use public Bluetooth API.

Agreed, they should not use internal BT APIs. If, however, this is really something that is vendor specific and/or outside the scope of the BT subsystem, it sounds like something the application should handle. I am not a bit fan of inter-subsystem communication without involving the application at all.

**Comment by MarekPieta** [comment]
Hi @Thalley, @jhedberg, @sjanc 
Proposed implementation of per-connection authentication callbacks is available here: https://github.com/zephyrproject-rtos/zephyr/pull/46789. I think we can start review and discussion.

**Comment by Thalley** [comment]
> Hi @Thalley, @jhedberg, @sjanc Proposed implementation of per-connection authentication callbacks is available here: #46789. I think we can start review and discussion.

Took a quick look at it. While the PR seem sound, I still fail to see how this will provide what you want for fast-pair. Even for connection-based auth, don't you still need to overwrite the auth_cbs for your use case?

**Comment by MarekPieta** [comment]
@Thalley, the new API allows us to overlay the authentication callbacks for a given connection which is even easier to use. As soon as device realizes that Fast Pair procedure should be used for a given conn (when device receives predefined GATT write), the device can update authentication callbacks for a given connection calling `bt_conn_auth_cb_register_conn` which would result in reporting expected capabilities during pairing (this would not affect other connections too). If the peer is Fast Pair Seeker, then GATT write must occur before pairing anyway.

**Comment by Thalley** [comment]
> @Thalley, the new API allows us to overlay the authentication callbacks for a given connection which is even easier to use. As soon as device realizes that Fast Pair procedure should be used for a given conn (when device receives predefined GATT write), the device can update authentication callbacks for a given connection calling `bt_conn_auth_cb_register_conn` which would result in reporting expected capabilities during pairing (this would not affect other connections too). If the peer is Fast Pair Seeker, then GATT write must occur before pairing so device would always use proper auth callbacks.

Right, but we are still back to doing
```c
const struct bt_conn_auth_cb fast_pair_cb;
const struct bt_conn_auth_cb *app_cb = bt_conn_auth_cb_get();
bt_conn_auth_cb_register(NULL);
bt_conn_auth_cb_register(&fast_pair_cb);
/* do fast pair */
bt_conn_auth_cb_register(NULL);
bt_conn_auth_cb_register(app_cb);
```

except just with the new API for a specific connection, right? 

I may have trouble wrapping my head around the use case until I actually see it being used.

**Comment by MarekPieta** [comment]
> But if the application has also called `bt_conn_auth_cb_register_conn`, then the Fast Pair Service will need to overwrite those, right?
> 
> It sounds more like (to me) that we need to add a fast-pair callback in the struct, and then have the service communicate with the application (that owns the callback), and do it via the application.

@Thalley, if application calls `bt_conn_auth_cb_register_conn` for a given connection, then calling the function for the second time will result in error code being reported. The callbacks would not be overwritten.

The assumption is that in most cases global callbacks would still be used by the application for regular pairing. New per-connection API would be used only for some vendor-specific pairing procedures (some of them may be even handled by application). If more than one vendor-specific procedure is triggered simultaneously, the device would not be able to react properly (probably the various procedures would contradict each other). In that case user will clearly see error code returned while trying to update the callbacks for the second time, so that nothing would break.

**Comment by Thalley** [comment]
> New per-connection API would be used only for some vendor-specific pairing procedures (some of them may be even handled by application).

If you are adding it as a public API, then you are inviting applications to use it. You should not expect an application to _not_ use a public API because you want to use it for a stack procedure. That's why I suggested a internal API for this sort of thing. 

In other words, adding the per-connection auth cb API you are simply reducing the risk of issues, not eliminating them.

**Comment by MarekPieta** [comment]
> If you are adding it as a public API, then you are inviting applications to use it. You should not expect an application to _not_ use a public API because you want to use it for a stack procedure. That's why I suggested a internal API for this sort of thing.
> 
> In other words, adding the per-connection auth cb API you are simply reducing the risk of issues, not eliminating them.

@Thalley, I think that vendor-specific procedures are in general not part of the Bluetooth stack, so they should not use internal API. 

Calling `bt_conn_auth_cb_register_conn` multiple times would just end with an error code. It should not break anything, the pairing would just follow the procedure that was triggered as the first one. Previous approach with getter could actually lead to unexpected behavior, because it allowed to swap used auth callback in the middle of pairing (new per-connection auth cb API prevents this).

If a subsystem uses `bt_conn_auth_cb_register_conn` API, then application integrator must be aware of this fact (the subsystem must inform about this in documentation). Alternatively such subsystem could expose API to notify application that given vendor-specific pairing procedure is about to start. Then application could even decide if the procedure should be started or rejected (such API may be added to our Fast Pair integration if needed).

Still, it may be a good idea to explain in docs that the global callbacks should be used to represent device's hardware capabilities and per-connection callbacks are meant to be used for some vendor-specific pairing flows. We should explicitly mention the limitations too.

**Comment by MarekPieta** [comment]
> At this point I don't have much more feedback before I can see a use case for it. To me it sounds like this is something that should be handle by the application, and not inter-subsystem communication (that also rely on vendor specific things), especially if it also relies on the application _not_ using a public API that is available to them.

For use-case example, see the Fast Pair subsystem in the nRF Connect SDK: https://github.com/nrfconnect/sdk-nrf/tree/main/subsys/bluetooth/services/fast_pair

While GATT service implementation (`fp_gatt_service.c`) handles Key based pairing request, `handle_key_based_pairing_req` is called. The function uses `fp_auth_start` (defined in `fp_auth.c`) to update authentication callbacks. Because of current API limitations, we need to use `extern const struct bt_conn_auth_cb *bt_auth;` to update callbacks in the `fp_auth.c` and user needs to ensure that there is only one ongoing pairing at a time (since we update callbacks from BT RX thread context and do not trigger pairing request from application, the procedure would be properly handled using Fast Pair's auth callbacks).

To improve stability of our solution, avoid mentioned limitations and make sure that callbacks would not be overwritten while pairing is ongoing, I would want to make `fp_auth_start` call the new per-connection API to update the auth callbacks only for a given connection. Please keep in mind that even if the callbacks cannot be updated, then the error code will be propagated and Fast Pair pairing procedure would be rejected.

I could consider to involve application before calling per-connection API in `fp_auth.c`. For example, the service could ask application for consent before it updates authentication callbacks. I would prefer to make this feature optional, because none of our current use-cases needs it and enabling it complicates integration a bit.

**Comment by Thalley** [comment]
> For use-case example, see the Fast Pair subsystem in the nRF Connect SDK: https://github.com/nrfconnect/sdk-nrf/tree/main/subsys/bluetooth/services/fast_pair
> 
> While GATT service implementation (`fp_gatt_service.c`) handles Key based pairing request, `handle_key_based_pairing_req` is called. The function uses `fp_auth_start` (defined in `fp_auth.c`) to update authentication callbacks. Because of current API limitations, we need to use `extern const struct bt_conn_auth_cb *bt_auth;` to update callbacks in the `fp_auth.c` and user needs to ensure that there is only one ongoing pairing at a time (since we update callbacks from BT RX thread context and do not trigger pairing request from application, the procedure would be properly handled using Fast Pair's auth callbacks).
> 
> To improve stability of our solution, avoid mentioned limitations and make sure that callbacks would not be overwritten while pairing is ongoing, I would want to make `fp_auth_start` call the new per-connection API to update the auth callbacks only for a given connection. Please keep in mind that even if the callbacks cannot be updated, then the error code will be propagated and Fast Pair pairing procedure would be rejected.
> 
> I could consider to involve application before calling per-connection API in `fp_auth.c`. For example, the service could ask application for consent before it updates authentication callbacks. I would prefer to make this feature optional, because none of our current use-cases needs it and enabling it complicates integration a bit.

Thanks for sharing. 

I took a look at the fast pair service implementation, and I can see why you'd want this change. 

Based on the suggested API change, and the use case of it, my thoughts are still that
A) Temporarily overwriting a application (singleton) callback is a poor design (although I do not have a better solution for it at this point)
B) The entire `fp_auth` part of the fast pair service implementation seem to me to be better placed in the application, rather than the stack. IMO the implementation should be simplified greatly (and serve as a easy way to setup the service and parse the read/write requests properly), and have an API towards the application to actual perform the pairing. 

The API change suggested is only relevant due to how fast pair has been implemented, but IMO the way fast pair has been implemented is more similar to an application than a service. I think that connection handling, pairing, etc. is better handled in the application, than the stack. I 

So those are my thoughts, and we may yet be able to find a solution to keep your fast pair implementation as is with some simple API change, but I still think that overwriting the `struct bt_auth` (even just for specific connections) will be a poor choice, and that an API between the service and the application will be better.

**Comment by carlescufi** [comment]
@MarekPieta ping

**Comment by MarekPieta** [comment]
Hi @carlescufi @Thalley 
To summarize. I think there are 2 separate things to discuss here:

- Integrating Fast Pair Service with application
We may consider providing additional API to let application decide about pairing flow. I think we could make it as optional feature and by default service could simply use Fast Pair flow if requested by Seeker. That keeps the integration simple by default and allows for more detailed control if needed.

- Providing modified bonding capabilities to the connected Fast Pair Seeker
Service (or application) needs API from the Bluetooth stack to modify bonding capabilities provided for a given connection. The capabilities must be updated after connection is established (when Seeker writes to Key-based Pairing Fast Pair GATT characteristic - that's the moment when we know that Fast Pair pairing flow will be used). It would be great if we could finish review of new API allowing to register auth callbacks per connection (https://github.com/zephyrproject-rtos/zephyr/pull/46789). The PR seems to fix other use-cases too (e.g. Kamil's request: https://github.com/zephyrproject-rtos/zephyr/issues/38336). The introduced atomic pointer allows us to avoid possible races when accessing the authentication callbacks after connection is established. If callbacks cannot be updated (SMP security has already started), proper error code is returned (we can't do anything more at this point). Users are still able to safely rely on the global callbacks using old API, so backwards compatibility is not broken too.
Of course if there would be other propositions I would be glad to discuss them and compare pros and cons. Approach could still be changed.

**Comment by MarekPieta** [comment]
HI @Thalley 
The existing API for Bluetooth authentication callbacks does not allow to use different callbacks for different connections (the set of callbacks is global). There is no access protection, so caller may modify the callbacks while security in SMP is ongoing too (callbacks can be silently updated, no error code would be returned). Because of this, we need to expand the API to properly support Fast Pair use-case anyway (I am already convinced that per-conn authentication callbacks proposed here: https://github.com/zephyrproject-rtos/zephyr/pull/46789 is a better approach than simply introducing a getter - this PR will eventually be closed).

Could you explain how could involving application allow us to avoid expanding Bluetooth authentication API? I think the API expansion is needed no matter if application or service would handle authentication task.

**Comment by Thalley** [comment]
> Could you explain how could involving application allow us to avoid expanding Bluetooth authentication API? I think the API expansion is needed no matter if application or service would handle authentication task (it's why I wanted to separate these tasks).

From what I can tell, it would be possible to create an API to the Fast Pair service, such that the Fast Pair communicates with the application w.r.t. the bonding authentication callbacks. So basically what you are trying to achieve by overwriting the `auth_cb` can be done by exposing an API for the Fast Pair service instead.

**Comment by MarekPieta** [comment]
> Not sure I follow this part - Why do we need to modify the structure at all?

When pairing is started, SMP reports device's bonding capabilities. Current SMP implementation generates the capabilities relying on callbacks that are available in `bt_auth` (e.g. if `passkey_display` callback is not NULL, it assumes that device is capable to display passkey etc.). This approach would no longer be valid for a device that changes its bonding capabilities in runtime assuming that we rely on one set of callbacks registered by application (we cannot modify the authentication callback structure after it's registered). To work around it, we would need an additional callback allowing application to properly report current bonding capabilities.

**Comment by Thalley** [comment]
> we cannot modify the authentication callback structure after it's registered

Why not? 

```c
static void auth_passkey_display(struct bt_conn *conn, unsigned int passkey)
{
	char addr[BT_ADDR_LE_STR_LEN];

	bt_addr_le_to_str(bt_conn_get_dst(conn), addr, sizeof(addr));

	printk("Passkey for %s: %06u\n", addr, passkey);
}
```

```c
auth_cb.passkey_display = auth_passkey_display;
err = bt_conn_auth_cb_register(&auth_cb);

auth_cb.passkey_display = NULL; /* deregister passkey_display callback at runtime */
```
is possible

**Comment by MarekPieta** [comment]
> I get what you mean, but I don't think it's unreasonable for an application to modify its source code after enabling a feature such as Fast Pair

I would not say it's unreasonable, but maybe we could keep the integration simpler.
In most use-cases, the application would only register global authentication capabilities and service could overlay the authentication callbacks for given connection if needed (on GATT write to Fast Pair characteristic). That may not involve application at all (I could introduce an optional callback for application to reject pairing using Fast Pair procedure if needed). Then basic Service integration would be simplified to enabling a Kconfig and more advanced use-cases could still handle the authentication callbacks in a dedicated way defined by integrator (no one forbids integrator to handle everything in a single global set of authentication callbacks).

**Comment by MarekPieta** [comment]
> I agree with that, and that the callbacks should only be modified when safe.

Definitely, it's why I proposed to even use atomic pointer in the SMP implementation. That allows us to safely support multiple, various sets of authentication callbacks (one set per pairing flow). I would prefer to swap whole set of callbacks instead of modifying only a single callback (Zephyr checks that callbacks that are about to be registered are valid).  

I understand that authentication callbacks are currently considered a singleton (they are meant to be related to HW IO capabilities that do not change in runtime). This limitation blocks proper implementation for the Fast Pair (and other vendor-specific pairing flows), it's why I propose API extension. Please review the solution proposed in the PR: https://github.com/zephyrproject-rtos/zephyr/pull/46789.

**Pull request closed without merging**
