### PR TITLE
Revert PM power state constraint code

### PR DESCRIPTION
**Pull request by gmarull**
PR was merged without any reviews from device model maintainer. I don't think changes in device.h are acceptable, a better solution is required to not pollute device.h with PM-related code. PM code in device.h was removed a long time ago to keep responsibilities clear, that PR seems to go against such principles by introducing unnecessary coupling again.

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]
I missed the original too.
This was not well thought trough. If it is a very specific use case, why generalizing this on all devices?

There is still time to revert this before this becomes a bulky legacy.

**Comment by ceolin** [comment]
> I missed the original too. This was not well thought trough. If it is a very specific use case, why generalizing this on all devices?

This is optional and depends on device, e.g it is in a power rail that will be power down when the SoC change states.
It is not an unusual use case, there are many drivers that set power state constraints to prevent the SoC to go to certain power states and it is hardcoded what makes them less portable.
 
> 
> There is still time to revert this before this becomes a bulky legacy.

The implementation is not really important and can change, only the API / functionality needs to be preserved.

**Comment by ceolin** [comment]
PM code in device.h was removed a long time ago to keep responsibilities clear, that PR seems to go against such principles by introducing unnecessary coupling again.

That is not entirely true, device  has reference to  pm (https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/device.h#L429) and it is part of device definition which is not much different from these changes.

That's said, that is not device power management, a device may need / use it without even support device power management since it is related with system power management.

Please what is the biggest problem with current implementation ? Be defined in all devices when the feature is enabled ? or just because it is define in the device struct ?
It can't be added in the power management struct because it is not part of device power management.

**Review by ceolin — CHANGES_REQUESTED** [review]
The feature was reviewed following all required process. Removing is not the right thing to do IMHO, if there is a better way we should work on it and not removing.

**Comment by nashif** [comment]
@gmarull  what are you expecting the TSC to do here? If this is an escalation, please follow the process outlined [here](https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#pr-technical-escalation) before escalating to the TSC: 

- I do not see any attempt to resolve any technical differences in the PR/issue or other forums.

**Comment by ceolin** [comment]
It would be nice to have comments replied otherwise there is no review / discussion. It shouldn't be an one way conversation :/

**Comment by ceolin** [comment]
I have a prototype removing it from `device.h`. https://github.com/zephyrproject-rtos/zephyr/pull/75003

**Comment by gmarull** [comment]
> @gmarull what are you expecting the TSC to do here? If this is an escalation, please follow the process outlined [here](https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#pr-technical-escalation) before escalating to the TSC:
> 
> * I do not see any attempt to resolve any technical differences in the PR/issue or other forums.

Just flagged as TSC because no new features are allowed now, so I thought it would require "special" approvals.

**Comment by gmarull** [comment]
> The feature was reviewed following all required process. Removing is not the right thing to do IMHO, if there is a better way we should work on it and not removing.

I'm fine with an alternative solution as shown in #75003. I opened this PR to propose a revert if none was provided before the release. As explained in there, the main concerns from a device model perspective are:

- Unnecessary coupling between device model and PM.
- struct device will get bigger for every device when the feature is enabled, even if the device doesn't require the feature. This used to be the same for device PM but was fixed a long time ago by struct device just holding a pointer to resources allocated by each device, based on its requirements.

While the PR followed the process, it introduced non-trivial changes to device.h (e.g. modify the struct device layout). This requires some extra approvals IMHO, even if I wasn't the assignee. Processes will never be perfect, people need to make sure to tag/ping relevant people for these kinds of changes, and accept a potential revert or breaking change if this does not happen.

**Comment by aescolar** [comment]
> Just flagged as TSC because no new features are allowed now, so I thought it would require "special" approvals.

Just for info: The TSC needs to get involved only when such a PR is ready to merge otherwise. (meaning it passes CI, it has the appropriate approvals, and so forth)

**Review by fabiobaltieri — APPROVED** [review]

**Comment by ceolin** [comment]
> > The feature was reviewed following all required process. Removing is not the right thing to do IMHO, if there is a better way we should work on it and not removing.
> 
> I'm fine with an alternative solution as shown in #75003. I opened this PR to propose a revert if none was provided before the release. As explained in there, the main concerns from a device model perspective are:
> 
>     * Unnecessary coupling between device model and PM.

That is open to discuss since that is an information that device wants to know. The proposed solution is moving it way from here in the cost of having to lookup a list to find a device constrainsts.

> 
>     * struct device will get bigger for every device when the feature is enabled, even if the device doesn't require the feature. This used to be the same for device PM but was fixed a long time ago by struct device just holding a pointer to resources allocated by each device, based on its requirements.

That is true, but it works exactly the same way you are saying was fixed a long time ago, holding a reference to an external object. It is not like the list of dependencies are part of the struct.

> 
> 
> While the PR followed the process, it introduced non-trivial changes to device.h (e.g. modify the struct device layout). This requires some extra approvals IMHO, even if I wasn't the assignee. Processes will never be perfect, people need to make sure to tag/ping relevant maintainers for these kinds of changes, and accept a potential revert or breaking change if this does not happen.

@gmarull  you were in the review list since the beginning and the pr was discussed for a long time, anyways I don't want to go this path ...

Honestly, I think the other solution is fine for the problem it is addressing but removing the whole feature without caring with who needs it and without asking for changes or suggestions  .... amuses me.

**Comment by gmarull** [comment]
> > > The feature was reviewed following all required process. Removing is not the right thing to do IMHO, if there is a better way we should work on it and not removing.
> > 
> > 
> > I'm fine with an alternative solution as shown in #75003. I opened this PR to propose a revert if none was provided before the release. As explained in there, the main concerns from a device model perspective are:
> > ```
> > * Unnecessary coupling between device model and PM.
> > ```
> 
> That is open to discuss since that is an information that devices want to know. The proposed solution is moving it way from here in the cost of having to lookup a list to find a device constrainsts.

This is really up to you, I, personally, don't care about PM anymore, but I do about device.h, and as a maintainer of device.h I don't find the current solution acceptable. There are likely other solutions, like re-using struct pm_device already referenced in struct device. After all, you're storing per-device information.

> 
> > ```
> > * struct device will get bigger for every device when the feature is enabled, even if the device doesn't require the feature. This used to be the same for device PM but was fixed a long time ago by struct device just holding a pointer to resources allocated by each device, based on its requirements.
> > ```
> 
> That is true, but it works exactly the same way you are saying was fixed a long time ago, holding a reference to an external object. It is not like the list of dependencies are part of the struct.
> 
> > While the PR followed the process, it introduced non-trivial changes to device.h (e.g. modify the struct device layout). This requires some extra approvals IMHO, even if I wasn't the assignee. Processes will never be perfect, people need to make sure to tag/ping relevant maintainers for these kinds of changes, and accept a potential revert or breaking change if this does not happen.
> 
> @gmarull you were in the review list since the beginning and the pr was discussed for a long time, anyways I don't want to go this path ...
> 
> Honestly, I think the other solution is fine for the problem it is addressing but removing the whole feature without caring with who needs it and without asking for changes or suggestions .... amuses me.

Zephyr has a wide audience, and core areas should be well-maintained. If a core area is touched in a non-trivial way and the process doesn't enforce reviews, it should be PR author responsibility to ensure it gets proper reviews, or, accept a potential revert until the feature is iterated to an acceptable state.

**Comment by ceolin** [comment]
> > > > The feature was reviewed following all required process. Removing is not the right thing to do IMHO, if there is a better way we should work on it and not removing.
> > > 
> > > 
> > > I'm fine with an alternative solution as shown in #75003. I opened this PR to propose a revert if none was provided before the release. As explained in there, the main concerns from a device model perspective are:
> > > ```
> > > * Unnecessary coupling between device model and PM.
> > > ```
> > 
> > 
> > That is open to discuss since that is an information that devices want to know. The proposed solution is moving it way from here in the cost of having to lookup a list to find a device constrainsts.
> 
> This is really up to you, I, personally, don't care about PM anymore, but I do about device.h, and as a maintainer of device.h I don't find the current solution acceptable. There are likely other solutions, like re-using struct pm_device already referenced in struct device. After all, you're storing per-device information.

That is not part of device power management, that is why it was not stored in `struct pm_device`. A device may need it without having device power management enabled.

> 
> > > ```
> > > * struct device will get bigger for every device when the feature is enabled, even if the device doesn't require the feature. This used to be the same for device PM but was fixed a long time ago by struct device just holding a pointer to resources allocated by each device, based on its requirements.
> > > ```
> > 
> > 
> > That is true, but it works exactly the same way you are saying was fixed a long time ago, holding a reference to an external object. It is not like the list of dependencies are part of the struct.
> > > While the PR followed the process, it introduced non-trivial changes to device.h (e.g. modify the struct device layout). This requires some extra approvals IMHO, even if I wasn't the assignee. Processes will never be perfect, people need to make sure to tag/ping relevant maintainers for these kinds of changes, and accept a potential revert or breaking change if this does not happen.
> > 
> > 
> > @gmarull you were in the review list since the beginning and the pr was discussed for a long time, anyways I don't want to go this path ...
> > Honestly, I think the other solution is fine for the problem it is addressing but removing the whole feature without caring with who needs it and without asking for changes or suggestions .... amuses me.
> 
> Zephyr has a wide audience, and core areas should be well-maintained. If a core area is touched in a non-trivial way and the process doesn't enforce reviews, it should be PR author responsibility to ensure it gets proper reviews, or, accept a potential revert until the feature is iterated to an acceptable state.

**Comment by nashif** [comment]
> Zephyr has a wide audience, and core areas should be well-maintained. If a core area is touched in a non-trivial way and the process doesn't enforce reviews, it should be PR author responsibility to ensure it gets proper reviews, or, accept a potential revert until the feature is iterated to an acceptable state.

please do not make up rules, it is the responsibility of the maintainer of an area to monitor changes to that area and review them. In this case, you were added as a reviewer and had plenty of time to take a look at the change. It is as simple as searching for PRs labeled with the areas you maintain on a regular basis, for example this [filter](https://github.com/zephyrproject-rtos/zephyr/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+label%3A%22area%3A+Device+Model%22).  And that if as a maintainer you did not get the notification or if you have not noticed the change coming in....

Putting the responsibility on the submitter to go after each reviewer just does not work and does not scale.

Please do not use reverts as a way to get things resolved, this does not always work and in many cases can be very counter-productive. In this case, file a bug, make it a blocker or whatever and negotiate the best way forward through productive discussions. 
Nobody was acting  maliciously here or trying to work-around the system. Like 100s of PRs every week, reviews are not done in time or things fall down the crack and we have to learn how to deal with that.

Here is one way this could be avoid in the future, will cover similar cases, but not all of them. https://github.com/zephyrproject-rtos/zephyr/pull/75016

**Comment by gmarull** [comment]
> > Zephyr has a wide audience, and core areas should be well-maintained. If a core area is touched in a non-trivial way and the process doesn't enforce reviews, it should be PR author responsibility to ensure it gets proper reviews, or, accept a potential revert until the feature is iterated to an acceptable state.
> 
> please do not make up rules,

I’m not making any rules, just applying common sense, based on what I see happening in other areas. 

 it is the responsibility of the maintainer of an area to monitor changes to that area and review them. In this case, you were added as a reviewer and had plenty of time to take a look at the change. It is as simple as searching for PRs labeled with the areas you maintain on a regular basis, for example this [filter](https://github.com/zephyrproject-rtos/zephyr/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+label%3A%22area%3A+Device+Model%22). And that if as a maintainer you did not get the notification or if you have not noticed the change coming in....
> 
> Putting the responsibility on the submitter to go after each reviewer just does not work and does not scale.
> 

Larger projects than Zephyr seem to succeed with less rules, but they tend to have a stronger core team IMHO.

> Please do not use reverts as a way to get things resolved, this does not always work and in many cases can be very counter-productive. In this case, file a bug, make it a blocker or whatever and negotiate the best way forward through productive discussions. Nobody was acting maliciously here or trying to work-around the system. Like 100s of PRs every week, reviews are not done in time or things fall down the crack and we have to learn how to deal with that.
> 

Reverts are a way to remove features that were not reviewed properly or prematurely merged, so a new iteration can be re-introduced later. A quick fix is also fine, I never opposed to that. 

> Here is one way this could be avoid in the future, will cover similar cases, but not all of them. #75016

I doubt more rules will avoid issues like this in the future. It’s just too easy to get PRs touching multiple areas merged.

**Comment by gmarull** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/75003 merged

**Pull request closed without merging**
