### PR TITLE
cmake: Toolchain abstraction: Introduce toolchain_ld_userspace

### PR DESCRIPTION
**Pull request by mped-oticon**
What we do to build for CONFIG_USERSPACE is heavily GNU-specific (both linker and binutils) and involves several python tools (that are also GNU reliant). 
This is also quite noisy in the root CMakeLists.txt file.

This is Part 1 of 2, in abstracting this userland cmake code.

No functional change expected.

This is motivated by the wish to abstract Zephyr's usage of toolchains,
permitting non-intrusive porting to other (commercial) toolchains.

Signed-off-by: Mark Ruvald Pedersen <mped@oticon.com>

-------------

Part of #16031

### CODE REVIEW

**Comment by marc-hb** [comment]
Could you share a (work in progress) branch with future commits showing where this is going? I mean just a personal branch, no "stacked PRs". Curious about gen_priv_stacks among others.

I fetched `refs/pull/15936/head` and ran `git diff HEAD~ -C05 -U20` which proved in a confusing yet useful way that not even a single byte of whitespace was harmed in the move.

**Comment by andrewboie** [comment]
The privilege stack stuff should be moved too, if you're going to move this.

There's also TONS of things in tree which assume the use of the GNU linker, curious why you're focusing on the userspace stuff for now. This patch by itself doesn't solve anything.

**Comment by mped-oticon** [comment]
> Could you share a (work in progress) branch with future commits showing where this is going? I mean just a personal branch, no "stacked PRs". Curious about gen_priv_stacks among others.

Sure here is my draft branch: https://github.com/mped-oticon/zephyr/tree/master-tc-linker 
gen_priv_stacks etc is also moved there.
I want to upstream this in small steps as that seems to work better, process-wise.
Bintools (objdump, ranlib, etc) will also have to be abstracted.

> I fetched `refs/pull/15936/head` and ran `git diff HEAD~ -C05 -U20` which proved in a confusing yet useful way that not even a single byte of whitespace was harmed in the move.

For me, I'd like to have these abstraction commits introduce no functional change. Then cleanup is a another commit or PR -- this, hopefully will make the PRs more acceptable.

**Comment by mped-oticon** [comment]
> The privilege stack stuff should be moved too, if you're going to move this.
> 
> There's also TONS of things in tree which assume the use of the GNU linker, curious why you're focusing on the userspace stuff for now. This patch by itself doesn't solve anything.

Yep. It will be moved too.

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
IMHO we are placing the portability abstraction API too high up in the stack.

For instance, we should have a portable API for renaming sections, as we do here:

https://github.com/zephyrproject-rtos/zephyr/pull/15936/files#diff-af3b638bc2a3e6c650974192a53c7291L1001

then we could keep the business logic of what sections should be renamed in portable core CMake code and keep the business logic of how to rename a section in the portability abstraction implementations.

Otherwise we would be duplicating code that has nothing to do with toolchain-specifics. This will not be maintainable.

**Comment by mped-oticon** [comment]
Will create new, finer-grained, PR where

1. ELF section renaming is abstracted.
2. Hash-table generation is abstracted (not everybody can use gperf).
3. The two python scripts (dwarf parser and gperf post-processing) are abstracted (these scripts assume GNU ld).
4. The common properties/dependencies/libraries are kept in root CMakeLists.txt

@SebastianBoe  Any thoughts on the above proposal?

**Comment by SebastianBoe** [comment]
This sounds much more like an approach we can maintain over time.

**Comment by marc-hb** [comment]
> Will create new, finer-grained, PR where

See #16031 for follow-ups.

(Yes that reference is also at the top, I found it there eventually / too late. I was being "too chronological")

**Pull request closed without merging**
