### PR TITLE
samples: sensor: qdec: Add nRF54L15 to platform allow

### PR DESCRIPTION
**Pull request by nordic-segl**
Add nRF54L15 to platform_allow and integration_platforms in the sample.yaml.
Overlay file for that target already exists in the boards directory.

### CODE REVIEW

**Review by kartben — DISMISSED** [review]

**Comment by nordic-segl** [comment]
I add one more commit.
When I tried to run Twister locally I got error:
ERROR   - nrf54l15pdk/nrf54l15/cpuapp/samples/sensor/qdec/sample.sensor.nrf_qdec_sensor: HARNESS:Console:no regex patterns configured.

I managed to run Twister when I moved regex from 'common' to harness_config defined in the test.

**Comment by nordic-segl** [comment]
I run Twister in CI on this PR. I confirmed that sample works correctly on nrf54l15
09:31:23  INFO    - 2/3 nrf54l15pdk/nrf54l15/cpuapp samples/sensor/qdec/sample.sensor.nrf_qdec_sensor  PASSED (device: 1057717622, 5.475s)

**Comment by PerMac** [comment]
@nordic-segl The common section can be used for defining regexes to use in all tests, like here https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/philosophers/sample.yaml.
However, the workflow goes like this: Twister takes an item from common section. If a test item provides a given field, it replace the common one (although there are exceptions for extra_args, which are extended). The logic is here https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/twister/twisterlib/config_parser.py#L160. In your case the common harness_config is replaced by test specific one. Note that regex is a level below. So if you wouldn't provide harness_config in you test, it wouldn't be overwritten. 
It would work if twister was overwriting starting from the bottom level, and not from the top level with the whole harness_config. Changing it now could probably break other existing tests/samples based on the current behavior and would require careful consideration. If you think it is worth investigating, please open a GH enhancement request

**Comment by nordic-segl** [comment]
Dear reviewers,
please find some time to do the review. It's a trivial change - I'm just adding target to the platform allow list.

**Review by PerMac — APPROVED** [review]

**Review by nordic-piks — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
