### PR TITLE
boards: Enable EDMA0 node for mm_feather and mm_swiftio

### LINKED ISSUE #41524: drivers: dma: dma_mcux_edma: unused variables cause daily build failures
**Describe the bug**
Twister fails during the daily build due to unused variables (warnings promoted to errors).

**To Reproduce**
```
twister -i -p mm_feather -s tests/drivers/dma/chan_blen_transfer/drivers.dma
```

**Expected behavior**
Daily build should not fail.

**Impact**
Annoyance, because the build succeeds with
```
west build -p auto -b mm_feather tests/drivers/dma/chan_blen_transfer
```

**Logs and console output**
```
/__w/zephyr/zephyr/drivers/dma/dma_mcux_edma.c:426:12: error: 'dma_mcux_edma_init' defined but not used [-Werror=unused-function]
  426 | static int dma_mcux_edma_init(const struct device *dev)
      |            ^~~~~~~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/dma/dma_mcux_edma.c:417:36: error: 'dma_mcux_edma_api' defined but not used [-Werror=unused-const-variable=]
  417 | static const struct dma_driver_api dma_mcux_edma_api = {
      |                                    ^~~~~~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/dma/dma_mcux_edma.c:162:13: error: 'dma_mcux_edma_error_irq_handler' defined but not used [-Werror=unused-function]
  162 | static void dma_mcux_edma_error_irq_handler(const struct device *dev)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/dma/dma_mcux_edma.c:143:13: error: 'dma_mcux_edma_irq_handler' defined but not used [-Werror=unused-function]
  143 | static void dma_mcux_edma_irq_handler(const struct device *dev)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Environment (please complete the following information):**
 - OS: CI
 - Toolchain: Zephyr SDK 0.13.2
 - Commit SHA: 7f5eb921dc8bb1b7014886986bbffdf111b68b15

**Additional context**
Daily Build failure:
https://github.com/zephyrproject-rtos/zephyr/runs/4676613967?check_suite_focus=true

### PR DESCRIPTION
**Pull request by danieldegrasse**
Enable `EDMA0` node with `status=okay` for `mm_feather` and `mm_swiftio`. This is required because the DMA MCUX driver generates function calls for each dma node with `status=okay`, and if no DMA nodes are enabled but the driver is included in the build, then there will be unused function warnings in the builds.

Fixes #41524

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@lgl88911 Can you verify that DMA works on The `mm_feather` using `tests/drivers/chan_blen_transfer`? I've tested these changes on the `mm_swiftio` and tests pass there.

**Review by dleach02 — APPROVED** [review]

**Comment by lgl88911** [comment]
@danieldegrasse I think I need a full linux environment to complete the twiser test mm_feater, and to execute the test knowledge "Build Pass" under WSL. I have been developing zephyr under WSL for a long time and when I opened my linux PC again today it didn't work anymore, I need some time to fix the Linux PC, so it might take a while to finish the real test.

```
# twister -v -i -p mm_feather -s tests/drivers/dma/chan_blen_transfer/drivers.dma
fatal: No tags can describe '1dafc921112b4f3b5c5a08170a99535f0ee65ac6'.
Try --always, or create some tags.
INFO    - JOBS: 8
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testcase list...
INFO    - 1 test scenarios (1 configurations) selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - 1/1 mm_feather                tests/drivers/dma/chan_blen_transfer/drivers.dma   PASSED (build)

INFO    - 1 of 1 test configurations passed (100.00%), 0 failed, 0 skipped with 0 warnings in 300.36 seconds
INFO    - In total 4 test cases were executed, 0 skipped on 1 out of total 394 platforms (0.25%)
INFO    - 0 test configurations executed on platforms, 1 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing xunit report /mnt/e/westz/tomato/t-clock-master/twister-out/twister.xml...
INFO    - Writing xunit report /mnt/e/westz/tomato/t-clock-master/twister-out/twister_report.xml...
INFO    - Run completed
```

**Comment by danieldegrasse** [comment]
@lgl88911 No worries- If you flash the test onto an `mm_feather` and it reports the test passing in the serial console, then everything should be working

**Review by MaureenHelm — APPROVED** [review]

**Comment by lgl88911** [comment]
@danieldegrasse Thanks for the suggestion, using `twister -v -i -p mm_feather -s tests/drivers/dma/chan_blen_transfer/drivers.dma` produced the result
and Burn `twister-out/mm_feather/tests/drivers/dma/chan_blen_transfer/drivers.dma/zephyr/zephyr.bin` to mm_feather, Serial output ALL pass：
```
 *** Booting Zephyr OS build 1dafc921112b  ***
Running test suite dma_m2m_test
===================================================================
START - test_dma_m2m_chan0_burst8
Preparing DMA Controller: Chan_ID=0, BURST_LEN=1
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan0_burst8 in 2.13 seconds
===================================================================
START - test_dma_m2m_chan1_burst8
Preparing DMA Controller: Chan_ID=1, BURST_LEN=1
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan1_burst8 in 2.11 seconds
===================================================================
START - test_dma_m2m_chan0_burst16
Preparing DMA Controller: Chan_ID=0, BURST_LEN=2
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan0_burst16 in 2.11 seconds
===================================================================
START - test_dma_m2m_chan1_burst16
Preparing DMA Controller: Chan_ID=1, BURST_LEN=2
Starting the transfer
DMA transfer done
It is harder to be kind than to be wise........
 PASS - test_dma_m2m_chan1_burst16 in 2.11 seconds
===================================================================
Test suite dma_m2m_test succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL

```

**Review by lgl88911 — APPROVED** [review]

**Pull request merged**
