### PR TITLE
Bluetooth: Add HCI Error codes defined in BT 5.2 Spec.

### PR DESCRIPTION
**Pull request by cvinayak**
Add missing and new HCI Error code values as defined in
Bluetooth Core Specification v5.2.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@jhe what is the strategy here, we only have error codes reference in zephyr tree? or list all Error codes in spec?

**Comment by carlescufi** [comment]
Would you mind adding the missing remote features as well in  https://github.com/zephyrproject-rtos/zephyr/blob/master/include/bluetooth/hci.h#L87?

We were just talking about this with Alexander from Nordic.

**Comment by cvinayak** [comment]
Will do.

**Comment by jhedberg** [comment]
> @jhe what is the strategy here, we only have error codes reference in zephyr tree? or list all Error codes in spec?

I'm fine having all of them - less hassle when at some point you need to take a new one into use.

**Comment by joerchan** [comment]
I think we should have all. In the case where you work with a different controller than the zephyr one it is annoying that you cannot use the zephyr defined names to find the meaning.

**Comment by cvinayak** [comment]
Updated with all error codes.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
