### PR TITLE
doc: release: Add highlights of Zephyr 3.7 release

### PR DESCRIPTION
**Pull request by kartben**
This introduces a high-level summary of the most notable changes in 3.7. This also tries to capture the same for changes since previous LTS.

The latter is 100% a proposal at this stage and far from complete. Looking for opinions from others on whether this is useful at all before spending more time trying to make it "right".

### CODE REVIEW

**Review by aescolar — APPROVED** [review]
This looks good to me.
I guess there is always the possibility of adding more features added since 2.7, but somewhere the line needs to be drawn.

**Comment by kartben** [comment]
I just realized that at least PTP (Precision Time Protocol) is missing from the highlights (from my POV at least 😄).
Will likely iterate some more on the list over the next few days but also happy if a first stab gets merged as soon as folks are comfortable with it, and it can always be completed in other PRs.

**Comment by aescolar** [comment]
> I just realized that at least 

Maybe you want to ping maintainers for their biggest highlights since 2.7, and then you can chose a shortlist from that?

**Comment by kartben** [comment]
> > I just realized that at least
> 
> Maybe you want to ping maintainers for their biggest highlights since 2.7, and then you can chose a shortlist from that?

In this case PTP is something recent I forgot for 3.7 proper, but yeah, good idea nevertheless :)

**Review by fabiobaltieri — COMMENTED** [review]
~~test ignore~~

**Review by nashif — APPROVED** [review]

**Pull request merged**
