### PR TITLE
dts: bindings: rename nxp,kinetis-ftm and nxp,kinetis-ftm-pwm compatibles

### PR DESCRIPTION
**Pull request by manuargue**
Rename "nxp,kinetis-ftm" and "nxp,kinetis-ftm-pwm" compatibles to "nxp,ftm" and "nxp,ftm-pwm", respectively, to remove the
device family from its name because this hardware block is used in multiple NXP devices from different families.

Also relocate "nxp,ftm" binding to timer bindings because NXP FlexTimer Module is a configurable timer peripheral and right now is wrongly placed under Arm bindings.

### CODE REVIEW

**Comment by manuargue** [comment]
unrelated CI failures due to `zephyr/include/generated/zephyr/syscalls/random.h:37: undefined reference to `z_impl_sys_rand_get'`.. I'm looking at it

**Review by henrikbrixandersen — APPROVED** [review]

**Review by anangl — DISMISSED** [review]

**Review by danieldegrasse — DISMISSED** [review]

**Comment by manuargue** [comment]
> unrelated CI failures due to `zephyr/include/generated/zephyr/syscalls/random.h:37: undefined reference to z_impl_sys_rand_get'`.. I'm looking at it

rebased to fix CI issues :crossed_fingers:

**Review by decsny — DISMISSED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by dleach02 — DISMISSED** [review]

**Comment by dleach02** [comment]
rebased to clear CI issues

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by bjarki-andreasen** [comment]
Tried restarting CI

**Comment by bperseghetti** [comment]
Appears to be an issue with building the shield for BT? https://github.com/zephyrproject-rtos/zephyr/actions/runs/12289202979/job/34564981997?pr=82195#step:12:911

**Comment by bperseghetti** [comment]
We should probably consider if any of these work?
https://github.com/zephyrproject-rtos/zephyr/blob/87b08cc5bb966eb83ddb491491ab5d844117dee1/samples/bluetooth/peripheral_ht/sample.yaml#L15-L21

**Comment by manuargue** [comment]
> Appears to be an issue with building the shield for BT? https://github.com/zephyrproject-rtos/zephyr/actions/runs/12289202979/job/34564981997?pr=82195#step:12:911
> 
> Seems to stem from: [a4b9ef6](https://github.com/zephyrproject-rtos/zephyr/commit/a4b9ef69c34c2bcbf16eaa1dfa84bbf86ad5c7fd)

it's still the same issue as reported above, I will rebase after https://github.com/zephyrproject-rtos/zephyr/pull/82859

**Comment by dleach02** [comment]
> > Appears to be an issue with building the shield for BT? [zephyrproject-rtos/zephyr/actions/runs/12289202979/job/34564981997?pr=82195#step:12:911](https://github.com/zephyrproject-rtos/zephyr/actions/runs/12289202979/job/34564981997?pr=82195#step:12:911)
> > Seems to stem from: [a4b9ef6](https://github.com/zephyrproject-rtos/zephyr/commit/a4b9ef69c34c2bcbf16eaa1dfa84bbf86ad5c7fd)
> 
> it's still the same issue as reported above, I will rebase after #82859 is merged

PR merged. I've rebased this PR for you.

**Comment by bjarki-andreasen** [comment]
Cool :)

**Comment by dleach02** [comment]
fixed the merge conflict

**Review by butok — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
