### PR TITLE
96b_stm32_sensor_mez: Add on-board Microphone support

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
This PR adds on-board DMIC support for `96b_stm32_sensor_mez` board. The microphone is connected to I2S2 of the STM32F446 controller and has been tested using the `96b_argonkey`
microphone sample utilizing the OpenPDMFilter library. Also, a small DMA issue has been fixed along the way.

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by avisconti** [comment]
@Mani-Sadhasivam 
First of all I have to say that I am very happy that there are additional works that goes on the line
of the ST mic support. Probably we should also support the x-nucleo-cca02m1 nucleo shield in the
next future!

I have following comments/observations:

- The work seems fine and inline with my expectations. But I would rather collapse the work in only two commits: one commit with all the board related work (i.e. dts + pinmux + Kconfig changes) and one commit with the dma STM32F4 fix. 
Concerning this latest fix it is something that is also impacting the ArgonKey board, so I need to test the fix and review it more carefully. Give me some time to review it carefully, even if it seems very simple.

- Concerning the I2S pinmuxing I have a big doubt. I think that you should have the same issue that I faced and described in #9028. Just to summarize there is an issue in STM32F4 SPI/I2S controller for which there is a corruption in the bitstream. To fix it the design suggest to decrease the APB speed and to increase the pinmux speed. I don't see in your pinmuxing any setting in HIGH SPEED. In ArgonKey
i have done following stuff:

  96b_argonkey_defconfig:
   \# APB2 clock is fixed at 42MHz to prevent known SPI/I2S bug
   CONFIG_CLOCK_STM32_APB2_PRESCALER=2
 
    pinmux.c:
   \#ifdef CONFIG_I2S_5
        {STM32_PIN_PB0, STM32F4_PINMUX_FUNC_PB0_I2S5_CK |
                        STM32_OSPEEDR_VERY_HIGH_SPEED},
        {STM32_PIN_PB8, STM32F4_PINMUX_FUNC_PB8_I2S5_SD},
   \#endif  /* CONFIG_I2S_5 */

Since same issue apply in SPI also I have done recently following commit 620ff63, where I fixed globally the SPI gpio speed to fix the issue, but I realize now that I should have done it for I2S as well.
Now I do not understand why you are not getting same issue. Can you comment on it?
In case I think we need to add an extension for I2S to 620ff63.

**Comment by avisconti** [comment]
@Mani-Sadhasivam 
I see now that you already have STM32_OSPEEDR_VERY_HIGH_SPEED in pinmux.c of the board.
THis is inline with ArgonKey. Nevertheless I think that a better work would be to add this flag in pinmux_stm32f4.h globally. Do you agree?

At the end, in my opinion, there should be 3 separate commits for this work:
1. board related: dts + Kconfig
2. general pinmux:  pinmux_stm32f4.h with STM32_OSPEEDR_VERY_HIGH_SPEED
3. dma F4 fix

**Comment by avisconti** [comment]
Concerning the DMA fix I noticed now that is an obvious (and silly) bug. I'm not sure how it was possible
it worked in my case. Anyway I would propose to fix it in a slightly different way if you agree.
Two options:

1. Move the assignment (i.e. stream->direction = config->channel_direction;) before the test.
2. Remove direction from stream structure, and always use config->channel_direction to test

I prefer the number one, just to be more conservative.

**Comment by erwango** [comment]
@Mani-Sadhasivam , please submit separate issue for DMA. As a bug fix, it should be part of 1.14. In this series, it will wait 1.15.

**Comment by Mani-Sadhasivam** [comment]
@avisconti
 
> @Mani-Sadhasivam
> I see now that you already have STM32_OSPEEDR_VERY_HIGH_SPEED in pinmux.c of the board.
> THis is inline with ArgonKey. Nevertheless I think that a better work would be to add this flag in pinmux_stm32f4.h globally. Do you agree?
> 

Agree. Will move the `STM32_OSPEEDR_VERY_HIGH_SPEED` flag to `pinmux.c` for all I2S_CK pins.

> At the end, in my opinion, there should be 3 separate commits for this work:
> 
> 1. board related: dts + Kconfig

Matter of taste. Usually I tend to split commits based on the subsystems and since DTS and Kconfig are different in terms of providing configurations in Zephyr I wouldn't prefer mixing those (unless someone strongly disagree with this).

> 2. general pinmux:  pinmux_stm32f4.h with STM32_OSPEEDR_VERY_HIGH_SPEED
> 3. dma F4 fix

**Comment by Mani-Sadhasivam** [comment]
> Concerning the DMA fix I noticed now that is an obvious (and silly) bug. I'm not sure how it was possible
> it worked in my case. 

You might have used DMA_2 which supports memcopy.

> Anyway I would propose to fix it in a slightly different way if you agree.
> Two options:
> 
> 1. Move the assignment (i.e. stream->direction = config->channel_direction;) before the test.

I consider doing this way but since we are setting other parameters like busy, callback etc... as a group, I decided to change the comparision parameter instead.

> 2. Remove direction from stream structure, and always use config->channel_direction to test
> 
> I prefer the number one, just to be more conservative.

Sounds good to me but I'd like to get @erwango thought on this.

**Comment by Mani-Sadhasivam** [comment]
> @Mani-Sadhasivam , please submit separate issue for DMA. As a bug fix, it should be part of 1.14. In this series, it will wait 1.15.

@erwango Sure, will split it as a separate PR.

**Comment by Mani-Sadhasivam** [comment]
@erwango @avisconti Dropped the DMA commit and created a new PR #14140

**Comment by avisconti** [comment]
> > At the end, in my opinion, there should be 3 separate commits for this work:
> > 
> > 1. board related: dts + Kconfig
> 
> Matter of taste. Usually I tend to split commits based on the subsystems and since DTS and Kconfig are different in terms of providing configurations in Zephyr I wouldn't prefer mixing those (unless someone strongly disagree with this).

Let's see what @erwango has to say about this. In my opinion those two changes are atomic as you are adding the microphone support thru I2S to this board.

**Comment by Mani-Sadhasivam** [comment]
@avisconti Reworked the pinmux commit!

**Comment by erwango** [comment]
> > > At the end, in my opinion, there should be 3 separate commits for this work:
> > > 
> > > 1. board related: dts + Kconfig
> > 
> > Matter of taste. Usually I tend to split commits based on the subsystems and since DTS and Kconfig are different in terms of providing configurations in Zephyr I wouldn't prefer mixing those (unless someone strongly disagree with this).
> 
> Let's see what @erwango has to say about this. In my opinion those two changes are atomic as you are adding the microphone support thru I2S to this board

I complain too much about non split commits, so I won't complain about having too much commits for once. This being said, I'd personally have done as suggested by @avisconti, since this is all related about the same feature and in that case subsystem is boards/ for both commits. 
What I would complain on is the lack of doc update ;-)

**Comment by avisconti** [comment]
> @avisconti Reworked the pinmux commit!

The pinmux commit seems perfect. I didn't test it on ArgonKey though. Maybe I should.

**Comment by Mani-Sadhasivam** [comment]
> What I would complain on is the lack of doc update ;-)

@erwango You want me to update the [Supported features](https://docs.zephyrproject.org/latest/boards/arm/96b_stm32_sensor_mez/doc/96b_stm32_sensor_mez.html#supported-features) section with I2S and DMIC?

**Comment by avisconti** [comment]
> > What I would complain on is the lack of doc update ;-)
> 
> @erwango You want me to update the [Supported features](https://docs.zephyrproject.org/latest/boards/arm/96b_stm32_sensor_mez/doc/96b_stm32_sensor_mez.html#supported-features) section with I2S and DMIC?

Yes, I think that documentation at this level just need to report that MP34DT01/I2S is now part of the feature list. In case you decide to add a sample for testing out the microphone a more detailed documentation should be prepared.

**Comment by avisconti** [comment]
@Mani-Sadhasivam 
Are you still working on this?
I'm waiting for this to be merged, because I need 'drivers/pinmux/stm32/pinmux_stm32f4.h' modifications you have done. I think you just need to slightly adjust the documentaion and you are done.

**Comment by Mani-Sadhasivam** [comment]
@avisconti I pushed it to low priority since the goal is to merge for v1.15. Anyway, I can add the documentation bit now.

**Comment by Mani-Sadhasivam** [comment]
@avisconti Added doc now!

**Comment by avisconti** [comment]
LGTM
But I would add in 6cffe1a commit message a reference to issue #9028.
Then I think we are done.

**Comment by Mani-Sadhasivam** [comment]
> LGTM
> But I would add in [6cffe1a](https://github.com/zephyrproject-rtos/zephyr/commit/6cffe1afe3c36736d2ef1fc9a930745144332105) commit message a reference to issue #9028.
> Then I think we are done.

Yes, I agree. Mentioned the issue in the commit description.

**Review by avisconti — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
Doc change is OK, but it would be nice to see some mention of microphone support since that's the purpose of this PR

**Comment by galak** [comment]
Looks like a merge conflict, can you take a look.

**Comment by Mani-Sadhasivam** [comment]
@galak Fixed the merge conflict!

**Comment by galak** [comment]
@erwango can you take a quick look.

**Review by galak — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Pull request merged**
