### PR TITLE
tests: fatal: increase robustness

### PR DESCRIPTION
**Pull request by tyrantlizard77**
We now verify, for every crash, that the expected thread
crashed with the expected reason.

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
minor test case bugfix

**Review by ioannisg — COMMENTED** [review]
Looks ok to me :)

**Comment by andrewboie** [comment]
> Looks ok to me :)

@ioannisg Can you capture that in a review then?

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
@pabigot could you take a look here, please?

**Review by pabigot — APPROVED** [review]
I'm pretty ignorant of this test but the change looks reasonable.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
