### PR TITLE
doc: fix broken rST syntax in Kconfig help

### LINKED ISSUE #29853: multiple PRs fail doc checks
E.g. https://github.com/zephyrproject-rtos/zephyr/pull/29847/checks?check_run_id=1365072761

Either something got merged with a problem or known issues needs to be updated.

### PR DESCRIPTION
**Pull request by utzig**
Update usage of literal syntax in Kconfig file from markdown to proper rST.

Fixes #29853

### CODE REVIEW

**Comment by utzig** [comment]
I am testing this locally, seems like changing Kconfig files also does not trigger documentation builds!

**Comment by utzig** [comment]
> I am testing this locally, seems like changing Kconfig files also does not trigger documentation builds!

Which is why the original PR that brought this in was not properly tested...

**Review by pabigot — APPROVED** [review]
Thanks.  I wasn't aware rST was allowed for Kconfig documentation.

**Comment by utzig** [comment]
> Thanks. I wasn't aware rST was allowed for Kconfig documentation.

All Kconfig files are parsed and made into rST, so `CONFIG_` symbols can be resolved in the documentation. I will add a commit also filtering Kconfig files...

**Comment by pabigot** [comment]
> All Kconfig files are parsed and made into rST, so `CONFIG_` symbols can be resolved in the documentation.

Good to know.  I see that at least two Kconfigs in Linux also use rST markup so this isn't Zephyr-only.

**Comment by utzig** [comment]
> Good to know. I see that at least two Kconfigs in Linux also use rST markup so this isn't Zephyr-only.

Oh no, we have a custom script that does this, `doc/scripts/gen_kconfig_rest.py`, it is not something that happens in a standard documentation build. I doubt Linux is also doing the same!

**Comment by pabigot** [comment]
> I doubt Linux is also doing the same!

It's not doing it the same way, but what I mean is that there are Kconfig files in Linux that use rST markup, which means we can reasonably assume that presence of rST in Kconfig help is compatible with standard tools to process Kconfig content.  If we couldn't make that assumption there would be a problem if, like devicetree source, we want Zephyr Kconfig files to be compatible with non-Zephyr systems.  Then we'd have either remove the markup, or document that Zephyr Kconfigs are not portable.

**Review by nashif — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
