### PR TITLE
devicetree: add CONFIG_LEGACY_DEVICETREE_MACROS

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This default-y option allows continued use of the legacy devicetree macros.

I'm proposing we set it to default n in time for the Zephyr 2.3 release, after converting in-tree users to the new API.

Unfortunately, `__DEPRECATED_MACRO` does not suffice as a transition path for users. This is because, at least in GCC, macros defined using `__DEPRECATED_MACRO` cannot be used in preprocessor lines like `#if DT_SOME_LEGACY_MACRO`.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
> at least in GCC, macros defined using `__DEPRECATED_MACRO` cannot be used in preprocessor lines like `#if DT_SOME_LEGACY_MACRO`.

Citation:

> The standard is unclear on where a _Pragma operator can appear. The preprocessor does not accept it within a preprocessing conditional directive like ‘#if’. To be safe, you are probably best keeping it out of directives other than ‘#define’, and putting it on a line of its own.

https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html

**Review by carlescufi — CHANGES_REQUESTED** [review]
This is a good way to go about it, no objections.
Please add a note in the 2.3 release notes though, as part of this PR. This is very similar to what was done for kernel timeouts, so you could follow the same format

**Comment by mbolivar-nordic** [comment]
> lease add a note in the 2.3 release notes though, as part of this PR.

Good idea; now done. I tacked on another fix since we're here, in a separate commit.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@galak can you take a look please?

**Comment by carlescufi** [comment]
@mbolivar-nordic please rebase
@galak ok with this one?

**Comment by mbolivar-nordic** [comment]
> please rebase

done

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
@carles will look to add to the deprecation policy that we might have options under Kconfig that require explicit enablement to get the old behavior.

**Pull request merged**
