### PR TITLE
serial: atmel_sam3: remove driver as it was deprecated

### PR DESCRIPTION
**Pull request by galak**
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by mnkp** [comment]
This looks good, however we also need to remove `dts/bindings/serial/atmel,sam3x-uart.yaml` file.

**Comment by galak** [comment]
> This looks good, however we also need to remove dts/bindings/serial/atmel,sam3x-uart.yaml file.

thanks, will remove it and update.

**Comment by mnkp** [comment]
It looks like we've overlooked a few more things.

./dts/arm/arduino_due.fixup:
```
#define CONFIG_UART_ATMEL_SAM3_NAME         ATMEL_SAM_UART_400E0800_LABEL
```
./boards/arm/arduino_due/Kconfig.defconfig:
```
if UART_ATMEL_SAM3

config UART_ATMEL_SAM3_BAUD_RATE
	default 115200

config UART_ATMEL_SAM3_CLK_FREQ
	default 84000000

endif # UART_ATMEL_SAM3
```

**Comment by galak** [comment]
Updated, maybe we got them all now :)

**Review by mnkp — APPROVED** [review]

**Pull request merged**
