### PR TITLE
More changes to make it buildable on GCC 11

### LINKED ISSUE #35870: Build failure with gcc 11.x on native_posix
**Describe the bug**
Warnings from new gcc turning into errors:

```
In file included from /home/nashif/Work/zephyrproject/zephyr/include/kernel_includes.h:39,
                 from /home/nashif/Work/zephyrproject/zephyr/include/kernel.h:17,
                 from /home/nashif/Work/zephyrproject/zephyr/include/zephyr.h:18,
                 from /home/nashif/Work/zephyrproject/zephyr/kernel/init.c:14:
/home/nashif/Work/zephyrproject/zephyr/include/sys/thread_stack.h:155:16: error: ignoring attribute ‘section (".noinit.\"WEST_TOPDIR/zephyr/kernel/init.c\".3")’ because it conflicts with previous ‘section (".noinit.\"WEST_TOPDIR/zephyr/kernel/include/kernel_internal.h\".0")’ [-Werror=attributes]
  155 |         struct z_thread_stack_element __kstackmem \
      |                ^~~~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/kernel/init.c:61:1: note: in expansion of macro ‘K_KERNEL_STACK_ARRAY_DEFINE’
   61 | K_KERNEL_STACK_ARRAY_DEFINE(z_interrupt_stacks, CONFIG_MP_NUM_CPUS,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/kernel/include/kernel_internal.h:136:36: note: previous declaration here
  136 | extern K_KERNEL_STACK_ARRAY_DEFINE(z_interrupt_stacks, CONFIG_MP_NUM_CPUS,
      |                                    ^~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/include/sys/thread_stack.h:157:17: note: in definition of macro ‘K_KERNEL_STACK_ARRAY_DEFINE’
  157 |                 sym[nmemb][Z_KERNEL_STACK_LEN(size)]
      |                 ^~~
cc1: all warnings being treated as errors
gmake[2]: *** [zephyr/kernel/CMakeFiles/kernel.dir/build.make:134: zephyr/kernel/CMakeFiles/kernel.dir/init.c.obj] Error
1
gmake[1]: *** [CMakeFiles/Makefile2:2781: zephyr/kernel/CMakeFiles/kernel.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2

```

**To Reproduce**

On fedora 34 with gcc 11.x

1.  twister -T samples/philosophers/ -p native_posix

### PR DESCRIPTION
**Pull request by dcpleung**
See individual commits for information.

Relates to #35707

### CODE REVIEW

**Comment by dcpleung** [comment]
This is on top of #35852. This new PR is to avoid adding new changes to that PR after approval.

**Comment by dcpleung** [comment]
Got most of `tests/kernel` for `qemu_x86` and `qemu_x86_64` built with orphan section warning disabled due to bunch of `.eh_frame_hdr` in `libgcc.a`. One test failed to build due to `_GLOBAL_OFFSET_TABLE_` being placed into `.got.plt` and GCC 11 on Fedora doesn't like. This PR should get most of the common errors out of the way, and we can deal with build error and warnings (and about the orphan sections) once we have Zephyr SDK built on top of GCC 11.

**Review by ceolin — APPROVED** [review]

**Review by enjiamai — APPROVED** [review]

**Comment by enjiamai** [comment]
The build process reports timeout, would you want to re-build it again?

**Review by jhedberg — APPROVED** [review]

**Comment by dcpleung** [comment]
Not sure why buildkite always times out.

**Review by tejlmand — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
