### PR TITLE
Switch ARC boards to openocd runner

### PR DESCRIPTION
**Pull request by abrodkin**
We used to use `em-starterkit` runner for ARC which is basically heavy-modified `openocd` runner tweaked to use GDB for loading and starting Elf files.

To use generic `openocd` runner we need to tweak it a little bit to accommodate the fact that our devboards have BootROM and for Zephyr apps we use only RAM (in whatever form it exist: SRAM, DDR, CCMs etc). For that in its turn we mostly need to implement a way to setup an entry-point and start execution from that as opposed to real "flashing" and resetting the board (which is currently done by `openocd` runner). And that we do here. Also since for entry-point recovery we need to have Elf (which gets built anyways before any image) we'll use Elf for loading (and OpenOCD is happy with it BTW).

And while at it we also enable usage of multiple boards with FTDI-based JTAG connected to the same one host machine via JTAG probe selection by FTDI's serial number (which is supposed to be unique unless curious user reprograms on-board EEPROM).

Well and we get rid of "em-starterkit" as well since we no longer need it.

### CODE REVIEW

**Review by mbolivar — APPROVED** [review]
West changes are OK with me since it solves your problem and I don't have a better solution right now.

**Review by ruuddw — APPROVED** [review]
Thanks for fixing this 'TODO' and using 
(and enhancing) the common openocd handler for the ARC development boards, looks clean to me.

**Review by vonhust — APPROVED** [review]

**Comment by abrodkin** [comment]
Removed `arc` runner from `scripts/west_commands/runners/__init__.py` which triggered `west` failure:
```
ERROR: extension command "flash" could not be run: could not import .../scripts/west_commands/flash.py.
Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/west/commands/__init__.py", line 365, in __call__
    mod = _commands_module_from_file(self.py_file)
  File "~/.local/lib/python3.7/site-packages/west/commands/__init__.py", line 333, in _commands_module_from_file
    mod = _import_mod_from(mod_name, file)
  File "~/.local/lib/python3.7/site-packages/west/commands/__init__.py", line 330, in _import_mod_from
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../scripts/west_commands/flash.py", line 12, in <module>
    from run_common import desc_common, add_parser_common, do_run_common
  File ".../scripts/west_commands/run_common.py", line 24, in <module>
    from runners import get_runner_cls, ZephyrBinaryRunner, MissingProgram
  File ".../scripts/west_commands/runners/__init__.py", line 14, in <module>
    from runners import arc
ImportError: cannot import name 'arc' from 'runners' (.../scripts/west_commands/runners/__init__.py)
```

**Comment by abrodkin** [comment]
Note that last Shippable build fails due to generation of huge images because https://github.com/zephyrproject-rtos/zephyr/pull/22601 is not yet accepted. I might get it merged in this pull-request for simplicity. Any thoughts?

**Review by jhedberg — APPROVED** [review]

**Comment by abrodkin** [comment]
@jhedberg does that mean this PR will be a part of 2.2.0?

**Comment by jhedberg** [comment]
> @jhedberg does that mean this PR will be a part of 2.2.0?

Yes. It had the milestone set to 2.2, so I assume that's what was wanted?

**Comment by jhedberg** [comment]
@abrodkin I was under the impression that this was more of a fix than an enhancement, but I now see that it's only got the enhancement label, so perhaps I should have waited. Anyway, it's in now - hopefully nothing breaks :)

**Comment by abrodkin** [comment]
> > @jhedberg does that mean this PR will be a part of 2.2.0?
> 
> Yes. It had the milestone set to 2.2, so I assume that's what was wanted?

Sure I'm more than happy to get that in 2.2 but was a bit unsure if it gets merged past RC1 :)
But please keep it now - it will really help us to do automated verification on real HW.

And I'll be willing to fix stuff if anything happens. Though with my most recent re-spin everything should be good (I hope).

**Pull request merged**
