### PR TITLE
samples: display: lvgl: add support for pwm lcd backlight

### PR DESCRIPTION
**Pull request by joelguittet**
Add support for PWM LCD backlight, if defined in the board. This permit to switch ON the backlight in this sample.

### CODE REVIEW

**Comment by faxe1008** [comment]
Thanks for following up your display contribution with that PR. As mentioned in the PR the lcd pwm is now separated out. The thing is that we now need to add this to all samples. I was wondering if the addition of a `chosen` node, something like `display-backlight-pwm` would allow to add a method into lvgl module which takes care of unblanking and setting the pwm. This would reduce boilerplate at least somewhat.

Any oppinions on that idea @jfischer-no @fabiobaltieri @joelguittet ?

**Comment by fabiobaltieri** [comment]
@faxe1008 yeah that's what I was suggesting in the original thread (https://github.com/zephyrproject-rtos/zephyr/pull/67311#discussion_r1475133631), this is proposing an alias, not too sure what is "most correct" but to me it makes sense to have something that mimics the display identifier (zephyr,display)

**Comment by joelguittet** [comment]
@fabiobaltieri I think @faxe1008 think the alias can then be automatically handled by LVGL subsystem, correct ? I don't know if this is something that is possible.

@faxe1008 you said:
> The thing is that we now need to add this to all samples

I don't understand that, why do we need to modify all samples ? Which sample are you thinking about exactly ? Actually the modification proposed to turn on the backlight of the LCD if the board itself defined the right pwm entry.

**Comment by faxe1008** [comment]
> think the alias can then be automatically handled by LVGL subsystem, correct ? I don't know if this is something that is possible.

It should be possible yes. We can add a function to for example `lvgl_display.h`, e.g. `lv_enable_display`. This function would unblank the screen and turn on the backlight pwm. You can call this function right before entering the event loop, after you are done with your initial widget construction.

The general setup of lvgl requires a `chosen`  `zephyr,display` alias to work, so I don't see why this should be out of flavor.

> I don't understand that, why do we need to modify all samples ? Which sample are you thinking about exactly ? 

There are more samples located at `samples/modules/lvgl` that would not work "out of the box" with lcds that require a pwm backlight.

**Comment by joelguittet** [comment]
> It should be possible yes. We can add a function to for example lvgl_display.h, e.g. lv_enable_display. This function would unblank the screen and turn on the backlight pwm.

Got it. What should be prototype for this function ? I see different scenarii:
- no backlight gpio/pwm defined
- backlight gpio ON/OFF with possible revert logic
- backlight with PWM, and in this case probably the settings of the PWM (at least the ratio) should be defined somewhere, no reason it should be 100% every time, isn't it ?

**Comment by fabiobaltieri** [comment]
Does LVGL have a backlight control API?

It's tempting to suggest using the LED subsystem otherwise, it already abstracts the gpio vs pwm case, you can already define a backlight at either, for example

```
        pwmleds {
                compatible = "pwm-leds";
                backlight: backlight {
                        pwms = <&pwm0 0 PWM_HZ(250) PWM_POLARITY_NORMAL>;
                };
        };
```

or

```
        leds {
                compatible = "gpio-leds";
                backlight: led_0 {
                        gpios = <&gpio0 8 GPIO_ACTIVE_HIGH>;
                };
        };
```

and use it with the same API, something like

```c

#define BACKLIGHT_LED_NODE DT_NODELABEL(system)
#define BACKLIGHT_LED_IDX DT_NODE_CHILD_IDX(BACKLIGHT_LED_NODE)

static const struct device *leds = DEVICE_DT_GET(DT_PARENT(BACKLIGHT_LED_NODE));

led_set_brightness(leds, BACKLIGHT_LED_IDX, 100);
```

It'd be silly to reimplement the same thing just renamed to "backlight" instead of "led"

**Comment by jfischer-no** [comment]
@fabiobaltieri @faxe1008 I may be missing something, but why cannot display_set_brightness() be used for this? The API is already there, doing it on the side like this is not nice and duplicates code in the apps.

**Comment by fabiobaltieri** [comment]
@jfischer-no because that's specific to the display device, it's certainly the right thing to use if the display controller includes brightness control AND it's used to control brightness in the specific board, but in reality it can either be that, or a separate circuit using a GPIO or PWM channel.

Maybe we could have a common structure added to the display API where one could specificy a backlight gpio or pwm channel, and then `display_set_brightness` would use that if provided or fallback to the display specific one. That may be the cleanest approach, needs a bit of redesign of the api though, adding a common structure and making sure it's initialized on all the drivers. It'd be nice though, what do you think?

**Comment by jfischer-no** [comment]
> @jfischer-no because that's specific to the display device, it's certainly the right thing to use if the display controller includes brightness control AND it's used to control brightness in the specific board, but in reality it can either be that, or a separate circuit using a GPIO or PWM channel.

I think this is not a problem, most of the small TFT LCD displays with integrated controller need PWM or GPIO to control the backlight. OLED can also use PWM to control brightness. Not sure about external panels connected to a display controller on the SoC. What external display controller actually has built-in brightness control?

> Maybe we could have a common structure added to the display API where one could specificy a backlight gpio or pwm channel, and then `display_set_brightness` would use that if provided or fallback to the display specific one. That may be the cleanest approach, needs a bit of redesign of the api though, adding a common structure and making sure it's initialized on all the drivers. It'd be nice though, what do you think?

That could be placed in display_common.[c,h], not sure API change is needed for that, but [Display Interface](https://docs.zephyrproject.org/latest/hardware/peripherals/display/index.html#display-api) API status is unstable since 1.14.

**Comment by joelguittet** [comment]
@fabiobaltieri @jfischer-no I was just reading again the integration of the driver I'm currently using at https://github.com/zephyrproject-rtos/zephyr/pull/67012
Seems this was already discussed and seems also the pwm backlight was proposed initially, but then it was removed.
And indeed, the `set_brightness` member of the driver api is used only by `display_dummy.c`... No other driver using this.

So, does it means the `set_brightness` should be implemented in a `display_common.c/h` and optionally overriden by the display driver itself in case the backlight is controlled by the controller itself as @jfischer-no indicates ? Me too I don't have references where the display controller controls the backlight directly, but maybe they are.

**Comment by fabiobaltieri** [comment]
@joelguittet there's a few more implementations (`display_max7219.c`, `display_nrf_led_matrix.c` and `display_otm8009a.c`). Other displays have it well, if you look at the ili9341 manual for example (https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf) there's a reference to a LEDPWM pin. I also haven't seen it used anywhere, but no doubt someone out there is controlling and LED backlight from it and may end up being supported.

About supporting this at subsystem level, this is what I had in mind (@jfischer-no please confirm if we are in line with it)
- add a pair of properties for a backlight gpio or pwm in `display-controller.yaml
- add a matching common data structure to hold a `struct gpio_dt_spec` or `struct pwm_dt_spec` in `drivers/display.h`
- add a macro to initialize the data in such structure, also in `drivers/display.h`, add the structure to all current display config structures, change all current display drivers to init the structures, this is not an uncommon pattern, see `struct gpio_driver_config`, `struct regulator_common_config`, `struct input_kbd_matrix_common_config` and the corresponding initializers
- at this point every display driver will have your common data structure in their config, you can modify `display_set_brightness` to get that structure, check if a gpio or pwm is set, if it is use that one to set the brightness, otherwise fallback to the controller specific api, if any

This would allow a display controller to implement brightness control, and a board to use either that, a pwm or a gpio, all through the display set brightness API.

**Comment by joelguittet** [comment]
@fabiobaltieri thanks to point the several drivers, seems I have checked to quickly!
And thanks fro the detailed overview you have in mind, looks almost clear to me and I will be happy to contribute on this part :-)

@jfischer-no is the above proposal from Fabio good for you as well ?

**Comment by fabiobaltieri** [comment]
@danieldegrasse ^^

**Comment by danieldegrasse** [comment]
> @danieldegrasse ^^

The idea here makes sense to me. Breaking out of tree drivers is a legitimate concern, perhaps we need a note in the migration guide to highlight this? Not sure what else we can do here to easily detect a driver that is not ported to use the new generic code.

**Pull request closed without merging**
