### PR TITLE
linker: do not force keep common kernel objects

### LINKED ISSUE #20663: kernel objects are being included always, regardless of usage
Noticing that this file is building unconditionally, whether used or not. This takes 20 byes of RAM

image

### PR DESCRIPTION
**Pull request by dcpleung**
This uses the new macros so the common kernel objects can be
garbage collected if they are not referred directly anywhere
in the code. This is useful for reducing library data size
as not all library functions and their corresponding kobjects
are being used.

Fixes #20663

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]
looks good

**Review by nashif — APPROVED** [review]

**Comment by dcpleung** [comment]
The compliance complain is about linker script not acting like C code...

**Review by carlescufi — CHANGES_REQUESTED** [review]
Thanks for this!

However, this still seems to leave stuff in that should not be there:

```
west build -b reel_board -t rom_report samples/basic/minimal/ -- -DCONF_FILE="common.conf no-mt.conf no-timers.conf arm.conf"
```
So it doesn't fix #20663 entirely.

You will likely need something like:
https://github.com/carlescufi/zephyr/commit/a0d30e298917eac3a178dd57a246e5d64936f723#diff-4560d3c90a6d35d90781757e85d2056dR12
and
https://github.com/carlescufi/zephyr/commit/a0d30e298917eac3a178dd57a246e5d64936f723#diff-9112b5bcdb85f9fc628e8175f32264b5R28

to stop pulling heap and mempool code when not needed.

**Comment by andrewboie** [comment]
> Thanks for this!
> 
> However, this still seems to leave stuff in that should not be there:
> 
> ```
> west build -b reel_board -t rom_report samples/basic/minimal/ -- -DCONF_FILE="common.conf no-mt.conf no-timers.conf arm.conf"
> ```
> 
> So it doesn't fix #20663 entirely.
> 
> You will likely need something like:
> [carlescufi@a0d30e2#diff-4560d3c90a6d35d90781757e85d2056dR12](https://github.com/carlescufi/zephyr/commit/a0d30e298917eac3a178dd57a246e5d64936f723#diff-4560d3c90a6d35d90781757e85d2056dR12)
> and
> [carlescufi@a0d30e2#diff-9112b5bcdb85f9fc628e8175f32264b5R28](https://github.com/carlescufi/zephyr/commit/a0d30e298917eac3a178dd57a246e5d64936f723#diff-9112b5bcdb85f9fc628e8175f32264b5R28)
> 
> to stop pulling heap and mempool code when not needed.

Is it the cross-dependencies between kernel/ and lib/ that are defeating the `--no-whole-archive` logic (as described in https://github.com/zephyrproject-rtos/zephyr/issues/20663#issuecomment-674162845)? We can ifdef stuff but I'm (wildly) speculating if there is an even better solution we are overlooking...

**Comment by dcpleung** [comment]
It looks like `mempool.c` is causing `kheap.c` to be included regardless if heap is being used, even though the `mempool.c` is not included in the final image. I added a kconfig for memory pool and have it disabled in the minimal sample itself. The ROM size of the image from the build command above goes from 3446 -> 2926.

**Comment by andrewboie** [comment]
> @carlescufi if you want, I can have CONFIG_KERNEL_MEM_POOL defaults to n if CONFIG_MULTITHREADING=n.

I'm not sure if the multithreading=n matters much. This configuration is deprecated and is going away soon.

> It looks like mempool.c is causing kheap.c to be included regardless if heap is being used, even though the mempool.c is not included in the final image. 

I think it's a general issue we need to solve, I don't think we want to go down a path where we have to have Kconfigs for core kernel APIs because of some interaction in dependencies between `kernel/` and `lib/os/`. I don't think we had this problem before the heap code landed and we had the kernel mempool code and the os lib mempool code.

What specifically is pulling in what, with respect to lib/os/mempool.c and kernel/kheap.c?

I have a feeling that the real proper fix for this is to finish what we started in https://github.com/zephyrproject-rtos/zephyr/issues/24358 I don't understand why that issue keeps bouncing back and forth between "enhancement" and "bug" status

**Comment by dcpleung** [comment]
It's caused by calling of `k_mem_pool_alloc()` in `mempool.c`, where this function resides in `kheap.c` if `CONFIG_MEM_POOL_HEAP_BACKEND=y`. Even if you extract this function into another file, it still calls `k_heap_alloc()` and `k_heap_free()` which results in `kheap.c` being included.

Setting `CONFIG_MEM_POOL_HEAP_BACKEND` to `n` simply changes from including `kheap.c` to including `mempool_sys.c` which has `SYS_LIST()`.

To completely prevent either `SYS_LIST()` from being included, `mempool.c` needs to be excluded from build, where kconfig is a way to achieve this.

**Review by carlescufi — APPROVED** [review]
I am happy with the outcome. Thank you @dcpleung.

**Pull request merged**
