### PR TITLE
bluetooth: update comment to LE Advertising Parameters struct

### PR DESCRIPTION
**Pull request by Xeenych**
Update description to maximum and minimum values of interval_min and
interval_max fields of bt_le_adv_param struct according to
Bluetooth Core Specification 5.2

Signed-off-by: Alexey Tsvetkov <xeenych@gmail.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
@Xeenych why did you make three PRs for this? You can just `git commit --amend` and `git push --force` to the branch of the original PR if you need to change existing commits.

**Comment by Xeenych** [comment]
Sorry. New console git user.
Compliance check didn't like my username. I changed user.name in "git config" to Alexey Tsvetkov, and then tried git --amend, and --force, but author string still remained as Xeenych. So, I made another clean PR =).

**Comment by jhedberg** [comment]
@Xeenych no problem. FWIW, you could have used `git commit --amend --reset-author` or `git commit --amend --author=...`

**Comment by Xeenych** [comment]
Great. Thanks

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
