### PR TITLE
syscall: Export all emitted syscalls, enabling them for extensions

### PR DESCRIPTION
**Pull request by edersondisouza**
Linkable loadable extensions can only use syscalls if they are exported via EXPORT_SYSCALL (or EXPORT_SYMBOL). Instead of enabling used syscalls one by one, this patch exports all of them automatically via `gen_syscalls.py`. If CONFIG_LLEXT=n, the section where the exported symbols live is discarded, so it should be a non-op when llext is not enabled.

This patch also removes the now redundant EXPORT_SYSCALL macro. Note that EXPORT_SYMBOL is still useful on different situations (and is indeed used by the code generated by `gen_syscalls.py`).

### CODE REVIEW

**Review by teburd — APPROVED** [review]
Love it

**Review by cfriedt — APPROVED** [review]
LGTM

**Review by dcpleung — APPROVED** [review]

**Review by TaiJuWu — APPROVED** [review]

**Review by pillo79 — APPROVED** [review]
Awesome!

**Comment by selescop** [comment]
Would be great if we could select them. The table could be huge by containing unnecessary syscall. Also, if it is automatic, how do you warranty forward compatibility?

**Comment by edersondisouza** [comment]
> Would be great if we could select them. The table could be huge by containing unnecessary syscall. Also, if it is automatic, how do you warranty forward compatibility?

Note that only syscalls on enabled subsystems will be available, which should limit it somewhat. If the size of the relocation table becomes a problem, we could open an issue for that. Maybe using Kconfig to somehow filter unwanted syscalls? I'd really like to avoid touching code everywhere to filter things.

About the forward compatibility, could you please expand on your concern here? And how would that differ from a world where we somehow select the available syscalls?

**Comment by selescop** [comment]
> About the forward compatibility, could you please expand on your concern here? And how would that differ from a world where we somehow select the available syscalls?

Well, here the syscalls are created via a hash table which is based on alphanumeric order. Meaning, each time you add a new syscall, depending on its (macro) name, it can be added in "the middle" of the previous syscall table. This differs from the world as in the world, syscalls have a lifetime ID, as here it can change from a release to another one. ex:

LTS2:
`syscall AAAAAA -> ID=1`
`syscall CCCCCCC -> ID=2`

LTS3 adding syscall BBBBB:
`syscall AAAAAAA -> ID=1`
`syscall BBBBBBBB -> ID=2`
`syscal CCCCCCCC -> ID=3`

we break forward compatibility as CCCCC syscall ID changed over releases

**Comment by selescop** [comment]
> It’s been that way for a long time

Agreed, but this propagates the "issue" to the extension feature
> this PR isn’t addressing that issue

Well, it does indirectly. Let me give you an example.
1) build a firmware -> using lots of syscalls
2) build N extensions -> using 1 syscall only
Since here the export automatization is based on the firmware usage and not N extensions' one, you'll end up with a "big" table but only needed 1 in reality.

Few choices:
1. add them all and filter (as @edersondisouza said)
2. add them based on user input? conf file?
3. add them based on extensions builds

> seems like a good topic for a github issue

Ok, will do

**Comment by pillo79** [comment]
I think this PR neatly solves the issue of "patching every file to export a syscall", and it allows for a far easier way of experimenting with llext. 
Maybe I'm missing something, but I don't see how that relates to the Zephyr design choice of mapping syscalls via a hash table: even if you exported only a few of them, you would have the same "ID mismatch" issue if you then changed the list of syscalls implemented in the core... 
I definitely would like to come up with a solution for this, but it's a big enough topic to warrant a separate issue.

**Review by stephanosio — COMMENTED** [review]
@edersondisouza This seems to have somehow caused `tests/kernel/mem_protect/mem_map/kernel.memory_protection.mem_map` to fail on `qemu_x86_tiny`, as seen in [the recent CI runs](https://github.com/zephyrproject-rtos/zephyr/actions/runs/8434894369/job/23099251647#step:11:1638):

```
START - test_k_mem_map_unmap

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_protect/mem_map/src/main.c:276: mem_map_api_test_k_mem_map_unmap: (free_mem equal to 0)
no free memory
 FAIL - test_k_mem_map_unmap in 0.002 seconds
```



To reproduce:

```
scripts/twister -v -N -M -p qemu_x86_tiny -s tests/kernel/mem_protect/mem_map/kernel.memory_protection.mem_map
```

Any idea?

**Comment by pillo79** [comment]
@stephanosio This PR had some subtle issues that have been fixed in https://github.com/zephyrproject-rtos/zephyr/pull/70584. I can reproduce the issue with your test case on `main` but not on that PR's branch.

**Comment by stephanosio** [comment]
> @stephanosio This PR had some subtle issues that have been fixed in #70584. I can reproduce the issue with your test case on `main` but not on that PR's branch.

I can confirm that the above failure is no longer observed with #70584. Thanks!

**Comment by edersondisouza** [comment]
> @edersondisouza This seems to have somehow caused `tests/kernel/mem_protect/mem_map/kernel.memory_protection.mem_map` to fail on `qemu_x86_tiny`, as seen in [the recent CI runs](https://github.com/zephyrproject-rtos/zephyr/actions/runs/8434894369/job/23099251647#step:11:1638):
> 
> ```
> START - test_k_mem_map_unmap
> 
>     Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_protect/mem_map/src/main.c:276: mem_map_api_test_k_mem_map_unmap: (free_mem equal to 0)
> no free memory
>  FAIL - test_k_mem_map_unmap in 0.002 seconds
> ```
> 
> To reproduce:
> 
> ```
> scripts/twister -v -N -M -p qemu_x86_tiny -s tests/kernel/mem_protect/mem_map/kernel.memory_protection.mem_map
> ```
> 
> Any idea?

After a quick look, it seems this PR ended up spilling some stuff into the image/RAM, making it bigger, which can be a problem for qemu_x86_tiny. The good news is that those are fixed at #70584

**Pull request merged**
