### PR TITLE
Drivers nrf gpio remove hal

### PR DESCRIPTION
**Pull request by ioannisg**
Remove HAL definitions from NRF GPIO driver.

### CODE REVIEW

**Review by pizi-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by anangl — COMMENTED** [review]
The commit titles are misleading to me. I wouldn't name it HAL what is removed. These are just definitions of register structures. It could be done in one commit titled e.g. "drivers: gpio: nrf: remove redundant definitions of register structures".

**Comment by ioannisg** [comment]
@anangl thanks for your comment, I will re-work the commit titles. Maybe, though, keep separate commits (since they are separate register structure definitions ;) )

**Comment by ioannisg** [comment]
@anangl I re-worked the commit messages based on your suggestion (had to adapt to character limits for commit titles, though)

**Comment by anangl** [comment]
@ioannisg Good. Although, to be exact, there's no gpiote driver in Zephyr (apart from the nrfx one which is not involved here) and the second commit mentions such one. But I think I can live with it. ;-)

My proposal to do it in one commit came exactly from the limitation of the title length. I only wanted to avoid mentioning GPIO and GPIOTE in separate titles. No objections to use separate commits for these changes.

**Review by anangl — APPROVED** [review]

**Pull request merged**
