### PR TITLE
code_relocation: Add support for non-XIP code relocation copy

### PR DESCRIPTION
**Pull request by gramsay0**
Add config CODE_DATA_RELOCATION_COPY_ALL.
Enabling this option gives non-XIP the same code relocation behavior as XIP:
Set the linker virtual address (VMA) to the destination memory region, the load address (LMA) to `ROMABLE_REGION`, and copy the data into place during early initialization.

When enabled, the existing `NOCOPY` flag can be used to achieve the alternate behavior, putting the code/data directly into the destination memory region without a copy.

This is useful for non-XIP builds to relocate code/data to other RAM regions, while keeping the image as a single contiguous blob. Bootloaders like mcuboot can only load a single contiguous blob into RAM.

For example: stm32h7a3 has ITCM at address 0x0 and SRAM at 0x24000000. If some code were relocated from SRAM to ITCM the elf file would contain physical LOAD segments for both memory regions. This would require >576MB to represent as a contiguous blob

### CODE REVIEW

**Comment by gramsay0** [comment]
@carlocaione I noticed that you authored the code relocation `NOCOPY` feature.
Could you take a look at this draft?

In short, non-XIP would also copy by default, unless the `NOCOPY` flag is set

**Comment by andyross** [comment]
This seems maybe too general for its own good to me.  Does this really not break anything?

What if you have a platform with discontiguous linked sections but a loader that already handles the magic (intel_adsp works like this, copying stuff from "IMR" memory to SRAM at startup, via a custom binary format it parses in early boot, but note that it doesn't use code relocation).

Maybe we want this behind a kconfig (CONFIG_RELOCATE_COPY_ALL or somesuch?)  Or maybe relocation is an obscure enough feature that no one cares?

**Comment by gramsay0** [comment]
> This seems maybe too general for its own good to me. Does this really not break anything?
> 
> What if you have a platform with discontiguous linked sections but a loader that already handles the magic (intel_adsp works like this, copying stuff from "IMR" memory to SRAM at startup, via a custom binary format it parses in early boot, but note that it doesn't use code relocation).

@andyross in this current proposal you would have to add the `NOCOPY` flag to `zephyr_code_relocate()`:

| `CONFIG_XIP` | (no flag) | `NOCOPY` |
| --- | --- | --- |
| Yes  | Copy  | No copy |
| No  | Copy (previously no copy)  | No copy |

I kind of like the simplicity of this, although it could be a breaking change for some.
I thought this could be added to the migration guide, but maybe that is a bit naive.

> Maybe we want this behind a kconfig (CONFIG_RELOCATE_COPY_ALL or somesuch?)

Another alternative to maintain back compatibility would be to add (something like) a `FORCECOPY` flag:

| `CONFIG_XIP` | (no flag) | `NOCOPY` | `FORCECOPY` |
| --- | --- | --- | --- |
| Yes  | Copy  | No copy | Copy |
| No  | No copy  | No copy | Copy |

> Or maybe relocation is an obscure enough feature that no one cares?

Maybe, I don't know the answer to this

**Comment by andyross** [comment]
Ah, gotcha.  I guess given that NOCOPY exists there's no particular reason to have strong feelings about the sense of the flag.  Though I'm pretty sure I am right that this would be a breaking change to an app built against the current tree and (for whatever reason) expected the copy not to happen, right?

**Comment by gramsay0** [comment]
> Though I'm pretty sure I am right that this would be a breaking change to an app built against the current tree and (for whatever reason) expected the copy not to happen, right?

Yes, that would be a breaking change.

I modified the draft to wrap this functionality in a separate config `CODE_DATA_RELOCATION_COPY_ALL` as you suggested.
That keeps this modification simple, without risking breaking anyone's build

**Comment by gramsay0** [comment]
This doesn't seem to be generating much interest...
I can close this if people do not think it is beneficial enough to include upstream 🤷

**Pull request closed without merging**
