### PR TITLE
ext : hal : Microchip MEC1501 watch dog timer header update.

### LINKED ISSUE #18480: Microchip's MEC1501 HAL is broken (watchdog part)
Obvious bug:

ext/hal/microchip/mec/mec1501/component/wdt.h:50:28: error: invalid suffix "u1" on integer constant
 #define MCHP_WDT_CTRL_EN  (1u1 << (MCHP_WDT_CTRL_EN_POS))

And: 
- It lacks of some registers field pos/mask/en macros.
- Naming convention is not consistent either.

### PR DESCRIPTION
**Pull request by scottwcpg**
Add defines for WDT interrupt values, register access macros,
and fix typo bugs.

Fixes: #18480

Signed-off-by: Scott Worley <scott.worley@microchip.com>

### CODE REVIEW

**Review by franciscomunoz — APPROVED** [review]

**Comment by gnuless** [comment]
Hey, @scottwcpg, if this fixes #18480, then then you should say

Fixes: #18480 

in the comments somewhere.  Github does some fancy automated things with it in that case.

**Review by albertofloyd — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Comment by galak** [comment]
> Just curious, is the update in a released microchip HAL?

will this update go to https://github.com/MicrochipTech/Peripheral-mec1701 ?

**Comment by galak** [comment]
Needs to get moved to https://github.com/zephyrproject-rtos/hal_microchip

**Comment by nashif** [comment]
lets close this, HAL updates now to to module repo.

**Pull request closed without merging**
