### PR TITLE
Lis3dhh driver

### PR DESCRIPTION
**Pull request by markuspragerNexplore**

### CODE REVIEW

**Review by avisconti — CHANGES_REQUESTED** [review]
I think that every new  driver for ST sensors should be done taking into account following considerations:

1. Must use the stmemsc module API (including the i2c/spi common read/write routine)
2. Must specify configuration in DT, in order to be able to specify different options for different driver instances.

You can refer to lis2ds12 or lis2dw12 for examples.

**Comment by markuspragerNexplore** [comment]
> I think that every new driver for ST sensors should be done taking into account following considerations:
> 
>     1. Must use the stmemsc module API (including the i2c/spi common read/write routine)
> 
>     2. Must specify configuration in DT, in order to be able to specify different options for different driver instances.
> 
> 
> You can refer to lis2ds12 or lis2dw12 for examples.

So I have been adapting the driver to accommodate your requests, however I am not able to build the new driver. 

/zephyr/drivers/sensor/lis3dhh/lis3dhh.h:26:10: fatal error: stmemsc.h: No such file or directory
   26 | #include <stmemsc.h>
 
Do I need to enable stmemsc functionality in the menuconfig somewhere maybe? I have not been able to find any option to do so.

**Comment by avisconti** [comment]
> > I think that every new driver for ST sensors should be done taking into account following considerations:
> > ```
> > 1. Must use the stmemsc module API (including the i2c/spi common read/write routine)
> > 
> > 2. Must specify configuration in DT, in order to be able to specify different options for different driver instances.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can refer to lis2ds12 or lis2dw12 for examples.
> 
> So I have been adapting the driver to accommodate your requests, however I am not able to build the new driver.
> 
> /zephyr/drivers/sensor/lis3dhh/lis3dhh.h:26:10: fatal error: stmemsc.h: No such file or directory 26 | #include <stmemsc.h>
> 
> Do I need to enable stmemsc functionality in the menuconfig somewhere maybe? I have not been able to find any option to do so.

You have to add in CMakeLists.txt following line: 
zephyr_library_include_directories(../stmemsc)

**Comment by markuspragerNexplore** [comment]
> @markuspragerNexplore Maybe you can take a look to PR #35841

That is actually helpful, thanks :) 

However, having fixed the issue with including stmemsc.h, I now have the problem that i can't include lis3dhh_reg.h 

/zephyr/drivers/sensor/lis3dhh/lis3dhh.h:27:10: fatal error: lis3dhh_reg.h: No such file or directory
   27 | #include "lis3dhh_reg.h"
      |          ^~~~~~~~~~~~~~~

How do I get west to include the correct directories?

**Comment by markuspragerNexplore** [comment]
@avisconti How should I be addressing configurations that depend on other configurations? For example FIFO Threshold configuration options depend on whether FIFO is actually enabled or not. Is there a way to do this similarly in .yaml as in Kconfig? "depends_on" gives me an error, so that seems to be for something else.

**Review by tejlmand — CHANGES_REQUESTED** [review]
The PR message says:
>  *No description provided.* 

Commit messages are like this:
> Added lis3dhh driver functionality
> Signed-off-by: Markus Prager <markus.prager@nexplore.com>

> Changed tabs into spaces in .yaml file to comply with twister demands…
> …. Reformatted Kconfig to also comply with twister demands.
> Signed-off-by: Markus Prager <markus.prager@nexplore.com>

and then there are merge commits.

Could you please rebase this PR and remove merge commits and then write some proper commit messages so that this PR can be reviewed.

Thanks in advance.

**Comment by avisconti** [comment]
> The PR message says:
> 
> > _No description provided._
> 
> Commit messages are like this:
> 
> > Added lis3dhh driver functionality
> > Signed-off-by: Markus Prager [markus.prager@nexplore.com](mailto:markus.prager@nexplore.com)
> 
> > Changed tabs into spaces in .yaml file to comply with twister demands…
> > …. Reformatted Kconfig to also comply with twister demands.
> > Signed-off-by: Markus Prager [markus.prager@nexplore.com](mailto:markus.prager@nexplore.com)
> 
> and then there are merge commits.
> 
> Could you please rebase this PR and remove merge commits and then write some proper commit messages so that this PR can be reviewed.
> 
> Thanks in advance.

Yes, correct! Thanks! 
Concerning the commit message you can take a look here: https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines

**Comment by avisconti** [comment]
@markuspragerNexplore  Do you still want to proceed on this PR?

**Pull request closed without merging**
