### PR TITLE
Exclude Storage Partition from the available image flash area

### PR DESCRIPTION
**Pull request by ioannisg**
Addresses #27471

The problem:
The storage partition is not visible to the linker, When code-partition is NOT used, the image code area may step into the storage partition, which may lead to problems hard to debug.

Proposed solution (in this PR):
- Describe in Boards DeviceTree the reserved flash area that shall not be accessible to the image
- Define the corresponding Kconfig symbols
- Use the Kconfig symbols in the Cortex-M linker to exclude the area from the image code space

Notes
- Only required when the build does not use the DT CODE PARTITION
- Only addressed for Nordic nRF DKs - should be extended to all in-tree board definitions

Limitations:
- Efficient only when the reserved area is at the end of the flash area (majority of the cases)

### CODE REVIEW

**Comment by Laczen** [comment]
@ioannisg, when code-partition is not used, what is the meaning of the flash division ? IMO if you want to use the flash division as described by the dts you should mandatory use code-partition. If the board dts file does not describe what is needed, it should be overriden.

**Comment by ioannisg** [comment]
> @ioannisg, when code-partition is not used, what is the meaning of the flash division ? IMO if you want to use the flash division as described by the dts you should mandatory use code-partition. If the board dts file does not describe what is needed, it should be overriden.

@Laczen thanks for the feedback, I also had the same thought. However, there's a challenge: mandatory use of code partition means mandatory using a bootloader as well, and this cannot be accepted as a default solution.

**Comment by ioannisg** [comment]
> when code-partition is not used, what is the meaning of the flash division ?

To elaborate more: users might not want to use the code partition, together with bootloader, and instead use the whole available flash. But they need to exclude the storage partition at the end. 

We need to find a solution that is backwards compatible with the current situation and still addresses the rather serious bug of having the zephyr code overlap with the storage space.

Forcing to use code-partition is not backwards-compatible.

I am open for alternative suggestions of course.

**Comment by Laczen** [comment]
> > when code-partition is not used, what is the meaning of the flash division ?
> 
> To elaborate more: users might not want to use the code partition, together with bootloader, and instead use the whole available flash. But they need to exclude the storage partition at the end.
> 
> We need to find a solution that is backwards compatible with the current situation and still addresses the rather serious bug of having the zephyr code overlap with the storage space.
> 
> Forcing to use code-partition is not backwards-compatible.
> 
> I am open for alternative suggestions of course.

Maybe we can just define the default behavior using code-partition: The default flash layout could just be: code-partition and storage-partition. I never understood why mcuboot is dictating the flash layout, maybe it is time to correct this.

**Comment by ioannisg** [comment]
> Maybe we can just define the default behavior using code-partition: The default flash layout could just be: code-partition and storage-partition. 

So, my patch is sort of doing this thing:
- defines a reserved flash area (for storage and/or for anything else that the image cannot use)
- rest of flash for code.

This is still the default. MCUboot enables USE_DT_CODE_PARTITION, and forces the flash layout, but that is not default.

> I never understood why mcuboot is dictating the flash layout, maybe it is time to correct this.

I guess the reason is that the partitions need to be statically defined in DeviceTree (which runs before Kconfig) and we need to account for whether we do need to use bootloader and image slots or not.

@Laczen if you can share a draft of your proposal and how it should work, feel free to post it here.

@mbolivar-nordic @nvlsianpu I hope you could give some feedback here, as well.

**Comment by mbolivar-nordic** [comment]
> Forcing to use code-partition is not backwards-compatible.

I don't follow this. The storage partition is defined in DT. Arguably, using the storage partition but not the code partition was always wrong.

**Comment by ioannisg** [comment]
> > Forcing to use code-partition is not backwards-compatible.
> 
> I don't follow this. The storage partition is defined in DT. Arguably, using the storage partition but not the code partition was always wrong.

Code partition is needed only when we deal with chain-loadable zephyr images, e.g. together with MCUboot, and/or in the case of Secure/Non-Secure images.

Storage partition may also be used outside this scenario; one may not care at all about bootloaders, but still wants to reserve some area for storage.

If we now force to use DT CODE PARTITION whenever storage partition is used, we will break compatibility with the above use cases.

**Comment by ioannisg** [comment]
> I guess the reason is that the partitions need to be statically defined in DeviceTree (which runs before Kconfig) and we need to account for whether we do need to use bootloader and image slots or not.

@mbolivar-nordic this is where i see the problem. All partitions are defined statically, and the are not aware of whether they are being used or not. This is decided later, with Kconfig.

**Comment by mbolivar-nordic** [comment]
> Code partition is needed only when we deal with chain-loadable zephyr images, e.g. together with MCUboot, and/or in the case of Secure/Non-Secure images.

No it's not. It's the partition that code goes into.

**Comment by mbolivar-nordic** [comment]
@ioannisg I think you're not understanding the purpose of the code partition.

There's nothing that's chain-loading specific about it.

You can read the documentation here: https://docs.zephyrproject.org/latest/reference/devicetree/index.html#chosen-nodes

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
I don't think this is the right approach for the reasons I mentioned above.

**Comment by ioannisg** [comment]
> I don't think this is the right approach for the reasons I mentioned above.

@mbolivar-nordic  I assume you insist on forcing the use of DT CODE PARTITION, whenever the storage partition is to be used by the application, is that correct?

Here's a typical default Zephyr board flash layout:

```
partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;

		boot_partition: partition@0 {
			label = "mcuboot";
			reg = <0x00000000 0xc000>;
		};
		slot0_partition: partition@c000 {
			label = "image-0";
			reg = <0x0000C000 0x32000>;
		};
		slot1_partition: partition@3e000 {
			label = "image-1";
			reg = <0x0003E000 0x32000>;
		};
		scratch_partition: partition@70000 {
			label = "image-scratch";
			reg = <0x00070000 0xa000>;
		};
		storage_partition: partition@7a000 {
			label = "storage";
			reg = <0x0007a000 0x00006000>;
		};
	};
```
 So, if a Zephyr application wants to use the storage partition, it will have to use the code-partition as well. Code partition is usually slot0_partition. This partition does not start at address 0x0, so the image needs to be chain-loadable by a parent image, at least for Cortex-M.

How would this work without a bootloader? This is the challenge I am talking about, otherwise, like I said, I am fine going with this.

**Comment by nvlsianpu** [comment]
> Forcing to use code-partition is not backwards-compatible.

I'm in line with this. But maybe we can switch to use the code-partition silently

Problem here is that partition layout with and without mcuboot differs each other.  Second problem is that Kconfig goes after DT - so build system is unable to choice proper partition layout basing on CONFIG_BOOTLOADER_MCUBOOT.
We never really defined layout without MCUBoot in DTS. Solution might be to switch to:
- provide non-mcuboot layout for each boards as the default
- provide overlay with mcuboot-enabled partition layout for each board (we can)
- set default for CONFIG_BOOTLOADER_MCUBOOT basing on existence of the boot-partition in DTS
- start to always use code partition.

This will keep backward compatibility while building. Building for MCUBoot will require to inject overlay file (but no need to set CONFIG_BOOTLOADER_MCUBOOT=y explicitly anymore), would be great if path in relation to the board directory will might be used.

**Comment by ioannisg** [comment]
@nvlsianpu I have been working on _just_ this thing earlier today. Let me post a new draft PR, to share this with the reviewers. :)

**Pull request closed without merging**
