### PR TITLE
move syst initialization code to zephyr tree and Add more useful fields in SyS-T message packet

### PR DESCRIPTION
**Pull request by wentongwu**
1. move syst initialization code to zephyr tree
2. Add more useful fields (payload length and timestamp) in SyS-T message packet.

Signed-off-by: Wentong Wu <wentong.wu@intel.com>

### CODE REVIEW

**Comment by wentongwu** [comment]
This PR depends on https://github.com/zephyrproject-rtos/mipi-sys-t/pull/1 and also we may have to update west.yml. @nashif

**Comment by wentongwu** [comment]
the only failure is not related.
```
[93/138] Building C object zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_shell.c.obj
FAILED: zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_shell.c.obj 
ccache /opt/sdk/zephyr-sdk-0.11.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBOARD_FLASH_SIZE=CONFIG_FLASH_SIZE -DBUILD_VERSION=zephyr-v2.2.0-2428-gf9d88ae88475 -DCPU_MK64FN1M0VLL12 -DKERNEL -DNDEBUG -D_FORTIFY_SOURCE=2 -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../../../../../../include -Izephyr/include/generated -I../../../../../../soc/arm/nxp_kinetis/k6x -I../../../../../../lib/fnmatch/. -I/home/buildslave/src/github.com/zephyrproject-rtos/modules/hal/cmsis/CMSIS/Core/Include -I/home/buildslave/src/github.com/zephyrproject-rtos/modules/hal/nxp/mcux/devices/MK64F12 -I/home/buildslave/src/github.com/zephyrproject-rtos/modules/hal/nxp/mcux/drivers/kinetis/. -isystem ../../../../../../lib/libc/minimal/include -isystem /opt/sdk/zephyr-sdk-0.11.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/9.2.0/include -isystem /opt/sdk/zephyr-sdk-0.11.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/9.2.0/include-fixed -Os -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/sanity-out/frdm_k64f/tests/boards/board_shell/boards.shell.shell/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mcpu=cortex-m4 -mthumb -mabi=aapcs -imacros/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-address-of-packed-member -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -Werror -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/boards/board_shell=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/buildslave/src/github.com/zephyrproject-rtos=WEST_TOPDIR -ffunction-sections -fdata-sections -std=c99 -nostdinc -MD -MT zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_shell.c.obj -MF zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_shell.c.obj.d -o zephyr/drivers/adc/CMakeFiles/drivers__adc.dir/adc_shell.c.obj   -c /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/adc/adc_shell.c
In file included from /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/adc/adc_shell.c:7:
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/adc/adc_shell.c:477:22: error: expected expression before ',' token
  477 |  ADC_SHELL_COMMAND(0),
      |                      ^
../../../../../../include/shell/shell.h:219:3: note: in definition of macro 'SHELL_STATIC_SUBCMD_SET_CREATE'
  219 |   __VA_ARGS__      \
      |   ^~~~~~~~~~~
```

**Comment by wentongwu** [comment]
ping

**Comment by nashif** [comment]
please adapt manifest

**Comment by wentongwu** [comment]
@nashif do you mean update west.yml?

**Review by nashif — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
