### PR TITLE
[TOPIC-BLE-LLCP] LLCP data path

### PR DESCRIPTION
**Pull request by thoh-ot**

### CODE REVIEW

**Comment by thoh-ot** [comment]
Sorry for the review spam

**Comment by thoh-ot** [comment]
Created a new PR https://github.com/zephyrproject-rtos/zephyr/pull/31978 for commit a89a79f44c3242ee78cfd04ab3e99042c23149d3 - this PR needs to be rebased when that is merged

**Review by kruithofa — APPROVED** [review]
LGTM

**Review by erbr-ot — APPROVED** [review]
Thanks for the walk-through

**Pull request merged**
