### PR TITLE
net: openthread: Fix RCP stuck in forever loop in uart_callback

### PR DESCRIPTION
**Pull request by yurvyn**
Issue description:
If run OpenThread RCP device (net/openthread/coprocessor sample) using tlsr9518adk80d board for many hours with several thread devices connected to the RCP, the RCP stuck in uart_callback for forever.
The issue potentially could be reproduced with other boards,  see the description below.

**Forever Loop description:**
1. `uart_callback` is running
``` 
103 static void uart_callback(const struct device *dev, void *user_data)
104 {
105	ARG_UNUSED(user_data);
106
107	while (uart_irq_update(dev) && uart_irq_is_pending(dev)) {
108
109		if (uart_irq_rx_ready(dev)) {
110			uart_rx_handle(dev);
111		}
112
113		if (uart_irq_tx_ready(dev) &&
114		    atomic_get(&ot_uart.tx_busy) == 1) {
115			uart_tx_handle(dev);
116		}
117	}
118}
```
2. `uart_irq_is_pending(dev)` (line 107) returns `true` because TX IRQ is enabled, to clear pending flag need to disable TX IRQ. 
3. Disabling of TX IRQ is part of `uart_tx_handle` (line 115) but it is not called because `ot_uart.tx_busy` equals 0 (line114).
4. So, forever loop happens if TX IRQ is enabled and `ot_uart.tx_busy` equals 0.

**How it is possible that TX IRQ is enabled and  `ot_uart.tx_busy` equals 0. Description:**

 `otPlatUartSend` is running (original version)
```
221 otError otPlatUartSend(const uint8_t *aBuf, uint16_t aBufLength)
222 {
223	if (aBuf == NULL) {
224		return OT_ERROR_FAILED;
225	}
226
227	if (atomic_cas(&(ot_uart.tx_busy), 0, 1)) {
228		write_buffer = aBuf;
229		write_length = aBufLength;
230
231		if (is_panic_mode) {
232			/* In panic mode all data have to be send immediately
233			 * without using interrupts
234			 */
235			otPlatUartFlush();
236		} else {
237			uart_irq_tx_enable(ot_uart.dev);
238		}
239		return OT_ERROR_NONE;
240	}
241
242	return OT_ERROR_BUSY;
242}
```
If RX IRQ happens between line 227 and 229 (when `tx_busy` is already set to 1 but `write_length` is not set yet), the `ot_uart.tx_busy` flag is set back to 0 inside `uart_callback`: `uart_irq_tx_ready` returns true (line 113) because TX buffer is empty,  `ot_uart.tx_busy` also is true (line 114) because we have just set it to 1 and as result `uart_tx_handle` is called (line 115). `uart_tx_handle` sets `ot_uart.tx_busy` flag to 0 if `write_length` equals 0.
So, when we com back to line 237, here we enable TX IRQ and `ot_uart.tx_busy` is 0.

**SOLUTION:**
`write_length` must be set before `ot_uart.tx_busy`.

### CODE REVIEW

**Comment by rlubos** [comment]
Thank you for the detailed description. One thing bugs me though, All of the three variables, `tx_busy`, `write_buffer` and `write_length` are set **before** TX IRQ is enabled with `uart_irq_tx_enable(ot_uart.dev);`.

So it makes me wonder - why would the `uart_irq_tx_ready()` inside `uart_callback()` return `true` in such case? @anangl I couldn't find it state explicitly, but could you clarify whether it's ok for `uart_irq_tx_ready()` to return `true` even if the TX IRQ is not enabled? If so, perhaps we need some additional check to verify if the IRQ is enabled or not. Otherwise, I think it might be an issue with the underlying UART driver you're using.

**Comment by yurvyn** [comment]
According to the UART driver documentation the `uart_irq_tx_ready` function just check for TX buffer can accept a new char.
The 'irq' in the function name just implies that this function must be called only from IRQ handler.

Noting more:

```
Check if UART TX buffer can accept a new char.
Check if UART TX buffer can accept at least one character for transmission (i.e. uart_fifo_fill() will succeed and return non-zero). 
This function must be called in a UART interrupt handler, or its result is undefined. 
Before calling this function in the interrupt handler, uart_irq_update() must be called once per the handler invocation.

Returns: 
1 – If at least one char can be written to UART.
0 – If device is not ready to write a new byte.
-ENOSYS – if this function is not supported.
-ENOTSUP – if API is not enabled.
```

So, looks like, it is not an issue of uart_b91 driver implementation.
Hoverer, I have just checked the implementation of other the UART drivers and some of them indeed additionally check for TX IRQ enabled (e.g. uart_nrfx_uart.c).

At least the next drivers check only for TX buffer (ignoring TX IRQ enabled):
- uart_b91.c
- uart_esp32.c
- uart_psoc6.c
- uart_liteuart.c
- uart_npcx.c
- uart_cc16xx_cc26xx.c

**Comment by anangl** [comment]
Yes, please. I see no reason to not add it as a clear requirement. In fact, it should have been done long time ago, as it would have helped prevent a lot of confusion in this regard.

**Review by anangl — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
LGTM

**Pull request merged**
