### PR TITLE
Bluetooth: host: Fix L2CAP reconfigure response

### PR DESCRIPTION
**Pull request by sjanc**
If the MTU value is decreased for any of the included channels, then
the receiver shall disconnect all  included channels. Disconnection
shall happen after reconfigure response is sent.

This was affecting L2CAP/ECFC/BI-03-C qualification test case.

Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

### CODE REVIEW

**Comment by Thalley** [comment]
@sjanc Can you provide me with the spec location where it says that channels shall be disconnected?

The only part about re-configuring a credit based channel I can find is 
image
 which does not specify that the channels shall be disconnected.

**Comment by sjanc** [comment]
Hi,

This comes from Test Spec requirements (see L2CAP/ECFC/BI-03-C).
I agree that it is a bit odd...

**Comment by Thalley** [comment]
> Hi,
> 
> This comes from Test Spec requirements (see L2CAP/ECFC/BI-03-C). I agree that it is a bit odd...

Indeed. Will you try to investigate that a bit? 

From the test case:
image

I assume that they disconnect behavior is from step 3, which seems unrelated to the request itself. In fact, step 2 explicitly states that the channel shall not be disconnected, and we should just return a response with the correct error code. 

The MSC does also not contain the disconnect part: 
image

There's not really any reason why the IUT should autonomously disconnect the channel(s). I wonder if it was meant to be the upper tester and not the IUT that initiates the disconnect request?

**Comment by alwa-nordic** [comment]
I agree. The PTS test must be incorrect. The Core spec does not say that the IUT should disconnect. Also the test spec itself does not seem to require the disconnect either.

From L2CAP.TS.p33ed2.pdf:
image

We should remove the current logic that triggers the disconnect.

**Comment by sjanc** [comment]
Test Spec explicitly requires disconnection in step 3 of test so PTS is acting according to TS.
I'll create an errata to remove step 3 from test

**Comment by sjanc** [comment]
FYI TSE 18813

**Comment by Thalley** [comment]
> FYI TSE 18813

If this gets approved then I suppose we'll need to remove the existing disconnect behavior?

**Comment by sjanc** [comment]
yes, I'll rework PR once it is approved

**Comment by sjanc** [comment]
TSE is now approved

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by cfriedt** [comment]
@sjanc - is there an issue for Qualification? L2CAP/ECFC/BI-03-C

We need an issue for the backport to v2.7 in #46600

**Pull request merged**
