### PR TITLE
llext: add build commands and tests for relocatable ELFs 

### PR DESCRIPTION
**Pull request by pillo79**
This PR introduces build support in the llext subsystem for relocatable objects, and a Twister test for validating this PR and #70793, which added llext support for them. It is intended to replace #70991 by providing the same result on the new CMake infrastructure merged in #67997. 

It does so by:
* introducing the `LLEXT_BINARY_TYPE` Kconfig, to select the build type among _object files_, _relocatable files_, or _shared libraries_, effectively making CMake code for llext almost arch-independent. The automatic defaults are for the tested combinations, but this gives developers more freedom to experiment. 
* relaxing `add_llext_target` rules to support multiple source files for the binary types that include a link step;
* adding build support for the relocatable case;
* incorporating the last 2 commits of #70991 from @lyakh adding support for zero-based addresses and a relocatable test case.

### CODE REVIEW

**Review by lyakh — APPROVED** [review]
Thanks! Tested locally too.

**Review by teburd — APPROVED** [review]

**Review by marc-hb — COMMENTED** [review]
You're removing `message(FATAL_ERROR "add_llext_target: unsupported architecture")`. So isn't that enough to remove the `LOADER_BUILD_ONLY` test limitation?

**Comment by pillo79** [comment]
> You're removing `message(FATAL_ERROR "add_llext_target: unsupported architecture")`. So isn't that enough to remove the `LOADER_BUILD_ONLY` test limitation?

Good idea! I have tried removing the barriers but I get a weird error on `x86`, `native` and `a53` arches:
```
In file included from zephyr/include/zephyr/toolchain.h:50,
                 from zephyr/include/zephyr/sys/__assert.h:11,
                 from zephyr/include/zephyr/sys/iterable_sections.h:10,
                 from zephyr/include/zephyr/llext/symbol.h:10,
                 from zephyr/tests/subsys/llext/simple/src/relative_jump_ext.c:15:
zephyr/include/zephyr/toolchain/gcc.h:573:2: error: #error processor architecture not supported
  573 | #error processor architecture not supported
      |  ^~~~~
```
(and all other llext tests). The compiler is missing `autoconf.h`; this is due to the fact that on these arches, the `build.ninja` rules for llext code _have no `FLAGS =` line at all_, even though the CMake code is obviously the same as the arches we are testing. This is next level for me as well... :man_shrugging:

**Review by tejlmand — APPROVED** [review]

**Comment by pillo79** [comment]
> on these arches, the build.ninja rules for llext code have no FLAGS = line at all, even though the CMake code is obviously the same as the arches we are testing. This is next level for me as well... 🤷‍♂️

_blah blah_ daemons _blah blah_

Turns out the solution was dumb - arches where LLEXT is not tested yet do not define an `LLEXT_REMOVE_FLAGS` variable, so the code turns it into an empty regexp, which promptly results in `$<FILTER:...>` erasing the whole list of Zephyr flags. :man_facepalming: 

I have this fixed locally, however since the PR is already approved I will open a separate one with this cleanup/refactor as soon as this lands.

**Comment by marc-hb** [comment]
> Turns out the reason was way clearer 

Nice! Well done.

> since the PR is already approved...

Agreed.

Note dropping LOADER_BUILD_ONLY is the ultimate goal BUT if you have it to keep it for some more time and gradually increase the list of architectures that actually run tests instead then it would be great progress too. A first, 64bits arch passing the tests would be an especially big milestone!

**Pull request merged**
