### PR TITLE
boards: arm: add support for NUCLEO-L053R8

### PR DESCRIPTION
**Pull request by akreft**
Add support for NUCLEO-L053R8 board with STM32L053R8 SoC.

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
Nice. Thanks.

**Review by erwango — CHANGES_REQUESTED** [review]
One minor comment, otherwise looks good!
Thanks

**Comment by akreft** [comment]
@erwango I updated the 'supported' section in the yaml file. Thanks for the review!

**Review by erwango — APPROVED** [review]

**Review by ydamigos — APPROVED** [review]

**Comment by akreft** [comment]
@erwango @ydamigos I'm new to the process. I'm sure this is a low priority pull request but what is typically the next step for merging once a pull request is approved? Do the pull requests get reviewed regularly by maintainers to identify merge candidates or do I have to request a merge? Also, Shippable and Codecov are showing errors. Are there any problems I have to fix to pass those checks? Thank you.

**Comment by ydamigos** [comment]
@akreft I checked shippable report and find out that some tests fail with the following error:
```
region `SRAM' overflowed
```
You can run sanitycheck locally to find out which tests fail. One test fails with the following error:
```
Commit 66468e965e:
3: UC4 Line exceeds max length (75>72): "Add support for the STM32L053X8 microcontroller on the NUCLEO-L053R8 board."
```

**Comment by galak** [comment]
@akreft the expectation is that CI has to pass for this to get merged.  As @ydamigos mentioned you can run sanitycheck locally so see what issues this new board port introduces:

./scripts/sanitycheck -p nucleo_l053r8

**Comment by akreft** [comment]
@galak I ran the sanity check as you described and it appears that many or all of the errors are due to SRAM overflow because this SoC has only 8K of SRAM. Is there a way to bypass these failing tests?

**Comment by erwango** [comment]
@akreft , I come back on what I proposed yesterday, sorry:
Before setting min_ram to 16Kb on samples/tests. Can you try deactivating one or more GPIOs on your board and check if working? 
Looking to the (rather long) list of impacted tests/samples, it would be nice to keep these working at minimum ram level. So, if deactivating some GPIOs allows to pass the test, let's do it. Same approach has been used on some other boards, such as nucleo_f030r8.

**Comment by akreft** [comment]
@erwango Thanks for the suggestion. I deactivated ports D and H as part of the defconfig and reduced the SRAM usage by 48 bytes. For the philosophers sample, for example, I am still at 9508 bytes of SRAM after disabling the two GPIO ports. The nucleo_f030r8 uses 7548 bytes of SRAM for the same sample and has the same increase of 48 bytes when I enable the two GPIO ports. Maybe there is a difference in the HAL libraries of the L0 and F0.

**Comment by erwango** [comment]
@akreft : On nucleo_f030r8, seems they also apply following custom stack size settings:
```
CONFIG_MAIN_STACK_SIZE=640
CONFIG_IDLE_STACK_SIZE=200
CONFIG_ISR_STACK_SIZE=512
```

**Comment by akreft** [comment]
@erwango : Thank you! It is finally passing all checks. I added the boot loader config settings shown below in addition to the stack size settings since the nucleo_f030r8 also had these settings as part of the effort to conserve SRAM usage.

```
CONFIG_IS_BOOTLOADER=y
CONFIG_BOOTLOADER_SRAM_SIZE=8
```

**Review by galak — APPROVED** [review]

**Pull request merged**
