### PR TITLE
Bluetooth: ISO: Add misisng disconnect reason to big_disconnect

### PR DESCRIPTION
**Pull request by Thalley**
A few calls to big_disconnect was missing the disconnect reason
due to a bad rebase.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
This was breaking CI on several PRs, as far as I could see.

**Review by joerchan — APPROVED** [review]

**Comment by Thalley** [comment]
Updated to fix spelling error in commit message.

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
@Thalley seems like CI caught some additional build issues

**Review by gmarull — APPROVED** [review]

**Comment by carlescufi** [comment]
> @Thalley seems like CI caught some additional build issues

I'll fix these and push here.

**Comment by ioannisg** [comment]
> > @Thalley seems like CI caught some additional build issues
> 
> I'll fix these and push here.

Thanks, this might be breaking other PRs at the moment.

**Pull request merged**
