### PR TITLE
drivers: pwm: nrf: Use HW PWM by default when available

### PR DESCRIPTION
**Pull request by anangl**
**drivers: pwm: nrf: Use HW PWM by default when available**

Enable HW PWM driver instead of the SW one on nRF SoCs where the PWM
peripheral is present.
Default PWM instances are also enabled on Nordic DK boards so that it
is possible to build the basic fade_led sample for them without extra
adjustments.

After the above changes are applied, some configuration alterations
in basic samples blink_led and fade_led become no longer needed.
These are removed. And the blink_led sample is corrected so that it
works with the nRF HW PWM driver as well.

**boards: nrf: Indicate pwm as supported on Nordic DK boards**

Indicate that PWM is supported on several Nordic DK boards so that
the pwm_nrf5_sw and pwm_nrfx drivers are covered by CI builds.

Related to #12860.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Review by ioannisg — COMMENTED** [review]
Looks ok to me
How were the pins selected? Arbitrary?

**Comment by anangl** [comment]
> How were the pins selected? Arbitrary?

These are LED0 pins on respective boards. Both samples (blink_led and fade_led) use this pin to visualize their job.

**Comment by ioannisg** [comment]
> 
> 
> > How were the pins selected? Arbitrary?
> 
> These are LED0 pins on respective boards. Both samples (blink_led and fade_led) use this pin to visualize their job.

I am refering to the pin setting in the board DTS file. So, as I understand, the pin numbers for PWM in the board DTS files are selected so that the samples with LED0 can execute properly, is this correct?

Just pointing out that the board default configuration (looks like it) depends on some samples. I don't see it as problem - we need to have some default config anyways.

**Review by nashif — APPROVED** [review]

**Comment by anangl** [comment]
> > > How were the pins selected? Arbitrary?
> > 
> > 
> > These are LED0 pins on respective boards. Both samples (blink_led and fade_led) use this pin to visualize their job.
> 
> I am refering to the pin setting in the board DTS file. So, as I understand, the pin numbers for PWM in the board DTS files are selected so that the samples with LED0 can execute properly, is this correct?

Yes.

> Just pointing out that the board default configuration (looks like it) depends on some samples. I don't see it as problem - we need to have some default config anyways.

Exactly, some default settings are needed. It feels natural to choose ones that can be used directly in some basic samples.

**Review by ioannisg — APPROVED** [review]

**Comment by anangl** [comment]
Rebased on master to resolve the merge conflicts in .yaml files.

**Comment by lemrey** [comment]
Nice!

**Pull request merged**
