### PR TITLE
nvs: Fix deletion of the last entry added

### LINKED ISSUE #18813: fs: nvs: Cannot delete entries
when I first call `nvs_init()` function, _this time FLASH space ALL is 0xFF_.
then I write entry just like this:` nvs_write(&fs, 1, buf, 1);`
then I delete this entry: `nvs_delete(&fs, 1);`
then, I read:` nvs_read(&fs, 1, buf1, 1);` **Successful return**

```C
while (1) {
		rd_addr = wlk_addr;
		rc = nvs_prev_ate(fs, &wlk_addr, &wlk_ate);
		if (rc) {
			return rc;
		}
		if ((wlk_ate.id == id) && (!nvs_ate_crc8_check(&wlk_ate))) {
			break;
		}
		if (wlk_addr == fs->ate_wra) {
			break;
		}
	}

	if (wlk_addr != fs->ate_wra) {
```

just like above code show, when i call `nvs_delete`, the loop find prev entry,and finally find it, then break the loop, but `if (wlk_addr != fs->ate_wra) ` is **false**.

### PR DESCRIPTION
**Pull request by carlescufi**
Make sure that the last entry added is deleted correctly by storing the
fact that one was found in a local variable.

Fix by Laczen JMS <laczenjms@gmail.com>

Fixes #18813.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
@nvlsianpu @Laczen the test suite run failed, could you take a look and see if you can share what the issue is?

**Comment by Laczen** [comment]
@carlescufi, @nvlsianpu, this was something nasty to find. The fix should be ok, but it brought up an error in the test: The test should fail at the specified location because it is trying to rewrite the same data. The fix for the test is simple: remove line 506 (filling_id--) in test main.c

**Comment by carlescufi** [comment]
> @carlescufi, @nvlsianpu, this was something nasty to find. The fix should be ok, but it brought up an error in the test: The test should fail at the specified location because it is trying to rewrite the same data. The fix for the test is simple: remove line 506 (filling_id--) in test main.c

Thank you @Laczen. I have now updated the test.

**Review by wentongwu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
> @carlescufi, @nvlsianpu, this was something nasty to find. The fix should be ok, but it brought up an error in the test: The test should fail at the specified location because it is trying to rewrite the same data. The fix for the test is simple: remove line 506 (filling_id--) in test main.c

@Laczen good catch - I missed this, test was passing among other things, because this bug was present.

**Review by nvlsianpu — APPROVED** [review]
Thanks for the fix, works very well.

**Comment by nvlsianpu** [comment]
I will back-port this manually once merged. (I expect automatic back-port failure)

**Pull request merged**
