### PR TITLE
[RFC][DNM]:Bluetooth: controller: Fix mayfly enqueue race

### PR DESCRIPTION
**Pull request by cvinayak**
A mayfly function re-execution is being missed due to the
mayfly dequeue in mayfly_run function being interrupted by
a mayfly_enqueue while the executed mayfly is dequeued.

This is fixed by re-inserting the mayfly struct back into
the queue on detection of this race condition.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by galak** [comment]
Is this still relevant, need to be opened?

**Comment by carlescufi** [comment]
@aescolar @stko-ot please review

**Comment by aescolar** [comment]
It was @stko-ot who found the issue and discussed it initially with @cvinayak. I'd have assumed he'd had provided feedback offline, as @cvinayak took in another, a bit more elaborate, patch in his wip branch.
So I guess @cvinayak can confirm if this PR can already be closed.

**Comment by cvinayak** [comment]
Will close this and will include it part of the new architecture changes PR.

**Pull request closed without merging**
