### PR TITLE
Clock_control: Light cleanup and refactoring of stm32 driver

### PR DESCRIPTION
**Pull request by erwango**
Factorize series specific code in stm32 clock control driver (using fact that some series use the same RCC blocks).
Refactor related STM32 Kconfig file to take advantage of the previous change and increase readability.

EDIT: Had to remove `/drivers/clock_control/*stm32f4*` line from CODEOWNERS. @rsalveti, @idlethread, please scream/raise hand (select the most appropriate) if you want to proceed otherwise.

### CODE REVIEW

**Comment by avisconti** [comment]
@erwango
The code LGTM.
Have you tested it extensively? Do you want me to perform some other tests on my h/w? (Don't know
when I could do that though)

**Comment by erwango** [comment]
Set as DNM waiting for additional tests

**Comment by erwango** [comment]
Basic tests performed on all series

**Review by mbolivar — APPROVED** [review]
LGTM, nice cleanup :)

**Review by Mani-Sadhasivam — APPROVED** [review]

**Review by ydamigos — APPROVED** [review]

**Pull request merged**
