### PR TITLE
manifest: psa-arch-tests to commit: f4fc244

### PR DESCRIPTION
**Pull request by Vge0rge**
New watchdog timer configuration for Nordic
devices.

Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@Vge0rge Please check the compliance failure.

**Review by joerchan — DISMISSED** [review]

**Comment by microbuilder** [comment]
Please update now that the other PR had been merged. Thanks!

**Comment by Vge0rge** [comment]
> 

Just rebased my PR and replaced the PR link with the hash :)

**Review by microbuilder — APPROVED** [review]

**Review by joerchan — APPROVED** [review]
Checked SHA.

**Pull request merged**
