### PR TITLE
drivers, crypto: Add support for CMAC

### PR DESCRIPTION
**Pull request by andysan**
This pull request introduces the necessary API changes to perform CMAC operations using the crypto API. The pull request also includes the necessary changes to support CMAC operations using the TinyCrypt backend.

These are a step towards implementing support for secure elements in LoRaWAN.

Kudos to @ceolin for pointing me to #9227 with an old prototype that included the same functionality.

### CODE REVIEW

**Comment by d3zd3z** [comment]
Although the implementation will probably be a little more complex, it seems unusual to me to present a MAC using a cipher API. Normally a block cipher will output ciphertext as its primary operation. Unfortunately, we don't seem to have an API for hashes/MACs. One option would be to create that.

**Comment by d3zd3z** [comment]
BTW, _implementing_ this using the crypto API is something that makes sense. But it'd be nice to have a more uniform API around hashing and MAC generation.

**Comment by andysan** [comment]
> Although the implementation will probably be a little more complex, it seems unusual to me to present a MAC using a cipher API. Normally a block cipher will output ciphertext as its primary operation. Unfortunately, we don't seem to have an API for hashes/MACs. One option would be to create that.

Agreed. I have flagged this PR as an RFC to reflect the fact that the API needs work. Reviewing the code, it seems like the API could use a general cleanup (why is the subsystem called crypto, but everything prefixed with cipher?).

I suspect we want to distinguish between the following related algorithms:

1. MAC algorithms that use a block cipher (e.g., CMAC/OMAC, and VMAC)
2. MACs based on cryptographic hashes (e.g., the HMAC family).
3. Cryptographic hashes

To start a session, we need to know the following:

1. Cipher algorithm, cipher key, and MAC algorithm. We can probably assume the cipher is encrypting. For VMACs, we need to know the parameters of the universal hash function.
2. MAC algorithm, hash function, key.
3. Hash function

**Option 1: The not so intrusive option**

I thin we could accommodate 1 without making large changes to the API. Treating CMAC as a mode is the least intrusive option, but it is ugly. We could potentially add `CRYPTO_CIPHER_OP_DIGEST` and `CIPHER_MODE_CMAC`/`CIPHER_MODE_VMAC`. We probably want to rename the enums in that case, but the rest of the API could remain largely the same. CMAC would then be described by `CRYPTO_OP_DIGEST`/`CRYPTO_ALGO_AES`/`CRYPTO_MODE_CMAC`.

For use case 2, we could just go with the proposal above and generalise `cipher_algo` to include cryptographic hashes. In that case, we would need to include HMAC as a mode. HMAC-SHA256 would then become `CRYPTO_OP_DIGEST`/`CRYPTO_ALGO_SHA256`/`CRYPTO_MODE_HMAC`.

Use case 3 could then easily be implemented by having a HASH mode. E.g.: `CRYPTO_OP_DIGEST`/`CRYPTO_ALGO_SHA256`/`CRYPTO_MODE_HASH`.

The main benefits of this approach is that it isn't particularly intrusive. We could keep the same begin/end session calls and any API changes could be patched up with a simple SED script.

The main drawbacks are:

- Redundant parameters and state in the context structure for hashes and hash-based MACs.
- Clunky API for simple use cases, particularly for plain hashes and ECB encryption.
- Representing hash and crypto algorithms in the same enum feels a bit dirty.

**Option 2: Separate `begin_session` flavours**

We could add separate flavours of begin_session for the three different operation classes described above. There would be a lot of overlap between encryption and cipher-based MACs, but that might be OK.

We would probably want to define a base context struct and separate context structs for each of the operation types in that case since the parameters and the amount of state differs.

Operations from each flavour would take a context of the specific type. E.g., `crypto_cmac` would take a `cipher_cmac_ctx` and `crypto_cipher_*_op` would take a `crypto_cipher_ctx`.

**Option 3: Extend context and drop `algo`, `mode`, and `type` from `begin_session`**

Similar to option 2, but instead of separate session calls, encode all of the parameters in a super context that is a union of all the supported contexts. Individual operations take a pointer to the  super context.

**Comment by d3zd3z** [comment]
We should probably also look at both PKCS#11 and the Arm [PSA crypto API](https://armmbed.github.io/mbed-crypto/html/index.html) specification. Developing yet another crypto API just because we can't isn't particularly useful, especially since using another specification would make it easier to work with 3rd party code. PSA crypto is probably a better match to what we want in Zephyr.

**Comment by andysan** [comment]
> We should probably also look at both PKCS#11 and the Arm [PSA crypto API](https://armmbed.github.io/mbed-crypto/html/index.html) specification. Developing yet another crypto API just because we can't isn't particularly useful, especially since using another specification would make it easier to work with 3rd party code. PSA crypto is probably a better match to what we want in Zephyr.

The PSA API seems like a good starting point, especially since TF-M was merged the other day and we should use that as a backend if available. The only missing functionality compared to the current api would be the ability to execute operations asynchronously, but that’s probably not used. 

Rewriting the API is a bigger project than I was planning on, so I don’t think I can justify that at the moment.

**Comment by andysan** [comment]
It might be worth asking one of the Linaro engineers working in the TF-M integration though. It seems like it would overlap with their interests.

**Comment by carlescufi** [comment]
cc @frkv

**Comment by andysan** [comment]
What motivated me to come up with this implementation was to add the missing pieces to implement a secure element interface for LoRaWAN. However, the current API needs quite a bit of work to support hardware secure elements (key derivation in hardware, key management, etc.) for that use case.

I agree with @d3zd3z that the effort would be better spent around a standardised and well-known API like PKCS11 or PSA that already exposes the require functionality. I have opened issue #25643 since there is a larger problem that needs to be solved.

**Comment by andysan** [comment]
Closing this PR since there is there doesn't seem to be a compelling reason to add CMAC to the current API without other major changes to the API.

**Pull request closed without merging**
