### PR TITLE
[DNM] Arch arm zephyr custom cmsis header removal

### PR DESCRIPTION
**Pull request by ioannisg**
This pull-request attempts to get rid of the custom-defined arch/arm/cortex-m/cmsis.h
that has shown to be a source of problems with regards to header inclusions. From now on, arm SOCs shall include ARM CMSIS through their <soc.h> inclusion.

### CODE REVIEW

**Comment by carlescufi** [comment]
This commit: "arch: arm: move convenience macro definitions where they are used" says "move" but it only adds to files, doesn't remove from others

**Comment by carlescufi** [comment]
In this commit "arch: arm: remove custom arm cmsis.h" you are not really removing it but actually limiting it to a single platform (beetle). I feel the commit message should reflect this

**Review by carlescufi — CHANGES_REQUESTED** [review]
Thanks for cleaning this up! Just the nitpick with the commit message.

**Comment by galak** [comment]
I'm good with the general direction here, want to make sure we either by hand or review CI that at least one board from each SoC is tested.

**Comment by ioannisg** [comment]
@galak I agree. I plan to run sanity check locally with one board from each ARM SOC, to test that this is OK. Once this is good to go, I will remove the DNM flag.

**Review by carlescufi — APPROVED** [review]
Thanks!

**Comment by ioannisg** [comment]
@galak , I think we can close this (for now), and put this for future (clean-up) work, if applicable.

**Comment by galak** [comment]
> @galak , I think we can close this (for now), and put this for future (clean-up) work, if applicable.

sounds good.

**Pull request closed without merging**
