### PR TITLE
Bluetooth: Correct printf format for 16-bit int architectures

### PR DESCRIPTION
**Pull request by haoyanbiao**
uint32_t format warning

Signed-off-by: YanBiao Hao <haoyanbiao@xiaomi.com>

### CODE REVIEW

**Comment by Thalley** [comment]
@haoyanbiao 

What is the warning? the existing code looks correct. 

This is also not related to Mesh

**Review by alwa-nordic — CHANGES_REQUESTED** [review]
Thank you for your help. But there are some problems with the change-set.

The new code will produce the wrong output. The specifiers must be zero-padded and hexadecimal. It should be `%08"PRIx32"`.

The commit message should be updated to be descriptive and without typos.

This change is not Mesh-specific.

**Comment by alwa-nordic** [comment]
@Thalley I suspect he is trying to compile the code on a platform where `unsigned int` is not `uint32_t`. Technically, the printf format specifiers for `uint32_t` are `PRIx32`, etc..

**Comment by haoyanbiao** [comment]
> @Thalley I suspect he is trying to compile the code on a platform where `unsigned int` is not `uint32_t`. Technically, the printf format specifiers for `uint32_t` are `PRIx32`, etc..

**Comment by haoyanbiao** [comment]
> > @Thalley I suspect he is trying to compile the code on a platform where `unsigned int` is not `uint32_t`. Technically, the printf format specifiers for `uint32_t` are `PRIx32`, etc..

yes, I port zephyr to many platforms。 The implementation of uint32_t type is different, sometimes unsigned int, sometimes unsigned long. If a platform implements according to unsigned long, the compilation will report warning. So，I think the %08"PRIx32" may work.

**Review by alwa-nordic — APPROVED** [review]

**Comment by Thalley** [comment]
> @Thalley I suspect he is trying to compile the code on a platform where `unsigned int` is not `uint32_t`. Technically, the printf format specifiers for `uint32_t` are `PRIx32`, etc..

Does this issue exist only for `print` functions (such as `snprintk`) or also for logging functions? If the latter, I believe we have quite a few more places where such a fix needs to be applied.

**Comment by alwa-nordic** [comment]
> > @Thalley I suspect he is trying to compile the code on a platform where `unsigned int` is not `uint32_t`. Technically, the printf format specifiers for `uint32_t` are `PRIx32`, etc..
> 
> Does this issue exist only for `print` functions (such as `snprintk`) or also for logging functions? If the latter, I believe we have quite a few more places where such a fix needs to be applied.

This applies to all printf-like functions. (And scanf-like as well.) The issue is intrinsic to variadic functions accepting mixed types. The compiler treats the variadic arguments at the call site (almost*) just like normal arguments and simply follows the calling convention for a function with that many arguments. As an illustration, the simplest calling convention pushes all arguments on stack in reverse order.

Note that the usual calling conventions don't carry size/type information about each argument, nor the argument count. So the variadic function relies completely on some custom method determining the argument types and count. For printf-like functions, the format argument supplies this information.

With our illustration calling convention, printf needs to know the size of its arguments, or it will mess up and produce garbage. Note that a variadic function uses `next_arg = va_arg(next_arg_type)` to abstract away the calling convention. Our illustration will get the size information from the type argument to `va_arg`. printf will call `va_arg(int)` when it gets to a `%d` in the format.

Compilers have a special understanding of printf in particular and are able to type-check it. This does not work in general for variadic functions.

*I said that variadic arguments are "almost" like normal argument, because there is an ancient quirk with variadic arguments. They are "integer promoted" at call site. (Just like arguments to implicitly defined functions. But that's luckily deprecated now.) That means that any int type smaller than normal int is automatically cast to int (preserving signedness). This is why you can get away with using `%d` (int) for printing (un-/signed) short int or char. But using `%d` for a long int can mess up the `va_arg` decoding and produce garbage. On some platforms, `uint32_t` is `unsigned long`.

I don't think there exists any platforms where the size of int is less than 16. It would be very esoteric. So using `%u` for `uint16_t` should be safe in practice. However, the C standard does not guarantee this.

Real calling conventions will use registers in some fashion for passing the first few arguments, with one argument in each register. That "promotes" the integer to the register width. So it may allow you to get away with even more, compared to the stack-based calling convention.

**Comment by hermabe** [comment]
There is an open issue regarding C99 format specifiers, but it is only planned for standard C functions. Even that faces some opposition. https://github.com/zephyrproject-rtos/zephyr/issues/46032

There, it is also noted that zephyr does not support 16-bit architectures. If that is the reason for this patch, I see no reason to accept it upstream.

**Review by jhedberg — CHANGES_REQUESTED** [review]
> it is also noted that zephyr does not support 16-bit architectures. If that is the reason for this patch, I see no reason to accept it upstream.

I agree with this, and the PR subject seems to imply this is the case.

**Comment by alwa-nordic** [comment]
Ok. Closing this as not-a-bug. @haoyanbiao Zephyr apparently defines its own data model that requires that `int` is `int32_t`. Basically, `CONFIG_ENFORCE_ZEPHYR_STDINT` must be `y` if you don't want undefined behavior.

**Pull request closed without merging**
