### PR TITLE
tests: thread: Add an initialization to the global variable

### PR DESCRIPTION
**Pull request by Zhaoningx**
Add an initialization to the global variable to make sure testcases
can be ran correctly.

Signed-off-by: NingX Zhao <ningx.zhao@intel.com>

### CODE REVIEW

**Review by peter-mitsis — COMMENTED** [review]
Aside from the detected compliance check error (which will need to be fixed), the proposed change looks good to me.

**Comment by enjiamai** [comment]
@Zhaoningx please fix the compliance issue, thanks.

**Comment by Zhaoningx** [comment]
Hi @enjiamai @peter-mitsis , I have fixed the compliance issue, thanks.

**Review by enjiamai — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]
Looks good to me.

**Pull request merged**
