### PR TITLE
net: sockets: recv() on unconnected stream socket should lead to ENOTCONN

### PR DESCRIPTION
**Pull request by pfalcon**
Because unoconnected stream socket doesn't have any chance to receive
    any data, so a blocking recv() would hang forever on it (and does
    without this change).
    
    Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
This was caught by MicroPython testsuite.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by mniestroj** [comment]
I've just encountered issues when testing Zephyr including this change. Looks like most net_offload drivers do not change state to `NET_CONTEXT_CONNECTED`, including ESP WiFi that I currently use. As a result TCP connection over socket API does not work.

**Comment by pfalcon** [comment]
@mniestroj: So, I suspected that even such a simple change could lead to issues, so I tested it on my side with my usual process (dumb_http_server and big_http_download on both qemu_x86 and frdm_k64f). I actually didn't even think about "offloading" case, and that shows the issue we have - I'm not sure how much we unittest that case at all, for example, AFAIK, we don't have some kind of reference "mock" driver which shows a correct implementation and which we actually exercise thoroughly in tests.

This change is correct re: POSIX semantics, and was found by a real application relying on it. So, reverting it, even if temporarily, doesn't make much sense. Instead, could you please look into updating a particular driver you work with to the proper connection state invariants, then hopefully to propagate that to other drivers. Thanks.

**Comment by WilliamGFish** [comment]
You could implement a 'cheap' fix by adding:
`&& !IS_ENABLED(CONFIG_NET_OFFLOAD)`

Billy..

**Comment by pfalcon** [comment]
> You could implement a 'cheap' fix

Except it's not a fix, but a workaround, which hides the issue, for it to grow its teeth and bite when least expected...

**Comment by mniestroj** [comment]
I agree that such workaround is not the way to go.

I am still fighting with other ESP WiFi issues, but I will certainly look into finding some proper solution. It is just a matter of time. I think by the end of week I should have something to propose.

**Comment by WilliamGFish** [comment]
You know you're both right; this would be a band-aid until a actual fix is created.

@mniestroj 
You may find that there are a few firmware issues that spring up when dealing with ESP and other modules. Particle are known for wrapping theirs to limit functionality.

Billy..

**Pull request merged**
