### PR TITLE
scripts: dts: Improve 'sub-node:' and 'child/parent: bus:' syntax

### PR DESCRIPTION
**Pull request by ulfalizer**
Two commits that simplify binding syntax a bit more, with backwards compatibility.

I can't think of any more improvements I want to make at the moment, besides fixing some `#cells` stuff pointed out by Bobby Noelte.

```
scripts: dts: Change 'sub-node: properties:' to 'child-properties:'

This removes a redundant key and reads much better, as seen in e.g.
partition.yaml:

    compatible: "fixed-partitions"

    properties:
        "#address-cells":
            type: int
            required: false

        "#size-cells":
            type: int
            required: false

    child-properties:
        label:
            type: string
            required: false

        read-only:
            type: boolean
            required: false

The old

    sub-node:
        properties:
            ...

syntax is supported for backwards compatibility, and prints a
deprecation warning if used.
```

```
scripts: dts: Change 'child/parent: bus: ...' to 'child/parent-bus:'

Instead of

    child:
        bus: foo

    parent:
        bus: bar

, have

    child-bus: foo

    parent-bus: bar

'bus' is the only key that ever appears under 'child' and 'parent', and
'child-bus' is nicely consistent with 'child-properties'.

Support the old keys for backwards compatibility, with a deprecation
warning if they're used.

Also add some 'child/parent-bus' tests to the edtlib test suite. It was
untested before.

I also considered putting more stuff under 'child' and 'parent' (like
having 'child: properties:', instead of 'child-properties'), but there's
not much point when there's just a few keys I think. Top-level stuff is
cleaner and easier to read.
```

### CODE REVIEW

**Comment by b0661** [comment]
child-properties should at least allow for one more level of child-properties where child-properties may be the only child property. This is needed to describe pin configurations for pinctrl. The pin control is the first level child property (" usart3_pins_a: usart3@0"). The pin configurations within the pin control are the second level child properties ("pins1", "pins2" ...). 

```
pinctrl: pin-controller {
        ...
         usart3_pins_a: usart3@0 {                                                   Comments
	        pins1 {
		        pinmux = <STM32_PINMUX('B', 10, AF7)>, /* USART3_TX */      -->Pin muxing information: AF7 (alternate function 7) selected on PB10 pin
			         <STM32_PINMUX('G', 8, AF8)>; /* USART3_RTS */      -->Pin muxing information: AF8 (alternate function 8) selected on PG8 pin
		        bias-disable;                                               -->Generic bindings corresponding to "no pull-up" and "no pull-down"
		        drive-push-pull;                                            -->Generic bindings to select pin driving information
		        slew-rate = <0>;                                            -->Generic bindings to select pin speed
	        };
	        pins2 {
		        pinmux = <STM32_PINMUX('B', 12, AF8)>, /* USART3_RX */
			         <STM32_PINMUX('I', 10, AF8)>; /* USART3_CTS_NSS */
		        bias-disable;
	        };
       };
       ...
};
```

Maybe child-properties could just be allowed recursively.

**Comment by ulfalizer** [comment]
> child-properties should at least allow for one more level of child-properties where child-properties may be the only child property. This is needed to describe pin configurations for pinctrl. The pin control is the first level child property (" usart3_pins_a: usart3@0"). The pin configurations within the pin control are the second level child properties ("pins1", "pins2" ...).
> 
> ```
> pinctrl: pin-controller {
>         ...
>          usart3_pins_a: usart3@0 {                                                   Comments
> 	        pins1 {
> 		        pinmux = <STM32_PINMUX('B', 10, AF7)>, /* USART3_TX */      -->Pin muxing information: AF7 (alternate function 7) selected on PB10 pin
> 			         <STM32_PINMUX('G', 8, AF8)>; /* USART3_RTS */      -->Pin muxing information: AF8 (alternate function 8) selected on PG8 pin
> 		        bias-disable;                                               -->Generic bindings corresponding to "no pull-up" and "no pull-down"
> 		        drive-push-pull;                                            -->Generic bindings to select pin driving information
> 		        slew-rate = <0>;                                            -->Generic bindings to select pin speed
> 	        };
> 	        pins2 {
> 		        pinmux = <STM32_PINMUX('B', 12, AF8)>, /* USART3_RX */
> 			         <STM32_PINMUX('I', 10, AF8)>; /* USART3_CTS_NSS */
> 		        bias-disable;
> 	        };
>        };
>        ...
> };
> ```
> 
> Maybe child-properties could just be allowed recursively.

Yeah, maybe something like this could be alright:

```yaml
child-properties:
    foo:
        ...
    child-properties:
        foo:
            ...
```

It's a little bit ugly in that `child-properties:` overlaps with property names though.

I wonder if something dumb like this might work too, as long as there's not a ton of levels:

```yaml
child-properties:
    ...

child-child-properties:
    ...
```

It's pretty nice and flat at least.

**Comment by ulfalizer** [comment]
Hmm... had never realized until now that `sub-node` allows recursion, because it's only ever used with `properties`.

A fully general version might be something like this (pretty much just a renaming, plus requiring a full binding):

```yaml
...

child-binding:
    title: ...
    description: ...

    properties:
        ...

    # Will indirectly get used for grandchildren, without any special logic
    child-binding:
        title: ...
        description: ...

        ...
```

I could go for that version too.

@b0661 
What do you think? Is it useful enough for the extra stuff?

**Comment by b0661** [comment]
>Hmm... had never realized until now that sub-node allows recursion, because it's only ever used with properties.

Legacy does not support that. I always had to patch for pinctrl.

> What do you think? Is it useful enough for the extra stuff?

I think the child-binding concept is much more usefull and much cleaner. It allows to classify the sub-node which in turn may allow to create better defines for the sub-node(s). 

I´m currently using heuristics for sub-node classification (ala. a pin-controller sub-node is a pinctrl node, a pinctrl sub-node is a pin configuration, a flash-controller sub-node is a partition list, a partition-list sub-node is a partition), this may all go away with child-bindings.

**Comment by ulfalizer** [comment]
> I think the child-binding concept is much more usefull and much cleaner. It allows to classify the sub-node which in turn may allow to create better defines for the sub-node(s).
> 
> I´m currently using heuristics for sub-node classification (ala. a pin-controller sub-node is a pinctrl node, a pinctrl sub-node is a pin configuration, a flash-controller sub-node is a partition list, a partition-list sub-node is a partition), this may all go away with child-bindings.

Yeah, I agree that a general mechanism might be better here. I hadn't thought about the recursive case when I did `child-properties`.

I'll go with `child-binding` (assuming that's what you meant).

**Comment by ulfalizer** [comment]
Split out the bus change: https://github.com/zephyrproject-rtos/zephyr/pull/19192

Going to implement the more general `child-binding:` thing instead.

**Pull request closed without merging**
