### PR TITLE
Misc net fixes

### PR DESCRIPTION
**Pull request by jukkar**
Various fixes to net-app, IPv6 and TCP.

@mike-scott The first patch fixes the issue we had with IP addresses having wrong values in your application.
The rest of the patches were found while testing large IPv6 packets over TLS.

This set is probably something that would be useful to have in 1.9.

### CODE REVIEW

**Comment by mike-scott** [comment]
Thanks @jukkar !  I'll test this over the weekend and do a review.

**Review by tbursztyka — APPROVED** [review]

**Comment by mike-scott** [comment]
@jukkar I tested this PR with the new net_app changes for LwM2M + DTLS support and I'm seeing an error in the ZoAP library.  It's failing this check in coap_parse_option()
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/zoap/zoap.c#L123

**Comment by mike-scott** [comment]
When I checked the values at that point, I was seeing:
coap_parse_option: context->buflen:47 r:1 len:197

The len var is being set above with a call to:
len = coap_option_header_get_len(context->buf[0]);

So there still may be some corruption going on.

**Comment by mike-scott** [comment]
For reference, the Zephyr branch I'm running is: https://github.com/mike-scott/zephyr/tree/dtls-testing

**Comment by jukkar** [comment]
> When I checked the values at that point, I was seeing:
> coap_parse_option: context->buflen:47 r:1 len:197
> 
> The len var is being set above with a call to:
> len = coap_option_header_get_len(context->buf[0]);
> 
> So there still may be some corruption going on.

Without diving too deep into the zoap code, I think the reason for the corruption is that zoap has this single fragment limitation, meaning that it is expecting the coap header located in the first fragment. My fix here leaves the coap header to the second fragment.

This issue with zoap will be fixed by Ravi's #1232 multi-fragment coap support. It is possible to change my commit so that we combine the first two fragments in which case the coap header would be located in first fragment. But I would rather go with the solution we have with this PR and #1232 PR. But if you really need this to work with zoap, we can certainly change this PR. Let me know what you think about this.

**Comment by mike-scott** [comment]
Let me port the LwM2M net_app PR (https://github.com/zephyrproject-rtos/zephyr/pull/1255) to the new CoAP framework and run some more DTLS tests.  No need to make this change do something that only works for a library which will be depreciated.

**Pull request merged**
