### PR TITLE
arch: arm: aarch32: USE_SWITCH implementation for Cortex-A

### PR DESCRIPTION
**Pull request by ibirnbaum**
Implementation of all functions related to the CONFIG_USE_SWITCH feature flag. Currently this feature is only enabled for aarch32 Cortex-A, due to a lack of suitable hardware for real-life testing on Cortex-R. However, no R-specific changes should be necessary in order to extend this feature to aarch32 Cortex-R.

Upon entry, z_arm_pendsv() expects the following:
- address of the struct k_thread that's being swapped in on top of the current stack,
- address of the struct k_thread that's being swapped out at SP + 0x4.

This is provided by either z_arm_svc if a context switch was triggered this way, or by z_arm_int_exit via a call to z_arch_get_next_switch_handle (if this function returns new != old thread).

If USE_SWITCH is set, the SVC handler invocation function now takes two arguments (from-thread and to-thread), which are provided by arch_switch() and are picked up by z_arm_svc().

### CODE REVIEW

**Comment by npitre** [comment]
Your `z_get_next_switch_handle()` usage is wrong. You may pass it a non-null
value only if the complete thread state is already saved to memory. Here it
appears that `z_arm_pendsv` is responsible for saving the entire thread's 
state, yet you call `z_arm_pendsv` after `z_get_next_switch_handle()` has 
returned. `z_get_next_switch_handle()` should probably always be passed 
NULL on ARM, making `z_arch_get_next_switch_handle()` redundant.

I'd suggest you read the "Symmetric Multiprocessing / Switch-based context 
switching" documentation where `z_get_next_switch_handle()` usage is 
discussed and have a look at the ARM64 and RISC-V implementations.

**Comment by andyross** [comment]
Yeah.  More broadly, this doesn't actually, heh, do anything useful.  The problem with ARM32 and z_swap() isn't the use of the old API per se (though it's always nice to see legacy APIs deprecated), it's that the PendSV-based context switch is inherently non-atomic.  The code can enter z_swap() and then take an interrupt in the kernel **after** the scheduler has made its decision about what the new "current" thread is but **before** that thread gets to run.  So the interrupt runs in a context where it thinks it interrupted the "switched-to" thread but it actually interrupted some other thread it doesn't know about.  And as a result the scheduler has to have special-case handling in a handful of very-hard-to-understand-and-maintain spots to manage this.

The arch_switch() API, by design, is required to be atomic (it needed this for SMP actually, not anything to do with arm32), and so can't (absent some very clever trickery I can't currently imagine) be correctly implemented using PendSV.

Really the right thing here would be a "conventional" musical chairs register swap context switch implementation for ARM.  But obviously that's more work than porting over the PendSV handler.

**Comment by povergoing** [comment]
> Yeah. More broadly, this doesn't actually, heh, do anything useful. The problem with ARM32 and z_swap() isn't the use of the old API per se (though it's always nice to see legacy APIs deprecated), it's that the PendSV-based context switch is inherently non-atomic. The code can enter z_swap() and then take an interrupt in the kernel **after** the scheduler has made its decision about what the new "current" thread is but **before** that thread gets to run. So the interrupt runs in a context where it thinks it interrupted the "switched-to" thread but it actually interrupted some other thread it doesn't know about. And as a result the scheduler has to have special-case handling in a handful of very-hard-to-understand-and-maintain spots to manage this.

Hi @andyross, please let me clarify something as many people may be confused about the AArch32 M and A/R (I am not complaining the AArch32 arch is a mess:) ). In terms of PendSV, yes, this is a big problem, but only Cortex-M has the PendSV, the Cortex-A/R AArch32 actually has no PendSV at all. This means Cortex-A/R arm32 can theoretically support USE_SWITCH/SMP the same way as Arm64 or RiscV do.  As you can see, the `USE_SWITCH` enable only if `CPU_AARCH32_CORTEX_A` is true. And that's why @SgrrZhf is splitting the Cortex-M and Cortex-A/R #60031 before implementing arm32 SMP.

Additionally, @ibirnbaum PendSV is defined as a SVC call in Cortex-A/R which is a `synchronize` call and does not really pend a low priority SV to the system but is really redundant/unnecessary since there is no difference to call the context_switch directly. But no worries, just keep it there, as there might be a lot of work without a split of cortex-M and A/R. I think @SgrrZhf will also take care of this.

**Comment by SgrrZhf** [comment]
> Hi @andyross, please let me clarify something as many people may be confused about the AArch32 M and A/R (I am not complaining the AArch32 arch is a mess:) ). In terms of PendSV, yes, this is a big problem, but only Cortex-M has the PendSV, the Cortex-A/R AArch32 actually has no PendSV at all. This means Cortex-A/R arm32 can theoretically support USE_SWITCH/SMP the same way as Arm64 or RiscV do. As you can see, the `USE_SWITCH` enable only if `CPU_AARCH32_CORTEX_A` is true. And that's why @SgrrZhf is splitting the Cortex-M and Cortex-A/R #60031 before implementing arm32 SMP.
> 
> Additionally, @ibirnbaum PendSV is defined as a SVC call in Cortex-A/R which is a `synchronize` call and does not really pend a low priority SV to the system but is really redundant/unnecessary since there is no difference to call the context_switch directly. But no worries, just keep it there, as there might be a lot of work without a split of cortex-M and A/R. I think @SgrrZhf will also take care of this.

Yeah, It Seems that It would be easier to introduce `USE_SWITCH` into Cortex-A/R arm32 after I separate Cortex-M and Cortex-A/R codes.  When this work is done, we can reference the implementation of arm64 of `USE_SWITCH` feature.

**Comment by SgrrZhf** [comment]
It's better to introduce a new function `z_arm_context_switch` rather than keep the `z_arm_pendsv` in Cortex-A/R arm32 codes. And `z_arm_context_switch` should be able to switch thread from the old one to the new one. We shouldn't call another function to do this in `z_arm_context_switch`.

For introducing `USE_SWITCH` feature, generally, we need to consider two situations, cooperative and preemptible.

1. cooperative
    kernel call `arch_switch`, then we can enter `z_arm_context_switch` directly and finish the context switch.
2. preemptible
  we need to refine  `z_arm_int_exit` and call `z_arm_context_switch` in it if need.

This is what I got from arch/arm64 code. 😄

**Comment by ibirnbaum** [comment]
Hey folks, I'm back from a short vacation & will address your comments ASAP.

**Comment by MaureenHelm** [comment]
> Hey folks, I'm back from a short vacation & will address your comments ASAP.

Any update?

**Comment by ibirnbaum** [comment]
> > Hey folks, I'm back from a short vacation & will address your comments ASAP.
> 
> Any update?

@MaureenHelm If this PR could have been integrated quickly, it could have served as a basis for the contributors currently working on aarch32 SMP support. However, it's more likely by now that the implementation proposed in #61206 will be used instead - I didn't get around to addressing the requested changes on this implementation before the other PR came up, which addresses full SMP support rather than just the USE_SWITCH support. Closing this PR, this implementation likely isn't required any more.

**Pull request closed without merging**
