### PR TITLE
doc: guides: tfm: fix documentation build

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Fix the TF-M requirements documentation build.

Fixes: ee001fa4bbb59f1949ac760f37bd74246868e9dd

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
This fixes CI errors as seen here: https://github.com/zephyrproject-rtos/zephyr/runs/4457706549?check_suite_focus=true

**Review by dleach02 — APPROVED** [review]
Thanks @henrikbrixandersen!

I'm curious on why the original commit that introduced this didn't fail CI like it is now?

**Comment by henrikbrixandersen** [comment]
> I'm curious on why the original commit that introduced this didn't fail CI like it is now?

It did fail in the original PR, but it was merged anyway: https://github.com/zephyrproject-rtos/zephyr/runs/4370333966?check_suite_focus=true

**Review by gmarull — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by dleach02** [comment]
> > I'm curious on why the original commit that introduced this didn't fail CI like it is now?
> 
> It did fail in the original PR, but it was merged anyway: [zephyrproject-rtos/zephyr/runs/4370333966?check_suite_focus=true](https://github.com/zephyrproject-rtos/zephyr/runs/4370333966?check_suite_focus=true)

Okay... appears @galak thought that the CI failures were not from that particular PR so they went ahead and merged it anyway... feels like we need a new rule in our process to avoid this in the future.

**Pull request merged**
