### PR TITLE
disk: Fix detect card error

### PR DESCRIPTION
**Pull request by lgl88911**
detect gpio low level means card insert.

Signed-off-by: Frank Li <lgl88911@163.com>

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
Seems right, but please also provide a commit to update `boards/arm/mm_swiftio/mm_swiftio.dts` to use the proper active levels from `boards/arm/mimxrt1050_evk/mimxrt1050_evk.dts`.  Currently one board is wrong no matter which way the comparison is made (unless one has inverters, which seems unlikely).

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
> Seems right, but please also provide a commit to update boards/arm/mm_swiftio/mm_swiftio.dts to use the proper active levels from boards/arm/mimxrt1050_evk/mimxrt1050_evk.dts. Currently one board is wrong no matter which way the comparison is made (unless one has inverters, which seems unlikely).

No, this isn't right. The driver uses `gpio_pin_get`, not `gpio_pin_get_raw`, so it's taking into account the dts active high/low flags. I don't have the mm_swiftio schematic, but assuming it's wired similarly to mimxrt1050_evk, then the fix is only to add `GPIO_ACTIVE_LOW` to the board dts.

**Comment by lgl88911** [comment]
> > Seems right, but please also provide a commit to update boards/arm/mm_swiftio/mm_swiftio.dts to use the proper active levels from boards/arm/mimxrt1050_evk/mimxrt1050_evk.dts. Currently one board is wrong no matter which way the comparison is made (unless one has inverters, which seems unlikely).
> 
> No, this isn't right. The driver uses `gpio_pin_get`, not `gpio_pin_get_raw`, so it's taking into account the dts active high/low flags. I don't have the mm_swiftio schematic, but assuming it's wired similarly to mimxrt1050_evk, then the fix is only to add `GPIO_ACTIVE_LOW` to the board dts.

Yes, this is my mistake. The disk sdcard uses a logical level. I regard it as a physical gpio level. It is the correct way to configure the active flag in dts. I have modified the dts in https://github.com/zephyrproject-rtos/zephyr/pull/25023 and now close the pr,.
Thanks for your review.

**Comment by MaureenHelm** [comment]
> Yes, this is my mistake. The disk sdcard uses a logical level. I regard it as a physical gpio level. It is the correct way to configure the active flag in dts. I have modified the dts in #25023 and now close the pr,.
> Thanks for your review.

No problem. Thanks for trying to fix it!

**Pull request closed without merging**
