### PR TITLE
doc: boards: fix board target

### PR DESCRIPTION
**Pull request by ru-fu**
Board target was changed but not updated in documentation.

Signed-off-by: Ruth Fuchss <ruth.fuchss@nordicsemi.no>

### CODE REVIEW

**Comment by ru-fu** [comment]
@lemrey @carlescufi

**Comment by martiles** [comment]
LGTM

**Review by dbkinder — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by ioannisg — CHANGES_REQUESTED** [review]
It should be without the 'ns' suffix . This is under 'Building a Secure only application '

**Comment by martiles** [comment]
if building the "hello world" without the 'ns' suffix, wouldn't that make it so it would be flashed over the "secure_boot" application. (At the memory address 0x0)

**Review by lemrey — APPROVED** [review]
~~It looks correct now~~
Actually, like Ioannis said it should be `nrf9160_pca10090`.

**Comment by ioannisg** [comment]
> 
> 
> if building the "hello world" without the 'ns' suffix, wouldn't that make it so it would be flashed over the "secure_boot" application. (At the memory address 0x0)

Yes, true.
But, here, I think we just need an example of building hello-world, just in the simplest, way. As for any other board. And the simplest way is not combining it with another image.

**Comment by ru-fu** [comment]
Updated as requested. @martiles - okay with this change?

**Review by ioannisg — APPROVED** [review]
Thanks

**Pull request merged**
