### PR TITLE
[v3.6-branch] doc: services: device_mgmt: mcumgr: Correct license for tool

### LINKED ISSUE #78927: doc: mcumgr: Wrong license for mcumgr-client
**Describe the bug**
The license shown for the `mcumgr-client` tool is BSD, the actual license of the tool is apache

**To Reproduce**
Read

**Expected behavior**
Information to be correct

**Impact**
Probably none

### PR DESCRIPTION
**Pull request by nordicjm**
Corrects an incorrect license for a tool (backport of #78923).

Fixes #78927

### CODE REVIEW

**Review by kartben — DISMISSED** [review]

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
This needs to go in as a backport of https://github.com/zephyrproject-rtos/zephyr/pull/78923 once it is merged.

**Comment by nordicjm** [comment]
> This needs to go in as a backport of #78923 once it is merged.

The backport will not work because the whole table is different in main vs 3.x

**Comment by henrikbrixandersen** [comment]
> > This needs to go in as a backport of #78923 once it is merged.
> 
> 
> 
> The backport will not work because the whole table is different in main vs 3.x

It still needs to go into `main` first. If the automatic backport fails, a manual backport must be done.

**Comment by nordicjm** [comment]
> > > This needs to go in as a backport of #78923 once it is merged.
> > 
> > 
> > The backport will not work because the whole table is different in main vs 3.x
> 
> It still needs to go into `main` first. If the automatic backport fails, a manual backport must be done.

Sure, the `main` one needs accepting first, but this is fully compliant with the process on https://github.com/zephyrproject-rtos/zephyr/wiki/Change-Control-and-Backports-to-stable-branches

> Changes can be submitted to a stable and a released branch in 2 ways:
>    Directly submitted to the branch as a pull request with the Backport label

**Comment by henrikbrixandersen** [comment]
Sure, but not like this. This provides no traceability on where this change occurred in `main`.

**Comment by nordicjm** [comment]
> Sure, but not like this. This provides no traceability on where this change occurred in `main`.

Nothing is required to go back to main that I've ever seen, it just needs to link to an issue. @nashif can you comment on what is needed?

**Comment by henrikbrixandersen** [comment]
As an example of a manually submitted PR against a release branch that maintains traceability to `main`:
- https://github.com/zephyrproject-rtos/zephyr/pull/78860

Notice how both the PR description and the Git commit log (produced with `git cherry-pick -x ...` contains references to the corresponding commits to `main`.

**Comment by nordicjm** [comment]
> As an example of a manually submitted PR against a release branch that maintains traceability to `main`:
> 
>     * [[Backport v3.6-branch] Bluetooth: RFCOMM: check the validity of received frame #78860](https://github.com/zephyrproject-rtos/zephyr/pull/78860)
> 
> 
> Notice how both the PR description and the Git commit log (produced with `git cherry-pick -x ...` contains references to the corresponding commits to `main`.

So top commit from `v3.6-branch` https://github.com/zephyrproject-rtos/zephyr/commit/2c2540ee463868dd0a5b2ebe8cfafeeecf1c74d7
```
    zephyr: Add zero-len check for utf8_trunc
    
    The function did not check if the provided string had a zero
    length before starting to truncate, which meant that last_byte_p
    could possible have pointed to the value before the string.
    
    Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>
```

What here does any of that?

**Comment by nordicjm** [comment]
> > What here does any of that?
> 
> That commit was a result of having to modify the original commit as per the discussion in #78286 (which does contain a reference to the original PR introducing the change on `main`).

Exactly, so I reference the issue here, the issue itself references all 3 items, the backport here is done manually because the table in `main` has moved on - just as the PR you referenced there, so what is different here?

**Review by henrikbrixandersen — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]

**Pull request merged**
