### PR TITLE
e1000 fixes

### PR DESCRIPTION
**Pull request by ozhuraki**
drivers: eth: e1000: Don't print function names twice
drivers: eth: e1000: Call ethernet_init() on init

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]

**Review by pfalcon — APPROVED** [review]
Let me approve this in the name of the "Trivial" PR category.

But if other reviewers will insist on more changes, @ozhuraki, please consider following changes too:

1. Use ETH_NET_DEVICE_INIT(), like most other Ethernet drivers do, instead of NET_DEVICE_INIT().
2. I'd also suggest to rename to rename e1000_probe(). While there's a kind of surface similarity with Linux, it turns out to lead more to confusion with e.g. return value: 87e4dc33b6a7530e4a12df6b2dd72588ea2e92f6 . In Zephyr, that function is called "init". That means that a Zephyr driver has 2 init functions: one for "device", another for "netif". Yep, that's a bit confusing. But mixing in Linux'es "probe" makes it all even more confusing.

**Comment by tbursztyka** [comment]
@pfalcon e1000_probe() function name is totally fine here as it does probe for the device on PCI bus.

Using ETH_NET_DEVICE_INIT enables support for VLAN that's a must indeed, @ozhuraki add another patch changing to that.

**Comment by jukkar** [comment]
> Using ETH_NET_DEVICE_INIT enables support for VLAN that's a must indeed, @ozhuraki add another patch changing to that.

Adding support for VLAN requires a bit more than just adding the ETH_NET_DEVICE_INIT() macro. We can have a separate pr that adds VLAN support and renames the init macro in same go. Lets keep this PR simple so that it can be merged soon.

**Comment by jukkar** [comment]
I tried this with #11138 but I am still not able to either receive or send packets. Tried with IPv4 and IPv6.

**Comment by pfalcon** [comment]
> I tried this with #11138 but I am still not able to either receive or send packets. Tried with IPv4 and IPv6.

Based on the contents of the patch, I wouldn't expect that it fixes anything, just cleanups a developer sees when they look at their code after a couple of weeks, happens with everyone.

**Review by jukkar — APPROVED** [review]
At least the patch that adds ethernet_init() would be needed, the driver will not work properly without it. So +1 for that. So one option is to send that patch separately as there seems to be more changes needed for the debug print patch.

**Comment by ozhuraki** [comment]
@nashif

I dropped dev_*() macros.

@pfalcon

I propose to sort out current problems first, then look at your proposals.

@pfalcon  @jukkar  @nashif 

There’s still a problem somewhere with the present qemu invocation.

Until it sorted out, qemu parameters “-vga none -display none -no-acpi -machine type=pc-0.14” need to be removed in order for e1000 to work.

If those aren’t important, I can make a pull request.

**Review by nashif — APPROVED** [review]

**Comment by pfalcon** [comment]
> I propose to sort out current problems first, then look at your proposals.

Sounds good to me, I approved this PR right away.

> There’s still a problem somewhere with the present qemu invocation.
Until it sorted out, qemu parameters “-vga none -display none -no-acpi -machine type=pc-0.14” need to be removed in order for e1000 to work.

Thanks for the info, will give it a try.

**Comment by pfalcon** [comment]
> There’s still a problem somewhere with the present qemu invocation.
Until it sorted out, qemu parameters “-vga none -display none -no-acpi -machine type=pc-0.14” need to be removed in order for e1000 to work.

Ack!! Confirming this works for me too. And I was able to minimize culprit options to just `-vga none -display none -machine type=pc-0.14`, i.e. `-no-acpi` could stay.

Generally, the problem seems to be with `-machine type=pc-0.14`, but removing just that and having `-vga none -display none` in makes no output visible after start (or perhaps make it hang soon after start).

@ozhuraki, definitely please submit a patch, people in the know then can comment how important `-machine type=pc-0.14` is, and we can either merge it or dig deeper.

Thanks!

**Comment by pfalcon** [comment]
P.S. After 12 pings of the qemu, I get:

~~~
uart:~$ [00:00:22.484,832] <err> eth_e1000.e1000_rx: Out of RX buffers
[00:00:22.484,832] <err> eth_e1000.e1000_rx: Out of RX buffers
~~~

But that's another issue for separate investigation of course.

**Comment by pfalcon** [comment]
@ozhuraki:

> -vga none -display none -machine type=pc-0.14

Ping re: submitting patch to remove harmful cruft from qemu params. Thanks.

**Comment by ozhuraki** [comment]
@pfalcon 

The reason for this problem is that qemu instantiates e1000 on x86 with IRQ=10 in the presence of “-vga none -display none -no-acpi -machine type=pc-0.14” (although it's reported as IRQ=11 at PCI scan).

Could you please check if the fix/workaround (https://github.com/ozhuraki/zephyr/tree/eth-irq) works for you?

P.S. Why the IRQ is misreported at PCI scan, is worth a check.

**Comment by pfalcon** [comment]
@ozhuraki:

> The reason for this problem is that qemu instantiates e1000 on x86 with IRQ=10

Cool investigative work! I really appreciate getting to the bottom of this, I wish we did the same for all other issue we see with the networking.

Well, let me do the actual testing of your branch a bit later (just trying to reply on Friday to comments on the many issues I follow, to not slip it into next week). But even with that info, I think it would be better to just drop `-machine type=pc-0.14` rather than work around it like that (of course, I don't know significance of `-machine type=pc-0.14`, but I'm sure if a simple patch to get rid of it is posted,  people in the know will tell us if there're strong reasons for it to stay.

**Pull request merged**
