### PR TITLE
tests:kernel:fpu_sharing Fixed missing struct defs for ARM

### PR DESCRIPTION
**Pull request by LoveKarlsson**
Added empty fp register structs for ARM combinations not handled.

### CODE REVIEW

**Comment by LoveKarlsson** [comment]
Well that caused some errors. I will look into them. Meanwhile I'll turn this into a draft

**Comment by npitre** [comment]
You should merge the fix into the first commit, not have a second commit
fixing breakage from the first commit.

Also please document which configuration combination causes problem.

**Comment by LoveKarlsson** [comment]
Squashed commit and added info to commit message about which types of ARMs it fails for, 
i.e. all ARMs without an fpu. This test apparently does not check if there is an actual fpu to test.

**Review by peter-mitsis — APPROVED** [review]
This test is simply not meant to be executed on a board without floating point support, let alone even build for such a board (see the \#error statements around lines 13 and 17 of main.c).

That being said, I am still willing to give this a +1 for the following reason--the proposed change makes it easier to spot the \#error statements in the build output as it ultimately reduces the noise.

**Review by npitre — APPROVED** [review]

**Pull request merged**
