### PR TITLE
modem_chat: fix hard fault on script stop

### LINKED ISSUE #64291: driver: modem_cellular: hard fault on network disconnection
**Describe the bug**
Based on BG95 modem, a hard fault occurs on network reconnection, and on device resume.
Hard fault occurs in subsys/modem/modem_chat.c:
static void modem_chat_script_stop(struct modem_chat *chat, enum modem_chat_script_result result)

**To Reproduce**
1. Build sample modem cellular
3. On network disconnection, suspend then resume

**Expected behavior**
No faults

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain 0.16.1
 - Zephyr 3.5

**Additional context**
By checking chat and chat->script null pointer, everything is working well.

### PR DESCRIPTION
**Pull request by RomainPelletant**
Fix fault on modem_cellular disconnection/reconnection
Fixes #64291

### CODE REVIEW

**Comment by bjarki-trackunit** [comment]
Nice catch :) please fix the commit message so we can get it merged

**Comment by RomainPelletant** [comment]
Done :)

**Review by bjarki-andreasen — APPROVED** [review]
Nice!

**Review by rerickson1 — CHANGES_REQUESTED** [review]
Sorry to be a pain, but there is no need for the abbreviations in the commit summary.
When I look at `modem: chat: fix hard fault on ntw disco` I get confused as to what that means. Just spell out the abbreviated words so someone looking at the history can make sense of it.

**Comment by bjarki-trackunit** [comment]
ah, @RomainPelletant it appears your changes did not get pushed :)

**Comment by RomainPelletant** [comment]
I should be done this time :)

**Comment by RomainPelletant** [comment]
@rerickson1 it is never a pain to have useful information in a git history

**Review by rerickson1 — APPROVED** [review]

**Review by ycsin — APPROVED** [review]

**Pull request merged**
