### PR TITLE
ext: debug: segger: Add missing # for else in SEGGER config header

### LINKED ISSUE #10685: Missing # for else in segger conf
https://github.com/zephyrproject-rtos/zephyr/blob/7ae220c845194a1c68b258cd4f9b1e63df26eb41/ext/debug/segger/rtt/SEGGER_RTT_Conf.h#L108

### PR DESCRIPTION
**Pull request by sigvartmh**
This commit fixes #10685

Signed-off-by: Sigvart M. Hovland <sigvart.hovland@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by nashif** [comment]
please fix commit message:

UC3 Title does not follow [subsystem]: [subject]: "Add missing # for else in SEGGER config header"

**Review by nashif — DISMISSED** [review]
UC3 Title does not follow [subsystem]: [subject]: "Add missing # for else in SEGGER config header"

**Comment by sigvartmh** [comment]
Better now?

**Comment by carlescufi** [comment]
@sigvartmh not yet. Please check the CI error log and fix your commit message.

**Comment by sigvartmh** [comment]
@nashif This should be fine now or do you just want  [subsystem]: [subject]: not the additional specification of ext?

**Pull request merged**
