### PR TITLE
[DNM] libc: minimal: add minimal wchar.h header

### PR DESCRIPTION
**Pull request by kv2019i**
[DNM] libc: minimal: add minimal wchar.h header
    
    Currently MIPI_SYST_LIB requires a full C-library implementation
    just because of few definitions it needs from wchar.h.
    
    It's quite inconvenient to have to change libc implementation
    just to enable MIPI Sys-T logs, so this patch provides a minimal
    wchar.h definitions to cver needs of MIPI_SYST_LIB.
    
    Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

### CODE REVIEW

**Comment by kv2019i** [comment]
If this is not acceptable approach (a partial wchar.h), I also have a modification to mipi-syst to allow it to be built without wchar.h, but that requires getting the change to upstream of that module.

**Comment by keith-packard** [comment]
Given the upcoming plan to make picolibc the default C library and move the minimal C library into more of a kernel validation role, perhaps this change wouldn't be as interesting?

**Comment by kv2019i** [comment]
@keith-packard wrote:
> Given the upcoming plan to make picolibc the default C library and move the minimal C library into more of a kernel 
> validation role, perhaps this change wouldn't be as interesting?

This is certainly an option if we can move completely to picolibc, that would indeed make this moot.  But at least for now we are still very much stuck to 
minimal libc (e.g. currently not able to even select this due to 0e0f878ddc48a018853945f5b1741ef9fe5c9ea9 ). With SOF we are using the XCC toolchain (xt-clang), which has its own set of issues with the libc implementations. I tried today xt-clang+newlib (to enable MIPI syst), but couldn't get this to work. Previous attempt at the same was at https://github.com/zephyrproject-rtos/zephyr/pull/52677 .

**Comment by nashif** [comment]
@kv2019i  We have already decided not to extend support in minimal libc beyond what we currently have, ket's focus on making sure picolibc works with xt-clang. This will be the default and does not require adhoc additions of this and that calls for various features.

**Comment by kv2019i** [comment]
Let's use picolibc instead.

**Pull request closed without merging**
