### PR TITLE
testcase for SMP kernel lockup on k_thread_abort

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
Test case for SMP kernel lockup on k_thread_abort issue #58040

### CODE REVIEW

**Comment by peter-mitsis** [comment]
If I am following things correctly, there are N cooperative threads being spawned-- 1 for each of the N cores. Since the cooperative threads will just spin and never relinquish the cores, the main thread will never never have a chance to invoke k_thread_abort().

**Comment by andyross** [comment]
Ah, but indeed the ztest thread is itself cooperative (you have logs in the linked bug).   So maybe this is a bug.

The ztest thread won't be preempted, as I read it, until it reaches k_thread_abort() where it will block in the join queue for the aborted thread.  And it **will** be preempted by the remaining worker thread at that point.  But... it now should have destroyed one of the threads, so it should have a CPU available to run on!  If it doesn't, that sounds like the thread failed to abort, or failed to wake up the sleeping thread, or something like that.

I'm still curious as to whether this behavior changes if you make the threads preemptible.  Would be good info.

**Review by andyross — DISMISSED** [review]
Should +1 this, since it's a good regression test for a known issue and involves minimal overhead.  Might consider removing the printk's to reduce spam.

**Review by nashif — DISMISSED** [review]

**Comment by evgeniy-paltsev** [comment]
@andyross 

as you've looked into this part of kernel in details - should I add the test case with preemptive threads [which I have as a draft in issue](https://github.com/zephyrproject-rtos/zephyr/issues/58040#issuecomment-1554711517)?

**Comment by andyross** [comment]
Sorry, missed the question.  For this particular bug, it doesn't actually matter as it wasn't strictly a priority bug.  I'd stick with the cooperative version as that's more constrained and easier to understand.

**Comment by evgeniy-paltsev** [comment]
Remased om main (where the initial issue is fixed), cleaned up test and added documentation.

@andyross @nashif please re-review

**Review by andyross — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
