### PR TITLE
sys: byteorder: Add support for sys_get_be64()

### LINKED ISSUE #18258: sys_get_be64() is missing from sys/byteorder.h
**Describe the bug**
There exists `sys_get_le64()` but nothing for big-endian version.

### PR DESCRIPTION
**Pull request by jukkar**
There is sys_get_le64() already but nothing for 64-bit
big-endian version.

Fixes #18258

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Review by tyrantlizard77 — DISMISSED** [review]
Shouldn't there be a test case updated to include this new API?

**Comment by jukkar** [comment]
> Shouldn't there be a test case updated to include this new API?

I actually thought about this but as there are no tests for any functions defined in ` include/sys/byteorder.h`, I did not start to create one.

**Review by carlescufi — APPROVED** [review]

**Comment by nashif** [comment]
> I actually thought about this but as there are no tests for any functions defined in ` include/sys/byteorder.h`, I did not start to create one.

tests/kernel/common/src/byteorder.c

**Comment by jukkar** [comment]
> tests/kernel/common/src/byteorder.c

Indeed, there are four tests for `sys_memcpy_swap()` but not for the `sys_get|put_le|ge*()` functions.

**Comment by ioannisg** [comment]
> 
> 
> > tests/kernel/common/src/byteorder.c
> 
> Indeed, there are four tests for `sys_memcpy_swap()` but not for the `sys_get|put_le|ge*()` functions.

So, let's have some testing then?

**Comment by jukkar** [comment]
> So, let's have some testing then?

I will be away next week (34), lets see how much time I have the following week when the 2.0 is released.

**Comment by jukkar** [comment]
Added also sys_put_be64() and unit tests for these.

**Comment by jukkar** [comment]
Added also tests for all get/put functions.

**Pull request merged**
