### PR TITLE
drivers: sensor: Store sensor trigger as a pointer - batch 1

### PR DESCRIPTION
**Pull request by MaureenHelm**
Fixes a batch of sensor drivers to store the user-supplied sensor
trigger as a pointer rather than a copy. This enables the trigger
handler to use CONTAINER_OF to retrieve a context pointer when the
trigger is embedded in a larger struct.

Signed-off-by: Maureen Helm <maureen.helm@intel.com>

re: #55130 (not using GH "fixes" notation because not all the drivers are done yet)

cc: @anthony32086 @huhebo

### CODE REVIEW

**Review by teburd — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
I am all for this, but it will break out-of-tree applications if they allocate the `struct sensor_trigger` on the stack. I would love to see a clarification of this in the API documentation (similar as to how this is documented for `struct gpio_callback`). I think an entry in the release notes would also be needed.

**Comment by galak** [comment]
am I missing where the storage for the trigger has gone with this change?  where is the data the pointer is pointing at?

**Comment by MaureenHelm** [comment]
> I am all for this, but it will break out-of-tree applications if they allocate the `struct sensor_trigger` on the stack. I would love to see a clarification of this in the API documentation (similar as to how this is documented for `struct gpio_callback`). I think an entry in the release notes would also be needed.

Update the API documentation and 3.4 release notes

> am I missing where the storage for the trigger has gone with this change? where is the data the pointer is pointing at?

It's stored by the user

**Comment by MaureenHelm** [comment]
> I am all for this, but it will break out-of-tree applications if they allocate the `struct sensor_trigger` on the stack. I would love to see a clarification of this in the API documentation (similar as to how this is documented for `struct gpio_callback`). I think an entry in the release notes would also be needed.

@henrikbrixandersen will you please take a look at the API documentation and release notes changes added in the most recent push?

**Review by henrikbrixandersen — APPROVED** [review]
Thanks!

**Review by teburd — APPROVED** [review]

**Pull request merged**
