### PR TITLE
Revert "samples: hello_world: use printf" (fixes: hello_world support for USB CDC devices)

### LINKED ISSUE #64023: hello_world no longer usable on USB CDC interface devices
**Describe the bug**
Due to how USB CDC works, it needs to enumerate before a PC can open the port, which takes time. As a result, it needs to be possible to delay the output of the hello world application on these devices so that this is visible, this (previously) was accomplished by enabling logging with a delay and forwarding printk to logging. However, with commit f623fcf3987cb35d73e1e5537822da5af865269f this is now broken, because hello_world uses printf calls which do not get routed to the log functions.

**To Reproduce**
Build hello_world with: `cmake -GNinja -DBOARD=nrf52840dk_nrf52840 -DSNIPPET=cdc-acm-console -DCONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y -DCONFIG_LOG=y -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000` then flash to an nrf52840dk and boot the board with dedicated USB plugged in - hello world is not printed

**Expected behavior**
hello world to be printed

**Impact**
Sample is useless for USB CDC boards

**Environment (please complete the following information):**
 - Commit SHA or Version used: 9e9f439522c1f0f0ef58d562283f7c979954bb86

### PR DESCRIPTION
**Pull request by nordicjm**
This reverts commit f623fcf3987cb35d73e1e5537822da5af865269f.

Fixes #64023

See linked bug for details

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]
Fix USB case instead

**Comment by nordicjm** [comment]
> Fix USB case instead

As Anas pointed out in the original PR:

> The only 'issue' with this change is that it now depends on CONFIG_STDOUT_CONSOLE and uses the C library path, this kconfig was defaulting to 'n' before it was changed in 2019 (https://github.com/zephyrproject-rtos/zephyr/commit/feab37096b16e5246c2ea61b27d99d4a3f71eac8), so now it looks like a hello world of the C library rather than being 100% zephyr and using the printk.

At the time it seems no one thought about what that would mean for things like USB CDC

**Comment by jfischer-no** [comment]
USB or USB CDC (whatever that means) can do nothing about this. This problem would exists with any virtual UART that requires a subsystem for transport, e.g. Network, Bluetooth.

**Review by henrikbrixandersen — APPROVED** [review]
Given that the main purpose of this sample is for people to establish "first contact" with their hardware, I think this makes sense. Perhaps we should add a comment right before the `printk()` statement explaining why this sample is using `printk()` and not `printf()`.

**Review by aescolar — APPROVED** [review]
I tend to agree it makes more sense to have this use printk instead of printf (same reasoning as https://github.com/henrikbrixandersen ,+ this being the most minimal sample you could expect with regards to what it uses and configures in)
If we now find that it is causing trouble in some cases, I think it is best to revert.

**Review by gmarull — CHANGES_REQUESTED** [review]
I'll insist here: it's a USB specific problem, it can be solved by allowing `printf` to behave as `printk` (isn't that possible?). Pushing USB related issues to a hello world sample is _solving_ the problem in the wrong direction, IMHO.

**Comment by carlescufi** [comment]
I don't really mind one way or the other, but I do have a question:

>As a result, it needs to be possible to delay the output of the hello world application on these devices so that this is visible, this (previously) was accomplished by enabling logging with a delay and forwarding printk to logging.

But why doesn't the CDC ACM buffer the bytes? I thought this was now the default.
@tmon-nordic @jfischer-no

**Comment by tmon-nordic** [comment]
> But why doesn't the CDC ACM buffer the bytes? I thought this was now the default.

Most likely due to this code:
https://github.com/zephyrproject-rtos/zephyr/blob/b032d0bc00489fc855e637fa86117ed284dec115/subsys/usb/device/class/cdc_acm.c#L1011-L1018

For this we would need an answer to following question: what to do with data that application sends prior to device being connected (connected here includes full enumeration) to the host?

**Comment by nordicjm** [comment]
> > But why doesn't the CDC ACM buffer the bytes? I thought this was now the default.
> 
> Most likely due to this code:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/b032d0bc00489fc855e637fa86117ed284dec115/subsys/usb/device/class/cdc_acm.c#L1011-L1018
> 
> For this we would need an answer to following question: what to do with data that application sends prior to device being connected (connected here includes full enumeration) to the host?

Same answer as the other USB CDC fix I would suggest: it would be entirely down the to the application. For hello world, you want it to block, for an application that does optional logging that users can look at, dump it. Users need to be able to select the mode though

**Comment by gmarull** [comment]
> > > But why doesn't the CDC ACM buffer the bytes? I thought this was now the default.
> > 
> > 
> > Most likely due to this code:
> > https://github.com/zephyrproject-rtos/zephyr/blob/b032d0bc00489fc855e637fa86117ed284dec115/subsys/usb/device/class/cdc_acm.c#L1011-L1018
> > 
> > For this we would need an answer to following question: what to do with data that application sends prior to device being connected (connected here includes full enumeration) to the host?
> 
> Same answer as the other USB CDC fix I would suggest: it would be entirely down the to the application. For hello world, you want it to block, for an application that does optional logging that users can look at, dump it. Users need to be able to select the mode though

can this behavior be controlled using a Kconfig option? I guess some other samples will also want this behavior.

**Comment by fabiobaltieri** [comment]
> Same answer as the other USB CDC fix I would suggest: it would be entirely down the to the application. For hello world, you want it to block, for an application that does optional logging that users can look at, dump it. Users need to be able to select the mode though

This is unfortunate, if printf cannot be used reliably in CDC UART connections then we should probably refrain from using it in samples entirely.

**Review by fabiobaltieri — APPROVED** [review]
Sounds reasonable to me to revert for now.

**Review by tmon-nordic — CHANGES_REQUESTED** [review]
I am on the "fix it in USB" side. I would prefer to have CDC ACM not lose any characters unless absolutely necessary (i.e. host is not reading the data and user disabled hardware flow control). The hardware flow control is inherently built in any non-isochronous USB protocol.

I recognize that CDC ACM shenanigans were happening in Zephyr for years and therefore when (and if) we finally fix it, there for sure will be voices to bring the old behavior back.

Therefore treat my "request changes" as a "you can ignore it if you don't mind going into the never ending revert cycle"

**Comment by nordicjm** [comment]
> unless absolutely necessary (i.e. host is not reading the data and user disabled hardware flow control).

That would be the case here, flow control would be disabled and the host would not be reading the data because the board would have just reset and set USB up, so would be printed before the host PC opens the port or even inits USB

**Comment by tmon-nordic** [comment]
> > unless absolutely necessary (i.e. host is not reading the data and user disabled hardware flow control).
> 
> That would be the case here, flow control would be disabled and the host would not be reading the data because the board would have just reset and set USB up, so would be printed before the host PC opens the port or even inits USB

But "Hello world!" is short enough to reside in the output buffer for long long time. I prefer to just direct all output data to buffer and deliver it to host regardless of when exactly it was printed. This for sure would change the behavior but I believe that is the proper way to go.

**Comment by nordicjm** [comment]
> > > unless absolutely necessary (i.e. host is not reading the data and user disabled hardware flow control).
> > 
> > 
> > That would be the case here, flow control would be disabled and the host would not be reading the data because the board would have just reset and set USB up, so would be printed before the host PC opens the port or even inits USB
> 
> But "Hello world!" is short enough to reside in the output buffer for long long time. I prefer to just direct all output data to buffer and deliver it to host regardless of when exactly it was printed. This for sure would change the behavior but I believe that is the proper way to go.

That is how it works with this revert

**Comment by nordicjm** [comment]
But it does work, I tested it. Get zephyr on `v3.4-branch` and build with `cmake -GNinja -DBOARD=thingy53_nrf5340_cpuapp -DCONFIG_LOG=y ..` then flash, wait 10 seconds, open UART and you get:
```
*** Booting Zephyr OS build zephyr-v3.4.0-66-g520d381585d7 ***

Hello World! thingy53_nrf5340_cpuapp
```

**Comment by nordicjm** [comment]
There seems to be some confusion about having USB connected or not, so let's be clear, the point of hello world is a "does this board work?" and "this is my first zephyr application" for people and board porters, someone booting the board with power without USB attached isn't really the intended purpose - if that does not work then sure, it should be fixed, but that is not why this commit is being reverted, the use case here is someone has a board, they flash their first zephyr application and are expecting to see it work as was the case last week with someone on discord where they spent days thinking something was very wrong and wasted their time.

**Comment by tmon-nordic** [comment]
> But it does work, I tested it. Get zephyr on `v3.4-branch` and build with `cmake -GNinja -DBOARD=thingy53_nrf5340_cpuapp -DCONFIG_LOG=y ..` then flash, wait 10 seconds, open USB CDC port and you get:
> 
> ```
> *** Booting Zephyr OS build zephyr-v3.4.0-66-g520d381585d7 ***
> 
> Hello World! thingy53_nrf5340_cpuapp
> ```

It works only because you had the nRF USB connected to the host and host did finish enumeration before the logger thread did manage to pass the characters to CDC ACM poll out function. Delay anything on the host side and it'll break.

Alternative way to get the sample to work due to exact same reason as why this revert "works" is to do:
```diff
diff --git a/samples/hello_world/src/main.c b/samples/hello_world/src/main.c
index 2758d75d3f..0e2a62cd85 100644
--- a/samples/hello_world/src/main.c
+++ b/samples/hello_world/src/main.c
@@ -5,9 +5,11 @@
  */
 
 #include <stdio.h>
+#include <zephyr/kernel.h>
 
 int main(void)
 {
+       k_sleep(K_MSEC(1000));
        printf("Hello World! %s\n", CONFIG_BOARD);
        return 0;
 }
```

I hope we don't have to go into discussion why fixing races with sleep is not proper solution.

**Comment by nordicjm** [comment]
@tmon-nordic so are you going to take the task of fixing this so it works?

**Comment by tmon-nordic** [comment]
> @tmon-nordic so are you going to take the task of fixing this so it works?

I can take this to my backlog. I realize that there'll be heated discussion about the new behavior (i.e. proper "handshaking" equivalent instead of crazy shenanigans) but I think that's the only way to finally resolve the never ending "change one shenanigan to another".

**Comment by gmarull** [comment]
I think that now that it is even more clear that it's a USB issue, revert should be avoided; otherwise we'll just paper this bug and there'll be no incentives to fix it properly. Also, this is not a regression, it's just a change that made an existing problem visible.

**Comment by tmon-nordic** [comment]
I did simple "just buffer if there's space available regardless of connection" change in CDC ACM and immediately hit the echo problem on Linux. See the discussion in https://github.com/zephyrproject-rtos/zephyr/issues/54705#issuecomment-1479526390 for links to Linux kernel mailing list posts where it is discussed.

How the echo is dealt on depends on applications. For example, with the simple buffering change mentioned above, I get to see the output if I use cat, i.e.
```
$ cat /dev/ttyACM0
Hello World! nrf52840dk_nrf52840

*** Booting Zephyr OS build zephyr-v3.5.0-473-g12ca3a21bff4 ***
```

But if I do use GTKTerm, then I won't see the "Hello World!" because it flushes all output it receives before configuring for the desired baud rate. This is another thing to bear in mind with such supposedly simple application.

I think the echo problem can be solved without relying on DTR checks all over the place by using ZLP. Linux does start issuing IN tokens on CDC ACM bulk endpoint as soon as application calls `open()` on tty port. Before the application manages to set parameters with `ioctl()`, the default is to echo back the characters. So Linux is echoing back the characters and it can be seen on the bus. I believe the way around that would not be to rely on DTR (as done in multiple places) but rather to arm the IN endpoint with Zero-Length Packet first. Then we would get to see when host actually starts to read the data and simply add some fixed delay before the real buffered data is sent.

**Comment by jfischer-no** [comment]
> I think the echo problem can be solved without relying on DTR checks all over the place by using ZLP. Linux does start issuing IN tokens on CDC ACM bulk endpoint as soon as application calls `open()` on tty port. Before the application manages to set parameters with `ioctl()`, the default is to echo back the characters. So Linux is echoing back the characters and it can be seen on the bus. I believe the way around that would not be to rely on DTR (as done in multiple places) but rather to arm the IN endpoint with Zero-Length Packet first. Then we would get to see when host actually starts to read the data and simply add some fixed delay before the real buffered data is sent.

This issues are just about CDC ACM used as a backend for console/logging, plain stream of characters, all this is not needed for data communication using a protocol. As you wrote it depends on the application, I am against aligning it to the behavior of certain applications/OS.

**Review by fabiobaltieri — CHANGES_REQUESTED** [review]
Hey folks, going over the new updates, changing my stance seeing the recent ones.

That said, the sample being kinda-broken in 3.5 is not super, how about reverting this in the 3.5 branch and leaving this as is for the development branch so you USB folks can figure a proper solution for 3.6?

**Comment by tmon-nordic** [comment]
I have proposed USB side fix in #64720. With the PR, the hello world is printed as expected regardless of when the host is connected and when host application opens tty device.

**Comment by fabiobaltieri** [comment]
> I have proposed USB side fix in #64720. With the PR, the hello world is printed as expected regardless of when the host is connected and when host application opens tty device.

That's even better, thanks Tomasz.

**Comment by nordicjm** [comment]
Closing in favour of #64720

**Pull request closed without merging**
