### PR TITLE
lib: updatehub: adding support for modem and also fix # 24853

### PR DESCRIPTION
**Pull request by mtahirbutt**
This pull request addresses the support for slower air interfaces (modem for example) to updatehub. Originally updatehub was designed for high speed fixed LAN interfaces. Therefore, in this patch, the proposed implementation has been tested with DIGI XBC-M5-UT-001 XBee Cellular 3G modem with STM32L475 MCU BSP. It should be noted here that #23397 PR should be used while testing for modem driver. It is expected that it should work with other interfaces as well. Some feedback is requested in this regard also. Besides, from network point, the paraemeters (retransmission etc.) can be tuned to any network. Only updatehub.c file needs review just to make sure.
Additionally there is also a bug fix for #24853 with updatehub.c.

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
Well why closed it? it would be fun to review it.

**Comment by mtahirbutt** [comment]
> 
> 
> Well why closed it? it would be fun to review it.

I struggled a bit with git and my local repo, wanted to upload only updatehub.c file. that is why thinking of generating another neater pull request.

**Comment by jfischer-phytec-iot** [comment]
please read carefully:
https://docs.zephyrproject.org/latest/contribute/index.html#coding-style
https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

maybe you want to convert this PR to Draft:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

**Comment by nandojve** [comment]
CC @otavio

**Comment by nandojve** [comment]
@mtahirbutt you need keep all required checks happy (green light) otherwise people could not even look at your PR. The first thing to do is rebase you code on top of master. Please, always check Shippable details to understand what is going on.

**Comment by mtahirbutt** [comment]
> 
> 
> @mtahirbutt you need keep all required checks happy (green light) otherwise people could not even look at your PR. The first thing to do is rebase you code on top of master. Please, always check Shippable details to understand what is going on.

thanks @nandojve for your kind note, I am trying to do that.

**Pull request closed without merging**
