### PR TITLE
doc: add two diagrams to user mode documentation

### PR DESCRIPTION
**Pull request by tyrantlizard77**
One shows how globals are routed for automatic memory
domains. The other illustrates control flow when making
system calls.

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
@dbkinder this is not working as expected, the diagrams do not show up, and I don't get any warnings either. Any advice?

**Comment by dbkinder** [comment]
Did you see these messages:
```
-:2: ERROR:EXECUTE_PERMISSIONS: do not set execute permissions for source files
#2: FILE: doc/reference/usermode/auto_mem_domain.png

-:20: ERROR:EXECUTE_PERMISSIONS: do not set execute permissions for source files
#20: FILE: doc/reference/usermode/syscall_flow.png
```

**Comment by nashif** [comment]
> I suspect if you remove execute permission on those two images and force push, you're back in business.

really? How is this related? Sphinx does not show executable images?

**Comment by dbkinder** [comment]
checkpatch is complaining about executable files in the PR

**Comment by andrewboie** [comment]
@dbkinder did that, still doesn't generate.

**Comment by dbkinder** [comment]
I see the diagrams here in the build artifacts: https://builds.zephyrproject.org/zephyrproject-rtos/zephyr/20670/docs/reference/usermode/memory_domain.html  and here: https://builds.zephyrproject.org/zephyrproject-rtos/zephyr/20670/docs/reference/usermode/syscalls.html

The latter could use a width option to make it smaller, but the pictures are indeed showing up?  What's not as you expected?

**Comment by nashif** [comment]
> @nashif checkpatch is complaining about executable files in the PR

yeah i know, but this has nothing to do with them showing in the docs or not.

**Comment by andrewboie** [comment]
never mind, user error. This seems to be working properly.

**Review by nashif — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
close enough, thanks!

**Comment by dbkinder** [comment]
@andrewboie I tweaked the figure directives to center, reduce the size of one of the images, and add a figure caption.

**Pull request merged**
