### PR TITLE
psa_protected_storage: stm32l562e_dk_ns flash issue

### PR DESCRIPTION
**Pull request by nandojve**
## Flash Storage Issue

After add support to `stm32l562e_dk_ns` in the `samples/tfm_integration/psa_protected_storage` with some changes a flash storage issue was exposed. It seems that when a non "happy path" is executed **psa_ps_get_info** and **psa_ps_remove** not behavior correctly.

The error seems to be reproducible when try execute `sample_ps_try_remove` as first storage action. The return is expected but sub-sequential access to `sample_ps_try_get_info` eventually fail. The `sample_ps_try_remove` fail when try remove an existent uid too.

## Changes to expose issue

 - Add support to stm32l562e_dk board
 - Add missing TFM_IPC config
 - Extract methods add changes easily
 - Expose stm32l562e flash storage bug

## Steps to reproduce

- west build -b stm32l562e_dk_ns zephyr/samples/tfm_integration/psa_protected_storage
- build/tfm/regression.sh
- west flash --hex-file build/tfm_merged.hex

## Output

```shell
[Sec Thread] Secure image initializing!
Booting TFM v1.4.1
*** Booting Zephyr OS build v2.7.99-2721-g0ea88d816be6  ***
Protected Storage sample started.
PSA Protected Storage API Version 1.0
Removing UID1
Failed to remove data! (-140)
Got expected error (PSA_ERROR_DOES_NOT_EXIST) when try remove UID
Writing data to UID1: The quick brown fox jumps over the lazy dog
Writing data to UID1, Flags: 0000, Size: 44
Get Info UID1
Info on data stored in UID00000001
- Size: 44
- Capacity: 0x30022020
- Flags: 0x 0
Read and compare data stored in UID1
Get Data UID1
Data stored in UID1: The quick brown fox jumps over the lazy dog
Get Info UID1
Info on data stored in UID00000001
- Size: 44
- Capacity: 0x30022020
- Flags: 0x 0
Overwriting data stored in UID1: Lorem ipsum dolor sit amet
Writing data to UID1, Flags: 0000, Size: 27
Get Info UID1
Failed to get info! (-132)
Writing data to UID2 with overwrite protection: The quick brown fox jumps over the lazy dog
Writing data to UID2, Flags: 0001, Size: 44
Get Info UID2
Info on data stored in UID00000002
- Size: 44
- Capacity: 0x30022020
- Flags: 0x 1
Attempting to write 'Lorem ipsum dolor sit amet' to UID2
Writing data to UID2, Flags: 0001, Size: 27
Failed to store data! (-133)
Get Info UID2
Info on data stored in UID00000002
- Size: 44
- Capacity: 0x30022020
- Flags: 0x 1
Got expected error (PSA_ERROR_NOT_PERMITTED) when writing to protected UID
Removing UID2
Failed to remove data! (-133)
Got expected error (PSA_ERROR_NOT_PERMITTED) when try remove UID
Get Info UID2
Info on data stored in UID00000002
- Size: 44
- Capacity: 0x30022020
- Flags: 0x 1
Removing UID1
Failed to remove data! (-132)
```

### CODE REVIEW

**Comment by erwango** [comment]
@nandojve Meanwhile, TFM 1.5.0 was integrated in Zephyr.
Using this version, it seems the error is fixed, can you have a ceck on your side ?
```
Booting TFM v1.5.0
*** Booting Zephyr OS build v2.7.99-2864-gdd08432972fa  ***
Protected Storage sample started.
PSA Protected Storage API Version 1.0
Removing UID1
Failed to remove data! (-140)
Got expected error (PSA_ERROR_DOES_NOT_EXIST) when try remove UID
Writing data to UID1: The quick brown fox jumps over the lazy dog
Writing data to UID1, Flags: 0000, Size: 44
Get Info UID1
Info on data stored in UID00000001
- Size: 44
- Capacity: 0x 1
- Flags: 0x 0
Read and compare data stored in UID1
Get Data UID1
Data stored in UID1: The quick brown fox jumps over the lazy dog
Get Info UID1
Info on data stored in UID00000001
- Size: 44
- Capacity: 0x 1
- Flags: 0x 0
Overwriting data stored in UID1: Lorem ipsum dolor sit amet
Writing data to UID1, Flags: 0000, Size: 27
Get Info UID1
Info on data stored in UID00000001
- Size: 27
- Capacity: 0x 1
- Flags: 0x 0
Writing data to UID2 with overwrite protection: The quick brown fox jumps over g
Writing data to UID2, Flags: 0001, Size: 44
Failed to store data! (-133)
Get Info UID2
Info on data stored in UID00000002
- Size: 44
- Capacity: 0x 2
- Flags: 0x 1
Attempting to write 'Lorem ipsum dolor sit amet' to UID2
Writing data to UID2, Flags: 0001, Size: 27
Failed to store data! (-133)
Get Info UID2
Info on data stored in UID00000002
- Size: 44
- Capacity: 0x 2
- Flags: 0x 1
Got expected error (PSA_ERROR_NOT_PERMITTED) when writing to protected UID
Removing UID2
Failed to remove data! (-133)
Got expected error (PSA_ERROR_NOT_PERMITTED) when try remove UID
Get Info UID2
Info on data stored in UID00000002
- Size: 44
- Capacity: 0x 2
- Flags: 0x 1
Removing UID1
```

Note: Many thanks for providing an easy way to reproduce the issue. That's really helpful

**Comment by erwango** [comment]
@nandojve Have you been able to verify this is working now?

**Comment by nandojve** [comment]
> @nandojve Have you been able to verify this is working now?

Hi @erwango, not yet. I hope this week.

**Comment by nandojve** [comment]
Hi @erwango ,

TFM 1.5 solved my issues related to storage. However, I noted below:

1) My Out of Tree branch not build anymore using my custom board

Kconfig.defconfig
```
if BOARD_MY_BOARD

config TFM_BOARD
	default "stm/stm32l562e_dk"
endif
```

Now generate:

```
warning: BUILD_WITH_TFM (defined at modules/trusted-firmware-m/Kconfig.tfm:28, modules/trusted-
firmware-m/Kconfig.tfm:28) was assigned the value 'y' but got the value 'n'. Check these unsatisfied
dependencies: ((TRUSTED_EXECUTION_NONSECURE && TFM_BOARD != "" && ARM_TRUSTZONE_M) ||
(TRUSTED_EXECUTION_NONSECURE && TFM_BOARD != "" && ARM_TRUSTZONE_M && 0)) (=n). See
http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_BUILD_WITH_TFM.html and/or look up
BUILD_WITH_TFM in the menuconfig/guiconfig interface. The Application Development Primer, Setting
Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be helpful
too.
```

2) When I build an example in my Out of Tree samples directory using `stm32l562e_dk_ns` board

```
Memory region         Used Size  Region Size  %age Used
           FLASH:       19368 B       512 KB      3.69%
            SRAM:       11328 B       192 KB      5.76%
        IDT_LIST:          0 GB         2 KB      0.00%
preprocess bl2 file
 updated
 updated
 updated
 updated
 updated
 updated
 updated
 updated
 updated
Traceback (most recent call last):
  File "/home/gfbudke/workspace/zephyr/scripts/mergehex.py", line 28, in merge_hex_files
    ih.merge(to_merge, overlap=overlap)
  File "/home/gfbudke/.local/lib/python3.8/site-packages/intelhex/__init__.py", line 875, in merge
    raise AddressOverlapError(
intelhex.AddressOverlapError: Data overlapped at address 0xC000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gfbudke/workspace/zephyr/scripts/mergehex.py", line 56, in <module>
    main()
  File "/home/gfbudke/workspace/zephyr/scripts/mergehex.py", line 52, in main
    merge_hex_files(args.output, args.input_files, args.overlap)
  File "/home/gfbudke/workspace/zephyr/scripts/mergehex.py", line 30, in merge_hex_files
    raise AddressOverlapError("{} has merge issues".format(hex_file_path))
intelhex.AddressOverlapError: /home/gfbudke/workspace/my-directory/build/zephyr_ns_signed.hex has merge issues
ninja: build stopped: subcommand failed.
```

**Comment by erwango** [comment]
> TFM 1.5 solved my issues related to storage.

Thanks for the info.

> 1. My Out of Tree branch not build anymore using my custom board

Since the warning isn't there when building with `stm32l562e_dk_ns`, I suggest to follow the values of reported symbols (`((TRUSTED_EXECUTION_NONSECURE && TFM_BOARD != "" && ARM_TRUSTZONE_M) ||
(TRUSTED_EXECUTION_NONSECURE && TFM_BOARD != "" && ARM_TRUSTZONE_M && 0)) (=n)`).
Could it be `TFM_BOARD` ?

> 2. When I build an example in my Out of Tree samples directory using stm32l562e_dk_ns board

This is likely due to a flash partition issue on the partition provided?

**Comment by nandojve** [comment]
> > TFM 1.5 solved my issues related to storage.
> 
> Thanks for the info.
> 
> > 1. My Out of Tree branch not build anymore using my custom board
> 
> Since the warning isn't there when building with `stm32l562e_dk_ns`, I suggest to follow the values of reported symbols (`((TRUSTED_EXECUTION_NONSECURE && TFM_BOARD != "" && ARM_TRUSTZONE_M) || (TRUSTED_EXECUTION_NONSECURE && TFM_BOARD != "" && ARM_TRUSTZONE_M && 0)) (=n)`). Could it be `TFM_BOARD` ?

I believe so, the custom board should be able to set TFM_BOARD as "stm/stm32l562e_dk" but isn't working.
Do you know a way to "force" TFM_BOARD without change Zephyr mainline?

> 
> > 2. When I build an example in my Out of Tree samples directory using stm32l562e_dk_ns board
> 
> This is likely due to a flash partition issue on the partition provided?

I need review this, I think I forgot to add the TFM partition. That could explain why data is colliding.

**Comment by erwango** [comment]
> Do you know a way to "force" TFM_BOARD without change Zephyr mainline?

What have you tried and is not working?

**Comment by nandojve** [comment]
> > Do you know a way to "force" TFM_BOARD without change Zephyr mainline?
> 
> What have you tried and is not working?

At custom board `Kconfig.defconfig`

```cmake
if BOARD_MY_BOARD

config TFM_BOARD
	default "stm/stm32l562e_dk"

endif
```

**Comment by erwango** [comment]
> ```cmake
> BOARD_MY_BOARD
> ```

@microbuilder Any idea why this wouldn't work?

**Comment by erwango** [comment]
> @erwango I'm not sure I follow. Is `CONFIG_TFM_BOARD` not being properly set via https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/trusted-firmware-m/Kconfig.tfm#L19

Question is how to deal with out of tree board (when BOARD_STM32L562E_DK is not set)?
Is (this)[https://github.com/zephyrproject-rtos/zephyr/pull/41454#issuecomment-1021180501] supposed to work ?

**Comment by nandojve** [comment]
Hi @erwango and @microbuilder ,

I've been reviewing this today and noted that I've been doing a mistake. TFM 1.5 solve storage problem.
Sorry about the noise.

**Comment by erwango** [comment]
Thanks @nandojve for  the heads up

**Pull request closed without merging**
