### PR TITLE
[RFC] intel_adsp: tools: Rust-ed adsp_tools

### PR DESCRIPTION
**Pull request by teburd**
Rather than fighting with multiprocessing/threads/async in python, and putting all code in a big single python file, build a suite of small rust programs to act as a userland driver of sorts to load firmware, dump logs, and tinker with the intel adsp in a variety of ways using shared code.

For example the existing cavstool.py handles IPC in a specific way for testing. This is in a way, a custom IPC protocol and handling setup that can be encoded into a specific host side test tool rather than in the loader/logger tooling which may be useful outside of that test setup.

This provides some libraries with generated register maps for the PCI devices (cavs not ace variants yet), mapping PCI resource files from devfs, and allocating memory usable by DMA from a huge page by determining its physical address from the page mapping. Mostly just like cavstool using the path laid by @andyross.

It does attempt to make a HDAStream over a set of buffers appear as a unidirectional I/O device with rusts std::io interfaces. This makes it nice for example to do what amounts piping a file to the hda stream for firmware loading. The same could be done in reverse for logging from winstream or another hda stream.

adsp_logger (winstream) works, and adsp_loader is almost done.

It's a bit hacky still, but can be very easily improved. The compiler will yell if you make type/naming mistakes. The initial goal I had was to try it out and see how it felt to myself and others, and if there was any apetite for doing this in rust rather than python. To do that I replicated a lot of what cavstool did and how it did it.

Its about the same number of lines of code as cavstool.py (~708 cavstool.py, ~1118 adsp_tools) though is missing the hda logger and ipc equivalent functionality so probably not entirely fair :-)

The major difference in total size is the register map is described in yaml here for the host side PCI bars. The PR is large because of the Cargo.lock file which can safely be left unreviewed.

Signed-off-by: Tom Burdick <thomas.burdick@intel.com>

### CODE REVIEW

**Comment by teburd** [comment]
Added some extra notes in the readme on how to run the tools with logging and backtraces in case they crash.

**Comment by marc-hb** [comment]
> Rather than fighting with multiprocessing/threads/async in python,
> putting all code in a big single python file, build a suite of small
> rust programs to act as a userland driver of sorts to load firmware,
> dump logs, and tinker with the intel adsp in a variety of ways using
> shared code.

This sounds like throwing the entire Python baby with the bathwater. I've observed a few re-invented wheels and anti-patterns in cavstool.py and friends (e.g. #46864) but that was IMHO just a lack of knowledge and attention. Python has great, super-high level libraries so if we're struggling with multiprocessing/threads/async it's really just because we're not using them (or because we have real, language-independent concurrency issues).

Rust is an incredibly promising replacement for C (= the language of memory corrup... management) but last I checked it did not solve any problem Python has. Except performance of course, but if performance was really a problem here then Python would have already been dropped long ago?

On one hand Rust may attract more l33t and cool hackerz to this area which would help with the lack of attention and resources (= the only real issue IMHO). On the other hand it will considerably raise the bar for one-line / drive-by fixes: not so good considering validation seems consistently assigned to less experienced engineers.


Also: great, yet another driver! (not)

**Comment by teburd** [comment]
> > Rather than fighting with multiprocessing/threads/async in python,
> > putting all code in a big single python file, build a suite of small
> > rust programs to act as a userland driver of sorts to load firmware,
> > dump logs, and tinker with the intel adsp in a variety of ways using
> > shared code.
> 
> This sounds like throwing the entire Python baby with the bathwater. I've observed a few re-invented wheels and anti-patterns in cavstool.py and friends (e.g. #46864) but that was IMHO just a lack of knowledge and attention. Python has great, super-high level libraries so if we're struggling with multiprocessing/threads/async it's really just because we're not using them (or because we have real, language-independent concurrency issues).
> 
> Rust is an incredibly promising replacement for C (= the language of memory corrup... management) but last I checked it did not solve any problem Python has. Except performance of course, but if performance was really a problem here then Python would have already been dropped long ago?
> 
> On one hand Rust may attract more l33t and cool hackerz to this area which would help with the lack of attention and resources (= the only real issue IMHO). On the other hand it will considerably raise the bar for one-line / drive-by fixes: not so good considering validation seems consistently assigned to less experienced engineers.
> 
> Finally, having to compile test code feels like a regression. Good bye quick experimentations on low-end test devices.
> 
> Also: great, yet another driver! (not)

Hah, indeed. The entire attempt here was driven by my frustration with trying to fix the python script to feel better. E.g. make a class for the ADSP with stuff like load_firmware() that may vary over hardware variants. Head meet wall.

No worries, it was a fun hack but not the direction to go in talking with others.

**Comment by andyross** [comment]
FWIW: one big advantage here is that rust can produce a static binary.  Getting python onto production chromebooks is a chore, and chromeos dev builds are stuck with python 3.6 for the moment.

**Comment by marc-hb** [comment]
From https://www.chromium.org/chromium-os/testing/autotest-developer-faq/#whats-the-fast-way-to-make-a-change-to-a-test-and-iterate-to-see-if-it-now-works

> The fastest way to develop a test is to not use compiled components in your test. If you can write a test without cross-compiling code you can modify the test in **python**/shell on the target and rerun it on the target directly.

Even Yocto has Python: https://github.com/thesofproject/sof-test/commit/a9ea627b3e679

--------

> chromeos dev builds are stuck with python 3.6 for the moment.

Ouch. chromebrew? See https://github.com/thesofproject/sof-test/issues/576

**Pull request closed without merging**
