### PR TITLE
drivers: RTC: update API to use DEVICE_API macros

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
Update RTC API and device drivers to use DEVICE_API macros.

### CODE REVIEW

**Review by pdgendt — APPROVED** [review]

**Comment by pdgendt** [comment]
Nit: subject has `DEIVCE` instead of `DEVICE`

**Review by RichardSWheatley — APPROVED** [review]

**Comment by dleach02** [comment]
Lets fix the commit title

**Comment by bjarki-andreasen** [comment]
header updated

**Comment by kartben** [comment]
assignee should be RTC maintainer

**Comment by kartben** [comment]
... and I messed up the 2-business day rule 🫣  Sorry, folks.

**Pull request merged**
