### PR TITLE
arch: aarch64: Rework exception entry/exit code

### PR DESCRIPTION
**Pull request by carlocaione**
Rework the assembly code for the ISR wrapper and SVC to share the
entry/exit code that is currently scattered amoung several files /
places. No functional changes.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

### CODE REVIEW

**Review by stephanosio — COMMENTED** [review]
I wonder if adding more branches and context preservation overhead is justifiable for the sake of "rework/refactoring."

IMHO, any repeated code should be defined as macros instead; this way, we do not introduce any performance penalties.

**Comment by carlocaione** [comment]
> I wonder if adding more branches and context preservation overhead is justifiable for the sake of "rework/refactoring."

This rework is needed because I want to rework a bit the entry / exit routines in a follow-up patch-set.

**Comment by carlocaione** [comment]
Please ignore checkpatch, it doesn't understand that it is a GAS macro.

**Review by stephanosio — APPROVED** [review]
Looks good to me.

**Comment by carlocaione** [comment]
Can we merge this? (@ioannisg maybe?)

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
I wonder if it is better to try to fix the checkpatch script first, and then get this merged with a green CI.

**Pull request merged**
