### PR TITLE
driver: entropy: stm32: manage both get_entropy and get_entropy_isr

### PR DESCRIPTION
**Pull request by ABOSTM**
driver: entropy: stm32: manage both get_entropy and get_entropy_isr
    
As stated in kernel/init.c in function sys_rand32_get()
/* FIXME: this assumes sys_rand32_get() won't use any synchronization
 * primitive, like semaphores or mutexes.  It's too early in the boot
 * process to use any of them.  ...
 */
    
So implement entropy_stm32_rng_get_entropy_isr() which is use
by default (if exist) in init functions.
And do not call k_yield in case of ENTROPY_BUSYWAIT flag is set.

Problem was detected on wb nucleo_h743zi (needs #27795) with test tests/crypto/rand32/  (CONF_FILE=prj_hw_random_xoroshiro.conf). It generate a bus fault due to k_yield during init.

### CODE REVIEW

**Review by erwango — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
LGTM

**Review by carlescufi — DISMISSED** [review]
You might want to consider both blocking and non-blocking versions or using something like `WFE` to avoid having a busy loop. See here:
https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/entropy/entropy_nrf5.c

**Comment by dleach02** [comment]
@carlescufi, WFE is useful consideration. As for the blocking/non-blocking, this problem they ran into occurs during initialization of the system. They also are using XOROSHIRO RNG as I suspect their entropy HW is not intended to be a RNG source. With XOROSHIRO, you don't need non-blocking.

**Comment by ABOSTM** [comment]
I am not an RNG/entropy expert (I am not sure to catch the difference between entropy and rng)
but our HW is a true RNG.
I dont know the specificity of XOROSHIRO, I just get an error in our test bench as it runs this test with config  prj_hw_random_xoroshiro.conf.
I will investigate further and consider WFE and blocking/non-blocking.

**Comment by ABOSTM** [comment]
I looked at the different implementations, and I found that 'entropy_sam.c' implementation was close to STM32 (which minimize changes required) and I feel that implementation quite simple, valid for all RNG HW from the different STM32 families and doing the job.
So I mimic this implementation:
* Add  entropy_stm32_rng_get_entropy_isr() which is use by default (if exist) in init functions.
* do not call k_yield in case of ENTROPY_BUSYWAIT flag is set (flag is set in case of call from init).

This prevent k_yield to be called from init (entropy_stm32_rng_get_entropy_isr(..., ENTROPY_BUSYWAIT)).
This provides whatever available when called from ISR when busy wait not allowed
This still yield for non isr call (entropy_stm32_rng_get_entropy())

Tested passed on nucleo_f746zg, nucleo_g474re, nucleo_f429zi, nucleo_h743zi, disco_l475_iot1
* tests/drivers/entropy  
* samples/drivers/entropy

Tested passed on nucleo_f746zg, nucleo_wb55rg, nucleo_g071rb, nucleo_g474re, nucleo_l4r5zi, stm32f3_disco, nucleo_f429zi, nucleo_h743zi, nucleo_f207zg, nucleo_l152re, nucleo_f103rb, disco_l475_iot1
* tests/crypto/rand32

@dleach02 @carlescufi, does it sound good to you ?

**Comment by erwango** [comment]
@ABOSTM, @dleach02, @carlescufi Since the change is now much more invasive, I propose to dismiss all reviews and start all over again in order to avoid merging non reviewed material

**Comment by dleach02** [comment]
I think you should stick with your original change and remove the yield and not worry about the interrupt version of the entropy function. This function will likely only be called twice, once in the kernel and once when initializing the XORISHIRO algorithm. I don't know the details of the entropy HW in this chip but I suspect the delay only occurs on the first access because it is waiting on filling the entropy FIFO. 

My feeling is that the interrupt version of the entropy function was added because there are platforms that rely on this HW to supply the RNG stream and on some platforms,the entropy IP also has the delay when refilling the fifo so they put int frameworks around it to attempt to reduce it.

**Comment by dleach02** [comment]
@ABOSTM, 

If the HW is a true RNG and can sustain a constant stream of RNG requests then you don't need to tie RNG to XIROSHIRO, it can be tied directly to the entropy driver and HW. 

But,if your hardware has situations where it has a long delay to refill the entropy queue when it is empty and that delay is long enough to break other things like certain networking protocols then you either need to use a PRNG function or you need to add some buffering code around your hardware similar to what the nrf platforms do and add an isr function interface. 

> I am not an RNG/entropy expert (I am not sure to catch the difference between entropy and rng)
> but our HW is a true RNG.
> I dont know the specificity of XOROSHIRO, I just get an error in our test bench as it runs this test with config prj_hw_random_xoroshiro.conf.
> I will investigate further and consider WFE and blocking/non-blocking.

**Review by dleach02 — APPROVED** [review]
lgtm... but my general comments still stands.

**Comment by ioannisg** [comment]
Looks very similar to the SAM driver, now, @ABOSTM @erwango, is this intentional?

(I remember fixing the ISR support on the get-entropy for SAM SoCs, a few releases back)

**Comment by ABOSTM** [comment]
`Looks very similar to the SAM driver, now, @ABOSTM @erwango, is this intentional?`
Yes, SAM driver look to me the simplest and closer to stm32 implementation.

Nevertheless, even if stm32h7 serie I originally worked on, has a true rng, with 128bit FIFO.
the driver is supposed to work for all STM32 series, like stm32l4 which has a simple rng without fifo.
Besides, for any serie, there is some delay between each valid data (delay depends on serie and also on clock configuration)
So following @dleach02 recommendation, I think now, that I should better look at the (more complex) nrf implementation.
I will come with a new proposal.

**Comment by ABOSTM** [comment]
New implementation proposed for review.
Mimic nrf implementation.
Needed to add interrupts property to rng node for all st32 board supporting it.

Tested passed on nucleo_f746zg, nucleo_g474re, nucleo_f429zi, nucleo_h743zi, disco_l475_iot1
* tests/drivers/entropy
* samples/drivers/entropy

Tested passed on nucleo_f746zg, nucleo_wb55rg, nucleo_g071rb, nucleo_g474re, nucleo_l4r5zi, stm32f3_disco, nucleo_f429zi, nucleo_h743zi, nucleo_f207zg, nucleo_l152re, nucleo_f103rb, disco_l475_iot1
* tests/crypto/rand32

**Comment by dleach02** [comment]
It would be interesting to see/know if the amount of code added is greater or less than just using the XORISHIRO RNG with this HW entropy as an initializer? I also did some initial performance characterization

**Comment by ABOSTM** [comment]
fix formatting issue.

**Pull request merged**
