### PR TITLE
CODEOWNERS: add more owners to tests/*

### PR DESCRIPTION
**Pull request by nashif**
Add more people to tests/* to get more reviews and to get notified when
tests/* change.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by nniranjhana — COMMENTED** [review]
can we also add
`tests/posix/*    @nniranjhana`?

**Comment by nashif** [comment]
> can we also add
> tests/posix/* @nniranjhana?

will do

**Review by spoorthik — COMMENTED** [review]
Thanks!

**Comment by pswarnak** [comment]
Cool, this will be helpful. Thanks.
May we also be added as owners for samples/* as not all tests are available in tests/* folder.

**Pull request merged**
