### PR TITLE
Deprecate FLASH_AREA_ macros

### PR DESCRIPTION
**Pull request by de-nordic**
The PR consists of 2 commits, which:
 1) deprecate FLASH_AREA_ macros;
 2) update release notes.

### CODE REVIEW

**Review by nvlsianpu — DISMISSED** [review]

**Comment by nvlsianpu** [comment]
@fabiobaltieri Can this be included into the 3.2 release?

**Comment by mmahadevan108** [comment]
Please help fix the merge conflicts

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri Can this be included into the 3.2 release?

This comes a bit late. Other label related APIs have been marked as deprecated so I'd say let's merge it, but then the label property has not been declared as deprecated for `fixed-partitions`, is this holding something back?

**Comment by nvlsianpu** [comment]
I can help with fixing the conflict if will be decided to integrate this.

**Review by mbolivar-nordic — DISMISSED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
