### PR TITLE
subsys: net: ip: l2: ethernet: fix kconfig

### PR DESCRIPTION
**Pull request by nvlsianpu**
Missing newline on end of the file - this cause failure
while try to use menuconfig.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by jukkar — CHANGES_REQUESTED** [review]
Minor change to subject needed

**Review by finikorg — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@jukkar 'net/ethernet: fix kconfig' ?
You have different convention than in other sub-modules.

**Comment by jukkar** [comment]
"net: l2: ethernet: ...." is enough here, no need to have "subsys:" in the subject.

**Comment by jukkar** [comment]
> You have different convention than in other sub-modules.

Not really, some people send patches with "net/...." but that is minority.

**Comment by nvlsianpu** [comment]
@jukkar - is it OK now?

**Comment by jukkar** [comment]
> is it OK now?

Yes, looks ok.

**Review by jukkar — APPROVED** [review]

**Pull request merged**
