### PR TITLE
drivers: wifi: eswifi: Ignore F_GETFL and F_SETFL ioctl calls. Add ZSOCK_POLLOUT revent in offloaded poll. Use peer_addr as addr in recvfrom.

### PR DESCRIPTION
**Pull request by davidalo**
Hello everyone.

Working on a `b_l4s5i_iot01a` board which is using a ESWIFI chip with offloaded sockets. I am struggling to make it work in order to connect to an LWM2M server and get the full functionality. 

For now the following problems have been / need to be addressed:

- [x] Add support or ignore F_GETFL and F_SETFL ioctl calls from lwm2m_engine
- [x] Add support for sending in offloaded poll.
- [x] Add support for recvfrom with addr.
- [x] ~~Review send invalid bytes  (see information below).~~
- [x] ~~Review recv invalid bytes (see information below).~~

With the first 3 commits I can properly connect to a LWM2M server (i.e. leshan or thingsboard). 
However,  I still face two issues:

1. When the LWM2M server performs a read request, it seems to be completed successfully but the server is reporting unexpected 0xFF bytes in CoAP.
```
[CoapServer(main)#9] INFO  org.eclipse.californium.ban - [LWM2M Server-coap://0.0.0.0:5685] Found payload marker (0xFF) but message contains no payload;
``` 

2. ~~When pushing an image from the LWM2M server to the device, bytes received are incorrect. As an example, the first bytes of the binary file are `3db8 f396 0000 0000 0002 0000 58a7 0200` and we receive `3db8 f396 0000 0000 0002 0000 5ca7 0200` in the LWM2M function.~~

LWM2M code seems fine as it is working well when running in a Ethernet board, so I guess that problems come from ESWIFI. Any help for debugging this is highly appreciated.

### CODE REVIEW

**Comment by davidalo** [comment]
Maybe related #76483

**Comment by jukkar** [comment]
Just a minor comment to the commits. Please use `drivers: wifi: eswifi: ....` prefix instead `ESWIFI: ...` for the commit subjects.

**Comment by davidalo** [comment]
> Just a minor comment to the commits. Please use `drivers: wifi: eswifi: ....` prefix instead `ESWIFI: ...` for the commit subjects.

Done

**Comment by davidalo** [comment]
A quick update from this weekend. It seems that rx of invalid bytes was an mistake on my end. RX is successful when using fixes from #76483.

Still need to dig deeper to check invalid bytes tx.

**Review by rlubos — COMMENTED** [review]
Please follow https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines regarding commit message format. All commits need a commit message body and a signoff entry.

**Pull request closed without merging**
