### PR TITLE
tests: bitfield: Convert legacy test case to ztest

### PR DESCRIPTION
**Pull request by punitvara**
Add ztest apis and make test case align to use ztest
framework.

Signed-off-by: Punit Vara <punit.vara@intel.com>

### CODE REVIEW

**Comment by punitvara** [comment]
@ramakrishnapallala  Can you please review ?

**Review by ramakrishnapallala — COMMENTED** [review]
minor comment on commit message:

Add ztest API's to make the test case align to ztest framework.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by nashif** [comment]
fix commit message, you are not adding ztest APIs, you are basically just migrating this test to ztest.

so, "migrate testcase to ztest and use ztest macros"

**Comment by punitvara** [comment]
Sorry for that. I will check for other commit if I have done some mistake.

**Pull request merged**
