### PR TITLE
drivers: i2c: sam0 fix bus synchronization issues and smart mode read after nack error

### LINKED ISSUE #38878: drivers: i2c: sam0: multiple edge case failures
**Describe the bug**
* Per device datasheets the bus state will be unknown until a transition on SDA is detected or the bus state is set to idle by software
* Smart mode causes a bus read every time the data register is read - this causes an additional read to be issued after the NACK is set by the host and the stop is never properly issued because the NACK flag is reset by the time the driver attempts to send the stop - this causes issues with some devices. 
* The PR #38482 causes the host to NACK every byte read from a device if data->num_msgs == 1

**Impact**
I2C driver for many devices does not function properly

### PR DESCRIPTION
**Pull request by bryan-hunt**
When in master mode when the peripheral is enabled the bus state is unknown - software needs to force it to idle before the peripheral is ready to transmit.

The I2C driver expects to be able to control the stop - however when trying to delay the stop the use of smart mode triggers another bus read after the NACK due the data register read. When using smart mode the nack and module command have to be issued at the same time to prevent this read from occurring. Smart mode has been disabled to allow the api to control the stop.

Fixes: #38878

Signed-off-by: Bryan Hunt <bryan.hunt@microchip.com>

### CODE REVIEW

**Comment by bryan-hunt** [comment]
@galak @nashif Can you kick off the workflows and check the reviewer list for this PR?

**Comment by nandojve** [comment]
Hi @bryan-hunt ,

Just to inform, it is not allowed merge commits in Zephyr. Instead create unnecessary commits, rebase your branch against the main branch and don't make commit with changes on top of original commit. I mean, rebase your branch and fixup your first commit (always). The rebase should be on top of upstream/main and don't forget to fetch upstream code.

Please, read [How to Contribute](https://docs.zephyrproject.org/latest/contribute/index.html) to get a better view about how to upstream code to ZephyrRTOS.

**Comment by nandojve** [comment]
Hi @bryan-hunt ,

Some fixes were made for I2C. Rebase before you continue your work.

**Comment by maxmclau** [comment]
@bryan-hunt +1 for rebase if you have the time. The i2c sam0 driver is currently broken.

**Pull request closed without merging**
