### PR TITLE
Bluetooth: controller: set new LLCP as default for DF

### PR DESCRIPTION
**Pull request by kruithofa**
This PR sets the new LLCP as the default instead of legacy
in case DF is enabled

Signed-off-by: Andries Kruithof <andries.kruithof@nordicsemi.no>

### CODE REVIEW

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/45547#issuecomment-1123740620 after 15:11:55.

**Comment by sjanc** [comment]
#AutoPTS run zephyr SM

**Comment by sjanc** [comment]
diff comparing to last weekly run:
GAP GAP/BOND/BON/BV-02-C XML-RPC ERROR
GAP GAP/SEC/AUT/BV-21-C INCONC
GAP GAP/SEC/SEM/BI-22-C PASS (2)
GAP GAP/SEC/SEM/BV-28-C PASS (3)
GAP GAP/SEC/SEM/BV-41-C PASS (2)
GAP GAP/SEC/SEM/BV-42-C PASS (3)
GAP GAP/SEC/SEM/BV-56-C PASS (2)
GAP GAP/SEC/SEM/BV-57-C BTP ERROR
GAP GAP/SEC/SEM/BV-58-C BTP ERROR

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/45547#issuecomment-1124118582 after 20:22:09.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/45547#issuecomment-1124118582 after 10:23:14.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Failed tests:
SM      SM/CEN/EKS/BI-01-C              PASS
SM      SM/CEN/EKS/BV-01-C              PASS
SM      SM/CEN/JW/BI-01-C               PASS
SM      SM/CEN/JW/BI-04-C               PASS
SM      SM/CEN/JW/BV-05-C               PASS
SM      SM/CEN/KDU/BI-01-C              PASS
SM      SM/CEN/KDU/BI-02-C              INCONC - ERRATA SE17732 TSE17772
SM      SM/CEN/KDU/BI-03-C              INCONC - ERRATA SE17732 TSE17772
SM      SM/CEN/KDU/BV-04-C              PASS
SM      SM/CEN/KDU/BV-05-C              PASS
SM      SM/CEN/KDU/BV-06-C              PASS
SM      SM/CEN/KDU/BV-10-C              PASS
SM      SM/CEN/KDU/BV-11-C              PASS
SM      SM/CEN/OOB/BI-01-C              PASS
SM      SM/CEN/OOB/BV-01-C              PASS
SM      SM/CEN/OOB/BV-03-C              PASS
SM      SM/CEN/OOB/BV-09-C              PASS
SM      SM/CEN/PKE/BI-01-C              PASS
SM      SM/CEN/PKE/BI-02-C              PASS
SM      SM/CEN/PKE/BV-01-C              PASS
SM      SM/CEN/PKE/BV-04-C              PASS
SM      SM/CEN/PROT/BV-01-C             PASS
SM      SM/CEN/SCJW/BI-01-C             PASS
SM      SM/CEN/SCJW/BV-01-C             PASS
SM      SM/CEN/SCJW/BV-04-C             PASS
SM      SM/CEN/SCOB/BI-01-C             PASS
SM      SM/CEN/SCOB/BI-04-C             PASS
SM      SM/CEN/SCOB/BV-01-C             PASS
SM      SM/CEN/SCOB/BV-04-C             PASS
SM      SM/CEN/SCPK/BI-01-C             PASS
SM      SM/CEN/SCPK/BI-02-C             PASS
SM      SM/CEN/SCPK/BV-01-C             PASS
SM      SM/CEN/SCPK/BV-04-C             PASS
SM      SM/CEN/SIGN/BI-01-C             PASS
SM      SM/CEN/SIGN/BV-01-C             PASS
SM      SM/CEN/SIGN/BV-03-C             PASS
SM      SM/CEN/SIP/BV-02-C              PASS
SM      SM/PER/EKS/BI-02-C              PASS
SM      SM/PER/EKS/BV-02-C              PASS
SM      SM/PER/JW/BI-02-C               PASS
SM      SM/PER/JW/BI-03-C               PASS
SM      SM/PER/JW/BV-02-C               PASS
SM      SM/PER/KDU/BI-01-C              PASS
SM      SM/PER/KDU/BI-02-C              INCONC - ERRATA SE17732 TSE17772
SM      SM/PER/KDU/BI-03-C              INCONC - ERRATA SE17732 TSE17772
SM      SM/PER/KDU/BV-01-C              PASS
SM      SM/PER/KDU/BV-02-C              PASS
SM      SM/PER/KDU/BV-03-C              PASS
SM      SM/PER/KDU/BV-07-C              PASS
SM      SM/PER/KDU/BV-08-C              PASS
SM      SM/PER/KDU/BV-09-C              PASS
SM      SM/PER/OOB/BI-02-C              PASS
SM      SM/PER/OOB/BV-02-C              PASS
SM      SM/PER/OOB/BV-04-C              PASS
SM      SM/PER/OOB/BV-10-C              PASS
SM      SM/PER/PKE/BI-03-C              PASS
SM      SM/PER/PKE/BV-02-C              PASS
SM      SM/PER/PKE/BV-05-C              PASS
SM      SM/PER/PROT/BV-02-C             PASS
SM      SM/PER/SCJW/BI-02-C             PASS
SM      SM/PER/SCJW/BV-02-C             PASS
SM      SM/PER/SCJW/BV-03-C             PASS
SM      SM/PER/SCOB/BI-02-C             PASS
SM      SM/PER/SCOB/BI-03-C             PASS
SM      SM/PER/SCOB/BV-02-C             PASS
SM      SM/PER/SCOB/BV-03-C             PASS
SM      SM/PER/SCPK/BI-03-C             PASS
SM      SM/PER/SCPK/BI-04-C             PASS
SM      SM/PER/SCPK/BV-02-C             PASS
SM      SM/PER/SCPK/BV-03-C             PASS
SM      SM/PER/SIE/BV-01-C              PASS
SM      SM/PER/SIP/BV-01-C              PASS

**Review by ppryga-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
Remove this line: `It is considered experimental because it is still under development and is not qualifiable yet.`  in the help in a follow up PR when appropriate.

**Pull request merged**
