### PR TITLE
Add rt1180 pwm support

### PR DESCRIPTION
**Pull request by lucien-nxp**
Tested with sample led_pwm

### CODE REVIEW

**Comment by lucien-nxp** [comment]
@hakehuang , could you help test sample/led_pwm on RT1180?

**Review by danieldegrasse — DISMISSED** [review]

**Comment by hakehuang** [comment]
> @hakehuang , could you help test sample/led_pwm on RT1180?

```
2024-09-04 09:11:17,147 - twister - DEBUG - DEVICE: [00:00:38.516,000] [0m<inf> main:   Increasing brightness gradually[0m
2024-09-04 09:11:19,175 - twister - DEBUG - DEVICE: [00:00:40.542,000] [1;31m<err> pwm_mcux: Too long period (206250), adjust pwm prescaler![0m
2024-09-04 09:11:19,180 - twister - DEBUG - DEVICE: [00:00:40.550,000] [1;31m<err> main: err=-22[0m
```

**Comment by lucien-nxp** [comment]
I will deal with the conflicts until https://github.com/zephyrproject-rtos/zephyr/issues/77970 resolved.

**Review by nordic-krch — DISMISSED** [review]

**Comment by carlescufi** [comment]
@lucien-nxp please rebase

**Comment by nordic-segl** [comment]
FYI
other PWM samples and tests that can be used for verification:
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/pwm/pwm_api/testcase.yaml
https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/basic/blinky_pwm/sample.yaml#L5
https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/basic/fade_led/sample.yaml#L9

**Comment by MaureenHelm** [comment]
Need to rebase

**Comment by danieldegrasse** [comment]
> > @hakehuang , could you help test sample/led_pwm on RT1180?
> 
> the test fails, as reported in #77970

Does this test still fail with this PR?

**Comment by hakehuang** [comment]
> Does this test still fail with this PR? If so, is this a failure we should fix here or in another PR?

the led/pwm test still fails. 
```
*** Booting Zephyr OS build v3.7.0-4339-g1ec5ce05f9f8 ***\r\n[00:00:00.005,000] <inf> main: Testing LED 0 - no label\r\n[00:00:00.010,000] <inf> main:   Turned on\r\n[00:00:01.015,000] <inf> main:   Turned off\r\n[00:00:02.020,000] <inf> main:   Increasing brightness gradually\r\n[00:00:04.046,000] <err> pwm_mcux: Too long period (234375), adjust pwm prescaler!\r\n[00:00:04.054,000] <err> main: err=-22\r\n[00:00:04.058,000] <inf> main: Testing LED 0 - no label\r\n[00:00:04.064,000] <inf> main:   Turned on\r\n[00:00:05.069,000] <inf> main:   Turned off\r\n[00:00:06.073,000] <inf> main:   Increasing brightness gradually\r\n[00:00:08.100,000] <err> pwm_mcux: Too long period (234375), adjust pwm prescaler!\r\n[00:00:08.108,000] <err> main: err=-22\r\n[00:00:08.112,000] <inf> main: Testing LED 0 - no label\r\n[00:00:08.118,000] <inf> main:   Turned on\r\n[00:00:09.122,000] <inf> main:   Turned off\r\n[00:00:10.127,000] <inf> main:   Increasing brightness gradually\r\n[00:00:12.153,000] <err> pwm_mcux: Too long period (234375), adjust pwm prescaler!\r\n[00:00:12.161,000] <err> main: err=-22\r\n[00:00:12.166,000] <inf> main: Testing LED 0 - no label\r\n[00:00:12.171,000] <inf> main:   Turned on\r\n[00:00:13.176,000] <inf> main:   Turned off\r\n[00:00:14.180,000] <inf> main:   Increasing brightness gradually\r\n[00:00:16.207,000] <err> pwm_mcux: Too long period (234375), adjust pwm prescaler!\r\n[00:00:16.215,000] <err> main: err=-22\r\n[00:00:16.219,000] <inf> main: Testing LED 0 - no label\r\n[00:00:16.225,000] <inf> main:   Turned on\r\n[00:00:17.229,000] <inf> main:   Turned off\r\n[00:00:18.234,000] <inf> main:   Increasing brightness gradually\r\n[00:00:20.260,000] <err> pwm_mcux: Too long period (234375), adjust pwm prescaler!\r\n[00:00:20.268,000] <err> main: err=-22\r\n[00:00:20.273,000] <inf> main: Testing LED 0 - no label\r\n[00:00:20.278,000] <inf> main:   Turned on\r\n
```

but I think we can fix it with https://github.com/zephyrproject-rtos/zephyr/issues/77970, and do not block this PR.

**Comment by danieldegrasse** [comment]
@lucien-nxp ping to fix the merge conflict when you get a chance

**Review by danieldegrasse — DISMISSED** [review]

**Review by danieldegrasse — DISMISSED** [review]

**Comment by lucien-nxp** [comment]
Only resolve the PR conflicts.

**Review by danieldegrasse — DISMISSED** [review]

**Comment by lucien-nxp** [comment]
Only rebase PR and resolve the conflicts.

**Review by mmahadevan108 — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@nordic-krch , can you help review

**Review by danieldegrasse — APPROVED** [review]

**Review by nordic-segl — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Pull request merged**
