### PR TITLE
Exx32 Sleeptimer

### PR DESCRIPTION
**Pull request by thorvald**
This uses the sl_sleeptimer service from the SDK to implement a low-energy wake-up timer for Exx32 MCUs.

Without this timer, if you enable sleep-states on these MCUs and wait for more than 5 seconds (the default for entering sleep state 1, aka EM2), the MCU will never wake up, as the systick timer is halted in EM2. Further complicating the current situation is that attaching a debug probe makes systick work even in EM2/EM3, so this problem only appears when not debugging.

### CODE REVIEW

**Comment by thorvald** [comment]
See https://github.com/zephyrproject-rtos/hal_silabs/pull/9 for matching PR

**Comment by chrta** [comment]
Can you provide some hints on how to test this (which sample application with what change)?

**Comment by thorvald** [comment]
@chrta One of my tests has been philosophers:
```
diff --git a/samples/philosophers/prj_tickless.conf b/samples/philosophers/prj_tickless.conf
index 0b448a8d9f..d9ed71e75d 100644
--- a/samples/philosophers/prj_tickless.conf
+++ b/samples/philosophers/prj_tickless.conf
@@ -7,3 +7,8 @@ CONFIG_SYS_POWER_MANAGEMENT=y
 CONFIG_TICKLESS_KERNEL=y

 CONFIG_MP_NUM_CPUS=1
+
+CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_1=1
+CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_2=2
+CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_3=3
+CONFIG_SYS_POWER_SLEEP_STATES=y
diff --git a/samples/philosophers/src/main.c b/samples/philosophers/src/main.c
index fb68126748..c54396edbf 100644
--- a/samples/philosophers/src/main.c
+++ b/samples/philosophers/src/main.c
@@ -55,7 +55,7 @@
 /* control the behaviour of the demo **/

 #ifndef DEBUG_PRINTF
-#define DEBUG_PRINTF 0
+#define DEBUG_PRINTF 1
 #endif

 #ifndef NUM_PHIL
```

```
cd samples/philosophers/
rm -rf build ; CONF_FILE="prj_tickless.conf" west build && west flash
```

Without this PR, this hangs as the system enters EM2/3 when sleeping more than 1 ms --  as the timer is based on HF clock, it will never trigger. If you run it in the debugger (which causes parts of the HF clock tree to be on even in EM2/3), it does work.

With this PR, this works, and the system idles in EM2. Note that you'll still see some serial console artifacts, as UART depends on HF clock as well, and it looks like it doesn't wait for the buffer to flush before allowing sleep. Future PR.

I did write a torture-test for this (weird configs and purposely busy-waiting with blocked irq etc), but it depends on piping the console output through "ts" and making sure time progresses at the same pace on the MCU as it does on the host.

**Comment by thorvald** [comment]
@chrta In case you already looked at the code, I just made a change to ```gecko_sleeptimer_callback```: It will announce 0 ticks if needed (the timeout is only reset in response to announcing, so if we don't announce, it won't get reset).

**Review by chrta — APPROVED** [review]
I tested the mentioned sample successfully on the efm32gg_stk3701a. So the philosophers example works as expected.
Most sanitycheck tests are also fine. I assume that the failed tests are caused by some other issue:
```
$ sanitycheck -p efm32gg_stk3701a -v --device-testing --device-serial /dev/ttyACM1

...
INFO    -  13/296 efm32gg_stk3701a          samples/subsys/nvs/sample.nvs.basic                FAILED Timeout (device 62.230s)
...
INFO    -  56/296 efm32gg_stk3701a          tests/net/checksum_offload/net.offload             FAILED Failed (device 4.880s)
...
INFO    -  71/296 efm32gg_stk3701a          tests/net/vlan/net.vlan                            FAILED Timeout (device 64.598s)
...
INFO    - 197/296 efm32gg_stk3701a          tests/kernel/sched/schedule_api/kernel.scheduler.multiq FAILED Failed (device 20.262s)
...
INFO    - 235/296 efm32gg_stk3701a          tests/kernel/timer/timer_api/kernel.timer          FAILED Failed (device 7.225s)
...
INFO    - 260/296 efm32gg_stk3701a          tests/lib/cmsis_dsp/basicmath/libraries.cmsis_dsp.basicmath FAILED Unknown (device 8.273s)
...
INFO    - 261/296 efm32gg_stk3701a          tests/lib/cmsis_dsp/support/libraries.cmsis_dsp.support FAILED Failed (device)
...
INFO    - 271 of 278 tests passed (97.48%), 7 failed, 668 skipped with 0 warnings in 2697.37 seconds
INFO    - In total 5241 test cases were executed on 1 out of total 299 platforms (0.33%)
INFO    - 277 tests executed on platforms, 1 tests were only built.
```

**Comment by thorvald** [comment]
@chrta Sorry for late feedeback here. I took a look through failing tests. A few of them failed to build due to missing abort(), but #29542 seemed to fix that, and I've rebased to include it.
There's still quite a few tests that fail. There's a few that are unreliable, and the remaining also fail on master, so I don't think they were introduced by this PR. Unreliable sanity-tests are a bit concerning, so I'll see if I can fix some of those in a separate PR, just need a better rig for long-running tests first :)

**Comment by chrta** [comment]
Since https://github.com/zephyrproject-rtos/zephyr/pull/31747 has been merged now, it would be good if this pr (and https://github.com/zephyrproject-rtos/hal_silabs/pull/9) could be rebased and use gecko sdk v3.1.0

**Pull request closed without merging**
