### PR TITLE
manifest: Update hostap to fix ECSA issue

### LINKED ISSUE #81123: net: wifi: Error log is seen during uAP switch to 2G's channel using ECSA when uAP started on 5G channels.
**Describe the bug**
Use NXP rd_rw621_bga board.
Error prints "<wrn> wpa_supp: Failed to check if DFS is required; ret=-1" are seen during SAP switch to 2G's channel using ECSA when SAP started on 5G channels.

**To Reproduce**
1. Load the build
2. Start SAP in Channel 36:
$ wifi ap enable -s AP_SSID -c 36
3. Connect Ex-STA to APUT and Verify association using ping traffic
4. Now request SAP to switch to CH6, warning prints
$ nxp_wifi uap-set-ecsa-cfg 1 0 6 10 1
<wrn> wpa_supp: Failed to check if DFS is required; ret=-1

**Expected behavior**
ECSA should work fine without any error messages.

**Impact**
 The root cause is that when SAP switch to 2.4G, its iface->current_mode is still about 5G, not updated. So the SAP state is not correct.
 
**Logs and console output**
$ nxp_wifi uap-set-ecsa-cfg 1 0 6 10 1
Command wlan-uap-set-ecsa-cfg
$ uap switch to channel 6 success!
[00:46:11.618,293] <inf> wpa_supp: ua: CTRL-EVENT-CHANNEL-SWITCH freq=2437 ht_enabled=1 ch_offset=0 ch_width=20 MHz cf1=2437 cf2=0 d0
[00:46:11.633,317] <inf> wpa_supp: ua: AP-CSA-FINISHED freq=2437 dfs=0
[00:46:11.642,514] <wrn> wpa_supp: Failed to check if DFS is required; ret=-1

### PR DESCRIPTION
**Pull request by MaochenWang1**
Update hostap to fix ECSA issue that warning log and current_mode is not updated.
Fix: https://github.com/zephyrproject-rtos/zephyr/issues/81123

### CODE REVIEW

**Comment by jukkar** [comment]
@MaochenWang1 if you think we need this for 4.0, then please create an issue and add "Fixes #...." to this PR description.

**Comment by MaochenWang1** [comment]
> @MaochenWang1 if you think we need this for 4.0, then please create an issue and add "Fixes #...." to this PR description.

thanks,  added

**Comment by jukkar** [comment]
@MaochenWang1 the hostap pr is now merged, please update the manifest file

**Comment by MaochenWang1** [comment]
> @MaochenWang1 the hostap pr is now merged, please update the manifest file

Hi @jukkar updated, please review

**Review by jukkar — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
