### PR TITLE
Add json-c external module

### LINKED ISSUE #59303: Add json-c as external module
## Origin

JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects. It aims to conform to [RFC 7159](https://tools.ietf.org/html/rfc7159).

URL: https://github.com/json-c/json-c

## Purpose

json-c provides friendly API to frame and parse json messages. It's well known in the Linux world and bringing it helps,

- building cross platform (compatible between Linux and zephyr apps)
- Friendly dynamic processing of complex json objects

Comparing with available native json data handling, json-c helps,
- framing json payloads using heap memory
- No need to statically pre-built json structures

## Mode of integration

Mode of integration: External module
Repository name: json-c
Reason: To keep in sync with the open source version of json-c, which helps rebasing

## Maintainership

- json-c open source community
- @ssekar15 
- @parthitce 

## Pull Request

Yet to prepare a final one based on https://github.com/linumiz/json-c/tree/zephyr

## Description

Please refer to https://json-c.github.io/json-c/

What is its primary functionality?
- JSON parsing and framing with friendly API's with extended functionality

What problem are you trying to solve?
- JSON processing with existing native implementation needs static definition of the json structures
- Dynamic parsing and framing of json objects

Why is this the right component to solve it?
- Predominant in use in Linux world and well known for it's stability
- ~18K footprint in memory (text + data + bss)

## Dependencies

What other components does this package depend on?
- None

Will the Zephyr project have a direct dependency on the component, or
will it be included via an abstraction layer with this component as a
replaceable implementation?
- We will have abstraction for file handling if needed based on LFS

## Revision

Version or SHA you would like to integrate initially
- https://github.com/json-c/json-c/releases/tag/json-c-0.16-20220414

## License

Please use an SPDX identifier (https://spdx.org/licenses/), such as
``BSD-3-Clause``
- https://github.com/json-c/json-c/blob/master/COPYING
- MIT License

### PR DESCRIPTION
**Pull request by parthitce**
- add initial support for json-c external module
- current dependency points to linumiz/fork of json-c

Fixes #59303

### CODE REVIEW

**Comment by parthitce** [comment]
```
In file included from modules/lib/json-c/json_object_private.h:25,                                                         
                 from modules/lib/json-c/json_object_iterator.c:17:                                                        
modules/lib/json-c/json_types.h:62:14: error: redeclaration of 'enum json_type'                                            
   62 | typedef enum json_type                                                                                                                                
      |              ^~~~~~~~~                                                                                                                                
In file included from modules/lib/json-c/json_object_iterator.c:16:                                                        
modules/hal/espressif/zephyr/esp32/../../components/wpa_supplicant/src/utils/json.h:13:14: note: originally defined here   
   13 |         enum json_type {         
   ```
   
With current state, we have the above conflict only for esp HAL and json-c. Should we have conditional compilation based on Kconfig for wpa_supplicant @sylvioalves ?

**Comment by sylvioalves** [comment]
> ```
> In file included from modules/lib/json-c/json_object_private.h:25,                                                         
>                  from modules/lib/json-c/json_object_iterator.c:17:                                                        
> modules/lib/json-c/json_types.h:62:14: error: redeclaration of 'enum json_type'                                            
>    62 | typedef enum json_type                                                                                                                                
>       |              ^~~~~~~~~                                                                                                                                
> In file included from modules/lib/json-c/json_object_iterator.c:16:                                                        
> modules/hal/espressif/zephyr/esp32/../../components/wpa_supplicant/src/utils/json.h:13:14: note: originally defined here   
>    13 |         enum json_type {         
> ```
> 
> With current state, we have the above conflict only for esp HAL and json-c. Should we have conditional compilation based on Kconfig for wpa_supplicant @sylvioalves ?

There is no Kconfig or conditional compilation right now. Let me see how we can work this out.

**Comment by parthitce** [comment]
@nashif @mrfuchs Ping for json-c!

**Comment by sylvioalves** [comment]
@parthitce, in case needed: https://github.com/zephyrproject-rtos/hal_espressif/pull/230

**Comment by parthitce** [comment]
> @nashif @mrfuchs Ping for json-c!

@nashif @mrfuchs Gentle ping!

**Comment by parthitce** [comment]
@nashif @mrfuchs Gentle ping!

**Pull request closed without merging**
