### PR TITLE
drivers: pwm: Restore default on re-initialization

### PR DESCRIPTION
**Pull request by pdunaj**
Jira:NCSDK-11329

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

**Comment by pdunaj** [comment]
The PWM is not able to properly driver pins after wakeup as it looses some of the configuration during deinit.
The patch restores default configuration.

**Comment by anangl** [comment]
Rebase, please.

**Review by MarekPieta — APPROVED** [review]

**Comment by pdunaj** [comment]
ah... is this nonsensical political correctness. I rebased on master but apparently somebody got changed the well established name for no good reason. Will rebase.

**Review by anangl — APPROVED** [review]

**Review by rakons — APPROVED** [review]

**Review by nashif — DISMISSED** [review]
Please remove references to Jira:NCSDK-11329

Add links to GH issues instead.

**Comment by pdunaj** [comment]
> Please remove references to Jira:NCSDK-11329
> 
> Add links to GH issues instead.

removed link; GH issue is not created in this case

**Comment by pdunaj** [comment]
Zephyr in its entirety. 2 months of being ready for review...

**Review by carlescufi — APPROVED** [review]

**Comment by nashif** [comment]
@pdunaj  can you please rebase and push again to get a fresh CI verdict, it has been a while since this was last checked.

**Comment by carlescufi** [comment]
> @pdunaj can you please rebase and push again to get a fresh CI verdict, it has been a while since this was last checked.

Sorry! I had this pr open in a tab and your comment did not show before I merged

**Pull request merged**
