### PR TITLE
hwmv2: move all non-ported legacy boards and socs to legacy folders

### PR DESCRIPTION
**Pull request by tejlmand**
To un-block continuing of soc and board porting then move all socs and boards which have not yet been ported to boards_legacy / soc_legacy folders.

All ported socs and boards are moved to their final location.

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Review by erwango — DISMISSED** [review]
Some details please

**Comment by erwango** [comment]
Additional question: should we hold all migrations waiting for this change to be merged?

**Comment by nordicjm** [comment]
This moves all v1 boards and socs to a new location, which will mean that the v2 location here is the final v2 location i.e. all paths can be updated as they will be the correct paths. If you have a v1 -> v2 port PR ready now to review, it can be posted and merged before this. If you have something you are going to port but have not yet started, you should use this as the base

**Review by simonguinot — DISMISSED** [review]
Hi @tejlmand. Shouldn't you update the `MAINTAINERS.yml` file as well ? Else it will be broken in the `collab-hwm` branch for all the boards moved into `boards/boards_legacy`...

**Comment by tejlmand** [comment]
> Hi @tejlmand. Shouldn't you update the `MAINTAINERS.yml` file as well ? Else it will be broken in the `collab-hwm` branch for all the boards moved into `boards/boards_legacy`...

the maintainers file is already broken for boards which have been ported to new hwm.
We plan to do a single update to the maintainers file, as this will minimize conflicts compared to having n-PRs which all updates maintainer file when porting socs and boards.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
