### PR TITLE
stm32 can misc

### PR DESCRIPTION
**Pull request by passgat**
The pull request includes some trivial fixes to the can_stm32.c file. 
I grouped them into a single pull request instead of creating three pull requests for each patch.

### CODE REVIEW

**Review by ABOSTM — APPROVED** [review]
@passgat , Thanks for this Pull Request.
Would be great to have a description in the PullRequest, otherwise LGTM

**Comment by passgat** [comment]
Gentle ping.

Thanks,
Dario

**Comment by alexanderwachter** [comment]
Unfortunately I'm on holiday.
I'll have a look when I'm back.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Please include a description of the changes in the PR itself. Otherwise looks good.

**Comment by passgat** [comment]
Gentle ping.

Thanks,
Dario

**Review by henrikbrixandersen — APPROVED** [review]

**Review by alexanderwachter — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
