### PR TITLE
manifest: Update openthread to b21e99b.

### PR DESCRIPTION
**Pull request by canisLupus1313**
This commit updates openthread to b21e99b.
Secondly, this commit aligns the history of openthread to Vanilla version 1:1.

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Review by rlubos — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
Hey I tagged this for v3.3.0, let us know if the update is to fix a security issue or something that should go for v3.2.0 instead.

**Comment by canisLupus1313** [comment]
@fabiobaltieri what is the timeline for v3.3?

**Comment by fabiobaltieri** [comment]
The release is scheduled for the 30th (https://github.com/zephyrproject-rtos/zephyr/wiki/Release-Management), it's more a matter of whether there's something critical in there.

**Comment by canisLupus1313** [comment]
@fabiobaltieri There are a few bug fixes introduced in this upmerge but those can wait till the 30th.

**Pull request closed without merging**
