### PR TITLE
tests: Remove newline character

### LINKED ISSUE #7170: zassert: Confusing rules and actual usage for messages in zassert_*() calls
Split off from https://github.com/zephyrproject-rtos/zephyr/pull/7164#discussion_r183550890 .

It seems that there're no clear rules on how to format failure messages for zassert_equal(), etc. calls. For example, I recently submitted 3-4 patches for tests, and with the last one, was randomly stopped by a project maintainer requiring me put "\n" at the end of such messages: https://github.com/zephyrproject-rtos/zephyr/pull/7164#discussion_r183550890 . None of these calls/messages were written by me, but were copy-pasted from the code written previously by other people.

To illustrate the situation better, here's a grep inside zephyr/tests/subsys/ :

~~~
zephyr/tests/subsys$ grep -r -E "zassert.+;$" * | wc
    761    4765   65257
zephyr/tests/subsys$ grep -r -E "zassert.+;$" * | grep  '\n");' | wc
    105     818   10488
zephyr/tests/subsys$ grep -r -E "zassert.+;$" * | grep  -v '\n");' | wc
    656    3947   54769
~~~

As can be seen, majority of developers have no idea that any particular trailer is required for zassert messages. Nor there seems to be any sense in requiring them - each such message is a standalone notice to user, which would be printed on a separate line anyway, and of course, zassert subsystem can handle special codes required for that, like carriage returns/line feeds, itself. 

Consequently, we can do one of the following:

1. Continue to have rules which don't seem to have much sense, are known to few, and applied inconsistently, as the case with a few of my PRs and grep stats above show.
2. Or clean it up and make work in a natural and intuitive way, with no special message trailers required.

### PR DESCRIPTION
**Pull request by punitvara**
Remove new line character from all zassert_*
messages. Following script has been used to do this.

https://github.com/punitvara/scripts/blob/master/remove_newlinech.py

Fixes #7170

Signed-off-by: Punit Vara <punit.vara@intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
This sounds unnecessary thing to do. Why not check when printing if the last character in the string is \n, and if it is not, then print \n at the end. Then we would not need this patch that touches lot of files in some automatic way.

**Comment by nashif** [comment]
> This sounds unnecessary thing to do. Why not check when printing if the last character in the string is \n, and if it is not, then print \n at the end. Then we would not need this patch that touches lot of files in some automatic way.

what is wrong with touching too many files? We can't be working around inconsistencies in the code just to not have commits touching too many files.

**Review by nashif — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]
+1 from me too. It's better to fix such cases once and for all, especially for should-have-been-LTS release. Otherwise, people will just copy-paste the code, and inconsistency will creep on.

**Comment by pfalcon** [comment]
recheck

**Review by spoorthik — APPROVED** [review]

**Comment by nashif** [comment]
only test failing is unrelated, will be fixed in some other PR.

**Pull request merged**
