### PR TITLE
samples: mesh/onoff-app: Enable persistent storage support

### PR DESCRIPTION
**Pull request by vikrant8052**
Enable persistent storage support in
samples/boards/nrf52/mesh/onoff-app.

Signed-off-by: Vikrant More <vikrant8051@gmail.com>

### CODE REVIEW

**Comment by vikrant8051** [comment]
@jhedberg @carlescufi 
I've enable persistent storage support for samples/boards/nrf52/mesh/onoff-app. 
Please review it.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks generally good, but two things that need fixing:

 - Use a more descriptive commit message subject, e.g. "samples: mesh/onoff-app: Enable persistent storage support"

- Remove the merge commit (simply rebasing against master should take care of it)

**Comment by vikrant8051** [comment]
@jhedberg I've make suggested changes. Please approved this now.

**Review by jhedberg — APPROVED** [review]

**Comment by vikrant8051** [comment]
@jhedberg  Thanks for merging it. :+1: 

Now it's my request to check the issue of 
"Persistent data storage which is not reliable after un-provisioning & re-provisioning the same Device " by using samples/boards/nrf52/mesh/onoff-app.

Try to control LEDs using #nRFMesh GUI Buttons
after re-provisioning ---> reseting the board.

**Pull request merged**
