### PR TITLE
Fix test plan to skip unconnected platforms

### PR DESCRIPTION
**Pull request by mbrunnen**
This change fixes the logic for filtering integration platforms in the test plan to skip unspecified ones based on the hardware map and the `--platform` option.

Changes Made:
- Removed the redundant condition `not self.options.platform` since it was never met in test-only mode.
- Modified the logic to correctly extract connected platforms from the DUT objects. DUT is not a dictionary.
- Updated the code to skip integration platforms that are not specified by the hardware map or the `--platform` option.

This change addresses issue #62723.

### CODE REVIEW

**Comment by nashif** [comment]
duplicate of #62560?

**Comment by mbrunnen** [comment]
> duplicate of #62560?
[PR!62671](https://github.com/zephyrproject-rtos/zephyr/pull/62671) should solve my problem, but still DUT is not a dictionary and the else case will never be executed. `self.options.platform` is always true in test-only mode.

```python

            if self.options.platform:
                connected_list = self.options.platform
            else:
                for connected in self.hwm.duts:
                    if connected['connected']:
                        connected_list.append(connected['platform'])
```

**Comment by mbrunnen** [comment]
I updated this PR, to just remove broken if branch. And updated the comment.

**Review by gchwier — DISMISSED** [review]
Right, `discover` method updates `options.platform`.

**Review by nashif — DISMISSED** [review]

**Review by gchwier — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
