### PR TITLE
Bluetooth: controller: Allow any valid ISO sync receiver BIG handle

### PR DESCRIPTION
**Pull request by mtpr-ot**
The BIG handle for an ISO sync receiver is provided by the host. The valid range is [0x00..0xEF], and this requires the controller to allow non-consecutive handle numbering. This means that even if only one sync set is supported, a BIG handle of ex. value 2 must be supported.

As the code uses indexing and range checking directly by handle, this needs to be changed. Introducing the handle index, which sequnces the handles such that index = 0 is always the "first handle", regardless of value.

### CODE REVIEW

**Comment by mtpr-ot** [comment]
This implementation may need changes for architectural reasons. The concept works fine and does the job (qualification tests pass), but there may be a nicer way to have both handle and index of handle, without the need to call a look-up function in many places. Suggestions are welcome.

**Comment by cvinayak** [comment]
> This implementation may need changes for architectural reasons. The concept works fine and does the job (qualification tests pass), but there may be a nicer way to have both handle and index of handle, without the need to call a look-up function in many places. Suggestions are welcome.

I think there is handle translation in hci for extended advertising sets, may be that can be reused here? Will review this PR in office tomorrow.

**Review by erbr-ot — COMMENTED** [review]
Looks pretty solid to me - can't see how to setup a map [0-0xEF] -> [index] without the mechanisms you suggest. To allow early exit 'on un-used big_handle' of the sync_iso_get() one could pre-init the big_handles to invalid value so as to allow the for-loop to check only used indicies.

**Review by cvinayak — DISMISSED** [review]
On second look... the changes are acceptable for me.

Please rebase and resolve conflicts.

**Review by erbr-ot — APPROVED** [review]
SLGTM

**Review by cvinayak — APPROVED** [review]

**Pull request merged**
