### PR TITLE
NXP drivers: dma: dma_mcux_pxp: Add flip feature

### PR DESCRIPTION
**Pull request by DerekSnell**
Update PXP driver to flip horizontally and/or vertically.  Also updated display_mcux_elcdif driver to flip when writing to display. Tested with sample/subsys/video/capture.

### CODE REVIEW

**Review by dleach02 — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Comment by kartben** [comment]
#73001 was merged before this one. Please resubmit, @DerekSnell, as the files are now in the wrong folder

**Comment by DerekSnell** [comment]
> #73001 was merged before this one. Please resubmit, @DerekSnell, as the files are now in the wrong folder

Will do, thanks for making me aware.

**Comment by ngphibang** [comment]
@DerekSnell : The video capture sample has been moved from `sample/subsys/video/capture` to `sample/subsys/video/capture`. I don't understand why you still let the board configs files (1064 and 1060 evk) in /subsys and not place them in /drivers ? and does it really work when the configs and the sample code are in two different places ?

**Comment by DerekSnell** [comment]
Hi @ngphibang ,
No, it won't work, and this was not intentional.  As kartben [stated above](https://github.com/zephyrproject-rtos/zephyr/pull/76484#issuecomment-2291598109), https://github.com/zephyrproject-rtos/zephyr/pull/73001 merged 2 days before this PR, and moved that sample.  Now we need a new PR to move these files.

Best regards

**Pull request merged**
