### PR TITLE
tests: Bluetooth: Mesh: Add tests to cover message publication

### PR DESCRIPTION
**Pull request by PavelVPV**
This is a copy of https://github.com/zephyrproject-rtos/zephyr/pull/41187 recreated after the original change was reverted here: https://github.com/zephyrproject-rtos/zephyr/pull/41344 due to a failing provisioning test. After setting `CONFIG_SYS_CLOCK_TICKS_PER_SEC` to 1000 (default is 100) the provisioning tests start failing when exchanging public key. Fix is in this PR: https://github.com/zephyrproject-rtos/zephyr/pull/41414

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by aescolar** [comment]
@PavelVPV Are you seeing cases fail at random? If so, that should never happen in simulation. (The only case in which that can happen is if something is broken badly somewhere, by for example having a test execution depend on an unitialized variable, or if somebody has introduced some other "random" behaviour. But such things should never been there)

**Comment by carlescufi** [comment]
> @PavelVPV Are you seeing cases fail at random? If so, that should never happen in simulation. (The only case in which that can happen is if something is broken badly somewhere, by for example having a test execution depend on an unitialized variable, or if somebody has introduced some other "random" behaviour. But such things should never been there)

I believe they were failing systematically. What I do not know is why they started failing suddenly, which prompted the necessity now to increase the timeout from 1000 to 1200 ms.

**Comment by alxelax** [comment]
> @PavelVPV Are you seeing cases fail at random? If so, that should never happen in simulation. (The only case in which that can happen is if something is broken badly somewhere, by for example having a test execution depend on an unitialized variable, or if somebody has introduced some other "random" behaviour. But such things should never been there)
> 
> I havent looked into the failing case, but setting CONFIG_SYS_CLOCK_TICKS_PER_SEC to 1000 sound quite a bit like something that is trying to mask a problem

This is the only test suite that uses BabbleSim backchannel for OOB communication between two executables. 
The issue exactly means no data has been received via the backchannel. Probably 1 sec is not enough to generate a key using uECC library, establish a back channel and receive this key. Even more, I'm not sure how the system clock impacts on backchannel communication.

**Review by alxelax — APPROVED** [review]

**Comment by aescolar** [comment]
> This is the only test suite that uses BabbleSim backchannel for OOB communication between two executables. The issue exactly means no data has been received via the backchannel. Probably 1 sec is not enough to generate a key using uECC library, establish a back channel and receive this key. Even more, I'm not sure how the system clock impacts on backchannel communication.

Note that embedded code executes in zero simulated time in the nrf52_bsim. If the uECC library does not use HW models, and does not "waste" time sleeping, calls to it will be done in zero time.
The backchannels should also be deterministic and add no delay, meaning, once one side sends something it is immediately available to the receiver. Note also that both devices do not really execute in parallel (they are step-locked) as soon as they start having radio activity.
That does not exclude that something else may have delayed the key exchange in simulated time, but whatever it may be, it should still be deterministic. If it is not we have a bug somewhere we need to fix (otherwise we are going to waste time debugging sporadic behaviours)

**Comment by carlescufi** [comment]
@PavelVPV @alxelax @trond-snekvik could we do a quick investigation before we merge this?

**Comment by alxelax** [comment]
> @PavelVPV @alxelax @trond-snekvik could we do a quick investigation before we merge this?
I'm able to take a look tomorrow morning if it is Ok.
Could we add DNM label before this?

**Comment by PavelVPV** [comment]
@aescolar, I didn't set `CONFIG_SYS_CLOCK_TICKS_PER_SEC` to 1000 to mask the problem. I set it to 1000 to make `k_uptime_get()` more precise (1ms precision instead of 10ms) in the new test. The issue appeared _after_ I set CONFIG_SYS_CLOCK_TICKS_PER_SEC to 1000. It is easy to check on the main branch by adding CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000 in prj.conf and then running the failing test. Then most of the time the receiver will abort the test before `uECC_make_key` is able to generate the new key pair. It is easier to see if sleep for 1 second in 100ms intervals on the receiver instead of sleeping for 1 second continuously. If `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is default (100), then most of time it will take 900ms (in 100ms intervals) before `uECC_make_key` returns new pair. When `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is set to 1000, then in most of time it will take 1000ms. I say _most of time_ because sometimes (rarely) key pair can be generated much earlier or immediately. I didn't dig deeply into `uECC_make_key` function. My guess is that rounding error causes this.

**Comment by PavelVPV** [comment]
@aescolar Please disregard part of my last comment. `uECC_make_pair` generates pair in constant time from what I see. The issue happens when the public key is sent.

**Comment by PavelVPV** [comment]
And this is not because of uninitialised variable. The receiver just ends the session because it doesn't receive the key.

**Comment by aescolar** [comment]
> @aescolar Please disregard part of my last comment. `uECC_make_pair` generates pair in constant time from what I see. The issue happens when the public key is sent.

@PavelVPV Is the very first thing the waiting device does, wait for the key to be sent off band before starting any radio activity?

**Comment by carlescufi** [comment]
> > @PavelVPV @alxelax @trond-snekvik could we do a quick investigation before we merge this?
> 
> I'm able to take a look tomorrow morning if it is Ok. Could we add DNM label before this?

Yes please. I set the label now.

**Comment by alxelax** [comment]
I tried to reproduce the issue but test always passes with both system clocks (1000 and 100) on my PC. I kind of agree with @aescolar in that all used functionalities have deterministic time. However, I'm pretty sure that two executables might have time shifts one against another and device that expects OOB key might start first. That depends on ongoing Linux activities, priorities, and the most important thing is PC performance. 

Looking at the log of the error case we see device public key has not been really sent via OOB aka back channel:
```
d_01: @00:00:00.000000  *** Booting Zephyr OS build v2.7.99-2638-g965a612071f8  ***
d_00: @00:00:00.000000  *** Booting Zephyr OS build v2.7.99-2638-g965a612071f8  ***
d_00: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
d_00: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
d_00: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.7 Build 99
d_01: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
d_01: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
d_01: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.7 Build 99
d_01: @00:00:00.000000  [00:00:00.000,000] <wrn> bt_id: No static addresses stored in controller
d_00: @00:00:00.000000  [00:00:00.000,000] <wrn> bt_id: No static addresses stored in controller
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: Identity: ED:71:8F:C2:E4:6E (random)
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x0059
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Bluetooth initialized
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Mesh initialized
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: Identity: ED:3B:20:15:18:12 (random)
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x0059
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Bluetooth initialized
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Mesh initialized
d_01: @00:00:00.979492 ERROR: (WEST_TOPDIR/zephyr/tests/bluetooth/bsim_bt/bsim_test_mesh/src/test_provision.c:321): OOB public key is not gotten
```

d_01 checks key that has not been sent yet.

for example this is log of the normal behavior:
```
d_01: @00:00:00.000000  *** Booting Zephyr OS build v2.7.99-2659-ge1b845cc8875  ***
d_00: @00:00:00.000000  *** Booting Zephyr OS build v2.7.99-2659-ge1b845cc8875  ***
d_00: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
d_00: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
d_00: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.7 Build 99
d_00: @00:00:00.000000  [00:00:00.000,000] <wrn> bt_id: No static addresses stored in controller
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: Identity: ED:3B:20:15:18:12 (random)
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x0059
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Bluetooth initialized
d_00: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Mesh initialized
d_01: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
d_01: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
d_01: @00:00:00.000000  [00:00:00.000,000] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.7 Build 99
d_01: @00:00:00.000000  [00:00:00.000,000] <wrn> bt_id: No static addresses stored in controller
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: Identity: ED:71:8F:C2:E4:6E (random)
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x0059
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Bluetooth initialized
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_test: Mesh initialized
d_00: @00:00:00.010328  [00:00:00.010,314] <inf> mesh_prov: OOB Public Key:
d_00: @00:00:00.010328                                      fd 97 15 d1 4a 9f 00 a0  a7 c1 26 1f 75 ca 12 8a |....J... ..&.u...
d_00: @00:00:00.010328                                      59 bd cf 42 76 54 27 8a  bd be 7c 0f 0f a7 67 ca |Y..BvT'. ..|...g.
d_00: @00:00:00.010328                                      e4 fb 12 2e fc 47 66 41  8b 0d c6 c3 c5 36 bc 28 |.....GfA .....6.(
d_00: @00:00:00.010328                                      c3 5d de 5d df 9a 68 bc  b8 bc ca c1 fb c5 af 38 |.].]..h. .......8
d_00: @00:00:00.010328  [00:00:00.010,314] <inf> bt_mesh_prov_device: Device UUID: 00000000-0000-0000-0030-6f61676e696c
d_01: @00:00:00.002648  [00:00:00.002,624] <inf> mesh_prov: OOB Public Key:
d_01: @00:00:00.002648                                      fd 97 15 d1 4a 9f 00 a0  a7 c1 26 1f 75 ca 12 8a |....J... ..&.u...
d_01: @00:00:00.002648                                      59 bd cf 42 76 54 27 8a  bd be 7c 0f 0f a7 67 ca |Y..BvT'. ..|...g.
d_01: @00:00:00.002648                                      e4 fb 12 2e fc 47 66 41  8b 0d c6 c3 c5 36 bc 28 |.....GfA .....6.(
d_01: @00:00:00.002648                                      c3 5d de 5d df 9a 68 bc  b8 bc ca c1 fb c5 af 38 |.].]..h. .......8
```

d_00 should send key first d_01 receives it afterward. 

Per my understanding, emulated Zephyr time depends very much on PC performans. It was a logical mistake to use:
`k_sleep(K_SECONDS(1));` emulated delay to wait for Linux processes switching.
Waiting time depends very much on PC performance. It is why I cannot see issue on a not very fast PC like my laptop, or we see the random issue on the build server that depends on ongoing server loading. 
Changing the system clock from 100 to 1000 caused better precision of some procedures that become faster due to better time granularity. This is why adding 1200 instead of 1000 made the test passable again (just an additional time margin).
My suggestion is to use normal delay(POSIX based) to wait for inter-executable communication. 
It will make the test a system clock and platform independent.

**Comment by alxelax** [comment]
If this sounds reasonable for you I will apply patch with POSIX delay to this PR

**Comment by aescolar** [comment]
Hi guys. This is the result of running the test with the scheduler being verbose with the current PR:
```
Starting prov_device_pb_adv_oob_public_key as device #0
Starting prov_provisioner_pb_adv_oob_public_key as device #1
Starting phy with 2 devices
d_01: @00:00:00.000000  *** Booting Zephyr OS build v2.7.99-2280-gfe840c514957  ***
d_00: @00:00:00.000000  *** Booting Zephyr OS build v2.7.99-2280-gfe840c514957  ***
d_01: @00:00:00.000000  [00:00:00.000,000] ESC[0m<inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)ESC[0m
d_01: @00:00:00.000000  [00:00:00.000,000] ESC[0m<inf> bt_hci_core: HW Variant: nRF52x (0x0002)ESC[0m
d_01: @00:00:00.000000  [00:00:00.000,000] ESC[0m<inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.7 Build 99ESC[0m
d_01: @00:00:00.000000  [00:00:00.000,000] ESC[1;33m<wrn> bt_id: No static addresses stored in controllerESC[0m
d_00: @00:00:00.000000  [00:00:00.000,000] ESC[0m<inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)ESC[0m
d_00: @00:00:00.000000  [00:00:00.000,000] ESC[0m<inf> bt_hci_core: HW Variant: nRF52x (0x0002)ESC[0m
d_00: @00:00:00.000000  [00:00:00.000,000] ESC[0m<inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.7 Build 99ESC[0m
d_00: @00:00:00.000000  [00:00:00.000,000] ESC[1;33m<wrn> bt_id: No static addresses stored in controllerESC[0m
d_01: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> bt_hci_core: Identity: ED:71:8F:C2:E4:6E (random)ESC[0m
d_01: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x0059ESC[0m
d_01: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffffESC[0m
d_01: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> mesh_test: Bluetooth initializedESC[0m
d_01: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> mesh_test: Mesh initializedESC[0m
d_00: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> bt_hci_core: Identity: ED:3B:20:15:18:12 (random)ESC[0m
d_00: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x0059ESC[0m
d_00: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffffESC[0m
d_00: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> mesh_test: Bluetooth initializedESC[0m
d_00: @00:00:00.002648  [00:00:00.002,624] ESC[0m<inf> mesh_test: Mesh initializedESC[0m
d_00: @00:00:00.010328  [00:00:00.010,314] ESC[0m<inf> mesh_prov: OOB Public Key:
d_00: @00:00:00.010328                                      fd 97 15 d1 4a 9f 00 a0  a7 c1 26 1f 75 ca 12 8a |....J... ..&.u...
d_00: @00:00:00.010328                                      59 bd cf 42 76 54 27 8a  bd be 7c 0f 0f a7 67 ca |Y..BvT'. ..|...g.
d_00: @00:00:00.010328                                      e4 fb 12 2e fc 47 66 41  8b 0d c6 c3 c5 36 bc 28 |.....GfA .....6.(
d_00: @00:00:00.010328                                      c3 5d de 5d df 9a 68 bc  b8 bc ca c1 fb c5 af 38 |.].]..h. .......8ESC[0m
d_00: @00:00:00.010328  [00:00:00.010,314] ESC[0m<inf> bt_mesh_prov_device: Device UUID: 00000000-0000-0000-0030-6f61676e696cESC[0m
p_2G4:  main: Connecting...
p_2G4: @00:00:00.000000  Device 0 wants to Rx in 13558 (abort,recheck at 18446744073709551615,13568)
p_2G4: @00:00:00.000000  Device 1 wants to wait until 1174802
```
You can see the test OOB exchange happens before any radio activity. And that the first time device 1 interacts with the Phy is at 1,17 seconds (that wait is triggered by the max resync time* in the nrf52_bsim with the phy, and it is most likely the first RTC tick that happens after 1second)
As mentioned before, during boot and until the first radio activity*, devices run asynchronously. Only when there starts being radio activity they are step-locked (because it normally does not matter in which exact order they boot).
Simulated time is way faster than real time, and as the devices are not synchronized (thru the Phy) yet, that 1st second of d1 can easily happen before d0 even starts.
And therefore the test fails at random

*or 1 second by default in the nrf52_bsim https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/posix/nrf52_bsim/time_machine.c#L63

>If this sounds reasonable for you I will apply patch with POSIX delay to this PR

That is not a good fix. (it would mask the problem most of the time, but you will still have very loaded systems sometimes where waiting 1 real time second is not going to fix the issue)

**Comment by alxelax** [comment]
> That is not a good fix. (it would mask the problem most of the time, but you will still have very loaded systems sometimes where waiting 1 real time second is not going to fix the issue)
> You'd want to call that function I pointed at above in the test initialization in both devices with say, 100ms, to ensure they never drift apart in simulated time by more than those 100ms.

Devices will not drift from any other more than 100 ms. This is Ok. However, it still requires real-time delay since emulated time cannot guarantee 100ms. @aescolar  Am I right?

**Comment by aescolar** [comment]
>it still requires real-time delay since emulated time cannot guarantee 100ms

You should not need any connection to real time from bsim tests (and you should actually not add it, as that can/will create unwanted issues)
When you call tm_set_phy_max_resync_offset(100000), the HW models will ensure that the device simulated time will never be farther ahead than 100 ms from the Phy simulated time. If all simulated devices do so, you can be sure no device is more than 100ms from each other in simulated time.
Nothing in the nrf52_bsim cares or knows about real time (unless you start checking it on your tests on your own by calling the underlaying Linux OS)

**Comment by alxelax** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/41414 with suggested fixes

**Comment by carlescufi** [comment]
@PavelVPV or @alxelax could you rebase this PR?
@aescolar can you take another look please?

**Comment by PavelVPV** [comment]
Rebased. Sorry for a bit of mess.

**Pull request merged**
