### PR TITLE
submanifests: optional: Bump nanopb to 0.4.9

### PR DESCRIPTION
**Pull request by pdgendt**
Sync upstream and get the latest tagged version 0.4.9.

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@nashif @carlescufi can you help review

**Comment by mmahadevan108** [comment]
@pdgendt , need an update to the release notes?

**Review by nashif — DISMISSED** [review]

**Comment by pdgendt** [comment]
Added release note

**Comment by kartben** [comment]
Isn't it a bit late to take module updates?

**Review by mmahadevan108 — APPROVED** [review]

**Comment by dkalowsk** [comment]
> Isn't it a bit late to take module updates?

This was one of the concerns I had brought up in the last Release meeting.  A few of our modules are needing updates and the maintainers are working on it, but the time lines are not lining up with the 4.0 release.  I don't think we came to any final conclusion during that discussion.  Likely want to have this discussion not on the PR though :-)

**Review by dkalowsk — APPROVED** [review]

**Pull request merged**
