### PR TITLE
dma: hda: enable xrun handling

### PR DESCRIPTION
**Pull request by makarukp**
This is proposition of enabling link under/overruns handling and reporting such events in dma status. 

Signed-off-by: Piotr Makaruk <piotr.makaruk@intel.com>

### CODE REVIEW

**Review by teburd — CHANGES_REQUESTED** [review]
In looking at the sof code for HDA this is logged, cleared, and then ignored. See https://github.com/thesofproject/sof/blob/main/src/drivers/intel/hda/hda-dma.c#L933

GPDMA does not have specific flagging to say there was an under/over run, but that the transfer (an endless loop of them in sof) has stopped by checking the enable bit, signaling an under/over run. https://github.com/thesofproject/sof/blob/main/src/drivers/dw/dma.c#L1126

I think returning -ENODATA here from get_status is good though! The error return is enough to signal an under/over run as the stream direction should be known by the caller.

So lets remove the bool additions from the status struct here, which are going to be unused by all other DMAs in Zephyr today and document the -ENODATA return.

Doing that, +1 from me easy

**Comment by makarukp** [comment]
@teburd 
I agree, it can be deduced by SOF and such approach seems to be enough.
According to https://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html shouldn't we change -ENODATA to -EPIPE  ?

**Comment by kv2019i** [comment]
> @teburd I agree, it can be deduced by SOF from stream direction and such approach seems to be enough. According to https://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html shouldn't we change -ENODATA to -EPIPE ?

For the error code, SOF has used ENODATA quite a bit, but I do agree EPIPE is probably better. ENODATA is more often used in cases, where the condition is not a fatal error yet, there's just not data yet. EPIPE seems more fitting as signals a more severe problem, which applies here as the DMA did run out of data leading to data loss.

**Review by teburd — APPROVED** [review]

**Review by dabekjakub — COMMENTED** [review]
Is this report generic for HDA link? In any case information in the comment on report functions describing where we actually reporting it to would be good I think.

Maybe to be more specific: If I was reading this not knowing the context I would ask myself why we clear on the xrun detect.

**Review by mwasko — APPROVED** [review]

**Comment by makarukp** [comment]
> Is this report generic for HDA link? In any case information in the comment on report functions describing where we actually reporting it to would be good I think.
> 
> Maybe to be more specific: If I was reading this not knowing the context I would ask myself why we clear on the xrun detect.

@dabekjakub  Good point. Yes, this is generic for HDA link. From SOF point of view link status is retrieved each time new data is copied from/to link in DAI or Chain DMA interfaces. Once we had a chance to get its status, we clear stat register and this is the only chance to handle xrun. After retrieving xrun we have  to clean it to be able to check it during next chunk processing. However, I am a little bit concerning if we should not move  reg clearing it to dma_reload...    What do you think ?

**Comment by fabiobaltieri** [comment]
@makarukp can you update the PR comment as well? Still says "please do not merge"

**Comment by kv2019i** [comment]
@makarukp @softwarecki @mwasko This causes HDMI tests to fail in SOF CI when we attempt to move to newer Zephyr mainline -> https://github.com/thesofproject/sof/pull/6965

**Comment by makarukp** [comment]
@kv2019i Could you provide any IPC + FW logs for analysis and reproduction?

**Comment by kv2019i** [comment]
@makarukp wrote:
> @kv2019i Could you provide any IPC + FW logs for analysis and reproduction?

https://sof-ci.01.org/sofpr/PR6965/build3542/devicetest/index.html?model=ADLP_RVP_SDW_IPC4ZPH&testcase=check-playback-3times

**Comment by marc-hb** [comment]
Thanks to `sof/west.yml` it's trivial to submit zephyr PRs to SOF CI even **BEFORE**  they are mergedin Zephyr, see recent example in https://github.com/zephyrproject-rtos/zephyr/pull/50136#issuecomment-1405516713

**Comment by marc-hb** [comment]
Could this be reverted for now? This is now blocking zephyr upgrades and testing like:
- thesofproject/sof/pull/6965
- thesofproject/sof/pull/7027

A bit problematic considering Zephyr is now in a pre-release, bug fixing phase.

**Comment by mwasko** [comment]
> Could this be reverted for now? This is now blocking zephyr upgrades and testing like:
> 
> * [[UPDATE ZEPHYR] zephyr: dai: Check error code before xrun report thesofproject/sof#6965](https://github.com/thesofproject/sof/pull/6965)
> * [board: intel_adsp_ace15_mtpm xtensa toolchain upgrade and enable xt-clang thesofproject/sof#7027](https://github.com/thesofproject/sof/pull/7027)
> * [[SKIP CI] sparse: temporarily ignore MTL address errors and add to daily tests thesofproject/sof#6722](https://github.com/thesofproject/sof/pull/6722)
> 
> A bit problematic considering Zephyr is now in a pre-release, bug fixing phase.

@marc-hb we are currently working to fix this issue. In case of no progress in a next few days we will revert changes.

**Comment by makarukp** [comment]
PR in OSF should solve the issue:
https://github.com/thesofproject/sof/pull/7044

**Pull request merged**
