### PR TITLE
dts: bindings: clock: Fix STM32G4 device clk src selection helper definitions

### PR DESCRIPTION
**Pull request by str4t0m**
Some device clock sources selection helpers were not correctly defined for the STM32G4 SOC.

With this commit the definitions are updated to match the desciption in the reference manual RM0453.

Fixes #47062

### CODE REVIEW

**Review by erwango — APPROVED** [review]
Thanks for catching this.
I wonder how this was not caught by tests though.
This was supposed to be covered by `drivers.stm32_clock_configuration.common_device.g4.i2c1_hsi`.
Can you check this test status ?

**Review by FRASTM — APPROVED** [review]
with column alignment

**Comment by str4t0m** [comment]
> This was supposed to be covered by `drivers.stm32_clock_configuration.common_device.g4.i2c1_hsi`.

Yes, executing this test made me aware of the issue. On the current main branch it fails with a timeout.

main: I2C clock selection changes the console uarts clock selction:
```
  *** Booting Zephyr OS build zephyr-v3.1.0-1037-ga1ef368094f7  ***
  Running TESTSUITE test_stm32_common_devices_clocks
  ===================================================================
  START - test_sysclk_freq
  PASS - test_sysclk_freq in 0.1 seconds
  ===================================================================
  START - test_i2c_clk_config
  I2C1 gating clock on枆怘憆憞憆憘怘昘昘怘憞昘怘怘
```

**Comment by erwango** [comment]
> Btw. that test case also fails for nucleo_wl55jc, because the hse is a TCXO and the overlay does not enable the hse-tcxo property. I will include a patch in the next PR.

Thanks for the input. Then we have an issue on our bench which didn't allow to report these failing test cases..
I'll investigate.

**Comment by str4t0m** [comment]
@erwango Should this be backported to the 3.1 release?

**Comment by erwango** [comment]
> Thanks for the input. Then we have an issue on our bench which didn't allow to report these failing test cases.. I'll investigate.

So indeed, our test bench doesn't report this specific kind of issues :/. Fixed now

**Pull request merged**
