### PR TITLE
kernel: timeout: optimize z_timeout_expires()

### PR DESCRIPTION
**Pull request by npitre**
This currently calls `timeout_rem()` then adds back the result of
`elapsed()` to cancel out the subtraction of another `elapsed()` call
within `timeout_rem()`. Better not to make any calls to `elapsed()` in
that case, especially given that `elapsed()` may incur hardware access
overhead through `sys_clock_elapsed()`.

Let's move the `elapsed()` subtraction to the only user of `timeout_rem()`
that needs it and remove its invocation from the `z_timeout_expires()`
path entirely.

### CODE REVIEW

**Review by peter-mitsis — COMMENTED** [review]
I don't think that this is quite correct--or at least it conflicts with documented behavior.

Consider the case when `timeout_rem()` returns 0 because the `timeout` has already expired-- `z_timeout_remaining()` would return a non-zero value which would result in behavior different from what is documented in the routines that call `z_timeout_remaining()` (such as `k_timer_remaining_ticks()`).

That being said, I agree that the unnecessary calls to `elapsed()` should be cleaned up.

**Comment by npitre** [comment]
If documentation and/or the implementation is wrong then this is a 
different issue and should be handled separately. This PR is not 
changing any existing semantics.

**Comment by npitre** [comment]
Oops, I see what you mean. This is not correct.
Fix coming.

**Comment by npitre** [comment]
> If it takes more than 1 tick to traverse the timeout queue to find our _timeout_ entry, then the value we return may show up as negative (for CONFIG_TIMEOUT_64BIT) or a rather large positive (!CONFIG_TIMEOUT_64BIT).

Making `elapsed()` first doesn't guarantee anything. You might be right 
on the tick edge which would still possibly create a negative value. The 
real fix would require clamping the result to a positive value.

Here I just wanted to get rid of the redundant `elapsed()` while 
preserving existing code logic.

**Review by peter-mitsis — APPROVED** [review]
At the very least, your proposed change makes things better and not any worse. Changing the order in which timeout_rem() and elapsed() are called is arguably more opportunistic, outside the scope of the original item and not yet 100% determined if it is even a problem. You have my +1. :)

**Review by cfriedt — APPROVED** [review]
LGTM - a subtle micro-optimization, I would guess.

**Review by andyross — APPROVED** [review]
Seems reasonable.  The general worry with timing code isn't usually that it's technically incorrect (apps should be able to handle time aliasing by one tick anyway, because that's a fundamental thing that can't be prevented), but that we have test code in CI that is more sensitive to timing behavior than the docs/history promised.   And the retry behavior on SMP platforms can often hide tests that get flaky.  Something to watch for once this merges.

**Review by nashif — APPROVED** [review]

**Pull request merged**
