### PR TITLE
bluetooth: controller: Document mem, memq, util

### PR DESCRIPTION
**Pull request by mped-oticon**
Adds documentation-commentary to some infrastructure used by the LL.
It is a long-term effort to better document the LL.

Notably, ticker and mayfly require more documentation; this will be
done later.

### CODE REVIEW

**Comment by cvinayak** [comment]
recheck

**Comment by cvinayak** [comment]
Documentation looks good to me. Will wait for the CI to succeed.

**Review by carlescufi — APPROVED** [review]
Nice job.

**Comment by carlescufi** [comment]
@mped-oticon can you please rebase?

**Comment by mped-oticon** [comment]
> @mped-oticon can you please rebase?

Done

**Pull request merged**
