### PR TITLE
Bluetooth: Audio: Switch to LESC GATT perm bits

### PR DESCRIPTION
**Pull request by kimsekkelund**
Follow-up on PR #46923
Switch from using BT_GATT_PERM_WRITE_ENCRYPT to use
BT_GATT_PERM_WRITE_LESC for applying the 128-bit entropy requirement to
all LE Audio services. Likewise for the READ permissions.

Signed-off-by: Kim Sekkelund <ksek@oticon.com>

### CODE REVIEW

**Comment by Thalley** [comment]
Isn't this also fixed as part of https://github.com/zephyrproject-rtos/zephyr/pull/47600?

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]
This will be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/47600
As discussed here https://github.com/zephyrproject-rtos/zephyr/pull/47600#issuecomment-1192534399, the LE Audio - specific security requirements should be validated in GATT read/write callbacks

**Comment by kimsekkelund** [comment]
Sorry. I didn't see that the permission bits from #46923 is reverted in #47600. So we should put my change at least on hold for now and possibly drop it.

**Comment by Thalley** [comment]
> Sorry. I didn't see that the permission bits from #46923 is reverted in #47600. So we should put my change at least on hold for now and possibly drop it.

I am fine with taking this in first, as it also solves a problem, and the other PR is now quite large and may take a while for complete.

**Review by Thalley — APPROVED** [review]

**Comment by MariuszSkamra** [comment]
> > Sorry. I didn't see that the permission bits from #46923 is reverted in #47600. So we should put my change at least on hold for now and possibly drop it.
> 
> I am fine with taking this in first, as it also solves a problem, and the other PR is now quite large and may take a while for complete.

Here's copy of my response posted here:  https://github.com/zephyrproject-rtos/zephyr/pull/47600#discussion_r934169839

"But wouldn't BT_GATT_PERM_WRITE_LESC exclude OOB method? If I understand correctly, setting BT_GATT_PERM_WRITE_LESC would reject access to attribute at GATT level if not paired with LE Secure Connections."

**Comment by kimsekkelund** [comment]
> Here's copy of my response posted here: [#47600 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/47600#discussion_r934169839)
> 
> "But wouldn't BT_GATT_PERM_WRITE_LESC exclude OOB method? If I understand correctly, setting BT_GATT_PERM_WRITE_LESC would reject access to attribute at GATT level if not paired with LE Secure Connections."

True, my PR does not address the OOB method. It just adds the 'LESC bits to the remaining LE Audio characteristics. For OOB we will have to wait for your changes.

**Comment by kimsekkelund** [comment]
As #47600 has been merged, I think that we should skip my PR.

**Comment by Thalley** [comment]
> As #47600 has been merged, I think that we should skip my PR.

Agreed. The solution from @MariuszSkamra seems to be more complete. Suggest to close this

**Comment by kimsekkelund** [comment]
This change is not relevant any more. #47600 implements a better solution.

**Pull request closed without merging**
