### PR TITLE
soc: nordic: nrf54h: Switch guards for nRF54H20 radiodore

### PR DESCRIPTION
**Pull request by adamkondraciuk**
Replace the symbol `CONFIG_SOC_NRF54H20_CPURAD` with the generic
`NRF_RADIOCORE`.

### CODE REVIEW

**Comment by masz-nordic** [comment]
EngB is not supported in Zephyr anymore, why is this needed?

**Review by gmarull — CHANGES_REQUESTED** [review]
EngB support has been removed

**Comment by adamkondraciuk** [comment]
> EngB support has been removed

description and commit message changed. Which symbol is more appropriate then? `CONFIG_SOC_NRF54H20_CPURAD`, or `NRF_RADIOCORE` ?

**Comment by gmarull** [comment]
> > EngB support has been removed
> 
> description and commit message changed. Which symbol is more appropriate then? `CONFIG_SOC_NRF54H20_CPURAD`, or `NRF_RADIOCORE` ?

in Zephyr code you should use `CONFIG_`.

**Pull request closed without merging**
