### PR TITLE
doc: Update doxygen awesome to v2.3.1

### PR DESCRIPTION
**Pull request by kartben**
Update to latest version of Doxygen awesome bringing a variety of improvements for better dark/light mode handling (ex. for code blocks), better compatibility with recent doxygen versions, etc.

I will probably look at enabling additional extensions at some point, e.g. https://jothepro.github.io/doxygen-awesome-css/md_docs_2extensions.html#extension-copy-button.

**📄 LIVE CI-BUILT DOCUMENTATION: https://builds.zephyrproject.io/zephyr/pr/64508/docs/doxygen/html/**

### CODE REVIEW

**Review by gmarull — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
Do we really want the dark/light switch button next to the search field? It makes it seem like it is associated with the search field form.

**Comment by kartben** [comment]
> Do we really want the dark/light switch button next to the search field? It makes it seem like it is associated with the search field form.

@henrikbrixandersen  You're probably right but this is already how it looks like (and has for many years!) with the current CSS ;)

**Comment by henrikbrixandersen** [comment]
> > Do we really want the dark/light switch button next to the search field? It makes it seem like it is associated with the search field form.
> 
> @henrikbrixandersen You're probably right but this is already how it looks like (and has for many years!) with the current CSS ;)

Not here? The current design renders the light/dark switch at the top of the page as shown here:

image

This PR renders it in the sidebar, next to the search field as shown here:

image

**Comment by kartben** [comment]
@henrikbrixandersen Doxygen pages have their own style :) 
https://docs.zephyrproject.org/latest/doxygen/html/index.html

**Review by henrikbrixandersen — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
