### PR TITLE
usb: bluetooth (hci_usb): do not use ZLP for HCI event transfers

### LINKED ISSUE #20250: hci_usb: scanning crashes controller if a lot of devices are nearby
**Describe the bug**
When enableing scanning in an environment where a lot of advertising devices are present, the controller may crashs after sending a lot of garbage hci events via USB.

This issue will happen sometimes with around 50 devices and regularly with more then 80 devices nearby and almost instantly with ~100.

What have you tried to diagnose or workaround this issue?
Different values for the CONFIG_BT_CTLR_DUP_FILTER_LEN were tested with the same outcome.

**To Reproduce**
The used hardware is a custom board with the nrf52840 connected via USB to the host processor, similar to the nrf52840_pca10056 that should be enough to reproduce the issue.

**Expected behavior**
Regarless of how many devices are nearby, the controller must not crash or send garbage hci events.

**Impact**
showstopper

**btmon output**
The part where the garbage hci events start. The controller sent a lot more until stopping and not responding to more HCI commands.
```
> HCI Event: LE Meta Event (0x3e) plen 30                                     #7674 [hci0] 1241.343725
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Random (0x01)
        Address: 57:4B:CA:5B:7D:59 (Resolvable)
        Data length: 18
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 12 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 1a1e325d6cd2
        RSSI: -77 dBm (0xb3)
> HCI Event: LE Meta Event (0x3e) plen 15                                     #7675 [hci0] 1241.387698
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Random (0x01)
        Address: DD:85:10:97:90:6F (Static)
        Data length: 3
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        RSSI: 62 dBm (0x3e)
@ MGMT Event: Device Found (0x0012) plen 32                                {0x0004} [hci0] 1241.387773
        LE Address: 57:4B:CA:5B:7D:59 (Resolvable)
        RSSI: -77 dBm (0xb3)
        Flags: 0x00000000
        Data length: 18
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 12 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 1a1e325d6cd2
@ MGMT Event: Device Found (0x0012) plen 32                                {0x0003} [hci0] 1241.387773
        LE Address: 57:4B:CA:5B:7D:59 (Resolvable)
        RSSI: -77 dBm (0xb3)
        Flags: 0x00000000
        Data length: 18
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 12 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 1a1e325d6cd2
@ MGMT Event: Device Found (0x0012) plen 32                                {0x0002} [hci0] 1241.387773
        LE Address: 57:4B:CA:5B:7D:59 (Resolvable)
        RSSI: -77 dBm (0xb3)
        Flags: 0x00000000
        Data length: 18
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 12 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 1a1e325d6cd2
@ MGMT Event: Device Found (0x0012) plen 32                                {0x0001} [hci0] 1241.387773
        LE Address: 57:4B:CA:5B:7D:59 (Resolvable)
        RSSI: -77 dBm (0xb3)
        Flags: 0x00000000
        Data length: 18
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 12 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 1a1e325d6cd2
> HCI Event: Unknown (0x2b) plen 2                                            #7676 [hci0] 1241.387710
        01 03                                            ..
> HCI Event: Inquiry Complete (0x01) plen 180                                 #7677 [hci0] 1241.430692
        invalid packet size
        b9 94 ca 74 1a 1f 1e ff 06 00 01 09 20 00 6e 21  ...t........ .n!
        64 9a 34 48 1e ae cd 3b bf 1c 4b 52 7b dc 0e 82  d.4H...;..KR{...
        f0 14 15 af 3f b8 3e 2b 02 01 03 01 c5 84 6c ee  ....?.>+......l.
        eb 1d 1f 1e ff 06 00 01 09 20 00 ad 3d ac a1 3d  ......... ..=..=
        fd 62 a0 f1 b3 a7 e5 8e cc a9 d9 e8 17 04 fe 27  .b.............'
        03 70 ba 3e 2b 02 01 03 01 37 6f 7e ad 25 08 1f  .p.>+....7o~.%..
        1e ff 06 00 01 09 20 02 9c 8b 35 0f 21 ef 00 5c  ...... ...5.!..\
        be b7 17 54 d1 04 94 11 a8 cc f1 a3 61 54 8d b6  ...T........aT..
        3e 28 02 01 03 00 28 77 40 5e 39 28 1c 1b ff 75  >(....(w@^9(...u
        00 42 04 01 80 60 28 39 5e 40 77 28 2a 39 5e 40  .B...`(9^@w(*9^@
        77 27 01 00 00 00 00 00 00 b5 3e 1d 02 01 00 01  w'........>.....
        ff 2c 1f 54                                      .,.T
> HCI Event: Unknown (0xc4) plen 67                                           #7678 [hci0] 1241.616710
        11 02 01 1a 02 0a 0c 0a ff 4c 00 10 05 01 18 4e  .........L.....N
        ae 03 b5 3e 2b 02 01 03 01 7c 75 7c ec 39 1c 1f  ...>+....|u|.9..
        1e ff 06 00 01 09 20 02 a6 83 51 3b 14 c9 a2 81  ...... ...Q;....
        cd 80 80 cc 63 ce 88 51 c8 70 37 d0 a4 43 48 b2  ....c..Q.p7..CH.
        3e 0c 02                                         >..
> HCI Event: Inquiry Complete (0x01) plen 4                                   #7679 [hci0] 1241.616722
        invalid packet size
        01 59 7d 5b                                      .Y}[
> HCI Event: Unknown (0xca) plen 75                                           #7680 [hci0] 1241.788715
        57 00 b3 3e 2b 02 01 03 01 8f d3 2d 10 d4 27 1f  W..>+......-..'.
        1e ff 06 00 01 09 20 00 0e 47 da a9 aa 8c dd 1c  ...... ..G......
        df 45 3a 5b dd 6d 47 57 cb 92 b5 6b aa 10 2c b0  .E:[.mGW...k..,.
        3e 1a 02 01 00 01 76 a0 8b 0e d5 4b 0e 02 01 1a  >.....v....K....
        0a ff 4c 00 10 05 1a 18 8f bd 19                 ..L........
> HCI Event: Unknown (0xd2) plen 62                                           #7681 [hci0] 1242.464788
        0c 02 01 04 01 76 a0 8b 0e d5 4b 00 d3 3e 0c 02  .....v....K..>..
        01 04 01 ff 2c 1f 54 c4 43 00 b4 3e 1a 02 01 00  ....,.T.C..>....
        01 4d aa b7 77 d9 74 0e 02 01 1a 0a ff 4c 00 10  .M..w.t......L..
        05 03 18 45 45 ab b7 3e 1e 02 01 00 01 d4        ...EE..>......
> HCI Event: Physical Link Loss Early Warning (0x43) plen 133                 #7682 [hci0] 1242.708790
        invalid packet size
        6a 39 54 12 02 01 1a 02 0a 0c 0b ff 4c 00 10 06  j9T.........L...
        1a 1e 01 a9 34 3d af 3e 2b 02 01 03 01 45 72 2f  ....4=.>+....Er/
        a8 66 25 1f 1e ff 06 00 01 09 20 02 e9 9a ff 44  .f%....... ....D
        d0 59 be 41 bf 9f 8b 31 4b 9a ce af 9b 7f a6 3d  .Y.A...1K......=
        74 d8 d0 b0 3e 2b 02 01 03 01 3f 67 ad ab 78 1f  t...>+....?g..x.
        1f 1e ff 06 00 01 09 20 02 2a 3a b8 a5 65 33 97  ....... .*:..e3.
        6a 86 b4 59 2f db 7a 15 07 7e 30 4a 6c aa df e3  j..Y/.z..~0Jl...
        b8 3e 2b 02 01 03 01 bc 48 a4 03 f2 36 1f 1e ff  .>+.....H...6...
        06 00 01 09 20                                   ....
> HCI Event: Unknown (0x00) plen 110                                          #7683 [hci0] 1243.023813
        92 59 0a 24 f9 6d c0 95 9d 93 75 e4 70 84 46 78  .Y.$.m....u.p.Fx
        b2 39 27 6e 99 35 b0 3e 0f 02 01 00 01 a9 1e c5  .9'n.5.>........
        5c 30 c8 03 02 01 06 d4 3e 2b 02 01 04 01 a9 1e  \0......>+......
        c5 5c 30 c8 1f 0c 08 50 6f 73 65 69 64 6f 6e 20  .\0....Poseidon
        52 61 11 06 31 01 9b 5f 80 00 00 80 00 10 00 00  Ra..1.._........
        10 00 03 00 d5 3e 2b 02 01 03 01 07 ba f1 06 64  .....>+........d
        10 1f 1e ff 06 00 01 09 20 00 9d 26 44 64        ........ ..&Dd
> ACL Data RX: Handle 3 flags 0x02 dlen 9                                     #7684 [hci0] 1244.228947
      ATT: Handle Value Indication (0x1d) len 4
        Handle: 0x0026
          Data: 0300
< ACL Data TX: Handle 3 flags 0x00 dlen 5                                     #7685 [hci0] 1244.229773
      ATT: Handle Value Confirmation (0x1e) len 0
> ACL Data RX: Handle 3 flags 0x02 dlen 8                                     #7686 [hci0] 1244.767969
      ATT: Handle Value Indication (0x1d) len 3
        Handle: 0x0042
          Data: 00
< ACL Data TX: Handle 3 flags 0x00 dlen 5                                     #7687 [hci0] 1244.769104
      ATT: Handle Value Confirmation (0x1e) len 0
< ACL Data TX: Handle 5 flags 0x00 dlen 8                                     #7688 [hci0] 1244.851114
      ATT: Write Request (0x12) len 3
        Handle: 0x004c
          Data: 4a
< ACL Data TX: Handle 0 flags 0x00 dlen 8                                     #7689 [hci0] 1244.866089
      ATT: Write Request (0x12) len 3
        Handle: 0x0040
          Data: 07
> ACL Data RX: Handle 5 flags 0x02 dlen 5                                     #7690 [hci0] 1244.878981
      ATT: Write Response (0x13) len 0
< ACL Data TX: Handle 5 flags 0x00 dlen 8                                     #7691 [hci0] 1244.884644
      ATT: Write Request (0x12) len 3
        Handle: 0x0040
          Data: 07
> ACL Data RX: Handle 0 flags 0x02 dlen 5                                     #7692 [hci0] 1244.914988
      ATT: Write Response (0x13) len 0
> ACL Data RX: Handle 5 flags 0x02 dlen 5                                     #7693 [hci0] 1244.946983
      ATT: Write Response (0x13) len 0
< ACL Data TX: Handle 3 flags 0x00 dlen 8                                     #7694 [hci0] 1244.978654
      ATT: Write Request (0x12) len 3
        Handle: 0x003d
          Data: 00
> ACL Data RX: Handle 3 flags 0x02 dlen 5                                     #7695 [hci0] 1245.083000
      ATT: Write Response (0x13) len 0
> HCI Event: Number of Completed Packets (0x13) plen 217                      #7696 [hci0] 1246.960149
        Num handles: 97
        Handle: 16021
        Count: 42488
        ee 9d 04 d9 08 d9 d2 b7 2b 88 12 dc af 3e 2b 02  ........+....>+.
        01 03 01 4a 1c b1 c8 0f 24 1f 1e ff 06 00 01 09  ...J....$.......
        20 00 b6 3a 87 93 4d 82 90 be ba 88 61 30 c2 52   ..:..M.....a0.R
        de ab 16 82 42 c0 1c 9c ee b8 3e 0c 02 01 04 01  ....B.....>.....
        08 3e 7b e9 e1 41 00 ba 3e 1d 02 01 00 01 e5 b3  .>{..A..>.......
        5b 45 cd 60 11 02 01 1a 02 0a 0c 0a ff 4c 00 10  [E.`.........L..
        05 03 18 6d 4e 87 b2 3e 0b 06 03 00 12 00 12 00  ...mN..>........
        09 00 ee 02 3e 0c 02 01 04 01 36 32 76 c2 78 74  ....>.....62v.xt
        00 b2 13 05 01 03 00 01 00 13 05 01 03 00 01 00  ................
        13 05 01 05 00 01 00 13 05 01 00 00 01 00 13 05  ................
        01 05 00 01 00 13 05 01 03 00 01 00 3e 1d 02 01  ............>...
        00 01 12 3c 8a 4f 3d 77 11 02 01 1a 02 0a 18 0a  ...<.O=w........
        ff 4c 00 10 05 01 18 26 d5 a9 ae 3e 0c 02 01 04  .L.....&...>....
        01 4d aa b7
```

**Environment:** 
 - OS: Linux, bluez 5.51
 - Toolchain: gnuarmemb 7.3.1 on macos
 - master@78cc4cb6

**Additional context**
Non default configuration for the usb_hci sample
```
CONFIG_BT_MAX_CONN=15
```

### PR DESCRIPTION
**Pull request by jfischer-no**
Do not use ZLP for HCI event transfers.
Linux btusb driver do not relies on ZLP to determine the
end of a transfer. Instead the data is transmitted
continuously and the driver obtains the length of an event
from the HCI Event Packet header.

Fixes: #20250

### CODE REVIEW

**Review by finikorg — APPROVED** [review]
LGTM, ZLP is needed when we do not know size of the packet

**Review by carlescufi — APPROVED** [review]

**Comment by jfischer-phytec-iot** [comment]
@LeBlue FYI

**Review by jhedberg — APPROVED** [review]

**Review by eobalski — COMMENTED** [review]
I am not sure if this actually fixes the problem or makes a workaround.
Could You please share the information/documentation which says that linux btusb does not rely on ZLP?
As I understand HCI events are transferred over interrupt endpoint. I haven't found the information that for those kind of transfers ZLP should be dropped.

**Comment by carlescufi** [comment]
> I am not sure if this actually fixes the problem or makes a workaround.
> Could You please share the information/documentation which says that linux btusb does not rely on ZLP?
> As I understand HCI events are transferred over interrupt endpoint. I haven't found the information that for those kind of transfers ZLP should be dropped.

From the spec:

```
When an interrupt transfer involves more data than can fit in one data payload of the currently established
maximum size, all data payloads are required to be maximum-sized except for the last data payload, which
will contain the remaining data. An interrupt transfer is complete when the endpoint does one of the
following:
• Has transferred exactly the amount of data expected
• Transfers a packet with a payload size less than wMaxPacketSize or transfers a zero-length packet
```

In the case of Bluetooth, we know exactly the amount of data that is expected. Also you can see that this is the case in the source code:
https://elixir.bootlin.com/linux/latest/source/drivers/bluetooth/btusb.c#L590

**Pull request merged**
