### PR TITLE
xtensa: don't build and run the reset handler twice

### PR DESCRIPTION
**Pull request by lyakh**
Currently Zephyr links reset-vector.S twice in xtensa builds: into the bootloader and the main image. It is run at the end of the boot loader execution and immediately after that again in the beginning of the main code. Remove the second copy to reproduce the current SOF behaviour.

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
Perhaps the ESP platforms need this ? If so, best to have some CONFIG option here.

**Comment by lyakh** [comment]
> Perhaps the ESP platforms need this ? If so, best to have some CONFIG option here.

@lgirdwood TBH it's hard to imagine that any platform would need this. I could understand if the builds were at least partially different: when building the boot loader a `BOOTLOADER` macro is defined, but it isn't checked in that file. But sure, we have to check! Would @andyross know or be able to test or whom should we ask? @andrewboie ?

**Comment by dcpleung** [comment]
I think `qemu_xtensa` needs this as there is no bootloader.

**Comment by nashif** [comment]
> I think `qemu_xtensa` needs this as there is no bootloader.

yes, that is what is failing in CI with this change.

**Comment by lyakh** [comment]
> I think `qemu_xtensa` needs this as there is no bootloader.

@dcpleung ok, thanks for the information! But we don't want to disadvantage real hardware configurations for the sake of a testing virtual platform? We could either make this conditional only in qemu builds or we could link reset-vector.S *always* with the main image and not with the bootloader? I tried that too and it worked as well, I only chose this version because that's how it is done in SOF.

**Comment by dcpleung** [comment]
Maybe add a kconfig to select whether to do reset in main image?

**Comment by lyakh** [comment]
> Maybe add a kconfig to select whether to do reset in main image?

@dcpleung you mean to handle a reset? Sure, that's a possibility too. But needlessly running that code twice really doesn't sound like a proper approach to me.

**Comment by dcpleung** [comment]
> > Maybe add a kconfig to select whether to do reset in main image?
> 
> @dcpleung you mean to handle a reset? Sure, that's a possibility too. But needlessly running that code twice really doesn't sound like a proper approach to me.

More like whether to call `_start` or `__start`.

**Comment by lyakh** [comment]
> > > Maybe add a kconfig to select whether to do reset in main image?
> > 
> > 
> > @dcpleung you mean to handle a reset? Sure, that's a possibility too. But needlessly running that code twice really doesn't sound like a proper approach to me.
> 
> More like whether to call `_start` or `__start`.

@dcpleung but this patch also removes reset-vector.S from the maid image, so `__start` isn't available there. So you'd have to build the file conditionally too

**Comment by dcpleung** [comment]
> > > > Maybe add a kconfig to select whether to do reset in main image?
> > > 
> > > 
> > > @dcpleung you mean to handle a reset? Sure, that's a possibility too. But needlessly running that code twice really doesn't sound like a proper approach to me.
> > 
> > 
> > More like whether to call `_start` or `__start`.
> 
> @dcpleung but this patch also removes reset-vector.S from the maid image, so `__start` isn't available there. So you'd have to build the file conditionally too

Yes, it can be achieved by having a kconfig.

**Comment by nashif** [comment]
lets fix this with a Kconfig that will be on for qemu or anyone else needing this.

**Comment by lyakh** [comment]
> lets fix this with a Kconfig that will be on for qemu or anyone else needing this.

@nashif @lgirdwood correct me if I'm wrong: when testing SOF with QEMU we use standard images, built for various hardware architectures. We don't have a Kconfig option for QEMU. Is it different for Zephyr? Do you make special builds for QEMU? I can move that code to the application image proper, that should work for everybody then. The only inconvenience I see is that SOF native builds do the opposite. But I don't see any conflicts there. We use different CMakeLists.txt anyway, so no intersecting. I can push such a version for review.

**Comment by lgirdwood** [comment]
@lyakh yes SOF binaries run on both with the same kconfig/binary but lets follow the Zephyr method here as @nashif has said.

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Pull request merged**
