### PR TITLE
doc: rework footer to be more compact

### PR DESCRIPTION
**Pull request by kartben**
https://builds.zephyrproject.io/zephyr/pr/78043/docs/safety/index.html vs.
https://docs.zephyrproject.org/latest/safety/index.html

There is likely no need for the footer to be so prominently asking folks to report issues with a page based on the number of issues that have been reported in the past year or so.

This change makes the footer less crowded and saves some precious vertical space.

Also made a change so that footer is always at the actual bottom of the screen rather, which makes pages with little text (like the one linked at the beginning of this comment) look better.

Related: similar work to save some space towards the top of the page #78032

### CODE REVIEW

**Comment by pdgendt** [comment]
Maybe keep a simple "Report an issue" link?

**Comment by kartben** [comment]
spotted a small glitch but should be all good now.

**Review by pdgendt — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by kartben** [comment]
Found new layout issues. DNM for now.

**Comment by nashif** [comment]
> Found new layout issues. e.g. [builds.zephyrproject.io/zephyr/pr/78043/docs/kernel/code-relocation.html](https://builds.zephyrproject.io/zephyr/pr/78043/docs/kernel/code-relocation.html)
> DNM for now.

what is the issue, looks fine to me :)

**Comment by kartben** [comment]
> > Found new layout issues. e.g. [builds.zephyrproject.io/zephyr/pr/78043/docs/kernel/code-relocation.html](https://builds.zephyrproject.io/zephyr/pr/78043/docs/kernel/code-relocation.html)
> > DNM for now.
> 
> what is the issue, looks fine to me :)

The long literal string after "An example of such a string..." is not properly wrapping when one has a narrow screen, but this isn't new apparently https://docs.zephyrproject.org/3.6.0/kernel/code-relocation.html so it might be a false alert :)
I was seeing some other issues but that's on a branch where I have additional changes so they might be what broke things.

**Comment by kartben** [comment]
OK so this really was a false alert. The issue highlighted above will probably need to be fixed at some point, but the other more serious glitches I was experiencing were definitely a false alert. Guess I rebased on top of broken main for nothing :)

**Pull request merged**
