### PR TITLE
ARC: boards: hsdk: disable XIP

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
XIP (eXecute In Place) is a method of executing programs directly from long term storage (i.e flash memory). It allows us to avoid copying text it into RAM, saving writable memory for dynamic data and not the static program code.

We don't have such non-volatile memory capable for executing in place on HSDK so we load Zephyr image to DDR memory with debugger each time.

Disable XIP option for HSDK as we don't need it.

### CODE REVIEW

**Review by abrodkin — APPROVED** [review]

**Comment by ruuddw** [comment]
Agree that the way code is loaded on HSDK doesn't need this, it was historically the approach (also in other ARC development boards) to mimic 'flash' on boards where we do not flash images but download and execute directly.

For testing it makes sense to stick to XIP to ensure the data copying from ROM to RAM is handled correctly. But, I believe there is still some work to do for MetaWare and XIP. On ARC without virtual addresses, is the 'ALIGN_WITH_INPUT' necessary? Alternative to disabling XIP here would be to fix the linker-tool-mwdt.h ? Or, would there be no alternative for ALIGN_WITH_INPUT?

**Comment by evgeniy-paltsev** [comment]
> For testing it makes sense to stick to XIP to ensure the data copying from ROM to RAM is handled correctly. 

I agree on the part that it's better to have a configuration with XIP to ensure that it's working. However I'd prefer to test it on some simulation platform (nsim or qemu) so we have more reproducible and stable environment.


PS: probably we can extend number of qemu configurations when the icount patches will be delivered. Here is an example that we have with x86

```
qemu_x86_64_defconfig
qemu_x86_64_nokpti_defconfig
qemu_x86_coverage_defconfig
qemu_x86_nokpti_defconfig
qemu_x86_nommu_defconfig
qemu_x86_nopae_defconfig
qemu_x86_tiny_defconfig
qemu_x86_xip_defconfig
         ^^^
```

**Comment by evgeniy-paltsev** [comment]
We want to have XIP tested on ARC simulation platform, here is enhancement issue for that: #30725

**Review by ruuddw — APPROVED** [review]
Thanks, with #30725 as a reminder for adding an XIP test target (and fixing MWDT support) I'm ok with this change.

**Pull request merged**
