### PR TITLE
boards/xtensa: stop cleaning intermediate binaries

### PR DESCRIPTION
**Pull request by fkokosinski**
This PR removes `CONFIG_CLEANUP_INTERMEDIATE_FILES` y-selection from some Xtensa board configs. Y-selecting this option causes `west spdx` to fail.

### CODE REVIEW

**Comment by marc-hb** [comment]
I never liked CONFIG_CLEANUP_INTERMEDIATE_FILES (I think it should be the default only in CI) and I turned it off in SOF because it breaks incremental builds but an explanation of why `west spdx` fails and how seems required in the commit message.

**Review by andyross — COMMENTED** [review]
Yeah, this doesn't look like a root cause fix to me either, even though the change itself looks fine.   Can we get clarity on what exactly it is that these boards want from having this on by default?  @nashif might know?

**Comment by fkokosinski** [comment]
Hi @marc-hb @andyross. Thanks for a taking a look at this PR!

Here's the error message that we're getting when running `west spdx`:
```
 File "/home/ant/zephyrproject/zephyr/scripts/west_commands/zspdx/walker.py", line 471, in collectTargetDependencies
    rd.ownerFileAbspath = pkg.targetBuildFile.abspath
AttributeError: 'NoneType' object has no attribute 'abspath'
```

If I understand this correctly, `cfgTarget.target.artifacts` is a list of artifact files. These artifacts are removed when `CONFIG_CLEANUP_INTERMEDIATE_FILES` is y-selected.

 If these files are removed, then `addBuildFile` doesn't add them to `pkg`, so `pkg.targetBuildFile` is `None`. There are some checks in https://github.com/zephyrproject-rtos/zephyr/blob/e47fc45c4d4ed3c04d6a147e10d2a52630b7f0d7/scripts/west_commands/zspdx/walker.py#L446-L466 to skip iterations, but they don't cover this situation, resulting in the error above.

**Comment by marc-hb** [comment]
Thanks @fkokosinski ! I don't understand the details but your last comment looks like a very good commit message to me.

**Comment by marc-hb** [comment]
>  your last comment looks like a very good commit message to me.

Actually, that commit message would fit better in a new,
different commit with this doc change:

```diff
--- a/Kconfig.zephyr
+++ b/Kconfig.zephyr
@@ -521,7 +521,9 @@ config CLEANUP_INTERMEDIATE_FILES
        bool "Remove all intermediate files"
        help
          Delete intermediate files to save space and cleanup clutter resulting
-         from the build process.
+         from the build process. Note this breaks incremental builds,
+         west spdx and maybe others.
+
```

Then the commit for your `boards/xtensa` changes could be just "see why in previous commit" :-)

**Comment by fkokosinski** [comment]
@marc-hb thanks for your suggestions! I've expanded the description of the `CLEANUP_INTERMEDIATE_FILES` symbol and expanded commit msgs. PTAL.

**Review by andyross — APPROVED** [review]
OK, the SPDX generation looks like it needs the intermediate files by definition, so indeed it's not compatible with this kconfig.  I'll throw a +1 on this, as I think we all agree this shouldn't be a default option.

But I give at least even odds there's some weird edge that requires this on the affected platforms.  @nashif @dbaluta @iuliana-prodan ?  One wild guess is that I know the xtensa linkage tricks regarding the cache/uncache mappings used to generate extremely large looking (~512MB, but actually sparse in the filesystem) early stage link binaries.  I'm pretty sure that got fixed with the advent of KERNEL_COHERENCE, so maybe this is an echo or an unfixed edge?

**Review by marc-hb — COMMENTED** [review]
> due to reasons described in https://github.com/antmicro/zephyr/commit/3d6703820be017962db14f31b654729fd9ee55c2.

You unfortunately can't do this in this git repo / project because the SHA1 will change when this PR is rebased and merged.

Alternatives:
- "described in the most recent Kconfig.zephyr commit"
- split this PR into 2 PRs, one per commit :-(

> But I give at least even odds there's some weird edge that requires this on the affected platforms

Do you mean "require" from a pure disk space CI standpoint or from (the horror) a Zephyr functional standpoint?

LGTM but while this admittedly hackish feature unsurprisingly breaks some eggs, it was added for a reason and some CI(s) probably need some alternative way to turn it back on from the command line thanks to some new twister --option or some overlay...

**Comment by fkokosinski** [comment]
> You unfortunately can't do this in this git repo / project because the SHA1 will change when this PR is rebased and merged.

Thanks for catching that! I've decided to just copy part of the reasoning from the first commit to the second one. I suppose we can't be _too verbose_, and it'll be easier for someone in the future to get why this change was introduced. Let me know if it works for you.

**Comment by andyross** [comment]
> Do you mean "require" from a pure disk space CI standpoint or from (the horror) a Zephyr functional standpoint?

Given my pet theory: more like an intermediate software standpoint.  Something that wants to make a tarball containing the (hypothetical) giant sparse file and produces an unreasonable result, something like that.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
do not remember the exact reason why I added this, so lets remove this from the defconfig and see what happens, it can't be that bad....

**Pull request merged**
