### PR TITLE
Log module fixes

### PR DESCRIPTION
**Pull request by mbolivar**
A couple of fixes related to logger modules, one for modules which span multiple files, and another for the initial settings of runtime filters.

### CODE REVIEW

**Comment by mbolivar** [comment]
closing until tomorrow when I have time to fix the unit tests, will reopen

**Comment by mbolivar** [comment]
@nordic-krch sanitycheck is passing for me locally now, would you mind having a look?

**Comment by mbolivar** [comment]
recheck

**Comment by nordic-krch** [comment]
lgtm (with minor 'the Logger' question).

**Comment by mbolivar** [comment]
> lgtm (with minor 'the Logger' question).

Thanks for the review!

Sorry, but what was the question? Was it about the use of the phrase "the Logger core" in the docstring for  LOG_MODULE_DECLARE? If so, that was done for consistency with the rest of the documentation, but I'm happy to change it.

**Comment by nordic-krch** [comment]
My question was about using "the Logger" instead of "the logger". I've used "the logger" in headers so far but if zephyr approach is to use capital letters for subsystem names then im ok to change it.

**Comment by mbolivar** [comment]
> My question was about using "the Logger" instead of "the logger". I've used "the logger" in headers so far but if zephyr approach is to use capital letters for subsystem names then im ok to change it.

I've changed it to match your pattern.

**Review by dbkinder — APPROVED** [review]
doc changes look ok, thanks.

**Comment by mbolivar** [comment]
recheck

**Review by nordic-krch — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
