### PR TITLE
[RFC][DO NOT MERGE]Move dts board

### LINKED ISSUE #3587: Move board related device tree files where the board is defined
**_Reported by Anas Nashif:_**

right now we put all device tree files for all boards into dts/<arch>/, this means that when adding a board we need to manage it in 2 different places. We should look into maintaining board dts files in the board directory, optionally move the common files for an SoC and architectures to where the Soc is maintained, under arch/<arch>/soc/...

This would enable us to maintain everything related to a board in one place and would make it easy for us to handle boards as drop-ins, i.e. maintain them out of tree as git submodules or through simple references.

(Imported from Jira ZEP-2148)

### PR DESCRIPTION
**Pull request by galak**
look at moving board.dts file into the board dir to make board dirs more standalone.

Fixes #3587

### CODE REVIEW

**Comment by galak** [comment]
@nashif, @agross-linaro take a look at the change to boards/arm/frdm_k64f/Makefile and what you think of that.

**Comment by carlescufi** [comment]
I like the idea. I don't recall why, on ARM boards the number of priority bits are in those files, should really be part of the SoC config shouldn't it?

**Comment by SebastianBoe** [comment]
> @nashif, @agross-linaro take a look at the change to boards/arm/frdm_k64f/Makefile and what you think of that. We need to have 2 passes at boards/$(ARCH)/$(BOARD_NAME) one for dts build which has to be early since we use it for config.h and second for normal .c file building of any board code. So this is what I could come up with.

FYI; the cmake branch determines what dts file to use differently. Instead of requiring build scripts
to set the dts source, it is assumed that the dts source file follows the naming convention:
dts/$(ARCH)/$(BOARD_NAME).dts_compiled

**Comment by galak** [comment]
@SebastianBoe I assume changing cmake from dts/$(ARCH)/$(BOARD_NAME)/.dts_compiled to board/$(ARCH)/$(BOARD)/$(BOARD_NAME) will be trivial.

**Comment by galak** [comment]
@carlescufi which files are you talking about w/regards to PRIO bits?

**Comment by carlescufi** [comment]
@galak the .fixup files: https://github.com/zephyrproject-rtos/zephyr/blob/master/dts/arm/nrf52_pca10040.fixup#L1

**Comment by nashif** [comment]
> @SebastianBoe I assume changing cmake from dts/$(ARCH)/$(BOARD_NAME)/.dts_compiled to board/$(ARCH)/$(BOARD)/$(BOARD_NAME) will be trivial.

Then maybe we should just do this after the cmake merge?

**Comment by erwango** [comment]
While I understand the idea of having boards dir standalone (and agree this would be nice), I wonder how this could fit with using a generic device tree database, that would be out of Linux tree.
This would require either:
-get generic device tree using the same approach
-remove boards from generic device tree database (but we lose 50% of the benefit of it)
-define generic to zephyr structure tree adaptation (rules and tools)
-acknowledge divergence from generic device tree data base

**Comment by MaureenHelm** [comment]
I don't have a strong opinion on this, but it raises the question of how far we want to go supporting things out of tree. Would/should we support out of tree SoCs or drivers?

**Comment by nashif** [comment]
> I don't have a strong opinion on this, but it raises the question of how far we want to go supporting things out of tree. Would/should we support out of tree SoCs or drivers?

I would say yes, any product development based on Zephyr should be feasible without having to checkin code into upstream Zephyr, this does not mean we have to move everything around and restructure our tree, but the build system should support pointing to alternate locations for DTS related files and not force one single location inside the zephyr tree.
In general terms, the model we need to be able to support is someone using the Zephyr kernel (scheduler and architecture interfaces) only and maintaining everything else on their own, this is a very common use case.

**Comment by nashif** [comment]
actually, related to that but orthogonal , I am proposing to move SoCs to the top level, see #4438

**Review by agross-oss — COMMENTED** [review]
I'd prefer to keep it centralized, but I don't have any strong feelings about it.  I do think we need to support the ability to search other directories (external).  But that could be a enhancement done at a later time.

**Comment by galak** [comment]
@agross-linaro any particular reason to keep it central for the board dts?  I agree for SoC related dtsi files.

**Comment by agross-linaro** [comment]
just that it spreads it around the system.  I suppose keeping the board specific stuff in the board directory does make things consistent.

**Comment by nashif** [comment]
this was moved on top of cmake, so closing

**Pull request closed without merging**
