### PR TITLE
net/ip: Rename Kconfig symbols `NET_BUF_*` to `NET_PKT_BUF_*`

### PR DESCRIPTION
**Pull request by chrta**
This fixes a naming inconsistencies where Kconfig symbols in net/ip should not be prefixed with `NET_BUF_`.

### CODE REVIEW

**Comment by rlubos** [comment]
I think that this change should be documented in https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/releases/release-notes-3.3.rst#api-changes.

I also wonder @carlescufi @nashif , is there a deprecation procedure for such a case, i. e. Kconfig symbol renaming? I saw there is a `DEPRECATED` Kconfig symbol, but it seems to be intended for use with boolean options.

**Comment by rlubos** [comment]
Deprecating Kconfig integers seems to be a bit tricky if we want to keep both symbols functional. For example `settings_file.c` handled this the following way: 
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/settings/src/settings_file.c#L22
however, I don't think this approach is applicable for the symbols modified in this PR given that there's no single switch to choose between deprecated/non-deprecated symbols, plus the fact that the symbols are used extensively across the code base.

I was thinking, perhaps the old deprecated symbol could default to 0 or a negative value, and then if set to something else, the new symbol could default to the deprecated one (so that if someone still uses the old config symbols, the new one gets the correct value)? Something like:
```
config NET_BUF_TX_COUNT
	int "How many network buffers are allocated for sending data (DEPRECATED)"
	default 0
	help
	  This option is deprecated, please use NET_PKT_BUF_TX_COUNT instead.

config NET_PKT_BUF_TX_COUNT
	int "How many network buffers are allocated for sending data"
	default NET_BUF_TX_COUNT if NET_BUF_TX_COUNT > 0
	default 36 if NET_L2_ETHERNET
	default 16
	help
	  Each data buffer will occupy CONFIG_NET_PKT_BUF_DATA_SIZE + smallish
	  header (sizeof(struct net_buf)) amount of data.
```
Plus a compile-time warning in `net_pkt.c` if depreacated symbol is used:
```
#if CONFIG_NET_BUF_TX_COUNT > 0
#warning "NET_BUF_TX_COUNT option is deprecated, please use NET_PKT_BUF_TX_COUNT instead."
#endif
```

Every other deprecated option would need to be handled in a similar way. @carlescufi @tejlmand Do you think this approach would be accepted?

**Comment by galak** [comment]
This feels like it qualifies as a tree-wide change.

**Comment by jhedberg** [comment]
> This feels like it qualifies as a tree-wide change.

@galak what are the implications of such a categorisation? Note that this is strictly about renaming IP stack Kconfig definitions in `subsys/net/ip/Kconfig` which should never have had a `NET_BUF_*` prefix. E.g. the net_buf and Bluetooth subsystems are not affected (except in the case of the latter where it interfaces with the IP stack).

@chrta could you rebase? There seems to be a few conflicts.

**Comment by galak** [comment]
Please take this through the tree-wide PR process and bring it up in the arch-review meeting.  Work with @carlescufi to put it on the agenda for arch-review.

**Comment by chrta** [comment]
I will not have any time working on this, so i am closing this pr. Anyone who is interested in this can pick this up and continue from here...

**Pull request closed without merging**
