### PR TITLE
nRF J-Link debug support

### PR DESCRIPTION
**Pull request by carlescufi**

### CODE REVIEW

**Review by mbolivar — APPROVED** [review]

**Comment by mbolivar** [comment]
@mhelm, any issues with this on your boards?

**Comment by durub** [comment]
Working great here on nRF52832. Thanks!

**Review by SebastianBoe — CHANGES_REQUESTED** [review]

**Comment by carlescufi** [comment]
@SebastianBoe agreed, fixed.

**Review by MaureenHelm — APPROVED** [review]
> @mhelm, any issues with this on your boards?

LGTM. Tested on frdm_k64f and mimxrt1050_evk

**Review by SebastianBoe — APPROVED** [review]

**Pull request merged**
