### PR TITLE
Update intel_adsp integration scripting

### PR DESCRIPTION
**Pull request by andyross**
These are the current versions of everything I'm using, along with a patch that actually removes the legacy stuff.  Not for merge during 2.6, but I should have these here for others to reference.

### CODE REVIEW

**Review by lyakh — CHANGES_REQUESTED** [review]
the new logger works well on CNL after you add the respective PCI ID to the list. So I think we should definitely at least add all missing PCI IDs to the list before removing old scripts?

**Comment by andyross** [comment]
Sure.  What's the VID/DID of your device?  Note that there's a slightly larger list of IDs in the cavs-fw.py script which I found in (some version of) the kernel driver, maybe I should suck those in.  Or even unify both scripts to a single tool...

Note that this isn't intended to merge right now (we absolutely don't delete tools after feature freeze!), this is here so others can track what I'm using locally.  Nonetheless it's time to start pruning out variant versions of stuff and picking winners.

**Comment by lyakh** [comment]
>  What's the VID/DID of your device?

my specific one is 8086:9dc8 but yes, let's get at least some reasonable initial list in, then we can add any missing ones.

**Comment by marc-hb** [comment]
I gave the `cavs-fw.py` version at commit 27773fd03070674 a good try on my UP2 system.

1. If the SOF kernel driver has never ever been loaded (`/etc/modprobe.d/ blacklist`), then `cavs-fw.py`  hangs the first time in:
```
  while (dsp.ADSPCS & 0x1000000) == 0: pass
```
After a first Ctrl-C, it then fails with a 100% consistent:
```
  Load failed?  FW_STATUS = 0x80000007
```


2. If the SOF kernel driver has been loaded and unloaded once, then `cavs-fw.py` hangs every time in:
```
while (dsp.SRAM_FW_STATUS >> 24) != 5: pass
```
A reboot + SOF driver blacklist gets back to "fresh from boot" situation 1.


The above is very consistent so there is no doubt that unloading the SOF kernel driver does NOT gets back to a "fresh from boot" situation. @lgirdwood , @plbossart, others, any clue? I've been using the modprobe scripts at https://github.com/thesofproject/sof-test/tree/c08bcadd717ed7188/tools/kmod

The exact same `sof-apl.ri` loads and runs and reloads perfectly fine with the kernel driver as many times as desired, `adsplogtool.py` showing expected logs every time.

I never tried the SOF diagnostic driver yet.

While I did not test it as much, I believe the current `cavs-fw.py` (without this PR) behaves the same.

**Comment by andyross** [comment]
Hm.  It's very reliable for me.  What BIOS version do you have on your up squared?  I guess it's possible that the CSME might end up with state that can confound things.

**Comment by marc-hb** [comment]
```
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.
Table at 0x79EF6000.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
        Vendor: American Megatrends Inc.
        Version: UPA1AM40
        Release Date: 08/06/2018
        Address: 0xF0000
        Runtime Size: 64 kB
        ROM Size: 6656 kB

        BIOS Revision: 5.12

Handle 0x0001, DMI type 1, 27 bytes
System Information
        Manufacturer: AAEON
        Product Name: UP-APL01
        Version: V1.0
```

These match what I found in UEFI menus.

**Review by marc-hb — CHANGES_REQUESTED** [review]
The new `adsplog.py` is great because it supports polling, buffer wraps, race conditions and what not. I use it all the time. However I'm working on logging itself right now and I have bugs - either bugs I introduced myself or bugs that were there already. For instance right now I have nothing valid in slot 0, 1 and 2 and I have two slots with ID number 33. In such a buggy situation the older `logtool.py` shows me as much (garbage) as it can which is very useful whereas the newer `adsplog.py` prints "ADSP Reset" in a loop and nothing else until the buffer wraps and something valid is found in slot 0. I had a look at the `adsplog.py` code to see if I could make it more robust but I found that its smarts seem to very strongly depend on the correctness of the log.

So for that reason and the "transition period" reason mentioned above I  think removing `logtool.py` is at least premature. I also heard that it may be currently used in some CI somewhere.

**Comment by kv2019i** [comment]
@andyross wrote:
> Sure. What's the VID/DID of your device? Note that there's a slightly larger list of IDs in the cavs-fw.py script which I found in (some version of) the kernel driver, maybe I should suck those in. Or even unify both scripts to a single tool...

https://github.com/zephyrproject-rtos/zephyr/pull/35298
Is probably better approach. Same could work for the loader as well.

**Pull request closed without merging**
