### PR TITLE
subsys: bluetooth: host: Add a user data pointer in struct bt_conn

### PR DESCRIPTION
**Pull request by kimsekkelund**
Add user_data pointer to struct bt_conn.
Define two functions to set and get the user_data pointer related to a
connection; bt_conn_set_user_data() and bt_conn_get_user_data().

An application which supports several simultaneous Bluetooth
connections and needs to maintain some state information related
to each connection does not have a simple way to link that state
information to the particular connection.

One way for the application to link the application data to the bt_conn
structure is to loop over all known connections and search for a match
with the bt_conn-pointer which is passed to the callback function.
This method will become CPU-inefficient if there are many callback
activations during the connection.

Therefore we propose to add a user_data pointer in the bt_conn
structure. The memory which the user_data pointer points at
is "owned" by the application and not touched by the stack.
To set and read the pointer, two functions are added to conn.c,
bt_conn_set_user_data() and bt_conn_get_user_data().
The application may choose to make user_data point to one of it's data
structures upon establishment of the connection through
bt_conn_set_user_data().
All callback functions which has the bt_conn pointer as parameter will
be able to access the application specific user_data through the
returned pointer from bt_conn_get_user_data().

Signed-off-by: Kim Sekkelund <ksek@oticon.com>

### CODE REVIEW

**Review by jhedberg — CHANGES_REQUESTED** [review]
I understand the reasoning behind wanting this, but it's not going to scale - there can be multiple profiles & protocols running on top of a bt_conn and you'd just get race conditions & conflicts if more than one tried to associate their own data with the bt_conn. A more workable (though admittedly less elegant) solution is to define your own array of custom data with CONFIG_BT_MAX_CONN entries and associate each array element with a bt_conn.

**Comment by jhedberg** [comment]
Btw, we have an internal `bt_conn_get_id()` API which eliminates the need to do look-ups of the right context (sorry, missed this detail of the PR description initially). We should probably look for a way to make it public - the main reason it's not is that it's easily confused with the local identity (it's possible to have multiple ones). Perhaps naming `id` to `index` might make it clearer that it returns an array index that can directly be used on an array with CONFIG_BT_MAX_CONN elements.

**Comment by jhedberg** [comment]
FWIW, currently the bt_conn_get_id() is exposed through subsys/bluetooth/host/conn_internal.h. It'd need to be moved (along with the renaming) to include/bluetooth/conn.h

**Comment by jhedberg** [comment]
I'd also like to add that one other reason this API hasn't been made public is that it then locks us into an implementation where the bt_conn objects are internally stored in a single array, i.e. we couldn't internally transition to, say, heap-allocated objects since then the concept of array index goes away.

**Comment by jhedberg** [comment]
Example `bt_conn_get_id()` usage:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/gatt.c#L290-296

**Comment by kimsekkelund** [comment]
@jhedberg, thanks for your comments. We currently use the approach that you mentioned in the first comment which is as you say less elegant. 
If bt_conn_get_id() will be exposed in conn.h it would be just as fine for us, and we would use that as table-index for the connection. All we need is to link the bt_conn to the application's state data in a simple and efficient way.
I understand the concerns of locking the design to be array based by exposing the bt_conn_get_id().

**Pull request closed without merging**
