### PR TITLE
Bluetooth: hci_raw: Fix number of TX buffers

### PR DESCRIPTION
**Pull request by Vudentz**
The numbers should have been the sum of HCI commands count and ACL TX
buffers but instead the buffer size was used which makes the pool holds
substatially more buffer than necessary.

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by cvinayak — DISMISSED** [review]
Note: on nrf51dk_nrf51422, ram use 19520 (this PR cherry-picked over 4b622af) - 19240 (05f0816) = 280 byte increase.

Can a 280 byte increase in 4b622af justified?

`#define BT_BUF_TX_SIZE MAX(BT_BUF_RX_SIZE, BT_BUF_ACL_SIZE)`

The above change makes host allocate more than a controller ACL size of 27 byte payloads.

We can decide to fix it in subsequent PR.

**Review by joerchan — APPROVED** [review]

**Comment by joerchan** [comment]
> The above change makes host allocate more than a controller ACL size of 27 byte payloads.
> 
> We can decide to fix it in subsequent PR.

It looks like this could be fixed by splitting the `hci_tx_pool` into a `hci_cmd_tx_pool` and a `hci_acl_tx_pool`. The order of sending should be maintained by the `tx_queue`

@Vudentz Is there any reason that we cannot split the `hci_tx_pool`? Or maybe under certain configurations for the USB H4 mode?
@cvinayak In any case I think that should be a different PR.

**Comment by Vudentz** [comment]
> > The above change makes host allocate more than a controller ACL size of 27 byte payloads.
> > We can decide to fix it in subsequent PR.
> 
> It looks like this could be fixed by splitting the `hci_tx_pool` into a `hci_cmd_tx_pool` and a `hci_acl_tx_pool`. The order of sending should be maintained by the `tx_queue`
> 
> @Vudentz Is there any reason that we cannot split the `hci_tx_pool`? Or maybe under certain configurations for the USB H4 mode?
> @cvinayak In any case I think that should be a different PR.

There is no specific reason not to have it split, I thought it would be simpler to implement using the same pool bit given their difference in size that end up adding extra bytes.

**Comment by Vudentz** [comment]
@cvinayak @joerchan Done, there should now use dedicated pools for ACL and CMD with their respective sizes and buffer count.

**Comment by joerchan** [comment]
@Vudentz Thanks. LGTM

**Comment by joerchan** [comment]
@Vudentz There appears to be naming conflicts with EDTT HCI test (edtt_ble_test_app/hci_test_app/src/main.c).

**Comment by Vudentz** [comment]
> @Vudentz There appears to be naming conflicts with EDTT HCI test (edtt_ble_test_app/hci_test_app/src/main.c).

Actually since EDTT is using hci_raw it should be managing its own buffers pool either so I guess it is just a matter of converting that to use bt_buf_get_tx.

**Comment by Vudentz** [comment]
> > @Vudentz There appears to be naming conflicts with EDTT HCI test (edtt_ble_test_app/hci_test_app/src/main.c).
> 
> Actually since EDTT is using hci_raw it should be managing its own buffers pool either so I guess it is just a matter of converting that to use bt_buf_get_tx.

Done, in fact we could replace the other pools as well and just use bt_buf_get_rx but there seems to be some timestamping going on, which is actually pretty weird since the likes o monitors, etc, wont be able to decode this properly and they already do their own time stamping.

**Comment by wopu-ot** [comment]
> Done, in fact we could replace the other pools as well and just use bt_buf_get_rx but there seems to be some timestamping going on, which is actually pretty weird since the likes o monitors, etc, wont be able to decode this properly and they already do their own time stamping.

The timestamps that are added by the EDTT HCI app are used in some EDTT tests. The packets go to the Python side of EDTT and don't pass through a host, so there is no need to conform to a specific format.

**Review by heri-developer — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Comment by jhedberg** [comment]
@cvinayak your "request changes" is blocking merging this. Could you take another look?

**Comment by Vudentz** [comment]
> > Done, in fact we could replace the other pools as well and just use bt_buf_get_rx but there seems to be some timestamping going on, which is actually pretty weird since the likes o monitors, etc, wont be able to decode this properly and they already do their own time stamping.
> 
> The timestamps that are added by the EDTT HCI app are used in some EDTT tests. The packets go to the Python side of EDTT and don't pass through a host, so there is no need to conform to a specific format.

Interesting to know, that said I suppose you could timestamp on the Python side instead, since that anyway is using uptime instead of a proper wall timer, anyway this can be changed later if is deemed necessary.

**Comment by Vudentz** [comment]
@jhedberg  looks like we have all the approvals necessary to merge this one.

**Review by wopu-ot — APPROVED** [review]

**Pull request merged**
