### PR TITLE
drivers: i2c: microchip: I2C reset fix

### PR DESCRIPTION
**Pull request by Manimaran-A**
Updated the code to to invoke reset using PCR block z_mchp_xec_pcr_periph_reset()  instead of resetting using I2C Configuration register

### CODE REVIEW

**Comment by cloudflare-wangler** [comment]
> Updated the code to to invoke reset using PCR block z_mchp_xec_pcr_periph_reset()  instead of resetting using I2C Configuration register

**Comment by jjdalynh** [comment]
if anyone's interested, i wrote up a small reset driver that would fit nicely with this and be more in line with other SoCs with IP reset blocks.  I'll include a usage example with this I2C driver.

**Review by rgundi — APPROVED** [review]
LGTM

**Review by jvasanth1 — APPROVED** [review]

**Comment by jvasanth1** [comment]
@albertofloyd can you help to approve?

**Review by teburd — APPROVED** [review]

**Pull request merged**
