### PR TITLE
xtensa: remove legacy arch implementation

### LINKED ISSUE #18138: xtensa arch has two different implementations
Core xtensa code has two implementations present, the old implementation contributed by Cadence and the rewrite done by @andyross 

We never sealed the deal on this, there's lots of conditional compilation for CONFIG_XTENSA_ASM2 in arch/xtensa

Purge the old xtensa arch code, have everything use the new code, remove old board targets where it doesn't work.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
We re-wrote the xtensa arch code, but never got around
to purging the old implementation.

Removed those boards which hadn't been moved to the new
arch code. These were all xt-sim simulator targets and not
real hardware.

Fixes: #18138

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by dcpleung** [comment]
If you remove `irq_manage.c`, dynamic interrupts won't work. @andyross might know whether this works with the ASM2 code.

**Comment by andrewboie** [comment]
@dcpleung I might have messed this up. But it looks like irq_manage.c is only compiled when ASM2 is disabled. So if we have dynamic IRQs with ASM2, that file isn't needed.

gen_sw_isr_table.py automates the creation of both the vector and sw ISR dispatch tables so maybe it Just Works? dynamic IRQs with that mechanism is just a runtime write to the sw ISR table.

**Comment by dcpleung** [comment]
> @dcpleung I might have messed this up. But it looks like irq_manage.c is only compiled when ASM2 is disabled. So if we have dynamic IRQs with ASM2, that file isn't needed.
> 
> gen_sw_isr_table.py automates the creation of both the vector and sw ISR dispatch tables so maybe it Just Works? dynamic IRQs with that mechanism is just a runtime write to the sw ISR table.

Looks like dynamic interrupt has never been tested with ASM2, as `irq_manage.c` was never included. So I think that `irq_manage.c` can be restored and added to source to compile.

**Review by dbkinder — APPROVED** [review]
doc changes LGTM

**Comment by andrewboie** [comment]
> Looks like dynamic interrupt has never been tested with ASM2, as irq_manage.c was never included. So I think that irq_manage.c can be restored and added to source to compile.

No it's not that simple, there is no z_isr_install() implementation.

I think we should just file a bug on this.

**Comment by andyross** [comment]
FWIW: asm2 just uses the generated sw_isr_table under the hood.  We could provide a portable irq_connect_dynamic() implementation on top of that and get it out of the (xtensa) arch layer entirely.

**Review by andyross — APPROVED** [review]
(Alternatively we could just copy that code over into one of the remaining files -- it's super short.)

Regardless I can't see anything wrong here.  It looks great to me.

**Comment by dcpleung** [comment]
Oh? `z_isr_install()` is in `arch/common/sw_isr_common.c` in my tree.

**Comment by andyross** [comment]
Right, it's just the wrapper that provides irq_connect_dynamic() that needs to be copied currently.  I'm just saying replace that with a "ARCH_USES_SW_ISR_TABLE" or whatnot.  Don't much care here.  Dropping support for dynamic IRQs isn't that big a deal, we can fix it later.

**Comment by andrewboie** [comment]
> Dropping support for dynamic IRQs isn't that big a deal, we can fix it later.

This never worked with ASM2 to begin with, we aren't "dropping" anything

**Comment by andyross** [comment]
Did it not?  It was supposed to, anyway.  The irq connect code wasn't really part of asm2, which just used what was there.

**Comment by andrewboie** [comment]
@andyross it never worked. The code was not built. and we are not enforcing a minimum set of functionality for arch ports. I keep finding surprises in x86_64, xtensa, ARMv8, etc. I opened #18273

**Pull request merged**
