### PR TITLE
samples: board: 96b_argonkey: remove led blinking

### PR DESCRIPTION
**Pull request by avisconti**
The LED part is taking too much time. Let's skip the
led blinking part.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Comment by avisconti** [comment]
@galak 
This PR is affecting the ArgonKey sample only.

**Comment by galak** [comment]
Just curious what you mean by it takes too much time, why is that an issue?

**Comment by avisconti** [comment]
@galak 
OK, let's be honest. For some reason the LP3943 driver when doing the 'led blinking' operation is not operating correctly. The issue seems to be inside the lp3943_set_dim_states() routine, where a LP3943 register gets updated. It seems that the issue showed up after  committing the cc4191666b (i2c: stm32: check messages before starting transmission), but I think that this commit just revealed some weaknesses already present somewhere. Actually I do not have much time to dedicate to this issue, but the Argonkey BSP is now broken and I wanted to quickly fix it. On the other hands would be nice to report the issue to the zephyr community, but I'm not sure exactly who to report the issue to, as it is not clear to me what is happening. Apparently the issue seems to be related to some weaknesses into the STM32 i2c driver.

**Comment by avisconti** [comment]
@galak 
I also noticed similar issues in the past when using the vl53l0x driver. At that time I noticed that the system stuck during i2c operations. Currently the driver seems to work fine. I also discussed the issue with @erwango, but he didn't have any clue and never experienced same issue. So, my proposal is to fix the ArgonKey BSP removing the 'blink led' part and to open a new PR (I can do that) with the intention to debug this issue.

**Comment by avisconti** [comment]
@galak 
Any comment here?

**Comment by galak** [comment]
> @galak
> Any comment here?

Do we have an issue opened up for the problem you described.  If so reference here (if not open one) and than I will approve and merge.

**Comment by avisconti** [comment]
@galak 
I just opened the issue #8915 
I may dedicate some time later on, or if someone is able to replicate it somehow can start to debug it.

**Comment by avisconti** [comment]
@galak 
Please do not forget this issue

**Comment by avisconti** [comment]
@galak 
Can you approve this PR? 
I will work with @erwango to debug the I2C issue

**Review by galak — APPROVED** [review]

**Pull request merged**
