### PR TITLE
genrest: Generate documentation and links for choices

### PR DESCRIPTION
**Pull request by ulfalizer**
Until now, choices have kinda been a black box in the Kconfig reference, and
hid the dependencies of choice symbols (because choice symbols depend directly
on the choice rather than on whatever the choice `depends on`).

Generate separate information pages for choices and turn `<choice>` dependencies
into links.

One complication is that choices (usually) don't have names. Use the index of
each choice in the Kconfig files (first choice seen = choice 0, then choice 1,
etc.) instead to identify each choice.

Choice reference pages include the same information as symbol reference pages
(minus some things that don't apply for choices), and also list the choice
symbols contained in the choice.

### CODE REVIEW

**Comment by ulfalizer** [comment]
CC @dbkinder @carlescufi @SebastianBoe

**Comment by dbkinder** [comment]
Looking at the output, while the filenames can be ``choice_40`` it would be nicer looking if the top symbol title was something more meaningful than ``choice_40``.  Maybe instead, have the title be ``choice: Quark SE Selection``  (derived from the prompt string of the choice).  It doesn't have to be unique since it's only displayed:

choice_40

**Comment by ulfalizer** [comment]
@dbkinder 
Yeah, looks confusing. I wasn't sure how to display a different string for the `.. option:: choice_x`, which I think is what generates the cross-reference target.

Here's the RST for that page:

```rst
:orphan:

.. title:: Choice

.. option:: choice_40

*Quark SE Selection*

Type: ``bool``

Direct dependencies
===================

...
```

Any ideas?

**Comment by dbkinder** [comment]
Alas, to fix this (use a better name) you'd need to use something other than the `` .. option`` directive and ``:option:`` role to link to it.    I manually edited things and this works and looks really close to what you're reST file's output looks like:

In the choice_40.rst (for example), instead of using the ``.. option`` directive use a label and a ``.. describe`` directive:

    :orphan:

    .. title:: choice: Quark SE Selection

    .. _choice_40:

    .. describe:: choice: Quark SE Selection
    
The ``.. describe`` directive appears just like the ``.. option`` directive on output, but doesn't generate a linking target, but the label on the previous line make a link target.

Then instead of using `` :option:`choice_40` `` to link to it, use `` :ref:`<choice> <choice_40>` `` or even use the prompt string and say `` :ref:`choice: Quark SE Selection <choice_40>` ``

**Comment by ulfalizer** [comment]
@dbkinder 
Thanks for the tip! I implemented that version.

Having the prompt text in there as well is nice.

Only thing that looks slightly wonky is that `choice` links get a different style compared to `symbol` links, but it's still an improvement.

skarmbild fran 2018-06-08 10-18-30

**Comment by ulfalizer** [comment]
@carlescufi 
Yeah... might be better. Changed.

**Review by carlescufi — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
Let's give it a try. Thanks.

**Pull request merged**
