### PR TITLE
arch/arm64: update gicv3 sre enablement

### PR DESCRIPTION
**Pull request by quic-egmc**
Fix writing of ICC_SRE_EL3 to or-in bits to align
with original intent to read-modify-write this
register.

Also disable FIQ and IRQ bypass so interrupt delivery
occurs through GIC.  Platforms may choose to override
this behavior in z_arm64_el3_plat_init implementations.

Signed-off-by: Eugene Cohen <quic_egmc@quicinc.com>

### CODE REVIEW

**Comment by carlocaione** [comment]
can you remove the overlapping bit setting from viper and QEMU now that we have that in the core code?

**Comment by quic-egmc** [comment]
> can you remove the overlapping bit setting from viper and QEMU now that we have that in the core code?

done!

**Review by povergoing — DISMISSED** [review]

**Review by carlocaione — DISMISSED** [review]

**Comment by MaureenHelm** [comment]
Please rebase

**Comment by quic-egmc** [comment]
rebase done

**Review by povergoing — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]

**Pull request merged**
