### PR TITLE
west.yml: allow users to easily add more modules

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Import any manifest files in a new 'submanifests' directory into
west.yml.

This lets users define custom zephyr modules or easily override
built-in modules by dropping their own manifest files into
submanifests/some-user-file.yaml.

Provide an example and a README with links to the relevant
documentation in 'submanifests' to get users started.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
The failing manifest action is because the action code can't handle imports here. I don't think it's a real problem with this PR. Will look into it.

**Comment by mbolivar-nordic** [comment]
Added DNM / RFC.

**Review by carlescufi — CHANGES_REQUESTED** [review]
This is a very good idea. The only thing I am missing is a reference to the new `submanifests` folder in the documentation. Maybe in the west user guide?

**Comment by mbolivar-nordic** [comment]
> Maybe in the west user guide?

I would suggest https://docs.zephyrproject.org/latest/guides/modules.html actually.

**Comment by cfriedt** [comment]
Seems like an interesting concept. I can see how this makes it slightly easier for external project CI because the actual manifest does not need to be modified

**Review by erwango — APPROVED** [review]
Handy improvement, approving with the condition the doc update is done as requested by @carlescufi

**Review by cfriedt — APPROVED** [review]
Same. LGTM, as long as @carlescufi 's concerns on docs are addressed.

**Comment by mbolivar-nordic** [comment]
> I would suggest https://docs.zephyrproject.org/latest/guides/modules.html actually.

I didn't get any negative feedback on this suggestion, so I went with this instead of the west pages.

**Comment by mbolivar-nordic** [comment]
> The failing manifest action is because the action code can't handle imports here. I don't think it's a real problem with this PR. Will look into it.

https://github.com/zephyrproject-rtos/action-manifest/pull/3 contains a fix

**Comment by mbolivar-nordic** [comment]
Rebased now that the action changes are merged. @carlescufi please revisit.

**Comment by mbolivar-nordic** [comment]
```
Run zephyrproject-rtos/action-manifest@v1.1.0
```

@carlescufi looks like GitHub is ignoring https://github.com/zephyrproject-rtos/zephyr/pull/37155/commits/1423484d03aa1ed39a9d8c92d16341703a7e4397 and just going with what's in master; not sure how to fix.

**Comment by mbolivar-nordic** [comment]
Maybe https://github.com/zephyrproject-rtos/zephyr/pull/38152 will work.

**Review by carlescufi — APPROVED** [review]

**Comment by tejlmand** [comment]
> > I would suggest https://docs.zephyrproject.org/latest/guides/modules.html actually.
> 
> I didn't get any negative feedback on this suggestion, so I went with this instead of the west pages.

Why wasn't I invited to the party :disappointed:

**Comment by mbolivar-nordic** [comment]
@tejlmand I believe the documentation already adequately covers this feature:

https://docs.zephyrproject.org/latest/guides/west/manifest.html#option-2-relative-path

Please let me know if you still disagree after reading that section.

**Comment by tejlmand** [comment]
> Please let me know if you still disagree after reading that section.

That section does cover it very well :+1: .
Just feel if reading the `self` section where `path` and `west-commands` are present in the example that it's easy to miss, even though it is in the table.

Especially cause the description added by this PR doesn't have a link to https://docs.zephyrproject.org/latest/guides/west/manifest.html#option-2-relative-path 
Thus users might go to `self` section and not the `import` section in the west guide.

**Comment by mbolivar-nordic** [comment]
> Just feel if reading the `self` section where `path` and `west-commands` are present in the example that it's easy to miss, even though it is in the table.

I don't know what you mean, sorry. In the link I pasted, the very first example has this for the `self` section:

```yaml
  self:
    import: submanifests
```

No `path`, no `west-commands`.

**Comment by tejlmand** [comment]
> I don't know what you mean, sorry.

I was referring to this PR, where you added:
> If you want to permanently add modules to the zephyr workspace and you are
using zephyr as your manifest repository, you can also add a west manifest file
into the :zephyr_file:`submanifests` directory. See
:zephyr_file:`submanifests/README.txt` for more details.

which doesn't point directly to the link you provided.
The README.txt itself contains the link, and if you click here: [submanifests](https://github.com/zephyrproject-rtos/zephyr/tree/main/submanifests) the link renders into clickable link, but this: [README.txt](https://github.com/zephyrproject-rtos/zephyr/blob/main/submanifests/README.txt) is just a text file.

In my case I probably just clicked the second link and didn't notice the direct link as it didn't render to a link.
That's probably the reason I ended up in the `self` section in `west` doc and the reason for my initial comment.
As it happened to me, I guess it could happen to others as well.

**Comment by mbolivar-nordic** [comment]
I'm still confused, sorry. You originally wrote in an [above comment](
https://github.com/zephyrproject-rtos/zephyr/pull/37155#issuecomment-946605469):

> as such a submanifest can be used for other things than submodules then I think it could be valuable to actually describe this feature in west

By "actually describe this feature in west", I assumed you mean "document this feature in the west documentation". So I sent you a link to where it is already documented.

If that's not what you meant, what are you asking for?

**Comment by tejlmand** [comment]
> If that's not what you meant, what are you asking for?

i'm not asking for this anymore, cause the link you sent me shows that it is documented in west.
What I tried in my last message, was to explain how I ended up not noticing that this was actually described in `west`.

I probably didn't notice the url in the `README.txt`, and thus I went straight to [west::self](https://docs.zephyrproject.org/latest/guides/west/manifest.html#self) description.

Because the url only renders to a clickable link when accessing [submanifests](https://github.com/zephyrproject-rtos/zephyr/tree/main/submanifests), I wonder if that should be the only link and thus remove the link to the `README.txt`.

Or even have the link to https://docs.zephyrproject.org/latest/guides/west/manifest.html#option-2-relative-path in the Zephyr module text you added. As to avoid others to get lost in the docs as I did :wink:

**Comment by mbolivar-nordic** [comment]
I would prefer to keep things as-is. The point of the README is to get people up to speed quickly who do not care about west. The link to the details is provided for those who are curious or want to know more.

**Pull request merged**
