### PR TITLE
ci: test using Python 3.11 as well

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Run CI tests against Python v3.11 as well.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
This is the first step for adressing #63977. In a follow-up PR, I will add testing on Python v3.12 as well. We should probably start discussing if we should still support as old releases as v3.8/3.9, or at least have a plan for phasing out the CI tests on these versions.

**Review by fabiobaltieri — COMMENTED** [review]
Can we drop 3.8?

**Review by kartben — APPROVED** [review]

**Comment by kartben** [comment]
> Can we drop 3.8?

Ya I was wondering that as well. Looks like it isn't going to be EOL until October 2024, fwiw.

**Comment by henrikbrixandersen** [comment]
> Can we drop 3.8?

If we do, we need to update the GSG to list a newer minimum Python version as well. 

I am not against that, but I think it is out of scope for this PR.

**Review by nashif — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
