### PR TITLE
log: make name param explicit

### PR DESCRIPTION
**Pull request by galak**
Rather than having some implied name for the logging name, explicitly
pass it in the macros LOG_MODULE_REGISTER & LOG_MODULE_DECLARE.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
doc changes look OK

**Comment by pizi-nordic** [comment]
@galak: The logger does not need `LOG_MODULE_NAME`. What you really need is a pointer to static and dynamic logger data is needed.

What about the following solution:

1. In the `_LOG_MODULE_REGISTER(_name, _level)` and `_LOG_RUNTIME_MODULE_DECLARE(_name)` add the following:
```
static inline const struct log_source_const_data *__log_current_const_data_get(void)
{
    return & LOG_ITEM_CONST_DATA(_name);
}

static inline struct log_source_dynamic_data *__log_current_dynamic_data_get(void)
{
    return &LOG_ITEM_DYNAMIC_DATA(_name);
}
```

2. Instead of using `&LOG_ITEM_DYNAMIC_DATA(LOG_MODULE_NAME)` and `&LOG_ITEM_CONST_DATA(LOG_MODULE_NAME)` use the `__log_current_dynamic_data_get()` and `__log_current_const_data_get()`.

The compiler should optimize out these functions and you will get something local to current compilation unit.

**Comment by nordic-krch** [comment]
@galak, @pizi-nordic proposal looks good imo.

**Comment by galak** [comment]
@pizi-nordic do you want to go head and make the change you suggested?

**Comment by nordic-krch** [comment]
@galak, @pizi-nordic is on vacation. I've applied his suggestion by modifying last commit on my fork (https://github.com/nordic-krch/zephyr/commits/logging). Not sure how to proceed with that?

**Comment by galak** [comment]
> @galak, @pizi-nordic is on vacation. I've applied his suggestion by modifying last commit on my fork (https://github.com/nordic-krch/zephyr/commits/logging). Not sure how to proceed with that?

Thanks, I pulled your changes into my tree and made a few updates.

**Comment by mbolivar** [comment]
Is it possible to use logger after this commit with module_foo from a static inline routine in module_foo.h, as well as with module_bar from module_bar.c, where module_bar.c includes module_foo.h?

I am guessing the previous way 'ought' to work, possibly with some warnings for redefining the macro, but I'm less sure about the effect this PR would have on that. @galak, can you clarify?

**Comment by mbolivar** [comment]
> Is it possible to use logger after this commit with module_foo from a static inline routine in module_foo.h, as well as with module_bar from module_bar.c, where module_bar.c includes module_foo.h?

I'm thinking of situations like this. What should the behavior be in general (with or without implicit names)?

```c
/******************************************************************************
 * in module_foo.h:
 */

#define LOG_MODULE_NAME foo
#include <logging/log.h>
LOG_MODULE_REGISTER();

static inline void module_foo_func(void)
{
	LOG_INF("hello from foo");
}


/******************************************************************************
 * in module_bar.c:
 */

#include <module_foo.h>
#define LOG_MODULE_NAME bar
#include <logging/log.h>
LOG_MODULE_REGISTER();

void module_bar_func(void)
{
	module_foo_func();
	LOG_INF("hello from bar");
}
```

**Comment by nordic-krch** [comment]
@mbolivar it's not only after this commit but in general using log in head it risky. I haven't yet into that but probably we would need to preceed every #define LOG_MODULE_NAME with #undef LOG_MODULE_NAME and use LOG_MODULE_DECLARE() in header and LOG_MODULE_REGISTER in C file.

**Review by nordic-krch — APPROVED** [review]
lgtm. Not sure why shippable complains about line length. It usually accepts my 'signed-off-by'.

edit: missing dash probably: **Signed-off by**: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

**Comment by mbolivar** [comment]
> I haven't yet into that but probably we would need to preceed every #define LOG_MODULE_NAME with #undef LOG_MODULE_NAME and use LOG_MODULE_DECLARE() in header and LOG_MODULE_REGISTER in C file.

Is that type of approach compatible with the changes @galak is suggesting? Naively it doesn't seem so, since the idea is to delete LOG_MODULE_NAME usage.

**Comment by galak** [comment]
> Is that type of approach compatible with the changes @galak is suggesting? Naively it doesn't seem so, since the idea is to delete LOG_MODULE_NAME usage.

Yeah, we should assume magic #defines being set, thus me merging this.

**Pull request merged**
