### PR TITLE
Bluetooth: controller: Moves lll_adv.h to common

### PR DESCRIPTION
**Pull request by Thalley**
Moved the lll_adv.h header from the nordic subdirectory
to the common ll_sw directory. This will allow the higher layers
to include the ull_adv_types.h file, as that depends on the structures in
lll_adv.h. This also puts the files next to the other lll_x.h headers.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

### CODE REVIEW

**Comment by thoh-ot** [comment]
lll_adv.h is not a common header file, it's vendor specific header file as the lll_adv structure can contain vendor specific fields needed by that lll implementation.

What do you mean by "allow the higher layers"? What problem is it that your are trying to solve? Many of the ull_*.c files include lll_adv.h before including ull_adv_types.h.

**Comment by Thalley** [comment]
@thoh-ot The `ull_adv_types.h` depend on the `lll_adv` struct to be defined. E.g. hci.c cannot include `ull_adv_types.h` for that reason. By higher layer I'm specifically talking about the hci (controller) layer. 

I was also under the understanding that the `lll_xxx.h` files were vendor specific and not common, but `lll_scan.h`, `lll_conn.h` and `lll_sync.h` files are all in the common `ll_sw` directory.

**Comment by thoh-ot** [comment]
It seems that when we did the reorganization of the code, we (Oticon) only had a need to have a custom `lll_adv.h` and `lll_xxx.h` header files where forgotten and not moved. Non the less our `lll_adv.h` is vendor specific so we cannot move `lll_adv.h` to common.

Why is it impossible to include `lll_adv.h` (and all of it's dependencies) in `hci.c` before including `ull_adv_types.h`?

**Review by kruithofa — APPROVED** [review]

**Review by thoh-ot — CHANGES_REQUESTED** [review]
NACK

**Comment by Thalley** [comment]
> It seems that when we did the reorganization of the code, we (Oticon) only had a need to have a custom `lll_adv.h` and the other `lll_xxx.h` header files where forgotten and not moved. Non the less our `lll_adv.h` is vendor specific so we cannot move `lll_adv.h` to common.
> 
> Why is it impossible to include `lll_adv.h` (and all of it's dependencies) in `hci.c` before including `ull_adv_types.h`?

@thoh-ot I'm sorry for not disclosing that in the PR: `ull_adv_types.h` contains references to `struct lll_adv` which is defined in `lll_adv.h`. 

I'd be very open for any ideas on how we can expose the ULL adv types, without moving the `lll_adv.h`. Perhaps this is part of a larger problem of consistency in the file structure of the controller, if we treat adv types different than scan types. 

I suggest that we take this discussion tomorrow at our weekly meeting.

**Comment by Thalley** [comment]
It's possible to include the `lll_adv.h` file without the full path, so that it'll include the right one without having to move this. Closing.

**Pull request closed without merging**
