### PR TITLE
Initial release of SD/MMC interface driver

### PR DESCRIPTION
**Pull request by pic16f887**
Pull request contains generic API interface for SD/MMC device and device specific driver for STM32F7 MCU family.

### CODE REVIEW

**Comment by ChaserTlss** [comment]
Anyone review this? Maybe this patch is useful for me.

**Comment by hongshui3000** [comment]
+1

**Comment by hongshui3000** [comment]
What is the status of this pull request?

**Comment by erwango** [comment]
@pic16f887, sorry for late feedback on this. Had missed this proposal.
After having had a very quick look, this seems rather good, even if I can't comment on the proposed API.
Could you rebase the PR so we can start an active review?

**Comment by pic16f887** [comment]
@erwango, I have rebased the code.

**Comment by erwango** [comment]
@pic16f887, sorry once again for letting this PR not reviewed.
To get more attention on that PR, can you please split the generic API and STM32 parts?
The generic API should get more attention.

**Comment by galak** [comment]
@pic16f887 any updates on this?

**Comment by avisconti** [comment]
Adding support to SDMMC looks quite interesting.
Has it been abandoned?

**Comment by pic16f887** [comment]
Currently I don't have a free time to finish it. You are free to use this code.

**Comment by galak** [comment]
Closing PR as its been marked stale for several months.  Feel free to re-open and update if desired.

**Pull request closed without merging**
