### PR TITLE
arch: arm: mpu: enforce power-of-two alignment only for user mode

### PR DESCRIPTION
**Pull request by ioannisg**
This commit modifies how the requirement for power-of-two
alignment for ARMv7-M MPU regions is enforced, making the
requirement be enforced only if building an application
with support for user Userspace feature.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by andrewboie** [comment]
What problem does this patch solve? In fact this really doesn't seem correct.
It's not like disabling userspace changes the fact that MPU regions have to be power of two size/aligned.

**Comment by ioannisg** [comment]
> 
> 
> What problem does this patch solve? In fact this really doesn't seem correct.
> It's not like disabling userspace changes the fact that MPU regions have to be power of two size/aligned.

@andrewboie this patch attempts to solve the problem of wasting stack area for threads. E.g. a Thread that needs 768, does not need to move up to 1024 bytes.

But I believe, I do see your concern:

The alignment of start and size with the minimum region size (32) is still enforced. So, we won't have an issue with MPU stack guards.

The only remaining problem would be the sizing of fixed regions, e.g. NO_CACHE, right? But that we could fix directly in the linker...

**Review by dbkinder — APPROVED** [review]
doc change LGTM.

**Comment by andrewboie** [comment]
```
@andrewboie this patch attempts to solve the problem of wasting stack area for threads. E.g. a Thread that needs 768, does not need to move up to 1024 bytes.

But I believe, I do see your concern:

The alignment of start and size with the minimum region size (32) is still enforced. So, we won't have an issue with MPU stack guards.
```

I just feel like this isn't quite the right solution.
Can't we make the stack rounding up logic conditional on CONFIG_USERSPACE instead? And not MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT?
My concern is that MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT describes how the hardware functions, it's not a policy setting.

**Comment by ioannisg** [comment]
> 
> 
> ```
> @andrewboie this patch attempts to solve the problem of wasting stack area for threads. E.g. a Thread that needs 768, does not need to move up to 1024 bytes.
> 
> But I believe, I do see your concern:
> 
> The alignment of start and size with the minimum region size (32) is still enforced. So, we won't have an issue with MPU stack guards.
> ```
> 
> I just feel like this isn't quite the right solution.
> Can't we make the stack rounding up logic conditional on CONFIG_USERSPACE instead? And not MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT?
> My concern is that MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT describes how the hardware functions, it's not a policy setting.

Yes, we could do that.

**Comment by ioannisg** [comment]
@andrewboie, I just had a more careful look into this:
So:
>My concern is that MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT describes how the hardware functions, it's not a policy setting.

This is absolutely correct.

>Can't we make the stack rounding up logic conditional on CONFIG_USERSPACE instead? And not MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT?

This is _already_ the case :)

Now, I suppose, @carlescufi, the remaining problem for you is that even if one wants to create a Supervisor thread (when building with CONFIG_USERSPACE), they would still have to round-up the size to the next power of two. That's the case, even if that thread has no intention of switching to user mode, ever (that should be the case for the BT stack threads).

@andrewboie how could we fix this issue? I.e. have an option at compile time to define thread stacks for supervisor-only threads that do not need to respect the power-of-two rounding up, but these thread shall never drop to user mode?

**Comment by ioannisg** [comment]
This PR is invalid as is - we should not merge at current state.

**Comment by andrewboie** [comment]
> @andrewboie how could we fix this issue? I.e. have an option at compile time to define thread stacks for supervisor-only threads that do not need to respect the power-of-two rounding up, but these thread shall never drop to user mode?

I think we need an alternate set of stack declaration macros for threads that will never drop to user mode. This is useful on x86 too as we'll save memory that would normally be allocated for the supervisor mode stack.

This is out of scope for 1.14 though.

**Comment by agross-linaro** [comment]
@andrewboie So if we add separate APIs and they are misapplied by the user, at worst we waste more memory, correct?

**Comment by andrewboie** [comment]
> @andrewboie So if we add separate APIs and they are misapplied by the user, at worst we waste more memory, correct?

They would either waste memory, or get a fatal error upon dropping to user mode when using a stack object that isn't designed for it, depending on the type of mis-match.

I opened #13637 for that.

Closing this, since it's not valid.

**Pull request closed without merging**
