### PR TITLE
tests: posix: env: colocate with single_process option group

### PR DESCRIPTION
**Pull request by cfriedt**
Move the previously singular `env` testsuite to be with the other features that are part of the `POSIX_SINGLE_PROCESS` Option Group.

This PR was forked from #81766

### CODE REVIEW

**Comment by cfriedt** [comment]
This PR was forked from #81766

**Review by ycsin — APPROVED** [review]

**Comment by cfriedt** [comment]
@ycsin - I wonder if I should try this again with CONFIG_POSIX_API. That should work for native_sim, right? At least in that case the standard includes paths could be used.

**Comment by ycsin** [comment]
> That should work for native_sim, right?

Hopefully? But probably have to wait until the ongoing refactoring work are done and do them in one go

**Comment by cfriedt** [comment]
I tried with `CONFIG_POSIX_API=y` but it doesn't Just Work unfortunately. So will leave the PR as-is.

It can be approved / merged

**Review by ceolin — APPROVED** [review]

**Pull request merged**
