### PR TITLE
settings: Add support for overriding NVS/FCB settings partition

### LINKED ISSUE #30152: Settings nvs subsystem uses a hardcoded flash area label
Enabling `CONFIG_SETTINGS_NVS` will result in `settings_nvs.c` initializing and using the flash area labeled `storage`, which is hardcoded in the subsys init function.

I would prefer if this partition label was configurable, so I could choose where the Settings subsys stored NV params.

Considered using Kconfig for this label, but Kconfig does not supported unquoted strings to produce a label.
The flash area partition id could also be passed when calling the `settings_subsys_init(void)` function,
like so `settings_subsys_init(struct flash_area *fap)`.
This would entail an API update and updating the backends accordingly.

### PR DESCRIPTION
**Pull request by abxy**
Change settings NVS and FCB backend to looks for chosen `zephyr,settings-partition`
in the first place, or fall back to partition "storage" if the chosen is not set.

This should fix https://github.com/zephyrproject-rtos/zephyr/issues/30152.

### CODE REVIEW

**Review by nvlsianpu — COMMENTED** [review]
Looks fine to me at the first glance.
I was thinking that assignment of partition to the settings have been done only for most simple scenario when the settings are the only storage client in the application. Looks like this approach makes possible to assign a dedicated partition.

**Review by nvlsianpu — COMMENTED** [review]
@abxy  can you update a settings test to use introduced chosen value?

**Comment by Laczen** [comment]
@abxy, thanks for the PR, this is a very nice addition. What do you think about naming it `zephyr,settings-partition`, this would also make it applicable to fcb.

**Comment by abxy** [comment]
I renamed the chosen to `zephyr,settings-partition` and updated to apply to FCB as well. Added a test each for NVS and FCB.

**Review by Laczen — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
