### PR TITLE
nrf52_nffs_example

### PR DESCRIPTION
**Pull request by vikrant8052**
…com>

	new file:   samples/subsys/fs/nffs/CMakeLists.txt
	new file:   samples/subsys/fs/nffs/README.rst
	new file:   samples/subsys/fs/nffs/prj.conf
	new file:   samples/subsys/fs/nffs/sample.yaml
	new file:   samples/subsys/fs/nffs/src/main.c

### CODE REVIEW

**Comment by carlescufi** [comment]
Hi Vikrant, thanks for contributing. You need to edit your commit message so it looks like:

```
samples: nffs: New NFFS sample

<description>

Signed-of-by: First Last <email>
```

If you need help configuring git to achieve this please join #zephyrproject on IRC (freenode.net) and I'm sure we'll be able to help you.

**Comment by vikrant8051** [comment]
Yes, I did it. 
Hope now it will get accepted.

**Comment by carlescufi** [comment]
This is still somehow incorrect. Look at the "Commits" tab and you will see there are 2 commits, one of which has incorrect formatting. You need to use:

```
git rebase -i upstream/master
```
to merge both commits into a single one

Then you can use

```
git commit --amend
```

to modify the commit message

**Comment by carlescufi** [comment]
@vikrant8051 you don't need to close the PR, you can change your commits and then `git push -f`

**Pull request closed without merging**
