### PR TITLE
drivers/i2c:  Reset the i2c for STM32F1 series to enter master mode properly

### PR DESCRIPTION
**Pull request by ycsin**
This pr fixes the I2C issue mentioned in #33196

Signed-off-by: Yong Cong Sin yongcong.sin@gmail.com

### CODE REVIEW

**Comment by ycsin** [comment]
ping @erwango @FRASTM @tagunil

**Review by erwango — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Please fix commit message.
(You don't need to mention previous review in the commit message)

**Review by FRASTM — APPROVED** [review]
commit message to update

**Comment by ycsin** [comment]
I don't understand, what commit message should I fix?

**Comment by erwango** [comment]
> I don't understand, what commit message should I fix?

Look at [details](https://github.com/zephyrproject-rtos/zephyr/pull/34088/checks?check_run_id=2288372069) in Compliance checks that are reported "Failed":
```
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

571f38edd1bf63607252cf0f9eefe4ad1d50c6b5: author email (Yong Cong Sin <yongcong.sin@gmail.com>) needs to match one of the signed-off-by entries.
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

1: UC2 Body does not contain a 'Signed-off-by:' line
1: UC5 Title exceeds max length (76>75): "drivers/i2c:  Reset the i2c for STM32F1 series to enter master mode properly"
1: UC6 Body has no content, should at least have 1 line.
3: B6 Body message is missing
Error: Process completed with exit code 1.
```

So you should fix your commit message:
- Add a sign-off
- Make title shorter
- Provide a commit description

**Comment by ycsin** [comment]
I see, is there a way to fix the commit message without doing a new PR?

**Comment by erwango** [comment]
> I see, is there a way to fix the commit message without doing a new PR?

Yes, you just need to amend your change.
cf `git amend` or click the amend button on git giu

> EDIT: I've already deleted the repo that has that commit, I think I have to recreate a new PR

Ok, this is getting harder :-).
So, FYI, you don't need to create a new PR:
In theory, you just need to use the same branch name and force push `git -f <your_repo> <branch_name>`.
Last, it is a good practice to avoid using `master` as branch name to push pull request.
Also, it is recommended not to delete branch before the PR is merged...

**Comment by ycsin** [comment]
Thanks for the patience and guidance, I will take note of these next time.
Will have to find some free time to learn how to force push something.

**Comment by ycsin** [comment]
Can't seem to have the deleted branch back, created yet another one (#34241) and therefore closing this, sorry for 'littering' the PR section!

**Pull request closed without merging**
