### PR TITLE
hal: nxp: Update to SDK 2.10.0

### LINKED ISSUE #37619: RT6xx TRNG reports error on first request after reset
**Describe the bug**
The recently added TRNG support for RT platforms (#37385) exposed an error that occurs where the first request to TRNG_GetRandomData() returns an error.

**To Reproduce**
1. west build -b mimxrt685_evk_cm33 -p always tests\crypto\rand32
2. west flash
3. connect serial terminal and hit reset button to see the error

**Expected behavior**
expectation is for no error.

**Impact**
Serious problem

### PR DESCRIPTION
**Pull request by dleach02**
Updating to the SDK 2.10.0 for select platforms.

Fixes #37619

Signed-off-by: David Leach <david.leach@nxp.com>

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by hakehuang** [comment]
@dleach02 I need 2 days full testing on this, will feedback once finish

**Comment by galak** [comment]
@dleach02 looks like failure with lpcxpresso55s69_ns. I know @microbuilder was asking about updating the SDK around the TFM integration, so he might be aware of what fix we need for TFM.

**Comment by galak** [comment]
@dleach02 are we waiting on something here to merge things here?

**Comment by dleach02** [comment]
@galak, I'm just waiting on the finish of an internal testing run on our HW range. Should be ready by tomorrow (it found issues over the weekend).

**Review by hakehuang — APPROVED** [review]
regression testing pass on all boards

**Comment by galak** [comment]
@dleach02 I merged the HAL side of this, can you update this PR now.

**Comment by dleach02** [comment]
Okay... I messed that up... give me a moment to fix this

**Comment by dleach02** [comment]
Okay... my 'git-fu' is not strong... new PR: #37680

**Pull request closed without merging**
