### PR TITLE
Bluetooth: Host: Fix ble event mask macro define.

### PR DESCRIPTION
**Pull request by zhjseu**
Signed-off-by: zhenghuajiang <hjzheng@bouffalolab.com>

### CODE REVIEW

**Review by Thalley — CHANGES_REQUESTED** [review]
The change is correct, but please add a commit message.

**Review by jhedberg — CHANGES_REQUESTED** [review]
As @Thalley said, looks like a good fix, but you need to add a commit message, and also (minor, but still) remove the `.` from the end of the summary line for consistency. You can do all this with `git commit --amend` + `git push --force`

**Comment by zhjseu** [comment]
@jhedberg @Thalley ，Sorry to forget the commit message, I will recommit it.

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by zhjseu** [comment]
hi, @Thalley @jhedberg , why still awaiting approval, is there anything wrong in the submission?

**Comment by jhedberg** [comment]
> why still awaiting approval, is there anything wrong in the submission

As you can see from the failed compliance check, you need to update the commit author information to match the Signed-off-by line (which looks fine)

**Pull request merged**
