### PR TITLE
drivers/i2c: Reset i2c of STM32F1 series to enter master mode properly

### PR DESCRIPTION
**Pull request by ycsin**
It's required to reset the I2C of the STM32F1 series for them to enter master mode properly.
This pr fixes the I2C issue mentioned in #33196

Signed-off-by: Yong Cong Sin <yongcong.sin@gmail.com>

### CODE REVIEW

**Comment by ycsin** [comment]
Finally it passed the compliance test, but I still don't understand why my previous commit message body failed. Some how it says it is too long (>75)?

**Comment by ycsin** [comment]
ping @erwango @FRASTM 
Third time a charm? Or at least I know how to amend and force push this PR as long as I didn't delete the branch

**Review by erwango — APPROVED** [review]

**Comment by FRASTM** [comment]
The Errata Sheet 096is said to apply to the medium-density devices, why enabling this to all the stm32F1 family by default.
Does the stm32f105 or f107 also require this WA ?

**Comment by erwango** [comment]
@FRASTM This was done on my request (on an earlier PR), as this is issue is reported in ES of all F1 variants.

**Review by FRASTM — APPROVED** [review]

**Pull request merged**
