### PR TITLE
Add example of OpenThread config and LWM2M Push button example

### PR DESCRIPTION
**Pull request by retfie**
Simple example with OpenThread and LWM2M IPSO Push button on Nordic nRF52840-PCA10056 board.

Build:
west build -s samples/net/lwm2m_client -d build-lwm2m_client -b nrf52840_pca10056 -- -DCONF_FILE=overlay-ot.conf

Sign:
west sign -t imgtool -d build-lwm2m_client -- --key root-rsa-2048.pem --header-size 512 --version 1.2.3

Flash:
west flash -d build-lwm2m_client --hex-file build-lwm2m_client/zephyr/zephyr.signed.hex

### CODE REVIEW

**Comment by mike-scott** [comment]
@retfie Hello!  First, thank you for submitting a PR to Zephyr!  I almost never get submissions for the LwM2M subsys.

I have a rather large rework of the current lwm2m sample in progress and if possible could we delay working on this PR till I get that up?   I really like how the work for the Nordic SDK came out here: https://github.com/NordicPlayground/fw-nrfconnect-nrf/tree/master/samples/nrf9160/lwm2m_client/src/lwm2m

And I'm going to split out the lwm2m source the same way in the mainline.

**Comment by retfie** [comment]
> @retfie Hello! First, thank you for submitting a PR to Zephyr! I almost never get submissions for the LwM2M subsys.
> 
> I have a rather large rework of the current lwm2m sample in progress and if possible could we delay working on this PR till I get that up? I really like how the work for the Nordic SDK came out here: https://github.com/NordicPlayground/fw-nrfconnect-nrf/tree/master/samples/nrf9160/lwm2m_client/src/lwm2m
> 
> And I'm going to split out the lwm2m source the same way in the mainline.

Sure, feel free to reuse some of the parts of this PR or totally ignored it, if something more is coming in this area. I'm very appreciate your work, and very impatient for updates !

Thanks,
Kiril

**Comment by jukkar** [comment]
> west build -s samples/net/lwm2m_client -d build-lwm2m_client -b nrf52840_pca10056 -- -DCONF_FILE=overlay-ot.conf

Just wondering if there is a typo here or was the overlay-ot.conf created with all needed options. Shouldn't the overlay file be specified with `-DOVERLAY_CONFIG=overlay-ot.conf`, isn't the prj.conf file now discarded if done like this?

**Comment by mike-scott** [comment]
@jukkar yes, it looks like the overlay-ot.conf is actually a full conf.  I was going to address that once I get back to this PR.

Or, just use the overlay that I have and haven't gotten around to posting.

**Pull request closed without merging**
