### PR TITLE
ext: hal: cmsis: Update ARM CMSIS headers to version 5.3.0

### PR DESCRIPTION
**Pull request by galak**
Origin: ARM CMSIS v5.3.0
License: Apache-2.0
URL: https://github.com/ARM-software/CMSIS_5.git
commit: 80cc44bba16cb4c8f495b7aa9709d41ac50e9529
Purpose: CMSIS Headers update.
Maintained-by: External

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
Required for ARMv8-M I assume?

**Review by carlescufi — CHANGES_REQUESTED** [review]
Hang on, your commit SHA in the commit message doesn't match the one in the official 5.3.0 release:

https://github.com/ARM-software/CMSIS_5/releases/tag/5.3.0

**Comment by galak** [comment]
> Required for ARMv8-M I assume?

the 5.2.0 release was needed for ARMv8-M, just keeping in sync w/CMSIS releases as ARMv8-M development is active.

**Comment by galak** [comment]
> Hang on, your commit SHA in the commit message doesn't match the one in the official 5.3.0 release:
> 
> https://github.com/ARM-software/CMSIS_5/releases/tag/5.3.0

Oops, had the 5.2.0 SHA, fixed now.

**Review by carlescufi — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
