### PR TITLE
snippets: cdc-acm-console: Initialize USB device stack at boot

### PR DESCRIPTION
**Pull request by casparfriedrich**
This snippet is most likely used to enable easy logging and without modifying application code; therefore the USB device stack should be initialized as well.

### CODE REVIEW

**Review by tmon-nordic — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Review by jfischer-no — CHANGES_REQUESTED** [review]
This should not be the default behavior, but can be easily enabled by the user by passing -DCONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

**Comment by carlescufi** [comment]
> This should not be the default behavior, but can be easily enabled by the user by passing -DCONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

Just for info, could you elaborate as to why this should not be the default behavior?

**Comment by jfischer-no** [comment]
> Just for info, could you elaborate as to why this should not be the default behavior?

Because it also can and should be usable with any USB sample/application (except console, of course). It cannot if CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT is set by default.

In general, it is reasonable for the user to pass some of the options from the command line. And not to have a default configuration or overlay configuration for every little thing.

**Comment by carlescufi** [comment]
> Because it also can and should be usable with any USB sample/application (except console, of course). It cannot if CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT is set by default.

But the snippet is called "cdc-acm-console", doesn't that mean that this snippet is designed and conceived for CDC ACM output only? If the snippet was called "usb-support" that would be different?

**Comment by nordicjm** [comment]
What other USB service would people be using with this snippet because in my mind they would be using USB CDC only

**Comment by carlescufi** [comment]
> What other USB service would people be using with this snippet because in my mind they would be using USB CDC only

Imagine you want to combine `hid-mouse` with CDC ACM output, because usually you test it on DKs with physical UART but now you want to test it on a dongle.

**Comment by casparfriedrich** [comment]
I kinda thought this was designed to get a cheap and easy way to enable some logging or shell. Passing `CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT` on the same command line is just the same with extra steps, right? And I imagined that projects already using USB device classes regularly wouldn't use this snippet anyway, since it just adds some configuration you most likely already have in your project.

**Comment by casparfriedrich** [comment]
Would it make sense to have a second snippet for that purpose?

**Comment by nordicjm** [comment]
I don't see the point in this snippet existing if it doesn't do what it says in the name. If you need it to work with something specialised like a USB HID device then why would you use this, you already have USB setup. But for people wanting to just use CDC ACM without USB this does not work without additional Kconfigs used - how is that useful?

**Comment by casparfriedrich** [comment]
How do be proceed from here?

**Comment by jfischer-no** [comment]
> How do be proceed from here?

I will not accept this patch. I have explained this many times, see also https://github.com/zephyrproject-rtos/zephyr/pull/61522#issuecomment-1682490684. Passing an extra command during the build is perfectly acceptable. Perhaps, we can do some magic when snippets support Kconfig files.

**Comment by jfischer-no** [comment]
> I don't see the point in this snippet existing if it doesn't do what it says in the name. If you need it to work with something specialised like a USB HID device then why would you use this, you already have USB setup. But for people wanting to just use CDC ACM without USB this does not work without additional Kconfigs used - how is that useful?

Snippet name is "CDC-ACM Console", and description "This snippet redirects serial console output to a CDC ACM UART", there is nothing about USB setup.

> 
> And years later we keep coming back to the badly designed USB Kconfig system where it just does not work well for people - lots of people. Why can't it be reworked to use hidden KConfigs for e.g. "SELECT_CANNOT_INIT_AT_BOOT" then make the init a boot dependent upon that not being selected like other subsystem KConfigs use?

Your frustration is based on your behavior of sticking with something more complicated and error-prone than simple additional Kconfig option from the command line.

**Comment by nordicjm** [comment]
> Your frustration is based on your behavior of sticking with something more complicated and error-prone than simple additional Kconfig option from the command line.

Let's be clear on this, it is not *my* frustration, it is frustration *of anyone that has tried to do this*, hence why there are so many issues raised about a single issue.

**Pull request closed without merging**
