### PR TITLE
lib/rbtree: Remove dead case in rb_remove()

### PR DESCRIPTION
**Pull request by Zhaoningx**
Fix issue #33239 to remove some bad code.

Signed-off-by: Ningx Zhao <ningx.zhao@intel.com>

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
I see the logic and this makes sense.  Can we improve the commit message though?  The term of art for this is "dead" code, not just "bad". :)  Something like:

```text
    lib/rbtree: Remove dead case in rb_remove()

    This "else" clause was dead code, in a valid tree it's not possible to have a node
    and its child both be red.
```

**Comment by andyross** [comment]
Also needs a proper header, should read "Fixes #33239" for the github automatic issue closer to work.

**Comment by andyross** [comment]
Having looked at this, this is subtle.  I believe that if the coverage shows that this never gets hit even in the stress unit test[1] that this is dead code, but I've managed to convince myself in both directions now several times.  I fear this might be live, but simply untested.

At the very least we should replace that case with an assertion instead.  There is a low cost  e.g.:

```c
                /* Both the node and its new child cannot be red here because
                 * (insert reason)
                 */
		__ASSERT(is_black(node)** || is_black(child), "both nodes red?!");
		if (is_red(node) || is_red(child)) {
			set_color(child, BLACK);
		}
```

[1]  Please check that the stress test is part of coverage!  It's a "unit" test now and I don't know if that gets picked up or not.  If that code is NOT run and we just don't hit this case in the tiny use cases that impact normal threads, then my guess is this fix is wrong and this is live code!

**Comment by Zhaoningx** [comment]
Hi @andyross , thanks for your comments, it's my thoughtlessness, I just analyzed and tested the source code rb.c carefully.  But I have no idea about the stress test, so could you tell me how to check that the stress test, how should I do about this? Thanks.

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
OK, I'm convinced.   At this point in the code, "node" is the node to be removed, which was previously located potentially anywhere in the tree.  But it's been swapped here into the position of a leaf child or a parent of exactly one leaf child (by construction).  And it now has the color that this position held before the swap.  Therefore we can assume the colors are correct.

Also: the test in question is tests/unit/rbtree, it has an exerciser that builds very large random trees to find edge cases in the code.  Because it's a "unit" test it probably doesn't run as part of coverage.  Maybe.  Honestly I'm not sure.

**Pull request merged**
