### PR TITLE
include: net: http: rework http headers

### PR DESCRIPTION
**Pull request by cfriedt**
Some housekeeping to make #46758 slightly easier
* move `enum http_method` to its own header under `http/`
* create `scripts/net/enumerate_http_status.py`
* add `enum http_status` in a separate header under `http/`
* move remaining http headers to `http/` directory

### CODE REVIEW

**Comment by jukkar** [comment]
Now there are http include files in two directories. Why not put all the http related files in to same place, either to `include/zephyr/net` or `include/zephyr/net/http`?

**Comment by cfriedt** [comment]
> Now there are http include files in two directories. Why not put all the http related files in to same place, either to `include/zephyr/net` or `include/zephyr/net/http`?

I was aiming to do it gradually - could move everything to `http/` though, if that makes sense.

**Comment by cfriedt** [comment]
@stephanosio - looks like the license issue may be a false positive. MIT is permissive, so should be compatible with Apache, unless I'm mistaken.

**Comment by stephanosio** [comment]
> @stephanosio - looks like the license issue may be a false positive. MIT is permissive, so should be compatible with Apache, unless I'm mistaken.

It is not a false positive. Integrating any non-Apache 2.0 code requires TSC approval; if approved, the check result can be overridden.

https://docs.zephyrproject.org/latest/contribute/external.html#submission-and-review-process

**Comment by cfriedt** [comment]
> > It is not a false positive. Integrating any non-Apache 2.0 code requires TSC approval; if approved, the check result can be overridden.
> 
> The code already exists in Zephyr, @cfriedt just moved it to another header and kept the license. I just wonder if we could just mark the license as Apache in the new header, after all it is just some enums we are copying here.

I'm inclined to go with @jukkar 's suggestion. For what equates to effectively constants, I think it's safe to relicense.

**Review by jukkar — COMMENTED** [review]
Looks reasonable. For the latest commit `include: net: http: rename http_x.h http/x.h`, it would be great to see the motivation/reasoning why this change in the commit message. Now the commit msg only states the obvious which can be seen also in the actual change.

**Review by ycsin — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
