### PR TITLE
boards: ambiq: apollo3: add connector dtsi for apollo3 boards

### PR DESCRIPTION
**Pull request by AlessandroLuo**
Added connector dtsi files for apollo3_evb and apollo3p_evb, and ran gpio_basic_api to test, all cases passed

### CODE REVIEW

**Review by RichardSWheatley — DISMISSED** [review]

**Review by aaronyegx — DISMISSED** [review]
LGTM.

**Comment by aaronyegx** [comment]
@AlessandroLuo Please remove the west.yml change to resolve the conflict. The revision of hal_ambiq has been pointed to the latest commit of main branch, otherwise it will cause failure on other test cases/modules.

**Review by aaronyegx — APPROVED** [review]

**Review by RichardSWheatley — APPROVED** [review]

**Comment by AlessandroLuo** [comment]
@nashif please help to merge this PR, thank you!

**Comment by RichardSWheatley** [comment]
> @nashif please help to merge this PR, thank you!

@nordic-krch

**Pull request merged**
