### PR TITLE
add hpmicro device support

### PR DESCRIPTION
**Pull request by willChuai**
This PR adds support for HPMicro HPM6750 SoC and hpm6750evkmini board that is use the SoC.

Add HPM6750 SoC support.

Add HPM6750EVKMINI support
Drivers: Serial, GPIO,Pinctrl

hal_hpmicro module request:
https://github.com/zephyrproject-rtos/zephyr/issues/46301

I submitted a [pull request](https://github.com/zephyrproject-rtos/zephyr/pull/46329) before, but due to the confusion in that pull request, I am initiating the pull request process again.

### CODE REVIEW

**Comment by nordicjm** [comment]
Can you not close and open multiple pull requests?

**Comment by willChuai** [comment]
> Can you not close and open multiple pull requests?

Thank you for your response. Because that pull request has not been approved, and our users have raised some unrelated issues within that pull request as well. I believe the information has become too chaotic, and there won't be any progress if it continues like this. Similarly, the new pull request from [hal_hpmicro](https://github.com/zephyrproject-rtos/hal_hpmicro/pull/2) has not been reviewed, causing my DNM label to remain unresolved. I also don't know whom to contact for this. Please help.

**Comment by gmarull** [comment]
Please, continue the work in https://github.com/zephyrproject-rtos/zephyr/pull/46329

**Comment by willChuai** [comment]
> Please, continue the work in #46329

Ok, But I don't have the authority to reopen that pull request. Please assist in taking the necessary actions. @gmarull @fkokosinski

**Comment by fkokosinski** [comment]
Hi, I can't open the original PR. I'm getting the following message:
> The feature/add_hpmicro_device_support branch was force-pushed or recreated.

**Comment by willChuai** [comment]
> Hi, I can't re-open the original PR. I'm getting the following message:
> 
> > The feature/add_hpmicro_device_support branch was force-pushed or recreated.

I performed these two actions, but it didn't reopen the original pull request. I deleted the branch again and then pull it once more, but there has been no response to the pull request #46329.

**Pull request closed without merging**
