### PR TITLE
ext: nordic: Update nrfx_config*.h entries

### PR DESCRIPTION
**Pull request by anangl**
_ext: nordic: Update nrfx_config_nrf52810.h entries_

This is a follow up to commit f0cf126015a073a5417e6fcfd06b2d41f0f18d87.
Entries in nrfx_config_nrf52810.h are synchronized with the template
from nrfx v1.6.2. In particular, the entries for SPI0, TWI0, and UART0
peripherals are added, so that these peripherals can be actually used
by nrfx drivers in Zephyr.

_ext: nordic: Unify NRFX_UART[E]* options handling in nrfx_config*.h_

The NRFX_UARTE* Kconfig options were handled only in the nrfx_config
for nRF9160. This commit updates remaining nrfx_configs, so that these
options are handled uniformly for all Nordic SoCs.
The NRFX_UART option, although defined in ext/hal/nordic/Kconfig,
were not supported in any of nrfx_config files, effectively making
it impossible to use nrfx_uart.c driver. This commit corrects this.

_ext: nordic: Unify NRFX_RTC* options handling in nrfx_config*.h_

This patch unifies the way NRFX_RTC* Kconfig options are handled in
nrfx_config*.h files for particular Nordic SoCs, so that these files
are easier in maintenance. For nRF52810 and nRF9160, this means adding
of support for these options, since it was missing.

### CODE REVIEW

**Comment by anangl** [comment]
Labeled as a bug because currently any attempt to build for nRF52810 with SPI0 peripheral selected for SPI_0 device (instead of SPIM0), leads to the following compilation error:
```
In file included from ../../../../../ext/hal/nordic/nrfx/nrfx.h:36,
                 from ../../../../../ext/hal/nordic/nrfx/drivers/include/nrfx_spi.h:35,
                 from /home/angl/zephyrproject/zephyr/drivers/spi/spi_nrfx_spi.c:8:
../../../../../ext/hal/nordic/nrfx/drivers/include/nrfx_spi.h:77:35: error: 'NRFX_SPI0_INST_IDX' undeclared here (not in a function); did you mean 'NRFX_SPI_INSTANCE'?
```
A similar error occurs when trying to build with TWI0 peripheral selected.

**Review by ioannisg — APPROVED** [review]

**Comment by ulfalizer** [comment]
`CONFIG_NRFX_UARTE2` and `CONFIG_NRFX_UARTE3` are referenced but undefined by the way (`ext/hal/nordic/Kconfig` only has definitions for `NRFX_UARTE0` and `NRFX_UARTE1`, though those never seem to get set either).

Might be unrelated to this PR, but it's the same code at least.

**Comment by anangl** [comment]
@ulfalizer
> `CONFIG_NRFX_UARTE2` and `CONFIG_NRFX_UARTE3` are referenced but undefined by the way (`ext/hal/nordic/Kconfig` only has definitions for `NRFX_UARTE0` and `NRFX_UARTE1`, though those never seem to get set either).

This is addressed in #13776, see commit 876594a59ce0989ac927a22381258ed92db83933.
These symbols don't get set in the Zephyr source tree because the driver (`ext/hal/nordic/nrfx/drivers/nrfx_uarte.c`) is not currently used there. But we should keep them, so that the driver can be used in out-of-tree code.
Currently these symbols are referenced only from `nrfx_config_nrf9160.h`. I'll add corresponding references to other `nrfx_config_*.h` files, so that we've got them aligned. I'll do it in a separate PR since there are more entries to align between these files (e.g. the counter related ones, `NRFX_RTC*` and `NRFX_TIMER*`).

**Comment by anangl** [comment]
@ulfalizer I finally decided to add the commits that align nrfx_config*.h files to this PR, to avoid merge conflicts between separated PRs.

@ioannisg Could you please re-review.

**Review by carlescufi — APPROVED** [review]

**Comment by anangl** [comment]
Rebased on master, then updated `ext/hal/nordic/nrfx_config_nrf52810.h` with the changes introduced by #13950.

**Pull request merged**
