### PR TITLE
tests: drivers: flash: Move negative tests to a separate project

### PR DESCRIPTION
**Pull request by nordic-segl**
Move negative tests for flash driver to a separate test suite.
Run negative tests only on platforms that are aligned.

### CODE REVIEW

**Comment by nordic-segl** [comment]
Enabling negative tests for all targets was over optimistic.
Motivation:
- there are different types of flash thus obtaining flash start and size from `zephyr,flash` node doesn't work as expected;
- API doesn't state clearly that driver implementation must check input arguments;
- it's not trivial for 'generic' driver (f.e. driver for Nordic nRF devices) to deduct valid addresses of flash memory for each target (flash location on nrf54l15 is different than on nrf54h20 while both are handled by the same driver).

**Comment by nordic-segl** [comment]
FYI @gbarkadiusz , @SzymonRichert , @manuargue

**Comment by gbarkadiusz** [comment]
How about the FRDM and the ITE board?

**Comment by nordic-segl** [comment]
> How about the FRDM and the ITE board?

If I understand correctly, negative tests were failing on FRDM, ITE and some other boards.

I removed negative test cases from tests/drivers/flash/common. This test suite was run on many targets.

I add tests/drivers/flash/negative_tests. This test suite will run only on targets listed in the platform_allow list.
For now, I enabled negative tests on Nordic targets only.
Other targets can be enabled later, when it's confirmed that tests are working correctly on them.

**Comment by manuargue** [comment]
> there are different types of flash thus obtaining flash start and size from zephyr,flash node doesn't work as expected;

perhaps we can use an alias so that each board can set in the overlay what's the flash memory device

**Comment by nordic-segl** [comment]
After cutting out code related to negative tests, I see source of problems.
```
#define TEST_AREA storage_partition
#define TEST_AREA_DEVICE FIXED_PARTITION_DEVICE(TEST_AREA)
static const struct device *const flash_dev = TEST_AREA_DEVICE;

#define TEST_FLASH_START (DT_REG_ADDR(DT_CHOSEN(zephyr_flash)))
#define TEST_FLASH_SIZE (DT_REG_SIZE(DT_CHOSEN(zephyr_flash)))

flash_fill(flash_dev, fill_val, (TEST_FLASH_START - 1), EXPECTED_SIZE);
```
I use flash device for `storage_partition` while flash start address and size I take from `zephyr_flash`.

**Comment by manuargue** [comment]
> I use flash device for `storage_partition` while flash start address and size I take from `zephyr_flash`.

that was I was trying to tell you here https://github.com/zephyrproject-rtos/zephyr/issues/77331#issuecomment-2303533473 :) I think using an `alias` is a simple way to solve this. But besides that, note also the erase alignment restriction on flash NOR memories, I added a patch in the same comment.

**Comment by nordic-segl** [comment]
I made changes to the negative_tests.
1. `zephyr_flash` is no longer used.
2. Test gets Flash start and size from `storage_partition`. Unfortunately, I haven't found general way to get these values - it depends on how DTS is constructed. Although, I don't have much experience with DTS.
3. I tested two Nordic target and I see differences in flash driver behaviour. Other tests are done in MRAM driver than in RRAM driver.

**Review by de-nordic — APPROVED** [review]

**Comment by gbarkadiusz** [comment]
@nordic-segl Please take a look at https://github.com/zephyrproject-rtos/zephyr/issues/77331#issuecomment-2306807150

**Review by gbarkadiusz — APPROVED** [review]
Looks good. Tested out on frdm and ite board.

**Pull request merged**
