### PR TITLE
samples: metairq_dispatch: Ensure large enough queues

### LINKED ISSUE #54610: samples: kernel: metairq_dispatch: sample.kernel.metairq_dispatch hangs
**Describe the bug**
The samples/kernel/metairq_dispatch/sample.kernel.metairq_dispatch hangs sometimes

Observed for:
- nrf5340dk_nrf5340_cpunet

**To Reproduce**
1. have nrf5340dk_nrf5340_cpunet connected
2. go to your zephyr dir
3. call ./scripts/twister -T samples/kernel/metairq_dispatch -p nrf5340dk_nrf5340_cpunet --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2023-02-08T01:29:10.664Z] [0mERROR   - *** Booting Zephyr OS build v3.3.0-rc2-44-g461a13c085de ***[0m
[2023-02-08T01:29:10.664Z] [0mI: Starting Thread0 at priority -2[0m
[2023-02-08T01:29:10.664Z] [0mI: Starting Thread1 at priority -1[0m
[2023-02-08T01:29:10.664Z] [0mII: ERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mMERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0mERROR: Queue full, event dropped![0m
[2023-02-08T01:29:10.664Z] [0m0 T0 mirq 2 disp 3 proc 2 real 5[0m
[2023-02-08T01:29:10.664Z] [0mI: M6 T0 mirq 100 disp 2873 proc 0 real 0[0m
[2023-02-08T01:29:10.664Z] [0mI: M8 T0 mirq 1880 disp 2894 proc 3 real 3[0m
[2023-02-08T01:29:10.664Z] [0mI: M9 T1 mirq 1880 disp 3019 proc 2 real 2[0m
[2023-02-08T01:29:10.664Z] [0mI: M10 T1 mirq 1880 disp 3142 proc 3 real 3[0m
[2023-02-08T01:29:10.664Z] [0mI: M30 T1 mirq 793 disp 1389 proc 3 real 3[0m
[2023-02-08T01:29:10.664Z] [0mI: M32 T1 mirq 792 disp 1513 proc 1 real 1[0m
[2023-02-08T01:29:10.664Z] [0m: Starting Thread2 at priority 0[0m
[2023-02-08T01:29:10.664Z] [0mI: M1 T2 mirq 2 disp 3737 proc 1 real 1[0m
[2023-02-08T01:29:10.664Z] [0mI: M3 T2 mirq 2 disp 3842 proc 0 real 0[0m
[2023-02-08T01:29:10.664Z] [0mI: M4 T2 mirq 102 disp 3954 proc 1 real 1[0m
[2023-02-08T01:29:10.664Z] [0mI: M5 T2 mirq 101 disp 4074 proc 3 real 3[0m
[2023-02-08T01:29:10.664Z] [0mI: M31 T2 mirq 793 disp 2210 proc 3 real 3[0m
[2023-02-08T01:29:10.664Z] [0mI: Starting Thread3 at priority 1[0m
[2023-02-08T01:29:10.664Z] [0mI: M2 T3 mirq 2 disp 4431 proc 0 real 0[0m
[2023-02-08T01:29:10.664Z] [0m[0m
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.15.1
 - Commit SHA or Version used: v3.3.0-rc2-44-g461a13c085de

### PR DESCRIPTION
**Pull request by tmon-nordic**
Make queues used in metairq dispatch sample capable of storing all generated messages. This prevents seemingly random hangs that tend to happen with some random seeds.

Fixes: #54610

### CODE REVIEW

**Comment by tmon-nordic** [comment]
@andyross  My biggest worry is that increasing the queue sizes essentially makes this sample no longer suitable for detecting actual timer problems... Please take extra scrutiny during review, if my worry is real then it is better to reject this PR than to "only make the CI green".

**Comment by andyross** [comment]
It looks harmless enough to me.  The goal of the test wasn't timer behavior, it was to exercise preemption paths and check that the resulting latencies look correct.

But what's the actual failure being detected?  From my read, the code will just drop a message when the msgq is full, and log a message to that effect.  That should be benign, no?   Where's the hang coming from?  Is there maybe a bug with the sample regex at the twister layer that gets confused?  If the sample will hang on this condition, then I agree that this is a bug somewhere else we should find and fix.

**Comment by tmon-nordic** [comment]
> But what's the actual failure being detected? From my read, the code will just drop a message when the msgq is full, and log a message to that effect. That should be benign, no? Where's the hang coming from? Is there maybe a bug with the sample regex at the twister layer that gets confused? If the sample will hang on this condition, then I agree that this is a bug somewhere else we should find and fix.

In `dev_timer_expired()` the `msg_seq` global is increased unconditionally. The hang comes from the `if (m->seq == MAX_EVENTS - 1)` check in `record_latencies()`. If the `MAX_EVENTS - 1` message is dropped either inside `dev_timer_expired()` function (i.e. not making it to `hw_msgs`) or inside `metairq_fn()` function (i.e. not making it to `threads[m.target].msgq`, then the sample won't ever end.

Alternative approach to preventing the hang caused by `dev_timer_expired()` dropping the message would be to increment `msg_seq` only after successfully posting it to `hw_msgs`. This would significantly improve the situation, but there is no guarantee that the message will make it to `threads[m.target].msgq` (however the probability of message not making it to `threads[m.target].msgq` with queue length being 16 sounds really really small).

**Review by andyross — APPROVED** [review]
Gotcha.   OK, I'm sold.

If you want to respin, it wouldn't hurt to put that explanation into a comment somewhere and turn the existing soft error into something fatal, since it turns out to be unrecoverable.  But just making room seems like a fine workaround given that it's just a sample that's explaining unrelated features.

I'll leave a +1 in any case.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
