### PR TITLE
manifest: mcuboot upgrade (fixes cmsis include for Cortex-M)

### PR DESCRIPTION
**Pull request by nvlsianpu**
Version which fixes cmsis include for all ARM CORTEX-M SoCs

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
CI was green (using https://github.com/zephyrproject-rtos/mcuboot/pull/10)
Original PR merged in upsteram, and synchronized to zephr-rtos fork.

**Review by mnkp — APPROVED** [review]
Thanks!

**Comment by nandojve** [comment]
HI Andrzej, I discover couple hours ago that a missing `#include <devicetree.h>` on` soc.h` give me that same problem at MCUboot.

**Comment by nvlsianpu** [comment]
@nandojve Did I understood you well - Does this patch solves the issue you described above?

**Comment by nvlsianpu** [comment]
@carlescufi Please review in your convenience.

**Comment by nandojve** [comment]
> @nandojve Did I understood you well - Does this patch solves the issue you described above?

Yes, patch solves and works without any doubts.

**Comment by mnkp** [comment]
Needs to be rebased.

**Comment by nvlsianpu** [comment]
rebased

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
