### PR TITLE
drivers: flash: spi_nor: unconditionally provide config pointer

### LINKED ISSUE #34716: flash: spi_nor: build fails when CONFIG_SPI_NOR_SFDP_RUNTIME is enabled
The spi_nor driver fails to build when the CONFIG_SPI_NOR_SFDP_RUNTIME option is enabled.

Here is the build error message:
```
drivers/flash/spi_nor.c: In function 'spi_nor_configure':
drivers/flash/spi_nor.c:1071:6: error: 'cfg' undeclared (first use in this function)
  if (cfg->has_lock != 0) {
```

### PR DESCRIPTION
**Pull request by pabigot**
Information about which block protect bits are set on power-up is not inferable from SFDP content, so we need the devicetree config pointer to get the has-lock property value even when SFDP data is read at runtime.

Fixes build error with `CONFIG_SPI_NOR_SFDP_RUNTIME=y`.

Fixes #34716

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

**Comment by simonguinot** [comment]
Hi @pabigot,

Thanks for taking care of this bug.

This patch is not good enough. You also need to move the `has_lock` member out of the `#ifndef CONFIG_SPI_NOR_SFDP_RUNTIME` statement in `struct spi_nor_config`.

Else, with your current patch, we have the following error when CONFIG_SPI_NOR_SFDP_RUNTIME is enabled:
```
drivers/flash/spi_nor.c: In function 'spi_nor_configure':
drivers/flash/spi_nor.c:1073:9: error: 'const struct spi_nor_config' has no member named 'has_lock'
  if (cfg->has_lock != 0) {
         ^~
drivers/flash/spi_nor.c:1080:36: error: 'const struct spi_nor_config' has no member named 'has_lock'
    rc = spi_nor_wrsr(dev, rc & ~cfg->has_lock);
```

**Comment by simonguinot** [comment]
#34716

**Comment by pabigot** [comment]
> This patch is not good enough. You also need to move the `has_lock` member out of the `#ifndef CONFIG_SPI_NOR_SFDP_RUNTIME` statement in `struct spi_nor_config`.

@simonguinot Thanks; fixed, and build checked against variant:
```
#CONFIG_SPI_NOR_SFDP_MINIMAL=y
#CONFIG_SPI_NOR_SFDP_DEVICETREE=y
#CONFIG_SPI_NOR_SFDP_RUNTIME=y
```

**Review by nvlsianpu — APPROVED** [review]

**Review by simonguinot — APPROVED** [review]
Build is now OK with all the SFDP Kconfig configurations. Thanks.

**Pull request merged**
