### PR TITLE
Dw i3c master pr

### PR DESCRIPTION
**Pull request by samitsingh7**
Added Designware I3C master driver.
The following features are supported:-

- Dynamic Address Assignment
- CCC
- I3C private read/write transfers
- I2C legacy support
- Supports SDR mode only

### CODE REVIEW

**Comment by samitsingh7** [comment]
I would like to have the stale label removed and requesting to add dev-review label.

**Comment by samitsingh7** [comment]
I would like to have the stale label removed and requesting to add dev-review label.

**Comment by dcpleung** [comment]
> @dcpleung I would like to have the stale label removed and requesting to add dev-review label.

Added `dev-review` label.

**Review by XenuIsWatching — CHANGES_REQUESTED** [review]
Hey! thanks for the PR, I had the time to go line by line of this PR, but I think there's a lot of issues where that need to address 'first' before it can go to the dev-review meeting (if ever needed). This is also a duplicate of another PR which appears to have all the issues present fixed, https://github.com/zephyrproject-rtos/zephyr/pull/64528 . I know that is 'draft' PR but I expect it to be published in the next few weeks once through testing is complete which is already in progress right now.
The only functional difference I see from this PR an that one is the use of the `DEVICE_MMIO` for the base pointer to the IP. I'm actually not familiar with that, is there a reason why that is needed and what exactly does that give you?
There is also the intel fpga dtsi commit for that in-tree board. I can see if that can be cherry-picked in to that PR.

Going through this PR, I see a lot of issues here and there that are addressed in https://github.com/zephyrproject-rtos/zephyr/pull/64528 along with more feature set implementation in that PR although it looks we both used a similar base code as a starting point 😉 . Would you be able to try out and review https://github.com/zephyrproject-rtos/zephyr/pull/64528 ?

**Comment by samitsingh7** [comment]
Hi @XenuIsWatching, @dcpleung -  I would like to have the stale label removed on this PR.

Thank you!

**Comment by XenuIsWatching** [comment]
> Hi @XenuIsWatching, @dcpleung - I would like to have the stale label removed on this PR.
> 
> Thank you!

What do you have planned in comparison with the other PR?
This PR is missing a lot that the other PR already has.
Are you planning on using this same PR to enable for the intel fpga?

**Pull request closed without merging**
