### PR TITLE
drivers/gpio: stm32: Fix gpio_stm32_configure

### LINKED ISSUE #12544: commit 2fb616e broke I2C on Nucleo F401RE + IKS01A2 shield
I2C is not working on IKS01A2 shield when the 2fb616e commit is there.
If I revert it then starts to work again.

To reproduce it you need to use theIKS01A2 shield on top of a Nucleo board.
The test to be used is currently not merged (#12398)

### LINKED ISSUE #12609: ext: stm32: revert fix https://github.com/zephyrproject-rtos/zephyr/pull/8762
**Describe the bug**
A fix was introduced in ext to fix LL API function.
After analysis, it appears that function is actually correct, and issue was actually in parameters provided that didn't match the API.
Revert fix introduced in API and fix use of API (in drivers/i2s/i2s_ll_stm32.c)

**To Reproduce**
NA

**Expected behavior**
NA

**Impact**
Wrong waveform generated

**Screenshots or console output**
NA

**Environment (please complete the following information):**
NA

**Additional context**
In drivers/i2s/i2s_ll_stm32.c, function `LL_RCC_PLLI2S_ConfigDomain_I2S`, parameter `PLLR` should be one of:
  * @param  PLLR This parameter can be one of the following values:
```
  *         @arg @ref LL_RCC_PLLI2SR_DIV_2
  *         @arg @ref LL_RCC_PLLI2SR_DIV_3
  *         @arg @ref LL_RCC_PLLI2SR_DIV_4
  *         @arg @ref LL_RCC_PLLI2SR_DIV_5
  *         @arg @ref LL_RCC_PLLI2SR_DIV_6
  *         @arg @ref LL_RCC_PLLI2SR_DIV_7
```
which are actually already shifted values.

### PR DESCRIPTION
**Pull request by erwango**
Behavior of function gpio_stm32_configure has been modified
during driver factorization. Various gpio settings (speed, mode, ..)
are applied conditionally while they used to be applied in sequence,
unconditionally before this change. As a consequence some
combinations of configurations are no more applied (like speed for
alternate mode). This of course has impact in some use cases.
Rework functions in order to apply settings unconditionally. Take
advantage of the change to reduce code size.

This change impacts all SoCs except F1 series.

Fixes #12544

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by avisconti** [comment]
@erwango 
I just re-tested again microphone sample with this commit and it works.
Then I took a look to the fix and seems that you went back to the simplicity of the original code, but
using the LL APIs (which is good). I wonder what happens in case of STM32F1X series though.

**Comment by erwango** [comment]
>I wonder what happens in case of STM32F1X series though.

@avisconti, I spent sometime looking at doing more simplification and there should be room for it, but at this step, as I am not able to do sufficient non regression on F1 based boards, I don't want to take the time and risk of doing additional changes.

**Review by avisconti — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
I don't know enough about STM32 to comment on the implementation, but the problem I encountered is resolved by this patch.

**Comment by avisconti** [comment]
@erwango 
I noticed that in the commit message you are referring to the wrong PR!
Correct one should be #12544 I think.
Is it correct?

**Comment by erwango** [comment]
@avisconti, Txs I did the mistake indeed but fixed only the commit indeed.

**Review by ydamigos — APPROVED** [review]

**Pull request merged**
