### PR TITLE
tests: k_heap api: add tests for k_heap_api

### LINKED ISSUE #29654: k_heap APIs have no tests
**Describe the bug**
We have tests for underlying `sys_heap`, but no tests for `k_heap`. Need test case coverage for all these APIs with full code coverage.

**To Reproduce**
```
cd tests
grep -nIRC3 k_heap_alloc
grep -nIRC3 k_heap_free
```

**Expected behavior**
Test case coverage of these functions.

**Impact**
Who knows if it actually works?

### PR DESCRIPTION
**Pull request by megatherium-95**
Add test cases to test k_heap_alloc() and k_heap_free() APIs

Fixes #29654

Signed-off-by: iva kik <megatheriumiva@gmail.com>

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Looks fine.  Not sure this test (which is really just of the wrapper APIs, we exercise the underlying sys_heap elsewhere) really needs to stand alone though.  You could just as easily wrap these as new cases into the existing mem_heap test.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
@megatherium-95 can you please add Copyright lines to the C files you introduced?

```
Run if [ -s ./artifacts/report.txt ]; then
Error: * scan/tests/kernel/mem_heap/k_heap_api/src/main.c missing copyright.
* scan/tests/kernel/mem_heap/k_heap_api/src/test_kheap.h missing copyright.
* scan/tests/kernel/mem_heap/k_heap_api/src/test_kheap_api.c missing copyright.
Error: Process completed with exit code 1.
```

**Comment by megatherium-95** [comment]
Is there a sample that I can use?

**Comment by andrewboie** [comment]
> Is there a sample that I can use?

Literally look at any C file in this project for an example.

This is the only thing preventing merge of this PR.

**Pull request merged**
