### PR TITLE
kernel/timer: fix period argument clamp handling

### LINKED ISSUE #54755: small timer periods take twice as much time as they should
**Describe the bug**

It is impossible to have single-tick timer periods. The effective minimum
period length is always 2 ticks.

**To Reproduce**

Run tests/kernel/timer/timer_behavior/ with CONFIG_TIMER_TEST_PERIOD=10000
and CONFIG_SYS_CLOCK_TICKS_PER_SEC=100.

**Additional context**

Commit 7832738ae985 ("kernel/timeout: Make timeout arguments an opaque
type") introduced the idea that "`z_add_timeout()` always adds one to the
incoming tick count to round up to the next tick, but the period interval
is always guaranteed to be reset from within the timer ISR, so no round up
is desired. Subtract one."

Then commit 3e729b2b1c52 ("kernel/timer: Correctly clamp period argument")
attempted to correct the fact that subtracting 1 to a single tick period
turned it into a K_NO_WAIT which means "never" here. So it clamped the
timeout value to 1 which effectively made it to 2 after the timeout
round-up.

This subtraction and clamping are simply misplaced. They should be 
performed when it is decided to register a new timeout i.e. in
`z_timer_expiration_handler()`.

### PR DESCRIPTION
**Pull request by npitre**
Commit 3e729b2b1c52 ("kernel/timer: Correctly clamp period argument")
increased the lower limit to 1 so that it wouldn't conflict with a
K_NO_WAIT. But in doing so it enforced a minimum period of 2 ticks.
And the subtraction must obviously be avoided if the period is zero, etc.

Instead of doing this masquerade in k_timer_start(), let's move the
subtraction and clamping in z_timer_expiration_handler() right before
registering a new timeout. It makes the code cleaner, and then it is
possible to have single-tick periods again.

Whith this, timer_jitter_drift in tests/kernel/timer/timer_behavior does
pass with any CONFIG_SYS_CLOCK_TICKS_PER_SEC value, even when the tick
period is equal or larger than the specified timer period for the test
which failed the test before.

Fixes #54755

### CODE REVIEW

**Comment by npitre** [comment]
Looks like CI failure is related to bug #54720 which has nothing to do with
this PR.

**Review by peter-mitsis — DISMISSED** [review]
Nice work! :)

**Review by ceolin — DISMISSED** [review]

**Review by andyross — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by npitre** [comment]
Repushed to restart CI now that the ARC failure workaround is merged.

**Comment by npitre** [comment]
@peter-mitsis @ceolin @andyross @teburd Your reviews were dismissed. Please re-approve.

**Review by andyross — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

**Pull request merged**
