### PR TITLE
Driver: Serial STM32: Fix how uart_irq_is_pending() works

### PR DESCRIPTION
**Pull request by Benichou34**
uart_stm32_irq_tx_enable/disable() functions use TC IRQ.
But uart_stm32_irq_tx_ready() function use TXE IRQ.
So uart_stm32_irq_tx_ready() function alway return 0, because TXE flag is never enabled by uart_stm32_irq_tx_enable.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for this proposition.

Though, in your description, you're mixing TXE flag and TXE IRQ.
TXE flag will always be set irrespective of TXEIE (interrupt enable) bit. According to reg manual 'This bit is set by hardware when the content of the TDR register has been transferred into
the shift register.'
TXE irq will be triggered depending on TXEI (configured by LL_USART_Enable/DisableIT_TXE()).

Though, there is indeed and issue in function uart_stm32_irq_is_pending, which is checking TXE. 
It seems this function is not actually used, but this should be fixed.

Choice of using TC instead of TXE IRQ was initially made to limit overruns.
Ideally, we should use TXE during transmission and TC after transmitting the last char.
I think we'll be able to rework that part once https://github.com/zephyrproject-rtos/zephyr/pull/10820 is available.

Getting back to what you described:
uart_stm32_irq_tx_ready always return zero. 
this would mean that TXE flag is 0: Data not transferred to the shift register yet > On going.

What is the exact issue you're facing?

**Comment by Benichou34** [comment]
As you say, the issue is in function uart_stm32_irq_is_pending, which is checking TXE by calling LL_USART_IsEnabledIT_TXE(). This function is used by the bluetooth H4 driver, in bt_uart_isr() function.
This issue causes an infinite loop in the H4 driver.

**Comment by erwango** [comment]
@Benichou34 ,

Ok, I wasn't aware of any use of this function on STM32, but this is indeed a bad math from my side.
Can you check if fixing LL_USART_IsEnabledIT_TXE() to LL_USART_IsEnabledIT_TC() fixes your issue?

**Comment by Benichou34** [comment]
@erwango 
Sorry for my slow answer.
I have changed LL_USART_IsEnabledIT_TXE() to LL_USART_IsEnabledIT_TC(), and that seems to fixes the issue. Do you want that I update the commit?

**Comment by erwango** [comment]
@Benichou34, yes, let's go with that fix, thanks.

**Comment by Benichou34** [comment]
@erwango
I have updated the commit.

**Review by erwango — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
I might have approved too quickly here.
For coherency, it might be better to check LL_USART_IsActiveFlag_TC instead of LL_USART_IsActiveFlag_TXE of we're now using LL_USART_IsEnabledIT_TC.
Can you try this if working and do the change?

**Comment by Benichou34** [comment]
Hello @erwango 
We tested with LL_USART_IsActiveFlag_TC instead of LL_USART_IsActiveFlag_TXE and this is ok, the change working.
I have updated the commit.

**Review by erwango — APPROVED** [review]

**Comment by pfalcon** [comment]
@erwango: I eyeballed this patch, but not the overall driver code. I don't use irq_is_pending() in console code, so that might explain why it was inconsistent. As long as this patch touches only irq_is_pending, I guess it can't do harm.

But might ping @jarz-nordic re: if they use irq_is_pending() in the shell backend.

@Benichou34:

> We tested ...

It would be useful to know how/what exactly you tested. The standard tests would be samples/subsys/console/echo and any sample with Zephyr shell enabled.

**Comment by pfalcon** [comment]
Updated title to correspond to the current contents of the patch.

**Pull request merged**
