### PR TITLE
 Add json-c external module

### LINKED ISSUE #59303: Add json-c as external module
## Origin

JSON-C implements a reference counting object model that allows you to easily construct JSON objects in C, output them as JSON formatted strings and parse JSON formatted strings back into the C representation of JSON objects. It aims to conform to [RFC 7159](https://tools.ietf.org/html/rfc7159).

URL: https://github.com/json-c/json-c

## Purpose

json-c provides friendly API to frame and parse json messages. It's well known in the Linux world and bringing it helps,

- building cross platform (compatible between Linux and zephyr apps)
- Friendly dynamic processing of complex json objects

Comparing with available native json data handling, json-c helps,
- framing json payloads using heap memory
- No need to statically pre-built json structures

## Mode of integration

Mode of integration: External module
Repository name: json-c
Reason: To keep in sync with the open source version of json-c, which helps rebasing

## Maintainership

- json-c open source community
- @ssekar15 
- @parthitce 

## Pull Request

Yet to prepare a final one based on https://github.com/linumiz/json-c/tree/zephyr

## Description

Please refer to https://json-c.github.io/json-c/

What is its primary functionality?
- JSON parsing and framing with friendly API's with extended functionality

What problem are you trying to solve?
- JSON processing with existing native implementation needs static definition of the json structures
- Dynamic parsing and framing of json objects

Why is this the right component to solve it?
- Predominant in use in Linux world and well known for it's stability
- ~18K footprint in memory (text + data + bss)

## Dependencies

What other components does this package depend on?
- None

Will the Zephyr project have a direct dependency on the component, or
will it be included via an abstraction layer with this component as a
replaceable implementation?
- We will have abstraction for file handling if needed based on LFS

## Revision

Version or SHA you would like to integrate initially
- https://github.com/json-c/json-c/releases/tag/json-c-0.16-20220414

## License

Please use an SPDX identifier (https://spdx.org/licenses/), such as
``BSD-3-Clause``
- https://github.com/json-c/json-c/blob/master/COPYING
- MIT License

### PR DESCRIPTION
**Pull request by parthitce**
- add initial support for json-c external module
- current dependency points to linumiz/fork of json-c

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/59303

Note: Couldn't re-open previous PR https://github.com/zephyrproject-rtos/zephyr/pull/60039, so creating a new one.

### CODE REVIEW

**Comment by parthitce** [comment]
@nashif @mrfuchs @kartben @stephanosio Please have a look.

**Comment by bjarki-trackunit** [comment]
How does this fit with the existing native zephyr JSON implementation, see [zephyr/data/json.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/data/json.h) ?

**Comment by parthitce** [comment]
> How does this fit with the existing native zephyr JSON implementation, see [zephyr/data/json.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/data/json.h) ?

json-c provides rich set of API's, which helps in building complex json structure with much flexibility. Using as an external module from well mature implementation of RFC7159. It can co-exist with existing native implementation json in zephyr.

**Comment by bjarki-trackunit** [comment]
We definitely should not have multiple json libraries in tree :) if you want this library added, it must be implemented as a module, exposing the APIs through `zephyr/json/json.h`, naturally, tests need to be added to ensure it builds with all supported platforms, and in tree use of the existing API needs to be extended.

The license of json-c is not apache 2.0, so you will have to bring it up at a TSC meeting to make sure the license is agreeable.

Then there is the question of size, is it optimized for embedded platforms? it seems to target android and unix. and can it be configured to run without dynamic memory allocation?

**Comment by parthitce** [comment]
> We definitely should not have multiple json libraries in tree :)
json-c will be external module and it will be out-of-tree module. Considering libc as an example here, zephyr has options for minimal/picolibc/newlib, where pico and newlib is external. It's a choice for the use to consume which version to use based on needs. Similarly, native json implementation in zephyr can be considered as minimal and external json-c can be considered as luxury version.

> if you want this library added, it must be implemented as a module, exposing the APIs through `zephyr/data/json.h`,
json-c is already an external module from another open source project. Consuming the API's from json-c library makes sense to me instead of pulling and maintaining the API's inside the zephyr's native implementation.

> naturally, tests need to be added to ensure it builds with all supported platforms, and in tree use of the existing API needs to be extended.
We have few conflicts with hal_espressif for json.  json-c by itself isn't bound to any architecture or SoC platforms, so I will be fixing the CI.

> 
> The license of json-c is not apache 2.0, so you will have to bring it up at a TSC meeting to make sure the license is agreeable.
The main idea behind this issue https://github.com/zephyrproject-rtos/zephyr/issues/59303 is to discuss the license and also the possibility to integrate json-c as external module. To add, json-c is `MIT License` which is compatible with Apache 2.0 AFAIK. Happy to discuss this with TSC.

> 
> Then there is the question of size, is it optimized for embedded platforms? it seems to target android and unix. and 
I will run some stats with native json and json-c to prepare example json and share soon.

> can it be configured to run without dynamic memory allocation?
No, json-c use dynamic memory for parsing and also for preparing  json objects, which can be freed/dropped. But why? Shouldn't a library use memory from heap?

**Comment by bjarki-trackunit** [comment]
> json-c is already an external module from another open source project. Consuming the API's from json-c library makes sense to me instead of pulling and maintaining the API's inside the zephyr's native implementation.

Please read https://docs.zephyrproject.org/latest/develop/modules.html if you haven't already as it is better than me summarizing it :)

> No, json-c use dynamic memory for parsing and also for preparing json objects, which can be freed/dropped. But why? Shouldn't a library use memory from heap?

Heaps are optional on embedded platforms, and are often not used. Instead, static objects and buffers, and pools of objects are allocated at build time, see `net_pkt` and `net_pkt_buf` and thread stacks for example.

**Comment by parthitce** [comment]
Removing stall and reopening the PR again. Although I couldn't spend time on this so far, will be able to resume soon and planned for August to address the queries. Thanks.

**Comment by parthitce** [comment]
@bjarki-andreasen 
> > json-c is already an external module from another open source project. Consuming the API's from json-c library makes sense to me instead of pulling and maintaining the API's inside the zephyr's native implementation.
> 
> Please read https://docs.zephyrproject.org/latest/develop/modules.html if you haven't already as it is better than me summarizing it :)

Thanks, discussions started with the tagged issue to come to a common ground about which JSON implementation to keep in zephyr.

> 
> > No, json-c use dynamic memory for parsing and also for preparing json objects, which can be freed/dropped. But why? Shouldn't a library use memory from heap?
> 
> Heaps are optional on embedded platforms, and are often not used. Instead, static objects and buffers, and pools of objects are allocated at build time, see `net_pkt` and `net_pkt_buf` and thread stacks for example.

I understand that heap is optional in the context of zephyr. Does this also applies to external modules? To add, I also adjusted the modules as optional under submanifest now.

**Comment by parthitce** [comment]
Closing this PR. see https://github.com/zephyrproject-rtos/zephyr/issues/59303#issuecomment-2335163121 for more details.

**Pull request closed without merging**
