### PR TITLE
dma: hda: calculate correct size if block_count > 1

### PR DESCRIPTION
**Pull request by juimonen**
This will allow to configure hda dma if block_count > 1 provided

Signed-off-by: Adrian Bonislawski <adrian.bonislawski@intel.com>
Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
This fixes https://github.com/thesofproject/sof/issues/6709 SOF bug.

**Comment by kv2019i** [comment]
@teburd @juimonen So this basicly comes down to where we have handle the difference between SG-enabled and non-SG DMA. Currently the SOF side client code uses same logic to talk to both DWDMA and HDDMA:
https://github.com/thesofproject/sof/blob/main/src/audio/dai-zephyr.c#L874

... we could add code on SOF/client side to combine the DMA chunk/periods into one DMA block, and pass that to Zephyr dma_config(), but then we'd need separate codepaths based on the DMA type.

I don't see a readily usable generic attrribute how to ask the DMA driver whether it supports SG or not, so not sure how to best tackle this.

**Review by ujfalusi — APPROVED** [review]
Fixes the HDA audio corruption on my devices:

Tested-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>

**Review by softwarecki — APPROVED** [review]

**Review by teburd — CHANGES_REQUESTED** [review]
As noted in the deleted assert here, HDA isn't a scatter gather DMA, and I want to better understand why it is we need to pretend it is one.

My thoughts go to wanting to communicate with dma_get_attribute that this DMA supports a single block (no scatter gather) rather than trying to have it pretend to be a scatter gather DMA. This could be useful more generally as the block configs are typically statically allocated in a fixed size pool and that could be useful information provided to SoF code and other Zephyr users.

@juimonen is looking at why it is that SOF wants to use a period count of 2 when using HDA and if using one is acceptable. Based on the feedback we can either add a dma attribute describing the number of acceptable blocks replacing what sof has in its plat_config struct today perhaps *or* improving this with asserts to validate that the blocks are sequential, non-overlapping, and without gaps.

**Comment by ujfalusi** [comment]
@teburd, if you push the decision to use or not use up to users then _all_ drivers using DMA must have path to support SG and non SG operation which is going to be ugly over time.
In Linux the DMAengine API for peripheral servicing is using SG list to describe the buffer in RAM. The DMA drivers itself will have to deal with the case if they don't support SG natively but given a list which has more than one entry.
Client drivers are using generic code for the DMA, but yes, some driver which is known to exist on a specific platform with a specific DMA can (and indeed, do) optimize the list they provide.
The point is that users of the DMA API should not be concerned about different DMAs having different capabilities to maintain portability and be able to use generic code.

imho.

**Comment by teburd** [comment]
> @teburd, if you push the decision to use or not use up to users then _all_ drivers using DMA must have path to support SG and non SG operation which is going to be ugly over time. In Linux the DMAengine API for peripheral servicing is using SG list to describe the buffer in RAM. The DMA drivers itself will have to deal with the case if they don't support SG natively but given a list which has more than one entry. Client drivers are using generic code for the DMA, but yes, some driver which is known to exist on a specific platform with a specific DMA can (and indeed, do) optimize the list they provide. The point is that users of the DMA API should not be concerned about different DMAs having different capabilities to maintain portability and be able to use generic code.
> 
> imho.

Different DMAs already have different capabilities. dma_get_attribute was added to deal with some of those already. Why not continue down that path? I'm suggesting an attribute that describes the acceptable block count which is useful regardless of HDA or GPDMA or other DMAs in Zephyr, it just happens to enable HDA to inform the caller there's only 1 block accepted, which is true! There's also a limit in Zephyr for the number of blocks that can be setup anyways as these are allocated in a static pool. This same API enables communicating that in a nice way.

e.g. from SoF's dai-zephyr.c something like... 

``` c
int res = dma_get_attribute(dev,  DMA_ATTR_MAX_BLOCK_COUNT, &max_block_count);

/* Setup sg list up to MIN(max_block_count, period_count) here... */
...

```

**Comment by juimonen** [comment]
> @juimonen I guess this can be dropped now?

yes.

**Review by marcinszkudlinski — APPROVED** [review]

**Comment by kv2019i** [comment]
Ping @juimonen

**Review by softwarecki — APPROVED** [review]

**Pull request closed without merging**
