### PR TITLE
boards: em_starterkit: stop overriding GPIO_INIT_PRIORITY

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Repro with `west build -p -b em_starterkit_em11d  -T tests/drivers/build_all/gpio/drivers.gpio.build`

---

This was introduced long time ago during a big priority refactoring, with the current priority changes it should not be necesary anymore, the current value is causing some build fail in the weekly test.

Fixes the following breakage:
```
$ west build -p -b em_starterkit_em11d -T tests/drivers/build_all/gpio/drivers.gpio.build
...
ERROR: /test/nct3807_alert_1 POST_KERNEL 52 51 < /test/gpio@deadbeef POST_KERNEL 70 47
ninja: build stopped: subcommand failed.
```

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]

**Review by abrodkin — DISMISSED** [review]
Thanks for the fix, but could you please provide some more details on how that gets in the way during your build test? Preferably with that information in both the PR and the commit comment.

**Comment by fabiobaltieri** [comment]
> Thanks for the fix, but could you please provide some more details on how that gets in the way during your build test? Preferably with that information in both the PR and the commit comment.

Sure, done.

**Comment by ruuddw** [comment]
I don't believe there's a reason to have the GPIO init priority set difference from the default for this board so can probably be safely removed as proposed.
But, it is not clear to me why the priority can't be set to '70', or what problem this causes. Do you have an explanation or pointer? Also, I believe there are many boards setting the priority - shouldn't more boards be updated?

**Comment by fabiobaltieri** [comment]
Updated to drop the last two overrides as well, thanks for pointing it out.

**Review by ruuddw — APPROVED** [review]

**Comment by ruuddw** [comment]
Thanks, at least the ARC boards are consistent now (there are many more boards defining the GPIO_INIT_PRIO...).

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@abrodkin could you unblock? This is causing CI breakages in other PRs.

**Comment by fabiobaltieri** [comment]
@abrodkin heya, sorry I'm going to dismiss and submit since this is blocking other PRs. If there's something pending reach out, I'll follow up separately.

**Pull request merged**
