### PR TITLE
pwm: Added MCUX_PWM support for MIMXRT1021

### PR DESCRIPTION
**Pull request by SoftubeBask**
Added PWM to config for MIMXRT1021 after testing and verifying it works.

Signed-off-by: Christoffer Bask <christoffer@softube.com>

### CODE REVIEW

**Review by dleach02 — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@SoftubeBask Thank you for your contribution. The below is flagged as an error during Compliance Check.

`UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Added MCUX_PWM support for MIMXRT1021, the same as for 1052, 1062 and 1064."`

Maybe you could add a `pwm` as the `[subsystem]:`

**Comment by SoftubeBask** [comment]
Is it okay now? I scrrewed up with the commits, though it was the commit message that was wrong and not the subject for the PR. Do i need to squash the commits or it's get taken care of with the merge later on?

**Comment by dleach02** [comment]
@SoftubeBask you should clean up the commit history with that last "merge commit"

**Comment by dleach02** [comment]
@SoftubeBask please do a rebase and push to see if we can clean up the CI problems?

**Comment by SoftubeBask** [comment]
Yes, sorry. I will see if I can get a colleague to help me sort it out so it's done correctly

**Comment by dleach02** [comment]
@SoftubeBask, your commit message needs to follow the format of [subsystem]: [subject] (and should not start with literal subsys:). Please correct that and you should then pass CI to allow us to merge this.

see https://docs.zephyrproject.org/latest/contribute/#commit-guidelines

**Comment by SoftubeBask** [comment]
I've updated the commit message, is it ok now?

**Comment by dleach02** [comment]
> I've updated the commit message, is it ok now?

I'll let CI verify...

**Comment by SoftubeBask** [comment]
Fixed the error that the title was to long (as long as it's the title for the PR and not commit message the message was about)

**Comment by dleach02** [comment]
@SoftubeBask, sorry to ask again but can you rebase and push? The documentation error looks like an issue that was recently fixed.

**Comment by SoftubeBask** [comment]
Rebased, hopefully okay now. Thank you for your patience

**Comment by SoftubeBask** [comment]
Could this be pushed through now? @mmahadevan108 @dleach02

**Pull request merged**
