### PR TITLE
net: if: Make sure to update the prefix when it already exists

### PR DESCRIPTION
**Pull request by vaussard**
This is an issue that I found while using the TAHI test suite for RFC2640. Running test case _v6LC.1.3.2: Part A (Time Elapsed Between Fragments less than Sixty Seconds)_ would succeed the first time, but fail on follow-up runs. Zephyr uses the wrong destination address due to an expired prefix not being re-enabled in these follow-up runs.

It can happen that the prefix exists but has expired. In that case, `net_if_ipv6_prefix_add()` will not work as intended, because it will bail out without re-enabling the existing prefix. Call `net_if_ipv6_prefix_init()` when the prefix already exists, so that it is also updated with the latest data (length, lifetime, etc.).

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
I'm a bit confused, what exactly needs to get re-initialized in order to make your test work? The `net_if_ipv6_prefix_init` does not seem to reset any timeouts, and I'd expect all of the fields it sets to be already configures in a situation when `ipv6_prefix_find()` finds that particular prefix (if it has expired, it shoul've been removed, no?).

**Comment by vaussard** [comment]
Yes sorry, my explanation was not very clear.

The problem is not really with the prefix timeout. But the prefix returned by `ipv6_prefix_find()` can be expired (for example after a call to `prefix_lifetime_expired()`), i.e. `ifprefix->is_used` is false. If `net_if_ipv6_prefix_add()` does nothing more, the prefix will be left with `is_used` set to false, so it will not be used, which is wrong.

From what I can tell, `net_if_ipv6_prefix_add()` does not set the prefix timeout timer. This task looks to be done by calling `net_if_ipv6_prefix_set_timer()` from `handle_prefix_onlink()`. But it is not related to the current problem.

Here are some debug logs. On the 1st run, everything works as expected:

```
[00:00:51.900,000] <dbg> net_if.net_if_ipv6_prefix_add: (rx_q[0]): [0] interface 0x80822c4 prefix 3ffe:501:ffff:100::/64 added
[00:00:51.900,000] <dbg> net_ipv6.handle_prefix_onlink: (rx_q[0]): Interface 0x80822c4/1 add prefix 3ffe:501:ffff:100::/64 lifetime 270991360
[00:00:51.900,000] <dbg> net_ipv6.handle_prefix_onlink: (rx_q[0]): Interface 0x80822c4/1 update prefix 3ffe:501:ffff:100::/64 lifetime 270991360
[00:00:51.900,000] <dbg> net_if.net_if_ipv6_prefix_set_timer: (rx_q[0]): Prefix lifetime 270991360 sec
```

But on the 2nd run, the `if (ifprefix)` path is taken (`TEST` lines added by my-self inside the if()):

```
[00:01:54.420,000] <dbg> net_if.net_if_ipv6_prefix_add: (rx_q[0]): TEST: interface 0x80822c4 prefix 3ffe:501:ffff:100::/64 found
[00:01:54.420,000] <dbg> net_if.net_if_ipv6_prefix_add: (rx_q[0]): TEST: infinite: 0; used: 0
[00:01:54.420,000] <dbg> net_ipv6.handle_prefix_onlink: (rx_q[0]): Interface 0x80822c4/1 add prefix 3ffe:501:ffff:100::/64 lifetime 270991360
[00:01:54.420,000] <dbg> net_ipv6.handle_prefix_onlink: (rx_q[0]): Interface 0x80822c4/1 update prefix 3ffe:501:ffff:100::/64 lifetime 270991360
[00:01:54.420,000] <dbg> net_if.net_if_ipv6_prefix_set_timer: (rx_q[0]): Prefix lifetime 270991360 sec
```

We can see that the prefix lifetime is correctly set, but notice the `is_used` set to 0. As a result, the prefix will not be used and the test case fails.

But now I realize that the problem is maybe with `ipv6_prefix_find()` returning an expired prefix. It tests `!ipv6->unicast[i].is_used` but do not test `!ipv6->prefix[i].is_used`. I experimented this idea with the following patch and it also works:

```
--- a/subsys/net/ip/net_if.c
+++ b/subsys/net/ip/net_if.c
@@ -2152,7 +2152,7 @@ static struct net_if_ipv6_prefix *ipv6_prefix_find(struct net_if *iface,
        }
 
        for (i = 0; i < NET_IF_MAX_IPV6_PREFIX; i++) {
-               if (!ipv6->unicast[i].is_used) {
+               if (!ipv6->unicast[i].is_used || !ipv6->prefix[i].is_used) {
                        continue;
                }
```

Let me know if you prefer this solution, which is probably more accurate.

**Comment by jukkar** [comment]
> But now I realize that the problem is maybe with `ipv6_prefix_find()` returning an expired prefix. It tests `!ipv6->unicast[i].is_used` but do not test `!ipv6->prefix[i].is_used`. I experimented this idea with the following patch and it also works:
> 
> ```
> --- a/subsys/net/ip/net_if.c
> +++ b/subsys/net/ip/net_if.c
> @@ -2152,7 +2152,7 @@ static struct net_if_ipv6_prefix *ipv6_prefix_find(struct net_if *iface,
>         }
>  
>         for (i = 0; i < NET_IF_MAX_IPV6_PREFIX; i++) {
> -               if (!ipv6->unicast[i].is_used) {
> +               if (!ipv6->unicast[i].is_used || !ipv6->prefix[i].is_used) {
>                         continue;
>                 }
> ```
> 
> Let me know if you prefer this solution, which is probably more accurate.

I agree, this check is better imho.

**Comment by rlubos** [comment]
Thanks for the detailed analysis, it's much easier to understand the issue now.

This actually made me wonder - inside `ipv6_prefix_find()`, is this check even a valid one? 
```
		if (!ipv6->unicast[i].is_used) {
			continue;
		}
```
Note, that we iterate over prefixes, yet we check the IPv6 addresses array on an interface. Note, that it might even end up in out of bound read, if `NET_IF_MAX_IPV6_ADDR < NET_IF_MAX_IPV6_PREFIX` for any reason - the size of IPv6 address and prefix arrays are separately configured.

Shouldn't this check be simply replaced with the following?
```
		if (!ipv6->prefix[i].is_used) {
			continue;
		}
```

**Comment by vaussard** [comment]
> Note, that we iterate over prefixes, yet we check the IPv6 addresses array on an interface. It might even end up in out of bound read, if `NET_IF_MAX_IPV6_ADDR < NET_IF_MAX_IPV6_PREFIX` for any reason - the size of IPv6 address and prefix arrays are separately configured.
> 
> Shouldn't this check be simply replaced with the following?
> 
> ```
> 		if (!ipv6->prefix[i].is_used) {
> 			continue;
> 		}
> ```

I would agree, this looks fishy. But I am not very knowledgeable in this area.

I went back through the history and found that this function was added by @jukkar in commit e13ff65c22c6bb11df14aefa01eafdfad5f16cb6. It already contained this test on the IPv6 address instead of the IPv6 prefix. Maybe Jukka knows if there is something that we are missing? Otherwise I can push the suggested change.

**Comment by jukkar** [comment]
> I went back through the history and found that this function was added by @jukkar in commit [e13ff65](https://github.com/zephyrproject-rtos/zephyr/commit/e13ff65c22c6bb11df14aefa01eafdfad5f16cb6)

Don't recall that commit after so many years. But after looking this piece of code
https://github.com/zephyrproject-rtos/zephyr/blob/7ab16c457b304ccff82056243e1cee8913263d3e/subsys/net/ip/net_if.c#L2155
it looks like the we are incorrectly checking unicast address instead of the more proper prefix one.
So the check should have been
```
		if (ipv6->prefix[i].is_used) {
			continue;
		}
```
at least it really looks like that.

**Comment by vaussard** [comment]
I looked at the other occurrences of loops on `unicast[i].is_used` in subsys/net/. They are all using a bound of `NET_IF_MAX_IPV6_ADDR` / `NET_IF_MAX_IPV4_ADDR` except for the piece of code above. Conversely the occurrences of `prefix[i].is_used` use a bound of `NET_IF_MAX_IPV6_PREFIX` with the only exception of the code above. So this looks indeed to be an error.

I will do the change, test it with the reproducer mentioned in the description and update the PR.

**Comment by vaussard** [comment]
I just pushed the new version @rlubos @jukkar

**Review by rlubos — APPROVED** [review]
Thanks, LGTM

**Review by jukkar — APPROVED** [review]

**Pull request merged**
