### PR TITLE
net: ip: fix promiscuous mode altering packets

### LINKED ISSUE #61647: Promiscuous mode altering some packets
I am using Zephyr for an ethernet application on an STM32H7. I use promiscuous mode on the interface and net_promisc_mode_wait_data() to successfully receive all ethernet packets, however, some packets have their ethernet headers stripped, and others don't.

In net_if.c net_if_recv_data() is the following code:

```C
verdict = net_if_l2(iface)->recv(iface, pkt);
if (verdict == NET_CONTINUE) {
new_pkt = net_pkt_clone(pkt, K_NO_WAIT);
} else {
new_pkt = net_pkt_ref(pkt);
}
```

This passes the packet to the layer 2 handler BEFORE it's cloned and passed to the promiscuous fifo. If the layer 2 hander (ethernet.c ethernet_recv() ) doesn't care about the packet, then verdict is NET_DROP and the packet gets placed in the promiscuous fifo unmodified. If however, the layer 2 hander also wants to handle the packet then it strips the headers by advancing the buffer pointer (net_buf_pull()), and verdict is NET_CONTINUE. It is only AFTER this that the packet is cloned and added to the promiscuous fifo.

Thus, some packets (multicast, broadcast, non self target mac address packets) are received through the promiscuous API unmodified, while others (those targeted to the MAC address of the device) are received with the ethernet headers stripped.

Suggestion: always clone the packet and pass to the promiscuous fifo before passing the original pkt up the stack, by replacing the following code in net_if.c net_if_recv_data():

```C
if (IS_ENABLED(CONFIG_NET_PROMISCUOUS_MODE) &&
	    net_if_is_promisc(iface)) {
		/* If the packet is not for us and the promiscuous
		 * mode is enabled, then increase the ref count so
		 * that net_core.c:processing_data() will not free it.
		 * The promiscuous mode handler must free the packet
		 * after it has finished working with it.
		 *
		 * If packet is for us, then NET_CONTINUE is returned.
		 * In this case we must clone the packet, as the packet
		 * could be manipulated by other part of the stack.
		 */
		enum net_verdict verdict;
		struct net_pkt *new_pkt;

		/* This protects pkt so that it will not be freed by L2 recv()
		 */
		net_pkt_ref(pkt);

		verdict = net_if_l2(iface)->recv(iface, pkt);
		if (verdict == NET_CONTINUE) {
			new_pkt = net_pkt_clone(pkt, K_NO_WAIT);
		} else {
			new_pkt = net_pkt_ref(pkt);
		}

		/* L2 has modified the buffer starting point, it is easier
		 * to re-initialize the cursor rather than updating it.
		 */
		net_pkt_cursor_init(new_pkt);

		if (net_promisc_mode_input(new_pkt) == NET_DROP) {
			net_pkt_unref(new_pkt);
		}

		net_pkt_unref(pkt);

		return verdict;
	}
```

with:
```C
if (IS_ENABLED(CONFIG_NET_PROMISCUOUS_MODE) &&
	    net_if_is_promisc(iface)) {
		struct net_pkt *new_pkt;

		new_pkt = net_pkt_clone(pkt, K_NO_WAIT);

		if (net_promisc_mode_input(new_pkt) == NET_DROP) {
			net_pkt_unref(new_pkt);
		}
	}
```

Please let me know if you would like a PR.

Thanks, Kieran.

### PR DESCRIPTION
**Pull request by graffiti**
Always clone net_pkt to pass to promiscuous queue.
Fixes #61647.

Previously, net_pkt was passed to L2 before conditionally cloning. But L2 would in some cases strip ethernet headers, so cloned net_pkt received through promiscuous interface would be missing headers.

### CODE REVIEW

**Comment by jukkar** [comment]
There is now an issue with unit test as it checks if the two network packets are the same but they are no longer that.
In `tests/net/promiscuous/src/main.c:test_verify_data()`
```
	pkt = net_promisc_mode_wait_data(K_SECONDS(1));
	zassert_equal_ptr(pkt, pkt1, "pkt %p != %p", pkt, pkt1);
	net_pkt_unref(pkt);

	pkt = net_promisc_mode_wait_data(K_SECONDS(1));
	zassert_equal_ptr(pkt, pkt2, "pkt %p != %p", pkt, pkt2);
	net_pkt_unref(pkt);
```
Instead of checking pointer equality here, we could check that they contain same amount of data and that the data is the same.

**Comment by graffiti** [comment]
ok thanks, I'm having some trouble running twister here atm, but when I have that sorted I'll take a look at the unit test.

**Comment by jukkar** [comment]
@graffiti you do not need twister to make sure that the test passes, this should be enough for local testing in your host
```
west build -b qemu_x86 -d build/promisc_mode -t run zephyr/tests/net/promiscuous/
```

**Comment by carlescufi** [comment]
@graffiti please rebase and resolve the conflicts

**Comment by henrikbrixandersen** [comment]
@Graffiti You're changing 5000+ files in this PR, which indicates a wrong commit history on your local branch. Please fix this.

**Comment by henrikbrixandersen** [comment]
@Graffiti You're changing 5000+ files in this PR, which indicates a wrong commit history on your local branch. Please fix this.

**Comment by graffiti** [comment]
sorry, messed up the rebase, I will create a new clean PR for this.

**Pull request closed without merging**
