### PR TITLE
boards: hifive_unmatched: add renode simulation

### PR DESCRIPTION
**Pull request by ycsin**
Changes to this file were missed out from the original PR #65564 that added Renode support for this board, add them here so that it gets ran in CI.

```
(.venv) ycsin@LAPTOP-ROG:~/zephyrproject$ twister -p hifive_unmatched -T zephyr/samples/subsys/shell/shell_module/
INFO    - Using Ninja..
INFO    - Zephyr version: zephyr-v3.5.0-2855-gee2ac818fa4e
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /home/ycsin/zephyrproject/twister-out/testplan.json
INFO    - JOBS: 6
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:    7/   7  100%  skipped:    3, failed:    0, error:    0
INFO    - 7 test scenarios (7 test instances) selected, 3 configurations skipped (2 by static filter, 1 at runtime).
INFO    - 4 of 7 test configurations passed (100.00%), 0 failed, 0 errored, 3 skipped with 0 warnings in 43.95 seconds
INFO    - In total 0 test cases were executed, 7 skipped on 1 out of total 654 platforms (0.15%)
INFO    - 0 test configurations executed on platforms, 4 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing JSON report /home/ycsin/zephyrproject/twister-out/twister.json
INFO    - Writing xunit report /home/ycsin/zephyrproject/twister-out/twister.xml...
INFO    - Writing xunit report /home/ycsin/zephyrproject/twister-out/twister_report.xml...
```

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi, thanks for this PR.

It looks like the current in-tree repl for this platform in Zephyr doesn't model the SD card which is required for running ext2 tests & samples. This means that they are unfortunately not runnable on Renode with the repl file Zephyr currently provides.

I'm not sure though on how we should proceed here, because they are perfecty runnable when Twister uses HW runner, so disabling them altogether for this platform seems like throwing the baby out with the bathwater.

**Comment by ycsin** [comment]
> It looks like the current in-tree repl for this platform in Zephyr doesn't model the SD card which is required for running ext2 tests & samples. This means that they are unfortunately not runnable on Renode with the repl file Zephyr currently provides.

Yeah just noticed that, will https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Peripherals/Peripherals/SD/SDCard.cs work? Otherwise it seems like we have to revert https://github.com/zephyrproject-rtos/zephyr/pull/65564?

**Comment by fkokosinski** [comment]
> will https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Peripherals/Peripherals/SD/SDCard.cs work?

Yup, it should work since  we're accessing the SD card in SPI mode on the Unmatched board. Note that we would still need to create an image with the ext2 filesystem before the test/sample, as they expect it to be flashed onto the card. 

The solution with `simulation_exclude` is also fine by me, so we probably should do that now, and extend the simulation support for the ext2 testing purposes later.

**Comment by ycsin** [comment]
> The solution with `simulation_exclude` is also fine by me, so we probably should do that now, and extend the simulation support for the ext2 testing purposes later.

ping, could you PTAL?

**Review by fkokosinski — APPROVED** [review]

**Review by tgorochowik — APPROVED** [review]

**Pull request merged**
