### PR TITLE
scripts/dts: add support for bytestring property values

### PR DESCRIPTION
**Pull request by pabigot**
This allows devicetree source to have entries like:
```
lut-20 = [ /* VCOM LUT */
	00 17 17 00 00 02
	00 0A 01 00 00 01
	00 0E 0E 00 00 02
	00 00 00 00 00 00
	00 00 00 00 00 00
	00 00 00 00 00 00
	00 00 00 00 00 00
	00 00
	];
```
which can be used in code like this:
```
#ifdef DT_INST_0_WAVESHARE_EPD_LUT_20
static const u8_t lut_20[] = DT_INST_0_WAVESHARE_EPD_LUT_20;
#endif
/* ... */
rc = SendCommand(0x20, lut_20, sizeof(lut_20));
```
rather than trying to assign an arbitrary number of individual elements into an array.

Addresses one part of #17309

### CODE REVIEW

**Comment by galak** [comment]
So I think we should use uint8-array for this purpose, but it means cleaning up the ethernet 'local-mac-address' generation.  Are you willing to look at that?

**Comment by pabigot** [comment]
I think I disagree on `uint8-array`, depending on what you mean.  `bytestring` is a documented devicetree type with distinct syntax: we should use it.  It may be that people actually want `uint8-array` to generate individual elements, as it currently does.  Certainly I don't think we should change the behavior and syntax for `uint8-array`, but maybe we should recognize that it should always have been `bytestring` and deprecate that type in the scripting.

**Comment by pabigot** [comment]
Ah, I see: indeed, `uint-array` should have been named `bytestring` then when I was looking for this feature I'd have found that it was already there (though buggy, in that it used decimal values).

**Comment by galak** [comment]
> I think I disagree on `uint8-array`, depending on what you mean. `bytestring` is a documented devicetree type with distinct syntax: we should use it. It may be that people actually want `uint8-array` to generate individual elements, as it currently does. Certainly I don't think we should change the behavior and syntax for `uint8-array`, but maybe we should recognize that it should always have been `bytestring` and deprecate that type in the scripting.

`uint8-array` came from trying to align with the dt-schema project.

https://github.com/devicetree-org/dt-schema

I check with the dt-schema maintainer on how we should handle bytestrings and he said to use uint8-array.

**Comment by pabigot** [comment]
FFS.  Ok, I'll update the PR.

**Comment by pabigot** [comment]
> So I think we should use uint8-array for this purpose, but it means cleaning up the ethernet 'local-mac-address' generation. Are you willing to look at that?

Updated the template to document `uint8-array`.  I'm not clear on what needs to be cleaned up for `local-mac-address`.

**Comment by pabigot** [comment]
> So I think we should use uint8-array for this purpose, but it means cleaning up the ethernet 'local-mac-address' generation. Are you willing to look at that?

Done, assuming CI doesn't find a problem.  Two of three vendors hard-code OUI regardless of devicetree content: I believe I've preserved that behavior.

**Review by jfischer-no — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by ulfalizer** [comment]
I wonder if skipping the `{}` in the output would make it a bit more general.

This makes it a bit more immediately obvious what's going on too, to me at least:

```c
static const u8_t lut_20[] = { DT_INST_0_WAVESHARE_EPD_LUT_20 };
```

**Review by ulfalizer — COMMENTED** [review]
I wonder if skipping the `{}` in the output would make it a bit more general.

This makes it a bit more immediately obvious what's going on too, to me at least:

```c
static const u8_t lut_20[] = { DT_INST_0_WAVESHARE_EPD_LUT_20 };
```

Also generates slightly less weird-looking output in the `.conf` file, but nothing will probably look at it anyway:

```
DT_NXP_KINETIS_ETHERNET_400C0004_LOCAL_MAC_ADDRESS=0x00, 0x00, 0x00, 0x00, 0x00, 0x00
```

instead of

```
DT_NXP_KINETIS_ETHERNET_400C0004_LOCAL_MAC_ADDRESS={ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
```

**Comment by pabigot** [comment]
My preference is to keep this as implemented:

The defines generally provide the value of the corresponding property, in a form where it can be assigned to a variable with the type of the property.  The value of this property is an array of bytes, and the literal expression of such a value includes braces.

Similarly if we extend this sort of thing to an option for properties that have compound values, as proposed in #17309, the initializer for a structure has enclosing braces that should be part of the generated value.

With the braces included developers don't need to know the details of the representation; they can just assign the value.  If the braces aren't included, simple assignment will produce syntax errors.

If there's a compelling use case where somebody would want to combine multiple properties into a sequence without any record of where the individual elements end, then an option to not generate the braces might be added.

I was unaware of the .conf file.  What's that used for?  Is there a reason why it should use a different representation of the property value?

**Comment by jfischer-phytec-iot** [comment]
@ulfalizer .`conf` file? Do you mean `generated_dts_board_unfixed.h`?


generated_dts_board_unfixed.h
```c
#define DT_NORDIC_NRF_SPI_4002B000_SOLOMON_SSD16XXFB_0_LUT_DEFAULT              { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
...
#define DT_INST_0_SOLOMON_SSD16XXFB_LUT_DEFAULT                                 DT_NORDIC_NRF_SPI_4002B000_SOLOMON_SSD16XXFB_0_LUT_DEFAULT
```

ssd16xx.c
```c
static u8_t ssd16xx_lut_default[] = DT_INST_0_SOLOMON_SSD16XXFB_LUT_DEFAULT;
```

**Comment by ulfalizer** [comment]
@jfischer-phytec-iot 
There's a `generated_dts_board.conf` as well. Can read the values from Kconfig and (I think) CMake.

@pabigot 
List of values seems less gotcha-prone to me. Can drop it in anywhere as part of a multi-dim initializer without gotchas, substitute it into a function call, etc. I'm more of a flexibility guy than a purity guy. Think the added `{}` makes it easier to read too.

Not super important anyway.

**Comment by ulfalizer** [comment]
Stuff like this won't work either:

```c
uint8_t foo[] = {1, 2, 3, DT_BLAH};
```

**Review by ulfalizer — APPROVED** [review]
Thinking about it some more, I now think the `{}`-less macro version is a bit icky in that it might trick you into thinking there's just one element though. Don't let it block.

**Review by jukkar — APPROVED** [review]
LGTM

**Pull request merged**
