### PR TITLE
tfm: Use generic nRF5340 NS platform support for BL5340 DVK

### PR DESCRIPTION
**Pull request by joerchan**

### CODE REVIEW

**Comment by rerickson1** [comment]
`west build -p -b bl5340_dvk_cpuapp_ns samples/tfm_integration/tfm_regression_test`

Results from running on board:
```
Non-Secure system starting...

#### Execute test suites for the Non-secure area ####
Running Test Suite IPC non-secure interface test (TFM_NS_IPC_TEST_1XXX)...
> Executing 'TFM_NS_IPC_TEST_1001' 
  Description: 'Get PSA framework version'
  TEST: TFM_NS_IPC_TEST_1001 - PASSED!
> Executing 'TFM_NS_IPC_TEST_1002' 
  Description: 'Get version of an RoT Service'
  TEST: TFM_NS_IPC_TEST_1002 - PASSED!
> Executing 'TFM_NS_IPC_TEST_1003' 
  Description: 'Connect to an RoT Service'
Connect success!
  TEST: TFM_NS_IPC_TEST_1003 - PASSED!
> Executing 'TFM_NS_IPC_TEST_1004' 
  Description: 'Request connection-based RoT Service'
  TEST: TFM_NS_IPC_TEST_1004 - PASSED!
> Executing 'TFM_NS_IPC_TEST_1010' 
  Description: 'Test psa_call with the status of PSA_ERROR_PROGRAMMER_ERROR'
Connect success!
The first time call success!
The second time call success!
  TEST: TFM_NS_IPC_TEST_1010 - PASSED!
> Executing 'TFM_NS_IPC_TEST_1012' 
  Description: 'Request stateless service'
  TEST: TFM_NS_IPC_TEST_1012 - PASSED!
TESTSUITE PASSED!
Running Test Suite PSA protected storage NS interface tests (TFM_NS_PS_TEST_1XXX)...
> Executing 'TFM_NS_PS_TEST_1001' 
  Description: 'Set interface'
  TEST: TFM_NS_PS_TEST_1001 - PASSED!
> Executing 'TFM_NS_PS_TEST_1002' 
  Description: 'Set interface with create flags'
  TEST: TFM_NS_PS_TEST_1002 - PASSED!
> Executing 'TFM_NS_PS_TEST_1003' 
  Description: 'Set interface with NULL data pointer'
  TEST: TFM_NS_PS_TEST_1003 - PASSED!
> Executing 'TFM_NS_PS_TEST_1004' 
  Description: 'Set interface with write once UID'
  TEST: TFM_NS_PS_TEST_1004 - PASSED!
> Executing 'TFM_NS_PS_TEST_1005' 
  Description: 'Get interface with valid data'
  TEST: TFM_NS_PS_TEST_1005 - PASSED!
> Executing 'TFM_NS_PS_TEST_1006' 
  Description: 'Get interface with zero data length'
  TEST: TFM_NS_PS_TEST_1006 - PASSED!
> Executing 'TFM_NS_PS_TEST_1007' 
  Description: 'Get interface with invalid UIDs'
  TEST: TFM_NS_PS_TEST_1007 - PASSED!
> Executing 'TFM_NS_PS_TEST_1008' 
  Description: 'Get interface with invalid data lengths and offsets'
  TEST: TFM_NS_PS_TEST_1008 - PASSED!
> Executing 'TFM_NS_PS_TEST_1009' 
  Description: 'Get interface with NULL data pointer'
  TEST: TFM_NS_PS_TEST_1009 - PASSED!
> Executing 'TFM_NS_PS_TEST_1010' 
  Description: 'Get info interface with write once UID'
  TEST: TFM_NS_PS_TEST_1010 - PASSED!
> Executing 'TFM_NS_PS_TEST_1011' 
  Description: 'Get info interface with valid UID'
  TEST: TFM_NS_PS_TEST_1011 - PASSED!
> Executing 'TFM_NS_PS_TEST_1012' 
  Description: 'Get info interface with invalid UIDs'
  TEST: TFM_NS_PS_TEST_1012 - PASSED!
> Executing 'TFM_NS_PS_TEST_1013' 
  Description: 'Remove interface with valid UID'
  TEST: TFM_NS_PS_TEST_1013 - PASSED!
> Executing 'TFM_NS_PS_TEST_1014' 
  Description: 'Remove interface with write once UID'
  TEST: TFM_NS_PS_TEST_1014 - PASSED!
> Executing 'TFM_NS_PS_TEST_1015' 
  Description: 'Remove interface with invalid UID'
  TEST: TFM_NS_PS_TEST_1015 - PASSED!
> Executing 'TFM_NS_PS_TEST_1021' 
  Description: 'Block compaction after remove'
  TEST: TFM_NS_PS_TEST_1021 - PASSED!
> Executing 'TFM_NS_PS_TEST_1022' 
  Description: 'Multiple partial gets'
  TEST: TFM_NS_PS_TEST_1022 - PASSED!
> Executing 'TFM_NS_PS_TEST_1023' 
  Description: 'Multiple sets to same UID from same thread'
  TEST: TFM_NS_PS_TEST_1023 - PASSED!
> Executing 'TFM_NS_PS_TEST_1024' 
  Description: 'Get support interface'
  TEST: TFM_NS_PS_TEST_1024 - PASSED!
> Executing 'TFM_NS_PS_TEST_1025' 
  Description: 'Set, get and remove interface with different asset sizes'
  TEST: TFM_NS_PS_TEST_1025 - PASSED!
TESTSUITE PASSED!
Running Test Suite PSA internal trusted storage NS interface tests (TFM_NS_ITS_TEST_1XXX)...
> Executing 'TFM_NS_ITS_TEST_1001' 
  Description: 'Set interface'
  TEST: TFM_NS_ITS_TEST_1001 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1002' 
  Description: 'Set interface with create flags'
Note: The UID in this test has already been created with
the PSA_STORAGE_FLAG_WRITE_ONCE flag in a previous test
run. Wipe the storage area to run the full test.
  TEST: TFM_NS_ITS_TEST_1002 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1003' 
  Description: 'Set interface with NULL data pointer'
  TEST: TFM_NS_ITS_TEST_1003 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1004' 
  Description: 'Set interface with write once UID'
  TEST: TFM_NS_ITS_TEST_1004 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1005' 
  Description: 'Get interface with valid data'
  TEST: TFM_NS_ITS_TEST_1005 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1006' 
  Description: 'Get interface with zero data length'
  TEST: TFM_NS_ITS_TEST_1006 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1007' 
  Description: 'Get interface with invalid UIDs'
  TEST: TFM_NS_ITS_TEST_1007 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1008' 
  Description: 'Get interface with invalid data lengths and offsets'
  TEST: TFM_NS_ITS_TEST_1008 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1009' 
  Description: 'Get interface with NULL data pointer'
  TEST: TFM_NS_ITS_TEST_1009 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1010' 
  Description: 'Get info interface with write once UID'
  TEST: TFM_NS_ITS_TEST_1010 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1011' 
  Description: 'Get info interface with valid UID'
  TEST: TFM_NS_ITS_TEST_1011 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1012' 
  Description: 'Get info interface with invalid UIDs'
  TEST: TFM_NS_ITS_TEST_1012 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1013' 
  Description: 'Remove interface with valid UID'
  TEST: TFM_NS_ITS_TEST_1013 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1014' 
  Description: 'Remove interface with write once UID'
  TEST: TFM_NS_ITS_TEST_1014 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1015' 
  Description: 'Remove interface with invalid UID'
  TEST: TFM_NS_ITS_TEST_1015 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1016' 
  Description: 'Block compaction after remove'
  TEST: TFM_NS_ITS_TEST_1016 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1017' 
  Description: 'Multiple partial gets'
  TEST: TFM_NS_ITS_TEST_1017 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1018' 
  Description: 'Multiple sets to same UID from same thread'
  TEST: TFM_NS_ITS_TEST_1018 - PASSED!
> Executing 'TFM_NS_ITS_TEST_1019' 
  Description: 'Set, get and remove interface with different asset sizes'
  TEST: TFM_NS_ITS_TEST_1019 - PASSED!
TESTSUITE PASSED!
Running Test Suite Crypto non-secure interface test (TFM_NS_CRYPTO_TEST_1XXX)...
> Executing 'TFM_NS_CRYPTO_TEST_1001' 
  Description: 'Non Secure Key management interface'
  TEST: TFM_NS_CRYPTO_TEST_1001 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1002' 
  Description: 'Non Secure Symmetric encryption (AES-128-CBC) interface'
  TEST: TFM_NS_CRYPTO_TEST_1002 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1003' 
  Description: 'Non Secure Symmetric encryption (AES-128-CFB) interface'
  TEST: TFM_NS_CRYPTO_TEST_1003 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1005' 
  Description: 'Non Secure Symmetric encryption (AES-128-CTR) interface'
  TEST: TFM_NS_CRYPTO_TEST_1005 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1006' 
  Description: 'Non Secure Symmetric encryption (AES-256-CTR) interface'
  TEST: TFM_NS_CRYPTO_TEST_1006 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1007' 
  Description: 'Non Secure Symmetric encryption invalid cipher'
  TEST: TFM_NS_CRYPTO_TEST_1007 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1008' 
  Description: 'Non Secure Symmetric encryption invalid cipher (AES-152)'
  TEST: TFM_NS_CRYPTO_TEST_1008 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1009' 
  Description: 'Non Secure Symmetric encryption invalid cipher (HMAC-128-CFB)'
  TEST: TFM_NS_CRYPTO_TEST_1009 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1010' 
  Description: 'Non Secure Unsupported Hash (SHA-1) interface'
  TEST: TFM_NS_CRYPTO_TEST_1010 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1011' 
  Description: 'Non Secure Hash (SHA-224) interface'
  TEST: TFM_NS_CRYPTO_TEST_1011 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1012' 
  Description: 'Non Secure Hash (SHA-256) interface'
  TEST: TFM_NS_CRYPTO_TEST_1012 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1019' 
  Description: 'Non Secure Unsupported HMAC (SHA-1) interface'
  TEST: TFM_NS_CRYPTO_TEST_1019 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1020' 
  Description: 'Non Secure HMAC (SHA-256) interface'
  TEST: TFM_NS_CRYPTO_TEST_1020 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1024' 
  Description: 'Non Secure HMAC with long key (SHA-224) interface'
  TEST: TFM_NS_CRYPTO_TEST_1024 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1030' 
  Description: 'Non Secure AEAD (AES-128-CCM) interface'
  TEST: TFM_NS_CRYPTO_TEST_1030 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1031' 
  Description: 'Non Secure AEAD (AES-128-GCM) interface'
  TEST: TFM_NS_CRYPTO_TEST_1031 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1032' 
  Description: 'Non Secure key policy interface'
  TEST: TFM_NS_CRYPTO_TEST_1032 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1033' 
  Description: 'Non Secure key policy check permissions'
  TEST: TFM_NS_CRYPTO_TEST_1033 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1034' 
  Description: 'Non Secure persistent key interface'
  TEST: TFM_NS_CRYPTO_TEST_1034 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1035' 
  Description: 'Non Secure AEAD interface with truncated auth tag (AES-128-CCM-8)'
  TEST: TFM_NS_CRYPTO_TEST_1035 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1036' 
  Description: 'Non Secure TLS 1.2 PRF key derivation'
  TEST: TFM_NS_CRYPTO_TEST_1036 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1037' 
  Description: 'Non Secure TLS-1.2 PSK-to-MasterSecret key derivation'
  TEST: TFM_NS_CRYPTO_TEST_1037 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1038' 
  Description: 'Non Secure HKDF key derivation'
  TEST: TFM_NS_CRYPTO_TEST_1038 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1039' 
  Description: 'Non Secure ECDH key agreement'
  TEST: TFM_NS_CRYPTO_TEST_1039 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1040' 
  Description: 'Non Secure Symmetric encryption (AES-128-OFB) interface'
  TEST: TFM_NS_CRYPTO_TEST_1040 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1041' 
  Description: 'Non Secure Symmetric encryption (AES-128-ECB) interface'
  TEST: TFM_NS_CRYPTO_TEST_1041 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1042' 
  Description: 'Non Secure Asymmetric encryption interface (RSA-OAEP)'
  TEST: TFM_NS_CRYPTO_TEST_1042 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1043' 
  Description: 'Non Secure Asymmetric encryption interface (RSA-PKCS1V15)'
  TEST: TFM_NS_CRYPTO_TEST_1043 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1044' 
  Description: 'Non Secure Sign and verify message interface (ECDSA-SECP256R1-SHA256)'
  TEST: TFM_NS_CRYPTO_TEST_1044 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1045' 
  Description: 'Non Secure Symmetric encryption (AES-128-CBC-PKCS7) interface'
  TEST: TFM_NS_CRYPTO_TEST_1045 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1046' 
  Description: 'Non Secure Symmetric encryption (AES-128-CBC-PKCS7) interface, shorter'
  TEST: TFM_NS_CRYPTO_TEST_1046 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1047' 
  Description: 'Non Secure Symmetric encryption (AES-128-CBC-PKCS7) interface, longer'
  TEST: TFM_NS_CRYPTO_TEST_1047 - PASSED!
> Executing 'TFM_NS_CRYPTO_TEST_1050' 
  Description: 'Non Secure RSASSA-PSS signature verification (RSASSA-PSS-SHA256)'
  TEST: TFM_NS_CRYPTO_TEST_1050 - PASSED!
TESTSUITE PASSED!
Running Test Suite Platform Service Non-Secure interface tests(TFM_NS_PLATFORM_TEST_1XXX)...
> Executing 'TFM_NS_PLATFORM_TEST_1001' 
  Description: 'Minimal platform service test'
  TEST: TFM_NS_PLATFORM_TEST_1001 - PASSED!
TESTSUITE PASSED!

*** Non-secure test suites summary ***
Test suite 'IPC non-secure interface test (TFM_NS_IPC_TEST_1XXX)' has PASSED
Test suite 'PSA protected storage NS interface tests (TFM_NS_PS_TEST_1XXX)' has PASSED
Test suite 'PSA internal trusted storage NS interface tests (TFM_NS_ITS_TEST_1XXX)' has PASSED
Test suite 'Crypto non-secure interface test (TFM_NS_CRYPTO_TEST_1XXX)' has PASSED
Test suite 'Platform Service Non-Secure interface tests(TFM_NS_PLATFORM_TEST_1XXX)' has PASSED

*** End of Non-secure test suites ***
```

**Review by rerickson1 — APPROVED** [review]

**Review by rerickson1 — CHANGES_REQUESTED** [review]
Looking at the sample output further, I think the entire secure area tests are missing.

**Comment by joerchan** [comment]
> Looking at the sample output further, I think the entire secure area tests are missing.

Are you referring to the test suites run in secure?
The output of that is on the second UART VCOM.

**Review by rerickson1 — APPROVED** [review]

**Comment by rerickson1** [comment]
> > Looking at the sample output further, I think the entire secure area tests are missing.
> 
> Are you referring to the test suites run in secure? The output of that is on the second UART VCOM.

Thanks! I checked, everything is passing.

**Review by SebastianBoe — APPROVED** [review]

**Pull request merged**
