### PR TITLE
dts: rt11xx: add missing GPIO7, GPIO8, GPIO12

### LINKED ISSUE #43292: NXP RT11xx devicetree missing GPIO7, GPIO8, GPIO12
**Is your enhancement proposal related to a problem? Please describe.**
DTS file includes most GPIO peripherals, but these 3 are missing.

**Describe the solution you'd like**
Add missing GPIO to DTS

**Additional context**
zephyr\dts\arm\nxp\nxp_rt11xx.dtsi

### PR DESCRIPTION
**Pull request by DerekSnell**
added missing GPIO peripherals to devicetree

resolves #43292

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@DerekSnell. Please take a look at the twister failures.

**Comment by danieldegrasse** [comment]
@mmahadevan108 @dleach02 I'm taking over this PR at @DerekSnell's request, since the GPIO definitions here are required for pin control enablement.

**Comment by mmahadevan108** [comment]
Can we close this PR?

**Comment by danieldegrasse** [comment]
@mmahadevan108 these GPIO definitions are required for pinctrl support on the RT11xx. We can merge this before that PR, or just use the definitions present in the pinctrl PR. I personally think we should merge this PR, since the missing GPIO definitions is an issue external to pin control being enabled.

**Comment by dleach02** [comment]
@danieldegrasse is this ready to merge then?

**Review by dleach02 — APPROVED** [review]

**Comment by danieldegrasse** [comment]
@dleach02, it should be, yeah

**Review by danieldegrasse — APPROVED** [review]

**Pull request merged**
