### PR TITLE
Bluetooth: shell: audio: Extend `vcs init` with opt params

### PR DESCRIPTION
**Pull request by MariuszSkamra**
Extend the `vcs init` command with optional parameters to set the
initial VCS state including volume level, mute state and step size.
This is needed to pass qualification test cases listed below:
VCS/SR/CP/BV-01-C,
VCS/SR/CP/BV-02-C,
VCS/SR/CP/BV-02-C,
VCS/SR/CP/BV-04-C

Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

### CODE REVIEW

**Review by sjanc — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
Didn't realize that we are using the shell for PTS tests :)

**Comment by MariuszSkamra** [comment]
> Didn't realize that we are using the shell for PTS tests :) 

Why not?

**Comment by Thalley** [comment]
> > Didn't realize that we are using the shell for PTS tests :)
> 
> Why not?

I just didn't know that :D 

But it's good to know, since that would also indicate that we need to make sure that the shell modules are complete in terms of what the API offers in the future. 

Are we using the shell modules for the GAP and GATT tests too?

**Comment by MariuszSkamra** [comment]
> I just didn't know that :D
> 
> But it's good to know, since that would also indicate that we need to make sure that the shell modules are complete in terms of what the API offers in the future.
> 
> Are we using the shell modules for the GAP and GATT tests too?

Shell can be used for GATT/GAP tests as well if one wish, but generally we use bluetooth/tester application instead because it's just faster to use automation

**Comment by Thalley** [comment]
> > I just didn't know that :D
> > But it's good to know, since that would also indicate that we need to make sure that the shell modules are complete in terms of what the API offers in the future.
> > Are we using the shell modules for the GAP and GATT tests too?
> 
> Shell can be used for GATT/GAP tests as well if one wish, but generally we use bluetooth/tester application instead because it's just faster to use automation

Alright, so ideally we'd also use a tester application for VCS at some point?

**Comment by MariuszSkamra** [comment]
> Alright, so ideally we'd also use a tester application for VCS at some point?

That would be nice. It probably requires extending BTP (binary protocol that instructs IUT) with some VCS specific commands, and some work in AutoPTS.

**Comment by Thalley** [comment]
> > Alright, so ideally we'd also use a tester application for VCS at some point?
> 
> That would be nice. It probably requires extending BTP (binary protocol that instructs IUT) with some VCS specific commands, and some work in AutoPTS.

Maybe preparing LE Audio for AutoPTS should be an item on the next F2F :)

**Pull request merged**
