### PR TITLE
edtlib: Add support for retrieving nodes by property labels

### LINKED ISSUE #41523: drivers: i2c: i2c_mcux: unused variables cause daily build failures
**Describe the bug**
Twister fails during the daily build due to unused variables (warnings promoted to errors).

**To Reproduce**
```
twister -i -p ip_k66f -s samples/subsys/display/grove_display/sample.display.grove_display
```

**Expected behavior**
Daily build should not fail.

**Impact**
Annoyance, because the build succeeds with
```
west build -p auto -b ip_k66f samples/subsys/display/grove_display
```

**Logs and console output**
```
/__w/zephyr/zephyr/drivers/i2c/i2c_mcux.c:216:36: error: 'i2c_mcux_driver_api' defined but not used [-Werror=unused-const-variable=]
  216 | static const struct i2c_driver_api i2c_mcux_driver_api = {
      |                                    ^~~~~~~~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/i2c/i2c_mcux.c:186:12: error: 'i2c_mcux_init' defined but not used [-Werror=unused-function]
  186 | static int i2c_mcux_init(const struct device *dev)
      |            ^~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/i2c/i2c_mcux.c:178:13: error: 'i2c_mcux_isr' defined but not used [-Werror=unused-function]
  178 | static void i2c_mcux_isr(const struct device *dev)
      |             ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Environment (please complete the following information):**
 - OS: CI
 - Toolchain: Zephyr SDK 0.13.2
 - Commit SHA: 7f5eb921dc8bb1b7014886986bbffdf111b68b15

**Additional context**
Daily Build failure:
https://github.com/zephyrproject-rtos/zephyr/runs/4676613761?check_suite_focus=true

### PR DESCRIPTION
**Pull request by dleach02**
Some DT nodes have a 'label' property that is useful to filter on. Add an OrderedDict of prop_label2node containing nodes that have a 'label' property. The key will be the 'label' value.

Fixes #41523

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]
Wow - great work!

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
This feels like the wrong approach. We shouldn't be making assumptions about what devices are named IMO. Device names are arbitrary values.  Do you have a good argument for why it must be done this way, or perhaps are there other ways to fix this bug?

**Comment by dleach02** [comment]
@mbolivar-nordic, I'm open to suggestions on how to address the root problem.

Another potential way to fix this is to get this groove display to actually have a DT node definition instead of the current method where it it defines a device node programmatically in the driver file using a Kconfig define to set the node name, which currently defaults to I2C_0. Then a board should have an overlay or some sort for the display and the filter could use the existing set of filters to filter on the higher level node information being there with an okay status. I'm not really interested in doing this to the groove display since I don't have one and didn't add this to the repo. 

Currently though, the display doesn't do this and the sample.yaml is only using a "depends" filter of i2c. So our platform gets selected because it "has" an i2c but since it doesn't have anything actually connected to the i2c and doesn't have the I2C_0 node status set to okay causing the nightly build CI to fail ... I suspect that any other platforms will have a similar problem if they don't have the I2C_0 enabled. 

My other fallback to address the problem is to add a platform exclude for our particular board and move on. But I wanted to figure out what information I could use from the device tree that is generic enough to filter on. I don't understand though why the i2c individual nodes have a "label" property but figured I could filter on that since this seems to be a standard. I could have just touched the twister expr_filter.py and programmatically walked through the properties looking for the label that matches the filter (this is how I originally had it) but figured it might turn out to be more useful to move this up into edtlib.py.

**Comment by erwango** [comment]
I agree with @mbolivar-nordic that the approach feels wrong.
Adding this function opens the pandora box on something that has actively been pushed back for years (use of labels), with the reason it is arbitrary and could not be sanitized by dtc (naming conflicts can't be detected).
There are a lot of other ways to sort this that are already used in other samples. Main ones being `platform_allow` and `platform_exclude`. I agree that these aren't a panacea as they scale difficultly. 
Though then main issue here is that the grove driver isn't ported to device tree (from what I can see). Otherwise one could use already available functions like:
```
    filter: dt_compat_enabled("grove,display")
```
So waiting for this driver to be ported to device tree, I think that `platform_allow` or `platform_exclude` would be acceptable (even if not ideal, I concur).

**Comment by dleach02** [comment]
@erwango, that was what I wanted to do in the first place but without the display being in device tree I could do that. 

I will submit a new PR to just exclude my platform and move on.

I do think though that there might be value in having support for generic filtering based on items in the device tree. This PR is not generic but we might consider a tweak of this to allow filtering on any node/property path definition.

**Comment by erwango** [comment]
> I will submit a new PR to just exclude my platform and move on.

Ok, fine.

> I do think though that there might be value in having support for generic filtering based on items in the device tree. This PR is not generic but we might consider a tweak of this to allow filtering on any node/property path definition.

What I'm afraid of, with adding a function for filtering on labels, is that people will want to use it (as it could be seen as 
convenient and easy to use) and we'll see more and more work around labels which we'll struggle to push back.
But otherwise, any other kind of filtering helpers are welcome for sure.

**Pull request closed without merging**
