### PR TITLE
boards: adafruit_feather_m0_basic_proto: Add USB device support.

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
USB device support was tested with the cdc_acm sample.

Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Seems like this is dependent on USB driver getting merged.

**Comment by henrikbrixandersen** [comment]
@galak The sam0 USB driver was already merged to master: https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/usb/device/usb_dc_sam0.c

**Comment by galak** [comment]
> @galak The sam0 USB driver was already merged to master: https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/usb/device/usb_dc_sam0.c

sorry about the noise, was grepping in an old tree for USB_DC_SAM0

**Review by dbkinder — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
So not technically an issue with this patch, but normally we have devices disabled in the soc dts file and enabled in the board dts since not all devices are used on all boards.

I'm going to send a PR to deal with that, so this will need to update to enable the usb controller in the board dts.

**Comment by galak** [comment]
I pushed PR #6554 to handle the dts update for usb.

**Comment by henrikbrixandersen** [comment]
@galak Recheck, please.

**Review by galak — APPROVED** [review]

**Comment by sundar-subramaniyan** [comment]
@henrikbrixandersen @galak 

The commit in the master branch seems to create CI failures for everyone.
Please take a look at these runs:
https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/12075/1/console
https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/12078/1/console
https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/12080/1/console

**Comment by henrikbrixandersen** [comment]
@sundar-subramaniyan @galak The pushed commit (34a38816f6339f15fd268906290206bf8bd2d590) does not match what is in this pull request. It lacks the change to `boards/arm/adafruit_trinket_m0/adafruit_trinket_m0.dts`.

**Comment by sundar-subramaniyan** [comment]
@henrikbrixandersen @galak Right. Just thought I'd point that to you guys to figure out and fix it.

**Comment by MaureenHelm** [comment]
> The pushed commit (34a3881) does not match what is in this pull request. It lacks the change to boards/arm/adafruit_trinket_m0/adafruit_trinket_m0.dts.

The change to the trinket board went in 3b78d937e57827e7e128544e7557ce40d9cb1321. A similar change was never made to the feather board, so I created a new PR #6580 to fix it.

**Pull request merged**
