### PR TITLE
cmake: snippets: application requested snippets

### PR DESCRIPTION
**Pull request by JordanYates**
Add a dedicated cmake variable (`SNIPPET_APP`) to allow applications to
automatically request snippets from `CMakeLists.txt`.

Applications cannot currently simply append to the `SNIPPET` variable
because of the behaviour of `zephyr_check_cache`, which automatically
drops modifications to the variable that aren't present in the cache.

`SNIPPET_APP` is therefore a cleaner alternative to:

```
list(APPEND SNIPPET "snippet3;snippet4")
set(SNIPPET ${SNIPPET} CACHE INTERNAL "" FORCE)
```

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
> Applications cannot currently simply append to the SNIPPET variable
because of the behaviour of zephyr_check_cache, which automatically
drops modifications to the variable that aren't present in the cache.

but isn't that exactly the purpose of `zephyr_check_cache()` in this case ?

Users are not allowed to change the active list of snippets after first CMake invocation.

With your proposed changes, a user can now do:

1. Run `cmake -Bbuild mysample`
2. Run `ninja -C build`
3. Edit `mysample/CMakeLists.txt`, and change / extend the value of `SNIPPET_APP`.
4. Run `ninja -C build` (incremental build) which triggers an automatic re-run of CMake.
   And voila, you have now by-passed the restriction of not being allowed to change the list of snippets in use.
   

So to me, the introduction of `SNIPPET_APP` is a no-go, unless we want to remove the `zephyr_check_cache()` restriction, which again would mean that we should probably update `snippets.cmake` to use `zephyr_get(SNIPPET MERGE SYSBUILD GLOBAL)` instead.
(That might even be a good idea regardless of above, but I haven't looked detailed enough at the snippets.cmake code to fully see if such change is feasible)

**Comment by JordanYates** [comment]
> Users are not allowed to change the active list of snippets after first CMake invocation.

The current setup prevents users from changing the active list on the first CMake invocation as well.
Adding `list(APPEND SNIPPET "snippet3;snippet4")` to `CMakeLists.txt` will never result in `snippet3` or `snippet4` being applied, no matter how clean the build.

I appreciate the concern about users changing the values after the first build, I am happy to lock down the value of `SNIPPET_APP` so that it cannot be changed after the first CMake invocation. I assume `zephyr_check_cache(SNIPPET_APP WATCH)` is sufficient?

**Comment by JordanYates** [comment]
> > Users are not allowed to change the active list of snippets after first CMake invocation.
> 
> The current setup prevents users from changing the active list on the first CMake invocation as well. Adding `list(APPEND SNIPPET "snippet3;snippet4")` to `CMakeLists.txt` will never result in `snippet3` or `snippet4` being applied, no matter how clean the build.
> 
> I appreciate the concern about users changing the values after the first build, I am happy to lock down the value of `SNIPPET_APP` so that it cannot be changed after the first CMake invocation. I assume `zephyr_check_cache(SNIPPET_APP WATCH)` is sufficient?

ping @tejlmand

**Comment by tejlmand** [comment]
> ping @tejlmand

this piece of code seems to work fine, even without this PR:
```
if(NOT snipA IN_LIST SNIPPET)
  set(SNIPPET snipA ${SNIPPET} CACHE STRING "" FORCE)
#endif()

find_package(Zephyr ....)

...
```

```
# First run, without a user provided snippet:
$ cmake -GNinja -DBOARD=mps3_an547 -Bbuild samples/hello_world/
Loading Zephyr default modules (Zephyr repository).
-- Application: /projects/github/ncs/zephyr/samples/hello_world
...
-- Board: mps3_an547
-- Snippet(s): snipA

# Re-run:
$ cmake build/
cmake build/
Loading Zephyr default modules (Zephyr base (cached)).
...
-- Board: mps3_an547
-- Snippet(s): snipA
```

Providing an extra user required snippet:
```
# First run:
$ cmake -GNinja -DBOARD=mps3_an547 -Bbuild samples/hello_world/ -DSNIPPET=snipB
Loading Zephyr default modules (Zephyr repository).
-- Application: /projects/github/ncs/zephyr/samples/hello_world
...
-- Board: mps3_an547
-- Snippet(s): snipA snipB
```

And trying to change value of SNIPPETS after first build:
```
$ cmake build/ -DSNIPPET=snipC
Loading Zephyr default modules (Zephyr base (cached)).
-- Application: /projects/github/ncs/zephyr/samples/hello_world
...
-- Board: mps3_an547
CMake Warning at /projects/github/ncs/zephyr/cmake/modules/extensions.cmake:2854 (message):
  The build directory must be cleaned pristinely when changing snippet,

  Current value="snipA;snipB", Ignored value="snipA;snipC"
Call Stack (most recent call first):
  /projects/github/ncs/zephyr/cmake/modules/snippets.cmake:40 (zephyr_check_cache)
  /projects/github/ncs/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /projects/github/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /projects/github/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  CMakeLists.txt:9 (find_package)

-- Snippet(s): snipA snipB
...
```

Seems main is working as intended.

**Comment by JordanYates** [comment]
> > ping @tejlmand
> 
> this piece of code seems to work fine, even without this PR:
> 
> ```
> if(NOT snipA IN_LIST SNIPPET)
>   set(SNIPPET snipA ${SNIPPET} CACHE STRING "" FORCE)
> endif()
> 
> find_package(Zephyr ....)
> 
> ...
> ```
> 
> ```
> # First run, without a user provided snippet:
> $ cmake -GNinja -DBOARD=mps3_an547 -Bbuild samples/hello_world/
> Loading Zephyr default modules (Zephyr repository).
> -- Application: /projects/github/ncs/zephyr/samples/hello_world
> ...
> -- Board: mps3_an547
> -- Snippet(s): snipA
> 
> # Re-run:
> $ cmake build/
> cmake build/
> Loading Zephyr default modules (Zephyr base (cached)).
> ...
> -- Board: mps3_an547
> -- Snippet(s): snipA
> ```
> 
> Providing an extra user required snippet:
> 
> ```
> # First run:
> $ cmake -GNinja -DBOARD=mps3_an547 -Bbuild samples/hello_world/ -DSNIPPET=snipB
> Loading Zephyr default modules (Zephyr repository).
> -- Application: /projects/github/ncs/zephyr/samples/hello_world
> ...
> -- Board: mps3_an547
> -- Snippet(s): snipA snipB
> ```
> 
> And trying to change value of SNIPPETS after first build:
> 
> ```
> $ cmake build/ -DSNIPPET=snipC
> Loading Zephyr default modules (Zephyr base (cached)).
> -- Application: /projects/github/ncs/zephyr/samples/hello_world
> ...
> -- Board: mps3_an547
> CMake Warning at /projects/github/ncs/zephyr/cmake/modules/extensions.cmake:2854 (message):
>   The build directory must be cleaned pristinely when changing snippet,
> 
>   Current value="snipA;snipB", Ignored value="snipA;snipC"
> Call Stack (most recent call first):
>   /projects/github/ncs/zephyr/cmake/modules/snippets.cmake:40 (zephyr_check_cache)
>   /projects/github/ncs/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
>   /projects/github/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
>   /projects/github/ncs/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
>   CMakeLists.txt:9 (find_package)
> 
> -- Snippet(s): snipA snipB
> ...
> ```
> 
> Seems main is working as intended.

Thanks for the working CMake snippet, I tried a few things without success before implementing this.

I have documented this process in #68181

**Pull request closed without merging**
