### PR TITLE
ext: hal: cmsis: Update ARM CMSIS headers to version 5.6.0

### PR DESCRIPTION
**Pull request by galak**
Origin: ARM CMSIS v5.6.0
License: Apache-2.0
URL: https://github.com/ARM-software/CMSIS_5.git
commit: b5f0603d6a584d1724d952fd8b0737458b90d62b
Purpose: CMSIS Headers update.
Maintained-by: External

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
Looks good. Seems we don't need to add our own compiler barriers, now, in our irq_lock, unlock, if we are using the NVIC CMSIS functions.

Should we open an issue for that?

**Comment by galak** [comment]
> Looks good. Seems we don't need to add our own compiler barriers, now, in our irq_lock, unlock, if we are using the NVIC CMSIS functions.
> 
> Should we open an issue for that?

Worth while doing.  Leave that up to you as the ARM maintainer ;).

**Comment by ioannisg** [comment]
> 
> 
> > Looks good. Seems we don't need to add our own compiler barriers, now, in our irq_lock, unlock, if we are using the NVIC CMSIS functions.
> > Should we open an issue for that?
> 
> Worth while doing. Leave that up to you as the ARM maintainer ;).

Fair point ;)

**Review by ioannisg — APPROVED** [review]

**Comment by mbolivar** [comment]
Not nacking, just asking: why not move this to a west module?

**Comment by galak** [comment]
> Not nacking, just asking: why not move this to a west module?

@nashif had some reason I felt that he didn't when we pulled all the HALs out.

One minor reason is the footprint size of the the full CMSIS_5 repo is 146M v 1.8M for the include dir we have today.

**Comment by ioannisg** [comment]
> 
> 
> > Not nacking, just asking: why not move this to a west module?
> 
> @nashif had some reason I felt that he didn't when we pulled all the HALs out.
> 
> One minor reason is the footprint size of the the full CMSIS_5 repo is 146M v 1.8M for the include dir we have today.

That's a good point, actually. Although, you wouldn't check this out all the time when you fetch zephyr; that would be done once, hopefully.

Also, I've heard another argument, from the same source. Without cmsis in the tree, we would need external dependency to build/run ARM Qemu targets.

**Comment by ioannisg** [comment]
@galak seems we need to address an issue if we wish to upgrade to using 5.6.0.
Apparently, CMSIS gcc (as well as other toolchain-specific headers) defines `cmsis_start`() function that uses linker symbols (e.g. `__copy_table_start__`, `__copy_table_end__ `etc.) defined in the provided scripts, which, however, we do not use in our linker script structure.

**Comment by galak** [comment]
> @galak seems we need to address an issue if we wish to upgrade to using 5.6.0.
> Apparently, CMSIS gcc (as well as other toolchain-specific headers) defines `cmsis_start`() function that uses linker symbols (e.g. `__copy_table_start__`, `__copy_table_end__ `etc.) defined in the provided scripts, which, however, we do not use in our linker script structure.

Agreed.  I noticed that CI was failing with the PR but haven't had time to see what the details actually are.

**Comment by ioannisg** [comment]
> Agreed. I noticed that CI was failing with the PR but haven't had time to see what the details actually are.

@galak I added a commit on top of the CMSIS bump to 5.6.0, which defines __PROGRAM_START, with some documentation. I believe this should be fine, to avoid build errors with the new CMSIS init routines.

**Pull request merged**
