### PR TITLE
[TOPIC-GPIO] Clean up on stm32 gpio driver

### PR DESCRIPTION
**Pull request by erwango**
Based on #20115

commit b1d56bc
```
Author: Erwan Gouriou <erwan.gouriou@linaro.org>
Date:   Fri Dec 13 14:53:18 2019 +0100

    drivers/gpio: stm32: Align arguments types on few api functions
    
    Somehow, types used in some api functions where not in line with
    api.
    Fix this.
    
    Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>
```

commit b57a362
```
Author: Erwan Gouriou <erwan.gouriou@linaro.org>
Date:   Fri Dec 13 09:54:27 2019 +0100

    drivers/gpio: stm32: Remove pin ordinals validation in driver
    
    Since pin ordinal validation is now done directly in gpio API,
    remove checks inside the driver itself.
    
    Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>
```

### CODE REVIEW

**Comment by mnkp** [comment]
Maybe this PR should target #20115 and not topic-gpio?

**Comment by pabigot** [comment]
DNM since this needs to be done after #20115 is merged, or I can integrate it into #20115.  Also `available` changed to `port_pin_mask` in response to review comments.

@erwango Do you want me to merge your commits into #20115 and update them for the new API?

**Comment by erwango** [comment]
> @erwango Do you want me to merge your commits into #20115 and update them for the new API?

Would be nice. Thanks

**Comment by pabigot** [comment]
> Would be nice. Thanks

The commit added here to remove the driver check for pin number has been merged with the commit that sets the common mask field in #20115.

The commit added here to align formal arguments with the declaration has been added to #20115.

@erwango Please verify that's what you intend and close this if there's no reason to keep it open.

**Comment by erwango** [comment]
> @erwango Please verify that's what you intend and close this if there's no reason to keep it open

@pabigot verified, thanks

**Pull request closed without merging**
