### PR TITLE
modules: hal_nordic: Update nrfx to version 1.8.1

### PR DESCRIPTION
**Pull request by anangl**
See https://github.com/zephyrproject-rtos/hal_nordic/pull/10

---

Update nrfx to the recently released version. See
https://github.com/NordicSemiconductor/nrfx/blob/v1.8.1/CHANGELOG.md
for a list of changes that this version introduces.

Origin: nrfx
License: BSD 3-Clause
URL: https://github.com/NordicSemiconductor/nrfx/tree/v1.8.1
commit: ecc3616b8ea766ba0c921681258463696ad47930
Purpose: Provide peripheral drivers for Nordic SoCs
Maintained-by: External

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Comment by anangl** [comment]
Re-triggered CI.

**Comment by carlescufi** [comment]
Please update with a SHA

**Review by ioannisg — COMMENTED** [review]
@anangl please update the PR since 1.8.1 is merged now

**Comment by anangl** [comment]
> @anangl please update the PR since 1.8.1 is merged now

Done.

**Review by ioannisg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
