### PR TITLE
Bluetooth: controller: split: Fix flash driver co-operation

### LINKED ISSUE #19484: Bluetooth: split:  bt_set_name() asserts due to flash and radio coex
**Describe the bug**
Using the split ll calling `bt_set_name()` **sometimes** fails even though no radio activity is present.
This appears to be only happening when a LE scan was started before (and stopped). Independent of the duty cycle.

**To Reproduce**
image

Happens after a couple of loops on nrf52840_dks. Only happens with `test1()` and `test2()`. Removing either of them appears to never run in the assertion.

**Expected behavior**
No assert.

**Impact**
showstopper.

**Screenshots or console output**
```
ASSERTION FAIL [ll_radio_state_is_idle()] @ ZEPHYR_BASE/drivers/flash/soc_flash_nrf.c:291␍␊
[15:04:10:857] ⇥    Radio is on during flash operation.␍␊
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Kubuntu 18.04
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.10.3
 - Commit SHA or Version used: 2051ad184614f02975ea8ba923cf5bff13c2535a

**Additional context**

### PR DESCRIPTION
**Pull request by cvinayak**
When flash driver requests abort of radio event in unreserved
time space, resume radio events in the pipeline where not
flushed. These resumed events caused flash driver to assert
on the check whether radio was in use.

Fixed by flushing the pipeline of all radio events, resume
and also those events in pipeline with pre-empt timeout
being setup.

Fixes: #19484.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
@tsvehagen could you please test this PR to see if it resolves your issue?

**Comment by nvlsianpu** [comment]
cc @ppryga

**Comment by tsvehagen** [comment]
> @tsvehagen could you please test this PR to see if it resolves your issue?

Yes I will have look and get back

**Comment by tsvehagen** [comment]
> @tsvehagen could you please test this PR to see if it resolves your issue?

I have experienced the same assert even with this fix. The same assert is also present in zephyr-v2.0.0 (although I didn't apply the patch when I used that tag). The message looked like this for zephyr-v2.0.0.

```
ASSERTION FAIL [ll_radio_state_is_idle()] @ ZEPHYR_BASE/drivers/flash/soc_flash_nrf.c:291
        Radio is on during flash operation.

FATAL: r0/a1:  0x00000004  r1/a2:  0x00000123  r2/a3:  0x00000001
FATAL: r3/a4:  0x0003da49 r12/ip:  0x00027351 r14/lr:  0x00027aef
FATAL:  xpsr:  0x6100001b
FATAL: Faulting instruction address (r15/pc): 0x0002c43e
FATAL: >>> ZEPHYR FATAL ERROR 4: Kernel panic
FATAL: Current thread: 0x20001f44 (idle)
FATAL: Halting system
```

**Comment by tsvehagen** [comment]
This fix seems to solve the problem. I haven't gotten any assert with the patch applied.

**Comment by cvinayak** [comment]
@carlescufi this can me merged.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
