### PR TITLE
Changed initialization order of structs for C++ compatability

### PR DESCRIPTION
**Pull request by moritzstoetter**
Changed initialization order of structs in two macros for C++ compatability

### CODE REVIEW

**Comment by Thalley** [comment]
@moritzstoetter Not rejecting this change, but could you elaborate your (empty) commit message?
What compatability are you fixing? What is the error that you'd otherwise get?

**Comment by moritzstoetter** [comment]
Hi @Thalley,

in C++ struct designator order must match the order of declaration.

So this example won't compile (in C++): https://godbolt.org/z/v6cfWM5Kd

`struct A {
    int a;
    int b;
};

A s = A{.b = 1, .a = 2};`

I reordered the designators in the macros accordingly.

**Comment by Thalley** [comment]
> Hi @Thalley,
> 
> in C++ struct designator order must match the order of declaration.
> 
> So this example won't compile (in C++): https://godbolt.org/z/v6cfWM5Kd
> 
> `struct A { int a; int b; };
> 
> A s = A{.b = 1, .a = 2};`
> 
> I reordered the designators in the macros accordingly.

Thanks! 
I haven't touched C++ in ages, so was unaware of this requirement, which seems to have been added in C++20: https://en.cppreference.com/w/cpp/language/aggregate_initialization

As per https://docs.zephyrproject.org/latest/develop/languages/cpp/index.html Zephyr supports C++11, which is why we haven't done these type of changes / insurances. 

If you decide to use C++20 instead of C++11 in your application, you may encounter way more issues than just this, as C++20 clearly is not backwards compatible, nor supported. 

I'd be happy to accept your change request, but I would suggest to expand your commit message (and not just PR description) with the reasoning

**Review by gmarull — CHANGES_REQUESTED** [review]
please, check https://docs.zephyrproject.org/latest/contribute/guidelines.html

**Comment by moritzstoetter** [comment]
I am not sure when this was added. But it's definitely been the case for C++11.

See this Godbolt link for the same example as above with 11: https://godbolt.org/z/hKffbKxfr 

I'll update the commit message, so we can get this in.

**Comment by moritzstoetter** [comment]
Also, there are most probably other macros that suffer from the same issue. So you might want to keep an eye out for this.

**Comment by moritzstoetter** [comment]
@Thalley I just added a commit message that explains the reason for this pr.

**Comment by Thalley** [comment]
@moritzstoetter Looks like something broke in your PR :)

**Comment by moritzstoetter** [comment]
> please, check https://docs.zephyrproject.org/latest/contribute/guidelines.html

I followed the workflow (https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow) to the letter, and the check still complains that the signature 'must have a full name'. Which, to be honest, I think it does. 

I find the error messages here not super helpful. Also the docs are really much longer and more spread out than I'd like them to be.

**Comment by Thalley** [comment]
> > please, check https://docs.zephyrproject.org/latest/contribute/guidelines.html
> 
> I followed the workflow (https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow) to the letter, and the check still complains that the signature 'must have a full name'. Which, to be honest, I think it does.
> 
> I find the error messages here not super helpful. Also the docs are really much longer and more spread out than I'd like them to be.

Just to make sure, did you use the `git commit -s` or `git commit --amend --signoff` when adding the lines? 

If you did, I wonder if it is related to you using a non-ascii character in your last name (Stötter). 

Finally, it looks like you've added 2 commits, rather than amending the first one

**Comment by moritzstoetter** [comment]
git commit --amend --signoff

I think

**Pull request closed without merging**
