### PR TITLE
scripts: edtlib: Add easy redirection of warnings

### PR DESCRIPTION
**Pull request by ulfalizer**
Add a 'warn_file' parameter to EDT.\_\_init\_\_() that gives a 'file' object
to write warnings to. Use it to capture and verify warnings generated
for deprecated features in testedtlib.py. This indirectly gets rid of
possibly broken-looking output when running it.

Because any function that writes warnings now needs to use EDT._warn()
(as self._warn()), some functions were moved into the EDT class.

### CODE REVIEW

**Comment by ulfalizer** [comment]
Builds on https://github.com/zephyrproject-rtos/zephyr/pull/19421, so it needs to go in first.

**Review by pabigot — CHANGES_REQUESTED** [review]
The warnings stuff looks fine, but there's a change to `#cells` that doesn't belong in this PR.

**Comment by ulfalizer** [comment]
@pabigot 
Yeah, see this earlier comment:

> Builds on #19421, so it needs to go in first.

That's why it's marked DNM.

**Comment by ulfalizer** [comment]
Hmm... seems this got in somehow. Maybe it was pushed manually.

**Pull request closed without merging**
