### PR TITLE
Support for 8 & 16 MB SRAM regions in Cortex M MPU

### PR DESCRIPTION
**Pull request by johan-ohman**
Added support for 8 MB MPU regions for SRAM sizes between 4 and 8 MB, and 16 MB MPU regions for SRAM sizes between 8 and 16 MB.

Signed-off-by: Johan Öhman <johan.ohman@softube.com>

### CODE REVIEW

**Review by galak — DISMISSED** [review]

**Review by MaureenHelm — COMMENTED** [review]
Need to fix the compliance failure, but otherwise the changes look good.
```
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

3e38f1a9a9f0fce87c33c96ef7f83aa96c7f126e: author email (johan-ohman <102667119+johan-ohman@users.noreply.github.com>) needs to match one of the signed-off-by entries.
3e38f1a9a9f0fce87c33c96ef7f83aa96c7f126e: author email (johan-ohman <102667119+johan-ohman@users.noreply.github.com>) does not follow the syntax: First Last <email>.
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

1: UC3 Title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "Support for 8 & 16 MB SRAM regions in Cortex M MPU"
3: UC4 Line exceeds max length (1[27](https://github.com/zephyrproject-rtos/zephyr/runs/5754358916?check_suite_focus=true#step:9:27)>75): "Added support for 8 MB MPU regions for SRAM sizes between 4 and 8 MB, and 16 MB MPU regions for SRAM sizes between 8 and 16 MB."
Error: Process completed with exit code 1.
```

**Review by microbuilder — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Comment by microbuilder** [comment]
You still need to amend the author for the commit:

```
author email (johan-ohman <102667119+johan-ohman@users.noreply.github.com>)
```

Try something like:

```bash
$ git commit --amend --author "..."
```

**Comment by microbuilder** [comment]
You can also change the author for the whole repo:

```bash
$ git config user.email <addr>
$ git config user.name "First Last"
$ git commit --amend --reset-author
$ git push -f origin my-branch
```

**Comment by johan-ohman** [comment]
Thank you for the feedback!
I thought the author info would update automatically when I amended the commit in GitKraken.
But now I know differently and have fixed it! Hopefully it will go through the compliance tests this time.

**Review by microbuilder — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
