### PR TITLE
modules: hal_silabs: Add Proprietary TRX example

### PR DESCRIPTION
**Pull request by silabs-ZoltanH**
Add Proprietary TRX example to show SiliconLabs radio board capabilities.

### CODE REVIEW

**Comment by zohavas** [comment]
I would like to remove the stale label, the submodule  PR is ready and approved waiting for the merge.

**Comment by nordicjm** [comment]
If I understand this correctly, this is tired to one specific piece of hardware from one vendor and requires binary blobs to even be used - what is the value of this being added here?

@nashif shouldn't this be something for the TSC?

**Comment by zohavas** [comment]
> If I understand this correctly, this is tired to one specific piece of hardware from one vendor and requires binary blobs to even be used - what is the value of this being added here?
> 
> @nashif shouldn't this be something for the TSC?

Hi @nordicjm,
Yes this sample application will be able to be only used with silabs hardware, that's why it is position in the silabs_hal repository. 
This can be used with any already supported Siliconlab board with the help of the Radio Configurator from Studio.
We want to show the radio capability of the gecko software and silabs hardware, that why we chosen this repository for user to easily find the correct way to use the radio functions.
We have already a similar discussion in the repo PR: https://github.com/zephyrproject-rtos/hal_silabs/pull/49#issuecomment-1880998345

**Comment by zohavas** [comment]
@henrikbrixandersen I would like to ask if [area: Blobs] is correct as I don't add or modify any libs, only use the existing ones.

**Comment by fabiobaltieri** [comment]
Hey this is not build in CI in the current state right? I was under the impression that it was (other modules have tests that are included in the normal CI run). If that's the case, distributing this with the OS had limited value, the idea here is that the sample code that ships with the project is maintained and kept up to date, at least it should be built tested.

Regardless, what I'm thinking is that having the sample in the module is going to be a potential extra load for API maintenance, say one of the sample API change, the author of the change has do do the whole module change dance.

On the other side, if this is in the main repository, a change of the binary blob or hal api would result in the extra step to change the main repo code, but then that's already case as changing the module involve a main PR anyway to update the west file.

So with that in mind I think that that having the sample in the module is a net negative, and this should be:
- moved in the main repo
- get an extra review (at first sight some api and styling are off)
- be relicenced like the other sample
- get an extra review
- get a build file so it gets build tested

There's an argument about having a sample backed by a proprietary blob module but frankly I don't see that as being different than any ble/wifi samples, I think we have platforms with blob for power management as well.

**Comment by tgorochowik** [comment]
I agree with Fabio, in addition I think we should rename this sample from "proprietary" to something else, if there is no dedicated name then maybe something more descriptive, as the code of this sample is not really proprietary, it's just the blob that is proprietary

**Pull request closed without merging**
