### PR TITLE
json: support parsing and serializing 'struct sensor_value'

### PR DESCRIPTION
**Pull request by mniestroj**
Up to now there was only support for parsing/encoding integer
numbers, with no support for real numbers.

This patch introduces support for parsing and encoding 'struct
sensor_value' variables. That way precision of this data type
is preserved, without adding heavy floating point to/from string
convertion functions. Introduced feature is especially helpful for
applications sending sensor measurements using high-level network
protocols (e.g. HTTP REST API).

Introduced code is 100% dependent on new JSON_LIBRARY_SENSOR_VALUE
Kconfig option. Hence these changes do not increase code size when
not used.

### CODE REVIEW

**Comment by mniestroj** [comment]
Just fixed "warning: array subscript has type 'char' [-Wchar-subscripts]" with newlib.

**Review by andyross — CHANGES_REQUESTED** [review]
This is.... kinda weird.  JSON is a generic interchange format.  It doesn't, and shouldn't, have intelligence about what a "sensor value" is.

I **think** what you're trying to do here is add support for some kind of Zephyr-internal non-integer format using the JSON IEEE-like floating point expressions as the string representation?  If so, do that elsewhere, not in the JSON layer itself.

Then add some kind of glue like a "non-integer value type" handler in the json parser, where the outer code can register what it wants, appropriate to its use case.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
I agree with @andyross it seems deeply problematic that we are changing the JSON parser itself to handle a data type we invented, such a change makes any files that use it no longer JSON...

**Comment by mniestroj** [comment]
Thanks for your input!

> This is.... kinda weird. JSON is a generic interchange format. It doesn't, and shouldn't, have intelligence about what a "sensor value" is.

I don't add "sensor value" to JSON, but to JSON parser/serializer. In case of JSON serializer an output will be "number" type descibed in https://tools.ietf.org/html/rfc7159#section-6 including integer part + fractional part (`int[.frac]`). In case of JSON parser situation is a bit worse, as it will just be able to parse subset of number representations. But so far we were okay with "number" values that were strictly integers. So still there is improvement there.

I'll try in other words. So far we just handled subset of possible representations of "number" type in JSON, i.e. integer number (`123`). Here we extend the implementation to handle numbers with decimal point (`123.45`).

Indeed `struct sensor_value` is internal Zephyr type. There is a reason why we use it inside sensor drivers instead of `double` or `float`. Question is: why shouldn't we use `struct sensor_value` instead of `double`?

> I **think** what you're trying to do here is add support for some kind of Zephyr-internal non-integer format using the JSON IEEE-like floating point expressions as the string representation? If so, do that elsewhere, not in the JSON layer itself.

I am not using strings here. The output of serialized `struct sensor_value` is "number", which is 100% conformant with JSON specification.

>I agree with @andyross it seems deeply problematic that we are changing the JSON parser itself to handle a data type we invented, such a change makes any files that use it no longer JSON...

I don't agree with that :) In my opinion serializing `sensor_value` with the implementation in this PR is okay with the grammar of "number" type in JSON (https://tools.ietf.org/html/rfc7159#section-6 or https://www.json.org/).

**Comment by andrewboie** [comment]
> I don't agree with that :) In my opinion output of serialized sensor_value by the implementation in this PR is okay with the grammar of "number" type in JSON (tools.ietf.org/html/rfc7159#section-6 or json.org).

Then implement the missing type from a generic JSON perspective. And build sensor stuff on top of that. I do not think you should be modifying the JSON parser itself with the notion of "sensors" directly.

**Comment by mniestroj** [comment]
>Then implement the missing type from a generic JSON perspective. And build sensor stuff on top of that. I do not think you should be modifying the JSON parser itself with the notion of "sensors" directly.

Do you mean that I should add something like:
```
struct json_fixed_point {
      int32_t val1;
      int32_t val2;
};
```
and just replace `sensor_value` with `json_fixed_point` in current implementation?

**Comment by andrewboie** [comment]
> > Then implement the missing type from a generic JSON perspective. And build sensor stuff on top of that. I do not think you should be modifying the JSON parser itself with the notion of "sensors" directly.
> 
> Do you mean that I should add something like:
> 
> ```
> struct json_fixed_point {
>       int32_t val1;
>       int32_t val2;
> };
> ```
> 
> and just replace `sensor_value` with `json_fixed_point` in current implementation?

I don't really care how you solve this, as long as nothing about "sensors" appears in lib/os/json.c or its associated header

**Comment by andyross** [comment]
Probably better something like:

```c
struct json_float {
    int64_t dec;
    int16_t exp10;
};
```

So "-98765.4321" would be represented as "`{ .dec = -987654321, .exp10 = -4 }`".  This is non-lossy and still (relatively) easily convertible to the existing sensor value.  You could cheat with sizes if you don't need to cover the range of a full IEEE double, I guess.

**Pull request closed without merging**
