### PR TITLE
modules: mbedtls: use proper memory alignment on 64-bit platforms

### PR DESCRIPTION
**Pull request by vg-sc**
This commit instructs mbedtls to use 64-bit alignment in its internal memory allocation routines when targeting 64-bit platforms. By default mbedtls uses 32-bit alignment regardless the platform, what may result in misaligned memory accesses, possibly inducing access time overhead or exceptions

### CODE REVIEW

**Review by ceolin — APPROVED** [review]

**Comment by vg-sc** [comment]
@d3zd3z, please have a look

**Comment by vg-sc** [comment]
@d3zd3z, please review

**Comment by vg-sc** [comment]
@d3zd3z, ping

**Comment by vg-sc** [comment]
@d3zd3z, did you have a chance to have a look?

**Comment by vg-sc** [comment]
@d3zd3z, please review

**Comment by vg-sc** [comment]
@ceolin, could you please remove stale label and maybe ping @d3zd3z?

**Comment by vg-sc** [comment]
> Wouldn't using `__alignof__` be more appropriate?

@kartben, that's not really obvious alignment of which type to use. To be completely safe, it should be something like ```__alignof__(unsigned long long)```, but it's an overkill for 32-bit platforms - 4 byte alignment seems to suffice. So the idea of ```sizeof(void *)``` is to explicitly set 4-byte alignment for 32-bit platforms and 8-byte for 64-bit ones. This should be enough for any real board. However, if necessary, alignment can be set to any desired value in custom config

**Comment by vg-sc** [comment]
@d3zd3z, please review

**Comment by vg-sc** [comment]
@d3zd3z, please review

**Review by carlescufi — APPROVED** [review]

**Comment by vg-sc** [comment]
Thanks!

**Pull request merged**
