### PR TITLE
drivers: modem: gsm: some misc improvements

### LINKED ISSUE #39144: gsm_ppp: stop & starting not working as expected with nullpointer dereference & no full modem init
**Describe the bug**
When stopping & starting the modem, the rssi_work_handle can lead to nullpointer crash in the timeout.c::remove_timeout. This due to the re-initialization of the rssi_work_handle in the gsm start, while the work was still sheduled (so re-init the sys_snode_t to nullpointers).
A similar error could occur with the gsm_configure if the stop & start is done while it's work is still ongoing (although very little chance since init & reshedule is just after eachother)

Next to the crash, when the modem starts, not all commands are re-executed due to a flag being set in the previous gsm_configure stage:
gsm_finalize_connection: gsm->attached. This leads to skipping the setup commands the next gsm start (like echo & disabling URC for network registration).

**To Reproduce**
```
//First time startup of the 
gsm_ppp_stop()
modem_reset() //own function --> takes about 12 seconds
gsm_ppp_start()

// Wait some time like 40 seconds
gsm_ppp_stop()
modem_reset() //own function --> takes about 12 seconds
gsm_ppp_start()
--> sometimes crash at this point 
```
Reproduction rate is about 70% for me

**Environment (please complete the following information):**
I'm using the GSM_MUX configuration with a Quectell BG95.
MODEM_GSM_RSSI_POLLING_PERIOD is set to 30 (I think it will be less visible with bigger timeouts)
This work is done on the 2.7.0-rc1 branch + single commit to fix PPP UART name

### PR DESCRIPTION
**Pull request by ycsin**
Some misc improvements for the `gsm_ppp` driver.

### CODE REVIEW

**Comment by ycsin** [comment]
cc @bbilas @wcappelle @endian-benjamin

**Review by rlubos — COMMENTED** [review]
IMHO looks reasonable, however please have a look at the CI result, the build failures seem relevant to your changes.

**Review by rerickson1 — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by bbilas — APPROVED** [review]

**Comment by HrMitrev** [comment]
Hi! After I updated my zephyr repo todat my code crashes:
```
00> [00:00:12.716,644] <err> os: ***** BUS FAULT *****
00> [00:00:12.716,644] <err> os:   Precise data bus error
00> [00:00:12.716,674] <err> os:   BFAR Address: 0xffffebb0
00> [00:00:12.716,674] <err> os: r0/a1:  0xffffeb9c  r1/a2:  0xffffebac  r2/a3:  0x00011d9c
00> [00:00:12.716,674] <err> os: r3/a4:  0x00000001 r12/ip:  0x00000000 r14/lr:  0x00007b35
00> [00:00:12.716,674] <err> os:  xpsr:  0x61000000
00> [00:00:12.716,674] <err> os: Faulting instruction address (r15/pc): 0x000104fc
00> [00:00:12.716,705] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
00> [00:00:12.716,705] <err> os: Current thread: 0x20001b68 (unknown)
00> [00:00:12.989,593] <err> os: Halting system
```

I've tracked the problem to  - d9ea07b7bd drivers: modem: gsm: convert work to delayable work
if I checkout                         - b2b9343c95 drivers: modem: gsm: declare structs in gsm_modem,
my code works.

here's the backtrace although It doesn't seem very useful:
```
#0  arch_system_halt (reason=reason@entry=0) at /home/hrm/git/zephyr_sdk/zephyr/kernel/fatal.c:32
#1  0x0000a26a in k_sys_fatal_error_handler (reason=reason@entry=0, esf=esf@entry=0x20007ad0 <z_interrupt_stacks+1976>) at /home/hrm/git/zephyr_sdk/zephyr/kernel/fatal.c:44
#2  0x0000a300 in z_fatal_error (reason=reason@entry=0, esf=esf@entry=0x20007ad0 <z_interrupt_stacks+1976>) at /home/hrm/git/zephyr_sdk/zephyr/kernel/fatal.c:127
#3  0x000023c0 in z_arm_fatal_error (reason=reason@entry=0, esf=esf@entry=0x20007ad0 <z_interrupt_stacks+1976>) at /home/hrm/git/zephyr_sdk/zephyr/arch/arm/core/aarch32/fatal.c:63
#4  0x00002952 in z_arm_fault (msp=<optimized out>, psp=<optimized out>, exc_return=<optimized out>, callee_regs=<optimized out>) at /home/hrm/git/zephyr_sdk/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:1051
#5  0x00002a64 in z_arm_usage_fault () at /home/hrm/git/zephyr_sdk/zephyr/arch/arm/core/aarch32/cortex_m/fault_s.S:102
#6  <signal handler called>
#7  0x86a02cea in ?? ()
#8  0x22f9d670 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

If I can compile with additional logs which may be helpful to you, please let me know :)

**Comment by ycsin** [comment]
@HrMitrev You reckon d9ea07b is causing the problem? I'll need to have a look tomorrow

**Comment by HrMitrev** [comment]
```
00> [00:00:02.311,279] <dbg> modem_gsm.gsm_configure: modem not ready -116
00> [00:00:02.311,309] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:04.311,553] <dbg> modem_gsm.gsm_configure: modem not ready -116
00> [00:00:04.311,584] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:06.311,828] <dbg> modem_gsm.gsm_configure: modem not ready -116
00> [00:00:06.311,859] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:06.313,323] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.313,323] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.316,345] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+COPS:] (len:8)
00> [00:00:06.316,864] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.316,864] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.318,664] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.318,664] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.370,086] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.370,117] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.422,149] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.422,180] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.474,121] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.474,121] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.528,076] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.528,076] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.530,212] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [] (len:7)
00> [00:00:06.530,212] <inf> modem_gsm: Manufacturer: Quectel
00> [00:00:06.530,731] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.530,731] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.583,129] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [] (len:9)
00> [00:00:06.583,160] <inf> modem_gsm: Model: BG600L-M3
00> [00:00:06.583,648] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.583,648] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.636,718] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [] (len:16)
00> [00:00:06.636,749] <inf> modem_gsm: Revision: BG600LM3LAR02A04
00> [00:00:06.637,237] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.637,237] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.690,338] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [] (len:15)
00> [00:00:06.690,338] <inf> modem_gsm: IMEI: 860873041067108
00> [00:00:06.690,826] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.690,856] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:06.693,328] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+CGATT:] (len:9)
00> [00:00:06.693,420] <dbg> modem_gsm.gsm_finalize_connection: Not attached, retrying...
00> [00:00:06.693,847] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:06.693,847] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:07.693,481] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:07.694,793] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:07.694,824] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:07.697,387] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+CGATT:] (len:9)
00> [00:00:07.697,479] <dbg> modem_gsm.gsm_finalize_connection: Not attached, retrying...
00> [00:00:07.697,906] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:07.697,906] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:08.697,540] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:08.698,791] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:08.698,791] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:08.701,293] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+CGATT:] (len:9)
00> [00:00:08.701,385] <dbg> modem_gsm.gsm_finalize_connection: Not attached, retrying...
00> [00:00:08.701,812] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:08.701,843] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:09.701,446] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:09.702,667] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:09.702,667] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:09.705,169] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+CGATT:] (len:9)
00> [00:00:09.705,261] <dbg> modem_gsm.gsm_finalize_connection: Not attached, retrying...
00> [00:00:09.705,688] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:09.705,688] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:10.705,322] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:10.706,542] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:10.706,573] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:10.709,045] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+CGATT:] (len:9)
00> [00:00:10.709,136] <dbg> modem_gsm.gsm_finalize_connection: Not attached, retrying...
00> [00:00:10.709,564] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:10.709,564] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:11.709,197] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration
00> [00:00:11.710,418] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:11.710,449] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:11.713,012] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+CGATT:] (len:9)
00> [00:00:11.713,104] <dbg> modem_gsm.gsm_finalize_connection: Not attached, retrying...
00> [00:00:11.713,531] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:11.713,531] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:12.713,165] <dbg> modem_gsm.gsm_configure: Starting modem 0x20000780 configuration[0m
00> [00:00:12.714,416] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [OK] (len:2)
00> [00:00:12.714,416] <dbg> modem_gsm.gsm_cmd_ok: ok
00> [00:00:12.716,918] <dbg> modem_cmd_handler.cmd_handler_process_rx_buf: match cmd [+CGATT:] (len:9)
00> [00:00:12.716,918] <inf> modem_gsm: Attached to packet service!
00> [00:00:12.717,010] <dbg> modem_gsm.gsm_finalize_connection: modem attach returned 0, read RSSI
00> [00:00:12.717,010] <err> os: ***** BUS FAULT *****
00> [00:00:12.717,010] <err> os:   Precise data bus error
00> [00:00:12.717,010] <err> os:   BFAR Address: 0xffffebb0
00> [00:00:12.717,041] <err> os: r0/a1:  0xffffeb9c  r1/a2:  0xffffebac  r2/a3:  0x00011f8c[0m
00> [00:00:12.717,041] <err> os: r3/a4:  0x00000001 r12/ip:  0x200003d8 r14/lr:  0x00007c83
00> [00:00:12.717,041] <err> os:  xpsr:  0x41000000
00> [00:00:12.717,041] <err> os: Faulting instruction address (r15/pc): 0x00010708
00> [00:00:12.717,041] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
00> [00:00:12.717,071] <err> os: Current thread: 0x20001b68 (unknown)
00> [00:00:13.152,526] <err> os: Halting system
```

That's the verbose log. Hope it helps. But I don't seem to get why I have to manually revert the changes.
If I checkout the main branch, my code crashes which naturally led me to go back to previos commits. Eventually at b2b9343 my code works as it worked yesterday. I shoud also point out that when the OS crashes, my code is at the main thread without extra user threads stuck on `k_sem_take(&sem, K_FOREVER);`

**Comment by ycsin** [comment]
@HrMitrev could you try to replace this [line ](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/modem/gsm_ppp.c#L711)with:

```
rssi_handler(&gsm->rssi_work_handle.work);
```

and see if the issue is still there?

**Comment by ycsin** [comment]
> Yes! That's it :)

Could you review #41610?

**Pull request merged**
