### PR TITLE
mgmt: mcumgr: update bt smp initialization

### PR DESCRIPTION
**Pull request by Alex-T-Stark**
Small oneline fix to smp_bt.c smp transport register. 

`smp_client_transport_register()` is a void function and has no return value, so it should be ignored.

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]

**Comment by nordicjm** [comment]
@Alex-T-Stark can you fix the compliance issues?

**Comment by Alex-T-Stark** [comment]
Amended commit message to fix compliance issue. 

Rebased to current upstream main.

**Review by nordicjm — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@Alex-T-Stark still there:

` 4: UC4 Commit message body line exceeds max length (100>75): "smp_client_transport_register() is a void function and has no return value, so it should be ignored."`

**Comment by nordicjm** [comment]
@fabiobaltieri looks ready to merge

**Pull request merged**
