### PR TITLE
Cmake migration squash history

### PR DESCRIPTION
**Pull request by SebastianBoe**
Hi Anas, this reduces the git history from 450 commits to 24, in addition I reviewed the
patchset and rewrote the history to remove some binary files that were introduced 
in the initial cmake commit by Joakim.

I do not want to reduce the history further because I think it is important
to retain attribution. Both to make git blame work correctly and out of respect
to the original authors.

Usually I would not rewrite the history like this, but instead rewrite it slightly
to remove fixup commits and reverts. But IMHO this is not feasible for a branch
with 450 commits.

### CODE REVIEW

**Comment by carlescufi** [comment]
Please add a signed-off line for Joakim and myself on the first commit

**Comment by SebastianBoe** [comment]
@carlescufi : Done.

**Comment by nashif** [comment]
all commits have the same title, maybe adding numbers will help identifying them by the title... i.e. 1/24, 2/24 etc..

**Comment by SebastianBoe** [comment]
> all commits have the same title, maybe adding numbers will help identifying them by the title... i.e. 1/24, 2/24 etc..

Makes sense, will rewrite just before the merge into master (to know the total number of commits).

**Review by galak — CHANGES_REQUESTED** [review]
I'm not sure what this is accomplishing, having commit's without any meaningful commit message isn't useful.  Also, if you want to maintain attribution, I think you can just have everyone's signed-off-by listed in one commit.  The various "fixes" to get cmake to work I don't think are terribly interesting from a history perspective.

I'd say just merge everything down to one or a few small handful of logical commits

**Comment by SebastianBoe** [comment]
> Also, if you want to maintain attribution, I think you can just have everyone's signed-off-by listed in one commit.

The problem is that git blame will only show one author. So I might get questions that would be better addressed to Anas or Joakim.

I think retaining the correct author gives a more useful git history than squashing down to one commit.

**Comment by galak** [comment]
> The problem is that git blame will only show one author. So I might get questions that would be better addressed to Anas or Joakim.
> 
> I think retaining the correct author gives a more useful git history than squashing down to one commit.

I think that is extremely minor vs the history and how this looks.  Especially if there isn't any commit history details that explain why the change/fix was made.  Either way, I still don't think it makes sense to have a slew of commits for this.  The git blame isn't different than if you do it for the top level Makefile today and majority of it associated with Juan Manuel Cruz

**Comment by SebastianBoe** [comment]
All right, will squash down to one commit. Just wanted to make sure
we understood each other.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
Hi, dissenting opinion here, I think we should not be squashing the git history like this at all. Just leave the commits as they are.

**Comment by nashif** [comment]
> Hi, dissenting opinion here, I think we should not be squashing the git history like this at all. Just leave the commits as they are.

we agreed in the TSC to push this in 3+ squashed commit:
- introduce the new cmake file
- commits for changes to existing files such as sanitycheck
- commit to remove Kbuild

The three main authors of this major change agree this is the right approach as well. The branch has lots of trial and error commits that do not make sense in the main tree and with very minimal commit messages that might lead to confusion due to the many rebases we had to do on top of new features being added while adding cmake support.

**Comment by mbolivar** [comment]
I have a few trivial fixes; feel free to squash them in: https://github.com/mbolivar/zephyr/commits/cmake-fixes

Otherwise I can wait until after the switch to post them

**Comment by SebastianBoe** [comment]
@nashif : The history has been re-written according to what we agreed on in the TSC meeting.

Removing KBuild will be done at some point after this PR.

This PR is ready to be force-pushed to zephyrproject-rtos/cmake_migration.

**Comment by SebastianBoe** [comment]
> I have a few trivial fixes; feel free to squash them in: https://github.com/mbolivar/zephyr/commits/cmake-fixes
> 
> Otherwise I can wait until after the switch to post them

@mbolivar : Thank you for contributing, I'll make sure these changes make it into the upcoming final migration PR.

**Comment by mbolivar** [comment]
> I'll make sure these changes make it into the upcoming final migration PR.

@SebastianBoe thanks!

**Comment by SebastianBoe** [comment]
The history has been rewritten and pushed to cmake_migration outside of this PR making this now obsolete.

**Pull request closed without merging**
