### PR TITLE
dts: rt5xx: rt6xx: Fix DTC sram warnings

### PR DESCRIPTION
**Pull request by butok**
Fix DTC warnings caused by sram node definition:
 _Warning (simple_bus_reg): /soc/sram@30000000: simple-bus unit address format error, expected "10000000"_

### CODE REVIEW

**Review by decsny — CHANGES_REQUESTED** [review]
I don't think this is the proper solution to this warning, you're changing it from the data bus address to the code bus address

**Comment by butok** [comment]
> I don't think this is the proper solution to this warning, you're changing it from the data bus address to the code bus address

Hi @decsny 
This is the way how to fix the _"expected 10000000"_ warning.
Would you rather to stay with the warning?

**Comment by decsny** [comment]
> > I don't think this is the proper solution to this warning, you're changing it from the data bus address to the code bus address
> 
> Hi @decsny This is the way how to fix the _"expected 10000000"_ warning. Would you rather to stay with the warning?

just switch the order of the indexes in the property. ie, 20000000->30000000 first, and 0->10000000 second.

**Comment by butok** [comment]
> > > I don't think this is the proper solution to this warning, you're changing it from the data bus address to the code bus address
> > 
> > 
> > Hi @decsny This is the way how to fix the _"expected 10000000"_ warning. Would you rather to stay with the warning?
> 
> just switch the order of the indexes in the ranges property. ie, 20000000->30000000 first, and 0->10000000 second.

OK. Updated.

**Review by danieldegrasse — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
