### PR TITLE
rp2040: Bugfix UART initialisation: Mixup of Zephyr constants and rpi-hal constants

### PR DESCRIPTION
**Pull request by 68ec020**
rpi-hal function "uart_set_format" expects data width in the range of 5..8. So you can't use the Zephyr abstraction constant UART_CFG_DATA_BITS_8 directly, because its value is 3. There is already a translation in "uart_rpi_configure", but it is not used for the default initialisation. So I reused "uart_rpi_configure". There is only one downside: It also sets the baud rate, which is already done in "uart_rpi_init".

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Comment by dcpleung** [comment]
@WebmasterTD

**Comment by 68ec020** [comment]
I decided I didn't like the baud rate being set twice. So a change the code a bit. I created a new function "uart_rpi_set_format" which contains everything from "uart_rpi_configure" which is format related. This function is then used in "uart_rpi_init" and "uart_rpi_configure".

**Review by nordicjm — APPROVED** [review]

**Comment by yonsch** [comment]
@68ec020 Thanks. Did you check that dynamic configuration still works?

**Review by dcpleung — APPROVED** [review]

**Comment by 68ec020** [comment]
I just wrote a small test program to switch between 115200 and 9600 every second. It works as expected.

**Pull request merged**
