### PR TITLE
cmake: gen_version_h: use copy_if_different to avoid unnecessary recompiles

### PR DESCRIPTION
**Pull request by arbrauns**
gen_version_h.cmake is invoked whenever the timestamp of `.git/index` changes, which happens on every `west update`, even if nothing has actually changed. Use `copy_if_different` to ensure the header file is only modified if its contents have actually changed.

### CODE REVIEW

**Review by nordicjm — COMMENTED** [review]
So to avoid a write you do a write then a rename which is another write... this isn't solving a problem

**Comment by arbrauns** [comment]
It does solve the problem, `copy_if_different` looks at the *content* of the file rather than the timestamp.

**Comment by tejlmand** [comment]
please provide a bit more information of your system.

Zephyr (when being a manifest repo) is not touched when running `west update`.

`west update` only touches projects in the manifest, and not the manifest repo.
But even if currently pointing at the right sha, then west update will do a `git checkout` and that command with touch the `.git/index`.

So in cases where Zephyr is not the manifest repo, but is being imported, then it's likely that the described issue can occur.
If this is the case, then please update the commit description, so that it is more clear exactly what the root cause is.

**Comment by arbrauns** [comment]
Sure, it's possible this only happens with actual projects, not when building something in the zephyr source tree itself.

**Comment by tejlmand** [comment]
> Sure, it's possible this only happens with actual projects, not when building something in the zephyr source tree itself.

and that's why the commit message must be more precisely written, especially when there is bug issue reported to link to.
In future, if someone cleans up code, then a git blame will show the commit and in such case it's important to know why code was made this way.

**Pull request closed without merging**
