### PR TITLE
ARM64 MMU fixes

### PR DESCRIPTION
**Pull request by npitre**
Looking at my own code I couldn't convince myself it was OK.
So I wrote a test and guess what? The code was broken... of course.

Here's the fix which required a slight rethinking of the page table
usage tracking. And more tests.

### CODE REVIEW

**Review by carlocaione — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@npitre this f7e11649fdf578b2e958e460c96566216dd57ff1 is now causing a test to fail in main:

` west build -p -b qemu_cortex_a53 tests/kernel/mem_protect/mem_map -T kernel.memory_protection.mem_map -t run`

```
E: Current thread: 0x4003f380 (test_k_mem_unmap_phys_bare)
Caught system error -- reason 0
 PASS - test_k_mem_unmap_phys_bare in 0.001 seconds
===================================================================
TESTSUITE mem_map succeeded
Running TESTSUITE mem_map_api
===================================================================
START - test_k_mem_map_exhaustion
Free memory: 133640192
E: insufficient virtual address space (requested 12288)
Mapped 632 pages
Free memory now: 131051520
ASSERTION FAIL [is_table_desc(src_table[i], level)] @ WEST_TOPDIR/zephyr/arch/arm64/core/mmu.c:486
	can't have partial block pte here
E: ELR_ELn: 0x0000000040002ca0
E: ESR_ELn: 0x0000000056000002
E:   EC:  0x15 (Unknown)
E:   IL:  0x1
E:   ISS: 0x2
E: TPIDRRO: 0x01000000400401d8
E: x0:  0x00000000400401d8  x1:  0x00000000000001e6
E: x2:  0x0000000000000090  x3:  0xffffff80ffffffc8
E: x4:  0x0000000000000000  x5:  0x000000000000002d
E: x6:  0x0000000000000000  x7:  0x0000000000000004
E: x8:  0x0000000000000004  x9:  0x0000000040006204
E: x10: 0x0000000040015ec0  x11: 0x0000000000000000
E: x12: 0x0000000000000000  x13: 0x000000009600004f
E: x14: 0x0000000040088f00  x15: 0x000000004003fa80
E: x16: 0x0000000040007734  x17: 0x00000000400401d8
E: x18: 0x0000000000000040  lr:  0x0000000040005364
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x4003f380 (test_k_mem_map_exhaustion)
Caught system error -- reason 4
Unexpected fault during test
===================================================================
PROJECT EXECUTION FAILED
```

**Comment by nashif** [comment]
It is probably worth it adding qemu_cortex_a53 as an integration platform in the test.

**Comment by dcpleung** [comment]
It seems the PTE is of value zero. So this is the case of table being referenced but PTE not in use (as described in the commit message for usage count change). If a test for invalid PTE is added before the assert to continue, the test passed. Though I am not sure if that is the correct fix.

**Comment by npitre** [comment]
Needed fix in #74269

**Pull request merged**
