### PR TITLE
wifi: hostap: upmerge hostap 2.11

### PR DESCRIPTION
**Pull request by krish2718**
Long pending first upmerge of hostap bringing in 2.11 version.

### CODE REVIEW

**Review by sachinthegreen — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by sachinthegreen — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Comment by jukkar** [comment]
@MaochenWang1 please take a look so we can proceed with upgrading hostap to 2.11

**Review by MaochenWang1 — DISMISSED** [review]

**Comment by jukkar** [comment]
hostap https://github.com/zephyrproject-rtos/hostap/pull/66 is now merged

**Comment by danieldegrasse** [comment]
NXP HAL https://github.com/zephyrproject-rtos/hal_nxp/pull/474 is merged, this PR just needs a rebase to fix conflicts

**Review by mmahadevan108 — APPROVED** [review]

**Review by MaochenWang1 — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@krish2718 , can you please rebase. The  NXP HAL SHA has been updated and is probably causing CI failures as this PR has not been merged

**Comment by nashif** [comment]
> @krish2718 , can you please rebase. The NXP HAL SHA has been updated and is probably causing CI failures as this PR has not been merged

I tried rebasing this locally to see if it fixes the issue, but met other issues...

**Comment by krish2718** [comment]
@mmahadevan108 it's rebased now.

**Review by sachinthegreen — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@jukkar, awaiting your approval

**Review by jukkar — APPROVED** [review]

**Pull request merged**
