### PR TITLE
RFC: drivers: mcr20a: check if receiving of ACK is required

### PR DESCRIPTION
**Pull request by jfischer-no**
The driver must know if Acknowledge Request flag is set in the FCF. If the flag is set, then the TX_RX sequence is selected and the transceiver waits for an ACK packet after the TX operation. If an ACK was received in time, ctx->ack_received will be set.

This does not "completely" fix ZEP-2479.

### CODE REVIEW

**Review by tbursztyka — COMMENTED** [review]
Big no no. No 15.4 driver should ever parse a packet and wait for a ack by itself.

Look at 15.4 L2: if a ack is requested, it will be waiting for a ack. The driver will let the l2 know about the ack received via ieee802154_radio_handle_ack()

have a look at subsys/net/l2/ieee802154/ieee802154_radio_utils.h and subsys/net/l2/ieee802154/ieee802154_radio_csma_ca.c for instance.

**Comment by jfischer-phytec-iot** [comment]
>Big no no. No 15.4 driver should ever parse a packet and wait for a ack by itself.

The driver must know if Acknowledge Request flag is set in the FCF and select proper sequence. The transceiver waits for a ACK and It will be handled in hardware, not in the driver. There is no other way to figure it out, except to look into packet.

I will move ieee802154_radio_handle_ack() to L:1133, have overlooked it.

**Comment by tbursztyka** [comment]
Can you link a reference on the hardware where they describe this behavior?

I really don't want any driver to parse a packet. But if necessary the radio api can be changed so the ack requirement can be passed through.

**Comment by jfischer-phytec-iot** [comment]
MCR20A transceiver, RM: http://www.nxp.com/docs/en/reference-manual/MCR20RM.pdf
Chapter 4.3.2.1.5 Sequence TR (Transmit/Receive)
"Needless to say, if during the transmit operation of a Sequence TR, an Acknowledge
frame is being requested of the receiving end device (Frame Control Field:
AckRequest=1), then Sequence TR with RXACKRQD=1 is the appropriate procedure"

**Comment by jfischer-phytec-iot** [comment]
AT86RF233 transceiver, RM: http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8351-MCU_Wireless-AT86RF233_Datasheet.pdf
Chapter 7.2.4 TX_ARET_ON – Transmit with Automatic Frame Retransmission and CSMA-CA Retry

We still have no driver for this transceiver, but this one can do more magic in the hardware.

**Comment by tbursztyka** [comment]
I meant a reference on MCR20A behavior.

I know some hardware are smarter than let's say cc2520 (that's easy...), but there is currently no logic yet to take advantage of it. And actually, such behavior can be usually enabled/disabled as wanted.

**Comment by tbursztyka** [comment]
Sorry missed the first reply of yours

**Comment by tbursztyka** [comment]
Ok so as far as I understood mcr20a pdf, it should be able to follow the usual simple way: called there "transmit sequence" chapter 4.3.2.1.3.  No?
Then it should work without handling cca and ack by itself.

**Comment by jfischer-phytec-iot** [comment]
Yes, the driver automatically selects the T sequence if no ACK request is desired.

To clarify, you want to receive an ACK over normal RX thread? Seriously? With TX -> Idle -> RX turnaround? (actually it is TX-> Idle-> ContextSwitch -> ...... ContextSwitch-> RX). This will fail every time AUTOACK is switched on and what is about interoperability?

IEEE Std 802.15.4-2011, 5.1.6.6 Transmission scenarios:
"Successful data transmission. The originator MAC sublayer transmits the data frame to the recipient
via the PHY data service. In waiting for an acknowledgment, the originator MAC sublayer starts a
timer that will expire after macAckWaitDuration"

**Comment by tbursztyka** [comment]
Autoack is for replying to a ack flag on a received frame (and that on you definitely want the hw to handle it directly on rx)

So far this non-optimized path works just fine. The reference you make about 15.4 specs is exactly what the L2 soft-mac layer does, as I told in my very first reply of this PR.

I have plans to optimize the path better when, and only when, the hw supports it (offloading ack reception as for instance mcr20a can, or offloading the whole cca logic, etc...). But this is not the scope of this patch.

**Comment by jfischer-phytec-iot** [comment]
>Autoack is for replying to a ack flag on a received frame (and that on you definitely want the hw to handle it directly on rx)
>So far this non-optimized path works just fine.

What hardware? CC2520 <-> CC2520 zephyr os only? Has it ever been tested with activated ACK (ack set)? Just try a few ping test with Linux or RIOT OS (if you still have the yellow board :smile: ).
(note: zephyr sets also the ACK_REQ flag for broadcast packets)

>The reference you make about 15.4 specs is exactly what the L2 soft-mac layer does, as I told in my very first reply of this PR.

Where is the timer for macAckWaitDuration? How does L2 guarantee that the time is not exceeded? Do any drivers or L2 checks for the SequenceNumber in an ACK Frame?

Can we not just expand the driver API? Such as:
```
        /** Transmit a packet fragment */                                                                 
        int (*tx)(struct device *dev,                                                                     
                  struct net_pkt *pkt,                                                                    
                  struct net_buf *frag,
                  bool ack_required); 
```

**Comment by tbursztyka** [comment]
The stack has been tested with and against various hardware, not only cc2520. And against different OS/stack in the other end as well (we had a interop event last june).

See my first comment to see where the wait is done. (Seq number is not checked though)

Anyway, I fail to see how this is all related to the ticket Jira: ZEP-2479. This driver used to works before. At least I remember it did. The driver should be able to send what we ask to send following the "transmit sequence" chapter 4.3.2.1.3.

**Comment by jfischer-phytec-iot** [comment]
>See my first comment to see where the wait is done. (Seq number is not checked though)

Ok, no timer for macAckWaitDuration, no SequenceNumber checking, and AUTOACK is always on?
We should not do it so, it's wrong.

>Anyway, I fail to see how this is all related to the ticket Jira: ZEP-2479. This driver used to works before. At least I remember it did. The driver should be able to send what we ask to send following the "transmit sequence" chapter 4.3.2.1.3.

It concerns point 2, the driver has always selected the TX_RX sequence because AUTOACK is switched on, regardless of whether ACK_REQ was set in the packet or not and csma_ca_tx_fragment sends each packet 3 times because TX_RX fails every time. The alternative would be to select only the T Sequence and disable AUTOACK. I did not want to see it merged, it's just an RFC.

**Comment by tbursztyka** [comment]
Of course there is a timer. Autoack on the device driver side is needed (nobody wants soft-ack tx, though it's supported), you can have separated sequences T and R, not TR altogether, in this driver with autoack set.
See Chapter 4.3.2.1.2, especially the beginning of page 61 and Chapter 4.3.2.1.3.

TR sequence is not possible with current path followed, so the bug is there in your driver, you need to switch to T and R sequences.

**Comment by jfischer-phytec-iot** [comment]
>Of course there is a timer. 

You mean the 10ms timeout in for ack_lock? csma_ca_radio_send can not be interrupted? What is the guarantee that the ACK can not be lost?

>TR sequence is not possible with current path followed, so the bug is there in your driver, you need to switch to T and R sequences.

For my understanding, as I see it, each received packet can be interpreted as ACK (ieee802154_cc2520.c : 673) or where is it checked if it is really an ACK?  

I would reluctantly fix this bug so that it goes the same not "optimal" path as the CC2520 driver.
You do not want to change the API so that the ACK_REQ can be handled in hardware?

**Comment by tbursztyka** [comment]
There is never ever any guarantee you'll receive a ACK, or any frame in fact, on such radio tech. Why csma_ca_radio_send would be uninterruptible? Why each received packet can be interpreted as a ACK? Why are we even discussing all of this here? :)

Changes are planned, I am going to come up with sub-Ghz support (wip stuff) and among other changes, better hw usage whenever possible will be there (it's mandatory for being able to support both sub and non sub Ghz at runtime).

You don't want to switch to sequence T and R in your driver, ok. Until then, this driver will be broken. I am fine with that.

**Comment by jfischer-phytec-iot** [comment]
>There is never ever any guarantee you'll receive a ACK, or any frame in fact, on such radio tech. Why csma_ca_radio_send would be uninterruptible?

Ok, sorry, I mean the probability that it can get lost, should not be increased by "not optimal path"  design.

>Why each received packet can be interpreted as a ACK? Why are we even discussing all of this here? :)

Sorry that I annoy you, but I want to understand exactly how the handling of the ACK works. What I understand from the code of the CC2520 driver is that any received packet with length equal  IEEE802154_ACK_PKT_LENGTH can be interpreted as ACK. If not, please tell me how it works, so I can interpret it correctly in my driver. Thank you.

**Comment by tbursztyka** [comment]
Non optimal path if not going to affect the reception of the ack frame hopefully. It's probably adding a bit more overhead on the whole tx process though. In the end it may affect a tiny little bit the throughput.

No other packet, but a ACK frame, can be of such length. Note that's valid only up to 802.15.4-2011.
I could have made the handling stricter, checking on the length only was a lazy short-cut which has its reasons in specs. Well, I could fix that still. Up to the 2011 version ACK frames are super badly designed in fact. Afterwards they finally fixed all the issue with ACK: but they are much longer and requires more work on the receiving side (and afaik, no hw supports it yet, but we don't care, for now).

**Comment by pfalcon** [comment]
Reading thru the discussion, I see @tbursztyka's point: there's a software implementation of MAC layer in Zephyr, and any driver should first of all be able to work with it. Premature optimizations for tricks of particular hardware will likely be just that - premature optimization, because every hardware has its own sets of tricks, so without analyzing bunch of transceivers and finding good abstractions for their capabilities it can just lead to messy API. IMHO of course.

**Comment by jfischer-phytec-iot** [comment]
replaced by #1135

**Pull request closed without merging**
