### PR TITLE
scripts: edtlib: do not inherit parent compatibles

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Commit 0d4dca10b2ac156b598f96b4dadb44ac7001380b ("scripts: edtlib: child binding compatibles match parents") was a hack meant to keep the edtlib.Binding class in place without modifying some twister behavior that needed further changes to work properly with first-class binding objects.

This is a hack which was necessary due to the way the dt_compat_enabled_with_alias twister filter works. Avoid the need for it by updating the filter so it works by matching the alias node's parent compatible instead. This works for in-tree users, which are all buttons and LEDs. Deprecate the filter and add a replacement, dt_enabled_alias_with_parent_compat, that's clearer.

Now that the edtlib hack is no longer necessary, remove it. Child Binding objects now have None compatible properties unless the binding YAML explicitly sets a compatible.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
Not sure what changed yet, but twister isn't complaining on this PR's CI. I think I should do a bit more digging into the issue that caused me to put this hack in originally before we should merge this, but this much is ready for review.

**Comment by galak** [comment]
> Not sure what changed yet, but twister isn't complaining on this PR's CI. I think I should do a bit more digging into the issue that caused me to put this hack in originally before we should merge this, but this much is ready for review.

I was curious about the twister comment, so yeah, agree we should dig into this a bit more.

**Review by pabigot — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
> agree we should dig into this a bit more.

I found the issue and added some prep work commits that should fix it before reverting the edtlib hack.

**Review by galak — COMMENTED** [review]
What is meant by 'unless the binding YAML explicitly sets a compatible' in the 'scripts: edtlib: do not inherit parent compatibles' commit?

**Comment by mbolivar-nordic** [comment]
It means the child binding's Binding object has 'binding.compatible' set to None unless the YAML sets a compatible for the child nodes themselves.

**Comment by mbolivar-nordic** [comment]
See the tests for examples.

**Comment by galak** [comment]
> compatible for the child nodes themselves.

Which implies the child devicetree node has a compatible as well - correct?

**Comment by mbolivar-nordic** [comment]
Devicetree:

```
/ {
        aliases {
                led0 = &led0;
        };

        leds {
                compatible = "gpio-leds";
                led0: led_0 {
                        gpios = <...>;
                        label = "LED 0";
                };
        };
};
```

- `/leds`: the edtlib.Node compatible is "gpio-leds"
- `/leds/led_0`: compatible is None

**Comment by mbolivar-nordic** [comment]
@galak I edited the above comment a couple times, but I think it explains the different cases now.

**Comment by pabigot** [comment]
I had a similar question; in tree `invensense,mpu9150` has a child-binding with a compatible, and `nxp,imx-flexspi-device.yaml` is included as a child binding where its compatible seems (intended) to be associated with the child.

**Review by nashif — APPROVED** [review]

**Comment by carlescufi** [comment]
@galak can we merge this now?

**Pull request merged**
