### PR TITLE
boards: arm: same70: Add mcuboot flash partitions to dts

### PR DESCRIPTION
**Pull request by jpfaff**
Signed-off-by: Jonas Pfaff <jonas.pfaff@gmail.com>

### CODE REVIEW

**Comment by pfalcon** [comment]
@nzmichaelh, @sknsean : FYI

**Comment by pfalcon** [comment]
@jpfaff : Build would need be fixed first to get a review. Thanks.

Commit message:

 >  Boards: arm: same70:

"boards" should be lower-case generally.

**Comment by nzmichaelh** [comment]
Thnaks @pfalcon I'm not planning on using mcuboot on the Arduino Zero / SAMD as it's a 256 KiB chip so an A/B partition scheme would be a bit tight.

**Comment by pfalcon** [comment]
@nzmichaelh : I just tried to cross-link people working on SAM MCUs so you guys were aware of each other's work and maybe helped with reviews.

**Comment by galak** [comment]
Do you mind to rebase this?

**Review by dbkinder — DISMISSED** [review]
doc change looks OK

**Comment by jpfaff** [comment]
Rebased. Sorry for the long delay.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
@mbolivar can you take a quick look and review this.  Thanks

**Review by mbolivar — APPROVED** [review]
Seems fine

**Pull request merged**
