### PR TITLE
Add support for NXP imx SNVS RTC

### PR DESCRIPTION
**Pull request by pdgendt**
Adds a driver using the SNVS high power and optionally low power
RTC instances. A device specific function `mcux_snvs_rtc_set` is
provided to update the current counter value.

The NXP hal module will need to be updated to use shim drivers

### CODE REVIEW

**Comment by pdgendt** [comment]
I've opened a PR in NXP HAL repo here https://github.com/zephyrproject-rtos/hal_nxp/pull/79

I can update this PR if that one is merged.

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Does `tests/drivers/counter/counter_basic_api` pass with this driver?

Please add `counter` to at least one board yaml to make this driver build in CI.

**Comment by dleach02** [comment]
@pdgendt, the HAL PR has been merged.  You can update this PR appropriately. 

We can follow up with @MaureenHelm to block.

**Comment by pdgendt** [comment]
> @pdgendt, the HAL PR has been merged. You can update this PR appropriately.
> 
> We can follow up with @MaureenHelm to block.

I've updated the PR and rebased onto the current `main`. I didn't find time yet to update the tests to take this along though.

**Comment by MaureenHelm** [comment]
> > @pdgendt, the HAL PR has been merged. You can update this PR appropriately.
> > We can follow up with @MaureenHelm to block.
>

I presume you mean "unblock"?

> I've updated the PR and rebased onto the current `main`. I didn't find time yet to update the tests to take this along though.

The driver implementation looks good, but I would still like to see that it gets built in CI. Maybe you could rework the test?

**Comment by pdgendt** [comment]
> The driver implementation looks good, but I would still like to see that it gets built in CI. Maybe you could rework the test?

@MaureenHelm I've reworked an existing test to include the iMX RT1064 evaluation board.

**Review by MaureenHelm — APPROVED** [review]

**Comment by pdgendt** [comment]
@dleach02, can this be merged or are there any open issues?

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
