### PR TITLE
drivers: serial: stm32 databits depends on parity

### LINKED ISSUE #33351: uart peripheral outputs 7 bits when configured in 8 bits + parity on stm32
On `nucleo_f746`, when using `UART_CFG_PARITY_EVEN`, the data width is reduced by one bit.
On the following scope capture, I'm sending 0x55 then 0xaa first with parity even, then with parity none. (115200 bauds, 1 stop bit, 8 data bits).
uart_even_none
(serial decoding is configured for 115200 bauds, 1 stop bit, parity even. It is not valid for the two later bytes which have been sent with no parity)

**To Reproduce**
1. unzip [test_uart.zip](https://github.com/zephyrproject-rtos/zephyr/files/6109122/test_uart.zip) under zephyr/samples/ : 
2. `west build -p auto -b nucleo_f746zg -d build/nucleo_f746zg/test_uart zephyr/samples/test_uart/`
3. probe on scope `usart6_tx` (pg14/arduino D1)

**Expected behavior**
The frames lengths of the first burst should be one bit longer than the second burst, when configuring `data_bits` to `UART_CFG_DATA_BITS_8`, I'm expecting to see 8 data bits of payload (excluding parity bit), and not 7 bits + parity (=8 bits).

**Environment (please complete the following information):**
- zephyr v2.5.0

I have the feeling that the issue comes from the fact that for (all ? some ?) stm32 devices, the *usart frame formats* table in reference manuals (f746, h743, f091) indicates that the `M` bits will configure the length of the payload which also depends on wether parity is enabled.

I made some modifications in `drivers/serial/uart_stm32.c` available [here](https://github.com/nvincent-vossloh/zephyr/commit/830997ddeded147828aa94c6f8250eaa88b7a423) which help with the situation described above by configuring the M bits based on parity being enabled or not.

If the behaviour described is indeed an issue and not a misunderstanding of the API on my part, I'll submit a PR.

Thanks.

### PR DESCRIPTION
**Pull request by nvincent-vossloh**
When configuring databits on stm32, take into account if parity is enabled, because in the zephyr API, the parity bit is not included in the `UART_CFG_DATA_BITS_x` whereas in ST register parity is included in datalength field register (`M` field).

I have tested it with a nucleo f746 for 8 bits datawidth with parity even enabled against a device with that configuration.

### CODE REVIEW

**Comment by FRASTM** [comment]
Does the usecase in zephyr exists where the data length is set to 9bits with parity -> stm32 configuration should set 10 bits of data

**Review by dcpleung — APPROVED** [review]

**Comment by erwango** [comment]
@nvincent-vossloh can you fix the issue reported by compliance checks ?

**Comment by erwango** [comment]
^^ @zisisadamos

**Comment by zisisadamos** [comment]
> ^^ @zisisadamos

Looks that it resolves the issue im facing however parity dependent datalength calculation happens on uart init function as well. Trying to see if its fixed there as well I am on mobile heading to office.

**Comment by zisisadamos** [comment]
> ^^ @zisisadamos

@erwango 
Ok so for me this fix works. Seems to scale better than mine and it seems to take into account 9bit implementations.
uart_stm32_init also does some calculations maybe its better to use new functions from this fix. But what I also notice is that fix on parity even or odd with data length 9bits will not report that its not supported.

**Comment by erwango** [comment]
@zisisadamos, thanks for the report. Don't hesitate to put your review comments so we focus on one single PR on the same topic

**Comment by FRASTM** [comment]
it looks like the https://github.com/zephyrproject-rtos/zephyr/pull/33722

**Comment by nvincent-vossloh** [comment]
@erwango, I have fixed the compliance check.

Regarding the allowed configurations should uart_stm32_configure() reports `ENOTSUP` in case of 9 bits + parity requested ?
Are there any other forbidden configurations ?

Thanks.

**Review by FRASTM — APPROVED** [review]

**Comment by erwango** [comment]
@nvincent-vossloh 

> Regarding the allowed configurations should uart_stm32_configure() reports ENOTSUP in case of 9 bits + parity requested ?
Are there any other forbidden configurations ?

Yes, we should inform of not supported configurations.
I don't see other unsupported configurations that are not declared right now.

**Comment by nvincent-vossloh** [comment]
`uart_stm32_configure` now returns `-ENOTSUP` when config is 9 databits and parity is not none.

Waiting for actions results but it should be good.

Let me know if something is missing.

Thanks

**Review by erwango — APPROVED** [review]

**Pull request merged**
