### PR TITLE
Revert "boards: arm: adafruit_feather_m0_basic_proto: Set flash offset"

### PR DESCRIPTION
**Pull request by KubaFYI**
The PR to be reverted breaks flashing with currently used Zephyr SDK (0.11.2). The SDK uses an older version of bossac which doesn't support the `---offset` argument (instead offsetting things by itself). I suspect the submitter of the original PR tested their code on a custom setup with a different version of bossac.

Reverts zephyrproject-rtos/zephyr#24738

Signed-off-by: Kuba Sanak <contact@kuba.fyi>

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
no objections from the runners side; I've noticed the same issue with the sdk bossac

**Comment by KubaFYI** [comment]
@MaureenHelm @galak is there anything else to be done with this to be merged in?

**Comment by galak** [comment]
> @MaureenHelm @galak is there anything else to be done with this to be merged in?

I assume there is no way to till which version of bossac is being used?

**Comment by KubaFYI** [comment]
> I assume there is no way to till which version of bossac is being used?

I suppose we could parse the output of `bossac --help` to extract the version string but that would depend on the format the help output to not change.

The sdk provides a set version of bossac to be used with `west flash` so we know what version to support and as such I'd say that the onus of dealing with the fallout of using other versions is on the user who decides to venture into the world of using non-zephyr SDK configurations

**Pull request closed without merging**
