### PR TITLE
west: spdx: Generate SPDX 2.2 tag-value documents

### LINKED ISSUE #7317: Add generation of SPDX TagValue documents to each build
Background: In order to keep up with the licensing changes, and ensure that no "surprises" happen late in the cycle,  we need to monitor the state of license information in the project on every build.

By following the layout proposed in reuse.software (see: https://reuse.software/practices/2.0/) scripting can be developed to check that only files with approved licenses are automatically accepted.

By building an SPDX document on each build,  checks can be programmed, to enforce /ext for deviations from Apache-2.0,  and that all files have a detectable license.   By doing these checks on every build,  licensing issues can be resolved as soon as detected, and reverted/fixed, rather than waiting for audit at formal release.

### PR DESCRIPTION
**Pull request by swinslow**
This adds support to generate SPDX 2.2 tag-value documents via the
new west spdx command. The CMake file-based APIs are leveraged to
create relationships from source files to the corresponding
generated build files. SPDX-License-Identifier comments in source
files are scanned and filled into the SPDX documents.

Before `west build` is run, a specific file must be created in the
build directory so that the CMake API reply will run. This can be
done by running:

    west spdx --init -d BUILD_DIR

After `west build` is run, SPDX generation is then activated by
calling `west spdx`; currently this requires passing the build
directory as a parameter again:

    west spdx -d BUILD_DIR

This will generate three SPDX documents in `BUILD_DIR/spdx/`:

1) `app.spdx`: This contains the bill-of-materials for the
application source files used for the build.

2) `zephyr.spdx`: This contains the bill-of-materials for the
specific Zephyr source code files that are used for the build.

3) `build.spdx`: This contains the bill-of-materials for the built
output files.

Each file in the bill-of-materials is scanned, so that its hashes
(SHA256 and SHA1) can be recorded, along with any detected licenses
if an `SPDX-License-Identifier` comment appears in the file.

SPDX Relationships are created to indicate dependencies between
CMake build targets; build targets that are linked together; and
source files that are compiled to generate the built library files.

`west spdx` can be called with optional parameters for further
configuration:

* `-n PREFIX`: specifies a prefix for the Document Namespaces that
will be included in the generated SPDX documents. See SPDX spec 2.2
section 2.5 at
https://spdx.github.io/spdx-spec/2-document-creation-information/.
If -n is omitted, a default namespace will be generated according
to the default format described in section 2.5 using a random UUID.

* `-s SPDX_DIR`: specifies an alternate directory where the SPDX
documents should be written. If not specified, they will be saved
in `BUILD_DIR/spdx/`.

* `--analyze-includes`: in addition to recording the compiled
source code files (e.g. `.c`, `.S`) in the bills-of-materials, if
this flag is specified, `west spdx` will attempt to determine the
specific header files that are included for each `.c` file. This
will take longer, as it performs a dry run using the C compiler
for each `.c` file (using the same arguments that were passed to it
for the actual build).

* `--include-sdk`: if `--analyze-includes` is used, then adding
`--include-sdk` will create a fourth SPDX document, `sdk.spdx`,
which will list any header files included from the SDK.

Fixes #7317

Signed-off-by: Steve Winslow <steve@swinslow.net>

### CODE REVIEW

**Comment by swinslow** [comment]
I've updated the PR to fix most of the prior patch compliance / coding style checks that were failing. The one remaining compliance check, and the Scancode checks, are false positives:

* Compliance: The [`licenses.py` file](https://github.com/zephyrproject-rtos/zephyr/blob/ef63ac760b3bfc125c828356dc05fa8800fe4a14/scripts/west_commands/zspdx/licenses.py) is a list of license IDs from the SPDX License List. It is used to determine whether an `SPDX-License-Identifier:` tag is an official SPDX ID or an invalid / custom license ID. The Compliance check is [complaining](https://github.com/zephyrproject-rtos/zephyr/pull/34555/checks?check_run_id=2433392547) about the spelling of one of the identifiers; however, it is spelled correctly according to the [official ID on the SPDX License List](https://spdx.org/licenses/zlib-acknowledgement.html).

* Scancode: Similarly, Scancode is [reporting](https://github.com/zephyrproject-rtos/zephyr/pull/34555/checks?check_run_id=2433392546) that many of the license IDs in that file are not permissive licenses. However, this is not applicable here as `licenses.py` is just noting that each ID is a valid ID; none of the content in the repo is actually under those licenses.

* Finally, Scancode is also reporting an error regarding CC0-1.0, which appears to be because of the [`DataLicense: CC0-1.0`](https://github.com/zephyrproject-rtos/zephyr/blob/ef63ac760b3bfc125c828356dc05fa8800fe4a14/scripts/west_commands/zspdx/writer.py#L99) line in `writer.py`. Note that SPDX 2.2 documents are required to be under CC0-1.0 according to [Section 2.2 of the SPDX spec](https://spdx.github.io/spdx-spec/2-document-creation-information/#22-data-license). So I'd guess that this false positive should be ignored / skipped, but I'm happy to discuss if you have questions.

**Comment by swinslow** [comment]
Here is a sample run of `west spdx` as an example.

```
(zephyr) steve@breq: zephyr> west spdx -i -b /home/steve/programming/zephyr/zephyrproject/zephyr/build/
initializing Cmake file-based API prior to build
initialized; run `west build` then run `west spdx`

(zephyr) steve@breq: zephyr> west build -b reel_board_v2 samples/net/dhcpv4_client/ -- -DSHIELD=link_board_eth
-- west build: generating a build system
Including boilerplate (Zephyr base): /home/steve/programming/zephyr/zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/steve/programming/zephyr/zephyrproject/zephyr/samples/net/dhcpv4_client
-- Zephyr version: 2.5.99 (/home/steve/programming/zephyr/zephyrproject/zephyr)

----- 8< snip: rest of standard west build output

[199/199] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      103712 B         1 MB      9.89%
            SRAM:       32712 B       256 KB     12.48%
        IDT_LIST:          0 GB         2 KB      0.00%

(zephyr) steve@breq: zephyr> west spdx -b /home/steve/programming/zephyr/zephyrproject/zephyr/build/
parsing CMake Cache file
parsing CMake Codemodel files
setting up SPDX documents
walking through targets
walking through pending sources files
walking through pending relationships
scanning files in package app-sources in document app-sources
scanning files in package zephyr-sources in document zephyr-sources
scanning files in package app in document build
scanning files in package arch__arm__core__aarch32 in document build
scanning files in package arch__arm__core__aarch32__cortex_m in document build
scanning files in package arch__arm__core__aarch32__cortex_m__mpu in document build
----- 8< snip: several more lines of similar output
scanning files in package zephyr in document build
scanning files in package zephyr_final in document build
scanning files in package zephyr_generated_headers in document build
scanning files in package zephyr_prebuilt in document build
scanning files in package zephyr_property_target in document build
Writing SPDX document app-sources to /home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/app.spdx
Writing SPDX document zephyr-sources to /home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/zephyr.spdx
Writing SPDX document build to /home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/build.spdx
```

This generates the `app.spdx`, `zephyr.spdx` and `build.spdx` SPDX documents in `/home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/`, which I'm attaching to this comment in a ZIP file:

[west-spdx.zip](https://github.com/zephyrproject-rtos/zephyr/files/6373203/west-spdx.zip)

**Comment by swinslow** [comment]
And here is a second example, this time with several of the optional parameters added. This is run on the same example as in the prior comment, so `west spdx -i` and `west build` have already been run.

```
(zephyr) steve@breq: spdx> west spdx \
>     -b /home/steve/programming/zephyr/zephyrproject/zephyr/build/ \
>     -n https://swinslow.net/spdxdocs/zephyr-example \
>     --analyze-includes --include-sdk
parsing CMake Cache file
parsing CMake Codemodel files
setting up SPDX documents
walking through targets
walking through pending sources files
walking through pending relationships
scanning files in package sdk in document sdk
scanning files in package app-sources in document app-sources
scanning files in package zephyr-sources in document zephyr-sources
scanning files in package app in document build
scanning files in package arch__arm__core__aarch32 in document build
scanning files in package arch__arm__core__aarch32__cortex_m in document build
scanning files in package arch__arm__core__aarch32__cortex_m__mpu in document build
----- 8< snip: several more lines of similar output
scanning files in package zephyr in document build
scanning files in package zephyr_final in document build
scanning files in package zephyr_generated_headers in document build
scanning files in package zephyr_prebuilt in document build
scanning files in package zephyr_property_target in document build
Writing SPDX document sdk to /home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/sdk.spdx
Writing SPDX document app-sources to /home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/app.spdx
Writing SPDX document zephyr-sources to /home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/zephyr.spdx
Writing SPDX document build to /home/steve/programming/zephyr/zephyrproject/zephyr/build/spdx/build.spdx
```

As indicated in the output, in addition to the three prior SPDX documents, this creates a fourth one, `sdk.spdx`.

This takes a bit longer to run, due to the dry runs of the C compiler to gather the information about included header files.

The SPDX documents are significantly larger than before (particularly `build.spdx` and `zephyr.spdx`) due to the inclusion of the various header files, as well as the relationships from them to the build products.

[west-spdx-with-includes.zip](https://github.com/zephyrproject-rtos/zephyr/files/6373230/west-spdx-with-includes.zip)

**Comment by swinslow** [comment]
cc @kestewart @nashif @tejlmand @mbolivar-nordic -- this is a heavily-rewritten replacement for #31065. I've aimed to address the criticisms that were raised during the review of that PR. I'd welcome any feedback that you may have, and I'm happy to join a call to talk through any questions live if that would be helpful. Thank you!

**Comment by mbolivar-nordic** [comment]
Thanks for the update! A few preliminary things from a quick skim:

> west spdx -b BUILD_DIR

I think I'd rather have this be -d instead of -b for consistency with `west build`. We use -b for 'board' and the `west spdx` lines are intermixed with `west build` lines, so it seems worth preserving people's muscle memory for what each option means.

>     * will list any header files included from the SDK.

So this is Zephyr SDK only? What about other toolchains; is listing header files from those unsupported? It seems like something that would be more at the compiler level rather than the toolchain level, naively.

Finally, I'm thinking this PR needs updates to MAINTAINERS.yml for the new files, right?

**Comment by swinslow** [comment]
Hi @mbolivar-nordic, thanks for the comments!

> I think I'd rather have this be -d instead of -b for consistency with `west build`. We use -b for 'board' and the `west spdx` lines are intermixed with `west build` lines, so it seems worth preserving people's muscle memory for what each option means.

Thanks -- sounds good, I'll plan to make that change.

> > ```
> > * will list any header files included from the SDK.
> > ```
> So this is Zephyr SDK only? What about other toolchains; is listing header files from those unsupported? It seems like something that would be more at the compiler level rather than the toolchain level, naively.

I've only tried the `--analyze-includes --include-sdk` options with the Zephyr SDK. Currently it does this process by:
1. looking in the `CMakeCache.txt` file for `CMAKE_C_COMPILER` to determine what compiler was used
2. re-calling that compiler with the arguments `-E -H` and all of the original build flags, for each source file, and parsing the output (which provides the list of included header files)
3. looking in the `CMakeCache.txt` file for `ZEPHYR_SDK_INSTALL_DIR` and assigning any files from there into the `sdk.spdx` file.

If someone is using a different toolchain and not the SDK, then although I haven't tried it myself, I would guess that steps 1 and 2 should still work (assuming the toolchain uses gcc; if it's a different compiler, the `-E -H` flags presumably wouldn't work). Without the SDK, I'd have to recheck the code to see whether step 3 would just be skipped for the include files that come from the SDK, or whether it would error out.

Either way, though, if someone doesn't use the SDK then if they omit `--analyze-includes --include-sdk`, they would still be able to gather the rest of the SPDX data -- source code files, build artifacts, etc. -- just not the included header files.

> Finally, I'm thinking this PR needs updates to MAINTAINERS.yml for the new files, right?

Sure -- I would guess so, though I defer to you whether that would be within the exist [`West:`](https://github.com/zephyrproject-rtos/zephyr/blob/9aa0f212aeefb0ca9a554207e349c273ee7279c8/MAINTAINERS.yml#L1505) block or a separate one for `west spdx` specifically? Apologies, this is my first significant contribution to Zephyr so I'm still learning the way that the community operates!

**Comment by swinslow** [comment]
Hi @mbolivar-nordic, I've updated the PR to fix the command line flag from -b to -d as you suggested. I amended the existing commit and did a force-push -- I know this likely isn't preferred, but I realized the earlier commit message had the -b command line flag in the detailed description, and I didn't want to cause confusion.

Unrelated, I also corrected an issue with SHA1 vs SHA256 checksums for external document references that I recently learned about separately due to an ambiguity in the SPDX spec (more details [here](https://github.com/swinslow/cmake-spdx/issues/8) if you're interested) -- shouldn't have any meaningful impact on the evaluation of this PR.

For your comment about updates to MAINTAINERS.yml -- would you prefer that it add me to the list as a collaborator for West? Or that I create a separate block for West SPDX, I'm guessing something like the following:

```yaml
West SPDX:
    status: maintained
    maintainers:
        - swinslow
    files:
        - scripts/west_commands/spdx.py
        - scripts/west_commands/zspdx/
    labels:
        - "area: West"
```

I wasn't sure if this would cause a problem, since the `files` entries there are all nested under `scripts/west_commands/` which is in the existing West block.

**Comment by nashif** [comment]
my only issue with all of this is the fact this is split into multiple commands, pre, build and post. Why can't all of this be done in one single call with the right options supplied, whether to west or even to cmake via -- -DCONFIG_.... 

Otherwise it looks good and generates useful information. Thanks...

**Comment by swinslow** [comment]
Thanks for your comments @nashif. 

On the multiple commands: The original prototype in #31065 had all three steps combined into one, by being a command-line flag passed to `west build`. The feedback from there, and the TSC call where it was discussed, was that it was undesirable to have it be a part of `west build`. (There were other problems with #31065, but that was one of the notable critiques.)

Given that, I broke it out into a separate `west spdx` call to be executed after the build. That explains why there is a post step after the build.

The reason for the pre step before the build is because, in order for the [CMake file-based API](https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html) to run, it relies on an empty file being present at a specific directory, namely `$BUILD_DIR/.cmake.api/v1/query/codemodel-v2`. To my knowledge, there isn't a way in CMake to trigger this via command-line arguments to the build process (I could be wrong about this).

So before CMake and the build are run, that empty file needs to be created at codemodel-v2. That could in theory be done as part of the call to `west build`, as in #31065 -- but given the feedback from before, I figured I shouldn't touch the `west build` command at all. So that's what the pre step of the `west spdx --init` call does. It just creates that empty file, so that when CMake runs, the CMake file-based API will create the build metadata that we'll use, post-build, to actually create the SPDX documents.

If folks are open to me modifying `west build` to have the empty-file-initialization happen there, though, I'm happy to propose something there. That would remove the pre step and just have `west build` with something like `--init-spdx`, followed by a `west spdx` call.

**Review by nashif — APPROVED** [review]
fine with it right now, we can optimize and reduce the amount of steps needed later.

**Comment by mbolivar-nordic** [comment]
> For your comment about updates to MAINTAINERS.yml -- would you prefer that it add me to the list as a collaborator for West?

Let's keep it simple and go that route, yes, on the understanding that bug reports and enhancements to the spdx component will be your domain. With that, I think I'm ready to approve.

As I said during our long ago discussion on Slack, extensions are cheap and I'm not conservative about adding them; my concern here is just to establish the expectation that you'll be doing ongoing maintenance here.

**Comment by swinslow** [comment]
> As I said during our long ago discussion on Slack, extensions are cheap and I'm not conservative about adding them; my concern here is just to establish the expectation that you'll be doing ongoing maintenance here.

Thanks @mbolivar-nordic! Sounds good and agreed. I'll add a commit to add myself to the list.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Great, thanks! Nice work and looking forward to getting this merged!

**Comment by MaureenHelm** [comment]
There's one part of the compliance check that needs to be fixed:
```
Error: See docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

Commit 4d656490c7:
1: UC6 Body has no content, should at least have 1 line.
```

**Comment by swinslow** [comment]
Thanks @MaureenHelm -- I was thrown off by this since the commit hash doesn't match either of the commits in my PR. But I think I see what is going on here now. Let me squash the commits and re-submit, and see if that addresses it.

**Comment by swinslow** [comment]
Hi @MaureenHelm, thanks, I've resolved that error. Note that the warning for "acknowledgement" still appears, though it is a false positive as mentioned [above](https://github.com/zephyrproject-rtos/zephyr/pull/34555#issuecomment-826395103).

**Pull request merged**
