### PR TITLE
drivers: rtc: Oscillator stop flag is not handled correctly

### LINKED ISSUE #76474: drivers: rtc: Oscillator stop flag is not handled correctly in RV-8263 driver
**Describe the bug**

The oscillator stop flag is never cleared so reading a time would result in an endless loop of errors.

### PR DESCRIPTION
**Pull request by Kampi**
Closes #76474

### CODE REVIEW

**Review by bjarki-andreasen — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by jakubtopic — CHANGES_REQUESTED** [review]
I think the current behavior is actually correct. The oscillator stop flag is reset by setting the time. If the oscillator flag is set during runtime due to oscillation failure, the time should be considered invalid, even if the flag can be cleared.

**Comment by Kampi** [comment]
> I think the current behavior is actually correct. The oscillator stop flag is reset by setting the time. If the oscillator flag is set during runtime due to oscillation failure, the time should be considered invalid, even if the flag can be cleared.

Yes, that´s exactly my thought. The issue is that the RTC has set the flag during a power-up phase so if you read the time after a power-up phase the flag is set and is never cleared.

The current solution marks the time invalid and clears the flag if set during a time read. Everything is fine if the flag was set because of a PoR of the RTC. If there is an oscillator error (low voltage for example) the flag is set again and the next time read is also invalid. Please see page 23 of the [app manual](https://www.microcrystal.com/fileadmin/Media/Products/RTC/App.Manual/RV-8263-C8_App-Manual.pdf).

```
When the oscillator of the RV-8263-C8 is stopped, the Oscillator Stop flag OS is set. The oscillator is considered to
be stopped between power up and stable crystal oscillation (start-up time tSTART). This time can be in a range of
typical 200 ms to maximal 2 s depending on temperature and supply voltage.

The flag remains set until cleared by command (see following Figure). If the flag cannot be cleared, then the oscillator
is not running. This method can be used to monitor the oscillator and to determine if the supply voltage has reduced
to the point where oscillation fails.
```

**Comment by jakubtopic** [comment]
> The issue is that the RTC set the flag during a power-up phase so if you read the time after a power-up phase the flag is set and is never cleared.

It is cleared upon setting time. If the flag is set, either the last power-up phase (until oscillation is stable) was not followed by setting the time using `rtc_set_time`, or there was an oscillation failure. In both cases, I would say the time should not be considered valid.

If the oscillation is stable and the flag was set, the behavior in this PR would be that the first reading of the time will return an error, but the following calls will be okay, despite the time still being invalid. I believe the current behavior (in upstream) is correct – I would maybe suggest changing the error number from `-ECANCELED` to `-ENODATA`.

**Comment by Kampi** [comment]
Let me think about your suggestion. 

And what do you mean with invalid time? There is no time set and the rtc will start with his default values as soon as the oscillator is ready. So if you read the time and the flag wasn't set  you get valid values. Also the OS flag can be set by a low voltage scenario. In this case the time in the RTC is still valid, regardless of you set it or not, but the oscillator has stopped. 
So I think using the error for no data is not a good choice because technically there are data available but the oscillator has stopped at one point so the time stored in the RTC might be old.

**Comment by jakubtopic** [comment]
> And what do you mean with invalid time?

Sorry if I wasn't clear. The description of the OS flag values in the attached app manual states:

- 0: Clock integrity is guaranteed.
- 1: Clock integrity is not guaranteed; oscillator has stopped or has been interrupted.

What I meant by "despite the time still being invalid" is pointing out that without setting the time (calling `rtc_set_time`), the detected state ("clock integrity is not guaranteed" – whether the time is not set or corrupted by low voltage) does not change. It seems odd to me that `rtc_get_time` would first return an error and then success for the same state.

> Also the OS flag can be set by a low voltage scenario. In this case the time in the RTC is still valid, regardless of you set it or not, but the oscillator has stopped.

I’m not familiar with this hardware, but if the voltage dropped to the point where the oscillator stopped, I wouldn’t assume that the time in RAM is preserved.

**Comment by Kampi** [comment]
TBH I´m also not sure if the time is completely invalid when the oscillator stops or if only the counter stops and the time is hold. Yes, it can look odd when time reads failed and succeeded and you didn´t change anything with the RTC.

I would suggest we close this PR and simply change `-ECANCELED` to `-ENODATA` as you suggested. It looks better to me from the users perspective.

Thank you for your thoughts!

**Pull request closed without merging**
