### PR TITLE
net: l2: ieee802154: Fix IEEE 802.15.4 shell regression + minor logging problem

### LINKED ISSUE #59125: net: l2: ieee802154: minor bug fixes/regression (PR available)
**Describe the bug**

Two bugs were identified in the IEEE 802.15.4 stack:
* The IEEE 802.15.4 shell extension would no longer display the full extended address (minor regression).
* In validate_addre(): `cbprintf()` causes a warning when printing `char *` pointers with `%p`. Fixed by casting to `(void *)`.

**To Reproduce**

* Retrieve extended address in ieee802154 shell extension.
* Enable CONFIG_NET_L2_IEEE802154_LOG_LEVEL_DBG=y

**Expected behavior**

* display full address
* do not emit a warning when printing dbg message

**Impact**

minor

PR with fixes already exits.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes two bugs (one a regression in the IEEE 802.15.4 shell extension and one a minor logging issue):
* The IEEE 802.15.4 shell extension would no longer display the full extended address due to a bug introduced in one of my earlier commits (which were already merged unfortunately).
* cbprintf() causes a warning when printing `char *` pointers with `%p`. Fixed by casting to `(void *)`.

Fixes #59125

### CODE REVIEW

**Comment by fgrandel** [comment]
@jukkar and/or @nandojve Maybe an ACK from your side if ok to facilitate quick merging?

**Comment by nandojve** [comment]
Zephyr still on RC stage and it is required an issue to merge it. It is important track issue on PR, see [commit-message-body](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-body)

**Comment by fgrandel** [comment]
> Zephyr still on RC stage and it is required an issue to merge it. It is important track issue on PR, see [commit-message-body](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-body)

Fixed.

**Review by nandojve — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by fgrandel** [comment]
Improved title to facilitate proper prioritization pre 3.4.

**Pull request merged**
