### PR TITLE
boards: Move nRF5340 CPUNET reset from board to SoC

### PR DESCRIPTION
**Pull request by hubertmis**
CPUNET reset is a SoC feature of nRF5340. It is available on all boards
with nRF5340 SoC. Because of that this option shall be connected with
Soc instead of board.

Signed-off-by: Hubert Miś <hubert.mis@nordicsemi.no>

### CODE REVIEW

**Review by ioannisg — COMMENTED** [review]
To me Enabling CPU NET does not seem to be an SoC option, it is clearly a "user" configuration (application developer's) option. It is connected with what sort of applications we want to run on the platform. The dependency on BT makes it obvious. (And BT is a user option, selected in samples prj.conf). Now, it is common that we use the Board definition to enable default user configuration, e.g. CONFIG_SPI, CONFIG_ARM_MPU, CONFIG_DCDC, etc., so I think the option is OK to stay at the board level.

SoC options are suitable for HW configuration, e.g. selection of timer driver, ticks/second, cache, etc. Allowing firmware to run on NET MCU is not a HW configuration; it's an application layer choice, IMHO

**Comment by hubertmis** [comment]
@ioannisg I understand your point.

However, my rationale was that the register to enable NET CPU power is available and usable in APP CPU regardless board is used. If we keep such config with board configuration, it would need to be copied to each board that has nRF53 SoC.
I've found this potential improvement when I was trying to add 802.15.4 protocol support to nRF53 SoC and I've realized that I have to grep all boards in Zephyr project to verify which one includes this config to add `default y if IEEE802154_NRF` line.

Similar configuration option is configuring NFC pins as GPIO in nRF52, that is related to SoC, but using this option is application dependent.

I agree that CONFIG_SPI and CONFIG_DCDC should be a board configuration, because these options make no sense if there are no SPI components on board or no passive components needed for DCDC. But enabling NET CPU is possible on every board with nRF53 - there are no external dependencies.

**Comment by ioannisg** [comment]
> However, my rationale was that the register to enable NET CPU power is available and usable in APP CPU regardless board is used. If we keep such config with board configuration, it would need to be copied to each board that has nRF53 SoC.

This is the price we have to pay. However, we could always create a common Kconfig file for all nRF53 board variants and keep common configuration there; configuration that is specific to nRF53 platforms, but also specific to the application use-case.

>> But enabling NET CPU is possible on every board with nRF53 - there are no external dependencies.

Same for ARM_MPU, there are no external dependencies, but it is a user option and therefore it resides in the board definitions.

I am fully supporting finding a way to minimize duplication of configuration, but it should respect the principle that 
- HW configuration should be present in DTS or SoC Kconfig
- Application configuration should be present in Board Kconfig structure, or samples' Kconfig

**Comment by hubertmis** [comment]
@ioannisg, What menuconfig structure would you expect for such configuration?

Currently it something like:
```
Erratum19
Board config
  DCDC_APP
  DCDC_NET
  RESET_NETCPU
SoC config
  NFC pins as GPIO
  Cache
```

I thought that it would be better like this:
```
Board config
  DCDC_APP
  DCDC_NET
Hardware config
  Erratum19
  NFC pins as GPIO
  Cache
  RESET_NETCPU
```

Would you like to make other sturcture? Another high-level config option like "Application SoC config"

**Comment by ioannisg** [comment]
- Errata are SoC -related, and should remain in SoC definition.
- Cache, as well.
- DCDC should be enabled in Board level. I see that we also have SOC_DCDC_NRF5XX options, but these are indirectly selected via Board Kconfig switches.
- RESET_NETCPU could also follow the DCDC approach, i.e. have hidden SoC level switches, enabled via Board switches. That's probably ok to do; only a minor enhancement in my opinion
- A bit hard to understand the NFCT_PINS_AS_GPIOS help text. Looks like it should also be enabled in Board level (and this is actually the case in the 52 dongle). 

My point was to have a common Board-level Kconfig structure for options that are application-related. Currently we do not have this infrastructure because each board has its own directory. So we tend to follow the policy : "move options to SoC level because they are common to all boards" which is in principle wrong. SoC level should not serve as a common board configuration Kconfig :) It should really be for HW configuration (at least th epart that is not done via DTS)

**Comment by hubertmis** [comment]
@ioannisg , I know my questions may be stupid, because I'm still learning Zephyr, but I would like to fully understand the picture here.
When I use menuconfig to configure my project, when I open "Board Options" menu I expect to find options related to given PCB. I would not search for a power-register-related reset configuration in there. From your comment I understood that you see "Board Options" more like "configuration of SoC features for particular project" than "configuration of SoC features for particular PCB" and that we shall add board-level Kconfig for each SoC to add project configuration options related to given SoC to "Board Options" menu. Have I understood correctly?

**Comment by ioannisg** [comment]
@hubertmis there are no stupid questions.

> When I use menuconfig to configure my project, when I open "Board Options" menu I expect to find options related to given PCB.

This is correct. However, as I mentioned earlier, in Board options we also add some user-level configuration; application configuration options we would like to be added, by default, in builds on a particular board. Check https://docs.zephyrproject.org/latest/guides/porting/board_porting.html for more details.

> would not search for a power-register-related reset configuration in there

That is correct  **we should not configure SoC hardware** via Board-level options.

However, in your case, the option does not really configure hardware of the SoC; it just **uses** the existing SoC hardware to execute a user configuration "selection", which is to enable booting of an **external** core (external to the current 5340 Application core, for which you are building Zephyr). Since it is external to your SoC, it is better suited as a Board option.

_I admit there is an issue here, because in Zephyr, the SoC is understood as a unit of execution: a "single" CPU and a "single" Zephyr image. So ther is a problem on multi-core CPUs because they contain multiple cores, and multiple Zephyr images. So, for Zephyr, nRF5340 is not a SoC; nRF5340 APP CPU is a SoC ;) and nRF5340 NET MCU is another SoC. They are both part of nRF5340 PDK, though._

>From your comment I understood that you see "Board Options" more like "configuration of SoC features for particular project" than "configuration of SoC features for particular PCB" and that we shall add board-level Kconfig for each SoC to add project configuration options related to given SoC to "Board Options" menu. Have I understood correctly?

Well, let me clarify this, then. Board option should be used to configure
- HW on the Board, outside the SoC we build Zephyr for. This can be related to "other" SoCs on the Board. OR (in your case) other cores in the SoC/Board (not the core you are building for).
- application level configuration (e.g. protocols, MPU, peripheral driver enabling, etc.) which should be desired _by default_ for any builds on a particular BOARD.

That said, yeah, "configuration of SoC features for particular project" is close to reality; I would rather say: "default configuration of SoC features for common application builds on a particular platform"

But it is _also_ "configuration of SoC features for particular PCB". So it is both. actually.

So, yeap, you have a correct understanding.

I understand your confusion with the CPU NET enabling on nRF5340.

I'd say, if we want to clean this up, we should
- have SoC related Kconfig options that boot NET MCU from nRF5340 Application MCU initialization code
- move the .c file that does the booting in the soc level
- keep a _top level_ Kconfig switch at Board level, which will select the SoC Kconfig option at SoC level that will compile-in the  .c file for the the reset of NET MCU.

**Comment by hubertmis** [comment]
@ioannisg , thanks for detailed explenation. I think I understand now. The most confusing part for me is that Zephyr SoC is not really SoC, but rather Core.

Perhaps to make it less confusing for newbies like me, there could be three levels of configuration in Zephyr:

1. Core configuration (current SoC configuration)
2. SoC configuration (related to configuration of inter-core features for the core the project is running on)
3. Board configuration (related to PCB)

In single-core SoCs 2. could be removed, or merged with 1.

However, as such change would need deep reorganization of the whole project, I don't intend to make proposal in this PR. I'm closing it.

**Pull request closed without merging**
