### PR TITLE
boards: arduino_portenta_h7: fix can1 device name

### PR DESCRIPTION
**Pull request by fabiobaltieri**
CI hotfix

---

This has been renamed to fdcan1 in 03f20698ae but this board was left out somehow.

### CODE REVIEW

**Review by str4t0m — CHANGES_REQUESTED** [review]
Thanks for this fix!
Could you please change this for the `arduino_giga_r1_m7.dts` as well, including the `zepyhr,canbus` chosen node. Such a chosen node should be added to the portenta as well, but we might do that in a follow up PR.

**Comment by fabiobaltieri** [comment]
> 

Thanks for catching this, somehow I missed it from the main CI run log.

**Review by henrikbrixandersen — APPROVED** [review]
Thank you.

**Review by str4t0m — APPROVED** [review]

**Comment by peter-mitsis** [comment]
Fixes #61570

**Pull request merged**
