### PR TITLE
devicetree: deprecate DT_BUS_LABEL variants

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
Marked DNM for @mbolivar-nordic review.

**Review by gmarull — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
I'm confused. This seems to overlap with https://github.com/zephyrproject-rtos/zephyr/pull/47729/. Which one do you want to move forward with?

**Comment by galak** [comment]
> I'm confused. This seems to overlap with #47729. Which one do you want to move forward with?

#47729 is merged so this is standalone now.

**Review by MaureenHelm — APPROVED** [review]

**Comment by galak** [comment]
@mbolivar-nordic can you take another look.

**Review by mbolivar-nordic — APPROVED** [review]

**Pull request merged**
