### PR TITLE
board: m5stack_m5dial: Add support for M5Dial IoT devkit

### PR DESCRIPTION
**Pull request by MrMarteng**
Adding support for M5stack M5Dial IoT development kit.

M5Dial features 1,28" round display, rotary button, beeper, touch-screen, real-time-clock and a NFC/RFID reader.

### CODE REVIEW

**Comment by MrMarteng** [comment]
This PR depends on #67012

**Comment by MrMarteng** [comment]
@kartben Maybe your are interested in supporting me again? ;-)

**Comment by kartben** [comment]
> @kartben Maybe your are interested in supporting me again? ;-)

I saw your other PR with the display driver so I was totally gonna ask you when the M5Dial board definition was gonna come 😬

**Comment by kartben** [comment]
It feels to me that it would be better to handle the M5Dial as a shield, with the StampS3 defined separately as an actual board. This way one could use M5Dial with e.g. a StampC3, or any other board with a compatible TBD "M5 stamp connector", and we would actually offer proper support for bare StampS3?

**Comment by MrMarteng** [comment]
> It feels to me that it would be better to handle the M5Dial as a shield, with the StampS3 defined separately as an actual board. This way one could use M5Dial with e.g. a StampC3, or any other board with a compatible TBD "M5 stamp connector", and we would actually offer proper support for bare StampS3?

🤔 maybe your are right. I am having a look into that. Support for StampS3 is on the way as well. Another holiday week ahead 😏

**Comment by kartben** [comment]
> 🤔 maybe your are right. I am having a look into that. Support for StampS3 is on the way as well. Another holiday week ahead 😏

Eheh, very nice!
Note that I need to finish the work on https://github.com/kartben/zephyr/tree/m5stack_atomlite at some point (I think only the README might be missing IIRC), so if you were also planning on adding Atom Lite you might want to hold off ;-)

**Comment by MrMarteng** [comment]
> > 🤔 maybe your are right. I am having a look into that. Support for StampS3 is on the way as well. Another holiday week ahead 😏
> 
> Eheh, very nice!
> Note that I need to finish the work on https://github.com/kartben/zephyr/tree/m5stack_atomlite at some point (I think only the README might be missing IIRC), so if you were also planning on adding Atom Lite you might want to hold off ;-)

I just added a pr for the atomS3lite recently (https://github.com/zephyrproject-rtos/zephyr/pull/67084).

**Comment by MrMarteng** [comment]
M5Dial support has been reworked via shield instead of a separate board: #67253

**Comment by kartben** [comment]
@MrMarteng not a full review, just a comment as I just spent some time playing with the M5Dial today :) Also used @joelguittet's work for pwm backlight control
https://github.com/kartben/zephyr/tree/m5dial_demo

**Comment by kartben** [comment]
Lol I posted on the wrong PR :) will move to the other one, as it applies anyway

**Pull request closed without merging**
