### PR TITLE
WIP: Bluetooth: l2cap: fix deadlock on allocating responses in sysworkq

### PR DESCRIPTION
**Pull request by mniestroj**
Most handlers that are executed in bt_att_recv() are calling
bt_att_create_pdu() to allocate response buffer. This function resolves
to net_buf_alloc(pool, K_FOREVER) call in the end. After [1] got applied
it means that sysworkq gets suspended if all buffers from acl_tx_pool
are already used. net_buf_alloc() never returns, because all allocated
buffers happen to be in att->tx_queue, which is only consumed in
sysworkq as well. This is a deadlock.

Allocating with K_FOREVER is never not a good idea in sysworkq, as all
system services suffer from that fact. Create a dedicated workqueue for
L2CAP received packets, so allocating responses doesn't hurt rest of the
system.

[1] 2699d05e45f5 ("Bluetooth: Fix BT_ATT_ENFORCE_FLOW")

Most importantly this patch fixes real deadlock. However it should be
considered a workaround, rather than real solution to the problem
(at least in current form).

### CODE REVIEW

**Comment by Vudentz** [comment]
Interesting, this is something we are not able to reproduce even in qualification scenarious so I wonder what kind of application are you using to be able to reproduce it. Because of ATT flow control it not normal to have more than one request queued into the tx_queue so perhaps there are multiple GATT client requests taking up all the buffers in which case the att->reqs is the one holding the buffers.

The second part of the problem seem that is not well understood, the freeing of the buffers happens on the driver when done with transmission so it shouldn't be causing a deadlock if we just have all buffers in used since as soon as TX thread process the first outgoing buffer and frees it should resume the thread waiting for a buffer, so it would block but not deadlock the syswq.

If the syswq is really deadlocking then we need to identify code where both the syswq is used for both locking and unlocking.

**Comment by Vudentz** [comment]
> The second part of the problem seem that is not well understood, the freeing of the buffers happens on the driver when done with transmission so it shouldn't be causing a deadlock if we just have all buffers in used since as soon as TX thread process the first outgoing buffer and frees it should resume the thread waiting for a buffer, so it would block but not deadlock the syswq.

I figured this is not quite right because of one small detail, the driver would do net_buf_unref but ATT is keeping a reference in order to resend, so one alternative is to stop doing net_buf_ref and perhaps use a dedicated pool for cloning ongoing requests, though that doesn't eliminate the deadlock only for ATT request so I wonder about other layers holding to buffer references.

**Comment by mniestroj** [comment]
>Interesting, this is something we are not able to reproduce even in qualification scenarious so I wonder what kind of application are you using to be able to reproduce it.

I have implemented a simple console over BLE, which uses WRITE and NOTIFY. Lots of logs get printed, which means that lots of data is sent using `bt_gatt_notify`. All buffers (6 configured) are already allocated when `att_mtu_req` gets called. However it hangs on `bt_att_create_pdu`, due to K_FOREVER timeout on allocating new buffer. All the allocated buffers are in att->tx_queue, as I described earlier. `conn->tx_queue` is empty at that time. `att->tx_sem.count` is equal 0.

>I figured this is not quite right because of one small detail, the driver would do net_buf_unref but ATT is keeping a reference in order to resend, so one alternative is to stop doing net_buf_ref and perhaps use a dedicated pool for cloning ongoing requests, though that does eliminates the deadlock only for ATT request so I wonder about other layers holding to buffer references.

Which `net_buf_ref` call do you mean?

At some point I want to prepare a PR with BLE shell backend. Before that happens, is there some way I can help with investigation now?

**Comment by Vudentz** [comment]
> > Interesting, this is something we are not able to reproduce even in qualification scenarious so I wonder what kind of application are you using to be able to reproduce it.
> 
> I have implemented a simple console over BLE, which uses WRITE and NOTIFY. Lots of logs get printed, which means that lots of data is sent using `bt_gatt_notify`. All buffers (6 configured) are already allocated when `att_mtu_req` gets called. However it hangs on `bt_att_create_pdu`, due to K_FOREVER timeout on allocating new buffer. All the allocated buffers are in att->tx_queue, as I described earlier. `conn->tx_queue` is empty at that time. `att->tx_sem.count` is equal 0.

Are you using bt_gatt_write or bt_gatt_write_without_response? The later should be free of this deadlock since it doesn't hold a extra reference for retrying.

> > I figured this is not quite right because of one small detail, the driver would do net_buf_unref but ATT is keeping a reference in order to resend, so one alternative is to stop doing net_buf_ref and perhaps use a dedicated pool for cloning ongoing requests, though that does eliminates the deadlock only for ATT request so I wonder about other layers holding to buffer references.
> 
> Which `net_buf_ref` call do you mean?

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/att.c#L328

> At some point I want to prepare a PR with BLE shell backend. Before that happens, is there some way I can help with investigation now?

From what I understand this shell of yours would work similarly to what mesh proxy does, so you are using a characteristic to emulate a input/output with write and notify, but mesh seems to be working.

Try enabling CONFIG_BT_DEBUG_GATT and CONFIG_BT_DEBUG_ATT or perhaps that is not possible because the logging itself in using you backend? Im not sure how it is done with other backends but if the backend itself would use code that does make use of the logging then we would have recursive calls into the logging which most likely would deadlock itself.

**Comment by mniestroj** [comment]
>Are you using bt_gatt_write or bt_gatt_write_without_response? The later should be free of this deadlock since it doesn't hold a extra reference for retrying.

I am using `bt_gatt_notify()` when sending data from Zephyr to PC. When reproducing this issue, I am not sending any data from PC to Zephyr. Below you can find description of service and function that sends data using `bt_gatt_notify()`. Hope this helps somehow.
```
BT_GATT_SERVICE_DEFINE(shell_bt_svc,
	/* SHELL Primary Service Declaration */
	BT_GATT_PRIMARY_SERVICE(&shell_bt_svc_uuid),

	BT_GATT_CHARACTERISTIC(&shell_bt_chr_rx_uuid.uuid,
			       BT_GATT_CHRC_WRITE_WITHOUT_RESP,
			       BT_GATT_PERM_WRITE,
			       NULL, shell_bt_chr_write, NULL),
	BT_GATT_CHARACTERISTIC(&shell_bt_chr_tx_uuid.uuid,
			       BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_NONE,
			       NULL, NULL, NULL),
	BT_GATT_CCC(shell_bt_ccc, shell_bt_ccc_changed),
);

static int ble_send(struct shell_ble *sh_ble)
{
	struct bt_conn *conn;
	char *buf;
	unsigned int remaining;
	unsigned int max_packet_size;
	int err;

	if (sh_ble->line_out.len == 0) {
		return 0;
	}

	conn = bt_conn_ref(sh_ble->client_conn);
	if (!conn) {
		return -ENOTCONN;
	}

	max_packet_size = bt_gatt_get_mtu(conn) -
		GATT_NOTIFY_HDR_SIZE;

	buf = sh_ble->line_out.buf;
	remaining = sh_ble->line_out.len;

	while (remaining) {
		unsigned int len = MIN(remaining, max_packet_size);

		err = bt_gatt_notify(conn,
				     &shell_bt_svc.attrs[3],
				     buf, len);
		if (err)
			break;

		buf += len;
		remaining -= len;
	}

	bt_conn_unref(conn);

	if (err < 0) {
		printk("Failed to send %d (%d bytes), shutting down?\n", err,
			(int) sh_ble->line_out.len);
		sh_ble->client_conn = NULL;
		return err;
	}

	/* We reinitialize the line buffer */
	sh_ble->line_out.len = 0;

	return 0;
}
```

> From what I understand this shell of yours would work similarly to what mesh proxy does, so you are using a characteristic to emulate a input/output with write and notify, but mesh seems to be working.
Yes, I am using service with two characteristics (TX and RX). In general my implementation is compatible with https://play.google.com/store/apps/details?id=com.nordicsemi.nrfUARTv2

**Comment by Vudentz** [comment]
> > Interesting, this is something we are not able to reproduce even in qualification scenarious so I wonder what kind of application are you using to be able to reproduce it.
> 
> I have implemented a simple console over BLE, which uses WRITE and NOTIFY. Lots of logs get printed, which means that lots of data is sent using `bt_gatt_notify`. All buffers (6 configured) are already allocated when `att_mtu_req` gets called. However it hangs on `bt_att_create_pdu`, due to K_FOREVER timeout on allocating new buffer. All the allocated buffers are in att->tx_queue, as I described earlier. `conn->tx_queue` is empty at that time. `att->tx_sem.count` is equal 0.

Are you using bt_gatt_write or bt_gatt_write_without_response? The later should be free of this deadlock since it doesn't hold a extra reference for retrying.

> > I figured this is not quite right because of one small detail, the driver would do net_buf_unref but ATT is keeping a reference in order to resend, so one alternative is to stop doing net_buf_ref and perhaps use a dedicated pool for cloning ongoing requests, though that does eliminates the deadlock only for ATT request so I wonder about other layers holding to buffer references.
> 
> Which `net_buf_ref` call do you mean?

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/att.c#L328

> At some point I want to prepare a PR with BLE shell backend. Before that happens, is there some way I can help with investigation now?

From what I understand this shell of yours would work similarly to what mesh proxy does, so you are using a characteristic to emulate a input/output with write and notify, but mesh seems to be working.

Try enabling CONFIG_BT_DEBUG_GATT and CONFIG_BT_DEBUG_ATT or perhaps that is not possible because the logging itself in using you backend? Im not sure how it is done with other backends but if the backend itself would use code that does make use of the logging then we would have recursive calls into the logging which most likely would deadlock itself.

> > Are you using bt_gatt_write or bt_gatt_write_without_response? The later should be free of this deadlock since it doesn't hold a extra reference for retrying.
> 
> I am using `bt_gatt_notify()` when sending data from Zephyr to PC. When reproducing this issue, I am not sending any data from PC to Zephyr. Below you can find description of service and function that sends data using `bt_gatt_notify()`. Hope this helps somehow.
> 
> ```
> BT_GATT_SERVICE_DEFINE(shell_bt_svc,
> 	/* SHELL Primary Service Declaration */
> 	BT_GATT_PRIMARY_SERVICE(&shell_bt_svc_uuid),
> 
> 	BT_GATT_CHARACTERISTIC(&shell_bt_chr_rx_uuid.uuid,
> 			       BT_GATT_CHRC_WRITE_WITHOUT_RESP,
> 			       BT_GATT_PERM_WRITE,
> 			       NULL, shell_bt_chr_write, NULL),
> 	BT_GATT_CHARACTERISTIC(&shell_bt_chr_tx_uuid.uuid,
> 			       BT_GATT_CHRC_NOTIFY,
> 			       BT_GATT_PERM_NONE,
> 			       NULL, NULL, NULL),
> 	BT_GATT_CCC(shell_bt_ccc, shell_bt_ccc_changed),
> );
> 
> static int ble_send(struct shell_ble *sh_ble)
> {
> 	struct bt_conn *conn;
> 	char *buf;
> 	unsigned int remaining;
> 	unsigned int max_packet_size;
> 	int err;
> 
> 	if (sh_ble->line_out.len == 0) {
> 		return 0;
> 	}
> 
> 	conn = bt_conn_ref(sh_ble->client_conn);
> 	if (!conn) {
> 		return -ENOTCONN;
> 	}
> 
> 	max_packet_size = bt_gatt_get_mtu(conn) -
> 		GATT_NOTIFY_HDR_SIZE;
> 
> 	buf = sh_ble->line_out.buf;
> 	remaining = sh_ble->line_out.len;
> 
> 	while (remaining) {
> 		unsigned int len = MIN(remaining, max_packet_size);
> 
> 		err = bt_gatt_notify(conn,
> 				     &shell_bt_svc.attrs[3],
> 				     buf, len);

I assume it is blocking on the line above? And this function is being executed in syswq context?

> 		if (err)
> 			break;
> 
> 		buf += len;
> 		remaining -= len;
> 	}
> 
> 	bt_conn_unref(conn);
> 
> 	if (err < 0) {
> 		printk("Failed to send %d (%d bytes), shutting down?\n", err,
> 			(int) sh_ble->line_out.len);
> 		sh_ble->client_conn = NULL;
> 		return err;
> 	}
> 
> 	/* We reinitialize the line buffer */
> 	sh_ble->line_out.len = 0;
> 
> 	return 0;
> }
> ```
> 
> > From what I understand this shell of yours would work similarly to what mesh proxy does, so you are using a characteristic to emulate a input/output with write and notify, but mesh seems to be working.
> > Yes, I am using service with two characteristics (TX and RX). In general my implementation is compatible with https://play.google.com/store/apps/details?id=com.nordicsemi.nrfUARTv2

This sort of service would be a lot simpler, and possible faster, if done on top of L2CAP channel directly.

**Comment by Vudentz** [comment]
So I did a quick hack on the gatt shell to allow sending multiple notifications on a row:

https://gist.github.com/Vudentz/55fd74cf2e7e35aaca42ef2015fbaffa

So it seems this is only affecting the case where the bt_gatt_notification is initiated on the syswq, so I tried doing the same on that:

https://gist.github.com/Vudentz/aeaad3445d30c944e55980027e0957f0

That indeeds block, but it manages to send 7 notifications before doing so.

**Comment by Vudentz** [comment]
So this one turns to be trickier than I though, while we can use a different thread/wq it would sufer from the same problem since we the application may notify from the callback if that blocks it means nothing else can be dispatched to the upper layers so we get deadlocked again, just in a different thread. What I think I would do is check if the thread is k_sys_work_q.thread on create buffer and make it fail if it cannot allocate a buffer imediately so at least the application gets notified with -ENOMEM and can back off until buffer become available.

**Pull request closed without merging**
