### PR TITLE
compilers/xcc: Disable -fno-printf-return-value property

### LINKED ISSUE #54336: picolibc is incompatible with xcc / xcc-clang toolchains
**Describe the bug**

Compilation of picolibc module for picolibc tests fails with XCC on ADSP platforms. Followup to https://github.com/zephyrproject-rtos/zephyr/issues/54224.

A few of the flags used by GCC to build the picolibc module are not compatible with XCC. Different flags are observed to be not working for different versions of XCC toolchain.

`RI-2021.7-linux (xcc-clang)` + MTL:
```
clang-10: error: unknown argument: '-fno-printf-return-value'
clang-10: warning: optimization flag '-fsignaling-nans' is not supported [-Wignored-optimization-argument]
```

`RG-2017.8-linux (xcc)` + CAVS15, 18, CAVS25:
```
xt-xcc ERROR parsing -frounding-math:  unknown flag
xt-xcc ERROR parsing -fsignaling-nans:  unknown flag
xt-xcc ERROR parsing -fno-stack-protector:  unknown flag
xt-xcc ERROR parsing -Warray-bounds:  unknown flag
xt-xcc ERROR parsing -ftls-model=local-exec:  unknown flag
xt-xcc ERROR parsing -fno-printf-return-value:  unknown flag
```

**To Reproduce**
```
export ZEPHYR_TOOLCHAIN_VARIANT=xcc
west build -p -b intel_adsp_cavs15 -T tests/kernel/common/kernel.common.picolibc
```

**Expected behavior**
Compilation

**Impact**
Annoyance

**Logs and console output**
See above.

**Environment**
 - OS: Ubuntu 20.04
 - Toolchain: XCC / XCC-clang (see above)
 - Recent main

### PR DESCRIPTION
**Pull request by keith-packard**
XCC doesn't support the -fno-printf-return-value compiler option

This should fix the issue seen with clang in #54345 but with the xcc compiler.

Signed-off-by: Keith Packard <keithp@keithp.com>

Fixes #54345

### CODE REVIEW

**Comment by laurenmurphyx64** [comment]
We're getting closer, got this now:

```
modules/picolibc/picolibc/include/stdlib.h:158: error: wrong number of arguments specified for ‘__deprecated__’ attribute
```

**Comment by keith-packard** [comment]
> ```
> modules/picolibc/picolibc/include/stdlib.h:158: error: wrong number of arguments specified for ‘__deprecated__’ attribute
> ```

Ok, sounds like we need to get picolibc running with xcc sometime later then; we'll need testing of the compiled code and the like before it'll be really ready for people to use. Is there any way to run code compiled with xcc under some qemu instance for development and testing?

**Comment by keith-packard** [comment]
From what I can determine, the GCC based xt-xcc compiler uses a version of gcc before 4.5.0 as that version includes support for the __deprecated__("this is a message") form. We can try adding a version check in the one place which uses the __deprecated__ attribute with a message.

https://github.com/picolibc/picolibc/pull/423 has the proposed change; I've verified that it doesn't break current GCC, but I don't have any GCC 4.4 or earlier compilers around to test with.

You can test this change by using PR #54394, which I've marked DNM at least until it passes picolibc CI and perhaps until after the current Zephyr release is done.

**Review by nordicjm — APPROVED** [review]

**Comment by laurenmurphyx64** [comment]
> Ok, sounds like we may want to get picolibc running with xcc sometime later then; the GCC version of XCC seems to be quite different than what picolibc gets regular testing with, so my confidence in it generating working code is not as high. 

@keith-packard Yeah, that seems like a fair assessment. It's a weird toolchain :sweat_smile: (FYI @nashif)

Btw, cherry-picked in your new PR and this was the output (I shortened some paths in this output text to make it easier to read):
```
[117/1037] Building C object modules/picolibc/CMakeFiles/c.dir/newlib/libc/iconv/ces/euc.c.obj
picolibc/newlib/libc/iconv/ces/euc.c:75: warning: missing initializer
picolibc/newlib/libc/iconv/ces/euc.c:75: warning: (near initialization for ‘euc_jp_cs_desc[3].prefix’)
picolibc/newlib/libc/iconv/ces/euc.c:87: warning: missing initializer
picolibc/newlib/libc/iconv/ces/euc.c:87: warning: (near initialization for ‘euc_tw_cs_desc[3].prefix’)
picolibc/newlib/libc/iconv/ces/euc.c:97: warning: missing initializer
picolibc/newlib/libc/iconv/ces/euc.c:97: warning: (near initialization for ‘euc_kr_cs_desc[1].prefix’)
[195/1037] Building C object modules/picolibc/CMakeFiles/c.dir/newlib/libc/posix/regcomp.c.obj
In file included from picolibc/newlib/libc/posix/regcomp.c:52:
picolibc/newlib/libc/posix/cclass.h:58: warning: missing initializer
picolibc/newlib/libc/posix/cclass.h:58: warning: (near initialization for ‘cclasses[12].fidx’)
[267/1037] Building C object modules/picolibc/CMakeFiles/c.dir/newlib/libc/tinystdio/vfscanf.c.obj
In file included from picolibc/newlib/libc/tinystdio/conv_flt.c:35,
                 from picolibc/newlib/libc/tinystdio/vfscanf.c:246:
picolibc/newlib/libc/tinystdio/../../libm/common/math_config.h: In function ‘issignaling_inline’:
picolibc/newlib/libc/tinystdio/../../libm/common/math_config.h:272: warning: integer constant is too large for ‘long’ type
picolibc/newlib/libc/tinystdio/../../libm/common/math_config.h:272: warning: integer constant is too large for ‘long’ type
picolibc/newlib/libc/tinystdio/../../libm/common/math_config.h:273: warning: integer constant is too large for ‘long’ type
[280/1037] Building C object modules/picolibc/CMakeFiles/c.dir/newlib/libc/stdlib/reallocarray.c.obj
picolibc/newlib/libc/stdlib/reallocarray.c: In function ‘reallocarray’:
picolibc/newlib/libc/stdlib/reallocarray.c:30: warning: implicit declaration of function ‘__builtin_mul_overflow’
[292/1037] Building C object modules/picolibc/CMakeFiles/c.dir/newlib/libc/stdlib/wcstoll.c.obj
FAILED: modules/picolibc/CMakeFiles/c.dir/newlib/libc/stdlib/wcstoll.c.obj 
ccache xtensa/XtDevTools/install/tools/RG-2017.8-linux/XtensaTools/bin/xt-xcc  -Ipicolibc/newlib/libm/common -isystem zephyr/build/modules/picolibc/picolibc/include --include zephyrproject/zephyr/build/modules/picolibc/picolibc/include/picolibc.h -nostdlib -D_LIBC -fno-strict-aliasing -Os -imacros zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h -fno-common -g -fms-extensions -imacroszephyrproject/zephyr/include/zephyr/toolchain/xcc_missing_defs.h -imacros zephyrproject/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -fgnu89-inline -Werror=implicit-int -ffunction-sections -fdata-sections -mlongcalls -Wextra -Werror=implicit-function-declaration -Wold-style-definition -MD -MT modules/picolibc/CMakeFiles/c.dir/newlib/libc/stdlib/wcstoll.c.obj -MF modules/picolibc/CMakeFiles/c.dir/newlib/libc/stdlib/wcstoll.c.obj.d -o modules/picolibc/CMakeFiles/c.dir/newlib/libc/stdlib/wcstoll.c.obj -c picolibc/newlib/libc/stdlib/wcstoll.c
picolibc/newlib/libc/stdlib/wcstoll.c: In function ‘wcstoll_l’:
picolibc/newlib/libc/stdlib/wcstoll.c:180: error: ‘LLONG_MIN’ undeclared (first use in this function)
picolibc/newlib/libc/stdlib/wcstoll.c:180: error: (Each undeclared identifier is reported only once
picolibc/newlib/libc/stdlib/wcstoll.c:180: error: for each function it appears in.)
picolibc/newlib/libc/stdlib/wcstoll.c:180: error: ‘LLONG_MAX’ undeclared (first use in this function)
[301/1037] Building C object modules/picolibc/CMakeFiles/c.dir/newlib/libc/stdlib/wcstoumax.c.obj
```

**Review by stephanosio — APPROVED** [review]

**Comment by keith-packard** [comment]
> @keith-packard Yeah, that seems like a fair assessment. It's a weird toolchain  (FYI @nashif)

Ok, sounds like a reasonable solution is to just skip xcc for now. Note that if picolibc becomes the default C library, then xcc support would need to be supported, so we're not eliminating any work in the long term, just delaying it.
> 
> Btw, cherry-picked in your new PR and this was the output (I shortened some paths in this output text to make it easier to read):

None of these are too surprising, nor are they going to be hard to fix, but we'll need to test those fixes, and Zephyr itself doesn't provide adequate C library test coverage to do that. Before promising support for this toolchain, I'd like see a plan for executing at least the picolibc test suite.

**Pull request closed without merging**
