### PR TITLE
libc: Make printf() work out of the box with Newlib

### PR DESCRIPTION
**Pull request by pfalcon**
~~~
Enable stdio to work by default if Newlib is used as libc - it's
reasonable expectation that if full-fledged libc (like Newlib) is
selected, then printf() works out of the box.
~~~

### CODE REVIEW

**Comment by pfalcon** [comment]
This is split-off and resubmission of the change which was initial part of https://github.com/zephyrproject-rtos/zephyr/pull/5570 .

There was detailed discussion of this change at https://github.com/zephyrproject-rtos/zephyr/pull/5570#pullrequestreview-88163325 , which I'll try to reproduce below:

 nashif 14 days ago Owner

this should not set to default, even when newlib is used, printk might be the preferred way, leave this to the application.
@pfalcon
pfalcon 14 days ago Member

I can submit that as a separate patch, but the change which started it all - if standard C library is selected, not some placeholder, standard C service should just work. (Yes, someone wanting to disable particular services, should be able to do that).
@nashif
nashif 14 days ago Owner

I agree with a should work comment, but that does not mean we enable it by default. For the should work we create tests, now all of the sudden everything built with newlib is using printf for example for logging, although it is not really needed. Applications should enable this explicitly.

Think forward, we want to switch to newlib by default, this is being delayed, but that is the goal, so in this case we end up with printf enabled by default and we would get lots of "cant fit into memory" type of errors.
@pfalcon
pfalcon 14 days ago Member

    Think forward, we want to switch to newlib by default

For me, the situation is rather clear - we want to switch to newlib by default, because we want printf() and many other things work out of the box. Because if we don't want them to work out of the box, we should just stick to the toy minimal lib. But then if a user does enable a no-nonsense C library, all baseline stuff in that library should work out of the box, and what can be more baseline than printf()? If we don't do that, we just get another loop of "config hell", which Zephyr already has a bunch.

However, it's clear that this change needs to be split off to a separate PR, let me do that, and let's continue.
@pfalcon
pfalcon 14 days ago Member

    now all of the sudden everything built with newlib is using printf for example for logging

printf() should not be used for logging, definitely not of sudden. libc's stdio and Zephyr's logging should be kept separate, at least by default. Maybe, there should be an option, to log to printf(), and maybe an option to printf() to zephyr syslog, but default for both should be off.
@nashif
nashif 14 days ago Owner

printf is actually not being used as a backend of syslog, it is set to printk. agree this should be its own PR with more input from other developers.

**Comment by pfalcon** [comment]
I still think this is the right change to make, to avoid "configuration hell", so resubmitting it. Again, the logic is: if ANSI C standard defines stdio subsystem and printf() function, then they should just work (print to console). If some party wants to disable libc's printing to console, they should have such an option (and there's such an option).

**Comment by pfalcon** [comment]
And here's the point why this was initially submitted as part of #5570. This is one-line change, which leads to a following impact in the code size:

qemu_x86 and samples/net/sockets/dumb_http_server, which is actually affected very positively by this change:

CONFIG_STDOUT_CONSOLE=n:
~~~
$ size zephyr.elf 
   text	   data	    bss	    dec	    hex	filename
  56345	  53092	 100872	 210309	  33585	zephyr.elf
~~~

CONFIG_STDOUT_CONSOLE=y:
~~~
$ size zephyr.elf
   text	   data	    bss	    dec	    hex	filename
  56370	  53092	 100872	 210334	  3359e	zephyr.elf
~~~

So, all the stdio code is there anyway. What CONFIG_STDOUT_CONSOLE=y does is enables and configures few one-line functions which bridge Newlib's stdio code and Zephyr's console code. We're talking about 25 bytes here.


@nashif : I hope that arguments above are enough, but I can submit an RFC to the mailing list if needed, rehashing this arguments over again.

**Comment by pfalcon** [comment]
recheck

**Comment by pfalcon** [comment]
> @nashif : I hope that arguments above are enough, but I can submit an RFC to the mailing list if needed, rehashing this arguments over again.

@nashif : Ping.

**Review by nashif — APPROVED** [review]

**Pull request merged**
