### PR TITLE
STMc031c6 twister issue 

### PR DESCRIPTION
**Pull request by Desvauxm-st**
add boards/nucleo_c031c6.conf with
CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=4096
to avoid twister issue due to a too low heap size on the co31c6

### CODE REVIEW

**Comment by keith-packard** [comment]
Seems like you might need `CONFIG_PICOLIBC_HEAP_SIZE` in some of these cases too.

**Comment by martinjaeger** [comment]
Nit-picking: I think this device is called STM32C031C6. The commit messages use an o instead of 0.

**Comment by Desvauxm-st** [comment]
@martinjaeger
yes thanks you

**Comment by Desvauxm-st** [comment]
@keith-packard
Following tests have been passed without changing CONFIG_PICOLIBC_HEAP_SIZE:
   tests/lib/cbprintf_fp/libraries.cbprintf_fp.printf.picolibc with nucleo_c031c6 
   tests/lib/cbprintf_fp/libraries.cbprintf_fp.printfcb.picolibc  with nucleo_c031c6
   tests/posix/getopt/portability.posix.getopt.picolibc with nucleo_c031c6

**Review by FRASTM — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
LGTM

**Pull request merged**
