### PR TITLE
crypto: Add support for ECB to the TinyCrypt shim

### PR DESCRIPTION
**Pull request by rettichschnidi**
* Add support for ECB to the TinyCrypt shim
* Improve the test coverage slightly for both shims

### CODE REVIEW

**Review by ceolin — COMMENTED** [review]
Zephyr is activelly moving towards PSA crypto and these drivers will go away. I suggest looking into this path. More in https://github.com/zephyrproject-rtos/zephyr/issues/43712

**Comment by rettichschnidi** [comment]
> Zephyr is activelly moving towards PSA crypto and these drivers will go away. I suggest looking into this path. More in #43712

Thanks a lot for the heads up, will keep in mind.

However, until a PSA API makes it into mainline, is there any chance this PR (or any other new features in the crypto driver) could be merged?

**Comment by rettichschnidi** [comment]
@ceolin @nashif @kartben Could you please have a look at this?

**Comment by rettichschnidi** [comment]
Giving up because deprecation is happening (#79566).

**Comment by tomi-font** [comment]
@rettichschnidi FYI the PSA Crypto API is already (and has already been for some time) available in Zephyr, and supports ECB.

**Pull request closed without merging**
