### PR TITLE
sensors: Sensor channel DT child nodes

### PR DESCRIPTION
**Pull request by teburd**
A rough, WIP, idea of maybe describing sensor channels as child nodes of a sensor. Original idea was from @MaureenHelm

Some nice attributes of this... it maybe better matches up with what the sensor subsystem needs (a channel rather than sensor in terminology). It enables possibly adding optional channels of information for devices that represent sensor hubs like bosch's bhi260ap which has many potential channels of information.

A single numerical value could represent a channel, and the information about that channel could be obtained perhaps using DT macros statically without any allocation or C calls involved

Related Issues/PRs
#64478
#63830 
#61163

### CODE REVIEW

**Comment by teburd** [comment]
So unfortunately, atleast today, there's no great way of patching up a tree given a compatible, or supplying a "default" subtree for a given compatible which would be really useful for this sort of thing but at least this builds and can sort of give some clues as to what I was thinking

**Review by yperess — COMMENTED** [review]
I'm personally not a big fan of the subtree approach (specifically because we can't set a default). I don't envision that we'll need much data here and I think that having something like the following would be enough:

```
bmi160 {
  compatible = "bosch,bmi160";
  channels = <SENSOR_CHAN_ACCEL_XYZ, SENSOR_CHAN_GYRO_XYZ, SENSOR_CHAN_DIE_TEMP>;
  attributes = <
                SENSOR_CHAN_ALL       SENSOR_ATTR_BATCH_DURATION
                SENSOR_CHAN_ACCEL_XYZ SENSOR_ATTR_SAMPLING_FREQUENCY
                SENSOR_CHAN_ACCEL_XYZ SENSOR_ATTR_OFFSET
                ...
                >;
};
```

**Comment by teburd** [comment]
> I'm personally not a big fan of the subtree approach (specifically because we can't set a default). I don't envision that we'll need much data here and I think that having something like the following would be enough:
> 
> ```
> bmi160 {
>   compatible = "bosch,bmi160";
>   channels = <SENSOR_CHAN_ACCEL_XYZ, SENSOR_CHAN_GYRO_XYZ, SENSOR_CHAN_DIE_TEMP>;
>   attributes = <
>                 SENSOR_CHAN_ALL       SENSOR_ATTR_BATCH_DURATION
>                 SENSOR_CHAN_ACCEL_XYZ SENSOR_ATTR_SAMPLING_FREQUENCY
>                 SENSOR_CHAN_ACCEL_XYZ SENSOR_ATTR_OFFSET
>                 ...
>                 >;
> };
> ```

How would you describe multiple channels of the same type in this scenario? This was the initial issue noted in some other PRs.

In case of multiple simple temperature channels this could be pretty easily done with child nodes.

There's also some potential benefit here in being able to configure and enable optional channels, e.g. some devices may act as sensor hubs with externally connected devices, or optional channels.

bhi260ap is the extreme end of this.

I'm not opposed to using properties, this is a rough idea coming from Maureen initially and I think it warranted exploring.

But really I feel like its DT that's limiting here as I'd *like* to have an array of structured data.

To do it in DT with defaults I'd need to set it up as a destructured set of arrays..


``` dt
bmi160 {
  compatible = "bosch,bmi160";
  channels = <SENSOR_CHANNEL_ACCEL, SENSOR_CHANNEL_GYRO, SENSOR_CHANNEL_TEMP>;
  channel-fields = <<SENSOR_FIELD_X, SENSOR_FIELD_Y, SENSOR_FIELD_Z>,
                    <SENSOR_FIELD_X, SENSOR_FIELD_Y, SENSOR_FIELD_Z>,
                    <SENSOR_FIELD_DIE>>;
};
```

I'd note that the way the ST sensors now work with enum ODR/filter/sensitivity options is quite nice but doesn't match up with attributes very well as you have them. That's something to look at harder seemingly.

**Comment by teburd** [comment]
Sensor WG: No one likes the include
Brix: Take a look at pinctl as a possible answer (index properties)

**Comment by lixuzha** [comment]
If there are multiple sensors of the same type in a chip, the sensing subsystem cannot use the existing sensor API to handle this situation. This pull request introduces channel index, which is a way to solve this problem. For me, this is a good start.

**Pull request closed without merging**
