### PR TITLE
MAINTAINERS: Add self to LED strip as collaborator

### PR DESCRIPTION
**Pull request by thedjnK**
Add myself to LED strip as a collaborator

### CODE REVIEW

**Review by simonguinot — APPROVED** [review]
@thedjnK has been collaborating to the led_strip subsystem since a few months by reviewing and helping with PRs and issues. So let's make it official ! Thanks for coming on board @thedjnK :)

PS: @thedjnK, maybe you could add some information to the profile of your thedjnK GitHub account. This would help to associate this nickname with commits found in the Zephyr git history. Note that I had a hard time to connect all your professional and hobbyist identities: emails (jamie.mccrae@nordicsemi.no, spam@helper3000.net) and GitHub accounts (nordicjm, thedjnK) and the Bell nickname on Discord.

**Review by fabiobaltieri — APPROVED** [review]

**Review by soburi — APPROVED** [review]

**Review by MaureenHelm — COMMENTED** [review]
Was there a resolution on whether we're ok with the same maintainer using two handles?

**Comment by thedjnK** [comment]
> Was there a resolution on whether we're ok with the same maintainer using two handles?

Two handles because 2 different purposes, I don't do areas of the other account outside of work hours or on this account, likewise I don't do areas from this account on the other account. This is a personal account with no relation to the work account

**Comment by simonguinot** [comment]
> > Was there a resolution on whether we're ok with the same maintainer using two handles?
> 
> Two handles because 2 different purposes, I don't do areas of the other account outside of work hours or on this account, likewise I don't do areas from this account on the other account. This is a personal account with no relation to the work account

IMHO it is good idea to use different accounts to separate personal and professional contributions. But here your [thedjnK](https://github.com/thedjnK) account is quite anonymous. Your first name and name are not displayed. So there is no way to link this account with commits in the Zephyr git history. So a review made with this account could be considered an anonymous contribution...

**Review by cfriedt — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
Feels like we are discussing a non-problem, sure there's more people with multiple accounts, just don't approve your on PR, which is quite obvious, that's it.

**Comment by thedjnK** [comment]
> > Feels like we are discussing a non-problem, sure there's more people with multiple accounts, just don't approve your on PR, which is quite obvious, that's it.
> 
> disagree it is a non-problem. There need to be some rules, approving other identity PRs is obviously an extreme, but appearing in 1 single PR with 2 identities is a problem (see #68076) and IMO it has to be completely visible or easy to find out we are dealing with the same person. so the comment above about displaying your name in the profile, etc

There is no nack in that thread, it's just asking the point in duplicating something we've had in zephyr for 6? If not more years now, the comment from this account just correcting some mistakes the OP said in their reply, and I feel like I'm more than knowledgeable on the area since for my job I'm the sole maintainer of that area and have contributed to it publicly (and privately) for years and in my personal free time do a lot of work around that such as https://github.com/thedjnK/AuTerm/ and https://github.com/thedjnK/net_loader so I disagree that there is a problem there

**Comment by nashif** [comment]
> There is no nack in that thread, it's just asking the point in duplicating something we've had in zephyr for 6? If not more years now, the comment from this account just correcting some mistakes the OP said in their reply, and I feel like I'm more than knowledgeable on the area since for my job I'm the sole maintainer of that area and have contributed to it publicly (and privately) for years and in my personal free time do a lot of work around that such as [thedjnK/AuTerm](https://github.com/thedjnK/AuTerm/) and [thedjnK/net_loader](https://github.com/thedjnK/net_loader) so I disagree that there is a problem there. If there's an inaccuracy with what I posted in that topic, feel free to correct it:

I am not really refering to the content of those comments and the validity of the statements made there. The fact that the same person appears in the same PR with two different identities seems very off and can be confusing to other reviewers, original submitter etc.

**Pull request merged**
