### PR TITLE
doc: Add gmtime_r() to rule A.5 exceptions 

### LINKED ISSUE #68003: subsys/net/lib/lwm2m/lwm2m_rw_cbor.c violates coding guidelines rule A.5
**Describe the bug**
Zephyr's coding guideline rule A.5 states which C library functions can be used by (embedded) code in the Zephyr tree
https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-5-c-standard-library-usage-restrictions-in-zephyr-codebase
subsys/net/lib/lwm2m/lwm2m_rw_cbor.c uses gmtime_r:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/lwm2m/lwm2m_rw_cbor.c#L46
which is not between these, and therefore is breaking this rule.

**To Reproduce**
N/A, code inspection

**Expected behavior**
No use of C library functions beyond those in that list in embedded Zephyr code (outside of the POSIX compatibility API layer)

**Impact**
Update 2024/01/26: 
Just the guideline violation.
After https://github.com/zephyrproject-rtos/zephyr/commit/4ff79cb74ac7c68957ce9a41847da4955dcb2721 was merged , this code builds without warnings for all in-tree libCs as even minimal libC provides this function https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/libc/minimal/source/time/gmtime.c#L81

**Logs and console output**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
Issue has been present since the file was added 8fd283a788f0198cc31a9ad5fa7f94c6588f81f2

### LINKED ISSUE #68056: subsys/shell/modules/date_service.c violates coding guidelines rule A.5
**Describe the bug**
Zephyr's coding guideline rule A.5 states which C library functions can be used by (embedded) code in the Zephyr tree
https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-5-c-standard-library-usage-restrictions-in-zephyr-codebase
subsys/shell/modules/date_service.c uses `gmtime_r()`:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/modules/date_service.c#L153
which is not between these, and therefore is breaking this rule.

**To Reproduce**
N/A, code inspection

**Expected behavior**
No use of C library functions beyond those in that list in embedded Zephyr code (outside of the POSIX compatibility API layer)

**Impact**
Just rule violation.

**Logs and console output**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
Issue has been present since the file was added c411ed93220bc0707903fe0fe15318c03a0d8412 

Related to #68003

Note, this shell module selects `POSIX_CLOCK`, and as such pulls part of the POSIX API compatibility shim. Due to this selection, this shell module is built for the native targets with PICOLIBC. PICOLIBC seems to always provide the `gmtime_r()` prototype even if `POSIX_C_SOURCE` is not defined (`gmtime_r()` is provided by default in C23 also). Therefore this will not trigger a build warning due to a missing prototype in this case. It seems also minimal and newlibc expose this function by default.

### PR DESCRIPTION
**Pull request by rlubos**
Add `gmtime_r()` to rule's A.5 exception list, and move its implementation to common libc area, as per @stephanosio [comment](https://github.com/zephyrproject-rtos/zephyr/issues/68003#issuecomment-1913872276) in #68003.

Fixes #68003
Fixes #68056

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]

**Review by aescolar — APPROVED** [review]
Fine by me

**Comment by keith-packard** [comment]
will need to update picolibc and the SDK for this. Is this going to land before the release?

**Comment by stephanosio** [comment]
> will need to update picolibc and the SDK for this. Is this going to land before the release?

We will need to target the next release since there is not enough to get that done.

**Review by stephanosio — APPROVED** [review]

**Comment by aescolar** [comment]
@stephanosio should we just merge this? Both CI checks failures are false positives, and there is no hard need to wait for a new SDK release containing the latest pico, as the code which uses it sets the macros it needs today. Worse case, in the meanwhile, new code using it would see a build warning if those are not set.

**Comment by stephanosio** [comment]
Scancode and compliance check failures are false positives. Merging.

**Pull request merged**
