### PR TITLE
Refactor mcux dspi driver to use device tree

### PR DESCRIPTION
**Pull request by MaureenHelm**
Refactors the mcux dspi driver to use device tree. Adds support for the frdm_kw41z since it has the same dspi peripheral as k64.

### CODE REVIEW

**Review by jfischer-no — COMMENTED** [review]
LGTM

**Review by dbkinder — APPROVED** [review]
+1 for docs

**Review by ydamigos — APPROVED** [review]
The changes regarding dts LGTM.

**Comment by MaureenHelm** [comment]
Rebased to fix merge conflicts

**Comment by MaureenHelm** [comment]
@galak ping

**Review by galak — COMMENTED** [review]
The dts.fixup might need minor updates based on merging of the GPIO dts script changes.

**Comment by galak** [comment]
Closing this as all this was in PR #7355

**Pull request closed without merging**
