### PR TITLE
driver: esp32: I2C code refactoring

### PR DESCRIPTION
**Pull request by sylvioalves**
Use i2c_hal functions to enable support for
multiple SoCs.

Use DT compat to enable I2C with from device
tree configuration.

Added support for ESP32S2 and ESP32C3.

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>

### CODE REVIEW

**Review by uLipe — APPROVED** [review]

**Review by glaubermaroto — APPROVED** [review]

**Comment by sylvioalves** [comment]
@cfriedt @nashif, I can't figure out the reason for buildkite to be failing as it points to `aruino_nano` board failure. Is `kconfig.esp32` change triggering that issue in the arduino project?

**Comment by sylvioalves** [comment]
> @cfriedt @nashif, I can't figure out the reason for buildkite to be failing as it points to `aruino_nano` board failure. Is `kconfig.esp32` change triggering that issue in the arduino project?

I added a update into`arduino_nano_33_ble` board to remove invalid I2C_X config.

**Comment by sylvioalves** [comment]
Just rebased.

**Review by uLipe — APPROVED** [review]

**Comment by sylvioalves** [comment]
Rebased again.

**Review by uLipe — APPROVED** [review]

**Comment by sylvioalves** [comment]
@cfriedt @nashif PTAL as well. Buidkite has failed but error is not related to this PR. Can you trigger the build again?

**Review by uLipe — APPROVED** [review]

**Comment by sylvioalves** [comment]
@cfriedt @nashif Now it worked.

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
