### PR TITLE
tests: kernel: do not enable PM in kernel tests

### PR DESCRIPTION
**Pull request by nashif**
- tests: kernel: remove tickless scenario
- tests: tickless: do not enable PM
- tests: kernel: remove pm from profiling test
- tests: logging: remove userspace testing

### CODE REVIEW

**Comment by nashif** [comment]
ok, one test is not related to PM

**Comment by ceolin** [comment]
Not sure about the profiling test. It has  a custom policy and it seems to be part of the test logic
https://github.com/zephyrproject-rtos/zephyr/blob/79c3ba802a1a7bded2399aabb03afbee23885745/tests/kernel/profiling/profiling_api/src/main.c#L26

**Comment by nashif** [comment]
> Not sure about the profiling test. It has a custom policy and it seems to be part of the test logic

I really do not know how custom PM policies related to profiling, this just do not belong here, it is very old code and when it was introduced probably it was to deal with some issue, however, now it is causing more issues than it supposed to solve.

**Comment by ceolin** [comment]
> > Not sure about the profiling test. It has a custom policy and it seems to be part of the test logic
> 
> I really do not know how custom PM policies related to profiling, this just do not belong here, it is very old code and when it was introduced probably it was to deal with some issue, however, now it is causing more issues than it supposed to solve.

I don't know about the test too, but my concern is that the policy decision is somehow part of test logic.

**Comment by nashif** [comment]
> I don't know about the test too, but my concern is that the policy decision is somehow part of test logic.

I do not see the logic tbh and why pm policy is part of profiling test, I mean the test itself is not a test really, it does not test anything, it just prints out stack usage

**Review by ceolin — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
