### PR TITLE
dts: boards: esp32_devkitc_wroom: add support blinky sample

### PR DESCRIPTION
**Pull request by Grin00**
add support blinky sample to esp32_devkitc_wroom board

### CODE REVIEW

**Comment by sylvioalves** [comment]
@Grin00 Do you have an `esp32_devkitc_wroom` with embedded LED?

**Comment by Grin00** [comment]
> @Grin00 Do you have an `esp32_devkitc_wroom` with embedded LED?

I have a clone of wroom devkit, something like [this one](https://www.amazon.com/Shinycome-ESP32-DevKitC-Development-ESP32-WROOM-32D-Bluetooth-Compatible/dp/B0CNZ2YS83/ref=sr_1_1?crid=6N1EBH0R62LM&keywords=esp32+wroom&qid=1702404840&sprefix=esp32+wroom%2Caps%2C233&sr=8-1). It has a power LED as original devkit, and embedded D2 blue LED that perfectly works with [blinky_pwm](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/basic/blinky_pwm/boards/esp32_devkitc_wroom.overlay#L13) sample
So I decided to add support of blinky sample and [fade_led](https://github.com/zephyrproject-rtos/zephyr/pull/66201)

**Comment by marekmatej** [comment]
@Grin00, thanks for your effort. The problem is that the official Espressif Esp32-devkitc supported in Zephyr does not have a user LED. Your PR says "make gpio2 a blue-led", which conflicts with the board assembly and with the Zephyr way. Moreover, there are many clones that could have LEDs on many different pins.

**Comment by Grin00** [comment]
> @Grin00, thanks for your effort. The problem is that the official Espressif Esp32-devkitc supported in Zephyr does not have a user LED. Your PR says "make gpio2 a blue-led", which conflicts with the board assembly and with the Zephyr way. Moreover, there are many clones that could have LEDs on many different pins.

Well, I am agree with you. I am able to create a PR for removing support of blinky_pwm by devkitc wroom. Do it?

**Pull request closed without merging**
