### PR TITLE
libc: cleanup exit()

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by keith-packard** [comment]
Do we have good definitions for what Zephyr wants `exit` vs `_exit` vs `_Exit` to do? How would this handle libc-specific state which is supposed to be cleaned up in `exit`, such as stdio and all of the `atexit` and `on_exit` bits?

**Comment by galak** [comment]
> Do we have good definitions for what Zephyr wants `exit` vs `_exit` vs `_Exit` to do? How would this handle libc-specific state which is supposed to be cleaned up in `exit`, such as stdio and all of the `atexit` and `on_exit` bits?

I don't think there is any good definition for this.  Much like what do we do on return of main.  I assumed `_exit` was meant purely as a hook for newlibc/picolibc to allow the OS to handle whatever it wants.  Obviously we don't do much other than spin forever right now.

**Comment by keith-packard** [comment]
> I don't think there is any good definition for this. Much like what do we do on return of main. I assumed `_exit` was meant purely as a hook for newlibc/picolibc to allow the OS to handle whatever it wants. Obviously we don't do much other than spin forever right now.

Sounds like it's going to be hard to evaluate whether this common implementation follows the spec until there's an actual spec. Is it that applications should never use any of these functions? Is there any notion of  a C99 "program" in Zephyr (which could be one or more threads) so that the semantics of `_Exit` could be defined to do something other than hang/reboot?

In any case, given that the C specification for `exit` includes invoking callbacks registered with `atexit`, flushing all stdio streams and removing `tmpfile` results, I don't think we can have a common implementation of `exit`. We should, however, provide a common implementation of `_Exit`.

**Comment by galak** [comment]
Going to close this and just open https://github.com/zephyrproject-rtos/zephyr/pull/57606 to have the test use `exit()` instead of `_exit()`

**Pull request closed without merging**
