### PR TITLE
doc: extensions: remove eager_only

### LINKED ISSUE #36569: '.. only:' is not working as expected in documentation
**Describe the bug**

We do have this role based content in our documentation that stopped working:

```
Zephyr Project Documentation
############################

.. only:: release

   Welcome to the Zephyr Project's documentation for version |version|.

   Documentation for the latest (main) development branch of Zephyr
   can be found at https://docs.zephyrproject.org/

.. only:: (development or daily)

   **Welcome to the Zephyr Project's documentation
   for the main tree under development** (version |version|).

```

The published documentation does not have any of the variants.

**To Reproduce**

check published docs and compare with source

**Expected behavior**

Need one variant at lease published

**Impact**

There is no way for us to create content based on the desired output, for example with

```
.. only:: html

   Use the version selection menu on the left to view
   documentation for a specific version of Zephyr.
```

### PR DESCRIPTION
**Pull request by gmarull**
The eager_only is currently breaking the usage of the `.. only`
directive, so remove it. Documentation seems to build fine without it.

Fixes #36569

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by mbolivar-nordic — COMMENTED** [review]
Hang on, are you sure about this? The commit log for when it was added (b645194cd3170b330a5431ab86fc6a0a61e474e1) says that the purpose is to handle conditional use of directives. We do have conditional directives in various places, including `contents::` and `toctree::` directives:

```

doc/guides/west/manifest.rst
11:.. only:: html
12-
13-   .. contents::
14-      :depth: 3

doc/guides/west/build-flash-debug.rst
16:.. only:: html
17-
18-   .. contents::
19-      :local:
20-

doc/contribute/index.rst
65:.. only:: latex
66-
67-   .. toctree::
68-      :maxdepth: 1
69-
70-      ../LICENSING.rst
```

**Comment by nashif** [comment]
`.. only::` not does not work at all, the eager_only was there to solve an issue and we do not know if this issue still exists, but right now it is cause for loads of content to not appear at all.

**Comment by nashif** [comment]
https://docs.zephyrproject.org/latest/guides/west/manifest.html for example does not have the 3 level depth.

**Comment by mbolivar-nordic** [comment]
That's a good example but the question still remains. E.g. do we get errors from the `toctree::` directive inside `only::` in doc/contribute/index.rst?

**Comment by gmarull** [comment]
@mbolivar-nordic errors would be seen on CI I guess

**Comment by nashif** [comment]
@gmarull  can you rebase.
The eager thing was introduced to support PDF building and that is exactly what I am looking into right now, so removing eager_only and figuring out how to get PDFs working again (and fixing html output because of non-working only::) takes precedence.

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic errors would be seen on CI I guess

Why would you guess that? Does CI build for LaTeX?

**Comment by gmarull** [comment]
> > @mbolivar-nordic errors would be seen on CI I guess
> 
> Why would you guess that? Does CI build for LaTeX?

I have tried to run the `latex` target (the one that runs Sphinx, no PDF build) and I only get these 3 warnings:

```
/home/gmarull/ws/teslabs/zephyr/zephyr/doc/_build/src/getting_started/index.rst:75: WARNING: Duplicate explicit target name: "install_dependencies_ubuntu". 
/home/gmarull/ws/teslabs/zephyr/zephyr/doc/_build/src/getting_started/index.rst:98: WARNING: Duplicate explicit target name: "install_dependencies_macos".  
/home/gmarull/ws/teslabs/zephyr/zephyr/doc/_build/src/getting_started/index.rst:134: WARNING: Duplicate explicit target name: "install_dependencies_windows".
``` 

I can't see any `only` on the getting started, so they must be caused by something else.

**Comment by gmarull** [comment]
> Why not build the PDF though? The whole point is to hide directives like toctree from the PDF build, right?

PDF build is currently broken, @nashif is working on fixes. I imagine that the warnings that only could generate should be thrown by Sphinx, not `pdflatex`.

**Review by mbolivar-nordic — APPROVED** [review]
Ah, OK, removing eager_only as a step along the way to restoring PDF builds makes sense then. Thanks for explaining; sorry I didn't get you at first.

**Pull request merged**
