### PR TITLE
tests: newlib/thread_safety: fix acrn_ehl_crb build error

### LINKED ISSUE #61129: acrn_ehl_crb:tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace.stress
**Describe the bug**
The test seems be failing fairly consistently with:

`/opt/toolchains/zephyr-sdk-0.16.1/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/12.2.0/../../../../x86_64-zephyr-elf/bin/ld.bfd: scripts/build/gen_kobject_placeholders.py did not reserve enough space for kobject rodata.`

https://github.com/zephyrproject-rtos/zephyr/runs/15459346533

Can't reproduce locally, any chance you x86 folks could look into it?

Can't quite figure if it's a regression but I've seen it failing for a while, for some reason only in the CI run.

**To Reproduce**
**UPDATED**
`west build -p -b acrn_ehl_crb -T tests/lib/newlib/thread_safety/libraries.libc.newlib_nano.thread_safety.userspace.stress` using Zephyr SDK 16.1

**Expected behavior**
A nice green PASS.

**Impact**
Blocking PR CI run.

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/runs/15459346533

### PR DESCRIPTION
**Pull request by dcpleung**
Somehow the kobject addresses are drastically different between Zephyr SDK 0.16.0 and 0.16.1. This results in the kobject hash table getting significantly bigger with many holes in it, and it overflows the reserved rodata area for kobject on acrn_ehl_crb. So workaround this for now by making the reserved space for kobject rodata bigger by providing a board config overlay.

Note that the renaming of prj_userspace.conf to userspace.conf and changing CONF_FILE to EXTRA_CONF_FILE is to workaround an issue with west build where providing CONF_FILE would skip the board overlay file.

Fixes #61129

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
Thanks for the quick followup @dcpleung. This has been reported in other tests and other boards as well (#61246 mentions `tests/net/socket/socketpair/net.socket.socketpair` on a newly introduced nxp board). Would it make sense to change `CONFIG_KOBJECT_RODATA_AREA_EXTRA_BYTES` default instead? (@bperseghetti)

**Comment by dcpleung** [comment]
This kconfig is supposed to be as small as possible to keep wasted space minimum. So I would say just change it as needed... unless the majority of boards are failing CI due to this.

**Review by nashif — APPROVED** [review]

**Comment by dcpleung** [comment]
> Also we are not in a super rush for this, I think we can hold this back for a bit while it's being investigated if you prefer so.

If that's the case, I will keep this as draft for now.

**Comment by bperseghetti** [comment]
> Thanks for the quick followup @dcpleung. This has been reported in other tests and other boards as well (#61246 mentions `tests/net/socket/socketpair/net.socket.socketpair` on a newly introduced nxp board). Would it make sense to change `CONFIG_KOBJECT_RODATA_AREA_EXTRA_BYTES` default instead? (cc @bperseghetti)

It was also failing on an older board as well that had no changes made to it.

**Pull request closed without merging**
