### PR TITLE
doc: fix comma typo in lvgl bindings

### PR DESCRIPTION
**Pull request by everedero**
Remove commas from dts array in lvgl bindings.

### CODE REVIEW

**Review by fabiobaltieri — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@everedero thanks for filing the fix! There's a small tweak you need to do in the commit message for the compliance script to pass, see: https://github.com/zephyrproject-rtos/zephyr/actions/runs/7696349856/job/20972409784?pr=68224

**Comment by kartben** [comment]
@everedero 

```
git commit --amend --author="First Last <email@xxx.com>"
```

**Comment by everedero** [comment]
I did amend the commit message and pushed it on my remote, but it did not update in the PR, shall I remove the current PR and re-create it?

**Comment by kartben** [comment]
@everedero Thanks!

**Review by faxe1008 — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
