### PR TITLE
cc13x2_cc26x2: define flash layout and support MCUboot bootloader

### PR DESCRIPTION
**Pull request by pepe2k**
The following series introduces changes required for support `MCUboot` on the **Texas Instruments SimpleLink CC13x2/CC26x2** MCU family and includes all the missing bits in the DTS files of the following boards:

- **CC1352P1 LaunchXL** (**CC1352P**)
- **CC1352R1 LaunchXL** (**CC1352R**)
- **CC1352R SensorTag** (**CC1352R**)
- **CC26x2R1 LaunchXL** (**CC2652R**)

The flash layout is defined as below (the same for all boards):

- `boot_partition:     40 KiB (0xa000)`
- `slot0_partition:   136 KiB (0x22000)`
- `slot1_partition:   136 KiB (0x22000)`
- `storage_partition:  32 KiB (0x8000)`
- `unused:              8 KiB (0x2000)`

When building application for chain-load with `MCUboot`, the `CCFG` will be included only with the bootloader image, so it should be programmed first (to make sure CCFG contains proper configuration).

Example memory map when building default `MCUboot` for `cc26x2r1_launchxl` board:

```
west build -b cc26x2r1_launchxl bootloader/mcuboot/boot/zephyr
[...]
Memory region         Used Size  Region Size  %age Used
           FLASH:       27514 B        40 KB     67.17%
             RAM:       23168 B        80 KB     28.28%
      FLASH_CCFG:          88 B         88 B    100.00%
           SRAM1:          0 GB         8 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%
```

### CODE REVIEW

**Comment by pepe2k** [comment]
@gmarull twister tests fails on linking (`power.c` is not built when `CONFIG_PM_DEVICE` is enabled). This was removed in [soc/arm/ti_simplelink/cc13x2_cc26x2/CMakeLists.txt](https://github.com/zephyrproject-rtos/zephyr/commit/c315c9b97c#diff-c32717a57ba1417d2b908e1d62dfae8d02cc150272a91d07d76e6b96dec16d60).

**Comment by gmarull** [comment]
> @gmarull twister tests fails on linking (`power.c` is not built when `CONFIG_PM_DEVICE` is enabled). This was removed in [soc/arm/ti_simplelink/cc13x2_cc26x2/CMakeLists.txt](https://github.com/zephyrproject-rtos/zephyr/commit/c315c9b97c#diff-c32717a57ba1417d2b908e1d62dfae8d02cc150272a91d07d76e6b96dec16d60).

https://github.com/zephyrproject-rtos/zephyr/pull/62244

**Review by vaishnavachath — APPROVED** [review]
@pepe2k Thanks for adding the MCUBOOT support, all of the launchpad also have an external SPI flash IIRC which can alternatively be used as Slot 1/scratch partition to achieve larger usable FW slots
This is what we did in BeagleConnect Freedom : https://git.beagleboard.org/beagleplay/cc1352/zephyr-beagle-cc1352/-/blob/sdk/boards/arm/beagle_bcf/beagleconnect_freedom.dts#L193

But that can definitely be an enhancement

**Comment by vaishnavachath** [comment]
> @vaishnavachath
> 
> > Thanks for adding the MCUBOOT support, all of the launchpad also have an external SPI flash IIRC which can alternatively be used as Slot 1/scratch partition to achieve larger usable FW slots
> 
> AFAIR, swap-using-scratch MCUboot's algorithm is no longer recommended (that's the reason why I didn't include `scratch_partition` here).
> 
> > This is what we did in BeagleConnect Freedom : https://git.beagleboard.org/beagleplay/cc1352/zephyr-beagle-cc1352/-/blob/sdk/boards/arm/beagle_bcf/beagleconnect_freedom.dts#L193
> > But that can definitely be an enhancement
> 
> Sounds fine, based on what I see, most of bits required for external SPI NOR flash support are missing in LaunchPad's DTSes at the moment anyway.
> 
> How about introduce later DTS overlay for all LaunchPads which would make all the partitions bigger and move `slot1_partition` and `storage_partition` to external SPI NOR? This would allow to use dual-image feature with just internal flash or in combination with external one.

Yes sure, the current changes looks good.

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
