### PR TITLE
drivers: spi_mcux_lpspi: clang-format

### PR DESCRIPTION
**Pull request by decsny**
Clang format the lpspi driver.

### CODE REVIEW

**Comment by danieldegrasse** [comment]
Checkpatch and clang-format seem to be in disagreement

image

**Comment by pdgendt** [comment]
> Checkpatch and clang-format seem to be in disagreement

TPAL #78522

**Review by pdgendt — DISMISSED** [review]
Typically we avoid these formatting commits to preserve file history, but given #78789 touches most of the file anyways, I think it's fine.

**Review by danieldegrasse — DISMISSED** [review]

**Comment by pdgendt** [comment]
Conflicts need to resolved.

**Review by pdgendt — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
