### PR TITLE
riscv: Make granularity of PMP configurable

### PR DESCRIPTION
**Pull request by bstsao**
According RISC-V privilege specification [1], 3.7 Physical Memory Protection
The granularity of PMP access control settings are platform-specific.

For example, the PMP granularity of adp_xc7k_ae350(N25F core [2]) FPGA-based development board is 8-bytes, but Zephyr currently force PMP granularity to 4-bytes.

This PR introduce the `CONIFG_PMP_GRANULARITY` to make the PMP granularity configurable.

If only support NAPOT encoding, the default value is 8-bytes, otherwise it is 4-bytes(NA4 or TOR).

[1] https://github.com/riscv/riscv-isa-manual/releases/download/Priv-v1.12/riscv-privileged-20211203.pdf
[2] http://www.andestech.com/en/products-solutions/andescore-processors/riscv-n25f/

### CODE REVIEW

**Review by fkokosinski — DISMISSED** [review]
LGTM

**Comment by carlescufi** [comment]
@carlocaione @npitre could you take a look?

**Comment by npitre** [comment]
Looks good overall. One minor nit:

Please rename `Z_RISCV_PMP_ALIGN` to something like 
`Z_RISCV_STACK_PMP_ALIGN` so it is clearer this is for stacks.
Otherwise `Z_RISCV_PMP_ALIGN` and `CONFIG_PMP_GRANULARITY` could be 
thought to be the same thing.

**Comment by bstsao** [comment]
Thanks for your advice. 
I've renamed `Z_RISCV_PMP_ALIGN` to `Z_RISCV_STACK_PMP_ALIGN` 
to indicate that this macro is for the stack.

**Review by carlocaione — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Pull request merged**
