### PR TITLE
CODEOWNERS: handle an account change

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
s/mbolivar/mbolivar-nordic/

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by mbolivar** [comment]
This is legit. Please use @mbolivar-nordic from now on.

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by nashif** [comment]
> This is legit. Please use @mbolivar-nordic from now on.

we need 2 pieces of ID and a blood sample.

**Review by nashif — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
> > This is legit. Please use @mbolivar-nordic from now on.
> 
> we need 2 pieces of ID and a blood sample.

:D will a GPG key do?

**Comment by carlescufi** [comment]
> > This is legit. Please use @mbolivar-nordic from now on.
> 
> we need 2 pieces of ID and a blood sample.

🥇

**Review by ioannisg — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
