### PR TITLE
scripts: west: sign: use top-level cmake project version

### PR DESCRIPTION
**Pull request by aunsbjerg**
use top-level cmake project version if defined, otherwise fall back to 0.0.0+0 as before.

can still be overridden with the \"--version\" argument to imgtool

Signed-off-by: Mikkel Jakobsen <mikkel.aunsbjerg@escolifesciences.com>

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
@aunsbjerg my approval is assuming that you tested this leads to no changes if the project versions are not defined -- can yo uconfirm?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
NAK. This changes the default from 0.0.0+0 to the version of the Zephyr RTOS being used since `cmake/modules/kernel.cmake` calls `project()`. This is unfortunate for reasons besides this one (see e.g. #28348).

**Comment by aunsbjerg** [comment]
> NAK. This changes the default from 0.0.0+0 to the version of the Zephyr RTOS being used since `cmake/modules/kernel.cmake` calls `project()`. This is unfortunate for reasons besides this one (see e.g. #28348).

This is not the intention of this change and _shouldn't_ be the case when using `CMAKE_PROJECT_VERSION` and not `PROJECT_VERSION`. The `CMAKE_PROJECT_VERSION` refers to the top-level project, and `PROJECT_VERSION` refers to the latest project. In Zephyr, the application/test/sample is the top-level project as far as I can tell.

I tested this just now, and it works as intended *if* the top-level `project()` specifies a `VERSION`, as is the case in my downstream application and the example application. However, if no `VERSION` is specified in the top-level `project()`, Zephyrs version is used. I frankly don't understand this - I would expect the `CMAKE_PROJECT_VERSION` to be empty and not be assigned some other project version.

So yeah, converting to draft until I can figure out a solution.

**Comment by nordicjm** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/modules/version.cmake is where the zephyr version is set to the cmake cache variables

**Pull request closed without merging**
