### PR TITLE
tests: benchmarks: remove obsolete boot_time test suite

### PR DESCRIPTION
**Pull request by jenmwms**
This test for boot time was sufficient when it was originally
introduced, but is no longer appropriate as the code and
ecosystem grew.

Signed-off-by: Jennifer Williams <jennifer.m.williams@intel.com>

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
need to also remove all the code and instrumentation feeding into that test.

**Comment by jenmwms** [comment]
> need to also remove all the code and instrumentation feeding into that test.

Thank you! I will update this PR.

**Comment by jenmwms** [comment]
Hi @nashif - to remove all the code and instrumentation feeding into the test - I understand that to be removing the config `BOOT_TIME_MEASUREMENT` throughout (kernel/init.c, idle.c, core/common.S , reset.S, ... ) which hold the hooks for `z_timestamp_main` and `z_timestamp_idle`. So, I'm working on a patch, will submit as a separate commit on this PR.

Please let me know if I misunderstood your comment. Thanks!

**Comment by nashif** [comment]
> Hi @nashif - to remove all the code and instrumentation feeding into the test - I understand that to be removing the config `BOOT_TIME_MEASUREMENT` throughout (kernel/init.c, idle.c, core/common.S , reset.S, ... ) which hold the hooks for `z_timestamp_main` and `z_timestamp_idle`. So, I'm working on a patch, will submit as a separate commit on this PR.

yes

**Review by laurenmurphyx64 — APPROVED** [review]

**Review by aasthagrover91 — APPROVED** [review]

**Review by yerabolu — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
