### PR TITLE
boards: arm: ubx_evkninab3_nrf52840 correct LED order

### PR DESCRIPTION
**Pull request by ghost**
Corrected order of led0, led1, led2 to be red, green, blue

Signed-off-by: Bob Recny <bob.recny@u-blox.com>

### CODE REVIEW

**Comment by brec-u-blox** [comment]
Just checking on this minor update. Thanks.

**Comment by brec-u-blox** [comment]
Just checking status. Can this be reviewed/merged?

**Comment by brec-u-blox** [comment]
Hi all. Just checking on this one. I know it's somewhat trivial, but it's the last in the u-blox nRF52-based module EVKs

**Review by MaureenHelm — APPROVED** [review]

**Comment by brec-u-blox** [comment]
Hi all. Just checking again. I hope to merge this last pull request soon.

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
