### PR TITLE
drivers: serial: fix STM32 async uart driver

### PR DESCRIPTION
**Pull request by niedzwiecki-dawid**
Fix a bug that causes not handling an IDLE line detection interrupt for some STM chips, e.g. STM32F412. It impacts the async UART communication - an information that data have been recieved is lost.

The issue occurs when the IDLE flag is set during handling another UART interrupt, e.g Transmission complete. The ISR calls uart_stm32_err_check function, which clears the noise error flag with LL_USART_ClearFlag_NE without any additional checks. Unfortunately, clearing the noise flag also clears the IDLE flag for some chips(an read to the USART_SR register followed by a read to the USART_DR register for STM32F412 clears PE, FE, NF, ORE and IDLE flags), hence the ISR is not called again for the IDLE event. The IDLE flag is no longer set.

Add checking the noise flag before clearing it.

Signed-off-by: Dawid Niedzwiecki <dn@semihalf.com>

### CODE REVIEW

**Comment by erwango** [comment]
Since it modifies uart API, you need to split your changes in 2 commits and be sure the API change is approved first.

**Comment by semihalf-niedzwiecki-dawid** [comment]
> Since it modifies uart API, you need to split your changes in 2 commits and be sure the API change is approved first.

Done. I'm not sure if a separated PR is needed.

**Comment by erwango** [comment]
> Done. I'm not sure if a separated PR is needed.

@dcpleung ?

**Review by FRASTM — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by dcpleung** [comment]
The change is trivial, and it does not change any existing APIs (e.g. functions and enums). So it should be fine.

**Review by erwango — APPROVED** [review]

**Pull request merged**
