### PR TITLE
Revert "scripts: bossac: Support flashing at an offset."

### LINKED ISSUE #22171: West bossac runner inorrectly tries to include an offset parameter when flashing
**Describe the bug**
The west bossac runner includes an offset parameter which is not accepted by the currently used bossac version after it was reverted back as a part of zephyrproject-rtos/sdk-ng#59.

**To Reproduce**
Steps to reproduce the behaviour:
1. build and attempt to flash anything using bossac (e.g. Adafruit Feather M0)

**Impact**
`west flash` unusable with bossac-programmed boards.

**Additional context**
This issue is being submitted to encapsulate a sub-issue of #22062.

### PR DESCRIPTION
**Pull request by KubaFYI**
This reverts commit bde3224c911176a6af4fa60a067c7492dfc76fe4.

Fixes: #22171

Signed-off-by: Kuba Sanak <contact@kuba.fyi>

### CODE REVIEW

**Review by mbolivar — CHANGES_REQUESTED** [review]
@galak are you ok with this?

**Review by mbolivar — APPROVED** [review]
Wrong button

**Comment by galak** [comment]
I guess I'd like to see the option left in the running and deal with the case if `offset=0` or change / support for `offset=None` to not pass --offset in that case.

**Comment by KubaFYI** [comment]
Thanks for the feedback @galak . I'll make sure to update the branch to reflect that.

**Pull request closed without merging**
