### PR TITLE
drivers: serial: NXP: Convert clock control to use DEVICE_DT_GET

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
Blocked on #32188

**Comment by mbolivar-nordic** [comment]
Also blocked on https://github.com/zephyrproject-rtos/zephyr/pull/32186, no?

**Comment by mbolivar-nordic** [comment]
> Also blocked on #32186, no?

Along with all the other similar PRs from today, I think.

**Review by mmahadevan108 — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
Needs rebase

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
