### PR TITLE
net: lwm2m: Fix floating point handling

### PR DESCRIPTION
**Pull request by rlubos**
I've identified several issues when I tried to fix a problem with floating-point resource writes (see commit messages for details).

In general, I've:
1. Dumped the differentiation between 32/64 bit float values in LwM2M engine, and focused on `float32_value`, which was most commonly used. The actual handling between 32/64 bit floats takes only place when TLVs are being parsed (and the actual type is identified based on the TLV size, as described in the specification).
2. Fixed the Plain Text formatter, which incorrectly parsed floating points.
3. Fixed JSON formatter, which had the same issue as above.
4. Fixed a few other issues in JSON formatter, which prevented successful writes in general.

I was actually considering to dump both float types defined by LwM2M and replace them with native `float` or `double`. Replacing `float32_value_t` with `double` should have minimal (if any) memory footprint impact and would increase the precision of the LwM2M floating point handling a lot. As it is a more invasive change to the engine however, I wanted to hear some opinions first, but for me, the use of `float32_value_t` is a bit counter-intuitive (and more difficult from the application point of view).

### CODE REVIEW

**Comment by MaikVermeulen** [comment]
Nice to see some work being done on the float implementation! 
Some quick thoughts:

- I'm still a little confused on why the special `float32_value_t` typedef is needed? Why not use a native float/double?
- The '32' notion is slightly confusing as it can be used to accept 64 bit values too. On the other hand though, the notion nicely underlines the type and implications.

I disliked the typedefs enough to replace them by a native float, and then use these functions to convert between the two:
```
float32_value_t float_to_float32_value_t (float input)
{
  float integer;
  float fractional;
  fractional = modff(input, &integer);

  float32_value_t output;
  output.val1 = (int32_t) integer;
  output.val2 = (int32_t) (fractional * 1e6);

  return output;
}
```
```
float float32_value_t_to_float (float32_value_t *input)
{
  return ((float) input->val1 + ((float) input->val2 / 1000000));
}
```

**Comment by rlubos** [comment]
> I'm still a little confused on why the special float32_value_t typedef is needed? Why not use a native float/double?

I was actually considering replacing `float32_value_t` with `double`, see the last paragraph in the PR description, just wanted to gather some opinions first, as it's a more invasive change. But I agree that this special representation of float is not very handy and built-in types should be easier for the application to handle (especially that double should actually increase precision at no cost).  But why were these types introduced in the first place is also a mystery to me.

> The '32' notion is slightly confusing as it can be used to accept 64 bit values too. On the other hand though, the notion nicely underlines the type and implications.

It just refers to the underlying types.

**Comment by marinjurjevic** [comment]
> I was actually considering replacing `float32_value_t` with `double`, see the last paragraph in the PR description, just wanted to gather some opinions first, as it's a more invasive change.

If I understood correctly, in the final implementation only `double` would be used for LwM2M FLOAT type? 
I agree with everything stated, we should remove this legacy code. 

I git blamed part of code declaring these types and they were included in [initial commit](https://github.com/zephyrproject-rtos/zephyr/commit/c46c206f8c65734cf16d4d859143325058edf63b) for lwm2m 4 years ago.

```
This library was based on source worked on by Joakim Eriksson,
Niclas Finne and Joel Hoglund which was adopted by Contiki and then
later revamped to work as a stand-alone library.
```
I quickly skimmed through contiki-ng repo and it seems even they abandoned this implementation.

**Comment by rlubos** [comment]
> If I understood correctly, in the final implementation only `double` would be used for LwM2M FLOAT type?

Yes, that's the idea.

> I quickly skimmed through contiki-ng repo and it seems even they abandoned this implementation.

Well, another argument to dump the custom float handling.

**Review by jukkar — APPROVED** [review]
LGTM. :+1: to moving to native double type.

**Comment by mlasch** [comment]
Hi, those changes look sensible, provided that there is a FPU present. For some boards like `native_posix` this is not (yet?) the case, at least it is not selected. For me it looks like testing lwm2m with the `native_posix` is not possible anymore after this change. This would also affect all SOCs which do not select `CONFIG_CPU_HAS_FPU` [1].

[1] https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_CPU_HAS_FPU.html

**Comment by MaikVermeulen** [comment]
> Hi, those changes look sensible, provided that there is a FPU present. For some boards like `native_posix` this is not (yet?) the case, at least it is not selected. For me it looks like testing lwm2m with the `native_posix` is not possible anymore after this change. This would also affect all SOCs which do not select `CONFIG_CPU_HAS_FPU` [1].
> 
> [1] https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_CPU_HAS_FPU.html

I haven't tested it, but perhaps software-support of floating points to replace the FPU functionality has to be enabled manually?

**Comment by pfalcon** [comment]
> float32_value_t 
> But why were these types introduced in the first place is also a mystery to me.

Just as hinted by other comments above, my guess would be to not rely (too much at least) on floating-point support to be available just to be able to deal with LWM2M.

Thus, the usual suggestion: why not split this PR in 2 parts, merge the obvious fixes for 2.7 LTS, and then consider whether adding dependency on native FP support should be part of 2.7 or not.

**Comment by pfalcon** [comment]
Commit message:

> This lead to issues
for instance with Leshan, where Leshan sent 64-bit value

Minor nitpick, but not everyone may know what Leshan is, so would be helpful to have a more detailed reference, like "Eclipse Leshan LWM2M library" (or server?).

**Comment by rlubos** [comment]
I've removed the transition to `double` from the PR, leaving only bug fixes. Additionally, I've added an extra commit which fixes a 32-bit binary float coversion, which I've identified during the rework.

**Comment by rlubos** [comment]
As for the transition to double, I'll open a separate PR after the release where we can discuss the topic further.

**Comment by rlubos** [comment]
> > Hi, those changes look sensible, provided that there is a FPU present. For some boards like `native_posix` this is not (yet?) the case, at least it is not selected. For me it looks like testing lwm2m with the `native_posix` is not possible anymore after this change. This would also affect all SOCs which do not select `CONFIG_CPU_HAS_FPU` [1].
> > [1] https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_CPU_HAS_FPU.html
> 
> I haven't tested it, but perhaps software-support of floating points to replace the FPU functionality has to be enabled manually?

@mlasch @MaikVermeulen 
It seems that I was overzealous with adding `select FPU` in the Kconfig. I've tested this with `qemu_x86` originally, and it only worked with FPU enabled - the reason for this is that minimal libc does not have support for software floating point. After switching to newlib it works fine with software FP support. And on the second thought, the LwM2M lib should not enforce either hardware or software FP. I think that in the final solution I'd add a proper `depends on` entry, to make sure that either FPU or software FP lib is avaiable. And then in the sample, either add board-specific overlay for qemu, or simply switch to newlib.

**Comment by rlubos** [comment]
Rebased & resolved conflict.

**Review by pfalcon — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
