### PR TITLE
boards: stm32_min_dev: Add SPI support

### PR DESCRIPTION
**Pull request by vslapik**
Add SPI support to stm32_min_dev board

Signed-off-by: Vasili Slapik <vslapik@gmail.com>

### CODE REVIEW

**Comment by vslapik** [comment]
Tested with BMP280 sensor attached using example from samples, was able to get correct values for temperature and pressure.

**Comment by MaureenHelm** [comment]
Hi @vslapik, thanks for your contribution! Please try to fix the shippable failures - there are a couple of in-tree spi samples and tests that aren't building correctly for your board:

- `samples/sensor/adxl372`
- `samples/sensor/bme280`
- `tests/drivers/spi/spi_loopback`

**Comment by vslapik** [comment]
I'm on it. Somehow my local run of sanitycheck differs from what I see here, need to figure out why together with appropriate UT fixes.

**Comment by MaureenHelm** [comment]
You can save yourself some time and run a subset of sanitycheck locally:

```$ sanitycheck -T samples/sensor -T tests/drivers/spi -p stm32_min_dev```

**Comment by vslapik** [comment]
Much appreciated, this is exactly what I was looking for :-)

**Review by dbkinder — APPROVED** [review]
+1 for doc changes.

**Comment by vslapik** [comment]
I have fixed those UT failures introduced by my change by adding appropriate Kconfig.defconfig file, failures are gone both on local environment and Shippable. However now Shippable complains about another failure **mps2_an385/tests/kernel/sleep/kernel.common.timing** which doesn't seem to be related to my changes and this failure wasn't seen in my local UT run. So I suspected that this is some kind of fluctuating test. I added "recheck" comment here trying to re-run Shippable (the way it is supposed to work if I understood Contribution Guidelines correctly) but it didn't trigger CI as I expected to. Could someone look at it, please?

**Review by erwango — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
