### PR TITLE
[Backport v3.5-branch] doc: zbus: fix VDED notification sequence figure

### LINKED ISSUE #64328: Documentation: ZBus VDED documentation is wrong for T1 > MS1 > MS2 > S1 scenario
**Describe the bug**
The VDED execution detail figure and table in zbus documentation are incorrect since Zephyr version 3.5.

**To Reproduce**
Take a look at [VDED documentation](https://docs.zephyrproject.org/3.5.0/services/zbus/index.html#virtual-distributed-event-dispatcher) when the priorities are  T1 > MS1 > MS2 > S1.

**Impact**
It can make developers confused about the zbus functioning.

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 32bdb24a92b5c6bb65185bbe3e6d4b88e647cf17 from #64200.

Fixes #64328

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
@rodrigopex This needs a bug report in order to be backported.

**Review by rodrigopex — COMMENTED** [review]
The issue (#64328) was created.

**Comment by henrikbrixandersen** [comment]
> The issue (#64328) was created.

Great! Now it just needs approvals ;)

**Review by jhedberg — APPROVED** [review]
Looks good.

Question: does the doc build actually take into account changes made to stable release branches? I.e. will content under `https://docs.zephyrproject.org/3.5.0/*` be eventually updated based on changes like this?

**Comment by jhedberg** [comment]
> will content under `https://docs.zephyrproject.org/3.5.0/*` be eventually updated based on changes like this?

...and I just noticed that the above link also contains the third version component (`0`), so 3.5.1 would have a different URL.

**Comment by jhedberg** [comment]
@rodrigopex your approval is still needed here

**Review by fabiobaltieri — APPROVED** [review]

**Review by rodrigopex — APPROVED** [review]

**Pull request merged**
