### PR TITLE
interrupt_controller: Fix initializing stm32_line_range structure

### PR DESCRIPTION
**Pull request by duda-patryk**
Index passed to DT_PROP_BY_IDX macro must be a number. Passing expression e.g. 2 * idx, results in taking value at second index and multiplying it by idx.

This patch changes the approach we use to initialize structures. Now list of line_ranges values is prepared and passed as arguments to DT_FOREACH_PROP_ELEM_VARGS. At each iteration we skip 2 * idx of list elements (skipping idx elements twice). After skipping, the first two elements of the list describe the range for the line processed in current iteration.

Fixes: #58421

### CODE REVIEW

**Comment by erwango** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/58197 available as an alternative.
Current solution avoids addition of UTIL_ macros, but is less readable.

One of both to be merged as part of RC2 due to https://github.com/zephyrproject-rtos/zephyr/issues/58830

**Comment by semihalf-duda-patryk** [comment]
I agree that #58197 is cleaner and easier to understand. For me, both patches are good, so please pick the one you like.

**Review by erwango — COMMENTED** [review]
I have a biased preference on https://github.com/zephyrproject-rtos/zephyr/pull/58197.
Of course, we can work on the readability by adding examples, but the code to initialize this driver is already somewhat complex and this change brings complexity to a next level.

**Comment by semihalf-duda-patryk** [comment]
> this change brings complexity to a next level

True. I spent 2 days to prepare this, which speaks for itself.

Ok. I'll keep this PR open until #58197 is merged. Just in case.

**Pull request closed without merging**
