### PR TITLE
build time selection of reversed display for ssd1306

### PR DESCRIPTION
**Pull request by sdalu**
Use of DTS to select at build time if ssd1306 will use a normal or a reverse display
see https://github.com/zephyrproject-rtos/zephyr/issues/19871

### CODE REVIEW

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Should be a Kconfig option as it is not a hardware property like height or width of the panel.

**Comment by sdalu** [comment]
@jfischer-phytec-iot, looking at current dts for ssd1306 you'll find `com-invdir` for "Scan direction is from last COM output to first COM output" (flipping display) which doesn't' seem to be hardware property and look similar to reverse mode. 
DTS would allow per instance configuration (if the driver support it), I'm not sure that Kconfig will allow that.
Do I stay in line with actual DTS or still move to Kconfig?

**Comment by jfischer-phytec-iot** [comment]
> @jfischer-phytec-iot, looking at current dts for ssd1306 you'll find `com-invdir` for "Scan direction is from last COM output to first COM output" (flipping display) which doesn't' seem to be hardware property and look similar to reverse mode.

A fixed display, for example mounted in a device, can not be rotated.

**Review by vanwinkeljan — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by jfischer-no — COMMENTED** [review]
`Fixes: 19873` will not close the issue, please change it to `Fixes: #19873` or better `Resolves: #19873`

**Review by jfischer-no — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
