### PR TITLE
stm32 sample to calculate CRC with stm32Cube functions

### PR DESCRIPTION
**Pull request by FRASTM**
This PR is proposing two basic samples to directly use stm32Cube HAL or LL functions in a zephyr application.
Cyclic Redundancy Check (CRC) is calculated on a data buffer directly using 

- LL_CRC functions from the stm32_ll_crc driver
- HAL_CRC functions from the stm32Xxx_hal_crc driver : requires a Kconfig to select USE_STM32_HAL_CRC and USE_STM32_HAL_CRC_EX

Running on any stm32 target with CRC instance

### CODE REVIEW

**Comment by FRASTM** [comment]
Running on a stm32 targe board:
$ west build -p always -b nucleo_h743zi samples/boards/st/crc

```
*** Booting Zephyr OS build v3.7.0-4465-gaff675500f60 ***

CRC computation
===============

CRC = 0x379e9f06
```

**Review by gmarull — CHANGES_REQUESTED** [review]
why do we need vendor HAL samples in Zephyr?

**Comment by henrikbrixandersen** [comment]
> why do we need vendor HAL samples in Zephyr?

I must admit I don't really see the point either. Zephyr should show-case Zephyr APIs in samples, not vendor HAL APIs.

**Comment by FRASTM** [comment]
rejected

**Pull request closed without merging**
