### PR TITLE
board: arm: disco_l475_iot1: Enable ADC support

### PR DESCRIPTION
**Pull request by Navin-Sankar**
Enable ADC support in disco_l475_iot1 board.

Signed-off-by: NavinSankar Velliangiri <navin@linumiz.com>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
LGTM, one tiny comment:
Please update also the `Default Zephyr Peripheral Mapping:` doc section

**Comment by Navin-Sankar** [comment]
> LGTM, one tiny comment:
> Please update also the `Default Zephyr Peripheral Mapping:` doc section



> LGTM, one tiny comment:
> Please update also the `Default Zephyr Peripheral Mapping:` doc section

@erwango done.

**Review by erwango — CHANGES_REQUESTED** [review]
Please remove the last commit, this is under dicussion in the following PR: https://github.com/zephyrproject-rtos/zephyr/pull/28594

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
CI failing due to #28594.
Will have to be rebased once fixed.

**Comment by ABOSTM** [comment]
@Navin-Sankar ,
There is already an ongoing PR to add ADC support for STM32 boards #27013
(awaiting merge since about 2 month due to buildkite issues).
It includes disco_l475_iot1 board, but not only.
Would you consider starting from PR #27013, comment it and propose changes if needed ?

**Review by galak — APPROVED** [review]

**Comment by ABOSTM** [comment]
DNM as a more complete PR already exist #27013

**Comment by galak** [comment]
Can you rebase/update now that #27013 is merged.

**Comment by Navin-Sankar** [comment]
@galak @ABOSTM rebased to #27013.

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
