### PR TITLE
MCUboot as application for ESP32xx

### PR DESCRIPTION
**Pull request by marekmatej**
This work provides MCUboot as default 2nd stage bootloader for ESP32xx targets, replacing/complementing currently used IDF bootloader.
Currently supported SoCs are:
- ESP32
- ESP32S2
- ESP32C3
- ESP32S3

### CODE REVIEW

**Comment by marekmatej** [comment]
There is a failing compliance check due to the register's name '`RESETING`', so this should be left as is.

**Review by LucasTambor — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]

**Comment by sylvioalves** [comment]
@npitre, in case this and https://github.com/zephyrproject-rtos/zephyr/pull/54835/commits/13f8dad94291608c60f6964967633b3b7f0400b6 gets reverted, build will break. So better to revert all PR if necessary.

**Comment by npitre** [comment]
I'm not talking about "arch: xtensa: Enable builds without the
multithreading" here which, for all I know about ARC, might be necessary.

I'm talking about "arch: riscv: Enable builds without the multithreading"
which is useless.

**Comment by marekmatej** [comment]
@npitre in the context of the whole PR and the ESP32 RISCV chips, it is actually useful and it allows us to disable the `MULTITHREADING` which makes the code footprint lower.

**Comment by npitre** [comment]
I'm sorry but this doesn't make any sense. Even if that were true for 
Esp32, this is a regression (footprint and runtime) for everybody else. 
So please consider another solution that would satisfy Esp32's needs.

**Pull request merged**
