### PR TITLE
drivers: serial: Xilinx ZynqMP/Zynq-7000 UART driver interrupt support fix

### PR DESCRIPTION
**Pull request by ibirnbaum**
- added SERIAL_SUPPORT_INTERRUPT in Kconfig.xlnx
- fixed UART_XLNX_PS_IRQ_CONF_FUNC macro which only worked for UART0,
  but not for UART1.

Interrupt support is required for test cases using the UART_PIPE feature
on the upcoming Cortex-A9 targets (QEMU/Zynq-7000).

Signed-off-by: Immo Birnbaum <Immo.Birnbaum@weidmueller.com>

### CODE REVIEW

**Review by stephanosio — COMMENTED** [review]
Thanks for submitting this PR.

Could you fix the commit title as well (not just the PR title)? Also it would be good to separate commits since these two changes are not related.

**Comment by ibirnbaum** [comment]
I changed the titles and split the commit as well as I could with my so far fairly limited git skills... I hope that's how the split was intended.

**Comment by stephanosio** [comment]
> I changed the titles and split the commit as well as I could with my so far fairly limited git skills... I hope that's how the split was intended.

The split looks good, but a few other things will need to be fixed in order to appease Gitlint (e.g. commit title/message line length and extraneous commits).

There is detailed information on what needs to be done in [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/index.html); in particular, have a look at interactive rebase/amending commits/force pushing.

**Comment by stephanosio** [comment]
CI will pass, but still need to get rid of all the previous/extraneous commits.

This PR should only contain the following two commits:
1. drivers: serial: Xilinx UART driver interrupt support feature flag
2. drivers: serial: Xilinx UART driver IRQ connect macro fix

**Review by stephanosio — COMMENTED** [review]
I tested this on `qemu_cortex_r5`, which uses `uart_xlnx_ps`, and the `tests/drivers/uart/uart_basic_api` `test_uart_fifo_read` does not seem to work properly -- the test is stuck (ignore the first two failing tests; they are unrelated to this PR and will need to be addressed separately).

```
*** Booting Zephyr OS build zephyr-v2.2.0-592-gc0d0f8b424de  ***
Running test suite uart_basic_test
===================================================================
starting test - test_uart_configure

    Assertion failed at ../src/test_uart_config.c:88: test_uart_configure: test_configure() == TC_PASS is false

FAIL - test_uart_configure
===================================================================
starting test - test_uart_config_get
This is a configure_get test.

    Assertion failed at ../src/test_uart_config.c:70: test_config_get: (ret == 0 is false)
set config error
FAIL - test_uart_config_get
===================================================================
starting test - test_uart_fifo_fill

    Assertion failed at ../src/test_uart_fifo.c:146: test_uart_fifo_fill: test_fifo_fill() == TC_PASS is false

FAIL - test_uart_fifo_fill
===================================================================
starting test - test_uart_fifo_read
Please send characters to serial console
```

I also tested `tests/boards/board_shell` on `qemu_cortex_r5` and noticed that it completely stopped working after enabling `SERIAL_SUPPORT_INTERRUPT`.

Could you run these two tests on your hardware and see if they work? If not, I think the interrupt mode implementation for `uart_xlnx_ps` is broken and that will need to be fixed before this (maybe that was why `SERIAL_SUPPORT_INTERRUPT` was not enabled in the first place?)

**Comment by ibirnbaum** [comment]
Hi Stephanos,
I'll do that! I'm just about done re-basing my Cortex-A aarch32 and Zynq-related additions under consideration of your commits for request #23668 (platform base code, SoC, Ethernet and GPIO device drivers, Zedboard & QEMU targets). Once I can build & debug binaries and run the test suite, I'll debug the driver. I originally came up with the modification as the 'net' tests using UART_PIPE wouldn't work without this feature flag, once it was added, the tests ran, so the flag must have *some* effect...

**Comment by ibirnbaum** [comment]
I've added an implementation of the run-time configuration get/set hook functions which had been missing so far, other than that, the driver was mostly already prepared for the kind of interrupt-driven operation as checked by the testcase mentioned above, but the interrupt status flags weren't cleared properly yet. 

The testcase now completes successfully on both the real hardware and QEMU, there's just one caveat: the RX test expects only one character per execution of the user callback function, therefore, the check for CR/LF doesn't work if the RX FIFO interrupt threshold is set to >1 character and neither CR nor LF is the first character in the buffer once the interrupt triggers, as data from the RX FIFO isn't queried in a while() loop. I've set the RX interrupt trigger threshold to 1 character for now, which seems highly inefficient to me. This might be a case where it would make sense to either modify the test routine or make the interrupt thresholds configurable for real-life operation via Kconfig. What's your opinion on that?

I guess the commit will hopefully follow tomorrow, as we're now past the stage of a simple one-liner modification, company policy says that a 2nd person within the company should do a quick review of the code before committing anything in the name of our company.

**Comment by ibirnbaum** [comment]
Seems like my git skills aren't good enough yet to figure out why the merge of my modifications with the changes regarding the DT_INST-macros that were admitted to the master branch in the meantime isn't recognized. I think I initially set up my fork of the repository the wrong way, without an upstream. I'm closing this request and will open a new one based on a clean repository with the latest modifications already on the master branch. Hopefully, merging will be easier with a correct upstream set.

**Pull request closed without merging**
