### PR TITLE
gen_mmu.py: load directly

### PR DESCRIPTION
**Pull request by tyrantlizard77**
On most workstations this was unintentionally being run under Python 2.

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Review by lpereira — APPROVED** [review]
Looks fine, but I wonder if it would be possible to have a $(PYTHON) variable that's the result of probing for the correct version of Python.

**Review by nashif — APPROVED** [review]

**Comment by andrewboie** [comment]
Don't see why $(PYTHON) is helpful, setting the script executable and having the OS parse the she-bang at the beginning does the right thing

**Comment by AdithyaBaglody** [comment]
Does the build on windows work properly with this change??

**Comment by andrewboie** [comment]
@AdithyaBaglody given that Windows build run under a BASH shell and we call other scripts directly exactly like this, I really have no idea what you are talking about...

**Pull request merged**
