### PR TITLE
board: arm: add initial support for Silabs Happy Gecko EFM32HG

### PR DESCRIPTION
**Pull request by mtuxpe**
Added Gecko SDK for Silabs Happy Gecko EFM32HG family

Signed-off-by: Marcio Montenegro <mtuxpe@gmail.com>

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Commit message needs to conform to what we have in CONTRIBUTING.rst for 3rd party code (look towards the bottom of CONTRIBUTING.rst) for examples/details.

**Review by galak — CHANGES_REQUESTED** [review]
Also, we need to be able to test code, so would need an SoC port & board port that uses EFM32HG before this gets accepted.

**Comment by mtuxpe** [comment]
Hi Kumar,
My first idea was to  submit  1 pull request for Gecko SDK and another pull
for board,examples,docs, etc...

**Comment by galak** [comment]
> Hi Kumar,
> My first idea was to  submit  1 pull request for Gecko SDK and another pull
> for board,examples,docs, etc...

Its best to have it all in one PR, but just separate commits, one for the SDK import, one for SoC, and one for board.

**Comment by chrta** [comment]
You can have a look here on how to structure the commits: https://github.com/zephyrproject-rtos/zephyr/pull/271/commits

**Comment by chrta** [comment]
@galak This pull request is obsolete and can be closed. It is part of https://github.com/zephyrproject-rtos/zephyr/pull/6945

**Comment by mtuxpe** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Duarte Nogueira: LIBERTEM A
ELEFANTE BAMBI" e queria saber se você pode ajudar assinando também.

A nossa meta é conseguir 200.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/zVM9JvLdfC

Obrigada/Obrigado!
Marcio

**Pull request closed without merging**
