### PR TITLE
dts: Remove support for deprecated DTS binding syntax

### PR DESCRIPTION
**Pull request by galak**
We deprecated a number of aspects of the DTS binding syntax in Zephyr
2.1.  Remove the support for the deprecated syntax.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Code changes look sane, though I'm just now coming up to speed on edtlib internals.

However, bindings.rst needs an update.

**Comment by galak** [comment]
> However, bindings.rst needs an update.

Should we keep or just remove the section in bindings.rst on transitioning from the old to new binding style?

**Comment by mbolivar-nordic** [comment]
I'm OK with removing the docs on transitioning the old style if you are; we've waited enough releases, right? And anyway the old release doc artifacts are still online if anybody needs them.

**Review by mbolivar-nordic — APPROVED** [review]
Code and docs changes LGTM. Perhaps mention the removal in the release notes?

**Comment by mbolivar-nordic** [comment]
This docs error needs fixing:

```
 ##[error]/home/runner/work/zephyr/zephyr/doc/_build/rst/doc/releases/release-notes-2.1.rst:422: WARNING: undefined label: legacy_binding_syntax (if the link has no caption the label must precede a section header)
```

I am actually not sure what to do with this... maybe link to the old release page? Or just edit the old notes and leave a comment saying "this page was edited during the 2.4 development cycle to reflect removal of support for the old bindings" or so.

**Review by sjg20 — APPROVED** [review]
Well the Python looks OK at least

**Pull request merged**
