### PR TITLE
doc: remove fix_tex script

### PR DESCRIPTION
**Pull request by gmarull**
The LaTeX build succeeds without the fix_tex.py script, so remove it.
The file actually mentions ".tex file produced by doxygen", so it may
not be relevant for Sphinx after all.

### CODE REVIEW

**Comment by carlescufi** [comment]
Typo: `fix_tex`, not `fix_text`

**Comment by gmarull** [comment]
> Typo: `fix_tex`, not `fix_text`

fixed, thx

**Comment by nashif** [comment]
Did you verify the output without this fix being applied? The fix does not seem to be related to a build failure, rather a layout issue.

**Comment by gmarull** [comment]
> Did you verify the output without this fix being applied? The fix does not seem to be related to a build failure, rather a layout issue.

I've just checked, and the script does exactly `0` replacements on the tex file, so it effectively does nothing to it.

**Comment by mbolivar-nordic** [comment]
>  The fix does not seem to be related to a build failure

Are you sure? It looks like the regular expression is fixing a runaway argument, which would be a syntax error in .tex, although it's doing it in a way that seems to throw away some information.

But that said, if the error is gone, no need for the 'fix'.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by nashif** [comment]
> Are you sure? It looks like the regular expression is fixing a runaway argument, which would be a syntax error in .tex, although it's doing it in a way that seems to throw away some information.

No, I am not sure, just asking to double check the output so we do not get any surprises with the PDF output after removing this.

The commit message for this fix:

```
commit 9945e7fda0ac81a4f343fc040828bad3f0494c2d
Author: Daniel Leung <daniel.leung@intel.com>
Date:   Thu Aug 23 11:11:11 2018 -0700

    doc: add ability to generate PDF

    This adds new targets to generate build documentation through
    LaTEX to PDF.

    There are a few notes:

    1. pdflatex complains about the tex file generated by doxygen
       so it needs to be fixed with a Python script before feeding
       in through pdflatex.
```

so, if there are no complaints and the output is sane, all is good.

**Comment by mbolivar-nordic** [comment]
> so, if there are no complaints and the output is sane, all is good.

Since the output is not causing a latex error anymore and the script has no effect, I think that it should be safe to merge this.

**Review by nashif — APPROVED** [review]

**Pull request merged**
