### PR TITLE
xtensa: fix dts_fixup.h with new DT_ prefix

### PR DESCRIPTION
**Pull request by nashif**
This fixes majority of drivers, however we still see build failures with
the interrupt handler.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
I still can see this:

```
ns -D__SIZEOF_LONG__=4 -fno-pic -fno-strict-overflow -Wno-pointer-sign -Werror=implicit-int -Wpointer-arith -ffunction-sections -fdata-sections -mlongcalls -std=c99 -o CMakeFiles/zephyr.dir/drivers/timer/xtensa_sys_timer.c.obj   -c /home/nashif/Work/github/zephyr/drivers/timer/xtensa_sys_timer.c
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S: Assembler messages:
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:983: Error: invalid symbolic operand
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:983: Error: non-constant expression in ".if" statement
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1065: Error: invalid symbolic operand
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1065: Error: non-constant expression in ".if" statement
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1138: Error: invalid symbolic operand
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1138: Error: non-constant expression in ".if" statement
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1210: Error: invalid symbolic operand
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1210: Error: non-constant expression in ".if" statement
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1282: Error: invalid symbolic operand
/home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:1282: Error: non-constant expression in ".if" statement
xt-xcc ERROR:  /opt/xtensa/XtDevTools/install/tools/RF-2016.4-linux/XtensaTools/bin/xt-as returned non-zero status 1
make[2]: *** [zephyr/CMakeFiles/zephyr.dir/build.make:177: zephyr/CMakeFiles/zephyr.dir/arch/xtensa/core/xtensa_vectors.S.obj] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/nashif/Work/github/zephyr/build'
make[1]: *** [CMakeFiles/Makefile2:535: zephyr/CMakeFiles/zephyr.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Linking C static library libkernel.a
cd /home/nashif/Work/github/zephyr/build/zep

```

**Comment by rgundi** [comment]
I too reached till exactly the same stage and then couldn't find a way further.

**Comment by nashif** [comment]
> /home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:983: Error: non-constant expression in ".if" statement

This is not related to the DT_ changes, the build issue came in with the timer changes ;-(

**Comment by rgundi** [comment]
> > /home/nashif/Work/github/zephyr/arch/xtensa/core/xtensa_vectors.S:983: Error: non-constant expression in ".if" statement
> 
> This is not related to the DT_ changes, the build issue came in with the timer changes ;-(

oh. thanks for figuring this out. I was about to start dissecting the other commits to see where this got broken.

**Review by rgundi — APPROVED** [review]

**Pull request merged**
