### PR TITLE
Do not reuse tag names (misra 5.7)

### PR DESCRIPTION
**Pull request by nashif**
Do not reuse tag name following zephyr coding guidelines (misra 5.7)

this is just the first pass.

﻿- fdtable: fdtable: do not use tag name fd_entry
- logging : do not reuse tag name log_output
- doc: device: follow coding guidelines
- drivers: device: do not reuse tag name 'device'

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Are we 100% sure we're reading that rule correctly?   ANSI put the struct tag into a separate namespace from symbols way back in the 80's precisely to prevent collisions like this and permit code like exactly the stuff this patch is changing.  Why would MISRA care?

**Review by chrta — APPROVED** [review]
Do we have a tool to prevent this issue from being (re-)added later on?

**Comment by nashif** [comment]
> Do we have a tool to prevent this issue from being (re-)added later on?

we do, but this will take some time to integrate.

**Review by dcpleung — APPROVED** [review]

**Comment by ceolin** [comment]
> Are we 100% sure we're reading that rule correctly? ANSI put the struct tag into a separate namespace from symbols way back in the 80's precisely to prevent collisions like this and permit code like exactly the stuff this patch is changing. Why would MISRA care?

I think the interpretation  is correct, the rule says that a tag name has to be a unique identifier. According with the C standard an identifier can be an object, a function, a tag, a member of a struct, union, typedef name, ....

My understanding is that the main problem that the rule address is the re-use of a tag for different types, but *probably* based on observation or some kind of statistical analysis they identified that reusing a tag name lead developers to make mistakes and recommended to not do this.

**Review by ceolin — APPROVED** [review]
lgtm. We just need to be careful to no introduce violations to rules 5.8 and 5.9, because we are not using any specific namespace when renaming them.

**Review by scottwcpg — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by albertofloyd — APPROVED** [review]

**Pull request merged**
