### PR TITLE
logging: Remove long interrupt locking when immediate mode is used.

### LINKED ISSUE #20770: irq locking in logging backend can cause missing interrupts
**Describe the bug**
The logging subsystem uses irq_lock() in certain locations to lock all interrupts while processing data. When CONFIG_LOG_IMMEDIATE is enabled interrupts will be disabled during the whole write progess, as can be seen here:
https://github.com/zephyrproject-rtos/zephyr/blob/d58f8bee79dddb9aa1b65a2ef1624ebf1b389a4e/subsys/logging/log_backend_std.h#L75

This can cause drivers which are relying on interrupts for reading data to miss bytes while logging at the same time.

I noticed the bug while working with an external cellular modem for data transmission with an STM32L4. Bytes from the UART interface are read by an interrupt handler. I noticed seemingly randomly lost bytes every now and then.

When commenting out the disabling of interrupts while writing data at https://github.com/zephyrproject-rtos/zephyr/blob/d58f8bee79dddb9aa1b65a2ef1624ebf1b389a4e/subsys/logging/log_backend_std.h#L90 the issue disappears.

**To Reproduce**
I unfortunately don't have a sample project which demonstrates the issue at the moment. An external modem connected to the uC with net example code should already cause the issue. Logging frequently should increase the chance to cause this issue.
This especially happens while sending/recieving big chunks of data, like large packages.

**Expected behavior**
I expect peripheral drivers using interrupts for reading (like UART or I2C) to receive data reliably without the possibility to loose bytes in any case.

**Discussion**
I haven't looked at the logging backend code so far and am sure, that there is a specific reason why all interrupts must be disabled while sending data.
I would like to know why there is the need for this and how we could maybe prevent this from causing issues in other peripheral drivers.

### PR DESCRIPTION
**Pull request by nordic-krch**
Changed behavior of the logger in immediate mode. Previously, context was lock for whole string processing and sending which resulted in log output being clean and not interleaved but at the cost of very long period of interrupt locking. It is changed to lock interrupts only for single byte sending over transport (e.g. uart). With this approach long locking time is removed but log output may be garbled since one log message can be interrupted by another.

Added test suite for log immediate mode which checks if logger is stable when log is preempted by another log.

Log output buffer is fixed to be single byte in immediate mode. It does not make sense to have longer buffer, saves ram and simplifies processing.

Fixes #20770.

### CODE REVIEW

**Comment by andrewboie** [comment]
Can you give some detail on why you are using interrupt locking here, instead of a semaphore or something like that?

If the answer is because there could be contention with interrupt handlers that are trying to possibly log something, I don't think preventing those interrupt handlers from running is desirable from a system latency perspective.

**Comment by nordic-krch** [comment]
> Can you give some detail on why you are using interrupt locking here, instead of a semaphore or something like that?

That's because log can be called from any context.

> I don't think preventing those interrupt handlers from running is desirable from a system latency perspective.

Immediate mode introduces huge system latency, each log message is processed in the context of the call, blocking for hundred of microseconds in given context (https://github.com/zephyrproject-rtos/zephyr/blob/d5314b8387bbd8b29ed9efbd57e2bf045e78b25f/subsys/logging/Kconfig#L123)

**Comment by andrewboie** [comment]
> > Can you give some detail on why you are using interrupt locking here, instead of a semaphore or something like that?
> 
> That's because log can be called from any context.
> 
> > I don't think preventing those interrupt handlers from running is desirable from a system latency perspective.
> 
> Immediate mode introduces huge system latency, each log message is processed in the context of the call, blocking for hundred of microseconds in given context (
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/d5314b8387bbd8b29ed9efbd57e2bf045e78b25f/subsys/logging/Kconfig#L123
> 
> )

Why are you using irq_lock/unlock instead of a spinlock?

**Comment by wentongwu** [comment]
basically I think we should keep the original lock interrupts here to keep the output of logger clean for immediate mode, users should enable logging thread if the application take care system latency.

for saving more buffer, current design handles the string format exactly before the really output, I haven't the latency data of this part, if it takes long, I don't think we should fix it because there will be huge change for logging subsystem, users definitely should use logging thread; but I would like to think it's the uart(for uart backend example) cause more system latency, I'm not sure if there is good way to handle it, I just imagine one when uart is doing the transfer we can have CPU to handle the next format, not sure if it works and if it's implementable.

**Comment by nordic-krch** [comment]
@wentongwu 
> basically I think we should keep the original lock interrupts here to keep the output of logger clean for immediate mode, users should enable logging thread if the application take care system latency.

Unfortunately, there will be those who prefer to have no interrupts locked and interleaved output and those preferring to have clean output. Some may expect that log_immediate will behave like printk which does not lock.

I will add this as an option then.

**Comment by carlescufi** [comment]
@andrewboie can you take a look at @nordic-krch's latest proposal in this PR?

**Review by wentongwu — APPROVED** [review]
PR looks good. But I still don't understand why they need interleaved output, AFAIK the LOG_PRINTK is used to overcome printk's no lock.

**Comment by nordic-krch** [comment]
@wentongwu 
> AFAIK the LOG_PRINTK is used to overcome printk's no lock.

and that works well when deferred mode is used. Some may want to use immediate mode but locking context is a problem for them (yet they can accept that log processing takes multiple milliseconds in any context, including interrupts).

Personally, i think that immediate mode works well for emulator, tests or single apps where there is not much going on and becomes unacceptable in more complex real time application.

**Comment by nordic-krch** [comment]
@andrewboie ping

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@andrewboie mind taking a look at this one?

**Review by tyrantlizard77 — APPROVED** [review]

**Pull request merged**
