### PR TITLE
Add STM32L451

### PR DESCRIPTION
**Pull request by benediktibk**
Add the MCU STM32L451.

### CODE REVIEW

**Comment by benediktibk** [comment]
My approach was to copy the files from the L452 and work through the differences of these two MCUs according to their datasheets. I tested it on a custom PCB, and the basic functionality (RCC, clocks, UART, GPIOs, UART, ...) is fine.

**Review by gautierg-st — DISMISSED** [review]
Approved because it seems correct, but from what I see, the only difference between L451 and L452 is the USB in the 52. Thus, it would be nice to include the 51 in the 52, and remove all nodes but the USB. That would avoid unnecessary duplication.

**Comment by benediktibk** [comment]
> Approved because it seems correct, but from what I see, the only difference between L451 and L452 is the USB in the 52. Thus, it would be nice to include the 51 in the 52, and remove all nodes but the USB. That would avoid unnecessary duplication.

I introduced a base called L45 and included it in L451 and L452.

**Comment by gautierg-st** [comment]
Thank you for this, but I don't think it is necessary to introduce a stm32l45.dtsi. It is perfectly fine to use stm32l451.dtsi as a base. This is how it's done on other series and it would be better to keep the same structure.

**Comment by benediktibk** [comment]
> Thank you for this, but I don't think it is necessary to introduce a stm32l45.dtsi. It is perfectly fine to use stm32l451.dtsi as a base. This is how it's done on other series and it would be better to keep the same structure.

Done

**Review by gautierg-st — APPROVED** [review]
LGTM, thanks!

**Review by erwango — APPROVED** [review]

**Pull request merged**
