### PR TITLE
samples: bluetooth: hci_usb: add missing config param

### PR DESCRIPTION
**Pull request by pabigot**
Samples should not assume that the board defconfig selects BT_CTLR when BT is selected.

Relates to #28091

### CODE REVIEW

**Comment by pabigot** [comment]
This appears to be a duplicate of #27105 except that this time whatever made me add it wasn't a build error.  I'll need to go back and figure out what the problem was this time.

**Comment by pabigot** [comment]
Aha: If you add this to the sample
```
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n
```
when `CONFIG_BT_CTLR=y` is not selected then plugging the device into a Linux system produces:

```
*** Booting Zephyr OS build zephyr-v2.4.0-4-g1e227d157697  ***
Bluetooth over USB sample
[00:00:00.310,668] <err> bt_hci_raw: No HCI driver registered
[00:00:00.310,699] <err> usb_bluetooth: Failed to open Bluetooth raw channel: -19
```

and the device doesn't work.  With `CONFIG_BT_CTLR=y` selected it gives:

```

*** Booting Zephyr OS build zephyr-v2.4.0-4-g1e227d157697  ***
Bluetooth over USB sample
[00:00:00.339,813] <inf> bt_hci_raw: Bluetooth enabled in RAW mode
```

and the device does work.

**Comment by jhedberg** [comment]
I suspect the idea here is that the board should have a sane default to enable its Bluetooth HW if it exists. What you're now doing is not without issues: the Bluetooth controller that the board has access to may not be a native one, i.e. some other HCI driver might be providing access to it (e.g. the RPMsg one or UART) and we just want to proxy it further over USB.

**Comment by joerchan** [comment]
I would say that this change is correct. The HCI (usb/uart/spi) are fundamentally controller samples, if controller is not supported then the sample won't work.

If we agree to do this then all hci_X samples should have it enabled though.

**Comment by jhedberg** [comment]
@joerchan there should be some consistency between boards though. I assume this issue exists because some boards enable the controller by default and others don't?

**Comment by jhedberg** [comment]
@carlescufi any thoughts on this?

**Comment by pabigot** [comment]
> @joerchan there should be some consistency between boards though. I assume this issue exists because some boards enable the controller by default and others don't?

Yes, that's why it happens to work for in-tree boards.  I don't think it's reasonable to expect people developing without-of-tree boards to know that they're supposed to have an "if BT then BT_CTLR" block in a defconfig.  I specifically don't do that for my Raytac boards because I want all dependencies that aren't implicit in core Zephyr to be explicit.

**Comment by joerchan** [comment]
@jhedberg Yes it is board defconfigs. Which means that if you compile peripheral sample you will get BT_CTLR=y on nrf52dk, and BT_CTLR=n on native_posix. In this case the defaults have ended up with the correct configuration.
But for these samples the board defconfig should be overriden, since BT_CTLR is required for the sample in this case.

**Comment by jhedberg** [comment]
I'm still having some some conflicting thoughts on this. IMO if a board has Bluetooth support (as in, it has Bluetooth HW), then enabling `CONFIG_BT=y` for it should result in the board selecting an appropriate default HCI driver. Why is this not a reasonable thing to expect from boards? We could even document it somewhere.

Maybe the reason I feel different about this (in terms of this not having anything to do with BT_CTLR specifically) is that when I started working with Zephyr Bluetooth there was no controller support at all, yet already then we had HCI_RAW-based applications. In particular, we could run it on the Arduino 101 board where you interfaced (from a PC) with a Quark CPU which in turn talked to an nRF51-based controller over UART. I.e. the controller you got access to from the host side was not a native one.

**Comment by pabigot** [comment]
>  Why is this not a reasonable thing to expect from boards? We could even document it somewhere.

It's a reasonable thing to expect only if it's clearly documented.

So alternatives could be to 
* document the expectation that `BT` should select `BT_CTLR` *in the target board files* if the Zephyr application is expected to provide the controller; and/or
* add `BT_CTLR` to the HCI samples and document in their READMEs the conditions under which it should be turned off because it's not necessary or is undesirable.

In any case at this stage of Zephyr I expect the vast majority of people trying to get the sample to run on their own boards will be using a native controller enabled by `BT_CTLR`, so the most helpful approach is to provide that in the sample so people understand that it's part of the Zephyr Bluetooth architecture.

If the conclusion is updating all HCI sample configurations to select the controller (as done for hci_usb here) is acceptable I'll update this, but would need to know what text to put in the README to describe cases where that's not the right selection.

**Comment by jhedberg** [comment]
A bit of a side-topic: I've been thinking that maybe the runtime-based registration of HCI drivers is a bit overkill (basically inherited from Linux where you often have dynamic controllers come and go and even multiple controllers). If we changed it to be a built-time registration (e.g. just requiring the controller to provide some well-known symbols) we'd get build errors for this situation rather than it being discovered only at runtime.

**Comment by joerchan** [comment]
Ok. documenting it is well enough, if the hci_usb sample can be made to work without native controller support, but forward it to a different driver instead.

The out-of-tree board sample also sets the defconfig for `BT_CTLR` so we have it there.

**Comment by pabigot** [comment]
> The out-of-tree board sample also sets the defconfig for `BT_CTLR` so we have it there.

The out of tree board sample does it incorrectly, by having:

```
CONFIG_BT=y
CONFIG_BT_CTLR=y
```
in `board_defconfig`.

The correct way to do this is:
```
config BT_CTLR
	default BT
```
in `Kconfig.defconfig`.

I'm tired of fighting this, so I've done this in my out of tree board.  I'll leave it to be fixed the next time somebody (maybe me) runs into the problem, or when I'm back on Nordic's time.

**Pull request closed without merging**
