### PR TITLE
Fix Build failures when compiling the NXP USB driver

### PR DESCRIPTION
**Pull request by mmahadevan108**
Failure introduced as part of PR https://github.com/zephyrproject-rtos/zephyr/pull/67261

### CODE REVIEW

**Review by yvanderv — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by tmon-nordic — COMMENTED** [review]
Is it necessary to revert both commits? Isn't  21c9c4abfe5c858b1c5d6c45a2c919d81b12a02b the only culprit?

**Review by jfischer-no — CHANGES_REQUESTED** [review]
If necessary, this should be done with
git revert -s 21c9c4abfe5c858b1c5d6c45a2c919d81b12a02b
git revert -s 2b91d62c0ef7be59c5de18018b66fc31adc26464

**Comment by mmahadevan108** [comment]
> Is it necessary to revert both commits? Isn't [21c9c4a](https://github.com/zephyrproject-rtos/zephyr/commit/21c9c4abfe5c858b1c5d6c45a2c919d81b12a02b) the only culprit?

Yes, both are related to the changes added as part of the PR to the USB HAL driver.

**Comment by mmahadevan108** [comment]
> If necessary, this should be done with git revert -s [21c9c4a](https://github.com/zephyrproject-rtos/zephyr/commit/21c9c4abfe5c858b1c5d6c45a2c919d81b12a02b) git revert -s [2b91d62](https://github.com/zephyrproject-rtos/zephyr/commit/2b91d62c0ef7be59c5de18018b66fc31adc26464)

@jfischer-no, that is how I reverted these commits.

**Comment by jfischer-no** [comment]
> > If necessary, this should be done with git revert -s [21c9c4a](https://github.com/zephyrproject-rtos/zephyr/commit/21c9c4abfe5c858b1c5d6c45a2c919d81b12a02b) git revert -s [2b91d62](https://github.com/zephyrproject-rtos/zephyr/commit/2b91d62c0ef7be59c5de18018b66fc31adc26464)
> 
> @jfischer-no, that is how I reverted these commits.

Then the commit message would be
```
    Revert "drivers: usb: device: add start of frame notifications to nxp mcux driver"
    
    This reverts commit 21c9c4abfe5c858b1c5d6c45a2c919d81b12a02b.
```
easier to spot in the history and re-reverted.

**Comment by mmahadevan108** [comment]
> 2b91d62

Update the PR with the original revert commit messages.

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
