### PR TITLE
Kconfig: Fix FLASH_LOAD_{OFFSET,SIZE} issue when enabling BOOTLOADER_MCUBOOT in menuconfig + documentation and naming improvements

### LINKED ISSUE #20673: guiconfig not working properly?
**Describe the bug**
Hello,
I am trying to run` west build -t guiconfig`, make some changes, they are writen to zephyr/.config, but still not used by west build.

**To Reproduce**
```
west init test2
cd test2`
west update
cd zephyr
zephyr-env.cmd
west build -b nrf52810_pca10040 samples\bluetooth\peripheral
 builds fine
west build -t guiconfig
 select Boot options - MCUBoot support (BOOTLOADER_MCUBOOT)
 save
settins are saved to build\zephyr\.config
west build -b nrf52810_pca10040 samples\bluetooth\peripheral
 still no MCUBOOT support, same parition scheme
I have to manualy modify samples\bluetooth\peripheral\prj.conf and add
CONFIG_BOOTLOADER_MCUBOOT=y

```
then 
west build -b nrf52810_pca10040 samples\bluetooth\peripheral  starts to build with new flash partition schema  (and doesn't finish linking, because for nrf52810 FW partition size if 54kB, but compiled binary takes 140kB - does anybody know how to make it smaller? to remove debug info or something? but this is for anothe thread may be)

**Expected behavior**
changes I make in GUI should be used while building

**Impact**
I have to search config defines and do the editing of prj.conf manuly

**Environment (please complete the following information):**
 - OS: Windows 7 64bit
 - Toolchain Zephyr, Arm toolchain 9-2019-q4
 - Commit SHA or Version used:  aae2c84619585143841c0ceb2552423e7dfbb6a3

### PR DESCRIPTION
**Pull request by ulfalizer**
Fixes: #20673

Main fix:

```
kconfig: Make FLASH_LOAD_OFFSET/SIZE non-configurable when DT is used

Having FLASH_LOAD_OFFSET and FLASH_LOAD_SIZE always configurable froze
their values at 0 when BOOTLOADER_MCUBOOT was enabled in menuconfig,
when instead the values from /chosen/zephyr,code-partition in devicetree
should be used. BOOTLOADER_MCUBOOT selects USE_CODE_PARTITION, which is
a flag to use the devicetree information.

To fix it, only make FLASH_LOAD_OFFSET and FLASH_LOAD_SIZE configurable
when USE_CODE_PARTITION is disabled. It looks like no configuration
files set them at the moment.

See the added documentation in
https://github.com/zephyrproject-rtos/zephyr/pull/20722 for an
explanation of why this happens. This bit novalisek in
https://github.com/zephyrproject-rtos/zephyr/issues/20673.

Fixes: #20673
```

Documentation improvements and cleanups:

```
kconfig: Improve USE_CODE_PARTITION prompt and help string

The prompt and help string for USE_CODE_PARTITION were too terse and
didn't make it clear that it's related to devicetree, which confused me.
Spell things out in more detail.

Unless the meaning of a symbol is completely obvious from context, aim
for at least a few sentences of help text. Think about what would be
confusing for someone coming at it without much context.
```

```
kconfig: Rename USE_CODE_PARTITION to USE_DT_CODE_PARTITION

USE_CODE_PARTITION is a bit vague as a symbol name ("use code partition
how?"). Rename it to USE_DT_CODE_PARTITION to make it clearer that it's
about devicetree.

This would break any third-party configuration files that set it, but
it'll generate an error since kconfig.py promotes warnings to errors, so
it's probably not a big deal.
```

```
kconfig: Factor out HAS_FLASH_LOAD_OFFSET dependency

Use a top-level 'if' instead of three separate 'depends on'. They're
exactly equivalent (top-level 'if's are just a shorthand for adding
'depends on' to each item within the 'if').
```

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]
Look fine.
For future; Would be great if PR description was an abstract instead of commit messages conglomerate :D

**Review by SebastianBoe — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
nice

**Review by mbolivar — APPROVED** [review]
Thanks!

**Comment by novalisek** [comment]
see my comment at https://github.com/zephyrproject-rtos/zephyr/issues/20673#issuecomment-554677434  I think it is not working properly when enabling and disabling mcuboot again

**Comment by ioannisg** [comment]
Anyone outside Nordic would like to review this? @galak @MaureenHelm

**Comment by ulfalizer** [comment]
> see my comment at [#20673 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/20673#issuecomment-554677434) I think it is not working properly when enabling and disabling mcuboot again

Posted a comment there that explains it.

**Comment by sslupsky** [comment]
Hi, I stumbled on this PR and issue #20673 .  I had been struggling to get the code-partition setting in devicetree to actually relocate my code.  I had to manually include 
```
CONFIG_FLASH_BASE_ADDRESS=0x2000
```
in my proj.conf to locate my code past my boot loader (uf2-samd).  Then I found this issue searching "code-partition".  Turns out, adding
```
CONFIG_USE_CODE_PARTITION
```
works.  So I added that to my board's defconfig.

The documentation about code-partition I referred to is here:  https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/guides/dts/flash_partitions.inc.  I think it would be helpful if this page was updated to explain that CONFIG_USE_CODE_PARTITION needs to be set so that the code-partition devicetree setting is used.

**Comment by ioannisg** [comment]
Moving this to 2.2, to get reviews outside nordic

**Review by mnkp — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
