### PR TITLE
Bluetooth: Shell: Set newest conn as default_conn

### PR DESCRIPTION
**Pull request by Thalley**
When dealing with multiple connections in the shell, it is more often than not the newest connection you want to interact with.

### CODE REVIEW

**Review by cvinayak — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Marking this as DNM until approval from @jhedberg and/or @alwa-nordic

**Comment by alwa-nordic** [comment]
Won't this be unexpected if when a device connects to you while you are typing a command?

**Comment by Thalley** [comment]
> Won't this be unexpected if when a device connects to you while you are typing a command?

That is a fair question, and yes! 

I had actually only really considered this from the centrals point of view, where you actively do a `bt connect` command first (or use the FAL), but you are right that from a peripheral point of view, this may be quite disturbing. 

If we do accept this change, we may want to only do that for the central.

**Comment by Thalley** [comment]
@alwa-nordic modified the change to only apply for the central role. Is that OK? 

Alternatively we can add another parameter for the `bt connect` to switch on connection - That would also work for me

**Comment by alwa-nordic** [comment]
> @alwa-nordic modified the change to only apply for the central role. Is that OK?
> 
> Alternatively we can add another parameter for the `bt connect` to switch on connection - That would also work for me

I'm ok with either. :+1:

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
