### PR TITLE
Bluetooth: Host: Disable BLE scan before setting random address

### PR DESCRIPTION
**Pull request by yang325**
According to Bluetooth core specification v5.2, if Host set
random address when any of scanning (passive or active), the
Controller shall return the error code Command Disallowed (0x0C).

### CODE REVIEW

**Review by Thalley — DISMISSED** [review]
I'm not sure that this PR does what you expect it do to, unless I'm misreading the code. 

It basically seems like the only change is that you have removed the check for `BT_DEV_ACTIVE_SCAN`, which sounds like the opposite of what you attempt to do.

**Comment by yang325** [comment]
@Thalley Previous design check BT_DEV_SCANNING and BT_DEV_ACTIVE_SCAN, which means device will disable scanning only when it is active scanning. While no matter it is passive or active, device should disable scanning before setting random address. So I suggest to check BT_DEV_SCANNING only.

**Comment by jhedberg** [comment]
I remember having conversations about this in the past. One area which doing such a change will impact negatively is Mesh since there you want to maximise the continuous (passive) scanning duty cycle, whereas every Mesh message you send requires a adv_start() + adv_stop().

**Comment by yang325** [comment]
@jhedberg Could you please share more about that conversion?
I tested the mesh demo on POSIX board (Intel NUC + Linux) but it run into a problem. The Controller return the error code Command Disallowed (0x0C). So I made this commit.

**Comment by Thalley** [comment]
> @Thalley Previous design check BT_DEV_SCANNING and BT_DEV_ACTIVE_SCAN, which means device will disable scanning only when it is active scanning. While no matter it is passive or active, device should disable scanning before setting random address. So I suggest to check BT_DEV_SCANNING only.

@yang325 You are correct, I had somehow confused `BT_DEV_ACTIVE_SCAN` with `BT_DEV_EXPLICIT_SCAN`.

**Comment by Thalley** [comment]
> I remember having conversations about this in the past. One area which doing such a change will impact negatively is Mesh since there you want to maximise the continuous (passive) scanning duty cycle, whereas every Mesh message you send requires a adv_start() + adv_stop().

Is it correctly understood, we change the random address for each mesh adv, and thus every time we need to send anything, we also need to restart scan? If that is the case, then I see the problem. This can of course be easily solved when we start using the extended advertising API for mesh, as there is a way to set only the advertising random address for a set. 
However, the controller shall return an error if we attempt to change the address, so either we A) don't change the address, or B) restart scan when we want to change the address, which shouldn't be that often, and shouldn't effect Mesh significantly. 

@jhedberg I did a quick search in the Mesh Profile spec, and I can't find the paragraph that states that Mesh should (shall?) change the address between each advertising. Can you point me to it?

**Comment by jhedberg** [comment]
@Thalley I'm not sure if this (using unique random address for each message) is actually mandated by the spec, but it's (AFAIK) what most Mesh implementations do. Anything else would unnecessarily leak information about the network (topology, number of nodes, etc) to a passive observer. It's possible that this is less of an issue now that we can use extended advertising HCI commands instead of the legacy ones - hopefully @trond-snekvik can comment on that.

**Comment by Thalley** [comment]
> @Thalley I'm not sure if this (using unique random address for each message) is actually mandated by the spec, but it's (AFAIK) what most Mesh implementations do. Anything else would unnecessarily leak information about the network (topology, number of nodes, etc) to a passive observer. It's possible that this is less of an issue now that we can use extended advertising HCI commands instead of the legacy ones - hopefully @trond-snekvik can comment on that.

I'm thinking that if we indeed change the address between each adv event, then we need to stop scan anyhow, otherwise the controller would (shall) not accept the command:
> If the Host issues this command when any of advertising (created using legacy advertising commands), scanning, or initiating are enabled, the Controller shall return the error code Command Disallowed (0x0C).

So I think that this host change just makes sure that the host conforms to the spec, and doesn't do anything but actually disabling scan rather than receiving an error on the address change. There is no way that Mesh, with legacy adv API, can change address while scanning, unless our controller is acting incorrect. Based on that, I think this PR makes sense, and if our Mesh implementation wants to change address between each adv, then it shall either take the scan performance hit, or use the extended advertising API.

**Review by Thalley — APPROVED** [review]

**Comment by trond-snekvik** [comment]
The unique random address is not part of the mesh spec, so we can technically force usage of the ext adv API instead if we need privacy. This appears to be more than just a performance issue for the mesh, as the babblesim tests are failing. 

The failing tests are the ones that manually start and stop the scanner to save power. AFAICT, this can't work properly for the mesh now, and needs a closer look in hci_core, as that is trying to start and stop the scanner correctly in these scenarios

**Comment by yang325** [comment]
@trond-snekvik What's your suggestion on code change?

**Comment by trond-snekvik** [comment]
I think @joerchan or @jhedberg may have suggestions for this, I'm not that experienced with hci_core

**Comment by yang325** [comment]
@joerchan @jhedberg Could you please share your suggestions?
I verified this commit on zephyr/samples/bluetooth/mesh and no issue reported. There might be some performance issue but I think this thing must be done.

**Comment by jhedberg** [comment]
If AE is the default for Mesh now days (is it?), then I guess this is alright. @yang325 please fix the Compliance check issue. I think the Coding Guidelines failure should go away once you rebase and and push again.

**Review by trond-snekvik — APPROVED** [review]
Approving with a mesh point of view. @cvinayak: you or someone else with a good grip on the hci_core/controller might want to try running this with a logic analyzer to check that this doesn't trip up the controller though. The passive scanner timing changed more than I would expect for the mesh test

**Comment by jhedberg** [comment]
@yang325 Compliance check is still failing since you're missing a Signed-off-by line in your commit (you can add that automatically using `git commit -s --amend`)

**Comment by yang325** [comment]
@jhedberg  I have updated commits. It seems that still need your approval.

**Comment by yang325** [comment]
What else should I do to merge commits?

**Review by jhedberg — APPROVED** [review]

**Review by joerchan — APPROVED** [review]
This looks OK to me.

@cvinayak and @rugeGerritsen The controller should behave the same way, as defined by the spec.

**Comment by cvinayak** [comment]
> The controller should behave the same way, as defined by the spec.

The change is to compare with 0x7 to restrict setting the address, here: https://github.com/zephyrproject-rtos/zephyr/blob/e5f21a7234d76078002c04a51afbaf6016b01a95/subsys/bluetooth/controller/ll_sw/ll_addr.c#L70

@joerchan Should I append a commit to this PR?

**Comment by joerchan** [comment]
> Should I append a commit to this PR?

I think another one would be better. They don't have to go in together.

**Pull request merged**
