### PR TITLE
samples: bluetooth: hci_usb: add missing Kconfig setting

### PR DESCRIPTION
**Pull request by pabigot**
Without CONFIG_BT_CTLR=y the application attempts to reference the
undefined function bt_hci_cmd_complete_create.

Signed-off-by: Peter A. Bigot <pab@pabigot.com>

### CODE REVIEW

**Review by joerchan — APPROVED** [review]
Which board did this happen on?

Most boards have this in the defconfig file:
```
config BT_CTLR
	default BT
```

**Comment by pabigot** [comment]
> Which board did this happen on?

An out of tree board where I've chosen not to add this default to the `defconfig`.

It doesn't really *have* to be fixed in the sample, but IMO it's better if sample configurations accurately reflect the required configuration options.  Especially when they're a thin wrapper around core capabilities.

**Comment by joerchan** [comment]
> > Which board did this happen on?
> 
> An out of tree board where I've chosen not to add this default to the `defconfig`.
> 
> It doesn't really _have_ to be fixed in the sample, but IMO it's better if sample configurations accurately reflect the required configuration options. Especially when they're a thin wrapper around core capabilities.

It doesn't hurt. But maybe it would make sense to align the other HCI samples? They don't have this kconfig either.

**Comment by pabigot** [comment]
> It doesn't hurt. But maybe it would make sense to align the other HCI samples? They don't have this kconfig either.

This was me as an individual, not a Nordic contractor.  I can go through all the examples and clean them up but it's not something I'll spend personal time on.

**Comment by jhedberg** [comment]
> It doesn't really have to be fixed in the sample, but IMO it's better if sample configurations accurately reflect the required configuration options

It's *not* a required configuration option though. It should be perfectly possible to use hci_usb (or hci_uart or any other similar app) on top of a second physical HCI transport rather than the native controller. You might e.g. have a controller connected through UART but want to expose it to another host using USB (I know - not a super realistic end-product use-case but something completely possible with Zephyr's Bluetooth stack)

**Review by jhedberg — CHANGES_REQUESTED** [review]
I only now read the PR description:

> Without CONFIG_BT_CTLR=y the application attempts to reference the
undefined function bt_hci_cmd_complete_create.

That's a bug  elsewhere though, and should be fixed through some other means than this prj.conf change.

**Comment by jhedberg** [comment]
Looking at this closer, it seems like the native controller is the only HCI driver that implements `bt_hci_cmd_complete_create()` although it's called from places (like `hci_raw.c`) that should be completely agnostic to the chosen HCI driver. *That's* what should be fixed instead of working around it like this.

**Comment by pabigot** [comment]
Fine with me; opened  #27118 to record this analysis.

**Pull request closed without merging**
