### PR TITLE
[Backport v1.14-branch] Bluetooth: Fix GAP/IDLE/NAMP/BV-01-C

### LINKED ISSUE #17092: Bluetooth: GAP/IDLE/NAMP/BV-01-C requires Read by UUID
GAP/IDLE/NAMP/BV-01-C:

Verify the IUT can perform the Name Discovery Procedure and retrieve the device name from a peer device.

In order to pass this test PTS expects Read by UUID to be used.

### PR DESCRIPTION
**Pull request by Vudentz**
This backports the necessary changes in order to pass the qualification test  GAP/IDLE/NAMP/BV-01-C.

Fixes #17092

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Comment by Vudentz** [comment]
@tedd-an please rerun autopts with these set just to confirm all the changes are in place.

**Comment by tedd-an** [comment]
> @tedd-an please rerun autopts with these set just to confirm all the changes are in place.
@Vudentz It looks like f6665c812 is also required to prevent the read_by_uuid from going into an infinite loop.
I tested this PR + f6665c812 and it passed the test.
```
f3dbfef2df (HEAD -> pr_17094) Bluetooth: gatt: Fix infinite read_by_uuid procedure
a64de56035 tests: bluetooth/tester: Add support Read Using Characteristic UUID
3ed44321a5 Bluetooth: GATT: Fix not parsing result of Read by Type
64da988b0c Bluetooth: GATT: Add support for Read Using Characteristic UUID
```
```
1/1   GAP   GAP/IDLE/NAMP/BV-01-C   PASS            26.052    
```

Also, do we need 52d2a08?

**Comment by Vudentz** [comment]
> > @tedd-an please rerun autopts with these set just to confirm all the changes are in place.
> 
> @Vudentz It looks like [f6665c8](https://github.com/zephyrproject-rtos/zephyr/commit/f6665c812ef4e24e0aa318b81f67ba05b1847531) is also required to prevent the read_by_uuid from going into an infinite loop.
> I tested this PR + [f6665c8](https://github.com/zephyrproject-rtos/zephyr/commit/f6665c812ef4e24e0aa318b81f67ba05b1847531) and it passed the test.
> 
> ```
> f3dbfef2df (HEAD -> pr_17094) Bluetooth: gatt: Fix infinite read_by_uuid procedure
> a64de56035 tests: bluetooth/tester: Add support Read Using Characteristic UUID
> 3ed44321a5 Bluetooth: GATT: Fix not parsing result of Read by Type
> 64da988b0c Bluetooth: GATT: Add support for Read Using Characteristic UUID
> ```
> 
> ```
> 1/1   GAP   GAP/IDLE/NAMP/BV-01-C   PASS            26.052    
> ```

Ive added that patch as well.

> Also, don't we need [52d2a08](https://github.com/zephyrproject-rtos/zephyr/commit/52d2a0862a64e4475bba039a1ba4b87e7c175e83)?

I guess it is best just to backport what is strictly necessary to minimize potential regressions on the shell.

**Comment by tedd-an** [comment]
@Vudentz I reran new PR and it passed. 
```
1/1   GAP   GAP/IDLE/NAMP/BV-01-C   PASS            24.905  
```

**Review by tedd-an — APPROVED** [review]

**Pull request merged**
