### PR TITLE
qemu_x86: restore previous flash size, increase RAM

### LINKED ISSUE #15831: qemu_x86 DTS does not reflect actual emulated hardware layout
The QEMU x86 emulator has 8MB reserved on its command line.
In our QEMU DTS, this was cut in half; the first 4MB (minus the zero page) was reserved for a simulated XIP ROM area. The second 4MB is read-write system RAM.

When the flash simulator driver was introduced, the ROM area was reduced to 1MB. This breaks a bunch of tests when CONFIG_COVERAGE=y as they require more than 1MB.

We should not have done this. DTS is supposed to reflect the ACTUAL hardware configuration. If we have a software constructed fake driver, its characteristics should be in Kconfig, not by hacking the DTS files.

At this time I am unable to raise the ROM size back where it was. I tried to de-couple the simulated flash characteristics from DTS but there are overlays and flash partition layouts depending on it by other tests. The closest I got was #15828 

**Please put the qemu_x86 flash size back to its original value of 4092K**

### PR DESCRIPTION
**Pull request by nvlsianpu**
Propose for fix https://github.com/zephyrproject-rtos/zephyr/issues/15831

### CODE REVIEW

**Review by kapi-no — APPROVED** [review]
LGTM.

Please make sure that all DT partitions are still in the range of flash simulator memory (after your modification).

**Comment by nvlsianpu** [comment]
> Please make sure that all DT partitions are still in the range of flash simulator memory (after your modification).

I kept simulated flash size at the same level.

**Review by carlescufi — APPROVED** [review]
This is the simplest way to fix this

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by marc-hb** [comment]
This broke my `export QEMU_EXTRA_FLAGS="-bios $HOME/OVMF_CODE-32.fd"` workaround for issues(s) #11717 :-(
Now 72/73 tests time out: 
```
./scripts/sanitycheck  -p qemu_x86   -T tests/kernel/ -v
...
71/73 qemu_x86                  tests/kernel/common/kernel.common                  FAILED: timeout (qemu)
	see: sanity-out/qemu_x86/tests/kernel/common/kernel.common/handler.log
72/73 qemu_x86                  tests/kernel/threads/thread_apis/kernel.threads    FAILED: timeout (qemu)
	see: sanity-out/qemu_x86/tests/kernel/threads/thread_apis/kernel.threads/handler.log
1 of 73 tests passed with 0 warnings in 75 seconds
```
`handler.log` files are empty, qemu is just stuck with no error message.

Any qemu expert having any idea why?

**Comment by andrewboie** [comment]
This patch doesn't seem to work, I still see only 1MB of ROM available

**Comment by marc-hb** [comment]
FWIW reverting just this small patch on top of c7c02fce3e082 `CommitDate: Fri May 31 16:04:43 2019 -0400` is enough to fix the OVMF + sanitycheck command above.
Just FYI, see #11717 for more details.

**Comment by nvlsianpu** [comment]
```
- zephyr,flash = &flash0;
+ zephyr,flash = &flash_sim0;
```

Without this scripts don't generate partition info form flash simulator dts.

**Comment by marc-hb** [comment]
@nvlsianpu I'm not sure I'm parsing your sentence correctly: is this one-line change an alternative to get back to the original, pre-simulator configuration and sizes?

**Comment by nvlsianpu** [comment]
@marc-hb Yesterday I tried to revert flash-simulartor related change (in DTS). Build was failing anyway.
```
 west build -d helow --board qemu_x86 zephyr/samples/hello_world/
source directory: /home/anpu/codedev/zephyrproject/zephyr/samples/hello_world
build directory: /home/anpu/codedev/zephyrproject/helow (created)
BOARD: qemu_x86 (origin: command line)
Zephyr version: 1.14.99
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.7", minimum required is "3.4") 
-- Selected BOARD qemu_x86
-- Found west: /home/anpu/.local/bin/west (found suitable version "0.5.7", minimum required is "0.5.6")
-- Loading /home/anpu/codedev/zephyrproject/zephyr/boards/x86/qemu_x86/qemu_x86.dts as base
-- Overlaying /home/anpu/codedev/zephyrproject/zephyr/dts/common/common.dts
Parsing Kconfig tree in /home/anpu/codedev/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/anpu/codedev/zephyrproject/zephyr/boards/x86/qemu_x86/qemu_x86_defconfig'
Merged configuration '/home/anpu/codedev/zephyrproject/zephyr/samples/hello_world/prj.conf'
Configuration saved to '/home/anpu/codedev/zephyrproject/helow/zephyr/.config'
-- Cache files will be written to: /home/anpu/.cache/zephyr
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/zephyr-sdk-0.10.0/i586-zephyr-elf/bin/i586-zephyr-elf-gcc
-- Performing Test toolchain_is_ok
-- Performing Test toolchain_is_ok - Success
Including module: tinycbor in path: /home/anpu/codedev/zephyrproject/modules/lib/tinycbor
Including module: qmsi in path: /home/anpu/codedev/zephyrproject/modules/hal/qmsi
Including module: esp-idf in path: /home/anpu/codedev/zephyrproject/modules/hal/esp-idf/zephyr
Including module: fatfs in path: /home/anpu/codedev/zephyrproject/modules/fs/fatfs
Including module: mcumgr in path: /home/anpu/codedev/zephyrproject/modules/lib/mcumgr
Including module: nffs in path: /home/anpu/codedev/zephyrproject/modules/fs/nffs
Including module: segger in path: /home/anpu/codedev/zephyrproject/modules/debug/segger
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anpu/codedev/zephyrproject/helow
[1/98] Preparing syscall dependency handling

[89/98] Linking C executable zephyr/zephyr_prebuilt.elf
Memory region         Used Size  Region Size  %age Used
             ROM:       19728 B         4 MB      0.47%
             RAM:          8 KB         4 MB      0.20%
        IDT_LIST:         416 B         2 KB     20.31%
        MMU_LIST:         104 B         1 KB     10.16%
[95/98] Generating mmu_tables.bin
FAILED: zephyr/arch/arch/x86/mmu_tables.bin 
cd /home/anpu/codedev/zephyrproject/helow/zephyr/arch/arch/x86 && /usr/bin/python3 /home/anpu/codedev/zephyrproject/zephyr/arch/x86/gen_mmu_x86.py -k /home/anpu/codedev/zephyrproject/helow/zephyr/zephyr_prebuilt.elf -o mmu_tables.bin -u user_mmu_tables.bin
Memory region 1 (4000:401000) overlaps memory region 0 (400000:800000)
ninja: build stopped: subcommand failed.
ERROR: command exited with status 1: /home/anpu/cmake/cmake-3.13.1-Linux-x86_64/bin/cmake --build /home/anpu/codedev/zephyrproject/helow
run as "west -v build -d helow --board qemu_x86 zephyr/samples/hello_world/" for a stack trace
```

What i mean is that flash size for `text`  is determined by what is chosen by `zephyr,flash`. We can chose only one zephyr,flash - and for this DTS node partitions description are generated. What is needed here is to rework scripts in such a way that DT_xxx information will be generated for flash-simualtor, and `flash0` will be chosen.

**Pull request merged**
