### PR TITLE
drivers: modem: adding power control support for offload modem

### PR DESCRIPTION
**Pull request by mtahirbutt**
Signed-off-by: Tahir Akram <mtahirbutt@hotmail.com>

This PR addresses the support for power control for offload modem.
The way to power off and on modem is left for users of this drivers.
The driver has been tested with echo_client app with SARA U201 modem.

### CODE REVIEW

**Comment by mike-scott** [comment]
@mtahirbutt You have a sample that makes use of the `restart_modem_offload` function?

I think this might work better as an offload API addition of some sort.  I feel like there might be other devices which need a function to "restart" devices that can be turned off temporarily.  If this is really only applicable to modems, then perhaps we can establish a public API function for this behavior somewhere here:
https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/modem/modem_context.h

@jukkar thoughts?  I'm not a fan of 1-off functions like this that are in a hidden include file.

**Comment by jukkar** [comment]
>  If this is really only applicable to modems, then perhaps we can establish a public API function for this behavior

Fully agree with you here. Currently the PM functionality is in flux / not ready yet so it is difficult to exactly say what this API would need to look like, but regardless of that there is a need to manage the power usage of all the modems, not just the SARA one.

**Comment by mtahirbutt** [comment]
> @mtahirbutt You have a sample that makes use of the `restart_modem_offload` function?
> 
> I think this might work better as an offload API addition of some sort. I feel like there might be other devices which need a function to "restart" devices that can be turned off temporarily. If this is really only applicable to modems, then perhaps we can establish a public API function for this behavior somewhere here:
> https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/modem/modem_context.h
> 
> @jukkar thoughts? I'm not a fan of 1-off functions like this that are in a hidden include file.

@mike-scott, I use net_if_up() and net_if_down() in combination with restart_modem_offload in the main application. As when I switch off the modem, it is not ready to accept socket connection. so thats why I introduced restart_modem_offload function. I did not touch anything else yet. I also introduced similar functionality for PPP with #27731.

**Comment by mike-scott** [comment]
Apologies for not managing this PR very well.  I maintain my portions of Zephyr completely on my own time these days and I've been swamped with normal work.

I'm sort of torn on this PR.

I really would like to see a better solution, but I understand the need for a stopgap solution.

@jukkar I haven't been to many of the planning meetings lately, but how far out are power management APIs?  Or really anything that someone could build on to manage modem power usage?

**Comment by jukkar** [comment]
> I haven't been to many of the planning meetings lately, but how far out are power management APIs?

The PM APIs are probably mostly ok, it is just that the infrastructure around is not ready yet. So if one turns off some low level device, the other devices using that service should be turned off too automatically, currently this is not yet working.

There is also #28475 and competing #27731 that are related to modem PM.

**Comment by jukkar** [comment]
I added modem power management topic to tomorrows network forum agenda. We can discuss more there if @endian-benjamin, @mtahirbutt and @mike-scott are able to join. See mail https://lists.zephyrproject.org/g/devel/message/7363 for links.

**Comment by mike-scott** [comment]
> I added modem power management topic to tomorrows network forum agenda. We can discuss more there if @endian-benjamin, @mtahirbutt and @mike-scott are able to join. See mail https://lists.zephyrproject.org/g/devel/message/7363 for links.

I'm sorry Jakkar, it's going to be a late night at work for me.  I can't make tomorrow morning.  Please pass along any discussion.  Thanks.

**Comment by endian-benjamin** [comment]
Not clear why we need this in the case of offloading, why isn't `net_if_down/net_if_up` sufficient?

**Comment by mtahirbutt** [comment]
> 
> 
> Not clear why we need this in the case of offloading, why isn't `net_if_down/net_if_up` sufficient?

having a one api function for start/stop will make easier for use in any app usage of the modem?

**Pull request closed without merging**
