### PR TITLE
drivers/sensor: Add navigational (GPS/GNSS) channels to API

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
Global positioning sensors are currently not
supported by the sensor API. This addition will
add support for the basic positioning data, using
units which are intuitive and easy to work with.

**The added channels are described here:**

Latitude and longitude. These channels must be
in decimal degrees. A decimal degree is floating
point representation of an angle from 0 to +-180
degrees. These angles can be directly converted
to doubles when computing distances for
example.

Speed over ground in meters pr second,

Altitude in meters above sea level.

Tracking angle in in decimal degrees from 0 to
360, relative to True North (Above earths
rotational axis)

Dilution of precision for position, it can be
determined from HDOP, VDOP, GDOP, PDOP etc.

**How to use the sensor API:**

To check if the sensor has a fix, indicating
that its positional data is valid, the
sensor_sample_fetch() function is used. If the
data is valid, the latest positional data is
updated and 0 is returned. If data is not
valid, an error is returned.

After fetching a sample, the
sensor_channel_get() function is used as usual.

To set the update rate of the positional
sensor, the attribute
SENSOR_ATTR_SAMPLING_FREQUENCY is used. This
allows for power saving by using features like
periodic scanning if a low update rate is
sufficient.

**In defence of the specified units:**

The units used should be SI units, that are
represent-able by a double (signed decimal
number), which in turn can be represented by a
sensor_value struct.

The sensor driver must read, parse, validate
and convert the navigational data to the units
described above.

The application is then tasked with converting
these units to whatever format it needs.

Signed-off-by: Bjarki AA <baa@trackunit.com>

### CODE REVIEW

**Comment by ycsin** [comment]
fyi #30564

**Comment by bjarki-trackunit** [comment]
> fyi #30564. I think a generic gnss APIs would likely need to be decided first before drivers like #46447 can be implemented

I will argue that the sensor API is that generic API, Looking at #46447 the API contains fetch, set (attr) and a bunch of getters (channels) https://github.com/zephyrproject-rtos/zephyr/pull/46447/files#diff-692be7bb6366413fb56f89a7c18f1dbba2cd06195a4fce47a54d739a4972b9ac which the sensor API is built for. The #30564 is a near copy of the sensor API, but prefixed with gnss, and with IMO to many parameters exposed to the application, that are not proven to be essential.

I believe that we should slowly add the channels and parameters that are actually useful to the sensor API over time as they are found to be useful, starting with the bare minimum channels added in this pull request.

The #46447 driver API could be rewritten to use the SENSOR API with the proposed changes, missing the TIME and SATELITES channels. I would argue that SATELITES is a less useful parameter to determine signal quality than HDOP, and TIME should use a more appropriate API to simply inform the system of the current time.

**Comment by ycsin** [comment]
> The #46447 driver API could be rewritten to use the SENSOR API with the proposed changes

You might want to have a look at #10376 as well, if you haven't already

**Comment by bjarki-trackunit** [comment]
Regarding #10376, the GNSS/GPS receiver could register itself to the network using socket offloading, using the address family AF_LOCAL (or we could add an AF_NMEA family), and simply send the raw frames as packets. I don't think this is a good idea however for the reasons that follow:

Not all GNSS/GPS sensors use the same data format, like NMEA, and sensors can have some quirks that the application should not have be aware of and forced to handle. However, all GNSS/GPS sensors provide at minimum the same basic data in the end, which is what is reflected in channels added by this pull request.

GNSS/GPS sensors are changing with time, no application should be tied to some specific protocol, like NMEA or indeed any location provider for that matter, like WIFI location, Cellular triangulation, etc. In the end, they provide the same positional data, speed, altitude, longitude and latitude along with some certainty (precision) variable for the provided location data (fx HDOP, maybe it should be changed to be in +- meters or some more general unit if possible).

The GNSS/GPS driver should be tasked with reading whatever data in whatever format it receives, and present it in a usable, unhanging and simple format (like latitude in degrees, not a device specific string format like ddmm.mmmm). The GNSS/GPS driver naturally validates the data before presenting it to the application as valid data.

For special cases where more data is required, there is the possibility of adding driver specific channels and attributes, but for the basic location data, it should just be available. If we look at the Android SDK for example, all you get is a location heading and altitude, there is no NMEA frames, no device specific parameters, it is simply handled in their drivers (and a little bit in global settings, like enable, precision etc, which could be in a Kconfig or dts). We should look to simple APIs like theirs for inspiration.

**Comment by bjarki-trackunit** [comment]
Changed DOP channel to accuracy radius in meters. It will be up to the implementer of the driver to determine the accuracy of the sensor compared to whichever accuracy/certainty metrics the sensor provides, like HDOP, and convert this to a radius in meters, within which the sensor is located within with a 68% certainty.

**Comment by ycsin** [comment]
I see this as a quick and easy way of getting something done, tbh personally I too prefer an API dedicated for GNSS. GNSS drivers can live in its own folder (`drivers/gnss`) where typical NMEA gnss drivers and common libs such as NMEA parser are stored, similar to how the modem drivers work. Other things such as existing modem driver can opt to implement the gnss device driver partially to provide a simple lat/lon, over cellular triangulation for example.

**Comment by bjarki-trackunit** [comment]
The GNSS sensor/modem (L76LL) I am implementing is part of the modem library, as it uses the command handler and iface modules, GNSS sensors using AT commands for setup and NMEA frames for data should go there, but that is for another discussion.

This solution solves the issues with getting location data, at the cost of having less user configurability from the application side, this solution i find is the best, since we have Kconfig and dts to fine tune the driver configuration.

There are two other solutions to a generic location API:

The first one I find unnecessary. This is creating a new API for positional data alone, which moves the "channels" out from the sensor API, and into named functions, like location_get_latitude(), no added functionality from what would be achieved using the already existing API, but tidier.

The second is more flexible. Create a GNSS API only for GNSS sensors, not cellular triangulation or other methods of determining location. In here, tracking modes, number of satelites, the raw HDOP values could be retrieved. I still feel this is an abundance of configurations available to the application during runtime, but if it really is needed, this is where the many configurations and raw values can be found. Then, create a new subsystem, **location**. Here, all sensors which can provide a location implement a location API, like an offloaded socket would, then, when the application requests a location, the **Location** subsystem goes through all providers, uses the get_accuracy function to determine the best provider, and returns this. I will start on this solution now, so can review and compare the solutions tomorrow :)

**Comment by sslupsky** [comment]
> The #30564 is a near copy of the sensor API, but prefixed with gnss, and with IMO to many parameters exposed to the application, that are not proven to be essential.

What do you mean by too many parameters exposes to the application?  I wrote the original RFC but didn't not see any comments from you on that proposal?

**Comment by bjarki-trackunit** [comment]
> > The #30564 is a near copy of the sensor API, but prefixed with gnss, and with IMO to many parameters exposed to the application, that are not proven to be essential.
> 
> What do you mean by too many parameters exposed to the application? I wrote the original RFC but did not see any feedback from you on that proposal before this PR?

We have not commented on the  #30564 before this pull request since we find it more efficient to show some comparative work to discuss from. In any case, later today there will be a pull request for a location subsystem/api that we will continue from, at which point this pull request will be closed.

**Comment by bjarki-trackunit** [comment]
The new proposal for location data has now been proposed here #46660, with this, this pull request is closed be prejudice :D

**Pull request closed without merging**
