### PR TITLE
tests drivers Uart async on stm32 boards requires dma channels config.

### PR DESCRIPTION
**Pull request by FRASTM**
This defines an overlay for the dma channels when executing the `tests/drivers/uart/uart_async_api` on stm32 nucleo boards:
- disco_l475_iot1
through overlay for this tests.

The DMA must be configured for the UART when asynch api is defined.

  on disco_l475_iot1: UART 4 is used for testing : DMA 2 channel 3 & 5 and request 2 is selected (uart4 is already selected for this board)

UART Tx pin must be connected to UART Rx pin on the board.
It also helps when running the test on _other_ stm32 boards or running other test (ex. tests/drivers/spi/spi_loopback) with dma on those boards.

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
```
*** Booting Zephyr OS build zephyr-v2.5.0-368-g16677de24c1c  ***                
Running test suite uart_async_test                                              
===================================================================             
START - test_single_read_setup                                                  
 PASS - test_single_read_setup                                                  
===================================================================             
START - test_single_read                                                        
 PASS - test_single_read                                                        
===================================================================             
START - test_chained_read_setup                                                 
 PASS - test_chained_read_setup                                                 
===================================================================             
START - test_chained_read                                                       
 PASS - test_chained_read                                                       
===================================================================             
START - test_double_buffer_setup                                                
 PASS - test_double_buffer_setup                                                
===================================================================             
START - test_double_buffer                                                      
 PASS - test_double_buffer                                                      
===================================================================             
START - test_read_abort_setup                                                   
 PASS - test_read_abort_setup                                                   
===================================================================             
START - test_read_abort                                                         
 PASS - test_read_abort                                                         
===================================================================             
START - test_chained_write_setup                                                
 PASS - test_chained_write_setup                                                
===================================================================             
START - test_chained_write                                                      
 PASS - test_chained_write                                                      
===================================================================             
START - test_long_buffers_setup                                                 
 PASS - test_long_buffers_setup                                                 
===================================================================             
START - test_long_buffers                                                       
 PASS - test_long_buffers                                                       
===================================================================             
START - test_write_abort_setup                                                  
 PASS - test_write_abort_setup                                                  
===================================================================             
START - test_write_abort                                                        
 PASS - test_write_abort                                                        
===================================================================             
START - test_forever_timeout_setup                                              
 PASS - test_forever_timeout_setup                                              
===================================================================             
START - test_forever_timeout                                                    
 PASS - test_forever_timeout                                                    
===================================================================             
Test suite uart_async_test succeeded                                            
===================================================================             
PROJECT EXECUTION SUCCESSFUL   
```

**Review by dcpleung — APPROVED** [review]

**Comment by FRASTM** [comment]
rebase
enable dma2 and usart6 in the board overlay dts

**Review by Mierunski — APPROVED** [review]

**Comment by FRASTM** [comment]
adding a **temporary** patch to avoid using the cache of the stm32f7 when running the tests uart_async_api ( #31711)

**Comment by FRASTM** [comment]
give the commit for the **disco_l475_iot1** only

**Review by erwango — APPROVED** [review]

**Pull request merged**
