### PR TITLE
driver: regulator: npm1300: fix build warning

### PR DESCRIPTION
**Pull request by maxd-nordic**
Initialize prev. uninitialized variable in regulator_npm1300_init().

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]
Variable is initialized, compiler likely not smart enough.

**Review by danieldegrasse — APPROVED** [review]

**Comment by gmarull** [comment]
> > Variable is initialized, compiler likely not smart enough.
> 
> Well, the error is checked as follows:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/b46ca11c4c255a8823705bdfda156edb63ac6158/drivers/regulator/regulator_npm1300.c#L591-L593
> 
> but `get_enabled_reg()` contains:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/b46ca11c4c255a8823705bdfda156edb63ac6158/drivers/regulator/regulator_npm1300.c#L534-L540
> 
> so if `mfd_npm1300_reg_read()` returned a value > 0, `enabled` would end up uninitialized. For consistency, it would be better to change the latter check to `ret < 0`.

indeed, great explanation :-)

**Comment by nordic-auko** [comment]
Created a new PR by request of @maxd-nordic with the suggested fix:
https://github.com/zephyrproject-rtos/zephyr/pull/80276

**Comment by gmarull** [comment]
alt https://github.com/zephyrproject-rtos/zephyr/pull/80276

**Pull request closed without merging**
