### PR TITLE
drivers: dai: intel: ssp: Only setup mclk/bclk when it is needed by role

### PR DESCRIPTION
**Pull request by ujfalusi**
When SSP is consumer for FS and BCLK then it does not needs MCLK as the shifting and rate is derived form the I2S bus directly. When SSP provides FS only then the BCLK setup is not needed. When SSP provides BCLK only then both MCLK and BCLK setup is needed.

In hardware multiple SSPs share the same MCLK source, in case of one SSP port is used as clock provider while other is used as clock consumer then the consumer SSP should not need to depend on the provider SSP configuration, the ports can run in different clock rates.

In this example the consumer SSP should not try to configure and lock the MCLK frequency to some arbitrary rate (as it does not need MCLK at all) which might be different than the frequency needed by the provider port.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@kv2019i can you take a look please?

**Review by kv2019i — DISMISSED** [review]

**Review by nashif — DISMISSED** [review]

**Review by jxstelter — DISMISSED** [review]

**Review by dnikodem — DISMISSED** [review]

**Comment by kv2019i** [comment]
Reviews are now fine. This is now pending the two required CI checks @ujfalusi  . @nashif please comment if this is wrong.

**Comment by ujfalusi** [comment]
Changes since v1:
- Rebased on main

**Comment by aescolar** [comment]
@ujfalusi needs rebase

**Comment by ujfalusi** [comment]
Changes since v2:
- rebased on main

**Review by dnikodem — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Pull request merged**
