### PR TITLE
doc/zio: Documentation for zio

### PR DESCRIPTION
**Pull request by microbuilder**
This commit pulls in the doxygen documentation for zio
and fixes some formatting issues for a monospaced text
block.

This resolves some unfinished change requests from #14008 
by @dbkinder, since that PR has already been merged into
topic-sensors.

Signed-off-by: Kevin Townsend <kevin@ktownsend.com>

### CODE REVIEW

**Comment by dbkinder** [comment]
To fix the doc build errors,  

* add a mention of the zio/index.rst to doc/reference/index.rst to get ZIO
  included in the API documentation TOC
* I don't see /doc/samples/zio/synth/README.rst in your PR, but I see that
  file if I pull your PR locally.  The doc build is complaining because
  the doc label in this README.rst is the same as another document, so 
  it should be changed to something like ``.. _synth_monitor:`` instead of
  ``.. _lsm6dsl:``

**Review by dbkinder — CHANGES_REQUESTED** [review]
While only two files are part of this PR, the doc build warnings are because of problems in other files that are not part of this PR?  (The two files in this PR look OK.  Maybe a rebase is needed?)

**Comment by mbolivar** [comment]
Does this need a rebase? Lots of unrelated patches; I'm not sure what to look at.

**Comment by microbuilder** [comment]
> Does this need a rebase? Lots of unrelated patches; I'm not sure what to look at.

Eek yeah just fixing it now :P

**Comment by jukkar** [comment]
Very rarely one needs to close a PR, usually it is enough to force push new content into existing PR. If you close the PR, all the comments etc discussion are "lost". Fortunately there was not any in this PR.

**Comment by microbuilder** [comment]
@jukkar This work was moved into another PR where it was more appropriate and more likely to stay in sync with changes to the new sensor API: https://github.com/zephyrproject-rtos/zephyr/pull/16266 ... apologies for the spam, however, due to the PR being based against a newer fork. 🤦‍♂

**Comment by jukkar** [comment]
@microbuilder no worries. I am just seeing people close PRs if there is some minor technical glitch somewhere, wondered if that was the case here too.

**Pull request closed without merging**
