### PR TITLE
nxp: boards: Add device specific pinctrl data to boards

### PR DESCRIPTION
**Pull request by galak**
Add pinctrl-0 nodes to various nxp boards.  The set of boards selected here is based on which boards utilize the `nxp,kinetis-uart`

### CODE REVIEW

**Comment by galak** [comment]
@Kludentwo & @henrikbrixandersen would appreciate any help in convert the other kinetis boards similar to what I've done here.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
> @Kludentwo & @henrikbrixandersen would appreciate any help in convert the other kinetis boards similar to what I've done here.

I'll start working on this tomorrow.

**Comment by galak** [comment]
> I'll start working on this tomorrow.

Thanks, I've got issue #34145 to track the progress.

**Review by MaureenHelm — APPROVED** [review]

**Comment by galak** [comment]
Build issue is unrelated.

**Pull request merged**
