### PR TITLE
drivers: usb: add support for USB OTG FS on STM32F7

### PR DESCRIPTION
**Pull request by aurel32**
The STM32F7 uses the same USB OTG FS controller than the STM32F4 series.
It is therefore trivial to add support for it, by adding the DT fixup
and pinmux macros, and the DT entries in stm32f7.dtsi. Keep it disabled,
it should be enabled at the board level.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Have you been able to test?
Then, please update help section of `USB_DC_STM32` flag.
Thanks

**Review by ydamigos — CHANGES_REQUESTED** [review]
Looks good but, as @erwango asked, did you test it on a board (e.g. STM32F723E-DISCO)?

**Comment by aurel32** [comment]
Thanks @erwango and @ydamigos for the review, I have just updated the commit with the requested changes. I have tested those changes with the `cdc_acm` and `hid` samples on an STM32F723E-DISCO board. I have also been using those changes for a few weeks on an application I am developing. I have done these additional changes to the board:

pinmux.c:
```
#ifdef CONFIG_USB_DC_STM32
       {STM32_PIN_PA11, STM32F7_PINMUX_FUNC_PA11_OTG_FS_DM},
       {STM32_PIN_PA12, STM32F7_PINMUX_FUNC_PA12_OTG_FS_DP},
#endif  /* CONFIG_USB_DC_STM32 */
```

stm32f723e_disco.dts:
```
&usbotg_fs {
       status = "ok";
};
```

I am working on adding other peripherals to the STM32F7 family, so I'll do a batch adding those peripherals to the board in a single patch.

**Review by ydamigos — APPROVED** [review]

**Comment by erwango** [comment]
@aurel32 , can you pull pinmux and dts changes in this PR so we get everything at a single place?

**Comment by erwango** [comment]
recheck

**Review by jfischer-no — APPROVED** [review]

**Comment by aurel32** [comment]
@erwango, I'll update this PR once PR#8649 (STM32F723E-DISCO support) is merged, as the pinmux and dts changes depend on files introduced in it.

**Comment by aurel32** [comment]
@erwango, I'll update this PR once PR#8649 (STM32F723E-DISCO support) is merged, as the pinmux and dts changes depend on files introduced in it.

**Comment by galak** [comment]
> @erwango, I'll update this PR once PR #8649 (STM32F723E-DISCO support) is merged, as the pinmux and dts changes depend on files introduced in it.

waiting on @dbkinder to review the docs on #8649, otherwise its good.

**Comment by aurel32** [comment]
Thanks @galak for the merge. I have just updated this PR with an additional commit enabling USB OTG FS on the STM32F723E-DISCO board.

**Review by ydamigos — APPROVED** [review]

**Review by loicpoulain — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
Doc changes LGTM, thanks!

**Review by finikorg — APPROVED** [review]
LGTM, not tested on real HW.

**Pull request merged**
