### PR TITLE
doc: boards: qemu: Mention support for SLIP networking

### PR DESCRIPTION
**Pull request by pfalcon**
Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
As a follow up to https://github.com/zephyrproject-rtos/zephyr/pull/612. Nowhere in qemu board descriptions we mention that they support networking, so for someone approaching Zephyr not from networking side, that fact may be quite hard to figure out.

**Comment by nashif** [comment]
rebase on top of latest master please

**Comment by pfalcon** [comment]
> rebase on top of latest master please

Done.

**Review by dbkinder — APPROVED** [review]
+1

**Pull request merged**
