### PR TITLE
Bluetooth: ATT: Check if channel is ready before reuse REQ buffer

### LINKED ISSUE #64967: Bluetooth: Host: bt_att: ATT buffer re-use mechanism is controller dependent
**Describe the bug**
The ATT buffer re-use mechanism relies on a controller sending number of completed packets after each TX to free the ATT TX metadata. Section 7.7.19 Number Of Completed Packets event of the Bluetooth Core specification (v5.4) states that "The rate with which this event is sent is manufacturer specific.". This means that a controller could choose to only send this event from time to time to ensure Host - Controller flow control, but not after each Tx. This would cause the Host to think that there is still an ongoing transaction on the ATT channel when it wants to send a new response, even if the previous response was already sent.

In bt_att_chan_create_pdu function:
```
if (re_use) {
        /* There can only ever be one transaction at a time on a
	        * bearer/channel. Use a dedicated channel meta-data to ensure
	        * we can always queue an (error) RSP for each REQ. The ATT
	        * module can then reschedule the RSP if it is not able to send
	        * it immediately.
	        */
        if (chan->rsp_meta.att_chan) {
	        /* Returning a NULL here will trigger an ATT timeout.
		        * This is better than an assert as an assert would
		        * allow a peer to DoS us.
		        */
	        LOG_ERR("already processing a REQ/RSP on chan %p", chan);
        
	        return NULL;
        }
		....
}
```

**To Reproduce**
I used Zephyr BLE on an internal platform, rebased on 3.5.0 tag. One board was flashed with the peripheral_ht sample and one with the central_ht sample. 2 calls in a row to bt_att_chan_create_pdu() without a HCI number of completed packets to free the ATT Tx metadata leads to erros. Service discovery is not finished properly and application functionality is affected.

**Related issues**
https://github.com/zephyrproject-rtos/zephyr/issues/64649
https://github.com/zephyrproject-rtos/zephyr/issues/62279

### PR DESCRIPTION
**Pull request by yeaissa**
- Check if channel is ready before the reuse
- Trigger the error if ATT_ENFORCE_FLOW is requested

Fixes: #64967

### CODE REVIEW

**Comment by yeaissa** [comment]
Related to: https://github.com/zephyrproject-rtos/zephyr/issues/64967

**Comment by jori-nordic** [comment]
I'm starting to regret this hack. Maybe reverting it altogether is best?
What do you think @yeaissa @jhedberg @alwa-nordic

**Comment by alwa-nordic** [comment]
> I'm starting to regret this hack. Maybe reverting it altogether is best?

That's fine. I am for reverting regressions.

**Comment by jhedberg** [comment]
> > I'm starting to regret this hack. Maybe reverting it altogether is best?
> 
> That's fine. I am for reverting regressions.

Fine with me as well.

**Comment by yeaissa** [comment]
If the changes resulting the regression are optional, maybe reverting them is a good option

**Comment by jori-nordic** [comment]
Reverting here: https://github.com/zephyrproject-rtos/zephyr/pull/65272

**Comment by yeaissa** [comment]
Reverting the commits you addressed with the PR fixes the issue. Thanks

**Comment by jori-nordic** [comment]
> Reverting the commits you addressed with the PR fixes the issue. Thanks

Alright, closing this PR then. Sorry again for the trouble this hack caused, I didn't imagine it'd be that bad.

**Pull request closed without merging**
