### PR TITLE
drivers: esp32: Fix esp_wifi_drv strncpy warning

### LINKED ISSUE #80066: drivers: esp32: esp_wifi_drv strncpy warning
**Describe the bug**

When compiling `esp_wifi_drv.c` with `CONFIG_SPEED_OPTIMIZATIONS=y` the compiler creates a warning:
```bash
   esp_wifi_drv.c:736:9: warning: 'strncpy' output may be truncated copying 32 bytes
       from a string of length 32 [-Wstringop-truncation]
      736 |         strncpy(status->ssid, data->status.ssid, WIFI_SSID_MAX_LEN);
```
**To Reproduce**

```bash
cd tests/boards/espressif/wifi
west build -p -b esp32s3_devkitm/esp32s3/procpu -- -DCONFIG_SPEED_OPTIMIZATIONS=y
```
**Environment (please complete the following information):**
main

### PR DESCRIPTION
**Pull request by rruuaanng**
Change the bytes occupied by the ssid member in the wifi structure to 'WIFI_SSID_MAX_LEN + 1' so that it can eliminate the '-Wstringop-truncation' warning.

Fixes #80066

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Please split the PR to two commits, one with the driver changes and the other with generic wifi changes.
The commit subject for the generic changes could start with `net: wifi: .....`

**Review by jukkar — APPROVED** [review]

**Review by wmrsouza — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]

**Comment by brandon-exact** [comment]
closes https://github.com/zephyrproject-rtos/zephyr/issues/80066

**Comment by rruuaanng** [comment]
Wait for the PR to merge before closing the issue.

**Comment by dleach02** [comment]
> Wait for the PR to merge before closing the issue.

I've updated the first comment to include the Fixes #<nnnn>. This will do the automatic linking and auto closing when this merges.

**Pull request merged**
