### PR TITLE
AArch64: Make SMC helpers more useful

### PR DESCRIPTION
**Pull request by carlocaione**
Patchset to make the SMCCC decoupled from PSCI  so that it can be used by other drivers / applications when they need to call into the secure monitor.

### CODE REVIEW

**Comment by carlocaione** [comment]
Please ignore the compliance failure.

**Review by npitre — APPROVED** [review]

**Review by sandeepbrcm — APPROVED** [review]
A-TF  -> TF-A

**Comment by carlocaione** [comment]
Can we merge this?

**Comment by carlocaione** [comment]
@nashif can you merge this? The compliance failure is expected and bogus.

**Pull request merged**
