### PR TITLE
twister: measure build time and report it.

### PR DESCRIPTION
**Pull request by nashif**
- twister: measure build time and report it in json output
- twister: tests: adapt tests for new behaviour in runner class

### CODE REVIEW

**Review by hakehuang — DISMISSED** [review]

**Review by gchwier — APPROVED** [review]
Looks good and works as expected (I've tested only on Linux)

**Review by golowanow — APPROVED** [review]

**Comment by nashif** [comment]
Here is a nugget I used for evaluating overall build time that can be used for comparing different modes :-)

```cat twister-out/twister.json  | jq '[.testsuites[].build_time | tonumber ] | add'```

**Comment by gchwier** [comment]
> Here is a nugget I used for evaluating overall build time that can be used for comparing different modes :-)
> 
> `cat twister-out/twister.json | jq '[.testsuites[].build_time | tonumber ] | add'`

@nordic-piks it can be used to compare build time when incremental build or ccache is used

**Comment by nashif** [comment]
> @nordic-piks it can be used to compare build time when incremental build or ccache is used

thats exactly why I implemented that :) I have some interesting numbers to show comparing different modes for building.

**Comment by nashif** [comment]
related https://github.com/zephyrproject-rtos/zephyr/pull/65742

**Pull request merged**
