### PR TITLE
doc: mgmt: mcumgr: Clarify sha256 hash details in img_mgmt

### LINKED ISSUE #52412: doc: mgmt: mcumgr: Clarify that hash in img_mgmt is a full sha256 hash and required
**Is your enhancement proposal related to a problem? Please describe.**
The hash used in MCUmgr should be a full SHA256 hash, so that it can be used to know if a file upload is correct or not. The original MCUmgr documentation clearly state that this is a a full SHA256 hash, the zephyr documentation wrongly states that it can be anything. Therefore the documentation should be updated.
The go mcumgr application correctly sends the full SHA256 hash.

### PR DESCRIPTION
**Pull request by nordicjm**
Clarifies that a full SHA256 hash is required for the hash in img_mgmt.

Fixes #52412

### CODE REVIEW

**Review by de-nordic — CHANGES_REQUESTED** [review]
That may break our own software.

**Review by philips77 — CHANGES_REQUESTED** [review]
Requested change breaks backwards compatibility with all existing tools.

**Comment by nordicjm** [comment]
> Requested change breaks backwards compatibility with all existing tools.

Existing MCUmgr go tool works fine, other tools that this breaks compatibility with were non-compliant with the original MCUmgr protocol, it does not say that a truncated hash can be used.

**Comment by philips77** [comment]
Also, doesn't say what sha version should be used. Actually, is there something like "original mcu manager protocol" documentation? I know Dominik wrote doc recently, based on the implementation, not any external doc.
The only thing that could suggest that `sha` is sha is the name, but there are at least 3 versions which could be used. 

Apart from that, assuming someone would use full sha256 already, is there any "version check result" proposed, and any response from the device in case of success / failure? This is also not expected by current implementations.

**Comment by nordicjm** [comment]
> Apart from that, assuming someone would use full sha256 already, is there any "version check result" proposed, and any response from the device in case of success / failure? This is also not expected by current implementations.

Existing tools will work regardless, even if you do not use a valid hash or just use a string like "abcd", the only change is that in the final packet if the image check Kconfig is enabled, there will be a new field in the response called `match` which is a bool, and will either be true or false. Existing tools should not care about this field, new tools that do care about this field will need to be compliant with sending a valid sha256 hash, otherwise they will read the field and see false if they have sent an invalid field for `sha`.

**Comment by de-nordic** [comment]
There is no description of "original protocol" regarding this. The SHA256, in case of mcumgr, can be deducted from definition of IMG_MGMT_DATA_SHA_LEN which states this is SHA256.
Internal code would compare AT MOST `IMG_MGMT_DATA_SHA_LEN` with what it has received.
Additionally it is not known what is the SHA taken from , and it may have been assumed that this is image SHA or TLV SHA from image sing.There is not sha check here at all, what happens the value here is used as session identifier, which is clearly seen in code.
Because this is established behaviour, by Zephyr and mcumgr-cli at this point, this should be corrected to reflect established behaviour.

Additionally from looking at source code of newtmgr here:
https://github.com/apache/mynewt-newtmgr/blob/c56797e09f8b1efe2e1ec9c44ac3a041320e0823/nmxact/xact/image.go#L169-L172
and here:
https://github.com/apache/mynewt-newtmgr/blob/c56797e09f8b1efe2e1ec9c44ac3a041320e0823/nmxact/xact/image.go#L348-L359
it can be clearly seen that the SHA is actually calculated over first chunk of data being sent, not entire image.

**Comment by philips77** [comment]
Hmm.. LGTM then. I even kinda like, that you've "fixed" the weirdly used `sha` to be the real sha. 

@de-nordic I like, after all. Although I was initially more in favor of "return sha with the last notification for the user to decide", that approach would need to have 2 issues:
1. the `sha` param would still not be a sha
2. clients would anyway need to handle and check the sha to check the integrity.

@nordicjm's proposal still requires client update, but fixes 1. without introducing an extra parameter.

As an author of 2 clients, I approve. From the customer perspective it will be all fine if the device would still undergo a reset + swap in case of a mismatch. This perhaps is not clear enough, that the `match` = false does not block dfu, it's just a hint.

**Comment by philips77** [comment]
Yes, clarification needs to be made what algorithm should be used on what data. Currently mobile libs are calculating over the whole bin file, but sending only 3 first bytes.

One other thing: proposed change in any form (whether sending sha by the client initially, or returning sha at the end from the device) requires MTU to be set to somewhat big value,. This again makes it not compatible with pre-Android 5 phones, where MTU was fixed to 23. Unless segmentation is used.

**Comment by nordicjm** [comment]
>  it can be clearly seen that the SHA is actually calculated over first chunk of data being sent, not entire image.

It is sent over the whole image, `data` there is the whole data, it splits it into chunks later on

**Comment by nordicjm** [comment]
> Yes, clarification needs to be made what algorithm should be used on what data. Currently mobile libs are calculating over the whole bin file, but sending only 3 first bytes.

sha256 of the whole bin is correct, this is how the go application does it (this has been verified), it does not send a sha256 of the first frame, it sends a sha256 of the whole image to be sent but only sends it in the first frame.

**Comment by de-nordic** [comment]
> > it can be clearly seen that the SHA is actually calculated over first chunk of data being sent, not entire image.
> 
> It is sent over the whole image, `data` there is the whole data, it splits it into chunks later on

That is true, my bad.

**Comment by de-nordic** [comment]
OK then. Let change it, but we should not enforce "the full sha", unless sha check is performed, because this is 64 characters required not only in protocol but also in upload state.

**Comment by philips77** [comment]
I think you should treat sha just like before if its length is != 16 bytes.
If a new fw is built with this check enabled it should also support "old apps", which are sending short sha. In this case it should just ignore and not do any check.

**Comment by nordicjm** [comment]
Release notes note has been added

**Review by stephanosio — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
