### PR TITLE
kernel: Fix compilation errors when CONFIG_TIMESLICING=n

### PR DESCRIPTION
**Pull request by dcpleung**
Add ifdef guard to the z_reset_timeslice() to fix compilation
errors when CONFIG_TIMESLICING is disabled.

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Comment by dcpleung** [comment]
recheck

**Comment by ceolin** [comment]
lgtm now :)

**Comment by ceolin** [comment]
@dcpleung did you receive my previous comments ? I'm not seeing them here

**Review by andyross — APPROVED** [review]
Yeah, this clearly got forgotten during the scheduler rework.  FWIW: one corrollary here is that we have poor test coverage of TICKLESS && !TIMESLICING.   It wouldn't be a bad idea to add some test cases to enumerate that, maybe just alternate config files for some existing test...

Also, full disclosure: I'm in the process of ripping all the timer/tickless/timeslicing/timeout code apart as we speak.

**Comment by dcpleung** [comment]
@ceolin I saw your comment about the #ifdef so I removed it. Though I am not seeing that comment in the comment history.

@andyross This was found during my playing with tickless. Once your re-work is done, these kinds of things should all be fixed (no pressure... *yet*).

**Comment by nashif** [comment]
@ceolin There is something wrong with how you comment on code it is not visible in the source and somehow appears as  standalone comment.

**Review by nashif — APPROVED** [review]

**Pull request merged**
