### PR TITLE
LoRaWAN: Add firmware-upgrade over the air (FUOTA) services 

### PR DESCRIPTION
**Pull request by martinjaeger**
This PR adds an implementation of the services specified by the LoRa Alliance to enable firmware-upgrade over the air (FUOTA):

- Application Layer Clock Synchronization ([TS003](https://resources.lora-alliance.org/technical-specifications/ts003-2-0-0-application-layer-clock-synchronization))
- Fragmented Data Block Transport ([TS004](https://resources.lora-alliance.org/technical-specifications/ts004-2-0-0-fragmented-data-block-transport))
- Remote Multicast Setup ([TS005](https://resources.lora-alliance.org/technical-specifications/ts005-2-0-0-remote-multicast-setup))

As for the rest of the LoRaWAN implementation in Zephyr, it uses some functions provided by the [LoRaMac-node module](https://github.com/zephyrproject-rtos/loramac-node) developed by Semtech. We are currently still using a custom fork with some bug fixes related to class C (cherry-picked from PRs in the upstream repo) and Zephyr-specific adaptations. Before we merge this, those changes need to go into the Zephyr fork.

Package handling and writing the firmware into flash is RTOS-aware and uses native Zephyr APIs. The FUOTA process requires MCUboot to verify and boot the received firmware image.

The FUOTA process is started by the application and afterwards runs in the background in its own work queue thread. After a firmware upgrade is successfully received, the application is notified via a callback and can reboot the device to apply the upgrade.

**Testing**

The implementation has been successfully tested with [ChirpStack](https://www.chirpstack.io/). Deploying a FUOTA requires the [FUOTA server](https://github.com/brocaar/chirpstack-fuota-server) in addition to the normal ChirpStack deployment. Testing with AWS IoT is currently ongoing.

We are still in the process of more extensive testing, but would be happy about any kind of early feedback.

**Licensing**

There is [existing code in the LoRaMac-node module](https://github.com/Lora-net/LoRaMac-node/tree/master/src/apps/LoRaMac/common/LmHandler/packages) that implements the FUOTA service (BSD-licensed). However, this code uses its own timer hooks and scheduling / processing mechanisms as it can be used in bare-metal applications. For optimized performance, I re-wrote the implementation from scratch using Zephyr APIs and kernel services. I did have a look at the existing code, of course, and took some inspiration from it, which I mentioned in the relevant files. @mluis1 as the original author of the LoRaMac-node code: Are you fine with this approach or would you like to see a different kind of attribution.

### CODE REVIEW

**Comment by JordanYates** [comment]
I think splitting out some parts of this into separate PR's might result in faster progress. The clock-sync spec for example looks standalone and relatively non-controversial. As a specific note on that, I don't think it should live under `fuota`.

**Comment by martinjaeger** [comment]
> I think splitting out some parts of this into separate PR's might result in faster progress. The clock-sync spec for example looks standalone and relatively non-controversial. As a specific note on that, I don't think it should live under `fuota`.

Separating the services is not as easy as it seems. Each of them needs a mechanism to send delayed messages and offload processing of messages. We need to run this in a separate thread and cannot use the system work queue, as calling `lorawan_send` from a system work queue handler will result in a dead lock. Now all services use one common `fuota` work queue thread. If they were completely independent and had their own threads, it would be a wast of resources IMO.

I agree, though, that clock sync as well as multicast could be used independent of FUOTA. Maybe we should create some sort of auxiliary lorawan work queue, which is shared by the three services of this PR and any other background services that may be introduced in the future. @JordanYates What would you suggest where these services should live and how the common parts should be called (instead of `fuota`)?

**Comment by JordanYates** [comment]
> Separating the services is not as easy as it seems. Each of them needs a mechanism to send delayed messages and offload processing of messages. We need to run this in a separate thread and cannot use the system work queue, as calling lorawan_send from a system work queue handler will result in a dead lock. Now all services use one common fuota work queue thread. If they were completely independent and had their own threads, it would be a wast of resources IMO.

I agree that a thread per service is a waste. The two options I see are fixing/updating `loran_send` so that it can be used in the system work queue (maybe via some `lorawan_send_async`), or implementing the standalone services as an API that a user thread drives. Personally I already have a dedicated thread for initiating LoRaWAN connections with backoffs and detecting dropped links, so slotting the clock-sync service into that thread would be ideal for my use-case.

> I agree, though, that clock sync as well as multicast could be used independent of FUOTA. Maybe we should create some sort of auxiliary lorawan work queue, which is shared by the three services of this PR and any other background services that may be introduced in the future.

Is this suggestion driven purely by the inability to use `lorawan_send` from the system work queue? If so I think a cleaner solution would be to fix that.

> What would you suggest where these services should live and how the common parts should be called (instead of fuota)?

`lorawan/services` is my suggestion.

**Comment by JordanYates** [comment]
Sorry! Laggy cafe internet

**Comment by martinjaeger** [comment]
The problem with `lorawan_send` is that it waits for the semaphore `mcps_confirm_sem`, which is given in `mcps_confirm_handler`. The `mcps_confirm_handler` is called from a system work queue item in the `lora` driver, so if we call `lorawan_send` from the system work queue, we stall the entire system work queue.

Other than calling `lorawan_send` from a separate thread (user or background service) I don't see how this could be easily avoided/fixed. The processing of the `dio1` interrupt in the driver involves some SPI communication, so it cannot run in an ISR (having higher priority than the system work queue).

Currently I've also implemented some re-join and backoff mechanisms running an a user thread in one application, but I think this should finally also be part of the lorawan subsys. So I'd prefer to introduce a dedicated thread for LoRaWAN background services. Storing files in `lorawan/services` instead of `lorawan/fuota` sounds like a good idea.

**Comment by rerickson1** [comment]
>  Storing files in lorawan/services instead of lorawan/fuota sounds like a good idea.

I like that idea.

**Comment by martinjaeger** [comment]
@JordanYates I've updated the whole thing according to your suggestion. The different services are now independent and added in dedicated commits for easier review. All services use a common work queue thread.

**Comment by JordanYates** [comment]
If `lorawan_send` was able to be used in the system workqueue, would the dedicated workqueue in this PR still be required?
I had a quick look and it seems possible with minimal changes, but I won't bother if the dedicated workqueue is still needed.

**Comment by rerickson1** [comment]
> However, I am not sure if it is actually a good idea to use (and block) the system work queue with these services. Erasing flash can take a couple of seconds depending on the flash partition size. Also the fragment decoder needs a lot of computing resources when it restores data of missed fragments from redundant fragments sent at the end.

I would not recommend using the system work queue for this. If you have a system that is also running bluetooth, this could cause issues.

**Comment by diggerdata** [comment]
Is this something that can be revisited?

**Comment by martinjaeger** [comment]
> Is this something that can be revisited?

Yes, I've still got it on my ToDo list. As you may have seen, the time sync part has already been merged to main in a dedicated PR. I have already rebased and updated the remaining part, but still need to test it again before opening a new PR. Will try to get that done within the next 2 weeks.

**Comment by diggerdata** [comment]
> > Is this something that can be revisited?
> 
> Yes, I've still got it on my ToDo list. As you may have seen, the time sync part has already been merged to main in a dedicated PR. I have already rebased and updated the remaining part, but still need to test it again before opening a new PR. Will try to get that done within the next 2 weeks.

That's great! Would be more than happy to test it on our development network of devices based on the RAK3172. We also sponsored Chirpstack to get the FUOTA server updated for v4.

**Comment by martinjaeger** [comment]
> We also sponsored Chirpstack to get the FUOTA server updated for v4.

That's nice! That was actually partly what I was waiting for, as I didn't want to set up v3 anymore and don't have access to the AWS IoT environment anymore at the moment.

**Comment by JiapengLi** [comment]
@martinjaeger 
I am author of https://github.com/JiapengLi/LoRaWANFragmentedDataBlockTransportAlgorithm

I am also using zephyr these days, I think I can help do some test or porting work if you need.

**Comment by dolence** [comment]
Is this abandoned? Are Zephyr LoRaWAN FUOTA actually supported in any form?

**Comment by martinjaeger** [comment]
> Is this abandoned? Are Zephyr LoRaWAN FUOTA actually supported in any form? 

It's not abandoned, but continued in small steps. The clock sync is already merged, remote multicast is ready for review (see link above) and frag data transport as the final step will follow afterwards.

**Comment by dolence** [comment]
> It's not abandoned, but continued in small steps. The clock sync is already merged, remote multicast is ready for review (see link above) and frag data transport as the final step will follow afterwards.

These are very good news! Thank you.

**Pull request closed without merging**
