### PR TITLE
SimpleLink SDK 2.40 update

### PR DESCRIPTION
**Pull request by vanti**
This pull request updates Zephyr to use TI CC3220 SDK 2.40, which includes the following tasks:

- Add/Update files taken from TI CC3220 SDK, including
    - peripheral drivers
    - driverlib (HAL)
    - WiFi host driver and porting layer interface headers

    Origin: Texas Instruments cc32xx SimpleLink SDK
    URL: http://www.ti.com/tool/download/SIMPLELINK-CC3220-SDK
    Purpose: Provide driver libraries and HAL for TI CC32XX SoC
    Maintained-by: External
- Ran dos2unix on the files from the SDK
- Update CC3220 board files
- Update the README in ext/hal/ti/simplelink
- Update user.h for Zephyr to provide its own os_Spawn implementation
- Update CMakeLists.txt to build correct list of files in SDK
- Update SimpleLink wifi driver so that it builds with the SDK
- Modify cc_pal.h to use posix headers from Zephyr
- Add posix api and pthread support to Kconfig when using wifi driver
  This is necessary given the code now uses pthread and sem. Both
  CONFIG_POSIX_API and CONFIG_PTHREAD_IPC are selected.
- Add a workaround for #13444 in cc_pal.h to undef timeval
- Move fcntl() from socket_offload.c to socket_offload.h, similar
to how other socket APIs are defined. This is necessary to avoid link
errors where the symbol is multiply-defined.

### CODE REVIEW

**Comment by vanti** [comment]
@rlubos Please take a look at the change to socket_offload.h regarding fcntl(), to see if it'd still work for you.

**Review by rlubos — APPROVED** [review]
+1 for the `fcntl` change. AFAIR I had some issues with keeping the implementation in the header file, but apparently that's no longer the case. Works fine with nRF offloading.

**Review by pfalcon — APPROVED** [review]

**Comment by galak** [comment]
@vanti @GAnthony can you add yourself and/or @GAnthony to CODEOWNERs.

I'd also ask that the import vs fixup / changes to the HAL be separate commits

**Comment by vanti** [comment]
> @vanti @GAnthony can you add yourself and/or @GAnthony to CODEOWNERs.
> 
> I'd also ask that the import vs fixup / changes to the HAL be separate commits

@galak  Do we need these changes to be bisectable (given the existing code won't build after the import without the fixes)? Logically having the split does make sense, so I am with you there.

**Comment by galak** [comment]
> @galak Do we need these changes to be bisectable (given the existing code won't build after the import without the fixes)? Logically having the split does make sense, so I am with you there.

No they don't need to be bisectable.

**Comment by galak** [comment]
@vanti please add or change yourself as the CODEOWNER.

**Comment by vanti** [comment]
@galak I have refactored the commits and updated CODEOWNERS.

**Review by jukkar — APPROVED** [review]
LGTM

**Pull request merged**
