### PR TITLE
drivers: sensor: lsm6dsl: add trigger support

### PR DESCRIPTION
**Pull request by avisconti**
Add DATA_READY trigger support to ST LSM6DSL driver.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Comment by avisconti** [comment]
AREA is sensors

**Review by MaureenHelm — COMMENTED** [review]
LGTM. Are the gpio defaults correct for all the in-tree boards that support this sensor? (96b_argonkey and disco_l475_iot1)

**Comment by avisconti** [comment]
@MaureenHelm 
> LGTM. Are the gpio defaults correct for all the in-tree boards that support this sensor? 
> (96b_argonkey and disco_l475_iot1)

Well, actually .... no. 
I just copied the default from other trigger examples in the area sensor, but to make it working
on ArgonKey I have to change the default. Not sure if they are correct for the disco_l475_iot1.

What I was planning for ArgonKey bsp was to add in the defconfig file for this board the proper
settings including the correct gpio for the trigger. But I can also remove the default setting here.

What do you think?

**Comment by MaureenHelm** [comment]
> What I was planning for ArgonKey bsp was to add in the defconfig file for this board the proper
> settings including the correct gpio for the trigger. But I can also remove the default setting here.

Yes, please update both board defconfigs and remove the default here. Ultimately we should get this from dts instead, but we're not quite there yet.

**Comment by MaureenHelm** [comment]
> These values above will be put in the defconfig file for ArgonKey bsp by me later on.
> I think that @erwango could do the same for the other platform.

I'm surprised that CI passed without adding the board defaults. Turns out this driver is not included in any of the build tests! Could you please add it to tests/drivers/build_all/sensors_a_m.conf?

**Comment by MaureenHelm** [comment]
@avisconti The problem is that the GPIO_DEV_NAME and GPIO_PIN_NUM are not conditioned upon HAS_DTS_I2C_DEVICE, so the configs always exist. A quick fix would be to change the default trigger mode to TRIGGER_NONE, or to put the defaults back into the driver Kconfig. The first option would be more consistent with other sensor drivers. 

A better fix would be to get sensor interrupt pins from dts, but as I said before I'm not sure we're ready for that yet. @erwango have you looked at this?

**Comment by erwango** [comment]
> A better fix would be to get sensor interrupt pins from dts, but as I said before I'm not sure we're ready for that yet. @erwango have you looked at this?

It would be quite close to support with https://github.com/zephyrproject-rtos/zephyr/pull/5381.
Though, I need some thinking to be it pass CI (Currently timed out because of too many boards impacted)

**Comment by avisconti** [comment]
@MaureenHelm 
OK, I followed your suggestion, thx! With your help guys I'm learning every day a new piece
of information about zephyr.

@erwango 
Perfect! As soon as the #5381 will be merged I think we will need to change the behaviour
in all the sensor drivers.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
