### PR TITLE
STM32: Various fixes to pm debug

### LINKED ISSUE #38784: stm32: pm: Debug mode not functional on G0
Enabling CONFIG_DEBUG=y has no effect on stm32g0 target.
After analysis, clock enable is required when to enable debug in stop mode, but missing.

### PR DESCRIPTION
**Pull request by erwango**
Fixes #38784

### CODE REVIEW

**Comment by erwango** [comment]
@ycsin you might be interested

**Review by galak — APPROVED** [review]

**Comment by ycsin** [comment]
I've noticed that on system boot and when mcu goes to STOP is causing my debug session to behave strangely, but I'm able to workaround it. I will test this patch tomorrow, thanks!

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by nashif — APPROVED** [review]

**Comment by erwango** [comment]
> I've noticed that on system boot and when mcu goes to STOP is causing my debug session to behave strangely, but I'm able to workaround it. I will test this patch tomorrow, thanks!

You might also be interested in https://github.com/zephyrproject-rtos/openocd/pull/46. No dependency with current patch.

**Comment by ycsin** [comment]
> You might also be interested in [zephyrproject-rtos/openocd#46](https://github.com/zephyrproject-rtos/openocd/pull/46). No dependency with current patch.

Thanks for the heads-up, is openocd better than Jlink?

**Comment by erwango** [comment]
> Thanks for the heads-up, is openocd better than Jlink?

@ycsin openocd is open source.

**Pull request merged**
