### PR TITLE
ITE: usb: it82xx2: enable RESUME interrupt and fix the ready bit issue

### PR DESCRIPTION
**Pull request by Chenhongren**
This PR includes the following changes
- enable RESUME interrupt
- fix issue with the unexpected setting of the ready bit

Tested with: Google Spikyrock project

### CODE REVIEW

**Review by tmon-nordic — COMMENTED** [review]
What about udc_it82xx2.c?

**Comment by Chenhongren** [comment]
> What about udc_it82xx2.c?

The udc it82xx2 driver has the same issue, and we're implementing the same fix. A PR will be submitted soon.

**Comment by Chenhongren** [comment]
hi @tmon-nordic @jfischer-no,
We'd like to know if you have any concerns about this PR. A project involving HID keyboard and touchpad is currently using the usb_dc subsystem and is approaching mass production. During remote wakeup stress testing, we discovered an issue where the HID functions stop working after wakeup. This PR was created to address the issue, and it's crucial to resolve it in the usb_dc stack. As for the udc changes, we are still working on them and conducting further testing to ensure greater stability.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@tmon-nordic @jfischer-no is it ok to get this through and follow up with the udc driver separately?

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
