### PR TITLE
include: always use <> for Zephyr includes

### PR DESCRIPTION
**Pull request by gmarull**
Double quotes "" should only be used for local headers.

### CODE REVIEW

**Review by carlocaione — APPROVED** [review]
this is a bit hilarious :D

**Review by fabiobaltieri — APPROVED** [review]
@gmarull would it make sense to have a compliance check for this? Can't think of a a case where `#include "zephyr/.*"` would be valid

**Review by Thalley — APPROVED** [review]
AFAIK we don't have any coding guidelines that states this, so this change is seemingly (unless you can provide a source for it otherwise) based on a personal choice, rather than official Zephyr coding guidelines. 

The only part related to this I could find was 
image
Which allows for the use of `"` 

I will approve because I agree with the changes and not because our coding guidelines demand this change. 

@fabiobaltieri before adding this to a CI check, it should be added to the coding guidelines IMO.

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri before adding this to a CI check, it should be added to the coding guidelines IMO.

Fair enough

**Comment by aescolar** [comment]
> AFAIK we don't have any coding guidelines that states this, so this change is seemingly (unless you can provide a source for it otherwise) based on a personal choice, rather than official Zephyr coding guidelines.

I don't mind this particular change per se, but I tend to recall that we had an understanding of not doing PRs of this type, or bundling this kind of changes in PRs. The reasoning being that there is no end to this kind of style polishing, but creates a lot of churn, merge conflicts and extra load for maintainers for relatively little benefit.

**Comment by gmarull** [comment]
> @gmarull would it make sense to have a compliance check for this? Can't think of a a case where `#include "zephyr/.*"` would be valid

I'm all in for a check and a rule. It's a matter of consistency, there's no reason to have "0.01%" of the code with a different style, headers have enough problems to yet have another one.

**Comment by Thalley** [comment]
> > AFAIK we don't have any coding guidelines that states this, so this change is seemingly (unless you can provide a source for it otherwise) based on a personal choice, rather than official Zephyr coding guidelines.
> 
> I don't mind this particular change per se, but I tend to recall that we had an understanding of not doing PRs of this type, or bundling this kind of changes in PRs. The reasoning being that there is no end to this kind of style polishing, but creates a lot of churn, merge conflicts and extra load for maintainers for relatively little benefit.

I would agree to this. 

Not sure if this PR counts as a Treewide change either, but in case it does, it also needs an RFC as per: https://docs.zephyrproject.org/latest/contribute/guidelines.html#treewide-changes

**Comment by gmarull** [comment]
> > > AFAIK we don't have any coding guidelines that states this, so this change is seemingly (unless you can provide a source for it otherwise) based on a personal choice, rather than official Zephyr coding guidelines.
> > 
> > 
> > I don't mind this particular change per se, but I tend to recall that we had an understanding of not doing PRs of this type, or bundling this kind of changes in PRs. The reasoning being that there is no end to this kind of style polishing, but creates a lot of churn, merge conflicts and extra load for maintainers for relatively little benefit.
> 
> I would agree to this.
> 
> Not sure if this PR counts as a Treewide change either, but in case it does, it also needs an RFC as per: https://docs.zephyrproject.org/latest/contribute/guidelines.html#treewide-changes

As is now, it's not a treewide change because this is not enforced nor mandatory. It's just a cleanup.

**Comment by fabiobaltieri** [comment]
> > I don't mind this particular change per se, but I tend to recall that we had an understanding of not doing PRs of this type, or bundling this kind of changes in PRs. The reasoning being that there is no end to this kind of style polishing, but creates a lot of churn, merge conflicts and extra load for maintainers for relatively little benefit.
> 
> I would agree to this.

I think there's a general understanding that purely cosmetic tree wide changes with no clear benefit should be avoided, but this specific one seems to make quite some sense, the include format differences are well understood. But I do think it's somewhat pointless to not follow up with a compliance check to keep this consistent in the future, at the rate of changes that the project has that's the only way to have coherency in the code base.

> Not sure if this PR counts as a Treewide change either, but in case it does, it also needs an RFC as per: https://docs.zephyrproject.org/latest/contribute/guidelines.html#treewide-changes

I don't think so, the scope of that is having a way of exposing and review changes that are going to break load of stuff either internally or externally. Doubt this will cause more than a couple merge conflicts, if any.

**Review by jukkar — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by Thalley** [comment]
> But I do think it's somewhat pointless to not follow up with a compliance check to keep this consistent in the future, at the rate of changes that the project has that's the only way to have coherency in the code base.

Agreed. I would also be in favor of that, granted that we add that to our coding guidelines. IMO the coding guidelines, and not the CI scripts, should be the source of truth, and IMO the CI scripts should not enforce rules that are not documented properly.

**Pull request merged**
