### PR TITLE
doc: fix multiple issues

### PR DESCRIPTION
**Pull request by gmarull**
Summary:
```
doc: doxygen: do not use separate member pages
When this option is enabled some data structures have missing pages. Use
the default setting (NO).

doc: warnings: make expressions more generic
When duplicates exist the problem may come from two or more distinct
constructs. When running parallel builds there is no guarantee on which
one will come first (or if all), so allow any C construct.

drivers: display: fix doxygen issues
The way some structures were documented was causing issues on the
Sphinx/Breathe side. Move to a more "standard" format.

doc: enable members option by default when using breathe 
Enable the :members: option by default when using breathe directives.
This exposes automatically stuff like structure fields.

doc: remove redundant usage of :members: in breathe directives
:members: is now enabled by default.
```

ref:https://zephyrproject.slack.com/archives/C18PLHN8H/p1621107917366000

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
Looks good, thank you!

**Review by vanwinkeljan — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
just need to fix `reference/bluetooth/gatt.rst`

**Review by mbolivar-nordic — DISMISSED** [review]
Just putting a -1 on real quick before it gets merged

**Comment by mbolivar-nordic** [comment]
I think this is a great change, I just am concerned about the possibility of it accidentally making some private members publicly documented within stable APIs.

I'm guessing that we have not audited the APIs in this page as a result of this PR:

https://docs.zephyrproject.org/latest/reference/api/overview.html

I think we should make sure that any newly visible structure members in stable APIs are either deliberately there for users to access, or explicitly documented as for internal use, so we can change them later without having to go through the stable API process.

@gmarull have you done something like that?

cc @carlescufi

**Comment by gmarull** [comment]
> I think this is a great change, I just am concerned about the possibility of it accidentally making some private members publicly documented within stable APIs.
> 
> I'm guessing that we have not audited the APIs in this page as a result of this PR:
> 
> https://docs.zephyrproject.org/latest/reference/api/overview.html
> 
> I think we should make sure that any newly visible structure members in stable APIs are either deliberately there for users to access, or explicitly documented as for internal use, so we can change them later without having to go through the stable API process.
> 
> @gmarull have you done something like that?
> 
> cc @carlescufi

I haven't performed an exhaustive analysis, but as far as I understand `:members:` displays public members, i.e. struct fields in our case (if they are documented, since we're not using `:undoc-members:`). This information is already displayed on the Doxygen side.

**Comment by mbolivar-nordic** [comment]
Maybe we can give the maintainers until rc3 to check their APIs to make sure they aren't accidentally overdocumenting as a result of this PR?

**Comment by gmarull** [comment]
> Maybe we can give the maintainers until rc3 to check their APIs to make sure they aren't accidentally overdocumenting as a result of this PR?

I'm ok with that, how can we notify?

**Comment by mbolivar-nordic** [comment]
> I'm ok with that, how can we notify?

per offline discussion with @carlescufi , this can be done via email to devel

**Comment by mbolivar-nordic** [comment]
@gmarull is there a doc build up somewhere people can click on, so they don't have to build it themselves?

**Review by joerchan — APPROVED** [review]

**Comment by nashif** [comment]
Do we have an example where this is wrong? The docs for members was always published, just differently. IMO this should be merged and issues should be addressed as we find them, if any. delaying this with no indication that someone is actually working on reviewing all APIs in the background is just pushing any potential issues for later, i.e. rc3...

**Comment by gmarull** [comment]
> Do we have an example where this is wrong? The docs for members was always published, just differently. IMO this should be merged and issues should be addressed as we find them, if any. delaying this with no indication that someone is actually working on reviewing all APIs in the background is just pushing any potential issues for later, i.e. rc3...

+1

**Comment by mbolivar-nordic** [comment]
Fine, removing my -1

**Comment by mbolivar-nordic** [comment]
@nashif I'm preparing my "I told you so" when we have to deal with this in the stable API process down the line ... :P

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
