### PR TITLE
Bluetooth: Update ICS to TCRL 2024-1

### PR DESCRIPTION
**Pull request by sjanc**

### CODE REVIEW

**Comment by sjanc** [comment]
This also includes changes and comments discussed in:
https://github.com/zephyrproject-rtos/zephyr/pull/71942
https://github.com/zephyrproject-rtos/zephyr/pull/70085

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
Will there be a new qualification file as a alternative to .bls?

**Comment by sjanc** [comment]
from what I see one must create a project and import ICS, there is currently no option to export/import whole project there

**Comment by Thalley** [comment]
> from what I see one must create a project and import ICS, there is currently no option to export/import whole project there

Is the ICS file the same as the .pts file here? 
In other words, can I locally with the new tools import what we now have and get the same project as you have?

**Comment by sjanc** [comment]
yes, you import .pts file into Qualification Workspace

**Comment by aescolar** [comment]
@jhedberg @jori-nordic is this for 3.7 ?

**Comment by jori-nordic** [comment]
I think so. It was discussed in the WG meeting but my memory fails me.
@sjanc could you confirm if we wanted this for the LTS?

**Pull request merged**
