### PR TITLE
reserved_memory: Remove it and cleanup

### PR DESCRIPTION
**Pull request by carlocaione**
The reserved memory mechanism (sections and regions definition) has been
entirely replaced, greatly extended and made it better by the work done
on the `zephyr,memory-region` compatible.

Since there are no actual users, remove it.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Comment by carlocaione** [comment]
@mbolivar-nordic @JordanYates could you take a look at this?

**Review by mbolivar-nordic — DISMISSED** [review]
IMO this PR is a good example of why it's good to keep definitions out of devicetree.h unless they are really "pure" devicetree API. If this was in devicetree.h, we would have to go through the stable API change process to remove this. As is, though, zephyr/linker/devicetree_reserved.h is not part of any stable API as far as I can tell.

However, I don't see it listed anywhere here: https://docs.zephyrproject.org/latest/develop/api/overview.html

That's OK only because it's being removed, in my opinion.

**Comment by mbolivar-nordic** [comment]
@carlocaione LGTM, but needs rebase

**Comment by JordanYates** [comment]
Is placing the nodes under `soc` the correct choice? If I do the following to try and reserve the first 256 bytes for something:
```
	soc {
		res: memory@20000000 {
			compatible = "zephyr,memory-region", "mmio-sram";
			reg = < 0x20000000 0x10 >;
			zephyr,memory-region = "RES";
		};
		usable: memory@20000010 {
			compatible = "zephyr,memory-region", "mmio-sram";
			reg = < 0x20000010 0xf00 >;
			zephyr,memory-region = "USABLE";
		};
	};
``` 
`zephyr.dts` ends up with:
```
	soc {
		sram0: res: memory@20000000 {
			compatible = "zephyr,memory-region", "mmio-sram";
			reg = < 0x20000000 0x10 >;
			zephyr,memory-region = "RES";
		};
		usable: memory@20000010 {
			compatible = "zephyr,memory-region", "mmio-sram";
			reg = < 0x20000010 0xf00 >;
			zephyr,memory-region = "USABLE";
		};
	};
```
Overriding the size of `sram0` just because I want to reserve the first part of it does not seem correct.

My question is, if we remove `reserved-memory`, what is our mechanism of partitioning RAM?

**Comment by JordanYates** [comment]
Also there are many other places in-tree using `reserved-memory`, how is this passing CI?
https://github.com/zephyrproject-rtos/zephyr/blob/05946ed9b26f2ad378299ce31733248a7632317f/boards/arm/thingy53_nrf5340/thingy53_nrf5340_common.dts#L295
https://github.com/zephyrproject-rtos/zephyr/blob/05946ed9b26f2ad378299ce31733248a7632317f/samples/subsys/ipc/ipc_service/icmsg/boards/nrf5340dk_nrf5340_cpuapp.overlay#L12
https://github.com/zephyrproject-rtos/zephyr/blob/05946ed9b26f2ad378299ce31733248a7632317f/samples/subsys/ipc/ipc_service/icmsg/remote/boards/nrf5340dk_nrf5340_cpunet.overlay#L12
https://github.com/zephyrproject-rtos/zephyr/blob/05946ed9b26f2ad378299ce31733248a7632317f/samples/tfm_integration/tfm_ipc/boards/nrf9160dk_nrf9160_ns.overlay#L27
etc

**Comment by carlocaione** [comment]
@JordanYates 

> Is placing the nodes under `soc` the correct choice? If I do the following to try and reserve the first 16 bytes for something:

You cannot do that. Can you create nested sections in the linker script? If the answer is no (and it is no) then you cannot do that either using the `zephyr,memory-region` mechanism. You can create non-overlapping sections and regions but if you want to reserve something in an already existing section then you have to use something else (like placing buffers with `__section__` & co).

Please note that what you are trying to do is generally wrong in any way. If you want to carve out a portion of the SRAM how can be sure that the kernel using the SRAM is not stepping over your data? What you have to do in that case is theoretically decrease the size of the SRAM to make space for the carved out section (and make those non overlapping at the end).

> Also there are many other places in-tree using reserved-memory, how is this passing CI?

The `reserved-memory` mechanism that I'm removing is a bit more complicated than that. It is not  simply acting on the nodes with the compatible. For that mechanism to be active you have to modify the linker script (in a similar way we do with `zephyr,memory-region`) but in this case no board / arch / sample is doing that. So this mechanism is simply unused.

**Comment by JordanYates** [comment]
I was asking because in one of the tests you just migrated the `reserved-memory` nodes under `soc`, and it didn't really look right.

> Please note that what you are trying to do is generally wrong in any way. If you want to carve out a portion of the SRAM how can be sure that the kernel using the SRAM is not stepping over your data? What you have to do in that case is theoretically decrease the size of the SRAM to make space for the carved out section (and make those non overlapping at the end).

If it's the wrong way, then the test should be updated to do it the right way.

As an aside, I don't agree that resizing SRAM is the best solution. The SRAM node should be how large the physical RAM is, partitioning SRAM should be some analogue of the FLASH `fixed-partitions` (which is what I thought `reserved-memory` was).

**Comment by JordanYates** [comment]
> The reserved-memory mechanism that I'm removing is a bit more complicated than that. It is not simply acting on the nodes with the compatible. For that mechanism to be active you have to modify the linker script (in a similar way we do with zephyr,memory-region) but in this case no board / arch / sample is doing that. So this mechanism is simply unused.

I'm a bit confused by this. Are devicetree files with `reserved-memory` nodes still valid after this PR?

**Comment by carlocaione** [comment]
> I was asking because in one of the tests you just migrated the reserved-memory nodes under soc, and it didn't really look right.

...

> If it's the wrong way, then the test should be updated to do it the right way.

Oooh, yeah I migrated without checking the addresses. Yes, that's formally not correct, I'll fix it. That is working correctly because the new section is very far away from anything else used in the SRAM section.

> I'm a bit confused by this. Are devicetree files with reserved-memory nodes still valid after this PR?

Yes, absolutely no change about that.

The nodes with compatible `reserved-memory` were used to create the sections only when in the linker script you have `LINKER_DT_RESERVED_MEM_REGIONS()` and `LINKER_DT_RESERVED_MEM_SECTIONS()` macros and that is not the case for any platform.

**Review by mbolivar-nordic — DISMISSED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
I don't think we should remove the binding, this is a pretty common binding in linux and thus I think valid for Zephyr as well.

**Comment by carlocaione** [comment]
> I don't think we should remove the binding, this is a pretty common binding in linux and thus I think valid for Zephyr as well.

I can keep the binding but the rest must really go.

**Review by gmarull — DISMISSED** [review]

**Comment by gmarull** [comment]
> > I don't think we should remove the binding, this is a pretty common binding in linux and thus I think valid for Zephyr as well.
> 
> I can keep the binding but the rest must really go.

I see no point on keeping unused bindings, so I'd just remove them.

**Comment by carlocaione** [comment]
@mbolivar-nordic last word is yours. Should we keep the binding or remove it?

**Review by mbolivar-nordic — DISMISSED** [review]
Removing the zephyr-specific binding sends a strong message that we no longer support it. This can be reverted if we ever want to support it again IMO.

**Comment by carlocaione** [comment]
> Removing the zephyr-specific binding sends a strong message that we no longer support it.

So if we want to remove this I need to force push again. Brace yourselves (and ACK this again later :)

**Review by gmarull — APPROVED** [review]

**Comment by galak** [comment]
> Removing the zephyr-specific binding sends a strong message that we no longer support it. This can be reverted if we ever want to support it again IMO.

What is Zephyr specific about the binding?  We have in tree .dts files that use `reserved-memory` nodes:

```
samples/subsys/ipc/ipc_service/icmsg/boards/nrf5340dk_nrf5340_cpuapp.overlay:   reserved-memory {
samples/subsys/ipc/ipc_service/icmsg/remote/boards/nrf5340dk_nrf5340_cpunet.overlay:    reserved-memory {
samples/subsys/ipc/ipc_service/static_vrings/boards/nrf5340dk_nrf5340_cpuapp.overlay:   reserved-memory {
samples/subsys/ipc/ipc_service/static_vrings/remote/boards/nrf5340dk_nrf5340_cpunet.overlay:    reserved-memory {
samples/tfm_integration/psa_crypto/boards/nrf9160dk_nrf9160_ns.overlay: reserved-memory {
samples/tfm_integration/tfm_ipc/boards/nrf9160dk_nrf9160_ns.overlay:    reserved-memory {
boards/arm/actinius_icarus/actinius_icarus_common.dts:  reserved-memory {
boards/arm/actinius_icarus_bee/actinius_icarus_bee_common.dts:  reserved-memory {
boards/arm/actinius_icarus_som/actinius_icarus_som_common.dts:  reserved-memory {
boards/arm/bl5340_dvk/bl5340_dvk_cpuapp_common.dts:     reserved-memory {
boards/arm/bl5340_dvk/bl5340_dvk_shared_sram_planning_conf.dts: reserved-memory {
boards/arm/bl5340_dvk/pre_dt_board.cmake:# - /reserved-memory/image@20000000 & /reserved-memory/image_s@20000000
boards/arm/circuitdojo_feather_nrf9160/circuitdojo_feather_nrf9160_common.dts:  reserved-memory {
boards/arm/lpcxpresso55s69/lpcxpresso55s69.dtsi:        reserved-memory {
boards/arm/mps2_an521/mps2_an521_ns.dts:        reserved-memory {
boards/arm/mps2_an521/mps2_an521_remote.dts:    reserved-memory {
boards/arm/mps3_an547/mps3_an547_ns.dts:        reserved-memory {
boards/arm/nrf5340dk_nrf5340/nrf5340_cpuapp_common.dts: reserved-memory {
boards/arm/nrf5340dk_nrf5340/nrf5340_shared_sram_planning_conf.dts:     reserved-memory {
boards/arm/nrf5340dk_nrf5340/pre_dt_board.cmake:# - /reserved-memory/image@20000000 & /reserved-memory/image_s@20000000
boards/arm/nrf9160dk_nrf9160/nrf9160dk_nrf9160_common.dts:      reserved-memory {
boards/arm/sparkfun_thing_plus_nrf9160/sparkfun_thing_plus_nrf9160_common.dts:  reserved-memory {
boards/arm/thingy53_nrf5340/pre_dt_board.cmake:# - /reserved-memory/image@20000000 & /reserved-memory/image_s@20000000
boards/arm/thingy53_nrf5340/thingy53_nrf5340_common.dts:        reserved-memory {
boards/arm/thingy53_nrf5340/thingy53_nrf5340_shared_sram_planning_conf.dts:     reserved-memory {
```

So why would we remove the binding?

**Comment by carlocaione** [comment]
> So why would we remove the binding?

That has nothing to do with this PR. We are removing support for nodes with **compatible** `reserved-memory`, like:
```
compatible = "reserved-memory";
```

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by galak** [comment]
Ah, sorry, completely misunderstood what was going on here.

**Review by galak — APPROVED** [review]

**Pull request merged**
