### PR TITLE
arch/x86: remove support for IAMCU ABI

### LINKED ISSUE #17888: arch/x86: remove IAMCU ABI support
We no longer have any real targets that use this ABI, only a qemu target.  We should remove support to clean up the arch code.

### PR DESCRIPTION
**Pull request by ghost**
This ABI is no longer required by any targets and is deprecated.

Fixes: #17888

Signed-off-by: Charles E. Youse <charles.youse@intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Comment by galak** [comment]
I take this PR to mean its ok to drop the iamcu toolchain build from SDK-ng.

**Comment by gnuless** [comment]
> I take this PR to mean its ok to drop the iamcu toolchain build from SDK-ng.

Yep.

**Review by dbkinder — APPROVED** [review]
doc changes LGTM.  remember to add this to the 2.0 release notes

**Comment by gnuless** [comment]
> doc changes LGTM. remember to add this to the 2.0 release notes

Added a commit to update the release notes for this feature removal.

**Comment by gnuless** [comment]
> Added a commit to update the release notes for this feature removal.

@dbkinder I've backed out this commit since this is marked for 2.1, not 2.0

**Comment by dbkinder** [comment]
doh. OK.

**Pull request merged**
