### PR TITLE
fix issues with soc rename: intel_adsp/ace30/ptl

### LINKED ISSUE #78931: SOF module sample tests broken in Zephyr main for ace30_ptl
**Describe the bug**
In https://github.com/zephyrproject-rtos/zephyr/commit/a654bfbdfa002ac5ab32d8593d762f5ef3dc4868 the ace30_ptl SOC kconfig and twister identifiers were renamed. But the SOF module uses the old ones still.
This broke Zephyr's main CI:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11009734491/job/30570116372

**To Reproduce**

**Expected behavior**
No broken tests in main CI
=> No uses of those renamed kconfig options and identifiers in modules

**Impact**
Broken main CI

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11009734491/job/30570116372

**Environment (please complete the following information):**

 - OS: Linux, Ubuntu 22.04 CI
 - Toolchain (e.g Zephyr SDK, ...): N/A
 - Commit SHA or Version used: main now: 45727b5fe141624a03866ff694c563830a26dfa4

**Additional context**
Introduced in https://github.com/zephyrproject-rtos/zephyr/pull/78474

### PR DESCRIPTION
**Pull request by nashif**
- soc: intel_adsp: rename missing file during compilation
- manifest: update SOF revision

Fixes #78931

### CODE REVIEW

**Review by gbernatxintel — APPROVED** [review]

**Comment by aescolar** [comment]
@nashif maybe this also needs updating(?)
xtensa-build-zephyr.py
94: "intel", "intel_adsp/ace30_ptl", 
100: "intel", "intel_adsp/ace30_ptl_sim",

**Comment by nashif** [comment]
> @nashif maybe this also needs updating(?)
> xtensa-build-zephyr.py
> 94: "intel", "intel_adsp/ace30_ptl",
> 100: "intel", "intel_adsp/ace30_ptl_sim",

yes, but this is not used in our CI or zephyr, this is done from SOF, so it wont break anything from our side of things in this PR.

Will do the update as a followup one CI is unblocked

**Review by aescolar — APPROVED** [review]

**Comment by gbernatxintel** [comment]
> @nashif maybe this also needs updating(?) xtensa-build-zephyr.py 94: "intel", "intel_adsp/ace30_ptl", 100: "intel", "intel_adsp/ace30_ptl_sim",

Yes, but I changed it in the sof repo

https://github.com/thesofproject/sof/pull/9475/files#diff-daebe2b740a448f2617ecb57b6bb2ac998b0ba033b67552559b5b1344f0ee1de

**Review by nordicjm — APPROVED** [review]

**Comment by nashif** [comment]
> Yes, but I changed it in the sof repo
> 
> [thesofproject/sof#9475 (files)](https://github.com/thesofproject/sof/pull/9475/files#diff-daebe2b740a448f2617ecb57b6bb2ac998b0ba033b67552559b5b1344f0ee1de)

yeah, will update sof module once this is merged

**Review by tmleman — APPROVED** [review]

**Review by softwarecki — APPROVED** [review]

**Pull request merged**
