### PR TITLE
Bluetooth: CAP: Implement bt_cap_initiator_unregister_cb

### PR DESCRIPTION
**Pull request by Thalley**
Implement function to unregisterd the CAP initiator callbacks.

### CODE REVIEW

**Comment by larsgk** [comment]
Just curious - what triggered the need to be able to unregister? (also, would we need the same for other modules?)

**Comment by Thalley** [comment]
> Just curious - what triggered the need to be able to unregister? (also, would we need the same for other modules?)

Sorry for not adding that to the commit log. 
In order to run unit tests, we need to be able to restore states to a known place, such as "no callbacks registered". The unit tests for the CAP initiator is being added by https://github.com/zephyrproject-rtos/zephyr/pull/73520

**Review by larsgk — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
LGTM

On a related note, some of the other modules use the sys_slist_t for storing a list of callbacks, should we use that for this module as well?

**Comment by Thalley** [comment]
> LGTM
> 
> On a related note, some of the other modules use the sys_slist_t for storing a list of callbacks, should we use that for this module as well?

Perhaps. 

The callbacks are only informative, and thus can be a list. 
On the other hand, it's unlikely that CAP will be called from multiple applications. 

I don't have a strong opinion on whether we should make them lists or not.

**Pull request merged**
