### PR TITLE
Revert 71718 and fix 71814

### LINKED ISSUE #71814: tests/net/all fails in CI due to build warning
**Describe the bug**
tests/net/all  (and others that build with CONFIG_PTHREAD) will build with a warning.
Given CI treating warnings as errors this will fail CI.

**To Reproduce**
1. mkdir build && cd build
2. cmake -GNinja -DBOARD=qemu_x86 ../tests/net/all
2. ninja

**Expected behavior**
No build warnings

**Impact**
Failing CI in main and for PRs which trigger these tests.

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/8799555855/job/24148965903#step:11:531

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 22.04)
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: main as of now a1dd9a5f6e562a11edc238e3af76dd64caddca83

**Additional context**
Introduced by 6e66aa1f7c15792a4f173355d05f6feb907811e5

### PR DESCRIPTION
**Pull request by aescolar**
This PR:
https://github.com/zephyrproject-rtos/zephyr/pull/71718
introduced a regression breaking CI:
https://github.com/zephyrproject-rtos/zephyr/issues/71814
Let's just revert it, and let that PR be submitted again with a proper fix.

Another quick fix just initializing the variable (to pacify the compiler) was sent in #71813
but there was valid concerns about the code having issues we are just masking. So let's revert the PR instead.

(Note the original PR did not respect the 2 working days review time frame)

Fixes #71814

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by aescolar** [comment]
There was an indentation issue in the original code the revert uncovered triggering checkpatch.
The revert commit now also fixes that indentation issue.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by ycsin — DISMISSED** [review]
This seems like a really minor issue, can we please hold this off for a while? I'm working on a fix now

EDIT: see #71828

**Comment by aescolar** [comment]
@ycsin the PR you refer to is an exact duplicate of https://github.com/zephyrproject-rtos/zephyr/pull/71813 which has not been merged after 2 developers raised concerns about just pacifying the compiler and masking a likely issue in the code.
Please remove your rejection of this PR.
This failure is breaking main and stopping other merges.
The original PR can be resubmitted and reviewed calmly after.

**Comment by cfriedt** [comment]
> @ycsin the PR you refer to is an exact duplicate of #71813 which has not been merged after 2 developers raised concerns about just pacifying the compiler and masking a likely issue in the code.

Just to stick up for @ycsin - there is no other issue in the code. This would have fixed it (and yes, it is just pacifying the compiler).

Sorry I did not get to it earlier, but I'm in bringup at the moment and am otherwise trying to deal with a minor injury.

For clarification, the issue was reproducible with
```shell
west build -p auto -b qemu_riscv64 -t run tests/posix/common -- -DCONFIG_PTHREAD_LOG_LEVEL_DBG=y
```

I will resubmit the original PR.

**Pull request merged**
