### PR TITLE
Implement bus locking on SAM0 I2C

### PR DESCRIPTION
**Pull request by attie-argentum**
After experiencing a few deadlocks, it was discovered that this bus does not implement any form of mutual exclusion... this patch addresses this and resolves potential deadlocks.

In my situation, we have an I/O expander with LEDs attached, and a charger controller... polling the charge controller, and updating LED state "_occasionally stopped working_" (exacerbated by more LED activity), along with all other items in the system work queue stopping.

After some digging, I discovered that there appears to be some clock stretching (I suspect from the I/O expander, though I'm not sure why that would be necessary...), and this often coincides with the fault.

Other drivers implement locking, which seems sensible and appears to fully resolve the issue (e.g: [STM32](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/i2c/i2c_ll_stm32.c#L118)).

---

As a bit of additional context, the charge controller is polled from the system queue, while the LEDs are updated from their own thread. I believe this is key to the issue presenting.

### CODE REVIEW

**Review by teburd — DISMISSED** [review]

**Review by nandojve — DISMISSED** [review]

**Comment by attie-argentum** [comment]
Rebase, for clean merge

**Review by teburd — APPROVED** [review]

**Review by nandojve — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
@teburd I'm not sure about this one. In general the caller should be ensuring that access to a device is done in a thread safe way. Doing this on a case by case basis will lead to inconsistent results across platforms. Are you sure? I would double-check with @tbursztyka

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Temporary NACK until @tbursztyka can comment on what the device driver model expectations are

**Comment by teburd** [comment]
There's no clarity on if its the device or the callers responsibility for synchronization. I've seen both. However for i2c most drivers have internal semaphores for ensuring thread safety as it is today, sam0 here is one of the unexpected ones.

See for example i2c_nrfx_twim.c which has two synchronization semaphores in fact to avoid issues.

**Comment by attie-argentum** [comment]
I also linked to the STM32 driver in the original message as a precursor... I feel it would be "_odd_" to place this responsibility on the user / not on the driver...

Additionally, in this instance, it's not so much about locking the bus, as maintaining sync between the transfer start / end... in my case, I believe a stretched clock gave another thread the opportunity to come in and attempt to make another transfer. [See here](https://github.com/zephyrproject-rtos/zephyr/blob/75387a8ad40809cc82dbe46c5c0b8c17d68526ea/drivers/i2c/i2c_sam0.c#L480-L481).

**Comment by teburd** [comment]
@mbolivar-nordic please look again

**Comment by teburd** [comment]
I've marked the PR as dev-review so we can discuss next week

**Comment by attie-argentum** [comment]
Thanks @teburd - just to confirm, is that [this](https://github.com/zephyrproject-rtos/zephyr/wiki/Zephyr-Committee-and-Working-Group-Meetings#zephyr-dev-meeting) meeting?
Depending on how things go earlier in my day, I might be able to attend on the 17th.

**Review by mbolivar-nordic — APPROVED** [review]
@teburd thanks for looking into this -- I think some commentary from @tbursztyka would be good still, but I won't block if there's precedent in other I2C drivers

**Comment by mbolivar-nordic** [comment]
I'm gonna leave this unmerged for now; it would be good to settle on if we need a general policy if we can do that in next week's dev-review

**Comment by carlescufi** [comment]
> I'm gonna leave this unmerged for now; it would be good to settle on if we need a general policy if we can do that in next week's dev-review

oops sorry @mbolivar-nordic, was on a merge binge and took this one in.

**Comment by sslupsky** [comment]
@attie-argentum I realize this PR is merged but shouldn't the lock be placed ahead of the var assignments here?

https://github.com/zephyrproject-rtos/zephyr/blob/be1380cc51bd872a5b0e8114cd60bddc37b863c5/drivers/i2c/i2c_sam0.c#L392-L395


It appears to me if another transaction is initiated, it could corrupt the driver's copy of the msg.

**Comment by attie-argentum** [comment]
@sslupsky - that looks like a very fair comment to me... fancy making a PR?

**Comment by sslupsky** [comment]
@attie-argentum I could do so but might take a while.  I am in the middle of migrating a bunch of drivers from 2.3 to 3.1.  One of the surprises is the existence of this PR which addresses an issue I raised af few years ago.  I submitted a PR back then to fix the problem but the PR didn't get any attention so I closed it.  As I read these comments about thread safety I think it was the same issue then.  But, you have a friend in @carlescufi, as he merged it.  So, thank you for finally getting this issue resolved in the tree.

There are a couple another issues related to this driver that need to be resolved.  One is power management.  When the transfer gets underway, if there is nothing else going on the kernel will idle and, if you sleep during idle, it create long delays.  I got around the issue by using a busy wait during the transfer.  However, it looks like there is a way to tell the kernel that the driver is busy now and prevent kernel idle from putting the mcu to sleep.  I need to do a little work on this an test it out.

Finally, the clock configuration for sam0 needs some attention.  There is no gclk configuration in the device tree.  This is necessary for the I2C and UART drivers because if you want to use the I2C or UART to wake from sleep, you need to configure a gclk to connect to GCLK_SLOW.

The last thing in my existing driver that has not made its way into the tree is support for I2C slave mode.

**Comment by attie-argentum** [comment]
See #48766

**Comment by sslupsky** [comment]
@attie-argentum Thank you for the update.

**Pull request merged**
