### PR TITLE
tests: Bluetooth: Upload Launch Studio Project and ICS

### PR DESCRIPTION
**Pull request by cvinayak**
Uploaded the Bluetooth Launch Studio generated projects and
ICS files. These files can be imported into Bluetooth users
Launch Studio, with their Bluetooth SIG account, and
generate the test plans.

This file provide detailed information in Launch Studio of
the supported Core features, Host Services and Profiles,
and Audio services.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by sjanc** [comment]
Does this match core host (GAP, GATT, SM, L2CAP) features we tests with autopts ? https://github.com/intel/auto-pts/tree/master/autopts/workspaces/zephyr/zephyr-master

**Comment by cvinayak** [comment]
> Does this match core host (GAP, GATT, SM, L2CAP) features we test with autopts ? https://github.com/intel/auto-pts/tree/master/autopts/workspaces/zephyr/zephyr-master

Yes, but also includes the audio services we plan to test, prepared by @MariuszSkamra 

Should add `_planned` or `_audio` as a suffix? and we add new files for current ICS used in autopts? (you can send a PR with those files)

**Review by kruithofa — APPROVED** [review]

**Comment by sjanc** [comment]
are those files correct?  I'm not able to import any of the bls files into launch studio...
Also tried importing host ICS configuration but none is set...

**Comment by cvinayak** [comment]
> are those files correct? I'm not able to import any of the bls files into launch studio... Also tried importing host ICS configuration but none is set...

It could be the line-endings... could you try `unix2dos` on the files and check if you can import it?

**Comment by sjanc** [comment]
yeap, unix2dos did the trick

**Comment by cvinayak** [comment]
> yeap, unix2dos did the trick

Should I covert it back to DOS line endings and have the compliance checks failing as exception to this PR?

**Comment by carlescufi** [comment]
@sjanc please take a look

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
