### PR TITLE
hack to generate structs

### PR DESCRIPTION
**Pull request by galak**
Toying with the idea, so hacked something to show the ability to generate struct's from DT nodes.  Not sure if this is useful or not, but wanted to put it out there for thought.

### CODE REVIEW

**Comment by pabigot** [comment]
Might have potential but we need to see how it looks when things are generated, especially for complex node content and non-required properties.

**Comment by galak** [comment]
> Might have potential but we need to see how it looks when things are generated, especially for complex node content and non-required properties.

Yeah, we should really be generating this based on the binding not on the node itself.

**Comment by galak** [comment]
Could see some value for pinmux.

**Comment by pabigot** [comment]
> Yeah, we should really be generating this based on the binding not on the device node itself.

I didn't realize it wasn't based on the binding.  Yes, it should come from the binding and go into some header somewhere that need only be included by modules that need it.

**Comment by mbolivar** [comment]
Agree that generating structs from a node should come from the binding.

I also hope we can take this new development as a chance to get away from the label property being so central, and find a solution for emitting structures which convert phandles to real pointers to the corresponding struct devices.

**Pull request closed without merging**
