### PR TITLE
tests: bluetooth: tester: Enable BT_TINYCRYPT_ECC for nRF5340

### LINKED ISSUE #74505: Bluetooth LE Audio qualification tests are failing
**Describe the bug**

All LE Audio related Bluetooth qualification tests are failing on nRF5340 due to missing LE SC support enabled.

**To Reproduce**

Run LE Audio Bluetooth tests on autoPTS.

**Expected behavior**
Tests shall pass.

**Impact**
Zephyr Bluetooth host qualification is affected

**Additional context**
Regression introduced by https://github.com/zephyrproject-rtos/zephyr/pull/73378

### PR DESCRIPTION
**Pull request by sjanc**
This needs to be enabled in nRF53 CPUAPP for LE SC support to be enabled.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/74505

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr AICS/SR/SPE/BI-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/74500#issuecomment-2176348135, board: nrf53, estimated start time: 17:13:25, test case count: 1, estimated duration: 0:00:22<details><summary>Test cases to be run</summary>AICS/SR/SPE/BI-01-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>AICS    AICS/SR/SPE/BI-01-C             PASS</details>

**Comment by sjanc** [comment]
this fix massive regression with LE Audio PTS tests

**Review by Thalley — APPROVED** [review]

**Comment by Thalley** [comment]
> this fix massive regression with LE Audio PTS tests

@sjanc we probably need to create a GH bug issue in order to get this merge during the feature freeze.

**Comment by sjanc** [comment]
fixes https://github.com/zephyrproject-rtos/zephyr/issues/74505

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
