### PR TITLE
GNSS: Remove redundant and improper periodic config API

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
The GNSS device driver API includes an API for setting the periodic power configuration at runtime. This API is not used in-tree, ~and is antithetical to the pm device subsystem~ and is not complex enough to support the variation of tracking and power modes provided by vendors.

### CODE REVIEW

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by JordanYates** [comment]
The challenge here is that GNSS modems can have sophisticated power management configuration that simply cannot be replicated by an application.

Defining the PM states for GNSS to be `ACTIVE==TRACKING` and `SUSPENDED==INACTIVE` is problematic because there is no API space left for features like cyclic tracking. For example
image

My feeling is that all of the above image should be defined as the `ACTIVE` state, while the `SUSPENDED` state should be for "GNSS is never attempting to get a fix".

In that setup, the periodic config API does not conflict with PM, and is instead just a different 'flavor' of `ACTIVE`.

**Comment by bjarki-andreasen** [comment]
@JordanYates Even in that case, this API is not nearly complex enough to support it :)

Being able to fully support, "auto tracking" I'm gonna call it, mixed in with power modes, like high accuracy, low power, and the odd and plentiful variations of those, is from my research not feasible with a generic API (although you are welcome to prove me wrong :)), the solutions provided by vendors is simply to varied.

Device drivers can expose such configurations in device specific APIs, as long as they, as you propose, don't conflict with the PM state, meaning it can't go to "deep sleep" or similar while resumed as this will not allow the application to interact with the GNSS until it wakes up again...

IMO device drivers will become too complex quickly as they have to deal with the different power modes a modem can be in at any time, for example: user wants to configure fix rate: Is the modem PM resumed, is the modem actually resumed (ready to receive commands), if not, is it in deep sleep? if it is, is a potential "force wakeup" gpio connected?, if it is, wake it up first, then send command. I'm being a bit pessimistic but this was something I chose not to implement for the Quectel LC7xG device driver, for which this exact scenario is relevant.

**Comment by JordanYates** [comment]
Oh I don't disagree that providing a generic API is probably impossible, and that the removed API isn't great.
Just that the documented reasoning for removing it should not be because it conflicts with PM, because IMO it doesn't.

It's easy to see the various "auto tracking" modes as different flavors of `ACTIVE`, in the same way that an IMU can be configured in a multitude of different ways while still being considered `ACTIVE`.

**Comment by bjarki-andreasen** [comment]
@JordanYates Updated the description :)

**Review by JordanYates — DISMISSED** [review]

**Comment by jukkar** [comment]
Should the change be mentioned in migration guide?

**Comment by tomi-font** [comment]
> Should the change be mentioned in migration guide?

+1

**Review by tomi-font — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by bjarki-andreasen** [comment]
Rebased and corrected indentation of the `The u-blox M10` migration guide entry

**Review by fabiobaltieri — APPROVED** [review]

**Review by tomi-font — APPROVED** [review]

**Pull request merged**
