### PR TITLE
sensors: vl53l1: build_all without the default Kconfig

### LINKED ISSUE #61281: Sensor vl53l1x doesn't compile without CONFIG_VL53L1X_INTERRUPT_MODE=y
NCS 2.4.1 / zephyr 3.3.99

As far as could verify, this is an issue of [vl53l1.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/vl53l1x/vl53l1.c) and occurs also with the current version of that file here in this repository. 

If the CONFIG_VL53L1X_INTERRUPT_MODE is not on, to build reports:

```
.../zephyr/drivers/sensor/vl53l1x/vl53l1.c: In function 'vl53l1x_worker':
.../zephyr/include/zephyr/sys/util.h:224:37: error: 'struct vl53l1x_data' has no member named 'work'
  224 |         ((type *)(((char *)(ptr)) - offsetof(type, field)))
      |                                     ^~~~~~~~
.../zephyr/drivers/sensor/vl53l1x/vl53l1.c:71:49: note: in expansion of macro 'CONTAINER_OF'
   71 |                 struct vl53l1x_data *drv_data = CONTAINER_OF(work, struct vl53l1x_data, work);
```

This is caused by the [conditional definition of vl53l1x_data](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/vl53l1x/vl53l1.c#L38-L47), which contains the field `work` only, if `CONFIG_VL53L1X_INTERRUPT_MODE` is defined.

But that [access to that "conditional field"](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/vl53l1x/vl53l1.c#L68-L75) is not guarded from being compiled, it's only guarded from being executed.

In order to fix it, either the definition of `vl53l1x_data` may not contain conditional fields, or all access must be guarded from being compiled by `#ifdef CONFIG_VL53L1X_INTERRUPT_MODE`.

### PR DESCRIPTION
**Pull request by fouge**
the `vl53l1x` driver doesn't compile in case the default Kconfig is not used, [see action](https://github.com/zephyrproject-rtos/zephyr/actions/runs/5210133122/jobs/9400839680?pr=59058)

Specifically, when one of this config is set to `n`
```
CONFIG_VL53L1X_INTERRUPT_MODE
CONFIG_VL53L1X_XSHUT
```

This branch aims to fix it

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]

**Comment by fouge** [comment]
too bad this didn't make it into 3.4 😬

**Comment by fouge** [comment]
@nashif pinging you to merge this one :)

**Comment by danielstuart14** [comment]
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/61281

**Comment by MaureenHelm** [comment]
@avisconti will you please take a look?

**Comment by MaureenHelm** [comment]
> @avisconti will you please take a look?

@avisconti @erwango ping

**Review by erwango — DISMISSED** [review]

**Review by avisconti — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@fouge this needs a rebase

**Comment by fouge** [comment]
@fabiobaltieri done

**Review by erwango — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by avisconti — APPROVED** [review]

**Pull request merged**
