### PR TITLE
drivers: bbled: mchp: BBLED low power enabled

### PR DESCRIPTION
**Pull request by Manimaran-A**
Updated the driver to support low power mode.
Introduced "enable-low-power" flag in device tree to control(on/off) the low power mode.

If flag added in DTS, during sleep BBLED will switch off the LEDs. Otherwise BBLED will continue the configured blinking pattern on LEDs.

### CODE REVIEW

**Comment by simonguinot** [comment]
Hi @Manimaran-A. Is it ready to be reviewed ?

**Comment by Manimaran-A** [comment]
> Hi @Manimaran-A. Is it ready to be reviewed ?

**Comment by Manimaran-A** [comment]
@simonguinot, update is done. You could review the changes.

**Review by jvasanth1 — APPROVED** [review]

**Review by simonguinot — CHANGES_REQUESTED** [review]
Hi @Manimaran-A,

Sorry for the delay, I have been busy lately.

I am not familiar with the PM API and I wonder if introducing a specific DT property to disable PM support in the driver is the right way to go. I can't find any other driver using this method.

So let's ask the PM folks for advice.

**Comment by simonguinot** [comment]
Hi @ceolin and PM collaborators. Please have a look at this PR. Is it correct to introduce/use a DT property to disable PM support for a driver ?

**Comment by Manimaran-A** [comment]
There may be two types of product requirement in SUSPEND state,
1. Keep blink the LED
2. Switch off the LED

So to provide control to the user to switch off/ON the LED, created flag in device tree.
With the help of that user can control the LED behavior in SUSPEND state.

**Comment by simonguinot** [comment]
> There may be two types of product requirement in SUSPEND state,
> 
>     1. Keep blink the LED
> 
>     2. Switch off the LED
> 
> 
> So to provide control to the user to switch off/ON the LED, created flag in device tree. With the help of that user can control the LED behavior in SUSPEND state.

I understand the use cases you describe. In some situation you may want to keep the LEDs working while the device is suspended. I simply wonder if there is another way to achieve that. Maybe the PM subsystem offers (or should offer) an API to disable PM for a device/driver. I'd like to have more comments here.

**Comment by simonguinot** [comment]
> > There may be two types of product requirement in SUSPEND state,
> > ```
> > 1. Keep blink the LED
> > 
> > 2. Switch off the LED
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So to provide control to the user to switch off/ON the LED, created flag in device tree. With the help of that user can control the LED behavior in SUSPEND state.
> 
> I understand the use cases you describe. In some situation you may want to keep the LEDs working while the device is suspended. I simply wonder if there is another way to achieve that. Maybe the PM subsystem offers (or should offer) an API to disable PM for a device/driver. I'd like to have more comments here.

And if the solution is really adding a DT or a Kconfig option, then maybe we should make it available for all the LED drivers and not just `led_mchp_xec`. After all the use cases you describe could apply to other devices...

**Comment by simonguinot** [comment]
@Manimaran-A As discussed in https://github.com/zephyrproject-rtos/zephyr/pull/58485 with @scottwcpg and @albertofloyd the `led_mchp_xec` driver should be removed. So do you agree to close this PR ?

**Comment by Manimaran-A** [comment]
Agree, closing the PR.

**Pull request closed without merging**
