### PR TITLE
doc: extensions: samples: Add "browse source code" button

### PR DESCRIPTION
**Pull request by kartben**
https://builds.zephyrproject.io/zephyr/pr/78960/docs/samples/hello_world/README.html

One of the first thing one wants to do when reading about a code sample is checking the code itself. This commit adds a button to directly take the user to the code sample's source code on GitHub.

image

### CODE REVIEW

**Review by gmarull — APPROVED** [review]

**Comment by nashif** [comment]
With this, do we still need the "Open on Github" on the top? It is becoming redundant now.

**Comment by kartben** [comment]
> With this, do we still need the "Open on Github" on the top? It is becoming redundant now.

Open on GitHub is on all pages, and is for opening the *doc* page. What's more, it's not visible on narrow screens (mobile).
For code samples specifically, what one wants is the code of the sample, and having it systematically an extra, non-necessarily obvious for newcomers, click away is not great (i.e people need to Open on GitHub, then *always* navigate one level up, granted they actually realize they can/should).
To your point though, there is certainly*some* redundancy indeed, but given that the new button is much more prominent and clearly states its associated action, I don't see it as an issue

**Review by nordicjm — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Comment by nashif** [comment]
> To your point though, there is certainly_some_ redundancy indeed, but given that the new button is much more prominent and clearly states its associated action, I don't necessarily see it as an issue.

ok, in general however and directly something for this PR, the header is very busy and depending on the page you are on, it can overlap or wrap, maybe reduce both items to just the icons? The redundancy will be slightly hidden :)

image

**Comment by kartben** [comment]
> > To your point though, there is certainly_some_ redundancy indeed, but given that the new button is much more prominent and clearly states its associated action, I don't necessarily see it as an issue.
> 
> ok, in general however and directly something for this PR, the header is very busy and depending on the page you are on, it can overlap or wrap, maybe reduce both items to just the icons? The redundancy will be slightly hidden :)
> 
> image
> 

Agreed. Having just the icons probably works, yes. And the wrapping can probably be limited by implementing ellipses in the breadcrumb, when it's getting too long (for example: "Docs / Latest » Samples and Demos » ... » AWS IoT Core MQTT" instead of "Docs / Latest » Samples and Demos » Networking » IoT Cloud » AWS IoT Core MQTT").

BTW, just to clarify, you meant something *not* for this PR, yes?

**Review by Thalley — APPROVED** [review]

**Comment by nashif** [comment]
> BTW, just to clarify, you meant something _not_ for this PR, yes?

yes, oops

**Pull request merged**
