### PR TITLE
drivers: fix race condition in SPI-based HCI driver

### PR DESCRIPTION
**Pull request by yang325**
Give the semaphore after transceiving the message.

Signed-off-by: Freddie Yang <freddie.yang325@outlook.com>

### CODE REVIEW

**Comment by jori-nordic** [comment]
Could you describe what's the race condition ? Your description only states the changes.

**Comment by yang325** [comment]
SPI is used in two threads -- void bt_spi_rx_thread(void) and bt_spi_send() called by hci_tx_thread().
Semaphore 'sem_busy' is to make sure SPI is locked when used.
While bt_spi_send() unlock it before transceiving the message.

**Comment by yang325** [comment]
Could you kindly remind me if it's clear? @jori-nordic

**Comment by jori-nordic** [comment]
> Could you kindly remind me if it's clear? @jori-nordic

Yes, sorry I got busy with other things yesterday. Approved.

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Pull request merged**
