### PR TITLE
samples: drivers: soc_flash_nrf5 fix missing flash write access

### PR DESCRIPTION
**Pull request by nvlsianpu**
By default CONFIG_MPU_ALLOW_FLASH_WRITE=n so example have been must
falling on any write to flash.
This patch adds CONFIG_MPU_ALLOW_FLASH_WRITE=y to project configuration.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
cc @carlescufi

**Review by carlescufi — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
>By default CONFIG_MPU_ALLOW_FLASH_WRITE=n so example have been must
falling on any write to flash.

so the example must have been failing on any write to flash.

**Comment by nvlsianpu** [comment]
updated

**Comment by carlescufi** [comment]
@nvlsianpu, I still see the old commit message?

**Comment by nvlsianpu** [comment]
sorry - it is strange day today.

**Review by carlescufi — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
