### PR TITLE
tests: net: socket: reuseaddr: some board don't work

### PR DESCRIPTION
**Pull request by Desvauxm-st**
boards nucleo_f429zi, nucleo_f746zg, nucleo_h743zi don't work
add platform_exclude for those boards

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Could you elaborate in the commit message what is the issue? The commit message should answer the question "why this commit is needed".

**Comment by Desvauxm-st** [comment]
With those 3 boards it don't work 
see after the console error message:

image

**Comment by jukkar** [comment]
I think we should not blindly exclude devices, perhaps there is an error in the test etc.

**Comment by Desvauxm-st** [comment]
@jukkar 
yes
see after  the bug :   
tests: net: socket: reuseaddr: some board don't work #63979

**Comment by jukkar** [comment]
I just wonder why they do not work, these boards seem to have Ethernet port in them. I am suspecting that the board Ethernet interface gets activated when running the test which then confuses the test results. This has been a common thing in the past. The solution is to disable the built-in Ethernet port when running the test, not just blindly disable the test.

**Comment by jukkar** [comment]
For example, the `drivers/ethernet/Kconfig.nxp_s32_netc` has added a dependency `depends on !NET_TEST` which should disable the built-in Ethernet if we run the unit test in the device. Could you check if setting something like this helps?

**Comment by Desvauxm-st** [comment]
@jukkar
I try this works with the current main as #64180 is merged.
and now it's works

**Pull request closed without merging**
