### PR TITLE
net: mdns + dns_sd: fix regression that breaks ptr queries

### PR DESCRIPTION
**Pull request by cfriedt**
While adding support for service type enumeration, a regression was introduced which prevented mDNS ptr query responses.

1. There was an off-by-one error with label size checking
2. Valid queries were failing to match in `dns_rec_match()` due to not checking for either NULL or 0 "wildcard" port 

Fixes #39284

### CODE REVIEW

**Comment by cfriedt** [comment]
Screen Shot 2021-10-08 at 3 01 23 PM
Screen Shot 2021-10-08 at 3 01 04 PM

**Review by jukkar — APPROVED** [review]
One minor nit about the commit subject, it would be great if `net:` is added as a prefix so that it is easier to search network related commits afterwards. Other than that LGTM.

**Comment by cfriedt** [comment]
> One minor nit about the commit subject, it would be great if `net:` is added as a prefix so that it is easier to search network related commits afterwards. Other than that LGTM.

Done!

**Review by pdgendt — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by ghost — APPROVED** [review]
I tested with IMXRT1064_evk and mdns discover softwares dns-sd, avahi-discover and zeroconfservicebrowser. The mdns service discovery functionality is working well. Thank you

However I do get warnings printed out but it doesn't seem to have impact on the functionality.

image

**Pull request merged**
