### PR TITLE
boards: Add counter capability to nordic boards

### PR DESCRIPTION
**Pull request by nordic-krch**
Added counter capability to pca10028, pca10040 and pca10056

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
There are a couple more boards that are officially supported by Nordic, can you take a look at those as well @nordic-krch?

**Comment by nordic-krch** [comment]
@carlescufi we rather want to cover all chips than boards. Do we have something official for nrf52810? nrf52810_pca10040?

**Comment by carlescufi** [comment]
@nordic-krch yep, `nrf52810_pca10040` is also officially supported.

**Comment by nordic-krch** [comment]
nrf52810_pca10040 added

**Review by anangl — APPROVED** [review]

**Comment by MaureenHelm** [comment]
Please rebase

**Comment by pabigot** [comment]
@nordic-krch Something doesn't look right: most of the material in this PR has been pushed to the topic-counters branch, rather than to your PR branch.  The only differences remaining are some yaml edits and a Kconfig that overwrites a change that was earlier merged to the topic branch.  Was that intentional?

**Comment by pabigot** [comment]
@MaureenHelm @nordic-krch I'm not sure what's going on; all I know is if I rebase this (unmerged?) PR on topic-counters, I get very few changes.

**Comment by nordic-krch** [comment]
@pabigot this PR is only one commit (https://github.com/zephyrproject-rtos/zephyr/pull/12155/commits/b976948157188f8d6a737da1cf2f889ef0e2c876) with very few changes. I will try to rebase it.

**Pull request merged**
