### PR TITLE
Bluetooth: audio: Add missing 'or' in service declaration

### PR DESCRIPTION
**Pull request by szymon-czapracki**
Fix missing or symbol in service declaration

### CODE REVIEW

**Comment by szymon-czapracki** [comment]
@MariuszSkamra FYI

**Review by Thalley — DISMISSED** [review]

**Comment by Thalley** [comment]
We should add `CONFIG_BT_PAC_SRC_LOC_WRITEABLE` and `CONFIG_BT_PAC_SNK_LOC_WRITEABLE` to the shell application

**Review by MariuszSkamra — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

**Comment by Thalley** [comment]
@szymon-czapracki You need to add a proper git commit message (and please also copy that to the PR description).

**Comment by szymon-czapracki** [comment]
> @szymon-czapracki You need to add a proper git commit message (and please also copy that to the PR description).

Done

**Review by Thalley — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

**Pull request merged**
