### PR TITLE
boards: mps2_an385: Exclude platform from networking tests

### PR DESCRIPTION
**Pull request by rlubos**
The platform is known for having unstable system timer with networking enabled (see https://github.com/zephyrproject-rtos/zephyr/issues/48608) causing occasional failures of time-sensitive networking testsuties (TLS, now DHCPv6). Instead of excluding the platform on per-test basis, just exclude the platform from networking testing globally.

### CODE REVIEW

**Comment by rlubos** [comment]
@cfriedt There was a problem with socketpair sample as it used `mps2_an385` as an integration platform. I propose to replace it with `qemu_cortex_m3`.

**Review by jukkar — APPROVED** [review]

**Comment by galak** [comment]
Is the unstable timer in qemu, actual HW or both?

**Comment by rlubos** [comment]
> Is the unstable timer in qemu, actual HW or both?

The problem is best described in the issue I've linked (https://github.com/zephyrproject-rtos/zephyr/issues/48608), I'm afraid I'm not able to provide any more detailed information.

**Review by cfriedt — APPROVED** [review]
Ideally we could get a fix in with Qemu, but I know that can take time.

LGTM 👍

**Comment by gramsay0** [comment]
Should we revert this now that the systick fix is in?

**Pull request merged**
