### PR TITLE
Designware (DW) I2C Slave Support and RPI Pico I2C Support

### PR DESCRIPTION
**Pull request by andrei-edward-popa**

### CODE REVIEW

**Comment by petejohanson** [comment]
Why did this get closed?

**Comment by andrei-edward-popa** [comment]
Sorry @petejohanson, it was my mistake, I did another PR with those modifications.

**Comment by petejohanson** [comment]
> > Why did this get closed?
> 
> Sorry @petejohanson, it was my mistake, I did another PR with those modifications.

Ah, no worries, just wanted to test these changes, and this PR was linked from Discord. I'll find your other PR.

**Comment by andrei-edward-popa** [comment]
> > > Why did this get closed?
> > 
> > 
> > Sorry @petejohanson, it was my mistake, I did another PR with those modifications.
> 
> Ah, no worries, just wanted to test these changes, and this PR was linked from Discord. I'll find your other PR.

https://github.com/zephyrproject-rtos/zephyr/pull/42513/files

**Pull request closed without merging**
