### PR TITLE
ext: hal: unisoc: Import Unisoc uwp5 hal version 0.2.0

### PR DESCRIPTION
**Pull request by easonxiang**
It provides device header files and driver libraries, include
    register definitions and helper functions for uwp5 series soc.

    Origin: unisoc uwp5
    License: Apache-2.0
    URL: https://github.com/unisoc/hal_uwp5/commits/v0.2.0
    commit: 8af994c037dc50df15b383c87a6307c5e07f7f6b
    Purpose: Provide peripheral drivers for Unisoc uwp5 soc
    Maintained-by: External

    Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>

### CODE REVIEW

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
This should be merged after the board support has been merged.

**Comment by easonxiang** [comment]
@SebastianBoe The board 96b_ivy5661 depends on interfaces in HAL libraries provided by this PR. I think this PR should be merged before board support.

**Comment by SebastianBoe** [comment]
All right, we can merge it in that order.

But this PR should not be merged until the other PR is ready to be merged, because there is no point in having HAL support for a board that is not in the tree.

**Comment by easonxiang** [comment]
Got it, thanks!

**Comment by galak** [comment]
I'm closing this PR, and merging it PR #10626 that adds SoC & Board support that uses this HAL.

@carlescufi do you mind making your comment on PR #10626

**Pull request closed without merging**
