### PR TITLE
samples: boards: stm32: fix backup sram memory displays wrong info

### LINKED ISSUE #37658: samples: boards/stm32/backup_sram : needs backup sram enabled in DT to properly display memory region
**Describe the bug**
A clean build of boards/stm32/backup_sram shows some sign of bug:
Displaying wrong info:
-  region name, falls back to `*default*: `
- size gibberish val

**To Reproduce**
1. west build -b nucleo_h723zg samples/boards/stm32/backup_sram/

**Expected behaviour**
Suppose to be 4KB 

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
Memory region         Used Size  Region Size  %age Used
           FLASH:       15756 B         1 MB      1.50%
            SRAM:        4288 B       128 KB      3.27%
            DTCM:          0 GB       128 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%
       *default*:        4952 B 18446744073709551615 B      0.00%
```

Solution:
Have a generic overlay file with enabled `backup_sram`
PR : #37659 

**Environment (please complete the following information):**
 - OS: (Ubuntu 20.04.2 LTS)
 - Toolchain (zephyr-sdk-0.13.0)
 - Commit SHA or Version used (zephyr: 7b9fbcd3b7e932996)

### PR DESCRIPTION
**Pull request by manoj153**
Closes #37658 
have a generic board overlay
Signed-off-by: Manojkumar Subramaniam <manoj@electrolance.com>

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]
Boards that have backup_sram need to enable it, for which case sample will just work. I don't think this "generic overlay" pattern is present in-tree.

**Comment by manoj153** [comment]
> Boards that have backup_sram need to enable it, for which case sample will just work. I don't think this "generic overlay" pattern is present in-tree.

by default as per the convention, I think, `backup_sram` is disabled in the top-level and it's not  even enabled on their respective boards DT `.overlay`  

my thinking was the sample suppose to work just right as possible out-of-box regardless of any stm32 boards given. 

Let me know if you have a better idea.

**Comment by gmarull** [comment]
Boards that have backup SRAM already define it:

https://github.com/zephyrproject-rtos/zephyr/blob/7b9fbcd3b7e93299681fe1c54e35ec787ab58171/boards/arm/nucleo_h743zi/nucleo_h743zi.dts#L155-L157

**Comment by manoj153** [comment]
> Boards that have backup SRAM already enable it:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/7b9fbcd3b7e93299681fe1c54e35ec787ab58171/boards/arm/nucleo_h743zi/nucleo_h743zi.dts#L155-L157

I get your point but the board I'm working on, has a backup SRAM but it'ss not enabled, Ill create a PR accordingly..
Link to board DT 
https://github.com/zephyrproject-rtos/zephyr/blob/7b9fbcd3b7e93299681fe1c54e35ec787ab58171/boards/arm/nucleo_h723zg/nucleo_h723zg.dts

**Comment by gmarull** [comment]
> > Boards that have backup SRAM already enable it:
> > https://github.com/zephyrproject-rtos/zephyr/blob/7b9fbcd3b7e93299681fe1c54e35ec787ab58171/boards/arm/nucleo_h743zi/nucleo_h743zi.dts#L155-L157
> 
> I get your point but the board I'm working on, has a backup SRAM but it'ss not enabled, Ill create a PR accordingly..
> Link to board DT
> https://github.com/zephyrproject-rtos/zephyr/blob/7b9fbcd3b7e93299681fe1c54e35ec787ab58171/boards/arm/nucleo_h723zg/nucleo_h723zg.dts

Yes, you need to update board to support backup SRAM. Can you close this PR, then?

**Pull request closed without merging**
