### PR TITLE
samples/net: small bug-fixes

### PR DESCRIPTION
**Pull request by maksimdrachov**
Addressing issue #36659

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
This raises a question, whether it should rather be the board definition, who provides _some_ random number generator, but we already enable test RNG in other samples, so I guess it's fine to enable it in the others as well.

You need a specific commit format though, to get this patch accepted. Please use `samples: net: ` prefix for the commit title, add some commit body, explaining rationale behind the changes, and add an signoff entry (with `-s` commit option).

**Review by pfalcon — COMMENTED** [review]
@maksimdrachov: Commit message here doesn't comply with Zephyr requirements. There should be a detailed, self-contained description of the change (both nature and reason of), which would be clear to someone (e.g. you) looking at it a year later. Please use `git log` for examples of good commit messages.

**Comment by maksimdrachov** [comment]
I will try to address all the issues as soon as I have some time.

Thanks for the feedback.

**Comment by maksimdrachov** [comment]
Hey,
Could you take a new look at this PR? Thanks!

@rlubos  @pfalcon

**Comment by rlubos** [comment]
@maksimdrachov The commit message still has some issues:
```
UC4 Line exceeds max length (83>72): "This change ensures a succesful built on both examples (tested using nucleo-f756zg)"
```

**Comment by maksimdrachov** [comment]
Yeah, will try to address this immediately

**Comment by maksimdrachov** [comment]
@rlubos 
This should fix it. :)

**Review by rlubos — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
