### PR TITLE
[RFC]drivers: qep: Add headers for qep

### PR DESCRIPTION
**Pull request by rbabub**
This is the header for supporting QEP driver.

A quadrature encoder peripheral (QEP) is a peripheral designed to interface
to a shaft encoder fitted to either a motor shaft or a user interface dial,
as a means to measure rotational speed, direction, and (optionally)
absolute angle of rotation.

Please refer 22.21 of https://cdrdv2.intel.com/v1/dl/getContent/636112 for
details about the IP.

Signed-off-by: Ramesh Babu B <ramesh.babu.b@intel.com>

### CODE REVIEW

**Review by gmarull — COMMENTED** [review]
Without an actual implementation, it's hard to review the API design. A driver and a sample should be included at least.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
We have implemented Quadrature Decoder drivers downstream using the sensor API (sensor channel for count, sensor attributes for configuration, sensor triggers for index pulse etc.).

Please justify why a new API is needed for this particular sensor type.

**Comment by alexanderwachter** [comment]
@rbabub Can you join the API meeting tomorrow? This PR is on the agenda.

**Comment by rbabub** [comment]
> @rbabub Can you join the API meeting tomorrow? This PR is on the agenda.

Ya sure.

**Comment by henrikbrixandersen** [comment]
We already have two quadrature decoder drivers in the tree, both implements the sensor API:
- https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/sensor/qdec_nrfx
- https://github.com/zephyrproject-rtos/zephyr/tree/main/drivers/sensor/qdec_sam

There's also a quadrature decoder sample:
- https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/sensor/qdec

**Comment by alexanderwachter** [comment]
API meeting:

please have a look at the sensor API and see if you could implement it as a sensor.

**Pull request closed without merging**
