### PR TITLE
drivers: uart_gecko: add individual pin locations support

### PR DESCRIPTION
**Pull request by mnkp**
SiLabs SoCs have in general a very uniform architecture, there is however a major difference in how pin locations are defined. Some series like efm32hg, efm32wg allow to set pin location in groups only. E.g. assignment of RX and TX signals to GPIO pins in UART driver can be chosen from a list of predefined combinations. Other series like efr32fg1p, efr32mg12p allow to set pin location individually. E.g. assignment of RX signal to GPIO pin can be chosen independently from the assignment of TX signal.

This commit adds support for configuring individual RX, TX pin locations on SoCs that contain ROUTELOC register.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
I'd rather we remove the 'location' support and only support 'location-{r,t}x'

**Review by chrta — APPROVED** [review]
LGTM and tested on a custom EFM32PG board.

Removing location completely would also be ok, and only have location-tx and location-rx. In that case we should `#error` if `location-tx != location-rx` for the older efm32 series 0 controller.

**Comment by mnkp** [comment]
I removed 'location' from DTS and added compile time errors in the driver in case the location-* values on SoCs that do not support setting individual pin locations are not equal.

**Review by chrta — APPROVED** [review]

**Comment by mnkp** [comment]
Superseded by #12525.

**Pull request closed without merging**
