### PR TITLE
net: tcp: Fix possible deadlock in tcp

### PR DESCRIPTION
**Pull request by neja20**
The tcp_lock and contexts_lock from net_context.c
are really working against each other and can
deadlock under heavy load. There is really no
reason to lock tcp_lock in tcp_conn_alloc()
accessed through net_tcp_get() and
tcp_conn_release() as there is nothing
else that can thread race in these situations.
The only part that needed protection is
slist tcp_conns, which now got the extra lock.

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
I don't think there's a need to introduce a separate mutex, the purpose of `tcp_lock` is to protect shared resources (which could be that it's just the list), let's focus on fixing its usage instead.

Can you elaborate more on the deadlock scenario you've encountered? Looking at this code again after some time, we might indeed should avoid having the `tcp_lock` held when accessing `tcp_conn_new()`, in case some other thread tries to open a new socket at the same time, we are in trouble.

**Comment by neja20** [comment]
The global locks `tcp_lock` and `contexts_lock` are often times called within each other, which is the main problem. My exact case is hard to simulate, although there is a way to reproduce this issue. So for example consider the following scenario. The `rx_q` receives packet and processes it in `tcp_recv()` where it locks the `tcp_lock` and continues to create tcp context in [tcp_conn_new](https://github.com/zephyrproject-rtos/zephyr/blob/8ea1ca73556149c7ca864e6d0c489c0f84115336/subsys/net/ip/tcp.c#L2194), this function needs to get the `net_context` [here](https://github.com/zephyrproject-rtos/zephyr/blob/8ea1ca73556149c7ca864e6d0c489c0f84115336/subsys/net/ip/tcp.c#L2323), which in turn wants to lock the `contexts_lock`.
And the same goes the other way around when some other thread in socket layer [creates a socket](https://github.com/zephyrproject-rtos/zephyr/blob/8ea1ca73556149c7ca864e6d0c489c0f84115336/subsys/net/lib/sockets/sockets.c#L181). Function `net_context_get()` locks `contexts_lock` and tries to alloc a `net_context` [here](https://github.com/zephyrproject-rtos/zephyr/blob/8ea1ca73556149c7ca864e6d0c489c0f84115336/subsys/net/ip/net_context.c#L458C8-L458C19) and the first thing it does is locking the `tcp_lock`. And that is the cause of potential deadlock. To reproduce the issue one could introduce yielding for example in a form of `k_msleep()` after both locks `tcp_lock`, `contexts_lock` [here](https://github.com/zephyrproject-rtos/zephyr/blob/8ea1ca73556149c7ca864e6d0c489c0f84115336/subsys/net/ip/tcp.c#L2117) and [here](https://github.com/zephyrproject-rtos/zephyr/blob/8ea1ca73556149c7ca864e6d0c489c0f84115336/subsys/net/ip/net_context.c#L445) to greatly increase the risk of deadlocking.

I opted for removing the `tcp_lock` from the `net_tcp_get()` as it is already almost thread safe with one exception of the sys_list. That led to introduction of the new `tcp_conns_lock` which allowed me to drop the `tcp_lock` even in other places like `tcp_conn_release()`. I think it is even more efficient as it does not lock the whole chunks of code but only the sys_list. Not to mention the weird locking in `net_tcp_foreach()`

**Comment by jukkar** [comment]
The only place where `tcp_lock` is used in after this change, is the `tcp_recv` so the question Robert and I have is that, do we need that lock there at all, and also could we just use `tcp_lock` instead of introducing a new one for these fixes?

**Comment by rlubos** [comment]
@neja20 Your reasoning around `tcp_conn_new()` sounds perfectly valid, we should not keep the lock for that call, it's unnecessary and can potentially lead to a deadlock. I just don't think we need a new mutex for that, let's just fix the current mutex use. We can narrow it down to protecting list only in other places as well I believe.

As for `net_tcp_foreach()`, again, we should still use the original mutex to protect the list, but I'm not sure we need to unlock it for each cb call indeed. At least I couldn't identify a scenario in the current codebase that could lead to a deadlock.

**Comment by neja20** [comment]
So I dropped the newly introduced mutex and narrowed down the usage of `tcp_mutex`.
I put back the unlocking mechanism in `net_tcp_foreach()` as I am not sure whether it would break anything else.
The `tcp_recv()` seems not to need the `tcp_mutex` after the `net_tcp_foreach()` got the extra locking.
I did a few test runs and it seems to be ok, with the current changes. What do you think?

**Review by rlubos — COMMENTED** [review]
> The tcp_recv() seems not to need the tcp_mutex after the net_tcp_foreach() got the extra locking.

You meant `tcp_conn_alloc()` instead `net_tcp_foreach()` here, right? I don't see relation to `net_tcp_foreach()` in that regard.

> So I dropped the newly introduced mutex and narrowed down the usage of tcp_mutex.
I put back the unlocking mechanism in net_tcp_foreach() as I am not sure whether it would break anything else.
The tcp_recv() seems not to need the tcp_mutex after the net_tcp_foreach() got the extra locking.
I did a few test runs and it seems to be ok, with the current changes. What do you think?

Thank you, I think the current change proposal makes sense.

Just one more request - please squash the two commits to keep the history cleaner.

**Comment by neja20** [comment]
@rlubos  Sorry, I meant the `tcp_conn_search()`, which initially didn't have locks, must be locked now because `tcp_recv` isn't.

Squashed.

**Comment by jukkar** [comment]
@ssharks you did TCP work earlier, are you able to review this too?

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Pull request merged**
