### PR TITLE
manifest: Update hal_nxp to add wifi related change

### PR DESCRIPTION
**Pull request by MaochenWang1**
Update hal_nxp to add wifi related change

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@MaochenWang1 please rebase to fix conflicts

**Comment by MaochenWang1** [comment]
Hi @danieldegrasse  rebased

**Comment by danieldegrasse** [comment]
> Hi @danieldegrasse rebased

Please rebase to clear conflicts (sorry, we have a lot of churn in the manifest right now)

**Comment by dleach02** [comment]
@MaochenWang1 HAL PR merged and I've updated this PR with the new SHA

**Review by mmahadevan108 — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]

**Pull request merged**
