### PR TITLE
Bluetooth: A2DP: Fix mistake parameter

### LINKED ISSUE #75556: Bluetooth: A2DP: bt_a2dp_stream_establish use the wrong internal parameter
**Describe the bug**
When implementing the codes, the copy-paste leads the wrong parameter. In the normal test, it may be not found because the used wrong parameter (set_config_param) may be set in the previous step (bt_a2dp_stream_config).

**To Reproduce**
1. cmake -DBOARD=board\_xyz
2. west build -b mimxrt1170_evk@B/mimxrt1176/cm7 tests/bluetooth/shell -DCONF_FILE="prj_br.conf"
3. the bluetooth shell demo doesn't support mimxrt1170_evk@B/mimxrt1176/cm7 yet, need to support it as zephyr\samples\bluetooth\handsfree_ag\boards\

**Expected behavior**

**Impact**
If calling bt_a2dp_stream_config and bt_a2dp_stream_establish from different sides, the bt_a2dp_stream_establish doesn't work.

### PR DESCRIPTION
**Pull request by MarkWangChinese**
need to use the value from stream.

fixes #75556

### CODE REVIEW

**Comment by jhedberg** [comment]
@MarkWangChinese could you open a bug report (GitHub issue) for this? That's normally required this late in the feature freeze in order for fixes to get merged.

**Comment by MarkWangChinese** [comment]
> @MarkWangChinese could you open a bug report (GitHub issue) for this? That's normally required this late in the feature freeze in order for fixes to get merged.

Opened and update the comment to link it.

**Review by Thalley — CHANGES_REQUESTED** [review]
The commit message needs to be improved. 

Why is the current value incorrect, and why is the new one correct?

**Comment by MarkWangChinese** [comment]
> The commit message needs to be improved.
> 
> Why is the current value incorrect, and why is the new one correct?

Updated.

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by carlescufi** [comment]
@lylezhu2012 please review

**Review by lylezhu2012 — APPROVED** [review]

**Pull request merged**
