### PR TITLE
doc: xenvm: Update GIC-related info and build steps

### PR DESCRIPTION
**Pull request by rshym**
- update info regarding GIC
- add instructions for building by `moulin`

### CODE REVIEW

**Comment by SgrrZhf** [comment]
Thanks for contributing.

I followed the instructions in this doc and tried to build it, but I got an error.
It seems that `ssh://git@gitpct.epam.com/epmd-aepr/img-proprietary` is an private repo. 
I noticed that this one is defined in `prod-devel-rcar.yaml`, should users change this URL to the public repo manually?

```
$ ninja image-full
[11/34] git clone
FAILED: yocto/proprietary
GIT_SSH_COMMAND='ssh -o BatchMode=yes' git clone -q ssh://git@gitpct.epam.com/epmd-aepr/img-proprietary yocto/proprietary && touch yocto/proprietary
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[16/34] Creating a west workspace (west init)
=== Initializing in /home/huizha01/workspace/arm/mybuild/zephyr
--- Cloning manifest repository from https://github.com/zephyrproject-rtos/zephyr
Cloning into '/home/huizha01/workspace/arm/mybuild/zephyr/.west/manifest-tmp'...
Updating files: 100% (21384/21384), done.
--- setting manifest.path to zephyr
=== Initialized. Now run "west update" inside /home/huizha01/workspace/arm/mybuild/zephyr.
[17/34] git clone
ninja: build stopped: subcommand failed.
```

**Comment by rshym** [comment]
Thank you for your feedback, and I'm sorry for that mistake.
I will rework mentioned yaml and wrap the proprietary repo under the optional switch.
Also, I got off-site feedback regarding the GIC-related commit, which will be removed from this PR.
I will come back with reworked PR.
Thanks for your time.

> Thanks for contributing.
> 
> I followed the instructions in this doc and tried to build it, but I got an error. It seems that `ssh://git@gitpct.epam.com/epmd-aepr/img-proprietary` is an private repo. I noticed that this one is defined in `prod-devel-rcar.yaml`, should users change this URL to the public repo manually?

**Comment by carlescufi** [comment]
@carlocaione @SgrrZhf @povergoing @firscity @lorc @luca-fancellu could one of you review this PR? Thanks!

**Comment by firscity** [comment]
@carlescufi, there are 2 problems with current version:
- `gic_version="default"` is not OK for all HW cases (board with real GIC v3 supports running guests with emulated GIC v2 and `default` will not work in such case)
- one of the repos in product yaml is private

So we are waiting for new version of the PR, I will take a look when it will be available.

**Comment by rshym** [comment]
Sorry that I left PR hanging.
I am reworking quite a big part of the code to address mentioned issue with access to the proprietary repo.
This will take some time, so I will close this PR for now, so nobody spends time on it.
And I will come back with a new version of PR.

**Pull request closed without merging**
