### PR TITLE
net: ipv4: Rework source address matching for LL addresses 

### LINKED ISSUE #82080: net: if: selection of the src iface based on the IPv4 destination results in invalid iface
**Describe the bug**
The iface selection based on the destination address (IPv4) upon pkt sending worked before https://github.com/zephyrproject-rtos/zephyr/pull/81280/commits/aaab9dc8953773e4df74c9b239ca027306d2c9c7.

**To Reproduce**
A system must have 2 ifaces configured for IPv4, i.e.:

`eth_0`: `169.254.250.250/24`  (_255.255.255.0_)
`eth_1`: `169.254.253.1/30` (_255.255.255.252_)

We are sending a pkt to `169.254.253.2` and expecting the system to use `eth_1`. However, `net_if_ipv4_addr_lookup` returns `eth_0`.

Reverting the commit solves the problem.

**Expected behavior**
Correct iface is being used to send the pkt.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK 0.17.0
 - https://github.com/zephyrproject-rtos/zephyr/commit/b7b4de8afeb93b480b6a8e3bef18c76ea6a82bc9

@jukkar

### PR DESCRIPTION
**Pull request by rlubos**
Currently we blindly return the LL address found on the default
interface or else on the first interface that has a valid LL address
configured.

This doesn't work well, if different interfaces have LL addresses
configured with a different subnet mask. Therefore, instead of blindly
selecting the address based on the first LL address encountered, use
net_if_ipv4_get_best_match() function for LL addresses to find the best
match for the given interface.

The rework takes into account current behavior, i. e. default interface
still gets the preference if there is no better candidate.

Fixes #82080

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by GeorgeCGV — DISMISSED** [review]
Thank you. Tested, it works.

**Comment by rlubos** [comment]
I have realized that there's still some issue with retaining the current behavior:
> The rework takes into account current behavior, i. e. default interface still gets the preference if there is no better candidate.

As we compare entire IPv4 addresses, and not only the subnet part, this may lead to unexpected results based on the "unique" part of the LL address. I've added a test case for the faulty scenario and a proposed fix. 

This should now well cover the scenario where two interfaces use default IPv4 LL netmask, and when they have custom (longer) netmasks.

**Review by pdgendt — DISMISSED** [review]

**Review by GeorgeCGV — DISMISSED** [review]

**Comment by rlubos** [comment]
Sorry for another push, had to fix the CI. Some tests did not specify netmask for an IPv4 address they registered.

**Review by pdgendt — DISMISSED** [review]

**Review by GeorgeCGV — DISMISSED** [review]

**Comment by rlubos** [comment]
After some consideration, I propose an alternative way to fix the failing tests. Fixing the tests itself is one thing, but they may be other cases like this in the wild, where the application did not register the netmask along with the address (which is a mistake but apparently it used to work. Therefore, instead of fixing the test cases I propose we just set a default netmask for every address, specified by Kconfig.

Not sure what's with CI in the latest run, doesn't seem related to my changes, likely something broke on main.

**Comment by rlubos** [comment]
Rebased (hopefully the last time) to incorporate the hotfix for the CI from main.

**Review by pdgendt — DISMISSED** [review]

**Review by GeorgeCGV — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]
The netmask commit feels a bit hackish and might cause some issues too if the user does not realize to set it properly. We could mention this is migration guide just in case someone actually reads those entries (wishful thinking here).

**Comment by rlubos** [comment]
@jukkar I've added the requested migration guide entry and a fix for a failing testsuite, which should use different subnets for test interface if it wants to verify interface/address selection reliably.

**Review by jukkar — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Review by GeorgeCGV — APPROVED** [review]

**Pull request merged**
