### PR TITLE
Atmel SAM E70 USB driver

### PR DESCRIPTION
**Pull request by aurel32**

### CODE REVIEW

**Comment by galak** [comment]
The dts bits look good to me.

**Review by dbkinder — APPROVED** [review]
+1 for docs, thanks.

**Review by galak — APPROVED** [review]
+1 for dt

**Comment by aurel32** [comment]
I have just pushed a rebased version of the patchset, due to the conflicts introduced when merging the watchdog driver.

**Review by nashif — APPROVED** [review]

**Pull request merged**
