### PR TITLE
arch/xtensa: Skip partial-save optimization when using COHERENCE

### PR DESCRIPTION
**Pull request by andyross**
When CONFIG_KERNEL_COHERENCE is set, stacks are cached/incoherent.
The interrupt return path will flush them, but for that to work all
call tree's the register contents need to be on the stack in memory
and not still held in register windows.

The best way to do this would be to do the flush on interrupt return
only when needed, but that requires a little surgery so the assembly
code knows the stack bounds.  Instead, this patch simply skips all the
optimizations, flushing the entire window register state on interrupt
entry.

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by andyross** [comment]
@lyakh OK, I was too distracted and this was more fun than the abort stuff.  Please try this.  It doesn't break anything for me on qemu_xtensa, nor tests/kernel/common on cavs15.

**Comment by andyross** [comment]
DNM for now until @lyakh can confirm this addresses the problems he's seeing.  And even then I think it deserves some time to find a better optimized way to do it.

**Comment by lyakh** [comment]
> DNM for now until @lyakh can confirm this addresses the problems he's seeing. And even then I think it deserves some time to find a better optimized way to do it.

@andyross interesting, it looks like this should fix it and it would certainly be a better way to fix it than my #32479 which supposedly should introduce a lot of unnecessary overhead, flushing caches on each window overflow exception, but unfortunately it doesn't work for me. I haven't taken the time to investigate thoroughly and from the first sight I don't see any "old" stack writes after that point, but in fact with this patch it looks even worse than without it - with it I only see a print from one thread, without it I see one print from each thread.

**Review by lyakh — CHANGES_REQUESTED** [review]
doesn't seem to fix the problem

**Comment by andyross** [comment]
Kill this.  Still seems theoretical in my testing, but I think I have a handle on how to do the Right Thing here.

**Comment by lyakh** [comment]
@andyross I still can reproduce lock ups in some configurations with just added random printk()s on top of your big clean-up PR #32356 . So, a fix is needed. My brutal cache-flushing in window exception patch fixes those problems, but we need a proper one.

**Pull request closed without merging**
