### PR TITLE
Bluetooth: Mesh: Fixes wrong return value

### PR DESCRIPTION
**Pull request by LingaoM**
Fixes missing return value on `va_del`
Fixes wrong return value on `va_add`

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]
Looks fine, though the returns weren't wrong per-se, since STATUS_SUCCESS is the same as 0, but using the right define is certainly more appropriate.

**Review by joerchan — APPROVED** [review]

**Comment by joerchan** [comment]
> Looks fine, though the returns weren't wrong per-se, since STATUS_SUCCESS is the same as 0, but using the right define is certainly more appropriate.

Well the `va_del` did not return 0. So then this is a bugfix, right?

**Comment by jhedberg** [comment]
> Well the va_del did not return 0. So then this is a bugfix, right?

@joerchan yes, I misread the second part of the patch. It also means that this should be considered for back-porting to 1.14.

**Comment by joerchan** [comment]
@jhedberg You didn't put the backport v1.14 label?

**Comment by jhedberg** [comment]
> @jhedberg You didn't put the backport v1.14 label?

@joerchan it would do no good since the automated backport would fail (due the mesh code having moved location since 1.14). I therefore use the generic backport label and will create a manual backport PR.

**Comment by jhedberg** [comment]
Removed the backport label since this depends on settings support for virtual labels, which is not part of 1.14.

**Pull request merged**
