### PR TITLE
boards: arm: stm32: Basic support for STM32F769I-DISCO board

### PR DESCRIPTION
**Pull request by jinyongiot**
Add support for STM32F769I-DISCO board. This like the ports for STM32F746G-DISCO board by Yurii Hamann <yurii@hamann.site>,thank Yurii Hamann .

### CODE REVIEW

**Comment by therealprof** [comment]
Nice. Looking forward to trying that out.

**Comment by erwango** [comment]
Hi @jinyongiot ,

Thanks for this contribution. Some clean up before starting the review:
- Remove the 'merge master branch' commit
- Split your change into 2 commits: arch/ and boards/
- Add a at list one line comment for each commit message

Cheers
Erwan

**Review by erwango — CHANGES_REQUESTED** [review]
Some changes before reviewing:

*Remove the 'merge master branch' commit
*Split your change into 2 commits: arch/ and boards/
*Add a at list one line comment for each commit message

**Review by ydamigos — CHANGES_REQUESTED** [review]
Do we actually need a specific `Kconfig.defconfig.stm32f769ni`? Isn't `Kconfig.defconfig.stm32f769xi` enough?

**Comment by erwango** [comment]
Closing since this is same as https://github.com/zephyrproject-rtos/zephyr/pull/8737

**Pull request closed without merging**
