### PR TITLE
drivers: can: separate CAN classic and CAN-FD syscalls, allow enabling CAN-FD at run-time

### LINKED ISSUE #45303: drivers: can: CAN classic and CAN-FD APIs are mixed together and CAN-FD is a compile-time option
**Describe the bug**
The current implementation of CAN-FD support depends on a compile-time flag (Kconfig), which either enables or disables CAN-FD support completely.

With `CONFIG_CAN_FD_MODE=y` it is not possible to enable/disable the reception of CAN-FD frames at run-time, meaning the CAN node will ACK CAN-FD frames - and CAN-FD frames will be matched by the added RX filters - even if the CAN bus should not be configured for CAN-FD.

Furthermore, the `can_set_timing()` and `can_set_bitrate()` system calls mix CAN classic and CAN-FD functionality, which makes the API confusing for non-CAN-FD users as some of the arguments are then ignored/unused. What should an application pass for the "data" timing if it is not CAN-FD aware? Passing in `0` or `NULL` will work as long with `CONFIG_CAN_FD_MODE=n` but cause the system call to fail if the user enabled `CONFIG_CAN_FD_MODE=y`.

**Expected behavior**
CAN classic and CAN-FD APIs should not be intermixed. The API should allow for enabling/disabling CAN-FD without re-compiling the firmware. It should still be possible to disable CAN-FD support completely at compile time.

**Impact**
It is not possible to create one firmware with support for both CAN classic and CAN-FD. Applications, which are not CAN-FD aware must deal with a confusing CAN driver API.

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Split CAN classic and CAN-FD syscalls into two:
- `can_set_timing()` -> `can_set_timing()` + `can_set_timing_data()`
- `can_set_bitrate()` -> `can_set_bitrate()` + `can_set_bitrate_data()`

Rename the CAN data phase API functions to `timing_data_*` for consistency:
- `can_get_timing_min_data()` -> `can_get_timing_data_min()`
- `can_get_timing_max_data()` -> `can_get_timing_data_max()`
- `.timing_min_data` -> `.timing_data_min`
- `.timing_max_data` -> `timing_data_max`

Convert the can_mode enum to a bit field to prepare for future extensions (CAN-FD mode, transmitter delay compensation, one-shot mode, 3-samples mode, ...). Rename the existing modes:
- `CAN_NORMAL_MODE` -> `CAN_MODE_NORMAL`
- `CAN_SILENT_MODE` -> `CAN_MODE_LISTENONLY`
- `CAN_LOOPBACK_MODE` -> `CAN_MODE_LOOPBACK`
    
These mode names align with the Linux naming for CAN control modes. The old `CAN_SILENT_LOOPBACK_MODE` can be set with the bitmask `(CAN_MODE_LISTENONLY | CAN_MODE_LOOPBACK)`.

Finally, add support for enabling/disabling CAN-FD frame transmission/reception at run-time.

Fixes: #45303

### CODE REVIEW

**Review by martinjaeger — APPROVED** [review]
LGTM

**Comment by henrikbrixandersen** [comment]
@erwango Please note the changes to the STM32 `soc.h` files.

**Review by teburd — APPROVED** [review]
Seems like a sensible set of changes. I'm modestly concerned by the undef's for stm32 and the placement of those in soc.h. Is that really the right place for that?

**Comment by henrikbrixandersen** [comment]
They need to be in `soc.h` to avoid redefinition errors when other C files include both `soc.h` and `can.h`. I am not fond of them either, but I see no other way to solve this (non-)namespace clash.

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen 
> 
> Hello,
> 
> commit [c8697fa](https://github.com/zephyrproject-rtos/zephyr/pull/45380/commits/c8697fad22b71383642c75f447658a10e7f1b6cc) forces the user to call `can_mcan_set_mode` to enable CAN-FD. 
> 
> 
> 
> Is it the expected behavior or should we enable CAN-FD by default if `CONFIG_CAN_FD_MODE` is defined?

You need to call `can_set_mode()` to enable CAN-FD. That is intentional.

**Pull request merged**
