### PR TITLE
Flash and nvs improvements

### PR DESCRIPTION
**Pull request by mjchen0**
NVS is very slow when CONFIG_SPI_NOR_IDLE_IN_DPD is defined because every flash operation involves entering and exiting the FLASH part's deep power down mode. In addition to the SPI cmd involved, there is typically a non-trivial delay required after issuing the exit from DPD cmd. These delays of every FLASH SPI operation can dramatically slow down NVS (in my tests, mounting a small NVS of 256 sectors too over an order of magnitude longer when DPD was enabled).

The main CL in this pull request introduces a new FLASH driver API that involves two new functions called acquire and release. These are implemented for the spi nor driver to call it's already existing acquire and release functions that do the DPD management, with some modification to reference count the acquires/release calls because they can now be nested.

NVS uses the new APIs if they exist, allowing multiple FLASH operations to be called while the FLASH part is acquired and kept out of DPD, avoiding the extra delay involved in each FLASH operation, but still putting the FLASH part to deep power down once we're idle.

The second CL is a smaller one that improves a comparison function, making it faster and reducing it's stack usage.

### CODE REVIEW

**Review by nordicjm — COMMENTED** [review]
This should be using https://docs.zephyrproject.org/latest/services/pm/device_runtime.html#introduction

**Review by de-nordic — CHANGES_REQUESTED** [review]
Split to two PRs, the changes are unrelated.
I do not think there is a need for callbacks nor internal counter, PM already handle that.
There are pm_device_runtime_get and pm_device_runtime_put functions use usage counter provided by the PM. What we probably lack here is the PM callback processing.

**Comment by mjchen0** [comment]
Okay, I've split into actually three PRs (third is the removal of the unneeded enter_dpd() call at end of spi_nor_configure() in spi_nor.c).

Using runtime pm is cleaner, but a little awkward in that anyone previously using CONFIG_SPI_NOR_IDLE_IN_DPD to save power will actually want to disable that now in favor of using runtime pm, and make sure to enable it in their device tree.

**Comment by mjchen0** [comment]
> Split to two PRs, the changes are unrelated. I do not think there is a need for callbacks nor internal counter, PM already handle that. There are pm_device_runtime_get and pm_device_runtime_put functions use usage counter provided by the PM. What we probably lack here is the PM callback processing.

I  make the requested change. Please review again.

**Comment by mjchen0** [comment]
Please have the stale label removed.

**Review by de-nordic — APPROVED** [review]

**Comment by Laczen** [comment]
@mjchen0 my knowledge on the PM subsystem is insufficient to confirm that the correct method is used (from the intro in PM I would think using `pm_device_busy_set()` and `pm_device_busy_clear()`, but I am not sure).
@JordanYates, @ceolin you are better placed to provide feedback.

**Comment by JordanYates** [comment]
I believe myself and @ceolin have come to an agreement that the SPI NOR driver should be automatically performing the PM operations in `flash_read/write/erase/etc`, closing with a `device_runtime_pm_put_async(dev, some_delay)`.

The async put would mean multiple requests closely grouped in time would not result in multiple PM transitions. This would resolve not only the issue here, but a collection of other flash users.

I just haven't had a board using the `spi_nor` driver since I left my previous job, so I hadn't gotten around to actually making the changes.

**Comment by JordanYates** [comment]
Could you take a look at #73246 and see if it resolves your issue?

**Comment by Laczen** [comment]
@mjchen0 have you had the time to check #73246 to see if this resolves the issue. If it does please close the PR.

**Comment by Laczen** [comment]
@mjchen0 a gentle nudge...

**Comment by Laczen** [comment]
> > @mjchen0 have you had the time to check #73246 to see if this resolves the issue. If it does please close the PR.
> 
> I just took a look and yes, I think it should resolve the issue as well, though there are differences. In my PR, if NVS is the only user of the spi_nor FLASH, the FLASH it is put to sleep as soon as possible after NVS is done. There is no additional latency for the async wait timeout and there is no extra code execution for scheduling and cancelling the work when a burst of FLASH activity occurs, etc. So I think my PR is complementary and has advantages.

I understand that the PR has advantages but I think it is too pm specific to integrate into NVS. What do you think about adding a routine to nvs: `int nvs_long_operation_cb(struct nvs_fs *fs, bool enable)` that would be called with `enable=true` at start end `enable=false` at the end?

**Comment by JordanYates** [comment]
> I just took a look and yes, I think it should resolve the issue as well, though there are differences. In my PR, if NVS is the only user of the spi_nor FLASH, the FLASH it is put to sleep as soon as possible after NVS is done. There is no additional latency for the async wait timeout and there is no extra code execution for scheduling and cancelling the work when a burst of FLASH activity occurs, etc. So I think my PR is complementary and has advantages.

I agree that this PR is more optimized for this particular use case (reading or writing from one NVS key), however I am not convinced that the performance improvement is significant. If NVS is the only user of the flash, then the delay can be set to 1ms and achieve the same functionality as this PR with minimal overhead (1ms of idle vs DPD on the flash, 1 additional SoC wakeup).

I am curious how often you are reading/writing to the NVS, that these few milliseconds are a problem.

**Comment by Laczen** [comment]
@mjchen0 I propose to close this PR. When #73246 is merged it would not be needed to integrate PM into nvs.

**Pull request closed without merging**
