### PR TITLE
Shell: Remove unnecessary new lines at startup

### PR DESCRIPTION
**Pull request by theob-pro**
When the shell start, it will print two lines. The reason for that behavior is not documented. Remove that to make the code simpler and shorter one line at a time.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
> When the shell start, it will print two lines. The reason for that behavior is not documented. Remove that to make the code simpler and shorter one line at a time.

What makes you think those newlines are unnecessary? The code was added for a reason.

**Comment by theob-pro** [comment]
> > When the shell start, it will print two lines. The reason for that behavior is not documented. Remove that to make the code simpler and shorter one line at a time.
> 
> What makes you think those newlines are unnecessary? The code was added for a reason.

The fact that there is no documentation nor any tests. I checked the PR that introduced the behavior (https://github.com/zephyrproject-rtos/zephyr/pull/9362) and did not find any arguments.

If you can think of how it could be useful, please let me know. And if possible, add a test to demonstrate the usefulness of it or at least some documentation.

**Comment by jakub-uC** [comment]
Thank you for your feedback. 
The reason for adding these new lines at the start of the shell is to ensure that the prompt begins on a clean line. This is particularly useful in situations where the program may have experienced a reset or if it has hung and subsequently restarted. By starting the prompt on a new line, it visually separates the new shell session from any previous output on the terminal, making it much clearer for the user to see where the new session begins.

I understand the importance of tests and documentation, but in this case, the functionality is straightforward and doesn’t require them. The code’s purpose is clear and adding tests or detailed documentation might not add much value.

However, I do see the benefit of making the intent clearer, so I'm happy to add a comment above the code to explain its purpose. This should help anyone reading the code in the future.

If you have further concerns or suggestions, I’m open to discussing them, but I believe a concise comment should suffice.

**Comment by theob-pro** [comment]
Hi @jakub-uC, thanks for taking the time to explain things to me, it's much appreciated!

That said, the way it is implemented looks a bit hacky to me.

You said that this functionality is straightforward but is it? At first, I did not understand why there was a condition on the length of the prompt.

From what I saw elsewhere when playing with other shells and terminal programs, the usual way would rather be to move the cursor position for this kind of thing.

So, I investigated a bit more, and I now understand why there is that `if` condition, but it's definitely not straightforward:

The function `state_set` in `shell_start` calls `z_shell_print_prompt_and_cmd` which calls `z_shell_op_cursor_position_synchronize`. In that function there is the following code:

https://github.com/zephyrproject-rtos/zephyr/blob/6b6c4333b7fb85d7ea0729e2d084af94f3b65ac4/subsys/shell/shell_ops.c#L75-L80

Seems to make sense: the line is full, we move the cursor to the next line. Now let's look at the documentation of `full_line_cmd`:

```
Function returns true if command length is equal to multiplicity of terminal width.
```

Seems odd, the docstring says that the function does a bit more than the comment at the call-site. Let's take a look at the implementation:

https://github.com/zephyrproject-rtos/zephyr/blob/6b6c4333b7fb85d7ea0729e2d084af94f3b65ac4/subsys/shell/shell_ops.c#L41-L48

Indeed, the function does more than what the comment in `z_shell_op_cursor_position_synchronize` states: If the line is empty, the function will return `true` and the cursor will be moved to a new line.

We now understand why there is that condition on the prompt size in `shell_start`. It's because when there is no prompt, the shell will have the correct behavior and will put the cursor on a new line. But that behavior is not documented at all and kind of a side effect according to the comment in `z_shell_op_cursor_position_synchronize`.

My point writing that is to highlight how something that may seem trivial isn't. I don't mind having two lines when I start my shell. But I definitely care about the code complexity and readability. And having code like that is not helpful for future contributors.

Here are my suggestions:
1. Apply my patch, as I demonstrated it, those two lines shouldn't be here
2. If you both agree (@henrikbrixandersen @jakub-uC), I'll make a follow-up PR that will remove the side effect of `full_line_cmd` and then add a call to `z_cursor_next_line_move` in `shell_start`

**Comment by jakub-uC** [comment]
@theob-pro
Please take a look at the example:
image

If you remove these two new lines, the result after the reset will be as shown in the picture, and it will have the following consequences until the command is executed (press Enter):

The prompt will be printed on the same line, in the same place where it was before the reset. This does not look neat.
The shell's logic will have an incorrect understanding of the cursor's position, which will negatively affect the correct handling of arrow keys for cursor movement (e.g., when navigating up/down during command editing).
The code you are analyzing further assumes that the shell started at position x == 0.

**Comment by theob-pro** [comment]
@jakub-uC, I understand your concern about the reset, and I agree with you. My point here is that the way it's done is not correct and hard to understand.

Was it clear to you why the there was that `if` condition if the prompt is empty? Does that mean that we don't mind writing on the same line after a reset if we don't have a prompt?

What I am proposing is fixing `full_line_cmd` and using `z_cursor_next_line_move` in `shell_start`. Does that make sense to you?

**Comment by jakub-uC** [comment]
I'm not entirely sure if I fully understand how you want to modify the `full_line_cmd function`. If it's not too much trouble, could I kindly ask you to add a commit to this PR that modifies this function?

Replacing `z_shell_raw_fprintf(sh->fprintf_ctx, "\n\n");` with two calls `z_cursor_next_line_move` is also fine with me. Calling the function twice doesn't add much overhead, especially since this code isn't executed very often. Typically after a reboot or shell suspension-resumption. This will definitely improve the readability of the code.

There is indeed an inconsistency in the comments for the `full_line_cmd function`. It should return true if the cursor needs to be on a new line, which is when the prompt plus the printed command take up the entire width of the terminal.

Thank you for your patience with the explanations, but each of us have a different context in mind, which leads to misunderstandings. Adding a commit with the proposed change would greatly improve communication.

**Comment by jakub-uC** [comment]
Ahh you did it already! :)
It looks great! Could you please add 2 new lines instead of 1? I should mention that this requirement was established at Nordic when I was still working there. ;)

**Comment by theob-pro** [comment]
> It looks great! Could you please add 2 new lines instead of 1? I should mention that this requirement was established at Nordic when I was still working there. ;)

Could you please provide more information? Is there a specific reason for that?

As I understand the reason for adding a new line at the shell startup, it's hard for me to find a good reason to add a second one. To be honest, if this is a personal preference I would prefer to tell users that they can configure the prompt however they want using one of the `CONFIG_SHELL_PROMPT_*` Kconfig symbols and that they can add new line there.

**Comment by jakub-uC** [comment]
I won't insist on making the change. The reasoning at the time was that with 2 lines, you can see the device reset, and it's possible to distinguish it from the regular execution of the command.

**Review by jakub-uC — DISMISSED** [review]

**Comment by theob-pro** [comment]
Rebased to fix failing test.

**Review by jori-nordic — APPROVED** [review]

**Review by jakub-uC — APPROVED** [review]

**Pull request merged**
