### PR TITLE
drivers: flash: spi_nor: fix config struct

### LINKED ISSUE #80383: drivers: flash: spi_nor: values vom DT not correctly used, when `CONFIG_SPI_NOR_SFDP_RUNTIME=y`
**Describe the bug**

when `CONFIG_SPI_NOR_SFDP_RUNTIME=y`, configs from the dts like the wp, hold and reset pins are not parsed correctly into the `struct spi_nor_config` and therefore can't be used by the driver.

**To Reproduce**
set `CONFIG_SPI_NOR_SFDP_RUNTIME=y`, when using the jedec,spi-nor flash driver

**Expected behavior**
dts configuration is used correctly

**Impact**
most of the available configuration, that can be done via the dts wont work when `CONFIG_SPI_NOR_SFDP_RUNTIME=y`,

**Logs and console output**

**Environment (please complete the following information):**
NA

**Additional context**
Got introduced with https://github.com/zephyrproject-rtos/zephyr/pull/70415

### PR DESCRIPTION
**Pull request by maass-hamburg**
lots of values from the DT where not set corretly, if
`CONFIG_SPI_NOR_SFDP_RUNTIME` was
enabled. This fixes it.

Got introduced with https://github.com/zephyrproject-rtos/zephyr/pull/70415

Fixes #80383

### CODE REVIEW

**Comment by de-nordic** [comment]
@maass-hamburg Can you report Bug issue for this? It has been introduced in v3.7.0 and will require release notes with referring to bug report.

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]
any reason not to include this for RC2?

**Comment by dkalowsk** [comment]
as @de-nordic stated this likely needs a release-note update.  @maass-hamburg can you add that release note addition so we can merge this in?

**Comment by mmahadevan108** [comment]
@maass-hamburg , could you help update the release notes.

**Comment by de-nordic** [comment]
> @maass-hamburg , could you help update the release notes.

@dkalowsk can we marge this and wait for @maass-hamburg to provide new PR with the release note?

If that will not happen I have provided one here: https://github.com/zephyrproject-rtos/zephyr/pull/80634 as alternative (DNM to give author a change to provide own).

**Comment by maass-hamburg** [comment]
Sorry, I was on vacation until yesterday. 
@de-nordic Thank you for creating the release note PR.

**Comment by de-nordic** [comment]
> Sorry, I was on vacation until yesterday. @de-nordic Thank you for creating the release note PR.

No problem. Thanks for accepting the proposed one.

**Pull request merged**
