### PR TITLE
boards: arm: disco_l475_iot1: Enable MSI PLL mode for USB

### LINKED ISSUE #18717: USB broken on disco l475 iot board
**Describe the bug**
Unable to init USB core

**To Reproduce**
Try any USB sample

**Expected behavior**
USB working

**Additional context**
Issue  is caused by commit 737d8051927d3354fbf398babfe1d156f4420442

### PR DESCRIPTION
**Pull request by loicpoulain**
The MSI PLL mode has been disabled but can be used since LSE is
populated on disco_l475_iot1 board. This is requested to enable
USB device controller support.

Fixes: 737d8051927d ("boards: arm: disco_l475_iot1: remove MCU slow down when using BlueRNG-MS")

fixes #18717

Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

### CODE REVIEW

**Comment by loicpoulain** [comment]
It fixes #18717

**Comment by ioannisg** [comment]
Looks trivial; there are some Lint issues, but I'd like some reviewing from @erwango , at least, at this late stage in the release cycle.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@loicpoulain can you fix CI please?

**Comment by loicpoulain** [comment]
> @loicpoulain can you fix CI please?

Done, was using Linux convention.

**Comment by yboutreux** [comment]
Bluetooth samples Beacon, Peripheral and Central are still working, sorry for the issue coming from https://github.com/zephyrproject-rtos/zephyr/commit/737d8051927d3354fbf398babfe1d156f4420442 !

**Review by ydamigos — APPROVED** [review]
LGTM.

**Review by erwango — APPROVED** [review]

**Pull request merged**
