### PR TITLE
modules: Introduce hal-nxp-mcux-sdk

### PR DESCRIPTION
**Pull request by MaureenHelm**
Introduces the new GitHub-based distribution of the MCUXpresso SDK as a
module in the west manifest. This new distribution provides the same
bare metal drivers as those downloaded from mcuxpresso.nxp.com and
imported into the hal_nxp module, however in this distribution they are
organized in a different directory structure that doesn't duplicate each
driver for every device. It can be integrated as-is into Zephyr without
the reorganization done in the hal_nxp module, and will therefore
simplify future updates of the SDK into Zephyr.

Currently the west manifest points to an NXP-hosted GitHub repo, but
will be updated once we have a Zephyr-hosted fork available.

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

- [ ] Depends on #32278
- [ ] Depends on NXPmicro/mcux-sdk#6

cc: @nxp-susan

### CODE REVIEW

**Review by galak — COMMENTED** [review]
I assume its reasonable to say that for a given board/SoC we'd never mix drivers from one HAL or the other?  If this is the case, seems like we can simplify the Kconfig a bit.

Feels like you can use the same Kconfig symbols in both the current zephyr HAL repo and the new mcux-sdk based repo, and just have a high level switch on MCUX v MCUX_SDK.

**Comment by MaureenHelm** [comment]
> I assume its reasonable to say that for a given board/SoC we'd never mix drivers from one HAL or the other? If this is the case, seems like we can simplify the Kconfig a bit.

I hope so, but I'm not sure yet.
 
> Feels like you can use the same Kconfig symbols in both the current zephyr HAL repo and the new mcux-sdk based repo, and just have a high level switch on MCUX v MCUX_SDK.

I agree having both `MCUX` and `MCUX_SDK` prefixed symbols feels like a lot of duplication, but I also don't think there should be any interdependencies between the two modules. If we did have a unified set of Kconfig symbols, where would they be defined? Also, the MCUXpresso SDK is considering adding support for Kconfig in NXPmicro/mcux-sdk#6, in which case we would only *use* the symbols in Zephyr, not define them in Zephyr.

**Comment by henrikbrixandersen** [comment]
Don't the symbols _need_ to be defined in Zephyr in order not to break Kconfig for people with custom west manifests where the MCUX SDK is not included?

**Comment by MaureenHelm** [comment]
> Don't the symbols _need_ to be defined in Zephyr in order not to break Kconfig for people with custom west manifests where the MCUX SDK is not included?

Now that you mention it, I think I remember hearing this during one of the module discussions.

@tejlmand can you give some guidance? Is there a way we can use Kconfig symbols defined in a module? These symbols are not specific to Zephyr and could be used by other projects.

This is a simplified version of what I want to do:

In the module:
```
config HAS_MCUX_SDK_DRIVER_FLEXCAN
	bool

config MCUX_SDK_DEVICE_MK64F12
	bool "MK64F12"
	select HAS_MCUX_SDK_DRIVER_FLEXCAN

config MCUX_SDK_DRIVER_FLEXCAN
	bool "FLEXCAN"
	depends on HAS_MCUX_SDK_DRIVER_FLEXCAN
	help
	  Build the FlexCAN bare metal driver
```

In Zephyr:
```
config CAN_MCUX_FLEXCAN
	bool "MCUX FlexCAN driver"
	depends on HAS_MCUX_SDK_DRIVER_FLEXCAN
	imply MCUX_SDK_DRIVER_FLEXCAN
	help
	  Build the FlexCAN shim driver
```

**Comment by tejlmand** [comment]
> > Don't the symbols _need_ to be defined in Zephyr in order not to break Kconfig for people with custom west manifests where the MCUX SDK is not included?
> 
> Now that you mention it, I think I remember hearing this during one of the module discussions.
> 
> @tejlmand can you give some guidance? Is there a way we can use Kconfig symbols defined in a module? These symbols are not specific to Zephyr and could be used by other projects.

If you refer to a Kconfig symbol defined in a module from a Kconfig file in the Zephyr repo, then that symbol must also exists inside Zephyr itself, in order for everything to work when the module is not present.

This is why all known Zephyr modules have their Kconfig files inside the Zephyr repo: https://github.com/nrfconnect/sdk-zephyr/tree/master/modules

If you only want the settings visible / configurable to the user when the module is actively present, then you can just have a dummy duplication inside Zephyr.

Like this:
```
if 0
# These are dummy definitions to avoid unknown symbols when the module is missing.
config HAS_MCUX_SDK_DRIVER_FLEXCAN
	bool

config MCUX_SDK_DRIVER_FLEXCAN
	bool
endif

config CAN_MCUX_FLEXCAN
	bool "MCUX FlexCAN driver"
	depends on HAS_MCUX_SDK_DRIVER_FLEXCAN
	imply MCUX_SDK_DRIVER_FLEXCAN
	help
	  Build the FlexCAN shim driver
```

That will ensure Zephyr builds, and only if the module is present, then the settings are configurable as those settings are now available in the module with prompts.

This is in principle what we do here:
https://github.com/zephyrproject-rtos/zephyr/blob/0106d8f2a391fffcefabd053e17c683ea2e53d8a/modules/Kconfig#L69-L74

and then as soon as the module is present, the Kconfig file is sourced properly with all symbols available to the user :smile:

**Pull request closed without merging**
