### PR TITLE
test: scheduling :add new conf file

### PR DESCRIPTION
**Pull request by yingmingx**
Add a conf file to make sure the kernel will use simple linked-list
ready queue as scheduling algorithm. This operation will increase module
testcase coverage and z_priq_dumb_add z_prj_dum_remove function are
called.

Signed-off-by: Ying ming <mingx.ying@intel.com>

### CODE REVIEW

**Comment by yingmingx** [comment]
This code change is OK, CI build failure due to #30408

**Review by LeiW000 — APPROVED** [review]
buildkite/zephyr failure has nothing to do with the change in the PR. So approve it.

**Comment by LeiW000** [comment]
@enjiamai , @mengxianglinx  please take look at it.

**Review by enjiamai — COMMENTED** [review]
please rebase and try to see if the build error problem fixed, thanks!

**Review by enjiamai — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
