### PR TITLE
Add wdog support for frdm_ke17z and frdm_ke17z512

### PR DESCRIPTION
**Pull request by ankeXiao**
Add wdog configuration to test 'tests/drivers/watchdog/wdt_basic_api' case.

### CODE REVIEW

**Review by danieldegrasse — COMMENTED** [review]
We should update the board documentation pages (`index.rst`) as well, right?

**Review by decsny — CHANGES_REQUESTED** [review]
update board doc page

**Comment by ankeXiao** [comment]
> We should update the board documentation pages (`index.rst`) as well, right?

Thanks for reminding, I will update it.

**Review by EmilioCBen — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Comment by dleach02** [comment]
@ankeXiao please resolve the merge conflicts

**Comment by ankeXiao** [comment]
> @ankeXiao please resolve the merge conflicts

Done

**Review by decsny — DISMISSED** [review]

**Review by dleach02 — DISMISSED** [review]

**Comment by ankeXiao** [comment]
Rebased to fix merge conflicts

**Review by dleach02 — APPROVED** [review]

**Comment by ankeXiao** [comment]
Can someone help to merge this PR? Thanks!

**Review by EmilioCBen — APPROVED** [review]

**Pull request merged**
