### PR TITLE
Generate aliases definition from device tree

### PR DESCRIPTION
**Pull request by erwango**
Aim of this pull request is to generate "#define" out of aliases{} node of dts files

Benefit is the ability to generate alternate definitions to a node with a name exempt from reference to a particular SoC. With this we can get "generic" #define that could be used in two different ways:
-directly in application code (cf #5381)
-in a fixup file dedicated to an application (cf #6837)

Code takes into account the case where a single node has several aliases.

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]

**Comment by b0661** [comment]
Wouldn´t it be enouch to have just a node alias (e.g. #define ALIAS_NODE ST_STM32_SPI_74000)?

As far as I understand the commit generates an alias define for all the properties of the aliased node (#define ALIAS_NODE_[PROP]  ST_STM32_SPI_74000_[PROP] ...).

The properties of the aliased node can easily be accessed by ALIAS_NODE ## _PROP or CONCAT(ALIAS_NODE, _PROP). No need to define all the property aliases.

**Comment by erwango** [comment]
@b0661 , IIUC, with CONCAT, we'd still need to get someone doing the generation in the end.
Which part of code would be in charge of that?

**Comment by b0661** [comment]
@erwango 

> Which part of code would be in charge of that

extract_dts_includes generates #define ARDUINO_SPI ST_STM32_SPI_75000

The arduino shield code uses e.g. ARDUINO_SPI##_LABEL to get the SPI driver label.

**Comment by erwango** [comment]
> The arduino shield code uses e.g. ARDUINO_SPI##_LABEL to get the SPI driver label.

Actually, for the shield part, I'm relying on shield dts.fixup to bind sensor CONFIG_ flags with soc generated bits:
```
#define CONFIG_HTS221_NAME			ARDUINO_I2C_ST_HTS221_5F_LABEL
#define CONFIG_HTS221_I2C_MASTER_DEV_NAME	ARDUINO_I2C_ST_HTS221_5F_BUS_NAME
```
I don't see how to do this binding with concatenation right now.

**Comment by b0661** [comment]
@erwango 

Maybe I got you wrong. I was thinking you want to mark the I2C node of the microcontroller that is used by the Arduino board. So ARDUINO_I2C is just an alias to ST_STM32_I2C_x. 

A shield is always using ARDUINO_I2C. Which is mapped to the correct microcontroller node.

**Comment by erwango** [comment]
@b0661 : It is possible that I've not been clear enough in my needs.

Actually I want my shield to be compatible with all boards that will define arduino_i2c.
For a nucleo_f4xx, we'll have indeed a binding ARDUINO_I2C <> ST_STM32_I2C_X
For a frdm_k64f, well have ARDUINO_I2C <> NXP_KINETIS_I2C_X

Then, I want this to be available for each component of my shield, typically a bus slave element like a sensor. I want my shield feature to be board independant, so I don't want to introduce binding in a board fixup file but then I can have a shield fixup file thanks to the alias:
```
#define CONFIG_HTS221_NAME ARDUINO_I2C_ST_HTS221_5F_LABEL
```
With binding to the board being done directly at dts computing, and depending on my board
```
#define ARDUINO_I2C_ST_HTS221_5F_LABEL ST_STM32_I2C_V1_40005400_ST_HTS221_5F_LABEL

or for another board

#define ARDUINO_I2C_ST_HTS221_5F_LABEL NXP_KINETIS_I2C_46000000_ST_HTS221_5F_LABEL
```

With this method, my shield code is totally board independant and binding is done before compilation

**Comment by b0661** [comment]
@erwango

Looking at your example there is a HTS221 sensor chip on your shield which is attached to the I2C bus. The I2C bus of the shield is connected to the ARDUINO_I2C bus of the Arduino board. The ARDUINO_I2C bus is defined by an alias to the specific SoC I2C port of the Arduino board. Depending on the Arduino board the SoC may be STM32, KINETIS, ...

1) To make your shield code independent from the actually used Arduino board you need to access the I2C device driver in a board agnostic way. To access the driver you need the LABEL property. By the simple alias generated from the DTS based on the node alias:

        #define ARDUINO_I2C   NXP_KINETIS_I2C_2  /* example KINETIS SoC, mabe STM,. ... */

    you gain access to the LABEL property of the specific I2C port device driver by e.g.

        #define SHIELD_I2C_LABEL  ARDUINO_I2C##_LABEL

    This expands to NXP_KINETIS_I2C_2_LABEL which should already by available in the generated include file.

2) To allow others to use the sensor on the shield you only have to provide a header file for the shield with:

        #define ARDUINO_I2C_ST_HTS221_5F_LABEL    ARDUINO_I2C##_LABEL


I understand that if you want to get rid of 2) you may generate all the defines for the components on your shield instead of providing a shield header file. But you were talking about a "shield fixup file" which is just the header file in 2).

**Comment by erwango** [comment]
@b0661, let's say my change is meant to be incremental to the current paradigm of code generation and use of fixup files. In that context, getting script generating more defines allows having less modifications and additions in the drivers and application code.

**Review by galak — APPROVED** [review]

**Pull request merged**
