### PR TITLE
Bluetooth: ISO: Add missing handling of interval and latency of unidir

### PR DESCRIPTION
**Pull request by Thalley**
Adds missing handling of the m_interval and m_latency if tx QOS is
not set, and handling of the s_interval and s_latency if rx QOS is
not set.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by koffes** [comment]
If the central just sets TX it does not seem that the RX parameters are set. Will investigate further.

**Comment by koffes** [comment]
Found it. Small mistake on your line 413 ;) RX vs TX

**Review by koffes — APPROVED** [review]

**Review by koffes — APPROVED** [review]

**Comment by joerchan** [comment]
@Thalley This does not seem to match the behavior that is documented.

```
	/** Channel Receiving QoS:
	 *  Setting NULL disables data path BT_HCI_DATAPATH_DIR_CTLR_TO_HOST
	 */
	struct bt_iso_chan_io_qos	*rx;
	/** Channel Transmission QoS:
	 *  Setting NULL disables data path BT_HCI_DATAPATH_DIR_HOST_TO_CTRL
	 */
	struct bt_iso_chan_io_qos	*tx;
```

Or am I misunderstanding it?

**Comment by Thalley** [comment]
> @Thalley This does not seem to match the behavior that is documented.
> 
> ```
> 	/** Channel Receiving QoS:
> 	 *  Setting NULL disables data path BT_HCI_DATAPATH_DIR_CTLR_TO_HOST
> 	 */
> 	struct bt_iso_chan_io_qos	*rx;
> 	/** Channel Transmission QoS:
> 	 *  Setting NULL disables data path BT_HCI_DATAPATH_DIR_HOST_TO_CTRL
> 	 */
> 	struct bt_iso_chan_io_qos	*tx;
> ```
> 
> Or am I misunderstanding it?

Maybe :)
The `rx` and `tx` pointers are an abstraction for the direction (and thus the data paths). What this PR does is handling the case(s) where only one of them is set in terms of setting the interval and latencies. This change is thus not directly related to direction or data paths. 

Perhaps you can elaborate more on why you don't think it matches the documentation?

**Comment by joerchan** [comment]
@Thalley I think the fact that if the TX pointer is disabled then RX values are used instead (and vice versa) deserves an explanation in the public API. That seems like something the application should be informed about.

**Comment by Thalley** [comment]
> @Thalley I think the fact that if the TX pointer is disabled then RX values are used instead (and vice versa) deserves an explanation in the public API. That seems like something the application should be informed about.

Hmm, I get your point. 

The CIG parameters is always (only) set for the central (master) and never the peripheral (slave). If only `tx` is set, then the `s_interval` and `s_latency` values are actually completely irrelevant since we only set the data path for one direction, and vice versa if `rx` is only set. If the spec allowed, we would probably just set to them 0. 

If it is unidirectional (i.e. only `tx` or `rx` is set), then only the master or slave values have any meaning, due to how we always set data path and CIG parameters in the same API call.

**Comment by joerchan** [comment]
Ok, so the values would not be used but need to be set to valid values, that is what you are saying.

The crossover is what I found confusing, I would expect a default value instead when the application does not provide it.

**Comment by Thalley** [comment]
> Ok, so the values would not be used but need to be set to valid values, that is what you are saying.
> 
> The crossover is what I found confusing, I would expect a default value instead when the application does not provide it.

That's an alternative we can consider. @Vudentz Any input? 

But otherwise I suggest that we get this PR in as it is blocking unidirectional CIS from working.

**Comment by Vudentz** [comment]
> > Ok, so the values would not be used but need to be set to valid values, that is what you are saying.
> > The crossover is what I found confusing, I would expect a default value instead when the application does not provide it.
> 
> That's an alternative we can consider. @Vudentz Any input?
> 
> But otherwise I suggest that we get this PR in as it is blocking unidirectional CIS from working.

Not really following you here, by not setting a direction it means it is disabled or is there something else you want to do with it, Ive already approved this one btw.

**Review by joerchan — APPROVED** [review]
Looks OK to me, it would be easier to understand the code if it was documented that setting the values for the disabled path is in fact irrelevant and only needs to be a valid value.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
