### PR TITLE
west.yml: Update hal_silabs to pull request #52 | Update to GSDK 4.4.0

### PR DESCRIPTION
**Pull request by sateeshkotapati**
Updated the remaining files present in gecko/emlib folder and gecko/common folder in Silabs HAL.

This pull request is required to align the codebase of zephyr_rtos/hal_silabs (https://github.com/zephyrproject-rtos/hal_silabs) with gecko_sdk v4.4.0 (https://github.com/SiliconLabs/gecko_sdk)

PR in hal_silabs : https://github.com/zephyrproject-rtos/hal_silabs/pull/52

### CODE REVIEW

**Comment by sateeshkotapati** [comment]
Hi @fkokosinski, could you review this PR, its wrt updating the remaining files in emlib folder to GSDK version 4.4.0. Thanks

**Comment by sateeshkotapati** [comment]
> You can now bump the revision of the HAL module

Hi @fkokosinski!, I have rebased and updated the revision of Silabs HAL, can you please approve this, Thanks.

**Review by fkokosinski — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by sateeshkotapati** [comment]
Hi, @fkokosinski can we merge this PR now?

**Comment by fkokosinski** [comment]
> Hi, @fkokosinski can we merge this PR now?

Hi, unfortunately I don't have merge rights :) Usually every so often people with merge rights go through PRs with the required number of ACKs and merge them. We'll have to wait here till that happens

**Pull request merged**
