### PR TITLE
Bluetooth: controller: commentary and readability improvements

### PR DESCRIPTION
**Pull request by mped-oticon**
* Rename the stack local 'done' to 'evdone' so as to disambiguate from
  MFIFO_DEQUEUE_PEEK(done) which is actually 'mfifo_done'.

* add comment on ull_slave_done

* add comments to addr_us_get

* add comments to HCI_CLASS

Signed-off-by: Mark Ruvald Pedersen <mped@oticon.com>

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]
LGTM

**Comment by cvinayak** [comment]
General comment, could we use Bluetooth with B in capital case in the commit title, as its trademark name?

**Comment by mped-oticon** [comment]
> General comment, could we use Bluetooth with B in capital case in the commit title, as its trademark name?

Definitely. I'll fix.
Out of curiosity, here is what the precedence has been so far:
```
$ git log2 | grep -oi "bluetooth: controller" | freq
     69 bluetooth: controller
    115 Bluetooth: Controller
    473 Bluetooth: controller
```

**Comment by cvinayak** [comment]
@mped-oticon I started (i think) with "Bluetooth: Controller: ... " (BT Spec. uses Controller") but then noticed that the majority already used was "Bluetooth: controller:...".... its just nitpicking for now :-)

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
