### PR TITLE
net: Remove legacy TCP stack

### PR DESCRIPTION
**Pull request by jukkar**
Remove legacy TCP stack as it is replaced by the new TCP2 stack.
The TCP2 stack has been the default stack from 2.4 release.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by kevin0402** [comment]
@jukkar 
I am not sure if it is a good idea to remove legacy TCP stack support because some TCP features or requirements are supported in legacy TCP stack but not in TCP2.
To my understanding, there is no clear plan to implement these features in TCP2.
Some developers might not switch to TCP2 due to above reason.

**Comment by pfalcon** [comment]
> I am not sure if it is a good idea to remove legacy TCP stack support

I'd generally be concerned too with removing TCP1 so soon. **Especially** given that this PR removes tests, without adding replacement (or clearly explaining the situation in the commit message, like "tests/net/tcp/src/main.c is removed because there's tests/net/tcp/XXX/YYY which contains all the relevant testcases and fully supersedes it.")

**Comment by jukkar** [comment]
> I am not sure if it is a good idea to remove legacy TCP stack support because some TCP features or requirements are supported in legacy TCP stack but not in TCP2.
> To my understanding, there is no clear plan to implement these features in TCP2.

Could you elaborate what features are not supported in TCP2? The plan is to remove TCP1 so there is definitely a clear incentive to add any missing support to TCP2.

**Comment by jukkar** [comment]
> this PR removes tests

Those tests only work with TCP1 thus so they are not usable after the TCP1 is removed.

**Comment by pfalcon** [comment]
> Those tests only work with TCP1 thus so they are not usable after the TCP1 is removed.

Can you please add that info explicitly to the commit message? And an extra sentence elaborating why they work only with TCP1 would also helpful.

**Comment by kevin0402** [comment]
> > I am not sure if it is a good idea to remove legacy TCP stack support because some TCP features or requirements are supported in legacy TCP stack but not in TCP2.
> > To my understanding, there is no clear plan to implement these features in TCP2.
> 
> Could you elaborate what features are not supported in TCP2? The plan is to remove TCP1 so there is definitely a clear incentive to add any missing support to TCP2.

1. TCP2 does not support TCP window size update.
2. TCP2 does not send our MSS to peer : #30367 (TCP1 does not support either)
3. TCP2 does not implement TCP alive check mechanism. (TCP1 does not support either)
4. TCP2 is not stable enough. If you do TCP loop back burn-in test, the system will stop or even crash.
5. The throughput of TCP2 is even worse than TCP1.

**Comment by jukkar** [comment]
> * TCP2 does not support TCP window size update.

I will investigate this, it is probably easy to implement to TCP2.

> 
> * TCP2 does not send our MSS to peer : #30367 (TCP1 does not support either)
> 
> * TCP2 does not implement TCP alive check mechanism. (TCP1 does not support either)
> 
> * TCP2 is not stable enough. If you do TCP loop back burn-in test, the system will stop or even crash.

My experience has been different so far. TCP2 has been much more stable than TCP1, especially if you have limited number of net_buf's and net_pkt's and you run out of them. Note that you should use the very latest upstream for TCP2 as I fixed one memory leak last week.

> 
> * The throughput of TCP2 is even worse than TCP1.

This is interesting, I would like to hear what kind of testing you are using for that.

I did a short test with both `qemu_x86` and `sam_e70_xplained` boards:

**sam_e70_xplained**
First with TCP2
```
$ cd samples/net/sockets/dumb_http_server_mt
$ cmake -B build -DBOARD=sam_e70_xplained . -DCONFIG_LOG_BUFFER_SIZE=65536 -DCONFIG_LOG_STRDUP_BUF_COUNT=400 -DCONFIG_NET_PKT_RX_COUNT=100 -DCONFIG_NET_PKT_TX_COUNT=100 -DCONFIG_NET_BUF_RX_COUNT=400 -DCONFIG_NET_BUF_TX_COUNT=400 -DCONFIG_NET_MAX_CONN=64 -DCONFIG_NET_MAX_CONTEXTS=32 -DCONFIG_NET_SAMPLE_NUM_HANDLERS=8 -DCONFIG_NET_TCP1=n
$ make -C build -j 9 flash
```
Then in Linux side, I used wrk tool https://github.com/wg/wrk
```
$ wrk -d 5 -t 16 -c 1000 http://192.0.2.1:8080
Running 5s test @ http://192.0.2.1:8080
  16 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.45ms   26.05ms 212.08ms   98.31%
    Req/Sec   184.78    133.27   363.00     50.00%
  356 requests in 5.10s, 763.54KB read
  Socket errors: connect 0, read 380, write 0, timeout 0
Requests/sec:     69.84
Transfer/sec:    149.78KB
```
Then with TCP1
```
$ cd samples/net/sockets/dumb_http_server_mt
$ cmake -B build -DBOARD=sam_e70_xplained . -DCONFIG_LOG_BUFFER_SIZE=65536 -DCONFIG_LOG_STRDUP_BUF_COUNT=400 -DCONFIG_NET_PKT_RX_COUNT=100 -DCONFIG_NET_PKT_TX_COUNT=100 -DCONFIG_NET_BUF_RX_COUNT=400 -DCONFIG_NET_BUF_TX_COUNT=400 -DCONFIG_NET_MAX_CONN=64 -DCONFIG_NET_MAX_CONTEXTS=32 -DCONFIG_NET_SAMPLE_NUM_HANDLERS=8 -DCONFIG_NET_TCP1=y
$ make -C build -j 9 flash
```
The results were much worse with TCP1
```
./wrk -d 5 -t 16 -c 1000 http://192.0.2.1:8080
Running 5s test @ http://192.0.2.1:8080
  16 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    48.89ms  137.80ms 628.82ms   86.67%
    Req/Sec     5.58     11.38    50.00     88.46%
  45 requests in 5.10s, 94.04KB read
  Socket errors: connect 0, read 67, write 0, timeout 0
Requests/sec:      8.82
Transfer/sec:     18.44KB
```
The numbers are not very good for either of these examples but TCP2 was 8 times faster in this test.

**qemu_x86**
```
$ cmake -B build -DBOARD=qemu_x86 . -DOVERLAY_CONFIG=../echo_server/overlay-e1000.conf -DCONFIG_LOG_BUFFER_SIZE=65536 -DCONFIG_LOG_STRDUP_BUF_COUNT=400 -DCONFIG_NET_PKT_RX_COUNT=100 -DCONFIG_NET_PKT_TX_COUNT=100 -DCONFIG_NET_BUF_RX_COUNT=400 -DCONFIG_NET_BUF_TX_COUNT=400 -DCONFIG_NET_MAX_CONN=64 -DCONFIG_NET_MAX_CONTEXTS=64 -DCONFIG_NET_SAMPLE_NUM_HANDLERS=64 -DCONFIG_NET_TCP1=n
```
The TCP2 results:
```
$ wrk -d 5 -t 16 -c 1000 http://192.0.2.1:8080
Running 5s test @ http://192.0.2.1:8080
  16 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   134.43ms  277.62ms   1.42s    86.59%
    Req/Sec    13.94     31.32   130.00     90.91%
  99 requests in 5.04s, 224.38KB read
  Socket errors: connect 0, read 99, write 0, timeout 17
Requests/sec:     19.65
Transfer/sec:     44.53KB
```
and with TCP1:
```
wrk -d 5 -t 16 -c 1000 http://192.0.2.1:8080
Running 5s test @ http://192.0.2.1:8080
  16 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   483.17ms  238.02ms 625.42ms   66.67%
    Req/Sec     1.75      2.22     5.00     75.00%
  4 requests in 5.04s, 8.36KB read
  Socket errors: connect 0, read 4, write 0, timeout 1
Requests/sec:      0.79
Transfer/sec:      1.66KB
```

**Comment by pfalcon** [comment]
>         The throughput of TCP2 is even worse than TCP1.

I can't ack that either. In my list, TCP2 has slight (15-20%) performance improvement over TCP1. I base my evaluation based on downloading large file from real-world Internet, the `big_http_download` sample.

The opposite direction (device->host) is also interesting, but there was no easily usable option to test that. I now see that dumb_http_server_mt has an option to serve 100K file, but that still too little to assess sustained throughput. And `dumb_http_server_mt` is not POSIX-compliant app, so there's always suspicion that "it uses dirty Zephyr API hacks to workaround network stack issues". `dumb_http_server` remains the baseline test for me, and it shows much more humble figures comparing to the "adhoc Zephyr API/MT" version. And IMHO, we should target "unadorned BSD sockets" for performance optimizations first thing (and judge results by it).

**Comment by pfalcon** [comment]
This PR is also now explicitly marked as "2.6.0", which alleviates concern of removing TCP1 **too** soon. And AFAIK, 2.6 is supposed to be an LTS release, so the desire to remove TCP1 before it is understood - to not maintain 2 stacks in the LTS.

Note that I personally still not going to approve this, unless my suggestions for elaborating the commit message (https://github.com/zephyrproject-rtos/zephyr/pull/31744#issuecomment-773186687) are addressed. But given the above circumstances with LTS, that won't preclude merging this, someone else will for sure approve, no matter how bad the commit message is ;-).

**Comment by jukkar** [comment]
> * TCP2 does not support TCP window size update.
> * TCP2 does not send our MSS to peer : #30367 (TCP1 does not support either)

@kevin0402 See #32076, it has the TCP window size update and also sends our MSS to peer. Actually TCP1 supports sending MSS to peer already.
Please try and report if they do not work as expected.

**Comment by jukkar** [comment]
Fixed merge conflict.

**Review by galak — APPROVED** [review]

**Review by mengxianglinx — APPROVED** [review]
TCP2 is upgrade of TCP1, not a different tcp stack, even TCP2 is not perfect, we can improve it, rather than go back to TCP1

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
