### PR TITLE
Added option to sanitycheck script to enable ASAN and LSAN

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Added option to sanitycheck script to enable address - and leak sanitizer.

### CODE REVIEW

**Review by aescolar — APPROVED** [review]
(Assuming this is just the same as in #19093 with the requested fix, did not recheck)
Thanks

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
let's not have two simultaneous PRs for the same thing please

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
> let's not have two simultaneous PRs for the same thing please

i think this is fine, this just enables the feature in sanitycheck, the other one is about enabling this by default in CI, which still needs some agreement.

**Comment by andrewboie** [comment]
> i think this is fine, this just enables the feature in sanitycheck, the other one is about enabling this by default in CI, which still needs some agreement.

Maybe I'm not explaining myself well but I don't want this tied to sanitycheck at all...

**Comment by nashif** [comment]
> Maybe I'm not explaining myself well but I don't want this tied to sanitycheck at all...

oh ok.

**Comment by nashif** [comment]
> Maybe I'm not explaining myself well but I don't want this tied to sanitycheck at all...

actually, this is not going to be ideal, because not everyone declares them as TEST and the value of this is that you can run it on any application, sample or test, also on things that are out of the tree and that are not tests per se.

**Comment by andrewboie** [comment]
> actually, this is not going to be ideal, because not everyone declares them as TEST and the value of this is that you can run it on any application, sample or test, also on things that are out of the tree and that are not tests per se.

```
sanitycheck -p native_posix -x CONFIG_ASAN=y
```

**Comment by vanwinkeljan** [comment]
> sanitycheck -p native_posix -x CONFIG_ASAN=y

@andrewboie If you would run that for native_posix_64 it will deadlock

To get it working for native_posix_64 you would end up with:
` ASAN_OPTIONS="detect_leaks=0" sanitycheck -p native_posix_64 -x CONFIG_ASAN=y`

vs the one proposed by this PR

`sanitycheck -p native_posix_64 --enable-asan`

Now another issue with your example is the following invalid command (as valgrind and asan can't be combined):
`sanitycheck -p native_posix -x CONFIG_ASAN=y --enable-valgrind`

If you would try to give `sanitycheck -p native_posix --enable-asan --enable-valgrind` an error will be thrown to the user telling him that the options are not compatible.

**Review by tyrantlizard77 — APPROVED** [review]
I'm OK with this as long as it doesn't get enabled in CI.

**Pull request merged**
