### PR TITLE
boards: fix SPI GPIO CS, display, link_board_eth, dw1000

### PR DESCRIPTION
**Pull request by jfischer-no**
Since commit 5963eba
("drivers: spi: CS configuration through devicetree")
the SPI GPIO CS flags are obtained from DT,
but the patch series has missed the necessary changes
for the ieee802154_dw1000 driver and decawave_dwm1001_dev board,
and in the device trees for displays and link_board_eth.

### CODE REVIEW

**Review by MaureenHelm — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Comment by pabigot** [comment]
`boards/arm/reel_board/dts/reel_board.dtsi` also needs a fix.

**Comment by jfischer-phytec-iot** [comment]
> `boards/arm/reel_board/dts/reel_board.dtsi` also needs a fix.

I was not sure about that because e.g. a shield would definitely change it.

**Comment by pabigot** [comment]
> > `boards/arm/reel_board/dts/reel_board.dtsi` also needs a fix.
> 
> I was not sure about that because e.g. a shield would definitely change it.

I'm not sure about that: a shield overlay *might* change it, but one that assumes the standard Arduino SPI function positions might not.

In any case I think it's good for documentation: it's extremely unlikely that 0 is the correct flags value for a SPI chip-select signal, but people might see it here and copy it.

If you want it left as zero let me know; #26684 patches it to use `GPIO_ACTIVE_LOW`.

**Comment by jfischer-phytec-iot** [comment]
> In any case I think it's good for documentation: it's extremely unlikely that 0 is the correct flags value for a SPI chip-select signal, but people might see it here and copy it.

okay, let's do it this way.

**Pull request merged**
