### PR TITLE
boards: update STM32 disco boards name yaml property

### PR DESCRIPTION
**Pull request by erwango**
Update yaml property for STM32 Disco boards.
It is set to silkscreen name

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by mbolivar** [comment]
Ah, makes sense, thanks for clearing that up.

BTW, is there any plan to rename disco_l475_iot1, say to stm32l475_disco or so? It has kind of a different naming convention than all the others.

**Comment by erwango** [comment]
> BTW, is there any plan to rename disco_l475_iot1, say to stm32l475_disco or so? It has kind of a different naming convention than all the others.

There is no plan right now. I agree current naming "itches". disco_l475_iot1 was just the only name I had waiting of an official name. Then I was disappointed with official name that seems worse to me and not correct (B-L475**E**-IOT01A  > should be B-L475**G**-IOT01A).
Let's wait to see if more of the B-XXX-XXX are coming with some naming logic (I know there is a second with similar name around, but I'd like to see a real tendency)

**Comment by mbolivar** [comment]
> Let's wait to see if more of the B-XXX-XXX are coming with some naming logic

Makes sense, thanks for the explanation.

**Comment by galak** [comment]
Do we want to do something similar in the .dts files?

**Review by galak — APPROVED** [review]

**Pull request merged**
