### PR TITLE
Revert "Implement net_context locking"

### PR DESCRIPTION
**Pull request by galak**
Reverts zephyrproject-rtos/zephyr#8674

This seems to break CI right now as there are failures in:

```
qemu_x86:
   tests/net/lib/dns_resolve/net.dns
   tests/net/lib/dns_resolve/net.dns.no_ipv6

...
===================================================================
starting test - dns_query_ipv6_numeric
PASS - dns_query_ipv6_numeric
===================================================================
Test suite dns_tests succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
***** CPU Page Fault (error code 0x00000002)
Supervisor thread wrote address 0x00000000
PDE: 0x025 Present, Read-only, User, Execute Enabled
PTE: 0x00 Non-present, Read-only, Supervisor, Execute Enabled
Current thread ID = 0x00401740
eax: 0x004016f0, ebx: 0x004016f0, ecx: 0x00000000, edx: 0x00000000
esi: 0x00000246, edi: 0x00000000, ebp: 0x0041c7d4, esp: 0x0041c7d4
eflags: 0x00000046 cs: 0x0008
call trace:
eip: 0x0000ea43
     0x0000ed2a (0x41c7e0)
     0x00004b38 (0x30)
     0x0000bf09 (0x4160e4)
     0x00002d08 (0x0)
Fatal fault in ISR! Spinning...
Terminate emulator due to fatal kernel error
```

### CODE REVIEW

**Review by tbursztyka — CHANGES_REQUESTED** [review]
Let's not revert: it is a necessary patch. Let's fix the bug it introduced instead.

**Comment by galak** [comment]
> Let's not revert: it is a necessary patch. Let's fix the bug it introduced instead.

I'm fine w/that, just need a quick solution since this breaks CI for everyone!

**Comment by tbursztyka** [comment]
@galak Let's say if we don't get a solution in ~2h, you'll be able to push your revert?

**Comment by jukkar** [comment]
Actually the tests pass, it is just that at the end there is a crash. Investigating...

**Comment by jukkar** [comment]
I have a "fix" proposal at #12926

**Pull request closed without merging**
