### PR TITLE
samples: subsys: usb: mass: add support for Adafruit feather nRF52840

### PR DESCRIPTION
**Pull request by gmarull**
Add configuration and overlay files for Adafruit feather nRF52840.
README has also been updated and improved. Documentation related to
littlefs has been moved to an independent section as it could apply to
any sample.

Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
A couple minor nits in the wording, but this looks good otherwise.

**Review by pabigot — APPROVED** [review]

**Review by jfischer-no — COMMENTED** [review]
@nashif @MaureenHelm @carlescufi @pabigot We already have an overlay for nRF (nRF52840) platform and SPI flash in the sample. This is just another combination. Do we really want to have overlays and a separate chapter in the documentation for all possible combinations? I think we should limit it, if it is not generic enough there should be only one example per platform.

**Comment by pabigot** [comment]
> This is just another combination.

I'm sympathetic to that view.  I decided that SPI+FatFs was likely more common that SPI+littlefs so it was worth adding it.  Also separating out the littlefs mount instructions from the board-specific sample makes sense and improves things.

There certainly should be a limit to how many variations are explicitly supported in a sample, but where that limit should be enforced is not clear.

**Review by carlescufi — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
> @nashif @MaureenHelm @carlescufi @pabigot We already have an overlay for nRF (nRF52840) platform and SPI flash in the sample. This is just another combination. Do we really want to have overlays and a separate chapter in the documentation for all possible combinations? I think we should limit it, if it is not generic enough there should be only one example per platform.

I sort of disagree. This is all contained in a `boards/` folder, and as far as the documentation goes, we can always try to find a format that is more compact to display all the pre-provided configurations for several boards.

**Pull request merged**
