### PR TITLE
tests: static_idt: Add description and RTM links

### PR DESCRIPTION
**Pull request by ajaykish**
Add doxygen groups, description and RTM links for
static idt test cases

Signed-off-by: Ajay Kishore <ajay.kishore@intel.com>

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
why are you changing checkpatch.pl?

**Comment by ajaykish** [comment]
@nashif I was getting below warnings during execution of ./scripts/checkpatch.pl for tests/kernel/static_idt/src/main.c :

tests/kernel/static_idt/src/main.c:92: WARNING:FUNCTION_ARGUMENTS: function definition argument 'exc_divide_error_handler' should also have an identifier name
#92: FILE: tests/kernel/static_idt/src/main.c:92:
+extern void *_EXCEPTION_STUB_NAME(exc_divide_error_handler, IV_DIVIDE_ERROR);

tests/kernel/static_idt/src/main.c:92: WARNING:FUNCTION_ARGUMENTS: function definition argument 'IV_DIVIDE_ERROR' should also have an identifier name
#92: FILE: tests/kernel/static_idt/src/main.c:92:
+extern void *_EXCEPTION_STUB_NAME(exc_divide_error_handler, IV_DIVIDE_ERROR);

So added support function pointers for unnamed function definition in checkpatch.pl.

**Comment by nashif** [comment]
> So added support function pointers for unnamed function definition in checkpatch.pl.

thats not how it works, you cant just be patching checkpatch whenever you get some warnings or errors, if you think you can improve checkpatch, send a separate patch with the enhancement, otherwise you can raise this issue in the PR as being a false negative for reviewers to ignore it.

**Comment by ajaykish** [comment]
@nashif removed the checkpatch related changes, and raised a GH issue #9411 for the warning generated by checkpatch.pl.

**Review by nashif — APPROVED** [review]

**Pull request merged**
