### PR TITLE
boards: arm: bt610: Rename from bt6x0

### PR DESCRIPTION
**Pull request by nordicjm**
The BT6x0 board configuration is only valid for the BT610 device,
therefore rename the boards file to BT610

Signed-off-by: Jamie McCrae <jamie.mccrae@lairdconnect.com>

### CODE REVIEW

**Review by tejlmand — CHANGES_REQUESTED** [review]
please add the old board name here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/deprecated.cmake

**Comment by lairdjm** [comment]
> please add the old board name here:
> https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/deprecated.cmake

Fixed

**Comment by lairdjm** [comment]
@nashif looks like an issue on the buildkite server, out of space.

**Review by tejlmand — APPROVED** [review]
lgtm

**Comment by cfriedt** [comment]
@lairdjm - might be necessary to rebase on main to get past those xtensa bugs

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
