### PR TITLE
ext: mbedtls: Don't define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS

### LINKED ISSUE #16303: mbedtls: config-tls-generic.h: MBEDTLS_PLATFORM_NO_STD_FUNCTIONS seems ungrounded
I recently spent a bunch of time debugging following issues: with debug logging enabled in mbedTLS, some messages are printed ok, some not, a bit of garbage was printed. Turned out, that we have MBEDTLS_PLATFORM_NO_STD_FUNCTIONS and MBEDTLS_PLATFORM_SNPRINTF_ALT defined in config-tls-generic.h. This causes mbedTLS to provide a dummy snprintf implementation, which then used in debug output which is broken.

However, mbedTLS isn't consistent with enforcing MBEDTLS_PLATFORM_NO_STD_FUNCTIONS in this way, and in other output just uses vsnprintf() without extra indirections similar to MBEDTLS_PLATFORM_SNPRINTF_ALT. Such output worked.

This makes me wonder why MBEDTLS_PLATFORM_NO_STD_FUNCTIONS is unconditionally defined at all. I guess (well, just guess so far) that the core of mbedTLS doesn't depend on too much of libc functionality. Then it's used only for optional things, like debug logging, and if user has enabled it, it would rather work out of box (by pulling in libc funcs, yeah, that's ok and expected).

Failing "work out of the box approach" (we shouldn't fail that), another approach would be "make configurable, and error out when needed, but not enabled". But the case "silently misbehave", as described above, should be avoided.

### PR DESCRIPTION
**Pull request by pfalcon**
That means that when mbedTLS will need functions like snprintf(),
printf(), a few others, they will be used from libc, as done
normally by most of software. Note that mentioned functions
aren't normally used on code paths doing TLS communication per se.
Instead, they are used by debug logging, additional "print info"
style functions, etc.

Before, when MBEDTLS_PLATFORM_NO_STD_FUNCTIONS was defined, those
functions were stubbed out, so silently didn't work as expected
(a specific symptom seen was that some debug messages were printed
as garbage, because an buffer on stack was passed to dummy snprintf
stub, which didn't do anything to it, and its uninitialized contents
were printed afterwards. Instead, the expectation was that an
application would call a "setter" function to set snprintf, etc.
implementations as provided by application itself.

For Zephyr, we clearly don't need to burden applications with such
setup, instead Zephyr, as an OS, provides integrated environment
were matters like that "just work". So, we just switch to libc-based
functions. If there ever will be usecases for
MBEDTLS_PLATFORM_NO_STD_FUNCTIONS, it can be made configurable later.

Fixes: #16303

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
@galak, @d3zd3z: One of the "aux" changes done while working on GoogleIoT port.

**Comment by pfalcon** [comment]
@mike-scott: Please have a look too, so you were in loop/it didn't go against your expectations.

**Review by rlubos — APPROVED** [review]
LGMT

**Review by jukkar — APPROVED** [review]

**Comment by mike-scott** [comment]
@pfalcon Thanks for the heads up.  Seems ok from my point of view.

**Review by mike-scott — APPROVED** [review]

**Comment by pfalcon** [comment]
Thanks. Will look into test breakage when time permits.

**Comment by pfalcon** [comment]
Fixed up tests here, should be ready to merge.

**Pull request merged**
