### PR TITLE
Add rgb565 font

### PR DESCRIPTION
**Pull request by hakehuang**
This pull request is  based on #22087 comments

### CODE REVIEW

**Comment by vanwinkeljan** [comment]
I dont see how this PR s resolving/addressing following comment from https://github.com/zephyrproject-rtos/zephyr/pull/22087#issuecomment-585251728

> BTW, I tested it and the problem with RGB565 support in CFB is that the memory consumption is far too high and this PR is not acceptable yet. Either CFB should be reworked and use partial write or be replaced by LVGL.

**Comment by hakehuang** [comment]
> I dont see how this PR s resolving/addressing following comment from [#22087 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/22087#issuecomment-585251728)
> 
> > BTW, I tested it and the problem with RGB565 support in CFB is that the memory consumption is far too high and this PR is not acceptable yet. Either CFB should be reworked and use partial write or be replaced by LVGL.

hi @vanwinkeljan , the memory issue is not CFB issue, but zephyr kernel, it does not have a mechanism to support large memory.  do you have discussion thread on this topic? I want to see the progress. Thanks.

**Comment by vanwinkeljan** [comment]
> the memory issue is not CFB issue

The problem is that the current CFB implementation assumes it has a full frame buffer available.
For small monochrome displays this is not an issue but for color displays this requires a large amount of RAM and CFB should be extended to support partial buffer writing.

**Comment by hakehuang** [comment]
thanks @vanwinkeljan

**Pull request closed without merging**
