### PR TITLE
cmake: compiler: clang: target.cmake: Add arm target

### PR DESCRIPTION
**Pull request by sigvartmh**
Adds `-mcpu and -mfloat-abi` to compiler flags if you try to compile for
the ARM architecture using llvm.

Signed-off-by: Sigvart Hovland <sigvart.m@gmail.com>

### CODE REVIEW

**Review by galak — COMMENTED** [review]
This technically adds arc as well as arm.

**Comment by sigvartmh** [comment]
I'll try to have a look to try to see why. Honestly I only wanted the llvm bytecode :) which I think I can get it to output.

I'll also try to clean up the build code.

**Comment by sigvartmh** [comment]
Seems if you disable multi-threading it works. Seems it MPU faults for some reason. I'll have a look into it.

**Comment by sigvartmh** [comment]
My assumption is that since you are using the arm-none-eabi-as clang don't see that start of main is used and it's optimized away.

**Pull request closed without merging**
