### PR TITLE
drivers: flash: stm32l4x: Fix uninitialized variable

### LINKED ISSUE #18361: [Coverity CID :203515]Uninitialized variables in /drivers/flash/flash_stm32l4x.c
Static code scan issues seen in File: /drivers/flash/flash_stm32l4x.c
 Category: Uninitialized variables
 Function: erase_page
 Component: Drivers
 CID: 203515
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by gon1332**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/18361

### CODE REVIEW

**Comment by gon1332** [comment]
@aescolar Could you check?

**Review by ioannisg — COMMENTED** [review]
Not sure if this is, now, needed, after @erwango 's latest work...
@erwango could you take a look?

**Comment by aescolar** [comment]
This is the commit @ioannisg referred to: 0381e8cbe991763176168c922ff8a11d91045ef3

**Review by erwango — COMMENTED** [review]
I'm not clear if this is really needed to fix coverity report.

Though, from functional point of view this doesn't add much since it initializes variable to a value which would, if used, generate a silent issue. So ideally, it should be coupled with a check of the variable before being used. But maybe this is overkill.

So, if https://github.com/zephyrproject-rtos/zephyr/issues/18361 is fixed by https://github.com/zephyrproject-rtos/zephyr/commit/0381e8cbe991763176168c922ff8a11d91045ef3, I'd propose to  reject this patch.

**Comment by aescolar** [comment]
Closing as the issue seems to be corrected with the patch in 0381e8c
If needed please reopen

**Pull request closed without merging**
