### PR TITLE
sensor: vcnl4040: Update dts binding for defaults

### PR DESCRIPTION
**Pull request by galak**
* Add comments about the default settings
* Change proximity-trigger default to match POR of 'disabled'
* Added reference to datasheet

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
Nice.

**Review by pabigot — CHANGES_REQUESTED** [review]
The changes look good, but I think we should have a section in the release notes to record when a defaulted property is changed, as this affects how existing out-of-tree devicetree sources will be interpreted.

**Review by MaureenHelm — APPROVED** [review]
Curious what prompted this?

**Comment by mbolivar-nordic** [comment]
> Curious what prompted this?

https://github.com/zephyrproject-rtos/zephyr/pull/28817

**Comment by galak** [comment]
> The changes look good, but I think we should have a section in the release notes to record when a defaulted property is changed, as this affects how existing out-of-tree devicetree sources will be interpreted.

Do you think under `API Changes` or `Sensor` section?

**Comment by galak** [comment]
> Curious what prompted this?

Auditing of 'default' usage in dts bindings.

**Comment by pabigot** [comment]
> @pabigot - Do you think under `API Changes` or `Sensor` section?

Not sensor, devicetree bindings cover the entire system, so API Changes.  Ideally within a group specific to Devicetree but it doesn't look like API Changes has any structure right now.

**Review by pabigot — APPROVED** [review]
Seems reasonable, anybody who cares can look at the diff to see what the impact of the change is.

**Pull request merged**
