### PR TITLE
board: arm: sensortile_box: add user button 1

### PR DESCRIPTION
**Pull request by asabil**
Add the USERPB1 button to the sensortile.box device tree

### CODE REVIEW

**Review by avisconti — COMMENTED** [review]
Looks good! How did you test it? Is it worth to add a simple sample code?

**Comment by asabil** [comment]
It was tested using a small sample program and the board. I don't see many existing board tests in the zephyr `tests/boards` for the sensortile.box, any recommendations on how/where to add a test?

**Review by henrikbrixandersen — APPROVED** [review]
Looks good. Testing should be possible using `samples/basic/button/`.

**Comment by asabil** [comment]
Anything else required on my side to have this moving forward?

**Review by avisconti — APPROVED** [review]

**Pull request merged**
