### PR TITLE
samples: bluetooth: move GATT services to subsys/bluetooth

### PR DESCRIPTION
**Pull request by lemrey**
This commit moves the BLE GATT service implementations from:
- _samples/bluetooth/gatt_ to
- _subsys/bluetooth/services_.

This new location is tentative and feedback is appreciated.

The rationale behind this change is to have these services appear as re-usable pieces of code rather than code snippets developed just for a few examples, and thus encourage and facilitate contributions.

### CODE REVIEW

**Comment by jhedberg** [comment]
The main reason the services have not been put under subsys/bluetooth/ is that then they become an official API with stability requirements. E.g. I'm far from confident that the current APIs are sufficient for real-life use cases and real hardware-based data sources. E.g. the HID and battery services just generate dummy data at the moment.

**Comment by Vudentz** [comment]
Ideally we would want to have each service behind a Kconfig option and then the application just have to enable it without having to interface with the application, but Im afraid that doesn't apply to every service, for instance we could do something like that for battery but then we need a driver interface that would give the readings to the service. For services that cannot be simply enabled via Kconfig and leave it in samples since that is just a reference how the attributes would look like, nothing more.

**Comment by lemrey** [comment]
@Vudentz I see the picture. Several BLE GATT services could interface directly to a sensor interface implementation, requiring a very small effort to be included in an application. However, this won't the case for _all_ BLE service in the future; some services could be self-cointained, other might need to interface with the application. Ultimately, those won't be used just as references for the attributes and would be better located in a different folder.

**Comment by cvinayak** [comment]
We need to mature the standard service behavior in a more stable well-known place in the repo, so that services/profiles can be qualified and design listed. Keeping all of the service implementation in application make it difficult to justify a BT design listing.

For starters, atleast mandatory features in the service/profile be maintained, and be presented for design listing. We have hold any optional ones under EXPERIMENTAL Kconfig.

**Comment by carlescufi** [comment]
@pdunaj @kapi-no can you please weigh in on this?

**Comment by carlescufi** [comment]
@lemrey @jhedberg Perhaps we could consider moving the services one by one, so that for each of them we actually get some feedback (I am hoping to get some from @pdunaj and @kapi-no) on real-world requirements for those.

**Comment by pdunaj** [comment]
Hi @carlescufi , at the moment we are not using anything from samples. I consider samples a demonstration/example code and don't want to point there.

We have our own copy of dis and bas (until these services will be implemented as subsystems).
We also use hids implemented by @kapi-no and company. This service is configurable via Kconfig.

**Comment by lemrey** [comment]
@carlescufi Moving the services one by one is a good idea.

If we are to categorize these services, we'd have at least two categories:
- self-contained service, like the Device Information service
These could at least be given a Kconfig entry to make them easy to pull in a project and customize
- services that mock up sensor data, like the Battery service
These services could maybe interface with sensor.h; a mockup sensor driver could be implemented to achieve the same functionality of the current implementation. In the future, users could select a new sensor data "source" via Kconfig and have the service work on real hardware with little effort.

The goal is to have a base of re-usable service implementations that can be easily pulled in by the application via Kconfig and that require the least amount of interfacing with the application. It won't be possible to avoid interfacing with the application in all cases though, and ultimately we might provide callback-based service implementations; imo those shouldn't be put in samples because they will be widely re-used.

@Vudentz @jhedberg Perhaps I could work in this direction on these two services and open PRs?

**Comment by jhedberg** [comment]
> @Vudentz @jhedberg Perhaps I could work in this direction on the two services above and open PRs?

@lemrey yes, sounds good to me.

**Comment by lemrey** [comment]
I will continue this work in several PRs each related to one service.
The first PR for the battery service is https://github.com/zephyrproject-rtos/zephyr/pull/9735.

**Pull request closed without merging**
