### PR TITLE
USB: netusb: rndis: Fix always disabled (on MS Windows)

### PR DESCRIPTION
**Pull request by finikorg**
Fixes regression.

### CODE REVIEW

**Review by jfischer-no — COMMENTED** [review]
LGTM

**Review by jukkar — APPROVED** [review]
Tested this and the device appears in windows 8, +1 from me.

**Review by loicpoulain — APPROVED** [review]

**Review by loicpoulain — CHANGES_REQUESTED** [review]
Did you check there is no regression for ECM and EEM on Linux ?

**Comment by finikorg** [comment]
@loicpoulain quickly tested ECM and EEM, they are working

**Review by loicpoulain — APPROVED** [review]

**Pull request merged**
