### PR TITLE
driver: sensor: Add i2c_label and i2c_addr in the max30101_config st…

### PR DESCRIPTION
**Pull request by aakkds**
Add i2c_label and i2c_addr in config struct and use the sensor address coming from the device tree rather than a macro.

### CODE REVIEW

**Comment by galak** [comment]
LGTM, Just curious the reason / need for this change?

**Comment by aakkds** [comment]
Hey @galak thanks for checking!
I received an hexiboard and was looking at what the upstream drivers supported when I noticed that the address was "hardcoded" in the header instead of retrieved from the device tree. I guess it was not modified because this address is fixed and not configurable for example with a pin put to GND or VCC.
As I see zephyr taking the direction of using device tree whenever possible, I took the opportunity to add the bus label/address in the config struct.

No particular need except trying to be more coherent with the rest of the code base (it is working perfectly fine without this of course).

**Review by pabigot — CHANGES_REQUESTED** [review]
Please squash these commits into one.  Though Zephyr doesn't make require bisectability within PRs, it's trivial (and common) to maintain it in this sort of change.

Other than that this looks fine.

**Comment by aakkds** [comment]
@pabigot Sure! It is done

**Review by pabigot — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
