### PR TITLE
tests: obj_tracing: Convert legacy test to ztest

### PR DESCRIPTION
**Pull request by punitvara**
Use ztest API in legacy test to support ztest
framework.

Signed-off-by: Punit Vara <punit.vara@intel.com>

### CODE REVIEW

**Comment by punitvara** [comment]
@AdithyaBaglody  Can you please review this ?

**Review by nashif — CHANGES_REQUESTED** [review]
look at the output, there is something wrong here:

```
***** BOOTING ZEPHYR OS v1.9.99 - BUILD: Oct 28 2017 16:44:05 *****
Running test suite test_obj_tracing
===================================================================
starting test - test_tracing
starting test - OBJECT TRACING TEST
SEMAPHORE REF: 0x004002f0
SEMAPHORE REF: 0x004002dc
SEMAPHORE REF: 0x004002c8
SEMAPHORE REF: 0x004002b4
SEMAPHORE REF: 0x004002a0
SEMAPHORE REF: 0x0042402c
SEMAPHORE QUANTITY: 5
PASS - object_monitor.
===================================================================
PASS - test_tracing.
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
COOP: 0x00400060 OPTIONS: 0x00, STATE: 0x00
COOP: 0x00400230 OPTIONS: 0x00, STATE: 0x00
COOP: 0x004001d4 OPTIONS: 0x00, STATE: 0x00
COOP: 0x00400178 OPTIONS: 0x00, STATE: 0x02
COOP: 0x0040011c OPTIONS: 0x00, STATE: 0x02
COOP: 0x004000c0 OPTIONS: 0x00, STATE: 0x00
PREMPT: 0x00401254 OPTIONS: 0x00, STATE: 0x02
COOP: 0x00401020 OPTIONS: 0x01, STATE: 0x00
THREAD QUANTITY: 8
PASS - test_thread_monitor.
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Comment by punitvara** [comment]
@nashif  need to arrange code. I will fix it

**Comment by punitvara** [comment]
In output one extra semaphore is printed as well one thread. Its because of with ztest, one extra thread adds to current threadlist and ztest uses one semaphore so its also added while object calculation. Is there any way to get rid or this ? I am not sure whether this test case qualify for ztest because in side test case one if condition checks for priority -1 and after introducing ztest has priority -1 so things are messing up because of that. what is your opinion in about this test ?

**Comment by nashif** [comment]
still the same problem:
```
***** BOOTING ZEPHYR OS v1.9.99 - BUILD: Nov 15 2017 14:28:19 *****
Running test suite test_obj_tracing
===================================================================
starting test - test_tracing
starting test - OBJECT TRACING TEST
SEMAPHORE REF: 0x004002d0
SEMAPHORE REF: 0x004002bc
SEMAPHORE REF: 0x004002a8
SEMAPHORE REF: 0x00400294
SEMAPHORE REF: 0x00400280
SEMAPHORE REF: 0x0042402c
SEMAPHORE QUANTITY: 5
PASS - object_monitor.
===================================================================
PASS - test_tracing.
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
COOP: 0x00400040 OPTIONS: 0x00, STATE: 0x00
COOP: 0x00400200 OPTIONS: 0x00, STATE: 0x00
COOP: 0x004001a8 OPTIONS: 0x00, STATE: 0x00
COOP: 0x00400150 OPTIONS: 0x00, STATE: 0x02
COOP: 0x004000f8 OPTIONS: 0x00, STATE: 0x02
COOP: 0x004000a0 OPTIONS: 0x00, STATE: 0x00
PREMPT: 0x00401254 OPTIONS: 0x00, STATE: 0x02
COOP: 0x00401020 OPTIONS: 0x01, STATE: 0x00
THREAD QUANTITY: 8
PASS - test_thread_monitor.
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL

```

Why do we have 'PROJECT EXECUTION SUCCESSFUL' twice?

**Comment by punitvara** [comment]
@nashif  Done

**Comment by punitvara** [comment]
@AdithyaBaglody  looks fine ?

**Review by AdithyaBaglody — APPROVED** [review]
LGTM

**Comment by punitvara** [comment]
@nashif Can you please merge this ?

**Review by nashif — APPROVED** [review]

**Pull request merged**
