### PR TITLE
stm32: dts: h7: added stm32h753

### PR DESCRIPTION
**Pull request by mkainy**
I do my first open source PR. So there may be a lot of problems. Please review stm32h753.dtsi to use stm32h753_eval.

### CODE REVIEW

**Comment by stephanosio** [comment]
@mkainy Once again, you are adding 3 previous fix-up commits in this PR. Please drop the previous 3 commits and only submit the last one.

1. ```git rebase -i HEAD~4```
2. ```
    p
    f
    f
    s
    ```
3. Finalise commit message.
4. Push

**Comment by mkainy** [comment]
Thank you for helping.
I am very new to git the first time.
I want to delete all my current git heads and start over.
Is this okay?

**Comment by mkainy** [comment]
@stephanosio I have another question.
I want to erase my closed PR history.
Is that possible?

**Comment by stephanosio** [comment]
> @stephanosio I have another question.
> I want to erase my closed PR history.
> Is that possible?

Pull requests cannot be deleted. If your PR contains incorrect commits, you can always modify the commits and force-push (you do not need to close and open a new PR).

**Comment by stephanosio** [comment]
> I want to delete all my current git heads and start over.

Try `git reset --hard master` in the PR branch.

**Pull request closed without merging**
