### PR TITLE
Bluetooth: Host: Remove experimental tag from periodic adv and sync

### PR DESCRIPTION
**Pull request by rugeGerritsen**
We have done sufficient testing to claim that the host is no longer
experimental.

### CODE REVIEW

**Review by alwa-nordic — APPROVED** [review]

**Comment by jhedberg** [comment]
I assume this is for 3.1, since normally API lifecycle changes (experimental to stable promotions, deprecations and removal of deprecated APIs) happens right after the feature merge window opens, not right after it has closed?

**Comment by rugeGerritsen** [comment]
> I assume this is for 3.1, since normally API lifecycle changes (experimental to stable promotions, deprecations and removal of deprecated APIs) happens right after the feature merge window opens, not right after it has closed?

@jhedberg , I would like to get this merged for 3.0. I have not been aware of the fact that experimental labels are removed right after the merge window opens. Is this still something that can be done? Until recently we have found and fixed a couple of bugs in this implementation. We now believe the implementation is stable enough.

**Comment by jhedberg** [comment]
@rugeGerritsen the general rule for the feature freeze is that only bug fixes and documentation updates are accepted in the tree. I'm not sure how API classification changes fit into that. @carlescufi do you have any thoughts on this?

**Comment by Thalley** [comment]
> We have done sufficient testing to claim that the host is no longer experimental.

What are the success criteria for removing [EXPERIMENTAL]? PTS testing passing?

Since this will rely on the Zephyr controller (when not using a 3rd party), shouldn't the same be done for the controller? 
e.g. just enabling these Kconfigs in the host won't give you a working build.  

@cvinayak Any input?

**Comment by rugeGerritsen** [comment]
> e Zephyr controller (when not using a 3rd party), shouldn't the same be done for the controller?
> e.g. just enabling these Kconfigs in the host won't give you a working build.

The testing has not been done with the Zephyr controller. We have run an extensive amount of tests, including the PTS tests.

**Comment by cvinayak** [comment]
> > We have done sufficient testing to claim that the host is no longer experimental.
> 
> What are the success criteria for removing [EXPERIMENTAL]? PTS testing passing?
> 
> Since this will rely on the Zephyr controller (when not using a 3rd party), shouldn't the same be done for the controller? e.g. just enabling these Kconfigs in the host won't give you a working build.
> 
> @cvinayak Any input?

Host and Controller are different component, Zephyr Bluetooth Host can be used with other conformant Controllers for testing and be verified to be non-experimental. 

Periodic Advertising in Zephyr Controller has couple more enhancements to be completed, hence the feature in Zephyr Controller will remain experimental.

The Periodic Advertising and  Synchronization samples in Zephyr do build by default on supported boards with experimental warning when Zephyr Controller is used.

Whether to switch experimental to non-experimental at this last moment of the v3.0.0 release, I agree with @jhedberg but probably the release team can take a decision on it.

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
@jhedberg can you confirm this is ok to merge now?

**Pull request merged**
