### PR TITLE
release: Zephyr v3.6.0-rc1

### PR DESCRIPTION
**Pull request by MaureenHelm**
Sets the version to v3.6.0-rc1.

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]
LGTM - I think the CI issue is unrelated 😏

**Comment by henrikbrixandersen** [comment]
> LGTM - I think the CI issue is unrelated 😏

It does not look "unrelated":

`    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/shell/shell_backend_uart/src/main.c:65: shell_backend_uart_test_backend_euart0_version: tx_content not equal to "Zephyr version " "3.6.0-rc1"
`

**Comment by henrikbrixandersen** [comment]
There's a mismatch between was is printed in `kernel_service.c` and what is expected in the test. The former uses `	shell_print(sh, "Zephyr version %d.%d.%d", SYS_KERNEL_VER_MAJOR(version), SYS_KERNEL_VER_MINOR(version), SYS_KERNEL_VER_PATCHLEVEL(version))` whereas the test expect `"Zephyr version " KERNEL_VERSION_STRING` (which includes the `EXTRAVERSION`).

**Comment by henrikbrixandersen** [comment]
Proposed fix: https://github.com/zephyrproject-rtos/zephyr/pull/68579

**Review by fabiobaltieri — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
