### PR TITLE
doc: fs: samples: Use new Sphinx extension to document samples

### PR DESCRIPTION
**Pull request by kartben**
Use the new code-sample directive and roles to document the filesystem samples so that they show up as "Related samples" when browsing the API documentation.

### CODE REVIEW

**Comment by Laczen** [comment]
Hi @kartben, what is the new code-sample directive and roles?

**Comment by kartben** [comment]
> Hi @kartben, what is the new code-sample directive and roles?

See e.g. https://docs.zephyrproject.org/latest/hardware/peripherals/gpio.html#api-reference

This gets auto-populated based on a new directive that can be used to describe code -sample more uniformly, including listing what API they are a good showcase of

https://github.com/zephyrproject-rtos/zephyr/blob/a477bddc59901912a6f176658bcab20ced229e10/samples/basic/blinky/README.rst?plain=1#L1-L5

**Comment by kartben** [comment]
Live site: https://builds.zephyrproject.io/zephyr/pr/62363/docs/services/file_system/index.html#api-reference

**Review by tmon-nordic — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Yay!

**Comment by kartben** [comment]
> Yay!

I appreciate the enthusiasm (I really do!) :)

**Pull request merged**
