### PR TITLE
samples: esp32: move board-specific ESP32 ipm sample

### PR DESCRIPTION
**Pull request by kartben**
The ESP32 ipm sample should live with board-specific samples.

Signed-off-by: Benjamin Cabé <benjamin@zephyrproject.org>

### CODE REVIEW

**Review by sylvioalves — COMMENTED** [review]
@kartben, makes sense. Thanks.

**Review by sylvioalves — APPROVED** [review]

**Comment by kartben** [comment]
> @kartben, makes sense. Thanks.

no problem :) 
BTW I didn't bother opening an issue for it, but I noticed `deep_sleep` and `light_sleep` samples are missing a `sample.yaml`. I would be nice to add it so that they go through CI.

**Review by marekmatej — APPROVED** [review]

**Review by uLipe — CHANGES_REQUESTED** [review]
All the IPM samples are platform specific, not board specific.

Other point the IPM driver is about to be deprecated in favor of mailbox driver, so I would avoid to add or change anything here.

**Comment by uLipe** [comment]
If the intention is to remove all the samples from IPM to their own vendor related folder, I would like to see it into a single PR instead of by vendor one, since this is a sistematic change.

If the intention is to just move the esp32 IPM, I don't see any reason for that since all the IPM samples here have platform specific changes, check the other samples and you will see each sample has different code.

Other thing to do here if the IPM samples could be more platform agnostic is to pack them into a single sample and push their diffenrence into a board directory with their .overlay plus .conf related to the target platform.

**Comment by kartben** [comment]
Closing the PR for now. @uLipe is raising a lot of good points and I initially didn't realize that *all* IPM samples are actually HW specific.

**Pull request closed without merging**
