### PR TITLE
logging: Revamp menuconfig

### PR DESCRIPTION
**Pull request by nordic-krch**
Clean up logging menuconfig by grouping configuration into
sections like: mode, processing configuration, backends.

Additionlly, removed LOG_ENABLE_FANCY_OUTPUT_FORMATTING which is no
longer in use.

After cleanup logging menu look like in the screens below.

Main menu:
image

Mode menu:
image

Filtering:
image

Output formatting:
image

Processing:
image

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by jukkar — APPROVED** [review]
LGTM

**Review by jakub-uC — APPROVED** [review]
Great change.
I will do similar change in the shell

**Review by dcpleung — APPROVED** [review]

**Comment by pfalcon** [comment]
> Clean up logging menuconfig

Clean up is a good thing, but based on the screenshots provided, I wonder if a bit more effort could be put into it...

> Mode menu:

I'm not sure what "mode: frontend" would mean. Perhaps, more words could help.

> Filtering:

Setting logging levels is the baseline operation. I'm not sure how burying that in submenu helps users. (For example, someone who'd cursory look at the top-level logging menu, would get an impression that it's not possible to adjust logging levels in Zephyr, because classifying loglevels under "filtering" is quite a scholastic exercise. "minimal-footprint" and "drop when full" also can be classified as "filtering" (they filter something, no?), and yet they aren't. Likewise, log levels should be just log levels, and preferrably, right at the fingertips).

> Output formatting:

Reading "mipi syst", I thought there was some line noise and lost characters when making screenshot, it took me some googling to figure out that actually "MIPI SyS-T" was meant.

> Processing

The screenshot shows that a couple of options inconsistently have a dot at the end. Can't parse the "On log full block in thread context" option name at all. "Amount of buffered logs which triggers processing thread": something like "Number of buffered log messages before flushing" would be clearer.

**Comment by nordic-krch** [comment]
@pfalcon thanks for your comments. 
- Added more help to frontend and deferred modes
- Renamed `Filtering` to `Logging levels filtering`.
- Applied comments from "processing" section

I did not modified mipi syst, I am not familiar with that so dont want to rephrase it just copied what was before.

**Comment by pfalcon** [comment]
@nordic-krch: Thanks for the updates!

> I did not modified mipi syst, I am not familiar with that so dont want to rephrase it just copied what was before.

Well, googling that leads to https://www.mipi.org/specifications/sys-t, where the official spelling is clear: "MIPI SyS-T". (So it's a common case that in colloquial writing we use lowercase abbreviations, it more official writing (like configuration descriptions), it would be nice to follow grammatically correct writing, or it may look just like misspelling to someone not familiar with a particular abbreviation).

**Comment by nordic-krch** [comment]
@pfalcon done

**Review by pfalcon — APPROVED** [review]
Thanks!

**Review by aescolar — APPROVED** [review]
+1 No complaints for the minimal changes to the posix boards default kconfig (checked too quickly the other kconfig changes to vouch for them, but did not see anything to complain)

**Review by nashif — APPROVED** [review]

**Pull request merged**
