### PR TITLE
boards/arc/qemu_arc: Disable use of branch delay slots

### LINKED ISSUE #60071: arc64 local variable corruption in z_init_static_threads
**Describe the bug**
When running the sample.portability.cmsis_rtos_v2.timer_synchronization test on arc64 under qemu using picolibc, `z_init_static_threads` goes into an infinite loop in the second instance of `_FOREACH_STATIC_THREAD` where it's calling `schedule_new_thread`. 

Debugging this, I discover that the register holding the termination value has been trashed and holds a completely bogus value (0x4275de2 instead of 0x80407594). Perturbing the code above the loop in essentially any way at all (I added `__asm__("")` just after `k_sched_lock()`) makes this issue go away. The difference in the assembly code is trivial -- it moves the load of `__static_thread_data_list_start` after the call to `k_sched_lock`

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? 
    - qemu_arc_hs5x
    - SDK version zephyr-sdk-0.16.2-rc1-5-g8d9b4fe
    - picolibc instead of minimal C library.

 - What have you tried to diagnose or workaround this issue?
 
Modifying the code in even trivial ways appears to work around this issue. I applied this diff:
```
diff --git a/kernel/thread.c b/kernel/thread.c
index fb578eb48d..5721023929 100644
--- a/kernel/thread.c
+++ b/kernel/thread.c
@@ -783,6 +783,7 @@ void z_init_static_threads(void)
         * delay of K_FOREVER.
         */
        k_sched_lock();
+       __asm__("");
        _FOREACH_STATIC_THREAD(thread_data) {
                if (thread_data->init_delay != K_TICKS_FOREVER) {
                        schedule_new_thread(thread_data->init_thread,
```

This generated the following change in the generated code:
```
--- broken.S	2023-07-05 23:27:30.536430480 -0700
+++ working.S	2023-07-05 23:27:18.483894200 -0700
@@ -1073,8 +1073,8 @@
 	add2	r14,r14,11
 .L106:
 	blo_s	.L107
-	mov_s	r14,@__static_thread_data_list_start
 	bl	@k_sched_lock
+	mov_s	r14,@__static_thread_data_list_start
 .L108:
 	mov_s	r0,@__static_thread_data_list_end
 	cmp_s	r14,r0
```

setting a break point on the `cmp_s` instruction here also makes things work. That makes me suspect that qemu might be at fault somehow? 

 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
    - I haven't tried bisecting.

**To Reproduce**
1. ./scripts/twister -O arc64-bug -xCONFIG_PICOLIBC=y -p qemu_arc_hs5x --test samples/subsys/portability/cmsis_rtos_v2/timer_synchronization/sample.portability.cmsis_rtos_v2.timer_synchronization

**Expected behavior**
Test completes successfully

**Impact**
This will delay the switch to using picolibc as the default C library.

**Environment (please complete the following information):**
 - OS: Debian unstable
 - Toolchain: SDK version 0.16.2-rc1-5-g8d9b4fe
 - Commit SHA or Version used: 8560fb319249e3fad3122f8541df4c4beef6e5e2 (main as of this writing)

### PR DESCRIPTION
**Pull request by keith-packard**
I spent several hours debugging a weird stack pointer corruption bug and discovered that QEMU appears to mess up register contents when an interrupt fires during the execution of a branch with a delay slot.

Instead of trying to fix qemu, let's just tell the compiler to not generate code that uses the branch instructions with delay slots.

Closes: #60071

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@ruuddw will you please take a look?

**Comment by ruuddw** [comment]
Sorry for not reacting sooner, vacation period. And, the QEMU delay slot issue meanwhile has been fixed upstream.
I expect we can get it included in the SDK for this release cycle.
Do you still want to have this workaround in? Then let's add some "TODO" remark and/or issue to allow the compiler to benefit from the branch delay slots again.

**Comment by keith-packard** [comment]
> Sorry for not reacting sooner, vacation period. And, the QEMU delay slot issue meanwhile has been fixed upstream. I expect we can get it included in the SDK for this release cycle. Do you still want to have this workaround in? Then let's add some "TODO" remark and/or issue to allow the compiler to benefit from the branch delay slots again.

It's just marked like this for the qemu target where there's no performance benefit for delay slots, so yeah, I think it'd be good to have this work-around present at least until we've got a 'real' SDK release that includes the fix. Otherwise we get random CI failures.

**Comment by evgeniy-paltsev** [comment]
Just for note: the rootcause fix is https://github.com/zephyrproject-rtos/sdk-ng/pull/692

I'd prefer to just have it in SDK asap, though I'm not sure if someone else can pick it while Stephanos is on leave.

**Review by ruuddw — APPROVED** [review]
Any ETA for getting the QEMU fix in the SDK, @evgeniy-paltsev ?
I'm ok with a temporary workaround, I like Keith' simple solution to have the compiler avoid it.
Or, given the root cause is known, do you foresee problems with this workaround?

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
