### PR TITLE
CI: Add building hello world on all platforms as part of sanitycheck

### PR DESCRIPTION
**Pull request by galak**
Do a simple build test on all platforms to make sure they build when we
change things.  This will hopefully catch an errors we run into from
time to time on platforms that don't get typicaly run by sanitycheck.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by nashif** [comment]
This is already covered in #8 btw, and in a more flexible and configurable way. Right now I just need to go and add latest boards and s/TBD/<something useful>/

**Comment by galak** [comment]
Do we want this as a stop gap until we get the YAML stuff merged in? Otherwise I can drop it.

**Comment by nashif** [comment]
> Do we want this as a stop gap until we get the YAML stuff merged in? Otherwise I can drop it.

This is overriding the test reports now, so it is a NO GO in the current form. Need to change sanitycheck to create a new xml output and append. Let me spend some time on the YAML stuff today and also address the test report issue before we go with this as a stop gap.

**Comment by galak** [comment]
Sounds good, wasn't sure about the output and how this impacted things.

**Comment by nashif** [comment]
not needed anymore, we do now have 'build_on_all' keyword which causes a test to be built on ALL available boards.. (as part of #8 )

**Pull request closed without merging**
