### PR TITLE
sensors: Adds drivers for ICM20948 IMU

### PR DESCRIPTION
**Pull request by pollend**
This adds support for TDK ICM20948. this commit only covers the basic implementation of the sensor and doesn't have support for triggers and other secondary configurations found in the datasheet. 

REF: https://github.com/zephyrproject-rtos/zephyr/pull/16668#issuecomment-1001431500

Signed-off-by: Michael Pollind <polli104@mail.chapman.edu>

### CODE REVIEW

**Comment by pollend** [comment]
this just revives the previous work haven't touched zephyr in a really long time might take me a bit to resolve the problems

**Comment by pollend** [comment]
been trying to find some time to clean this up. I think I will try to do this over the coming weekend.

**Comment by MaureenHelm** [comment]
> Any updates? Why was this not merged this time?

It's hard to see after the PR is closed, but it looks like the code wouldn't have passed compliance checks. This fixup commit should have been squashed into the original commit, and the sensor needs to get added to `tests/drivers/build_all/sensor`

**Comment by Bedmonds91** [comment]
My PR for this sensor passed all tests but wasn't accepted anyway since the component is too close to EOL. I've posted the driver on my account if your interested (@bedmonds91)

**Pull request closed without merging**
