### PR TITLE
tests/storage/flash_map: Fix erase and flatten test

### LINKED ISSUE #74066: frdm_k64f: tests/subsys/storage/flash_map/storage.flash_map.mpu fails
Describe the bug
The tests/subsys/storage/flash_map/storage.flash_map.mpu failed.
Assertion failed at ./tests/subsys/storage/flash_map/src/main.c:242: flash_map_test_flash_area_erase_and_flatten: (erased is false)
Erase failed at index 1

```
Tue, 11 Jun 2024 09:52:40 GMT INFO    - frdm_k64f    tests/subsys/storage/flash_map/storage.flash_map.mpu  FAILED Failed (device: xxx, 10.815s)
```

To Reproduce
```
scripts/twister -W -p frdm_k64f --device-testing -T tests/subsys/storage/flash_map -v
```
```
The following issues were found (showing the top 10 items):
Tue, 11 Jun 2024 09:53:10 GMT INFO    - 1) tests/subsys/storage/flash_map/storage.flash_map.mpu on frdm_k64f failed (Failed)
Tue, 11 Jun 2024 09:53:10 GMT INFO    - 
Tue, 11 Jun 2024 09:53:10 GMT INFO    - To rerun the tests, call twister using the following commandline:
Tue, 11 Jun 2024 09:53:10 GMT INFO    - west twister -p <PLATFORM> -s <TEST ID>, for example:
Tue, 11 Jun 2024 09:53:10 GMT INFO    - 
Tue, 11 Jun 2024 09:53:10 GMT INFO    - west twister -p frdm_k64f -s tests/subsys/storage/flash_map/storage.flash_map.mpu
Tue, 11 Jun 2024 09:53:10 GMT INFO    - or with west:
Tue, 11 Jun 2024 09:53:10 GMT INFO    - west build -p -b frdm_k64f tests/subsys/storage/flash_map -T storage.flash_map.mpu
```

Logs and console output
```
INFO    - frdm_k64f    tests/subsys/storage/flash_map/storage.flash_map.mpu  FAILED Failed (device: xxx, 10.815s)
INFO    - ./twister-out/frdm_k64f/tests/subsys/storage/flash_map/storage.flash_map.mpu/handler.log
ERROR   - ***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build v3.6.0-5742-g2efc447c1b41 (delayed boot 500ms) ***
Running TESTSUITE flash_map
===================================================================
START - test_fixed_partition_node_macros
PASS - test_fixed_partition_node_macros in 0.001 seconds
===================================================================
START - test_flash_area_check_int_sha256
PASS - test_flash_area_check_int_sha256 in 0.159 seconds
===================================================================
START - test_flash_area_disabled_device
PASS - test_flash_area_disabled_device in 0.001 seconds
===================================================================
START - test_flash_area_erase_and_flatten
Assertion failed at ./tests/subsys/storage/flash_map/src/main.c:242: flash_map_test_flash_area_erase_and_flatten: (erased is false)
Erase failed at index 1
FAIL - test_flash_area_erase_and_flatten in 4.744 seconds
===================================================================
START - test_flash_area_erased_val
PASS - test_flash_area_erased_val in 0.001 seconds
===================================================================
START - test_flash_area_get_sectors
PASS - test_flash_area_get_sectors in 0.904 seconds
===================================================================
TESTSUITE flash_map failed.
------ TESTSUITE SUMMARY START ------
SUITE FAIL -  83.33% [flash_map]: pass = 5, fail = 1, skip = 0, total = 6 duration = 5.810 seconds
- PASS - [flash_map.test_fixed_partition_node_macros] duration = 0.001 seconds
- PASS - [flash_map.test_flash_area_check_int_sha256] duration = 0.159 seconds
- PASS - [flash_map.test_flash_area_disabled_device] duration = 0.001 seconds
- FAIL - [flash_map.test_flash_area_erase_and_flatten] duration = 4.744 seconds
- PASS - [flash_map.test_flash_area_erased_val] duration = 0.001 seconds
- PASS - [flash_map.test_flash_area_get_sectors] duration = 0.904 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: bf5ab1639defa729ed7ac2c5f1bffb02
PROJECT EXECUTION FAILED
```

Environment:
OS: Linux
Zephyr version: v3.6.0-5742-g2efc447c1b41
Zephyr SDK version: 0.16.5-1

### PR DESCRIPTION
**Pull request by de-nordic**
Fix offset read for verification and comparison of read to erased value, where type mismatch has been causing fails in comparisons.

Fixes #74066

### CODE REVIEW

**Comment by arikgreen** [comment]
@de-nordic yesterday I tried your fix on our frdm but the fail still exists.
```
Tue, 11 Jun 2024 19:43:34 GMT    ===================================================================
Tue, 11 Jun 2024 19:43:34 GMT    START - test_flash_area_erase_and_flatten
Tue, 11 Jun 2024 19:43:34 GMT    Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/subsys/storage/flash_map/src/main.c:242: flash_map_test_flash_area_erase_and_flatten: (erased is false)
Tue, 11 Jun 2024 19:43:34 GMT    Erase failed at index 1
Tue, 11 Jun 2024 19:43:34 GMT    FAIL - test_flash_area_erase_and_flatten in 4.746 seconds
Tue, 11 Jun 2024 19:43:34 GMT    ===================================================================
```

**Comment by de-nordic** [comment]
> @de-nordic yesterday I tried your fix on our frdm but the fail still exists.
> 
> ```
> Tue, 11 Jun 2024 19:43:34 GMT    ===================================================================
> Tue, 11 Jun 2024 19:43:34 GMT    START - test_flash_area_erase_and_flatten
> Tue, 11 Jun 2024 19:43:34 GMT    Assertion failed at WEST_TOPDIR/os.rtos.zephyr.zephyr/tests/subsys/storage/flash_map/src/main.c:242: flash_map_test_flash_area_erase_and_flatten: (erased is false)
> Tue, 11 Jun 2024 19:43:34 GMT    Erase failed at index 1
> Tue, 11 Jun 2024 19:43:34 GMT    FAIL - test_flash_area_erase_and_flatten in 4.746 seconds
> Tue, 11 Jun 2024 19:43:34 GMT    ===================================================================
> ```

I may need some help here from you @arikgreen on diagnosing the problem. as it will take me a moment to get the board and the PR fixes the same issue on nrf52840 already.

**Comment by arikgreen** [comment]
> 
> I may need some help here from you @arikgreen on diagnosing the problem. as it will take me a moment to get the board and the PR fixes the same issue on nrf52840 already.
ok, no problem. How can I help you?

**Comment by de-nordic** [comment]
> > I may need some help here from you @arikgreen on diagnosing the problem. as it will take me a moment to get the board and the PR fixes the same issue on nrf52840 already.
> > ok, no problem. How can I help you?

Can you run the sample and provide me with a log from the run?  I have added a few TC_PRINT lines that specify the parameters of the Flash Area used.

**Comment by de-nordic** [comment]
> 
> Your fix works. Sorry, it was my fault. The gh workflow had checkouted to the wrong sha, and not implemented your changes. You can back to previous version.
> 

No problem. Thanks for checking this for me. I am living the TC_PRINTS as they are useful anyway, so this is ready as is. Thanks again.

**Review by arikgreen — APPROVED** [review]

**Comment by de-nordic** [comment]
@dleach02 @katgiadla Would you find some time to review?

**Comment by katgiadla** [comment]
> @dleach02 @katgiadla Would you find some time to review?

unfortunatelly, it does not work on-target

**Comment by dleach02** [comment]
@butok @hakehuang could one of  you look at this?

**Comment by butok** [comment]
BTW: 
The test does not have a readme file.
In fact, many tests and samples do not have any description. Does Zephyr have any rules?
Every time people have to guess what they are doing.

**Comment by butok** [comment]
> @butok @hakehuang could one of you look at this?

I do not have the frdm-k64f, 
but for frdm-mcxn947 the test is failed before this PR and also failed after this PR.
The test log:
```
*** Booting Zephyr OS build v3.6.0-5869-g2a348e5bf97b ***
Running TESTSUITE flash_map
===================================================================
START - test_fixed_partition_node_macros
 PASS - test_fixed_partition_node_macros in 0.001 seconds
===================================================================
START - test_flash_area_check_int_sha256
 PASS - test_flash_area_check_int_sha256 in 0.123 seconds
===================================================================
START - test_flash_area_disabled_device
 PASS - test_flash_area_disabled_device in 0.001 seconds
===================================================================
START - test_flash_area_erase_and_flatten
E: Size of CONFIG_FLASH_FILL_BUFFER_SIZE

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/storage/flash_map/src/main.c:223: flash_map_test_flash_area_erase_and_flatten: (rc == 0 is false)
flash device fill fail
 FAIL - test_flash_area_erase_and_flatten in 0.142 seconds
===================================================================
START - test_flash_area_erased_val
 PASS - test_flash_area_erased_val in 0.001 seconds
===================================================================
START - test_flash_area_get_sectors
 PASS - test_flash_area_get_sectors in 0.665 seconds
===================================================================
TESTSUITE flash_map failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  83.33% [flash_map]: pass = 5, fail = 1, skip = 0, total = 6 duration = 0.933 seconds
 - PASS - [flash_map.test_fixed_partition_node_macros] duration = 0.001 seconds
 - PASS - [flash_map.test_flash_area_check_int_sha256] duration = 0.123 seconds
 - PASS - [flash_map.test_flash_area_disabled_device] duration = 0.001 seconds
 - FAIL - [flash_map.test_flash_area_erase_and_flatten] duration = 0.142 seconds
 - PASS - [flash_map.test_flash_area_erased_val] duration = 0.001 seconds
 - PASS - [flash_map.test_flash_area_get_sectors] duration = 0.665 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED
```

**Comment by arikgreen** [comment]
this is the handler.log from run on frdm_k64f
```
***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build v3.6.0-5703-g7345e0ee707b (delayed boot 500ms) ***
Running TESTSUITE flash_map
===================================================================
START - test_fixed_partition_node_macros
PASS - test_fixed_partition_node_macros in 0.001 seconds
===================================================================
START - test_flash_area_check_int_sha256
PASS - test_flash_area_check_int_sha256 in 0.156 seconds
===================================================================
START - test_flash_area_disabled_device
PASS - test_flash_area_disabled_device in 0.001 seconds
===================================================================
START - test_flash_area_erase_and_flatten
Flash area info:
pointer:	 0x2000117c
offset:	 495616
size:	 425984
PASS - test_flash_area_erase_and_flatten in 9.825 seconds
===================================================================
START - test_flash_area_erased_val
PASS - test_flash_area_erased_val in 0.001 seconds
===================================================================
START - test_flash_area_get_sectors
PASS - test_flash_area_get_sectors in 0.908 seconds
===================================================================
TESTSUITE flash_map succeeded
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [flash_map]: pass = 6, fail = 0, skip = 0, total = 6 duration = 10.892 seconds
- PASS - [flash_map.test_fixed_partition_node_macros] duration = 0.001 seconds
- PASS - [flash_map.test_flash_area_check_int_sha256] duration = 0.156 seconds
- PASS - [flash_map.test_flash_area_disabled_device] duration = 0.001 seconds
- PASS - [flash_map.test_flash_area_erase_and_flatten] duration = 9.825 seconds
- PASS - [flash_map.test_flash_area_erased_val] duration = 0.001 seconds
- PASS - [flash_map.test_flash_area_get_sectors] duration = 0.908 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 66def2e841e7e9bec3c57c96e87f6896
PROJECT EXECUTION SUCCESSFUL
```

**Comment by butok** [comment]
> this is the handler.log from run on frdm_k64f
> 
> ```
> ***** delaying boot 500ms (per build configuration) *****
> *** Booting Zephyr OS build v3.6.0-5703-g7345e0ee707b (delayed boot 500ms) ***
> Running TESTSUITE flash_map
> ===================================================================
> START - test_fixed_partition_node_macros
> PASS - test_fixed_partition_node_macros in 0.001 seconds
> ===================================================================
> START - test_flash_area_check_int_sha256
> PASS - test_flash_area_check_int_sha256 in 0.156 seconds
> ===================================================================
> START - test_flash_area_disabled_device
> PASS - test_flash_area_disabled_device in 0.001 seconds
> ===================================================================
> START - test_flash_area_erase_and_flatten
> Flash area info:
> pointer:	 0x2000117c
> offset:	 495616
> size:	 425984
> PASS - test_flash_area_erase_and_flatten in 9.825 seconds
> ===================================================================
> START - test_flash_area_erased_val
> PASS - test_flash_area_erased_val in 0.001 seconds
> ===================================================================
> START - test_flash_area_get_sectors
> PASS - test_flash_area_get_sectors in 0.908 seconds
> ===================================================================
> TESTSUITE flash_map succeeded
> ------ TESTSUITE SUMMARY START ------
> SUITE PASS - 100.00% [flash_map]: pass = 6, fail = 0, skip = 0, total = 6 duration = 10.892 seconds
> - PASS - [flash_map.test_fixed_partition_node_macros] duration = 0.001 seconds
> - PASS - [flash_map.test_flash_area_check_int_sha256] duration = 0.156 seconds
> - PASS - [flash_map.test_flash_area_disabled_device] duration = 0.001 seconds
> - PASS - [flash_map.test_flash_area_erase_and_flatten] duration = 9.825 seconds
> - PASS - [flash_map.test_flash_area_erased_val] duration = 0.001 seconds
> - PASS - [flash_map.test_flash_area_get_sectors] duration = 0.908 seconds
> ------ TESTSUITE SUMMARY END ------
> ===================================================================
> RunID: 66def2e841e7e9bec3c57c96e87f6896
> PROJECT EXECUTION SUCCESSFUL
> ```

Fine. So we can approve it.
The frdm-mcxn947 error is not related to this PR, and I am going to fix it soon.

**Review by butok — APPROVED** [review]

**Pull request merged**
