### PR TITLE
driver/sensor: add LIS2DS12 sensor support

### PR DESCRIPTION
**Pull request by avisconti**
Add support to STM LIS2DS12 3-axis accelerometer driver.
The driver support I2C and SPI bus communication and both
polling and drdy trigger mode.
Currently it uses high resolution only as power mode.

It has been tested on Nucleo F401RE + IKS01A2 shield using the available DIL24

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Driver looks great. Please add the sensor to `tests/drivers/build_all/sensors_i_z.conf` to ensure that it gets built in CI.

Do you plan to add it to `boards/shields/x_nucleo_iks01a1/x_nucleo_iks01a1.overlay`?

**Comment by avisconti** [comment]
> Do you plan to add it to `boards/shields/x_nucleo_iks01a1/x_nucleo_iks01a1.overlay`?

Well, actually no. I mean, both x_nucleo_iks01a1 and x_nucleo_iks01a2 shields does not include
this sensor. Nevertheless it can be added to DIL24. This is what I did on x_nucleo_iks01a2 in order
to test it. So, if you and @erwango think it is a good idea, I could add in the overlay of the
x_nucleo_iks01a2 shield the support of this sensor as 'example' of DIL24 extension.

**Comment by avisconti** [comment]
> Driver looks great. Please add the sensor to `tests/drivers/build_all/sensors_i_z.conf` to ensure that it gets built in CI.

Sure, I forgot it.

**Review by MaureenHelm — APPROVED** [review]
> Well, actually no. I mean, both x_nucleo_iks01a1 and x_nucleo_iks01a2 shields does not include
> this sensor. Nevertheless it can be added to DIL24. This is what I did on x_nucleo_iks01a2 in order
> to test it. So, if you and @erwango think it is a good idea, I could add in the overlay of the
> x_nucleo_iks01a2 shield the support of this sensor as 'example' of DIL24 extension.

Is DIL24 an expansion header? Will defer to @erwango to decide if this makes sense.

**Comment by avisconti** [comment]
> Is DIL24 an expansion header? Will defer to @erwango to decide if this makes sense.

Yes, it is a standard socket where you can put an additional sensor for testing purpose.
We may want to change the overlay file in order to present an example for the DIL24.
Not sure is worth doing it. @erwango any opinion?

**Pull request merged**
