### PR TITLE
kernel: Provide only one _SYSCALL_HANDLER() macro

### PR DESCRIPTION
**Pull request by lpereira**
Use some preprocessor trickery to automatically deduce the amount of
arguments for the various _SYSCALL_HANDLERn() macros.  Makes the grunt work
of converting a bunch of kernel APIs to system calls slightly easier.

The same trick might be used for the _SIMPLE_ handler variants, although
this patch does not contemplate this.

Signed-off-by: Leandro Pereira <leandro.pereira@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
CI is barfing due to commit message line length:
4: UC4 Line exceeds max length (75>72): "arguments for the various _SYSCALL_HANDLERn() macros.  Makes the grunt work"

As well as some checkpatch.pl false-positives that we will need @nashif  to override

**Comment by lpereira** [comment]
Repushed with a fixed commit message

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
I used github's fancy editor to resolve a merge conflict

**Comment by andrewboie** [comment]
Somehow, the edit I made does not propagate properly to the CI job, as the code it builds has "_SYSCALL_HANDLER2" for the new thread revoke API.
While we ponder these mysteries, might need @lpereira to rebase :)

**Comment by andrewboie** [comment]
recheck

**Comment by andrewboie** [comment]
rebased at #4360

**Comment by lpereira** [comment]
Closing in favor of #4360

**Pull request closed without merging**
