### PR TITLE
soc: nrf: Cleanup dts_fixup.h

### PR DESCRIPTION
**Pull request by galak**
Remove dts_fixup.h files that are needed anymore, remove defines that
are used, and replace defines with new DT macros.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
If / when we get https://github.com/zephyrproject-rtos/zephyr/pull/24890 merged will update this to remove DT_UART_x_NAME.

**Review by carlescufi — COMMENTED** [review]
Are we not missing the fixups for SPI @galak?

**Comment by galak** [comment]
> Are we not missing the fixups for SPI @galak?

What do you mean, the SPI are removed.  There isn't anything in tree that uses DT_SPI_._NAME

**Comment by carlescufi** [comment]
> What do you mean, the SPI are removed. There isn't anything in tree that uses DT_SPI_._NAME

Right, but shouldn’t we cover all peripherals in the fixup file regardless of whether they are actually used or not @galak?

**Comment by galak** [comment]
> Right, but shouldn’t we cover all peripherals in the fixup file regardless of whether they are actually used or not @galak?

What do you mean?  We're trying to phase out the usage of the file.

**Comment by carlescufi** [comment]
> > Right, but shouldn’t we cover all peripherals in the fixup file regardless of whether they are actually used or not @galak?
> 
> What do you mean? We're trying to phase out the usage of the file.

Right but this might be in use out of tree. It’s a macro we were providing to users that is now removed?

**Comment by carlescufi** [comment]
Anyway I will approve to unblock this. It would be good if we could add a note in the release notes about the macros that have gone away and what to replace them with.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
