### PR TITLE
net: buf: Take advantage of __must_check annotation

### PR DESCRIPTION
**Pull request by jhedberg**
Update appropriate `net_buf` APIs with `__must_check` and update any misuse that was found in the tree.

### CODE REVIEW

**Comment by jhedberg** [comment]
There is still one place of "misuse" of `net_buf_ref()` in `subsys/canbus/isotp/isotp.c` which I hope @alexanderwachter  could help out with (since I can't completely understand this code): https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/canbus/isotp/isotp.c#L695-L715

**Review by jukkar — APPROVED** [review]
Nice improvement :+1:

**Review by rlubos — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Comment by jhedberg** [comment]
Hmm, seems like doxygen doesn't like using this for function pointers:
```
29 Warning, treated as error:
30 /home/runner/work/zephyr/zephyr/doc/_build/src/reference/networking/net_buf.rst:139:Type must be either just a name or a typedef-like declaration.
31 If just a name:
32  Error in declarator or parameters
33  Invalid C declaration: Expected identifier in nested name, got keyword: struct [error at 6]
34    struct net_buf *__must_check(* net_buf_allocator_cb )(k_timeout_t timeout, void *user_data)
35    ------^
36 If typedef-like declaration:
37  Error in declarator or parameters
38  Invalid C declaration: Expected identifier in nested name. [error at 29]
39    struct net_buf *__must_check(* net_buf_allocator_cb )(k_timeout_t timeout, void *user_data)
40    -----------------------------^
```

Anyone have an idea if something can be done about that, or I should just forget about trying to use __must_check on function pointers?

**Comment by gmarull** [comment]
@jhedberg You can add `__must_check` here https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/zephyr.doxyfile.in#L2012

**Comment by jhedberg** [comment]
> @jhedberg You can add __must_check here https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/zephyr.doxyfile.in#L2012

@gmarull thanks a lot! I've added a corresponding patch to the PR now.

**Comment by joerchan** [comment]
@jhedberg Looks like unrelated build failures? Maybe just rebase it?

**Comment by jhedberg** [comment]
> @jhedberg Looks like unrelated build failures? Maybe just rebase it?

@joerchan no, that's exactly the remaining issue I mentioned in my comment https://github.com/zephyrproject-rtos/zephyr/pull/36370#issuecomment-863239058

@alexanderwachter had some proposal on Slack for how to fix this, which I didn't yet have a chance to look at.

**Review by pfalcon — APPROVED** [review]

**Comment by pfalcon** [comment]
> @alexanderwachter had some proposal on Slack for how to fix this, which I didn't yet have a chance to look at.

Any updates on this?

**Comment by alexanderwachter** [comment]
No, sorry. Is someone else able to do a quick fix?

**Comment by carlescufi** [comment]
> No, sorry. Is someone else able to do a quick fix?

Not sure, maybe @henrikbrixandersen ?

**Review by mniestroj — APPROVED** [review]

**Comment by martinjaeger** [comment]
Please don't remove ISO-TP! We are using it and I have contributed to it in the past, but I was not aware of this issue.

@alexanderwachter do you remember the Slack discussions and can you post the details here?

**Comment by jhedberg** [comment]
> Please don't remove ISO-TP! We are using it and I have contributed to it in the past, but I was not aware of this issue.

I doubt removing it would have happened - my primary intention was to get the attention of people interested in it (like yourself), which seems to have been successful 😉 

> @alexanderwachter do you remember the Slack discussions and can you post the details here?

I'll open an issue for this, describing my findings

**Comment by jhedberg** [comment]
> I'll open an issue for this, describing my findings

Issue opened: #40070

**Comment by martinjaeger** [comment]
Fix for `isotp.c` provided in #40162. This PR should be rebased as soon as the fix is merged.

**Pull request merged**
