### PR TITLE
dts: arm64: agilex: add additional cpu nodes

### PR DESCRIPTION
**Pull request by dinguyen702**
Add CPU1 - CPU3 nodes and add the cpu0 label.

Signed-off-by: Dinh Nguyen <dinguyen@kernel.org>
---
v2: add cpu0 label

### CODE REVIEW

**Review by carlocaione — DISMISSED** [review]
LGTM. For the next time there is no need to close a PR and open a new one. You can simply force push your changes.

**Review by povergoing — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Hi @dinguyen702, I saw you added a version comment in the patch commit it itself with a "---", do you want to remove it before we merge? I understand on kernel patches it would get stripped by "git am", but that does not work on GitHub since the patch gets merged directly server side. Normally PR version comments are added to the PR thread itself.

**Comment by dinguyen702** [comment]
> Hi @dinguyen702, I saw you added a version comment in the patch commit it itself with a "---", do you want to remove it before we merge? I understand on kernel patches it would get stripped by "git am", but that does not work on GitHub since the patch gets merged directly server side. Normally PR version comments are added to the PR thread itself.

I've forced update the branch with the "---" removed. Please let me know if that's the correct procedure? Apologies if it wasn't, I'm stumbling through this process.

**Comment by fabiobaltieri** [comment]
> > Hi @dinguyen702, I saw you added a version comment in the patch commit it itself with a "---", do you want to remove it before we merge? I understand on kernel patches it would get stripped by "git am", but that does not work on GitHub since the patch gets merged directly server side. Normally PR version comments are added to the PR thread itself.
> 
> I've forced update the branch with the "---" removed. Please let me know if that's the correct procedure? Apologies if it wasn't, I'm stumbling through this process.

Yeah but there's now an extra merge commit, just rebase the original commit and force push it (drop the merge). No worries, it's a significantly different workflow than on kernel.org (which arguably is what git was designed for).

**Comment by dinguyen702** [comment]
> > > Hi @dinguyen702, I saw you added a version comment in the patch commit it itself with a "---", do you want to remove it before we merge? I understand on kernel patches it would get stripped by "git am", but that does not work on GitHub since the patch gets merged directly server side. Normally PR version comments are added to the PR thread itself.
> > 
> > 
> > I've forced update the branch with the "---" removed. Please let me know if that's the correct procedure? Apologies if it wasn't, I'm stumbling through this process.
> 
> Yeah but there's now an extra merge commit, just rebase the original commit and force push it (drop the merge). No worries, it's a significantly different workflow than on kernel.org (which arguably is what git was designed for).

got it! thanks!

**Review by fabiobaltieri — APPROVED** [review]

**Review by povergoing — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by SgrrZhf — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]

**Comment by ngboonkhai** [comment]
This PR is approved so fast, I don't even have chance to review it yet, btw @dinguyen702 have you verify this on a real board?

**Pull request merged**
