### PR TITLE
socketpair improvements

### LINKED ISSUE #52360: samples/net/sockets/socketpair does not run as expected
**Describe the bug**
I tried to run samples/net/socket/socketpair, and got the folllowing issue first, 

```
*** Booting Zephyr OS build zephyr-v3.2.0-585-ge80a0c35e666  ***
Alpha: socketpair: 1 <=> 0
Bravo: socketpair: 3 <=> 2
socketpair failed: 23
Alpha closed fd 0
Bravo closed fd 2

```
Then I figure out I need to increase the default CONFIG_POSIX_MAX_FDS from 4 to 8 for 3 socket pairs (should this change be  covered in socketpair/prj.conf ?)

Even I add this setting, I saw this issue, seems the poll mechanism was broken?

```
*** Booting Zephyr OS build zephyr-v3.2.0-585-ge80a0c35e666  ***
Alpha: socketpair: 1 <=> 0
Bravo: socketpair: 3 <=> 2
Charlie: socketpair: 5 <=> 4
fd: 1: read 5 bytes
fd: 1: read 5 bytes
fd: 1: read 5 bytes
fd: 1: read 0 bytes
fd: 1: read 0 bytes
fd: 1: read 0 bytes
<keep looping>
fd: 1: read 0 bytes
fd: 1: read 0 bytes
fd: 1: read 0 bytes
fd: 1: read 0 bytes

```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?   
 - What have you tried to diagnose or workaround this issue?
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - ...

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

### LINKED ISSUE #54347: zephyr/posix/fcntl.h header works differently on native_posix platform
**Describe the bug**
When using `fcntl.h` header from Zephyr, one has to pay attention of the one corner case, which is native_posix platform, perhaps others.

As discovered in https://github.com/zephyrproject-rtos/zephyr/issues/54332 this causes side effects on native_posix that are not visible on other platform. Workaround is to use different header on `ARCH_POSIX` like this:
```
#ifdef CONFIG_ARCH_POSIX
#include <fcntl.h>
#else
#include <zephyr/posix/fcntl.h>
#endif
```

This workaround is already used in `zephyr/subsys/net/lib/sockets/sockets.c` which forces anyone using `fcntl()` on sockets to use the same workaround. Without including the same header flags like `O_NONBLOCK` might end up using different value, and therefore calls like `fcntl(sock, F_SETFD, O_NONBLOCK)` do not cause the wanted effect, but neither they produce any error.

**To Reproduce**
1. Include only `<zephyr/posix/fcntl.h>`
2. try to make a socket non-blocking
3. build with `native_posix`
4. Observe that the socket is blocking

**Expected behavior**
I would expect this workaround to be inside `include/zephyr/posix/fcntl.h` so the code inside Zephyr does not need to implement various workaround for various platforms.

**Impact**
Annoying, and might slow the development.

This issue is related to https://github.com/zephyrproject-rtos/zephyr/issues/54332

### PR DESCRIPTION
**Pull request by cfriedt**
4 commits:
* improvements for socketpair sample app (it was broken for a while)
* rename `socketpair_example.c` to `main.c`
* minor improvements for `socketpair.c`
* additional `<fcntl.h>` corrections in the networking subsystem

Fixes #54347
Fixes #52360

### CODE REVIEW

**Comment by cfriedt** [comment]
I would really prefer to get this sample running in `harness: console` rather than `harness: net` so that we can run it on any host and have twister automatically check the output for `SUCCESS` using the `regex` property in `sample.yaml`. It's completely unnecessary for socketpair to depend on networking other than relying on some of the existing socket code.

**Comment by rlubos** [comment]
@cfriedt `net/lib/sockets/sockets_tls.c` also needs an update.

**Comment by SeppoTakalo** [comment]
Is there a reason why we apply this workaround:
```c
#ifdef CONFIG_ARCH_POSIX
#include <fcntl.h>
#else
#include <zephyr/posix/fcntl.h>
#endif
```
to all files, but not in the `<zephyr/posix/fcntl.h>` header itself?

**Comment by cfriedt** [comment]
> Is there a reason why we apply this workaround:
> 
> ```c
> #ifdef CONFIG_ARCH_POSIX
> #include <fcntl.h>
> #else
> #include <zephyr/posix/fcntl.h>
> #endif
> ```
> 
> to all files, but not in the `<zephyr/posix/fcntl.h>` header itself?

Yes - because `CONFIG_ARCH_POSIX` and `CONFIG_POSIX_API` have been mutually exclusive for years. Hopefully that can be fixed soon.  It's precipitated quite a bit of spaghetti between `lib/os/`, `subsys/net`, and `lib/posix`. I would not recommend mixing them up again. It's actually somewhat helpful to identify where we conditionally include `<fcntl.h>` for `native_posix` as well. 

Specifically w.r.t. the network subsystem though, there is a cyclic dependency between the networking subsystem and posix needs to be broken by a mutual dependency. Currently, we have:

```
┌───────────┐       ┌───────────┐
│           ├──────►│           │
│   POSIX   │       │   NET     │
│           │◄──────┤           │
└───────────┘       └───────────┘
```

But we need
```
          ┌───────────┐
          │           │
          │    ??     │
          │           │
          └▲────────▲─┘
           │        │
           │        │
┌──────────┴┐       ├───────────┐
│           │       │           │
│   POSIX   ├───────►   NET     │
│           │       │           │
└───────────┘       └───────────┘
```

I'm thinking the correct name for `??` would be something like `zfdio`

**Comment by cfriedt** [comment]
> @cfriedt `net/lib/sockets/sockets_tls.c` also needs an update.

@rlubos - fixed!

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
LGTM

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
