### PR TITLE
drivers: ethernet: add dependency to CONFIG_ETH_INIT_PRIORITY

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add a dependency on CONFIG_NET_L2_ETHERNET for CONFIG_ETH_INIT_PRIORITY. This hides the Ethernet driver initialization priority option in menuconfig unless CONFIG_NET_L2_ETHERNET is selected.

CONFIG_ETH_INIT_PRIORITY cannot currently be moved inside the CONFIG_ETH_DRIVER if-statement in Kconfig as it is used outside the Ethernet driver source files.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
Okay. This is a bit messy. We have a lot of code outside `drivers/ethernet` that depends on `CONFIG_ETH_INIT_PRIORITY` (WiFi, USB, tests/, ...). This is why CI fails.

**Comment by henrikbrixandersen** [comment]
CC: @galak since he introduced 6124ccfccf3ac53b63fe97c772f51363c7915686 ;-)

**Comment by jukkar** [comment]
Duplicate of #51929

**Review by nashif — DISMISSED** [review]

**Comment by jukkar** [comment]
I proposed a change in https://github.com/zephyrproject-rtos/zephyr/pull/51929#issuecomment-1310852209
I did not test that so caveat emptor.

**Comment by henrikbrixandersen** [comment]
> I proposed a change in [#51929 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/51929#issuecomment-1310852209)
> I did not test that so caveat emptor.

Thanks. I will look into providing a non-breaking solution to this.

**Comment by henrikbrixandersen** [comment]
Rebased on main.

**Comment by henrikbrixandersen** [comment]
> I proposed a change in [#51929 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/51929#issuecomment-1310852209) I did not test that so caveat emptor.

@jukkar I have update the commit to use the proposed dependency. It's better than the current situation, but not perfect.

**Review by jukkar — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
