### PR TITLE
drivers: pwm: fix the bug of frequency in pwm_nrf5_sw

### PR DESCRIPTION
**Pull request by findlayfeng**
- 正确的分频值
- 函数 pwm_nrf5_sw_get_cycles_per_sec 获取正确的周期数
The following is a machine translation
- The correct prescaler value
- The function pwm_nrf5_sw_get_cycles_per_sec gets the correct number of cycles

### CODE REVIEW

**Comment by cvinayak** [comment]
Please elaborate on the bug, and how to reproduce the bug.

**Comment by findlayfeng** [comment]
只是计算上的问题
首先软件pwm依赖timer
配置pwm都是在配置timer
nrf的timer时钟固定为MHZ(16)(16 * 1000 * 1000)而不是 16 * 1024 * 1024
这里使用了一个nrf16位的timer,支持 0-9 次二分频,所以这是一个最大定是周期是 25位分辨率为16位的timer
原来的函数将32位的周期值调整成16位进行配置
但进行了很奇怪的计算
将周期数右移了周期数高16位的值，注意这里使用了值而不是位数
而且没有配置二分频次数
我的改动就是，将16位以下的值直接进行配置(这里和原来函数的表现相似)
16位到25位之间，计算出应该使用正确的二分频次数值，和二分频后对应的周期数
超过25位返回错误

使用 pwm_nrf5_sw 驱动时，设置cycles值超过 0xffff 就会出现错误

From Google Translate
It's just a computational problem
First software pwm depends on timer
Configure pwm are in the configuration timer
Nrf's timer clock is fixed at MHZ(16)(16 * 1000 * 1000) instead of 16 * 1024 * 1024
An nrf 16-bit timer is used here, which supports 0-9 times divide-by-two, so this is a timer with a maximum resolution of 25 bits and a resolution of 16 bits.
The original function adjusts the 32-bit period value to 16 bits for configuration
It turned out that there was a very strange calculation here
The number of cycles is shifted right by the number of cycles higher by 16 bits. Note that values are used instead of the number of bits
And there is no configuration for the number of divide-by-2
My change is to configure the following 16-bit value directly (here and the original function is similar to the performance)
Between 16 and 25 bits, calculate that the correct value of divide-by-2 should be used, and the number of cycles after the divide-by-two
More than 25 bits return error

When using the pwm_nrf5_sw driver, setting the cycles value to exceed 0xffff results in an error

**Comment by findlayfeng** [comment]
http://infocenter.nordicsemi.com/pdf/nRF51_RM_v3.0.1.pdf
page 99
18.1

**Comment by findlayfeng** [comment]
@cvinayak

**Comment by cvinayak** [comment]
@findlayfeng could you please review https://github.com/zephyrproject-rtos/zephyr/pull/8068 to check if it meets your concerns.

**Comment by cvinayak** [comment]
@findlayfeng I have seen you comments in #8068. You can fix the frequency bug (for over 16-bit period values), rebased over #8068. I assume would be based on updating the Kconfig supplied prescaler value when the period cycles value is over the 16-bit max.

**Comment by nashif** [comment]
stale PR, reopen if becomes relevant again.

**Pull request closed without merging**
