### PR TITLE
Add LinkServer support for RT1170 DEV KIT 

### PR DESCRIPTION
**Pull request by zanderzhng**
Add LinkServer support for RT1170 DEV KIT

### CODE REVIEW

**Comment by DerekSnell** [comment]
Hi @zanderzhng ,
Thank you for contributing this.  Can you resolve the compliance issue?  The Zephyr Project does not allow Merge Commits in a PR.  Thank you

**Comment by kartben** [comment]
> Hi @zanderzhng ,
> Thank you for contributing this.  Can you resolve the compliance issue?  The Zephyr Project does not allow Merge Commits in a PR.  Thank you

Furthermore you will need to sign off your commit and have a commit message and description that follows the contributing guidelines. https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines
Thanks!

**Comment by kartben** [comment]
@zanderzhng ping?

**Review by DerekSnell — CHANGES_REQUESTED** [review]
Hi @zanderzhng ,
Thank you for contributing this.  NXP has also been working in parallel to enable our LinkServer debug support on more NXP boards, including this one.  We just submitted our PR [Enable LinkServer support on NXP RT1170](https://github.com/zephyrproject-rtos/zephyr/pull/62229).  I believe our PR includes your changes, but also covers the other board revision, and updates the board doc page.  I suggest we close this PR, and if you have any feedback or further contributions, you can add to our PR.
Thank you

**Pull request closed without merging**
