### PR TITLE
mainfest: west.yml: Update version of SEGGER RTT library

### PR DESCRIPTION
**Pull request by sigvartmh**
Bumped segger libary version up to version 3.40

### CODE REVIEW

**Comment by carlescufi** [comment]
@sigvartmh please rebase and use a new SHA

**Comment by sigvartmh** [comment]
@carlescufi Done, sorry for the late reply I've been out on vacation.

**Comment by carlescufi** [comment]
@sigvartmh can you fix the dup line?

**Comment by sigvartmh** [comment]
@carlescufi done

**Review by carlescufi — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
