### PR TITLE
Fix leaks with cloned packets

### PR DESCRIPTION
**Pull request by talih0**
To reproduce issue for commit  "net: buf: Drop the reference count on all fragments"
The net_bufs will leak and the allocation will eventually fail.
```
for (int i = 0; i < 100; i++) {
                pkt = net_pkt_alloc_with_buffer(eth_if, 512, AF_UNSPEC, 0, K_NO_WAIT);
		if (!pkt) {
			printk("Failed allocation\n");
		}
		pkt_shallow_copy = net_pkt_shallow_clone(pkt, K_NO_WAIT);
		net_pkt_unref(pkt);
		net_pkt_unref(pkt_shallow_copy);
}
```
To reproduce issue for commit  "pkt: Don't trim packet with more than one ref count"
The same code as above, but trim the packet.
```
for (int i = 0; i < 100; i++) {
                pkt = net_pkt_alloc_with_buffer(eth_if, 512, AF_UNSPEC, 0, K_NO_WAIT);
		if (!pkt) {
			printk("Failed allocation\n");
		}
		pkt_shallow_copy = net_pkt_shallow_clone(pkt, K_NO_WAIT);
		net_pkt_trim_buffer(pkt);
		net_pkt_unref(pkt);
		net_pkt_unref(pkt_shallow_copy);
}
```

### CODE REVIEW

**Comment by talih0** [comment]
The other option is to explicitly say that net_buf_unref() will only drop the reference count on the current buffer and free *only* the current buffer (at the moment it will free all the fragments).
The caller to net_buf_unfref() would be responsible for dropping the refcount on all the remaining fragments. 

I think this would be more consistent with net_buf_ref() which only increments the count for the current buffer.

**Comment by jhedberg** [comment]
> The other option is to explicitly say that net_buf_unref() will only drop the reference count on the current buffer and free **only** the current buffer (at the moment it will free all the fragments). The caller to net_buf_unfref() would be responsible for dropping the refcount on all the remaining fragments.
> 
> I think this would be more consistent with net_buf_ref() which only increments the count for the current buffer.

This is the right option, but the way you phrase things indicates some confusion around why the API is  the way it is currently. There is no explicit "free buffer" API, so you can't really talk in terms of what should or shouldn't free a buffer. The API is explicitly designed around the concept of reference counting, where a reference is simply a pointer variable pointing at a buffer. Freeing is a buffer-internal detail which happens implicitly when the buffer determines that no one is referencing it anymore.

Since a buffer has a reference to the next fragment (if there is one) it should drop that reference (i.e. call `net_buf_unref()`) when the buffer itself gets freed. The buffer has no visibility or responsibility to the "fragments of the fragment" when doing this, i.e. it's likewise the responsibility of the next fragment to manage its own fragment list, and so on.

**Comment by talih0** [comment]
> > The other option is to explicitly say that net_buf_unref() will only drop the reference count on the current buffer and free **only** the current buffer (at the moment it will free all the fragments). The caller to net_buf_unfref() would be responsible for dropping the refcount on all the remaining fragments.
> > I think this would be more consistent with net_buf_ref() which only increments the count for the current buffer.
> 
> This is the right option, but the way you phrase things indicates some confusion around why the API is the way it is currently. There is no explicit "free buffer" API, so you can't really talk in terms of what should or shouldn't free a buffer. The API is explicitly designed around the concept of reference counting, where a reference is simply a pointer variable pointing at a buffer. Freeing is a buffer-internal detail which happens implicitly when the buffer determines that no one is referencing it anymore.
> 
> Since a buffer has a reference to the next fragment (if there is one) it should drop that reference (i.e. call `net_buf_unref()`) when the buffer itself gets freed. The buffer has no visibility or responsibility to the "fragments of the fragment" when doing this, i.e. it's likewise the responsibility of the next fragment to manage its own fragment list, and so on.

I think I came up with a simpler fix by only bumping the ref count of head during a shallow clone of a packet.
I slightly reworded the commit message in the latest version I pushed.

**Review by jhedberg — DISMISSED** [review]

**Comment by talih0** [comment]
ping pls

**Review by rlubos — COMMENTED** [review]
Looks ok, however, there are a lot of compliance warnings in the new test cases, please fix them.

**Review by rlubos — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by chrta** [comment]
I ran into this issue in a zephyr-3.1-based firmware that does routing between two network interfaces. This pr fixed that issue for me.

**Comment by talih0** [comment]
> I ran into this issue in a zephyr-3.1-based firmware that does routing between two network interfaces. This pr fixed that issue for me.

@chrta This PR may also be of interest for your use case
https://github.com/zephyrproject-rtos/zephyr/pull/48218

**Pull request merged**
