### PR TITLE
Deprecate RPL

### PR DESCRIPTION
**Pull request by rveerama1**
RPL is no longer interest of Zephyr community. We already sent mail to mailing list for new maintainer. Also informed about this in Zephyr Networking Forum. No response received so far. So deprecating RPL.

### CODE REVIEW

**Review by jfischer-no — DISMISSED** [review]
please wait with deprecating, i will look at the rpl after ELCE2018

**Comment by rveerama1** [comment]
> please wait with deprecating, i will look at the rpl after ELCE2018

Ok.

**Comment by rveerama1** [comment]
> please wait with deprecating, i will look at the rpl after ELCE2018

@jfischer-phytec-iot So, what are your plans about RPL?

**Comment by pfalcon** [comment]
@jfischer-phytec-iot: Ping again.

And let me actually approve this, to appreciate @rveerama1's efforts to move forward with this (i.e. making clear to any users that this library in Zephyr is unmaintained).

**Review by pfalcon — APPROVED** [review]
Approving by timeout.

**Comment by rveerama1** [comment]
@jfischer-phytec-iot, you can revert this incase if you have proper plan how you are going to continue with RPL.

**Comment by rveerama1** [comment]
@nashif @tbursztyka ping

**Comment by nashif** [comment]
recheck

**Review by nashif — APPROVED** [review]

**Pull request merged**
