### PR TITLE
dts: sam_e70_xplained: configure all UARTs

### PR DESCRIPTION
**Pull request by mnkp**
UART driver needs to be configured at boot or it will fail to initialize. This patch provides missing configuration data for all available UART devices. This ensures that the driver will initialize correctly when selected by Kconfig.

I'm not sure if the proposed solution is the correct one, however the current setup is inconsistent. If we enable an UART driver other than the default usart1 it will fail to initialize.

### CODE REVIEW

**Comment by mnkp** [comment]
@fallrisk please have a look.

**Review by galak — CHANGES_REQUESTED** [review]
Can you explain further what you exactly is happening w/regards to initialization and failing to boot.  The change doesn't seem like how we should be fixing this.

**Comment by mnkp** [comment]
If a user enables in Kconfig any other device than USART_1, let's say USART_0, the device initialization will fail during boot since the current speed values for USART_0 are not defined. The device will be unusable for the rest of the runtime.

**Comment by galak** [comment]
When you say the device, which device are you referring to. The full chip, USART_0 or USART_1?

**Comment by mnkp** [comment]
I'm not quite sure what you mean by full chip. I'm talking about any serial device e.g. USART_0 as selected by Kconfig: > Device Drivers > Serial Drivers > Atmel SAM MCU family USART driver > Enable USART0 config option. That is CONFIG_USART_SAM_PORT_0.

**Comment by ydamigos** [comment]
Shouldn't it fail during build?
I test it on stm32f3_disco board.
I enable the  CONFIG_UART_STM32_PORT_3=y in an application prj.conf without adding
```
&usart3 {
	current-speed = <115200>;
	status = "ok";
};
```
in the  stm32f3_disco.dts file and it fails at build time because the defines:
```
#define ST_STM32_USART_40004800_BASE_ADDRESS_0
#define ST_STM32_USART_40004800_CURRENT_SPEED		
#define ST_STM32_USART_40004800_IRQ_0	
#define ST_STM32_USART_40004800_IRQ_0_PRIORITY	
#define ST_STM32_USART_40004800_LABEL	
#define ST_STM32_USART_40004800_SIZE_0	
#define ST_STM32_USART_40004800_BASE_ADDRESS	
#define ST_STM32_USART_40004800_SIZE
```
are not generated in outdir/stm32f3_disco/include/generated/generated_dts_board.h.

@mnkp Did I understand the issue correctly?

**Comment by mnkp** [comment]
Sorry, yes, it should fail during build. That's the same issue as @ydamigos confirmed on stm32f3_disco board.

**Comment by ydamigos** [comment]
The issue is that, right now, we need to enable the device (UARTx, I2Cx) in a Kconfig file and to configure it in a dts file. I believe the goal is to enable the device in the boards dts file in the future. Of course this raises other questions like: will we be able to override the default board configuration using dts on our application?

**Comment by ydamigos** [comment]
Is it a good choice to enable all the U(S)ART interfaces? Aren't they multiplexed with other signals (SPI, I2C, etc) on some pins? In the future someone will add support for other interfaces and he will also need to enable them. Are there any rules / policies regarding the Zephyr default configuration on the supported boards? Do we try to keep some balance among the enabled interfaces?

**Comment by mnkp** [comment]
I guess someone needs to answer the question where do we go with DTS and what its intended usage is.

If we want to use DTS to enable/disable particular devices (rather than merely provide device configuration data) it's a whole another story. Enabling devices is currently handled by Kconfig and the change this PR introduces does not enable UARTs.

It's true though that `status = "ok"` line is meant to enable the device. The DTS and Kconfig are currently inconsistent. And if we are moving to DTS we should probably remove device enable options from Kconfig rather than go for the solution proposed in this PR.

One aspect of DTS which is still unclear to me despite searching online is: can DTS handle dependencies just as Kconfig can. I.e. if some sensor driver needs I2C to function properly does enabling sensor driver in DTS enables automatically required I2C device driver?

**Comment by galak** [comment]
The intent for per port cfg is to get that from the DT.  The Kconfig should just enable which driver and any software specific configuration options.

So right now we have to have the DT and Kconfig in sync, but once we can start generating the device structures from DT we can get away from that.

**Comment by ydamigos** [comment]
@galak We can keep the Zephyr default board configuration (Kconfig files and dts) in sync but we cannot stop a user enable any port (using prj.conf) in application project. Can we override the default dts in user application project?

**Comment by galak** [comment]
Yes, we can allow an app to overlay the board dts.

See examples in ./samples/bluetooth/hci_uart/nrf52_pca10040.overlay

**Comment by ydamigos** [comment]
@mnkp Should we close this PR? Someone is able to enable a port in prj.conf and add an overlay file to configure it.

**Comment by mnkp** [comment]
Yes, this PR should be closed. The proposed solution is not the right one.

**Pull request closed without merging**
