### PR TITLE
drivers: mbox: add IVSHMEM based mbox driver

### PR DESCRIPTION
**Pull request by uLipe**
Since the IPM drivers are moving towards deprecation the existing inter VM shared memory IPM driver needs to be converted into a Mailbox kind driver, this PR makes this conversion based on the existing IPM driver.

### CODE REVIEW

**Comment by uLipe** [comment]
Merging this driver would enable to using IPC subsystems on top of the IVSHMEM.

**Comment by uLipe** [comment]
Hi folks, any updates here?

**Comment by uLipe** [comment]
@carlocaione  sorry bothering you again, can you review it, or point who can I tag to review this one?

Thank you!

**Comment by uLipe** [comment]
@nashif who else should I relay this PR? It has been opened for a while.

Thank you.

**Review by tbursztyka — APPROVED** [review]
Seems fine to me. There could be a use for this in 2+ zephyr running in ACRN for instance.

**Comment by uLipe** [comment]
@tbursztyka could you point someone that may review this as well?

**Review by nashif — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@uLipe I am changing the milestone to 4.1 as the 4.0 release is now in testing phase and is only accepting bug fixes and documentation updates

**Pull request merged**
