### PR TITLE
mgmt: mcumgt: grp: img_mgmt: Erase slot sector by sector

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes an issue whereby a bluetooth link might become timed out during a flash erase process by splitting it up sector by sector

### CODE REVIEW

**Comment by de-nordic** [comment]
I am in favor of erasing flash page by page, as it also helps in multithreading - something we should generally address in our flash drivers, I have one question though this fix is needed even if we have tickler enabled in soc_flash_nrf driver?

**Comment by nordicjm** [comment]
> I am in favor of erasing flash page by page, as it also helps in multithreading - something we should generally address in our flash drivers, I have one question though this fix is needed even if we have ticker enabled in soc_flash_nrf driver?

The ticker itself wouldn't do anything for this but the Kconfig to enable partial erase would from what I can see, and if that is enabled then this PR seems moot.

**Comment by Laczen** [comment]
@nordicjm, the use of `flash_page_foreach` should be avoided as it will generate an error in case `CONFIG_USERSPACE` is enabled. To avoid this problem a PR (#68112) was proposed that allows getting the required info without `flash_page_foreach`.

**Comment by Laczen** [comment]
I was also wondering if partial erase would avoid this problem. The proposed PR will probably also not solve all cases, e.g. on stm32 devices with large blocks an erase (even by block) can require a long time.

**Comment by nordicjm** [comment]
> @nordicjm, the use of `flash_page_foreach` should be avoided as it will generate an error in case `CONFIG_USERSPACE` is enabled. To avoid this problem a PR (#68112) was proposed that allows getting the required info without `flash_page_foreach`.

Works fine, it would only have an error if it was running from a user mode thread but MCUmgr is kernel space

**Comment by nordicjm** [comment]
> I was also wondering if partial erase would avoid this problem. The proposed PR will probably also not solve all cases, e.g. on stm32 devices with large blocks an erase (even by block) can require a long time.

Only an issue for things like bluetooth, in the stm32 case bluetooth runs on a co-processor so should not be a problem

**Comment by Laczen** [comment]
> > @nordicjm, the use of `flash_page_foreach` should be avoided as it will generate an error in case `CONFIG_USERSPACE` is enabled. To avoid this problem a PR (#68112) was proposed that allows getting the required info without `flash_page_foreach`.
> 
> Works fine, it would only have an error if it was running from a user mode thread but MCUmgr is kernel space

Works for now. The use of `flash_page_foreach` should be avoided (although I like the methodology).

**Pull request closed without merging**
