### PR TITLE
scripts: runners: add frequency setting support for blackmagicprobe

### PR DESCRIPTION
**Pull request by kpochwala**
Black Magic Probe supports a "monitor frequency" command that sets
adapter frequency. [1]

Not really documented in blackmagicprobe docs, but does in fact change
upload speed.

[1] https://github.com/blackmagic-debug/blackmagic/blob/master/src/command.c#L75

Signed-off-by: Krzysztof Pochwała <k.pochwala@gmail.com>

### CODE REVIEW

**Review by mbolivar-nordic — COMMENTED** [review]
Hi and thanks for this.

The commit message doesn't seem to match the help string in the blackmagicprobe sources. The sources says something about "minimum high and low times", which I'm confused about. Can you provide some more details about this discrepancy please?

**Comment by kpochwala** [comment]
Hi @mbolivar-nordic,

sure, I can elaborate: this parameter is used to calculate periods of high and low pulses, which in turn change overall upload speed.It is used here:

https://github.com/blackmagic-debug/blackmagic/blob/master/src/command.c#L269

which in turn call platform-specific functions, for example:

for stm32 based: https://github.com/blackmagic-debug/blackmagic/blob/master/src/platforms/stm32/timing_stm32.c#L77
for launchpad-icdi it is unused: https://github.com/blackmagic-debug/blackmagic/blob/master/src/platforms/hosted/platform.c#L326
for esp8266 based fork: https://github.com/walmis/blackmagic-espidf/blob/master/main/platform.c#L69

and for hosted: https://github.com/blackmagic-debug/blackmagic/blob/master/src/platforms/hosted/platform.c#L326

this sets `swd_delay_cnt` (with exception for hosted and unused launchpad-icdi) - that is delay in ticks for given platform and its clock. This in turn is used in while-loop delays all over the place here (higher the delay, lower the speed):

for swd: https://github.com/blackmagic-debug/blackmagic/blob/master/src/platforms/common/swdptap.c#
for jtag: https://github.com/blackmagic-debug/blackmagic/blob/master/src/platforms/common/jtagtap.c

Is it sufficient? :)

**Review by henrikbrixandersen — APPROVED** [review]
LGTM

**Review by mniestroj — APPROVED** [review]

**Comment by carlescufi** [comment]
@kpochwala please fix the tests: https://github.com/zephyrproject-rtos/zephyr/runs/7148319992?check_suite_focus=true

**Comment by kpochwala** [comment]
> This pull request has been marked as stale because it has been open (more than) 60 days with no activity. Remove the stale label or add a comment saying that you would like to have the label removed otherwise this pull request will automatically be closed in 14 days. Note, that you can always re-open a closed pull request at any time.

sorry, totally forgot about this - will get back in following week

**Pull request closed without merging**
