### PR TITLE
MAINTAINERS: Add a maintainer and collaborator for Silabs Platforms

### PR DESCRIPTION
**Pull request by jhedberg**
Add Johan, Jerome and Aksel to Silabs Platforms. Also update the subsystem and GitHub label name from "SiLabs" to "Silabs", since this is the more usual spelling.

### CODE REVIEW

**Comment by jhedberg** [comment]
Regarding the label change, I already renamed it in GitHub, so this PR will sync up with that.

CC @Jerome-pouiller @asmellby

**Comment by jhedberg** [comment]
Also, could one of the zephyrproject-rtos admins please add @jerome-pouiller to the GitHub organization, so that he can be added as reviewer, etc.

**Review by jerome-pouiller — APPROVED** [review]
Looks good for me.

**Review by carlescufi — DISMISSED** [review]

**Comment by jhedberg** [comment]
After internal discussion, added @asmellby as well as a Collaborator

**Review by asmellby — APPROVED** [review]

**Review by carlescufi — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]

**Comment by jhedberg** [comment]
I had overlooked that the hal_silabs section also needs similar updates. Now fixed. @carlescufi @kartben you'll need to re-approve - sorry for the hassle.

**Review by kartben — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
