### PR TITLE
Zephyr v3.1.0

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
DNM, waiting for ACK from @carlescufi 

Final steps:

- update API overview page tracking release modifications
- update doc/conf.py and VERSION to 3.1.0
- bump PATCHLEVEL to .99 in VERSION in a final commit, opening up the floodgates again

### CODE REVIEW

**Review by stephanosio — APPROVED** [review]
> [VERSION: bump to 3.1.99](https://github.com/zephyrproject-rtos/zephyr/pull/46275/commits/8b209c70e7d1835c4b3e6b860b1357fe48dbe065)

Normally, bumping to 99 would be done in a separate PR after tagging the release, but it would also work if you make sure to tag the 3.1.0 release specifically on [release: Zephyr 3.1.0](https://github.com/zephyrproject-rtos/zephyr/pull/46275/commits/5f54b1a90b17fab7841c40590dc04a9312403b2e) instead of the latest commit after merging this PR.

**Comment by mbolivar-nordic** [comment]
> it would also work if you make sure to tag the 3.1.0 release specifically on [release: Zephyr 3.1.0](https://github.com/zephyrproject-rtos/zephyr/pull/46275/commits/5f54b1a90b17fab7841c40590dc04a9312403b2e) instead of the latest commit after merging this PR.

Yup, that's my plan exactly.

Normally, the fact that all the commits in a PR must be merged atomically is a liability. In this case, I'm taking advantage of it to make sure there is no possible gap between the release commit and the commit which opens the next merge window.

**Review by carlescufi — CHANGES_REQUESTED** [review]
We need to tag with the VERSION file at 3.1.0, not 3.1.99

**Comment by mbolivar-nordic** [comment]
> We need to tag with the VERSION file at 3.1.0, not 3.1.99

 Please read the commits in order and see the above discussion; there is a plan for this.

**Review by carlescufi — APPROVED** [review]

**Comment by nashif** [comment]
we will see how this works and still not sure what problem is this trying to solve, but this looks weird, you are creating a release and submitting a post-release commit at the same time and in the same PR. Atomicity is never guaranteed, because there is a gap between this being merged and creating the tag. This can be error prone as well, i.e.. tagging the wrong commit instead of just tagging HEAD and then also creating the branch....

**Pull request merged**
