### PR TITLE
Minor checkpatch fixes

### PR DESCRIPTION
**Pull request by de-nordic**
Fixes to CONSTANT_COMPARISON:
 1) there has been missing $ in variable reference;
 2) added check that allows conditional statements that have constants (literals) on both sides of am operator to pass through, without warning.

This should let PRs like here: https://github.com/zephyrproject-rtos/zephyr/pull/42049 go through

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by carlescufi** [comment]
The question is whether we shoudl allow const to const comparison in code or require some sort of macro to do this.

**Comment by gmarull** [comment]
> The question is whether we shoudl allow const to const comparison in code or require some sort of macro to do this.

Agreed

**Comment by de-nordic** [comment]
I have removed availability to pass `<numeric_literal> == PREPROCESSOR_DEF`.

> The question is whether we shoudl allow const to const comparison in code or require some sort of macro to do this.

@carlescufi @gmarull 

I do not think that this makes sense to enforce, taking aside DTS macros and so on, just generally. Basically if I would do:
```
#define IS_EQUAL(x, y) ((x) == (y))
#define SOME 1
#define OTHER 2

if (IS_EQUAL(SOME, OTHER)) {
....
}
```
above code would be considered OK although it just obfuscates:
```
if (SOME == OTHER) {
...
}
```

We allow `IS_ENABLED(...)` and really on C optimizations to make work of C preprocessor, and doing `SOME == OTHER` is the same, and this is not constant comparison directly because we do not know what, in reality, will be substituted in preprocessing phase for a given identifier.
Actually, we decide whether this is a constant identifier by a name, for example:
```
A0000
A_
A_IDENT
````
are constant, but
```
#define DT_N_S_analog_connector_P_compatible_EXISTS 1
```
is not.

Often we use code like this:
```
#define ERROR posix_print_error_and_exit
```
("drivers/serial/uart_native_posix.c" 442L)
to make life easier, and `posix_print_error_and_exit` is not constant.

Enforcing the rule we may actually hurt size optimizations in some cases, because you can override this with:
```
int left = SOME

if (left == OTHER) {
...
}
```
this may or may not be removed by compiler, if it is smart enough to figure out that `SOME == OTHER`, so `left == OTHER` and `left` is local variable being assigned literal.

Also we do not enforce the rule to the `switch`, which makes
```
switch(SOME) {
case OTHER:
    ...
}
```
possible even though it is basically `if (SOME == OTHER)`.
Just thinking...

**Comment by tejlmand** [comment]
> Just thinking...

Although you have some good reasoning, and examples on examples that are not caught by checkpatch, then the linked PR  #42049 that seems to be initial reason for this PR used the direct constant comparison and it appears that use is actually bad:
https://github.com/zephyrproject-rtos/zephyr/pull/42049#discussion_r821767374

So currently it does seem to be good that checkpatch failed in that PR.

For now, I think we need a better example where a const comparison fails, and is to be considered something that should be allowed.

**Comment by de-nordic** [comment]
> > Just thinking...
> 
> Although you have some good reasoning, and examples that are not caught by checkpatch, then the linked PR #42049 that seems to be initial reason for this PR used the direct constant comparison and it appears that use is actually bad: [#42049 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/42049#discussion_r821767374)

> 
It does not actually state it is bad, it states it is ugly, which is just an opinion, so generally code is OK
Additionally the code is mixed variable/constant comparison as the first if, at line 447, in if/else block, has variable as left side operand.
#fdefs will not make the code look nicer, definitely; and `IS_ENABLED` gymnastics is just putting lipstick on a pig.

**Comment by tejlmand** [comment]
> It does not actually state it is bad, it states it is ugly, which is just an opinion

but an opinion based on the fact that the driver is not multi-instance, and therefore such comparison is possible.
If code had proper multi-instance support, then such comparison would not be there in the first place.

So the fact that checkpatch fails makes it clear that this driver doesn't support multi-instance.

**Comment by de-nordic** [comment]
> So the fact that checkpatch fails makes it clear that this driver doesn't support multi-instance.

Fair enough.

**Pull request closed without merging**
