### PR TITLE
tests/spi: add a rx only test, benchmark, and Arduino Zero config.

### PR DESCRIPTION
**Pull request by nzmichaelh**
This gives better coverage on the SAM0 by exercising the RX only
paths.

The benchmark is a simple transcive-big-blocks-in-a-loop.  This is
useful for the SAM0 as the driver is CPU based and the benchmark shows
how close the driver gets to peak throughput.

Signed-off-by: Michael Hope <mlhx@google.com>

### CODE REVIEW

**Comment by nzmichaelh** [comment]
The extra whitespace changes convert spaces to tabs to make checkpatch happy.

**Review by tbursztyka — CHANGES_REQUESTED** [review]
Could not find anything wrong, just switch to LOG_*() macros instead of SYS_LOG_* ones

**Comment by aescolar** [comment]
@nzmichaelh are you planning to follow up on this PR? If not please close the PR (it can always be reopened later)

**Comment by jfischer-phytec-iot** [comment]
@benpicco FYI, maybe you want take it over.

**Pull request closed without merging**
