### PR TITLE
Bluetooth: Controller: Add support for scanning complete periodic adv trains

### PR DESCRIPTION
**Pull request by andrzej-kaczmarek**
This adds support to scan complete periodic adv trains including mixed scheduling from ULL/LLL if necessary.

### CODE REVIEW

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Review by ppryga-nordic — CHANGES_REQUESTED** [review]
I'm wondering about one situation. What in case the scanner is synchronized to periodic advertisement, there is a chain of e.g. 6 PDUs. 4th AUX_CHAIN_IND PDU is received with wrong CRC. node_rx is set to type: `NODE_RX_TYPE_EXT_AUX_RELEASE` but no report is generated to inform host about incomplete data and no more IQ reports. 

See 7.7.65.21 LE Connectionless IQ Report event:
> This event is also used by the Controller to report that it has insufficient
resources to report IQ samples for all received Constant Tone Extensions and
has failed to sample at least once. In this case Packet_Status shall be set to
0xFF and Sample_Count to 0x00.

**Review by cvinayak — COMMENTED** [review]
Did a quick pass, looks good. Will do some testing and review early tomorrow, and will get back.

**Review by ppryga-nordic — CHANGES_REQUESTED** [review]
I went over last commit very briefly. I'll continue that in the morning.

**Review by ppryga-nordic — COMMENTED** [review]
There are some not addressed comments.

**Review by cvinayak — APPROVED** [review]
No more stressing change requests from my side. I could not get to testing, but will do when I can get to it in my todo. Any functional issues can be address when discovered as bug fixes.

**Review by ppryga-nordic — APPROVED** [review]
Tested with use of `direction_finding_connectionless_rx`. Changes approved.

**Pull request merged**
