### PR TITLE
Charger API Documentation Cleanup

### PR DESCRIPTION
**Pull request by rriveramcrus**
During the churn of the initial Charger API PR the documentation for the charging API got stale and fell behind. This PR corrects the documentation up.

### CODE REVIEW

**Comment by nashif** [comment]
while you are at it, can you please add the charger into the Maintainer file please?

**Comment by rriveramcrus** [comment]
Hello @nashif,

@aaronemassey and I are in discussions with a potential co-maintainer. We will update this PR once the details have been ironed out. Sorry for the delay.

**Review by nashif — DISMISSED** [review]

**Comment by nashif** [comment]
> @aaronemassey and I are in discussions with a potential co-maintainer. We will update this PR once the details have been ironed out. Sorry for the delay.

start with a skelton at least, we can add/remove people as maintainers an co-maintainers later. This will help with adding reviewers and auto-labeling etc.

**Comment by kartben** [comment]
@rriveramcrus 
not directly related to this PR but please look into moving the charger sample from samples/charger to samples/drivers/charger when you have a chance. It could also use a README :)

**Comment by rriveramcrus** [comment]
@nashif, I have added @aaronemassey and myself as maintainers. I will create a separate PR later to update the new comaintainer.

**Review by nashif — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
