### PR TITLE
drivers: timer: systick: fix off-by-one setting

### LINKED ISSUE #15309: ARM Cortex-M SysTick Load value setting off-by-one
When the counter reaches zero, it reloads the value in
SYST_RVR on the next clock edge. This means that if the
LOAD value is N, the interrupt ("tick") is triggered
every N+1 cycles. Therefore, when we operate in non-
tickless mode, we need to configure the LAOD value
with CYC_PER_TICK - 1, in order to get an event
every CYC_PER_TICK cycles.

Reference: https://developer.arm.com/docs/dui0471/l/handling-processor-exceptions/configuring-systick

### LINKED ISSUE #15348: ARM Cortex-M: SysTick: unhandled race condition
It looks like we are not handling properly a possible race condition in ARM Cortex-M SysTick.

The implementation in `z_clock_set_timeout()` for TICKLESS mode performs the following steps:
1. Disables interrupts
2. Calculates SysTick re-load value based on the desired timeout
3. Re-configures and re-starts the SysTick timer to count-down towards this timeout.
4. Re-enables interrupts.

If, during steps (1) and (2) the SysTick actually wraps, an event will be triggered and the SysTick interrupt will be pending. As a result, as soon as we re-enable the interrupt, the ISR will be executed immediately; not after the desired timeout.

The event is rare but the impact is significant - we are advancing the clock immediately, when we should have been waited for the timeout.

Root-cause and solution:
Clearing the internal SysTick status flag (CTRL.COUNTFLAG) is not sufficient to clear a pending event; we also need to do it explicitly in ICSR (Clear the PENDSTSET bit).

Reproduce:
I have written a simple HW test case for ARM SysTick (a modified hello-world example) here:

https://github.com/ioannisg/zephyr/tree/drivers_systick_testcase/samples/hello_world

which demonstrates that clearning the COUNTFLAG is not sufficient to suppress already pending events (See TEST 4 and TEST 5).

### PR DESCRIPTION
**Pull request by ioannisg**
When the counter reaches zero, it reloads the value in
SYST_RVR on the next clock edge. This means that if the
LOAD value is N, the interrupt ("tick") is triggered
every N+1 cycles. Therefore, when we operate in non-
tickless mode, we need to configure the LOAD value
with CYC_PER_TICK - 1, in order to get an event
every CYC_PER_TICK cycles.

Fixes #15309 

Update: we address the race condition in TICKLESS mode in this pull-request, too.

Fixes #15348 

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Good point.

**Comment by ioannisg** [comment]
Note that subtracting 1 makes the first event occur slightly earlier, but fixes the time for all the remaining events, afterwards.

**Comment by pizi-nordic** [comment]
> Note that subtracting 1 makes the first event occur slightly earlier, but fixes the time for all the remaining events, afterwards. @andyross , do you think this deserves an inline explanatory comment?

IMHO This could be fixed ultra-easily:
LOAD = CYC_PER_TICK - 1;
VAL = LOAD + 1;

**Comment by ioannisg** [comment]
> 
> 
> > Note that subtracting 1 makes the first event occur slightly earlier, but fixes the time for all the remaining events, afterwards. @andyross , do you think this deserves an inline explanatory comment?
> 
> IMHO This could be fixed ultra-easily:
> LOAD = CYC_PER_TICK - 1;
> VAL = LOAD + 1;

Thanks, @pizi-nordic . 
Actually, now that I am thinking more, maybe your suggestion is not needed. (But it definitely works).
If e.g. LOAD = 99, and VAL = 0, we need 1 cycle for VAL to be 99, and then 99 cycles to trigger the event (Triggers when going from 1 to 0). So seems we are good.

**Comment by ioannisg** [comment]
Adding an extra commit for Code-Ownership of this file, which was missing.

**Comment by pizi-nordic** [comment]
I also think that this is not a big deal: There will be one cycle miss in uptime, which is already affected by the time needed to init the system, so it is already imprecise.

**Review by pizi-nordic — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Review by pizi-nordic — APPROVED** [review]

**Comment by ioannisg** [comment]
Please, re-review

**Review by MaureenHelm — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Note that the extra -1 in z_clock_set_timeout() is going to be swamped by the overhead of the read/compute/write cycle, which we don't try to finesse.  Not technically wrong, of course.  We'd need to write some assembly and carefully cycle-count the code to do this truly correct.

The pending interrupt clear looks right per my read of the docs, but of course I'm no expert there.

**Pull request merged**
