### PR TITLE
 scripts: dts: Use DT_ prefix in generated labels

### PR DESCRIPTION
**Pull request by anangl**
As agreed at ELCE, these are the changes required to proceed further with #10377.

I wasn't sure how to treat some FLASH related labels (like `FLASH_WRITE_BLOCK_SIZE`) since they are directly referenced from existing code. I decided to leave them in the current form, see the commit message.

### CODE REVIEW

**Comment by SebastianBoe** [comment]
Relates to https://github.com/zephyrproject-rtos/zephyr/issues/7213

**Review by erwango — COMMENTED** [review]
I'm fine with the change.

Two points before approval:
- What is the rational for adding compat in alias prefix? Won't we loose genericity?
- When discussing with @carlescufi , we concluded compat flags should remain in CONFIG namespace, though, I can't recall the reason, raised question here: https://github.com/zephyrproject-rtos/zephyr/issues/10821#issuecomment-436947248

**Comment by carlescufi** [comment]
@erwango @anangl @galak 

>When discussing with @carlescufi , we concluded compat flags should remain in CONFIG namespace, though, I can't recall the reason, raised question here: #10821 (comment)

This is actually not the case, I edited my comment in #10821. One thing is the macros/defines generated by DT, which need to live in the `DT_` namespace. The other is future Kconfig options set by DT, for which we need to invert the order in which Kconfig and DT are run. These will not be macros, but actually Kconfig fragment files. So in the future we will define:

```
.h file:
#define DT_COMPAT_STM32_SPI 1
.conf file:
CONFIG_DT_COMPAT_STM32_SPI=y
```
So what @anangl has done is fine in my opinion.

**Comment by anangl** [comment]
@erwango 
> What is the rational for adding compat in alias prefix? Won't we loose genericity?

To indicate the purpose of the value that the label defines and this way help preventing misuses of the label (see #10377, we want to use labels generated through aliases in drivers, to avoid creating fixups). @galak, please correct me if I didn't clearly or entirely read your idea of adding this.
We won't loose genericity. For generic nodes we'll still get generic prefixes, for instance DT_GPIO_LEDS_ for "gpio-leds" compatibles. The only disadvantage I see is that the label name lengthens, but I guess it is an acceptable price.

**Comment by erwango** [comment]
@carlescufi 

> So in the future we will define:
> 
> ```
> .h file:
> #define DT_COMPAT_STM32_SPI 1
> .conf file:
> CONFIG_DT_COMPAT_STM32_SPI=y
> ```

Then, how will we link both ? Btw, raising question in #9406, so discussion could continue here, and not disturb current PR.

**Comment by erwango** [comment]
@anangl 

> For generic nodes we'll still get generic prefixes, for instance DT_GPIO_LEDS_ for "gpio-leds" compatibles.

So indeed, I was wondering on non generic nodes, like for instance, if we have: 
```
	aliases {
		zi2c = &i2c1;
	};
```

So generated #define will use i2c1 compatible field.
Which means we won't be able to use a ZI2C_NAME for testing for instance. And we'll always need fixup to establish generic #define's like
#define CONFIG_I2C_1_NAME			ST_STM32_I2C_V2_40005400_LABEL
Or we'll need other approach than alias to establish generic devices bindings

**Comment by anangl** [comment]
> Which means we won't be able to use a ZI2C_NAME for testing for instance. And we'll always need fixup to establish generic #define's like
> #define CONFIG_I2C_1_NAME	ST_STM32_I2C_V2_40005400_LABEL
> Or we'll need other approach than alias to establish generic devices bindings

Yes. It won't be possible to use aliases for this.
@galak, how can we solve this? Using `chosen` maybe?

**Comment by galak** [comment]
> Yes. It won't be possible to use aliases for this.
> @galak, how can we solve this? Using `chosen` maybe?

I'm confused, what's the concern / problem?  We should have the alias replace a very specific part of symbol name we create.

**Comment by galak** [comment]
Can you pull out the reelboard fix into its own PR, we can merge that right away.

**Comment by erwango** [comment]
@galak 

> I'm confused, what's the concern / problem? We should have the alias replace a very specific part of symbol name we create.

My point is that by introducing 'compatible' in alias #define we lose genericity of the alias

**Review by galak — CHANGES_REQUESTED** [review]
I'd like to see all the alias handling in scripts/dts done in a single place, rather than having it across every extractor.

**Comment by galak** [comment]
> I'd like to see all the alias handling in scripts/dts done in a single place, rather than having it across every extractor.

This way the rules about how aliases are used/defined/created will be consistent.

**Comment by carlescufi** [comment]
@anangl as per a conversation on [Slack](https://zephyrproject.slack.com/archives/C18PLHN8H/p1541695284179800) we should also rename (`CONFIG_` to `DT_`) the left side of the fixup files, but only for those that do not map to an existing Kconfig symbol. I can help you out with that.

**Comment by ulfalizer** [comment]
I could hack up a version of this tomorrow. Off to bed now.

**Comment by ulfalizer** [comment]
@carlescufi @andrzej-kaczmarek 
Script below. Run it in the top-level Zephyr directory.

Here's the spec I followed:

1. Read the contents of all dts_fixup.h files in Zephyr
2. Check the left-hand side of the #define macros (i.e. the X in #define X Y)
3. Check if that name is also the name of a Kconfig option
3.a If it is, then do nothing
3.b If it is *not*, then replace `CONFIG_` with `DT_`
4. Replace the use of the changed #define in the code itself (.c, .h)

I wonder if the search should include other files as well. It could be pretty easy to tweak at least.

Tell me if you spot any issues or want any tweaks.

```python3
#!/usr/bin/env python3

import glob
import os
import re
import sys

# Use our own Kconfiglib
sys.path.insert(0, "scripts/kconfig")
import kconfiglib

# Referenced in the Kconfig files. The glob patterns include the entire Kconfig
# tree.
os.environ["KERNELVERSION"]="1.0.0"
os.environ["BOARD_DIR"]="boards/*/*/"
os.environ["ARCH"]="*"
os.environ["SOC_DIR"]="soc/"
os.environ["SRCARCH"]="x86"

# Set with all Kconfig symbol names
sym_names = {sym.name for sym in kconfiglib.Kconfig().unique_defined_syms}

# List of CONFIG_FOO #defines in dts_fixup.h files that aren't Kconfig symbols.
# The "FOO" part is stored.
fake_sym_names = []
for filename in glob.glob("**/dts_fixup.h", recursive=True):
    for match in re.finditer("^\s*#\s*define\s*CONFIG_(\w*)",
                             open(filename, encoding="utf-8").read(),
                             re.MULTILINE):
        if match.group(1) not in sym_names:
            fake_sym_names.append(match.group(1))

# The byte string shenanigans below is to preserve line endings and support
# files with non-UTF-8 encodings (we seem to have some)

# See e.g.
# https://stackoverflow.com/questions/6116978/how-to-replace-multiple-substrings-of-a-string.
# Use \b word boundaries to avoid replacing CONFIG_FOO in CONFIG_FOO_BAR.
replace_re = re.compile(
    b"\\bCONFIG_(" + b"|".join(name.encode() for name in fake_sym_names) + b")\\b")
def replace_fake(s):
    # Replaces all "CONFIG_FOO" where FOO is not a Kconfig symbol with
    # "DTS_FOO", in the string 's'
    return replace_re.sub(lambda match: b"DTS_" + match.group(1), s)

# Do the replacement
for pattern in "**/dts_fixup.h", "**/*.c", "**/*.h":
    for filename in glob.glob(pattern, recursive=True):
        contents = open(filename, "rb").read()
        open(filename, "wb").write(replace_fake(contents))
```

**Comment by ulfalizer** [comment]
Version 2 that also adds "DT_" to macros to dts_fixup.h macros starting with neither DT_ nor CONFIG_:

```python3
#!/usr/bin/env python3

import glob
import os
import re
import sys

# Use our own Kconfiglib
sys.path.insert(0, "scripts/kconfig")
import kconfiglib

# Referenced in the Kconfig files. The glob patterns include the entire Kconfig
# tree.
os.environ["KERNELVERSION"] = "1.0.0"
os.environ["BOARD_DIR"] = "boards/*/*/"
os.environ["ARCH"] = "*"
os.environ["SOC_DIR"] = "soc"
os.environ["SRCARCH"] = "x86"

# Set with all Kconfig symbol names
sym_names = {sym.name for sym in kconfiglib.Kconfig().unique_defined_syms}

# List of CONFIG_FOO #defines in dts_fixup.h files that aren't Kconfig symbols.
# The "FOO" part is stored.
fake_sym_names = []

# List of #defines that in dts_fixup.h files that start with neither CONFIG_
# nor DT_
unprefixed_macros = []

for filename in glob.glob("**/dts_fixup.h", recursive=True):
    for match in re.finditer("^\s*#\s*define\s+(\w+)",
                             open(filename, encoding="utf-8").read(),
                             re.MULTILINE):
        macro = match.group(1)
        if macro.startswith("CONFIG_"):
            name = macro[7:]
            if name not in sym_names:
                fake_sym_names.append(name)
        elif not macro.startswith("DT_"):
            unprefixed_macros.append(macro)

# The byte string shenanigans below is to preserve line endings and support
# files with non-UTF-8 encodings (we seem to have some)

# See e.g.
# https://stackoverflow.com/questions/6116978/how-to-replace-multiple-substrings-of-a-string.
# Use \b word boundaries to avoid replacing CONFIG_FOO in CONFIG_FOO_BAR.

# CONFIG_ macros not in Kconfig
fake_re = b"CONFIG_(?:" + \
              b"|".join(name.encode() for name in fake_sym_names) + \
          b")"

# Macros prefixed with neither CONFIG_ nor DT_
unprefixed_re = b"|".join(name.encode() for name in unprefixed_macros)

replace_re = re.compile(fake_re + b"|" + unprefixed_re)

def replace(s):
    # Replaces non-Kconfig CONFIG_* macros with DT_* macros and adds a DT_
    # prefix to unprefixed macros, in 's'

    def sub_fn(match):
        match_s = match.group()
        if match_s.startswith(b"CONFIG_"):
            return b"DT" + match_s[6:]
        return b"DT_" + match_s

    return replace_re.sub(sub_fn, s)

# Do the replacement
for pattern in "**/dts_fixup.h", "**/*.c", "**/*.h":
    for filename in glob.glob(pattern, recursive=True):
        contents = open(filename, "rb").read()
        open(filename, "wb").write(replace(contents))
```

**Comment by ulfalizer** [comment]
@carlescufi @andrzej-kaczmarek @anangl
Added a small fix to v2 (forgot the `\b` word boundaries from v1). Not sure if it makes any difference for the output, but to be safe.

**Comment by carlescufi** [comment]
@galak 

>I'd like to see all the alias handling in scripts/dts done in a single place, rather than having it across every extractor.

Can we merge all the changes to the fixup files and the rest and then follow-up in a second PR? This PR is hard to merge because it gets stale quickly.

**Comment by anangl** [comment]
Added a commit with changes created by the above script (v2 with small modification - exclusion of the ext/ folder).
The reel_board related commit (pulled out to #11251) is still here so that CI has a chance to succeed.

**Comment by anangl** [comment]
This won't be that easy to update all these labels defined by dts_fixups with just a script.
They are often used in macros in parameterized forms, for instance:
```
CONFIG_GPIO_STM32_GPIO##__SUFFIX##_BASE_ADDRESS
```
or
```
CONFIG_UART_##idx##_TX_PIN
```
Any ideas how to automatically catch all these?

**Comment by galak** [comment]
We should aim at getting CI passing or close to it to get this merged.  I would suggest doing the following on a local box:

./scripts/sanitycheck -T samples/hello_world/ -N -l

**Comment by carlescufi** [comment]
> This won't be that easy to update all these labels defined by dts_fixups with just a script.
> They are often used in macros in parameterized forms, for instance:
> 
> ```
> CONFIG_GPIO_STM32_GPIO##__SUFFIX##_BASE_ADDRESS
> ```
> or
> 
> ```
> CONFIG_UART_##idx##_TX_PIN
> ```
> Any ideas how to automatically catch all these?

Are those in the drivers or in the `dts_fixup.h` files?
@galak do you have any recommendations here?

**Comment by anangl** [comment]
> Are those in the drivers or in the `dts_fixup.h` files?

In drivers. See for example [here](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/gpio/gpio_stm32.c#L223).

**Comment by loicpoulain** [comment]
Sorry, but why using the specific DT_ prefix? device-tree is one way to describe hardware but other methods or tools exist. We don't really care if they are generated from a device-tree, manually or other...  this should be abstracted. A e.g. 'HW_' prefix makes more sense to me.

**Comment by carlescufi** [comment]
@loicpoulain this is for data extracted from Device Tree. You can still use HW_ if you really have a driver that doesn’t use DT

**Comment by loicpoulain** [comment]
@carlescufi, @ulfalizer 
I'm not against moving to a dedicated prefix, I assume CONFIG should be only used for configuring OS features (not hardware layout). But I think it's a pity to move to a Device Tree centric approach whereas device tree could be completely abstracted. A driver should not care about the underlying way the hardware is described, it just needs to retrieve the resources in a generic way. For example, Linux uses unified device properties interface to access hardware resources whether they are described with device-tree, with ACPI or statically in the source. Don't want to block this PR though if you think this is the way to go.

**Comment by ulfalizer** [comment]
@loicpoulain 
I'm a device tree noob to be honest.

Does it make a difference that Zephyr does that compile-time device tree thing? If it's abstracted, I guess it might have to be in a way that still allows things to get compiled away when settings happen to come from DT. That might be doable though.

No strong opinions here from me at least.

**Comment by anangl** [comment]
Rebased on master to use the reel_board fix from there. Applied one more correction to make the CI green. However, I don't know how to deal with [this error](https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/26695/5/tests). It does not seem to be related.

**Comment by carlescufi** [comment]
@loicpoulain @ulfalizer 
> I'm not against moving to a dedicated prefix, I assume CONFIG should be only used for configuring OS features (not hardware layout). But I think it's a pity to move to a Device Tree centric approach (DT_) 

I see your point now. I think this is for @galak to comment on but as far as I know for Zephyr we are essentially making Device Tree the only source of truth. This is as you mention different from Linux, I will let @galak comment on that.

**Comment by erwango** [comment]
@loicpoulain 

> For example, Linux uses unified device properties interface to access hardware resources whether they are described with device-tree, with ACPI or statically in the source. Don't want to block this PR though if you think this is the way to go.

This is an interesting point and I think work in #10904. While it is for now a device tree only work, following point opens the possibility to use generic HW description.

> * Implementation basics:
>   * Input: 
>     * EDTS Python library API (cf https://github.com/zephyrproject-rtos/zephyr/pull/9876, and zephyr/topic-EDTS branch) exclusively. No use of the `edts.json` directly in order to avoid reliance on the JSON formatting 

Though, this is a whole new story. This can be added as a new Zephyr issue, but will have to be studied in a next step. Let's try to enable the use of one formatted description for now and once it is done maybe we can study how to enable more.
Btw, it is still possible to provide HW description "statically in the source", so that's one point available already :-)

**Comment by anangl** [comment]
I solved the problem with parameterized forms of the defined macros, as well as some other issues that popped up (see the last commit message), by tweaking the Ulf's script a bit more.
@galak Could this be merged as it is now, and the further improvement of the extracting scripts done in a follow-up PR [as Carles suggested](https://github.com/zephyrproject-rtos/zephyr/pull/11180#issuecomment-437342261)?

**Comment by carlescufi** [comment]
> I solved the problem with parameterized forms of the defined macros, as well as some other issues that popped up (see the last commit message), by tweaking the Ulf's script a bit more.
> @galak Could this be merged as it is now, and the further improvement of the extracting scripts done in a follow-up PR [as Carles suggested](https://github.com/zephyrproject-rtos/zephyr/pull/11180#issuecomment-437342261)?
> EDIT: Right after I added this comment and the CI finished successfully, another couple of conflicts appeared...

https://en.wikipedia.org/wiki/Sisyphus

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Going to merge it, and we'll deal with any fixup, etc after.

**Comment by mnkp** [comment]
This PR has been merged however I would like to add one comment.

> > What is the rational for adding compat in alias prefix? Won't we loose genericity?
> 
> To indicate the purpose of the value that the label defines and this way help preventing misuses of the label (see #10377, we want to use labels generated through aliases in drivers, to avoid creating fixups). [...]
> We won't loose genericity. For generic nodes we'll still get generic prefixes, for instance DT_GPIO_LEDS_ for "gpio-leds" compatibles. The only disadvantage I see is that the label name lengthens, but I guess it is an acceptable price.
> -- @anangl

According to the Devicetree Specification "The alias node shall be at the root of the devicetree". Which implies that properties defined by the node belong to the global namespace. We probably shouldn't prefix defines generated from the aliases node with 'compatible' property.

**Comment by anangl** [comment]
> According to the Devicetree Specification "The alias node shall be at the root of the devicetree". Which implies that properties defined by the node belong to the global namespace. We probably shouldn't prefix defines generated from the aliases node with 'compatible' property.

But please note that we don't generate labels for the properties of the "aliases" node themselves. These properties (i.e. actual definitions of aliases) provide only alternative (usually shorter) paths to other nodes defined in the Devicetree, and they are used here exactly for this purpose. Therefore, for every node for which an alias is also defined, we generate an extra set of labels with the middle part (normally derived from the path to the node) replaced with the alias name.

If I am not precise enough in my explanation, I hope @galak can correct me or elaborate on this. In [one the comments above](https://github.com/zephyrproject-rtos/zephyr/pull/11180#issuecomment-437062203) he already stated:
> We should have the alias replace a very specific part of symbol name we create.

**Comment by pabigot** [comment]
@anangl If `add_prop_aliases` in `extract/globals.py` is modified to prefix `DT_` to what's emitted under `--old-alias-names` I think we'd get something pretty close to what is being requested.  Though there might be some multiple-definition issues to catch.

**Comment by mnkp** [comment]
> Therefore, for every node for which an alias is also defined, we generate an extra set of labels with the middle part (normally derived from the path to the node) replaced with the alias name.

From the Devicetree Specification: "Each property of the /aliases node defines an alias. The property name specifies the alias name. The property value specifies the full path to a node in the devicetree". It implies that an alias can replace the full path to the node name. 

If we remove 'compatible' from the defines generated for aliases it doesn't stop us from using them in the device drivers and getting rid of the dts_fixup.h files. Every alias refers to a single, distinct hardware module.

Also, the current approach of prefixing defines generated for aliases with 'compatible' property doesn't solve any problem, instead it creates some:

>> So indeed, I was wondering on non generic nodes, like for instance, if we have:
>> 
>> ```
>> 	aliases {
>> 		zi2c = &i2c1;
>> 	};
>> ```
>> 
>> So generated #define will use i2c1 compatible field.
>> Which means we won't be able to use a ZI2C_NAME for testing for instance. And we'll always need fixup to establish generic #define's like
>> #define CONFIG_I2C_1_NAME ST_STM32_I2C_V2_40005400_LABEL
>> Or we'll need other approach than alias to establish generic devices bindings
>> -- @erwango
>
> Yes. It won't be possible to use aliases for this.
> how can we solve this? Using `chosen` maybe?
> -- @anangl

**Comment by mnkp** [comment]
Just one more comment. If, for some reason, we would prefer to use a 'qualified' names in the defines there is a different approach which does not involve misusing aliases node.

According to the specification a DTS node is defined as
```
[label:] node-name[@unit-address] {
	[properties definitions]
	[child nodes]
}
```
e.g.
```
usart0: usart@40010000 { /* USART0 */
		[...]
};
```
where usart0 is a node label. We could modify the script to generate DT_ defines that use label name rather than a unit address. E.g.
```
DT_SILABS_GECKO_USART_40010000_BASE_ADDRESS=0x40010000
```
would become
```
DT_SILABS_GECKO_USART_USART0_BASE_ADDRESS=0x40010000
```
As such the resulting defines would relay on logical names and not on part number dependent, fixed addresses. Such defines could be used directly by the device drivers without the need for dts_fixup entries.

**Comment by pfalcon** [comment]
> would become
> DT_SILABS_GECKO_USART_USART0_BASE_ADDRESS=0x40010000

@mnkp: You're touching on very important issue, which drills back of my mind for a long time. Suppose I wrote driver_foo.c, how to make it work for board1 with foo@10000000 and board2 with foo@20000000?

So, please continue! I'm happy to give +0.9 for any suitable proposal which addresses that sanely (+0.9 because I don't think U know DT enough to be 100% sure that some solution is the best one).

**Comment by mnkp** [comment]
Let's continue discussion related to use of aliases, node labels and other issues which goal is to eliminate dts_fixup files to #11737 since this PR has already been merged and lists many participants who are likely not interested in the topic.

**Pull request merged**
