### PR TITLE
tests: c_lib: Enable sqrt tests in non-FPU configurations

### PR DESCRIPTION
**Pull request by tbr-tt**
This enables the sqrt() and sqrtf() tests also in case of soft-float configurations. It is expected that the tests will link, run and pass also with soft-float. As proposed in #63438.

EDIT: The note below was applicable before Zephyr SDK 0.16.4 was released:
~~NOTE: At the moment this PR is expected to fail CI on qemu_x86 and qemu_sparc in picolibc configuration, which should be resolved by #62882.~~

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@keith-packard will you please take a look?

**Comment by keith-packard** [comment]
> @keith-packard will you please take a look?

This needs #62882 as that has the x86 soft float fixes.

**Comment by tbr-tt** [comment]
This test now passes in CI and with Zephyr SDK 0.16.4.

**Review by keith-packard — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
Nice work 👍

**Pull request merged**
