### PR TITLE
cmake: extensions: fix set_ifndef behavior

### PR DESCRIPTION
**Pull request by mbolivar**
The current set_ifndef() behavior is not correct if:

1. the variable is already set, and
2. the "if not defined" value evaluates to an empty string

For example:

```
set_ifndef(VAR_IS_SET $ENV{UNSET_ENV_VAR})
```

If the variable VAR_IS_SET already has a value, but UNSET_ENV_VAR is
not defined in the environment, a CMake syntax error occurs.

This happens, for example, in gccarmemb.cmake:

```
set_ifndef(GCCARMEMB_TOOLCHAIN_PATH $ENV{GCCARMEMB_TOOLCHAIN_PATH})
```

If GCCARMEMB_TOOLCHAIN_PATH is already set in CMake, but the environment variable is not, this errors out unnecessarily.

Fix this behavior by deferring the check for whether at least one value is present to when the variable doesn't have a value set.

### CODE REVIEW

**Comment by SebastianBoe** [comment]
Hi, I'm sorry, but I'm pretty sure the original behaviour was the expected/intended behaviour.

This is not specific to the set_ifndef function, the user must surround values with \" when the value might be unset. ($ENV{UNSET_ENV_VAR} does not evaluate to the empty string value, it evaluates to, well, nothing, you can think of it as if the interpreter skips the token, or as if the C preprocessor expands an unset macro)

The same happens with the CMake message command for instance.

```
message("$ENV{YOYO}")
message($ENV{YOYO})
message()
message("")
message($ENV{ZEPHYR_BASE})
```

The above will error on line 2 and 3. And otherwise behave as expected. (YOYO is not set)

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
.

**Comment by mbolivar** [comment]
Hi @SebastianBoe, thank you for taking the time to explain.

I can't say I find this "feature" of the CMake language very intuitive, but I accept your explanation based on message().

I've updated this PR to fix all the call sites instead of putting the check into the function itself. Would you please re-review?

**Review by SebastianBoe — APPROVED** [review]
Not intuitive indeed.

**Review by nashif — APPROVED** [review]

**Pull request merged**
