### PR TITLE
Bluetooth: host: Add bond_deleted callback

### LINKED ISSUE #20978: Add bond_deleted callback
**Is your feature request related to a problem? Please describe.**
In order to keep track of bonds in an application, a `bond_deleted` callback needs to be added to Zephyr. Currently there is no way for an application to know when a bond has been removed, except for using the `bt_foreach_bond()` API. Even then it is unclear when to call this API.

**Describe the solution you'd like**
In case the stack removes a bond, for example when enabling `CONFIG_BT_KEYS_OVERWRITE_OLDEST`, an application needs to be able to know what bond was removed using a callback.

**Describe alternatives you've considered**
Not sure what an alternative would be.

**Additional context**
From slack:

> Joakim Andersson 2:24 PM
> maybe make a feature request, I didn't want to tie the whitelist to this since it could be used for other use-cases. In that remove/add and clear would possibly mess up the list maintained as the bond.
> We use it for example to "directed advertisement" as a workaround since android has problem with actual directed advertisement.
> @jhe Given the CONFIG_BT_KEY_OVERWRITE_OLDEST There is something that I have seen for a while might be useful and that is a bond_deleted callback. As there is a couple of places where the stack clears the bond automatically. And it might be necessary for the application to have a way to sync it's own bond information, like for example the whitelist.
> jhe 2:29 PM
> @Joakim Andersson sure, that’d make sense
> Joakim Andersson 2:33 PM
> @Mattia Would it perhaps be enough to use bt_bond_foreach and a bt_bond_removed callback to manage the whitelist in the application? I'm sceptical about putting the whitelist policy in the stack as it can have many different use-cases.
> Mattia 2:34 PM
> @Joakim Andersson I could clear the whitelist upon a succesfull new bond and then re-add all bonded devices using bt_foreach_bond() API to the whitelist
> Joakim Andersson 2:34 PM
> Altough whitelisting bonded devices makes a lot of sense, it could potentially be cleared or entries removed accidentally by the app.
> @Mattia That could work too. But I think the bond_deleted callback is needed for other use-cases so I think I will add it anyway.
> Mattia 2:44 PM
> And use that same function on boot and that should ensure my whitelist / bonds are synchronized
> Joakim Andersson 2:47 PM
> @jhe Using proper bt_conn_ref when doing the bt_conn_write_without_response seems to fix the issue on reconnect where we don't have a conn context for the central.
> But I'm still seing that the peripheral stops sending write_commands after a while, and the throughput of the central seems to have been limited. So something is not right. Still investigating that.
> jhe 2:48 PM
> @Joakim Andersson perhaps the ATT “marking connection as disconnected” thing?
> Joakim Andersson 2:49 PM
> Not seeing that now.
> jhe 2:49 PM
> @Joakim Andersson did you fix the refcounting in both the central_hr and peripheral apps?
> Joakim Andersson 2:50 PM
> Yes.
> Mattia 2:50 PM
> @Joakim Andersson bond_deleted callback would be cleaner indeed so if that would be added I think my use-case is covered
> Joakim Andersson 2:50 PM
> @Mattia Great. I'll have to do it at a later time though. Could you create feature request issue and assign it to me?

### PR DESCRIPTION
**Pull request by joerchan**
Add bond_deleted callback so that the application can keep track
of when bond information is deleted in the stack.
Bond information can be deleted by the application through bt_unpair
or automatically by the stack in some cases, e.g when
CONFIG_BT_KEYS_OVERWRITE_OLDEST is enabled and the oldest bond
is overwritten.

Fixes: #20978

### CODE REVIEW

**Comment by joerchan** [comment]
I'm wondering if this should be gated behind Kconfig option, thoughts?

**Comment by joerchan** [comment]
CC: @mfiumara

**Review by KAGA164 — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@jhedberg do you want to take a look before we merge it?

**Comment by jhedberg** [comment]
> @jhedberg do you want to take a look before we merge it?

@carlescufi I just did, and it seems fine to me. Isn't there also some "bond management service" through which a remote device can inform us of bond removal, which might make sense to integrate with this (in a separate & later PR, of course).

**Review by jhedberg — APPROVED** [review]

**Comment by carlescufi** [comment]
> > @jhedberg do you want to take a look before we merge it?
> 
> @carlescufi I just did, and it seems fine to me. Isn't there also some "bond management service" through which a remote device can inform us of bond removal, which might make sense to integrate with this (in a separate & later PR, of course).

Yes, there is. Bond Management Service, and you are right that if someone implements it we should integrate it with this.

**Comment by carlescufi** [comment]
@joerchan you have actual CI failures.

**Comment by joerchan** [comment]
> @joerchan you have actual CI failures.

Thanks. I have added the needed ifdef guard.

**Comment by joerchan** [comment]
@carlescufi @jhedberg 

>  Isn't there also some "bond management service" through which a remote device can inform us of bond removal, which might make sense to integrate with this (in a separate & later PR, of course)

I'm not so sure those can be integrated in a way that makes sense, the callback is called after having disconnected and remove all the data. The Bond Management Service needs a connection to send the message to the peer.

Moving the bond_deleted callback to before disconnecting would be opposed to what this callback is trying to do, which is to give the application a notification that it can delete bond information from flash. Deleting it before the connection is disconnected could lead to issues since new messages could still be received.

There is only one case where the stack deletes the bond info on it's own, and that is when the OVERWRITE_OLDEST option is enabled. Should we consider having to support a future BMS and OVERWRITE_OLDEST feature as part of this PR?

**Comment by carlescufi** [comment]
> Moving the bond_deleted callback to before disconnecting would be opposed to what this callback is trying to do, which is to give the application a notification that it can delete bond information from flash. Deleting it before the connection is disconnected could lead to issues since new messages could still be received.

Why is this a problem? even if the bond is deleted the connection is already established, so why do you need the bond info anymore during a connection?

**Comment by joerchan** [comment]
> > Moving the bond_deleted callback to before disconnecting would be opposed to what this callback is trying to do, which is to give the application a notification that it can delete bond information from flash. Deleting it before the connection is disconnected could lead to issues since new messages could still be received.
> 
> Why is this a problem? even if the bond is deleted the connection is already established, so why do you need the bond info anymore during a connection?

I meant that the application deletes it part of the bond information could lead to issues when the connection is still active, and requests can still be received while deleting the bond information.

In any case the BMS messages should probably be verified to have been sent before disconnecting, which would mean that bond_deleted callback becomes blocking.

**Comment by joerchan** [comment]
I think BMS might have to be implemented as integrated in the stack, and not using the public API only. Which makes sense since bond management is already part of the host.

**Comment by carlescufi** [comment]
> I think BMS might have to be implemented as integrated in the stack, and not using the public API only. Which makes sense since bond management is already part of the host.

Agreed, so let's merge this and if we implement BMS as part of the core stack it will come with its own set of APIs.

**Pull request merged**
