### PR TITLE
doc: Added Percepio Tracealyzer guide on Tracing page

### PR DESCRIPTION
**Pull request by johankraft**
PREVIEW: https://builds.zephyrproject.io/zephyr/pr/76726/docs/services/tracing/index.html

The Tracing page did not cover the Percepio Tracealyzer support. Added a technical guide for Tracealyzer, with a screenshot of a Zephyr trace as example, similarly to how SEGGER SystemView is presented. Also added a "Tracing tools" subsection to group the three tools mentioned on the page for improved overview.

Signed-off-by: Johan Kraft <johan.kraft@percepio.com>

### CODE REVIEW

**Review by teburd — DISMISSED** [review]

**Comment by johankraft** [comment]
Force-pushed a fix for the Sphinx error (Title underline too short) and made the commit message shorter to pass compliance checks.

**Comment by kartben** [comment]
@johankraft This is great, thanks for your work on this. Will try to have a pass this week

**Review by nashif — DISMISSED** [review]

**Review by kartben — CHANGES_REQUESTED** [review]
Temp nak as I have a pending review

**Review by kartben — CHANGES_REQUESTED** [review]
woops, didn't realize I wouldn't be able to push my fixup commit directly to your branch as it's protected. Could you please apply the (cosmetic!) changes from this fixup commit?
https://github.com/kartben/zephyr/commit/2af9cd303d78b914236348493ee73ee886c84b2a

Thanks!

**Comment by johankraft** [comment]
@kartben Thanks, I have applied your fixes in a new commit.

**Review by kartben — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
