### PR TITLE
kconfiglib: Fix symlink issue, unclutter symbol strings, avoid redundant writes, misc.

### PR DESCRIPTION
**Pull request by ulfalizer**
Prompted by a symlink issue reported by @marc-hb. Also includes various other improvements.

Three commits:

```
kconfiglib: Unclutter symbol strings, avoid redundant writes, misc.

Update kconfiglib, menuconfig, and guiconfig to upstream revision
5c904f4549 to get various improvements and fixes in:

 - Marc Herbert found an issue involving symlinks, absolute paths,
   and rsource that could lead to files not being found. The root cause
   was relpath() assuming that symlink/../bar is the same as bar/, which
   isn't guaranteed.

   Fix it by handling paths in a simpler, more textual way.

 - Propagated dependencies from 'depends on' are now stripped from
   properties when symbols are printed (e.g. in information dialogs and
   generated documentation).

   The printed representation now also uses shorthands.

   Before:

     config A
             bool
             prompt "foo" if C && D
             default A if B && C && D
             depends on C && D

   After:

     config A
             bool "foo"
             default A if B
             depends on C && D

 - Before writing a configuration file or header, Kconfiglib now
   compares the previous contents of the file against the new contents,
   and skips the write if there's no change. This avoids updating the
   modification time, and can save work.

   A message like "No change to '.config'" is shown when there's no
   change.

 - .config now has '# end of <menu>' comments to make it easier to see
   where a menu ends. This was taken from a change to the C tools.

 - load_config() and write_(min_)config() now return a message that can
   be printed with print(kconf.load_config()). This allows messages to
   be reused in e.g. the configuration interfaces (nice now that there's
   also a "No change to..." string).
```

```
genrest: Mention that dependencies are only propagated to 'depends on'

A recent Kconfiglib change turns

    config A
            bool
            prompt "foo" if C && D
            default A if B && C && D
            depends on C && D

into

    config A
            bool "foo"
            default A if B
            depends on C && D

Where e.g. D might be from a surrounding menu/if.

Update the note at the end of symbol pages to clarify that only the
'depends on' includes propagated dependencies.

Piggyback some minor cleanup.
```

```
kconfig.py: Use messages returned by load_config() and write_config()

load_config() and write_config() now return a message to print. This
message also says whether the configuration was loaded (replace=True) or
merged (replace=False), and whether the new .config is different from
the old (for write_config()).

Print the returned messages and remove some old print()s.

Also switch to an improved warning control API (the old one is still
supported, but might as well).
```

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
I don't get any new errors when doing a from-scratch ``make htmldocs`` build with this PR, and a rebuild ``make htmldocs`` with no changes takes only 7 seconds instead of 8 minutes. LGTM.

**Comment by ulfalizer** [comment]
@dbkinder 
Heh, that's weird. Didn't think it'd have any (major) effect on doc building performance. Only difference I can think of is that it generates fewer links, due to the uncluttered symbols.

Wonder if there's something else going on.

**Comment by ulfalizer** [comment]
Hmm... seems about the same as before to me (15 seconds).

**Comment by marc-hb** [comment]
I've been using an earlier and shorter " quick fix" for the dot-dot .. symlink issue fixed by https://github.com/ulfalizer/Kconfiglib/commit/92791a3fe15bb2d5c1

Before testing this new fix, I obviously tried to reproduce the issue. I was literally banging my head against the wall failing to reproduce until I found... this: https://github.com/zephyrproject-rtos/mcumgr/pull/1

:-(

**Comment by marc-hb** [comment]
Just tested commit 4c9ac5757860e "kconfiglib: Fix symlink issue, unclutter symbol strings, avoid redundant writes, misc" in this PR and I confirm it resolves the particular symlink issue I just detailed in https://github.com/ulfalizer/Kconfiglib/commit/92791a3fe15bb2d5c1

I can't comment about all the rest.

**Comment by ulfalizer** [comment]
@carlescufi 
*ping*

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Thanks!

**Pull request merged**
