### PR TITLE
Fix i2s stm32

### PR DESCRIPTION
**Pull request by avisconti**
DMA operation in I2S STM32F4 driver is sometime failing due to overrun error (I'm testing it
in RX with PDM microphone, but it may fail in TX as well for underrun error).

The issue is that when the DMA operation is completed there is no much time to re-enable it for a new
transfer. For example, in the case of a PDM microphone clocked at 2MHz we only have 8us to re-
program the DMA to receive the new 16-bit sample. The dma_config() is too expensive in terms of 
time (I measured 5.1 us) and we are close to the limit. 
So, I implemented the dma_reload() for dma STM32F4 so that less time is required (I measured
1.1 us). This API is in fact the one that must be used to prepare for new DMA transfer.

### CODE REVIEW

**Comment by avisconti** [comment]
@Mani-Sadhasivam 
Can you review this PR and verify if it is breaking something at your end?
Thanks!

**Review by erwango — APPROVED** [review]

**Comment by avisconti** [comment]
@erwango 
Maybe I should put in the commit message the reference to this PR.
What do you think?

**Review by Mani-Sadhasivam — APPROVED** [review]
Changes look good to me and I also tested it on 96Boards STM32 Sensor mezzanine. Thanks!

**Comment by erwango** [comment]
@avisconti 

> Maybe I should put in the commit message the reference to this PR.
What do you think?

Can you say that again?

**Comment by avisconti** [comment]
> > Maybe I should put in the commit message the reference to this PR.
> > What do you think?
> 
> Can you say that again?

@erwango 
I already added in eb39f2b commit message a reference to #14618:
("Fix issue #141618")

**Comment by erwango** [comment]
ok, got it. Well we do this in general when issue is described in a real github issue.
For PR we don't put PR reference in commits. One reason is you can always come back to the PR from the commit when browsing with github (PR reference is available below commit messages).

**Comment by avisconti** [comment]
> ok, got it. Well we do this in general when issue is described in a real github issue.
> For PR we don't put PR reference in commits. One reason is you can always come back to the PR from the commit when browsing with github (PR reference is available below commit message

Yes, I understand.
I did it anyway because this is a FIX for an issue. And here you can (not always) find more description. In fact, I suggested @Mani-Sadhasivam to do the same in his PR.

**Pull request merged**
