### PR TITLE
runners: nrfjprog: workaround for multi-core hex files

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
The nrfjprog utility is not capable of flashing a hex file which
affects the flash memories of both coprocessors of the nRF53 family of
SoCs.

However, the user is capable of creating such a hex file using the
HEX_FILES_TO_MERGE build system variable.

An example use case is to build a bluetooth controller application for
the network core, then use the zephyr.hex file in that build directory
as the HEX_FILES_TO_MERGE argument for a separate Bluetooth
application build targeting the app core.

Work around this by detecting the situation and doing the right thing
by splitting the hex file back up again, even if thats a bit awkward.
Splitting the hex into app and network core components allows them to
be flashed separately. This is the only way we can get the job done
with nrfjprog.

This is arguably nicer since there's just one 'west flash' invocation.
At least in the use case named above, you wouldn't need to rebuild the
controller application very often, so this is a simpler user workflow.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@anangl this is a more upstream-friendly version of https://github.com/nrfconnect/sdk-zephyr/commit/09b7569da1bfa5f0d62429dd8dde95c34611a600 as discussed internally.

**Review by anangl — APPROVED** [review]
LGTM

**Review by tejlmand — CHANGES_REQUESTED** [review]
Being a bit curios here.
In which situation can this occur upstream ?

The `nrf5340dk_nrf5340_cpuapp` and `nrf5340dk_nrf5340_cpunet` are two different boards that targets each their own core.
Thus Zephyr always builds for one core or the other,  so how can this happen in the first place ?

Also, this relates to the discussion that was also raised here, in the context related to UICR, but with similarities in nature.
Namely that we want to split or program only portion of the hex file:
https://github.com/nrfconnect/sdk-zephyr/pull/322#issuecomment-645166940

Also there was an older PR with similar splitting that was closed here:
https://github.com/zephyrproject-rtos/zephyr/pull/21928

The two hex files for appcore and netcore are available before merging.
With this in mind, I think one of the following suggestions would be better generic solutions long term:
- Being able to create a list of hex files to use for the runner.
- Support multiple runners.yml. Then each runner.yml could independently state the target and hex to flash.
   Such solution would not be tied to a single SoC, but be generic and thus more scalable in general for boards with multiple SoCs, and multicore SoC.
- Improve nrfjprog to support flashing of only certain address range, for example: `nrfjprog --program <hex-file> --from-addr <addr> --to-addr <addr>`

**Comment by mbolivar-nordic** [comment]
> In which situation can this occur upstream ?

I explained this in detail in the commit log and in the source code comment.

> * Being able to create a list of hex files to use for the runner.

That is the logical effect of HEX_FILES_TO_MERGE.

**Comment by tejlmand** [comment]
> 
> 
> > In which situation can this occur upstream ?
> 
> I explained this in detail in the commit log and in the source code comment.
> 
> > * Being able to create a list of hex files to use for the runner.
> 
> That is the logical effect of HEX_FILES_TO_MERGE.



> 
> 
> > In which situation can this occur upstream ?
> 
> I explained this in detail in the commit log and in the source code comment.
> 

Except for the following:
- No CMake code in Zephyr or Zephyr modules uses `HEX_FILES_TO_MERGE` (or in NCS for that matter)
- The `HEX_FILES_TO_MERGE` uses a fixed name name `merged.hex` which is actually not so nice. Such output names should ideally be user configurable.
- The runners will not flash the `merged.hex` per default, even when using `HEX_FILES_TO_MERGE`.

Therefore I think that doing this in Zephyr, as currently proposed in this PR is only a partial solution.

In NCS, the actual hex to flash is handled by modifying the runners yaml properties, like this:
https://github.com/nrfconnect/sdk-nrf/blob/20e438ad68ff982985ec7334dcdd098586c580d5/cmake/partition_manager.cmake#L541-L550
```
get_target_property(runners_content runners_yaml_props_target yaml_contents)

string(REGEX REPLACE "hex_file:[^\n]*"
  "hex_file: ${merged_hex_to_flash}" new  ${runners_content})

set_property(
  TARGET         runners_yaml_props_target
  PROPERTY       yaml_contents
  ${new}
  )
```

so therefore, this is not something that happens in a vanilla Zephyr today.

What i'm asking, is that if we want to base this on `HEX_FILES_TO_MERGE` as you state in the commit message, I would like to see a proper integration of `HEX_FILES_TO_MERGE` and the flashing of that hex-file by the runner.
This will also be beneficial for this use-case:
https://github.com/zephyrproject-rtos/zephyr/pull/32490#pullrequestreview-596230831

where it was discussed offline that a more generic solution should be used, but a nRF53 specific solution was acceptable short term.

> > * Being able to create a list of hex files to use for the runner.
> 
> That is the logical effect of HEX_FILES_TO_MERGE.

No, this still doesn't provide a list of files to the runner itself.
It provides a single merged file to the runner, a file which then has to be split by the runner.

What I'm asking, as the possibility to provide a list of files to flash and / or list of runners to use (each domain to flash could require dedicated arguments, just like the nRF53, that requires different `--coprocessor` arguments.)

The principle of splitting merged hex files is not scalable among multiple socs / runners.
As example, this fix won't work if flashing using the JLink runner.

**Comment by mbolivar-nordic** [comment]
> Except for the following:
>     * No CMake code in Zephyr or Zephyr modules uses `HEX_FILES_TO_MERGE` (or in NCS for that matter)

That doesn't matter because it is publicly documented user visible functionality:

https://docs.zephyrproject.org/latest/application/index.html#application-cmakelists-txt

> The Cmake property HEX_FILES_TO_MERGE leverages the application configuration provided by Kconfig and CMake to let you merge externally built hex files with the hex file generated when building the Zephyr application.

The user really can make this happen in vanilla zephyr.

**Review by tejlmand — APPROVED** [review]
Discussed directly.

Would really like to see a more generic solution regarding the runners in future, as I believe this will happen more often with more and more multicore or multi-socs on boards happening.

But as this is very localized hack, this PR it's accepted, as-is.

**Pull request merged**
