### PR TITLE
Bluetooth: Mesh: Fix heartbeat subscription state handling

### PR DESCRIPTION
**Pull request by jhedberg**
PTS version 7.3.0 incorporates some errata which change the expected
behavior of the heartbeat subscription state. Update the code so that
the following tests pass successfully:

MESH/NODE/CFG/HBS/BV-01
MESH/NODE/CFG/HBS/BV-02
MESH/NODE/CFG/HBS/BV-03
MESH/NODE/CFG/HBS/BV-04

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
@kolodgrz please test this

**Comment by kolodgrz** [comment]
@jhedberg now it works alright.

1/4   MESH   MESH/NODE/CFG/HBS/BV-01-C   PASS            40.363             
2/4   MESH   MESH/NODE/CFG/HBS/BV-02-C   PASS            58.784                  
3/4   MESH   MESH/NODE/CFG/HBS/BV-03-C   PASS            59.222                  
4/4   MESH   MESH/NODE/CFG/HBS/BV-04-C   PASS            40.626

**Comment by jhedberg** [comment]
Thanks for testing @kolodgrz . @sjanc @Vudentz @carlescufi @cvinayak could I get a review so we can get this merged? Thanks.

**Review by cvinayak — APPROVED** [review]
LGTM

**Pull request merged**
