### PR TITLE
arch: riscv & arm64: print symbol name in stack trace

### PR DESCRIPTION
**Pull request by ycsin**
See each commit message for details

https://builds.zephyrproject.io/zephyr/pr/72973/docs/releases/release-notes-3.7.html

# Standing issue

I was expecting the same can be applied to x86, but `qemu_x86` crashes when I try to use something from the symtab.

# Testing

## RISCV

```
west build -p auto -b qemu_riscv32 zephyr/tests/arch/common/stack_unwind \
    -T arch.common.stack_unwind.riscv_sp \
    -t run -- \
    -DCONFIG_EXCEPTION_STACK_TRACE_SYMTAB=y
```

```
*** Booting Zephyr OS build v3.6.0-4306-g9c7c06afd3b6 ***
Hello World! qemu_riscv32
1: func1
2: func2
3: func1
4: func2
5: func1
6: func2
E:      a0: 00000003    t0: 00000000
E:      a1: 800081c3    t1: 0000004c
E:      a2: 0000000a    t2: 00000000
E:      a3: 8000a138    t3: 0000002a
E:      a4: 00000000    t4: 0000002e
E:      a5: 00000004    t5: 0000007f
E:      a6: 00000068    t6: 00000010
E:      a7: 0000006a
E:      sp: 8000bb80
E:      ra: 80000786
E:    mepc: 80000794 [func2+0x1e]
E: mstatus: 00021880
E: 
E:      s0: 8000a31c    s6: 00000000
E:      s1: 800024f2    s7: 00000000
E:      s2: 00000000    s8: 00000000
E:      s3: 00000000    s9: 00000000
E:      s4: 00000000   s10: 00000000
E:      s5: 00000000   s11: 00000000
E: 
E: call trace:
E:       0: sp: 8000bb8c   ra: 800007c6 [func1+0x24]
E:       1: sp: 8000bb9c   ra: 8000079a [func2+0x32]
E:       2: sp: 8000bbac   ra: 800007c6 [func1+0x24]
E:       3: sp: 8000bbbc   ra: 8000079a [func2+0x32]
E:       4: sp: 8000bbcc   ra: 800007c6 [func1+0x24]
E:       5: sp: 8000bbdc   ra: 800007ea [main+0x1c]
E:       6: sp: 8000bbe4   ra: 800024f2 [bg_thread_main+0x0]
E:       7: sp: 8000bbec   ra: 80002512 [bg_thread_main+0x20]
E:       8: sp: 8000bbf0   ra: 800024f2 [bg_thread_main+0x0]
E:       9: sp: 8000bbfc   ra: 80000bc6 [z_thread_entry+0x26]
E: 
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x8000a138 (main)
E: Halting system
```

## ARM64

```
west build -p auto -b qemu_cortex_a53 zephyr/tests/arch/common/stack_unwind \
    -T arch.common.stack_unwind.arm64 \
    -t run -- \
    -DCONFIG_SYMTAB=y
```

```
*** Booting Zephyr OS build v3.6.0-4076-g98b58e2aef93 ***
Hello World! qemu_cortex_a53
1: func1
2: func2
3: func1
4: func2
5: func1
6: func2
E: ELR_ELn: 0x0000000040001270
E: ESR_ELn: 0x0000000056000002
E:   EC:  0x15 (Unknown)
E:   IL:  0x1
E:   ISS: 0x2
E: TPIDRRO: 0x010000004001aa08
E: x0:  0x0000000000000009  x1:  0x000000000000000a
E: x2:  0x00000000407ff000  x3:  0x0000000000000090
E: x4:  0x0000000000000000  x5:  0x000000000000002d
E: x6:  0x0000000000000000  x7:  0x0000000000000006
E: x8:  0x0000000000000003  x9:  0x0000000000000000
E: x10: 0x0000000000000000  x11: 0x0000000000000000
E: x12: 0x0000000000000000  x13: 0x0000000000000000
E: x14: 0x0000000000000000  x15: 0x0000000000000000
E: x16: 0x0000000000000000  x17: 0x0000000000000000
E: x18: 0x0000000000000000  lr:  0x0000000040001260
E: 
E: backtrace  0: fp: 0x000000004005daa0 lr: 0x00000000400012b4 [func1+48]
E: backtrace  1: fp: 0x000000004005dac0 lr: 0x0000000040001278 [func2+64]
E: backtrace  2: fp: 0x000000004005dae0 lr: 0x00000000400012b4 [func1+48]
E: backtrace  3: fp: 0x000000004005db00 lr: 0x0000000040001278 [func2+64]
E: backtrace  4: fp: 0x000000004005db20 lr: 0x00000000400012b4 [func1+48]
E: backtrace  5: fp: 0x000000004005db40 lr: 0x00000000400012e4 [main+36]
E: backtrace  6: fp: 0x000000004005db60 lr: 0x00000000400058a4 [bg_thread_main+56]
E: backtrace  7: fp: 0x000000004005db70 lr: 0x0000000040001734 [z_thread_entry+72]
E: backtrace  8: fp: 0x000000004005db80 lr: 0x0000000000000000 [?+0]
E: 
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x4001a330 (main)
E: Halting system
```

# TODO

- [x] https://github.com/zephyrproject-rtos/zephyr/pull/72728#discussion_r1604727976

### CODE REVIEW

**Review by fkokosinski — DISMISSED** [review]
RISC-V changes from 6a32c2cd35b1374384d3430cb8ec8eff3989d623 LGTM

**Comment by ycsin** [comment]
Polished a few things, should be final now.

**Review by cfriedt — DISMISSED** [review]

**Review by npitre — DISMISSED** [review]
I have a few ideas to shrink the ROM footprint but that may come later

**Comment by ycsin** [comment]
Rebased to fix merge conflict

**Review by npitre — APPROVED** [review]

**Comment by ycsin** [comment]
Failed CI passed locally:

```
west build -b qemu_riscv32_smp -p auto -t run zephyr/tests/kernel/spinlock -T kernel.multiprocessing.spinlock_fairness
```

**Review by cfriedt — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Pull request merged**
