### PR TITLE
[Backport v3.0-branch] Fix the broadcast ipi issue when Zephyr SMP runs on Xen

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 48cce661d5d1085f1cb0fa121f866ecdaac400c0~3..48cce661d5d1085f1cb0fa121f866ecdaac400c0 from #43576

### CODE REVIEW

**Review by stephanosio — APPROVED** [review]

**Review by povergoing — APPROVED** [review]

**Review by stephanosio — CHANGES_REQUESTED** [review]
There is a build failure.

**Comment by povergoing** [comment]
> There is a build failure.

What should I do?

**Comment by povergoing** [comment]
Oh, the last commit seems redundant. This failure will be fixed when https://github.com/zephyrproject-rtos/zephyr/pull/45452 merged, so I will remove it when 45452 merged.

**Review by stephanosio — APPROVED** [review]

**Comment by povergoing** [comment]
@dkalowsk Sorry to bother you. I think there is one I forgot to notify you. Would you like to take a look?

**Review by dkalowsk — APPROVED** [review]

**Pull request merged**
