### PR TITLE
soc : arm : microchip_mec Move custom busy wait config to MEC1501 SoC

### LINKED ISSUE #18880: boards: mec15xxevb_assy6853: consider moving ARCH_HAS_CUSTOM_BUSY_WAIT to SoC definition
**Describe the bug**
There has been a suggestion in #18318 to consider moving ARCH_HAS_CUSTOM_BUSY_WAIT definition/selection in the SoC definition instead of board definition.

This makes sense since this requirement appears to be SoC specific.

### PR DESCRIPTION
**Pull request by scottwcpg**
Configuration item custom busy wait is required for all MEC1501 series
if its RTOS timer driver is enabled. We moved the configuration logic
from board level to MEC1501 SoC level.

Signed-off-by: Scott Worley <scott.worley@microchip.com>

Closes #18880

### CODE REVIEW

**Comment by scottwcpg** [comment]
This PR addresses issue #18880 boards: mec15xxevb_assy6853: consider moving ARCH_HAS_CUSTOM_BUSY_WAIT to SoC definition.

**Review by albertofloyd — APPROVED** [review]

**Review by franciscomunoz — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
It feels like you might be moving too much to the SoC.  For example is !RTOS_TIMER seems like SYS_CLOCK_HW_CYCLES_PER_SEC would be a board setting.

**Comment by scottwcpg** [comment]
Hi,
I pushed changes to keep frequency selection at the board level and only timer selection defaults are in SoC level.

**Review by galak — APPROVED** [review]

**Comment by scottwcpg** [comment]
Rebase to fix GitLint issue.

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
