### PR TITLE
dts: Move SoC devicetree includes under a vendor directory

### PR DESCRIPTION
**Pull request by MaureenHelm**
Cleans up SoC devicetree include file locations to follow the convention
of dts/\<arch\>/\<vendor\>/

Signed-off-by: Maureen Helm <maureen.helm@intel.com>

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Review by enjiamai — DISMISSED** [review]

**Comment by carlocaione** [comment]
Can I suggest also:

`dts/arm64/fvp-aemv8r` -> `dts/arm64/fvp/...`
`dts/arm64/qemu-virt` -> `dts/arm64/qemu/...`

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by ruuddw — CHANGES_REQUESTED** [review]
There's one more reference to emsk.dtsi in samples\boards\arc_secure_services\em_starterkit_em7d_normal.dts, could you please add 'synopsys' in the path there as well? Thanks!

**Review by carlocaione — DISMISSED** [review]

**Review by dcpleung — DISMISSED** [review]

**Review by enjiamai — DISMISSED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by evgeniy-paltsev — DISMISSED** [review]

**Review by ruuddw — DISMISSED** [review]

**Comment by mevalver** [comment]
Is there any other pending action from my side?

**Comment by nashif** [comment]
rebase

**Review by teburd — DISMISSED** [review]

**Review by povergoing — DISMISSED** [review]

**Comment by povergoing** [comment]
> Can I suggest also:
> 
> `dts/arm64/fvp-aemv8r` -> `dts/arm64/fvp/...` `dts/arm64/qemu-virt` -> `dts/arm64/qemu/...`

Do we have a plan to also clean up the `board/arm/`,  too many boards...

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by MaureenHelm** [comment]
Rebased and fixed merge conflicts

**Review by henrikbrixandersen — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
