### PR TITLE
Bluetooth: l2cap_br: Support Multi-Command Packet

### PR DESCRIPTION
**Pull request by lylezhu2012**
Improve L2CAP BR to handle more than one signalling command in one receiving L2CAP packet.

### CODE REVIEW

**Comment by jhedberg** [comment]
Even if the spec allows this, have you actually seen any devices using it in practice?

**Comment by lylezhu2012** [comment]
> Even if the spec allows this, have you actually seen any devices using it in practice?

There is a ICS item L2CAP 2/1 for this feautre.

**Comment by jhedberg** [comment]
> > Even if the spec allows this, have you actually seen any devices using it in practice?
> 
> There is a ICS item L2CAP 2/1 for this feautre.

Is it mandatory or optional?

**Comment by jhedberg** [comment]
Btw, I'm not necessarily opposed to this, but I think you can do it cleaner (more readable) by factoring out the handling of one command to a dedicated function and then do the fetching of one command from the buffer in a separate function that calls the other one.

**Comment by lylezhu2012** [comment]
> > > Even if the spec allows this, have you actually seen any devices using it in practice?
> > 
> > 
> > There is a ICS item L2CAP 2/1 for this feautre.
> 
> Is it mandatory or optional?

L2CAP 2/1: Mandatory IF L2CAP 0/1 "BR/EDR" OR L2CAP 0/3 "BR/EDR/LE", otherwise Excluded.

**Review by jhedberg — APPROVED** [review]
Looks good now. Thanks!

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
