### PR TITLE
boards: st: stm32h745i_disco: fix CAN phy devicetree representation

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
On this board, the CAN transceivers are not GPIO controlled, but passive, and should not be represented by the "can-transceiver-gpio" compatible (as this leads to driver compilation warnings due to missing GPIO properties).

Fixes: c8faa1e3809854e83bc7abe9d33737a5047d9125

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
This is causing compilation warnings in CI as seen in https://github.com/zephyrproject-rtos/zephyr/pull/71857

**Review by erwango — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Comment by erwango** [comment]
> This is causing compilation warnings in CI as seen in https://github.com/zephyrproject-rtos/zephyr/pull/71857

Thanks for the fix. It's really frustrating to have these CI issues detected post-merge

**Comment by aescolar** [comment]
@henrikbrixandersen the fixes line in the PR description needs fixing :)

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen the fixes line in the PR description points to a commit, not a GH issue

I know?

**Comment by henrikbrixandersen** [comment]
> Thanks for the fix. It's really frustrating to have these CI issues detected post-merge

If "can" was listed as supported in `boards/st/stm32h745i_disco/stm32h745i_disco_stm32h745xx_m7.yaml` it would have been caught in the initial PR.

**Review by alexanderwachter — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by str4t0m — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Pull request merged**
