### PR TITLE
ARM/ARM64 split - part 2 - AArch32

### PR DESCRIPTION
**Pull request by carlocaione**
Part 2 of the split, only related to AArch32.

The only thing to notice in addition to the part 1 is that now the aarch32 include directories are shipping some header files printing a warning message in case the old path is still used.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Can you split out the moving of headers like exc.h into a separate commit/PR?  And keep this just to the removal of `aarch32`

**Review by galak — COMMENTED** [review]
Can the second commit just be the "header guards" changes.  I'd merge the other changes into the first commit.

**Review by galak — COMMENTED** [review]
I think the there should be a commit to address the low hanging fruit issues reported by checkpatch.  Things like:

* WARNING:BLOCK_COMMENT_STYLE: Block comments should align the * on each line
* WARNING:LONG_LINE: line length of 101 exceeds 100 columns
* WARNING:BLOCK_COMMENT_STYLE: Block comments use a trailing */ on a separate line
* WARNING:LINE_CONTINUATIONS: Avoid line continuations in quoted strings
etc.

that are pretty trivial to address.

**Comment by carlocaione** [comment]
@galak

> Can you split out the moving of headers like exc.h into a separate commit/PR? And keep this just to the removal of `aarch32`

Not sure I understand what you mean. If I remove the `aarch32` I'm basically moving the location of the header files.

> Can the second commit just be the "header guards" changes. I'd merge the other changes into the first commit.

ok

> I think the there should be a commit to address the low hanging fruit issues reported by checkpatch

That's material for another PR. I think it's better for now keep the line diff to the minimum for this PR, otherwise it gets more confusing than this already is.

**Comment by galak** [comment]
> > Can you split out the moving of headers like exc.h into a separate commit/PR? And keep this just to the removal of `aarch32`
> 
> Not sure I understand what you mean. If I remove the `aarch32` I'm basically moving the location of the header files.

Not sure if its technically feasible, but there are changes in `arch/arm/include/aarch32/cortex_a_r/exc.h` to use `cortex_a_r/exc.h`.  I was asking if that change can be a separate commit/PR.

**Comment by galak** [comment]
> > I think the there should be a commit to address the low hanging fruit issues reported by checkpatch
> 
> That's material for another PR. I think it's better for now keep the line diff to the minimum for this PR, otherwise it gets more confusing than this already is.

I'm ok with that, only fear is losing the issues that get reported.

**Comment by carlocaione** [comment]
> Not sure if its technically feasible, but there are changes in `arch/arm/include/aarch32/cortex_a_r/exc.h` to use `cortex_a_r/exc.h`. I was asking if that change can be a separate commit/PR.

As usual it depends how much we care about bisectability. If I move that change to a separate commit the bisection of any code using the old include location will be broken (some out-of-tree code I suppose).

> I'm ok with that, only fear is losing the issues that get reported.

I'll take care to open an issue with the checkpatch report.

**Comment by carlocaione** [comment]
> As usual it depends how much we care about bisectability. If I move that change to a separate commit the bisection of any code using the old include location will be broken (some out-of-tree code I suppose).

@ioannisg what's your take on this?

**Review by npitre — APPROVED** [review]
Perhaps something to consider. In MAINTAINERS.yml:

```
     files:
-        - arch/arm/aarch32/
+        - arch/arm/
         - arch/arm/common/
         - arch/arm/offsets/
```

I guess that `arch/arm/common/` and `arch/arm/offsets/` are now redundant.
Similarly elsewhere too.

**Comment by ioannisg** [comment]
> > As usual it depends how much we care about bisectability. If I move that change to a separate commit the bisection of any code using the old include location will be broken (some out-of-tree code I suppose).
> 
> @ioannisg what's your take on this?

I would favor diff separation into standalone commits, for ease of reviewing.

**Review by ioannisg — APPROVED** [review]

**Pull request closed without merging**
