### PR TITLE
drivers: gpio_emul: Fire callbacks for pins configured as input + output

### PR DESCRIPTION
**Pull request by rekanorman**
Currently, if a GPIO is configured as both input and output, callbacks will not be fired when the output value changes because input pins are masked out. This means the output-wiring mechanism does not work as expected for these pins.

Change it to fire callbacks for all output pins instead. Only fire callbacks if they have not already been fired when triggering interrupt events, to prevent callbacks being fired twice for a single state change.

### CODE REVIEW

**Comment by rekanorman** [comment]
This causes the tests in tests/drivers/gpio/gpio_api_1pin/src/test_pin_interrupt.c to fail. They configure the pin as input + output, and check interrupts are only triggered when expected (e.g. on rising edge only). But with this change interrupts are triggered unconditionally every time the output value changes.

I'm not sure what the best fix is. It seems like a limitation of using the same callback mechanism to mock both interrupts and output-wiring. Ideally gpio_emul would be able to fire only interrupt callbacks or only output-wiring callbacks depending on the situation, but I don't think this is possible.

**Comment by cfriedt** [comment]
@rekanorman - in general, the change looks ok. Are you able to ensure all test cases pass with this change?

The bluetooth host / scancode issue is unrelated, so it shouldn't block this PR, but I would suggest rebasing prior to pushing again, in case someone else has fixed it already in `main`.

**Comment by fabiobaltieri** [comment]
> They configure the pin as input + output, and check interrupts are only triggered when expected

Is the test misconfigured or the change making it misbehave? The test is setting an edge with one of the `GPIO_INT_EDGE_...` flags, if those are failing it sounds like the emulation driver is not emulating those correctly (or the test is wrong I guess)

**Comment by rekanorman** [comment]
I think the test is valid, and the change causes incorrect behaviour in the following situation:
* The pin is configured as input + output
* It has an interrupt configured, e.g. GPIO_INT_EDGE_RISING
* A falling edge occurs, e.g. via gpio_pin_set() -> ... -> gpio_emul_port_clear_bits_raw()
* The previous behaviour of gpio_emul_port_clear_bits_raw() was:
	* gpio_emul_pend_interrupt() - doesn’t fire callbacks because it’s not a rising edge
	* gpio_fire_callbacks() - doesn’t fire callbacks because input pins are masked out
* The behaviour with this change is:
	* gpio_emul_pend_interrupt() - doesn’t fire callbacks because it’s not a rising edge
	* gpio_fire_callbacks() - does fire callbacks since it’s an output pin
	* So the interrupt callback is fired, which is wrong since it’s not a rising edge

The problem is that firing callbacks is all-or-nothing. I think what we want is to fire output-wiring callbacks only in some cases (e.g. the one above), and interrupt callbacks only in others. But I'm not sure how to implement something like this.

**Comment by fabiobaltieri** [comment]
> The problem is that firing callbacks is all-or-nothing. I think what we want is to fire output-wiring callbacks only in some cases (e.g. the one above), and interrupt callbacks only in others. But I'm not sure how to implement something like this.

I see, that's a bit confusing though, why would there be an unconditional path that calls `gpio_fire_callbacks` regardless of the pin interrupt configuration? That does not feel right to me. @cfriedt are you familiar with this part of the driver?

**Comment by cfriedt** [comment]
> > They configure the pin as input + output, and check interrupts are only triggered when expected
> 
> Is the test misconfigured or the change making it misbehave? The test is setting an edge with one of the `GPIO_INT_EDGE_...` flags, if those are failing

I haven't looked into it in a long time. Is the emulation driver not running regularly in CI for those tests? It would need to be run regularly in order to properly catch regressions. 

It was added in c313828eaf1bf336fa9686d97186d2bd0dc281df and it was definitely OK at that point.

> it sounds like the emulation driver is not emulating those correctly (or the test is wrong I guess)

I would guess, since new functionality is being added here, there might be changes required in the test as well, to account for the desired emulation.

> This causes the tests in tests/drivers/gpio/gpio_api_1pin/src/test_pin_interrupt.c to fail. They configure the pin as input + output, and check interrupts are only triggered when expected (e.g. on rising edge only). But with this change interrupts are triggered unconditionally every time the output value changes.

A quick grep shows that no specialized behaviour exists for the emulation driver currently under `tests/drivers/gpio/gpio_api_1pin/`.

It's possible that if the behaviour of the driver is being changed, the desired emulation behaviour might need to change in this test as well. 

> I'm not sure what the best fix is. It seems like a limitation of using the same callback mechanism to mock both interrupts and output-wiring.

That's kind of a design feature. It helps to ensure that that behavioural logic lives in one place and reduces the need for additional API calls. Feel free to make a separate PR if you would like to modify that though.

> Ideally gpio_emul would be able to fire only interrupt callbacks or only output-wiring callbacks depending on the situation, but I don't think this is possible.

It's likely quite possible. That new functionality might need to be added in this PR though, if that is what is required.

**Comment by rekanorman** [comment]
> why would there be an unconditional path that calls gpio_fire_callbacks regardless of the pin interrupt configuration?

Before this change, the code was:
```
	/* for output-wiring, so the user can take action based on output */
	gpio_fire_callbacks(&drv_data->callbacks, port, pins & ~get_input_pins(port));
```

I.e. input pins were masked out, so there was no issue with unexpected interrupts (but output-wiring callbacks were never called for input pins, which is the issue I'm trying to fix). So the issue with unexpected interrupts was introduced by this change, and I understand that it needs to be fixed before submitting this.

I'm just not sure what the best fix is. It seems like the driver needs some way to distinguish between interrupt callbacks and output-wiring callbacks, so it can fire only one or the other depending on the situation. But I'm not sure how to implement this using the gpio callback mechanism. E.g. I can't see a way to attach metadata like this to a callback. But I'm very new to zephyr, so it's possible I'm missing some obvious solution.

**Comment by fabiobaltieri** [comment]
There's some logic I'm missing entirely from the emulated driver: a normal hardware gpio configured as output would normally just read its own output as input and fire up the interrupt regardless of the input configuration, but only if the interrupt functionality is enabled, so on the emulated driver I would expect the same code path for the interrupt logic on both setting a output value or setting an emulated input value, and that would involve calling `gpio_emul_gen_interrupt_bits` to mask out the pins that are not configured. So why there are `gpio_fire_callbacks` calls directly in any other functions? I think that those have to go.

I suppose that the problem is that I don't understand the `for output-wiring, so the user can take action based on output` comment, is that meant to be a testing only functionality built on top of the interrupt callback system?

**Comment by rekanorman** [comment]
> is that meant to be a testing only functionality built on top of the interrupt callback system?

Yes. It can be used to emulate things like two pins being wired together in hardware. There's an example with a comment in tests/drivers/gpio/gpio_basic_api/src/gpio_emul_callback.c.

It's meant to be completely independent from interrupts. I.e. you can register an output-wiring callback regardless of whether the pin has an interrupt. But it reuses the same callback mechanism.

**Comment by fabiobaltieri** [comment]
> It's meant to be completely independent from interrupts. I.e. you can register an output-wiring callback regardless of whether the pin has an interrupt. But it reuses the same callback mechanism.

Ok, it feels to me like that should be a test driver specific callback independent from the interrupt one, would that make sense?

**Comment by rekanorman** [comment]
Yeah, I guess so. I wasn't sure whether the existing callback mechanism is only meant to be used for interrupts, or meant to be generic. I can't see anything in the comments in gpio.h which says it should only be used for interrupts. But skimming through a few non-emulated gpio drivers it looks like they all fire callbacks on interrupts only, so at least by convention it's being used that way.

**Comment by fabiobaltieri** [comment]
Yeah the driver seems to be somewhat vague with the association of "callback" and "interrupt", never noticed it before and somewhat funny, what else would a GPIO controller use a callback for... :-)

So it looks like the emulated driver could use some refactoring.

**Comment by rekanorman** [comment]
Yeah. Realistically it might be a while before I have time to work on it. Should I just keep this open until then?

And thanks for your help :)

**Comment by fabiobaltieri** [comment]
> Yeah. Realistically it might be a while before I have time to work on it. Should I just keep this open until then?

Sure, whatever works for you.

**Pull request closed without merging**
