### PR TITLE
Improve video sw generator

### PR DESCRIPTION
**Pull request by ngphibang**
This PR add support for XRGB32 format to the video sw generator as this is useful to test camera and display pipeline on i.MX RT11XX. It also contains some minor fixes.

The first commit (which adds XRGB fourcc) is part of [another PR](https://github.com/zephyrproject-rtos/zephyr/pull/69810) and could be dropped if that PR is merged first :

> [include: video: Add XRGB32 pixel format](https://github.com/zephyrproject-rtos/zephyr/commit/8465fec6f4ed53ef6b85d7501c1aaadde5afbae5)

### CODE REVIEW

**Comment by ngphibang** [comment]
Hi @loicpoulain ,
Could you help to review this one ?
Thanks

**Review by loicpoulain — DISMISSED** [review]
neat!

**Comment by ngphibang** [comment]
@loicpoulain I made a mistake in the commit "[drivers: video: sw_generator: Fix set_format](https://github.com/zephyrproject-rtos/zephyr/pull/69817/commits/10198d1f8978adf55222c774fc49f78e9c8cb8ee)

Instead of moving `static const struct video_format_cap fmts[]`, I dupplicated it. I 've just pushed force to fix this.
Could you please approve the PR again ? Sorry for this !

**Review by loicpoulain — APPROVED** [review]

**Comment by dleach02** [comment]
Added @loicpoulain as the assignee as he is the maintainer of the drivers\video 

@danieldegrasse can you give this a review?

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
