### PR TITLE
jlink: custom flashing support

### PR DESCRIPTION
**Pull request by jcpi-q**
Allows to use a custom flashing script with jlink runners.

### CODE REVIEW

**Comment by pdgendt** [comment]
Requires a rebase

**Review by pdgendt — DISMISSED** [review]

**Comment by kartben** [comment]
@jcpi-q can you please rebase as there is a merge conflict now? Thanks!

**Review by kartben — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by zeonchew** [comment]
Hi @jcpi-q 

Would like to check with you whether it is intended that after refactoring into `run_flash_cmd()`, that the construction of cmd variable goes into the condition `if self.supports_loader and self.loader:` instead of staying outside of the if statement as it was?

https://github.com/jcpi-q/zephyr/blob/e2a32d8b0ca596afeae48739c43817f693720a88/scripts/west_commands/runners/jlink.py#L413-L431

`west flash` command stops to works at my side because variable `cmd` is not initialized, as the loader option is not used. 
Hence causing exception to the thrown at 

https://github.com/jcpi-q/zephyr/blob/e2a32d8b0ca596afeae48739c43817f693720a88/scripts/west_commands/runners/jlink.py#L438

**Comment by kartben** [comment]
> Hi @jcpi-q 
> 
> Would like to check with you whether it is intended that after refactoring into `run_flash_cmd()`, that the construction of cmd variable goes into the condition `if self.supports_loader and self.loader:` instead of staying outside of the if statement as it was?
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/f90ce01d4ac507c99e3cddcaba6fd13239b06034/scripts/west_commands/runners/jlink.py#L413-L438
> 
> `west flash` command stops to works at my side because variable `cmd` is not initialized, as the loader option is not used. 
> Hence causing exception to the thrown at the execution line at L438: 
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/f90ce01d4ac507c99e3cddcaba6fd13239b06034/scripts/west_commands/runners/jlink.py#L438
> 

#82005

@jcpi-q @pdgendt  can you help line up a (hot)fix please? Or we can just revert for now.

**Pull request merged**
