### PR TITLE
Add a web3-iot-sdk application sample

### PR DESCRIPTION
**Pull request by Tide00**
Add a web3-iot-sdk application example

Signed-off-by: Tide00 <taegukusa@gmail.com>

### CODE REVIEW

**Comment by nordicjm** [comment]
Please read https://docs.zephyrproject.org/latest/contribute/external.html module addition requests must be submitted as an issue with a TSC label and full details on what it is, why it is needed, license information, etc.

**Review by gmarull — CHANGES_REQUESTED** [review]
please no web3/crypto/NFT scams in tree

**Review by jfischer-no — CHANGES_REQUESTED** [review]
No to scam in Zephyr Project.

https://web3isgoinggreat.com/

**Comment by kartben** [comment]
Sorry @Tide00  but this PR doesn't even seem to make any sense. Apologies if this will come across as harsh, but closing for now.

Feel free to reopen with more details on what you are trying to accomplish (none can be found in the PR description, commit message, or sample readme). The code in this PR is pulling stuff that's not even a Zephyr module only to not even do anything useful with it, so it's a bit confusing.

**Comment by Tide00** [comment]
> No to scam in Zephyr Project.
> 
> https://web3isgoinggreat.com/

Sorry to make you feel scammed, just trying to build a bridge between embedded devices and web3. But that really isn't reflected in my sample, so I'll rebuild it.

**Pull request closed without merging**
