### PR TITLE
[Backport v3.4-branch] drivers: spi: mcux_flexcomm: fix chip select bug w/ intermediate dma …

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 2a4acb2c4232f89890456527e0f62167d91ec6d8
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/59575

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
@mjchen0 could you look into the CI fail here?

**Comment by fabiobaltieri** [comment]
NVM I fixed that, can you review?

**Review by mjchen0 — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by jgl-meta — APPROVED** [review]
This looks okay to me.

**Comment by jgl-meta** [comment]
@dleach02 since you are the task owner, I will leave you in charge of merging this if you are okay with it.

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
@nashif does the release manager for 3.4 handle the merges of these backports?

**Comment by jgl-meta** [comment]
> @nashif does the release manager for 3.4 handle the merges of these backports?

@dleach02 I had been handling everything that the task owner had signed off on. I thought that is what I had been told was the correct thing to do.

**Comment by nashif** [comment]
> @nashif does the release manager for 3.4 handle the merges of these backports?

yes

**Pull request merged**
