### PR TITLE
net: buf: buffer recovery function

### PR DESCRIPTION
**Pull request by JordanYates**
Implements a method to recover a net_buf pointer from a data pointer
  that points to the memory held by an active net_buf.

  net_buf's are a natural solution when working with asynchronous API's to
  ensure that memory is valid for the duration of the call, calling
  `net_buf_unref` inside a done callback to free the memory. However many
  APIs only provide the raw data pointer in their done callbacks, making
  it difficult to recover the net_buf to call `net_buf_unref`.

  An example of how this can be used:
  ```
  NET_BUF_POOL_DEFINE(pool, 5, 100, 0, NULL);

  void send_uart_async(void *mem, size_t len)
  {
    struct net_buf *buf = net_buf_alloc(&pool, K_FOREVER);
    net_buf_add_mem(buf, mem, len);
    uart_tx(uart_driver, buf->data, buf->len, SYS_FOREVER_MS);
  }

  void cb(const struct device *dev, struct uart_event *evt, void *ud)
  {
    struct net_buf *buf;
    if (evt->type == UART_TX_DONE) {
      buf = net_buf_recover_from_ptr(&pool, evt->data.tx.buf);
      if (buf) {
        net_buf_unref(buf);
      }
    }
  }
  ```

### CODE REVIEW

**Comment by jukkar** [comment]
As the `net_buf` can be part of chain of buffers, I just wonder how this could work out if we unref a buf but the previous buffer still points to the freed one.

**Comment by jhedberg** [comment]
There is also the issue that net_buf's (as long as the underlying pool supports it) can be cloned, so that two net_buf structs point at the same data.

**Comment by jhedberg** [comment]
@JordanYates for the example you quoted, I think it'd be more natural to pass a pointer to the net_buf (or a pointer to a more high-level context part of which would be the net_buf pointer) e.g. through the `void *ud` parameter of the callback.

**Comment by JordanYates** [comment]
> As the net_buf can be part of chain of buffers, I just wonder how this could work out if we unref a buf but the previous buffer still points to the freed one.

Good point. The target of this PR is API's that just take raw memory pointers, so chains don't really make sense there.
That said, introducing an API that only works for some situations is probably not the best idea.
I have been toying around with the idea of a seperate "referenced buffer" API for a while now, which `net_buf` could then extend for its chaining operations etc. The proposed function would be more coherent in that context.

**Comment by JordanYates** [comment]
> @JordanYates for the example you quoted, I think it'd be more natural to pass a pointer to the net_buf (or a pointer to a more high-level context part of which would be the net_buf pointer) e.g. through the `void *ud` parameter of the callback.

The problem is where in `send_uart_async` are you setting the pointer to the `net_buf`? If you do it before the call you will corrupt any currently running transmission (As `uart_tx` can fail), if you do it after you are not guaranteed to set the variable before the callback runs.

**Pull request closed without merging**
