### PR TITLE
tests: net: stop whitelisting

### PR DESCRIPTION
**Pull request by jukkar**
This is the same as #15836 but merge conflicts solved.

This is bad practice and may conceal issues on platforms
not in the whitelist.

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]
We really need to move forward with this, because with older broken boards fixed, there's now new broken boards have been added.

**Comment by ioannisg** [comment]
@jukkar maybe rebase and re-try CI on this? Since now #17501 is merged.

**Review by ioannisg — APPROVED** [review]

**Review by nashif — APPROVED** [review]
we need to fix those CI issues

**Comment by jukkar** [comment]
Rebased. There is still the issue with qemu_x86_64 and net_buf test.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
@LeiW000 FYI

**Comment by jukkar** [comment]
Fixing merge conflicts

**Comment by jukkar** [comment]
Rebasing against latest master

**Comment by jukkar** [comment]
Only remaining issue is #15881

**Review by MaureenHelm — APPROVED** [review]

**Comment by jukkar** [comment]
The failing test should pass after #18531 is merged.

**Pull request merged**
