### PR TITLE
STM32: move dts.fixup files to soc level

### PR DESCRIPTION
**Pull request by dwagenk**
- move dts.fixup files contents from board level to soc family level for STM32 SOCs. (#5707)
   > tested by compiling spi_loopback test for 96b_carbon board before and after transition and comparing generated `generated_dts_board.h`

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Can you pull out the dts refactor’s into a separate PR.  Those look good and happy to merge them right away.

**Review by galak — CHANGES_REQUESTED** [review]
Seems like we should be able to get SPI loopback w/o having board specific conf files.

**Comment by DWagenk** [comment]
@ galak

> Can you pull out the dts refactor’s into a separate PR. Those look good and happy to merge them right away.

changed this PR to only contain the dts refactor.

**Review by ydamigos — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by erwango** [comment]
@DWagenk , @ydamigos , @galak : This has been fast, thanks!

**Pull request merged**
