### PR TITLE
Add driver for OpenTitan SPI host

### PR DESCRIPTION
**Pull request by snematbakhsh**

### CODE REVIEW

**Review by tbursztyka — CHANGES_REQUESTED** [review]
Handle the case when CONFIG_SPI_ASYNC=y in your driver (just have a function returning -ENOTSUP for api's transaction_async)

**Comment by snematbakhsh** [comment]
Oops, I don't think I intended to remove all reviewers? I thought I just clicked "Request Re-Review" for [tbursztyka](https://github.com/tbursztyka). I will re-add everyone.

**Comment by snematbakhsh** [comment]
> Oops, I don't think I intended to remove all reviewers? I thought I just clicked "Request Re-Review" for [tbursztyka](https://github.com/tbursztyka). I will re-add everyone.

Well, I will just leave it as-is for now, I don't seem to have the ability to manually add reviewers.

**Comment by fkokosinski** [comment]
Hi @snematbakhsh, I've manually readded reviewers that were previously added in this PR.

**Comment by snematbakhsh** [comment]
> Handle the case when CONFIG_SPI_ASYNC=y in your driver (just have a function returning -ENOTSUP for api's transaction_async)

Done.

**Comment by snematbakhsh** [comment]
> > Handle the case when CONFIG_SPI_ASYNC=y in your driver (just have a function returning -ENOTSUP for api's transaction_async)
> 
> Done.

**Comment by snematbakhsh** [comment]
Sorry for the churn, I am very unfamilar with the github interface. I thought that "close with comment" would close the "Change request", but in fact it closed the entire PR.

The requested change has been made and I believe this PR is ready for merge.

**Review by fkokosinski — DISMISSED** [review]
LGTM

**Comment by snematbakhsh** [comment]
> Handle the case when CONFIG_SPI_ASYNC=y in your driver (just have a function returning -ENOTSUP for api's transaction_async)

Done.

**Review by tbursztyka — DISMISSED** [review]

**Comment by carlescufi** [comment]
@snematbakhsh please rebase

**Comment by snematbakhsh** [comment]
> 

Done.

**Review by fkokosinski — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
