### PR TITLE
modules: hal_nordic: Update nrfx to version 2.1.0

### PR DESCRIPTION
**Pull request by anangl**
This PR updates the hal_nordic module revision, to switch to nrfx 2.1.0. It also reverts a temporary patch that is no longer needed after the update of nrfx.

Because the list of peripherals for nRF5340 has changed as follows:

- SPIM2 has been renamed to SPIM4
- SPIM2-3, SPIS2-3, TWIM2-3, TWIS2-3, and UARTE2-3 have been added

a couple of related corrections needed to be applied in dts and Kconfig files, plus the spi_nrfx_spim driver has been extended with the support for SPIM4.

---
https://github.com/zephyrproject-rtos/hal_nordic/pull/20 needs to go in first.

### CODE REVIEW

**Review by kl-cruz — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@anangl shippable failed due to static asserts, please check.

**Comment by anangl** [comment]
> @anangl shippable failed due to static asserts, please check.

Yes, I was a bit too quick with this PR. I forgot about some changes in nRF5340 peripherals. I applied corresponding corrections.

**Comment by anangl** [comment]
Rebased on master, to resolve the conflict in `west.yml`.

**Comment by anangl** [comment]
Updated hal_nordic revision to the proper SHA, as https://github.com/zephyrproject-rtos/hal_nordic/pull/20 has been merged.

**Pull request merged**
