### PR TITLE
linker: esp32: add iterable sections

### PR DESCRIPTION
**Pull request by sylvioalves**

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Comment by dcpleung** [comment]
Do you know if there is any plan to support more than 16 sections?

**Comment by sylvioalves** [comment]
> Do you know if there is any plan to support more than 16 sections?

@dcpleung Yes, once MCUBoot support gets ready, which is almost completed, we won't have this limitation anymore.

**Comment by sylvioalves** [comment]
Hi, can we get this review?

**Comment by sylvioalves** [comment]
@nashif Anything I can do here to merge this?

**Review by nashif — APPROVED** [review]

**Pull request merged**
