### PR TITLE
kernel: extensions and clarifications to time-conversion changes

### PR DESCRIPTION
**Pull request by pabigot**
Several concerns raised in review of #19591 were not addressed.  This provides the changes promised in https://github.com/zephyrproject-rtos/zephyr/pull/19591#issuecomment-544982246 to mitigate those concerns.

I don't insist on the move of the internal header to a less visible location, but it certainly didn't get the consideration I expected when I asked for it to be done in https://github.com/zephyrproject-rtos/zephyr/pull/19591#pullrequestreview-297761527 or in https://github.com/zephyrproject-rtos/zephyr/pull/17155#discussion_r321313551.

I can do nothing at this point about the essential-type changes made in-tree by the previous merge.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
This looks very sensible to me. I tried to check all the new conversion functions against the doc and they do look all correct. I did not check the parameters to `z_tmcvt()`.

**Review by nordic-krch — APPROVED** [review]
lgtm

**Comment by carlescufi** [comment]
@andyross could you please take a quick look before feature freeze?

**Comment by pabigot** [comment]
also please @nashif as the guardian of where include files go.  Thank you.

**Review by andyross — APPROVED** [review]
Looks harmless, sure.

**Review by tyrantlizard77 — APPROVED** [review]

**Pull request merged**
