### PR TITLE
SMP: PM: Fix for rebooting the core using PSCI.

### PR DESCRIPTION
**Pull request by SumitJain3083**
Currently If the secondary core is turned off using PSCI ( pm_cpu_off ) then it can't be turned on again.

This Has been discussed in the issue https://github.com/zephyrproject-rtos/zephyr/issues/64211.

To add this support , PSCI CPU_ON call fails because the function pointer for smp_init_top() is null.

Added the changes so that the function pointer is not NULL and secondary cores can call z_arm64_secondary_start() again to start the core after it has been turned off.

### CODE REVIEW

**Comment by povergoing** [comment]
`pm_cpu_off` is just to shut down the CPU, IMHO this is not a real shutting down and rebooting a core. There is no ending process of shutting down a core, for example, the system resources the core is holding, the corresponding gic rdist and any other resources held in cache. So this is a very dangerous feature.

**Comment by SumitJain3083** [comment]
> `pm_cpu_off` is just to shut down the CPU, IMHO this is not a real shutting down and rebooting a core. There is no ending process of shutting down a core, for example, the system resources the core is holding, the corresponding gic rdist and any other resources held in cache. So this is NOT enough to support rebooting a core

Agreed , this change is just to fix the part when if CPU on is called then the function pointer is null which causes the system crash.  other features like you mentioned clearing GIC rdist , flush cache has to be taken care off.

Can you please share more insights on when you say "Core acquire system resource ?"  or do you mean process running on core acquire system resource ?

**Comment by povergoing** [comment]
> Can you please share more insights on when you say "Core acquire system resource ?" or do you mean process running on core acquire system resource ?

The rebooting is a system-wide feature, not just an arch feature, so that's not an easy thing.
From what I can tell, the simplest way of rebooting might be (suppose you want to shutdown core 1): core 1 should go into the idle thread (this way you don't need to care about cache), do some cleanup before poweroff:
1) generic timer, if there is a timer already set (specifically the compare register) should migrate to another core.
2) GIC, all spi routing to the RDist corresponding to the core 1 should be handled, also need to think if this RDist should be powered off too, and should make sure the RDist can be reenabled without error.
3) FPU sharing, Zephyr arm64 enabled FPU sharing, should flush the context before powering off
4) SMP, also need to take care of the IPI, the core 1 should be removed from the broadcasting list.
I am not 100% sure but I believe there are still some annoying things you might need to handle ...
Definitely a big work.

**Comment by SumitJain3083** [comment]
@povergoing  does

> > Can you please share more insights on when you say "Core acquire system resource ?" or do you mean process running on core acquire system resource ?
> 
> The rebooting is a system-wide feature, not just an arch feature, so that's not an easy thing. From what I can tell, the simplest way of rebooting might be (suppose you want to shutdown core 1): core 1 should go into the idle thread (this way you don't need to care about cache), do some cleanup before poweroff:
> 
> 1. generic timer, if there is a timer already set (specifically the compare register) should migrate to another core.
> 2. GIC, all spi routing to the RDist corresponding to the core 1 should be handled, also need to think if this RDist should be powered off too, and should make sure the RDist can be reenabled without error.
> 3. FPU sharing, Zephyr arm64 enabled FPU sharing, should flush the context before powering off
> 4. SMP, also need to take care of the IPI, the core 1 should be removed from the broadcasting list.
> 
> I am not 100% sure but I believe there are still some annoying things you might need to handle ... Definitely a big work.

@povergoing  for the registered ISRs , does Zephyr OS has any setting to set the affinity. 
any info how we can disable the IPIs and SPIs on the core which is about to be turned off ? 

I checked Linux code and seems the only thing that is taken care off is the migration of all the interrupts. Can you please share your thoughts considering what is done on linux.

**Pull request closed without merging**
