### PR TITLE
boards: arm: add OTG_FS on nucleo_u575zi_q

### PR DESCRIPTION
**Pull request by Desvauxm-st**
add OTG_FS on nucleo_u575zi_q

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Please udate board documentation. Otherwise this is fine.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
> @erwango Why does this need to go into 3.6? It looks like a feature addition, not a bug fix.

Oops, indeed, this is for V3.7.0, sorry for the confusion... Thanks @MaureenHelm (Things are moving so fast in Zephyr .... ;D)

**Review by ajarmouni-st — APPROVED** [review]

**Review by nordicjm — CHANGES_REQUESTED** [review]
Needs converting to hwmv2

**Review by FRASTM — APPROVED** [review]

**Comment by erwango** [comment]
@marwaiehm-st Can you take the ownership of this PR ?

**Comment by erwango** [comment]
Replaced by #72357

**Pull request closed without merging**
