### PR TITLE
logging: Make v2 the default, deprecate v1 (alternative 2)

### LINKED ISSUE #41728: logging v2 transition
API meeting:

- Switch to v2 by default in 3.0.0
- Deprecation:
 
1. Deprecate in Kconfig:
```
if(CONFIG_LOG_IMMEDIATE || CONFIG_LOG_DEFERRED)
  message(WARNING "CONFIG_LOG_{IMMEDIATE,DEFERRED} is deprecated.
  Please use CONFIG_LOG2_{IMMEDIATE,DEFERRED}(defaults to v2) instead and adapt to the new backend API..."
    )
endif()
```

alternative:

```
CONFIG_LOG=y
CONFIG_LOG_V1=y
CONFIG_LOG_V2=y

// both v1 and v2
CONFIG_MODE_IMMEDIATE=y
CONFIG_MODE_DEFERRED=y
```

2. Add comments in [log_backed.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/logging/log_backend.h) stating clearly that v1 is deprecated, without actually doing any compiler-aware deprecation.

### PR DESCRIPTION
**Pull request by nordic-krch**
Counter proposal to #41739.

Deprecated `CONFIG_LOG2_MODE_DEFERRED` and `CONFIG_LOG2_MODE_IMMEDIATE`.

Introduced `CONFIG_LOG1` which enables legacy v1 (with cmake warning).

`CONFIG_LOG_MODE_IMMEDIATE=y` and `CONFIG_LOG_MODE_DEFERRED=y` enables v2.

Behavior for various use cases:

Using defaults
===========

If logging was just enabled with `CONFIG_LOG=y` v2 instead of v1 will be used. If out of tree backend is used which does not support v2 API, application will assert when no backend that supports v2 is found. `CONFIG_LOG1=y` can be added to use legacy backend.

Explicitly using v1
==============

If `CONFIG_LOG_MODE_DEFFERED=y` or `CONFIG_LOG_MODE_IMMEDIATE=y` was used v2 instead of v1 will be used. If out of tree backend is used which does not support v2 API, application will assert when no backend that supports v2 is found. `CONFIG_LOG1=y` can be added to use legacy backend.

Explicitly using v2
==============

If `CONFIG_LOG2_MODE_DEFFERED=y` or `CONFIG_LOG2_MODE_IMMEDIATE=y` there will be cmake warning but there will be no change in implementation. `CONFIG_LOG2_MODE_DEFFERED=y` can be removed since deferred mode is the default one. CONFIG_LOG2_MODE_IMMEDIATE=y` shall be changed to `CONFIG_LOG_MODE_IMMEDIATE=y`.

With this approach, when logging v1 is removed, just `CONFIG_LOG1` is removed.

Fixes #41728.

### CODE REVIEW

**Comment by nashif** [comment]
this alternative is my favourite.

**Comment by dcpleung** [comment]
Like to only have one set of `LOG_MODE_*`.

**Comment by nordic-krch** [comment]
Removed `DNM` and closed PR with alternative 1 as this one seemed to be leading. Please focus your review here so it can get in before freeze.

**Comment by henrikbrixandersen** [comment]
This is also my preferred solution. Thanks!

However, I am not familiar enough with the logging framework to provide a useful code review, so I will leave that to others.

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
