### PR TITLE
Add ENE KB1200 SOC support

### PR DESCRIPTION
**Pull request by ene-steven**

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Thank you for your contribution. However, please split this huge (12000+ lines) PR into multiple, smaller PRs. Start with initial SoC support along with a board, then gradually build on top of that in later PRs. 

Please see https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html for for further details.

**Comment by kartben** [comment]
Thanks for this! To add to what @henrikbrixandersen said, and to set expectations, feature freeze for Zephyr 3.5 is next week, Sept. 29, so it is unlikely that this can make it for 3.5. But just like Henrik said, splitting this into smaller PRs should definitely help!

**Comment by kartben** [comment]
Interestingly it looks like this PR is confusing the check_compliance script and putting it in some kind of deadlock.
I can reproduce locally, and it looks like it's due to the zillion of errors being reported (or the diff being too large, or both) and that don't fit into the pipe?

The hack below unlocks the situation
@fabiobaltieri 

```patch
diff --git a/scripts/ci/check_compliance.py b/scripts/ci/check_compliance.py
index c63007580e..bc362bf8b6 100755
--- a/scripts/ci/check_compliance.py
+++ b/scripts/ci/check_compliance.py
@@ -202,12 +202,24 @@ class CheckPatch(ComplianceTest):
                                 stdout=subprocess.PIPE,
                                 cwd=GIT_TOP)
         try:
-            subprocess.run((checkpatch, '--mailback', '--no-tree', '-'),
-                           check=True,
-                           stdin=diff.stdout,
-                           stdout=subprocess.PIPE,
-                           stderr=subprocess.STDOUT,
-                           shell=True, cwd=GIT_TOP)
+            process = subprocess.Popen(
+                [checkpatch, '--mailback', '--no-tree', '-'],
+                stdin=diff.stdout,
+                stdout=subprocess.PIPE,
+                stderr=subprocess.STDOUT,
+                shell=True, cwd=GIT_TOP,
+                text=True
+            )
+
+            while True:
+                output = process.stdout.readline()
+                if output:
+                    print(output.strip())
+                return_code = process.poll()
+                if return_code is not None:
+                    if return_code != 0:
+                        print(f"Process terminated with return code {return_code}")
+                    break

         except subprocess.CalledProcessError as ex:
             output = ex.output.decode("utf-8")
```

**Comment by fabiobaltieri** [comment]
> Interestingly it looks like this PR is confusing the check_compliance script and putting it in some kind of deadlock. I can reproduce locally, and it looks like it's due to the zillion of errors being reported (or the diff being too large, or both) and that don't fit into the pipe?

Too much output:

```
git diff HEAD~1..HEAD | ./scripts/checkpatch.pl --mailback --no-tree - | wc -l
75341
```

`re.findall` finds 18523 matches and the cycle that goes over those does not scale for some reasons, process the first few quickly and then starts processing them at a very slow rate, I've let it go for a minute or so and it was down to two (!!) per second, it'll eventually stale altogether.

Would not be mad if you want to rewrite it.

**Pull request closed without merging**
