### PR TITLE
Add UART5 to stm32f1 dts.fixup, Align all stm32 dts.fixup 

### PR DESCRIPTION
**Pull request by slightc**
1. Add UART5 to stm32f1 dts.fixup
2. I find in a lot of dts.fixup file is not alignment, an use **tab** , I'm raplace with **space**,
I hope developer can unify use the **space** not **tab**.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
UART5 addition in dts.fixup is good, but misses stm32f1xx dtsi files update to be enabled.

**Review by galak — CHANGES_REQUESTED** [review]
The whitespace change will not be accepted, its against the Style Guidelines for Zephyr.

**Comment by qq1433255094** [comment]
@galak thanks i will fix that

**Comment by erwango** [comment]
@qqqq1433255094, any update?

**Comment by erwango** [comment]
@thelittlehan , do you plan to continue this PR? Or should we close it?

**Comment by erwango** [comment]
@thelittlehan , UART5 is now in stm32f1 fixups, I'm closing this PR.

**Pull request closed without merging**
