### PR TITLE
net: if: Add new flags to disable ND/MLD per interface

### PR DESCRIPTION
**Pull request by rlubos**
Add new network interface flags, which allows to disable ND/MLD protocolS from being used on the interface. This allows to interfaces that do not support ND/MLD (like OpenThread) to coexist with other IPv6 interfaces.

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]
LGTM, any tests that we can add?

**Comment by rlubos** [comment]
> LGTM, any tests that we can add?

Yeah, I'll add a test case for each flag shortly.

**Comment by rlubos** [comment]
Ok, added a simple test case for each flag.

**Review by pdgendt — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Review by jukkar — COMMENTED** [review]
Looks good, but could you add the new flags to net_shell so that they are pretty printed in "net iface" cmd (see `iface_flags2str()` function in net_shell.c)

**Comment by rlubos** [comment]
> Looks good, but could you add the new flags to net_shell so that they are pretty printed in "net iface" cmd (see `iface_flags2str()` function in net_shell.c)

Sure, I've added a new commit covering this.

**Review by pdgendt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
