### PR TITLE
Build: Added support for out-of-tree Arch

### PR DESCRIPTION
**Pull request by kapedev**
Introduces the ARCH_ROOT argument, similar to BOARD_ROOT and SOC_ROOT.
This enables support for out-of-tree architectures.

The ARCH_ROOT out-of-tree layout is expected to be the following:
 * ${ARCH_ROOT}/arch/${ARCH}/
 * ${ARCH_ROOT}/include/arch/${ARCH}/ (Optional)

This PR supersedes PR #11411 now that the CMake version has been bumped

Signed-off-by: Klaus Petersen <kape@oticon.com>

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]

**Review by mped-oticon — APPROVED** [review]

**Comment by aescolar** [comment]
Note: The coverage report massive diff would seem to be due to codecov not being able to find the report from the last master, and quite confusedly picking another one as reference quite back in time

**Review by aescolar — APPROVED** [review]

**Comment by aescolar** [comment]
recheck

**Review by aescolar — DISMISSED** [review]
Documentation cannot be built with the PR as it is.

**Review by aescolar — APPROVED** [review]

**Comment by kapedev** [comment]
Thanks for the heads up Alberto, I’ll take a look tomorrow

Sent from my Spectrum ZX



On Thu, Feb 7, 2019 at 9:49 PM +0100, "Alberto Escolar" <notifications@github.com<mailto:notifications@github.com>> wrote:


@aescolar approved this pull request.

**Pull request merged**
