### PR TITLE
Add boards and drivers to 1.14 release notes

### PR DESCRIPTION
**Pull request by MaureenHelm**
- Adds all the new Arm, RISC-V, and shield boards to the 1.14 release
notes.
- Adds new and significantly modified drivers to the 1.14 release notes.

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
Should we consolidate the longs lists in a final edit?

**Review by ioannisg — APPROVED** [review]
Looks fine.
@anangl you might want to review the drivers' part.

**Comment by ruuddw** [comment]
Here's the summary list for ARC - let me know if you can merge into this PR, or prefer a separate PR.

Arch/ARC
 * Userspace and MPU driver improvements
 * Optimization of the thread stack definition macros
 * Bug fixes: handling of lp_xxx registers in _rirq_return_from_coop, nested interrupt handling, hardware stack bounds checking, execution benchmarking

Boards
 * Synopsys ARC IoT DevKit
 * Several ARC simulation targets (ARC nSIM EM/SEM; with and without MPU stack guards)

Drivers
 * arcv2 timer driver: refactoring and accuracy improvements (boot time measurements)

**Comment by nashif** [comment]
@ruuddw I will add those in a different PR.

**Pull request merged**
