### PR TITLE
lts: 2.7.5: security rel notes

### PR DESCRIPTION
**Pull request by ceolin**
Release notes about vulnerabilities fixed in 2.7.5 release.

### CODE REVIEW

**Comment by ceolin** [comment]
fixes #58353

**Review by cfriedt — APPROVED** [review]
LGTM - @stephanosio, can you also ack / Super-Power merge?

**Comment by cfriedt** [comment]
@ceolin - were there any specific CVEs part of the mbedTLS 2.26.x release that should be included here? Would it make sense to mention the CVEs that we're potentially avoided by switching to mbedTLS 2.28?

If we don't have evidence of an attack against Zephyr even, is there a link that can be referenced that lists generally which vulnerabilities were fixed between 2.26 and 2.28?

**Review by stephanosio — APPROVED** [review]

**Comment by cfriedt** [comment]
A link to the mbedTLS release notes already exists, I'm just really curious about actual CVEs encountered in the wild in any product between 2.26 and 2.28

**Comment by cfriedt** [comment]
https://www.cvedetails.com/vulnerability-list/vendor_id-15698/product_id-32568/year-2021/ARM-Mbed-Tls.html
https://www.cvedetails.com/vulnerability-list/vendor_id-15698/product_id-32568/year-2022/ARM-Mbed-Tls.html
https://www.cvedetails.com/vulnerability-list/vendor_id-15698/product_id-32568/year-2023/ARM-Mbed-Tls.html

**Comment by ceolin** [comment]
> A link to the mbedTLS release notes already exists, I'm just really curious about actual CVEs encountered in the wild in any product between 2.26 and 2.28

I just added a commit on top with vulnerabilities fixed from 2.26 to 2.28.3. I think that is a little bit to much for us tbh though.

**Comment by cfriedt** [comment]
LGTM - thanks @ceolin .

@stephanosio - please merge when it's green

**Pull request merged**
