### PR TITLE
.github: use west update --narrow

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This avoids fetching unnecessary refs.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
This _should_ work with the changes GitHub made to allow fetching SHAs directly, but let's see how CI reacts.

**Comment by mbolivar-nordic** [comment]
@galak I'm seeing lines in the output that make it seem like the caches aren't used everywhere, e.g.:

```
 --- edtt: initializing
Initialized empty Git repository in /__w/zephyr/tools/edtt/.git/
```

I see this in https://github.com/zephyrproject-rtos/zephyr/pull/34881/checks?check_run_id=2513564523 for example.

Does the container have the modules already downloaded somewhere? That would be the best way to speed this up. If you have an existing workspace somewhere else on the system, you can do `west update --narrow --path-cache /my/existing/workspace`; that's the biggest win.

**Comment by galak** [comment]
> @galak I'm seeing lines in the output that make it seem like the caches aren't used everywhere, e.g.:
> 
> ```
>  --- edtt: initializing
> Initialized empty Git repository in /__w/zephyr/tools/edtt/.git/
> ```
> 
> I see this in https://github.com/zephyrproject-rtos/zephyr/pull/34881/checks?check_run_id=2513564523 for example.
> 
> Does the container have the modules already downloaded somewhere? That would be the best way to speed this up. If you have an existing workspace somewhere else on the system, you can do `west update --narrow --path-cache /my/existing/workspace`; that's the biggest win.

The container doesn't have a cache at all in it.  The AWS EC2 image has the cache.  So we could add cache to the github workflows.

**Comment by mbolivar-nordic** [comment]
> So we could add cache to the github workflows.

That would definitely make them go faster, but this PR seems to have passed CI and should provide some improvement as a standalone patch. Your call what to do with it.

**Comment by mbolivar-nordic** [comment]
@galak are you still interested in this? If not I'll close it.

**Comment by cfriedt** [comment]
@mbolivar - I think this is worthwhile if this saves a fair bit of bandwidth without necessarily requiring any elaborate caching schemes to be devised. Would be happy to approve as well, if @galak is still on board.

**Comment by mbolivar-nordic** [comment]
It saves an amount of bandwidth equal to the unnecessary objects which are not fetched. I think it's a harmless optimization even if it's minor.

**Comment by mbolivar-nordic** [comment]
Closing due to lack of feedback.

**Pull request closed without merging**
