### PR TITLE
samples: logging: disable usermode for bytesensi_l

### LINKED ISSUE #75617: samples/subsys/logging/logger/sample.logger.usermode fails to build for bytesensi_l & bl654_dvk/nrf52840/pa
**Describe the bug**
samples/subsys/logging/logger/sample.logger.usermode fails to build for both
* bytesensi_l 
* bl654_dvk/nrf52840/pa

**To Reproduce**
1. twister -p bytesensi_l -T samples/subsys/logging/logger -s sample.logger.usermode

**Expected behavior**
No build errors (or platforms filtered out from test)

**Impact**
2 failures in weekly CI

**Logs and console output**
```
warning: LOG_PRINTK (defined at subsys/logging/Kconfig.processing:8) has direct dependencies !USERSPACE && !LOG_MODE_MINIMAL && LOG with value n, but is currently being y-selected by the following symbols:
 - LOG_BACKEND_RTT_FORCE_PRINTK (defined at subsys/logging/backends/Kconfig.rtt:104), with value y, direct dependencies LOG_BACKEND_RTT && !LOG_FRONTEND_ONLY && !LOG_MODE_MINIMAL && LOG (value: y), and select condition LOG_BACKEND_RTT && !LOG_FRONTEND_ONLY && !LOG_MODE_MINIMAL && LOG (value: y)
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 22.04 CI
 - Toolchain (e.g Zephyr SDK, ...): 0.16.8
 - Commit SHA or Version used: main as of now 980d3f4c4f4ef4ec15c5bcd538155a184df6e1b8

### PR DESCRIPTION
**Pull request by morandg**
This fixes https://github.com/zephyrproject-rtos/zephyr/issues/75617

### CODE REVIEW

**Review by aescolar — COMMENTED** [review]
Could you please add also bl654_dvk_pa ? 
Thanks in advance

**Comment by morandg** [comment]
@aescolar , does this platform exist or am I missing something?
```bash
$ twister -p bl654_dvk_pa -T zephyr/samples/subsys/logging/logger -s sample.logger.usermode
# ...
ERROR   - platform_filter - unrecognized platform - bl654_dvk_pa
```

**Comment by aescolar** [comment]
> @aescolar , does this platform exist or am I missing something?
> 
> ```shell
> $ twister -p bl654_dvk_pa -T zephyr/samples/subsys/logging/logger -s sample.logger.usermode
> # ...
> ERROR   - platform_filter - unrecognized platform - bl654_dvk_pa
> ```

Sorry `bl654_dvk/nrf52840/pa`

**Review by aescolar — APPROVED** [review]

**Review by dariis — APPROVED** [review]
worked for me, both were skipped:
```bash
twister -p bytesensi_l -T samples/subsys/logging/logger -s sample.logger.usermode
twister -p bl654_dvk/nrf52840/pa -T samples/subsys/logging/logger -s sample.logger.usermode
```

**Review by nordic-krch — APPROVED** [review]

**Review by rerickson1 — APPROVED** [review]

**Pull request merged**
