### PR TITLE
libraries for support mcuboot serial FWU

### LINKED ISSUE #3081: Concise Binary Object Representation (CBOR)
**_Reported by Anas Nashif:_**

from RFC7049:

The Concise Binary Object Representation (CBOR) is a data format
whose design goals include the possibility of extremely small code
size, fairly small message size, and extensibility without the need
for version negotiation.  These design goals make it different from
earlier binary serializations such as ASN.1 and MessagePack.

(Imported from Jira ZEP-1620)

### PR DESCRIPTION
**Pull request by nvlsianpu**
This patch introduce libraries which are need for support Mcuboot serial recovery mode.
These libraries are in usage by newtmgr protocol encoding and parsing. Mcuboot serial recovery protocol simply implements image related piece of newtmgr protocol.

Libraries:
- tinycbor:  cbor library
- cborattr: attribute based decoder cbor
- base64: base64 library

These libraries will be useful for future OTA DFU works as well.

As the serial recovery functionality consumes additional flash, the bootloader partition was extended as well for nRF52840 SoC.

Fixed #3081.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@carlescufi, @utzig

**Comment by carlescufi** [comment]
@nvlsianpu "ext: lib: Add cboorattr library" s/cboorattr/cborattr

**Review by nashif — CHANGES_REQUESTED** [review]
tinycbor  origin is https://github.com/01org/tinycbor, not mynewt, you need to import and document the original source. Did mynewt have patches on top of upstream?

**Comment by nvlsianpu** [comment]
> did mynewt have patches on top of upstream
Yes it has. The status is that origin dosen't fit to the cborattr and newtmgr anymore.

**Comment by nashif** [comment]
@thiagomacieira your thoughts?

**Comment by thiagomacieira** [comment]
Comparing to TinyCBOR v0.4

```diff
+struct cbor_encoder_writer;
+
+typedef int (cbor_encoder_write)(struct cbor_encoder_writer *, const char *data, int len);
+
+typedef struct cbor_encoder_writer {
+    cbor_encoder_write *write;
+    int                 bytes_written;
+} cbor_encoder_writer;
+
+
 /* Encoder API */
 struct CborEncoder
 {
-    union {
-        uint8_t *ptr;
-        ptrdiff_t bytes_needed;
-    } data;
-    const uint8_t *end;
+    cbor_encoder_writer *writer;
+    void *writer_arg;
     size_t added;
     int flags;
 };
@@ -172,7 +179,8 @@ typedef struct CborEncoder CborEncoder;
 
 static const size_t CborIndefiniteLength = SIZE_MAX;
 
-CBOR_API void cbor_encoder_init(CborEncoder *encoder, uint8_t *buffer, size_t size, int flags);
+
+CBOR_API void cbor_encoder_init(CborEncoder *encoder, cbor_encoder_writer *pwriter, int flags);
```

This is a wholly patched and unsupported version. This is not upstream.

TinyCBOR team has been trying to design a writer that would be able to work with Zephyr's `net_buf` but has not come to an API yet. When we do, it will be different from the above.

My recommendation is to reject this import and instead work with TinyCBOR upstream to design this feature sooner rather than later (it's not in the v0.5 roadmap).

**Comment by carlescufi** [comment]
@thiagomacieira @nashif @nvlsianpu I understand. Can we take a middle-ground way forward here? i.e. accept this temporarily and work upstream in parallel. The problem is that it's not only the serial recovery mode that will need this, but also the DFU work that will start next week, and unless we can really add this upstream in that timeframe we will be blocked by the lack of CBOR support in Zephyr.

**Comment by thiagomacieira** [comment]
Not sure that's a good idea. There's other software using TinyCBOR and Zephyr at the same time. Introducing this patched version will cause symbol collision and subtle errors.

**Comment by nvlsianpu** [comment]
We can move this tinycbor to mynewt_tinycybor as temporary resolution and us it only for a newtmgr like dfu. Then in near future we should move to original tinycbor.

**Comment by thiagomacieira** [comment]
You need to rename all non-static functions.

**Comment by nvlsianpu** [comment]
I mean to move it to separate code piece  in sense of Kconfig + Make file. So if it will be kept as not enable i will be not included in the build by any means.  I'm not sure if using both version simultaneously make sense. Is it a case?

As @carlescufi wrote: we want this as temporary (but not shadow) solution for much bigger  and important for use and Zephyr DFU development.

**Comment by thiagomacieira** [comment]
My point is that if you import a patched TinyCBOR, you may break applications that use TinyCBOR because the symbols will clash with the application-provided copy. The only way out for that is to rename all non-static symbols, until we manage to upstream the feature and then deduplicate.

**Comment by utzig** [comment]
Another option might be to break tinycbor out of this PR, add it to the DFU "branch" and/or to mcuboot (for serial recovery) for the time being, and start working ASAP on designing and upstreaming the writer interfaces. Would that work?

**Comment by nvlsianpu** [comment]
@utzig I would accept that. It should touch both tinycbor and cborattr. @carlescufi you thoughts?

**Review by galak — CHANGES_REQUESTED** [review]
The commit message doesn't really give enough info to find the sources you are referring to, I'd expect a git tree URL

**Comment by nvlsianpu** [comment]
I close this as replayed by https://github.com/zephyrproject-rtos/zephyr/pull/4237

**Pull request closed without merging**
