### PR TITLE
C++: add a sample on using exceptions

### PR DESCRIPTION
**Pull request by brgl**
~The docs state that C++ exceptions work but the compiler flags disable them. This removes the switch in question and adds a sample that contains example configuration that enables exception handling and shows how a custom exception can be implemented, throws and caught.~

All I needed was to enable `CONFIG_EXCEPTIONS=y` but the sample is still useful so I'll keep this PR. Especially since unlike the test, it shows that we can implement custom exceptions inheriting from others and catch them by their parent class' type.

### CODE REVIEW

**Review by stephanosio — CHANGES_REQUESTED** [review]
You need to set `CONFIG_EXCEPTIONS=y` if you want exceptions support and that is clearly documented in the docs:
https://docs.zephyrproject.org/latest/develop/languages/cpp/index.html#language-features

> In order to make use of the C++ exceptions, the [CONFIG_EXCEPTIONS](https://docs.zephyrproject.org/latest/kconfig.html#CONFIG_EXCEPTIONS) must be selected in the application configuration file.

Also, we already have a test that tests exceptions:
https://github.com/zephyrproject-rtos/zephyr/blob/855216f582d2e10f65159c70f104579d0c6235b0/tests/subsys/cpp/libcxx/src/main.cpp#L76-L89

**Comment by brgl** [comment]
Ah, this wasn't clear. Thanks. I would still keep the sample if you don't mind, I find samples easier to browse for hints than tests.

**Comment by stephanosio** [comment]
> Ah, this wasn't clear. Thanks. I would still keep the sample if you don't mind, I find samples easier to browse for hints than tests.

[This is already quite clearly documented in the docs as well as in Kconfig](https://docs.zephyrproject.org/latest/develop/languages/cpp/index.html#language-features):

> In order to make use of the C++ exceptions, the [CONFIG_EXCEPTIONS](https://docs.zephyrproject.org/latest/kconfig.html#CONFIG_EXCEPTIONS) must be selected in the application configuration file.

I do not think adding a dedicated sample for C++ exceptions is the right way to go about. If any, it should be documentation update to make exceptions support-related details more visible.

**Comment by stephanosio** [comment]
> Browsing examples is faster and usually the first step before diving into docs.

For Zephyr, the boundary between the "samples" and "tests" is somewhat blurred. Ideally, "samples" should be of more practical use than the "tests" (e.g. USB CDC device sample).

If we are talking about an example on just using "exceptions," then we already have a test that can serve as a good example -- it does not make sense to add a "sample" that just demonstrates how to use exceptions when we already have a "test" that does exactly that and can serve as a good example.

**Comment by stephanosio** [comment]
> Exceptions don't work for every config and when they don't work

When you set `CONFIG_EXCEPTIONS=y` for an unsupported configuration, you will get a Kconfig message saying the symbol has been de-selected.

**Comment by brgl** [comment]
In that case would a test case for exception inheritance work?

**Comment by stephanosio** [comment]
> In that case would a test case for exception inheritance work?

sure, as long as you are adding it to `tests/subsys/cpp/libcxx`.

**Pull request closed without merging**
