### PR TITLE
build: native_posix: use iterable sections

### PR DESCRIPTION
**Pull request by cfriedt**
Convert native_posix tasks into iterable sections for consistency.

### CODE REVIEW

**Comment by cfriedt** [comment]
Just a few comments:
* main motivator was to have less irregularity to deal with when adding macOS support for `native_posix`
* iterable sections have a more consistent layout, naming convention, etc, than the previous native task structure
* obviously, less performant to sort at runtime, but we're still talking about maybe a ms delay on GHz CPUs
* Alternative to sorting at runtime would be to define a different iterable section for each level (i.e. `struct native_task_PRE_BOOT_1`, etc)
* probably less desireable to have several structs aliasing the same `struct native_posix`

Happy to rework, but this change makes adding macOS support a bit easier.

**Review by aescolar — CHANGES_REQUESTED** [review]
I may be missing something, and if that is the case I'd be happy to hear it.
But I do not see why ordering native_tasks at runtime helps in the big picture given that native_posix needs to support linker sorted sections just like every other platform.

**Comment by cfriedt** [comment]
> I may be missing something, and if that is the case I'd be happy to hear it. But I do not see why ordering native_tasks at runtime helps in the big picture given that native_posix needs to support linker sorted sections just like every other platform.

@aescolar - With this change `native_posix` would still default to linker-sorted sections (in general), so that has not changed.

Here it is really only the `struct native_task` iterable section that is sorted at runtime. It's questionable whether there is any hard requirement at all for the (new) iterable section to be sorted by the linker.

As I said, it **is** possible to do the same thing in the linker, but it makes for slightly less appealing code.

Essentially, it boils down to creating several structs instead of one. I found the code "less pleasant" to look at, but to each their own.
```
struct native_task_PRE_BOOT_1;
struct native_task_PRE_BOOT_2;
struct native_task_PRE_BOOT_3;
struct native_task_FIRST_SLEEP;
struct native_task_AT_EXIT;
```

I'll add another commit to this PR without squashing to give you an idea of what that alternative looks like. If you prefer that alternative, then I'll squash.

**Comment by aescolar** [comment]
>I'll add another commit to this PR without squashing to give you an idea of what that alternative looks like. If you prefer that alternative, then I'll squash.

Please do

**Comment by cfriedt** [comment]
@aescolar - this might not be necessary, so I'm going to set it back to draft mode.

Lately I've been going down a bit of a rabbit hole getting focusing on clang / LLVM quirks on macOS. One quirk with LLVM is that the ld64.lld (LLD implementation on macOS) was only ever designed to be feature-compatible with Apple's linker, which does not support linker scripts.

I may be about to embark on a fool's errand, but I think it may be possible to add GNU linker script support to LLD. All of the parsing code can be reused, for example. There are some semantic differences that need to be either ignored or reinterpreted between ELF and Mach-O but I think it can be done.

**Pull request closed without merging**
