### PR TITLE
dts: arm: silabs: Remove label property from devicetrees

### PR DESCRIPTION
**Pull request by galak**
Label properties are not required.

Signed-off-by: Kumar Gala <galak@kernel.org>

### CODE REVIEW

**Review by chrta — APPROVED** [review]
lgtm

**Review by henrikbrixandersen — APPROVED** [review]

**Review by catch-twenty-two — APPROVED** [review]
looks good, thanks for the heads up

**Comment by DRuffer** [comment]
I'm wondering what is driving this change. We use node labels and the label field interchangeably, but not looking forward to tracking down all the label field usages and "fixing" them at this point. If we do need to do this, then it would be useful to have a justification for the effort.

**Comment by galak** [comment]
> I'm wondering what is driving this change. We use node labels and the label field interchangeably, but not looking forward to tracking down all the label field usages and "fixing" them at this point. If we do need to do this, then it would be useful to have a justification for the effort.

The label property in devicetree was never meant to be utilized as we have in Zephyr.  Its a long standing cleanup to remove it.  We've cleaned up its usage in tree so `label` is only utilized in a small handful of places.

**Pull request merged**
