### PR TITLE
lib: os: cbprintf: Add support for packed packages.

### PR DESCRIPTION
**Pull request by nordic-krch**
Added support for packages with packed (without alignment) arguments.
Such packages are not using va_arg to get argument but copy data
directly from the buffer. This approach saves space and allow
to move message between different platforms (with same
endianess).
    
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by npitre** [comment]
I'm not convinced by this.

My reaction to @pabigot's proposal from a couple months ago was about
the fact that the cbprintf code got way more complex and harder to
maintain. This is why I suggested the va_list-based alternative to allow
for reusing the print formatting code unchanged.

This PR is crossing the same line as @pabigot's original proposal, even
though the code is abstracted inside a macro. As soon as
CONFIG_CBPRINTF_PACKAGE_PACKED is turned on, the runtime printf code
complexity explodes for all users. What is the benefit in that case to
have static log records created at compile time with super clever macros
for space efficiency if the runtime code to consume them doubles in size?

One of the stated reasons is:

```
    Such packages are not using va_arg to get argument but copy data
    directly from the buffer. This approach saves space and allow
    to move message between different platforms (with same
    endianess).
```

This is broken not only across different endianess, but also across
word sizes. In particular, "%ld" (long) does not have the same size
on 32-bits vs 64-bits architectures, and similarly for pointers, size_t,
etc. And when is the alignment most likely to change? Yes, when moving
from 32 to 64 bits and the other way around. So... do you *really* need
to support this case?

As for saving space... I think there is a much simpler and more efficient
way to actually save space. The idea is to look at the va_list packaged
buffer and remove all the zero integers from it. That includes ints
representing placeholders for string pointers for those strings that
have been copied into the package, as well as actual zero values, or
even larger integers like long longs whose magnitude is way smaller
than the available value range (pretty common in practice), and of course
actual alignment padding. I did start to write some code a while ago to
do just that which used the unused portion of the header as a bitmap to
remember where to insert zeroes back in `cbpprintf()`. I just didn't get
around to complete it. But this has the potential to save much more space
than simply getting rid of alignment constraints, with very little new
code. And the printf code still remains unchanged/optimal.

**Comment by nordic-krch** [comment]
@npitre 
> cbprintf code got way more complex and harder to maintain.

Change is limited only to argument getting method so i can't see how it increases complexity and thus cost of maintenance.

> As soon as CONFIG_CBPRINTF_PACKAGE_PACKED is turned on, the runtime printf code complexity explodes for all users.

It is now foreseen that It will be enabled only in specific cases (some versions of multi-domain logging).

>  if the runtime code to consume them doubles in size

Enabling this option adds ~270 bytes of ROM (cortex-m3).

> This is broken not only across different endianess, but also across word sizes. 

Yes, you are right, it's not only the endianess but also discrepancy in standard type sizes. However, I've compared sizes and alignment for all platforms supported by zephyr and results are following. If we look at standard type sizes (excluding long doubles) then all 32 bit platforms has the same sizes, same goes for 64 bit platforms. As for alignment, there are more discrepancy between 32 bit platforms (while all 3 64 bit platforms has the same alignment). It means, that packed packages can be shared between 32 bit cores in same SoC (if long doubles are not used), same for 64 bit SoC.

The idea for using packed packages is multi-domain logger in multicore SoC. If you have a helper CPU that is relatively slow but you would like to get logging data from it to the master core. Since helper CPU is slow (or loaded) you would like to avoid string formatting there, using packed packages you can pass log message (packages) even when alignment does not match (but sizes do). It is assumed that if alignement+size does not match then the only option to pass package is to format a string locally and create a package that contains formatted string. That will be the default behavior, enabling packed version will be done on SoC level configuration.

> As for saving space...

That is not the reason i'm doing it. If there is a gain that's good but i am aware that it is rather insignificant.

**Comment by npitre** [comment]
> Yes, you are right, it's not only the endianess but also discrepancy in standard type sizes. However, I've compared sizes and alignment for all platforms supported by zephyr and results are following. If we look at standard type sizes (excluding long doubles) then all 32 bit platforms has the same sizes, same goes for 64 bit platforms. As for alignment, there are more discrepancy between 32 bit platforms (while all 3 64 bit platforms has the same alignment). It means, that packed packages can be shared between 32 bit cores in same SoC (if long doubles are not used), same for 64 bit SoC.

We agree that this doesn't work across architecture widths nor 
endianness. And on 64-bit architectures the alignment tend to stay the 
same already.

So what is your usage scenario where this would be needed?

If this is only one particular case then it is probably wiser to have 
one particular solution rather than having a large solution that has the 
looks of being generic but isn't in practice.

**Comment by nordic-krch** [comment]
Ok, will close for now.

**Pull request closed without merging**
