### PR TITLE
CAN internal controller on NucleoF412ZG

### PR DESCRIPTION
**Pull request by pbonazzi**
Added CAN node for NucleoF412ZG board . 

I have tested it with ``samples/drivers/can`` .

### CODE REVIEW

**Review by martinjaeger — CHANGES_REQUESTED** [review]
Hi @pbonazzi, thanks for the contribution and congrats to your first Zephyr PR.

There are a few minor changes required to make this PR ready to merge. Did you see the [contribution guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html)?

- The commit message has to be updated (see guideline) and needs to include the sign-off line.
- The two commits have to be squashed.

Other than that it looks good.

**Review by martinjaeger — CHANGES_REQUESTED** [review]
The two commits have to be squashed into a single one.

Can you also please check the build failure?

**Comment by lairdjm** [comment]
@pbonazzi I think an issue has arisen here

**Comment by martinjaeger** [comment]
@pbonazzi Please see [here](https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow) for some hints regarding `git rebase -i` workflow. Most important: Don't use `git merge`.

**Comment by pbonazzi** [comment]
Thank you for supporting me, I will follow these steps carefully now .

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Martin Jäger ***@***.***>
Gesendet: Tuesday, June 7, 2022 9:48:43 AM
An: zephyrproject-rtos/zephyr ***@***.***>
Cc: Pietro Bonazzi ***@***.***>; Mention ***@***.***>
Betreff: Re: [zephyrproject-rtos/zephyr] CAN internal controller on NucleoF412ZG (PR #45985)


@pbonazzi<https://github.com/pbonazzi> Please see here<https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow> for some hints regarding git rebase -i workflow. Most important: Don't use git merge.

**Pull request closed without merging**
