### PR TITLE
usb: Add USB definitions for EEM device

### PR DESCRIPTION
**Pull request by loicpoulain**
Add CDC Ethernet Emulation Model subclass and protocol codes.

Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
A typical questions would be: why do we need these (on their own, without any code using them)?

**Comment by finikorg** [comment]
@loicpoulain are you implementing EEM? btw I am going to send pull request for ECM and there is RNDIS work in progress.

**Review by finikorg — APPROVED** [review]
The numbers at least are correct ;)

**Comment by loicpoulain** [comment]
Yes trying to implement EEM.

**Comment by jfischer-phytec-iot** [comment]
It would be better to insert the subclass and protocol codes + management and notification elements into respective class header, and because it is CDC EEM, 9c91652 might be appropriate.

**Comment by nashif** [comment]
this PR needs to be rebased

**Review by nashif — APPROVED** [review]

**Pull request merged**
