### PR TITLE
input: it8xxx2_kbd: fix col_size build warning range

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Fix the range check for col_size to allow a configuration with less than 16 columns. Not sure why the minimum was set so high but there's no reason I can tell for it.

### CODE REVIEW

**Review by nashif — DISMISSED** [review]

**Review by gmarull — DISMISSED** [review]

**Review by keith-zephyr — DISMISSED** [review]

**Comment by Dino-Li** [comment]
Should we also make masks for driving columns and reading rows based on the properties of row-size and col-size?
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/input/input_ite_it8xxx2_kbd.c#L73
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/input/input_ite_it8xxx2_kbd.c#L86
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/input/input_ite_it8xxx2_kbd.c#L172

**Comment by fabiobaltieri** [comment]
@Dino-Li do we have to? My doubt was `drivers/gpio/gpio_kscan_ite_it8xxx2.c` when using those pins as gpio but it seems to be using different registers, so I'd imagine that there's no conflict with other drivers. Is there any issue you can think of when using these unmasked? The board I'm using has all 18 lines going to the keyboard connector, I didn't see any problem but can certainly run some tests if you suspect any issue.

**Comment by Dino-Li** [comment]
> @Dino-Li do we have to? My doubt was `drivers/gpio/gpio_kscan_ite_it8xxx2.c` when using those pins as gpio but it seems to be using different registers, so I'd imagine that there's no conflict with other drivers and the pin control multiplexing is thinking the function separate. Is there any issue you can think of when using these unmasked? The board I'm using has all 18 lines going to the keyboard connector, I didn't see any problem but can certainly run some tests if you suspect any issue.

We have to do this because KBS and GPIO modes use the same KSOL and KSOH1 registers to drive pins.
kbs

**Comment by fabiobaltieri** [comment]
@Dino-Li ok I see what's going on there, yes that needs a couple masks let me give it a shot

**Comment by Dino-Li** [comment]
> how does that look now? 

LGTM.

>Dropped a couple castings that I don't think were needed as well while at it to keep things a bit simpler, did not do `KBS_KSI` since it should not really matter, same for `KBS_KSOH2` right?

Right.

**Comment by fabiobaltieri** [comment]
Ok I'm a bit limited in what I can test with what I have but it seems to work alright, masks are what I expect (13 cols 0xff and 0x1f), keyboard works.

@Dino-Li thanks for spotting the issue.

**Review by Dino-Li — APPROVED** [review]

**Review by aasinclair — APPROVED** [review]

**Pull request merged**
