### PR TITLE
terminology: adopt CMake, python, and Kconfig code to use qualifiers

### PR DESCRIPTION
**Pull request by tejlmand**
Followup: #69905

Adopting new board terminology for CMake, python, and Kconfig code to use qualifiers instead of identifiers.

Also adjusted to board target where applicable.

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]

**Review by nordicjm — CHANGES_REQUESTED** [review]
Missing update in `scripts/snippets.py`

**Comment by nordicjm** [comment]
`samples/drivers/counter/maxim_ds3231/README.rst` has `boot banner, board identifier` which can be updated also

**Comment by nordicjm** [comment]
`doc/hardware/porting/board_porting.rst` needs updating too

**Comment by tejlmand** [comment]
> Missing update in scripts/snippets.py
> samples/drivers/counter/maxim_ds3231/README.rst has boot banner, board identifier which can be updated also
> doc/hardware/porting/board_porting.rst needs updating too

All updated.

**Review by gmarull — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]
PR with `west boards` completion needs to be merged right after this is merged

**Review by fabiobaltieri — DISMISSED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
