### PR TITLE
tests: pwm_api: Add timing check

### PR DESCRIPTION
**Pull request by raffarost**
Use GPIO interrupts to check PWM output timing.

Depends on #80872

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
This is what https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/pwm/pwm_loopback is for?

**Comment by raffarost** [comment]
> This is what https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/pwm/pwm_loopback is for?

Hi @henrikbrixandersen,
I understand pwm_loopback requires the peripheral to support CC, which is not the case for all drivers (e.g ESP's LEDC pwm).

**Comment by henrikbrixandersen** [comment]
> > This is what [`main`/tests/drivers/pwm/pwm_loopback](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/pwm/pwm_loopback?rgh-link-date=2024-11-18T13%3A25%3A12Z) is for?
> 
> Hi @henrikbrixandersen, I understand pwm_loopback requires the peripheral to support CC, which is not the case for all drivers (e.g ESP's LEDC pwm).

Does the chip have another PWM-capture capable peripheral? Producer and consumer does not need to be of the same peripheral type in `pwm_loopback`.

I'm okay with introducing a GPIO-based PWM loopback test, but I don't think it should be in the main PWM API test suite like this (which is also why I placed the initial loopback test in its own test suite).

**Comment by raffarost** [comment]
> > > This is what [`main`/tests/drivers/pwm/pwm_loopback](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/pwm/pwm_loopback?rgh-link-date=2024-11-18T13%3A25%3A12Z) is for?
> > 
> > 
> > Hi @henrikbrixandersen, I understand pwm_loopback requires the peripheral to support CC, which is not the case for all drivers (e.g ESP's LEDC pwm).
> 
> Does the chip have another PWM-capture capable peripheral? Producer and consumer does not need to be of the same peripheral type in `pwm_loopback`.
> 
> I'm okay with introducing a GPIO-based PWM loopback test, but I don't think it should be in the main PWM API test suite like this (which is also why I placed the initial loopback test in its own test suite).

Some Espressif chips only have LEDC and no MCPWM, thus no CC available. The test was meant to be a simple timing check, because we've had some regressions after HAL updates. I can create a separate test suite for it. I'd just need to think how to avoid repeating code, as the 'configs', 'sets' and test sequence would be the same.

**Comment by raffarost** [comment]
@henrikbrixandersen I created a PR for the new implementation

**Comment by bjarki-andreasen** [comment]
should this one be closed in favor of #82258 ?

**Pull request closed without merging**
