### PR TITLE
Link Layer Discovery Protocol support

### PR DESCRIPTION
**Pull request by jukkar**

### CODE REVIEW

**Review by tbursztyka — CHANGES_REQUESTED** [review]
Overall looks ok to me.

One thing in lldp core code: could you use lldp_ prefix to all "private" (aka static) functions there. That's all.

**Comment by jukkar** [comment]
> One thing in lldp core code: could you use lldp_ prefix to all "private" (aka static) functions there. That's all.

I do not see much point in this prefix thing. The net_* prefix means the function is public, all the other functions are private thus the naming is irrelevant here. Also all private functions are contained locally in one file so they are also easy to find.

**Review by tbursztyka — APPROVED** [review]

**Review by dbkinder — CHANGES_REQUESTED** [review]
small tweaks suggested

**Comment by jukkar** [comment]
Compilation and documentation fixes.

**Comment by jukkar** [comment]
Fixed rebase conflict

**Comment by jukkar** [comment]
ping @dbkinder

**Comment by jukkar** [comment]
recheck

**Review by dbkinder — APPROVED** [review]
OK, thanks.

**Pull request merged**
