### PR TITLE
modules: tfm: Split trusted-firmware-m repository

### LINKED ISSUE #39353: TFM: Split trusted-firmware-m repository
## Introduction

Split the zephyr project maintained repository trusted-firmware-m into a fork of the individual upstream repositories

## Problem description

In the current setup of the TF-M repositories the history of the upstream repositories are lost.
This complicates the maintainability of the project, for example:
 - Checking if a fix has been included
 - Checking why a change was made
 - Cherry-picking important fixes outside of a regular sync-up.
 - Bisecting

## Proposed change

Split the current trusted-firmware-m repository into a per-repository fork of upstream.

## Detailed RFC
Create 3 forks of the upstream repositories:
 - https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git
   revision: a199c3047f320a2f82b9a0c27af5b50991184e0f
 - https://git.trustedfirmware.org/TF-M/tf-m-tests.git
   revision: b0c06b46b8a32d73794637e2a034a9cfbb4e883b
 - https://github.com/ARM-software/psa-arch-tests.git 
   revision: 02d145d80da31bc78ce486bda99ad55597fea0ca

Apply the current set of downstream patches to the individual repositories.
The organization of the folders would remain the same.

### Dependencies

Affects projects / users that have forked the current repository (i.e NCS).

## Alternatives

Do nothing

### PR DESCRIPTION
**Pull request by joerchan**
Split the zephyr project maintained repository trusted-firmware-m into
forks of the individual upstream repositories.

https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git
Upstream: TF-Mv1.4.1
Additions:
zephyr: module: Add zephyr module file
trusted-firmware-m: platform: lpcxpresso55s69: Update SDK

https://git.trustedfirmware.org/TF-M/tf-m-tests.git
Upstream: 51ff2bdfae043f6dd0813b000d928c4bda172660
Additions:
zephyr: module: Add module file for tf-m-tests

https://github.com/ARM-software/psa-arch-tests.git
Upstream: 60faad2ead1b967ec8e73accd793d3ed0e5c56bd
Additions:
zephyr: module: Add module file for psa-arch-tests
psa-arch-tests: Allow overriding of toolchain file

The organization of folders remain the same with the following
exceptions:
Moved:
root folder moved from modules/tee/tfm to modules/tee/tf-m to avoid
problems with west update.
zephyr/module.yml to trusted-firmware-m/zephyr/module.yml and
${ZEPHYR_TRUSTED_FIRMWARE_M_MODULE_DIR} points to what was previously
${ZEPHYR_TRUSTED_FIRMWARE_M_MODULE_DIR}/trusted-firmware-m.
Added:
psa-arch-tests/zephyr/module.yml and ${ZEPHYR_PSA_ARCH_TESTS_MODULE_DIR}
tf-m-tests/zephyr/module/ and ${ZEPHYR_TF_M_TESTS_MODULE_DIR}
Removed:
init-git.sh
README.rst

Fixes: #39353

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]
Much better!

For a big change like this where it is easy to make a mistake the test ~/ncs/zephyr/samples/tfm_integration/tfm_regression_test/ should be run.

**Comment by joerchan** [comment]
> a small observation in `tf-m-tests` repo. There seems to be a missing newline in the yaml file.
> 
> [zephyrproject-rtos/tf-m-tests@8728f5e#r58336047](https://github.com/zephyrproject-rtos/tf-m-tests/commit/8728f5ed6b1879eb7f876f2fc6937a480340155f#r58336047)

Thanks, fixed now.

**Review by tejlmand — CHANGES_REQUESTED** [review]
having some concerns of placing a new project inside an abandoned git repo.

**Review by tejlmand — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]

**Comment by microbuilder** [comment]
Thanks for putting this together. Tested, and seems good here.

**Review by microbuilder — CHANGES_REQUESTED** [review]
> Thanks for putting this together. Tested, and seems good here.

Sorry, I take that back. There seems to be an issue with finding the cross compiler on some platforms.

Testing with OS X and the Zephyr SDK or a GNU Embedded toolchain, regression tests work fine:

```bash
$ west build samples/tfm_integration/tfm_regression_test/ -p -b mps2_an521_ns -t run
```

But the PSA Arch tests are failing looking for the cross compiler:

```bash
$ west build zephyr/samples/tfm_integration/tfm_psa_test/ -p -b mps2_an521_ns -t run -- \
  -DCONFIG_TFM_PSA_TEST_STORAGE=y
...
[98/457] Performing install step for 'psa_generate_database'
FAILED: app/psa_api_tests/src/psa_generate_database-stamp/psa_generate_database-install /Users/kevin/Linaro/zephyr/zephyr/build/tfm/app/psa_api_tests/src/psa_generate_database-stamp/psa_generate_database-install 
cd /Users/kevin/Linaro/zephyr/zephyr/build/tfm/app/psa_api_tests/src/psa_generate_database-build && /usr/local/Cellar/cmake/3.21.2/bin/cmake --build . --target install && /usr/local/Cellar/cmake/3.21.2/bin/cmake -E touch /Users/kevin/Linaro/zephyr/zephyr/build/tfm/app/psa_api_tests/src/psa_generate_database-stamp/psa_generate_database-install
[1/5] [PSA] : Creating generator source /Users/kevin/Linaro/zephyr/zephyr/build/tfm/app/psa_api_tests/targetConfigGen.c
[2/5] Building C object CMakeFiles/TargetConfigGen.dir/Users/kevin/Linaro/zephyr/zephyr/build/tfm/app/psa_api_tests/targetConfigGen.c.o
[3/5] Linking C executable TargetConfigGen
FAILED: TargetConfigGen 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/TargetConfigGen.dir/Users/kevin/Linaro/zephyr/zephyr/build/tfm/app/psa_api_tests/targetConfigGen.c.o -o TargetConfigGen   && :
ld: library not found for -lSystem
```

We tried to resolve this previously with:

- https://github.com/ARM-software/psa-arch-tests/pull/268

Which was eventually replaced with:

- https://github.com/ARM-software/psa-arch-tests/pull/276

But this no longer seems to work, or was somehow lost in translation moving to separate repos, or may simply never have worked and slipped through the cracks. I'm guilty of generally only testing with the regression tests, not the PSA test suites.

Some further investigation required here to figure out why this isn't working, and what fix is required.

**Comment by microbuilder** [comment]
The `INHERIT` changes seem to have been made: https://github.com/zephyrproject-rtos/zephyr/commit/e3b3afa7a5a54af480670a8e96bb0933822a8800

@SebastianBoe What platform, etc., are you using that this passes on? I guess Linux + Zephyr SDK?

**Comment by SebastianBoe** [comment]
Unable to reproduce the issue with Linux+gnuarmemb.

**Comment by microbuilder** [comment]
> Unable to reproduce the issue with Linux+gnuarmemb.

Thanks. The INHERIT mechanism doesn't seem to work on OS X (with gnuarmemb or Zephyr SDK), and I assume Windows as well. I'll try to dig into this on the OS X side to see why it's not passing the toolchain info up.

**Comment by microbuilder** [comment]
@SebastianBoe This feels like an entirely different issue, to be honest, and I don't want to block this PR with something that is out of scope here. I'll try to figure out why `INHERIT` isn't working on OS X, but file a new issue if the problem is more complex than expected, or a separate PR if I find a fix quickly here. It isn't related to the change to splitting the repos up, though.

**Review by microbuilder — APPROVED** [review]

**Pull request merged**
