### PR TITLE
Add options needed for GDEM029T94 initialization

### PR DESCRIPTION
**Pull request by korneliuszo**
Supersets #49377

### CODE REVIEW

**Comment by carlescufi** [comment]
@korneliuszo please do not close Pull Requests. Instead, edit your commits with `git rebase -i` and `git commit --amend` and then force-push with `git push -f`.

**Comment by carlescufi** [comment]
@korneliuszo thanks!
Note that the twister-build issues are not related to your PR and will be fixed shortly.

**Comment by stephanosio** [comment]
Rebased to fix CI failure

**Comment by carlescufi** [comment]
@galak @gmarull @mbolivar-nordic could you take a look?

**Review by jfischer-no — CHANGES_REQUESTED** [review]
The commit title should be like: "drivers: ssd16xx: ..."
Commit messages still not explain the reason for the changes.
IIRC, there is work in opposite direction, see #48163

**Comment by korneliuszo** [comment]
#48163 looks better than my patchset, rebased needed by me patches on this pull request.

**Comment by mbolivar-nordic** [comment]
> #48163 looks better than my patchset, rebased needed by me patches on this pull request.

So are you going to close this?

**Comment by korneliuszo** [comment]
Closing

**Pull request closed without merging**
