### PR TITLE
logging: use LOG_MODE_MINIMAL instead of LOG_MINIMAL in code

### PR DESCRIPTION
**Pull request by dcpleung**
`CONFIG_LOG_MINIMAL` is simply being used to enable
`CONFIG_LOG_MODE_MINIMAL` as a redirection. Therefore, it is
better for code to use `CONFIG_LOG_MODE_MINIMAL` so it is more
consistent with other modes.

### CODE REVIEW

**Comment by hongshui3000** [comment]
@dcpleung
I found that the following two configurations may cause the compilation to fail.
Because the function in the macro is not optimized, but the function itself is not implemented due to the cmakefile file selection.
1.CONFIG_LOG=n ，CONFIG_NO_OPTIMIZATIONS=y
2.CONFIG_LOG=y，CONFIG_LOG_MODE_MINIMAL = y CONFIG_NO_OPTIMIZATIONS=y

**Comment by nordic-krch** [comment]
`LOG_MINIMAL` was kept to allow using `select LOG_MINIMAL` because you cannot do `select LOG_MODE_MINIMAL`. So `LOG_MINIMAL` is used internally as a flag that indicates feature being enabled.

I was thinking about approach with options like `LOG_PREFER_MODE_MINIMAL` (removing `LOG_MINIMAL`) and having minimal mode as default in `LOG_MODE` choice when that option is set. After that logging would use `LOG_MODE_MINIMAL` as internal flag for that feature.

**Comment by dcpleung** [comment]
That is similar to what I am doing here. The difference is that selecting `LOG_MINIMAL` would disallow other modes to be selected. Otherwise, there would be situation where `LOG_MINIMAL` is enabled, but non-minimal mode is selected.

**Comment by jukkar** [comment]
I just wonder if we could get at least the commit `testsuite: Allow user to override minimal logging` from this PR merged to 2.6. I got bitten again this when debugging some networking issue in the tests.

**Comment by nordic-krch** [comment]
@jukkar it's been merged here #34883

**Comment by jukkar** [comment]
> it's been merged here #34883

Thanks :+1: I missed it.

**Pull request closed without merging**
