### PR TITLE
intel_adsp: ace: add firmware loading tool

### PR DESCRIPTION
**Pull request by nashif**
Add python script for loading intel_adsp ACE FW into hardware.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Nice, I'll give this a try as soon as I get a moment to rebuild a kernel (no huge pages in chromeos).

FWIW, while it's not super important for a per-device script, this is an awful lot of cut/paste from cavstool and it would be nice to see those unified.

**Comment by andyross** [comment]
It works!  But it only gets as far as the boot banner.  Is there any magic I need to do?  I haven't looked at all.  Does the console handler gets swapped to something non-winstream maybe?   I know there are a bunch of log backends for this device now; SOF itself is using mstream via debugfs, which almost certainly isn't going to work with a python loader.  Does the SOF driver in the kernel need to be unloaded?  etc...

**Comment by marc-hb** [comment]
FWIW, `mtrace-reader.py` is the only thing currently used by Intel in the main SOF branch: https://github.com/thesofproject/sof/commit/13ba5fe90ccb9f

It's very likely different for other vendors.

Recent logs example: https://sof-ci.01.org/sofpr/PR8592/build883/devicetest/index.html

**Comment by andyross** [comment]
mtrace works just fine[1], it's just a poor fit for Zephyr because it demands a kernel driver on the other side.

[1] Though personally I think logging to anything that isn't a shared memory window is fragile as it relies on the firmware OS stack to stay functional enough to manage the transfer -- a hung or panicked kernel still has its logs available for reading with winstream, not so much anything involving DMA.  Also DMA requires a reader on the other side where shared memory is stateless.  If you forget to launch your reader, the buffer is still there.  99% of audio firmware work would work fine with it, but for kernel problems, leave me my buffers.

**Review by kv2019i — APPROVED** [review]
Thanks @nashif ! I agree it would be nice to de-duplicate this with cavstool.py , but given there are some not-so-obvious small differences, this is not a trivial thing to do, so better to have this available.

@andyross This should work just before, winstream log is available as long as it's enabled in the build.

**Comment by andyross** [comment]
> @andyross This should work just before, winstream log is available as long as it's enabled in the build.

Right.  To be clear: winstream is there and working, because I see the firmware load and the boot banner appear (so, like basically everything this script is responsible for is working).  But after that I get no output, implying that something broke.  My guess was that a non-winstream log backend was coming in and stomping on the printk hook, but again I haven't had time to debug.  Regardless this script itself works great and should merge.

**Comment by nashif** [comment]
> Right. To be clear: winstream is there and working, because I see the firmware load and the boot banner appear (so, like basically everything this script is responsible for is working).

hmm, works fine here:

```
INFO:ace-fw:ACK IPC
INFO:ace-fw:Starting DMA, FW_STATUS = 0xffffffff
INFO:ace-fw:Waiting 2 seconds for firmware handoff, FW_STATUS = 0xffffffff
INFO:ace-fw:FW alive, FW_STATUS = 0x5
INFO:ace-fw:ACE firmware load complete
--
*** Booting Zephyr OS build zephyr-v3.5.0-3058-ged976be41707 ***
thread_a: Hello World from cpu 0 on intel_adsp_ace15_mtpm!
WARNING:ace-fw:acetool: Unrecognized IPC command 0x1b080000 ext 0x0
thread_b: Hello World from cpu 0 on intel_adsp_ace15_mtpm!
thread_a: Hello World from cpu 0 on intel_adsp_ace15_mtpm!
thread_b: Hello World from cpu 0 on intel_adsp_ace15_mtpm!
thread_a: Hello World from cpu 0 on intel_adsp_ace15_mtpm!
thread_b: Hello World from cpu 0 on intel_adsp_ace15_mtpm!
thread_a: Hello World from cpu 0 on intel_adsp_ace15_mtpm!
```

**Comment by andyross** [comment]
Hah, yeah, I decided to try something other than hello_world and it's fine.  What actually happened is that hello_world started using stdio printf() and not printk() a while back, and ace15 doesn't have the console backend set up apparently.  This has burned me a few times now, IMHO that patch is sort of a mistake.

**Review by softwarecki — APPROVED** [review]

**Comment by nashif** [comment]
> Hah, yeah, I decided to try something other than hello_world and it's fine. What actually happened is that hello_world started using stdio printf() and not printk() a while back, and ace15 doesn't have the console backend set up apparently. This has burned me a few times now, IMHO that patch is sort of a mistake.

yep, I am all for reverting it back to what it was before.

**Comment by andyross** [comment]
> yep, I am all for reverting it back to what it was before.

Or at least add a test so that platforms don't forget to wire it up.  Anything with a printk char_out() hook can be wired to stdio with minimal fuss, it's just that nothing checks it so you get situations like this where hello_world fails to say hello.

**Pull request merged**
