### PR TITLE
use prep_c for xtensa to align with other architectures

### PR DESCRIPTION
**Pull request by nashif**
- **xtensa: remove mention of crt0-app.S**
- **xtensa: introduce prep_c for xtensa**
- **xtensa: adapt soc code to use prep_c**
- **xtensa: move arch_kernel_init code into prep_c**

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Review by uLipe — DISMISSED** [review]

**Review by andyross — DISMISSED** [review]

**Review by sylvioalves — DISMISSED** [review]

**Review by tmleman — CHANGES_REQUESTED** [review]
SOF CI reports a FW exception in tests with this PR. From what I see, the tests on power flow from D3 are failing.

https://github.com/thesofproject/sof/pull/9345

**Comment by marc-hb** [comment]
Thanks @tmleman for testing this, great catch.

I just got confirmation from @ranj063 that her recent "DSP Ops tester" work could be useful to debug this panic. It requires this Linux kernel patch:
- https://github.com/thesofproject/linux/pull/4874

The corresponding test script is here:
- https://github.com/thesofproject/sof-test/commit/5419b42ff162a75dec0a4230b5d6012b23cb39b9

**Comment by nashif** [comment]
> SOF CI reports a FW exception in tests with this PR. From what I see, the tests on power flow from D3 are failing.

should be fix now.

**Comment by nashif** [comment]
@tmleman please have another look.

**Review by tmleman — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
