### PR TITLE
shell: Added assert to verify that columns != 0

### PR DESCRIPTION
**Pull request by koffes**
Assert to check columns. Averts a potential divide by zero

### CODE REVIEW

**Review by andvib — APPROVED** [review]

**Comment by jakub-uC** [comment]
@koffes  May you please also update:
`SHELL_DEFAULT_TERMINAL_WIDTH` and add there a range: 1-65535?

**Review by jakub-uC — DISMISSED** [review]

**Comment by jakub-uC** [comment]
The `SHELL_DEFAULT_TERMINAL_WIDTH` is already a Kconfig option. My proposal is to add a range 1-65535 to it.

**Review by jakub-uC — APPROVED** [review]

**Comment by koffes** [comment]
The confusion came from this both being a define and a Kconfig. Changes have been appended and review re-requested.

**Review by alexsven — APPROVED** [review]

**Comment by koffes** [comment]
@jakub-uC : Could you please re-approve?

**Review by jakub-uC — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
