### PR TITLE
drivers: sensor: adxl367: fix #68879

### LINKED ISSUE #68879: ADXL367 adxl367_fifo_setup incorrect param type
**Describe the bug**
The `sets_nb` param in the function `adxl367_fifo_setup` in the file `drivers/sensor/adxl367/adxl367.c` is of type `uint8_t` but it should be of type `uint16_t` given that the function `adxl367_set_fifo_sample_sets_nb` takes in this parameter and is declared as `uint16_t` for that function.

Please also mention any information which could help others to understand
the problem you're facing:
 - nRF52832
- Manually setting the sample count using an I2C command

**Expected behavior**
Calling the function `adxl367_fifo_setup` with `sets_nb` with a value greater than 255 should not trigger an overflow.

**Impact**
Annoyance

### PR DESCRIPTION
**Pull request by borob-engineering**
changed data type of mentioned parameter to uint16_t to avoid overflows.
fix for #68879

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]
Need to rebase and resolve conflicts

**Review by teburd — DISMISSED** [review]

**Comment by aescolar** [comment]
Rebase needed

**Comment by fabiobaltieri** [comment]
@borob-engineering can you rebase please? Also while at it, could you use a descriptive comment on the commit message? the issue number is ok for the pull request comment but means nothing in the git history once the project is checked out and forked anywhere other than in the main repository on GitHub so those references should be avoided.

**Comment by teburd** [comment]
@fabiobaltieri good catch!

**Comment by fabiobaltieri** [comment]
> It is good to append "Fixes #issue_number" to the end of the commit description as GitHub has the nice behaviour of closing the issue when the PR is merged.

I normally recommend against using that format (hash-number) in the actual commit message for the same reason, that reference only makes sense in this specific fork of the repository, in this org.

What I would suggest instead is:
- you can use the "Fixes #number" in the PR description (not the commit message, the comment that you write in the GitHub UI when you open the pull request). The PR is hard bound to this fork of the repo so fine to use the short format there, and that does indeed achieve what Nick describe about automatically closing the issue. Or:
- if you really want to leave a reference to issue number in the commit itself (because it adds more details or there's some useful troubleshooting data or whatever), use the full URL, which identifies the issue in the specific org, and you can use the "Link" git tag for that, which these days is extremely common in kernel.org ([random example](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=df04b152fca2d46e75fbb74ed79299bc420bc9e6)), and is occasionally used in Zephyr as well (try `git log --grep Link:`)

**Comment by nashif** [comment]
> * you can use the "Fixes #number" in the PR description (not the commit message, the comment that you write in the GitHub UI when you open the pull request).

who does that these days? Not sure how many pull requests I have done, I never do this. For me it is all done using commit messages. I then use github client which creates the pr and puts the commit messages in the PR body and if it has a "fixes \#" it appears in the PR....

Also note that your recommendation here conflicts with what we have the contribution guidelines, see
https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-body

image

**Comment by nashif** [comment]
needs a rebase

**Review by nashif — CHANGES_REQUESTED** [review]
Please fix the commit message, see https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

**Pull request closed without merging**
