### PR TITLE
boards: arc: nsim: fix yaml identifier for nsim_em_em7d_v22

### PR DESCRIPTION
**Pull request by IRISZZW**
fix yaml identifier for nsim_em_em7d_v22 configuration

### CODE REVIEW

**Review by abrodkin — DISMISSED** [review]
Could you please elaborate a bit on:
1. How did you find that?
2. Why that was not caught before (was this config ever built & run)?
3. What happens w/o proposed change?

**Comment by IRISZZW** [comment]
> Could you please elaborate a bit on:
> 
> 1. How did you find that?
> 2. Why that was not caught before (was this config ever built & run)?
> 3. What happens w/o proposed change?

When I run sanity check script for nsim_em boards with arcmwdt toolchain in our server, it will filter out all tests and report:
`Not supported by the toolchain`
https://github.com/zephyrproject-rtos/zephyr/blob/6c53e9331854a3485112685c47b77852f3576224/scripts/sanity_chk/sanitylib.py#L2876

But I can not reproduce it in my virtual machine, it works well.

First I guess this maybe caused by some wrong envionment variables, then I check it carefully. but there seems no big difference which may caused the failure.

Then I debug with sanity check script:
https://github.com/zephyrproject-rtos/zephyr/blob/6c53e9331854a3485112685c47b77852f3576224/scripts/sanity_chk/sanitylib.py#L2874

 `plat.supported_toolchains` should be `['arcmwdt', 'zephyr']` , as we set in nsim_em.yaml file:

https://github.com/zephyrproject-rtos/zephyr/blob/6c53e9331854a3485112685c47b77852f3576224/boards/arc/nsim/nsim_em.yaml#L6-L8

But when I print the value of 'plat.supported_toolchains', it shows only support `zephyr` toolchain.

https://github.com/zephyrproject-rtos/zephyr/blob/6c53e9331854a3485112685c47b77852f3576224/scripts/sanity_chk/sanitylib.py#L2598-L2606

the codes above read all yaml files in board root folder, and store in `self.platforms`, and 
https://github.com/zephyrproject-rtos/zephyr/blob/6c53e9331854a3485112685c47b77852f3576224/scripts/sanity_chk/sanitylib.py#L2775-L2776

platform_filter use the key words `name` which get from

https://github.com/zephyrproject-rtos/zephyr/blob/6c53e9331854a3485112685c47b77852f3576224/scripts/sanity_chk/sanitylib.py#L1371

So, I check the yaml files with identifier, then find the errors.

**Comment by IRISZZW** [comment]
With out this fix, we can't run sanity check for `nsim_em_em7d_v22`, 
and it will also cause sainty check for `nsim_em` failed sometime, 
it depends on the read order of `nism_em.yaml `and `nsim_em_em7d_v22.yml` file:
`nism_em.yaml ` first in my server which results failure.
`nsim_em_em7d_v22.yml` first in my virtual machine which results warning but get right results.

**Review by ruuddw — APPROVED** [review]
copy-paste mistake

**Review by nashif — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]

**Pull request merged**
