### PR TITLE
subsys: cpp: support standards with GNU extensions

### PR DESCRIPTION
**Pull request by Damian-Nordic**
Matter project (https://github.com/project-chip/connectedhomeip) requires `-std=gnu++14` C++ standard and we currently have to manually override the standard for certain CMake build targets.

Add support for `-std=gnu++XX` C++ standards.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

### CODE REVIEW

**Review by stephanosio — COMMENTED** [review]
> we currently have to manually override the standard for certain CMake build targets.

That is arguably a good thing because we do not want to encourage the use of the GNU extensions in any way, especially noting that our long term plan is to support many different toolchains that may or may not support the GNU extensions.

Some thoughts on this:

1. GNU extensions are not really "standards," but non-standard extensions to the standard C++. In that sense, should these configs really be under `prompt "C++ Standard`?
2. What do we do when, for instance, `STD_GNUPP11` is selected and the toolchain in use does not support such a thing?

**Comment by Damian-Nordic** [comment]
>     1. GNU extensions are not really "standards," but non-standard extensions to the standard C++. In that sense, should these configs really be under `prompt "C++ Standard`?

Right, but compilers accept GNU extensions using `-std` flag which I believe stands for "standard" ;). I guess in the context of compilers it's common to think of "standard" as of a set of language features rather than any formal notion.

>     2. What do we do when, for instance, `STD_GNUPP11` is selected and the toolchain in use does not support such a thing?

Hmm. Isn't it the same as when we select `STD_CPP20` and the toolchain does not support such a thing? I think we already allow to specify standards which I'm pretty sure are not supported by all toolchains used to build Zephyr codebase.

**Comment by tejlmand** [comment]
> That is arguably a good thing because we do not want to encourage the use of the GNU extensions in any way, especially noting that our long term plan is to support many different toolchains that may or may not support the GNU extensions.

agree on this.



> > 1. GNU extensions are not really "standards," but non-standard extensions to the standard C++. In that sense, should these configs really be under `prompt "C++ Standard`?
>
> Right, but compilers accept GNU extensions using -std flag which I believe stands for "standard" ;). I guess in the context of compilers it's common to think of "standard" as of a set of language features rather than any formal notion.

From gcc [docs](https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/C-Dialect-Options.html#C-Dialect-Options)
> -std=
> ...
> When a base standard is specified, the compiler accepts all programs following that standard plus those using GNU extensions that do not contradict it. 

so if `c++14` is not good enough but `gnu++14` is really required for that project, then it sounds like we should really be careful.

I would like to know why `-std=c++14` which is supported through [CONFIG_STD_CPP14](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_STD_CPP14.html) is not sufficient in this case.

Especially because the Matter project is not part of Zephyr manifest, we should be careful on this, as we generally prefer sticking with official standards, not GNU extension that  contradicts them.

**Comment by Damian-Nordic** [comment]
What's exactly the risk for Zephyr project in allowing users to easily build Zephyr with `gnu++` dialect? I think throwing obstacles in their path won't prevent them from using whatever flags they prefer by doing some CMake magic (as we do in Matter), but will just make their life a bit harder (in the name of what?). If there wasn't a valid use case for `gnu++` why would compiler developers bother implementing them?

I think Matter project decided to use `gnu++` for no big reasons - it just enables some extra functions, such as `strnlen` etc. And since no other platform has any issue with that it was probably no-brainer. We can continue maintaining our solution for overriding the standard, so I won't argue about that long, but I just thought we could make it a bit cleaner and I can't tell I understand the reasons for not doing that :)

**Comment by tejlmand** [comment]
> What's exactly the risk for Zephyr project in allowing users to easily build Zephyr with gnu++ dialect? 

Did you read the part of: `plus those using GNU extensions that do not contradict it.`
This basically means that if you have to use `gnu++14`, then you get some extensions which can contradicts the official c++14 standard.
So if code today expects `c++14` in it's official form, then how do you ensure that code still works as expected when switching to `gnu++14` ?

Besides that, the main risk I see is code expecting a specific GNU extension and thereby making that code even harder to work with non-GCC based toolchains.

There is already a lot of cleanup ahead for ARM Compiler 6 (armclang) wrt. source code.
We shouldn't blindly do more, without full overview of side-effects.

Also remember, when setting this flag, all Zephyr libraries will be compiled with that flag.

> it just enables some extra functions, such as `strnlen` etc. 

`strnlen` is from the C standard, and is still available when using `c++14`, so that cannot be the reason.

> I think Matter project decided to use gnu++ for no big reasons - 

So, are you sure they won't compile with `c++14` then ?

>  We can continue maintaining our solution for overriding the standard

If you really would like to build all C++ code using `gnu++14`, then you may propose to add a symbol name here:
https://github.com/zephyrproject-rtos/zephyr/blob/b374dc6a7fd8f841394ad6cf2364c7ceef05f3c7/subsys/cpp/Kconfig#L13
Like this:
```
choice CPP_STD_CHOICE
```
that will allow you to add more choices in your downstream project.
And then this `else()` should be adjusted so that it allows downstream users to add custom standards, if they so like:
https://github.com/zephyrproject-rtos/zephyr/blob/b374dc6a7fd8f841394ad6cf2364c7ceef05f3c7/CMakeLists.txt#L224-L225

Of course it will then be your own responsibility to ensure that Zephyr builds correctly with any custom standard.

> I think Matter project decided to use gnu++ for no big reasons 

I think I need a much better reason to start officially supporting and bugfixing Zephyr and modules when a given gnu++ extensions is enabled, without even knowing why this was needed to be supported in the first place.

**Comment by tejlmand** [comment]
> `strnlen` is from the C standard, and is still available when using `c++14`, so that cannot be the reason.

actually I was wrong here.
`strnlen` is from POSIX.1-2008, not the C standard, although C11 annex K has this mentioned.
So relying on a GNU extension to have a posix function available might even be worse.

**Comment by tejlmand** [comment]
> `strnlen` is from POSIX.1-2008, not the C standard, although C11 annex K has this mentioned.


We have `strnlen` available when using minimal libc:
https://github.com/zephyrproject-rtos/zephyr/blob/b374dc6a7fd8f841394ad6cf2364c7ceef05f3c7/lib/libc/minimal/source/string/string.c#L126

but it's not part of `newlib`, so when building code that uses `strnlen` and `newlib` user's will see:
```
$ cmake .... -DCONFIG_NEWLIB_LIBC=y
$ ninja -Cbuild
...
/projects/github/ncs/zephyr/tests/subsys/cpp/cxx/src/main.cpp: In function 'void test_main()':
/projects/github/ncs/zephyr/tests/subsys/cpp/cxx/src/main.cpp:73:10: error: 'strnlen' was not declared in this scope; did you mean 'strlen'?
   73 |  int a = strnlen(str, 255);
      |          ^~~~~~~
      |          strlen
[86/159] Building C object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/fault.c.obj
```
@stephanosio this might be worth looking into.

**Comment by Damian-Nordic** [comment]
> Did you read the part of: `plus those using GNU extensions that do not contradict it.` This basically means that if you have to use `gnu++14`, then you get some extensions which can contradicts the official c++14 standard. So if code today expects `c++14` in it's official form, then how do you ensure that code still works as expected when switching to `gnu++14` ?
> 
> Besides that, the main risk I see is code expecting a specific GNU extension and thereby making that code even harder to work with non-GCC based toolchains.
> 
> There is already a lot of cleanup ahead for ARM Compiler 6 (armclang) wrt. source code. We shouldn't blindly do more, without full overview of side-effects.

I think majority of Zephyr developers uses C, not C++, and during the work on Matter I've hit on Zephyr code which doesn't work in C++ several times. For example, Zephyr codebase contains a lot of macros using compound literals. Thus I didn't have the impression that any C++ standard is officially supported with barely any C++ tests and samples. I just thought the standards available in Kconfig are options which users may use, but Zephyr is primarily C-based and C++ projects must expect a limited support.

> Also remember, when setting this flag, all Zephyr libraries will be compiled with that flag.

Yes. That was the goal.

> I think I need a much better reason to start officially supporting and bugfixing Zephyr and modules when a given gnu++ extensions is enabled, without even knowing why this was needed to be supported in the first place.

Ok. I didn't realize that adding the Kconfig options has that implication. We will continue maintaining the support for gnu++14 in our project.

**Pull request closed without merging**
