### PR TITLE
west.yml: Update hal_stm32 with a fix on the stm32h7 drivers

### LINKED ISSUE #76834: stm32: hal: ospi: dma read not working
There is an bug in the ospi hal that was fixed 3 month ago:

https://github.com/STMicroelectronics/stm32h7xx_hal_driver/commit/cff8a947c901b8db3f94f731e3aef516c7c60d8b

Please update the stm32cube h7 hal.

### PR DESCRIPTION
**Pull request by FRASTM**
stm32h7xx_hal driver partial update to v1.11.3

Fixes [76834](https://github.com/zephyrproject-rtos/zephyr/issues/76834)

### CODE REVIEW

**Comment by FRASTM** [comment]
set ../modules/hal/stm32/stm32cube  to c4099c229323f305eef75ff6ba93ee9b89827581

**Comment by FRASTM** [comment]
change hal_stm32 revision SHA1 as hal_stm32 is now updated

**Comment by erwango** [comment]
Can you update commit description, so that it is clear that you're also including https://github.com/zephyrproject-rtos/zephyr/pull/78241 (which is fine)

**Comment by FRASTM** [comment]
rebase on ca09a4b91c4a977d743837419f11d7c9d373364e

Includes the https://github.com/zephyrproject-rtos/zephyr/pull/78249
Includes the https://github.com/zephyrproject-rtos/zephyr/pull/78241

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Pull request merged**
