### PR TITLE
arch/arm: Fix THREAD_MONITOR entry struct

### LINKED ISSUE #7541: arm: struct k_thread->entry is overwritten once the thread is scheduled
The `struct __thread_entry *entry` pointer in `struct k_thread` is useless for thread monitoring because it is located at the top of the stack and is overwritten by the first push when entering the thread.
1. `pInitCtx` is allocated at the top of the stack
2. `struct __thread_entry *entry` points to `pInitCtx`
3. When swapping the thread, `pInitCtx` is used and then popped
4. Now `struct __thread_entry *entry` points to some free stack that will be overwritten soon

This problem is easy to spot while trying to use thread->entry->pEntry to get the entry point of each thread, either in a GDB script or using some C code.

Idea to fix this issue (if CONFIG_THREAD_MONITOR):
- Reserve some space for `struct __thread_entry` at the bottom of the stack (or just after the sentinel if any)
- Copy part of `pInitCtx` (entry point + arguments) to this space and make `entry` point to it

Would it be acceptable to reserve some space at the bottom of each stack for this purpose?

### PR DESCRIPTION
**Pull request by andyross**
On ARM, the __thread_entry struct pointer used when
CONFIG_THREAD_MONITOR is enabled was pointing to the initial exception
stack frame.  That's not right: even though this contains all the same
info, it's not layout-compatible with the API struct.  And once the
thread starts running, the ESF gets unwound and the memory recliamed
for the stack frame of the entry function!

Stuff the __thread_entry struct into its own memory at the bottom of
the stack like the other architectures do.  Fixes #7541

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by lpereira — APPROVED** [review]
LGTM.   This seems to affect xtensa as well.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andyross** [comment]
Should work compatibly on xtensa asm2, at least the code looks like it works.  Again, though, doesn't look like we ever tested the contents of the __thread_entry struct well, so I wouldn't be shocked to find bugs basically anywhere.

**Review by agross-oss — CHANGES_REQUESTED** [review]
What about the user mode thread setup?  We scrub the stack fully when we transition, does this need to be set up again?

**Comment by andyross** [comment]
Yeah, this won't be particularly compatible with userspace -- there's no way to trust the data you get if you put it on the thread's own stack.  But then the API is just a debug aid (and a pretty primitive one at that -- just a linked list of threads that stores a copy of their entry functions and the three parameters) for traditional apps.  Long term, we'd surely need some kind of process enumeration abstraction (heh, process IDs, command line memory, parents, process groups, session identifiers...) that works better across a protection boundary.

**Comment by andyross** [comment]
Heh, reading that back I was way to wordy:

All this is doing is fixing a bug on ARM where memory that should be preserved gets clobbered on thread entry.  I agree the thread enumeration debug API needs to be reworked, but that's not really in scope for #7541.

**Comment by andyross** [comment]
@agross-linaro , any chance to remove the -1 pending a redesign?  It remains a fix for non-MMU applications and doesn't break anything under MMU that wasn't broken already.

**Review by agross-oss — APPROVED** [review]
questions addressed during discussion.  looks ok

**Comment by andrewboie** [comment]
We should just embed the thread_entry struct directly in struct k_thread instead of storing a pointer to some memory on the stack.

**Comment by andyross** [comment]
Don't disagree there, it's a semi-crazy API.  Frankly it doesn't really do much anyway.  The linked list of threads is useful (and in struct thread already).  Storing the initial entry point and arguments is less so, anyone who cares can stash that stuff while debugging trivially.

My guess is that on some architecture, it was possible to finesse things such that the values that had to be on the stack anyway could share storage.  That doesn't work here because of the way the ESF unwinds.  Probably could be made to work on x86 as long as the entry is cdecl (but a quick read shows it doesn't, and it wouldn't work in iamcu anyway).  No idea.

**Pull request merged**
