### PR TITLE
Zephyr Thread tests and coverage improvements

### PR DESCRIPTION
**Pull request by ramakrishnapallala**

### CODE REVIEW

**Comment by nashif** [comment]
now this is not really improving coverage :)

**Comment by ramakrishnapallala** [comment]
@nashif I simply removed an unused function. This should increase the coverage right?

**Comment by nashif** [comment]
> @nashif I simply removed an unused function. This should increase the coverage right?

in theory yes, not sure what is going on

**Comment by ramakrishnapallala** [comment]
@nashif I checked locally again, it works properly.

This patch improves the coverage of thread.c by 3%

If you can rerun the codecov.io we should see that in github as well.

codecov.io is not being triggered if we update the patches.

**Comment by nashif** [comment]
recheck

**Comment by nashif** [comment]
recheck

**Review by tyrantlizard77 — APPROVED** [review]
Minor change. Shouldn't hurt anything.

**Pull request merged**
