### PR TITLE
Bluetooth: Controller: Add BT_CTLR_EVENT_OVERHEAD_RESERVE_MAX Kconfig

### PR DESCRIPTION
**Pull request by cvinayak**
Add BT_CTLR_EVENT_OVERHEAD_RESERVE_MAX Kconfig to allow the omit of EVENT_OVERHEAD_START_US and EVENT_OVERHEAD_END_US in the time reservation calculations.

### CODE REVIEW

**Review by Thalley — DISMISSED** [review]

**Review by mtpr-ot — DISMISSED** [review]
Looks OK

**Comment by carlescufi** [comment]
@cvinayak please rebase

**Comment by cvinayak** [comment]
@Thalley and @mtpr-ot Rebased (the Kconfig help text updated, mention of "radio ramp" removed, and clarified that only Peripheral ACL and Peripheral ISO event time reservation is modified by this Kconfig).

**Review by Thalley — APPROVED** [review]

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Pull request merged**
