### PR TITLE
Enable SPI driver for MAX32xxx MCUs

### PR DESCRIPTION
**Pull request by ozersa**
SPI driver implemented and merged onto main by https://github.com/zephyrproject-rtos/zephyr/pull/73496
It just enabled for MAX32690 by above PR..
Then new MAX32 MCUs that listed below merged into upstream/main. This PR enabled SPI for them.

- [MAX32655 EVKIT](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32655evkit.html)
- [MAX32655 FTHR](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32655fthr.html#eb-overview)
- [MAX32670 EVKIT](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32670evkit.html)
- [MAX32672 EVKIT](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32672evkit.html)
- [MAX32672 FTHR](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32672fthr.html)
- [MAX32680 EVKIT](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32680evkit.html)
- [MAX32662 EVKIT](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32662evkit.html)
- [MAX32666 FTHR](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32666fthr.html)
- [MAX32675 EVKIT](https://www.analog.com/en/resources/evaluation-hardware-and-software/evaluation-boards-kits/max32675evkit.html)

@ttmut @hfakkiz  @mertekren  fyi.

DMA related addition is going to be pushed by a dedicated PR.

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]

**Comment by ozersa** [comment]
Conflicts are fixed, and rebased onto main.

**Review by MaureenHelm — DISMISSED** [review]

**Comment by ozersa** [comment]
Rebased to fix conflicts.

**Review by MaureenHelm — COMMENTED** [review]
Let's follow #76601 and do the same for SPI

**Comment by ozersa** [comment]
> Let's follow #76601 and do the same for SPI

Sure, done. thanks.

**Review by MaureenHelm — COMMENTED** [review]
```
tests: i2c: i2c_target_api: Remove duplicate properties

SPI pins are defined in board.dts file to simplify usage
so that no need to redefine it in overlay files

Signed-off-by: Sadik Ozer <sadik.ozer@analog.com>
```
The first line in the commit message has a copy/paste error, need to replace i2c with spi.

**Comment by ozersa** [comment]
> ```
> tests: i2c: i2c_target_api: Remove duplicate properties
> 
> SPI pins are defined in board.dts file to simplify usage
> so that no need to redefine it in overlay files
> 
> Signed-off-by: Sadik Ozer <sadik.ozer@analog.com>
> ```
> 
> The first line in the commit message has a copy/paste error, need to replace i2c with spi.

Fixed.

**Review by MaureenHelm — DISMISSED** [review]

**Review by ubieda — DISMISSED** [review]

**Comment by ozersa** [comment]
Rebased to fix conflicts.

**Review by MaureenHelm — DISMISSED** [review]

**Review by ubieda — DISMISSED** [review]

**Review by tbursztyka — DISMISSED** [review]

**Comment by ozersa** [comment]
Conflicts will be fixed after https://github.com/zephyrproject-rtos/zephyr/pull/73560 being merged.

**Comment by ozersa** [comment]
Rebased to fix conflict and content extended as per of below PRs.
https://github.com/zephyrproject-rtos/zephyr/pull/73560
https://github.com/zephyrproject-rtos/zephyr/pull/73578
https://github.com/zephyrproject-rtos/zephyr/pull/73576
https://github.com/zephyrproject-rtos/zephyr/pull/76627

- SPI enabled for MAX32662/ MAX32666/ MAX32672
- DMA enabled for available part numbers.

**Review by MaureenHelm — DISMISSED** [review]

**Review by ubieda — DISMISSED** [review]

**Comment by MaureenHelm** [comment]
Needs rebase

**Comment by ozersa** [comment]
> Needs rebase

Done, thanks.

**Comment by ozersa** [comment]
DMA related addition removed, it will be pushed as separate PR.

**Review by MaureenHelm — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
