### PR TITLE
dts: xtensa: Fix gpio-reserved-ranges of esp32_wroom_32ue_n4

### PR DESCRIPTION
**Pull request by Peth-typark**
The range of GPIO37-38 is <5 2>

Signed-off-by: Peth-typark <typark0422@pethcare.com>

### CODE REVIEW

**Comment by sylvioalves** [comment]
@Peth-typark, nice catch. Are you able to fix all other .dtsi gpio1 `gpio-reserved-ranges' accordingly? Almost all of them has this wrong value. In case you can't, let me know and I add to this PR. Thanks!

**Comment by Peth-typark** [comment]
Alright. However, the only files I could find are the ones with GPIO range comments, which is the extent of what I can do. I will add the fixes.

**Comment by sylvioalves** [comment]
> Alright. However, the only files I could find are the ones with GPIO range comments, which is the extent of what I can do. I will add the fixes.

Thanks!

**Comment by Peth-typark** [comment]
Sure. That sounds good.

**Review by wmrsouza — APPROVED** [review]

**Comment by Peth-typark** [comment]
@sylvioalves, I’ve updated the PR with the fixes for all the files I could find and squashed the commits into one. Please let me know if there’s anything else I need to address or if further changes are required. Thanks!

**Review by uLipe — APPROVED** [review]

**Comment by kartben** [comment]
@Peth-typark please address compliance issues. Author and sign off entry should be your legal name (First Last)

**Comment by kartben** [comment]
@sylvioalves please take a look

**Review by wmrsouza — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]

**Pull request merged**
