### PR TITLE
headers: Drop extern attribute from functions

### PR DESCRIPTION
**Pull request by ceolin**
Extern attribute is not needed and it is not consistently used across Zephyr headers.

### CODE REVIEW

**Review by d3zd3z — COMMENTED** [review]
It might be worth discussing this at a TSC or architecture level. There isn't anything particularly wrong with having `extern` on function prototypes, as it just makes the default explicit. But it is also redundant, and doesn't really convey any new information.

**Comment by ceolin** [comment]
> It might be worth discussing this at a TSC or architecture level. There isn't anything particularly wrong with having `extern` on function prototypes, as it just makes the default explicit. But it is also redundant, and doesn't really convey any new information.

Yep, the problem IMHO is that its usage is inconsistent in Zephyr. If the intention using it is to make it clear that these functions are public one may assume that the ones not using it are not, which is not correct.

**Review by andyross — APPROVED** [review]
+1 from me, though needless to say I'll be hiding from any kind of official discussion.

I don't know why this style was always there.  It's old, and didn't carry anywhere beyond the ancient kernel files that still use it.

**Review by cfriedt — APPROVED** [review]
Yea please.

**Review by peter-mitsis — APPROVED** [review]
Ideally, I would like to see some of the multi-lined declarations cleaned up so that the code appears tidier, but that is a non-blocking item.

**Pull request merged**
