### PR TITLE
board: acrn : config for the flash runner

### PR DESCRIPTION
**Pull request by enjiamai**
Add config for acrn using sanitycheck automation.
For zephyr ACRN visualization testing, we need to add this file. 

Signed-off-by: Enjiax Mai <enjiax.mai@intel.com>

### CODE REVIEW

**Review by chen-png — APPROVED** [review]
It works for acrn to run sanitycheck script.

**Comment by LeiW000** [comment]
Simply change. It looks good to me.

**Comment by LeiW000** [comment]
@andrewboie could you take look at it? We need it for testing ACRN platform.

**Comment by mm387561** [comment]
@andrewboie @nashif  excuse me, could you please help to check this PR first, this blocks our automated zephyr + ACRN testing. And this modification is simply adding a ACRN board.cmake file . Thank you!

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
