### PR TITLE
samples: bluetooth: update prj.conf (added CONFIG_GPIO)

### PR DESCRIPTION
**Pull request by npal-cy**
Enable GPIO for all ble applications that use additional GPIO (e.g. for LED or button)

### CODE REVIEW

**Comment by Thalley** [comment]
> without this update ble samples which are using GPIO, will return compile error on platforms which by default has disabled GPIO in board (e.g. cyw920829m2evk_02)

But with this change, any board that does not support GPIO will have a build warning. 

If you want to enable it for a specific board the disables it by default, then it should should into a board specific .conf file in the `boards` subdirectory

**Comment by npal-cy** [comment]
> But with this change, any board that does not support GPIO will have a build warning.
No, any board that does not support GPIO will have a build error in anyway, because those samples  currently are using GPIO.

**Comment by Thalley** [comment]
> No, any board that does not support GPIO will have a build error in anyway, because those samples currently are using GPIO. Am i right?

All GPIO related code should be guarded by the Kconfig, so if GPIO=n the samples should still build and run fine. The samples that does not have `CONFIG_GPIO=y` does not require it; it is entirely optional. 

If you want to enable GPIO for a specific board for specific samples, that should be in done in the board-specific files. 

> also, there are couple bt samples which has enabled GPIO:

Not sure if that is intentional or a mistake from the author.

**Comment by npal-cy** [comment]
ok. I will enable CONFIG_GPIO for cyw920829m2evk_02 from board. 
Close this PR

**Pull request closed without merging**
