### PR TITLE
dts: bindings: uart-controller: Set default values UART controller

### PR DESCRIPTION
**Pull request by casparfriedrich**
Add default values for baud rate, data bits, parity and stop bits so drivers can use system wide defaults.

### CODE REVIEW

**Comment by dcpleung** [comment]
I don't think it is a good idea to force a default at the top level. A board level default is more appropriate.

**Comment by casparfriedrich** [comment]
What do you mean by board default? Currently it's a per driver default.

**Comment by dcpleung** [comment]
You are doing this in the basic bindings, which means any driver bindings including this will get the default. If you need a per-driver default, it needs to be done at the driver bindings.

**Comment by casparfriedrich** [comment]
That's the whole point ;-). Currently every driver needs to set those values to a default value in code with something like this:
```
	static struct uart_mcux_data uart_mcux_##n##_data = {		\
		.uart_cfg = {						\
			.stop_bits = UART_CFG_STOP_BITS_1,		\
			.data_bits = UART_CFG_DATA_BITS_8,		\
			.baudrate  = DT_INST_PROP(n, current_speed),	\
			.parity    = UART_CFG_PARITY_NONE,		\
			.flow_ctrl = DT_INST_PROP(n, hw_flow_control) ?	\
				UART_CFG_FLOW_CTRL_RTS_CTS : UART_CFG_FLOW_CTRL_NONE,\
		},							\
	};								\
```
The idea is that this could be simplified to this:
```
	static struct uart_mcux_data uart_mcux_##n##_data = {		\
		.uart_cfg = {						\
			.stop_bits = DT_INST_PROP(n, stop_bits),	\
			.data_bits = DT_INST_PROP(n, data_bits),	\
			.baudrate  = DT_INST_PROP(n, current_speed),	\
			.parity    = DT_INST_PROP(n, parity),		\
			.flow_ctrl = DT_INST_PROP(n, hw_flow_control) ?	\
				UART_CFG_FLOW_CTRL_RTS_CTS : UART_CFG_FLOW_CTRL_NONE,\
		},							\
	};								\
```
without forcing the user user to set every single value for every node. I have another PR to archive the same for `flow_ctrl`
As far as I can see 115200/8n1 seems to be a de facto standard.

**Review by mbolivar-ampere — CHANGES_REQUESTED** [review]
Thanks for the idea. However, I am against this change.

115200 8N1 is the most common setting for serial consoles these days, but this is not a correct use of `default`, and violates our policies regarding this feature in the DT bindings language.

https://docs.zephyrproject.org/latest/build/dts/bindings-upstream.html#rules-for-default-values

**Comment by casparfriedrich** [comment]
I generally agree. The Idea was that in this particular case there is an implicit default here and having the driver to decide what the default is feels rather random.

**Comment by casparfriedrich** [comment]
Rebased

**Comment by casparfriedrich** [comment]
Rebased. But I guess this one can be closed?

**Pull request closed without merging**
