### PR TITLE
mbedtls: update to 3.6.2

### PR DESCRIPTION
**Pull request by tomi-font**
https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.2

### CODE REVIEW

**Review by frkv — APPROVED** [review]
LGTM (pending correct SHA)

**Review by valeriosetti — DISMISSED** [review]
LGTM once the manifest will be properly updated

**Review by Vge0rge — DISMISSED** [review]
Looks good

**Review by kartben — DISMISSED** [review]

**Comment by kartben** [comment]
CI failure is fixed with #79904. Rebase needed

**Review by d3zd3z — DISMISSED** [review]
I've merged mbedtls, so you can push an update with the hash.

**Comment by dkalowsk** [comment]
Changes look good to me, just need to get that hash updated as everyone keeps saying :-)  Thanks for keeping on top of mbedTLS.

**Review by dkalowsk — DISMISSED** [review]

**Review by ceolin — DISMISSED** [review]

**Review by kartben — APPROVED** [review]

**Review by valeriosetti — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]

**Comment by dkalowsk** [comment]
@d3zd3z looking for your approval to move this forward I believe.

**Pull request merged**
