### PR TITLE
drivers: sensor: mcux qdec rework rotation

### PR DESCRIPTION
**Pull request by jeppenodgaard**
This PR does the following:
~~add revolutions channel~~
~~add revolutions to qdec sample~~
~~add revolutions to mcux qdec driver~~
EDIT:
Remove modulus feature and return degrees larger than
count_per_revolution.
This makes it possible to detect if a full rotation has occured.

### CODE REVIEW

**Review by yperess — COMMENTED** [review]
I'm not sold on why this is needed, isn't this just another unit for `SENSOR_CHAN_ROTATION`?

3*PI == 1.5 revolutions

**Comment by jeppenodgaard** [comment]
> I'm not sold on why this is needed, isn't this just another unit for `SENSOR_CHAN_ROTATION`?

This makes it possible to read the number of total rotations.
It also makes it possible to check if more that a complete rotation
has occurred since the last reading. For example if the first reading
gives 10 degrees and the next gives 5 degrees the encoder might
have gone back 5 degrees or it might have gone forward 355 degrees.

> 3*PI == 1.5 revolutions

I am not sure what you mean by this?

**Comment by jeppenodgaard** [comment]
@yperess I need the revolutions and would like to upstream the feature. Please let me know what you would like me to do :)

**Comment by jeppenodgaard** [comment]
@yperess That makes sense. I renamed and reworked the PR.

**Review by MaureenHelm — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
