### PR TITLE
arch: posix: Add support cross-compile

### PR DESCRIPTION
**Pull request by LingaoM**
https://github.com/zephyrproject-rtos/zephyr/issues/70967

### CODE REVIEW

**Review by aescolar — CHANGES_REQUESTED** [review]
As the PR overtook any discussion, I answer here:

>    I what run Zephyr samples on Raspberry Pi 4B(Which is arm linux os),
>    How i can build some zephyr sample run directly run Raspberry Pi?

You would build it in that Raspberry Pi directly. But that sounds like something one would normally not try to do:
native_{sim,posix} is meant as an aid to allow developers to run and test Zephyr in their development machine (or a CI machine). It is, in no way, meant to allow running Zephyr apps in an embedded Linux machine just like if it was running Zephyr. It's drivers and the way everything else is built do not attempt to provide a real time execution environment but a test environment.
Cross-compiling is not just unsupported, it was never meant to be supported. It would open a quite big can of worms. In general nothing in native_sim/posix is meant to cross compile. You use your local libraries and tools to build for your local machine where you test and debug your application and Zephyr.

**Comment by LingaoM** [comment]
We have a need to run Zephyr on ARM Linux, and I also tested this patch and it ran very well.

**Comment by aescolar** [comment]
> We have a need to run Zephyr on ARM Linux, and I also tested this patch and it ran very well.

And why don't you compile it in that ARM Linux machine where you want to run it?

**Comment by LingaoM** [comment]
> > We have a need to run Zephyr on ARM Linux, and I also tested this patch and it ran very well.
> 
> And why don't you compile it in that ARM Linux machine where you want to run it?

I really think so, but our embedded Linux device is resource-constrained and does not have so much storage space and computing power to directly compile Zephyr (Zephyr is quite large, and the tool chain is even larger)

**Comment by aescolar** [comment]
> but our embedded Linux device is resource-constrained and does not have so much storage space and computing power 
So why do you want to run on it?

**Comment by LingaoM** [comment]
> So why do you want to run on it?

Some of our Mijia gateway products need to use Zephyr Bluetooth host. We hope that the protocol stack used on our chip module is the same as the protocol stack used on the gateway, which is easier for us to maintain.

**Comment by LingaoM** [comment]
@aescolar Do you have any questions?

**Comment by aescolar** [comment]
> In addition, we see that Zephyr can not only run on embedded devices, but also on Linux devices, which is exactly the function we want.

Not really.. You can run for development purposes but you should really **not** run it for production. For several reasons, at least: Security wise it is horrible: native_{sim/posix} are going to reproducibly generate the same random numbers; Time will be extremely jittery, and will drift back and forth with load vs real time.

What you are trying to do, is not only not supported but actively discouraged.

**Comment by aescolar** [comment]
@LingaoM please do not remove or edit others' comments

**Pull request closed without merging**
