### PR TITLE
[TOPIC-GPIO] drivers: sensor: lsm9ds0_gyro: convert to new GPIO API

### PR DESCRIPTION
**Pull request by pabigot**
Use the new pin and interrupt configuration API.

NOTE: Because hardware is not available this has been build-tested
only.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

**Review by avisconti — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
@pabigot can you fix CI?

**Comment by pabigot** [comment]
> @pabigot can you fix CI?

Probably not.  The failure is due to #21568, which is fixed but not in the topic branch.  I've restarted shippable, maybe it'll work.

**Comment by pabigot** [comment]
Whoops, no, it's [not fixed](https://github.com/zephyrproject-rtos/zephyr/issues/21568#issuecomment-577040311) just redirected.

**Review by MaureenHelm — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
