### PR TITLE
sanitycheck: point to correct gcov path

### LINKED ISSUE #22534: sanitycheck qemu_x86_coverage problem with SDK 0.11.1
sanitycheck --platform qemu_x86_coverage -C -T tests/lib/onoff/

locally is producing:

```
INFO    - JOBS: 32
INFO    - Building initial testcase list...
INFO    - 1 test configurations selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0
INFO    - 1 of 1 tests passed (100.00%), 0 failed, 0 skipped with 0 warnings in 36.72 seconds
INFO    - In total 1 test cases were executed on 1 out of total 228 platforms (0.44%)
INFO    - Generating coverage files...
geninfo: ERROR: need tool /usr/local/zephyr-sdk/i586-zephyr-elf/bin/i586-zephyr-elf-gcov!
lcov: ERROR: cannot read file /mnt/nordic/zp/zephyr/sanity-out/coverage.info!
lcov: ERROR: cannot read file /mnt/nordic/zp/zephyr/sanity-out/coverage.info!
lcov: ERROR: cannot read file /mnt/nordic/zp/zephyr/sanity-out/coverage.info!
lcov: ERROR: cannot read file /mnt/nordic/zp/zephyr/sanity-out/coverage.info!
genhtml: ERROR: cannot read file /mnt/nordic/zp/zephyr/sanity-out/coverage.info!

lrwxrwxrwx 1 pab pab 17 Feb  4 08:31 /usr/local/zephyr-sdk -> zephyr-sdk-0.11.1
```

`i586-zephyr-elf-gcov` was last seen in SDK 0.10.x, though `x86_64-zephyr-elf-gcov` appears to be in SDK 0.11.x.

### PR DESCRIPTION
**Pull request by nashif**
The SDK has a new path for x86 gcov, point to the new binary. Also, do
not clean artifacts when running coverage.

Fixes #22534

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Review by pabigot — CHANGES_REQUESTED** [review]
I still get a spew of errors just like https://github.com/zephyrproject-rtos/zephyr/issues/22534#issuecomment-583162924 with no generated coverage data.  This is probably part of the problem, but it doesn't fix the issue.

**Comment by nashif** [comment]
> I still get a spew of errors just like [#22534 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/22534#issuecomment-583162924) with no generated coverage data. This is probably part of the problem, but it doesn't fix the issue.

well, this is another bug then that needs to be filed against the SDK. This fixes the issue reported in  #22534.
I tried with this patch and it works for me with 0.11.1:

```
i9:zephyr(gcov_path): sanitycheck -p qemu_x86_coverage -C -T tests/lib/onoff/
INFO    - JOBS: 20
INFO    - Building initial testcase list...
INFO    - 1 test configurations selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0
INFO    - 1 of 1 tests passed (100.00%), 0 failed, 0 skipped with 0 warnings in 33.17 seconds
INFO    - In total 1 test cases were executed on 1 out of total 229 platforms (0.44%)
INFO    - Generating coverage files...
INFO    - HTML report generated: /home/nashif/Work/zephyrproject/zephyr/sanity-out/coverage/index.html
```

**Comment by nashif** [comment]
@pabigot  what lcov version you have? can you try with gcovr? (--coverage-tool gcovr)

**Comment by pabigot** [comment]
> @pabigot what lcov version you have? can you try with gcovr? (--coverage-tool gcovr)
```
tirzah[578]$ lcov --version
lcov: LCOV version 1.13
tirzah[580]$ sanitycheck --platform qemu_x86_coverage -C -T tests/lib/onoff/ --coverage-tool gcovr
Renaming output directory to /mnt/nordic/zp/zephyr/sanity-out.5
INFO    - JOBS: 32
INFO    - Building initial testcase list...
INFO    - 1 test configurations selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0
INFO    - 1 of 1 tests passed (100.00%), 0 failed, 0 skipped with 0 warnings in 36.93 seconds
INFO    - In total 1 test cases were executed on 1 out of total 229 platforms (0.44%)
INFO    - Generating coverage files...
usage: gcovr [options] [search_paths...]
gcovr: error: unrecognized arguments: --json
usage: gcovr [options] [search_paths...]
gcovr: error: unrecognized arguments: --json
usage: gcovr [options] [search_paths...]
gcovr: error: unrecognized arguments: --add-tracefile
tirzah[581]$ gcovr --version
gcovr 4.1

Copyright 2013-2018 the gcovr authors
Copyright 2013 Sandia Corporation
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
```

**Comment by nashif** [comment]
gcovr --version
gcovr 4.2

**Comment by nashif** [comment]
Ok, i was able to reproduce the issue on another host(ubuntu) with lcov 1.13, tried with gcovr 4.2, it works fine, so it is not related to the SDK and we can exclude the SDK, most likely lcov.

**Comment by andrewboie** [comment]
```
apboie@apboie-mobl4:~/projects/zephyr/zephyr (130) nashif/gcov_path
$ cat ~/tools/zephyr-sdk/sdk_version
0.11.1
apboie@apboie-mobl4:~/projects/zephyr/zephyr nashif/gcov_path
$ lcov --version
lcov: LCOV version 1.14
apboie@apboie-mobl4:~/projects/zephyr/zephyr nashif/gcov_path
$ gcovr --version
gcovr 4.2

Copyright 2013-2018 the gcovr authors
Copyright 2013 Sandia Corporation
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
apboie@apboie-mobl4:~/projects/zephyr/zephyr (127) nashif/gcov_path
$ . zephyr-env.sh 
apboie@apboie-mobl4:~/projects/zephyr/zephyr nashif/gcov_path /home/apboie/projects/zephyr/zephyr
$ sanitycheck -p qemu_x86_coverage -C -T tests/lib/onoff/
Renaming output directory to /home/apboie/projects/zephyr/zephyr/sanity-out.1
INFO    - JOBS: 32
INFO    - Building initial testcase list...
INFO    - 1 test configurations selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0
INFO    - 1 of 1 tests passed (100.00%), 0 failed, 0 skipped with 0 warnings in 36.78 seconds
INFO    - In total 1 test cases were executed on 1 out of total 229 platforms (0.44%)
INFO    - Generating coverage files...
geninfo: WARNING: /home/apboie/projects/zephyr/zephyr/sanity-out/qemu_x86_coverage/tests/lib/onoff/libraries.onoff/CMakeFiles/app.dir/src/main.c.gcno: Overlong record at end of file!
geninfo: WARNING: cannot find an entry for kernel.h##89d5bf7618c1fca4907337b79d929a7a.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for kernel.h##995bd8355f260c9a4629956fa5452285.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for main.c##0923dc7f9398a895b04f1a48b03343fa.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for onoff.h##bcef262fcda3ba07d69b3ec876518792.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for slist.h##3de24f29cd9ee1e3ca7ba77071ab784d.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for ztest_assert.h##d201774caae8de57b8fda062921ec875.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for ztest_test.h##24f89967d7fc67745a048e074cf0aef4.gcov in .gcno file, skipping file!
geninfo: WARNING: /home/apboie/projects/zephyr/zephyr/sanity-out/qemu_x86_coverage/tests/lib/onoff/libraries.onoff/zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/fatal.c.gcno: Overlong record at end of file!
geninfo: WARNING: cannot find an entry for arch.h##70865a6af6d4979d614b366ae3737cbe.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for fatal.c##407bfbeebe884b3d824d00db7a937f54.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for kernel_arch_func.h##84f188d55368383d68fb38f06df93a0c.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for log_core.h##24034719ede41d28fe43ccb1e9c0d8b8.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for mmustructs.h##3544fbaa812f9374465e98e6a4d94965.gcov in .gcno file, skipping file!
```

Not working for me. Note my LCOV version, I upgraded to 1.14.

**Comment by nashif** [comment]
works on fedora because it has lcov 1.14 and this patch:

https://src.fedoraproject.org/fork/thm/rpms/lcov/raw/8027efa02f36d903fceb6210f439910f52a8bd27/f/geninfo.patch

I tried installing this: http://mirrors.kernel.org/ubuntu/pool/universe/l/lcov/lcov_1.14-2_all.deb

and it works.

**Review by tyrantlizard77 — APPROVED** [review]
turns out you need not only LCOV 1.14, but a *patched* version whose geninfo understands recent GCC. I hate computers.

**Review by pabigot — APPROVED** [review]

**Pull request merged**
