### PR TITLE
subsys/mgmt/hawkbit: Fix typo

### PR DESCRIPTION
**Pull request by ycsin**
Removes the extra space before "not".

Signed-off-by: Yong Cong Sin <yongcong.sin@gmail.com>

### CODE REVIEW

**Comment by ycsin** [comment]
Fixes point 3 of #37225

**Comment by Navin-Sankar** [comment]
@ycsin Kindly submit all the changes related to hawkbit in single pr with different commits message.

**Review by cfriedt — APPROVED** [review]

**Comment by ycsin** [comment]
> @ycsin Kindly submit all the changes related to hawkbit in single pr with different commits message.

Is it really required? I separated them so that if one of the changes isn't desired it won't affect other changes.

**Comment by ycsin** [comment]
Closed as @Navin-Sankar requested this to be concatenated with other PRs.
This is now covered by #37351

**Pull request closed without merging**
