### PR TITLE
Bluetooth: Add support for fixed passkeys

### LINKED ISSUE #8350: bluetooth: request BLE stack to support pre-set passkey for pairing
Some bluetooth devices don't have either display or keyboard, but still require security features as much as possible, like secured pairing. One possible solution to support this kind of devices is that the device can store a pre-set passkey in its flash memory during manufacturing, and have the passkey printed on its case. So, a user can pick up the passkey from its case when pairing it. 

Current authentication API `struct bt_conn_auth_cb` doesn't support this kind of requirements. The passkey passed to the function `passkey_display` is actually a random number.

### LINKED ISSUE #8385: Missing documentation on bt_conn_auth_cb(...)
@conn.h there are no documentation on the CB-function bt_conn_auth_cb(...), making it hard to know what the intended functionality of callbacks are.
Ideally the comments should clearly indicate when it can be expected that a given callback occours.

### PR DESCRIPTION
**Pull request by jhedberg**
Add a new bt_passkey_set() API that can be used to set a fixed passkey to be used for pairing. The new API also requires a new Kconfig option to be enabled first (CONFIG_BT_FIXED_PASSKEY).

Fixes #8350
Fixes #8385

### CODE REVIEW

**Comment by jhedberg** [comment]
@jli157 FYI

Note: marked as DNM (Do Not Merge) until more reviews and testing has been done

**Comment by jhedberg** [comment]
This PR now also contains an initial patch to provide documentation for the authentication callbacks, and clear/clean up some issue regarding the cancel and passkey_display callbacks.

**Comment by jhedberg** [comment]
@jli157 based on your description I have a feeling your issue has nothing to do with this PR. Did you try pairing without this PR? Do you know how to trigger it? I'm asking since it sounds from your description that you assume pairing would automatically happen when you connect with LightBlue.

Normally you need to read a protected characteristic in order to trigger pairing - at least I'm not aware of any explicit "pair" button in LightBlue. E.g. with samples/bluetooth/peripheral one would need to read the first 128-bit vendor characteristic to trigger pairing. The only exception is samples/bluetooth/peripheral_sc_only for which simply connecting is enough. I've modified both of these apps to enable the new feature and it works as expected for me. Same with the shell. Note that if you take these samples as a starting point you need to set the .passkey_display callback to NULL since that's not allowed in combination with a fixed passkey.

**Comment by jli157** [comment]
@jhedberg What kind of behavior can be expected when pairing the device with this PR? 

My current project implemented a static passkey by forcibly reassigning a passkey to a static value like below:
```
--- a/subsys/bluetooth/host/smp.c
+++ b/subsys/bluetooth/host/smp.c
@@ -1900,6 +1900,10 @@ static u8_t legacy_request_tk(struct bt_smp *smp)
 
                passkey %= 1000000;
 
+               if(IS_ENABLED(CONFIG_BT_USE_STATIC_PASSKEY)) {
+                       passkey = CONFIG_BT_STATICK_PASSKEY;
+               }
+
                bt_auth->passkey_display(conn, passkey);
 
                passkey = sys_cpu_to_le32(passkey);
```

And in my project, I've implemented the following callbacks:
```
 static struct bt_conn_auth_cb auth_cb_display = {
       .passkey_confirm = auth_passkey_confirm,
       .passkey_display = auth_passkey_display,
        .pairing_confirm = auth_pairing_confirm,
        .cancel = auth_cancel,
        .pairing_complete = auth_pairing_complete,
        .pairing_failed = auth_pairing_failed,
};
```
I know the customized process could be kind of hacking way but it works with the following pairing process: 
1. LightBlue scans nearby BLE devices, including the one running the customized firmware. 
2. Click the device name to try connecting the device;
3. LightBlue will show all characteristics the device exposes. 
4. Almost at the same time, iPhone will pop up a dialog to ask me to input the passkey if the device is accessed at the first time. 
5. If the passkey was correctly entered, the pairing will complete and the device bonding information will be saved to iPhone's settings. 
6. Next time If the device is accessed by either LightBlue or any BLE application, the dialog for asking the passkey will not be necessary unless I click "forget the device" in the settings. And the device can be automatically connected. 

Is my understanding or the pairing process I'm showing wrong or different from what the PR is supposed to support?

**Comment by jhedberg** [comment]
@jli157 pairing will not be triggered with LightBlue until you read a characteristic that requires encryption/authentication. You haven't shown me your full app code, so I can't comment on that. The peripheral_sc_only app calls bt_conn_security() in its connected callback, which is why it's able to trigger encryption for every connection (pairing for the first one).

It's a bit alarming that you've only modified the legacy pairing code - that's only valid if you pair with devices that can't do SC. The iPhone *can* do SC so you'd also need to modify the SC code path (note that you can't call your device Bluetooth 5.0 or even 4.2 if you don't support SC - to enable it you need to enable CONFIG_BT_TINYCRYPT_ECC=y). Anyway, I'm not sure what your custom modifications have to do with this PR? If you intend to go with the new fixed passkey feature you'll need to scrap your custom modifications. Also note that bt_passkey_set() will return an error if you have passkey_confirm, passkey_display or passkey_entry callbacks set as non-NULL.

**Comment by jhedberg** [comment]
@jli157 one correction: LightBlue *will* enable encryption if you're previously paired, however for triggering the pairing you'll need to call bt_conn_security() from your app or read a protected characteristic in LightBlue

**Comment by jli157** [comment]
@jhedberg Actually, my application does the same thing as what `peripheral_sc_only` does, calling `bt_conn_security(conn, BT_SECURITY_MEDIUM)` in the callback `connected` and the function returns successfully. Also, to apply this PR, I've already removed the implementation for callback functions `passkey_confirm` and `passkey_display`; thus the function `bt_set_passkey()` returns successfully. And my `prj.conf` includes the required BT settings: 
```
CONFIG_BT=y
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_SMP=y
CONFIG_BT_SIGNING=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ATT_PREPARE_COUNT=2
CONFIG_BT_TINYCRYPT_ECC=y
```
However, I still didn't see the pairing process was activated.  Did I still miss something? Which sample you would recommend to test this PR, peripheral_sc_only?

**Comment by jhedberg** [comment]
Due to the SMP code changes it'd be important to run PTS SMP tests on this PR. @MariuszSkamra would you be able to do that? Thanks.

**Comment by jhedberg** [comment]
@jli157 your pairing_confirm() callback is missing a call to bt_conn_auth_pairing_confirm(). I think that's why this was failing. The reason you were getting the pairing_confirm() callback for a pairing you triggered was in turn due to a bug in SMP context initialization, for which I've added fixes to this PR now.

**Comment by jhedberg** [comment]
The PR has been updated to allow any auth callbacks now. @sjanc convinced me that the appropriate handling of just-works should be just like it is with other authenticated methods, i.e. we still allow just-works and rely on e.g. the GATT database permissions to decide what can be accessed with an unauthenticated key.

**Review by sjanc — APPROVED** [review]

**Comment by jhedberg** [comment]
recheck

**Comment by jli157** [comment]
@jhedberg Thanks for pointing out the problem in my code! Yes, it works now after adding `bt_conn_auth_pairing_confirm`.

**Comment by jhedberg** [comment]
> @jhedberg Thanks for pointing out the problem in my code! Yes, it works now after adding bt_conn_auth_pairing_confirm.

@jli157 btw, if all your callback does is to call that function, then it's probably best to not use that callback at all (i.e. set it to NULL). The end result will be the same, except with less code on the application side.

**Comment by jli157** [comment]
I tried without `pairing_confirm` and still works like what you said, that is great! Thanks again for making this PR and pointing out the problems in my code!

**Comment by jhedberg** [comment]
recheck

**Comment by jli157** [comment]
Hey @jhedberg Johan, the paring behavior changed a lot after you added the last patch. Without that patch, the paring phone will ask me to enter the static passkey and the security level was increased to "4"
```
shell> Connected
Confirm pairing for 6b:2b:b5:9c:cb:e8 (random)
Security changed: 6b:2b:b5:9c:cb:e8 (random) level 4
Identity resolved 6b:2b:b5:9c:cb:e8 (random) -> 40:4d:7f:a6:0f:7e (public)
Pairing with 40:4d:7f:a6:0f:7e (public) is complete, bond: 1
```
However, after adding the last patch, my iPhone just ask me:
**"my device" would like to pair with your iPhone | cancel | Pair**

And I don't need to enter the passkey anymore to get the device paired and bonded, with the following logs: 
```
shell> Connected
Security changed: 40:4d:7f:a6:0f:7e (public) level 2
Pairing with 40:4d:7f:a6:0f:7e (public) is complete, bond: 1
```
Obviously, the security level was down to "level 2" with the last patch. 

Should I add other stuffs to keep the same behavior? 

Thank you!

**Comment by jhedberg** [comment]
@jli157 I think it's because of a bug I introduced to the `get_io_capa()` function. Should be fixed now, so please try again.

**Review by MariuszSkamra — APPROVED** [review]
1/36   SM   SM/MAS/PROT/BV-01-C   PASS            60.737                  
 2/36   SM   SM/SLA/PROT/BV-02-C   PASS            89.601                  
 3/36   SM   SM/SLA/JW/BV-02-C     PASS            30.025                  
 4/36   SM   SM/MAS/JW/BV-05-C     PASS            31.838                  
 5/36   SM   SM/MAS/JW/BI-01-C     PASS            29.689                  
 6/36   SM   SM/SLA/JW/BI-02-C     PASS            21.902                  
 7/36   SM   SM/SLA/JW/BI-03-C     PASS            28.485                  
 8/36   SM   SM/MAS/JW/BI-04-C     PASS            22.884                  
 9/36   SM   SM/MAS/PKE/BV-01-C    PASS            23.354                  
10/36   SM   SM/SLA/PKE/BV-02-C    PASS            28.219                  
11/36   SM   SM/MAS/PKE/BV-04-C    PASS            23.48                  
12/36   SM   SM/SLA/PKE/BV-05-C    PASS            27.999                  
13/36   SM   SM/MAS/PKE/BI-01-C    PASS            18.919                  
14/36   SM   SM/MAS/PKE/BI-02-C    PASS            17.587                  
15/36   SM   SM/SLA/PKE/BI-03-C    PASS            24.466                  
16/36   SM   SM/MAS/OOB/BV-05-C    PASS            23.334                  
17/36   SM   SM/SLA/OOB/BV-06-C    PASS            29.13                  
18/36   SM   SM/MAS/OOB/BV-07-C    PASS            23.137                  
19/36   SM   SM/SLA/OOB/BV-08-C    PASS            30.336                  
20/36   SM   SM/MAS/EKS/BV-01-C    PASS            23.105                  
21/36   SM   SM/SLA/EKS/BV-02-C    PASS            28.367                  
22/36   SM   SM/MAS/EKS/BI-01-C    PASS            17.492                  
23/36   SM   SM/SLA/EKS/BI-02-C    PASS            18.982                  
24/36   SM   SM/MAS/SIGN/BV-01-C   PASS            35.989                  
25/36   SM   SM/MAS/SIGN/BV-03-C   PASS            43.489                  
26/36   SM   SM/MAS/SIGN/BI-01-C   PASS            36.993                  
27/36   SM   SM/SLA/KDU/BV-01-C    PASS            30.354   #1              
29/36   SM   SM/SLA/KDU/BV-03-C    PASS            30.504                  
30/36   SM   SM/MAS/KDU/BV-04-C    PASS            23.738                       
32/36   SM   SM/MAS/KDU/BV-06-C    PASS            24.114                  
33/36   SM   SM/SLA/KDU/BV-07-C    PASS            34.075                  
34/36   SM   SM/SLA/SIP/BV-01-C    PASS            28.993                  
35/36   SM   SM/MAS/SIP/BV-02-C    PASS            23.194                  
36/36   SM   SM/SLA/SIE/BV-01-C    PASS            38.272  

1/2   SM   SM/SLA/KDU/BV-02-C   PASS            33.558                  
2/2   SM   SM/MAS/KDU/BV-05-C   PASS            23.465

**Pull request merged**
