### PR TITLE
Can driver api

### PR DESCRIPTION
**Pull request by yishai1999**
Add wrapper DEVICE_API macro to all can_driver_api instances.

Also, check that device passed to CAN shell is a can device.

### CODE REVIEW

**Comment by pdgendt** [comment]
Duplicate of https://github.com/zephyrproject-rtos/zephyr/pull/82128

See https://github.com/zephyrproject-rtos/zephyr/issues/82102 for an overview

**Comment by pdgendt** [comment]
Closing duplicate

**Comment by yishai1999** [comment]
> Closing duplicate

Oh! Didn't realize. Can I help?

**Comment by pdgendt** [comment]
> > Closing duplicate
> 
> @pdgendt Oh! Didn't realize. Can I help?

Sure, put your name next to the item you want to look into, or add a comment if you can't edit. Be mindful of finding all occurrences and special cases. I've skipped a few because they need a bit more attention, but I will come back to those.

**Pull request closed without merging**
