### PR TITLE
drivers: ethernet: fix rx used bit not set when high bps ethernet dat…

### PR DESCRIPTION
**Pull request by gitGideonhub**
…a coming in and wrap dma buffer descriptor

recently, I am using zephyr with its Ethernet driver and running on ZynqMP RPU, however, when I doing throughput test I found when high data rate cause the rx dma buffer wrap arround, the rx isr pending handle will not clear the dma buffer.
This scenario can be fixed by flushing the the exist dma buffer packet and re-configure the dma rx buffer.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@decsny please take a look

**Comment by decsny** [comment]
@gitGideonhub please read 
https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribute-guidelines
https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html

you need to clean up your commits to meet these guidelines

**Comment by gitGideonhub** [comment]
Thanks! I will handle this in a few days!

**Comment by gitGideonhub** [comment]
> @gitGideonhub please read https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribute-guidelines https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html
> 
> you need to clean up your commits to meet these guidelines

Hello, Is there any method to modify commit message without re-open a PR.
Thanks.

**Comment by henrikbrixandersen** [comment]
> Hello, Is there any method to modify commit message without re-open a PR.

Yes, search for instruction on how to do an interactive rebase in Git.

**Pull request closed without merging**
