### PR TITLE
tests: error_hook: remove filter and define testcases in yaml file

### LINKED ISSUE #45706: tests: error_hook: mismatch testcases in testplan.json
**Describe the bug**
Twister collected the expected-to-run test function list and then check if they get passed.
But for some specific tests like `tests/ztest/error_hook`, it has two `ztest_test_suite` in `test_main()`.

```
void test_main(void)
{

#if defined(CONFIG_USERSPACE)
	k_thread_access_grant(k_current_get(), &tdata, &tstack);

	ztest_test_suite(error_hook_tests,
			 ztest_user_unit_test(test_catch_assert_fail),
			 ztest_user_unit_test(test_catch_fatal_error),
			 ztest_unit_test(test_catch_z_oops),
			 ztest_unit_test(test_catch_assert_in_isr)
			 );
	ztest_run_test_suite(error_hook_tests);
#else
	ztest_test_suite(error_hook_tests,
			 ztest_unit_test(test_catch_fatal_error),
			 ztest_unit_test(test_catch_assert_fail),
			 ztest_unit_test(test_catch_assert_in_isr)
			 );
	ztest_run_test_suite(error_hook_tests);
#endif
}
```
For each test scenario defined in yaml file, which `ztest_test_suite` should be collected in the test-plan is confused for twister.
For now, as we can see in the below, twister always choose the first `ztest_test_suite` as test plan, so the test functions actually run didn’t match twister’s expectation. Then twister will mark the mis-matching one as failure.

```
{
    "environment":{
        "os":"posix",
        "zephyr_version":"NA",
        "toolchain":"zephyr"
    },
    "testsuites":[
        {
            "name":"tests/ztest/error_hook/testing.ztest.error_hook",
            "arch":"x86",
            "platform":"qemu_x86",
            "run_id":"75d50e6b216a8b43b71651eebd18d250",
            "runnable":true,
            "testcases":[
                {
                    "identifier":"testing.ztest.error_hook.catch_z_oops",
                    "status":null
                },
                {
                    "identifier":"testing.ztest.error_hook.catch_assert_in_isr",
                    "status":null
                },
                {
                    "identifier":"testing.ztest.error_hook.catch_fatal_error",
                    "status":null
                },
                {
                    "identifier":"testing.ztest.error_hook.catch_assert_fail",
                    "status":null
                }
            ]
        },
        {
            "name":"tests/ztest/error_hook/testing.ztest.error_hook.no_userspace",
            "arch":"x86",
            "platform":"qemu_x86",
            "run_id":"e4c616cb24b8a4fd80410a3150219ba7",
            "runnable":true,
            "testcases":[
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_z_oops",
                    "status":null
                },
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_assert_in_isr",
                    "status":null
                },
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_fatal_error",
                    "status":null
                },
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_assert_fail",
                    "status":null
                }
            ]
        }
    ]
}
```

**To Reproduce**
1. twister -p qemu_x86 -T tests/ztest/error_hook/
2. see testplan.json

**Expected behavior**
Testcases in testplan.json should conform to test test scenario defined in yaml file.

**Environment (please complete the following information):**
 - OS: linux
 - Toolchain 0.14.1
 - Commit d781945

### PR DESCRIPTION
**Pull request by ghost**
1.Remove filter to allow platforms(e.g. qemu_x86) supporting
CONFIG_ARCH_HAS_USERSPACE run testcases when userspace is disabled.

2.Define all testcases in the yaml for consistency and issue parsing
them during setup.

fixes #45706 
Signed-off-by: Guo Lixin <lixinx.guo@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
The way this test is written, which is common to many newly added tests serving the same purpose is not compatible with how twister works and how we parse testcases data and causes issues with reporting. So, I prefer if this (and other tests) are done proper and without the ifdefs.

@enjiamai  this was originally done by you.

**Comment by enjiamai** [comment]
> The way this test is written, which is common to many newly added tests serving the same purpose is not compatible with how twister works and how we parse testcases data and causes issues with reporting. So, I prefer if this (and other tests) are done proper and without the ifdefs.
> 
> @enjiamai this was originally done by you.

Got it! I believe all of these should be fixed because we have a much better way to do this now. (in yaml file). We are fixing this. Thank you for providing this feature.

**Comment by LixinGuoX** [comment]
This version can have only one `ztest_test_suite` in `test_main()`, but it also has a side effect on reports.
We define 3 testcases for `testing.ztest.error_hook.no_userspace` in yaml file explicitly, that's what we expect in test plan. But in actual runtime instance, we have 4 testcases in report, with one more `ztest skip` testcase which is out of test plan.
It seems like `testcases ` defined in yaml file is useless under this situation, do we need to keep them in yaml file? Which one should we focus on, test plan or runtime report?
```
{
            "name":"tests/ztest/error_hook/testing.ztest.error_hook.no_userspace",
            "arch":"x86",
            "platform":"qemu_x86",
            "run_id":"6a650c98a06981f70ea8caf6ec1ad75a",
            "runnable":true,
            "status":"passed",
            "execution_time":"2.09",
            "testcases":[
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_fatal_error",
                    "execution_time":"0.50",
                    "status":"passed"
                },
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_assert_fail",
                    "execution_time":"0.10",
                    "status":"passed"
                },
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_assert_in_isr",
                    "execution_time":"0.10",
                    "status":"passed"
                },
                {
                    "identifier":"testing.ztest.error_hook.no_userspace.catch_z_oops",
                    "execution_time":"0.10",
                    "status":"skipped",
                    "reason":"ztest skip"
                }
            ]
        }
```

**Review by enjiamai — DISMISSED** [review]

**Comment by enjiamai** [comment]
Hi @LixinGuoX , I suggest remove the C code change and keep testcase.yaml only.

**Comment by LixinGuoX** [comment]
Hi @enjiamai , have removed the C code change, please re-review, thanks.

**Review by enjiamai — APPROVED** [review]

**Review by chen-png — APPROVED** [review]

**Pull request merged**
