### PR TITLE
Bluetooth: controller: split: Fix missing terminate_ack initialization

### LINKED ISSUE #20135: Bluetooth: controller: split: Missing initialization of master terminate_ack flag
The LL.TS.5.1.1 test case LL/CON/SLA/BV-11-C [Slave Sending Termination] fails in BabbleSim  after the commit fcd9612016e170abc4abb5387a2b3057ea840859, which correctly prevents MD bit being set indiscriminately.
This is caused by the master not acknowleding the TERMINATION_IND, now  the slave is no longer sending it with MD=1.

**To Reproduce**
1. Run test case LL/CON/SLA/BV-11-C, with nRF52 board as Upper- and Lower Tester
2. Test fails with disconnect cause **0x22** (BT_HCI_ERR_LL_RESP_TIMEOUT) instead of **0x16** (BT_HCI_ERR_LOCALHOST_TERM_CONN)
3. Inspecting the air trace shows that master did not acknowledge the TERMINATION_IND

**Expected behavior**
Slave (IUT) should disconnect with **0x16** (BT_HCI_ERR_LOCALHOST_TERM_CONN)

**Impact**
This issue, besides failing LL verification test, slows down BLE disconnection

### PR DESCRIPTION
**Pull request by cvinayak**
Add the missing initialization of master role terminate_ack
flag. This caused slave initiated remote termination as
procedure timeout.

Fixes #20135.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by thoh-ot** [comment]
It feels a bit wierd that the "Refactor LLL" commit is included in the PR to fix the reported issue, but i agree on the solution as a whole, but would rather have seen the "Refactor LLL" in another PR.

**Review by mtpr-ot — COMMENTED** [review]
I agree with @thoh-ot, and would have preferred to have refatoring and fix separated. Porting the fix also becomes more difficult, if needed. However, both commits look good.

**Review by mtpr-ot — APPROVED** [review]
Let's go with this version

**Comment by cvinayak** [comment]
> would rather have seen the "Refactor LLL" in another PR.

@thoh-ot @mtpr-ot I have the refactoring in separate commit, as the fix made sense with the refactoring and having two separate PRs with dependency meant I can cant push/merge the fix before the refactor PR is merged, hence this single PR with two commits.

**Review by thoh-ot — APPROVED** [review]

**Comment by alexandru-porosanu-nxp** [comment]
Hi @cvinayak, @carlescufi, this PR breaks the compilation for central_hr, on all boards (including Nordic ones). The reason why the automated BabbleSim test doesn't catch this is because it sets both CONFIG_BT_CENTRAL=y and  CONFIG_BT_PERIPHERAL=y. And since the struct ull_conn's 'slave' member is now #ifdef'ed, unless you build with CONFIG_BT_PERIPHERAL=n, you will not see the failures below:

```
[124/177] Building C object zephyr/subsys/bluetooth/controller/CMakeFiles/subsys__bluetooth__controller.dir/ll_sw/nordic/lll/lll_conn.c.obj
FAILED: zephyr/subsys/bluetooth/controller/CMakeFiles/subsys__bluetooth__controller.dir/ll_sw/nordic/lll/lll_conn.c.obj 
ccache /home/zephyr-testing/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBUILD_VERSION=zephyr-v2.0.0-1669-g39f2281c89a4 -DKERNEL -DNRF51 -D_FORTIFY_SOURCE=2 -D__PROGRAM_START -D__ZEPHYR__=1 -I/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll -I/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/. -I/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/include -I/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw -I/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic -I/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/hci/nordic -I/home/zephyr-testing/zephyrproject/zephyr/kernel/include -I/home/zephyr-testing/zephyrproject/zephyr/arch/arm/include -I/home/zephyr-testing/zephyrproject/zephyr/include -I/home/zephyr-testing/zephyrproject/zephyr/include/drivers -Izephyr/include/generated -I/home/zephyr-testing/zephyrproject/zephyr/soc/arm/nordic_nrf/nrf51 -I/home/zephyr-testing/zephyrproject/zephyr/ext/lib/crypto/tinycrypt/include -I/home/zephyr-testing/zephyrproject/zephyr/ext/hal/cmsis/Core/Include -I/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth -I/home/zephyr-testing/zephyrproject/modules/hal/nordic/nrfx -I/home/zephyr-testing/zephyrproject/modules/hal/nordic/nrfx/drivers/include -I/home/zephyr-testing/zephyrproject/modules/hal/nordic/nrfx/mdk -I/home/zephyr-testing/zephyrproject/modules/hal/nordic/. -isystem /home/zephyr-testing/zephyrproject/zephyr/lib/libc/minimal/include -isystem /home/zephyr-testing/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/include -isystem /home/zephyr-testing/zephyr-sdk-0.10.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/include-fixed -Os -imacros/home/zephyr-testing/zephyr-build/build_nfr/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mthumb -mcpu=cortex-m0 -imacros/home/zephyr-testing/zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/zephyr-testing/zephyrproject/zephyr/samples/bluetooth/central_hr=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/zephyr-testing/zephyrproject/zephyr=ZEPHYR_BASE -ffunction-sections -fdata-sections -mabi=aapcs -march=armv6s-m -std=c99 -nostdinc -MD -MT zephyr/subsys/bluetooth/controller/CMakeFiles/subsys__bluetooth__controller.dir/ll_sw/nordic/lll/lll_conn.c.obj -MF zephyr/subsys/bluetooth/controller/CMakeFiles/subsys__bluetooth__controller.dir/ll_sw/nordic/lll/lll_conn.c.obj.d -o zephyr/subsys/bluetooth/controller/CMakeFiles/subsys__bluetooth__controller.dir/ll_sw/nordic/lll/lll_conn.c.obj   -c /home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c
/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c: In function 'isr_done':
/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:612:8: error: 'struct lll_conn' has no member named 'slave'
     lll->slave.window_widening_event_us;
        ^~
/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:616:7: error: 'struct lll_conn' has no member named 'slave'
    lll->slave.window_widening_event_us = 0;
       ^~
/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:617:7: error: 'struct lll_conn' has no member named 'slave'
    lll->slave.window_size_event_us = 0;
       ^~
/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c: In function 'isr_rx_pdu':
/home/zephyr-testing/zephyrproject/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:662:7: error: 'struct lll_conn' has no member named 'slave'
    lll->slave.latency_enabled = 1;
```
I would like to create a PR for fixing this, if that's OK with you.

**Comment by cvinayak** [comment]
@alexandru-porosanu-nxp Hope this has been addressed in https://github.com/zephyrproject-rtos/zephyr/pull/20307

**Comment by alexandru-porosanu-nxp** [comment]
@cvinayak , oh, haven't seen that one...anyhow, I'm a bit worried that the automated testing did not catch this.

**Pull request merged**
