### PR TITLE
shell: Add shell comment command rem

### PR DESCRIPTION
**Pull request by rtalbott-tmo**
Added the shell comment command.

Use case: executing scripts that may contain comments.

### CODE REVIEW

**Review by jakub-uC — COMMENTED** [review]
What is purpose of this command? What shall it do?

**Comment by rtalbott-tmo** [comment]
The purpose of the command is to do nothing and simply ignore the entire line.  The use case would be where a script of various commands and the user would like to add comments (rem, in this case).

**Review by jakub-uC — APPROVED** [review]

**Comment by jakub-uC** [comment]
@rtalbott-tmo  Maybe its worth mentioning in the documentation - shell.rst?

**Review by carlescufi — APPROVED** [review]

**Comment by GeorgeCGV** [comment]
Could be great to make it optional.

**Comment by davidemania** [comment]
Yes an option to disable it would be very much welcomed

**Pull request merged**
