### PR TITLE
MCXN947: Add SCTimer support

### PR DESCRIPTION
**Pull request by mmahadevan108**
Add support for SCTimer

### CODE REVIEW

**Review by decsny — DISMISSED** [review]

**Review by danieldegrasse — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
Please rebase on `main` and resolve any merge conflicts.

**Review by danieldegrasse — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by DerekSnell — COMMENTED** [review]
Hi @mmahadevan108 ,
There is a typo in the commit message.  The SOC is mcxn947, not mcxn974.  I updated the PR title.
Thanks

**Comment by mmahadevan108** [comment]
> Hi @mmahadevan108 , There is a typo in the commit message. The SOC is mcxn947, not mcxn974. I updated the PR title. Thanks

Thanks, I have updated the commit message.

**Comment by mmahadevan108** [comment]
@anangl , can you help review

**Review by anangl — APPROVED** [review]

**Pull request merged**
