### PR TITLE
scripts: menuconfig: revoke official Windows support

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
The windows-curses library that has been provided for Windows
compatibility is now unmaintained. Unless a new maintainer volunteers,
Python 3.9 is the last version that has a wheel for this package on
PyPI.

Move the requirement from requirements-base.txt to
requirements-extras.txt as a result, and make sure this will not cause
any errors on Python 3.10 and beyond by restricting the environment
even further.

Update the menuconfig.py program itself to make users aware of these
changes (which should be noticeable in late 2021, when the Python 3.10
release is expected.)

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
I tacked on a related CODEOWNERS commit.

**Comment by tejlmand** [comment]
> The windows-curses library that has been provided for Windows
compatibility is now unmaintained. Unless a new maintainer volunteers,
Python 3.9 is the last version that has a wheel for this package on
PyPI.

Maybe someone could create a wheel package for Python 3.10 when it's out, without signing up as maintainer of the windows-curses port.
At least I see a big difference between creating a new wheel and then fix open issues.

To ensure a good user experience for windows users, we should try to provide a package, even if the code itself are still looking for a maintainer (`guiconfig` is far from `menuconfig` in user experience).

I think we should wait with merging this PR until we are closer to Python 3.10 release.

**Comment by mbolivar-nordic** [comment]
> Maybe someone could create a wheel package for Python 3.10 when it's out, without signing up as maintainer of the windows-curses port.
> At least I see a big difference between creating a new wheel and then fix open issues.

What you are proposing is exactly that "someone" maintain the package.

Are you volunteering?

**Comment by tejlmand** [comment]
> What you are proposing is exactly that "someone" maintain the package.
> 
> Are you volunteering?

If it is about just creating, testing, and uploading the wheel package to PyPI once a year when a new Python 3.x goes out, I think that I could manage that (and thus making life a bit easier for windows users).
I think it is important enough to at least make it easy for windows users to install.

If it about actually maintaining the package in broader scope, that is: bug fixing, enhancement, etc. then I probably have to say no.
Like everyone else, I also have enough to do, so would prefer we still mark it as in need of official maintainer.

Was this clear enough ?

**Comment by mbolivar-nordic** [comment]
> Was this clear enough ?

Not really, because it's not either of those two things. Why don't you take a look in the README and decide if you're volunteering to keep this going:

https://github.com/zephyrproject-rtos/windows-curses

**Comment by tejlmand** [comment]
> Why don't you take a look in the README

Well, looking at that readme, it describes re-patching for new Python version with [@b1cf4e1](https://github.com/zephyrproject-rtos/windows-curses/commit/b1cf4e10cecb9ba3e43766407c2ed2b138571f85) and [@30ca08b](https://github.com/zephyrproject-rtos/windows-curses/commit/30ca08bfbcb7a332228ddcde026181b2009ea0a7), building and uploading to PyPI, of course for all Python versions we support.
But I assume the amount of work might be more than anticipated, and you know something I don't :wink: 

So should take a closer look, as I would need to be sure to have sufficient time, before committing to this.

When I wrote:
> If it about actually maintaining the package in broader scope, that is: bug fixing, enhancement, etc. then I probably have to say no.

I was more referring to all the open issues that are raised: https://github.com/zephyrproject-rtos/windows-curses/issues

**Comment by mbolivar-nordic** [comment]
> Well, looking at that readme, it describes re-patching for new Python version

Right, which is neither:

> just creating, testing, and uploading the wheel package

nor:

>  bug fixing, enhancement, etc.

But something a bit different.

The curses patches I prepared for 3.9 were not exactly the same as the curses patches for 3.8 from Ulf that you linked to.

The curses module implementation may change in between Python versions and we have to adjust our patches each time.

This wasn't very much work this time, but we have no guarantees it won't be more work later depending on what the Python developers do.

So again, are you saying "yes, I volunteer to take over this effort and make it work on time next year, during the Python 3.10 rc period, so it's uploaded to PyPI by the time 3.10 is released"?

If you are saying yes to this, I will close this PR. Otherwise I still think windows-curses is best-effort supported and we should **not** include it in our requirements in a way that causes them to fail if windows-curses is not available.

**Comment by mbolivar-nordic** [comment]
I want to get more eyes on this so I've added dev-review. Let'I will try to set up a last call for maintainers then.

**Review by carlescufi — COMMENTED** [review]
I'd like to ask if it's possible to find a maintainer for the package outside of the zephyr community. Is there a way to search, using perhaps PyPi, for projects that have the `windows-curses` package as a dependency? Or advertise the fact that the package will be orphaned in some Python forum?

**Comment by mbolivar-nordic** [comment]
@carlescufi 

This isn't PyPI, but I was surprised to learn that the GitHub dependents list includes many projects that clearly are not Zephyr related:

https://github.com/zephyrproject-rtos/windows-curses/network/dependents?package_id=UGFja2FnZS0zNTQ2NjMzNjQ%3D

I'm not sure what forum might be best to advertise this, though. The users seem to be pretty spread out.

**Review by carlescufi — CHANGES_REQUESTED** [review]
> @carlescufi
> 
> This isn't PyPI, but I was surprised to learn that the GitHub dependents list includes many projects that clearly are not Zephyr related:
> 
> https://github.com/zephyrproject-rtos/windows-curses/network/dependents?package_id=UGFja2FnZS0zNTQ2NjMzNjQ%3D

That is an astoundingly long list. It makes me rethinking this whole thing to be honest. Let me put a stop to this PR temporarily while I try to find an alternative solution to this.

**Comment by mbolivar-nordic** [comment]
Closing per dev-review discussion.

We will postpone until Python 3.10 and see what happens then.

@carlescufi to follow up internally to see if we can find a maintainer within Nordic.

**Comment by tejlmand** [comment]
@mbolivar-nordic thanks for opening (and closing) this PR.

It raised peoples attention regarding the need for a windows-curses maintainer.

**Pull request closed without merging**
