### PR TITLE
soc: arm: exx32: Add SoC files for EFR32MG24A010F1024IM48

### PR DESCRIPTION
**Pull request by casparfriedrich**
Add *.dtsi as well as Kconfig files for SiLabs EFR32MG24A010F1024IM48

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi @casparfriedrich, two questions:
1. is there any reason this is marked as a draft? Is the final SoC support still subject to change? The usual flow for merging PRs in HALs is that we require the "main" (Zephyr) PR to first be ACK'd. We can't really do that with a draft PR
2. is there no board that could use this SoC in Zephyr that you're working on? Without a board, some of the tools that we use for CI testing won't work (twister)

**Comment by casparfriedrich** [comment]
Hi @fkokosinski,
this is a draft, because I wasn't sure what the process is and expected the hal to be updated first as it needs to be referenced in `west.yml`. Apart from that there nothing to change from my side.
Regarding the board: I'm working on a commercial board which can't go upstream. After all no one could make use of the hardware...

**Comment by casparfriedrich** [comment]
Anything on this?

**Comment by fkokosinski** [comment]
Hi, sorry for the late response!

> Regarding the board: I'm working on a commercial board which can't go upstream. After all no one could make use of the hardware...

Then it looks like the Kconfig options and devicetree configuration that you're introducing in this PR are essentially dead and untestable from Zephyr's perspective. I'm not sure - again, from Zephyr's perspective - if it's a good idea to merge this as it is, so unfortunately I'm reluctant to give a +1 on this.

**Comment by casparfriedrich** [comment]
Understandable. What would be the "correct" way to get commercial platform running. By now I don't see any other way than forking the silabs hal as well as the zephyr main tree to get this in somehow. Unfortunately silabs has so many variants of their cpus that there can't be a real example board for each and everyone of them...

**Comment by fkokosinski** [comment]
I'm not certain about your particular commercial product architecture, but:

> forking the silabs hal

That indeed would be necessary.

> as the zephyr main tree

Not really - you could go for the out-of-tree SoC approach as described [here](https://docs.zephyrproject.org/latest/develop/application/index.html#soc-definitions). Then, you would point to your HAL fork in the manifest file so that west handles it correctly.

**Comment by casparfriedrich** [comment]
> I'm not certain about your particular commercial product architecture, but:
> 
> > forking the silabs hal
> 
> That indeed would be necessary.
> 
> > as the zephyr main tree
> 
> Not really - you could go for the out-of-tree SoC approach as described [here](https://docs.zephyrproject.org/latest/develop/application/index.html#soc-definitions). Then, you would point to your HAL fork in the manifest file so that west handles it correctly.

Okay, I'll have a look into the link you posted

**Pull request closed without merging**
