### PR TITLE
Shell add minimal footprint feature

### PR DESCRIPTION
**Pull request by jakub-uC**
Added new Kconfig feature `CONFIG_SHELL_MINIMAL` that provides only basic shell functionality.
It deactivates the following features:

- Build-in shell commands
- History
- Printing command's help                                                                                              
- Partial completion and autocompletion with the Tab key
- Changing the prompt name in runtime
- Calling shell_execute_cmd from the application
- Colors in the shell
- Arrows handling
- Insert mode
- Wildcards
- Meta-keys

I observed the following impact on resources usage:
The standard build of the shell example:
image

The same example but with the `CONFIG_SHELL_MINIMAL` option set:
image

### CODE REVIEW

**Review by carlescufi — CHANGES_REQUESTED** [review]
Should we enable `CONFIG_CBPRINTF_NANO` now that we have a unified formatting library?

**Comment by jakub-uC** [comment]
@carlescufi Good point

**Comment by jakub-uC** [comment]
@carlescufi  I am having some problems when I am adding `CONFIG_CBPRINTF_NANO`.

When I've created Kconfig in this way:

```
config SHELL_MINIMAL                                                                                                     
        bool "Enable minimal-footprint shell"                                                                            
        select CBPRINTF_NANO                                                                                             
        help                                                                                                             
          Enable only minimal shell functionality to limit memory footprint.                                             
          Following features are not active:                                                                             
          - Build-in shell commands                                                                                      
          - History                                                                                                      
          - Command help                                                                                                 
          - Partial completion and autocompletion with the Tab key                                                       
          - Changing the prompt name in runtime                                                                          
          - Calling shell_execute_cmd from the application                                                               
          - Colors in the shell                                                                                          
          - Arrows handling                                                                                              
          - Insert mode                                                                                                  
          - Wildcards                                                                                                    
          - Meta-keys
```

I am getting the following build error:

```
warning: the choice symbol CBPRINTF_NANO (defined at lib/os/Kconfig.cbprintf:16) is selected by the following symbols, but select/imply has no effect on choice symbols
 - SHELL_MINIMAL (defined at subsys/shell/Kconfig:18)
Parsing /home/jakub/ncs/zephyr/samples/subsys/shell/shell_module/Kconfig
Loaded configuration '/home/jakub/ncs/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp_defconfig'
Merged configuration '/home/jakub/ncs/zephyr/samples/subsys/shell/shell_module/prj.conf'

error: Aborting due to Kconfig warnings
```

**Review by pabigot — COMMENTED** [review]
I'm not convinced the approach of `CONFIG_SHELL_MINIMAL=y` is maintainable.  As people add new features or change things, somebody has to remember to go back and update the Kconfig description to say what is or is not enabled.

To address that there should probably be a test that confirms the effects of this option.

Also if somebody wants an otherwise minimal shell that has one feature (e.g. `STATS`) enabled, they can't  do that because it depends on `!MINIMAL`.

It would seem more flexible to just maintain and document an overlay that configures for the minimal configuration, and add a few options for things that can't currently be turned off independently, like history and autocomplete.

**Pull request closed without merging**
