### PR TITLE
[TOPIC: DTS] scripts: dts: Improve syntax and code for including binding files

### PR DESCRIPTION
**Pull request by ulfalizer**
Have

    include: foo.dts
    include: [foo.dts, bar.dts]

instead of

    inherits:
        !include foo.dts

    inherits:
        !include [foo.dts, bar.dts]

This is a nicer and shorter and less cryptic syntax, and will make it
possible to get rid of the custom PyYAML constructor for '!include'
later.

'inherits: !include ...' is still supported for backwards compatibility
for now. Later on, I'm planning to mass-replace it, add a deprecation
warning if it's used, and document 'include:'. Then the '!include'
implementation can be removed a bit later.

'!include' has caused issues in the past (see the comment above the
add_constructor() call), gets iffy with multiple EDT instances, and
makes the code harder to follow.

I'm guessing '!include' might've been intended to be useful outside of
'inherits:' originally, but that's the only place where it's used. It's
undocumented that it's possible to put it elsewhere.

To implement the backwards compatibility, the code just transforms

    inherits:
        !include foo.dts

into

    inherits:
        - foo.dts

and treats 'inherits:' similarly to 'include:'. Previously, !include
inserted the contents of the included file instead.

Some more sanity checks for 'include:'/'inherits:' are included as well.

### CODE REVIEW

**Comment by galak** [comment]
Looks good.  Will wait for the todo items (mass convert, and deprecation warning) before merging.

**Comment by ulfalizer** [comment]
> Looks good. Will wait for the todo items (mass convert, and deprecation warning) before merging.

Better to merge now I think. It's a no-op and avoids merge conflicts with later changes to the code.

I want to wait until release before doing the conversion. Think it might be less messy than having it on the topic-dts branch.

**Comment by galak** [comment]
> Better to merge now I think. It's a no-op and avoids merge conflicts with later changes to the code.
> 
> I want to wait until release before doing the conversion. Think it might be less messy than having it on the topic-dts branch.

Happy to merge this now, but we should do the conversion on topics-dts, its highly unlikely and dts changes will go into the release tree at this point.  And I expect to merge 'topics-dts' as one of the first things merged into 2.1.

**Review by galak — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
Lets at least add the doc update before merge.

**Comment by ulfalizer** [comment]
Alright, I'll do the conversion and add docs tomorrow.

**Comment by galak** [comment]
> Alright, I'll do the conversion and add docs tomorrow.

I did the conversions, we need to add support to the old scripts to handle the new format.

**Comment by ulfalizer** [comment]
@galak 
Thanks for the conversion.

Updated the old scripts and the documentation.

I wonder if it's worth keeping backwards compatibility here, if the `required: true/false` stuff doesn't. Doesn't hurt at least, so I kept it.

I could add a backwards compatibility patch for the `required` stuff as well if needed.

**Comment by ulfalizer** [comment]
Hmm... need to rebase too.

**Review by galak — APPROVED** [review]

**Pull request merged**
