### PR TITLE
cmake: compiler: add warning for double-promotion

### PR DESCRIPTION
**Pull request by XenuIsWatching**
Add`-Wdouble-promotion` to the warning base. C implicit
promotion rules will want to make floats into doubles very easily. Given
that zephyr targets lower end microprocessors which do not have a
double precision floating point unit, this should be avoided or at least
known when it does happen.

This is to prevent something like #38651 from happening again

Signed-off-by: Ryan McClelland <ryanmcclelland@fb.com>

### CODE REVIEW

**Comment by XenuIsWatching** [comment]
Apparently the Automated checks are revealing there are now warnings being revealed :/

**Review by carlescufi — APPROVED** [review]

**Review by stephanosio — COMMENTED** [review]
Thanks for sending this PR.

`-Wdouble-promotion` should indeed be enabled by default to prevent wasting precious memory space and processing power.

The only concern/question I have is whether this option should belong in `warning_base` -- we currently have many other (arguably essential) warnings currently specified under `warning_dw_*`.

https://github.com/zephyrproject-rtos/zephyr/blob/ca8e3baed7db2acb165eb45c3e3079bfb4ed8ab3/cmake/compiler/gcc/compiler_flags.cmake#L56-L59

https://github.com/zephyrproject-rtos/zephyr/blob/ca8e3baed7db2acb165eb45c3e3079bfb4ed8ab3/cmake/compiler/gcc/compiler_flags.cmake#L69-L72

@tejlmand Could you comment on the rationale behind these "warning levels" and what rules/policies we have regarding which warnings should belong to which level?

Did these have anything to do with the recently defined coding rules and the related discussions in the Safety Committee?

**Comment by XenuIsWatching** [comment]
There are also warnings generated with this change when the CI runs their builds. Some of these are within the modules, such as STM32.

While I definitely can submit another pull request (or add another commit stacked below this one) that will fix the double promotion warnings within the zephyr repo... I'm not sure what do you about the ones in the vendor modules. I do believe that these should be fixed *before* merging in with this flag enabled by default.

**Comment by SebastianBoe** [comment]
The warning levels were inherited from the Linux kernel's Kbuild build system.

They have not proven to be particularly useful in Zephyr.

**Comment by SebastianBoe** [comment]
One could consider omitting the flag for native_posix.

double's are plenty fast outside of embedded.

If most failures are in native_posix code then omitting it for this platform could make it easier to get this in.

**Comment by XenuIsWatching** [comment]
As I run through *all the CI* errors... There appears to be a lot of issues that are getting exposed (more than just the posix issues seen earlier)

* Networking and Sensor drivers that were getting double promoted
* ST HAL module has some issues with double promotion (mostly with the new STM32U hal they just added)
* Just about every printf with floats which were always getting promoted to doubles (really no short term way around this other than to cast it :confused: )

**Review by aescolar — COMMENTED** [review]
+1 for the posix changes.
I have no quarrel with enabling this warning.

**Comment by XenuIsWatching** [comment]
For some modules, such as CMSIS-DSP, which use floats all over the place and have warnings in quite a few places. I'd rather not touch ARM's code, and just disable the `-Wdouble-promotion` flag for that module. It is not quite clear to me how disabling the flag for the module would be done. Would anyone have any insight?

**Comment by SebastianBoe** [comment]
zephyr_library_compile_options(-Wdouble-promotion)

in the CMakeLists.txt that creates the zephyr_library() which contains the sources.

**Comment by XenuIsWatching** [comment]
> > Ahh.... I had to use zephyr_compile_options(-Wno-double-promotion) and that worked
> 
> You meant zephyr_library_compile_options, right? Otherwise you would disable it globally.

Opps.. yep, that's right. I used `zephyr_library_compile_options(-Wno-double-promotion)`

**Review by SebastianBoe — APPROVED** [review]

**Comment by XenuIsWatching** [comment]
It might be best if this pull request is broken up. Gonna resubmit this to fix only the double promotions within zephyr itself, and the flags will have to come later.

**Comment by XenuIsWatching** [comment]
_unfortunately, there was an issue where I submitted that pull request with my main branch, and it won't let me rename it as a I draft another separate pull request_

**Pull request closed without merging**
