### PR TITLE
Use picolibc printf to implement printk

### PR DESCRIPTION
**Pull request by keith-packard**
Just as with cbprintf, picolibc's stdio is flexible enough to provide a compatible interface for printk that eliminates a bunch of extra code in Zephyr.

### CODE REVIEW

**Comment by npitre** [comment]
The commit log says:

> Picolibc printf is smaller than the built-in printk while offering
> a full POSIX implementation.

Would be nice to have numbers to back this assertion?

Then `k_chr_out()` is used when `printk()` is called from user threads.
It does:

```
        k_str_out(&c, 1);
```

In other words, it'll trigger a syscall trap for every single character.

The code in printk.c invoke the `k_str_out()` after
`CONFIG_PRINTK_BUFFER_SIZE` characters (32 by default) which is
significantly less costly.

Can't you factorize things in printk.c directly instead of duplicating
this code? For example, you could have:

```
#ifdef _PICOLIBC__
static FILE __k_out = FDEV_SETUP_STREAM(
       buf_char_out_wrapper,
       NULL, NULL, _FDEV_SETUP_WRITE);
#define PRINT_USER(fmt, ap) vfprintf(&__k_out, fmt, ap)
#else
#define PRINT_USER(fmt, ap) cbvprintf(buf_char_out, fmt, ap)
#endif
```

or something along those lines.

**Review by andyross — DISMISSED** [review]
For me, the code size benefits of the unification are enough to get me to a +1 here.

But **absolutely** put me in the "send the printfs into a ring and let them fight to the death" camp.  I'll bring the popcorn.

**Comment by keith-packard** [comment]
> The commit log says:
> 
> > Picolibc printf is smaller than the built-in printk while offering
> > a full POSIX implementation.
> 
> Would be nice to have numbers to back this assertion?

Building samples/hello-world for qemu-cortex-m3.

main:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:        9056 B       256 KB      3.45%
            SRAM:        3960 B        64 KB      6.04%
        IDT_LIST:          0 GB         2 KB      0.00%
```

picolibc-printk
```
Memory region         Used Size  Region Size  %age Used
           FLASH:        7956 B       256 KB      3.03%
            SRAM:        3968 B        64 KB      6.05%
        IDT_LIST:          0 GB         2 KB      0.00%
```

picolibc-cbprintf (which replaces cbprintf that underpins printk):
```
Memory region         Used Size  Region Size  %age Used
           FLASH:        8032 B       256 KB      3.06%
            SRAM:        3960 B        64 KB      6.04%
        IDT_LIST:          0 GB         2 KB      0.00%
```

Paring the two implementations to their barest support, it looks like cbprintf is a few bytes smaller:

main with CBPRINTF_NANO:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:        7808 B       256 KB      2.98%
            SRAM:        3960 B        64 KB      6.04%
        IDT_LIST:          0 GB         2 KB      0.00%
```

picolibc-printk with all the printf knobs disabled:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:        7852 B       256 KB      3.00%
            SRAM:        3968 B        64 KB      6.05%
        IDT_LIST:          0 GB         2 KB      0.00%
```

> Can't you factorize things in printk.c directly instead of duplicating this code? For example, you could have:

Yeah, that's a better plan -- and the picolibc-cbprintf provides almost all of the savings. Thanks for the suggestion, I'll rework the patch to do that, while also replacing snprintk/vsnprintk with calls to snprintf/vsnprintf for applications using those.

**Comment by npitre** [comment]
> > Would be nice to have numbers to back this assertion?

> Building samples/hello-world for qemu-cortex-m3.

Great! Given you collected those numbers already, please stuff them
in the commit log as well.

**Comment by keith-packard** [comment]
> > > Would be nice to have numbers to back this assertion?
> 
> > Building samples/hello-world for qemu-cortex-m3.
> 
> Great! Given you collected those numbers already, please stuff them in the commit log as well.

done.

**Review by npitre — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
LGTM

**Review by nordic-krch — APPROVED** [review]

**Comment by marc-hb** [comment]
The static analyzer "sparse" does not seem to like `FDEV_SETUP_STREAM`

- https://github.com/zephyrproject-rtos/zephyr/issues/63003

```
/zep_workspace/zephyr/lib/os/printk.c:123:33: error: undefined identifier 'FDEV_SETUP_STREAM'
/zep_workspace/zephyr/lib/os/printk.c:144:32: error: undefined identifier 'FDEV_SETUP_STREAM'
/zep_workspace/zephyr/lib/os/printk.c:144:49: error: invalid initializer
/zep_workspace/zephyr/include/zephyr/posix/sys/stat.h:40:11: error: unable to open 'sys/_timespec.h'
```

**Comment by keith-packard** [comment]
Is the analyzer not using the picolibc version of stdio.h for some reason? That's where the macro is defined.

**Comment by marc-hb** [comment]
Answered in
- https://github.com/zephyrproject-rtos/zephyr/issues/63003#issuecomment-1732124014

**Pull request merged**
