### PR TITLE
drivers/flash: fix warnings about missing casts

### LINKED ISSUE #21290: Compiler warnings in flash.h: invalid conversion from 'const void*' to 'const flash_driver_api*'
There is a missing cast in `/include/drivers/flash.h`, i checked it on master too.

These are only warnings:
`In file included from ../src/main.cpp:15:
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_read(device*, off_t, void*, size_t)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:104:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  104 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_write(device*, off_t, const void*, size_t)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:128:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  128 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_erase(device*, off_t, size_t)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:159:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  159 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'int z_impl_flash_write_protection_set(device*, bool)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:185:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  185 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h: In function 'size_t z_impl_flash_get_write_block_size(device*)':
/Users/szundi/zephyrproject/zephyr/include/drivers/flash.h:272:44: warning: invalid conversion from 'const void*' to 'const flash_driver_api*' [-fpermissive]
  272 |  const struct flash_driver_api *api = dev->driver_api;
      |                                       ~~~~~^~~~~~~~~~
      |                                            |
      |                                            const void*`

### PR DESCRIPTION
**Pull request by szundi**
fix warnings about missing casts in /include/drivers/flash.h on the dev->driver_api
fixes #21290
Signed-off-by: András Szabó <szundi@gmail.com>

### CODE REVIEW

**Comment by szundi** [comment]
is it possible that ${ZEPHYR_BASE}/scripts/checkpatch.pl check for 80 long lines, but the bot here checks if it is <72?

**Comment by stephanosio** [comment]
> is it possible that ${ZEPHYR_BASE}/scripts/checkpatch.pl check for 80 long lines, but the bot here checks if it is <72?

It is referring to the commit message.

**Review by pabigot — DISMISSED** [review]

**Review by stephanosio — COMMENTED** [review]
I think we should really establish guidelines on handling these C++ issues.

These implicit void pointer conversions are perfectly valid and even encouraged in C (e.g. when using `malloc`), while C++ is very pedantic about it; in fact, the only reason we are not getting an error for this is that we specify `-fpermissive`.

IMHO, since these headers primarily target C and such explicit casts involving `void *` are both redundant and (arguably) ugly, I think we should leave them as is and ignore the warnings.

https://github.com/zephyrproject-rtos/zephyr/pull/11371#pullrequestreview-175469965

**Comment by nvlsianpu** [comment]
Normally rather need to fix current PR than close it and open its replacement
https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
Normally rather need to fix current PR than close it and open its replacement
https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

Pleas fix commit message this way.

**Comment by szundi** [comment]
@stephanosio I feel you too, but default zephyr setting build should not spam warnings in my opinion. They need to make policy change, otherwise someone has to make these go away. Strategically I don't really see where this goes, so if it is against long term strategy, I am happy to see this fix trashed for good - otherwise I feel this beautiful 😉

**Comment by pabigot** [comment]
> IMHO, since these headers primarily target C and such explicit casts involving `void *` are both redundant and (arguably) ugly, I think we should leave them as is and ignore the warnings.

I sympathize, but these headers provide the implementation of the flash API, and if they are incorrect the flash API can't be used.

I was already reconsidering my approval, and so now I'm withdrawing it in favor of opening #21365 as the general case.  I believe much of the conversion can be automated with Coccinelle.

**Comment by stephanosio** [comment]
> I feel you too, but default zephyr setting build should not spam warnings in my opinion.

Ideally, these warnings should be allowed to be turned off as they were before; but unfortunately, the gcc guys are as much of `void *` haters as the ISO C++ guys; so, I guess that is not happening anytime soon.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81787

I wonder if writing a wrapper for g++ that filters out the `-fpermissive` warnings involving implicit `void *` type conversions could be an option.

Alternatively, we could patch the g++ in the Zephyr SDK to add an option like `-Wno-implicit-void-pointer-type-conversion`.

**Comment by szundi** [comment]
> > I feel you too, but default zephyr setting build should not spam warnings in my opinion.
> 
> Ideally, these warnings should be allowed to be turned off as they were before; but unfortunately, the gcc guys are as much of `void *` haters as the ISO C++ guys; so, I guess that is not happening anytime soon.
> 
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81787
> 
> I wonder if writing a wrapper for g++ that filters out the `-fpermissive` warnings involving implicit `void *` type conversions could be an option.
> 
> Alternatively, we could patch the g++ in the Zephyr SDK to add an option like `-Wno-implicit-void-pointer-type-conversion`.

This patch ide is nice. Maybe this casting is just waste of work, does not mean any benefit when later something changes.

**Comment by pabigot** [comment]
@szundi please see #21391.  Thanks for raising this concern.

**Comment by stephanosio** [comment]
> This gcc patch idea is nice. Maybe this casting is just waste of work, does not mean any benefit when later something changes. However on Mac, there is no zephyr SDK.

https://github.com/zephyrproject-rtos/zephyr/issues/21365#issuecomment-565390756

It seems that Clang is even more pedantic about it and, at that point, I suppose we have no other option but to appease the C++ specs.

@pabigot is working on establishing the de facto guidelines for this (#21365, #21391, #21392).

**Comment by pabigot** [comment]
Superseded by #21391

**Pull request closed without merging**
