### PR TITLE
Bluetooth: host: Fix L2CAP sent callback on disconnected channel

### PR DESCRIPTION
**Pull request by joerchan**
When receiving the L2CAP sent callbacks the dynamic L2CAP channel may
have been disconnected already. The user of the dynamic channel should
have received the disconnected and released callbacks for this channel
to release any resources for the data being sent, so simply ignoring
this sent callback is enough.

Fix sent callbacks by providing the CID to the callback instead of a
pointer to potentially released memory, and lookup the CID to check that
it is still valid.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@sjanc Can we do a round of PTS testing for this fix? Only L2CAP tests should be needed.

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by sjanc** [comment]
just to confirm that there were no regressions in PTS tests with that

**Comment by d3zd3z** [comment]
@joerchan It looks like the backports to 2.4 and 2.5 will have to be done manually.

**Comment by joerchan** [comment]
@d3zd3z Why is that? The cherry-pick seems to have worked, but CI is failing, seems to be a CI issue AFAICT.

**Pull request merged**
