### PR TITLE
Revert "tests: posix: net: fix missing clock_t and clockid_t with newlib"

### PR DESCRIPTION
**Pull request by nashif**
This reverts commit 45b3010d74924b4a4b5a72b782abb73dcefe76f3.

Issue introduced in #79884.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by ycsin — DISMISSED** [review]
https://github.com/zephyrproject-rtos/zephyr/pull/79963

**Comment by nashif** [comment]
> #79963

are we playing whack a mole now? a hotfix that needs a hotfix that will eventually need another hotfix?

**Review by carlescufi — APPROVED** [review]
I think we should revert this, then continue development on 
https://github.com/zephyrproject-rtos/zephyr/pull/79963

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by dleach02** [comment]
Doesn't this now return issue #79892

**Comment by duda-patryk** [comment]
> Doesn't this now return issue #79892

Yes. Maybe we should revert #76352 also?

**Comment by cfriedt** [comment]
> > Doesn't this now return issue #79892
> 
> Yes. Maybe we should also revert #76352?

Hard no @duda-patryk

**Comment by duda-patryk** [comment]
> > > Doesn't this now return issue #79892
> > 
> > 
> > Yes. Maybe we should also revert #76352?
> 
> Hard no @duda-patryk

Why? This is the second time the main branch is broken due to #79892 (first time was #75205). I understand that for the first time there may have been some issues you were not aware of - accidents happen. Issue #75205 contains all information to reproduce the problem and I really don't understand why we are dealing with this again.

**Comment by cfriedt** [comment]
> Issue #75205 contains all information to reproduce the problem

What problem exactly? Feel free to check out the branch for PR #80006 and be specific about what you feel is broken after that PR is merged.

> I really don't understand why we are dealing with this again.

Progress. You're welcome 😃

**Pull request merged**
