### PR TITLE
Kernel: Improve single thread (CONFIG_MULTITHREADING=n) support

### PR DESCRIPTION
**Pull request by nordic-krch**
An attempt to improve no multithreading (no-mt) support in order to keep it in the tree by:
- cleanup in kernel/timer as `k_timer` is expected to work in no-mt
- extending `tests/kernel/timer/timer_api` to validate no-mt case
- cleanup in kernel so that number of kernel source files can be limited when no-mt.
- added support for no-mt in ztest
- added sanity test for no-mt which validates that expected features are working: `k_busy_wait`, `k_timer`, `irq_locking`, `k_cpu_idle`, `SYS_INIT`
- removing `z_arm_pendsv` from vector table
- reverted deprecation of no-mt.

Note that currently all existing multithreading tests are passing only on `cortex_m` but having test coverage for expected scope will help to add support for other platforms.

Separate PR will cover documentation (will be based on #29338).

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Not that it fits much with Zephyr's overall market direction (increasingly moving into larger and more complicated systems), but it's nice to see this being resurrected.  Any data on binary size to share?

**Comment by carlescufi** [comment]
> Not that it fits much with Zephyr's overall market direction (increasingly moving into larger and more complicated systems), but it's nice to see this being resurrected. Any data on binary size to share?

Thank you @andyross. I do not want to reopen the discussion about the usefulness of the feature but suffice to say that the fact that we are investing time and effort into it, that we commit to maintaining it, that the [ARC architecture might use it](https://github.com/zephyrproject-rtos/zephyr/issues/27415#issuecomment-672962197) in the future and that it was [useful for the Aarch64 maintainers](https://github.com/zephyrproject-rtos/zephyr/issues/27415#issuecomment-708996024) when initially bringing up the platform should be enough reason to keep it.

**Review by npitre — APPROVED** [review]

**Comment by npitre** [comment]
There will always be room for tiny microcontrollers anyway.
If Zephyr loses its ability to be trimmed down then people will write 
another RTOS all over again.

**Comment by hongshui3000** [comment]
This is good news. I can still use single-threaded + my own single-threaded thing-driven framework to develop simple applications. At the same time, I can also use the zephyr software ecosystem.

**Comment by nordic-krch** [comment]
@andyross  regarding:
> Any data on binary size to share?

Savings are not stunning (~2k) but it depends on the perspective. If you want to fit your bootloader in 4k pages. Then such savings may mean 4k vs 8k and that becomes significant.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@nordic-krch please rebase
@dcpleung coudl you please take a look?

**Review by dcpleung — APPROVED** [review]

**Comment by nordic-krch** [comment]
@carlescufi rebased, CI green except for compliance failure that we need to live with.

**Pull request merged**
