### PR TITLE
soc: nordic: Increase SYS_CLOCK_TICKS_PER_SEC resolution for nRF54L

### PR DESCRIPTION
**Pull request by MarGasiorek**
Increase SYS_CLOCK_TICKS_PER_SEC resolution in order to get more accurate time values in zephyr.

### CODE REVIEW

**Comment by masz-nordic** [comment]
CC @adamkondraciuk

**Comment by nordic-krch** [comment]
@MarGasiorek I opened #75887 where i proposed 31250 Hz. I wanted to use something that has 2^n divisor as it works faster (see description in #75887). Would 31250 be enough for your case? Note that increasing clock rate may cause some `tests/kernel/timer` to fail on nrf54 boards.

**Comment by MarGasiorek** [comment]
> @MarGasiorek I opened #75887 where i proposed 31250 Hz. I wanted to use something that has 2^n divisor as it works faster (see description in #75887). Would 31250 be enough for your case? Note that increasing clock rate may cause some `tests/kernel/timer` to fail on nrf54 boards.

@nordic-krch it sounds reasonable for me, @adamkondraciuk what is your opinion?

**Comment by MarGasiorek** [comment]
Done in https://github.com/zephyrproject-rtos/zephyr/pull/75887

**Pull request closed without merging**
