### PR TITLE
drivers: adc: lmp90xxx: initialise all instances

### LINKED ISSUE #32046: LMP90xxx ADC driver fails to initialise more than one instance
**Describe the bug**
The LMP90xxx ADC driver supports multiple instances, but only for devices with _different_ compat strings. If given a DTS with multiple devices with the same compat, only the first one is initialised in the driver.

**Expected behavior**
The LMP90xxx ADC driver should initialise all instances regardless of the compat string.

**Impact**
This is a showstopper for using the LMP90xxx ADC driver on boards with more than one of the same LMPs.

**Environment (please complete the following information):**
 - OS: GNU/Linux
 - Toolchain Zephyr SDK,
 - Commit SHA or Version used: v2.5.0-rc2

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Iterate through all lmp90xxx device instances found in the devicetree and initialise all of them.

Fixes #32046.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
`ERROR:MULTISTATEMENT_MACRO_USE_DO_WHILE: Macros with multiple statements should be enclosed in a do - while loop` - this is not the case for the the `include/devicetree.h` macros resembling the introduced, local macro. Is this a hard requirement?

**Comment by mbolivar-nordic** [comment]
> s this a hard requirement?

Just send a patch turning it off. Checkpatch warnings were turned into errors and now it's a game of whack-a-mole to turn off the ones that are noise.

**Comment by henrikbrixandersen** [comment]
> Just send a patch turning it off. Checkpatch warnings were turned into errors and now it's a game of whack-a-mole to turn off the ones that are noise.

Thanks @mbolivar-nordic. I have included it here to get this PR to pass checkpatch. If it needs to go in a separate PR, please let me know.

**Review by mbolivar-nordic — APPROVED** [review]
LGTM

**Review by nashif — APPROVED** [review]

**Pull request merged**
