### PR TITLE
samples: drivers: watchdog: Disable logging

### PR DESCRIPTION
**Pull request by SavinayDharmappa**
disable CONFIG_LOG as application is not using logging feature.

Signed-off-by: Savinay Dharmappa <savinay.dharmappa@intel.com>

### CODE REVIEW

**Review by ramakrishnapallala — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
The application isn’t using logging, but the watchdog drivers are.

The idea of enabling logging in the watchdog sample was to aid in debugging watchdog drivers and their functionality. 

What prompted you to wanting to disable it?

**Comment by SavinayDharmappa** [comment]
@henrikbrixandersen  this change causes exception when run in esp32 platform. You can look into #13291

**Comment by nashif** [comment]
> @nashif enabling logging is causing exception when this application runs on esp32 platform. #13291

then you need to put this in the commit message. Obviously this is not a fix for the bug, this is just working around it. Do we have an issue about why logging causing an exception on esp32?

**Comment by henrikbrixandersen** [comment]
@nashif Looks like we do: #9596.

There are at least two other bug reports about crashes on ESP32 (#10915 and #10628), where the code in question is built with `CONFIG_LOG=y`.

**Comment by nashif** [comment]
> @nashif Looks like we do: #9596.

right, still this PR is not needed.

**Comment by SavinayDharmappa** [comment]
closing this PR , as this isssue will get fixed when  #9596 is fixed.

**Comment by SupritiAnju** [comment]
still facing spinning issue in watchdog sample while using it with esp32 
prj file only have CONFIG_WATCHDOG=y

**Pull request closed without merging**
