### PR TITLE
build: Added CONFIG_NO_OPTIMIZATIONS

### LINKED ISSUE #5720: Add CONFIG_NOOPTIMIZATIONS option
Add a configuration option that only forces the compilation optimizations to -O0 independently of other configuration options.

Background: Currently we have CONFIG_DEBUG which enables some extra code and sets -Og [-Og does still optimize some relatively trivial code away], and CONFIG_COVERAGE which sets -O0 and enables coverage dumping.
So neither is appropriate if one wants to debug or instrument the code that otherwise would be compiled without either option, and does not want to dump coverage info.

It should be possible to combine this new option with either CONFIG_DEBUG or CONFIG_COVERAGE . This new option should not have any other effect more than lowering optimizations to -O0

### PR DESCRIPTION
**Pull request by aescolar**
Added a new config option which lowers the compiler
optimizations to -O0 independently of other flags.

CONFIG_COVERAGE uses it now instead of having its own
choice in CMakeLists.txt

Fixes #5720

Signed-off-by: Alberto Escolar Piedras <alpi@oticon.com>

### CODE REVIEW

**Review by tyrantlizard77 — COMMENTED** [review]
Would it be possible to make this a radio-button like option alongside CONFIG_DEBUG (which sets the opt to -Og)?

**Comment by aescolar-ot** [comment]
> Would it be possible to make this a radio-button like option alongside CONFIG_DEBUG (which sets the opt to -Og)?

With alongside you mean in the same menu?
Now this new setting sits inside the `Build and Link Features`>`Compiler Options`
While the CONFIG_DEBUG is in `Debugging Options`

**Comment by SebastianBoe** [comment]
> Would it be possible to make this a radio-button like option alongside CONFIG_DEBUG (which sets the opt to -Og)?

Working on it:https://github.com/SebastianBoe/zephyr/commit/b22c827339b40ce15c399a27c8717424e9a1de6f

**Comment by aescolar-ot** [comment]
@SebastianBoe How is it going with this?
If you are caught on something else, and if nobody objects maybe we could just merge this one in. And later, whenever you are ready with your nicer patch take it.
Otherwise we seem to be stalling in a "better is the enemy of the good enough" situation.

**Comment by nashif** [comment]
> How is it going with this?

can you pull that change from @SebastianBoe and make it part of this PR? We should try and do this in 1 single step.

**Comment by SebastianBoe** [comment]
@aescolar-ot : You can merge this PR into your branch: https://github.com/aescolar-ot/zephyr/pull/1

**Comment by aescolar-ot** [comment]
@SebastianBoe Thanks. I cherry picked your 2 commits, fixed a conflict and squashed them together.

**Review by nashif — APPROVED** [review]

**Comment by aescolar-ot** [comment]
@SebastianBoe @andrewboie : Are we ready to merge?

**Review by SebastianBoe — APPROVED** [review]

**Pull request merged**
