### PR TITLE
Arch arm mpu declare mpu config as const

### PR DESCRIPTION
**Pull request by ioannisg**
Define and declare mpu configuration structures as const.
Trivial.

Fixing #10320

### CODE REVIEW

**Comment by ioannisg** [comment]
FYI @MaureenHelm

**Review by erwango — COMMENTED** [review]
You didn't modify 'struct arm_mpu_region' declarations in arch/arm/core/cortex_m/mpu/arm_mpu.c ?

**Comment by ioannisg** [comment]
>  You didn't modify 'struct arm_mpu_region' declarations in arch/arm/core/cortex_m/mpu/arm_mpu.c ?

@erwango  I suppose such `struct arch_mpu_region` variables are to be populated in run-time. Am I missing something?

**Comment by erwango** [comment]
> @erwango I suppose such struct arch_mpu_region variables are to be populated in run-time. Am I missing something?

Yeah, right, declared local variables are all populated runtime. Please discard this comment. Change is fine to me then.

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
