### PR TITLE
samples: rtc: ds1307: Generic RTC Sample

### PR DESCRIPTION
**Pull request by walidbadar**
This sample application periodically reads date and time data from the DS1307 RTC module.

Tested with esp32_devkitc_wroom board and DS1307 RTC module.

### CODE REVIEW

**Comment by kartben** [comment]
@walidbadar please keep the work in #76501 so that the history of discussion and changes can be better followed

**Review by walidbadar — COMMENTED** [review]
Removed whitespaces

**Comment by kartben** [comment]
@walidbadar as indicated before, please take a moment to read the project's contribution guidelines. This will save you a lot of trouble with failed compliance checks etc.
Thanks!

**Comment by walidbadar** [comment]
@kartben Could you please approve the workflows for this PR so the checks can run? Thank you!

**Comment by kartben** [comment]
@walidbadar until you squash your commits, compliance check will keep failing as it runs against *each* commit in your PR

**Pull request closed without merging**
