### PR TITLE
doc: connectivity: bluetooth: sync function name

### PR DESCRIPTION
**Pull request by HanfG**
fix a typo

### CODE REVIEW

**Review by jori-nordic — DISMISSED** [review]
Only missing the typo in the PR title now :smile: 

jokes aside, it would be nice if you could also fix the same typo in https://github.com/jori-nordic/zephyr/blob/66d9ddd9dc587f299c530a5aea307f1b68075e59/doc/connectivity/bluetooth/bluetooth-arch.rst#L283 in the same pr :+1: 

edit: it's not really a typo, I think the function was renamed some time ago and some occurrences were missed.

**Review by jori-nordic — APPROVED** [review]

**Review by jori-nordic — CHANGES_REQUESTED** [review]
sorry, still have the typo in the first commit

**Review by jhedberg — DISMISSED** [review]

**Comment by Thalley** [comment]
@HanfG Please fix your commits: There should only be the two commits fixing the two typos: You have duplicate commits and merge commits. You can use `git commit --amend` and `git push -f` to properly update and re-upload your commits as per the https://docs.zephyrproject.org/latest/contribute/guidelines.html#contribution-workflow

**Comment by HanfG** [comment]
Sorry, my git is not very skilled.

**Comment by jori-nordic** [comment]
@HanfG actually just one commit is enough. You can do a `git reset --soft origin/main` to get rid of all the commits but keep the changes. Then make a commit as usual and `git push --force-with-lease`.

**Comment by HanfG** [comment]
Very helpful, thinks!!!😀

**Review by jori-nordic — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]

**Review by jori-nordic — APPROVED** [review]
I just fixed the commit check (author format)

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
