### PR TITLE
settings: cleanup deletion test

### PR DESCRIPTION
**Pull request by nvlsianpu**
- cleanup deletion test
- fix integer vs unsigned compassion in nvs back-end

### CODE REVIEW

**Comment by nvlsianpu** [comment]
cc @LingoMeng

**Review by fnde-ot — APPROVED** [review]
LGTM

**Review by kapi-no — APPROVED** [review]

**Review by rakons — APPROVED** [review]

**Comment by ioannisg** [comment]
@nvlsianpu does this require backport to 1.14 lts?

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> @nvlsianpu does this require backport to 1.14 lts?

No, not at all.

**Pull request merged**
