### PR TITLE
Add mcxn236 irtc support

### PR DESCRIPTION
**Pull request by NeilChen93**
Add mcxn236 irtc support

### CODE REVIEW

**Review by EmilioCBen — DISMISSED** [review]

**Review by danieldegrasse — DISMISSED** [review]
Approving, but this will have to go in after 4.0 release as it is a new feature

**Review by dleach02 — DISMISSED** [review]

**Review by danieldegrasse — DISMISSED** [review]

**Comment by danieldegrasse** [comment]
We should add an entry to the documentation page for the IRTC, indicating it is supported

**Comment by mmahadevan108** [comment]
@NeilChen93 , how was this tested?

**Review by danieldegrasse — DISMISSED** [review]

**Comment by mmahadevan108** [comment]
@NeilChen93, also please update the 4.1 release notes to indicate this support was added.

**Comment by kartben** [comment]
This needs another rebased, sorry

**Review by mmahadevan108 — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
