### PR TITLE
Drivers nrf rename clock control nrf5

### PR DESCRIPTION
**Pull request by ioannisg**
Refactoring: CLOCK_CONTROL_NRF5 --> CLOCK_CONTROL_NRF
The symbol is to be used also in nRF9160, which is not a nRF5 series SOC.

### CODE REVIEW

**Review by aescolar — DISMISSED** [review]
You seem to have some forgotten includes
drivers/clock_control/nrf_power_clock.c:17
```#include <drivers/clock_control/nrf5_clock_control.h> ```
Apart from that I do not have anything against.

**Review by carlescufi — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
Oops, approved by mistake. Blocking until I can take a look.

**Comment by ioannisg** [comment]
> 
> 
> You seem to have some forgotten includes
> drivers/clock_control/nrf_power_clock.c:17
> `#include <drivers/clock_control/nrf5_clock_control.h> `
> Apart from that I do not have anything against.

Thank you @aescolar. Updated.

**Review by carlescufi — CHANGES_REQUESTED** [review]
You need to rename:
`drivers/clock_control/Kconfig.nrf5`
to
`drivers/clock_control/Kconfig.nrf`

**Comment by ioannisg** [comment]
> 
> 
> You need to rename:
> `drivers/clock_control/Kconfig.nrf5`
> to
> `drivers/clock_control/Kconfig.nrf`

Certainly forgot that, thanks, @carlescufi 
Done now

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@aescolar please revisit

**Review by galak — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Pull request merged**
