### PR TITLE
CMake broke handling of CONFIG_MBEDTLS_BUILTIN=n

### PR DESCRIPTION
**Pull request by miyatsu**
If defined CONFIG_MBEDTLS without define CONFIG_MBEDTLS_BUILTIN, may
cause cmake error: "Cannot specify link libraries for target 'mbedTLS'
which is not built by this project."

If CONFIG_MBEDTLS_BUILTIN disabled by user in Kconfig but leave
CONFIG_MBEDTLS enabled, may cause make error with the same message.

Solve this by enable CONFIG_MBEDTLS_BUILTIN for default and make it
select and depend on CONFIG_MBEDTLS.

Signed-off-by: Ding Tao <miyatsu@qq.com>

### CODE REVIEW

**Review by pfalcon — DISMISSED** [review]
Sorry, but MBEDTLS_BUILTIN has very specific meaning: https://github.com/miyatsu/zephyr/blob/a51854d2044eb2533c1f6ff24a49581dd9dc65ab/ext/lib/crypto/mbedtls/Kconfig#L28 .

The overall issue is CMake side, and that's where it should be fixed. As a workaround, we probably could switch to "default y" for MBEDTLS_BUILTIN.

**Comment by miyatsu** [comment]
Hi @pfalcon 
I'm not familiar with cmake.
Should I just close this PR or. set "default y" for MBEDTLS_BUILTIN as a new commit ?

**Comment by SebastianBoe** [comment]
It sounds like CMake no longer supports linking with an external mbedtls.

@miyatsu : Please post steps to reproduce and I will fix this.

Board, sample, conf_file, etc.

**Comment by miyatsu** [comment]
Sure @SebastianBoe , you may see the error message do those steps:

sample: /zephyr/samples/net/mqtt_publisher
board: frdm_k64f

edit config file: prj_frdm_k64f.conf, add one line: CONFIG_MBEDTLS=y

Then cmake etc..

By the way, manually disable CONFIG_MBEDTLS_BUILTIN without disable CONFIG_MBEDTLS_BUILTIN, once quit the Kconfig, then never get into Kconfig again.

**Comment by miyatsu** [comment]
Here is the output on my conputer

Zephyr version: 1.10.0
-- Generating zephyr/include/generated/autoconf.h
-- Generating zephyr/include/generated/generated_dts_board.h
CMake Error at ../../../cmake/extensions.cmake:663 (target_link_libraries):
  Cannot specify link libraries for target "mbedTLS" which is not built by
  this project.
Call Stack (most recent call first):
  ../../../subsys/net/ip/CMakeLists.txt:1 (zephyr_link_interface_ifdef)


-- Configuring incomplete, errors occurred!

**Comment by SebastianBoe** [comment]
Hi, the problem with the proposed solution is that:

CONFIG_MBEDTLS_BUILTIN means you are using a built-in MDEDTLS
MBEDTLS_LIBRARY means you are using an external MBEDTLS

But after the patch, it is not possible to have

MBEDTLS enabled, BUILTIN disabled, and LIBRARY enabled.

Which is the use-case for someone who wants an external mbdetls. 

I'm sure we can find some Kconfig that makes sense ...

**Comment by miyatsu** [comment]
Thanks for your explanation, I've just notice the kconfig have a "choise", it may can solve this.
I can check it out when I have some free time. But my knowledge are limited, it may take a while for me to solve this alone.

**Comment by SebastianBoe** [comment]
Hi,  @miyatsu , I think I might have a solution: https://github.com/miyatsu/zephyr/pull/1

**Review by SebastianBoe — APPROVED** [review]

**Comment by miyatsu** [comment]
@SebastianBoe Wait for one second,
I just tested your commit, one bug is still there, its seems can not solve by edit this Kconfig file.

When config external library without specify a valid linkable lib, I still can't re-entry "make menuconfig" after I quit the kconfig GUI.

**Comment by SebastianBoe** [comment]
@miyatsu : Hi, can you see if this patch resolves the issues you have discovered?

https://github.com/SebastianBoe/zephyr/commit/8493db58c34cce3a6423f3609bc46d5b5bbe8139.patch

**Comment by miyatsu** [comment]
@SebastianBoe I just tested, it seems still not fixed.

I use the sample "mqtt_publisher" and board "frdm_k64f" without any change but apply your patch.
Here is my test output:

CMake Deprecation Warning at /home/username/project/zephyr/cmake/app/boilerplate.cmake:47 (cmake_policy):
  The OLD behavior for policy CMP0000 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:3 (include)


-- Selected BOARD frdm_k64f
Zephyr version: 1.10.0
-- Generating zephyr/include/generated/autoconf.h
-- Generating zephyr/include/generated/generated_dts_board.h
CMake Error at ../../../cmake/extensions.cmake:663 (target_link_libraries):
  Cannot specify link libraries for target "mbedTLS" which is not built by
  this project.
Call Stack (most recent call first):
  ../../../subsys/net/ip/CMakeLists.txt:1 (zephyr_link_interface_ifdef)


-- Configuring incomplete, errors occurred!
See also "/home/username/project/zephyr/samples/net/mqtt_publisher/build/frdm_k64f/CMakeFiles/CMakeOutput.log".
See also "/home/username/project/zephyr/samples/net/mqtt_publisher/build/frdm_k64f/CMakeFiles/CMakeError.log".
Makefile:896: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1



I have a plan, we should dismiss all the pre-check on "make menuconfig", then, problem solved. Haha

**Comment by miyatsu** [comment]
@SebastianBoe I'm list all my ops, you can recurrence by check this list below:

Step 1:
mkdir -p build/frdm_k64f && cd build/frdm_k64f && cmake -DBOARD=frdm_k64f ./ ../../

Step 2:
make menuconfig

Step 3:
At the kconfig GUI,
enable CONFIG_MBEDTLS
choise CONFIG_MBEDTLS_LIBRARY
leave CONFIG_MBEDTLS_INSTALL_PATH blank

Step 4:
Quit kconfig

Step 5:
make menuconfig

Step 6:
You may see the error message above.

**Comment by SebastianBoe** [comment]
I am unable to reproduce, at step 6 I do not see that error mesage.

I tried with xconfig though, will try with menuconfig ...

**Comment by SebastianBoe** [comment]
Could not reproduce with menuconfig either.

Are you sure this patch applied correctly?

https://github.com/SebastianBoe/zephyr/commit/8493db58c34cce3a6423f3609bc46d5b5bbe8139.patch

Perhaps you could try this branch:

https://github.com/SebastianBoe/zephyr/commits/kconfig-fix-2017-12-11

**Comment by miyatsu** [comment]
I’m now in subway back home, I will retry when I get home. May be one hour

**Comment by miyatsu** [comment]
@SebastianBoe I just test it, nothing wrong with this branch, bug fixed !!

May be some other commit in master branch that I didn't pull up and merge to the branch I put into test.
I do apply that patch alone with two previous commits of yours and mine into my local master branch, I swear...

Thanks for fix this bug. Time for bed, good nignt~

**Comment by miyatsu** [comment]
@SebastianBoe  I've rebase your commit ready to close this PR, please review.

**Comment by SebastianBoe** [comment]
Hi, I see that the only changes since I approved was commits by me, so my approval still stands. I don't have time to re-review.

**Comment by miyatsu** [comment]
Yes, I just fix some conflicts, @pfalcon do you have time to review this ?

**Comment by pfalcon** [comment]
Commit  "mbedtls: Added support for using an externally built mbedtls" message:

> This support has been tested
as well as MBEDTLS_LIBRARY was tested in CI (Not at all).

What does "(Not at all)" mean here?

**Comment by pfalcon** [comment]
> mbedtls: Kconfig: Re-organize to enabled choosing an mbedtls impl. 

Typo, should be "to enable".

**Comment by pfalcon** [comment]
Also commit message:

> This patch implements the same support.

Suggested to rewrite as "This patch implements this support."

**Comment by pfalcon** [comment]
The patches look fine. I removed my -1.

There're however some typos/mis-clarities in the commit messages which I point out above. If they're fixed, I'll be happy to add my +1. Otherwise, there's already approval from @SebastianBoe . Thanks.

**Comment by nashif** [comment]
recheck

**Comment by nashif** [comment]
recheck

**Comment by miyatsu** [comment]
Hi, @nashif , thanks for your time to review this.
I'm a little confusion about the "recheck" you have commend, it that means I need to recheck the commit before merge, or you use "recheck" as a command to trigger the test procedure?

**Comment by nashif** [comment]
@miyatsu this was just to trigger a rebuild

**Pull request merged**
