### PR TITLE
tests: Bluetooth: BAP Broadcast source id and BASE unit tests

### PR DESCRIPTION
**Pull request by Thalley**
Add unit test to test the get_id and get_base functions.

### CODE REVIEW

**Review by cvinayak — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by cvinayak — DISMISSED** [review]

**Review by larsgk — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Comment by carlescufi** [comment]
@cvinayak @larsgk please revisit

**Review by cvinayak — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by cvinayak — DISMISSED** [review]

**Review by larsgk — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by cvinayak — DISMISSED** [review]

**Comment by Thalley** [comment]
PR has been updated due to a bug found. This bug is fixed by https://github.com/zephyrproject-rtos/zephyr/pull/63550 and thus the unit tests here will not pass until that has been merged.

**Review by jhedberg — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
