### PR TITLE
CAN: make the can.frame test endian agnostic

### PR DESCRIPTION
**Pull request by ghost**
Enables the `can.frame` test on `qemu_leon3` and fixes a related test failure.

Eliminated assumptions made by the test on how data structures are stored.

### CODE REVIEW

**Comment by martin-aberg** [comment]
@alexanderwachter may have some input on the updated test as code owner for the canbus subsystem.

**Comment by alexanderwachter** [comment]
@martin-aberg Thanks for the PR. Makes sense to use de defines. Not sure why you changed from frame std_id to ext_id.
We anyway need to refactor the zcan_frame structs. I'll open an issue for that.

**Comment by alexanderwachter** [comment]
True!
The reason behind test_invalid_zcan_frame_to_can_frame() was that some drivers did not touch the bits above bit number 12 when receiving a standard identifier. However, the Linux frame expects that the whole 29 bits are valid.
This test case tests if the upper bits are set to zero IIRC.

**Comment by alexanderwachter** [comment]
@martin-aberg can you rebase?
#28345 did some changes on the z_can_frame

**Comment by martin-aberg** [comment]
Thanks for the notification @alexanderwachter. It is now rebased. #28345 fixed some of the issues which were previousy covered by this PR.

**Review by alexanderwachter — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Pull request merged**
