### PR TITLE
tests: arch: arm: Use a more common SHA algorithm

### PR DESCRIPTION
**Pull request by joerchan**
The profile type "not set" uses the "default crypto config" header. However platform may set their own crypto configuration headers. SHA-512 algorithm is not the most common algorithm to support and are for example disabled in profile types medium and small.

Change to SHA-256 which is much more common and is even needed internally by TF-M for protected storage and sub-key derivation.

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
Missing sauce tag and a plan for upstreaming.

**Review by SebastianBoe — DISMISSED** [review]

**Comment by microbuilder** [comment]
@joerchan I agree SHA-256 is far more common, but looks like this broke CI as-is?

**Comment by joerchan** [comment]
@microbuilder Works on my DK™.

It appears to be an issue that exists in the main branch also. 
Looking into it.

**Comment by joerchan** [comment]
Musca B1 board is broken, will rebase this PR once https://github.com/zephyrproject-rtos/zephyr/pull/60219 is merged.

**Comment by microbuilder** [comment]
@joerchan Want to rebase this now that the musca fixes have been merged, and I'll review? Thanks!

**Comment by joerchan** [comment]
Rebased with Musca fix.

**Comment by joerchan** [comment]
There are test failures for the ARM boards on this test-case.

**Comment by joerchan** [comment]
I had to add a loop for the SHA-256 call because the interrupt work did not run after the first attempt.

I could not get other timing tweaking to work.

I don't think this is a very stable test-case. And probably a more stable test would be a custom secure service that triggered the non-secure interrupt during its execution.

**Comment by microbuilder** [comment]
> I had to add a loop for the SHA-256 call because the interrupt work did not run after the first attempt.
> 
> I could not get other timing tweaking to work.
> 
> I don't think this is a very stable test-case. And probably a more stable test would be a custom secure service that triggered the non-secure interrupt during its execution.

As discussed offline, adding `CONFIG_QEMU_ICOUNT_SHIFT=8` will give QEMU more time between executing instructions on a fast machine so that the interrupt isn't lost. Just as a FYI for anyone bumping in this in the future, since it's a common issue.

**Review by microbuilder — APPROVED** [review]

**Review by SebastianBoe — APPROVED** [review]

**Pull request merged**
