### PR TITLE
Led rgb

### PR DESCRIPTION
**Pull request by mogenslu**
A virtual driver combining 3 individual LED's into one RGB LED

The individual LED's need their own driver and could e.g be led_gpio's or led_pwm's.
This driver makes it easy to combine 3 LED's into 1 RGB LED, with blink and brightness control

### CODE REVIEW

**Comment by simonguinot** [comment]
Hi @mogenslu,

I suggest you convert this PR into a draft until it is ready.

In addition please provide a use case explaining the benefit of having such a virtual driver. I have to say I am not convinced so far.

**Comment by mogenslu** [comment]
Hi @simonguinot
Sorry if I have spammed the system, it is my first pull request.
The code is ready, but there was some compliance checks, which failed. - Git commit msg, spaces, use of * in comments and swapping left and right side in if statements - nothing that changes how the code works.
Right now it looks like the compliance check has stalled, which I don't know what to do about.

The use case for this driver is that many dev boards, and probably also many dedicated boards has a RGB led, which is actually 3 LED's, one red, one blue and one green. They are often controlled directly with a GPIO or a PWM, hence there is the led_gpio and the led_pwm drivers.
With this PR I made a led_rgb driver, which can combine the 3 LED's into 1 virtual LED, where you can set the color, make it blink, adjust the brightness as if it was 1 LED, the driver will handle it is actually 3 LED's.

**Comment by mogenslu** [comment]
Hi
Could someone approve the awaiting workflows, so they can run ?
Could you also do the review ?
Thanks

**Review by simonguinot — CHANGES_REQUESTED** [review]
Hi @mogenslu,

First of all, I apologize for the delay. I haven't forgotten you but I am embarrassed by this PR and that's why I postponed (way too much) my review.

In general, I think it would be nice for Zephyr to support multi-color GPIO and PWM LEDs via the `set_color` API method (rather than handling them as multiple single-color LEDs). And I think you had a smart idea with your `led_rgb` driver by "composing" a pseudo LED from several single color/channel LEDs.

But I also think this is some kind of hack and that the right way would be to add support for multiple color/channel to the `led_gpio` and `led_pwm` drivers directly. And if we have that, then there is little interest in having a driver allowing to "compose" pseudo LEDs...

Less important but still worth mentioning, you'll find a couple of comments below.

**Pull request closed without merging**
