### PR TITLE
Fix riscv_machine_timer mtime read

### LINKED ISSUE #10788: riscv_machine_timer driver don't follow the spec ?
The mtime isn't read properly in the following code : 
https://github.com/zephyrproject-rtos/zephyr/blob/da699e4a3b5f1baf1305331bbea0f8697117a8b9/drivers/timer/riscv_machine_timer.c#L51

I use _Volume I: RISC-V User-Level ISA V2.2  -> Figure 2.5: Sample code for reading the 64-bit cycle counter in RV32_ as reference.

### PR DESCRIPTION
**Pull request by Dolu1990**
This pullrequest fix #10788

### CODE REVIEW

**Comment by Dolu1990** [comment]
This issue could lead to some timer freeze.
For instance on a system which take (let's say) 5 cycles between reading the mtime low and the mtime high,  a timer freez would occure each 5/2^32 timer interrupts.

If that system is running at 100 Mhz, the freez would be  about 40 seconds, and if the timer is running at 1Khz it would happen each 10 days.

**Comment by Dolu1990** [comment]
@pgielda @kgugala Ready for review

**Comment by nategraff-sifive** [comment]
Thanks for your contribution @Dolu1990!

Right now there's also a rewrite of a whole bunch of timer drivers in PR #10556, which includes a similar change for the RISC-V machine timer driver along with a number of other improvements.

**Comment by brouhaha** [comment]
@Dolu1990 The code looks good. I think your analysis of the freeze is wrong. Unless some nested higher-priority interrupt(s) block the timer handler for near 2^32 mtime cycles, the loop will never iterate more than twice before it succeeds to get two consecutive identical reads of mtimeh.

**Comment by Dolu1990** [comment]
Oulala, look like there is some serious business around the timer ^^
thanks :)

**Comment by nategraff-sifive** [comment]
Closing, #10556 included this same change. Thanks again for your contribution @Dolu1990!

**Comment by Dolu1990** [comment]
<3

**Pull request closed without merging**
