### PR TITLE
samples: mesh: nrf52: amendment in States restoration implementation

### PR DESCRIPTION
**Pull request by vikrant8052**
1.

For Genric OnPowerUp equal to 0x02 (Restore):
    If a transition was in progress when powered down, the element restores the target state when
    powered up. Otherwise the element restores the state it was in when powered down. This
    commit implements above mentioned logic.

2.

Removed redundant code.

Signed-off-by: Vikrant More <vikrant8051@gmail.com>

### CODE REVIEW

**Comment by vikrant8051** [comment]
I will merge 3rd commit in first one today itself.

**Comment by vikrant8051** [comment]
Removed the bug.

**Comment by vikrant8051** [comment]
Please provide any review updates if any.

**Review by jhedberg — APPROVED** [review]
The changes look fine to me, but I'm not familiar enough with the model spec to say whether this is compliant with it.

**Comment by vikrant8051** [comment]
Hi @jhedberg 
Please refer page no. 30 -> 3.14 -> Table 3.6 -> context under '0x02' row.

Previously, I had implemented thing which is not matching with Specs requirement.
I used to save, lightness & temp. value after transition get completed. 

But Specs says, if (OnPowerUp == 2) & (transition is in progress) & (device get switched off),
 then after device get switched on it should initialize itself with Target values of interrupted transition.

To happens this, if (OnPowerUp == 2), then we need to save target values on PS storage before transition start.

**Review by trond-snekvik — COMMENTED** [review]
I'm not sure I agree with this change. In the spec, the `last` state is the last non-zero value, and is used to recover our state if there's no default value and OnPowerUp==On (this is what appears to happen on line 191 of state_binding.c). 

After this change, we store the _target_ value in flash, using the `last` name, even if it's 0. Additionally, if OnPowerUp==On, we're now initializing lightness to `LIGHTNESS_MAX`, instead of the last non-zero value, as the `state_binding` function reads `light_lightness_srv_user_data.last`, which is still on its default value until we call `readjust_lightness` at the bottom of that function. 

I think the right way to handle this would be to store the last non-zero value (the `last` state, as it's described in the spec), as well as the `onoff` state, and revert the change in state_binding.c:184. This way, we'll initialize to the last known non-zero value if OnPowerUp=On, and the last known value (zero or otherwise) if OnPowerUp=Recover. This also requires that `last` reflects the target values of the transition, and not the "actual" values.

Please correct me if I've misunderstood something.

**Comment by vikrant8051** [comment]
Ok.. I got your point.

I will add last 3 line of this code snapshot ... ( so that if default value = 0 then last value will not be remain as 0)

```
case STATE_RESTORE:
		light_lightness_srv_user_data.last = (u16_t)
			(light_ctl_srv_user_data.lightness_temp_last >> 16);
		light_ctl_srv_user_data.temp =
			(u16_t) (light_ctl_srv_user_data.lightness_temp_last);
		state_binding(ONPOWERUP, ONOFF_TEMP);

               if (light_lightness_srv_user_data.last == 0) {
                       light_lightness_srv_user_data.last = LIGHTNESS_MAX;
               }
```

**Comment by vikrant8051** [comment]
Hi @trond-snekvik,
Thank you very much for your valuable review cum feedback.
 
As per your recommendations, I have reworked on commit 1. These are latest changes:
 - Create two separate entities of **lightness_last** & **lgithness_temp_last_target** to get store in PS storage
- lightness_last will get store as soon as lightness value updates.
- lightness_last will always contains non-zero value & this will remove bug in following case
```
  if (gen_onoff_srv_root_user_data.onoff == STATE_ON) {
 		if (light_lightness_srv_user_data.def == 0U) {
 			lightness = light_lightness_srv_user_data.last;
 		} else {
 				lightness = light_lightness_srv_user_data.def;	
 		}
  }
```

**Review by trond-snekvik — APPROVED** [review]
Looks good to me!

**Pull request merged**
