### PR TITLE
include: dfu: mcuboot: Fix header information for MCUBoot

### PR DESCRIPTION
**Pull request by sigvartmh**
Add updated version of MCUBoot header and additional header information.

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar** [comment]
Shouldn't this also include updates to boot_read_bank_header()?

I would have expected an addition of a boot_read_v2_header() function that filled this in properly, and also changes to boot_read_bank_header() to check the magic numbers to decide whether to call that or boot_read_v1_header().

**Comment by sigvartmh** [comment]
https://github.com/zephyrproject-rtos/zephyr/blob/1ef9b20f6119b1884ebb1d4cd2823a866b92a1ab/subsys/dfu/boot/mcuboot.c#L30-L57

Peeked into the mcuboot file and the header is already implemented there. It's weird that we have this here and not in the header file. Do you know why?

**Comment by mbolivar** [comment]
> Peeked into the mcuboot file and the header is already implemented there. It's weird that we have this here and not in the header file. Do you know why? The V1 header described here is the V2 header described in the PR AFIK.

v1 here means "the one used in mcuboot versions 1.x.y". Is there an upcoming mcuboot version 2 that is changing the header version? If not, I'm not sure there's anything wrong with this code as-is -- am I missing something?

**Comment by sigvartmh** [comment]
@mbolivar Change the PR to reflect the changes I wanted to see/do. For me it is weird that the header information found in the header file is not reflecting the real layout of the mcuboot header. By moving it out of the `mcuboot.c` file protocols and other files which want to use some information from the mcuboot header can easily use it by including the header for mcuboot instead of having to define the layout again in a struct by themselves.

**Comment by sigvartmh** [comment]
I think the raw header can be removed from `mcuboot.c`

**Review by mbolivar — CHANGES_REQUESTED** [review]
> For me it is weird that the header information found in the header file is not reflecting the real layout of the mcuboot header. By moving it out of the mcuboot.c file protocols and other files which want to use some information from the mcuboot header can easily use it by including the header for mcuboot instead of having to define the layout again in a struct by themselves.

This was done on purpose to have the header information exposed by this API be generic and future-proof in case the on-disk layout changes incompatibly. This revision loses that feature.

I think it's OK if you want to add some additional APIs for getting the raw data, but I don't think we should be forcing all users to know about it.

**Comment by sigvartmh** [comment]
I think exposing the magic would be helpful at least but that maybe just me as it can tell something about which version of MCUBoot the image belongs too as they have had two. However I'll change the PR to move the raw header out into the header so that it can be used by other files which needs this information.

**Comment by mbolivar** [comment]
> I think exposing the magic would be helpful at least but that maybe just me as it can tell something about which version of MCUBoot the image belongs too as they have had two.

That's what the `mcuboot_version` field should be capturing. Upstream mcuboot promised that incompatible changes to the header would be accompanied by major version bumps, so a single int should be enough to tell what version of the bootloader the image was built for.

>  However  I'll change the PR to move the raw header out into the header so that  it can be used by other files which needs this information. Or expose an  additional API which can be called to check if it is an mcuboot header

Sure, adding "raw" routines if they are useful to someone could be reasonable -- I don't know your use case. But the point of designing this API in this way was to hide the user from these details when possible.

**Comment by sigvartmh** [comment]
I don't see the abstraction to be all that useful to be honest but it is fine to keep it simple.  It's used 2 places in conjecture with `boot_img_read_bank_header`. This means you can't detect the image type in transit you actually have to store it before you can start guessing if it is an MCUBoot image or garbage.

I can just store the raw_header layout in the file I'm working in but would it make sense to also expose the actual raw_header in the header `dfu/mcuboot.h`? For use-cases such as this or do you actually want to hide it behind something like `bool boot_is_header(u8_t *buf, size_t len, struct mcuboot_header)` Which populates the structure if true?

**Comment by sigvartmh** [comment]
I assume the functionality is not needed by anyone else I'll just close this

**Comment by mbolivar** [comment]
> I assume the functionality is not needed by anyone else I'll just close this

Like I said if it's useful to expose the raw header then that makes sense to do via additional API.

BTW, do you know what's going on with the new MCUboot version keeping the magic number but having incompatible changes to the header? That seems inconsistent with the previous guarantees about versioning.

**Pull request closed without merging**
