### PR TITLE
drivers: wifi: esp: signal blocking behavior on busy device

### PR DESCRIPTION
**Pull request by eHammarstrom**
Implementations such as the TLS sockets depend on the
EAGAIN signal when requesting a non-blocking sendto that would
block.

Signed-off-by: Emil Hammarstrom <emil.hammarstrom@assaabloy.com>

I do not have any hardware to test this PR, but I noticed this when working on
another net_offloaded driver that also returned -EBUSY on [sendto](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sendto.html) with K_NO_WAIT.

```
static int tls_tx(void *ctx, const unsigned char *buf, size_t len)
{
	struct net_context *net_ctx = ctx;
	ssize_t sent;

	sent = sock_fd_op_vtable.sendto(ctx, buf, len,
					net_ctx->tls->flags, NULL, 0);
	if (sent < 0) {
		if (errno == EAGAIN) {
			return MBEDTLS_ERR_SSL_WANT_WRITE;
		}

		return MBEDTLS_ERR_NET_SEND_FAILED;
	}

	return sent;
}
```

### CODE REVIEW

**Comment by eHammarstrom** [comment]
@jukkar can you mark DNM?

@tsvehagen RFC

**Comment by WilliamGFish** [comment]
I will have a look at this over the holidays.

Billy..

**Comment by WilliamGFish** [comment]
It looks like they have attempted to manage this in the subsys/net/lib/sockets.c
~Line:610
```
		if (status < 0) {
			if (((status == -ENOBUFS) || (status == -EAGAIN)) &&
			    K_TIMEOUT_EQ(timeout, K_FOREVER)) {
				/* If we cannot get any buffers in reasonable
				 * amount of time, then do not wait forever as
				 * there might be some bigger issue.
				 * If we get -EAGAIN and cannot recover, then
				 * it means that the sending window is blocked
				 * and we just cannot send anything.
				 */
```

**Comment by mniestroj** [comment]
In PR #30816 -EBUSY is no longer returned, as packets are always scheduled for sending. See https://github.com/zephyrproject-rtos/zephyr/pull/30816/commits/e5376d72bd67f149a3d1050421bb06e8d1854370.

**Comment by eHammarstrom** [comment]
@mniestroj neat, I didn't know `struct net_pkt` had the `work` member, very useful.
I'll close this in favor of your re-write, thanks!

**Pull request closed without merging**
