### PR TITLE
sample/zoap_server: correct large-update/large-create block handling

### PR DESCRIPTION
**Pull request by rbtchc**
When testing against etsi_coaptest.sh, test cases TD_COAP_BLOCK_03/04 will get stuck. This is because these testcases send out a blockwise transfer but with an empty payload. Although this should be a legit request, large-update/create handlers did not check "MORE" flag in block1 option and always return an error when a request comes with an empty payload.
    
Corrected as below
1. Initialize zoap_block_context when first block arrives.
    (SIZE1 option is not always available. In the case that SIZE1 is
    unavailable, the zoap_block_context will be re-initialized each time
    a new block has arrived)
2. Check "MORE" flag of block1 option. If it's the last block, then an empty payload should be allowed.
3. Response w/ 2.04 CHANGED when the last block has arrived
4. Remove adding block2 option to the response since we are not sending back any data to the caller

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
I would rather see Ravi's zoap rework at #1232 be merged first as that will change the coap sample apps.

**Comment by rbtchc** [comment]
I re-apply the work on top of #1232 when it's merged.

**Comment by rbtchc** [comment]
Rebase on top of #1232, @rveerama1 please take a look at the patch.

**Comment by rveerama1** [comment]
LGTM.

**Comment by rbtchc** [comment]
@jukkar please help to take a look at the PR. Thanks

**Review by jukkar — APPROVED** [review]
LGTM, sorry about the delay.

**Pull request merged**
