### PR TITLE
tests: kernel: accept NXP exception codes

### PR DESCRIPTION
**Pull request by JordanYates**
NXP CPUs don't appear to raise the same exception codes as other ARM chipsets for the same error conditions (from #53551 and #54053).

This PR updates the relevant tests to be more flexible in accepting a range of possible exception codes and fixes the reported errors.

### CODE REVIEW

**Comment by microbuilder** [comment]
Tested successfully on `frdm_k64f`, but CI failing on other boards above.

**Review by microbuilder — APPROVED** [review]

**Review by andyross — CHANGES_REQUESTED** [review]
This rises just above my ick level, sorry.

If NXP isn't behaving the way other architectures do that's presumptively an architecture bug.  If we can't fix that for compatibility reasons, we should at least have it documented somewhere obvious that can be cited from the test code.

If the whole fatal error API isn't as standard as we want (I see some pre-existing ARMisms in the code here) then we probably want to fix the documentation at the OS level too.

**Comment by JordanYates** [comment]
> This rises just above my ick level, sorry.
> 
> If NXP isn't behaving the way other architectures do that's presumptively an architecture bug. If we can't fix that for compatibility reasons, we should at least have it documented somewhere obvious that can be cited from the test code.
> 
> If the whole fatal error API isn't as standard as we want (I see some pre-existing ARMisms in the code here) then we probably want to fix the documentation at the OS level too.

Alternate solution is available here (#54118), which reverts the testing behaviour back to how it was, everyone gets a `K_ERR_CPU_EXCEPTION` for every exception.

I am no expert on ARM implementations, but skimming through the reference manual it seems like which exception is raised depends on implementation details. e.g. `An IBUSERR is only recorded if the instruction is issued for execution`. How are we supposed to tell at the code level whether the instruction is expected to be issued for execution, or if it will fail before being issued with a MemFault instead?

**Comment by microbuilder** [comment]
> I am no expert on ARM implementations, but skimming through the reference manual it seems like which exception is raised depends on implementation details. e.g. `An IBUSERR is only recorded if the instruction is issued for execution`. How are we supposed to tell at the code level whether the instruction is expected to be issued for execution, or if it will fail before being issued with a MemFault instead?

Some of this is always going to be implementation defined, and the tests probably aren't the right place to capture all of those design/implementation variations. The alternative PR (#54118) does seem better in that case, and we still have the richer reason codes when debugging a real-world system, which is an improvement over the situation before that PR.

**Comment by JordanYates** [comment]
> To be clear: I'm not complaining that we don't have a fixed set of error codes implemented the same way everywhere. That's ridiculous. If NXP (or anyone else) has useful information to report to sys_fatal_error_handler() that for whatever reason isn't genericaly portable, it should be able to do so.

The problem here is not that NXP has some new set of error codes that other ARM devices don't have, it's that NXP is raising different error codes (that to me still seem reasonable) for the same fault conditions. This isn't really a difference between archs, but within an arch.

> All I'm saying is that we should treat this as a documentation issue somewhere, so someone coming by looking at this test can see "Oh, this platform is special, here's where I go to see how that works".

I think the problem is that we don't know how it works, and I'm not sure we reasonably can expect to, as it looks to be related to how NXP has chosen to implement the ARM core. The code that sets the reasons is simply looking at the `CPSR` register value, I'm not sure how it could be anything else.

> (And of course ideally we'd have some kind of extensible framework here so generic code like tests can know that this is an arch-specific value and maybe that it's a "subtype of memory fault" or something. But that's longer term).

That's basically what the alternate PR is doing, collapsing the all the arch-specific values back down into what they were before (K_ERR_CPU_EXCEPTION). Going any deeper (MemFault vs UsageFault for example) brings us back to this same issue, even the subtypes aren't consistent.

**Pull request closed without merging**
