### PR TITLE
doc: posix: add aep diagrams and condense aep docs

### PR DESCRIPTION
**Pull request by cfriedt**
Since each POSIX Application Environment Profile provides an additive feature set over the previous profile, we can reduce the description of each to only the base System Interfaces and then the deltas from one profile to the next.

Doc previews:
* [overview](https://builds.zephyrproject.io/zephyr/pr/71846/docs/services/portability/posix/overview/index.html#posix-subprofiles)
* [aep](https://builds.zephyrproject.io/zephyr/pr/71846/docs/services/portability/posix/aep/index.html)

### CODE REVIEW

**Comment by cfriedt** [comment]
If anyone knows of any preferred colours for the diagrams, please feel free to make some suggestions. I'm happy to follow convention there.

**Review by ycsin — DISMISSED** [review]
LGTM

**Comment by cfriedt** [comment]
@kartben - can you please take a look?

**Comment by cfriedt** [comment]
* added more detail for what is currently supported by `POSIX_FILE_SYSTEM` (in `lib/os/fdtable.c`, `lib/posix/options/fs.c`)
* added @de-nordic for a review

**Review by ycsin — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]
everything looks alright, and the generated docs look correct to me.  Only suggestion on the colors is just stay consistent in the gradient but take that as someone who is not a designer.

**Pull request merged**
