### PR TITLE
cmake: Use -serial bt-server when CONFIG_BT

### PR DESCRIPTION
**Pull request by SebastianBoe**
Signed-off-by: Sebastian Boe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by jhedberg** [comment]
Didn't we talk about using CONFIG_BT_HOST instead of CONFIG_BT? In practice I suppose it doesn't make any difference since we don't build controller-only apps for qemu.

I'm also surprised to see in the patch that there was some attempts at cmake-based qemu support in the apps, so I wonder if there was something else preventing qemu Bluetooth support from working.

**Comment by SebastianBoe** [comment]
@jhedberg : I didn't use _HOST as you suggested because I found that the beacon sample didn't have it set.

**Comment by jhedberg** [comment]
> @jhedberg : I didn't use _HOST as you suggested because I found that the beacon sample didn't have it set.

I think it must then get selected through some implicit dependency, since there's no way the beacon code would build without BT_HOST.

**Comment by jhedberg** [comment]
Anyway, as I said, this is quite minor, assuming that this makes qemu work - I'll be testing it

**Comment by SebastianBoe** [comment]
> I think it must then get selected through some implicit dependency, since there's no way the beacon code would build without BT_HOST.

With qemu_x86 on the beacon sample with Kbuild I get:
```

sebo@mach:~/workspace_zephyr/zephyr/samples/bluetooth/beacon$ grep CONFIG_BT outdir/qemu_x86/.config
CONFIG_BT_UART=y
CONFIG_BT_H4=y
# CONFIG_BT_H5 is not set
# CONFIG_BT_NO_DRIVER is not set
# CONFIG_BT_NRF51_PM is not set
CONFIG_BT=y
CONFIG_BT_HCI=y
# CONFIG_BT_CUSTOM is not set
# CONFIG_BT_HCI_RAW is not set
# CONFIG_BT_PERIPHERAL is not set
# CONFIG_BT_CENTRAL is not set
CONFIG_BT_BROADCASTER=y
# CONFIG_BT_OBSERVER is not set
CONFIG_BT_HCI_VS_EXT=y
CONFIG_BT_HCI_VS_EXT_DETECT=y
# CONFIG_BT_RPA is not set
CONFIG_BT_DEBUG=y
# CONFIG_BT_DEBUG_NONE is not set
CONFIG_BT_DEBUG_LOG=y
# CONFIG_BT_DEBUG_MONITOR is not set
CONFIG_BT_DEBUG_COLOR=y
# CONFIG_BT_DEBUG_HCI_DRIVER is not set
CONFIG_BT_HCI_HOST=y
CONFIG_BT_HCI_CMD_COUNT=2
CONFIG_BT_RX_BUF_COUNT=3
CONFIG_BT_RX_BUF_LEN=76
CONFIG_BT_HCI_TX_STACK_SIZE=256
CONFIG_BT_HCI_TX_PRIO=7
# CONFIG_BT_WAIT_NOP is not set
CONFIG_BT_HCI_RESERVE=0
CONFIG_BT_RECV_IS_RX_THREAD=y
CONFIG_BT_RX_STACK_SIZE=1024
CONFIG_BT_RX_PRIO=8
# CONFIG_BT_MESH is not set
CONFIG_BT_HOST_CRYPTO=y
CONFIG_BT_DEVICE_NAME="Test beacon"
CONFIG_BT_DEVICE_APPEARANCE=0
# CONFIG_BT_TINYCRYPT_ECC is not set
# CONFIG_BT_DEBUG_HCI_CORE is not set
# CONFIG_BT_BREDR is not set
# CONFIG_BT_CTLR is not set
# CONFIG_BT_SHELL is not set

```

CONFIG_BT_HOST is not selected either, as it would then be found to be set here I believe.

**Comment by jhedberg** [comment]
No, there's CONFIG_BT_HCI_HOST=y there - sorry for getting the Kconfig variable name wrong

**Comment by jhedberg** [comment]
Anyway, I just tried a few sample Bluetooth apps, and indeed qemu is now working fine. So I leave it up to you to switch to HCI_HOST or not.

**Review by carlescufi — CHANGES_REQUESTED** [review]
CONFIG_BT is fine for now

**Review by carlescufi — COMMENTED** [review]
CONFIG_BT is fine for now

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
