### PR TITLE
boards: hifive1*: Use correct SYS_CLOCK_HW_CYCLES_PER_SEC.

### LINKED ISSUE #44427: SYS_CLOCK_HW_CYCLES_PER_SEC not correct for hifive1_revb / FE310
8388bb7c24bca94a5d40dba0a36e79b80647be6b changed SYS_CLOCK_HW_CYCLES_PER_SEC default to 320000 (was 32768). But, 32768 seems to be the correct setting for hifive1_revb. Test code (run on hifive1_revb):

       while (1) {
               printf("cps: %d cycles: %d secs: %d\n",
                               sys_clock_hw_cycles_per_sec(),
                               sys_clock_cycle_get_32(),
                               sys_clock_cycle_get_32() / sys_clock_hw_cycles_per_sec());
               for (int i = 0; i < 5 * 1000 * 1000; ++i) __asm__ volatile("nop;");
       }

With latest head:

cps: 320000 cycles: 1995 secs: 0                                                
cps: 320000 cycles: 33245 secs: 0                                               
cps: 320000 cycles: 64211 secs: 0                                               
cps: 320000 cycles: 95157 secs: 0                                               
cps: 320000 cycles: 126103 secs: 0                                              
cps: 320000 cycles: 157055 secs: 0                                              
cps: 320000 cycles: 188008 secs: 0                                              
cps: 320000 cycles: 218960 secs: 0                                              
cps: 320000 cycles: 249913 secs: 0                                              
cps: 320000 cycles: 280865 secs: 0                                              
cps: 320000 cycles: 311818 secs: 0                                              
cps: 320000 cycles: 342770 secs: 1

(Print rate is approximately 1 print / sec).

With 8388bb7c24bca94a5d40dba0a36e79b80647be6b reverted:

cps: 32768 cycles: 2174 secs: 0                                                 
cps: 32768 cycles: 33232 secs: 1                                                
cps: 32768 cycles: 64172 secs: 1                                                
cps: 32768 cycles: 95111 secs: 2                                                
cps: 32768 cycles: 126051 secs: 3                                               
cps: 32768 cycles: 156997 secs: 4                                               
cps: 32768 cycles: 187943 secs: 5                                               
cps: 32768 cycles: 218889 secs: 6                                               
cps: 32768 cycles: 249835 secs: 7 

Note that FE310 gets HW cycles from mtime, which counts rtcclk cycles (ref: 9.3 "Timer Registers" in FE310 manual). "RTC should be driven by an external 32.768 kHz watch crystal oscillator".

I'm happy to change this back for hifive1_revb (and/or for all FE310), but based on the 8388bb7c24bca94a5d40dba0a36e79b80647be6b commit message, I wonder if the value 32768 broke something else (maybe something in QEMU target)?

### PR DESCRIPTION
**Pull request by snematbakhsh**
hifive1 and hifive1_revb are confirmed to use 32.768 KHz LFCLK, which is
the rate that mtime / system clock increments.

Fixes: #44427

Signed-off-by: Shawn Nematbakhsh <shawn@rivosinc.com>

### CODE REVIEW

**Comment by snematbakhsh** [comment]
I don't know why these timer-related tests are failing on HiFive1. I double checked the FE310-G000 docs, and the chip should function the same as G002, from a mtime / rtcclk point of view.

I don't have a HiFive1 board, and I don't know how to obtain one. I am going to experiment with my CL in order to invoke tests on the HiFive1 platform with various SYS_CLOCK_HW_CYCLES_PER_SEC parameters.

**Comment by fkokosinski** [comment]
Hi @snematbakhsh. This indeed seems to be an error on my part. Thanks for spotting it. I've tested your changes on the `hifive1` board, and it looks like tests start failing on real hw as well after applying them. One thing that I've noticed is that `SYS_CLOCK_TICKS_PER_SEC` gets the value `128` from the configuration, whereas the [docs](https://docs.zephyrproject.org/latest/kconfig.html#CONFIG_SYS_CLOCK_TICKS_PER_SEC) state:
> This option specifies the nominal frequency of the system clock in Hz

So in our case, it should have the value of `32768`. Applying this change makes the tests pass, at least in my local env, and makes your demo work correctly. Could you apply this change in this PR? This symbol is currently defined for `hifive1` and `hifive_revb` individually in `Kconfig.defconfig`.

**Comment by snematbakhsh** [comment]
Hi @fkokosinski,

Thanks for the review. I added the change you suggested to this PR.

Is my understanding here correct? CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC (frequency of the hardware timer used for the system clock) @ 32768 (an immutable property of the boards we are dealing with) w/ CONFIG_SYS_CLOCK_TICKS_PER_SEC (frequency of the system clock in Hz) @ 128 seems like a valid configuration (exactly 256 HW cycles per tick). But, it seems less than ideal in many applications, because the minimum timing granularity is 1000 / 128 =~ 7.8 msec - this means msleep(1) could end up waiting for ~7.8 msec. Maybe this poor timing precision is the cause of failure for those timing-related tests.

I think the optimal value of CONFIG_SYS_CLOCK_TICKS_PER_SEC would have the following properties:

- “1 millisecond is exactly represented by an integral number of ticks” (from docs).
- 1 tick is exactly represented by an integral number of SysClock HW cycles.

([Code reference](https://github.com/zephyrproject-rtos/zephyr/blob/dcaf8dab1473fdeddb4754720d8ec7fb7522cafb/include/sys_clock.h#L150)).

Unfortunately it’s not possible to achieve both properties w/ our 32768 Hz system clock.

CONFIG_SYS_CLOCK_TICKS_PER_SEC docs also mention the following: “Defaults on most hardware platforms (ones that support setting arbitrary interrupt timeouts) are expected to be in the range of 10 kHz”.

With this in mind, do you think CONFIG_SYS_CLOCK_TICKS_PER_SEC = 8192 might be more appropriate than 32768 here?

**Comment by fkokosinski** [comment]
Thanks for your input @snematbakhsh. It looks like I haven't run the whole test suite, and that the value of the symbol `SYS_CLOCK_TICKS_PER_SEC` is not the root issue here.

I've done some digging and bisecting, and from what I found the first bad commit is 085125525895d17216e71512fd37e137dc1d35d4, but I have no idea why the CI didn't catch it back then. Also, the CI reports 12 failing tests, while in my local env only 3 of them are failing, regardless of whether I use Renode or QEMU to run the simulations, which are:
* tests/kernel/tickless/tickless_concept/kernel.tickless.concept
* tests/kernel/sleep/kernel.common.timing
* tests/kernel/workq/work_queue/kernel.workqueue

**Comment by snematbakhsh** [comment]
Hi @fkokosinski,

Thanks for investigating. Given that `SYS_CLOCK_TICKS_PER_SEC` seems to be unrelated, I modified this PR to only include the commit that corrects `SYS_CLOCK_HW_CYCLES_PER_SEC`. I opened https://github.com/zephyrproject-rtos/zephyr/issues/44856 regarding the test failures on HiFive1.

**Comment by fkokosinski** [comment]
Closing this one at it was superseded by #45344.

**Pull request closed without merging**
