### PR TITLE
drivers: i2c: Add Ambiq I2C driver

### PR DESCRIPTION
**Pull request by msierszulski**
This PR adds the Ambiq IOM I2C driver, as well as instances in SoC.
This PR should be merged after the https://github.com/zephyrproject-rtos/hal_ambiq/pull/3 is merged.

### CODE REVIEW

**Review by fkokosinski — DISMISSED** [review]
LGTM

**Comment by msierszulski** [comment]
@fkokosinski I had to rebase PR due to conflicts.

**Review by fkokosinski — DISMISSED** [review]

**Review by tgorochowik — DISMISSED** [review]

**Comment by fkokosinski** [comment]
Hi @msierszulski, I've merged the HAL PR. Please update your `west.yml` changes.

**Comment by msierszulski** [comment]
Hi @fkokosinski, @tgorochowik. I've rebased the PR

**Review by tgorochowik — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Pull request merged**
