### PR TITLE
soc: intel_adsp: Add app API for page-level memory management

### PR DESCRIPTION
**Pull request by andyross**
This adds an API above the just-added TLB driver that does page-level allocation management of memory in the various cAVS memory spaces, with mapping/remapping support in HP-SRAM where the hardware permits. Memory bounds are automatically detected via a pre-existing linker symbol.

### CODE REVIEW

**Comment by andyross** [comment]
Add SOF folks for review.  Strictly this isn't aimed at SOF but they're in the target market and know the hardware best.

**Review by lgirdwood — CHANGES_REQUESTED** [review]
I think we need to make some parts of this API platform generic Zephyr APIs that either abstract platform specific calls or fallback to generic calls if features are not supported on a particular platform. i.e. we need a consistent client memory API so that the client code remains platform neutral (which it is today).

**Review by nashif — CHANGES_REQUESTED** [review]
Agree with Liam. This is an API that is being advertised as an "app API" so it needs to either use existing memory management APIs that are hardware agnostic or introduce a new class of API available to the application. Application should not be aware of the HW platform it is accessing at this level.

While this hardware might be unique to a vendor, it is not unique to Audio DSPs and same vendor can reuse it for something else; so it can't be called soc_adsp and be under the ADSP collection of SoCs. The same hardware IP can for example come as part of a new DSP for touch, vision or whatever, are we going to implement this over and over again for each class and provide different APIs each time?

The code itself seems to be isolated enough from the SoC which makes it a good candidate for a driver/sub-ystem with a dedicated API or ideally it could use existing memory APIs we have already in place for MMU in case the hardware is mutually exclusive (TLB(!) vs MMU) or we can make them mutually exclusive for the sake of simplicity and moving forward with this PR.

Please consider moving the implementation out of the SoC and introduce this as a subsystem or driver that can be enabled for platforms that support it, potentially also enable it in DTS.

**Comment by andyross** [comment]
I'm out of ideas then.  Someone else will need to take this.  I genuinely feel this is a clean and straightforward driver for a weird piece of hardware that doesn't pollute the rest of Zephyr, but something for which open source drivers are probably a good thing.  I recognize that others have differing opinions, but don't see a path to agreement anymore.

If this isn't the right code here, then... sorry, I'm just not the one to write it.

**Comment by dcpleung** [comment]
@lgirdwood https://github.com/zephyrproject-rtos/zephyr/pull/40971 and https://github.com/zephyrproject-rtos/zephyr/pull/40656 are an attempt to make this more generic. Could you take a look?

**Pull request closed without merging**
