### PR TITLE
boards: stm32: Remove useless CONFIG_BOARD_FOO from _defconfig files

### PR DESCRIPTION
**Pull request by erwango**
CONFIG_BOARD_FOO is enabled in a number of board *_defconfig files
although it is useless as set by cmake.

Clean it from STM32 impacted boards.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by ulfalizer — APPROVED** [review]
Thanks for cleaning it up!

This gets a bit subtle. The CMake files don't actually explicitly set the `BOARD_*` Kconfig variables anywhere. What happens is that the Kconfig board `choice` only ends up with one option, because of this (note that the `source` is within a `choice`):

https://github.com/zephyrproject-rtos/zephyr/blob/510102dd71c0479c55fd23071b250e477a2e87bd/boards/Kconfig#L22

Since a choice must always have some symbol selected, that has the same effect as turning the symbol defined in `$(BOARD_DIR)/Kconfig.board` on.

Did you check that none of the `Kconfig.board` files define more than one symbol? That might break things, if the first symbol isn't supposed to be the one that's enabled (Kconfig choices default to the first symbol).

Maybe things could be reorganized to be a bit less confusing later. This looks good as a cleanup though.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Minor nit, commit message is 'bard' instead of 'board'

**Comment by ulfalizer** [comment]
Maybe the subtle choice thing could be mentioned in the commit message too, so that people don't go hunting for `CONFIG_BOARD_FOO` assignments in CMake files.

Could always copy-paste the thing I wrote in there.

**Comment by erwango** [comment]
@galak, @ulfalizer, thanks for reviews. I've updated the change with your inputs.

Btw, shippable should time out

**Review by ydamigos — APPROVED** [review]

**Comment by ulfalizer** [comment]
@erwango 

Did you check this part btw? It's the only potential breakage here.

> Did you check that none of the `Kconfig.board` files define more than one symbol? That might break things, if the first symbol isn't supposed to be the one that's enabled (Kconfig choices default to the first symbol).

**Comment by erwango** [comment]
@ulfalizer, I oversaw this point. Will check and fix if where needed.

**Review by avisconti — APPROVED** [review]
LGTM

But for the sake of (my) better understanding can you possibly add here more comments about this sentence:
   (as defined as a one option choice, symbol defaults to 'y')

**Review by MaureenHelm — APPROVED** [review]

**Comment by galak** [comment]
Mergeing by hand as this will always timeout.

**Pull request merged**
