### PR TITLE
 bluetooth: gatt: Add GAP Central Address Resolution characteristic 

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This adds Central Address Resolution characteristic that is required
to check by peer if it's about to send directed advertisements where
initiator address is set to RPA.
Zephyr supports the Address Resolution, so the characteristic value
is hard-coded.
Please check Core 5.0 Vol 3 Part C 12.4 CENTRAL ADDRESS RESOLUTION
Related PTS test case: GAP/CONN/ACEP/BV-03-C

### CODE REVIEW

**Review by sjanc — APPROVED** [review]
this is affecting qualification so it is good candidate for 1.13.  If not initial 1.13 than it should be backported to next point release.

**Comment by carlescufi** [comment]
Is the char mandatory if SMP is supported? The reason I ask is that maybe we should allow the application to control its presence via Kconfig?

**Comment by sjanc** [comment]
From the spec:

"The Peripheral shall check if the peer device supports address resolution by
reading the Central Address Resolution characteristic before using directed
advertisement where the initiator address is set to a Resolvable Private
Address (RPA). The Central Address Resolution characteristic defines whether the device
supports privacy with address resolution. "

So if we support it (and we do if SMP support is enabled, right?) we should have this characteristic present.

**Comment by MariuszSkamra** [comment]
There are few PTS test cases affected by this. Those are new in PTS, I've pushed the new 6 test cases to review in AutoPTS on friday.

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
>So if we support it (and we do if SMP support is enabled, right?) we should have this characteristic present.

Don't we need to check `CONFIG_BT_PRIVACY` as well?

**Review by sjanc — CHANGES_REQUESTED** [review]
After some discussion I think that this should depends on central and privacy instead..

**Comment by MariuszSkamra** [comment]
Updated

**Review by sjanc — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
