### PR TITLE
IPM: Add Host-DSP Communication channel driver

### PR DESCRIPTION
**Pull request by finikorg**
Add IPM driver for Host-DSP communication channel. 

Driver resembles https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/ipm/ipm_cavs_idc.c intra-DSP communication channel for Host-DSP communication.

Picked from huge PR with console over IPM and sanitycheck for the up2 board: https://github.com/zephyrproject-rtos/zephyr/pull/22724

### CODE REVIEW

**Comment by dcpleung** [comment]
I think we should name the name "ipm_intel_adsp" (or something more descriptive).

**Comment by finikorg** [comment]
> I think we should name this "ipm_intel_adsp" (or something more descriptive).
@dcpleung , do you mean change driver name (drivers/ipm/ipm_adsp.c ) ?

**Comment by dcpleung** [comment]
Driver name and kconfigs.

**Comment by finikorg** [comment]
> Driver name and kconfigs.

Updated according to comment and modified to use latest drivers APIs.

**Review by dcpleung — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Pull request merged**
