### PR TITLE
ext: hal: nordic: Update nrfx to version 1.0.0

### PR DESCRIPTION
**Pull request by anangl**
Updates nrfx to the recently released version and adjusts its glue
layer accordingly.
License headers are slightly corrected to match the license text at
https://opensource.org/licenses/BSD-3-Clause.
Deprecated MDK files nrf51xxx_peripherals.h are removed, since they
are replaced by a common file named nrf51_peripherals.h.

Additionally, SVD files for nRF5 SoCs are imported.

Origin: nrfx
License: BSD 3-Clause
URL: https://github.com/NordicSemiconductor/nrfx/tree/v1.0.0
commit: cf78ebfea1719d85cf4018fe6c08cc73fe5ec719
Purpose: Provide peripheral drivers for Nordic SoCs
Maintained-by: External

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
Looks good, thanks. Note that the change in license text is there exclusively to match more closely the standard version of the 3-clause BSD template.

**Comment by anangl** [comment]
recheck

**Comment by anangl** [comment]
Triggered another check as the previous one failed in a strange way:
https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/12671/2/console.

**Comment by anangl** [comment]
@sundar-subramaniyan I had to modify the nRF5 USB driver, since the ACCESSFAULT event is no longer available. Could you have a look?

**Comment by sundar-subramaniyan** [comment]
@anangl LGTM. Mind sharing the reason for removing the access fault event?

**Comment by anangl** [comment]
@sundar-subramaniyan AFAICT the event appeared to be not really useful, so it was decided to get rid of it.
Thanks for looking into this PR.

**Comment by sundar-subramaniyan** [comment]
@anangl Okay. Actually in one case it was useful where the USBD enable sequence went wrong because of this [anomaly](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52840.EngB.errata%2Fdita%2Ferrata%2FnRF52840%2FEngineeringB%2Flatest%2Ferr_840.html). The event can indicate incorrect enumeration sequence.

**Comment by sundar-subramaniyan** [comment]
@anangl Okay, I understand. The anomaly is [No. 187. “USB cannot be enabled"](http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.nrf52840.EngB.errata/dita/errata/nRF52840/EngineeringB/latest/anomaly_840_187.html#anomaly_840_187).

**Comment by carlescufi** [comment]
@nashif any feedback on this? It's just a new version import.

**Comment by anangl** [comment]
Added origin info in the commit importing SVD files.

**Review by nashif — APPROVED** [review]

**Pull request merged**
