### PR TITLE
audio: codec: Extend codec API to support recording

### PR DESCRIPTION
**Pull request by btogorean**
Add start_input and stop_input to the audio codec API.

Signed-off-by: Bogdan Togorean <bogdan.togorean@analog.com>

### CODE REVIEW

**Comment by hongshui3000** [comment]
I'm also looking forward to this API enhancement. But I think there should be test case, driver support, so that PR can be accepted

**Comment by btogorean** [comment]
> I'm also looking forward to this API enhancement. But I think there should be test case, driver support, so that PR can be accepted

I have the driver PR in work but is dependent on this interface. Should I create a PR with the driver too and link this PR as a prerequisite of it?

**Comment by hongshui3000** [comment]
Input control should be pretty basic for the audio api, but don't know why it hasn't been added until today. Hope to add the api soon. My application example is, bluetooth audio, I will turn on the input and output when the phone is talking, and turn off the input to save power when playing music, so I need to control the input of the codec separately. However, the current api cannot implement individual control input. This is detrimental to the power consumption control of bluetooth audio such as ble audio

**Comment by carlescufi** [comment]
API meeting:

- No participants with relevant experience/knowledge
- PR Requires implementation in at least one driver

**Pull request closed without merging**
