### PR TITLE
dts: nxp: convert UART drivers to new dt macros

### PR DESCRIPTION
**Pull request by galak**
Converts the following drivers to new DT_INST macros:

```
 serial/uart_mcux_flexcomm.c
 serial/uart_mcux_lpsci.c
```

### CODE REVIEW

**Comment by galak** [comment]
This depends on PR #24362.  Will need to rebase once #24362 is merged.

**Comment by galak** [comment]
Pulled lpuart into its own PR to hopefully get both of the PRs to pass CI & not timeout.

PR #24528

**Review by MaureenHelm — APPROVED** [review]

**Comment by MaureenHelm** [comment]
Need to rebase and fix the merge conflict

**Comment by galak** [comment]
> Need to rebase and fix the merge conflict

rebased.

**Comment by galak** [comment]
CI failure exists on master.  Will look into fix, but going to merge this rather than wasting another CI cycle.

**Pull request merged**
