### PR TITLE
Revert "ARM64: Add support for AM6x A53 pinctrl"

### PR DESCRIPTION
**Pull request by gmarull**
https://github.com/zephyrproject-rtos/zephyr/pull/55245 was merged without any approval of the pinctrl maintainers. The introduced changes have notable deficiencies (many documented in the pinctrl guidelines, like usage of standard properties, direct usage of `pinctrl-0` props in drivers, etc.) that need to be addressed.

Reverting, so that an improved design can be submitted later and merged with a proper review.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by nashif** [comment]
Can we please give the original submitter a chance to fix those notable deficiencies? Is this broken beyond saving that we have to revert the whole thing?

**Comment by gmarull** [comment]
@gramsay0 please, check this.

**Comment by grantramsay** [comment]
Hi, apologies that I made some mistakes, I'm happy to fix them.

If review comments are added here or to the original PR I could create a new PR?

> usage of standard properties

Is this referring to using properties like `bias-pull-up;` rather than `VNDSOC_PIN(X, 0, MUX0)`?
The documentation suggests that both models are valid (though the former is recommended):
https://docs.zephyrproject.org/latest/hardware/pinctrl/index.html#pin-configuration
I considered that Linux uses the later model, so using that might keep _some_ consistency when porting device trees e.g:
https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/ti/k3-am625-sk.dts#L162

> direct usage of `pinctrl-0` props in drivers

Understood, I will come up with a better solution.

After the original PR was merged I realised that k3 architecture SoCs (including the one I'm targeting) usually have multiple pinctrl peripherals, so the driver needs to be multi-instance. This might be a good chance to fix that as well

**Comment by gramsay0** [comment]
@gmarull @nashif I've created A PR here https://github.com/zephyrproject-rtos/zephyr/pull/56677.
Please provide feedback on anything else you would like changed

**Comment by gmarull** [comment]
> Hi, apologies that I made some mistakes, I'm happy to fix them.
> 
> If review comments are added here or to the original PR I could create a new PR?
> 
> > usage of standard properties
> 
> Is this referring to using properties like `bias-pull-up;` rather than `VNDSOC_PIN(X, 0, MUX0)`? The documentation suggests that both models are valid (though the former is recommended): https://docs.zephyrproject.org/latest/hardware/pinctrl/index.html#pin-configuration I considered that Linux uses the later model, so using that might keep _some_ consistency when porting device trees e.g: https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/ti/k3-am625-sk.dts#L162

It is ok to maintain Linux compatibility, they are not likely using the relatively new _standard_ properties like `bias-pull-up`, however, the Zephyr bindings are not equal, e.g. you're using `pinmux` and not `pinctrl-single,pins`. So we either gain full compatibility with Linux, or, we just use the recommended Zephyr guidelines.

**Comment by gramsay0** [comment]
@gmarull 
> So we either gain full compatibility with Linux, or, we just use the recommended Zephyr guidelines.

Good point, at the moment it is neither of these.
Which do you recommend?

**Pull request closed without merging**
