### PR TITLE
CODEOWNERS: Add sjanc for Bluetooth host paths

### PR DESCRIPTION
**Pull request by sjanc**
This will help with review process.

Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

### CODE REVIEW

**Comment by Thalley** [comment]
Isn't it https://github.com/zephyrproject-rtos/zephyr/blob/main/MAINTAINERS.yml that need to be updated, and not the CODEOWNERS file?

**Comment by Thalley** [comment]
See https://docs.zephyrproject.org/latest/project/project_roles.html?highlight=collaborator#collaborator

**Review by carlescufi — DISMISSED** [review]

**Comment by sjanc** [comment]
I'm bit confused about CODEOWNER vs MAINTAINERS... should I edit MAINTAINERS.yml  instead?

**Comment by Thalley** [comment]
> I'm bit confused about CODEOWNER vs MAINTAINERS... should I edit MAINTAINERS.yml instead? or both?

I can't remember the purpose of the CODEOWNERS file, but the MAINTAINERS.yml file is what needs to be updated according to https://docs.zephyrproject.org/latest/project/project_roles.html?highlight=collaborator#collaborator. 

@carlescufi @jhedberg Please advice

**Review by Thalley — DISMISSED** [review]
Accepting from the point of view of Bluetooth Audio.

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
