### PR TITLE
disable boards still using pinmux and deprecate pinmux

### PR DESCRIPTION
**Pull request by nashif**
- drivers: pinmux: deprecate pinmux
- boards: disable mec1501modular_assy6885 and mec15xxevb_assy6853

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by enjiamai — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by PerMac — APPROVED** [review]

**Comment by gmarull** [comment]
It is a shame that we end up with this approach, so I won't give +1. Developers promised to deliver a solution in time before 3.2.0, but they have failed to make it. I think board removal (not to be confused with platform support) or breaking board by removing `pinmux.c` would send a stronger message on poorly maintained platforms/boards.

**Comment by nashif** [comment]
> would send a stronger message on poorly maintained platforms/boards

how is this poorly maintained exactly? This board is maintained, tested, on a daily basis and in no means broken or anything. Last time I checked, pinux is still supported, will be supported for 2 more releases after deprecation. 
Many PRs and features did not go in because of vacations and PRs being blocked by people being out. Maintainer was out, they are actively working on adding this support and in no-way ignoring the issue.

Lets see, delaying deprecation, or deprecate by working around the CI issue which is preventing us from deprecating, or breaking a working, maintained and supported platform....

**Comment by gmarull** [comment]
> > would send a stronger message on poorly maintained platforms/boards
> 
> how is this poorly maintained exactly? This board is maintained, tested, on a daily basis and in no means broken or anything. 

Maintenance includes keeping up with in-tree additions/changes, this is clearly not the case.

> Last time I checked, pinux is still supported, will be supported for 2 more releases after deprecation.

Supported for OOT uses, in-tree code can't use deprecated features. This has always been the rule, unless I'm mistaken.

> Many PRs and features did not go in because of vacations and PRs being blocked by people being out. Maintainer was out, they are actively working on adding this support and in no-way ignoring the issue.

So now Zephyr schedule needs to consider people's vacation? Really?
> 
> Lets see, delaying deprecation, or deprecate by working around the CI issue which is preventing us from deprecating, or breaking a working, maintained and supported platform....

**Comment by nashif** [comment]
> Maintenance includes keeping up with in-tree additions/changes, this is clearly not the case. (pinctrl was added ~1y ago)

Right, and that process started, it is in no-way being ignored, it just did not happen in time.

> Supported for OOT uses, in-tree code can't use deprecated features. This has always been the rule, unless I'm mistaken.

Right, but right now pinmux is not deprecated.

> So now Zephyr schedule needs to consider people's vacation? Really?

Yes and No. Nobody likes this, but sh*t happens and we always have this issue during the summer. Features get blocked because of various reasons including the fact the most people are out and go to the next release if they do not make it in time. This is exactly the case.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@jvasanth1 committed to drop pinmux.c from the boards by EoD as part of https://github.com/zephyrproject-rtos/zephyr/pull/48893, with that plus this PR we should be able to move forward.

**Pull request merged**
