### PR TITLE
json: add support to include a already encoded object to a object

### PR DESCRIPTION
**Pull request by maass-hamburg**
add support to include a already encoded object to a object.
~~This is needed in #69293~~

### CODE REVIEW

**Comment by ycsin** [comment]
Ping @Sir-Branch @d3zd3z - any thoughts on this?

**Review by ycsin — DISMISSED** [review]

**Comment by mkaranki** [comment]
This would benefit from test case, which would also document the feature to some extent.

**Review by nashif — DISMISSED** [review]
can you please add a test?

**Review by ycsin — APPROVED** [review]
re-ack

**Review by kartben — APPROVED** [review]

**Comment by maass-hamburg** [comment]
ping @d3zd3z

**Comment by ycsin** [comment]
> ping @d3zd3z

another ping @d3zd3z

**Review by d3zd3z — APPROVED** [review]

**Pull request merged**
