### PR TITLE
Updated LVGL to v7.6.1

### LINKED ISSUE #29050: Ugrade lvgl library
Bundled version in zephyr 2.4 of LGVL is 7.0.2, but last version is 7.6.1 which include numerous bug fixes.
(I"m currently being hit by memory bugs in the chart widget, bugs that don't occur in last version)

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Updated LVGL to version 7.6.1

resolves #29050 

Only tested on native posix board as I have currently no HW available

Marked DNM, as https://github.com/zephyrproject-rtos/lvgl/pull/9 not yet merged

No significant memory changes were observed with this new version.
The ROM usage decreased with ~1.8KB on `nrf52840dk_nrf52840`  (80476 bytes -> 78624 bytes)

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]
Missing new options:

- `LV_BIG_ENDIAN_SYSTEM` (I suppose this is known at build time?)
- `LV_USE_FONT_COMPRESSED`

Material theme has new flags available:
- `LV_THEME_MATERIAL_FLAG_NO_TRANSITION`
- `LV_THEME_MATERIAL_FLAG_NO_FOCUS`

Changed defaults:
- `LV_THEME_DEFAULT_COLOR_PRIMARY` (to `lv_color_hex(0x01a2b1)`)
- `LV_THEME_DEFAULT_COLOR_SECONDARY` (to `lv_color_hex(0x44d1b6)`)
- `LV_LINEMETER_PRECISE` (enabled, but may increase ROM usage)

ref. https://github.com/lvgl/lvgl/compare/v7.0.2...v7.6.1

**Comment by gmarull** [comment]
Tested on `nrf52840dk_nrf52840` + `buydisplay_2_8_tft_touch_arduino`

**Comment by gmarull** [comment]
@vanwinkeljan support for Montserrat 8px/10px doesn't work (https://github.com/lvgl/lvgl/issues/1845) so I think they should not be added until fixed.

**Comment by vanwinkeljan** [comment]
@gmarull added missing options and flags.

Regarding the default colors I just kept them the same as it would require a large number (at minimum 8) of Kconfigs to change.

On the line meter precision I rather keep it in line with the approach of a minimal default config.

**Review by jfischer-no — APPROVED** [review]
Tested with SSD1306, ST7786, SSD16XX based displays.

**Review by gmarull — APPROVED** [review]
LGTM, however, we could wait for the next release (seems to be scheduled for 20/10) so that fixes for bugs like https://github.com/lvgl/lvgl/issues/1845 are included.

**Comment by sdalu** [comment]
7.7.0 is out: https://github.com/lvgl/lvgl/tree/v7.7.0

**Comment by vanwinkeljan** [comment]
Looks like for some reason lvgl 7.7.0 is not yet `officially` released (latest release on github still points 7.6.1).
So I will not wait any longer and keep 7.6.1.

**Comment by vanwinkeljan** [comment]
Let's push 7.6.1 as for some reason 7.7.0 is not yet been released.
There is a tag to 7.7.0 but the latest release according to the lvgl github page is still 7.6.1.

**Comment by vanwinkeljan** [comment]
@gmarull @jfischer-phytec-iot Thx for testing!

**Pull request merged**
