### PR TITLE
Led PWM sample

### PR DESCRIPTION
**Pull request by yishai1999**
Added another cute little part to the sample logic and added two more overlay files

### CODE REVIEW

**Review by kartben — CHANGES_REQUESTED** [review]
sample.yaml and README.rst need to be updated
I would also consider doing the increase-then-decrease in a single loop to avoid duplicating code

**Comment by yishai1999** [comment]
> sample.yaml and README.rst need to be updated I would also consider doing the increase-then-decrease in a single loop to avoid duplicating code

I updated the files.
Regarding the single loop - I think it would just make the code less readable. If you have a suggestion for a way to make it look good and in one loop I'm all ears.

**Comment by yishai1999** [comment]
@kartben Can we merge?

**Review by kartben — APPROVED** [review]

**Comment by yishai1999** [comment]
@bbilas @Mani-Sadhasivam @nashif @simonguinot Can you take a look?

**Comment by simonguinot** [comment]
> @bbilas @Mani-Sadhasivam @nashif @simonguinot Can you take a look?

@yishai1999 It looks good to me but can you add the changes to `release-notes-4.1.rst` ? Thanks in advance ! :)

**Comment by kartben** [comment]
> > @bbilas @Mani-Sadhasivam @nashif @simonguinot Can you take a look?
> 
> @yishai1999 It looks good to me but can you add the changes to `release-notes-4.1.rst` ? Thanks in advance ! :)

@simonguinot what changes? There is nothing in there that's "release note worthy", or did I miss something important?

**Comment by simonguinot** [comment]
> > > @bbilas @Mani-Sadhasivam @nashif @simonguinot Can you take a look?
> > 
> > 
> > @yishai1999 It looks good to me but can you add the changes to `release-notes-4.1.rst` ? Thanks in advance ! :)
> 
> @simonguinot what changes? There is nothing in there that's "release note worthy", or did I miss something important?

@kartben the change of behavior of the LED PWM sample ?

**Comment by kartben** [comment]
> > > > @bbilas @Mani-Sadhasivam @nashif @simonguinot Can you take a look?
> > > 
> > > 
> > > @yishai1999 It looks good to me but can you add the changes to `release-notes-4.1.rst` ? Thanks in advance ! :)
> > 
> > @simonguinot what changes? There is nothing in there that's "release note worthy", or did I miss something important?
> 
> @kartben the change of behavior of the LED PWM sample ?

Yeah, not really something that anyone really cares about seeing in the release notes IMO :) FWIW we're actually trying to document better what belongs to release notes and what doesn't so that it's clearer for folkdst https://github.com/zephyrproject-rtos/zephyr/pull/82542

**Comment by simonguinot** [comment]
> > > > > @bbilas @Mani-Sadhasivam @nashif @simonguinot Can you take a look?
> > > > 
> > > > 
> > > > @yishai1999 It looks good to me but can you add the changes to `release-notes-4.1.rst` ? Thanks in advance ! :)
> > > 
> > > 
> > > @simonguinot what changes? There is nothing in there that's "release note worthy", or did I miss something important?
> > 
> > 
> > @kartben the change of behavior of the LED PWM sample ?
> 
> Yeah, not really something that anyone really cares about seeing in the release notes IMO :) FWIW we're actually trying to document better what belongs to release notes and what doesn't so that it's clearer for folkdst #82542

ah ah ah :)

**Review by simonguinot — APPROVED** [review]

**Pull request merged**
