### PR TITLE
kernel/sched: Mark sleeping threads suspended

### LINKED ISSUE #9506: Ztest becomes unresponsive while running SMP tests
Issue: The tests in tests/kernel/smp when executed becomes unresponsive.

Sample log:

```
Running test suite smp
===================================================================
starting test - test_smp_coop_threads
PASS - test_smp_coop_threads
===================================================================
starting test - test_cpu_id_threads
```

Same set of tests when executed individually by commenting rest of the tests in testsuite like below:

```
 ztest_test_suite(smp,
/*           ztest_unit_test(test_smp_coop_threads),
*/
             ztest_unit_test(test_cpu_id_threads)
/*,
             ztest_unit_test(test_coop_resched_threads),
             ztest_unit_test(test_preempt_resched_threads),
             ztest_unit_test(test_yield_threads),
             ztest_unit_test(test_sleep_threads),
             ztest_unit_test(test_wakeup_threads),
             ztest_unit_test(test_wakeup_pending_threads)
*/
             );
    ztest_run_test_suite(smp);
```
the test case executes successfully.

Sample log:

```
Running test suite smp
===================================================================
starting test - test_cpu_id_threads
PASS - test_cpu_id_threads
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
```
It is the same case for all the test cases in smp. Cleanup of threads created is handled in test case already.
```
 ztest_test_suite(smp,
/*           ztest_unit_test(test_smp_coop_threads),
             ztest_unit_test(test_cpu_id_threads),
*/
             ztest_unit_test(test_coop_resched_threads)

/*,
             ztest_unit_test(test_preempt_resched_threads),
             ztest_unit_test(test_yield_threads),
             ztest_unit_test(test_sleep_threads),
             ztest_unit_test(test_wakeup_threads),
             ztest_unit_test(test_wakeup_pending_threads)
*/
             );
    ztest_run_test_suite(smp);

Execution log:

Running test suite smp
===================================================================
starting test - test_coop_resched_threads
PASS - test_coop_resched_threads
===================================================================
===================================================================

PROJECT EXECUTION SUCCESSFUL
```

Steps to reproduce:

```
cd tests/kernel/smp
mkdir build && cd build
cmake -DBOARD=esp32 ..
make flash
```

### PR DESCRIPTION
**Pull request by andyross**
On SMP, there was a bug where the logic that re-adds _current to the
run queue at swap time would accidentally reschedule threads that had
just gone to sleep, because the is_thread_prevented_from_running()
predicate only tests for threads that are "suspended" or "pending" and
not sleeping.

Overload _THREAD_SUSPENDED to indicate "sleeping" also.  Simple fix
for an immediate bug, though long term we really want to unify all the
blocked conditions to prevent this kind of state bug.

Fixes #9506

### CODE REVIEW

**Comment by gnuless** [comment]
My only concern about utilizing a flag (either repurposing an existing one, or making a new one) was being sure that every possible path that revives the thread would clear the flag (without clearing it went it shouldn't, in the case of a repurposed flag). I don't know enough about the scheduler to make a determination, but if you're satisfied that z_thread_timeout() and z_impl_k_wakeup() cover those paths, I believe you.

**Comment by gnuless** [comment]
Unfortunately this doesn't fix #9506.  The tests do not complete successfully, regardless of the number of tests enabled/disabled (as suggested the bug report).  There seems to be no rhyme or reason to how far the test proceeds before the board hangs, but I haven't seen it get past the first three, and typically it hangs on the first or second test.  Occasionally, after hanging for a long time (on the order of minutes) a test will suddenly proceed and complete.

**Comment by andyross** [comment]
Sigh.  Well, you found **a** bug for sure, just not the only one I guess.  I'll remove the Fixes note from the commit message and push another set.  Still running, but it looks like this allows us to re-enable SMP for a 15 test cases on x86_64, so it's still a win.  Give it another 20 minutes or so for more data and I'll push.

**Review by ghost — CHANGES_REQUESTED** [review]
I don't think we can overload _THREAD_SUSPENDED in this way, as it interferes with the original meaning. Consider a thread that calls k_sleep() - any call to k_thread_suspend() to suspend that thread (by another thread, obviously) will effectively be ignored, because the thread will lift its own suspension when its sleep timer expires.

Perhaps we should add another flag, _THREAD_SLEEPING?

**Comment by andyross** [comment]
I see your point, but the new behavior is AFAICT not any different than the old one.

Before, if you had a thread that entered k_sleep(), and you called k_thread_suspend(), it would be flagged SUSPENDED but not otherwise do anything.  If it then hit the sleep timeout while suspended, it would wake up even though it was supposed to have been still suspended!  Alternatively, if the k_thread_resume() call happened first, then the thread would resume synchronously even though it was still supposed to be sleeping.

Which is to say, we've always treated these states as effectively the same thing, and our docs seem to be silent on the original intent of mixing "suspend/resume" with "sleep/wakeup".  I think what you're imagining is a kernel design where "blocked" is the logical OR of the two (and of "pended"), but that's not actually what we've implemented.

And in fact longer term I'd like to see the APIs merge and be documented the same way (i.e. k_thread_suspend(k_current_get()) acts identically to sleep with an infinite timeout, and k_thread_resume()/k_wakeup() get documented as synonyms, with one being deprecated).  I don't see why we have historically split them like this.

**Review by ghost — APPROVED** [review]

**Comment by gnuless** [comment]
Fair enough.  That's not what the docs imply, from the Kernel API docs:

> Once suspended, a thread cannot be scheduled until another thread calls k_thread_resume() to remove the suspension.

Which, as you pointed out, is misleading and does not reflect the actual behavior.

**Review by dcpleung — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andyross** [comment]
Actually thinking about this, I'm convinced @gnuless is right and the behavior that we want, long-term, is for sleeping and wakeup to be orthogonal for the same reason that a SIGSTOP/SIGCONT is orthogonal to sleep() on a unix box.  That needn't affect this patch, since we don't do it right anyway, but we want to fix this going forward.

**Pull request merged**
