### PR TITLE
manifest: bsim: Do not import explicitly but keep copy in submanifests/

### LINKED ISSUE #57198: bsim module must be cloned for west to work
**Describe the bug**
When running west a prompt that looks like the following appears. 
`
FATAL ERROR: failed manifest import in bsim (tools/bsim)
  Failed importing "west.yml" from revision "908ffde6298a937c6549dbfa843a62caab26bfc5"
  Hint: for this to work:
          - bsim must be cloned
          - its manifest-rev ref must point to a commit with the import data
        To fix, run:
          west update
`
this seems to be a little backwards since it forces pulling in additional modules, outside of the minimum necessary to build.

**To Reproduce**
1. Follow the getting started guide but replace `west update` with `west update only_what_I_need`
2. Run a `west status`
You will get an error message that looks like the one above.
3. Run `west build -b qemu_x86 samples/hello_world/`, you get: `west: error: argument <command>: invalid choice: 'build'`
4. git revert 01a12f658 makes everything work again instantly (no need to re-init, update or anything)

**Expected behavior**
We should still be able to build without the bsim module. Or at least we should provide a work around to build without it.

**Environment (please complete the following information):**
 - OS: Seen on MacOS and Linux

### PR DESCRIPTION
**Pull request by aescolar**
Due to a limitation in the west import feature,
    a project cannot both have an import and be part of a group.
    Moreover, when a project has an import and is not filtered
    out, it is required for that project to be present
    for most west commands to work.
    
As the bsim project is not filtered by default,
    it causes trouble for users who never run a
    west update but try to use west further.
    
To work around this issue, let's disable the import
    in the bsim project, and instead copy its manifest
    into the submanifests/ folder.
    
Having a replica of the babblesim manifes in the submanifest
    folder is likely to cause some confusion in users,
    wrt to which version of components they are using.
    So whenever west supports both imports and groups, or another
    simple and nicer way of working around this, it should be used.

Fixes #57198

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]
Works great with this, thanks for fixing.

**Review by cfriedt — DISMISSED** [review]
Wow - @aescolar - this is amazing. Actually a very elegant solution. Thanks!

**Comment by cfriedt** [comment]
Again, not debating `bsim` at all - it is a great tool for BLE development.

I just wanted to add, that this fixes the issue that we at Meta had with including the external `bsim` manifest in `west.yml`. 

Easy repro recipe to validate the fix:
```
west init /tmp/zephyrproject
cd /tmp/zephyrproject/zephyr
curl -L -o /tmp/57361.patch 'https://github.com/zephyrproject-rtos/zephyr/pull/57361.patch'
git apply /tmp/57361.patch
west status &>/dev/null
echo $?
# 0
```

But in the interest of scalability, virtually everything in Zephyr should be optional (#54276). E.g. in order to run `native_posix`, `qemu_x86_64`, or `qemu_riscv64` tests, there were previously no other dependencies other than the main `zephyr` repo. That's a nice "feature" if you will, and we should preserve that.

Whether adding to `submanifests/` is OK with with the TSC is a separate story. I don't see any harm in adding `submanifests/bsim/west.yml`.

Meta would definitely prefer this solution though over needing to internally host one or more manifest repositories. We would prefer to continue being able to clone Zephyr as-is.

**Review by mbolivar-nordic — COMMENTED** [review]
This seems really error-prone since the manifests have to be kept in sync with each other, right?

**Review by carlescufi — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by cfriedt — DISMISSED** [review]
This works for me.

Again, thanks @aescolar, @carlescufi, @mbolivar-nordic, and everyone who put in effort to come to a mutually agreeable and technically sound solution here 👍

**Review by nashif — CHANGES_REQUESTED** [review]
do not think submanifests should be used for this, all modules/projects shall be in west.yaml. This is also differrs from the solution presented to the TSC without any objections.

**Comment by cfriedt** [comment]
> do not think submanifests should be used for this, all modules/projects shall be in west.yaml. This is also differrs from the solution presented to the TSC without any objections.

@nashif - @nordicjm made a good point to me (offline). This solution at least de-risks things for now from a policy perspective - i.e. avoids setting the precedent in a release that it is ok to add things to `west.yml` that require additional (possibly external) modules / a non-minimal clone.

It's completely valid though for Nordic and Oticon or anyone else to want to do Zephyr things and to do them upstream.

Maybe this just buys a bit more time to sort out a better technical solution? 🤷‍♂️ 

I would say it's a good thing to discuss at the TSC F2F..

**Comment by aescolar** [comment]
> this solution also works, without submanifests,..

@nashif Would you be so kind as to elaborate what is the concern with submanifests?
If the concern is that it would be in the submanifest folder, that can be solved by placing it anywhere else.
(Note also that from west point of view the submanifests/bsim/ folder is different than submanifests/, as west does not crawl subfolders, it is effectively just an unrelated folder).

(Note that what you wrote there does not actually work as is, though it is possible to dump the submanifests entries into the main manifest with some minor changes and it would work).

**Comment by aescolar** [comment]
Superseded by #59023

**Pull request closed without merging**
