### PR TITLE
rework extern "C" blocks in various include files

### PR DESCRIPTION
**Pull request by pabigot**
This PR collects fixes to #17997 specific to headers in the general include and driver area.  arch, soc, and other headers required to complete the task are not included in this PR to simplify reviewing.

### CODE REVIEW

**Review by vanwinkeljan — APPROVED** [review]
lvgl changes lgtm

**Review by jhedberg — APPROVED** [review]
Bluetooth changes look fine to me

**Review by jukkar — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
LGTM

**Pull request merged**
