### PR TITLE
soc: arm: new stm32f412vx device

### LINKED ISSUE #38966: Please add STM32F412VX
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
There are many kinds of STM32F4 microcontrollers. I am using the stm32f412ve in my project but this type is not maintained yet. In my opinion it is only the Kconfig, which is not maintained.

**Describe why you are asking for this support?**
I think this type is also widespread and should be mainline maintained. This support in hal_stm32 is given.

For me i fixed the issue temporarly.

**Additional context**
In Directory `soc/arm/st_stm32/stm32f4` i did:

add to _Kconfig.soc_:

```
config SOC_STM32F412VX
	bool "STM32F412VX"
```

add new file _Kconfig.defconfig.stm32f412vx_:
```
# ST STM32F412VX MCU configuration options
# SPDX-License-Identifier: Apache-2.0

if SOC_STM32F412VX

config SOC
	default "stm32f412vx"

config NUM_IRQS
	default 97

endif # SOC_STM32F412VX
```

### PR DESCRIPTION
**Pull request by FRASTM**
This adds a new stm32f412Vx in the list of stm32F4 devices.
The module stm32cube/stm32f4/soc/stm32f412vx.h exists

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/38966

Datasheet : [https://www.st.com/resource/en/datasheet/stm32f412ve.pdf](https://www.st.com/resource/en/datasheet/stm32f412ve.pdf)

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
This is good, but I'd like to take the opportunity to make some clean up in these f412 defconfig definitions:
- Let's group f412 definitions into a common Kconfig.defconfig.stm32f412xx (like done on f407)
- Let's rename SOC_STM32F412ZG and SOC_STM32F412CG to SOC_STM32F412ZX and SOC_STM32F412CX

This should allow minimizing further churn on these f412xx.

**Comment by FRASTM** [comment]
grouping  all Kconfig for the stm32f412  devices in the  ./soc/arm/st_stm32/stm32f4/Kconfig.defconfig.stm32f412xx
will remove the newly created ./soc/arm/st_stm32/stm32f4/Kconfig.defconfig.stm32f412vx (and also ./soc/arm/st_stm32/stm32f4/Kconfig.defconfig.stm32f412cx and ./soc/arm/st_stm32/stm32f4/Kconfig.defconfig.stm32f412zx)

**Comment by FRASTM** [comment]
includes:  the ./soc/arm/st_stm32/stm32f4/Kconfig.defconfig.stm32f412xx
+ board adapatatio with the new SOC_STM32F412CX

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
