### PR TITLE
drivers: flash: spi_nor: ensure paired calling of acquire/release_device

### PR DESCRIPTION
**Pull request by ndrs-pst**
Adjusted the code to guarantee resource release irrespective of operation success or failure.

### CODE REVIEW

**Comment by de-nordic** [comment]
@ndrs-pst Would it be possible for you to log Bug issue for this in Zephyr and change this to fix?
This would also require release note entry commit within this PR.

**Comment by de-nordic** [comment]
> > @ndrs-pst Would it be possible for you to log Bug issue for this in Zephyr and change this to fix? This would also require release note entry commit within this PR.
> 
> I'm ready to assist with the issue, but I want to ensure I understand your instructions correctly. Just to clarify, do you want me to open a Bug report in Zephyr for this issue and link it to this PR. Please confirm or provide further details if I've misunderstood.

As far as I can tell some of error paths would leave the device with semaphore taken? This seems like a bug to me.
Once there is bug, then this becomes fix for a bug.
Release notes entry is acknowledge that informs that bug existed and is now fixed: this is in case somebody has been seeing the issue but never reported it.

**Comment by ndrs-pst** [comment]
@de-nordic, just created issue https://github.com/zephyrproject-rtos/zephyr/issues/67336 that link to this PR

**Comment by de-nordic** [comment]
> @de-nordic, just created issue #67336 that link to this PR

OK, thanks. Add line to your commit message
```
Fixes #67336
```
and push the commit again.

**Review by anangl — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
