### PR TITLE
Bluetooth: controller: Various nRF51 related optimizations related to qualification

### PR DESCRIPTION
**Pull request by cvinayak**
This passes 183 of selected LL conformance tests on nRF51 SoCs. 
Controller on nRF51 SoCs will not support Privacy, Data Length Update and PHY update procedures.

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]
Did some basic mesh testing with this and the micro:bit, and nothing appears broken.

**Review by carlescufi — APPROVED** [review]
Limited testing shows no regressions. Additional test runs will be done with EBQ by @cvinayak

**Review by carlescufi — CHANGES_REQUESTED** [review]
Some EBQ tests not passing

**Comment by cvinayak** [comment]
Reverted a commit in this PR related to moving of RSSI implementation that was support to reduce ISR critical CPU time, but it broken some conf tests for nRF52. Re-testing on nRF51 after the revert, after which will re-test on nRF52.

**Comment by cvinayak** [comment]
Fixed a NULL pointer dereferencing hardfault seen during regression testing on nRF52 using the EBQ tester.

Also, a temporary workaround to avoid the Radio ISR experiencing a suspected latency that could cause it from completing on time. Investigating the reason for such an introduced ISR entry latency, meanwhile.

**Comment by carlescufi** [comment]
This PR might not be required at all after all. Will update soon.

**Comment by cvinayak** [comment]
The commits in this PR are required to fulfill the system sanity when advanced options like Fast Encryption setup implementation is enabled on nRF51 SoCs.

The workaround commit is removed from this PR, as the ISR latency was introduced by a local debug commit that locked IRQs around UART transmissions, there is no asserts/issue when it is removed.

Current set of commits in this PR has been regression tested with conformance tester on nRF52 and passes all its ICS selected 270 tests. 

The nRF51 is currently being tested again with the commits in this PR. Will update here well it completes.

**Review by nashif — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
