### PR TITLE
actions: publish docs every 3 hours

### PR DESCRIPTION
**Pull request by nashif**
Publish docs twice daily, this way fixes early in the morning are
reflects online same day.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Comment by gmarull** [comment]
is there any reason why we can't publish after every successful build from `main` ?

**Review by gmarull — APPROVED** [review]

**Comment by nashif** [comment]
> is there any reason why we can't publish after every successful build from `main` ?

this is going to be lots of publishing, we might think about doing this every few hours instead of the above, say every 3 hours...

**Comment by nashif** [comment]
changed to publish every 3 hours.

**Comment by gmarull** [comment]
@nashif missed the last push?

**Comment by nashif** [comment]
> @nashif missed the last push?

hmm, no, for some reason GH is not updating....

**Comment by nashif** [comment]
oh crap, I was pushing to the main repo

**Pull request merged**
