### PR TITLE
scripts: dts: convert test suites to pytest

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Use the pytest test framework in the dtlib.py and edtlib.py test
suites (testdtlib.py and testedtlib.py respectively).

The goal here is not to change what is being tested. The existing test
suite is excellent and very thorough.

However, it is made up of executable scripts where all of the tests
are run using a hand-rolled framework in a single function per file.
This is a bit all-or-nothing and prevents various nice features
available in the de-facto standard pytest test framework from being
used.

In particular, pytest can:

- drop into a debugger (pdb) when there is a problem
- accept a pattern which specifies a subset of tests to run
- print very detailed error messages about the actual and expected
  results in various traceback formats from brief to very verbose
- gather coverage data for the python scripts being tested (using a plugin)
- run tests in parallel (using a plugin)
- It's easy in pytest to run tests with temporary directories
  using the tmp_path and other fixtures. This lets us avoid
  temporarily dirtying the working tree as is done now.

Moving to pytest lets us leverage all of these things without any loss
in ease of use (in fact, some things are nicer in pytest):

- Any function that starts with "test_" is automatically picked up and
  run. No need for rolling up lists of functions into a test suite.
- Tests are written using ordinary Python 'assert'
  statements.
- Pytest magic unpacks the AST of failed asserts to print details on
  what went wrong in really nice ways. For example, it will show you
  exactly what parts of two strings that are expected to be equal
  differ.

For the most part, this is a pretty mechanical conversion:

- extract helpers and test cases into separate functions
- insert temporary paths and adjust tests accordingly to not match
  file names exactly
- use 'assert CONDITION' instead of 'if not CONDITION: fail()'

There are a few cases where making this happen required slightly
larger changes than that, but they are limited.

Update check_compliance.py accordingly, removing hacks that are no
longer needed.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
For reference, this is what an error would look like (I tested in an earlier force push of this PR with a function that fails on purpose):

deliberate-pytest-err

**Review by galak — COMMENTED** [review]
Since you've got to touch check_compliance.py would it be better to just move this to a github workflow action similar to what we have for sanitycheck and west (.github/workflows/sanitycheck_tests.yml & .github/workflows/west_cmds.yml) and remove it from check_compliance.py

**Review by galak — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
Looks like a good idea.

I don't really think it belongs in check_compliance.  Its just another thing that needs to be tested as part of any PR that might change the code.  If it could be invoked from `sanity_check` via something in `tests/unit/` that might be best.

Otherwise I guess a specific action that ran the python tests would be fine.  It just seems a little out of place (but I haven't been tracking the new actions-dependent CI stuff).

**Comment by mbolivar-nordic** [comment]
Should be good to go once BK and the docs build have time to finish, dropping DNM

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
