### PR TITLE
ESP32: Support for HAL v5.1

### PR DESCRIPTION
**Pull request by LucasTambor**
This PR adds the necessary changes to support HAL 5.1

Besides some minor updates to enable support for the new HAL, there are also some more substantial changes such as:
*  The use of pre compiled binaries for bootloader and partition-table (_Temporary_).
*  Power management support for ESP32S3
* Improvements in WiFi driver and WPA3 support for station mode

This PR will remain as a Draft until some known issues are solved.

Known issues:
* ESP32S3 can't boot when WIFI is enabled

Feel free to test it and give some feedback regarding code review, feature regression and/or any other issues found.
If you want to test it, don't forget to run the commands:
`west update hal_espressif` and  `west blobs fetch hal_espressif`

### CODE REVIEW

**Comment by LucasTambor** [comment]
Hi @gramsay0 , thanks for pointing that out. We have fixed it :)

**Comment by adolfogc** [comment]
Hi, I'm testing this branch and currently observe that the LED driver (using a PWM LED) is failing:

```
ERROR in CMAKE_SOURCE_DIR/src/bsp/led.cpp:29
```

Sample snippet:
```cpp
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/led.h>

// ...

static const struct device* l_led_pwm = DEVICE_DT_GET(DT_COMPAT_GET_ANY_STATUS_OKAY(pwm_leds));

// ... 

void init(void) {
    Q_ASSERT(device_is_ready(l_led_pwm));
}

void on(void) {
    int ret = led_on(l_led_pwm, 0);
    Q_ASSERT(ret >= 0); // <------------------------ fails here
}
```

**Comment by laurin** [comment]
Hey, I can run the hello_world on my ESP32-S3-DevKitC-1-N32R8V with the espressif hal 5.1 branch. (I am using the esp32s3_devkitm.conf board configuration).

However, when I flash mcuboot and an application to the device, the boot fails like this:

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
Octal Flash Mode Enabled
For OPI Flash, Use Default Flash Boot Mode      
mode:SLOW_RD, clock div:2
load:0x3fca0000,len:0x2580
load:0x40384000,len:0x400 
load:0x40384400,len:0x64a0
load:0x4038d000,len:0x2d0c
entry 0x40385f50
I (78) boot: MCUboot 2nd stage bootloader
I (78) boot: chip revision: v0.1
I (78) boot.esp32s3: Boot SPI Speed : 40MHz      
I (78) boot.esp32s3: SPI Mode       : SLOW READ  
I (81) boot.esp32s3: SPI Flash Size : 8MB        
I (85) boot: Enabling RNG early entropy source...


--- changed baud rate (57600 baud) ---


I (101) spi_flash: detected chip: generic
I (101) spi_flash: flash io: fastrd
E (101) spi_flash: Detected size(512k) smaller than the size in the binary image header(8192k). Probe failed.
```

I think it is weird that the detected size is 512kB while the flash is actually 32MB.

Sorry if that is not within the scope of this PR.

**Comment by EricNRS** [comment]
Are there patches for the zephyr repository as well?  Looks like a lot of filename changes as I immediately hit compilation errors:
```sh
west build -b esp32s3_devkitm --pristine --sysbuild samples/hello_world
In file included from/work/zephyr-latest/modules/hal/espressif/components/spi_flash/esp_flash_api.c:21:
/work/zephyr-latest/modules/hal/espressif/components/spi_flash/esp_flash_api.c: In function 'esp_flash_read_encrypted':
/work/zephyr-latest/modules/hal/espressif/zephyr/esp32s3/../../components/spi_flash/include/spi_flash_mmap.h:31:33: error: 'CONFIG_MMU_PAGE_SIZE' undeclared (first use in this function); did you mean 'CONFIG_FLASH_SIZE'?
   31 | #define SPI_FLASH_MMU_PAGE_SIZE CONFIG_MMU_PAGE_SIZE /**< Flash cache MMU mapping page size */
      |                                 ^~~~~~~~~~~~~~~~~~~~
/work/zephyr-latest/modules/hal/espressif/components/spi_flash/esp_flash_api.c:1313:34: note: in expansion of macro 'SPI_FLASH_MMU_PAGE_SIZE'
 1313 |     size_t map_src = address & ~(SPI_FLASH_MMU_PAGE_SIZE - 1);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~
/work/zephyr-latest/modules/hal/espressif/zephyr/esp32s3/../../components/spi_flash/include/spi_flash_mmap.h:31:33: note: each undeclared identifier is reported only once for each function it appears in
   31 | #define SPI_FLASH_MMU_PAGE_SIZE CONFIG_MMU_PAGE_SIZE /**< Flash cache MMU mapping page size */
      |                                 ^~~~~~~~~~~~~~~~~~~~
/work/zephyr-latest/modules/hal/espressif/components/spi_flash/esp_flash_api.c:1313:34: note: in expansion of macro 'SPI_FLASH_MMU_PAGE_SIZE'
 1313 |     size_t map_src = address & ~(SPI_FLASH_MMU_PAGE_SIZE - 1);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~
[91/235] Building C object zephyr/CMakeFiles/zephyr.dir/h...dules/hal/espressif/components/spi_flash/flash_mmap.c.obj
FAILED: zephyr/CMakeFiles/zephyr.dir/home/eric/work/zephyr-latest/modules/hal/espressif/components/spi_flash/flash_mmap.c.obj 
```

**Comment by EricNRS** [comment]
Any chance this will make it into the Zephyr 2.6 release?

**Comment by rftafas** [comment]
> Any chance this will make it into the Zephyr 2.6 release?

I think you mean 3.6, no, I don't think so. There is a new draft: https://github.com/zephyrproject-rtos/zephyr/pull/68760

**Pull request closed without merging**
