### PR TITLE
MAINTAINERS: Add Grzegorz (57300) as collaborator for build system

### PR DESCRIPTION
**Pull request by tejlmand**
Add Grzegorz Swiderski (57300) as collaborator for build system.

### CODE REVIEW

**Review by nashif — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
`Error parsing MAINTAINERS.yml: MAINTAINERS.yml: malformed 'collaborators' value for area 'Build system' -- should be a list of strings` uh oh... maybe add quotes around your username?

**Comment by carlescufi** [comment]
> `Error parsing MAINTAINERS.yml: MAINTAINERS.yml: malformed 'collaborators' value for area 'Build system' -- should be a list of strings` uh oh... maybe add quotes around your username?

Or maybe we need to fix the script?

**Comment by fabiobaltieri** [comment]
> Or maybe we need to fix the script?

I still think it may make sense to have it in quotes from a yaml parsing perspective.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> Problem with intelligent string / int type detection, it's never intelligent when you need it to be. Quotes added.

Thanks, let's see if the assigner script breaks next. :-)

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
