### PR TITLE
boards: soc: riscv: add QEMU RV32 virt board

### PR DESCRIPTION
**Pull request by katsuster**
This patch add definitions and settings for QEMU RV32 virt machine.
These are minimal supports only for CPU, Memory, CLINT and UART.

QEMU has supported multiple machine types. It seems virt machine
is most suitable for developing and testing SMP mode on rv32/rv64
both architecture using QEMU.

 | Support       | sifive_u | spike | virt  |
 +---------------+----------+-------+-------+
 | SMP           | yes      | yes   | yes   |
 | RV32/64       | 64       | 32/64 | 32/64 |
 | UART input    | yes      | no    | yes   |
 | Real machine? | yes      | no    | no    |

Signed-off-by: Katsuhiro Suzuki <katsuhiro@katsuster.net>

### CODE REVIEW

**Comment by katsuster** [comment]
I've fixed copyright warnings from scancode.

**Comment by katsuster** [comment]
I've fixed a CODEOWNER warning from Compliance check.

Is it OK to set my account for owner of new dts file? If NO, please comment it.

**Review by tyrantlizard77 — APPROVED** [review]
assuming you intend to use this as the test area for SMP enabling, this looks good to me

**Comment by andrewboie** [comment]
> Is it OK to set my account for owner of new dts file? If NO, please comment it.

Yes you should do this.

**Comment by katsuster** [comment]
Add USE_SWITCH and SMP options.

**Comment by katsuster** [comment]
Fix mistake, add IPI interface.

**Comment by katsuster** [comment]
It's better to add this PR onto #29105 PR, so close this PR.
Because buildkait can check CONFIG_SMP part.

Thanks a lot for review of @andrewboie .

**Pull request closed without merging**
