### PR TITLE
json: general cleanup of source code

### PR DESCRIPTION
**Pull request by Sir-Branch**
Removed extra lines, unnecessary variables and slight refactoring.

I've been creating multiple PRs that are easy to follow for ease of review and discussion, please let me know if this is frowned upon as it may cluster the history.

### CODE REVIEW

**Review by martinjaeger — COMMENTED** [review]
One empty line before a return statement is very common in the Zephyr codebase. Same for declaration of variables at the top of the function. So I'm not sure if the refactoring is really needed.

**Comment by Sir-Branch** [comment]
Appreciate the insight. I agree, I've updated the commit to only include modifications which improve readability/maintainability in my opinion:

- Improved while loop of lexer_number function
- Made explicit comparison to string terminator '\0'
- Reduced to single return point where it makes sense
- Eliminated unnecessary variables

PS: Also rebased for CI conflict

**Review by martinjaeger — COMMENTED** [review]
Honestly, I'm not sure if this "cleanup" really improves the code.

For example, I don't think that modifying function parameters inside the function body (as suggested for `json_escape_internal`) is particularly nice style. It also [violates MISRA rules](https://rules.sonarsource.com/c/tag/misra/RSPEC-1226).

Also the other parts of the code can just be left as is in my opinion, following the rule "never touch a running system". As it's partly a matter of taste I will not block the PR, but I will also not approve.

**Comment by cfriedt** [comment]
@mrfuchs - can you please review?

**Comment by mrfuchs** [comment]
> @mrfuchs - can you please review?

I agree with @martinjaeger. I'm not sure this patch improves the code quality/readability. However, it unnecessarily moves the code a little bit more away from the [original author's code](https://github.com/lpereira/lwan/blob/master/src/samples/techempower/json.c) (which is still maintained) -- something that I would avoid, if possible.

**Comment by Sir-Branch** [comment]
Thanks I really appreciate both reviews, seeing all these things you have pointed out I agree that this PR is mostly counter productive. I'll go ahead and close it out.

**Pull request closed without merging**
