### PR TITLE
scripts: compliance: add a compliance check to keep blocks of code sorted

### PR DESCRIPTION
**Pull request by fabiobaltieri**
scripts: compliance: add a compliance check to keep blocks of code sorted

This allows defining a list within two marker (zephyr-keep-sorted-start and zephyr-keep-sorted-stop), and have the CI validate that the block is kept sorted every time stuff gets added to it.

This is mainly for Kconfig and CMake include lists so that there's no ambiguity on where to add new stuff.

### CODE REVIEW

**Comment by nashif** [comment]
nice :)

**Review by keith-zephyr — DISMISSED** [review]

**Comment by keith-zephyr** [comment]
Can you also update the [Kconfig Tips document](https://docs.zephyrproject.org/latest/build/kconfig/tips.html) to reference these new markers?  I'm not sure if there is a good spot to mention this for the CMake files.

**Review by stephanosio — CHANGES_REQUESTED** [review]
I find the approach proposed in this PR to be too limiting to be of practical use; for example:

1. There has to be exactly one list element per line.
    * What if you have a list where each element may span across multiple lines due to line length limit or other syntactical and style-related requirements?
1. There cannot exist any variation among the list elements.
    * What if I want to mix `add_subdirectory_ifdef` and `add_subdirectory_ifndef` in the same list?
    * What if I want to add a comment above `add_subdirectory_ifdef`?

If we are introducing something like `zephyr-keep-sorted-start` and `zephyr-keep-sorted-stop`, we would want it to be capable of handling the cases like the above; if not, it will likely end up not being very useful or dragging anything that is placed inside the `zephyr-keep-sorted` block with its own limitations.

**Comment by fabiobaltieri** [comment]
>        * What if you have a list where each element may span across multiple lines due to line length limit or other syntactical and style-related requirements?

Ok good point, changed so it ignores blank lines and comments within the block, and so it detects multi-line entries, just checking for lines starting with spaces or tabs, nothing super fancy.

This way you add comments and it won't complain about it, it also allowed to do the subsys and driver lists in a single block.

>     2. There cannot exist any variation among the list elements.
>        
>        * What if I want to mix `add_subdirectory_ifdef` and `add_subdirectory_ifndef` in the same list?

That I have problems with, I can fairly easily add a set of string substitutions while reading the line to discard the known suffixes (_ifdef, _ifndef), but then I feel like the resulting order would become a bit of a nightmare to understand and you could not really just grab the block and sort it from the editor (which is the common case I had in mind). I would rather live with the compromise that unconditionals, _ifdef and_ifndef are grouped together and accept it as a limitation of the tool, at least for now.

The alternative would be to make the error propose a "correct list" that one could copy paste but it sounds like a very cumbersome thing to use (talking from first hand experience, we have some internal tooling that sorts python include list, it's not just lexicographical and I find it very frustrating).

>        * What if I want to add a comment above `add_subdirectory_ifdef`?

Handled.

**Review by keith-zephyr — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Rebased.

**Review by keith-zephyr — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Rebased :-)

**Review by kartben — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
