### PR TITLE
west.yml: Update libmetal and open-amp for v2023.10 release

### PR DESCRIPTION
**Pull request by arnopo**
Update to the last relase of open-amp library
The libmetal is updated to a more recebnt commit to integrate 2 zephyr commits on top of the v2023.10 release.

### CODE REVIEW

**Comment by carlescufi** [comment]
```
INFO    - /__w/zephyr/zephyr/twister-out/nrf5340bsim_nrf5340_cpuapp/samples/subsys/logging/multidomain/sample.logging.multidomain.ipc_static_vrings.simu/handler.log
ERROR   - d_00: @00:00:00.000000  (CPU:1): *** Booting Zephyr OS build zephyr-v3.5.0-1999-gc4cb59af6464 ***
d_00: @00:00:00.000000  (CPU:1): IPC-service REMOTE [INST 1] demo started
d_00: @00:00:00.037842  (CPU:0): *** Booting Zephyr OS build zephyr-v3.5.0-1999-gc4cb59af6464 ***
d_00: @00:00:00.037842  (CPU:0): Hello World! nrf5340bsim_nrf5340_cpuapp
d_00: @00:00:00.037842  (CPU:0): [00:00:00.000,000] <inf> app: IPC-service HOST [INST 1] demo started
d_00: @00:00:02.000031  (CPU:0): [00:00:01.000,030] <inf> app: ipc open 0
ipc_service_register_endpoint() failure
```

**Comment by arnopo** [comment]
> ```
> INFO    - /__w/zephyr/zephyr/twister-out/nrf5340bsim_nrf5340_cpuapp/samples/subsys/logging/multidomain/sample.logging.multidomain.ipc_static_vrings.simu/handler.log
> ERROR   - d_00: @00:00:00.000000  (CPU:1): *** Booting Zephyr OS build zephyr-v3.5.0-1999-gc4cb59af6464 ***
> d_00: @00:00:00.000000  (CPU:1): IPC-service REMOTE [INST 1] demo started
> d_00: @00:00:00.037842  (CPU:0): *** Booting Zephyr OS build zephyr-v3.5.0-1999-gc4cb59af6464 ***
> d_00: @00:00:00.037842  (CPU:0): Hello World! nrf5340bsim_nrf5340_cpuapp
> d_00: @00:00:00.037842  (CPU:0): [00:00:00.000,000] <inf> app: IPC-service HOST [INST 1] demo started
> d_00: @00:00:02.000031  (CPU:0): [00:00:01.000,030] <inf> app: ipc open 0
> ipc_service_register_endpoint() failure
> ```

Regression is introduced by https://github.com/OpenAMP/libmetal/pull/244

but something seems not clean in the test as the `libmetal_setup `is called twice time per CPU.
Here is a trace with some added printk.
```
@00:00:00.000000  (CPU:1): *** Booting Zephyr OS build zephyr-v3.5.0-1999-gc4cb59af6464 ***
d_00: @00:00:00.000000  (CPU:1): IPC-service REMOTE [INST 1] demo started
d_00: @00:00:00.000000  (CPU:1): ipc1_entry, 59
d_00: @00:00:00.000000  (CPU:1): ipc_service_open_instance, 21
d_00: @00:00:00.000000  (CPU:1): libmetal_setup, 81 start 
d_00: @00:00:00.000000  (CPU:1): metal_init: _metal.common.ref_count 0
d_00: @00:00:00.000000  (CPU:1): libmetal_setup, 111 end 
d_00: @00:00:00.037842  (CPU:0): *** Booting Zephyr OS build zephyr-v3.5.0-1999-gc4cb59af6464 ***
d_00: @00:00:00.037842  (CPU:0): Hello World! nrf5340bsim_nrf5340_cpuapp
d_00: @00:00:00.037842  (CPU:0): [00:00:00.000,000] <inf> app: IPC-service HOST [INST 1] demo started
d_00: @00:00:00.037842  (CPU:0): ipc1_entry, 58
d_00: @00:00:00.037842  (CPU:0): ipc_service_open_instance, 21
d_00: @00:00:00.037842  (CPU:0): libmetal_setup, 81 start 
d_00: @00:00:00.037842  (CPU:0): metal_init: _metal.common.ref_count 0
d_00: @00:00:00.037842  (CPU:0): libmetal_setup, 111 end 
d_00: @00:00:00.037842  (CPU:0): [00:00:00.000,000] <err> ipc_service: Register endpoint logging
d_00: @00:00:00.037842  (CPU:0): register_ept : 431 start
d_00: @00:00:00.037842  (CPU:0): register_ept : 452 end 
d_00: @00:00:01.000040  (CPU:1): register_ept : 431 start
d_00: @00:00:01.000040  (CPU:1): ipc_rpmsg_register_ept : 55 start 
d_00: @00:00:01.000040  (CPU:1): rpmsg_create_ept : 275 start 
d_00: @00:00:01.000040  (CPU:1): ipc_service_open_instance, 21
d_00: @00:00:01.000040  (CPU:1): libmetal_setup, 81 start 
d_00: @00:00:01.000040  (CPU:1): metal_init: _metal.common.ref_count 1
d_00: @00:00:01.000040  (CPU:1): libmetal_setup, 111 end 
d_00: @00:00:01.000040  (CPU:1): register_ept : 431 start
d_00: @00:00:01.000040  (CPU:1): ipc_rpmsg_register_ept : 55 start 
d_00: @00:00:01.000040  (CPU:1): rpmsg_create_ept : 275 start 
d_00: @00:00:02.000031  (CPU:0): ipc1_entry, 63
d_00: @00:00:02.000031  (CPU:0): ipc_service_open_instance, 21
d_00: @00:00:02.000031  (CPU:0): libmetal_setup, 81 start 
d_00: @00:00:02.000031  (CPU:0): metal_init: _metal.common.ref_count 1
d_00: @00:00:02.000031  (CPU:0): libmetal_setup, 111 end 
d_00: @00:00:02.000031  (CPU:0): [00:00:01.000,030] <inf> app: ipc open 0
d_00: @00:00:02.000031  (CPU:0): [00:00:01.000,030] <err> ipc_service: Register endpoint ipc1
d_00: @00:00:02.000031  (CPU:0): register_ept : 431 start
d_00: @00:00:02.000031  (CPU:0): register_ept : 452 end 
d_00: @00:00:16.564026  (CPU:1): rpmsg_create_ept : 313 end 
d_00: @00:00:16.564026  (CPU:1): ipc_rpmsg_register_ept : 69  end ret = -2002
d_00: @00:00:16.564026  (CPU:1): ipc_service_register_endpoint() failure ( -22)
d_00: @00:00:16.564026  (CPU:1): rpmsg_create_ept : 313 end 
d_00: @00:00:16.564026  (CPU:1): ipc_rpmsg_register_ept : 69  end ret = -2002
d_00: @00:00:16.564026  (CPU:1): ASSERTION FAIL [err >= 0] @ WEST_TOPDIR/zephyr/subsys/logging/backends/log_multidomain_backend.c:202
d_00: @00:00:16.564026  (CPU:1): @ WEST_TOPDIR/zephyr/lib/os/assert.c:43
```


@carlocaione, @carlescufi: Do you have any idea what could be causing this behavior? I don't see anything wrong in the sample project that could explain it.

**Comment by carlescufi** [comment]
> @carlocaione, @carlescufi: Do you have any idea what could be causing this behavior? I don't see anything wrong in the sample project that could explain it.

No, not directly. Perhaps @emob-nordic or @nordic-krch may know something about it.

**Comment by emob-nordic** [comment]
> > @carlocaione, @carlescufi: Do you have any idea what could be causing this behavior? I don't see anything wrong in the sample project that could explain it.
> 
> No, not directly. Perhaps @emob-nordic or @nordic-krch may know something about it.

Not an expert in openAMP

**Comment by arnopo** [comment]
I think I found the issue:


meta_init is acalled a first time in [ipc1_entry()](https://elixir.bootlin.com/zephyr/v3.5.0/source/samples/subsys/logging/multidomain/remote/src/ipc_service.c#L44)
```c
    ipc_service_open_instance() 
        backend->open_instance()  that point to subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c : open()
            ipc_static_vrings_init()
                libmetal_setup()
                    metal_init()
```
        	
asecond time in [https://elixir.bootlin.com/zephyr/v3.5.0/source/subsys/logging/backends/log_backend_ipc_service.c#L49)
``` 
    init()
       backend_remote->transport_api->init(backend_remote); that point to backend_ipc_service_init()
           ipc_service_open_instance()
              backend->open_instance()  that point to subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c : open()
                  ipc_static_vrings_init()
                      libmetal_setup()
                         metal_init()
```

What is strange is that the patch added in lmetal_init prevent to reinitialise if alrteady initialised.
And the issue here is that the test fails if the libmetal is not reinitialised by `backend_ipc_service_init`

From my analysis the bug is in the zephyr part... What is the objective of the log backend? can we disable it for test?

**Comment by nordic-krch** [comment]
unfortunately I have not idea what's going on there. There are two different instances of ipc backends one for sample and one for logging so `ipc_service_open_instance()` is called twice but with different instace.

**Comment by carlocaione** [comment]
@arnopo 
> What is strange is that the patch added in metal_init prevents to reinitialize, if already initialized.
> And the issue here seems that the test fails if the libmetal is not reinitialized by `backend_ipc_service_init`

I'm a bit lost here. The `libmetal` patch is simply returning `0` if the metal singleton has been already initialised, how that is making the sample failing?

@nordic-krch 
> unfortunately I have not idea what's going on there. There are two different instances of ipc backends one for sample and one for logging so ipc_service_open_instance() is called twice but with different instace.

Yes, but why that would be a problem?

**Comment by arnopo** [comment]
> @arnopo
> 
> > What is strange is that the patch added in metal_init prevents to reinitialize, if already initialized.
> > And the issue here seems that the test fails if the libmetal is not reinitialized by `backend_ipc_service_init`
> 
> I'm a bit lost here. The `libmetal` patch is simply returning `0` if the metal singleton has been already initialised, how that is making the sample failing?

Yes that why I suspect an issue in Zephyr. 
whithout the libmetal patch  


> @arnopo
> 
> > What is strange is that the patch added in metal_init prevents to reinitialize, if already initialized.
> > And the issue here seems that the test fails if the libmetal is not reinitialized by `backend_ipc_service_init`
> 
> I'm a bit lost here. The `libmetal` patch is simply returning `0` if the metal singleton has been already initialised, how that is making the sample failing?

That why i suspect a bug in the zephyr part.
the test is working well if following code is executed twice time:
https://github.com/OpenAMP/libmetal/blob/main/lib/init.c#L17-L26

I perform further tests. seems that the issue is linked to the `_metal.common.generic_device_list`
Following dirty patch fix the issue:
```c
@@ -11,8 +11,11 @@ int metal_init(const struct metal_init_params *params)
 {
 	int error = 0;
 
-	if (_metal.common.ref_count++ != 0)
+	if (_metal.common.ref_count++ != 0) {
+		metal_list_init(&_metal.common.generic_device_list);
 		return 0;
+	}
```
So the issue is around the metal_register_generic_device call

**Comment by carlocaione** [comment]
@arnopo

I'm confused how `metal_init()` is supposed to be accessed concurrently:

```c
// _metal.common.ref_count is 0

if (_metal.common.ref_count++ != 0)
    return 0;
// _metal.common.ref_count is 1

memset(&_metal, 0, sizeof(_metal));
// _metal.common.ref_count is 0 (again)

...
++_metal.common.ref_count;
// _metal.common.ref_count is 1
```

**Comment by arnopo** [comment]
> @arnopo
> 
> I'm confused how `metal_init()` is supposed to be accessed concurrently:
> 
> ```c
> // _metal.common.ref_count is 0
> 
> if (_metal.common.ref_count++ != 0)
>     return 0;
> // _metal.common.ref_count is 1
> 
> memset(&_metal, 0, sizeof(_metal));
> // _metal.common.ref_count is 0 (again)
> 
> ...
> 
> ++_metal.common.ref_count;
> // _metal.common.ref_count is 1
> ```

It is a standard call counter to avoid reinitializing several times, but also to deinitialize only when all users have released the libmetal.

The confusion can come from the `memset(&_metal, 0, sizeof(_metal))` that resets the `_metal.common.ref_count`, leading to it be increased a  second time.

**Comment by carlescufi** [comment]
@carlocaione @arnopo any progress here? do we need to discuss this in a meeting?

**Comment by carlocaione** [comment]
> @carlocaione @arnopo any progress here? do we need to discuss this in a meeting?

I took a look at the problem but it is very, very puzzling to me why that commit is breaking `bsim`. I honestly do not exclude that the problem is in `bsim` itself. I spent a few hours but was unable to find the root cause.

On my side I need a bit more time to debug this because so far nothing stands out as wrong on the Zephyr / libmetal / open-amp side.

**Comment by arnopo** [comment]
> > @carlocaione @arnopo any progress here? do we need to discuss this in a meeting?
> 
> I took a look at the problem but it is very, very puzzling to me why that commit is breaking `bsim`. I honestly do not exclude that the problem is in `bsim` itself. I spent a few hours but was unable to find the root cause.
> 
> On my side I need a bit more time to debug this because so far nothing stands out as wrong on the Zephyr / libmetal / open-amp side.

I don't have any more bandwidth this week for a deeper investigation ( and probably not the week after also). If it's blocking, we can revert the commit on top of the release and create an issue.
However, there is a risk that the issue will be given low priority.

**Comment by arnopo** [comment]
@carlocaione @carlescufi 

I think I found the issue.
The issue is in In [ipc_static_vrings.c](https://elixir.bootlin.com/zephyr/latest/source/subsys/ipc/ipc_service/lib/ipc_static_vrings.c
)

We are calling `metal_device_open()` twice with the same device name `SHM_DEVICE_NAME`
From libmetal percpective there is only one instance of libmetal with several devices. These devices are identified by a name.
Therefore, since we have two device instances, we should have two different names.

Prior to the fix in libmetal, it appeared to be working because we initilaze libmetal and allocated resources for one instance. then we clean-up libmetal and reinitialized libmetal for the second instance.

I fixed the issue with following quick and dirty patch:

```diff
@@ -7,13 +7,18 @@
 #include <zephyr/ipc/ipc_static_vrings.h>
 #include <zephyr/cache.h>
 
 #define SHM_DEVICE_NAME		"sram0.shm"
 
+#define SHM_DEVICE_NAME1	"sram1.shm"
+
 #define RPMSG_VQ_0		(0) /* TX virtqueue queue index */
 #define RPMSG_VQ_1		(1) /* RX virtqueue queue index */
 
+
+static unsigned int static_vring_cnt = 0;
+
 static void ipc_virtio_notify(struct virtqueue *vq)
 {
 	struct ipc_static_vrings *vr;
 
 	vr = CONTAINER_OF(vq->vq_dev, struct ipc_static_vrings, vdev);
@@ -86,11 +91,12 @@ static int libmetal_setup(struct ipc_static_vrings *vr)
 	err = metal_register_generic_device(&vr->shm_device);
 	if (err != 0) {
 		return err;
 	}
 
-	err = metal_device_open("generic", SHM_DEVICE_NAME, &device);
+	err = metal_device_open("generic",  static_vring_cnt? SHM_DEVICE_NAME1 : SHM_DEVICE_NAME,
+				&device);
 	if (err != 0) {
 		return err;
 	}
 
 	vr->shm_io = metal_device_io_region(device, 0);
@@ -164,11 +170,11 @@ int ipc_static_vrings_init(struct ipc_static_vrings *vr, unsigned int role)
 
 	if (!vr) {
 		return -EINVAL;
 	}
 
-	vr->shm_device.name = SHM_DEVICE_NAME;
+	vr->shm_device.name = static_vring_cnt? SHM_DEVICE_NAME1 : SHM_DEVICE_NAME;
 	vr->shm_device.num_regions = 1;
 	vr->shm_physmap[0] = vr->shm_addr;
 
 	metal_io_init(vr->shm_device.regions, (void *) vr->shm_addr,
 		      vr->shm_physmap, vr->shm_size, -1, 0, NULL);
@@ -176,10 +182,12 @@ int ipc_static_vrings_init(struct ipc_static_vrings *vr, unsigned int role)
 	err = libmetal_setup(vr);
 	if (err != 0) {
 		return err;
 	}
 
+	static_vring_cnt++;
+
 	return vq_setup(vr, role);
 }

```
I think the  `ipc_static_vrings_init ` caller should provide the "vr->shm_device.name" based on a specific name (based on DT?)

**Comment by jhedberg** [comment]
@carlescufi @carlocaione @arnopo any progress on this? What are the next steps? I'm interested, since this seems to be indirectly blocking the progress of #65908 :)

**Comment by carlocaione** [comment]
I'll try to find sometimes to fix this next week. Please note that this should be trivial to fix if you want to progress yourself: it is simply matter of setting `vr->shm_device.name` to the instance name gathered from DT.

**Comment by arnopo** [comment]
I have something on my side, I'm preparing a PR
```diff
--------- subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c ----------
index dcbff7b360..20e29604fa 100644
@@ -555,6 +555,7 @@ static int open(const struct device *instance)
 
 	data->vr.notify_cb = virtio_notify_cb;
 	data->vr.priv = (void *) conf;
+	data->vr.shm_device.name = instance->name;
 
 	err = ipc_static_vrings_init(&data->vr, conf->role);
 	if (err != 0) {

---------------- subsys/ipc/ipc_service/lib/ipc_static_vrings.c ----------------
index be6c365a02..f6ca553fcc 100644
@@ -88,7 +88,7 @@ static int libmetal_setup(struct ipc_static_vrings *vr)
 		return err;
 	}
 
-	err = metal_device_open("generic", SHM_DEVICE_NAME, &device);
+	err = metal_device_open("generic", vr->shm_device.name, &device);
 	if (err != 0) {
 		return err;
 	}
@@ -166,7 +166,8 @@ int ipc_static_vrings_init(struct ipc_static_vrings *vr, unsigned int role)
 		return -EINVAL;
 	}
 
-	vr->shm_device.name = SHM_DEVICE_NAME;
+	if ( vr->shm_device.name == NULL)
+		vr->shm_device.name = SHM_DEVICE_NAME;
 	vr->shm_device.num_regions = 1;
 	vr->shm_physmap[0] = vr->shm_addr;
```

**Comment by arnopo** [comment]
Pull request that should fix the issue: https://github.com/zephyrproject-rtos/zephyr/pull/66525

**Comment by arnopo** [comment]
@carlescufi,  @carlocaione 
I rebased on top of the main branch. Now  the CI is Ok

**Review by carlocaione — DISMISSED** [review]

**Review by carlocaione — DISMISSED** [review]

**Comment by arnopo** [comment]
My bad, seems that i made a merge error in https://github.com/zephyrproject-rtos/libmetal/commit/55aac79513bd7a81c71040e7c8986f8d5d3aa496
Files that have been deleted in the libmetal library repo are still present  in the Zephyr libmetal repo.
I will send a new PR to fix that and update this one

**Review by carlocaione — DISMISSED** [review]

**Comment by arnopo** [comment]
update after merge of https://github.com/zephyrproject-rtos/libmetal/pull/24

**Review by jhedberg — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Comment by carlescufi** [comment]
Waiting for a re-ack from @carlocaione and I'll merge

**Comment by carlescufi** [comment]
> Waiting for a re-ack from @carlocaione and I'll merge

On second thought, nothing has changed and Carlo may be on holiday so merging.

**Pull request merged**
