### PR TITLE
LwM2M: Support optional resources per LwM2M Spec

### PR DESCRIPTION
**Pull request by mike-scott**
This patchset adds support for handling resources which are marked "optional".  This is to say that the LwM2M objects in Zephyr won't setup these resources by default.   If desired, user sample code can implement the backing buffers and handling.

### CODE REVIEW

**Comment by mike-scott** [comment]
@therealprof @rbtchc Let me know if you can help review and/or test.

**Comment by mike-scott** [comment]
FYI, on real hardware this adds about 300 bytes of flash (due to handling of optional flag) and 320 bytes of RAM usage (due to new data flag in resource instance structure).

**Review by therealprof — APPROVED** [review]
Tested on a Nucleo-F429ZI. LGTM and makes a lot of sense.

**Review by jukkar — APPROVED** [review]
LGTM

**Pull request merged**
