### PR TITLE
tests: boards: remove intel_s1000_crb tests

### PR DESCRIPTION
**Pull request by jenmwms**
This commit removes the tests for intel_s1000_crb based on
the discussion in #20017 to convert to new GPIO API.

Signed-off-by: Jennifer Williams <jennifer.m.williams@intel.com>

### CODE REVIEW

**Review by chen-png — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
I do not see any discussion or any reasoning why this is being removed. This test does have more than GPIO and I am not following why we are removing it instead of fixing it.

**Comment by nashif** [comment]
Also note that this test was actually 2 tests or applications, one of which was placed inside the other (cache).

**Comment by jenmwms** [comment]
> I do not see any discussion or any reasoning why this is being removed. This test does have more than GPIO and I am not following why we are removing it instead of fixing it.

Thanks. I was assigned to remove it. I will ask for explanation on #20017 commentary and update the commit.

**Review by dcpleung — CHANGES_REQUESTED** [review]
The idea is to convert the GPIO API calls to new API. If the existing tests can be covered by the new `gpio_basic_api` and/or `gpio_1pin_api` tests, then remove those tests. However, the `intel_s1000_crb` samples have things other than GPIO. So this should be not removed as a whole.

**Comment by jenmwms** [comment]
> The idea is to convert the GPIO API calls to new API. If the existing tests can be covered by the new `gpio_basic_api` and/or `gpio_1pin_api` tests, then remove those tests. 

Thanks! There is no PR for `gpio_basic_api`, and no PR or mention of `gpio_1pin_api`. At this time it is not clear if those will cover the basic gpio tests for s1000 here, so proceed with converting (rather than removing)?  It might be duplicate effort since these new tests might cover whats needed here for s1000 tests.

> However, the `intel_s1000_crb` samples have things other than GPIO. So this should be not removed as a whole.

Thanks! That was unclear from the instruction. I will take a closer look.

**Comment by galak** [comment]
Going to close this PR in favor of #21983.  Re-open if any issues.

**Pull request closed without merging**
