### PR TITLE
drivers: pinctrl: gecko: Fix location configuration for I2C

### LINKED ISSUE #74420: drivers: pinctrl: gecko: I2C pinout configuration broken for Series 1 and Series 2
**Describe the bug**
I2C pins get incorrectly configured on Silabs boards.

On boards with Series 1 devices (e.g. `slstk3701a`), the route location of the SCL pin is wrongly set.

On boards with Series 2 devices (e.g. `xg24_dk2601b`), the DBUS port/pin selection is wrongly set.

This is a regression introduced in https://github.com/zephyrproject-rtos/zephyr/pull/69649/commits/13cb35d8ec6f9df5964a4cb6d5437720a10ba361 when pinctrl was implemented for I2C on Silabs devices.

**To Reproduce**
Series 1: Attempt to configure I2C to location 7 by using `GECKO_LOC(I2C_SCL, 7)` as part of the pinctrl selection. Observe that SCL is configured to location 5 instead.

Series 2: Attempt to configure I2C to any port/pin combination such as PC5 using `GECKO_PSEL(I2C_SDA, C, 5)` as part of pinctrl selection. Observe that the pin value is set to the value of `GECKO_LOC()` instead, and port is always set to port A.

**Expected behavior**
Series 1: SCL is configured to location 7.

Series 2: Port/pin is configured to the port and pin given by `GECKO_PSEL()` selection.

**Impact**
Prevents I2C from working on Silabs boards.

### PR DESCRIPTION
**Pull request by asmellby**
I2C location configuration in the gecko pinctrl driver was broken for Series 1 and Series 2. Series 1 cleared the wrong bitmask when writing location, while Series 2 used the wrong values entirely due to port/pin info not being available in the `*_LOC` case.

With these fixes, I am able to communicate with the Si7021 RHT sensor on boards from both series.

Fixes #74420

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by jerome-pouiller — APPROVED** [review]
I hope one day we will be able to get rid of the `#ifdef` in the code.

**Comment by aescolar** [comment]
@asmellby If this is a bug, would you be so kind as to label it "bug" and create an accompanying bug report.

**Comment by jhedberg** [comment]
> @asmellby If this is a bug, would you be so kind as to label it "bug" and create an accompanying bug report.

I'd have thought "Fix ..." in the subject implies that, whereas the "bug" label is primarily for issues. But I certainly agree that now that we're in the stabilization phase all PRs which are bug fixes should have an accompanying "Fixes ..." link.

**Comment by asmellby** [comment]
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/74420.

**Pull request merged**
