### PR TITLE
soc: arm: gigadevice: use common API headers

### PR DESCRIPTION
**Pull request by gmarull**
Stop relying on <soc.h> to access HAL APIs. Use generic, per-API headers
instead. Note that <soc.h> has been left as is for now, since ARM MPU
relies on a fragile chain of includes/type definitions.

This change should improve compilation efficiency, as we no longer pull
APIs that are not needed. A similar approach is followed by STM32
drivers.

Related to https://github.com/zephyrproject-rtos/zephyr/pull/46147 and https://github.com/zephyrproject-rtos/zephyr/issues/41543

### CODE REVIEW

**Comment by gmarull** [comment]
cc: @cameled

**Comment by nandojve** [comment]
Please update PR with hash code from hal_gigadevice.

**Comment by gmarull** [comment]
> Please update PR with hash code from hal_gigadevice.

done

**Review by nandojve — APPROVED** [review]
CC: @soburi

**Review by martinjaeger — APPROVED** [review]
LGTM

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by soburi** [comment]
@gmarull  @nandojve
 
> CC: @soburi

LGTM

**Pull request merged**
