### PR TITLE
Bluetooth: Mesh: Provisioning Start Fix

### PR DESCRIPTION
**Pull request by WilliamGFish**
Resolves issue with the Bluetooth mesh provisioning process. Provisioning device would not fully complete initiation steps.

Signed-off-by: William Fish william.fish@manulytica.com

### CODE REVIEW

**Review by trond-snekvik — APPROVED** [review]

**Review by trond-snekvik — CHANGES_REQUESTED** [review]
@WilliamGFish the two commits need to merged into one with a sign-off line.

**Comment by WilliamGFish** [comment]
I know but I struggle using git and PR in zephyr, I end up causing more problems as I try to resolve PR comment issues. can you help?

**Comment by jhedberg** [comment]
@WilliamGFish could you still remove the redundant second "Bluetooth: Mesh: Provisioning Start Fix" line in the commit message? (you can accomplish this with `git commit --amend` and `git push --force` to the PR branch)

**Comment by jhedberg** [comment]
@WilliamGFish you'll also need to fix this compliance check failure:
```
a71e6eb41bb516ac466528ee3394f21a1002b47a: author email (WilliamGFish <william.fish@manulytica.com>) needs to match one of the signed-off-by entries.
24
a71e6eb41bb516ac466528ee3394f21a1002b47a: author email (WilliamGFish <william.fish@manulytica.com>) does not follow the syntax: First Last <email>.
```

**Comment by jhedberg** [comment]
@WilliamGFish btw, all of this should be automatic if you've configured git correctly (with the right author name and email information) and use `git commit -s` to auto-generate the Signed-off-by line.

**Comment by jhedberg** [comment]
@WilliamGFish changing the git commit author field is accomplished with `git commit --amend --author="Author Name <author@email.com>`, or by fixing your git configuration and just doing `git commit --amend --reset-author`

**Comment by jhedberg** [comment]
@WilliamGFish if you haven't done so already, you probably want to add the following to `~/.gitconfig` so that you don't ever need to think about this again:
```
[user]
	name = William Fish
	email = william.fish@manulytica.com
```

**Review by jhedberg — APPROVED** [review]

**Review by trond-snekvik — APPROVED** [review]

**Pull request merged**
