### PR TITLE
tests: bsim: Bluetooth: CAP broadcast AC testing updates 

### LINKED ISSUE #67050: LE Audio: Controller: Config settings with 44.1 kHz and 48 kHz are rejected at LE Create BIG
**Describe the bug**
Not high prio, posting just for the record:

Zephyr controller rejects the LE Create BIG if the fallowing config settings are used:
- 441_1
- 441_2
- 48_1
- 48_2
- 48_3
- 48_4
- 48_5
- 48_6

When the Zephyr controller is built with `CONFIG_BT_CTLR_CONN_ISO_LOW_LATENCY_POLICY=n` the LE Create BIG succeed, but only for the 441_1 setting. Even then the PTS device is not able to synchronize to the broadcast.

**To Reproduce**
With the AutoPTS and nRF5340 board.

**Expected behavior**
Zephyr controller accepts each of the mentioned config settings.

**Impact**
Affected PTS test cases:
BAP/BSRC/STR/BV-09-C
BAP/BSRC/STR/BV-10-C
BAP/BSRC/STR/BV-26-C
BAP/BSRC/STR/BV-27-C
BAP/BSRC/STR/BV-28-C
BAP/BSRC/STR/BV-29-C
BAP/BSRC/STR/BV-30-C
BAP/BSRC/STR/BV-31-C
BAP/BSRC/STR/BV-32-C
BAP/BSRC/STR/BV-33-C

**Logs and console output**

**Environment**
 - OS: Windows
 - Toolchain: Zephyr SDK 0.16.4
 - Commit SHA: 915f0fd74c6065b39ab84b2ecafce57000c822a7

**Additional context**
@cvinayak

### PR DESCRIPTION
**Pull request by cvinayak**
Fixes #67050

### CODE REVIEW

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/67392#issuecomment-1887352377 after 15:54:59.

**Comment by mkasenberg** [comment]
I saw the bot logs and the patch works great, controller has successfully accepted the config settings. The autopts cron will report fails though, because an MMI handler in autopts has a bug and does not send anything, the fix is not merged yet https://github.com/auto-pts/auto-pts/pull/1067/commits/f1453575017757489ef8250dc57a3ca0c95b5181#diff-fc44e218eeb03508ffb17b3eda2ca77928b173334fe43d2c55ff23df09b09e46R315-R323

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/BSRC/STR/BV-09-C            FAIL<br>BAP     BAP/BSRC/STR/BV-10-C            FAIL<br>BAP     BAP/BSRC/STR/BV-26-C            FAIL<br>BAP     BAP/BSRC/STR/BV-27-C            FAIL<br>BAP     BAP/BSRC/STR/BV-28-C            FAIL<br>BAP     BAP/BSRC/STR/BV-29-C            FAIL<br>BAP     BAP/BSRC/STR/BV-30-C            FAIL<br>BAP     BAP/BSRC/STR/BV-31-C            FAIL<br>BAP     BAP/BSRC/STR/BV-32-C            FAIL<br>BAP     BAP/BSRC/STR/BV-33-C            FAIL</details>

**Comment by cvinayak** [comment]
#AutoPTS run zephyr BAP/BSRC/STR/BV-09-C

**Comment by mkasenberg** [comment]
> #AutoPTS run zephyr BAP/BSRC/STR/BV-09-C

Your nick name was not in the privilege users list. I will add you and rerun the cron.

**Comment by mkasenberg** [comment]
I've tested this PR locally and got PASS
[BAP_BSRC_STR_BV_09_C_2024_01_24_14_13_02.zip](https://github.com/zephyrproject-rtos/zephyr/files/14039342/BAP_BSRC_STR_BV_09_C_2024_01_24_14_13_02.zip)

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/67392#issuecomment-1907982593 after 15:05:02.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>BAP     BAP/BSRC/STR/BV-09-C            FAIL</details>

**Comment by cvinayak** [comment]
> > #AutoPTS run zephyr BAP/BSRC/STR/BV-09-C
> 
> Your nick name was not in the privilege users list. I will add you and rerun the cron.

Thank you for adding to users list. 

I want to get the PR merged soon and want to try if the tester would report SUCCESS. But seems like the fix you mentioned is not merged yet? https://github.com/zephyrproject-rtos/zephyr/pull/67392#issuecomment-1887398033

**Comment by mkasenberg** [comment]
Yes, it finally got all the approves, so it may be merged any time soon.

But to make the bot to report success one more PR is needed https://github.com/zephyrproject-rtos/zephyr/pull/68061, it turns off BT_CTLR_ISOAL_SN_STRICT, because the tester app fails to select a right sequence number even for one ISO packet.

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr BAP/BSRC/STR/BV-09-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/67392#issuecomment-1911613698 after 08:42:58.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>BAP     BAP/BSRC/STR/BV-09-C            PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/67050 The 441_1 config rejected</details>

**Review by Thalley — APPROVED** [review]
Nice! 

One downside of the interval changes is that won't properly reflect real-world cases (at least not for the sink), so we may only be testing best-case here rather than default-case or even average case.

**Review by kruithofa — APPROVED** [review]

**Pull request merged**
