### PR TITLE
samples: watchdog: Remove STM32 IWDG specific sample

### PR DESCRIPTION
**Pull request by galak**
The STM32 IWDG specific sample hasn't been updated since we deprecated
the watchdog APIs it uses.  Additionally, this sample is never built (its
missing a prj.conf for stm32 hardware and related sample.yaml changes).

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by erwango** [comment]
Let's give @apodogrocki some time to see if we wants to fix this

**Comment by galak** [comment]
> Let's give @apodogrocki some time to see if we wants to fix this

sure thing, figured my removal might spark some interest in fixing it.

We also need to fix the STM32 watchdog driver to use the new API.

**Comment by galak** [comment]
> Let's give @apodogrocki some time to see if we wants to fix this

@apodogrocki any updates?

**Comment by apodogrocki** [comment]
I have started looking at the code. But due to being overloaded with work
at the moment, it could take me more time than I have expected. If there is
someone else who could do it in a shorter time, maybe it would be worth
assigning that task to him/her.

wt., 6.11.2018, 18:15: Kumar Gala <notifications@github.com> napisał(a):

**Review by erwango — COMMENTED** [review]
@galak , is there a rush for this or can we set a delay so that @apodogrocki has the required time to do this? (since I don't think we'll find another skilled volunteer)

**Comment by galak** [comment]
> @galak , is there a rush for this or can we set a delay so that @apodogrocki has the required time to do this? (since I don't think we'll find another skilled volunteer)

No rush, I'll close out this PR for now, its more about updating the driver.  We need to ideally aim for end of Nov/early Dec time frame.

**Comment by galak** [comment]
Closing this PR for now, will aim for removal or rework with the updating of the STM32 IWDG driver to the new watchdog API.

**Pull request closed without merging**
