### PR TITLE
drivers: a few device_get_binding cleanups

### PR DESCRIPTION
**Pull request by gmarull**
Remove usage of device_get_binding from a few drivers that can get the device reference at build time. Also simplified GPIO/I2C/SPI usage using the *_dt_spec utilities.

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]
+1 for CAN changes.

**Review by MaureenHelm — DISMISSED** [review]
Nice cleanup

**Review by nvlsianpu — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]
+1 for DAC changes.

**Review by carlescufi — DISMISSED** [review]

**Comment by dleach02** [comment]
@nashif is there a reason why the github actions bot adds just platform NXP on this PR?

**Review by nandojve — APPROVED** [review]
LGTM, tested rf2xx with SAM4S + atsamr21

**Review by mbolivar-nordic — APPROVED** [review]
led_strip

**Review by alexanderwachter — APPROVED** [review]
+1 for the MCP2515. Very nice!

**Pull request merged**
