### PR TITLE
bluetooth: controller: nrf: Provide info about used DPPI resources

### PR DESCRIPTION
**Pull request by anangl**
Use common definitions of HAL_USED_PPI_CHANNELS and HAL_USED_PPI_GROUPS
macros that will provide (through z_bt_ctlr_used_nrf_ppi_* variables)
information about either PPI or DPPI (depending on the SoC) resources
used by the Bluetooth controller.
Update also the hal_nordic module revision, to make the related nrfx
allocator aware of those reserved DPPI resources.

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
Makes sense to me.
Didn't look deep into the cleanup, though.

**Review by cvinayak — APPROVED** [review]

**Comment by carlescufi** [comment]
@anangl please update to SHA

**Comment by anangl** [comment]
@carlescufi I think it would be good to have https://github.com/zephyrproject-rtos/zephyr/pull/30351 merged first, as it will generate a conflict in `west.yml`.

**Comment by carlescufi** [comment]
> @carlescufi I think it would be good to have #30351 merged first, as it will generate a conflict in `west.yml`.

Yep, that's done now.

**Comment by anangl** [comment]
Rebased and updated with the proper SHA.

**Pull request merged**
