### PR TITLE
drivers: ieee802154: extend capabilities

### PR DESCRIPTION
**Pull request by jciupis**
This commit extends the capabilities of the nRF IEEE 802.15.4 radio
driver with IEEE802154_HW_TX_SEC capability.

Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

### CODE REVIEW

**Review by e-rk — APPROVED** [review]

**Review by edmont — APPROVED** [review]

**Review by rlubos — COMMENTED** [review]
LGTM, but please drop the manifest update commit, it's no longer needed.

**Comment by jciupis** [comment]
@rlubos done.

**Review by rlubos — APPROVED** [review]
Thanks

**Review by jukkar — APPROVED** [review]

**Comment by e-rk** [comment]
I forgot to remove the DNM lable. There is nothing that blocks this PR now.

**Pull request merged**
