### PR TITLE
boards: nxp: imx95_evk: add edma and sai nodes

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Add edma and sai nodes for the M7-based i.MX95 board.

### CODE REVIEW

**Review by mmahadevan108 — DISMISSED** [review]

**Review by dbaluta — DISMISSED** [review]

**Comment by dbaluta** [comment]
@LaurentiuM1234  this looks good to me. Good to merge once the conflicts are resolved.

**Comment by LaurentiuM1234** [comment]
Rebased and fixed conflict.

**Review by dbaluta — APPROVED** [review]

**Comment by mmahadevan108** [comment]
Please look at the CI failures.

**Comment by LaurentiuM1234** [comment]
Rebased. https://github.com/zephyrproject-rtos/zephyr/pull/78911 should fix the CI failures.

**Comment by LaurentiuM1234** [comment]
Waiting for fix on new failures: https://github.com/zephyrproject-rtos/zephyr/pull/78986.

**Comment by mmahadevan108** [comment]
Please rebase.

**Comment by LaurentiuM1234** [comment]
> Please rebase.

done

**Review by JiafeiPan — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
