### PR TITLE
Add initial multi-domain support to the logger core

### PR DESCRIPTION
**Pull request by nordic-krch**
Extended logger core to handle multiple domains in terms of getting names, filtering level of sources. Setting runtime filter level, etc. Added test for new features.

Introduce new concept to the logger: `link`. Link creates a pair with backend on the side. Application can have multiple links and each link can handle multiple domains (e.g. ipc link to another core which has trustzone and thus has 2 domains). Remote domains are controlled through link API. Link is using heap to allocate memory for domain names in the link and optionally runtime filtering settings for log sources in that link. Runtime filtering will allow control of remote log sources logs in the same way as the local one.

This PR does not add any link, potential link implementations may include following:
- link to second core (implemented over open amp)
- link to secure domain (trustzone)

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
+1 for doc change

**Review by nashif — CHANGES_REQUESTED** [review]
Create feature that needs some documentation. This probably needs some diagram describing how logging works across multiple domains and cores..

**Comment by nordic-krch** [comment]
@nashif I've extended logger documentation with multi-domain section: https://github.com/zephyrproject-rtos/zephyr/pull/19978/commits/9fa013cb602933e948f3dc2c35b7a63f5efcb2bd
@dbkinder can you review?

**Comment by nordic-krch** [comment]
I've created draft PR (#21416) which shows logging on multidomains on nrf53840 using openamp. It is based on this PR.

**Pull request closed without merging**
