### PR TITLE
gpio_mcp23sxx_fix: spi_msg and multiple inst

### PR DESCRIPTION
**Pull request by danielskatt**
**Changed SPI message from 2 seperate to 1**
The SPI communication did not work since the data frame was split into (addr, reg) and (data,data) but now the data frame is sent as a whole (addr, reg, data, data)

**Fixed problem using multiple instances**
It is now possible to add more than one instance of a gpio_mcp23sxx device

Signed-off-by: Daniel Skatt <daniel.skatt@gmail.com>

### CODE REVIEW

**Comment by emslGit** [comment]
@mnkp any chance to get a look at this?

**Comment by henrikbrixandersen** [comment]
> **Fixed problem using multiple instances**
> It is now possible to add more than one instance of a gpio_mcp23sxx device

Could you please elaborate on the nature of the problem fixed here? All I see is renaming of a macro argument?

**Comment by danielskatt** [comment]
> > **Fixed problem using multiple instances**
> > It is now possible to add more than one instance of a gpio_mcp23sxx device
> 
> Could you please elaborate on the nature of the problem fixed here? All I see is renaming of a macro argument?

@henrikbrixandersen Thanks for responding, the problem was due to the variable created below was named mcp23sxx_##inst##_drvdata and the argument was #define GPIO_MCP23SXX_DEVICE(n) so either change the variable name to mcp23sxx_##n##_drvdata or change the define argument to GPIO_MCP23SXX_DEVICE(inst). Since other drivers used inst as argument name I chose the same.

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by danielskatt** [comment]
Hi @mnkp , any chance you can review these changes? Thanks in advance

**Comment by henrikbrixandersen** [comment]
@mnkp @cfriedt ping

**Review by cfriedt — APPROVED** [review]
Looks OK - generally, it would be preferably to else minute whitespace changes (or at least put them in a separate commit). Not blocking though.

**Pull request merged**
