### PR TITLE
ITE MAINTAINERS: add tachometer path for compliance check

### PR DESCRIPTION
**Pull request by RuibinChang**
Add path: drivers/sensor/ite_tach_it8xxx2/*it8xxx2*
for compliance check.

Signed-off-by: Ruibin Chang <Ruibin.Chang@ite.com.tw>

### CODE REVIEW

**Comment by RuibinChang** [comment]
In the PR (https://github.com/zephyrproject-rtos/zephyr/pull/39993)  shows: 
Run python3 ./scripts/get_maintainer.py path CMakeLists.txt
./scripts/get_maintainer.py: error: /home/runner/work/zephyr/zephyr/MAINTAINERS.yml: glob pattern 'drivers/*/*it8xxx2*' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'

So I commit this PR, but it still occur an error:
Run python3 ./scripts/get_maintainer.py path CMakeLists.txt
./scripts/get_maintainer.py: error: /home/runner/work/zephyr/zephyr/MAINTAINERS.yml: glob pattern 'drivers/*/*/*it8xxx2*' in 'files' in area 'ITE Platforms' does not match any files
Error: Process completed with exit code 1.

Excuse me, what shall I do to solve errors?

**Comment by MaureenHelm** [comment]
> So I commit this PR, but it still occur an error: Run python3 ./scripts/get_maintainer.py path CMakeLists.txt ./scripts/get_maintainer.py: error: /home/runner/work/zephyr/zephyr/MAINTAINERS.yml: glob pattern 'drivers/_/_/_it8xxx2_' in 'files' in area 'ITE Platforms' does not match any files Error: Process completed with exit code 1.
> 
> Excuse me, what shall I do to solve errors?

Add this commit to the PR that adds the new driver (#39993)

**Comment by RuibinChang** [comment]
> Add this commit to the PR that adds the new driver (#39993)

Thanks for your reply. 

Actually, yesterday I committed maintainer to driver PR by in a commit or separating two commit in a relation chain, and both show:
MAINTAINERS.yml: glob pattern 'drivers/*/*it8xxx2*' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'

So I finally separated maintainer commit to another PR, but unfortunately it can't find files in path drivers/*/*/*it8xxx2*, then shows error.

As your suggestion, I add path 'drivers/*/*/*it8xxx2*' to the driver PR, but the checker still configures the old directory 'drivers/*/*it8xxx2*' instead of 'drivers/*/*/*it8xxx2*' : 
MAINTAINERS.yml: glob pattern 'drivers/*/*it8xxx2*' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'

**Comment by MaureenHelm** [comment]
> > Add this commit to the PR that adds the new driver (#39993)
> 
> Thanks for your reply.
> 
> Actually, yesterday I committed maintainer to driver PR by in a commit or separating two commit in a relation chain, and both show: MAINTAINERS.yml: glob pattern 'drivers / * / * it8xxx2 *' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'
> 
> So I finally separated maintainer commit to another PR, but unfortunately it can't find files in path drivers / * / * / * it8xxx2 *, then shows error.
> 
> As your suggestion, I add path 'drivers/ * / * / * it8xxx2 *' to the driver PR, but the checker still configures the old directory 'drivers / * / * it8xxx2 *' instead of 'drivers/ * / * / * it8xxx2 *' : MAINTAINERS.yml: glob pattern 'drivers / * / * it8xxx2 *' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'

You can have more than one commit in a PR. Add this commit to your `pwm_tachometer` branch, then #39993 will contain two commits.

**Comment by RuibinChang** [comment]
> > > Add this commit to the PR that adds the new driver (#39993)
> > 
> > 
> > Thanks for your reply.
> > Actually, yesterday I committed maintainer to driver PR by in a commit or separating two commit in a relation chain, and both show: MAINTAINERS.yml: glob pattern 'drivers / * / * it8xxx2 *' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'
> > So I finally separated maintainer commit to another PR, but unfortunately it can't find files in path drivers / * / * / * it8xxx2 *, then shows error.
> > As your suggestion, I add path 'drivers/ * / * / * it8xxx2 *' to the driver PR, but the checker still configures the old directory 'drivers / * / * it8xxx2 *' instead of 'drivers/ * / * / * it8xxx2 *' : MAINTAINERS.yml: glob pattern 'drivers / * / * it8xxx2 *' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'
> 
> You can have more than one commit in a PR. Add this commit to your `pwm_tachometer` branch, then #39993 will contain two commits.

Ack, the checker still configures the old directory 'drivers / * / * it8xxx2 *' instead of 'drivers/ * / * / * it8xxx2 *' :
MAINTAINERS.yml: glob pattern 'drivers / * / * it8xxx2 *' in 'files' in area 'ITE Platforms' matches a directory, but has no trailing '/'

And I don't think we should add trailing '/' in drivers / * / * it8xxx2 *, because there are files in drivers / * / * it8xxx2 * and need reviewers, ex. drivers/ watchdog/ Kconfig.it8xxx2, wdt_ite_it8xxx2.c ....

**Pull request closed without merging**
