### PR TITLE
Revert "boards: arm: rpi_pico: Enable MPU defaultly"

### LINKED ISSUE #54545: boards: rpi_pico: Bad MPU settings
A recent change to the rpi_pico board enabling the MPU causes some features to stop working. This is because the RP2040 relies on some functions running from the RAM.

### PR DESCRIPTION
**Pull request by soburi**
From #52705.
@purdeaandrei find the #53973 PR makes problem.
I also reproduced. To avoid confusion, reverting it.

@purdeaandrei,

Thank you for mention the problem,
and sorry for the your inconvenience.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54545

### CODE REVIEW

**Review by yonsch — APPROVED** [review]

**Comment by laurenmurphyx64** [comment]
Hi, @soburi Your PR needs a linked bug report to be merged into the Zephyr 3.3 release. Is this PR fixing https://github.com/zephyrproject-rtos/zephyr/issues/52705, or does it need a different bug report?

**Comment by yonsch** [comment]
@laurenmurphyx64 No, that bug was discovered while working on that issue, so a new issue should be opened

**Comment by yonsch** [comment]
@laurenmurphyx64 I've created #54545

**Review by stephanosio — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@yonsch should there be a MAINTAINERS entry for this board so that changes to this gets an assignee? Feel free to send a PR if that's the case.

**Comment by stephanosio** [comment]
> @yonsch should there be a MAINTAINERS entry for this board so that changes to this gets an assignee? Feel free to send a PR if that's the case.

Not this specific board, but "Raspberry Pi Pico Platform" should be there, indeed.

**Comment by yonsch** [comment]
As long as the maintainer does not need to physically own all of these boards I think it's fine

**Comment by fabiobaltieri** [comment]
> As long as the maintainer does not need to physically own all of these boards I think it's fine

No of course but there should be an entry covering the platform specific drivers, and I think it should include the rpi_pico board since it's effectively the reference board for it, see for example https://github.com/zephyrproject-rtos/zephyr/blob/0c5286dee6d4a21ebefd99563f5cdffda65f9c85/MAINTAINERS.yml#L2008-L2028

**Pull request merged**
