### PR TITLE
net: buf: Add support for reading/writing 24, 48 and 64 bit values

### PR DESCRIPTION
**Pull request by Vudentz**
This add support for other sizes that can be found on protocols, 24 bits specially is becoming more used by Bluetooth nowadays to express intervals in usec.

### CODE REVIEW

**Comment by Vudentz** [comment]
@jhedberg @tbursztyka any comments on this one?

**Review by tbursztyka — APPROVED** [review]
seems fine to me

**Comment by Vudentz** [comment]
It would be great to have someone double check if the __bswap_24 and __bswap_48 are actually proper since apparently there are no tests for those.

**Comment by Vudentz** [comment]
It would be great if you guys can have a look at the bit shifts macros for 24/48 since that I wasn't sure it is proper.

**Comment by wopu-ot** [comment]
This PR seems to supersede #17247

**Comment by Vudentz** [comment]
> This PR seems to supersede #17247

Right, I didn't realize that was pending, I mean that is awful long, I will try to add test cases for net_buf so it exercise the whole thing.

**Comment by Vudentz** [comment]
Added byteorder tests for net_buf.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by pfalcon — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
