### PR TITLE
intel_adsp: ace30: Bring up ACE 3.0 (PTL)

### PR DESCRIPTION
**Pull request by ceolin**
This commit adds definition of ACE 3.0 Panther Lake board.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>
Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by andyross** [comment]
Doing a cut/paste check of the added files vs. ace20_lnl files:

* adsp_boot.h, adsp_ipc_regs.h and adsp_memory_regions.h are identical files, modulo stuff like whitespace and copyright dates.

* dmic_regs_ace3x.h is an identical file, **and** was given a new file name needlessly!

* adsp_interrupt.h and adsp_memory.h differ only in register address #defines, which should be in devicetree anyway.

Really the only meaninful deltas I can see are in adsp_power and adsp_shim.

Maybe clean this up before merge?  Duplicated code makes interfaces difficult to evolve, and is one of the reasons that older DSP platforms like cAVS 1.8[1] are no longer in the tree and cut off from new development.

Not a -1 as it's not my platform, but this kind of gives me an ick.

[1] By far the most popular chromebook platform in the field!  And it will never see new Zephyr/SOF features.

**Comment by ceolin** [comment]
> Doing a cut/paste check of the added files vs. ace20_lnl files:
> 
> * adsp_boot.h, adsp_ipc_regs.h and adsp_memory_regions.h are identical files, modulo stuff like whitespace and copyright dates.

That was from a wrong rebase :/ They were correct in the first version :p

> * dmic_regs_ace3x.h is an identical file, **and** was given a new file name needlessly!
> * adsp_interrupt.h and adsp_memory.h differ only in register address #defines, which should be in devicetree anyway.
>

**Review by nashif — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by marc-hb** [comment]
> Duplicated code makes interfaces difficult to evolve

Also:
- https://github.com/thesofproject/sof/pull/9185

**Comment by marc-hb** [comment]
> Maybe clean this up before merge? Duplicated code makes interfaces difficult to evolve, and is one of the reasons that older DSP platforms like cAVS 1.8[1] are no longer in the tree and cut off from new development.

Small bug fix:
- #74694

**Pull request merged**
