### PR TITLE
drivers/sensor/lsm6dsl: Use DT defines to select I2C/SPI bus

### PR DESCRIPTION
**Pull request by avisconti**
Remove configuration parameter CONFIG_BUS_TYPE. Now we may
make use of DT_ST_LSM6DSL_BUS_I2C and DT_ST_LSM6DSL_BUS_SPI
definition to select the bus.

Signed-off-by: Armando Visconti <armando.visconti@st.com>

### CODE REVIEW

**Comment by avisconti** [comment]
compiled/tested on both ArgonKey (LSM6DSL_SPI) and disco_l475_iot1 (LSM6DSL_I2C) boards

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
So I think we need avoid using DT_ symbols in CMakeLists.txt

I wondering about introducing a:

`lsm6dsl_bus.c` which looks like:

```
#ifdef DT_ST_LSM6DSL_BUS_SPI
#include "lsm6dsl_spi.c"
#elif defined(DT_ST_LSM6DSL_BUS_I2C)
#include "lsm6dsl_i2c.c"
#else 
#error "..."
#endif
```

**Comment by galak** [comment]
We also probably need to add:

`#define DT_ST_LSM6DSL_BUS_I2C 1` in `tests/drivers/build_all/dts_fixup.h`

**Review by galak — CHANGES_REQUESTED** [review]
Made a few comments on how to get sanity builds to pass.

**Comment by avisconti** [comment]
> So I think we need avoid using DT_ symbols in CMakeLists.txt

This should be fine, as I was able to compile it for ArgonKey and discovery iot boards.

> We also probably need to add:
> #define DT_ST_LSM6DSL_BUS_I2C 1 in tests/drivers/build_all/dts_fixup.h

It might be. I can try.

**Comment by galak** [comment]
> This should be fine, as I was able to compile it for ArgonKey and discovery iot boards.
> 
> >

The reason I say that is because of how build the tests that are failing.  Use DT_ in CMakefile.txt like this is probably best to be avoided.

**Comment by erwango** [comment]
@galak 

> So I think we need avoid using DT_ symbols in CMakeLists.txt

I understand why (lack of dependencies control and so on), but I feel this render the DT_X_BUS not easy to use. I know this seems like a proposal going in the opposite direction of all the efforts made recently, but:
What about generating a CONFIG_, as it is proposed for compats in https://github.com/zephyrproject-rtos/zephyr/issues/9406#issuecomment-436982059?

**Comment by avisconti** [comment]
@galak @erwango 

> So I think we need avoid using DT_ symbols in CMakeLists.txt

To be honest I'm not sure I understand why we cannot do it, but I feel
you are both right


> I wondering about introducing a:
> lsm6dsl_bus.c which looks like:
>
>#ifdef DT_ST_LSM6DSL_BUS_SPI
>#include "lsm6dsl_spi.c"
>#elif defined(DT_ST_LSM6DSL_BUS_I2C)
>#include "lsm6dsl_i2c.c"
>#else 
>#error "..."
>#endif

Why not doing the following instead:

CMakeLists.txt::
   ...
   zephyr_library_sources(lsm6dsl_spi.c)
   zephyr_library_sources(lsm6dsl_i2c.c)
   ...

lsm6dsl_spi.c::
#ifdef DT_ST_LSM6DSL_BUS_SPI
...
#endif  

lsm6dsl_i2c.c::
#ifdef DT_ST_LSM6DSL_BUS_I2C
...
#endif  

Similar to @galak proposal, but without introducing a new file.

**Comment by avisconti** [comment]
@galak 
Any comment on this PR?

**Review by galak — APPROVED** [review]

**Pull request merged**
