### PR TITLE
tests: benchmarks: footprints: this is not a test

### PR DESCRIPTION
**Pull request by nashif**
Do not configure this as a test, this will change footprint drastically
and will skew results and tracking.

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Review by ioannisg — CHANGES_REQUESTED** [review]
I understand the rationale, but then this should not be under ./zephyr/tests/

I this we must enforce everything under this directory to enable CONFIG_TEST=y, we need uniformity and consistency. That's my opinion at least :)

Alternatives:
- make this a sample, place this under zephyr/samples/benchmarks/. This makes sense, as these benchmarking "tests" do not really test any functionality, do not have asserts, etc.
- place this under ./zephyr/benchmarking; ultimately I expect more samples to be developed as pure benchmarking.

**Comment by nashif** [comment]
> * make this a sample, place this under zephyr/samples/benchmarks/. This makes sense, as these benchmarking "tests" do not really test any functionality, do not have asserts, etc.
> 
> * place this under ./zephyr/benchmarking; ultimately I expect more samples to be developed as pure benchmarking.

none of the alternative are viable, benchmarking has always been under tests and I do not agree that each application under tests/ must have CONFIG_TEST, especially this one. The idea here not to have things enabled for footprint, so adding CONFIG_TEST defeats the purpose. 

Also, I am not following why CONFIG_TEST is needed here.

**Comment by ioannisg** [comment]
Several defaults are enabled when CONFIG_TEST is enabled. Some of those defaults are essential for being able to run the tests automated, in twister on some platforms. And I want to be able to run _everything_ under ./zephyr/tests in my twister plans.

In general,  if I am not able to set CONFIG_TEST=y to any test case under ./zephyr/tests/, then what is the reason for having this Kconfig, anyways?

Why is it not viable for benchmark applications to be moved out, under samples? After all they are samples - they are not verifying functional behavior? And AFAIK, twister does run samples, as well.

**Comment by nashif** [comment]
> In general, if I am not able to set CONFIG_TEST=y to any test case under ./zephyr/tests/, then what is the reason for having this Kconfig, anyways?

because not enabling CONFIG_TEST and whatever comes with it, is PART of the test. When I say this is not a test, I mean this does not behave like other tests, i.e. we do not use ztest or we do not expect any specific output, the configuration options are the test, and not having CONFIG_TEST is what we are testing actually.

Benchmarks are not samples, there is nothing more to say here.

>  they are not verifying functional behavior?

They do actually., this one verifies footprint, other benchmarks verify performance, latency and other things and they serve as integration tests, I did not remove this option from all, but the footprint test is a special case and it should not pull whatever CONFIG_TEST selects and that to be able to control a set of features that we are monitoring for footprint.

**Comment by nashif** [comment]
The reason this breaks tracking and footprint testing:

image

**Comment by ioannisg** [comment]
> because not enabling CONFIG_TEST and whatever comes with it, is PART of the test. When I say this is not a test, I mean this does not behave like other tests, i.e. we do not use ztest or we do not expect any specific output, the configuration options are the test, and not having CONFIG_TEST is what we are testing actually.

Understood, but you should agree the lack of uniformity here is at least problematic :)

I checked now and the test is listed as build-only, so I don't see a problem with missing the CONFIG_TEST setting, at least for the platforms I usually run CI on. (I missed that detail earlier, but your comment about no "specific output" guided me to it.).

**Review by ioannisg — APPROVED** [review]
I guess enabling LOG/LOG_MINIMAL here is done to measure the component footprint and not because the test is supposed to execute on CI and the output to be verified, right @nashif ?

Approving this, assuming the test will stay as being build-only.

**Comment by nashif** [comment]
> Understood, but you should agree the lack of uniformity here is at least problematic :)

I do not think it is problematic. if we start categorizing whatever we have under tests right now to achieve "uniformity" we will end up with many other cases that would end up as top level folders.



> Approving this, assuming the test will stay as being build-only.

even if a test runs, it can select to disable things like logging or other features not needed for the test. If some platforms require CONFIG_TEST to pass, this is a problem that needs to be resolved somewhere else.

**Comment by ioannisg** [comment]
> even if a test runs, it can select to disable things like logging or other features not needed for the test. 

@nashif my thought is that CONFIG_TEST=y should be expected to be set in all Zephyr tests, in the same way as CONFIG_ARM=y should be expected to be set, if you build for any Cortex platform :) So, platforms may set up all the required stuff to be able to run the tests, based on a single Kconfig dependency: CONFIG_TEST. (...and, alternatively, may not set those up when running e.g. samples, or applications).

It is true that CONFIG_TEST enables some defaults that have an impact on the size of the executable, hence the minimal tests, must have the option disabled. We may need to rethink what CONFIG_TEST should be enabling, then. Or keep those tests **outside** the mainline tests, so they do not get to run in "regular" CI.

> If some platforms require CONFIG_TEST to pass, this is a problem that needs to be resolved somewhere else.

I don't agree on this. I think CONFIG_TEST=y shall be a sufficient condition that the "test" is able to run in CI on a platform (otherwise it needs to be filtered-out in .yaml). So I can invoke twister -b "my_board" -T zephyr/tests/ and be sure that everything below this directory can build and run. Essentially, what I want CONFIG_TEST to imply is more like `config TESTABLE_IN CI`. I do not care what default features (e.g. kernel features) CONFIG_TEST enables; that we can discuss but it is out of scope.

**Pull request merged**
