### PR TITLE
Linker library property improvements

### PR DESCRIPTION
**Pull request by tejlmand**
Those commits clean up linker library property handling by moving minimal C++ handling to the CMake file where it now belongs and avoids sourcing linker library properties for native builds.

### CODE REVIEW

**Review by stephanosio — COMMENTED** [review]
Not the most intuitive thing to set the libc++ (or libc for that matter) flags first only to unset it later ... but I guess that is what we have now.

**Review by stephanosio — APPROVED** [review]

**Comment by dkalowsk** [comment]
@tejlmand and @stephanosio is this something we're going to want in 4.0?

**Comment by tejlmand** [comment]
> Not the most intuitive thing to set the libc++ (or libc for that matter) flags first only to unset it later

Agree, the optimal is actually be to adjust it to the minimal c++ static library when this CMake code is executed.
But that is a different task because that requires that we remove the minimal c++ lib from the whole-archive part.

Thus preferring to do this cleanup step-wise.

**Comment by tejlmand** [comment]
> @tejlmand and @stephanosio is this something we're going to want in 4.0?

it's a further cleanup / improvement but not fixing any bugs, so strictly not needed for 4.0

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
