### PR TITLE
tests: benchmarks: Disable userspace for benchmarks

### PR DESCRIPTION
**Pull request by AdithyaBaglody**
benchmarks: Disable userspace for benchmarks

Disable userspace for benchmarks because it changes the KPI
numbers. It will be re-enabled once the required code is
in place.

Fixes: GH-7907

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

### CODE REVIEW

**Review by nashif — DISMISSED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
wrong fix, this is happening due to the MPU being enabled. We need to fix this proper, for example disable MPU for this test.

**Comment by andrewboie** [comment]
> We need to fix this proper, for example disable MPU for this test.

That doesn't sound like a root-cause fix to me, can you elaborate?

**Comment by nashif** [comment]
> That doesn't sound like a root-cause fix to me, can you elaborate?

If we find the root-cause, lets fix it proper and that should be the long term goal. @AdithyaBaglody  has the task to adapt all benchmarks we have for MPU/MPUless configurations so we can measure overhead of enabling MPU and userspace. So we need to be able to run those tests/benchmarks with both configurations. Initially, we need to have those benchmarks run as before and without MPU, so disabling this will give us this, in 1.13 we can add the MPU/Userspace benchmarks.

Note that enabling MPU right and userspace right now is going to distort any KPIs we have tracking from the time before we had userspace enabled, this needs to be fixed.

**Comment by AdithyaBaglody** [comment]
@nashif I will disable the USERSPACE for all benchmarks as of now. Once I update the benchmarks/timing_info for MPU/MMU I will re-enable for specific benchmarks only.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
thanks, so it was the HW stack protection causing the regression, we can keep MPU enabled in this case :)

**Pull request merged**
