### PR TITLE
Bump mbedTLS to 2.16.6

### PR DESCRIPTION
**Pull request by ceolin**

### CODE REVIEW

**Comment by carlescufi** [comment]
@ceolin https://github.com/zephyrproject-rtos/mbedtls/pull/11 is merged, please update the manifest with a SHA.

**Comment by ceolin** [comment]
> @ceolin [zephyrproject-rtos/mbedtls#11](https://github.com/zephyrproject-rtos/mbedtls/pull/11) is merged, please update the manifest with a SHA.

done

**Review by rlubos — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
Checked SHA

**Pull request merged**
