### PR TITLE
doc: fix typo

### PR DESCRIPTION
**Pull request by androbi-com**
typo

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]

**Review by gmarull — CHANGES_REQUESTED** [review]
Please check https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines

**Review by tejlmand — APPROVED** [review]

**Comment by sisius** [comment]
I am wondering if I did the correct thing. I was reading the docs and noted a typo (just one letter missing). A button "Open on GitHub" kinda suggested me this was the place to fix the typo. But now I see this kicked off all the machinery for code changes, maybe a lot of processes/work for just inserting one letter in the docs? Is this the correct way for fixing things in the docs?

**Comment by SebastianBoe** [comment]
It's correct. We just don't have a CI system smart enough to not test code when doc changes are done.

**Comment by androbi-com** [comment]
I am sorry, I don't know how to ammend the author of a previous commit. I have added the "signed off", but the author still comes as the nickname. Please reject this pull request if there is no simpler solution.

**Comment by SebastianBoe** [comment]
Closing, hopefully someone else will fix the type when the docs are reworked at a later time.

**Pull request closed without merging**
