### PR TITLE
samples: driver: video: enable capture case to run

### PR DESCRIPTION
**Pull request by hakehuang**
enable capture case with fixture_camera to run

### CODE REVIEW

**Comment by josuah** [comment]
It is possible that `mimxrt1064_evk` board config is missing due to a renaming that happened at the same time as a contribution.
https://github.com/zephyrproject-rtos/zephyr/pull/78414

In hope this does not affect your setup.
I will need to learn about test fixtures, that sounds interesting.

**Review by danieldegrasse — APPROVED** [review]

**Comment by hakehuang** [comment]
> It is possible that `mimxrt1064_evk` board config is missing due to a renaming that happened at the same time as a contribution.
> #78414

Rt1060 and rt1064 are basically the same for video

**Comment by josuah** [comment]
It looks like part of this project to improve hardware-in-the-loop tests:
- https://github.com/zephyrproject-rtos/zephyr/issues/68400

Sorry I lack experience for reviewing the test fixtures, and could not find `fixture_camera` mentioned anywhere on the python scripts. Did I miss something?

**Comment by hakehuang** [comment]
> Sorry I lack experience for reviewing the test fixtures, and could not find `fixture_camera` mentioned anywhere on the python scripts. Did I miss something?

the fixture_camera is a postion taken here, the process is that, if you add --fixture fixture_camera in your command line or 
```
fixtures:
 - fxiture_camera
```
in your board map file, then you can test this case, otherwise, this is a build only case. As for now, this is the first case with fixture_camera. and the fixture_camera is a virtual for below devices list in readme.

- `Camera iMXRT`_

- :ref:`mimxrt1064_evk`
- `MT9M114 camera module`_

- :ref:`mimxrt1170_evk`
- `OV5640 camera module`_

**Comment by josuah** [comment]
Thank you this was insightful! This makes sense and permits me to understand fixtures.
Having a command line flag `--fixture fixture_camera` means there is no dependency for this to be usable, and already useful for custom boards.

**Review by josuah — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
