### PR TITLE
Fixes for newlib stdio support with CONFIG_POSIX_API=y.

### PR DESCRIPTION
**Pull request by invoxiaamo**

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by pfalcon** [comment]
@invoxiaamo:

This looks harmless, but I'd like to ask for clarification re: "fix all files to be opened in line buffer mode" - does this lead to any additional dynamic malloc allocation on stdio side, or something, i.e. does this change behavior which can lead to earlier libc heap exhaustion comparing to previous behavior?

**Comment by invoxiaamo** [comment]
Hello Paul.

So I did some tracing of the following code with GDB to trace calls to 
fopen, fwrite, write and _malloc_r:

```
unsigned char buffer[4096];

void test(void)
{
     FILE *F = fopen("/local/test.bin", "w");
     if (!F) {
         printf("fopen failed\n");
         return;
     }

     memset(buffer, 0, sizeof(buffer));
     for (int i=0; i < sizeof(buffer); i+= 15) {
         buffer[i] = '\n';
     }

     fwrite(buffer, 4096, 1, F);
     fwrite(buffer, 4, 1, F);
     fclose(F);
}
```

The filesystem is a littleFS one mounted on /local.. but it doesn't 
matter here.

With the patch enabling block buffering, we have the following trace
```
      fopen(/local/test.bin)
      _malloc_r( r, 412 )
      fwrite(...,4096,1,...)
      _malloc_r( r, 1024 )
      write(3, x, 4096)
      fwrite(...,4,1,...)
      write(3, x, 4)
```

Without the patch:

```
      fopen(/local/test.bin)
      _malloc_r( r, 412 )
      fwrite(...,4096,1,...)
      write(3, x, 1)
      write(3, x, 15)
   [.... write(3, x, 15)  x ~270 ]
      write(3, x, 15)
      fwrite(...,4,1,...)
      write(3, x, 1)
      write(3, x, 3)
```

So:
- The malloc usage is the same. A 1024 buffer size (BUFSIZ) is used to 
store temporary data in both cases.
- you can see we can avoid lots of processing and write ops due to 
inefficient line processing operations when applied to non-string content.

Regards,
Arnaud



Le 01/10/2020 à 15:56, Paul Sokolovsky a écrit :

**Comment by pfalcon** [comment]
@invoxiaamo:

> - The malloc usage is the same. A 1024 buffer size (BUFSIZ) is used to
store temporary data in both cases.

Thanks for checking this, and posting detailed info. This should leave enough trace for someone who might be looking into that later.

> - you can see we can avoid lots of processing and write ops due to
inefficient line processing operations when applied to non-string content.

So, that's what I kinda wondered, because the commit description is "libc: newlib: fix all files to be opened in line buffer mode", and I read it literally, as written: "Make a fix, so that all files are opened in line buffer mode". Whereas you seem to apply a fix to *avoid* that. Can you please update the commit message to be less ambiguous, a.g. "libc: newlib: Avoid all files to be opened in line buffer mode" ? And if you can mention full/block buffering in the body of the message, it would be only good.

**Comment by invoxiaamo** [comment]
Commit message updated.

**Review by pfalcon — APPROVED** [review]
Thanks!

**Pull request merged**
