### PR TITLE
Fixes 10-bit ADC resolution on MEC1501

### LINKED ISSUE #23202: Macro value for 10 bit ADC is wrong in MEC driver.
Current microchip ADC driver is using reserved fields to program 10bit resolution setting.
In :\modules\hal\microchip\mec\mec1501\component\adc.h: 
`#define MCHP_ADC_SAR_CTRL_RES_10_BITS	(0x01ul << 1)`

This value should be: 
`#define MCHP_ADC_SAR_CTRL_RES_10_BITS	(0x02ul << 1)`

Also, when using 10 bit resolution, driver should shift data in reading register.
adc_mchp_xec.c driver should use `MCHP_ADC_SAR_CTRL_SHIFTD_EN ` when using 10bit resolution.

### PR DESCRIPTION
**Pull request by dcpleung**
This points to an updated HAL which fixes the incorrect bits for 10-bit resolution. Also enable the hardware feature to right justify the ADC output data for 10-bit resolution.

Fixes #23202

Needs https://github.com/zephyrproject-rtos/hal_microchip/pull/8

### CODE REVIEW

**Review by scottwcpg — APPROVED** [review]

**Review by franciscomunoz — APPROVED** [review]

**Review by albertofloyd — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by jhedberg** [comment]
@dcpleung should the DNM be removed? It seems the HAL dependency is merged?

**Comment by dcpleung** [comment]
> @dcpleung should the DNM be removed? It seems the HAL dependency is merged?

I have updated `west.yml` to point to the latest SHA, and removed the DNM tag. This should be good to go pending CI.

**Comment by albertofloyd** [comment]
@jhedberg would this be make it to v2.2.0?

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
> @jhedberg would this be make it to v2.2.0?

Sure.

**Pull request merged**
