### PR TITLE
feat: add support for TDK NTCG103JF103FT1 thermistor

### PR DESCRIPTION
**Pull request by maxmclau**
Adds compensation table for NTCG103JF103FT1 thermistor. The compensation table for this thermistor is shared with a few other thermistors like the NTCG163JF103FT1 so maybe it'd make sense to rename it NTCG1x3JF103FT1? Wasn't sure how Zephyr prefers to handle those sorts of naming conventions.

### CODE REVIEW

**Comment by maxmclau** [comment]
any chance this could be reviewed soon? I'm also up to wait until https://github.com/zephyrproject-rtos/zephyr/pull/60682 is merged if that's easier

**Comment by MaureenHelm** [comment]
> any chance this could be reviewed soon? I'm also up to wait until #60682 is merged if that's easier

#60682 has been merged. Please rebase

**Comment by maxmclau** [comment]
rebased

> > any chance this could be reviewed soon? I'm also up to wait until #60682 is merged if that's easier
> 
> #60682 has been merged. Please rebase

Rebased - should be good for review

**Review by MaureenHelm — APPROVED** [review]

**Comment by MaureenHelm** [comment]
@teburd @yperess Can you take a look at this? It's a pretty simple change that fell through the cracks

**Review by yperess — APPROVED** [review]

**Pull request merged**
