### PR TITLE
Allow extending hexdump log message

### PR DESCRIPTION
**Pull request by nordic-krch**
Add api to extend hexdump log message. Extending may include allocating additional chunks. It enables appending data to log message on the fly which will be used in multi-domain context.

Extended log_output module to allow conversion from standard or hexdump log message to extended log message. Extended log message contains formatted string message (source name and formatted string with arguments). Extended log message gets all metadata from original log message (e.g. source id, timestamp, level).

Extended message is self contained in a sense that it can be transferred between domains and formatted on another side (domain name is needed). Extended messages will be used in multi-domain logger.

### CODE REVIEW

**Review by tyrantlizard77 — COMMENTED** [review]
code looks clean but what's the end user API look like? How does this tie into the hexdump macros in the main log.h?

**Comment by nordic-krch** [comment]
@andrewboie it's not yet used by the logger nor intended to be used by the user. I started to work on the logger in multi-domain context and that's one of the pieces that will be used. I want to introduce it partially instead of one big PR.

**Comment by nordic-krch** [comment]
ping to reviewers. I would like to get that in to avoid multidomain logger PR being too big.

**Comment by nordic-krch** [comment]
I've created draft PR (#21416) which shows logging on multidomains on nrf53840 using openamp. It is based on this PR.

**Pull request closed without merging**
