### PR TITLE
soc: atmel_sam: set SYS_CLOCK_HW_CYCLES_PER_SEC from DT

### PR DESCRIPTION
**Pull request by mnkp**
Set the defalut value of SYS_CLOCK_HW_CYCLES_PER_SEC Kconfig option
from the Device Tree. The `clock-frequency` property of the DT `cpu@0`
node is a single source of truth defining the CPU frequency. This is
the value used e.g. by all Atmel drivers.

For Atmel SAM family CPU clock is currently the only supported system
clock source. Ensure that kernel understanding of the hardware clock
frequency is the correct one.

### CODE REVIEW

**Review by nandojve — APPROVED** [review]
Hi @mnkp ,

This is a good clean up. If you think it is appropriated, you could move property from `soc/arm/atmel_sam/<series>/Kconfig.defconfig.series` to `zephyr/soc/arm/atmel_sam/Kconfig.defconfig`.  I think it became a little bit redundant and currently, we have `WATCHDOG` there.

**Comment by mnkp** [comment]
> you could move property from `soc/arm/atmel_sam/<series>/Kconfig.defconfig.series` to `zephyr/soc/arm/atmel_sam/Kconfig.defconfig`.

Good point. Thanks for the suggestion. I squashed all the changes into one commit.

**Review by stephanosio — APPROVED** [review]
The changes look reasonable.

Just noting that this is true if and only if:
1. Cortex-M SysTick is the active system timer configured for the board (this is currently the case and there is little incentive to use something else -- e.g. TC or TCC).
2. Cortex-M SysTick is configured to use processor clock ([this is currently true](https://github.com/zephyrproject-rtos/zephyr/blob/aa8e34302a184b9cd13b0aa10d1a4fd2a1b104b1/drivers/timer/cortex_m_systick.c#L163), but the SysTick hardware itself also supports using an external clock source).

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
There are some CI build failures on nordic platforms. @mnkp pls investigate

**Comment by mnkp** [comment]
> There are some CI build failures on nordic platforms. @mnkp pls investigate

My bad, I overlooked `depends on` in Kconfig. Fixed.

**Review by nashif — APPROVED** [review]

**Pull request merged**
