### PR TITLE
doc: drivers: deprecate driver init levels

### PR DESCRIPTION
**Pull request by nguyenmthien**
Remove deprecated driver initialization levels in the docs.

### CODE REVIEW

**Review by nashif — CHANGES_REQUESTED** [review]
Those levels are not deprecated.

**Comment by nguyenmthien** [comment]
> Those levels are not deprecated.

Those are deprecated in [this commit](https://github.com/zephyrproject-rtos/zephyr/commit/beec8b05a8f11de474c88cdec15cdf89dbd3a86b)

**Comment by nashif** [comment]
> Those are deprecated in [this commit](https://github.com/zephyrproject-rtos/zephyr/commit/beec8b05a8f11de474c88cdec15cdf89dbd3a86b)

initialization of devices in this level is deprecated, not the init level itself.

**Comment by nguyenmthien** [comment]
> > Those are deprecated in [this commit](https://github.com/zephyrproject-rtos/zephyr/commit/beec8b05a8f11de474c88cdec15cdf89dbd3a86b)
> 
> initialization of devices in this level is deprecated, not the init level itself.

This file is the documentation for the device driver model, and not the init system as a whole right?

**Comment by nashif** [comment]
> This file is the documentation for the device driver model, and not the init system as a whole right?

afaik this is the only place init levels are documented in the docs.

**Comment by nguyenmthien** [comment]
> > This file is the documentation for the device driver model, and not the init system as a whole right?
> 
> afaik this is the only place init levels are documented in the docs.

The wording of the removed sentences and the page title make it clear that this content is meant for device drivers only. IMO, the lack of documentation for `SYS_INIT()` does not constitute the necessity of including deprecated APIs in driver inits.

**Review by gmarull — APPROVED** [review]
considering this is a page dedicated to drivers, changes make sense. SYS_INIT Doxygen documents init levels in detail https://docs.zephyrproject.org/latest/doxygen/html/group__sys__init.html

**Review by cfriedt — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
