### PR TITLE
samples: can: add b2b_xfer sample

### PR DESCRIPTION
**Pull request by CkovMk**
This sample requires 2 boards. Sender node sends CAN frame when button is pressed, then listens reply CAN frame from replier board.

Readme is WIP. Not really familiar with .rst syntax...

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
This looks like just an interactive edition of `samples/drivers/can/counter/` in non-loopback mode.

I don't see a need for introducing another sample doing simple board-to-board CAN communication?

**Comment by CkovMk** [comment]
Yeah I didn't notice that example before. If not needed I'll close it.

**Comment by henrikbrixandersen** [comment]
> Yeah I didn't notice that sample before. The point of this sample is that it's interoperable with the b2b_interrupt_xfer example in NXP MCUXspresso SDK (So you can have 1 board running zephyr and the other running SDK). If not needed I'll close it.

I don't see a need for such a sample in upstream Zephyr, sorry. Perhaps something for an NXP downstream fork? Or stand-alone demo app?

**Comment by CkovMk** [comment]
No problem, close it.

**Pull request closed without merging**
