### PR TITLE
devicetree: drop support for dts_fixup.h files

### PR DESCRIPTION
**Pull request by gmarull**
Devicetree fixup files existed previous to the current stable Devicetree
API. While they served their purpose, they are no longer necessary nor
used in-tree. This patch drops support for this legacy feature.

### CODE REVIEW

**Review by galak — DISMISSED** [review]

**Review by jeremybettis — DISMISSED** [review]

**Comment by galak** [comment]
Marking DNM to make sure we get @mbolivar-nordic approval.

**Review by tejlmand — DISMISSED** [review]
thanks for cleaning this up.

**Review by mbolivar-nordic — COMMENTED** [review]
You're on a rampage to make my ZDS 2022 talk where I explained these details obsolete, huh?

OK, fine, I guess it gives me an excuse to give it again next time, less work to prep slides...

No objections, but I do agree we should change devicetree_unfixed.h to something else now. It doesn't make sense.

How about `devicetree_generated.h`?

**Comment by gmarull** [comment]
> You're on a rampage to make my ZDS 2022 talk where I explained these details obsolete, huh?
> 

heh, same problem with my presentation. New DT Kconfig helpers, usage of select, etc. I actually created a v2 slides, so people won't copy a _legacy_ pattern... :smile:

> OK, fine, I guess it gives me an excuse to give it again next time, less work to prep slides...
> 
> No objections, but I do agree we should change devicetree_unfixed.h to something else now. It doesn't make sense.
> 
> How about `devicetree_generated.h`?

+1, will push the name change

**Review by mbolivar-nordic — DISMISSED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Pull request merged**
