### PR TITLE
samples: nrf52: Ignore messages with prohibited parameters

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This fixes an issue of sending Status message as a response
to Set command with prohibited parameters.
Status message shall not be sent in this case according to
Mesh Model Spec 1.3.3.

Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

### CODE REVIEW

**Comment by MariuszSkamra** [comment]
@vikrant8051 FYI

**Comment by MariuszSkamra** [comment]
@jhedberg Do not merge this yet. I have to fix the rest of the models

**Comment by vikrant8051** [comment]
@MariuszSkamra Kindly don't do anything as of now. It will create lot of confusion.
If you required please create separate app.

@jhedberg Please look into this.

**Comment by jhedberg** [comment]
@vikrant8051 what confusion do you mean? This PR seems like a fairly straight-forward fix to the app, and this app needs to be fixed no matter what.

**Comment by vikrant8051** [comment]
Hi Johan,

Kindly wait till I merged from my side.

Thank You !!

**Comment by MariuszSkamra** [comment]
@vikrant8051 
You are kidding me. I have a lot of work to do, sorry I haven't been responsive. But I found free slot to test your patches and provide a fix. You want me to test your solutions only?? Who am I to you? Someone is paying for my time and you want to throw my work away?

**Comment by vikrant8051** [comment]
@MariuszSkamra I respect your contribution. Without your help it was impossible to go ahead. It was my humble request only. Kindly don't take it in wrong way.

**Comment by vikrant8051** [comment]
@MariuszSkamra It was my reflexive reaction. And I think I was wrong & sorry for that.

**Pull request closed without merging**
