### PR TITLE
Fix posix newlib / disable posix lib on native_posix arch

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by galak** [comment]
@vanti this should address the issue you reported in:

https://github.com/zephyrproject-rtos/sdk-ng/issues/45

**Comment by pfalcon** [comment]
recheck

**Review by pfalcon — APPROVED** [review]
Let me approve this as an incremental step towards resolving POSIX subsys issues (but likely not the final step, for example I'm sure we'l need to tweak includes back and forth).

**Comment by pfalcon** [comment]
Closing/reopening to get rid of CI timing test glitch.

**Comment by vanti** [comment]
> @vanti this should address the issue you reported in:
> 
> [zephyrproject-rtos/sdk-ng#45](https://github.com/zephyrproject-rtos/sdk-ng/issues/45)

@galak I added a test here: https://github.com/zephyrproject-rtos/zephyr/pull/13599

**Pull request merged**
