### PR TITLE
[backport v2.2] Bluetooth: controller: Fix ticker catch up on ISR latency

### LINKED ISSUE #23070: Bluetooth: controller: Fix ticker implementation to avoid catch up
**Describe the bug**
Relates to #22926

Temporarily ticker compatibility mode has been enabled for nRF5 platforms.

Two issues observed:
1. Either flash driver's ticker instance or master role ticker instance do not get scheduled. Both have an interval of 7.5 ms.
2. Flash erase takes 80 ms during which CPU is halted, master intervals try catch up consuming CPU time that cause master events not being scheduled at hard real time deadlines.

Detailed analysis to be posted here, post v2.2 release completes.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

### PR DESCRIPTION
**Pull request by cvinayak**
Fix ticker to avoid catch up of periodic timeouts in case of
large ISR latencies like in case of flash erase scenarios.

Relates to #23815.
Fixes #23070.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by thoh-ot — APPROVED** [review]

**Comment by carlescufi** [comment]
@cvinayak Please rebase on latest v2.2-branch

**Comment by cvinayak** [comment]
@carlescufi, sorry for the delay. Done.

**Comment by carlescufi** [comment]
@jhedberg should we merge?

**Comment by jhedberg** [comment]
> @jhedberg should we merge?

@carlescufi yep, thanks for the reminder

**Pull request merged**
