### PR TITLE
drivers: wifi: winc1500: Update reset procedure in wifi_winc1500_nm_bsp.c

### PR DESCRIPTION
**Pull request by gp-src**
drivers: wifi: winc1500: Update reset procedure in wifi_winc1500_nm_bsp.c

ATWINC1500 reset pin is active low.
Correct reset procedure to use logical sense, not physical sense,
as per gpio_pin_set_dt().

Signed-off-by: George Priestner <georgepriestner@gmail.com>

### CODE REVIEW

**Comment by GeorgePriestner-Eaton** [comment]
Should also resolve #52792

**Review by Kludentwo — APPROVED** [review]
I do not have a device to test it but I trust you have ;-)

**Review by rlubos — COMMENTED** [review]
Please follow [commit guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines) regarding the commit message.
Specifically:
* Use `drivers: wifi: winc1500:` prefix for the title
* Stick to 72 char/line limit
* Add signoff entry

**Comment by jukkar** [comment]
@gp-src please note that changing the github PR note/description does nothing to the commit itself, you need to edit your local commit in your tree and force push the branch

**Comment by gp-src** [comment]
@jukkar Hopefully the commit name/note are OK now.

Not sure why those 3 unit tests have failed though.

**Comment by rlubos** [comment]
> Not sure why those 3 unit tests have failed though.

It's a regression on main that is already fixed. A rebase should help.

>  463ec46377d7fc04938918255a217e6d3480316c: author email (gp-src <75914191+gp-src@users.noreply.github.com>) needs to match one of the signed-off-by entries.
463ec46377d7fc04938918255a217e6d3480316c: author email (gp-src <75914191+gp-src@users.noreply.github.com>) does not follow the syntax: First Last <email>.

This looks like a git misconfiguration on your side. Make sure that your `user.name` and `user.email` git configs match the signoff entry, and reset the commit author (`git commit --amend --reset-author`).

**Comment by gp-src** [comment]
Hm seems rebasing wasn't the best idea... didn't realise bot would add all reviewers to this PR. Should I just close and re-create?

**Comment by gp-src** [comment]
I'm not sure why GitHub is saying there are conflicts now. I have checked locally for conflicts and nothing is found and have force pushed the rebase from main.

**Pull request closed without merging**
