### PR TITLE
tests: drivers: flash on stm32l475 requires higher stack size

### PR DESCRIPTION
**Pull request by FRASTM**
Increasing the stack size to pass the tests/drivers/flash testcase on the disco_l475_iot1 disco kit.
Note that CONFIG_MPU_ALLOW_FLASH_WRITE is set.

The tests/drivers/flash on this platform target is PASSED on each run (previously failed into hardfault on 1 of 2 runs)

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
west build -p auto -b disco_l475_iot1 tests/drivers/flash : 
```
I: qspi-nor-flash@0: SFDP v 1.6 AP ff with 3 PH
I: PH0: ff00 rev 1.6: 16 DW @ 30
I: qspi-nor-flash@0: 8 MiBy flash
I: PH1: ffc2 rev 1.0: 4 DW @ 110
*** Booting Zephyr OS build zephyr-v3.1.0-4715-gdd7b3488d886  ***
Running TESTSUITE flash_driver
===================================================================
START - test_read_unaligned_address
 PASS - test_read_unaligned_address in 0.035 seconds
===================================================================
TESTSUITE flash_driver succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [flash_driver]: pass = 1, fail = 0, skip = 0, total = 1 dus
 - PASS - [flash_driver.test_read_unaligned_address] duration = 0.035 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Review by enjiamai — DISMISSED** [review]

**Comment by FRASTM** [comment]
rebased on 4a702ea21ef82b301464551807358f8490951e45
includes the https://github.com/zephyrproject-rtos/zephyr/pull/49967

**Review by enjiamai — APPROVED** [review]
For the stack size increasing portion of this PR, I think I am for it. Because we also saw a few tests that need to increase the stack sizes after migrating the new ztest API.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
Remove first commit

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
