### PR TITLE
lib/os/prf.c: _ldiv5() optimizations

### PR DESCRIPTION
**Pull request by npitre**

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
This passes the tests in #29876 where I've applied the commits to the same routine in its proposed new home.

**Comment by npitre** [comment]
On Mon, 9 Nov 2020, Peter A. Bigot wrote:

> Just:
> 
>     *v = (v + 2U) / 5U;
> 
> would seem to be more clear. Also this can be `inline`.

The compiler already inlines this one on its own.

**Comment by pabigot** [comment]
> The compiler already inlines this one on its own.

At certain optimization levels, yes, some toolchains will do so.  I prefer to be explicit about intent.  But I agree it's not likely to be a problem for most cases.

**Comment by npitre** [comment]
It's probably best to let the compiler figure out what's best.

For example, I tried to pass v as a direct value rather than as a 
reference in the non-inline case and surprizingly the compiled code 
became larger on most architectures.

**Pull request merged**
