### PR TITLE
lib/timeutil: fix const correctness and remove undefined behavior

### LINKED ISSUE #18465: timeutil_timegm() has undefined behavior
Discussion in #18346 makes clear that the implicit undefined behavior of this function in cases where `time_t` cannot represent the true value needs to be addressed.  Do this before the API is part of a Zephyr release.

### PR DESCRIPTION
**Pull request by pabigot**
The algorithm for converting broken-down civil time to seconds in the POSIX epoch time scale would produce undefined behavior on a toolchain that uses a 32-bit time_t in cases where the referenced time could not be represented exactly.

However, there are use cases in Zephyr for civil time conversions outside the 32-bit representable range of 1901-12-13T20:45:52Z through 2038-01-19T03:14:07Z inclusive.

Add new API that specifically returns a 64-bit signed seconds count, and revise the existing API to detect out-of-range values and convert them to a diagnosible error.

Closes #18465

### CODE REVIEW

**Comment by pabigot** [comment]
`native_posix` is the only in-tree platform that uses 32-bit `time_t`.

**Review by carlescufi — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
@ioannisg can you take a look and see if we can get this merged?

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg can you take a look and see if we can get this merged?

Will do, that.

**Review by ioannisg — APPROVED** [review]

**Review by galak — COMMENTED** [review]
Is this change remove an API for timeutil_timegm?

**Comment by pabigot** [comment]
@galak it is technically an API change (return `time_t` to return `s64_t`, though only differences is on native_posix 32-bit).  I had this targeted for 2.0 (which is when the API was introduced) but it didn't get attention.

I suppose it might be accompanied by a release notes entry, if we have release notes entries for API changes.

**Comment by pabigot** [comment]
@galak Actually, looking closely, I don't think this is worth highlighting as an API change.  The return value did *not* change (a new function was added the provides full range regardless of `time_t`).  The change to indicate the function doesn't modify the reference passed in should have no impact on any use.

**Comment by pabigot** [comment]
?  The existing name `timeutil_timegm` did not change.  It was simply re-implemented based on a new 64-bit-safe function.

**Comment by galak** [comment]
> ? The existing name `timeutil_timegm` did not change. It was simply re-implemented based on a new 64-bit-safe function.

Ah, I missed it in the diff.. sorry for the noise.

**Pull request merged**
