### PR TITLE
NRF: DT: Re-organize nodes

### PR DESCRIPTION
**Pull request by galak**
Moving SRAM and Flash-Controller node definitions under "soc"

### CODE REVIEW

**Comment by ioannisg** [comment]
@galak , indeed, the output for nRF9160 is a bit different, but it looks to me that it is only a re-arrangement of the memory objects.

**Comment by ioannisg** [comment]
any plan to work on this @galak?

**Comment by ioannisg** [comment]
ping

**Comment by galak** [comment]
> ping

No plan, would love for you guys take this over.

**Comment by ioannisg** [comment]
> 
> 
> > ping
> 
> No plan, would love for you guys take this over.

Yes, we will.

**Review by ioannisg — APPROVED** [review]
I rebased that, added the changes for nRF52811, as well, and did some basic build-testing: I noticed that moving the flash-controller node into soc, simply, changes the order of the DT definitions in the generated dts.conf, but no changes in the actual content.

**Pull request merged**
