### PR TITLE
zephyr: Use deprecated instead of legacy for Kconfig int types

### PR DESCRIPTION
**Pull request by galak**
Rename the Kconfig symbol from LEGACY_ZEPHYR_INT_TYPES to
DEPRECATED_ZEPHYR_INT_TYPES.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
Thanks!

Would you mind also changing this:
https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/development_process/api_lifecycle.rst#deprecated

[...] or by introducing a Kconfig option (typically one that contains the ~LEGACY~ DEPRECATED word in it) that, when enabled, reverts the APIs back to their previous form

**Comment by galak** [comment]
> Thanks!
> 
> Would you mind also changing this:
> https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/development_process/api_lifecycle.rst#deprecated
> 
> [...] or by introducing a Kconfig option (typically one that contains the ~LEGACY~ DEPRECATED word in it) that, when enabled, reverts the APIs back to their previous form

Done in https://github.com/zephyrproject-rtos/zephyr/pull/26048.

**Review by carlescufi — APPROVED** [review]

**Comment by jukkar** [comment]
To me, calling the option with `LEGACY` would be fine here as the deprecation status is set separately with `__DEPRECATED_MACRO`, so there is no need to mention it multiple times. No strong opinion here, this change just feels unnecessary.

**Review by nashif — APPROVED** [review]

**Comment by galak** [comment]
> To me, calling the option with `LEGACY` would be fine here as the deprecation status is set separately with `__DEPRECATED_MACRO`, so there is no need to mention it multiple times. No strong opinion here, this change just feels unnecessary.
> 
> The commit message tells what it is changing but lack information why we are doing the change.

Not all cases can be covered by the __DEPRECATED_MACRO and so sometimes we have to utilize a Kconfig option.

**Pull request merged**
