### PR TITLE
drivers: sensor: icm42605: Fix use of deprecated API

### LINKED ISSUE #32151: Use of deprecated macro's in icm42605
The icm42605 driver use DEVICE_AND_API_INIT which is deprecated.

### PR DESCRIPTION
**Pull request by galak**
Fixes #32151

### CODE REVIEW

**Comment by galak** [comment]
@JHKim8212 FYI.  Number if issues in having the driver even compile.

**Review by gmarull — COMMENTED** [review]
I wonder why build issues were not spotted by https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/drivers/build_all/sensors_i_z.conf#L9 ? Maybe because even CMake entry was missing?

**Review by gmarull — CHANGES_REQUESTED** [review]
Build still fails because no instances use the driver, I suppose it needs to be added here https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/drivers/build_all/spi.dtsi (sensor entry and new CS entry)

**Comment by JHKim8212** [comment]
@galak I will also check on my environment after pull all Zephyr project.

**Comment by galak** [comment]
> I wonder why build issues were not spotted by https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/drivers/build_all/sensors_i_z.conf#L9 ? Maybe because even CMake entry was missing?

Yeah, the cmake missing meant it pretty much got skipped.

**Review by gmarull — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
thanks @galak

**Pull request merged**
