### PR TITLE
boards:arm:olimexino_stm32: Activate CAN on olimexino stm32

### PR DESCRIPTION
**Pull request by SebastianStumm**
This commit adds support for CAN on the olimexino_stm32 board.
CAN was added to stm32f103Xb.dtsi, pinmux_stm32f1.h and stm32-pinctrlf1.h
CAN_RX: PB8, CAN_TX: PB9

Signed-off-by: Sebastian Stumm <sstumm@localhost.localdomain>

### CODE REVIEW

**Review by ydamigos — CHANGES_REQUESTED** [review]
Hi @SebastianStumm,

thanks for enabling CAN on olimexino_stm32. I tried to run `tests/drivers/can/api` on my olimexino_stm32 board but tests failing with 'Device not found'.

```***** Booting Zephyr OS v1.14.0-rc3-249-                                               *
Running test suite can_driver
===================================================================
starting test - test_set_loopback

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:285: test_)
Device not not found
FAIL - test_set_loopback
===================================================================
starting test - test_send_and_forget

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:300: test_)
Device not not found
FAIL - test_send_and_forget
===================================================================
starting test - test_filter_attach

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:315: test_)
Device not not found
FAIL - test_filter_attach
===================================================================
starting test - test_receive_timeout

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:352: test_)
Device not not found
FAIL - test_receive_timeout
===================================================================
starting test - test_send_receive_std

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:242: send_)
Device not not found
FAIL - test_send_receive_std
===================================================================
starting test - test_send_receive_ext

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:242: send_)
Device not not found
FAIL - test_send_receive_ext
===================================================================
starting test - test_send_receive_std_masked

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:242: send_)
Device not not found
FAIL - test_send_receive_std_masked
===================================================================
starting test - test_send_receive_ext_masked

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:242: send_)
Device not not found
FAIL - test_send_receive_ext_masked
===================================================================
starting test - test_send_receive_wrong_id

    Assertion failed at <ZEPHYR_SDK>/tests/drivers/can/api/src/main.c:418: test_)
Device not not found
FAIL - test_send_receive_wrong_id
===================================================================
Test suite can_driver failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Comment by erwango** [comment]
Thanks @SebastianStumm for this contribution.
While it is not explicitely stated in documentation, it seems to me you should provide a valid email address as DCO (https://docs.zephyrproject.org/latest/contribute/index.html#developer-certification-of-origin-dco)

**Comment by galak** [comment]
@SebastianStumm any plans to address the feedback?  If not we will close those PR and feel free to re-open if you want to re-submit the change.  Thanks.

**Comment by alexanderwachter** [comment]
Closed in favor of #20462

**Pull request closed without merging**
