### PR TITLE
dts: atmel_sam: Refactor SoC dts.fixup into arch/arm/soc/atmel_sam

### PR DESCRIPTION
**Pull request by galak**
Move common SoC dts.fixup defines into
arch/arm/soc/atmel_sam/<BAR>/dts.fixup so we remove duplication in the
boards and only have board specific defines in
boards/arm/<FOO>/dts.fixup.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by fallrisk — APPROVED** [review]
Yup, all these fixes are for the SoC and are not specific to a board.

**Review by nzmichaelh — COMMENTED** [review]
To confirm, this only adds comments to three files and doesn't change anything else?

**Comment by fallrisk** [comment]
It moves the files into SoC from board.

**Comment by nzmichaelh** [comment]
Ah, I missed the 'boards/arm/arduino_due/dts.fixup → arch/arm/soc/atmel_sam/sam3x/dts.fixup' in the diff.

**Pull request merged**
