### PR TITLE
drivers: sensor: qdec_mcux: ENC_Init on changed settings

### PR DESCRIPTION
**Pull request by jeppenodgaard**
Call ENC_Init in qdec_mcux_attr_set when changing data->qdec_config.
Otherwise the changed settings has no effect.

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]

**Comment by mmahadevan108** [comment]
@jeppenodgaard, any thoughts on the above comment.

**Comment by jeppenodgaard** [comment]
> @jeppenodgaard, any thoughts on the above comment.

I agree. Sorry for the delay. I do not have access to hardware to test changes atm.

**Comment by jeppenodgaard** [comment]
@mmahadevan108 I've added and tested your suggestion on mimxrt1050_evk.

**Review by MaureenHelm — APPROVED** [review]

**Comment by MaureenHelm** [comment]
@mmahadevan108 please revisit

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
