### PR TITLE
subsys: usb: Change the buffer fragmentation for IN transfers.

### PR DESCRIPTION
**Pull request by pawelzadrozniak**
USB controller was performing the fragmentation by itself and the driver
was not aware if current chunk is the last one if data size is equal to
maximum chunk size. Some hardware controllers (i.e. in nRF52840) handle
the status stage by hardware which must be triggered after the last data
chunk.
Currently, the whole remaining data is passed to the driver, and the
driver decides whether to fragment the data internally, or send only
the chunk and report back to the stack.

Signed-off-by: Paweł Zadrożniak <pawel.zadrozniak@nordicsemi.no>

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
@ydamigos Can you please test it with stm32 hal driver?

**Comment by carlescufi** [comment]
@finikorg can you test this with the platforms available to you?

**Comment by finikorg** [comment]
@carlescufi works for quark_se

**Comment by jfischer-phytec-iot** [comment]
@carlescufi yes, usb_dc_kinetis passes all test (`samples/subsys/usb/testusb` + testusb tool from linux kernel). 101 has the same problems as with master, but passes TEST 9 and TEST 10. Generally LGTM, I do not expect any problems.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Approving as per comments above from @finikorg and @jfischer-phytec-iot

**Review by jfischer-no — APPROVED** [review]
LGTM

**Comment by jfischer-phytec-iot** [comment]
@carlescufi Let us wait for @ydamigos ok

**Review by finikorg — APPROVED** [review]

**Review by ydamigos — CHANGES_REQUESTED** [review]
I tested on stm32f3_disco board with cdc_acm sample and it fails to recognize the device when I plug the USB cable.

**Comment by carlescufi** [comment]
>I tested on stm32f3_disco board with cdc_acm sample and it fails to recognize the device when I plug the USB cable.

@ydamigos thanks for testing. Do you have any idea why this is failing? @jfischer-phytec-iot any clues?

**Review by ydamigos — APPROVED** [review]
@carlescufi Thanks. LGTM.

**Review by loicpoulain — APPROVED** [review]

**Comment by aurel32** [comment]
I don't think the STM32 change is correct. This effectively limit the transfer size to 64 bytes for ALL endpoints instead of doing that for only endpoint 0. This is an issue in high speed mode

**Comment by carlescufi** [comment]
> I don't think the STM32 change is correct. This effectively limit the transfer size to 64 bytes for ALL endpoints instead of doing that for only endpoint 0. This is an issue in high speed mode

I believe you are right. Can you check the updated version I've pushed?

**Comment by carlescufi** [comment]
@ydamigos just to be sure, would you be able to test this on hw? I assume it will work now, but just in case. Otherwise we can always merge and then I can fix it after the fact, let me know.

**Comment by aurel32** [comment]
Thanks for the updated version. Unfortunately I won't have access to my boards before tomorrow night. I guess @ydamigos can have a try.

As for the real issue, one guess is that the STM32 HAL layer is doing the fragmentation, and assumes that the buffer is valid during the whole transfer, while the USB code assumes that once the function returns the buffer can be overwritten. It's only a guess as I can't check on real hardware right now. I wonder if we should switch to using the STM32 LL instead of HAL, even if it is a lot of work.

**Comment by carlescufi** [comment]
>As for the real issue, one guess is that the STM32 HAL layer is doing the fragmentation, and assumes that the buffer is valid during the whole transfer, while the USB code assumes that once the function returns the buffer can be overwritten. 

That could be, or maybe the HAL is limited to 64 bytes when writing to EP0.

> I wonder if we should switch to using the STM32 LL instead of HAL, even if it is a lot of work.

Maybe someone is willing to do that work but right now the priority is that the USB stack works with all current drivers.

**Comment by aurel32** [comment]
> That could be, or maybe the HAL is limited to 64 bytes when writing to EP0.

That's indeed another option. Without having the hardware it's difficult to say.

> > I wonder if we should switch to using the STM32 LL instead of HAL, even if it is a lot of work.

> Maybe someone is willing to do that work but right now the priority is that the USB stack works with all current drivers.

I fully agree, I don't say that we have to fix that part now, I was just giving ideas for fixing it on the long term. On the short term your new version looks fine to me, just that I can't test it.

**Comment by ydamigos** [comment]
@carlescufi @aurel32 I tested it and it works on full speed. I don't have a device which supports high speed.

**Comment by carlescufi** [comment]
Thanks both @ydamigos and @aurel32

**Pull request merged**
