### PR TITLE
Adding FMC to H56x-series

### PR DESCRIPTION
**Pull request by ts4ling**
As requested in

https://github.com/zephyrproject-rtos/zephyr/issues/77888

I'm adding the DT basics for the flexible memory controller.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Please extend to h533.dtsi as it is also supported on this SoC.
Also please fix CI issue reported here:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/10883689829/job/30197382533?pr=78481#step:11:45

Unfortunately there is no in tree board which would help to test this so we'll rely on your feedback.

**Comment by ts4ling** [comment]
Well, I would fix the `check-warns` errors, but the errors isn't verbose enough. I can dive into the element and find this note
```
The log was not found. It may have been deleted based on retention settings.
```
But no reason for the error.
`h533.dtsi` looks pretty empty, I'll add the fmc node.

**Comment by ts4ling** [comment]
> But no reason for the error.

Ah, it's the commit message again...I guess.

**Review by erwango — APPROVED** [review]
That's perfect, thanks!

**Review by marwaiehm-st — APPROVED** [review]

**Pull request merged**
