### PR TITLE
console: native: fix in Kconfig descriptions

### PR DESCRIPTION
**Pull request by aescolar**
Improve the prompts and help messages for the NATIVE CONSOLE options to make them less ambigous

### CODE REVIEW

**Comment by ulfalizer** [comment]
Not an expert on these symbols, but probably reasonable.

The naming and help texts for `NATIVE_POSIX_CONSOLE` ("Use native stdin and stdout to print messages and get input") and `NATIVE_POSIX_STDIN_CONSOLE` ("Use native console to get input") are confusing to me. Kinda looks like the first one implies the second one. Guessing whoever added that `depends on` thought the same...

Unrelated, but the symbol definition could be a simplified a bit by the way:

```
config NATIVE_POSIX_STDIN_CONSOLE
	bool "Read from native stdin for console"
	default y if NATIVE_POSIX_CONSOLE
	depends on ARCH_POSIX
	help
	  Use native console to get input.
```

Just `default NATIVE_POSIX_CONSOLE` would work too.

**Comment by aescolar** [comment]
> The naming and help texts for 

Yep, it is a bit confusing due to "native console" referring both to the host console/terminal, and sometimes referring to the NATIVE_CONSOLE

**Comment by aescolar** [comment]
@ulfalizer Hopefully it is a bit clearer after this new commit

**Comment by ulfalizer** [comment]
Yeah, bit clearer at least.

Still a bit weird that you can have both "feed the host terminal stdin to the Zephyr console/shell" and "Zephyr's printk messages will be directed to the host terminal stdout", while at the same time not having "the host terminal is used for the Zephyr console".

**Comment by ulfalizer** [comment]
Or that you can have "the host terminal is used for the Zephyr console" while having none of the other ones.

Makes my head spin a bit...

**Comment by aescolar** [comment]
@ulfalizer: Actually, my mistake, it is not cleanly possible.. So I just changed the PR to only clarify the descriptions..
`NATIVE_POSIX_CONSOLE` is only there for the purpose of getting native_posix_console.c to compile.
And inside that file, there is, independently, code for the stdin and the stdout part.

**Review by nashif — APPROVED** [review]

**Review by ulfalizer — APPROVED** [review]

**Pull request merged**
