### PR TITLE
pm: Remove unused fields in pm_device

### PR DESCRIPTION
**Pull request by ceolin**
Several fields on struct pm_device are just necessary when
built with PM_DEVICE_RUNTIME.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]

**Review by teburd — CHANGES_REQUESTED** [review]
I agree with gmarull, it would be nice to avoid the duplicated doc comments

**Review by teburd — APPROVED** [review]
looks good!

**Review by gmarull — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by kurddt** [comment]
@cfriedt Do you think this change could be backported to 2.7 ?

**Comment by cfriedt** [comment]
> @cfriedt Do you think this change could be backported to 2.7 ?

@kurddt, @ceolin - does this change fix a bug? If so, it needs to have an associated issue.

**Comment by kurddt** [comment]
It's not a bug per se but could free up quite some ROM and RAM. I tried to look up for an associated bug or feature request but couldn't find anything

**Comment by cfriedt** [comment]
> It's not a bug per se but could free up quite some ROM and RAM. I tried to look up for an associated bug or feature request but couldn't find anything

That in itself could be considered a bug. Please create one.

**Comment by ceolin** [comment]
It i s not a bug IMHO but an enhancement. Though it an harmless be ported to 2.7.

**Comment by kurddt** [comment]
@cfriedt I created #42622

**Pull request merged**
