### PR TITLE
drivers/subsys: usb: fix issues with init.h

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Review by jfischer-no — DISMISSED** [review]
Please group USB-related commits into one PR.

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by gmarull** [comment]
@jfischer-no other USB PRs have been already merged

**Review by carlescufi — DISMISSED** [review]

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Well, there should be some time elapsed before a PR gets merged, so it would not happen that there are ~~tree~~ four PRs doing the same oneline fix if this guideline had been followed. I will block this for 24 hours in case you find another one.

**Comment by gmarull** [comment]
merged all remaining USB cases, I see no other required fixed in drivers/usb nor subsys/usb now.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]
Thanks

**Pull request merged**
