### PR TITLE
dma: Enable support on stm32wb, memory to memory mode

### PR DESCRIPTION
**Pull request by erwango**
Enable memory to memory dma operations on STM32WB series.
 Tested on nucleo_wb55rg with dma tests loop_transfer and chan_blen_transfer.

Based  on https://github.com/zephyrproject-rtos/zephyr/pull/20543

### CODE REVIEW

**Comment by cybertale** [comment]
LGTM, this focuses on dts changes, so I checked some basic parameters and it seems like everything is fine.

**Comment by erwango** [comment]
> LGTM, this focuses on dts changes, so I checked some basic parameters and it seems like everything is fine.

@cybertale Can you approve the change then ?

**Review by FRASTM — COMMENTED** [review]
CONFIG_HEAP_MEM_POOL_SIZE=1024
is defined for any stm32 soc in the ./soc/arm/st_stm32/common/Kconfig.defconfig.series

**Comment by erwango** [comment]
@FRASTM should I close this one? I think it is supersede by your work.

**Comment by FRASTM** [comment]
Yes, this PR is now covered by the #20825

**Comment by erwango** [comment]
@FRASTM, thanks for confirming. Let me close this one.

**Pull request closed without merging**
