### PR TITLE
Configure lpuart flow control pin mux

### PR DESCRIPTION
**Pull request by MarkWangChinese**

### CODE REVIEW

**Review by danieldegrasse — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by bas-archembedded** [comment]
@MarkWangChinese Doesn't this just check if the FLOWCONTROL state exists and never actually select it ?

**Comment by MarkWangChinese** [comment]
> @MarkWangChinese Doesn't this just check if the FLOWCONTROL state exists and never actually select it ?

Sorry, I don't get your point, do you mean how to enable the uart flowcontrol? It is enabled by the DT that can be overwritten by overlay file.

**Comment by MarkWangChinese** [comment]
> > > @MarkWangChinese Doesn't this just check if the FLOWCONTROL state exists and never actually select it ?
> > 
> > 
> > Sorry, I don't get your point, do you mean how to enable the uart flowcontrol? It is enabled by the DT that can be overwritten by overlay file.
> 
> From what I read, err = pinctrl_lookup_state(config->pincfg, PINCTRL_STATE_FLOWCONTROL, &state); only looks up the state but it never actually transitions into that state anywhere ? IMHO this needs to be pinctrl_apply_state(config->pincfg, PINCTRL_STATE_FLOWCONTROL); ? pinctrl_apply_state() checks if the state is valid and if not returns error and in that case it will use "default" pinmux as the lpuart driver code then applies the default state.

Yes, I think you are right, Thanks. The `pinctrl_lookup_state` should be replaced by `pinctrl_apply_state` through the static codes review. I remember that I did test with bluetooth audio sample. Will you create pr to fix it?

**Comment by bas-archembedded** [comment]
> > > > @MarkWangChinese Doesn't this just check if the FLOWCONTROL state exists and never actually select it ?
> > > 
> > > 
> > > Sorry, I don't get your point, do you mean how to enable the uart flowcontrol? It is enabled by the DT that can be overwritten by overlay file.
> > 
> > 
> > From what I read, err = pinctrl_lookup_state(config->pincfg, PINCTRL_STATE_FLOWCONTROL, &state); only looks up the state but it never actually transitions into that state anywhere ? IMHO this needs to be pinctrl_apply_state(config->pincfg, PINCTRL_STATE_FLOWCONTROL); ? pinctrl_apply_state() checks if the state is valid and if not returns error and in that case it will use "default" pinmux as the lpuart driver code then applies the default state.
> 
> Yes, I think you are right, Thanks. The `pinctrl_lookup_state` should be replaced by `pinctrl_apply_state` through the static codes review. I remember that I did test with bluetooth audio sample. Will you create pr to fix it?

I have created it here: https://github.com/zephyrproject-rtos/zephyr/pull/88866. Thanks for checking :)

**Pull request merged**
