### PR TITLE
doc: usb: Update API doc

### PR DESCRIPTION
**Pull request by loicpoulain**
Add missing DC driver functions:
- usb_dc_ep_read_wait
- usb_dc_ep_read_continue
- usb_dc_ep_mps

Add missing DC status code:
- USB_DC_INTERFACE

Document new transfer API.

Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

### CODE REVIEW

**Review by jfischer-no — COMMENTED** [review]
LGTM

**Review by finikorg — APPROVED** [review]

**Review by dbkinder — DISMISSED** [review]
While the changes look OK, why is this documentation duplicated here and not just maintained in the header files and use the doxygen collected content in this document?

**Comment by loicpoulain** [comment]
@dbkinder, Agree, I've just seen #5702.

**Review by dbkinder — APPROVED** [review]
Address #5702 in a separate PR

**Pull request merged**
