### PR TITLE
Revert "soc: intel: renamed soc from ace30_ptl to ace30"

### LINKED ISSUE #78931: SOF module sample tests broken in Zephyr main for ace30_ptl
**Describe the bug**
In https://github.com/zephyrproject-rtos/zephyr/commit/a654bfbdfa002ac5ab32d8593d762f5ef3dc4868 the ace30_ptl SOC kconfig and twister identifiers were renamed. But the SOF module uses the old ones still.
This broke Zephyr's main CI:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11009734491/job/30570116372

**To Reproduce**

**Expected behavior**
No broken tests in main CI
=> No uses of those renamed kconfig options and identifiers in modules

**Impact**
Broken main CI

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11009734491/job/30570116372

**Environment (please complete the following information):**

 - OS: Linux, Ubuntu 22.04 CI
 - Toolchain (e.g Zephyr SDK, ...): N/A
 - Commit SHA or Version used: main now: 45727b5fe141624a03866ff694c563830a26dfa4

**Additional context**
Introduced in https://github.com/zephyrproject-rtos/zephyr/pull/78474

### PR DESCRIPTION
**Pull request by aescolar**
This reverts commit a654bfbdfa002ac5ab32d8593d762f5ef3dc4868.

This commit broke Zephyr CI, as both the platform name and SOC kconfigs are used in the SOF module which would also need an update. Doing such an update is out of scope for a hotfix.

Fixes #78931

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Comment by Thalley** [comment]
For some reason GH won't let me add the original author of those, @gbernatxintel as a reviewer...

**Comment by tomi-font** [comment]
> For some reason GH won't let me add the original author of those, @gbernatxintel as a reviewer...

It's because of the 15-reviewer limit.

**Review by stephanosio — APPROVED** [review]

**Comment by nashif** [comment]
we have a proper fix: https://github.com/zephyrproject-rtos/zephyr/pull/78932

**Review by nashif — CHANGES_REQUESTED** [review]
we have a proper fix, lets avoid a revert in this case.

**Comment by aescolar** [comment]
Closing as not needed

**Pull request closed without merging**
