### PR TITLE
Generate devicetree errors for actual source files, not intermediate files

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This causes any devicetree error messages to refer to the source files
which contain the errors instead of intermediate `<BOARD>.dts.pre.tmp`
files in the build directory.

Do this using a new python-devicetree feature which can correctly
handle cpp's generated line marker directives. This requires some re-work
to a few longstanding implementation details.

### CODE REVIEW

**Review by gmarull — APPROVED** [review]
Would be nice to print something like this in case of error:
```
board.dts:2:20: error: the error description
&pwm0 {
    status = "okay"
                ~~~^
```

**Comment by mbolivar-nordic** [comment]
> Would be nice to print something like this in case of error:

Agreed, but let's put that off for a future enhancement for now. The issue is that GCC's preprocessor collapses whitespace, so the line numbers in the preprocessor output are accurate, but the columns may differ from the input files, so it's not a perfect match.

Thanks for review.

**Review by SebastianBoe — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by teburd — APPROVED** [review]
Well seeing as I've run into this, and the confusing errors that came before this change, gets a huge +1 from me.

**Review by henrikbrixandersen — APPROVED** [review]
Thank you!

**Comment by mbolivar-nordic** [comment]
Related mcuboot PR: https://github.com/mcu-tools/mcuboot/pull/1235

**Pull request merged**
