### PR TITLE
mgmt: mcumgr: grp: fs_mgmt: set .upload flag in file_access_data if uploading

### PR DESCRIPTION
**Pull request by JiapengLi**
set .upload flag in file_access_data if uploading

### CODE REVIEW

**Review by nordicjm — DISMISSED** [review]

**Review by de-nordic — DISMISSED** [review]
Looks OK.

**Comment by JiapengLi** [comment]
add a space fix the commit name, sorry for the inconvenience.

**Review by nordicjm — CHANGES_REQUESTED** [review]
Commit body needs a description, see https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines for details

**Comment by JiapengLi** [comment]
Sorry for the mistake and thank you for the ref link. Just fix.

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
