### PR TITLE
logging: fix dictionary logging and added pytest

### PR DESCRIPTION
**Pull request by dcpleung**
(See individual commits for details.)

### CODE REVIEW

**Comment by dcpleung** [comment]
Documentation error is due to 73235.

**Comment by nashif** [comment]
@dcpleung  please rebase.

**Comment by dcpleung** [comment]
Rebased.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
re-assigning to @dcpleung  who maintains the dictionary logging feature and its tests.

**Review by teburd — APPROVED** [review]

**Pull request merged**
