### PR TITLE
[TOPIC-GPIO] drivers: sensors: vl53l0x: update to new GPIO API

### PR DESCRIPTION
**Pull request by erwango**
Update to the new GPIO API.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by avisconti — APPROVED** [review]
LGTM!

**Comment by avisconti** [comment]
@erwango do you need to update #20017?

**Comment by erwango** [comment]
> @erwango do you need to update #20017?

@avisconti, already done if I'm correct.

**Comment by avisconti** [comment]
> > @erwango do you need to update #20017?
> 
> @avisconti, already done if I'm correct.

Correct! Sorry for the noise.

**Pull request merged**
