### PR TITLE
Bluetooth: Mesh: Fix persistent storage behavior

### PR DESCRIPTION
**Pull request by jhedberg**
These patches fix various things that were broken with the persistent storage behavior. I think this may be a good candidate for 1.12.1

@MariuszSkamra it'd be good to do a PTS test run on this PR.

@vikrant8051 this should fix the issue you saw with the node state not being completely restored if you did an intermediate node reset, reprovisioning and a power cycle.

### CODE REVIEW

**Comment by vikrant8051** [comment]
@jhedberg That's great !!  And Thank You !!

**Review by carlescufi — APPROVED** [review]
No objections, looks good.

**Comment by jhedberg** [comment]
> @jhedberg I'll run the tests EOD to have the results tomorrow

Thanks @MariuszSkamra , what's the verdict?

**Review by MariuszSkamra — APPROVED** [review]
Looks good, tests passed, no regressions found

**Comment by jhedberg** [comment]
> Looks good, tests passed, no regressions found

Thanks @MariuszSkamra !

**Pull request merged**
