### PR TITLE
pm: device: Add wakeup state property

### PR DESCRIPTION
**Pull request by pdgendt**
Add a dts binding property to override the initial wakeup state.

With battery powered boards it is possible that peripheral
devices start in a non-active state (e.g. suspended or off).

Allow to statically override the wakeup state.

### CODE REVIEW

**Comment by ceolin** [comment]
@pdgendt It is intended to be used only when system is initializing, or it  should be used every time the SoC becomes ACTIVE (e.g: resumes from PM_STATE_STANDBY) ?

The property name suggest the latter but I'm not sure which is the intention.

**Comment by ceolin** [comment]
That needs to be properly documented because will impact drivers initialization, they will need be "power" aware at this early stage, what does not happen right now.

The idea makes sense for me, just need to understand exactly how is intended to work and and document it.

**Comment by pdgendt** [comment]
Hey @ceolin ,

> @pdgendt It is intended to be used only when system is initializing, or it should be used every time the SoC becomes ACTIVE (e.g: resumes from PM_STATE_STANDBY) ?
> 
> The property name suggest the latter but I'm not sure which is the intention.

The intention is indeed to be used when system is initializing, if the SoC is resuming from standby, it'll probably have the device states still in memory.
I wasn't sure about the naming as well, but figured I could re-use the `wakeup` prefix. Maybe `startup-state` makes more sense?

> That needs to be properly documented because will impact drivers initialization, they will need be "power" aware at this early stage, what does not happen right now.

The addition of this property can be used IMO for drivers to behave differently during initialization, however my first intention was to play nicely with the device power management API from the application's perspective. Currently all devices are considered **active** until actively set otherwise. So performing a resume action would return `-EALREADY` and there is no way around that currently AFAIK.

What changes would you like to see then for this PR?

**Review by gmarull — CHANGES_REQUESTED** [review]
When the system boots up, all device init functions are called, meaning a device should be in active state. How is a device, e.g. in `off` state initialized? I'd like to understand what problem is this trying to solve (a real example would be useful), so adding -1 for now.

**Comment by pdgendt** [comment]
> When the system boots up, all device init functions are called, meaning a device should be in active state. How is a device, e.g. in `off` state initialized? I'd like to understand what problem is this trying to solve (a real example would be useful), so adding -1 for now.

@gmarull, the scenario where I use it for is on a battery powered board, where the main SoC (running zephyr) is suspended when inactive, and has an external wakeup (from a giro in my case). RAM isn't preserved in this state.
The zephyr application, before going to the suspended state, turns off all peripheral devices that otherwise would drain the battery.

On wakeup I leave it to the application to turn on the peripheral devices, as the `init` functions aren't dependent on actual communication.

Performing a resume action in the `init` function regardless of the startup state would result in slower boot times, or potentially wouldn't even work.

**Pull request closed without merging**
