### PR TITLE
Bluetooth: controller: Fix mayfly optimization

### PR DESCRIPTION
**Pull request by cvinayak**
Fix incorrect reset of mayfly pended flag. This fix reduces
CPU use by mayfly.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by wopu-ot** [comment]
I assume this PR would make #16714 obsolete?

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Comment by cvinayak** [comment]
Adding DNM until an issue I am analyzing gets to an acceptable conclusion.

**Comment by cvinayak** [comment]
Removed DNM, as this PR does not introduce any regression (tested manually and run through conformance testing)

**Review by wopu-ot — APPROVED** [review]

**Pull request merged**
