### PR TITLE
[DNM] pyOCD frequency support

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add support for specifying the SWDCLK frequency in Hz for pyOCD and use it for the nrf52840_pca10059 and nrf52_adafruit_feather boards (I have not been able to test it with other boards).

### CODE REVIEW

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
The west changes need to be submitted to https://github.com/zephyrproject-rtos/west instead

**Comment by henrikbrixandersen** [comment]
@MaureenHelm Thanks. I have submitted the west changes to zephyrproject-rtos/west#18.

**Comment by nashif** [comment]
lets close this and follow https://github.com/zephyrproject-rtos/west/pull/18 instead.

**Comment by henrikbrixandersen** [comment]
@nashif Ok, but we need to merge in the changes in this PR when the west functionality is merged in.

**Comment by carlescufi** [comment]
@henrikbrixandersen @mbolivar should we reopen this now?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen @mbolivar should we reopen this now?

@carlescufi No, it is handled in #17180.

**Pull request closed without merging**
