### PR TITLE
drivers: gpio: nrf5 add polarity logic, and other

### PR DESCRIPTION
**Pull request by findlayfeng**
1.Correct handling of polarity flags
2.Correct handling enable callback by port
3.Correct handling disable callback by port

Signed-off-by: Findlay Feng <i@fengch.me>

### CODE REVIEW

**Comment by ioannisg** [comment]
@findlayfeng Looks like the changes in this PR, listed in the description, could be done in separate commits, since they seem to be independent of each other. I wonder if you could do this split, to ease the review.

**Comment by findlayfeng** [comment]
Ok, wait a while

**Comment by ioannisg** [comment]
@findlayfeng could you please rebase this pr?

**Comment by findlayfeng** [comment]
I need to confirm if this pr is needed, and other alternatives have been added to the latest code.

**Comment by findlayfeng** [comment]
This pr is no longer needed

**Pull request closed without merging**
