### PR TITLE
doc: doxygen: generate and expose Doxygen tag file

### PR DESCRIPTION
**Pull request by JordanYates**
Generate the doxygen tag file when building documentation and expose it on the website for external projects to link against.
See https://www.doxygen.nl/manual/external.html

IMO it makes sense to enable external users to link to the LTS docs over the next few years, hence the backport.

Backport of #41688 and #41530

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/41529

### CODE REVIEW

**Comment by JordanYates** [comment]
FYI @gmarull

**Review by gmarull — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by gmarull** [comment]
@JordanYates this should also be backported: https://github.com/zephyrproject-rtos/zephyr/pull/42468

**Comment by JordanYates** [comment]
> @JordanYates this should also be backported: #42468

Done

**Comment by cfriedt** [comment]
Associated issue is #41529

**Pull request merged**
