### PR TITLE
Revert "pm: device: add driver init helper"

### PR DESCRIPTION
**Pull request by JordanYates**
Reverts zephyrproject-rtos/zephyr#60411
Was merged before #60410, which has not yet been approved.

### CODE REVIEW

**Comment by gmarull** [comment]
Maybe we can wait until https://github.com/zephyrproject-rtos/zephyr/pull/60410 gets merged today?

**Comment by benediktibk** [comment]
Would this fix #60766?

**Comment by JordanYates** [comment]
> Maybe we can wait until #60410 gets merged today?

It's probably best to revert it as #60410 has gained a few extra commits since the merged PR was opened and I don't know what merging it looks like at this point.

**Comment by JordanYates** [comment]
> Would this fix #60766?

Looks like it, the twister invocation you provided worked on the branch as merged but not after I manually rebased on main

**Comment by JordanYates** [comment]
Also causing CI failures

**Review by carlescufi — APPROVED** [review]

**Comment by JordanYates** [comment]
@gmarull @erwango can you please approve

**Review by erwango — APPROVED** [review]

**Comment by carlescufi** [comment]
Compliance failures are just no signed-off-by in revert commits.

**Comment by fabiobaltieri** [comment]
Sorry Jordan, should have added a DNM there, #60410 went in so I guess we can unrevert.

**Pull request merged**
