### PR TITLE
Add api for dac with continuous mode

### PR DESCRIPTION
**Pull request by shlomow**
Add suggestion of api for dac with continuous mode. The goal is to transmit samples with accurate frequency (using hardware triggers), and provide an api for continuously update the samples. Look at the updated include file for the api signatures.

I would be happy to here suggestions to make this api more proper and suitable for many use cases.

This also implements the api for stm32.

needs: #33918, #32713

### CODE REVIEW

**Comment by ikerperezdelpalomar** [comment]
Hi, I am working on applying DMA to ADC, I have an error I don't manage to fix so i had a look at you work in #33846 to compare it. The problem I have comes from when a dma direction is assigned, in your code that would be [line 454 of dac_stm32.c](https://github.com/shlomow/zephyr/blob/9a636bc40348053fb5c4d5eb6fba7c7ccf79b7a5/drivers/dac/dac_stm32.c#L454).

I build `tests/drivers/adc/adc_api/` as a test and I get the next error: 
```
error: 'struct adc_stm32_data' has no member named 'dma_dir'
```

which makes sense because `adc_stm32_data` doesn't have a `dma_dir` member, however your equivalent structure doesn't have it neither, and and [spi's driver's](https://github.com/zephyrproject-rtos/zephyr/blob/0a7ea88b064eeb50300ce624d81a5ad45032f7e9/drivers/spi/spi_ll_stm32.h#L32) one neither.

So I was wondering if you could have some hint about where should I be looking at to fix this.

Thanks

**Comment by shlomow** [comment]
I am not sure I understand. It is written as dma_##dir so the preprocessor concatenates the `dir`. Can you upload your work? By the way, I have all my work on the analog peripherals (including adc with dma) in an external module so you can just use it. The is also some applications on how to use it. Unfortunately the work on adc currently abuse the present api and not adding some dedicated functions for working with adc and dma. https://github.com/shlomow/stm32-adc-dma

**Comment by ikerperezdelpalomar** [comment]
> I am not sure I understand. It is written as dma_##dir so the preprocessor concatenates the `dir` 

Does that mean that the preprocessor will create the dir member in the structure?

> Can you upload your work? 

My work can be seen in this branch: https://github.com/ikerperezdelpalomar/zephyr/commits/adc_dma

>.By the way, I have all my work on the analog peripherals (including adc with dma) in an external module so you can just use it. The is also some applications on how to use it.

I will have a look at your work, I might use it, thanks!

>Unfortunately the work on adc currently abuse the present api and not adding some dedicated functions for working with adc and dma. https://github.com/shlomow/stm32-adc-dma

So what does involve adapting the current driver to DMA?

**Comment by shlomow** [comment]
I will try to look at your code.
My driver uses dma. When you call the read function the signal will be set after half of the buffer is filled. Look at the app that sends the samples over serial. But is uses dma fine and it is working for me for a few months

**Comment by ikerperezdelpalomar** [comment]
> I will try to look at your code.
> My driver uses dma. When you call the read function the signal will be set after half of the buffer is filled. Look at the app that sends the samples over serial. But is uses dma fine and it is working for me for a few months

I was wondering, how come that your work on applying dma to adc hasn't been merged to zephyr master branch?

**Comment by shlomow** [comment]
The current api of adc doesn't deal with use cases that needs to sample analog pins in buffer mode so dma can  used. This pr starts those api extensions

**Review by martinjaeger — COMMENTED** [review]
@shlomow Sorry that this is taking so long.

As the proposed API changes are quite significant and should be done in a similar way for the ADC, I want to have a closer look at how this is done in the Linux kernel IIO (as mentioned by @gmarull in the other PR). Unfortunately didn't find the time yet.

We are also planning to discuss ADC, DAC with DMA in the context of power electronics (where you also need the hardware triggers) at the Zephyr Developer Summit. Maybe you are interested to join aswell (the proposal has not been accepted, though).

**Pull request closed without merging**
