### PR TITLE
RFC: logging: Preparation for string literals stripping

### PR DESCRIPTION
**Pull request by nordic-krch**
In response to feature requested (#44942).

PR demonstrates how string literals stripping could be achieved. A non-existing memory region is created and memory section with logging string literals is put there. Section can be then removed from elf and make this region empty. Elf with section present can be used to build a database for dictionary logging.

Currently, it is supported only by `arm cortex_m`. non-existing region is created at address immediately following `ROM`. In case it overlaps with something there will be a linking error and we can add kconfig option to override this location. Since it is removed from final binary, region can overlap with anything not specified in the linker file (e.g. memory-mapped registers).

Elf stripping can be added as build post action. Original `zephyr.elf` can be copied as `zephyr_ext.elf` (used as input to dictionary python script). Then section can be stripped:
`arm-zephyr-eabi-objcopy -R log_strings_sections build/zephyr/zephyr_ext.elf build/zephyr/zephyr.elf`

Adding this post action would require extension to toolchain abstraction so help would be needed (@tejlmand ?).

Added a temporary modification to `hello_world` to show how configuration would look like.

### CODE REVIEW

**Comment by nordic-krch** [comment]
@UnicycleBloke fyi

**Comment by UnicycleBloke** [comment]
An interesting solution. Thanks for the heads up. In my alternative logger I placed the dictionary data at the end using zephyr_linker_sources(SECTIONS ...), and removed it as described above. I found that west flash uses the zephyr.hex generated from zephyr.elf, so it was necessary to regenerate the HEX after stripping the section from the ELF. Are POST_BUILD commands run before generating the HEX and BIN files from the ELF?

**Comment by UnicycleBloke** [comment]
An interesting solution. Thanks for the heads up. In my alternative logger I placed the dictionary data at the end using zephyr_linker_sources(SECTIONS ...), and removed it as described above. I found that west flash uses the zephyr.hex generated from zephyr.elf, so it was necessary to regenerate the HEX after stripping the section from the ELF. Are POST_BUILD commands run before generating the HEX and BIN files from the ELF?

**Comment by nordic-krch** [comment]
> I placed the dictionary data at the end using zephyr_linker_sources(SECTIONS ...)

I was afraid that at some point there will be another use case for putting something at the end so went for dedicated memory. In essence both solutions are similar. What is missing is all the post build actions with toolchain abstraction. There is a list of post build action, one of them is dictionary db build:
https://github.com/zephyrproject-rtos/zephyr/blob/acbdbb15dd808697b8efd15e753921f88a7b6020/CMakeLists.txt#L1718
It would need to be hooked somewhere there.

**Comment by optical-o** [comment]
@carlescufi Is this stale ? Or there is a plan to continue in development of this ?

**Comment by carlescufi** [comment]
> @carlescufi Is this stale ? Or there is a plan to continue the development of this ?

I'll check internally.

**Comment by carlescufi** [comment]
@optical-o I checked with @nordic-krch and he does not have plans to follow-up this work in the short term. Feel free to pick it up if you are interested!

**Pull request closed without merging**
