### PR TITLE
drivers: sensor: fcx_mldx5 issue 74761

### LINKED ISSUE #74761: [Coverity CID: 363738] Copy into fixed size buffer in drivers/sensor/fcx_mldx5/fcx_mldx5.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/dcf42917c550714d2457947538b9e29d083e872e/drivers/sensor/fcx_mldx5/fcx_mldx5.c

Category: Security best practices violations
Function: `fcx_mldx5_uart_send`
Component: Drivers
CID: [363738](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=363738)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/dcf42917c550714d2457947538b9e29d083e872e/drivers/sensor/fcx_mldx5/fcx_mldx5.c#L239

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=363738

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_STRING_OVERFLOW). ([CWE-120](http://cwe.mitre.org/data/definitions/120.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by jilaypandya**
This commit fixes #74761

### CODE REVIEW

**Review by jeppenodgaard — DISMISSED** [review]
LGTM

**Review by jeppenodgaard — COMMENTED** [review]
First check seems redundant now. Why keep it?

**Comment by jilaypandya** [comment]
> First check seems redundant now. Why keep it?

coz one of the values in  the array is zero and i think in this case, no memcpy operation shall take place.

```
static const uint8_t fcx_mldx5_cmds_data_len[] = {
        ********************************
	[FCX_MLDX5_CMD_RESET] = 0,
        ********************************
};
```

**Review by jeppenodgaard — APPROVED** [review]

**Comment by jeppenodgaard** [comment]
> > First check seems redundant now. Why keep it?
> 
> coz one of the values in  the array is zero and i think in this case, no memcpy operation shall take place.
> 
> ```
> static const uint8_t fcx_mldx5_cmds_data_len[] = {
>         ********************************
> 	[FCX_MLDX5_CMD_RESET] = 0,
>         ********************************
> };
> ```

Of course. Thanks for the explanation

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Please explain in the commit message why you are making this change. It's ok to reference a GitHub Issue number, but that in itself isn't sufficient.

**Review by MaureenHelm — APPROVED** [review]

**Review by jeppenodgaard — APPROVED** [review]

**Pull request merged**
