### PR TITLE
Build/flash/debug template file

### LINKED ISSUE #6831: Update template docs with build example
We've got a sphinx extension used to generate example build instructions.  Include use of the ``zephyr-app-commands`` extension in the sample templates found in the ``doc/templates`` folder, to help show how to use it (vs. using a ``code-block``)

### PR DESCRIPTION
**Pull request by mbolivar**
Fixes #6831

### CODE REVIEW

**Review by carlescufi — COMMENTED** [review]
Why is the doc itself a template? I thought it was documenting a template script, but why does the documentation file end with `.tmpl`?

**Comment by mbolivar** [comment]
> Why is the doc itself a template? I thought it was documenting a template script, but why does the documentation file end with .tmpl?

The original issue (#6831) requested that the file be put in that directory.

As noted in the commit log,

```
This isn't truly a "template" file, but it provides several examples
for common usage patterns along with a full list of options.
```

**Review by dbkinder — CHANGES_REQUESTED** [review]
This isn't quite the right approach to document this Sphinx extension.  If you don't mind, I'd suggest abandoning this PR and assign this to me. I'll take a stab at including the docstring from the python code into the Sphinx-generated documentation.

**Comment by mbolivar** [comment]
> If you don't mind, I'd suggest abandoning this PR and assign this to me. I'll take a stab at including the docstring from the python code into the Sphinx-generated documentation.

Even better :)

**Pull request closed without merging**
