### PR TITLE
board: nucleo_h723zg: enable backup_sram

### PR DESCRIPTION
**Pull request by manoj153**
this SoC supports backup sram
Signed-off-by: Manojkumar Subramaniam <manoj@electrolance.com>

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]
Docs should also be updated, see https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/nucleo_h743zi/doc/index.rst

**Review by FRASTM — APPROVED** [review]

**Comment by FRASTM** [comment]
and  **./boards/arm/nucleo_h723zg/nucleo_h723zg.yaml**  as well
`+  backup_sram`

**Comment by manoj153** [comment]
> Docs should also be updated, see https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/nucleo_h743zi/doc/index.rst



> and **./boards/arm/nucleo_h723zg/nucleo_h723zg.yaml** as well
> `+ backup_sram`

Done updating those

**Review by gmarull — APPROVED** [review]

**Comment by gmarull** [comment]
@manoj153 please check compliance failures.

**Comment by manoj153** [comment]
> @manoj153 please check compliance failures.

my bad, I missed to check out the test result.. all ok now

**Review by ABOSTM — APPROVED** [review]
LGTM

**Pull request merged**
