### PR TITLE
samples: bluetooth: Enable extended advertising support in hci_rpmsg

### PR DESCRIPTION
**Pull request by sjanc**
Extended advertising is now commonly used and there is no point in not enabling it by default in networking core. Especially that there is no "common" config for application and networking core to share Bluetooth configuration.

Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

### CODE REVIEW

**Comment by Thalley** [comment]
> Extended advertising is now commonly used and there is no point in not enabling it by default in networking core. Especially that there is no "common" config for application and networking core to share Bluetooth configuration.

I think I disagree. Extended advertising has a significant larger memory footprint IIRC, and there is a reason why it isn't enabled by default. 

AFAIK this change is to fix the failing test cases for Mesh, right? Perhaps it would be better to simply add it for the netcore compilation for those tests instead. 

But I also want to hear other's opinions

**Comment by cvinayak** [comment]
> Extended advertising has a significant larger memory footprint IIRC, and there is a reason why it isn't enabled by default.

Yes. Extended advertising is not enabled by default in Bluetooth subsystem.

You should create a testing specific conf file, this way you can have this separate conf file meeting the testing needs and without issues when defaults in Bluetooth subsystem may be changed in future. Add this conf file to sample.yaml so that the application is build tests by CI.

**Comment by jori-nordic** [comment]
IMO the nRF5340 is not a small device, so enabling extended advertising will likely be done by the user anyways, so it makes sense to enable it by default there.

If applications need to run multiple network stacks in the network core, they can disable it as needed in their netcore prj.conf or overlays.

**Comment by Thalley** [comment]
> IMO the nRF5340 is not a small (ie memory-constrained) device, so enabling extended advertising will likely be done by the user anyways, so it makes sense to enable it by default there.
> 
> If applications need to run multiple network stacks in the network core, they can disable it as needed in their netcore prj.conf or overlays.

If that is the case, then extended advertising should be enabled by default for the board, and not for `hci_rpmsg`, right? 

It feels odd to argue that extended advertising should be enabled by default in all cases, and then only enable it for a single sample application.

**Comment by sjanc** [comment]
Ext adv is enabled in bluetooth stack by default if you enable mesh...

I choose to enable it by default in hci_rpmsg was to keep things simple, otherwise one needs to keep both cores in sync when enabling host features. And that sample is used only for networking core and there is no easy way to force specific configuration based on application core application configuration.

anyway, I'm fine with dedicated config for netcore with EA enabled if that is preferred.

**Comment by Thalley** [comment]
> I choose to enable it by default in hci_rpmsg was to keep things simple, otherwise one needs to keep both cores in sync when enabling host features. And that sample is used only for networking core and there is no easy way to force specific configuration based on application core application configuration.

This is a challenge we face with LE Audio as well (where we need to enable much more features than Mesh). For ISO support we ended up with the specific configuration files 

https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/hci_rpmsg/nrf5340_cpunet_iso_receive-bt_ll_sw_split.conf
https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/hci_rpmsg/nrf5340_cpunet_iso_broadcast-bt_ll_sw_split.conf

To handle it. While I see your point, I am not sure I agree that Mesh should be handled uniquely, and I think it is more proper that we find a common solution for Mesh/ISO/LE Audio/Direction Finding, etc. who all need specific netcore configurations to work properly. 

For example you also have stuff like `BT_CTLR_MESH_SCAN_FILTERS` which are Mesh specific controller configs. 

That being said, I would be OK to enable EXT_ADV for the nRF5340 development kit (would need to move your suggested change into a board config file instead), rather than enabling it for the entire sample.

**Comment by sjanc** [comment]
We can also overlay it directly in autopts for nrf5340, I'll see how this works out and either close or update this PR

**Comment by sjanc** [comment]
we fixed that in autopts overlay: https://github.com/intel/auto-pts/pull/826

**Pull request closed without merging**
