### PR TITLE
Support for measuring timer behaviour with external tool

### PR DESCRIPTION
**Pull request by edersondisouza**
Modifies timer_behavior test to that `jitter_drift.c` tests also toggle a GPIO, that can be connected to an external tool (such as a logic analyzer) to measure timer behaviour.
A pytest test is also added to get the data from the external tool and assert some measurements.
Finally, an example of how to interface with an external tool to get the data is provided. Note that the external tool can change, as long an interface to get the data is there.

### CODE REVIEW

**Review by andyross — DISMISSED** [review]
This looks nifty.  Any interesting results?

**Review by teburd — COMMENTED** [review]
This looks good to me, would be good to get a device tree person to look over the bindings and such

**Comment by edersondisouza** [comment]
v2:
 - Use `logger.info` instead of `print` on pytest;
 - Added a `requirements-saleae.txt` (and a mention of it on README) for the saleae interface module;
 - Moved `config` fixture to `conftest.py`.

**Comment by edersondisouza** [comment]
> This looks nifty. Any interesting results?

Not really - unless you count me finding out yet again that different clocks run at different speeds. I want to eventually test this with a logic analyzer which support external clocks.

**Review by gchwier — APPROVED** [review]
Reviewed python/pytest scripts, it looks good.

**Review by teburd — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
