### PR TITLE
samples: drivers: led_pwm: Update sample to remove usage of DT_INST

### PR DESCRIPTION
**Pull request by benjaminbjornsson**
Update sample to use DT_COMPAT_GET_ANY_STATUS_OKAY in order to remove
usage of DT_INST.

Signed-off-by: Benjamin Björnsson <benjamin.bjornsson@gmail.com>

### CODE REVIEW

**Review by Mani-Sadhasivam — COMMENTED** [review]
What about `device_get_binding`?

**Comment by benjaminbjornsson** [comment]
> What about `device_get_binding`?

Good point, I've updated.

**Comment by benjaminbjornsson** [comment]
@Mani-Sadhasivam when looking at this sample I get the feeling that the led API should be extended to support getting the number of leds? All API functions except `write_channels` takes the `led` argument but there's no explicit way of getting what range this argument supports.

**Review by galak — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
You need to update sample.yaml to match the output change you made, this will fix CI failure:

```
diff --git a/samples/drivers/led_pwm/sample.yaml b/samples/drivers/led_pwm/sample.yaml
index c6beedfa8d..fe9a3845ff 100644
--- a/samples/drivers/led_pwm/sample.yaml
+++ b/samples/drivers/led_pwm/sample.yaml
@@ -13,7 +13,6 @@ tests:
       type: multi_line
       ordered: true
       regex:
-        - "Found device \\S+"
         - "Testing LED \\d+"
         - "Turned on"
         - "Turned off"

```

**Review by galak — APPROVED** [review]

**Comment by benjaminbjornsson** [comment]
> You need to update sample.yaml to match the output change you made, this will fix CI failure:
> 
> ```
> diff --git a/samples/drivers/led_pwm/sample.yaml b/samples/drivers/led_pwm/sample.yaml
> index c6beedfa8d..fe9a3845ff 100644
> --- a/samples/drivers/led_pwm/sample.yaml
> +++ b/samples/drivers/led_pwm/sample.yaml
> @@ -13,7 +13,6 @@ tests:
>        type: multi_line
>        ordered: true
>        regex:
> -        - "Found device \\S+"
>          - "Testing LED \\d+"
>          - "Turned on"
>          - "Turned off"
> ```

Thanks!

**Review by Mani-Sadhasivam — APPROVED** [review]

**Pull request merged**
