### PR TITLE
[Backport v2.7-branch] Drivers: Flash: stm32: G0 dual bank handling, G0 error check and CFGBSY check fixes

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 9e852644a82140b61c4d01e9021c99f9c85a3e15~6..9e852644a82140b61c4d01e9021c99f9c85a3e15 from #37480

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/37389

### CODE REVIEW

**Review by ycsin — APPROVED** [review]

**Comment by cfriedt** [comment]
Associated issue is https://github.com/zephyrproject-rtos/zephyr/issues/37389

**Review by ABOSTM — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Comment by ycsin** [comment]
@erwango could you review this?

**Comment by erwango** [comment]
> @erwango could you review this?

PR already has 3 approvals, there's nothing blocking it from being merged.

**Comment by ycsin** [comment]
> > @erwango could you review this?
> 
> PR already has 3 approvals, there's nothing blocking it from being merged.

My impression is that backport has a bit different requirement, lets see what @cfriedt says

**Comment by cfriedt** [comment]
@erwango, @ycsin - I've been told a couple of times that LTS backports require maintainer approval (probably true for all backports).

**Comment by erwango** [comment]
> @erwango, @ycsin - I've been told a couple of times that LTS backports require maintainer approval (probably true for all backports).

Thanks @cfriedt, somehow I've missed this info or I forgot about it.

**Review by erwango — APPROVED** [review]

**Pull request merged**
