### PR TITLE
rework extern "C" handling for headers not otherwise bundled

### PR DESCRIPTION
**Pull request by pabigot**
This collects more changes necessary for closing issue #17997.

### CODE REVIEW

**Comment by pabigot** [comment]
Note that the shippable failure is due to #18198 and is unrelated to this PR.

**Review by carlescufi — APPROVED** [review]
LGTM. All the changes are similar to the ones in the rest of C++ PRs.

**Comment by carlescufi** [comment]
@galak @nashif please take a look
@pabigot can you check CI?

**Comment by pabigot** [comment]
@carlescufi CI isn't going to pass until there's a new toolchain with zephyrproject-rtos/sdk-ng#96 verified and merged.  The same build failure happens on master; I don't know why it wasn't discovered during toolchain validation.

**Comment by pabigot** [comment]
CI now passes.

**Review by ioannisg — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]

**Pull request merged**
