### PR TITLE
kernel: Improve tick <-> ms conversion.

### PR DESCRIPTION
**Pull request by pizi-nordic**
The kernel incorrectly assumed, that system timer frequency is always
divisible without remainder by couple "natural" tick rates (like 100).
As result on some SoCs, time calculations was not correct, producing
strange effects (invalid sleep times, incorrect k_uptime_get() and so on).

This commit enables accurate, but costly (using 64-bit math) tick <-> ms
conversion if the selected tick interval is not exact due to hardware
limitations.

Signed-off-by: Piotr Zięcik <piotr.ziecik@nordicsemi.no>

Note: This PR solves the described problem only for non-tickless kernel. Patches for tickless mode will follow.

### CODE REVIEW

**Comment by pizi-nordic** [comment]
CC: @carlescufi

**Review by andyross — CHANGES_REQUESTED** [review]
So, the hard-coded tick list fix looks correct and has value.  The rest seems like sorta needless churn, though.  You're renaming things and moving them around, mostly to inline a function that doesn't seem to need to be inlined.

If you want to do refactoring and cleanup, can you do that in a separate patch from the bugfix?

**Comment by pizi-nordic** [comment]
@andyross: I put every logic change in separate commit. I hope that now this PR is more readable.

**Comment by pizi-nordic** [comment]
I hoped that I would be able to separate tickless and non-tickless changes, but at the moment this is not possible, as tickless build is broken with these patches applied. I have added "DNM" label until this will be resolved.

**Review by andyross — APPROVED** [review]
I see the failures, but I'm sure those are straightforward.  I like the patch structure much better, thanks.

**Comment by nashif** [comment]
SYS_CLOCK_TICKS_PER_SEC=0 means we do not have a timer, it is a valid option yes. I do not remember the details now, but intention was to support configurations without a clock. This is also how we set SYS_CLOCK_EXISTS option which is then used in the scheduler.

**Comment by pizi-nordic** [comment]
@nashif: Thank you!

**Review by nashif — APPROVED** [review]

**Pull request merged**
