### PR TITLE
net: rpl: Remove the deprecated code

### PR DESCRIPTION
**Pull request by jukkar**
The RPL was deprecated earlier so remove it by this commit.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by pfalcon** [comment]
Wait, did we really want to *remove* this for 1.14, not just deprecate?

**Comment by tbursztyka** [comment]
We deprecated it early enough to remove it for 1.14

**Review by tbursztyka — APPROVED** [review]

**Comment by jukkar** [comment]
Removed also RPL texts from documentation

**Review by pfalcon — APPROVED** [review]

**Review by dbkinder — APPROVED** [review]
doc changes LGTM

**Review by rveerama1 — APPROVED** [review]

**Comment by lgl88911** [comment]
@nashif @jukkar At last night I pull code and can't find RPL Code. I find the pr remove RPL. but I don't kown remove it for what reason. Where can I get more information about it. Thanks !

**Comment by pfalcon** [comment]
@lgl88911 : It followed standard open-source community-driven process: a request was posted on the developers' mailing list calling for a (new) maintainer for RPL code and disclosing that otherwise code would be removed, because it initially was imported from another project, and now misses various bugfixes, etc. There was enough wait for responses, there were some responses, but eventually people didn't follow up with maintainership. In the end, after a few months, code was removed.

If you would like to stay in loop and influence Zephyr development and progress better, please be sure to subscribe to the Zephyr "devel" mailing list: https://lists.zephyrproject.org/g/devel

**Comment by lgl88911** [comment]
@pfalcon Thanks for your reply. Remove RPL from zephyr, That's a regrets.

**Comment by abbcdfin** [comment]
@pfalcon Thanks for the explanation. Is there any chance to bring back the RPL in case somebody could take the responsibility to maintain the code?

**Comment by jukkar** [comment]
> Is there any chance to bring back the RPL in case somebody could take the responsibility to maintain the code?

Yes, it is possible to bring back RPL support if someone sends a PR and is willing to take responsibility of maintaining it.

**Comment by abbcdfin** [comment]
@jukkar Got it, thanks very much. I am kind of new to Zephyr dev community. Do you think it would be helpful to bring it back or actually not many people are using it? We are using Zephyr and RPL in a project and probably will keep using it. But if RPL is not required by the mainstream, we can probably use our own branch to maintain it.

**Comment by jukkar** [comment]
I do not know about the usage of RPL, you could ask this in the mailing list as it has wider audience.

**Pull request merged**
