### PR TITLE
soc/intel_adsp: Use the cAVS IDC driver pervasively, remove IPM

### PR DESCRIPTION
**Pull request by andyross**
This is a series which continues the now-merged cleanup pass, enabling the new/unified IDC driver as the only sched_ipi() implementation for all platforms, doing a little more cleanup, and fixing a bug on APL that has to do with a startup latency races.

Note that this is ready for review, but not merge yet.  We need validation of the fix on APL with SOF still, and consensus about the mechanism (I'm like 84% sure myself -- it sure makes more sense than previous theories).

Also there are at least two spots where this series makes a change and then invalidates it by removing the relevant code.  That's silly and I should squash those changes.  It's left in currently for better history of the understanding.

### CODE REVIEW

**Comment by andyross** [comment]
(Stick a DNM on it for now pending squash)

**Comment by andyross** [comment]
Remove DNM and reorganize things a bit to reflect what we now believe to be the truth of the matter (SOF is masking interrupts somewhere and needs them unmasked at core startup, and cAVS 1.5 hardware needs a delay before the IDC interrupt is delivered)

**Comment by kv2019i** [comment]
@andyross @lyakh  Test now passes on cAVS1.5 with multicore SOF test case. Here's a FW trace bit (sof-logger):

```
[     1210117.347748] (      160499.687500) c0 ipc                  src/ipc/ipc3/handler.c:1576 INFO ipc: new cmd 0x40070000
[     1210132.243580] (          14.895833) c0 ipc                  src/ipc/ipc3/handler.c:693  INFO ipc: pm core mask 0x3 -> enable
[     1210718.806057] (         586.562500) c1 zll-schedule       src/schedule/zephyr_ll.c:504  ERROR zephyr_ll_scheduler_init(): unsupported domain 2
[     1210807.035220] (          88.229164) c1 idc                           src/idc/idc.c:351  INFO idc_init()
[     1210897.503967] (          90.468750) c0 ipc                  src/ipc/ipc3/handler.c:1576 INFO ipc: new cmd 0x30010000
[     1215644.430861] (        4746.926758) c1 component             src/ipc/ipc3/helper.c:296  INFO comp new dai <c2b00d27-ffbc-4150-a51a-245c79c5e54b> type 2 id 1.2
[     1215707.503775] (          63.072914) c1 power              ../cavs/lib/pm_runtime.c:151  INFO dis-ssp-clk-gating index 0 CLKCTL 00100002
[     1215721.514192] (          14.010416) c1 dai                           src/lib/dai.c:164  INFO dai_get type 1 index 0 new sref 1
[     1215738.493358] (          16.979166) c1 power              ../cavs/lib/pm_runtime.c:279  INFO dis-dwdma-clk-gating index 0 CLKCTL 04100002
[     1215871.930852] (         133.437500) c1 dma                           src/lib/dma.c:121  INFO dma_get() ID 0 sref = 1 busy channels 0
[     1216251.982920] (         380.052063) c0 ipc                  src/ipc/ipc3/handler.c:1576 INFO ipc: new cmd 0x80010000
[     1216286.982919] (          35.000000) c0 ipc                  src/ipc/ipc3/handler.c:569  INFO ipc: dai 1.0 -> config
```

c0/1 is the core emitting the trace. The core enable was reporting errors before with the PR.

**Review by kv2019i — APPROVED** [review]
Looks good @andyross !

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
