### PR TITLE
remove custom k_thread_abort() for Cortex-R, add test, fix native_posix issue

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Cortex-R had a custom `k_thread_abort()` implementation which skips any scheduler calls if we're in an interrupt handler, because this happens anyway on the way out of the interrupt. This is true for all arches, so just fold this into the default version.

In doing this, I found that on `native_posix` calling `k_thread_abort()` in an ISR was terminating the ISR immediately, if the interrupted thread is the one being killed. Simple fix, fortunately.

I added a test scenario to specifically show that aborting an interrupted thread in an ISR works as expected.

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Looks great here

**Comment by andrewboie** [comment]
Note: there is some inconsistency in how arches report `arch_is_in_isr()` when taking a fatal error: https://github.com/zephyrproject-rtos/zephyr/issues/21923#issuecomment-674228625

Despite this, we have a lot of tests which ensure the right thing happens (most in `tests/kernel/fatal`) and this PR doesn't break any of that. AFAICT, those arches which do report `arch_is_in_isr()` in `k_sys_fatal_error_handler()`, do the scheduling calls on the way out of exceptions as well (which is debatable whether we really want this once recoverable exceptions become more common)

**Review by stephanosio — APPROVED** [review]
Cortex-R changes look ok to me.

**Review by aescolar — CHANGES_REQUESTED** [review]
Good catch about the posix arch issue.
But shouldnt the change there be like this:
```diff
diff --git a/arch/posix/core/posix_core.c b/arch/posix/core/posix_core.c
index 7727a37853..b44d42856e 100644
--- a/arch/posix/core/posix_core.c
+++ b/arch/posix/core/posix_core.c
@@ -499,10 +499,6 @@ void z_impl_k_thread_abort(k_tid_t thread)
        z_thread_single_abort(thread);
        z_thread_monitor_exit(thread);
 
-       if (arch_is_in_isr()) {
-               return;
-       }
-
        if (_current == thread) {
                if (tstatus->aborted == 0) { /* LCOV_EXCL_BR_LINE */
                        tstatus->aborted = 1;
@@ -520,6 +516,10 @@ void z_impl_k_thread_abort(k_tid_t thread)
                        thread_idx,
                        __func__);
 
+               if (arch_is_in_isr()) {
+                       return;
+               }
+
                (void)z_swap_irqlock(key);
                CODE_UNREACHABLE; /* LCOV_EXCL_LINE */
        }
```
So the thread is marked as aborted, and will be removed in the swap in the tail of the interrupt.
Otherwise unless k_thread_abort() would be called again, the underlying pthread would be left lingering  (not the worst thing that can happen, but not the desired behaviour).

**Comment by andrewboie** [comment]
@aescolar thanks for reviewing, I made your suggested change.

**Review by aescolar — APPROVED** [review]

**Pull request merged**
