### PR TITLE
ip: route: disable LL address check when using dummy L2

### PR DESCRIPTION
**Pull request by vaussard**
The dummy L2 does not setup the link layer address. Do not check the source and destination link layer addresses when routing packets otherwise packet routing will not work when using a dummy L2.

Note: this is maybe not the best approach, as this will disable the check for all interfaces, including non-dummy L2. Would it be a way to check the source/destination interface directly?

### CODE REVIEW

**Comment by rveerama1** [comment]
@vaussard please check this https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/net/6lo/src/main.c#L198. I don't know whether it solves your problem or not, please take a look those tests.

**Comment by jukkar** [comment]
AFAIK the dummy_l2 is only used when testing things (under tests/net/*). What test is failing so that we need to do this?

**Comment by jukkar** [comment]
> I am using a SLIP interface without TAP.

Ok, that is certainly possible but you are now the first one using TUN device :)

**Review by jukkar — CHANGES_REQUESTED** [review]

**Comment by jukkar** [comment]
recheck

**Review by jukkar — APPROVED** [review]

**Comment by vaussard** [comment]
Hi @jukkar, thank you for taking care of fixing this PR. Sorry I was too busy to promptly address your comment.

**Comment by jukkar** [comment]
No worries, I went through old PRs and started fixing some that looked most useful to have.

**Pull request merged**
