### PR TITLE
west/commands/sign: Use CONFIG_MCUBOOT_SIGNATURE_KEY_FILE when provided 

### PR DESCRIPTION
**Pull request by de-nordic**
The commit adds change to signt.py that will pick signing key
from CONFIG_MCUBOOT_SIGNATURE_KEY_FILE, if such option is provided;
if the --key command line option is provided to imgtool, then the
command line will override the .config selection.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
Why this PR? The point of the kconfig option is to allow the build system to automatically call `west sign` from `cmake/mcuboot.cmake`. If the user is using `west sign` manually, they should be able to use whatever keys they want and not get a warning IMO.

Is this causing problems for someone? Can you explain the motivation a bit more than is already done in the PR description?

**Comment by de-nordic** [comment]
> 
> Why this PR? The point of the kconfig option is to allow the build system to automatically call `west sign` from `cmake/mcuboot.cmake`. If the user is using `west sign` manually, they should be able to use whatever keys they want and not get a warning IMO.
> 

The warning will only appear if the key in .config is provided and when it is different than the one that is given to the command line. It happened to me some time ago that I have been trying to sign with different key then the one I should use, causing app to not boot. The warning is just for those who provide `--key`, to the tool, that they have been previously using different key, to let them know.

>
> Is this causing problems for someone? Can you explain the motivation a bit more than is already done in the PR description?

Not really a problem, inconvenience rather: when I have started with Zephyr my first app to build was smp_svr and I have found the option and tried to use it to sign the software but it did not work; so I have started using `--key` option and have used it since.

But the option is there and it is available in Zephyr when invoking mkconfig on any app that works with mcuboot. We can either block it from being visible or use it; I have decided to use it.

Now you may provide key in overaly or set it via `-D` or set/override it with `--key`.

**Comment by de-nordic** [comment]
Actually the documentation here: https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_MCUBOOT_SIGNATURE_KEY_FILE.html#cmdoption-arg-CONFIG_MCUBOOT_SIGNATURE_KEY_FILE says that this is how does `west sign` supposed to behave (except for the warning).

Seems that this PR becomes bugfix.

**Comment by de-nordic** [comment]
OK seems that I have missed the point of the option. I do agree there is no reason for the change.

**Pull request closed without merging**
