### PR TITLE
drivers: sensor: Store sensor trigger as a pointer - batch 3

### LINKED ISSUE #55130: Drivers: Sensor: Store `struct sensor_trigger` as a const pointer for CONTAINER_OF usage.
**Is your enhancement proposal related to a problem? Please describe.**
Currently the `const struct sensor_trigger *` passed to all sensor drivers with the `sensor_trigger_set_t` are de-referenced and saved as a copy instead of the const pointer, [ex: adxl372](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/adxl372/adxl372_trigger.c#L114). Then when an event occurs either the pointer to the [dev_data copy of sensor_trigger](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/adxl372/adxl372_trigger.c#L47) is passed or a [local stack copy](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/bmi160/bmi160_trigger.c#L20) is made.

**Describe the solution you'd like**
Instead of making a copy of the user provided `const struct sensor_trigger *` change all drivers to save the const pointer directly and pass it to the `sensor_trigger_handler_t` function when an event occurs.
This allows the usage of **CONTAINER_OF** by the callee to retrieve a context pointer if they choose to embedded the sensor_trigger in a higher struct.

**Describe alternatives you've considered**
No change and instead users continue to use global variables for callback access to user data.

### PR DESCRIPTION
**Pull request by MaureenHelm**
Fixes the last batch of sensor drivers to store the user-supplied sensor
trigger as a pointer rather than a copy. This enables the trigger
handler to use CONTAINER_OF to retrieve a context pointer when the
trigger is embedded in a larger struct.

Signed-off-by: Maureen Helm <maureen.helm@intel.com>

Fixes #55130 (this is the last batch after #55566 and #56123)

cc: @anthony32086 @huhebo

### CODE REVIEW

**Review by yperess — COMMENTED** [review]
Do we need to document that you can no longer use a sensor trigger struct that's on the stack?

**Comment by henrikbrixandersen** [comment]
> Do we need to document that you can no longer use a sensor trigger struct that's on the stack?

Already done in 2da26be77b0a51e7f7cf4c1a996b621f204350d5

**Review by henrikbrixandersen — APPROVED** [review]
Thank you, @MaureenHelm.

**Review by teburd — APPROVED** [review]

**Review by yperess — APPROVED** [review]

**Comment by teburd** [comment]
Fixes #11666 as well I believe

**Pull request merged**
