### PR TITLE
drivers: flash: nrf: Avoid locking when not threaded

### PR DESCRIPTION
**Pull request by carlescufi**
When using CONFIG_MULTITHREADING=n, the semaphore primitives are
non-functional and useless. Remove their usage when this option is
enabled.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
@cvinayak thanks!

**Comment by carlescufi** [comment]
@nvlsianpu maybe this will help remove the symptoms you were seeing in the bootloader

**Comment by carlescufi** [comment]
@nvlsianpu @cvinayak with this patch `_Swap()` and `k_sem_*` disappear from the MCUboot image, as they should.

**Pull request merged**
