### PR TITLE
SPARC: Add support for C++ exceptions

### PR DESCRIPTION
**Pull request by ghost**
This implements the SPARC run-time support needed for C++ exceptions. Also enables the `qemu_leon3` board in the test case `cpp.libcxx.exceptions` to exercise the SPARC support.

It is intended to solve the SPARC part of #32448 .

### CODE REVIEW

**Comment by stephanosio** [comment]
cc @yashi @ntavish

**Comment by martin-aberg** [comment]
The `cpp.libcxx.exceptions` test PASS in buildkite/zephyr for qemu_leon3.
I have also verified the patch by running the test case on hardware and in another simulator (TSIM).

**Review by tejlmand — APPROVED** [review]
Confirm that this passes on qemu_leon3.
Someone else must confirm on real hw.

**Comment by galak** [comment]
@martin-aberg do you mind rebasing this since I merged the 64-bit C++ PR first.

**Comment by martin-aberg** [comment]
@galak OK. It is rebased now. Thanks.

**Review by galak — APPROVED** [review]

**Pull request merged**
