### PR TITLE
fix tests scenarios failing with undefined reference to `z_impl_sys_rand_get`

### LINKED ISSUE #82344: mk64f12: test failing with undefined reference to 'z_impl_sys_rand_get'
**Describe the bug**
Tests failing with undefined reference to `z_impl_sys_rand_get` for boards `hexiwear/mk64f12` and `frdm_k64f/mk64f12`. It looks like ~these boards lack of RNG driver and~ the test scenarios are not enabling any test RNG.

**To Reproduce**
```
west build -p -b hexiwear/mk64f12 tests/subsys/mgmt/mcumgr/os_mgmt_info -T mgmt.mcumgr.os.info.bt
west build -p -b frdm_k64f/mk64f12 samples/bluetooth/peripheral_ht -T sample.bluetooth.peripheral_ht.frdm_kw41z_shield
west build -p -b frdm_k64f/mk64f12 samples/bluetooth/peripheral_hr -T sample.bluetooth.peripheral_hr.frdm_kw41z_shield
```

**Expected behavior**
All tests above can build

**Impact**
Blocking CI of https://github.com/zephyrproject-rtos/zephyr/pull/82195 with unrelated failure

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/pull/82195/checks?check_run_id=33638058374
Example
```
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map /__w/zephyr/zephyr/twister-out/frdm_k64f_mk64f12/samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr.frdm_kw41z_shield/zephyr/zephyr_pre0.map 
: && ccache /opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc  -gdwarf-4 -gdwarf-4 zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr_pre0.elf  zephyr/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map=/__w/zephyr/zephyr/twister-out/frdm_k64f_mk64f12/samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr.frdm_kw41z_shield/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/arm/core/libarch__arm__core.a  zephyr/arch/arch/arm/core/cortex_m/libarch__arm__core__cortex_m.a  zephyr/arch/arch/arm/core/mpu/libarch__arm__core__mpu.a  zephyr/lib/libc/picolibc/liblib__libc__picolibc.a  zephyr/lib/libc/common/liblib__libc__common.a  zephyr/lib/net_buf/liblib__net_buf.a  zephyr/subsys/bluetooth/common/libsubsys__bluetooth__common.a  zephyr/subsys/bluetooth/host/libsubsys__bluetooth__host.a  zephyr/subsys/bluetooth/crypto/libsubsys__bluetooth__crypto.a  zephyr/drivers/bluetooth/libdrivers__bluetooth.a  zephyr/drivers/clock_control/libdrivers__clock_control.a  zephyr/drivers/console/libdrivers__console.a  zephyr/drivers/gpio/libdrivers__gpio.a  zephyr/drivers/pinctrl/libdrivers__pinctrl.a  zephyr/drivers/serial/libdrivers__serial.a  zephyr/drivers/timer/libdrivers__timer.a  modules/hal_nxp/hal_nxp/lib..__modules__hal__nxp.a  modules/mbedtls/libmbedTLSBase.a  modules/mbedtls/libmbedTLSCrypto.a  modules/mbedtls/libmbedTLSX509.a  modules/mbedtls/libmodules__mbedtls.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  -L/__w/zephyr/zephyr/twister-out/frdm_k64f_mk64f12/samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr.frdm_kw41z_shield/zephyr  zephyr/arch/common/libisr_tables.a  modules/mbedtls/libmbedTLSBase.a  modules/mbedtls/libmbedTLSCrypto.a  modules/mbedtls/libmbedTLSX509.a  -Wl,--fatal-warnings  -mcpu=cortex-m4  -mthumb  -mabi=aapcs  -mfp16-format=ieee  -mtp=soft  -fuse-ld=bfd  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn  -Wl,-no-pie  -specs=picolibc.specs  -DPICOLIBC_LONG_LONG_PRINTF_SCANF -L"/opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/thumb/v7e-m/nofp" -lc -lgcc && cd /__w/zephyr/zephyr/twister-out/frdm_k64f_mk64f12/samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr.frdm_kw41z_shield/zephyr && /usr/bin/cmake -E true
/opt/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: modules/mbedtls/libmbedTLSBase.a(zephyr_entropy.c.obj): in function `sys_rand_get':
/__w/zephyr/zephyr/twister-out/frdm_k64f_mk64f12/samples/bluetooth/peripheral_hr/sample.bluetooth.peripheral_hr.frdm_kw41z_shield/zephyr/include/generated/zephyr/syscalls/random.h:37: undefined reference to `z_impl_sys_rand_get'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK 0.16.8
 - Commit SHA or Version used: 6c7b38f5fa1cb4d382a030762efbcfe587ea974d

**Additional context**
Seems like a solution would be to enable `CONFIG_TEST_RANDOM_GENERATOR=y` either for the boards or in the test scenarios.

### PR DESCRIPTION
**Pull request by manuargue**
Some tests are failing with undefined reference to `z_impl_sys_rand_get` for boards `hexiwear/mk64f12` and `frdm_k64f/mk64f12`. ~It looks like these boards lack of RNG driver and and the test scenarios are not enabling any test RNG, so enable it.~

Not sure about side effects, so I'm open to better suggestions -I'm just trying to unblock unrelated CI failures in another pr.

Fixes #82344

### CODE REVIEW

**Review by Thalley — COMMENTED** [review]
Not sure about this change. 

The documentation for the option states:
```
	  This option is intended to be selected only by application-level
	  configurations (e.g. in tests and samples) to indicate that the
	  application is allowed to run with a random number generator that is not
	  truly random. Board-level configurations must not select this option
	  unless the sole purpose of the board is testing (e.g. QEMU emulation
	  boards).
```

Not sure if we can consider these cases here tests. 

Furthermore, the option is hardened, which will give a build warning. That doesn't like something we really want to have in samples. 

An alternative to this PR is to remove the boards that do not support a random generator for applications that require a random generator.

**Comment by manuargue** [comment]
>An alternative to this PR is to remove the boards that do not support a random generator for applications that require a random generator.

my bad, it seems that is possible to enable `CONFIG_ENTROPY_GENERATOR=y` for these SoCs -which I'm not familiar with :)

**Comment by Thalley** [comment]
> > An alternative to this PR is to remove the boards that do not support a random generator for applications that require a random generator.
> 
> my bad, it seems that is possible to enable `CONFIG_ENTROPY_GENERATOR=y` for these SoCs -which I'm not familiar with :)

Doing a search for `CONFIG_ENTROPY_GENERATOR=y` show that it's more common to enable this in the `prj.conf` files, rather than in board files. 

I'm not sure which way is "correct"

**Comment by manuargue** [comment]
> Doing a search for CONFIG_ENTROPY_GENERATOR=y show that it's more common to enable this in the prj.conf files, rather than in board files.

I based on https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/peripheral_ht/boards/frdm_rw612.conf#L2. I'm not familiar enough with the tests to enable it at prj.conf, so I'll let others with better knowledge on this comment.

**Comment by jhedberg** [comment]
I'd assume it's the enabling of Bluetooth that brings this dependency. It might make more sense to do this as a select statement in the HCI driver that this board uses, similar to what was done for ESP32 here: #82198

**Comment by manuargue** [comment]
> I'd assume it's the enabling of Bluetooth that brings this dependency. It might make more sense to do this as a select statement in the HCI driver that this board uses, similar to what was done for ESP32 here: #82198

It's using the `BT_H4`/`zephyr,bt-hci-uart` generic driver, not an specific NXP implementation.

I see from https://github.com/zephyrproject-rtos/zephyr/pull/79931/files three other different approaches to this same problem:
1. Select `CONFIG_ENTROPY_GENERATOR=y` from test/sample prj.conf
2. Select `CONFIG_ENTROPY_GENERATOR=y` from the board's sample/test conf overlay
3. Set `CONFIG_ENTROPY_GENERATOR` default to `y` in the board defconfig when `BT=y`

If the dependency comes from the `BT_H4` driver, then I agree with you to select it from there. Otherwise, (3) may be a better fit.

**Review by hakehuang — APPROVED** [review]

**Comment by jhedberg** [comment]
Right now this seems to be fixing this on a per-app basis, which would then leave all other Bluetooth apps broken with this board. So out of the various alternatives being discussed that's probably the worst option.

**Comment by manuargue** [comment]
> Could you try if the same issue gets fixed by #82363? If so, then we should probably move to that instead of selecting `ENTROPY_GENERATOR` separately for each board or HCI driver.

@jhedberg agree, it fixes the issue indeed, thanks! Btw you may want to also cleanup all the tests/samples overlays that are selecting `ENTROPY_GENERATOR` for specific boards after your change.

**Comment by manuargue** [comment]
moved to https://github.com/zephyrproject-rtos/zephyr/pull/82363

**Pull request closed without merging**
