### PR TITLE
drivers/sensor: lps22hh: Enable fetching individual sensor channels

### PR DESCRIPTION
**Pull request by cbraissant**
Add the possibility to fetch specific sensor channels independently, either pressure data with SENSOR_CHAN_PRESS or temperature data with SENSOR_CHAN_AMBIENT_TEMP. Additionally, the option to fetch both channels simultaneously remains available using SENSOR_CHAN_ALL, thus not breaking any samples.

### CODE REVIEW

**Review by avisconti — CHANGES_REQUESTED** [review]
LGTM, but pls just squash the two commits together. Thanks

**Comment by MaureenHelm** [comment]
Please rebase

**Review by avisconti — DISMISSED** [review]

**Comment by avisconti** [comment]
Please rebase to latest HEAD and solve the conflict.

**Comment by cbraissant** [comment]
Hi Armando, thanks for taking care of this pull request.
As you might have seen, it's my first one, and I'm not totally confident on how to process it, especially for the rebase.
If there is any mistake from my part, I apologize for it, and would appreciate some guidance. 
Thanks a lot

**Review by avisconti — APPROVED** [review]

**Comment by avisconti** [comment]
> Hi Armando, thanks for taking care of this pull request. As you might have seen, it's my first one, and I'm not totally confident on how to process it, especially for the rebase. If there is any mistake from my part, I apologize for it, and would appreciate some guidance. Thanks a lot

No problem, we need to grow a big community team! And you did great, thanks!

**Review by MaureenHelm — APPROVED** [review]

**Comment by avisconti** [comment]
not sure why CI has not completed yet

**Comment by MaureenHelm** [comment]
> not sure why CI has not completed yet

Try rebasing to kick CI

**Comment by avisconti** [comment]
> > not sure why CI has not completed yet
> 
> Try rebasing to kick CI

@cbraissant can you rebase and repush just to retrigger CI? Thanks

**Comment by cbraissant** [comment]
Hi @avisconti and @MaureenHelm,
I've rebased and repushed the code, let me know if there is anything I can do!

**Review by ubieda — APPROVED** [review]

**Comment by ubieda** [comment]
Your PR has all the green checks. Unless someone requests changes: It'll be merged soon 🙂

**Pull request merged**
