### PR TITLE
USB: Fixes for stm32 driver

### PR DESCRIPTION
**Pull request by finikorg**
Cherry picked from another PR

### CODE REVIEW

**Review by ydamigos — COMMENTED** [review]
@finikorg We should check if ep_state isn't null but I don't think that e42d78fde2ebf24c8ccfc680553086c52edbf17f fixes #13560.

**Comment by finikorg** [comment]
> @finikorg We should check if ep_state isn't null but I don't think that [e42d78f](https://github.com/zephyrproject-rtos/zephyr/commit/e42d78fde2ebf24c8ccfc680553086c52edbf17f) fixes #13560.

There is another fix also for that Issue. This exact patch fixes crash mentioned there.

**Review by ydamigos — APPROVED** [review]
Looks fine.

**Comment by galak** [comment]
If you desire this fix in 1.14, please open or associate this PR with an Issue.

**Comment by carlescufi** [comment]
@finikorg do we need this for 1.14? What PR is this cherry-picked from?

**Comment by finikorg** [comment]
cherr-picked from harness PR #14874

**Review by jfischer-no — APPROVED** [review]

**Pull request merged**
