### PR TITLE
Add NXP usb device khci controller driver

### PR DESCRIPTION
**Pull request by MarkWangChinese**
Add NXP usb device khci controller driver, it is one shim of the NXP SDK kinetis USB device controller driver. The default kinetis device controller driver use the usb_dc_kinetis.c, user can select to use this driver by setting CONFIG_USB_KINETIS=0 and setting CONFIG_USB_DC_NXP_KHCI=1

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
The change for 'button_1' should not be in this PR, please pull it out and submit it as its own PR.

**Review by galak — CHANGES_REQUESTED** [review]
Is this trying to be an alternate implementation to what is already in the tree?  If so we need to understand why we need a different implementation, got agreement from the parties involved (in this case @jfischer-phytec-iot) on what the plan forward is.

**Comment by MarkWangChinese** [comment]
> Is this trying to be an alternate implementation to what is already in the tree? If so we need to understand why we need a different implementation, got agreement from the parties involved (in this case @jfischer-phytec-iot) on what the plan forward is.

Hi @galak,
NXP has four types device controllers: khci, ehci, ip3511fs and ip3511hs. The NXP SDK ehci controller driver has been upstreamed to the Zephyr master. I will upstream ip3511fs and ip3511hs controller drivers later.
I am trying to upstream SDK khci controller currently. The USB khci controller driver is enabled yet in Zephyr, it has no relation with the NXP SDK khci controller driver. I plan to upstream the NXP SDK khci controller driver to Zephyr too.
And I think we are more familiar with the this controller, and I think the SDK khci driver's maturity and quality have been varified by many customer products and the compliance test.

**Comment by jfischer-phytec-iot** [comment]
>And I think we are more familiar with the this controller, and I think the SDK khci driver's maturity and quality have been varified by many customer products and the compliance test.

I am also very familiar with kinetis usb device controller. I prefer the native implementation and since we have the native driver I do not see the benefits of the shim driver.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Native implementation of the driver already exists.

**Comment by MarkWangChinese** [comment]
> > And I think we are more familiar with the this controller, and I think the SDK khci driver's maturity and quality have been varified by many customer products and the compliance test.
> 
> I am also very familiar with kinetis usb device controller. I prefer the native implementation and since we have the native driver I do not see the benefits of the shim driver.

Hi @jfischer-phytec-iot , I sent one e-mail to you and Emeltchenko Andrei to talk about putting the NXP controller driver to zephyr in 2018-12-3, Andrei agreed add the NXP SDK KHCI shim controller driver as an alternative, and you are in the mail list too. We do this pull-request based on the agreement.

**Comment by jfischer-phytec-iot** [comment]
> > > And I think we are more familiar with the this controller, and I think the SDK khci driver's maturity and quality have been varified by many customer products and the compliance test.
> > 
> > 
> > I am also very familiar with kinetis usb device controller. I prefer the native implementation and since we have the native driver I do not see the benefits of the shim driver.
> 
> Hi @jfischer-phytec-iot , I sent one e-mail to you and Emeltchenko Andrei to talk about putting the NXP controller driver to zephyr in 2018-12-3, Andrei agreed add the NXP SDK KHCI shim controller driver as an alternative, and you are in the mail list too. We do this pull-request based on the agreement.

Based on experiences with the (shim) drivers in the last months and the effort of maintaining and testing the drivers and stack I am against having two drivers for the same hardware and I am against shim drivers for the usb stack.

(About your e-mail 2018-12-3, I have not seen a question mark in your email, just statements.)

**Comment by finikorg** [comment]
Personally I prefer native drivers but I do not have many objections to have alternative driver if it improve something or supports more HW boards.

**Comment by MarkWangChinese** [comment]
> > > > And I think we are more familiar with the this controller, and I think the SDK khci driver's maturity and quality have been varified by many customer products and the compliance test.
> > > 
> > > 
> > > I am also very familiar with kinetis usb device controller. I prefer the native implementation and since we have the native driver I do not see the benefits of the shim driver.
> > 
> > 
> > Hi @jfischer-phytec-iot , I sent one e-mail to you and Emeltchenko Andrei to talk about putting the NXP controller driver to zephyr in 2018-12-3, Andrei agreed add the NXP SDK KHCI shim controller driver as an alternative, and you are in the mail list too. We do this pull-request based on the agreement.
> 
> Based on experiences with the (shim) drivers in the last months and the effort of maintaining and testing the drivers and stack I am against having two drivers for the same hardware and I am against shim drivers for the usb stack.
> 
> (About your e-mail 2018-12-3, I have not seen a question mark in your email, just statements.)

Hi @jfischer-phytec-iot , I summary the follow issues that I think the native kinetis usb device controller driver has, could you please check them? If I am wrong, please let me know. All these issues have been handled by the NXP SDK controller driver.
1. In the Kinetis USB controller, there is limitation that if the device is not ready to receive the setup token sent by the host, the device controller would hang. To avoid such issue, the driver needs to prime a transfer to receive the next setup token as soon as possible once the previous setup transfer is done. From the code we could see, the next setup prime operation would be called by the upper layer of the USB Kinetis driver, it might be not quick enough in some extreme cases.
There are customers that encountered this issue. In SDK controller driver, we prepare receiving the setup transaction quickly with the controller's ping-pong buffer in the usb ISR after last controler transfer is done.

2. I think many device controller will clear the EP0's stall state automatically when receiving the setup token from host, but the KHCI controller doesn't do this. So we need clear the stall state quickly after replying stall for EP0, otherwise the controller may return STALL for next setup transaction, this will lead host error. I think we have encountered this issue in the compliance test.

3. In old kinetis usb controller, there is only one bit to set the stall for IN and OUT of the same endpoint number. The new registers are added to support seperated stall in new controller. SDK controller driver will process this based on the SDK feature MACROs (new controller soc will define the feature MACRO). NXP controller is upgraded continually, if there is any new update or fix, we will update controller driver accordingly, the shim drvier doesn't need to care the details.

4. When the Clear_Feature(HALT) is received from the host via EP0, the data toggle needs to be reset. And any unfinished transfer needs to be cancelled. Please take the following case into accounted that the Host sends out a Clear_Feature(HALT) even the corresponding ep is NOT in stall status. I find that there is no callback in the usb_dc_kinetis.c.

**Comment by carlescufi** [comment]
@MarkWangChinese 

I've marked this as dev-review so that we can discuss this during a cal.
Would you be able to attend?
https://github.com/zephyrproject-rtos/zephyr/wiki/Zephyr-Committee-and-Working-Group-Meetings#zephyr-dev-meeting

**Comment by nashif** [comment]
discussed in dev-review meeting. Discussion will continue in the USB meeting.

**Comment by MarkWangChinese** [comment]
From my viewpoint, it is better for the SDK USB stack customers to migrate to Zephyr more smoothly, and the SDK controller driver can give them confidence because they have used it. And if there are any IP fix or upgrade, I will fix the controller driver with first priority and the shim driver can be updated quickly, I can contribute the native driver too, but it is second priority, the customers may get the update untimely.

**Comment by carlescufi** [comment]
@MarkWangChinese @MaureenHelm it would be good if you could post a technical comparison of the native and HAL-based drivers in terms of RAM/ROM footprint, features and performance (throughtput, etc.)

**Comment by MarkWangChinese** [comment]
I will update the comparison in next week, sorry for the delay.

**Comment by MarkWangChinese** [comment]
I build the mass demo, the footprint is as follow:
I execute the command line: cmake -GNinja -DOVERLAY_CONFIG="overlay-ram-disk.conf" -DBOARD=frdm_k64f  ..
The Shim Driver:
   text    data     bss     dec     hex filename
  35184   17924   11852   64960    fdc0 zephyr.elf
The Native Driver:
   text    data     bss     dec     hex filename
  34974   17964   12556   65494    ffd6 zephyr.elf
So the shim's flash size is bigger by 170 (text + data), the native driver's ram size is bigger by 744 (data + bss).

I do the throughput test as follow:
I increase the ram disk size by changing #define RAMDISK_VOLUME_SIZE (32 * 512) to #define RAMDISK_VOLUME_SIZE (300 * 512) in file fat12_ramdisk.h
I use the CrystalDiskMark's seq read/write to test the throughput, the shim driver's throughput is : Read (~799KB/s), Write (~707KB/s)
The native driver cannot run well, format fails on windows. I create one issue #17007.

For the technical comparision, I have listed few technical points for shim drivers' benifits previously. From my viewpoint, 1. There is any SOC upgrade, I will upgrade the MCUX SDK usb driver firstly, and the shim driver will update too, they are same except the shim, customer can get the upgrade quickly. 2. The shim driver gives the old NXP USB customers confidence to migrate from MCUX SDK to Zephyr.

**Pull request closed without merging**
