### PR TITLE
drivers: ONFI NAND: Add drivers for ONFI NAND Flash

### PR DESCRIPTION
**Pull request by rogeryou**
Add ONFI NAND Flash driver for using ONFI NAND Flash like MX30LF2GE8AB.
This driver is tested on MIMXRT1170_EVK.
The implementation is mainly inspired from NXP SDK.
And the onfi.h file unify the interface to access the ONFI NAND Flash controller.
As for controller layer, we add the SEMC module related driver to support the NAND Flash operation.
By the way, NAND Flash MX30LF2GE8AB's on-die ECC is always enable.
But the implementation also provide software ECC algorithm like BCH.

### CODE REVIEW

**Comment by carlescufi** [comment]
@de-nordic @Laczen could you take a look?

**Comment by carlescufi** [comment]
@rogeryou could you please take a look at the CI failures and fix them?

**Comment by danieldegrasse** [comment]
@rogeryou Please review [Zephyr's contribution guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html)

A few initial issues:
- CI will not pass with merge commits. Instead, please rebase changes onto the latest revision of `main`
- Commits must follow the naming style of `subsystem: commit title` and include a body (see [here](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines))
- Please keep commit messages as descriptive as possible, and group related changes. For this PR, you may want to split commits like this:
	- Commit introducing MEMC driver for NXP SEMC peripheral
	- Commit introducing  ONFI nand driver
	- Commit adding required changes to the board level to enable this flash device

**Comment by rogeryou** [comment]
> 

OK! I am trying to fix CI related issues.

**Pull request closed without merging**
