### PR TITLE
add MIPS arch and qemu Malta board support

### LINKED ISSUE #6082: Support the MIPS architecture
Support MIPS architecture and select boards. In addition and for the purpose of testing support Qemu and verify it passes all kernel tests.

### PR DESCRIPTION
**Pull request by frantony**
This PR adds support for the MIPS architecture and qemu Malta board.

* MIPS32r1 and MIPS32r2 CPUs are supported;
* both big- and little-endian modes are supported;
* soft-float is supported;
* Zephyr SDK 0.13.2 should be used.

Previous attempt to add MIPS support was https://github.com/zephyrproject-rtos/zephyr/pull/1576.

This PR was inspired by https://github.com/zephyrproject-rtos/zephyr/pull/29718 and adopts a lot of code from RISC-V, NIOS2, SPARC and Xtensa codebase.

How to test:
----------------

Install Zephyr SDK 0.13.2 (https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.13.2).

Compile & run the *hello_world* example:

```
cd /workdir/zephyr

export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
export ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.13.2/

source zephyr-env.sh

rm -rf build/
west build -b qemu_malta_be samples/hello_world
west build -t run
-- west build: running target run
[0/1] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: 24Kc
*** Booting Zephyr OS build v2.7.99-2234-g1b3e2e02c1c5  ***
Hello World! qemu_malta_be
```

Tasks:
---------------

- [x]  offset stuff/thread handling is adopted from RISC-V<s>offset stuff/thread handling is kept from https://github.com/zephyrproject-rtos/zephyr/pull/1576 and should be reworked</s>;
- [x] ``CONFIG_TICKLESS_KERNEL`` is <s>not</s> supported;
- [x] ``small-data section exceeds 64KB`` link error (samples/compression/lz4), fixed in https://github.com/zephyrproject-rtos/sdk-ng/pull/411; use [Zephyr SDK 0.13.2](https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.13.2);
- [x] [no qemu-system-mipsel in Zephyr SDK 0.13.1](https://github.com/zephyrproject-rtos/sdk-ng/issues/400) fixed in https://github.com/zephyrproject-rtos/sdk-ng/pull/401; use [Zephyr SDK 0.13.2](https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.13.2);
- [x] tests/subsys/cpp/libcxx     <s>Build failure (``relocation truncated to fit: R_MIPS_GPREL16 against `typeinfo for __cxxabiv1::__forced_unwind'``), the problem looks the same as https://github.com/zephyrproject-rtos/zephyr/pull/30405#issuecomment-955663713 but adding ```CT_NEWLIB_NANO_GCC_LIBSTDCXX_TARGET_CXXFLAGS``` to ct-ng/configs/mips.config does not fix the problem;</s> see fix in https://github.com/zephyrproject-rtos/zephyr/issues/6082#issuecomment-966590935
- [x] false negative error reports from twister <s>can be fixed with `-j` option;</s> CONFIG_QEMU_ICOUNT set to y.
- [x] tests/subsys/logging/log_api;
- [x] tests/subsys/logging/log_msg2;
- [x] real world hardware example (see https://github.com/frantony/zephyr/tree/20210617.mt76x8);
- [x] interrupt-enabled UART support, so samples/subsys/shell/shell_module/ runs under qemu;
- [x] tests/kernel/interrupt/arch.interrupt  <s>Build failure (``error: implicit declaration of function 'arch_irq_connect_dynamic'``). At the moment there is no ``arch_irq_connect_dynamic()`` function for mips</s>;
- [x] tests/kernel/context/kernel.common <s>test_kernel_cpu_idle* tests fail with ```Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/context/src/main.c:385: _test_kernel_cpu_idle: (tms2 < tms is true)```</s>.

Closes #6082.

### CODE REVIEW

**Comment by frantony** [comment]
@nashif @galak @andrewboie

At the moment I can run sanitycheck tests under qemu with this command sequence:

```
cd zephyr

export ZEPHYR_TOOLCHAIN_VARIANT=gccmipsmti
export GCCMIPSMTI_TOOLCHAIN_PATH=/opt/imgtec/Toolchains/mips-mti-elf/2017.10-05/
source zephyr-env.sh

./scripts/sanitycheck --arch mips
```

The corresponding sanitycheck output looks like this:

```
INFO    - Total complete:  241/ 241  100%  skipped:  609, failed:   86
INFO    - 82 of 168 test configurations passed (48.81%), 86 failed, 609 skipped with 0 warnings in 380.03 seconds
INFO    - In total 1213 test cases were executed, 5832 skipped on 1 out of total 313 platforms (0.32%)
INFO    - 62 test configurations executed on platforms, 106 test configurations were only built.
```

The most annoying test build error reason is this readelf warning:

```
readelf: Warning: [ 1]: Link field (0) should index a symtab section.
```

Have you any ideas how it can be fixed?

BTW, can we revive mips support in zephyr SDK?

**Comment by frantony** [comment]
Here is ``./scripts/twister --arch mips -v`` output for 27e6d9524a5:

```
INFO    - 131 of 168 test configurations passed (77.98%), 37 failed, 611 skipped with 0 warnings in 259.78 seconds
INFO    - In total 1189 test cases were executed, 5859 skipped on 1 out of total 314 platforms (0.32%)
INFO    - 102 test configurations executed on platforms, 66 test configurations were only built.
```

**Comment by frantony** [comment]
Here is ``./scripts/twister --arch mips -v`` output for 0a057ee557:

```
INFO    - 262 of 332 test configurations passed (78.92%), 70 failed, 997 skipped with 0 warnings in 448.79 seconds
INFO    - In total 2374 test cases were executed, 11418 skipped on 2 out of total 319 platforms (0.63%)
INFO    - 204 test configurations executed on platforms, 128 test configurations were only built.
```

**Comment by frantony** [comment]
Here is ``./scripts/twister --arch mips -v`` output for b484dcdb166483c5ccccfffcfa9ce507b0223a38:
```
==> gccmipsmti-toolchain.log <==
INFO    - 326 of 332 test configurations passed (98.19%), 6 failed, 997 skipped with 0 warnings in 391.32 seconds
INFO    - In total 2364 test cases were executed, 11430 skipped on 2 out of total 319 platforms (0.63%)
INFO    - 268 test configurations executed on platforms, 64 test configurations were only built.

==> zephyr-toolchain.log <==
INFO    - 313 of 348 test configurations passed (89.94%), 35 failed, 981 skipped with 0 warnings in 741.80 seconds
INFO    - In total 2471 test cases were executed, 11323 skipped on 2 out of total 319 platforms (0.63%)
INFO    - 255 test configurations executed on platforms, 93 test configurations were only built.
```

**Comment by adityaxavier** [comment]
Hi few observations.
1. I tried building it and running it on 7688an board ( 32MB flash, 256MB RAM ) on openwrt linux as an application, it did not work.
2. I tried building it and flashing it on 7688an Board instead of the openwrt bin file.. so that the bootloader boots it directly instead, it did not work. ~ BAD MAGIC number.
3. I tried building it and running it in Qemu, that didn't work either. 
4. There are few things I did not understand why you configured as.
     a. serial has a different id vs reg value.
     b. memory should ideally start from 0 and go up to 8000000, at least that's how I have in linux kernel DTS, if its size and location instead then size should be 0x8000000 instead of reg = <0x80100000 0x100000>, once changed to a lower number it is at least accepted by QEMU. Though then it throws out as invalid argument.
 

While you are at this, is it also possible to make a native_posix with cpu type as mips ? That would help to test it on top of linux instead of replacing the entire OS with zephyr at least initially.

Do let me know if I can be of any help.

**Comment by frantony** [comment]
@adityaxavier 

Thanks for your comment!

>Hi few observations.
>
>    I tried building it and running it on 7688an board ( 32MB flash, 256MB RAM ) on openwrt linux as an application, it did not work.
>    I tried building it and flashing it on 7688an Board instead of the openwrt bin file.. so that the bootloader boots it directly instead, it did not work. ~ BAD MAGIC number.

What board do you use?
What bootloader do you use?

I use experimental barebox bootloader with ELF file support.

But most of time I use loading via EJTAG.

Can you use EJTAG on your board?

>    I tried building it and running it in Qemu, that didn't work either.
>    There are few things I did not understand why you configured as.
>    a. serial has a different id vs reg value.

I suppose you are speaking about this

```
	uart2: serial@1ff70000 {
		compatible = "ns16550";
		reg = <0xb0000e00 0x100>;
		reg-shift = <2>;
```
I'll fix it in a short time.

>    b. memory should ideally start from 0 and go up to 8000000, at least that's how I have in  linux kernel DTS, if its size and location instead then size should be 0x8000000 instead of reg = <0x80100000 0x100000>, once changed to a lower number it is at least accepted by QEMU. 

Linux has separate memory areas and load address declaration. At the moment zephyr linking routine uses memory start address from dts to calculate load address. So changing memory start address to 0x80100000 I just change zephyr image load address.


>Though then it throws out as invalid argument.
>
> While you are at this, is it also possible to make a native_posix with cpu type as mips ? That would help to test it on top of linux instead of replacing the entire OS with zephyr at least initially.

Do you mean running native_posix zephyr on linux host with MIPS cpu?

> Do let me know if I can be of any help.

**Comment by adityaxavier** [comment]
> @adityaxavier
> 
> Thanks for your comment!
> 
> > Hi few observations.
> > I tried building it and running it on 7688an board ( 32MB flash, 256MB RAM ) on openwrt linux as an application, it did not work.
> > I tried building it and flashing it on 7688an Board instead of the openwrt bin file.. so that the bootloader boots it directly instead, it did not work. ~ BAD MAGIC number.
> 
> What board do you use?
Its 7688AN custom board, made by a Chinese manufacturer.
> What bootloader do you use?
Currently am using U-Boot ( Padavan version  )
> 
> I use experimental barebox bootloader with ELF file support.
Got it. I'll try porting barebox for it and attempt again.
> 
> But most of time I use loading via EJTAG.
> 
> Can you use EJTAG on your board?
I do not have EJTAG on my board. So I flashed zephyr elf file from padavan's web server and checked..
> 
> > I tried building it and running it in Qemu, that didn't work either.
> > There are few things I did not understand why you configured as.
> > a. serial has a different id vs reg value.
> 
> I suppose you are speaking about this
> 
> ```
> 	uart2: serial@1ff70000 {
> 		compatible = "ns16550";
> 		reg = <0xb0000e00 0x100>;
> 		reg-shift = <2>;
> ```
> 
> I'll fix it in a short time.
> 
> > b. memory should ideally start from 0 and go up to 8000000, at least that's how I have in  linux kernel DTS, if its size and location instead then size should be 0x8000000 instead of reg = <0x80100000 0x100000>, once changed to a lower number it is at least accepted by QEMU.
> 
> Linux has separate memory areas and load address declaration. At the moment zephyr linking routine uses memory start address from dts to calculate load address. So changing memory start address to 0x80100000 I just change zephyr image load address.
> 
> > Though then it throws out as invalid argument.
> > While you are at this, is it also possible to make a native_posix with cpu type as mips ? That would help to test it on top of linux instead of replacing the entire OS with zephyr at least initially.
> 
> Do you mean running native_posix zephyr on linux host with MIPS cpu?
Yes, I would not want to initially shift the entire production / development to Zephyr without working WiFI / Ethernet / Switch etc.. I was hence planning on using Zephyr to run a custom firmware to handle BLE side of things instead of having yet another BLE Firmware to manage and a GO / bluez stack on Linux. It would be of great use at least for me, to simplify release management.
> 
> > Do let me know if I can be of any help.

**Comment by frantony** [comment]
at the moment there is no qemu-system-mipsel in Zephyr SDK 0.13.1, please see https://github.com/zephyrproject-rtos/sdk-ng/issues/400

**Comment by frantony** [comment]
The https://github.com/zephyrproject-rtos/zephyr/commit/7839d70083e597633b733c0c9ec70d9839a7a0b3 contains fixes for timers and has this test results:

```
INFO    - 439 of 480 test configurations passed (91.46%), 41 failed, 2755 skipped with 0 warnings in 1476.26 seconds
INFO    - In total 3125 test cases were executed, 51334 skipped on 2 out of total 404 platforms (0.50%)
INFO    - 384 test configurations executed on platforms, 96 test configurations were only built.
```
We need a patch for sdk-ng:
```

diff --git a/configs/mips.config b/configs/mips.config
index a00859f..2b2d8aa 100644
--- a/configs/mips.config
+++ b/configs/mips.config
@@ -12,7 +12,7 @@ CT_BINUTILS_DEVEL_REVISION="c7d30a54fc17c1e9d9b1c39c7623222442c63af8"
 CT_NEWLIB_SRC_DEVEL=y
 CT_NEWLIB_DEVEL_URL="https://github.com/zephyrproject-rtos/newlib-cygwin.git"
 CT_NEWLIB_DEVEL_REVISION="2893dbb10f1fe3bf431a26f89a22e12a5020dc02"
-CT_LIBC_NEWLIB_TARGET_CFLAGS="-O2 -G0"
+CT_LIBC_NEWLIB_TARGET_CFLAGS="-O2 -G0 -mips32 -mabi=32 -mno-gpopt -fno-pic"
 # CT_LIBC_NEWLIB_ENABLE_TARGET_OPTSPACE is not set
 CT_LIBC_NEWLIB_IO_LL=y
 CT_LIBC_NEWLIB_IO_FLOAT=y
```

I'll prepare PR for sdk-ng later.

**Comment by stephanosio** [comment]
> +CT_LIBC_NEWLIB_TARGET_CFLAGS="-O2 -G0 -mips32 -mabi=32 -mno-gpopt -fno-pic"

It would be good to enable multilib if supported.

**Comment by frantony** [comment]
The https://github.com/zephyrproject-rtos/zephyr/pull/30405/commits/53f82419cc5f579d858418649360878c6767a718 is rebased on top of main branch and contains several fixes.

There are some false positive error reports from twister.

First run ``./scripts/twister --arch mips -v -v`` gives me this:
```
INFO    - 444 of 480 test configurations passed (92.50%), 35 failed, 2763 skipped with 0 warnings in 1811.81 seconds
INFO    - In total 3115 test cases were executed, 51481 skipped on 2 out of total 407 platforms (0.49%)
INFO    - 386 test configurations executed on platforms, 94 test configurations were only built.
```

Second run ``./scripts/twister --arch mips --only-failed -v -v`` gives me this:
```
INFO    - 8 of 36 test configurations passed (22.22%), 28 failed, 0 skipped with 0 warnings in 157.36 seconds
INFO    - In total 262 test cases were executed, 1 skipped on 0 out of total 407 platforms (0.00%)
INFO    - 30 test configurations executed on platforms, 6 test configurations were only built.
```

28 configuration failed. As there are big- and little- endian configuration for every test we have only 14 tests failed.

* tests/kernel/interrupt/arch.interrupt  Build failure (``error: implicit declaration of function 'arch_irq_connect_dynamic'``). At the moment there is no ``arch_irq_connect_dynamic()`` function for mips;

* tests/subsys/cpp/libcxx     Build failure (``relocation truncated to fit: R_MIPS_GPREL16 against `typeinfo for __cxxabiv1::__forced_unwind'``), the problem looks the same as https://github.com/zephyrproject-rtos/zephyr/pull/30405#issuecomment-955663713 but adding ```CT_NEWLIB_NANO_GCC_LIBSTDCXX_TARGET_CXXFLAGS``` to ct-ng/configs/mips.config does not fix the problem;

* tests/kernel/context/kernel.common test_kernel_cpu_idle* tests fails with ```Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/context/src/main.c:385: _test_kernel_cpu_idle: (tms2 < tms is true)```;

* tests/subsys/logging/log_api

* tests/subsys/logging/log_msg2

**Comment by frantony** [comment]
The https://github.com/zephyrproject-rtos/zephyr/commit/d69b4a92c3c1092b0d9dd04dedf5fcc06f8d74cb is rebased on top of main branch and contains several fixes.

There are some false negative error reports from twister.

First run ``./scripts/twister --arch mips -v -v`` gives me this:
```
INFO    - 451 of 480 test configurations passed (93.96%), 29 failed, 2765 skipped with 0 warnings in 1501.26 seconds
INFO    - In total 3115 test cases were executed, 51897 skipped on 2 out of total 407 platforms (0.49%)
INFO    - 389 test configurations executed on platforms, 91 test configurations were only built.
```

Second run ``./scripts/twister --arch mips --only-failed -v -v`` gives me this:
```
INFO    - 5 of 29 test configurations passed (17.24%), 24 failed, 0 skipped with 0 warnings in 140.53 seconds
INFO    - In total 199 test cases were executed, 11 skipped on 0 out of total 407 platforms (0.00%)
INFO    - 25 test configurations executed on platforms, 4 test configurations were only built.
```

24 configuration failed. As there are big- and little- endian configuration for every test we have only 12 tests failed.

* tests/subsys/cpp/libcxx     Build failure (``relocation truncated to fit: R_MIPS_GPREL16 against `typeinfo for __cxxabiv1::__forced_unwind'``), the problem looks the same as https://github.com/zephyrproject-rtos/zephyr/pull/30405#issuecomment-955663713 but adding ```CT_NEWLIB_NANO_GCC_LIBSTDCXX_TARGET_CXXFLAGS``` to ct-ng/configs/mips.config does not fix the problem;

* tests/subsys/logging/log_api

* tests/subsys/logging/log_msg2

**Comment by frantony** [comment]
The https://github.com/zephyrproject-rtos/zephyr/commit/2ef72de3e38209cb3d059898824fc449c38cac6c is rebased on top of main branch and contains several fixes.

There are some false negative error reports from twister.

First run ``./scripts/twister --arch mips -v -v`` gives me this:
```
INFO    - 471 of 478 test configurations passed (98.54%), 6 failed, 2767 skipped with 0 warnings in 1210.98 seconds
INFO    - In total 3104 test cases were executed, 51909 skipped on 2 out of total 407 platforms (0.49%)
INFO    - 389 test configurations executed on platforms, 89 test configurations were only built.
```

Second run ``./scripts/twister --arch mips --only-failed -v -v`` gives me this:
```
INFO    - 3 of 7 test configurations passed (42.86%), 4 failed, 0 skipped with 0 warnings in 51.36 seconds
INFO    - In total 53 test cases were executed, 0 skipped on 0 out of total 407 platforms (0.00%)
INFO    - 3 test configurations executed on platforms, 4 test configurations were only built.
```

4 configuration failed. As there are big- and little- endian configuration for every test we have only 2 tests failed.

* tests/subsys/cpp/libcxx     Build failure (``relocation truncated to fit: R_MIPS_GPREL16 against `typeinfo for __cxxabiv1::__forced_unwind'``), the problem looks the same as https://github.com/zephyrproject-rtos/zephyr/pull/30405#issuecomment-955663713 but adding ```CT_NEWLIB_NANO_GCC_LIBSTDCXX_TARGET_CXXFLAGS``` to ct-ng/configs/mips.config does not fix the problem.

**Comment by frantony** [comment]
@stephanosio

> > +CT_LIBC_NEWLIB_TARGET_CFLAGS="-O2 -G0 -mips32 -mabi=32 -mno-gpopt -fno-pic"
> 
> It would be good to enable multilib if supported.

multilib is already enabled, please see https://github.com/zephyrproject-rtos/sdk-ng/blob/main/configs/mips.config#L7. Here is ``gcc -print-multi-lib`` output:

```
$ /opt/toolchains/zephyr-sdk-0.13.1/mips-zephyr-elf/bin/mips-zephyr-elf-gcc -print-multi-lib
.;
soft-float;@msoft-float
el;@EL
soft-float/el;@msoft-float@EL
```

**Comment by frantony** [comment]
The https://github.com/zephyrproject-rtos/zephyr/pull/30405/commits/bf182866ae4dc5e16dee5a6ac22a2197d6a6fb58 is rebased on top of main branch and contains several fixes. It can pass 100% tests after patching ct-ng, see https://github.com/zephyrproject-rtos/zephyr/issues/6082#issuecomment-966590935

**Comment by frantony** [comment]
The https://github.com/zephyrproject-rtos/zephyr/pull/30405/commits/4170bbcb3b42abad6a193d544bcf9d05c2f1a083 is rebased on top of main branch.
Use [Zephyr SDK 0.13.2](https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.13.2).

```
INFO    - 478 of 478 test configurations passed (100.00%), 0 failed, 2783 skipped with 0 warnings in 1690.52 seconds
INFO    - In total 3056 test cases were executed, 51999 skipped on 2 out of total 409 platforms (0.49%)
INFO    - 396 test configurations executed on platforms, 82 test configurations were only built.
```

Changes since https://github.com/zephyrproject-rtos/zephyr/commit/bf182866ae4dc5e16dee5a6ac22a2197d6a6fb58:

* TICKLESS_KERNEL support is added;
* CONFIG_QEMU_ICOUNT set to y.

**Comment by frantony** [comment]
@galak 

At the moment buildkite uses SDK 0.13.1. SDK 0.13.2 should be used for MIPS port.

Could you please update SDK to 0.13.2 in the buildkite pipeline?

**Comment by stephanosio** [comment]
> Could you please update SDK to 0.13.2 in the buildkite pipeline?

@frantony #40469

**Comment by frantony** [comment]
@andrewboie @andyross @carlescufi @galak @MaureenHelm @nashif

I suppose that the PR is ready for merging.

Please review!

github CI reports about several warnings:

```
-:2421: WARNING:NEW_TYPEDEFS: do not add new typedefs
#2421: FILE: include/arch/mips/thread.h:44:
+typedef struct _callee_saved _callee_saved_t;

-:2427: WARNING:NEW_TYPEDEFS: do not add new typedefs
#2427: FILE: include/arch/mips/thread.h:50:
+typedef struct _thread_arch _thread_arch_t;

-:2491: WARNING:NEW_TYPEDEFS: do not add new typedefs
#2491: FILE: lib/libc/minimal/include/sys/types.h:51:
+typedef int off_t;
```

I see that every arch introduces ``_callee_saved_t``,  ``_thread_arch_t`` and ``off_t`` type definition so I can't avoid these warnings.

**Comment by frantony** [comment]
@andrewboie @andyross @carlescufi @galak @MaureenHelm @nashif

Please review!

**Comment by carlescufi** [comment]
@andyross @dcpleung @stephanosio @peter-mitsis reviews welcome

**Comment by carlescufi** [comment]
> I see that every arch introduces `_callee_saved_t`, `_thread_arch_t` and `off_t` type definition so I can't avoid these warnings.

Yes, don't worry @frantony, just ignore them and we'll override the failure.

**Review by dcpleung — APPROVED** [review]

**Comment by frantony** [comment]
@andyross @carlescufi @galak @MaureenHelm @nashif @peter-mitsis @stephanosio

Please, review!

**Review by peter-mitsis — APPROVED** [review]
Looks good as far as I can tell.

**Pull request merged**
