### PR TITLE
MAINTAINERS: Add snematbakhsh as OpenTitan platform maintainer

### PR DESCRIPTION
**Pull request by snematbakhsh**
Add myself as maintainer for OpenTitan.

### CODE REVIEW

**Comment by ycsin** [comment]
Could you please have a look at the CI errors?

**Comment by snematbakhsh** [comment]
> Could you please have a look at the CI errors?

Typo fixed - now passing, thanks.

**Review by ycsin — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Comment by ycsin** [comment]
ping @MaureenHelm

**Review by MaureenHelm — APPROVED** [review]

**Comment by kartben** [comment]
@snematbakhsh  thanks for stepping up as a maintainer! Feel free to claim your Zephyr Maintainer badge here: [forms.gle/oCw9iAPLhUsHTapc8](https://forms.gle/oCw9iAPLhUsHTapc8) :)

**Pull request merged**
