### PR TITLE
code-guideline: Warning about implicit fallthrough in switch() satements

### PR DESCRIPTION
**Pull request by ceolin**
Option -Wimplicit-fallthrough as the name suggests raises a warning when
there is an implicit fallthrough in a switch clause. This warning does
not happen when the last statement is a return or a call to a function
declared with noreturn attribute.

This flag helps to enforce two MISRA-C rules (not completely), 16.1 and
16.3

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by nashif** [comment]
This seems to be problematic with 3rd party code in modules, it is already failing on nrf hal that was updated just yesterday. We can't enforce gcc warnings on 3rd party code

**Comment by pfalcon** [comment]
> This seems to be problematic with 3rd party code in modules, it is already failing on nrf hal that was updated just yesterday. We can't enforce gcc warnings on 3rd party code

I see problems with Zephyr builds in Linaro CI, where it complains about lib/fnmatch/fnmatch.c: https://ci.linaro.org/job/zephyr-upstream/5488/PLATFORM=qemu_cortex_m3,ZEPHYR_TOOLCHAIN_VARIANT=zephyr,label=docker-xenial-amd64-13/console (search for "this statement may fall through"). Strangely, I can't reproduce that locally so far.

Beyond that, it fails JerryScript Zephyr port, where the error truly happens in 3rd-party code (i.e. JerryScript): 

I'm still looking into (and that's why I didn't post a bug), but it looks like this warning should be a Kconfig option. It may be even enabled by default, but there should be a way to disable it based on particular application interfacing needs.

**Comment by ceolin** [comment]
> > This seems to be problematic with 3rd party code in modules, it is already failing on nrf hal that was updated just yesterday. We can't enforce gcc warnings on 3rd party code
> 
> I see problems with Zephyr builds in Linaro CI, where it complains about lib/fnmatch/fnmatch.c: https://ci.linaro.org/job/zephyr-upstream/5488/PLATFORM=qemu_cortex_m3,ZEPHYR_TOOLCHAIN_VARIANT=zephyr,label=docker-xenial-amd64-13/console (search for "this statement may fall through"). Strangely, I can't reproduce that locally so far.
> 
> Beyond that, it fails JerryScript Zephyr port, where the error truly happens in 3rd-party code (i.e. JerryScript): https://ci.linaro.org/jenkins/job/lite-aeolus-jerryscript/PLATFORM=frdm_k64f,ZEPHYR_TOOLCHAIN_VARIANT=zephyr,label=docker-xenial-amd64-13/1184/display/redirect
> 
> I'm still looking into (and that's why I didn't post a bug), but it looks like this warning should be a Kconfig option. It may be even enabled by default, but there should be a way to disable it based on particular application interfacing needs.



> > This seems to be problematic with 3rd party code in modules, it is already failing on nrf hal that was updated just yesterday. We can't enforce gcc warnings on 3rd party code
> 
> I see problems with Zephyr builds in Linaro CI, where it complains about lib/fnmatch/fnmatch.c: https://ci.linaro.org/job/zephyr-upstream/5488/PLATFORM=qemu_cortex_m3,ZEPHYR_TOOLCHAIN_VARIANT=zephyr,label=docker-xenial-amd64-13/console (search for "this statement may fall through"). Strangely, I can't reproduce that locally so far.
> 
> Beyond that, it fails JerryScript Zephyr port, where the error truly happens in 3rd-party code (i.e. JerryScript): https://ci.linaro.org/jenkins/job/lite-aeolus-jerryscript/PLATFORM=frdm_k64f,ZEPHYR_TOOLCHAIN_VARIANT=zephyr,label=docker-xenial-amd64-13/1184/display/redirect
> 
> I'm still looking into (and that's why I didn't post a bug), but it looks like this warning should be a Kconfig option. It may be even enabled by default, but there should be a way to disable it based on particular application interfacing needs.

That makes sense (the problem), I can workaround making it optional for now, but I don't believe that is the right thing to do. We should not use exactly the same flags we use to build Zephyr's code on third-party components. There are many other options that can help us to enforce our code guideline that will cause problems in thirdy-party.

IMHO they should be always set since they are enforcing our own code-guideline, so we need change the build to allow using a set of flags only in Zephyr's code. That's said, it is not a bad idea make it optional while we don't have it properly fixed.

**Comment by pfalcon** [comment]
@ceolin:

> We should not use exactly the same flags we use to build Zephyr's code on third-party components.

Maybe we shouldn't, but the matter of fact that we do. And it's very easy to explain why: to compile a C source (properly), we need to pass proper CFLAGS to C compiler. So, 3rd-party modules query Zephyr build system for CFLAGS, and pass it to C compiler. And that includes **all** compiler options - from target selection, down to proverbial warning options.

Now you're saying that we should have different categories of compiler options, and I fully agree with you. Instead of:

~~~
  zephyr_compile_options(
    -Wimplicit-fallthrough=2
    )
~~~
we should have:

~~~
  zephyr_compile_warn_options(
    -Wimplicit-fallthrough=2
    )
~~~

And then d3a8fd40b902e1f1b95be9812d8b71dc0e270a1e (the file from it) should be updated to generate different `Z_CFLAGS_*` options (e.g. Z_CFLAGS_MAIN, Z_CFLAGS_INC, Z_CFLAGS_WARN), to allow 3rd-party modules finer control of what they want to pick up from Zephyr.

So, if you can go to implement it this way, that would be much appreciated. My cmake foo is unlikely enough to do that.


cc @tejlmand to be in loop of this issue and possibly help.

**Comment by pfalcon** [comment]
In the meantime, commit to enable this option was reverted in https://github.com/zephyrproject-rtos/zephyr/pull/27775 (apparently, temporarily).

**Pull request merged**
