### PR TITLE
drivers/uart: stm32: Report 9bits transactions as not supported

### LINKED ISSUE #31799: uart_configure does not return -ENOTSUP for stm32 uart with 9 bit data length.
**Describe the bug**
When we use uart_configure on STM32 for a device with data length of 9 bits we dont get -ENOTSUP

**To Reproduce**
1. Create a 9bit configuration for uart device
2. use that device as an argument for uart_configure 
3. Bug. Seems like device is initialized and supports 9bit.

**Expected behavior**
Return -ENOTSUP

**Impact**
Not that critical. Lack of 9bit support is more critical.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit 95712bd4988930760cddd95ad7c3fc4065ebccbb

### PR DESCRIPTION
**Pull request by erwango**
STM32 uart driver doesn't support 9bits transactions in any case,
so remove case were it was declared as supported.

Fixes #31799

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by erwango** [comment]
Reported error  is the following:
```
-:13: WARNING:CONSTANT_COMPARISON: Comparisons should place the constant on the right side of the test
#13: FILE: drivers/serial/uart_stm32.c:342:
+	    || (UART_CFG_DATA_BITS_9 == cfg->data_bits)) {
```
Need to fix the whole file...

**Review by dcpleung — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Comment by hwilmers** [comment]
This removes support for following configuration:
   UART_CFG_PARITY_EVEN,
   UART_CFG_DATA_BITS_9
I found this configuration to result in the uart performing "8 bits, even parity" (on stm32l475) with good success.
Would there be any other way to achieve this configuration after above PR?

**Comment by erwango** [comment]
> I found this configuration to result in the uart performing "8 bits, even parity" (on stm32l475) with good success.

@hwilmers, do you mean "9 bits, even parity"? Or maybe I'm not understanding correctly your point.

**Comment by hwilmers** [comment]
I mean "8 bits, even parity", like in "19200 8E1".
It may be the result of an unintended side effect that this works.

**Comment by erwango** [comment]
> It may be the result of an unintended side effect that this works.

Probably

@dcpleung, do you have any hint for this question: https://github.com/zephyrproject-rtos/zephyr/pull/32204#issuecomment-789699346 ? Should we find a way to let it work "unintentionally" ?

**Comment by hwilmers** [comment]
Apparently, the word length as it is used in the stm32 usart includes the optional parity bit. This is what I found in this official reference manual, on page 1345:
https://www.st.com/content/ccc/resource/technical/document/reference_manual/02/35/09/0c/4f/f7/40/03/DM00083560.pdf/files/DM00083560.pdf/jcr:content/translations/en.DM00083560.pdf

A straight forward translation between usual notation and the implementation on stm32 would be to add one to the word length if a parity bit is appended.

**Pull request merged**
