### PR TITLE
boards: arm: xiao_ble: add blackmagicprobe runner

### PR DESCRIPTION
**Pull request by augustozanellato**
Add support for running and debugging xiao_ble with blackmagicprobe.
Tested with a stlink v2 flashed with native bmp.

### CODE REVIEW

**Comment by kartben** [comment]
Hi @augustozanellato  -- would you be so kind to also update the board's README to indicate that using BMP is an option? Maybe take inspiration from Arduino Giga R1 doc?

**Review by MaureenHelm — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]
+1 but if you happen to want to update the README as per my earlier comment, @augustozanellato, that would be great :)

**Comment by augustozanellato** [comment]
> +1 but if you happen to want to update the README as per my earlier comment, @augustozanellato, that would be great :)

Sorry, I forgot to do that after your previous comment, just pushed the doc update.

**Comment by kartben** [comment]
> > +1 but if you happen to want to update the README as per my earlier comment, @augustozanellato, that would be great :)
> 
> Sorry, I forgot to do that after your previous comment, just pushed the doc update.

Thanks! Since you will need to fix your second commit as it's not signed off, may I suggest you actually squash everything into just one commit anyway, as it's all the same change. Thanks again!

**Comment by augustozanellato** [comment]
> Thanks! Since you will need to fix your second commit as it's not signed off, may I suggest you actually squash everything into just one commit anyway, as it's all the same change. Thanks again!

I fixed the commit before seeing this message, but now it's squashed

**Review by kartben — APPROVED** [review]
Perfect! Thanks for your patience and hope this is only the first of many more contributions :-)

**Review by MaureenHelm — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Pull request merged**
