### PR TITLE
MAINTAINERS: Add ADI Platforms section

### PR DESCRIPTION
**Pull request by MaureenHelm**
Adds new ADI Platforms section covering device drivers and bindings for Analog Devices, Maxim Integrated, and Linear Technology.

### CODE REVIEW

**Comment by nashif** [comment]
hmm, that does not seem to be covering any platforms though...

**Comment by MaureenHelm** [comment]
> hmm, that does not seem to be covering any platforms though...

Indeed, but it seemed like the closest fit since all the vendor-specific sections are platforms. I thought "ADI drivers" or something similar might get confused as a class of drivers with a common API.

**Review by carlescufi — APPROVED** [review]
Yay!

**Review by microbuilder — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> > hmm, that does not seem to be covering any platforms though...
> 
> Indeed, but it seemed like the closest fit since all the vendor-specific sections are platforms. I thought "ADI drivers" or something similar might get confused as a class of drivers with a common API.

Also if you name it anything differently it'd miss

https://github.com/zephyrproject-rtos/zephyr/blob/731b689c499d0aeb192192f355f55bfe19a23743/scripts/set_assignees.py#L121C23-L121C23

**Pull request merged**
