### PR TITLE
MAINTAINERS/CODEOWNERS: Removing myself from maintainer role

### PR DESCRIPTION
**Pull request by jukkar**
I cannot invest the time required for maintaining the networking
stack anymore, so I am stepping down from the maintainer role.
I am proposing Rober Lubos to be a new network maintainer.
I have been working with him for several years, and he is always
very helpful and knowledgeable to review and comment patches and
issues. He knows the network stack well and will for sure be able
to handle the task as he has been doing the maintenance already
for a long time.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>
Acked-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by ioannisg** [comment]
Do we need a TSC label here (and, ultimately, a TSC vote)? @rlubos is already an appointed Zephyr Maintainer for other code areas; TSC does not need to approve adding him as maintainer for this additional area. His acceptance of the role should be sufficient, IMO.
@nashif FYI

**Review by MaureenHelm — APPROVED** [review]
Thank you @jukkar for your many contributions over the last 5 years. Best wishes in your new role!

Thank you @rlubos for stepping up to maintain the networking stack!

**Comment by jukkar** [comment]
> Thank you @jukkar for your many contributions over the last 5 years. Best wishes in your new role!

Thanks Maureen, it has been a pleasure to work with the whole Zephyr community!

**Comment by galak** [comment]
Thanks @jukkar!  Wish you well in your next endeavors.  Thanks @rlubos for taking over!

**Review by galak — APPROVED** [review]

**Comment by jukkar** [comment]
Fixed merge conflict.

**Review by mniestroj — APPROVED** [review]

**Comment by cfriedt** [comment]
Wow @jukkar - I can't imagine yours will be easy shoes to fill. Thanks for all of your help over the years!

**Pull request merged**
