### PR TITLE
tests: fix filtering on integration platforms

### LINKED ISSUE #39738: twister: tests: samples: Skips on integration_platforms in CI
**Describe the bug**
If `integration_platforms` are given in a sample/testcase yaml it means the CI has to evaluate these platforms (they must not get skipped). A CI test for #36433 exposed that the following tests/samples requires a fix:

- samples/subsys/shell/shell_module/sample.shell.shell_module.minimal_rtt in native_posix:samples/subsys/shell/shell_module/sample.shell
- tests/drivers/flash/drivers.flash.stm32 in nrf52840dk_nrf52840:tests/drivers/flash/drivers.flash
- tests/subsys/logging/log_core_additional/logging.add.user in native_posix:tests/subsys/logging/log_core_additional/logging.add
- tests/ztest/mock_fff/testing.ztest.mock_fff in native_posix:tests/ztest/mock_fff/testing.ztest
- tests/ztest/mock_fff/testing.ztest.mock_fff_global in native_posix:tests/ztest/mock_fff/testing.ztest

**To Reproduce**
See error in CI https://buildkite.com/zephyr/zephyr/builds/44471#16cc743c-5380-409d-aee4-fd17801a3155
run `scripts/twister -G -v -T <path_to_problematic_test>
see skips in results

**Impact**
Breach in CI regression testing. Instead of being executed, a test/sample was silently skipped. These tests has to be fixed before #36433 can be merged

**Environment (please complete the following information):**
Doesn't matter

### PR DESCRIPTION
**Pull request by nashif**
Fixed filtering on integration platforms.

Fixes #39738

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by nordic-krch — APPROVED** [review]

**Comment by PerMac** [comment]
I see the PR doesn't address all errors from the issue this PR marks as getting fixed. Validating if the reported error is fixed is a bit hard, because the errors are exposed in another PR #36433. It means we might need to rebase #36433 onto this PR to check if this PR fixes some errors exposed in #36433. I can rebase my PR onto this one, and we will see if the errors are gone. 
 @nashif Is the plan to fix those errors in parts? After validating rebasing on in #36433 I can approve this PR, but after it is merged and there are still not all errors fixed, i will reopen #39738 and edit to what errors are left.

**Review by PerMac — CHANGES_REQUESTED** [review]
I see the PR doesn't address all errors from the issue this PR marks as getting fixed. Validating if the reported error is fixed is a bit hard, because the errors are exposed in another PR #36433. It means we might need to rebase #36433 onto this PR to check if this PR fixes some errors exposed in #36433. I can rebase my PR onto this one, and we will see if the errors are gone. 
 @nashif Is the plan to fix those errors in parts? After validating rebasing on in #36433 I can approve this PR, but after it is merged and there are still not all errors fixed, i will reopen #39738 and edit to what errors are left.

**Comment by nashif** [comment]
@PerMac  this is not going to work and I am not sure why I was assigned to https://github.com/zephyrproject-rtos/zephyr/issues/39738 in the first place, just trying to get rid of this bug and remove it from my plate.

The right way to do it is to fix all issues your PR (#36433) finds in the same PR, otherwise this will continue to be a chicken and egg problem.

This PR fixes the issues listed in the original issue, if you think it does not, please let me know what it does not fix and I will look at it.
I can't be dealing with an open-ended bug that depends on something else.

**Comment by nashif** [comment]
> @nashif Is the plan to fix those errors in parts? After validating rebasing on in #36433 I can approve this PR, but after it is merged and there are still not all errors fixed, i will reopen #39738 and edit to what errors are left.

IMO You should fix those in the same PR you are exposing them.

**Comment by PerMac** [comment]
@nashif:
>@PerMac this is not going to work and I am not sure why I was assigned to https://github.com/zephyrproject-rtos/zephyr/issues/39738 in the first place, just trying to get rid of this bug and remove it from my plate.

Twister and CI is leaky. Many regressions are caught by developers by chance, after being in the main for a while. I am aware of all the difficulties in such a vast project, with hundreds of platforms and thousands of tests that can be executed. Testing everything is just not feasible. 
We try patching those breaches by providing new fixes and workflows. Having the CI decided what to test and what to skip is probably necessary for such a vast project, but we need at least reliability and traceability of the "decision process". One of the ideas to get a bit more control over the CI was to use "integration_platforms". This list not only tells CI which platform to choose for testing but what is IMO more important it should forbid the CI to skip such configurations. I mean, what is even the point of explicitly telling CI which configuration to test, if the CI could decide to skip it at one point, and no one will even realized, that there is 0 coverage in the CI for a given feature/module/etc? And the problem is that it actually continue to happen.  

IMO having unreliable CI is a HIGH PRIORITY issue. I think our mindset should be "how to improve the quality/reliability" and not "get rid of this bug". 

>IMO You should fix those in the same PR you are exposing them.

Ok, we can try this approach. I will certainly ask for help, since I don't have enough knowledge about all the exposed bugs

> This PR fixes the issues listed in the original issue, if you think it does not, please let me know what it does not fix and I will look at it.

The mentioned issue listed 5 exposed failures, where in this PR you addressed 2 of them. I am sorry, but I don't see a point in coping the issue's body here. I rebased my PR exposing the issues on this one and main and some of the reported issues are still there.

>I can't be dealing with an open-ended bug that depends on something else.

It is not an open ended bug. It has clear definition of failing samples. It seems after all the rebasing new issues were exposed, but there are not reported as the part of the issue yet and don't have to be. So I don't expect you to keep on fixing all the newly exposed bugs, neither do I plan to have the issue growing. I can open a new one and try fixing other issues. But please, don't imply that I am making the original issue open ended. The scope was clearly defined and not fully addressed.

**Comment by nashif** [comment]
> IMO having unreliable CI is a HIGH PRIORITY issue. I think our mindset should be "how to improve the quality/reliability" and not "get rid of this bug".

huh, cool down. I am fine with this being fixed, however the approach is not ideal. You are introducing a change that exposes issues, fine, fix those issues with the change so we can get it integrated the earliest. Filing bugs against each issue is just going to delay this and the fixes are trivial enough to be part of the code that introduces them.


> The mentioned issue listed 5 exposed failures, where in this PR you addressed 2 of them. I am sorry, but I don't see a point in coping the issue's body here. I rebased my PR exposing the issues on this one and main and some of the reported issues are still there.
Because 1 was fixed automagically and did not need a fix and 2 others can't be fixed, they depend on a module that is not in the manifest, so there is nothing to fix.

> It is not an open ended bug. It has clear definition of failing samples. It seems after all the rebasing new issues were exposed, but there are not reported as the part of the issue yet and don't have to be.

yes, thats what I call open-ended, but the time something is fixed, new issues will show up because we did not integrate the change that would guard against them, so this is going to be a whack a mole type of situation, read: open-ended.

**Comment by PerMac** [comment]
The commit was cherry-picked into #36433 as suggested. This is the PR which exposes the issue and will come with the fixes for exposed failures.

**Pull request closed without merging**
