### PR TITLE
soc: nordic: Use 31250 Hz as system tick rate for GRTC

### PR DESCRIPTION
**Pull request by nordic-krch**
So far 10 kHz tick rate was used but it has 2 drawbacks:
- kernel timer precision is limited to 100 us which is worse compared to 30 us on platforms which use RTC (which had 32768 Hz tick rate)
- GRTC has 1 MHz frequency so tick rate requires dividing by 100 during timeout calculation. When 31250 Hz is used (which is 1000000 / 32) then dividing can be done with bit shifting and it is faster (> 2 times faster on Cortex-M33 and >8 times faster on VPR - RISCV).

### CODE REVIEW

**Comment by nordic-krch** [comment]
@adamkondraciuk fyi

**Comment by nordicjm** [comment]
@tmon-nordic don't know anything about the USB implementation but can you think of any reason that 32us is too slow of a tick rate?

**Comment by tmon-nordic** [comment]
> @tmon-nordic don't know anything about the USB implementation but can you think of any reason that 32us is too slow of a tick rate?

Tick rate doesn't really matter in USB context IMHO. Things that are timing specific are always relative to SOF packet, and the software pretty much have to handle the interrupt right away to be in time. I cannot quite see a reason why any tick rate would be "too slow", as long as the necessary context switch can happen as a result of interrupt anywhere within the "tick slot".

**Comment by nordic-krch** [comment]
@anangl @adamkondraciuk @nordicjm @gmarull can you take a look?

**Review by nordicjm — APPROVED** [review]

**Comment by masz-nordic** [comment]
Conflicting with https://github.com/zephyrproject-rtos/zephyr/pull/77607

**Comment by anangl** [comment]
> * kernel timer precision is limited to 100 us which is worse compared to 30 us on platforms which use RTC (which had 32768 Hz tick rate)

Is this actually a drawback? According to [Zephyr docs](https://docs.zephyrproject.org/latest/kernel/services/timing/clocks.html#time-units), the tick rate is expected to be in range of 10 kHz by default on most platforms. Actually, 32768 Hz for nRF platforms that use RTC is one of the exceptions and it was introduced more to avoid dividing of the clock frequency in software than to get a better accuracy of timeouts (see https://github.com/zephyrproject-rtos/zephyr/commit/7c0f44816ef65707c3859329ee8367d3524e613c). And such short 30 us tick was in fact causing some troubles, for example in kernel tests (see https://github.com/zephyrproject-rtos/zephyr/commit/c55266a925b03e333cb30e887ddf2a34da38ede7 and https://github.com/zephyrproject-rtos/zephyr/commit/4d511cfb6a0c2c6875edc813dcb79ae56fd9a25b).

Maybe it would be better to use 15625 by default (to simplify division) and higher rates only in applications that really require it?

**Comment by nordic-krch** [comment]
> And such short 30 us tick was in fact causing some troubles, for example in kernel tests

That was because they were written assuming tick rate is slower than 10 khz. It does not mean that higher tick rate is bad even though the docs states that it should be in range of 10 kHz I am not aware of any technical reason why it should not (except for tests not ready for that).

One example that comes to my mind is handling of RX timeouts in nordic uart driver where k_timer periodically checks for line activity. Shortest RX timeout that can be set is 5 * shortest kernel timeout. It does not apply to platforms with GRTC because they have HW RX timeout but it's just an example where higher tick rate can give significant benefits.

Another thing is that nordic platforms had been working with 32 khz for long so users may expect similar precision on new platforms.

**Comment by nordicjm** [comment]
With 10KHz you have a maximum resolution of 100us, with 32.768KHz you have a maximum resolution of 30.5us, so if you need short intervals then the latter is preferred (I know for at least 1 in-tree sensor, which I am using with an nRF52840, the 30.5us rate is required, 100us would not allow any communication with it)

**Review by anangl — APPROVED** [review]

**Pull request merged**
