### PR TITLE
hal_st: Make it a zephyr library.

### LINKED ISSUE #19614: Make zephyr_library out of hal_stm32 and hal_st
**Is your enhancement proposal related to a problem? Please describe.**
cf https://github.com/zephyrproject-rtos/hal_nordic/pull/6

### PR DESCRIPTION
**Pull request by erwango**
Depends on zephyrproject-rtos/hal_st/pull/4 and zephyrproject-rtos/hal_stm32/pull/52

Fixes #19614

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by avisconti — APPROVED** [review]
PR #4
Very good!

**Comment by erwango** [comment]
Seems it doesn't work as expected

**Comment by avisconti** [comment]
> Seems it doesn't work as expected

Strange.
Yesterday I tried it out. What I did was to take your commit, apply it on hal/st here and compile/test everything. I'm quite sure I was using your patch.

To be honest I'm not able to get why CI is breaking. I'm not able to download the logs.

**Comment by erwango** [comment]
@avisconti  I think I got it: I was declaring `zephyr_library` outside of `HAS_STLIB`, which could create am empty lib in some cases.

**Comment by erwango** [comment]
@avisconti Interesting failure remains as it seems we should not share HAS_STLIB
between both modules.
I'll fix this tomorrow

**Review by joerchan — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Pull request merged**
