### PR TITLE
tests: spi: stm32: STM32 SPI driver unit tests

### PR DESCRIPTION
**Pull request by dgastonochoa**
This is a proposal for adding unit tests for the STM32 SPI driver.

I have seen that there are no unit-tests for drivers. I don't know if it's a Zephyr policy to not have them.

Part of the source code needs to be adapted to be able to run unit tests. The 2 main points that summarize these changes are:

* Since these are unit tests, it's necessary to create "bridge" functions that can be "faked" with FFF. Essentially, this means expanding the `spi_ll_stm32.h` header, which contains functions such as `ll_func_tx_is_empty`, and replace all the platform-specific calls in the driver by these. This cannot be `static inline` in a header file, they need to be defined in a `*.c` file so the interface can be mocked. 
* It's necessary to add conditional compilation statements to not include certain things in the unit tests (all the driver initialization with macros such as `DT_INST_FOREACH_STATUS_OKAY` for instance). This is something that has already being done in `bluetooth`.

How to test
=======
The tests can be run with the following command:

`west twister -O ./build/twister-custom-out --no-clean --inline-logs -T tests/drivers/spi/spi_stm32/`

Also, run the existing SPI loopback tests.

### CODE REVIEW

**Comment by dgastonochoa** [comment]
Hi @teburd and @erwango, 

I created this draft to receive a shallow review before making it a real PR. This is to verify that the principle of this draft is admissible for Zephyr, rather than receiving detailed feedback (see description). My main question is if it's problem to create an interface to decouple the STM32 SPI driver from the STMCube low level functions. 

In general, if the idea of this draft is approved, I will move it to an actual PR and then the actual review will start.

Thanks.

**Comment by dgastonochoa** [comment]
I forgot to mention that I have more test cases, but I didn't want to add them as they are not relevant for this draft's purpose.

**Comment by dgastonochoa** [comment]
Kind reminer to @teburd @erwango @tbursztyka 

This draft has had no activity for quite a while. Could I receive some feedback about whether or not it's feasible to merge this change, after applying the (potential) requested changes? Maybe the change is considered too large and not worthy it as its purpose is to add unit tests to a driver; in this case I would appreciate to clarify it.

**Comment by erwango** [comment]
> This draft has had no activity for quite a while.

If it's ready to review, please move it out of draft state (which is equivalent to "not ready for review")

**Comment by erwango** [comment]
@dgastonochoa If it's ready to review, please move it out of draft state (which is equivalent to "not ready for review")

**Comment by dgastonochoa** [comment]
> @dgastonochoa If it's ready to review, please move it out of draft state (which is equivalent to "not ready for review")

It requires little changes to rebase, but in general it is ready for review.

**Comment by MaureenHelm** [comment]
@dgastonochoa please address the failed CI checks

@erwango please revisit

**Comment by dgastonochoa** [comment]
Unfortunately, I won't have time to keep working on this in the short term. I still would like to give it a try, so maybe I re-open this in a few months. I will close it for now, to avoid confusions. Thanks.

**Pull request closed without merging**
