### PR TITLE
net: net_app is enabled with CONFIG_NET_APP

### PR DESCRIPTION
**Pull request by nashif**
Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

**Review by pfalcon — CHANGES_REQUESTED** [review]
Despite Jukka's initial approval, I don't think this change is enough. prj.conf's for specific apps still have "CONFIG_NET_APP_SETTINGS=y" lines, not "CONFIG_NET_APP=y", so we either need to update them all, or trace back to use of CONFIG_NET_APP_SETTINGS.

**Review by pfalcon — COMMENTED** [review]
Actually, disregard my previous comment - there're both CONFIG_NET_APP_SETTINGS and CONFIG_NET_APP in use.

**Review by pfalcon — APPROVED** [review]

**Comment by pfalcon** [comment]
And there doesn't seem to be a way to just remove "changes requested" flag, the only option seems to be set it to "approved", what I did.

**Review by pfalcon — CHANGES_REQUESTED** [review]
Well, this patch breaks e.g. echo_server, so needs more work, e.g. adding CONFIG_NET_APP=y for it.

**Comment by pfalcon** [comment]
Right, echo_server and few other broken samples are also reported by shippable.

**Comment by nashif** [comment]
needs to be redone.

**Pull request closed without merging**
