### PR TITLE
boards: nxp: Switch MCUBoot FW Update mode to Swap & Move

### PR DESCRIPTION
**Pull request by butok**
Switch the default MCUBoot FW Update mode from Swap & Scratch to more preferable Swap & Move for the rest of NXP MCUs. Other NXP MCU platforms have been already switched. 
Delete the scratch partition. Save RAM & ROM.

### CODE REVIEW

**Comment by Laczen** [comment]
@butok, thanks for the PR. IIRC there are 2 possible ways to define partitions for the swap-move in mcuboot:
1. Define image0 partition one erase-block larger than image1 partition,
2. Define image0 and image1 partitions equal but leave one erase-block unused at the end of image0 partition.

The defines provided do not follow this requirement, this might lead to problems with larger images. Have you tested if the definitions work for large images ?

**Comment by butok** [comment]
> @butok, thanks for the PR. IIRC there are 2 possible ways to define partitions for the swap-move in mcuboot:
> 
> 1. Define image0 partition one erase-block larger than image1 partition,
> 2. Define image0 and image1 partitions equal but leave one erase-block unused at the end of image0 partition.
> 
> The defines provided do not follow this requirement, this might lead to problems with larger images. Have you tested if the definitions work for large images ?

Thanks for pointing this out.
I just went through other .dts platforms without a scratch slot. And all the ones I've seen have the same size for slot0 and slot1. So I'd rather be consistent and stay with option (2).

**Comment by Laczen** [comment]
> > @butok, thanks for the PR. IIRC there are 2 possible ways to define partitions for the swap-move in mcuboot:
> > 
> > 1. Define image0 partition one erase-block larger than image1 partition,
> > 2. Define image0 and image1 partitions equal but leave one erase-block unused at the end of image0 partition.
> > 
> > The defines provided do not follow this requirement, this might lead to problems with larger images. Have you tested if the definitions work for large images ?
> 
> Thanks for pointing this out. I just went through other .dts platforms without a scratch slot. And all the ones I've seen have the same size for slot0 and slot1. So I'd rather be consistent and stay with option (2).

IMO many examples for other dts platforms might not be correct and users have not discovered this problem because their images are small. It is ok to go with option 2 but add some remark in the dts that there is a "unavailable" erase-block.

**Comment by butok** [comment]
> > > @butok, thanks for the PR. IIRC there are 2 possible ways to define partitions for the swap-move in mcuboot:
> > > 
> > > 1. Define image0 partition one erase-block larger than image1 partition,
> > > 2. Define image0 and image1 partitions equal but leave one erase-block unused at the end of image0 partition.
> > > 
> > > The defines provided do not follow this requirement, this might lead to problems with larger images. Have you tested if the definitions work for large images ?
> > 
> > 
> > Thanks for pointing this out. I just went through other .dts platforms without a scratch slot. And all the ones I've seen have the same size for slot0 and slot1. So I'd rather be consistent and stay with option (2).
> 
> IMO many examples for other dts platforms might not be correct and users have not discovered this problem because their images are small. It is ok to go with option 2 but add some remark in the dts that there is a "unavailable" erase-block.

It should be part of MCUBoot/imagetool documentation, not dts.
Also, imagetool should do calculations and reserve place for header/tails/status areas.

**Comment by danieldegrasse** [comment]
> Also, imagetool should do calculations and reserve place for header/tails/status areas.

@butok On the K64F, I tried loading an image padded to 25680 bytes. With the 512 byte header, and 432 byte trailer, the image comes out to 26624 bytes. This should fill the entire slot on the K64F. I'm able to upgrade to this image using the DFU mode in MCUBoot without any issues, but the imgtool image does not complain. Based on my understanding of the MCUBoot swap algorithm, this image should be too large, right?

I tested with the following script:
```
# Build and flash MCUBoot
west build -p always -b frdm_k64f -d build-bootloader \
        ../bootloader/mcuboot/boot/zephyr/ \
        -DCONFIG_BOOT_USB_DFU_WAIT=y
west flash -d build-bootloader
# Create hello world image of max slot size
west build -p always -b frdm_k64f samples/hello_world/ \
        -DCONFIG_BOOTLOADER_MCUBOOT=y -d build-img1
truncate -s 25680 build-img1/zephyr/zephyr.bin
imgtool sign --pad -S 26624 --align 1 -k ../bootloader/mcuboot/root-rsa-2048.pem \
        -H 512 -v 0.0.0 \
        build-img1/zephyr/zephyr.bin build-img1/zephyr/zephyr.signed.bin
west flash -d build-img1 --bin-file build-img1/zephyr/zephyr.signed.bin
# Create synchronization sample of max slot size
west build -p always -b frdm_k64f samples/synchronization/ \
        -DCONFIG_BOOTLOADER_MCUBOOT=y -d build-img2
truncate -s 25680 build-img2/zephyr/zephyr.bin
imgtool sign --pad -S 26624 --align 1 -k ../bootloader/mcuboot/root-rsa-2048.pem \
        -H 512 -v 0.0.0 \
        build-img2/zephyr/zephyr.bin build-img2/zephyr/zephyr.signed.bin
# Reset board, and use dfu-util to update
echo "Press reset switch to enter bootloader..."
sleep 20
# Use dfu-util to upgrade
sudo dfu-util -D build-img2/zephyr/zephyr.signed.bin  -a 1
```

**Comment by butok** [comment]
Mr. Brown:
**"I would discourage you from using a scratch partition...
I really need to go through and remove the scratch partitions from the existing DTS files, as people keep copying them...
I really, really, would like people to stop using swap-scratch."**

So in this commit we are switching from the swap-scratch to move mode.
Please all reviewer +vote to finish the moving. 

Later, we can improve it by +-sector size and/or change imgtool behavior.

**Comment by danieldegrasse** [comment]
> "I would discourage you from using a scratch partition...
I really need to go through and remove the scratch partitions from the existing DTS files, as people keep copying them...
I really, really, would like people to stop using swap-scratch."

Agree here- swap move wear levels, which is a large benefit. However, I agree with @Laczen- if we are going to move boards over to swap move, we should follow the best possible partition allocation (from [MCUBoot design documents](https://github.com/mcu-tools/mcuboot/blob/main/docs/design.md#swap-without-using-scratch)):

>  Therefore the most memory-size-effective slot layout is when the primary slot is exactly one sector larger than the secondary slot, although same-sized slots are allowed as well

**Comment by butok** [comment]
> > "I would discourage you from using a scratch partition...
> > I really need to go through and remove the scratch partitions from the existing DTS files, as people keep copying them...
> > I really, really, would like people to stop using swap-scratch."
> 
> Agree here- swap move wear levels, which is a large benefit. However, I agree with @Laczen - if we are going to move boards over to swap move, we should follow the best possible partition allocation (from [MCUBoot design documents](https://github.com/mcu-tools/mcuboot/blob/main/docs/design.md#swap-without-using-scratch)):
> 
> > Therefore the most memory-size-effective slot layout is when the primary slot is exactly one sector larger than the secondary slot, although same-sized slots are allowed as well

Updated: Slot 0 now has one additional sector, for use with the swap move algorithm.

**Review by danieldegrasse — APPROVED** [review]
Thanks for tackling this improvement!

**Review by dleach02 — APPROVED** [review]
Thanks @butok

**Pull request merged**
