### PR TITLE
lib: posix: eventfd: support build with !POSIX_API

### PR DESCRIPTION
**Pull request by mniestroj**
Just change include path to support build with CONFIG_POSIX_API=n.

Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>

### CODE REVIEW

**Comment by pfalcon** [comment]
It's nice to see this doesn't fail existing tests. But to ensure that this actually works, we actually should build eventfd with both POSIX_API=y and POSIX_API=n.

I also don't agree that this bug, the original discussion was about having this as POSIX subsys feature. If it works without POSIX_API=y defined - fine, but if not (to be proven by the test mods mentioned above) - it's still works per the spec. (And the whole idea is that supporting exponential number of configurations is, well, hard). Recasting as "enhancement".

**Comment by mniestroj** [comment]
@pfalcon What are your suggestions about new test for POSIX_API=n? Should we add entirely new `tests/posix/eventfd_no_posix_api/` or change implementation of `tests/posix/eventfd/` to use Zephyr API for creating threads and using `zsock_close()` (which would allow us to compile with POSIX_API=n and POSIX_API=y)?

The reason why I have labeled this PR as "bug" was that Kconfig allowed to select EVENTFD without POSIX_API. eventfd actually works without POSIX_API, but the only problem is bad include path that this PR tries to fix.

**Comment by pfalcon** [comment]
@mniestroj 

> What are your suggestions about new test for POSIX_API=n? 

No, it's not about new test, it's about new build config for one of (probably just one at all?) eventfd test. Similar how we test socket samples both with POSIX_API=y and POSIX_API=n: https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/net/sockets/sntp_client/sample.yaml#L9

**Comment by mniestroj** [comment]
> @mniestroj
> 
> > What are your suggestions about new test for POSIX_API=n?
> 
> No, it's not about new test, it's about new build config for one of (probably just one at all?) eventfd test. Similar how we test socket samples both with POSIX_API=y and POSIX_API=n: https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/net/sockets/sntp_client/sample.yaml#L9

That is exactly what I meant with:
> change implementation of tests/posix/eventfd/ to use Zephyr API for creating threads and using zsock_close() (which would allow us to compile with POSIX_API=n and POSIX_API=y)?

So what about `pthread_*()`, etc.? Those are not available with POSIX_API=n. Should I convert those to `k_thread_*()` counterparts for this test?

**Comment by pfalcon** [comment]
> So what about pthread_*(), etc.? Those are not available with POSIX_API=n. Should I convert those to k_thread_*() counterparts for this test?

Ah, sorry, I don't know. That's where complexity of maintaining this stuff comes from. And based on my experience maintaining that duality for sockets, you could hear my faint hint: "Maybe just don't?". 

But otherwise yes, you'd need to duplicate a test then. Feel free to make it simple, like devoid of any threading at all. I'd even say we could look at the direction of the eventfd sample, which is written in exactly this way (thread-less), but: a) it currently lack sample.yaml at all - my fault, let me fix it in next couple of days; b) that sample is specifically intended to show compatibility with Linux, and I'd prefer to keep it clean from #ifdef mess. But feel free to copy logic from there into a new, simple/short test.

**Comment by pfalcon** [comment]
> a) it currently lack sample.yaml at all - my fault, let me fix it in next couple of days

Submitted: https://github.com/zephyrproject-rtos/zephyr/pull/26099 . Note that this reminded me of my biggest concern with eventfd - that it requires CONFIG_NETWORKING=y, which in turn pulls stuff like SLIP, which then requires UART_INTERRUPT_DRIVEN, which isn't even implemented for all archs/platforms, so breaks the build. @tsvehagen, would be nice to do something about this dependency tail.

**Comment by tsvehagen** [comment]
> > a) it currently lack sample.yaml at all - my fault, let me fix it in next couple of days
> 
> Submitted: #26099 . Note that this reminded me of my biggest concern with eventfd - that it requires CONFIG_NETWORKING=y, which in turn pulls stuff like SLIP, which then requires UART_INTERRUPT_DRIVEN, which isn't even implemented for all archs/platforms, so breaks the build. @tsvehagen, would be nice to do something about this dependency tail.

Agree, lets get rid of that dependency. The problem is actually the `net/socket.h` file. When including that without having networking support, this is what happens.

```
In file included from /home/tsvehagen/devel/zephyrproject/zephyr/include/net/net_l2.h:15,
                 from /home/tsvehagen/devel/zephyrproject/zephyr/include/net/net_if.h:29,
                 from /home/tsvehagen/devel/zephyrproject/zephyr/include/net/net_context.h:27,
                 from /home/tsvehagen/devel/zephyrproject/zephyr/include/net/dns_resolve.h:17,
                 from /home/tsvehagen/devel/zephyrproject/zephyr/include/net/socket.h:27,
                 from /home/tsvehagen/devel/zephyrproject/zephyr/lib/posix/eventfd.c:12:
/home/tsvehagen/devel/zephyrproject/zephyr/include/net/buf.h:785:20: error: 'CONFIG_NET_BUF_USER_DATA_SIZE' undeclared here (not in a function)
```

So one way to fix it is to have `#if IS_ENABLED(CONFIG_SOCKET)` at some places in `eventfd.c`. Another way is to make it possible to include `net/socket.h` without having networking support.

@jukkar What is your view on the `CONFIG_NET_BUF_USER_DATA_SIZE` in `net/buf.h`? Does it make sense to be able to include `net/buf.h` while having `CONFIG_NET_BUF=n`?

**Comment by jukkar** [comment]
> Does it make sense to be able to include `net/buf.h` while having `CONFIG_NET_BUF=n`?

We should be able to include `net/buf.h` even if net_buf's are not in use. As the functionality provided by net_buf API is not in use, inclusion of net/buf.h would be a no-op in this case.

**Comment by tsvehagen** [comment]
@pfalcon When https://github.com/zephyrproject-rtos/zephyr/pull/26138 is merged, it should be possible to build `samples/posix/eventfd` with `CONFIG_NETWORKING=n`.

**Comment by mniestroj** [comment]
@pfalcon 

> But otherwise yes, you'd need to duplicate a test then. Feel free to make it simple, like devoid of any threading at all. I'd even say we could look at the direction of the eventfd sample, which is written in exactly this way (thread-less), but: a) it currently lack sample.yaml at all - my fault, let me fix it in next couple of days; b) that sample is specifically intended to show compatibility with Linux, and I'd prefer to keep it clean from #ifdef mess. But feel free to copy logic from there into a new, simple/short test.

I have reused part of `tests/posix/eventfd/`, as it is already in "ztest style". I've also replaced `close()` with `zsock_close()` and didn't use test cases with threads. As a result both POSIX_API=n and POSIX_API=y are tested. I hope that overall this is what you had in mind ;)

**Review by pfalcon — APPROVED** [review]
@mniestroj, looks good, thanks!

**Review by tsvehagen — APPROVED** [review]

**Pull request merged**
