### PR TITLE
LE Audio: broadcast callbacks

### LINKED ISSUE #75252: Bluetooth: BAP: Add broadcast sink/source callback structs
**Is your enhancement proposal related to a problem? Please describe.**
Operations on the broadcast sink and sources affect an entire BIG. 
For example, if you create a broadcast source with 4 BIS, they will all be created and started at the same time (and with a single HCI event), but in Zephyr they are treated as 4 individual streams. 

In some cases such as stopping a broadcast sink or source followed by a delete, you will today need to wait for each stream to be stopped, before you can delete the underlying structure. Having set of callbacks that affect entire broadcast sink or sources, rather than the individual streams, will be useful here, as you only need to wait for a single callback (and can even do the delete operation in that callback). 

**Describe the solution you'd like**
Create a struct for callbacks for broadcast sources and a struct for broadcast sinks. 
The callbacks in these struct should reflect state changes in the source and sink, such as `deleted`, `configured`, `stopped` and `started`.

**Describe alternatives you've considered**
N/A

**Additional context**
It may make sense to first implement this at the ISO layer, and then simply use the BIG callbacks from ISO to trigger the BAP callbacks.

### PR DESCRIPTION
**Pull request by Thalley**
Add callbacks that affect the entire broadcast groups

fixes https://github.com/zephyrproject-rtos/zephyr/issues/75252

### CODE REVIEW

**Comment by Thalley** [comment]
There is dependencies in the commits, but this PR can split into multiple smaller ones if requested by reviewers

**Review by kruithofa — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by kruithofa — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Comment by Thalley** [comment]
Converted to draft until CI issue is fixed

**Comment by Thalley** [comment]
Confirmed to be a controller issue:

**Comment by Thalley** [comment]
> Confirmed to be a controller issue:
> 
> This is the valgrind report on the segfault:
> 
> ```
> d_00: @00:00:26.415894  Stopping broadcast sink 0x853f9e0
> d_00: @00:00:26.415894  [00:00:26.415,893] <err> bt_bap_broadcast_sink: bt_bap_broadcast_sink_stop: sink->big 0x853f9e0 0x850a420
> ==148372== Thread 8:
> ==148372== Jump to the invalid address stated on the next line
> ==148372==    at 0x0: ???
> ==148372==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
> ==148372== 
> ==148372== 
> ==148372== Process terminating with default action of signal 11 (SIGSEGV)
> ==148372==  Bad permissions for mapped region at address 0x0
> ==148372==    at 0x0: ???
> ==148372==
> ```
> 
> The callstack is:
> 
> ```
> 0x0	
> isoal_rx_append_to_sdu() at subsys/bluetooth/controller/ll_sw/isoal.c:696 0x8354543	
> isoal_rx_unframed_consume() at subsys/bluetooth/controller/ll_sw/isoal.c:954 0x8355530	
> isoal_rx_pdu_recombine() at subsys/bluetooth/controller/ll_sw/isoal.c:1,422 0x8356b37	
> encode_node() at subsys/bluetooth/controller/hci/hci_driver.c:511 0x83014fa	
> process_node() at subsys/bluetooth/controller/hci/hci_driver.c:575 0x830163a	
> recv_thread() at subsys/bluetooth/controller/hci/hci_driver.c:721 0x830193a	
> ```

Just a reminder @cvinayak - Not sure if we ever created a GH issue for this

**Review by kruithofa — APPROVED** [review]

**Review by pin-zephyr — APPROVED** [review]
LGTM

**Pull request merged**
