### PR TITLE
drivers: flash: nrfx: Modify flash address validation

### PR DESCRIPTION
**Pull request by adamkondraciuk**
Modifications in 'is_regular_addr_valid()' function which didn't work properly
when flash base address was different than 0x00000000.
Added calculating address bounds with respect to flash base address.

Signed-off-by: Adam Kondraciuk <adam.kondraciuk@nordicsemi.no>

### CODE REVIEW

**Review by nvlsianpu — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
Looks ok to me

**Comment by ioannisg** [comment]
@adamkondraciuk could you please rebase the PR onto zephyr/master?

**Review by ioannisg — CHANGES_REQUESTED** [review]
can't be merged, now

**Comment by nvlsianpu** [comment]
Patch was already merged in #19796

**Pull request closed without merging**
