### PR TITLE
net: ptp: extract PTP interfaces outside gPTP subsys under NET_L2_PTP

### PR DESCRIPTION
**Pull request by alsrgv**
As per #38352, we would like to start building out PTP (IEEE 1588) support for superset of gPTP functionality in Zephyr. This is the first step to abstract away some key interfaces from NET_GPTP umbrella to NET_L2_PTP.

Signed-off-by: Alex Sergeev <asergeev@carbonrobotics.com>

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Looks reasonable, couple of comments:

* Please change the commit subject to "net: ptp: ...."
* The commit message line length should be around 70 chars. More details at https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines
* Please split the commit to at least two parts. One for the generic changes, and the other(s) for driver changes. Also please change other drivers than mcux (even if you are only interested in NXP one) so that the other drivers do not bitrot. Each driver change could also go to its own commit for easier review.

**Comment by alsrgv** [comment]
@jukkar, thanks for the feedback!

I've reformatted the commits to general PTP code and `eth_mcux` driver.  The two remaining drivers are `eth_sam_gmac` and `eth_native_posix`.

I'd appreciate guidance on updating remaining two drivers - they both timestamp just a subset of PTP packets, while `eth_mcux` and `eth_stm32` that we're working on timestamp all PTP packets.

I can attempt to update `eth_sam_gmac`, but since I don't have a dev board, I don't have a way to test it.

Are changes like this typically done by updating all the drivers in a single PR, or, for backwards compatible changes like this one do drivers get updated as needed by component owners or parties that use those boards?

**Comment by jukkar** [comment]
> I've reformatted the commits to general PTP code and `eth_mcux` driver. The two remaining drivers are `eth_sam_gmac` and `eth_native_posix`.
> 
> I'd appreciate guidance on updating remaining two drivers - they both timestamp just a subset of PTP packets, while `eth_mcux` and `eth_stm32` that we're working on timestamp all PTP packets.
> 
> I can attempt to update `eth_sam_gmac`, but since I don't have a dev board, I don't have a way to test it.
> 
> Are changes like this typically done by updating all the drivers in a single PR, or, for backwards compatible changes like this one do drivers get updated as needed by component owners or parties that use those boards?

If you do not have the hw, then changing the driver in a drastic way is problematic as you cannot test the changes. Anyway, the most important thing here is that the driver compiles ok, so if you are changing something in core PTP functionality, you need to make sure that the driver still compiles and works properly and there are no regressions.

**Comment by alsrgv** [comment]
I've verified that `eth_sam_gmac` driver compiles by running `west build -p auto -b sam_e70_xplained samples/net/gptp` and I've verified `eth_mcux` driver using a dev kit.

The change introduced here is incremental and backwards compatible (aside from internal `net_pkt_*_ptp` rename) - it introduces `NET_L2_PTP` as a configuration layer before `NET_GPTP` and allows future development of PTP subsystem that will cover larger scope of IEEE 1588 standard than gPTP does.

Code that currently uses `NET_GPTP` can still do that freely, and can be incrementally decomposed into common `NET_L2_PTP` and `NET_GPTP` parts down the line.

Is there anything else that should be done to this patch before it can proceed?

**Review by jukkar — APPROVED** [review]
LGTM, this is a good start for IEEE 1588 support so +1

**Review by rlubos — APPROVED** [review]

**Review by hakehuang — CHANGES_REQUESTED** [review]
there is a sample gptp need update as well, besides, the gptp is based on 8021AS-2020, which is different from IEEE 1588-2008, do we plan to support both of them? with unified interfaces?

**Comment by alsrgv** [comment]
Hi @hakehuang,

According to https://en.wikipedia.org/wiki/Time-Sensitive_Networking#Time_Synchronization:

> IEEE 802.1AS is a tightly constrained subset of IEEE 1588 with sub-microsecond precision and extensions to support synchronisation over WiFi radio (IEEE 802.11). The idea behind this profile is to narrow the huge list of different IEEE 1588 options down to a manageable few critical options that are applicable to home networks or networks in automotive or industrial automation environments.

My thought was to make `NET_GPTP` extend `NET_L2_PTP` which paves way to build out IEEE 1588 support for L2 layer. This support is not built out yet, so I don't believe renaming gptp example or shell commands is appropriate yet.

Does this address your concern?

**Comment by hakehuang** [comment]
> not built out yet, so I don't believe renaming gptp example or shell commands is appropriate yet.

but this PR will make the gptp sample not work. so you will have further PR to fix this?

**Review by hakehuang — APPROVED** [review]

**Comment by alsrgv** [comment]
@hakehuang, why do you believe this change breaks gptp sample? I just tested gptp sample on FRDM-K64F with this change and it worked.

This change does not deprecate use of `NET_GPTP`. Instead, it introduces another configurability layer, `NET_L2_PTP` which corresponds to IEEE 1588-2008, layer 2. Selecting `NET_GPTP` automatically selects `NET_L2_PTP`.

**Comment by hakehuang** [comment]
> @hakehuang, why do you believe this change breaks gptp sample? I just tested gptp sample on FRDM-K64F with this change and it worked.

sorry my bad, the gptp is not impacted. Thanks to double check.

**Comment by alsrgv** [comment]
Anything else needed for this PR before it can be merged? I'm planning to open a PR to add PTP HW timestamping support to STM32 in a next few of days, and it depends on this PR to be merged.

**Comment by rlubos** [comment]
@alsrgv Zephyr is currently in a code-freeze stage, since this PR is not a bugfix it needs to wait for the release to be merged.

**Comment by alsrgv** [comment]
@rlubos, I see, thanks. Is there a planned timeline for code freeze end?

**Comment by rlubos** [comment]
@alsrgv Please see https://github.com/zephyrproject-rtos/zephyr/wiki/Program-Management#actual-and-planned-milestone-dates

**Comment by alsrgv** [comment]
Thanks!

**Pull request merged**
