### PR TITLE
samples: boards: mimxrt595_evk_cm33: system_off: misc cleanups

### PR DESCRIPTION
**Pull request by gmarull**
- Remove unnecessary includes
- Remove redundant definitions (sample is not portable anyway)
- Use printf
- Check for device readiness
- Do not check for zero ticks (not possible for the given timeout/driver), also, driver should likely error for such case anyway
- Check for all error codes

### CODE REVIEW

**Review by danieldegrasse — COMMENTED** [review]
Can you add `CONFIG_REGULATOR=y` to the `prj.conf` file? Testing this sample it seems that it is not being turned on, but it should be (I suspect that this was also broken before this PR). With those changes this sample works for me

**Comment by gmarull** [comment]
> Can you add `CONFIG_REGULATOR=y` to the `prj.conf` file? Testing this sample it seems that it is not being turned on, but it should be (I suspect that this was also broken before this PR). With those changes this sample works for me

hmm but the application doesn't use the regulator API, so the setting must be enabled somewhere else. where/how is it being used?

**Comment by danieldegrasse** [comment]
> hmm but the application doesn't use the regulator API, so the setting must be enabled somewhere else. where/how is it being used?

This board has the PCA9420 on it- that regulator can have the voltage mode selected via two input pins. On the RT595 EVK, those pins are routed to a few special signals on the SOC that will toggle when the part enters low power mode. So while the sample does not use the regulator API, power management on this board requires the regulator in order to function. It looks like what is needed here is to default `CONFIG_REGULATOR` to enabled at the board level when `CONFIG_POWEROFF=y`, just as we do when `CONFIG_PM=y`: https://github.com/zephyrproject-rtos/zephyr/blob/33c922a771aee12e329de1a10c6fc65b0e01ed4a/boards/arm/mimxrt595_evk/Kconfig.defconfig#L32

**Comment by gmarull** [comment]
> > hmm but the application doesn't use the regulator API, so the setting must be enabled somewhere else. where/how is it being used?
> 
> This board has the PCA9420 on it- that regulator can have the voltage mode selected via two input pins. On the RT595 EVK, those pins are routed to a few special signals on the SOC that will toggle when the part enters low power mode. So while the sample does not use the regulator API, power management on this board requires the regulator in order to function. It looks like what is needed here is to default `CONFIG_REGULATOR` to enabled at the board level when `CONFIG_POWEROFF=y`, just as we do when `CONFIG_PM=y`:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/33c922a771aee12e329de1a10c6fc65b0e01ed4a/boards/arm/mimxrt595_evk/Kconfig.defconfig#L32

Thanks for the details, added a new patch enabling regulator if poweroff is also enabled.

**Review by danieldegrasse — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
