### PR TITLE
post built html to the cloud

### PR DESCRIPTION
**Pull request by nashif**

### CODE REVIEW

**Comment by dbkinder** [comment]
Curious, why do you want the doxygen-generated API documentation?  We had turned that off over a year ago in favor of the sphinx/breathe generated docs.

**Comment by nashif** [comment]
> Curious, why do you want the doxygen-generated API documentation? We had turned that off over a year ago in favor of the sphinx/breathe generated docs.

Because the doxygen module structure is a mess and this is the best way to verify changes to doxygen and how the modules relate to each other.

**Comment by nashif** [comment]
output:
http://zephyr-logs.s3-website-us-east-1.amazonaws.com/pull-requests/zephyrproject-rtos/zephyr/1013/doc
and
http://zephyr-logs.s3-website-us-east-1.amazonaws.com/pull-requests/zephyrproject-rtos/zephyr/1013/api/

**Comment by dbkinder** [comment]
If we're redesigning the API docs for the project, let's open a Jira and define the plan. Is the intention to focus on use of the doxygen-generated pages and phase out the Sphinx/breathe pages?

-- david kinder

On Aug 6, 2017, at 7:11 AM, Anas Nashif <notifications@github.com<mailto:notifications@github.com>> wrote:


Curious, why do you want the doxygen-generated API documentation? We had turned that off over a year ago in favor of the sphinx/breathe generated docs.

Because the doxygen module structure is a mess and this is the best way to verify changes to doxygen and how the modules relate to each other.

**Comment by nashif** [comment]
> If we're redesigning the API docs for the project, let's open a Jira and define the plan. Is the intention to focus on use of the doxygen-generated pages and phase out the Sphinx/breathe pages?

No, again, this just spits the output in HTML and makes it available for viewing, Nothing else changes, I did not change any output or replaced anything. The Doxygen output makes it possible to view API documentation related changes and allows for better structuring which is otherwise not possible.

While we are using RST for all of this, the doxygen structure needs to be sane.

**Comment by dbkinder** [comment]
Oh, I was assuming you wanted to link the doxygen output into our doc navigation somewhere, and potentially replace our API docs with the doxygen output.   The former would be an OK thing, the latter would require more serious planning.

**Review by dbkinder — APPROVED** [review]

**Comment by nashif** [comment]
> Oh, I was assuming you wanted to link the doxygen output into our doc navigation somewhere, and potentially replace our API docs with the doxygen output. The former would be an OK thing, the latter would require more serious planning.

Yes, agree. The bulk of this PR is to give you and others a way to view the HTML output, something you wanted some time ago...

**Comment by dbkinder** [comment]
Ah, so this is "artifact" doc output for every shippable run? Nice. How long will it stay around?

-- david kinder

On Aug 6, 2017, at 9:49 AM, Anas Nashif <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, I was assuming you wanted to link the doxygen output into our doc navigation somewhere, and potentially replace our API docs with the doxygen output. The former would be an OK thing, the latter would require more serious planning.

Yes, agree. The bulk of this PR is to give you and others a way to view the HTML output, something you wanted some time ago...

**Pull request merged**
