### PR TITLE
Fix a ST LSM6DSO IMU driver bug and add support for LSM6DSO32

### PR DESCRIPTION
**Pull request by xyzzy42**
This adds support for the ST LSM6DSO32 IMU to the existing driver.  It's identical to the LSM6DSO other than an accelerometer with twice the range.

I also noticed that the driver was double endian converting the data, likely unnoticed since most systems are little-endian, and fixed that.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
@avisconti could you please take a look?

**Comment by theol0403** [comment]
I'm new to zephyr, but I tried giving this a shot (I am using this sensor) but ran into some issues.

I cherry-picked the three commits, and changed my dts overlay spi sensor to `compatible = "st,lsm6dso32";`. 
However, I then get the warning ` warning: #warning "LSM6DSO driver enabled without any devices"` and the driver does not start.

I don't think this PR enables some Kconfig `CONFIG_LSM6DSO`, so I'm confused if I did anything wrong.

**Review by MaureenHelm — APPROVED** [review]
> I'm new to zephyr, but I tried giving this a shot (I am using this sensor) but ran into some issues.
> 
> I cherry-picked the three commits, and changed my dts overlay spi sensor to compatible = "st,lsm6dso32";.
> However, I then get the warning warning: #warning "LSM6DSO driver enabled without any devices" and the driver does not start.
>
> I don't think this PR enables some Kconfig CONFIG_LSM6DSO32, so I'm confused if I did anything wrong.

Is the compatible node and its parent bus enabled (`status = okay`) in your devicetree?

**Comment by trentp-igor** [comment]
There is just the one driver, `CONFIG_LSM6DSO`.

The issue is because of this (in the commit message):

> The difference is detected by using "st,lsm6dso32" as the first compatible entry, **followed by "st,lsm6dso"**.

The dts standard for handling a device which is a backward compatible version of another device, is to list multiple compatible entries.  The first is the most specific entry and the last is the most generic.  Examples:

```
dts/arm/st/l5/stm32l5.dtsi:                   compatible = "st,stm32-lpuart", "st,stm32-uart";
boards/shields/x_nucleo_eeprma2/x_nucleo_eeprma2.overlay:             compatible = "st,m95xxx", "atmel,at25";
dts/arm/nxp/nxp_imx7d_m4.dtsi:                        compatible = "fsl,imx7d-pwm", "fsl,imx27-pwm";
```

**Review by avisconti — APPROVED** [review]
LGTM
(good catch also for the BE/LE part. I guess there might be other issues like that in other sensors using HAL v2.00)

**Pull request merged**
