### PR TITLE
net: lib: http: Correct http_client edge-case behavior

### PR DESCRIPTION
**Pull request by glarsennordic**
Correct various small edge-case behaviors that have been accidentally introduced in the http_client.

- http_client_req no longer incorrectly returns -ETIMEDOUT on NULL HTTP resonse. -ETIMEDOUT is now only returned when the underlying TLS socket times out.
- http_client_req now returns -ECONRESET upon incomplete (but non-NULL) HTTP response. The request callback is no longer called in this case (as with any other error state).
- http_wait_data has been refactored slightly to increase clarity.

### CODE REVIEW

**Comment by glarsennordic** [comment]
@jukkar Do you mind testing this with your conn_mgr PR to see if it meets your needs? I am pretty sure this will return -ETIMEDOUT in the scenario you need it to, while also returning http status zero in the situation I need it to

**Comment by glarsennordic** [comment]
Related PR which this PR will possibly replace:
https://github.com/zephyrproject-rtos/zephyr/pull/70816

**Review by jukkar — COMMENTED** [review]
LGTM, just fix the compliance issue and we should be good to go.

**Review by rlubos — DISMISSED** [review]
Looks good, can we move it out of draft?

**Review by jukkar — DISMISSED** [review]

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Pull request merged**
