### PR TITLE
boards: fix openocd deprecated configuration

### PR DESCRIPTION
**Pull request by it-klinger**
Replace deprecated settings:
  adapter_khz  -->  adapter speed
  adapter_nsrst  -->  adapter srst delay

Tested on olimex stm32_e407 board with olimex arm-usb-tiny-h adapter

### CODE REVIEW

**Comment by it-klinger** [comment]
It seems that the PR is waiting for another reviewer. What can I do to get another one to continue with the PR?

**Comment by decsny** [comment]
@erwango a lot of the boards changed are STM, can you help to review this PR

**Comment by erwango** [comment]
> @erwango a lot of the boards changed are STM, can you help to review this PR

Lot of boards are using STM32 SoCs, but only one of them is from ST and this is a rarity. So I'm not able to test.

**Comment by it-klinger** [comment]
How can we continue with this PR?
Should we leave the wrong settings in openocd.cfg in the repo because of missing reviewers?

**Comment by erwango** [comment]
If at least one maintainer or contributors of those boards could confirm this is not causing regression, it would be ok I think.
"Just need" to ping one

**Comment by it-klinger** [comment]
@sylvioalves Could you please confirm, that this PR is not expected to produce regressions, please?
Do you need some more information from my side for this?

**Comment by it-klinger** [comment]
@dleach02  Could you please confirm, that this PR is not expected to produce regressions, please?
Do you need some more information from my side for this?
I contact you because of board "boards/nxp/lpcxpresso11u68/" which is afected by this PR

**Review by ajarmouni-st — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by kartben** [comment]
@marekmatej @sylvioalves @LucasTambor @uLipe  can we get a review/+1 from espressif side? Thanks!

**Comment by marekmatej** [comment]
> @marekmatej @sylvioalves @LucasTambor @uLipe can we get a review/+1 from espressif side? Thanks!

@kartben Judging from the config files in Espressif OpenOCD related to the ESP32 targets, the changes in this PR should work fine.

**Review by vaishnavachath — APPROVED** [review]

**Review by marekmatej — APPROVED** [review]

**Pull request merged**
