### PR TITLE
Update of subsystems/registers address offsets for NEORV32 v. 1.9.2

### PR DESCRIPTION
**Pull request by VolodymyrSvintozelskyi**
Currently, the Zephyr project supports the NEORV32 core of version 1.8.6.
Since the release of that version, the Neorv32 memory mapping was changed a few times.
This PR updates the address offsets of different subsystems/registers within Zephyr, to support the latest release of Neorv32, which is 1.9.2.

### CODE REVIEW

**Review by carlocaione — CHANGES_REQUESTED** [review]
Commit message is missing

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
You need to at least also update https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/neorv32/Kconfig.soc

**Comment by fkokosinski** [comment]
Hi, thanks for this PR.

Please note that you have some compliance check issues. You can run the compliance check script locally with: `./scripts/ci/check_compliance.py` in the main directory of the Zephyr repo.

**Comment by henrikbrixandersen** [comment]
Please coordinate your efforts with author of #65627.

**Pull request closed without merging**
