### PR TITLE
dt: Fix DTC warning

### PR DESCRIPTION
**Pull request by SebastianBoe**
DTC is triggering the warning: "Node has a unit name, but no reg
property".

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
We could alternatively disable the warning with -Wno-unit_address_vs_reg .

Any idea what we want to do about this warning? @erwango , @b0661 , @galak ?

Fix or suppress?

**Review by galak — CHANGES_REQUESTED** [review]
We shouldn't add reg to address this warning, look the following commit on how to address:

commit 7b0ce85242414c9391198d953c07e3858b1a11d0
Author: Erwan Gouriou <erwan.gouriou@linaro.org>
Date:   Tue Sep 18 19:45:43 2018 +0200

    boards: dts: Fix dtc warning in stm32 board dts files

**Comment by SebastianBoe** [comment]
Thank you for the feedback, I will apply an equivalent fix.

I actually considered and tested that approach, but (incorrectly) concluded that we wouldn't want to do that for compatibility reasons.

For instance, code that uses GPIO_LEDS_0_GPIO_PIN would need to be ported to use GPIO_LEDS_LEDS_LED_0_GPIO_PIN.

**Comment by galak** [comment]
> For instance, code that uses GPIO_LEDS_0_GPIO_PIN would need to be ported to use GPIO_LEDS_LEDS_LED_0_GPIO_PIN.

most of the GPIO cases dont typically use the GPIO_LEDS_LEDS_LED_0_GPIO_PIN define, but an alias name, so its lets of an issue.

**Comment by SebastianBoe** [comment]
@galak : Fixed.

**Comment by galak** [comment]
> Fix or suppress?

let's fix

**Review by galak — APPROVED** [review]

**Pull request merged**
