### PR TITLE
llext: 64bits fixes

### PR DESCRIPTION
**Pull request by marc-hb**
3 commits.

Fixes LLEXT 64bits compilation errors observed in SOF daily tests first (hence the high priority)
- https://github.com/thesofproject/sof/actions/runs/8210724586/job/22458665825

and then reproduced _without_ SOF in this modified test here:
- https://github.com/zephyrproject-rtos/zephyr/pull/70000

### CODE REVIEW

**Comment by marc-hb** [comment]
The rare `Context switching while holding lock!` failures and panics when running `tests/modules/thrift/ThriftTest/` can't possibly be related to this PR: these tests don't compile `llext.c` at all (I checked).

https://github.com/zephyrproject-rtos/zephyr/actions/runs/8219622840/job/22480353797?pr=70002
https://github.com/zephyrproject-rtos/zephyr/pull/70002/checks?check_run_id=22481802768

```
START - test_multi_exception
testMultiException(Xception, test 1)
testMultiException(Xception2, test 2)
ASSERTION FAIL [arch_irq_unlocked(key) || k_sched_current_thread_query()->base.thread_state & (((1UL << (0))) | ((1UL << (3))))] @ WEST_TOPDIR/zephyr/kernel/include/kswap.h:99
	Context switching while holding lock!
E: RAX: 0x0000000000000004 RBX: 0x00000000001d6910 RCX: 0x0000000000000001 RDX: 0x0000000000000001
E: RSI: 0x0000000000000063 RDI: 0x0000000000196277 RBP: 0x00000000001d9c00 RSP: 0x00000000001d9bd8
E:  R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x0000000000000002 R11: 0x0000000000000000
E: R12: 0x00000000001b0240 R13: 0x0000000000000000 R14: 0x0000000000000000 R15: 0x0000000000000046
E: RSP: 0x00000000001d9bd8 RFLAGS: 0x0000000000000002 CS: 0x0018 CR3: 0x0000000000218000
E: RIP: 0x000000000013e302
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x1b0240 (unknown)
E: Halting system
```

All other tests passed.

**Comment by marc-hb** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/70002/commits/8c757df21daf1a799eecd01887afc2952d313ad3 combined this PR with the new `loader_build` test submitted in #70000. That new `loader_build` test passed on multiple architectures:
https://github.com/zephyrproject-rtos/zephyr/pull/70002/checks?check_run_id=22481802768

Removing the new test now from this PR so it can be reviewed separately in #70000

**Comment by marc-hb** [comment]
> The rare Context switching while holding lock! failures and panics when running tests/modules/thrift/ThriftTest/ can't possibly be related to this PR: these tests don't even compile llext.c at all (I checked).

These did not happen again, just a glitch.
https://github.com/zephyrproject-rtos/zephyr/actions/runs/8223847673/job/22487042759?pr=70002

Concurrency == not deterministic...

**Review by pillo79 — APPROVED** [review]
Thanks for these cleanups! :+1:

**Review by teburd — APPROVED** [review]

**Review by LaurentiuM1234 — APPROVED** [review]
Thanks!

**Comment by marc-hb** [comment]
> What platform was that scheduler failure on?

It was qemu_x86_64 in both cases, I edited my comment above.

**Comment by cfriedt** [comment]
> The rare `Context switching while holding lock!` failures and panics when running `tests/modules/thrift/ThriftTest/` can't possibly be related to this PR: these tests don't even compile `llext.c` at all (I checked).

Yes - apologies for that. It's due to a kind of ad-hoc mutex solution due to the current lack of `std::mutex` support.

Should be fixed soon by https://github.com/zephyrproject-rtos/sdk-ng/pull/735 which adds proper C++ `std::thread`, `std::mutex` support, etc, and has been a very long time in the works.

**Review by cfriedt — APPROVED** [review]

**Comment by marc-hb** [comment]
Thanks @cfriedt , great that a fix is coming soon!

Depending on how frequent this failure is and how soon the fix is coming, having an open bug filed would really save time.

I searched for https://github.com/zephyrproject-rtos/zephyr/issues?q=is%3Aissue++context+switching+while+holding+lock+ but I only found closed bugs.

**Pull request merged**
