### PR TITLE
arch/x86: CONFIG_BOOTLOADER_UNKNOWN renamed to CONFIG_X86_MULTIBOOT

### PR DESCRIPTION
**Pull request by ghost**
The only use of the BOOTLOADER_UNKNOWN config option is on x86, where
it controls whether a multiboot header is embedded in the output.
This patch renames the option to be more descriptive, and makes it
an x86-specific option, rather than a Zephyr top-level option.

This also enables X86_MULTIBOOT by default, since the header only
occupies 12-16 bytes of memory and is (almost always) harmless.

Signed-off-by: Charles E. Youse <charles.youse@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]
LGTM!

**Review by andyross — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by wentongwu — APPROVED** [review]

**Comment by andrewboie** [comment]
something seems to be broken in CI

**Review by nashif — CHANGES_REQUESTED** [review]
this enables CONFIG_X86_MULTIBOOT on all x86 platforms, including quark d2000 and se 1000 where it was not enabled before, is this wanted?

**Comment by gnuless** [comment]
> this enables CONFIG_X86_MULTIBOOT on all x86 platforms, including quark d2000 and se 1000 where it was not enabled before, is this wanted?

I'm not sure I'd say that it's _wanted_, but it just ends up emitting an extra 15 bytes into the text segment, at most.  Do you think it's worth changing their configs for the space savings and/or just for the sake of completeness?  I can do that.

**Comment by nashif** [comment]
> I'm not sure I'd say that it's _wanted_, but it just ends up emitting an extra 15 bytes into the text segment, at most. Do you think it's worth changing their configs for the space savings and/or just for the sake of completeness? I can do that.

Just not to break anything unexpected I would just disable multiboot on those platforms, no need to wake a sleeping giant.

**Comment by gnuless** [comment]
> Just not to break anything unexpected I would just disable multiboot on those platforms, no need to wake a sleeping giant.

Done!

**Review by nashif — APPROVED** [review]

**Pull request merged**
