### PR TITLE
samples: kernel: cycle64: modify default timeout

### LINKED ISSUE #40367: sample: cycle_64 is failing out due to a timeout on 64-bit versions of qemu_x86 and ehl_crb
**Describe the bug**
Sample cycle64 in Kernel should run successfully but it is failing on **64-bit version of qemu_x86 and ehl_crb**. 

What have you tried to diagnose or workaround this issue?
Ran the sample on 32-bit qemu_x86 and it is passing without any issue. 

**To Reproduce**
1. twister -W -p qemu_x86_64 -T samples/kernel/cycle64/  -j 1 -vvv    
                    **or** 
 twister -W -p ehl_crb --device-testing --device-serial /dev/ttyUSB0 -T samples/kernel/cycle64/  --west-flash=/home/ztest/EHL_X86_PXE.sh -j 1

2. See timeout.

**Expected behavior**
```
DEBUG   - QEMU (2771557): Booting from ROM..*** Booting Zephyr OS build v2.7.99-1382-g742412606090  ***
DEBUG   - QEMU (2771557): wrap-around should occur in 42s
DEBUG   - QEMU (2771557): [ddd:hh:mm:ss.0ms]
DEBUG   - QEMU (2771557): [000:00:00:00.000]: cycle: 000000000001fad0
DEBUG   - QEMU (2771557): [000:00:00:42.960]: cycle: 00000001000fd823
DEBUG   - QEMU (2771557): [000:00:01:25.920]: cycle: 00000002001f9a23
DEBUG   - QEMU (2771557): [000:00:02:08.880]: cycle: 00000003002f5c23
DEBUG   - QEMU (2771557): SUCCESS
DEBUG   - QEMU (2771557) complete (passed) after 2.0869383811950684 seconds
DEBUG   - No timeout, return code from QEMU (None): 0
DEBUG   - return code from QEMU (None): 0
```

**Logs and console output**
```
DEBUG   - QEMU (2772183): Booting from ROM..*** Booting Zephyr OS build v2.7.99-1382-g742412606090  ***
DEBUG   - QEMU (2772183): wrap-around should occur in 42s
DEBUG   - QEMU (2772183): [ddd:hh:mm:ss.0ms]
DEBUG   - QEMU (2772183): [000:00:00:00.010]: cycle: 000000000014555c
DEBUG   - QEMU (2772183): [000:00:00:42.980]: cycle: 00000001005cecd4
```

**Environment (please complete the following information):**
 - OS: Fedora
 - Toolchain: SDK 0.13.1
 - Commit SHA: 74241260

### PR DESCRIPTION
**Pull request by cfriedt**
Integration platforms for cycle64 are those that exhibit a "time warp" characteristic - such as `qemu_riscv64` where the application runs to completion almost instantly but the clock says that 14 minutes has passed.

Fast integration tests are good for CI, and so the timeout for integration tests is lowered to 5s.

However, some users have reported that the test fails when run under twister but succeeds under west for non-integration platforms. I've observed the test taking up to 86 seconds on `qemu_cortex_a53`, which is beyond the default 60s timeout allows with twister.

This change should address both cases.

Fixes #40367

### CODE REVIEW

**Comment by cfriedt** [comment]
On my desk, `qemu_x86_64` ended up taking 136s. Would be great if someone else could reproduce.

```
west build -p auto -b qemu_x86_64 -t run samples/kernel/cycle64
```

**Comment by olofj** [comment]
What's the purpose of this sample? Right now, the `timeout()` function doesn't seem to working correctly, but it's not documented what the actual intent of it is.

It calculates a new timeout that is 2^32 ticks away, but then masks off the top 32 bits, so it takes all the way until the 64-bit counter wraps to actually time out. Reducing the number of loops to 2 (to abort right after the cycle counter reaches beyond 32-bit space) doesn't seem like the right thing to do.

Wouldn't the better fix here be to let `timeout()` return the cycle counter beyond 32-bit values, and then just wait on it to wrap as expected?  It's also a lot more valuable to show this for values beyond the 32-bit ones, quitting on the second iteration doesn't do that.

**Comment by nashif** [comment]
@cfriedt  this looks more like a test, not a sample, can you move this to some existing test please?
btw, the sample also fails on m2gl025_miv on main branch.

**Comment by nashif** [comment]
rebase to see why CI did not catch the failure here.

**Comment by cfriedt** [comment]
> @cfriedt this looks more like a test, not a sample, can you move this to some existing test please? btw, the sample also fails on m2gl025_miv on main branch.

A timeout under `twister` I guess? I have not run this test under renode for `m2gl025_miv`. However, it works fine on `qemu_riscv32` (in `twister` and via `west`).

The main reason that this is a sample and not a test, is that if someone were to blanket-run `twister` without `-G`, assuming the average time across `N` boards to run the test was `T` seconds, then `twister` would take `N [boards] * T [s/board]` longer to run than it does today, which I'm guessing nobody wants.

Of course, the amount of time for the test to run successfully in `twister` varies per platform. Therefore, in order to make `twister` succeed, the timeout would need to be at least as long as it takes for the longest timer to wrap around the 32-bit boundary, which is an awfully long time to wait for `SUCCESS`.

**Comment by nashif** [comment]
> The main reason that this is a sample and not a test...

well, this does not make a difference really if you put it under sample, the test is just run exactly the same way. That is not really the point here, but it would better go into tests, it does not qualify as a sample, no docs, and anything here could for example be part of the docs.

If the failures are all timeouts and the test just takes too long to run, then mark it as `slow: True` in the yaml file or limit it to the platforms where results come fast: `platforms_allow: native_posix`, with slow twister will ignore it unless twister is run with `--enable-slow`. 
Right now this test is failing on multiple platforms due to the timeout... 
`integration_platforms` is not the right way to filter the platforms here. The test has to pass without -G, see how it fails here:  https://github.com/zephyrproject-rtos/zephyr/runs/4348498579?check_suite_focus=true

**Comment by cfriedt** [comment]
> > The main reason that this is a sample and not a test...
> 
> well, this does not make a difference really if you put it under sample, the test is just run exactly the same way. That is not really the point here, but it would better go into tests, it does not qualify as a sample, no docs, and anything here could for example be part of the docs.
> 
> If the failures are all timeouts and the test just takes too long to run, then mark it as `slow: True` in the yaml file or limit it to 

Done!

```bash
$ twister --enable-slow -T tests/kernel/timer/cycle64
...
INFO    - Total complete:   30/  30  100%  skipped:   20, failed:    0
INFO    - 16 of 16 test configurations passed (100.00%), 0 failed, 20 skipped with 0 warnings in 143.98 seconds
INFO    - In total 16 test cases were executed, 20 skipped on 30 out of total 407 platforms (7.37%)
INFO    - 15 test configurations executed on platforms, 1 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing xunit report /home/cfriedt/workspace/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/cfriedt/workspace/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
```

**Review by nashif — APPROVED** [review]

**Comment by cfriedt** [comment]
> What's the purpose of this sample? Right now, the `timeout()` function doesn't seem to working correctly, but it's not documented what the actual intent of it is.

Sorry - missed this comment. The `timeout()` function calculates the number of cycles until the next 32-bit wrap-around (which is by definition only 32-bits).

**Pull request merged**
