### PR TITLE
Update overview page for DSP subsystem

### PR DESCRIPTION
**Pull request by cperkulator**
fix table to render properly

Before: 
image

After: 
image

### CODE REVIEW

**Review by stephanosio — CHANGES_REQUESTED** [review]
Thanks for the fix.

Please review the [Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines) and format the commit accordingly.

**Review by yperess — DISMISSED** [review]

**Review by stephanosio — DISMISSED** [review]

**Comment by carlescufi** [comment]
@cperkulator please fix your commit so we can merge this.

**Comment by stephanosio** [comment]
See https://github.com/zephyrproject-rtos/zephyr/actions/runs/3737354789/jobs/6347118165#step:9:26

**Comment by cperkulator** [comment]
@carlescufi The commit should be formatted correctly now. Could you approve the workflow?

**Comment by stephanosio** [comment]
Rebased

**Comment by stephanosio** [comment]
@cperkulator Please use your full name in the commit author field and sign-off: https://github.com/zephyrproject-rtos/zephyr/actions/runs/3865254721/jobs/6588629279#step:9:26

**Review by nashif — DISMISSED** [review]

**Review by stephanosio — DISMISSED** [review]

**Comment by stephanosio** [comment]
CI seemed to be stuck, rebased to retrigger it.

**Review by stephanosio — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Pull request merged**
