### PR TITLE
tests: bsim_bt: edtt tests: Use latest EDTT without the bridge

### PR DESCRIPTION
**Pull request by aescolar**
The latest EDTT does not use the bridge anymore.

### CODE REVIEW

**Comment by aescolar** [comment]
CC @Tronil

**Review by jhedberg — APPROVED** [review]

**Comment by gopiotr** [comment]
If you deleted EDTT bridge then shouldn't you decrease number of devices connected to phy from `-D 3` to `-D 2`?
https://github.com/zephyrproject-rtos/zephyr/blob/070ac366c5278c4b45acd1584875cb35993fc904/tests/bluetooth/bsim_bt/edtt_ble_test_app/tests_scripts/gatt.llcp.sh#L42-L43
https://github.com/zephyrproject-rtos/zephyr/blob/070ac366c5278c4b45acd1584875cb35993fc904/tests/bluetooth/bsim_bt/edtt_ble_test_app/tests_scripts/gatt.sh#L42-L43
https://github.com/zephyrproject-rtos/zephyr/blob/070ac366c5278c4b45acd1584875cb35993fc904/tests/bluetooth/bsim_bt/edtt_ble_test_app/tests_scripts/_controller_tests_inner.sh#L111-L112

BTW I observe, that passing to phy too high number of connected devices probably does not impact on simulation result. Do I understand it correctly?  For example in `_controller_tests_inner.sh` there was passed `-D 4` argument to phy, when even before deleting bridge there were only 3 devices connected to phy (two `nrf52_bsim` devices, and EDTT bridge)? I analyzed quickly `ext_2G4_phy_v1` bsim component and I noticed, that passing to high number of connected devices impact only on creating extra modems, which are just not used in simulation.

**Comment by aescolar** [comment]
Hi @gopiotr , 

>If you deleted EDTT bridge then shouldn't you decrease number of devices connected to phy from -D 3 to -D 2?

The EDTT is using one extra "interface" to the simulation Phy to stall the simulation while it processes (Before the bridge was the one using this extra interface).

You can see that the EDTT transport is also provided a device number `./src/edttool.py -s=${SIMULATION_ID} `**-d=2** `..`
That is that interface.

> .. that passing to phy too high number of connected devices probably does not impact..

Note that if you pass a too high total device number to the Phy it will prevent the simulation from starting. The Phy waits for all devices to connect to the simulation before starting. So it will just wait forever for that device that is not coming.

**Comment by gopiotr** [comment]
@aescolar thank you for the explanation - now it make sense and it is clear for me. I think that after removing bridge it became easier to understand. In the past I wrongly thought that bridge is also directly connected to phy what wasn't true.

Now I realized, that in `_controller_tests_inner.sh` the number of devices is set as `-D 4` because EDTT additionally use `--low-level-device` which is treated as separate fourth device in simulation - I missed it and that's why I thought that it is possible to pass too high number of devices. But now I read this docs: https://github.com/EDTTool/EDTT/blob/main/docs/EDTT_framework_Babblesim.md and it is clear for me how `--low-level-device` works.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
