### PR TITLE
net: ip: lock non-atomic read access to ll address

### LINKED ISSUE #50875: net: ip: race in access to writable net_if attributes
**Describe the bug**

The net_if API may be concurrently accessed by several threads. Write access to certain net_if attributes (notably link-layer address) is therefore guarded by a mutex lock.
    
Locking has only been introduced for write access while non-atomic read access does not seem to be guarded. This seems to create a race condition during concurrent read and write access to net_if attributes unless I'm overlooking something that makes locking unnecessary in this special case...
    
As an aside: Currently all instances of net_if are guarded by a single global lock although there's no danger of race conditions across instances. It may make sense to introduce more granular per-instance locking of net_if rather than global locking.

**To Reproduce**

This bug has been found analytically. A sample patch will be provided that explains what a solution could look like.

**Expected behavior**

Memory that can be written and read concurrently by independent threads should be properly guarded against race conditions.

**Impact**

As the race condition is in code paths that may be executed with high frequency (e.g. net packet code), net packets might be corrupted when updating net_if attributes concurrently.

Example: The link layer address of an interface needs to be changed when switching from extended to short source addresses in the IEEE 802.15.4 protocol after associating to a PAN without taking the interface down for concurrent TX. Socket code will add the source address of a package on-the-fly by accessing the current link-layer address of the interface. Accessing the link-layer address is not safe, IMHO, while it is being written. So packets being created by a TX thread while the RX thread responds to a (dis)association response from a remote coordinator which switches the net_if's link-layer address from extended to short (or the opposite) may corrupt the outgoing packet's link-layer address when RX/TX run on different CPUs or RX get's preempted in the middle of updating the ll address.

**Logs and console output**

n/a

**Environment (please complete the following information):**

current mainline

**Additional context**

I'll attach a patch to this bug report which introduces a partial tentative fix by exposing the net_if mutex via internal API methods. These methods will then be used to exemplify my understanding of read-time locking in some frequently used functions of the net IP stack.
    
The patch is not intended as a fix. Many such fixes would have to be introduced to protect all critical sections with read access to writable parts of the net_if struct unless I'm overlooking something (which is entirely possible!).

Unfortunately this fix seems to introduce enough lag to **break several timing tests** in twister. So advice on whether and how this should be approached is highly appreciated.

### PR DESCRIPTION
**Pull request by ghost**
The net_if API may be concurrently accessed by several threads. That's the reason why write accesses to certain net_if attributes (notably link-layer address) are guarded by a mutex lock.

Unfortunately locking has only been introduced for write access while non-atomic read access is not properly guarded. This creates a race condition during concurrent read and write access to net_if attributes.

This change introduces a partial fix by exposing the mutex in two additional API methods and introducing these methods in some frequently used functions of the net IP stack.

This change is not intended as a complete fix of all race conditions caused by the missing protection of read access to net_if. It only addresses the most prominent execution paths.

It may also make sense to introduce more granular per-instance locking of net_if rather than global locking. This is out of scope in this change, though.

@rlubos @tbursztyka Any ideas how to improve performance (reduce lag) and/or fix timing tests which this PR seems to break?

Fixes #50875.

### CODE REVIEW

**Comment by jukkar** [comment]
About the test failures, there is this one with compile failure
```
ERROR   - Cmake build failure: /__w/zephyr/zephyr/samples/shields/lmp90100_evb/rtd for frdm_k64f
INFO    - 174/570 frdm_k64f                 samples/shields/lmp90100_evb/rtd/sample.shields.lmp90100_evb.rtd FAILED Cmake build failure (build)
INFO    - /__w/zephyr/zephyr/twister-out/frdm_k64f/samples/shields/lmp90100_evb/rtd/sample.shields.lmp90100_evb.rtd/build.log
ERROR   - Loading Zephyr default modules (Zephyr base).
-- Application: /__w/zephyr/zephyr/samples/shields/lmp90100_evb/rtd
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter 
-- Cache files will be written to: /__w/zephyr/zephyr/.cache
-- Zephyr version: 3.2.99 (/__w/zephyr/zephyr)
-- Found west (found suitable version "0.14.0", minimum required is "0.7.1")
-- Board: frdm_k64f
-- Shield(s): lmp90100_evb
-- Found host-tools: zephyr 0.15.0 (/opt/toolchains/zephyr-sdk-0.15.0)
-- Found toolchain: zephyr 0.15.0 (/opt/toolchains/zephyr-sdk-0.15.0)
-- Found Dtc: /opt/toolchains/zephyr-sdk-0.15.0/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /__w/zephyr/zephyr/boards/arm/frdm_k64f/frdm_k64f.dts
-- Found devicetree overlay: /__w/zephyr/zephyr/boards/shields/lmp90100_evb/lmp90100_evb.overlay
-- Found devicetree overlay: /__w/zephyr/zephyr/samples/shields/lmp90100_evb/rtd/app.overlay
devicetree error: /__w/zephyr/zephyr/samples/shields/lmp90100_evb/rtd/app.overlay:7 (column 1): parse error: undefined node label 'lmp90100'
-- In: /__w/zephyr/zephyr/twister-out/frdm_k64f/samples/shields/lmp90100_evb/rtd/sample.shields.lmp90100_evb.rtd/zephyr, command: /usr/bin/python3.8;/__w/zephyr/zephyr/scripts/dts/gen_defines.py;--dts;/__w/zephyr/zephyr/twister-out/frdm_k64f/samples/shields/lmp90100_evb/rtd/sample.shields.lmp90100_evb.rtd/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/__w/zephyr/zephyr/dts/bindings;--header-out;/__w/zephyr/zephyr/twister-out/frdm_k64f/samples/shields/lmp90100_evb/rtd/sample.shields.lmp90100_evb.rtd/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/__w/zephyr/zephyr/twister-out/frdm_k64f/samples/shields/lmp90100_evb/rtd/sample.shields.lmp90100_evb.rtd/zephyr/zephyr.dts.new;--edt-pickle-out;/__w/zephyr/zephyr/twister-out/frdm_k64f/samples/shields/lmp90100_evb/rtd/sample.shields.lmp90100_evb.rtd/zephyr/edt.pickle;--edtlib-Werror;--vendor-prefixes;/__w/zephyr/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /__w/zephyr/zephyr/cmake/modules/dts.cmake:230 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /__w/zephyr/zephyr/cmake/modules/zephyr_default.cmake:108 (include)
  /__w/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /__w/zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:8 (find_package)
```
Does not seem to be related to your changes.

The socket failure is related to this PR
```
INFO    - 569/569 qemu_x86                  tests/net/socket/select/net.socket.select.preempt  FAILED Failed (qemu 29.495s)
INFO    - /__w/zephyr/zephyr/twister-out/qemu_x86/tests/net/socket/select/net.socket.select.preempt/handler.log
ERROR   - SeaBIOS (version zephyr-v1.0.0-0-g31d4e0e-dirty-20200714_234759-fv-az50-zephyr)
Booting from ROM..
*** Booting Zephyr OS build zephyr-v3.2.0-111-g06ef455787d8  ***
Running TESTSUITE net_socket_select
===================================================================
START - test_fd_set
 PASS - test_fd_set in 0.002 seconds
===================================================================
START - test_select

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/select/src/main.c:132: net_socket_select_test_select: (tstamp <= FUZZ is false)

 FAIL - test_select in 0.147 seconds
===================================================================
TESTSUITE net_socket_select failed.
```
The FUZZ value we are comparing here is only 60ms, and now with extra locking, it is certainly possible that something takes longer and we see a failure. The fuzz value might be too tight although we have not changed that value for a long time. The error might go away if we introduce mutex inside net_if instead of re-using the global lock. Could you experiment with this?

**Comment by rlubos** [comment]
> It may also make sense to introduce more granular per-instance locking of net_if rather than global locking. This is out of scope in this change, though.

True, I agree.

> Any ideas how to improve performance (reduce lag) and/or fix timing tests which this PR seems to break?

Actually, the `select` test suite failure does not seem to be timing-related. I did some debugging, and it seems that changes in this PR affect the boot sequence somehow*, causing the DAD procedure to fail (due to net_pkt shortage) effectively breaking the network interface auto-configuration. Increasing `CONFIG_NET_PKT_TX_COUNT=6` in the test case helps.

* Would still be good to identify what exactly changed, I did not spend too much time on this. It seems to be related to the mutex lock added to `net_pkt_set_iface()`.

**Comment by laurenmurphyx64** [comment]
Hi! Thanks for the PR, could you add "Fixes #50875" to the commit message?

**Review by tbursztyka — COMMENTED** [review]
Why not just adding the locking logic directly into net_if_get_link_addr() ?

That said, indeed we may need to revise this to lock per-net_if instead of the whole net_if core

**Comment by fgrandel** [comment]
> Why not just adding the locking logic directly into net_if_get_link_addr() ?

@tbursztyka This would solve the problem for a single read access to the pointer (only!) but still the address itself (or any other writable attribute) could be changed while you're still using it. One way to solve this would be to create an individual copy of the address under the lock and only hand out the copy but that would introduce an even more inacceptable time/space footprint. So the only solution I'm aware of is exposing the lock itself and let users lock the address as long as they are reading it.

**Comment by rlubos** [comment]
@fgrandel  What about that `select` test, did you try to increase the buffer count?

**Comment by fgrandel** [comment]
@rlubos I'll be able to look into this on the weekend.

**Comment by fgrandel** [comment]
Hi @rlubos ! It cost me a whole day to understand what's going on here... I'll try to explain:

In a nutshell: 

1) Sending packages will acquire the iface lock and will hold on to the lock even when yielding control to other threads due to missing TX package capacity, waiting for a package slab to become available.
2) The problem now is that **my change introduced locking into the package allocation** path. **Package allocation will now block for all (!) package pools while one thread is waiting for package capacity** in any pool.
3) The dummy interface used in the test will try to acquire an RX package in response to every TX package being sent, otherwise sending will not make progress and TX packages will never be freed. As the initial setup of a default IPv6 interface takes a lot of packages (MLD, NS, ND) TX capacity will quickly be exhausted but then the TX cannot succeed as the RX path is deadlocked. Only when the slab timeout of the waiting thread has been reached, will execution continue.
4) The timeout will lead to out-of-memory failures (NULL being returned from package allocation) which again will cause sending to fail completely and net_if_up() will not be able to configure the IPv6 interface.

In the select test the broken initial MLD/NS/ND process caused the network stack to send out ND or ICMP6 packages all the time even while the test case was running. This clogged the TX queue which would then not yield and therefore, when the test thread got back control, no package would have been received (or the timeout reached - whatever comes first). This will fail the test of course.

This explains why adding package capacity (or switching off ND) seems to fix the test as the TX queue will no longer block and the deadlock not occur, the network setup will succeed and the test itself will not experience a race with internal network processes.

This is a really subtle bug - so I'm happy that I took the time to analyze the problem before it became everyone's headache. ;-) I think we cannot introduce the change I proposed as is. It couples package pools in a non-tolerable way IMHO. Unfortunately I cannot think of a good solution - as the race condition that I'm trying to fix here is real as well.

Locking on interface level is not a solution btw. as the interaction is between package pools and a single interface.

Maybe it's a bad idea to keep the interface lock while yielding due to missing package capacity. But fixing this by locking less greedily would be a major project as this concerns almost all functions in net_if that directly or transitively allocate packages or fragments. This goes far over my weekend capacity.

Any ideas @tbursztyka @rlubos how to fix this?

**Comment by fgrandel** [comment]
Here a little excerpt from the log that shows the deadlock:

```
[00:00:00.080,000] <dbg> net_pkt: pkt_alloc_with_buffer: (main): On iface 0x1562ec size 48 (1)
[00:00:00.080,000] <dbg> net_pkt: pkt_alloc_with_buffer: (tx_q[0]): On iface 0x1562ec size 92 (2)
[00:00:00.080,000] <dbg> net_pkt: net_pkt_set_iface: (tx_q[0]): lock iface and get link address (3)
[00:00:00.140,000] <dbg> net_pkt: pkt_alloc: (main): no MEM ---------------------------------------- (4)
[00:00:00.140,000] <err> net_if: Cannot join solicit node address ff02::1:ff00:1 (-12) (5)
[00:00:00.140,000] <dbg> net_pkt: pkt_alloc_with_buffer: (main): On iface 0x1562ec size 20
[00:00:00.250,000] <dbg> net_pkt: pkt_alloc: (main): no MEM ----------------------------------------
[00:00:00.250,000] <dbg> net_pkt: net_pkt_set_iface: (tx_q[0]): unlock iface and get link address
```

1) Main thread tries to allocate a TX package and yields due to missing TX package capacity while still holding the interface lock.
2) TX thread takes over and tries to allocate an RX package (due to the dummy interface driver trying to clone the TX package to the RX path).
3) Allocating packages requires the interface lock. The TX thread is deadlocked as the main thread still holds the interface lock.
4) The slab timeout is being reached and the main thread receives a ENOMEM response.
5) Network interface initialization fails immediately.

**Comment by rlubos** [comment]
I'm not sure I see the need for separate TX/RX mutexes at the net_if level. Sure, a per-instance lock to assure thread safety wherever needed sound reasonable, but 3 separate locks? I'm concerned this is bringing yet another potential deadlock risk to the table if misused.

> Main thread tries to allocate a TX package and yields due to missing TX package capacity while still **holding the interface lock**.

I wonder, isn't that a culprit? Keeping the mutex locked for a blocking operation that doesn't really need to be protected? Unless the pre/post allocation operations are expected to be atomic (but I'm assuming it's net_ipv6_start_dad() we're dealing with here, for which it doesn't seem to), there's no really need to keep the mutex locked. Especially, that action required to unblock the operation (i. e. release the buffers) require the mutex itself.

**Comment by fgrandel** [comment]
> I'm not sure I see the need for separate TX/RX mutexes at the net_if level.

@rlubos Hmm, it depends what you want...

It might seem to be preferable to use a simple short lived spinlock alone, but I'm unsure why the long lived mutex was introduced in the first place. It seems as if it was on purpose to serialize function calls within a protocol flow, e.g. to maintain interface operational state consistency during NS/ND/router discovery, etc. In that case it would definitely be required to hold on to such a lock while waiting for package capacity. And if the protocol requires progress on the RX side to be able to send the next packet (as is the case in all ordered request/response protocol flows) then one common lock for RX and TX would be a bad idea. Here a single lock increases the risk of deadlock as I've shown in my test.

Using a mutex to avoid memory corruption as in the originally reported bug is too heavyweight, though, and you usually don't want your thread to yield if your intention is to synchronize a memory access a few instructions. That's why put the spinlock on the list of options.

I honestly don't know in that case what the "right" mixture looks like. Maybe the original authors of the stack should explain their intention?

**Comment by fgrandel** [comment]
I just edited https://github.com/zephyrproject-rtos/zephyr/pull/50905#issuecomment-1287864547 to clarify some concepts. This will hopefully help whoever looks into this issue.

**Comment by fgrandel** [comment]
@rlubos I propose we remove the Stale label. While this is not the highest prio bug it is still a real problem, has been well researched and would be a good target for some external contributor.

**Comment by rlubos** [comment]
> @rlubos I propose we remove the Stale label. While this is not the highest prio bug it is still a real problem, has been well researched and would be a good target for some external contributor.

Yes, true, I've missed the notification about PR getting marked as stale.

**Comment by MaureenHelm** [comment]
@rlubos is this PR still relevant?

**Comment by rlubos** [comment]
> @rlubos is this PR still relevant?

It's more of a reference PR to take over.

**Comment by rlubos** [comment]
Closing in favor of https://github.com/zephyrproject-rtos/zephyr/pull/56857

**Comment by rlubos** [comment]
I see I only wrote a comment w/o actually closing the PR...

**Pull request closed without merging**
