### PR TITLE
modules: hal: nordic: Fix translation of peripheral symbols

### LINKED ISSUE #22541: hal_nordic: nrf_glue.h change mapped assert function
Today the mapping from NRFX_ASSERT is done like this:

`#define NRFX_ASSERT(expression)  assert(expression)`

When we are using a different version of libc, the assert is mapped to libc and we cannot reach the zephyr assert handler and consequently, we cannot reach 
`assert_post_action` to handle the fault as we desire.

Suggest we instead map this to ` __ASSERT_NO_MSG`

@anangl

### PR DESCRIPTION
**Pull request by anangl**
Update the hal_nordic module revision, to apply the following change:

nrfx_config: Fix translation of symbols for _S or _NS only peripherals

For peripherals with only one type of access available (either secure
or non-secure), the common symbol translation scheme cannot be used
as it leads to mapping to non-existing symbols (e.g. NRF_FICR_NS).
Instead, use fixed translations for these symbols (e.g. NRF_FICR to
NRF_FICR_S, only for secure images).

---

~~https://github.com/zephyrproject-rtos/hal_nordic/pull/26 needs to go in first.~~
~~https://github.com/zephyrproject-rtos/hal_nordic/pull/27 needs to go in first.~~

Includes also the changes from #22869 (those were required to get green CI for this PR).
Fixes #22541.

### CODE REVIEW

**Review by kapi-no — APPROVED** [review]

**Comment by anangl** [comment]
Had to rebase on top of #22869 to get green CI.

**Comment by anangl** [comment]
Updated hal_nordic's SHA.

**Comment by anangl** [comment]
Once more updated the hal_nordic module revision, to include the changes from https://github.com/zephyrproject-rtos/hal_nordic/pull/27.

**Comment by ioannisg** [comment]
Can you rebase and re-run @anangl ?

**Comment by anangl** [comment]
Rebased on master.

**Comment by ioannisg** [comment]
@anangl you can update the PR now

**Comment by anangl** [comment]
Updated hal_nordic's SHA.

**Comment by anangl** [comment]
This PR includes also the changes from the closed #22869 (those were required to get green CI for this PR) and hence fixes #22541.

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
