### PR TITLE
arch: arm64: avoid invalidating of RO mem after mem map

### LINKED ISSUE #64758: arm64: Crash when mapping read-only area
The following example crashes on the `phycore_am62x_a53` board, although it seems to work on `qemu_cortex_a53` board...

Example:

    static uint8_t rw_section[CONFIG_MMU_PAGE_SIZE] __aligned(CONFIG_MMU_PAGE_SIZE);
    uintptr_t rw_virt = 0;
    printk("Mapping RW section %p %zu\n", rw_section, sizeof(rw_section));
    z_phys_map((uint8_t **)&rw_virt,
               (uintptr_t)rw_section, sizeof(rw_section),
               K_MEM_CACHE_WB | K_MEM_PERM_RW);
    printk("Mapped RW section to %p\n", (void *)rw_virt);

    static uint8_t ro_section[CONFIG_MMU_PAGE_SIZE] __aligned(CONFIG_MMU_PAGE_SIZE);
    uintptr_t ro_virt = 0;
    printk("Mapping RO section %p %zu\n", ro_section, sizeof(ro_section));
    z_phys_map((uint8_t **)&ro_virt,
               (uintptr_t)ro_section, sizeof(ro_section),
               K_MEM_CACHE_WB);
    printk("Mapped RO section to %p\n", (void *)ro_virt);

Output:

	Mapping RW section 0xfc00b000 4096
	Mapped RW section to 0xfc7ed000
	Mapping RO section 0xfc00a000 4096
	[00:00:00.015,000] <err> os: ELR_ELn: 0x00000000fbffb7d4
	[00:00:00.021,000] <err> os: ESR_ELn: 0x000000009600014f
	[00:00:00.027,000] <err> os:   EC:  0x25 (Data Abort taken without a change in Exception level)
	[00:00:00.036,000] <err> os:   IL:  0x1
	[00:00:00.040,000] <err> os:   ISS: 0x14f
	[00:00:00.045,000] <err> os: FAR_ELn: 0x00000000fc7ec000
	[00:00:00.051,000] <err> os: TPIDRRO: 0x01000000fc015398
	[00:00:00.057,000] <err> os: x0:  0x00000000fc7ec000  x1:  0x00000000fc7ed000
	[00:00:00.065,000] <err> os: x2:  0x0000000000000040  x3:  0x000000000000003f
	[00:00:00.073,000] <err> os: x4:  0x00000000fc7ec000  x5:  0x0000000000000174
	[00:00:00.080,000] <err> os: x6:  0x0000000000000004  x7:  0x0000000000000000
	[00:00:00.088,000] <err> os: x8:  0xaaaaaaaaaaaaaaaa  x9:  0xaaaaaaaaaaaaaaaa
	[00:00:00.096,000] <err> os: x10: 0xaaaaaaaaaaaaaaaa  x11: 0x0000000000000000
	[00:00:00.104,000] <err> os: x12: 0xaaaaaaaaaaaaaaaa  x13: 0xaaaaaaaaaaaaaaaa
	[00:00:00.112,000] <err> os: x14: 0xaaaaaaaaaaaaaaaa  x15: 0xaaaaaaaaaaaaaaaa
	[00:00:00.119,000] <err> os: x16: 0xaaaaaaaaaaaaaaaa  x17: 0xaaaaaaaaaaaaaaaa
	[00:00:00.127,000] <err> os: x18: 0xaaaaaaaaaaaaaaaa  lr:  0x00000000fbffc018
	[00:00:00.135,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
	[00:00:00.143,000] <err> os: Current thread: 0xfc014700 (main)
	[00:00:00.149,000] <err> os: Halting system
	
This appears to have started happening after this commit https://github.com/zephyrproject-rtos/zephyr/commit/c9b534c4ebca8c3d02bc7d783c79771f1409d096.

Crashes here: `z_phys_map` -> `arch_mem_map` -> `inv_dcache_after_map_helper` -> `arm64_dcache_range` -> `dc_ops("ivac", start_addr);`.

Maybe caused by this:

> DC IVAC, requires write permission or else a permission fault is generated

https://developer.arm.com/documentation/den0024/a/Caches/Cache-maintenance

### PR DESCRIPTION
**Pull request by xakep-amatop**
The Cortex ARM documentation states that the DC IVAC instruction requires write access permission to the virtual address (VA); otherwise, it may generate a permission fault.

Therefore, it is needed to avoid invalidating read-only memory after the memory map operation.

This issue has been produced by commit c9b534c.
This commit resolves the issue #64758.

Fixes: #64758

### CODE REVIEW

**Comment by gramsay0** [comment]
In Linux you can use `devm_memremap` which returns R/W memory, even if the underlying memory is R/O (i.e. with regard to a hypervisor). As long as you don't write to R/O pages everything still works.

Zephyr `z_phys_map` with `K_MEM_PERM_RW` behaved similarly until this change https://github.com/zephyrproject-rtos/zephyr/commit/c9b534c4ebca8c3d02bc7d783c79771f1409d096.

My use-case is the ivshmem-v2 driver, which will need to be modified to map each section differently.
The ivshmem-v2 memory is laid out like this:

```
+-----------------------------+   -
|                             |   :
| Output Section for peer n-1 |   : R/W for peer n-1, else R/O
|     (n = Maximum Peers)     |   :
+-----------------------------+   -
:                             :
:                             :
:                             :
+-----------------------------+   -
|                             |   :
|  Output Section for peer 1  |   : R/W for peer 1, else R/O
|                             |   :
+-----------------------------+   -
|                             |   :
|  Output Section for peer 0  |   : R/W for peer 0, else R/O
|                             |   :
+-----------------------------+   -
|                             |   :
|     Read/Write Section      |   : R/W
|                             |   :
+-----------------------------+   -
|                             |   :
|         State Table         |   : R/W
|                             |   :
+-----------------------------+   <-- Shared memory base address
```

Currently this whole memory block is allocated using `z_phys_map` with `K_MEM_PERM_RW`, even though some sections are R/O (similar to the Linux implementation):
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/virtualization/virt_ivshmem.c#L254

I don't understand the intricacies of https://github.com/zephyrproject-rtos/zephyr/commit/c9b534c4ebca8c3d02bc7d783c79771f1409d096, but I'm wondering if/why Zephyr should have different behavior in this regard?

I'm happy to update the ivshmem driver if needed.

In any case, could the changes please be backported to v3.5-branch?

**Comment by carlocaione** [comment]
@gramsay0 can you check whether this commit is fixing your usecase?

**Comment by gramsay0** [comment]
> @gramsay0 can you check whether this commit is fixing your usecase?

I had assumed this would not resolve my issue without testing it 🤦
This does indeed seem to resolve my issue.

I assumed `z_phys_map` with `K_MEM_PERM_RW` would result in `inv_dcache_after_map_helper` being called with `MT_RW` set, but that is not the case.

Although the call to `inv_dcache_after_map_helper` in `arch_mem_map` seems like it it never does anything now.

`mem_flags` is set to either `MT_NORMAL` (4) or `MT_NORMAL_WT` (5):
```
mem_flags = (mem_flags == K_MEM_CACHE_WB) ? MT_NORMAL : MT_NORMAL_WT;
inv_dcache_after_map_helper(virt, size, mem_flags);
```
`MT_RW` is `8`, so this will always return early:
```
static inline void inv_dcache_after_map_helper(void *virt, size_t size, uint32_t attrs)
{
	if ((attrs & MT_RW) != MT_RW) {
		return;
	}
	...
```

Is this intended?

**Comment by xakep-amatop** [comment]
> > @gramsay0 can you check whether this commit is fixing your usecase?
> 
> I had assumed this would not resolve my issue without testing it 🤦 This does indeed seem to resolve my issue.
> 
> I assumed `z_phys_map` with `K_MEM_PERM_RW` would result in `inv_dcache_after_map_helper` being called with `MT_RW` set, but that is not the case.
> 
> Although the call to `inv_dcache_after_map_helper` in `arch_mem_map` seems like it it never does anything now.
> 
> `mem_flags` is set to either `MT_NORMAL` (4) or `MT_NORMAL_WT` (5):
> 
> ```
> mem_flags = (mem_flags == K_MEM_CACHE_WB) ? MT_NORMAL : MT_NORMAL_WT;
> inv_dcache_after_map_helper(virt, size, mem_flags);
> ```
> 
> `MT_RW` is `8`, so this will always return early:
> 
> ```
> static inline void inv_dcache_after_map_helper(void *virt, size_t size, uint32_t attrs)
> {
> 	if ((attrs & MT_RW) != MT_RW) {
> 		return;
> 	}
> 	...
> ```
> 
> Is this intended?

Nope, thank you for pointing that out.

Also, I can reproduce the issue locally with the code provided by @gramsay0. I have two boards, one based on Cortex A57 and another one based on Cortex A55. I can confirm that I see the same issue with the CA55 board; at the same time, the issue isn't reproducible with the CA57.

**Comment by gramsay0** [comment]
@xakep-amatop thanks for the fix and taking time to reproduce the issue 👍
This patch fixes the issue I raised, so I think it is good to merge.

Although my actual use-case is slightly different.
Do you have any thoughts on if/why Zephyr should behave differently to Linux WRT:

> In Linux you can use `devm_memremap` which returns R/W memory, even if the underlying memory is R/O (i.e. with regard to a hypervisor). As long as you don't write to R/O pages everything still works.

**Review by gramsay0 — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]

**Review by povergoing — APPROVED** [review]

**Pull request merged**
