### PR TITLE
lptim: stm32g4: support of the lptimer on stm32g4xx

### PR DESCRIPTION
**Pull request by FRASTM**
This patch enables the LP Timer driver for the stm32g4xx soc, to be used in tickless kernel. The LPTimer is clocked by the LSI or LSE. It provides the following APIs:
z_clock_set_timeout
z_clock_elapsed
z_clock_driver_init
and irq handler

This patch requires the support of the lptimer for l4 serie [#18582]

Signed-off-by: Francois Ramu francois.ramu@st.com

### CODE REVIEW

**Comment by FRASTM** [comment]
This PR requires the "lptim: stm32l4: support of the lptimer" #18582 
The soc stm32g431 holds the "config STM32_LPTIM_TIMER"
The board sets the CONFIG_STM32_LPTIM_CLOCK_LSE=y
Sample applications could overwrite this in the proj.conf

**Comment by FRASTM** [comment]
rebase

**Comment by FRASTM** [comment]
re-submit after update on "lptim: stm32l4: support of the lptimer" #18582

**Comment by FRASTM** [comment]
this PR is following introduction of lptim on l4
lptim: stm32l4: support of the lptimer #18582

**Comment by FRASTM** [comment]
rebase

**Comment by FRASTM** [comment]
rebase

**Review by MaureenHelm — APPROVED** [review]
@erwango please review

**Pull request closed without merging**
