### PR TITLE
make clock_settime/clock_gettime REALTIME MT safe…

### LINKED ISSUE #23419: posix: clock: No thread safety clock_[get/set]time
Hi,
Posix specify that clock_settime and clock_gettime are Multithread safe. However, the global variable rt_clock_base could be get/and set at the same time without protection... Is that normal?

### PR DESCRIPTION
**Pull request by ghost**
To make clock_settime/gettime REALTIME thread-safe, as spec states, locking is needed.

Fixes #23419

I would like to have this backported to 2.6

### CODE REVIEW

**Comment by cfriedt** [comment]
Please change your commit message and summary above to say Fixes #nr instead, as that will automatically close the original issue once merged.

**Review by cfriedt — APPROVED** [review]
LGTM

**Comment by pakar1** [comment]
@cfriedt Tests seems to be done but things state that actions are required from maintainer.. Just posting a comment to notify since there is no maintainer for posix, as far as i understood.

**Comment by cfriedt** [comment]
@pakar1 - looks like you need to run `git commit --amend -s` to add a `Signed-off-by` line.

**Comment by pakar1** [comment]
@cfriedt I have no clue on whom i should ask to sign it off.. No maintainer to ask and i'm not a collaborator so i should probably not be the one to sign it off either?
First PR to zephyr so please bear with me.

**Comment by cfriedt** [comment]
> @cfriedt I have no clue on whom i should ask to sign it off.. No maintainer to ask and i'm not a collaborator so i should probably not be the one to sign it off either?
> First PR to zephyr so please bear with me.

@pakar1 - **You** need to sign off on it. Please see previous comment

**Comment by pakar1** [comment]
@cfriedt Any idea when this will be merged?

**Review by carlescufi — APPROVED** [review]
LGTM

**Pull request merged**
