### PR TITLE
ARC: QEMU: Enable icount support

### LINKED ISSUE #26163: qemu_arc_{em,hs} keeps failing in CI on tests/kernel/lifo/lifo_usage
**Describe the bug**
Keeps failing in CI

https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/75382/3/tests

```
*** Booting Zephyr OS build zephyr-v2.3.0-305-gb04ff83884de  ***
Running test suite test_lifo_usage
===================================================================
starting test - test_lifo_nowait
PASS - test_lifo_nowait
===================================================================
starting test - test_lifo_wait
PASS - test_lifo_wait
===================================================================
starting test - test_timeout_empty_lifo
PASS - test_timeout_empty_lifo
===================================================================
starting test - test_timeout_non_empty_lifo
PASS - test_timeout_non_empty_lifo
===================================================================
starting test - test_timeout_lifo_thread

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/lifo/lifo_usage/src/main.c:329: test_timeout_lifo_thread: packet != NULL is false

FAIL - test_timeout_lifo_thread
===================================================================
starting test - test_timeout_threads_pend_on_lifo

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/lifo/lifo_usage/src/main.c:401: test_thread_pend_and_timeout: packet == NULL is false

FAIL - test_timeout_threads_pend_on_lifo
===================================================================
Test suite test_lifo_usage failed.
===================================================================
PROJECT EXECUTION FAILED
```

excluding it for now, but need a fix.

EDIT: This test fails on both `qemu_arc_hs` and `qemu_arc_em`.

### LINKED ISSUE #26227: icount support for qemu_arc_{em,hs}
**Is your enhancement proposal related to a problem? Please describe.**
The `qemu_arc_em` and `qemu_arc_hs` targets aren't using icount. This causes timing sensitive tests to intermittently fail.

**Describe the solution you'd like**
icount enabled in QEMU command line arguments for `qemu_arc_em` and `qemu_arc_hs`, as we have done on most other arches.

My understanding is that some issues in upstream QEMU must be resolved for the ARC port in order for this to happen.

### LINKED ISSUE #26500: sanitycheck reports failing tests with test_slice_scheduling()
**Describe the bug**
When I was optimizing my PR #25813, there is always a failure on test_slice_scheduling.
Handler.log shows all other platforms are good except qemu_arc_hs and qemu_arc_em.
So I checkout git branch to master and change macro ITRERATION_COUNT in  test_priority_scheduling.c and
test_slice_scheduling.c from 5 to 10, this happens, but not every time.

**To Reproduce**
1. In master branch, commit ID ba0a791635c9fa70f0dc5ffb7a98a03f7e28f000
2. change macro ITRERATION_COUNT in  test_priority_scheduling.c and test_slice_scheduling.c from 5 to 10
3. run command: sanitycheck -T tests/kernel/sched/schedule_api/ 

**Logs and console output**
```


START - test_slice_reset

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:91: thread_time_slice: (t <= expected_slice_max is false)
timeslice too big, expected 110000 got 115322

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:88: thread_time_slice: (t >= expected_slice_min is false)
timeslice too small, expected 90000 got 15903

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:88: thread_time_slice: (t >= expected_slice_min is false)
timeslice too small, expected 90000 got 960
 FAIL - test_slice_reset
===================================================================
START - test_slice_scheduling
AB
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

C
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

D
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

E
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

F
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

G
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

H
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

I
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false



    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

A
    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false

 FAIL - test_slice_scheduling
===================================================================
START - test_priority_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
 PASS - test_priority_scheduling

```

### PR DESCRIPTION
**Pull request by abrodkin**
This allows to get much more reproducible results in terms of amount of tests passed & failed.
For now only those 2 tests fail due to time-out (for some reason in QEMU now they are running a bit more than 60 seconds and that needs a separate investigation):
```
tests/kernel/sched/schedule_api/kernel.scheduler
tests/kernel/sched/schedule_api/kernel.scheduler.multiq
```

But note it requires QEMU for ARC with `icount` support!
@galak @stephanosio that's a QEMU patch which applies equally well to v4.2 & v5.0: https://github.com/abrodkin/qemu/commit/45e7fc2ce84609a96960666f49674b9700a1737f

Closes #26227
Fixes #26500 
Fixes #26163

NOTE: This needs to be merged after the aforementioned QEMU patch is available in the CI image.

### CODE REVIEW

**Comment by stephanosio** [comment]
Test QEMU build can be downloaded here:
https://github.com/stephanosio/zephyr-qemu/actions/runs/157146129

Make sure to symlink `zephyr-qemu-system-arc` to `qemu-system-arc` and set `QEMU_BIN_PATH` to test with this PR.

Test result can be found here:
`qemu_arc_hs`: https://gist.github.com/stephanosio/29040c42da71e4ce7f852dcee984976c
`qemu_arc_em`: https://gist.github.com/stephanosio/5c59108e4e03b16c2abd80149fc8257e

I can confirm that, with the patched QEMU and this PR, the test failure rate is much lower, but I see two persistently failing tests for both `qemu_arc_hs` and `qemu_arc_em`:
```
$ scripts/sanitycheck -v -N -p qemu_arc_hs -f
Keeping artifacts untouched
INFO    - JOBS: 32
INFO    - 2 test configurations selected, 0 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - 1/2 qemu_arc_hs               tests/kernel/sched/schedule_api/kernel.scheduler   FAILED Exited with 1 (qemu)
ERROR   - see: /home/stephanos/Dev/zephyr-public/zephyr/sanity-out/qemu_arc_hs/tests/kernel/sched/schedule_api/kernel.scheduler/handler.log
INFO    - 2/2 qemu_arc_hs               tests/kernel/sched/schedule_api/kernel.scheduler.multiq FAILED Exited with 1 (qemu)
ERROR   - see: /home/stephanos/Dev/zephyr-public/zephyr/sanity-out/qemu_arc_hs/tests/kernel/sched/schedule_api/kernel.scheduler.multiq/handler.log
```

**Comment by stephanosio** [comment]
@abrodkin Adding the following patch should resolve `tests/kernel/sched/schedule_api` timeout issues:
```
diff --git a/tests/kernel/sched/schedule_api/testcase.yaml b/tests/kernel/sched/schedule_api/testcase.yaml
index b5842663b2..41c952fe12 100644
--- a/tests/kernel/sched/schedule_api/testcase.yaml
+++ b/tests/kernel/sched/schedule_api/testcase.yaml
@@ -4,6 +4,7 @@ tests:
     extra_configs:
       - CONFIG_TIMESLICING=y
     tags: kernel threads sched userspace
+    timeout: 120
   kernel.scheduler.no_timeslicing:
     filter: not CONFIG_SCHED_MULTIQ
     extra_configs:
@@ -14,6 +15,7 @@ tests:
     extra_configs:
       - CONFIG_TIMESLICING=y
     tags: kernel threads sched userspace
+    timeout: 120
   kernel.scheduler.multiq_no_timeslicing:
     extra_args: CONF_FILE=prj_multiq.conf
     extra_configs:
```

**Review by stephanosio — COMMENTED** [review]
Please remove the following `platform_exclude`s as well:
https://github.com/zephyrproject-rtos/zephyr/blob/cd8f46b998d218a7038cf1ad273ff6ef87b5bfe9/tests/kernel/timer/timer_api/testcase.yaml#L4

https://github.com/zephyrproject-rtos/zephyr/blob/cd8f46b998d218a7038cf1ad273ff6ef87b5bfe9/tests/kernel/timer/timer_api/testcase.yaml#L8

https://github.com/zephyrproject-rtos/zephyr/blob/27d42f060da1afe129ae2b66e15a09dc54e904cf/tests/kernel/lifo/lifo_usage/testcase.yaml#L5

https://github.com/zephyrproject-rtos/zephyr/blob/cd8f46b998d218a7038cf1ad273ff6ef87b5bfe9/tests/kernel/tickless/tickless_concept/testcase.yaml#L8

**Review by vonhust — APPROVED** [review]

**Comment by abrodkin** [comment]
> 
> 
> @abrodkin Adding the following patch should resolve `tests/kernel/sched/schedule_api` timeout issues:
> 
> ```
> diff --git a/tests/kernel/sched/schedule_api/testcase.yaml b/tests/kernel/sched/schedule_api/testcase.yaml
> index b5842663b2..41c952fe12 100644
> --- a/tests/kernel/sched/schedule_api/testcase.yaml
> +++ b/tests/kernel/sched/schedule_api/testcase.yaml
> @@ -4,6 +4,7 @@ tests:
>      extra_configs:
>        - CONFIG_TIMESLICING=y
>      tags: kernel threads sched userspace
> +    timeout: 120
>    kernel.scheduler.no_timeslicing:
>      filter: not CONFIG_SCHED_MULTIQ
>      extra_configs:
> @@ -14,6 +15,7 @@ tests:
>      extra_configs:
>        - CONFIG_TIMESLICING=y
>      tags: kernel threads sched userspace
> +    timeout: 120
>    kernel.scheduler.multiq_no_timeslicing:
>      extra_args: CONF_FILE=prj_multiq.conf
>      extra_configs:
> ```

I may indeed increase a timeout there, but on other platforms as well as on nSIM those tests run much faster. Also my fast review of those test sources reveals that there's no [at least explicit] delay or something which might intentionally introduce this very visible delay in between printing letters and so there might be hidden something that makes certain OS mechanics unexpectedly slow. And IMHO that needs a separate investigation. So once QEMU stuff for ARC is back in action we'll file an issue for tracking that one, OK?

**Comment by abrodkin** [comment]
@stephanosio see I pushed reverts of exclusions previously done for `qemu_arc_{em|hs}.

**Review by wentongwu — APPROVED** [review]

**Comment by abrodkin** [comment]
@galak, @stephanosio any hint on when updated Zephyr SDK with fixed QEMU for ARC might be available?

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by galak** [comment]
@abrodkin do you have a patch for icount support on qemu 4.2 for ARC?  Trying to see if we release a SDK 0.11.5 with a newlib fix for xtensa and arc icount support or just wait for 0.12.x

**Comment by abrodkin** [comment]
> 
> 
> @abrodkin do you have a patch for icount support on qemu 4.2 for ARC? Trying to see if we release a SDK 0.11.5 with a newlib fix for xtensa and arc icount support or just wait for 0.12.x

I do have it and it works equally well as v5.0-based one.
See https://github.com/abrodkin/qemu/commit/609b0ad995d0c9414239265b7098a43a47d31e7e

**Comment by abrodkin** [comment]
@galak so with https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.12.0-beta-1 and that PR I'm seeing very nice and reliable results:
```
./scripts/sanitycheck --platform qemu_arc_hs
Install the anytree module to use the --test-tree option
INFO    - JOBS: 20
INFO    - Building initial testcase list...
INFO    - 938 test configurations selected, 709 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
ERROR   - qemu_arc_hs               tests/crypto/tinycrypt/crypto.tinycrypt            FAILED: Timeout
ERROR   - see: /SCRATCH/abrodkin/Projects/sources/git/zephyrproject/zephyr/sanity-out/qemu_arc_hs/tests/crypto/tinycrypt/crypto.tinycrypt/handler.log
INFO    - Total complete:  229/ 229  100%  skipped:   63, failed:    1
INFO    - 165 of 166 tests passed (99.40%), 1 failed, 772 skipped with 0 warnings in 610.68 seconds
INFO    - In total 1009 test cases were executed on 1 out of total 297 platforms (0.34%)
INFO    - 149 tests executed on platforms, 17 tests were only built.


./scripts/sanitycheck --platform qemu_arc_em
Install the anytree module to use the --test-tree option
INFO    - JOBS: 20
INFO    - Building initial testcase list...
INFO    - 938 test configurations selected, 709 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:  229/ 229  100%  skipped:   63, failed:    0
INFO    - 166 of 166 tests passed (100.00%), 0 failed, 772 skipped with 0 warnings in 332.96 seconds
INFO    - In total 1010 test cases were executed on 1 out of total 297 platforms (0.34%)
INFO    - 150 tests executed on platforms, 16 tests were only built.
```

So I think we're good to go now, finally :)

**Review by ruuddw — APPROVED** [review]

**Comment by abrodkin** [comment]
Ok now with available SDK [v0.12.0-beta-1](https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.12.0-beta-1) (kudos to @galak) this PR could be merged (as it is, w/o any re-spin as it still applies nicely) as results are now quite promising:
```
./scripts/sanitycheck --platform qemu_arc_em --platform qemu_arc_hs
ZEPHYR_BASE unset, using ".../zephyr"
INFO    - Zephyr version: zephyr-v2.4.0-1558-g8f31d35de4
INFO    - JOBS: 64
INFO    - Building initial testcase list...
INFO    - 1942 test configurations selected, 1464 configurations discarded due to filters.
INFO    - Adding tasks to the queue...
INFO    - Total complete:  376/ 478  78%  skipped:  128, failed:    0
ERROR   - qemu_arc_em               tests/kernel/sched/schedule_api/kernel.scheduler   FAILED: Timeout
ERROR   - see: .../zephyr/sanity-out/qemu_arc_em/tests/kernel/sched/schedule_api/kernel.scheduler/handler.log
INFO    - Total complete:  377/ 478  78%  skipped:  128, failed:    1
ERROR   - qemu_arc_hs               tests/kernel/sched/schedule_api/kernel.scheduler   FAILED: Timeout
ERROR   - see: .../zephyr/sanity-out/qemu_arc_hs/tests/kernel/sched/schedule_api/kernel.scheduler/handler.log
INFO    - Total complete:  378/ 478  79%  skipped:  128, failed:    2
ERROR   - qemu_arc_em               tests/kernel/sched/schedule_api/kernel.scheduler.multiq FAILED: Timeout
ERROR   - see: .../zephyr/sanity-out/qemu_arc_em/tests/kernel/sched/schedule_api/kernel.scheduler.multiq/handler.log
INFO    - Total complete:  379/ 478  79%  skipped:  128, failed:    3
ERROR   - qemu_arc_hs               tests/kernel/sched/schedule_api/kernel.scheduler.multiq FAILED: Timeout
ERROR   - see: .../zephyr/sanity-out/qemu_arc_hs/tests/kernel/sched/schedule_api/kernel.scheduler.multiq/handler.log
INFO    - Total complete:  421/ 478  88%  skipped:  128, failed:    4WARNING - qemu_arc_hs/tests/crypto/tinycrypt/crypto.tinycrypt stuck?
INFO    - Total complete:  465/ 478  97%  skipped:  128, failed:    4
ERROR   - qemu_arc_hs               tests/crypto/tinycrypt/crypto.tinycrypt            FAILED: Timeout
ERROR   - see: .../zephyr/sanity-out/qemu_arc_hs/tests/crypto/tinycrypt/crypto.tinycrypt/handler.log
INFO    - Total complete:  478/ 478  100%  skipped:  128, failed:    5
INFO    - 345 of 350 tests passed (98.57%), 5 failed, 1592 skipped with 0 warnings in 492.23 seconds
INFO    - In total 2395 test cases were executed on 2 out of total 307 platforms (0.65%)
INFO    - 313 tests executed on platforms, 37 tests were only built.
```

@nashif, @carlescufi any chance to get this one merged finally and start looking at QEMU for ARC in the per-PR CI?

**Review by ruuddw — APPROVED** [review]

**Comment by galak** [comment]
> @nashif, @carlescufi any chance to get this one merged finally and start looking at QEMU for ARC in the per-PR CI?

1. we need to release SDK 0.12.0
2. we need to update the CI env to use SDK 0.12.0

Until both of these are done, we can't merge this PR.

**Comment by abrodkin** [comment]
I guess we're just waiting for https://github.com/zephyrproject-rtos/zephyr/pull/30854 to get merged as SDK is out, Docker image is also there.

**Comment by abrodkin** [comment]
Oh, and I guess we'll need to revert https://github.com/zephyrproject-rtos/zephyr/commit/7d10b68baaaa8fcf32610f1c65156685dc87cc6d to get QEMU for ARC back in the CI.

**Comment by abrodkin** [comment]
Now when https://github.com/zephyrproject-rtos/zephyr/pull/30854 is merged we're waiting for real switch to newer SDK in the CI done here: https://github.com/zephyrproject-rtos/zephyr/pull/31230.

**Comment by nashif** [comment]
@abrodkin  please rebase.

**Comment by galak** [comment]
@abrodkin do you want to rebase this now that we've merge SDK 0.12.1 support.

**Comment by abrodkin** [comment]
@galak rebased, let's see what we now get from the CI here.

**Comment by abrodkin** [comment]
@galak so these are the failures from Buildkite:

* qemu_arc_hs:
  * tests/kernel/sched/schedule_api/kernel.scheduler
  * tests/kernel/sched/schedule_api/kernel.scheduler.multiq

* m2gl025_miv
  * tests/kernel/lifo/lifo_usage/kernel.lifo.usage

* cc26x2r1_launchxl:
  * tests/kernel/tickless/tickless_concept/kernel.tickless.concept
  * tests/kernel/timer/timer_api/kernel.timer.tickless

* cc1352r1_launchxl:
  * tests/kernel/tickless/tickless_concept/kernel.tickless.concept
  * tests/kernel/timer/timer_api/kernel.timer.tickless

* cc1352r_sensortag:
  * tests/kernel/tickless/tickless_concept/kernel.tickless.concept
  * tests/kernel/timer/timer_api/kernel.timer.tickless

**Comment by galak** [comment]
> @galak so these are the failures from Buildkite:
> 
>     * qemu_arc_hs:
>       
>       * tests/kernel/sched/schedule_api/kernel.scheduler
>       * tests/kernel/sched/schedule_api/kernel.scheduler.multiq
> 
>     * m2gl025_miv
>       
>       * tests/kernel/lifo/lifo_usage/kernel.lifo.usage
> 
>     * cc26x2r1_launchxl:
>       
>       * tests/kernel/tickless/tickless_concept/kernel.tickless.concept
>       * tests/kernel/timer/timer_api/kernel.timer.tickless
> 
>     * cc1352r1_launchxl:
>       
>       * tests/kernel/tickless/tickless_concept/kernel.tickless.concept
>       * tests/kernel/timer/timer_api/kernel.timer.tickless
> 
>     * cc1352r_sensortag:
>       
>       * tests/kernel/tickless/tickless_concept/kernel.tickless.concept
>       * tests/kernel/timer/timer_api/kernel.timer.tickless

Opened issue for the CC13xx/CC26xx issues - #31488.  Looking at the others.  The arc one's seem specific to the PR, so will let you look into those.

**Comment by nashif** [comment]
m2gl025_miv failing is not related to this change, only ones I see:
```
* qemu_arc_hs:
  
  * tests/kernel/sched/schedule_api/kernel.scheduler
  * tests/kernel/sched/schedule_api/kernel.scheduler.multiq
```

Those pass when run locally just fine.

**Comment by nashif** [comment]
this is now merged thru another PR #31550

**Pull request closed without merging**
