### PR TITLE
Bluetooth: tester: Add Configuration and Health Client models

### PR DESCRIPTION
**Pull request by MariuszSkamra**
One of the PTS test cases requires preparation of large composition
data that cannot be sent without segmentation.
This patch adds Configuration and Health Client models to the root_models to increase the Elements size in Composition Data Page 0.

### CODE REVIEW

**Comment by jhedberg** [comment]
What if we always registered a large composition data and avoided complicating the BTP protocol? Are there any tests which *require* a "small" composition data?

**Comment by jhedberg** [comment]
Actually, since we now support Configuration and Health Client models, if you just add those to root_models that might already increase the size of the composition data enough to be large enough.

**Review by jhedberg — CHANGES_REQUESTED** [review]
See my comments

**Comment by MariuszSkamra** [comment]
You have right. Adding Configuration and Health Client models meet the PTS requirements. I'll push patch.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
