### PR TITLE
manifest: update hal_nxp

### PR DESCRIPTION
**Pull request by fabiobaltieri**
repro: `west build -p -b mimx8mp_evk_a53 -T tests/kernel/common/kernel.common`

https://github.com/zephyrproject-rtos/hal_nxp/pull/280

---

Update hal_nxp to include a build warning fix for redefinition of MPIDR_AFFLVL_MASK.

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@fabiobaltieri , thank you. HAL PR has been merged.
Would you need a similar wrapper on the Zephyr side header files as well?

**Comment by fabiobaltieri** [comment]
Updated with the final sha.

> @fabiobaltieri , thank you. HAL PR has been merged. Would you need a similar wrapper on the Zephyr side header files as well?

No I think we decided to keep the guards in the modules and plain defines in the upstream code.

**Review by mmahadevan108 — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@mmahadevan108 well, your point about include order was pretty good :-) had to add an explicit include in the CCM file to make that work, would not be surprised if we hit some other one right now. Maybe let's keep this to have the CI running again and then you NXP folks may revisit the situation if this becomes more of a problem?

**Comment by fabiobaltieri** [comment]
Tested this locally with `./scripts/twister -p mimx8mn_evk_a53`, seems to work but that surprised me a bit considering how many references of `fsl_clock.h` are in the code.

**Review by mmahadevan108 — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
ok I think that that one is due to https://github.com/zephyrproject-rtos/hal_nxp/pull/276, which was merged in the HAL but not included in the last west.yaml update, my fix for the macro collision is on top of that though so the HAL update is fixing the collision but including those changes which are breaking s32z

**Comment by fabiobaltieri** [comment]
ok this may need https://github.com/zephyrproject-rtos/zephyr/pull/62685, let me try to cherry pick it

**Comment by fabiobaltieri** [comment]
@manuargue FYI I cherry picked https://github.com/zephyrproject-rtos/zephyr/pull/62685 (withouht the manifest hash) on top of this.

**Comment by manuargue** [comment]
> @manuargue FYI I cherry picked https://github.com/zephyrproject-rtos/zephyr/pull/62685 (without the manifest hash) on top of this.

@fabiobaltieri I'm okay with it from changes pov. Also @mmahadevan108 is suggesting to revert the pr in the HAL for the s32z to get your fixes in first.

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri I'm okay with it from changes pov. Also @mmahadevan108 is suggesting to revert the pr in the HAL for the s32z to get your fixes in first.

Thanks, unless the new files add some test that reveals new breakages this should pass, at least I've rerun all targets that broke on the last run so I say there's hope. :-)

If you folks want to prepare a rollback PR, we can run those in parallel and decide after the end of this run.

**Review by mmahadevan108 — APPROVED** [review]

**Review by manuargue — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
alright, all pass, let's give this a shot and see how it does on the push run

**Comment by fabiobaltieri** [comment]
@mmahadevan108 @dleach02 there's load more drivers using `fsl_clock.h`, I did some test build and seems like none of those are used in the nxp cortex-a53 right now, but they would all trigger again the macro collision if they end up being used with that platform. You may want to review that separately see if you can come up with a solution that avoids the potential collision entirely.

**Comment by dleach02** [comment]
Many apologies folks. @fabiobaltieri, next time I see you dinner is on me.

**Comment by mmahadevan108** [comment]
cc @JiafeiPan. Need your help to investigate this.

**Comment by fabiobaltieri** [comment]
> Many apologies folks. @fabiobaltieri, next time I see you dinner is on me.

Hey no prob, thanks for the quick reviews :-)

**Pull request merged**
