### PR TITLE
Add feather header

### PR DESCRIPTION
**Pull request by rosterloh**
Added feather header pinout and updated an example board using it.

nRF52 Feather Pinout

### CODE REVIEW

**Comment by rosterloh** [comment]
@galak This has been open for a while and I've had no comments. Is there a problem with it?

**Comment by tsvehagen** [comment]
> @galak This has been open for a while and I've had no comments. Is there a problem with it?

Could you please take a look at the zephyrbot comments. I think this would be a nice addition to be able to add some feather shields.

**Comment by rosterloh** [comment]
@tsvehagen I'm not really sure what the problem is with my email address. This in not my first PR. I've added a description to the last commit and added a newline at the end of the file as suggested.

**Comment by tsvehagen** [comment]
> @tsvehagen I'm not really sure what the problem is with my email address. This in not my first PR. I've added a description to the last commit and added a newline at the end of the file as suggested.

Yea I'm not sure what was the problem with the email either but it seems to be okay now :p Thanks.

**Review by pabigot — APPROVED** [review]
Looks good.

FWIW I was looking just two days ago to do exactly this, except my target is the Particle mesh boards.  Although those conform to the feather physical connection and many of the functions, they use a different pin order, skip one pin, and add another.  So it's good this one is here for the Adafruit version, and I'll add the Particle one separately.

**Review by galak — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
LGTM, but it might be worth editing the boards yaml files and add feather_serial, feather_i2c and feather_spi in `supported` section.
This will be useful for upcoming support of sample feather shields.

**Comment by rosterloh** [comment]
@erwango done and added adafruit_feather_nrf52840 for good measure

**Review by erwango — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
