### PR TITLE
net: lwm2m: Add callback to report observers added/deleted and notification ack/timeout

### PR DESCRIPTION
**Pull request by MaikVermeulen**

### CODE REVIEW

**Comment by MaikVermeulen** [comment]
Two things crossed my mind while working on this:
1. Is the `lwm2m_rd_client_start()` okay like this or should I not interfere with its API?
2. Perhaps we would like to make a dedicated function find to which observer object a token belongs, currently this code, or slight variations of it, is in 3 or 4 places:
```
	SYS_SLIST_FOR_EACH_CONTAINER(&ctx->observer, obs, node) {
		if (memcmp(obs->token, token, tkl) == 0) {
			found_obj = obs;
			break;
		}

		prev_node = &obs->node;
	}

	if (!found_obj) {
		return -ENOENT;
	}
```

**Comment by huelsenfruchtzwerg** [comment]
Thanks for picking this up!

@JPSELC pointed out in #38531 that the callback would need to report the token to the user, and I'm inclined to agree with him.
When the callback only gives the path to the object, there's no way for the application to now _what_ data exactly has been delivered, i.e. if two notifications are created ~close to each other, one times out and one is acknowleged.

**Comment by huelsenfruchtzwerg** [comment]
Just had a quick look, it looks to me like notifications for the same observations will always have the same token. So this won't work for the use case I described anyway, in which case I believe the API is fine as is. But somebody should double check, I might just be missing something. :)
If so, this raises another question: Should the client be modified to never have >1 notification per observation in flight/unacknowledged so what data is/is not delivered is answerable?

**Comment by JPSELC** [comment]
Repeat sends of the same notification will have the same token, as far as I know, but that is not the same as a new notification from  the same path.
@huelsenfruchtzwerg If you are limiting the notification sending until the previous notification is acknowledged, you have to store them, I guess, which might link in well with the original motivation of storing notifications when offline.

**Comment by huelsenfruchtzwerg** [comment]
> Since the tokens are generated per coap message, so for every notification instance, they remain the same for retransmissions because it's still the same coap message. New notifications will be new coap messages with new tokens.

Not for notifications though, they [explicitly set the token to the same as the observation](https://github.com/zephyrproject-rtos/zephyr/blob/1ea0fabe722bfd6e6257b536908c726b594a21a8/subsys/net/lib/lwm2m/lwm2m_engine.c#L4247).

That is, unless I'm misunderstanding the code.

**Comment by JPSELC** [comment]
Ah yes, I think that's the case.

**Comment by huelsenfruchtzwerg** [comment]
This is probably just a convenience thing though to easily look up the original observation, and we could "fix" this by adding a explicit link between original Notification-Msg -> Observation-Token.

**Comment by huelsenfruchtzwerg** [comment]
One side note:
I believe a "is_observed(ctx, path)" function would also be useful, else the application would need to duplicate the state in situations where it's e.g. waiting for a number of observations to be established.

**Comment by JPSELC** [comment]
> This is probably just a convenience thing though to easily look up the original observation, and we could "fix" this by adding a explicit link between original Notification-Msg -> Observation-Token. (at the cost of memory consumption, obviously)

I just checked, and it's the standard (V1.0.2) Section 8.2.6 indicates "Token of CoAP layer is used to match the asynchronous
notifications with the Observe GET." The Server uses the Token to understand what observer the notification relates to.

**Comment by MaikVermeulen** [comment]
Great discussion guys, thanks for the clarification.

Personally I would like to propose to add a pointer to a user object to the notifications. That way, on timeout or ACK, we can notify the application. The user object e.g. could be a pointer to a structure { measurement, timestamp } or whatever. The application could even add a unique identifier to that structure. I think this would solve the data buffering case quite well, leaving storage to the users and just having LwM2M as a transport protocol. One could have a list of measurements in e.g. RAM and get feedback on which ones are done and which ones are not. That list would indicate cleanly the number of live notifications, and buffer the data until ACKed. One drawback I do see is that the data would be duplicate, as it's in the notifications in the LwM2M engine, and in the user application.

As for the use-cases described in #38531, I think this user object way could work as well?
And of course, if you see alternative approaches, please share!

**Comment by JPSELC** [comment]
This is the messages array variable in lwm2m_engine.c

static struct lwm2m_message messages[CONFIG_LWM2M_ENGINE_MAX_MESSAGES];

which limits the maximum number of messages that are "active", and so limits the memory used by Zephyr for notifications. I think this may default to 3 or something like that, but obviously is configurable.
I think this is the array that the user needs visibility into. e.g. how many active messages?
I also think that if a notification times out, or the CONFIG_LWM2M_ENGINE_MAX_MESSAGES limit is reached, you are effectively offline (even if temporarily), and should start storing notifications in user space.
Perhaps at this point:
https://github.com/zephyrproject-rtos/zephyr/blob/d75b7a65076d8e3912fa8249a3030d23e1153f9e/subsys/net/lib/lwm2m/lwm2m_engine.c#L4236

**Comment by MaikVermeulen** [comment]
For everyone interested:
```
Currently on Github I see that there are 3 or so issues all related to buffering/handling intermittent connectivity.

For focussed discussion, I think it would be nicer to have a central thread on it.
I’ve made a thread ‘Client offline mode, data buffering, etc.’ in the LwM2M channel on the Discord.
```

**Comment by huelsenfruchtzwerg** [comment]
>  I also think that if a notification times out, or the CONFIG_LWM2M_ENGINE_MAX_MESSAGES limit is reached, you are effectively offline (even if temporarily), and should start storing notifications in user space.

Right now notifications will wait for space for new messages to be available and create them at that point.

**Comment by rlubos** [comment]
Hey, I was not able to dig in the detail into the code yet, but just to clarify:
* Each notification should use the same token as the one present in the initial GET message triggering the observation. So you cannot differentiate between individual observations based on the token only (but I see you've already figured this out). This is covered by the CoAP observe spec.
* Individual notifications can be differentiated based on either CoAP Message ID value or the Observer option value. The latter should be incremented for each notification so that the observer can identify outdated notifications.

**Pull request closed without merging**
