### PR TITLE
runners: jlink: add option to erase flash range

### LINKED ISSUE #40201: runners:jlink: fail to flash board with protected sector when erase requested
**Describe the bug**
After change #39734 it is not possible to flash board with protected memory area. When erase of board is requested in jlink runner args, protection of memory cause error during mass erase and flash procedure stops. Issue is visible on stm32wb55 when part of memory that is used by second core is protected against erase. 

**To Reproduce**
Try to flash board with part of memory configured as protected with erase option enabled for jlink runner. 
board_runner_args(jlink "--device=STM32WB55xx" "--speed=4000" "--reset-after-load" "--erase")

**Expected behavior**
Board flashed successfully.

**Environment (please complete the following information):**)
 - Zephyr SDK 13.1
 - Zephyr: 404f67ab5e571b5e209ac59adc99edc15a3475d9

**Log**
J-Link>connect
Device "STM32WB55XX" selected.

Connecting to target via SWD
Found SW-DP with ID 0x6BA02477
DPIDR: 0x6BA02477
Scanning AP map to find all available APs
AP[2]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
AP[1]: AHB-AP (IDR: 0x84770001)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x410FC241. Implementer code: 0x41 (ARM)
Found Cortex-M4 r0p1, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 000BB00C SCS-M7
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 003BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 003BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 000BB9A1 TPIU
ROMTbl[0][5]: E0041000, CID: B105900D, PID: 000BB925 ETM
ROMTbl[0][6]: E0043000, CID: B105900D, PID: 005BB906 CTI
SetupTarget() start
WARNING: Secure Firmware detected @ 0x080CA000
Connecting to target AP[0]/Cortex-M4
CORE ID AP[0]:0x410FC241
CORE ID AP[0]/Cortex-M4 halted!
SetupTarget() end
Cortex-M4 identified.
J-Link>erase
Erasing device...
Comparing flash   [100%] Done.
Erasing flash     [100%] Done.

****** Error: Failed to erase chip @ address 0x08000000 (sector is locked)
Failed to erase chip.
Failed to execute RAMCode for chip erase!
J-Link: Flash download: Total time needed: 4.494s (Prepare: 0.025s, Compare: 0.000s, Erase: 4.461s, Program: 0.000s, Verify: 0.000s, Restore: 0.007s)
ERROR: Erase returned with error code -5.
J-Link>

### PR DESCRIPTION
**Pull request by bbilas**
Introduce a new option that allows the user to erase the flash range of the selected device.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/40201

Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>

### CODE REVIEW

**Review by erwango — APPROVED** [review]

**Review by mbolivar-nordic — COMMENTED** [review]
Hi, I am a bit confused about this PR. The issue it is fixing has a discussion where the agreed-upon approach is to add sector erase. Usually I interpret that to mean that we will just erase the areas that are affected by the image, but this PR seems to be erasing manually specified ranges instead. That seems different than the approach in the issue and like more work for the user. Was a regular sector erase not practical for some reason?

**Comment by bbilas** [comment]
> Hi, I am a bit confused about this PR. The issue it is fixing has a discussion where the agreed-upon approach is to add sector erase. Usually I interpret that to mean that we will just erase the areas that are affected by the image, but this PR seems to be erasing manually specified ranges instead. That seems different than the approach in the issue and like more work for the user. Was a regular sector erase not practical for some reason?

It seems that your approach sounds much better than the proposed one. Is there any easy way to obtain the information about the flash range used by the image in the runner script?

**Comment by mbolivar-nordic** [comment]
@bbilas at least for Nordic SoCs and according to this case report, JLinkExe should do sector erase by default when `--erase` is not given: https://devzone.nordicsemi.com/f/nordic-q-a/52596/jlinkexe-equivalent-of-nrfjprog---sectorerase

I see that this patch is for an STM32 part only, though, so perhaps that does not apply.

However, the JLink runner will flash a .hex file preferentially if one exists (see code near the comment "Get the build artifact to flash" in jlink.py), so I wonder if we can fix this issue for that particular board by:

1. not using --erase
2. enabling CONFIG_BUILD_OUTPUT_HEX=y in the board defconfig

@Zzzwierzak since you were the original reporter of https://github.com/zephyrproject-rtos/zephyr/issues/40201, can you please test the above approach?

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Putting a -1 on here for now while we have an alternative approach untested

**Pull request closed without merging**
