### PR TITLE
boards: arm: Add support for Avnet MicroZed board

### PR DESCRIPTION
**Pull request by marek-vedral**
Add support for the MicroZed system on module [1]. This configuration is based on the existing port of Digilent Zybo, which is officially supported and has the same Xilinx Zynq-7000 SoC.

The commit #50969, adding a 1:1 mapping for SLCR registers, has not been approved yet. I have included the commit here to allow the system to use Ethernet.

Cc: Michal Sojka <michal.sojka@cvut.cz>
Signed-off-by: Marek Vedral <marek.vedral@gmail.com>

[1]: https://www.avnet.com/wps/portal/us/products/avnet-boards/avnet-board-families/microzed/

### CODE REVIEW

**Comment by marek-vedral** [comment]
Cc @wentasah

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Blocking for the same reason as given in https://github.com/zephyrproject-rtos/zephyr/pull/50969#pullrequestreview-1135851138

**Comment by ibirnbaum** [comment]
@henrikbrixandersen @marek-vedral I take that as a pointer to finally get this clock control driver thing done...

I don't know this board so far, but a while ago, I did a board definition (including a Vivado/Vitis tutorial) for the Zedboard on a branch in my personal Github space. With the Zedboard, there's a chance of running the blinky sample, as the board has exactly *one* LED attached to the PS GPIO controller which is always available, while the other LEDs, slider switches and push buttons on the board must be made accessible by adding instances of the AXI GPIO controller IP to the FPGA bitstream. Is there a similar situation with this board? If so, I'd suggest, as I have done with my Zedboard definition, to provide the DT entries for the optional AXI GPIO controller IPs as a DT overlay file, so that those GPIO instances can be added to the Zephyr build if a suitable bitstream is loaded into the FPGA upon power-up.

**Comment by marek-vedral** [comment]
> @henrikbrixandersen @marek-vedral I take that as a pointer to finally get this clock control driver thing done...
> 
> Is there a similar situation with this board? If so, I'd suggest, as I have done with my Zedboard definition, to provide the DT entries for the optional AXI GPIO controller IPs as a DT overlay file in the board directory, so that those GPIO instances can be added to the Zephyr build if a suitable bitstream is loaded into the FPGA upon power-up.

I don't think so. I did not use the FPGA at all, the button and LED are wired to specific pins corresponding to the PS GPIO controller, as you said. As for the second button, and LED, these don't appear to be connected to the SoC at all and are used for hardware resets.

I am not sure what you mean by "slider switches", but the three jumpers control the boot device. I am not sure wether these may be accessed - the MicroZed HW Users Guide does not explicitly say that they are adjustable, but the jumpers are connected to PS_MIO pins 2,4 and 5 (thus shuould be controlled by GPIO bank 0).

**Comment by wentasah** [comment]
Can this be reopened? I'd still like to get MicroZed support merged eventually.

**Pull request closed without merging**
