### PR TITLE
Bluetooth: Fix size-creep of RX/TX buffers & contexts

### LINKED ISSUE #21049: Bluetooth: Multiple issues with net_buf usage
- There's code using BT_BUF_USER_DATA_MIN even though this has been meaningless for awhile due to the global Kconfig setting for all net_bufs. What's worse, BT_BUF_USER_DATA_MIN isn't flagged as deprecated.
 - The memory footprint got recently bloated because HCI command user data got moved into a separate array
 - Luckily, thanks to the previous point, we can reduce the Bluetooth default net_buf user data size from 8 to 4

### PR DESCRIPTION
**Pull request by jhedberg**
The recent deadlock fixes for the RX/TX buffers & contexts had the unfortunate side-effect of increased memory footprint. Luckily they also open up the possibility of reducing the footprint by us now having a smaller requirement on the net_buf user data.

These three patches remove usage of the deprecated BT_BUF_USER_DATA_MIN macro and reduces the default net_buf user data from 8 to 4 bytes. The end result is now close to where we were before the recent redesign.

Fixes #21049

### CODE REVIEW

**Comment by jhedberg** [comment]
@jukkar @ozhuraki you might want to take a look at the `subsys/net/Kconfig` change for NET_BUF_USER_DATA_SIZE. I'm actually thinking we could simplify this even further by having the defaults such that one can always fit a pointer into the user data, i.e. have it 4 bytes for 32-bit and 8 bytes for 64-bit systems.

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]
+1 to net_buf changes

**Review by tbursztyka — APPROVED** [review]
net_buf change looks fine to me

**Review by ozhuraki — APPROVED** [review]
LGTM

**Comment by dleach02** [comment]
is there an issue addressed by this PR?

**Comment by jhedberg** [comment]
> is there an issue addressed by this PR?

@dleach02 yes, #21049. I've added a proper reference to the PR description.

**Review by joerchan — APPROVED** [review]

**Pull request merged**
