### PR TITLE
shields: remove link board can

### PR DESCRIPTION
**Pull request by jfischer-no**
Remove link board can, shield was discontinued in
prototype status and will be replaced by a successor.

### CODE REVIEW

**Review by pabigot — APPROVED** [review]

**Comment by alexanderwachter** [comment]
We used this shield as kind of a sample to demonstrate how to use the mcp2515.
Can't we just leave it in the tree?

**Comment by pabigot** [comment]
If it's not an Arduino shield it [shouldn't be here as an Arduino shield](https://github.com/zephyrproject-rtos/zephyr/pull/21979#discussion_r367936396).

How about instead adding a shield definition for https://www.sparkfun.com/products/13262 and using that for the example?  Here's all you'd need to do:
```
commit cdd53161e671ec59b020304006e412f1b084bcb2
Author: Peter Bigot <peter.bigot@nordicsemi.no>
Date:   Thu Jan 16 10:05:31 2020 -0600

    boards: shields: link_board_can: correct GPIO specification
    
    The shield GPIO specifiers should be in terms of the Arduino header,
    not whatever target board gpio1 was used to test this.
    
    The shield support does not clearly identify the specific shield.
    Google suggests this may be the SparkFun CAN-Bus Shield.  Update both
    cs-gpios and the MCP2515 interrupt signal to match the SparkFun v13a
    schematic.  Note that SparkFun Uno header pin labeling does not match
    Zephyr's enumeration.
    
    Also remove the Nordic-specific MISO/MOSI/SCK pin specifications;
    these also belong in the board devicetree node.
    
    Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

diff --git a/boards/shields/link_board_can/link_board_can.overlay b/boards/shields/link_board_can/link_board_can.overlay
index 66ee34c409..4c35f3c9e5 100644
--- a/boards/shields/link_board_can/link_board_can.overlay
+++ b/boards/shields/link_board_can/link_board_can.overlay
@@ -6,15 +6,12 @@
 
 &spi1 {
        status = "okay";
-       cs-gpios = <&gpio1 3 0>;
-       sck-pin = <36>;
-       mosi-pin = <37>;
-       miso-pin = <38>;
+       cs-gpios = <&arduino_header 16 0>; /* D10 */
 
        mcp2515@0 {
                compatible = "microchip,mcp2515";
                spi-max-frequency = <1000000>;
-               int-gpios = <&gpio1 7 GPIO_INT_ACTIVE_LOW>;
+               int-gpios = <&arduino 19 GPIO_INT_ACTIVE_LOW>; /* D13 */
                status = "okay";
                label = "CAN_1";
                reg = <0>;
```

**Comment by jfischer-phytec-iot** [comment]
I also do not understand the confusion with Arduino Shield, it is not mentioned anywhere.

@alexanderwachter 
I will send you appropriate number of replacements once the successor is manufactured.

**Comment by pabigot** [comment]
> I also do not understand the confusion with Arduino Shield, it is not mentioned anywhere.

OK, that's a fair point, and I should have noticed that it wasn't referencing `arduino_spi` and left it alone in my first pass at #21979.  But every other shield overlay that provided `cs-gpios` was Arduino-compatible, and the overlay had no documentation, so I made some "reasonable" assumptions.

**Comment by pabigot** [comment]
I would be OK with leaving this shield in-tree if it clearly documented where it came from (manufacturer, actual product identifier not just "link-board-can" ) and made clear what sort of shield it is.  Maybe there should be `link_gpio` and `link_spi` labels if "link" is the name for the header configuration used on reel-board.

In its current form it's creating extra work during tree-wide maintenance because this information is not readily available.

**Comment by alexanderwachter** [comment]
> I also do not understand the confusion with Arduino Shield, it is not mentioned anywhere.
> 
> @alexanderwachter
> I will send you appropriate number of replacements once the successor is manufactured.

I'll appreciate having the new board then :-)
Still, we can't use the new board as a sample for MCP2515.
Usually, if somebody want's to use the MCP2515, all you need to do is copy the shield and adapt the IOs.

**Comment by jfischer-phytec-iot** [comment]
> > I also do not understand the confusion with Arduino Shield, it is not mentioned anywhere.
> > @alexanderwachter
> > I will send you appropriate number of replacements once the successor is manufactured.
> 
> I'll appreciate having the new board then :-)
> Still, we can't use the new board as a sample for MCP2515.
> Usually, if somebody want's to use the MCP2515, all you need to do is copy the shield and adapt the IOs.

There is dfrobot_can_bus_v2_0 shield which can be used as generic one or as example. That is why I am not so sad to remove it :smile:.

**Comment by alexanderwachter** [comment]
> There is dfrobot_can_bus_v2_0 shield which can be used as generic one or as example. That is why I am not so sad to remove it smile.

Overlooked this one :-)

**Review by alexanderwachter — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Pull request merged**
