### PR TITLE
Remove Quark D2000 SoC, dev board, and related drivers.

### PR DESCRIPTION
**Pull request by ghost**
We are dropping support for the Quark series, and the D2000 is the first.

### CODE REVIEW

**Comment by gnuless** [comment]
Even among the Quarks, the D2000 is an oddball, especially with its use of a non-standard interrupt controller.  This opens up the way to clean house with respect to interrupt architecture on x86 and potential consolidation with x86-64.

**Review by dbkinder — APPROVED** [review]
Looks like it removes all the d2000 docs and samples docs, and references to d2000

**Review by dcpleung — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
```
i9:zephyr((HEAD detached from upstream/pull/16987)): git grep mvic
CODEOWNERS:/include/drivers/mvic.h                   @andrewboie
dts/bindings/interrupt-controller/intel,mvic.yaml:      constraint: "intel,mvic"

$ git grep d2000

doc/guides/test/sanitycheck.rst:        identifier: quark_d2000_crb
doc/guides/test/sanitycheck.rst:     west build -b quark_d2000_crb
doc/guides/test/sanitycheck.rst:     cmake -DBOARD=quark_d2000_crb ..
doc/guides/test/sanitycheck.rst:            platform_exclude: quark_d2000_crb

```

**Comment by gnuless** [comment]
@nashif Fixed as requested, but Shippable died on unrelated failure.

**Review by nashif — APPROVED** [review]

**Pull request merged**
