### PR TITLE
Backport NRF UART/E fixes

### PR DESCRIPTION
**Pull request by rerickson1**
Backport all NRF UARTE fixes that have not made it to the 1.14 branch.  
Addresses #24076.

### CODE REVIEW

**Comment by rerickson1** [comment]
Looks like a lot of warnings for the doc build that are unrelated to any of these commits.  Not sure how to resolve that.

**Comment by rerickson1** [comment]
@carlescufi FYI, need this tagged properly for back-porting to 1.14 thanks!

**Comment by carlescufi** [comment]
@anangl can you review this please?

**Comment by carlescufi** [comment]
CCB: No objections pending PR approval

**Review by anangl — COMMENTED** [review]
I'm not sure I understand why you decided to add those two last commits to this PR.
The first one that backports dcdc61cfdbf65b50cfdfa01e7f40daf08a58615a ("drivers: serial: nrf_uarte: Allow TX only instance") introduces an enhancement, it's not fixing anything. And it in fact introduces the problem that the second commit ("drivers: nrf: uarte: check if RXSTARTED before issue STOPRX ") is fixing. So it seems you could drop those two commits.
But if the intention was to actually backport this enhancement, you should also backport its follow-up (commit 729a9b0050d8885882959ffec665b36314e268a0, "drivers: serial: nrfx_uarte: Improve TX only mode). And for consistency it would be good to also backport the same enhancement for UART (commit 6a6063b57a5c79872b92cfc89de97e000be058db, "drivers: serial: nrfx_uart: Allow TX only mode").

**Comment by rerickson1** [comment]
> I'm not sure I understand why you decided to add those two last commits to this PR.
> The first one that backports [dcdc61c](https://github.com/zephyrproject-rtos/zephyr/commit/dcdc61cfdbf65b50cfdfa01e7f40daf08a58615a) ("drivers: serial: nrf_uarte: Allow TX only instance") introduces an enhancement, it's not fixing anything. And it in fact introduces the problem that the second commit ("drivers: nrf: uarte: check if RXSTARTED before issue STOPRX ") is fixing. So it seems you could drop those two commits.
> But if the intention was to actually backport this enhancement, you should also backport its follow-up (commit [729a9b0](https://github.com/zephyrproject-rtos/zephyr/commit/729a9b0050d8885882959ffec665b36314e268a0), "drivers: serial: nrfx_uarte: Improve TX only mode). And for consistency it would be good to also backport the same enhancement for UART (commit [6a6063b](https://github.com/zephyrproject-rtos/zephyr/commit/6a6063b57a5c79872b92cfc89de97e000be058db), "drivers: serial: nrfx_uart: Allow TX only mode").

Thanks for the feedback, agree with your comments.  I dropped those two commits and tested with my example: https://github.com/rerickson1/nrf52840_lpm
I would also like to get https://github.com/zephyrproject-rtos/zephyr/pull/24209 incorporated as well, but waiting for feedback/approval on that.

**Comment by rerickson1** [comment]
Incorporated the #24209 fix.

**Comment by carlescufi** [comment]
@anangl could you take another look please?

**Comment by anangl** [comment]
@rerickson1 Please update the commit taken from #24209.

**Comment by rerickson1** [comment]
@anangl Done, grabbed the latest commit.

**Review by anangl — APPROVED** [review]

**Review by Mierunski — APPROVED** [review]

**Comment by rerickson1** [comment]
@nashif Anything else needed to get this merged?

**Pull request merged**
