### PR TITLE
drivers: ieee802154: deprecate OT "sleep" nomenclature

### LINKED ISSUE #62995: drivers: ieee802154: deprecate/rename "SLEEP" capability/event
**Problem Description**

The concept of "sleeping" is being used in the "SLEEP_TO_TX" hardware capability as well as in the "SLEEP" event. This concept has a well defined meaning in Zephyr related to threading and power management, though, which differs from OpenThread's definition as "RX off".

**Proposed Solution**

- I propose that we deprecate the "SLEEP_TO_TX" capability altogether as it is redundant (see explanation in the attached commit) and conflicts with all of Zephyr's nomenclature, #61227, RFC 2863, Thread standard and IEEE 802.15.4. This hardware capability just binds the API to an internal implementation detail of OpenThread.
- I propose to rename the "SLEEP" event to "RX_OFF" which conforms to the nomenclature in Zephyr, this API and IEEE 802.15.4.

Also compare https://github.com/zephyrproject-rtos/zephyr/pull/63255/commits/3dec95ee6b32456b8f499e9130bbb5838ab825ca where the distinction between operational state and receiver state has been implemented for the CC13/26xx SubG driver. I think something similar should be introduced in the nRF5 driver (and all other drivers) for RFC 2863 standard compliance.

**Alternatives**

I first considered just renaming the "sleep to TX" hw capability but then I realized that it really breaks standard/Zephyr requirements badly plus is redundant with a properly implemented RX slot implementation - unless I'm overlooking something.

**Additional context**

See the requirements outlined in #61227.

### PR DESCRIPTION
**Pull request by ghost**
*NOT meant for Zephyr v3.5. A section will be added to the release notes for 3.6 once those are out.*

"Sleeping" has a well defined meaning in Zephyr related to threading and power management. This differs from OpenThread's definition:

- Deprecates the "SLEEP_TO_TX" capability as it is redundant and conflicts with all of Zephyr's nomenclature, #61227, RFC 2863, Thread standard and IEEE 802.15.4. This binds the API to an implementation detail of OpenThread, instead.

- Renames the "SLEEP" event to "RX_OFF" which conforms to the nomenclature in Zephyr, this API and IEEE 802.15.4.

Fixes: #62995 (Enhancement Request), see there for a detailed rationale and analysis.

### CODE REVIEW

**Review by rlubos — CHANGES_REQUESTED** [review]
No issue with `SLEEP` -> `RX_OFF` transition, but not ok with deprecating `IEEE802154_HW_SLEEP_TO_TX` capability. It was introduced with a specific power optimization in mind (see https://github.com/openthread/openthread/issues/4689 for details) and I see no relevance to scheduled reception here.

**Comment by fgrandel** [comment]
> No issue with `SLEEP` -> `RX_OFF` transition, but not ok with deprecating `IEEE802154_HW_SLEEP_TO_TX` capability. It was introduced with a specific power optimization in mind.

Yeah, I'm aware of that. That's why I've specified a well-defined distinction between "interface UP/DOWN" (as required by the net stack / RFC 2863) and "receiver ON/OFF" (as required by OT L2 - and many other use cases, including TSCH). The recently updated driver spec defines how you can manage the two separately:
* start/stop manages interface UP/DOWN
* RX slots can be used with well-defined "magic" start values (see IEEE802154_CONFIG_RX_SLOT_OFF and IEEE802154_CONFIG_RX_SLOT_NONE in the radio API and the corresponding description in IEEE802154_CONFIG_RX_SLOT) to ensure the receiver will either be immediately turned off or on (when the interface state is already UP) or that the receiver will not turned on when calling start() (when the interface is initially DOWN)

I think it is required that we can manage the two states separately, as RFC 2863 specifies that an interface SHALL NOT pass packets while it is "DOWN". "Sleep to TX" however would be able to transport a packet even if the administrator has requested the interface to remain in "DOWN" mode.

What I mean by deprecation in this case means: We only remove "sleep to TX" *after* OT has been updated to no longer use start/stop to manage the receiver but the newly introduced direct receiver management.

**Comment by rlubos** [comment]
The problem I see is that RX slot management (at least for now) has a dependency to the `IEEE802154_HW_RXTIME` capability while the currently used `IEEE802154_HW_SLEEP_TO_TX` has not (for example Thread SED does not require `IEEE802154_HW_RXTIME`). So we're creating artificial requirements here (at least with current proposal).

**Comment by fgrandel** [comment]
> The problem I see is that RX slot management (at least for now) has a dependency to the `IEEE802154_HW_RXTIME` capability while the currently used `IEEE802154_HW_SLEEP_TO_TX` has not (for example Thread SED does not require `IEEE802154_HW_RXTIME`). So we're creating artificial requirements here (at least with current proposal).

That is true - we have to think more about how we can decouple this.

**Comment by jciupis** [comment]
> Could the non-standard "sleep to TX" capability maybe become a direct configure() call setting the standard MAC PIB attribute macRxOnWhenIdle directly

I believe `IEEE802154_HW_SLEEP_TO_TX` capability represents something different than `macRxOnWhenIdle`. The latter determines whether the receiver should be enabled when the interface is idle. What the capability indicates is whether it's possible to transition the transceiver directly from `RX_OFF` to `TX`. In other words, it describes the capability of the driver when the interface is _not_ idle.

Consider a driver configured with `macRxOnWhenIdle` equal false, so that the receiver is turned off when the interface is idle. When a frame is to be transmitted and the interface stops being idle, the `macRxOnWhenIdle` holds no information which state the transceiver should enter because it describes the transceiver's behavior in a different state - idle. Therefore it seems to me this is not the solution here.

I'm wondering though if there's a way to avoid exposing such a capability to the driver's user at all. I see it's only used in Openthread:
https://github.com/zephyrproject-rtos/zephyr/blob/026dbdf5392ea0cb96ff8a9a204a2d239de096a5/modules/openthread/platform/radio.c#L793-L796

@edmont Would it be feasible to move the responsibility for correctly transitioning the transceiver to transmit state one layer down, to the driver? This way the code above could call `run_tx_task` unconditionally (or at least with loosened condition on the radio state) and the driver would perform the needed steps, be it `RX_OFF` -> `RX_ON` -> `TX` or directly `RX_OFF` -> `TX`, depending on the hardware capabilities.

**Comment by fgrandel** [comment]
@jciupis Thank you for taking the time to better explain the SLEEP_TO_TX capability. Very much appreciated!

> I see it's only used in Openthread

Correct - plus it's only implemented in the nRF5 driver and it seems that it cannot be cleanly mapped to any standard primitive. That's why I suspected that it may have to be reviewed along the lines of #61227.

> the `macRxOnWhenIdle` holds no information which state the transceiver should enter because it describes the transceiver's behavior in a different state - idle.

I agree.

> I'm wondering though if there's a way to avoid exposing such a capability to the driver's user at all.

Agreed. This should be an implementation detail of the driver if anyhow possible. Which of our drivers requires RX on before TX at all? Sounds like a rather exotic requirement?

Moving this implementation detail inside the driver only solves half of the problem, though. We still need a way for OT to manage RX on/off state independently from start/stop.

Combining all our arguments, we seem to need the following changes then (ordered):
* We deprecate the SLEEP_TO_RX capability without removing it yet.
* We extend the driver API such that RX on/off can be managed "directly" independently from start/stop (my argument), timed RX (@rlubos 's argument) and macRxOnWhenIdle (@jciupis 's argument). macRxOnWhenIdle was a bad idea anyway as it's a complex MAC-level feature and we're looking for something much lower-level. What we need corresponds to the direct vs. timed TX distinction. We probably simply need configure(rx_on/rx_off) which may be called in any operational state but will only take effect when/while the driver is UP. Alternatively we could have a separate rx() method for improved symmetry with tx() but I'd say that symmetry would be rather artificial and therefore prefer to extend configure() - do you agree?
* Then the nRF5 driver needs to implement the new configure() call. The other drivers don't have to be migrated yet as they don't interface with OT. Migrating them shouldn't be too difficult either, though. We don't need a new capability for this feature as the configure() call returns -ENOTSUP anyway when the feature isn't implemented.
* OT would then be changed to use the new configure() API instead of start/stop and remove all references to SLEEP_TO_RX.
* Finally we can remove the SLEEP_TO_TX capability from the nRF5 driver and from the API. The driver doesn't have to be changed, otherwise, as it has the SLEEP_TO_TX capability unconditionally and we assume that future drivers will manage the details of RX off to TX transition internally.

Does this sound like a plan?

**Comment by rlubos** [comment]
>  IIRC, SEDs use standard indirect transmission in Thread. How long does a SED switch their receiver on after a data request (pointer to the spec is enough - I can read it up there)? 

Yes, SED use indirect transmission, however I'm not actually sure if we can call it "standard". Thread 1.2 introduced a feature called "Enhanced Frame Pending" (described in Thread 1.3.0 specification, ch. 3.2.6.2), which seems to be listed as a modification to the standard. But it's more of a FYI, it shouldn't really matter in this regard.

As for the RX on time in this mode, I don't think it can be specified beforehand, as it depends on whether there is some actual data pending for the SED or not. If the parent (coordinator) replies with Frame Pending bit set to 0, the receiver can be turned off immediately. Otherwise, it should remain on as long as the parent reports there is more data to come (again, as indicated by the Frame Pending bit).

> Does this sound like a plan?

Sounds fine to me.

**Comment by edmont** [comment]
> @edmont Would it be feasible to move the responsibility for correctly transitioning the transceiver to transmit state one layer down, to the driver? This way the code above could call `run_tx_task` unconditionally (or at least with loosened condition on the radio state) and the driver would perform the needed steps, be it `RX_OFF` -> `RX_ON` -> `TX` or directly `RX_OFF` -> `TX`, depending on the hardware capabilities.

This would be possible as long as `otPlatRadioGetCaps` returns `OT_RADIO_CAPS_SLEEP_TO_TX` unconditionally and we make sure that every Zephyr driver supports this transition.

This is required because `RadioSpinel<InterfaceType>::Transmit` contains this check, so a Zephyr's RCP build should communicate this capability.

**Comment by fgrandel** [comment]
> As for the RX on time in this mode, I don't think it can be specified beforehand, as it depends on whether there is some actual data pending for the SED or not. If the parent (coordinator) replies with Frame Pending bit set to 0, the receiver can be turned off immediately. Otherwise, it should remain on as long as the parent reports there is more data to come (again, as indicated by the Frame Pending bit).

@rlubos Yes, of course you're right. That's why it was a bad idea by myself to use any of the MAC-level PIB attributes here. The time to listen after a data request is macResponseWaitTime btw if I'm not mistaken, so in theory all standard timings *could* be derived. But as we all agree, it's not the driver's responsibility but L2's to calculate the timings and communicate them at a lower level to the driver.

**Comment by edmont** [comment]
> @edmont Should some future driver not support this nor be able to deal with it as an implementation detail, we can still re-introduce some (if possible: standard-based) capability or derive it from a return code. But unless we have a requirement I think it is adequate to simplify the API instead, do you agree?

I do.

**Comment by fgrandel** [comment]
Thanks everyone for your input.

@rlubos I reworded the deprecation notice and commit message to represent our discussion result. I also opened a new issue (#63670) that captures the agreed migration path away from the "sleep to TX" capability. Does this render this PR acceptable from your pov?

**Review by rlubos — APPROVED** [review]

**Review by jciupis — APPROVED** [review]

**Pull request merged**
