### PR TITLE
dts: esp32c6: add i2c support

### PR DESCRIPTION
**Pull request by RomainPelletant**
- Add I2C support on esp32c6
- Add I2C0 port node in xiao_esp32c6 board
- Add I2C0 port node in esp32c6_devkitc board
- Update manifest to target new hal_espressif revision (for [i2c hal support](https://github.com/zephyrproject-rtos/hal_espressif/pull/380) on esp32c6)

This [PR](https://github.com/zephyrproject-rtos/hal_espressif/pull/380) has been merged first on hal_espressif repository.

Updates #29394

### CODE REVIEW

**Review by gmarull — DISMISSED** [review]

**Comment by wmrsouza** [comment]
Please rebase on top of main, since #82813 was merged

**Comment by sylvioalves** [comment]
Hal side merged: 9fbf519573e713bd92bb8222bcfef77e7219584b

**Review by raffarost — DISMISSED** [review]

**Review by wmrsouza — DISMISSED** [review]

**Comment by sylvioalves** [comment]
@RomainPelletant, we need to wait #82746 be merged before this one due to hal changes.

**Review by uLipe — DISMISSED** [review]

**Review by wmrsouza — APPROVED** [review]

**Comment by sylvioalves** [comment]
@RomainPelletant, can you re-arange the commit order?
1) Manifest update
2) SoC and/or pinctrl changes
3) Boards

Although this is not mandatory, it is a way to make sure the board change (adding I2C) will be indeed buildable.

**Comment by RomainPelletant** [comment]
@sylvioalves it has been done (order). I added support for esp32c6_devkitc since the initial proposal

**Review by raffarost — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]

**Pull request merged**
