### PR TITLE
Bluetooth: Host: Remove deprecated HCI driver API

### PR DESCRIPTION
**Pull request by jhedberg**
Remove the deprecated HCI driver API which was provided by the hci_driver.h
header file. The deprecation happened in Zephyr 3.7, so the API can now be
removed for Zephyr 4.1.

### CODE REVIEW

**Review by LingaoM — DISMISSED** [review]

**Review by lylezhu2012 — DISMISSED** [review]

**Review by rugeGerritsen — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]

**Comment by jhedberg** [comment]
I had to tweak #ifdefs in `hci_core.c` a bit more to ensure that unit tests pass, since some of them don't have a `zephyr,bt-hci` chosen property. Now the code accepts a missing chosen property, but only when `CONFIG_ZTEST=y`. In other cases a build assert gets triggered (easier for a human to parse than DT build errors). Hopefully CI should pass now.

**Review by alwa-nordic — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]

**Comment by jhedberg** [comment]
The remaining CI failures seem to be due to unrelated issues. I'll trigger a re-run once fixes for those have been merged.

**Comment by jhedberg** [comment]
CI is passing now. @LingaoM @lylezhu2012 @rugeGerritsen please re-approve if you're still fine with the PR. Thanks.

**Review by rugeGerritsen — DISMISSED** [review]

**Review by LingaoM — DISMISSED** [review]

**Review by lylezhu2012 — DISMISSED** [review]

**Review by kartben — CHANGES_REQUESTED** [review]
although one could say people knew this was coming, we do need a mention in the release notes - thanks!
see ex. https://docs.zephyrproject.org/latest/releases/release-notes-4.0.html#removed-apis-in-this-release

**Comment by jhedberg** [comment]
> although one could say people knew this was coming, we do need a mention in the release notes - thanks! see ex. https://docs.zephyrproject.org/latest/releases/release-notes-4.0.html#removed-apis-in-this-release

@kartben done. I actually did take a look at some of the other PRs linked from #77069 and didn't immediately see that the release notes were being touched, but you're right that it makes sense to mention there.

**Review by kartben — DISMISSED** [review]

**Comment by jhedberg** [comment]
Heh.. I knew it was a risky move to start trying to use more advanced documentation syntax in the release notes, and now the Documentation build fails. @kartben do you know what would be the right way to make an inline reference to a doxygen group, like I tried to do?

**Review by rugeGerritsen — DISMISSED** [review]

**Comment by jhedberg** [comment]
> Heh.. I knew it was a risky move to start trying to use more advanced documentation syntax in the release notes, and now the Documentation build fails. @kartben do you know what would be the right way to make an inline reference to a doxygen group, like I tried to do?

I solved it (hopefully) by making a reference to `doc/connectivity/bluetooth/api/hci_driver.rst` which in turn has the reference to the doxygen group.

**Comment by kartben** [comment]
> > Heh.. I knew it was a risky move to start trying to use more advanced documentation syntax in the release notes, and now the Documentation build fails. @kartben do you know what would be the right way to make an inline reference to a doxygen group, like I tried to do?
> 
> I solved it (hopefully) by making a reference to `doc/connectivity/bluetooth/api/hci_driver.rst` which in turn has the reference to the doxygen group.

https://docs.zephyrproject.org/latest/contribute/documentation/guidelines.html#role-c-group :)
Your "workaround" is fine by me so no need to update the PR again if you don't feel like it

**Comment by jhedberg** [comment]
> https://docs.zephyrproject.org/latest/contribute/documentation/guidelines.html#role-c-group :)
> Your "workaround" is fine by me so no need to update the PR again if you don't feel like it

Now updated to use `:c:group:`. Thanks for the pointer to the documentation! I think I failed to find it since I was looking for examples of directives with "doxygen" in the name, like what's used here:
https://github.com/zephyrproject-rtos/zephyr/blob/f235ddb2cf261eccd93633e4a91060f71008ec6b/doc/connectivity/bluetooth/api/hci_drivers.rst?plain=1#L11

**Review by kartben — APPROVED** [review]

**Comment by jhedberg** [comment]
@alwa-nordic @lylezhu2012 @LingaoM @rugeGerritsen one more approval needed here and then this should be ready to go in. Thanks.

**Review by LingaoM — APPROVED** [review]

**Review by rugeGerritsen — APPROVED** [review]

**Pull request merged**
