### PR TITLE
driver: nrfx_uarte: Handle RXTO ISR only if it's expected

### PR DESCRIPTION
**Pull request by spanceac**
When initializing the UARTE driver, a check is present for the case where UARTE RX was left enabled by a bootloader.
If it's enabled, the code will call the STOPRX task and wait in loop for one of the RXTO or ERROR event flags to be set.

The check for ERROR event was added in
https://github.com/spanceac/zephyr/commit/e729e6db10763b87bc02e6508b4aef9d76945f61 with the assumption that if an ERROR event is present, an RXTO event might not come.

But an RXTO event triggered by the STOPRX task still might come after the initialization phase and the RXTO ISR will be triggered. If the RXTO interrupts triggers, depending on its timing, it can cause problems.
For example, if an UARTE API user registered an UARTE events handler callback and enabled RX, it will receive invalid UART_RX_BUF_RELEASED and UART_RX_DISABLED events.

This commit attempts to fix this issue by adding a flag to determine if the RXTO interrupt is expected and decide whether to handle it or not.

### CODE REVIEW

**Comment by nordic-krch** [comment]
I think that we got it wrong in the first place (I mean https://github.com/spanceac/zephyr/commit/e729e6db10763b87bc02e6508b4aef9d76945f61). According to the documentation RXTO will always come event after ERROR occurred and in all those years we never seen a case where it didn't. It is more likely that we falsely assumed that if RXSTARTED event is set during the initialization it means that RX is active but it maybe that RXSTARTED  and ERROR events are not handled by the bootlooder driver but RXTO is.

It would be better to rework initialization and trigger STOPRX and wait for RXTO with timeout and if it timeouts we can assume that RX is stopped.

**Comment by spanceac** [comment]
@nordic-krch I think we can assume that the bootloader might do unexpected things, like triggering the `STOPRX` task without clearing `RXSTARTED` flag and/or `ERROR` flag. When the initialization process starts we can assume that the UART RX is in an unknown state regardless of the `RXSTARTED` flag. Since we don't know the real state, I think the safest way is to try to stop RX. But I don't know if an `RXTO` event is still generated if UART is already stopped and we trigger the `STOPRX` task. I will do a test and see

**Comment by spanceac** [comment]
I have checked, and if I call the `STOPRX` task and UART is already stopped, the `RXTO` never comes. So we need to trigger the `STOPRX` task and wait for `RXTO` with a timeout. From my observations of how long it takes for `RXTO` to come and reading the documentation, it seems that the timeout should be 4x the time it takes to receive a byte at the current baudrate. So the code should read the baudrate register and derive the timeout from there. I can do it like this if we agree upon the idea

**Comment by bjarki-andreasen** [comment]
I created an alternative solution which simply removes the potential `STOPRX` task from the init of the UARTE peripheral. It is not up to the application to do cleanup from a failing bootloader, the bootloader must leave the UARTE in an idle state with events cleared.

**Comment by MaureenHelm** [comment]
@bjarki-andreasen @anangl ping?

**Comment by nordic-krch** [comment]
IMO this should be closed as #75703 solves that issue.

**Comment by spanceac** [comment]
Closing because alternative solution https://github.com/zephyrproject-rtos/zephyr/pull/75703 was merged

**Pull request closed without merging**
