### PR TITLE
TF-M: increase default Mbed TLS heap size in TF-M

### LINKED ISSUE #79864: tests: subsys: jwt: libraries.encoding.jwt.rsa.psa fails
**Describe the bug**
The test `tests/subsys/jwt/libraries.encoding.jwt.rsa.psa` fails

Observed for:
- `nrf5340dk/nrf5340/cpuapp/ns`
- `nrf9160dk/nrf9160/ns`

**To Reproduce**
1. have `nrf9160dk/nrf9160/ns` connected
2. go to your zephyr dir
3. call `./scripts/twister -T tests/subsys/jwt -p nrf9160dk/nrf9160/ns --device-testing --device-serial /dev/ttyACM0 -v --inline-logs  --west-flash="--erase"`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v3.7.0-4339-g1ec5ce05f9f8 ***
Running TESTSUITE jwt_tests
===================================================================
START - test_jwt

    Assertion failed at zephyr/tests/subsys/jwt/src/main.c:48: jwt_tests_test_jwt: (res not equal to 0)
Signing payload
 FAIL - test_jwt in 0.022 seconds
===================================================================
TESTSUITE jwt_tests failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [jwt_tests]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.022 seconds
 - FAIL - [jwt_tests.test_jwt] duration = 0.022 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: 8cf83447ecd64014499884f8a73d7731
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
- OS: Ubuntu 20.04.1 LTS
- Toolchain Zephyr SDK 0.16.8
- Commit SHA or Version used: `v3.7.0-4232-g9b5260de9a31`

**Additional context**
Probably introduced by 29e82d2f23b099ead21a045a869818e24552de87

### PR DESCRIPTION
**Pull request by valeriosetti**
This PR updates the TF-M reference in to include a couple of commits which are useful to properly size the heap memory allocated in TF-M for the crypto partition. This is necessary in order to allow Mbed TLS to handle RSA signatures with 2048-bits (previously only 1024-bits were possible).

Resolves #79864

### CODE REVIEW

**Review by tomi-font — DISMISSED** [review]

**Review by kartben — DISMISSED** [review]

**Review by ithinuel — DISMISSED** [review]

**Comment by d3zd3z** [comment]
So, this seems reasonable, at least as far as RSA goes, but do you know where the requirement for RSA at all is coming from?

**Comment by valeriosetti** [comment]
> So, this seems reasonable, at least as far as RSA goes, but do you know where the requirement for RSA at all is coming from?

If you meant "who is willing to use RSA signatures with 2048-bits" then I was notified by this issue https://github.com/zephyrproject-rtos/zephyr/issues/79864.

Instead if your question was more like "why RSA needs so much heap memory", it's because TF-M uses Mbed TLS in its crypto partition to perform crypto operations and there RSA uses heap memory a lot (through `bignum` module, in case you are curious).

Luckily the TF-M team already spotted this issue recently and they already had a fix for it, so it was quite easy for me to cherry-pick the fix from them.

@d3zd3z did I answered your question?

**Review by tomi-font — CHANGES_REQUESTED** [review]
Please change at least the title of the commit to be more explicit about what this is for than `update reference`.

**Review by tomi-font — DISMISSED** [review]

**Comment by valeriosetti** [comment]
I had to rebase to solve a conflict on `west,yml`. Please re-check :)

**Review by tomi-font — APPROVED** [review]

**Review by frkv — APPROVED** [review]
LGTM

(Reasonable addition to ensure better support for RSA)

**Comment by valeriosetti** [comment]
@ithinuel @kartben since your last approval I only changed the title of the commit as requested by @tomi-font. Can you please take another look when you have some time?

**Review by carlescufi — APPROVED** [review]

**Review by ithinuel — APPROVED** [review]

**Pull request merged**
