### PR TITLE
MAINTAINERS: add a separate area for blackmagicprobe runner

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Add an area for Black Magic Probe and myself as maintainer. It's just a runner file and does not get much traffic, but I have the hardware to test this and use it regularly so I may as well get PRs for this from the bot.

### CODE REVIEW

**Review by kartben — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
Thank you!

**Review by nashif — APPROVED** [review]

**Review by MaureenHelm — COMMENTED** [review]
Appreciate you taking this on @fabiobaltieri , but isn't this the same as someone creating an area for one specific driver, which we've pushed back on in other cases?

**Comment by fabiobaltieri** [comment]
> Appreciate you taking this on @fabiobaltieri , but isn't this the same as someone creating an area for one specific driver, which we've pushed back on in other cases?

Almost certainly, you tell me, I'm not particularly vocal about this but the last few of these got thrown my way anyway because few people use this, figures this would make it happen automatically and not after weeks of no response.

**Review by cfriedt — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@MaureenHelm what's the verdict? yay or nay? I'm not too emotionally attached to either option, just want this PR off my queue, happy to close it :-)

**Comment by MaureenHelm** [comment]
> @MaureenHelm what's the verdict? yay or nay? I'm not too emotionally attached to either option, just want this PR off my queue, happy to close it :-)

I'd rather see one west runners area and treat it like a driver class.

**Comment by fabiobaltieri** [comment]
> I'd rather see one west runners area and treat it like a driver class.

Sounds good, let's reevaluate down the road then.

**Pull request closed without merging**
