### PR TITLE
Normalize .cc extensions to .cpp

### PR DESCRIPTION
**Pull request by yperess**
Rename all .cc files to .cpp (note that no .hh files were found).
Addresses #44196

Signed-off-by: Yuval Peress <peress@google.com>

### CODE REVIEW

**Review by stephanosio — COMMENTED** [review]
Thanks.

What about the `h` to `hpp` changes?

**Comment by yperess** [comment]
I ran the same for .hh but couldn't find any.
Going through the pain .h files to see which are strictly C++ will have to be done by hand and will take longer.

**Comment by stephanosio** [comment]
> I ran the same for .hh but couldn't find any.
> Going through the pain .h files to see which are strictly C++ will have to be done by hand and will take longer.

Here I am mainly referring to the h files in the same directories as these cpp files.

**Comment by yperess** [comment]
> > I ran the same for .hh but couldn't find any.
> > Going through the pain .h files to see which are strictly C++ will have to be done by hand and will take longer.
> 
> Here I am mainly referring to the h files in the same directories as these cpp files.

Gotcha, OK, some headers were used by `.c` files so I left those with `.h`, but updated the rest.

**Review by MaureenHelm — APPROVED** [review]

**Review by laurenmurphyx64 — APPROVED** [review]
LGTM, thanks for making the changes.

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
