### PR TITLE
boards: rv32m1_vega: fix the location of the YAML file

### PR DESCRIPTION
**Pull request by mbolivar**
This needs to match the defconfig name.

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by nashif** [comment]
why does the board directory has a different name?

**Comment by galak** [comment]
> why does the board directory has a different name?

probably because its like arduino_101 and has multiple different cores.

**Comment by nashif** [comment]
> probably because its like arduino_101 and has multiple different cores.

but the arduino_101 is split into multiple boards with consistent naming:

```
boards/arc/arduino_101_sss/arduino_101_sss.yaml
boards/x86/arduino_101/arduino_101.yaml
```

**Comment by mbolivar** [comment]
> but the arduino_101 is split into multiple boards with consistent naming:

What is not consistent about the vega naming? _ri5cy is when you want to target the RI5CY core. There is also a ZERO-RISCY core we do not have upstream support for yet but would like to add, it will have a _zero_riscy substring in the defconfig name.

Is there just one YAML file for *all* thes variants which is the common basename of the board, or one YAML file *per* variant?

**Comment by mbolivar** [comment]
> How will you add the ZERO-RISCY core support? in the same directory or as a separate board configuration?

same directory

**Comment by nashif** [comment]
ok, this is the direction we want to go with in the future anyways based on discussion started in #12401, so I think it is fine.

**Review by nashif — APPROVED** [review]

**Review by kgugala — APPROVED** [review]

**Pull request merged**
