### PR TITLE
MAINTAINERS: Add myself to kernel as a collaborator

### PR DESCRIPTION
**Pull request by TaiJuWu**
Add myself to kernel as a collaborator

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by TaiJuWu** [comment]
Ping @andyross @peter-mitsis @cfriedt

**Review by cfriedt — CHANGES_REQUESTED** [review]
I'm not necessarily blocking this (maybe I'm missing some other important information) but I just would like to point out that TaiJuWu has [only made 3 commits to Zephyr](https://github.com/zephyrproject-rtos/zephyr/pulls?q=is%3Apr+author%3ATaiJuWu+is%3Aclosed+is%3Amerged).

Based on the [TSC Project Roles and meritocratic process](https://docs.zephyrproject.org/latest/project/project_roles.html), and given that the kernel is a fairly critical part of Zephyr, should we maybe let TaiJuWu soak for a bit before being granted Collaborator status?

**Review by cfriedt — APPROVED** [review]
I have the missing info now 👍

**Review by henrikbrixandersen — APPROVED** [review]
Thanks for stepping up!

**Review by andyross — APPROVED** [review]

**Pull request merged**
