### PR TITLE
Imxrt1050 add a1 silicon support

### PR DESCRIPTION
**Pull request by jhqian**
Add A1 silicon support for RT1050

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
The commit message for the update to ext for the SDK files should say what version of the new files you are pulling in.

**Comment by jhqian** [comment]
Updated commit message with SDK version

**Comment by jhqian** [comment]
Any other comment for this PR?

**Comment by MaureenHelm** [comment]
Will revisit after the next MCUXpresso SDK release

**Pull request closed without merging**
