### PR TITLE
boards: stm32h747i_disco: adjust openocd reset config and debug

### PR DESCRIPTION
**Pull request by gmarull**
Summary:

- I have experienced some problems when flashing this board using OpenOCD. Adding `connect_assert_srst` forces reset assertion before any connection atempt (`srst_nogate` is required).
- Add necessary entries to debug CM7 core using OpenOCD.

### CODE REVIEW

**Comment by erwango** [comment]
I'm fine with the change but I'd like to have a test and I don't have the board right now.
I'll try to get the board by tomorrow and review again.

**Comment by gmarull** [comment]
@erwango I have to say that sometimes openocd just works with current settings, but some others there's no way to program the board. With these reset settings I have 100% success rate when flashing. I'm using `Open On-Chip Debugger 0.10.0+dev-01341-g580d06d9d-dirty (2020-05-16-15:41)`.

**Review by erwango — APPROVED** [review]
Tested OK

**Review by KozhinovAlexander — APPROVED** [review]
Same as my PR #29688, except separate config for M4. I've also tested this settings and can confirm necessity. Therefore approved from me and thank you!

P.S.: @gmarull @erwango Can we put this configs to some common directory for all stm32h7 dual core SoC's? It looks like, it can be reused by multiple boards.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
