### PR TITLE
tests: device: Optimize prj.conf to improve code coverage

### PR DESCRIPTION
**Pull request by Intel-sp**
The testcase cover the Z_SYSCALL_HANDLER(device_get_binding, name),
but the lcov tool didn't include. And add CONFIG_NEWLIB_LIBC=y to
make lcov tool include the function.

Signed-off-by: Peng Su <peng.su@intel.com>

### CODE REVIEW

**Review by LeiW000 — APPROVED** [review]
One line change. It looks good to me.

**Review by nashif — CHANGES_REQUESTED** [review]
Not following how another libc gives you coverage from a basic functions that should also work with any other libc.

**Comment by LeiW000** [comment]
I dig it more. But I have not found why enabling "CONFIG_NEWLIB_LIBC" can make " Z_SYSCALL_HANDLER(device_get_binding, name)" included in code coverage report. So the change in this code view is a workaround. Without the workaround,  Z_SYSCALL_HANDLER(device_get_binding, name) it reported as "not be covered", although it has been called by the code in "tests/kernel/device".

The test cases in "tests/kernel/device" are enabled only for platform "native_posix" "native_posix_64" "qemu_x86". So it is safe to enable "CONFIG_NEWLIB_LIBC" on those platforms. 

We need to get this workaround merged today to make function code coverage of kernel 100% for 2.0 release. After it, we will continue to look into it to find the root cause. Maybe, it is a gcov or lcov issue. We just need more time.

@nashif  and all reviewer, are you OK to approve this PR?

**Comment by LeiW000** [comment]
Close this PR as the issue will be fixed with #18825.

**Pull request closed without merging**
