### PR TITLE
samples: mesh_demo: Reduce footprint for bbc micro:bit

### LINKED ISSUE #55328: samples: bluetooth: Bluetooth Mesh sample has 55-byte RAM overflow on BBC micro:bit
**Describe the bug**

* Follow the instructions at https://docs.zephyrproject.org/3.1.0/samples/bluetooth/mesh_demo/README.html to build Bluetooth Mesh sample for micro:bit 
* Build fails during the linking phase due to RAM overflow:
```
/Users/kartben/zephyr-sdk-0.15.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../../../../arm-zephyr-eabi/bin/ld.bfd: region `RAM' overflowed by 55 bytes
```

**To Reproduce**

See above

**Expected behavior**

Compilation should work and user should be able to flash their micro:bit

**Impact**

This sample claims to be "specially" designed for the micro:bit, so it'd be great if it'd work out-of-the-box!

**Environment (please complete the following information):**

macOS, SDK 0.15.2
Zephyr 6a5a2534a0556b04be83f6149cb4bd8e4f66d77f

### PR DESCRIPTION
**Pull request by carlescufi**
The sample no longer fits in RAM, reduce the number of discardable packets to make it fit.

Fixes #55328.

### CODE REVIEW

**Review by kartben — DISMISSED** [review]
I can confirm that this fixes the issue, thanks! Not able to test on a real device tho.

**Comment by alxelax** [comment]
Hi @carlescufi, I fixed it here: https://github.com/zephyrproject-rtos/zephyr/pull/55327

**Comment by PavelVPV** [comment]
> Hi @carlescufi, I fixed it here: #55327

Could you include Carles's solution into your PR? This would release even more RAM in the sample.

**Comment by alxelax** [comment]
> > Hi @carlescufi, I fixed it here: #55327
> 
> Could you include Carles's solution into your PR? This would release even more RAM in the sample.

I'll rebase if it goes in first.

**Review by jhedberg — DISMISSED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by carlescufi** [comment]
> > > Hi @carlescufi, I fixed it here: #55327
> > 
> > 
> > Could you include Carles's solution into your PR? This would release even more RAM in the sample.
> 
> I'll rebase if it goes in first.

I think we should merge this one first and then discuss a bit more about the complete removal.

**Review by PavelVPV — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
