### PR TITLE
drivers: can: remove deprecated APIs

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Remove the CAN APIs deprecated in Zephyr v3.0.0.

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Comment by nashif** [comment]
when was this marked as deprecated?

**Comment by henrikbrixandersen** [comment]
> when was this marked as deprecated?

Just before v3.0.0, but the CAN API is marked unstable so deprecations are not enforced (so neither is the two release cycle rule).

**Comment by nashif** [comment]
> Just before v3.0.0, but the CAN API is marked unstable so deprecations are not enforced (so neither is the two release cycle rule).

ok. Why is still unstable btw? It has been there for a while.

**Comment by henrikbrixandersen** [comment]
> ok. Why is still unstable btw? It has been there for a while.

This is what I have been working on fixing for the last few months or so ;) Please see #36724.

**Review by alexanderwachter — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
@alexanderwachter Please re-review. I had to rebase to fix CI.

**Review by alexanderwachter — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Pull request merged**
