### PR TITLE
github: hello_world_multiplatform: run on Ubuntu 24.04

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Run the multi-platform Hello World build on Ubuntu 24.04.

### CODE REVIEW

**Review by nashif — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
Note: The Ubuntu 24.04 runner is only in public beta so far:
- https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/
- https://github.com/actions/runner-images/issues/9848

I was just trying to assert whether something had changed in the runner, affecting the Zephyr build.

**Comment by henrikbrixandersen** [comment]
I think it's safe to say the GitHub Ubuntu 24.04 runners are still not quite ready.

**Comment by henrikbrixandersen** [comment]
@aescolar The `native_sim` failure on Ubuntu 24.04 seems to be related to https://github.com/actions/runner-images/issues/9977#issuecomment-2153044449. Should we attempt to fix this before LTSv3?

**Comment by aescolar** [comment]
> @aescolar The `native_sim` failure on Ubuntu 24.04 seems to be related to [actions/runner-images#9977 (comment)](https://github.com/actions/runner-images/issues/9977#issuecomment-2153044449). Should we attempt to fix this before LTSv3?

I have a VM with Ubuntu24.04 and this sample builds and runs just fine both standalone and run by twister.
I guess to be able to know what the problem is one would need to run this docker image locally. But at this point I would  not even assume that error is coming from the native_sim executable.

**Comment by henrikbrixandersen** [comment]
> > @aescolar The `native_sim` failure on Ubuntu 24.04 seems to be related to [actions/runner-images#9977 (comment)](https://github.com/actions/runner-images/issues/9977#issuecomment-2153044449). Should we attempt to fix this before LTSv3?
> 
> I have a VM with Ubuntu24.04 and this sample builds and runs just fine both standalone and run by twister. I guess to be able to know what the problem is one would need to run this docker image locally. But at this point I would not even assume that error is coming from the native_sim executable.

The comment which I linked to says:

> That is expected as the CONFIG_COMPAT_32BIT_TIME kernel option is not enabled on ubuntu24 (and likely will never be), we do not patch kernel ourselves as we take the stock azure's sku, as a result we can not help solving this, unfortunately.

Is `CONFIG_COMPAT_32BIT_TIME ` enabled in the Ubuntu 24.04 Linux kernel, you are running (`grep CONFIG_COMPAT_32BIT_TIME /boot/config-$(uname -r)`)?

**Comment by aescolar** [comment]
> Is `CONFIG_COMPAT_32BIT_TIME ` enabled in the Ubuntu 24.04 Linux kernel, you are running (`grep CONFIG_COMPAT_32BIT_TIME /boot/config-$(uname -r)`)?

Yes. It is the default kernel distributed by Ubuntu with 24.04. Not some custom thing.

From that comment you linked at, what I gather is that somebody at Microsoft decided to roll their own custom kernel in their default "Ubuntu 24.04" Azure VM images, with that feature purposely disabled. And that github for their "ubuntu-24.04" runners just uses that image.
So what I understand is that Github's "ubuntu24.04" is not actual Ubuntu 24.04, but "Microsoft's Linux based on Ubuntu 24.04".

**Comment by aescolar** [comment]
```
$ grep CONFIG_COMPAT_32BIT_TIME /boot/config-$(uname -r)
CONFIG_COMPAT_32BIT_TIME=y
$ uname -a
Linux <redacted> 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```

**Comment by henrikbrixandersen** [comment]
> Yes. It is the default kernel distributed by Ubuntu with 24.04. Not some custom thing.
> 
> From that comment you linked at, what I gather is that somebody at Microsoft decided to roll their own custom kernel in their default "Ubuntu 24.04" Azure VM images, with that feature purposely disabled. And that github for their "ubuntu-24.04" runners just uses that image.
> 
> So what I understand is that Github's "ubuntu24.04" is not actual Ubuntu 24.04, but "Microsoft's Linux based on Ubuntu 24.04".

Right. That still leaves us with the issue of not being able to run 32-bit native_sim on the GitHub hosted Ubuntu 24.04 runners.

**Comment by aescolar** [comment]
> Right. That still leaves us with the issue of not being able to run 32-bit native_sim on the GitHub hosted Ubuntu 24.04 runners.

So it seems :), I guess one option is to ask MS to enable back this feature in their VM's kernel. Because clearly we are not the only ones affected.

**Comment by aescolar** [comment]
@henrikbrixandersen I peeked thru the linked issues from other projects' CI and it seems they just stuck w ubuntu22.04 for the jobs where they hit the issue.

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen I peeked thru the linked issues from other projects' CI and it seems they just stuck w ubuntu-22.04 for the jobs where they hit the issue.

Sure, that's an option, but we would _like_ to run on this platform in CI, as this is what many downstream Zephyr users will begin using.

**Comment by aescolar** [comment]
> Sure, that's an option, but we would _like_ to run on this platform in CI, as this is what many downstream Zephyr users will begin using.

Of course. That's why I pinged the GH guy who closed the issue.
All I intended was to provide more context about the situation: "There is quite a few other projects with this same issue. And, so far, what they did is keep using with the previous github image version"

**Comment by henrikbrixandersen** [comment]
Upstream bug report: https://bugs.launchpad.net/ubuntu/+source/linux-signed-azure/+bug/2071445

**Comment by aescolar** [comment]
The fixed kernel is in 24.04, things build and run fine :)

**Review by fabiobaltieri — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
