### PR TITLE
drivers: uart_nsim: Add device tree support

### PR DESCRIPTION
**Pull request by galak**
Add Device Tree support for uart nsim ARC driver.  Utilize the binding
from Linux that is "snps,arc-uart".

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@ruuddw @vonhust I wondering if the nsim uart driver should be renamed as it might not be specific to nsim.

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]
tested with nsim board, works

**Comment by galak** [comment]
> > 
> 
> I believe the Linux arc_uart is actually a different one. This nsim_uart is a simple, minimal simulator uart. How about a dts binding like "snps,nsim-uart"?

I'm happy to rename, I glanced at the linux driver drivers/tty/serial/arc_uart.c the register map looked similar/identical.

**Comment by ruuddw** [comment]
Yes, they all are similar (16550 like), but different...
Please rename for consistency to nsim-uart, and thanks for the DTS update - it was reuse of a pre-dts driver when added...

**Comment by galak** [comment]
> Yes, they all are similar (16550 like), but different...
> Please rename for consistency to nsim-uart, and thanks for the DTS update - it was reuse of a pre-dts driver when added...

Ok, no worries, will make the change.

**Comment by galak** [comment]
> Ok, no worries, will make the change.

@ruuddw should be updated now.

**Review by ruuddw — APPROVED** [review]

**Pull request merged**
