### PR TITLE
boards: arduino_opta: add M7 core support

### PR DESCRIPTION
**Pull request by uLipe**
With the release of the schematic of the Arduino OPTA, it makes sense to support both cores to run Zephyr, this PR adds it, and exposes some of the features.

Please notice the schematic lacks of some information of the WIFI+BT combo, so they are not supported this time, on the other hand USB and Ethernet access are available.

For console purpose it is possible to use the side expansion connector and wire the UART pins from there, the documentation mentions that

### CODE REVIEW

**Comment by uLipe** [comment]
Added some extra information, the OPTA has two applications scenarios:

*  Zephyr M7r + Zephyr M4  Images: the image on the M4 has the base address located to the beginning of the second flash bank
*  Arduino M7 + Zephyr M4: In this case Arduino code sets the boot address of the M7 to 0x8008000.

In the second case, it is not possible to use the same DTS configuration, we need to create a code partition with custom address, and it was done on the previous PR: https://github.com/zephyrproject-rtos/zephyr/pull/64101 which brought the support for the M4, the solution adopted here, is to make default Zephyr + Zephyr configurations, and point in the documentation how to create an overlay file with the code partition when mixing Arduino code with Zephyr code.

Other than that, tested on Hardware a set of samples on both cores. 

It is unfortunate that the debug port is not exposed  on Opta.

**Review by nordicjm — CHANGES_REQUESTED** [review]
Duplicate of https://github.com/zephyrproject-rtos/zephyr/pull/77297

**Comment by uLipe** [comment]
I was not aware of that, thank you.

@pillo79 , do you think there is something here that can enhance the other PR?

**Comment by uLipe** [comment]
Closing this one in favor of the existing original PR, I'm going to work on the additional support.

**Pull request closed without merging**
