### PR TITLE
samples:  spi_pico_pio:  Sample to demonstrate SPI PIO driver

### PR DESCRIPTION
**Pull request by ThreeEights**
Simple adaptation of zephyr/samples/sensor/bme280 to use the SPI PIO driver for the Raspberry Pi Pico.

### CODE REVIEW

**Comment by ThreeEights** [comment]
@yonsch - Could you join in the review on this pull request?  It really should have been included in the last PR, but it wasn't ready back then, so this has been sitting on my hard drive ever since.

Thanks,
Steve

**Comment by yonsch** [comment]
This seems very similar to the original sample, why do you need a new one?

**Comment by ThreeEights** [comment]
@yonsch - That's a great philosophical question - and just the discussion I was hoping for.  One option is adding this sample under samples/boards/rpi_pico, to show that it's a demonstration of the special features of that board.  The alternative would be to just add the rpi_pico.overlay to the existing samples/sensor/bme280 sample.  I would like there to be some way to indicate that this addition specifically demonstrates the use of the PIO SPI driver.  I also don't know of a way to force CONFIG_SPI=y for that specific build configuration.

What would you recommend?

**Comment by yonsch** [comment]
In my opinion the point of PIO is that the drivers implemented with it act like "real" peripherals, not requiring modifications to the code using them. So I think it would be nicer to see that overlays is all that it takes to make this sample run over PIO rather than "real" SPI.

**Comment by ThreeEights** [comment]
@yonsch - That makes sense.  I'll close out this pull request and start over.

**Pull request closed without merging**
