### PR TITLE
Zephyr: Fix double promotions

### PR DESCRIPTION
**Pull request by XenuIsWatching**
This the same as https://github.com/zephyrproject-rtos/zephyr/pull/38958 but without the last commit that add the compile flag.

I don't think it's quite ready yet for the flag until the build issues with modules are sorted out yet.

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by aescolar — COMMENTED** [review]
+1 for the native_posix changes.

**Review by bbolen — APPROVED** [review]

**Comment by cfriedt** [comment]
@XenuIsWatching - is this ready yet?

**Comment by XenuIsWatching** [comment]
> @XenuIsWatching - is this ready yet?

Yes.... sorry if I wasn't clear in the original topic. This is all ready to go... but it's just that adding the warning flag globally is not yet (which is not in this pull request)

**Comment by cfriedt** [comment]
@XenuIsWatching - I'll add `DNM` for now. Please ping me when it can be merged.

**Comment by XenuIsWatching** [comment]
> @XenuIsWatching - I'll add `DNM` for now. Please ping me when it can be merged.

@cfriedt Sorry, if I wasn't clear. This all ready to be merged

**Pull request merged**
