### PR TITLE
enable PCB antenna on Particle boards

### LINKED ISSUE #14123: Particle boards need a board initialization module for antenna configuration
The Particle boards have a SKY13351 SPDT switch that selects between a PCB antenna and an external uFL antenna.  On the Xenon the Zephyr board initialization probably leaves this in an unconfigured mode, resulting in neither antenna being connected and so very poor RF performance.  Driving P0.24 high enables the PCB antenna, which adds more than 10 dB.  Driving P0.25 high enables the uFL antenna.

For Xenon to be useful as a Bluetooth/6LowPAN device it needs a board initialization function that configures P0.24 for write and sets the GPIO.  Whether API to select the external antenna is necessary is up to whoever solves this.

I discovered this while doing performance analysis of my non-Zephyr framework, and have not looked at Argon or Boron.  By the schematic they both have the same switch, but the pins to select the antenna are different on Argon, and Boron has a single signal that also needs to be driven.

### LINKED ISSUE #15374: PR 15230 introduces test failure for particle_argon
git bisect identifies 7b1ee5cf13dc4f130b556534bd4c8dd78ceec6c6 as introducing this failure, which blocks testing of #15369.
```
lilith[402]$ git reset --hard 7b1ee5cf13dc4f130b556534bd4c8dd78ceec6c6
HEAD is now at 7b1ee5cf13 tests: CONFIG_TEST_USERSPACE now off by default
lilith[403]$ rm -rf argon ; west build -d argon -b particle_argon tests/drivers/spi/spi_loopback/
source directory: /mnt/devel/external/zp/zephyr/tests/drivers/spi/spi_loopback
build directory: /mnt/devel/external/zp/zephyr/argon (created)
BOARD: particle_argon
Zephyr version: 1.14.0
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.7", minimum required is "3.4") 
-- Selected BOARD particle_argon
-- Found west: /home/pab/.local/bin/west (found suitable version "0.5.7", minimum required is "0.5.6")
-- Loading /mnt/devel/external/zp/zephyr/boards/arm/particle_argon/particle_argon.dts as base
-- Overlaying /mnt/devel/external/zp/zephyr/dts/common/common.dts
particle_argon.dts.pre.tmp:312.23-315.5: Warning (simple_bus_reg): /soc/virtualcom: missing or empty reg/ranges property
Parsing Kconfig tree in /mnt/devel/external/zp/zephyr/tests/drivers/spi/spi_loopback/Kconfig
Loading /mnt/devel/external/zp/zephyr/boards/arm/particle_argon/particle_argon_defconfig as base
Merging /mnt/devel/external/zp/zephyr/tests/drivers/spi/spi_loopback/prj.conf
Configuration written to '/mnt/devel/external/zp/zephyr/argon/zephyr/.config'
-- Cache files will be written to: /home/pab/.cache/zephyr
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Performing Test toolchain_is_ok
-- Performing Test toolchain_is_ok - Success
Including module: tinycbor in path: /mnt/devel/external/zp/modules/lib/tinycbor
CMake Warning at ../../../../CMakeLists.txt:1468 (message):
  

        ------------------------------------------------------------
        --- WARNING:  __ASSERT() statements are globally ENABLED ---
        --- The kernel will run more slowly and use more memory  ---
        ------------------------------------------------------------


-- Configuring done
CMake Error at ../../../../cmake/extensions.cmake:357 (add_library):
  No SOURCES given to target: drivers__spi
Call Stack (most recent call first):
  ../../../../cmake/extensions.cmake:334 (zephyr_library_named)
  ../../../../drivers/spi/CMakeLists.txt:1 (zephyr_library)


-- Build files have been written to: /mnt/devel/external/zp/zephyr/argon
ERROR: command exited with status 1: /usr/local/bin/cmake -B/mnt/devel/external/zp/zephyr/argon -H/mnt/devel/external/zp/zephyr/tests/drivers/spi/spi_loopback -GNinja -DBOARD=particle_argon
run as "west -v build -d argon -b particle_argon tests/drivers/spi/spi_loopback/" for a stack trace
```

### PR DESCRIPTION
**Pull request by pabigot**
Without this initialization code no antenna is selected, and Bluetooth signal quality is at least 7 dBi less than it could be.

Also added a patch for the unrelated test failure.

Closes #14123 
Closes #15374

### CODE REVIEW

**Comment by pabigot** [comment]
The build failure occurs on master commit 42d330406e on which this PR is based.  When somebody fixes that I'll rebase and resubmit.

**Comment by cvinayak** [comment]
@pabigot if the same skyworks PA/LNA in use you can use the BLE controller's dynamic PA/LNA control, see https://github.com/zephyrproject-rtos/zephyr/pull/12832

**Comment by pabigot** [comment]
@cvinayak maybe, but that patch doesn't seem as clear about what it's doing.  There will need to be an ability to control selection of PCB and u.FL antenna based on the target configuration, but it should be outside the BLE infrastructure since Particle devices are also used in non-BLE networks.

In any case, this code is what I'm using in my fork, and I just wanted to get something upstreamed since the devices perform very poorly without enabling the antenna.

**Comment by cvinayak** [comment]
@pabigot ok.. I misread SKY13351, as its mere RF switch, you are right its not related to BLE radio events. 

Nit-pick, preferrably use GPIO APIs instead of CMSIS calls, so new contributors can re-use (copy) implementation when they are adding new boards having SKY13351 to other SoCs.

**Review by mike-scott — CHANGES_REQUESTED** [review]
Agree with @cvinayak and switch to standard GPIO APIs.  Other than that LGTM.

**Comment by pabigot** [comment]
@mike-scott @cvinayak switching to the Zephyr GPIO driver is a fair request, but upstreaming this isn't a priority to me so it's not going to happen anytime soon.  For whatever that's worth.

There's precedent for bypassing it (reel_board) if you'd rather see this in sooner.

IMO the correct approach would be to have a switch driver that ensures the switch isn't left in an undefined state, but that's way to much work.

**Comment by mike-scott** [comment]
@pabigot 
I have a new version of this series:
- Rebased on today's master
- Dropped first patch as it was already merged
- Using Zephyr GPIO APis with board.h files for clarity on the GPIO port/pin names
- Blended it into the existing boron board.c which sets up the serial buffer for the modem

See last 2 commits here: https://github.com/mike-scott/zephyr/tree/issue/14123

Consider reviewing and reposting here?

**Comment by pabigot** [comment]
@mike-scott Please open a PR with your solution; I'll review that and close this one.  Replacing this with yours seems too confusing.

**Comment by mike-scott** [comment]
@pabigot ok, I can submit it in a new PR.  Mainly, I wanted you to know it's based on your initial work here.  So thanks for getting it started.

**Pull request closed without merging**
