### PR TITLE
boards: x86: Add support for Intel Alder Lake boards

### PR DESCRIPTION
**Pull request by jhedberg**
Add basic support for Intel Alder Lake CRB and RVP boards

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Comment by jhedberg** [comment]
> Can we please move away from 3 charachter acronyms to something a bit more verbose? intel_adl or even intel_alderlake. This is starting get very cryptic IMO.

I'm fine with that. I think I'd prefer just adding the intel prefix and the short-hand platform version (i.e. `intel_adl`). The full name is still visible in documentation, etc. Would be good to try to convert all existing platforms within a fairly short time-window, however, so that we don't end up with some `intel_` prefixes and some boards without.

@najumon1980 FYI.

**Review by finikorg — DISMISSED** [review]
I will reuse common parts of the doc when PR #60440 is merged.

**Comment by nashif** [comment]
> I'm fine with that. I think I'd prefer just adding the intel prefix and the short-hand platform version (i.e. `intel_adl`).

yes, this is fine.

**Comment by jhedberg** [comment]
The board names have now been updated to have an intel_ prefix

**Comment by jhedberg** [comment]
@nashif @dcpleung could you please take another look? Thanks.

**Review by dcpleung — DISMISSED** [review]

**Review by najumon1980 — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
