### PR TITLE
NUCLEO-H745ZI-Q add ethernet driver support for Cortex-M4

### PR DESCRIPTION
**Pull request by KozhinovAlexander**
Adding ETH driver support for Cortex-M4 core on NUCLEO-H745ZI-Q board.

### CODE REVIEW

**Comment by erwango** [comment]
@Nukersson nothing wrong with the commits, but I don't see the link with the title of this PR.

**Comment by Nukersson** [comment]
> @Nukersson nothing wrong with the commits, but I don't see the link with the title of this PR.

I do not understand, what you exactly mean. Maybe this link to my branch: https://github.com/Nukersson/zephyr/tree/stm32h7_cortex_m4_add_ethernet_support
?

**Comment by Nukersson** [comment]
> @Nukersson nothing wrong with the commits, but I don't see the link with the title of this PR.

@erwango Can you see it now?

**Comment by erwango** [comment]
@Nukersson the PR title and description suggests you're doing something to the series/socs, but you're only doing changes in one board..

**Comment by Nukersson** [comment]
> @Nukersson the PR title and description suggests you're doing something to the series/socs, but you're only doing changes in one board..

You're right. Changed the name. Actually here is everything prepared on the SoC side.

**Comment by erwango** [comment]
> > @Nukersson the PR title and description suggests you're doing something to the series/socs, but you're only doing changes in one board..
> 
> You're right. Changed the name. Actually here is everything prepared on the SoC side.
> 
> @erwango Should I change branch name also? It would be a little bit tricky and may need closing this PR and opening a new one.

No need for the branch (I don't think there are much people looking to this), but editing also the PR description would be nice.

**Comment by Nukersson** [comment]
> ... but editing also the PR description would be nice

@erwango  Done

**Review by erwango — APPROVED** [review]

**Comment by Nukersson** [comment]
@ABOSTM @galak You're welcome for your reviews! And thank you very much!

**Review by galak — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
