### PR TITLE
shell: Kconfig: remove empty line at EOF

### PR DESCRIPTION
**Pull request by jhedberg**
Introduced by commit 5cf7b48eb475c424a89bee7c030805db09180e91

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
I'm surprised CI doesn't catch this kind of stuff. git highlights it as bright red for me.

**Review by galak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by jakub-uC — APPROVED** [review]

**Comment by jarz-nordic** [comment]
Kconfig cannot have an empty line at the end?

**Comment by jhedberg** [comment]
Actually, the issue was present in both shell.c and Kconfig. It was shell.c that it was introduced to by the commit I referenced. I just got confused by the title of the commit since it referred to Kconfig. I've fixed both issues and updated the commit message accordingly.

> Kconfig cannot have an empty line at the end?

@jarz-nordic it's considered redundant whitespace, like that at the end of lines or multiple empty lines. Git will highlight this in bright red if you've enabled color output, e.g. I have the following in my `~/.gitconfig`:
```
[diff]
	color = auto

[pager]
	color = true

[status]
	color = auto

[color]
	ui = auto

[apply]
	whitespace = fix
```

**Comment by jarz-nordic** [comment]
@jhedberg: I added this empty lines, its just my habit. It is because Keil compiler is giving a warning where there is no empty line at the end of file. I just need to use to the new practice ;)

**Comment by jhedberg** [comment]
> @jhedberg: I added this empty lines, its just my habit. It is because Keil compiler is giving a warning where there is no empty line at the end of file. I just need to use to the new practice ;)

Understood. That's I strange thing in Keil.. I wonder what's the rationale for it.

**Pull request merged**
