### PR TITLE
ARC: gcc-m-cpu: check for exact HS CPU type instead of whole family

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
As of today we check against CPU_ARCHS config option which may be related to different HS CPUs (i.e. ARCv2 HS, ARCv3 HS, etc...). 
Let's check against exact HS CPU type (CPU_HS3X) as we do EM processors.

### CODE REVIEW

**Review by abrodkin — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by ruuddw** [comment]
How does this relate to the different HS flavors described here?
https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/Understanding-GCC-mcpu-option#arc-hs

'hs' seems to be the generic option, hs34/hs38 the more specific ones.

**Comment by evgeniy-paltsev** [comment]
> How does this relate to the different HS flavors described here?
https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/Understanding-GCC-mcpu-option#arc-hs
'hs' seems to be the generic option, hs34/hs38 the more specific ones.

'hs' is generic for ARCv2 HS, but for ARCv3 HS we use mcpu=arc64.

**Comment by ruuddw** [comment]
What triggered my question is the "CONFIG_CPU_HS3x". I missed it in PR #33518: the help text says it is for both HS3x and HS4x.
This confused me, expecting HS3x to be HS3x specific and not HS4x.
Maybe CPU_HS3x_HS4x would be better? What's  your plan for config option for 64 bit ARC HS? Let's try and find some consistent, self explaning names.

**Comment by carlescufi** [comment]
@evgeniy-paltsev could you please reply to @ruuddw's question?

**Comment by IRISZZW** [comment]
maybe we need to use different mcpu options for boards: hsdk nsim_hs and arc_qemu_hs, https://github.com/zephyrproject-rtos/zephyr/issues/31757.

**Pull request closed without merging**
