### PR TITLE
west.yml: hal_ambiq: Update stimer HAL.

### PR DESCRIPTION
**Pull request by BryanZhuAM**
Update stimer HAL from latested AmbiqSuite.

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi @BryanZhuAM. I've merged your HAL PR. You can now update the revision in `west.yml` for Ambiq HAL to `ff4ca358d730536addf336c40c3faa4ebf1df00a`.

**Comment by BryanZhuAM** [comment]
> Hi @BryanZhuAM. I've merged your HAL PR. You can now update the revision in `west.yml` for Ambiq HAL to `ff4ca358d730536addf336c40c3faa4ebf1df00a`.

@fkokosinski Thanks for reminder, I have updated this PR

**Review by fkokosinski — APPROVED** [review]

**Comment by BryanZhuAM** [comment]
@tgorochowik Need one more approval for this HAL update, would you pls help on it?

**Review by tgorochowik — APPROVED** [review]
It would be nice if for such changes the reason for this update would be specified in the main PR message.

In this case in the corresponding HAL PR I see that it fixes one of the kernel tests on your board, but it's not immedietaly clear for people who look at this PR.

(Adding this comment also as a note to a person who will be merging this - this update is needed to fix kernel tests on ambiq boards).

Thanks!

**Comment by BryanZhuAM** [comment]
> ff4ca358d730536addf336c40c3faa4ebf1df00a

 @tgorochowik Thanks a lot for reminder, will follow this guide in the future

**Pull request merged**
