### PR TITLE
doc: logging: Fix some grammar issues

### LINKED ISSUE #64763: [doc] Documentation issue in 'services/logging/index'
This issue covers some grammatical fixes to the logging page, which will be addressed in the linked pull request.

I did notice that previous changes to the logging page removed the text about the `CONFIG_LOG_PROCESS_THREAD` Kconfig option. Was there a particular reason for that? If not, I am happy to make another change to add some text about using that option.

**Environment**

* Page: `services/logging/index`
* Version: main
* SHA-1: 503422b91e7bb3826231cea55602c7efe47ed4f9

### PR DESCRIPTION
**Pull request by adleris**
Fixes some grammar issues in the documentation.

Fixes #64763.

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]

**Review by kartben — CHANGES_REQUESTED** [review]
Brilliant stuff, thank you. 
Just a minor request for change, which you can address by also fixing the compliance issue (commit message should not be empty). Thanks!!

**Comment by kartben** [comment]
@adleris can you have a look at the compliance check error and my request for change? Thanks again for the PR!

**Review by nordic-krch — DISMISSED** [review]

**Comment by adleris** [comment]
@kartben apologies for the delay, I've fixed the compliance issue and your suggestion!

**Review by kartben — APPROVED** [review]
Excellent, thanks again!

**Review by nordic-krch — APPROVED** [review]

**Pull request merged**
