### PR TITLE
Sensor CMakeFile and Kconfig cleanup

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Clean and sort the include/source list, use the allow empty lib cmake thing. Saves trying to figure where to add new stuff.

Note: I don't have the slightest hope that this is enough to keep them consistent over time (the other lists I sorted are already off), so I think I'll followup with a precompliance validate that the block stays sorted (https://github.com/zephyrproject-rtos/zephyr/pull/58149).

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]
Thanks for this @fabiobaltieri ! It already needs a rebase. :)

**Comment by fabiobaltieri** [comment]
Ok it should be good now, the merge conflict markers were a bit odd not sure why, had to redo it from scratch.

**Review by MaureenHelm — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by nashif** [comment]
rebase

**Comment by fabiobaltieri** [comment]
Rebased, will get there eventually :-)

**Comment by fabiobaltieri** [comment]
Re-re-rebased. Adding sensors is a popular activity these days.

**Review by teburd — APPROVED** [review]

**Comment by teburd** [comment]
> Re-re-rebased. Adding sensors is a popular activity these days.

Probably one of the most active areas with first time and one time contributors

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
