### PR TITLE
[RFC] drivers/spi: implement a composite event for async callback

### PR DESCRIPTION
**Pull request by vlotech**
For not all applications the poll_signal interface is a practical solution to tell upper layers an asynchronous transfer is completed.
To allow different types of synchronization, a composite interface is made. Allowing semaphore (give), mutex (unlock), alert (send) and poll (signal) to be used depending on the application one of the given methods can be used.  

An additional method could be added, which is a callback function with the device as argument. This is not added to this composite interface yet. 

In case this is seen as a practical way of handling asynchronous callbacks, it could be extended to a generic implementation for all I/O drivers. 

Signed-off-by: Vincent van der Locht <vincent@vlotech.nl>

### CODE REVIEW

**Comment by carlescufi** [comment]
@vlotech the test are failing to build with your changes, can you take a look and add the additional changes required?

**Review by superna9999 — COMMENTED** [review]
I have no objection for this

**Comment by vlotech** [comment]
Figured out my editor was not handling tabs and spaces correct. 
That's solved now. I do notice that the checkpatch on github gives a different output than the one ran locally as described in the documentation.

**Comment by nashif** [comment]
@vlotech any update to this change? Can you please rebase.

**Comment by vlotech** [comment]
@nashif I've rebased the pull request and all checks have passed as requested. Please review the patches so it can be merged.

**Pull request closed without merging**
