### PR TITLE
tests: kernel: convert to ztest

### PR DESCRIPTION
**Pull request by nniranjhana**
Replaced test points with ztest APIs and split the main file into two - main.c, which has ztest entry and corresponding test file, which has the original routines.

JIRA: ZEP-2382

Signed-off-by: Niranjhana N <niranjhana.n@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
What's the impetus for this change?
For test cases that have just one test routine, what's the benefit to converting to ztest?
Please, provide some justification / JIRA links in the PR summary

**Comment by nniranjhana** [comment]
@andrewboie I have added descriptions and the JIRA link to the commits.
The arm_runtime_nmi routine does not need ztest (it is just one routine) - but I had added a ztest entry to the main function for obtaining similar outputs for all test files. Should I remove it?

**Comment by nashif** [comment]
> What's the impetus for this change?

Have one single way for writing tests, be consistent in how we write tests and get similar output from all tests to have better reports. 

> For test cases that have just one test routine, what's the benefit to converting to ztest?

Thats the thing, we have too many tests that have just one routine. Next time when we have something else to test in this area we should be able to easily add a new ztest test function to that same testcase and avoid writing new test from scratch. 

Eventually we should be able to group many tests together and have better coverage and faster test turnaround times, especially when testing on real hardware.

**Review by nashif — CHANGES_REQUESTED** [review]
scripts/sanity_chk/last_sanity.xml should not be checked in

**Comment by nniranjhana** [comment]
@nashif okay, removed it

**Pull request merged**
