### PR TITLE
tests: timer_behavior: jitter test using timer start delay and period

### PR DESCRIPTION
**Pull request by npitre**
Exercize both the timer start delay as wellas the timer period and
gather stats for each.

This was a wish from @teburd in PR #55345.

### CODE REVIEW

**Comment by teburd** [comment]
Testing this out on a sam e70 I get...

```
*** Booting Zephyr OS build zephyr-v3.3.0-963-g4f2c0b007ca1 ***
Running TESTSUITE timer_jitter_drift
===================================================================
START - test_jitter_drift_timer_period
periodic timer behavior test using built-in restart mechanism
collecting time samples for approx 10 seconds
periodic timer samples gathered, calculating statistics
timer clock rate 300000000, kernel tick rate 10000
period duration statistics for 10000 samples (0 rollovers):
  expected: 1000 us,            300000.000000 cycles
  min:      997.223333 us,      299167 cycles
  max:      1000.210000 us,     300063 cycles
  mean:     999.999656 us,      299999.896800 cycles
  variance: 0.003261 us,        293.473150 cycles
  stddev:   0.057104 us,        17.131058 cycles
timer start cycle 8312245, end cycle 3008311213,
total time 9999996.560000 us, expected time 10000000.000000 us,
expected time drift 0.000000 us, difference -3.440000 us
 PASS - test_jitter_drift_timer_period in 10.094 seconds
===================================================================
START - test_jitter_drift_timer_startdelay
periodic timer behavior test using explicit start with delay
collecting time samples for approx 10 seconds
periodic timer samples gathered, calculating statistics
FAIL - periodic_diff@99. Caught a timer wrap around which isn't handled!
FAIL - periodic_diff@99. Caught a timer wrap around which isn't handled!
timer clock rate 300000000, kernel tick rate 10000
period duration statistics for 9999 samples (1 rollovers):
  expected: 1000 us,            300000.000000 cycles
  min:      998.496667 us,      299549 cycles
  max:      1000.193333 us,     300058 cycles
  mean:     999.999844 us,      299999.953195 cycles
  variance: 0.000589 us,        53.026512 cycles
  stddev:   0.024273 us,        7.281930 cycles
timer start cycle 3040651016, end cycle 1745683257,
total time 61489146908048620.000000 us, expected time 10000000.000000 us,
expected time drift 0.000000 us, difference 61489146898048620.000000 us

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_behavior/src/jitter_drift.c:253: do_test_using: (abs(time_diff_us) < CO)
Drift (in microseconds) outside expected bound
 FAIL - test_jitter_drift_timer_startdelay in 10.128 seconds
===================================================================
TESTSUITE timer_jitter_drift failed.
```

Which I think is almost entirely because the wrap isn't dealt with. We'd need to define the wrap value for each timer driver to deal with this correctly from what I recall, especially as the systick timer count is 24 bits :(

Thoughts?

**Comment by npitre** [comment]
Is there a QEMU target for this I could use?

**Comment by andyross** [comment]
Pretty much all the qemu arm32 devices use systick (I'm sure there's an outlier somewhere): qemu_cortex_m3, mps2_an{385,521} for sure.  There may be interactions with other settings though; emulation platforms still use 100 Hz tick rates (though they don't have to post-icount, maybe we should fix that).

**Review by andyross — DISMISSED** [review]
Forgot vote, though I guess I'll have to refresh it anyway

**Comment by npitre** [comment]
Added the skipping of total duration validation if timer wrap-arounds
are detected.

I still think adding `sys_clock_cycle_get_64()` to the systick driver
(PR #55658) is also the right thing to do until the kernel takes more
responsibility arount cycle-to-tick conversions.

**Review by peter-mitsis — APPROVED** [review]

**Review by teburd — APPROVED** [review]
Not failing the drift test seems like a mistake here, but without 64 bit counters its hard to not wrap so... +1, but this should be revisited if #55345 is merged

**Review by andyross — APPROVED** [review]
Still looks great

**Pull request merged**
