### PR TITLE
dts: add binding for intel ssp

### PR DESCRIPTION
**Pull request by ArsenEloglian**
Add ssp (sspbase) node for Intel ssp.

Signed-off-by: ArsenEloglian <ArsenX.Eloglian@intel.com>

### CODE REVIEW

**Review by juimonen — DISMISSED** [review]
lgtm

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
The compatible is missing

**Comment by ArsenEloglian** [comment]
> The compatible is missing

Done, please re-review.

**Review by MaureenHelm — DISMISSED** [review]

**Review by juimonen — DISMISSED** [review]

**Review by laurenmurphyx64 — DISMISSED** [review]

**Review by mwasko — DISMISSED** [review]

**Review by lgirdwood — DISMISSED** [review]

**Comment by ArsenEloglian** [comment]
I kindly ask to merge this PR.

**Review by nashif — APPROVED** [review]

**Review by juimonen — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
