### PR TITLE
doc: Fix a typo

### PR DESCRIPTION
**Pull request by dluke62**
Fix a typo in the spelling of "current".
Add "current" to spelling.txt.

### CODE REVIEW

**Review by keith-zephyr — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Review by yperess — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Well, spelling check failing on the spelling file is quite hilarious.

@dluke62 do you feel like fixing the CI check as well? :-)

https://github.com/zephyrproject-rtos/zephyr/blob/e544bdb5e2ba254c4357c8835f26405b05c370d2/scripts/ci/check_compliance.py#L216 should probably be skipped if `m[2]` is `TYPO_SPELLING` and `m[5]` is the spelling file.

**Comment by dluke62** [comment]
thank you @fabiobaltieri , i will take a look at the CI check too

**Review by nashif — APPROVED** [review]

**Review by kartben — CHANGES_REQUESTED** [review]
Thanks for the PR! Could you please change the commit message and description for the commit fixing the CI check?

**Review by MariuszSkamra — APPROVED** [review]

**Comment by dluke62** [comment]
@kartben thank you, I've updated the second commit message.

**Review by fabiobaltieri — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Pull request merged**
