### PR TITLE
scripts: nrfjprog runner enhancements

### PR DESCRIPTION
**Pull request by mbolivar**
A few trivial nrfjprog enhancements:

- avoid raising RuntimeError for no connected boards until the user actually runs the command (we need one additional patch in run_common.py to catch this properly as well)
- don't use input() if sys.stdin is not a tty, to make the script fail fast in automated deployments when --snr should have been used, but wasn't (@nashif I'm guessing your board farms won't be affected by this, but heads up)
- sort the list of IDs when prompting for one of several, for consistent output across runs

### CODE REVIEW

**Comment by mbolivar** [comment]
@ioannisg mind giving this a look? It's small

**Review by ioannisg — APPROVED** [review]
The nrfjprog part looks ok to me
I'd do a quick testing and report back

**Review by ioannisg — CHANGES_REQUESTED** [review]
So I was doing some testing [in Windows] - it seems that when multiple boards are connected, and the tool prompts for entering the desired device number (as they are enumerated by SNR) the wrong SNR is passed and the flashing will be attempted on the wrong device.

@mbolivar can you investigate?

**Comment by mbolivar** [comment]
> @mbolivar can you investigate?

Sorry about that. Fixed. Thanks for catching that.

**Review by ioannisg — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
