### PR TITLE
hwmv2: boards: sync up the vendor tags and vendor-list

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Sync up the board.yml vendor prefixes with the vendor prefixes file, add a CI check to ensure they stay in sync.

### CODE REVIEW

**Comment by nordicjm** [comment]
Goes with https://github.com/zephyrproject-rtos/zephyr/pull/69285 which will be discussing at architecture working group tomorrow

**Comment by ruuddw** [comment]
For ARC I'm not so happy with this. For HWMV2 ARC boards were renamed to Synopsys boards (Synopsys does many different things, everyone knows them as ARC boards...), and now Synopsys becomes 'snps'?

**Comment by nashif** [comment]
> For ARC I'm not so happy with this. For HWMV2 ARC boards were renamed to Synopsys boards (Synopsys does many different things, everyone knows them as ARC boards...), and now Synopsys becomes 'snps'?

that is coming from here https://github.com/zephyrproject-rtos/zephyr/blob/4a72cb16cfd5a8df86b7f1653632dd49b3ea5ff5/dts/bindings/vendor-prefixes.txt#L581. This is for folder and tooling, the full name wil appear in full where it needs to.. 

This was done previously here as well: https://github.com/zephyrproject-rtos/zephyr/blob/4a72cb16cfd5a8df86b7f1653632dd49b3ea5ff5/boards/arc/hsdk4xd/hsdk4xd.yaml#L16

**Review by nordicjm — APPROVED** [review]

**Comment by nordicjm** [comment]
Needs rebase

**Comment by tejlmand** [comment]
> For ARC I'm not so happy with this. For HWMV2 ARC boards were renamed to Synopsys boards (Synopsys does many different things, everyone knows them as ARC boards...), and now Synopsys becomes 'snps'?

was discussed at Arch WG Feb. 27, and former decision was reconfirmed, see also: https://github.com/zephyrproject-rtos/zephyr/pull/69285#issuecomment-1966919405

So if `snps` should be `synopsys` then that requires the vendor prefix to be changed.

**Review by tejlmand — APPROVED** [review]

**Comment by ruuddw** [comment]
> So if `snps` should be `synopsys` then that requires the vendor prefix to be changed.

Let's stick to snps, a prefix should be as short as possible as it's used at many places. My point was that for places where typing a few extra characters is not a problem and improves understanding, why not keep the full name. But no blocker for me.

**Comment by fabiobaltieri** [comment]
> Let's stick to snps, a prefix should be as short as possible as it's used at many places. My point was that for places where typing a few extra characters is not a problem and improves understanding, why not keep the full name. But no blocker for me.

Because that's what's in `dts/bindings/vendor-prefixes.txt`

**Comment by fabiobaltieri** [comment]
rebased and updated

**Pull request merged**
