### PR TITLE
tests: drivers: adc_dma: fix sampling interval failing NXP tests

### PR DESCRIPTION
**Pull request by heinwessels**
In 6e21ebf the sampling interval was changed, which caused the issue #56070. This is fixed by allowing different boards to specify a sampling period.

Also changed the test_task_with_interval to verify that the supplied interval was used.

### CODE REVIEW

**Comment by heinwessels** [comment]
@hakehuang would you mind testing this code?

**Comment by heinwessels** [comment]
@teburd this code will fix half the issue you observed. It should finish the first two tests, and the crash on the third. The other half is caused by a few limitations in the NXP ADC driver, which @hakehuang is fixing, and will likely have a PR ready for soon.

**Comment by teburd** [comment]
Results
```
*** Booting Zephyr OS build zephyr-v3.3.0-1420-g16ccf91e2e17 ***
Running TESTSUITE adc_dma
===================================================================
START - test_adc_asynchronous_call
Samples read: 0x0373 0x0000 0x007f 0x0000 0x0373 0x0000 
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/adc/adc_dma/src/test_adc.c:182: check_samples: (INVALID_ADC_VALUE not equal to sam)
[5] should be empty
 FAIL - test_adc_asynchronous_call in 0.021 seconds
===================================================================
START - test_adc_invalid_request
E: Invalid resolution
E: Invalid resolution
Samples read: 0x0309 0x0000 
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/adc/adc_dma/src/test_adc.c:182: check_samples: (INVALID_ADC_VALUE not equal to sam)
[1] should be empty
 FAIL - test_adc_invalid_request in 0.022 seconds
===================================================================
START - test_adc_repeated_samplings
repeated_samplings_callback: done 1
Samples read: 0x030b 0x0000 
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/adc/adc_dma/src/test_adc.c:182: check_samples: (INVALID_ADC_VALUE not equal to sam)
[1] should be empty
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/sched.c:1750
        aborting essential thread 0x200007e0
E: r0/a1:  0x00000004  r1/a2:  0x000006d6  r2/a3:  0x00000080
E: r3/a4:  0x00002e09 r12/ip:  0x00000000 r14/lr:  0x00006663
E:  xpsr:  0x41000011
E: Faulting instruction address (r15/pc): 0x00007c44
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Fault during interrupt handling

E: Current thread: 0x200007e0 (main)
E: Halting system
```

**Comment by heinwessels** [comment]
> Results

Ah, that looks correct. The crash and failing tests will be fixed by hakehuang.

**Comment by hakehuang** [comment]
> Ah, that looks correct. The crash and failing tests will be fixed by hakehuang.

@heinwessels , one qeustion, how can I create a PR based your PR?

**Comment by heinwessels** [comment]
> > Ah, that looks correct. The crash and failing tests will be fixed by hakehuang.
> 
> @heinwessels , one qeustion, how can I create a PR base on your PR?

Can we merge this PR as is? @anangl @teburd It doesn't block CI, as it's not run. Maybe @hakehuang can show that all tests pass if he applies his changes on top of mine.

Other option is that you `cherry-pick` my commit into a new branch, and then apply your changes on top of that. However, I would prefer the first option. You could even make a commit fixing it on your own branch that's public somewhere, and I `cherry-pick` it into this PR.

**Comment by hakehuang** [comment]
> @hakehuang would you mind testing this code?

with your fix and my PR #56120 test log is patch there

**Review by hakehuang — APPROVED** [review]
need work with
https://github.com/zephyrproject-rtos/zephyr/pull/56120

**Review by teburd — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@anangl sorry did not realize that the test was not NXP specific and merged without waiting for your approval, lmk if this was not ok and should be reworked.

**Pull request merged**
