### PR TITLE
ext: hal: nordic: Update ieee802154 radio driver to version 1.2.3

### PR DESCRIPTION
**Pull request by rlubos**
Update nRF ieee802154 radio driver to version 1.2.3. See
https://github.com/NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver/blob/1.2.3/release_notes/nrf_802154_1.2.3.md
for a list of changes.

Origin: nRF-IEEE-802.15.4-radio-driver
License: BSD 3-Clause
URL: https://github.com/NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver/tree/1.2.3
commit: 359cff11e6b4101f2c9433a952aa35705ca7b567
Purpose: Provide up-to-date version of the radio driver
Maintained-by: External

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by jukkar** [comment]
Could you split this to two commits, one having changes to the ext/hal/nordic and the other one for changes in zephyr driver?

**Review by carlescufi — CHANGES_REQUESTED** [review]
Can you please split this into 2 commits: 1 for changes to `ext/` and another one for the rest. Also in the commit that imports the new `ext/` can you follow the format that is defined for commits to `ext/`?

**Comment by rlubos** [comment]
@jukkar @carlescufi What about the rule that each commit should build? The API of the radio driver changed, hence in order to keep the Zephyr driver to build I had to make the change atomic.

Alternatively, I could provide the new driver in a separate commit while still keeping the old one, and then remove the old driver after switching to the new API.

**Comment by tbursztyka** [comment]
There isn't a strong rule about each commit should compile. Here it's better to have one patch for ext, one for drivers. 
It is sometimes better to have incremental patches that touch only a specific source or directory, and next ones applying the necessary changes.

**Comment by rlubos** [comment]
Ok, I'll split it then.

**Comment by rlubos** [comment]
@carlescufi Can you re-review? Your request have been adressed.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Merging since no additional objections have been raised and the license and file are already part of Zephyr.

**Pull request merged**
