### PR TITLE
modules: hal_nordic: fixed wrong 802.15.4 NET core init level

### PR DESCRIPTION
**Pull request by ahasztag**
The intialization level of 802.15.4 on NET core was set to APPLICATION,
which caused some applications to break during initialization. Changed
it to POST_KERNEL.

### CODE REVIEW

**Comment by ahasztag** [comment]
@ankuns @jciupis @rlubos - could you take a look at this?

**Comment by jukkar** [comment]
Isn't this going to conflict the core network stack that is started also in `POST_KERNEL`, it seems that 802.15.4 was suppose to start after the network stack is initialized.

**Comment by jciupis** [comment]
@jukkar you're certainly right that the initialization priority must be chosen carefully to match all the dependencies correctly. However, this initialization used to be done in `POST_KERNEL`. Only a couple of days a commit was merged that changed it: https://github.com/zephyrproject-rtos/zephyr/commit/3e5812cc5fb20ef3a45c2746ab64a697ffbb8536#diff-abb4be945b077402d1793fd4f5687073c480bcf4c2c5ba13c6c8bc74fc9b539eL22 

@e-rk @kapi-no was there any particular reason to move this initialization out of `POST_KERNEL` to a later stage?

**Comment by e-rk** [comment]
@jciupis I have changed this to `APPLICATION` and changed the init priority, because the previous init order was in conflict with the `ipc_service`. The service was used before it was initialized. 

My reasoning behind changing the init level was my assumption, that on the nRF53 net-core the driver is not used by anything else, which was wrong. It was only necessary to change the init priority to ensure it happened after `ipc_service` and leave the init level alone.

Honestly, the right approach to this problem in my opinion would be to split the initialization of the radio driver from the initialization of the serialization/ieee802.15.4 shim. That way, the driver would always be initialized at the same init level/prio, regardless of configuration and it would cover cases where the driver is used with no serialization or 802.15.4 shim. But since this option seems to work and it's needed fast, I think it's good to go.

**Review by e-rk — DISMISSED** [review]

**Comment by e-rk** [comment]
@jciupis That would make sense.

**Comment by ahasztag** [comment]
@jciupis @e-rk  please take a look at the change I suggest now. There is no equivalent of `CONFIG_RPMSG_SERVICE_INIT_PRIORITY` (IPC is started by calling `nrf_802154_serialization_init` in the nrf_802154_init_net.c file) - however I've noted, that in order for the driver to work, this initailization must be started after (so at a higher value of `CONFIG_NRF_802154_SER_RADIO_INIT_PRIO`) than `CONFIG_KERNEL_INIT_PRIORITY_DEVICE`

**Comment by ahasztag** [comment]
For some reasons I forgot to introduced I mentioned in the last comment, please take a look at them

**Review by e-rk — APPROVED** [review]

**Review by jciupis — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
