### PR TITLE
xtensa: set toolchain variant per SoC

### PR DESCRIPTION
**Pull request by nashif**
The toolchain variant per SoC is not always the soc name, so set this
per SoC and use this in the SDK instead of hardcoding the soc name.

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Comment by nashif** [comment]
@galak  can you please give this a look?

**Comment by nashif** [comment]
@tejlmand  ditto

**Review by andyross — APPROVED** [review]
Makes sense, though I'm as always ignorant of the right way to do the cmake parts of this.

FWIW: if we're going to start unioning platforms to similar toolchains, we might want to start calling it something like "xtensa_lx6" which better reflects the upstream IP.  But I guess that's out of scope.

It does need to be pointed out that this trick starts us down the road of having to soft-configure differences between CPUs that used to be hardwired into the toolchain.  I 100% support that (because Xtensa's model is mindbending and just a huge pain), but there will at some stage be blowback.

**Comment by tejlmand** [comment]
> @tejlmand ditto

A little late, but LGTM.

**Pull request merged**
