### PR TITLE
modules: qcbor: integrate QCBOR library

### PR DESCRIPTION
**Pull request by mniestroj**
QCBOR library is a powerful, commercial-quality CBOR encoder/decoder.

TODO:
- [ ] create qcbor mirror with `zephyr` branch
- [ ] update `west.yml` with qcbor mirror under zephyrproject-rtos

### CODE REVIEW

**Review by carlescufi — CHANGES_REQUESTED** [review]
Blocking for now based on two reasons:

- We have a CBOR library already (TinyCBOR), although we do indeed want to get rid of it
- We had plans to transition to [cddl-gen](https://github.com/NordicSemiconductor/cddl-gen), like MCUboot already did

**Comment by mniestroj** [comment]
@carlescufi thanks for feedback.

Is it a requirement to use QCBOR in order to get it integrated? QCBOR might be nice for application developers and this PR allows them to easily start using it.

Additionally I plan to create PR with another west module, that requires QCBOR (at least for now). Would that be good enough reason to integrate QCBOR into Zephyr, assuming that this new module would be welcome?

**Comment by carlescufi** [comment]
> Is it a requirement to use QCBOR in order to get it integrated? QCBOR might be nice for application developers and this PR allows them to easily start using it.

We do not allow multiple implementations of a standard/feature to be in the tree/forest. For good reasons, because otherwise it gets complicated :) But let's talk about it together and see what we can do.

**Comment by de-nordic** [comment]
> 
> Additionally I plan to create PR with another west module, that requires QCBOR (at least for now). Would that be good enough reason to integrate QCBOR into Zephyr, assuming that this new module would be welcome?

Then we should wait for the PR for that module and look at the case having all the parts together.

Right now we try to move everything to cddl encoder/decoder to be able to remove the custom variant of TinyCBOR, which has been taken from MyNewt/core code base.

**Review by de-nordic — CHANGES_REQUESTED** [review]
This should be re-considered together with the module that requires it.

**Pull request closed without merging**
