### PR TITLE
net: shell: iface: Add command to set gateway

### PR DESCRIPTION
**Pull request by MateuszKarlic**
Add a command `net iface set_ipv4_gateway` that allows setting IPv4 gateway for an interface from net shell.

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
Wouldn't it be a better fit to put this in IPv4 shell space? I. e.:
`net ipv4 gateway <index> <address>`

**Comment by MateuszKarlic** [comment]
I also thinking about putting it behind `ipv4`. As suggested, moved it there and added `argc` check

**Review by pdgendt — APPROVED** [review]
LGTM, if you have the time to spare, it would be nice to do the same for the netmask.

**Review by rlubos — APPROVED** [review]

**Comment by jukkar** [comment]
> if you have the time to spare, it would be nice to do the same for the netmask.

Preferably after this change #68419

**Review by jukkar — APPROVED** [review]

**Comment by MateuszKarlic** [comment]
> > if you have the time to spare, it would be nice to do the same for the netmask.
> 
> Preferably after this change #68419

Sure, I can take a look into it after this PR is merged

**Pull request merged**
