### PR TITLE
restore demand paging PR + PC fixes

### PR DESCRIPTION
**Pull request by tyrantlizard77**
This PR:

- Restores all the demand paging commits that were reverted on Friday (the root cause of the sentinel failure is #31546)
- Adds CONFIG_ARCH_MAPS_ALL_RAM. This signals to the kernel that all RAM has a bootup mapping, and not just the Zephyr image. Page frame management is unaffected, but this will be taken into account when establishing new memory mappings, as to not disturb the existing mapping for all RAM.
- Enable CONFIG_ARCH_MAPS_ALL_RAM for ACPI targets. Various PC-like targets had their VM size increased.

### CODE REVIEW

**Comment by jenmwms** [comment]
Thanks @andrewboie! I've started HW testing, will post details soon.

**Review by dcpleung — APPROVED** [review]

**Review by aasthagr — APPROVED** [review]

**Review by jenmwms — APPROVED** [review]

**Comment by jhedberg** [comment]
This unfortunately breaks EHL booting with SBL. Reverting to commit 3746ebc305f5ae581665cd033637a11caee5b836 (i.e. right before this PR went in) makes it work again.

**Comment by jhedberg** [comment]
> This unfortunately breaks EHL booting with SBL. Reverting to commit 3746ebc (i.e. right before this PR went in) makes it work again.

Using `git bisect` to narrow this down gives the following:
```
5c47bbc5010d98c6f6d795aa6d268138c3463bbd is the first bad commit
commit 5c47bbc5010d98c6f6d795aa6d268138c3463bbd
Author: Andrew Boie <andrew.p.boie@intel.com>
Date:   Thu Dec 10 11:23:21 2020 -0800

    x86: only map the kernel image
    
    The policy is changed and we no longer map all page frames.
    
    Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

 arch/x86/gen_mmu.py | 27 ++++++++++++++++++---------
 1 file changed, 18 insertions(+), 9 deletions(-)
```

**Comment by jhedberg** [comment]
I added some debug logs to the ACPI table code with the suspicion that something is outside, but it looks to me like everything is still within 2MB that's declared for the board:
```
Starting MB Kernel ...
find_rsdp search 0xf0e0
find_rsdp rsdp 0xfff80
z_acpi_find_table rsdt 0x78854030
z_acpi_find_table returning sdt 0x788545b0
*** Booting Zephyr OS build zephyr-v2.4.0-3554-g3746ebc305f5  ***
z_acpi_find_table rsdt 0x78854030
z_acpi_find_table returning sdt 0x78854530
Hello World! ehl_crb_sbl
```

Btw, I seem to be unable to increase the declared RAM amount from 2MB (even if I also increase KERNEL_VM_SIZE) - it results in some build errors.

**Pull request merged**
