### PR TITLE
net: ethernet: Clean up net_eth_fill_header() function

### PR DESCRIPTION
**Pull request by pfalcon**
There's an apparent typo in testing net_buf headroom. Also, after
adding VLAN header support, its size should be used too.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
This is result of my review of #8270. There must be a typo/thinko in the original assert, or I don't understand something (and that's why I bring it up). It also brings other point:

1. There's a confusing dichotomy between net_pkt_ll_reserve() and net_buf_headroom(). Both overall in the API, and specifically here: why do we assert on net_buf_headroom(), but then use net_pkt_ll_reserve()? Maybe we should tie both in the assert?
2. I'd suggest to remove `frag` param to this function, it doesn't make much sense, the header goes to the first frag of `pkt` param.

**Comment by jukkar** [comment]
> There's a confusing dichotomy between net_pkt_ll_reserve() and net_buf_headroom(). Both overall in the API, and specifically here: why do we assert on net_buf_headroom(), but then use net_pkt_ll_reserve()? Maybe we should tie both in the assert?

net_buf_headroom() calculates how much space there is in net_buf for ll header. The net_pkt_ll_reserve() just returns the value of ll header. They should return the same value but are just calculated differently.


> I'd suggest to remove frag param to this function, it doesn't make much sense, the header goes to the first frag of pkt param.

Yes, the frag parameter is quite useless and could be removed. If you feel like it, just send a PR that removes it.

**Review by jukkar — DISMISSED** [review]

**Comment by pfalcon** [comment]
> net_buf_headroom() calculates how much space there is in net_buf for ll header. The net_pkt_ll_reserve() just returns the value of ll header. They should return the same value but are just calculated differently.

Yes, that's my understanding too, and I just wonder if "ideally" we should check that "they should return the same value" in the assert (now that we have it at all).

> Yes, the frag parameter is quite useless and could be removed. If you feel like it, just send a PR that removes it.

Added a commit to this PR. Still would like to get an ack from @tbursztyka too that it goes in the right direction for the Ethernet subsys, maybe I'm missing something.

**Comment by pfalcon** [comment]
For reference, I tested these changes with socket dumb_http_server and big_http_download samples.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by tbursztyka — APPROVED** [review]

**Pull request merged**
