### PR TITLE
build: Do not build "raw" binary by default

### PR DESCRIPTION
**Pull request by finikorg**
Build "raw" binary zephyr.bin only if needed. This also "fixes" building with llvm 64-bit targets which are failing when building "raw" binary file.

### CODE REVIEW

**Review by nordicjm — CHANGES_REQUESTED** [review]
Erm, no. This is not an acceptable change.

**Comment by finikorg** [comment]
> Erm, no. This is not an acceptable change.

I think most of the boards do not need this "raw" binary, why do we need to create it?

**Comment by nordicjm** [comment]
mcuboot upgrades are output as signed binary files, ST's DAPLINK programmer (alongside other DAPLINK) programmers use binary files for programming devices.

**Comment by finikorg** [comment]
> mcuboot upgrades are output as signed binary files, ST's DAPLINK programmer (alongside other DAPLINK) programmers use binary files for programming devices.

So what is a problem of enabling this for selected boards?

**Comment by nordicjm** [comment]
> So what is a problem of enabling this for selected boards?

From what I can see in zephyr, there's 398 boards, not 4.

**Pull request closed without merging**
