### PR TITLE
doc: update known-issues for Sphinx==3.3.0

### PR DESCRIPTION
**Pull request by utzig**
Sphinx==3.3.0 slightly changed the warning messages, which causes fails on filter-known-issues. Update to the new messages.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by utzig** [comment]
@nashif @carlescufi I am building locally to be sure the fix is correct, because changing .known-issues is not triggering the documentation build anymore.

**Comment by carlescufi** [comment]
> @nashif @carlescufi I am building locally to be sure the fix is correct, because changing .known-issues is not triggering the documentation build anymore.

You could fix this in this very PR by adding the known issues folder here:
https://github.com/zephyrproject-rtos/zephyr/blob/master/.github/workflows/doc-build.yml#L8

**Comment by utzig** [comment]
@carlescufi @nashif Fixed the issues locally, so I removed the DNM

**Comment by utzig** [comment]
> > @nashif @carlescufi I am building locally to be sure the fix is correct, because changing .known-issues is not triggering the documentation build anymore.
> 
> You could fix this in this very PR by adding the known issues folder here:
> https://github.com/zephyrproject-rtos/zephyr/blob/master/.github/workflows/doc-build.yml#L8

Done

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> > > @nashif @carlescufi I am building locally to be sure the fix is correct, because changing .known-issues is not triggering the documentation build anymore.
> > 
> > 
> > You could fix this in this very PR by adding the known issues folder here:
> > https://github.com/zephyrproject-rtos/zephyr/blob/master/.github/workflows/doc-build.yml#L8
> 
> Done

And doc is building now.

**Review by galak — APPROVED** [review]

**Pull request merged**
