### PR TITLE
drivers/gnss Add GNSS API

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
**Purpose**
This API is based on the shared functionalities
between GNSS modems from Quectel, Telit, Nordic
and U-blox.

**NOTE**
This is a draft for discussion purposes

**Research**
There are many functionalities which are either
only supported by less than half of the modems,
or have modem specific configurations for which
creating an abstraction is futile.

The following segments split the different
configurations and features into categories:

Features and configs covered by GNSS API:
- Get location data
- Get date and time
- Set/get fix rate
- Set/get power mode
- Set/get pps mode only (not config)
- Get visible satelites count

Features and configs covered by DTS/KConfig:
- PPS config (polarity, pulsewidth, source, etc.)
- Navigation modes (Bike, Helicopter, etc.)
- Enabled technologies (GLONASS, GPS, etc.)

Features and configs covered by driver
specific API:
- A-GPS (most of them use proprietary data
  formats and sources)
- Anything covered by DTS/KConfig that might need
  to be adjusted during runtime

**Discussion**
- What if any features/configs must be added to the GNSS API
- Can a generic solution be created for A-GPS data

### CODE REVIEW

**Comment by ycsin** [comment]
One thing comes to my mind is that for Quectel modem you can configure the type of NMEA sentences that it outputs, should that be handled here or somewhere lower?

**Comment by bjarki-trackunit** [comment]
> One thing comes to my mind is that for Quectel modem you can configure the type of NMEA sentences that it outputs, should that be handled here or somewhere lower?

All NMEA sentences and proprietary setup commands, pin configurations etc. should be handled by the driver, below this API. We can however create a callback with "raw" NMEA  sentences (validated and parsed to argv, argc) which the application can register to if it wants to do more complicated work.

**Comment by ycsin** [comment]
> All NMEA sentences and proprietary setup commands, pin configurations etc. should be handled by the driver

Yea I'd imagine that the parsing of the sentences will handled ~at the driver. My question is about the configuration of which NMEA sentences should the modem output, i.e. Quectel will output at least 4 difference NMEA at once by default, but I'm probably only interested in GGA & RMC so being able to configure that somewhere could save the buffer size.

If other modems support similar configuration, I think it would be nice to have a more generalized way of configuring it so that code is more portable, just some random thoughts

**Comment by bjarki-trackunit** [comment]
> > All NMEA sentences and proprietary setup commands, pin configurations etc. should be handled by the driver
> 
> Yea I'd imagine that the parsing of the sentences will handled ~at the driver. My question is about the configuration of which NMEA sentences should the modem output, i.e. Quectel will output at least 4 difference NMEA at once by default, but I'm probably only interested in GGA & RMC so being able to configure that somewhere could save the buffer size.
> 
> If other modems support similar configuration, I think it would be nice to have a more generalized way of configuring it so that code is more portable, just some random thoughts

If the goal is simply to save on buffer size, this would be done by the driver internally if the feature exists. The driver should only read and process the NMEA or OSP data it needs to fulfill the API, so optimizing the driver would include limiting the NMEA sentences to the ones needed.

**Pull request closed without merging**
