### PR TITLE
RFC: Renaming PM APIs

### LINKED ISSUE #11047: doc: missing Doxygen generated documentation for any function which name starts with an underscore
"[Power Management Hook Interface](https://docs.zephyrproject.org/latest/api/power_management_api.html#power-management-hook-interface)" section of "[Power Management APIs](https://docs.zephyrproject.org/latest/api/power_management_api.html)" is empty despite the fact that zephyr/include/power.h contains all necessary Doxygen comments.

Functions which should appear in this section are:
```
static inline void _sys_soc_pm_idle_exit_notification_disable(void);
void _sys_soc_resume_from_deep_sleep(void);
void _sys_soc_resume(void);
extern int _sys_soc_suspend(s32_t ticks);
```

It looks like Doxygen ignores all function names which start with an underscore.

### PR DESCRIPTION
**Pull request by nashif**
- Rename \_sys to sys\_
- Rename \_sys_soc -> sys\_

Fixes #11047

### CODE REVIEW

**Review by dbkinder — APPROVED** [review]
doc changes LGTM

**Comment by andrewboie** [comment]
No objections to this change.
Do we have documentation somewhere which indicates the appropriate use of prefixes (z_, k_, sys_, etc)

**Review by ioannisg — COMMENTED** [review]
This seems a safe change to me.

**Review by nniranjhana — APPROVED** [review]

**Review by ramakrishnapallala — APPROVED** [review]

**Review by spoorthik — APPROVED** [review]

**Review by pizi-nordic — APPROVED** [review]

**Comment by carlescufi** [comment]
@nashif why is this tagged as DNM?

**Comment by nashif** [comment]
recheck

**Pull request merged**
