### PR TITLE
maintainers: Update Arm maintainer and collabs

### PR DESCRIPTION
**Pull request by microbuilder**
Updates the maintainer for Arm and cleans up the collab list.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by ithinuel — APPROVED** [review]
Thank you!

**Review by kartben — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by microbuilder** [comment]
@nashif @carlescufi Probably worth mentioning on the next TSC call since it's a pretty important subsystem/arch. 

I'm gutted not to have the time it needs, but it's too important to leave neglected and Wilfried will be able to drive some needed changes forward on Aarch32.

Congrats @ithinuel and I'm sure you'll learn a lot in the new role, being forced to go down a lot of new rabbit holes.

**Review by henrikbrixandersen — APPROVED** [review]
@microbuilder Thank you for all your efforts on maintaining the Arm arch! Hope you won't be disappearing down a rabbit hole yourself.

**Review by stephanosio — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by kartben** [comment]
@ithinuel thanks for stepping up as a maintainer! Feel free to claim your Zephyr Maintainer badge here: https://forms.gle/oCw9iAPLhUsHTapc8 :)

**Pull request merged**
