### PR TITLE
Cleanup driver for MCP23S17

### PR DESCRIPTION
**Pull request by benediktibk**
Move the content of the header for the MCP23S17 into the source file and remove the doxygen comments, as requested in a similar case in #54433.

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
I see the point in moving the definitions into the C file, but why remove code documentation that was already written?

**Comment by benediktibk** [comment]
> I see the point in moving the definitions into the C file, but why remove code documentation that was already written?

@henrikbrixandersen In a different PR (https://github.com/zephyrproject-rtos/zephyr/pull/54433), for which I used this driver as a starting point, @cfriedt wanted to get rid of the doxygen documentation. Hence I assumed it is generally not desired to have such a documentation.

**Comment by henrikbrixandersen** [comment]
@cfriedt ping?

**Comment by cfriedt** [comment]
> @cfriedt ping?

Is there a benefit to documenting self-descriptive, private / static functions?

It adds nothing to Zephyr documentation as far as I am aware, and is not mentioned anywhere in [Code Documentation](https://docs.zephyrproject.org/latest/project/documentation.html).

In this case, I found that the documentation was not really clarifying anything, so yes, I approve.

**Review by cfriedt — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Pull request merged**
