### PR TITLE
Add cooked mode capture support

### PR DESCRIPTION
**Pull request by jukkar**
Add cooked mode capture support to capture API. In cooked mode capture, arbitrary data can be captured and then encapsulated into so called SLL packet format and then sent to outside system for a review. See the documentation in the PR for more details.

### CODE REVIEW

**Review by cfriedt — DISMISSED** [review]
LGTM - this is a nifty feature. Is there a Wireshark plugin in the near future? 😃

**Comment by jukkar** [comment]
> Is there a Wireshark plugin in the near future?

I was not planning that atm, as there is the `net-capture.py` scapy app in net-tools that has initial support for saving the data to pcap file which could then be viewed in wireshark. As of this writing, the `net-capture.py` does not yet remove the tunnel headers so slight modifications are needed in that front.

**Comment by jukkar** [comment]
* updated the net-tools manifest to get the updated net-capture.py script

**Review by rlubos — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by jukkar** [comment]
* No changes to commits, only updated to latest main

**Pull request merged**
