### PR TITLE
[Backport v3.2-branch] logging: Use STRUCT_SECTION macros for log backend

### LINKED ISSUE #56067: Fix build issues with arm clang compiler for mec17xx platforms
There are a number of different failures we see when building the arm clang compiler when building the mec17xx platforms.

### PR DESCRIPTION
**Pull request by zephyrbot**
Fixes #56067

Backport e6bbc6941a338a3f81757e7dfb28bd9822e5810d from #49899

### CODE REVIEW

**Comment by galak** [comment]
Need as part of #56067

**Review by galak — APPROVED** [review]

**Comment by jgl-meta** [comment]
@carlescufi @mbolivar-nordic

**Comment by mbolivar-nordic** [comment]
> @carlescufi @mbolivar-nordic

??

We were v3.1 release managers, not v3.2

**Comment by jgl-meta** [comment]
> 

Sorry about that. Do you know who was for 3.2 or where I can find out?

**Comment by mbolivar-nordic** [comment]
On Tue, Apr 25 2023, jgl-meta wrote:
>> 
>
> Sorry about that. Do you know who was for 3.2 or where I can find out?


$ git show v3.2.0
tag v3.2.0
Tagger: Fabio Baltieri ***@***.***>

@fabiobaltieri

**Review by fabiobaltieri — APPROVED** [review]

**Comment by jgl-meta** [comment]
@nordic-krch Can you make a decision on this? If you approve of this can you check it in?

**Review by nordic-krch — APPROVED** [review]

**Pull request merged**
