### PR TITLE
west: set west version in manifest file

### PR DESCRIPTION
**Pull request by mbolivar**
It's time to nail this down.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by tejlmand** [comment]
@mbolivar  Looks good, but you should probably update the SHA now.

**Comment by mbolivar** [comment]
@tejlmand done, please revisit.

**Review by carlescufi — CHANGES_REQUESTED** [review]
Please update to latest SHA in west

**Comment by galak** [comment]
@carlescufi mentioned we needed an updated SHA?

**Comment by carlescufi** [comment]
Also please bump up required version to 0.5.5 in this PR

**Comment by mbolivar** [comment]
@carlescufi @galak done

**Review by SebastianBoe — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by mbolivar** [comment]
recheck

**Comment by mbolivar** [comment]
retest

**Comment by mbolivar** [comment]
@nashif do we need a rebuild of the CI container? The bootstrapper on it is too old.

```
    The version was found to be 0.5.4:
      West bootstrapper version: v0.5.4 (/usr/local/lib/python3.5/dist-packages/west/_bootstrap)
    But the minimum supported version is 0.5.5
    Please upgrade, e.g. with:
        pip3 install --upgrade west
    if the version from pip is too old, or:
        west update
    if the version in the installation is too old.
```

**Review by galak — DISMISSED** [review]
Looks like we need 0.5.6 based on:

https://github.com/zephyrproject-rtos/west/pull/235

We need to update docker images, update CI, and make a release once 0.5.6 is out before this PR can be merged.

**Comment by mbolivar** [comment]
> Looks like we need 0.5.6 based on:

Done

> We need to update docker images, update CI, and make a release once 0.5.6 is out before this PR can be merged.

Ready for this

**Review by tejlmand — APPROVED** [review]
Looking good.

**Pull request merged**
