### PR TITLE
net: socket: Change the protocol field for AF_PACKET sockets

### PR DESCRIPTION
**Pull request by jukkar**
In order to be compatible with Linux AF_PACKET socket calls, the protocol field needs to be network byte order.
So for example if user wants to receive all packets, then the protocol field needs to be set as `htons(ETH_P_ALL)`. See Linux manual page at
https://www.man7.org/linux/man-pages/man7/packet.7.html for details.

### CODE REVIEW

**Review by krish2718 — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Review by aescolar — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Comment by jukkar** [comment]
* ieee802154 CI failures fixed

**Review by rlubos — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Comment by fengming-ye** [comment]
is this PR ready to merge? I'll modify my PR according to it.
https://github.com/zephyrproject-rtos/zephyr/pull/73120

**Comment by aescolar** [comment]
> is this PR ready to merge? I'll modify my PR according to it. #73120

Once the review time criteria is met (in another 30h), it will be merged (assuming no rejections, no new pushes and no merge conflicts)

**Comment by fgrandel** [comment]
Thx, @jukkar . Very useful.

**Pull request merged**
