### PR TITLE
MAINTAINERS: clean up and propose myself

### PR DESCRIPTION
**Pull request by tomi-font**
See details in the commit messages.

### CODE REVIEW

**Review by ceolin — COMMENTED** [review]
AFAIU we have one entry for the external module (West project) and another one for the things inside Zephyr's repository. That is not only for mbedTLS, other modules do the same. 

Other than that, It will be great to have you as a collaborator !!

**Comment by tomi-font** [comment]
> AFAIU we have one entry for the external module (West project) and another one for the things inside Zephyr's repository. That is not only for mbedTLS, other modules do the same.

I did that because:

- The `Mbed TLS` and `TF-M Integration` and their respective `West project` entries were fragmented and not consistent, e.g. the `TF-M Integration` one [had the modules directory in its files](https://github.com/zephyrproject-rtos/zephyr/blob/v3.7.0-rc3/MAINTAINERS.yml#L4009), and its `West project` entry did not have @valeriosetti as collaborator.
- I saw some `West project` entries that had more than just what's under the modules directory, e.g. [thrift](https://github.com/zephyrproject-rtos/zephyr/blob/v3.7.0-rc3/MAINTAINERS.yml#L4856). I'm essentially proposing the same for Mbed TLS and TF-M here.

What do people think about this?

**Comment by ithinuel** [comment]
IIUC, this is used by bots to identify and & assign reviewer to affected areas.

So,
- if "TF-M integration" uses files (`#include`) coming from `modules/trusted-firmware-m` then it should have an entry to it, in additions to the tests, samples and any other parts that need maintenance under this umbrella.
- "West project: TF-M" should only have that of the modules (it already covers the whole other repo)

I don't quite understand the point of separating a module and its integration since I'd expect both to be maintained by the same group of people.
https://docs.zephyrproject.org/latest/develop/modules.html states that a module owner may not be the same as the Zephyr maintainer so it may be the reason behind this.

Either way such a change (removing areas with maintainers) should be reviewed by the TSC according to https://docs.zephyrproject.org/latest/project/project_roles.html#maintainers-file

> Major changes to the file, including the addition of new areas with new maintainers should come in as standalone pull requests and require TSC review.

**Comment by tomi-font** [comment]
@ithinuel I didn't quite follow. But regarding your last point, I don't consider what I did to be a major change. Even though it removes two entries, it's more of a small cleanup. (In practice nothing changes, it's just for a better organization.)

**Comment by tomi-font** [comment]
What do people think about the merging of the [Mbed TLS](https://github.com/zephyrproject-rtos/zephyr/pull/75925/commits/a178e11316ed2e169132691867a2a0a7346547ec) and [TF-M](https://github.com/zephyrproject-rtos/zephyr/pull/75925/commits/f77884b7712b30d20d4f3ad9151034b68e12dc0e) entries into their respective West project ones?
@cfriedt Isn't it how it's done with Thrift?

**Comment by keith-zephyr** [comment]
Notes from the Process WG meeting on 2024-07-31:

@MaureenHelm - the separate maintainer sections allows for different labels
@keith-zephyr - the maintainer file does support multiple labels in a section
@MaureenHelm and @dleach02 - want some more time to review the changes

**Comment by tomi-font** [comment]
ping @MaureenHelm @dleach02

**Review by MaureenHelm — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
