### PR TITLE
Cmake final history rewrite [branch cleanup, not for review]

### PR DESCRIPTION
**Pull request by SebastianBoe**
@nashif : This is upstream/cmake_migration after rebasing it onto master, porting the new changes, and rewriting the history again.

### CODE REVIEW

**Comment by galak** [comment]
Something seems off about this PR, seems like a rebase might be needed?

**Comment by SebastianBoe** [comment]
> Something seems off about this PR, seems like a rebase might be needed?

The reason it looks weird is that github is showing you that cmake_migration is being updated with new commits from master. Which is our intention, as this PR sync's cmake_migration with the latest master. It's difficult to explain, but everything is as it should be.

**Comment by galak** [comment]
> The reason it looks weird is that github is showing you that cmake_migration is being updated with new commits from master. Which is our intention, as this PR sync's cmake_migration with the latest master. It's difficult to explain, but everything is as it should be.

Not sure I understand, but its completely unreviewable at this point.

**Comment by SebastianBoe** [comment]
I would recommend using a local git client to view the differences between master and cmake_migration.

**Comment by carlescufi** [comment]
@SebastianBoe are you sure? to me it looks like it's missing a rebase like @galak said, so that both branches are in sync?

**Comment by SebastianBoe** [comment]
Yes, I am sure.

It is difficult to explain, but this is following the sync workflow we have been doing all the way.

anaZ will force-push this branch to cmake_migration and this will make the history look like
cmake_migration has branched off of a recent version of master.

In hindsight I think we should have used a workflow that used merge commits instead of rebase, rewriting history has proven to be messy. This wouldn't prevent commits from master to end up in a PR like this though, that is a quirk/feature of github.

**Comment by carlescufi** [comment]
OK, this must be what we used to see with GitHub when we used the bluetooth subsystem branch, and one of the reasons we steered away from it.
So you suggest a manual diff with Git locally to actually examine the changes then. I will try that.

**Comment by galak** [comment]
@nashif can still for push this to the cmake_migration, but we can change the 'base' to 'master' to make the review easier.

**Comment by SebastianBoe** [comment]
@galak : This PR has master as a 'base' https://github.com/zephyrproject-rtos/zephyr/pull/4692 and is probably what you are looking for.

This PR is just for Anas to review some changes to cmake_migration.

**Comment by nashif** [comment]
This is not intended for review actually, this is just us cleaning up house before the actual PR against master :)

**Pull request closed without merging**
