### PR TITLE
drivers: flash: remove W25QXXDV driver

### PR DESCRIPTION
**Pull request by pabigot**
The spi_flash_w25qxxdv driver has been superseded by the generic
spi_nor driver for over a year.  The only non-refactoring change to
the W25Q driver in the last 18 months was done to support a backport
to 1.14.

All devices supported by spi_flash_w25qxxdv driver are expected to be
supported by the spi_nor driver, using the standard `jedec,spi-nor`
devicetree compatible.  No in-tree devicetree files make use of this
driver.

Remove the confusion about which driver to select by removing the
unmaintained redundant driver.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

**Comment by pabigot** [comment]
Inspired by #27791.  I don't think we have a policy for this, but as deprecation isn't really feasible I propose to email the user and devel lists requesting feedback on this PR, with merge in one week if it's approved.

**Review by gmarull — APPROVED** [review]

**Comment by baw-serafin** [comment]
:+1:  Just wasted an hour last week to find the differences

**Comment by thedjnK** [comment]
I have some general questions about this, I'm not against removing the old driver:

- The first thing that comes to mind is “if it ain’t broke, don’t fix it” - does the w25qxxdv driver work fine without issues? If so, then I don’t really see a lack of code updates as the main reason to remove it.
- "All devices supported by spi_flash_w25qxxdv driver are expected to be supported by the spi_nor driver, using the standard jedec,spi-nor devicetree compatible" this reads like it hasn't been fully tested or there might be a device whereby it doesn't work. Can you guarantee 100% of devices using the w25qxxdv driver will work with the spi_nor driver?

**Comment by pabigot** [comment]
> * The first thing that comes to mind is “if it ain’t broke, don’t fix it” - does the w25qxxdv driver work fine without issues?

No, per #27791 and other informal communications.  At least it could only work if you used a compatible that incorrectly identified the device actually present.

> * Can you guarantee 100% of devices using the w25qxxdv driver will work with the spi_nor driver?

No, because I have no idea what devices are using that driver.

I can guarantee[*] that any JEDEC SPI NOR serial flash memory using standard 4-signal (SDI, SDO, SCK, CS) SPI that does not work with the spi-nor driver would be considered a bug in that driver and given pretty high priority for a fix.  That is not true for the winbond driver, which nobody maintains.

[*] not a guarantee, but certainly an intent.

**Review by chrta — CHANGES_REQUESTED** [review]
I think the file dts/bindings/mtd/winbond,w25q16.yaml must be removed, too.

Otherwise i am also in favor of this change.

Edit: `grep -r -i winbond` shows a few other occurrences which should be removed.

**Comment by pabigot** [comment]
> I think the file dts/bindings/mtd/winbond,w25q16.yaml must be removed, too.

Thanks, done, also the all-device build devicetree node.  The other references are still valid (e.g. when there's an actual winbond device being identified).

**Review by chrta — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by pabigot** [comment]
>  I propose to email the user and devel lists requesting feedback on this PR, with merge in one week if it's approved.

I suppose I should have marked this DNM, or maybe we need another label that indicates "Delayed awaiting community feedback".

**Comment by mbolivar-nordic** [comment]
> I suppose I should have marked this DNM, or maybe we need another label that indicates "Delayed awaiting community feedback".

I think DNM is sufficiently general for this. It's always possible to leave a comment explaining why it's DNM as done here: https://github.com/zephyrproject-rtos/zephyr/pull/27688#issuecomment-680157951

**Pull request merged**
