### PR TITLE
doc: sphinx: Fix broken import of lexer.DtsLexer

### LINKED ISSUE #6851: 'make html' in doc/ fails with lexer.DtsLexer import error
Error message:

```
Exception occurred:
  File "conf.py", line 128, in <module>
    from lexer.DtsLexer import DtsLexer
ImportError: No module named lexer.DtsLexer
```

### PR DESCRIPTION
**Pull request by ulfalizer**
When sphinx-build is run under Python 2, running e.g. 'make html' in
doc/ currently causes the following error:

    Exception occurred:
      File "conf.py", line 128, in <module>
        from lexer.DtsLexer import DtsLexer
    ImportError: No module named lexer.DtsLexer

The problem is that `doc/extensions/lexer/` contains no `__init__.py` file,
which prevents Python 2 from finding submodules in it[1].

The problem does not occur for Python 3, due to implicit namespaces
packages:
https://www.python.org/dev/peps/pep-0420/

Add an empty `__init__.py` to `doc/extensions/lexer/` to fix building when
`sphinx-build` uses Python 2 (2.7 is still the version recommended on the
Sphinx homepage). This won't alter the behavior for Python 3.

(doc/extensions is added to the search path at the beginning of conf.py
and so doesn't need an `__init__.py`. `doc/extensions/zephyr/` already has an
empty `__init__.py`.)

[1] https://docs.python.org/2/tutorial/modules.html#packages

Fixes #6851

Signed-off-by: Ulf Magnusson <ulfalizer@gmail.com>

### CODE REVIEW

**Comment by nashif** [comment]
hmm, are you using python2?

**Comment by ulfalizer** [comment]
> hmm, are you using python2?

Looks like it: 

```
$ file /usr/bin/sphinx-build
/usr/bin/sphinx-build: symbolic link to ../share/sphinx/scripts/python2/sphinx-build
```

Didn't realize Python 2 and Python 3 differed in behavior there, but yeah, `import foo.bar` seems to work in Python 3, even if `foo/` has no `__init__.py`. I'm more used to single-file projects. ;)

Is building the documentation only supported for Python 3? A clearer error might be nice in that case. @jukkar ran into exactly the same issue a few days ago.

**Comment by ulfalizer** [comment]
Related: https://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3

It looks like having the empty `__init__.py` in there will still work the same at least. That'd be consistent with `doc/extensions/zephyr/` as well.

**Comment by ulfalizer** [comment]
I updated the commit message to make it clear that only the Python 2 version of `sphinx-build` is affected.

**Review by jukkar — APPROVED** [review]
+1 from me, "make htmldocs" works ok with this fix

**Comment by jukkar** [comment]
> I have no issues merging this, but in general Zephyr requires Python 3 for everything.

I have both python2 and python3 installed, but for some reason the "make htmldocs" used the python2 version. Perhaps we should enforce python3 so that it would be used automatically by zephyr. Now the requirement for python3 seems to missing (at least in the document generation).

**Pull request merged**
