### PR TITLE
Proposing a new gPTP maintenance area and proposes self as collaborator

### PR DESCRIPTION
**Pull request by ghost**
@jukkar proposed that I add myself as a collaborator for the gPTP area. As a corresponding maintenance area didn't exist, this PR proposes to introduce one.

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
actually... 
Would make sense to exlude thos from other areas, to avoid duplication and uncertainity about who to assign things to, right now many of the files are already covered in the networking area, so please exclude them from there, otherwise we will have:

```
./scripts/get_maintainer.py path doc/connectivity/networking/api/gptp.rst
Networking
	status: maintained
	maintainers: rlubos, jukkar
	collaborators: tbursztyka, ssharks
	inform:
	labels: area: Networking
	description:
gale:zephyr(topic/twister_status_2): ./scripts/get_maintainer.py path include/zephyr/net/gptp.h
Networking
	status: maintained
	maintainers: rlubos, jukkar
	collaborators: tbursztyka, ssharks
	inform:
	labels: area: Networking
	description:
```

**Comment by fgrandel** [comment]
> Would make sense to exlude thos from other areas

Good point! Fixed.

**Review by jukkar — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Comment by kartben** [comment]
@fgrandel  please look at resolving conflicts - thx!

**Review by nashif — DISMISSED** [review]

**Comment by fgrandel** [comment]
> @fgrandel please look at resolving conflicts - thx!

Done.

**Review by MaureenHelm — APPROVED** [review]

**Comment by fgrandel** [comment]
@jukkar @nashif re-ACK required as I had to rebase due to merge conflicts

**Review by jukkar — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
