### PR TITLE
bluetooth: tester: Enable extended advertising

### PR DESCRIPTION
**Pull request by sjanc**
Some peripheral tests are failing if CONFIG_BT_EXT_ADV=n. That was previously implicitly enabled by MESH but it has dedicated overlay.

Affected tests:
GAP/BROB/BCST/BV-03-C
GAP/CONN/UCON/BV-06-C
GAP/PRIV/CONN/BV-10-C

### CODE REVIEW

**Comment by sjanc** [comment]
Asthis PR merely workaround true problem I've created an issue https://github.com/zephyrproject-rtos/zephyr/issues/56326 for tracking

**Comment by sjanc** [comment]
#AutoPTS run zephyr GAP/BROB/BCST/BV-03-C GAP/CONN/UCON/BV-06-C GAP/PRIV/CONN/BV-10-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/56325#issuecomment-1488695177 after 16:11:14.

**Review by Thalley — APPROVED** [review]

**Comment by Thalley** [comment]
> Some peripheral tests are failing if CONFIG_BT_EXT_ADV=n. That was previously implicitly enabled by MESH but it has dedicated overlay.
> 
> Affected tests: GAP/BROB/BCST/BV-03-C GAP/CONN/UCON/BV-06-C GAP/PRIV/CONN/BV-10-C

Do we then never test with `CONFIG_BT_EXT_ADV=n` now?

**Comment by sjanc** [comment]
no (at least not since MESH enabled ext adv by default)

**Comment by Thalley** [comment]
> no (at least not since MESH enabled ext adv by default)

That seems like an oversight to me, as legacy advertising is still the default in Zephyr. 
Should we have an overlay for extended advertising? IMO it would make sense to run all advertising tests (or rather those that are applicable) for both legacy and extended.

**Review by MariuszSkamra — APPROVED** [review]

**Pull request merged**
