### PR TITLE
samples/subsys/mcumgr/smp_svr: Define Image Version as Default

### PR DESCRIPTION
**Pull request by joaodullius**
Define CONFIG_MCUBOOT_IMAGE_VERSION as default in the example, as this is crucial for versioning using mcumgr/smp_svr

### CODE REVIEW

**Comment by de-nordic** [comment]
Commit missing sign-off.

**Comment by joaodullius** [comment]
> Commit missing sign-off.
Amended, sorry.

**Comment by de-nordic** [comment]
Can you squash that into one commit and force push to the branch?

**Comment by joaodullius** [comment]
I was not able to squash due to merging into the branch. Will start from scratch on a new branch.

**Comment by de-nordic** [comment]
@joaodullius Do not close this, just push your new branch here.

**Comment by joaodullius** [comment]
> @joaodullius ~Do not close this, just push your new branch here.~
> Sorry I have not noticed that you are working from main branch.

Yep... This is my first contribution attempt, and it got a little messy. I Closed it and opened again as #37208

**Pull request closed without merging**
