### PR TITLE
Intel S1000 Kconfig cleanup and build fixes

### PR DESCRIPTION
**Pull request by nashif**
- move options from _defconfig to Kconfig.defconfig
- Fix build issue with new logger macros

### CODE REVIEW

**Review by rgundi — APPROVED** [review]
LGTM. Thanks for this.

**Review by rgundi — COMMENTED** [review]
@nashif, things that are configurable by the App goes into _defconfig and those that are not configurable (invisible) goes into Kconfig.defconfig, right? So, don't you think all the interrupt configurations should get into Kconfig.defconfig? I am a bit confused here. I understand the USB parameters being in _defconfig though.

**Comment by nashif** [comment]
> @nashif, things that are configurable by the App goes into _defconfig and those that are not configurable (invisible) goes into Kconfig.defconfig, right?

No, the application is responsible for enabling the features it needs, such features should not be part of the default configuration. So they should not be in _defconfig.

Some of the USB and Interrupts configs can also be moved, but I see those as essential for any application right now, so lets leave them.

**Review by sathishkuttan — APPROVED** [review]
LGTM

**Pull request merged**
