### PR TITLE
esp32s3: i2s: draft of driver

### PR DESCRIPTION
**Pull request by TiboDevC**
Tested with west build samples/drivers/i2s/echo on esp32s3-wroom-1 devkit
It requires those commits https://github.com/zephyrproject-rtos/hal_espressif/pull/236

**This is just a draft, it does not work yet.**
It could be a base if someone is willing to help.

### CODE REVIEW

**Comment by sam131208** [comment]
@TiboDevC   The register address of the i2s0 controller is incorrectly written as reg = <0x6002d000 0x1000>.

**Comment by TiboDevC** [comment]
@sam131208 all right, wrong copy past!

**Comment by rftafas** [comment]
@TiboDevC hal_espressif changes were merged. Do you have any updates on this?

**Comment by ddB0515** [comment]
also curious if there is anything changed, would like to help so can you post an update
(also replied on Discord so maybe easier to follow)

**Comment by TiboDevC** [comment]
The first step, merging https://github.com/zephyrproject-rtos/hal_espressif/pull/236 is done, so now the driver can be implemented.
I am new to Zephyr, so this is a naive approach of driver and I am quite sure I am missing some Zephyr details.

I wanted the driver to work only with DMA as a first step but I am not sure of to interface the I2S driver and the DMA driver. In ´esp32s3_devkitm.dts´ I declared
```
&i2s0 {
     status = "okay";
     pinctrl-0 = <&i2s0_default>;
     pinctrl-names = "default";

     dma-names = "rx", "tx";
     dmas = <&dma 2>, <&dma 3>;
 };
```
which comes from `zephyr/dts/bindings/dma/espressif,esp32-gdma.yaml` I think. This part has to be checked. 
`dts/bindings/i2s/espressif,esp32-i2s.yaml` also the I2S configuration I created from what I understood but I am not sure of all the keywords like
```
  dma-enabled:
     type: boolean
     description: Enable I2S DMA support

   dma-clk:
     type: int
     description: DMA clock source
```
are they Zephyr keywords defined somewhere else?

For `drivers/i2s/i2s_esp32.c` I tried to implement same logic as other I2S drivers in this folder.

I could receive some data from the I2S hardware block at the end but I am not sure about the Zephyr implementation and device tree declaration, interaction between the I2S driver and GDMA driver.

So still some work to do.

**Comment by LucasTambor** [comment]
Hello @TiboDevC . How is it going with this driver?

You said you are having some trouble interfacing the I2S driver with DMA. ESP32S3 have `GDMA` peripheral which is implemented by  [dma_esp32_gdma.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/dma/dma_esp32_gdma.c). 

You can interface the I2S driver with it using the DMA API from [zephyr/drivers/dma.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/drivers/dma.h).

The best example we have on this is the UART driver [uart_esp32.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_esp32.c) when `CONFIG_UART_ASYNC_API=y`. You can also take a look at the [esp32s3_devkitm.overlay](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/uart/uart_async_api/boards/esp32s3_devkitm.overlay) from the [uart_async_api](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/uart/uart_async_api) test to see how the dts is supposed to look. 

There is no need for this in the bindings file: 
```
  dma-enabled:
     type: boolean
     description: Enable I2S DMA support

   dma-clk:
     type: int
     description: DMA clock source
```
Which seems to be inspired by the [espressif,esp32-spi.yaml](https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/spi/espressif%2Cesp32-spi.yaml) This properties are required in this case because ESP32 and ESP32S2 does **not** have the `GDMA` peripheral and the DMA operations are controlled withing the SPI domain. But, as I said, this does not apply to I2S for ESP32S3.

I suggest you take a look on how other vendor implemented their I2S drivers to see the usage of DMA API, such as `dma_start`, `dma_config`, `dma_stop`, and so on. 

Happy coding and feel to ask if any doubt.

**Comment by rhvarrier** [comment]
Hello, has this been finally merged ? I see esp32_i2s.c is present in the main branch. However I'm unable to get a clear audio out using this driver (I'm only getting only a very distorted output)

**Comment by rftafas** [comment]
It is known to work, please update to latest, there were lots of fixes.

**Comment by rhvarrier** [comment]
> It is known to work, please update to latest, there were lots of fixes.

@rftafas Thanks for the response. Do you have a specific working example for i2s in esp32. When using a generic Max98357 i2s DAC, all I'm getting is static and distorted noise.

**Comment by rftafas** [comment]
It is working. Unfortunately, I don't have examples. Please, take this to discord, similar users reported similar and were able to solve the problem by proper configuration of the system.

**Pull request closed without merging**
