### PR TITLE
Revert dts: Add led nodes to nxp boards, refactor mcux gpio driver to use dts

### LINKED ISSUE #7172: Mcr20a initialization crashes with frdm_k64f board
Mcr20a initialization crashes in frdm_k64f, latest upstream commit I noticed this crash is
--------------------------------------------------------------------------------------
commit f5f95ee3a909e522acb1a8ee534635d45803441c
Author: Leandro Pereira <leandro.pereira@intel.com>
Date:   Fri Apr 6 15:55:11 2018 -0700

    kernel: sem: Ensure that initial count is lesser or equal than limit
--------------------------------------------------------------------------------------

***** BUS FAULT *****
  Executing thread ID (thread): 0x20008a14
  Faulting instruction address:  0x11f38020
  Instruction bus error
Fatal fault in essential thread! Spinning...

### PR DESCRIPTION
**Pull request by MaureenHelm**
Reverts #7129. Fixes #7172

### CODE REVIEW

**Review by rveerama1 — APPROVED** [review]

**Review by galak — CHANGES_REQUESTED** [review]
Do we really need to revert all the changes?  It seems like the change for "dts: Add gpio labels to all kinetis socs" and "boards: Move led and button definitions to dts for kinetis bo…" would be ok to keep.

**Comment by MaureenHelm** [comment]
> Do we really need to revert all the changes? It seems like the change for "dts: Add gpio labels to all kinetis socs" and "boards: Move led and button definitions to dts for kinetis bo…" would be ok to keep.

I almost kept those, but thought it would be confusing to others if I reverted only part of the offending PR.

**Review by mike-scott — APPROVED** [review]

**Comment by galak** [comment]
How about we hold on this PR, and see if we can fixup FXOS8700, MCR20A, and FXAS21002_GPIO_NAME

**Comment by galak** [comment]
Opened PR #7188 an alternate to this PR.

**Comment by MaureenHelm** [comment]
I updated to revert only the offending commits, not the entire PR.

**Comment by galak** [comment]
This should be fixed cleanly now with merger of #7355

**Pull request closed without merging**
