### PR TITLE
dts: nxp edma update edma label to align with config setting

### PR DESCRIPTION
**Pull request by hakehuang**
after 7c699348a846df7c8105406898521eda1615be88
Convert drivers to new DT device macros

now the device name is aligned with label so we need
align them to default config

Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>

### CODE REVIEW

**Comment by hakehuang** [comment]
@MaureenHelm , this updates align for all default settings to use the right dma device name. so that DTS is aligned with config settings

**Review by MaureenHelm — APPROVED** [review]

**Comment by galak** [comment]
No issue with the change, but curious why its needed.  Is there somewhere we depend on the label name being "DMA_x"?

**Comment by hakehuang** [comment]
@mmahadevan108 , I need you help to get another review approving. Thanks in advance.

**Comment by hakehuang** [comment]
> No issue with the change, but curious why its needed. Is there somewhere we depend on the label name being "DMA_x"?

@galak , this is because in dma driver test, we are using the config_dma_x, to minimum the code change, I rename the EDMA label to DAM_0 to align with the configs used.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Looks like this needs rebasing now.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
