### PR TITLE
dts: arm: 96b_carbon: add I2C_2 support

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
This patch enables I2C_2 support for 96b_carbon. Without
this patch, trying to build I2C_2 for 96b_carbon will result in 
build error.

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
send this against the 'arm' branch.

Also, curious what purpose are we exposing I2C_2 for?

**Comment by Mani-Sadhasivam** [comment]
@galak I2C_1 on 96b_carbon seems to be not working. But I2C_2 works without any issues.

**Comment by ydamigos** [comment]
@Mani-Sadhasivam I am driving an oled display using I2C_1 on 96b_carbon. I just test it again against master branch.

**Comment by galak** [comment]
I'm confused, you are connecting an oled display to I2C_1 or I2C_2?

I assume I2C_1 doesn't work for you because the pins are shared with an UART.

I'm not sure if we should have the .dts change since we'd be enabling I2C_2 always - seems like a usecase/application specific enablement.  The .fixup file update makes sense to me.  I'd be ok if we update the .dts, but remove status="ok"

**Comment by ydamigos** [comment]
@galak I am connecting the oled display to I2C_1 (PB6, PB7) and it works fine. There is no conflict with the pins between UART and I2C in the default 96b_carbon dts file. USART1 uses pins PA10, PA9, USART2 uses pins PA3, PA2.
According to @Mani-Sadhasivam reply on the users mailing list he was using pins PB8, PB9 for I2C_1 which are not configured in the board's default pinmux.

>  The .fixup file update makes sense to me. I'd be ok if we update the .dts, but remove status="ok"

+1

**Comment by Mani-Sadhasivam** [comment]
@galak closing this PR as I've messed with the update. I'll open another PR

**Pull request closed without merging**
