### PR TITLE
CivetWeb reorganize samples

### LINKED ISSUE #28941: Civetweb: create separate directory
**Is your feature request related to a problem? Please describe.**
CivetWeb using samples have potential to spread over multiple directories (especially after merging of #28323).

**Describe the solution you'd like**
Put all CivetWeb using samples into one `civetweb` root directory. Thus allowing http/websocket and many more CivetWeb based samples existing in one root directory (e.g. `samples/net/civetweb/http_server`, `samples/net/civetweb/websocket_server`).

**Describe alternatives you've considered**
none. (Maybe your suggestion?)

**Additional context**
Should be done incrementally after merging of #28323 and  #30175

### PR DESCRIPTION
**Pull request by KozhinovAlexander**
- Move all CivetWeb samples to one directory
- Add directory with CivetWeb common includes
- Update cmake files

### CODE REVIEW

**Comment by Nukersson** [comment]
@jukkar @PiotrZierhoffer @MaureenHelm Please review.

**Comment by jukkar** [comment]
Looks ok, but we could put all the civetweb code into `samples/net/civetweb` directory. Having the code under sockets seems unnecessary here.

**Comment by Nukersson** [comment]
> Looks ok, but we could put all the civetweb code into `samples/net/civetweb` directory. Having the code under sockets seems unnecessary here.

@jukkar Any suggestions where to put it then?

**Comment by jukkar** [comment]
> Any suggestions where to put it then?

Please put all civetweb samples code to `samples/net/civetweb` directory. So basically just move the code you have now in `sockets/civetweb` one level up.

**Comment by Nukersson** [comment]
> > Any suggestions where to put it then?
> 
> Please put all civetweb samples code to `samples/net/civetweb` directory. So basically just move the code you have now in `sockets/civetweb` one level up.

Done

**Review by jukkar — APPROVED** [review]

**Comment by pfalcon** [comment]
> samples: net: sockets: civetweb 

I'm not sure how good that is for the subject line of the commit. (I also personally notice that commit message misses dots at the end of sentences and capitalization at the beginning).

**Comment by Nukersson** [comment]
> > samples: net: sockets: civetweb 
> 
> I'm not sure how good that is for the subject line of the commit. (I also personally notice that commit message misses dots at the end of sentences and capitalization at the beginning).
> 

I would say - it is not important for the code quality and still understandable for log 9f push messages.

**Comment by pfalcon** [comment]
> I would say - it is not important for the code quality

The quality of code definitely depends on the quality of the change control. And proper change descriptions are unalienable part of the quality change control. Otherwise, it may be a nice surprise that behind barely readable change messages there're top-notch quality changes. I myself didn't check that though, I was stopped by the commit title which doesn't describe the change properly (so, I can't verify that the change properly implements the intent of change, because again, it's not described well).

**Comment by jukkar** [comment]
> I can't verify that the change properly implements the intent of change, because again, it's not described well

Well, you could propose a fix if you are reviewing these PRs.

Anyway, the commit subject of the first commit is indeed a bit short. We could change that to
`samples: net: civetweb: Refactor code structure` or something like that.

**Comment by Nukersson** [comment]
> > I would say - it is not important for the code quality
> 
> The quality of code definitely depends on the quality of the change control. And proper change descriptions are unalienable part of the quality change control. Otherwise, it may be a nice surprise that behind barely readable change messages there're top-notch quality changes. I myself didn't check that though, I was stopped by the commit title which doesn't describe the change properly (so, I can't verify that the change properly implements the intent of change, because again, it's not described well).

@pfalcon Thank you fro your message. I got it. Could you probably more precise point on stuff, you want improve? It will help you and me to follow better quality of commits.

**Comment by Nukersson** [comment]
> > I can't verify that the change properly implements the intent of change, because again, it's not described well
> 
> Well, you could propose a fix if you are reviewing these PRs.
> 
> Anyway, the commit subject of the first commit is indeed a bit short. We could change that to
> `samples: net: civetweb: Refactor code structure` or something like that.

Done

**Comment by pfalcon** [comment]
@Nukersson 

> @pfalcon Thank you fro your message. I got it. Could you probably more precise point on stuff, you want improve? It will help you and me to follow better quality of commits.

Will do, thanks. I kind of started with the knowledge that this is not your first contribution, and that the guidelines for Zephyr commit messages are written down in pretty detailed form: https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines . My point was to draw attention that these guidelines aren't a kind of "sinecure", but actually useful for other developers (I for example regularly do `git log --oneline`) and would help to get reviews quicker/easier on average.

(And it's especially important for all maintainers to be on the same line regarding that, and you're now a maintainer of these samples, and will review other people's PRs for them).

**Review by pfalcon — APPROVED** [review]

**Pull request merged**
