### PR TITLE
intel_s1000: scripts: Fix the runner script

### PR DESCRIPTION
**Pull request by rgundi**
This essentially reverts the commit bc7b1c5 in addition to
minor changes.

Signed-off-by: Rajavardhan Gundi <rajavardhan.gundi@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
This would be a bit easier to review if it was 2 commits: a revert and then the new changes you made.

**Comment by rgundi** [comment]
> This would be a bit easier to review if it was 2 commits: a revert and then the new changes you made.

Done.

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
These changes need to be submitted to https://github.com/zephyrproject-rtos/west instead.

**Comment by rgundi** [comment]
@MaureenHelm So, should i clone a new repository for west and submit this change there? That'll ultimately get reflected here?

**Comment by MaureenHelm** [comment]
> @MaureenHelm So, should i clone a new repository for west and submit this change there? That'll ultimately get reflected here?

Yes

**Comment by rgundi** [comment]
> @MaureenHelm If i have to submit it on west, it will be a single commit as the patch that is being reverted is absent on west. So, the changes will be squashed back to a single commit. Is that ok?

@MaureenHelm can you please comment?

**Comment by nashif** [comment]
> @MaureenHelm If i have to submit it on west, it will be a single commit as the patch that is being reverted is absent on west. So, the changes will be squashed back to a single commit. Is that ok?

yes, that is ok. west is another repo with a different code base.

**Comment by rgundi** [comment]
Pushed it to west. https://github.com/zephyrproject-rtos/west/pull/101

**Comment by rgundi** [comment]
@MaureenHelm Though this is now merged into west repository, i still don't see the changes in the mainline Zephyr. Does that happen manually?

**Pull request closed without merging**
