### PR TITLE
Bluetooth: tests: Fix config option dependencies

### PR DESCRIPTION
**Pull request by cvinayak**
With the introduction of controller's advanced features
Kconfig option, some of the dependent options where not
enabled in the init tests build. Fixed by enabling the
advanced features Kconfig options.

Also, updated conf files to reflect latest set of Kconfig
options supported by the Bluetooth controller subsystem.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by jhedberg** [comment]
I pushed a fix to this PR for the compiler warning that was causing CI to fail

**Comment by jhedberg** [comment]
Ok, seems there are more warnings, but this time in the controller side. @cvinayak I'll leave this one to you:

`subsys/bluetooth/controller/ll_sw/ctrl.c:2613:29: error: ‘LLCP_ENCRYPTION’ undeclared (first use in this function)
         (conn-&gt;llcp_type != LLCP_ENCRYPTION)) ||`

**Comment by cvinayak** [comment]
@jhedberg I will handle the errors and push updates.

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@cvinayak : IMHO this should not wait for the -Ofast fix. Turns out there is no trivial solution, so I need some time to fix it.

**Comment by jhedberg** [comment]
so, ok to merge then?

**Comment by SebastianBoe** [comment]
Wait, this might be broken ...

**Comment by SebastianBoe** [comment]
I expected

cmake -DCONF_FILE=prj_controller_dbg.conf -DBOARD=nrf51_pca10028 ~/zephyr/tests/bluetooth/init

to produce a .config that had CONFIG_BT_CTLR_FAST_ENC=y, but it didn't.

Commenting out this in prj_controller_dbg.conf

#CONFIG_BT_CTLR_PHY_2M_NRF=y

fixed the issue.

Perhaps the root cause is here:

```
config BT_CTLR_LE_ENC
	bool
	depends on !BT_CTLR_DATA_LENGTH_CLEAR && !BT_CTLR_PHY_2M_NRF
```

LE_ENC does not depend on ! PHY_2M_NRF does it?

I'm not familiar enough with bluetooth to be sure what's going wrong.

**Comment by carlescufi** [comment]
@SebastianBoe encryption and 2Mbit/s PHY are mutually exclusive in nRF51 at least

**Comment by SebastianBoe** [comment]
Hmm, okay, so I guess it is prj_controller_dbg.conf that is broken then.

It should not be both enabling FAST_ENC and 2M at the same time.

**Comment by SebastianBoe** [comment]
I'll leave this to you @cvinayak , I have my own bugs to deal with :)

**Comment by cvinayak** [comment]
@SebastianBoe in a nrf51_pca10028 FAST_ENC is disabled when PHY_2M_NRF is enabled... but on nrf51_pca10040 FAST_ENC is enabled as PHY_2M_NRF is invalid for nRF52.

This PR is good as-is, as these conf files are meant to cover Kconfig options under sanitycheck.

**Comment by SebastianBoe** [comment]
I don't like that a user can enable FAST_ENC and then it builds without FAST_ENC and there is no feedback to the user about something being amiss. But this is not my subsystem, so if this is okay for you guys then it is OK for me.

**Comment by carlescufi** [comment]
@SebastianBoe I don't like it either but this is how it was before CMake. If we want to fix that it should be a separate PR

**Comment by SebastianBoe** [comment]
Interestingly enough, the linux kernel's merge_config behaves as I would expect,
it warns you if you tried to enable something but it wasn't enabled.

https://github.com/torvalds/linux/blob/master/scripts/kconfig/merge_config.sh#L157
https://github.com/zephyrproject-rtos/zephyr/pull/5086#issuecomment-346063707

**Pull request merged**
