### PR TITLE
ci: fix doc workflow on schedule

### PR DESCRIPTION
**Pull request by nashif**
Build phase was skipped, we were checking for file changes which will
not have any results on a scheduled event.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by kartben — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by kartben** [comment]
Thanks for the quick fix, @nashif! I would suggest taking this in as a hotfix since until this is merged, docs.zephyrproject.org is not properly being updated.

**Review by aescolar — APPROVED** [review]

**Comment by aescolar** [comment]
@kartben @nashif feel free to add hotfix if you want and press the button. Otherwise, we just wait 3 hours , in which @stephanosio can look at it

**Review by henrikbrixandersen — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by stephanosio — CHANGES_REQUESTED** [review]
Actually, something does not seem right in this PR. What problem is this fixing?

**Comment by kartben** [comment]
> Actually, something does not seem right in this PR. What problem is this fixing?

Making sure that the job that runs every 3 hours always actually builds the docs no matter what (i.e. even if there is seemingly no change as per the changed-files filter), so that the "publish" job always has a fresh site/PDF to deploy.

**Comment by stephanosio** [comment]
> builds the docs no matter what (i.e. even if there is seemingly no change as per the changed-files filter)

Why do we want to re-build and re-publish docs when there is no change?

As far as I understand, `tj-actions/changed-files` supports `schedule` event and compares the content of the current `schedule` event against the last triggered `schedule` event. Was there a problem with this?

**Comment by nashif** [comment]
> Why do we want to re-build and re-publish docs when there is no change?

because this is the original behaviour. We never did scheduled CI based on the files being changed. I prefer thas instead of trusting the files we list there which might become out of date for whatever reason. Let's just continue as before, aside from that, this actually has some real fixes to the workflow and dependencies.

**Comment by stephanosio** [comment]
> because this is the original behaviour. We never did scheduled CI based on the files being changed. I prefer thas instead of trusting the files we list there which might become out of date for whatever reason. Let's just continue as before, aside from that, this actually has some real fixes to the workflow and dependencies.

Fair enough. While change-based triggering is nice way to optimise CI usage and reduce cost, HTML doc build only takes around 15 minutes and the associated cost is rather insignificant.

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
