### PR TITLE
sample: subsys: shell: shell_module: add config for timing at boot

### LINKED ISSUE #33275: ehl_crb: samples/subsys/shell/shell_module does not work
samples/subsys/shell/shell_module on EHL does not work at all. 

HW dbg shows it went to the fatal exception handling path.

I disabled all the thread related options in the prj.conf:
```                                                                                            
CONFIG_PRINTK=y
CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_INIT_STACKS=y
#CONFIG_THREAD_STACK_INFO=y
CONFIG_KERNEL_SHELL=y
#CONFIG_THREAD_MONITOR=y
CONFIG_BOOT_BANNER=n
#CONFIG_THREAD_NAME=y
CONFIG_DEVICE_SHELL=y
CONFIG_POSIX_CLOCK=y
CONFIG_DATE_SHELL=y
#CONFIG_THREAD_RUNTIME_STATS=y
```

And it worked again. So one of this option is broken on EHL.

### PR DESCRIPTION
**Pull request by jenmwms**
Use of CONFIG_THREAD_RUNTIME_STATS was added to this sample, but
caused issue because the call to z_thread_mark_switched_in()
is using k_cycle_get_32() before the timer is initialized.
Enable CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y to
select hidden config CONFIG_TIMING_FUNCTIONS_NEED_AT_BOOT,
which calls to initialize the timer needed at boot for thread
runtime stats configuration.

Fixes #33275

Signed-off-by: Jennifer Williams <jennifer.m.williams@intel.com>

### CODE REVIEW

**Comment by jenmwms** [comment]
Tested on ehl_crb and qemu_x86_64.

**Review by nordic-krch — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
Looks good, but you'll need to fix the Compliance check failure (missing newline at EOF)

**Review by ceolin — APPROVED** [review]

**Comment by jenmwms** [comment]
Resolved compliance check error. Curious why my pre-check did not catch missing EOF :/  Thanks for the patience!

**Review by yerabolu — APPROVED** [review]

**Comment by jenmwms** [comment]
> Resolved compliance check error. Curious why my pre-check did not catch missing EOF :/ Thanks for the patience!

This compliance error bouncing is confusing. First failed because missing new line at EOF, so I added it, but now it has error to remove the blank line at end of file. Which is correct? Other prj.conf files do not have a blank line at the end of file.

**Review by andyross — APPROVED** [review]
Nice catch!

**Comment by andyross** [comment]
FWIW: Longer term, it's probably worth adding a relevant kconfig select in there to make sure this misconfiguration doesn't happen in the future.  Alternatively we should figure out what the timer driver is doing wrong and fix it there.

**Comment by jenmwms** [comment]
Thanks @jhedberg for the help to catch the line ending characters that CI was detecting. I can see it now it VS Code. Cheers!

**Review by enjiamai — APPROVED** [review]

**Pull request merged**
