### PR TITLE
Add MPS3 AN547 Non Secure target

### PR DESCRIPTION
**Pull request by theotherjimmy**
~NOTE: This includes, and depends on #38149. ATM, this means that the last 2 commits in the history are added by this PR.~ Rebased onto current main.

This adds a new target, `mps3_an547_nonsecure`, that builds TF-M as the Secure world firmware and Zephyr as the Non-secure world firmware.

### CODE REVIEW

**Review by microbuilder — CHANGES_REQUESTED** [review]
NS boards should have a `_ns` suffix, not the older `_nonsecure`. See board name list here as a reference: https://docs.zephyrproject.org/latest/guides/tfm/requirements.html#tf-m-requirements

Also , please make sure to add this board to the documentation/list above. See: https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/guides/tfm/requirements.rst

**Review by microbuilder — DISMISSED** [review]

**Review by microbuilder — APPROVED** [review]

**Comment by galak** [comment]
The CI failure is not related to this PR, so going to merge it and we'll open an issue to track the failure which is due to QEMU.

**Review by galak — APPROVED** [review]

**Comment by dleach02** [comment]
Okay... turns out CI failure was related to this PR... FYI :-(

**Comment by theotherjimmy** [comment]
It's related to the mps3-an547, but not specifically relating to secure/non-secure. (note that the tests are for the mps3_an547 without the _ns suffix). At least one of the problems is documented in 2 issues: https://github.com/zephyrproject-rtos/zephyr/issues/40970 and https://github.com/zephyrproject-rtos/sdk-ng/issues/420

**Comment by theotherjimmy** [comment]
The other of the problems is documented here: https://github.com/zephyrproject-rtos/zephyr/issues/40569

**Pull request merged**
