### PR TITLE
west: runners: jlink: option to flash .hex files

### PR DESCRIPTION
**Pull request by JordanYates**
Adds the option to flash `.hex` files instead of the default `.bin` file.
There are two primary reasons why a developer may want to flash a `.hex` file instead of `.bin`:
1. Faster programming in cases where there is large amounts of padding between sections
2. To avoid writing to memory addresses without variables that may be used for other purposes

In support of the usefulness of `.hex`, `nrfjprog` chooses to flash `.hex` files, not `.bin`.
Boards can enable this behavior by default by updating `board.cmake` to:

`board_runner_args(jlink "--device=nrf52" "--speed=4000" "--flash-hex")`

### CODE REVIEW

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
There are longstanding usability issues related to west flash that we can't seem to find cycles to prioritize, e.g. https://github.com/zephyrproject-rtos/zephyr/pull/18159. I understand and sympathize with this situation; however, I don't want to make it worse by adding options like this. I think it makes the situation worse by increasing the amount of runner-specific behavior users will have to deal with.

Can we just make jlink flash .hex files by default instead? I can't think of a reason why that wouldn't be a pareto improvement offhand.

**Comment by JordanYates** [comment]
> Can we just make jlink flash .hex files by default instead? I can't think of a reason why that wouldn't be a pareto improvement offhand.

That works as well. Could there be cases where users are expecting padding bytes to be flashed to a value instead of ignored? Some situation where a CRC is run over FLASH?

**Comment by henrikbrixandersen** [comment]
How about signed MCUboot images with padding?

**Comment by JordanYates** [comment]
> How about signed MCUboot images with padding?

Maybe, but given that the nrfjprog runner uses `.hex` apparently without problems, I am leaning towards there not being any realistic configurations where it would be a problem.

**Comment by mbolivar-nordic** [comment]
Right, MCUboot's imgtool supports hex files, so that's not an issue.

**Pull request closed without merging**
