### PR TITLE
drivers: modem: ublox-sara-r4: fix getaddrinfo

### PR DESCRIPTION
**Pull request by hwilmers**
The implementation of offload_getaddrinfo in this driver failed
when the node it was called with was an IP address. This condition
was never detected, and as a consequence a DNS query was done on
the IP address instead of returning it directly.

Also, the port was set first after running the DNS query.
As a consequence, if the IP address would have been returned directly,
this would have been done without a port been set.

Both errors are fixed in this patch.

Signed-off-by: Hans Wilmers <hans@wilmers.no>

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Looks fine by me, just submit as a normal PR for a proper review.

**Review by jukkar — APPROVED** [review]

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by hwilmers** [comment]
@jukkar @mike-scott Thanks for a fast review. Any chance to get it merged?

**Comment by jukkar** [comment]
> Any chance to get it merged?

I don't know. 2.3 release manager will decide, @carlescufi do you think this could be merged to 2.3-rc1?

**Comment by carlescufi** [comment]
Yes, this is fixing a bug so it can be merged.

**Pull request merged**
