### PR TITLE
ci: create a merged junit report

### LINKED ISSUE #34264: CI: twister: Add  merged report from all sub-builds to buildkite build artifacts
**Is your enhancement proposal related to a problem? Please describe.**
If one wants to check the status of some particular test run in the CI, they will have to check individual reports/artifacts from sub-builds (there are 20 of them). It would be more convenient to be able to have access to a single report with all the results

**Describe the solution you'd like**
After all sub-builds are executed, the resulting XML reports are merged into a single one and added to the build artifacts

**Describe alternatives you've considered**
Seems straight forward and I have no alternatives

### PR DESCRIPTION
**Pull request by galak**
Upload a build artifact that is the merged junit report

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
Start at dealing with:
https://github.com/zephyrproject-rtos/zephyr/issues/34264

**Comment by galak** [comment]
@nashif - Do we have any means to filter a junit file to just failures?

**Comment by PerMac** [comment]
@galak In our internal CI we have a custom script for getting "failures", "errors" and "skips" from reports. It goes through the XML entries (nodes) and checks if they contain "error"/'failure"/"skipped". Sth like this:
```
platforms = ET.parse(xml_path).getroot()
for platform_node in platforms:
    plat_name = platform_node.attrib['name']
    for tc_node in platform_node[1:]:
        ts_id = tc_node.attrib['classname']
        *_, tc_id = tc_node.attrib['name'][len(ts_id) + 1:].rsplit(".", 1)

        failure_nodes = tc_node.findall("failure")
        error_nodes = tc_node.findall("error")
        skip_nodes = tc_node.findall("skipped")
        if failure_nodes:
            failure_message = ' '.join(ET.tostring(failure, 'unicode') for failure in failure_nodes)
        elif error_nodes:
            error_message = ' '.join(ET.tostring(error, 'unicode') for error in error_nodes)
        elif skip_nodes:
            skip_message = skip_nodes[0].attrib['message']
```

**Comment by PerMac** [comment]
I think junit2html must be ablo to get the summary of failures/errors. When you click on a given platform in the weekly on target results the report starts from listing all errors/failures: https://testing.zephyrproject.org/daily_tests/zephyr-v2.5.0-2159-g48f5e746c820/report/nrf5340dk_nrf5340_cpuapp.xml.html#07aed72e-e206-4e2d-9296-0464bb7619eb
I also had a quick glance at what google tells for "github actions junit summary" and these actions popped up:
https://github.com/marketplace/actions/publish-unit-test-results - this looks quite advanced
and https://github.com/mikepenz/action-junit-report
but I haven't check much about these actions.

**Comment by galak** [comment]
> I think junit2html must be ablo to get the summary of failures/errors. When you click on a given platform in the weekly on target results the report starts from listing all errors/failures: https://testing.zephyrproject.org/daily_tests/zephyr-v2.5.0-2159-g48f5e746c820/report/nrf5340dk_nrf5340_cpuapp.xml.html#07aed72e-e206-4e2d-9296-0464bb7619eb
> I also had a quick glance at what google tells for "github actions junit summary" and these actions popped up:
> https://github.com/marketplace/actions/publish-unit-test-results - this looks quite advanced
> and https://github.com/mikepenz/action-junit-report
> but I haven't check much about these actions.

Not sure I follow.  The goal with this PR was mostly to publish the merged junit xml and I added running junit2html since it seemed like low hanging fruit.  (and to show how we can annotate the buildkite report outselves).  I figure we can work on improving the "HTML" report as we go forward.

**Comment by PerMac** [comment]
@galak This was my answer to your "Do we have any means to filter a junit file to just failures?" question. Just some loose ideas.

**Review by nashif — APPROVED** [review]

**Review by PerMac — APPROVED** [review]

**Pull request merged**
