### PR TITLE
tests: drivers: can: shell: use HDA logging on cavs platforms

### PR DESCRIPTION
**Pull request by shuai1x**
This PR links to https://github.com/zephyrproject-rtos/zephyr/pull/50006.
And it also links to https://github.com/zephyrproject-rtos/zephyr/pull/50401, https://github.com/zephyrproject-rtos/zephyr/pull/50403, https://github.com/zephyrproject-rtos/zephyr/pull/50516.

Logging through winstream can miss logs when log output is fast. 
The shell test suffer from this on CAVS platforms. 
Add CAVS config overlays to use HDA logging instead.

Signed-off-by: Zhao Shuai <shuai1x.zhao@intel.com>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
Should this really be configured on a test-by-test basis? This seems very fragile. Why not configure it globally for these boards?

**Comment by shuai1x** [comment]
> Should this really be configured on a test-by-test basis? This seems very fragile. Why not configure it globally for these boards?

Because we configure it when we only want to use HDA logging, but most of cases are using winstream. And only these three tests will fail due to missing logs that is caused by winstream. So we want to use HDA logging to fix this problem. But not all the cases need to use HDA logging, we can't abandon winstream.

**Comment by henrikbrixandersen** [comment]
> Because we configure it when we only want to use HDA logging, but most of cases are using winstream. And only these three tests will fail due to missing logs that is caused by winstream. So we want to use HDA logging to fix this problem. But not all the cases need to use HDA logging, we can't abandon winstream.

So what happens when the timing of another random test case changes or is borderline to what winstream can handle of output? I still think this is a very fragile approach.

**Comment by shuai1x** [comment]
> > Because we configure it when we only want to use HDA logging, but most of cases are using winstream. And only these three tests will fail due to missing logs that is caused by winstream. So we want to use HDA logging to fix this problem. But not all the cases need to use HDA logging, we can't abandon winstream.
> 
> So what happens when the timing of another random test case changes or is borderline to what winstream can handle of output? I still think this is a very fragile approach.

Winstream and HDA logging are the two methods for CAVS for logging output. Because we can't abandon the winstream, but need to fix the problem that winstream missing log, so we use HDA logging for these three cases. We only use the HDA logging for these three cases, and other tests still use winstream, not HDA logging. And if any case need to use the HDA logging, we must add the boards overlay. So for these three cases, we add the boards overlay, which means this case we use HDA logging, so no mater the timing changes or being borderline to what winstream can handle of output, it still use the HDA logging, not winstream.

**Comment by str4t0m** [comment]
@shuai1x Could you please check if #50623 would also fix the issue.

**Review by nashif — CHANGES_REQUESTED** [review]
> @shuai1x Could you please check if #50623 would also fix the issue.

yes, please do. The changes in this PR is a very bad workaround IMO, this does not scale.

**Comment by shuai1x** [comment]
> > @shuai1x Could you please check if #50623 would also fix the issue.
> 
> yes, please do. The changes in this PR is a very bad workaround IMO, this does not scale.

Ok, I will try and get back to you soon.

**Comment by shuai1x** [comment]
> > @shuai1x Could you please check if #50623 would also fix the issue.
> 
> yes, please do. The changes in this PR is a very bad workaround IMO, this does not scale.

I tested the PR https://github.com/zephyrproject-rtos/zephyr/pull/50623 on CAVS platform five times. And it would pass stably, so this PR would also fix this issue. @nashif @str4t0m

**Comment by henrikbrixandersen** [comment]
@shuai1x Can this be closed, then?

**Comment by henrikbrixandersen** [comment]
Closing as fixed by #50623. Please reopen if that is not the case.

**Pull request closed without merging**
