### PR TITLE
DT: Rename from dts.fixup to dts_fixup.h

### PR DESCRIPTION
**Pull request by SebastianBoe**
The Zephyr configuration system uses many different files in many
different formats. It makes it a lot easier for users to understand
what these files do if we use the correct file extensions.

To this end we rename the dts.fixup files to use the correct file
extension '.h'.

This is a breaking change for out-of-tree fixup files.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
If this approach is accepted I will add a deprecation warning that detects and warns about unported out-of-tree dts.fixup files.

**Review by ioannisg — APPROVED** [review]
The approach to switch to .h from .fixup is ok for me

**Review by fallrisk — APPROVED** [review]

**Review by erwango — APPROVED** [review]
Fine to me even if I'd prefer we could get rid of .fixup (_fixup.h) the soonest

**Comment by galak** [comment]
> I'm curious if @agross-linaro considered this when originally adding the fixup support. It seems like not using .h was deliberate, perhaps because fixups aren't fully formed .h files?

Yeah, I was wondering this as well, and torn about the fact that fixup files aren't exactly a well formed .h file.

**Comment by agross-linaro** [comment]
No it wasn't deliberate in the sense that I was actively avoiding .h.  It was more that I wanted to make sure people understood it was a fixup or hack.  I am ok with changing to .h

**Review by agross-oss — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@nashif : This has been synced with master and is ready for merging.

I believe the interested parties have had time to review.

**Pull request merged**
