### PR TITLE
arch: arm64: enhance backtrace dump check

### PR DESCRIPTION
**Pull request by JungoLin1978**
Examine the fp and lr values of each frame to prevent nested exceptions caused by data abort.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
Needs rebase

> @carlocaione please take a look

ping

**Comment by kartben** [comment]
@JungoLin1978 could you please rebase? I will then try to help get this reviews and approvals :)

**Comment by JungoLin1978** [comment]
@kartben I just created a new PR #82696 for this change. Please kindly review the new one. I will close this new old due to rebase issue in my local code base. Thanks for your help.

**Comment by JungoLin1978** [comment]
Replace this one with a new PR https://github.com/zephyrproject-rtos/zephyr/pull/82696

**Pull request closed without merging**
