### PR TITLE
lib: os: cbprintf: Add alignment offset to packaging

### PR DESCRIPTION
**Pull request by nordic-krch**
Added parameter to `CBPRINTF_STATIC_PACKAGE` which indicates buffer alignment offset compared to `CBPRINTF_PACKAGE_ALIGNMENT`. When offset is set to 0, macro assumes that input buffer is aligned to `CBPRINTF_PACKAGE_ALIGNMENT`. When offset is positive, macro assumes that buffer address is shifted by given number of bytes to `CBPRINTF_PACKAGE_ALIGNMENT` alignment.
    
Extended `cbprintf_package` to use len argument as alignment offset indicator when calculating length only (package pointer is null).
    
Features are not available for xtensa platform which seems to require 16 byte alignment from the package. It is only an assumption due to lack of the documentation and may be fixed in the future.
    
Feature allows to avoid unnecessary padding when package is part of a message and preceded by a header of a known size. For example, message header on 32 bit architecture has 12 bytes, long doubles are not used so cbprintf requires 8 byte alignment. Without alignment offset indicator, package containing just a string with one argument would need 4 byte padding after the header and 4 byte padding after the package. Message would be 32 bytes long. With alignment offset indication both paddings are not needed and message is only 24 bytes long.

Additionally, updated tests to validate case when input buffer is not aligned.

### CODE REVIEW

**Comment by npitre** [comment]
I think the changes to `cbprintf_package()` could be greatly simplified.
Something like:

```
diff --git a/lib/os/cbprintf_packaged.c b/lib/os/cbprintf_packaged.c
index 24e50d2f51..7592952c57 100644
--- a/lib/os/cbprintf_packaged.c
+++ b/lib/os/cbprintf_packaged.c
@@ -218,9 +218,14 @@ int cbvprintf_package(void *packaged, size_t len,
 	/*
 	 * When buf0 is NULL we don't store anything.
 	 * Instead we count the needed space to store the data.
+	 * In this case, incoming len argument indicates the anticipated
+	 * buffer "misalignment" offset.
 	 */
 	if (!buf0) {
-		len = 0;
+		align = IS_ENABLED(CONFIG_CBPRINTF_PACKAGE_LONGDOUBLE) ?
+			VA_STACK_ALIGN(long double) : VA_STACK_ALIGN(double);
+		buf += len % align;
+		len = -(len % align);
 	}
 
 	/*
```

**Comment by nordic-krch** [comment]
@npitre thanks, that simplifies a lot. Code updated. I've also added comment about sparc from https://github.com/zephyrproject-rtos/zephyr/pull/33472#discussion_r597068396 to the code.

**Review by npitre — APPROVED** [review]

**Comment by nordic-krch** [comment]
@pabigot can you take a look?

**Review by pabigot — COMMENTED** [review]
> @pabigot can you take a look?

The whole packaged cbprintf infrastructure is moving forward based only on reviews and contributions from three people who contributed to it, in a nice little nepotistic circle.  Its motivation is #31535, which so far has neither deep reviews nor an assessment of its impact on the system as a whole.

I don't see anything wrong with this PR, but as a "lame duck" Zephyr contributor I'm not comfortable being the review that gets this merged, as [I was for #32863](https://github.com/zephyrproject-rtos/zephyr/pull/32863#pullrequestreview-609211017).

IMO this initiative needs input from a wider range of the stakeholders who are going to have to use and support it in the future.  Best to start that now.

**Comment by nordic-krch** [comment]
@pabigot i only wonder how to engage people into review. Because no volunteers for reviews does not mean that there is no one waiting for the feature.There are a lot of users of the logger and quite a few that waits for v2 with new features it brings but even though #31535 is out for a while there are no reviews.

**Comment by npitre** [comment]
Hoping for wider interest is sometimes pretty utopic.

As long as there is one (or two, or three) people willing to look after 
the code that's fine. If the "stakeholders" aren't standing up to 
support it in the future then the code will naturally fade away, and 
that's fine too.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@nordic-krch please rebase

**Comment by nordic-krch** [comment]
@carlescufi rebased.

**Pull request merged**
