### PR TITLE
subsys: shell: removing legacy shell

### PR DESCRIPTION
**Pull request by jakub-uC**
All legacy shell examples have been migrated to the new shell.
In order to avoid maintaining two shell subsystems legacy shell will be removed.

Signed-off-by: Jakub Rzeszutko <jakub.rzeszutko@nordicsemi.no>

### CODE REVIEW

**Review by pfalcon — DISMISSED** [review]
Commit message:

> While all legacy shell examples have been migrated to the new shell.
In order to avoid maintaining two shell subsystems it was decided
that legacy shell will be removed.

I'm not sure I can understand that completely. Can you reword it please?

> it was decided that legacy shell will be removed.

If this was written in Wikipedia, it would immediately get *[BY WHOM?]* markup.

**Review by dbkinder — COMMENTED** [review]
Are there no doc changes needed?

**Comment by aescolar** [comment]
Isn't the legacy shell an "API" which needs to be deprecated for one release before being removed?

**Comment by jarz-nordic** [comment]
@nashif : May you please clarify if we should keep legacy shell for one more release? It sounds reasonable.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
LGTM, commit message is OK now.

**Review by aescolar — DISMISSED** [review]
After this change, aren't
subsys/console/line_fifo.c
and all the input part of driver/console/* dead code?

**Comment by jarz-nordic** [comment]
@aescolar : Possibly, but in long term we wish to use console as shell backend.

**Comment by aescolar** [comment]
> Possibly, but in long term we wish to use console as shell backend.

@jarz-nordic : So the idea is to leave those kconfig options, code and documentation as zombies in the tree? Won't that confuse things quite a bit?

**Review by nashif — APPROVED** [review]

**Pull request merged**
