### PR TITLE
cmake: remove _if_kconfig() functions

### PR DESCRIPTION
**Pull request by carlescufi**
This set of functions seem to be there just because of historical
reasons, stemming from Kbuild. They are non-obvious and prone to errors,
so remove them in favor of the `_ifdef()` ones with an explicit
`CONFIG_` condition.

Script used:
```
git grep -l _if_kconfig | xargs sed -E -i "s/_if_kconfig\(\s*(\w*)/_ifdef(CONFIG_\U\1\E \1/g" 
```

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by nashif** [comment]
I thought those were actually very useful, nice and clever macros..

**Comment by carlescufi** [comment]
> I thought those were actually very useful, nice and clever macros..

Beauty is in the eye of the beholder. I personally find them confusing and needless, but let's see what others think. I'll add an `RFC` to the title.

**Comment by carlescufi** [comment]
@nashif Unless I'm mistaken this is unearthing actual bugs:

```
Found references to undefined Kconfig symbols. If any of these are false
positives, then add them to UNDEF_KCONFIG_WHITELIST in check_compliance.py in the ci-tools repo.

If the reference is for a comment like /* CONFIG_FOO_* */ (or
/* CONFIG_FOO_*_... */), then please use exactly that form (with the '*'). The
CI check knows not to flag it.

More generally, a reference followed by $, @, {, *, or ## will never be
flagged.

CONFIG_GROVE                               drivers/CMakeLists.txt:17
CONFIG_KERNEL                              kernel/CMakeLists.txt:42, kernel/CMakeLists.txt:43
CONFIG_RTC                                 drivers/CMakeLists.txt:27
```

**Comment by jukkar** [comment]
> I personally find them confusing and needless, but let's see what others think. I'll add an `RFC` to the title.

I also would prefer that the config option is shown there, it is more clearer to the reader so +1 to this one.

**Review by jukkar — APPROVED** [review]

**Comment by nashif** [comment]
> Unless I'm mistaken this is unearthing actual bugs:

yup, those predate the kconfig checking and kconfig variables are constructed so kconfig sanity does not catch such issues.

**Review by nashif — APPROVED** [review]

**Comment by de-nordic** [comment]
The `_kconfig` variant makes it harder to search `CMakeLists.txt` for occurrences of CONFIG or other identifiers that enable certain compilations. If file name gets changed or Kconfig option gets changed, then we end up changing to `_ifdef` anyway.
The `_ifdef` variant may be given list of files to include and I do not know whether `_kconfig` could do the same.

**Review by de-nordic — APPROVED** [review]
Looks good. Thanks!

**Review by alexanderwachter — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by carlescufi** [comment]
Removed RFC from the title since this seems to have enough support.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by vanwinkeljan — APPROVED** [review]

**Pull request merged**
