### PR TITLE
samples: nats: Check return value and convert to ztest

### PR DESCRIPTION
**Pull request by punitvara**
Check return value for the function and convert test case
to ztest framework

Signed-off-by: Punit Vara <punit.vara@intel.com>

### CODE REVIEW

**Comment by punitvara** [comment]
I didn't have networking device to check this. If someone can test it I can appreciate @tarunkum

**Review by jukkar — CHANGES_REQUESTED** [review]
This is a sample application and not a unit test, thus ztest should not be used here.

**Comment by pfalcon** [comment]
So, if the idea is to fix a coverity issue, it should be done with just normal `if` + `printk`.

**Comment by punitvara** [comment]
ok thanks @pfalcon

**Comment by jukkar** [comment]
This was already fixed by another PR thus closing it.

**Pull request closed without merging**
