### PR TITLE
tests: mem_block: add a delay between test functions

### LINKED ISSUE #46925: Intel CAVS: tests/lib/mem_block/ failed, caused by too frequent log output.
**Describe the bug**
On Intel_adsp_cavs platform, `tests/lib/mem_block/` failed due to missing the early log like below:

We manually increase the `HP_SRAM_WIN3_SIZE` in `soc/xtensa/intel_adsp/common/include/cavs-mem.h:line#26` from `0x2000 `to `0x4000` can resolve this issue temporarily, but we are not sure if this new value is safe, need further reference to spec or other.

```
Prefixing /home/ztest/zephyrproject/zephyr/twister-out/intel_adsp_cavs18/tests/lib/mem_blocks/lib.mem_blocks/zephyr/zephyr.ri with manifest /home/ztest/zephyrproject/zephyr/twister-out/intel_adsp_cavs18/tests/lib/mem_blocks/lib.mem_blocks/zephyr/zephyr.ri.xman

DEBUG   - DEVICE: --
DEBUG   - DEVICE: 4  A3 0x9e01f560
DEBUG   - DEVICE: E:  **  A4 0x1  A5 0x60020  A6 0x9e01f628  A7 0x60c20
DEBUG   - DEVICE: E:  **  A8 0x1  A9 (nil) A10 0x1 A11 0x9e01f5dc
DEBUG   - DEVICE: E:  ** A12 0x9e01f000 A13 0x57 A14 0xbe01c07b A15 0x10
DEBUG   - DEVICE: E:  ** LBEG (nil) LEND (nil) LCOUNT (nil)
DEBUG   - DEVICE: E:  ** SAR 0x4
DEBUG   - DEVICE:
DEBUG   - DEVICE:
DEBUG   - DEVICE: Backtrace:0xBE0138EF:0xBE01C140 0xBE012E45:0xBE01C150 0xBE013402:0xBE01C170 0xBE010BD9:0xBE01C1A0 0xBE0144DA:0xBE01C1D0 0xBE011E4B:0xBE01C1F0
DEBUG   - DEVICE:
DEBUG   - DEVICE: E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
DEBUG   - DEVICE: E: Current thread: 0x9e01f000 (test_mem_block_invalid_params_p)
DEBUG   - DEVICE: Caught system error -- reason 4
DEBUG   - DEVICE: PASS - test_mem_block_invalid_params_panic_1 in 0.3 seconds
```
The log output after we changed HP_SRAM_WIN3_SIZE to 0x4000 is:
```
Prefixing /home/ztest/zephyrproject/zephyr/twister-out/intel_adsp_cavs18/tests/lib/mem_blocks/lib.mem_blocks/zephyr/zephyr.ri with manifest /home/ztest/zephyrproject/zephyr/twister-out/intel_adsp_cavs18/tests/lib/mem_blocks/lib.mem_blocks/zephyr/zephyr.ri.xman

DEBUG   - DEVICE: --
DEBUG   - DEVICE: ***** delaying boot 500ms (per build configuration) *****
DEBUG   - DEVICE: Running TESTSUITE lib_mem_block_test
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_mem_block_alloc_free
DEBUG   - DEVICE: PASS - test_mem_block_alloc_free in 0.1 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_mem_block_alloc_free_alt_buf

```
**To Reproduce**
1. `twister -W --hardware-map ~/cavs/cavs.map --device-testing -v  -T tests/lib/mem_blocks/ -vv -x=CONFIG_BOOT_DELAY=500`

**Expected behavior**
Test should pass.

**Environment (please complete the following information):**
 - OS: Linux
 - Commit b034711f595ec51f2055cc7a623d4668c116d169

### PR DESCRIPTION
**Pull request by ghost**
Currently, cavstool.py can not catch up with the log output flooding
into the winstream buffer. We have to add a delay between test functions
to catch the full log without missing anything.

Fixes: #46925 
Signed-off-by: Guo Lixin <lixinx.guo@intel.com>

### CODE REVIEW

**Comment by smrtos** [comment]
The CI failures seem irrelevant.

**Review by smrtos — DISMISSED** [review]

**Review by peter-mitsis — DISMISSED** [review]

**Comment by enjiamai** [comment]
Thanks, @LixinGuoX , it fixed the issues on CAVS boards. But I was thinking if we could apply this only for CAVS boards, and keep completed log for other boards?

**Review by smrtos — APPROVED** [review]

**Review by smrtos — DISMISSED** [review]

**Review by enjiamai — DISMISSED** [review]

**Review by nashif — CHANGES_REQUESTED** [review]
This is a workaround and is not fixing the problem and the issue linked, we can't go around changing tests to hide an issue .

**Comment by smrtos** [comment]
@nashif 

Some of my thoughts:

- The test point of this test case is not about the logging. We can tell that from the `asserts` in the code. So reducing logs won't cripple the test. 

- It's inherent in the design of winstream ring buffer to lose logs if the logging is too frequent. See https://github.com/zephyrproject-rtos/zephyr/issues/47833. 


So maybe it's OK to reduce the noise of excessive logs for this test.

**Comment by LixinGuoX** [comment]
Using a before function to add an extra delay(1 seconds) between test functions can help cavstool.py to catch the full log without missing anything.

**Comment by nashif** [comment]
> Some of my thoughts:
> 
> * The test point of this test case is not about the logging. We can tell that from the `asserts` in the code. So reducing logs won't cripple the test.

It is not, but we also do not want to start special casing platforms enabling something on one and disabling on the others. Logs are there for a reason, to see crashes in details and such. If a test is to be changed for this type of reasoning, it needs to be done globally and not for one platform.

> * It's inherent in the design of cavstool.py and winstream to lose logs if the fw logging is too frequent. See [Intel CAVS: cavstool.py fails to extract complete log from winstream buffer when logging is frequent #47833](https://github.com/zephyrproject-rtos/zephyr/issues/47833).

Right, we need to figure out an alternative way for capturing tests then.


> So maybe it's OK to reduce the noise of excessive logs just for this test.

My issue is that it does not end here, we have already modified a few tests this, what is the point of enabling logging if we have to disable it after that?

There are 2 ways out of this:

1. Alternative logging on this platform, maybe long term.
2. Better way for caputering results, you are already working on that.

**Comment by smrtos** [comment]
We just turned to use an extra delay as the before function. Rather than use `platform_exclude`.
This can give cavstool.py a chance to catch up. And also it can work on all platforms. 

We can continue work on the 2 ways out for long term.

Do you think it's sufficient to fix this test? @nashif

**Review by smrtos — APPROVED** [review]

**Comment by nashif** [comment]
closing this as we have a solution already.

**Pull request closed without merging**
