### PR TITLE
stm32wl55 configures the PLL with MSI as source

### LINKED ISSUE #43316: stm32wl55 cannot enable PLL source as MSI
**Describe the bug**
when configuring the PLL clock of  nucleo_wl55jc at 48MHz with MSI (4MHz) source. 

Define the dts clock source to be:
```
&clk_lse {
	status = "okay";
	clock-frequency = <32768>;
};

&clk_msi {
	status = "okay";
	msi-range = <6>; /* default value */
	msi-pll-mode;
};

&pll {
	div-m = <1>;
	mul-n = <24>;
	div-p = <2>;
	div-q = <2>;
	div-r = <2>;
	clocks = <&clk_msi>;
	status = "okay";
};

&rcc {
	clocks = <&pll>;
	clock-frequency = <DT_FREQ_M(48)>;
};
```

**To Reproduce**
 seePR https://github.com/zephyrproject-rtos/zephyr/pull/43157:
 ```
west build -p auto -b nucleo_wl55jc -- -DDTC_OVERLAY_FILE="boards/wl_clear_clocks.overlay;boards/wl_pll_48_msi_4.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/
``` 
--> no output on the console

**Expected behavior**
```
*** Booting Zephyr OS build zephyr-v3.0.0-490-g517cefeebcbc  ***
testing clock config on nucleo_wl55jc
Running test suite test_stm32_syclck_config
===================================================================
START - test_sysclk_freq
 PASS - test_sysclk_freq in 0.3 seconds
===================================================================
START - test_sysclk_src
 PASS - test_sysclk_src in 0.2 seconds
===================================================================
START - test_pll_src
 PASS - test_pll_src in 0.2 seconds
===================================================================
Test suite test_stm32_syclck_config succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Impact**
PLL source does not accept MSI clock as source

**Logs and console output**
```
testing clock config on nucleo_wl55jc
Running test suite test_stm32_syclck_config
===================================================================
START - test_sysclk_freq
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/clock_control/stm32_cl)
Expected sysclockfreq: 48000000. Actual sysclockfreq: 4000000
 FAIL - test_sysclk_freq in 0.3 seconds
===================================================================
START - test_sysclk_src
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/clock_control/stm32_cl)
Expected sysclk src: PLL. Actual sysclk src: 0
 FAIL - test_sysclk_src in 0.3 seconds
===================================================================
START - test_pll_src                                                            
PLL src is MSI                                                                  
 PASS - test_pll_src in 0.1 seconds                                             
===================================================================             
Test suite test_stm32_syclck_config failed.                                     
===================================================================             
PROJECT EXECUTION FAILED 
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

### PR DESCRIPTION
**Pull request by FRASTM**
Change the MSI range configuration when the PLL has MSI as source  for stm32wl soc
This is due to an erroneous pll freq calculation in the LL_PLL_ConfigSystemClock_MSI function from stm32Cube driver

Requires hal_stm32 PR https://github.com/zephyrproject-rtos/hal_stm32/pull/133

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/43316

Signed-off-by: Francois Ramu [francois.ramu@st.com](mailto:francois.ramu@st.com)

### CODE REVIEW

**Comment by FRASTM** [comment]
Based on the PR  https://github.com/zephyrproject-rtos/zephyr/pull/43157

$ west build -p auto -b nucleo_wl55jc -- -DDTC_OVERLAY_FILE="boards/wl_clear_clocks.overlay;boards/wl_pll_48_msi_16.overlay" tests/drivers/clock_control/stm32_clock_configuration/stm32_common/
can configure the sysclock with pll at 48MHz from MSI at 16MHz
where tests/drivers/clock_control/stm32_clock_configuration/stm32_common/boards/wl_pll_48_msi_16.overlay is:
```

&clk_msi {
	status = "okay";
	msi-range = <8>; /* 16MHz value */
};

&pll {
	div-m = <2>;
	mul-n = <12>;
	div-p = <2>;
	div-q = <2>;
	div-r = <2>;
	clocks = <&clk_msi>;
	status = "okay";
};

&rcc {
	clocks = <&pll>;
	clock-frequency = <DT_FREQ_M(48)>;
};
```

**Review by erwango — CHANGES_REQUESTED** [review]
Please remove commit `drivers: spi: stm32 spi with dma must enable cs after periph`

**Review by ABOSTM — DISMISSED** [review]

**Comment by erwango** [comment]
@FRASTM Please update west.yaml

**Comment by FRASTM** [comment]
update west.yml after merge of https://github.com/zephyrproject-rtos/hal_stm32/pull/133 & https://github.com/zephyrproject-rtos/hal_stm32/pull/134

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
