### PR TITLE
net: lib: http_server: fix snprintk issue of size_t

### PR DESCRIPTION
**Pull request by yangbolu1991**
Fixed snprintk issue of size_t.

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Could you add more information to commit message why this is an issue, for example what is the error message etc.

**Comment by yangbolu1991** [comment]
Updated to v2. Changes,
- Updated commit message per @jukkar comments.

Thanks a lot.

**Comment by yangbolu1991** [comment]
> Could you add more information to commit message why this is an issue, for example what is the error message etc.

Thanks. Updated.
size_t type varies from machines. So, size_t used in snprintk should be careful.

**Review by jukkar — APPROVED** [review]
Thanks, this is better now and easier to understand when reading the commit log in future.

**Review by rlubos — APPROVED** [review]

**Review by LaurentiuM1234 — APPROVED** [review]

**Pull request merged**
