### PR TITLE
Bluetooth: Mesh: Fix sequence number in Friend queue

### PR DESCRIPTION
**Pull request by jhedberg**
The code was updating net_rx->seq to make sure sdu_recv() gets the
right sequence number (seq_auth for segmented messages), however later
net_rx->seq was also used for enqueuing to the Friend Queue, causing
the queued messages to have the wrong value.

To fix this, don't update net_rx->seq, rather pass an explicit
sequence number value to sdu_recv(), which is just net_rx->seq for
unsegmented messages, and seq_auth for segmented messages.

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
@kkietava @petrip @rymanluk FYI

**Comment by jhedberg** [comment]
@MariuszSkamra we'd need to run the transport layer and Friendship (Friend role) PTS tests on this before merging.

**Comment by jhedberg** [comment]
@MariuszSkamra did you have a chance to run the Friendship tests on this?

**Comment by MariuszSkamra** [comment]
Sure, I'll run those tests tomorrow. We don't have Friend tests automated, and there are 20 test cases to run manually.

**Comment by jhedberg** [comment]
@MariuszSkamra one thing to note: when I was recently testing Friendship tests I noticed that the single transmission that the Friend does is not necessarily enough for the controller to send out a packet, especially when using an UART based controller. So if you use qemu, I recommend doing the following:

```
--- a/subsys/bluetooth/host/mesh/friend.c
+++ b/subsys/bluetooth/host/mesh/friend.c
@@ -40,7 +40,7 @@
 /* PDUs from Friend to the LPN should only be transmitted once with the
  * smallest possible interval (20ms).
  */
-#define FRIEND_XMIT_COUNT   0
+#define FRIEND_XMIT_COUNT   2
 #define FRIEND_XMIT_INT     20
 
 struct friend_pdu_info {
```

For testing LPN with UART HCI (e.g. qemu), you'll also want to fine-tune the HCI latency: `CONFIG_BT_MESH_LPN_SCAN_LATENCY=50`

**Comment by jhedberg** [comment]
@Vudentz @sjanc @carlescufi for the record, I tested this change against SiLabs, and it made the Friend tests pass which were previously failing, so I'd appreciate a review so we can get this merged.

**Review by carlescufi — APPROVED** [review]
No objections from my limited understanding. Sorry for the delay, was on holiday and now travelling.

**Pull request merged**
