### PR TITLE
arch: kconfig: Set flash size/address to 0 by default when !XIP

### PR DESCRIPTION
**Pull request by gramsay0**
Many boards/SoCs in-tree do this:
```
if !XIP
config FLASH_SIZE
    default 0
config FLASH_BASE_ADDRESS
    default 0
endif
```
And many other boards are missing this configuration (e.g. stm32 series).
Making this the default helps get non-XIP just working

ref: #72307

### CODE REVIEW

**Comment by dcpleung** [comment]
What are the failures? If there is no flash, there is no need to specify these kconfigs. Some flash do have address starting at 0x00000000 so it should not be considered an invalid config.

**Comment by gramsay0** [comment]
> What are the failures? If there is no flash, there is no need to specify these kconfigs. Some flash do have address starting at 0x00000000 so it should not be considered an invalid config.

The failure outputs an obscure error message e.g:
```
west build -b nucleo_f756zg zephyr/samples/hello_world -DCONFIG_XIP=n
...
/tmp/cc2CISlB.s: Assembler messages:
/tmp/cc2CISlB.s:49: Error: missing expression
/tmp/cc2CISlB.s:55: Error: missing expression
```
as these configs exist with no value.

These configs are used in common C files and linker scripts, so they need to be defined e.g:
```
#if !defined(CONFIG_XIP) && (CONFIG_FLASH_SIZE == 0)
#define ROM_ADDR RAM_ADDR
#else
```

**Review by erwango — DISMISSED** [review]

**Comment by erwango** [comment]
@gramsay0 Would you mind adding the related clean-up from boards/socs configurations ?

**Comment by dcpleung** [comment]
In that case, maybe just make flash size default to 0, and leave the address untouched?

**Comment by gramsay0** [comment]
> In that case, maybe just make flash size default to 0, and leave the address untouched?

Integer configs need a value, otherwise you get an error during prebuild.

We could make `config FLASH_BASE_ADDRESS` `depends on FLASH_SIZE > 0`, although that would require a larger refactor (there is ~120 uses of `FLASH_BASE_ADDRESS` in-tree) and likely break some out-of-tree apps/boards

**Review by erwango — APPROVED** [review]

**Review by vaishnavachath — APPROVED** [review]

**Pull request merged**
