### PR TITLE
tests: Bluetooth: Convert PTS files to CRLF

### PR DESCRIPTION
**Pull request by Thalley**
Modify all the PTS files to be CRLF, as PTS and the
qualification tool expects these files to be CRLF.

Also adds a .editorconfig file to provide help for editors.

Ideally we would do something like `*.pts text eol=crlf`
in a .gitattributes file, but Github doesn't know how
to treat those properly, and won't convert files downloaded
from github.com.

### CODE REVIEW

**Comment by Thalley** [comment]
The github issues:
https://github.com/orgs/community/discussions/76759
https://github.com/orgs/community/discussions/112294

**Review by theob-pro — DISMISSED** [review]

**Comment by kartben** [comment]
> Ideally we would do something like *.pts text eol=crlf
in a .gitattributes file, but Github doesn't know how
to treat those properly, and won't convert files downloaded
from github.com.

But it would probably be good to add the entry in the `.gitattributes` file nevertheless, no? This sounds more "standard" than a `.editorconfig` file?

**Review by thoh-ot — DISMISSED** [review]

**Comment by Thalley** [comment]
> > Ideally we would do something like *.pts text eol=crlf
> > in a .gitattributes file, but Github doesn't know how
> > to treat those properly, and won't convert files downloaded
> > from github.com.
> 
> But it would probably be good to add the entry in the `.gitattributes` file nevertheless, no? This sounds more "standard" than a `.editorconfig` file?

I tried that, but once you do that, you are no longer able to control the line endings manually, and git reverted all the files back to LF, which unfortunately means that they cannot be downloaded without git as CRLF (e.g. with wget or direct download from the GH webui). 

Spent a good few hours trying to make `.gitattributes` work, but due to the mentioned GH bugs it cannot be done (or at least I was not capable of doing that).

**Comment by Thalley** [comment]
We can ignore the failing compliance checks; they never pass for these files (I wonder if we can somehow exclude them or otherwise add special rules for these files?)

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Added an additional commit that adds final newlines to the files as well. Tested to work with the qualification tool and @theob-pro tested it with the PTS software as well

**Review by theob-pro — APPROVED** [review]

**Comment by Thalley** [comment]
Have been running compliance checks locally for 2 hours without finishing. I think there is a bug somewhere in the python script, as running the perl script finishes in a few seconds. 

Compliance will however fail due to `ERROR:DOS_LINE_ENDINGS: DOS line endings`

**Review by jhedberg — APPROVED** [review]

**Comment by sjanc** [comment]
just a note that bls files are now useless (Launchstudio is down and new Qualification Workspace allows only .pts import/export)

**Comment by Thalley** [comment]
> just a note that bls files are now useless (Launchstudio is down and new Qualification Workspace allows only .pts import/export)

Oh, so we should probably just removed those :)

**Comment by sjanc** [comment]
yes, I'd just remove those,  after that I'll rebase my PR with update .pts files based on feedback I received

**Comment by Thalley** [comment]
> yes, I'd just remove those, after that I'll rebase my PR with update .pts files based on feedback I received

Sure we can do that, instead of this PR. Can you add the .editorconfig file as well?

**Comment by sjanc** [comment]
yeap, I'll add .editorconfig

**Review by kruithofa — APPROVED** [review]

**Comment by Thalley** [comment]
Closing as this is now a duplicate of https://github.com/zephyrproject-rtos/zephyr/pull/75809

**Pull request closed without merging**
