### PR TITLE
STM32 ADC asynchronous clock check

### PR DESCRIPTION
**Pull request by gautierg-st**
This PR stems from #78047.

Some STM32 ADC can be configured to use either a synchronous or an asynchronous clock by using the `st,adc-clock-source` property. In case of asynchronous clock, the specific domain clock is specified in the `clock` property.
Until now, asynchronous clock mode could be selected without explicitly setting the domain clock. To avoid implicit configuration, this PR enforces that the domain clock is specified if asynchronous mode is used.

This PR adds a check in the ADC driver, and a domain clock is specified for all ST boards that currently have an active ADC in asynchronous clock mode.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
IIUC, this is a breaking change for existing ASYNC users which relied on implicit domain clock configuration.

Please update adc dt binding to document properly this new constraint and update v4.0 migration guide.

Otherwise LGTM

**Review by erwango — DISMISSED** [review]

**Review by marwaiehm-st — DISMISSED** [review]

**Comment by erwango** [comment]
@gautierg-st Rebase required

**Comment by gautierg-st** [comment]
> @gautierg-st Rebase required

Done

**Review by erwango — APPROVED** [review]

**Review by marwaiehm-st — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Comment by srvanloon-priv** [comment]
@gautierg-st @erwango I think this is ready for merge ? If so then I can rebase my original patch on top to get that in as well :)

**Comment by bas-archembedded** [comment]
@gautierg-st @erwango I think this is ready for merge ? If so then I can rebase my original patch on top to get that in as well :)

**Comment by gautierg-st** [comment]
Yes, it is ready, hopefully will be merged soon :)

**Comment by erwango** [comment]
@nordic-krch Would you mind having a look ?

**Pull request merged**
