### PR TITLE
Add RPMsg-Lite 2.2.0 into Zephyr

### PR DESCRIPTION
**Pull request by stanislav-poboril**
Adds RPMsg-Lite 2.2.0 library support and a sample application into Zephyr on NXP LPC54114 SoC/board. It can work also on i.MX 6SoloX and i.MX7 SoCs' M4 cores, but it will require a separate sample application as the other core is running usually Linux there. Perhaps we can base the sample on @diegosueiro's Remote Echo sample application [here](https://github.com/diegosueiro/zephyr/commit/70dda5ec5d1768dc21ec4f348bd6e26eb8821a5d).

Based on #5960 which was rejected in past due to RPMsg-Lite having the Clear-BSD license. As per @MarekNovakNXP's discussion with @nashif and @carlescufi at Embedded World conference, it has been agreed to put this into Zephyr now that the license is back to BSD-3-Clause.

To be merged only after 1.14 is released.

### CODE REVIEW

**Comment by galak** [comment]
> Based on #5960 which was rejected in past due to RPMsg-Lite having the Clear-BSD license. As per @MarekNovakNXP's discussion with @nashif and @carlescufi at Embedded World conference, it has been agreed to put this into Zephyr now that the license is back to BSD-3-Clause.

This needs to be raised at the TSC again for discussion.

**Review by dbkinder — APPROVED** [review]
doc LGTM.

**Comment by sigvartmh** [comment]
Anything happening here or has it been decided that this should not go into Zephyr due to licensing issues?

**Comment by PetrLukasNXP** [comment]
We are still supporting adding RPMsg-Lite to Zephyr. License wise we are BSD, so I hope there should be no license issues.

Adding @Maureen Helm<mailto:maureen.helm@nxp.com> and @Michal Princ<mailto:michal.princ@nxp.com>.

Petr

**Comment by sigvartmh** [comment]
@carlescufi What was the resolution of the meeting in the TSC?

**Comment by carlescufi** [comment]
@galak this PR was recently raised to me by devs working on a project. Does it make sense to continue to pursue this and have both OpenAMP and RPMsg-Lite as part of Zephyr? Should this be discussed in the TSC or dev-review context?

**Comment by PetrLukasNXP** [comment]
All NXP Heterogenous Multicore platforms are based on RPMSG-Lite. It would be good to have it as a part of Zephyr.

**Comment by sigvartmh** [comment]
@galak Ping

**Comment by nashif** [comment]
@carlescufi  I do not see why this can't be pushed as a west module given that we have users. AFAIK this does not touch any core Zephyr functionality anyways.

**Comment by carlescufi** [comment]
> @carlescufi I do not see why this can't be pushed as a west module given that we have users. AFAIK this does not touch any core Zephyr functionality anyways.

I agree, I personally have no objections to having this as a module, but @galak needs to weigh in. I will add a dev-review tag. cc @MaureenHelm

**Review by carlescufi — CHANGES_REQUESTED** [review]
This should be a module

**Comment by pabigot** [comment]
I agree that if added to zephyr this should be a module.

**Pull request closed without merging**
