### PR TITLE
Minor cavstool fixes

### PR DESCRIPTION
**Pull request by marc-hb**
3 commits.

[lib/os: clarify that the winstream object does not track reads](https://github.com/zephyrproject-rtos/zephyr/pull/42718/commits/d304dc1c5770b776af171867519e091a5b373014) 
[d304dc1](https://github.com/zephyrproject-rtos/zephyr/pull/42718/commits/d304dc1c5770b776af171867519e091a5b373014)
Clarify that the reader MUST track the last sequence number read and
that the 'start' offset is not involved in that.
Some pre-conceptions + the sentence "the current state of the stream"
threw me off for a while. Thanks Andy for explaining this to me.

[soc/intel_adsp: cavstool: log out of bounds mmap offsets](https://github.com/zephyrproject-rtos/zephyr/pull/42718/commits/bbe5eb02272c0b8513b0664ac4194889cf2b2729) 
[bbe5eb0](https://github.com/zephyrproject-rtos/zephyr/pull/42718/commits/bbe5eb02272c0b8513b0664ac4194889cf2b2729)
The winstream can become corrupted when the firmware hasn't booted or is
in the bad state.

[soc/intel_adsp: cavstool: poll FW_STATUS even when --log-only](https://github.com/zephyrproject-rtos/zephyr/pull/42718/commits/c35de52b2c3058ad0fe028e0c30f748e4a4d364f) 
[c35de52](https://github.com/zephyrproject-rtos/zephyr/pull/42718/commits/c35de52b2c3058ad0fe028e0c30f748e4a4d364f)
Failures to boot are not exclusive to the cavstool.py, they can happen
with the kernel driver and --log-only too. For such a situation this
commit adds a useful delay and these two log lines (before the mmap
crashes eventually):
```
 INFO:cavs-fw:Waiting for firmware handoff, FW_STATUS = 0x81000012
 WARNING:cavs-fw:Load failed?  FW_STATUS = 0x1006701
```

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Looks great to me

**Review by dcpleung — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by nashif** [comment]
image

redundant information :)

Please add a detailed summary of what this PR does...

**Comment by marc-hb** [comment]
I simply copied the 3 commit messages to the PR description. They are all small fixes in the same area but they are not related enough to each other for a combined "cover letter".

Github is designed to review a single commit per PR + fixup commits. So in theory I should have submitted 3 different PRs here (I typically do this) but that seemed like a lot of overhead for so little code, not just for me but for the reviewers as well.

It's also common that people copy/paste/diverge commit messages to the PR description, then change them significantly and force push and forget to update the stale PR description. I've been confused a number of times by this. Github does not let you comment on or compare the actual commit messages. It's simply not designed for the "rewrite history and force-push" workflow: #39194

**Comment by nashif** [comment]
> Github is designed to review a single commit per PR + fixup commits.

where are you getting this from? Is this some documented design principle or is this your own view of how GH should work?

**Comment by marc-hb** [comment]
> > Github is designed to review a single commit per PR + fixup commits.

> where are you getting this from? Is this some documented design principle or is this your own view of how GH should work?

It started when people showed me how other projects use Github. Then I found a fairly long list of glitches, annoyances and missing features that all instantly go away the moment you switch to the "fixup" review flow:
- https://github.com/zephyrproject-rtos/zephyr/pull/14444#issuecomment-575320941

Then more people concurred: https://github.com/isaacs/github/issues/959#issuecomment-592978474

More recently,  a list of yet other people (Zephyr users) who want to review multiple commits and rewrite history are looking at alternatives to Github:
- #39194

I think Github documentation does not clearly state this to avoid putting off some customers but the cumulative evidence  clearly shows what the preferred review model is.

**Pull request merged**
