### PR TITLE
nxp: imx8ulp: enable serial interface

### PR DESCRIPTION
**Pull request by LaurentiuM1234**

### CODE REVIEW

**Review by iuliana-prodan — DISMISSED** [review]

**Review by decsny — CHANGES_REQUESTED** [review]
the west.yml change should not be a separate commit

**Comment by LaurentiuM1234** [comment]
> the west.yml change should not be a separate commit

What's the rationale for that? Current layout doesn't break git bisect as far as 8ULP is concerned.

**Comment by LaurentiuM1234** [comment]
**V2 changes**

1. Dependency merged. Updated hal_nxp SHA
2. Squashed manifest update with the commit that enables the serial interface.

**Review by dcpleung — DISMISSED** [review]

**Review by iuliana-prodan — DISMISSED** [review]

**Review by JiafeiPan — DISMISSED** [review]

**Review by mmahadevan108 — CHANGES_REQUESTED** [review]
Wait for https://github.com/zephyrproject-rtos/zephyr/pull/71173 before merging this one.

**Comment by LaurentiuM1234** [comment]
Rebased. https://github.com/zephyrproject-rtos/zephyr/pull/71173 has been merged.

**Review by dbaluta — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@decsny, please review again.

**Review by dcpleung — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by nordic-segl — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Pull request merged**
