### PR TITLE
[Backport v2.7-branch] board: nucleo_h745zi_q: enable POWER_SUPPLY_DIRECT_SMPS

### PR DESCRIPTION
**Pull request by zephyrbot**
Backport 98acf68d41393a470cd2efebc5861686bbad63d9 from #41087

### CODE REVIEW

**Review by FRASTM — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Requires https://github.com/zephyrproject-rtos/zephyr/pull/41437 to be merged first.
Blocking until it is done

**Comment by erwango** [comment]
@cfriedt This PR requires https://github.com/zephyrproject-rtos/zephyr/pull/41437 and it was created before it is merged on v2.7 branch. This is why CI is failing.
https://github.com/zephyrproject-rtos/zephyr/pull/41437 is now merged (but, do to lack of rebase, ci is still failed.
How should we proceed ?

**Comment by cfriedt** [comment]
> @cfriedt This PR requires #41437 and it was created before it is merged on v2.7 branch. This is why CI is failing. #41437 is now merged (but, do to lack of rebase, ci is still failed. How should we proceed ?

I lack superpowers to force-push to this branch, so please close this PR and open a new one. Sorry :(

**Comment by erwango** [comment]
@cfriedt replaced by https://github.com/zephyrproject-rtos/zephyr/pull/41717

**Pull request closed without merging**
