### PR TITLE
Bluetooth: hci_usb: Simplify write function

### PR DESCRIPTION
**Pull request by finikorg**
Simplify write function using net_buf primitives.

Signed-off-by: Andrei Emeltchenko <andrei.emeltchenko@intel.com>

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]
LGTM

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks good, but could you please fix the commit message to make it clear what exactly this is about. Simply changing the summary to "Bluetooth: hci_usb: Simplify write function" should do it. Now when I saw the PR for the first time I thought it was related to some stack-internal write function, when in fact this is only about a specific sample app (hci_usb)

**Comment by jhedberg** [comment]
Oh, hold on. The actual commit message has a different summary than the PR (how did that happen?). Still, I'd add a Bluetooth prefix to it.

**Comment by finikorg** [comment]
updated prefixes

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
