### PR TITLE
bluetooth: gatt: remove operation infix from authorization callback API

### PR DESCRIPTION
**Pull request by kapi-no**
Related to: https://github.com/zephyrproject-rtos/zephyr/pull/67615

This PR attempts to address the following suggestion:

https://github.com/zephyrproject-rtos/zephyr/pull/67615#discussion_r1459250604

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by kapi-no** [comment]
Hmmm, the `samples/bluetooth/unicast_audio_client/sample.bluetooth.audio_unicast_client` keeps failing for me within the "Build with Clang/LLVM" job. Any idea how to work around this issue?

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
> Hmmm, the `samples/bluetooth/unicast_audio_client/sample.bluetooth.audio_unicast_client` keeps failing for me within the "Build with Clang/LLVM" job. Any idea how to work around this issue?

Seems like #68255 might fix it. I just triggered a CI rerun.

**Review by jori-nordic — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@jori-nordic is this a fix or can it be pushed to 3.7?

**Comment by jhedberg** [comment]
> @jori-nordic is this a fix or can it be pushed to 3.7?

@fabiobaltieri I think this would be good to get in. This is a new API that was introduced for 3.6, and if we release in its current form we'd have to go through the formal change process in order to merge this PR post-3.6.

**Pull request merged**
