### PR TITLE
Fix CONFIG_MULTITHREADING=n

### PR DESCRIPTION
**Pull request by andyross**
We never had a test for this (admittedly somewhat obscure) feature, and I broke it when mucking with the scheduler.  Fix bug, add test.

Note that while this restores proper behavior, it doesn't try to check for a "lean" implementation.  I definitely see some junk in the link that probably shouldn't be there, and I'm sure that we've probably balooned the size of these binaries in 1.12.  Needs attention.

### CODE REVIEW

**Comment by nashif** [comment]
> We never had a test for this (admittedly somewhat obscure) feature,

actually we did and we had a bug related to this as well. The test was disabled due to the bug #5733, the test was in the hello world sample which is disabled when ASSERTS are on.

**Comment by andyross** [comment]
Hah, so maybe it wasn't me that broke it. :)   Though the scheduler work probably did make the size worse at least.

Should I remove the test patch from the PR then or leave this one in place?

**Review by tyrantlizard77 — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
This fixes the assert we were seeing. Thank you!

**Comment by nashif** [comment]
> Should I remove the test patch from the PR then or leave this one in place?

I would instead remove the hello world one, just in case we want to test other things in single thread mode.

**Pull request merged**
