### PR TITLE
drivers: modem: bg9x: Prevent compiling unused configs

### LINKED ISSUE #38535: drivers: modem: bg9x: Kconfig values compiled into `autoconf.h` even if it isn't being used
**Describe the bug**
The bg9x modem's [Kconfig](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/modem/Kconfig.quectel-bg9x) is lacking the `if MODEM_QUECTEL_BG9X` `endif` guard to prevent its default values from being compiled into the `autoconf.h`

**To Reproduce**
1. Build anything
2. Check the `autoconf.h` for bg9x related configs

**Expected behavior**
Kconfig default values should be compiled only when its source is being used.

**Impact**
`autoconf.h` pollution.

### PR DESCRIPTION
**Pull request by ycsin**
Currently the default Kconfig values from bg9x modem are being mistakenly compiled into the `autoconf.h` due to a missing `if` guard in the `Kconfig.quectel-bg9x`. This pr patches that.

Fixes #38535

### CODE REVIEW

**Comment by ycsin** [comment]
Im getting BG9X related configs in my `autoconf.h`

**Comment by ycsin** [comment]
@cfriedt @bwasim

**Comment by cfriedt** [comment]
@ycsin - can you please create an issue for this PR? The sooner the better, as the release team is triaging issues today.

**Comment by ycsin** [comment]
> @ycsin - can you please create an issue for this PR? The sooner the better, as the release team is triaging issues today.

Done, sorry for the delay!

**Review by galak — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]

**Pull request merged**
