### PR TITLE
drivers: flash: Add MAX32xxx flash driver

### PR DESCRIPTION
**Pull request by mertvatansever**
This PR adds flash driver for ADI MAX32xxx series microcontrollers. Test overlays for "flash/common" are provided for each board.

### CODE REVIEW

**Comment by ttmut** [comment]
You could combine commits from same author into a single one.

Also needs a rebase.

**Comment by mertvatansever** [comment]
> Needs rebase.

Done

**Comment by mertvatansever** [comment]
> You could combine commits from same author into a single one.

Done

**Review by MaureenHelm — APPROVED** [review]

**Review by ozersa — APPROVED** [review]

**Review by ttmut — APPROVED** [review]

**Review by de-nordic — CHANGES_REQUESTED** [review]
The driver completely lacks checks for offset/size ranges. Is that ok with the driver and these happen in MXC_FLC_ calls?

**Review by de-nordic — APPROVED** [review]

**Comment by de-nordic** [comment]
> > The driver completely lacks checks for offset/size ranges. Is that ok with the driver and these happen in MXC_FLC_ calls?
> 
> These are being checked in MXC_FLC_ calls.

Thanks!

**Pull request merged**
