### PR TITLE
tests: subsys: nvs testing on stm32 boards

### PR DESCRIPTION
**Pull request by FRASTM**
Add configuration to run the  
- tests/subsys/settings/nvs/
- samples/subsys/nvs/

on more stm32 platforms: 
-   nucleo_f746zg
-   nucleo_f207zg
-   nucleo_h743zi

Signed-off-by: Francois Ramu [francois.ramu@st.com](mailto:francois.ramu@st.com)

### CODE REVIEW

**Comment by Laczen** [comment]
@FRASTM, please note:
a. A nvs sector cannot be larger than 64kB,
b. At least two sectors are required.

**Comment by Laczen** [comment]
@FRASTM, the limit to 64kB is internal in nvs, just a change in the include file will not work.

**Comment by Laczen** [comment]
> @FRASTM, the limit to 64kB is internal in nvs, just a change in the include file will not work.

The only way nvs can be used on devices with 'heterogeneous' block sizes is by using the small blocks at the start or at the start of the second block. Using them at the start will make it difficult (if not impossible) to use it with mcuboot. This is a limiting factor for these devices.

**Comment by Laczen** [comment]
> @Laczen thanks to the explanation ; lLimiting to the nucleo_f207 for reason detailed above Rebase on [4fa2f6f](https://github.com/zephyrproject-rtos/zephyr/commit/4fa2f6fdb29b2173c94fc3c9e4485e83817bffa8) after merge of #50979 that fixes CI issue

On the nucleo_f207 this will also not work, there is only one sector reserved and this sector is 128kB.

PS: I have recently released a new storage solution (https://github.com/Laczen/kvs) that would allow configuring for the stm32 devices with heterogeneous blocks sizes (e.g. combine one 16kB sector with the 64kB sector, or use 2 128kB sectors). I am still improving this solution.

**Comment by FRASTM** [comment]
This PR would be reserved for future use after @Laczen 's solution is ready

**Pull request closed without merging**
