### PR TITLE
hda_log: Bug fixes and improvements

### LINKED ISSUE #59060: tests/boards/intel_adsp/hda_log fails on intel_adsp_cavs25
**Describe the bug**
Various tests in `tests/boards/intel_adsp/hda_log` are failing when run on intel_adsp_cavs25 with no output on the screen

**To Reproduce**

`/scripts/twister -p intel_adsp_cavs25 --device-testing --hardware-map ~/map.yaml -T tests/boards/intel_adsp/hda_log`

**Expected behavior**
test should pass

The issue was introduced with 7d54586751cfe405d2cdcfd850f8100bc9844f63, which looks very related.

### PR DESCRIPTION
**Pull request by teburd**
Resurrection of a PR from the past to fix HDA log

Fixes #59060 along with other likely issues in terms of panic mode and immediate mode logging

### CODE REVIEW

**Review by tmleman — DISMISSED** [review]

**Comment by teburd** [comment]
Rebased

**Comment by teburd** [comment]
The output is still mangled and its unclear to me as to why at the moment

**Comment by nashif** [comment]
can you please rebase and push again?

**Comment by MaureenHelm** [comment]
> can you please rebase and push again?

@teburd ping

**Comment by MaureenHelm** [comment]
@teburd do you plan to continue with this PR?

**Comment by teburd** [comment]
Converted to draft as I haven't spent the time needed to finish this. HDA log is fixed but it broke other things (smoke testing, etc).

**Pull request closed without merging**
