### PR TITLE
tests/kernel/schedule_api: Fix slop in timeslice test

### PR DESCRIPTION
**Pull request by andyross**
[This is some work-in-progress on this somewhat odd test case that is giving us trouble on one hardware platform.  It acts to tighten the slop due to platform and timing differences.  Note that it doesn't pass on qemu_cortex_r5 right now, so this isn't ready for merge.  But it may be worth playing with.]

This test is a little subtle: it wants to spawn three threads to run
and be switched out by a timeslice interrupt.  And it wants to consume
half a time slice itself before it starts running.  And, because
timeslicing runs out of the same tick framework in the timer driver,
it needs to align to the start of a tick before the process starts.
And further: it does its own time math not in ticks but in timer
cycles, so it's quite sensitive to slop.

But it's "synchronize to tick boundary" code was actually
synchronizing to a CYCLE boundary, which is just wrong.  And it was
doing this in the wrong order.  It was resetting the timeslice first
and then synchronizing to a tick by spinning, which means that the
test was always going to begin as much as a tick late.  Do the tick
synchronization (via a sleep) first.

Finally, the manager thread that was spawning the new threads lives at
the same priority as the highest priority child threads, which means
it can potentitially wake up on the semaphores that they are giving in
the middle of the test and consume CPU unexpectedly.  Make sure it's
sleeping for the duration.

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by andyross** [comment]
@jenmwms @aasthagr You might want to try this on hardware.  There are definitely some holes in the way the test was doing its accounting that this should tighten up a bit.  But as mentioned it too has exposed some weirdness on one of the virtual platforms (qemu_cortex_r5 is an icount/deterministic device with 1000 Hz ticks, so it should be reasonably robust and it's possible it's showing a variant of the same issue you're seeing -- I'm still looking).

**Review by tyrantlizard77 — APPROVED** [review]
subtle stuff. the change looks fine, although I'm not sure I completely understand why we sync to tick boundary before we make the k_thread_create() calls, thread creation is a bit heavyweight so would it be better to do afterwards just so that the thread creation tasks dont themselves mess up timing.

maybe pass K_FOREVER to k_thread_create(), sync to tick, and then loop again calling k_thread_start on all of them?

**Comment by andyross** [comment]
If you do the tick sync with a sleep after creating the threads, then those threads will start running too early.  The test depends on the main thread not yielding until it's eaten half a timeslice.  Which begs the question of "Why is the main thread at a preemptible priority in the first place!?" (note that it's explicit: the test actually SETS that priority on the current thread).    And I don't have an answer.  It's... a weird test case.  Not the only one, to be fair.

**Comment by andrewboie** [comment]
> If you do the tick sync with a sleep after creating the threads, then those threads will start running too early.

Yeah, that's the reason I suggested perhaps passing K_FOREVER to k_thread_create() and then starting them later. Just in case the thread creation itself causes overhead which could affect the test. I don't  know if this is much of a concern it was just a thought.

**Comment by andyross** [comment]
I think if I were to rewrite this, I'd set up the manager thread at a higher cooperative priority to ensure nothing preempted it (this test runs with MP_NUM_CPUS=1, so it's not subject to SMP dispatch) then seed the timestamp immediately before entering that half-slice spin loop, then finally doing a sleep.

Or just drop the half-slice thing.  I don't understand what it's trying to test, at the point the master thread yields there isn't anything else to run, of course the next thread is going to run synchronously.

But that's a lot of logic change, and "rewrite the test while chasing a failure" is kinda bad practice.

**Comment by andyross** [comment]
Just to note: the qemu_cortex_r5 root cause that is preventing this from merging is tracked in #29298

**Comment by andyross** [comment]
Rebase, add a patch to qemu_cortex_r5 that addresses the root cause on that platform: the driver bug was real, but it was actually acting to SUPPRESS failures by ignoring tick loss.  The real issue that got exposed here was that the platform is just really, really slow as configured and was falling behind on CPU trying to meet its 1000 Hz tick rate with a 12 MHz virtual clock.  See comments in the patch.

@jenmwms @aasthagr This should be good to merge upstream now if you want to try it on the hardware.

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
