### PR TITLE
 lib: cbprintf: fix ubsan errors in cbvprintf_package (take 2)

### PR DESCRIPTION
**Pull request by nordic-krch**
As #77963 had to be reverted this is a second approach.

To be checked if that fixes ubsan errors.

### CODE REVIEW

**Comment by nordic-krch** [comment]
@cujomalainey as your PR had to be reverted I tried another approach but I don't know how to verify if that fixes ubsan errors (however, i don't do pointer arithmetic anymore). Can you check?

**Review by cujomalainey — APPROVED** [review]
Clever thinking, yep that satisfies UBSAN. Thanks!

Also I finally figured out hot run the format on the patch directly if you want to satisfy the checks. `git clang-format HEAD~1`

**Review by cujomalainey — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]
Thanks for the second attempt!

**Comment by nordic-krch** [comment]
@dcpleung @mmahadevan108 can you take a look?

**Review by dcpleung — APPROVED** [review]

**Pull request merged**
