### PR TITLE
shell: support setting help string for each entry in a dictionary command

### PR DESCRIPTION
**Pull request by xinyangt9**
Add support for setting the help description for each entry in a dictionary
command. Currently the syntax string alone may not provide sufficient
description of its entry. This commit also helps keep the help messages
consistent with existing style.

Signed-off-by: Xinyang Tan <xinyang.tan@delve.com>

### CODE REVIEW

**Review by Domino-Jachas — DISMISSED** [review]

**Review by jakub-uC — CHANGES_REQUESTED** [review]
Nice improvement, please update shell tests as well:
`tests/subsys/shell/shell/src/main.c`

**Review by jakub-uC — DISMISSED** [review]

**Comment by jakub-uC** [comment]
@jasonxytan: Did you try to rebase your PR? I am able to build some of these failing tests on the `main` branch.

**Comment by jasonxytan** [comment]
> @jasonxytan: Did you try to rebase your PR? I am able to build some of these failing tests on the `main` branch.

Didn't work. I'll look into it later.

**Comment by carlescufi** [comment]
@jasonxytan sorry for the delay, Please rebase this PR so that we get rid of the merge commit.

**Review by jakub-uC — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
