### PR TITLE
Bluetooth: Host: Send status for terminated directed adv

### LINKED ISSUE #68681: Bluetooth: host: BT_HCI_ERR_ADV_TIMEOUT is not sent to connected_cb() for directed advertisments
**Describe the bug**
The BT_HCI_ERR_ADV_TIMEOUT is not correctly sent to the connected_cb in the case of directed advertisements started through the ext_adv_start function. 

**Expected behavior**
When starting a directed advertiser with timeout equal to BT_GAP_ADV_HIGH_DUTY_CYCLE_MAX_TIMEOUT or less, I expect to get a connected_cb with err==BT_HCI_ERR_ADV_TIMEOUT if no connection has been made in time. This timeout can then be used to start a slower advertising cycle.

**Impact**
Showstopper: Makes it impossible to know if the directed advertiser has timed out or not.

### PR DESCRIPTION
**Pull request by alexsven**
- Fix bug where status was only sent for legacy adv
- Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/68681

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
This change is fine, as otherwise the `status` field is never used.

**Comment by alexsven** [comment]
Fixes: #68681

**Comment by Thalley** [comment]
@jori-nordic I was wondering if the remainder of the comment with directed advertising should also be removed, because the behavior of `le_adv_stop_free_conn` seems to be the same for both directed and undirected advertising. 

To see if that was intentional, I checked how the `conn` object was allocated in `bt_le_adv_start_ext`, and that also looks weird to me. 

We have something like 
```c
	if (IS_ENABLED(CONFIG_BT_PERIPHERAL) && conn) {
		/* If undirected connectable advertiser we have created a
		 * connection object that we don't yet give to the application.
		 * Since we don't give the application a reference to manage in
		 * this case, we need to release this reference here
		 */
		bt_conn_unref(conn);
	}
```

But we create/allocate the connection object regardless of whether it is directed advertising, and in fact we have the following right above

```c
	err = bt_le_adv_set_enable_ext(adv, true, &start_param);
	if (err) {
		LOG_ERR("Failed to start advertiser");
		if (IS_ENABLED(CONFIG_BT_PERIPHERAL) && conn) {
			bt_conn_set_state(conn, BT_CONN_DISCONNECTED);
			bt_conn_unref(conn);
		}

		return err;
	}
```

Where there is no distinction between directed and undirected advertising. 

I fear that we may have other places where such comments may exist (regarding directed advertising) that are no longer true, and it's unclear to me whether the code should be changed to accommodate the comment, or if the comments should be removed.

**Comment by jori-nordic** [comment]
From a first look at that fn, I don't see directed adv being treated differently re:refs. I think we should just strike `undirected` from the comment.

**Review by jori-nordic — APPROVED** [review]

**Pull request merged**
