### PR TITLE
Stm spi clocks

### PR DESCRIPTION
**Pull request by KimBP**
It seems like SPI5 has never been used on stm32f411/412.
The clock was missing. Took a while to realize the problem was a missing clock, because SPI5 was configured like SPI4 in stm32f411.dtsi.
The reason though why spi4 might work (haven't used it my self) is that it is already fully defined in stm32f401.dtsi.

With this PR the duplicate spi4 attributes are removed and spi5 clock attribute is added

### CODE REVIEW

**Review by erwango — APPROVED** [review]
Thanks for this fix

**Review by FRASTM — COMMENTED** [review]
Should the same clock Enable for the SPI5 be included also  for the **stm32f410**.dtsi
rmk: this was correctly done for the I2S 4 and I2S 5

**Comment by KimBP** [comment]
Yeah it seems to be missing there too - but the stm32f410.dtsi seems to have another include hirarchy so don't know if somehow it can be set somewhere else.
Looking into the reference manual for stm32f410 I see it supports spi1, spi2 and spi5. 
I will add the missing clock to stm32f410.dtsi too

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by FRASTM — APPROVED** [review]

**Pull request merged**
