### PR TITLE
Bluetooth: HCI: Add function to get connection handle of connection

### PR DESCRIPTION
**Pull request by joerchan**
Add public API function to get the connection handle of the connection.
The connection handle is needed by applications that intend to send
vendor specific commands for a given connection.

In order to use the conn.h header file in hci.h I had to remove the dependency in conn.h on hci.h to avoid a circular dependency.
 - Extracted GAP and Device Address defines out from hci.h
 - Added non-HCI scan types to bluetooth.h (with same values)
 - Extracted hci error codes to its own header file so that conn.h can include hci_err.h instead.

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]
LGTM

**Review by jhedberg — DISMISSED** [review]

**Review by mtpr-ot — DISMISSED** [review]
OK

**Comment by wopu-ot** [comment]
I am not sure whether I fully understand the use case. Shouldn't vendor-specific commands be issued from a vendor-specific extension to the host rather than the application?

**Review by carlescufi — APPROVED** [review]
LGTM, can we double-check that we don't break any existing applications due to the header shuffle?

**Comment by joerchan** [comment]
> LGTM, can we double-check that we don't break any existing applications due to the header shuffle?

Apart from running shippable?

Atleast I have included the header files back again. So I think it should be fine, unless somebody was including hci.h to get GAP definitions

**Review by jhedberg — APPROVED** [review]

**Comment by carlescufi** [comment]
> > LGTM, can we double-check that we don't break any existing applications due to the header shuffle?
> 
> Apart from running shippable?
> 
> Atleast I have included the header files back again. So I think it should be fine, unless somebody was including hci.h to get GAP definitions

OK, thanks.

**Review by wopu-ot — APPROVED** [review]

**Pull request merged**
