### PR TITLE
Fix esp32 gpios

### PR DESCRIPTION
**Pull request by tyalie**
While working with the XIAO ESP32S3 I found a few mistakes in the dts files of two ESP32 boards. The issue essentially boils down to easy overlookable contributor error. The esp32 reference manual doesn't separate their GPIO pins into blocks of 32, but instead names them consecutively. This clashes a bit with how Zephyr does gpio. This resulted in erroneous GPIO definition like `<&gpio0 47>`.

These patches fix that for the `m5stack_core2` and the `xiao_esp32s3` board. I used `grep -orP "gpio\d \d+"` to find these mistakes.

### CODE REVIEW

**Comment by tyalie** [comment]
When I'm already here: Would it be possible to enforce the strict requirement of "gpios < 32" during compile time?

**Comment by sylvioalves** [comment]
@tyalie, nice catch.

**Review by sylvioalves — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by marekmatej — APPROVED** [review]

**Comment by kartben** [comment]
@sylvioalves / all could someone explain to me what sda-gpios / scl-gpios is supposed to do, and why it's needed in addition to pinctrl? 
To put it differently, I know for a fact that I used i2c1 on the M5Stack Core 2 and it worked just fine (although maybe the bug this PR fixes had the side effect of messing up with the config of GPIO 0 and 1, I guess?)

**Comment by sylvioalves** [comment]
@kartben, I2C1 would work perfectly fine as pinctrl selects proper pin.  
However, some ESP32 SoCS supports hardware bus clear. To accomplish that, gpio handling is needed as you can see below (from i2c_esp32.c file). I guess that might be a way to extract pin number from pinctrl so we would dismiss `sda-gpios / scl-gpios` from DTS.

```c
#ifndef SOC_I2C_SUPPORT_HW_CLR_BUS
	const struct i2c_esp32_config *config = dev->config;
	const int scl_half_period = I2C_CLR_BUS_HALF_PERIOD_US; /* use standard 100kHz data rate */
	int i = 0;

	gpio_pin_configure_dt(&config->scl.gpio, GPIO_OUTPUT);
	gpio_pin_configure_dt(&config->sda.gpio, GPIO_OUTPUT | GPIO_INPUT);
	/* If a SLAVE device was in a read operation when the bus was interrupted, */
	/* the SLAVE device is controlling SDA. If the slave is sending a stream of ZERO bytes, */
	/* it will only release SDA during the  ACK bit period. So, this reset code needs */
	/* to synchronize the bit stream with either the ACK bit, or a 1 bit to correctly */
	/* generate a STOP condition. */
	gpio_pin_set_dt(&config->sda.gpio, 1);
	esp_rom_delay_us(scl_half_period);
	while (!gpio_pin_get_dt(&config->sda.gpio) && (i++ < I2C_CLR_BUS_SCL_NUM)) {
		gpio_pin_set_dt(&config->scl.gpio, 1);
		esp_rom_delay_us(scl_half_period);
		gpio_pin_set_dt(&config->scl.gpio, 0);
		esp_rom_delay_us(scl_half_period);
	}
	gpio_pin_set_dt(&config->sda.gpio, 0); /* setup for STOP */
	gpio_pin_set_dt(&config->scl.gpio, 1);
	esp_rom_delay_us(scl_half_period);
	gpio_pin_set_dt(&config->sda.gpio, 1); /* STOP, SDA low -> high while SCL is HIGH */
	i2c_esp32_config_pin(dev);
#else
```

**Pull request merged**
