### PR TITLE
Remove global properties

### PR DESCRIPTION
**Pull request by mbolivar**
Just submitting to get shippable results for now.

I've been trying and failing to come up with a better way to do HEX_FILES_TO_MERGE in a global-free way, but https://cmake.org/cmake/help/v3.13/policy/CMP0040.html makes that difficult.

### CODE REVIEW

**Review by SebastianBoe — APPROVED** [review]
Changing the CMP0079 policy to NEW is sane.

Avoiding the use of GLOBAL targets also makes sense. What is global today may not be global tomorrow. Using 'target' properties instead of 'global' properties allows us more flexibility in the future.

**Comment by ioannisg** [comment]
@mbolivar do you want to have this in 2.0 Release?

**Comment by mbolivar** [comment]
> @mbolivar do you want to have this in 2.0 Release?

@ioannisg I think @SebastianBoe and I need to discuss a bit more with at least @nashif and @galak if this is part of a multi-image approach we are comfortable with or not.

**Comment by mbolivar** [comment]
Following offline discussion with @SebastianBoe, this will be submitted as part of another PR.

**Pull request closed without merging**
