### PR TITLE
NXP S32 SoC improvements to accommodate new devices

### PR DESCRIPTION
**Pull request by manuargue**
1. Renaming directory for S32K1 support:
The `s32k` directory, which currently supports the S32K3 series, is renamed to align with the respective series names and to accommodate S32K1 devices. This adjustment is necessary due to significant differences in core architecture, MPU, peripherals, and other key aspects between the two series.

2. Streamlining Kconfig options:
The S32K3 Kconfig options currently using the 'M7' suffix are simplified by removing this suffix, as all devices in the S32K3 series feature an Arm Cortex-M7 core. Also in order to remove redundancy, the part number configuration options are consolidated by keeping `CONFIG_SOC_PART_NUMBER` to store the part number as a string and `CONFIG_SOC_PART_NUMBER_<part>` to be selected by the boards.

### CODE REVIEW

**Review by bperseghetti — DISMISSED** [review]

**Comment by manuargue** [comment]
build failure `INFO    - 564/750 mr_canhubk3               tests/subsys/llext/llext.simple.arm                 ERROR Build failure (build)` should be fixed with https://github.com/zephyrproject-rtos/zephyr/pull/64995

**Comment by manuargue** [comment]
rebased & fixed conflicts

**Review by bperseghetti — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Comment by Dat-NguyenDuy** [comment]
@manuargue pls rebase

**Review by bperseghetti — DISMISSED** [review]

**Review by henrikbrixandersen — COMMENTED** [review]
+1 for CAN changes.

**Review by dleach02 — APPROVED** [review]

**Review by bperseghetti — APPROVED** [review]

**Pull request merged**
