### PR TITLE
Draft: Simple NCM driver for usb-next

### PR DESCRIPTION
**Pull request by rgrr**
I have ported a simple version of my TinyUSB NCM driver to Zephyr.

The driver has been kept very simple.  Current idea is not to optimize performance, focus is more on existence of an NCM driver for Zephyr.

The driver currently has unsolved problems with iperf.  This is under investigation.

So consider this as experimental.

### CODE REVIEW

**Comment by decsny** [comment]
> The driver currently has unsolved problems with iperf

I will point out, I think zperf library in general has unresolved problems with iperf, what kind of problems do you mean?

**Comment by rgrr** [comment]
> > The driver currently has unsolved problems with iperf
> 
> I will point out, I think zperf library in general has unresolved problems with iperf, what kind of problems do you mean?

Sorry for not being more specific.  If you monitor network traffic with Wireshark and do 

    for MSS in 10 100 800 1450; do iperf -c 192.168.2.1 -e -i 1 -M $MSS -l 8192 -P 1 ; sleep 2; done

you can observe "TCP Dup ACK"s which do not happen with ECM.  Really not sure what is happening there.

**Comment by rgrr** [comment]
gosh... messed up the branch completely... I think, I have to restart, sorry for stealing your time.

**Comment by rgrr** [comment]
New PR is https://github.com/zephyrproject-rtos/zephyr/pull/72310

**Comment by tmon-nordic** [comment]
> gosh... messed up the branch completely... I think, I have to restart, sorry for stealing your time.

For the future, you can just force push over without resorting to creating new PR.

**Comment by rgrr** [comment]
Thank you for the hint.  Although using (a limited set of) git daily, I'm sometimes feeling like a beginner to it.

**Pull request closed without merging**
