### PR TITLE
LE Audio: Use array of stream pointers instead of array of streams

### LINKED ISSUE #42587: LE Audio: BAP Unicast API use array of pointers instead of array of streams
**Is your enhancement proposal related to a problem? Please describe.**
The ISO API uses an array of pointers, such you can e.g. allocate your ISO channels as 
```c
struct bt_iso_chan left;
struct bt_iso_chan right;

cig_param.cis_channels[0] = &left;
cig_param.cis_channels[1] = &right;

int bt_iso_cig_create(&cig_param, &cig);
```

whereas this takes an array of channels, so that you need to do
```c
struct bt_audio_stream streams[2];
struct bt_audio_stream *left = &streams[0];
struct bt_audio_stream *right = &streams[1];

bt_audio_unicast_group_add_streams(group, streams);
```

In other words, the channels need to be allocated in an array, which is less flexible IMO, especially if you need to allocate multiple streams per remove device. The alternative here would be 

```c
struct bt_audio_stream *streams[2];
struct bt_audio_stream left;
struct bt_audio_stream right;

streams[0] = &left;
streams[1] = &right;

bt_audio_unicast_group_add_streams(group, streams, ARRAY_SIZE(streams));
```

**Describe the solution you'd like**
Change the streams input of `bt_audio_unicast_group_create`, `bt_audio_unicast_group_add_streams`, `bt_audio_unicast_group_remove_streams`, `bt_audio_broadcast_source_create` and `bt_audio_broadcast_sink_sync` to take an array of pointers to `bt_audio_streams` instead of an array of `bt_audio_streams`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
This updates some of the LE Audio APIs to use a more flexible approach when it comes to creating and modifying groups. 

fixes https://github.com/zephyrproject-rtos/zephyr/issues/42587

### CODE REVIEW

**Review by Casper-Bonde-Bose — DISMISSED** [review]
This is a very good change making the API much more usable on a real system where you might not want to change only some of the streams you store.

**Comment by Thalley** [comment]
Fixed issue when deleting broadcast sinks

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Comment by Thalley** [comment]
Added new commit to update the broadcast sample to the API change

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by jhedberg — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

**Pull request merged**
