### PR TITLE
include: usb: add missing HID collection types

### PR DESCRIPTION
**Pull request by ddavidebor**
Added Logical, Report, Named Array, Usage Switch, and Modifier collections in addition to existing Physical and Application collections.

### CODE REVIEW

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Commit title should be `include: usb: add missing HID collection types`.
Please change commit message to:
```

include: usb: add missing HID collection types

Add Logical, Report, Named Array, Usage Switch,
and Modifier collections types.
```

**Comment by ddavidebor** [comment]
@jfischer-no amended :-)

**Comment by petejohanson** [comment]
This would be great. ZMK had to define the collection report constant locally because this was lacking.

**Review by jfischer-no — APPROVED** [review]
Thanks

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
