### PR TITLE
Bluetooth: controller: Fix regression in central event close

### LINKED ISSUE #29957: BLE Notifications limited to 1 per connection event on Zephyr v2.4.0 Central
**Describe the bug**
I am in the process of upgrading my application from v2.3.0 to v2.4.0. While doing testing I observed a decrease in throughput over the application BLE link. After taking a capture between my peripheral (custom) and central (Zephyr v2.4.0) devices I observed that only a single notification is being received per connection event. This is despite the notification payload setting the More Data flag which should cause the Central to ACK and receive the next notification as there is plenty of time before the next connection event.

To rule out complications due to my application I was able to reproduce this via the Zephyr BLE HRS samples (central_hr and peripheral_hr).

**To Reproduce**
Steps to reproduce the behavior on Zephyr v2.4.0:

**On the central board**
1. `west build -b nrf52dk_nrf52832 zephyr/samples/bluetooth/central_hr && west flash`

**On the peripheral board**
1. Modify `samples/bluetooth/peripheral_hr/src/main.c` with the following snippet:

```diff
@@ -130,7 +130,7 @@ void main(void)
         * of starting delayed work so we do it here
         */
        while (1) {
-               k_sleep(K_SECONDS(1));
+               k_sleep(K_USEC(100));
 
                /* Heartrate measurements simulation */
                hrs_notify();
```
2. `west build -b nrf52dk_nrf52832 zephyr/samples/bluetooth/peripheral_hr && west flash`
3. Observe reduced notification throughput via BLE sniff

**Expected behavior**
The peripheral should be able to send multiple notifications per connection event.

**Impact**
This issue greatly reduces possible throughput of a BLE application via notifications.

**Logs and console output**
I have attached a capture from Wireshark

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: gcc-arm-none-eabi-9-2020-q2-update
 - Commit SHA or Version used: v2.4.0

[zephyr_v2.4.0_notification_capture.pcapng.zip](https://github.com/zephyrproject-rtos/zephyr/files/5526926/zephyr_v2.4.0_notification_capture.pcapng.zip)

### PR DESCRIPTION
**Pull request by cvinayak**
Fix regression in connection radio event close in central
role introduced in commit 222dca55981

Fixes #29957.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@ejohnso49 FYI

**Comment by cvinayak** [comment]
@carlescufi @galak @nashif This PR commit message body fails checkpatch locally  (commit description style), but is not flagged by CI...

**Comment by ejohnso49** [comment]
I am going to test with this branch shortly, thank you!

**Comment by ejohnso49** [comment]
Confirmed with the same tests built from this branch that this fixes #29957.
[zephyr_v2.4.0_notification_capture_fixed.pcapng.zip](https://github.com/zephyrproject-rtos/zephyr/files/5533209/zephyr_v2.4.0_notification_capture_fixed.pcapng.zip)

Thanks again @cvinayak and everyone else for the quick response!

**Review by kruithofa — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
