### PR TITLE
drivers: can: loopback: convert the CAN loopback driver to dts

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Convert the CAN loopback driver from being configured via Kconfig to multi-instance configured via devicetree and enable it for a number of test cases on `native_posix`/`native_posix_64`.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
The CI failure is due to #41255.

**Review by alexanderwachter — APPROVED** [review]
The tests look way better now!

**Review by martinjaeger — APPROVED** [review]
Nice improvement.

Finally finding some time to look at your CAN PRs, @henrikbrixandersen. Happy new year everyone :)

**Review by aescolar — APPROVED** [review]
+1 on native_posix related changes

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
