### PR TITLE
dts: arm: st: l4: Split stm32l412 into two memory groups in device tree

### PR DESCRIPTION
**Pull request by gudnimg**
This commit creates two new files in the device tree

1. stm32l412X8.dtsi
2. stm32l412XB.dtsi

This will specifically add stm32l412X8 to the device tree
which was not supported before. Also the memory
for stm32l412XB was not defined specifically before.

Related to issue https://github.com/zephyrproject-rtos/zephyr/issues/33655

For reference: 
image

### CODE REVIEW

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Comment by FRASTM** [comment]
Can you also check if there is a `Kconfig.defconfig.stm32l412x` to add in the soc/arm/stm32/stm32l4

**Comment by GunZi200** [comment]
> Can you also please check if there is a `Kconfig.defconfig.stm32l412x` to add in the soc/arm/stm32/stm32l4

Yeb it is missing. I have it ready locally, I'll create another PR for it later today. :)

**Comment by erwango** [comment]
@GunZi200 would be easier if you add in this PR. You can have multiple commits in one PR. This is easier to follow for related changes.

**Comment by GunZi200** [comment]
> @GunZi200 would be easier if you add in this PR. You can have multiple commits in one PR. This is easier to follow for related changes.

Ok, I'll add it here

**Comment by GunZi200** [comment]
@erwango @FRASTM I added the missing copyright, should hopefully pass all CI checks now.

**Review by erwango — APPROVED** [review]

**Pull request merged**
