### PR TITLE
soc: sam_e70: Mpu regions should include SRAM regions.

### PR DESCRIPTION
**Pull request by AdithyaBaglody**
In order to disable the execution of code from the RAM region
we need to declare it in arm_mpu_regions.c file.

Signed-off-by: Adithya Baglody <adithya.nagaraj.baglody@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
Why is this necessary?
Shouldn't the background map have execute disabled instead, and we only enable execution for flash?

**Comment by AdithyaBaglody** [comment]
@andrewboie even I thought that no execute was default. But it turns out we need to do this.
Tested and verified this behavior.

**Comment by andrewboie** [comment]
> But it turns out we need to do this.

Have you filed a bug on this behavior?
We need to solve the issue of controlling what memory regions are executable.
We don't necessarily need to do what you are proposing here.
Why don't we amend the background map setting to have the no-execute flag set? That way we don't need to consume another memory region.
@agross-linaro any comments?

**Comment by agross-linaro** [comment]
So it appears we cannot change the default memory map behavior.  So by default it allows execute.  So we'll have to use a region to squash that.

**Comment by andrewboie** [comment]
Agreed. Background map can't be configured. This looks like what we need to do.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by agross-oss — APPROVED** [review]

**Pull request merged**
