### PR TITLE
samples: Explicitly disable boot USB device support init at boot

### LINKED ISSUE #52882: Sample applications that enable USB and error if it fails are incompatible with boards like thingy53 with auto-USB init (i.e. USB CDC for logging)
**Describe the bug**
Sample applications that enable USB usually exit if it fails, this is a problem if a board uses USB CDC for it's main UART as this will be enabled during boot-up, but applications will also enable this, which will fail, and if the code exists, the sample will not run.
Example: smp_svr

**To Reproduce**
Build application for device with USB CDC UART, e.g. bl654_usb or thingy53, image will boot, show USB error, then be inoperable

**Expected behavior**
Applications to work regardless of USB CDC configuration

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Commit SHA or Version used: 510dca57da82faf8a546af403c7a2cebbf42289b

### PR DESCRIPTION
**Pull request by nordicjm**
Disables having USB enabled for applications whereby the application
    enables USB to prevent a conflict arising whereby USB is registered
    from multiple points and later calls fail.

Fixes #52882

Have not manually tried running these.

### CODE REVIEW

**Review by de-nordic — DISMISSED** [review]
smp_svr sample looks ok.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
That is problematic. These series of patches change expected behavior. Instead, user should disable Kconfig option CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT if they want to use these samples. I also warned about this earlier.

**Comment by jfischer-no** [comment]
> > These series of patches change expected behavior
> 
> It fixes issues with board which already have USB CDC enabled, it does not impact other use cases

It does, these samples expect USB device support to be enabled exclusively.

> > Instead, user should disable Kconfig option CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT if they want to use these samples
> 
> This is a terrible workaround.

Well, terrible hacks require terrible workarounds, maybe I am missing motivation for this changes, but why would changes below work?
```diff
diff --git a/samples/subsys/usb/cdc_acm/prj.conf b/samples/subsys/usb/cdc_acm/prj.conf
index 7614fbb1a43..55e4fe9217f 100644
--- a/samples/subsys/usb/cdc_acm/prj.conf
+++ b/samples/subsys/usb/cdc_acm/prj.conf
@@ -8,3 +8,4 @@ CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
 CONFIG_SERIAL=y
 CONFIG_UART_INTERRUPT_DRIVEN=y
 CONFIG_UART_LINE_CTRL=y
+CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
```

**Comment by nordicjm** [comment]
@MarekPieta can you try the above with a thingy53 and see if it resolves the issue?

**Comment by desowin** [comment]
Why not skip the `usb_enable(NULL)` call altogether if `IS_ENABLED(CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT)`?

**Comment by MarekPieta** [comment]
Discussed with @kapi-no. He will handle the tests (I just start 2 week vacation).

**Comment by kapi-no** [comment]
@nordicjm, I was fixing build failures today for the upmerge. I am planning to test your PR tomorrow.

**Review by de-nordic — DISMISSED** [review]
smp_svr sample config looks ok.

**Comment by jfischer-no** [comment]
Since it only about samples configuration, could we please just have one commit with more accurate description for that?
```
samples: usb: explicitly disable USB device support initialization at boot

Allow boards that configure CDC ACM UART as default logging backend
to use USB device support samples out of the box.
```

**Comment by kapi-no** [comment]
I verified a few NCS samples (e.g. peripheral_hids_mouse) to check if the USB configuration from upstream (https://github.com/zephyrproject-rtos/zephyr/pull/52293) works with them (and the MCUboot image).

**Review by kapi-no — DISMISSED** [review]

**Comment by carlescufi** [comment]
> Since it only about samples configuration, could we please just have one commit with more accurate description for that?
> 
> ```
> samples: usb: explicitly disable USB device support initialization at boot
> 
> Allow boards that configure CDC ACM UART as default logging backend
> to use USB device support samples out of the box.
> ```

I agree this makes more sense. @nordicjm could you please squash the commits?

**Comment by nordicjm** [comment]
Squashed

**Review by desowin — DISMISSED** [review]

**Review by jfischer-no — CHANGES_REQUESTED** [review]
```
> ... one commit with more accurate description for that?

samples: usb: explicitly disable USB device support initialization at boot

Allow boards that configure CDC ACM UART as default logging backend
to use USB device support samples out of the box.

```
:arrow_up: not addressed.

**Comment by jfischer-no** [comment]
> @jfischer-no Because it's not always related to USB CDC, any board can enable USB at boot for whatever reason, doesn't need to have anything to do with CDC, so that comment would be wrong and invalid

No. Generally, **a board must not enable USB device support**, it is up to application, see release-notes-2.2.rst, it is not arbitrarily, there are reasons like class specific initialization/registrations/callbacks. This was explained many times in different reviews, it is also noted in usb_enable() documentation. Clean solution to use CDC ACM UART for logging or shell when a board requires it, is CDC ACM UART shield approach or whatever it will be. Since there was no progress on  a **generic** solution, Kconfig option USB_DEVICE_INITIALIZE_AT_BOOT was introduced (cheery-picked) to allow a board to configure CDC ACM UART  as default backend and enable USB device support, there is even 'depends on USB_CDC_ACM' and description is 'Use CDC ACM UART as backend for console, shell, or logging.'. 
So, the only existing case for a board in the tree is to use CDC ACM UART as logging or shell backend, and only for this case the changes in your PR are necessary. This should also be reflected in the commit message.

**Review by jfischer-no — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
