### PR TITLE
drivers: uart: Extend API with function for controlling the receiver

### LINKED ISSUE #60990: drivers: uart: Add API to disable RX
**Is your enhancement proposal related to a problem? Please describe.**
When asynchronous API is not used in UART device then RX is always on (started during the initialization). RX being always on increases power consumption. If user wants to reduce the power consumption he would like to force RX to be disabled. Currently, the only way to do that is to call `pm_device_action_run()` and suspend the UART. However, this API is not recommended and might be deprecated in the future. With introduction of runtime device power management (PM) it's device responsibility to get to the lowest power state when not used. It would be better to provide API which disables RX and rely on runtime PM that it will get to the lowest power state.

**Describe the solution you'd like**
Introduce `uart_rx_ctrl(const struct device *uart, bool enable)`. If async API is enabled it returns `-ENOTSUP` otherwise it start (`enable` is true) or stops the UART (if `enable` is false). Since stopping UART may take some time we might consider providing a callback (if NULL then blocking). `uart_rx_ctrl` is proposed instead of `uart_rx_enable` because there is already such function in async API.

### PR DESCRIPTION
**Pull request by nordic-krch**
Proposal of API extension with example implementation for Nordic UARTE peripheral.

Fixes #60990.

### CODE REVIEW

**Comment by dcpleung** [comment]
Why callback? I would think this is an operation where you want it done now, instead of scheduling a power down for later. If it cannot be done immediately, maybe return `-EAGAIN`.

**Comment by nordic-krch** [comment]
> Why callback?

Maybe it's just nordic specific but on our  UART stopping RX takes 5 bytes so for 115200 it's ~500us between triggering stop and getting stopped event. I was thinking about a case when user in the interrupt context after reading RX fifo (interrupt driven API) decides to stop uart RX. With blocking option that cannot be done on nordic devices.

I can change to sync version and return error if called from interrupt context. What do you think?

**Comment by dcpleung** [comment]
Hm... if that's case, the callback is needed. Though, I think the callback should have another argument for `enable`.

**Comment by dcpleung** [comment]
BTW, could you enclose the API under a kconfig? So this is enabled only when needed.

**Review by galak — CHANGES_REQUESTED** [review]
Need to make sure the API is clear about if called and than one calls poll_in() or what happens if any other RX API is called.

Do we need an API to keep track of the status of RX, or are we saying this is left to the user to track?

**Pull request closed without merging**
