### PR TITLE
Convert DNS to use socket service

### PR DESCRIPTION
**Pull request by jukkar**
This will convert DNS resolver and mDNS/LLMNR responders to use socket service API instead of using `net_context` directly.
The change will allow some socket offloading use cases and can also potentially save memory. This is preparation work for fixing #72553.

### CODE REVIEW

**Comment by jukkar** [comment]
* CI fixes

**Review by rlubos — DISMISSED** [review]
LGTM

**Comment by jukkar** [comment]
* more CI fixes, weird how new test failures come after each run

**Review by rlubos — DISMISSED** [review]

**Comment by jukkar** [comment]
* More CI fixes. My local twister run passes now so hopefully CI will pass too.
* Cherry-picked commit from Robert's PR https://github.com/zephyrproject-rtos/zephyr/pull/72919/commits/89d67f2bc6d81579e936c566961e7d1f83d6108c in order to avoid excluding native_posix from most of the networking tests

**Review by rlubos — APPROVED** [review]

**Review by canisLupus1313 — APPROVED** [review]

**Comment by Rakshita00** [comment]
Are these changes needs to be done to make getaddrinfo work smoothly for https without getting error like -101 (EAI_UNKNOWN)?

**Comment by jukkar** [comment]
> Are these changes needs to be done to make getaddrinfo work smoothly for https without getting error like -101 (EAI_UNKNOWN)?

No, the change was done to lower system resource usage by using only one service handler thread if user enables multiple socket services.

**Comment by Rakshita00** [comment]
Actually we are using https in our product to send data to an aws server
Sometimes it is able to retrieve the IP address by getaddrinfo() and send data perfectly but many times we noticed that we were continuously getting err: -101 (EAI_UNKNOWN) issue and it happens very rarely that it recovers itself

What I noticed is that if by any chance the network gets disconnected and than reconnects again the resolve issue gets fixed for sometime but than again the issue starts repeating

**Comment by jukkar** [comment]
Perhaps your network connection is flaky and you get timeouts when resolving addresses.

**Comment by Rakshita00** [comment]
But even when the network connection is stable I face these continuously 
If I don't add the recovering mechanism in the code to reconnect the wifi, the issue won't get recovered even

**Comment by jukkar** [comment]
This really sounds that your issues are in wifi connectivity, and not in upper protocol stack layer.

**Pull request merged**
