### PR TITLE
doc/reference/drivers: document device-specific API extensions

### PR DESCRIPTION
**Pull request by pabigot**
This PR updates the documentation to cover a technical solution to
providing a driver instance that extends the functionality of a
subsystem API.  The solution described was mooted in Zephyr PR #17072
and approved by the Technical Steering Committee during its 2019-08-07
meeting.

Relates-to: #11993
Signed-off-by: Peter A. Bigot <pab@pabigot.com>

### CODE REVIEW

**Comment by pabigot** [comment]
@aescolar @MaureenHelm I'd like to see this in 2.0.0 so we record TSC's decision approving the technique.  If it's not going in until 2.1.0 then it could just be bundled with #17631 where it's already been approved.

**Comment by aescolar** [comment]
> I'd like to see this in 2.0.0 so

@pabigot Feel free to change the milestone then.
I set it for 2.1 because we are now in freeze, and there is no driver yet making use of this. Therefore I presumed it is not the priority to review/merge this until after the release is closed.
(Tagging things with the appropriate milestone should allow people to filter better and lose less time sifting thru PRs)

**Comment by pabigot** [comment]
I was distracted and didn't have a chance to finish the setup, which included linking in @ioannisg as release manager to make an assessment.

If this isn't appropriate for 2.0 I'll just close this and do it again when there's an in-tree use.  Though that could delay anybody else making use of this capability.

**Comment by aescolar** [comment]
> I'll just close this and 

I don't think there is any need to close it even if it is not making it into 2.0. A PR can be reviewed calmly during freeze.

**Comment by ioannisg** [comment]
> 
> 
> > I'll just close this and
> 
> I don't think there is any need to close it even if it was not making it into 2.0. A PR can be reviewed calmly during freeze.

Also doc fixes (and, I think, even extensions)may be merged during the freeze, if they are approved

**Review by dbkinder — APPROVED** [review]
+1 for doc changes

**Review by ioannisg — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Pull request merged**
