### PR TITLE
drivers: display: grove_lcd_rgb: move to misc and refactor

### PR DESCRIPTION
**Pull request by gmarull**
The driver does not implement a display API, it has a custom API. Having
it under display is confusing, since display API consumers may expect
they can use it. These sort of custom drivers fit better under
drivers/misc. Zephyr could actually have a character display driver interface to cover these sort of devices.

I've also refactored the driver to be in "better shape".

### CODE REVIEW

**Comment by nashif** [comment]
It is still a display sample, I am not sure what the issue is of having it in this location. And it is being used and I used it just recently.

**Comment by gmarull** [comment]
> It is still a display sample, I am not sure what the issue is of having it in this location. And it is being used and I used it just recently.

It is a driver that drives a display, but does not implement the display API. FT8XX, a similar case that has a custom API, was moved to drivers/misc for this reason. Is there any reason why this driver doesn't implement the display interface?

**Review by MaureenHelm — DISMISSED** [review]

**Review by jfischer-no — DISMISSED** [review]

**Review by dkalowsk — APPROVED** [review]
I am not aware of any reason why it should live in drivers/display vs drivers/misc.  If the decision is to move to misc, this looks like a clean move to me.

**Comment by gmarull** [comment]
@jfischer-no @MaureenHelm please re-review.

**Comment by gmarull** [comment]
@jfischer-no @MaureenHelm ping

**Review by jfischer-no — APPROVED** [review]
:+1:

**Pull request merged**
