### PR TITLE
Refactor STM32H723/733, STM32H725/735 and add STM32H730 line support

### PR DESCRIPTION
**Pull request by GeorgeCGV**
Adds:

- STM32H730XX value line
- DeviceTree for STM32H730XB SoC

Modifies:

- Refactors STM32H723/733, STM32H725/735 devicetree files to use the inclusion of previous SoC line.
- Corrects STM32H723 memory regions.
- Corrects copyright and license comments (*adds missing line separator*).

~@erwango, shall the STM32H730 extend STM32H25? All of them use the same RM0468 (_"STM32H723/733, STM32H725/735 and STM32H730"_). The STM32H23 is not fully defined (_missing correct SRAM regions_). I can extend the STM32H23 DTS and then let H730 extend H725. What do you think?~

### CODE REVIEW

**Comment by erwango** [comment]
> @erwango, shall the STM32H730 extend STM32H25? All of them use the same RM0468 (_"STM32H723/733, STM32H725/735 and STM32H730"_). The STM32H23 is not fully defined (_missing correct SRAM regions_). I can extend the STM32H23 DTS and then let H730 extend H725. What do you think?

That should work indeed

**Comment by GeorgeCGV** [comment]
@erwango, ready for review.

**Review by erwango — APPROVED** [review]
Neat, txs!

**Review by ABOSTM — APPROVED** [review]
lgtm

**Pull request merged**
