### PR TITLE
Bluetooth: TBS: Make GTBS mandatory

### LINKED ISSUE #42487: LE Audio: Make TBS optional
**Is your enhancement proposal related to a problem? Please describe.**
Current TBS instances is mandatory, but GTBS is optional, but in the spec it is the other way around. GTBS is mandatory if supporting the TBS functionality, and there can then be 0 or more specific TBS instances. 

**Describe the solution you'd like**
The Kconfigs needs to change such that GTBS isn't an option, and the number of TBS services can be 0. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Any places that checked for GTBS is now always enabled as GTBS is mandatory to support, and the Kconfig option was removed.

Also removed a duplicate Kconfig option for TBS,
BT_TBS_SERVICE_COUNT, as it was unused.

The other Kconfig option BT_TBS_BEARER_COUNT is used instead exclusively to set it if needed.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/42487

### CODE REVIEW

**Comment by Thalley** [comment]
Converted to draft to also include changes to the TBS client

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by kruithofa — DISMISSED** [review]

**Comment by Thalley** [comment]
Rebased to solve merge conflicts

**Review by kruithofa — APPROVED** [review]

**Review by jthm-ot — APPROVED** [review]
Great work. Looks good to me

**Pull request merged**
