### PR TITLE
scripts/*syscalls.py: sort os.walk() for a more deterministic build

### PR DESCRIPTION
**Pull request by marc-hb**
Found by "disordered --shuffle-dirents=yes".

Sorting os.walk() in scripts/subfolder_list.py removes the randomness in
the following files:

  build/zephyr/misc/generated/syscalls_subdirs.txt
  build/zephyr/CMakeFiles/syscall_list_h_target.dir/ or build.ninja

Sorting os.walk() in scripts/parse_syscalls.py removes the randomness
in:

  build/zephyr/misc/generated/syscalls.json
  build/zephyr/include/generated/syscall_dispatch.c
  build/zephyr/include/generated/syscall_list.h

Note my (limited so far) testing did *not* observe any randomness in any
object file that this would address; the main purpose here is to remove
a very large amount of noise in diffoscope.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by agross-linaro** [comment]
Seems like a good change.

**Review by agross-oss — APPROVED** [review]

**Comment by SebastianBoe** [comment]
Very nice.

**Comment by marc-hb** [comment]
BTW it's possible right now to entirely nullify the output of `diffoscope --exclude-directory-metadata hello_world/build.1/ hello_world/build.2/` where build.1 and build.2 are two consecutive `hello_world/build/` with just this hack:

```
--- a/cmake/app/boilerplate.cmake
+++ b/cmake/app/boilerplate.cmake
@@ -28,6 +28,9 @@ cmake_minimum_required(VERSION 3.13.1)
 # CMP0002: "Logical target names must be globally unique"
 cmake_policy(SET CMP0002 NEW)
 
+SET(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> Dqc <TARGET> <LINK_FLAGS> <OBJECTS>")
+SET(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> -D <TARGET>")
+
 if(NOT (${CMAKE_VERSION} VERSION_LESS "3.13.0"))
   # Use the old CMake behaviour until 3.13.x is required and the build
   # scripts have been ported to the new behaviour.
```
It's unrelated to `disordered --shuffle-dirents=yes` and needed either way.

**Comment by marc-hb** [comment]
Another determinism fix if you liked this one: PR #13608 git describe --abbrev=12

**Pull request merged**
