### PR TITLE
Test: tracing: check zephyr os tracing functions

### PR DESCRIPTION
**Pull request by Zhaoningx**
Add some testcases for subsys/trace and Use self-define
backends to get tracing data and check
the output data.

more comments see https://github.com/zephyrproject-rtos/zephyr/pull/27897
due to long time no changed, so closed by zephyrbot, so I re-open this PR, and please have a
take look at this, Thanks.

Signed-off-by: Ningx Zhao <ningx.zhao@intel.com>

### CODE REVIEW

**Review by LeiW000 — CHANGES_REQUESTED** [review]
Ning needs more time to design test cases for tracing.

**Comment by nashif** [comment]
you need to rebase this PR against a recent version of master.

**Comment by Zhaoningx** [comment]
@nashif  @LeiW000 ， I have finished the issue, so could you have a take look at this PR? thanks.

**Comment by Zhaoningx** [comment]
Hi @LeiW000 , I think we can close this PR, I will re-design tracing testcases by using default backend.

**Comment by LeiW000** [comment]
Then, please close it.

**Pull request closed without merging**
