### PR TITLE
drivers: led: lp5562: Ignores vin-supply and supply-gpio settings

### LINKED ISSUE #70397: LED: ti,lp5562 driver ignores vin-supply and supply-gpio device tree settings
**Describe the bug**
The TI LP5562 driver binding includes the i2c-device binding, which in turn includes the power binding. This binding specifies a vin-supply for a power regulator and supply-gpios for a power enable GPIO for the device. The driver does not do anything with these device tree arguments.

**To Reproduce**
Create an instance of an ti,lp5562 device.
Set the vin-supply and supply-gpios values.
Compile the blinky app.
The regulator will not be turned on, and the GPIO will not be set.

**Expected behavior**
The driver should enable power to the LP5562 before trying to communicate with it over I2C.

### PR DESCRIPTION
**Pull request by timKnodel**
Fixes #70397

### CODE REVIEW

**Comment by MaureenHelm** [comment]
Please rebase and remove the merge commit

**Comment by simonguinot** [comment]
ping @timKnodel

**Comment by timKnodel** [comment]
Updated

**Comment by timKnodel** [comment]
ping @simonguinot

**Comment by simonguinot** [comment]
> ping @simonguinot

Thanks for the update @timKnodel. I am off this week, so I'll review it next week.

**Comment by simonguinot** [comment]
Hi @timKnodel,

This PR looks good to me but here is my concern: in the issue description you says:

> This binding specifies a vin-supply for a power regulator and supply-gpios for a power enable GPIO for the device. The driver does not do anything with these device tree arguments.

But it appears that no driver does anything with these properties. There is no match for the following command:

`$ grep -r -E "vin_supply|supply_gpio" drivers/`

So I wonder if this is the right way to go... Since I am not familiar with the regulator API, I'll ask the regulator people for their review. Let's wait to hear from them !

**Comment by simonguinot** [comment]
Hi @aasinclair @danieldegrasse and @gmarull. Please, can you review this PR ? Thanks in advance.

**Comment by timKnodel** [comment]
That is easy to do, but I am not clear why we the power.yaml exists and is included in the device's dts binding it is not supposed to be used by the device drivers to manage power.

**Comment by aasinclair** [comment]
> That is easy to do, but I am not clear why we the power.yaml exists and is included in the device's dts binding it is not supposed to be used by the device drivers to manage power.

Indeed.  It is not implemented by anything any more.
It looks like it has been replaced by regulators in the last couple of years, so should probably be removed at some point.

**Comment by simonguinot** [comment]
Hi @timKnodel. I suggest we drop this PR. If you agree, please close it. Thanks

**Comment by nashif** [comment]
is this PR still relevant or should it be closed? what about the associated issue?

**Comment by simonguinot** [comment]
Hi @timKnodel. I suggest we drop this PR. If you agree, please close it. Thanks

> is this PR still relevant or should it be closed? what about the associated issue?

I think this PR and the associated issue can be closed. I was just waiting for a feedback from @timKnodel.

**Comment by simonguinot** [comment]
A fixed regulator should be used instead.

**Pull request closed without merging**
