### PR TITLE
Bluetooth: Mesh: Use decimals instead of hex nums in DFD shell cmds

### PR DESCRIPTION
**Pull request by PavelVPV**
JSON doesn't support hexdecimals as numbers.

### CODE REVIEW

**Review by alxelax — COMMENTED** [review]
Could you elaborate how JSON is related to mesh shell?

**Comment by PavelVPV** [comment]
> Could you elaborate how JSON is related to mesh shell?

We format output commands of DFD server in JSON.

**Comment by PavelVPV** [comment]
> > Could you elaborate how JSON is related to mesh shell?
> 
> We format output commands of DFD server in JSON.

...in shell. This is for easy parsing when using mcumgr IIRC.

**Review by alxelax — APPROVED** [review]
Hm... I didn't know about this anything. Need to figure out.

**Review by Andrewpini — APPROVED** [review]

**Pull request merged**
