### PR TITLE
llext: split llext.c in multiple files

### PR DESCRIPTION
**Pull request by pillo79**
Currently all llext code is contained in a single 1k-line file, making it difficult to manage. This PR refactors the llext subsystem by splitting `llext.c` by topic in multiple files:

* `llext_mem.[ch]` manages the llext heap and provides generic alloc/free to the subsystem, along with the functions dealing with section allocation; 
* `llext_load.[ch]` contains the bulk of the `llext_load()` function, implementing ELF parsing, section mapping and symbol management;
* `llext_link.[ch]` implements the `llext_link()` function that is called at load time to apply the actual relocations to the binary.

This work results in the original `llext.c` file only having public API implementations.

This PR introduces **no functional change**; the only (minor) code changes are in the first 2 commits:
* b2adb5499286beee7a65864f3bbd2d0948a28c87 adds generic llext heap management wrappers;
* b84b2726620c0e36570915711f8583a586c40e72 moves all sanity checks inside `do_llext_load()` so that only generic API wrapper code remains in `llext_load()`.

### CODE REVIEW

**Review by teburd — COMMENTED** [review]
It's fine to split up the implementation file (.c files) but I'd perhaps consolidate the headers into one private to the subsystem header (llext_priv.h or something along these lines) rather than having headers with only single function signatures

**Review by teburd — DISMISSED** [review]
I like it, looks clean to me I suppose it'll need rebasing depending on what merges first :-)

**Comment by pillo79** [comment]
> I like it, looks clean to me I suppose it'll need rebasing depending on what merges first :-)

Indeed. As this is a relatively painless cut-and-paste, I will rebase this after #73571 and #72358, which are much more intrusive, are in.

**Comment by pillo79** [comment]
Rebased over current `main`.

**Review by teburd — DISMISSED** [review]

**Comment by pillo79** [comment]
v2: 
* dropped the removal of `llext_find_section` as it's actively used by SOF.

**Review by teburd — DISMISSED** [review]

**Comment by pillo79** [comment]
Apologies for the many resubmissions, but this was a needed fix.

v3: 
* `LOG_DBG` messages were not shown since the default log level was used.

**Review by teburd — APPROVED** [review]

**Review by lyakh — APPROVED** [review]

**Comment by lyakh** [comment]
tested with SOF, no regressions identified

**Pull request merged**
