### PR TITLE
drivers: sensor: Add sensor info iterable section and shell command

### PR DESCRIPTION
**Pull request by MaureenHelm**
Adds an iterable section in ROM to hold constant information, such as vendor and model name, for all enabled sensor driver instances and a corresponding sensor shell command. Vendor and model names are extracted from devicetree compatibles (see #49489 and #50015), and friendly names are extracted from an optional base sensor devicetree property (see #50929).

## Example 1: `reel_board`
```console
$ west build -b reel_board -p auto samples/sensor/sensor_shell/
```

```console
uart:~$ sensor info
0xbeec: device: 0xbcb8, vendor: Avago Technologies, model: apds9960, friendly name: 
0xbefc: device: 0xbcd0, vendor: NXP Semiconductors, model: fxos8700, friendly name: 
0xbf0c: device: 0xbce8, vendor: Texas Instruments, model: hdc, friendly name: 
0xbf1c: device: 0xbd00, vendor: Nordic Semiconductor, model: nrf-temp, friendly name: 
```

## Example 2: `frdm_k64f` with `x_nucleo_iks01a3` sensor shield
```console
$ west build -b frdm_k64f -p auto samples/sensor/sensor_shell/ -- -DSHIELD=x_nucleo_iks01a3
```
```console
uart:~$ sensor info
0xc92c: device: 0xc500, vendor: STMicroelectronics, model: hts221, friendly name: 
0xc93c: device: 0xc518, vendor: STMicroelectronics, model: lis2dw12, friendly name: 
0xc94c: device: 0xc530, vendor: STMicroelectronics, model: lis2mdl, friendly name: 
0xc95c: device: 0xc548, vendor: STMicroelectronics, model: lps22hh, friendly name: 
0xc96c: device: 0xc560, vendor: STMicroelectronics, model: lsm6dso, friendly name: 
0xc97c: device: 0xc578, vendor: STMicroelectronics, model: stts751, friendly name: 
0xc98c: device: 0xc4e8, vendor: NXP Semiconductors, model: fxos8700, friendly name: 
```

cc: @huhebo

### CODE REVIEW

**Review by teburd — DISMISSED** [review]

**Comment by galak** [comment]
the output a few comments on the output, not sure how we can improve this:
`0xc92c: device: 0xc500, vendor: STMicroelectronics, model: hts221, friendly name: `

1. Its unclear what the first number printed even means w/o looking at the code -- is this value meaningful?
2. Not sure if tweaking 'device' to 'device pointer' would be more clear?
3. I wonder about putting brackets around the strings to make it maybe a bit more obvious when a string is empty/NULL:
4. 
`0xc92c: device pointer: 0xc500, vendor: [STMicroelectronics], model: [hts221], friendly name: []`

**Review by dcpleung — DISMISSED** [review]

**Comment by MaureenHelm** [comment]
> a few comments on the output, not sure how we can improve this: `0xc92c: device: 0xc500, vendor: STMicroelectronics, model: hts221, friendly name: `
> 
> 1. Its unclear what the first number printed even means w/o looking at the code -- is this value meaningful?

Not really, no. Removed.

> 2. Not sure if tweaking 'device' to 'device pointer' would be more clear?

Replaced with "device name", which is also used as an argument to the `sensor get` shell command

> 3. I wonder about putting brackets around the strings to make it maybe a bit more obvious when a string is empty/NULL:
> 
> So maybe: `device pointer: 0xc500, vendor: [STMicroelectronics], model: [hts221], friendly name: []`

Not sure I love it, but added the brackets.

**Comment by teburd** [comment]
> > a few comments on the output, not sure how we can improve this: `0xc92c: device: 0xc500, vendor: STMicroelectronics, model: hts221, friendly name: `
> > 
> > 1. Its unclear what the first number printed even means w/o looking at the code -- is this value meaningful?
> 
> Not really, no. Removed.
> 
> > 2. Not sure if tweaking 'device' to 'device pointer' would be more clear?
> 
> Replaced with "device name", which is also used as an argument to the `sensor get` shell command
> 
> > 3. I wonder about putting brackets around the strings to make it maybe a bit more obvious when a string is empty/NULL:
> > 
> > So maybe: `device pointer: 0xc500, vendor: [STMicroelectronics], model: [hts221], friendly name: []`
> 
> Not sure I love it, but added the brackets.

Whats wrong with using quotes here in place of the brackets? The brackets make me think there's going to be an array of these things which I don't think is the case here right?

**Review by dcpleung — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Comment by stephanosio** [comment]
> 3\. I wonder about putting brackets around the strings to make it maybe a bit more obvious when a string is empty/NULL:

Why not just print `(null)`, `(none)` or `(empty)` when a string is empty instead of putting (arguably confusing) brackets everywhere?

`device pointer: 0xc500, vendor: STMicroelectronics, model: hts221, friendly name: (null)`

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
The fundamentals are there, we can bike shed about the output in a follow-up PR.

**Comment by MaureenHelm** [comment]
> The fundamentals are there, we can bike shed about the output in a follow-up PR.

Follow up PR: #51864

**Pull request merged**
