### PR TITLE
bluetooth: id: make sharing RPA between adv sets optional

### PR DESCRIPTION
**Pull request by kapi-no**
Added a Kconfig option that allows to restore the RPA generation policy before the RPA sharing feature was introduced in the following PR:

https://github.com/zephyrproject-rtos/zephyr/pull/55449

The new Kconfig option configures the advertising sets linked with the same Bluetooth identity to use unique Resolvable Private Address. The generated RPAs of the advertising sets in a given rotation period differ from each other.

### CODE REVIEW

**Comment by kapi-no** [comment]
The RPA sharing feature (contributed in the https://github.com/zephyrproject-rtos/zephyr/pull/55449 PR) introduces dependencies between the advertising sets and it is unclear how the Bluetooth identity should handle the case in which two sets return conflicting return values in the `rpa_expired` callback. This issue is described under the following link:

https://github.com/zephyrproject-rtos/zephyr/issues/64625

The `CONFIG_BT_RPA_UNIQUE_PER_ADV_SET` option allows the application to have more autonomous Bluetooth advertising sets that do not have cross dependencies. In most cases, users shouldn't care whether the RPA for all advertising sets is the same.

I am also happy to change the default behaviour (e.g. RPA sharing mode turned off) if it seems like a better approach. The new Kconfig option can also be changed to describe an option for turning on/off the RPA sharing mode instead of the RPA unique mode.

**Comment by alwa-nordic** [comment]
@niym-ot You are the author of the RPA sharing feature. What's your opinion on this PR? Should the sharing mode be the non-default behavior?

**Comment by kapi-no** [comment]
After thinking about it for a while, I think the RPA sharing (e.g. `CONFIG_BT_RPA_SHARING`) should have a configuration option instead of like it is currently done in my PR (`CONFIG_BT_RPA_UNIQUE_PER_ADV_SET). The RPA sharing requires additional code (more complexity) and memory. It also reduces the privacy aspect quite a bit as it is easier for the observer of advertising packets to infer the protocol used by the broadcasting device (they can easily link two advertising sets to the same device).

In most cases, users do not probably need the RPA sharing feature.

@niym-ot, we would like to hear your input as @alwa-nordic already indicated in his last comment.

**Comment by kapi-no** [comment]
Added a commit with an additional test configuration to cover the code path when the RPA sharing feature is enabled

**Review by alwa-nordic — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Comment by kapi-no** [comment]
Changed the `simulation_id` for the test execution with the RPA sharing enabled to fix BabbleSim CI failures. The previous name collided with the simulation identifier intended for the test run with the RPA sharing disabled.

**Review by alwa-nordic — APPROVED** [review]

**Review by theob-pro — APPROVED** [review]

**Comment by niym-ot** [comment]
Great to put it under config flag, CONFIG_BT_RPA_SHARING ! We will test the feature once we pull in the latest Zephyr.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
