### PR TITLE
dts: arm: stm32h723 fix SRAM2 address

### LINKED ISSUE #54597: SRAM2 wrong on certain stm32h7 SOC (system crashes during startup)

### PR DESCRIPTION
**Pull request by rlezuo1**
* there is a subtle difference to the stm32h74x
 * c.f. rm0468 (stm32h723/733 stm32h725/735 and stm32h730)
 * verified on stm32h735

Fixes #54597

### CODE REVIEW

**Review by FRASTM — DISMISSED** [review]

**Comment by erwango** [comment]
Thanks for the fix. Can you open a related issue ? This would be required to get it merged asap (merge window is currently frozen ).

**Review by erwango — DISMISSED** [review]
Thanks for the fix

**Comment by rlezuo1** [comment]
related issue https://github.com/zephyrproject-rtos/zephyr/issues/54597

**Review by GeorgeCGV — DISMISSED** [review]
Thank you! Please fix the compliance error.

**Review by gautierg-st — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by GeorgeCGV — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Pull request merged**
