### PR TITLE
samples: mbedTLS server: Remove CONFIG_NET_SLIP_TAP assignment

### PR DESCRIPTION
**Pull request by ulfalizer**
Was written as "CONFIG_NET_SLIP", which doesn't exist.

Jukka Rissanen indicated in
#7810 that
CONFIG_NET_SLIP_TAP doesn't need to be enabled here ("I prefer we remove
the line completely as the TAP is enabled automatically for qemu_x86"),
so remove the assignment rather than fixing it.

Signed-off-by: Ulf Magnusson <Ulf.Magnusson@nordicsemi.no>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by ulfalizer** [comment]
Looks to be a legit build failure here, so DNM.

**Comment by pfalcon** [comment]
> Looks to be a legit build failure here, so DNM.

Hmm:

~~~
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/drivers/console/uart_pipe.c:95:37: error: ‘CONFIG_UART_PIPE_ON_DEV_NAME’ undeclared (first use in this function)
  uart_pipe_dev = device_get_binding(CONFIG_UART_PIPE_ON_DEV_NAME);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

But why do we have "epidemic" (well, 2nd for today) of unrelated breakages?

**Review by jukkar — DISMISSED** [review]
I prefer we remove the line completely as the TAP is enabled automatically for qemu_x86.

**Comment by ulfalizer** [comment]
@jukkar 
OK, will do.

Re. the build failure, what are the proper dependencies here? `CONFIG_NET_SLIP_TAP` is only referenced in `cmake/emu/qemu.cmake`. It sets `QEMU_NET_STACK`.

 - [CONFIG_UART_PIPE_ON_DEV_NAME dependencies](http://docs.zephyrproject.org/reference/kconfig/CONFIG_UART_PIPE_ON_DEV_NAME.html#direct-dependencies)

 - [NET_SLIP_TAP dependencies](http://docs.zephyrproject.org/reference/kconfig/CONFIG_NET_SLIP_TAP.html#direct-dependencies)

**Comment by ulfalizer** [comment]
@jukkar 
I updated the PR to remove it. Might be dependency issues here that could be checked separately.

**Pull request merged**
