### PR TITLE
Revert 69705 and fix #72344

### LINKED ISSUE #72344: tests/subsys/logging/log_timestamp/ failing on qemu_x86[_64] on main
**Describe the bug**
tests/subsys/logging/log_timestamp/logging.output.custom_timestamp is failing in main since #69705 was merged

**To Reproduce**
1. twister -p qemu_x86 -T tests/subsys/logging/log_timestamp/ -s logging.output.custom_timestamp 

**Expected behavior**
No errors

**Impact**
main CI broken

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/8951164071/job/24587211348#step:11:3389
```
SeaBIOS (version zephyr-v1.0.0-0-g31d4e0e-dirty-20200714_234759-fv-az50-zephyr)
Booting from ROM..
*** Booting Zephyr OS build v3.6.0-3414-gfa7c05cf4718 ***
Running TESTSUITE test_timestamp
===================================================================
START - test_custom_timestamp

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/logging/log_timestamp/src/log_timestamp_test.c:78: test_timestamp_test_custom_timestamp: strcmp(exp_str, mock_buffer) not equal to 0

 FAIL - test_custom_timestamp in 0.002 seconds
===================================================================
TESTSUITE test_timestamp failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [test_timestamp]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.002 seconds
 - FAIL - [test_timestamp.test_custom_timestamp] duration = 0.002 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: d540a6b01e39b244047af44d6af1d792
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 22.04 (CI)
 - Toolchain  Zephyr SDK (CI)
 - Commit SHA or Version used: fa7c05cf4718be15adad0e913fa51a2d5b5bf3dc

**Additional context**
Introduced by https://github.com/zephyrproject-rtos/zephyr/commit/7c03e5de7f0298e9219f82da52b75696c45baa9d

### PR DESCRIPTION
**Pull request by aescolar**
https://github.com/zephyrproject-rtos/zephyr/pull/69705
Introduced a regression in main in which tests/subsys/logging/log_timestamp started failing. 

Let's revert the PR. It can be submitted after with the issue fixed.

Fixes #72344

### CODE REVIEW

**Review by fabiobaltieri — APPROVED** [review]

**Comment by jhedberg** [comment]
@aescolar did you consider reverting just the one commit that @fabiobaltieri identified as the culprit? I was able to verify that simply reverting it also fixes the issue.

**Comment by aescolar** [comment]
> @aescolar did you consider reverting just the one commit that @fabiobaltieri identified as the culprit? I was able to verify that simply reverting it also fixes the issue.

I did, but I was concerned that reverting only that one I would leave something else broken. It just seemed the cleaner and safer thing to do was revert the whole PR; And once the author identifies the cause behind the issue the PR can be resubmitted with it fixed.

**Review by jhedberg — APPROVED** [review]
> > @aescolar did you consider reverting just the one commit that @fabiobaltieri identified as the culprit? I was able to verify that simply reverting it also fixes the issue.
> 
> I did, but I was concerned that reverting only that one I would leave something else broken. It just seemed the cleaner and safer thing to do was revert the whole PR; And once the author identifies the cause behind the issue the PR can be resubmitted with it fixed.

Ok. Fair enough.

**Comment by aescolar** [comment]
Thanks @najumon1980 , does that mean you will be able to have a patch ready and passing soon? (in a matter of an hour or so). Otherwise we can just merge the revert and the original PR can be resubmitted without time pressure.

**Comment by najumon1980** [comment]
let see I can provide a fix for this

**Review by najumon1980 — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by najumon1980** [comment]
Provided following fix for the regression:
https://github.com/zephyrproject-rtos/zephyr/pull/72352

**Comment by jhedberg** [comment]
> @najumon1980 The fix in #72352 does not seem too trivial. I'm quite inclined to merge this revert PR and unblock main. If you don't say otherwise in the next few minutes I'll go ahead and merge this one.

Yes, I think it's better to give the correct fix some more time for review, especially from @andyross, so let's merge the revert first.

**Comment by andyross** [comment]
Random aside: this is the second time in a week we've seen core tests regress from PR's that didn't see them in CI?  Is something getting skipped?  Basically how was this not caught?

**Pull request merged**
