### PR TITLE
userspace: add app memory report script

### PR DESCRIPTION
**Pull request by tyrantlizard77**
This script accepts a kernel binary and dumps out information
on how much memory is wasted due to partition size/alignment
constraints.

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

**Comment by andrewboie** [comment]
Sample output:

```
$ python3 ~/projects/zephyr4/scripts/appmem_report.py zephyr/zephyr.elf 
Userspace memory partition report:
Partition                     Total       Used        Wasted      Efficiency
----------------------------------------------------------------------------
ztest_mem_partition           0x40        0x34        0xc         81.25%
  gap 0x0         
z_libc_partition              0x20        0x4         0x1c        12.50%
  gap 0x7fa0      
k_mbedtls_partition           0x8000      0x7fe0      0x20        99.90%

total                         0x10000     0x8018      0x7fe8      50.04%

```

**Review by dcpleung — APPROVED** [review]

**Review by ioannisg — COMMENTED** [review]
Where is the script invoked?

**Comment by andrewboie** [comment]
> Where is the script invoked?

manually, at the moment.
In a later PR I might attach it to verbose builds.

**Review by agross-oss — APPROVED** [review]

**Comment by andrewboie** [comment]
Closing for now, as @dcpleung modification to the partitioning script can dump similar information.

**Pull request closed without merging**
