### PR TITLE
dts: stm32: Remove pinctrl definitions

### PR DESCRIPTION
**Pull request by erwango**
dts pinctrl definitions were pushed in tree without the code
available to deal with it. They have been kept waiting for the
code, but this is taking much more time than initially thought.

So in current zephyr tree, for all STM32 boards, we have pinmux.c
file which is used to configure pins and these files that are
basically no-op. This situation is creating a lot of confusion
especially to new comers, and create useless maintenance effort.

Remove these files for now.
When zephyr will ready to use them, this commit could be reverted.

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by erwango** [comment]
@b0661, I'm suspecting you're using these of tree, so would like to get your acknowledgment in order to proceed.

**Comment by b0661** [comment]
>> @b0661, I'm suspecting you're using these of tree, so would like to get your acknowledgment in order to proceed.

@erwango Iḿ fine with removing the dts pinctrl definitions.

**Comment by erwango** [comment]
> > > @b0661, I'm suspecting you're using these of tree, so would like to get your acknowledgment in order to proceed.
> 
> @erwango Iḿ fine with removing the dts pinctrl definitions.

@b0661, thanks!

**Review by ydamigos — CHANGES_REQUESTED** [review]
You missed `stm32_min_dev` board.

**Comment by erwango** [comment]
> You missed stm32_min_dev board.

Fixed, Thanks @ydamigos .

**Review by ydamigos — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by galak** [comment]
Any harm in keeping these?

**Comment by erwango** [comment]
> Any harm in keeping these?

People complaining it has no effect or trying to fix, pushing updates... So this is basically frequent support trying to exaplian the situation.
Though, I was thinking it could be back again as soon as needed by reverting the commit.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
hand merging since this will not pass CI due to size of change.

**Comment by galak** [comment]
Hand merged since we know its not going to pass CI.

**Pull request merged**
