### PR TITLE
drivers: spi: Make spi_context.h usable for CONFIG_MULTITHREADING=n

### PR DESCRIPTION
**Pull request by yashi**
`drivers/flash/spi_nor.c` supports `CONFIG_MULTITHREADING=n` however spi drivers using `spi_context.h` can't.

This commit makes `spi_context.h` usable for single threaded applications by removing `k_sem lock` and `k_sem sync` for `CONFIG_MULTITHREADING=n`, and introduces a new macro `SPI_CONTEXT_BASE_INIT()` for both `CONFIG_MULTITHREADING=y` and `n`.

This reduces about 3KB.

With CONFIG_MULTITHREADING=n

    Memory region         Used Size  Region Size  %age Used
               FLASH:          0 GB         0 GB
                 RAM:       12260 B       128 KB      9.35%
            IDT_LIST:          0 GB         2 KB      0.00%

With CONFIG_MULTITHREADING=y

    Memory region         Used Size  Region Size  %age Used
               FLASH:          0 GB         0 GB
                 RAM:       15556 B       128 KB     11.87%
            IDT_LIST:          0 GB         2 KB      0.00%

`spi_context_cs_configure_all()`, `_spi_context_cs_control()`, and `spi_context_cs_control()` are move above `#ifndef CONFIG_MULTITHREADING` in order to group the related functions under one `#ifdef`.

### CODE REVIEW

**Comment by tbursztyka** [comment]
> The member variable lock and sync in struct spi_context is not removed in this commit because that will clutter INIT macros. We can remove them later if we need to save a few more bytes.

Go ahead, make the modification. From macro point of view, it seems rather easy: in case of non-multi-threading, declare empty macros (SPI_CONTEXT_INIT_LOCK(...) SPI_CONTEXT_INIT_SYNC(...) ). Where do you see a clutter issue? 
Afaik, there should not be anything to do on driver side (drivers call these macro with their privata data name and context attribute name, and so far: both are still valid whether multithreading is on or not).

**Comment by yashi** [comment]
> declare empty macros (SPI_CONTEXT_INIT_LOCK(...) SPI_CONTEXT_INIT_SYNC(...) ). Where do you see a clutter issue? 

How do you want to handle the left comma (,) in the struct initializers?

If you have this:

```c
struct spi_dw_data spi_dw_data_port_3 = {
	SPI_CONTEXT_INIT_LOCK(spi_dw_data_port_3, ctx),
	SPI_CONTEXT_INIT_SYNC(spi_dw_data_port_3, ctx),
	SPI_CONTEXT_CS_GPIOS_INITIALIZE(DT_DRV_INST(3), ctx)
};
```

With an empty macro, you will end up with

```c
struct spi_dw_data spi_dw_data_port_3 = {
	,
	,
	SPI_CONTEXT_CS_GPIOS_INITIALIZE(DT_DRV_INST(3), ctx)
};
```

This is valid if and only if you have `struct k_sem lock` and `struct k_sem sync` in the `struct spi_context`.  But then, what is the point of removing the initializer, which only initialize at compile time?

I only came up with three options.  If you know a better way, it's more than welcome!

1. empty macros with comma included
2. empty macros with comma included (Linux way)
3. `#ifdef CONFIG_MULTITHREADING` around the initializer


### Empty macros with comma included

Instead of the current `SPI_CONTEXT_INIT_LOCK()`, define it as

```c
#define SPI_CONTEXT_INIT_LOCK(_data, _ctx_name)				\
	._ctx_name.lock = Z_SEM_INITIALIZER(_data._ctx_name.lock, 0, 1),
```

- pros: simple?
- cons:
  - changes on driver side (removing the trailing comma).
  - confuses simple code highlighter?

### Empty macros with comma included (Linux way)

This is a variant of the former.  I'm not yet sure why but Linux does a bit differently.  They put a comma in front of the initializer.  You can see [__MUTEX_INITIALIZER](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/mutex.h?h=v6.3#n108) here.

```c
#define SPI_CONTEXT_INIT_LOCK(_data, _ctx_name)				\
	,  ._ctx_name.lock = Z_SEM_INITIALIZER(_data._ctx_name.lock, 0, 1)
```

- pros: support (really) old compiler?
- cons:
  - changes on driver side.
  - confuses simple code highlighter?

### #ifdef CONFIG_MULTITHREADING around the initializer

Instead of changing the definition of `SPI_CONTEXT_INIT_LOCK`, we can add `#if` in the driver side.

```c
#if IS_ENABLED(CONFIG_MULTITHREADING)
struct spi_dw_data spi_dw_data_port_3 = {
	SPI_CONTEXT_INIT_LOCK(spi_dw_data_port_3, ctx),
	SPI_CONTEXT_INIT_SYNC(spi_dw_data_port_3, ctx),
	SPI_CONTEXT_CS_GPIOS_INITIALIZE(DT_DRV_INST(3), ctx)
};
#else
struct spi_dw_data spi_dw_data_port_3 = {
	SPI_CONTEXT_CS_GPIOS_INITIALIZE(DT_DRV_INST(3), ctx)
};
#endif
```

DW is a simple one but many others having the initializer within a macro for `DT_INST_FOREACH_STATUS_OKAY()`.  That means that the whole macro block must be `#ifdef`'ed

- pros: no change for `SPI_CONTEXT_INIT_LOCK`.
- cons: 
  - requires changes on driver if supports `CONFIG_MULTITHREADING=n`

**Comment by tbursztyka** [comment]
indeed, missed that issue.

Well unfortunately, none of the options seem nice enough. So we need to go further.

What about having a unique macro SPI_CONTEXT_BASE_INIT() that all spi's driver private data would call, which macro would relevantly set the locks or not etc... And, in order to avoid the comma issue on driver side would always initialize one attribute such as 'config' to NULL (though it is already set to NULL by default).  So the macro would never be empty whether multithreading is set or not. 
You could also move the  SPI_CONTEXT_CS_GPIOS_INITIALIZE() I think.

That solution still requires a change on all drivers, but overall it will make things simpler (and cleaner in drivers too). What do you think?

**Comment by yashi** [comment]
In addition to the commit message, I'll leave a comment in the macro.
```diff
diff --git a/drivers/spi/spi_context.h b/drivers/spi/spi_context.h
index 1aed41173ee..adeed2ec9f0 100644
--- a/drivers/spi/spi_context.h
+++ b/drivers/spi/spi_context.h
@@ -55,6 +55,18 @@ struct spi_context {
 #endif /* CONFIG_SPI_SLAVE */
 };
 
+
+#if IS_ENABLED(CONFIG_MULTITHREADING)
+#define SPI_CONTEXT_BASE_INIT(_data, _ctx_name)				\
+	._ctx_name.config = NULL,					\
+	SPI_CONTEXT_INIT_LOCK(_data, _ctx_name),			\
+	SPI_CONTEXT_INIT_SYNC(_data, _ctx_name)
+#else
+#define SPI_CONTEXT_BASE_INIT(_data, _ctx_name)				\
+	._ctx_name.config = NULL
+	/* Make compilers happy */
+#endif
+
 #define SPI_CONTEXT_INIT_LOCK(_data, _ctx_name)				\
 	._ctx_name.lock = Z_SEM_INITIALIZER(_data._ctx_name.lock, 0, 1)
 
```

**Comment by tbursztyka** [comment]
@yashi that's exactly what I am proposing yes. Seems like a better solution to me, compared to earlier options. What do you think?

**Comment by bamkrs** [comment]
Are all spi-driver maintainers in the loop of this PR? I think just removing the semaphores isn't the whole story. For example, in the nrfx-spi-drivers there are direct calls to `k_sem_reset` on the sync-semaphore:
https://github.com/zephyrproject-rtos/zephyr/commit/6499cd868da7a804aff8238ba390fcce381b6088

**Comment by scottwcpg** [comment]
@yashi Hi, could you explain the single threaded plus CONFIG_SPI_ASYNC=y use case?  The spi_context.h code still touches the lock and async semaphores that have not been initialized.

**Comment by yashi** [comment]
> @yashi that's exactly what I am proposing yes. Seems like a better solution to me, compared to earlier options. What do you think?

@tbursztyka I'm all good with it. Thank you for your suggestion!

**Comment by yashi** [comment]
@bamkrs Thank for the suggestion.  

- https://github.com/yashi/zephyr/pull/2

My PR is strictly about `context.h`.  I thought it's up to the SPI controller drivers to support `CONFIG_MULTITHREADING=n` or not.  But obviously it's a good point. would you mind creating PR on here at zephyrproject-rtos/zephyr instead of my local one?

**Comment by teburd** [comment]
I'll be really curious to see how this can actually work without semaphores, most drivers rely on the semaphore to block the caller while waiting for the completion event (ISR).

**Comment by yashi** [comment]
@mbolivar-nordic, Would you mind giving me an insight why you initialize `sync_status` in `spi_context_buffers_setup()` in the commit https://github.com/zephyrproject-rtos/zephyr/commit/6c717095b87445a8cf4325d9067f7a3f7b80a370?

I'd like to remove the variable for `CONFIG_MULTITHREADING=n` but it's initialized there.

**Comment by yashi** [comment]
> I'll be really curious to see how this can actually work without semaphores, most drivers rely on the semaphore to block the caller while waiting for the completion event (ISR).

Care to engligten me a bit?

This is my understanding. Under single threaded environment, (obviously) there is only one thread to call SPI API.  The thread call `spi_transceive()` step by step without any other thread interleaving.

Many drivers call `spi_context_wait_for_completion()` at the very end of `_transceive()`, which (undre multi-threaded env.) wait for a `spi_context_complete()` to be called.  But with a single thraed, the completion should be completed by the time `spi_context_wait_for_completion()`is called _unless_ ASYNC_ is used.

Or, does ASYNC work without Multithreading?  Does it work just a single thread with an interrupt?

**Comment by yashi** [comment]
hmm... ASYNC and interrupt usage are different things I suppose.  Thanks @teburd.

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic, Would you mind giving me an insight why you initialize `sync_status` in `spi_context_buffers_setup()` in the commit [6c71709](https://github.com/zephyrproject-rtos/zephyr/commit/6c717095b87445a8cf4325d9067f7a3f7b80a370)?

It's been almost 6 years since I wrote that code, so I don't remember why I chose that particular function. However, it has to get set to 0 somewhere early in the `transceive` callback for every driver, and doing a quick spot-check of a couple of in-tree drivers, spi_context_buffers_setup() is called early in transceive with the context locked, so it seems like a reasonable place to put it. Do you have another suggestion?

**Review by tbursztyka — APPROVED** [review]

**Comment by yashi** [comment]
@mbolivar-nordic Thanks.  That's exactly what I wanted to know.  And, No, I don't have any better places.

**Comment by yashi** [comment]
@tbursztyka Give me a few days.  I'll update `spi_context_wait_for_completion()` and `spi_context_complete()` with `atomic_t`.

**Review by nashif — APPROVED** [review]

**Comment by carlescufi** [comment]
> @tbursztyka Give me a few days. I'll update `spi_context_wait_for_completion()` and `spi_context_complete()` with `atomic_t`.

Should we merge this as-is @yashi or wait for an update?

**Comment by fabiobaltieri** [comment]
@yashi marked as DNM so it falls off the filters, feel free to remove the tag if this can be merged

**Comment by schneider-engineering** [comment]
@yashi we would be interested in this being merged, is this expected to be picked up again?

**Pull request closed without merging**
