### PR TITLE
boards: acrn: Update documentation and remove outdated configurations

### PR DESCRIPTION
**Pull request by finikorg**
Current documentation refer to the very old ACRN release and it makes it almost impossible to reproduce steps.
Update documentation to simplify steps and remove old outdated configuration.

https://builds.zephyrproject.io/zephyr/pr/65681/docs/boards/x86/acrn/doc/index.html

### CODE REVIEW

**Comment by MaureenHelm** [comment]
@jhedberg please take a look

**Comment by jhedberg** [comment]
@finikorg does this need any updating before merging? I'll at least re-trigger CI since it was run almost two months ago the last time.

**Comment by jhedberg** [comment]
@finikorg strangely, I don't see the usual options to re-run the tests. Could you rebase and do it that way? Thanks.

**Comment by finikorg** [comment]
> @finikorg strangely, I don't see the usual options to re-run the tests. Could you rebase and do it that way? Thanks.

rebased

**Review by jhedberg — APPROVED** [review]

**Comment by finikorg** [comment]
@najumon1980 @nashif @tbursztyka Could you review this PR, before moving to HWM v2.

**Pull request closed without merging**
