### PR TITLE
kernel: CONFIG_THREAD_MONITOR thread list and iteration fixes

### LINKED ISSUE #13318: k_thread_foreach api breaks real time semantics
**Describe the bug**
When 'kernel stacks' or 'kernel threads' commands are entered at the command prompt realtime performance is lost.

**To Reproduce**

1) Enable shell, kernel extensions and thread/stack info. Specifically, the following must be defined;
CONFIG_INIT_STACKS, CONFIG_THREAD_MONITOR, CONFIG_THREAD_STACK_INFO
2) Setup short period secondary task which is dependent on external interrupt (e.g. to toggle a pin in response to incoming pin change)
3) Compile (tested on STM32F429 build)
4) At the command prompt type 'kernel stacks' or 'kernel threads'
5) Observe that realtime response of other task is lost.

I think this is due to the k_spin_lock in kernel/thread.c::k_thread_foreach ... would it not be sufficient to just do a k_sched_lock here? Worst consequence would be incorrectly reported threads/stacks for the case that the printing task manipulated one of the, which it's not supposed to do anyway.

**Expected behavior**
Interrupt responding second task should continue to operate correctly.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
Annoyance. Prevents use of kernel threads/kernel stacks commands on a realtime system.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
Linux, Zephyr SDC, 1.3.99, a4e950a276a9d39a5bbe6495d085f78203e13a6c

### PR DESCRIPTION
**Pull request by ghost**
k_thread_foreach() failed to release a lock during iteration. the lock
is now released between callbacks and the API documentation is updated
to clarify the semantics.

The thread list has been changed to use kernel slists, rather than an
ad hoc construct. This simplifies some code and has obvious long-term
maintenance advantages, but breaks the OpenOCD interface.

Fixes: #13318

Signed-off-by: Charles E. Youse <charles.youse@intel.com>

### CODE REVIEW

**Comment by gnuless** [comment]
We might not want to merge this until a patch to OpenOCD is written, post 1.14, I'd imagine.

I'm also a bit concerned about removing the SYS_THREAD_MONITOR_HEAD and SYS_THREAD_MONITOR_NEXT from include/debug/object_tracing.h; I'm not sure if this constitutes part of a public API that needs to be preserved.  Those macros are not easily "rephrased" to use the slist primitives; instead, the [few] places these were referenced from Zephyr itself were rewritten.

**Review by andyross — APPROVED** [review]
Looks good, though I'll fully admit I'm clueless about how the openocd integration works or what it really does (I guess at some point that gets handed to a gdbserver?)

**Review by tyrantlizard77 — APPROVED** [review]
LGTM

I'm not sure what we need to do about OpenOCD.

**Comment by gnuless** [comment]
Out of date.

**Pull request closed without merging**
