### PR TITLE
Remove legacy CoAP implementation

### PR DESCRIPTION
**Pull request by rveerama1**
As we are removing net_app and net_pkt based libraries and applications, CoAP legacy based libraries and apps are moved to socket based implementations. So removing legacy CoAP.

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by rveerama1** [comment]
Fixing sanitycheck findings.

**Review by mike-scott — APPROVED** [review]

**Review by mike-scott — DISMISSED** [review]
This PR should change the coap_sock.h include in include/net/lwm2m.h to coap.h, please.

**Comment by rveerama1** [comment]
> This PR should change the coap_sock.h include in include/net/lwm2m.h to coap.h, please.

Done.

**Comment by sdrsdr** [comment]
One of the HUGE advantages of  net_pkt API is/was the callback on new data. Any plans on implementing such thing on socket based API?

**Comment by jukkar** [comment]
> One of the HUGE advantages of net_pkt API is/was the callback on new data. Any plans on implementing such thing on socket based API?

Could you propose a patch that does that?

**Review by mike-scott — APPROVED** [review]
LGTM.  Thanks for fixing LwM2M.

**Pull request merged**
