### PR TITLE
dts: edtlib: Require properties to have 'required: true/false'

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Review by gmarull — COMMENTED** [review]
In my opinion assuming `required=False` if missing should be enough. What would be useful (if not in place) is to warn about `default + required=True`.

**Comment by mbolivar-nordic** [comment]
I can't find a justification for why in the commit logs; did I miss something? What makes the extra boilerplate worthwhile?

**Comment by galak** [comment]
> I can't find a justification for why in the commit logs; did I miss something? What makes the extra boilerplate worthwhile?

it was an old PR from Ulf that never got merged because of CI failures.  I think it was a cleanup - my guess is that it might be the only property that we infer by its lack of being there, vs explicitly having it set one way or the other.

**Comment by mbolivar-nordic** [comment]
>  I think it was a cleanup - my guess is that it might be the only property that we infer by its lack of being there, vs explicitly having it set one way or the other.

But `enum` and `const` can be missing too, and they have well defined meanings in that case (any value of the type is OK / no constant value).

I'm with @gmarull; why bother with the extra typing if the current way works fine?

**Comment by galak** [comment]
Works for me, will close out this PR.

**Pull request closed without merging**
