### PR TITLE
[RFC] Improved devicetree error reporting macrobatics

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
This PR demonstrates how adding statement expressions to our repertoire of macrobatic tricks can turn inscrutable errors like this:

```
/home/mbolivar/zp/zephyr/samples/hello_world/src/main.c:12:39: error: ‘__device_dts_ord___ORD’ undeclared (first use in this function); did you mean ‘__device_dts_ord_11’?
   12 |         printk("Hello World! %p\n", DEVICE_DT_GET(DT_INVALID_NODE));
      |                                       ^~~~~~~~~~~~~~~~~~~~~~
      |                                       __device_dts_ord_11
```

Into much more helpful errors like this:

```
/home/mbolivar/zp/zephyr/samples/hello_world/src/main.c:12:38: error: static assertion failed: "Invalid devicetree node identifier: _"
   12 |         printk("Hello World! %p\n", DEVICE_DT_GET(DT_INVALID_NODE));
      |                                      ^~~~~~~~~~~~~~
```

Posting as an RFC to see what people think of the approach, with hopes of spurring various DT-derived APIs to adopt it.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
@mbolivar-nordic I like it! A huge improvement to one of the very weak spots of Zephyr - especially for newcomers.

**Comment by gmarull** [comment]
image

**Comment by stephanosio** [comment]
sold

**Comment by keith-zephyr** [comment]
I'm a big fan of the build time failure over the link time failure.  Can you also update `EMUL_DT_GET`?

**Comment by galak** [comment]
+1

**Comment by mbolivar-nordic** [comment]
> I'm a big fan of the build time failure over the link time failure.

@keith-zephyr well, you still get a link error if there's no such device but there is a valid DT node; this approach is good for catching other mistakes, though; see https://github.com/zephyrproject-rtos/zephyr/pull/50055#issuecomment-1240986557. 

> Can you also update `EMUL_DT_GET`?

I will take a look. Probably going to start with the 'real' peripheral APIs since those are the ones I'm familiar with.

**Comment by mbolivar-nordic** [comment]
Shoot, looks like statement expressions aren't as general as I was hoping:

```
/home/mbolivar/zp/zephyr/include/zephyr/device.h:286:32: error: braced-group within expression allowed only inside a function
  286 | #define DEVICE_DT_GET(node_id) ({                                       \
      |                                ^
```

**Comment by tejlmand** [comment]
I sure like the improvement, but knowing we would like to have wider toolchain support and there are users with custom toolchains ( don't remember if those are gcc or clang based, otr even something else ) then for such a core part we should be careful.

We could consider a compiler check to allow for gcc and clang based compilers, and let others keep current behavior.
@evgeniy-paltsev @daor-oti @felipe-iar any thoughts / comments on this ?

**Comment by gmarull** [comment]
> Shoot, looks like statement expressions aren't as general as I was hoping:
> 
> ```
> /home/mbolivar/zp/zephyr/include/zephyr/device.h:286:32: error: braced-group within expression allowed only inside a function
>   286 | #define DEVICE_DT_GET(node_id) ({                                       \
>       |                                ^
> /home/mbolivar/zp/zephyr/drivers/console/uart_console.c:39:9: note: in expansion of macro 'DEVICE_DT_GET'
>    39 |         DEVICE_DT_GET(DT_CHOSEN(zephyr_console));
>       |         ^~~~~~~~~~~~~
> ```
> 
> There's got to be some way to salvage this, though.

Maybe it will be possible on C23? https://thephd.dev/c23-is-coming-here-is-what-is-on-the-menu#n3038---introduce-storage-classes-for-compound-literals

**Comment by bjarki-trackunit** [comment]
If we can solve this, we will no longer need to generate externs for devices created by devicetree
```
({ extern struct device DEVICE_DT_NAME_GET(node_id); \
   struct device *ret = COND_CODE_1(DT_NODE_EXISTS(node_id), (&DEVICE_DT_NAME_GET(node_id)), (NULL)); \
   BUILD_ASSERT(DT_NODE_EXISTS(node_id), "Invalid devicetree node identifier: " STRINGIFY(node_id)); \
   ret; })
```

**Comment by evgeniy-paltsev** [comment]
Tested on ARC platforms - this doesn't work with both GNU and MWDT toolchains :( Error example:

```
In file included from /SCRATCH/arcjenkins/de02-custom-arcdev4/workspace/arcoss_verification/zephyr_verification/sanity_check-3/zephyr/drivers/console/uart_console.c:24:
/SCRATCH/arcjenkins/de02-custom-arcdev4/workspace/arcoss_verification/zephyr_verification/sanity_check-3/zephyr/include/zephyr/device.h:284:1: error: braced-group within expression allowed only inside a function
  284 | ({ struct device *ret = COND_CODE_1(DT_NODE_EXISTS(node_id), (&DEVICE_DT_NAME_GET(node_id)), (NULL)); \
      | ^
/SCRATCH/arcjenkins/de02-custom-arcdev4/workspace/arcoss_verification/zephyr_verification/sanity_check-3/zephyr/drivers/console/uart_console.c:39:9: note: in expansion of macro 'DEVICE_DT_GET'
   39 |         DEVICE_DT_GET(DT_CHOSEN(zephyr_console));
      |         ^~~~~~~~~~~~~
```

Platform: nsim_hs
Test: tests/kernel/sched/schedule_api/kernel.scheduler
Toolchain: Zephyr SDK 0.15.0

**Comment by mbolivar-nordic** [comment]
I've got no ideas to make this foolproof. I was hoping to find a way to `COND_CODE_1(AM_I_INSIDE_A_FUNCTION_RIGHT_NOW, (DO_THIS_PR_CHANGE), (DO_THE_EXISTING_BEHAVIOR))`, but standard C doesn't seem to provide any preprocessor-time facilities for that particular test :\.

**Pull request closed without merging**
