### PR TITLE
manifest: bump hal_nxp revision

### PR DESCRIPTION
**Pull request by jsiverskog**
this revision contains an usb fix that allows
tests/subsys/usb/device/usb.device to pass on lpcxpresso55s69_cpu0.

see https://github.com/zephyrproject-rtos/hal_nxp/pull/315 for more information.

### CODE REVIEW

**Review by danieldegrasse — DISMISSED** [review]
Changes fix the test failure for me, and enable USB DFU mode to work correctly on LPC SOCs

**Comment by mmahadevan108** [comment]
Thanks for the fix. Can you please update `west.yml`

**Comment by jsiverskog** [comment]
> Thanks for the fix. Can you please update `west.yml`

done!

**Comment by jsiverskog** [comment]
@danieldegrasse : done.

**Review by danieldegrasse — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Pull request merged**
