### PR TITLE
ci: build tests based on manifest change using tags

### LINKED ISSUE #61716: Enhance CI to run tests based on module updates.
Currently, there is a manifest workflow that looks for changes to the manifest and adds labels to a PR that indicate changes to a particular module. However, this information doesn't affect tests that are run, and tests are easily missed when they affect modules. For example, updating just the manifest for a module won't cause that module's tests to be run, unless a change also is made to one of that module's support files within the Zephyr repository. Or, for example, changing the mcuboot modules doesn't cause TF-M tests to be rerun, even though the TF-M code directly links to some code within mcuboot.

To improve this, the logic from `manifest.yml` should be copied to (or even better, factored out) the `test_plan.py` script so that information could be used to affect the test plan. One possibility is to run tests containing specific tags for the modules, based on the same logic as the manifest action uses to add labels.

### PR DESCRIPTION
**Pull request by nashif**
- ci: test_plan: add tags based on manifest change

Fixes #61716

### CODE REVIEW

**Comment by d3zd3z** [comment]
This looks like it is doing the right thing. Presumably, we would want to have just the script changes without actually changing a module, but then again, that wouldn't get tested until other changes go in.

**Comment by nashif** [comment]
> This looks like it is doing the right thing. Presumably, we would want to have just the script changes without actually changing a module, but then again, that wouldn't get tested until other changes go in.

unrelated test commits removed

**Review by nordicjm — COMMENTED** [review]
Change looks okay but can't see this part: `manifest: add mcuboot to bootloader group`

**Comment by kartben** [comment]
> Change looks okay but can't see this part: `manifest: add mcuboot to bootloader group`

I think this was the test commit that @nashif had initially to check it worked as expected, and then removed as per https://github.com/zephyrproject-rtos/zephyr/pull/61718#issuecomment-1687186488.

**Review by carlescufi — APPROVED** [review]
LGTM

**Review by nordicjm — APPROVED** [review]

**Review by d3zd3z — APPROVED** [review]
This will be quite helpful. Thanks.

**Pull request merged**
