### PR TITLE
kernel: k_poll: Introduce separate status for cancelled events

### LINKED ISSUE #9032: net/sockets/echo_async crashes after several connections (qemu_x86)
I've experienced an `echo_async` sample crash when I was playing with it on qemu_x86. Actually, it's pretty simple to reproduce, just connect/disconnect a few times with telnet (for me two times is enough). Here's the log:
```
***** Booting Zephyr OS v1.12.0-880-g86b5edc4d *****
Asynchronous TCP echo server waits for connections on port 4242...
Connection #0 from 192.0.2.2 fd=4198848
poll error: 4
Connection #1 from 192.0.2.2 fd=4198848
poll error: 4
***** CPU Page Fault (error code 0x00000000)
Supervisor thread read address 0x00000000
PDE: 0x025 Present, Read-only, User, Execute Enabled
PTE: 0x00 Non-present, Read-only, Supervisor, Execute Enabled
Current thread ID = 0x00402180
eax: 0x00000000, ebx: 0x00401230, ecx: 0x0041521c, edx: 0x0041527c
esi: 0x00000001, edi: 0x0041527c, ebp: 0x0041520c, esp: 0x004151f8
eflags: 0x00000006 cs: 0x0008
call trace:
eip: 0x00015742
     0x00015940 (0x293)
     0x000056fd (0x415254)
     0x00003c5c (0x400340)
     0x000128ed (0x4153e8)
     0x00003e03 (0x0)
Fatal fault in essential thread! Spinning...
```

Didn't have too much time to dive in, but the crash itself takes place within `k_poll` function. Yet it looks that the problem here is that sockets are not being closed. Not sure about the error returned by the `poll` function (`EINTR` doesn't look too scary), but the fact that sockets are not closed is disturbing. Perhaps `net_context` for whatever reason is not notyfing the socket shim about connection being closed, so in result `recv` and `close` are not called?

Nothing fancy in wireshark logs, just two opened and closed connections:
image

### PR DESCRIPTION
**Pull request by pfalcon**
Previously (as introduced in 48fadfe62), if k_poll() waited on a
queue (or subclass like fifo), and wait was cancelled on queue's
side using k_queue_cancel_wait(), k_poll returned -EINTR. But it
did not set event->state field (to anything else but
K_POLL_STATE_NOT_READY), so in case of waiting on multiple queues,
it was not possible to differentiate which of them was cancelled.

This in particular broke detection of network socket EOF conditions
in POSIX poll() implementation.

This situation is now resolved with introduction of explicit
K_POLL_STATE_CANCELLED state, which is now set for cancelled queue
(-EINTR return remains the same).

This change also elaborates docstring for the functions mentioned, to
document this behavior.

Fixes: #9032

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
@Vudentz, some thing just can't be put to rest ;-).

Turned out, your change https://github.com/zephyrproject-rtos/zephyr/commit/48fadfe6232a4520f13da6c54a8dd204f8c5ece2 actually broke POSIX poll() implementation done on top of k_poll(). POSIX semantics is that when EOF happens (and that condition is being signaled with k_fifo_cancel_wait() translates to "read data available" (POLLIN). User tries to read, and discovers that there's no data on this socket no more (EOF). So, it's imperative that cancel_wait() leads to "active" poll state, while you in https://github.com/zephyrproject-rtos/zephyr/commit/48fadfe6232a4520f13da6c54a8dd204f8c5ece2#diff-ec46254d7d7d1ff37f681251c352e3f8L98 set it in this case to K_POLL_STATE_NOT_READY, which is null, non-signaled state. The only hint of cancellation is -EINTR return code, but as may imagine, that doesn't differentiate among multiple fifos.

So, instead of submitting a revert of that commit and go on another spin of that vicious cycle, I did more homework. So, what you need is cancellation to have separate, explicit return code (IIRC, to differentiate of race condition between multiple k_fifo_get callers). What I need is "active" poll state. The solution is thus to introduce a new poll state, which would map to -EINTR return.

And that's what this patch does, and even documents the behavior of funcs more explicitly. Hopefully, this patch finally will put this issue to rest.

**Comment by pfalcon** [comment]
@rlubos : 2nd commit here then fully fixes https://github.com/zephyrproject-rtos/zephyr/issues/9032 . Were your sockets/{echo_client,server} affected? (They use poll(), right?). Feel free to give it a try.

**Comment by rlubos** [comment]
@pfalcon Sorry. I'm on vacation now and don't have a chance to test it. `echo_client` does use poll, but it's pretty straigtforward, so I wouldn't expect any suprises if other samples work fine. Thanks for looking into that btw.

**Comment by pfalcon** [comment]
@rlubos: Ack, thanks for the response, no hurries/worries. Just trying to understand how that issue could go unnoticed for so long (will definitely add echo_async to my usual set of smoke tests).

**Comment by Vudentz** [comment]
@pfalcon LGTM but perhaps we should add a test for the new state then so we ensure the behaviour is not changed again. Btw, I don't see you using the new state, is the code you attempt to fix out of the tree?

**Comment by pfalcon** [comment]
@Vudentz: Indeed, there was no testcase for k_poll returning -EINTR at all. Now added, tests for both -EINTR and K_POLL_STATE_CANCELLED.

**Comment by pfalcon** [comment]
CI issues now fixed.

**Comment by pfalcon** [comment]
@Vudentz, ping. A test was added on your suggestion, this is ready for review. Thanks.

**Review by dcpleung — APPROVED** [review]
Looks good to me.

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by nashif — APPROVED** [review]

**Pull request merged**
