### PR TITLE
shell: add select command

### LINKED ISSUE #10769: shell: "select" command suddenly gone
Following up on the quick discussion on IRC.

So, a user which used both old and new shell would immediately notice the lack of "select" command in the new one. On IRC, I was told that it's not needed, and one can access all commands directly.  I don't what was meant by that, but my interpretation is obvious - it would mean that knowing that there's "stats" command in "net" shell module, I can type "stats" and it would get executed.

Of course, it cannot work like that, because there could be "bt stats", etc. commands. So, I proceeded to check, and of course, "stats" doesn't work:

~~~
uart:~$ stats
stats: command not found
~~~

Instead, I need to type:
~~~
uart:~$ net stats 

Interface 0x00424a20 (Ethernet) [0]
===================================
~~~

Of course, it's alleviated by completion, but:

1. Completion was there in the old shell too.
2. It was possible to use "net stats" in the old shell too.
3. But besides that, there was also "select &lt;module>" command which allowed get rid of typing "net" altogether!

Of course, with possibility no.3 provided, users enjoyed it. And of course, they noticed the regression with the new shell, and submit tickets asking what's up.

### PR DESCRIPTION
**Pull request by jakub-uC**
Added `select` command similar to one available in the legacy shell.

In order for the command to be selected, it must meet the criteria:
 - It is a static command.
 - It is not preceded by a dynamic command.
 - It has at least one subcommand

It means you can select either root command or its subcommands as long as above criteria are met.

If you type `select` you can still use the `tab` button to prompt and autocomplete all available commands.

To unselect the command one must press `ctrl + s`.
You can only select a command if no other command is selected. This prevents ambiguity as to what action should be performed.

Fixes #10769

Signed-off-by: Jakub Rzeszutko <jakub.rzeszutko@nordicsemi.no>

### CODE REVIEW

**Comment by jarz-nordic** [comment]
select

**Comment by jukkar** [comment]
I do not see much point in this select command in new shell. We have tab completion nowadays and it is working well so no need to type much stuff anyway. This code just means more memory consumption without much benefit.

**Comment by jarz-nordic** [comment]
@jukkar : In my opinion it is also not "must be" feature. @pfalcon suggested that the lack of such a command could be a regression compared to the previous solution.

**Comment by jukkar** [comment]
> @jukkar : In my opinion it is also not "must be" feature. @pfalcon suggested that the lack of such a command could be a regression compared to the previous solution.

We have been removing lot of code and APIs from 1.14. We also had the "select" command removed by accident in new shell so I see no harm not introducing it back. My main point is that it adds more memory requirement to shell which is quite large already.

**Review by nashif — CHANGES_REQUESTED** [review]
I do not think we need this and agree with @jukkar, lets keep it simple. This is not a regression. It is also not marked as a bug, we agreed to just mention that change in the release notes.

**Comment by jarz-nordic** [comment]
ok, I do not mind closing it.

**Pull request closed without merging**
