### PR TITLE
dts: bindings: add bg95 power pulse duration

### LINKED ISSUE #64292: dts: bindings: add power pulse duration in bg95 modem cellular
**Is your enhancement proposal related to a problem? Please describe.**
Modem is based on BG95 MiniPCIe hardware, the power pulse duration set by default at 1500ms is sometime not sufficient

**Describe the solution you'd like**
Add the (already existing) power_pulse_duration_ms as an optional parameter by default

**Describe alternatives you've considered**
Patch the quectel,bg95.yaml file

### PR DESCRIPTION
**Pull request by RomainPelletant**
Add power pulse duration as optional parameter for BG95
Fixes #64292

### CODE REVIEW

**Review by rerickson1 — APPROVED** [review]

**Review by bjarki-andreasen — CHANGES_REQUESTED** [review]
If the value 1500ms it not long enough, this needs to be addressed within the drivers, not the devicetree binding. Since you are not using it anywhere upstream, and if you insist on it being a devicetree property, I would recommend you simply create an out-of-tree binding and apply it to your devicetree locally.

**Comment by RomainPelletant** [comment]
@bjarki-trackunit Thank you for your answer.
It is not a problem to target that kind of (custom) issue in the driver directly IMHO, but still in my opinion, the device tree includes custom dependencies based on the effective board and peripherals used so I thought it was the place to set that kind of parameters.
As the modem_cellular is pretty flexible and offers reset, power with their pulse duration parameters I believed that expose them as optional settings could add more flexibility facing custom boards issues.
Please let me know if this PR differs from your vision (mine is closed to that issue :) ) and I close it

**Comment by bjarki-trackunit** [comment]
@RomainPelletant Can you demonstrate that this is a board issue? The time it takes for the modem to respond to the power key is dependent on the firmware and revision of the modem right?

**Comment by RomainPelletant** [comment]
Modem revision & version is what I include in custom boards issues. In the terms a product is released with a specific version and (may) not change (although DFOTA function on some modems).
So no, I cannot demonstrate it is specific to BG95 MiniPCIe revision because it is not related to PCB directly

**Comment by bjarki-trackunit** [comment]
In that case, we need a better compatible, and possibly better driver handling :) We do need to expand the compatible from BG95, since there are variants like M3 which doesn't have a GNSS modem for example, which modem revision, or version rather, are you using?

**Comment by RomainPelletant** [comment]
You are right, it is the M3 model.
If we want the driver to be working out of the box (for BG95 as module), I understand your point of view and this PR is no more relevant.
Besides, the integration is specific to our board and maybe FAQ section is more appropriate for going deeper on this topic.
Thanks for explaining your point of view: it makes more sense to me why is it shall not be upstreamed

**Pull request closed without merging**
