### PR TITLE
Unify soc name

### PR DESCRIPTION
**Pull request by JiafeiPan**
In hal_nxp, MCUX_DEVICE is defined according to CONFIG_SOC, and MCUX_DEVICE is followed by CPU Core name in mcux-sdk, so let's unify with MCUX_DEVICE definition with mcux-sdk.

This PR depends on https://github.com/zephyrproject-rtos/hal_nxp/pull/268

### CODE REVIEW

**Review by carlocaione — DISMISSED** [review]

**Review by povergoing — DISMISSED** [review]

**Comment by JiafeiPan** [comment]
Updated to fix confliction.

**Review by povergoing — DISMISSED** [review]

**Comment by JiafeiPan** [comment]
Rebased.

**Review by carlocaione — DISMISSED** [review]

**Comment by JiafeiPan** [comment]
Rebased.

**Review by dleach02 — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by JiafeiPan** [comment]
The depend on PR of nxp_hal  has been merged, so please approve and merge this one, thanks.

**Review by povergoing — APPROVED** [review]

**Pull request merged**
