### PR TITLE
edtlib: validate compatible properties

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Error out on compatible properties with invalid values. The regular
expression used to validate them matches what's used in dt-schema.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
This is the result of some discussion in https://github.com/zephyrproject-rtos/zephyr/pull/34938.

**Comment by mbolivar-nordic** [comment]
I'm calling this a bugfix since it is turning up an issue in at least one board so far.

**Review by Navin-Sankar — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
```
devicetree error: node '/connector' compatible '96b-lscon-3v3' must match this regular expression: '^[a-zA-Z][a-zA-Z0-9,+\-._]+$'
```

@galak how should we handle this? I think the compatible should probably be changed. You OK with that?

**Comment by galak** [comment]
> @galak how should we handle this? I think the compatible should probably be changed. You OK with that?

Why is this considered a violation?

**Comment by mbolivar-nordic** [comment]
> must match this regular expression: '^[a-zA-Z][a-zA-Z0-9,+\-._]+$'

dt-schema requires a letter as the first character, not a number

**Comment by mbolivar-nordic** [comment]
How about:

- `96b-lscon-3v3` -> `linaro,96b-lscon-3v3`
- `96b-lscon-1v8` -> `linaro,96b-lscon-1v8`

**Comment by mbolivar-nordic** [comment]
Updated with linaro vendor prefixes. I added an entry to the release notes as well.

**Comment by galak** [comment]
> > 
> 
> dt-schema requires a letter as the first character, not a number
> 
> edit: reference: https://github.com/robherring/dt-schema/blob/58dae8bf6e2f704ca75b324239530e7ac7f03f75/schemas/dt-core.yaml#L24

Would like to reach out to RobH if this isn't clearly specified in the devicetree spec (and to update the spec if need be).

**Comment by mbolivar-nordic** [comment]
> Would like to reach out to RobH if this isn't clearly specified in the devicetree spec (and to update the spec if need be).

https://github.com/devicetree-org/devicetree-specification/commit/05a34819e59d57f3a2465d0a1b8148aa98bb7a37

Added by @sjg20

**Comment by mbolivar-nordic** [comment]
I guess the spec itself is just making a recommendation, but since dt-schema is enforcing it, I think it's OK for us to follow along.

**Comment by mbolivar-nordic** [comment]
Hmm, the leading letter actually isn't mentioned there. I'll send a patch.

**Comment by galak** [comment]
> > 
> 
> [devicetree-org/devicetree-specification@05a3481](https://github.com/devicetree-org/devicetree-specification/commit/05a34819e59d57f3a2465d0a1b8148aa98bb7a37)
> 
> Added by @sjg20

I have no issue with us updating edtlib to match dt-schema in this way.  We should just also get the spec to match dt-schema here.  I don't think @sjg20's update covers the case here.

**Comment by galak** [comment]
> Hmm, the leading letter actually isn't mentioned there. I'll send a patch.

thanks

**Review by Mani-Sadhasivam — APPROVED** [review]
I'm Ok with adding `linaro` as the vendor prefix to the `96b-lscon*` compatibles.

**Review by galak — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
> Hmm, the leading letter actually isn't mentioned there. I'll send a patch.

https://www.spinics.net/lists/devicetree-spec/msg00988.html

**Review by trond-snekvik — APPROVED** [review]
Would there be value in checking these against the vendor prefixes file as well?

**Comment by mbolivar-nordic** [comment]
> Would there be value in checking these against the vendor prefixes file as well?

Sure, but not for 2.6. I'll send a follow-up PR instead.

**Comment by mbolivar-nordic** [comment]
> > Would there be value in checking these against the vendor prefixes file as well?
> 
> Sure, but not for 2.6. I'll send a follow-up PR instead.

I opened a draft here so we can discuss further: https://github.com/zephyrproject-rtos/zephyr/pull/35422

**Comment by galak** [comment]
@mbolivar-nordic you looking at the CI failures with this?

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic you looking at the CI failures with this?

Yep, I've been checking once daily and adding commits which fix up the bad compatibles.

**Comment by galak** [comment]
> Yep, I've been checking once daily and adding commits which fix up the bad compatibles.

will merge this once it passed CI.

**Comment by galak** [comment]
@mbolivar-nordic might try this locally:

`./scripts/twister --cmake-only -T samples/hello_world/ -l`

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic might try this locally:

I went a slightly different route, but I can generate zephyr.dts for hello_world for all the boards in the `west boards` output with the latest force push.

Why didn't CI find these errors on previous runs?

**Comment by galak** [comment]
> I went a slightly different route, but I can generate zephyr.dts for hello_world for all the boards in the `west boards` output with the latest force push.
> 
> Why didn't CI find these errors on previous runs?

Not sure, I merged a board rename change a day or two ago, but after that I don't think there would be any other changes that would impact this change.

**Comment by mbolivar-nordic** [comment]
OK, I'm guessing I just mixed up some of the u-blox boards, then, since they were so similar.

**Comment by mbolivar-nordic** [comment]
CI is green no

**Pull request merged**
