### PR TITLE
kernel: posix: implementation of POSIX semaphores

### PR DESCRIPTION
**Pull request by jmtorrespalma**
Initial PR to ask for consensus on several topics regarding general POSIX layer support in Zephyr.

This can be considered more of a RFC rather than a PR, there are a few things that need to be discussed here before putting any more effort:

- Common POSIX stuff: things like struct timespec or O_CREAT are supposed to be defined globally for the whole system, so if POSIX support is wanted, there should be a global header for those symbols.
- Named semaphores: the kernel needs to keep track of named semaphores, and allocate memory for them, so we should decide on which kernel data structure is more suitable for this. I have been thinking on memory pools. However passing kernel pointers to the application (even if same memory space) is not the best idea.
- Configuration: details like maximum number of semaphores in the system I believe that should be up to the application, so I think we should support compilation options for those.
- Behaviour: we need to support the standard, but some details are left to the implementation, such as acceptable names for semaphores, retrieve negative values in sem_getvalue(), etc.
- Extensibility: I'm afraid that if we start using a libc, all of this is going to crash, so have to be careful about this, especially having plans of adding default newlib support.

Related to #1291 and #5667

### CODE REVIEW

**Comment by aescolar-ot** [comment]
@jmtorrespalma : Remember to add to https://github.com/zephyrproject-rtos/zephyr/blob/master/arch/posix/include/posix_cheats.h your new functions so they don't clash with the native ones

**Comment by lpereira** [comment]
@jmtorrespalma I believe there's another PR adding these functions already (#5532); I'm not sure about its status, though; the author seems to have abandoned it.

**Comment by punitvara** [comment]
@lpereira I just updated the PR and resolving review comments

**Comment by jmtorrespalma** [comment]
@lpereira @punitvara 
My fault, didnt't see it before and now there is some duplicated work, however those patches are still very far from a final solution in my view. I'll be happy to review and give pointers though.

However I still believe issues noted in the description should be addressed and aligned, so when adding another POSIX features they can all have a common base and not having to rebase every related PR once #5667 goes through a new review iteration.

**Comment by nashif** [comment]
posix semaphore already implemented.

**Pull request closed without merging**
