### PR TITLE
Bluetooth: controller: split: Fix Tx FIFO, queue, and pool corruption

### LINKED ISSUE #18546: Hard Fault when connecting to BLE device
**Describe the bug**
nRF51822 (CFAC) crashes when connecting to it several times. Android (7.1.1) app connects to device to write (initialize timer) and read data (measurements). After a couple of iterations (connecting, reading the data, disconnecting) Zephyr crashes. It is not always the same number of iterations.

**To Reproduce**
TBA

**Impact**
It is needed to reinitialize the hardware, measurements in RAM are lost - showstopper

**Screenshots or console output**
```
FATAL: ***** HARD FAULT *****
FATAL: r0/a1:  0x00000003  r1/a2:  0x20004630  r2/a3:  0x00000000
FATAL: r3/a4:  0x00000002 r12/ip:  0x000186e3 r14/lr:  0x00002a3f
FATAL:  xpsr:  0x01000011
FATAL: Faulting instruction address (r15/pc): 0x000108be
FATAL: >>> ZEPHYR FATAL ERROR 0: CPU exception
FATAL: Current thread: 0x200015ec (unknown)
[00:04:49.397,247] <err> bt_ctlr_llsw_nordic_lll_conn: assert: 'e' failed
FATAL: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.10.3, west v0.6.0
 - Zephyr v2.0.0-rc1 (4524035bc8d5e8eb892bccc1ce9547b09e9c7f52)

**Additional context**
TBA

### PR DESCRIPTION
**Pull request by cvinayak**
Fix the Tx FIFO, queue and pool corruption due to missing
release of link object to Tx link pool and hence missing
reset of the per connection initially allocated Tx link
free pointer.

The bug caused Tx PDUs and associated memory to be lost
leading to missing L2CAP segment transmissions. With lost
control PDU buffers, ULL would stall processing Done events
also leading to controller asserts.

Fixes #18546.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@ChristianHirsch Please verify this fix for #18546, and leave your comments. Thanks in advance.

**Review by mtpr-ot — APPROVED** [review]
This PR **does in fact solve** my TX link pool corruption problem! Good work.
All other integration tests pass as well.

**Comment by cvinayak** [comment]
> 
> 
> This PR **does in fact solve** my TX link pool corruption problem! Good work.
> All other integration tests pass as well.

Thanks for testing.

**Comment by ChristianHirsch** [comment]
@cvinayak I tested it for over an hour, had many connect/disconnect cycles and no crashes. Seems to work, thank's for fixing!

**Comment by cvinayak** [comment]
@ChristianHirsch Thank you. One last question, you tested on nRF51 and/or nRF52?

**Comment by ChristianHirsch** [comment]
@cvinayak I tested it on nRF51.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> @cvinayak I tested it for over an hour, had many connect/disconnect cycles and no crashes. Seems to work, thank's for fixing!

Thank you for testing @ChristianHirsch

**Comment by carlescufi** [comment]
Also tested locally and verified the issue is gone.

**Comment by paulgavrikov** [comment]
Will this be backported to 1.14?

**Comment by aescolar** [comment]
@paulgavrikov Nope. The split link layer is not supported in 1.14. And this is a fix for the split link layer

**Pull request merged**
