### PR TITLE
scripts: Add "the the" as a common typo in spellchecker

### PR DESCRIPTION
**Pull request by kartben**
Somehow this is seems to be a very common typo. Adding it to spelling.txt
 to catch it as part of compliance check.

### CODE REVIEW

**Review by fabiobaltieri — DISMISSED** [review]

**Review by MaureenHelm — DISMISSED** [review]

**Comment by kartben** [comment]
@fabiobaltieri I would add #zephyr-keep-sorted-* but the list is not sorted at the moment, sigh. Thoughts?

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri I would add #zephyr-keep-sorted-* but the list is not sorted at the moment, sigh. Thoughts?

Do it!!!

**Review by rerickson1 — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]
👍

**Comment by nashif** [comment]
You probably want to sync this with https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/spelling.txt?h=v6.7-rc1 and keep the sorting compatible

**Review by rerickson1 — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by pdgendt** [comment]
I think the `the the` commit was accidentally removed in the sorting commit, as it isn't in the list anymore.

**Comment by kartben** [comment]
> I think the `the the` commit was accidentally removed in the sorting commit, as it isn't in the list anymore.

Wow, thanks!

**Comment by kartben** [comment]
OK I think I will just drop the "keep sorted" thing (we hardly ever touch this file, so very little risk of conflicts and whatnot), synchronize with Linux kernel, and add "the the"

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
```console
$ git grep "the the " | wc -l
26
```

https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html :-)

**Review by nashif — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]

**Pull request merged**
