### PR TITLE
boards: stm32: Extend stm32f746g_disco board with Arduino header

### PR DESCRIPTION
**Pull request by Marco-Peter**
Adding GPIO mapping for Arduino connector.

Signed-off-by: Marco Peter <marco@peter-net.ch>

### CODE REVIEW

**Review by FRASTM — APPROVED** [review]
checked with STM32F746G-DISCO MB1191 schematics

**Review by erwango — CHANGES_REQUESTED** [review]
Please follow scheme used in other STM32 based board and move arduino header to dedicated arduino_r3_connector.dtsi file

**Comment by Marco-Peter** [comment]
Used nucleo_l452re as example.

**Comment by erwango** [comment]
> Used nucleo_l452re as example.

Well, no luck ;-). I'll fix it

**Review by erwango — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
