### PR TITLE
Add die_temp_polling support for nRF51-DK and nRF52840-DK

### PR DESCRIPTION
**Pull request by yamaoku-009**
Adding die-temp0 aliases for nrf51822 and nrf52840.
The die_temp_polling sample uses this alias
This PR verified with nRF51-DK and nRF52840-DK

### CODE REVIEW

**Review by mbolivar-nordic — COMMENTED** [review]
Hello @yamaoku-009 and thank you for your patch. Personally I am not sure if we should be adding these aliases to the SoC .dtsi files for just a couple of the Nordic SoCs, since other SoCs may support this too. To provide this feature at SoC level, I think it would be better to manage all supported Nordic SoCs.

Would you be willing to add support for your sample to the specific boards you have tested, by adding the appropriate `samples/sensor/die_temp_polling/boards/*.overlay` files?

cc @anangl

**Comment by yamaoku-009** [comment]
I fixed it as pointed out in the review.

**Review by mbolivar-nordic — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
@yamaoku-009 I was going to merge this PR, but I noticed there are some failed compliance checks. Could you please fix them?

**Comment by yamaoku-009** [comment]
fixed it.

**Review by anangl — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
