### PR TITLE
modules: tf-m: fix git clone during build

### LINKED ISSUE #76090: TF-M: builds download source from external git repository
**Describe the bug**

Since the update to [TFM v2.1.0](https://github.com/zephyrproject-rtos/trusted-firmware-m/pull/105), any builds of TF-M are cloning down sources from this repo: https://github.com/ARM-software/CMSIS_6

Offending commit: https://github.com/zephyrproject-rtos/trusted-firmware-m/commit/3d54aca3851590bf5ecf5f52f361b390c925e257

**To Reproduce**

`west build -b nrf9161dk/nrf9161/ns zephyr/samples/hello_world/ -p`
Observe:
```
...
-- Build files have been written to: /home/jordan/code/zephyr/build/tfm/lib/ext/cmsis-subbuild
[1/9] Creating directories for 'cmsis-populate'
[1/9] Performing download step (git clone) for 'cmsis-populate'
Cloning into 'cmsis-src'...
remote: Enumerating objects: 28525, done.
remote: Counting objects: 100% (3662/3662), done.
remote: Compressing objects: 100% (977/977), done.
remote: Total 28525 (delta 3071), reused 3002 (delta 2624), pack-reused 24863
Receiving objects: 100% (28525/28525), 39.74 MiB | 5.76 MiB/s, done.
Resolving deltas: 100% (21001/21001), done.
HEAD is now at d0c460c1 CMSIS-Core(M): Add Cortex-M52 support : add core_m52.h
[2/9] Performing update step for 'cmsis-populate'
...
```

**Expected behavior**

Builds should not be pulling down sources from the internet.
Builds should complete regardless of internet connectivity state.

**Impact**

"Untrusted" (Not zephyrproject) source being pulled down from the internet on each build.
Unable to build TF-M applications without an internet connection.
40MB download for every TF-M build in CI.
Feels like it violates some sort of Zephyr guideline, or should.

**Environment (please complete the following information):**

```
~/code/zephyr/zephyr$ git describe
v3.7.0-rc3-73-gac52bd629d7
```

### PR DESCRIPTION
**Pull request by tomi-font**
As of v2.1.0 TF-M has updated to CMSIS v6 and switched from hosting the sources to depending on the upstream repository, cloning it at build time.

To prevent a download from happening during the build, CMSIS v6 sources are pushed to Zephyr's fork of TF-M and the `CMSIS_PATH` CMake variable is set to point to them.

Fixes #76090.

### CODE REVIEW

**Review by Vge0rge — DISMISSED** [review]

**Review by valeriosetti — DISMISSED** [review]

**Review by ithinuel — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Module PR: https://github.com/zephyrproject-rtos/trusted-firmware-m/pull/109

**Review by cfriedt — DISMISSED** [review]

**Review by dkalowsk — DISMISSED** [review]

**Review by d3zd3z — DISMISSED** [review]
No objections to pulling it this way from the TSC.

**Comment by aescolar** [comment]
Added dnm until the module PR is merged, and this PR manifest points to a commit in the module and not PR

**Comment by aescolar** [comment]
Thanks @tomi-font,  the module PR has been merged. Please update the manifest pointer.

**Comment by tomi-font** [comment]
Do we also plan on forking the CMSIS v6 repo for after the release?

**Review by valeriosetti — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by ithinuel — APPROVED** [review]

**Pull request merged**
