### PR TITLE
Rename shadow variables (part 2) and partially enable -Wshadow

### PR DESCRIPTION
**Pull request by dcpleung**
Here are a few more commits on renaming shadow variables, and also partially enable -Wshadow (see last commit).

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]
mcumgr OK

**Review by carlocaione — APPROVED** [review]
Ok for the RPMSg backend

**Review by carlescufi — APPROVED** [review]

**Comment by martinjaeger** [comment]
Would have been nice to ask @henrikbrixandersen for review of the CAN related commit. 505c17ed7b11f10b643169510ef314a1315d9a5f is not really ideal.

**Comment by nashif** [comment]
IMO this should have been marked as a treewide change to get more attention and awareness.

**Pull request merged**
