### PR TITLE
devicetree: add `DT_ENUM_HAS_VALUE`

### PR DESCRIPTION
**Pull request by JordanYates**
Add a macro for checking if an enumeration matches a given value.
This enables code to directly check whether a string enumeration is a
specific value, without needing to construct an intermediate variable,
and without checking against a index value which may change.

```
/* Enables this */
if (DT_INST_ENUM_HAS_VALUE(0, power_amplifier_output, rfo_hp)) {}
/* Instead of this */
if (DT_INST_ENUM_IDX(0, power_amplifier_output) == 0) {}
```

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

### CODE REVIEW

**Comment by KloudJack** [comment]
Maybe we should update comparable usages of `DT_ENUM` and variants that would be improved by this PR as well.

Just to name a few: 
 
- boards/common/actinius/actinius_board_common.c
- drivers/dac/dac_sam0.c
- drivers/lora/sx127x.c
- drivers/memc/memc_stm32.c
- drivers/pinctrl/pinctrl_stm32.c
- drivers/regulator/regulator_npm6001.c
- drivers/sensor/bh1750/bh1750.c
- drivers/sensor/mcp970x/mcp970x.c
- drivers/usb/device/usb_dc_sam_usbc.c
- soc/riscv/riscv-privilege/telink_b91/soc.c

**Review by galak — DISMISSED** [review]
Can we do something like
```
if (DT_INST_ENUM_IDX(0, power_amplifier_output) == DT_INST_ENUM_CONST(0, power_amplifier_output, rfo_hp) {}
```

That way we aren't embedded the comparison logic into the macro.

**Comment by JordanYates** [comment]
> Can we do something like
> 
> ```
> if (DT_INST_ENUM_IDX(0, power_amplifier_output) == DT_INST_ENUM_CONST(0, power_amplifier_output, rfo_hp) {}
> ```
> 
> That way we aren't embedded the comparison logic into the macro.

Do you have a more specific concern? The use of `IS_ENABLED` for comparison is quite common in `devicetree.h`.
I don't doubt that it could be done as you suggested, but it is much more verbose in code, and would require many more defines in `devicetree_generated.h`.

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
No matter what, either macros.bnf of the list of prop-suf values at the top of devicetree.h need updating.

Will consider the rest of the PR in a separate review

**Comment by mbolivar-nordic** [comment]
> The use of `IS_ENABLED` for comparison is quite common in `devicetree.h`.

I agree with @JordanYates on this. The API as proposed seems fine to me unless @galak has a specific concern.

**Comment by JordanYates** [comment]
Property documented in the `prop-suf` section at the top of `devicetree.h`.
Added the `_EXISTS` postfix to the generated define to be consistent with other defines that are either `1` or don't exist.

**Review by mbolivar-nordic — APPROVED** [review]
OK for me

**Comment by mbolivar-nordic** [comment]
@galak ping

**Review by gmarull — APPROVED** [review]

**Pull request merged**
