### PR TITLE
arch: riscv: make userspace depends on toolchain support TLS

### LINKED ISSUE #65860: riscv: cross-compile build fail with CONFIG_TEST_USERSPACE
**Describe the bug**

When ZEPHYR_TOOLCHAIN_VARIANT=cross-compile and CONFIG_TEST_USERSPACE=y, a Kconfig dependency warning arises between CONFIG_PMP and CONFIG_THREAD_LOCAL_STORAGE.

**To Reproduce**

1. `$ source zephyr-env.sh`
2. `$ export ZEPHYR_TOOLCHAIN_VARIANT=cross-compile`
3. If use Andes toolchain
    `$ export CROSS_COMPILE=~/nds-gnu-toolchain/nds32le-elf-newlib-v5/bin/riscv32-elf-`
    or you can use zephyr-sdk to reproduce this error
    `$ export CROSS_COMPILE=~/zephyr-sdk-0.16.1/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-`
5. `$ cd tests/kernel/common`
6. `$ cmake -B build -DBOARD=adp_xc7k_ae350`
7. See error

**Impact**

RISC-V PMP always selects THREAD_LOCAL_STORAGE if CONFIG_USERSPACE is enabled, but the cross-toolchain may not support TLS (.e.q. old version of Andes [nds-gnu-toolchain](https://github.com/andestech/nds-gnu-toolchain))

**Logs and console output**
```
...
warning: THREAD_LOCAL_STORAGE (defined at kernel/Kconfig:1251) has direct dependencies ARCH_HAS_THREAD_LOCAL_STORAGE && TOOLCHAIN_SUPPORTS_THREAD_LOCAL_STORAGE with value n, but is currently being y-selected by the following symbols:
 - RISCV_PMP (defined at arch/riscv/Kconfig:206), with value y, direct dependencies RISCV (value: y), and select condition USERSPACE && RISCV (value: y)

error: Aborting due to Kconfig warnings
...
``` 

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Toolchain: Andes [nds-gnu-toolchain](https://github.com/andestech/nds-gnu-toolchain), please follow the [README](https://github.com/andestech/nds-gnu-toolchain#readme) to build the toolchain.
 Or you can use zephyr-sdk with ZEPHYR_TOOLCHAIN_VARIANT=cross-compile to reproduce this error.
 - Commit SHA or Version used: latest main branch a51bd53cef

### PR DESCRIPTION
**Pull request by jimmyzhe**
When ZEPHYR_TOOLCHAIN_VARIANT=cross-compile and CONFIG_TEST_USERSPACE=y, a Kconfig dependency warning arises between CONFIG_PMP and CONFIG_THREAD_LOCAL_STORAGE.
However, not all RISC-V cross-toolchains support TLS (e.q. [old version of Andes toolchain](https://github.com/andestech/nds-gnu-toolchain)). 
Therefore, make RISC-V select ARCH_HAS_USERSPACE only if the toolchain supports TLS.

Fixes #65860

### CODE REVIEW

**Comment by fkokosinski** [comment]
Hi @jimmyzhe! Could you provide steps to reproduce the warning you've mentioned, and could you paste the warning itself here? A bug report/issue would also be welcome. Thanks!

**Comment by jimmyzhe** [comment]
Ok, I wrote the reproduction steps and the warning message in issue #65860. thanks.

**Comment by jimmyzhe** [comment]
I see, that might seem a bit unconventional.

How about providing a RISC-V userspace without relying on TLS?
Currently, TLS is used to handle [arch_is_user_context()](https://github.com/zephyrproject-rtos/zephyr/blob/88425fe3bba191162df4ab798aad4f0938d079a7/include/zephyr/arch/riscv/syscall.h#L161C39-L161C39) in RISC-V userspace and it is clean and efficient code for handling this function.
Perhaps we could provide an alternative implementation, similar to how the xtensa architecture does ([zephyr/include/zephyr/arch/xtensa/syscall.h](https://github.com/zephyrproject-rtos/zephyr/blob/88425fe3bba191162df4ab798aad4f0938d079a7/include/zephyr/arch/xtensa/syscall.h#L202)).

I think the implementation of [arch_is_user_context()](https://github.com/zephyrproject-rtos/zephyr/blob/2ddd73feafd3316af2c547c34d6969bea637d5c6/include/zephyr/arch/riscv/syscall.h#L172) in zephyr-v3.1.0 maybe a good solution for RISC-V cross-toolchain without TLS.
(Execute "csrr t0, mscratch" to trigger an exception, then decode $mepc and update $t0 in isr.S)

And the ["select THREAD_LOCAL_STORAGE"](https://github.com/zephyrproject-rtos/zephyr/blob/88425fe3bba191162df4ab798aad4f0938d079a7/arch/riscv/Kconfig#L216) can be modified to "imply THREAD_LOCAL_STORAGE" based on toolchain supports TLS.

**Comment by jimmyzhe** [comment]
Hi @npitre , thank you for your reply.

The latest Andes toolchain (ast-v5-3-0) supports TLS and it is the user's responsibility to set `CONFIG_TOOLCHAIN_CROSS_COMPILE_SUPPORTS_THREAD_LOCAL_STORAGE`.

However, for those older Andes toolchains without TLS, these toolchains still support Zephyr's other features, but `CONFIG_THREAD_LOCAL_STORAGE` and `CONFIG_USERSPACE` should not be selected when `CONFIG_TEST_USERSPACE` is enabled .

Making RISC-V userspace support both TLS and no-TLS implementation can solve toolchain dependency problem, although it makes generic code fragmented and hard to maintain.

I am not sure which solution is more proper (filtering out `ARCH_HAS_USERSPACE` / adding userspace without TLS implementation), if or both solutions are inappropriate.

**Comment by fkokosinski** [comment]
> The latest Andes toolchain (ast-v5-3-0) supports TLS and it is the user's responsibility to set `CONFIG_TOOLCHAIN_CROSS_COMPILE_SUPPORTS_THREAD_LOCAL_STORAGE`.

This sounds like Andes's toolchain needs a separate entry in `cmake/toolchain`. See: espressif.

> However, for those older Andes toolchains without TLS

Is there a case when the user is forced to use the older toolchain from Andes, instead of using the current one that supports TLS?

**Pull request closed without merging**
