### PR TITLE
twister: add console harness support for ztest

### PR DESCRIPTION
**Pull request by ghost**
Tests may need to be verified both in ztest and console, that could
be confusing when selecting the harness.
As most tests are written in ztest, so add console support for ztest
and configure to use ztest harness directly.
Also add some judgements to make sure that ztest and console are
verified at the same time, and if there are failures, we can distinguish
them in results.

Signed-off-by: Guo Lixin <lixinx.guo@intel.com>

### CODE REVIEW

**Comment by LixinGuoX** [comment]
CI failed due to blocked by #45849

**Comment by LixinGuoX** [comment]
With this patch, if ztest verified success but console failed, we can see log as below:
```
...
DEBUG   - QEMU (522320): TESTSUITE test_log_syst succeeded
DEBUG   - QEMU (522320): ===================================================================
DEBUG   - QEMU (522320): RunID: f80eec6dbd85b65592cb9275ab599ab0
DEBUG   - QEMU (522320): PROJECT EXECUTION SUCCESSFUL
DEBUG   - QEMU (522320) complete (failed) after 2.0957398414611816 seconds
DEBUG   - No timeout, return code from QEMU (None): 0
DEBUG   - return code from QEMU (None): 0
DEBUG   - run status: qemu_x86/tests/subsys/logging/log_syst/logging.log_syst.mipi_syst failed
INFO    - 2/2 qemu_x86                  tests/subsys/logging/log_syst/logging.log_syst.mipi_syst FAILED Console Failed (qemu 2.096s)
ERROR   - see: /home/zephyrproject/zephyr/twister-out/qemu_x86/tests/subsys/logging/log_syst/logging.log_syst.mipi_syst/handler.log
```

**Comment by PerMac** [comment]
I guess I am missing something, but why you would need both of this options? what would be a use case for it? E.g. why a message (or its meaningful parts) which is supposed to be check with console regex cannot be verified by ztest itself? So instead of verifying output on serial with additional regex (the serial has to work anyway to get ztest output), why not verifying it internally, with zassert, and making it a part of a test case?

**Comment by LixinGuoX** [comment]
> I guess I am missing something, but why you would need both of this options? what would be a use case for it? E.g. why a message (or its meaningful parts) which is supposed to be check with console regex cannot be verified by ztest itself? So instead of verifying output on serial with additional regex (the serial has to work anyway to get ztest output), why not verifying it internally, with zassert, and making it a part of a test case?

Hi, I agree with you that it's better to verify it by ztest internally.  As I can find, there is only one case(`tests/subsys/debug/coredump/coredump_backends`) needs both ztest and console, that could be a special one. It seems ok to verify some return values in zassert, and it also request to verify the dumped log  which I think is reasonable. I know we can catch fatal errors in thread level but I am not sure if there is a way to verify the dumped information.

**Review by hakehuang — DISMISSED** [review]

**Comment by hunterhu3000** [comment]
@MaureenHelm As Anas is on holiday, could you please help to review? Thanks

**Comment by yperess** [comment]
I'm very interested in this feature. We have a lot of features in the chromium EC that we'd like to have tests for using ztest. A category of these are console commands which are used for debugging. We'd like to be able to assert on the output of these in order to make sure that the right information is being displayed to developers.

As an example (a very simple one). We have a battery status command where the developer can get the current status, while we have tests to make sure that the status is correct, we also want to make sure that the right information is printed to the developer.

**Review by yperess — CHANGES_REQUESTED** [review]
Can you migrate one of the existing tests that use `console` over to use ztest so we can see this working?

**Comment by henrikbrixandersen** [comment]
@yperess Couldn’t you use a stub shell backend for that? Execute the shell command and verify its output in the shell stub?

**Comment by enjiamai** [comment]
Hi @yperess , @henrikbrixandersen , I would close this PR because @LixinGuoX is no longer working on this. Please feel free to continue on this.

**Pull request closed without merging**
