### PR TITLE
net: l2: openthread: Add config option to enable OpenThread ref. device

### PR DESCRIPTION
**Pull request by edmont**
Add the option to enable Thread Certification reference device support in OpenThread stack.

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
Looks good but please update OpenThread revision in the `west.yml` with a PR reference from OpenThread repository (`pull/14/head`). Also note, that due to Zephyr feature freeze, this PR might be delayed.

**Review by rlubos — APPROVED** [review]
LGTM

**Comment by rlubos** [comment]
DNM until SHA is updated.

**Comment by edmont** [comment]
@rlubos OT revision is updated now.

**Comment by rlubos** [comment]
Thanks

**Review by jukkar — APPROVED** [review]

**Pull request merged**
