### PR TITLE
drivers: can: Fix sample point calculation

### PR DESCRIPTION
**Pull request by talih0**
Signed-off-by: Andriy Gelman <andriy.gelman@gmail.com>

### CODE REVIEW

**Comment by alexanderwachter** [comment]
This change does not pass the test:
west build -b native_posix zephyr/tests/drivers/can/timing -- -DCONF_FILE="prj_loopback.conf"

**Comment by alexanderwachter** [comment]
Seems that the tescase is wrong. When delta is zero, the z_assert within does not work.
IMO z_assert within is wrong...

**Comment by alexanderwachter** [comment]
#32295 fixes the zassert_within()

**Comment by alexanderwachter** [comment]
@talih0 Thanks for your fix!

**Review by alexanderwachter — APPROVED** [review]

**Review by martinjaeger — CHANGES_REQUESTED** [review]
Thanks for the fix. I agree that `assert_within` needs an update.

@talih0 please add an additional line with further explanations to the commit message to pass the CI. Will approve afterwards.

**Comment by talih0** [comment]
> Thanks for the fix. I agree that `assert_within` needs an update.
> 
> @talih0 please add an additional line with further explanations to the commit message to pass the CI. Will approve afterwards.

Thanks @alexanderwachter @martinjaeger
I've updated the commit message.

**Review by martinjaeger — APPROVED** [review]

**Comment by alexanderwachter** [comment]
Can you rebase? The within assert is fixed.

**Pull request merged**
