### PR TITLE
fs/NVS: hardening against bad close_ate offset value

### LINKED ISSUE #34382: fs/nvs: if closing ATE has to high offset NVS iterates up to the end of flash.
**Describe the bug**
If closing ate is valid (crc is ok) and close_ate.offset
has not allowed value GC will performed flash read above
NVS partition.

**Environment (please complete the following information):**
 - https://github.com/zephyrproject-rtos/zephyr/commit/e3a25b3b3a141560d9d6c41121ab598e07a431c4

### PR DESCRIPTION
**Pull request by nvlsianpu**
1)
If closing ate is valid (crc is ok) and close_ate.offset
has not allowed value GC can't be performed straight forward.
Such sector might be treated as to by recovery first as it might
be remains after a disturbed nvs write.

2)
For a sector it is possible that close_ate.offset == (fs->sector_size - ate_size) as
the results of closing the sector while it contained only corrupted
written data.
It is possible corner case, and such sector should be treated as empty
by GC.

fixes #34382

### CODE REVIEW

**Comment by nvlsianpu** [comment]
This is part of #33947 patch decided to contribute stand-alone/

**Comment by Laczen** [comment]
> If closing ate is valid (crc is ok) and close_ate.offset
> has not allowed value GC can't be performed straight forward.
> Such sector might be treated as to by recovery first as it might
> be remains after a disturbed nvs write.
>
I have been thinking about this one also. Maybe it would be better to evaluate the ATE based on both crc and offset (and introduce a routine for this). This would also protect against a data ATE that has a valid crc but a invalid offset. If a invalid close_ate is found it should first check if it can find a empty ATE and start recovery from that ATE.

> 
> For a sector it is possible that close_ate.offset == stop_addr as
> the results of closing the sector while it contained only corrupted
> written data.
> It is possible corner case, and such sector should be treated as empty
> by GC.
> 
> fixes #34382

This corner case might also need some further investigation. Normally the stop_addr does not belong to the same sector so it could not be that these are equal. What might be possible (but I would need to re-study the code) is that while searching for an empty ATE (for a badly closed sector) it goes over the sector boundary and tries to find an empty ATE in the previous sector while it should stop at the sector boundary. When all goes right it should only be possible to go to a previous sector by increasing ATE location.

**Review by Laczen — CHANGES_REQUESTED** [review]
`close_ate.offset =  stop_addr` is a valid condition for a one record sector. Closing a sector while containing no valid data does not result in this condition.

**Comment by nvlsianpu** [comment]
> close_ate.offset = stop_addr is a valid condition for a one record sector.

In NVS instance object ate write offset (`fs->ate_wra`) points on address where we can write incoming ATE (well visible in `nvs_flash_ate_wrt()`). In the close operation value from `fs->ate_wra` is decremented befor being write as `close_ate.offset`, so the offset will point to the last valid data ATE.

.> Closing a sector while containing no valid data does not result in this condition.

No, sector might be closed with such offset as well if the first ATE field has erased value. This is
sector ending which causes this issue (close_ate is at 0xF6FF8 address).
image

And of course, this is exactly for this specific

**Comment by Laczen** [comment]
> > close_ate.offset = stop_addr is a valid condition for a one record sector.
> 
> In NVS instance object ate write offset (`fs->ate_wra`) points on address where we can write incoming ATE (well visible in `nvs_flash_ate_wrt()`). In the close operation value from `fs->ate_wra` is decremented befor being write as `close_ate.offset`, so the offset will point to the last valid data ATE.
> 
stop_addr is just before the sector_close ATE, so a `close_ate.offset ==stop_addr` is a valid condition.

**Comment by Laczen** [comment]
> > Closing a sector while containing no valid data does not result in this condition.
> 
> No, sector might be closed with such offset as well if the first ATE field has erased value. This is
> sector ending which causes this issue (close_ate is at 0xF6FF8 address).
> image
> 
> And of course, this is exactly for this specific

This is an unclosed sector, what would close it (there is still place for an ATE) ?

**Comment by nvlsianpu** [comment]
NVS treats this sector as filled up to 0xF6FDF. To trigger close operation just need to request nvs_write with more than 16 bytes of data.

**Comment by Laczen** [comment]
> NVS treats this sector as filled up to 0xF6FDF. To trigger close operation just need to request nvs_write with more than 16 bytes of data.

Ok, but then the close_ate.offset that is written would be sector_size - ate_size (the address of the close_ate), this is not equal to stop_addr.

**Comment by nvlsianpu** [comment]
^^ right, will correct that. I mixed stop_addr with gc_addr.

**Comment by nvlsianpu** [comment]
superseded by #34512

**Pull request closed without merging**
