### PR TITLE
style: add clang-format file for simple code formatting

### PR DESCRIPTION
**Pull request by locomuco**

### CODE REVIEW

**Comment by pfalcon** [comment]
Perhaps, it would be useful to add to commit message info what clang-format is, and how to use it?

**Review by galak — APPROVED** [review]

**Comment by nashif** [comment]
just tested with uncrustify vs clang-format, and they do conflicting operations. See commit 268fa152f2ec82855b5841b74cb4c9f29e9f43dc which adds uncrustify, maybe more configuration options for clang-format are needed

**Comment by locomuco** [comment]
@nashif I'll check that, didn't know of uncrustify, thanks for pointing me there

**Comment by locomuco** [comment]
closed in favor of using uncrustify over clang-format

**Pull request closed without merging**
