### PR TITLE
drivers: flash: mcux: Avoid locking when not threaded

### LINKED ISSUE #13433: Error when rebooting the frdm_k64f board
Hello, I have a question, if anyone can help me I will be very happy. I have an application on zephyr, that downloads an image and saves it in flash area 1. I use the last mcuboot and the board is frdm_k64f. When I rebooted happens that error bellow:

```
[00:00:00.004,948] <inf> mcuboot: Starting bootloader
[00:00:00.010,967] <inf> mcuboot: Image 0: magic=good, copy_done=0x3, image_ok=0x1
[00:00:00.018,793] <inf> mcuboot: Scratch: magic=unset, copy_done=0x5b, image_ok=0x3
[00:00:00.016,952] <inf> mcuboot: Boot source: slot 0
[00:00:00.014,445] <inf> mcuboot: Swap type: test
***** BUS FAULT *****
  Imprecise data bus error
***** Hardware exception *****
Current thread ID = 0x00000000
Faulting instruction address = 0x3ebe
```
I don't know why it happens.
So, I used the git bisect to find where started the problem, and the commit is:

```
commit dc0713a706e7e2898c172c6c0965b1b784859841
Author: Andy Ross <andrew.j.ross@intel.com>
Date:   Thu Jul 5 12:50:41 2018 -0700

    kernel: Cleanup. Remove redundant test when calling _Swap()
    
    _Swap() must already handle the case where _get_next_ready_thread() is
    the same as _current.
    
    Signed-off-by: Andy Ross <andrew.j.ross@intel.com>
```
Unfortunately, I don't know how to solve it.

### PR DESCRIPTION
**Pull request by mike-scott**
When using CONFIG_MULTITHREADING=n, the semaphore primitives are
non-functional and useless. Remove their usage when this option is
enabled.

Based on similar commit for nRF:
https://github.com/zephyrproject-rtos/zephyr/commit/408ea1464b254972f00469cad4f23c078c2857d4

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/13433

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
@MaureenHelm This was your recommended fix for K64F and mcuboot re: flash driver using semaphores when CONFIG_MULTITHREADED=n

Let me know if it needs changes.

**Comment by d3zd3z** [comment]
I've tested this with MCUboot, and it fixes the problem there.

**Review by d3zd3z — APPROVED** [review]
LGTM

**Review by galak — COMMENTED** [review]
Seems like these should optimize away rather than having to add such ifdef's for every bit of code that uses a semaphore.

**Comment by d3zd3z** [comment]
I agree @galak, I think this should be fixed in the semaphore code, not every random place that we find something trying to lock.

It is a little complicated, because our core API only has semaphores, and not some kind of mutex, so we can't tell if a use is using it as a lock, or for some kind of wakeup. Realistically, use of a semaphore should be a compile error without multithreading, and use of locks should compile to nothing.

Remember, although mutexes can be simulated with semaphores, they aren't the same thing.

**Review by carlescufi — APPROVED** [review]

**Comment by aescolar** [comment]
@mike-scott Nothing has happened for quite a while in this PR. Is there some plan to continue with it? If not would you consider closing it?

**Comment by d3zd3z** [comment]
Any ideas on how to solve this? There isn't an easy way to optimize these out as semaphores, because it depends on how they are being used. When used for locking, they can just go away with no multithreading. But, if being used for wakeups or counting, they should probably error (or perhaps even be a compilation error).

**Comment by nashif** [comment]
stale, closing. Reopen when there are updates...

**Pull request closed without merging**
