### PR TITLE
samples: shell: integrate fs into shell_module

### PR DESCRIPTION
**Pull request by pabigot**
If this is the go-to application for shell work, it should support the filesystem shell interface too.

Motivation for this is simplifying testing and use of the proposed filesystem backend in #27486, but also moving toward support for all file system commands in one application, when the modules are enabled.

TBD whether the existing `samples/subsys/shell/fs` should be removed, and whether all of the boards it supports need to be present in the shell module.  If it goes the documentation on supporting filesystems on posix would likely disappear, unless it's integrated into the shell test (which seems a stretch).

### CODE REVIEW

**Comment by vanwinkeljan** [comment]
I have no problem in removing `samples/subsys/shell/fs` but I think the documentation should be moved in that case.
Further general documentation should be added to the existing shell sample.

**Comment by pabigot** [comment]
@vanwinkeljan I'd thought about the documentation, but the fs example is alone in trying to document the shell commands.  Copying over that to the general shell module would prompt a request to document all the other command groups, which is more than I care to take on.

I certainly think documentation of shell commands is incredibly poor, but it's not clear where/how it can be improved.  Isolating it to a sample readme is not, IMO, the right approach.

**Comment by vanwinkeljan** [comment]
Agree that shell command should not only be documented in the sample documentation. 

But I think that at least a README file should be added to the shell sample now it is even not clear from the documentation that there even is a shell sample.

**Comment by pabigot** [comment]
#27805

**Pull request closed without merging**
