### PR TITLE
topic/counters: miscellaneous cleanup

### PR DESCRIPTION
**Pull request by pabigot**
### tests: drivers: counter: improve comments on reserved instances

RTC1 (not RTC0) is excluded because it is used as the system clock.

Also document that TIMER0 and RTC0 may be rejected when CONFIG_BT_LL_SW
is enabled.

### drivers: counter: nrf: make name configuration consistent

Using `COUNTER_2_NAME` when all other properties are
`COUNTER_TIMER2_foo` is confusing.  Make the names consistent.

### drivers: timer: conflict RTC timer with RTC1 counter

The system timer uses RTC1, but does not implement the counter API with
it.  Instead of auto-enabling the counter API on the system timer make
the two conflict until/unless both APIs are supported by the peripheral.

### drivers: counter: add API to query counter frequency

Add API to get the base counter frequency.

### CODE REVIEW

**Comment by MaureenHelm** [comment]
recheck

**Review by MaureenHelm — APPROVED** [review]

**Comment by pabigot** [comment]
@MaureenHelm do you still have in your local git repo the results of merging this to topic-counters?  It looks like a pair of forced push from @nordic-krch overwrote the base branch and dropped these changes.

**Comment by nordic-krch** [comment]
@pabigot  @MaureenHelm unfortunately that may have happen...  this PR seems to be in. What is missing?

**Comment by pabigot** [comment]
@MaureenHelm @nordic-krch it is in, my mistake.  See questions in 12155 (I was trying to rebase that on the current base so I could test it, and got weird results).

**Pull request merged**
