### PR TITLE
shell: Make autocomplete work with non-sorted commands

### PR DESCRIPTION
**Pull request by Vudentz**
This allows declaring the commands in any order which sometimes is
convenient when commands are conditional making it undesirable to
sort everything.

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

**Comment by Vudentz** [comment]
@pfalcon fixed

**Comment by Vudentz** [comment]
@jarz-nordic can you review this one?

**Comment by jarz-nordic** [comment]
I think it is also worth to update documentation.

**Comment by Vudentz** [comment]
@jarz-nordic Does the documentation say anything about entries required to be sorted?

**Comment by jarz-nordic** [comment]
@Vudentz : yes, it is few times mentioned in shell.rst

**Review by jakub-uC — CHANGES_REQUESTED** [review]
Please update shell.rst by removing information saying that subcommands shall be added in alphabetical order.

I have tested it and it works fine:
1. Tab works correctly.
2. Commands are executed correctly.
3. Wildcards work correctly.

Good job 👍

**Comment by Vudentz** [comment]
@jarz-nordic I removed the references about alphabetically sorted from shell.rst, Ive also removed references of that in code as well.

**Comment by jarz-nordic** [comment]
@Vudentz : I will testdynamic commands as well. Possibly lines 64 - 65 must be removed as well.

**Comment by jarz-nordic** [comment]
@Vudentz : I tested it just now. Dynamic commands also work fine without sorting.
So shell.rst lines 64 - 65 shall be alo removed.

**Comment by Vudentz** [comment]
@jarz-nordic done

**Review by jakub-uC — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
