### PR TITLE
net: lwm2m: Add raw CBOR content writer tests

### PR DESCRIPTION
**Pull request by nordic-mare**
This will add unit tests for the raw CBOR content encoder/decoder.

Signed-off-by: Markus Rekdal <markus.rekdal@nordicsemi.no>

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]

**Comment by nordic-mare** [comment]
The remaining failure is due to [zcbor PR217](https://github.com/NordicSemiconductor/zcbor/pull/217)

**Review by VeijoPesonen — DISMISSED** [review]
Looks good to me

**Comment by VeijoPesonen** [comment]
@SeppoTakalo Please review.

**Review by SeppoTakalo — DISMISSED** [review]

**Comment by VeijoPesonen** [comment]
@rlubos Are we to wait that a fixed ZCBOR version is released - and it finds its way to Zephyr - before this PR is merged?

**Comment by rlubos** [comment]
Well, we can't merge a PR with failing CI, it'd break the main.

**Review by VeijoPesonen — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by SeppoTakalo — APPROVED** [review]

**Pull request merged**
