### PR TITLE
modules: CMSIS: integrate CMSIS-NN

### PR DESCRIPTION
**Pull request by JordanYates**
Import and integrate the CMSIS-NN libraries from CMSIS release v5.8.0.

Adds a selection of tests to validate the integration of the library is functioning properly. Complete functional testing is left to the externally maintained project.

Only the TFL micro compliant functions are imported, see: https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN#legacy-vs-tfl-micro-compliant-apis

Resurrection of #24914
Recreation of #41353 due to Github issues

### CODE REVIEW

**Review by stephanosio — DISMISSED** [review]
LGTM

**Review by tejlmand — APPROVED** [review]
lgtm

**Comment by freddan80** [comment]
Hi @JordanYates, it's nice to see your interest in CMSIS-NN! It looks from your comment that you're using CMSIS-NN via TFL micro:

> Only the TFL micro compliant functions are imported

Did you plan to add CMSIS-NN integration into the existing [Zephyr TFLM integration](https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/tflite-micro/CMakeLists.txt), or are you using integrating that separately? 

Cheers,
Fredrik

**Comment by JordanYates** [comment]
> Hi @JordanYates, it's nice to see your interest in CMSIS-NN! It looks from your comment that you're using CMSIS-NN via TFL micro:
> 
> > Only the TFL micro compliant functions are imported
> 
> Did you plan to add CMSIS-NN integration into the existing [Zephyr TFLM integration](https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/tflite-micro/CMakeLists.txt), or are you using integrating that separately?
> 
> Cheers, Fredrik

Only the TFL micro functions were imported because AFAIK the older functions are no longer supported.
Right now we are using CMSIS-NN manually for a colleague, but I'm sure at some point we will want to properly integrate it as a backend for TF.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> Did you plan to add CMSIS-NN integration into the existing [Zephyr TFLM integration](https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/tflite-micro/CMakeLists.txt), or are you using integrating that separately?

@freddan80 Now that basic inclusion as a module is merged, feel free to add additional integration with TFL in a separate PR

**Comment by freddan80** [comment]
@JordanYates 
> Only the TFL micro functions were imported because AFAIK the older functions are no longer supported.

Correct. We're only maintaining the TFL micro kernels.

> Right now we are using CMSIS-NN manually for a colleague, but I'm sure at some point we will want to properly integrate it as a backend for TF.

Sounds reasonable.

@carlescufi 

> Now that basic inclusion as a module is merged, feel free to add additional integration with TFL in a separate PR

For sure a separate PR. I was just curious if there was plan.

Cheers

**Pull request merged**
