### PR TITLE
CONFIG_EXCEPTION_DEBUG should depend on CONFIG_DEBUG

### PR DESCRIPTION
**Pull request by lpereira**
Signed-off-by: Leandro Pereira <leandro.pereira@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — COMMENTED** [review]
Need more justification for doing this, or at least a larger plan for dealing with debug options.

At the moment, CONFIG_DEBUG is off by default and just changes compiler setting. This is on by default,  but won't be with the change, and as a result any CPU exception will fall into the _NANO_ERR_SPURIOUS_INT case. That includes page faults, protection faults, any exception.

At minimum, we need this enabled for all the QEMU targets.

**Comment by nashif** [comment]
I guess this change is needed to satisfy some security and release requirements that mandate not enabling debugging by default and disabling debugging in the default configuration. CONFIG_DEBUG probably needs to be changed to not change compiler flags and instead enable various runtime debug features, changing optimization should be another explicit option, so developers can know what to expect when enabling CONFIG_DEBUG.

But to @andrewboie  concerns, I would disable CONFIG_EXCEPTION_DEBUG by default and enable it in `tests/include/test.config` instead, then we need to discuss CONFIG_DEBUG and how the semantics should be changed to make it more obvious and connect other debugging features to this option to aid during debugging.

**Comment by andrewboie** [comment]
> But to @andrewboie concerns, I would disable CONFIG_EXCEPTION_DEBUG by default and enable it in tests/include/test.config

It's an x86-only option.
If we're gonna tie all these debug features to CONFIG_DEBUG, maybe just enable CONFIG_DEBUG in test.config instead. Or enable CONFIG_DEBUG by default in all the qemu defconfigs since we care about neither performance or footprint on QEMU targets

**Comment by nashif** [comment]
> It's an x86-only option.

should still work for other architectures, it will just be optimised out.


> If we're gonna tie all these debug features to CONFIG_DEBUG, maybe just enable CONFIG_DEBUG in test.config instead. Or enable CONFIG_DEBUG by default in all the qemu defconfigs since we care about neither performance or footprint on QEMU targets

yes, we should be able to enable DEBUG by default on Qemu, this should not affect security requirements, because Qemu will not be used in production anyways.

**Comment by nashif** [comment]
outdated, closing. Reopen with updates/rebase if needed.

**Pull request closed without merging**
