### PR TITLE
usb: Remove unused usb_vbus logic

### PR DESCRIPTION
**Pull request by finikorg**
The logic is unused so we can remove it.

### CODE REVIEW

**Review by jfischer-no — CHANGES_REQUESTED** [review]
We should not do that. I actually changed it to the new API and DT because we can not know if it is used outside the tree and the functionality self is valid.

**Comment by carlescufi** [comment]
> We should not do that. I actually changed it to the new API and DT because we can not know if it is used outside the tree and the functionality self is valid.

I agree with @jfischer-phytec-iot . We discussed this in the USB meeting and it was converted to the new API instead. We don't know if we have users of this feature out of tree.

**Review by carlescufi — CHANGES_REQUESTED** [review]
See comment

**Comment by finikorg** [comment]
This was used for now deprecated board. AFAIK nobody uses this now.

**Comment by jfischer-phytec-iot** [comment]
> This was used for now deprecated board. AFAIK nobody uses this now.

Even if nobody uses it now, this is up-to-date and useful.

**Comment by finikorg** [comment]
OK, closing PR

**Pull request closed without merging**
