### PR TITLE
west.yml: nrf_radio_802154 SWI priority bug fix

### LINKED ISSUE #28360: drivers: nrf_802154: SWI IRQ priority is not read correctly
`nrf_802154` driver does not use its platform IRQ API to read SWI IRQ priority, which results in an invalid behaviour of the driver.

### PR DESCRIPTION
**Pull request by pkwiek**
Port SWI priority evaluation to use platform IRQ.

Fixes #28360

Signed-off-by: Pawel Kwiek <pawel.kwiek@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
@pkwiek Please update `west.yml` with the following SHA, the `hal_nordic` PR was merged: `615c762a6d2e411d631cc6bd18fb45f892a5cbc3`

**Review by ioannisg — CHANGES_REQUESTED** [review]
Please update the manifest pointer

**Review by rlubos — APPROVED** [review]

**Comment by ioannisg** [comment]
No, please, force-push, and keep only the last commit with the SHA :)

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
@pkwiek just curious, can you investigate why the pull-request labeler is failing?

**Comment by MaureenHelm** [comment]
> @pkwiek just curious, can you investigate why the pull-request labeler is failing?

It was failing on master yesterday. Please rebase to pick up the fix

**Pull request merged**
