### PR TITLE
soc: arm: sam4s: Add spi driver support

### PR DESCRIPTION
**Pull request by nandojve**
Since current sam_spi driver is compatible wtih sam4 platform this enables driver support on sam4s mcu.

depends on: https://github.com/zephyrproject-rtos/zephyr/pull/22394

### CODE REVIEW

**Comment by nandojve** [comment]
I can't understand why this patch broke sample.bluetooth.peripheral_hr_rv32m1_vega_ri5cy.

**Review by dbkinder — APPROVED** [review]
docs LGTM.

**Review by mnkp — COMMENTED** [review]
I've added DNM label since #21319 needs to be merged first. The PR looks good, however I would like to re-review it when it is rebased on top of merged #21319.

**Comment by nandojve** [comment]
@mnkp  do you think this could still make it into the 2.2 release?

**Comment by nandojve** [comment]
> I've added DNM label since #21319 needs to be merged first. The PR looks good, however I would like to re-review it when it is rebased on top of merged #21319.

I splitted #21319 and now this PR depends only of #22394, the true dependency.

**Review by mnkp — APPROVED** [review]

**Comment by mnkp** [comment]
All dependencies of this PR has already been merged on master.  #22394 has been replaced by #22401. Apart from resolving merge conflicts there shouldn't be anything blocking this PR. I've removed DNM label.

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@nandojve  can you please rebase?

**Comment by nandojve** [comment]
I took liberty to complement this PR with more two commits. The first one fix a warning message that is now treated by CI as error. In this case added spi0 on board dts file to fix it. The second one, once spi is now supported, it needs to be on board yaml file.

**Comment by carlescufi** [comment]
I have retriggered CI on this PR to check against the topic-gpio branch merge.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
