### PR TITLE
drivers: pinmux: stm32: STM32F2 added ETH support to pinmux and use it

### PR DESCRIPTION
**Pull request by therealprof**
This patch adds support for Ethernet in the STM32F2 family of
microcontrollers and enables it for the the Nucleo-F207ZG.

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by qianfan-Zhao** [comment]
@therealprof Hi I had a custom stm32f207ve board and it support ethernet. But stm32f207ve doesn't has GPIOG, it use PB11/PB12 pin as eth not PG11/PG13.

So could you please add STM32F2_PINMUX_FUNC_PB11_ETH and STM32F2_PINMUX_FUNC_PB12_ETH marco in pinmux_stm32f2.h?

**Comment by qianfan-Zhao** [comment]
@therealprof Since you add support ETH support for nucleo-f207zg, could you please also update the doc?

**Review by erwango — CHANGES_REQUESTED** [review]
Minor comment:
@therealprof , can you add, in help section of ETH_STM32_HAL, the list of series currently supported by the driver (the ones for which minimum tests have been done and eth is enabled on at least a board): F4, and F2 now. 
Then you could do the same in your PR for enabling eth on F7.
Thanks!

**Comment by therealprof** [comment]
@qianfan-Zhao I'm a bit wary about adding things I can not really test here, can you add this yourself in a later PR maybe? I will certainly update the documentation.

@erwango Will do.

**Comment by qianfan-Zhao** [comment]
@therealprof 
>  I'm a bit wary about adding things I can not really test here, can you add this yourself in a later PR maybe?

Sure. And I can test that on my custom stm32f207vg board.

**Comment by therealprof** [comment]
@qianfan-Zhao @erwango I've addressed your documentation requests.

**Comment by qianfan-Zhao** [comment]
@therealprof sorry I means nucleo-f207zg.rst. I think you should leave a message to explain it supports Ethernet and which pin used.

**Comment by therealprof** [comment]
@qianfan-Zhao That's what I did: https://github.com/therealprof/zephyr/blob/6e7cc69b169db80a6b6448b1a72c53cc4dde90b1/boards/arm/nucleo_f207zg/doc/nucleo_f207zg.rst

**Comment by qianfan-Zhao** [comment]
@therealprof sorry I hadn't notice that.

**Review by dbkinder — APPROVED** [review]
+1 for doc changes

**Comment by therealprof** [comment]
@erwango Can you please have it another look whether your change requests have been sufficiently addressed?

**Review by erwango — APPROVED** [review]

**Comment by therealprof** [comment]
@erwango @dbkinder Anyone care to merge this please?

**Pull request merged**
