### PR TITLE
[Backport v1.14-branch] Bluetooth: controller: Fix handling zero length L2CAP start frame

### LINKED ISSUE #17288: Bluetooth: controller: Fix handling of L2CAP start frame with zero PDU length
**Describe the bug**
When a host sends HCI ACL packet with L2CAP start frame length of zero, the controller is sending incorrect LL_DATA START PDU with zero length.

**To Reproduce**
Run BT LL TS 5.1.0 conformance test cases

**Expected behavior**
The controller should not send LL_DATA START PDU with zero length.

**Impact**
Failing test case

**Screenshots or console output**
Not available

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: Zephyr v1.14 release

**Additional context**
None

### PR DESCRIPTION
**Pull request by cvinayak**
Backport #17046. 

Fixes #17288.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by ioannisg** [comment]
@cvinayak this needs a bug report

**Comment by cvinayak** [comment]
@ioannisg added #17288

**Comment by ioannisg** [comment]
@cvinayak thanks.
Just curious, any reason this was not created automatically? Forgotten back-port label?

**Review by joerchan — APPROVED** [review]

**Comment by cvinayak** [comment]
> Just curious, any reason this was not created automatically? Forgotten back-port label?
Yes, forgotten backport label.

**Comment by ioannisg** [comment]
> 
> 
> > Just curious, any reason this was not created automatically? Forgotten back-port label?
> 
> Yes, forgotten backport label.

@nashif moving this to ready

**Pull request merged**
