### PR TITLE
Fixes building on XCC (again)

### LINKED ISSUE #36661: xtensa xcc does not support "-Warray-bounds"
**Describe the bug**
warning：
```
In file included from E:/work/zephyr/include/sys/atomic_c.h:76,
                 from E:/work/zephyr/include/sys/atomic.h:31,
                 from E:/workzephyr/include/kernel_structs.h:25,
                 from E:/work/zephyr/include/arch/xtensa/arch_inlines.h:14,
                 from E:/work/zephyr/include/arch/arch_inlines.h:23,
                 from E:/work/zephyr/include/sys/arch_interface.h:1056,
                 from E:/work/zephyr/include/arch/cpu.h:13,
                 from zephyr/isr_tables.c:8:
zephyr/include/generated/syscalls/atomic_c.h:18: warning: unknown option after '#pragma GCC diagnostic' kind  
```
code:
build\zephyr\include\generated\syscalls\atomic_c.h
```
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
```
zephyr\scripts\gen_syscalls.py
```
syscall_template = """
/* auto-generated by gen_syscalls.py, don't edit */
%s

#ifndef _ASMLANGUAGE

#include <syscall_list.h>
#include <syscall.h>

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
#pragma GCC diagnostic push
#endif

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#pragma GCC diagnostic ignored "-Warray-bounds"
#endif
```

### PR DESCRIPTION
**Pull request by dcpleung**
This set of commits fixes building on XCC in general, and some are specific for Intel ADSP SoCs.

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
This looks good to me.

Does this means that you can build SOF with Zephyr, with XCC toolchain?
What XCC toolchain version are you using?
Are there any build steps on how to do it, like for GCC [here ](https://docs.zephyrproject.org/latest/guides/beyond-GSG.html#build-and-run-an-application) or [here](https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html#)?

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
> Is it enough to set ZEPHYR_TOOLCHAIN_VARIANT and CROSS_COMPILE as mentioned [here](https://docs.zephyrproject.org/latest/getting_started/toolchain_other_x_compilers.html)?

ZEPHYR_TOOLCHAIN_VARIANT=xcc

example of how it is used with a specific board: https://docs.zephyrproject.org/latest/boards/xtensa/intel_s1000_crb/doc/index.html

**Comment by dcpleung** [comment]
This was tested with RG-2017.8.

To use XCC to build, you will need to set the following environment variables:
```
ZEPHYR_TOOLCHAIN_VARIANT=xcc
TOOLCHAIN_VER=RG-2017.8-linux
XTENSA_CORE=<Xtensa Core ID>
XTENSA_BUILD_PATHS=<path to XCC installation>/XtDevTools/install/builds/
```

**Comment by iuliana-prodan** [comment]
> This was tested with RG-2017.8.
> 
> To use XCC to build, you will need to set the following environment variables:
> 
> ```
> ZEPHYR_TOOLCHAIN_VARIANT=xcc
> TOOLCHAIN_VER=RG-2017.8-linux
> XTENSA_CORE=<Xtensa Core ID>
> XTENSA_BUILD_PATHS=<path to XCC installation>/XtDevTools/install/builds/
> ```

@nashif @dcpleung thanks, I'll also try on i.MX.
Do you know what would be the difference between XCC and GCC? 
Are there any performance benefits?

**Comment by dcpleung** [comment]
I am not sure about any performance benefits, as I haven't done any benchmarking. IIRC, XCC can emit instructions to be used on the DSP which GCC doesn't not support.

**Review by kv2019i — APPROVED** [review]
Thanks @dcpleung ! Tested with SOF on Intel cavs25 and works fine.

**Comment by kv2019i** [comment]
@iuliana-prodan wrote:
> Are there any performance benefits?

gcc doesn't support all xtensa extensions (like Hifi3) and e.g. in SOF these are disabled in gcc builds (and generic version is used instead). Depending on algorithm, this can have a very large performance impact.

**Pull request merged**
