### PR TITLE
Net shell cleanups

### PR DESCRIPTION
**Pull request by Vudentz**

### CODE REVIEW

**Review by pfalcon — CHANGES_REQUESTED** [review]
> None of the public function were being used appart from net_shell_init which not longer do anything.

Did you try to look up why these functions are public? ff3b0190545d5311adb65be9deaf05bf9125dddc

And in general, we really should stop thinking about Zephyr as a thing in itself nobody cares about, and start to think about as an OS kernel, majority of users of which are outside the tree. Thanks.

**Review by jukkar — CHANGES_REQUESTED** [review]
We can certainly remove net_shell_init() but we need to leave the shell command functions to net_shell.h. These are currently used by micropython as commented by @pfalcon

**Comment by Vudentz** [comment]
Should that be moved to include then? How can anyone know these are public interfaces if it is restricted to subsys? Also by not being public it pretty much guaranteed to have its API break at some point, so we should probably think twice on accepting this sort of use case propose by https://github.com/zephyrproject-rtos/zephyr/commit/ff3b0190545d5311adb65be9deaf05bf9125dddc for internal headers.

Btw, can't the shell itself be operated without the use of console? Though that would make the commands themselves a public API and changing any of those could break existing tools.

**Comment by pfalcon** [comment]
@Vudentz : Please see https://jira.zephyrproject.org/browse/ZEP-2064 where un-static-izing those functions was proposed. My approach is that between "unable to reuse" and "public API with corresponding guarantees", there's a room for middle-line, where reuse is possible, but API isn't declared stable. At least, I wasn't brave enough to propose to make that public API right away, and I don't think it's worth doing that at this stage. If you think it's worth doing it now, maybe it is.

> Btw, can't the shell itself be operated without the use of console? Though that would make the commands themselves a public API and changing any of those could break existing tools.

Current shell implementation is largely tied into callback-based UART API, which makes composability of it not ideal I didn't try to approach it from that side. And indeed, that would make only extra layer to "emulate" for other implementations of shells. Just exporting functions makes it pretty good, based on experience with Zephyr.js and MicroPython design as examples.

**Comment by Vudentz** [comment]
Just a quick hack: https://gist.github.com/Vudentz/cb0f90ec10d779ccc61a80bbdca0e59d

With that you just call shell_exec passing the line with command, etc, and this actually can be unit test without any UART layer in between.

**Comment by pfalcon** [comment]
I'm all for exposing more reusable functions (in principle). However, it doesn't help much with the original usecase, using it would be as good as a C program using `system("ls")` to enumerate files in a directory - indeed, it's possible, and a lot of software is written like that, but why, if the task is actually to let reuse implementations of the commands, not adhoc Zephyr shell. E.g., for MicroPython an implementation of a particular function looks like:

~~~
+STATIC mp_obj_t mod_shell_iface(void) {
+    net_shell_cmd_iface(0, NULL);
+    return mp_const_none;
+}
+STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_shell_iface_obj, mod_shell_iface);

 STATIC const mp_map_elem_t mp_module_usocket_globals_table[] = {
+    { MP_OBJ_NEW_QSTR(MP_QSTR_shell_iface), (mp_obj_t)&mod_shell_iface_obj },
 };
~~~

Another example, I may imagine some C app, while being developed/debugged, may want to call net_shell_cmd_conn(0, NULL) every minute, not `char cmd[] = "conn"; shell_exec(cmd);` (and the latter of course won't work alone, because Zephyr shell is truly adhoc with all those context-dependent submodules), etc., etc.

**Comment by Vudentz** [comment]
> Another example, I may imagine some C app, while being developed/debugged, may want to call net_shell_cmd_conn(0, NULL) every minute, not char cmd[] = "conn"; shell_exec(cmd); (and the latter of course won't work alone, because Zephyr shell is truly adhoc with all those context-dependent submodules), etc., etc.

Yep, but if in turn it would like to do something like that and also use Bluetooth shell command suddenly we would have to expose yet another set of functions to be public, so this method of yours is a lot more intrusive and in fact make internal API public when there is no guarantee that they won't change.

As for the context I guess simply doing shell_exec("select net") at the beginning should be all you need, after all the whole point here is to use the shell without the console.

**Comment by pfalcon** [comment]
> we would have to expose yet another set of functions to be public, so this method of yours is a lot more intrusive

It's not intrusive if we make them reusable, non-static right away ;-). Doesn't have to be truly "public", just "internal reusable API".

I'll let you guys decide on that, but diagnostics is important function, why make apps to reinvent it instead of reuse what's already in Zephyr, and at the same time, using string manipulation functions to access it in an RTOS looks strange, that's IMHO.

**Comment by Vudentz** [comment]
> It's not intrusive if we make them reusable, non-static right away ;-). Doesn't have to be truly "public", just "internal reusable API".

I guess internal API can be reusable only for other internal parts, since that would cause build errors, for external code that is pretty hard to maintain compatibility.

> I'll let you guys decide on that, but diagnostics is important function, why make apps to reinvent it instead of reuse what's already in Zephyr, and at the same time, using string manipulation functions to access it in an RTOS looks strange, that's IMHO.

Considering you used the analogy of shell_exec with system, which is useful for testing purposed, this is not reinventing anything, in fact, I don't recall any other interface with shell in other OSes or you have seem any shell exporting function like shell_ls?

**Comment by pfalcon** [comment]
> since that would cause build errors, for external code that is pretty hard to maintain compatibility.

And that's good. For example, if net_shell_cmd_iface() gets renamed, or signature changes, there immediately will be build error. Compare that with what happens if a textual shell command gets renamed (or "select", or shell submodule name). A possibility of build error is part of usage contract - these functions are diagnostics in nature, not "production", so maintainers of 3rd-party project should consider what's important for their project (at its particular stage) - seamless buildability or diagnostability. Given that Zephyr is in high churn anyway, I don't think that's big issue.

> I don't recall any other interface with shell in other OSes or you have seem any shell exporting function like shell_ls?

Well, Zephyr is RTOS, and we know that primary interface so far is direct function calls. And I personally don't treat Zephyr's shell as a full-fledged interface - it's really too adhoc, that's why I'm trying to bypass it (including potentially garbage-collecting its code) and instead jut get to specific functions.

**Comment by Vudentz** [comment]
> A possibility of build error is part of usage contract - these functions are diagnostics in nature, not "production", so maintainers of 3rd-party project should consider what's important for their project (at its particular stage) - seamless buildability or diagnostability. Given that Zephyr is in high churn anyway, I don't think that's big issue.

For a 3rd-party you can always patch zephyr for its own use, yet you prefer that zephyr takes the burden of maintaining this interface when in fact there is no internal users of it. Also, please check there is no build error otherwise we wouldn't be seeing 'All checks have passed' bellow, instead we are spending a great deal of time with 3rd-party features that as you mentioned are not meant for 'production'.

**Comment by Vudentz** [comment]
@jukkar This set is no longer removing the net_shell.h so it should be safe to apply.

**Review by jukkar — APPROVED** [review]

**Comment by pfalcon** [comment]
@Vudentz :

> For a 3rd-party you can always patch zephyr for its own use

If everyone will have to patch Zephyr to get basic functionality out of it, there will be situation worse than with Linux (due to Zephyr's licensing).

> yet you prefer that zephyr takes the burden of maintaining this interface when in fact there is no internal users of it.

As I tried to explain, I exactly don't want to put extra burden on Zephyr by defining any "public" API so far, while still making a first shy step towards allowing apps to reuse wealth of diagnostics code Zephyr already has. It may be that one of the next steps will be to actually define that as a public API (without tying it to Z shell in any way), or maybe we indeed would need to backtrack to going full-on thru the shell, like you showed.

All in all, I appreciate giving it a chance and static'izing those functions back few weeks after they were exposed. (And sorry for the delay with response, sick leave.)

**Pull request merged**
