### PR TITLE
Bluetooth: shell: Unregister the previous scan callback to avoid register repeatedly before register

### PR DESCRIPTION
**Pull request by nngt88**
1.[Description]
tests: tester: Device hang is observed when LE Scan
[Root Cause]
For le_ext_adv_report, Data[i] of one adv report is 0-229, for the adv_buf of saving, it just is 73 bytes, so sometimes the bytes of adv report is more than the adv_buf, resulted hang
[Fix]
Increase the adv_buf size.
[Testing]
After modified, Device hang is not observed after stress testing with LE Scan

2.[Description]
tests: shell: Restart bt will register the same scan callback twice.
Callback next node point to itself,when scan, callback function
loop infinitely
[Root Cause]
After bt_disable, then bt_init, register scan_cb two times,
[Fix]
Unregister the previous callback to avoid register repeatedly.
[Testing]
After modified, test bt init,bt scan on,bt scan off,bt disable as loop, issue doesn't repoduce.

Signed-off-by: Guotao Zhang guotao.zhang@nxp.com

### CODE REVIEW

**Comment by alwa-nordic** [comment]
Can we instead do the registration once on boot?

**Review by Thalley — CHANGES_REQUESTED** [review]
Hmm, the issue described implies that `bt_ready` is called twice without error, which shouldn't be possible since it has

```c
	if (atomic_test_and_set_bit(bt_dev.flags, BT_DEV_ENABLE)) {
		return -EALREADY;
	}
```

Please provide the steps you used to generate this issue

**Comment by carlescufi** [comment]
@nngt88 the commit in this PR changing the advertising buffer size is also present in #75756. Can you remove it from this PR?

**Comment by nngt88** [comment]
> Hmm, the issue described implies that `bt_ready` is called twice without error, which shouldn't be possible since it has
> 
> ```c
> 	if (atomic_test_and_set_bit(bt_dev.flags, BT_DEV_ENABLE)) {
> 		return -EALREADY;
> 	}
> ```
> 
> Please provide the steps you used to generate this issue

**Comment by Thalley** [comment]
> Hmm, the issue described implies that `bt_ready` is called twice without error, which shouldn't be possible since it has
> 
> ```c
> 	if (atomic_test_and_set_bit(bt_dev.flags, BT_DEV_ENABLE)) {
> 		return -EALREADY;
> 	}
> ```
> 
> Please provide the steps you used to generate this issue

Re-reading your message, it's more clear to me now. 

I don't think the solution is the unregister in the `bt_ready` callback, but rather disable when we do `bt_disable`. 

Alternatively we can do as @alwa-nordic suggested and register them once at boot time instead

**Comment by nngt88** [comment]
Hi @all, sorry, my code is old,  I found the issue have been solved 1 month ago, so I will decline this PR, Thanks 
https://github.com/zephyrproject-rtos/zephyr/pull/74011/commits/d34fd0f517f24166ece52da75fe687a4a2b2475b

**Pull request closed without merging**
