### PR TITLE
runners: add Black Magic Probe runner cmake file

### PR DESCRIPTION
**Pull request by ntavish**
Added required cmake file for blackmagicprobe
runner added in #12380.
    
Signed-off-by: Tavish Naruka <tavishnaruka@gmail.com>

### CODE REVIEW

**Review by mbolivar — CHANGES_REQUESTED** [review]
Hi, thanks for the patch! Please submit this to the west repository: https://GitHub.com/zephyrproject-rtos/west. The copy of west in zephyr is going away.

**Comment by ntavish** [comment]
Hi, I have a separate PR in that repo also. I was told that till the
transition happens, this copy also stays.

**Comment by ntavish** [comment]
This one specifically: https://github.com/zephyrproject-rtos/west/pull/134.

**Comment by ntavish** [comment]
Closing this PR as https://github.com/zephyrproject-rtos/west/pull/134 will be merged and then copied over to zephyr repo.

**Comment by ntavish** [comment]
Runner has been copied over from west, but needs this cmake file. Reopened.

**Pull request closed without merging**
