### PR TITLE
boards: stm32f469i_disco: Enable CAN peripheral support

### PR DESCRIPTION
**Pull request by windsorschmidt**
Tested working on a 32F469IDISCOVERY board using the example project
in samples/net/sockets/can with the Discovery board's CAN signals (CN5
pins 9 and 10) connected to a SN65HVD232D CAN bus transceiver.

Using this configuration, I'm able to send and receive frames between
the Discovery board and a Linux host with a USB2CAN adapter.

Signed-off-by: Windsor Schmidt <windsor.schmidt@gmail.com>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for the change
Please fix the warning reported by zephyrbot, otherwise LGTM.

**Comment by erwango** [comment]
@windsorschmidt, the pins you assigned are conflicting with pins assigned to I2C1 (a.k.a Arduino I2C)
Is there a way to find pins compatible with I2C1 ?
Else we should at least warn users.

**Review by erwango — CHANGES_REQUESTED** [review]
@windsorschmidt, the pins you assigned are conflicting with pins assigned to I2C1 (a.k.a Arduino I2C)
Is there a way to find pins compatible with I2C1 ?
Else we should at least warn users.

**Comment by windsorschmidt** [comment]
> Is there a way to find pins compatible with I2C1 ?

Hi, and thanks for the review.

Looking at the datasheet (DS11189) and the board user manual (UM1932), It doesn't look like there are alternate pins for CAN1 available at any of the board's connectors. Alternatively, CAN2 signals appear at the "extension connector" CN12. I will try modifying the board files to use CAN2 when I have time.

> Else we should at least warn users.

I don't know the Zephyr ecosystem well enough to suggest the best way to do this. If there is a previous example to base this on, I'm happy to submit a PR on the board's documentation. Please advise on how I should proceed with this patch.

As an aside, many of the Zephyr-supported boards use CAN-enabled STM32 parts, yet very few show explicit support for this peripheral. As an RTOS end-user, I've been eagerly waiting for CAN bus support in Zephyr, and would love to see it featured on as many supported boards as possible.

**Comment by erwango** [comment]
> Looking at the datasheet (DS11189) and the board user manual (UM1932), It doesn't look like there are alternate pins for CAN1 available at any of the board's connectors. Alternatively, CAN2 signals appear at the "extension connector" CN12. I will try modifying the board files to use CAN2 when I have time.

Would be great indeed so we could enjoy both I2C and CAN at the same time.
Though, for some reason CAN2 is not yet available in CAN driver, so you'd have to make it available first.

> 
> As an aside, many of the Zephyr-supported boards use CAN-enabled STM32 parts, yet very few show explicit support for this peripheral. As an RTOS end-user, I've been eagerly waiting for CAN bus support in Zephyr, and would love to see it featured on as many supported boards as possible.

Thanks for your interest. For board support addition, we mostly rely on community members contributions (as you just did) since this require some work and adding support on all boards would be a huge task.

**Comment by alexanderwachter** [comment]
> As an aside, many of the Zephyr-supported boards use CAN-enabled STM32 parts, yet very few show explicit support for this peripheral. As an RTOS end-user, I've been eagerly waiting for CAN bus support in Zephyr, and would love to see it featured on as many supported boards as possible.

@windsorschmidt Thanks for your PR and thanks for your interest int the Zephyr CAN subsystem.
As Erwan already mentioned, we rely on the community to add the boards but additionally, we need to test all the boards. There are lots of things that could possibly go wrong, and we only add boards that are already tested. Feel free to add support for all boards you have at hand :-)

**Comment by alexanderwachter** [comment]
> Would be great indeed so we could enjoy both I2C and CAN at the same time.
> Though, for some reason CAN2 is not yet available in CAN driver, so you'd have to make it available first.

CAN2 is not available because it is only a slave of CAN1 and the driver currently only supports CAN1.

**Comment by alexanderwachter** [comment]
@windsorschmidt According to the reference manual, PA_11 as CAN_RX (CN9 PIN3) and PA_12 as CAN_TX (CN9  PIN6) could also be used for CAN1

**Comment by alexanderwachter** [comment]
FYI: #22200 introduces CAN2 support.

**Comment by windsorschmidt** [comment]
@alexanderwachter thanks for the heads up. I'll close this PR and wait to test my hardware using #22200.

**Pull request closed without merging**
