### PR TITLE
net: Avoid building native stack components with CONFIG_NET_NATIVE=n

### PR DESCRIPTION
**Pull request by rlubos**
Another set of changes for better separation of native network stack and offloaded cases. This disables building of native stack features when NET_NATIVE is disabled. It's been reported that builds may fail with `--no-gc-sections` option enabled.

The major change here is separation of generic socket code (syscalls shared between native and offloaded implementations) from native IP sockets implementation. For some reason git produced pretty scary diff, but in reality the `sockets.c` file has simply been split into two.

### CODE REVIEW

**Comment by rlubos** [comment]
Added a commit removing the faulty macro, just in case.

**Review by jukkar — DISMISSED** [review]

**Comment by jukkar** [comment]
> It's about `SET_ERRNO()` macro, the check must've been disabled when the macro was originally introduced. Shall we ask to override this, or take the opportunity and remove that macro?

Overriding is a good choice, I think the macro just hides things without being useful.

**Review by jukkar — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
The first commit is kind of hard to review, but I hope/assume this is simply moving out parts to a separate file.

**Comment by rlubos** [comment]
> The first commit is kind of hard to review, but I hope/assume this is simply moving out parts to a separate file.

That is correct, the first commit just moved entire functions from one file to another. For some reason git decided to provide a pretty nasty diff for this.

**Pull request merged**
