### PR TITLE
doc: update debuger documents for NXP RT series

### PR DESCRIPTION
**Pull request by hakehuang**
on board debuger now unified as MCU-Link

### CODE REVIEW

**Comment by hakehuang** [comment]
@dleach02 @mmahadevan108 @yvanderv please help to review this debuger updates for RT series board

**Comment by decsny** [comment]
@DerekSnell would be interested in this

**Review by DerekSnell — CHANGES_REQUESTED** [review]
Hi @hakehuang ,
Before making these doc changes, I will work with you offline to finalize these updates.  Thanks

**Comment by hakehuang** [comment]
need more alignment on lagecy boards

**Pull request closed without merging**
