### PR TITLE
Sample: Add Bluetooth L2CAP Mesh sample

### PR DESCRIPTION
**Pull request by prathje**
Hello everyone,
I have been working on several simultaneous Bluetooth Low Energy connections.
However, I encountered problems, mostly assertion errors, while doing a lot of parallel connections.

One example with 20 devices resulted in the following assertion fail:
```
d_14: @00:00:21.215881  ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:305
d_14: @00:00:21.215881  	k_sem_take failed with err -11
d_14: @00:00:21.215881  @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:305
d_14: @00:00:21.215881 WARNING: Exiting due to fatal error
```

I think that race conditions due to many connections result in undesired behavior of the BLE stack. Therefore, I built this specific, simplified example that bases on parallel connections: Devices create a sort of connection-oriented BLE mesh. They advertise and directly connect to other devices, sending dummy data over L2CAP channels.
I believe an example like this may aid in solving or even uncovering issues such as https://github.com/zephyrproject-rtos/zephyr/issues/30245 , https://github.com/zephyrproject-rtos/zephyr/issues/36381, or https://github.com/zephyrproject-rtos/zephyr/issues/25917  .
The multi-device environment is simulated using BabbleSim and should be easily tweaked for testing purposes as well.

What would you think of such a sample (or a respective test case)?

### CODE REVIEW

**Comment by cvinayak** [comment]
@prathje Thank you for this sample, I have not reviewed the implementation, but this sample should definitely help me analyse the cause of the deadlocks. I will post here if I have some results.

**Comment by cvinayak** [comment]
@prathje Please cherry-pick #37629 and verify if you still face issue (I have run `bsim.sh 20` with no crashes)

**Comment by prathje** [comment]
@cvinayak Thank you very much for your support! And I hope that this sample could indeed help you.

Unfortunately, I tried to cherry-pick your commit and the other way around, but I could not get the simulation to run beyond the 21.215881 mark with 20 devices. As the BabbleSim runs are deterministic, it should not really be possible that we get different results. Did you run into the same assertion error before applying your fix?

**Comment by cvinayak** [comment]
> Did you run into the same assertion error before applying your fix?

No, I was not able to reproduce your error on the PR branch, but I got assertions in `ull.c` and `ull_conn.c` files when running `btsim.sh 11`  11 connections.

Maybe, my toolchain makes a difference (archlinux with gcc version 11.1.0 on virtualbox)

**Comment by prathje** [comment]
> Maybe, my toolchain makes a difference (archlinux with gcc version 11.1.0 on virtualbox)

I see. I will investigate that, thanks!

**Comment by cvinayak** [comment]
@prathje  Also, I had to remove `-defmodem=BLE_simple -channel=Indoorv1 -argschannel -preset=Huge3 -speed=1.1 -at=50` because I got `ERROR: (src/channel_2G4Indoorv1.c:380): Unknown modulation type 32` error after 1.41 seconds.

**Comment by cvinayak** [comment]
@prathje I had to pull in and rebuild my babblesim library, now I am able to reproduce the `hci_core.c: 305` issue. I will analyse the issue further and  post here.

**Comment by prathje** [comment]
> @prathje I had to pull in and rebuild my babblesim library, now I am able to reproduce the `hci_core.c: 305` issue. I will analyse the issue further and post here.

Neat! I was just about to send you the closed issue in BabbleSim 👍
Your help is very appreciated!

**Comment by cvinayak** [comment]
[log_20_5.txt](https://github.com/zephyrproject-rtos/zephyr/files/6975444/log_20_5.txt)

The above log with added `printk` indicates that the device `d_14` is waiting to Tx a data packet (waiting for num cmplt) and then deadlocks trying to send HCI disconnect.

This appears similar to the issue #25917

**Comment by prathje** [comment]
Thank you for the investigation!
Once the sample works for a single connection (i.e.`CONFIG_BT_MAX_CONN=2` results in `L2CAP_MESH_MAX_CONN=1`),
one may then try to connect to more than once device simultaneously with increased CONFIG_BT_MAX_CONN values.
Also, the amount of net_buffers can be increased with L2CAP_MESH_PARALLEL_BUFFERS.

**Pull request closed without merging**
