### PR TITLE
boards: arm: pandora_stm32l475_defconfig, Set malloc arena size to zero

### PR DESCRIPTION
**Pull request by TrekMax**
These are a handful of fixes required to use picolibc as the default C library

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Please include details of the actual failure.

**Comment by keith-packard** [comment]
Is this resolved by disabling malloc by default? #63259 has patches to completely remove malloc for tests which don't use it, saving both the default arena *and* the malloc initialization code.

**Comment by QinYUN575** [comment]
> Please include details of the actual failure.

By default, using picolibc will set the configuration COMMON_LIBC_MALLOC_ARENA_SIZE to -1, which will result in the size of the heap being defined as the unused ram size (set to 0), leading to initialization failure.

https://github.com/zephyrproject-rtos/zephyr/blob/90b9809c6f5563c8a8f93310fa65fdb8f321bc06/lib/libc/common/source/stdlib/malloc.c#L95-L110

**Review by keith-packard — COMMENTED** [review]
cool.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by keith-packard** [comment]
> > Is this resolved by disabling malloc by default? #63259 has patches to completely remove malloc for tests which don't use it, saving both the default arena _and_ the malloc initialization code.
> 
> Tried it, it works

Seems like we should merge #63259 instead of this then -- that way when malloc is required by any subsystem, it will have a non-empty arena on this board without requiring additional config changes.

**Pull request closed without merging**
