### PR TITLE
net: ip: Allow DHCPv4 to override IPv4 autoconf address if only 1 unicast address per interface is allowed

### PR DESCRIPTION
**Pull request by ad8sweera**
When DHCPv4 and IPv4 Autoconf are both enabled and only 1 unicast address is allowed per interface, the address type which gets registered for the interface is not deterministic.

This fix allows a DHCPv4 address to override an IPv4 autoconf address in the single unicast address case.

Signed-off-by: Savin Weeraratne <savin.weeraratne@audinate.com>

### CODE REVIEW

**Comment by jukkar** [comment]
Why not require that user should increase the unicast address count to 2 in this case? This can be very confusing to the application if the network interface address changes all of a sudden and the previous address is used by a socket.

**Review by jukkar — CHANGES_REQUESTED** [review]
I still think this is a bad idea. If you have both DHCP and autoconf enabled, you definitely should have 2 unicast address allowed per interface.

**Comment by GeorgeAtKistler** [comment]
It is a pitty that that patch did not get accepted, eg. with a config option.
It works well for us, see https://github.com/zephyrproject-rtos/zephyr/discussions/68238#discussioncomment-8316492

**Comment by jukkar** [comment]
@GeorgeAtKistler I do not mind the actual feature, but the patch was checking that 1 unicast address is available which imho is not correct.

**Pull request closed without merging**
