### PR TITLE
bootloader/mcuboot: Add fix for main return type

### PR DESCRIPTION
**Pull request by keith-packard**
This fix is pending upstream.

### CODE REVIEW

**Comment by thedjnK** [comment]
This needs to be submitted to https://github.com/mcu-tools/mcuboot and not the zephyr fork

**Comment by keith-packard** [comment]
> This needs to be submitted to https://github.com/mcu-tools/mcuboot and not the zephyr fork

Thanks! https://github.com/mcu-tools/mcuboot/pull/1696

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — CHANGES_REQUESTED** [review]
OK but The MCUboot revision update should be brought by synchronization PR.

**Comment by stephanosio** [comment]
To be integrated via https://github.com/zephyrproject-rtos/zephyr/pull/57553

**Pull request closed without merging**
