### PR TITLE
tests: bsim: Use the pre_init_f instead of post_init_f

### PR DESCRIPTION
**Pull request by rugeGerritsen**
When using the post_init_f to initialize the `bst_result`, it is not possible to mark the test as
passed immediately as the `bst_result` will be
initialized after the test completes.

This change should overcome this limitation.

### CODE REVIEW

**Review by jori-nordic — DISMISSED** [review]
Do you know why `post_init` was used in the first place?

**Comment by Thalley** [comment]
> Do you know why `post_init` was used in the first place?

Probably just a cascade effect. The first BSIM test was implemented by @aescolar back in https://github.com/zephyrproject-rtos/zephyr/pull/10688 and then the use of `test_post_init_f` was probably just copy pasted up until now

**Review by alwa-nordic — DISMISSED** [review]

**Comment by alxelax** [comment]
@aescolar, could you confirm that moving phy resyncing from post_init to pre_init will not impact the test scenario? Will the emulated devices get drifft again if synchronization was done earlier? 
In mesh we use an initialization step to be sure that bsim environment has been already synchronized before running the test scenario. It is required to exclude time drifting among before the first access to the media.

**Comment by aescolar** [comment]
@alxelax  if what you mean with "moving phy resyncing from post_init to pre_init") is calling tm_set_phy_max_resync_offset(), you can do that at any point . That is ok. In this case, there is no practical difference, as one (pre_init) is called in time 0 before booting the CPU, the other (post_init), in time 0 when the CPU goes to sleep the first time.

But looking at one of the tests, it is not ok is calling
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bsim/bluetooth/mesh/src/test_friendship.c#L52
test_common_init() -> bt_mesh_test_friendship_init() -> k_sem_init() 
in pre_init as that code is run from the HW models threads, before the CPU thread has been spawned (and the kernel is not initialized yet).
Mind you, it is also not ok to call that from post_init, as that is also called from the HW models thread, when the CPU is sleeping.

I have not checked other tests changed here, so I cannot say if what is being nor called from preinit instead of postinit is ok or not.

**Review by alxelax — CHANGES_REQUESTED** [review]
Hi @rugeGerritsen, could you revert this change for mesh tests? I'm afraid, they require better investigation to understand whether it adds indeterminism or doesn't.
Also changes cause the situation when some tests do initialization in pre_init over macro `TEST_CASE`, but some tests do initialization in post_init over macro `TEST_CASE_WBACKCHANNEL` since pre_init is used for back channel initialization.

**Review by alxelax — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Pull request merged**
