### PR TITLE
MAINTAINERS: Bluetooth Mesh: add myself as collaborator

### PR DESCRIPTION
**Pull request by KyraLengfeld**
Added KyraLengfeld as a collaborator in Bluetooth mesh.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Review by omkar3141 — APPROVED** [review]

**Review by alxelax — APPROVED** [review]

**Review by omkar3141 — CHANGES_REQUESTED** [review]
Please change commit message. It says something completely different :)

**Comment by KyraLengfeld** [comment]
> Please change commit message. It says something completely different :)

Yes, I have noticed now :D

**Review by omkar3141 — APPROVED** [review]

**Review by Balaklaka — APPROVED** [review]

**Review by MaureenHelm — COMMENTED** [review]
@PavelVPV please take a look

**Review by kartben — APPROVED** [review]

**Comment by carlescufi** [comment]
> @PavelVPV please take a look

@MaureenHelm, @PavelVPV is currently on leave. We were hoping that the approvals of @omkar3141 and @alxelax  would suffice.

**Review by PavelVPV — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
