### PR TITLE
net: openthread: Add crypto backend based on PSA API

### PR DESCRIPTION
**Pull request by Damian-Nordic**
OpenThread has lately got an option to provide a custom crypto backend that replaces the default, based on mbedTLS API. Implement a backend based on ARM PSA crypto API that is better suited for applications willing to take advantage of the ARM trust zone technology.

Add Kconfig option: `OPENTHREAD_CRYPTO_PSA_ENABLE` which enables that backend.

Also, another Kconfig option: `OPENTHREAD_PLATFORM_KEY_REFERENCES_ENABLE`, implied by the former, which enables usage of key references instead of literal keys in OpenThread. It will eventually allow OpenThread applications to keep sensitive data such as encryption keys in the secure storage, accessible from the secure world only.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

### CODE REVIEW

**Review by theotherjimmy — CHANGES_REQUESTED** [review]

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
Minor review done.

Still needs review by someone familiar with crypto API.

**Review by LuDuda — APPROVED** [review]
Looks great, thanks :+1:

**Review by frkv — CHANGES_REQUESTED** [review]
Some minor NITS

**Review by SebastianBoe — APPROVED** [review]

**Review by theotherjimmy — APPROVED** [review]

**Review by frkv — APPROVED** [review]
LGTM

**Review by rlubos — APPROVED** [review]

**Pull request merged**
