### PR TITLE
drivers: can: set default initial bitrates via Kconfig

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
- Set the default initial bitrates globally via Kconfig. The initial bitrates can still be overridden using the "bus-speed" and "bus-speed-data" devicetree properties.
- Remove all CAN controller "bus-speed" and "bus-speed-data" properties. These all use the default bitrates set via Kconfig.

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
Just an observation, how come 125 kbps/1 Mbps is the default speed.
Automotive SAE is 250 kbps/2 Mbps
https://www.sae.org/standards/content/j1939-17_202012/

**Comment by henrikbrixandersen** [comment]
> Just an observation, how come 125 kbps/1 Mbps is the default speed. Automotive SAE is 500 kbps/2 Mbps https://www.sae.org/standards/content/j1939-17_202012/

Mostly historical reasons, I guess. These bitrates have been used as the default bitrates in Zephyr since the introduction of CAN/CAN FD.

**Review by martinjaeger — DISMISSED** [review]

**Review by alexanderwachter — COMMENTED** [review]
Much easier to maintain :-)

**Review by alexanderwachter — DISMISSED** [review]

**Comment by alexanderwachter** [comment]
Intended to approve

**Review by str4t0m — COMMENTED** [review]
I think I have found one remaining occurrence in `boards/pjrc/teensy4/teensy40.dts` (line 71), I guess this was not left intentionally?
Edit: And just noticed that flexcan1 properties are overwritten in 3 seperate instances in this file.

**Comment by henrikbrixandersen** [comment]
> I think I have found one remaining occurrence in `boards/pjrc/teensy4/teensy40.dts` (line 71), I guess this was not left intentionally?

Thanks, fixed. Missed that one due to the spacing next to the braces.

> Edit: And just noticed that flexcan1 properties are overwritten in 3 seperate instances in this file.

Fixes that as well while here, thanks.

**Review by str4t0m — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
Rebased on `main` to pull in `boards/st/stm32h745i_disco`.

**Review by alexanderwachter — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Review by str4t0m — APPROVED** [review]

**Pull request merged**
