### PR TITLE
tests: add CONFIG when use HDA logging for mem_blocks test

### PR DESCRIPTION
**Pull request by shuai1x**
This PR links to https://github.com/zephyrproject-rtos/zephyr/pull/50006.
And it also links to https://github.com/zephyrproject-rtos/zephyr/pull/50402, https://github.com/zephyrproject-rtos/zephyr/pull/50403, https://github.com/zephyrproject-rtos/zephyr/pull/50516.

Add CONFIG_LOG_PRINTK=y to perfect the HDA logging.

Signed-off-by: Zhao Shuai <shuai1x.zhao@intel.com>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
Should this really be configured on a test-by-test basis? This seems very fragile. Why not configure it globally for these boards?

**Comment by shuai1x** [comment]
> Should this really be configured on a test-by-test basis? This seems very fragile. Why not configure it globally for these boards?

Because we configure it when we only want to use HDA logging, but most of cases are using winstream. And only these three tests will fail due to missing logs that is caused by winstream. So we want to use HDA logging to fix this problem. But not all the cases need to use HDA logging, we can't abandon winstream.

**Comment by nashif** [comment]
Please see if #50623 fixes the issues and remove all HDA logging changes from those tests.

**Review by nashif — CHANGES_REQUESTED** [review]
Please see if #50623 fixes this problem, this change is a workaround and does not scale.

**Comment by shuai1x** [comment]
> Please see if #50623 fixes this problem, this change is a workaround and does not scale.

I tested the PR https://github.com/zephyrproject-rtos/zephyr/pull/50623 on CAVS platform five times. And it would pass stably, so this PR would also fix this issue. @nashif

**Comment by henrikbrixandersen** [comment]
Closing as fixed by #50623. Please reopen if that is not the case.

**Pull request closed without merging**
