### PR TITLE
mgmt: Reduce user data requirement

### PR DESCRIPTION
**Pull request by jhedberg**
These two patches take a different approach to what #8209 was trying to fix.

Currently only build tested, so looking for runtime testers :)

### CODE REVIEW

**Comment by pfalcon** [comment]
@ccollins476ad: FYI

**Review by carlescufi — APPROVED** [review]
Nice! LGTM but I will let @Vudentz approve before we merge

**Comment by carlescufi** [comment]
@nvlsianpu @Vudentz can you take a look?

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by nvlsianpu** [comment]
I will just test it in a minute, the approve.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
tested, works well.

**Pull request merged**
