### PR TITLE
tests: kernel: interrupt: Provide slight delay after irq_unlock

### PR DESCRIPTION
**Pull request by galak**
On qemu_x86 with LLVM we see this test fail due to how its generates code between the irq_unlock and zassert check.  We need to provide a little delay to allow the interrupt events to get processed before we do any checking.

Signed-off-by: Kumar Gala <kumar.gala@intel.com>

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Comment by andyross** [comment]
Hm... if this is a code generation bug with the ordering around the irq_unlock(), then we're probably missing a barrier somewhere.  The fix should be to make the compiler emit the right ordering, not to insert a delay?

Basically this can't be the right fix as I see it.  If interrupts are unlocked and there's an interrupt pending we absolutely shouldn't be running even one cycle of user mode code after the CLI instruction.  If it were hardware (e.g. setting a GPIO that then is wired back to an interrupt pin), I'd believe that maybe the interrupt is taking a while to propagate through the APIC.  But on qemu?  Surely that's synchronous, right?

Can you try replacing that sleep with a memory clobber (`__asm__ volatile("", ::: "memory");`) and see if that does anything?

**Comment by galak** [comment]
> Hm... if this is a code generation bug with the ordering around the irq_unlock(), then we're probably missing a barrier somewhere. The fix should be to make the compiler emit the right ordering, not to insert a delay?
> 
> Basically this can't be the right fix as I see it. If interrupts are unlocked and there's an interrupt pending we absolutely shouldn't be running even one cycle of user mode code after the CLI instruction. If it were hardware (e.g. setting a GPIO that then is wired back to an interrupt pin), I'd believe that maybe the interrupt is taking a while to propagate through the APIC. But on qemu? Surely that's synchronous, right?
> 
> Can you try replacing that sleep with a memory clobber (`__asm__ volatile("", ::: "memory");`) and see if that does anything?

So it fails with just the memory clobber.  I've added just a nop, and that works.  I'm guessing this is a qemu issue when when its posting the interrupt:

This version w/nop passes:
```
  100b7b: fb                            sti
  100b7c: 90                            nop
  100b7d: a1 68 c2 10 00                movl    1098344, %eax
  100b82: 83 f8 02                      cmpl    $2, %eax
```

This version w/o nop fails:
  100b7b: fb                            sti
  100b7c: 90                            nop
  100b7d: a1 68 c2 10 00                movl    1098344, %eax
  100b82: 83 f8 02                      cmpl    $2, %eax

**Comment by galak** [comment]
> > Hm... if this is a code generation bug with the ordering around the irq_unlock(), then we're probably missing a barrier somewhere. The fix should be to make the compiler emit the right ordering, not to insert a delay?
> > Basically this can't be the right fix as I see it. If interrupts are unlocked and there's an interrupt pending we absolutely shouldn't be running even one cycle of user mode code after the CLI instruction. If it were hardware (e.g. setting a GPIO that then is wired back to an interrupt pin), I'd believe that maybe the interrupt is taking a while to propagate through the APIC. But on qemu? Surely that's synchronous, right?
> > Can you try replacing that sleep with a memory clobber (`__asm__ volatile("", ::: "memory");`) and see if that does anything?
> 
> So it fails with just the memory clobber. I've added just a nop, and that works. I'm guessing this is a qemu issue when when its posting the interrupt:
> 
> This version w/nop passes:
> 
> ```
>   100b7b: fb                            sti
>   100b7c: 90                            nop
>   100b7d: a1 68 c2 10 00                movl    1098344, %eax
>   100b82: 83 f8 02                      cmpl    $2, %eax
> ```
> 
> This version w/o nop fails:
> 
> ```
>   100b7b: fb                            sti
>   100b7c: 90                            nop
>   100b7d: a1 68 c2 10 00                movl    1098344, %eax
>   100b82: 83 f8 02                      cmpl    $2, %eax
> ```

@andyross this really looks like a QEMU timing issue.  I can change the code to be:

```
 #ifdef CONFIG_QEMU_TARGET
 arch_nop();
  #endif
```

**Review by andyross — COMMENTED** [review]
Sorry, getting back to this.  I guess I'd be more comfortable with a NOP (and a comment explaining that it works around a delay with interrupt delivery on qemu) than a sleep, yeah. :)

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Looks great, thanks.

**Review by nashif — APPROVED** [review]

**Pull request merged**
