### PR TITLE
Misc TCP2 fixes

### PR DESCRIPTION
**Pull request by jukkar**
This contains a fix to #28216. It also has some minor tweaks I noticed while creating the PR. I considered creating a separate PR for those minor things but as the commits are very small and clear, I send all in this on PR.

### CODE REVIEW

**Review by rlubos — APPROVED** [review]
Looks good, I've tested the changes with echo samples and I haven't spotted any unexpected behaviour with these changes (I could observe sporadic disconnects before with high traffic).

**Comment by jukkar** [comment]
I found out some corner cases so I am adding couple of more patches and some fixes to existing ones. Marking this as DNM for time being.

**Comment by jukkar** [comment]
Fixed a ton of corner cases, seems to work ok in my testing but please try if you can. This is very much needed in 2.4 so lets try to get this in.

**Review by nashif — APPROVED** [review]

**Comment by pfalcon** [comment]
I was on vacation last week, so testing this only now. And - I was able to run `ab -n100000 http://192.0.2.1:8080/` against `dump_http_server`:

```
Time taken for tests:   1297.976 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      218100000 bytes
HTML transferred:       212200000 bytes
Requests per second:    77.04 [#/sec] (mean)
...
Percentage of the requests served within a certain time (ms)
  50%     13
  66%     14
  75%     14
  80%     14
  90%     15
  95%     17
  98%     18
  99%     18
 100%     26 (longest request)
```

This is totally unbelievable, I never was able to do that. With my initial TCP2 testing (https://github.com/zephyrproject-rtos/zephyr/issues/27876 and fix), it guaranteedly crashed with `-n10000`, and with TCP1, `-n10000` could easily stall. The result is even more amazing knowing that there're issues with QEMU UART handling (https://github.com/zephyrproject-rtos/zephyr/issues/8187). So, some of SLIP packets received are broken, and the stack not just copes with them, it does so in a way to not affect performance (see percentage histogram above, which is quite flat).

Great work, @jukkar! (And keeping fingers that the results are sustainable.) This is a8ffc03f6eb/qemu_x86 so far. Will be busy with a virtual conference this week, but will try to test newer revisions, and on real hardware.

Also tested `big_http_download` - it works, with about the same (slow) speed. Maybe we should add the speed output to it after all, and target stack performance as the next milestone.

**Pull request merged**
