### PR TITLE
tests: bluetooth: tester: Add nrf54l15dk and remove nrf54l15pdk

### PR DESCRIPTION
**Pull request by m-alperen-sener**
Rename the config files according to nrf54l15dk.

### CODE REVIEW

**Review by Thalley — CHANGES_REQUESTED** [review]
Commit message does not match the content of the commit. This only adds a new platform, and does not change any existing entry of the nRF54l15

**Comment by cvinayak** [comment]
> Commit message does not match the content of the commit. This only adds a new platform, and does not change any existing entry of the nRF54l15

May be two commits? one for rename of files and other to add the target for CI coverage.

FYI, open source Controller implementation does not support entropy, crypto and encryption features yet.

**Comment by m-alperen-sener** [comment]
> Commit message does not match the content of the commit. This only adds a new platform, and does not change any existing entry of the nRF54l15

I split the commit to make it more clear, and updated the commit message to clarify the changes.

**Comment by m-alperen-sener** [comment]
> > Commit message does not match the content of the commit. This only adds a new platform, and does not change any existing entry of the nRF54l15
> 
> May be two commits? one for rename of files and other to add the target for CI coverage.
> 
> FYI, open source Controller implementation does not support entropy, crypto and encryption features yet. I see CI passing in this PR, not sure if the added target is being covered here for build failures?

I might need insight on that a bit more; I though it would be better to have at least build test since the board is added here even though it has not complete support yet.

**Review by Thalley — DISMISSED** [review]

**Comment by cvinayak** [comment]
> > > Commit message does not match the content of the commit. This only adds a new platform, and does not change any existing entry of the nRF54l15
> > 
> > 
> > May be two commits? one for rename of files and other to add the target for CI coverage.
> > FYI, open source Controller implementation does not support entropy, crypto and encryption features yet. I see CI passing in this PR, not sure if the added target is being covered here for build failures?
> 
> I might need insight on that a bit more; I though it would be better to have at least build test since the board is added here even though it has not complete support yet.

the target is added to testcase.yaml.... is this build in this PR CI? is there a easy way to look here in this PR?

**Comment by m-alperen-sener** [comment]
> > > > Commit message does not match the content of the commit. This only adds a new platform, and does not change any existing entry of the nRF54l15
> > > 
> > > 
> > > May be two commits? one for rename of files and other to add the target for CI coverage.
> > > FYI, open source Controller implementation does not support entropy, crypto and encryption features yet. I see CI passing in this PR, not sure if the added target is being covered here for build failures?
> > 
> > 
> > I might need insight on that a bit more; I though it would be better to have at least build test since the board is added here even though it has not complete support yet.
> 
> the target is added to testcase.yaml.... is this build in this PR CI? is there a easy way to look here in this PR?

Apparently twister test coverage does not include build for real target; I am removing the commit for adding nrf54l15 to test.yml for now.

**Review by Thalley — CHANGES_REQUESTED** [review]
Please remove the `- Adding the target nrf54ldk and removing the target nrf54lpdk.` part of the commit message, as this now only renames the config files

**Review by cvinayak — APPROVED** [review]

**Review by sjanc — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Pull request merged**
