### PR TITLE
hwinfo: stm32: Enable PIN_RESET only if there were no other causes

### PR DESCRIPTION
**Pull request by yonsch**
STM32 SoCs implement various reset types by pulling the reset
pin low. Therefore, these reset types set the PINRST flag, even
if the reset was not caused by an actual pin reset event.
To fix this, the driver should check the PINRST flag last,
and set PIN_RESET only if the other flags are unset.

Signed-off-by: Yonatan Schachter <yonatan.schachter@gmail.com>

### CODE REVIEW

**Comment by yonsch** [comment]
I could not find this behavior in the official documentation, but I have experienced it myself and found it documented [here](http://www.micromouseonline.com/2012/03/29/stm32-reset-source/)

**Comment by alexanderwachter** [comment]
Not sure if this change is a good idea. I would prefer to let the user decide to ignore this flag.
Lets assume an application is only looking for pin resets, and therefor only resets the flags at pin reset. Then the application would miss this event. Or if multiple resets occur (power and pin), then the pin reset is not set even it should be there.

**Review by alexanderwachter — CHANGES_REQUESTED** [review]
Blocking for now. See comment

**Comment by yonsch** [comment]
Thanks, @alexanderwachter . I see your point, yet I still think there is an issue here.
Letting the user ignore this flag assumes that the user knows that this flag can be set even if there was no actual pin reset, which is a behavior that is not documented in `hwinfo`, nor in the reference manual (It probably is documented somewhere, though I was not able to find it).
Second, even if the user does know about this issue, handling this in user code means that this code is not portable between different platforms, or that it has to be `ifdef`ed for each platform. Portability, at least to me, is why I would use `hwinfo` in the first place. If I wanted something very specific to the platform that I was using, I would use the HAL directly. If I use a cross platform API like hwinfo, I would expect that I at least get consistent results across platforms.
Lastly, I think that returning PIN_RESET if there was no pin reset is wrong, even though this is what the RCC claims. I am sure there were good reasons behind the design decision of doing so, but I believe most users will prefer to have this feature hidden from them. If the API claims that PIN_RESET is set when the SoC is reset through the reset pin, then I wouldn't expect to see it after a software reset. Wrapping this with `hwinfo`, gives Zephyr a chance to "fix" this "confusion".
Of course, this is my opinion, and I may be wrong. Perhaps a better implementation could be devised, or another flag could be added to distinguish between actual pin resets and "virtual" pin resets. Anyway, thanks for your time.

**Comment by alexanderwachter** [comment]
Still I think we should not mask it.

**Review by FRASTM — APPROVED** [review]

**Comment by yonsch** [comment]
Although I still think that the different implementations should return uniform results across platforms (just like both iwdg and wwdg are masked to simply WATCHDOG_RESET), I agree with @alexanderwachter that these changes might not have the expected effects for every use case. Perhaps it should be documented that hwinfo expects the user to always clear the reset cause upon reset, or alternatively, make this behaviour configurable. Anyways, I'm ambivalent about this myself now.

**Comment by cfriedt** [comment]
@erwango - are you able to weigh-in here?

I'm leaning toward agreeing with @alexanderwachter. However, I wonder if there needs to be a generic test to check against what @yonsch has described... or for it as the case may be.

**Comment by yonsch** [comment]
Maybe adding a `hwinfo_get_reset_cause_raw` that returns the flags as they are.
Or, adding helper functions/macros for accessing the reset causes, such as `hwinfo_is_pin_reset` which are guaranteed to return the same value on every platform.

**Comment by ycsin** [comment]
> It probably is documented somewhere, though I was not able to find it

I implemented this manually in my application (didn't know `z_impl_hwinfo_get_reset_cause` exists until I see this PR) recently and I also noticed this, I also don't see this documented anywhere.
image

I'm also considering to remove the PINRST flag if other flag is set in my application for the sake of displaying them easily in a piechart. But I'm not sure if I'd remove it directly in the `z_impl_hwinfo_get_reset_cause`.

**Review by FRASTM — APPROVED** [review]

**Comment by erwango** [comment]
@yonsch, @alexanderwachter Closing as consensus in the fact that current implementation is finally ok.

**Pull request closed without merging**
