### PR TITLE
dts: Replace deprecated DT_OPENISA_RV32M1_* macros with DT_ALIAS_*

### PR DESCRIPTION
**Pull request by ulfalizer**
scripts/dts/gen_defines.py currently generates prefixes from properties
in aliases/ in two formats:

    DT_ALIAS_<property>_*
    DT_<compatible of pointed-to node>_<property>_*

For example, 'aliases { usart-0 = &usart0; }' generates

    DT_ALIAS_USART_0_*
    DT_NXP_LPC_USART_USART_0_*

when the &usart0 node has 'compatible = "nxp,lpc-usart"'.

The second form exists for backwards compatibility. It's spammy and hard
to read, and easy to confuse for DT_\<compatible>\_\<unit address>_*, which
also gets generated for devicetree nodes.

The code in gen_defines.py that generates the deprecated form has a
'# TODO: See if we can remove or deprecate this form' Comment over it.

Update all macros that come from /aliases to use the DT_ALIAS_* form,
for macros prefixed with DT_OPENISA_RV32M1_*.

### CODE REVIEW

**Review by henrikbrixandersen — COMMENTED** [review]
Don’t we usually use `DT_INST_` for driver device instances? Aliases are more of an application thing?

**Comment by ulfalizer** [comment]
> Don’t we usually use `DT_INST_` for driver device instances? Aliases are more of an application thing?

These are/were using aliases at least, and include the name of the property in their name. It's just easier to see now.

Maybe other cleanups could be done separately.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
> These are/were using aliases at least, and include the name of the property in their name. It's just easier to see now.

Ah, that was not clear to me.
 
> Maybe other cleanups could be done separately.

OK.

**Comment by ulfalizer** [comment]
(Copy-pasting this into all PRs just so people don't misunderstand it.)

To clarify, this is not adding any new alias macros. All of the replaced macros were already being generated from aliases. This is just converting from an old and bad form of macros generated from aliases to the better `DT_ALIAS_*` form.

Further improvements might be possible, like switching some of them over to `DT_INST_*`. I want to get rid of the old and bad form of alias macros first though, because it can be done somewhat mechanically (though it's still a lot of tiring manual tinkering).

**Pull request merged**
