### PR TITLE
sanitycheck: mark arc simulation smp systems as mdb

### PR DESCRIPTION
**Pull request by nashif**
This changes back smp simulation systems to require mdb.

### CODE REVIEW

**Comment by andrewboie** [comment]
I don't think this will work right with the other changes that went into https://github.com/zephyrproject-rtos/zephyr/commit/6f6fddf7e9c43e226a57ce5a77e22641bf3bb61c

please, let's just revert it (I have updated #28028) to do this

**Review by tyrantlizard77 — DISMISSED** [review]
this doesn't work

https://github.com/zephyrproject-rtos/zephyr/commit/6f6fddf7e9c43e226a57ce5a77e22641bf3bb61c 
 removed cmake/emu/mdb.cmake 

please, lets just revert it

**Comment by nashif** [comment]
> this doesn't work

what does not work? the cmake file is not related to sanitycheck.

**Comment by nashif** [comment]
> there are no clauses in sanitylib.py that check `platform.simulation "mdb"`

If forgot to add it, now it is there, this should work and I did test it with a dummy mdb executable.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]
Thanks for taking care of that.

**Comment by ruuddw** [comment]
I believe the idea was that since mdb is not a simulator, just a way to start the simulator using the mdb debugger, it was cleaner to always call it nsim, but use either nsimdrv or mdb to launch. But for SMP nsimdrv cannot be used, so maybe the selection logic should first try and use mdb, and if not available nsimdrv. Maybe with a way to override via env variable.

**Comment by nashif** [comment]
>  so maybe the selection logic should first try and use mdb, and if not available nsimdrv.

ok, but this will fail and we will be back at square one. If we do not find mdb and retry with nsimdrv instead, it will fail for SMP targets..

**Comment by andrewboie** [comment]
> I believe the idea was that since mdb is not a simulator, just a way to start the simulator using the mdb debugger, it was cleaner to always call it nsim, but use either nsimdrv or mdb to launch. But for SMP nsimdrv cannot be used, so maybe the selection logic should first try and use mdb, and if not available nsimdrv. Maybe with a way to override via env variable.

@ruuddw the tree is broken right now. This is a hotfix so that people with nsindrv and not mdb don't have their sanitycheck runs failing all over the place.
We are not going to leave the tree broken while the best solution is debated.
This is going to go in, if you want to make further enhancements to this mechanism please send them as followup patches.

**Comment by ruuddw** [comment]
I have no problem with this 'hotfix' if it helps you - just want to make sure we can use sanitycheck with nsim_hs_smp if mdb is installed. Filtering out the nsim_hs_smp tests when the required tools are not installed is imho a different topic.

**Pull request merged**
