### PR TITLE
drivers: modem: gsm: FSM implementation

### PR DESCRIPTION
**Pull request by ycsin**
This PR is based on my previous implementation (#38596) with a bit of polish (MISRA-related) here and there, but it is not tested on a real hardware.

### CODE REVIEW

**Comment by bbilas** [comment]
I've tested these patch series using `Telit ME910G1-W1` module and it works well however I would set the gsm state as stopped when the interface is down, let's see:

<pre>
 drivers/modem/gsm_ppp.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/drivers/modem/gsm_ppp.c b/drivers/modem/gsm_ppp.c
index c3462aa247..add3a37ca0 100644
--- a/drivers/modem/gsm_ppp.c
+++ b/drivers/modem/gsm_ppp.c
@@ -1250,6 +1250,7 @@ static void gsm_mgmt_event_handler(struct net_mgmt_event_callback *cb,

        if (mgmt_event == NET_EVENT_IF_DOWN) {
                LOG_INF("GSM network interface down");
+               gsm.state = GSM_PPP_STOP;
                /* raise semaphore to indicate the interface is down */
                k_sem_give(&gsm.sem_if_down);
                return;
</pre>

I had a case when the network interface was down and I wasn't able to re-run it again without power-cycle because it was still active.

```<inf> modem_gsm: Manufacturer: Telit
<inf> modem_gsm: Model: ME910G1-W1
<inf> modem_gsm: Revision: M0C.300003
<inf> modem_gsm: IMEI: XX
<inf> modem_gsm: IMSI: XX
<inf> modem_gsm: ICCID: XX
<inf> modem_gsm: Searching for network...
<inf> modem_gsm: Searching for network...
<inf> modem_gsm: Network registered, roaming.
<inf> modem_gsm: Attached to packet service!
<inf> modem_gsm: RSSI: -1000
<inf> modem_gsm: RSSI: -69
<inf> modem_gsm: RSSI: -69
<inf> modem_gsm: RSSI: -67
<inf> modem_gsm: RSSI: -67
<inf> modem_gsm: RSSI: -67
<inf> modem_gsm: RSSI: -67
<inf> modem_gsm: RSSI: -67
<inf> modem_gsm: RSSI: -67
<inf> modem_gsm: RSSI: -67
<inf> modem_gsm: RSSI: -67
<inf> net_ppp: Initializing PPP to use UART_8
<inf> modem_app: Modem is ready
uart:~$ net iface

Interface 0x20203770 (PPP) [1]
==============================
Link addr : XX
MTU       : 1500
Flags     : NO_AUTO_START,IPv4
IPv4 unicast addresses (max 1):
        XX manual preferred infinite
IPv4 multicast addresses (max 1):
        <none>
IPv4 gateway : 0.0.0.0
IPv4 netmask : 0.0.0.0
uart:~$ net ping 8.8.8.8
PING 8.8.8.8
28 bytes from 8.8.8.8 to XX: icmp_seq=0 ttl=51 time=272 ms
28 bytes from 8.8.8.8 to XX: icmp_seq=1 ttl=51 time=139 ms
28 bytes from 8.8.8.8 to XX: icmp_seq=2 ttl=51 time=176 ms
uart:~$ 
<inf> modem_app: Modem is disconnected
<inf> modem_gsm: GSM network interface down
uart:~$ modem_gsm start
<err> modem_gsm: gsm_ppp is already started
uart:~$ modem_gsm stop
<wrn> modem_gsm: Failed locking modem cmds!
```

**Review by rerickson1 — APPROVED** [review]

**Comment by ycsin** [comment]
@bbilas this is the expected behavior that the modem must be explicitly stopped before it can be started again. 
The driver probably needs some recovery mechanism in the future

**Comment by bbilas** [comment]
> @bbilas thanks for testing this!
> 
> This is the expected behavior that the modem must be explicitly stopped before it can be started again. The driver probably needs some recovery mechanism in the future

Ok, I'll handle that somehow in my app then. The recovery mechanism would be so useful for my case and at first look it shouldn't be difficult to implement.

**Review by bbilas — APPROVED** [review]

**Comment by ycsin** [comment]
> The recovery mechanism would be so useful for my case and at first look it shouldn't be difficult to implement.

Would be a very nice addition if you don't mind taking this!

**Pull request merged**
