### PR TITLE
up_squared: use HPET timer and fixes some tests

### LINKED ISSUE #67356: up_squared: tests/kernel/workq/user_work/kernel.workqueue.user fail
**Describe the bug**
`tests/kernel/workq/user_work/kernel.workqueue.user`
fail.

**To Reproduce**
twister --device-testing --hardware-map up2.map -s tests/kernel/workq/user_work/kernel.workqueue.user -vv

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v3.5.0-3808-gabafe9bbe24c ***
DEBUG   - DEVICE: Running TESTSUITE workqueue_api
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_workq_user_mode
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/workq/user_work/src/main.c:90: test_k_work_user_submit_to_queue_fail: k_work_user_is_pending(&work[0]) is true
DEBUG   - DEVICE: 
DEBUG   - DEVICE: FAIL - test_workq_user_mode in 0.018 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: TESTSUITE workqueue_api failed.
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY START ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: SUITE FAIL -   0.00% [workqueue_api]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.018 seconds
DEBUG   - DEVICE: - FAIL - [workqueue_api.test_workq_user_mode] duration = 0.018 seconds
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ------ TESTSUITE SUMMARY END ------
DEBUG   - DEVICE: 
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: RunID: dafe8b915969f2351f939adbc68c2efc
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
```
**Environment:**
- OS: Linux
- Toolchain: zephyr-sdk-0.16.3
- zephyr-v3.5.0-3808-gabafe9bbe24c

### LINKED ISSUE #68616: up_squared: tests/lib/c_lib/thrd - many tests fail
**Describe the bug**

list of failing c_lib tests:
I did a bisection last week and found a commit that breaks the tests: https://github.com/zephyrproject-rtos/zephyr/commit/eefaeee061c869cfa33be9693ff186ca60f76ff9. But now we have build fail before this commit.
```
tests/lib/c_lib/thrd/libraries.libc.c11_threads.minimal 
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc 
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.module
tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc.notls 
tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib 
tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib_nano 
```

**To Reproduce**
`twister --device-testing --hardware-map up2.map -T tests/lib/c_lib/thrd/ -vv`

**Logs and console output**
too many tests fail, here is an example output:
```
DEBUG   - DEVICE: >>Checking Media Presence......
DEBUG   - DEVICE: >>Media Present......
DEBUG   - DEVICE: Downloading NBP file...
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Succeed to download NBP file.
DEBUG   - DEVICE: *** Zephyr EFI Loader ***
DEBUG   - DEVICE: RSDP found at 0x79c34000
DEBUG   - DEVICE: Zeroing 12292096 bytes of memory at 0x13c000
DEBUG   - DEVICE: Zeroing 1112 bytes of memory at 0xf1bba8
DEBUG   - DEVICE: Copying 32768 data bytes to 0x1000 from image offset
DEBUG   - DEVICE: Copying 245760 data bytes to 0x100000 from image offset 32768
DEBUG   - DEVICE: Copying 2255784 data bytes to 0xcf5000 from image offset 278528
DEBUG   - DEVICE: Jumping to Entry Point: 0x1137 (48 31 c0 48 31 d2 48)
DEBUG   - DEVICE: *** Booting Zephyr OS build v3.6.0-rc1-8-gf6ecad20a1e7 ***
DEBUG   - DEVICE: Running TESTSUITE libc_cnd
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_cnd_broadcast_wait
DEBUG   - DEVICE: ASSERTION FAIL [__attr_is_initialized(attr)] @ WEST_TOPDIR/zephyr/lib/posix/options/pthread.c:808
DEBUG   - DEVICE: E: RAX: 0x0000000000000004 RBX: 0x000000000013d590 RCX: 0x0000000000000001 RDX: 0x0000000000000000
DEBUG   - DEVICE: E: RSI: 0x0000000000000328 RDI: 0x0000000000135225 RBP: 0x0000000000ceaec0 RSP: 0x0000000000ceaea8
DEBUG   - DEVICE: E:  R8: 0x0000000000000008  R9: 0x0000000000ceac00 R10: 0x00000000ffffffff R11: 0x0000000000cead10
DEBUG   - DEVICE: E: R12: 0x0000000000000000 R13: 0x0000000000100407 R14: 0x000000000013c010 R15: 0x000000000013d590
DEBUG   - DEVICE: E: RSP: 0x0000000000ceaea8 RFLAGS: 0x0000000000000246 CS: 0x0018 CR3: 0x0000000000f1a000
DEBUG   - DEVICE: E: RIP: 0x0000000000103687
DEBUG   - DEVICE: E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
DEBUG   - DEVICE: E: Current thread: 0x13ea40 (test_cnd_broadcast_wait)
DEBUG   - DEVICE: Caught system error -- reason 4 0
DEBUG   - DEVICE: Fatal error was unexpected, aborting...
```

**Environment:**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.3
 - v3.6.0-rc1-8-gf6ecad20a1e7

### PR DESCRIPTION
**Pull request by dcpleung**
* tests: workq/user_work: change how resource pool is exhausted
* tests: c_lib/thrd: more stack for up_squared board
* boards: x86/up_squared: use HPET timer

Fixes #68616

### CODE REVIEW

**Review by laurenmurphyx64 — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by najumon1980** [comment]
Suggest to use overlay file in test app instead of changed default APIC TSC timer to HPET in board configuration.

**Review by peter-mitsis — APPROVED** [review]

**Comment by nashif** [comment]
is this fixing 68616, if so, added "Fixes #68616" to the body

**Review by finikorg — APPROVED** [review]

**Comment by dcpleung** [comment]
> Suggest to use overlay file in test app instead of changing default APIC TSC timer to HPET in board configuration.

The issue is that UP Squared boards can be ordered with different CPUs running at different speed. Using HPET is the only way to target all these SKUs with correct real world timing.

**Comment by andyross** [comment]
> The issue is that UP Squared boards can be ordered with different CPUs running at different speed. Using HPET is the only way to target all these SKUs with correct real world timing.

Sorry, for clarity: you're saying that different devices are sold with different clocking, but we need to use them all with the same binary Zephyr build and can't discriminate with kconfig/DTS, right?  Not that different cores on the **same** device are showing skew between their TSC values (which would be a hardware bug with the invariant TSC).

**Comment by dcpleung** [comment]
> > The issue is that UP Squared boards can be ordered with different CPUs running at different speed. Using HPET is the only way to target all these SKUs with correct real world timing.
> 
> Sorry, for clarity: you're saying that different devices are sold with different clocking, but we need to use them all with the same binary Zephyr build and can't discriminate with kconfig/DTS, right? Not that different cores on the **same** device are showing skew between their TSC values (which would be a hardware bug with the invariant TSC).

Not necessarily the same binary. The default clock rate (in board config) is 1.6GHz with APIC timer, for Atom. So if someone buys a board with Pentium or Celeron, which runs at 1.1GHz, they will be very confused on why the board would sleep ~15 seconds instead of the commanded 10 seconds if they use the board config as-is. Therefore, since the board config is "generic" to all variants of UP Squared (i.e. applies to all SKUs), we should use HPET as the base clock rate is the same on all of them. Also note that the DTS specifies 2GB as main memory size even though you can get boards with 8GB memory.

**Pull request merged**
