### PR TITLE
drivers: sensor: mcp9600: fix wrong register address

### LINKED ISSUE #66150: drivers: sensor: MCP9600: Wrong register addresses
Most of the internal registers of the MCP9600 in the code have wrong addresses.

Starting [from ](https://github.com/zephyrproject-rtos/zephyr/blob/3d3b287b7908625dc8356ac3532d9b6943edbb50/drivers/sensor/mcp9600/mcp9600.c#L28) the `MCP9600_REG_A1_CONFIG`, all registers with higher addresses have wrong address.

From TABLE 5-1 in the [datasheet ](https://ww1.microchip.com/downloads/en/DeviceDoc/MCP960X-Data-Sheet-20005426.pdf) we can see the list of registers: 

image

### PR DESCRIPTION
**Pull request by naNEQ**
The address of most of the registers defined in
the driver are wrong. This fixes it, following
the correct numbering as can be found in the
device's datasheet. Addresses #66150.

### CODE REVIEW

**Review by tristan-google — DISMISSED** [review]
Welcome to the Zephyr project and thank you for submitting a patch. I checked these against [this datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/MCP960X-Data-Sheet-20005426.pdf) and they appear correct. Would you be able to also adjust the blank lines so the config, hysteresis, and limit macros are each grouped together?

**Comment by naNEQ** [comment]
> Welcome to the Zephyr project and thank you for submitting a patch. I checked these against [this datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/MCP960X-Data-Sheet-20005426.pdf) and they appear correct. Would you be able to also adjust the blank lines so the config, hysteresis, and limit macros are each grouped together?

Do I push to the same branch? And what about the commit message, the same as before?

**Comment by kartben** [comment]
You may just *amend* your existing commit, and then just force push to your branch, since in this case the changes to the blank lines are not worth having in a separate commit IMO. Feel free to mention it in the updated commit message though.
Thanks!

**Review by kartben — APPROVED** [review]
Very nice, thank you very much @naNEQ!

**Review by aasinclair — APPROVED** [review]

**Review by tristan-google — APPROVED** [review]
Thank you!

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
