### PR TITLE
West v1.2.0 docs

### PR DESCRIPTION
**Pull request by mbolivar-ampere**
Add release notes for this version.

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]
LGTM, I don't think we need to change the the required version in west.yml until we add actual `description:` fields, agreed @mbolivar-ampere ?

**Comment by mbolivar-ampere** [comment]
> agreed @mbolivar-ampere ?

agreed

**Review by jhedberg — DISMISSED** [review]

**Comment by mbolivar-ampere** [comment]
@jhedberg @carlescufi docs build finally passing, please revisit

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
LGTM

**Pull request merged**
