### PR TITLE
Migrate internal code to the public iterable section APIs

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Hey hi, this is a followup to https://github.com/zephyrproject-rtos/zephyr/pull/37410, which dropped the "Z_" prefix from the iterable section macros and grouped them together in a doc page.

Four patches in this PR:
- rename all the internal calls to use the non `Z_` macro, tried to keep the coding stile consistent for each file
-  move the implementation to the non`Z_` macros and mark the old one as `__DEPRECATED_MACRO` (could not do it for the linker ones though, seems like the warning is a gcc thing)
- add a unit test for the functionality, this validates RAM and ROM sections for various architectures and key sorting
- expand the documentation to add a usage example

Let me know what you think.

### CODE REVIEW

**Comment by cfriedt** [comment]
I'm fine with this - is there an issue associated with these changes?

**Comment by cfriedt** [comment]
LGTM

**Comment by fabiobaltieri** [comment]
(merge conflict, rebased and updated)

**Review by cfriedt — APPROVED** [review]

**Review by cfriedt — CHANGES_REQUESTED** [review]
I think I need to remove my +1 for now, because a separate PR just reminded me of another iterable macro - `Z_LINK_ITERABLE_ALIGNED`. 

Please have a look and see if it makes sense to work that into this PR.

https://github.com/zephyrproject-rtos/zephyr/pull/37641

**Comment by fabiobaltieri** [comment]
> I think I need to remove my +1 for now, because a separate PR just reminded me of another iterable macro - `Z_LINK_ITERABLE_ALIGNED`.
> 
> Please have a look and see if it makes sense to work that into this PR.
> 
> #37641

Hey, yeah I saw those and it made sense to me to leave them alone (as in: Z_ prefixed, internal). Not too sure why the esp32 linker files uses them directly rather than the section macros. Xtensa SoCs seem to not have a common linker script and do things somewhat differently than the others, but for usage outside of the core code I think that the ones I covered here should do.

If there's a use case you know about I'm happy to document that one as well. Or I guess we can always add it later if someone needs it.

**Comment by dcpleung** [comment]
The ESP32 tools to stitch binary images can only deal with at max 16 sections. That's why it has to use `Z_LINK_ITERABLE_ALIGNED()` directly instead of including those common linker snippets.

**Review by dcpleung — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Pull request merged**
