### PR TITLE
dts: arm: nxp: lpc55s1x: add ctimer nodes

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add CTimer devicetree nodes for the NXP LPC55S1x.

Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
```
*** Booting Zephyr OS build v3.7.0-rc2-46-g866fa6ad69e5 ***
Running TESTSUITE counter_basic
===================================================================
START - test_all_channels
Testing ctimer@8000
Testing ctimer@9000
Testing ctimer@28000
Testing ctimer@29000
Testing ctimer@2A000
 PASS - test_all_channels in 0.661 seconds
===================================================================
START - test_cancelled_alarm_does_not_expire
Skipped for ctimer@8000
Skipped for ctimer@9000
Skipped for ctimer@28000
Skipped for ctimer@29000
Skipped for ctimer@2A000
 SKIP - test_cancelled_alarm_does_not_expire in 0.512 seconds
===================================================================
START - test_late_alarm
Skipped for ctimer@8000
Skipped for ctimer@9000
Skipped for ctimer@28000
Skipped for ctimer@29000
Skipped for ctimer@2A000
 SKIP - test_late_alarm in 0.512 seconds
===================================================================
START - test_late_alarm_error
Skipped for ctimer@8000
Skipped for ctimer@9000
Skipped for ctimer@28000
Skipped for ctimer@29000
Skipped for ctimer@2A000
 SKIP - test_late_alarm_error in 0.512 seconds
===================================================================
START - test_multiple_alarms
Testing ctimer@8000
Testing ctimer@9000
Testing ctimer@28000
Testing ctimer@29000
Testing ctimer@2A000
 PASS - test_multiple_alarms in 0.780 seconds
===================================================================
START - test_set_top_value_with_alarm
Testing ctimer@8000
Testing ctimer@9000
Testing ctimer@28000
Testing ctimer@29000
Testing ctimer@2A000
 PASS - test_set_top_value_with_alarm in 1.055 seconds
===================================================================
START - test_short_relative_alarm
Skipped for ctimer@8000
Skipped for ctimer@9000
Skipped for ctimer@28000
Skipped for ctimer@29000
Skipped for ctimer@2A000
 SKIP - test_short_relative_alarm in 0.517 seconds
===================================================================
START - test_single_shot_alarm_notop
Testing ctimer@8000
Testing ctimer@9000
Testing ctimer@28000
Testing ctimer@29000
Testing ctimer@2A000
 PASS - test_single_shot_alarm_notop in 0.860 seconds
===================================================================
START - test_single_shot_alarm_top
Testing ctimer@8000
Testing ctimer@9000
Testing ctimer@28000
Testing ctimer@29000
Testing ctimer@2A000
 PASS - test_single_shot_alarm_top in 0.860 seconds
===================================================================
TESTSUITE counter_basic succeeded
Running TESTSUITE counter_no_callback
===================================================================
START - test_set_top_value_without_alarm
Testing ctimer@8000
Testing ctimer@9000
Testing ctimer@28000
Testing ctimer@29000
Testing ctimer@2A000
 PASS - test_set_top_value_without_alarm in 0.536 seconds
===================================================================
TESTSUITE counter_no_callback succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [counter_basic]: pass = 5, fail = 0, skip = 4, total = 9 duration = 6.269 seconds
 - PASS - [counter_basic.test_all_channels] duration = 0.661 seconds
 - SKIP - [counter_basic.test_cancelled_alarm_does_not_expire] duration = 0.512 seconds
 - SKIP - [counter_basic.test_late_alarm] duration = 0.512 seconds
 - SKIP - [counter_basic.test_late_alarm_error] duration = 0.512 seconds
 - PASS - [counter_basic.test_multiple_alarms] duration = 0.780 seconds
 - PASS - [counter_basic.test_set_top_value_with_alarm] duration = 1.055 seconds
 - SKIP - [counter_basic.test_short_relative_alarm] duration = 0.517 seconds
 - PASS - [counter_basic.test_single_shot_alarm_notop] duration = 0.860 seconds
 - PASS - [counter_basic.test_single_shot_alarm_top] duration = 0.860 seconds

SUITE PASS - 100.00% [counter_no_callback]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.536 seconds
 - PASS - [counter_no_callback.test_set_top_value_without_alarm] duration = 0.536 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL

```

**Review by dleach02 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Comment by aescolar** [comment]
@henrikbrixandersen 4.0?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen 4.0? 

It's only touching the LPC55S1x SoC family and one associated board and all tests pass. The same nodes are present in other LPC55xxx family SoC devicetrees, so the risk of something breaking is very low. 

I'd like to see it in v3.7.0, but won't push for it.

**Comment by dleach02** [comment]
> > @henrikbrixandersen 4.0?
> 
> It's only touching the LPC55S1x SoC family and one associated board and all tests pass. The same nodes are present in other LPC55xxx family SoC devicetrees, so the risk of something breaking is very low.
> 
> I'd like to see it in v3.7.0, but won't push for it.

I'm fine with it for 3.7.

**Pull request merged**
